### ISSUE TITLE
libwmf.pc only exists in RedHat based distributions

### ISSUE THREAD

**Issue by nieder** [ImageMagick/ImageMagick#10]
On OS X 10.9 with IM 6.9.1-5, configure fails to find libwmf:
~~~~
configure:31879: checking for WMF
configure:31886: $PKG_CONFIG --exists --print-errors "libwmf >= 0.2.8"
Package libwmf was not found in the pkg-config search path.
Perhaps you should add the directory containing `libwmf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libwmf' found
~~~~
libwmf.pc doesn't exist in the standar libwmf library, which is what Fink and MacPorts provide on OS X. Nor does it exist in Debian or [Ubuntu](http://packages.ubuntu.com/wily/amd64/libwmf-dev/filelist).

The WMF check worked at least to 6.9.1-2 when it was using an autotools macro.The check should not depend on a non-standard file that exists only on a very limited set of distributions.

**Comment by urban-warrior** [comment]
Fixed.
