### ISSUE TITLE
Weird blue artifact on -evaluate-sequence median

### ISSUE THREAD

**Issue by TidyMaze** [ImageMagick/ImageMagick#1003]
### Description
When I try to use `-evaluate-sequence median` it outputs a file with blue/purple artifacts.

### Steps to Reproduce
- Prepare a sequence of Tiff images (maybe other formats cause the same issue)
- Run `convert *.tif -evaluate-sequence median OUT.jpg`
- Observe that many parts show blue/purple artifacts/noise

On this image, you can see the issue in trees on left side, on roundabout bushes and on deleted vehicles. For each part where there is an issue, there were 5x more pictures with correct colors in output (taking median should have worked). I used a set of 10 pictures, aligned with hugin align tools [Align_image_stack](https://wiki.panotools.org/Align_image_stack).
Full image exemple : [here](https://i.imgur.com/RHCYLfz.jpg)
Zoomed exemple : [here](https://i.imgur.com/cMKZ3lF.png)

I reproduce this problem with jpg/tif output, and with a different set of pictures.

### System Configuration

- ImageMagick version: Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114
- Environment : Ubuntu 17.10

### Final words

Let me know if I do something wrong, it's the first time I use imagemagick and I may ignore some important things. Thanks

**Comment by fmw42** [comment]
Please post the original TIFF image. Your images are JPGs. The hosting provider may have changed them from TIFF to JPG. We need the original TIFF to check your convert command.
