### ISSUE TITLE
Assertion fails in CopyMagickCLCacheInfo

### ISSUE THREAD

**Issue by wsz** [ImageMagick/ImageMagick#1005]
### Description
[This line of code](https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/opencl.c#L1494) fails when you try to compress [this image](https://i.cubeupload.com/NZy0fa.png) using the following command:
```
magick mogrify \
    -path       /tmp \
    -filter     Triangle \
    -define     filter:support=2 \
    -thumbnail  114x144 \
    -unsharp    0.25x0.25+8+0.065 \
    -dither     None \
    -posterize  136 \
    -quality    82 \
    -define     jpeg:fancy-upsampling=off \
    -define     png:compression-filter=5 \
    -define     png:compression-level=9 \
    -define     png:compression-strategy=1 \
    -define     png:exclude-chunk=all \
    -interlace  none \
    -colorspace sRGB \
    -strip      NZy0fa.png
```
The error message is:
```
magick: MagickCore/opencl.c:1494: CopyMagickCLCacheInfo: Assertion `pixels == info->pixels' failed.
```
I have found this set of options in the following article: [Efficient Image Resizing With ImageMagick](https://www.smashingmagazine.com/2015/06/efficient-image-resizing-with-imagemagick/)

### System Configuration
- ImageMagick version: 7.0.7.23
- OS: ArchLinux
- `ocl-icd` version: 2.2.12
- `opencl-nvidia` version: 390.25
- Graphics card: NVIDIA GeForce 960M GTX

**Comment by dlemstra** [comment]
The OpenCL support for NVIDIA is a bit buggy from time to time and can cause this odd behavior. I think it might be better to disable OpenCL support on your system.

**Comment by wsz** [comment]
You were right. It runs without an error if I disable OpenCL by setting environment variable `MAGICK_OCL_DEVICE=OFF` ([your answer](https://superuser.com/questions/1103574/imagemagick-disable-opencl-on-linux/1104127#1104127)) though it would be nice if ImageMagick could choose a better framework on its own, especially since it does not require a recompilation.
