### ISSUE TITLE
Regression in 336bb3 when reading from fd0 pseudonym

### ISSUE THREAD

**Issue by danieltwagner** [ImageMagick/ImageMagick#1006]
As of 336bb38beecd94390af872fe9c16aa7693a97ac0 the following breaks:
```
$ cat input.tiff | ./magick fd:0 jpeg:fd:1 > output.jpg
magick: Cannot read TIFF header. `/tmp/magick-165626S6-zKgOhNtY' @ error/tiff.c/TIFFErrors/645.
magick: NoDataReturned `0' @ error/fd.c/ReadFDImage/122.
```
However, when reading from pipes using the filename `-` things continue to work as expected:
```
$ cat input.tiff | ./magick - jpeg:- > output.jpg
$
```
The previous commit (3755d2289b032919c065f6ab11ef570063f7f828) works as expected when using `fd0` and `fd1`.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
