### ISSUE TITLE
Conversion 12x slower on 7.0 and 6.9 compared to 6.8

### ISSUE THREAD

**Issue by coffeebite** [ImageMagick/ImageMagick#1007]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
```bash
convert photo.gif -coalesce -resize 16x16 output.gif
```
For the following image, this command takes 1.5s on ImageMagick 6.8.9-10 but 20s on 6.9.7-4 and 7.0.7-24 (the latest) on Ubuntu 16.04.

[https://padlet-uploads.storage.googleapis.com/12/8fcc20926abdeba05ef00e8950b09e80/photo.gif](https://padlet-uploads.storage.googleapis.com/12/8fcc20926abdeba05ef00e8950b09e80/photo.gif)

### Steps to Reproduce
Download the image and run the convert command on an Ubuntu 16.04 machine with ImageMagick 6.8.9-10 and then 7.0.7-24 and compare the results.

### System Configuration

- ImageMagick version: 7.0.7-24
- Environment (Operating system, version and so on): Ubuntu 16.04 Xenial
- Additional information: On a Mac with 7.0.7-24, it seems to complete in 1.5s. The slowdown seems to be a Linux only issue. From what I can tell, there is no GPU acceleration on the Mac.

**Comment by urban-warrior** [comment]
Try this command:

`convert photo.gif -coalesce -resize 16x16 +dither output.gif`

**Comment by coffeebite** [comment]
Thanks for replying. Still extremely slow.

**Comment by urban-warrior** [comment]
We're using ImageMagick 7.0.7-25.  The command runs in a fraction of a second.  Still too slow for you?
```
-> time convert photo.gif -coalesce -resize 16x16 +dither output.gif
0.386u 0.082s 0:00.90 51.1%     0+0k 9232+944io 38pf+0w
```

**Comment by coffeebite** [comment]
Thanks. Which Linux are you on? It is not slow on a Mac for me. Just Debian (both stretch and ubuntu).

**Comment by coffeebite** [comment]
I already did. Not much impact either. Also, on the same machine, 7.0.7-24 is a lot slower than 6.8.9-10 with the exact same configuration. Wondering what changed in 6.9 to cause this slowdown.

**Comment by fmw42** [comment]
Does removing +dither make any difference?

**Comment by coffeebite** [comment]
Not much, no.

**Comment by fmw42** [comment]
Does the speed improve if you output to miff or tiff? It could be in the quantization after the resize.

**Comment by coffeebite** [comment]
Unfortunately, it doesn't. :(

**Comment by fmw42** [comment]
What happens if you remove the -resize? What happens if you replace -resize with -scale?

**Comment by coffeebite** [comment]
Still slow.

**Comment by coffeebite** [comment]
BTW, this is not the behavior for ALL gifs, just a few specific ones. A lot of gifs take comparable time on 6.8.9-10 and 7.0.7-24.

**Comment by fmw42** [comment]
Does this gif have many more frames that the ones that work fine?

**Comment by coffeebite** [comment]
Yes, the slow one has 290 frames. None of the ones that are fine (not fast, but at least comparable across different versions of ImageMagick) have that many.

**Comment by urban-warrior** [comment]
With that many frames, its possible the frames are being pushed to disk rather than memory.  That would certainly slow down processing.  You can determine if that's the case by adding `-debug cache` to your command-line.  Some of the frames may remain in memory but look for certain frames on disk.  Disk is much slower than memory.  See https://www.imagemagick.org/script/architecture.php#tera-pixel for details.

**Comment by coffeebite** [comment]
Sorry for dropping the ball on this. Seeing the same behavior with much fewer frames. Plus I have 1.5GB of memory allocated to ImageMagick. Lastly, its fast in 6.8 but not 6.9 so if it were a memory issue, wouldn't it affect both versions?

I'll continue to test more things and report my findings. Thank you for your replies.
