### ISSUE TITLE
master and ImageMagick-6 branch should be aware of clang's use of libomp

### ISSUE THREAD

**Issue by jwhowarth** [ImageMagick/ImageMagick#101]
Currently, when configure, in both master and ImageMagick-6 branch, is executed against the clang 3.8 compilers, GOMP_LIBS is incorrectly set to -lgomp. Starting with clang 3.8, the -fopenmp option defaults to -fopenmp=libomp to use the LLVM libomp OpenMP library. The configure.ac in both branches should be updated to something like...
```
--- configure.ac	2016-01-23 14:22:10.000000000 -0500
+++ configure.ac.new	2016-01-28 01:01:49.000000000 -0500
@@ -1386,6 +1386,12 @@
 GOMP_LIBS=''
 if test "$enable_openmp" != 'no'; then
   if test "${GCC}" = "yes"; then
+    # Clang 3.8 and later defaults to the LLVM OpenMP implementation
+    if test "x$GOMP_LIBS" = x ; then
+      if $CC --version 2>&1 | grep clang > /dev/null ; then
+        AC_CHECK_LIB(omp,omp_get_num_procs,GOMP_LIBS="-lomp",,)
+      fi
+    fi
     # Open64 (passes for GCC but uses different OpenMP implementation)
     if test "x$GOMP_LIBS" = x ; then
       if $CC --version 2>&1 | grep Open64 > /dev/null ; then
```
to insure that GOMP_LIBS is correctly set to -lomp. 

Note that although prior clang releases defaulted to -fopenmp=libgomp, the -fopenmp=libgomp support is effectively a no-op as the clang compiler doesn't emit any code generation for openmp support in that mode. This is also true for clang 3.8 and clang trunk for -fopenmp=libgomp as the required gomp compatibility code isn't on their TODO list.

**Comment by urban-warrior** [comment]
We added your patch to the master and ImageMagick-6 branched.  Look for a release distribution in about 10 days.
