### ISSUE TITLE
Unable to add png, gif and tif delegate to the convert binary

### ISSUE THREAD

**Issue by nik6018** [ImageMagick/ImageMagick#1010]
Hi,

This is my first message to the list, very happy to do so.

I am trying to compile ImageMagick with support for jpeg, png, gif, tif delegates.

Though the compiling finishes without any error, it does not work. When I try to check the delegates the compiled package supports is only "bzlib jpeg ltdl zlib".

```
[root@localhost /]# /usr/local/apps/imagemagick/bin/convert -version
Version: ImageMagick 7.0.7-25 Q16 x86_64 2018-03-05 http://www.imagemagick.org
Copyright: Â© 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP
Delegates (built-in): bzlib jpeg ltdl zlib
```

I am unable to add png, gif & tif delegate to the binary. I have tried googling for hours on how to add it but not able to find solution to the same.

Here is my configure command:

```
LDFLAGS="-L/usr/local/apps/lib" CPPFLAGS="-I/usr/local/apps/include" ./configure --prefix=/usr/local/apps/imagemagick
--enable-shared=yes \
--enable-delegate-build \
--with-modules=yes \
--with-bzlib=yes \
--with-jpeg=yes \
--with-png=yes \
--with-tiff=yes \
--with-xml=yes \
--with-zlib=yes && make && make install >> $LOG 2>&1
```

Please if anyone could help with this.

**Comment by urban-warrior** [comment]
Carefully inspect the $LOG output.  Each library is validated before it is accepted by the ImageMagick configure script.   Validation requires the configure script find the particular delegate libraries headers and the binary library.  If they cannot be found, the delegate library fails validation and support for the respective image format is not included with ImageMagick.  A summary of which delegate libraries that fail to validate are included in the last 50 or so lines of $LOG.  Here is an example of a delegate library that was validated and one that failed to validate:

```
  ...
  WEBP              --with-webp=yes             yes
  WMF               --with-wmf=yes              no
  ...
```
This means that for this instance of ImageMagick, you can expect to be able to read and write images in the Google WEBP image format but you will be unable to read or write images in the WMF format.

**Comment by nik6018** [comment]
Thanks for the reply @urban-warrior 

While compiling I received what you were describing:

![check](https://user-images.githubusercontent.com/16150710/37018933-41edc316-213c-11e8-95b8-c76dcaf543ba.png)

How can I make sure that the configure script gets the PNG library binary? as I have passed the LDFLAG where my library resides.

I am really confused as the JPEG library resides in the same directory(/usr/local/apps/lib) and the JPEG delegate is getting accepted and PNG is not.

**Comment by fmw42** [comment]
Your install of libpng may not have worked successfully. It may have needed some other dependency. Check the config.log file for your install of libpng and see if there are any errors. Or try to install it again and make sure it has no errors. Then install ImageMagick again.

**Comment by nik6018** [comment]
I have checked the config.log for libpng and there seem to be no issues 

Here you can check the screenshot:
![screenshot 33](https://user-images.githubusercontent.com/16150710/37138544-7824a73e-22d0-11e8-9e39-bc2a3aac5531.png)

Following is my configure command for libpng:
```
LDFLAGS="-L/usr/local/apps/lib" CPPFLAGS="-I/usr/local/apps/include" ./configure --prefix=/usr/local/apps \
--with-sysroot=/usr/local/apps \
--with-zlib-prefix=/usr/local/apps \
--with-pkgconfigdir=/usr/local/apps/lib/pkgconfig && make && make install >> $LOG 2>&1
```

**Comment by milo-trujillo** [comment]
I can confirm the above problem. _Other_ programs can link against libpng, it's certainly installed correctly, but ImageMagick doesn't recognize it. Any ideas from the community? ImageMagick is pretty limited without support for common file formats...

**Comment by fmw42** [comment]
Is /usr/local/apps/lib in your PATH environment variable?

**Comment by milo-trujillo** [comment]
No - I am on MacOS, and there is no /usr/local/apps directory.

**Comment by fmw42** [comment]
You wrote: 

> LDFLAGS="-L/usr/local/apps/lib"

Typically one installs in /usr/local/lib

If on MacOSX, you might want to do what I do -- namely, install all delegates from MacPorts and then instal IM from source. See https://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=29100.  Alternately, install IM for Mac OSX from Homebrew. It typically comes with delegates. Or if on Mac OSX High Sierra, install from the ImageMagick binary at https://imagemagick.org/script/download.php#macosx

**Comment by fmw42** [comment]
Are you sure that the ImageMagick binary did not include PNG. That would be very surprising.
