### ISSUE TITLE
Use x265 or openHEVC to replace libde265

### ISSUE THREAD

**Issue by zhaoqingma** [ImageMagick/ImageMagick#1011]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hi,
I want to use ImageMagic to decode HEIF images.  However, it seem ImageMagic requires delegate libde265 for HEIF image.
Is it possible to use x265 or openHEVC to replace libde265?
The reason is libde265 is licensed under LGPL v3, I want to avoid GPL/LGPL v3 in my project.  And since x265 and openHEVC are licensed under GPL/LGPL v2, they are good for me.

Thanks!

- ImageMagick version: 7.0.7-24
- Environment (Operating system, version and so on): linux
- Additional information:

**Comment by urban-warrior** [comment]
HEIC is a contributed coder that requires libde265.  The ImageMagick development team did not write it nor do we maintain it other than ensuring it works with each ImageMagick release and patching if a security issue is posted.  If you or another user wants to contribute a modified HEIC coder, one that depends on x265 or openHEVC, post your pull request to https://github.com/ImageMagick/ImageMagick/pulls and we will consider including it in the next point release of ImageMagick

**Comment by mattwaltbriggs** [comment]
+1
The source code for libde265 in github does not appear to compile under macOS either.

**Comment by fancycode** [comment]
libheif supports registering arbitrary plugins to do the actual encoding / decoding (see https://github.com/strukturag/libheif/blob/9031b5388bdaf7d1d4c85071c78afd77405068a4/libheif/heif.h#L875 and https://github.com/strukturag/libheif/blob/9031b5388bdaf7d1d4c85071c78afd77405068a4/libheif/heif_plugin.h), so you could write your own decoder plugin that is not using libde265.
