### ISSUE TITLE
compare always return 1 for two identical images

### ISSUE THREAD

**Issue by stfairy** [ImageMagick/ImageMagick#1012]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Running `compare` on two identical images return 1 as exit code.

### Steps to Reproduce

Download the latest source and compile from it.  After that run

```
$ identify -version
Version: ImageMagick 7.0.7-25 Q16 x86_64 2018-03-06 http://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): jbig jng jpeg lzma png tiff x zlib
$ compare rose.jpg rose.jpg diff.png
$ echo $?
1
```

`diff.png` is totally transparent.  I expect `compare` to return 0 as documented in `man compare`.

`rose.jpg` is attached:

![rose](https://user-images.githubusercontent.com/196279/37024624-51e14c98-2164-11e8-8c08-d61f0544ea1e.jpg)

I've also tried many other images (mostly PNG files) and `compare` always return 1.

### System Configuration

- ImageMagick version: 7.0.7-25
- Environment (Operating system, version and so on): Ubuntu 16.04.4 LTS (4.13.0-36-generic #40~16.04.1-Ubuntu SMP x86_64)
- Additional information: None.

**Comment by stfairy** [comment]
@urban-warrior Thanks for the explanation.  Indeed, I can resolve the issue by adding `-metric AE`.

**Comment by stephenhuh** [comment]
to be honest @xjia1 i dont think this is expected behavior. for metrics like SSIM it's strange that the exit code is nonzero and instead one for a comparison of the same image. while i understand the default behavior, the exit code in my opinion should follow a stable convention IMO

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Comment by stephenhuh** [comment]
Wow. Thank you @urban-warrior this may be the fastest issue comment to resolution proposal speed ive seen. Really appreciate the commitment to quality!
