### ISSUE TITLE
floodfill broken in both IM6 and IM7

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#1014]
A recent version has broken flood filling. Below a minimal example which *should* fill the whitespace:

```cpp
#include <Magick++.h>

using namespace Magick;

int main(){
  std::list<Image> images; 
  readImages( &images, "logo:");

  double fuzz = 1000;
  for_each ( images.begin(), images.end(), Magick::colorFuzzImage( fuzz ));
  for_each ( images.begin(), images.end(), Magick::floodFillColorImage(
      Magick::Geometry("1x1"), "orange"));

  writeImages( images.begin(), images.end(), "output.png" );
}

```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
It looks like we broke this when we met @jeroen. The default color `Color()` should be marked as invalid. But the alpha channels was inconsistent between IM6 and IM7 so I added a patch to make sure it had the same value. But my change now makes the color valid while it is invalid. This new patch should resolve that issue.

**Comment by jeroen** [comment]
Thanks for fixing!
