### ISSUE TITLE
identify: insufficient image data in file `./image.pcx' @ error/pcx.c/ReadPCXImage/405.

### ISSUE THREAD

**Issue by bdoss** [ImageMagick/ImageMagick#1015]
It seems like this calculation is improperly throw a CorruptImageError for otherwise valid PCX files:

https://github.com/ImageMagick/ImageMagick/blob/4cd61940efb573150303c73c2be4079133da042f/coders/pcx.c#L404-L405

I've attached a [zip file](https://github.com/ImageMagick/ImageMagick/files/1787856/test-samples.zip) with two 8-bit PCX example files. The file green100.pcx will identify properly, while green250.pcx will fail with a CorruptImageError exception.

From what I can tell, it seems like this was introduce in 7.0.7-12 by https://github.com/ImageMagick/ImageMagick/commit/1cbaa9f61214d0695870cf9e85b5a859b76da9bc

**Comment by raeesaa** [comment]
In what version was this issue fixed?
