### ISSUE TITLE
Errors in heic.c/ParseIpmaAtom when reading conformance files

### ISSUE THREAD

**Issue by silverbacknet** [ImageMagick/ImageMagick#1016]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
It seems like HEIF/HEIC parser might be adapted to only work with Apple iPhone output; it won't accept any of the official conformance files for the format, which are likely using more features of the format. Even simple ones with only a single included image won't read, though. I don't have Apple HEIC files to test, only the conformance ones for now.

### Steps to Reproduce
Download any of the files from the official Nokia repository and try to read them with IM:
https://github.com/nokiatech/heif_conformance/tree/master/conformance_files

They all give the error "ImproperImageHeader `item id is incorrect' @ error/heic.c/ParseIpmaAtom/529"

### System Configuration

- ImageMagick version: 7.0.7
- Environment (Operating system, version and so on): Windows 10 1709 x64
- Additional information: Tried 7.0.7 Q16, Q16 HDRI, Q8.

**Comment by urban-warrior** [comment]
You are correct, we currently only read Apple iPhone HEIC image files.  We will work on conformance images over time.  In the mean-time, feel free to submit a pull request if you or another user wants to contribute a patch to permit reading the conformance images.

**Comment by silverbacknet** [comment]
Thank you. I'll give hacking at it some effort this weekend, now that I have the specs handy.

**Comment by ddor254** [comment]
i see that this issue was fixes in Version: ImageMagick 7.0.7-29, but this version does not have a proper download in order to build it manually, just clone master and build from there.

also it is important to say that this error gets thrown but the convert **succeed**. is that the proper behavior ?

**Comment by silverbacknet** [comment]
It's not fixed in 7.0.7-29, all that's fixed in this release is lots of little memory initialization bugs (so far). Supporting HEIC in general is still another big project, and I'm too burnt out from other projects to do much.
