### ISSUE TITLE
Since upgrading from 6.9.9.34 to 6.9.9.36 a bug regarding drawing with opacity has been introduced

### ISSUE THREAD

**Issue by downhiller** [ImageMagick/ImageMagick#1021]
### Prerequisites

- [ x] I have written a descriptive issue title
- [ n/a] I have verified that I am using the latest version of ImageMagick
- [ x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In php, this very simple code used to draw a translucent rectangle onto a photo, but since performing the update the rectangle is now black:

### Steps to Reproduce
`$draw = new ImagickDraw();`
`$draw->setFillColor('#000000');`
`$draw->setFillOpacity(0.5);`
`$draw->rectangle(0, $bottom, $width, $bottom + $height);`
`$photo->drawImage($draw);`

### System Configuration
PHP 7.2 on Centos 6

**Comment by downhiller** [comment]
A fix appears to be to switch the two setFill lines, so change from the above to:

`
$draw->setFillOpacity(0.5);
$draw->setFillColor('#000000');
`

**Comment by urban-warrior** [comment]
Does this work?

`$draw->setFillColor('#00000088');`

**Comment by downhiller** [comment]
It does, which makes me feel a bit silly since I had tried #88000000 but not the other way around!

Doesn't change the fact that some perfectly valid code that used to work had stopped working without warning though.
