### ISSUE TITLE
when i use command line to gen psd file, but i cant control a position of per image

### ISSUE THREAD

**Issue by XP1988** [ImageMagick/ImageMagick#1022]
### Prerequisites

- [ ]when i use command line to gen psd file, but i cant control a position of per image.

the cmd  as follow:
convert back.png -adjoin back.png title.png -density 72  -gravity southeast -geometry 120x30+20+20    final.psd

**Comment by XP1988** [comment]
-geometry 120x30+20+20 , but this config cant be useful.

**Comment by XP1988** [comment]
@alex @mirakui @Schnouki @tpett @emcconville

**Comment by fmw42** [comment]
I am not sure what you are trying to do. But if I am correct, try this 

Unix syntax:

`convert back.png \( title.png -resize 120x30 \) -gravity southeast -geometry +20+20 -compose over -composite final.psd`

Windows syntax:

`convert back.png ( title.png -resize 120x30 \ -gravity southeast -geometry +20+20 -compose over -composite final.psd`

If this is not what you want, then please clarify how you want them combined. Also if possible provide links to your input images.

**Comment by ronyuzhang** [comment]
i've had this problem,too. your scrtipt command can only gen psd file that are not layered. i need a psd file which are layered and component'position can be set by command line.

**Comment by ronyuzhang** [comment]
@fmw42

**Comment by dlemstra** [comment]
@ronyuzhang Can you please stop with adding new responses with names of people you want to take a look at this.

**Comment by fmw42** [comment]
Post your input images and requirements for offsets and also if possible the corresponding proper PSD file

**Comment by XP1988** [comment]
@fmw42 
You can try like this:
download:
background.jpg https://ss2.bdstatic.com/70cFvnSh_Q1YnxGkpoWK1HF6hhy/it/u=3737501919,2021289867&fm=27&gp=0.jpg
title.png http://d.lanrentuku.com/down/png/1712/12fugu-christmas-png/12christmas-png-11.png
The command:
convert background.jpg  background.jpg title.png -density 72  -gravity southeast -geometry 120x50+250+20  -adjoin  final.psd
'-gravity southeast -geometry 120x50+250+20' don't take effect

Effect i want like this,but the file is PSD and has two layers.
convert  background.jpg  -compose atop title.png -density 72  -gravity southeast -geometry 120x50+250+20 -composite final.png

**Comment by fmw42** [comment]
Post the PSD file you want me to make from your two other images.
