### ISSUE TITLE
ImageMagick6: opencl.c: NULL pointer dereference not fixed completely

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1024]
https://github.com/ImageMagick/ImageMagick/blob/ImageMagick-6/magick/opencl.c#L895
I think NULL ptr dereference can still happen there. (issue #792)

**Comment by dlemstra** [comment]
Thanks for reporting this. I just pushed a patch to make sure this will be resolved in the next release.

**Comment by pgajdos** [comment]
Thanks!
