### ISSUE TITLE
"improper image header" for XBM tests in tests/validate-formats-disk

### ISSUE THREAD

**Issue by sharkcz** [ImageMagick/ImageMagick#1029]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I see following errors
````
  test 858: XBM/Undefined/TrueColor/8-bits... fail @ tests/validate.c/ValidateImageFormatsInMemory/1653.
    reason:improper image header `/tmp/magick-3319046LkghGTCi8vq2' @ error/xbm.c/ReadXBMImage/279
  test 859: XBM/Undefined/TrueColorAlpha/8-bits... fail @ tests/validate.c/ValidateImageFormatsInMemory/1653.
    reason:improper image header `/tmp/magick-3319046LkghGTCi8vq2' @ error/xbm.c/ReadXBMImage/279
...
````
when running the test suite on a system with large PIDs. The problem is the check for 32 characters on https://github.com/ImageMagick/ImageMagick/blob/master/coders/xbm.c#L238 iff the temporary filename is generated on a system with current PID >= 1000000. I'll attach the created temp XBM file.

### Steps to Reproduce

- get to a high enough PID
- run make check

### System Configuration

- ImageMagick version: master branch
- Environment (Operating system, version and so on): Fedora 27
- Additional information:

**Comment by sharkcz** [comment]
[magick-test.zip](https://github.com/ImageMagick/ImageMagick/files/1824948/magick-test.zip)

**Comment by sharkcz** [comment]
You can reproduce that easily with
````
[dan@eagle tmp]$ identify magick-test.xbm 
identify: improper image header `magick-test.xbm' @ error/xbm.c/ReadXBMImage/281.
````

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
