### ISSUE TITLE
FTBFS: i386 (maybe due to coprocessor and double extension)

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#1034]
Imagemagick FTBFS under i386/ia64

It smell like a subtle bug in coprocessor arithmetic, see buildd
https://buildd.debian.org/status/package.php?p=imagemagick&suite=sid

**Comment by urban-warrior** [comment]
It looks like Magick++/tests/tests.tap is failing, test 2.  That is likely the attributes unit test group.  Can you post Magick++/tests/tests.log.  It looks like one of the `attributes` unit test group is failing, we need to confirm and determine which individual test in the group is actually failing.

**Comment by urban-warrior** [comment]
IM 6.9.9-40 will be release likely today.  Try to build and let us know if the unit tests pass.

**Comment by bastien-roucaries** [comment]
Still fail
Line: 160, backgroundColor default (#FFFFFFFFFFFF) is incorrect
Testing throwing and catching exceptions. A program crash or a message
that the exception was not caught indicates a test failure.  A properly
formatted exception message indicates success:
Caught exception, good!:
  "attributes: unable to open image `foo': No such file or directory @ error/blob.c/OpenBlob/2761"
Line: 1074, pixelColor default (#FFFF00000000) is not canvas color (#FFFF00000000) as expected
2 failures
not ok

**Comment by bastien-roucaries** [comment]
Ping ?

**Comment by bastien-roucaries** [comment]
Ping ?

**Comment by urban-warrior** [comment]
We ran the unit tests under i386 Windows and they passed.  This is the only 32-bit host we have access to.  We do not have a speculative patch which means we must reproduce the problem before we can issue a proper patch.  Can we get access to a host where the problem exhibits so we can properly debug this issue?

**Comment by bastien-roucaries** [comment]
Yes you can, see pbuilder for debian for instance. But I think the best thing to do is to become a debian maintainer for imagemagick.

We have access to a huge list of machine and arch and it will ease you to debug stuff.

Moreover, you will access to cross distro security bug.

I can sponsor you if needed and you could get access to buildd if needed.

you only need to get your gpg key signed by two 

Program to acess to porter box is here https://dsa.debian.org/doc/guest-account/
how to become a DM is here https://wiki.debian.org/DebianMaintainer

You need to need to get you key signed and unfortunalty you will need to get outside WY

Bastien

**Comment by bastien-roucaries** [comment]
If needed we can arrange a dd to your home, in order to sign your keys, or when you go to travel.
It will also improve the ring of trust of your key but I understand.

Do you have acess to pbuilder ? What is your distro ? A i386 chroot is quite easy to setup, and I could help

**Comment by urban-warrior** [comment]
Our primary development machines are Fedora, CentOS, Ubuntu, and Windows.  We use these simply because that's what's available to us.  We've never used Debian nor do we know what pbuilder is.  Ideally, we could provide a SSH public key, we would log into a Debian host somewhere where we could build ImageMagick, run the unit tests, reproduce the problem, and apply a patch such that the unit tests pass.  We estimate the duration of just a couple of hours.  What is the path of least resistance to get this issue fixed?

**Comment by bastien-roucaries** [comment]
Because your key is not trusted, you could not get under debian (best will have to a ssh key assiociated to your gpg key). But we understand your lack of time, thus they are an alternative

You could use pbuilder-dist
pbuilder-dist precise i386 create
pbuilder-dist precise i386 update
pbuilder-dist precise i386 login

you will get in a i386 chroot, where you could do what you want. You should change precise to your target dsitribution (last unbuntu).

The failled build make check is HDRI Q16

**Comment by bastien-roucaries** [comment]
(pbuilder dist is available under ubuntu)

**Comment by bastien-roucaries** [comment]
when login on pbuilder do apt-get build-dep imagemagick

**Comment by deep-42-thought** [comment]
I get the exact same error in archlinux32. We compile in a setarch'ed systemd-nspawn container, maybe that is easier for you to facilitate? Additionally, we also have a vagrant image of archlinux32 (Run `vagrant init archlinux32/archlinux32` - it's a bit outdated, you need to run `sudo pacman -Syu` first inside the vm), where you could hunt for the error yourself.

**Comment by bastien-roucaries** [comment]
We get a patches on the debian sides:

Do you confirm it is the real fix or they are a problem on your API that does not convert to string ?
'''
--- a/Magick++/tests/attributes.cpp.orig	2018-03-18 15:15:56.000000000 +0100
+++ b/Magick++/tests/attributes.cpp	2018-05-08 16:06:41.820001000 +0200
@@ -154,7 +154,7 @@
     //
 
     // Test default value.
-    if ( image.backgroundColor() != ColorRGB("white") )
+    if ( image.backgroundColor() != string(ColorRGB("white")) )
       {
 	++failures;
 	cout << "Line: " << __LINE__ << ", backgroundColor default ("
@@ -1068,7 +1068,7 @@
     // pixelColor
     //
     // Test default
-    if ( image.pixelColor(40,60) != canvasColor )
+    if ( image.pixelColor(40,60) != string(canvasColor) )
       {
 	++failures;
 	cout << "Line: " << __LINE__ << ", pixelColor default ("
'''

**Comment by dlemstra** [comment]
@deep-42-thought and @bastien-roucaries Can you still reproduce this issue?

**Comment by deep-42-thought** [comment]
here, all unit tests pass now (version 7.0.8-14) - thanks
