### ISSUE TITLE
Convert command error if target image parent directory ends with dot

### ISSUE THREAD

**Issue by Pr1st0n** [ImageMagick/ImageMagick#1035]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Convert command fails if target image parent folder name ends with dot.
Problem occures only on linux (debian) system, on windows (10) system everything works as expected.

```convert: unable to open image 'test./logo.gif': No such file or directory @ error/blob.c/OpenBlob/3375.```

https://github.com/ImageMagick/ImageMagick/blob/c78be6be9f7000a791b40784b80c33d62936eca8/MagickCore/blob.c#L3375

### Steps to Reproduce
    convert logo.gif test./logo.gif

### System Configuration

- ImageMagick version: master branch
- Environment (Operating system, version and so on): Windows 10 => Docker for Windows (Debian 8.8 container)
- Additional information: Problem occurres in mounted directory

**Comment by urban-warrior** [comment]
Unfortunately we cannot reproduce the problem you reported.  We're using the latest release of ImageMagick under Fedora, Ubuntu, and CentOS and your command completes without complaint and `test./logo.gif` is created as expected.

**Comment by Pr1st0n** [comment]
Sorry, I should mention that I'm using docker. I've updated the question. Indeed the problem is not reproduce in basic container directories. Only in mounted one.
Any ideas for solution or workaround?

**Comment by urban-warrior** [comment]
We would need to reproduce the problem before we could offer any advice.  Unfortunately we do have access to Docker nor Debian.
