### ISSUE TITLE
null pointer dereference in RecordProfileData

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#1037]
Version: ImageMagick 7.0.7-28
Here is the critical code in function RecordProfileData:
```
else
    {
      profile_record=AcquireMagickMemory(sizeof(*profile_record));    //2739
      (void) memset(profile_record,0,sizeof(*profile_record));    //2740
      profile_record->kernel_name=name;
      device->profile_records=ResizeMagickMemory(device->profile_records,(i+2)*
        sizeof(*device->profile_records));
      device->profile_records[i]=profile_record;
      device->profile_records[i+1]=(KernelProfileRecord) NULL;
    }
```
line 2739 AcquireMagickMemory may return null pointer to “profile_record”, so line 2740  may cause null pointer dereference.
Credit : ADLab of Venustech

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
