### ISSUE TITLE
null pointer dereference in ParseIpcoAtom

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#1038]
Version: ImageMagick 7.0.7-28
Here is the critical code in function ParseIpcoAtom:
```
    prop->data = (uint8_t *) AcquireMagickMemory(prop->size);        //408
    if (DBChop(&propDb, db, prop->size) != MagickTrue) {
      ThrowAndReturn("incorrect read size");
    }
    memcpy(prop->data, propDb.data, prop->size);        //412
```
line 408 AcquireMagickMemory may return null pointer to “prop->data”, so line 412  may cause null pointer dereference.
Credit : ADLab of Venustech

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
