### ISSUE TITLE
Memory leak in WriteFITSImage 

### ISSUE THREAD

**Issue by jgj212** [ImageMagick/ImageMagick#1045]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Memory leak in WriteFITSImage 

### Steps to Reproduce
```
  fits_info=(char *) AcquireQuantumMemory(FITSBlocksize,sizeof(*fits_info)); 	// line 661, allocation for fits_info
  if (fits_info == (char *) NULL)
    ThrowWriterException(ResourceLimitError,"MemoryAllocationFailed");
  (void) memset(fits_info,' ',FITSBlocksize*sizeof(*fits_info));
  /*
    Initialize image header.
  */
  image->depth=GetImageQuantumDepth(image,MagickFalse);
  image->endian=MSBEndian;
  quantum_info=AcquireQuantumInfo(image_info,image);
  if (quantum_info == (QuantumInfo *) NULL)
    ThrowWriterException(ResourceLimitError,"MemoryAllocationFailed");   		// line 672, memory leak as not free fits_info
```

### System Configuration
- ImageMagick version: 7.0.7-28
- Environment (Operating system, version and so on): Ubuntu14.04 x86_64
- Additional information:

Credit: ADLab of Venustech

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
