### ISSUE TITLE
Memory leak in WritePDBImage 

### ISSUE THREAD

**Issue by jgj212** [ImageMagick/ImageMagick#1050]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Memory leak in WritePDBImage 

### Steps to Reproduce
```
  runlength=(unsigned char *) AcquireQuantumMemory(9UL*packets,  			//line 846, allocation for runlength
    image->rows*sizeof(*runlength));
  buffer=(unsigned char *) AcquireQuantumMemory(512,sizeof(*buffer));
  scanline=(unsigned char *) AcquireQuantumMemory(image->columns,packet_size*
    sizeof(*scanline));
```

```
  quantum_info=AcquireQuantumInfo(image_info,image);
  if (quantum_info == (QuantumInfo *) NULL)
    ThrowWriterException(ResourceLimitError,"MemoryAllocationFailed");  	//line 871, memory leak as not free runlength
```

### System Configuration
- ImageMagick version: 7.0.7-28
- Environment (Operating system, version and so on): Ubuntu14.04 x86_64
- Additional information:

Credit: ADLab of Venustech

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
