### ISSUE TITLE
Problem installing from source with lzma support

### ISSUE THREAD

**Issue by jeffmcneill** [ImageMagick/ImageMagick#1055]
The most recent version of ImageMagick6 and 7 result in a make error running the installation using Chrome Brew on ChromeOS, using an Asus Flip C101PA (new). Since this previously worked on a different Chromebook, it may be that the lmza library or some other dependency has broken rather than ImageMagick itself.

Here is the error message:
~~~
MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `lzma_easy_encoder'
MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `lzma_code'
MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `lzma_auto_decoder'
MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `lzma_end'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:7057: utilities/magick] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/local/tmp/crew/ImageMagick-7.0.7-27.tar.xz.dir/ImageMagick-7.0.7-27'
make: *** [Makefile:5185: all] Error 2
imagemagick7 failed to install: `make V=0 -j6` exited with 2
~~~

I've previously submitted changes to three files to update to the current versions available from ImageMagick, however I've also tested with earlier versions found on archived ftp locations, with the same error message.

## Versions and system information

~~~
chromebrew: 0.4.3

CHROMEOS_ARC_ANDROID_SDK_VERSION=25
CHROMEOS_ARC_VERSION=4613139
CHROMEOS_AUSERVER=https://tools.google.com/service/update2
CHROMEOS_BOARD_APPID={564AC308-CBD5-485D-9EF5-EB97DBB5F264}
CHROMEOS_CANARY_APPID={90F229CE-83E2-4FAF-8479-E368A34938B1}
CHROMEOS_DEVSERVER=
CHROMEOS_RELEASE_APPID={564AC308-CBD5-485D-9EF5-EB97DBB5F264}
CHROMEOS_RELEASE_BOARD=bob-signed-mpkeys
CHROMEOS_RELEASE_BRANCH_NUMBER=76
CHROMEOS_RELEASE_BUILDER_PATH=bob-release/R64-10176.76.0
CHROMEOS_RELEASE_BUILD_NUMBER=10176
CHROMEOS_RELEASE_BUILD_TYPE=Official Build
CHROMEOS_RELEASE_CHROME_MILESTONE=64
CHROMEOS_RELEASE_DESCRIPTION=10176.76.0 (Official Build) stable-channel bob
CHROMEOS_RELEASE_NAME=Chrome OS
CHROMEOS_RELEASE_PATCH_NUMBER=0
CHROMEOS_RELEASE_TRACK=stable-channel
CHROMEOS_RELEASE_VERSION=10176.76.0
DEVICETYPE=CHROMEBOOK
GOOGLE_RELEASE=10176.76.0
~~~

I was able to get this compiled when using the `- without-lzma` switch. 

I'm pretty sure that the file with the problem is with either `/coders/miff.c` and/or `/coders/tiff.c`

However, the problem could be upstream with `lzma` since I've tried earlier versions and they create the same error message, whereas before it worked (albeit on a different machine, but still ChromeOS).
- https://github.com/ImageMagick/ImageMagick/blob/dd30840686c40071e11a22818ebd9f2728a96f2f/coders/miff.c
- https://github.com/ImageMagick/ImageMagick/blob/c3e7c6db0efd50a9bf9113d081bde0c5e9c45a17/coders/tiff.c

These seem to be the only files actually calling `lzma`.

**Comment by urban-warrior** [comment]
Under Fedora, Ubuntu, and CentOS 7, the latest ImageMagick releases build without complaint with the LZMA delegate library.  Check `Makefile`.  We have

```
LZMA_LIBS = -llzma
...
coders_miff_la_LIBADD = $(MAGICKCORE_LIBS) $(LZMA_LIBS) $(ZLIB_LIBS) $(BZLIB_LIBS)
```
If you have something similar, perhaps you have a toolchain problem.

**Comment by jeffmcneill** [comment]
There is now a binary for `ImageMagick` available in `crew` which works for me. Also I noticed that `lzma` has been updated upstream.
