### ISSUE TITLE
montage.t fails completely for i586

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1059]
I get with ImageMagick-7.0.7-28, i586:

1..19
$montage=$images->Montage( background=>'#696e7e' )
ReadImage()
Test 1, signatures do not match.
     Expected: d29f905749426e5491bbd8c4f58b7c14dc1a72250632b7e7b542910e0cbb7c77
     Computed: 92ba8d258c6b9030582db4c5c910e5f4dd1e9e8602982536e9ec2c0d8df76a47
     Depth:    16
not ok 1
$montage=$images->Montage( background=>'#696e7e',  geometry=>'90x80+5+5>', gravity=>'Center' )
ReadImage()
Test 2, signatures do not match.
     Expected: 21ab4077722e45db67c945b2364cfc1365d3f939d57fc6fb2c7b77f161381c2e
     Computed: 3bb285a0229e9e2b208afec21d57cbbe5170d7da4325192cdb5487d409e89eac
     Depth:    16
not ok 2
$montage=$images->Montage( background=>'#696e7e',  geometry=>'90x80+5+5>', gravity=>'NorthWest' )
ReadImage()
Test 3, signatures do not match.
     Expected: a518ad6aa1c3ad2b117864525d610481c1b3b9ead2c624c773fb427f85ef897b
     Computed: d15b6c1eab8199e55757cf39aee98c5a3be60c4e4b0e1217c22026ba66caea11
     Depth:    16
not ok 3
$montage=$images->Montage( background=>'#696e7e',  geometry=>'90x80+5+5>', gravity=>'North' )
ReadImage()
Test 4, signatures do not match.
     Expected: 4126725283eb699545d755a6b30c5fc6cee9ac16a1e8310cdbbedcbd054bebf6
     Computed: 22abf5559e1447a2fceffda0f085e2b6323e176b5985fc8b13f28acb614be785
     Depth:    16
not ok 4
$montage=$images->Montage( background=>'#696e7e',  geometry=>'90x80+5+5>', gravity=>'NorthEast' )
ReadImage()
Test 5, signatures do not match.
     Expected: e144c8d0da144864063753903838a286d46da56ca9ea0ce0b6080f84c6feac6c
     Computed: 0d452b2da257a9ee2d9a04dc74208c73eaebab84e22467c9ec87cd5c090c5189
     Depth:    16
not ok 5
$montage=$images->Montage( background=>'#696e7e',  geometry=>'90x80+5+5>', gravity=>'West' )
ReadImage()
Test 6, signatures do not match.
     Expected: 67286cf1ed572e836f6b67c5d733a039bba9e6a7ef18d25397e46c17223b206f
     Computed: 05bae3f904fa02efb41a799b3f6ab3306e3fb81e36de1db7c007f765216045fe
     Depth:    16
not ok 6
$montage=$images->Montage( background=>'#696e7e',  geometry=>'90x80+5+5>', gravity=>'East' )
ReadImage()
Test 7, signatures do not match.
     Expected: decf855bf26dfc3f7401769a09e302d8bac53cba6c27fd456cdfbc35e494be01
     Computed: f163f6b5614c0775ba24be21fc333cbf7c0b7fc1e7a2e451be50ac53d205115a
     Depth:    16
not ok 7
$montage=$images->Montage( background=>'#696e7e',  geometry=>'90x80+5+5>', gravity=>'SouthWest' )
ReadImage()
Test 8, signatures do not match.
     Expected: 848fda241866b1a191ab4794b42272b5756dbeacac5b58ef5227a34a8c72817d
     Computed: ce38408fc88329bf58d7c0aaf3659dedf4bcf2d77a7558ee27b53255e7d0eaa6
     Depth:    16
not ok 8
$montage=$images->Montage( background=>'#696e7e',  geometry=>'90x80+5+5>', gravity=>'South' )
ReadImage()
Test 9, signatures do not match.
     Expected: f5cccb291b3bea8cb62e5cd7a6c8e154eedfd8e12c20409a8e663231e62411c4
     Computed: 613f4cae8e89076bc596656af043c5e1eb1bfdd6d428dbe9f4457ae0f22b8cf3
     Depth:    16
not ok 9
$montage=$images->Montage( background=>'#696e7e',  geometry=>'90x80+5+5>', gravity=>'SouthEast' )
ReadImage()
Test 10, signatures do not match.
     Expected: a19748d933fefe536b29b8ba98ce0024e3f2dc98102a1f56307a229bc3042f1c
     Computed: fe7d7998cbf08790ed60da0d7c650bab839456c40a195a1c5289197e29edea67
     Depth:    16
not ok 10
$images->Set(bordercolor=>'blue', mattecolor=>'red')
$montage=$images->Montage( background=>'#696e7e',  tile=>'4x4', geometry=>'90x80+3+3>', frame=>'8x10',
  borderwidth=>'0', gravity=>'Center', background=>'gray' )
ReadImage()
Test 11, signatures do not match.
     Expected: dcfa6c2bc0e20ff0b5dba464559a1e106e605ec456c21c1205a53e478e4f3e02
     Computed: 7ebcd395a0e50d0672e60f8d5d72bcdb85aec5390c27a5b4e4daf865b2125828
     Depth:    16
not ok 11
$images->Set(bordercolor=>'blue', mattecolor=>'red')
$montage=$images->Montage( background=>'#696e7e',  tile=>'4x4', geometry=>'90x80+6+6>', frame=>'8x10',
  borderwidth=>'0', gravity=>'Center', shadow=>'True',background=>'gray' )
ReadImage()
Test 12, signatures do not match.
     Expected: b3b7a530270164b4c5e391ac8080736a901428e5f650694170969fd292559317
     Computed: 512355652abfbe2bd250e5c6373c3a7dcfc798f18a2b2ba0e2d443a72e4f8f58
     Depth:    16
not ok 12
$images->Set(bordercolor=>'blue', mattecolor=>'red')
$montage=$images->Montage( background=>'#696e7e',  tile=>'4x4', geometry=>'90x80+6+6>', frame=>'8x10',
  borderwidth=>'0', gravity=>'Center', shadow=>'True', texture=>'granite:' )
ReadImage()
Test 13, signatures do not match.
     Expected: 08d4dfa09995e13a518002565d862f6e89d65de37d59c1d1ab45d7c6cde6bd47
     Computed: 6351f76d52950b1a7c5e6fc8dbe96b5c63c1b2a3952d8843881e8002997998ca
     Depth:    16
not ok 13
$montage=$images->Montage( background=>'#696e7e',  tile=>'4x4', geometry=>'90x80+6+6>', mode=>'Unframe',
  borderwidth=>'0', gravity=>'Center', background=>'gray' )
ReadImage()
Test 14, signatures do not match.
     Expected: 245f9fbee901f99e08458aad797ade92ea17e68b230212510ad2eca96e169e39
     Computed: c28243f40a2a524fa64364b94d18e14d603a6569bca66be4e42f1ee0899a1a52
     Depth:    16
not ok 14
$images->Set(bordercolor=>'red')
$montage=$images->Montage( background=>'#696e7e',  tile=>'4x4', geometry=>'90x80+6+6>', mode=>'Unframe',
  borderwidth=>'5', gravity=>'Center', background=>'gray' )
ReadImage()
Test 15, signatures do not match.
     Expected: 611833bd0e13681a82d34c4c40b2a263bf245ac879de240114df874f9eaca7f0
     Computed: 9648d59a707ebecc50b265ab349f71e28789cf2b33bc0706a597891495ceab64
     Depth:    16
not ok 15
$images->Set(bordercolor=>'red')
$montage=$images->Montage(  tile=>'4x4', geometry=>'90x80+6+6>', mode=>'UnFrame',
  borderwidth=>'5', gravity=>'Center', background=>'gray' )
ReadImage()
Test 16, signatures do not match.
     Expected: 611833bd0e13681a82d34c4c40b2a263bf245ac879de240114df874f9eaca7f0
     Computed: 9648d59a707ebecc50b265ab349f71e28789cf2b33bc0706a597891495ceab64
     Depth:    16
not ok 16
$montage=$images->Montage( background=>'#696e7e',  tile=>'16x1', geometry=>'90x80+0+0>', mode=>'Unframe',
  borderwidth=>'0', gravity=>'Center', background=>'gray' )
ReadImage()
Test 17, signatures do not match.
     Expected: 49bf08b9ae34c7c8acee15b123c29e414ae6fb9bdf2a15dbdd3a33a753b8e7ff
     Computed: ec415b4c388d7243848d99303b8eedbabc6766d3081ceac14b11a619d147b674
     Depth:    16
not ok 17
$montage=$images->Montage( background=>'#696e7e',  tile=>'4x4', geometry=>'90x80>', mode=>'Concatenate' )
ReadImage()
Test 18, signatures do not match.
     Expected: b46f6d6c6305ab1d5f05f89030e775fca2f01dd5d40a8340372bd31dafaa4e83
     Computed: 0197f8b2677cf8e6bf9b0e2f7ef3fc4f30845cd30318bacb7387a7d2bced278e
     Depth:    16
not ok 18
$montage=$images->Montage( background=>'#696e7e',  tile=>'4x4', geometry=>'+0+0', mode=>'Unframe', shadow=>'False',
  borderwidth=>'0', background=>'gray' )
ReadImage()
Test 19, signatures do not match.
     Expected: b46f6d6c6305ab1d5f05f89030e775fca2f01dd5d40a8340372bd31dafaa4e83
     Computed: 6e0355e0ecf6a7007415de09d2d69ca4f128e5d8f1632ebb4ff6f7c3c617420a
     Depth:    16
not ok 19

This issue is not new. I disabled montage.t a while back and forgot about it.

**Comment by urban-warrior** [comment]
We need to build ImageMagick in a i586 environment to debug. Unfortunately we do not have access to a i586 host.
