### ISSUE TITLE
Converting PSD => PSD doesn't preserve layer property "compose"

### ISSUE THREAD

**Issue by KurtPfeifle** [ImageMagick/ImageMagick#1060]
I've tested this with today's Git checkout of sources which I built myself on macOS. Unfortunately I cannot share the PSD file (it's not mine, and I'm not allowed to share it by the owner).

````
/usr/local/bin/magick -version
 Version: ImageMagick 7.0.7-29 Q16 x86_64 2018-03-26 http://www.imagemagick.org
 Copyright: © 1999-2018 ImageMagick Studio LLC
 License: http://www.imagemagick.org/script/license.php
 Features: Cipher DPC HDRI Modules 
 Delegates (built-in): autotrace bzlib cairo djvu fftw fontconfig freetype gslib gvc jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib
````

I simply did run this command to convert it:

    magick in.psd out.psd

Then, to compare some metadata about the files:

````
magick magick identify -format "%[scene]  --   %g  --  %[compose]  --  %[label]\n" in.psd
 identify: unknown image property "%[label]" @ warning/property.c/InterpretImageProperties/3884.
 0  --   1200x1250+0+0  --  Over  --  
 1  --   2433x2442-584-642  --  None  --  background_schraeg
 2  --   1200x1250+0+0  --  None  --  background_gruen
 3  --   1200x1250+0+0  --  None  --  background
 4  --   815x673+227+517  --  Multiply  --  shadow
 5  --   857x93+239+74  --  Over  --  Text auf Hintergrund
 6  --   911x915+240+218  --  Over  --  product
 7  --   251x102+399+1031  --  Over  --  CL rail
 8  --   85x35+565+1098  --  Over  --  CL rail small
 9  --   1063x1111+68+70  --  Over  --  CL guides
 10  --   1680x1775+139-786  --  None  --  PF angle
 11  --   1061x52+69+1131  --  Over  --  PF white area below
 12  --   51x1062+1093+121  --  Over  --  PF white area right
 13  --   1062x1112+69+69  --  None  --  PF guides

magick magick identify -format "%[scene]  --   %g  --  %[compose]  --  %[label]\n" out.psd
 identify: unknown image property "%[label]" @ warning/property.c/InterpretImageProperties/3884.
 0  --   1200x1250+0+0  --  Over  --  
 1  --   2433x2442-584-642  --  Over  --  background_schraeg
 2  --   1200x1250+0+0  --  Over  --  background_gruen
 3  --   1200x1250+0+0  --  Over  --  background
 4  --   815x673+227+517  --  Over  --  shadow
 5  --   857x93+239+74  --  Over  --  Text auf Hintergrund
 6  --   911x915+240+218  --  Over  --  product
 7  --   251x102+399+1031  --  Over  --  CL rail
 8  --   85x35+565+1098  --  Over  --  CL rail small
 9  --   1063x1111+68+70  --  Over  --  CL guides
 10  --   1680x1775+139-786  --  Over  --  PF angle
 11  --   1061x52+69+1131  --  Over  --  PF white area below
 12  --   51x1062+1093+121  --  Over  --  PF white area right
 13  --   1062x1112+69+69  --  Over  --  PF guides
````

As can be noticed, the "compose" mode for layer 4 (labelled as "shadow") changed from "Multiply" to "Over". Compose modes for other layers changed from "None" to "Over" as well.

I don't have Photoshop around here myself, so I cannot create a sample for testing. However, I'll dig around in The Internets and try to find one which is publically available (and then edit this post to include a link).

**Comment by urban-warrior** [comment]
Unfortunately, without an example PSD image that exhibits this problem, there is little we can do. Add -debug coder to your command-line and post the results here. The debugging may help us debug the problem.

**Comment by KurtPfeifle** [comment]
I found an example Photoshop file using one layer using "compose overlay", downloadable here as a ZIP:

* https://www.freepik.com/free-psd/wooden-button-design_989771.htm#term=buttons&page=1&position=1

It's under a "free license with attribution": Created by Teinstud - Freepik.com.

The issue reported here can be reproduced with the PSD file included in the downloaded .zip.

**Comment by KurtPfeifle** [comment]
Thanks, @dlemstra! I build a new version from Git sources and verified that the fix worked :-)
