### ISSUE TITLE
Producing PDF output inserts weird 'Producer' metadata 

### ISSUE THREAD

**Issue by KurtPfeifle** [ImageMagick/ImageMagick#1063]
When IM7 produces PDF output, it inserts weird *Producer* values (this metadata is optional) into the PDF metadata (it uses the path to ImageMagick's local *index.html* documentation file). While this issue is not too important, it still looks very weird.

**Suggestions:**

1. Insert a part of the string which is printed by the `magick -version` command -- for example insert *`ImageMagick 7.0.7-29 Q16 x86_64 20180324 http://www.imagemagick.org`*.

1. Consider to also fill the (optional) *Creator:* field in the PDF metadata.

----

<sup>According to the [PDF-1.7 spec](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=558) (table 317, page 550):</sup>

1. <sup>*Producer* is meant to name the product that converted a document from an originally different format to PDF.</sup>
1. <sup>*Creator* is meant to name the product that created the original document before it was converted to PDF.</sup>

----

### Steps to reproduce

**ImageMagick version:**

````
magick -version
  Version: ImageMagick 7.0.7-29 Q16 x86_64 20180324 http://www.imagemagick.org
  Copyright: © 1999-2018 ImageMagick Studio LLC
  License: http://www.imagemagick.org/script/license.php
  Features: Cipher DPC HDRI OpenMP 
  Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig \
          jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp wmf \
          x xml zlib
````

**Create a PDF with ImageMagick:**

````
magick logo: logo.pdf
````

**Check the PDF properties:**

````
 pdfinfo logo.pdf | grep Producer
   Producer:       /usr/local/share/doc/ImageMagick-7//index.html
````

![PDF metadata as displayed by Preview.app on macOS](https://i.stack.imgur.com/9kD6Q.jpg)

----

### Update

Just noticed: IM v6 (6.9.9-26) uses the same way to name *"Producer"* metadata...

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
