### ISSUE TITLE
Long form percent escape '%[compression]' does not work

### ISSUE THREAD

**Issue by KurtPfeifle** [ImageMagick/ImageMagick#1064]
The documentation (https://www.imagemagick.org/script/escape.php in section *"Long Form Attribute Percent Escapes"*) has a table with this entry:

    %[compression]     Image compression type (as of IM 7.0.3.8)

In section *"Single Letter Attribute Percent Escapes"* it says:

    %C                 image compression type

The long form does not work for me, the single letter form does:

    magick identify -format "C: %C  --  compression: %[compression]  --  %M\n" wizard: logo: netscape:
      C: LZW  --  compression:   --  wizard:
      C: LZW  --  compression:   --  logo:
      C: LZW  --  compression:   --  netscape:

Tested with this version of ImageMagick, locally built from current Git sources:

````
Version: ImageMagick 7.0.7-29 Q16 x86_64 2018-03-26 http://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): autotrace bzlib cairo djvu fftw fontconfig freetype gslib gvc jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib
````

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
