### ISSUE TITLE
MAGICK_MAP_LIMIT MAGICK_MEMORY_LIMIT ignored by mogrify

### ISSUE THREAD

**Issue by scivision** [ImageMagick/ImageMagick#1068]
### Prerequisites

- [X ] I have written a descriptive issue title
- [X ] I have verified that I am using the latest version of ImageMagick
- [ X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
ImageMagick is ignoring large memory limit settings, instead using disk temporary files, which is extremely slow. Forcing ImageMagick temporary files to RAM disk works around this issue.

### Steps to Reproduce
1. take a large image, such as a 12200x5400 [NEXRAD PNG](https://mesonet.agron.iastate.edu/archive/data/2018/02/12/GIS/uscomp/n0q_201802120000.png) 
2. rescale with `MAGICK_MAP_LIMIT=2GB MAGICK_MEMORY_LIMIT=2GB mogrify -scale 10% "*.png"`
3. ImageMagick ignores these limits, however setting `MAGICK_DISK_LIMIT=100MB` will error as expected

Workaround: 
use ` MAGICK_TEMPORARY_PATH=/run/shm` to use RAM drive.

### System Configuration
Ubuntu 17.10

- ImageMagick version:  6.9.7-4 Q16 x86_64 20170114
- Environment (Operating system, version and so on): Ubuntu 17.10
- Additional information:

**Comment by urban-warrior** [comment]
We confirm your settings work as expected with a modern release of ImageMagick.  Your release of ImageMagick is fairly old.  You might try setting memory and map resources in /etc/ImageMagick/policy.xml.  Also try these commands:

```
identify -list resource
convert -limit map 2GB -limit memory 2GB logo: logo.png
convert -debug cache logo: logo.png
```
