### ISSUE TITLE
Drawing roundrectangle at the right side of an image fails; too many bezier coordinates

### ISSUE THREAD

**Issue by AndreasGB** [ImageMagick/ImageMagick#1069]
### Description
Drawing a roundrectangle at the right side of an image fails with 

```
convert: too many bezier coordinates `' @ error/draw.c/DrawImage/3035.
convert: non-conforming drawing primitive definition `roundrectangle' @ error/draw.c/DrawImage/3364.
```

Whereas just drawing a rectangle works up to the side of the image.

### Steps to Reproduce

Run

```
convert -size 1920x1080 xc:skyblue -fill black -draw "roundrectangle 1600,960 1790,880 5,5" drawn.gif
```

Which will fail, whereas this works for example for a rectangle.

### System Configuration

- ImageMagick version: ImageMagick 7.0.7-27 Q16 x86_64 2018-03-18
- Environment (Operating system, version and so on): Arch Linux

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick likely this weekend.

**Comment by AndreasGB** [comment]
Awesome! Thanks for the quick response!
