### ISSUE TITLE
"Catastrophic failure" when using the ".Composite" tool of the ImageMagickObject COM+ component with latest IM 6.9.9.40 DLL

### ISSUE THREAD

**Issue by AlexLaforge** [ImageMagick/ImageMagick#1070]
![catastrophic-failure-composite](https://user-images.githubusercontent.com/8602659/38118513-680d2e2e-33bb-11e8-9331-ee4e2bfe2c2c.png)
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The latest IM 6.9.9.40 version ran under Windows with VBScript leads to the following error "Catastrophic failure", when using the ".Composite" tool.
The ".Composite" tool seems broken with the Imagemagick COM+ object. As a comparison, it was working correctly with the (old) IM 6.8.5 version, and is working on 7.0.7-28.

As the official Docs states that "The ImageMagickObject COM+ component provides access to the compare, convert, composite, mogrify, identify, montage, and stream tools", I assume that this looks to a clear bug :
http://www.imagemagick.org/script/ImageMagickObject.php
or
https://legacy.imagemagick.org/script/I ... Object.php

### Steps to Reproduce
1. Install the latest Windows DLL Package of IM 6.9.9.40 Q16 x64 HDRI

2. Create a c:\TestIM.vbs file containing the following source code :
```
Set IMimg = CreateObject("ImageMagickObject.MagickImage.1")
	IMimg.Composite "rose:", "logo:", "c:\rose-over-logo.png"
Set IMimg = Nothing
```

3. Execute this code with the 64-bit version of the WSH :
C:\windows\system32\wscript.exe c:\TestIM.vbs

4. Instead of the expected result that would see the creation of the "c:\rose-over-logo.png" file thanks to the ".Composite" tool, an error is generated :
Line : 2
Char : 2
Error : Catastrophic failure
Code : 8000FFFF
Source : (null)

### Already checked
- The DLL is well registered in the 64-bit Registry
- The "ImageMagickObject.MagickImage.1" is well created
- The Read/Write/Modify user rights are correct on c:\
- The ".Identify" tool works properly from the COM+ component, and can read from c:\
- The ".Convert" tool works properly from the COM+ component, and can write on c:\

### System Configuration

- ImageMagick version: 6.9.9.40 Q16 x64 HDRI
- Environment (Operating system, version and so on): Windows Server 2012 Standard 64 bits
- Additional information: ImageMagickObject x64 Windows DLL, used from VBScript

**Comment by dlemstra** [comment]
I cannot reproduce your issue with the latest development build. And I have no idea why it is failing on your machine.

**Comment by AlexLaforge** [comment]
Hi @dlemstra ,
I have not tested the latest development build, but only the last official release 6.0.0-40.
