### ISSUE TITLE
Convert PDF to TIFF compress Group 4 causes TIFF result with Black Background

### ISSUE THREAD

**Issue by ITGuy1234** [ImageMagick/ImageMagick#1071]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I am trying to convert a PDF invoice to a TIFF file but the results have a black background while using compress Group 4. This doesn't seem to happen with all PDFs. 
### Steps to Reproduce

Sample code I am running, the compress Group 4 causes the TIFF to result in black background
magick.exe convert -units PixelsPerInch -density 300 Invoice#S21118045.pdf -background white -alpha remove -flatten -alpha off -compress Group4 Invoice#S21118045.tif

![invoice s21118045](https://user-images.githubusercontent.com/37913810/38111365-b6549364-336c-11e8-9cbe-01f5ceb7bde9.jpg)

- ImageMagick version: 7.07-28 Q16 (64-bit)
- Environment (Operating system, version and so on): Windows 7, 64 Bit 
- Additional information:

**Comment by fmw42** [comment]
Please post a link to your PDF file, so we can examine it and you exact command line. 

It is likely and issue with either the alpha channel or with the colorspace. Note that JPG does not support transparency. 

Note that in Imagemagick 7 use magick and not magick convert.

Try removing the alpha remove and alpha off and add -colorspace sRGB if your PDF is in CMYK colorspace. Flattening by itself removes the alpha channel. So you have removed it too soon.

`magick.exe -units PixelsPerInch -density 300 -colorspace sRGB Invoice#S21118045.pdf -background white -flatten -compress Group4 Invoice#S21118045.tif`
