### ISSUE TITLE
OpenMP support configured but not available on macOS with LibOMP

### ISSUE THREAD

**Issue by rgov** [ImageMagick/ImageMagick#1073]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm trying to build ImageMagick with OpenMP support using the system Clang and LibOMP installed with Homebrew.

### Steps to Reproduce
I've installed LibOMP via Homebrew and then configured ImageMagick like so:

    CFLAGS="-I/usr/local/opt/libomp/include -Xpreprocessor -fopenmp" \
    LDFLAGS="-L/usr/local/opt/libomp/lib -lomp" \
    ./configure --disable-osx-universal-binary --prefix=/usr/local/Cellar/imagemagick/7.0.7-28 --disable-dependency-tracking --disable-silent-rules --enable-shared --enable-static --with-modules --enable-opencl --enable-openmp --without-webp --without-openjp2 --without-gslib --with-gs-font-dir=/usr/local/share/ghostscript/fonts --without-fftw --without-pango --without-x --with-freetype=yes --without-wmf

During configuration I see this output:

```
checking for clang option to support OpenMP... none needed
...
  Options used to compile and link:
    PREFIX          = /usr/local/Cellar/imagemagick/7.0.7-28
    EXEC-PREFIX     = /usr/local/Cellar/imagemagick/7.0.7-28
    VERSION         = 7.0.7
    CC              = clang
    CFLAGS          = -I/usr/include/libxml2 -I/usr/local/Cellar/libpng/1.6.34/include/libpng16 -I/usr/local/Cellar/xz/5.2.3/include -I/usr/local/opt/freetype/include/freetype2    -I/usr/local/opt/libomp/include -Xpreprocessor -fopenmp -Wall -mtune=core2 -fexceptions -D_FORTIFY_SOURCE=0 -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
    CPPFLAGS        =   -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
    PCFLAGS         = 
    DEFS            = -DHAVE_CONFIG_H
    LDFLAGS         = -L/usr/local/opt/libomp/lib -lomp
    LIBS            = 
    CXX             = clang++
    CXXFLAGS        = -I/usr/local/opt/libomp/include -Xpreprocessor -fopenmp -pthread
    FEATURES        = DPC HDRI Cipher OpenMP Modules
    DELEGATES       = bzlib mpeg freetype jng jpeg lzma png tiff xml zlib
```

Additionally, I see the `-fopenmp` flag passed to each invocation of the compiler, and the resulting binary does link against `libomp.dylib`, suggesting my linker flags were honored.

But in the end, the resulting binary does not list OpenMP support:

```
Version: ImageMagick 7.0.7-28 Q16 x86_64 2018-03-31 http://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib
```

[Full build log.](https://gist.github.com/rgov/7e877a7997fc9a316d0f67feda17c67e)

### System Configuration

- ImageMagick version: 7.0.7-28
- Environment (Operating system, version and so on): macOS 10.13.4, Apple LLVM version 9.1.0 (clang-902.0.39.1)

**Comment by urban-warrior** [comment]
To enable OpenMP, the toolchain must export _OPENMP and _OPENMP must be greater than 200203 or __OPENCC__ must be defined.  Are these symbols exported by your toolchain?  If not, we may need to adjust our OpenMP detection method.

**Comment by rgov** [comment]
I wrote a trivial C file that just includes `<omp.h>` and prints out the value of `_OPENMP` and it built fine and outputs `201107`. The `OPENCC` environment variable is not defined.

**Comment by urban-warrior** [comment]
That means OpenMP support is enabled in your ImageMagick build.  However, from your description, the configure script does not detect it to enable it as a feature.  We use the autoconf AC_OPENMP() macro to detect OpenMP support.  That might suggest a bug, lacking robustness, or out of date.  We build under Fedora, and AC_OPENMP() detects OpenMP as expected.

**Comment by rgov** [comment]
The configure script does seem to enable it, it's listed in the `FEATURES` print out.

I did notice that `configure` did detect that OpenMP is `unsupported` for C++ files, but if I add the `-Xpreprocessor -fopenmp` flags to `CXXFLAGS`, then it chokes... 

```
libtool: compile:  clang++ -DHAVE_CONFIG_H -I. -I./config -I. -I. -I./Magick++/lib -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/opt/libomp/include -Xpreprocessor -fopenmp -I/usr/local/opt/libomp/include -Xpreprocessor -fopenmp -pthread -c Magick++/lib/Blob.cpp  -fno-common -DPIC -o Magick++/lib/.libs/Magick___lib_libMagick___7_Q16HDRI_la-Blob.o

error: unknown argument: '-Xpreprocessor'
make[1]: *** [Magick++/lib/Magick___lib_libMagick___7_Q16HDRI_la-Blob.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2
```

However I don't understand this error—the `-Xpreprocessor` flag definitely exists, and the command goes to the compiler just fine. Is something else trying to parse the compiler flags?

**Comment by urban-warrior** [comment]
Closing as stale and we cannot help.  We did not write the OpenMP M4 macro, we just utilize it as is.
