### ISSUE TITLE
Resize makes the computer crash

### ISSUE THREAD

**Issue by Youness-e** [ImageMagick/ImageMagick#1074]
### Description & Steps to Reproduce
For a few days, doing a resize with convert instantly makes my computer freeze. (need manual restart)
Simple convert works perfectly, but if I add a -resize, it does not work anymore, as with this command:

Work fine:
`magick convert rose.jpg rose.png`

Freeze computer (no ouput):
`magick convert rose.jpg -resize 50% rose.png`

Image used: https://www.imagemagick.org/image/rose.jpg

I tried with a command like
`MAGICK_THREAD_LIMIT = 1 convert -debug all -resize 50% -limit memory 16MB -limit map 2MB rose.jpg rose2.jpg &> debug_imagemagick.txt`

(increase memory above 64MB makes freeze the computer)

console output: [1] 6138 abort (core dumped)
debug file (64M text file): https://www.sendspace.com/file/0aoka0

No logs of the system, so no way to know the origin of the problem. 

### System
Archlinux
Linux ypc 4.15.13-1-ARCH #1 SMP PREEMPT Sun Mar 25 11:27:57 UTC 2018 x86_64 GNU/Linux
Imagemagick version: 6.9.9-40 and 7.0.7.27-2

`identify -list resource`
Resource limits:
  Width: 107.374MP
  Height: 107.374MP
  List length: -1
  Area: 42.0213GP
  Memory: 19.5677GiB
  Map: 39.1354GiB
  Disk: unlimited
  File: 768
  Thread: 4
  Throttle: 0
  Time: unlimited

**Comment by fmw42** [comment]
In IM 7, magick replaces convert. So leave off convert 

`magick rose.jpg -resize 50% rose.png`

or in IM 7

`convert rose.jpg -resize 50% rose.png`

If those do not work, then perhaps a problem with your install of Imagemagick or a conflict between your IM 6 and IM 7 versions. One of the developers will need to help further.

**Comment by Youness-e** [comment]
Same issue with 
`magick rose.jpg -resize 50% rose.png`
or 
`convert rose.jpg -resize 50% rose.png`

Keep IM6 or IM7 only doesn't change anything :(

**Comment by Youness-e** [comment]
With MAGICK_OCL_DEVICE=OFF, it's working.
I will try to downgrade my opencl version.

Thanks you, you save me !

**Comment by Faalagorn** [comment]
@Youness-e Seeing as it's related to mesa, is that bug reported to Mesa upstream? The issue still happens for me on 64-bit Arch, 4.16.12 kernel and mesa-git 102412.79fe00efb4-1 with AMD Radeon RX 580 – any kind of resize options makes the computer stops responding (with mouse stopping responding a few seconds later) and it won't close until I *REISUB* it. It happens with both the most recent 6 and 7 version of imagemagick. `MAGICK_OCL_DEVICE=OFF` indeed helps with solving the issue.

**Comment by Krizai** [comment]
I'm experiencing a similar issue.
Resizing freezes forever if ocl is enabled. 
IM version is :
```
Version: ImageMagick 7.0.10-30 Q8 x64 2020-09-19 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 192729111
Features: Cipher DPC OpenCL
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib
```

Output of  `magick convert -debug all -resize 50% cat.png cat2.jpg` ends with 
```
2020-09-23T07:35:55+00:00 0:00.921 0.578u 7.0.10 Exception convert[18704]: blob.c/FileToBlob/1438/Exception
  unable to read blob 'C:\Users\Tulip\AppData\Local\ImageMagick\magick_opencl________Intel(R)_Core(TM)_i5-3230M_CPU_@_2.60GHz_142e145a_64.bin': No such file or directory
```

The same thing happens when I'm trying to do resize via MagickWand - freeze with any filter except for Bessel and Gaussian
