### ISSUE TITLE
"man 1 ImageMagick.1" mentions non-existent quantize(5) and miff(4) manual pages

### ISSUE THREAD

**Issue by KurtPfeifle** [ImageMagick/ImageMagick#1080]
When reading manual page *"man 1 ImageMagick.1"* it mentions in its "SEE ALSO" section the following man pages: *quantize(5)* and *miff(4)*. Both these man pages are not present.

On the other hand, the following manual pages are present, but not mentioned in the "SEE ALSO" section:

 *import(1)*,  
 *magick(1)*,  
 *magick-script(1)*,  
 *stream(1)*,  
 *Magick++-config(1)*,  
 *MagickCore-config(1)*,  
 *MagickWand-config(1)*.

This result is true for an locally ImageMagick version built (on Debian Stretch) from current Git sources:

````
Version: ImageMagick 7.0.7-29 Q16 x86_64 20180326 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib
````

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
