### ISSUE TITLE
Color of image getting changed while converting svg to png

### ISSUE THREAD

**Issue by PratibhaB24** [ImageMagick/ImageMagick#1082]
We have to write .svg images to excel . As we can't write svg to excel so we are converting .svg to .jpeg using ImageMagick then writing to excel using ClosedXML. 
Everything is working fine but some images color are getting black . Some are writing perfectly to excel file with proper original color .
I can't provide sample images as it is legacy project .

//here is code snippet :
Byte[] imgInJPEGFormat = null;
MagickReadSettings settings = new MagickReadSettings();                                          
settings.Width = 800;
settings.Height = 600;
settings.Format = MagickFormat.Svg;
 //as we can't write .svg images to excel so .svg is formatted to .jpg 
//(Byte[])dataRow[columnCounter] is data in bytes of svg images
using (MagickImage img = new MagickImage((Byte[])dataRow[columnCounter], settings))
 {
img.Format = MagickFormat.Png;
imgInJPEGFormat = img.ToByteArray();
 }
objSheet.WriteTTImageInExcel(workingRow, workingCol, imgInJPEGFormat);

- ImageMagick version:
Magick.NET-Q8-AnyCPU.dll version 7.2.1.0
I have tried latest version but still problem exists

**Comment by dlemstra** [comment]
You are posting the issue in the wrong project. This is the correct project: https://github.com/dlemstra/Magick.NET

**Comment by PratibhaB24** [comment]
Thanks I will post on provided project..hope I will find solution there

**Comment by PratibhaB24** [comment]
Thank you
I will repost issue in above mentioned project
