### ISSUE TITLE
"Magick" tool cannot be used with the ImageMagickObject COM+ component

### ISSUE THREAD

**Issue by AlexLaforge** [ImageMagick/ImageMagick#1083]
### Prerequisites

- [X] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Not really sure that is a bug, but that seem to be a missing method implementation.
In 7.0.7-28, the dynamic variables are only usable using the "magick" command, not the "convert" command.
Consequently, as the ImageMagickObject COM+ component does not recognize the "magick" command, that would be a great addition to make the ImageMagickObject COM+ component support it.

The docs actually do not state that the "magick" command is supported, but that fact limit the usage of the COM+ Component. Supporting the "new" v7 "Magick" command would seem to be very logical. [](http://www.imagemagick.org/script/ImageMagickObject.php)

As this COM+ component is only a wrapper of the classic command-line, (I think that) it *should not* be too complicated to allow the usage of "magick" the same way "convert" is available in the ImageMagickObject COM+ component.

### Steps to Reproduce

1. Install the latest Windows DLL Package of IM 7.0.7-28 Q16 x64 HDRI
2. Create a c:\Test-Magick.vbs file containing the following source code :
```
Set img = CreateObject("ImageMagickObject.MagickImage.1")
	'Does not Work
	img.Magick "c:\SOURCE.png", "-set", "option:NewW %[fx:w/2]", "-resize", "%[NewW]x", "c:\DEST.png" 
Set img = Nothing
```
3. Execute this code with the 64-bit version of the WSH :
C:\windows\system32\wscript.exe c:\Test-Magick.vbs

4. An error message is produced :
_Line : 3
Char : 2
Error : Object doesn't support this property or method: img.Magick
Code : 800A01B6
Source : Microsoft VBScript runtime error_

### System Configuration
- The DLL is well registered in the 64-bit Registry
- The "ImageMagickObject.MagickImage.1" is well created

- ImageMagick version: 7.0.7-28 Q16 x64 HDRI
- Environment (Operating system, version and so on): Windows Server 2012 R2 Standard 64 bits
- Additional information: ImageMagickObject x64 Windows DLL, used from VBScript

![method-not-supported](https://user-images.githubusercontent.com/8602659/38211201-fe90e042-36b9-11e8-908a-358c6480c967.png)

**Comment by urban-warrior** [comment]
We added support for the "magick" command as you suggested.  It will likely take a few days to compile and test.
