### ISSUE TITLE
Latest pull no longer compiles on cygwin

### ISSUE THREAD

**Issue by ennss** [ImageMagick/ImageMagick#1088]
This appeared perhaps 2 weeks ago(?) 
Fresh git clone, configure, make:
[configlog.zip](https://github.com/ImageMagick/ImageMagick/files/1891297/configlog.zip)

  CC       MagickCore/MagickCore_libMagickCore_7_Q32HDRI_la-deprecate.lo
In file included from MagickCore/deprecate.c:48:0:
./MagickCore/studio.h:101:21: fatal error: direct.h: No such file or directory
 # include <direct.h>
                     ^
compilation terminated.
make[1]: *** [Makefile:7700: MagickCore/MagickCore_libMagickCore_7_Q32HDRI_la-de
precate.lo] Error 1
make[1]: Leaving directory '/cygdrive/h/cygwin17/ImageMagick/ImageMagick'
make: *** [Makefile:5178: all] Error 2

Seems to be fixed completely by removing reference to direct.h from ./MagickCore/studio.h:101, or

changing if from from:    

#if defined(MAGICKCORE_WINDOWS_SUPPORT)

# include <io.h>
# include <direct.h>
# if !defined(MAGICKCORE_HAVE_STRERROR)
#  define HAVE_STRERROR
# endif
#endif

to: 

#if defined(MAGICKCORE_WINDOWS_SUPPORT)
# include <io.h>
#if !defined(__CYGWIN__)
# include <direct.h>
#endif
# if !defined(MAGICKCORE_HAVE_STRERROR)
#  define HAVE_STRERROR
# endif
#endif

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
