### ISSUE TITLE
null pointer dereference in CompileOpenCLKernels

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1090]
I think the same as in #793, but for ImageMagick-6. 
https://github.com/ImageMagick/ImageMagick/blob/ImageMagick-6/magick/opencl.c#L1151

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
