### ISSUE TITLE
Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/912

### ISSUE THREAD

**Issue by bhargavparekh** [ImageMagick/ImageMagick#1092]
I am using the ImageMagick 6.9.7-4. When I upload the tif image and it save as 0 byte in the folder.
I got this type error in error log:
"Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/912"

**Comment by fmw42** [comment]
I would check your uploading software, if you are getting a zero byte file size. If the file uploads fine, then the message you are getting is simply a warning that there is some optional tag that Imagemagick does not know about. It is not an error and Imagemagick should process your file fine.

**Comment by urban-warrior** [comment]
Post a URL to your image.  We need to download it and reproduce the problem before we can comment.
