### ISSUE TITLE
assertion failure in ReplaceImageInList (cont.)

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1093]
This is follow up of #802. I think the second parameter of the other `ReplaceImageInList()` call:
```
ReplaceImageInList(&p,CloneImage(q,0,0,MagickTrue,exception));
```
should be checked before use, too (I guess that was actually the original report @bestshow, correct?).

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
