### ISSUE TITLE
Error "improper image header" on .xcf file with a layer larger than canvas

### ISSUE THREAD

**Issue by ChrisJAllan** [ImageMagick/ImageMagick#1100]
### Description
Trying to access an xcf file that has a layer larger than the canvas gives the following output:

```
identify: improper image header `test.xcf' @ error/xcf.c/ReadOneLayer/821.
identify: not enough pixel data `test.xcf' @ error/xcf.c/ReadXCFImage/1373.
```

### Steps to Reproduce
Basic image to demonstrate: [test.xcf.zip](https://github.com/ImageMagick/ImageMagick/files/1930154/test.xcf.zip)

### System Configuration

- ImageMagick version: ImageMagick 7.0.7-28 Q16 x86_64 2018-03-31
- Environment (Operating system, version and so on): Arch Linux
- Additional information: Kernel x86_64 Linux 4.14.33-1-lts<br />Image made with Gimp 2.8.22

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
