### ISSUE TITLE
Request to restore "6.9.9-34" tag

### ISSUE THREAD

**Issue by matthewbauer** [ImageMagick/ImageMagick#1101]
Hi,

We are relying on Git tags in Nixpkgs (https://github.com/NixOS/nixpkgs/issues/39276). At some point recently the "6.9.9-34" tag has disappeared (in fact all ImageMagick 6 tags are gone). AFAICT ImageMagick 6 is still officially supported. Not sure what happened to the tag or when it happened but it was at least available in January (https://github.com/NixOS/nixpkgs/commit/d18299edcb8536b7cf5be9c8caed12d25e7badcc).

**Comment by dlemstra** [comment]
The code of ImageMagick 6 used to be a in a branch. We moved this to a separate project. Your tag can now be found here: https://github.com/ImageMagick/ImageMagick6/releases/tag/6.9.9-34. The following PR should fix your issue: https://github.com/NixOS/nixpkgs/pull/39294
