### ISSUE TITLE
-sparse-color in version 7 works differently compared to version 6 of ImageMagick

### ISSUE THREAD

**Issue by dronferganskiy** [ImageMagick/ImageMagick#1104]
### Prerequisites

- [*] I have written a descriptive issue title
- [*] I have verified that I am using the latest version of ImageMagick
- [*] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
-sparse-color in 7 version of ImageMagick does not define the area to which this option must apply

### Steps to Reproduce
I have code. 

```convert -size 125x39 xc:none -fill gradient:'#227fdc-#035cb6'  -draw 'roundrectangle 0,0 124,38 18,18' \( +clone -sparse-color  Voronoi '0,19.5 #227fdc 0,20.5 #035cb6' \) -background none -compose SrcOver -flatten   some_name.png```

It draws a rounded button that fills with two colors from the middle of the button.

In version 6 everything is rendered correctly, 
![button_1](https://user-images.githubusercontent.com/38645096/39240141-6f2fe4a8-489c-11e8-9570-920f8e53e4b6.png)

but in version 7 the option ```\( +clone -sparse-color  Voronoi '0,19.5 #227fdc 0,20.5 #035cb6' \)``` is applied to the entire canvas
![button_2](https://user-images.githubusercontent.com/38645096/39240015-0bb44e5a-489c-11e8-8e8a-7748f3b0f593.png)

Is this bug or feature?

### System Configuration

- ImageMagick 7 version:
Version: ImageMagick 7.0.7-19 Q16 x86_64 2018-02-03
Delegates (built-in): bzlib cairo freetype jng jpeg lcms ltdl png rsvg tiff xml zlib

- ImageMagick 6 version:
Version: ImageMagick 6.9.9-20 Q16 x86_64 2017-12-06
Delegates (built-in): bzlib cairo freetype jng jpeg lcms ltdl png rsvg tiff zlib

please help with the solution of this problem, thanks

**Comment by urban-warrior** [comment]
Channels are handled differently in IMv7 per the porting guide @ https://www.imagemagick.org/script/porting.php.  Try this command:

`convert -size 125x39 xc:none -fill gradient:'#227fdc-#035cb6' -draw 'roundrectangle 0,0 124,38 18,18' \( +clone -sparse-color Voronoi '0,19.5 #227fdc00 0,20.5 #035cb600' \) -background none -compose SrcOver -flatten some_name.png`

There is a smoother color transition in IMv7.  Which version is correct?  If you feel IMv6 is the correct rendering, we will investigate further.

**Comment by dronferganskiy** [comment]
The problem is not the color transition
The problem is that the option -sparse-color does not correctly determine its scope

The same code without options -gradient and -flatten

`convert -size 125x39 xc:none -draw 'roundrectangle 0,0 124,38 18,18' \( +clone -sparse-color Voronoi '0,19.5 #227fdc 0,20.5 #035cb6' \) -background none -compose SrcOver some_name.png`

In version 6 of ImageMagick we get two files

![aaaa-0](https://user-images.githubusercontent.com/38645096/39615523-130c459a-4f90-11e8-961d-4ad2de1f9f6e.png)  - draw a roundrectangle

![aaaa-1](https://user-images.githubusercontent.com/38645096/39615529-1a1dcb24-4f90-11e8-8915-dee59938669e.png) - fill it with color using the option -space-color

That is, the option -spark-color applied to the previously drawn roundrectangle

But, in 7 version of ImageMagick we get another result

![bbbb-0](https://user-images.githubusercontent.com/38645096/39615624-b8950e8e-4f90-11e8-887f-38f6d074e1a6.png) - draw a roundrectangle

![bbbb-1](https://user-images.githubusercontent.com/38645096/39615632-bd6a2d22-4f90-11e8-8b37-01ebfcd820b7.png) - try to fill it with color using the option -space-color

The option -space-color did not define the region of the previously drawn roundrectangle, and applied to the entire canvas

**Comment by urban-warrior** [comment]
Try this command:

`convert -size 125x39 xc:none -fill gradient:'#227fdc-#035cb6' -draw 'roundrectangle 0,0 124,38 18,18' \( +clone -channel rgb -sparse-color Voronoi '0,19.5 #227fdc 0,20.5 #035cb6' \) -background none -compose SrcOver -flatten some_name.png`

It works for both IMv7 and IMv6.  See the [porting](https://www.imagemagick.org/script/porting.php) guide which says (in regard to the -channel option):

> the default is to update the RGBA channels, previously, in IMv6, the default was RGB. If you get results that differ from IMv6, you may need to specify -channel RGB on your command line

**Comment by dronferganskiy** [comment]
Thanks, this code works in both versions
