### ISSUE TITLE
only base_offset_size=0 and index_size=0 are supported

### ISSUE THREAD

**Issue by ddor254** [ImageMagick/ImageMagick#1105]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
getting this error: 
"convert: improper image header `only base_offset_size=0 and index_size=0 are supported' @ error/heic.c/ParseIlocAtom/583."

and fail to create the converted (jpeg) file.

### Steps to Reproduce
1 . downloaded file from nokiatech repo - https://github.com/nokiatech/heif/blob/gh-pages/content/images/autumn_1440x960.heic

2 . run command convert autumn_1440x960.heic autumn_1440x960.jpeg

### System Configuration

- ImageMagick version: Version: ImageMagick 7.0.7-29
- Environment (Operating system, version and so on): ubuntu 16.04
- Additional information:

**Comment by dlemstra** [comment]
This is by design? We are reporting an error that we don't support this. This might change when we merge #1099.
