### ISSUE TITLE
Incorrect colors after manipulating an image

### ISSUE THREAD

**Issue by jhorowitz-firedrum** [ImageMagick/ImageMagick#1108]
### Description
Processing images typically produces incorrect colors in the output file.

git bisect reports the following commit as the source of the bug: 558360c4a27ae652530e3ed72580088f2a0662bb 

For build configurations with HDRI disabled and a Quantum Depth other than 8 or 16, behavior has changed wherein ClampToQuantum is no longer called in AcquirePixelThreadSet.

See [line 1205 in the referenced commit].(https://github.com/ImageMagick/ImageMagick/commit/558360c4a27ae652530e3ed72580088f2a0662bb#diff-1e2afebe93e10ebad7531cb43e604625R1205)

[This patch](https://github.com/ImageMagick/ImageMagick/files/1939933/issue-1108-fix-q32-without-hdri-builds.patch.txt) fixes the issue on commit 880612a33b00fb0bcd47f6191e9f0d352f86a0b3.

### Steps to Reproduce
Source Image:
![header2](https://user-images.githubusercontent.com/21692512/39157507-f6ac9d2e-470f-11e8-8c13-834be72d5e02.jpg)

Extract the [TestCaseAssets.zip](https://github.com/ImageMagick/ImageMagick/files/1940332/TestCaseAssets.zip) file to a temporary directory and run the following command from within that directory:
```bash
convert header2.jpg -profile PRMG_v2.0.1_MR.icc -profile sRGB_v4_ICC_preference.icc -colorspace sRGB +profile icc -units PixelsPerInch -density 96x96 output.jpg
```

Correct output with commit immediately preceding the referenced commit (2159d37d656512a74fddac61c91407744fde588f):
![2159d37d656512a74fddac61c91407744fde588f-output](https://user-images.githubusercontent.com/21692512/39157837-a0f1ca88-4711-11e8-9ca7-ba6fb2475ee2.jpg)

Incorrect output with the referenced commit (558360c4a27ae652530e3ed72580088f2a0662bb):
![558360c4a27ae652530e3ed72580088f2a0662bb-output](https://user-images.githubusercontent.com/21692512/39157748-21350b84-4711-11e8-954d-2c912d71a1f5.jpg)

Incorrect output with current master commit (c11311cea432dc4ea689b02ebf7e391e4fb4a682):
![c11311cea432dc4ea689b02ebf7e391e4fb4a682-output](https://user-images.githubusercontent.com/21692512/39157677-cb87221c-4710-11e8-86ff-6ce996a837dd.jpg)

### System Configuration
- ImageMagick version: Originally discovered on commit 880612a33b00fb0bcd47f6191e9f0d352f86a0b3
- Environment: CentOS 5.11
- Additional information: Configure command line arguments for build below
```bash
./configure --disable-hdri --with-quantum-depth=32
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
