### ISSUE TITLE
Undesired color inversion after manipulating an image

### ISSUE THREAD

**Issue by jhorowitz-firedrum** [ImageMagick/ImageMagick#1109]
### Description
Processing images typically produces undesired color inversion in the output file.

git bisect reports the following commit as the source of the bug: e9e21b3a70b909905237ac6e145908acf1750aa3 

### Steps to Reproduce
Source Image: 
![finishedpanel](https://user-images.githubusercontent.com/21692512/39156937-48afffd8-470d-11e8-8c52-a2d4de9a4689.jpg)

Extract the [TestCaseAssets.zip](https://github.com/ImageMagick/ImageMagick/files/1940269/TestCaseAssets.zip) file to a temporary directory and run the following command from within that directory:
```bash
convert finishedpanel.jpg -profile PRMG_v2.0.1_MR.icc -profile sRGB_v4_ICC_preference.icc -colorspace sRGB +profile icc -units PixelsPerInch -density 96x96 output.jpg
```

Correct output with commit immediately preceding the referenced commit (409701b58ec91f8a13b2f43c367d2b02bb3db101):
![409701b58ec91f8a13b2f43c367d2b02bb3db101-output](https://user-images.githubusercontent.com/21692512/39157299-112267fc-470f-11e8-80f9-4f3e748a9eb9.jpg)

Incorrect output with the referenced commit (e9e21b3a70b909905237ac6e145908acf1750aa3):
![e9e21b3a70b909905237ac6e145908acf1750aa3-output](https://user-images.githubusercontent.com/21692512/39157073-f8d7ebbe-470d-11e8-826b-044889d1be95.jpg)

Incorrect output with current master commit (c11311cea432dc4ea689b02ebf7e391e4fb4a682):
![c11311cea432dc4ea689b02ebf7e391e4fb4a682-output](https://user-images.githubusercontent.com/21692512/39157459-bc6e2dbc-470f-11e8-8c3e-220f6e3ebce1.jpg)

### System Configuration
- ImageMagick version: Current master (commit c11311cea432dc4ea689b02ebf7e391e4fb4a682)
- Environment: CentOS 5.11
- Additional information: Configure command line arguments for build below
```bash
./configure --disable-hdri --with-quantum-depth=32
```

**Comment by fmw42** [comment]
Seems like your input JPG is sRGB with no profile. You are then assigning it a CMYK profile and then converting back to sRGB. That is likely why you are getting the color inversion. Either use a CMYK input JPG or just assign it the sRGB profile.

**Comment by jhorowitz-firedrum** [comment]
I do that when no ICC profile is detected within the file. Otherwise, if passed a cmyk image with no profile, assigning the sRGB profile does the same thing with messed up colors.

Is there a better process for conversion to sRGB for unknown colorspace input files?

**Comment by fmw42** [comment]
You should check the colorspace first. Then if CMYK and no profile, do what you did. If sRGB and no profile, just use the sRGB.icc profile. If CMYK and a profile exists, just use the sRGB.icc profile.

See %[colorspace] string format at https://www.imagemagick.org/script/escape.php or extract it from identify -verbose data.

**Comment by jhorowitz-firedrum** [comment]
I guess relying on catching a thrown exception isn't really the right way of doing things.
I've adjusted my code and we'll see how that works. Thanks @fmw42!
