### ISSUE TITLE
-layers composite doesn't respect compose:outside-overlay

### ISSUE THREAD

**Issue by njdoyle** [ImageMagick/ImageMagick#1110]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using the `-layers composite` command line option for `convert`, I expect it to respect the `compose:outside-overlay` option the way the `-composite` option does. Right now, that doesn't seem to be the case.
Relatedly, [documentation](https://www.imagemagick.org/script/command-line-options.php#composite) seems to suggest this option defaults to `true` but that also doesn't seem to be the case.

### Steps to Reproduce
Here's a DstIn cookie cutter composite example. The following two commands should produce the same result but they don't:
```
convert -define 'compose:outside-overlay=true' rose: -alpha on \( -background none -pointsize 30 label:A \) -gravity center -compose dstin -composite composite_out.png
```
Which outputs:
![composite_out](https://user-images.githubusercontent.com/316852/39209536-06530686-47d4-11e8-899f-83701ddd5fcf.png)

```
convert -define 'compose:outside-overlay=true' rose: -alpha on null: \( -background none -pointsize 30 label:A \) -gravity center -compose dstin -layers composite layers_out.png
```
Which outputs:
![layers_out](https://user-images.githubusercontent.com/316852/39209537-06695e0e-47d4-11e8-80bb-d3a888775840.png)

The second command should produce the same output as the first command.

### System Configuration

- ImageMagick version: ImageMagick 7.0.7-28 Q16 x86_64 2018-04-24
- Environment (Operating system, version and so on): macOS 10.13.3
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by njdoyle** [comment]
The behaviour of `compose:outside-overlay` looks like what I expect now with `-layers composite` in 7.0.7-29. Thank you!
The documentation still doesn't align with the defaults though. It seems like `compose:outside-overlay` defaults to `false` while the documentation suggests it defaults to `true`.
