### ISSUE TITLE
Unable to convert animate gif to animate webp

### ISSUE THREAD

**Issue by shelvsky** [ImageMagick/ImageMagick#1111]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
It seems that IM still doesn't support to encode animated WebP yet right? I checked the code in the path coders/ and I found nothing about it. So any plans for that? It not, maybe I can contribute
magick [gif image] -coalesce [dst webp gif]
looks like it will produce a series of still webp images but not one animate webp

### System Configuration

- ImageMagick version: ImageMagick-7.0.7-27
- Environment (Operating system, version and so on): CentOS 7.2
- Additional information:

**Comment by urban-warrior** [comment]
Correct ImageMagick does not currently support animated WebP.  ImageMagick is open-source, anyone from the user community is welcome to contribute a patch that adds supports animated WebP.

**Comment by DSpeichert** [comment]
Looks like this could be closed since #1708 was manually merged.
