### ISSUE TITLE
Imagemagick breaks image when downsizing colorspace

### ISSUE THREAD

**Issue by Luke-SF** [ImageMagick/ImageMagick#1113]
### Prerequisites

- [X] I have written a descriptive issue title
- [?] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Imagemagick fails to correctly downsize an image when using `convert -colors 255 ./breaky.png ./out.png
![breaky](https://user-images.githubusercontent.com/2318837/39336517-cdc01f3a-496c-11e8-81e1-3238a2de7ec7.png)
![out](https://user-images.githubusercontent.com/2318837/39336531-e684313c-496c-11e8-9282-5c8cfee75067.png)

### Steps to Reproduce
Run the command and note the broken output file.

### System Configuration

- ImageMagick version:
Version: ImageMagick 6.9.9-26 Q16 x86_64 2018-04-12 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules 
Delegates (built-in): bzlib djvu fftw fontconfig freetype gslib jbig jng jp2 jpeg lcms ltdl lzma openexr png ps raw tiff webp x xml zlib

- Environment (Operating system, version and so on):
Mac OS 10.13.4

**Comment by urban-warrior** [comment]
Try this command:

`convert ./breaky.png -alpha off -colors 255 ./out.png`
