### ISSUE TITLE
Segmentation fault on Termux

### ISSUE THREAD

**Issue by leewdch** [ImageMagick/ImageMagick#1116]
### Description
When trying to use imagemagick, in specific pywal, on the Termux terminal on my phone I get a segmentation fault error. The error has been first reported [here](https://github.com/dylanaraps/pywal/issues/237).

### Steps to Reproduce
This is the command used in my previous attempt:
`convert /path/to/img.jpg -resize 25% -colors 16 -unique-colors txt:-`

### System Configuration
I'm using imagemagick on the Termux Linux environment for Android. I tried both the stable and dev branch but same result.

- ImageMagick version: stable,now 7.0.7.27 aarch64
- Environment (Operating system, version and so on): Android 7.1 - Latest version of Termux
- Additional information: I get my image sample from a symlink to sdcard path

![screenshot_20180430-175822](https://user-images.githubusercontent.com/11262717/39437113-33914178-4ca0-11e8-91d6-590e09e5d319.png)

**Comment by urban-warrior** [comment]
We tried your command with the latest ImageMagick release, 7.0.7-28, and we cannot reproduce the problem.  The command completes without complaint,
