### ISSUE TITLE
FcPatternDestroy / FcPatternEqualSubset memory leak

### ISSUE THREAD

**Issue by schumilo** [ImageMagick/ImageMagick#1117]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Memory leak in FcPatternDestroy and FcPatternEqualSubset. 
ASAN Report: 

```
=================================================================
==27212==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x4b9228 in __interceptor_malloc (/home/sergej/ImageMagick/.libs/lt-magick+0x4b9228)
    #1 0x7fa878e9f0b9 in FcPatternDestroy (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d0b9)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x4b93b0 in calloc (/home/sergej/ImageMagick/.libs/lt-magick+0x4b93b0)
    #1 0x7fa878e9f7c8 in FcPatternEqualSubset (/usr/lib/x86_64-linux-gnu/libfontconfig.so.1+0x1d7c8)
```
Found with a modified version of the kAFL fuzzer (https://github.com/RUB-SysSec/kAFL).

Credits: Sergej Schumilo, Cornelius Aschermann (Ruhr-Universität Bochum)

### Steps to Reproduce

```
# Using an ASAN build of ImageMagick
ASAN_OPTIONS=allow_addr2line=true ./magick_asan memleak_1 /dev/null 
```
[memleak_1.zip](https://github.com/ImageMagick/ImageMagick/files/1965318/memleak_1.zip)

### System Configuration

- ImageMagick version: ImageMagick 7.0.7-29 Q16 x86_64 2018-04-30
- Environment (Operating system, version and so on): Ubuntu 16.04.4 LTS
- Additional information:

**Comment by urban-warrior** [comment]
Perhaps the leak is within GNU libfontconfig.  Valgrind --leak-check=full returns

```
==14045==    definitely lost: 0 bytes in 0 blocks
==14045==    indirectly lost: 0 bytes in 0 blocks
```
