### ISSUE TITLE
Weird white noise when converting .eps file (with php7 Imagick)

### ISSUE THREAD

**Issue by vedmant** [ImageMagick/ImageMagick#112]
Hi, I have a problem with converting images from .eps to .png when using Imagick php70 extension, it looks like this  http://screencast.com/t/rRtjTTf5B http://screencast.com/t/wgATl29POYN. I previously opened Issue in [Imagick](https://github.com/mkoppanen/imagick) repository [Issue 137](https://github.com/mkoppanen/imagick/issues/137) and got answer that this might be problem with invalid memory access in ImageMagick. So I opened issue here, hope you can help me with this.

Here are some reports from valgrind:
[php70-2.txt](https://github.com/ImageMagick/ImageMagick/files/108935/php70-2.txt)
[php56-2.txt](https://github.com/ImageMagick/ImageMagick/files/108936/php56-2.txt)
[convert-2.txt](https://github.com/ImageMagick/ImageMagick/files/108937/convert-2.txt)

**Comment by dlemstra** [comment]
Which version of Ghostscript are you using? This could be a bug in Ghostscript. When I convert your file on Windows with Ghostscript 9.15 I get a correct output image.

**Comment by vedmant** [comment]
I tried different Ghostscript versions, initially it was 9.07, I tried 9.18 and 9.16 which caused segmentation fault in php, then I downgraded to 9.14 that works.

**Comment by vedmant** [comment]
@dlemstra So what is the answer then?

**Comment by vedmant** [comment]
@dlemstra Probably I explained it wrong, I mean on GS 9.14 php doesn't crash with segmentation fault (like with GS > 9.16), but I'm getting the same noise on image when converting .eps files as with 9.07 version. I can also try to use 9.15.

**Comment by dlemstra** [comment]
Oh sorry, I assumed it was fixed. Are you using the latest version of ImageMagick btw?

**Comment by vedmant** [comment]
Yes, I use Version: ImageMagick 6.9.3-2 Q16 x86_64 2016-01-22. 

After some manipulations (reinstalling different versions) with ghostscript and ImageMagick I started to get this distorted images in all cases, convert, php56 and php70.

For convert command it appears when I save it with png32 instead of just png option (convert myfile.eps png32:output.png). 

For php it appears not all the time too, for example it shows normal image when I set resolution to 200x200 (but still shows bad image when I run script through php-fpm) also it works ok when I change image format to png instead of png32. There are other cases when image generated with errors, as I use compositeImage, shadowImage and other methods in the script, if it's important I can check in which cases image has errors.

In all cases when there are error in image, valgrind shows much more errors.

There are some valgrind reports and generated images examples:
![convert](https://cloud.githubusercontent.com/assets/5052406/12697418/3341f242-c748-11e5-8f10-8049c70f0ff9.png)
[convert.txt](https://github.com/ImageMagick/ImageMagick/files/110912/convert.txt)
![php56](https://cloud.githubusercontent.com/assets/5052406/12697419/3342e454-c748-11e5-8d9d-c6e02a0d0213.png)
[php56.txt](https://github.com/ImageMagick/ImageMagick/files/110911/php56.txt)
![php70](https://cloud.githubusercontent.com/assets/5052406/12697420/334416c6-c748-11e5-8a4a-44eaab056cd5.png)
[php70.txt](https://github.com/ImageMagick/ImageMagick/files/110910/php70.txt)

**Comment by dlemstra** [comment]
Are you able to reproduce this issue on the command line @vedmant ?

**Comment by vedmant** [comment]
@dlemstra Actually I replaced some used Imagick methods by different alternatives and this issue disappeared, however new problem appeared: occasional segfaults crashes in Ghostscript library, but that's different story.

**Comment by dlemstra** [comment]
Thanks for your reply, I will close this issue then.
