### ISSUE TITLE
7.0.7-29: t/filter.t fails

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1120]
Thanks for 7.0.7-29.

t/filter.t is failing for me with:
```
Draw(fill=>'none',stroke=>'gold',primitive=>'circle',points=>'60,90 60,120',strokewidth=>2) ...
  Draw (fill=>'none',stroke=>'gold',primitive=>'circle',points=>'60,90 60,120',strokewidth=>2): Exception 460: non-conforming drawing primitive definition `Circle' @ error/draw.c/DrawImage/3606
not ok 15
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
Yes, that works.

Thanks for incredibly quick response.

**Comment by pgajdos** [comment]
I think issue can be closed.
