### ISSUE TITLE
in Magick++ Magick::TypeMetric lacks some accessors to attributes of MagickCore TypeMetric

### ISSUE THREAD

**Issue by mbasaglia** [ImageMagick/ImageMagick#1121]
### Description
Magick::TypeMetric doesn't have accessors for:
* _TypeMetric::bounds
* _TypeMetric::origin
* _TypeMetric::pixels_per_em

Compare the C++ library

https://github.com/ImageMagick/ImageMagick/blob/master/Magick%2B%2B/lib/Magick%2B%2B/TypeMetric.h
https://github.com/ImageMagick/ImageMagick/blob/master/Magick%2B%2B/lib/TypeMetric.cpp

With the underlying C struct:

https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/draw.h#L360

**Comment by dlemstra** [comment]
Thanks for letting us know. The properties will be available in the next release.
