### ISSUE TITLE
convert(1) exit code not properly documented

### ISSUE THREAD

**Issue by paride** [ImageMagick/ImageMagick#1122]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

The manpage for compare(1) says:

> The compare program returns 2 on error otherwise 0 if the images are similar or 1 if they are dissimilar.

but no definition of *similarify* is given. When are two images considered similar? Which metric is used by default? Is the exit code affected by `-metric`?

**Comment by fmw42** [comment]
The similarity value as it means similar or dissimilar depends upon the metric. For example RMSE will be similar when the value is 0. NCC will be similar when the value is largest. AE is just a count of the dissimilar number of pixels. I believe the default is NCC, but am not positive about that. I would doubt that the exit code depends upon the metric. But the IM developer will need to give you a definitive answer on that and the default. More information about metrics can be found at https://www.imagemagick.org/Usage/compare/ especially in the statistics section.

**Comment by urban-warrior** [comment]
The compare program returns 2 on error otherwise 0 if the images are similar or 1 if they are dissimilar as defined by the metric and fuzz.  The normalized cross correlation error metric is an exception. For this metric, 1 is interpreted as two identical images.  With a non-zero fuzz, the source images might have some pixels that differ but are considered similar.  With a fuzz of zero, all pixels exactly match to be considered similar.

**Comment by paride** [comment]
Thanks @urban-warrior. So is it correct to say that with `-fuzz 0` (or when `-fuzz` is not specified), *similar* means *identical*?

I have read about the normalized cross correlation exception in https://www.imagemagick.org/script/compare.php:

> The compare program returns 2 on error otherwise 0 if the images are similar or 1 if they are dissimilar except for the default metric, the normalized cross correlation error metric. For this metric, 1 is interpretted as two identical images.

but in practice it doesn't seem to work like that. Given two identical images:
```
$ compare -metric AE reference.png test.png null:
0
```
the normlized cross correlation is indeed 1, but the exit code is not:
```
$ compare -metric NCC reference.png test.png null:
1
$ echo $?
0
```

**Comment by urban-warrior** [comment]
Your patch was added.  Thanks.
