### ISSUE TITLE
Stop removing old release and tag

### ISSUE THREAD

**Issue by adevress** [ImageMagick/ImageMagick#1124]
### Prerequisites

- [X ] I have written a descriptive issue title
- [X ] I have verified that I am using the latest version of ImageMagick
- [X ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

A lot of people and package managers use directly github as the upstream source for their installation. Please stop to delete old tags and release that are on the ImageMagick github repository. This is a very bad practice: a tag should be immutable and something we can rely on. When a version is published, it MUST stay available online, Please. I understand your will to push for recent release but builds of old versions should still be possible for reproducibility reasons ( it is important in the scientific world ).

All the 6.9.9-* versions of ImageMagick suddenly disappeared. Breaking the builds of people depending on it.

### Steps to Reproduce
git tag

**Comment by dlemstra** [comment]
See: https://github.com/ImageMagick/ImageMagick/issues/1101
