### ISSUE TITLE
non-conforming drawing primitive definition `rectangle' @ error/draw.c/DrawImage/4073

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#1125]
As of this week's release I see this error in both 6.9.9-43 and 7.0.7-31 when drawing a rectangle:
```
non-conforming drawing primitive definition `rectangle' @ error/draw.c/DrawImage/4073
```

**Comment by jeroen** [comment]
Actually the entire drawing api is broken 😢

**Comment by jeroen** [comment]
Actually there are multiple issues. Opening a separate issue.

**Comment by fmw42** [comment]
It would be most helpful if you provide your actual full command line and any relevant input images.

**Comment by jeroen** [comment]
I'm only using the C++ api via my bindings, but I can try to extract something.

**Comment by fmw42** [comment]
Sorry, I did not see your other posts with code in some of them. I thought you were using the command line. However, if you can create a very simple example to reproduce the issue, it would be most helpful for the IM developers to check it out.

**Comment by jeroen** [comment]
OK I found the problem. It happens when you draw a rectangle but specify the y axis is in the reverse direction, i.e. `y0 > y1`. Below a minimal example:

```cpp
#include <Magick++.h>

using namespace Magick;

#if MagickLibVersion >= 0x700
#define container vector
#else
#define container list
#endif

int main(){
  Image image(Geometry(800, 600), Color("thistle"));
  image.magick("PNG");

  //Draw rectangle
  std::container<Drawable> rect;
  rect.push_back(DrawableFillColor("pink"));
  rect.push_back(DrawableRectangle(400, 300, 640, 120));
  image.draw(rect);

  image.write(std::string("test.png"));
}
```

**Comment by urban-warrior** [comment]
The team has been busy with a security review of the ImageMagick code base.  In a few cases, some security patches broke things.  We fixed this problem as of the lastest commit.

**Comment by jeroen** [comment]
Thanks for the fix. Confirm that the error is now gone.
