### ISSUE TITLE
Drawing API completely broken IM6

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#1126]
Actually the entire drawing api is broken in IM6 😢You can just use any of the previous drawing examples I posted like this one: #996

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by jeroen** [comment]
Thanks the clipping problem fixed in HEAD. The other problem is here: https://github.com/ImageMagick/ImageMagick/issues/1125

**Comment by jeroen** [comment]
Actually it's not fixed. The example code linked above is supposed to show this:

![test7](https://user-images.githubusercontent.com/216319/39868263-21e798d0-5459-11e8-9a5c-137fc8a52f25.png)

However in the master branch of IM6 we see this:

![test](https://user-images.githubusercontent.com/216319/39868293-41d3c8bc-5459-11e8-807a-25c48ffa521a.png)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
