### ISSUE TITLE
Long running programs and time resource limit.

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#113]
Please can you advise on the problem below I'm facing using the MagickWand API:

* I want any image that takes more than 45 seconds to time out, so I've set the time resource limit to be 45 seconds.

* For performance reason I'm processing the images through Imagick/ImageMagick in a background process that runs continuously.

What I'm seeing is that:

* The background process processes one image.

* 45 seconds pass.

* Any requests to process images after that time generated the fatal error `time limit exceeded `Operation canceled' @ fatal/cache.c/GetImagePixelCache/1555.`

i.e. the time limit seems to be calculated since the time when the first image was processed, rather than individual image operations.

Is there any way to set a time limit for image processing, that can work with a long running image processor?

**Comment by urban-warrior** [comment]
The resource time limit is global.  You could reset the resource time limit after each image you process.  There is a MagickWand API call to do that.    Note the time of invocation of your first image.  Then set the resource time limit to 

    new_limit = time() - invocation_time + 45

**Comment by Danack** [comment]
> There is a MagickWand API call to do that.

Could you tell me which function you're referring to please? I'm aware of MagickSetResourceLimit, but that doesn't seem to affect the behaviour.

In particular, that function doesn't appear to reset the static `time_limit` function inside the [GetImagePixelCache function](https://github.com/ImageMagick/ImageMagick/blob/ImageMagick-6/magick/cache.c#L1551), which I believe is the thing that triggering the 'time out' for me?

Or am I just using it wrong?

**Comment by mikayla-grace** [comment]
You are right.  There is currently no way to limit time on a per image basis.  We only call GetMagickResourceLimit(TimeResource) once to reduce overhead when processing image scanlines.  A per image time limit would be a new feature.  You could propose it @ http://www.imagemagick.org/discourse-server/viewforum.php?f=2 to be considered for development in a future release of ImageMagick.

**Comment by Danack** [comment]
k - I've opened a discussion there, so will close this issue.

http://www.imagemagick.org/discourse-server/viewtopic.php?f=2&t=29083
