### ISSUE TITLE
heic support 

### ISSUE THREAD

**Issue by dineshkannaa** [ImageMagick/ImageMagick#1135]
may I know from which version heic is supported in image magick ?

**Comment by dlemstra** [comment]
Support was added in 7.0.7-23 and we made some big improvements in 7.0.7-29.

**Comment by dineshkannaa** [comment]
Thank you . I installed libde265 , but when I make the build it says "HEIC --with-heic=yes  value=no" . I want to use HEIC functions of Image Magick . could you tell what I'm doing wrong.

**Comment by dlemstra** [comment]
You will also need libheif.

**Comment by dineshkannaa** [comment]
libheif is released under GNU LGPL license . will there be any license problem if we used it for a commercial purpose .

**Comment by dlemstra** [comment]
libde265 also uses LGPL. I like this explanation about LGPL: https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3). Short answer, it depends.

**Comment by dineshkannaa** [comment]
Thank you
