### ISSUE TITLE
compilation error in make file

### ISSUE THREAD

**Issue by dineshkannaa** [ImageMagick/ImageMagick#1136]
I know its a silly one but help me to solve this issue , when I try to make ImageMagick-7.0.7-34  the error is MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `PNGSetExifProfile' , what I am missing ?

**Comment by abdelhady** [comment]
It happened with me too

**Comment by dlemstra** [comment]
A patch to resolve this has been pushed, we are planning to publish a new release very soon.
