### ISSUE TITLE
Redundant MngInfoFreeStruct()

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1139]
I think ReadOneMNGImage() should not free mng_info at all as ReadMNGImage() will do, if I understand correctly.
https://github.com/ImageMagick/ImageMagick/blob/master/coders/png.c#L5780

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
