### ISSUE TITLE
heic unsupported codec

### ISSUE THREAD

**Issue by finalnova** [ImageMagick/ImageMagick#1140]
### Description
`convert 'IMG_0875.HEIC' output.jpg`
When trying to change HEIC to JPG through the above command, the following error occurs.
```
convert: Unsupported feature: Unsupported codec `IMG_0875.HEIC' @ error/heic.c/IsHeifSuccess/121.
convert: no images defined `output.jpg' @ error/convert.c/ConvertImageCommand/3275.
```

identify file info `IMG_0875.HEIC HEIC 3024x4032 3024x4032+0+0 8-bit YCbCr 1.89983MiB 0.010u 0:00.049`

### System Configuration
- ImageMagick version: `ImageMagick 7.0.7-32 Q16 x86_64 2018-05-23`
- Environment (Operating system, version and so on): `centos7`
- Additional information:
```
libde265 : 1.0.4
libheif : 1.1.0
imagemagick : 7.0.7-32
```

```
# identify -list format | grep HEIC
HEIC* rw-   High Efficiency Image Format
```

```
# identify -version
Version: ImageMagick 7.0.7-32 Q16 x86_64 2018-05-23 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP
Delegates (built-in): bzlib djvu fontconfig freetype heic jng jpeg lcms lzma openexr pangocairo png tiff wmf x xml zlib
```

**Comment by urban-warrior** [comment]
ImageMagick calls the HEIC delegate library to decode or encode HEIC images.  The library is returning the exception you see.  Its likely that your HEIC image has an encoding that is not supported by the HEIC delegate library.  Contact the HEIC developers for additional information.

**Comment by dlemstra** [comment]
You can find the library here: https://github.com/strukturag/libheif

**Comment by AdityaChaganti** [comment]
@namjug-kim Any luck with this?

**Comment by meonkeys** [comment]
@AdityaChaganti see https://github.com/ImageMagick/ImageMagick/issues/1470#issuecomment-536409858 , it's probably libheif not finding de265 (a HEIC issue, not imagemagick).
