### ISSUE TITLE
Feature request: customization of TIFF compression predictor setting

### ISSUE THREAD

**Issue by courtarro** [ImageMagick/ImageMagick#1144]
I've searched the source code and it looks like [the setting for `TIFFTAG_PREDICTOR` is fixed](https://github.com/ImageMagick/ImageMagick/blob/master/coders/tiff.c#L3833) for various compression settings to `PREDICTOR_HORIZONTAL`. Two other settings are valid in the modern TIFF standard, and customizing the predictor could be offered to users via a new tag such as `-define tiff:predictor=3`. Observe that GraphicsMagick [added this feature back in 2009](http://www.graphicsmagick.org/ChangeLog-2009.html) and I imagine [a similar approach](http://hg.code.sf.net/p/graphicsmagick/code/file/535883a4cf4d/coders/tiff.c#l5073) could be made to bring it to ImageMagick.

Motivation: I've been searching for an answer to the question "Why does Adobe Lightroom CC not support 16-bit floating-point TIFF files produced by ImageMagick?" and I think this might be the key.

I don't know the politics regarding IM and GraphicsMagick - is it legal to port the feature from GM to IM? If so, would IM be amenable to a pull request by me to make this happen?

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by courtarro** [comment]
Amazing response time. Thanks. I was able to fetch a recent build this evening and found the output file to be successful. For future reference (anyone else who needs a 16-bit floating-point TIF that Lightroom can read), this is the command that works:

     magick "asdf.exr" -depth 16 -compress zip -define quantum:format=floating-point -define tiff:predictor=3 "asdf.tif"
