### ISSUE TITLE
OpenEXR: Build host has missing dependacy

### ISSUE THREAD

**Issue by ansenlong** [ImageMagick/ImageMagick#1145]
It seems as your build host has a missing dependency, it never building imagemagick with OpenEXR.

I verified this to kick start my own build process with docker:

Here is all the commands:

[root@75d3df5c7618 /]# yum -y update
[root@75d3df5c7618 /]# yum -y install gcc make gcc-c++ rpm-build
[root@75d3df5c7618 /]# yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
[root@75d3df5c7618 /]# curl https://www.imagemagick.org/download/linux/SRPMS/ImageMagick-7.0.7-35.src.rpm -o /ImageMagick-7.0.7-35.src.rpm

[root@75d3df5c7618 SOURCES]# mkdir -p /root/rpmbuild/SOURCES
[root@75d3df5c7618 SOURCES]# cd /root/rpmbuild/SOURCES
[root@75d3df5c7618 SOURCES]# rpm2cpio /ImageMagick-7.0.7-35.src.rpm |cpio -i
[root@75d3df5c7618 SOURCES]# yum-builddep -y /root/rpmbuild/SOURCES/ImageMagick.spec 

[root@75d3df5c7618 SOURCES]# rpm -qi OpenEXR-devel
Name        : OpenEXR-devel
Version     : 1.7.1
Release     : 7.el7
Architecture: x86_64
Install Date: Mon May 28 13:33:56 2018
Group       : Development/Libraries
Size        : 342156
License     : BSD
Signature   : RSA/SHA256, Fri Jul  4 04:03:14 2014, Key ID 24c6a8a7f4a80eb5
Source RPM  : OpenEXR-1.7.1-7.el7.src.rpm
Build Date  : Tue Jun 10 07:29:55 2014
Build Host  : worker1.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Vendor      : CentOS
URL         : http://www.openexr.com/
Summary     : Headers and libraries for building apps that use OpenEXR
Description :
Headers and libraries for building apps that use OpenEXR.

[root@75d3df5c7618 SOURCES]# rpmbuild -ba /root/rpmbuild/SOURCES/ImageMagick.spec 

Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/ImageMagick-7.0.7-35.x86_64
Wrote: /root/rpmbuild/SRPMS/ImageMagick-7.0.7-35.src.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/ImageMagick-7.0.7-35.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/ImageMagick-devel-7.0.7-35.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/ImageMagick-libs-7.0.7-35.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/ImageMagick-djvu-7.0.7-35.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/ImageMagick-doc-7.0.7-35.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/ImageMagick-perl-7.0.7-35.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/ImageMagick-c++-7.0.7-35.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/ImageMagick-c++-devel-7.0.7-35.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/ImageMagick-debuginfo-7.0.7-35.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.A5WLps
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd ImageMagick-7.0.7-35
+ /usr/bin/rm -rf /root/rpmbuild/BUILDROOT/ImageMagick-7.0.7-35.x86_64
+ exit 0
[root@75d3df5c7618 SOURCES]#

**Comment by urban-warrior** [comment]
We had problems building the RPM as root on CentOS 7, however, with a user login the RPM build completed without complaint.
