### ISSUE TITLE
confused if condition

### ISSUE THREAD

**Issue by bugfreecode** [ImageMagick/ImageMagick#1146]
https://github.com/ImageMagick/ImageMagick/blob/2d9deb32e44a60599fb37c530590afb1503feb0c/coders/jpeg.c#L363

 if (jpeg_info->err->num_warnings++ **>** JPEGExcessiveWarnings)

**Comment by urban-warrior** [comment]
Our logic appears proper.  We want to throw a warning until there are over a thousand and then suppress any additional warnings.
