### ISSUE TITLE
Please bump version when soname change

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick#1150]
Hi,

Soname have changed again (.5 => .6) in a patch version which is terribly hard to manage when we want to be able to install multiple version (ImageMagick6 package and default ImageMagick from the distro), especially because only version (7.0.7) is used for directory layout.

So, 7.0.8 will be better.

**Comment by urban-warrior** [comment]
The next time an SO bump is required, we will increment the micro version of IM as well.
