### ISSUE TITLE
boundary values of -gamma in ImageMagick 7

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1151]
Hello,

I have question about behavioral change between ImageMagick 6 and ImageMagick 7. I have tested with 6.9.9-46 and 7.0.7-34. The test is based on [example page](http://www.imagemagick.org/Usage/canvas/).

To be clear, I do not intend to create one color images that way; I consider this just as a testcase that could exhibit a bug potentially.

### 1. creating black image with -gamma 0
```
(A) convert  test.png  -gamma 0  -alpha off  black_gamma.png
(B) convert  test.png  \
           -channel red -gamma 0 \
           -channel green -gamma 0 \
           -channel blue -gamma 0 \
           -alpha off black_gamma.png
```
* both (A) and (B) works as described in the example page for 6.9.9-46 and both produce:
![black_gamma](https://user-images.githubusercontent.com/4067843/40647067-45f91f60-632b-11e8-9260-807865d5e5e8.png)
* both (A) and (B) both produce 7.0.7-34:
![black_gamma](https://user-images.githubusercontent.com/4067843/40647114-5d067496-632b-11e8-9b43-0b5906f2d877.png)

I have tried few triplets of -gamma: (1.0, 1.0, 1.0), (2.0, 2.0, 2.0), (2.0, 2.0, 1.0), (3.0, 3.0, 3.0), (0.5, 0.5, 0.5), (0.1, 0.1, 0.1) and of course (0, 0, 0). Results seem to my human eye to be equal for IM6 and IM7, except just (0, 0, 0).  Unfortunately I am far from being image processing expert and I do not see the reasoning behind the results.

### 2. creating yellow image with -gamma -1, -1, 0

This is perhaps related to previous problem. Consider following command:
```
(A) convert  test.png  -gamma -1,-1,0  -alpha off  yellow_gamma.png
(B) convert  test.png  \
          -channel red -gamma -1 \
          -channel green -gamma -1 \
          -channel blue -gamma 0  \
          -alpha off \
          yellow_gamma.png
```
* Command (A) will not work with ImageMagick 7 anymore, see [this topic](https://www.imagemagick.org/discourse-server/viewtopic.php?t=32312) for details.
* Both (A) and (B) commands produce pure yellow image for 6.9.9-46.
![yellow_gamma](https://user-images.githubusercontent.com/4067843/40648277-5225c916-632e-11e8-9432-461f15d04f49.png)
* (B) produces almost pure yellow image in ImageMagick 7, except the area with 
  pixels with fraction of blue in it.
![yellow_gamma](https://user-images.githubusercontent.com/4067843/40648707-5f398736-632f-11e8-95fa-1e485f21b225.png)

Again, if you consider this as not a bug, fine with me, we will adjust our test cases according to new results and/or Anthony's proposals sent privately.

Thank you!

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
This proves to be fixed for me, thanks a lot!
