### ISSUE TITLE
Clear composition method in ImageMagick 7

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1157]
Hello,

this is inspired by commands in [canvas example](http://www.imagemagick.org/Usage/canvas/#other) and [compose example](http://www.imagemagick.org/Usage/compose/#clear) pages. Neither of command from there containing Clear method have result in ImageMagick 7 I would  expect given results shown in these examples. To sum up, for following command:
```
composite -compose Clear null:  rose: compose_my.png
```
I get following result for 6.9.9-46:
![compose_my](https://user-images.githubusercontent.com/4067843/40707641-9973494c-63f1-11e8-827c-037dafea2be8.png)
but for 7.0.7-35 it results in
![compose_my](https://user-images.githubusercontent.com/4067843/40707672-b22d435c-63f1-11e8-87d5-ce4218633a9d.png)

Is this a bug or should this command be used differently in ImageMagick 7?

Thanks!

**Comment by dlemstra** [comment]
What happens when you put the commands in the correct order:

`composite  rose: -compose Clear null: compose_my.png`

**Comment by pgajdos** [comment]
Thanks for the reply.

This creates PNG 1x1 1x1+0+0 8-bit Gray 272B image.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
Indeed, the issue seems to be fixed 7.0.8-6. Thanks!
