### ISSUE TITLE
Error when installing: cannot compute sizeof (float_t)

### ISSUE THREAD

**Issue by tleunen** [ImageMagick/ImageMagick#1158]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
It fails to install because of the error `cannot compute sizeof (float_t)`

Not sure if I have something missing on my system, but any help would be appreciated

### Steps to Reproduce
Installing from homebrew
```
❯ brew install imagemagick --with-fontconfig
==> ./configure --disable-osx-universal-binary --prefix=/usr/local/Cellar/imagemagick/7.0.7-36 --disable-silent-rules --enable-shared --
Last 15 lines from /Users/tommy/Library/Logs/Homebrew/imagemagick/01.configure:
checking for ssize_t... yes
checking for uid_t in sys/types.h... yes
checking for uint8_t... unsigned char
checking for uint16_t... unsigned short int
checking for uint32_t... yes
checking for uint64_t... yes
checking for uintmax_t... no
checking for uintptr_t... yes
checking for unsigned long long int... (cached) yes
checking for locale_t... yes
checking for float_t... yes
checking for double_t... yes
checking size of float_t... configure: error: in `/private/tmp/imagemagick-20180530-96832-p9clby/ImageMagick-7.0.7-36':
configure: error: cannot compute sizeof (float_t)
```

### System Configuration

- ImageMagick version: 7.0.7-36
- Environment (Operating system, version and so on): mac os 10.13.4

**Comment by fmw42** [comment]
Does it work if you leave off --with-fontconfig? Why are you using --disable-osx-universal-binary? Does Mac OSX High Sierra need an INTEL environment, which perhaps needs the universal binary? I am not really an expert here. I install all my delegates from MacPorts and then install ImageMagick from source. That way I can always keep up with the current IM release

**Comment by tleunen** [comment]
I've tried with another machine and it works fine. So there's definitely something wrong on the other machine. With fontconfig or not, it doesn't change anything. And then the configure command is done automatically so I didn't explicitly choose to disable the universal binary.

The first machine was done using the migration assistant tool on mac os. So I'm pretty sure it did something wrong now. I'll reset everything again.

For this reason, I'll close the issue.
