### ISSUE TITLE
How to compare two images using imageMagick,JAVA & selenium

### ISSUE THREAD

**Issue by dipakbachhav** [ImageMagick/ImageMagick#1159]
I am trying to compare two images using ImageMagick but failed. Could you please help me with the working code for comparing two images ?

**Comment by dlemstra** [comment]
Are you using JMagick?

**Comment by dipakbachhav** [comment]
Hello Sir,

I am not using jmagick . I have working code with robot framework and currently looking for comparing two images. Could you please help me with working code?

**Comment by dlemstra** [comment]
Your question is really vague and you are not providing any details. What kind of help are you looking for?

**Comment by dipakbachhav** [comment]
Actually, I want to compare two images using image magick. So when we compare two images if images are different then I am expecting a fail result.  
I  have done image comparison using robot framework long time back(https://blog.codecentric.de/en/2017/09/robot-framework-compare-images-screenshots/) and now I am looking for the same solution using java code. Can you please help me with your valuable time and working solution ?

**Comment by urban-warrior** [comment]
We support using ImageMagick command-line or the C, C++, or .NET API's.  We generally cannot offer assistance with JMagick or Java.

**Comment by kowsalyadevi16** [comment]
The below code worked to compare two images. You can download the jar from the below location.

https://www.frontendtest.org/blog/screenshot-comparison/

import org.frontendtest.components.ImageComparison;

	public void img_compare(String org_img, String comp_img, String output_img) throws IOException {
		String imgOriginal = org_img;
		String imgToCompareWithOriginal = comp_img;
		String imgOutputDifferences = output_img;
		//Compare the two images mentioned above.
		//ImageComparison(pixelPerBlockX,pixelPerBlockY,Threshold)
		ImageComparison imageComparison = new ImageComparison(10,10,0.05);
		if(imageComparison.fuzzyEqual(imgOriginal,imgToCompareWithOriginal,imgOutputDifferences))
			log.info("Images are fuzzy-equal.");
		else
			log.error("Images are not fuzzy-equal.");
	}
