### ISSUE TITLE
cannot ignore the warning

### ISSUE THREAD

**Issue by bugfreecode** [ImageMagick/ImageMagick#1160]
https://github.com/ImageMagick/ImageMagick/blob/2d9deb32e44a60599fb37c530590afb1503feb0c/coders/jpeg.c#L363

during libjpeg execution，all WARNMS throw an exception, How can I ignore the warning and let the libjpeg continue?

Thanks for any suggestions。

**Comment by urban-warrior** [comment]
What do you mean by continue?  We have a corrupt JPEG image that issues a warning but the conversion completes because its a warning, not an error.    What behavior are you experiencing?

**Comment by bugfreecode** [comment]
what the purpose of JPEGExcessiveWarnings set to 1000?
if jpeg_info->err less than 1000, it will throw an exception, and then , the conversion will be finished.

i want the code continue run, if err_num less then 1000.
