### ISSUE TITLE
7.0.7 Testsuite returns 2 fails - Ubuntu 18.04

### ISSUE THREAD

**Issue by briligg** [ImageMagick/ImageMagick#1161]
After a fresh install of IM 7.0.7-37  Q16HDRI I ran 'make check', and the result had 2 fails: 
FAIL: tests/wandtest.tap 1
FAIL: Magick++/demo/demos.tap 6

test-suite.log is attached

My system is a recent install of Ubuntu 18.04, with all updates current. I have an i7 processor, 16 GB memory, and a GeForce 960GX graphics card.

[test-suite.log](https://github.com/ImageMagick/ImageMagick/files/2059190/test-suite.log)

**Comment by urban-warrior** [comment]
Install the Freetype delegate library, rebuild ImageMagick and rerun the tests.  Do the test still fail?

**Comment by briligg** [comment]
Freestyle wasn't installed when I did that test, it's true. Unfortunately, after installing a bunch of additional delegates and rebuilding, the 'make check' command isn't working for me, so I can't confirm that was the issue. It may not be relevant and have something to do with my system. 'Make check' in the IM folder returns 'make: *** No rule to make target 'check'.  Stop.'

**Comment by urban-warrior** [comment]
The unit tests must pass for us on a variety of systems before we release ImageMagick.  They can fail on some systems if they have missing dependencies or perhaps other unanticipated problems.  One of our development systems is Ubuntu 18.04 and the unit tests pass for us.
