### ISSUE TITLE
Bump libpng version in linux build (RPM)

### ISSUE THREAD

**Issue by ansenlong** [ImageMagick/ImageMagick#1164]
Would it be possible to bump the png version as well, our developers found transparent issues with the png format as it works on the mac version/build (Homebrew) but not on the linux version from libpng 1.5.13 to 1.6.34.

identify -list format|grep -i libpng
           See http://www.libpng.org/pub/mng/ for details about the JNG
      MNG* PNG       rw+   Multiple-image Network Graphics (libpng 1.6.34)
           See http://www.libpng.org/pub/mng/ for details about the MNG
      PNG* PNG       rw-   Portable Network Graphics (libpng 1.6.34)
           See http://www.libpng.org/ for details about the PNG format.

Linux system info:
# rpm -qa Image\*
ImageMagick-7.0.7-37.x86_64
ImageMagick-libs-7.0.7-37.x86_64

[root@rf-gen4-001 ~]# sha1sum /usr/bin/identify 
ead2730d0392c7c21a63e0c4607e31715ba89b76  /usr/bin/identify

As you can see png is not a dynamic so it should be safe to just include a newer version in the build process.
[root@rf-gen4-001 ~]# ldd /usr/bin/identify|grep -i png
[root@rf-gen4-001 ~]# ldd /usr/bin/convert|grep -i png

[root@rf-gen4-001 ~]# identify -list format|grep -i libpng
           See http://www.libpng.org/pub/mng/ for details about the JNG
      MNG* PNG       rw+   Multiple-image Network Graphics (libpng 1.5.13)
           See http://www.libpng.org/pub/mng/ for details about the MNG
      PNG* PNG       rw-   Portable Network Graphics (libpng 1.5.13)
           See http://www.libpng.org/ for details about the PNG format.

**Comment by dlemstra** [comment]
We do not maintain that RPM package so you should ask this question somewhere else.
