### ISSUE TITLE
Large number of list items in XMP bag metadata causes exponential slowdown reading image

### ISSUE THREAD

**Issue by johnbuuck** [ImageMagick/ImageMagick#1166]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When an image is being read that contains XMP meta-data with a node containing a large number of list-items, processessing seems to hang.

### Steps to Reproduce
Attempt to convert the attached TIFF image to a JPG image. The attached TIFF file contains an XMP profile that contains an &lt;XMP-photoshop:DocumentAncestors&gt; tag with over 184,000 &lt;rdf:li&gt; tags, The source code in xml-tree.c,
`      while ((node->ordered != (XMLTreeInfo *) NULL) &&
             (node->ordered->offset <= offset))
`
sequentially searches to find where to insert each of these list items and each search goes all the way to the end of the list so doing so to add 184,000 nodes essentially never completes.

### System Configuration
- ImageMagick version: 6.8.6, 6.8.8, 7.0.7
- Environment (Operating system, version and so on): Windows 7.0
- Additional information:

[2dc6c90a21ce478f9b80ba479db4818b.zip](https://github.com/ImageMagick/ImageMagick/files/2074238/2dc6c90a21ce478f9b80ba479db4818b.zip)

**Comment by urban-warrior** [comment]
We're using ImageMagick 7.0.7-38 and 6.9.9-49.  Your image converts within seconds.   Can you check these releases and let us know if the conversion still hangs.  If so, post the exact command you are using so we can try to reproduce the problem.

We could add a limit to how many XML nodes are permitted, however, if its a legitimate XMP profile, ImageMagick should read it.  We could also add a define to skip reading the profiles to speed up processing. Finally, we could add a resource limit on the maximum profile length.
