### ISSUE TITLE
Temp files are not deleted if program aborts due to exceeding time limit

### ISSUE THREAD

**Issue by ntsh** [ImageMagick/ImageMagick#1167]
### Prerequisites

- [✓] I have written a descriptive issue title
- [✓] I have verified that I am using the latest version of ImageMagick
- [✓] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
If a file conversion takes a time longer than the max time allocated in policy.xml, the program exits with an error. However the temporary files are not cleaned-up before exiting.

### Steps to Reproduce
Set following policy in policy.xml

    <policy domain="resource" name="area" value="1MP"/>
    <policy domain="resource" name="time" value="5"/>

Use a large image file : For example: [107 MB jpg](https://upload.wikimedia.org/wikipedia/commons/2/2c/A_new_map_of_Great_Britain_according_to_the_newest_and_most_exact_observations_%288342715024%29.jpg)

Command:

    > magick bigjpeg.jpg bigpng.png

Output:

    magick: time limit exceeded `Unknown error' @ fatal/cache.c/GetImagePixelCache/1703

Side effects:
Templ file  magick-* is created (624,908 KB) and not cleaned-up.

### System Configuration

- ImageMagick version: Using command line windows binary release - ImageMagick-7.0.7-38-Q16
- Environment (Operating system, version and so on): Windows 10 Pro, Version 1709

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
