### ISSUE TITLE
[7.0.7-30?+, win, x64] conjure does not read images anymore (wild guess)

### ISSUE THREAD

**Issue by AvalonCV** [ImageMagick/ImageMagick#1168]
Hello everybody,

I somehow struggle to get conjure to work in 7.0.7-30+. Every call ends with:

**conjure.exe: negative or zero image size `conjuretest.msl' @ error/image.c/SetImageExtent/2638.
conjure.exe: no decode delegate for this image format `conjuretest.msl' @ error/svg.c/ReadSVGImage/3243.**

This fails in 7.0.7-30 and 7.0.7-38. It does however work with version 7.0.7-9. I do not know the exact version it stopped working (hence the ? in the issue title).

### Steps to Reproduce
1. I used the wizard.png image that ships with IM, but it does not matter if it is a) a different image or b) a different image format.

2. the msl file

\<?xml version="1.0" encoding="UTF-8"?>
\<msl>
	\<group>
		\<image id="main">
			\<read filename="wizard.png" />
		\</image>
		\<write filename="wizardx.png" />
	\</group>
\</msl>

3. run "conjure {msl-file-name}"

-> should lead to the error. The same code works in 7.0.7-9

### System Configuration
- _ImageMagick version:_ 
7.0.7-30 and 7.0.7-38 (fail)
7.0.7-9 (works)
=> every version I used has been the portable x64 Windows Binary Release.

- _Environment (Operating system, version and so on):_
I tried this using Win10 Pro and Windows Server 2008 R2 (both 64bit).

[Update]
The reason why I think it may be related to how input images are read: even it I change to filename to something non-existing - the error remains the same (iirc the -9 version tells me that the file cannot be found).
[Update2]
Fixed </read in msl example

If you need further information please feel free to ask.

Best regards and have a nice day!

**Comment by dlemstra** [comment]
And `<\read` is a typo?

**Comment by AvalonCV** [comment]
@dlemstra : The <\read was something I messed up when creating this issue, sorry about that. I updated the example.

@fmw42 : Thanks for the advice but unfortunately even with `magick conjure {msl-file-name}` it still leads to the same 'negative or zero image size' message.

**Comment by AvalonCV** [comment]
That did it. I guess I expected it to work like in the older versions and based on the message I thought something might be wrong with the way IM + conjure handles the input image. 

Thank you very much for your help and have a nice day!
Best regards
