### ISSUE TITLE
-region not working for -selective-blur

### ISSUE THREAD

**Issue by YoitoFes** [ImageMagick/ImageMagick#1169]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
`-region` option does not working for `-selective-blur` correctly. The filter is applied to the whole of target image.

### Steps to Reproduce

Following command reproduce this bug.

```
 magick convert -region 5%x100% -selective-blur 5x5+5% image.bmp
```

### System Configuration

- ImageMagick version:  ImageMagick 7.0.7-38 Q16 x64
- Environment (Operating system, version and so on): Win 10 Pro (64 bit)

**Comment by fmw42** [comment]
-region require offsets to define the rectangular region (just like in -crop). Also for ImageMagick 7, use magick, not magick convert.

**Comment by YoitoFes** [comment]
Thanks for the help @fmw42 but I tried following commnad as you said and `-region` still does not work. `-selective-blur` is applied to the whole of the image.

```
magick src.bmp  -region 100x100+100+100 -selective-blur 5x5+5% dest.bmp
```

**Comment by fmw42** [comment]
Yes, it seems that is true, though the correct value should be 0x5+5%. But -blur 0x5 seems to work. So I think you may have found a bug with -region and -selective-blur. It looks like -region and -adaptive-blur fail also.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
