### ISSUE TITLE
Image shade changes while converting a tiff to jpg with RGB colorspace

### ISSUE THREAD

**Issue by sw-craftsman** [ImageMagick/ImageMagick#1170]
### Prerequisites

- [✓] I have written a descriptive issue title
- [✓] I have verified that I am using the latest version of ImageMagick
- [✓] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I convert attached tiff file to jpg mentioning color-space as RGB, its shade changes from brownish to greenish. It produces expected output when we don't pass color-space or keep it 'CMYK', source file is of CMYK type but I am looking for an RGB output.

### Steps to Reproduce
convert.exe "Sample.tif" "Output_Default.jpg"
convert.exe "Sample.tif" -colorspace RGB "Output_RGB.jpg"
convert.exe "Sample.tif" -colorspace CMYK "Output_CMYK.jpg"

### System Configuration
- ImageMagick version: I am using 6.9.2.6 (but it's reproducible with latest version 6.9.9-50 as well)
- Environment (Operating system, version and so on): Windows 7, Windows Server 2012
- Additional information:

[Files.zip](https://github.com/ImageMagick/ImageMagick/files/2090481/Files.zip)

Thanks

**Comment by fmw42** [comment]
colorspace RGB is linear and has color shifts, thus not what you likely want. Try -colorspace sRGB.

`convert.exe "Sample.tif" -colorspace sRGB "Output_RGB.jpg"`

**Comment by sw-craftsman** [comment]
Thanks for reply ... but sRGB is producing same output as RGB.

I understand RGB is linear but technically don't you think it's a bug ? Even though source file is CMYK ImageMagick isnt' supposed to retain original colors while converting it to JPG with RGB ? I thought that was a valid expectation.

**Comment by fmw42** [comment]
It works fine for me on IM 6.9.9.50 Q16 Mac OSX. The result is quite different from -colorspace RGB.

But you would get better results using profiles to do the conversion.

**Comment by sw-craftsman** [comment]
@fmw42, would you mind sharing your sRGB profile and the output with me ?

I tried sRGB.icc that comes with IM and also another one that I had (attaching both), but output continues to remain exactly same, so even passing the profile isn't making any difference.

I use it like this : convert.exe "Sample.tif" -profile "sRGB.icc" -colorspace "sRGB" "Output.jpg" ... hope this is a correct command.

[Profiles.zip](https://github.com/ImageMagick/ImageMagick/files/2092890/Profiles.zip)

Thanks

**Comment by fmw42** [comment]
Your image is CMYK with no profile. So you need to add a CMYK profile, then an sRGB profile and not use -colorspace.

Here are two results:


convert Sample.tif -colorspace sRGB output1.jpg



convert Sample.tif -profile /Users/fred/images/profiles/USWebCoatedSWOP.icc -profile /Users/fred/images/profiles/sRGB.icc output2.jpg









Profiles:

**Comment by sw-craftsman** [comment]
@fmw42, Ok I tried both commands, output1 is exactly same as before, output2 is somewhat better but still there is a noticeable difference, attaching screenshot, I have kept both icc profile files in the current folder where convert.exe is present. Don't know what am I missing :(

![display](https://user-images.githubusercontent.com/40173975/41312733-79a0830a-6ea5-11e8-8be8-5feb05417052.png)

**Comment by fmw42** [comment]
On my Mac in Preview, I do not see as much change as you show here. Viewers may present different results. What are you using to view the images and make screen snaps? The screen snaps may also change the results.

Fred

**Comment by fmw42** [comment]
You can try different CMYK and RGB profiles to see if you can make it look better. 

Also since the Sample.tiff is CMYK without a profile, it may look different for different viewers. So you should attach a CMYK profile to it so that viewers will try to present a more consistent result when viewing.

Fred

**Comment by sw-craftsman** [comment]
I had opened images in Microsoft Photo which is the default s/w on my Windows 10 laptop, then print-screen, and paste in MSPaint, I didn't notice any change in the display at any stage.

This sample.tif is created by someone else, so I cannot attach a profile to it or update it in any manner, I will try different CMYK and RGB profiles as you suggested.

Thanks.
