### ISSUE TITLE
command exception

### ISSUE THREAD

**Issue by dineshkannaa** [ImageMagick/ImageMagick#1171]
while processing a image file this exception occurs . 

org.im4java.core.CommandException: org.im4java.core.CommandException: identify: Expected 8192 bytes; found 3803 bytes `magick-15960zGA4DKwboUwQ' @ warning/png.c/MagickPNGWarningHandler/1744.

**Comment by dlemstra** [comment]
This is a warning that can be ignored but it looks like the `org.im4java.core` library also throws an exception. We did not write or main that library so I don't know how you can `quiet` warnings.
