### ISSUE TITLE
bmp file exception

### ISSUE THREAD

**Issue by dineshkannaa** [ImageMagick/ImageMagick#1172]
while processing a .bmp file this exception occurs .

org.im4java.core.CommandException: identify: length and filesize do not match `magick-16124iGaniDrrYZu3' @ error/bmp.c/ReadBMPImage/825."" ""org.im4java.core.InfoException: org.im4java.core.CommandException: org.im4java.core.CommandException: identify: length and filesize do not match `magick-16124iGaniDrrYZu3' @ error/bmp.c/ReadBMPImage/825.

**Comment by dlemstra** [comment]
This is most likely happening because your BMP file is corrupt. Can you share the image?

**Comment by dineshkannaa** [comment]
this error is occuring for all bmp files .. I have attached a sample bmp file I used .
[LAND2.BMP.zip](https://github.com/ImageMagick/ImageMagick/files/2110937/LAND2.BMP.zip)

**Comment by urban-warrior** [comment]
The BMP image encodes a file length of 787512 bytes whereas the actual filesize is 787510 bytes.  ImageMagick is informing you of this discrepancy.

**Comment by LeahPike** [comment]
Is it possible for ImageMagick to continue with the file and correct it?

**Comment by urban-warrior** [comment]
Recent releases of ImageMagick throws an exception but continues processing.

**Comment by LeahPike** [comment]
I'm running version 7.22.0 and it throws the exception and then doesn't continue, I'm making a new image with the following code:

``` c#
using (var image = new MagickImage(inputMemoryStream))
```

We're going through an existing library of files within our database and processing them to make the file sizes smaller.

Here is the file causing the issue: [error file.zip](https://github.com/ImageMagick/ImageMagick/files/5674920/error.file.zip)

**Comment by urban-warrior** [comment]
The is no ImageMagick version 7.22.0.  The current release, 7.0.10-47 can read your file and process it along with an exception warning a mismatched length and filesize attributes.

**Comment by LeahPike** [comment]
My mistake we're using Magick.NET version 7.22.0

**Comment by dlemstra** [comment]
Your file is corrupt but you can do this to ignore that inside Magick.NET:

```C#
// This works in the current release
var settings = new MagickReadSettings(new BmpReadDefines
{
    IgnoreFileSize = true,
});

using (var image = new MagickImage("error file.BMP", settings))
{
}

// This will be possible in the next release:
var bmpReadDefines = new BmpReadDefines
{
    IgnoreFileSize = true,
};

using (var image = new MagickImage("error file.BMP", bmpReadDefines))
{
}
```
