### ISSUE TITLE
Cent OS : no decode delegate for this image format `/tmp/magick-JkCvoQ54' @ error/constitute.c/ReadImage/544

### ISSUE THREAD

**Issue by gmandar4** [ImageMagick/ImageMagick#1174]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

I have used following Packages to install libde256 
sudo yum install git -y
sudo yum group install "Development Tools" -y
git clone https://github.com/strukturag/libde265.git 
cd libde265
 /bash autogen.sh
./configure --disable-dec265 --disable-sherlock265
make
sudo make install

I am still facing problem of converting .heic to .jpg 

My Imagemagick version is imagemagick-7.0.8-0
--

--

**Comment by urban-warrior** [comment]
The libheif delegate library is required to read / write the HEIF image format.

**Comment by gmandar4** [comment]
Not able to install libheif delegate library in centos. How to install it...?

**Comment by urban-warrior** [comment]
We can help you with installing ImageMagick but you will need to check with the libheif team for help the HEIF delegate library.
