### ISSUE TITLE
Feature: "Amount" control for Floyd-Steinberg dither

### ISSUE THREAD

**Issue by oli414** [ImageMagick/ImageMagick#1175]
With some small additions to the Floyd-Steinberg dithering algorithm, it becomes possible to control the amount of dither like you can do in Photoshop (Diffusion Amount).

I propose that an additional optional parameter is added to the dither option. This would be a percentage value with a default value of 100%.

In my fork, you can see how the Floyd-Steinberg algorithm would have to be modified to allow for more control. In the example, the amount is set to 35%. The result is nearly identical to what setting the dither amount in Photoshop to 35% would produce.
https://github.com/oli414/ImageMagick/commit/a62046cfd1d81e0f41767e38d5a5cd2af6861af3

**Comment by urban-warrior** [comment]
We'll have a patch in the next point release of ImageMagick.  The control will likely be -define dither:antenuate=35%.

**Comment by oli414** [comment]
Sounds great. I was hoping to implement it myself but I was unable to figure out how I would go about adding an option. I'm looking forward to this addition.

**Comment by urban-warrior** [comment]
Patch applied in the Gitlab Master.  Use `-dither floyd-steinberg  -define dither:diffusion-amount=35% -colors 250`.

**Comment by dlemstra** [comment]
@oli414 Next time when you want to add something please let us know in advance so we can assist you in adding it.
