### ISSUE TITLE
leak in Read?Image in ycbcr.c, rgb.c, bgr.c, gray.c and cmyk.c

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1179]
This is follow-up of  #1041.
Should not more clean-up happen at:
https://github.com/ImageMagick/ImageMagick/blob/master/coders/bgr.c#L985
?
I mean at least quantum_info and canvas_image is not freed, perhaps also CloseBlob(image) should be called? Or just break instead of return?

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
