### ISSUE TITLE
identify: improper image header

### ISSUE THREAD

**Issue by Skalkaz** [ImageMagick/ImageMagick#1182]
I got the error (see title) for this specific link:
http://www.compoundchem.com/wp-content/uploads/2016/05/A-Guide-to-Common-Polyatomic-Ions-%E2%80%93-Colour-Version.png

Tell me if you can't reproduce the error and environment needed.

**Comment by dlemstra** [comment]
It seems that you decided to delete the issue template. Can you please tell us which version of ImageMagick you are using and which platform you are running this on?

**Comment by Skalkaz** [comment]
MacOs 10.13.4
Version: ImageMagick 7.0.7-28 Q16 x86_64 2018-03-25 http://www.imagemagick.org

AND

Amazon Linux AMI 2018.03
Version: ImageMagick 6.7.8-9 2016-06-22 Q16 http://www.imagemagick.org

**Comment by urban-warrior** [comment]
Your image converts without complaint for us.  We're using ImageMagick ImageMagick-7.0.8-5 and 6.9.10-5.
