### ISSUE TITLE
PerlMagick error: setpixel/SetPixel redefined.

### ISSUE THREAD

**Issue by stoecker** [ImageMagick/ImageMagick#1184]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed]

### Description

With newest openSUSE Leap usage of ImageMagick in Perl results in disturbing warnings which fill the Apache error log when used from CGI scripts:

Call
perl -We 'use Image::Magick;'

Get
Subroutine Image::Magick::Q16HDRI::setPixel redefined at /usr/lib/perl5/5.26.1/x86_64-linux-thread-multi/DynaLoader.pm line 210.
Subroutine Image::Magick::Q16HDRI::setpixel redefined at /usr/lib/perl5/5.26.1/x86_64-linux-thread-multi/DynaLoader.pm line 210.

I assume it has to do with the setpixel/setPixel in the ALIAS of SetPixels/SetPixel function in ./PerlMagick/quantum/quantum.xs.in, as this is the only place where lowercase setpixel exists. I assume defining the same value twice is not really allowed and now issues a warning it did not with previous perl versions.

### System Configuration

ImageMagick 7.07 or 7.0.8.3, probably older versions as well.
Perl version: v5.26.1
System: Linux openSUSE Leap 15.0 (newest)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
