### ISSUE TITLE
Recent change breaks build on Cygwin

### ISSUE THREAD

**Issue by ennss** [ImageMagick/ImageMagick#1186]
A recent change (7.0.8.3(?), probably involving the windows build) has broken the build on Cygwin, where some includes are duplicated:

  CC       MagickCore/MagickCore_libMagickCore_7_Q32HDRI_la-deprecate.lo
In file included from /usr/include/w32api/winsock2.h:56:0,
                 from ./MagickCore/studio.h:126,
                 from MagickCore/deprecate.c:48:
/usr/include/w32api/psdk_inc/_fd_types.h:100:2: warning: #warning "fd_set and as
sociated macros have been defined in sys/types.      This can cause runtime prob
lems with W32 sockets" [-Wcpp]
 #warning "fd_set and associated macros have been defined in sys/types.  \
  ^~~~~~~
In file included from ./MagickCore/studio.h:126:0,
                 from MagickCore/deprecate.c:48:
/usr/include/w32api/winsock2.h:995:34: error: conflicting types for `select'
   WINSOCK_API_LINKAGE int WSAAPI select(int nfds,fd_set *readfds,fd_set *writef
ds,fd_set *exceptfds,const PTIMEVAL timeout);
                                  ^~~~~~
In file included from /usr/include/sys/types.h:68:0,
                 from /usr/include/stdio.h:61,
                 from ./MagickCore/studio.h:59,
                 from MagickCore/deprecate.c:48:
/usr/include/sys/select.h:62:5: note: previous declaration of `select' was here
 int select __P ((int __n, fd_set *__readfds, fd_set *__writefds,
     ^~~~~~
In file included from ./MagickCore/studio.h:126:0,
                 from MagickCore/deprecate.c:48:
/usr/include/w32api/winsock2.h:1004:34: error: conflicting types for `gethostnam
e'
   WINSOCK_API_LINKAGE int WSAAPI gethostname(char *name,int namelen);
                                  ^~~~~~~~~~~
In file included from /usr/include/unistd.h:4:0,
                 from ./MagickCore/studio.h:94,
                 from MagickCore/deprecate.c:48:
/usr/include/sys/unistd.h:300:6: note: previous declaration of `gethostname' was
 here
  int gethostname (char *__name, size_t __len);
      ^~~~~~~~~~~
In file included from MagickCore/deprecate.c:48:0:
./MagickCore/studio.h:129:0: warning: ignoring #pragma comment  [-Wunknown-pragm
as]
 #pragma comment (lib, "ws2_32.lib")

In file included from ./MagickCore/studio.h:241:0,
                 from MagickCore/deprecate.c:48:
./MagickCore/nt-base.h:32:0: warning: "_CRT_SECURE_NO_DEPRECATE" redefined
 #define _CRT_SECURE_NO_DEPRECATE  1
.....

Making the following changes to MagickCore/studio.h  allows the build to complete:

Change: 
#if defined(MAGICKCORE_WINDOWS_SUPPORT)
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#pragma comment (lib, "ws2_32.lib")
#endif

to:  

#if defined(MAGICKCORE_WINDOWS_SUPPORT)
#if !defined(__ CYGWIN __)
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#endif
#pragma comment (lib, "ws2_32.lib")
#endif

and:  

#if defined(MAGICKCORE_WINDOWS_SUPPORT)
# include "MagickCore/nt-base.h"
#endif

to:

#if defined(MAGICKCORE_WINDOWS_SUPPORT)
#if !defined(__ CYGWIN __)
# include "MagickCore/nt-base.h"
#endif
#endif

(So we don't want MAGICKCORE_WINDOWS_SUPPORT defined if we're on CYGWIN ??)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
