### ISSUE TITLE
The "--" command line option in convert (at least) does not work (any more)

### ISSUE THREAD

**Issue by rlepigre** [ImageMagick/ImageMagick#1187]
In previous versions, one could use the standard "end of options" marker `--` on the command line. For example, one could then use the following command.
```bash
# convert -- input.png output.jpg
```
And this is useful if you work with files which names start with a dash.

However, this does not work anymore (on my system at least).
```bash
# convert -- input.png output.jpg
convert: unrecognized option `--' @ error/convert.c/ConvertImageCommand/3262.
```
I am running Archlinux, and here are the result of relevant commands.
```bash
# uname -r
4.16.13-2-ARCH
# zsh --version
zsh 5.5.1 (x86_64-unknown-linux-gnu)
# convert --version
Version: ImageMagick 7.0.8-3 Q16 x86_64 2018-06-25 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP 
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib
```

I know that the `--` option still works with the following version.
```
Version: ImageMagick 6.9.9-28 Q16 amd64 2018-06-24 http://www.imagemagick.org
Version: ImageMagick 6.9.9-34 Q16 x86_64 20180122 http://www.imagemagick.org
```

**Comment by urban-warrior** [comment]
We're using ImageMagick 6.9.10-4, the current release, and your command works as expected, completes, and does not throw an exception.

**Comment by rlepigre** [comment]
@urban-warrior Thanks for you answer, but as I said in the above I observed the problem with ImageMagick 7.0.8-3. As far as I know, there is no issue with versions 6.9.X-Y or 6.10.X.Y.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
