### ISSUE TITLE
 Class 'imagick' not found

### ISSUE THREAD

**Issue by gmandar4** [ImageMagick/ImageMagick#1188]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Class 'imagick' not found (PHP)
### System Configuration

- ImageMagick version:  ImageMagick 7.0.8-3
- Environment (centos,):
- Additional information:
I have installed image ImageMagick 7.0.8-3.
It is working with cmd. 
But when using it in php it shows  Class 'imagick' not found.

**Comment by fmw42** [comment]
Imagick is not created nor provided by the Imagemagick organization. It is a separate tool. See https://pecl.php.net/package/imagick
