### ISSUE TITLE
Fail of 2 tests of the test-suite

### ISSUE THREAD

**Issue by zsuzsika** [ImageMagick/ImageMagick#1189]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Fail of two tests of the test-suite
### Steps to Reproduce

After successful installation of ImageMagick, I run the command 'make check'. Two tests failed, to log is attached.
### System Configuration

I use Linux.
- ImageMagick version: 7.0.8-3
- Environment (Operating system, version and so on): Debian
[test-suite.log](https://github.com/ImageMagick/ImageMagick/files/2157847/test-suite.log)

- Additional information:

**Comment by urban-warrior** [comment]
Ghostscript must be installed oln your system before the ImageMagick unit test suite will succeed.
