### ISSUE TITLE
coders/pcd.c ReadPCDImage()function potential memory-leak bug

### ISSUE THREAD

**Issue by fisher2020** [ImageMagick/ImageMagick#1194]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce
the bug is in this location:
https://github.com/ImageMagick/ImageMagick/blob/master/coders/pcd.c#L551
the code is as follows:
```
 header=(unsigned char *) AcquireQuantumMemory(0x800,3UL*sizeof(*header)); //allocate header
  if (header == (unsigned char *) NULL)
    ThrowReaderException(ResourceLimitError,"MemoryAllocationFailed");
  chroma1=(unsigned char *) NULL;
  chroma2=(unsigned char *) NULL;
  luma=(unsigned char *) NULL;
  count=ReadBlob(image,3*0x800,header);
  if (count != (3*0x800))
    ThrowPCDException(CorruptImageError,"ImproperImageHeader"); //did not free header 
  overview=LocaleNCompare((char *) header,"PCD_OPA",7) == 0;
  if ((LocaleNCompare((char *) header+0x800,"PCD",3) != 0) && (overview == 0))
    ThrowPCDException(CorruptImageError,"ImproperImageHeader"); //did not free header
  rotate=header[0x0e02] & 0x03;
  number_images=((header[10] << 8) | header[11]) & 0xffff;
  header=(unsigned char *) RelinquishMagickMemory(header);
  if ((overview != 0) &&
      (AcquireMagickResource(ListLengthResource,number_images) == MagickFalse))
    ThrowPCDException(ResourceLimitError,"ListLengthExceedsLimit"); // did not free header
```
credit : www.vackbot.com  (墨云科技)
### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
Not a memory leak or we cannot reproduce the problem.  Notice the ThrowPCDException() macro has code to free the header:
```
#define ThrowPCDException(exception,message) \
{ \
  if (header != (unsigned char *) NULL) \
    header=(unsigned char *) RelinquishMagickMemory(header); \

```
If you still feel there is a leak, we'll need a method to reproduce the leak.

**Comment by fisher2020** [comment]
@urban-warrior ,thanks your remind. it is not a memory leak.
