### ISSUE TITLE
memory leak bug in MagickCore/animate.c: XAnimatelmages() function at line 1912

### ISSUE THREAD

**Issue by 921580451** [ImageMagick/ImageMagick#1197]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

hello,i find a memory leak bug in imagemagick,the details is on the Steps to Reproduce.

### Steps to Reproduce

the bug located in animate.c,
MagickExport Image *XAnimateImages(Display *display,
  XResourceInfo *resource_info,char **argv,const int argc,Image *images,
  ExceptionInfo *exception) functiion at line 1912
the bug code is on
https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/animate.c#L1912
the code fragment is as follows:
```
windows->image.pixmaps=(Pixmap *) AcquireQuantumMemory(number_scenes,
    sizeof(*windows->image.pixmaps));
  windows->image.matte_pixmaps=(Pixmap *) AcquireQuantumMemory(number_scenes,
    sizeof(*windows->image.pixmaps));
```

we can see that we allocate a memory and assigned it to windows->image.pixmaps and windows->image.matte_pixmaps. In case of meeting the conditions, it is possible that one of them is not free in the code::
https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/animate.c#L1916
the code fragment is as follows:
```
 if ((windows->image.pixmaps == (Pixmap *) NULL) ||
      (windows->image.matte_pixmaps == (Pixmap *) NULL))
    ThrowXWindowFatalException(ResourceLimitFatalError,"MemoryAllocationFailed",
      images->filename);
```
credit：www.vackbot.com(墨云科技)

**Comment by urban-warrior** [comment]
Not a memory leak.  Notice the ThrowXWindowFatalException().  A fatal exception calls system exit() and terminates the program freeing *all* memory consumed by the ImageMagick instance.
