### ISSUE TITLE
memory leak bug in coders/art.c: ReadARTImage() function

### ISSUE THREAD

**Issue by 921580451** [ImageMagick/ImageMagick#1198]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

hello,i find a memory leak bug in imagemagick,the details is on the Steps to Reproduce.

### Steps to Reproduce

the bug located in coders/art.c,
static Image *ReadARTImage(const ImageInfo *image_info,ExceptionInfo *exception) functiion
the bug code is on
https://github.com/ImageMagick/ImageMagick/blob/master/coders/art.c#L156
the code fragment is as follows:
```quantum_info=AcquireQuantumInfo(image_info,image);```

we can see that we allocate a memory and assigned it to quantum_info,but we forget to free it in the code:
https://github.com/ImageMagick/ImageMagick/blob/master/coders/art.c#L183
the code fragment is as follows:
```
if (y < (ssize_t) image->rows)
    ThrowReaderException(CorruptImageError,"UnableToReadImageData");
  if (EOFBlob(image) != MagickFalse)
    ThrowFileException(exception,CorruptImageError,"UnexpectedEndOfFile",
      image->filename);
```

credit：www.vackbot.com(墨云科技)

**Comment by urban-warrior** [comment]
Unfortunately, we cannot reproduce the problem. The quantum_info variable is freed @ https://github.com/ImageMagick/ImageMagick/blob/master/coders/art.c#L182.  If we force the exception, valgrind, our memory debugger does not report any leaked memory.
