### ISSUE TITLE
Resizing an image with -filter Lanczos crops it, resizes wrong

### ISSUE THREAD

**Issue by akunohomu** [ImageMagick/ImageMagick#1200]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When resizing an image using -filter Lanczos -distort Resize, the output image has the bottom cropped.

### Steps to Reproduce
Input image: https://i.imgur.com/LWpzMG7.png

Good commandline: `magick.exe LWpzMG7.png -resize 1300x99999 out_good.png`  
Image is resized to 1300x527, as expected.

Bad commandline: `magick.exe LWpzMG7.png -filter Lanczos -distort Resize 1300x99999 out_bad.png`  
Image is resized to 1292x430, missing significant area on the bottom.

### System Configuration

- ImageMagick version: `Version: ImageMagick 7.0.8-4 Q16 x64 2018-07-03 http://www.imagemagick.org`, portable version downloaded from website
- Environment (Operating system, version and so on): Windows 10 x64, Intel i7-5820k
- Additional information: Also occurs with my own build of 7.0.7-31

**Comment by urban-warrior** [comment]
We cannot reproduce this problem on our Linux systems.  We'll try to reproduce under Windows when we get a chance.
