### ISSUE TITLE
[Homebrew] curl: (3) <url> malformed

### ISSUE THREAD

**Issue by rob-keepsafe** [ImageMagick/ImageMagick#1202]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Fails to install using Homebrew (e.g. `$ brew install imagemagick librsvg`)  with a `curl: (3) <url> malformed` error.

Failing install: https://gist.github.com/rob-keepsafe/90b9b943a67d53e6e853b6491b3dc012 
Passing install: https://gist.github.com/rob-keepsafe/6f9a2357495e4b9f333d3dee7f27300b 

### Steps to Reproduce

I'm currently seeing this while installing on CircleCI.

### System Configuration

More info on machine config: https://circle-macos-docs.s3.amazonaws.com/image-manifest/build-405/index.html 

- ImageMagick version: imagemagick-7.0.8-6.high_sierra.bottle.tar.gz
- Environment (Operating system, version and so on): macOS 
- Additional information: Xcode 9.3

**Comment by dlemstra** [comment]
We don't maintain the brew package of ImageMagick. It looks like you can report an issue through this page: http://brewformulas.org/Imagemagick.

**Comment by rob-keepsafe** [comment]
Thanks. Seems there were some corrupted formulae or components, so explicitly running `brew update` before each install on a new VM resolved things.
