### ISSUE TITLE
LinearGRAYColorspace is missing in Magick++ Include.h

### ISSUE THREAD

**Issue by danomimanchego123** [ImageMagick/ImageMagick#1204]
Not long ago, ``LinearGRAYColorspace`` was added to ```MagickCore/colorspace.h```, but there's no corresponding ``using`` lines in ``Magick++/Include.h``.  So, you cannot reference ``Magick::LinearGRAYColorspace`` in C++ code.  The other enums are there, so this seems like an oversight.

- ImageMagick version: found in **7.0.7-38.tar.gz** but the line is still missing in GitHub head.
- Environment: cross-compile using buildroot.

**Comment by dlemstra** [comment]
Thanks for reporting this. This will be resolved in the next release of ImageMagick.
