### ISSUE TITLE
Missing check for image in coders/txt.c

### ISSUE THREAD

**Issue by Young-X** [ImageMagick/ImageMagick#1207]
### Prerequisites

- [ Y ] I have written a descriptive issue title
- [ Y ] I have verified that I am using the latest version of ImageMagick
- [ Y ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

There is a missing check for image in coders/txt.c. I think this is the same issue as #591 and the patch for #591 is a8f9c2aabed37cd6a728532d1aed13ae0f3dfd78.

### Steps to Reproduce

There is a missing check for image in coders/txt.c. (https://github.com/ImageMagick/ImageMagick/blob/master/coders/txt.c#L591)

In my opinion, below is the proposal patch.

```
    if (status == MagickFalse)
      break;
    *text='\0';
 +    if (EOFBlob(image) != MagickFalse)
 +      {
 +        ThrowFileException(exception,CorruptImageError,"UnexpectedEndOfFile",
 +          image->filename);
 +        break;
 +      }
      (void) ReadBlobString(image,text);	
```

### System Configuration

- ImageMagick version: latest version
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
Can you clarify why we need that check? `*text='\0';` should make sure break the loop.

**Comment by Young-X** [comment]
sorry for reporting this issue. I checked the code and found this is not a bug.
