### ISSUE TITLE
[Feature Request] Store illuminant matrices and provide quick option for conversion

### ISSUE THREAD

**Issue by tomdl89** [ImageMagick/ImageMagick#1212]
ImageMagick uses a D65 [Standard Illuminant](https://en.wikipedia.org/wiki/Standard_illuminant) as reference white when converting from sRGB.

If the user wants to use a different illuminant, they have to look up the [chromatic adaptation transform](http://www.brucelindbloom.com/Eqn_ChromAdapt.html) and use this with the `-colorspace XYZ` and `-color-matrix` options before converting.

I would like to see the chromatic adaptation transform matrices added to the code, and a new option added (a name like `-illuminant` would do) with parameters (like `D50` `D55` `E` etc) which ImageMagick treats as a shortcut to these matrices.

This would make the command simpler to type and less error prone. If I had the coding skills to implement this, I would, so I'm hoping someone who does would be willing! Thanks

**Comment by urban-warrior** [comment]
We need a few reference conversions so we can check that our chromatic adaptation transform to or from the XYZ colorspace is returning expected results.  Post several conversions of D65 XYZ to another illuminant with the -colorspace XYZ and -color-matrix command-line options.  We'll use your conversions as sanity checks against any coding solution we come up with before we commit the patch to the ImageMagick source repository.

**Comment by urban-warrior** [comment]
We added support for the -illuminant option as you requested.  It will be available for testing by sometime tomorrow.
