### ISSUE TITLE
How to tint a png image in C?

### ISSUE THREAD

**Issue by internalG** [ImageMagick/ImageMagick#1216]
I have little knowledge about graphics. I think there should be a simple function but ImageMagick is too big. My files are in
https://www.dropbox.com/sh/qz6l51aulyfq34l/AACuIMcDatbIWQ5IzdnXsLLqa?dl=0

graypin.png is the source file, redpin.svg is its desired look with red(EB1F23) tint. SVG does it by the filter. I need to do the same in C. So with C code I'd done load the png pixels in RGBA, but still can't find the key of tintred = red * grayscalevalue etc. Is there same function here? TIA

**Comment by fmw42** [comment]
See http://www.imagemagick.org/Usage/color_mods/#tinting. Sorry, I do not know the C API equivalent.

**Comment by internalG** [comment]
Thank you. Maybe I can get something like f(x)=(1-(4.0*((x-0.5)*(x-0.5)))) directly? I must code it in C.

**Comment by internalG** [comment]
OK. I googled the formula.
