### ISSUE TITLE
Function ExtentImage behaves different in IMv6 and IMv7, is it normal?

### ISSUE THREAD

**Issue by shelvsky** [ImageMagick/ImageMagick#1218]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I want to apply a specific background color to the input image but it has no effect by code below with IMv7 but works well with IMv6:

```
int main(int argc,char **argv)
{
  ExceptionInfo
    *exception;

  Image
    *image,
    *images,
    *resize_image,
    *thumbnails;

  ImageInfo
    *image_info = NULL;

  if (argc != 4)
    {
      (void) fprintf(stdout,"Usage: %s image thumbnail\n",argv[0]);
      exit(0);
    }

  std::string color = argv[3];
  MagickCoreGenesis(*argv,MagickTrue);
  exception=AcquireExceptionInfo();
  image_info=CloneImageInfo((ImageInfo *) NULL);
  (void) strcpy(image_info->filename,argv[1]);
  images=ReadImage(image_info,exception);
  if (exception->severity != UndefinedException)
    CatchException(exception);
  if (images == (Image *) NULL)
    exit(1);

  MagickBooleanType ret;

  PixelInfo basecolor;
  ret = QueryColorCompliance(color.c_str(), AllCompliance, &basecolor, exception);


  RectangleInfo rect;
  rect.x = 0;
  rect.y = 0;
  rect.width = images->columns;
  rect.height = images->rows;

  images->background_color = basecolor;
  Image* extented = ExtentImage(images, &rect, exception);
  thumbnails = CloneImage(extented, 0, 0, (MagickBooleanType)0, exception);
  if( exception->severity != UndefinedException || thumbnails == NULL)
      exit(1);

  (void) strcpy(thumbnails->filename,argv[2]);
  WriteImage(image_info, thumbnails, exception);

  MagickCoreTerminus();
  return(0);
}

```
the original Image:
![trans](https://user-images.githubusercontent.com/3603525/42929456-b104daba-8b6c-11e8-863e-11e5736a4d21.png)
output Image:
![test](https://user-images.githubusercontent.com/3603525/42929536-e4017ffe-8b6c-11e8-8b1b-58f8e7993e86.jpg)

But after I changed the width and height values in struct RectangleInfo with 0, it works:
output Image:
![out](https://user-images.githubusercontent.com/3603525/42929724-7782da16-8b6d-11e8-9d16-c2a58caed24c.jpg)

So does it meet the expectation or is it a bug?

### Steps to Reproduce
1. install  ImageMagick-7.0.7-38
2. compile my program with command:
g++ -Wno-unused-variable -Wno-unused-but-set-variable -o transform transform.cpp -I/opt/ImageMagick7.0.7/include/ImageMagick-7 `Magick++-config --cppflags --cxxflags --ldflags --libs`
3. run the program like this:
./transform trans.png out.jpg "#FF0000"

### System Configuration

- ImageMagick version: ImageMagick-7.0.7-38
- Environment (Operating system, version and so on): centos 7.2
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
