### ISSUE TITLE
dadcode in ImageMagick/coders/cut.c

### ISSUE THREAD

**Issue by boo0m** [ImageMagick/ImageMagick#1220]
### Prerequisites

- [Y] I have written a descriptive issue title
- [Y] I have verified that I am using the latest version of ImageMagick
- [Y] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hi, there seems some badcode in ImageMagick/coders/cut.c

### Steps to Reproduce
The code is in ImageMagick/coders/cut.c:372
The program assigning palette = null, and in line 418.
`  palette=NULL;
  clone_info=NULL;
  Header.Width=ReadBlobLSBShort(image);
  Header.Height=ReadBlobLSBShort(image);
  Header.Reserved=ReadBlobLSBShort(image);`
 The value of "palette" must be "NULL" if the program wants to execute "Desclone_infotroyImage(palette); "
`  if (status == MagickFalse)
    {
      if (palette != NULL) 
        palette=Desclone_infotroyImage(palette); 
      if ( != NULL) 
        clone_info=DestroyImageInfo(clone_info); 
      return(DestroyImageList(image));
    }`

**Comment by urban-warrior** [comment]
The code appears for be correct.  There is a CUT_KO label where `palette` might be non-NULL and as such should be destroyed on exception.
