### ISSUE TITLE
UNINTENDED_INTEGER_DIVISION in ImageMagick/coders/rle.c

### ISSUE THREAD

**Issue by boo0m** [ImageMagick/ImageMagick#1222]
### Prerequisites

- [Y] I have written a descriptive issue title
- [Y] I have verified that I am using the latest version of ImageMagick
- [Y] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce
The code in ImageMagick/coders/rle.c:276 might use wrong  types in division operation.
In the code, the number_pixels, number_planes, bits_per_pixel and GetBlobSize(image) are not the type "double", but they are compared with a number which type is double.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
