### ISSUE TITLE
Version 6.9.7-4 creates gibberish of pdf text (no scan) when converting to jpg

### ISSUE THREAD

**Issue by MiroBabic** [ImageMagick/ImageMagick#1227]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have pdf document which contains pure text (no image of scan) which I want to convert to jpg for OCR process. When I do simple convert file.pdf out.jpg it creates gibberish output from the part which has pure text but actually it does correct conversion of scan.
Here is the output how does it look like
[https://stackoverflow.com/questions/51521016/imagemagick-convert-pdf-with-textno-scan-to-gibberish](url)

### Steps to Reproduce

[file.pdf](https://github.com/ImageMagick/ImageMagick/files/2229364/file.pdf)

`convert file.pdf out.jpg`

### System Configuration
Ubuntu 18.04.01
imagemagick 6.9.7-4
ghostscript 9.22

same file is converted fine on ubuntu 16.04.5
imagemagick 6.8.9-9
ghostscript 9.18

Update:
actually after several tests I found out that problem might be with ghostscript version
I tried Ubuntu 17.04 with imagemagick 6.9.7-4 but ghostscript 9.19 and output is fine
I tried Ubuntu 18.04 with imagemagick 6.9.7-4 but ghostscript 9.21 and output is broken

**Comment by dlemstra** [comment]
You should try to reproduce this with the tooling of Ghostscript yourself. And then check if you can still reproduce it with the latest version. Maybe 9.22 was bugged?

**Comment by MiroBabic** [comment]
Right, version 9.22 of GS is bugged. Manually installed 9.23 (ubuntu 18.04 doesnt provide 9.23 in repo) and all is working fine
