### ISSUE TITLE
"no images for write" error when constructing Info object

### ISSUE THREAD

**Issue by ethanhere** [ImageMagick/ImageMagick#1228]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
"no images for write" error when constructing Info object

### Steps to Reproduce
The test code:
final ClassLoader classLoader = this.getClass().getClassLoader();
InputStream is = classLoader.getResourceAsStream("Lumia-920-red.jpg");
Info info = new Info("-", is, true);
Error
Caused by: org.im4java.core.InfoException: org.im4java.core.CommandException: org.im4java.core.CommandException: magick: no images for write '-write' '-' at CLI arg 4 @ error/operation.c/CLINoImageOperator/4750.
at org.im4java.core.Info.getBaseInfo(Info.java:360)
at org.im4java.core.Info.<init>(Info.java:179)

### System Configuration
I am running this on MacOS. I installed imagemagick by command 'brew install imagemagick'

- ImageMagick version:
$ /usr/local/bin/magick -version
Version: ImageMagick 7.0.8-8 Q16 x86_64 2018-07-23 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib

- Environment (Operating system, version and so on):
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.6 (15G21013)
      Kernel Version: Darwin 15.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: 
      User Name: 
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 23 minutes

- Additional information:
The same test code works with imagemagick 6.7.2

**Comment by dlemstra** [comment]
We do not write or maintain the `im4java` library. You will need to report your issue somewhere else (no clue where).
