### ISSUE TITLE
Test is fail

### ISSUE THREAD

**Issue by boyfox** [ImageMagick/ImageMagick#1230]
------------ Server ----------------
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

Testsuite summary for ImageMagick 7.0.8
============================================================================
# TOTAL: 86
# PASS:  84
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/ImageMagick/ImageMagick/issues
============================================================================
Makefile:11044: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/opt/ImageMagick-7.0.8-8'
Makefile:11150: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/opt/ImageMagick-7.0.8-8'
Makefile:11362: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/opt/ImageMagick-7.0.8-8'
Makefile:11365: recipe for target 'check' failed
make: *** [check] Error 2

Look to attachment: 

[test-suite.log](https://github.com/ImageMagick/ImageMagick/files/2232909/test-suite.log)

**Comment by dlemstra** [comment]
Install the Freetype delegate library, rebuild ImageMagick and rerun the tests. Do the test still fail?

**Comment by boyfox** [comment]
@dlemstra thanks works well, but I have another problem, look why not exists delegates, all dependencies installed, I run this command:

`nice -n 19 convert -quiet -resize 169x169^ -gravity center -crop 169x169+0+0 /var/www/pollo/media/8/polloman/input.jpeg -quality 70 -unsharp 0x0.5 /var/www/pollo/media/8/polloman/polloman_169x169_1.jpeg`

and got this error:

`convert: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/512.
convert: no images defined `/var/www/pollo/media/8/polloman/polloman_169x169_1.jpeg' @ error/convert.c/ConvertImageCommand/3275.`

why?

identify -version:

Version: ImageMagick 7.0.8-8 Q16 x86_64 2018-07-26 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): 

Look delegates is empty

**Comment by boyfox** [comment]
Thank you all, you can close this issue, I fixed my problem with this answer: https://askubuntu.com/questions/1042436/how-to-install-delegate-libraries-for-image-magick-7-0-7
