### ISSUE TITLE
Orientation info from HEIC decoder does not match actual pixel orientation

### ISSUE THREAD

**Issue by rudchenkos** [ImageMagick/ImageMagick#1232]
### Description

It turns out that in HEIC the pixels are never rotated and the metadata only indicates the orientation of the sensor when the photo was taken. After [`ReadHEICImage` populates EXIF profile](https://github.com/ImageMagick/ImageMagick/blob/master/coders/heic.c#L212) and returns a decoded image, the `exif:Orientation` property is [interpreted by ReadImage](https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/constitute.c#L668) which sets `Image->orientation` accordingly.

Hence, there is a discrepancy between `Image->orientation` and actual pixel orientation in images loaded with the `heic` coder. Particularly, this leads to incorrect behavior of the `-auto-orient` which in this case tries to compensate non-existing pixel rotation.

### Steps to Reproduce

1. Take a HEIC image with `exif:Orientation` not equal to "1" (`TopLeftOrientation`). For instance, a portrait photo with one of the newer Apple iPhone devices. You can download an example photo here: https://www.dropbox.com/s/celi7ejhit9ybzb/test.heic?dl=0
1. Desktop image viewers like `Preview` on macOS normally display the photo as if camera was not rotated.
1. `convert test.heic -auto-orient test.jpg`

#### Expected result

`test.jpg` appears in viewers the same way as original.

#### Actual result

`test.jpg` appears sideways.

### System Configuration
- ImageMagick version: 7.0.8-9 Q16
- Environment: macOS 10.13.6, but the problem is cross-platform

**Comment by dlemstra** [comment]
I get the error below when I try to read your test image. What are the versions of your delegates?

```
I:\heic>identify test.heic
identify: Invalid input: No 'ftyp' box `test.heic' @ error/heic.c/IsHeifSuccess/121.
```
