### ISSUE TITLE
imagemagick creates some temporary files in curent directory

### ISSUE THREAD

**Issue by protegh** [ImageMagick/ImageMagick#1235]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I first noticed this with imagemagick-7.0.8.5 but then tried imagemagick-7.0.8.8 and could reproduce the behavior: Under some conditions imagemagick tools create short living temporary files in the current directory. The files all have random name with six characters (for example: KYDzDK wcdvza TRQiPT 5k1Or5).

### Steps to Reproduce
In first shell start:
```
$ inotifywait -m /some/path/for/testing -e create
Setting up watches.
Watches established.
```
In second shell do:
```
$ cd /some/path/for/testing
$ convert -delay 25 -loop 0 "https://www.niederschlagsradar.de/image.ashx?type=regioloop&regio=stg&j=-3&srt=loop1stunde" \( +clone -set delay 200 \) +swap +delete - | animate -title Stuttgart -
```
Then you'll see in first shell:
```
/some/path/for/testing CREATE 6uod3L
/some/path/for/testing CREATE etJpLz
/some/path/for/testing CREATE auxUYL
/some/path/for/testing CREATE G9aaHz
```
The files are just created and imediately removed.

Other temporary files (with the `magick-` prefix) are created in `/tmp/...` and if I run the commands inside a folder where I don't have write permissions there is no error message and the animation works.

Setting any of
```
$ export MAGICK_TMPDIR=/tmp
$ export MAGICK_TEMPORARY_PATH=/tmp
$ export TMPDIR=/tmp
```
changes nothing.

If I split the above convert-animate pipe into:
```
$convert -delay 25 -loop 0 "https://www.niederschlagsradar.de/image.ashx?type=regioloop&regio=stg&j=-3&srt=loop1stunde" \( +clone -set delay 200 \) +swap +delete img.gif
$ animate -title Stuttgart img.gif
```
there is no file created in `/some/path/for/testing` (except for `img.gif` certainly).

If I do:
```
$ convert -delay 25 -loop 0 img.gif \( +clone -set delay 200 \) +swap +delete - | animate -title Stuttgart -
```
there are two short living temporary files created.
### System Configuration
- ImageMagick version: 7.0.8.5 and 7.0.8.8
- Environment: Gentoo Linux, systemd-238, gcc 7.3.0, glibc-2.26, bash 4.4.12(1)-release

**Comment by urban-warrior** [comment]
Temporary files created by ImageMagick always start with the "magick-" prefix and respect the MAGICK_TMPDIR and TMPDIR environment variables.  Other temporary filenames are created by delegate programs or libraries ImageMagick leverages.  For example, ImageMagick calls the libXML delegate library to download any image file with the HTTPS prefix.
