### ISSUE TITLE
-region not working with -swirl on imagemagick 7

### ISSUE THREAD

**Issue by DuBistKomisch** [ImageMagick/ImageMagick#1236]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Ran into this while trying out [this script](https://github.com/LukeSmithxyz/voidrice/pull/60). Specifying a `-region` doesn't set where the `-swirl` takes place. This was the behaviour in imagemagick 6.

### Steps to Reproduce
Take an image like:

![lock](https://user-images.githubusercontent.com/703055/43672057-409f5ec4-97e9-11e8-8b04-d0d56ba5815e.png)

Run `convert lock.png -region 1920x1080+0+0 -swirl 360 +region screen.png`.

On 7 you get:

![screen](https://user-images.githubusercontent.com/703055/43672078-9bc0ca86-97e9-11e8-9f31-887080a806b4.png)

On 6 you get:

![screen](https://user-images.githubusercontent.com/703055/43672085-b0422702-97e9-11e8-8af7-20d86ecfa2ba.png)

### System Configuration
I'm on Arch Linux, using latest imagemagick and imagemagick6 packages, which are 7.0.8.8 and 6.9.10.8.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by DuBistKomisch** [comment]
Thanks, but I just tried out 7.0.8-10 and this is still not working.
