### ISSUE TITLE
Suggestion: Test crashing input files in make check

### ISSUE THREAD

**Issue by moshekaplan** [ImageMagick/ImageMagick#124]
To prevent fixed bugs from being reintroduced into the code, it might be worth adding the crashing input files to `make check`.

One thought on how to implement that: In the `tests` directory, create a new directory called 
`crash_tests` and use the makefile to run `convert infile /dev/null` on each file in `crash_tests`.

**Comment by mikayla-grace** [comment]
We run the tests against the images you provided before a release.  However, we have not exported these as part of the source or binary distribution.  The distribution is already fairly large.  If we export these image files, we may export them as a separate distributiion

**Comment by urban-warrior** [comment]
ImageMagick is using continuous OSS fuzzing to help prevent crashing.  This should resolve any existing problems as well any future bugs we might inadvertently introduce.
