### ISSUE TITLE
7.0.8-9 testsuite failure

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1241]
Hi, I get following results for `filter.t`:

```
ok 52
Solarize() ...
ok 53
Swirl(90) ...
  mean-error=0.00955737680124622, maximum-error=0.76078431372549
not ok 54
Threshold(90%) ...
ok 55
Trim() ...
ok 56
UnsharpMask('5x2+1') ...
ok 57
Wave('25x150') ...
  mean-error=0.352084396721652, maximum-error=0.913725490196078
not ok 58
```

**Comment by pgajdos** [comment]
6.9.10-9 does not expose this issue.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
Thanks, the issue fixed.
