### ISSUE TITLE
convert modifies exif field - Y-Resolution to 72 (from 300 in tested scenarios) in output JPG file

### ISSUE THREAD

**Issue by sudiptosarkar** [ImageMagick/ImageMagick#1242]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I discovered this bug while using im4j to remove the embedded colorspace I get on my images from darktable. I noticed there was one exif field that got changed when doing that. The `Y-Resolution` exif field (which in the original photo was 300), was changed to 72. I did this on multiple other photos to confirm the bug.

I then installed imagemagick 6 (also from Homebrew) and replicated the same issue there as well.

Every other exif info field was fine except for this one. The steps to reproduce the issue are listed below.

### Steps to Reproduce
1. Get an image with a 300x300 dpi resolution and ensure the exif info has X-Resolution and Y-Resolution at 300 (any normal camera should produce such a photo).
2. Check the dpi resolution with:
```
identify -format "%x x %y" <jpgFileName>
```
3. Check the exif information for `Y-Resolution` (I'm using `exif`, but any other exif tool can be used):
```
exif <jpgFileName>
```
4. Remove the colorspace (other conversions may also do this, although I've only done this one)
```
convert +profile "colorspace" <jpgFileName> mod_<jpgFileName>
```
5. Check the exif information for `Y-Resolution` on the output jpg file
```
exif mod_<jpgFileName>
```
6. Notice that the exif field value for `Y-Resolution` has changed to 72.

### System Configuration

- ImageMagick version: 7.0.8-8 Q16 x86_64 2018-07-23 and 6.9.10-8 Q16 x86_64 2018-07-23
- Environment (Operating system, version and so on): macOS High Sierra - 10.13.5
- Additional information: Binaries installed using homebrew (although, I don't see why it won't get replicated on non-homebrew installations).

**Comment by urban-warrior** [comment]
We cannot reproduce the problem as described.  Perhaps it is specific to certain images.  Post a link here so we can download and reproduce the problem.  Note, ImageMagick obtains the resolution from the EXIF profile.  If the EXIF profile is missing, it obtains it from the JPEG header.

```
-> exif before.jpg | grep -i resolution
X-Resolution        |300
Y-Resolution        |300
-> convert +profile "colorspace" before.jpg im.jpg
-> exif im.jpg | grep -i resolution
X-Resolution        |300
Y-Resolution        |300
```

**Comment by sudiptosarkar** [comment]
@urban-warrior Sorry about the late reply... Here are the files:
Original file - https://www.dropbox.com/s/fe77xqul716nh5c/DSC_5989.jpg?dl=1
Converted file - https://www.dropbox.com/s/mrf6g9xhfb7t99c/DSC_5989_srgb.jpg?dl=1

**Comment by sudiptosarkar** [comment]
Is there any more inputs I need to provide for this?

**Comment by dlemstra** [comment]
@sudiptosarkar Have you given it a try with the latest version?

**Comment by dlemstra** [comment]
We update the exif profile when the new image is written. It looks like we are parsing the profile incorrectly and only write part of the exif profile. The output of `identify -verbose output.jpg` shows only the `exif:XResolution`.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
