### ISSUE TITLE
ThumbnailImage function may reveal sensitive information

### ISSUE THREAD

**Issue by d0ge** [ImageMagick/ImageMagick#1243]
### Prerequisites

- [ Y ] I have written a descriptive issue title
- [ Y ] I have verified that I am using the latest version of ImageMagick
- [ Y ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Information Exposure at ThumbnailImage function. 
Vulnerable code
https://github.com/ImageMagick/ImageMagick/blob/92a873d0873534bc6ad50e5509709919dccfbdb4/MagickCore/resize.c#L3738
Image property Thumb::URI may contains information about path to the processing file. Image property software may contains information about executable file path

### Steps to Reproduce
Generate thumbnail for any file, at my example:
```convert /Users/user/Work/path/output.png -thumbnail 64x64 test.png ```
The test.png file will contains information:
```
EXtdate:create2018-08-08T22:00:15+03:00??
4%tEXtdate:modify2018-08-08T22:00:15+03:00????RtEXtsoftware/usr/local/Cellar/imagemagick/7.0.8-8/share/doc/ImageMagick-7//index.html?.tEXtThumb::Document::Pages1???/tEXtThumb::Image::Height128C|A?tEXtThumb::Image::Width128Ѝ?tEXtThumb::Mimetypeimage/png??VNtEXtThumb::MTime1533754815??1tEXtThumb::Size386B?x=?2tEXtThumb::URIfile:///Users/user/Work/path/output.png??CIEND?B
```
I think by default ImageMagick should not insert such information

### System Configuration

- ImageMagick version: ImageMagick 7.0.8-8 Q16 x86_64 2018-07-23
- Environment (Operating system, version and so on): MacOS
- Additional information: I've found such vulnerability in real systems

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
