### ISSUE TITLE
Error reading pcx image generated from another image

### ISSUE THREAD

**Issue by jamarsa** [ImageMagick/ImageMagick#1248]
When I generate, either using convert or writing from gimp, certain pcx files, after that I'm unable to read them with ImageMagick. An example png file that shows the problem is attached here.
It's a very simple image, a rounded box over a white background, for use with Allegro 4.2.
With ImageMagick 6.6.9-7 I had no issues.

Sequence of commands:
**smant@portatil:/caja/src/menu$ file btn_empty.png**
btn_empty.png: PNG image data, 300 x 300, 8-bit/color RGB, non-interlaced
**smant@portatil:/caja/src/menu$ convert btn_empty.png btn_empty.pcx
smant@portatil:/caja/src/menu$ file btn_empty.pcx**
btn_empty.pcx: PCX ver. 3.0 image data bounding box [0, 0] - [299, 299], 3 planes each of 8-bit colour, 72 x 72 dpi, RLE compressed
**smant@portatil:/caja/src/menu$ identify btn_empty.pcx**
identify: improper image header `btn_empty.pcx' @ error/pcx.c/ReadPCXImage/409.
**smant@portatil:/caja/src/menu$**

![btn_empty](https://user-images.githubusercontent.com/42421699/44174303-06636e00-a0e3-11e8-8830-3cdb26910ab4.png)

Operating System:

Archlinux 64-bit, up to date. Laptop with i7 intel processor

- ImageMagick version:
convert --version
Version: ImageMagick 7.0.8-8 Q16 x86_64 2018-08-01 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP 
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by jamarsa** [comment]
Oh, thanks! I didn't expect the solution so quickly! I was resorting to use the older version via a VM machine while I waited for the fix
