### ISSUE TITLE
setImageBias has no effect

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#125]
Hi, 
It looks like one issue that was raised before didn't get applied as with the fix:
http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=25732

i.e. all uses of MorphologyApply() still seem to be missing reading the bias value from the image, so something like the below is still needed.

cheers
Dan

+double 
+ bias;
+
+bias=image->bias;

Line 914-ish:

-convolve_image=MorphologyApply(image,channel,ConvolveMorphology,1,
- kernel_info,UndefinedCompositeOp,0,exception);
+convolve_image=MorphologyApply(image,channel,ConvolveMorphology,1,
+ kernel_info,UndefinedCompositeOp,bias,exception);

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
