### ISSUE TITLE
Tests fails with Q8 non-HDRI

### ISSUE THREAD

**Issue by dontub** [ImageMagick/ImageMagick#1260]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
tests.tap 2 fails with a Q8 non-HDRI build (`./configure --with-quantum-depth=8 --disable-hdri`). The test passes when only either of the option is used. The build machine has CentOS 7 installed. From test-suite.log:
> "lt-attributes: unable to open image 'foo': No such file or directory @ error/blob.c/OpenBlob/3489"
Line: 1277, signature (146366a0f4150adc7b28f4f5da750ec2ca2c50ff8b14f894ce1e4d7d4058f465) is incorrect
Caught exception: lt-attributes: unable to open X server `/home/[...]/ImageMagick-7.0.8-10/utilities/magick display' @ error/display.c/DisplayImages/1685
not ok
FAIL: Magick++/tests/tests.tap 2

### Steps to Reproduce
Make a Q8 non-HDRI build and run the tests.

### System Configuration
- ImageMagick version: 7.0.8-10
- Environment (Operating system, version and so on): CentOS 7.5.1804 x86_64

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
