### ISSUE TITLE
Windows build fails when MAGICKCORE_TIFF_DELEGATE is not defined

### ISSUE THREAD

**Issue by akbyrd** [ImageMagick/ImageMagick#1261]
`TIFFErrorHandler`, `TIFFErrors`, and `TIFFWarnings` are all defined inside `#if defined(MAGICKCORE_TIFF_DELEGATE)` preprocessor blocks, but code using these symbols is outside of the preprocessor blocks, leading to compiler errors on the undefined symbols. Namely, these two blocks

```
static TIFFErrorHandler
  error_handler,
  warning_handler;
```
```
      (void) TIFFSetWarningHandler(warning_handler);
      (void) TIFFSetErrorHandler(error_handler);
```

It doesn't appear to be possible to compile on Windows without having the tiff library available.

**Comment by dlemstra** [comment]
Thanks for reporting this issue. This will be resolved in the next release of ImageMagick.
