### ISSUE TITLE
Bug in writing EXIF metadata during HEIC to JPEG conversion

### ISSUE THREAD

**Issue by asuwend1** [ImageMagick/ImageMagick#1266]
### Description
When I convert HEIC with EXIF metadata to JPEG, I can't read the EXIF metadata properly from the resulting JPEG **with some commonly used Java packages** (exiftool can still read it with warning though). I believe this used to work properly approximately 1 month ago.

Metadata reader tried:
https://github.com/apache/commons-imaging
https://github.com/drewnoakes/metadata-extractor

### Steps to Reproduce
Input image: https://github.com/monostream/tifig/blob/master/fixtures/5_tree_path.heic
(this input image has EXIF Orientation tag)
asuwedi-mbp:tmp Ari$ exiftool 5_tree_path.heic | grep -i warn
asuwedi-mbp:tmp Ari$ convert 5_tree_path.heic 5_tree_path.jpg
asuwedi-mbp:tmp Ari$ exiftool 5_tree_path.jpg | grep -i warn
**Warning                         : [minor] Unknown garbage at start of EXIF segment**

I believe, this "minor" warning caused it to be unreadable to many EXIF metadata reader.

asuwedi-mbp:tmp Ari$ exiftool -v5 5_tree_path.jpg

...
    07f8: 00 00 00 06 00 00 00 01 00 00                   [..........]
  **Warning = [minor] Unknown garbage at start of EXIF segment**
  ExifByteOrder = MM
  + [IFD0 directory with 11 entries]
...

### System Configuration

- ImageMagick version:
Version: ImageMagick 7.0.7-39 Q16 x86_64 2018-08-25 https://www.imagemagick.org
- Environment (Operating system, version and so on):
MacOS High Sierra, 10.13.6
- Additional information:

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
