### ISSUE TITLE
[Text -> Image] Inconsistent width of a monospace font.

### ISSUE THREAD

**Issue by Yay295** [ImageMagick/ImageMagick#127]
For a program I'm working on, I need to have text stored as individual BMP images for each character in a font. This is easy enough to do with `convert -font <font> -pointsize <size> -background none -gravity center label:<glyph> <font>/<glyph filename>.bmp`. The problem I've come across is in trying to use Consolas - a monospace font. Despite being a monospace font, the BMP's generated by ImageMagick (for pointsize 18) range from 8 to 12 pixels wide, making correct spacing of the letters in my program somewhat more difficult than it should be. I know that this is happening because fonts are complex and ImageMagick is just trying to make sure the entire glyph lies within the image, but shouldn't there be some way to make sure a monospace font stays monospace?

**Comment by fmw42** [comment]
Can't you just specify -size 12x in your command to force the width to 12 pixels for each character?

**Comment by Yay295** [comment]
> Can't you just specify -size 12x in your command to force the width to 12 pixels for each character?

Yes, but they wouldn't be the same height then would they?

> I suspect that the font file you have may not have well defined glyph metrics. You can check that out with -debug annotate.

What am I looking for?

**Comment by mikayla-grace** [comment]
What version of ImageMagick are you using?  Try ImageMagick 6.9.3-3, the current release.  There was a recent patch against the complex text layout we recently introduced.

**Comment by fmw42** [comment]
> Yes, but they wouldn't be the same height then would they?
If you specify the -pointsize 18 and -size 12x, you should get results the same height. But see the previous comment about upgrading to IM 6.9.3..3

**Comment by Yay295** [comment]
> What version of ImageMagick are you using?

6.9.3-2

> Try ImageMagick 6.9.3-3, the current release.

Still the same size.

**Comment by Yay295** [comment]
> If you specify the -pointsize 18 and -size 12x, you should get results the same height.

No, you get results of the same width. If you specify `-size` and `-pointsize`, `-pointsize` is ignored. A somewhat acceptable solution I found is to use
`mogrify -extent <width>x -background none -gravity center <font>/<glyph filename>.bmp`
The problem being that if the image width goes from or to an odd numbered size, the text will be somewhat blurred as ImageMagick tries to place it in the middle of two pixels.

**Comment by dlemstra** [comment]
I just did a quick test with the latest (dev) version of IM and I keep getting images with the same size. Can you give it another try with the most recent version @Yay295 ? I am executing the following command:
```
convert -font consolas -pointsize 40 -background none label:i i.bmp
convert -font consolas -pointsize 40 -background none label:W W.bmp
```

Both images are 21x41

**Comment by Yay295** [comment]
Those two images are both 24x41 for me, but it does seem to be working better. However, at pointsize 19, 'A' is 13x20 while 'a' is 12x20. Testing all ASCII characters, 12/94 are 13x20, the rest are 12x20. I'm guessing this is caused by rounding somewhere?

(note for the future: the current release is 6.9.3-7)

**Comment by dlemstra** [comment]
I did some more testing and it turns out the rounding is done by FreeType. We call FT_Glyph_To_Bitmap and use the width of the bitmap. Not sure how we could change/fix this.

**Comment by spoutn1k** [comment]
Sorry but how is this completed ? I cannot generate a font file for my EFI program as magick will not output a consistently spaced font sample. Even if the fault technically lies with FreeType, magick is still unable to do this basic thing ?

**Comment by dlemstra** [comment]
We are using the freetype api and that is returning us the size so this is out of our control.

**Comment by spoutn1k** [comment]
Yes I understand this. However from a macro perspective magick does not behave as expected, and there is no fix yet. Even if it is not a priority, for tracking's sake this should not be closed, as it masks its visibility.

**Comment by dlemstra** [comment]
I added the `upstream` label to make it more clear that this is not a bug in our software. We don't need to keep this issue open and keep track of what is happening upstream. You are of course more than welcome to post a message here that tells other users in which version a fix was added for this in the future.

p.s. This might already be fixed in the most recent version of Freetype.

**Comment by spoutn1k** [comment]
Hey, your project, your rules. But if I get a laptop that will not boot I would be pretty surprised if the manufacturer said: "actually this is the CPU vendor that is responsible bye".

Exactly ! It might already be fixed. But because this is closed no one would think to look, until someone encounters the issue and they stumble onto an issue marked as completed. I hope you see my point.

**Comment by dlemstra** [comment]
Don't forget that we are a non commercial project and we are all doing this in our spare time so comparing us with a commercial manufacturer is a bit strange. If someone finds this issue they will see that this is something that we cannot fix and I will make sure to make this more clear in the comments next time.
