### ISSUE TITLE
Coders wmf.c and ttf.c cause compile errors when compiling MagickCore without MagickWand

### ISSUE THREAD

**Issue by akbyrd** [ImageMagick/ImageMagick#1273]
I'm compiling only MagickCore and the coders necessary to use it. When deploying it as a static lib and headers I noticed that the aforementioned coders are actually including and relying on MagickWand.h. Both `MAGICKCORE_SANS_DELEGATE` and `MAGICKCORE_FREETYPE_DELEGATE` are undefined, so nothing is actually _using_ MagickWand, but it still gets included.

The short of it is that MagickCore cannot actually be deployed as a standalone API. MagickWand *must* be deployed along with it. Especially when statically linking, since you have no control over which coders are included.

**Comment by urban-warrior** [comment]
TTF does not depend on MagickWand, WMF does.  ImageMagick depends on a number of delegate libraries for certain image formats.  JPEG, for example, requires libjpeg.  If you want to use the WMF coder, you need libMagickWand.  Disable WMF and MagickCore should work without the MagickWand library dependency.  To test, be sure to download the IMv7 trunk with our TTF patch.

**Comment by akbyrd** [comment]
Tested latest (08106772547f2016be3d927a5cf33e40b2bae33d). TTF is good, but WMF will still fail the build when it is disabled. The issue is that even when WMF is disabled (i.e. `MAGICKCORE_WMF_DELEGATE` is not defined) the `MagickWand.h` include is still active because it is outside of any preprocessor checks. This is in contrast to JPEG which puts the include directives inside a preprocessor check such that it doesn't try to pull in dependencies when JPEG is disabled.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by akbyrd** [comment]
Thanks!
