### ISSUE TITLE
[Feature Request] Ability to define which coders to register when building as a static library

### ISSUE THREAD

**Issue by akbyrd** [ImageMagick/ImageMagick#1274]
It looks like when building MagickCore as a dynamic library you are able to only load the coders you need at runtime. This makes it possible to avoid building coders you don't need. However, when building as a static library MagickCore that ability is not present. Since the register and unregister functions are explicitly called there's no way to avoid compiling coders without causing link issues, even if you don't need some of those coders.

I'm spending a lot of time compiling 131 coders when I need ~3 of them.

It would a massive help if I could disable the coders I don't wish to use as part of the build process. Something as simple as having macros for _every_ coder in magick-baseconfig.h the same way we have e.g. `MAGICKCORE_PNG_DELEGATE` for enabling and disabling use of libpng would be perfectly reasonable. Or perhaps moving MagickModules to the config header so we can poke it directly.

Any added control here would greatly appreciated. Thanks!

**Comment by urban-warrior** [comment]
You are welcome to submit a PR with a solution for selective compile / building of static coders.  We currently do not have a solution for your feature request.
