### ISSUE TITLE
[Feature Request] Ability to disable added `#pragma message(...)` output

### ISSUE THREAD

**Issue by akbyrd** [ImageMagick/ImageMagick#1275]
This is a small one, but I'd like to be able to disable the added build output generated from `#pragma message(...)` lines. In my particular build configuration I'm getting spammed with

> MagickCore lib static interface
> MagickCore module static interface

for each compiled coder.

**Comment by urban-warrior** [comment]
What is the code associated with the pragma messages.  We disable a number of pragmas already, we can likely disable these as well.

**Comment by dlemstra** [comment]
The messages have been removed.

**Comment by akbyrd** [comment]
Thanks!
