### ISSUE TITLE
Screenshot is distorted at 1366x768 resolution

### ISSUE THREAD

**Issue by khanhas** [ImageMagick/ImageMagick#1276]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Screenshot output is completely distorted when using `magick` CLI or from Magick++.  
But weird thing is that it only happens when my screen resolution is 1366x768. When I use other resolutions, it works normally again
.
### Steps to Reproduce
Change screen resolution to 1366x768.

Run this in terminal:
```
magick screenshot: D:\file.png
```

`D:\file.png`:
![image](https://user-images.githubusercontent.com/26436809/44748275-9076f200-ab39-11e8-9a94-d1ef80894167.png)

### System Configuration
- ImageMagick version: ImageMagick 7.0.8-10 Q16 x64 2018-08-14
- Environment: Windows 10 1803 (build 17134)

**Comment by dlemstra** [comment]
I can reproduce your issue on my laptop. I have no idea why this is happening but I will get back to you when I have more info.

**Comment by dlemstra** [comment]
I found and fixed the bug, this will be resolved in the next release.
