### ISSUE TITLE
StreamImage fails on single channel grayscale PNGs

### ISSUE THREAD

**Issue by akbyrd** [ImageMagick/ImageMagick#1279]
On PNG images that are single channel, grayscale StreamImage fails with `CorruptImageWarning "InvalidColormapIndex"`. This occurs for any value of map in SetStreamInfoMap.

I'm seeing this on ImageMagick 7.0.8-10. Repro code and image below ([image source](https://opengameart.org/content/pbr-fireaxe-model-icon))

```c++
#include "MagickCore/MagickCore.h"
#include <string.h>

#define CHECK() if (exInfo->severity) __debugbreak();
auto srcFilePath = "../test.bmp";
auto dstFilePath = "../test.raw";

int main()
{
	MagickCoreGenesis(nullptr, MagickTrue);
	ExceptionInfo* exInfo = AcquireExceptionInfo();

	ImageInfo* imInfo = AcquireImageInfo();
	strcpy(imInfo->filename, srcFilePath);

	StreamInfo* strInfo = AcquireStreamInfo(imInfo, exInfo); CHECK();
	SetStreamInfoMap(strInfo, "R");

	OpenStream(imInfo, strInfo, dstFilePath, exInfo);        CHECK();
	Image* imImage = StreamImage(imInfo, strInfo, exInfo);   CHECK();

	DestroyImage(imImage);
	DestroyStreamInfo(strInfo);
	DestroyImageInfo(imInfo);
	DestroyExceptionInfo(exInfo);
	MagickCoreTerminus();
	return 0;
}
```

https://user-images.githubusercontent.com/484784/44810271-246eab00-ab86-11e8-9fa5-58d52dbbc4de.png

P.S. It looks like this may apply to ReadStream as well.

**Comment by urban-warrior** [comment]
Unfortunately we cannot reproduce this problem.  We compiled your source against 7.0.8-10 and added debugging code to report any exceptions.  None were reported.

**Comment by akbyrd** [comment]
Here's a [full repro solution](https://drive.google.com/file/d/1UG5sFIyCLaPJ3x4OeWFzjJQFjx5MFJnA/view?usp=sharing) for Visual Studio compiling from source at 08106772547f2016be3d927a5cf33e40b2bae33d. It's a git clone of ImageMagick, VisualMagick, and ImageMagick-Windows (I know, not the way it was meant to be done, but I forgot and cloned the first two manually). It's janky, but it shows the issue. Solution was generated from ImageMagick/premake5.lua.

- Open ImageMagick/build/ImageMagick.sln.
- Compile.
- Set a breakpoint at ImageMagick/imt/main.cpp line 20.
- Step to line 21 and inspect exInfo (ExceptionInfo).

**Comment by urban-warrior** [comment]
We discovered an uninitialised pixel on the PNG reader.  We will have a patch sometime this week to fix the problem you reported.  Thanks.

**Comment by urban-warrior** [comment]
Try your program with the latest ImageMagick trunk.  Do you still get an invalid colormap index exception?
