### ISSUE TITLE
StreamImage from file to memory safely

### ISSUE THREAD

**Issue by akbyrd** [ImageMagick/ImageMagick#1280]
I'm streaming from a file into a memory buffer that I own and preallocate. I've stumbled my way into something that mostly works, but I can't actually check how much data was written to my buffer. In the debugger I can see that StreamInfo->blob->offset has the actual amount of data written, but that's not accessible since StreamInfo is opaque. Image->blob seems to reflect the input file, not the output blob so the size of the blob is the size of the file. I know I can PingStream beforehand, but I'd like to sanity check the output to ensure the amount written is what I expect.

I'm reasonably certain I'm not using this API ideally, but it's not clear to me what the 'right way' to do things is. What am I doing wrong and how can I check to see how much data was written to the output blob?

```c++
#include "MagickCore/MagickCore.h"
#include <string.h>

#define CHECK() if (exInfo->severity) __debugbreak();
auto srcFilePath = "../test.bmp";
auto dstFilePath = "../test.raw";

int main()
{
    size_t outputSize = 256 * 256 * 3;
    size_t bufferSize = outputSize * 2;
    void*  outputData = malloc(bufferSize);

    MagickCoreGenesis(nullptr, MagickTrue);
    ExceptionInfo* exInfo = AcquireExceptionInfo();

    ImageInfo* imReadInfo = AcquireImageInfo();
    strcpy(imReadInfo->filename, srcFilePath);

    ImageInfo* imWriteInfo = AcquireImageInfo();
    SetImageInfoBlob(imWriteInfo, outputData, bufferSize);
    StreamInfo* strInfo = AcquireStreamInfo(imWriteInfo, exInfo); CHECK();
    OpenStream(imWriteInfo, strInfo, ConstantString(""), exInfo); CHECK();

    Image* imImage = StreamImage(imReadInfo, strInfo, exInfo);    CHECK();

    DestroyImage(imImage);
    DestroyStreamInfo(strInfo);
    DestroyImageInfo(imWriteInfo);
    DestroyImageInfo(imReadInfo);
    DestroyExceptionInfo(exInfo);
    MagickCoreTerminus();
    free(outputData);
    return 0;
}
```

Here's what the various sizes are after StreamImage

![sizes](https://user-images.githubusercontent.com/484784/44822485-40874200-abb0-11e8-842a-d95d72975ff6.png)

On the same topic, it looks like ImageMagick does something bad if the buffer is too small. Rather than failing and filling out ExceptionInfo it appears to complete, but freeing my buffer later causes an exception. I suspect IM is trying to realloc the buffer because it thinks it owns it.

Also, I'm using the stream API for speed and efficiency. I'm trying to avoid any extraneous copies of the image data. However, in e.g. bmp.c it looks like an extra copy is being made in the following line:
```c++
pixel_info=AcquireVirtualMemory(image->rows, (bytes_per_line,image->columns+256UL)*sizeof(*pixels));
```
even though later in the ReadBMPImage function rows are written to the actual output buffer one row at a time. Does StreamImage not guarantee that allocations are limited to a single row for an image?

ImageMagick 7.0.8-10
Windows 10 Enterprise x64 (1709)

**Comment by akbyrd** [comment]
To directly address concrete issues:
1) Can I ask how much data was written by StreamImage or not?
2) What should happen if I pass a buffer that is too small to StreamImage?
3) Is the StreamImage usage code about correct?

**Comment by urban-warrior** [comment]
ImageMagick is written in C.  If we wrote it today, it likely would be written in C++ and StreamImage() would be a private method.  StreamImage() serves the stream command and pinging an image well but apparently is not robust enough for general usage.  Until we get a chance to make it more robust and improve the documentation, our current recommendation is not to use this interface and instead use ReadImage().  ReadImage() has proven itself robust but does lack the ability to read pixels directly into the user buffer.
