### ISSUE TITLE
identify -format "%[colors]" does not work

### ISSUE THREAD

**Issue by akunohomu** [ImageMagick/ImageMagick#1285]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
[ImageMagick docs](https://www.imagemagick.org/script/escape.php) say:

>%[colors] | Number of unique colors in the image (as of IM 7.0.3.8)

However, it is not actually recognized by ImageMagick. `%k`, which has the same effect, does work.

### Steps to Reproduce
```
>identify.exe -format "%k" image.png
86779

>identify.exe -format "%[colors]" image.png
identify.exe: UnknownImageProperty "%[colors]" @ warning/property.c/InterpretImageProperties/3994.

>identify.exe --version
Version: ImageMagick 7.0.8-11 Q16 x64 2018-08-29 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC HDRI
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib
```
### System Configuration
Windows 10 x64, ImageMagick  7.0.8-11 Q16 x64 portable

**Comment by fmw42** [comment]
I can verify that it works in IM 6.9.10.10 but not IM 7.0.8.10 Q16 Mac OSX Sierra

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
