### ISSUE TITLE
Magick hang on the input file

### ISSUE THREAD

**Issue by tianxiaogu** [ImageMagick/ImageMagick#1286]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I was running a fuzzing tool on ImageMagick and it detects a hang.
This issue may be a duplicate of <https://github.com/ImageMagick/ImageMagick/issues/1255>.
I reported it as well since ASAN does not work as expected in my case.

### Steps to Reproduce

1. Download and unzip [imagemagick-62.zip](https://github.com/ImageMagick/ImageMagick/files/2339333/imagemagick-62.zip)
2. Run `magick convert imagemagick-62 /dev/null`. Here, magick is built by clang without ASAN.
3. When I run the command with `-limit width 10MP -limit height 10MP`, the hang will be prohibited.

When I am trying to reproduce the issue with ASAN, the program hangs. If I press `ctrl+c`, the following message is displayed.
```
^C==2065==WARNING: ASan is ignoring requested __asan_handle_no_return: stack top: 0x7fff28299000; bottom 0x7f6b43fee000; size: 0x0093e42ab000 (635188195328)
False positive error reports may follow
For details see https://github.com/google/sanitizers/issues/189

```
### System Configuration

- ImageMagick version: HEAD (9df54d69589bf2730968d3bc7b4703311708c47d)
- Environment (Operating system, version and so on): Ubuntu 18.04 , Clang-8
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by tianxiaogu** [comment]
Thanks for your confirmation and reply.
