### ISSUE TITLE
-threshold: outdated example in doc

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1293]
https://www.imagemagick.org/script/command-line-options.php?#threshold
```
convert in.png -threshold 100% black.png
```
does not give all-black image, rather all-transparent one, as alpha channel is set to highest value, too, if I understand correctly. For example -alpha off could be used I think.

**Comment by dzedro** [comment]
Also `-threshold -1` behaves differently between version 6 and 7
```
[1] convert test.png -channel A -threshold -1 +channel trans_threshold.png
```
on version 6 according to [example](https://www.imagemagick.org/Usage/canvas/) image is transparent, but on version 7 does image look as when `-alpha off` is used
- version 6 [1]:
![trans_threshold_6](https://user-images.githubusercontent.com/9447312/45078577-afa0f100-b0f0-11e8-9325-7c8f3c16184a.png)
- version 6 [1] with `-alpha off`:
![trans_threshold_6_2](https://user-images.githubusercontent.com/9447312/45078597-b62f6880-b0f0-11e8-9493-3ff5a8faa799.png)
- version 7 [1]:
![trans_threshold_7](https://user-images.githubusercontent.com/9447312/45078606-baf41c80-b0f0-11e8-8a0e-a562b5768fe3.png)
-version 7 [1] with `-alpha off`:
![trans_threshold_7_2](https://user-images.githubusercontent.com/9447312/45078613-bd567680-b0f0-11e8-87b1-22c1c1db3874.png)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
Thanks for documentation change.
