### ISSUE TITLE
Missing checks in various coders.

### ISSUE THREAD

**Issue by tianxiaogu** [ImageMagick/ImageMagick#1295]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Based on the patch of <https://github.com/ImageMagick/ImageMagick6/commit/d5e7c2b5ba384e7d0d8ddac6c9ae2319cb74b9c5>, we found that many `ReadXXXImage` functions in `coders/XXX.c` miss the similar check against `GetBlobSize(image)`. Hope this issue is helpful.

Known examples:
* dib
* pcx
* sgi
* pnm

### Steps to Reproduce

A set of artifacts would be helpful. [HANGS.zip](https://github.com/ImageMagick/ImageMagick/files/2351324/HANGS.zip)

### System Configuration

- ImageMagick version: HEAD
- Environment (Operating system, version and so on): Ubuntu 18.04 x86-64, clang-8
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
