### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [ImageMagick/ImageMagick#1296]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the destructor for the class “Magick::Exception”](https://github.com/ImageMagick/ImageMagick/blob/306762972e7c7dd2158bf00d39ed2ebd87c49e65/Magick%2B%2B/lib/Exception.cpp#L43 "Update candidate: Destructor for Magick::Exception").

**Comment by dlemstra** [comment]
Feel free to send us a PR for this. We can also apply the patch if you prefer that 👍

**Comment by dlemstra** [comment]
Will do it myself then :) Just wanted to give you the option to send a PR

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/ImageMagick/ImageMagick/commit/81cf63587558159824424c7175aa93e704a24a49 "Deletion of an unnecessary check").
