### ISSUE TITLE
can't convert png file to dcm

### ISSUE THREAD

**Issue by cza2018** [ImageMagick/ImageMagick#1300]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I cannot convert png file to dcm using convert. I also tried using mogrify -format and got the same message (below).

### Steps to Reproduce

download png file from: https://en.wikipedia.org/wiki/Minions_(Despicable_Me)#/media/File:Minions_characters.png

$ convert Minions_characters.png Minions_characters.dcm
convert: no encode delegate for this image format `DCM' @ warning/constitute.c/WriteImage/1171.

### System Configuration

- ImageMagick version:
convert -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2018-07-10 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib

- Environment (Operating system, version and so on):
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

- Additional information:

**Comment by dlemstra** [comment]
ImageMagick only has support for reading DCM images. There is no support for writing them:
```
dirk@DIRK:~$ convert -list format | grep DCM
      DCM* DCM       r--   Digital Imaging and Communications in Medicine image
```
