### ISSUE TITLE
`convert: zTXt: chunk data is too large` for png files

### ISSUE THREAD

**Issue by Yoric** [ImageMagick/ImageMagick#1301]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

`convert` fails to open some PNG files, resulting in the following error messages:

```
convert: zTXt: chunk data is too large `Deck10.png' @ error/png.c/MagickPNGErrorHandler/1711.
convert: no images defined `top10.png' @ error/convert.c/ConvertImageCommand/3288.
```

I managed to reproduce the issue with a number of 80Mb files PNG, all of them produced by `convert` from a high resolution `pdf`.

### Steps to Reproduce

1. Download file [`bug.png`](https://drive.google.com/file/d/1o0cEVZ2bw8ol-tPD7mdLXewDeHucBYEq/view?usp=sharing) (might work with any large PNG).
2. `convert bug.png foobar.png` or anything more complicated.

The same operation works if, in the previous steps, I produce `bug.jpg` instead of `bug.png` and perform `convert bug.jpg foobar.png`.

### System Configuration

- ImageMagick version: 7.0.8-11_1 (HomeBrew package)
- Environment (Operating system, version and so on): macOS 10.13.6 (17G65)
- Additional information: libpng 1.6.35 (HomeBrew package)

**Comment by urban-warrior** [comment]
We're using libpng 1.6.34 and your image converts without complaint.  The exception you received is thrown by the PNG delegate library.  Post your issue to their development team, only they can help you.

**Comment by Yoric** [comment]
When you say "their development team", you're talking about libpng, right?

**Comment by dlemstra** [comment]
@Yoric  it appears the build in default value in the PNG library for a maximum chunk size is pretty low. I just pushed a change so it will use the limit we set inside ImageMagick. You should be able to read the image again when we publish the next release.

**Comment by Yoric** [comment]
Thanks!
