### ISSUE TITLE
Random GIF hangs with 100% CPU 95% mem

### ISSUE THREAD

**Issue by ThomasLabstep** [ImageMagick/ImageMagick#1306]
See also: https://github.com/ImageMagick/ImageMagick/issues/658

We are using LiipImagineBundle + Imagine PHP library.

The GIF binary is fully loaded in memory.

We only upscale and resize the first frame of the GIF.

We can reproduce this bug on our AWS EC2 t2.micro Load balanced cluster.

We are using AWS EC2 OS.

It's been bugging us a lot these past days.

Random GIF works, others don't.

Example working GIF: https://giphy.com/gifs/big-hero-6-UYgK6kSXD1WDu

We have no idea how to fix this... We cannot even extract the log files from our instance because it becomes unresponsive. We can only terminate it.

Some info:
```
Version: ImageMagick 6.7.8-9 2016-06-22 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP
```

```
Linux ip-xxx 4.14.62-65.117.amzn1.x86_64 #1 SMP Fri Aug 10 20:03:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dlemstra** [comment]
And we have no idea which version of ImageMagick you are using. Next time please use the issue template, it's there for a reason.

**Comment by ThomasLabstep** [comment]
Hello!

I did provide the version. Please check again.

I'm ready to give as much information as needed.

**Comment by dlemstra** [comment]
That version of ImageMagick is ancient. Can you reproduce your issue with the latest version of ImageMagick?

**Comment by ThomasLabstep** [comment]
It's a bit better, at least we got 504 gateway timeout as a response from the nginx server before dying.

But our instance is still completely dead and unresponsive.

I'm using this GIF: 
![1](https://user-images.githubusercontent.com/32262520/45490111-2b88e200-b75e-11e8-8824-792e0c7787cc.gif)

**Comment by dlemstra** [comment]
I am not an imagick expert but I wonder if this is compatible with IM7 and if you are not secretly still using IM6. You can check that with the following method: http://php.net/manual/en/imagick.getversion.php

**Comment by ThomasLabstep** [comment]
You're right!

```
Array ( [versionNumber] => 1656 [versionString] => ImageMagick 6.7.8-9 2016-06-22 Q16 http://www.imagemagick.org )
```

Now, how the hell do we update it??

**Comment by urban-warrior** [comment]
ImageMagick can be resource intensive.  You likely need to reduce the memory limits so that large image sequences are pushed to disk rather than memory.  Without limits, the process likely consumes all or most of the available memory starving system processes or exceeds the limits of the nginx configuration.  Try reducing the memory limits as we do @ https://imagemagick.org/script/security-policy.php.  We use a similar policy @ http://transloadit.imagemagick.org/MagickStudio/ and never have resource issues.

**Comment by ThomasLabstep** [comment]
Thank you very much !

That's an idea we can explore.

We will try limiting memory. I'll let you know how it goes.

**Comment by ThomasLabstep** [comment]
Interestingly, when I try to upload our GIF into your system, I get:

```
Exception 400: memory allocation failed `/var/www/html/ImageMagick/MagickStudio/workarea/0ab2fa619558365fa4145c57189f298a40008c6d16475d94d39fb0f3aba272860845b68658a09c1699783d92b804000c0a606ab3a2f89ce14cae632984c2d622/MagickStudio.dat' @ error/gif.c/ReadGIFImage/1274: 
```

**Comment by urban-warrior** [comment]
Try now, you'll get the expected exception: "list length exceeds limit..."  The ImageMagick online web presence only permits an image sequence of a maximum of 32 frames.

**Comment by mh47838704** [comment]
i have the same question，how can i avoid or fix it

size of test1.gif：2.23MB
execute the resize cmd：convert test1.gif -layers Coalesce -resize 600x400 -layers Optimize test1-resize-result.gif
resource usage：
mem：about 3GB
CPU：200%

**Comment by mh47838704** [comment]
> See also: #658
> 
> We are using LiipImagineBundle + Imagine PHP library.
> 
> The GIF binary is fully loaded in memory.
> 
> We only upscale and resize the first frame of the GIF.
> 
> We can reproduce this bug on our AWS EC2 t2.micro Load balanced cluster.
> 
> We are using AWS EC2 OS.
> 
> It's been bugging us a lot these past days.
> 
> Random GIF works, others don't.
> 
> Example working GIF: https://giphy.com/gifs/big-hero-6-UYgK6kSXD1WDu
> 
> We have no idea how to fix this... We cannot even extract the log files from our instance because it becomes unresponsive. We can only terminate it.
> 
> Some info:
> 
> ```
> Version: ImageMagick 6.7.8-9 2016-06-22 Q16 http://www.imagemagick.org
> Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
> Features: OpenMP
> ```
> 
> ```
> Linux ip-xxx 4.14.62-65.117.amzn1.x86_64 #1 SMP Fri Aug 10 20:03:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> ```

i met the same question, how did you fix it (ノ￣▽￣)

convert  resize gif(2.3MB) cosume about 3GB mem

**Comment by ThomasLabstep** [comment]
Here to help.

It will only crash EC2 randomly for some GIFs, other GIF will work just fine. There's no real pattern. The GIF can have tons of animations or only a few, can be super big or super small.
I could even crash the EC2 with a tiny 5kb GIF.

We decided to get rid entirely of image management on our end because it was obvious we would never be able to get rid of this bug.

We decided to switch to imgix as a third party system to handle all of our image resize. You just give access to them on your S3 bucket and they do the magic on the frontend with some query parameters.
It's been magic ever since.

Either you drop support of GIF for your service, or you pay for a third party that can handle GIF correctly.

Even if the solution for this GIF crashing EC2 was found, we would not switch back to using Imagine at this point.

**Comment by fmw42** [comment]
IM 6.7.8.9 is known to have bugs. However, I cannot say whether that is the cause of your issue. Is this an AWS issue or and ImageMagick issue?  Does it work on other platforms?

**Comment by ThomasLabstep** [comment]
> IM 6.7.8.9 is known to have bugs.

I just want to mention that downgrading IM did not solve this issue. I remember trying 5 lower versions and they all crashed the same.

EC2 is a bad platform for heavy processing because once your CPU reaches 100%, the instance becomes unresponsive and AWS will turn it into a zombie. You can only kill or reboot. You cannot ssh anymore or extract any log about what happened. That's why I recommend linode.

It did work fine on my macbook pro with i7 and 16 Gb RAM. It could be a EC2 specific bug. Which is why I recommend trying linode.
