### ISSUE TITLE
tiled image inside a primitive has shift layout in newer versions of imagemagick

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1309]
```
convert -size 128x128 canvas:khaki \
        -tile tree.gif  -draw 'circle 64,64 10,50'  tile_fill.gif
```
With 6.8.8-1 I get:
![tile_fill_old2](https://user-images.githubusercontent.com/4067843/45482045-51f25180-b74d-11e8-9486-a27961c30784.gif)
With 7.0.8-11 and 6.9.10-11 I get:
![tile_fill_new2](https://user-images.githubusercontent.com/4067843/45482069-5e76aa00-b74d-11e8-8433-24683c0d172a.gif)

The wallpaper is slightly shifted to right and to bottom. I do not see a big problem in it, I even am not sure how the filling a primitive with tiled image is defined. I want to just ensure you do not see a wider bug in it.

Interesingly, 
```
convert -size 128x128 canvas:khaki -tile tree.gif  -draw 'circle 54,54 0,54'  tile_fill.gif
```
gives the same results (on human eye sight) for all versions.

**Comment by pgajdos** [comment]
This is on linux, x86_64.

Originally, this was inspired by one of examples from 'Tiling with an Image already In Memory' section from Usage/canvas.

Just tell me if you consider exact layout of the tiled image in the primitive as insignificant. We will adjust or remove the test.

**Comment by fmw42** [comment]
I tested on ImageMagick 6.9.10.11 Q16 Mac OSX and get the following:

Input:
![tree](https://user-images.githubusercontent.com/13458218/45501796-164c8d00-b737-11e8-8a7c-ebc5162122a7.gif)

`convert -size 128x128 canvas:khaki -tile tree.gif  -draw 'circle 64,64 0,64'  tile_fill2.gif`

![tile_fill2](https://user-images.githubusercontent.com/13458218/45501832-311f0180-b737-11e8-870c-f80da0a90217.gif)


`convert -size 128x128 xc: -tile tree.gif -draw "color 0,0 reset" tile_fill3.gif`

![tile_fill3](https://user-images.githubusercontent.com/13458218/45501850-3e3bf080-b737-11e8-85e0-a7777bfea95b.gif)


The way to see that it is fine is to animate the two and see that they align properly. Also there is no offset of the tree in the simple tiling. 

![tile_animation](https://user-images.githubusercontent.com/13458218/45501905-6a577180-b737-11e8-8bb5-3308fcbf9b37.gif)

So I would say that the current versions are correct.

**Comment by pgajdos** [comment]
Thanks Fred for clarification.
