### ISSUE TITLE
Mogrify and Convert both throw "not authorized" error

### ISSUE THREAD

**Issue by Schneiderism** [ImageMagick/ImageMagick#1310]
### Description
Currently, attempting to use `mogrify -format pdf ~/Desktop/TIFFs/*.tif` results in the following error message:
> mogrify: not authorized \`PDF' @ error/constitute.c/IsCoderAuthorized/408.

### Steps to Reproduce
`brew install ImageMagick`
`mogrify -format pdf ~/Desktop/TIFFs/*.tif`
Error -> ```mogrify: not authorized `PDF' @ error/constitute.c/IsCoderAuthorized/408.```

### System Configuration
- ImageMagick version: ImageMagick 7.0.8-11_1 (Most recent for what Homebrew retrieves)
- Environment (Operating system, version and so on): MacOS X High Sierra, Version 10.13.6
- Additional information: MacBook Pro 13" laptop

**Comment by fmw42** [comment]
With ImageMagick 7, you need to put magick before mogrify. You also need Ghostscript and Tiff delegates. This works for me on IM 7.0.8.11 Q16 MacOSX with Ghostscript 9.24 and TIFF 4.0.9_0.

```
convert logo: logo.tiff
magick mogrify -format pdf logo.tiff
```

**Comment by Schneiderism** [comment]
`magick mogrify -format pdf ~/Desktop/TIFFs/testDoc.tif` returns the same message:
```mogrify: not authorized `PDF' @ error/constitute.c/IsCoderAuthorized/408```

Am I missing a prerequisite? I've removed `convert` from the script I'm using and now rely on `mogrify`, but still need to get it working. I currently have **libtiff 1.0.9** and **Ghostscript 9.25**

**Comment by dlemstra** [comment]
It looks like the Homebrew team disabled PDF by default:

- https://github.com/Homebrew/homebrew-core/commit/bc4a2b858b47a76ced48ddf2b89a7eefca5ad2a9#diff-b910f0001145806daa9ce950b1c51e69
- https://raw.githubusercontent.com/Homebrew/formula-patches/a95f9dd/imagemagick/imagemagick_safer_defaults.diff

You will need to patch your `policy.xml` file.

**Comment by Schneiderism** [comment]
Found the issue. Apparently as of ImageMagick 7, the `policy.xml` file negates all permissions of the program in order to protect security. Line 80 and line 87 of `/usr/local/etc/ImageMagick-7/policy.xml` must have `rights="none"` changed to `rights="all"` or a similar permission node.

**Comment by znmeb** [comment]
I ran into this on Arch Linux - their upgrades broke my code calling `image_write` from the R `magick` package. I'll go post a note on the Arch page.

**Comment by znmeb** [comment]
Arch bug opened: https://bugs.archlinux.org/task/60607

**Comment by jap1968** [comment]
In my case, the problem was solved following these indications:
https://nowardev.wordpress.com/2018/11/04/convert-im6-q16-not-authorized-kubuntu-pdf-imagemagick-convert-shit-error/

Edit the file `/etc/ImageMagick-6/policy.xml` to have that values:
`<policy domain="coder" rights="read|write" pattern="PDF" />`
