### ISSUE TITLE
Canvas bounds are not properly set when changed and saved in raw formats

### ISSUE THREAD

**Issue by dukesrg** [ImageMagick/ImageMagick#132]
Seems like since 6.9.3-? canvas size are not properly set by fact when rotating/transposing image and saving at least to GRAY, RGB, BGR.
ex. 320x240x24bpp PNG -rotate 90 or -transpose produces 240x320 PNG but 320x320 BGR output, but verbose still reports output is 240x320.

**Comment by mikayla-grace** [comment]
Raw image formats such as GRAY, RGB, etc.  do not include any metadata.  Instead they are simply pixel values.  Width and height and depth is defined on the command line:

    convert -size 320x240 -depth 8 image.gray -rotate 90 rotate.gray
    convert -size 240x320 -depth 8 rotate.gray rotate.png

**Comment by dukesrg** [comment]
@mikayla-grace
I suppose this should make clear:
```
C:\convert -verbose -size 320x240 -depth 8 **-rotate 90** base.png base.bgr
base.png PNG 320x240 320x240+0+0 8-bit sRGB 63.2KB 0.016u 0:00.003
base.png=>base.bgr PNG 320x240=>240x320 **240x320**+0+0 8-bit sRGB **307**KB 0.000u 0:00.006

C:\convert -verbose -size 320x240 -depth 8 **-flip** base.png base.bgr
base.png PNG 320x240 320x240+0+0 8-bit sRGB 63.2KB 0.000u 0:00.003
base.png=>base.bgr PNG 320x240 **320x240**+0+0 8-bit sRGB **230**KB 0.016u 0:00.005
```
Produced output is 320x320 with ablack stripe. crop, page, repage changes nothing. This does not affect BMP, MONO and even PNG (which actually support image offset) but at least BGR, RGB and GRAY are affected. 6.9.1--7 working fine, Actual bug appeared somewhere between  late 6.9.2 and 6.9.3

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
