### ISSUE TITLE
Error or Enhancement for Coalescing Layers of PSD Files

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#1320]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When I try to coalesce a layered PSD file, I would expect the results to be the size of the flattened layer. But this does not happen.

### Steps to Reproduce

This is what I tried:

`convert cellphone.psd cellphoneB_%d.png`

This command produces results the way I would expect or would like to see them.

```
for ((i=0; i<8; i++)); do
convert -quiet -size 1600x1600 xc:none cellphone.psd[$i] -background none -layers merge +repage cellphoneA_$i.png
done

```

If this is not a bug, then would it be possible to add a new -define so that a similar result could be produced in a single command line.

My test images are in a zip file that is attached. Note the data is proprietary to a client of mine.

### System Configuration

Testing was done in Imagemagick 6.9.10.11 Q16 Mac OSX Sierra.

[cellphone_PSD_coalesce_issue.zip](https://github.com/ImageMagick/ImageMagick/files/2389946/cellphone_PSD_coalesce_issue.zip)

**Comment by urban-warrior** [comment]
Try this command:

`convert cellphone.psd -background none -gravity center  -extent 1600x1600 +repage cellphoneB_%d.png`

**Comment by fmw42** [comment]
That would change the virtual canvas offset if the layers were not already centered

**Comment by fmw42** [comment]
This also does not work properly.

`convert -quiet cellphone.psd -coalesce cellphoneB_%d.png`

The layers get mixed together in some of the resulting png images.

**Comment by fmw42** [comment]
Working with Dirk, we found the proper method to do this using -dispose background.

`convert -quiet -dispose background cellphone.psd -coalesce cellphoneB_%d.png`
