### ISSUE TITLE
identify throws an error with DNG files

### ISSUE THREAD

**Issue by ItalyPaleAle** [ImageMagick/ImageMagick#1322]
### Description

When running `identify` on a DNG file, with the `.dng` extension, the command throws an error

### Steps to Reproduce

````
$ identify --version
Version: ImageMagick 7.0.8-11 Q16 x86_64 2018-09-17 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP
Delegates (built-in): bzlib cairo fftw fontconfig freetype heic jng jpeg lqr ltdl lzma png rsvg tiff webp xml zlib

$ identify IMG_0481.dng
identify: delegate failed `'ufraw-batch' --silent --create-id=also --out-type=png --out-depth=16 '--output=%u.png' '%i'' @ error/delegate.c/InvokeDelegate/1844.
identify: unable to open image '/var/folders/bg/n0d5fy3j4bqfzh3fndjftn6m0000gn/T/magick-31892YzvMwcnp8wZR.ppm': No such file or directory @ error/blob.c/OpenBlob/3489.
````

Test image is here: https://italypalealedev.blob.core.windows.net/public/IMG_0481.dng

### System Configuration

- ImageMagick version: 7.0.8-11
- Environment (Operating system, version and so on): Tested on macOS (installed via brew), Fedora, and Docker container based on Ubuntu

**Comment by fmw42** [comment]
Looks like you do not have ufraw installed as a delegate. I think if you did you would find "raw" in your list of delegates.

The following works fine for me on IM 7.0.8.11 Q16 Mac OSX Sierra

`magick identify -quiet IMG_0481.dng`
IMG_0481.dng TIFF 256x171 256x171+0+0 8-bit sRGB 24.9236MiB 0.000u 0:00.000

Note with IM 7, you should put magick before each command such as identify, mogrify, compare, etc. But use on magick in place of convert.

**Comment by ItalyPaleAle** [comment]
Thanks. I just realized that indeed on Linux I am getting the error you report above. I didn't pay attention to the errors when I opened this issue, and copied what I saw from my mac.

Also, for your point above

> However magick identify will read it as TIFF as above unless you use DNG: preface to your image. 

Indeed, that was the other issue I reported tonight: #1321 

_By the way, how do you install ufraw on Mac?_

**Comment by dlemstra** [comment]
The following works perfectly under Windows @fmw42:
```
I:\raw>magick identify -quiet DNG:IMG_0481.dng
DNG:IMG_0481.dng=>IMG_0481.dng DNG 6024x4022 6096x4056+72+34 16-bit sRGB 24.9236MiB 0.016u 0:00.006
```

Can we close this issue @ItalyPaleAle?

**Comment by ItalyPaleAle** [comment]
Sounds like this issue (aside from the missing dependency on my machine) is related to #1321 anyways, after @fmw42 's comment.

**Comment by fmw42** [comment]
It does not work under Mac OSX as I showed above for IM 7, but does work for IM 6.

**Comment by jhondge** [comment]
I'm working now with tiff(dng) format on [aws-lambda-image](https://github.com/jhondge/aws-lambda-image), as following steps:
* build [ufraw](http://ufraw.sourceforge.net/Install.html#Linux) on AMI
* copy the ufraw binary to my project path and set the path to environment variables
* change the `gm` src `-` to `DNG:-` (from buffer stream)

**Comment by Kingfisher1986** [comment]
I have solved it by compiling ImageMagick 7 with the `libraw-dev` library and then use it like: `identify dng:your-image-name`. Worked without problem.
