### ISSUE TITLE
Error reading pcx image

### ISSUE THREAD

**Issue by jbgeosoft** [ImageMagick/ImageMagick#1323]
Related to #1248, but  the attached PCX file fails at the same line even with the patch for that issue applied.

Commenting lines 408 and 409 (which was not there in 7.0.7) allows the coder to work. Since the new code introduced seems to improve security I am sure this is just a workaround. I am not familiar enough with the PCX format to contribute a proper patch at this time.

[120.zip](https://github.com/ImageMagick/ImageMagick/files/2394038/120.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
