### ISSUE TITLE
PSD layer export not working with PHP API

### ISSUE THREAD

**Issue by pedrofs** [ImageMagick/ImageMagick#133]
Hi guys, I'm almost sure this is not the best place for asking a question like that but I'll give a shoot anyway.

I'm exporting PSD layers to PNG using the PHP API and it is working just great for a several numbers of PSDs. The issue is that for some layers the result is not the expected one, the result layer image is broken, showing only pixel noise.

This is the code I'm using:

```php
for ($i = 1; $i < $image->getNumberImages(); $i++) {
	$image->setIteratorIndex($i);

	$path = $this->getDataSource()->getPath($filename);
	$layerPath = sprintf($path . DS . self::LAYER_NAME, $i);

	$this->parsedContent[$i] = $image->getImagePage();
	$this->parsedContent[$i]['path'] = basename(dirname($layerPath)) . DS . basename($layerPath);

	$image->writeImage($layerPath);
}
```

The original layer image (try to grab to see the content, it is a white text):

![test-13](https://cloud.githubusercontent.com/assets/56484/13110658/822a499e-d568-11e5-9231-3212ecaa858e.png)

The result image:

![layer_13](https://cloud.githubusercontent.com/assets/56484/13110668/8cec5048-d568-11e5-8390-eba4b1eaa3cc.png)

When I do command line `identify` the result is (the layer in question is the last one, 13):

```
weight loss.psd[0] PSD 851x315 851x315+0+0 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[1] PSD 851x315 851x315+0+0 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[2] PSD 455x325 455x325+436-6 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[3] PSD 394x501 394x501+194-130 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[4] PSD 399x480 399x480+195-125 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[5] PSD 603x462 603x462-3-119 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[6] PSD 217x226 217x226-33-95 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[7] PSD 302x309 302x309-20+128 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[8] PSD 224x228 224x228+222-115 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[9] PSD 341x67 341x67+51+34 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[10] PSD 180x4 180x4+136+121 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[11] PSD 32x6 32x6+210+120 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[12] PSD 241x65 241x65+104+137 8-bit sRGB 924KB 0.000u 0:00.000
weight loss.psd[13] PSD 216x44 216x44+118+149 8-bit sRGB 924KB 0.000u 0:00.000
```

The curious thing is that when I try a simple command line `convert weight loss.psd test.png` all layers are successfully exported.

Thanks and best,
Pedro.

**Comment by dlemstra** [comment]
Are you using the same version of ImageMagick through PHP and on the command line? This might be a bug that we fixed earlier.

**Comment by pedrofs** [comment]
Hey @dlemstra you are right. My system `convert` is using `ImageMagick 6.9.2-8` while PHP is using `ImageMagick 6.7.7-10`.

I will update the PHP one and see the result.

Thanks for your help!

**Comment by pedrofs** [comment]
It worked just great.

I've updated ImageMagick from source. I'll describe steps here for anyone that could need in future.

Download the lastest version here http://www.imagemagick.org/download/ and run:
```
./configure
make
make install
```

Download the lastest PHP module here https://pecl.php.net/package/imagick and run:
```
phpize
./configure
make
make install
```

All my exports worked fine after that.

Thanks again!
