### ISSUE TITLE
convert -list gravity exit code is not 0

### ISSUE THREAD

**Issue by cancerberoSgx** [ImageMagick/ImageMagick#1333]
It is expected that when an application exit without errors its exit code should be 0 but in this case is actually always 1 : 

```sh
$ convert -list gravity
None
Center
East
Forget
NorthEast
North
NorthWest
SouthEast
South
SouthWest
West
$ echo $?
1
$ convert -version
Version: ImageMagick 7.0.8-11 Q16 x86_64 2018-08-29 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP 
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib
```

Use case is, I'm writing integration tests or generation scripts that extract this meta information using the CLI and I check the command executed correctly expecting statusCode===0

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by cancerberoSgx** [comment]
Nice, thanks! 

BTW, I'm running ImageMagick 100% in the browser thanks to https://github.com/KnicKnic/WASM-ImageMagick that implements imagemagick (and some required libraries) emscripten output. Only basic features supported (no fonts, no fft, no webp, np pdf) but it's working nicely so far. I'm playing with it for if you want to test it online. I thought it's worthy to mention at least here. 

 * https://github.com/KnicKnic/WASM-ImageMagick
 * https://cancerberosgx.github.io/autumn-leaves/#/convertDemo

Would be great if a person with more experience with IM & libraries compilation could take a look - supporting fonts  would be great but it seems 'gs' program is a dependency... Do you think I should create an issue just to track this and put some comments in the readme or web page ? 

Thanks again
