### ISSUE TITLE
Facing issue with MiniMagick::Error convert convert: Unrecognized option (-layers)

### ISSUE THREAD

**Issue by nikhilthombare** [ImageMagick/ImageMagick#1334]
Here is my code and system information. The code is working on local environment but not on ubuntu server.

full error desc: convert uploads/tmp/1538654628-28339-2085/thumb_animated_clock.gif -coalesce -resize 100x100 -layers Optimize public/uploads/tmp/1538654628-28339-2085/thumb_animated_clock.gif

```
def gif_safe_transform!
  MiniMagick::Tool::Convert.new do |image| # Calls imagemagick's "convert" command
    image << @file.path
    image.coalesce # Remove optimizations so each layer shows the full image.

    yield image

    image.layers "Optimize" # Re-optimize the image.
    image << @file.path
  end
end

def my_resize(size)
  if @file.content_type == "image/gif"
    gif_safe_transform! do |image|
      image.resize "#{size}x#{size}" # Perform any transformations here.
    end
  else
    # Process other filetypes if necessary.
  end
end
```
~/repo/xyz# convert --version
Version: ImageMagick 6.7.7-10 2018-07-10 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP

**Comment by dlemstra** [comment]
ImageMagick 6.7.7-10 is ancient. You should upgrade your version of ImageMagick.

**Comment by nikhilthombare** [comment]
@dlemstra Facing same issue still after update version 
### new version:
```
Version: ImageMagick 6.9.10-12 Q16 x86_64 2018-10-05 https://imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC OpenMP
Delegates (built-in): bzlib djvu fftw fontconfig freetype gvc jbig jng jpeg lcms lqr lzma openexr pangocairo png tiff wmf x xml zlib

```
MiniMagick::Error (`convert /home/ubuntu/www/camp/releases/20181005100835/public/uploads/tmp/1538734461-19587-6099/thumb_output.gif -coalesce -scale 80x80 -layers Optimize /home/ubuntu/www/camp/releases/20181005100835/public/uploads/tmp/1538734461-19587-6099/thumb_output.gif` failed with error:
convert convert: Unrecognized option (-layers).
):


##### Can someone help me to solve this issue.

**Comment by dlemstra** [comment]
Are you sure that you are using the same version inside MiniMagick?

**Comment by nikhilthombare** [comment]
When I fire command inside rails application on server its show me

### puts system('identify -version')

```
GraphicsMagick 1.3.23 2015-11-07 Q16 http://www.GraphicsMagick.org/
Copyright (C) 2002-2015 GraphicsMagick Group.
Additional copyrights and licenses apply to this software.
See http://www.GraphicsMagick.org/www/Copyright.html for details.
```
But when same code run in local development o/p 

```
Version: ImageMagick 6.9.10-11 Q16 x86_64 2018-09-17 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff xml zlib

**Comment by dlemstra** [comment]
I suspect that MiniMagick is using GraphicsMagick instead of ImageMagick. I will close this issue now because this is now just an installation issue.
