### ISSUE TITLE
Cannot build with distort image functions

### ISSUE THREAD

**Issue by cujomalainey** [ImageMagick/ImageMagick#1341]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have downloaded the source to the latest build and I'm just trying to get a simple rotation animation with an image to work using SRT distortion. I am trying to use the distort method on the image class but for the life of me cannot get it to compile. I can use other methods such as zoom, rotate, scale, but not distort for some reason, the compiler complains that it doesn't exist even though I can see it in the C++ code and the header files. Any information to what silly thing I am missing would be great.

### Steps to Reproduce
Build this
```
#include <Magick++/Image.h>

using namespace Magick;

int main() {
        Image img;
        img.distort(1, NULL, NULL); // I know the arguments are wrong, ignoring that fact for now.
}
```
via this
`g++ $(GraphicsMagick-config --cppflags --ldflags --libs) -o out test.cpp`
and get this 
```
test.cpp: In function ‘int main()’:
test.cpp:5:6: error: ‘class Magick::Image’ has no member named ‘distort’; did you mean ‘directory’?
  img.distort();
      ^~~~~~~
```
### System Configuration

- ImageMagick version: 7.0.8-12
- Environment (Operating system, version and so on): raspbian stretch, pi 3 B
- Additional information: clean install

**Comment by emcconville** [comment]
I think your mixing GraphicsMagick and ImageMagick. Try the following..

    g++ $(Magick++-config --cppflags --ldflags) -o out test.cpp

**Comment by cujomalainey** [comment]
Yep that was it, thanks for catching that, I have been hunting this for hours
