### ISSUE TITLE
PNG grayscale bitdepth conversion are degraded at 7.0.8-12

### ISSUE THREAD

**Issue by yoya** [ImageMagick/ImageMagick#1343]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce

```
% convert rose: -type grayscale rose-gray.png
% convert rose: -type grayscale -depth 4 rose-gray-depth4.png
% convert rose: -type grayscale -depth 2 rose-gray-depth2.png
```

![rose-gray](https://user-images.githubusercontent.com/26040/46664221-52babe00-cbfb-11e8-9498-685ace5714ee.png)
![rose-gray-depth4](https://user-images.githubusercontent.com/26040/46664184-361e8600-cbfb-11e8-87f7-9a76c29d735e.png)
![rose-gray-depth2](https://user-images.githubusercontent.com/26040/46664168-28690080-cbfb-11e8-8756-c8b134208831.png)

### System Configuration

- ImageMagick version:

ImageMagick-7.0.8-12

```
% convert -version
Version: ImageMagick 7.0.8-12 Q16 x86_64 2018-10-05 https://imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP
Delegates (built-in): bzlib cairo fftw fontconfig freetype heic jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff webp wmf x xml zlib
```

- binary installation.

```
% brew install imagemagick
```

- Environment (Operating system, version and so on):

macOS High Sierra (10.13.6)

- Additional information:

Deletion of the following line will be OK(only this issue).
- https://github.com/ImageMagick/ImageMagick/commit/a315af3c73d107d73da90f54f41a0b88f27a3d80

I guess this is relevant.
- https://github.com/ImageMagick/ImageMagick/issues/1305

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
