### ISSUE TITLE
Memory leak in WritePDBImage

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1345]
Hey,

in issue #1050, there was a memory leak discussed and then fixed by 74f8b6c. However, I think `buffer` and `scanline` should be freed, too.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
Thanks!
