### ISSUE TITLE
Warning messages output from readImageBlob

### ISSUE THREAD

**Issue by adam1010** [ImageMagick/ImageMagick#1346]
I'm using up-to-date docker image: php:7.2-fpm
ghostscript: 9.20
php: 7.2
imagick: 7.0.7-35 Q16 (installed from 3.4.3 pecl)

When I use the Imagick library from within my PHP app I'm getting these warnings displayed:
```
**** Warning: considering '0000000000 XXXXX n' as a free entry.
**** Warning: considering '0000000000 XXXXX n' as a free entry.
**** Warning: considering '0000000000 XXXXX n' as a free entry.
```

The errors are triggered when `readImageBlob` is called:

```
    $im = new \Imagick();
    $im->readImageBlob(file_get_contents($pdf_file));
```

I noticed a similar (closed) issued here #341

**Comment by dlemstra** [comment]
What happens when you upgrade Ghostscript?

**Comment by adam1010** [comment]
GS 9.25 did appear to fix the issue, thanks!
