### ISSUE TITLE
Memory leak in WritePCXImage

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1347]
This is followup of #1049.

https://github.com/ImageMagick/ImageMagick/blob/5c4f2944c0c299832046ad308414daf8087f6f70/coders/pcx.c#L985

I think page_table should be freed here, too.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
Thanks!
