### ISSUE TITLE
"Error: X unsupported relocations" when resizing on radeon hardware

### ISSUE THREAD

**Issue by stuartpb** [ImageMagick/ImageMagick#1351]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

Previously mentioned at http://www.imagemagick.org/discourse-server/viewtopic.php?t=34758

### Description

Trying to `convert -resize` any image results in a failure like this:

```
Error: 8 unsupported relocations
Error: 8 unsupported relocations
Error: 8 unsupported relocations
Error: 8 unsupported relocations
Error: 8 unsupported relocations
Segmentation fault (core dumped)
```

The full gdb backtrace for one such failed invocation is up at https://gist.github.com/stuartpb/1f7885c33938551461085ff383410dd5.

Based on this, @loqs tracked this down [on the Arch Linux forums](https://bbs.archlinux.org/viewtopic.php?pid=1809711#p1809711) to an error coming out of Mesa (right around [here](https://github.com/mesa3d/mesa/blob/master/src/gallium/drivers/radeonsi/si_compute.c#L244-L249)) about the shader ImageMagick is handing it.

The number of unsupported relocations crashing the magick process appears to vary from machine to machine: it might be tied to the number of cores available (the gdb dump I'm linking here is from a system with an 8-core processor).

### Steps to Reproduce

From the looks of things, this happens any time you try to downscale an image on an up-to-date Arch Linux install with an AMD graphics card: for example, dylanaraps/pywal#299 points to one notable invocation that triggers it on the affected hardware.

### System Configuration

Present on ImageMagick 7.0.8-12 Q16 x86_64 2018-09-23 https://imagemagick.org

The current version of Mesa in Arch Linux (where this error started getting reported) is 18.2.2-1.

**Comment by dlemstra** [comment]
This looks like a bug inside the ImageMagick code. We recursively call `DestroyMagickCLCacheInfoAndPixels` when the status is not `CL_COMPLETE`:

```C
if ((status == CL_SUCCESS) && (event_status != CL_COMPLETE))
  {
    openCL_library->clSetEventCallback(info->events[i],CL_COMPLETE,
      &DestroyMagickCLCacheInfoAndPixels,info);
    return;
  }
```

But it turns out that we can also get a negative value (https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/clGetEventInfo.html) when an error occurred. We need to correct this check. 

But I don't understand why you get that error message or if we have caused that. And are you able to test a patch to check if we no longer get a segmentation fault after our patch has been applied to the master?

**Comment by stuartpb** [comment]
Sure, I can test a patch.

**Comment by stuartpb** [comment]
Shouldn't that be `(event_status < CL_COMPLETE && event_status > 0)`? And shouldn't there be a check for what the error return code (if any) is?

**Comment by dlemstra** [comment]
CL_COMPLETE is zero so that is the same check. We cannot really do anything with the error code so we don't need to check what it is. We are here only checking that all events have been completed.

**Comment by stuartpb** [comment]
Oh, I misread the documentation (I thought it said the states go from smallest to largest, not the other way around).

I'll give it a shot (I've never manually patched a compiled package before, so this might take a few hours). I take it the line to patch is [here](https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/opencl.c#L2901) (MagickCore/opencl.c line 2901)?

**Comment by dlemstra** [comment]
That is indeed the correct spot to patch. And thanks for helping me test this.

**Comment by stuartpb** [comment]
Looks like that patch fixes it: I just ran a build that includes a `convert` line to produce smaller icons that had the failure that originally prompted me to file this issue (and ImageMagick's in-tree `tests/validate-convert.tap` failed on the pre-patch code), and it's working now (as is validate-convert.tap).

**Comment by dlemstra** [comment]
Just pushed a patch to resolve this issue. And thanks again for helping me out!
