### ISSUE TITLE
Convert -trim option only works in the color red

### ISSUE THREAD

**Issue by LH24** [ImageMagick/ImageMagick#1352]
Hi, 

I am running into a very strange problem with the trim function of convert. 

Long story short I am trying to trim the black background from an image and replacing it with white.
It wont allow me to do this in one step, so here are the commands have to run. The only color that allows me to get a properly trimmed image is red, however, it removes the red color from my image which I need. Not sure what can be done about this. Any suggestions? 

convert *.gif -fill white -draw "color 1,1 replace" *_white.gif #replace background with white
convert *_white.gif -transparent white *_trans.gif #remove white background, replace with transparent 
convert *_trans.gif -bordercolor red -border 1x1 -trim +repage *_trim.gif #I have played with almost every color, if red is not used, it will only trim a small portion from the side of my image
convert *_trim.gif -fill white -draw "color 1,1 replace" *_fill.gif #replace red background for white
convert *_fill.gif -background white -gravity center -extent 300x350 *_resize.gif

At the end I get the image I want, however, all red in the image has been replaced with white. I have tried changing the red in my picture to a different color to begin with so I can preserve it, but then the trim function does not work properly.. 

My set up is ImageMagick 6.5.3-7 on Gnome 2.28.2

I am really hoping there's a solution. 
Thanks! 

Lindsay

**Comment by dlemstra** [comment]
First of all your version of ImageMagick is ancient so I would advise you to upgrade to the latest version. If it is still broken in the latest version then please attach some sample images so we can try to reproduce your issue.
