### ISSUE TITLE
convert: Maximum TIFF file size exceeded. `TIFFAppendToStrip' @ error/tiff.c/TIFFErrors/650.

### ISSUE THREAD

**Issue by ahmedtamseer** [ImageMagick/ImageMagick#1353]
Hi,

I am running a command (see below) to convert a jpeg image to tiff image by using -resize option. 

`convert -verbose -quality 100 -scale 54000 -units PixelsPerInch -density 300x300 -resample 300x300 input.jpeg -resize 54000 output.tif`

I ran into an error (see below) after some time. The command gave me 314bytes of an image as an output.

`convert: Maximum TIFF file size exceeded. `TIFFAppendToStrip' @ error/tiff.c/TIFFErrors/650.`

If I run same command (see below) by changing scale and resize value to 28800, gave me 1.2GB of file.

`convert -verbose -quality 100 -scale 28800 -units PixelsPerInch -density 300x300 -resample 300x300 input.jpeg -resize 28800 output.tif`

### System Configuration

- ImageMagick version: ImageMagick 7.0.8-12 Q16 x86_64 2018-10-05
- Environment (Operating system, version and so on): Ubuntu 16.04, 64-bit
- Additional Information: input.jpeg of size 15.9 MB

**Comment by dlemstra** [comment]
What is your question?

**Comment by ahmedtamseer** [comment]
Is there any size limit for output file? 
Why I am getting convert: Maximum TIFF file size exceeded.TIFFAppendToStrip' @ error/tiff.c/TIFFErrors/650.` error??

**Comment by dlemstra** [comment]
LMGTFY: https://www.awaresystems.be/imaging/tiff/faq.html#q8

**Comment by urban-warrior** [comment]
Use the TIFF64 format, for example,

`convert hugeimage.pam tiff64:hugeimage.tif`
