### ISSUE TITLE
master failing to build due to identical cases in switch

### ISSUE THREAD

**Issue by reaperhulk** [ImageMagick/ImageMagick#1354]
Looks like this is the culprit: https://github.com/ImageMagick/ImageMagick/blob/41a3cc9323255b321c9b5361a8f1aad8e68b6229/coders/tiff.c#L3596-L3602

conflicts with https://github.com/ImageMagick/ImageMagick/blob/41a3cc9323255b321c9b5361a8f1aad8e68b6229/coders/tiff.c#L3608-L3614

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
