### ISSUE TITLE
 image watermark opacity problem

### ISSUE THREAD

**Issue by tczf1128** [ImageMagick/ImageMagick#1356]
### Description
set opacity in watermark seems not work well.

### Steps to Reproduce
I use the golang binding of imagemagick, here is my golang code to set a watermark on a image.
```
watermark.SetImageAlpha(0.9) 
mw.CompositeImage(watermark, imagick.COMPOSITE_OP_OVER, false, x, y)

```

here is the implementation of golang bindings
```
func (mw *MagickWand) SetImageAlpha(alpha float64) error {
	ok := C.MagickSetImageAlpha(mw.mw, C.double(alpha))
	runtime.KeepAlive(mw)
	return mw.getLastErrorIfFailed(ok)
}

func (mw *MagickWand) CompositeImage(source *MagickWand,
	compose CompositeOperator, clipToSelf bool, x, y int) error {

	var clip C.MagickBooleanType = 0
	if clipToSelf {
		clip = 1
	}

	ok := C.MagickCompositeImage(mw.mw, source.mw,
		C.CompositeOperator(compose), clip,
		C.ssize_t(x), C.ssize_t(y))

	runtime.KeepAlive(source)
	return mw.getLastErrorIfFailed(ok)
}
```
when I set watermark alpha, I get the second error picture.
![ok](https://user-images.githubusercontent.com/4197519/47071395-063c3780-d226-11e8-9719-e56f821b4e35.jpg)
![error](https://user-images.githubusercontent.com/4197519/47071404-0c321880-d226-11e8-953b-c6f27f8989a7.jpg)

And I want this
![need](https://user-images.githubusercontent.com/4197519/47071729-d7729100-d226-11e8-9345-bec471f92451.jpg)

### System Configuration

- ImageMagick version: 7.0.8-12
- Environment (Operating system, version and so on): macos

**Comment by dlemstra** [comment]
You probably need to enable the alpha channel in your first image to make this work.

**Comment by tczf1128** [comment]
mw.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_ON) ?
seems still not work

**Comment by dlemstra** [comment]
@tczf1128 Did you manage to resolve your issue?

**Comment by dotSlashLu** [comment]
Try to remove the watermark's alpha channel:
```go
watermark.SetImageAlphaChannel(imagick.ALPHA_CHANNEL_REMOVE)
```

**Comment by hetianyi** [comment]
@tczf1128 How did you resolve this problem?
