### ISSUE TITLE
Convert: unknown field with tag 293 - Image is all Black

### ISSUE THREAD

**Issue by OutOfOptionz** [ImageMagick/ImageMagick#1358]
### Description

While attempting to convert TIFF documents to PDF, some documents convert fine while others have an all black background. In investigating, determined it was not the conversion, but the initial reading of the TIFF document: 

Using IMDisplay to open the TIFF, receive a warning "Unknown field with tag 293 (0x125)", then after accepting the warning ("OK"), the image is displayed as all black. Apparently the issue is not with the conversion, but the initial reading if the image.

1. Using -quiet does not change anything - the resulting image is the same (all black background).
2, Exiftool does not fix the file - Tag 293 (T6Options) is not rewritable, per exiftool

### System Configuration
Windows 10 and Windows Server 2012

- ImageMagick version: 7.0.8-12 Q16-HDRI (64-bit) (2018-09-23)

**Comment by urban-warrior** [comment]
Some TIFF images have proprietary fields that ImageMagick may not understand.  Or the values may need to be normalized to distinguish them visually.  You'll need to post one or two example TIFF images that fail for you before we can comment further.

**Comment by OutOfOptionz** [comment]
Not able to provide TIFFs – have personal information on them.
