### ISSUE TITLE
Test failures in 6.9.3-5

### ISSUE THREAD

**Issue by zarniwhoop73** [ImageMagick/ImageMagick#136]
I am seeing 2 failures, the first I do not understand, but the second is because Helvetica is apparently missing from my system: I installed ghostscript-fonts-std-8.11 to /usr/share/ghostscript/fonts in the belief that would provide Helvetica - is there a better source ?

first:
FAIL: Magick++/tests/tests
==========================

1..12
Line: 65  Vertical append failed, signature = 0909f7ffa7c6ea410fb2ebfdbcb19d61b19c4bd271851ce3bd51662519dc2b58
1 failures
not ok
FAIL: Magick++/tests/tests.tap 1

The second is:
Caught exception: lt-demo: unable to read font `Helvetica' @ warning/annotate.c/RenderType/917
not ok
FAIL: Magick++/demo/demos.tap 3

Google found a past report which said that n019003 is the Helvetica font - I have n019003l.{afm,pfb,pfm} - should I do something additional to make those usable ?

**Comment by kwm81** [comment]
I can only reproduced the first failure with 6.9.3-5 on FreeBSD.

FAIL: Magick++/tests/tests
==========================

1..12
Line: 65  Vertical append failed, signature = 0909f7ffa7c6ea410fb2ebfdbcb19d61b19c4bd271851ce3bd51662519dc2b58
1 failures
not ok
FAIL: Magick++/tests/tests.tap 1
Testing throwing and catching exceptions. A program crash or a message
that the exception was not caught indicates a test failure.  A properly
formatted exception message indicates success:
Caught exception, good!:
  "attributes: unable to open image `foo': No such file or directory @ error/blob.c/OpenBlob/2702"
ok
PASS: Magick++/tests/tests.tap 2

**Comment by kwm81** [comment]
The ImageMagick-6 branch checkout 01f4ac1 gives the following result:

PASS: Magick++/tests/tests.tap 1
