### ISSUE TITLE
Alpha support for writing heif images?

### ISSUE THREAD

**Issue by chregu** [ImageMagick/ImageMagick#1361]
### Description
With #1099 ImageMagick does "natively" support heic/heif images now, which is great and als works great. Unfortunately, alpha channels are not supported by ImageMagick yet for saving heif images. libheif and their example at do support it, 'though. 
https://github.com/strukturag/libheif/blob/master/examples/heif_enc.cc

Would be great, if this could be supported also by ImageMagick, maybe @farindk knows how to do this (may C is too rusty to actually give it a try currently)

### Steps to Reproduce
convert image-with-alpha.png image-with-alpha.heic

- ImageMagick version: 7.0.8-12
- Environment (Operating system, version and so on): Doesn't matter

**Comment by jreinertnash** [comment]
A common use case for this would be converting a PNG with alpha channel transparency to a HEIF file with an alpha channel.

**Comment by meyermarcel** [comment]
I would like to solve this issue but I have no or bad C experiences. Also I think it is important to adapt to the structures in this project of which I have no knowledge. So the chances are bad for a mergeable Pull Request from my side.

@dlemstra works on [heic.cc](https://github.com/ImageMagick/ImageMagick/blob/master/coders/heic.c) from time to time and enhances the heic coder step by step. Thanks a lot @dlemstra, I really appreciate your commitment!

**Comment by jeevi-cao** [comment]
> ### Description
> With #1099 ImageMagick does "natively" support heic/heif images now, which is great and als works great. Unfortunately, alpha channels are not supported by ImageMagick yet for saving heif images. libheif and their example at do support it, 'though.
> https://github.com/strukturag/libheif/blob/master/examples/heif_enc.cc
> 
> Would be great, if this could be supported also by ImageMagick, maybe @farindk knows how to do this (may C is too rusty to actually give it a try currently)
> 
> ### Steps to Reproduce
> convert image-with-alpha.png image-with-alpha.heic
> 
> * ImageMagick version: 7.0.8-12
> * Environment (Operating system, version and so on): Doesn't matter

i need this too

**Comment by dlemstra** [comment]
Support for this will become available in the next release.
