### ISSUE TITLE
[Magick++] Using ColorHSL makes object completely transparent

### ISSUE THREAD

**Issue by khanhas** [ImageMagick/ImageMagick#1368]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Using `Magick::ColorHSL` as `Magick::Image`'s background color or `Magick::DrawableFillColor` to draw shape causes them to lost their correct solid color and be transparent instead.
I believe this bug just appeared recently since it worked normally before.  

### Steps to Reproduce
```cpp
int main()
{
    Magick::InitializeMagick("\\");

    Magick::Image dest = Magick::Image(
        Magick::Geometry(600, 600),
        Magick::ColorHSL(0.5, 0.3, 0.3)
    );

    Magick::DrawableList toDraw = {
        Magick::DrawableFillColor(Magick::ColorHSL(0.27, 0.6, 0.6)),
        Magick::DrawableEllipse(300, 300, 150, 150, 0, 360)
    };

    dest.draw(toDraw);

    dest.write("D:\\hslTest.bmp");

    return 0;
}
```

`hslTest.bmp`
![image](https://user-images.githubusercontent.com/26436809/47477560-05bc2600-d850-11e8-8447-f0af21f354ac.png)

### System Configuration
- ImageMagick version: ImageMagick 7.0.8-14 Q16 x64 2018-10-24
- Environment: Windows 10 Version 1803 (Build 17134.345)

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
