### ISSUE TITLE
Error upon installation of ImageMagick 7

### ISSUE THREAD

**Issue by doctorate75** [ImageMagick/ImageMagick#1369]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Two error were detected upon checking the installation of ImageMagick

### Steps to Reproduce
I followed the steps mentioned in this link: https://linuxconfig.org/how-to-install-imagemagick-7-on-ubuntu-18-04-linux

### System Configuration
Ubuntu 18.04LTS
[test-suite.log](https://github.com/ImageMagick/ImageMagick/files/2518606/test-suite.log)

- ImageMagick version: 7.0.8
- Environment (Operating system, version and so on):Linux Ubuntu 18.04LTS
- Additional information: See the attached test-suite.log file

**Comment by urban-warrior** [comment]
This works for us:

```
sudo apt install libmagick-dev
sudo apt install libfreetype6-dev
cd ImageMagick-7.0.8-14
./configure
make
make check
```
