### ISSUE TITLE
compile ImageMagick-7.0.8-14.x86_64 by GCC met problems need help

### ISSUE THREAD

**Issue by xiaoleiren** [ImageMagick/ImageMagick#1372]
Hi,
I am a student and had like to compile the ImageMagick-7.0.8. by GCC on Ubuntu, but I met a difficult problem that I can not find out the correct sequence of compilers from the makefile or configure files  (I mean that a correct combination commands and it should be include paths of all the source code were I need). I wouldn't be able to compile the source code without them, you know that everybody uses the make/makefile directive to install it automatically in general, not manually by gcc. 
I just want to try to get different results through O2 O3 compilation and trying to analyze these .bin.

the Version is ImageMagick-7.0.8-14.x86_64.rpm

Could you please give me some help?  :)
Thank you so much.
I am looking forward to your reply.

**Comment by urban-warrior** [comment]
Try compiling directly from the source distribution.  See https://imagemagick.org/script/install-source.php#unix.  Can you compile now?

**Comment by dlemstra** [comment]
Any news @xiaoleiren ?
