### ISSUE TITLE
[CLI] Check if all input files exist before starting to process them

### ISSUE THREAD

**Issue by pzmarzly** [ImageMagick/ImageMagick#1373]
Recently, I was building large PDFs with ImageMagick 7.0.8-14 Q16 x86_64 2018-10-24, using e.g. `convert file1.png file2.png file3.png fil4.png output.pdf`. One filename had a typo, thus the file did not exist. Still, I received no error for few minutes, until Magick exited with `convert: unable to open image 'fil4.png': No such file or directory @ error/blob.c/OpenBlob/3490.`.

I suggest CLI programs should verify existence of files both on startup and on processing them, for convenience (user's time save).

**Comment by dlemstra** [comment]
We process your command step by step instead of parsing it first and then executing it. This means that we don't know if your file exists until we get to the argument where you give us a file name. Changing this might be possible but will be a lot of work.
