### ISSUE TITLE
why using -dct float as default value when decoding jpeg, it may give different results on different machines

### ISSUE THREAD

**Issue by yunzhehi** [ImageMagick/ImageMagick#1374]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

-dct float Use floating-point DCT method. 
  The float method is mainly a legacy feature. It does  not produce significantly more accurate results than the int method, and it is much slower. The float  method may also give different results on different  machines due to varying roundoff behavior, whereas the integer methods should give the same results on all machines. 
### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Extra info from the documentation:

```
Selects the algorithm used for the DCT step.  Choices are:
        JDCT_ISLOW: slow but accurate integer algorithm
        JDCT_IFAST: faster, less accurate integer method
        JDCT_FLOAT: floating-point method
        JDCT_DEFAULT: default method (normally JDCT_ISLOW)
        JDCT_FASTEST: fastest method (normally JDCT_IFAST)
In libjpeg-turbo, JDCT_IFAST is generally about 5-15% faster than
JDCT_ISLOW when using the x86/x86-64 SIMD extensions (results may vary
with other SIMD implementations, or when using libjpeg-turbo without
SIMD extensions.)  For quality levels of 90 and below, there should be
little or no perceptible difference between the two algorithms.  For
quality levels above 90, however, the difference between JDCT_IFAST and
JDCT_ISLOW becomes more pronounced.  With quality=97, for instance,
JDCT_IFAST incurs generally about a 1-3 dB loss (in PSNR) relative to
JDCT_ISLOW, but this can be larger for some images.  Do not use
JDCT_IFAST with quality levels above 97.  The algorithm often
degenerates at quality=98 and above and can actually produce a more
lossy image than if lower quality levels had been used.  Also, in
libjpeg-turbo, JDCT_IFAST is not fully accelerated for quality levels
above 97, so it will be slower than JDCT_ISLOW.  JDCT_FLOAT is mainly a
legacy feature.  It does not produce significantly more accurate
results than the ISLOW method, and it is much slower.  The FLOAT method
may also give different results on different machines due to varying
roundoff behavior, whereas the integer methods should give the same
results on all machines.
```

We also decided to add a patch where `JDCT_IFAST` will be used when the dct_method is not specified by the user and the quality is 90 or lower.

**Comment by beedell-roke** [comment]
> The float method may also give different results on different machines due to varying roundoff behavior, whereas the integer methods should give the same results on all machines.

Why is that a problem?
