### ISSUE TITLE
.tiff file got InsufficientImageDataInFile error

### ISSUE THREAD

**Issue by longcdf** [ImageMagick/ImageMagick#1375]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have a tiff file store at google drive: https://drive.google.com/file/d/1TOZu9lJFB9nynWnOjfzjYvJm3DBn5D-A/

I tried to convert this file from "tiff" to "tiff".
And I get the exception: InsufficientImageDataInFile

As I debug, TIFFScanlineSize(tiff) is 213 and GetBlobSize(image) is 186, so it throws the exception:
```
if(((MagickSizeType)TIFFScanlineSize(tiff)) > GetBlobSize(image))
    ThrowTIFFException(CorruptImageError, "InsufficientImageDataInFile");
```

> identify -verbose 199712.tiff
> identify: insufficient image data in file `199712.tiff' @ error/tiff.c/ReadTIFFImage/1651.

The file seems fine:

> tiffinfo.exe 199712.tiff
> TIFF Directory at offset 0x3c (60)
> Image Width: 1704 Image Length: 11
> Bits/Sample: 1
> Compression Scheme: CCITT Group 4
> Photometric Interpretation: min-is-black
> Orientation: row 0 top, col 0 lhs
> Rows/Strip: 11
> Planar Configuration: single image plane

- ImageMagick version: ImageMagick-7.0.8-14
- Environment: Windows 10

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
