### ISSUE TITLE
magick convert reported a sigbus error

### ISSUE THREAD

**Issue by Mtoxic** [ImageMagick/ImageMagick#1376]
### Prerequisites

- [ √ ] I have written a descriptive issue title
- [ √ ] I have verified that I am using the latest version of ImageMagick
- [ √ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I got a crash file by fuzzing, when I tested in my machine, the program aborted, and reported a SIGBUS error. The crash file is small, but the output seems large, every time I run it would take a little long and cause the left space little. 

[crash_file.zip](https://github.com/ImageMagick/ImageMagick/files/2553570/crash_file.zip)

### Steps to Reproduce
run `./magick convert ./crash_file /dev/null`
output:
```
$ ./magick convert ./crash_file /dev/null 
Aborted (core dumped)
```

output in gdb:
```
$ r convert ./crash_file /dev/null 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGBUS, Bus error.

__memset_avx2 () at ../sysdeps/x86_64/multiarch/memset-avx2.S:161
161	../sysdeps/x86_64/multiarch/memset-avx2.S: No such file or directory.
```

Output with ASan, but it's just a warning = =.
```
==24691==WARNING: AddressSanitizer failed to allocate 0x00f4b0b40000 bytes
==24691==AddressSanitizer's allocator is terminating the process instead of returning 0
==24691==If you don't like this behavior set allocator_may_return_null=1
==24691==AddressSanitizer CHECK failed: ../../../../src/libsanitizer/sanitizer_common/sanitizer_allocator.cc:147 "((0)) != (0)" (0x0, 0x0)
    #0 0x7f3256769631  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0xa0631)
    #1 0x7f325676e5e3 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0xa55e3)
    #2 0x7f32566e6425  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x1d425)
    #3 0x7f325676c865  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0xa3865)
    #4 0x7f32566ebb4d  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x22b4d)
    #5 0x7f32566ecb65  (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x23b65)
    #6 0x7f325676203f in __interceptor_posix_memalign (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9903f)
    #7 0x7f3255d9bec9 in AcquireAlignedMemory MagickCore/memory.c:266
    #8 0x7f3255d9c311 in AcquireVirtualMemory MagickCore/memory.c:611
    #9 0x7f3255fb9558 in ReadDIBImage coders/dib.c:668
    #10 0x7f3255c511b6 in ReadImage MagickCore/constitute.c:547
    #11 0x7f3255c51b59 in ReadImages MagickCore/constitute.c:922
    #12 0x7f32555b66ac in ConvertImageCommand MagickWand/convert.c:643
    #13 0x7f325568352a in MagickCommandGenesis MagickWand/mogrify.c:184
    #14 0x40172a in MagickMain utilities/magick.c:149
    #15 0x7f3254f1a82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #16 0x401308 in _start (/home/toxic/imagemagick/bin/magick+0x401308)
```

### System Configuration
ubuntu-16.04 64bit
 4.15.0-34-generic #37~16.04.1-Ubuntu

- ImageMagick version: ImageMagick 7.0.8-15 Q16 x86_64, latest commit 91dcab5
- Additional information:
I don't know if it's a bug, if not, you can close this issue, and sorry for that.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
