### ISSUE TITLE
improper image header reading some pcx files

### ISSUE THREAD

**Issue by pedro-w** [ImageMagick/ImageMagick#1377]
### Description
ImageMagick can't open some pcx files. This *seems* to apply to images with a small number of colors and more than 1024 pixels. Affected images can't be converted or even identified.
I am aware of #1323 but I think my version is from after the fix for that went in.

### Steps to Reproduce
In these steps I am using ImageMagick to create a pcx which it can't read itself but I found the problem whilst processing images from elsewhere. I think the images that IM creates are valid pcx files and it's the reader which is at fault.
```
$ magick xc:red -resize 48x22! t.pcx && magick identify t.pcx  
identify: improper image header `t.pcx' @ error/pcx.c/ReadPCXImage/412.
```
note that
```
$ magick xc:red -resize 48x21! t.pcx && magick identify t.pcx 
```
and
```
$ magick logo -resize 48x22! t.pcx && magick identify t.pcx 
```
are OK.

### System Configuration
Version: ImageMagick 7.0.8-14 Q16 x86_64 2018-10-25 https://imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib freetype jng jp2 jpeg lcms ltdl lzma png tiff webp xml zlib

on MacOS 10.14.1 (installed via homebrew, this is the latest version brew gives me)

**Comment by pedro-w** [comment]
Problem line is here:
https://github.com/ImageMagick/ImageMagick/blob/16c6b15da6ea2d02ae0076061fba4e242af01f3b/coders/pcx.c#L411-L412
The history of this was:
* extra check introduced from Chromium fuzz testing 7323203
* Divisor changed to 8 89f10ff
* Divisor changed to 10 5a21195 (#1248)
* Divisor changed to 12 fac6abc (#1323)

The choice of these numbers seem arbitrary to me.

If I understand it, the intention was to check "Does this data blob possibly contain enough bytes to produce the image size specified by the header?"

 If so, the 'worst' case is when the image is just one color, in which case the RLE compression would expand 2 bytes to 63, so the _minimum_ file size, including 128-byte header would be width * height * planes * 2 / 63 + 128. 

Does this make sense? Can you check the calculation?

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pedro-w** [comment]
Thanks for the response. Unfortunately I don't think this has fixed the general problem. I rebuilt IM from the current git master (with 54a848d applied) and though I don't see errors for the specific example I gave at the top, other sizes do give errors.

I tried
```
magick xc:red -resize ${N}x${N} test.pcx
```
for N=10,20,30... and any image of 40x40 or larger gives an 'ImproperImageHeader' error with `magick identify`
Please can you confirm (I may have made a mistake in compiling IM)

**Comment by pedro-w** [comment]
I think this is a more accurate size calculation whilst still being 'lightweight':
```
diff --git a/coders/pcx.c b/coders/pcx.c
index c6656515e..e921a4668 100644
--- a/coders/pcx.c
+++ b/coders/pcx.c
@@ -408,7 +408,7 @@ static Image *ReadPCXImage(const ImageInfo *image_info,ExceptionInfo *exception)
     pcx_packets=(size_t) pcx_packets*pcx_info.planes;
     if ((size_t) (pcx_info.bits_per_pixel*pcx_info.planes*image->columns) > (pcx_packets*8U))
       ThrowPCXException(CorruptImageError,"ImproperImageHeader");
-    if ((MagickSizeType) (pcx_packets/13) > GetBlobSize(image))
+    if ((MagickSizeType) (pcx_packets/32 + 128) > GetBlobSize(image))
       ThrowPCXException(CorruptImageError,"ImproperImageHeader");
     scanline=(unsigned char *) AcquireQuantumMemory(MagickMax(image->columns,
       pcx_info.bytes_per_line),MagickMax(pcx_info.planes,8)*sizeof(*scanline));
```
I wrote some code, using magick++, to create valid PCXs and invalid ones (by truncating files) and test them, let me know if it would be useful.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
