### ISSUE TITLE
[BUG] Convert BPG from PNG, not passing the -quality argument to libbpg

### ISSUE THREAD

**Issue by dem123456789** [ImageMagick/ImageMagick#1378]
### Description
I download and install the newest version ImageMagick-7.0.8-14-Q16-x64-dll on Windows. I try to convert a png file to bpg file.
The png file is 199KB but the converted bpg file is 255KB. No matter what quality I set, the size is huge and PSNR is Inf(seems lossless).
The command I use is 
convert mountain.png -quality 10 test.bpg
I do use imdisplay to show the test.bpg. It looks OK and I measure the PSNR which is Inf.

### Steps to Reproduce
Some effort to reproduce has been made on the forum [here](https://imagemagick.org/discourse-server/viewtopic.php?f=1&t=34999)

### System Configuration

- ImageMagick version: ImageMagick-7.0.8-14-Q16-x64-dll
- Environment (Operating system, version and so on): Windows 10

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
