### ISSUE TITLE
Cannot install ImageMagick with Ghostscript support

### ISSUE THREAD

**Issue by revolter** [ImageMagick/ImageMagick#1383]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce

```
brew install --with-ghostscript imagemagick
magick --version
```

prints:

```
Version: ImageMagick 7.0.8-14 Q16 x86_64 2018-11-11 https://imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jp2 jpeg lcms ltdl lzma png tiff webp xml zlib
```

and `convert test.ai test.png` throws this error:

```
convert: no images defined `test.png' @ error/convert.c/ConvertImageCommand/3288.
```

### System Configuration

- ImageMagick version: `7.0.8-14 Q16 x86_64 2018-11-11`
- Environment (Operating system, version and so on): `macOS 10.14 (18A391)`
- Additional information:

**Comment by fmw42** [comment]
IM 7 uses magick and not convert. So try

`magick test.ai test.png`

Be sure that you have a current version of GS and that it is properly installed. It should show up in 

`magick --version`

as gs or gslib.

In a terminal you should be able to get the version from

`gs --version`

**Comment by revolter** [comment]
Sorry, I forgot to mention that I did `brew install ghostscript`:

```bash
gs --version
```

then uninstalled imagemagick and installed it again by passing the `--with-ghostscript` argument.

**Comment by revolter** [comment]
I uninstalled imagemagick again and ran `brew install -v --with-ghostscript imagemagick`:

[imagemagick_install_output.txt](https://github.com/ImageMagick/ImageMagick/files/2569241/imagemagick_install_output.txt)

**Comment by urban-warrior** [comment]
Your log shows a configure script command line of:

`./configure --disable-osx-universal-binary --prefix=/usr/local/Cellar/imagemagick/7.0.8-14 --disable-dependency-tracking --disable-silent-rules --disable-opencl --disable-openmp --enable-shared --enable-static --with-freetype=yes --with-modules --with-openjp2 --with-webp=yes --without-fftw --without-pango --without-x --without-wmf`

You need to add '-with-gslib' to build ImageMagick with the Ghostscript API.  However, if the Ghostscript delegate library is not built, ImageMagick will revert to using the Ghostscript delegate library, 'gs.'

**Comment by engmg2011** [comment]
after installing ghostscript I ran `brew install imagemagick` and it worked with me
