### ISSUE TITLE
ImageMagick crashes on converting big JPG to WEBP

### ISSUE THREAD

**Issue by dooman87** [ImageMagick/ImageMagick#1384]
### Description
I'm trying to convert 3MB jpeg file to WEBP and getting error: `convert: width or height exceeds limit "/imgs/apple.webp' @ error/webp.c/WriteWEBPImage/623."`

### Steps to Reproduce

Please find a file to reproduce on at the bottom of this ticket.

`convert ./apple.jpg ./apple.webp`

### System Configuration

- ImageMagick version: 7.0.8-13
- In docker using this image: dpokidov/imagemagick
- I've also was able to replicate bug on older versions that coming with Alpine Linux

### File to reproduce:

![apple](https://user-images.githubusercontent.com/124110/48507042-f5bbc300-e89e-11e8-9c30-6106fea08bc0.jpg)

**Comment by dlemstra** [comment]
There is a limit on the size of a WebP image. The maximum width and height are 16838: https://developers.google.com/speed/webp/faq#what_is_the_maximum_size_a_webp_image_can_be.

And your file is 750x27221:
```
I:\jpg>identify apple.jpg
apple.jpg JPEG 750x27221 750x27221+0+0 8-bit sRGB 3.41868MiB 0.000u 0:00.003
```
