### ISSUE TITLE
Error converting ico to png: "insufficient image data in file"

### ISSUE THREAD

**Issue by shmerl** [ImageMagick/ImageMagick#1386]
I'm trying to convert an icon for a GOG game from ico to png and it fails as follows:

```convert goggame-1885888793.ico icon.png
convert-im6.q16: insufficient image data in file `goggame-1885888793.ico' @ error/icon.c/ReadICONImage/380.
convert-im6.q16: no images defined `icon.png' @ error/convert.c/ConvertImageCommand/3258.
```

Version:
```
convert --version
Version: ImageMagick 6.9.10-14 Q16 x86_64 20181023 https://imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
```

OS: Debian testing Linux, x86_64.

For instance Gimp opens this file and can convert it.

**Comment by shmerl** [comment]
See attached icon on which you can test it:

[example.ico.zip](https://github.com/ImageMagick/ImageMagick/files/2587161/example.ico.zip)

**Comment by kwm81** [comment]
Got the same issue.

OS: FreeBSD 12.0-BETA4  amd64

% identify --version
Version: ImageMagick 6.9.10-14 Q16 amd64 2018-11-13 https://imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules 
Delegates (built-in): bzlib cairo fftw fontconfig freetype jbig jng jp2 jpeg lcms lqr ltdl lzma png raw rsvg tiff webp wmf x xml zlib

[launcher_icon.ico.gz](https://github.com/ImageMagick/ImageMagick/files/2593258/launcher_icon.ico.gz)
