### ISSUE TITLE
Apparently should be 1,1.. `JPEGPreDecode' @ error/tiff.c/TIFFErrors/654.

### ISSUE THREAD

**Issue by Juanfree** [ImageMagick/ImageMagick#1389]
### Prerequisites

I installed imageMagick 7 in a ubuntu 18 docker container, I am running the convert script but sometimes I am receiving this error:

Apparently should be 1,1.. `JPEGPreDecode' @ error/tiff.c/TIFFErrors/654.

And the TIFF generated appears black.

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
Sounds like an incorrect TIFF image but without an example on how we can reproduce this I cannot be sure if that is the case.

**Comment by Juanfree** [comment]
I cannot share the example because has personal information, but does not exist some way to fix the TIFF with imageMagick?

**Comment by dlemstra** [comment]
Your file is corrupt so ImageMagick cannot read it and that means you can also not use it to "fix" the file. It also looks like you are missing part of the error message. It should start with "Improper JPEG sampling factors".

**Comment by Juanfree** [comment]
convert: Unknown field with tag 512 (0x200) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/999.
convert: Unknown field with tag 513 (0x201) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/999.
convert: Unknown field with tag 514 (0x202) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/999.
convert: Improper JPEG sampling factors 2,1
Apparently should be 1,1.. `JPEGPreDecode' @ error/tiff.c/TIFFErrors/654.

That's are some errors. And then the document generated appears with all pages black.

**Comment by Juanfree** [comment]
ok, thanks!
