### ISSUE TITLE
-format "%@" reports a 20 digit long trim width or height with some images on Windows

### ISSUE THREAD

**Issue by pr3sidentspence** [ImageMagick/ImageMagick#1392]
### Prerequisites

- [x ] I have written a descriptive issue title
- [x ] I have verified that I am using the latest version of ImageMagick
- [x ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Some jpeg images cause Magick to report a 20 digit width using %@ when some fuzz values are specified.
EDIT Nov 19 2018 13:44 CDT: I have now seen this happen with the reported trimmed height as well.

### Steps to Reproduce

Images causing this problem at: [https://1drv.ms/f/s!As3ZytCDCPbLj5Vvc7xxM4wXHBrVZA](https://1drv.ms/f/s!As3ZytCDCPbLj5Vvc7xxM4wXHBrVZA) 

Fuzzes between 57% and 63% on this [image](https://1drv.ms/u/s!As3ZytCDCPbLj5VwLMo2hEtGgyYFzA), e.g....

`C:\path>MAGICK TccL95U.jpg -fuzz 57% -format "%@" info:`

...cause the output to be like:

`18446744073709552000x1895+389+432`

### System Configuration

- ImageMagick version:
6.9.10-11 Q16 x64 HDRI
7.0.4-8 Q16 x64
7.0.4-8-14 Q16 x64
7.0.8-14 Q16 x64 HDRI

 on Windows 10
- Environment (Operating system, version and so on): Windows 10 (multiple builds)
- Additional information: ImageMagick 6.8.9-9 Q16 x86_64 running in Windows Subsystem for Linux (ubuntu) does not exhibit this problem.

**Comment by pr3sidentspence** [comment]
This probably isn't news to the developers, but apparently, this is really close to 2^64, and the trailing zeros may have to do with trying to do calculations with more precision than the language can handle. (I'm inferring from some StackOverflow questions with the 20 digit number in them about JavaScript)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick

**Comment by pr3sidentspence** [comment]
Wow. Fast. Thanks.
