### ISSUE TITLE
Native CLAHE support

### ISSUE THREAD

**Issue by whugemann** [ImageMagick/ImageMagick#1393]
### Description

I would like ImageMagick to have native support for CLAHE, as discussed in https://imagemagick.org/discourse-server/viewtopic.php?f=22&t=35058. As is said there, the C code is readily available and its author Karel Zuiderfeld confirmed just there that his code may be freely implemented into ImageMagick.

**Comment by urban-warrior** [comment]
Started working on implementing CLAHE a few days ago.  Give us a few weeks and we'll add a patch.

**Comment by whugemann** [comment]
Besides Karel Zuiderveld's original C code, you might find the Java code of Stephan Saalfeld's Plugin for Fiji/ImageJ useful, which you can find at GitHub under https://github.com/axtimwalde/mpicbg/tree/master/mpicbg/src/main/java/mpicbg/ij/clahe

**Comment by urban-warrior** [comment]
Try the -clache option in the lastest ImageMagick Beta release.
