### ISSUE TITLE
ImageMagick can’t open a specific WebP image

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [ImageMagick/ImageMagick#1398]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When I get a WebP image from GIMP website, open with ImageMagick, I get an error:<br>
![tempsnip](https://user-images.githubusercontent.com/10364351/49130160-6fee3d80-f2ca-11e8-9a88-92e7d6ca527e.png)

### Steps to Reproduce

1. Get this image from https://www.gimp.org/news/2018/11/08/gimp-2-10-8-released/
2. Open IMDisplay
3. Press Ctrl+O to open the image

### System Configuration

None

- ImageMagick version: 7.0.8-14 Q16 x64
- Environment (Operating system, version and so on): Windows 10
- Additional information: -

**Comment by urban-warrior** [comment]
ImageMagick utilizes the libwebp delegate library to read images in the WEBP format.  Post this issue to their developers.  The libwebp tools choke on this image:

```
-> dwebp gimp-2-10-8-ZeMarmot-frama.webp 
Error! Decoding of an animated WebP file is not supported.
       Use webpmux to extract the individual frames or
       vwebp to view this image.
Decoding of gimp-2-10-8-ZeMarmot-frama.webp failed.
Status: 4(UNSUPPORTED_FEATURE)
```
