### ISSUE TITLE
Weird stripe effect with CLAHE

### ISSUE THREAD

**Issue by whugemann** [ImageMagick/ImageMagick#1399]
### Description

Weird stripe effect with CLAHE

### Steps to Reproduce

Occurs if the tile are not square, say 6x4 for an image with 4:3 aspect ratio. There are diagonal stripes in the output image

### System Configuration

- ImageMagick version:  7.0.8-14 Q16 x86 2018-11-27
- Environment (Operating system, version and so on): Windows 7, 32 bit
- Additional information:

**Comment by whugemann** [comment]
Sorry, I didn't notice that I could upload files over here. 
The above input image is 640x480, i.e. 4:3.
The output at the bottom was produced by
magick test.jpg -clahe 6x4+127+3 -quality 80% 6x4.jpg

![test](https://user-images.githubusercontent.com/45207380/49228938-c2277f80-f3ec-11e8-8476-2c352741e49f.jpg)
![6x4](https://user-images.githubusercontent.com/45207380/49229328-9062e880-f3ed-11e8-823d-e5e3ae1b21f5.jpg)

**Comment by fmw42** [comment]
I was under the impression that this is still under development and was at this time only doing a global -equalize. At least that was the situation last weekend. The IM developer has just built the framework and not put in the actual tiling equalize. He said he would not get back to it until this next weekend. As far as I know this is only in the beta and not released yet.

**Comment by urban-warrior** [comment]
The -clahe option is still under development-- it is not released yet.  However, we are interested in feedback during the development-- so thanks for your post and sample image.  We will investigate and report back when we have a patch.
