### ISSUE TITLE
Cannot reconstruct gif after removing first frame

### ISSUE THREAD

**Issue by dopey** [ImageMagick/ImageMagick#1401]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Trying and failing to remove the first N frames from a gif. If I remove the first frame the resulting,
reconstructed gif, appears corrupted on my filesystem. By corrupted I mean that I can't open it with Preview, b/c Preview says it's corrupted. Note: I can remove any other frames from the gif, just not the first. I assume I'm doing something wrong, so this is probably less of an issue than a question.

### Steps to Reproduce
1) convert gif into frames using `convert +adjoin`
2) remove first frame of gif
3) reconstruct the gif from remaining frames
4) End up with corrupted gif

```
#!/bin/bash
animtoconvert=$1

# Split in frames
convert $animtoconvert +adjoin temp_%04d.gif

# remove first frame
rm temp_0000.gif

# Create the new animation & clean up everything
convert $( ls temp_*) new_animation.gif
rm temp_*
```

### System Configuration

- ImageMagick version: 7.0.8-14
- Environment (Operating system, version and so on): Mac OS Mojave
- Additional information:

**Comment by fmw42** [comment]
Try

```
convert $animtoconvert -coalesce +adjoin temp_%04d.gif
rm temp_0000.gif
convert $( ls temp_*) -layers optimize new_animation.gif

```
If that does not work, then add -dispose xxx before $( ls temp_*) and try the various dispose arguments listed at https://imagemagick.org/Usage/anim_basics/#dispose

**Comment by dopey** [comment]
Your snippet worked (didn't have to use `-dispose`)! Thanks a ton for the suggestion.
