### ISSUE TITLE
CLAHE seems to be just AHE

### ISSUE THREAD

**Issue by whugemann** [ImageMagick/ImageMagick#1404]
### Description

CLAHE seems to be just AHE with no control over the contrast limit

### Steps to Reproduce

I still cannot see any inluence of the clip-limit parameter. In _Fiji/ImageJ_ its influence is quite drastic, the default value beeing 3.0. In ImageMagick, I cannot see any difference, regardless what value I supply for it. And https://www.imagemagick.org/script/command-line-options.php gives no hint on what values IM expects for this parameter. Questions:
- Is it a real or an integer value?
- What is the range?
- I am confused by the {+-} in front of the last two parameters. To my knowledge, most commands expect a plus a the default, as with lat, and a negative parameter tells the command something different. But how can you possibly have a negative count of histogram bins? Or what would a negative contrast threshold possibly mean?

### System Configuration

Windows 10, 64 bit, IM 7.0.8-15

**Comment by urban-warrior** [comment]
Use percent, e.g. -clahe 2x2+128+3%.  For correct percent scaling, you'll need the Beta release of IM.

**Comment by whugemann** [comment]
There is still something wrong, as the effect of the clip parameter is nonlinear. Usually, the higher the threshold, the stronger the equalisation effect should be, but this is not the case.

I took a look at your code and can only make a rough guess, what's wrong. I think it's the passage where you calculate the excess and directly refer to clip_climit, whereas the original code (https://github.com/erich666/GraphicsGems/blob/master/gemsiv/clahe.c) scales it to unsigned long first

`ulClipLimit = (unsigned long) (fCliplimit * (uiXSize * uiYSize) / uiNrBins);`

and the uses this value for clipping.

**Comment by whugemann** [comment]
Sorry, I did not mean to close the issue. I clicked "close and comment" by hazard.

**Comment by urban-warrior** [comment]
Can you provide a reference image and command line that illustrates the "non-linear" effect you are seeing?

**Comment by whugemann** [comment]
I have just taken my test image from https://github.com/ImageMagick/ImageMagick/issues/1399 and applied the command line
`magick test.jpg -clahe 8x8+127+3% clahe_8x8_127_03.jpg`
which gave this result:
![clahe_8x8_127_03](https://user-images.githubusercontent.com/45207380/49686616-41a50500-faf7-11e8-8f4e-c0b1e5056e9d.jpg)
The result is the same, regardless what percentage I provide for the contrast limit. This is literally so, as a binary comparation of the files yields no difference whatsoever.

I couldn't reproduce my original effect (I should have noted the parameters I used). But there, the effect somehow weakend for percentages over 30%.
`magick -version`
yields:
Version: ImageMagick 7.0.8-16 Q16 x64 2018-12-06 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC HDRI Modules OpenMP 
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib

**Comment by urban-warrior** [comment]
Don't use percent.  Instead use a clip limit of 2 or 3 as a good starting point.  Its a float so you can use fractional such as -clahe 2x2+128+2.7.

**Comment by fmw42** [comment]
` ... whereas the original code (https://github.com/erich666/GraphicsGems/blob/master/gemsiv/clahe.c)  ...
`

Can you provide the output from your input image processed with the above code from GitHub?

**Comment by urban-warrior** [comment]
Already checked.  The clahe.c module is returning the same exact results as IM.

**Comment by fmw42** [comment]
FYI: Here are the results from my two adaptivegamma scripts:

Input:
http://www.fmwconcepts.com/misc_tests/adaptivegamma/49228938-c2277f80-f3ec-11e8-8476-2c352741e49f.jpg

Adaptivegamma1:
http://www.fmwconcepts.com/misc_tests/adaptivegamma/49228938-c2277f80-f3ec-11e8-8476-2c352741e49f_adaptivegamma.jpg

Adaptivegamma2:
http://www.fmwconcepts.com/misc_tests/adaptivegamma/49228938-c2277f80-f3ec-11e8-8476-2c352741e49f_adaptivegamma2.jpg

**Comment by whugemann** [comment]
> Don't use percent.

Well, it was you who told me:

> Use percent, e.g. -clahe 2x2+128+3%. For correct percent scaling, you'll need the Beta release of IM.

and I am pretty shure that the documentation at https://imagemagick.org/script/command-line-options.php#clahe said so until yesterday ...

Well, anyway, it functions as expected now; thank you for implementing this feature!

This is IM's result of -clahe 16x16+128+3
![tire_16x16_128_03](https://user-images.githubusercontent.com/45207380/49699010-f7da1e80-fbcb-11e8-8f9e-7a8a36a4fcb0.jpg)
and this is Fiji's result using tiles of 40x40, 128 histogramm bins and a contrast threshold of 3:
![tire_fiji_40x40px_128_3 0](https://user-images.githubusercontent.com/45207380/49699038-3a9bf680-fbcc-11e8-8821-3eaf0e6ba544.jpg)
That's pretty much the same.
Remark: The approach of the Fiji filter is somewhat different, as it asks for the absolute dimensions of the tiles. Here 16x40=640.
There still is however a little glitch at the lower right corner of the upper image, where IM's CLAHE produces a triangular artefact. You can especially see that if you choose higher values for the contrast limit.

**Comment by urban-warrior** [comment]
The issue is resolved.  The limit of tiles is 256x256, not 16x16.

**Comment by urban-warrior** [comment]
The triangle problem is fixed.  Virtual pixels are only required when there is a partial tile.  That's not the case, for example, if the image is 640x480 and the tiles is 16x16 or 2x2.  If its 3x3, a partial tile is required and virtual pixels are utilized.

**Comment by fmw42** [comment]
Great thanks. Is there a new beta available for me to test the fix?

**Comment by whugemann** [comment]
I am also glad that you raised the number of tiles, as 16x16 would have been too little: If you test the tire example with 4x3 tiles (corresponding to 16x12 for an image of 2,560x1,920 pixel), you get a very different result with less detail, especially on the rim.

I am not so sure about  the partial tile explanation of the effect, as I used 16x16 tiles in the above example.

Your aproach by defining tiles rather than a neighborhood of the pixel in question is probably the best approach to the problem from a photographer's point of view, but a scientist would rather ask: What extension has the smallest detail which I want to preserve by the filter?, see: https://imagej.net/Enhance_Local_Contrast_(CLAHE)

Do you see a possibility to reflect both philosophies in the command's options? For example, a negative histogram bins count could suggest that x times y is the size of the tile rather than their count. I admit that could be confusing to a novice ...

**Comment by fmw42** [comment]
One possible way to achieve this might be to use a -define to set the width and height and then from that convert internally to the closest number of cells in x and y.

**Comment by urban-warrior** [comment]
Design principles of processes requires us, as best we can, to have only one way to do one thing-- otherwise it can get confusing for the user.  Defines are fine to modify slightly the flow of an algorithm.  For your suggestion we would need to replace the `#tiles-x X #tiles-y` with `width x height` rather than support both methods.  We could support the later since the option is brand new and likely not embedded in any scripts but we are reluctant to support both ways of using the -clahe option.  What's your preference?

**Comment by fmw42** [comment]
For me, width and height of a cell is preferred. but I will defer to Wolfgang's preference.

**Comment by urban-warrior** [comment]
Wolfgang, what is your preference?  We don't have much time to lock this option down.  If we do use width / height, we can use percentages.

**Comment by urban-warrior** [comment]
Correct.

**Comment by fmw42** [comment]
OK Thanks. We will see what Wolfgang prefers as to number of cells or cell dimensions

**Comment by whugemann** [comment]
Sorry for my late reply, but the e-mail notifications about your discussion dropped in overnight.

I have just had a look at Karel Zuiderveld's original code and saw that it works with the tile philosophy. So far, I was only used to Stephan Saalfeld's implementation in ImageJ/Fiji, which works with the neighborhood philosophy. 

I would opt for the neigborhood philosophy for the following reasons:

- It's nowadays probably the most common, due to its implementation in ImageJ / Fiji
- It's closer to the philosophy of related filters, such as Photoshop's Shadow / Highlights and Gimp's Light and shadow filter.
- It would allow Saalfeld's "slow" approach, i.e. a non-interpolating, strict neighborhood impementation, sometime in the future.
- Given the possibility to define the tiles as a percentage of the image dimension, it more or less allows the tiles philosophy as an alternative.

**Comment by urban-warrior** [comment]
We have a patch to support tile width / height in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow. 

As a starting point, try -clahe 50x50%+128+3.

**Comment by fmw42** [comment]
Yes, it seems to work fine for me using tile size in width and height with and without the %. The triangular artifact is also gone.

**Comment by whugemann** [comment]
Sorry that I have to spill the wine: Under Windows, I could not make any sense of magick's behaviour. The command sometimes worked and sometimes just did nothing, without throwing an error. This affected both versions of clahe, with or without the percent sign. For the test, I used the tire example once again, trying things like:

`magick tire.jpg -clahe 320x240+128+3 tire-320x240-128-3.jpg`
`magick tire.jpg -clahe 50%x50%+128+3 tire-50x50pc-128-3.jpg`

As said above, I sometimes succeded, even with other values for the neighborhood, e.g. 160x120 or 25%x25%, giving (as expected) a result differing from the 2x2 tiles.

Version: ImageMagick 7.0.8-17 Q16 x64 2018-12-11 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC HDRI Modules OpenMP 
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib

**Comment by fmw42** [comment]
For me using IM 7.0.8.17 beta with HDRI on Mac OSX, those two commands produce very similar result apart from some tiny spots in the center of the rims. I have not tried without HDRI

**Comment by whugemann** [comment]
I have just installed IM beta without HDMI support on my Windows 10, 64 bit computer:
```
Version: ImageMagick 7.0.8-17 Q16 x64 2018-12-16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib
```
and found CLAHE principially functioning. (Just before, I once again verified that IM with HDMI support behaves as described, i.e. is not functioning.)

In order to illustrate the difference between 2x2 and 50%x50%, I produced this test image:
![tn2](https://user-images.githubusercontent.com/45207380/50083466-2e2f2380-01f4-11e9-8198-8783afae06ba.png)
This is the result of -clahe 2x2+128+3:
![tn_2x2 128 3](https://user-images.githubusercontent.com/45207380/50083470-325b4100-01f4-11e9-85e8-5e29ea317d4b.png)
And this is the result of -clahe 50%x50%+128+3:
![tn_50pcx50pc 128 3](https://user-images.githubusercontent.com/45207380/50083473-35eec800-01f4-11e9-8b7b-8033a525a87b.png)
IMHO, both results should be identical, unless I miss a decisive point (?).

**Comment by fmw42** [comment]
I can reproduce this issue on IM 7.0.8.17beta as of today (Dec. 17 2018) at 4PM from the latest beta download on my Mac OSX Sierra.

**Comment by fmw42** [comment]
Sorry, dumb mistake on my part. The algorithm uses either a tile width and height in pixels or as a percent of the image width and height. So 2x2 no longer corresponds to 50x50%. The correct correspondence would be in this case 160x120 or 50x50%

**Comment by fmw42** [comment]
Wolfgang -- The algorithm still internally works by number of tiles. The tile width and height are used to determine how may tiles are needed. There is a limit of 256x256 tiles currently. So for example if one had a 10,000 width and height image and used a tile of 100x100, that would mean 100x100 tiles or 10,000 tiles, which is less than 65535 tiles max. This is more tiles than the original algorithm which had a limit of 16x16=256. Do you think one might ever need more than 256x256 tiles?

**Comment by whugemann** [comment]
OK, I see that I finally got confused ;-). Yes, 160x120 and 50%x50% give exactly the same result (32x24 and 10%x10% do so, too). Using tiles with less pixels than the histogram bin count however makes no sense. IM should at least give a warning to the user (?).

I have no idea where the original limit to the tile count stems from. We could ask Karel Zuiderveld himself, as he has become a member of the IM community. I personally can think of special applications, such as astronomy or cell count, where you could possibly go for a very large number of tiles, so why not leave this decision to the user?

**Comment by whugemann** [comment]
I have just installed version 7.0.8-17 Q16 x86 2018-12-18 without HDRI support on my Windows 7 32 bit computer and now the results were very obscure, leaving a tile-wide frame of unprocessed pixels around a messed up area. The test images were too large to present them over here.

Thus, I switched back to the beta version and I am just happy with the results (and I will stop complaining over here).
