### ISSUE TITLE
ReadMipmaps does not propagate alpha_trait to mipmaps

### ISSUE THREAD

**Issue by JonnyRivers** [ImageMagick/ImageMagick#1405]
### Description

ReadMipmaps() in dds.c does not propagate alpha_trait to mipmap images.  This means that the alpha channel in mipmaps 2..N is incorrect for DDS images that have alpha < 1 in the highest mipmap.

I have fixed this locally by adding ```image->next->alpha_trait = image->alpha_trait;``` before ```image=SyncNextImageInList(image);``` in ReadMipmaps.

### Steps to Reproduce

* Create a DXT5 texture with mipmaps and with alpha < 1 in some pixels.
```
ImageInfo* imInfo = AcquireImageInfo();
SetImageOption(imInfo, "dds:skip-mipmaps", "false");
for (Image* img = GetFirstImageInList(imImage); img != nullptr; img = GetNextImageInList(img))
{
  ExportImagePixels(
    img,
    0, 0,
    img->columns, img->rows,
    "RGBA",
    StorageType::CharPixel,
    pixels,
    exInfo
  );
}
```
* Note that the alpha channel data is correct for the first image and 255 for all pixels in subsequent images.

### System Configuration
- Environment (Operating system, version and so on):  Windows 10

**Comment by JonnyRivers** [comment]
Here is a grid overlay texture that highlights the issue.

[TerrainGrid.zip](https://github.com/ImageMagick/ImageMagick/files/2645742/TerrainGrid.zip)

**Comment by dlemstra** [comment]
Thanks for reporting this and helping us figure out how to fix this. This will be resolved in the next release of ImageMagick.

**Comment by akbyrd** [comment]
@dlemstra Do you expect this is a complete fix? Are they any other settings in mip chains that aren't propagated or is it possible other codes have the same issue? I'm trying to decide if I should take the next release or wait a bit to let related issues get resolved. (I haven't had a chance to give the selective coder compilation a go so this is going to be 2 birds with one stone :) )

**Comment by dlemstra** [comment]
@akbyrd I don't think we have this issue in other coders. And please let me know how the selective coder works for you 👍
