### ISSUE TITLE
Fail to convert to true PDF/A, metadata is in UTF16 and should be in UTF8

### ISSUE THREAD

**Issue by christianclavet** [ImageMagick/ImageMagick#1409]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I was able to create PDF/A from ImageMagick (with Ghostscript), but Ghostscript refuse to encode in PDF/A because the resulting PDF metadata are stored in UTF16. It should be in UTF8 to be acceptable.
Encoding with the pdfa: keyword produce a PDF/A 3B that is not appropriate, "standard" for archival is PDF/A 1, or PDF/A 2B. 
Check here:
https://www.pdf-tools.com/pdf20/en/resources/pdf-iso-standards/pdfa-3-overview/

### Steps to Reproduce

- Use a series of images and encode them in PDF, use the resulting file and try to enforce it to PDF/A with Ghostscript, will result in a warning about wrong metadata format (UTF16) while it should be UTF8.

Repeat the same process with the PDFA process, and would result in the same warning, the resulting PDF is not PDFA at all.

### System Configuration

Windows 10 64 bit.

- ImageMagick version:
ImageMagick-7.0.8-15-portable-Q16-x64
Ghostscript GPL 9.26 win64

- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by christianclavet** [comment]
Thanks! Tested today and Ghostscript now can be able to put it in PDF/a -1. Will there be an option that we can enforce this directly  (PDF/A-1) from ImageMagick? Right now the PDFA: option will put it in PDF/A-3B.

**Comment by dlemstra** [comment]
@christianclavet Could you open a separate issue and request that feature there?
