### ISSUE TITLE
Bugs in conversion of PSD

### ISSUE THREAD

**Issue by redcap97** [ImageMagick/ImageMagick#141]
I found a bug in conversion of PSD (color mode: Bitmap, depth: 1bit, channels: 1).

```
convert file.psd file.png
```

PSD file: https://www.dropbox.com/s/ppscdtz7r3u2xsu/file.psd?dl=0

version 6.9.3-0 (Right)

![file](https://cloud.githubusercontent.com/assets/928237/13339928/9fea8b52-dc6f-11e5-9e9e-5306f4700edb.png)

version 6.9.3-5 (Wrong)

![file](https://cloud.githubusercontent.com/assets/928237/13339943/bc801a52-dc6f-11e5-9e17-b0d72c9f5ac1.png)

It looks like this commit is the cause: https://github.com/ImageMagick/ImageMagick/commit/a97a5f301305033499e3ed52fc48e123f13136df

**Comment by dlemstra** [comment]
Thanks for the report. I will take a look at it this weekend.

**Comment by dlemstra** [comment]
I just pushed a patch to fix it in GIT master and ImageMagick-6 branch @ http://git.imagemagick.org/repos/ImageMagick. The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
