### ISSUE TITLE
How to configure and build with libgcdm for lossless jpeg conversion and dicom support

### ISSUE THREAD

**Issue by ClarkSims** [ImageMagick/ImageMagick#1413]
### Description
I am compiling from source. I want to be able to convert dicom files to jpeg or png files. From various post, it sounds like I need to build with a lossless jpeg library. libgdcm has this. It is a fork of libjpeg, with the lossless patch. The header file jconfig.h is here:
/usr/include/gdcm-2.6/gdcmjpeg/jconfig.h
/usr/include/gdcm-2.6/gdcmjpeg/12/jconfig.h
/usr/include/gdcm-2.6/gdcmjpeg/16/jconfig.h
/usr/include/gdcm-2.6/gdcmjpeg/8/jconfig.h

I have several versions of the jpeg library in a single version of libgdcm. I am not sure which to use or how to set up my environment so that configure finds the libraries.

Other post says I need tiff support also, so I have included that

### Steps to Reproduce
first install libgdcm-dev and   libtiff5-dev
sudo apt-file list libgdcm2-dev

sudo apt-get install libtiff5-dev

With this command, jpeg support is not supported. I have attached the output from configure:
./configure --prefix=/usr/local/imagemagick  --with-freetype=yes --with-jpeg
[config.txt](https://github.com/ImageMagick/ImageMagick/files/2661506/config.txt)

With this command, I get configure: error: unrecognized option: `--includearch-dir=/usr/include/gdcm-2.6/gdcmjpeg/':
./configure --prefix=/usr/local/imagemagick  --with-freetype=yes  --includearch-dir=/usr/include/gdcm-2.6/gdcmjpeg/  --with-freetype=yes

### System Configuration
I am using this version of gcc on unbuntu 16.04:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

- ImageMagick version:
I just did a git clone today. I have this version:
commit f4c998836e25f05e7fdf31817aa46dc9df9056e0
Author: Cristy <urban-warrior@imagemagick.org>
Date:   Sun Dec 9 18:12:50 2018 -0500

**Comment by urban-warrior** [comment]
Type `./configure --help` for the proper option to declare the C header file location.  You likely want to use `--includedir`.
