### ISSUE TITLE
Writing Metadata(EXIF/IPTC/GPS/TIFF)  to JPG/PNG/TIFF images formats

### ISSUE THREAD

**Issue by atifjanjua** [ImageMagick/ImageMagick#1414]
### Prerequisites

- [Y] I have written a descriptive issue title
- [N] I have verified that I am using the latest version of ImageMagick 
- [Y] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I am using ImageMagick for .net 7.3.0.0 for writing Medadata, which consists of EXIF, IPTC, GPS and TIFF. I have to write metadata in three image formats i.e jpeg, png and tiff. 
All mentioned metadata is written successfully in the jpeg images, but tiff  writes IPTC/TIFF and png did not write any thing.
I also tried "convert" utility with different switches to do so but no results.

1-Need to write EXIF and GPS data including IPTC and TIFF in tiff file formats.
2-Need to write EXIF/IPTC/GPS/TIFF data to png file formats.

- System Configurations

Microsoft Windows 10
Visual Studio 2015

- ImageMagick version:

Magick.NET-Q16-AnyCPU.dll 7.3.0.0

**Comment by dlemstra** [comment]
Do you have a command line example that does not work with the latest release of ImageMagick?

**Comment by atifjanjua** [comment]
Eventually I want to write tiff and png images using source code as i am writing jpeg images, like 

 NativeColorSpaceImage.AddProfile(EXIFProfile);
 NativeColorSpaceImage.AddProfile(IPTCProfile);
 NativeColorSpaceImage.write(Path);

All profiles are added successfully in the NativeColorSpaceImage but at the time of writing in tiff and png formats it looses data.

I just tried to convert the jpeg(containing all metadata) images to tiff/png with convert utility.

convert image.jpeg image.tiff or image.png.

1- I have to add more than 100 fields of metadata, are you expecting to do this one by one using convert utility??????
2- Is this possible to write all metadata in tiff/png image using source code ????
3- Can you please tell me command to convert jpeg images to tiff/png in one go, including  all metadata that jpeg format contains?????

**Comment by dlemstra** [comment]
Could you open an issue here instead: https://github.com/dlemstra/Magick.NET. And could you also include a small code sample that I can use to reproduce the issue? And please upgrade to the latest version of Magick.NET this might be a bug in an earlier version.
