### ISSUE TITLE
Inconsistent RAM usage

### ISSUE THREAD

**Issue by joost823** [ImageMagick/ImageMagick#1416]
I have a folder with 365 .png images, from 0001.png to 0365.png I try to make one big .gif out of it using convert. However, it eats up all my RAM (8GB) and SWAP (8 GB), of which only 2 GB is used when not running imagemagick. All images have the same dimensions (900 x 800), and filesize ranges from 180kb to 200kb. Can someone explain why this is happening?

    convert -delay 20 gif_dump/0[0-3]*.png test.gif 

consumes 12+GB (365 images)

    convert -delay 20 gif_dump/0[0-1]*.png test.gif 

consumes 455 mb  (200 images)

    convert -delay 20 gif_dump/0[1-2]*.png test.gif

 consumes 455 mb  (200 images)

    convert -delay 20 gif_dump/0[2-3]*.png test.gif 

consumes 455 mb ( 165 images)

Version: ImageMagick 6.9.7-4 Q16 x86_64 running on ubuntu 18.04

**Comment by urban-warrior** [comment]
Review https://imagemagick.org/script/architecture.php for how resources are consumed by the pixel cache.  To conserve memory, you can trade-off memory for performance by pushing the pixel cache to disk.  See https://imagemagick.org/script/architecture.php#tera-pixel.
