### ISSUE TITLE
Error processing certain jpg metadata (7.0.8-15 and above)

### ISSUE THREAD

**Issue by jsfeldman** [ImageMagick/ImageMagick#1419]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Between versions 7.0.8-14 and 7.0.8-15 I think a bug developed when processing the metadata of some jpg files. When I run identify on the image I get this:

```
$ magick identify ~/Desktop/magick_broken_img.jpg
identify: CorruptImageProfile `xmp' @ warning/profile.c/SetImageProfileInternal/1746.
identify: memory allocation failed `/Users/.../Desktop/magick_broken_img.jpg' @ error/jpeg.c/ReadProfile/803.
identify: Improper call to JPEG library in state 201 `/Users/.../Desktop/magick_broken_img.jpg' @ error/jpeg.c/JPEGErrorHandler/333.
```

but it seems to process fine when I run it on version 7.0.8-14.

### Steps to Reproduce
Run `magick identify` on this image:
![magick_broken_img](https://user-images.githubusercontent.com/8559979/49960722-b2686a80-fec5-11e8-8b50-719aad2e427f.jpg)

### System Configuration
It has occurred for me both on Mac and Ubuntu

- ImageMagick version: 7.0.8-15 & 7.0.8-16
- Environment (Operating system, version and so on): macOS Mojave 10.14.1
- Additional information: Let me know if you need any other information. Sorry if this has been reported already, but I couldn't find anything that matched this. Thanks!

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by 284794507** [comment]
this bug is still exsit in Magick.NET-Q8-AnyCPU 7.11.0

**Comment by zaharcelac** [comment]
Faced the same issue in **ImageMagick 7.0.9-22 Q16 x86_64 2020-02-06**

`mogrify: CorruptImageProfile `xmp' @ warning/profile.c/SetImageProfileInternal/1704.`

**Comment by hbakkercg** [comment]
Seeing this in
ImageMagick 7.0.10-4 Q16 x86_64 2020-03-30 
identify: CorruptImageProfile `xmp' @ warning/profile.c/SetImageProfileInternal/1884.

**Comment by nshoes** [comment]
Why is this closed? Also seeing the error:
```convert: CorruptImageProfile `xmp' @ warning/profile.c/SetImageProfileInternal/1884```

**Comment by alexey-samoylov** [comment]
> Why is this closed? Also seeing the error:
> `` convert: CorruptImageProfile `xmp' @ warning/profile.c/SetImageProfileInternal/1884 ``

Also see the same error

**Comment by urban-warrior** [comment]
We're using the latest release of ImageMagick, 7.0.10-14 and the image and profile is read without complaint.  Post a link to your image if if throws the warning and we'll try to reproduce the problem.

**Comment by aiooly** [comment]
Got same error, use ImageMagick: `7.0.10-14` and try to call this command `convert -units pixelsperinch -density 72x72 test-convert/multi-pages.pdf -append -quality 80 test-convert/multi-pages-1.jpeg`
```
convert: CorruptImageProfile `xmp' @ warning/profile.c/SetImageProfileInternal/1888
```

**Comment by dlemstra** [comment]
And where can we find `test-convert/multi-pages.pdf` @aiooly ? We cannot reproduce this issue with the image in this issue and none of the other comments provide us with another test image.

**Comment by potterpg** [comment]
I also have this error using the Magick++ CPP API:
Version: ImageMagick 7.0.10-17 Q16 x86_64 2020-06-19
Error in XCODE: (MacOS Catalina)
![Screenshot - 27_07_2020 , 13_56_57](https://user-images.githubusercontent.com/25082282/88544401-3aef3c80-d011-11ea-855a-8a46cabe7d3c.png)
Image used:
![IMG_0708](https://user-images.githubusercontent.com/25082282/88544443-4b9fb280-d011-11ea-9718-061c92c6e03e.jpg)

Same solution compiled on Windows with VS2019 does seem to work?

**Comment by Tom2112** [comment]
I'm using ImageMagick 7.0.10-34 Q16 2020-10-08 on Windows 10.0.19041.572, and I get the CorruptImageProfile error only when performing batch operations on a folder of images, such as:
`identify *.jpg`
But not when I run identify individually for each image.
I also get the error when I run the following as part of a batch file:
`magick mogrify -quality 60 -resize "1024x1024>" -path R:\1024\ *.jpg`
Sorry I can't post the images, as they are NSFW and copyrighted. If you know how I can get them to you for testing without posting them here, I'd be happy to send them.

**Comment by dlemstra** [comment]
My email is on my profile.
