### ISSUE TITLE
black line sometimes appears when appending together png files

### ISSUE THREAD

**Issue by giltayar** [ImageMagick/ImageMagick#1420]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using `-append` with some pngs, I sometimes get black (or white) one-pixel lines inserted into the resulting image.

### Steps to Reproduce
1. `git clone https://github.com/giltayar/imagemagick-stitching-bug.git`
2. `cd imagemagick-stitching-bug`
3. `for i in {1..100}; do magick -limit memory 32Mib -limit map 32Mib screenshot0.png screenshot1.png -append result.png && compare result.png expected-screenshot.png diff.png ; echo $?; done`
4. I consistently get `compare` failing sporadically (always happens after 5 tries) due to a black line appearing.

### System Configuration
Linux running in a Docker container (node:10)

- ImageMagick version: 7.0.8-16
- Environment (Operating system, version and so on): Linux running in a Docker container (node:10 image)
- Additional information:
It does *not* happen when compiling using `--with-quantum-depth=8 --disable-hdri` on `configure`.

**Comment by urban-warrior** [comment]
Add `--disable-openmp` to the configure script command-line and rebuild / reinstall ImageMagick.  Does that resolve the black-line issue?  If so, the problem is a faulty OpenMP delegate library.  If the problem persists, let us know and we will investigate further.

**Comment by giltayar** [comment]
Tried it just now. Unfortunately, problem still persists.

**Comment by giltayar** [comment]
Note for other developers with the same problem: the workaround (of adding `--with-quantum-depth=8 --disable-hdri` to `configure`) _does_ work.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
