### ISSUE TITLE
Magick++: Request support for pingImages()

### ISSUE THREAD

**Issue by rodlie** [ImageMagick/ImageMagick#1421]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I would like to request a new feature in Magick++; ``pingImages()``. It should work that same way as ``readImages()`` works today (but without the pixel data of course). This would help speed up reading layered files in Magick++.

```
std::list<Magick::Image> images;
Magick::readImages(&images, filename);
```
```
std::list<Magick::Image> images;
Magick::pingImages(&images, filename);
```

### Steps to Reproduce

No steps needed to reproduce.

### System Configuration

- ImageMagick version: 6.9.10-16
- Environment: Linux/Windows/Mac
- Reference: https://imagemagick.org/discourse-server/viewtopic.php?f=23&t=35193

**Comment by dlemstra** [comment]
This feature will be available in the next release of ImageMagick 7. We only add new features to IM7 so this will not become available in ImageMagick 6.

**Comment by rodlie** [comment]
Great, thanks!
