### ISSUE TITLE
assertion failed in CopyMagickMemory 

### ISSUE THREAD

**Issue by paon-m** [ImageMagick/ImageMagick#1423]
Hi,

we are using php ImageMagick extension to process some jpeg images converting them in some lower formats:

                  $im = new \Imagick($filePath);
                   //if height or width are greater than resize value resize image
                    if ($im->getimagewidth() > $resizeDim || $im->getimageheight() > $resizeDim) {
                        $im->resizeImage($resizeDim, $resizeDim, \Imagick::FILTER_LANCZOS, 1, true);
                    }
                    $im->transformimagecolorspace(\Imagick::COLORSPACE_RGB);
                    $im->setImageFormat('jpg'); //change image format
                    $im->writeImage($destinationFilePath);

and sometimes we have php crashing with this assert:

php: magick/memory.c:508: CopyMagickMemory: Assertion `source != (const void *) ((void *)0)' failed. 

Unfortunately is not something that happens always on the same images but it seems to occur randomly, so we don't a have a way to reproduce it with a test case.

Technical data : 
Red Hat Enterprise Linux Server release 6.4
4 cpu, 8gb ram
php 5.5.23
ImageMagick 6.5.7

I know it's an old version of php and ImageMagick, so I would know if update them will solve the problem, if yes please advise on the version we should use.
Many thanks in advance

Massimo

**Comment by dlemstra** [comment]
I would advise you to wait a couple days for the new version. The current release has some issues with JPEG files that contain XMP profiles. But I have no idea if that will resolve your issue. That is something that you will have to find out for yourself.
