### ISSUE TITLE
Background PNG is black after 8:6.7.7.10-6ubuntu3.13

### ISSUE THREAD

**Issue by jeremydevos** [ImageMagick/ImageMagick#1427]
Hello,

After applying the ImageMagick update:
https://launchpad.net/ubuntu/+source/imagemagick/8:6.7.7.10-6ubuntu3.13

The generation of an image presents black squares (JPG).

This situation is on an ubuntu 14.04

Is it possible to have an explanation? should I add a parameter to avoid this problem?

Thank you
Jeremy

**Comment by urban-warrior** [comment]
We need a method to reproduce the problem before we can comment.   What command-line produces the black squares?  Does it happen always or with select images?
