### ISSUE TITLE
Composite of png onto bitonal TIFF and saving as PNG fails

### ISSUE THREAD

**Issue by kevindente** [ImageMagick/ImageMagick#1428]
### Description
I have
1) A 1 bpp (bitonal) TIFF image with g4 compression 
2) A small PNG file being tiled across the base image using composite

Running composite and saving the result to a PNG renders the original image to the PNG, but doesn't have the PNG contents tiled across the image. If I save it as JPG the composite works as expected. If I change the image to an 8 bit depth with no compression first then the composite works as expected. 

### Steps to Reproduce

composite overlay.png  sourcetiff.tif[0] -tile" "test1.png"  // no composite
composite overlay.png sourcetiff.tif[0] -tile" "test1.jpg"  // composite works
composite overlay.png sourcetiff.tif[0] -compress none -depth 8 -tile" "test1.png"  //composite works
composite overlay.png sourcetiff.tif[0] -compress none -depth 2 -tile" "test1.png"  //composite works
composite overlay.png sourcetiff.tif[0] -compress none -depth 1 -tile" "test1.png"  //no composite

There are no errors displayed  - it just renders the source image without the overlay

### System Configuration
- ImageMagick version:
7.0.8-16
- Environment (Operating system, version and so on):
macOS Mojave 10.14.2
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
