### ISSUE TITLE
Unable to draw as there is no PNG delegate but its installed.

### ISSUE THREAD

**Issue by vickylance** [ImageMagick/ImageMagick#1430]
### Prerequisites

- [ x ] I have written a descriptive issue title
- [ x ] I have verified that I am using the latest version of ImageMagick
- [ x ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am trying to create images out of an image using the draw command. But I am getting no delegate for PNG but its already installed.

### Steps to Reproduce
I did the following commands.
```
E:\Projects>convert -size 353x371 xc:none -draw 'image Over 0,0 100,100 image.png' flappy.png
convert: non-conforming drawing primitive definition `image' @ error/draw.c/RenderMVGContent/4361.
convert: unable to open image 'Over': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: unable to open image 'Over': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/556.
convert: unable to open image '0,0': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: unable to open image '0,0': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/556.
convert: unable to open image '400,300': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: unable to open image '400,300': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/556.
convert: unable to open image 'image.png'': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: unable to open image 'image.png'': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: unable to open module file 'C:\Program Files\ImageMagick-7.0.8-Q16\modules\coders\IM_MOD_RL_PNG'_.dll': No such file or directory @ warning/module.c/GetMagickModulePath/675.
convert: no decode delegate for this image format `PNG'' @ error/constitute.c/ReadImage/556.

E:\Projects>convert -list configure

Path: [built-in]

Name                  Value
-------------------------------------------------------------------------------
FEATURES              OpenMP
MAGICK_TEMPORARY_PATH C:/Users/vkkpp/AppData/Local/Temp
NAME                  ImageMagick
QuantumDepth          16

Path: C:\Program Files\ImageMagick-7.0.8-Q16\configure.xml

Name                  Value
-------------------------------------------------------------------------------
CC                    vs10
COPYRIGHT             Copyright (C) 1999-2018 ImageMagick Studio LLC
DELEGATES             bzlib freetype jpeg jp2 lcms png raw tiff x11 xml wmf zlib
FEATURES              OpenMP
HOST                  Windows
LIB_VERSION           0x708
LIB_VERSION_NUMBER    7,0,8,20
NAME                  ImageMagick
RELEASE_DATE          2019-01-01
VERSION               7.0.8
WEBSITE               http://www.imagemagick.org

E:\Projects>
```

### System Configuration

ImageMagick version: 7.0.8
- Environment (Operating system, version and so on): Windows 10 Pro
- Additional information:

**Comment by dlemstra** [comment]
On Windows you will need to use `"` instead of `'`. What happens when you use this command:
`convert -size 353x371 xc:none -draw "image Over 0,0 100,100 image.png" flappy.png`?

**Comment by vickylance** [comment]
@dlemstra When I run the cmd that u mentioned I am getting the below error.
```
E:\Projects>convert -size 353x371 xc:none -draw "image Over 0,0 100,100 image.png" flappy.png
convert: unable to open image 'image.png': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: non-conforming drawing primitive definition `image' @ error/draw.c/RenderMVGContent/4361.

E:\Projects>
```

**Comment by vickylance** [comment]
@fmw42  I am still getting the same error.
I tried in my windows and mac machine as well. same error. Also I tried in Ubuntu bash in windows still getting the same error.

```
 $ convert -size 353x371 xc:none -draw "image Over 0,0 100,100 'image.png'" flappy.png
convert: unable to open image 'image.png': No such file or directory @ error/blob.c/OpenBlob/3490.
convert: non-conforming drawing primitive definition `image' @ error/draw.c/RenderMVGContent/4361.
```

**Comment by fmw42** [comment]
Your command:

`magick -size 714x512 canvas:none -draw "image Over 0,0 100,100 'image.png'" flappy.png`

works fine for me on IM 7.0.8.20 Q16 HDRI Mac OSX Sierra. But note that using 0,0 100,100 resizes the image.png and does not just crop it. So it you want just a subsection, you will need to crop first.

Perhaps a better way, is to either resize or crop and use -compose over -composite.

To resize:
`magick -size 714x512 canvas:none \( image.png -resize 100x100 \) -gravity northwest -geometry +0+0 -compose over -composite flappy1.png`

To crop:
`magick -size 714x512 canvas:none \( image.png -crop 100x100+0+0 +repage \) -gravity northwest -geometry +0+0 -compose over -composite flappy2.png`

Note that: -gravity northwest -geometry +0+0 are the defaults and can be removed above. But if you want to place the resized or cropped image elsewhere, then you need them. 

For Windows, remove the all the \

See:
https://imagemagick.org/script/command-line-options.php#gravity
https://imagemagick.org/script/command-line-options.php#geometry
https://imagemagick.org/Usage/layers/#convert

**Comment by vickylance** [comment]
@fmw42 I am still not able to get it to work. :(
<img width="1677" alt="screenshot 2018-12-27 at 12 22 44 am" src="https://user-images.githubusercontent.com/5861833/50454442-a4a6f080-096d-11e9-8f8a-59809ae912bd.png">

**Comment by fmw42** [comment]
Was this on your Mac or Windows. If your Mac, then perhaps your install is bad or you need to provide the path the image.png. Are you sure you have the proper name of the image?

**Comment by vickylance** [comment]
it is my mac. Isnt the image.png the one that will be created newly from the flappy.png? if so why do i need to give a path to image.png?

**Comment by fmw42** [comment]
No, image.png is the input image that you posted and which you want to crop and then place into the canvas:none image that first created. Perhaps if you explain what you are trying to do, I can help further. If you just want to crop the image you posted, then 

`convert image.png -crop WxH+X+Y +repage cropped.png`

See
https://imagemagick.org/Usage/crop/#crop

**Comment by vickylance** [comment]
Ok so as you can see the flappy.png is a texture atlas from which I want to crop out all the individual sprites in a single command. I used https://www.leshylabs.com/apps/sstool/ this online tool to create sections of each of the sprites and there is a imagemagick export command in that tool itself which is supposed to be used to cut the input image into multiple individual sprites.
and it exported the above command.

**Comment by fmw42** [comment]
try

magick -size 714x512 canvas:none \( flappy.png -crop 100x100+0+0 +repage \) -gravity northwest -geometry +0+0 -compose over -composite flappy_output.png

**Comment by vickylance** [comment]
Ok that works but can you tell me what the below command does. I got it from the above website by following the below steps.
1. go to https://www.leshylabs.com/apps/sstool/
2. drag and drop the flappy.png
3. click the remap button below
4. select ImageMagick from the below dropdown and it will generate the imagemagick command to crop all the sprites.

```
convert \
        -size 714x512\
        canvas:none \
        -draw "image SrcOver 0, 0 288, 512 sprite1.png" \
        -draw "image SrcOver 292, 0 308, 112 sprite2.png" \
        -draw "image SrcOver 604, 0 52, 270 sprite3.png" \
        -draw "image SrcOver 660, 0 52, 242 sprite4.png" \
        -draw "image SrcOver 292, 116 226, 116 sprite5.png" \
        -draw "image SrcOver 574, 116 26, 28 sprite6.png" \
        -draw "image SrcOver 528, 128 34, 24 sprite7.png" \
        -draw "image SrcOver 574, 148 12, 14 sprite8.png" \
        -draw "image SrcOver 594, 152 2, 2 sprite9.png" \
        -draw "image SrcOver 590, 162 2, 2 sprite10.png" \
        -draw "image SrcOver 574, 168 26, 28 sprite11.png" \
        -draw "image SrcOver 528, 180 34, 24 sprite12.png" \
        -draw "image SrcOver 576, 200 14, 20 sprite13.png" \
        -draw "image SrcOver 536, 220 10, 10 sprite14.png" \
        -draw "image SrcOver 524, 222 6, 6 sprite15.png" \
        -draw "image SrcOver 492, 236 80, 28 sprite16.png" \
        -draw "image SrcOver 582, 236 10, 20 sprite17.png" \
        -draw "image SrcOver 348, 244 34, 24 sprite18.png" \
        -draw "image SrcOver 446, 248 34, 24 sprite19.png" \
        -draw "image SrcOver 344, 264 10, 8 sprite20.png" \
        -draw "image SrcOver 492, 268 80, 28 sprite21.png" \
        -draw "image SrcOver 578, 268 14, 20 sprite22.png" \
        -draw "image SrcOver 344, 272 6, 4 sprite23.png" \
        -draw "image SrcOver 604, 274 44, 44 sprite24.png" \
        -draw "image SrcOver 358, 282 10, 12 sprite25.png" \
        -draw "image SrcOver 440, 288 44, 44 sprite26.png" \
        -draw "image SrcOver 492, 300 80, 28 sprite27.png" \
        -draw "image SrcOver 578, 300 14, 20 sprite28.png" \
        -draw "image SrcOver 360, 306 2, 6 sprite29.png" \
        -draw "image SrcOver 378, 308 44, 18 sprite30.png" \
        -draw "image SrcOver 352, 310 4, 4 sprite31.png" \
        -draw "image SrcOver 366, 310 4, 4 sprite32.png" \
        -draw "image SrcOver 354, 316 20, 26 sprite33.png" \
        -draw "image SrcOver 604, 322 32, 32 sprite34.png" \
        -draw "image SrcOver 582, 324 6, 14 sprite35.png" \
        -draw "image SrcOver 292, 346 112, 44 sprite36.png" \
        -draw "image SrcOver 408, 346 76, 38 sprite37.png" \
        -draw "image SrcOver 488, 346 80, 28 sprite38.png" \
        -draw "image SrcOver 574, 346 14, 20 sprite39.png" \
        -draw "image SrcOver 604, 358 32, 32 sprite40.png" \
        -draw "image SrcOver 574, 370 14, 20 sprite41.png" \
        -draw "image SrcOver 484, 394 80, 28 sprite42.png" \
        -draw "image SrcOver 568, 394 12, 14 sprite43.png" \
        -draw "image SrcOver 584, 394 12, 14 sprite44.png" \
        -draw "image SrcOver 292, 398 96, 38 sprite45.png" \
        -draw "image SrcOver 394, 398 86, 38 sprite46.png" \
        -draw "image SrcOver 484, 426 80, 28 sprite47.png" \
        -draw "image SrcOver 568, 426 12, 14 sprite48.png" \
        -draw "image SrcOver 584, 426 12, 14 sprite49.png" \
        -draw "image SrcOver 292, 442 66, 38 sprite50.png" \
        -draw "image SrcOver 364, 442 102, 44 sprite51.png" \
        -draw "image SrcOver 484, 458 44, 44 sprite52.png" \
        -draw "image SrcOver 532, 458 44, 44 sprite53.png" \
        -draw "image SrcOver 580, 462 10, 10 sprite54.png" \
        -draw "image SrcOver 292, 490 32, 14 sprite55.png" \
        -draw "image SrcOver 330, 490 14, 20 sprite56.png" \
        -draw "image SrcOver 350, 490 14, 20 sprite57.png" \
        -draw "image SrcOver 370, 490 14, 20 sprite58.png" \
        -draw "image SrcOver 390, 490 14, 20 sprite59.png" \
        -draw "image SrcOver 408, 490 12, 14 sprite60.png" \
        -draw "image SrcOver 424, 490 12, 14 sprite61.png" \
        -draw "image SrcOver 440, 490 12, 14 sprite62.png" \
        -draw "image SrcOver 456, 490 12, 14 sprite63.png" \
        spritesheet.png
```

**Comment by vickylance** [comment]
Ok I think I will write a simple script to convert the exported json format from that tool to image magick crop command that u gave in a chaining fashion. to get all the sprites in a single go.

**Comment by fmw42** [comment]
This script will extract all your sprites from the spritesheet image you provided.

```
cropArr=(`convert spritesheet.png -alpha extract -type bilevel \
-define connected-components:verbose=true \
-define connected-components:area-threshold=0 \
-connected-components 4 \
null: | grep "gray(255)" | sed 's/^[ ]*//' | cut -d " " -f2`)

num=${#cropArr[*]}

for ((i=0; i<num; i++)); do 
convert spritesheet.png -crop ${cropArr[i]} +repage image_$i.png
done

```

It uses connected components. First I extract the alpha channel and use connected components to locate all the white regions in your image. Then for each crop region that it finds, I crop the image and saved to a new image for that region.

See https://imagemagick.org/script/connected-components.php

**Comment by vickylance** [comment]
@fmw42  Wow thank you soo much your script works like charm once I bump the area threshold to 20pixel. I feel like creating an entire tool using it :D

**Comment by vickylance** [comment]
@fmw42 Hi I just wanted to know if its possible to get the coordinates of each pixels of each connected components instead of imagemagick itself creating and dumping the images

**Comment by fmw42** [comment]
You can get the coordinates of the bounding box and the centroid from connected-components. If you want the coordinate of each pixel of each individual region, then you can save to txt: format rather than   image_$i.png. Perhaps I do not understand your question. So please clarify if my answer is not what you want.
