### ISSUE TITLE
Regression unit identify

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#1442]
From debian bug (urgent near freeze) https://bugs.debian.org/918642

Could you copy paste the patch as answer here or send me to my usual adress to get fixed before freeze.

Dear Maintainer,

After the upgrade from 6.9.10.14 to 6.9.10.23, I noticed that the
autopkgtests for the package ruby-mini-magick is failing due to one test
about checking units to show the size of the image in cm and inches.

I could isolate the problem by running the `identify` command on a test
image (rgb.png in the spec/fixtures directory of the ruby-mini-magick
source package).

Running:
identify -verbose -units PixelsPerInch rgb.png > output_in.txt
identify -verbose -units PixelsPerCentimeter rgb.png > output_cm.txt
diff -u output_in.txt output_cm.txt

gives me the following with 8:6.9.10-14 from testing:

```
--- /tmp/output_cm.txt  2019-01-07 22:32:49.257702663 +0100
+++ /tmp/output_in.txt  2019-01-07 22:32:40.457055525 +0100
@@ -3,9 +3,9 @@
   Mime type: image/png
   Class: PseudoClass
   Geometry: 16x12+0+0
-  Resolution: 118.11x118.11
-  Print size: 0.135467x0.1016
-  Units: PixelsPerCentimeter
+  Resolution: 300x300
+  Print size: 0.0533333x0.04
+  Units: PixelsPerInch
   Colorspace: sRGB
   Type: Palette
   Base type: Undefined
@@ -118,12 +118,11 @@
     signature: 0d23f0078b8f89ca473e67bb38773cb94fd8ec5591e4207e83ff95cb27a6a0dd
   Artifacts:
     filename: rgb.png
-    units: PixelsPerCentimeter
+    units: PixelsPerInch
     verbose: true
   Tainted: False
   Filesize: 359B
   Number pixels: 192
-  Pixels per second: 19200B
-  User time: 0.010u
-  Elapsed time: 0:01.010
+  User time: 0.000u
+  Elapsed time: 0:01.000
   Version: ImageMagick 6.9.10-14 Q16 x86_64 20181023 https://imagemagick.org
```
whereas it gives the following with 8:6.9.10-23 (with a suffix -23 to
the text files).

```
--- /tmp/output_cm-23.txt       2019-01-07 22:34:38.136761722 +0100
+++ /tmp/output_in-23.txt       2019-01-07 22:34:45.201163917 +0100
@@ -5,7 +5,7 @@
   Geometry: 16x12+0+0
   Resolution: 118.11x118.11
   Print size: 0.135467x0.1016
-  Units: PixelsPerCentimeter
+  Units: PixelsPerInch
   Colorspace: sRGB
   Type: Palette
   Base type: Undefined
@@ -118,7 +118,7 @@
     signature: 0d23f0078b8f89ca473e67bb38773cb94fd8ec5591e4207e83ff95cb27a6a0dd
   Artifacts:
     filename: rgb.png
-    units: PixelsPerCentimeter
+    units: PixelsPerInch
     verbose: true
   Tainted: False
   Filesize: 359B
```

Maybe it was induced by this change?
https://github.com/ImageMagick/ImageMagick6/commit/8c7648a1adf7bba35594074f191affd3ff3263bb

Attaching the reference image and the full output files.

I am setting severity serious, as it breaks the testsuite of
ruby-mini-magick and provides wrong data when identifying images.

Thank you in advance

Cédric

**Comment by urban-warrior** [comment]
We'll will revert the patch and determine a better strategy to handle https://imagemagick.org/discourse-server/viewtopic.php?f=3&t=35185 while ensuring the ruby-magic unit tests do not fail.  Can you apply the patch to 6.9.10-23 or do you require a 6.9.10-24 release?  If so, let us know and we will schedule a release within the next few days.

**Comment by bastien-roucaries** [comment]
Will revert locally. A fix of both issue will be welcome and applied.

A release is appreciated but not stricly needed
