### ISSUE TITLE
Take the wrong orientation tag when a photo have both exif:Orientation and tiff:Orientation

### ISSUE THREAD

**Issue by liuzhe0223** [ImageMagick/ImageMagick#1445]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
IM may take the wrong orientation tag when a photo have both `exif:Orientation` and `tiff:Orientation`.

### Steps to Reproduce

1.  `wget https://o4itt7tbh.qnssl.com/media/upload/qq52475308@7-1488955710037-6.jpeg`
2.  `identify -verbose qq52475308@7-1488955710037-6.jpeg | grep Orientation`
```
  Orientation: LeftBottom
    exif:Orientation: 1
    tiff:Orientation: 8
```

Chrome and firefox  would chose `exif:Orientation: 1` as Orientation.

### System Configuration
- ImageMagick version:  ImageMagick 7.0.8-23 Q16 
- Environment: macOS 10.14.1

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
