### ISSUE TITLE
Annotate Position and Skewing Text

### ISSUE THREAD

**Issue by snlacks** [ImageMagick/ImageMagick#1446]
### Description
When using -composite -annotate some of the positioning is different/incorrect in 7.0.8-22. When reverting to 7.0.8-14 it works.

example a position will be set, but the placement of the horizontal is too far to the right and the text becomes skewed.

### Steps to Reproduce
magick convert -size 900x550 xc:white  -gravity center \(   filename -charcoal 2 -resize 686x310   \) -geometry -15-15 -composite -gravity center \(  templateFilename -gravity center -pointsize 20 -font ArialB -annotate -400-30 '37.75"' -annotate -10+170 '128.5"' -annotate +365-122 '34.75"' \) -composite outputFilename

- ImageMagick version: 
broken on 7.0.8-22,
works on 7.0.8-14 (not sure of other versions)
- Environment (Operating system, version and so on):
Mojave MacOS 10.14.2

May be related to: https://github.com/ImageMagick/ImageMagick/issues/209

**Comment by snlacks** [comment]
Thanks for responding, I can't currently provide images I don't own them. I will see if I can create a mock version but that's not my area of expertise.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
