### ISSUE TITLE
Issue: Convert RGB PDF to CMYK PDF

### ISSUE THREAD

**Issue by deepakkjose** [ImageMagick/ImageMagick#1448]
I have an issue (ImageMagick version 6.9.3) for converting sRGB PDF file to CMYK.
The output PDF file always "RGB". It is not converting to CMYK
This issue only happening to convert PDF to PDF.
On PDF to JPG conversion colorspace change to CMYK.

The command we have used is
convert "source.pdf" -colorspace cmyk "output.pdf"

**Comment by fmw42** [comment]
This works for me on IM 6.9.10.23 Q16 Mac OSX Sierra with Ghostscript 9.25

```
convert lena.jpg lena.pdf
convert lena.pdf -colorspace CMYK lena2.pdf
identify -verbose lena2.pdf
Image: lena2.pdf
  Format: PDF (Portable Document Format)
  Mime type: application/pdf
  Class: DirectClass
  Geometry: 256x256+0+0
  Resolution: 72x72
  Print size: 3.55556x3.55556
  Units: Undefined
  Colorspace: CMYK  <------CMYK
  Type: ColorSeparation
  Endianess: Undefined
  Depth: 16/8-bit

```
Perhaps you should post your PDF file, so it can be examined. Also what is your platform and exact IM version 6.9.3.x and date of the version. Also what is your version of Ghostscript used to read the PDF file.

**Comment by deepakkjose** [comment]
I am using IM 6.9.3.2 Q8 (26-10-2017), Windows 10, Ghostscript 9.26.

I have attached my sample file.

[rgb_to_cmyk.pdf](https://github.com/ImageMagick/ImageMagick/files/2744462/rgb_to_cmyk.pdf)

**Comment by dlemstra** [comment]
I wonder if this can all be done with Ghostscript. Don't think ImageMagick is the correct tool when converting from PDF to PDF.

**Comment by fmw42** [comment]
I agree with Dirk. If your input PDF has an imbedded image, then you might want to extract it with pdfimages and then convert it to PDF again. Or perhaps there are other tools that might work better.
