### ISSUE TITLE
ImageMagick 7 converts alpha to black

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [ImageMagick/ImageMagick#145]
Input image: https://i.imgur.com/RXdHeLx.png

Very simple 32-bit PNG, black text on transparent background. Using current IM7 beta magick.exe (from https://www.imagemagick.org/download/beta/ImageMagick-7.0.0-0~beta20160302-portable-Q16-x64.zip, identifies as 7.0.0-0 Q16 x64 2016-02-28), I use this commandline:

`magick test.png -filter Lanczos -distort Resize 250x250 output.png`

Expected result: Image is scaled with no issues, as previously worked
Actual result: Image is now entirely black

Using Windows 7 x64, CPU is Intel i7-5820k.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
