### ISSUE TITLE
Problem with pipes on linux

### ISSUE THREAD

**Issue by Vampire** [ImageMagick/ImageMagick#1458]
I'm using `identify` on Ubuntu from the imagemagick package `8:6.9.7.4+dfsg-16ubuntu6.4` to verify various file types.

While this works fine:
```bash
$ identify -regard-warnings otf:FontAwesome.otf && echo true || echo false
otf:FontAwesome.otf=>FontAwesome.otf OTF 800x480 800x480+0+0 16-bit sRGB 135KB 0.060u 0:00.050
true
```

this does not:
```bash
identify -regard-warnings otf:<(cat FontAwesome.otf) && echo true || echo false
otf:/dev/fd/63=>/dev/fd/63 OTF 800x480 800x480+0+0 16-bit sRGB 0.190u 0:00.199
identify-im6.q16: unable to read font `/dev/fd/63' @ warning/annotate.c/RenderType/964.
false
```

So it seems imagemagick does not cope well with pipes.
It displayed the correct result but then had a warning.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
