### ISSUE TITLE
Region selection in "import" command produce corrupted graphics and output (Unexpected lines).

### ISSUE THREAD

**Issue by OmarSquircleArt** [ImageMagick/ImageMagick#1460]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When taking a screenshot using the command `import test.png`, the rectangle lines used to visualize the selected region leave trails and artifacts, those lines are preserved and are visible in the final image. This gif illustrates the problem:

![Problem](https://user-images.githubusercontent.com/25300994/51685829-dc01cf00-1ff7-11e9-8e01-6e7c56ed5d64.gif)

### Steps to Reproduce
Execute: `import test.png`

### System Configuration

- ImageMagick version: 7.0.8
- Environment (Operating system, version and so on): Arch Linux. Deepin Desktop Environment. Using AMDGPU driver with Mesa's RadeonSI OpenGL implementation on an RX 590.
- Additional information:
```
Features: Cipher DPC HDRI Modules OpenCL OpenMP 
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp wmf x xml zlib
```
This [question](https://superuser.com/questions/1295713/weird-border-artefacts-when-taking-screenshots-with-import) on SuperUser seem to be related.

**Comment by urban-warrior** [comment]
The ImageMagick code that supports "rubber banding" has worked well and remained unchanged for nearly 20 years now.  Recently we have seen the behavior you reported suggesting a change and / or bug in the Windows manager or in the X11 protocol.  We'll investigate but it will likely take some time to track the source of this problem.

**Comment by OmarSquircleArt** [comment]
@urban-warrior Do you mind pointing me to the source code for the drawing? I might try and solve this myself, since I can replicate it readily.

**Comment by urban-warrior** [comment]
Take a look @ MagickCore/XSelectWindow().  XSelectWindow() allows a user to select a window using the mouse.  If the mouse moves, a cropping rectangle is drawn and the extents of the rectangle is returned.

**Comment by OmarSquircleArt** [comment]
@urban-warrior It seems the unexpected results are resulted from applications redrawing the regions where the selection happens, thus rubber banding fails.

Grabbing the X server before performing the selection solves the problem. I tried it in multiple situations and it worked fine. Is there an objection to this approach?

**Comment by urban-warrior** [comment]
We grab the pointer but your suggesting we grab the server as well.  Easy enough to do.  Can you create a pull request with the patch or I suspect its just a few lines, you can post it here.

**Comment by OmarSquircleArt** [comment]
@urban-warrior The patch is indeed simple. However, I am not sure how to create diffs. So I just created a pull request #1563. I also added more details to explain why the server should be grabbed.

One question though, what is the significance of `(void)` in the function call `(void) XGrabServer(display);`?
