### ISSUE TITLE
imageMagick portable x86 binaries package contains 64bit ffmpeg.exe

### ISSUE THREAD

**Issue by pmiess** [ImageMagick/ImageMagick#1461]
### Prerequisites

- [ X] I have written a descriptive issue title
- [ X] I have verified that I am using the latest version of ImageMagick
- [ X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
if I run the ffmpeg from 
https://imagemagick.org/download/binaries/ImageMagick-7.0.8-24-portable-Q16-x86.zip
on a 32bit VM I get an error
"The specified executable is not a valid application for this OS platform."

### Steps to Reproduce

1. download ImageMagick-7.0.8-24-portable-Q16-x86.zip on a 32bit system
2. extract ffmpeg.exe
3. run ffmpeg.exe from a command prompt
4. error message is printed
 

### System Configuration
IE11 windows 7 32bit windows VM from http://modern.IE

- ImageMagick version: 7.0.8-24
- Environment (Operating system, version and so on): Windows 7 32bit VM
- Additional information: I also checked with dependency walker and it says its 64bit
If you run it by double clicking you get a longer and more descriptive error. That error text cant be selected so I cant copy it easily.

**Comment by urban-warrior** [comment]
Until we can fix this in the distribution, replace the binary with a 32-bit release of ffmpeg for Windows readily located with your favorite search engine.

**Comment by dlemstra** [comment]
I think it might even be better to completely remove ffpmeg from the Windows distribution and let the user download/install it themselves.

**Comment by urban-warrior** [comment]
The general expectation of software is that you download it and it just works.  I suspect most people that download IM would not read the README that points to the ffmpeg download and just assume the image formats that ImageMagick delegates to ffmpeg doesn't work.  Could the install script have a checkbox for ffmpeg and have the install script download its @ install time?

**Comment by pmiess** [comment]
For this package there is no install script.
"Just copy to your host and run (no installer, no Windows registry entries)."

**Comment by dlemstra** [comment]
I will try to see if it is possible to download the ffmpeg binaries during the build and include that in the installer/portable downloads.

**Comment by dlemstra** [comment]
We have changed the build to download ffmpeg and it now includes a 32-bit version of ffmpeg in the 32-bit build. And the 64-bit build now includes a 64-bit version of ffmpeg.
