### ISSUE TITLE
2 make check errors

### ISSUE THREAD

**Issue by arpanbanerjee01** [ImageMagick/ImageMagick#1463]
### Prerequisites

- [ Y] I have written a descriptive issue title
- [ Y] I have verified that I am using the latest version of ImageMagick
- [Y ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

2 make check errors
### Steps to Reproduce

./configure
make
sudo make install 
make check
### System Configuration

Ubuntu
- ImageMagick version:ImageMagick-7.0.8-24
- Environment (Operating system, version and so on):Ubuntu 16.04 LTS
- Additional information: NA

Unable to run convert

**Comment by dlemstra** [comment]
And the actual error is?
