### ISSUE TITLE
Image dither effect changed from version ImageMagick 6.7.0-10 to ImageMagick 7.0.7-24

### ISSUE THREAD

**Issue by lumpchen** [ImageMagick/ImageMagick#1466]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Image dither effect changed from version ImageMagick 6.7.0-10 to ImageMagick 7.0.7-24

### Steps to Reproduce
Source image: 
![icono_telefono](https://user-images.githubusercontent.com/2239287/51971911-48c41000-24b5-11e9-92e5-75c8473f7a96.png)
Convert cmd: convert -quiet -dither FloydSteinberg -resample 96.0x96.0 -units PixelsPerInch -compress Group4 -monochrome -type Bilevel "C:\icono_Telefono.png" "C:\icono_Telefono.TIFF" 
ImageMagick 6.7.0-10 result:
[icono_Telefono.zip](https://github.com/ImageMagick/ImageMagick/files/2811864/icono_Telefono.zip)
 ImageMagick 7.0.7-24 result:
[icono_Telefono_707.zip](https://github.com/ImageMagick/ImageMagick/files/2811868/icono_Telefono_707.zip)

Also, run cmd "convert -quiet -threshold 50% -resample 96.0x96.0 -units PixelsPerInch -compress Group4 -monochrome -type Bilevel ..." has the same issue.

### System Configuration
Win10-64bit

- ImageMagick version:ImageMagick 6.7.0-10 to ImageMagick 7.0.7-24
- Environment win10-64bit
- Additional information:

**Comment by fmw42** [comment]
With Images with Alpha channels, for IM 7, you should add -channel rgb to avoid processing the alpha channel. So these two commands produce the same results. Also for correct syntax, read the input image after -quiet and before other settings and operators.

`convert -quiet img.png -threshold 50% -resample 96.0x96.0 -units PixelsPerInch -compress Group4 -monochrome -type Bilevel result6.png`



`magick -quiet img.png -channel rgb -threshold 50% -resample 96.0x96.0 -units PixelsPerInch -compress Group4 -monochrome -type Bilevel result7.png`



These two commands including the -channel rgb for IM 7 are closer, but have slightly different dithering brightnesses. So still an issue here.

convert -quiet img.png -dither FloydSteinberg -resample 96.0x96.0 -units PixelsPerInch -compress Group4 -monochrome -type Bilevel result6.png

![result6](https://user-images.githubusercontent.com/13458218/51999126-eea05c00-246e-11e9-9d0e-8b644fa80bc7.png)


magick -quiet img.png -channel rgb -dither FloydSteinberg -resample 96.0x96.0 -units PixelsPerInch -compress Group4 -monochrome -type Bilevel result7.png

![result7](https://user-images.githubusercontent.com/13458218/51999133-f233e300-246e-11e9-8caf-5d07a05ac6ec.png)

**Comment by dlemstra** [comment]
Can we close this issue @lumpchen?
