### ISSUE TITLE
OptimizeImageLayers adds white pixel to resulting .gif

### ISSUE THREAD

**Issue by Cyberboss** [ImageMagick/ImageMagick#1468]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

`OptimizeImageLayers()` adds a white pixel to top left corner of the end of the output `.gif`

Ref https://github.com/tgstation/IconDiffBot/issues/42

### Steps to Reproduce

I've only been able to identify one case where this happens.

We have a bot that analyzes our game's asset binaries for pull requests and creates GitHub checks for comparing sprite differences. The proprietary `.dmi` format also allows for animated sprites which the bot converts into `.gif`s for maintainer convenience. For simplicity in diagnosing this issue, I've extracted the input data into this zip:  [white_pixel_test.zip](https://github.com/ImageMagick/ImageMagick/files/2814165/white_pixel_test.zip)  

And here is the output:

![test](https://user-images.githubusercontent.com/8171642/52007817-51105100-249d-11e9-9052-8296990996e1.gif)

The bot uses [Magick.NET-Q16-AnyCPU v7.10.2](https://www.nuget.org/packages/Magick.NET-Q8-AnyCPU) (nuget links to GitHub) which, in turn, uses ImageMagick 7.0.8-25-beta. The high-level C# code builds the `.gif` with this snippet:

https://github.com/tgstation/IconDiffBot/blob/7f8c2118c5cb56d50b1d4aa1bec94388c0e4f4a3/IconDiffBot/Core/DiffGenerator.cs#L262-L314

Note that the input to the `MagickImage` constructor are streams of the raw `.png`s in the order I provided. `state.Rewind` is `true`, `state.LoopCount.HasValue` is `false`, and `state.LoopCount` evaluates to `[42.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]`. Hopefully, this is easily translated into the C++ code

One of these `.gif`s (for the input files provided) was created with a single white pixel in the top right where it should be transparent. This lingers for about 1 second at the end of the animation sequence. I traced the problem down to the call to `OptimizeImageLayers()`. Removing it gets rid of the pixel, but leaves undesirable artifacts in the output.

### System Configuration

- ImageMagick version: 7.0.8-25-beta
- Environment (Operating system, version and so on): Windows 10 Professional x64 and Linux (Docker, dotnet:2.1-aspnetcore-runtime -> debian:stretch-slim)

**Comment by dlemstra** [comment]
Could you open an issue in the MagickNET repo instead?
