### ISSUE TITLE
identify or convert report "attempt to set read-only property `Version'" error

### ISSUE THREAD

**Issue by shelvsky** [ImageMagick/ImageMagick#1469]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

when I use convert or identify to deal with this png image attached, there will be an error report which says:

identify: attempt to set read-only property `Version' @ error/property.c/SetImageProperty/4493

I don't quit understand what this is about and why is it

### Steps to Reproduce

identify -verbose <image file> or use convert as well, but it will succeed at the end anyway

### System Configuration

- ImageMagick version: 7.0.7-38
- Environment (Operating system, version and so on):centos 7.2
- Additional information:

![7](https://user-images.githubusercontent.com/3603525/52035914-9d739380-2566-11e9-8f61-b93bd1515dba.png)

**Comment by fmw42** [comment]
I can confirm this on IM 7.0.8.25 Q16 Mac OSX Sierra. But it does not happen with IM 6.9.10.25 Q16 Mac OSX Sierra.

**Comment by urban-warrior** [comment]
Version is a reserved property in ImageMagick.  We'll add a patch to instead use the PNG namespace, e.g. png:version.
