### ISSUE TITLE
Building ImageMagick from Source with HEIC enabled is still being skipped

### ISSUE THREAD

**Issue by kevinludlow** [ImageMagick/ImageMagick#1470]
I have been using various versions of ImageMagick for years and have never had a problem installing delegates before.  I have recently upgraded to the most recent version of ImageMagick with the hope of getting the HEIC delegate installed, but even when I run the configure script with HEIC enabled, the output is still reporting to me that it is NOT being enabled.  I'm not sure what else is supposed to be done in order to configuration to run properly.
 
I checked out the most recent version from the Git Repository and ran the configure script with the delegates enabled that I read were supposed to be turned on.

### Parameters Used

I used the following configure parameters:

`./configure --prefix=/usr/local --enable-shared --disable-openmp --with-modules=no --with-webp=yes --with-gslib=no --with-openjp2=yes --with-gvc=yes --with-fftw=yes --with-heic=yes`

### Config Output

The configuration script builds successfully, but you can clearly see below that the HEIC delegate is turned off despite recognizing that --with-heic is set to 'yes'

```
Delegate Library Configuration:
  BZLIB             --with-bzlib=yes		yes
  Autotrace         --with-autotrace=no		no
  DJVU              --with-djvu=yes		no
  DPS               --with-dps=yes		no
  FFTW              --with-fftw=yes		no
  FLIF              --with-flif=yes		no
  FlashPIX          --with-fpx=yes		no
  FontConfig        --with-fontconfig=yes	no
  FreeType          --with-freetype=yes		yes
  Ghostscript lib   --with-gslib=no		no
  Graphviz          --with-gvc=yes		no
  HEIC              --with-heic=yes             no
  JBIG              --with-jbig=yes		no
  JPEG v1           --with-jpeg=yes		yes
  LCMS              --with-lcms=yes		yes
  LQR               --with-lqr=yes		no
  LTDL              --with-ltdl=yes		no
  LZMA              --with-lzma=yes		yes
  Magick++          --with-magick-plus-plus=yes	yes
  OpenEXR           --with-openexr=yes		no
  OpenJP2           --with-openjp2=yes		no
  PANGO             --with-pango=yes		no
  PERL              --with-perl=no		no
  PNG               --with-png=yes		no
  RAQM              --with-raqm=yes		no
  RAW               --with-raw=yes 	   	no
  RSVG              --with-rsvg=no		no
  TIFF              --with-tiff=yes		yes
  WEBP              --with-webp=yes		no
  WMF               --with-wmf=yes		no
  X11               --with-x=			yes
  XML               --with-xml=yes		yes
  ZLIB              --with-zlib=yes		yes
  ZSTD              --with-zstd=yes		no
```
I have read some other issues in here with the same problem, but at least in those cases the configuration script seems to recognize that somebody is attempting to configure with HEIC enabled.

I am running an Amazon AWS box with CentOS.  I haven't found any specific documentation suggesting so, but are there additional libraries that need to be first installed before running the build script?

### /proc/version

Linux version 4.9.75-25.55.amzn1.x86_64 (mockbuild@gobi-build-64013) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Fri Jan 5 23:50:27 UTC 2018
`

### /etc/os-release

NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"`
`

### ImageMagick Version

Version: ImageMagick 7.0.8-24 Q16 x86_64 2019-01-30 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib freetype jpeg lcms lzma tiff x xml zlib

Any thoughts on this one?

**Comment by dlemstra** [comment]
Did you install `libde265` and `libheif`?

**Comment by kevinludlow** [comment]
Thanks for the quick response. 

As far as I know I DID install both of them.  It was a little disjointed finding the necessary libraries for CentOS and I couldn't get them to install from Yum and therefore built them.

I got libheif from here: https://github.com/strukturag/libheif.git

And I was able to find an RPM for libde265 (libde265-0.8-1.el7.nux.x86_64.rpm)

I'm definitely no sys admin, but can usually manage Linux configs and installations pretty well.  This one is really just not making sense.  I'm also a little surprised to find that there doesn't seem to be a Yum package for all of this?  Is there a reason the new IM isn't available through Yum?  ...or have I perhaps just missed it somehow?

**Comment by urban-warrior** [comment]
Check config.log.  Search for libheif in the log.  In that area will be the reason why the configure script failed to validate the libheif delegate library.  Fix the problem and rerun the configure script.  Now build and install ImageMagick.  You should have the HEIC feature enabled now.

**Comment by kevinludlow** [comment]
> Check config.log. Search for libheif in the log.

Thanks so much for that.  It's actually quite revealing.  Apparently it's unable to find the library in the search path.  I'm not entirely sure why it can't find it, but at least it's a good starting place for figuring this one out.  I still remain a little confused why it requires a build like this.  I've been installing ImageMagick for about 13 years now and have never had any kind of trouble with a delegate before, it's always been fairly straightforward.  This one seems to have a lot of independent technical obstacles that need to be first overcome.

I think this is the section from config.log that is relevant:

`Package raqm was not found in the pkg-config search path.
Perhaps you should add the directory containing `raqm.pc'
to the PKG_CONFIG_PATH environment variable
No package 'raqm' found
configure:31035: $? = 1
configure:31049: result: no
No package 'raqm' found
configure:31077: result:
configure:31325: result: -------------------------------------------------------------
configure:31329: checking for libgvc >= 2.9.0
configure:31336: $PKG_CONFIG --exists --print-errors "libgvc >= 2.9.0"
Package libgvc was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgvc.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libgvc' found
configure:31339: $? = 1
configure:31353: $PKG_CONFIG --exists --print-errors "libgvc >= 2.9.0"
Package libgvc was not found in the pkg-config search path.
Perhaps you should add the directory containing `libgvc.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libgvc' found
configure:31356: $? = 1
configure:31370: result: no
No package 'libgvc' found
configure:31398: result:
configure:31442: result: -------------------------------------------------------------
configure:31446: checking for libheif
configure:31453: $PKG_CONFIG --exists --print-errors "libheif"
Package libheif was not found in the pkg-config search path.
Perhaps you should add the directory containing `libheif.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libheif' found
configure:31456: $? = 1
configure:31470: $PKG_CONFIG --exists --print-errors "libheif"
Package libheif was not found in the pkg-config search path.
Perhaps you should add the directory containing `libheif.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libheif' found
configure:31473: $? = 1
configure:31487: result: no
No package 'libheif' found
configure:31515: result:
configure:31553: result: -------------------------------------------------------------
configure:31555: checking for JBIG
configure:31557: result:
configure:31561: checking jbig.h usability
configure:31561: gcc -std=gnu99 -std=gnu99 -c -I/usr/include/freetype2       -g -O2 -Wall -mtune=core-avx2 -fexceptions -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16   -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  conftest.c >&5
conftest.c:266:18: fatal error: jbig.h: No such file or directory
 #include <jbig.h>`

Although these path files might be relevant too; I haven't tried to debug the problem yet per the last suggestion:

`#define XML_DELEGATE 1
#define INCLUDE_PATH "/usr/local/include/ImageMagick-7/"
#define INCLUDEARCH_PATH "/usr/local/include/ImageMagick-7/"
#define LIBRARY_RELATIVE_PATH "ImageMagick-7.0.8"
#define EXECUTABLE_PATH "/usr/local/bin/"
#define LIBRARY_PATH "/usr/local/lib/ImageMagick-7.0.8/"
#define LIB_BIN_BASEDIRNAME "bin"
#define MODULES_BASEDIRNAME "modules"
#define CODER_DIRNAME "coders"
#define FILTER_DIRNAME "filters"
#define DOCUMENTATION_PATH "/usr/local/share/doc/ImageMagick-7/"
#define CONFIGURE_RELATIVE_PATH "ImageMagick-7"
#define CONFIGURE_PATH "/usr/local/etc/ImageMagick-7/"
#define SHARE_RELATIVE_PATH "ImageMagick-7"
#define SHARE_PATH "/usr/local/share/ImageMagick-7/"
#define SHAREARCH_BASEDIRNAME "config"`

**Comment by urban-warrior** [comment]
Did you set PKG_CONFIG_PATH to a path where libheif.pc resides?

**Comment by kevinludlow** [comment]
Thanks for the continued followup.  So short answer is YES, I did manage to get it to install when I properly set the path per your recommendation.  The longer answer is that it still doesn't seem to help imageMagick actually convert an HEIC file.

When I take a look at the install delegates now, HEIC is definitely one of the supported types that I have.  Here is what the delegates line looks like in the configuration:

`DELEGATES             bzlib mpeg freetype heic jpeg lcms lzma ps tiff x xml zlib`

So that's good.  But unfortunately when I try to convert an HEIC file that I have (standard image from my iPhone) over to a JPG, it tells me that I still don't have the supported codec.  The specific output is this:

`magick IMG_9995.HEIC out.jpg`
`magick: Unsupported feature: Unsupported codec `IMG_9995.HEIC' @ error/heic.c/IsHeifSuccess/125.`

Strangely enough though, if I start with a JPG file and attempt to convert it to an HEIC file, it will register a success through imageMagick, but the resulting filesize is 0 bytes, so it's clearly not really doing anything.  Still not sure why this one delegate is so difficult to get going.

Any other thoughts would be greatly appreciated.

**Comment by kevinludlow** [comment]
It's also worth noting that this person had the exact same problem: https://github.com/ImageMagick/ImageMagick/issues/1140

I followed the link to the libheif library found on that page (https://github.com/strukturag/libheif) and installed that specific library so that I could point the path to the libheif.pc file it creates.  Unfortunately I still wind up having the same problem (and incidentally, the same problem that person had too).

**Comment by urban-warrior** [comment]
Which problem?  Type

`convert -version`

is `heic` listed as a Delegate?  If not, check why in config.log, fix the problem and rebuild ImageMagick.  If its an Unsupported feature, post the problem to the libheic developers.  We did not write the libheic delegate library so we cannot help.

**Comment by eplt** [comment]
I have written a full step by step guide to get it working on Ubuntu 18.04.
https://medium.com/@eplt/5-minutes-to-install-imagemagick-with-heic-support-on-ubuntu-18-04-digitalocean-fe2d09dcef1

**Comment by urban-warrior** [comment]
@eplt, Change 

```
sudo apt-get install build-essential autoconf git-core
sudo apt-get build-dep imagemagick libde265 libheif
```
to
```
sudo apt-get install build-essential autoconf libtool git-core
sudo apt-get build-dep imagemagick libmagickcore-dev libde265 libheif
```
in your article to ensure all the relevant ImageMagick delegate libraries are included in the source build and that the unit tests will pass.

**Comment by eplt** [comment]
Updated accordingly. Thanks.

**Comment by meonkeys** [comment]
> It's also worth noting that this person had the exact same problem: #1140
> 
> I followed the link to the libheif library found on that page (https://github.com/strukturag/libheif) and installed that specific library so that I could point the path to the libheif.pc file it creates. Unfortunately I still wind up having the same problem (and incidentally, the same problem that person had too).

Check out https://github.com/strukturag/libheif/issues/90 . If you see `checking for libde265... no` when you `./configure` libheif, that's the issue. libheif will still compile (and imagemagick can use this and claims `heic` as a delegate), but it won't be able to decode a HEIC image file.

**Comment by manojcmenon** [comment]
> 
> 
> I have written a full step by step guide to get it working on Ubuntu 18.04.
> https://medium.com/@eplt/5-minutes-to-install-imagemagick-with-heic-support-on-ubuntu-18-04-digitalocean-fe2d09dcef1

@eplt Can you do the same for Amazon Linux 2 or any RedHat flavor?

**Comment by alexander-ronin** [comment]
As I see, HEIC also do not builded in on Windows version: https://github.com/Imagick/imagick/issues/314

**Comment by dlemstra** [comment]
The Windows binaries have support for reading HEIC. I suspect that you are using an old version.

**Comment by nerixim** [comment]
@eplt and anyone trying to build IM with HEIC on Amazon Linux 2, try this:
https://github.com/serverlesspub/imagemagick-aws-lambda-2/pull/26

It is for Lambda but uses Amazon Linux image so should work for your case.

**Comment by brandur** [comment]
Just in case it helps someone else, I had this exact issue and it turned out that it was because I needed `dav1d` installed as a dependency. From `config.log`:

```
configure:31871: $PKG_CONFIG --exists --print-errors "libheif >= 1.4.0"
Package dav1d was not found in the pkg-config search path.
Perhaps you should add the directory containing `dav1d.pc'
to the PKG_CONFIG_PATH environment variable
Package 'dav1d', required by 'libheif', not found
configure:31874: $? = 1
configure:31888: $PKG_CONFIG --exists --print-errors "libheif >= 1.4.0"
Package dav1d was not found in the pkg-config search path.
Perhaps you should add the directory containing `dav1d.pc'
to the PKG_CONFIG_PATH environment variable
Package 'dav1d', required by 'libheif', not found
configure:31891: $? = 1
configure:31905: result: no
Package 'dav1d', required by 'libheif', not found
```

As suggested here already, this information is only available in `config.log`. `./configure` skips HEIC support without explaining why, and you find the binary without it.

My fix was to install `libdav1d-dev`:

```
sudo apt-get install libdav1d-dev
```

**Comment by Kyogre** [comment]
```
 Perhaps you should add the directory containing libheif.pc' to the PKG_CONFIG_PATH environment variable No package 'libheif' found configure:31456: $? = 1 configure:31470: $PKG_CONFIG --exists --print-errors "libheif" Package libheif was not found in the pkg-config search path. Perhaps you should add the directory containing libheif.pc'
```

For RedOS 7.3 needed this packages:
`yum install perl gcc binutils glibc glibc-devel make libtool-ltdl-devel fftw3-devel djvulibre-devel libtool libheif libwebp libde265 libheif-devel libheif-tools libdav1d libdav1d-devel`
