### ISSUE TITLE
Supporting to ICC profile embeded BMP writing.

### ISSUE THREAD

**Issue by yoya** [ImageMagick/ImageMagick#1471]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Windows BMPv5 can include ICC profile.
I created a patch that makes "EMBEDED_PROFILE" writing possible with ImageMagick.

patch & detail description is here.
- https://github.com/ImageMagick/ImageMagick/pull/1467

### Steps to Reproduce

- GBR-lcms.icc : ICC Profile (RGB=>GBR color rotate)
- rose-GBR.bmp : BMPv5 file with ICC Profile

```
% convert rose: -profile GBR-lcms.icc rose-GBR.bmp
```

These files in [files.zip](https://github.com/ImageMagick/ImageMagick/files/2824391/files.zip)
(rose-GBR.bmp, GBR-lcms.icc)

ImageMagick-7.0.8-25 can't produce BMP file with ICC Profile.

### System Configuration

ImageMagick version: ImageMagick-7.0.8-25
Environment (Operating system, version and so on): macOS Mojave v10.14.3
Additional information:

**Comment by urban-warrior** [comment]
Thanks for the patch.  We will apply it manually, there are a few required mods to the patch.
