### ISSUE TITLE
Supporting to ICC profile embeded BMP reading.

### ISSUE THREAD

**Issue by yoya** [ImageMagick/ImageMagick#1475]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Windows BMPv5 format can include ICC profile.
I have created a patch that makes "EMBEDED_PROFILE" reading possible with ImageMagick.

patch is here.
- https://github.com/ImageMagick/ImageMagick/pull/1474

### Steps to Reproduce

- lcms2-sGBR.icc : ICC Profile (I've rotated RGB>GBR color tristimulus values in LCMS2 build-in sRGB profile)
- rose-GBR.bmp : BMPv5 file include ICC Profile

```
% convert rose: -profile lcms2-sGBR.icc rose-GBR.bmp # since ImageMagick-7.0.8-26
% identify -format "%[icc:*]" rose-GBR.bmp
icc:copyright=No copyright, use freely
icc:description=sRGB built-in
% convert rose-GBR.bmp GBR-getback.icc
```
These files in [files.zip](https://github.com/ImageMagick/ImageMagick/files/2845829/files.zip)
 (lcms2-sGBR.icc, rose-GBR.bmp)

### System Configuration

ImageMagick version: ImageMagick-7.0.8-26
Environment (Operating system, version and so on): macOS Mojave v10.14.3
Additional information:

**Comment by urban-warrior** [comment]
We committed your patch.  Thanks.
