### ISSUE TITLE
7.0.8-27 t/write.t fails

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1478]
```
$ perl t/write.t
[..]
Flexible Image Transport System ...
ReadImage FITS:output.fits: Exception 435: unable to open image 'output.fits': No such file or directory @ error/blob.c/OpenBlob/3485
not ok 6
[..]
$ find -name *.fits
./t/input.fits
./t/output-0.fits
./t/output-1.fits
./t/output-2.fits
$
```
I have not the failure in 7.0.8-26.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
I tried 7.0.8-27 with altered input.fits and the part of the commit relevant to write.t and it works. I had to remove montage.t change though, otherwise it would fail. I assume that montage.t change is related to another change, which will be in 7.0.8-28 as well. I think we can close now, in case of another issue I will let you know.

Thanks for the quick response!
