### ISSUE TITLE
HEIC images cannot be open in macOS

### ISSUE THREAD

**Issue by JakubOnderka** [ImageMagick/ImageMagick#1479]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Images converted from JPG to HEIC format cannot be open in Preview app.

### Steps to Reproduce
1. Download any JPG file
2. `convert test.jpg test.heic`
3. `identify test.heic`: `test.heic HEIC 1440x960 1440x960+0+0 8-bit YCbCr 0.020u 0:00.009`
3. `open test.heic`
4. Preview will write "File test.heic cannot be open"

### System Configuration

- ImageMagick version:
```
Version: ImageMagick 7.0.8-27 Q16 x86_64 2019-02-12 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP 
Delegates (built-in): bzlib freetype heic jng jp2 jpeg lcms ltdl lzma openexr png tiff webp xml zlib
```
- Environment (Operating system, version and so on): macOS 10.14.3 (18D109)

**Comment by urban-warrior** [comment]
ImageMagick utilizes the libheif delegate library to read and write HEIC images.  Post this issue to the libheif developers as only they can resolve this issue.  However, before you do, make sure you are using the latest release of the libheif library.

**Comment by JakubOnderka** [comment]
Closing, because images converted with latest Imagemagick from Homebrew HEIC images can be open with Preview without problem.

```
Version: ImageMagick 7.0.8-28 Q16 x86_64 2019-02-19 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP 
Delegates (built-in): bzlib freetype heic jng jp2 jpeg lcms ltdl lzma openexr png tiff webp xml zlib
```

**Comment by zhutq** [comment]
In case someone encounters this later:
If you are building ImageMagick yourself, do check the vision of libheif (possibly by ` magick -list format | grep HEIC`).
For me, a great portion of heic files produced by libheif 1.3.2 could not be opened by Preview. Upgrading to libheif 1.7.0 solved the issue. You may need to also build libheif yourself.
