### ISSUE TITLE
cmdline is not producing filenames correctly

### ISSUE THREAD

**Issue by KnicKnic** [ImageMagick/ImageMagick#1483]
### Description
When running the following commandline in my Webassembly compliation of ImageMagick I got wrong output names. 
@dlemstra stated
" I can also reproduce the issue on the command line without doing any wasm magick. It looks like we calculate an incorrect offset inside InterpretImageFilename so it is not related to 8 character file names."

### Steps to Reproduce
```
convert * -flatten -crop x20% +repage -quality 100 -scene 0 -set filename:mysize %t %[filename:mysize]-%d.jpeg
```

I tried to split a filename of abcdefghijklmn.jpg thinking this would generate abcdefghijklmn-0.jpg, abcdefghijklmn-1.jpg, ...
However I got file name abcdefgh0.jpg. This was unexpected for 2 reasons.
1. I did not abcdefghijklmn, but the shortened abcdefgh
2. I did not get '-'.

### System Configuration
repro url
https://knicknic.github.io/imagemagick/

- ImageMagick version: 7.0.8-5
- Environment (Operating system, version and so on): Windows 10 (17763.1.amd64fre.rs5_release.180914-1434), chrome 72.0.3626.109 (Official Build) (64-bit)
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and already have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by KnicKnic** [comment]
Thanks, updated https://knicknic.github.io/imagemagick/ & it has now been fixed.
The commit was https://github.com/ImageMagick/ImageMagick/tree/6c88e0ad4f2c754b0452ef65809a16bf925bf8e6
