### ISSUE TITLE
7.0.8-28 - PSD alpha channel detection not working

### ISSUE THREAD

**Issue by sfunm** [ImageMagick/ImageMagick#1485]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I try to detect if a given Photoshop .psd file has an alpha channel. For quite some time (until ImageMagick 7.0.2-10) 'identify -format "%[channels]" image.psd' and 'identify -format "%[r]" image.psd' did the trick.
Results where "srgba" and "DirectClass sRGB Alpha", respectively.

### Steps to Reproduce
identify -format "%[channels] image.psd
Expected result: srgba
Given result (7.0.8-25, 7.0.8-28): srgb
or
identify -format "%[r]" image.psd
Expected result: DirectClass sRGB Alpha
Given result (7.0.8-25, 7.0.8-28): DirectClass sRGB

Test image: [image.zip](https://github.com/ImageMagick/ImageMagick/files/2880569/image.zip)

### System Configuration
Works:
ImageMagick 7.0.2-0 Q16
ImageMagick 7.0.2-10 Q16
ImageMagick 7.0.8-9 Q16

Doesn't Work:
ImageMagick 7.0.8-25 Q16
ImageMagick 7.0.8-28 Q16

Tested on 
Windows 10
Mac OS 10.14.2
Mac OS 10.13.6
Debian Stretch
Gentoo

**Comment by mp-t** [comment]
Conversion of multi-layer PSD's with alpha channels is not working correctly as well.

This is a major road block. Please fix.

**Comment by dlemstra** [comment]
Just pushed a hack to enable the alpha channel when we cannot use the layer information to determine if we should enable the alpha channel in the merged image. In the next release image.psd will have an alpha channel.

And can you please open another issue @mp-t and explain in much more detail the problem that you are experiencing?

**Comment by fmw42** [comment]
Dirk, How are you going to handle the situation where the PSD file has both background transparency and an alpha channel or multiple alpha channels?  

Does it make sense to have a define to choose which to make the alpha channel in the output for PNG or TIFF?

**Comment by dlemstra** [comment]
This is a hack for when the image has no layer information. It picks the first "extra" channel as the alpha channel like it did earlier. Dont think we need a define for this situation.

**Comment by fmw42** [comment]
OK. But consider at least what you might want to do when there is both a background channel and and alpha channel.

**Comment by mp-t** [comment]
It's the same problem. Will test again with your fix.

**Comment by dlemstra** [comment]
I am not sure if this is the same issue @mp-t. This hack only works for images that have no layers.
