### ISSUE TITLE
Support pango alignment

### ISSUE THREAD

**Issue by johnnyshields** [ImageMagick/ImageMagick#1488]
Seems like there's no way to activate pango alignment from the CLI. There is the `-gravity` option but that doesn't work for "east" (it rotates the text).

Would propose to add `-define pango:align={left,center,right}`. Could also look at adding `-define pango:gravity`

Here's a patch from the internets:

```
--- coders/pango.c.orig	2015-10-27 19:45:50.079263256 +0100
+++ coders/pango.c	2015-10-27 19:46:33.672399568 +0100
@@ -320,6 +320,17 @@
   if ((align != PANGO_ALIGN_CENTER) &&
       (draw_info->direction == RightToLeftDirection))
     align=(PangoAlignment) (PANGO_ALIGN_LEFT+PANGO_ALIGN_RIGHT-align);
+  // start hack for TextPango.ofx
+  option=GetImageOption(image_info,"pango:align");
+  if (option != (const char *) NULL) {
+    if (LocaleCompare(option,"center") == 0)
+      align=PANGO_ALIGN_CENTER;
+    if (LocaleCompare(option,"left") == 0)
+      align=PANGO_ALIGN_LEFT;
+    if (LocaleCompare(option,"right") == 0)
+      align=PANGO_ALIGN_RIGHT;
+  }
+  // end hack
   pango_layout_set_alignment(layout,align);
   if (draw_info->font == (char *) NULL)
     description=pango_font_description_new();
```

**Comment by rodlie** [comment]
Just wanted to note that I'm the original author of that patch, feel free to re-use.

**Comment by fmw42** [comment]
I believe it can be done directly in the Pango Markup Language. See https://developer.gnome.org/pango/stable/PangoMarkupFormat.html

**Comment by johnnyshields** [comment]
@fmw42 it cannot be done in pango markup--from what I can see there is no "align" option. I experimented with the various "gravity" options but they don't do what I want, which is simple text alignment.

@rodlie thank you for this patch. could you raise it as a PR?

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by johnnyshields** [comment]
wow, you guys are awesome! any chance of getting a backport on this to 6.x branch?

**Comment by johnnyshields** [comment]
oh, it's already on imagemagick 6. great!

**Comment by danielpetri1** [comment]
This does not seem to be supported anymore:

`convert -background '#CCCCCC' -define pango:align=right pango:'line number one\nno. 2 😀' align-right.png` produces a left-aligned image.

![](sftp://dpetri@develop.distancelearning.cloud:22/home/dpetri/align-right.png)

**Comment by sergeevabc** [comment]
Right, but what about vertical alignment? In case of `label:` it is enough to set `-gravity center`, but with `pango:` it centers horizontally only. IM v.7.1.1-21.
