### ISSUE TITLE
PDF from Stdin fails in 7.x

### ISSUE THREAD

**Issue by kilroy42** [ImageMagick/ImageMagick#1491]
Stdin option "pdf:-" does not longer work in ImageMagick 7.x.

Ghostscript is called with two input files and one output file (and of course, there is only one input file).

**Command to test:**

`cat document.pdf | convert pdf:- png:- | less`

**Expected output:** 

`<PNG data>`

**Actual output:**

/undefinedfilename in (/tmp/magick-302037TLxacKuuAis)
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
Dictionary stack:
   --dict:967/1684(ro)(G)--   --dict:0/20(G)--   --dict:78/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 9.26: Unrecoverable error, exit code 1
convert: FailedToExecuteCommand 'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72'  '-sOutputFile=/tmp/magick-30203bG5K_1ukdJgg%d' '-f/tmp/magick-30203F9dIDoiWrEhR' '-f/tmp/magick-302037TLxacKuuAis'' (1) @ error/pdf.c/InvokePDFDelegate/290.
convert: no images defined png:-' @ error/convert.c/ConvertImageCommand/3300.

**Environment**

Tested under: Ubuntu, Gentoo
Versions tested:
 - Unaffected: 6.9.7-4 (Ubuntu), 6.9.10.27 (Gentoo)
 - Affected: 7.0.8.25, 7.0.8.27, 7.0.8.28

**Comment by kilroy42** [comment]
Alpine Linux 3.9, Imagemagick 7.0.8.23-r0 is also affected (tested in Docker container for easy reproducibility)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by kilroy42** [comment]
Thanks for the very fast response and patch. Already integrated it into our packages and it works flawlessly!

**Comment by ricardodeazambuja** [comment]
Curiously, I am just trying to convert a pdf into a jpg:
`magick input.pdf output.jpg`

And I am having the same problem as above:

```
Error: /undefinedfilename in (/tmp/magick-NXByWMbRJeRQxTXIIN9WwOK37SoGk2fK)
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
Dictionary stack:
   --dict:774/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 10.00.0: Unrecoverable error, exit code 1
magick: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72' -dPrinted=false  '-sOutputFile=/tmp/magick-fFNu6cLSf6dAEQH3vcB0m76RKQqTMcdL%d' '-f/tmp/magick-NXByWMbRJeRQxTXIIN9WwOK37SoGk2fK' '-f/tmp/magick-kbr9-svxDEft8gehFXjQJbTYZ7Tl3noL'' (256) @ error/ghostscript-private.h/ExecuteGhostscriptCommand/74.
```

But I am using the latest version of ImageMagick (I just downloaded it):
```
Version: ImageMagick 7.1.0-57 Q16-HDRI x86_64 d68553b17:20221230 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(3.1) 
Delegates (built-in): bzlib djvu fontconfig freetype jbig jng jpeg lcms lqr lzma openexr png raqm tiff webp x xml zlib
Compiler: gcc (4.2)
```

However, I also get the same error with the older version (`convert input.pdf output.jpg`):
```
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib
```

What did I do differently from when it used to work? I installed ghostscript 10 (`Ghostscript 10.0.0 snap for Linux x86 (64 bit)`) and it stopped working. Why did I install gs 10? Because the 9.50 was not able to deal with CIDFont and the output had no text.

I hope these details can help somehow.

**Comment by fmw42** [comment]
Looks to me like either a problem with your version of Ghostscript or your PDF file.  Can you post your PDF?

**Comment by fmw42** [comment]
try

`magick image.pdf image.jpg`

**Comment by ricardodeazambuja** [comment]
I just created this pdf: [PDF from Stdin fails in 7.x · Issue #1491 · ImageMagick_ImageMagick.pdf](https://github.com/ImageMagick/ImageMagick/files/10366830/PDF.from.Stdin.fails.in.7.x.Issue.1491.ImageMagick_ImageMagick.pdf)
Then I ran `magick 'PDF from Stdin fails in 7.x · Issue #1491 · ImageMagick_ImageMagick.pdf' test.png` and the output was:
```
Error: /undefinedfilename in (/tmp/magick-X5YJXyAMFBMEOKF3V_tQe1MZbrbsIQ1Y)
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
Dictionary stack:
   --dict:774/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 10.00.0: Unrecoverable error, exit code 1
magick: FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72' -dPrinted=false  '-sOutputFile=/tmp/magick-aAmV4QJtE5nD8J3gABoukIzX0TlWKNA0%d' '-f/tmp/magick-X5YJXyAMFBMEOKF3V_tQe1MZbrbsIQ1Y' '-f/tmp/magick-usW3mBHCnxlk1rCn2H7rrBFA052T3I90'' (256) @ error/ghostscript-private.h/ExecuteGhostscriptCommand/74.
```
Using the same versions as my first message here.
Why does it passes two input files to ghostscript? Is that how it was supposed to be?

**Comment by ricardodeazambuja** [comment]
Ok, so it must be something with  Ghostscript 10.0.0. Thanks!

**Comment by fmw42** [comment]
Try downgrading to GS 9.5.6

**Comment by ricardodeazambuja** [comment]
Yes, this version works perfectly! So, there's (or there'll be) a problem when GS 10.0.0 becomes mainstream. Thanks again!
