### ISSUE TITLE
HEIC convert under rpm installation

### ISSUE THREAD

**Issue by whisere** [ImageMagick/ImageMagick#1493]
I have installed the latest ImageMagick via rpm under redhat 7 here:
https://imagemagick.org/script/download.php#unix
but when I tried to convert heic file to jpg, reported:
convert: no decode delegate for this image format `HEIC' @ error/constitute.c/ReadImage/556.

I have installed libde265 and libheif

but when I run identify --version, it says:
Version: ImageMagick 7.0.8-29 Q16 x86_64 2019-03-01 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): bzlib djvu fontconfig freetype jng jpeg lzma openexr pangocairo png tiff wmf x xml zlib

How can we enable heif? Can it be included in the rpm? Thank you.

**Comment by urban-warrior** [comment]
HEIC is not enabled for the CentOS 7 RPM binary builds.  Instead, build ImageMagick from the SRPM source distribution.  It will detect libheif on your system and include it as a supported format.

**Comment by whisere** [comment]
Thanks @urban-warrior I followed this instruction to build from source:
https://www.tecmint.com/install-imagemagick-in-linux/
But after installation, there was no change.
I tried ./configure --with-heic=yes
But the output: HEIC              --with-heic=yes             no
Any idea? Thanks!

**Comment by whisere** [comment]
also checked libraries:
Package libheif-1.3.2-2.el7.x86_64 already installed and latest version
Package libde265-1.0.2-6.el7.x86_64 already installed and latest version

**Comment by urban-warrior** [comment]
Did you install the devel RPM's?  ImageMagick must find the delegate header files before it can validate the delegate.  If you continue to have problems, inspect config.log.  It will tell you precisely why the libheif failed to validate.

**Comment by whisere** [comment]
Thank you very much for the tip @urban-warrior ! I did  sudo yum install libheif-devel
now it says HEIC              --with-heic=yes             yes
after ./configure --with-heic=yes.

**Comment by whisere** [comment]
all work now after make and make install!
