### ISSUE TITLE
Unable to run PHP Imagick from command line

### ISSUE THREAD

**Issue by georgewoofbates** [ImageMagick/ImageMagick#1494]
I'm running into a very frustrating problem when using Imagick in PHP.

Simple code:

```
$image = '1551660111_7801.jpg';
$imageBG = new Imagick();
$imageBG->readImage($image);
$imageBG->resizeImage('1280', '720', 1, 1, true);
$imageBG->writeImage ('test.jpg');
```

When I run this via Chrome, no issues, generates the new file.

But when I run through terminal like this

`php test.php`

I get this error

`Fatal error: Class 'Imagick' not found in ../test.php on line 8`

Using OSX, with MAMP.

**Comment by fmw42** [comment]
Have you tried using the full path to test.php?

**Comment by urban-warrior** [comment]
Unfortunately, we cannot reproduce the problem on our Linux systems.  The command-line returns expected results for us.  You likely need to activate the extension.  On our system, we have this .ini file:

```
; Enable imagick extension module
extension = imagick.so

; Documentation: http://php.net/imagick

; Don't check builtime and runtime versions of ImageMagick
imagick.skip_version_check=1

; Fixes a drawing bug with locales that use ',' as float separators.
;imagick.locale_fix=0

; Used to enable the image progress monitor.
;imagick.progress_monitor=0
```
