### ISSUE TITLE
Support for Canon's .CR3 RAW format

### ISSUE THREAD

**Issue by bobmoff** [ImageMagick/ImageMagick#1497]
I have no idea if this is feasible, but Lightroom, ON1 Photo Raw and macOS Preview and Finder has support for this format. Would be amazing if ImageMagick would too.

Description of the Canon Raw v3 (CR3) file format:
https://github.com/lclevy/canon_cr3

**Comment by urban-warrior** [comment]
ImageMagick delegates camera formats to the libraw delegate library.  Post your request to the libraw developers.  Once its supported in libraw, let us know and  we'll add some magick so ImageMagick can process CR3 images.

**Comment by tim-hilt** [comment]
Support was added to libraw.

**Comment by urban-warrior** [comment]
Thanks.  We'll add a commit to recognize the format in ImageMagick.
