### ISSUE TITLE
*FLAG 'sanitization' breaks some variants of user-provided flags

### ISSUE THREAD

**Issue by mgorny** [ImageMagick/ImageMagick#15]
The variable sanitization (https://github.com/ImageMagick/ImageMagick/blob/master/configure.ac#L3714) assumes it's sane to strip every 'duplicate' word in *FLAGS. This is wrong assumption, and can blow in user's face a lot. In particular, it breaks when:

* options with arguments are passed (`--param foo`),
* options can occur meaningfully multiple times (`-Wl,-Bstatic -lfoo -Wl,-Bdynamic`).

For example, my CFLAGS:

    CFLAGS="-march=k8-sse3 -mcx16 -msahf --param l1-cache-size=64 --param l1-cache-line-size=64 --param l2-cache-size=512 -O2 -pipe -frecord-gcc-switches"

turns into:

    CFLAGS="-march=k8-sse3 -mcx16 -msahf --param l1-cache-size=64 l1-cache-line-size=64 l2-cache-size=512 -O2 -pipe -frecord-gcc-switches"

which simply causes build failures. For some users (see the static/dynamic case above), it will instead cause silent deviations from requested build (i.e. wrong libs being linked statically).

**Comment by urban-warrior** [comment]
Thanks for alerting us to the problem.  Look for a fix within the hour.
