### ISSUE TITLE
Default density is different than the documented value

### ISSUE THREAD

**Issue by dessant** [ImageMagick/ImageMagick#151]
According to the docs, the default dpi value is 72, but i'm seeing 90 on Windows.
https://github.com/ImageMagick/ImageMagick/search?utf8=%E2%9C%93&q=72+dots+per+inch&type=Code

```python
import wand.image

svg_code = b"""<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="100px" height="100px" version="1.1"
     xmlns="http://www.w3.org/2000/svg">
    <rect x="0" y="0" width="10px" height="10px"/>
</svg>
"""

with wand.image.Image() as image:
    image.read(blob=svg_code)
    print(image.resolution)
```
Output
```python
(90, 90)
```

**Comment by mikayla-grace** [comment]
The default density is 72, except for SVG which is 90.  We'll make a note of it in the documentation.

**Comment by dessant** [comment]
@mikayla-grace, thanks for the update.
Fixed in https://github.com/ImageMagick/ImageMagick/commit/f650f4f6d51e47b73fe9363ac3c45777fda90d23.
