### ISSUE TITLE
displaying an HEIF file doesn't work

### ISSUE THREAD

**Issue by HJarausch** [ImageMagick/ImageMagick#1511]
I'm running ImageMagick (GIT) with libheif (GIT) here.
I can convert a TIFF image to an HEIC file and I can view the resulting file with GIMP.
BUT 'display"-ing this file gives nonsense (has nothing to do with the original image).

What am I missing?

Many thanks for a hint,
Helmut

**Comment by fmw42** [comment]
It would help the IM developers to know your IM version and platform.

**Comment by HJarausch** [comment]
As I said, ImageMagick is freshly compiled from the GIT sources from today.
My platform is Gentoo Linux.

**Comment by urban-warrior** [comment]
Can you post a reference image and the exact command-lines you are using?  We tried a few commands on our develop machines and we can write/read HEIC images without any problems.

**Comment by HJarausch** [comment]
Please download [https://nokiatech.github.io/heif/content/images/autumn_1440x960.heic](url)
and "display" that file.
On my machine it looks like
![autumn_1440x960_display](https://user-images.githubusercontent.com/3754462/54493648-a8924100-48d2-11e9-8e00-29df316bbfb9.png)

**Comment by urban-warrior** [comment]
Its in the YCbCr colorspace.  Try this command:

`display -colorspace sRGB autumn_1440x960.heic `

**Comment by HJarausch** [comment]
Many thanks, that looks fine. Is there a means to set the default to sRGB?

**Comment by urban-warrior** [comment]
Sure, add it to the command line:

`convert autumn_1440x960.heic -colorspace sRGB autumn_1440x960,png`

You can get better color transform control with  color profiles, something like this:

`convert autumn_1440x960.heic -profile myYCbCrprof.icc -profile sRGB.icc autumn_1440x960.png`
