### ISSUE TITLE
-quality does not work properly when converting PNG to HEIC

### ISSUE THREAD

**Issue by Provissy** [ImageMagick/ImageMagick#1512]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When `-quality` was set when using `convert` to convert PNG files to HEIC format, this setting seems not functioning properly. It works fine when converting from JPEG.

### Steps to Reproduce
Source PNG files' `identify` output:
`magick identify 01.png`
`01.png PNG 3455x4652 3455x4652+0+0 8-bit sRGB 22.7215MiB 0.000u 0:00.000`

Convert to heic using command:
`magick convert -quality 50 01.png 01.test.heic`
Identifying the output:
`magick identify 01.test.heic`
`01.test.heic PNG 3455x4652 3455x4652+0+0 8-bit sRGB 21.0195MiB 0.000u 0:00.000`

When quality was set to 20:
`01.20.heic PNG 3455x4652 3455x4652+0+0 8-bit sRGB 22.3369MiB 0.000u 0:00.000`
It seems that the output becomes even larger.

However in GIMP, the quality setting works fine when converting the same file using the Export As function.
[Screenshot of GIMP setting HEIC quality](https://user-images.githubusercontent.com/9506924/54530291-567a1a00-49bd-11e9-8ce5-6f7437295894.png)

When converting from JPEG, ImageMagick works perfectly fine:
`magick identify 01.test.jpg`
`01.test.jpg JPEG 3455x4652 3455x4652+0+0 8-bit sRGB 4.19222MiB 0.000u 0:00.000`

`magick convert -quality 50 01.test.jpg 01.test.jpg.heic`
`01.test.jpg.heic JPEG 3455x4652 3455x4652+0+0 8-bit sRGB 1.1596MiB 0.000u 0:00.000`

### System Configuration
Operating System: Windows 10 V1809, latest ImageMagick build, not tested in Linux distributions.
`Version: ImageMagick 7.0.8-33 Q16 x64 2019-03-10 http://www.imagemagick.org`

**Comment by Provissy** [comment]
It seems that when converting a specific file to HEIC, the source file format will be suited into the new HEIF/HEIC container but not encoding with HEVC.

`magick identify -verbose 01.heic`
```
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
```

**Comment by dlemstra** [comment]
The windows build does not support encoding the file to heic due to license issues. You are creating a PNG file because your input file is also png.

**Comment by Provissy** [comment]
Thanks a lot, could you please also add this note into wiki or the official website? Very appreciated.

**Comment by urban-warrior** [comment]
Type `convert -list format`.  It lists all the formats that are supported for that particular instance of ImageMagick.
