### ISSUE TITLE
Failed to handle transparency when convert svg to png in docker

### ISSUE THREAD

**Issue by Harold2017** [ImageMagick/ImageMagick#1516]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm using imagemagick in docker to convert svg to png. My svg file has a 
transparent background but output png with black background.

### Steps to Reproduce
Build docker with following dockerfile:
```
FROM python:3.6-slim
# Ignore APT warnings about not having a TTY
ENV DEBIAN_FRONTEND noninteractive
# Ensure UTF-8 locale
RUN echo "LANG=\"en_GB.UTF-8\"" > /etc/default/locale
# Install dependencies
RUN apt-get update && \
    apt-get install -y imagemagick \
    libmagickwand-dev \
    && apt-get clean autoclean \
	&& apt-get autoremove --yes \
	&& rm -rf /var/lib/{apt,dpkg,cache}/
RUN pip --no-cache-dir --disable-pip-version-check \
	install wand==0.5.1
```

I've tried:
`convert -background none in.svg out.png`
and 
`convert -background transparent in.svg out.png`

Both cmd works well on my host pc but failed with black background png in docker.

### System Configuration
- ImageMagick version: `ImageMagick 6.9.7-4 Q16 x86_64 20170114`
- Delegates (built-in): `bzlib djvu fftw fontconfig freetype jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib`
- Environment (Operating system, version and so on): `docker` with above dockerfile
- Additional information:

Many thanks.

**Comment by fmw42** [comment]
I am not a docker expert. But ImageMagick can use 3 different renderers for SVG: its internal MSVG/XML, the RSVG delegate or Inkscape. If Inkscape is on the system, current versions (by date - your is 1/14/2017) will use it automatically. It is the best. Next is RSVG and finally is MSVG/XML. You can find out from `convert -list format` and see which shows in the line for SVG. Docker is likely using just the MSVG/XML whereas your host pc may be using one of the others. You may want to install either Inkscape or RSVG delegate with ImageMagick in Docker. But that is beyond my capabilities. Perhaps one of the others on this forum may be able to help you further. This is a common issue from what I have seem on other forums with Docker vanilla installs.

**Comment by Harold2017** [comment]
@fmw42  many thanks! 
I got the following result when use `convert -list format`:
* on host PC: 
    ```bash
    SVG  SVG       rw+   Scalable Vector Graphics (XML 2.9.4)
    SVGZ  SVG       rw+   Compressed Scalable Vector Graphics (XML 2.9.4)
    PNG* PNG       rw-   Portable Network Graphics (libpng 1.6.28)
    ```
* on docker:
    ```bash
    SVG  SVG       rw+   Scalable Vector Graphics (XML 2.9.4)
    SVGZ  SVG       rw+   Compressed Scalable Vector Graphics (XML 2.9.4)
    PNG* PNG       rw-   Portable Network Graphics (libpng 1.6.34)
    ```
Both use XML.
I have Inkscape installed on my host but it seems imagemagick did NOT use it.
I have updated libpng in docker to `libpng 1.6.34` from `https://sourceforge.net/projects/libpng/files/libpng16/1.6.34/` but it did NOT solve the transparency problem.

**Comment by Harold2017** [comment]
@fmw42 I tried building Imagemagick with rsvg and it solved the problem. 
I write a gist: https://gist.github.com/Harold2017/5a53d940e49f3d7d87e126948b51b86e
> reference: https://imagemagick.org/script/install-source.php

**Comment by fmw42** [comment]
Do both your systems have the very same version of ImageMagick and date associated with it? If so, then I am at a loss to know why. I have never used Docker. Perhaps one of the IM developers might have some other ideas or questions.

**Comment by Harold2017** [comment]
@fmw42 , thanks for your response. 
Both my host and docker has the same version of ImageMagick and patch date but from different distributions (host: ubuntu, docker: debian). i do NOT have inkscape in docker, and i think this caused the different performance of SVG rendering. As for docker, i think RSVG is a good replacement.
Many thanks!

**Comment by Aleksi44** [comment]
Same issue here.
Just added inkscape in my Dockerfile :

```
apt-get install --yes --quiet inkscape
```

And it works ! Thanks @Harold2017
