### ISSUE TITLE
The previews of some png files are low res or chunky around the edges and have phantom image 

### ISSUE THREAD

**Issue by DigneshGoyal** [ImageMagick/ImageMagick#152]
Below is the command used
![a](https://cloud.githubusercontent.com/assets/12810106/13844990/24a08ede-ec63-11e5-8857-a78b44dea466.png)

convert.exe 01-Monster-8oz-Pthd.png -intent relative -sample 1024x768> -quality 95 -colorspace sRGB -strip -auto-orient 01-Monster-8oz-Pthd-S.jpg 

Please help me on this to use correct parameters to generate proper images.

Thanks

**Comment by glennrp** [comment]
Adding the "-flatten" option should help:

     convert.exe 01-Monster-8oz-Pthd.png -intent relative -sample 1024x768> -quality 95 -colorspace sRGB -strip -auto-orient -flatten 01-Monster-8oz-Pthd-S.jpg

This will compose the input image, which uses the alpha channel for antialiasing, against the background.

**Comment by DigneshGoyal** [comment]
Thank you so much ..Issue is resolved.

**Comment by DigneshGoyal** [comment]
Hi ..Is there a way to keep the background transparent on the png image when generating the previews?
These look much better but should emulate exactly what the image is .With the above setting I am getting a white background..can that be be made transparent.

Thanks,

**Comment by glennrp** [comment]
Omit "-flatten".

**Comment by DigneshGoyal** [comment]
![preview](https://cloud.githubusercontent.com/assets/12810106/15272416/7325dcc6-1a94-11e6-8ed7-9d64ff83eb22.jpg)

**Comment by DigneshGoyal** [comment]
Hi. I have removed "flatten" from the settings.and I have attached the screenshot of preview generated.
Looks like removing of flatten from the setting resulted in chunky around the edges and have phantom image.

Please advise further on how to resolve the issue.
Thanks,

Below is the version of ImageMagick I have used.

C:\Users\dgoyal>convert -version
Version: ImageMagick 6.9.2-7 Q16 x64 2015-11-28 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib cairo freetype jng jp2 jpeg lcms lqr openexr pangocairo png ps rsvg tiff webp xml zlib

**Comment by DigneshGoyal** [comment]
Can someone please advise on how it can be solved.

**Comment by njdoyle** [comment]
Use `-resize` instead of `-sample`. Not an ImageMagick bug.
This may help in the future: http://www.imagemagick.org/script/command-line-options.php

**Comment by DigneshGoyal** [comment]
![700affb418f609d522611d5f186100303f88ce24249d5655ea pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/12810106/15359081/53953260-1d25-11e6-9a33-506d6d77cfb2.jpg)


I have used -resize instead of -sample. It should emulate exactly what the image is .With the above setting I am getting a white background..can that be be made transparent.

**Comment by DigneshGoyal** [comment]
![prewi](https://cloud.githubusercontent.com/assets/12810106/15359163/b78af7a0-1d25-11e6-9ba0-fa84a4689855.jpg)

**Comment by njdoyle** [comment]
Not if you save it as a JPEG. Again, not an ImageMagick bug.

**Comment by DigneshGoyal** [comment]
Thank you very much  for helping me on this.
