### ISSUE TITLE
fopen_utf8 calls fopen instead of _wfopen when compiled with Mingw64

### ISSUE THREAD

**Issue by dubhater** [ImageMagick/ImageMagick#1526]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick (the latest version of fopen_utf8, anyway)
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

A user reported that it's not possible to open a png image if the file name contains Chinese characters:
```
Read: ImageMagick error: libimwri.dll: UnableToOpenBlob 'C:\Users\couga\Desk
top\æ±æ–¹Project\Team Shanghai Alice.png': No such file or directory @ erro
r/blob.c/OpenBlob/3094

« Note that "æ±æ–¹" above should have read instead "東方". »
```
This simple C code reveals that ``__MINGW32__`` is in fact defined:
```C
#if defined(__MINGW32__)

#error "mingw32"

#endif
```
when compiled with ``x86_64-w64-mingw32-gcc -o test.exe test.c``, and so fopen_utf8 calls fopen instead of _wfopen:
https://github.com/ImageMagick/ImageMagick/blob/57b308b170bb9e0ab184602bb1fed47bafe5a9d4/MagickCore/utility-private.h#L128-L132

### Steps to Reproduce

* Compile ImageMagick for Windows with GCC and Mingw64.
* Try to open a file with Chinese characters in its name.

### System Configuration

Build system: Arch Linux
Host system: some kind of Windows newer than XP.

- ImageMagick version: 7.0.7-25, but fopen_utf8 hasn't changed since then.
- GCC version: 7.3.0
- Mingw64 libraries version: 5.0.3

I use _wfopen in other software compiled in the same way, so it's definitely possible.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by kleisauke** [comment]
Could these differences be reverted?
https://github.com/ImageMagick/ImageMagick/commit/4a0a88e411bb88c2fb1618f40e529ddc8e497959#diff-e1f4947fd4a171647f1226e4e83d0a27R173
https://github.com/ImageMagick/ImageMagick6/commit/633d5a989eb384416431d0863ded22d71de37a72#diff-0f8074a1e49bc4123321b1e58de70ab5R161

Since it causes errors when building with Mingw-w64:
```
In file included from ../ImageMagick-6.9.10-35/magick/blob.c:72:
../ImageMagick-6.9.10-35/magick/utility-private.h:163:3: error: conflicting types for 'mode_t'
   mode_t;
   ^~~~~~
In file included from /data/mxe/usr/x86_64-w64-mingw32.shared/mingw/include/sys/stat.h:26,
                 from ../ImageMagick-6.9.10-35/magick/studio.h:65,
                 from ../ImageMagick-6.9.10-35/magick/blob.c:47:
/data/mxe/usr/x86_64-w64-mingw32.shared/mingw/include/sys/types.h:77:17: note: previous declaration of 'mode_t' was here
 typedef _mode_t mode_t;
                 ^~~~~~
Makefile:8931: recipe for target 'magick/libMagickCore_6_Q16_la-blob.lo' failed
make[3]: *** [magick/libMagickCore_6_Q16_la-blob.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
```

**Comment by MarcoMartins86** [comment]
I confirm that MinGW build is broken with the error mentioned above, although, the only thing that needs to be reverted is the removal of `&& !defined(__MINGW32__)` in the preprocessor comparison above the `typedef int mode_t;` . So, files with a unicode name will continue working when the build is made in MinGW.
