### ISSUE TITLE
how to add watermark with Magick++? 

### ISSUE THREAD

**Issue by shangjiuliu** [ImageMagick/ImageMagick#153]
how to add watermark with Magick++?

**Comment by dlemstra** [comment]
There are various ways of doing this. You can find the command line examples here: http://www.imagemagick.org/Usage/annotating/#watermarking

And here is a translation of one of the examples:
` composite -dissolve 25% -gravity south wmark_image.png   logo.jpg  wmark_dissolve.jpg`

```C++
Image watermark("wizard:");
watermark.resize("64x64");

Image logo("logo:");
logo.artifact("compose:args", "25%");
logo.composite(watermark, GravityType::SouthWestGravity, CompositeOperator::DissolveCompositeOp);
logo.write("logo.png");
```

**Comment by dlemstra** [comment]
Did this answer your question and can we close the issue?

**Comment by shangjiuliu** [comment]
Yes.
another question:
Image watermark("wmark_image.png");
how do i get the data of watermark?

i can do like this:
   Blob ret;
   watermark.write(&ret); 
   ret.data();
is there another way get the data of watermark?
