### ISSUE TITLE
potential null pointer de-reference bug

### ISSUE THREAD

**Issue by GoSSIP-SJTU** [ImageMagick/ImageMagick#1530]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In codes/png.c, the return value of png_malloc is used without null pointer check which can cause null pointer de-reference.

### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
When `png_malloc` fails it will call `png_error` and end up in our error handling method that will do a jump to exit the encoding or decoding. Can you clarify where we should add this check?

**Comment by dlemstra** [comment]
@GoSSIP-SJTU Can we close this?
