### ISSUE TITLE
ImageMagick on WSL creates empty folder pointing to Windows user directory AppData\Roaming

### ISSUE THREAD

**Issue by jpweytjens** [ImageMagick/ImageMagick#1535]
### Prerequisites

- [ x] I have written a descriptive issue title
- [ x] I have verified that I am using the latest version of ImageMagick
- [ x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Running any ImageMagick tool on WSL, in the WSL directory or the Windows directories, creates an empty folder `'C:\\Users\\user\\Appdata\\Roaming\\ImageMagick'`

I'm not sure if this is due to ImageMagick, or the Windows Subsystem for Linux (WSL). So far I haven't seen this with other linux tools, which leads me to believe it might be a related to ImageMagick.

### Steps to Reproduce
![im](https://user-images.githubusercontent.com/34494702/55542683-dbf11000-56c7-11e9-9b2e-8cb71a27e826.PNG)

### System Configuration

- ImageMagick version: 7.0.8.37-1
- Environment: Windows 10 version 1803, build 17134.590 and [ArchWSL](https://github.com/yuk7/ArchWSL) with kernel 4.4.0-17134-Microsoft
- Additional information: I've tried setting MAGICK_TMPDIR, but this had no effect.

**Comment by dlemstra** [comment]
Is it possible that you have an environment variable that is set to a Windows directory?

**Comment by jpweytjens** [comment]
Thanks for pointing me in the right direction. I have an environment variable `APPDATA` that links to `C:\Users\jweytjen\AppData\Roaming`. Changing this in WSL doesn't seem to affect the APPDATA variable in Windows. 

While this solves this problem, I don't understand what ImageMagick is doing with this variable? It's also unclear to me where or when this environment variable is set?

There is some documentation out there suggesting that you can share environment variables between Windows and WSL with `WSLENV` but that variable is not defined on my system. Running `grep` on my home and etc folder doesn't immediately show a process that could be setting `APPDATA` to point to a Windows folder.

**Comment by dlemstra** [comment]
We check those environment variables at a few places inside this project. One example is here: https://github.com/ImageMagick/ImageMagick/blob/252dd2c52bcc591ccd673abdbb70113b42388150/MagickCore/opencl.c#L300. But should probably only check `LOCALAPPDATA`, `APPDATA` and `USERPROFILE` on Windows.

Thanks for reporting this and I will push some changes to resolve this issue later this week/weekend.

**Comment by dlemstra** [comment]
The patch has been added and this will be resolved in the next release.
