### ISSUE TITLE
[7.0.8-37] testsuite failures on FreeBSD

### ISSUE THREAD

**Issue by kwm81** [ImageMagick/ImageMagick#1537]
Btw how do the test find fonts? I'm building with both fontconfig and freetype enabled and the test suite can't find the helvetica font. and I have several hiits for "Helvetica" when I run the fc-list command.

Btw the test fail with "analyze.la" is because I ran the test suite uninstalled, if I install it the error goes away..

=========================================
   ImageMagick 7.0.8: ./test-suite.log
=========================================

# TOTAL: 86
# PASS:  79
# SKIP:  0
# XFAIL: 0
# FAIL:  7
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/wandtest
====================

tests/wandtest.c main 5323 non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4407
1..1
Reading images...
Iterate forward...
index 0 scene 0
index 1 scene 1
index 2 scene 2
index 3 scene 3
index 4 scene 4
Iterate reverse...
index 4 scene 4
index 3 scene 3
index 2 scene 2
index 1 scene 1
index 0 scene 0
Remove scene 1...
index 0 scene 0
index 1 scene 2
index 2 scene 3
index 3 scene 4
Insert scene 1 back in sequence...
index 0 scene 0
index 1 scene 1
index 2 scene 2
index 3 scene 3
index 4 scene 4
Set scene 2 to scene 1...
index 0 scene 0
index 1 scene 1
index 2 scene 1
index 3 scene 3
index 4 scene 4
Apply image processing options...
not ok
FAIL: tests/wandtest.tap 1

FAIL: Magick++/tests/tests
==========================

1..13
ok
PASS: Magick++/tests/tests.tap 1
Testing throwing and catching exceptions. A program crash or a message
that the exception was not caught indicates a test failure.  A properly
formatted exception message indicates success:
Caught exception, good!:
  "attributes: unable to open image 'foo': No such file or directory @ error/blob.c/OpenBlob/3485"
ok
PASS: Magick++/tests/tests.tap 2
ok
PASS: Magick++/tests/tests.tap 3
ok
PASS: Magick++/tests/tests.tap 4
ok
PASS: Magick++/tests/tests.tap 5
ok
PASS: Magick++/tests/tests.tap 6
Histogram for file "/usr/home/kwm/sources/freebsd/ports/graphics/ImageMagick7/work/ImageMagick-7.0.8-37/Magick++/tests/test_image.miff"
10367 entries:
       125: (    0,    0,    0)
         9: (    0,    0,  257)
         4: (    0,    0,  514)
         1: (    0,    0, 1028)
         1: (    0,    0, 1285)

<snip>

         1: (65535,65535,60395)
         1: (65535,65535,61423)
         1: (65535,65535,62708)
         1: (65535,65535,62965)
         1: (65535,65535,63222)
ok
PASS: Magick++/tests/tests.tap 7
Checking for working exceptions (may crash) ... Throwing 'Magick::WarningResourceLimit' exception
Successfully caught 'Magick::WarningResourceLimit' exception
Throwing library 'Magick::Exception' exception
Successfully caught library 'Magick::Exception' exception
Exception testing passed!
ok
PASS: Magick++/tests/tests.tap 8
ok
PASS: Magick++/tests/tests.tap 9
Caught exception: tests: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1383
not ok
FAIL: Magick++/tests/tests.tap 10
ok
PASS: Magick++/tests/tests.tap 11
ok
PASS: Magick++/tests/tests.tap 12
ok
PASS: Magick++/tests/tests.tap 13

FAIL: Magick++/demo/demos
=========================

1..24
File: /usr/home/kwm/sources/freebsd/ports/graphics/ImageMagick7/work/ImageMagick-7.0.8-37/Magick++/demo//model.miff
analyze: unable to load module 'analyze.la': /usr/local/lib/ImageMagick-7.0.8//modules-Q16HDRI/filters/analyze.la @ error/module.c/InvokeDynamicImageFilter/984
ok
PASS: Magick++/demo/demos.tap 1
Caught exception: button: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1383
not ok
FAIL: Magick++/demo/demos.tap 2
Read images ...
Creating thumbnails...
  add noise ...
  add noise (blue) ...
  annotate ...
Caught exception: demo: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1383
not ok
FAIL: Magick++/demo/demos.tap 3
Writing image "flip_out.miff" ...
ok
PASS: Magick++/demo/demos.tap 4
angle 0
Caught exception: gravity: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1383
not ok
FAIL: Magick++/demo/demos.tap 5
Caught exception: piddle: non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4407
not ok
FAIL: Magick++/demo/demos.tap 6
Caught exception: shapes: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1383
not ok
FAIL: Magick++/demo/demos.tap 7
ok
PASS: Magick++/demo/demos.tap 8
ok
PASS: Magick++/demo/demos.tap 9
ok
PASS: Magick++/demo/demos.tap 10
ok
PASS: Magick++/demo/demos.tap 11
ok
PASS: Magick++/demo/demos.tap 12
ok
PASS: Magick++/demo/demos.tap 13
ok
PASS: Magick++/demo/demos.tap 14
ok
PASS: Magick++/demo/demos.tap 15
ok
PASS: Magick++/demo/demos.tap 16
ok
PASS: Magick++/demo/demos.tap 17
ok
PASS: Magick++/demo/demos.tap 18
ok
PASS: Magick++/demo/demos.tap 19
ok
PASS: Magick++/demo/demos.tap 20
ok
PASS: Magick++/demo/demos.tap 21
ok
PASS: Magick++/demo/demos.tap 22
ok
PASS: Magick++/demo/demos.tap 23
ok
PASS: Magick++/demo/demos.tap 24

**Comment by urban-warrior** [comment]
All the unit tests passed for us on FreeBSD 12.0.  We first installed the ImageMagick7 package (pkg install) which downloaded and installed all the ImageMagick dependencies.  New we configured and build ImageMagick from source.  Finally we ran the unit tests and they all passed without complaint.

**Comment by urban-warrior** [comment]
Forgot to mention, you'll also need the gsfonts package to expose the Helvetica font (e.g. pkg install gsfonts).

**Comment by kwm81** [comment]
With 7.0.8.39 and after installing gsfonts, all test pass.
Last question: do the test use gsfonts only or are the other parts of IM that use the fonts?

**Comment by jxu** [comment]
I had the same issue. On RHEL the package is ghostscript-fonts 

http://rpmfind.net/linux/rpm2html/search.php?query=ghostscript-fonts
