### ISSUE TITLE
ImageMagick can't read Photoshop color profile in PNG

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [ImageMagick/ImageMagick#154]
Example image: https://40.media.tumblr.com/3933e724978397af2fef38a176fac3e3/tumblr_o4odrcRrxd1qfb777o1_1280.png

Example reproduction:
1. Create image in Photoshop CC 2015.1.2 using profile Adobe RGB (1998)
2. Save for Web as PNG24 with "Embed color profile" and "Convert to sRGB" both checked
3. Run `magick image.png icc:profile.icc`
4. ImageMagick says there is no color profile, although `identify -verbose image.png` does note there is iCCP chunk (but does not list profile.

The profile can be successfully extracted by [exiftool](http://www.sno.phy.queensu.ca/~phil/exiftool/) and then used. And it is used by browsers. So I assume bug in ImageMagick.

Using `ImageMagick 7.0.0-0 Q16 x64 2016-03-20` HDRI on Windows 7 x64.

**Comment by glennrp** [comment]
It is being rejected by libpng16.

  Version: ImageMagick 6.9.0-0 Q16 x86_64 2014-12-16 http://www.imagemagick.org
q16identify: iCCP: known incorrect sRGB profile `tumblr_o4odrcRrxd1qfb777o1_1280.png' @ warning/png.c/MagickPNGWarningHandler/1671.

**Comment by AlyoshaVasilieva** [comment]
`identify -verbose image.png` shows no errors at all for me using 7 or `6.9.3-8 Q16 x64 2016-03-20`. I only receive an error when trying to extract a profile, with exact error being
```magick: no color profile is available `profile.icc' @ error/meta.c/WriteMETAImage/2356.``` It'd be nice for error message to be shown.

It seems that replacing Adobe RGB 1998 with sRGB v2 appears to result in identical colors, so I'll do this.

**Comment by glennrp** [comment]
You can skip the libpng profile-checking by running "convert" or "identify" with the
"-define png:preserve-iccp" option.

Your test PNG doesn't contain an Adobe RGB 1998 profile; it contains an old invalid (but popular) Microsoft/HP sRGB profile.
