### ISSUE TITLE
identify&convert of DPX file cause error

### ISSUE THREAD

**Issue by mtrepanier** [ImageMagick/ImageMagick#1551]
### Description
Using the latest version of ImageMagick cause the error `improper image header`
But using an older version, I have try a lots of them and found out that `7.0.7-28` will work but `7.0.7-29` and all newer version will fail.

Some DPX file will work, but some not

### Steps to Reproduce
Here's the failing DPX file: https://drive.google.com/file/d/1xPr3YgHd1oLuA99CZRa7XRFYn5kzfTbP/view?usp=sharing

`# identify will_fail.dpx`
`# identify: improper image header 'will_fail.dpx' @ error/dpx.c/ReadDPXImage/855.`

### System Configuration
- ImageMagick version:
- Environment (Operating system, version and so on): Centos7
- Additional information: compiled locally using docker

**Comment by fmw42** [comment]
Perhaps you should provide the command line that created it and the input image to the command line, so that the developers can try to reproduce your processing and result

**Comment by mtrepanier** [comment]
It's a DPX file coming from a client that we want to convert to a jpeg.  The DPX file is in the ticket information.

To reproduce, it's easy, use newest version of imagemagick and just run a simple `identify` on this file and you will get the error.  Then rollback to version `7.0.7-28` and you will see that it's passing.

I have try a lot of version and `7.0.7-28` seem to be the newest version that accept this file.

**Comment by dlemstra** [comment]
7.0.7-40 is the latest version, can you reproduce the issue with that version?

**Comment by mtrepanier** [comment]
Yes, all version after `7.0.7-28` I can reproduce it

**Comment by mtrepanier** [comment]
Well at least for `centos7`

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
