### ISSUE TITLE
ImageMagick -strip option fails to strip some ancillary PNG chunks

### ISSUE THREAD

**Issue by WinTakeAll** [ImageMagick/ImageMagick#156]
The `-strip` option appears to not strip PNG bKGD or cHRM chunks, though it does skip gAMA, tIME and tEXt. Not sure about the others. It is however possible to exclude them with options like `define png:include-chunk=none` or `define png:exclude-chunk=bkgd`. I'm seeing this in v6.9.3-7 (Windows x86 and x64, static, 16 bits-per-pixel component builds). 

[This comment by author Glenn R-P](http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=17729#p67041) implies it should avoid everything but gAMA. [This one](https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=29357#p131408) mentions cHRM.

If there's a change here, it'd be great if also the [currently terse documentation](http://imagemagick.org/script/command-line-options.php#strip) was expanded to specifically state what's included and not. Example: "_For PNG files the use of this option precludes all chunks defined as ancillary, which can be identified by their initial lowercase letter._"

**Comment by saoirse-ronan** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
@WinTakeAll Can we close this issue?
