### ISSUE TITLE
Cannot find "Set" equivalent to "MagickGetImagePixelColor"

### ISSUE THREAD

**Issue by karai17** [ImageMagick/ImageMagick#1566]
I am trying to expand a Lua binding for ImageMagick but I cannot locate any function that would be the `set` equivalent to `MagickGetImagePixelColor`. I have been looking through the code and documentation but I am not seeing anything that would help me. It also doesn't help that GitHub's search feature leaves a lot ot be desired..

![image](https://user-images.githubusercontent.com/590332/57174461-d0ebe580-6e15-11e9-9236-0b8e78bb9444.png)

![image](https://user-images.githubusercontent.com/590332/57174455-b7e33480-6e15-11e9-90ed-934271d55d9f.png)

My use case is that I am looping through all of the pixels in an image, comparing their values, and if they meet some threshold I want to set them to a new colour.

```lua
-- Example
for x=1, image:get_width() do
	for y=1, image:get_height() do
		local r, g, b = image:get_pixel(x, y)
		if r==0 and g==0 and b==0 then
			image:set_pixel(x, y, r, g, b, 0)
		end
	end
end
```

**Comment by urban-warrior** [comment]
Review the PixelWand methods @ https://imagemagick.org/api/pixel-wand.php.  PixelWand provides setters and getters for pixel color components.

**Comment by karai17** [comment]
Thanks for the response. It looks like `PixelSetPixelColor` might be what I am looking for. Is there any particular reason why there is no paired `MagickSetImagePixelColor` function?

**Comment by urban-warrior** [comment]
Likely an oversight.  We'll add it in the next point release of ImageMagick.

**Comment by karai17** [comment]
Cool, thank you. In the mean time I'll try to figure out how to use the pixel wand directly for my binding.

**Comment by karai17** [comment]
Does `PixelSetPixelColor` only set the colour of the wand, or does that push the pixel colour back to the image data? If only the former, how would I push the new colour to the image data?

**Comment by urban-warrior** [comment]
Use a pixel iterator to update pixel colors.  See https://imagemagick.org/source/contrast.c as an example or  review this snippet:

```
PixelWand
  **pixels;

  iterator=NewPixelIterator(magick_wand);
  if (iterator == (PixelIterator *) NULL)
    ThrowAPIException(magick_wand);
  pixels=PixelGetNextIteratorRow(iterator,&number_wands);
  for (i=0; pixels != (PixelWand **) NULL; i++)
  {
    (void) PixelSetColor(pixels[i],"#224466");
    (void) PixelSyncIterator(iterator);
    pixels=PixelGetNextIteratorRow(iterator,&number_wands);
  }
  (void) PixelSyncIterator(iterator);
  iterator=DestroyPixelIterator(iterator);

```

**Comment by narekyan** [comment]
but how to set color of the specific pixel, if I have only x, y and the color ?
@urban-warrior @karai17
