### ISSUE TITLE
 unable to resolve the issue...FAIL: tests/wandtest.tap 1 & FAIL: Magick++/demo/demos.tap 6

### ISSUE THREAD

**Issue by Skizorpc** [ImageMagick/ImageMagick#1569]
PASS: tests/validate-montage.tap 1
PASS: tests/validate-stream.tap 1
PASS: tests/drawtest.tap 1
FAIL: tests/wandtest.tap 1
PASS: Magick++/tests/tests.tap 1
PASS: Magick++/tests/tests.tap 2
PASS: Magick++/tests/tests.tap 3
PASS: Magick++/tests/tests.tap 4
PASS: Magick++/tests/tests.tap 5
PASS: Magick++/tests/tests.tap 6
PASS: Magick++/tests/tests.tap 7
PASS: Magick++/tests/tests.tap 8
PASS: Magick++/tests/tests.tap 9
PASS: Magick++/tests/tests.tap 10
PASS: Magick++/tests/tests.tap 11
PASS: Magick++/tests/tests.tap 12
PASS: Magick++/tests/tests.tap 13
PASS: Magick++/demo/demos.tap 1
PASS: Magick++/demo/demos.tap 2
PASS: Magick++/demo/demos.tap 3
PASS: Magick++/demo/demos.tap 4
PASS: Magick++/demo/demos.tap 5
FAIL: Magick++/demo/demos.tap 6
PASS: Magick++/demo/demos.tap 7
PASS: Magick++/demo/demos.tap 8
PASS: Magick++/demo/demos.tap 9
PASS: Magick++/demo/demos.tap 10
PASS: Magick++/demo/demos.tap 11
PASS: Magick++/demo/demos.tap 12

[FAIL:Magick++/demo/demos.tap 6]
[FAIL: tests/wandtest.tap 1]

Version: ImageMagick 7.0.8-44 Q16 x86_64 2019-05-11 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): fftw lzma x zlib

**Comment by urban-warrior** [comment]
Try the ImageMagck 7.0.8-45 release.  If the test still fails, locate the relevant failure in Magick++/demo/demos.log and post it here so we know which test failed and why.

**Comment by sivaselvik** [comment]
Hi  Skizorpc, have you found any solution? Even I face the similar issue. Couldn't identify the cause and solution.

**Comment by jafd** [comment]
The most likely cause for that particular test (wandtest) failing is that you don't have a font named "Helvetica" anywhere on your system, or that ImageMagick doesn't know how to find it.
