### ISSUE TITLE
Cosmetic issues in Information text during Windows setup

### ISSUE THREAD

**Issue by WinTakeAll** [ImageMagick/ImageMagick#157]
Getting an unrefined first impression by some typographic issues in the text "Welcome to ImageMagick!" shown after the license agreement when running Windows setup (ImageMagick-6.9.3-7-Q8-x64-dll.exe).

- There's an unexplained font change mid-sentence around the paragraphs about Ghostscript
- Headings and subheadings jump back-and forth between 3 different indentations
- There's a strange bullet character (a Unicode symbol for number 10 in inverse video in a circle) repeatedly in the list starting "Create a desktop icon". Just use the standard bullet (Alt+0149) on the numpad in Windows.

**Comment by dlemstra** [comment]
Thanks for reporting this. The installer uses the rtf files from this folder: https://github.com/ImageMagick/VisualMagick/tree/master/installer/txt. We can make the changes ourselves but feel free to send us a pull request to fix the documents. It also seems to be using some strange font. We should probably change this.

**Comment by WinTakeAll** [comment]
I have submitted a pull request for an edited version. Besides removing superfluous formatting (about 1/2 the file size), I made the text shorter and more readable. And I removed plenty of obsolete information related to Windows versions older than XP.

I also removed the statements about ActiveState Perl and how it needs to be installed before chosing the alleged ImageMagick installation option "Install PerlMagick for ActiveState Perl v5.8.4 build 811" because that option no longer exists and has been replaced with an option to install PerlMagick for Strawberry Perl.

However, I am not 100% sure about the status of ActiveState Perl support and if still supported what the installation instructions are, so I asked a [question on the forum](https://www.imagemagick.org/discourse-server/viewtopic.php?f=7&t=29367) and if gets answered it iis possible something about ActiveState needs to be re-added later.

**Comment by dlemstra** [comment]
Thanks for the patches :+1:. I will merge them later this week. We modified the document in the IM6 branch due to your question. Could you also update the document to mention 'Strawberry Perl' instead of 'AcitveState Perl' or did you already do that? We switched because it was easier to use in our appveyor build.

**Comment by dlemstra** [comment]
Your patches have been applied!
