### ISSUE TITLE
7.0.8-45 fails to configure on macOS

### ISSUE THREAD

**Issue by njdoyle** [ImageMagick/ImageMagick#1572]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When trying to build ImageMagick 7.0.8-45 on macOS (Mojave), `./configure` no longer works. This regressed from ImageMagick 7.0.8-44.

### Steps to Reproduce
Get latest source release of ImageMagick 7.0.8-45. Extract it and run:
```
./configure --prefix=/Users/nidoyle/Prefix
```
Problem may not depend on `--prefix` but that is how I build it. That prefix holds image dependency libraries, etc.

Excerpt of failure:
```
-------------------------------------------------------------
Update ImageMagick configuration
checking that generated files are newer than configure... done
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating common.shi
config.status: creating config/configure.xml
config.status: creating config/delegates.xml
config.status: creating config/ImageMagick.rdf
config.status: creating config/MagickCore.dox
config.status: creating config/MagickWand.dox
config.status: creating config/Magick++.dox
config.status: creating config/type-apple.xml
config.status: creating config/type-dejavu.xml
config.status: creating config/type-ghostscript.xml
config.status: creating config/type-urw-base35.xml
config.status: creating config/type-windows.xml
config.status: creating config/type.xml
config.status: creating ImageMagick.spec
config.status: creating Magick++/bin/Magick++-config
config.status: creating MagickCore/ImageMagick.pc
config.status: creating Magick++/lib/Magick++.pc
config.status: creating MagickCore/MagickCore-config
config.status: creating MagickCore/MagickCore.pc
config.status: creating MagickCore/version.h
config.status: creating Makefile
config.status: creating magick.sh
config.status: creating PerlMagick/check.sh
config.status: creating PerlMagick/default/Magick.pm
config.status: creating PerlMagick/Makefile.PL
config.status: creating PerlMagick/default/Makefile.PL
config.status: creating PerlMagick/quantum/Makefile.PL
config.status: creating PerlMagick/quantum/quantum.pm
config.status: creating PerlMagick/quantum/quantum.xs
config.status: creating PerlMagick/quantum/typemap
config.status: creating utilities/animate.1
config.status: creating utilities/compare.1
config.status: creating utilities/composite.1
config.status: creating utilities/conjure.1
config.status: creating utilities/convert.1
config.status: creating utilities/display.1
config.status: creating utilities/identify.1
config.status: creating utilities/ImageMagick.1
config.status: creating utilities/import.1
config.status: creating utilities/magick.1
config.status: creating utilities/magick-script.1
config.status: creating utilities/mogrify.1
config.status: creating utilities/montage.1
config.status: creating utilities/stream.1
config.status: creating MagickWand/MagickWand-config
config.status: creating MagickWand/MagickWand.pc
config.status: creating config/config.h
config.status: executing MagickCore/magick-baseconfig.h commands
config.status: creating MagickCore/magick-baseconfig.h - prefix MAGICKCORE for config/config.h defines
config.status: executing depfiles commands
config.status: error: in `/Users/nidoyle/Prefix/tmp/polite-1557944718-2483/install/imageMagick7/ImageMagick-7.0.8-45':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  Try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
```

### System Configuration

- ImageMagick version: `7.0.8-45`
- Environment (Operating system, version and so on): `macOS 10.14.4 (18E226) Mojave`
- Additional information: See attached [config.log](https://github.com/ImageMagick/ImageMagick/files/3184064/config.log)

**Comment by suishouen** [comment]
I also have the same issue on macOS High Sierra.
When I configure ImageMagick 7.0.8-45, configure fails and end up with the same error.

ProductName: Mac OS X
ProductVersion: 10.13.6
BuildVersion: 17G7024

**Comment by CyberCr33p** [comment]
Same issue with FreeBSD.

**Comment by urban-warrior** [comment]
We recently updated to the latest autoconf/automake configuration files and something broke. The culprit is likely in automake. Until there is patch, try this command to build ImageMagick under Mac OS X:

`./configure MKDIR_P="/bin/mkdir -p" --disable-dependency-tracking`

**Comment by suishouen** [comment]
Just a quick note:

I tried to build the latest ImageMagick-master (470655aa95fb3178ecca6b545f5e6a1654f0da85) with "MKDIR_P="/bin/mkdir -p" --disable-dependency-tracking".
The isuue seems to be fixed  tentatively.

Thanks a lot.

```
identify -version
Version: ImageMagick 7.0.8-46 Q16 x86_64 2019-05-17 https://imagemagick.org
```

**Comment by suishouen** [comment]
I tried to build the latest master: 7d05d64d4798afbd42c5e2f20560b7b7901f3eb8.
Now "MKDIR_P="/bin/mkdir -p" --disable-dependency-tracking" **seems not to be required**.

Can anyone confirm?

**Comment by urban-warrior** [comment]
We applied a patch to the autoconf configuration files and the IM build problem appears to be resolved.  Autoconf was pointing to a relative path, config/install-sh, rather than an absolute path.

**Comment by suishouen** [comment]
@urban-warrior:

Thanks.

**Comment by njdoyle** [comment]
ImageMagick 7.0.8-46 now configures and builds properly for me with no workarounds. Thank you!
