### ISSUE TITLE
Composite with multiple channels not returning as expected

### ISSUE THREAD

**Issue by trockefeller-pathway** [ImageMagick/ImageMagick#1575]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I made two test images to try to figure out what was happening with Magick.Net's Composite operation difference.

# Blocks

[![RGB Blocks][1]][1]

# Letters

[![Letters][2]][2]

# Difference on Red channel
Doing this command:
```csharp
blocks.Composite(letters, CompositeOperator.Difference, Channels.Red);
```
results in this

[![blocks difference with letters red channel][3]][3]

Which looks correct.
# Difference on Blue channel
Doing this command:
```csharp
blocks.Composite(letters, CompositeOperator.Difference, Channels.Blue);
```
results in this

[![blocks difference with letters blue channel][4]][4]

Which also looks correct.

# Difference on Red and Blue channels
I thought you could do a difference on multiple channels like this
```csharp
blocks.Composite(letters, CompositeOperator.Difference, Channels.Red & Channels.Blue);
```
But that command results in this

[![blocks difference with letters red and blue channels][5]][5]

Which looks incorrect, and just looks like the original Blocks image.

Am I misunderstanding how to use the Composite operation on multiple channels? Is this a bug in Magick.Net? For now it seems like the work around is to do the composite operation separate for each channel.

  [1]: https://i.stack.imgur.com/wNdq9.jpg
  [2]: https://i.stack.imgur.com/LbpF8.jpg
  [3]: https://i.stack.imgur.com/ovwsF.jpg
  [4]: https://i.stack.imgur.com/8pZQn.jpg
  [5]: https://i.stack.imgur.com/SCkVZ.jpg

### System Configuration

- ImageMagick version: Magick.NET-Q8-AnyCPU (7.13.0)
- Environment (Operating system, version and so on): Windows 10 Pro x64

**Comment by dlemstra** [comment]
Next time it will be better to open this issue in the correct project.

You should use a `|` instead of a `&`.

**Comment by trockefeller-pathway** [comment]
Cue face palm... I was so focused on needing the red channel *and* the blue channel that knowledge of the binary operators escaped me.

Thank you.

**Comment by dlemstra** [comment]
This never ever happend to me....
