### ISSUE TITLE
svg tspans draw on top of each other

### ISSUE THREAD

**Issue by MaikWagner** [ImageMagick/ImageMagick#1578]
While updating to ImageMagick 7.0.8-46 I realized that the tspan rendering problem from #1231 has resurfaced.

tspans are drawn overlapped again, using the example svg from #1231:
![text-bad](https://user-images.githubusercontent.com/7701966/58335019-f8483800-7e40-11e9-831c-6001a04400ec.png)

Earlier versions of IM and Browsers produced the correct result image:
![text](https://user-images.githubusercontent.com/7701966/58334701-6b04e380-7e40-11e9-82d8-2046c27e2bad.png)

If the following change from 3cbf950024aefa2720633b02434c9990b70c6892 is reverted, the test image is rendered properly again: 
```diff --git a/MagickCore/draw.c b/MagickCore/draw.c
index 6e4ee1a..4e2ed30 100644
--- a/MagickCore/draw.c
+++ b/MagickCore/draw.c
@@ -3676,7 +3676,7 @@ static MagickBooleanType RenderMVGContent(Image *image,
         if (LocaleCompare("text",keyword) == 0)
           {
             primitive_type=TextPrimitive;
-            cursor=0.0;
+        //    cursor=0.0;
             break;
           }
         if (LocaleCompare("text-align",keyword) == 0)```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
