### ISSUE TITLE
Don't add white background (bKGD) PNG chunk, and for indexed-color images, extra palette entry

### ISSUE THREAD

**Issue by WinTakeAll** [ImageMagick/ImageMagick#158]
When using ImageMagick **convert** to process paletted .png images without the color _white_ I noticed the following 3 related problems:

1. There was an unneeded _white_ color entry added to the palette
2. There was an unneeded PNG bKGD chunk added pointing to the white color index - misleading because that's not the image's actual background color
3. Worst: 1-, 2- or 4-bit paletted images using all entries (again without white) required the next larger bit depth on output (i.e. 2-, 4- or 8-bit), doubling the uncompressed size.

An example re point 3: Consider a pic like [basn3p01 from PngSuite](http://www.schaik.com/pngsuite/basn3p01.png) which uses only _yellow_ and _blue_ and is stored as a 1-bit (i.e. 2-color) paletted .png. Now run **convert -verbose basn3p01.png basn3p01_out.png** and you'll see that a **3c** output image is generated from the **2c** input, and it consequently grew to a 2-bit (i.e 4-color) paletted image.

Analogous for 4 unique colors with no white which becomes 5c and takes 4 instead of 2 bits per pixel, and for 16 colors which becomes 17c and takes 8 instead of 4 bits per pixel.

Workarounds for this include setting **-background** to a color that does exist in the image when there's no white (e.g. add **-background #EEFF22** for the yellow in the example above), or to use an option like **-define png:exclude-chunk=bkgd** to avoid adding the bKGD at all. (Noting that currently **-strip** doesn't work, reported here as [issue #156](https://github.com/ImageMagick/ImageMagick/issues/156).)

But why confuse users with the need for a workaround the 99% of the time they are not doing an operation that makes use of the background color?

In the case of true color images there is of course no palette to mess with but **convert** still adds the unnecessary bKGD chunk. Less harm but still some harm done.

I'd suggest the behavior is changed so that no bKGD chunk and/or extra palette entry is created at least unless the **-background** switch is used to specify one.

I'm noticing that this doesn't happen for BMP or TIF output. (No bKGD chunks there, but the extra _white_ palette entry isn't added for those formats.) I'm also noticing that the fork GraphicsMagic doesn't add this for PNG, even if **-background** is used.

Also noticing there's no mention of this in the [documentation for the -background option](http://www.imagemagick.org/script/command-line-options.php#background).

I'm seeing this in IM 6.9.3-7 on Windows x86/x64.

**Comment by mikayla-grace** [comment]
Add the -strip option to your convert command line.  Does that return expected results?

**Comment by dlemstra** [comment]
Can you respond to our question @WinTakeAll ?

**Comment by WinTakeAll** [comment]
@mikayla-grace, @dlemtra: I do get the expected results by adding the -strip option to the convert command line, so that is a viable workaround.

**Comment by WinTakeAll** [comment]
@mikayla-grace, @dlemstra: I do get the expected result with the -strip option added to the convert command line, so that is a viable workaround.
