### ISSUE TITLE
"-define dither:diffusion-amount" option for Floyd-Steinberg dither doesn't seem to  work

### ISSUE THREAD

**Issue by antoinebaudoux** [ImageMagick/ImageMagick#1584]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have tried several values for the "dither:diffusion-amount" option and it doesn't seem to affect the result image : 

```
convert -dither floyd-steinberg -define "dither:diffusion-amount=0%"   -posterize 16 image.bmp "image.random.0.bmp"
convert -dither floyd-steinberg -define "dither:diffusion-amount=10%"  -posterize 16 image.bmp "image.random.10.bmp"
convert -dither floyd-steinberg -define "dither:diffusion-amount=20%"  -posterize 16 image.bmp "image.random.20.bmp"
convert -dither floyd-steinberg -define "dither:diffusion-amount=30%"  -posterize 16 image.bmp "image.random.30.bmp"
convert -dither floyd-steinberg -define "dither:diffusion-amount=40%"  -posterize 16 image.bmp "image.random.40.bmp"
convert -dither floyd-steinberg -define "dither:diffusion-amount=50%"  -posterize 16 image.bmp "image.random.50.bmp"
convert -dither floyd-steinberg -define "dither:diffusion-amount=60%"  -posterize 16 image.bmp "image.random.60.bmp"
convert -dither floyd-steinberg -define "dither:diffusion-amount=70%"  -posterize 16 image.bmp "image.random.70.bmp"
convert -dither floyd-steinberg -define "dither:diffusion-amount=80%"  -posterize 16 image.bmp "image.random.80.bmp"
convert -dither floyd-steinberg -define "dither:diffusion-amount=90%"  -posterize 16 image.bmp "image.random.90.bmp"
convert -dither floyd-steinberg -define "dither:diffusion-amount=100%" -posterize 16 image.bmp "image.random.100.bmp"
```
where "image.bmp" is the following:

[image.bmp.zip](https://github.com/ImageMagick/ImageMagick/files/3244825/image.bmp.zip)

The resulting image always shows ugly gradients, the same regardless of the "dissfusion-amount" value:

<img width="507" alt="Screenshot 2019-06-02 at 14 57 25" src="https://user-images.githubusercontent.com/5154448/58761668-0421b180-8547-11e9-9e2d-e45df3eed787.png">

If I use ordered dithering, The gradient is smoother : 

```
convert -ordered-dither o8x8,16  -normalize +dither -posterize 16 "image.bmp" "image.ordered.bmp"

```

<img width="451" alt="Screenshot 2019-06-02 at 14 57 39" src="https://user-images.githubusercontent.com/5154448/58761676-1b609f00-8547-11e9-95e8-1adf5e4ee66b.png">

I was guessing that specifying a higher diffusion amount would lead to smoother gradients, am I missing something here?

Thanks for your feedback, 

Antoine

### Steps to Reproduce
Execute code above 
### System Configuration

- ImageMagick version: ImageMagick 7.0.8-47 Q16 x86_64 2019-05-30
- Environment (Operating system, version and so on):MacOs 10.14.4
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by antoinebaudoux** [comment]
Hello, 

This doesn't seem to be fixed in 7.0.8-68 : I have still issues specifying the diffusion amount when I use `-dither floyd-steinberg ` along with `-posterize 16`

Take this image, a simple grayscale gradient:

![gradient](https://user-images.githubusercontent.com/5154448/66571467-a09c3600-eb6f-11e9-83f6-f7949c5aedf3.png)

This command : 

`convert "gradient.png" -dither FloydSteinberg -define dither:diffusion-amount=100% -posterize 16  "gradient.floydsteinberg.png"`

produce the unexpected result : 

![gradient floydsteinberg](https://user-images.githubusercontent.com/5154448/66571577-d2ad9800-eb6f-11e9-975a-1dd0cb19e087.png)

**Comment by antoinebaudoux** [comment]
I should point out that it works perfectly well with `-colors` and but not with `-posterize`
Also, ordered dithering works as expected with `-posterize`

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by sergeevabc** [comment]
I have downloaded ```ImageMagick 7.0.9-17 Q16 x64 2020-01-19```,
run what @antoinebaudoux suggested [earlier][1] and got the same result,
yet something was obviously fixed according to the following comment,
so how the result should look like?

[1]: https://github.com/ImageMagick/ImageMagick/issues/1584#issuecomment-540570117
