### ISSUE TITLE
Feature request: Bokeh effect

### ISSUE THREAD

**Issue by jxu** [ImageMagick/ImageMagick#1587]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
https://en.wikipedia.org/wiki/Bokeh

How can this be implemented? IIRC this can be approximated with a convolution with a disk (or lens shaped polygon). 

Fred Weinhaus has implemented a version here http://www.fmwconcepts.com/imagemagick/bokeh/index.php 

To quote:
> - Computes n points equally spaced around a circle
> - Uses the points to draw a white on black polygon image
> - Converts the image into NetPBM textual PGM format
> - Edits the PGM data into Imagemagick convolution filter format
> - Convolves the filter with the thresholded image
> - Adds the new image to the original using -compose plus to form the output

**Comment by fmw42** [comment]
Conversion to any other code language requires licensing, if for commercial purposes. Contact me about your potential use.

**Comment by jxu** [comment]
My intent for this feature request was not to port your script to another language, but to implement the functionality internally, since specialized blurs already are implemented. 
To answer your questions this is more out of curiosity than anything. I do not have any commercial use.

**Comment by fmw42** [comment]
The code snippet in my script for computing the polygons is trivial math that can be done in any language. So one could simple write a module that computes the polygon as PGM and converts to imagemagick -morphology convolve text kernel format. PGM is easy to convert to that format. The rest is simple imagemagick convolution and composite that can be done in any in any ImageMagick API.  Alternately, ImageMagick could permit images to be used as kernels directly.
