### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by hburrows** [ImageMagick/ImageMagick#1590]
The https://imagemagick.org/ website is down (it's been like this for the past 8 hours).  This is not an issue with ImageMagick.  I don't know how else to communicate this so I figured I would create a GitHub issue especially since the URL is prominent in the README.md.

```
curl -i https://imagemagick.org/
curl: (7) Failed to connect to imagemagick.org port 443: Connection refused
```

**Comment by fmw42** [comment]
That and the discourse server are working fine again at this time.

**Comment by Djfe** [comment]
I also noticed that they were down, now they are back

**Comment by dlemstra** [comment]
Please don't create an issue when our website is down. GitHub issues are for issues with the code and not the website.

**Comment by Djfe** [comment]
Where else can we report can we report issues with the website then?

**Comment by dlemstra** [comment]
Maybe use twitter instead?

**Comment by hburrows** [comment]
@dlemstra After submitting this issue the idea of using Twitter occurred to me.  Next time.  Thanks to @fmw42  for quickly fixing this.

**Comment by fmw42** [comment]
I did not fix it. I just added the notification that it was fixed and back online, as I finally could get to it.

**Comment by lohit101** [comment]
Years later, the website is still not working...

**Comment by fmw42** [comment]
It is being worked on. Sorry.  Please be patient.

**Comment by jericodaag** [comment]
Is the server already up?

**Comment by fmw42** [comment]
It might be down for a while more as there was a power issue
