### ISSUE TITLE
convert: memory allocation failed @ error/tiff.c/ReadTIFFImage/1805.

### ISSUE THREAD

**Issue by jxu** [ImageMagick/ImageMagick#1591]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When converting a 1 GB TIFF image to jpeg, ImageMagick fails to allocate memory with the following error:

```
2019-06-13T17:12:05+00:00 35:44.510 316.000u 7.0.8 Exception convert[919]: tiff.c/ReadTIFFImage/1805/Exception
  memory allocation failed `rawdata/images/111249.svs'
2019-06-13T17:12:05+00:00 35:44.510 316.000u 7.0.8 Cache convert[919]: cache.c/DestroyPixelCache/1039/Cache
  destroy rawdata/images/111249.svs[0]
2019-06-13T17:12:05+00:00 35:44.511 316.000u 7.0.8 Resource convert[919]: resource.c/RelinquishMagickResource/1081/Resource
  File: 1/0/768
2019-06-13T17:12:05+00:00 35:44.511 316.000u 7.0.8 Resource convert[919]: resource.c/RelinquishUniqueFileResource/1119/Resource
  /app/work/mssm/tmp/magick-919zC3h6Lq9UptP
2019-06-13T17:14:40+00:00 38:19.093 328.540u 7.0.8 Resource convert[919]: resource.c/RelinquishMagickResource/1081/Resource
  Disk: 194.957GiB/0B/8EiB
2019-06-13T17:14:40+00:00 38:19.094 328.540u 7.0.8 Exception convert[919]: convert.c/ConvertImageCommand/3273/Exception
  no images defined `resize_images/111249.jpeg'
convert: memory allocation failed `rawdata/images/111249.svs' @ error/tiff.c/ReadTIFFImage/1805.
convert: no images defined `resize_images/111249.jpeg' @ error/convert.c/ConvertImageCommand/3273.
```

https://github.com/ImageMagick/ImageMagick/blob/ba347f6390140b4d5b478d12fa728ab8c1d94d66/coders/tiff.c#L1805 
shows cannot acquire enough memory. Is AcquireMagickMemory using entirely heap? 
I looked briefly through API https://imagemagick.org/api/memory.php and maybe AcquireVirtualMemory may work? 

### Steps to Reproduce
I can't post the image I have since it's confidential and way too large to post. 
But here is the output from identify: 

```
rawdata/images/111249.svs[0] TIFF 205176x85022 205176x85022+0+0 8-bit sRGB 1.03773GiB 0.010u 0:00.074
```

Here's what I use to run the convert:

```
magick convert -monitor -resize 20% -limit memory 32GB -limit map 32GB -debug All rawdata/images/111249.svs[0] resize_images/111249.jpeg
```

### System Configuration

- ImageMagick version: 

Version: ImageMagick 7.0.8-48 Q16 x86_64 2019-06-02 https://imagemagick.org                                                                                                                      Copyright: © 1999-2019 ImageMagick Studio LLC                                                                                                                                                    License: https://imagemagick.org/script/license.php                                                                                                                                              Features: Cipher DPC HDRI                                                                                                                                                                        Delegates (built-in): bzlib cairo fftw fontconfig freetype gvc jbig jng jp2 jpeg lzma pangocairo png rsvg tiff webp x xml zlib

- Environment (Operating system, version and so on):

Red Hat Enterprise Linux Server 7.6 (Maipo)

 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz

- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  AcquireVirtualMemory() is the likely resolution to this problem.  Look for a patch in the master branch within a day or two.

**Comment by jxu** [comment]
So my program got much farther than before, so I assume it got past acquiring memory. However I'll still have to use VIPS or OpenSlide since reading the image took 260 GB of disk and and WritePixelCachePixels's current rate will take a few days to run. And this is on an 18-core server with 64 GB RAM! The CPU usage maxes out at 10% and memory usage at 20%. I guess reading/writing to disk really is slow.

**Comment by swvanderlaan** [comment]
Hi,

I have a similar issue which I don't understand. We use `*.ndpi`-images. Below the output from `tiffinfo`.
