### ISSUE TITLE
PSD error - "abort trap 6: pointer being freed already on death row

### ISSUE THREAD

**Issue by ljw1004** [ImageMagick/ImageMagick#1594]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
There are some PSD files I created in photoshop which give "Abort trap: 6 - pointer being freed already on death-row" when I try to manipulate them in imagemagick.

### Steps to Reproduce
This file contains four PSD images "a.psd, b.psd, c.psd, d.psd" that I created in Photoshop: [images.zip](https://github.com/ImageMagick/ImageMagick/files/3294402/images.zip)
```
$ convert a.psd a.jpg
convert(33187,0x10e32b5c0) malloc: pointer 0x100bba000 being freed already on death-row
convert(33187,0x10e32b5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

$ convert b.psd b.jpg
convert(33226,0x116dd75c0) malloc: pointer 0x10d0a9000 being freed already on death-row
convert(33226,0x116dd75c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

$ convert c.psd c.jpg
convert(33241,0x110a635c0) malloc: pointer 0x10e819000 being freed already on death-row
convert(33241,0x110a635c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

$ convert d.psd d.jpg
[ works fine]
```
I included "d.psd" which works fine just as a point of comparison to show a similar that works fine - I created all four files in Photoshop in the same way.

Incidentally, `convert -resize 200x200 a.psd a.jpg` completes successfully without any error, for all of the images.

### System Configuration

- ImageMagick version:  7.0.8-49 Q16 x86_64 2019-06-13
- Environment (Operating system, version and so on): macOS 10.14.4 (18E226)

**Comment by fmw42** [comment]
Using IM 6.9.10.49 on MacOSX Sierra, conversion works fine as:

`convert a.psd[0] a.jpg`

Note the [0], which selects the first layer, which is the flattened layer.

But using IM 7.0.8.49, I get black images, but no error messages.

`magick a.psd[0] a.jpg`

Note in IM 7, use magick, not convert and not magick convert or you will get IM 6 type behavior.

Note your PSD files give me a message about missing fonts when open them in Photoshop CC. I have substituted fonts.

**Comment by fmw42** [comment]
I get no error message and the results appear successful on IM 7.0.10.28 Q16 Mac OSX with the following commands

`magick a.psd -resize 200x200 a.jpg`

etc on b,c and d

Please note that correct IM syntax reads the input before -resize; otherwise there could be problems. Also as I mentioned before, use magick rather than convert in IM 7 unless you have a symbolic link set up.
