### ISSUE TITLE
heap-buffer-overflow in MagickCore/fourier.c:277:19 in ComplexImages

### ISSUE THREAD

**Issue by SuhwanSong** [ImageMagick/ImageMagick#1596]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

There's a heap-buffer-overflow bug in MagickCore/fourier.c:277:19 in ComplexImages. This is maybe related with [#1595](https://github.com/ImageMagick/ImageMagick/issues/1595#issue-456713579)

### Steps to Reproduce

run_cmd:
`magick -seed 0 -fill rgb"("92,95,220")" -verbose "(" magick:granite -flip  ")" "(" magick:rose +repage ")" "(" magick:wizard +repage ")" -page 771x631+21+13 -red-primary 435,82  -blue-primary 875,773  -complex add   tmp`

also this can trigger same bug.
`magick -seed 0 -encoding AdobeStandard -virtual-pixel checker-tile -pointsize 66 "(" magick:logo +repage ")" "(" magick:rose +repage ")" "(" magick:rose -extent x210-67-95 -monochrome  ")" -depth 43 -blue-primary 592,304  -green-primary 37,595  -complex add -complex magnitude-phase -layers compare-overlay   tmp`

this one too.
`magick -seed 0 -antialias "(" magick:netscape -colors 79 -roll -79+10  ")" "(" magick:rose -flop -roll -88-60 -wave 79x61  ")" -gravity Center -alpha Deactivate -complex add -delete 2   tmp
`

Here's ASAN result.
```
==16498==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x624000017f00 at pc 0x7f376f7aa555 bp 0x7ffdb7263450 sp 0x7ffdb7263448
READ of size 4 at 0x624000017f00 thread T0
    #0 0x7f376f7aa554 in ComplexImages MagickCore/fourier.c:277:19
    #1 0x7f376efd18c1 in CLIListOperatorImages MagickWand/operation.c:3890:22
    #2 0x7f376efdd34e in CLIOption MagickWand/operation.c:5276:14
    #3 0x7f376ee1ea99 in ProcessCommandOptions MagickWand/magick-cli.c:477:7
    #4 0x7f376ee1fd0a in MagickImageCommand MagickWand/magick-cli.c:796:5
    #5 0x7f376ee69ba1 in MagickCommandGenesis MagickWand/mogrify.c:185:14
    #6 0x526f95 in MagickMain utilities/magick.c:149:10
    #7 0x5268e1 in main utilities/magick.c:180:10
    #8 0x7f37698e0b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #9 0x41b069 in _start (install/bin/magick+0x41b069)

0x624000017f00 is located 0 bytes to the right of 7680-byte region [0x624000016100,0x624000017f00)
allocated by thread T0 here:
    #0 0x4e6200 in __interceptor_posix_memalign (install/bin/magick+0x4e6200)
    #1 0x7f376f858666 in AcquireAlignedMemory MagickCore/memory.c:265:7
    #2 0x7f376f5afd5c in AcquireCacheNexusPixels MagickCore/cache.c:4968:37
    #3 0x7f376f59d1c4 in SetPixelCacheNexusPixels MagickCore/cache.c:5076:12
    #4 0x7f376f594b05 in GetVirtualPixelCacheNexus MagickCore/cache.c:2751:10
    #5 0x7f376f5b2f36 in GetCacheViewVirtualPixels MagickCore/cache-view.c:664:10
    #6 0x7f376f7a9e5d in ComplexImages MagickCore/fourier.c:250:8
    #7 0x7f376efd18c1 in CLIListOperatorImages MagickWand/operation.c:3890:22
    #8 0x7f376efdd34e in CLIOption MagickWand/operation.c:5276:14
    #9 0x7f376ee1ea99 in ProcessCommandOptions MagickWand/magick-cli.c:477:7
    #10 0x7f376ee1fd0a in MagickImageCommand MagickWand/magick-cli.c:796:5
    #11 0x7f376ee69ba1 in MagickCommandGenesis MagickWand/mogrify.c:185:14
    #12 0x526f95 in MagickMain utilities/magick.c:149:10
    #13 0x5268e1 in main utilities/magick.c:180:10
    #14 0x7f37698e0b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310

SUMMARY: AddressSanitizer: heap-buffer-overflow MagickCore/fourier.c:277:19 in ComplexImages

```

### System Configuration

- ImageMagick version:
Version: ImageMagick 7.0.8-50 Q16 x86_64 2019-06-17 https://imagemagick.org

- Environment (Operating system, version and so on):
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename: bionic

- Additional information:
CC=clang-7 CXX=clang++-7 ./configure --disable-openmp

**Comment by urban-warrior** [comment]
hanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
