### ISSUE TITLE
 convert:  NonconformingDrawingPrimitiveDefinition `polyline' @  error/draw.c/RenderMVGContent/4401

### ISSUE THREAD

**Issue by JugeshHM** [ImageMagick/ImageMagick#1598]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

With new version of ImageMagick (7.0.8-44) horizontal lines of graph(svg image) is only getting plotted. After few seconds graph is coming properly with proper x and y co-ordinates. In log I can see below error:
 convert: NonconformingDrawingPrimitiveDefinition `polyline' @ error/draw.c/RenderMVGContent/4401
It was working fine with 7.0.7-0 version

### System Configuration

- ImageMagick version: 7.0.8-44
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
Post a link to an example SVG image that throws the exception.  We need to download it an inspect it to track the source of the exception and prepare a proper resolution.

**Comment by fmw42** [comment]
Which SVG renderer are you using? There are 3: Imagemagick's MSVG/XML, RSVG delegate and Inkscape. Use -verbose in your command to see which is used. You do not show your command. What was it. Try installing Inkscape. ImageMagick will use that. It is probably the best of the 3 with RSVG second.
