### ISSUE TITLE
sendfile(2) used in MagickCore/cache.c is not portable.

### ISSUE THREAD

**Issue by kwm81** [ImageMagick/ImageMagick#16]
MagickCore/cache.c:502 uses sendfile(2).

On linux sendfile only takes 4 arguments, on FreeBSD it 7. 
The linux man page also states:
>Not specified in POSIX.1-2001, nor in other standards.
>
>Other UNIX systems implement sendfile() with different semantics and prototypes.  It should not be used in portable programs.

So it seems that either support both sendfile(2) implimentations or write portable replacement code.

This issue was found because of:
>MagickCore/cache.c:502:13: warning: implicit declaration of function 'sendfile' is invalid in C99 [-Wimplicit-function-declaration]
And after adding the headers required on FreeBSD for sendfile(2) the compile errored because of the different implimentations that resulted in this bug.

Linux sendfile(2) man page: http://man7.org/linux/man-pages/man2/sendfile.2.html
FreeBSD sendfile(2) man page: https://www.freebsd.org/cgi/man.cgi?query=sendfile&apropos=0&sektion=0&manpath=FreeBSD+10.1-RELEASE&arch=default&format=html

**Comment by kwm81** [comment]
Should mention that this is with IM 7, I haven't checked IM 6.

**Comment by urban-warrior** [comment]
Look for the ImageMagick 6.9.1-8 release later this week, sendfile() support has been removed.
