### ISSUE TITLE
Where did PreserveCorruptImage go?

### ISSUE THREAD

**Issue by MichaelLogutov** [ImageMagick/ImageMagick#160]
The latest version has removed PngReadDefines.PreserveCorruptImage property - why is that? I was using it to handle opening PNG images that has bad CRC but actually still can be viewed normally.

**Comment by MichaelLogutov** [comment]
Also, where did ResolutionX and ResolutionY go? Why such breaking changes increments only the minor version of the package?

**Comment by dlemstra** [comment]
I seems that you are talking about Magick.NET. Can you create an issue here: https://github.com/dlemstra/Magick.NET/issues? I will answer your question there.
