### ISSUE TITLE
memory error in imagemagick while using convert 

### ISSUE THREAD

**Issue by ajay-rexweb** [ImageMagick/ImageMagick#1605]
''' Python3 code running in os.system
convert -limit map 2000MB memory 2000MB \ -size $dims xc:none \ \( design_adjusted.png -alpha set -virtual-pixel transparent +distort Perspective "$coords" \) \-geometry +419+926 -compose Over -composite design_positioned.png
'''

Error: convert: Memory allocation failed `none' @ fatal/mogrify.c/MogrifyImage/1431.

Expected Result: the design_positioned should be made.
- ImageMagick version:
Version: ImageMagick 6.9.10-49 Q16 x86_64
Ubuntu 18.04

**Comment by urban-warrior** [comment]
Your Python environment may be severely memory constrained.  Its failing trying to allocate the coordinates for the distort option.  How many coordinates do you have in "$coords"?

**Comment by ajay-rexweb** [comment]
Thank you for your response. I'm done with the coords. But facing memory
allocation error for convert -size.
