### ISSUE TITLE
Picture's proportions are not kept

### ISSUE THREAD

**Issue by Ricky-Tigg** [ImageMagick/ImageMagick#1606]
Component:
```
$ dnf list installed | grep -i imagemagick
ImageMagick.x86_64      1:6.9.10.28-1.fc30       @fedora
```
Description of problem:  picture's proportions are not kept. Partial illustration:

![ImageMagick_1:6 9 10 28_proportions_not_kep](https://user-images.githubusercontent.com/26058215/59786058-0f0e6d00-92cf-11e9-882b-5fc92a69fc41.png)

Steps to reproduce in terminal:
```
# systemd-analyze plot > /home/$USER/systemd-analyze.svg
$ display systemd-analyze.svg
```

**Comment by urban-warrior** [comment]
Try these commands:
```
# sudo dnf install inkscape
# systemd-analyze plot > /home/$USER/systemd-analyze.svg
$ display systemd-analyze.svg
```
Do you get expected results now?

**Comment by Ricky-Tigg** [comment]
Once suggested package has been installed, wrong proportions are yet present in displayed picture.
```
$ rpm -qa --queryformat '%10{size} - %-25{name} \t %{version} \t %{os} \n' | awk '{print $1/1024/1024, $2, $3, $4}' | grep -i inkscape
152.12 - inkscape 0.92.4
```

**Comment by urban-warrior** [comment]
We are getting expected results, however, we are using ImageMagick 6.9.10-49, the current release.

**Comment by Ricky-Tigg** [comment]
Indeed an old build.
```
$ LANG=C rpm -qi ImageMagick
(...)
Architecture: x86_64
(...)
Source RPM  : ImageMagick-6.9.10.28-1.fc30.src.rpm
Build Date  : Mon Feb 18 18:20:23 2019
(...)
URL         : http://www.imagemagick.org/

$ LANG=C dnf info ImageMagick
Last metadata expiration check: 5:25:57 ago on Thu Jun 20 15:11:14 2019.
(...)
Architecture : x86_64
(...)
URL          : http://www.imagemagick.org/
```
As noticeable mentions present at _URL_-fields figure an insecure protocol – HTTP – while the page is presently served as _https://imagemagick.org/index.php_.
