### ISSUE TITLE
WritePCXImage() does not properly limit image->columns and image->rows

### ISSUE THREAD

**Issue by likemeng** [ImageMagick/ImageMagick#1607]
### Prerequisites

- [ y] I have written a descriptive issue title
- [ y] I have verified that I am using the latest version of ImageMagick
- [ y] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
in coders/pcx.c, WritePCXImage(const ImageInfo *image_info,Image *image,
  ExceptionInfo *exception) function trys to limit image->columns and image->rows in the right range (<=65535)in the code ,
https://github.com/ImageMagick/ImageMagick/blob/master/coders/pcx.c#L917 

but when  imageListLength=GetImageListLength(image); returns greater than 1,it means that imagelist has more than one image. the columns and rows of the image which is not the first image will not be checked any more.

**Comment by urban-warrior** [comment]
Refer to the per-image check @ https://github.com/ImageMagick/ImageMagick/blob/master/coders/pcx.c#L985.

**Comment by likemeng** [comment]
@urban-warrior ,image->rows is not checked,rigtht?

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
