### ISSUE TITLE
Multiple instances of use of uninitialised value

### ISSUE THREAD

**Issue by tysmith** [ImageMagick/ImageMagick#161]
To reproduce this behavior run the attached test cases with the follow command line:
valgrind -q ./magick convert bmp:test_case.bmp gif:-
or
valgrind -q ./convert bmp:test_case.bmp gif:-

I was able to reproduce this with ImageMagick-6.9.3-8 and revision 540ea6e8c064feb3e43621f5bcc9d3c43eeb0b41

[tests_and_logs.zip](https://github.com/ImageMagick/ImageMagick/files/200954/tests_and_logs.zip)

**Comment by saoirse-ronan** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by tysmith** [comment]
I came across a few more using the latest revision ff69ad37d27f8245ddf71da0b090e1bda0cfaa71

To reproduce this behavior run the attached test cases with the follow command line:
valgrind -q ./magick convert ico:test_case.bmp gif:-

[test_and_logs_2.zip](https://github.com/ImageMagick/ImageMagick/files/201761/test_and_logs_2.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by tysmith** [comment]
I came across more using the latest revision c6c70bb24e8ce03432af9d2149664c46895d17d9

To reproduce this behavior run the attached test cases with the follow command line:
valgrind -q ./magick convert ico:test_case.bmp gif:-

[test_case_3.zip](https://github.com/ImageMagick/ImageMagick/files/203418/test_case_3.zip)

**Comment by saoirse-ronan** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Can you still reproduce this issue @tysmith?
