### ISSUE TITLE
Use libraw instead of ufraw

### ISSUE THREAD

**Issue by linkyndy** [ImageMagick/ImageMagick#1617]
I am using Alpine Linux and `ufraw` is not available there. I am hence installing `libraw` and my understanding is it should work with `imagemagick`, however it doesn't. If I try to identify a CR2 image, I get:

```
$ identify /RAW_CANON_EOS_5DS.CR2
identify: delegate failed `'ufraw-batch' --silent --create-id=also --out-type=png --out-depth=16 '--output=%u.png' '%i'' @ error/delegate.c/InvokeDelegate/1867.
identify: unable to open image '/var/folders/t9/3qlk128n0tl29lrv08524kj40000gn/T/magick-49133I4b75F4Dvmhz.ppm': No such file or directory @ error/blob.c/OpenBlob/3497.
```

What am I missing and how I can get `imagemagick` work with RAW images on Alpine Linux? Thanks!

**Comment by urban-warrior** [comment]
If you install libraw development (header files are required), you must then build/install ImageMagick from source.  It will detect the delegate library when you run the `configure` script and leverage it to read your CR2 image.

**Comment by linkyndy** [comment]
Thanks for replying! Do I need to install imagemagick from source for that? Isn’t there any way I could use the Alpine imagemagick package as is, and then configure something?

**Comment by linkyndy** [comment]
I've also seen delegates...would that potentially help with swapping `ufraw-batch` with `libraw`?

**Comment by urban-warrior** [comment]
ufraw-batch is a delegate program, libraw a delegate library.  Delegate libraries are preferred and the delegate program is only consulted if the library is not available.  To include delegate library support, you must build ImageMagick from scratch.  You could bypass ImageMagick and convert your image with the dcraw program.

**Comment by linkyndy** [comment]
I understand. Thanks for your help!
