### ISSUE TITLE
heap-buffer-overflow at MagickCore/composite.c:666:45 in CompositeImage

### ISSUE THREAD

**Issue by SuhwanSong** [ImageMagick/ImageMagick#1618]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

There's a heap-buffer-overflow at MagickCore/composite.c:666:45 in CompositeImage.
It's related with [#1603](https://github.com/ImageMagick/ImageMagick/issues/1603)(Closed).

### Steps to Reproduce

run_cmd:
`magick -seed 0 "(" magick:netscape +repage ")" "(" magick:netscape -implode 33  ")" -comment "<��'" -region x924+9+2 -layers compare-overlay   tmp`

Here's ASAN log.
```
==7516==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x620000002e00 at pc 0x7ff7d516904d bp 0x7ffdcaa16330 sp 0x7ffdcaa16328
READ of size 4 at 0x620000002e00 thread T0
    #0 0x7ff7d516904c in CompositeImage MagickCore/composite.c:666:45
    #1 0x7ff7d539bde7 in CompareImagesLayers MagickCore/layer.c:808:12
    #2 0x7ff7d4b4839f in CLIListOperatorImages MagickWand/operation.c:4205:26
    #3 0x7ff7d4b5139e in CLIOption MagickWand/operation.c:5282:14
    #4 0x7ff7d4992a99 in ProcessCommandOptions MagickWand/magick-cli.c:477:7
    #5 0x7ff7d4993d0a in MagickImageCommand MagickWand/magick-cli.c:796:5
    #6 0x7ff7d49ddba1 in MagickCommandGenesis MagickWand/mogrify.c:185:14
    #7 0x526f95 in MagickMain utilities/magick.c:149:10
    #8 0x5268e1 in main utilities/magick.c:180:10
    #9 0x7ff7cf454b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310
    #10 0x41b069 in _start (install/bin/magick+0x41b069)

0x620000002e00 is located 0 bytes to the right of 3456-byte region [0x620000002080,0x620000002e00)
allocated by thread T0 here:
    #0 0x4e6200 in posix_memalign (install/bin/magick+0x4e6200)
    #1 0x7ff7d53cd116 in AcquireAlignedMemory MagickCore/memory.c:265:7
    #2 0x7ff7d5123f2c in AcquireCacheNexusPixels MagickCore/cache.c:4972:37
    #3 0x7ff7d5111264 in SetPixelCacheNexusPixels MagickCore/cache.c:5080:12
    #4 0x7ff7d5108ba5 in GetVirtualPixelCacheNexus MagickCore/cache.c:2753:10
    #5 0x7ff7d5127106 in GetCacheViewVirtualPixels MagickCore/cache-view.c:664:10
    #6 0x7ff7d5168d7e in CompositeImage MagickCore/composite.c:637:11
    #7 0x7ff7d539bde7 in CompareImagesLayers MagickCore/layer.c:808:12
    #8 0x7ff7d4b4839f in CLIListOperatorImages MagickWand/operation.c:4205:26
    #9 0x7ff7d4b5139e in CLIOption MagickWand/operation.c:5282:14
    #10 0x7ff7d4992a99 in ProcessCommandOptions MagickWand/magick-cli.c:477:7
    #11 0x7ff7d4993d0a in MagickImageCommand MagickWand/magick-cli.c:796:5
    #12 0x7ff7d49ddba1 in MagickCommandGenesis MagickWand/mogrify.c:185:14
    #13 0x526f95 in MagickMain utilities/magick.c:149:10
    #14 0x5268e1 in main utilities/magick.c:180:10
    #15 0x7ff7cf454b96 in __libc_start_main /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:310

SUMMARY: AddressSanitizer: heap-buffer-overflow MagickCore/composite.c:666:45 in CompositeImage

```

### System Configuration

- ImageMagick version:
Version: ImageMagick 7.0.8-51 Q16 x86_64 2019-06-27 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib fontconfig freetype jbig jng jpeg lzma openexr pangocairo png tiff webp x xml zlib

- Environment (Operating system, version and so on):
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename: bionic

- Additional information:
CC=clang-7 CXX=clang++-7 ./configure --disable-openmp

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
