### ISSUE TITLE
Issues with convert -type option: Does nothing for PNG, fails to force TrueColor for grayscale BMP

### ISSUE THREAD

**Issue by WinTakeAll** [ImageMagick/ImageMagick#162]
I'm finding issues with the **-type** command-line option documented [here](http://www.imagemagick.org/script/command-line-options.php#type). To test, from Willem van Schaik's [PngSuite](http://www.schaik.com/pngsuite/) I downloaded [`basn3p04.png` (4-bit paletted)](http://www.schaik.com/pngsuite/basn3p04.png) and [`basn0g04.png` (4-bit grayscale)](http://www.schaik.com/pngsuite/basn0g04.png). Then I tried the following commands using the ImageMagick 6.9.3-7 Q8 x64 (statically linked) build under Windows 7 64-bit:

1. `convert -verbose basn3p04.png basn3p04_default.png` generates a 16c paletted PNG from the 15c input. Ok, except that it added the color _white_, reported separately [here](https://github.com/ImageMagick/ImageMagick/issues/158).

2. `convert -type TrueColor -verbose basn3p04.png basn3p04_truecolor.png` generates the same paletted PNG as (1), not the TrueColor you'd expect.

3. `convert -verbose basn0g04.png basn0g04_default.png` generates a 4-bit grayscale PNG just like the input. All good.

4. `convert -type Palette -verbose basn0g04.png basn0g04_palette.png` generates the same grayscale PNG as (3), failing to force Palette.

5. `convert -type TrueColor -verbose basn0g04.png basn0g04_truecolor.png` again generates the same output as (3), failing to force TrueColor.

6. `convert -verbose basn3p04.png basn3p04_default.bmp` generates a 15c indexed color BMP. All good. (Note that for BMP no color _white_ is added which was a problem with PNG.)

7. `convert -type TrueColor -verbose basn3p04.png basn3p04_truecolor.bmp` generates a TrueColor BMP. Again all good.

8. `convert -verbose basn0g04.png basn0g04_default.bmp` also generates a TrueColor BMP though the input was 4-bit grayscale. Somewhat reasonable since there's no native grayscale BMP subformat, but a 4-bit palette would've been more efficient than 24-bit; there's only 16 grays.

9. `convert -type Palette -verbose basn0g04.png basn0g04_palette.bmp` still generates a TrueColor BMP from the 4-bit grayscale input, failing to force Palette.

Other formats:

The `-type` option behaves correctly for TIF and JPG. (There's no paletted JPG, but there is native grayscale and `-type TrueColor` can successfully be used to force that into truecolor, (which is the one example of `-type` use given in the documentation). I haven't tried formats other than PNG/BMP/TIF/JPG.

**Comment by glennrp** [comment]
For precise control of PNG output format you can use the PNG8, PNG24, PNG32, etc. subformats,
as in

    convert input.img png24:output.png

Or you can use "-define png:..." as in

    convert input.img -define png:bit-depth=8 -define png:color-type=6 RGBA.png

I suppose the docs could be expanded to recommend using these rather than -type with PNG outputs.

**Comment by marksteward** [comment]
Or maybe throw an error if passing -type truecolor and the input is png8.
