### ISSUE TITLE
Ralcgm is having issues with Windows server 2016 . Creating threads and causing the memory leakage. Any updates y it is not working for 2016. 

### ISSUE THREAD

**Issue by vishnubs53** [ImageMagick/ImageMagick#1625]
### Prerequisites

- [ ] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by fmw42** [comment]
I see no steps to reproduce nor a description of the issue! In fact there is no information presented at all.

**Comment by dlemstra** [comment]
We did no write or maintain ralcgm. You are asking this question in the wrong place.

**Comment by vishnubs53** [comment]
Issue is with CGM to PNG conversion.
I have tested the ralcgm.exe in the Windows Server 2016 and Windows server 2012 and 2008. 
Command " ralcgm -d PS -oC test.cgm test.jpg " .
In Windows 2008 and 2012 results are the same
