### ISSUE TITLE
RALCGM is not working in windows server 2016

### ISSUE THREAD

**Issue by vishnubs53** [ImageMagick/ImageMagick#1626]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Ralcgm is not converting the cgm files to png (occurs only on windows server 2016)

### Steps to Reproduce
Command " ralcgm -d PS -oC test.cgm test.jpg " . to be executed in ralcgm installed path
In Windows 2008 and 2012 results are the same
### System Configuration

Windows server 2016
64 bit os, X64 processor

- ImageMagick version:
tested with 6.9 and 7.0
Ralcgm : v3.5
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
Please do not create duplicate issues.
