### ISSUE TITLE
ImageMagick 6.9.3-7 on OS X 10.11.3 creates, but doesn't install, type-apple.xml

### ISSUE THREAD

**Issue by johnsonea** [ImageMagick/ImageMagick#163]
Building and installing ImageMagick 6.9.3-7 on OS X 10.11.3 creates config/type-apple.xml and references it in config/type.xml but does not install type-apple.xml into /usr/local/etc/ImageMagick-6 along with type.xml and others (it does install type-ghostscript.xml and others).  It doesn't seem to matter if ./configure is provided --with-apple-font-dir=/Library/Fonts or not.

**Comment by mikayla-grace** [comment]
type-apple.xml is only useful in select environments so we do not install it by default, but instead, leave it to the user to move it in-place and reference it from type.xml.

**Comment by johnsonea** [comment]
Not entirely accurate -- `configure` writes type.xml to include type-apple.xml based on the presence of `apple_font_dir`:

`if test "${apple_font_dir}x" != 'x'; then`
`type_include_files="${type_include_files} "'<include file="type-apple.xml" />'`

So it would seem logical to do the second half of this and install type-apple.xml

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Has this issue been resolved for you @johnsonea  and can we/you close this issue?
