### ISSUE TITLE
Error by reading "-draw" arguments from a MVG file (7.0.8-53)

### ISSUE THREAD

**Issue by m7b** [ImageMagick/ImageMagick#1631]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
An error occurs when passing an MVG file with @ as "-draw" argument:

> convert.exe: NonconformingDrawingPrimitiveDefinition `@' @ error/draw.c/RenderMVGContent/4396.

### Steps to Reproduce
Only trying the 1. example of http://www.imagemagick.org/Usage/draw/ under section "Reading MVG Files"

`V:\ImageMagick-7.0.8-53-portable-Q16-x86\convert.exe -verbose
-size 100x60 xc:skyblue
-draw @mvg_circles.mvg
mvg_draw.gif`

content of mvg_circles.mvg:
`fill green   circle 41,39 44,57`
`fill blue    circle 59,39 56,57`
`fill red     circle 50,21 50,3`

output:

> xc:skyblue=>skyblue XC 100x60 100x60+0+0 16-bit sRGB 0.000u 0:00.001
> xc:skyblue=>mvg_draw.gif XC 100x60 100x60+0+0 16-bit Palette sRGB 1c 126B 0.031u 0:00.045
> convert.exe: NonconformingDrawingPrimitiveDefinition `@' @ error/draw.c/RenderMVGContent/4396.

### System Configuration

- ImageMagick version: ImageMagick-7.0.8-53-portable-Q16-x86
- Environment (Operating system, version and so on): Win10
- Additional information: -

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
