### ISSUE TITLE
convert "-draw" text placement with gravity does not work as expected

### ISSUE THREAD

**Issue by m7b** [ImageMagick/ImageMagick#1633]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Placing text with gravity are not working anymore.

result:
![wrong_placement](https://user-images.githubusercontent.com/11319218/61109735-e6b8ff00-a485-11e9-811b-c9d9d530e780.png)

expected result, created with ImageMagick-7.0.7-22-portable-Q16-x86:
![expected](https://user-images.githubusercontent.com/11319218/61109736-e6b8ff00-a485-11e9-8739-1357fd20f32a.png)

### Steps to Reproduce

`convert.exe -size 220x130 canvas:lightblue -draw "gravity NorthWest text 0,0 'NW' gravity NorthEast text 0,0 'NE' gravity North text 0,0 'N' gravity South text 0,0 'S' " result.png
`

### System Configuration

- ImageMagick version: ImageMagick-7.0.8-53-portable-Q16-x86
- Environment (Operating system, version and so on): Win10
- Additional information:

**Comment by m7b** [comment]
Example with more gravity-options:

`
convert.exe -verbose -size 220x130 canvas:lightblue -draw "gravity NorthWest text 0,0 'NW' gravity North text 0,0 'N' gravity NorthEast text 0,0 'NE' gravity East text 0,0 'E' gravity Center text 0,0 'C' gravity West text 0,0 'W' gravity SouthWest text 0,0 'SW' gravity South text 0,0 'S' gravity SouthEast text 0,0 'SE'" result.png
`

expected:
![expected2](https://user-images.githubusercontent.com/11319218/61110722-31d41180-a488-11e9-83c3-f482fb093484.png)


actual:
![wrong_placement2](https://user-images.githubusercontent.com/11319218/61110685-17019d00-a488-11e9-9352-39aedaa275c5.png)

**Comment by fmw42** [comment]
You should use magick not convert on IM 7. But I can confirm the same bad result using IM 7.0.8.53 on OSX Sierra with:

`magick -size 220x130 canvas:lightblue -draw "gravity NorthWest text 0,0 'NW' gravity NorthEast text 0,0 'NE' gravity North text 0,0 'N' gravity South text 0,0 'S' " result.png`

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by m7b** [comment]
Today I tested version ImageMagick-7.0.8-54~beta20190714-portable-Q16-x86 @ [https://www.imagemagick.org/download/beta/](https://www.imagemagick.org/download/beta/) in this respect.
But it doesn't seem to have brought any improvement. Instead I don't see any text at all.  Only a light blue area. I think the case doesn't seem to be finished yet.
