### ISSUE TITLE
-background option not working alone

### ISSUE THREAD

**Issue by gauravano-cultgear** [ImageMagick/ImageMagick#1634]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I tried to change the background of a local image using `convert "input.png" -background "#4287f5" "output.png"`

It's creating a new file **output.png** but background of image is same. When I used background option with flatten like

`convert "output.png" -background "#4287f5" -flatten "output3.png"` It worked. It changed the background as well as flattened the file.

### System Configuration

- ImageMagick version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org

- Environment (Operating system, version and so on): Ubuntu 18.04

- Additional information: I originally tried performing this background change operation using mini_magick but that also failed and when I flattened the file there using `magick.flatten` that also worked out. Are they dependent?

**Comment by fmw42** [comment]
-background is a setting and by itself will do nothing. It needs an operator to act on the setting. If you want to change the background color, then you need to use -flatten or -fill newcolor -opaque old color. So your two commands are working as they should. -background probably should have been called -backgroundcolor to avoid confusion.

**Comment by gauravano-cultgear** [comment]
Hi @fmw42, thanks for clarifying and pointing to docs.
