### ISSUE TITLE
magick xc:black black.pnm creates a white image 

### ISSUE THREAD

**Issue by cjmayo** [ImageMagick/ImageMagick#1636]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Fix from #1632 resolved issue with:
`magick -size 100x100 xc:white white.pnm`
but broke:
`magick -size 100x100 xc:black black.pnm`
which now creates a white image.
### Steps to Reproduce

1) `magick -size 100x100 xc:black black.pnm`
2) View black.pnm and see it is white instead of the expected black

### System Configuration

- ImageMagick version: 7.0.8-53 + 
```diff
--- a/coders/pnm.c
+++ b/coders/pnm.c
@@ -1944,7 +1944,7 @@ static MagickBooleanType WritePNMImage(const ImageInfo *image_info,Image *image,
         if (quantum_info == (QuantumInfo *) NULL)
           ThrowWriterException(ResourceLimitError,"MemoryAllocationFailed");
         (void) SetQuantumEndian(image,quantum_info,MSBEndian);
-        quantum_info->min_is_white=MagickTrue;
+        quantum_info->min_is_white=MagickFalse;
         pixels=GetQuantumPixels(quantum_info);
         for (y=0; y < (ssize_t) image->rows; y++)
         {
```
- Environment (Operating system, version and so on): Gentoo Linux
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
