### ISSUE TITLE
perl testsuite fails with 7.0.8-54

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1640]
Hi!

Testsuite fails for me in `read.t`
```
Portable bitmap format (black and white), binary format ...
mean-error=1, maximum-error=1
not ok 22
```

and  `write.t`

```
Portable bitmap format (black and white), binary format ...
ReadImage()
Image: PBM:input_p4.pbm, signatures do not match.
     Expected: 71e1a6be223e307b1dbf732860792b15adba662b7a7ef284daf7f982f874ccf1
     Computed: 88ad5b37729ccd4fc292fbaf32776e8009f72abc6136827383231af3676ba956
     Depth:    16
not ok 12
```

The system is linux, x86_64. All tests pass with 7.0.8-53.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
Thank you for the quick fix. Will try again with next release.

**Comment by pgajdos** [comment]
Actually, I tried with 7.0.8-54 plus 4b0c03f, `write.t` now succeeds. However, `read.t` is still failing.

**Comment by urban-warrior** [comment]
Look for a fix in the new release later today, -55.  Its important that the unit tests pass for each release.

**Comment by pgajdos** [comment]
Okay, will report back later. Thanks.

**Comment by pgajdos** [comment]
I have tested with -56, the issue is fixed. Thanks!
