### ISSUE TITLE
C++ cropping  interface does not work with relative 

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#1642]
According to the [manual page](http://www.imagemagick.org/Usage/crop/) we can use percentages in the crop geometry, for example:

    convert rose:   -crop 50%x+0+0      crop_half.gif
However in the C++ api the values are always interpreted as absolute coordinates. For example `50%` will result in an output of `50px`.  

```cpp
#include <Magick++.h> 
using namespace Magick;

int main(){ 
  Magick::Image image("logo:");
  Geometry geom("50%x+0+0");
  image.crop(geom);
  image.page();
  image.write(std::string("output.png"));
}
```

Downstream issue: https://github.com/ropensci/magick/issues/192

**Comment by urban-warrior** [comment]
This is the correct behavior.  The -crop option calls the MagickCore CropImageToTiles() method whereas you are calling CropImage().  You can call CropImageToTiles() as MagickCore::CropImageToTiles() as it is not part of the Magick++ namespace.

**Comment by jeroen** [comment]
OK that's unfortunate. Could you show me how to safely call the MagickCore method on a C++ Image object. Something like this?

```c
// c++ objects
std::string crop
Magick::Image *input;

// call c methods
MagickCore::Image *image = input.image();
MagickCore::ExceptionInfo *exception = MagickCore::AcquireExceptionInfo();
MagickCore::Image *output = MagickCore::CropImageToTiles(image, crop.c_str(), exception);
if(output != NULL)
  *image = *output;
exception=DestroyExceptionInfo(exception);
```

**Comment by jeroen** [comment]
Fixed on my end in https://github.com/ropensci/magick/commit/cbdb7053078e9b14b30fda6dd763f2f013648c10
