### ISSUE TITLE
Converting from PDF to PBM inverts the image

### ISSUE THREAD

**Issue by stovocor** [ImageMagick/ImageMagick#1643]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using `convert` to save any PDF file as a PBM file, the result is inverted.
This issue started with 7.0.8.54 and is still present in 7.0.8.55. It might be related to #1632.

### Steps to Reproduce
`convert file.pdf file.pbm`

If this issue does not happen with all PDF files, use [this example file](https://www.orimi.com/pdf-test.pdf).

### System Configuration

- ImageMagick version: 7.0.8.55
- Environment (Operating system, version and so on): Arch Linux

**Comment by fmw42** [comment]
From the PBM documentation, the values are intended to be inverted, I think. 

> Each bit represents a pixel: 1 is black, 0 is white. 

See http://netpbm.sourceforge.net/doc/pbm.html

**Comment by stovocor** [comment]
I do not think that this behavior is intended since with 7.0.8.53 the image was not inverted.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by fmw42** [comment]
> I do not think that this behavior is intended since with 7.0.8.53 the image was not inverted.

The inversion is built into PBM according to the documentation. Whether Imagemagick wants to honor or ignore it or not is up to the developers. 

But I agree that Imagemagick probably should do the negate internally before writing the PBM output, so a display of the both input and output images looks the same.
