### ISSUE TITLE
svg tspans draw on top of each other again

### ISSUE THREAD

**Issue by MaikWagner** [ImageMagick/ImageMagick#1647]
While updating to ImageMagick 7.0.8-56 I realized that the tspan rendering problem from #1231 + #1578  has resurfaced again.

tspans are drawn overlapped again, using the example svg from #1231:
![master_broken](https://user-images.githubusercontent.com/7701966/61814647-ce16f480-ae48-11e9-977b-749b64adaf0e.png)

Earlier versions of IM and Browsers produced the correct result image:
![text](https://user-images.githubusercontent.com/7701966/58334701-6b04e380-7e40-11e9-82d8-2046c27e2bad.png)

If the following change from ff2a20308d2260c526f93b85ea46323b580f399b that was used to fix in #1633 is reverted, the test image is almost rendered properly again: 
```diff --git a/MagickCore/draw.c b/MagickCore/draw.c
--- a/MagickCore/draw.c
+++ b/MagickCore/draw.c
@@ -4294,6 +4294,8 @@ static MagickBooleanType RenderMVGContent(Image *image,
         status&=GetTypeMetrics(image,clone_info,&metrics,exception);
         clone_info=DestroyDrawInfo(clone_info);
         cursor+=metrics.width;
+        if (draw_info->compliance != SVGCompliance)
+          cursor=0.0;
         break;
       }
       case ImagePrimitive:
```

However, unwanted space is still added before the commas as in https://github.com/ImageMagick/ImageMagick/issues/1231#issuecomment-409880454.
![geometry_fixed](https://user-images.githubusercontent.com/7701966/61814919-6ad99200-ae49-11e9-929e-8277dcee598b.png)

Reverting 3cc832a0a68946c33ec27dd9e9f51f1ec8d92e6e removes all surrounding spaces from text fragments, which is also not correct:
![whitespace_not_fixed](https://user-images.githubusercontent.com/7701966/61815078-bb50ef80-ae49-11e9-8718-099f6bc87890.png)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by MaikWagner** [comment]
Great, thx! Works like a charm!
