### ISSUE TITLE
HEIC  - 'no encode delegate for this image format `HEIC' 

### ISSUE THREAD

**Issue by danwalmsley** [ImageMagick/ImageMagick#1648]
### Prerequisites

- [x ] I have written a descriptive issue title
- [ x] I have verified that I am using the latest version of ImageMagick
- [ x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am unable to encode an image as HEIC - 'no encode delegate for this image format `HEIC' .

### Steps to Reproduce
```
using (var encodedImage = new MagickImage(image.RawData.ToArray()
                , new PixelReadSettings(image.Width, image.Height, 
                StorageType.Float, PixelMapping.RGB)))
            {
                encodedImage.Format = MagickFormat.Heic;

                var memoryStream = new MemoryStream(5000000);
                encodedImage.Write(memoryStream);

                return memoryStream.ToArray();
            }
```

### System Configuration

This is on Windows 10 1903 - x64, im using it in a .net standard 2.0 library referenced from a UWP app.

- ImageMagick version:
`Include="Magick.NET-Q16-HDRI-x64" Version="7.14.1"`

**Comment by Cloudmersive** [comment]
This was closed - but what was the resolution?  Was this not fixed?

**Comment by urban-warrior** [comment]
ImageMagick can write the HEIC image format if the development version of libheif is installed before ImageMagick is configured, built, and installed.

**Comment by J4cker14** [comment]
I have the same, built under windows with libheif installed.

I followed: https://imagemagick.org/script/install-source.php#windows

**Comment by dlemstra** [comment]
Under is only support for encoding to the `.avif` format under Windows.
