### ISSUE TITLE
Invalid free

### ISSUE THREAD

**Issue by tysmith** [ImageMagick/ImageMagick#165]
To reproduce this behavior run the attached test cases with the follow command line with an ASan build:
./magick convert ico:test_case.ico null:-

==50987== ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x600400009b30
    #0 0x7f0c2330333a in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.0+0x1533a)
    #1 0x46d351 in RelinquishMagickMemory /home/user/code/ImageMagick/MagickCore/memory.c:979
0x600400009b30 is located 0 bytes inside of 772-byte region [0x600400009b30,0x600400009e34)
==50987== AddressSanitizer CHECK failed: ../../../../src/libsanitizer/asan/asan_thread_registry.cc:153 "((tid < n_threads_)) != (0)" (0x0, 0x0)
    #0 0x7f0c2330031d (/usr/lib/x86_64-linux-gnu/libasan.so.0+0x1231d)
    #1 0x7f0c23307133 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/usr/lib/x86_64-linux-gnu/libasan.so.0+0x19133)
    #2 0x7f0c233018c8 (/usr/lib/x86_64-linux-gnu/libasan.so.0+0x138c8)
    #3 0x7f0c23304e01 (/usr/lib/x86_64-linux-gnu/libasan.so.0+0x16e01)
    #4 0x7f0c23305733 (/usr/lib/x86_64-linux-gnu/libasan.so.0+0x17733)
    #5 0x7f0c232f6a3f (/usr/lib/x86_64-linux-gnu/libasan.so.0+0x8a3f)
    #6 0x7f0c23303367 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.0+0x15367)
    #7 0x46d351 in RelinquishMagickMemory /home/user/code/ImageMagick/MagickCore/memory.c:979
    #8 0x53a702 in DestroySplayTree /home/user/code/ImageMagick/MagickCore/splay-tree.c:699
    #9 0x475418 in DestroyImageOptions /home/user/code/ImageMagick/MagickCore/option.c:1954
    #10 0x423e82 in DestroyImageInfo /home/user/code/ImageMagick/MagickCore/image.c:1266
    #11 0x424709 in DestroyImage /home/user/code/ImageMagick/MagickCore/image.c:1202
    #12 0x44e089 in DestroyImageList /home/user/code/ImageMagick/MagickCore/list.c:451
    #13 0x6e6835 in ReadICONImage /home/user/code/ImageMagick/coders/icon.c:298
    #14 0x9d4b07 in ReadImage /home/user/code/ImageMagick/MagickCore/constitute.c:496
    #15 0x9d7dd2 in ReadImages /home/user/code/ImageMagick/MagickCore/constitute.c:846
    #16 0xf049ca in ConvertImageCommand /home/user/code/ImageMagick/MagickWand/convert.c:634
    #17 0x10405f3 in MagickCommandGenesis /home/user/code/ImageMagick/MagickWand/mogrify.c:175
    #18 0x41e521 in MagickMain /home/user/code/ImageMagick/utilities/magick.c:137
    #19 0x7f0c224edec4 in __libc_start_main /build/eglibc-3GlaMS/eglibc-2.19/csu/libc-start.c:287
    #20 0x41e0b1 in _start (/home/user/Desktop/img/magick+0x41e0b1)

[test_case.zip](https://github.com/ImageMagick/ImageMagick/files/209220/test_case.zip)

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in GIT master branch @ http://git.imagemagick.org/repos/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
