### ISSUE TITLE
C++20 modules

### ISSUE THREAD

**Issue by danielvandenberg95** [ImageMagick/ImageMagick#1650]
### Prerequisites

- [x ] I have written a descriptive issue title
- [x ] I have verified that I am using the latest version of ImageMagick
- [x ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Magick++ can not be used in C++20 with modules enabled.
`typedef struct _MagickInfo
{
  char
    *name,
    *description,
    *version,
    *mime_type,
    *note,
    *module;//Seen as a keyword`

### Steps to Reproduce
1. Make into Visual Studio project
2. Create an extra visual studio project, with Magick++ as dependency.
3. Add `#include <magick++.h>`
4. Enable  /experimental:module
5. Try compiling.
6. Get magick.h(69): error C2059: syntax error: 'module'.

### System Configuration

- ImageMagick version: master
- Environment (Operating system, version and so on): Windows, Visual Studio 2017, 64 bits.
- Additional information: I did not test this in other compilers supporting modules, but to my knowledge of the proposal using the keyword "module" as a variable name will be illegal.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
