### ISSUE TITLE
"CANNOT LINK EXECUTABLE" Error in Termux after update to 7.0.8.56

### ISSUE THREAD

**Issue by Tawanda-MT** [ImageMagick/ImageMagick#1651]
convert u.png test.png
CANNOT LINK EXECUTABLE: cannot locate symbol "jpeg_default_qtables" referenced by "/data/data/com.termux/files/usr/lib/libMagickCore-7.Q16HDRI.so"...
page record for 0xb6f4b02c was not found (block_size=16)

**Comment by urban-warrior** [comment]
Looks link you need to include the JPEG delegate library in the linking command line, e.g. -ljpeg.

**Comment by Tawanda-MT** [comment]
Hello urban-warrior. Please assist on how I can do the above.

**Comment by Tawanda-MT** [comment]
The problem was solved by upgrading packages, ie "pkg upgrade" on Termux for android. Thank you for you concern.
