### ISSUE TITLE
use imageMagick source code api, how to convert jpg to jp2 and set the quailty of jp2

### ISSUE THREAD

**Issue by iamhgdabc** [ImageMagick/ImageMagick#1654]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

i wan to convert jpg to jp2 and set the quailty of jp2, it is useful convet jpg to jp2 with MagickSetImageFormat function, but when i use MagickGetImageCompressionQuality function to set the quailty of jp2, it is not take effect，how can i convert jpg to jp2 and set quality at the same time use ImageMagick C api.
### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
MagickGetImageCompressionQuality() gets the compression quality.  Instead, use MagickSetCompressionQuality() or MagickSetImageCompressionQuality().
