### ISSUE TITLE
SEGV @ NULL in GetNextValueInSplayTree

### ISSUE THREAD

**Issue by tysmith** [ImageMagick/ImageMagick#166]
To reproduce this behavior run the attached test cases with the follow command line with an ASan build:
./magick convert ico:test_case.ico null:-

==51772== ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00000053bb96 sp 0x7ffcc95d32e0 bp 0x601000007d50 T0)
AddressSanitizer can not provide additional info.
    #0 0x53bb95 in GetNextValueInSplayTree /home/user/code/ImageMagick/MagickCore/splay-tree.c:843
    #1 0x468f1b in GetMagickInfo /home/user/code/ImageMagick/MagickCore/magick.c:558
    #2 0x9344aa in BlobToImage /home/user/code/ImageMagick/MagickCore/blob.c:352
    #3 0x6e8f11 in ReadICONImage /home/user/code/ImageMagick/coders/icon.c:371
    #4 0x9d4b07 in ReadImage /home/user/code/ImageMagick/MagickCore/constitute.c:496
    #5 0x9d7dd2 in ReadImages /home/user/code/ImageMagick/MagickCore/constitute.c:846
    #6 0xf049ca in ConvertImageCommand /home/user/code/ImageMagick/MagickWand/convert.c:634
    #7 0x10405f3 in MagickCommandGenesis /home/user/code/ImageMagick/MagickWand/mogrify.c:175
    #8 0x41e521 in MagickMain /home/user/code/ImageMagick/utilities/magick.c:137
    #9 0x7f04ac7b5ec4 in __libc_start_main /build/eglibc-3GlaMS/eglibc-2.19/csu/libc-start.c:287
    #10 0x41e0b1 in _start (/home/user/Desktop/img/magick+0x41e0b1)
SUMMARY: AddressSanitizer: SEGV /home/user/code/ImageMagick/MagickCore/splay-tree.c:843 GetNextValueInSplayTree

[test_case.zip](https://github.com/ImageMagick/ImageMagick/files/209223/test_case.zip)

**Comment by dlemstra** [comment]
The fix for issue https://github.com/ImageMagick/ImageMagick/issues/165 also fixed this issue. Thanks :+1: again for reporting this.

**Comment by attritionorg** [comment]
Can you link the fixing commit for these? Don't see it in the history. Thanks!
