### ISSUE TITLE
Adding [0] affects how IM handles filenames with %% in them (Win32)

### ISSUE THREAD

**Issue by Rekrullurker** [ImageMagick/ImageMagick#1660]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Let's say you have an aminated GIF with the filename "Te%%st.gif" If you issue the command;

identify -format %w "Te%%st.gif"

It works fine, but you'll get the width of every frame in the file. If you only want to get the width of the first frame and you use the command;

Identify -format %w "Te%%st.gif"[0]

Or;

Identify -format %w "Te%%st.gif[0]"

It produces the error;

"identify: UnableToOpenBlob 'Te%st.gif': No such file or directory @ error/blob.c/OpenBlob/3497."

Adding [0] seems to make IM lose one of the %%. It works if you add an additional %, making the filename "Te%%%st.gif", but that's not practical to do in an automated script that processes all the files in a directory. If the filename should happen to contain three percent signs "Te%%%st.gif", you need to add two extra ones to make it work, "Te%%%%%st.gif"

### Steps to Reproduce
Rename any file to include %% in the filename. Enter the following command;

identify -format %w "file%%name.ext"[0]

### System Configuration
2.4Ghz Core-2-Duo
WinXP Pro, SP3
4GB RAM
- ImageMagick version: ImageMagick-7.0.8-59-portable-Q16-x86.zip
- Environment (Operating system, version and so on): Windows XP Pro, SP3
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
