### ISSUE TITLE
1-byte-read-heap-buffer-overflow in IsHTML

### ISSUE THREAD

**Issue by omira-sch** [ImageMagick/ImageMagick#1664]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Calling IsHTML() with a 5 bytes allocated buffer will cause an out-of-bounds read of 1 byte.

https://github.com/ImageMagick/ImageMagick/blob/252dd2c52bcc591ccd673abdbb70113b42388150/coders/html.c#L95-L102

The problem is the strncasecmp is correctly limited to read only 5 bytes ("html\0") and there is a check for the minimum length of 5, but the buffer pointer is incremented by one byte "magick+1" in between.

Should be:
```
if (length < 6) 
  return(MagickFalse); 
```

### Steps to Reproduce

```
==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x609000003a75 at pc 0x000001185cd4 bp 0x7fff81ca00a0 sp 0x7fff81ca0098
READ of size 1 at 0x609000003a75 thread T0
SCARINESS: 12 (1-byte-read-heap-buffer-overflow)
    #0 0x1185cd3 in InternalStrnlen /src/libfuzzer/FuzzerTracePC.cpp:403:26
    #1 0x1185cd3 in __sanitizer_weak_hook_strncmp /src/libfuzzer/FuzzerTracePC.cpp:637
    #2 0x1185cd3 in __sanitizer_weak_hook_strncasecmp /src/libfuzzer/FuzzerTracePC.cpp:659
    #3 0x435938 in strncasecmp /src/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_common_interceptors.inc:537:3
    #4 0xc09dc8 in IsHTML imagemagick/coders/html.c:99:7
    #5 0xac90cf in GetImageMagick imagemagick/MagickCore/magick.c:319:10
...
```
### System Configuration

- ImageMagick version: HEAD (latest commit https://github.com/ImageMagick/ImageMagick/commit/5754efa6a280f892dcd6042439078408275e8f59)
- Environment (Operating system, version and so on): linux
- Additional information: reported by oss-fuzz while fuzzing libvips, with ImageMagick compiled as dependency

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
