### ISSUE TITLE
__memset_sses and clear_page_c_e use a lot of CPU

### ISSUE THREAD

**Issue by iamhgdabc** [ImageMagick/ImageMagick#1667]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

![xxx](https://user-images.githubusercontent.com/11517961/63070303-4440df80-bf4d-11e9-9b03-93b7937315f7.png)
how to optimize cpu usage
ImageMagick version is 6.9.8-4
### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
Try the latest release of ImageMagick, 6.9.10-60.  We get
```
  23.07%  convert  libMagickCore-6.Q16.so.6.0.0  [.] TransformSignature
  10.20%  convert  libpthread-2.17.so            [.] __pread_nocancel
   9.64%  convert  libpthread-2.17.so            [.] __pwrite_nocancel
   6.32%  convert  libgomp.so.1.0.0              [.] omp_set_lock
   5.63%  convert  libMagickCore-6.Q16.so.6.0.0  [.] RiemersmaDither
   4.49%  convert  libgomp.so.1.0.0              [.] omp_unset_lock
```

**Comment by dlemstra** [comment]
Ping @iamhgdabc
