### ISSUE TITLE
can no more compile imagemagick-7.0.8-61

### ISSUE THREAD

**Issue by freakout42** [ImageMagick/ImageMagick#1669]
i compile imagemagick on a selfmaintained Linux-platform since 1997 and 7.0.8-61 refuses to compile/link:

<pre>CCLD     utilities/magick
MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `AcquireCLocale'
collect2: error: ld returned 1 exit status
</pre>
is there any obvious reason for that? All the current libs for gs png tiff gd bzip2 jpeg freetype fontconfig libffi pango harfbuzz glib2 gettext are installed on the system and imagemagick-7.0.8-60 compiles fine with the same build script.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by freakout42** [comment]
i applied patch https://github.com/ImageMagick/ImageMagick/commit/7e66200bcf6a3f360dcf08498c041ec2c85630bc and it works fine for me - thanks for the quick solution and for ImageMagick
