### ISSUE TITLE
error "Time delay method not defined."

### ISSUE THREAD

**Issue by iamhgdabc** [ImageMagick/ImageMagick#1670]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

  CC       MagickCore/libMagickCore_7_Q8HDRI_la-version.lo
MagickCore/utility.c: 在函数‘MagickDelay’中:
MagickCore/utility.c:1743:3: 错误：#error "Time delay method not defined."
 # error "Time delay method not defined."
   ^
  CC       MagickCore/libMagickCore_7_Q8HDRI_la-vision.lo
  CC       MagickCore/libMagickCore_7_Q8HDRI_la-widget.lo
make[2]: *** [MagickCore/libMagickCore_7_Q8HDRI_la-utility.lo] 错误 1

should link what library?
### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
ImageMagick requires a high resolution sleep function.  The configure script looks for one of nanosleep(), usleep(), select(), poll(), Sleep(), or snooze().  If it can't find one of these, it gives up and throws a compile exception.
