### ISSUE TITLE
Number of resolutions is too high in comparison to the size of tiles

### ISSUE THREAD

**Issue by NickLekkas10** [ImageMagick/ImageMagick#1673]
https://imagemagick.org/discourse-server/viewtopic.php?f=3&t=34682

Hello,

I have the same problem as the topic above but it seems there has not been a solution for it yet. As you can see there is a problem with the number of resolutions when there is a big difference between the width and the height of an image. (Look the example in the link above)
I am using ImageMagick v7 in ubuntu 18.04.

**Output:**
Caught exception: <executable>: Number of resolutions is too high in comparison to the size of tiles
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/194
Caught exception: <executable>: Number of resolutions is too high in comparison to the size of tiles
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/194
Error: An exception occurred during image extraction
<output-params>

**Comment by dlemstra** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by NickLekkas10** [comment]
Thanks for the quick response.
