### ISSUE TITLE
Missing Delegates - JP2

### ISSUE THREAD

**Issue by NickLekkas10** [ImageMagick/ImageMagick#1676]
Hi

I have seen that you had jp2 delegate until your 7.0.8.12 version. After that version jp2 delegate is not present in the magic.c file and so I can not use identify and convert for jp2 files.
I need it because I try to use jp2 compress and i get larger files than the normal ones.

**Comment by dlemstra** [comment]
We have moved this to a different header file but it appears that I made a mistake. Just pushed a patch to resolve this.

**Comment by dlemstra** [comment]
And it seems that we had an incorrect offset in the magic.c file. This started at offset `4` but the correct offset is `0` so I had to revert this fix.

Can you explain in more detail what kind of issue you are experiencing?
