### ISSUE TITLE
pdf to tiff conversion gives bad quality image

### ISSUE THREAD

**Issue by manibharathytu** [ImageMagick/ImageMagick#1677]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Input file : https://drive.google.com/open?id=1zgDNQDTzzljBiNkMvw4WMd3Bc35dVdjB
Output file : https://drive.google.com/open?id=1OOcZY-IVzmvrIWeBdjgUWSOM0hAJZcxq

The quality of the output file is bad while the quality of input file is good

### Steps to Reproduce

 Open terminal and enter the following command
`convert input_file output.tiff`

### System Configuration

- ImageMagick version: Version: ImageMagick 7.0.8-14 Q16 x86_64
- Environment (Operating system, version and so on): Ubuntu 16.04
- Additional information:

**Comment by fmw42** [comment]
Where is your command? Where are your input an output images? The developers need to be able to reproduce your results.  What is your exact ImageMagick version and platform/OS?

**Comment by manibharathytu** [comment]
@fmw42 Added information to question. Let me know if you need any more info.

**Comment by fmw42** [comment]
On ImageMagick 7, use magick not convert. You need to set a higher density and then resize correspondingly to get good quality. So try

`magick -density 288 med.pdf -resize 25% output.tiff`

**Comment by manibharathytu** [comment]
Thanks @fmw42 . That gives a better quality image. I'm exploring on those options. I still have one more issue. The second page of my output comes in black background which you can see from that link.

**Comment by fmw42** [comment]
The second page has partial transparency in your PDF. You can see that from the color values if you  do 

`magick identify -verbose med.pdf`

To make the background white do the following:

`magick -density 288 med.pdf -background white -alpha background -alpha off -resize 25% output.tiff`
