### ISSUE TITLE
is safe to use openmp in  Multithread program

### ISSUE THREAD

**Issue by iamhgdabc** [ImageMagick/ImageMagick#1678]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

https://legacy.imagemagick.org/script/openmp.php 
it says in certain cases it might be optimal to set the number of threads to 1 (e.g. -limit thread 1) or to disable OpenMP completely. my program is a Multithread Framework， it is safe to use openmp now.
### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
Are you asking a question or making a statement?

**Comment by dlemstra** [comment]
It is safe to openmp in a multithreaded environment but it is possible that it is faster when openmp is disabled. But that depends on your situation and you should measure that yourself.
