### ISSUE TITLE
Color spaces `gray` and `lineargray` appear to be the same.

### ISSUE THREAD

**Issue by mfwitten** [ImageMagick/ImageMagick#1680]
There appears to be no difference between the colorspaces [non-linear] `gray` and `lineargray`.

Certainly, I don't understand what's going on, which *might* indicate a bug in ImageMagick or a need to improve the documentation.

Version:

    $ magick -version
    Version: ImageMagick 7.0.8-53 Q16 i686 2019-07-15 https://imagemagick.org
    Copyright: © 1999-2019 ImageMagick Studio LLC
    License: https://imagemagick.org/script/license.php
    Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
    Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zlib

In the following POSIX shell code, there is initially created at index 0 in the ImageMagick image sequence an `sRGB` color image with one orange pixel; from this `sRGB` image, the following 2 grayscale images are created next:

* A [non-linear] `gray` image (at index 1).
* A `lineargray` image (at index 2).

Then, from that same `sRGB` color image (at index 0), a linear `RGB` image is created (at index 3, which can be seen to differ in its green component due to the color-space conversion; from this `RGB` image, the following 2 grayscale images are created next:

* A [non-linear] `gray` image (at index 4).
* A `lineargray` image (at index 5).

Here is the code:

    magick \
      -size 1x1 canvas:"orange"                 \
                                                \
      \( -clone 0 -colorspace gray \)           \
      \( -clone 0 -colorspace lineargray \)     \
                                                \
      \( -clone 0 -colorspace rgb \)            \
                                                \
      \( -clone 3 -colorspace gray \)           \
      \( -clone 3 -colorspace lineargray \)     \
                                                \
      txt:

This is the code's output on my system:

    # ImageMagick pixel enumeration: 1,1,65535,srgb
    0,0: (65535,42405,0)  #FFFFA5A50000  orange
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (44262.7)  #ACE7ACE7ACE7  gray(67.5405%)
    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (44262.7)  #ACE7ACE7ACE7  lineargray(67.5405%)
    # ImageMagick pixel enumeration: 1,1,65535,rgb
    0,0: (65535,24658.3,0)  #FFFF60520000  rgb(100%,37.6262%,0%)
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (44262.7)  #ACE7ACE7ACE7  gray(67.5405%)
    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (44262.7)  #ACE7ACE7ACE7  lineargray(67.5405%)

**As you can see, the grayscale values are always the same!**

In the following, the POSIX shell function `make_grays` produces 4 pairs of single-pixel images; each pair consists of a [non-linear] `gray` image and a `lineargray` image, such that the `lineargray` image is derived by converting the `gray` image:

    gray()
    { 
      magick -size 1x1 canvas:"gray($1)" -write txt: -colorspace LinearGray txt:
    }

    make_grays()
    { 
      for v; do
        gray "$v"%
        printf '%s\n' --------------------
      done
    }

Unexpectedly, the pixel value for each image in a pair is the same:

    $ make_grays 1 45 55 99
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (655.35)  #028F028F028F  gray(1%)
    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (655.35)  #028F028F028F  lineargray(1%)
    --------------------
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (29490.8)  #733373337333  gray(45%)
    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (29490.8)  #733373337333  lineargray(45%)
    --------------------
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (36044.2)  #8CCC8CCC8CCC  gray(55%)
    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (36044.2)  #8CCC8CCC8CCC  lineargray(55%)
    --------------------
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (64879.7)  #FD70FD70FD70  gray(99%)
    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (64879.7)  #FD70FD70FD70  lineargray(99%)
    --------------------

Here is a more extensive list, indicating that there is no difference between [non-linear] `gray` and `lineargray`:

    $ make_grays $(seq 1 100) | grep '^[-0-9]'
    0,0: (655.35)  #028F028F028F  gray(1%)
    0,0: (655.35)  #028F028F028F  lineargray(1%)
    --------------------
    0,0: (1310.7)  #051F051F051F  gray(2%)
    0,0: (1310.7)  #051F051F051F  lineargray(2%)
    --------------------
    0,0: (1966.05)  #07AE07AE07AE  gray(3%)
    0,0: (1966.05)  #07AE07AE07AE  lineargray(3%)
    --------------------
    0,0: (2621.4)  #0A3D0A3D0A3D  gray(4%)
    0,0: (2621.4)  #0A3D0A3D0A3D  lineargray(4%)
    --------------------
    0,0: (3276.75)  #0CCD0CCD0CCD  gray(5%)
    0,0: (3276.75)  #0CCD0CCD0CCD  lineargray(5%)
    --------------------
    0,0: (3932.1)  #0F5C0F5C0F5C  gray(6%)
    0,0: (3932.1)  #0F5C0F5C0F5C  lineargray(6%)
    --------------------
    0,0: (4587.45)  #11EB11EB11EB  gray(7%)
    0,0: (4587.45)  #11EB11EB11EB  lineargray(7%)
    --------------------
    0,0: (5242.8)  #147B147B147B  gray(8%)
    0,0: (5242.8)  #147B147B147B  lineargray(8%)
    --------------------
    0,0: (5898.15)  #170A170A170A  gray(9%)
    0,0: (5898.15)  #170A170A170A  lineargray(9%)
    --------------------
    0,0: (6553.5)  #199A199A199A  gray(10%)
    0,0: (6553.5)  #199A199A199A  lineargray(10%)
    --------------------
    0,0: (7208.85)  #1C291C291C29  gray(11%)
    0,0: (7208.85)  #1C291C291C29  lineargray(11%)
    --------------------
    0,0: (7864.2)  #1EB81EB81EB8  gray(12%)
    0,0: (7864.2)  #1EB81EB81EB8  lineargray(12%)
    --------------------
    0,0: (8519.55)  #214821482148  gray(13%)
    0,0: (8519.55)  #214821482148  lineargray(13%)
    --------------------
    0,0: (9174.9)  #23D723D723D7  gray(14%)
    0,0: (9174.9)  #23D723D723D7  lineargray(14%)
    --------------------
    0,0: (9830.25)  #266626662666  gray(15%)
    0,0: (9830.25)  #266626662666  lineargray(15%)
    --------------------
    0,0: (10485.6)  #28F628F628F6  gray(16%)
    0,0: (10485.6)  #28F628F628F6  lineargray(16%)
    --------------------
    0,0: (11141)  #2B852B852B85  gray(17%)
    0,0: (11141)  #2B852B852B85  lineargray(17%)
    --------------------
    0,0: (11796.3)  #2E142E142E14  gray(18%)
    0,0: (11796.3)  #2E142E142E14  lineargray(18%)
    --------------------
    0,0: (12451.6)  #30A430A430A4  gray(19%)
    0,0: (12451.6)  #30A430A430A4  lineargray(19%)
    --------------------
    0,0: (13107)  #333333333333  gray(51)
    0,0: (13107)  #333333333333  lineargray(51)
    --------------------
    0,0: (13762.4)  #35C235C235C2  gray(21%)
    0,0: (13762.4)  #35C235C235C2  lineargray(21%)
    --------------------
    0,0: (14417.7)  #385238523852  gray(22%)
    0,0: (14417.7)  #385238523852  lineargray(22%)
    --------------------
    0,0: (15073.1)  #3AE13AE13AE1  gray(23%)
    0,0: (15073.1)  #3AE13AE13AE1  lineargray(23%)
    --------------------
    0,0: (15728.4)  #3D703D703D70  gray(24%)
    0,0: (15728.4)  #3D703D703D70  lineargray(24%)
    --------------------
    0,0: (16383.8)  #400040004000  gray(25%)
    0,0: (16383.8)  #400040004000  lineargray(25%)
    --------------------
    0,0: (17039.1)  #428F428F428F  gray(26%)
    0,0: (17039.1)  #428F428F428F  lineargray(26%)
    --------------------
    0,0: (17694.5)  #451E451E451E  gray(27%)
    0,0: (17694.5)  #451E451E451E  lineargray(27%)
    --------------------
    0,0: (18349.8)  #47AE47AE47AE  gray(28%)
    0,0: (18349.8)  #47AE47AE47AE  lineargray(28%)
    --------------------
    0,0: (19005.2)  #4A3D4A3D4A3D  gray(29%)
    0,0: (19005.2)  #4A3D4A3D4A3D  lineargray(29%)
    --------------------
    0,0: (19660.5)  #4CCD4CCD4CCD  gray(30%)
    0,0: (19660.5)  #4CCD4CCD4CCD  lineargray(30%)
    --------------------
    0,0: (20315.9)  #4F5C4F5C4F5C  gray(31%)
    0,0: (20315.9)  #4F5C4F5C4F5C  lineargray(31%)
    --------------------
    0,0: (20971.2)  #51EB51EB51EB  gray(32%)
    0,0: (20971.2)  #51EB51EB51EB  lineargray(32%)
    --------------------
    0,0: (21626.5)  #547B547B547B  gray(33%)
    0,0: (21626.5)  #547B547B547B  lineargray(33%)
    --------------------
    0,0: (22281.9)  #570A570A570A  gray(34%)
    0,0: (22281.9)  #570A570A570A  lineargray(34%)
    --------------------
    0,0: (22937.2)  #599959995999  gray(35%)
    0,0: (22937.2)  #599959995999  lineargray(35%)
    --------------------
    0,0: (23592.6)  #5C295C295C29  gray(36%)
    0,0: (23592.6)  #5C295C295C29  lineargray(36%)
    --------------------
    0,0: (24248)  #5EB85EB85EB8  gray(37%)
    0,0: (24248)  #5EB85EB85EB8  lineargray(37%)
    --------------------
    0,0: (24903.3)  #614761476147  gray(38%)
    0,0: (24903.3)  #614761476147  lineargray(38%)
    --------------------
    0,0: (25558.7)  #63D763D763D7  gray(39%)
    0,0: (25558.7)  #63D763D763D7  lineargray(39%)
    --------------------
    0,0: (26214)  #666666666666  gray(102)
    0,0: (26214)  #666666666666  lineargray(102)
    --------------------
    0,0: (26869.4)  #68F568F568F5  gray(41%)
    0,0: (26869.4)  #68F568F568F5  lineargray(41%)
    --------------------
    0,0: (27524.7)  #6B856B856B85  gray(42%)
    0,0: (27524.7)  #6B856B856B85  lineargray(42%)
    --------------------
    0,0: (28180)  #6E146E146E14  gray(43%)
    0,0: (28180)  #6E146E146E14  lineargray(43%)
    --------------------
    0,0: (28835.4)  #70A370A370A3  gray(44%)
    0,0: (28835.4)  #70A370A370A3  lineargray(44%)
    --------------------
    0,0: (29490.8)  #733373337333  gray(45%)
    0,0: (29490.8)  #733373337333  lineargray(45%)
    --------------------
    0,0: (30146.1)  #75C275C275C2  gray(46%)
    0,0: (30146.1)  #75C275C275C2  lineargray(46%)
    --------------------
    0,0: (30801.5)  #785178517851  gray(47%)
    0,0: (30801.5)  #785178517851  lineargray(47%)
    --------------------
    0,0: (31456.8)  #7AE17AE17AE1  gray(48%)
    0,0: (31456.8)  #7AE17AE17AE1  lineargray(48%)
    --------------------
    0,0: (32112.2)  #7D707D707D70  gray(49%)
    0,0: (32112.2)  #7D707D707D70  lineargray(49%)
    --------------------
    0,0: (32767.5)  #800080008000  gray(50%)
    0,0: (32767.5)  #800080008000  lineargray(50%)
    --------------------
    0,0: (33422.8)  #828F828F828F  gray(51%)
    0,0: (33422.8)  #828F828F828F  lineargray(51%)
    --------------------
    0,0: (34078.2)  #851E851E851E  gray(52%)
    0,0: (34078.2)  #851E851E851E  lineargray(52%)
    --------------------
    0,0: (34733.6)  #87AE87AE87AE  gray(53%)
    0,0: (34733.6)  #87AE87AE87AE  lineargray(53%)
    --------------------
    0,0: (35388.9)  #8A3D8A3D8A3D  gray(54%)
    0,0: (35388.9)  #8A3D8A3D8A3D  lineargray(54%)
    --------------------
    0,0: (36044.2)  #8CCC8CCC8CCC  gray(55%)
    0,0: (36044.2)  #8CCC8CCC8CCC  lineargray(55%)
    --------------------
    0,0: (36699.6)  #8F5C8F5C8F5C  gray(56%)
    0,0: (36699.6)  #8F5C8F5C8F5C  lineargray(56%)
    --------------------
    0,0: (37355)  #91EB91EB91EB  gray(57%)
    0,0: (37355)  #91EB91EB91EB  lineargray(57%)
    --------------------
    0,0: (38010.3)  #947A947A947A  gray(58%)
    0,0: (38010.3)  #947A947A947A  lineargray(58%)
    --------------------
    0,0: (38665.7)  #970A970A970A  gray(59%)
    0,0: (38665.7)  #970A970A970A  lineargray(59%)
    --------------------
    0,0: (39321)  #999999999999  gray(153)
    0,0: (39321)  #999999999999  lineargray(153)
    --------------------
    0,0: (39976.3)  #9C289C289C28  gray(61%)
    0,0: (39976.3)  #9C289C289C28  lineargray(61%)
    --------------------
    0,0: (40631.7)  #9EB89EB89EB8  gray(62%)
    0,0: (40631.7)  #9EB89EB89EB8  lineargray(62%)
    --------------------
    0,0: (41287.1)  #A147A147A147  gray(63%)
    0,0: (41287.1)  #A147A147A147  lineargray(63%)
    --------------------
    0,0: (41942.4)  #A3D6A3D6A3D6  gray(64%)
    0,0: (41942.4)  #A3D6A3D6A3D6  lineargray(64%)
    --------------------
    0,0: (42597.8)  #A666A666A666  gray(65%)
    0,0: (42597.8)  #A666A666A666  lineargray(65%)
    --------------------
    0,0: (43253.1)  #A8F5A8F5A8F5  gray(66%)
    0,0: (43253.1)  #A8F5A8F5A8F5  lineargray(66%)
    --------------------
    0,0: (43908.5)  #AB84AB84AB84  gray(67%)
    0,0: (43908.5)  #AB84AB84AB84  lineargray(67%)
    --------------------
    0,0: (44563.8)  #AE14AE14AE14  gray(68%)
    0,0: (44563.8)  #AE14AE14AE14  lineargray(68%)
    --------------------
    0,0: (45219.2)  #B0A3B0A3B0A3  gray(69%)
    0,0: (45219.2)  #B0A3B0A3B0A3  lineargray(69%)
    --------------------
    0,0: (45874.5)  #B333B333B333  gray(70%)
    0,0: (45874.5)  #B333B333B333  lineargray(70%)
    --------------------
    0,0: (46529.8)  #B5C2B5C2B5C2  gray(71%)
    0,0: (46529.8)  #B5C2B5C2B5C2  lineargray(71%)
    --------------------
    0,0: (47185.2)  #B851B851B851  gray(72%)
    0,0: (47185.2)  #B851B851B851  lineargray(72%)
    --------------------
    0,0: (47840.6)  #BAE1BAE1BAE1  gray(73%)
    0,0: (47840.6)  #BAE1BAE1BAE1  lineargray(73%)
    --------------------
    0,0: (48495.9)  #BD70BD70BD70  gray(74%)
    0,0: (48495.9)  #BD70BD70BD70  lineargray(74%)
    --------------------
    0,0: (49151.2)  #BFFFBFFFBFFF  gray(75%)
    0,0: (49151.2)  #BFFFBFFFBFFF  lineargray(75%)
    --------------------
    0,0: (49806.6)  #C28FC28FC28F  gray(76%)
    0,0: (49806.6)  #C28FC28FC28F  lineargray(76%)
    --------------------
    0,0: (50462)  #C51EC51EC51E  gray(77%)
    0,0: (50462)  #C51EC51EC51E  lineargray(77%)
    --------------------
    0,0: (51117.3)  #C7ADC7ADC7AD  gray(78%)
    0,0: (51117.3)  #C7ADC7ADC7AD  lineargray(78%)
    --------------------
    0,0: (51772.7)  #CA3DCA3DCA3D  gray(79%)
    0,0: (51772.7)  #CA3DCA3DCA3D  lineargray(79%)
    --------------------
    0,0: (52428)  #CCCCCCCCCCCC  gray(204)
    0,0: (52428)  #CCCCCCCCCCCC  lineargray(204)
    --------------------
    0,0: (53083.3)  #CF5BCF5BCF5B  gray(81%)
    0,0: (53083.3)  #CF5BCF5BCF5B  lineargray(81%)
    --------------------
    0,0: (53738.7)  #D1EBD1EBD1EB  gray(82%)
    0,0: (53738.7)  #D1EBD1EBD1EB  lineargray(82%)
    --------------------
    0,0: (54394.1)  #D47AD47AD47A  gray(83%)
    0,0: (54394.1)  #D47AD47AD47A  lineargray(83%)
    --------------------
    0,0: (55049.4)  #D709D709D709  gray(84%)
    0,0: (55049.4)  #D709D709D709  lineargray(84%)
    --------------------
    0,0: (55704.8)  #D999D999D999  gray(85%)
    0,0: (55704.8)  #D999D999D999  lineargray(85%)
    --------------------
    0,0: (56360.1)  #DC28DC28DC28  gray(86%)
    0,0: (56360.1)  #DC28DC28DC28  lineargray(86%)
    --------------------
    0,0: (57015.5)  #DEB7DEB7DEB7  gray(87%)
    0,0: (57015.5)  #DEB7DEB7DEB7  lineargray(87%)
    --------------------
    0,0: (57670.8)  #E147E147E147  gray(88%)
    0,0: (57670.8)  #E147E147E147  lineargray(88%)
    --------------------
    0,0: (58326.2)  #E3D6E3D6E3D6  gray(89%)
    0,0: (58326.2)  #E3D6E3D6E3D6  lineargray(89%)
    --------------------
    0,0: (58981.5)  #E666E666E666  gray(90%)
    0,0: (58981.5)  #E666E666E666  lineargray(90%)
    --------------------
    0,0: (59636.8)  #E8F5E8F5E8F5  gray(91%)
    0,0: (59636.8)  #E8F5E8F5E8F5  lineargray(91%)
    --------------------
    0,0: (60292.2)  #EB84EB84EB84  gray(92%)
    0,0: (60292.2)  #EB84EB84EB84  lineargray(92%)
    --------------------
    0,0: (60947.6)  #EE14EE14EE14  gray(93%)
    0,0: (60947.6)  #EE14EE14EE14  lineargray(93%)
    --------------------
    0,0: (61602.9)  #F0A3F0A3F0A3  gray(94%)
    0,0: (61602.9)  #F0A3F0A3F0A3  lineargray(94%)
    --------------------
    0,0: (62258.2)  #F332F332F332  gray(95%)
    0,0: (62258.2)  #F332F332F332  lineargray(95%)
    --------------------
    0,0: (62913.6)  #F5C2F5C2F5C2  gray(96%)
    0,0: (62913.6)  #F5C2F5C2F5C2  lineargray(96%)
    --------------------
    0,0: (63569)  #F851F851F851  gray(97%)
    0,0: (63569)  #F851F851F851  lineargray(97%)
    --------------------
    0,0: (64224.3)  #FAE0FAE0FAE0  gray(98%)
    0,0: (64224.3)  #FAE0FAE0FAE0  lineargray(98%)
    --------------------
    0,0: (64879.7)  #FD70FD70FD70  gray(99%)
    0,0: (64879.7)  #FD70FD70FD70  lineargray(99%)
    --------------------
    0,0: (65535)  #FFFFFFFFFFFF  gray(255)
    0,0: (65535)  #FFFFFFFFFFFF  lineargray(255)
    --------------------

**Comment by urban-warrior** [comment]
Named colors closely follows the SVG standard-- that is, named colors are interpreted as non-linear sRGB or gray.  SVG expects rgb() to return values in the sRGB colorspace rather than linear RGB.  For symmetry we interpret lineargray() as non-linear gray.

**Comment by mfwitten** [comment]
I'm still uncertain. Conversion from `sRGB` to `RGB` produces a difference (as expected):

    $ magick canvas:orange \( +clone -colorspace RGB \) txt: | grep '^0'
    0,0: (65535,42405,0)  #FFFFA5A50000  orange
    0,0: (65535,24658.3,0)  #FFFF60520000  rgb(100%,37.6262%,0%)

**However, I'll note that the color name/specification changed, too! According to you, it shouldn't have changed, and should be the following:**

    0,0: (65535,42405,0)  #FFFFA5A50000  orange
    0,0: (65535,24658.3,0)  #FFFFA5A50000  orange

That is to say, **only the channel values should be different**; the color names should be the same.

Anyway, with regard to grays, [according to the docs](https://imagemagick.org/script/command-line-options.php#colorspace):

> Note, ImageMagick assumes the sRGB colorspace if the image format does not indicate otherwise. For colorspace conversion, the gamma function is first removed to produce linear RGB.
> \[&hellip;\]
> `Gray = 0.212656*R+0.715158*G+0.072186*B`
> \[&hellip;\]
> `LinearGray = 0.298839*R+0.586811*G+0.114350*B`

(Please note that the documentation above is completely ambiguous, with a bias towards being wrong; in the formulas, the variables `R`, `G`, and `B` are non-linear, such that the coefficients of the formulas incorporate linearization.)

Therefore, the results of conversion to `Gray` should be different from the results of conversion to `LinearGray`, but they are exactly the same:

    $ magick canvas:orange                    \
        \( -clone 0 -colorspace Gray \)       \
        \( -clone 0 -colorspace LinearGray \) \
        txt: | grep '^0'
    0,0: (65535,42405,0)  #FFFFA5A50000  orange
    0,0: (44262.7)  #ACE7ACE7ACE7  gray(67.5405%)
    0,0: (44262.7)  #ACE7ACE7ACE7  lineargray(67.5405%)

I expected something more like the following:

    0,0: (65535,42405,0)  #FFFFA5A50000  orange
    0,0: (44262.7)  #ACE7ACE7ACE7  gray(67.5405%)
    0,0: (44468.1)  #ACE7ACE7ACE7  gray(67.5405%)

which I got by doing these Python calculations:

    >>> R,G,B = (65535,42405,0) # non-linear values
    >>> Gray = 0.212656*R+0.715158*G+0.072186*B
    >>> Gray
    44262.68595
    >>> Gray/65535
    0.675405294117647
    >>> LinearGray = 0.298839*R+0.586811*G+0.114350*B
    >>> LinearGray
    44468.13432
    >>> LinearGray/65535
    0.6785402352941176

and then the following ImageMagick commands (using `-fx` to bypass color names/specs):

    $ magick canvas:'gray(0)' -fx 0.675405294117647  txt:
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (44262.7)  #ACE7ACE7ACE7  gray(67.5405%)
    $ magick canvas:'lineargray(0)' -fx 0.6785402352941176 txt:
    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (44468.1)  #ADB4ADB4ADB4  lineargray(67.854%)

**BUT NOTE:**

The expected form was produced by manually replacing:

    #ADB4ADB4ADB4  lineargray(67.854%)

with:

    #ACE7ACE7ACE7  gray(67.5405%)

because you've stated that a color name is basically non-linear by definition; only the actual, stored channel value should be different.

Needless to say, I'm quite confused!

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by mfwitten** [comment]
Alas, the original problem is back (`Gray` and `LinearGray` are indistinguishable):

    $ magick                                \
      canvas:orange                         \
      \( -clone 0 -colorspace Gray       \) \
      \( -clone 0 -colorspace LinearGray \) \
      txt: | grep '^0'
    0,0: (65535,42405,0)  #FFFFA5A50000  orange
    0,0: (44262.7)  #ACE7ACE7ACE7  gray(67.5405%)
    0,0: (44262.7)  #ACE7ACE7ACE7  lineargray(67.5405%)

That last line ***should*** have the following channel value (as calculated previously using the `LinearGray` formula with non-linear `sRGB` inputs `R` and `G` and `B`):

    44468.13432

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by mfwitten** [comment]
* Now, conversion between `Gray` and `LinearGray` appears to cause the channel value to approach zero asymptotically:

      $ magick canvas:orange                \
        \( +clone -colorspace Gray       \) \
        \( +clone -colorspace LinearGray \) \
        \( +clone -colorspace Gray       \) \
        \( +clone -colorspace LinearGray \) \
        \( +clone -colorspace Gray       \) \
        \( +clone -colorspace LinearGray \) \
        \( +clone -colorspace Gray       \) \
        \( +clone -colorspace LinearGray \) \
        \( +clone -colorspace Gray       \) \
        \( +clone -colorspace LinearGray \) \
        \( +clone -colorspace Gray       \) \
        \( +clone -colorspace LinearGray \) \
        txt: | grep ^0
      0,0: (65535,42405,0)  #FFFFA5A50000  orange
      0,0: (44262.7)  #ACE7ACE7ACE7  gray(67.5405%)
      0,0: (27115.7)  #69EC69EC69EC  lineargray(41.3759%)
      0,0: (30762.1)  #782A782A782A  gray(46.94%)
      0,0: (12242.1)  #2FD22FD22FD2  lineargray(18.6803%)
      0,0: (16180.5)  #3F353F353F35  gray(24.6899%)
      0,0: (3253.38)  #0CB50CB50CB5  lineargray(4.96434%)
      0,0: (6002.42)  #177217721772  gray(9.1591%)
      0,0: (574.546)  #023F023F023F  lineargray(0.876701%)
      0,0: (1728.82)  #06C106C106C1  gray(2.638%)
      0,0: (133.809)  #008600860086  lineargray(0.20418%)
      0,0: (472.997)  #01D901D901D9  gray(0.721747%)
      0,0: (36.6097)  #002500250025  lineargray(0.0558628%)

* I'll note, too, that I have reservations about the existing calculation of `Gray`.

    As shown in the previous discussion, the initial `Gray` channel value (`44262.7`) seems to be derived from using *non-linear* values for `R` and `G` and `B` in the conversion formula; however, not only is the formula fundamentally linear in nature, but the literature I've looked at (including ImageMagick's own documentation, as pointed out) says that those inputs should be *linearized* (e.g., already gamma-expanded). In other words, currently, the calculation for `Gray` seems to be this (Python interactive interpreter):

      >>> R,G,B = (65535,42405,0) # canvas:orange (e.g., gamma-compressed sRGB values)
      >>> Gray = 0.212656*R+0.715158*G+0.072186*B
      >>> Gray
      44262.68595

    but it should be this (assuming these linearized values are themselves correct):

      >>> R,G,B = (65535,24658.3,0) # canvas:orange -colorspace RGB
      >>> Gray = 0.212656*R+0.715158*G+0.072186*B
      >>> Gray
      31570.9914714

**Comment by mfwitten** [comment]
Please note the EDIT at the end of the last comment.

**Comment by urban-warrior** [comment]
Thanks for your careful analysis and follow-up.  As you can tell, this has been a challenging fix.  Try the latest commit and let us know what still breaks.
