### ISSUE TITLE
Color `lineargray(x)` is recognized, but always `0` regardless of `x`.

### ISSUE THREAD

**Issue by mfwitten** [ImageMagick/ImageMagick#1681]
The color specification `lineargray()` is recognized, but always returns `lineargray(0)` regardless of its argument.

Given this:

    $ magick -size 1x1 canvas:'lineargray(50%)' txt:

I expect this:

    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (32767.5)  #800080008000  lineargray(50%)

but I get this:

    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (0)  #000000000000  lineargray(0)

Note that `lineargray()` is in fact recognized; an unknown specification produces an error:

    $ magick -size 1x1 canvas:'foobar(50%)' txt:
    magick: unrecognized color `foobar(50%)' @ warning/color.c/QueryColorCompliance/2394.
    magick: no images for write '-write' 'txt:' at CLI arg 4 @ error/operation.c/CLINoImageOperator/4816.

Version:

    $ magick -version
    Version: ImageMagick 7.0.8-53 Q16 i686 2019-07-15 https://imagemagick.org
    Copyright: © 1999-2019 ImageMagick Studio LLC
    License: https://imagemagick.org/script/license.php
    Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
    Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zlib

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
