### ISSUE TITLE
Operator `-threshold` fails on PNG with `lineargray` color space.

### ISSUE THREAD

**Issue by mfwitten** [ImageMagick/ImageMagick#1682]
The `-threshold` operator fails for a PNG input with `lineargray` as its color space; consider this POSIX shell code:

    magick -size 1x1 canvas:'gray(50%)' -set colorspace LinearGray \
      -write txt: \
      -write pixel.miff \
      pixel.png

    for format in miff png; do
      printf '%s %s:\n' ------------- "$format"
      magick pixel."$format" -write txt: -threshold 25% txt:
    done

which produces this output:

    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (32767.5)  #800080008000  lineargray(50%)
    ------------- miff:
    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (32767.5)  #800080008000  lineargray(50%)
    # ImageMagick pixel enumeration: 1,1,65535,srgb
    0,0: (65535,65535,65535)  #FFFFFFFFFFFF  white
    ------------- png:
    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (32767)  #7FFF7FFF7FFF  lineargray(49.9992%)
    # ImageMagick pixel enumeration: 1,1,65535,srgb
    0,0: (0,0,0)  #000000000000  black

As you can see, the "same" image produces different results depending on the input format; the MIFF image properly goes to white, while the PNG image erroneously goes to black.

The problem goes away in a supposedly non-linear `gray` color space; this:

    magick -size 1x1 canvas:'gray(50%)' \
      -write txt: \
      -write pixel.miff \
      pixel.png

    for format in miff png; do
      printf '%s %s:\n' ------------- "$format"
      magick pixel."$format" -write txt: -threshold 25% txt:
    done

produces this:

    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (32767.5)  #800080008000  gray(50%)
    ------------- miff:
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (32767.5)  #800080008000  gray(50%)
    # ImageMagick pixel enumeration: 1,1,65535,srgb
    0,0: (65535,65535,65535)  #FFFFFFFFFFFF  white
    ------------- png:
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (32767)  #7FFF7FFF7FFF  gray(49.9992%)
    # ImageMagick pixel enumeration: 1,1,65535,srgb
    0,0: (65535,65535,65535)  #FFFFFFFFFFFF  white

Indeed, using a "50%" as the threshold produces black for both, while "49%" produces white for both.

Version:

    $ magick -version
    Version: ImageMagick 7.0.8-53 Q16 i686 2019-07-15 https://imagemagick.org
    Copyright: © 1999-2019 ImageMagick Studio LLC
    License: https://imagemagick.org/script/license.php
    Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
    Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zlib

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
