### ISSUE TITLE
`-threshold` unexpectedly produces color `sRGB` image

### ISSUE THREAD

**Issue by mfwitten** [ImageMagick/ImageMagick#1683]
The `-threshold` operator unexpectedly produces a color image in the `sRGB` color space.

GIven this:

    magick -size 1x1 canvas:'gray(50%)' -colorspace LinearGray \
        \( +clone -threshold 25% \) txt:

I expect the following output:\*

    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (32767.5)  #800080008000  lineargray(50%)
    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (65535)  #FFFFFFFFFFFF  lineargray(255)

but get this instead:

    # ImageMagick pixel enumeration: 1,1,65535,lineargray
    0,0: (32767.5)  #800080008000  lineargray(50%)
    # ImageMagick pixel enumeration: 1,1,65535,srgb
    0,0: (65535,65535,65535)  #FFFFFFFFFFFF  white

Version:

    $ magick -version
    Version: ImageMagick 7.0.8-53 Q16 i686 2019-07-15 https://imagemagick.org
    Copyright: © 1999-2019 ImageMagick Studio LLC
    License: https://imagemagick.org/script/license.php
    Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
    Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zlib

&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  

--------------------------

\* Actually, I expect `lineargray(100%)`, not `lineargray(255)`. And, as pointed out in issue #1681, `lineargray(x)` fails for `x != 0`.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
