### ISSUE TITLE
`-draw` primitives (especially `color`) create alpha channel unnecesarily

### ISSUE THREAD

**Issue by mfwitten** [ImageMagick/ImageMagick#1685]
Consider this POSIX shell function:

    draw()
    {
      magick -size 1x1 canvas:'gray(100%)'          \
        \( +clone -fill 'gray(100%)' -draw "$@" \)  \
        txt:;
    }

As you can see in the following, drawing a single, white, opaque pixel over a single, white, opaque pixel produces an alpha channel implicitly.

    $ draw 'point 0,0' 
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (65535)  #FFFFFFFFFFFF  gray(255)
    # ImageMagick pixel enumeration: 1,1,65535,graya
    0,0: (65535,65535)  #FFFFFFFFFFFFFFFF  graya(255,1)

**Inexplicably, the same happens with the `color` fill primitive:**

    $ draw 'color 0,0 point' 
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (65535)  #FFFFFFFFFFFF  gray(255)
    # ImageMagick pixel enumeration: 1,1,65535,graya
    0,0: (65535,65535)  #FFFFFFFFFFFFFFFF  graya(255,1)

Given that an alpha channel is unnecessary for either operation (especially the `color` fill primitive), this implicit creation of an alpha channel seems improper (or at least inefficient), and is presumably some kind of leaky abstraction of the underlying algorithm.

* At the very least, the documentation should explain that an alpha channel will be created, and that the user must remove the alpha channel explicitly.

* Perhaps, these operations should create an alpha channel only if one is required.

* Perhaps, it would be worthwhile to allow the user to specify more explicitly how alpha calculations should be performed (e.g., maybe there could be an implicit flattening per pixel calculation, thereby obviating the need for an alpha channel).

Version:

    $ magick -version
    Version: ImageMagick 7.0.8-53 Q16 i686 2019-07-15 https://imagemagick.org
    Copyright: © 1999-2019 ImageMagick Studio LLC
    License: https://imagemagick.org/script/license.php
    Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
    Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zlib

**Comment by urban-warrior** [comment]
Drawing requires an alpha channel.  If none is available, an all opaque alpha channel is implicitly created.  We will update the docs to reflect this.  In the mean-time, remove the alpha channel after the draw with `-alpha off`.
