### ISSUE TITLE
`-draw` black pixel results in non-black pixel (when HDRI enabled)

### ISSUE THREAD

**Issue by mfwitten** [ImageMagick/ImageMagick#1686]
Using `-draw` to paint a black pixel atop a non-black pixel results in a pixel that is not actually black; this is presumably only a problem when [HDRI](https://imagemagick.org/script/high-dynamic-range.php) is enabled.

Consider this POSIX shell function:

      draw()
      {
        initial_color=$1; shift
        magick -size 1x1 canvas:"gray($initial_color)"    \
          \( +clone -fill 'gray(0)' -draw "$@" \)         \
          txt:
      }

With that function, the following creates a single black pixel and then paints another black pixel atop it:

    $ draw 0 'point 0,0'
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (0)  #000000000000  gray(0)
    # ImageMagick pixel enumeration: 1,1,65535,graya
    0,0: (0,65535)  #000000000000FFFF  graya(0,1)

This is as expected (ignoring the unnecessary creation of an alpha channel, as reported in issue #1685).

However, consider what happens when the pixel is initially non-zero (not black):

    $ draw 1 'point 0,0'
    # ImageMagick pixel enumeration: 1,1,65535,gray
    0,0: (257)  #010101010101  gray(1)
    # ImageMagick pixel enumeration: 1,1,65535,graya
    0,0: (1.3932e-17,65535)  #000000000000FFFF  graya(0,1)

The pixel has taken on a non-zero (albeit extremely tiny) floating point number! Here is a function that draws a selection of examples:

    $ draw_multiple()
      (
        for v in 0 1 23% 48% 76% 90% 100%; do
          draw "$v" "$@" | awk '/^[0-9]/ {print $1 $2}'
          printf '%s\n' ----------------
        done
      )

Then:

    $ draw_multiple 'point 0,0'
    0,0:(0)
    0,0:(0,65535)
    ----------------
    0,0:(257)
    0,0:(1.3932e-17,65535)
    ----------------
    0,0:(15073.1)
    0,0:(8.17112e-16,65535)
    ----------------
    0,0:(31456.8)
    0,0:(1.70528e-15,65535)
    ----------------
    0,0:(49806.6)
    0,0:(2.70002e-15,65535)
    ----------------
    0,0:(58981.5)
    0,0:(3.19739e-15,65535)
    ----------------
    0,0:(65535)
    0,0:(3.55266e-15,65535)
    ----------------

The `color` fill primitive does *not* exhibit this problem:

    $ draw_multiple 'color 0,0 point'
    0,0:(0)
    0,0:(0,65535)
    ----------------
    0,0:(257)
    0,0:(0,65535)
    ----------------
    0,0:(15073.1)
    0,0:(0,65535)
    ----------------
    0,0:(31456.8)
    0,0:(0,65535)
    ----------------
    0,0:(49806.6)
    0,0:(0,65535)
    ----------------
    0,0:(58981.5)
    0,0:(0,65535)
    ----------------
    0,0:(65535)
    0,0:(0,65535)
    ----------------

Version:

    $ magick -version
    Version: ImageMagick 7.0.8-53 Q16 i686 2019-07-15 https://imagemagick.org
    Copyright: © 1999-2019 ImageMagick Studio LLC
    License: https://imagemagick.org/script/license.php
    Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
    Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zlib

**Comment by urban-warrior** [comment]
We're cannot reproduce this problem.  We're executing ImageMagick 7.0.8-63 with HDRI enabled.
