### ISSUE TITLE
The `-draw` primitive `matte` is broken

### ISSUE THREAD

**Issue by mfwitten** [ImageMagick/ImageMagick#1687]
ImageMagick's own example usage of the `matte` drawing primitive does not (or no longer) works.

[At this point](https://www.imagemagick.org/Usage/draw/#matte) in the documentation:

    https://www.imagemagick.org/Usage/draw/#matte

there is the following example:

> convert color_test.png -fill none -draw 'matte 30,20 floodfill' matte_floodfill.png

However, it does not work:

    $ wget https://www.imagemagick.org/Usage/draw/color_test.png
    $ convert color_test.png -fill none -draw 'matte 30,20 floodfill' matte_floodfill.png
    convert: non-conforming drawing primitive definition `30' @ error/draw.c/RenderMVGContent/4395.

Indeed, the `matte` primitive seems to have trouble parsing the coordinates:

    $ matte() { magick -size 5x1 canvas: -draw "matte $1,0 point" txt:; }
    $ for x in 0 1 2 3 4; do matte "$x"; done
    magick: non-conforming drawing primitive definition `0' @ error/draw.c/RenderMVGContent/4395.
    magick: non-conforming drawing primitive definition `1' @ error/draw.c/RenderMVGContent/4395.
    magick: non-conforming drawing primitive definition `2' @ error/draw.c/RenderMVGContent/4395.
    magick: non-conforming drawing primitive definition `3' @ error/draw.c/RenderMVGContent/4395.
    magick: non-conforming drawing primitive definition `4' @ error/draw.c/RenderMVGContent/4395.

Version:

    $ magick -version
    Version: ImageMagick 7.0.8-53 Q16 i686 2019-07-15 https://imagemagick.org
    Copyright: © 1999-2019 ImageMagick Studio LLC
    License: https://imagemagick.org/script/license.php
    Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
    Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zlib

**Comment by fmw42** [comment]
In IM 7, use magick not convert. Also replace matte with alpha. This works fine for me on IM 7.0.8.63 Q16 Mac OSX.

`magick color_test.png -fill none -draw 'alpha 30,20 floodfill' matte_floodfill.png`

**Comment by mfwitten** [comment]
Thanks for the explanation.
