### ISSUE TITLE
Upgrade to ImageMagick-7.0.8-63 at Ubuntu 18.04.3 LTS failed

### ISSUE THREAD

**Issue by Elmit2015** [ImageMagick/ImageMagick#1688]
I tried to upgrade with following steps:
```
sudo apt-get update
sudo apt-get install build-essential checkinstall libx11-dev libxext-dev zlib1g-dev libpng12-dev libjpeg-dev libfreetype6-dev libxml2-dev
```

Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libpng12-dev' has no installation candidate

```
cd /opt
sudo wget http://www.imagemagick.org/download/ImageMagick.tar.gz
sudo tar -xvzf ImageMagick.tar.gz
cd ImageMagick-7.0.8-63/
sudo touch configure
sudo ./configure
sudo make
```
Warning:
  CC       coders/MagickCore_libMagickCore_7_Q16HDRI_la-pdf.lo
coders/pdf.c: In function ‘ReadPDFImage’:
coders/pdf.c:544:3: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
   (void) write(file," ",1);
   ^~~~~~~~~~~~~~~~~~~~~~~~

`sudo make install`
Warnings:
libtool: warning: relinking 'MagickWand/libMagickWand-7.Q16HDRI.la'
libtool: warning: relinking 'Magick++/lib/libMagick++-7.Q16HDRI.la'

```
sudo ldconfig /usr/local/lib
sudo make check
```
FAIL: tests/wandtest.tap 1
FAIL: Magick++/demo/demos.tap 6

============================================================================
Testsuite summary for ImageMagick 7.0.8
============================================================================
# TOTAL: 86
# PASS:  84
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/ImageMagick/ImageMagick/issues
============================================================================
Makefile:11873: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/opt/ImageMagick-7.0.8-63'
Makefile:11979: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/opt/ImageMagick-7.0.8-63'
Makefile:12194: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/opt/ImageMagick-7.0.8-63'
Makefile:12197: recipe for target 'check' failed
make: *** [check] Error 2

You can see the log file here: https://bc.elmit.com/john/test-suit.log

How to fix?

**Comment by urban-warrior** [comment]
We got a 404 for https://bc.elmit.com/john/test-suit.log.

**Comment by Elmit2015** [comment]
sorry, spelling error:
https://bc.elmit.com/john/test-suit.log
