### ISSUE TITLE
what is the difference between coder and module in policy.xml

### ISSUE THREAD

**Issue by rebirthwyw** [ImageMagick/ImageMagick#1689]
i can't find explanation of module domain in policy.xml,does it contain both coder and filter?

**Comment by urban-warrior** [comment]
Coders are static image read/write methods whereas modules are dynamic (loaded @ run time).  When it comes to security its important to be exacting, as these are two different subsystems, we have two different policy domains.   The module policy allows or denies dynamic modules at run-time.  It also allow or denies static coders from registering (if its not registered, you can't read/write the image format).  Coder policies are queried on-demand.   For example, you attempt to read an EPS image.  The coder polices are checked at that moment.  If EPS is not allowed, an exception is thrown.
