### ISSUE TITLE
AIX  -  recipe for target 'test-suite.log' failed

### ISSUE THREAD

**Issue by scorour** [ImageMagick/ImageMagick#169]
Hi,
I am trying to build from source on AIX 6.1.9, doing the testsuite, it fails on 1 and errors on 3, log file attached, any help would be appreciated.

The fail is with:
Failed to read file /tmp/ImageMagick-6.9.3-7/ImageMagick-6.9.3-7/_build/sub/../../Magick++/tests/test_image.miff for input!
not ok
FAIL: Magick++/tests/tests.tap 11

I have checked and the file does exist, so not sure about "failed to read file...."

Many thanks.
============================================================================
Testsuite summary for ImageMagick 6.9.3
============================================================================
# TOTAL: 76
# PASS:  72
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 3
============================================================================
See ./test-suite.log
Please report to https://github.com/ImageMagick/ImageMagick/issues
============================================================================
Makefile:10922: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/tmp/ImageMagick-6.9.3-7/ImageMagick-6.9.3-7/_build/sub'
Makefile:11028: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/tmp/ImageMagick-6.9.3-7/ImageMagick-6.9.3-7/_build/sub'
Makefile:11240: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/tmp/ImageMagick-6.9.3-7/ImageMagick-6.9.3-7/_build/sub'
Makefile:11243: recipe for target 'check' failed
make[1]: *** [check] Error 2
make[1]: Leaving directory '/tmp/ImageMagick-6.9.3-7/ImageMagick-6.9.3-7/_build/sub'
Makefile:11158: recipe for target 'distcheck' failed
make: *** [distcheck] Error 1
root@sysncl3adm /tmp/ImageMagick-6.9.3-7 #

[test-suite.txt](https://github.com/ImageMagick/ImageMagick/files/216150/test-suite.txt)

**Comment by dlemstra** [comment]
Can you reproduce this issue with the latest release?

**Comment by louislau95** [comment]
![image](https://user-images.githubusercontent.com/48686853/54565161-7682fb00-4a08-11e9-9fd5-3320961452df.png)
I also have same problem, how to solve it?

**Comment by urban-warrior** [comment]
Take a look at test-suite.log and identify which unit test is failing.  You can also look at the particular log of the test that fails for additional detail.  Knowing which unit test failed will help use identify why the test failed.

**Comment by ojde** [comment]
Same here.
Debian Stretch

> ============================================================================
See ./test-suite.log
Please report to https://github.com/ImageMagick/ImageMagick/issues
============================================================================
Makefile:11648: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/usr/src/packages/imagick/ImageMagick-7.0.8-39'
Makefile:11754: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/usr/src/packages/imagick/ImageMagick-7.0.8-39'
Makefile:11969: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/usr/src/packages/imagick/ImageMagick-7.0.8-39'
Makefile:11972: recipe for target 'check' failed
make: *** [check] Error 2

FAILS had common theme around fonts
> FAIL: tests/wandtest
====================
tests/wandtest.c main 5323 non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4407
...
Caught exception: montageImages: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1383
not ok
FAIL: Magick++/tests/tests.tap 10
...
Caught exception: button: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1383
not ok
FAIL: Magick++/demo/demos.tap 2nnn


The last one was repeated several times

Cause for failures:
\<typemap\>  \</typemap\> in /usr/local/etc/ImageMagick/type.xml was empty
After populating it with fonts installed on the system such as

    <type
     format="ttf"
     name="DejaVuSansMono"
     fullname="DejaVu Sans Mono"
     family="DejaVu Sans Mono"
     glyphs="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
    />
    <type
     format="ttf"
     name="DejaVuSerifB"
     fullname="DejaVu Serif Bold"
     family="DejaVu Serif"
     glyphs="/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf"
    />

and creating 'redirects' for that helvetica font not found

    <type
       format="ttf"
       name="Helvetica"
       fullname="Helvetica Sans"
       family="Helvetica Sans"
       glyphs="/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"
    />

    <type
       format="ttf"
       name="HelveticaB"
       fullname="Helvetica Sans Bold"
       family="Helvetica Sans"
       glyphs="/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
    />

All tests passed and no recipes failed.

====

There's a script **imagick_type_gen.pl** available [here](https://www.imagemagick.org/discourse-server/viewtopic.php?t=24901) which colects available fonts and writes the xml list. It needs _locate_.

$> apt-get install locate
$> updatedb
$> ./imagick_type_gen.pl > fontlist.xml
