### ISSUE TITLE
No decode delegate for this image format issue in AIX build

### ISSUE THREAD

**Issue by ayappanec** [ImageMagick/ImageMagick#1690]
I compiled ImageMagick 7.0.8-61 in AIX 6.1 with jpeg,png., etc and other supports. 
But when the below command. it fails with "no decode delegate for this image format" error.
convert testimg.jpg -negate testimg_mod.jpg
convert: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/556.
convert: no images defined `testimg_mod.jpg' @ error/convert.c/ConvertImageCommand/3273.

But it has the support for jpeg. "convert -list configure" shows it 

DELEGATES             bzlib fontconfig freetype jbig jng jpeg ltdl lzma png tiff x xml zlib

Attaching the entire output of "convert -list configure" here. 
[configure_output.txt](https://github.com/ImageMagick/ImageMagick/files/3573784/configure_output.txt)

**Comment by urban-warrior** [comment]
You may need to trace the system calls (e.g. strace) to see if there is a permission or other problem dynamically loading the JPEG delegate library.  You can also `ldd` the convert utility to see if its pointing to the correct JPEG delegate library.

**Comment by ayappanec** [comment]
Used "truss" command (similar to strace in linux ) and figure out i am not shipping the *.la files.
And also in AIX, the coders directory has shared libraries (*.so) contained in the archives (*.a). So had to change the Itmain.sh file to have dlname something like "jpeg.a(jpeg.so)" and built it again.
With these changes , it's working now. 
Thanks for the information.
