### ISSUE TITLE
Issue while converting PDF to PNG

### ISSUE THREAD

**Issue by ashokbommareddy2015** [ImageMagick/ImageMagick#1691]
We are using the ImageMagic tool to view PDF files.

Issue is :  We are using custom font as logo for a few of our documents. Initially we create a word document with custom font as logo and generate the PDF files. Imagemagick converts the PDF file to PNG but the logo is being rendered as letter "K" and not with the correct logo.

We are using -  Magick.NET - 7.14.2 Version 

Could you please advise on  this issue?

**Comment by urban-warrior** [comment]
We need to reproduce the problem before we can comment.  Post a link to your PDF source, the resulting rendering Magick.Net produces, and a rendering of logo.
