### ISSUE TITLE
Convert DCM to JPG Error

### ISSUE THREAD

**Issue by jejus52** [ImageMagick/ImageMagick#1692]
Hi.
I am contacting you because there is a problem converting the dicom file.
In the window10 environment, converting the dicom file to IMDisplay was converted normally.
Attempts to convert the same dicom file in a Linux environment fail with a ReadDCMImage error. Make sure ImageMagic is installed incorrectly in your Linux environment.
I will attach the error capture screen, so please contact me if you need a dcm file.
Window10 and Linux ImageMagick versions are the same as 7.0.8-60.

![20190903_095020](https://user-images.githubusercontent.com/54921514/64305492-8ac4af80-cfca-11e9-868a-38b4e27fd670.png)

![20190903_095832](https://user-images.githubusercontent.com/54921514/64305505-8ef0cd00-cfca-11e9-8069-03f32ced2fad.png)

**Comment by fmw42** [comment]
Post a your DCM file so the developers can test with it or review its properties.

**Comment by jejus52** [comment]
> Post a your DCM file so the developers can test with it or review its properties.

I have attached a DCM file. Please check.

**Comment by fmw42** [comment]
Sorry, I overlooked the link at the bottom. I get the same message when doing 

`magick DCM:I00038608088.dcm x.jpg`

on IM 7.0.8.63 Q16 HDRI Mac OSX Sierra.

Note that with IM 7 use magick not convert.

**Comment by jejus52** [comment]
> Sorry, I overlooked the link at the bottom. I get the same message when doing
> magick DCM:I00038608088.dcm x.jpg
> on IM 7.0.8.63 Q16 HDRI Mac OSX Sierra.
> Note that with IM 7 use magick not convert.
> So one of the developers will need to review this. Perhaps your file was not written fully compliant in some way, such that it works in Windows, but not Unix.

So if you put an issue on the github here, does the developer ImageMagic identify the bug? Please check.

**Comment by fmw42** [comment]
What are you asking? It is not clear to me. The ImageMagick developers will monitor this forum and respond to the issue when they have time.

**Comment by dlemstra** [comment]
Your DCM file is not a DICOM file but a JP2 file and to read that you will OpenJPEG library installed as a delegate. Under Windows there is support for this format and that is why the file is recognized as a JP2 file and loaded into the image viewer. But under Linux you don't have OpenJPEG installed as a delegate.

**Comment by jejus52** [comment]
> Your DCM file is not a DICOM file but a JP2 file and to read that you will OpenJPEG library installed as a delegate. Under Windows there is support for this format and that is why the file is recognized as a JP2 file and loaded into the image viewer. But under Linux you don't have OpenJPEG installed as a delegate.



If so, is there any way to install OpenJPEG on Linux version? I've tried it a few times but it doesn't apply to the delegate.
