### ISSUE TITLE
ImageMagick 7.0.8-63 Q16 x64 2019-08-31 installs older FFMpeg 3.4 by default

### ISSUE THREAD

**Issue by jimmckeeth** [ImageMagick/ImageMagick#1693]
### Prerequisites

- [ x ] I have written a descriptive issue title
- [ x ] I have verified that I am using the latest version of ImageMagick
- [ x ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I previously had FFmpeg 4.2 installed on my Windows computer. I installed ImageMagick 7.0.8-63 Q16 and it includes FFmpeg 3.4, which is older and doesn't support palettegen correctly. Unfortunately ImageMagick got ahead of FFmpeg on the path and I spent way too much time trying to figure out why palettegen stopped working.

### Steps to Reproduce

1. Install FFmpeg 4.2
2. Install ImageMagick 7.0.8-63 Q16 with the default options
3. Now FFmpeg 3.4 is on the path ahead of FFmpeg 4.2

### Suggested Resolutions

1. Check to see if FFmpeg is installed before installing an older version
2. Update the installer to include the latest version of FFmpeg
3. Don't make installing an older version of FFmpeg the default
4. If ImageMagick needs the older version of FFmpeg then put it in a sub-directory that isn't on the path

### System Configuration
Windows 10 64-bit 
Version 10.0.18362 Build 18362
ImageMagick 7.0.8-63 Q16 x64 2019-08-31

**Comment by urban-warrior** [comment]
Soon, ImageMagick will ask the user whether to install ffmpeg.  If checked, the installer will grab the latest release of ffmpeg.
