### ISSUE TITLE
`-extent` unexpectedly converts to `sRGB` and destroys color count

### ISSUE THREAD

**Issue by mfwitten** [ImageMagick/ImageMagick#1694]
The `-extent` operator unexpectedly converts an image's colorspace to `sRGB` (and apparently destroys information about the number of colors):

    $ magick -size 1x1 canvas:'gray(50%)' +write info:  \
             -colors 1 +write info:                     \
             -extent 1x1 +write info:                   \
             -type Palette +write info:                 \
             -extent 1x1 info:
    canvas:gray(50%) CANVAS 1x1 1x1+0+0 16-bit Gray 0.000u 0:00.000
    canvas:gray(50%) CANVAS 1x1 1x1+0+0 16-bit Gray 1c 0.000u 0:00.000
    canvas:gray(50%) CANVAS 1x1 1x1+0+0 16-bit sRGB 0.000u 0:00.000
    canvas:gray(50%) CANVAS 1x1 1x1+0+0 16-bit Palette Gray 1c 0.000u 0:00.000
    canvas:gray(50%) CANVAS 1x1 1x1+0+0 16-bit Palette sRGB 0.000u 0:00.000

This is perhaps related to issue #1683:

* `-threshold` unexpectedly produces color `sRGB` image 

Version:

    $ magick -version
    Version: ImageMagick 7.0.8-53 Q16 i686 2019-07-15 https://imagemagick.org
    Copyright: © 1999-2019 ImageMagick Studio LLC
    License: https://imagemagick.org/script/license.php
    Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5)
    Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zlib

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
