### ISSUE TITLE
Assertion failure when converting to SVG

### ISSUE THREAD

**Issue by purpledrosophila** [ImageMagick/ImageMagick#1695]
### Prerequisites

- [x ] I have written a descriptive issue title
- [x ] I have verified that I am using the latest version of ImageMagick
- [ x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I cannot convert any image formats to SVG using the latest version of ImageMagick. With any file I try, I get a core dump:

```
convert: MagickCore/blob.c:1554: WriteBlobStream: Assertion `image->blob->type != UndefinedStream' failed.
Aborted (core dumped)
```

### Steps to Reproduce
1. Create an xcf, png, ps, or jpg
2. Try to convert to svg with: convert [filename] test.svg

### System Configuration

- ImageMagick version: 7.0.8-64
- Environment (Operating system, version and so on): Windows subsystem for Linux, Ubuntu 18.04
- Additional information: Have librsvg installed; cairo, pango, and rsvg are all listed as delegates

EDIT: I compared the lines between ImageMagick 6 and ImageMagick 7; wherever the problem is, it doesn't look like it's inside the method that calls this assertion, since the code lines leading up to it are identical. The method is WriteBlobStream, if that helps.

**Comment by urban-warrior** [comment]
hanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by purpledrosophila** [comment]
Hi all, I wanted to check in if you don't mind. Has a fix been submitted for this yet, and will it be available in the next release? If not, do you have an ETA? I need this capability for work, and my boss has requested an update. Thanks!

**Comment by urban-warrior** [comment]
Fixed in the latest ImageMagick release, 7.0.8-65.

**Comment by purpledrosophila** [comment]
That's awesome, thank you! Will 7.0.8-65 be on the release page soon?

**Comment by urban-warrior** [comment]
Refresh your browser cache.  The release is posted on the website as of this morning.

**Comment by purpledrosophila** [comment]
Thank you; the conversion completes now without crashing. I'm getting an unexpected result, though. I used to be able to convert png color images to svg with ImageMagick, and now I only get a black and white image that's really poor quality with a lot missing. Same thing with converting from XCF. Has something changed in terms of internal processing? When I try to convert from xcf to svg, I get a really low quality image in black and white with most of it missing, same thing when I try to convert from png to svg.

**Comment by purpledrosophila** [comment]
Never mind, I realized I was doing something wrong. Thank you!
