### ISSUE TITLE
ImageMagick crashed if add page range as [0]

### ISSUE THREAD

**Issue by lumpchen** [ImageMagick/ImageMagick#1697]
[1568192120225.pdf](https://github.com/ImageMagick/ImageMagick/files/3600258/1568192120225.pdf)

### Description
ImageMagick crached if add page range [0].
![issue](https://user-images.githubusercontent.com/2239287/64690156-510c1100-d4c2-11e9-89e5-26064e29a23a.png)

### Steps to Reproduce
Good if run as:
identify C:\1568192120225.pdf
Crash if run as:
identify C:\1568192120225.pdf[0]

### System Configuration
Windows 

- ImageMagick version:
Version: ImageMagick 7.0.7-24 Q16 x86 2018-02-25 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC HDRI
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr openexr pangocairo png ps raw rsvg tiff webp xml zlib

**Comment by dlemstra** [comment]
Can you upgrade to the latest version and test if you can still reproduce this issue?

**Comment by lumpchen** [comment]
> Can you upgrade to the latest version and test if you can still reproduce this issue?
Yes, I can reproduce this issue on latest version:

Version: ImageMagick 7.0.8-64 Q16 x64 2019-09-08 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC HDRI OpenCL
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg
 tiff webp xml zlib

**Comment by lumpchen** [comment]
I tested more cases about this issue, and found the issue is related to embedded PNG image. If the image is not on the first page, then no problem here. The problem is not happened on first page, in fact, it can be any page with PNG images.

So the problem should be with:
1. Have PNG image on the page N.
2. Run command with page range parameter as [N] for processing the page N

[no_crash_issue.pdf](https://github.com/ImageMagick/ImageMagick/files/3604120/no_crash_issue.pdf)

PS C:\dev\imagemagick\ImageMagick-7.0.8-64-portable-Q16-x64> **.\identify.exe C:\dev\xPression\temp\no_crash_issue.pdf[0]**
C:\dev\xPression\temp\no_crash_issue.pdf[0]=>C:\dev\xPression\temp\no_crash_issue.pdf PDF 612x792 612x792+0+0 16-bit sRGB 6582B 0.000u 0:00.000

PS C:\dev\imagemagick\ImageMagick-7.0.8-64-portable-Q16-x64> **.\identify.exe C:\dev\xPression\temp\no_crash_issue.pdf[1]**
identify.exe: FailedToExecuteCommand `"C:/dev/xPression/gs/bin/gswin32c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -dFirstPage=2 -dLastPage=2"-sOutputFile=C:/Users/mikel/AppData/Local/Temp/magick-22808fWGznKqepGJV%d" "-fC:/Users/mikel/AppData/Local/Temp/magick-22808ZsCcOJGvTXUo""-fC:/Users/mikel/AppData/Local/Temp/magick-22808bwYvXYZs_c7E"' (-1073741819) @ error/delegate.c/ExternalDelegateCommand/478.

**Comment by dlemstra** [comment]
I don't understand what you are telling us. The `no_crash_issue.pdf` also crashes? And have you tried changing your Ghostscript version?

**Comment by lumpchen** [comment]
> I don't understand what you are telling us. The `no_crash_issue.pdf` also crashes? And have you tried changing your Ghostscript version?

> The `no_crash_issue.pdf` also crashes?

Sorry for the confused file name, but yes, this PDF will still make ImageMagick crash. I rearrange  the problem description:

Reproduce steps: 
1. Download PDF file has issue:  [crash_issue.pdf](https://github.com/ImageMagick/ImageMagick/files/3614618/crash_issue.pdf)
 
 2. Run command: **identify.exe C:\crash_issue.pdf[1]**, then IM crashed.

3. Run command **identify.exe C:\crash_issue.pdf** or any other pages like **identify.exe C:\crash_issue.pdf[0]**, then IM works as expected.

> And have you tried changing your Ghostscript version?

Yes, I've updated to latest version of GS(9.2.7/win64bit). I also updated IM to latest version (7.0.8-64 Q16 x64 2019-09-08/wind64bit).

Thanks for your patience!

**Comment by urban-warrior** [comment]
Try the latest ImageMagick release 7.0.8-65.  If that fails for you, let us know and we'll dedicate resources to trace and fix the source of the bug.

**Comment by urban-warrior** [comment]
We cannot reproduce the problem you reported.  We ran all your examples under Windows 10, IM 7.0.8-67, and GS 9.2.7/win64bit.  Your commands completed without complaint or crash.

**Comment by lumpchen** [comment]
No crash issue on 7.0.8-67, will try to upgrade to latest version. 
Thank you all!
