### ISSUE TITLE
how do i get the data of Image?

### ISSUE THREAD

**Issue by shangjiuliu** [ImageMagick/ImageMagick#170]
Image image("wmark_image.png");
how do i get the data of image?

i can do like this:
Blob ret;
image.write(&ret); 
ret.data();
is there another way get the data of watermark?
can i get the data directly from image?

**Comment by dlemstra** [comment]
Can you clarify what you mean by data?

**Comment by dlemstra** [comment]
@shangjiuliu, did you still need our help or can we close this issue?

**Comment by shangjiuliu** [comment]
sorry.
the data means the binary data of image.
I get it like this:
Blob ret;
image.write(&ret); 
data = ret.data();

but it take so much time,so i want find another way
