### ISSUE TITLE
Flattening images with PerlMagick

### ISSUE THREAD

**Issue by purpledrosophila** [ImageMagick/ImageMagick#1700]
### Prerequisites

- [x ] I have written a descriptive issue title
- [ x] I have verified that I am using the latest version of ImageMagick
- [ x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

Hi all,

This is actually 2 different questions; as far as I know there isn't technically a bug here, but we could potentially make the case for a "documentation" bug.

1. Despite looking through the documentation and doing lots of Googling, I can't figure out how to flatten a PNG image in PerlMagick. I'm converting an image that has multiple layers into a PNG, and I need the PNG to be all one layer when I write it.

2. Second, since I couldn't find this in the documentation, may I possibly help improve the docs a bit? I'm a professional technical writer, and I feel like I could be of use.

Thanks!

**Comment by urban-warrior** [comment]
Find the website source @ https://github.com/ImageMagick/Website.  Make your mods and post it as a pull request @ https://github.com/ImageMagick/Website/pulls.

Use `$image->Flatten()` to first flatten your image layers and then write the result in the PNG format.

**Comment by purpledrosophila** [comment]
Thank you,
I have tried using $image->Flatten multiple ways, and I'm still getting multiple separate PNGs written for each layer of the image, without respecting transparency. I have tried simply using the Flatten call, and also getting each image layer manually and passing it to Flatten as an array, like this:

```
$im = Image:Magick->new;
$im->Read(filename=>$in_file);
$im->Flatten();
$im->Write('png:' . $png);
```

```
$max_layers = 256;
@layers;
$im = Image:Magick->new;
for ($i = 0; $i <= $max_layers; $i++) {
    if ($im->[$i]) { push(@layers, $im->[$i]); }
    else { last; }
}
$im->Read(filename=>$in_file);
$im->Flatten(@layers);
$im->Write('png:' . $png);
```

When these calls start, the input file exists, the PNG file does not. (I was writing that code manually; if it doesn't compile I apologize. It should work though.)

The output for both of these programs is multiple files named $png, with a dash followed by the layer number, rather than one file called $png.

Is there something I'm missing here?

**Comment by urban-warrior** [comment]
See https://imagemagick.org/script/perl-magick.php:

The Flatten() method flattens a set of images and returns it. For example,
```
$p = $images->Flatten(background=>'none');
$p->Write('flatten.png');
```
The sequence of images is replaced by a single image created by composing each image after the first over the first image.

**Comment by purpledrosophila** [comment]
Interesting, I'm still getting multiple images, one for each layer. I am getting a flattened image now as well, but I'm still also getting an image written for every layer. Is that the expected behavior? If so, it wasn't clear to me from the docs.

```
my $im = Image::Magick->new;
$im->Read(filename=>$in_file);
$im->Flatten(background=>'none');
$im->Write("$out_dir/$png");
```

**Comment by dlemstra** [comment]
@purpledrosophila You will need to use the return value of the `Flatten` method:

```perl
# OLD
$im->Flatten(background=>'none');
$im->Write("$out_dir/$png");

# NEW
$resultImage = $im->Flatten(background=>'none');
$resultImage->Write("$out_dir/$png");
```

**Comment by purpledrosophila** [comment]
Thank you so much! :)
