### ISSUE TITLE
fx while() condition never matched

### ISSUE THREAD

**Issue by capotti** [ImageMagick/ImageMagick#1701]
### Prerequisites
Example:
magick rose: -format "%[fx:ii=10;while(ii<10,debug(ii);ii=ii+1)]" info:-

### Description
endless loop, ii is incremented correctly, ii < 10 does not match

### Steps to Reproduce
see example

### System Configuration
osx 

- ImageMagick version: ImageMagick 7.0.8-59 Q16 x86_64 2019-08-05
- Environment (Operating system, version and so on): OSX 10.14.06
- Additional information: none

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
