### ISSUE TITLE
Heif (High Efficiency Image File Format) IOS images turn purple

### ISSUE THREAD

**Issue by Sicos1977** [ImageMagick/ImageMagick#1703]
### Description
When converting Heif JPEG (IOS) images to PDF they turn purple

### Steps to Reproduce
Convert the attached image to PDF. The image in the PDF is purple

### System Configuration
Windows 2012 R2 server

- ImageMagick version:
Magick.NET-Q16-AnyCPU 7.14.1

**Comment by Sicos1977** [comment]
Well it seems that GraphicsMagick is working fine. It's Ghostscript that is turning the image purple

**Comment by fmw42** [comment]
This is an ImageMagick forum, not one for GraphicsMagick. They are not maintained by the same organizations.
