### ISSUE TITLE
line endings renedered as empty boxes in SVGs since 1ececd4e

### ISSUE THREAD

**Issue by rcanavan** [ImageMagick/ImageMagick#1704]
The SVG from #1231 is broken again (tested with 7.0.8-66 and master). This time, newlines are rendered as empty boxes:

![newlines-as-boxes](https://user-images.githubusercontent.com/4719149/65610362-7f551a80-dfb1-11e9-9af2-cd3f8f09c55e.png)
 
The commit that caused this is https://github.com/ImageMagick/ImageMagick/commit/1ececd4ee57d37f64ba2d92384bbadde3d875ee9

**Comment by urban-warrior** [comment]
hanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by rcanavan** [comment]
Fix confirmed. Thanks.
