### ISSUE TITLE
Problem in conversion of RGB to png

### ISSUE THREAD

**Issue by Prasad454** [ImageMagick/ImageMagick#1710]
Hi, 

I am capturing an image with a image sensor and trying to convert the caprtured image from rgb to png format, but i see the png format image after converting is devided into 2 parts. The 1st part again devided into 2 vertical parts in Red and Yellow colors, the second part is completely black. 1st part is having the required image.

Below is the command used to capture the image from v4l
v4l2-ctl --device /dev/video0 --stream-mmap --stream-to=input3.rgb --stream-count=1

Below is the command used to convert the image from rgb to png
sudo convert -size 1600x1300 -sampling-factor 4:2:0 -depth 8 -interlace plane input3.rgb out116.png

Please find the below image that converted into .png format

![out100](https://user-images.githubusercontent.com/53291749/65936183-59ff5b00-e44e-11e9-9927-c7e5735d8b62.png)

If any body have any info on this how to make it a correct picture, pls guide me

**Comment by urban-warrior** [comment]
Post a link to your input3.rgb raw video file.  We need to inspect it before we can offer any additional assistance.
