### ISSUE TITLE
cannot convert doc file to pdf

### ISSUE THREAD

**Issue by sumanla13a** [ImageMagick/ImageMagick#172]
`convert -verbose aaaaa.doc app.pdf`

converts the doc file to pdf but then throws an error as follows
`"soffice" --headless --convert-to pdf --outdir `dirname "aaaaa.doc"` "aaaaa.doc" 2> "/tmp/magick-3117s1MGyT9qfcRf"; mv "aaaaa.doc.pdf" "/tmp/magick-3117lmiHpZuCqneI"
convert /home/suman/aaaaa.doc -> /home/suman//aaaaa.pdf using writer_pdf_Export
Overwriting: /home/suman//aaaaa.pdf
mv: cannot stat ‘aaaaa.doc.pdf’: No such file or directory
convert: delegate failed `"soffice" --headless --convert-to pdf --outdir `dirname "%i"` "%i" 2> "%Z"; mv "%i.pdf" "%o"' @ error/delegate.c/InvokeDelegate/1333.
convert: unable to open image `/tmp/magick-3117K4Z51LCtNZpW': No such file or directory @ error/blob.c/OpenBlob/2702.
convert: unable to open file `/tmp/magick-3117K4Z51LCtNZpW': No such file or directory @ error/constitute.c/ReadImage/540.
convert: no images defined `apppp.pdf' @ error/convert.c/ConvertImageCommand/3252.
`

**Comment by dlemstra** [comment]
We can reproduce the issue and we will have fix for this in the next release.

**Comment by sumanla13a** [comment]
@dlemstra Any news when it will be?

**Comment by dlemstra** [comment]
Your issue should be resolved in ImageMagick 7.0.1-1 or 6.9.3-10.
