### ISSUE TITLE
Manualy loading relevant .dll instead of using environment variable

### ISSUE THREAD

**Issue by Padawham** [ImageMagick/ImageMagick#1733]
# Description

While using the uninstalled version of ImageMagick, I'm trying to create an Image (class from magick). The call throws an exception with:
``Could not open image "—": RegistryKeyLookupFailed `CoderModulesPath' @ error/module.c/GetMagickModulePath/662``
After searching, it appears ImageMagick finds other .dll in its {imageMagick}/modules/coders path, wich I did not provide while doing the initialize in c++ (instead I provided the {imageMagick} to find the <CORE_*.dll>). Adding the variable in my code works fine, but manualy loading the missing .dll (determined by loaking at loaded .dlls with and without the variable) still throws the error... 
I thought ImageMagick explictly checked for a valid path in that variable while in uninstalled version, but providing a fake, yet existing, directory still failed. Is there a way to not set the MAGICK_CODER_MODULE_PATH and still make this work?

### Steps to Reproduce

Add the uninstalled version of ImageMagick to a c++ project.
Don't set MAGICK_CODER_MODULE_PATH but load all dll, that would usualy be loaded for an operation.
Create an ImageMagick::Image(ImageMagick::Blob, ImageMagick::Geometry, uint)

The different .dll from trying with the MAGICK_CODER_MODULE_PATH: `IM_MOD_RL_png_.dll`

### System Configuration

- ImageMagick version: 7.0.8
- Environment (Operating system, version and so on): Windows 10

**Comment by dlemstra** [comment]
Could you explain in more detail what kind of issues you are running into? I don't understand what you are trying to tell us.

**Comment by Padawham** [comment]
I want to control exactly what .dll I load so I can unload all of it at the right time. Because of it, I do not wish to set the MAGICK_CODER_MODULE_PATH which gives access to ImageMagick all of it's module's .dll, since my code wouldn't know which one to unload. Furthermore, if we ever extend our use of ImageMagick, setting the variable would make ImageMagick find its additional .dll without problem leading most probably to forgetting to unload it at the proper time.

My exact problem is that even while loading all of imageMagick .dlls before I initialize, it won't work when I don't have the MAGICK_CODER_MODULE_PATH set to the right directory. I would expect that variable to only tell where to look for .dll, and, since I loaded them myself, to work even if it's not set. The path to set only contains .dll, I have trouble figuring out what more use does that var have. In other words, with the same .dll loaded, it only works if I set a variable which points on the said loaded .dll. Why is that ?

Maybe Github wasn't the proper place to ask this, but there was no email or anything on the ImageMagick.org

**Comment by 2shady4u** [comment]
Hello, I would like to also give my 5 cents on this issue.

I'm currently working on a C++ library that uses ImageMagick as one of its dependencies.
It would indeed be great if the relevant DLL modules could be loaded either manually or
to manually set the path to which ImageMagick should restrict its search for the relvant DLL.
