### ISSUE TITLE
hang when loading SVG containing <path id="path" ...>

### ISSUE THREAD

**Issue by mleonhard** [ImageMagick/ImageMagick#1738]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
ImageMagick hangs when loading an SVG file containing a `<path />` tag with `id="path"`.  I discovered this when trying to convert SVG to PNG.

### Steps to Reproduce
```
$ echo '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 5 5"><g><path id="path" d="M 1,1 L 1,4 L 4,4 Z"/></g></svg>' >bug.svg && convert bug.svg bug.png
```

### System Configuration
bash prompt on MacOS 10.14.6.

- ImageMagick version:
Downloaded from https://imagemagick.org/download/binaries/ImageMagick-x86_64-apple-darwin17.7.0.tar.gz
```
$ convert -version
Version: ImageMagick 7.0.8-9 Q16 x86_64 2018-08-04 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib freetype jng jpeg lcms png raw tiff webp xml zlib
```
- Environment (Operating system, version and so on): MacOS 10.14.6 (18G95)
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
