### ISSUE TITLE
Cannot call convert from script because MacOS clears DYLD_LIBRARY_PATH

### ISSUE THREAD

**Issue by mleonhard** [ImageMagick/ImageMagick#1744]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The ImageMagick binary requires the `DYLD_LIBRARY_PATH` environment variable to be set.  Apparently MacOS automatically clears this environment variable when one process launches another.  See https://github.com/rbenv/rbenv/issues/962 .  This makes ImageMagick unusable from scripts.

### Steps to Reproduce

```
$ curl -s https://imagemagick.org/download/binaries/ImageMagick-x86_64-apple-darwin17.7.0.tar.gz |tar xz
$ export MAGICK_HOME=$PWD/ImageMagick-7.0.8/
$ export DYLD_LIBRARY_PATH=$PWD/ImageMagick-7.0.8/lib
$ export PATH=$MAGICK_HOME/bin:$PATH
$ echo $MAGICK_HOME
/Users/user/tmp/ImageMagick-7.0.8/
$ which convert
/Users/user/tmp/ImageMagick-7.0.8//bin/convert
$ convert --version
Version: ImageMagick 7.0.8-9 Q16 x86_64 2018-08-04 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib freetype jng jpeg lcms png raw tiff webp xml zlib
$ python -c 'import subprocess; subprocess.check_call(["convert", "--version"])'
dyld: Library not loaded: /ImageMagick-7.0.8/lib/libMagickCore-7.Q16HDRI.6.dylib
  Referenced from: /Users/user/tmp/ImageMagick-7.0.8//bin/convert
  Reason: image not found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['convert', '--version']' returned non-zero exit status -6
$ python -c 'import subprocess; subprocess.check_call(["sh", "-c", "set"])' |grep DYLD
$ 
```

### System Configuration
- ImageMagick version: ImageMagick 7.0.8-9 Q16 x86_64 2018-08-04
- Environment (Operating system, version and so on): MacOS 10.14.6 (18G95)
- Additional information:

Would there be some way to build a statically-linked MacOS binary?

Is there an alternative way to pass the library path?

**Comment by urban-warrior** [comment]
The article you cited details work-arounds to this problem.  Another solution is to use the static release of ImageMagick.  The static release does not depend on the DYLD_LIBRARY_PATH environment variable.

**Comment by 7c00** [comment]
> The article you cited details work-arounds to this problem. Another solution is to use the static release of ImageMagick. The static release does not depend on the DYLD_LIBRARY_PATH environment variable.

@urban-warrior Where to get a static release?

**Comment by fmw42** [comment]
The static is the first version (labeled just magick) at https://imagemagick.org/script/download.php

**Comment by 7c00** [comment]
> The static is the first version (labeled just magick) at https://imagemagick.org/script/download.php

It's for Linux. Is there a static release for macOS?
