### ISSUE TITLE
can't create/convert to HEIC image format

### ISSUE THREAD

**Issue by yobaid93** [ImageMagick/ImageMagick#1755]
### Description
I'm having an issue creating or converting [PNG, JPG ..] to HEIC image format.
worth known, that I could convert from HEIC format to other formats, so apparently the HEIC file is readable by imagick.

when I do :
`mogrify -format heic test.png`
I get the following error:
`mogrify: Success 'test.heic' @ error/heic.c/IsHeifSuccess/136.`
and the result is 0 byte file.
 
ImageMagick and libheif (and libde265) are built from source, as libheif isn't available for debian stretch (repo) yet.
I did the following instructions to build ImageMagick:
 ```
./configure --with-heic=yes
 make 
sudo make install
```
during "configure" step, it does check for libheif
`checking for libheif... yes`

### System Configuration
- ImageMagick version: 7.0.8-68 Q16
- Environment (Operating system, version and so on): Debian GNU/Linux 9 (stretch)

**Comment by urban-warrior** [comment]
We tried the following with 7.0.8-68:

$ convert logo: logo.png
$ mogrify -format heic logo.png
$ file logo.heic
logo.heic: ISO Media, HEIF Image HEVC Main or Main Still Picture Profile

**Comment by jordipolo87** [comment]
I have the same error, with the same OS, Debian 9. Have you found any solution @yobaid93 ?

**Comment by jordipolo87** [comment]
It seems that is some problem related with the OS, I have followed the same process to install everything in Ubuntu 18.04 and everything is working well.

**Comment by nikhil-lunawat** [comment]
I am also facing this issue. Output file is of 0 byte
libheif-1.8.0
imagemagick on 7.0.10
libde265 1.0.5

**Comment by hanjo** [comment]
> after debugging further, encoder jpeg.h file was missing in pkgconfig path which is not allowing imagemagick to convert from heif to jpeg

Hi @nikhil-lunawat , can you be a little more specific? To what location did you need to copy that file?

Thanks!
