### ISSUE TITLE
ImageMagick7 is slow than ImageMagick6

### ISSUE THREAD

**Issue by iamhgdabc** [ImageMagick/ImageMagick#1758]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

ImageMagick7 execute MagickReadImage and MagickCompositeImage cost 300ms
ImageMagick6 execute MagickReadImage and MagickCompositeImage cost 100ms
in my code，why is MI7 is slow than MI6
code：
`if (MagickReadImage(wm, imgfile) != MagickTrue) {
        goto _err;
    }

    if (MagickCompositeImage(ctx->wand, wm, AtopCompositeOp, MagickFalse, x, y) != MagickTrue) {
        goto _err;
    }`

confogure about IM7 :
`./configure --with-jemalloc --disable-dependency-tracking --disable-openmp --disable-shared --without-magick-plus-plus --without-fftw --without-fpx --without-djvu --without-fontconfig --with-freetype --without-gslib --without-gvc --without-jbig --without-lcms --without-lqr --without-lzma --without-openexr --without-pango --without-rsvg --without-tiff --without-bzlib --without-wmf --without-xml --without-dps --without-x --enable-delegate-build --with-quantum-depth=8 --disable-hdri "CFLAGS=-I/usr/local/include/openjpeg-2.3 -I$(PWD)/libjxr/sourceCode/jxrlib/image -I$(PWD)/libjpeg-turbo -I$(PWD)/libwebp/src -I$(PWD)/libpng" "LDFLAGS=-ldl -lrt -pthread -L/usr/local/lib -lopenjp2 -L$(PWD)/libjxr/sourceCode/jxrlib/build -ljpegxr -L$(PWD)/libjpeg-turbo/.libs -ljpeg -L$(PWD)/libwebp/src/.libs -lwebp -L$(PWD)/freetype/objs/.libs -lfreetype -L$(PWD)/libpng/.libs -lpng12" "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig" CPPFLAGS="-I$(PWD)/libjpeg-turbo -I$(PWD)/libpng"`
confogure about IM6 :
`./configure --enable-opencl --with-jemalloc --disable-dependency-tracking --disable-openmp --disable-shared --without-magick-plus-plus --without-fftw --without-fpx --without-djvu --without-fontconfig --with-freetype --without-gslib --without-gvc --without-jbig --without-lcms --without-lqr --without-lzma --without-openexr --without-pango --without-rsvg --without-tiff --without-bzlib --without-wmf --without-xml --without-dps --without-x --enable-delegate-build --with-quantum-depth=8 "CFLAGS=-g -I/usr/local/include/openjpeg-2.3 -I$(PWD)/libjxr/sourceCode/jxrlib/image -I$(PWD)/libjpeg-turbo -I$(PWD)/libwebp/src -I$(PWD)/libpng" "LDFLAGS=-ldl -lrt -pthread -L/usr/local/lib -lopenjp2 -L$(PWD)/libjxr/sourceCode/jxrlib/build -ljpegxr -L$(PWD)/libjpeg-turbo/.libs -ljpeg -L$(PWD)/libwebp/src/.libs -lwebp -L$(PWD)/freetype/objs/.libs -lfreetype -L$(PWD)/libpng/.libs -lpng12" "PKG_CONFIG_PATH=/usr/local/lib/pkgconfig";`

### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
Not sure if that method uses OpenCL but why are you building IM6 with and IM7 without support for OpenCL?

**Comment by iamhgdabc** [comment]
> Not sure if that method uses OpenCL but why are you building IM6 with and IM7 without support for OpenCL?

building IM6 without OpenCL get the same result, does IM7 building with opencl by default

**Comment by iamhgdabc** [comment]
IM6 is configured as follows
ImageMagick is configured as follows. Please verify that this configuration
matches your expectations.

  Host system type: x86_64-unknown-linux-gnu
  Build system type: x86_64-unknown-linux-gnu

                 Option                        Value
  ------------------------------------------------------------------------------
  Shared libraries  --enable-shared=no		no
  Static libraries  --enable-static=yes		yes
  Module support    --with-modules=no		no
  GNU ld            --with-gnu-ld=yes		yes
  Quantum depth     --with-quantum-depth=8	8
  High Dynamic Range Imagery
                    --enable-hdri=no		no

  Install documentation:			yes

  Delegate Library Configuration:
  BZLIB             --with-bzlib=no		no
  Autotrace         --with-autotrace=no		no
  DJVU              --with-djvu=no		no
  DPS               --with-dps=no		no
  FFTW              --with-fftw=no		no
  FLIF              --with-flif=yes		no
  FlashPIX          --with-fpx=no		no
  FontConfig        --with-fontconfig=no	no
  FreeType          --with-freetype=yes		yes
  Ghostscript lib   --with-gslib=no		no
  Graphviz          --with-gvc=no		
  JBIG              --with-jbig=no		no
  JPEG v1           --with-jpeg=yes		yes
  LCMS              --with-lcms=no		no
  LQR               --with-lqr=no		no
  LTDL              --with-ltdl=yes		no
  LZMA              --with-lzma=no		
  Magick++          --with-magick-plus-plus=no	no
  OpenEXR           --with-openexr=no		no
  OpenJP2           --with-openjp2=yes		yes
  PANGO             --with-pango=no		no
  PERL              --with-perl=no		no
  PNG               --with-png=yes		yes
  RAQM              --with-raqm=yes		no
  RSVG              --with-rsvg=no		no
  TIFF              --with-tiff=no		no
  WEBP              --with-webp=yes		yes
  WMF               --with-wmf=no		no
  X11               --with-x=no			no
  XML               --with-xml=no		no
  ZLIB              --with-zlib=yes		yes

  Delegate Program Configuration:
  GhostPCL          None				pcl6 (unknown)
  GhostXPS          None				gxps (unknown)
  Ghostscript       None				gs (8.70)

  Font Configuration:
  Apple fonts       --with-apple-font-dir=default	
  Dejavu fonts      --with-dejavu-font-dir=default	none
  Ghostscript fonts --with-gs-font-dir=default	/usr/share/fonts/default/Type1/
  Windows fonts     --with-windows-font-dir=default	none

  X11 Configuration:
        X_CFLAGS        = 
        X_PRE_LIBS      = 
        X_LIBS          = 
        X_EXTRA_LIBS    = 

  Options used to compile and link:
    PREFIX          = /usr/local
    EXEC-PREFIX     = /usr/local
    VERSION         = 6.9.8
    CC              = gcc -std=gnu99 -std=gnu99
    CFLAGS          = -I/usr/local/include/libpng12   -I/usr/local/include/openjpeg-2.3   -I/usr/include/freetype2       -g -I/usr/local/include/openjpeg-2.3 -I/home/mona_release/shark-mona/modules/mona_image/deps/libjxr/sourceCode/jxrlib/image -I/home/mona_release/shark-mona/modules/mona_image/deps/libjpeg-turbo -I/home/mona_release/shark-mona/modules/mona_image/deps/libwebp/src -I/home/mona_release/shark-mona/modules/mona_image/deps/libpng -Wall -mtune=core2 -fexceptions  -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=8
    CPPFLAGS        =   -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=8 -I/home/mona_release/shark-mona/modules/mona_image/deps/ImageMagick/magick -I/home/mona_release/shark-mona/modules/mona_image/deps/ImageMagick/wand
    PCFLAGS         = 
    DEFS            = -DHAVE_CONFIG_H
    LDFLAGS         = -ldl -lrt -pthread -L/usr/local/lib -lopenjp2 -L/home/mona_release/shark-mona/modules/mona_image/deps/libjxr/sourceCode/jxrlib/build -ljpegxr -L/home/mona_release/shark-mona/modules/mona_image/deps/libjpeg-turbo/.libs -ljpeg -L/home/mona_release/shark-mona/modules/mona_image/deps/libwebp/src/.libs -lwebp -L/home/mona_release/shark-mona/modules/mona_image/deps/freetype/objs/.libs -lfreetype -L/home/mona_release/shark-mona/modules/mona_image/deps/libpng/.libs -lpng12 -L/home/mona_release/shark-mona/modules/mona_image/deps/ImageMagick/magick -L/home/mona_release/shark-mona/modules/mona_image/deps/ImageMagick/wand
    LIBS            = 
    CXX             = g++
    CXXFLAGS        = -g -O2 
    FEATURES        = DPC CipherImageMagick is configured as follows. Please verify that this configuration
matches your expectations.

  Host system type: x86_64-pc-linux-gnu
  Build system type: x86_64-pc-linux-gnu

                 Option                        Value
  ------------------------------------------------------------------------------
  Shared libraries  --enable-shared=no		no
  Static libraries  --enable-static=yes		yes
  Build utilities   --with-utilities=yes        yes
  Module support    --with-modules=no		no
  GNU ld            --with-gnu-ld=yes		yes
  Quantum depth     --with-quantum-depth=8	8
  High Dynamic Range Imagery
                    --enable-hdri=no		no

  Install documentation:			yes

  Delegate Library Configuration:
  BZLIB             --with-bzlib=no		no
  Autotrace         --with-autotrace=no		no
  DJVU              --with-djvu=no		no
  DPS               --with-dps=no		no
  FFTW              --with-fftw=no		no
  FLIF              --with-flif=yes		no
  FlashPIX          --with-fpx=no		no
  FontConfig        --with-fontconfig=no	no
  FreeType          --with-freetype=yes		yes
  Ghostscript lib   --with-gslib=no		no
  Graphviz          --with-gvc=no		
  HEIC              --with-heic=yes             no
  JBIG              --with-jbig=no		no
  JPEG v1           --with-jpeg=yes		yes
  LCMS              --with-lcms=no		no
  LQR               --with-lqr=no		no
  LTDL              --with-ltdl=yes		no
  LZMA              --with-lzma=no		
  Magick++          --with-magick-plus-plus=no	no
  OpenEXR           --with-openexr=no		no
  OpenJP2           --with-openjp2=yes		yes
  PANGO             --with-pango=no		no
  PERL              --with-perl=no		no
  PNG               --with-png=yes		yes
  RAQM              --with-raqm=yes		no
  RAW               --with-raw=yes 	   	no
  RSVG              --with-rsvg=no		no
  TIFF              --with-tiff=no		no
  WEBP              --with-webp=yes		yes
  WMF               --with-wmf=no		no
  X11               --with-x=no			no
  XML               --with-xml=no		no
  ZLIB              --with-zlib=yes		yes
  ZSTD              --with-zstd=yes		no

  Delegate Program Configuration:
  GhostPCL          None				pcl6 (unknown)
  GhostXPS          None				gxps (unknown)
  Ghostscript       None				gs (8.70)

  Font Configuration:
  Apple fonts       --with-apple-font-dir=default	
  Dejavu fonts      --with-dejavu-font-dir=default	none
  Ghostscript fonts --with-gs-font-dir=default	/usr/share/fonts/default/Type1/
  URW-base35 fonts  --with-urw-base35-font-dir=default  none
  Windows fonts     --with-windows-font-dir=default	none

  X11 Configuration:
        X_CFLAGS        = 
        X_PRE_LIBS      = 
        X_LIBS          = 
        X_EXTRA_LIBS    = 

  Options used to compile and link:
    PREFIX          = /usr/local
    EXEC-PREFIX     = /usr/local
    VERSION         = 7.0.8
    CC              = gcc -std=gnu99 -std=gnu99
    CFLAGS          = -I/usr/local/include   -I/usr/local/include   -I/usr/local/include/libpng12   -I/usr/local/include/openjpeg-2.3   -I/usr/include/freetype2       -I/usr/local/include/openjpeg-2.3 -I/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libjxr/sourceCode/jxrlib/image -I/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libjpeg-turbo -I/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libwebp/src -I/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libpng -Wall -mtune=core2 -fexceptions -pthread -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=8
    CPPFLAGS        =  -I/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libjpeg-turbo -I/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libpng -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=8
    PCFLAGS         = 
    DEFS            = -DHAVE_CONFIG_H
    LDFLAGS         = -ldl -lrt -pthread -L/usr/local/lib -lopenjp2 -L/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libjxr/sourceCode/jxrlib/build -ljpegxr -L/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libjpeg-turbo/.libs -ljpeg -L/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libwebp/src/.libs -lwebp -L/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/freetype/objs/.libs -lfreetype -L/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libpng/.libs -lpng12
    LIBS            =     -lfreetype    -ljpeg   -L/usr/local/lib -lpng12          -L/usr/local/lib -lwebpmux -lwebp   -L/usr/local/lib -lwebp            -L/usr/local/lib -lopenjp2        -lz       -lm   -ljemalloc 
    CXX             = g++
    CXXFLAGS        = -g -O2 -mtune=core2 -pthread
    FEATURES        = DPC Cipher
    DELEGATES       = mpeg freetype jng jpeg openjp2 png ps webp zlib
==============================================================================

    DELEGATES       = mpeg freetype jng jpeg openjp2 png ps webp zlib
==============================================================================

IM7 is configured as follows

**Comment by iamhgdabc** [comment]
IM7:
ImageMagick is configured as follows. Please verify that this configuration
matches your expectations.

  Host system type: x86_64-pc-linux-gnu
  Build system type: x86_64-pc-linux-gnu

                 Option                        Value
  ------------------------------------------------------------------------------
  Shared libraries  --enable-shared=no		no
  Static libraries  --enable-static=yes		yes
  Build utilities   --with-utilities=yes        yes
  Module support    --with-modules=no		no
  GNU ld            --with-gnu-ld=yes		yes
  Quantum depth     --with-quantum-depth=8	8
  High Dynamic Range Imagery
                    --enable-hdri=no		no

  Install documentation:			yes

  Delegate Library Configuration:
  BZLIB             --with-bzlib=no		no
  Autotrace         --with-autotrace=no		no
  DJVU              --with-djvu=no		no
  DPS               --with-dps=no		no
  FFTW              --with-fftw=no		no
  FLIF              --with-flif=yes		no
  FlashPIX          --with-fpx=no		no
  FontConfig        --with-fontconfig=no	no
  FreeType          --with-freetype=yes		yes
  Ghostscript lib   --with-gslib=no		no
  Graphviz          --with-gvc=no		
  HEIC              --with-heic=yes             no
  JBIG              --with-jbig=no		no
  JPEG v1           --with-jpeg=yes		yes
  LCMS              --with-lcms=no		no
  LQR               --with-lqr=no		no
  LTDL              --with-ltdl=yes		no
  LZMA              --with-lzma=no		
  Magick++          --with-magick-plus-plus=no	no
  OpenEXR           --with-openexr=no		no
  OpenJP2           --with-openjp2=yes		yes
  PANGO             --with-pango=no		no
  PERL              --with-perl=no		no
  PNG               --with-png=yes		yes
  RAQM              --with-raqm=yes		no
  RAW               --with-raw=yes 	   	no
  RSVG              --with-rsvg=no		no
  TIFF              --with-tiff=no		no
  WEBP              --with-webp=yes		yes
  WMF               --with-wmf=no		no
  X11               --with-x=no			no
  XML               --with-xml=no		no
  ZLIB              --with-zlib=yes		yes
  ZSTD              --with-zstd=yes		no

  Delegate Program Configuration:
  GhostPCL          None				pcl6 (unknown)
  GhostXPS          None				gxps (unknown)
  Ghostscript       None				gs (8.70)

  Font Configuration:
  Apple fonts       --with-apple-font-dir=default	
  Dejavu fonts      --with-dejavu-font-dir=default	none
  Ghostscript fonts --with-gs-font-dir=default	/usr/share/fonts/default/Type1/
  URW-base35 fonts  --with-urw-base35-font-dir=default  none
  Windows fonts     --with-windows-font-dir=default	none

  X11 Configuration:
        X_CFLAGS        = 
        X_PRE_LIBS      = 
        X_LIBS          = 
        X_EXTRA_LIBS    = 

  Options used to compile and link:
    PREFIX          = /usr/local
    EXEC-PREFIX     = /usr/local
    VERSION         = 7.0.8
    CC              = gcc -std=gnu99 -std=gnu99
    CFLAGS          = -I/usr/local/include   -I/usr/local/include   -I/usr/local/include/libpng12   -I/usr/local/include/openjpeg-2.3   -I/usr/include/freetype2       -I/usr/local/include/openjpeg-2.3 -I/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libjxr/sourceCode/jxrlib/image -I/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libjpeg-turbo -I/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libwebp/src -I/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libpng -Wall -mtune=core2 -fexceptions -pthread -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=8
    CPPFLAGS        =  -I/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libjpeg-turbo -I/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libpng -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=8
    PCFLAGS         = 
    DEFS            = -DHAVE_CONFIG_H
    LDFLAGS         = -ldl -lrt -pthread -L/usr/local/lib -lopenjp2 -L/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libjxr/sourceCode/jxrlib/build -ljpegxr -L/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libjpeg-turbo/.libs -ljpeg -L/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libwebp/src/.libs -lwebp -L/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/freetype/objs/.libs -lfreetype -L/home/mona_code/mona_SHARKMONA-71/shark-mona/modules/mona_image/deps/libpng/.libs -lpng12
    LIBS            =     -lfreetype    -ljpeg   -L/usr/local/lib -lpng12          -L/usr/local/lib -lwebpmux -lwebp   -L/usr/local/lib -lwebp            -L/usr/local/lib -lopenjp2        -lz       -lm   -ljemalloc 
    CXX             = g++
    CXXFLAGS        = -g -O2 -mtune=core2 -pthread
    FEATURES        = DPC Cipher
    DELEGATES       = mpeg freetype jng jpeg openjp2 png ps webp zlib
==============================================================================

**Comment by iamhgdabc** [comment]
> Not sure if that method uses OpenCL but why are you building IM6 with and IM7 without support for OpenCL?

has any way to fix this problem？

**Comment by iamhgdabc** [comment]
> Not sure if that method uses OpenCL but why are you building IM6 with and IM7 without support for OpenCL?
IM7 perf info:
![FDW2GR3VTL~WO{)O)KZ5K}G](https://user-images.githubusercontent.com/11517961/67263092-abdd5300-f4d9-11e9-8c7f-c4f2d7317fc4.png)
IM6 perf info:
![5YZZ`F0$XO_Y0KUERUDSMUO](https://user-images.githubusercontent.com/11517961/67263103-b26bca80-f4d9-11e9-8ba9-a2397e486928.png)

just use MagickReadImage to read a localfile and use MagickCompositeImage to composite to a img

**Comment by iamhgdabc** [comment]
@dlemstra  
how to fix this problem，what different between IM6 and IM7 about default configure options

**Comment by iamhgdabc** [comment]
@dlemstra  
how to fix this problem，what different between IM6 and IM7 about default configure options
