### ISSUE TITLE
C compiler missing 

### ISSUE THREAD

**Issue by lravisingh** [ImageMagick/ImageMagick#176]
configure: error: in `/opt/genus/ImageMagic/ImageMagick-6.9.3-8':
configure: error: no acceptable C compiler found in $PATH
  

dev-abcxuzserver-lx01:/opt/xyz/ImageMagic/ImageMagick-6.9.3-8 # ./configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
configuring ImageMagick 6.9.3-8
checking whether build environment is sane... yes
checking for style of include used by make... GNU
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/opt/genus/ImageMagic/ImageMagick-6.9.3-8':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

**Comment by mikayla-grace** [comment]
ImageMagick requires a C compiler to build.  Either download / install a pre-compiled binary distribution of ImageMagick or install a C compiler, build ImageMagick, then install it.

**Comment by lravisingh** [comment]
Thanks , I did install the C Gcc compiler , everything works as expected !!

**Comment by lravisingh** [comment]
Thanks for the help !!

On Fri, Apr 29, 2016 at 12:35 PM, Dirk Lemstra <notifications@github.com>
wrote:

> Closed #176 <https://github.com/ImageMagick/ImageMagick/issues/176>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ImageMagick/ImageMagick/issues/176#event-645240354>
>



-- 
RAVI KUMAR SINGH
