### ISSUE TITLE
No delegate for this image format 'MSG'

### ISSUE THREAD

**Issue by abha3011** [ImageMagick/ImageMagick#1762]
Hi,

I need to convert a .msg file to an jpeg image. Can we do it using ImageMagick ?

I tried to run the below command,
        magick mail.msg mail.jpeg
but it gives an error :
      magick: no decode delegate for this image format `MSG' @ error/constitute.c/ReadImage/512.

I am using Version: ImageMagick 7.0.7-35 Q16 x86_64 2018-05-21

Can you please suggest if that is possible.

Thanks,
Abha

**Comment by fmw42** [comment]
What is an .msg file? Can you provide an example?

**Comment by abha3011** [comment]
Hello, 
  Sorry for the delayed response as I was on Holiday.

.msg file is actually an outlook mail message that I save as .msg format.
I want its text to be converted into an image. I tried with the command you have provided : 
        magick TEXT:mail.msg mail.jpg
 but it doesn't work. It actually creates 4 different .jpg files with junk characters/ unreadable form.

But I tried to save the outlook mail as .Txt and ran the command 
          magick TEXT:mail.txt mail.jpg
This indeed created a jpg image. Though with some junk characters.

But my requirement is to save the file as either .MSG or .html file 
[files.zip](https://github.com/ImageMagick/ImageMagick/files/3808209/files.zip)
and then convert it into an image.

Is there any similar way we can get the text of an outlook mail ( ( .MSG or .HTML format ) into an jpg image? I have attached the sample files for your reference.

Regards,
Abha

**Comment by fmw42** [comment]
Display the HTML in a browser and screen snap it. Or once display in your browser save as PDF. Then ImageMagick can convert the PDF to an image.

The msg file seems to be a binary file in proprietary format. I do not think ImageMagick understands that format.

I will defer to the ImageMagick developers for further comment or correction.

**Comment by abha3011** [comment]
Thanks for your response. 
But in screen snapping the problem is that if the text is more than a screen page it will just take a screen shot for current view. And also it needs more of user involvement to first save the mail as html and then again take a screen shot and then convert to image. So this is little difficult as for our requirement. 

Do let me know if there is really another way to just convert an outlook email into an image by any means.

Thanks,
Abha

**Comment by abha3011** [comment]
Hi,

We are still facing issue with converting .msg / .html into jpeg image. Did you get a chance to get a reply from the ImageMagick developers regarding this issue.

Regards,
Abha
