### ISSUE TITLE
'-fuzz' does not make an effect on '-fill' & '-opaque'

### ISSUE THREAD

**Issue by i0xHeX** [ImageMagick/ImageMagick#1769]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm trying to select and replace non cyan colors (with -fuzz) to black from the image:
![IN](https://i.ibb.co/FwkYs16/in.png)
And getting the not expected result - only one color left, fuzz didn't make an effect:
![OUT](https://i.ibb.co/4Py6cyS/out.png)

Changing `-fuzz` option from 0% to 100% does not make eny effect.

### Steps to Reproduce
```
magick.exe convert ^
    workspace\in.bmp ^
    -fuzz 50% ^
    -fill black ^
    +opaque "#00d7ff" ^
    workspace\out.bmp
```

### System Configuration
- ImageMagick 7.0.9-0 Q16 x64 2019-10-25
- Windows 10 (x64)

P.S. Also recently tested on 7.0.9-1 Q16 x64 2019-10-28, same issues.

**Comment by fmw42** [comment]
Your command works as expected to change all but #00d7ff to black. Your cyan color is not one single color, but has many near cyan colors due to antialiasing. So the larger you make the fuzz value, the more those near-cyan colors will be changed to black. Make your fuzz value smaller, say 10%. That looks better to me.

**Comment by i0xHeX** [comment]
> Your command works as expected to change all but #00d7ff to black. Your cyan color is not one single color, but has many near cyan colors due to antialiasing. So the larger you make the fuzz value, the more those near-cyan colors will be changed to black. Make your fuzz value smaller, say 10% or even less. That looks better to me.
> 
> `convert img.png -fuzz 10% -fill black +opaque "#00d7ff" x.png`
> 
> ![x](https://user-images.githubusercontent.com/13458218/67696073-71553980-f963-11e9-8b4b-9be4fe28b585.png)

I solved the issue. Thanks.
The problem was in batch file syntax, where `%` should be written as `%%`.
