### ISSUE TITLE
identify -format %n prints number of frames multiple times

### ISSUE THREAD

**Issue by twelve17** [ImageMagick/ImageMagick#177]
Given a 7 frame animated gif `blah.gif`, running `identify -format %n blah.gif` yields `7777777`.   `identify` seems to be printing the number of frames value as many times as there are frames.  For example, a 21 frame animated gif yields the output `21` printed 21 times: `212121212121212121212121212121212121212121`.

A workaround [found in this forum post](http://www.imagemagick.org/discourse-server/viewtopic.php?t=28755) is to add a newline character to the format command, and use `head` to grab the first line:
```
identify -format "%n\n" blah.gif | head -n 1
7
```

I am seeing this behavior in ImageMagick on Mac OS X via homebrew:
 ```
imagemagick: stable 6.9.3-7 (bottled), HEAD
Tools and libraries to manipulate images in many formats
https://www.imagemagick.org/
/usr/local/Cellar/imagemagick/6.9.3-7 (1,459 files, 17.9M) *
```

I am not seeing this behavior in this older version (under Linux):
```
Version: ImageMagick 6.7.7-0 2012-08-02 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP
```

**Comment by mikayla-grace** [comment]
Things change.  The current behavior is the expected behavior for a number of years now and there are no plans to change it.

**Comment by jacobbullock** [comment]
@mikayla-grace  is there a way to run the identify command but to break after the first iteration?  using -format %n runs really slow when processing a large video.  Would be nice to be able to pull total number of frames without processing every single frame.

**Comment by mikayla-grace** [comment]
By default, identify 'pings' an image which is quite efficient.  It does read the entire image but does not create a pixel cache saving memory and/or disk I/O.  Reading the entire image can detect if the image is corrupt and in many cases is necessary to count the total number of frames in the image file.  It does not work for %n. but you can only identify one frame, for example, with ```identify 'blah.gif[0]'. 

Video files are problematic because we leverage an external delegate program which unpacks the entire video sequence before ImageMagick can process it.  For this case, we lose most of the efficiency that ImageMagick garners from native image format support.

**Comment by mlfarrell** [comment]
are you frickin kidding me guys?  Just because it's "expected" doesn't make it right.

**Comment by n0099** [comment]
`identify 'blah.gif[0]'` will only print `1` since it's just exits after parsed the first frame
as described in the docs: https://imagemagick.org/script/escape.php
> %N	number of images in current image sequence, report once per image sequence

u can use `identify -format '%N\n' blah.gif` to achieve the old behavior, sadly it will have to read all the frames before exits, so it's slow for long animated gif
