### ISSUE TITLE
ImageMagick release tarballs disappear

### ISSUE THREAD

**Issue by fxcoudert** [ImageMagick/ImageMagick#1771]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When a new ImageMagick version is released, the previous tarball is removed from the www.imagemagick.org server. Sadly, this is making life difficult for Homebrew, as we have to maintain our own local mirror, but this can fail if new IM versions are released faster than our CI and code review process: https://github.com/Homebrew/homebrew-core/pull/46010

Could you please keep older tarballs of the code at a *stable* URL? Maybe not all, but as least the past N versions?

**Comment by fxcoudert** [comment]
Wrong link: I meant to link to https://github.com/Homebrew/homebrew-core/pull/45869

**Comment by urban-warrior** [comment]
Point Homebrew to https://imagemagick.org/download/releases.  We'll keep the latest 3 releases of the current release there.  However, give us a few weeks.  We have a few other priorities to squash first.

**Comment by fxcoudert** [comment]
OK, thanks

**Comment by rodlie** [comment]
I use this mirror for older releases: https://mirror.sobukus.de/files/src/imagemagick/
