### ISSUE TITLE
dng coder no longer compiling against libraw's master branch

### ISSUE THREAD

**Issue by alex** [ImageMagick/ImageMagick#1772]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

https://oss-fuzz-build-logs.storage.googleapis.com/log-34a88d07-5ec5-4b0c-849f-e3cc8973c73b.txt

```
Step #4: coders/dng.c:182:21: error: no member named 'FlashEC' in 'libraw_imgother_t'
Step #4:     raw_info->other.FlashEC);
Step #4:     ~~~~~~~~~~~~~~~ ^
Step #4: 1 error generated.
```
This seems to have been caused by a recent change to libraw, probably https://github.com/LibRaw/LibRaw/commit/d1975cb0e055d2bfe58c9d845c9a3e57c346a2f9

### Steps to Reproduce

1) Clone imagemagick from master
2) Clone libraw from master
3) Try to build IM against libraw

**Comment by urban-warrior** [comment]
Thanks... and fixed.
