### ISSUE TITLE
ICC color profile stripped when writing png

### ISSUE THREAD

**Issue by ikerr** [ImageMagick/ImageMagick#1774]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Running the following command results in a png file that does not contain an embedded color profile, even though it should:

`convert in.png -profile AdobeRGB1998.icc -strip -profile AdobeRGB1998.icc out.png`

### Steps to Reproduce

Run the following command on a png file with an embedded sRGB profile (see the link below for a sample image):

`convert in.png -profile AdobeRGB1998.icc -strip -profile AdobeRGB1998.icc out.png`

_(Note: the actual command that I am using is more complex, but I have reduced it to the above for the purpose of discussion.)_

The idea is to first convert to the AdobeRGB1998.icc profile and then strip comments from the file. However, since `-strip` also strips color profiles, there is an additional `-profile AdobeRGB1998.icc` option after the `-strip` to re-add the profile.

**Expected output**: out.png should contain an AdobeRGB1998.icc profile
**Actual output**: out.png does not contain an ICC profile

The result is that the colors in the image are relative to the AdobeRGB1998 profile, but the profile is not embedded in the image, which leads to incorrect colors when the image is displayed.

This problem does _not_ occur when writing to a jpg:

`convert in.png -profile AdobeRGB1998.icc -strip -profile AdobeRGB1998.icc out.jpg`

You can also work around the problem using a two-step process:

```
convert in.png -profile AdobeRGB1998.icc -strip tmp.png
convert tmp.png -profile AdobeRGB1998.icc out.png
```

The images mentioned in this post can be found here: https://gist.github.com/ikerr/0cc125c8b97bf31642eee7a7df0f8922

### System Configuration

- ImageMagick version: ImageMagick 7.0.9-2 Q16 x86_64 2019-10-31
- Environment (Operating system, version and so on): macOS 10.13.6
- Additional information:

**Comment by urban-warrior** [comment]
Try this command:

`convert in.png -profile AdobeRGB1998.icc -strip -profile AdobeRGB1998.icc -define png:include-chunk=zTXt,iCCP out.png`
