### ISSUE TITLE
use MagickGetImageBlob to get dynamic webp failed

### ISSUE THREAD

**Issue by iamhgdabc** [ImageMagick/ImageMagick#1777]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

use MagickGetImageBlob to get dynamic webp
assert like this： magick/layer.c:252: CoalesceImages: Assertion `exception->signature == 0xabacadabUL' failed
### System Configuration

- ImageMagick version: ImageMagick6-6.9.10-71
- Environment (Operating system, version and so on): centos6
- Additional information:

**Comment by dlemstra** [comment]
Can you add a small code sample that demonstrates the issue?

**Comment by iamhgdabc** [comment]
> Can you add a small code sample that demonstrates the issue?

`
first：
MagickReadImageBlob(ctx->wand, (const unsigned char *)ctx->content, ctx->content_length)
to read dynamic webp
then：
do same image process like set image quality
final：
content_new = (char *)MagickGetImagesBlob(ctx->wand, &content_new_length);
to get final webp
error：magick/layer.c:252: CoalesceImages: Assertion `exception->signature == 0xabacadabUL' failed.
`
