### ISSUE TITLE
When comparing blank (white) images of different size - returns there's no difference

### ISSUE THREAD

**Issue by amirhalatzi** [ImageMagick/ImageMagick#1778]
### Prerequisites

- [x ] I have written a descriptive issue title
- [x ] I have verified that I am using the latest version of ImageMagick
- [x ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When comparing white/blank images in version 7, it shows no difference - even though they're sizes are different. This is a regression compared to version 6.9

### Steps to Reproduce
1. Create 1024x768 white png image
1. Create 1024x400 white png image
1. `compare -metric ae a.png b.png diff.png`
Result: diff file is created with the size of the bigger image

### System Configuration
- ImageMagick version:7 .0.9-2 Q16 x86_64 2019-10-31
- Environment: MacOS 10.15.1

**Comment by fmw42** [comment]
I think you misunderstand the syntax. When you want to compare two images of equal size use the command you mentioned. When you want to compare two images of different size, then you need to add -subimage-search to your command. See https://imagemagick.org/script/compare.php

**Comment by amirhalatzi** [comment]
Thanks for the response, but I think I explained myself wrong.

I use the compare command as part of an npm package [chai-image-assert](https://github.com/diosmosis/chai-image-assert). I use it to verify an image generated by during a test equals a reference image. 

In my case, if the image is blank/all-white - it ignores that it's a different size and report them as equal.

Running the same test with ImageMagick 6.9 - it detects the difference in size, and don't bother comparing the images at all (which is the desired behavior).
