### ISSUE TITLE
Getting "insufficient image data" error when opening common readable TIFF file with LZW compression

### ISSUE THREAD

**Issue by stumpdk** [ImageMagick/ImageMagick#1780]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I try to open a TIFF file (LZW compression, RGB, 23x800 pixels). When doing it, I get the following error:

```magick.exe: insufficient image data in file `1.tif' @ error/tiff.c/ReadTIFFImage/1832```

It is an error that looks alot like this issue (which were closed in version 7.0.8-15, but concerned compression CCITT Group 4) : https://github.com/ImageMagick/ImageMagick/issues/1375

The image can be opened and viewed in different viewers (Windows Image Viewer, IrfanView etc.)

### Steps to Reproduce

* Download this file: [1.zip](https://github.com/ImageMagick/ImageMagick/files/3847179/1.zip) and unzip it

* Run this command: ```magick convert 1.tif 2.png``` returns the following error: ```convert: insufficient image data in file `1.tif' @ error/tiff.c/ReadTIFFImage/1832.```

### Additional info
```magick identify  1.tif --verbose``` returns the following info: 

```1.tif TIFF 800x23 800x23+0+0 8-bit sRGB 1152B 0.000u 0:00.002```

TifTagViewer gives the following tags:

* SubFileType (1 Long): Zero
* ImageWidth (1 Long): 800
* ImageLength (1 Long): 23
* BitsPerSample (3 Short): 8, 8, 8
* Compression (1 Short): LZW
* Photometric (1 Short): RGB
* StripOffsets (1 Long): 228
* Orientation (1 Short): TopLeft
* SamplesPerPixel (1 Short): 3
* RowsPerStrip (1 Long): 23
* StripByteCounts (1 Long): 924
* XResolution (1 Rational): 150
* YResolution (1 Rational): 150
* PlanarConfig (1 Short): Contig
* ResolutionUnit (1 Short): Inch
* PageNumber (2 Short): 0, 0

### System Configuration
Running ImageMagick on Windows 10 using PowerShell.

- ImageMagick version: ImageMagick 7.0.9-3 Q16 x64 2019-11-13
- Environment (Operating system, version and so on): Windows 10 (10.0.18362)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
