### ISSUE TITLE
Add a switch to save grayscale images to color PFM.

### ISSUE THREAD

**Issue by gonsolo** [ImageMagick/ImageMagick#1783]
I convert exr images to pfm for OpenImageDenoise. Unfortunately the denoiser accepts only colour (PF) PFM images. When all the objects and and lights in my image are gray convert automatically saves the pfm image as a grayscale (Pf) image which can't be read by denoise.

Please add a switch to force colour pfm images (PF header) even if there are only grayscale values.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by gonsolo** [comment]
This doesn't fix it. The type of my floating-point HDR 32-bit three-channel grayscale EXR image is UndefinedType at that point.

**Comment by gonsolo** [comment]
This would be a fix:

        format='F';
        if ((image_info->type != TrueColorType) &&
            (image_info->type != UndefinedType) &&
            (SetImageGray(image,&image->exception) != MagickFalse))
          format='f';

**Comment by gonsolo** [comment]
An even better solution would be to never mess with the channels of an image. So three-channel-images stay three-channel and one-channel keep one channel.

**Comment by urban-warrior** [comment]
Try this command:

`convert image.exr -type truecolor image.pfm`

**Comment by gonsolo** [comment]
That works. Thanks.
