### ISSUE TITLE
Convert svg to dxf results in coredump

### ISSUE THREAD

**Issue by teo1978** [ImageMagick/ImageMagick#1785]
### Prerequisites

- [ ] I have verified that I am using the latest version of ImageMagick

Well, probably not

. I am using the latest available to me through `apt get install`.

- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

No. I expect a decent bug tracker to do that for me when submitting the report.

### Description
See steps to reproduce

### Steps to Reproduce

- Download the attached file `test.svg`
- run:
```
$ convert test.svg test.dxf
```

## Expected
Either a dxf file is produced, or an error message is output with an explanation of why the file couldn't be converted.

I don't even know whether dxf is a supported output format, but even if not, a coredump is certainly not acceptable behavior.

### System Configuration

- ImageMagick version: ImageMagick 6.8.9-9 Q16 x86_64 2019-11-12
- Environment (Operating system, version and so on): ubuntu 16.04
- Additional information:

P.S. Seriously? Can't attach an svg file?? Well let me zip it.
[test.svg.zip](https://github.com/ImageMagick/ImageMagick/files/3879006/test.svg.zip)

**Comment by teo1978** [comment]
Actually the same happens when trying to convert to pdf, png, or even svg itself. I guess the problem is with the input rather than the output

**Comment by teo1978** [comment]
Is it possible that it is still this??
http://www.imagemagick.org/discourse-server/viewtopic.php?t=6305

**Comment by teo1978** [comment]
Now I'm trying the most recent version built from source, and instead of a coredump, I get this:

```
convert: delegate failed `'potrace' --svg --output '%o' '%i'' @ error/delegate.c/InvokeDelegate/1891
```

**Comment by urban-warrior** [comment]
Try installing `potrace`.  Does `sudo apt install potrace` fix the problem?
