### ISSUE TITLE
Install from source broken

### ISSUE THREAD

**Issue by teo1978** [ImageMagick/ImageMagick#1786]
### Description

I followed the instructions from here:
https://imagemagick.org/script/install-source.php

I already have a presumably older version installed on Ubuntu via apt-get (I wanted to uninstall it but the list of dependant stuff that would be uninstalled scared me).

However, looking at where the documentation says `make install` would install it, it shouldn't conflict with the installed one.

(side note: I would have appreciated instructions from the download page on how to just use the binaries compiled from source without installing them anywhere, or if that is not possible for whatever reason, say so explicitly)

### Steps to Reproduce

- Download and extract source from https://imagemagick.org/script/install-source.php
- ./configure
- sudo make install
- Try to run:

```
$ /usr/local/bin/convert somefile.svg somefile.dxf

/usr/local/bin/convert: error while loading shared libraries: libMagickCore-7.Q16HDRI.so.7: cannot open shared object file: No such file or directory

```

### System Configuration

- ImageMagick version: just downloaded from source right now
- Environment (Operating system, version and so on): ubuntu 16.04
- Additional information:

**Comment by teo1978** [comment]
Now `which convert` returns `/usr/local/bin/convert` which is the one installed from source. How can I uninstall this without screwing up the previous existing installation?

**Comment by urban-warrior** [comment]
To uninstall, try this command:

`make uninstall`

In the install instructions, it says "You may need to configure the dynamic linker run-time bindings:"

`sudo ldconfig /usr/local/lib`
