### ISSUE TITLE
Homebrew formula doesn't list ghostscript as dependency

### ISSUE THREAD

**Issue by AndrinGautschi** [ImageMagick/ImageMagick#1787]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
A clean installation via homebrew delivers a version which is not aware of installed fonts on the system.  Installing ghostscript (also via brew) fixes that. I'd suggest to list ghostscript as dependency. 

### Steps to Reproduce
```
brew uninstall imagemagick ghostscript
brew clean
brew install imagemagick
convert -list font
```

### System Configuration
- ImageMagick version: 7.0.9-5 (bottled), HEAD
- Environment (Operating system, version and so on): MacOS Catalina 10.15.1, MacBook Pro

**Comment by urban-warrior** [comment]
We updated the documentation to reflect the Ghostscript font dependency.  Thanks.
