### ISSUE TITLE
ImagickException: FailedToExecuteCommand 'inkscape ERROR

### ISSUE THREAD

**Issue by kendallmark3** [ImageMagick/ImageMagick#1789]
After packaging our AP,I which uses your Library, into a docker container and running on Azure we are getting this error

ImagickException: FailedToExecuteCommand 'inkscape' '/tmp/magick-10857XI3tNBMKkA5E' --export-png='/tmp/magick-10857gQzvFK4Rmpsm' --export-dpi='90,90' --export-background='rgb(0%,0%,0%)' --export-background-opacity='0' > '/tmp/magick-108573FwCVBAeAeP3' 2>&1' (-1) @ error/delegate.c/ExternalDelegateCommand/463

It runs fine locally when served from IIS but not from a Docker container- fails intermittently on Azure and also locally inside a container-

Is there a setting in the container or in the configuration that the tmp storage size is being set and can we change it?

Reference:https://github.com/nextcloud/server/issues/2579

**Comment by dlemstra** [comment]
Did you install `inkscape` in those other environments?

**Comment by kendallmark3** [comment]
Thank you Dirk- Yes in my dockerfile here is the install:
RUN ln -s /lib/x86_64-linux-gnu/libdl-2.24.so /lib/x86_64-linux-gnu/libdl.so
RUN apt-get update && apt-get -y install inkscape
RUN apt-get update && apt-get -y install libpng-dev

Our program API finishes and produces the jpg most of the time but as the size of the image grows it fails with the above error- We are adding locations to a map points at 70 point seems of but after that we get the error- thus it appears as the tmp storage is too small for inkscape to create the temp image?

**Comment by dlemstra** [comment]
Have you tried checking the content of your docker container when it is running? I am wondering if the temporary files are nicely cleaned up with IMagick.

**Comment by roblou123** [comment]
Hi @kendallmark3. Facing a similar issue and just wondering if you found the source/solution to this problem

**Comment by kendallmark3** [comment]
Turned out to be a memory leak- testing locally and optimized for memory
with some settings- got us for some time- high loads are still not right-
look for ways to distribute load during peak times

**Comment by silgon** [comment]
I have the same error in WASM. Kind of difficult to install inkscape there...
