### ISSUE TITLE
Files converted to HEIC do not work in Adobe Photoshop CC 2018 and Lightroom Classic 9

### ISSUE THREAD

**Issue by maxim-saplin** [ImageMagick/ImageMagick#1790]
Files converted to HEIC do not work in Adobe Photoshop CC 2018 and Lightroom Classic 9 though they work fine in macOS Finder and Preview.

### Steps to Reproduce
- Take any JPG file
- Convert it to heic (e.g. 'magick 1.jpg 1.heic')
- Launch Photoshop
- Click in top menu Photoshop CC -> Preferences > Camera Raw... and in settings dialog (under File Handling) make sure you have 'Automatically open all supported JPEGs and HEICs' is selected
- Open the converted HEIC and see that Photoshop says it has trouble with the file

#### Checking if there's issue with HEIC created by other programs
- Open the same JPG file with macOS's Preview app
- File -> Export -> save as HEIC
- Open the file in Photoshop, see that it's working fine

#### Making Photoshop open ImageMagick produced file
- Click in top menu Photoshop CC -> Preferences > Camera Raw... and in settings dialog (under File Handling) set  'Automatically open JPEGs and HEICs *with settings*'
- Open the ImageMagick converted HEIC file and see that Photoshop at first shows Color Profile selection dialog and after that all works fine.

#### Lightroom troubles
- Try importing the folder with ImageMagick converted and Preview coinverted HEIC files
- See that ImageMagik's HEIC is not displayed (empty tile), while Preview's HEIC is displayed fine

P.S.: Adobe Bridge also doesn't work

### System Configuration

- ImageMagick version: 7.0.9-5 Q16 x86_64
- Environment (Operating system, version and so on): macOS 10.15.1
- Additional information: Adobe Photoshop CC 2018, Adobe Lightroom Classic 9, Adobe Camera Raw 12

**Comment by maxim-saplin** [comment]
[Sample files.zip](https://github.com/ImageMagick/ImageMagick/files/3890865/Sample.files.zip)
- 1.jpg - source file
- 1.heic - ImageMagick's output
- 1-export-with-Preview-app.heic - macOS's Preview app output

**Comment by dlemstra** [comment]
Those files are created with the libheif library (https://github.com/strukturag/libheif). It could be an issue with that library or we are using their API incorrectly. Are you using the latest version of that library?

**Comment by maxim-saplin** [comment]
> Those files are created with the libheif library (https://github.com/strukturag/libheif). It could be an issue with that library or we are using their API incorrectly. Are you using the latest version of that library?

Is that a question to me? All I did was installing ImageMagick via brew last week. Should I check anything else in my env?

**Comment by dlemstra** [comment]
Yes this is a question for you. We don't have the same environment as you do so we cannot reproduce this issue. We need to figure out if we need to change something or that the issue lies in the libheif library.

**Comment by maxim-saplin** [comment]
How do I check libheif version?

**Comment by dlemstra** [comment]
I don't have a Mac and never used brew myself. Maybe @fmw42 can help us with this?

**Comment by yoya** [comment]
homebrew separate directories for each library, so you can probably guess version with the following command:
```
% convert -list configure | grep ^CFLAGS
CFLAGS                -I/usr/include/libxml2 -I/usr/local/Cellar/webp/1.0.3/include -I/usr/local/Cellar/webp/1.0.3/include -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -D_THREAD_SAFE -I/usr/local/Cellar/ilmbase/2.3.0/include/OpenEXR -I/usr/local/Cellar/openexr/2.3.0/include/OpenEXR -I/usr/local/Cellar/xz/5.2.4/include -I/usr/local/Cellar/openjpeg/2.3.1/include/openjpeg-2.3 -I/usr/local/Cellar/little-cms2/2.9/include -I/usr/local/Cellar/libheif/1.6.0/include -I/usr/local/opt/freetype/include/freetype2   -Xpreprocessor -fopenmp -g -O2 -Wall -mtune=penryn -fexceptions -D_FORTIFY_SOURCE=0 -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
% convert -list configure | grep ^CFLAGS | grep -o "libheif/[0-9.]*"
libheif/1.6.0
```

additional carefully  checking.
```
% brew info libheif
libheif: stable 1.6.0 (bottled)
ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
https://www.libde265.org/
/usr/local/Cellar/libheif/1.5.1_2 (32 files, 2.3MB)
  Poured from bottle on 2019-11-03 at 16:07:56
/usr/local/Cellar/libheif/1.6.0 (36 files, 2.3MB) *
  Poured from bottle on 2019-11-23 at 15:50:53
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libheif.rb
==> Dependencies
Build: pkg-config ✔
Required: jpeg ✔, libde265 ✔, libpng ✔, shared-mime-info ✔, x265 ✔
==> Analytics
install: 95,653 (30 days), 242,348 (90 days), 605,781 (365 days)
install-on-request: 3,415 (30 days), 8,026 (90 days), 14,110 (365 days)
build-error: 0 (30 days)
```

**Comment by maxim-saplin** [comment]
Here's the output from my terminal

```
bash-3.2$ convert -list configure | grep ^CFLAGS | grep -o "libheif/[0-9.]*"

libheif/1.6.0
```

```
bash-3.2$ brew info libheif

libheif: stable 1.6.0 (bottled)
ISO/IEC 23008-12:2017 HEIF file format decoder and encoder
https://www.libde265.org/
/usr/local/Cellar/libheif/1.6.0 (23 files, 2.3MB) *
  Poured from bottle on 2019-11-20 at 09:33:48
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libheif.rb
==> Dependencies
Build: pkg-config ✔
Required: jpeg ✔, libde265 ✔, libpng ✔, shared-mime-info ✔, x265 ✔
==> Analytics
install: 95,653 (30 days), 242,348 (90 days), 605,781 (365 days)
install_on_request: 3,415 (30 days), 8,026 (90 days), 14,110 (365 days)
build_error: 0 (30 days)
```

**Comment by urban-warrior** [comment]
```
convert -list format | grep -i heic
    HEIC* rw+   High Efficiency Image Format (1.5.1)
```

**Comment by maxim-saplin** [comment]
```
bash-3.2$ convert -list format | grep -i heic
     HEIC* HEIC      rw+   High Efficiency Image Format (1.6.0)
```

**Comment by yoya** [comment]
I'm using macOS 10.15.1 Catalina, so I can't try Adobe Photoshop CC 2018 / Lightroom Classic 9, but I encountered that Adobe Photoshop Lightroom (20191017-... build) can't read HEIC generated by ImageMagick.

If you can't load the next images,
-  https://github.com/nokiatech/heif/blob/gh-pages/content/images/autumn_1440x960.heic
- [C001.zip](https://github.com/ImageMagick/ImageMagick/files/3912408/C001.zip) (C001.heic, GPAC ISOBMFF conformance test file)

And if you can load this image, I guess it's probably the same phenomenon.
- [1-extendOffset.zip](https://github.com/ImageMagick/ImageMagick/files/3912481/1-extendOffset.zip) (1-extendOffset.heic)

The difference between 1.heic and 1-extendOffset.heic is only the usage of iloc box.

- 1.heic - iloc structure & infomation elements is here.

```
% MP4Box -std -diso 1.heic  | grep iloc -A 2
<ItemLocationBox Size="34" Type="iloc" Version="0" Flags="0" Specification="p12" Container="meta" offset_size="4" length_size="4" base_offset_size="4" index_size="0">
<ItemLocationEntry item_ID="1" data_reference_index="0" base_offset="335" construction_method="0">
<ItemExtentEntry extent_offset="0" extent_length="28052" extent_index="0" />
```
- 1-extendOffset.heic is here. (binary edited manually from 1.heic)

```
% MP4Box -std -diso  1-extendOffset.heic  | grep iloc -A 2
<ItemLocationBox Size="34" Type="iloc" Version="0" Flags="0" Specification="p12" Container="meta" offset_size="4" length_size="4" base_offset_size="4" index_size="0">
<ItemLocationEntry item_ID="1" data_reference_index="0" base_offset="0" construction_method="0">
<ItemExtentEntry extent_offset="335" extent_length="28052" extent_index="0" />
```

strukturag/libheic, GPAC/MP4Box,  nokiatech/heif use the iloc base_offset indicate the location of media(image) data in mdat box.
Apple iPhone image viewer and macOS preview.app not use iloc baseOffset but indicates it with extent_offset.

Perhaps Adobe Photoshop Lightroom  only considers only Apple's binaries to read HEIF , and base_offset seems to be ignored, I think so.
