### ISSUE TITLE
7.0.9-6: read.t failing on Truevision Targa image

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#1792]
Thanks for the new release.

I just get the following failure:
```
Truevision Targa image file ...
mean-error=0.0939722498831872, maximum-error=0.847058823529412
not ok 35
```
With 7.0.9-5 there was no such issue. 6.9.10-75 also does not suffer.
System: linux x86_64

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
Thanks! I am sorry I just noticed that write.t is failing, too:

Image: TGA:input.tga, signatures do not match.
     Expected: d0b17026dc758a4088c96bc0f21a2bf14e3ab4af8a35638129f7731f2f1cbe7e
     Computed: 5fd8b14e213578e41bb598825d5a9431f025de653c15896c696063fc3ed472ff
     Depth:    16
not ok 24

**Comment by pgajdos** [comment]
Thanks!
