### ISSUE TITLE
Regression since 7.0.9-4: 'compose over' with color mask produces only one-colored image

### ISSUE THREAD

**Issue by sephiroth-j** [ImageMagick/ImageMagick#1796]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I noticed that a few graphics test from TYPO3 CMS (8.7.29 LTS) are producing wrong outputs with the latest ImageMagick 7.0.9-7. The results where fine with my previous environment using ImageMagick 7.0.9-2. The regression was first introduced in version 7.0.9-4.

Instead of writing a png file with 8 bit color depth, it is just writing a 1-bit depth png visually identical to `color.png`.

### Steps to Reproduce
- build ImageMagick 7.0.9-4 or newer
- `magick composite +profile '*' -compose over +matte 'png:color.png' 'png:base.png' 'png:mask.png' out.png`
- **actual result**
![out-actual](https://user-images.githubusercontent.com/23166289/70266036-fec64d80-179b-11ea-91f5-167f32c57beb.png)
- **expected result**
![out-expected](https://user-images.githubusercontent.com/23166289/70266048-0980e280-179c-11ea-8d27-ef7a053226de.png)

### System Configuration

- ImageMagick version: 7.0.9-7
- Environment (Operating system, version and so on): Linux x64 (SLES 11 SP4)
- Additional information: beta 7.0.9-8 from 12/05 is affected as well

[**debug logs from 7.0.9-2 and 7.0.9-4 and build log**](https://github.com/ImageMagick/ImageMagick/files/3928681/imagemagick-7.0.9-4.regression.zip)

base.png
![base](https://user-images.githubusercontent.com/23166289/70266155-3f25cb80-179c-11ea-8a68-7603233416bb.png)

color.png
![color](https://user-images.githubusercontent.com/23166289/70266239-62507b00-179c-11ea-940f-67520351ab1b.png)

mask.png
![mask](https://user-images.githubusercontent.com/23166289/70266251-67adc580-179c-11ea-9726-dc93862ef50b.png)

**Comment by fmw42** [comment]
Your command has no output image. Also you should use magick rather than (magick) composite. The former is much more flexible and allow many more additional commands to be used with it.

Try the following. It works for me on IM 7.0.9.7 Q16 Mac OSX Sierra

`magick base.png color.png mask.png +profile '*' -compose over -composite result.png`

**Comment by dexterbg** [comment]
This may be the same bug, if it isn't I can open a separate issue:

We need to overlay the brightness channel of an image to a base image (like gimp layer mode "HSV Value"). We've been achieving this by converting the base and overlay to HSB and copying the "blue" channel (brightness) of the overlay (masked by the overlay) onto the base:

`convert base.png -colorspace HSB overlay.png -colorspace HSB overlay.png -compose CopyBlue -composite -colorspace sRGB result.png`

base.png
![base](https://user-images.githubusercontent.com/2706753/71818744-168a3d80-308a-11ea-8329-2b6b1ff6d85b.png)

overlay.png
![overlay](https://user-images.githubusercontent.com/2706753/71818801-39b4ed00-308a-11ea-864d-2f318a2180cb.png)

result.png with 7.0.8
![result-7 0 8-28](https://user-images.githubusercontent.com/2706753/71818813-476a7280-308a-11ea-9e00-af3233ba2cff.png)

We had been using the remi distribution of IM7 for CentOS 7 version 7.0.8-28 up to December 22. After Updating to 7.0.9-9 and now 7.0.9-13 we now get this:

result.png with 7.0.9
![result-7 0 9-9](https://user-images.githubusercontent.com/2706753/71818854-62d57d80-308a-11ea-8798-c27a703d0b94.png)

**Comment by dexterbg** [comment]
Apparently the CopyBlue issue has been fixed, with IM version 7.0.10 it's working again.

Thanks to the IM team!
