### ISSUE TITLE
Imagick create gif animation - spends more than 200mb of memory

### ISSUE THREAD

**Issue by goodwin74** [ImageMagick/ImageMagick#1797]
When creating a GIF, more than 200 MB is spent and the PHP process freezes and gives a 404 error.
What is the reason for this? And how to fix it?
The total size of all frames (in base64) is only 5mb, where from so much memory consumption?
```
$animation = new Imagick();
            $animation->setFormat('GIF');
            foreach ($framesBase64jpeg as $frameBase64){
                    $data = explode( ',', $frameBase64);
                    $frame = new Imagick();
                    $frame->readimageblob(base64_decode($data[1]));
                    $frame->setImageDelay(4);
                    $animation->addImage($frame);
             }
         echo base64_encode($animation->getImagesBlob());
```

**Comment by urban-warrior** [comment]
See https://imagemagick.org/script/architecture.php#tera-pixel.  Not sure how to do it in iMagick but you need to force the pixel processing to disk rather than memory.  You can set the security policy, for example, see https://imagemagick.org/script/architecture.php#tera-pixel or set an environment variable, see https://imagemagick.org/script/resources.php#environment.

**Comment by goodwin74** [comment]
> See https://imagemagick.org/script/architecture.php#tera-pixel. Not sure how to do it in iMagick but you need to force the pixel processing to disk rather than memory. You can set the security policy, for example, see https://imagemagick.org/script/architecture.php#tera-pixel or set an environment variable, see https://imagemagick.org/script/resources.php#environment.

Did I understand correctly? I have to do this:
IMagick::setResourceLimit(imagick::RESOURCETYPE_MEMORY, -1);
IMagick::setResourceLimit(imagick::RESOURCETYPE_MAP, -1);
IMagick::setResourceLimit(imagick::RESOURCETYPE_DISK, 314572800);
