### ISSUE TITLE
Error when chop after trim

### ISSUE THREAD

**Issue by kivist** [ImageMagick/ImageMagick#18]
<img width="247" alt="test" src="https://cloud.githubusercontent.com/assets/13446211/8818552/b5e17066-3075-11e5-9a30-8b8dbe4aa63e.png">

Code (test.png is shown above) run in cmd 
(I'm not pro so I don't know how to paste good looking codes- -):
line1:  convert test.png -trim test.png
line2:  convert test.png -gravity East -chop 3x0 test.png

Line2 returns error :
"convert.exe: geometry does not contain image `test.png' @ warning/transform.c/ChopImage/225."

Environment:
Surface pro 3 i5 16G mem
Windows 10 x64 build 10240 
ImageMagick-6.9.1-9-Q16-x64-dll.exe

**Comment by urban-warrior** [comment]
Try this:

    convert test.png -trim +repage -gravity East -chop 3x0 test.png

**Comment by kivist** [comment]
Issue solved.

Now I know the meaning of
"Here we trim the image, but only to list the result on what part of the image was trimmed, not the actual trimmed image. "

However, is it possible to add a warning like "Cannot chop an image with canvas info" when this kind of stupid mistake was made by amateurs like me?

Thanks very much.

**Comment by urban-warrior** [comment]
You actually can chop an image with a virtual canvas, it may give unexpected results unless you take into account the virtual canvas geometry.
