### ISSUE TITLE
ImageMagick says -contrast option replaced with -level (huh?)

### ISSUE THREAD

**Issue by pnoeric** [ImageMagick/ImageMagick#1801]
### Prerequisites

- [x ] I have written a descriptive issue title
- [ x] I have verified that I am using the latest version of ImageMagick
- [x ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I have a simple ImageMagick command that uses `-contrast` which is well-documented here: https://imagemagick.org/script/command-line-options.php#contrast

My command:
`magick in.jpg -enhance -contrast -background white -quality 100 -resize 200x200^ -gravity center -extent 200x200 out.jpg
`

But I'm getting this error:

`magick: option has been replaced '-contrast', use "-level" at CLI arg 3 @ warning/operation.c/CLISimpleOperatorImage/2078.`

So... huh? It [looks like `-contrast` is still available on the command line](https://imagemagick.org/script/command-line-options.php#contrast), and I don't see how `-level` is supposed to replace it. There's nothing I can find about `-contrast` being replaced/removed. It's very strange.

** UPDATE - I can even see [right here][1] in the code where MagickWand (which I assume is part of ImageMagick) actually generates that error message. However, I don't know why it's doing that, and as I said, can't find anything in any documentation that implies `-contrast` should not be used. Mysterious.

  [1]: https://github.com/ImageMagick/ImageMagick/blob/master/MagickWand/operation.c#L2078

### Steps to Reproduce

`magick in.jpg -enhance -contrast -background white -quality 100 -resize 200x200^ -gravity center -extent 200x200 out.jpg`

### System Configuration
- ImageMagick version:

```
Version: ImageMagick 7.0.9-7 Q16 x86_64 2019-12-02 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(3.1)
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zlib
```

- Environment (Operating system, version and so on):

CentOS 7

**Comment by fmw42** [comment]
The same command fails for me, also, on IM 7.0.9-7 Q16 Mac OSX.  I see nothing in the porting documentation at https://imagemagick.org/script/porting.php#cli regarding deprecation of -contrast. However, as an alternate command, one can use -brightness-contrast bri,con, which is more flexible. See https://imagemagick.org/script/command-line-options.php#brightness-contrast
