### ISSUE TITLE
No 7.0.9-8 and 7.0.9-9 releases/tags

### ISSUE THREAD

**Issue by jjoos** [ImageMagick/ImageMagick#1803]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

We rely on packages in https://github.com/ImageMagick/ImageMagick/releases to update our machines, the latest releases aren't in there while they are present in the changelog: https://github.com/ImageMagick/ImageMagick/blob/master/ChangeLog . 

If I can help pleas let me know (I did a quick search on any documentation about releases).

**Comment by dlemstra** [comment]
We do this manually an we will do this later this week.
