### ISSUE TITLE
Release on Github doesn't match the packaged version

### ISSUE THREAD

**Issue by jgelens** [ImageMagick/ImageMagick#1805]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Release on Github doesn't match the packaged version. I downloaded `Release build (7.0.9-8)` on Github and it has the wrong version set inside:

```~/Downloads/ImageMagick-7.0.9-8
❯  grep PACKAGE_RELEASE version.sh
PACKAGE_RELEASE="9"
PACKAGE_LIB_VERSION_NUMBER="7,0,9,${PACKAGE_RELEASE}"
```

- ImageMagick version: 7.0.9-8

**Comment by dlemstra** [comment]
Thanks for reporting this will take a look at it tonight

**Comment by dlemstra** [comment]
A new tag has been set.

**Comment by jgelens** [comment]
Thanks!
