### ISSUE TITLE
memory leak:when convert any format pic to heic

### ISSUE THREAD

**Issue by yo123abxd** [ImageMagick/ImageMagick#1808]
### Description
It's leaking very slow, I converted a test pic(jpeg, 192kb) to heic about 300000 times and the program leaked about 100Mb memory.

I used valgrind to detect where is leaking, and there are 1 blocks are definitely losed

==29420== 1,008 bytes in 1 blocks are definitely lost in loss record 2,342 of 2,699
==29420==    at 0x4C2A355: memalign (vg_replace_malloc.c:908)
==29420==    by 0x4C2A41F: posix_memalign (vg_replace_malloc.c:1072)
==29420==    by 0x9CFAC3: x265::x265_malloc(unsigned long) (in xxx
==29420==    by 0x93B6BE: x265_encoder_open_176 (in xxx
==29420==    by 0x7C6A62: x265_encode_image(void*, heif_image const*, heif_image_input_class) (in xxx
==29420==    by 0x7B7A72: heif::HeifContext::Image::encode_image_as_hevc(std::shared_ptr<heif::HeifPixelImage>, heif_encoder*, heif_encoding_options const*, heif_image_input_class) (in xxx
==29420==    by 0x7B8630: heif::HeifContext::encode_image(std::shared_ptr<heif::HeifPixelImage>, heif_encoder*, heif_encoding_options const*, heif_image_input_class, std::shared_ptr<heif::HeifContext::Image>&) (in xxx
==29420==    by 0x7B0E88: heif_context_encode_image (in xxx
==29420==    by 0x6F423F: WriteHEICImage (in xxx
==29420==    by 0x527C11: WriteImage (in xxx
==29420==    by 0x502900: ImageToBlob (in xxx
==29420==    by 0x502E68: ImagesToBlob (in xxx

### Steps to Reproduce
here is the test codes:

std::string img;
void test() {
Magick::Blob src_blob(img.data(), img.length());
std::list<Magick::Image> total_images;
Magick::readImages(&total_images, src_blob);
total_images.begin()->magick("HEIC");
std::string out_binary;
Magick::Blob out_blob;
total_images.begin()->write(&out_blob);
out_binary.assign((const char*)out_blob.data(), out_blob.length());
}

int main() {
/*
init magick
*/
/*
assign img
*/
for (int i = 0; i < 300000; ++i) {
test();
}
return 0;
}

### System Configuration
centos4
gcc482

**Comment by dlemstra** [comment]
Which versions of the different libraries are you using? This could also be a bug in libde265, libheif or x265. It looks like we are doing the correct calls to that library but you might be using an old version that did this incorrectly. We really need more information.

**Comment by yo123abxd** [comment]
libde265 version:1.0.3  https://github.com/strukturag/libde265
libheif version:1.5.1  https://github.com/strukturag/libheif/
x265 version: 3.1.2  http://www.x265.org/
any else informations do you need? 
thank you for answering~

**Comment by dlemstra** [comment]
Can you reproduce the issue if you update those to the latest version? And are you using the latest version of ImageMagick?

**Comment by yo123abxd** [comment]
yes, I have tried latest version of ImageMagick, it was also leaking

**Comment by dlemstra** [comment]
I asked two questions can you please provide an answer to both?

**Comment by yo123abxd** [comment]
uhhhh, I am sorry for ignoring your first question, I will try to update those to the latest version and run again.

**Comment by dlemstra** [comment]
Can you explain why you closed thus issue @yo123abxd ?

**Comment by yo123abxd** [comment]
uhhhh, My boss arrange me to deal with other project, so I closed it.
