### ISSUE TITLE
Converting pfm to exr crops intensity at 1.0

### ISSUE THREAD

**Issue by gonsolo** [ImageMagick/ImageMagick#1809]
Hi!

When converting a floating point pfm file with a maximum brightness of 17 to an exr file the brightness is cropped at 1.0. When saving an pfm file in Gimp to exr the maximum brightness stays 17.

Additionally the pfm file was 32 bit float, the resulting exr is 16 bit float, the result from Gimp stays at 32 bit float.

Additionally Imagemagick sets the compression to None while Gimp compresses by default with zip, so the file is 1.9MB (Gimp) instead of 3.1MB (IM) down from 6.1MB from the original, despite being still at 32 bit.

Unfortunately I can't upload the pfm as the format is not supported on github.

**Comment by urban-warrior** [comment]
We need to reproduce the problem before we can offer a solution.  Post a link to your image on one of the free file hosting services such as Google Drive/Dropbox/etc..
