### ISSUE TITLE
MagickGetImageInterpolateMethod not in header file IM7.0.1

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#181]
The function MagickGetImageInterpolateMethod is listed as still being part of the api, and is in magick-image.c, but isn't listed in magick-image.h

Is it meant to be there?

**Comment by Danack** [comment]
Related - MagickSetImageInterpolateMethod seems to be missing entirely?

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
