### ISSUE TITLE
GIF image transcoding speed is too slow and quality is too large

### ISSUE THREAD

**Issue by jackDiscovery** [ImageMagick/ImageMagick#1812]
```
time convert pig-bug.gif -coalesce  -filter box  -resize 100x73  -layers Optimize pig_thumbnail_3.gif

real	0m0.431s
user	0m0.428s
sys	0m0.074s
```

```
time convert pig-bug.gif -coalesce  -filter box -layers Optimize -resize 100x73  pig_thumbnail_3.gif

real	0m3.081s
user	0m2.280s
sys	0m1.241s
```

Put the -layers Optimize command before and after the -resize command, the processing time is very different

**Comment by dlemstra** [comment]
I have no idea what you are trying to tell us?

**Comment by jackDiscovery** [comment]
> I have no idea what you are trying to tell us?
Gif transcoding performance is too slow. It takes 3s to process a picture at 50 frames. I am at http://www.imagemagick.org/Usage/anim_mods/#resize
It was found that the performance of the -layers Optimize command before and after -resize was different, and the time gap was several times.
How does the C code implement -layers Optimize in different locations?

**Comment by fmw42** [comment]
When you do -layers optimize, it compress the animated gif. If you do something afterwards, such as -resize, IM has to do the equivalent of -coalesce to decompress the animation before it can do the -resize. So you are adding an additional step of decompressing the effect of the -layers optimize

**Comment by jackDiscovery** [comment]
> When you do -layers optimize, it compress the animated gif. If you do something afterwards, such as -resize, IM has to do the equivalent of -coalesce to decompress the animation before it can do the -resize. So you are adding an additional step of decompressing the effect of the -layers optimize. So you should expect a longer processing time. So order of commands can change the processing result or timing.

The current purpose is to optimize the processing performance. By binding with golang, the related purpose cannot be achieved, but convert can,

          ```
  imgWand := imagick.NewMagickWand()
		 err = imgWand.ReadImageBlob(imgProcessor.SourceImage)
		 if err != nil {
			return nil
	         }
		 imageNum := imgWand.GetNumberImages()
		 imgWand = imgWand.CoalesceImages()
		 bordColor := imagick.NewPixelWand()
		 defer bordColor.Destroy()
		 bordColor.SetColor("#b0c4de")
		 //bordColor.SetColor("LightSteelBlue")
		 err := imgWand.SetImageBorderColor(bordColor)
		 if err != nil {
		 	return nil
		 }
                for index := 0; index < int(imageNum); index++ {
				imgWand.SetIteratorIndex(index)
				watermark, ok := operation.(WatermarkOperation)
				imgErr := operation.process(imgWand)
				if imgErr != nil {
					return nil, false, imgErr
				}
		}
		imgWand = imgWand.OptimizeImageLayers()
		startCodeTime2 := time.Now()
		retImg := imgWand.GetImagesBlob()
		errorLogger.Printf("GetImageBlobs used:%.0fms.", 
                time.Now().Sub(startCodeTime2).Seconds()*1000)

GetImageBlobs used:1980ms.
```
How do I do this, this has been a problem for me for a long time, please guide me

**Comment by jackDiscovery** [comment]
`convert pig-bug.gif -coalesce  -filter box  -resize 100x73  -layers Optimize pig_thumbnail_3.gif`

How to write the above command in C language, please give me a demo
