### ISSUE TITLE
-clahe is broken again

### ISSUE THREAD

**Issue by whugemann** [ImageMagick/ImageMagick#1813]
### Description
The -clahe option doesn't work in newest (Windows) version

### Steps to Reproduce
Just try to use -clahe 10%x10%+128+3.0 on any JPEG image 

### System Configuration
Windows 10, 64 bit

- ImageMagick version:
ImageMagick 7.0.9-9 Q16 x64 2019-12-17

After several trys at the end of 2018, I have stayed with

- ImageMagick 7.0.8-23 Q16 x64 2019-01-02
under Windows 10 64bit and with 

- ImageMagick 7.0.8-17beta -Q16-x86-dll 2018-12-12
on our Windows 7 32bit computers 

to avoid further difficulties with CLAHE.
(We use it on a daily basis in our office, as it is a really cool option for problematic photos.)

After one year pause, I now tried the current version of IM, and the -clahe option is not functioning again. It just produces no output at all (and no error messages either).

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
