### ISSUE TITLE
Issues with PNG > GIF conversion on recent versions

### ISSUE THREAD

**Issue by Mad182** [ImageMagick/ImageMagick#1819]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hello! A user of my website provided me some example files that fail to convert from PNG to GIF properly. Investigating this issue I found this is not the only case. Some files have messed up colors, and some operations involving resizing at the same step simply fail with "Aborted" displayed in terminal on latest versions. It seems the issue started at some release after 7.0.8-12 but before or at 7.0.9-9

Source image:
https://coding.lv/upload/mad/orig.png

I ran "convert -colors 255 -background none 1.png 1.gif" with various versions of ImageMagick and this was the output:

**ImageMagick 7.0.8-12 Q8 x86_64** and **ImageMagick 6.8.9-9 Q16 x86_64**
all fine:
https://coding.lv/upload/mad/6.8.9-9.gif

**ImageMagick 7.0.9-9 Q8 x86_64**
colors messed up:
https://coding.lv/upload/mad/7.0.9-9.gif

**ImageMagick 7.0.9-10 Q8 x86_64** and **ImageMagick 7.0.9-12 Q8 x86_64**
messed up, but differently:
https://coding.lv/upload/mad/7.0.9-12.gif

If it helps anything, I also got a stack trace or something like that running just convert 1.png 1.gif on 7.0.9-9 with the same file:
https://coding.lv/upload/mad/output.txt

### Steps to Reproduce

For the results above I ran:
> convert -colors 255 -background none orig.png result.gif

Some other parameters may cause it to fail completely, for example (on 7.0.9-12, but not 7.0.9-9):

> convert -colors 255 -background none orig.png -resize 1200x1200\> result.gif
> Aborted

(note that -resize part shouldn't even change anything in this instance, it just there to limit maximum size)

### System Configuration

> convert --version
> Version: ImageMagick 7.0.9-12 Q8 x86_64 2019-12-30 https://imagemagick.org
> Copyright: © 1999-2020 ImageMagick Studio LLC
> License: https://imagemagick.org/script/license.php
> Features: Cipher DPC HDRI OpenMP(4.5) 
> Delegates (built-in): bzlib djvu flif fontconfig freetype jbig jng jp2 jpeg lcms lzma pangocairo png tiff webp wmf x xml zlib

Running on Debian Linux, it's doing the same on Debian 9 and Debian 10.
> uname -a
> Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux

All versions mentioned above were compiled from source, except 6.8.9-9, which was installed from Debian repositories. Libraries are default from Debian repos.

**Comment by urban-warrior** [comment]
Unfortunately we cannot reproduce the problem.  We're using ImageMagick 7.0.9-12 under Fedora 31/CentOS 7/Mac OS X/Win 10.  Perhaps its a build or threading problem on Debian.  Configure ImageMagick 7.0.9-12 with this command:

`./configure --disable-openmp`

Now build/install.  Did that fix the problem?

**Comment by Mad182** [comment]
Adding --disable-openmp didn't change the result, but your comment gave me an idea to remove  --with-quantum-depth=8 parameter to keep everything to defaults, and it seems that fixed it. This only manifests in imagemagick Q8

I's running fine on 7.0.8-12 Q8 and 7.0.9-12 Q16, but produces wrong results on 7.0.9-12 Q8

I also reproduced it on a freshly installed and updated Debian minimal installation VPS to exclude any possible issues with specific config I have on my production machines (this issue manifests on all 7 o them).

If you want to repeat this on a fresh Debian box with default repos:

> sudo su

> apt-get install build-essential libpng*-dev libglib2.0-dev libfontconfig1-dev zlib1g-dev libxml2-dev libexif-dev libfreetype6-dev libjpeg-dev libtiff5-dev libwebp-dev webp libwmf-dev fftw-dev libdjvulibre-dev libbz2-dev libmng-dev libmng1 liblzma-dev liblcms2-dev libde265-dev libpango1.0-dev libopenjp2-*

> cd && rm -rf ./ImageMagick* && rm -rf ./sources && mkdir sources && cd sources/ && wget https://imagemagick.org/download/ImageMagick.tar.gz && tar xf ImageMagick.tar.gz && cd ImageMagick-* && ./configure --with-quantum-depth=8 --prefix=/usr && make && make install && ldconfig && convert --version

Recompiling with Q16 seems to have fixed the problem for me now.

**Comment by fmw42** [comment]
It works perfectly fine using IM 7.0.9.12 on Mac OSX Sierra with libpng 1.6.37 using proper syntax, which read the input **before** any operations. So

`magick orig.png -colors 255 -background none result.gif`

Note that without +dither before -colors, it will dither your colors.

Also it is possible that using convert rather than magick on IM 7 will cause IM 6 type processing. So best to use magick or be sure you have a symbolic link from convert to magick.

**Comment by Mad182** [comment]
Thanks, but the params actually doesn't matter for causing the bug to appear. 7.0.9.12  Q8 on Debian also fails without any additional params, but in that case it dosn't produce any output file at all:

> convert orig.png result.gif
> corrupted double-linked list (not small)
> Aborted

**Comment by fmw42** [comment]
Perhaps a Q8 or OpenMP 4.5 issue, since it works fine for me on Q16 with OpenMP 3.1.  What is your platform?

**Comment by Mad182** [comment]
Yes, I think it's a Q8 issue, as I wrote in a comment above, removing "--with-quantum-depth=8" from configure command seems to have fixed it for me. I tried it on Debian 9 and Debian 10.

**Comment by urban-warrior** [comment]
We're currently using IM 7.0.9-13 Beta and HDRIQ8 returns expected results for your command.  We'll try earlier releases to see if we can reproduce the problem.

**Comment by browlry** [comment]
I'm having a similar issue. Like Mad182, it affects v7.0.9, but not v7.0.8.

When I try to convert files to GIF or PDF, Imagemagick gets stuck on the "Dithering" step in versions 7.0.9-13 Q8 x64 (built from source) and 7.0.9-12 Q16 x64 (downloaded from https://imagemagick.org/script/download.php). I don't have the issue when using 7.0.8-42 Q16 x64 or 7.0.8-68 Q16 x64 (both downloaded from https://imagemagick.org/script/download.php).

In the 7.0.8 versions, I'm running a command like this:

`magick -monitor -density 100 scan-002.jpg -auto-threshold OTSU -type bilevel -compress fax scan-002_100dpi.pdf`

The "dithering" step usually takes less than five seconds. I'll see something like `Dither/Image/tiff:C:/Users/browlry/AppData/Local/Temp[magick-44445k8yHlS6TH-j]: 8691 of 8692, 100% complete` in the command output.

However, if I run the same command in one of the 7.0.9 versions, the dithering step takes so long that I haven't had the patience to let it finish yet. I'll see something like `dither image colors[C:\Users\browlry\temp\scan-002.jpg]: 65600 of 3740000, 01% complete`.

I'm not sure why the "dithering" operations to complete went from 9 thousand in v. 7.0.8 to 4 million in v.7.0.9.

I can work around this by adding the `+dither` option to turn off dithering. Once I do that, 7.0.9 gives me the same output as 7.0.8.

`magick -monitor -density 100 scan-002.jpg -auto-threshold OTSU +dither -type bilevel -compress fax scan-002_100dpi.pdf`

So it looks like there was a change in 7.0.9 where Imagemagick applies dithering in situations where it did not do so before.

In 7.0.9, I'm seeing the dithering issue on commands as simple as:

`magick -monitor scan-002.jpg scan-002.gif`
`magick -monitor scan-002.jpg scan-002.pdf`

but I don't see the dithering issue when I run a command like

`magick -monitor scan-002.jpg scan-002.png`

**Comment by fmw42** [comment]
GIF has to quantize to 256 colors, since its output is 8-bit palette. It uses the quantize function same as in -colors 256. So I guess without the +dither is does the same default as it does with -colors 256. Adding +dither turns off the default dithering. Not sure why it is doing very slow dithering nor why it dithers for PDF. But it may be connected to the recent change for -monochrome that needed dithering enabled. PNG does not need dithering for 24-bit format. It would if you used PNG8:scan-002.png
