### ISSUE TITLE
DrawGetStrokeOpacity not header for IM7.0.1

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#182]
The method DrawGetStrokeOpacity is in drawing-wand.c and is part of the public api http://www.imagemagick.org/api/drawing-wand.php#DrawGetStrokeOpacity, but apparently it isn't listed in a header.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
