### ISSUE TITLE
error: ‘class Magick::Color’ has no member named ‘redQuantum’

### ISSUE THREAD

**Issue by airglow923** [ImageMagick/ImageMagick#1820]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I compiled the latest ImageMagick 7 from github using the command:

`./configure --with-modules --enable-shared --with-perl && make && make install`

on Cygwin.

Then used `Magick::Color::redQuantum()` and received the following error:

`error: 'class Magick::Color' has no member named 'redQuantum'`

This could also be found when using greenQuantum and blueQuantum.

### Steps to Reproduce

Sample code used to reproduce the same error:

```
// sample.cpp
#include "ImageMagick-7/Magick++.h"

int main()
{
        Magick::Image image;
        image.read("");
        image.pixelColor(0, 0).redQuantum();
}
```

Command used to compile:
`` g++ `Magick++-config --cppflags --cxxflags` sample.cpp `Magick++-config --ldflags --libs` ``

### System Configuration

- ImageMagick version:
```
$ magick --version
Version: ImageMagick 7.0.9-12 Q16 x86_64 2019-12-30 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): ltdl lzma x zlib
```

- Environment (Operating system, version and so on):
```
$ uname -a
CYGWIN_NT-10.0 DESKTOP 3.0.7(0.338/5/3) 2019-04-30 18:08 x86_64 Cygwin
```

- Additional information:

```
$ gcc --version
gcc (GCC) 7.4.0
```

**Comment by dlemstra** [comment]
`redQuantum` has been renamed to `quantumRed` in ImageMagick 7.
