### ISSUE TITLE
when convert fails， a new tmp file create     

### ISSUE THREAD

**Issue by wangwei418** [ImageMagick/ImageMagick#1821]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
when i convert  image to webp. the command such as   :
    cat aa.jpg |convert  -   webp:-  >b 
if not success ,will be create a  tmp file in out project root path. file name is    "webp:-".
this file is a  binary，but b is empty.
the problem is that the file    "webp:-"  always exists,all the transformations that follow  for webp  are not  work, unless rm this file.
please help thanks

### System Configuration

- ImageMagick version: ImageMagick 7.0.4-2 Q16 x86_64
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
If the WebP image format is not supported by your instance of ImageMagick, webp:- simply becomes the output filename rather than the image sent to stdout.

The current release of ImageMagick is 7.0.9-13.  Consider upgrading your release of ImageMagick.

**Comment by wangwei418** [comment]
> If the WebP image format is not supported by your instance of ImageMagick, webp:- simply becomes the output filename rather than the image sent to stdout.
> 
> The current release of ImageMagick is 7.0.9-13. Consider upgrading your release of ImageMagick.

Thank you for your answer。
my instance of ImageMagick supported webp. that case i don`t knwow the reason,may be some image can not convert to webp.in my program have no exception throw
if one case,my server can not service for webp.
now i  will check the tmp file and remove it 
later  try upgrading ,thanks!
