### ISSUE TITLE
Access violation writing location on Image object constructor

### ISSUE THREAD

**Issue by parsamoradi73** [ImageMagick/ImageMagick#1823]
I am trying to define a new Image object and reading an image file by .read property
but in the first line of code I got this error:

Access violation writing location

I run my code in visual studio 2017
ImageMagick version: ImageMagick-7.0.9-13-Q16-x64-dll.exe
and I have linked include and lib directories VS project.

**Comment by dlemstra** [comment]
Could you also include a small code sample that reproduces this issue?

**Comment by parsamoradi73** [comment]
`Yes sure.
Image img;
img.read("path\\to\\file");

This error happened on the first line.

Actually, I want to copy opencv Mat data to Image object through code below:
Image img( src.rows, src.cols, "RGB", CharPixel, (char *)src.data );
but i saw that the problem comes from Image constructor

**Comment by dlemstra** [comment]
I suspect that something else in your program is corrupting the creation of the image. Did you call `InitializeMagick` and is your program also 64 bit?
