### ISSUE TITLE
Word repetition in resource management section of ltmain.sh

### ISSUE THREAD

**Issue by FabienLaunay** [ImageMagick/ImageMagick#1828]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The word **that** is unexpectedly repeated in the _resource management_ section of _ltmain.sh_.

### Steps to Reproduce
1. Open [config/ltmain.sh](https://github.com/ImageMagick/ImageMagick/blob/master/config/ltmain.sh)
2. Scroll to row 475
3. Note that the word **that** is unexpectedly repeated.

### System Configuration
Not applicable.

**Comment by urban-warrior** [comment]
We did not write nor do we maintain ltmain.sh.  See https://www.gnu.org/software/libtool/manual/html_node/Integrating-libtool.html.

**Comment by FabienLaunay** [comment]
@urban-warrior understood. I will report  this issue via a different channel. Thank you.
