### ISSUE TITLE
configure.ac:3159 comment needs to be commented out

### ISSUE THREAD

**Issue by nieder** [ImageMagick/ImageMagick#183]
During ./configure:
~~~~
checking for gzip... /sw/bin/gzip
./configure: line 36751: Apple: command not found
checking for Apple fonts directory... not found!
~~~~
Line 3159 in configure.ac should have a leading #.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
