### ISSUE TITLE
Word repetition in hook function management section of ltmain.sh

### ISSUE THREAD

**Issue by FabienLaunay** [ImageMagick/ImageMagick#1831]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The word **of** is unexpectedly repeated in the _hook function management_ section of _ltmain.sh_.

### Steps to Reproduce
1. Open [config/ltmain.sh](https://github.com/ImageMagick/ImageMagick/blob/master/config/ltmain.sh)
2. Scroll to row 1479
3. Note that the word **of** is unexpectedly repeated.

### System Configuration
Not applicable.

**Comment by dlemstra** [comment]
There is no need to create an issue for your pull request. Please describe what you have found in the PR instead.

**Comment by FabienLaunay** [comment]
Understood. Thanks for your comment.

**Comment by FabienLaunay** [comment]
Closing this issue following comment from @urban-warrior in #1828 .
