### ISSUE TITLE
Image can't be resized if there's a read-only property named `width` in the image. 

### ISSUE THREAD

**Issue by kiloreux** [ImageMagick/ImageMagick#1833]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When you try to resize an image that contains `width` in its properties. You get `can't set read-only property width`

### Steps to Reproduce
Try to apply any resize on this image.

https://drive.google.com/file/d/1OgTGtOFZ_XTPcsfc_X_n0-tA0usY4wIw/view?usp=sharing

### System Configuration

- ImageMagick version: 7.0.9-16
- Environment (Operating system, version and so on): Ubuntu 18.04
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by kiloreux** [comment]
Tested the fix. Works fine. Thank you very much.
