### ISSUE TITLE
cannot identify jpeg xr image when read from stdin

### ISSUE THREAD

**Issue by delgado3d** [ImageMagick/ImageMagick#1834]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
`identify` fails with `identify: no decode delegate for this image format` when reading a jpeg xr image from stdin. If same image was read from disk with `.jxr` extension, `identify` correctly detects the image.

### Steps to Reproduce
```
$ cat image.jxr | identify -
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/562.

$ identify image.jxr
image.jxr PPM 800x531 800x531+0+0 8-bit sRGB 1.21538MiB 0.010u 0:00.005
```

### System Configuration

- ImageMagick version: `ImageMagick 7.0.9-16 Q16 x86_64 2020-01-12`
- Environment (Operating system, version and so on): `macOS 10.15.2`
```
Version: ImageMagick 7.0.9-16 Q16 x86_64 2020-01-12 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(3.1)
Delegates (built-in): bzlib freetype heic jng jp2 jpeg lcms ltdl lzma openexr png tiff webp xml zlib
```

Update:
Image: https://dex-div-pub.s3-ap-southeast-1.amazonaws.com/image.jxr

**Comment by dlemstra** [comment]
Can you share the file?

**Comment by fmw42** [comment]
Have you installed the jxrlib delegate on your Mac? It looks like you may have not. When using identify directly, it seems to be interpreting your file as PPM and not JXR. Does magick -version list jxr as a delegate?

**Comment by fmw42** [comment]
I am not an expert on JXR nor Brew, but I suspect it never got properly installed in ImageMagick. One of the IM developers will have to comment further.

**Comment by dlemstra** [comment]
The JXR format is loaded with the help of third party executable. When the file has the `.jxr` extension ImageMagick knows that it needs to execute that delegate. In your case it needs to determine the format from the first few bytes of the image but that is not supported for this image format.
