### ISSUE TITLE
Trim: defined background color does not work

### ISSUE THREAD

**Issue by spajak** [ImageMagick/ImageMagick#1837]
It looks like `trim:background-color` parameter for [-trim](https://imagemagick.org/script/command-line-options.php#trim) is totally ignored. No matter what color is set, the output is always the same:

```
magick.exe test.tif -fuzz 1% -define "trim:background-color=#FFFFFF" -trim +repage test.jpg
```

Windows 10

Version: ImageMagick 7.0.9-16 Q16 x64 2020-01-12 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib

**Comment by fmw42** [comment]
It only works with -define trim:percent-background=0%

**Comment by spajak** [comment]
So it should be written in the docs. (Anyway, I see no reason why it could not work without `percent-background` also)

**Comment by fmw42** [comment]
You should not need it for the normal trim. What is your situation where you think you need to use that define? Can you post an input, your command and show an output that did not work the way you think it should?

**Comment by spajak** [comment]
My input are scanned documents. `-trim` uses left-top pixel value as its reference color. But, if you have a scan, this pixel value can vary, and if its too dark or too bright my fuzz factor may be too small (and I want too keep fuzz factor as low as possible). My current solution is to use `-shave` then `-bordercolor` and `-border`. But its like a workaround. I was thinking `trim:background-color` could replace those 3 switches, and make whole command shorter.

**Comment by fmw42** [comment]
-trim looks at all four sides as I understand it. But I will let the IM developers respond better. I still do not understand your issue. Scanned documents have issues with dust and other spots on the document that can prevent -trim from working well. Assigning a color does not solve that as far as I understand your issue. Can you post and example image and show what your issue is?

**Comment by spajak** [comment]
Assigning `-trim` reference color manually *does* help me to decrease fuzz value, because I know an average background color of my scans. Corner pixels are not an average - they may vary from scan to scan. I get better results if I set my calculated color using `-border`.
