### ISSUE TITLE
Multi-layer PSD with alpha channels is read as three channel image.

### ISSUE THREAD

**Issue by mp-t** [ImageMagick/ImageMagick#1838]
### Description
PSD blobs with multiple layers that contain three color channel and an alpha channel are read in as a three color channel image, omitting the alpha.

See also https://github.com/ImageMagick/ImageMagick/issues/1485 for a report about single layer PSDs.

### Steps to Reproduce
```
Magick::Blob blob;
// data is a multi-layer PSD with four channels
blob.update(data, size);
Magick::Image image(blob);
assert(image.alpha()); // fails on newer versions
```
This file should reproduce the behavior: [alpha_test.zip](https://github.com/ImageMagick/ImageMagick/files/4086013/alpha_test.zip)

### System Configuration
Works on older versions:
ImageMagick 6.8.6 Q16
ImageMagick 7.0.8-9 Q16

Does not work on:
ImageMagick 7.0.9-16 Q16

Please also see https://github.com/ImageMagick/ImageMagick/issues/1485
The behavior changed between these versions and the current build.

**Comment by dlemstra** [comment]
Did you also test this with the latest version (7.0.9-17)?
