### ISSUE TITLE
-distort Resize madness on tiff first converted to mpc

### ISSUE THREAD

**Issue by dirteat** [ImageMagick/ImageMagick#1839]
Version 7.0.8

### Description

Trying to use the -distort Resize method on an mpc file created from a tiff file produced an image in which the RGB channels seems to be spread over 3 different columns. It is not easy to explain with wording, so the way to reproduce is this:

### Steps to Reproduce

convert input.tif input.mpc
convert input.mpc -distort Resize AxB! output_AB.mpc
convert output_AB.mpc output_AB.png

output_AB.png is showing this 3 columns RGB stripes all over the picture (or grey stripes if the input if grayscale).

NB. For instance, take this as input.tif, resize to AxB=5000x5000
https://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73934/gebco_08_rev_elev_A1_grey_geo.tif

What is amazing is that the following is working fine:
convert input.tif -distort Resize AxB! output_AB.png

output_AB.png is fine and resized as wanted.

### System Configuration
Linux mageia 7
- ImageMagick version: 7.0.8

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dirteat** [comment]
Great, it works! Thanks a lot, closing then!
