### ISSUE TITLE
Converting series of PNGs to MNG ignores "-dispose Background" option.

### ISSUE THREAD

**Issue by amackenzie** [ImageMagick/ImageMagick#1840]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am converting a folder of PNGs (with transparent backgrounds, if that matters) into a single MNG animation using `convert -dispose Background -delay 2 ./$1/*.png -loop 0 ./output/$1.mng`.

The animation itself comes out correctly, however, the dispose option appears to be completely ignored, so as the animation plays, the previous frames persist and clutter up the image.

Converting to a GIF works fine, as well as playing it using `animate`.

Another user appeared to have run into this issue a while ago at https://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=33667 , but there does not appear to have been a resolution then as well.

### Steps to Reproduce

1. Run `convert -dispose Background -delay 2 ./*.png -loop 0 ./output..mng` with a series of PNGs available.
2. Check the result using a viewer to see the persistent frames lingering (irfanview in this case).

### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on): FreeBSD 12.0-RELEASE-p3 amd64 with ImageMagick 7.0.8-57 Q16 amd64 2019-09-21
- Additional information: N/A

**Comment by dlemstra** [comment]
The `-dispose Background -delay 2` should be specified after the files are read.
