### ISSUE TITLE
identify: Unsupported file-type: Unspecified: File does not support the 'heic' brand.

### ISSUE THREAD

**Issue by shanemcquillan** [ImageMagick/ImageMagick#1841]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm receiving the error message "identify: Unsupported file-type: Unspecified: File does not support the 'heic' brand." when running `identify` with the attached image (attached as archive because Github doesn't seem to allow directly uploading .heic image). This is working without issue with other .heic files:

I'm seeing this on latest install using Homebrew.

[image.heic.zip](https://github.com/ImageMagick/ImageMagick6/files/4131522/image.heic.zip)

### Steps to Reproduce
Execute:

    identify image.heic

### System Configuration

- ImageMagick version: ImageMagick 7.0.9-20
- Environment (Operating system, version and so on): macOS 10.14.4
- Additional information:

**Comment by urban-warrior** [comment]
ImageMagick utilizes the libheif delegate library to read and write the HEIC image format.  You'll need to contact the libheif developers to resolve this problem.  We cannot help.

**Comment by shanemcquillan** [comment]
Filed here - https://github.com/strukturag/libheif/issues/199
