### ISSUE TITLE
24-bit floating point TIFF doesn't load properly

### ISSUE THREAD

**Issue by jonsneyers** [ImageMagick/ImageMagick#1842]
### Description
TIFF files containing 24-bit FP data are loaded incorrectly – it looks like the data is interpreted as 32-bit FP, causing the left 3/4 of the image to be a garbled version of the actual image, and the right 1/4 to be empty (black).

### Steps to Reproduce
This zip file contains a TIFF which was created with Photoshop, saved as 24-bit FP.
Photoshop does produce a warning when selecting that option: "Not all TIFF readers support 24 bit floating point values.  Use 24 bit values?"
[test.zip](https://github.com/ImageMagick/ImageMagick/files/4153273/test.zip)

Converting it to PNG using `convert` produces the following:
![test-24bit tif](https://user-images.githubusercontent.com/15010068/73745483-6aed0f80-4753-11ea-8b38-c3f6ebe903bd.png)

While it should look like this:
![test-16bit tif](https://user-images.githubusercontent.com/15010068/73745492-6f192d00-4753-11ea-8ab5-46b440834677.png)
(this is what `convert` produces when the input is a 16-bit half-float TIFF)

### System Configuration
This was tested on a stock IM 6, but I don't think newer versions (e.g. IM 7) will behave differently.
- ImageMagick version: 6.9.10-14 Q16 x86_64 20181023
- Environment (Operating system, version and so on): Ubuntu

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick in a few days.  The patch will also be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ in a few days.
