### ISSUE TITLE
imagemagick 'convert' can't deal with pdf more than 100 pages

### ISSUE THREAD

**Issue by GongSiqiu** [ImageMagick/ImageMagick#1844]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I want to enhance the contrast of a pdf file. When I deal with more than 100 pages, convert works well at beginning and I can see jpgs in /tmp. But then the CPU and memory usage become 100% . Finally, this command was 'terminated by signal SIGKILL (Forced quit)'
### Steps to Reproduce

1. convert -density 50 origin.pdf   -level 70,90% -quality 50 out.pdf
2. wait

convert -density 50 origin.pdf[1-99]   -level 70,90% -quality 50 out.pdf worked well while [101-200] failed
### System Configuration

- ImageMagick version: ImageMagick 7.0.8-64 Q16 x86_64 2019-09-13
- Environment (Operating system, version and so on): debian 10
- Additional information:

**Comment by urban-warrior** [comment]
Per https://imagemagick.org/script/architecture.php#tera-pixel, try this command:

```
magick -memory 2GiB -limit map 4GiB -define registry:temporary-path=./ \
  -density 50 origin.pdf -level 70,90% -quality 50 out.pdf
```

**Comment by GongSiqiu** [comment]
Thank you very much! Finally I use
`magick -monitor -limit memory 2Gib map 4GiB  -define registry:temporary-path=./ \
  -density 50 origin.pdf -level 70,90% -quality 50 out.pdf`
because 
magick: unrecognized option `-memory' at CLI arg 1 @ fatal/magick-cli.c/ProcessCommandOptions/428.
