### ISSUE TITLE
[Build error]  undefined reference to `GOMP_loop_nonmonotonic_dynamic_next'

### ISSUE THREAD

**Issue by rubyFeedback** [ImageMagick/ImageMagick#1845]
I am trying to compile version:

  ImageMagick-7.0.9.23

I do run into this error though:

  CCLD     utilities/magick
/usr/bin/ld: warning: libjpeg.so.8, needed by /usr/lib/libtiff.so, may conflict with libjpeg.so.62
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `GOMP_loop_nonmonotonic_dynamic_next'
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `GOMP_loop_nonmonotonic_dynamic_start'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:7870: utilities/magick] Error 1
make[1]: Leaving directory '/Depot/j/ImageMagick-7.0.9.23'
make: *** [Makefile:5988: all] Error 2
make install
make  install-am
make[1]: Entering directory '/Depot/j/ImageMagick-7.0.9.23'
  CCLD     utilities/magick
/usr/bin/ld: warning: libjpeg.so.8, needed by /usr/lib/libtiff.so, may conflict with libjpeg.so.62
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `GOMP_loop_nonmonotonic_dynamic_next'
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `GOMP_loop_nonmonotonic_dynamic_start'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:7870: utilities/magick] Error 1
make[1]: Leaving directory '/Depot/j/ImageMagick-7.0.9.23'
make: *** [Makefile:12266: install] Error 2

I am quite sure that e. g. 7.0.9.15 compiled fine. Not sure what is GOMP
but perhaps it is related to something that may be broken or missing on my
system. In this case perhaps it could be shown what may be missing.

(I compile everything from source; only glibc is a bit old but the rest is
very up-to-date.)

i. e. my system is like this:

    Operating system                GNU/Linux
    Operating system bit type       x86_64 (64 bit)
    CPU Model                       AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G, 4 cores
    RAM                             14954 MB RAM
    cflags in use                   -O2 -fPIC -fno-strict-overflow -Wno-error
    gcc                             9.2.0 
    glibc                           2.23  
    linux kernel                4.4.14 # I can test with a more recent kernel but I don't think it makes a difference
    binutils                        2.34

**Comment by urban-warrior** [comment]
Looks like you are not linking to libgomp with -lgomp?  You can try to manually fix the problem, or add --disable-openmp on your configure script command-line and rebuild/reinstall ImageMagick.  This disable OpenMP which likely not what you want-- because without OpenMP, ImageMagick will only run on one of your cores.
