### ISSUE TITLE
Blank SVGs generated

### ISSUE THREAD

**Issue by kiloreux** [ImageMagick/ImageMagick#1846]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I try to resize this SVG, it generates a blank SVG instead of a normal one.

https://drive.google.com/file/d/1KacenoNmqzY1uRbUq6hfRY47ZBINl2Cp/view?usp=sharing

### Steps to Reproduce
convert file.svg -auto-orient -background none -flatten -resize 1364x result.svg

### System Configuration
Issue appears in `7.0.8-65` if that helps.

Also tested the latest version 7.0.9-24

- ImageMagick version: 7.0.9-24
- Environment (Operating system, version and so on): Linux Ubuntu 18.04
- Additional information:

**Comment by urban-warrior** [comment]
Use inkscape to convert SVG to SVG.   ImageMagick will leverage the autotrace delegate library if your instance of ImageMagick has it built-it as a feature.  Without autotrace enabled, ImageMagick makes a best effort to produce a wonky SVG.  In your instance, it did not do a good job.

**Comment by kiloreux** [comment]
It seems like this version of ImageMagick uses `potrace` instead of `autotrace`. And I already have potrace delegate enabled.

**Comment by kvz** [comment]
Can we try to make our version of imagemagick use Inkscape instead of potrace tho @kiloreux ?

**Comment by kiloreux** [comment]
I tried that as part of autotrace efforts. It doesn't work I'm afraid. It will still generate an empty blank SVG.

**Comment by kvz** [comment]
Could we see what change was introduced in 7.0.8-65 that would result in blank svgs for Inkscape as we as potrace and autotrace?

**Comment by urban-warrior** [comment]
Inkscape changed their command-line options.  If your inkscape version < 1.0, you need to manually change `export-file` to `export-png` in delegates.xml.  There is a comment in the file to help guide you.

**Comment by kiloreux** [comment]
> @kiloreux does the version before that work, with all three or a subset of those?

Yeah, it works just fine, without autotrace though.

**Comment by kvz** [comment]
What if we try with the imagemagick straight from their website, vs our own Nix build?
