### ISSUE TITLE
classify  color image and monochrome image

### ISSUE THREAD

**Issue by xuanson97hg** [ImageMagick/ImageMagick#1849]
Some body help me explane  command :
$ convert img.png -colorspace HSB -separate -delete 0 -fx "u*v" -blur 2x2 -threshold 30% -format '%[fx:mean]\n' info:
 i want classify color image and monochrome image

**Comment by fmw42** [comment]
It converts the image to HSB color space. Then deletes the Hue. Then multiplies the Saturation and Brightness channels, blurs them, then threshold. Then finally gets the average over the full thresholded image. I have no idea what the purpose is unless you can give more context or provide a link to where it was used.

**Comment by xuanson97hg** [comment]
@fmw42  Can you tell me why delete h channel and what mean of threshold. Please

**Comment by fmw42** [comment]
I have no idea what the purpose of that is without further context. Where did you find that command? They apparently want the product of the Saturation and the Brightness for some reason that I do not know without further context. Thresholding means to convert the image into binary (black and white only), making 70% of the image white and 30% black.

**Comment by xuanson97hg** [comment]
@fmw42  i It converts the image to HSB color space. Then deletes the Hue. Then multiplies the Saturation and Brightness channels get has result is  grey_image but it not like magick result

**Comment by fmw42** [comment]
You need to identify what tool you are using and what is being done. I cannot help review your command line compared to something I cannot test.

**Comment by xuanson97hg** [comment]
![imagemgaick7_result](https://user-images.githubusercontent.com/41713335/75424877-24668b80-5974-11ea-939b-f43b8dc9398a.jpg)
![image_by_me](https://user-images.githubusercontent.com/41713335/75424893-2b8d9980-5974-11ea-8d3c-c5ef792d7fe4.JPG)

**Comment by xuanson97hg** [comment]
@fmw42  this is Result image magick 7  and my result when i delete hue channel Then multiplies the Saturation and Brightness channels . My result so bad! . how to like result image magick . I want classcify image color and image monochrome if it has mean color lager 0.00 after convert binary image by cmd:
$ convert img.png -colorspace HSB -separate -delete 0 -fx "u*v" -blur 2x2 -threshold 30% -format '%[fx:mean]\n' info:

**Comment by fmw42** [comment]
Is the first image your input or a result from somewhere else?  If it is the input, it is grayscale and it does not make sense to convert to HSB. Please post your color input image.
