### ISSUE TITLE
Not possible to pick the Compose option from identify -format on psd files

### ISSUE THREAD

**Issue by ingolfured** [ImageMagick/ImageMagick#185]
I'm trying to extract the Compose attribute like so from an PSD file:

```
identify -verbose some.psd | grep Compose
```

only, I want to use the `identify -format`. Any ideas how to accomplish that?

**Comment by dlemstra** [comment]
This is not possible with the current version of ImageMagick but I just pushed a patch to add support for this. You will be able to do this in the next version:

```
C:\Users\Dirk>identify -format "%[compose]" logo:
Over
```
