### ISSUE TITLE
Does it support multiple languages, I think I can participate in the translation

### ISSUE THREAD

**Issue by cws999** [ImageMagick/ImageMagick#1850]
Does it support multiple languages, I think I can participate in the translation

**Comment by urban-warrior** [comment]
Download the ImageMagick source and change to the `config` folder.  Copy `english.xml` to your favorite language as defined in `locale.xml`.  For example, assume you want to translate into Italian.    Copy `english.xml` to `italian.xml`.  Edit `italian.xml`, leave the tags as is but change the English messages to Italian.  Contribute your translation with a git pull request and we will include it in the ImageMagick distribution.  Your contribution assume you agree with the ImageMagick license @ https://imagemagick.org/script/license.php.

**Comment by cws999** [comment]
ok
