### ISSUE TITLE
Composite bitonal tiff onto bitonal tiff produces unexpected results

### ISSUE THREAD

**Issue by kevindente** [ImageMagick/ImageMagick#1851]
### Description
I have a small bitonal TIFF (text rendered into an image) that I'm tiling over another bitonal TIFF as a watermark. The watermark image has black text.  However, on the resulting image, the watermark text shows as white, not black.

If I composite a PNG version of the watermark image, it works as expected (black text)

### Steps to Reproduce
composite -tile <watermarkimage.tif> <baseimage.tif> out.png

- ImageMagick version:
7.0.9-23

- Environment (Operating system, version and so on):
macOS Catalina

**Comment by fmw42** [comment]
Please post a link to your two input TIFF files

**Comment by kevindente** [comment]
[
[im_testimages.zip](https://github.com/ImageMagick/ImageMagick/files/4268348/im_testimages.zip)

](url)

**Comment by kevindente** [comment]
In this case, wm.tif is the image being tiled, and black.tiff is the background.

**Comment by fmw42** [comment]
I do not understand what you expect. When I do either of these with IM 6.9.10.96 Q16 Mac OSX, I get white text over black.

```
composite -tile wm.tif black.tiff out.png
composite -tile wm.png black.tiff out.png

```

Likewise, with IM 7.0.9.26 Q16 Mac OSX, for 

magick composite -tile wm.tif black.tiff out.png
magick composite -tile wm.png black.tiff out.png

What do you expect? If you put black text onto a black image, you will not see the text!  What are you getting?
