### ISSUE TITLE
ImageMagick version 7.0.9-8, the RGB white picture is rotated 90 degrees and the grey picture is turned

### ISSUE THREAD

**Issue by jackDiscovery** [ImageMagick/ImageMagick#1855]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:
7.0.9-8

`convert mix_cut_white.jpg -rotate 90 -background white white.jpg`

![src](https://user-images.githubusercontent.com/33868757/75643274-757ac600-5c79-11ea-8000-bc7ac3c4759d.jpg)

**Comment by fmw42** [comment]
Set the background before the rotate:

`convert mix_cut_white.jpg -background white -rotate 90 white.jpg`

**Comment by jackDiscovery** [comment]
> Set the background before the rotate:
> 
> `convert mix_cut_white.jpg -background white -rotate 90 white.jpg`

Still a gray picture
Still a gray picture, the previous version 7.0.7-11 is okay, but it wo n’t work after the upgrade

**Comment by fmw42** [comment]
If on IM 7, use magick in place of convert.

**Comment by t246246** [comment]
It seems working with ImageMagick 7.0.9-17 Q16 x86_64 2020-01-21 using your file.

**Comment by jackDiscovery** [comment]
> It seems working as expected with ImageMagick 7.0.9-17 Q16 x86_64 2020-01-21 using your file.

The image before rotate is (RGB / 8 #) and the image after rotate is (gray / 8 #). There are images in the issue.

**Comment by jackDiscovery** [comment]
> It seems working as expected with ImageMagick 7.0.9-17 Q16 x86_64 2020-01-21 using your file.

Still a gray picture
The image before rotate is (RGB / 8 #) and the image after rotate is (gray / 8 #). There are images in the issue.

**Comment by fmw42** [comment]
On IM 7 try:

`magick mix_cut_white.jpg -background white -rotate 90 -type truecolor white.jpg`

On IM 6 try:

`convert mix_cut_white.jpg -background white -rotate 90 -type truecolor white.jpg`

If those fail, post a link to your input image so we can test with it.

**Comment by t246246** [comment]
Imagmagick will try to do some optimize when converting.  Similar issue will be found at https://github.com/dlemstra/Magick.NET/issues/376 . IMO there should be a option to keep it as RGB, but currently you should have to give option by yourself (as in Fred's message above.)

@fmw42 The image is attached at the first message. (it is downloadable from white area.)

**Comment by t246246** [comment]
If -define auto-grayscale=off dose not work, this seems to be a bug. (Sorry I cannot try it now.)

**Comment by fmw42** [comment]
This works for me on IM 6.9.10.97 Q16 Mac OSX

```
convert white.jpg -background white -rotate 90 -type truecolor x.jpg
identify x.jpg
```
Colorspace: sRGB


Note that it is:

`-define **colorspace**:auto-grayscale=on\|off`

prevent automatic conversion to grayscale inside coders that support grayscale. _This should be accompanied by **-type truecolor**.  PNG and TIF do not need this define. With PNG, just use PNG24:image. With TIF, just use -type truecolor. JPG and PSD will need this define.

**Comment by jackDiscovery** [comment]
> This works for me on IM 6.9.10.97 Q16 Mac OSX
> 
> ```
> convert white.jpg -background white -rotate 90 -type truecolor x.jpg
> identify x.jpg
> ```
> 
> Colorspace: sRGB
> 
> Note that it is:
> 
> -define **colorspace**:auto-grayscale=on|off
> 
> prevent automatic conversion to grayscale inside coders that support grayscale. _This should be accompanied by_ **-type truecolor**. PNG and TIF do not need this define. With PNG, just use PNG24:image. With TIF, just use -type truecolor. JPG and PSD will need this define.

Thank you. The problem has been resolved. After adding -type truecolor, I still don't understand why the new version will have problems?
