### ISSUE TITLE
Core dumped convert svg

### ISSUE THREAD

**Issue by dhiogoboza** [ImageMagick/ImageMagick#1858]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I found similar issues but it is possible that my crash have a different root cause.

### Description
When I try to convert the image attached [image.svg.zip](https://github.com/ImageMagick/ImageMagick/files/4282888/image.svg.zip) a crash happens: Aborted (core dumped).

### Steps to Reproduce
`convert image.svg image.png`
or
`convert image.svg image.jpg`

### System Configuration
Ubuntu 16.04
ImageMagick:
Version: ImageMagick 6.8.9-9 Q16 x86_64 2019-11-12 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib

- ImageMagick version: 8:6.8.9.9-7ubuntu5.15
- Environment: Ubuntu 16.04

**Comment by fmw42** [comment]
It works fine for me using IM 6.9.10.97 Q16 Mac OSX with Inkscape doing the SVG rendering via ImageMagick. ImageMagick can use any of 3 different renderers: MSVG/XML (internal to IM), RSVG delegate or Inkscape if it is on your system.  Which renderer are you using. The first two will show up when you do `convert -list format` and look at the end of the line for SVG. I see your convert -version shows RSVG. So I assume you are using that. You may need to upgrade ImageMagick and/or install Inkscape. Or perhaps just upgrade RSVG.

**Comment by urban-warrior** [comment]
The image works for the latest releases of ImageMagick.  It was a bug likely fixed some time ago.  Try installing the latest release and try again:

```
$ sudo apt install imagemagick-devel
$ wget https://imagemagick.org/download/ImageMagick.tar.gz
$ tar xvf ImageMagick.tar.gz
$ cd ImageMagick-7*
$ ./configure
$ make
$ sudo make install
$ convert image.svg image.png
```

**Comment by dhiogoboza** [comment]
> It works fine for me using IM 6.9.10.97 Q16 Mac OSX with Inkscape doing the SVG rendering via ImageMagick. ImageMagick can use any of 3 different renderers: MSVG/XML (internal to IM), RSVG delegate or Inkscape if it is on your system. Which renderer are you using. The first two will show up when you do `convert -list format` and look at the end of the line for SVG. I see your convert -version shows RSVG. So I assume you are using that. You may need to upgrade ImageMagick and/or install Inkscape. Or perhaps just upgrade RSVG.

I run `convert -list format` and the output for SVG was:
```
SVG  SVG       rw+   Scalable Vector Graphics (RSVG 2.40.13)
SVGZ  SVG       rw+   Compressed Scalable Vector Graphics (RSVG 2.40.13)
```

I try with inkscape using `inkscape --file image.svg --export-png image.png` and the conversion was successfully! Thanks for the fast response and support!

**Comment by dhiogoboza** [comment]
> The image works for the latest releases of ImageMagick. It was a bug likely fixed some time ago. Try installing the latest release and try again:
> 
> ```
> $ sudo apt install imagemagick-devel
> $ wget https://imagemagick.org/download/ImageMagick.tar.gz
> $ tar xvf ImageMagick.tar.gz
> $ cd ImageMagick-7*
> $ ./configure
> $ make
> $ sudo make install
> $ convert image.svg image.png
> ```

I try to follow your steps but there is no installation candidate for `imagemagick-devel` for me:
```
E: Unable to locate package imagemagick-devel
```

I am using Ubuntu 16.04. With inkscape the conversion was successfully. Thanks for the fast response and support!

**Comment by urban-warrior** [comment]
It might be called `imagemagick-dev`.  Type `apt list | grep -i imagema` to find the correct package name.

**Comment by dhiogoboza** [comment]
Here are the output for the commands:

```
$ imagemagick-dev
imagemagick-dev: command not found
```

```
$ apt list | grep -i imagema

graphicsmagick-imagemagick-compat/xenial-updates,xenial-updates,xenial-security,xenial-security 1.3.23-1ubuntu0.6 all
imagemagick/xenial-updates,xenial-security,now 8:6.8.9.9-7ubuntu5.15 amd64 [installed]
imagemagick-6.q16/xenial-updates,xenial-security,now 8:6.8.9.9-7ubuntu5.15 amd64 [installed]
imagemagick-common/xenial-updates,xenial-updates,xenial-security,xenial-security,now 8:6.8.9.9-7ubuntu5.15 all [installed,automatic]
imagemagick-dbg/xenial-updates,xenial-security 8:6.8.9.9-7ubuntu5.15 amd64
imagemagick-doc/xenial-updates,xenial-updates,xenial-security,xenial-security 8:6.8.9.9-7ubuntu5.15 all
kimagemapeditor/xenial 4:15.12.3-0ubuntu1 amd64
```
