### ISSUE TITLE
Error while installing imagemagick on os x 10.11.4

### ISSUE THREAD

**Issue by rajashreekm** [ImageMagick/ImageMagick#186]
See ./test-suite.log
Please report to https://github.com/ImageMagick/ImageMagick/issues
============================================================================
make[3]: *** [test-suite.log] Error 1
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
make: *** [check] Error 2

**Comment by mikayla-grace** [comment]
Your report does not provide enough information, we need to know which tests failed.  The tests have logs, such as tests/validate-formats-memory.log which will include the reason for the failure.  Some failures are expected.  For example, some tests attempt to convert Postscript.  They are expected to fail if you don't have Ghostscript installed on your system.

**Comment by dlemstra** [comment]
Can you provide us with more information @rajashreekm ?
