### ISSUE TITLE
no codec for HEIC

### ISSUE THREAD

**Issue by BDN001** [ImageMagick/ImageMagick#1863]
I have an issue with converting HEIC to JPG: 

(server): $HOME/ImageMagick-7.0.10-0/bin/convert IMG_0621.HEIC IMG_0621.JPG
convert: Unsupported feature: Unsupported codec `IMG_0621.HEIC' @ error/heic.c/IsHeifSuccess/136.
convert: no images defined `IMG_0621.JPG' @ error/convert.c/ConvertImageCommand/3282.

I am using the latest version of ImageMagick
Version: ImageMagick 7.0.10-0 Q16 x86_64 2020-03-10 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.0) 
Delegates (built-in): heic jng jpeg png zlib

Together with libde265-1.0.5 and libheif-1.6.2

Delegate library configuration:
  BZLIB             --with-bzlib=yes		no
  Autotrace         --with-autotrace=no		no
  DJVU              --with-djvu=yes		no
  DPS               --with-dps=yes		no
  FFTW              --with-fftw=yes		no
  FLIF              --with-flif=yes		no
  FlashPIX          --with-fpx=yes		no
  FontConfig        --with-fontconfig=yes	no
  FreeType          --with-freetype=yes		no
  Ghostscript lib   --with-gslib=no		no
  Graphviz          --with-gvc=yes		no
  HEIC              --with-heic=yes             yes
  JBIG              --with-jbig=yes		no
  JPEG v1           --with-jpeg=yes		yes
  JPEG XL           --with-jxl=yes    no
  LCMS              --with-lcms=yes		no
  LQR               --with-lqr=yes		no
  LTDL              --with-ltdl=yes		no
  LZMA              --with-lzma=yes		no
  Magick++          --with-magick-plus-plus=yes	yes
  OpenEXR           --with-openexr=yes		no
  OpenJP2           --with-openjp2=yes		no
  PANGO             --with-pango=yes		no
  PERL              --with-perl=no		no
  PNG               --with-png=yes		yes
  RAQM              --with-raqm=yes		no
  RAW               --with-raw=yes 	   	no
  RSVG              --with-rsvg=no		no
  TIFF              --with-tiff=yes		no
  WEBP              --with-webp=yes		no
  WMF               --with-wmf=yes		no
  X11               --with-x=			no
  XML               --with-xml=yes		no
  ZLIB              --with-zlib=yes		yes
  ZSTD              --with-zstd=yes		no

I have searched open and closed issues and cannot find anything that resolves this issue. There is reference to /IsHeifSuccess/136 in issue 'can't create/convert to HEIC image format #1755' but no resolution, and a generic google search returns relatively little, 
The image was taken today on an iPhone 7Plus iOS 13.3.1, and the server is Debian v8. I have successfully used brew to install ImageMagick on Mac and convert the same image. I followed the steps in 1and1 support:

https://www.ionos.co.uk/help/server-cloud-infrastructure/managed-dedicated-server/install-imagemagick-over-ssh/

...but had to supplement this with libde265, libpng and libheif first. 

Any help would be appreciated.

**Comment by NavinF** [comment]
I had the same issue. Run ` ./configure`  in `libheif` and confirm that it prints 
`configure: libde265 decoder: yes`

If it says "no", go ahead and rebuild libde265  and wrangle with autotools/pkg-config, the crappiest build system still in use, until it says "yes". (The libde265 readme only has instructions for cmake, but that didn't work for me. Try ./autogen.sh)

I built ImageMagick from source and converted some iOS images just now, so I know it's doable. 

You could also narrow down the problem space by trying https://github.com/strukturag/libheif#example-programs

**Comment by BDN001** [comment]
Thanks both, I will give it another try! :-)
