### ISSUE TITLE
no decode delegate for this image format `PNG'

### ISSUE THREAD

**Issue by ostrolucky** [ImageMagick/ImageMagick#1865]
### Description
Imagemagick complains about having no delegate for png, even though it's listed in both --version and -list configure

### How to reproduce
```
0# convert Winter-Gloves-PNG-Background-Image.png wat.jpg
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/562.
convert: no images defined `wat.jpg' @ error/convert.c/ConvertImageCommand/3273.
```

Use this image
![Winter-Gloves-PNG-Background-Image](https://user-images.githubusercontent.com/496233/76938777-85400e80-68f7-11ea-8bf8-7e1972a01913.png)

### System Configuration
```
# convert --version
Version: ImageMagick 7.0.9-7 Q16 x86_64 2019-12-03 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jng jpeg lcms ltdl lzma png ps rsvg tiff webp x xml zlib
# convert -list configure
Path: [built-in]

Name                  Value
-------------------------------------------------------------------------------
DELEGATES             bzlib cairo fontconfig freetype gslib heic jng jpeg lcms ltdl lzma png ps rsvg tiff webp x xml zlib
FEATURES              Cipher DPC HDRI Modules
MAGICK_TEMPORARY_PATH /tmp
NAME                  ImageMagick
QuantumDepth          Q16
convert: unable to access configure file `configure.xml' @ warning/configure.c/GetConfigureOptions/699.
bash-5.0# convert Winter-Gloves-PNG-Background-Image.png wat.jpg
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/562.
convert: no images defined `wat.jpg' @ error/convert.c/ConvertImageCommand/3273.
```

**Comment by ostrolucky** [comment]
I discovered the problem. Here is good reproducer for environment where this happens.
```
FROM alpine:3.11
RUN apk add --no-cache --virtual .build-deps imagemagick-dev
RUN apk add --repository https://nl.alpinelinux.org/alpine/edge/community imagemagick
```

So yeah issue is on my side because I'm mixing stuff from different repositories. HOWEVER, ImageMagick should still handle this better, instead of lying about PNG being supported, then fail.

**Comment by scholarboss** [comment]
> I discovered the problem. Here is good reproducer for environment where this happens.
> 
> ```
> FROM alpine:3.11
> RUN apk add --no-cache --virtual .build-deps imagemagick-dev
> RUN apk add --repository https://nl.alpinelinux.org/alpine/edge/community imagemagick
> ```
> 
> So yeah issue is on my side because I'm mixing stuff from different repositories. HOWEVER, ImageMagick should still handle this better, instead of lying about PNG being supported, then fail.

Hi, I met the same problem. 
```
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/562.
convert: no images defined `./exposure_A_2355160.mpc' @ error/convert.c/ConvertImageCommand/3282.

--- FILE vina.png NOT READABLE OR HAS ZERO SIZE ---
```
could you tell me how do you solve it?

**Comment by ostrolucky** [comment]
By removing `--repository https://nl.alpinelinux.org/alpine/edge/community`
