### ISSUE TITLE
ImageMagick convert -crop returns the same image

### ISSUE THREAD

**Issue by En3pY** [ImageMagick/ImageMagick#1868]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am having a really odd behavior when using **convert -crop** feature. When invoking a fairly simple command like the following:

/usr/bin/convert -crop 652x369+928+519 /tmpdir/heading.jpg /tmpdir/crop.jpg

crop.jpg is the same output as heading.jpg.

By doing something like 100 tests on different samples, I found out it doesn't happen on a regular basis and I couldn't find the reason why.

The original image (heading.jpg) is a simple image file, 1920x1080px in resolution. I made the following tests. **works** are the commands that are executed with success, **fails** are the commands where crop.jpg are perfect clones of heading.jpg.

/usr/bin/convert -crop 100x100 heading.jpg crop.jpg   works
/usr/bin/convert -crop 100x200 heading.jpg crop.jpg   works
/usr/bin/convert -crop 200x100 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x200 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x300 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x369 heading.jpg crop.jpg   fails
/usr/bin/convert -crop 652x368 heading.jpg crop.jpg   fails
/usr/bin/convert -crop 652x367 heading.jpg crop.jpg   fails
/usr/bin/convert -crop 652x366 heading.jpg crop.jpg   fails
/usr/bin/convert -crop 652x365 heading.jpg crop.jpg   fails
/usr/bin/convert -crop 652x364 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x363 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x362 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x361 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x360 heading.jpg crop.jpg   works

I tested this with different files format (but I mostly work with jpg files) and resolutions, and can't predict - and therefore find a solution - to the issue. With or without offset information the same behavior occurs.

### Steps to Reproduce
```
/usr/bin/convert -crop 100x100 heading.jpg crop.jpg   works
/usr/bin/convert -crop 100x200 heading.jpg crop.jpg   works
/usr/bin/convert -crop 200x100 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x200 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x300 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x369 heading.jpg crop.jpg   fails
/usr/bin/convert -crop 652x368 heading.jpg crop.jpg   fails
/usr/bin/convert -crop 652x367 heading.jpg crop.jpg   fails
/usr/bin/convert -crop 652x366 heading.jpg crop.jpg   fails
/usr/bin/convert -crop 652x365 heading.jpg crop.jpg   fails
/usr/bin/convert -crop 652x364 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x363 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x362 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x361 heading.jpg crop.jpg   works
/usr/bin/convert -crop 652x360 heading.jpg crop.jpg   works
```

### System Configuration
The issue happens on a CentOS 7.7.1908.

Also tried upgrading ImageMagick, so I have the very same behavior on:

- 6.7.8.9 (yum package ImageMagick-6.7.8.9-18.el7.x86_64)
- 7.0.10-1 (rpm from ImageMagick website)

**Comment by fmw42** [comment]
Your syntax is incorrect. Read the input before -crop command. This is especially important for IM 7.  Try that and see if that fixes the issue. I note that IM 6.7.8.9 has had issues. Update if you can.

**Comment by En3pY** [comment]
I fixed the order of the input file, and it seems to have improved the situation. I am doing more tests on different input images, whereas I still have some unexpected result on some pictures.

The problem persisted on 6.7 (changing orders didn't help) whereas on 7.0.10 seems to be working but with the above considerations. I will post an update after I will have some more results.

**Comment by fmw42** [comment]
As I mentioned above, I have experienced problems with IM 6.7.8.9. So it is conceivable that is the source of your difficulty.
