### ISSUE TITLE
configure --with-openjp2 can't switch library path

### ISSUE THREAD

**Issue by yoya** [ImageMagick/ImageMagick#1869]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

configure --with-openjp2 option disables the OpenJP2 delegate when an arbitrary library path is specified.

### Steps to Reproduce

```
% ./configure --with-openjp2=/Users/yoya/openjpeg/2.3.0

(...)

  OpenJP2           --with-openjp2=/Users/yoya/openjpeg/2.3.0		no

(...)
```

### System Configuration

- ImageMagick version: ImageMagick-7.0.10-2
- Environment (Operating system, version and so on): macOS Catalina (10.15.3), GNU bash version 3.2.57(1)-release (x86_64-apple-darwin19)
- Additional information: 

It seems that there are options with similar problems besides openjp2.

* OK (library path can specified)

```
if test "$with_jpeg" != 'no'; then
  AC_MSG_RESULT([-------------------------------------------------------------]\
)
```

--with-bzlib
--with-dps
--with-flif
--with-fpx
--with-gslib
--with-jpeg
--with-jxl
--with-tiff
--with-wmf
--with-perl

* NG (disabled when library is specified)

```
if test "x$with_openjp2" = "xyes"; then
  AC_MSG_RESULT([-------------------------------------------------------------]\
)
```

--with-zlib
--with-zstd
--with-autotrace
--with-fftw
--with-djvu
--with-fontconfig
--with-freetype
--with-raqm
--with-gvc
--with-heic
--with-big
--with-lcms
--with-openjp2
--with-lqr
--with-lzma
--with-openexr
--with-pango
--with-png
--with-raw
--with-rsvg
--with-webp
--with-xml

**Comment by urban-warrior** [comment]
See pkg-config.  You'll need to build a custom libopenjp2.pc file and refer to its location with the PKG_CONFIG_PATH environment variable.  Now rerun the ./configure script.  If it still fails, refer to config.log to discover why, fix the problem, and try again.

**Comment by yoya** [comment]
thank you very much!
