### ISSUE TITLE
Issue (or misunderstanding) with '^' geometry operator

### ISSUE THREAD

**Issue by TheMaikXX** [ImageMagick/ImageMagick#1870]
### Description
Unexpected behaviour occured while using ```-resize``` option inside ```magick mogrify``` tool.
I need to make from images (with varying dims - and aspect ratios) squared thumbnails.
I do this inside Elixir and there is lib ```Mogrify``` that has ```resize_to_fill``` function that really does "fill" because it passes either ```widthx``` or ```xheight``` (which partly solves my problem but my images dont have unified orientation) but this lib only processes one image at a time.. But I (think) dont have this control over param passed to ```-resize``` option. I tried using the ```^``` operator to make original image fill given geometry but it turned out to be fit operation..

My goal is to resize image to fill given area (even overflow thats ok) and then crop from center final size. but resize does not make fill but fit instead..

### Steps to Reproduce
- (ommited mogrify)
- original image (in my case with dims: ```960x365```)
- execute inside Windows Command Prompt ```magick convert -resize 100x100^ input.jpeg output.jpeg```
- output.jpeg has dims ```100x38``` not ```263x100```

### System Configuration
- ImageMagick version:
```magick -version
Version: ImageMagick 7.0.7-25 Q8 x64 2018-03-04 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr openexr pangocairo png ps raw rsvg tiff webp xml zlib
```
- Environment (Operating system, version and so on):
![image](https://user-images.githubusercontent.com/30082602/77349172-e5d9ac00-6d3a-11ea-8536-d5449a5e899b.png)
- Additional information:

**Comment by TheMaikXX** [comment]
Tried also with version ```Version: ImageMagick 7.0.10-2 Q16 x64 2020-03-22 http://www.imagemagick.org``` with no luck neither

**Comment by fmw42** [comment]
Proper ImageMagick syntax is to read the image before any commands. Also for IM 7, use magick not magick convert. 

On Windows, ^ is an escape character and so needs to be doubled to escape it. So try

`magick input.jpeg -resize 100x100^^  output.jpeg`

**Comment by TheMaikXX** [comment]
> On Windows, ^ is an escape character and so needs to be doubled to escape it. So try

Nice! that did the trick.. Thanks for quick response

> Proper ImageMagick syntax is to read the image before any commands. Also for IM 7, use magick not magick convert.

ah, ok but that was just for demo.. this issue originated from scenario where I use mogrify which seems that it needs first options than input image.. e.g:
```
magick mogrify ( -resize "200x200^^" -format webp -path "output_images\200" ) "input_images\*"
  ( -resize "75x75^^" -format webp -path "output_images\75" ) "input_images\*"
```
When I tried to specify input images first, nothing appeared in ```output_images\{75,200}``` dir nor the input images were modified. (I know that I didnt specified last arg output as output in this case although I still had that ```-path "..."``` inside each sequence of image midifiers

But thanks. You helped me a lot :)

**Comment by fmw42** [comment]
Correct. Mogrify has a different order and the input images are specified last. Mogrify is much older that magick or convert. But I do not think the parentheses are needed, thought will not hurt.

I assume you have two different command lines above and that they are not chained into one command line -- correct? If they are chained, then that would not work as far as I know.

**Comment by TheMaikXX** [comment]
Yes, that's right. I format original images, together with another
pipelines that create some thumbnail sizes - just resize, crop and format..
no real magick yet :)

**Comment by fmw42** [comment]
Good. Glad to hear the ^^ fixed your issue.
