### ISSUE TITLE
Multi-value of jp2:quality does not work

### ISSUE THREAD

**Issue by yoya** [ImageMagick/ImageMagick#1873]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

-  https://imagemagick.org/script/jp2.php

> jp2:quality=x,x,...	set the quality layer PSNR, given in dB. The order is from left to right in ascending order. The default is a single lossless quality layer.

Even if the values of jp2:quality are arranged in ascending order as described above, it's still an error because it should be in descending order. 

### Steps to Reproduce

- I want it to work
```
% convert rose: -define jp2:quality=10,20,30 rose.jp2
convert: tcp_rates[1]=0.000000 (corrected as 1.000000) should be strictly lesser than tcp_rates[0]=0.000000 (corrected as 1.000000)
 `OpenJP2' @ warning/jp2.c/JP2WarningHandler/237.
convert: tcp_rates[2]=0.000000 (corrected as 1.000000) should be strictly lesser than tcp_rates[1]=0.000000 (corrected as 1.000000)
 `OpenJP2' @ warning/jp2.c/JP2WarningHandler/237.
```

 -  superfluous
```
% convert rose: -define jp2:quality=30,20,10 rose.jp2
convert: tcp_rates[1]=0.000000 (corrected as 1.000000) should be strictly lesser than tcp_rates[0]=0.000000 (corrected as 1.000000)
 `OpenJP2' @ warning/jp2.c/JP2WarningHandler/237.
convert: tcp_rates[2]=0.000000 (corrected as 1.000000) should be strictly lesser than tcp_rates[1]=0.000000 (corrected as 1.000000)
 `OpenJP2' @ warning/jp2.c/JP2WarningHandler/237.
```

### System Configuration

- ImageMagick version: 7.0.10-3
- Environment (Operating system, version and so on):macOS Catalina (10.15.3), OpenJPEG 2.3.1
- Additional information:

OpenJPEG checks the tcp_rates array, even though ImageMagick sets the tcp_distoratio array to a value in jp2:quality.
Probably because ImageMagick set cp_disto_alloc=1 at the beginning to make the default lossless, but did not set cp_disto_alloc back to 0 just by setting cp_fixed_quality=1 when jp2:quality is specified.

**Comment by urban-warrior** [comment]
Thanks for the patch.  It appears to resolve the problem you reported.

**Comment by yoya** [comment]
Here's what I tested with the ImageMagick/master HEAD (3c92cc113675d82c87d07c9965d01baa7efc3db7) branch. 
It is as expected.

```
% ~/ImageMagick/master/bin/convert rose: -quality 10 rose.jp2
% ~/ImageMagick/master/bin/convert rose: -define jp2:quality=10,20,30 rose.jp2
% identify  rose.jp2
rose.jp2 JP2 70x46 70x46+0+0 8-bit sRGB 0.000u 0:00.000
%
% ~/ImageMagick/master/bin/convert rose: -define jp2:quality=30,20,10 rose.jp2
convert: tcp_distoratio[1]=20.000000 should be strictly greater than tcp_distoratio[0]=30.000000
 `OpenJP2' @ warning/jp2.c/JP2WarningHandler/237.
convert: tcp_distoratio[2]=10.000000 should be strictly greater than tcp_distoratio[1]=20.000000
 `OpenJP2' @ warning/jp2.c/JP2WarningHandler/237.
```

 Thank you.
