### ISSUE TITLE
Please, add support for MacOS 10.9

### ISSUE THREAD

**Issue by effolkronium** [ImageMagick/ImageMagick#1875]
### Description

convert
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /opt/.CyFIR/bin/ImageMagic_darwin/bin/convert
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /opt/.CyFIR/bin/ImageMagic_darwin/bin/convert
  Expected in: /usr/lib/libSystem.B.dylib

**### Can be fixed with this environment variable for clang compiler:**

**export MACOSX_DEPLOYMENT_TARGET=10.9**

**or with flag --mmacosx-version-min=10.9**

### Steps to Reproduce
**convert --version**

### System Configuration

- ImageMagick version: 7.0.10-2 Q16 x86_64 2020-03-17
- Environment MacOS 10.9

**Comment by urban-warrior** [comment]
We added the MACOSX_DEPLOYMENT_TARGET environment variable as you suggested.  Thanks.
