### ISSUE TITLE
bug: HEIC files are converted to an empty 0 byte PNG

### ISSUE THREAD

**Issue by NavinF** [ImageMagick/ImageMagick#1876]
### Steps to Reproduce
```
$ magick identify IMG_1746.heic
IMG_1746.heic HEIC 4032x3024 4032x3024+0+0 8-bit YCbCr 0.000u 0:00.003
$ magick convert IMG_1746.heic out.png
convert: Success `out.png' @ error/heic.c/IsHeifSuccess/136.
$ ls -l out.png
-rwxrwxrwx 1 navin navin 0 Mar 26 08:26 out.png
```

### System Configuration
Ubuntu on WSL
Compiled from source
```
$ magick convert --version
Version: ImageMagick 7.0.10-2 Q16 x86_64 2020-03-26 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in): heic
```

Sample file: https://github.com/NavinF/junk/blob/master/IMG_1746.heic?raw=true

Same file is successfully decoded by https://strukturag.github.io/libheif/

**Comment by NavinF** [comment]
Seems like I didn't build libpng. Fixed with
```
sudo apt install libpng-dev
./configure --with-heic=yes --with-png
sudo make install
```

Leaving the bug report open because the error is very misleading ( `convert`  should not print "convert: Success" when it failed) and it should never emit an empty file.

**Comment by dlemstra** [comment]
The convert success message is probably an error from the libheif library. I had a similar issue this weekend and submitted a patch to get a better error message.
