### ISSUE TITLE
Buggy behavior when pdf filename contains ‘:’

### ISSUE THREAD

**Issue by NightMachinary** [ImageMagick/ImageMagick#1877]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When I use this zsh function

```
pdf-cover () {
 convert "$1[0]" "$1:r.png"
}
```

on files whose names contain `:`:

- Version 6.9:

```
convert-im6.q16: must specify image size b.pdf' @ error/raw.c/ReadRAWImage/136.
convert-im6.q16: no images defined a:b.png' @ error/convert.c/ConvertImageCommand/3258.
```

- Latest version (7.0.10):

No error but the output is invalid png.

I’m on Ubuntu.

**Comment by urban-warrior** [comment]
Try "pdf:$1[0]" to explicitly set the image file to PDF.  By default, ImageMagick performs a best guess on the input image format.

**Comment by NightMachinary** [comment]
> Try "pdf:$1[0]" to explicitly set the image file to PDF. By default, ImageMagick performs a best guess on the input image format.

Thanks! This works:

```
pdf-cover () {
 convert "pdf:$1[0]" "png:$1:r.png"
}
```

I think a warning for other people is a good idea.

**Comment by urban-warrior** [comment]
There is a discussion about implicit and explicit filenames @ https://imagemagick.org/script/command-line-processing.php#anatomy.
