### ISSUE TITLE
Please don't include any headers inside your C++ namespaces

### ISSUE THREAD

**Issue by dubhater** [ImageMagick/ImageMagick#188]
Inevitably your project's header(s) will include some system header or other, and then you end up with stdlib functions that are invisible to unsuspecting users because they're living inside your project's own namespace.

Specifically, this bit of code: https://github.com/ImageMagick/ImageMagick/blob/fd3938350bb00f1fd96467ba4e91af25774801dc/Magick++/lib/Magick++/Include.h#L40

In Blob.cpp:
```C++
#include "Magick++/Include.h"
#include "Magick++/Blob.h"
```

In Include.h:
```C++
namespace MagickCore
{
#include <MagickCore/MagickCore.h>
#include <MagickWand/MagickWand.h>
#undef inline // Remove possible definition from config.h

#undef class
}
```

In Blob.h:
```C++
#include <string>
```

``<string>`` includes ``<cwchar>``, which can't find standard C functions like wcscat, because whatever header declares them was included inside the MagickCore namespace.

GCC's protests:
```
  CXX      Magick++/lib/Magick___lib_libMagick___7_Q16HDRI_la-Blob.lo
In file included from /usr/i686-w64-mingw32/include/c++/5.1.0/bits/postypes.h:40:0,
                 from /usr/i686-w64-mingw32/include/c++/5.1.0/bits/char_traits.h:40,
                 from /usr/i686-w64-mingw32/include/c++/5.1.0/string:40,
                 from ../Magick++/lib/Magick++/Blob.h:13,
                 from ../Magick++/lib/Blob.cpp:13:
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:177:11: error: ‘::wcscat’ has not been declared
   using ::wcscat;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:178:11: error: ‘::wcscmp’ has not been declared
   using ::wcscmp;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:179:11: error: ‘::wcscoll’ has not been declared
   using ::wcscoll;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:180:11: error: ‘::wcscpy’ has not been declared
   using ::wcscpy;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:181:11: error: ‘::wcscspn’ has not been declared
   using ::wcscspn;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:183:11: error: ‘::wcslen’ has not been declared
   using ::wcslen;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:184:11: error: ‘::wcsncat’ has not been declared
   using ::wcsncat;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:185:11: error: ‘::wcsncmp’ has not been declared
   using ::wcsncmp;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:186:11: error: ‘::wcsncpy’ has not been declared
   using ::wcsncpy;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:188:11: error: ‘::wcsspn’ has not been declared
   using ::wcsspn;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:193:11: error: ‘::wcstok’ has not been declared
   using ::wcstok;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:196:11: error: ‘::wcsxfrm’ has not been declared
   using ::wcsxfrm;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:204:11: error: ‘::wcschr’ has not been declared
   using ::wcschr;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:205:11: error: ‘::wcspbrk’ has not been declared
   using ::wcspbrk;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:206:11: error: ‘::wcsrchr’ has not been declared
   using ::wcsrchr;
           ^
/usr/i686-w64-mingw32/include/c++/5.1.0/cwchar:207:11: error: ‘::wcsstr’ has not been declared
   using ::wcsstr;
           ^
```

The system is Arch Linux. The ImageMagick version is 7.0.1-0, from tarball.

**Comment by dlemstra** [comment]
I don't think the `<string>` headers are included inside the MagickCore or the Magick namespace. Can you clarify how it is included? The `<MagickCore/MagickCore.h>` and `<MagickWand/MagickWand.h>` don't include the `Blob.h` header file. I don't understand why you get this error message, it builds without problems on my Windows and Ubuntu machine.

**Comment by dubhater** [comment]
It goes like this:
Blob.cpp ->
Magick++/Include.h ->
begin namespace MagickCore ->
MagickCore/MagickCore.h ->
MagickCore/utility.h ->
/usr/i686-w64-mingw32/include/sys/stat.h ->
/usr/i686-w64-mingw32/include/io.h ->
/usr/i686-w64-mingw32/include/string.h (declares wcscat and friends)
end namespace MagickCore.

Here is Blob.cpp after preprocessing: [Blob.txt](https://github.com/ImageMagick/ImageMagick/files/251967/Blob.txt). The relevant stuff starts at line 8577.

**Comment by dubhater** [comment]
Same problem with 7.0.2-0.

**Comment by dlemstra** [comment]
Can you apply my patch on your machine and tell me if this patches fixes your issue?

**Comment by dubhater** [comment]
Yes, that fixes the errors mentioned earlier. Thank you.
