### ISSUE TITLE
Caught exception: gravity: unable to read font `helvetica' @ erro$ not ok FAIL: Magick++/demo/demos.tap 5

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [ImageMagick/ImageMagick#1890]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Caught exception: gravity: unable to read font `helvetica' @ erro$
not ok
FAIL: Magick++/demo/demos.tap 5

### Steps to Reproduce

```
make check
```
```
==========================================
   ImageMagick 7.0.10: ./test-suite.log
==========================================

# TOTAL: 86
# PASS:  85
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: Magick++/demo/demos
=========================

1..24
File: /Users/charlielee/ImageMagick-7.0.10-4/Magick++/demo//model$
  TopLeftColor     =
  TopRightColor    =
  BottomLeftColor  =
  BottomRightColor =
  filter:brightness:mean = 28064.7
  filter:brightness:standard-deviation = 14301.2
  filter:brightness:kurtosis = 0.845075
  filter:brightness:skewness = 1.40394
  filter:saturation:mean = 14866.4
  filter:saturation:standard-deviation = 16329
  filter:saturation:kurtosis = 3.25558
  filter:saturation:skewness = 2.06652
```
### System Configuration

- ImageMagick version:
Version: ImageMagick 7.0.10-4 Q16 x86_64 2020-04-11 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib freetype heic jng jp2 jpeg lcms lzma openexr png tiff webp x xml zlib

- Environment (Operating system, version and so on):
macOS Catalina 10.15.3
- Additional information:

**Comment by urban-warrior** [comment]
See https://imagemagick.org/script/advanced-unix-installation.php where it says:

> Ghostscript iand Freetype are prerequisites, otherwise certain unit tests that render text and the EPS, PS, and PDF formats will likely fail.

**Comment by urban-warrior** [comment]
See https://imagemagick.org/script/advanced-unix-installation.php where it says:

> Ghostscript and Freetype are prerequisites, otherwise certain unit tests that render text and the EPS, PS, and PDF formats will likely fail.
