### ISSUE TITLE
Resource limit for area not respected

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#19]
Hi, 

Please can you advise what I can possibly be doing wrong for ImageMagick to not be respecting the 'Area' resource limit. For the code below, I would expect the image to not be read, as it is far larger than the area resource limit set programmatically. I've also tried setting the area resource in the policy.xml, and that also seems to have no effect.

Images are taken from ftp://ftp.aerasec.de/pub/advisories/decompressionbombs/pictures/ - for obvious reasons not linked directly.

Tested against 6.9.1-4

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <malloc.h>
#include <wand/MagickWand.h>
    
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>


int main(int argc,char **argv) {
    MagickWand *magick_wand;
    MagickBooleanType status;

    MagickWandGenesis();
    magick_wand = NewMagickWand();

    MagickSetResourceLimit(AreaResource, 1000 * 1000);

    status = MagickReadImage(magick_wand, "./images/picture-100M-6000x6000.png");

    if (status == MagickFalse) {
        printf("Failed to MagickReadImage");
        return -1;
    }

    printf("This shouldn't be reached - the image is larger than the area resource.\n");

    MagickSetImageFormat(magick_wand, "png");

    status = MagickWriteImages(magick_wand, "./output/resource_output.png", MagickTrue);
    if (status == MagickFalse) {
        printf("Failed to MagickWriteImages");
        return -1;
    }

    MagickWandTerminus();
 
    return(0);
}

```

**Comment by urban-warrior** [comment]
If an image exceeds any area limit, it is cached to disk rather than memory.  If the image exceeds the disk limit, execution is halted.  You can prevent large images from being read by setting the Width / Height limits.

**Comment by Danack** [comment]
Thanks.
