### ISSUE TITLE
with-method-prefix seems to be broken

### ISSUE THREAD

**Issue by vhuber** [ImageMagick/ImageMagick#1912]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In [this](https://github.com/ImageMagick/ImageMagick/commit/ed300af85f0b74302fa100f4f35fb9c24c8b79af#diff-861cd4c8f9784eca13ed12ac26eb5bb2) commit, Cristy removed - among others - the line
```c++
#define GetMagickQuantumDepth  PrependMagickMethod(GetMagickQuantumDepth)
```
As a result, I if understand correctly, I can not use for that particular function the prefix I want to embed, which is unconvenient since a thirdparty embed an old ImageMagick version that generates conflicts for my application.

What should I do ?

### System Configuration
Linux/RedHat
- ImageMagick version: 7.0.10
- Environment RedHat / Gcc
- Additional information:

**Comment by urban-warrior** [comment]
These defines are auto-generated from a script.  We corrected the script and regenerated the method names which now include GetMagickQuantumDepth.  In the mean-time, you should be able to add the GetMagickQuantumDepth define to your headers and get the desired effect.

**Comment by vhuber** [comment]
I've simply get the last commit to get my problem solved.

Thank you

**Comment by vhuber** [comment]
@urban-warrior Do you have a planing to release 7.0.10-8 (https://imagemagick.org/download/) ?

**Comment by urban-warrior** [comment]
Yes, this weekend.
