### ISSUE TITLE
PSD Layer Labels over 31 characters in length are truncated

### ISSUE THREAD

**Issue by tohann** [ImageMagick/ImageMagick#1917]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When editing a PSD, we have a few layers that have labels that are over 31 characters in length. Using identify to analyze the image, the long layer labels are truncated at 31 characters.

### Steps to Reproduce
Create PSD with a layer that has a long label, > 31 characters.
Run identify on the PSD and the output will show the truncated layer label.

### System Configuration

- ImageMagick version: Version: ImageMagick 7.0.9-8 Q16 x86_64 2019-12-09 https://imagemagick.org
- Environment (Operating system, version and so on): macOS Mojave
- Additional information:

**Comment by dlemstra** [comment]
Can you share a PSD file that demonstrates this issue?

**Comment by tohann** [comment]
Thank you for your quick response. The PSDs I've been working with are from a client, so I'm working to get permission from them to share them with you. In the meantime...

I'm trying to nail down the issue. I created a new PSD that has just 2 layers. One layer has a short label, and the second layer has a label that matches one that was truncated in another PSD. This new PSD *did not* have the label truncated when using identify.

The client's PSDs typically have many, many layers (average would be 100-250 layers, 85mb in file size). I started with one of their PSDs, and removed layers to get down to a more manageable test file. After removing about 50 layers, the truncation issue disappeared. The layers that were previously truncated now show in full when using identify.

So, I'm not sure if this is a file size issue, or number of layers issues, or an issue with how the PSDs are created or something else. I'm still running a few tests. I will share the problematic PSD as soon as I get approval from the client.

**Comment by dlemstra** [comment]
You can always share the file privatly by email if that is more convenient for your client.

**Comment by tohann** [comment]
Thank you. Email sent with problematic PSD attached.

**Comment by dlemstra** [comment]
Turns out those label are really truncated. I don't know why but they are limited to 32 bytes. But the layer names are also stored in the additonal info of the layer. Will need to investigate if and how we could read the information from there.

**Comment by dlemstra** [comment]
This feature has been added in ImageMagick 7.0.10-9.

**Comment by tohann** [comment]
Confirmed this issue is fixed. Thanks for taking care of it!
