### ISSUE TITLE
convert animate gif to animate webp problem

### ISSUE THREAD

**Issue by 809481244** [ImageMagick/ImageMagick#1927]
when i use the command to convert animate gif to animate webp
`convert g.gif g.webp` 
there are some problem like below images:

![before](https://user-images.githubusercontent.com/25897065/80168679-0fc20f00-8616-11ea-86de-f76985eb65ce.gif) |  ![after](https://user-images.githubusercontent.com/25897065/80168932-bc03f580-8616-11ea-8ed4-66f22d1fd17a.gif)
------|------
before.gif | after.webp

but when i use the command of libwebp
`gif2webp -lossy g.gif -o g.webp`
everything is ok.

please help me!

**Comment by fmw42** [comment]
I can confirm the results are bad on IM 7.0.10.7 Q16 Mac OSX. But I do not know enough about webp define options specified at https://imagemagick.org/script/webp.php to know which ones might help. I think the Imagemagick developers may need to look at this.

**Comment by 809481244** [comment]
My server os is Ubuntu 18.04.3 LTS  and ImageMagic version is 7.0.10-3 Q16
