### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [ImageMagick/ImageMagick#193]
Would you like to [replace any double quotes](https://github.com/ImageMagick/ImageMagick/blob/06f590165f0505d42005264893fe14a9e8a79986/Magick%2B%2B/lib/Magick%2B%2B/Image.h#L12 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by dlemstra** [comment]
We should use double quotes according to the stackoverflow post that you linked. Can you clarify why you think we should change this?

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by dlemstra** [comment]
> #include <file>
    This variant is used for system header files.

> #include "file"
    This variant is used for header files of your own program.

Those includes are header files of our own program so I really don't understand why we would want to change that.

**Comment by elfring** [comment]
Are any include statements specified in source files which belong to one of your software libraries?

**Comment by dlemstra** [comment]
The example from your first post are our include files so yes they are.

**Comment by elfring** [comment]
Would you like to distinguish a bit more between include statements in source files for software libraries and ordinary programs?

**Comment by dlemstra** [comment]
I am sorry but you lost me. I don't understand what you are asking us to change.

**Comment by elfring** [comment]
I suggest to replace double quotes by angle brackets around file names for include statements in source files which belong to a software library.

**Comment by dlemstra** [comment]
All your links suggest that we should not change from double quotes to angle brackets so we will keep it like this.

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?
