### ISSUE TITLE
caption: problem with vertical bounding box overflow

### ISSUE THREAD

**Issue by olsln** [ImageMagick/ImageMagick#1932]
### Description
Working with text in images, I have a problem with fonts that use bounding box overflow as it's called in http://www.imagemagick.org/Usage/text/#overflow. When using caption: to fill a region, this overflow is not considered as it should.

### Steps to Reproduce
1. This renders okay, the lines overlap as expected for this font:
`magick -background '#800' -size 360x120 -font Matrix-Bold caption:"multiline reproducer" 1.jpg`
![1](https://user-images.githubusercontent.com/64224741/80247218-f947a200-866d-11ea-9459-edfca02c0338.jpg)

2. As a workaround, I normally use some extra interline spacing, which is fine as well:
`magick -background '#800' -size 360x120 -font Matrix-Bold -interline-spacing 30 caption:"reproducer extra spacing ok" 2.jpg`
![2](https://user-images.githubusercontent.com/64224741/80247363-36139900-866e-11ea-9b25-7612764b75e2.jpg)

3. ... until you use to much of it:
`magick -background '#800' -size 360x120 -font Matrix-Bold -interline-spacing 70 caption:"reproducer extra spacing fail" 3.jpg`
![3](https://user-images.githubusercontent.com/64224741/80247435-53486780-866e-11ea-9fc2-992f8ac741c9.jpg)

4. ... or make the image smaller:
`magick -background '#800' -size 360x80 -font Matrix-Bold caption:"multiline reproducer" 4.jpg`
![4](https://user-images.githubusercontent.com/64224741/80247251-082e5480-866e-11ea-992f-bb66f9dfc67f.jpg)

The last two are unexpected to me. As I understand it, "caption:" is supposed to fill the given space, which it doesn't. The complete last line should be part of the image. I'd expect either the last pixel of the font color to be still in the image, or maybe even the whole enlarged space under the last line - you could well argue for a fix in both directions. But I'd prefer the former, as inter line spacing should rather mean between lines and not from line to image border.

I had a similar problem with the font "Loki-Cola" where e.g. "C" has a wide overflow to the right, but that was with the rather old version 6.8.9-9. The current version gives me the expected result, which ensures me that the text cut off in half above is indeed a bug:
5. `magick -size 80x80 -background lightblue -font Loki-Cola caption:"C" 5.jpg`
![5](https://user-images.githubusercontent.com/64224741/80248137-9d7e1880-866f-11ea-885e-50e98cb86eb9.jpg)

As you can see, the part of the letter that's overflowing the bounding box remains visible here. I guess there has been a bounding box fix for horizontal overflow already. But vertical overflow still seems to be a problem.

A fixed "caption" would be best, but for the meantime, is there any suitable workaround?

The only thing I found was guessing to make the image the right amount of pixels larger than required so that around half a line can be added at the bottom, which should be enough for all letters to render correctly (as in image number 2). But that is not feasible when auto-generating large amounts of images with texts of different lengths.

### System Configuration

- ImageMagick version: `Version: ImageMagick 7.0.10-6 Q16 x86_64 2020-04-07 https://imagemagick.org`
- `Delegates (built-in): bzlib djvu fontconfig freetype gvc jbig jng jpeg lcms lqr lzma openexr png raqm tiff wmf x xml zlib`
- Environment (Operating system, version and so on): `Linux Mint 18 Sarah`

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by olsln** [comment]
It changed but if I understood the purpose of "caption:" correctly it is not fixed yet.

As I am not able to build ImageMagick with support to render fonts on my system, I had to wait for the binaries.

Now I tried with `Version: ImageMagick 7.0.10-9 Q16 x86_64 2020-04-26 https://imagemagick.org`

The result:
- `magick -background '#800' -size 360x120 -font Matrix-Bold -interline-spacing 70 caption:"reproducer extra spacing fail" 3new.jpg`
![3new](https://user-images.githubusercontent.com/64224741/80619341-e1449980-8a44-11ea-954d-cef84f9335c7.jpg)

My expectation: Use the available space and break the text. That was the intent of "caption:", I guess?

- `magick -background '#800' -size 360x120 -font Matrix-Bold -interline-spacing 70 caption:"reproducer extra spacing fail but no matter how much text you add it should wrap somewhere" 3long.jpg`
![3long](https://user-images.githubusercontent.com/64224741/80619516-15b85580-8a45-11ea-8e17-886fa8214cd5.jpg)

The space that would be available when inserting line breaks isn't used at all. What looks also suspicious is the amount of unused space on the right, but that might be a side issue.

**Comment by olsln** [comment]
Well I looked a little further and there is a strange effect with increasing interline spacing:

`i=10; while [ $i -lt 30 ]; do i=$((i+1)); magick -background '#800' -size 360x120 -font Matrix-Bold -interline-spacing $i caption:"reproducer extra spacing fail but no matter how much text you add it should wrap somewhere" 3long-spc$i.jpg; done`

11. ![3long-spc11](https://user-images.githubusercontent.com/64224741/80620962-f3273c00-8a46-11ea-9f88-5bd9dfd8bf75.jpg)
...
15. ![3long-spc15](https://user-images.githubusercontent.com/64224741/80620972-f4f0ff80-8a46-11ea-850c-326b8f24203e.jpg)
...
30. ![3long-spc30](https://user-images.githubusercontent.com/64224741/80621001-fa4e4a00-8a46-11ea-966c-97aaf3da4b67.jpg)

So 11 looks fine, but there is confusingly much space in e.g. 15 or 30. Isn't font size reduced too much for those?

**Comment by dlemstra** [comment]
I am getting a different result with the latest version of ImageMagick. Can we close this issue @olsln?
