### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ImageMagick/ImageMagick#194]
I would like to point out that identifiers like "[`_KernelProfileRecord`](https://github.com/ImageMagick/ImageMagick/blob/9dbe06aff8188c56679d5f04eff703b51bcb6446/MagickCore/opencl.h#L32)" and "[`_MAGICKCORE_IMAGE_H`](https://github.com/ImageMagick/ImageMagick/blob/fe3754c618d9689abc2ce9366c6eab53f417c049/MagickCore/image.h#L18)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by mikayla-grace** [comment]
Thanks for the suggestion, we changed out macro names so they are no longer reserved identifiers.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/ImageMagick/ImageMagick/commit/83bceaa5d7a1196e05c1ccba443f90f4b032fca6 "Deletion of some underscores").
There are [some update candidates left over around data structures](https://github.com/ImageMagick/ImageMagick/blob/83bceaa5d7a1196e05c1ccba443f90f4b032fca6/MagickCore/geometry.h#L91 "More update candidates"), aren't there?
