### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [ImageMagick/ImageMagick#195]
The function "[exit](http://pubs.opengroup.org/onlinepubs/9699919799/functions/exit.html "Terminate a process.")" does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function "[MagickSignalHandler](https://github.com/ImageMagick/ImageMagick/blob/f539c63cdc3a92d92880ccc3fefe140fc095f345/MagickCore/magick.c#L1314 "Reconsider signal handling implementation.")".

**Comment by dlemstra** [comment]
Thanks for reporting this.

**Comment by elfring** [comment]
How do you think about to use [the data type "sig_atomic_t"](http://en.cppreference.com/w/c/program/sig_atomic_t "Documentation for sig_atomic_t") for [the variable "magickcore_signal_in_progress"](https://github.com/ImageMagick/ImageMagick/blob/157f00a2e65ec7633ec818e4dd6cf7030b9932f9/MagickCore/magick.c#L126 "Update candidate")?
