### ISSUE TITLE
Feature request: identify -verbose output as yaml (currently almost yaml)

### ISSUE THREAD

**Issue by ghuzar** [ImageMagick/ImageMagick#1950]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

The current version of `identify -verbose` produces almost valid `yaml` format output.

It would be **nice to add a `-yaml`** flag that would **generate a yaml valid output** (or even make this a default option)

The changes required (at least for `jpg`,`png`,`gif`,`tif`,`bmp` that I have checked) would just be:

**1: (first line)** 

 `Image: file.jpg` 

to become

```
Image:
    Filename: file.jpg
```

**2: histogram and colormap (change indentation)** 

    49602: ( 49, 51, 39)  #313327 srgb(49,51,39)
        492: ( 98, 121, 135 )  #627987 srgb( 98,121,135)

to become:

    49602: ( 49, 51, 39 )  #313327 srgb(49,51,39)
    492:     ( 98, 121, 135 )  #627987 srgb( 98,121,135)

Then output would be **valid yaml** and **much easier to filter**. See below:
(I manually remove everything after `Image:`. Also the original output does not include color and histogram maps in this case.)

**prerequisites for testing:**

```bash
# getting an image
wget https://www.photos-public-domain.com/wp-content/uploads/2016/08/tortie-cat.jpg

# making sure that correct version of `yq` is instaled:
sudo pip install yq
# or
pip install --user yq

# also install its dependency
sudo apt install jq
```

**Command:**
```bash
# filter identify output using yq yaml parser
identify -verbose tortie-cat.jpg | sed 's/^Image:.*/Image:/' | yq -Y '.Image|{"Format","Geometry","Colorspace","Depth","Channel depth","Filesize","Number pixels"}'

```
**output (yml)**

```yml
Format: JPEG (Joint Photographic Experts Group JFIF format)
Geometry: 1629x1629+0+0
Colorspace: sRGB
Depth: 8-bit
Channel depth:
  red: 8-bit
  green: 8-bit
  blue: 8-bit
Filesize: 671KB
Number pixels: 2.654M

```

**Command:**

```bash
# filter identify output using yq yaml parser
identify -verbose tortie-cat.jpg | sed 's/^Image:.*/Image:/' | yq '.Image|{"Format","Geometry","Colorspace","Depth","Channel depth","Filesize","Number pixels"}'

```

output (json):

```json
{
  "Format": "JPEG (Joint Photographic Experts Group JFIF format)",
  "Geometry": "1629x1629+0+0",
  "Colorspace": "sRGB",
  "Depth": "8-bit",
  "Channel depth": {
    "red": "8-bit",
    "green": "8-bit",
    "blue": "8-bit"
  },
  "Filesize": "671KB",
  "Number pixels": "2.654M"
}

```

### System Configuration

- ImageMagick version: `ImageMagick 6.9.7-4 Q16 x86_64 20170114`
- Environment (Operating system, version and so on): `Ubuntu 18.04.4 LTS`
- Additional information:

**Comment by urban-warrior** [comment]
Good idea.  We'll add this feature in the next week or two.

**Comment by urban-warrior** [comment]
Try

```
magick tortie-cat.jpg tortie-cat.yaml
```
