### ISSUE TITLE
Missing JP2 support on RPM package ImageMagick 6.9.10.68

### ISSUE THREAD

**Issue by kamilpavlicko** [ImageMagick/ImageMagick#1954]
Hi 

for some reason (probably security issues) all RPM package older than ImageMagick-6.9.10.68 were removed from EPEL Centos7 repository.
Within our project (Ruby on Rails -> rmagick interation) we need to support jp2 format.
After `yum install ImageMagick` and `identify -list format` I cannot see JP2 codec support.
I assume, RPM package is built without --with-jp2.

### Prerequisites CENTOS7

- Docker container with fresh CentOS7

### Description
 Missing JP2 support

### Steps to Reproduce
- run Docker with centOS7
- `yum install openjpeg2`
- `yum install openjpeg2-devel`
- `yum install ImageMagick`
- `identify -list format` 

No jp2 listed

### CENTOS8
Following these steps on centOS8 -> JP2 support included
Everything is working well on CentOS8

Is there any way to fix it on CentOS7?

Thanks

**Comment by urban-warrior** [comment]
```
yum install ImageMagick-devel
wget https://imagemagick.org/download/ImageMagick-6.9.11-10.tar.gz
tar xvf ImageMagick-6.9.11-10.tar.gz
cd ImageMagick-6.9.11-10
./configure
sudo make install
/usr/local/bin/convert -list format
```
Verify JP2 support is built-in.

**Comment by kamilpavlicko** [comment]
No, JP2 is not build-in and supported after fresh instalation

I also tried reconfigure with --with-jp2 and then make install
Still no JP2 support


`[root@1f57de3ec337 ImageMagick-6.9.11-10]# /usr/local/bin/convert -list format | grep JP
           see part 5 which describes the image encoding (RLE, JPEG, JPEG-LS),
           and supplement 61 which adds JPEG-2000 encoding.
      JNG* rw-   JPEG Network Graphics
      JPE* rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 1.2.90)
     JPEG* rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 1.2.90)
      JPG* rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 1.2.90)
      JPS* rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 1.2.90)
      PGX* rw-   JPEG 2000 uncompressed format
    PJPEG* rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 1.2.90)`

**Comment by kamilpavlicko** [comment]
Could you please give some workaround, or will be this fixed in next RPM package ? 

Thanks
