### ISSUE TITLE
Performance issue with Group 4 compression TIFF

### ISSUE THREAD

**Issue by Larssson** [ImageMagick/ImageMagick#1955]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I posted earlier on the old forum about this issue and a patch was made, see https://imagemagick.org/discourse-server/viewtopic.php?f=1&t=37778
However, after testing this patch the performance seems to be even worse when converting a TIFF with Group 4 compression to PDF.

These are the timings for each version I tested.
6.9.2-10 -- 19 s
7.0.9-6 -- 58 s
7.0.10-7 -- 103 s

Changing the output format runs way faster, no matter which version.
TIFF->BMP -- 8 s
TIFF->PNG -- 15 s
So it seems this issue affects only TIFF->PDF conversion.

### Steps to Reproduce

Run magick convert with the image linked in the original post, output to pdf.
The timings mentioned here are from 10 conversions.

### System Configuration

- ImageMagick version: ImageMagick 7.0.10-7 Q8 x86_64 2020-04-24
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
This could be a Ghostscript issue? Which version of Ghostscript are you using? And which operating system are you using.

**Comment by Larssson** [comment]
Ghostscript 9.18-5, running on Red Hat Enterprise Linux 7.7

**Comment by fmw42** [comment]
That version is ancient. I recommend that you upgrade and try your processing again. Ghostscript is at 9.52

**Comment by Larssson** [comment]
Upgraded to Ghostscript 9.52 but behaviour is the same.

**Comment by Larssson** [comment]
@dlemstra @fmw42 
Is Ghostscript even involved in writing pdf? I had a quick look in coders/pdf.c and there seems GS is used only while reading pdf. Can you please confirm.

**Comment by fmw42** [comment]
My understanding is that it is only involved with reading PDF files.

**Comment by dlemstra** [comment]
Sorry I missed that. Did not realize you are having this issue when writing a PDF file. Attaching the test file here for future testing: 
[12pages.zip](https://github.com/ImageMagick/ImageMagick/files/4611877/12pages.zip)

**Comment by Larssson** [comment]
@dlemstra
I thought Cristy removed the color reduction step in the fix below. When can we expect this issue to be fixed?

https://github.com/ImageMagick/ImageMagick/commit/5e0c2589dbb6db78addf08d08b06d7d172365435
https://github.com/ImageMagick/ImageMagick/commit/a3c68bd4e7e71899ada1ce6eb5b544f0d41819ba
https://github.com/ImageMagick/ImageMagick/commit/d7d048929db2654db40176b75ad40cdaf4a9df7a

**Comment by dlemstra** [comment]
Not sure what you are asking? And did you get any information from the logging?

**Comment by Larssson** [comment]
@dlemstra
There is a tremendous amount of lines in the log and I don't know what to look for. We started experiencing this performance issue after upgrading IM and I'm asking if  this is expected behavior or something that will be fixed? If you need more info on the issue I need to know what to look for.

**Comment by urban-warrior** [comment]
The performance problem is due to generating thumbnails.  We'll add a define to skip over the thumbnail generation and that will likely resolve the problem.  We will post here when a patch is issued.

**Comment by Larssson** [comment]
@urban-warrior 
Thanks for the quick fix. I compiled and tried running `magick convert -define pdf:thumbnail=false 12pages.tiff test.pdf` but I don't see any difference. Anything wrong with my command or can I see somehow in debug output that the define is correctly interpreted?

**Comment by Larssson** [comment]
@urban-warrior 
It seems pdf:thumbnail=false is now the default behaviour, when I run without define it doesn't generate any thumbnail, but the thumbnail generation seems to take just a fraction of the time. How did you get it to run in 1/3 of the time?

```
./magick convert -verbose -define pdf:thumbnail=true -print "__Options__\n%[option:*]" 12pages.tiff test.pdf
12pages.tiff[0] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 227.73KiB 0.130u 0:00.129
12pages.tiff[1] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 0.120u 0:00.111
12pages.tiff[2] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 0.100u 0:00.096
12pages.tiff[3] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 0.090u 0:00.086
12pages.tiff[4] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 0.080u 0:00.076
12pages.tiff[5] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 0.070u 0:00.067
12pages.tiff[6] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 0.060u 0:00.057
12pages.tiff[7] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 0.050u 0:00.048
12pages.tiff[8] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 0.040u 0:00.038
12pages.tiff[9] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 0.030u 0:00.028
12pages.tiff[10] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 0.020u 0:00.019
12pages.tiff[11] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 0.020u 0:00.009
__Options__
pdf:thumbnail=true
12pages.tiff=> GROUP4 1648x2336 1648x2336+0+0 1-bit Gray 18703B 0.690u 0:00.698
12pages.tiff=> GROUP4 1648x2336=>75x106 1-bit Gray 2c 237B 0.280u 0:00.279
12pages.tiff=>[1] GROUP4 1648x2336 1648x2336+0+0 1-bit Gray 19890B 0.760u 0:00.754
12pages.tiff=>[1] GROUP4 1648x2336=>75x106 1-bit Gray 2c 248B 0.290u 0:00.287
12pages.tiff=>[2] GROUP4 1648x2336 1648x2336+0+0 1-bit Gray 19193B 0.700u 0:00.704
12pages.tiff=>[2] GROUP4 1648x2336=>75x106 1-bit Gray 2c 257B 0.270u 0:00.278
12pages.tiff=>[3] GROUP4 1648x2336 1648x2336+0+0 1-bit Gray 19038B 0.710u 0:00.703
12pages.tiff=>[3] GROUP4 1648x2336=>75x106 1-bit Gray 2c 287B 0.270u 0:00.276
12pages.tiff=>[4] GROUP4 1648x2336 1648x2336+0+0 1-bit Gray 18703B 0.710u 0:00.707
12pages.tiff=>[4] GROUP4 1648x2336=>75x106 1-bit Gray 2c 237B 0.280u 0:00.278
12pages.tiff=>[5] GROUP4 1648x2336 1648x2336+0+0 1-bit Gray 19890B 0.740u 0:00.729
12pages.tiff=>[5] GROUP4 1648x2336=>75x106 1-bit Gray 2c 248B 0.270u 0:00.277
12pages.tiff=>[6] GROUP4 1648x2336 1648x2336+0+0 1-bit Gray 19193B 0.730u 0:00.725
12pages.tiff=>[6] GROUP4 1648x2336=>75x106 1-bit Gray 2c 257B 0.280u 0:00.278
12pages.tiff=>[7] GROUP4 1648x2336 1648x2336+0+0 1-bit Gray 19038B 0.700u 0:00.701
12pages.tiff=>[7] GROUP4 1648x2336=>75x106 1-bit Gray 2c 287B 0.280u 0:00.282
12pages.tiff=>[8] GROUP4 1648x2336 1648x2336+0+0 1-bit Gray 18703B 0.700u 0:00.706
12pages.tiff=>[8] GROUP4 1648x2336=>75x106 1-bit Gray 2c 237B 0.280u 0:00.278
12pages.tiff=>[9] GROUP4 1648x2336 1648x2336+0+0 1-bit Gray 19890B 0.700u 0:00.707
12pages.tiff=>[9] GROUP4 1648x2336=>75x106 1-bit Gray 2c 248B 0.290u 0:00.278
12pages.tiff=>[10] GROUP4 1648x2336 1648x2336+0+0 1-bit Gray 19193B 0.690u 0:00.699
12pages.tiff=>[10] GROUP4 1648x2336=>75x106 1-bit Gray 2c 257B 0.280u 0:00.280
12pages.tiff=>[11] GROUP4 1648x2336 1648x2336+0+0 1-bit Gray 19038B 0.750u 0:00.759
12pages.tiff=>[11] GROUP4 1648x2336=>75x106 1-bit Gray 2c 287B 0.280u 0:00.285
12pages.tiff=>/adihome/66122891/test.pdf[0] TIFF 1648x2336 1648x2336+0+0 1-bit Bilevel Gray 227.73KiB 12.100u 0:12.144
```

**Comment by Larssson** [comment]
@urban-warrior @dlemstra 
I didn't see much difference when switching off thumbnail generation, it now runs in 3/4 of the time (see log above). @urban-warrior wrote it now runs in 1/3 of the time and this sounds reasonable as it's about the same time as IM 6.9.2. Any ideas why I don't see the same performance increase?

**Comment by Larssson** [comment]
@urban-warrior @dlemstra 
Thumbnail generation doesn't make much difference, when I run with pdf:thumbnail=false and verbose I get GROUP4 1648x2336=>1x1 instead of GROUP4 1648x2336=>75x106 but run time is still slow.

I traced the issue and discovered that it appeared after this commit
https://github.com/ImageMagick/ImageMagick/commit/83c306dd3a2ed767effb16e725f4a0e338d978a6

Earlier there was a check in SetImageType if the image is monochrome.

This issue was properly address in the first fix (see commits below) but there is still one call to SetImageType in tiff.c:3493 which does not have the monochrome check.
https://github.com/ImageMagick/ImageMagick/commit/5e0c2589dbb6db78addf08d08b06d7d172365435
https://github.com/ImageMagick/ImageMagick/commit/a3c68bd4e7e71899ada1ce6eb5b544f0d41819ba

Adding the monochrome condition to this call will fix the issue. Can you add this fix in the official repo?
  ```
  /*
      Initialize TIFF fields.
    */
    if ((image_info->type != UndefinedType) &&
        (image_info->type != OptimizeType) &&
		IsImageMonochrome(image) == MagickFalse)
      (void) SetImageType(image,image_info->type,exception);
```

**Comment by dlemstra** [comment]
That fix does looks wrong because we don't set the image to monochrone there. We will need to investigate this.

**Comment by urban-warrior** [comment]
Its just checking if the image is monochrome before it sets the image type.  We applied the patch.  Will do some testing to ensure its a robust patch before we release it.

**Comment by Larssson** [comment]
@urban-warrior I see the fix was reverted last night. Any issues to keep it?

**Comment by urban-warrior** [comment]
@dlemstra pointed out a flaw with your patch. Consider the -type truecolor command-line option.  The option would not return expected results with your patch.  However, if we just check if an image is monochrome, that seems to solve the performance issue.  We'll add a temporary patch while we investigate further.

**Comment by Larssson** [comment]
@urban-warrior @dlemstra
Any plans to make a permanent fix? The temporary patch doesn't work, SetImageType must be skipped. Of course, I can modify this myself but would prefer to have it fixed out of the box for each new version.

**Comment by dlemstra** [comment]
It looks like the patch 1722c9863b9491acb8e8be87740ebef737aa134d resolves your issue @Larssson. This will become available in the next release of ImageMagick.
