### ISSUE TITLE
LAB documentation inconsistent or wrong

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#1967]
At https://imagemagick.org/script/color.php, the documentation for specifying LAB colors seems inconsistent and also inconsistent with current behavior.  IM 7.0.10.9 Q16 HDRI Mac OSX Sierra. 

In that document it says:

> Specify the Lab colors like this:
> 
> cielab(62.253188, 23.950124, 48.410653)
> 
> Note, the a and b components of any Lab color you specify are biased internally by 50% to ensure it fits in the quantum range (typically 0 to 65535). The bias is retained when writing to the TIFF and MIFF image formats. However, the TXT format supports negative pixel values so the bias is removed when writing to this format:
> 
> magick xc:cyan -colorspace LAB txt:
> \#ImageMagick pixel enumeration: 1,1,65535,cielab
> 0,0: (91.1131%,-18.8571%,-5.5436%)  #E93F00000000  cielab(91.1131%,-18.8571%,-5.5436%)
> 
> magick -size 100x100 xc:"cielab(91.1131%,-18.8571%,-5.5436%)" -colorspace sRGB cyan.png
> 

At the top, the cielab values do not show % symbols. But the bottom command seems to report and use values in %.  

**What is the range of values that can be specified, when not using % for each of cie L,A,B?**

**Comment by urban-warrior** [comment]
We corrected the documentation.  The cielab() specification can be found in section 12.3.4. LAB color in the SVG 2 docs @ https://www.w3.org/TR/2013/WD-SVG2-20130409/color.html.  If you find ImageMagick not conforming to this specification, that would be a bug.  Let us know and we will add a patch.
