### ISSUE TITLE
Possible Bug: Documentation for LAB colors

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#1968]
At https://imagemagick.org/script/color.php, the documentation for specifying LAB colors seems i inconsistent with current behavior.  In that document it says:

> Specify the Lab colors like this:
> 
> cielab(62.253188, 23.950124, 48.410653)
> 
> Note, the a and b components of any Lab color you specify are biased internally by 50% to ensure it fits in the quantum range (typically 0 to 65535). The bias is retained when writing to the TIFF and MIFF image formats. However, the TXT format supports negative pixel values so the bias is removed when writing to this format:
> 
> magick xc:cyan -colorspace LAB txt:
> \#ImageMagick pixel enumeration: 1,1,65535,cielab
> 0,0: (91.1131%,-18.8571%,-5.5436%)  #E93F00000000  cielab(91.1131%,-18.8571%,-5.5436%)
> 
> magick -size 100x100 xc:"cielab(91.1131%,-18.8571%,-5.5436%)" -colorspace sRGB cyan.png
> 

When I repeat the cyan conversion, I get different values from those listed here. IM 7.0.10.9 Q16 HDRI Mac OSX Sierra.

```
magick xc:cyan -colorspace LAB txt:
# ImageMagick pixel enumeration: 1,1,65535,cielab
0,0: (59711,20409.5,-3632.9)  #E93F4FBA71CF  cielab(91.1132,-48.0855,-14.1358)
```

My values are not in %, but seem correct:

`magick -size 100x100 xc:"cielab(91.1132,-48.0855,-14.1358)" cyan_from_LAB.png`

![cyan_from_LAB](https://user-images.githubusercontent.com/13458218/80754640-3aafd580-8ae4-11ea-9154-60995562c8cf.png)

The values from the documentation are in % and also produce a valid cyan color:

`magick -size 100x100 xc:"cielab(91.1131%,-18.8571%,-5.5436%)" cyan_from_docs.png`

![cyan_from_docs](https://user-images.githubusercontent.com/13458218/80755016-e78a5280-8ae4-11ea-8a35-a83542b506d2.png)

**What are the range of values that may be used to specify each of cie L,A,B values when not using %** (as per magick xc:"cielab(91.1132,-48.0855,-14.1358) ... ")

You may merge this post with my previous one, since the question is really the same.

**Comment by urban-warrior** [comment]
We corrected the documentation.  The cielab() specification can be found in section 12.3.4. LAB color in the SVG 2 docs @ https://www.w3.org/TR/2013/WD-SVG2-20130409/color.html.  If you find ImageMagick not conforming to this specification, that would be a bug.  Let us know and we will add a patch.

**Comment by fmw42** [comment]
That section of the SVG documentation does not indicate what the min and max values are.
