### ISSUE TITLE
Converting with -auto-orient -flatten cut off image

### ISSUE THREAD

**Issue by xuanvinh2005** [ImageMagick/ImageMagick#197]
I tried to convert this file with follow command line (7.0.1-2)
convert.exe  -auto-orient -flatten E:\in.jpg E:\out.png,
out.png is cut off a part of original. When I removed "-flatten" it seems to be fine
Output file
![out](https://cloud.githubusercontent.com/assets/17859346/15152926/0312d8c8-168c-11e6-9c66-9bad9d112625.png)
Original file
![1](https://cloud.githubusercontent.com/assets/17859346/15152931/09e8529a-168c-11e6-995d-3ab5bc7a1bc6.JPG)

**Comment by dlemstra** [comment]
Why are you adding the -flatten, you don't need it. And you probably want to put your commands in the correct order:

    convert.exe E:\in.jpg -auto-orient E:\out.png,

**Comment by dlemstra** [comment]
Is this issue resolved @xuanvinh2005 ?
