### ISSUE TITLE
Magick::Color::scaleDoubleToQuantum(), public or protected?

### ISSUE THREAD

**Issue by Ximalas** [ImageMagick/ImageMagick#1970]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The documentation for `Magick::Color::scaleDoubleToQuantum()` and `Magick::Color::scaleQuantumToDouble()`, https://imagemagick.org/api/Magick++/classMagick_1_1Color.html, claim these `static` functions are declared `public`, yet in the `Magick++/Color.h` header file they are declared `protected`.
In the older version, ImageMagick 6.9.11.6, these functions are indeed declared `public`.

I came across this issue while trying to persuade Inkscape to compile and link with ImageMagick 7.0.10 on FreeBSD. One of the other consumers of ImageMagick on my laptop, GNU Emacs, recently switched to 7.0.10, forcing me to try to get the two remaining consumers, Icingaweb 2 and Inkscape, to use 7.0.10. Note, I'm _not_ a FreeBSD ports committer.

If `Magick::Color::scaleDoubleToQuantum()` and `Magick::Color::scaleQuantumToDouble()` are not ment to be used outside of ImageMagick, then the documentation should state so, and, if possible, offer alternatives for software that relies on the previous behaviour.

### Steps to Reproduce
Try to compile a simple function accessing `Magick::Color::scaleDoubleToQuantum()` and/or `Magick::Color::scaleQuantumToDouble()`.

### System Configuration
- ImageMagick version: 7.0.10-6
- Environment (Operating system, version and so on): FreeBSD/amd64 base/head r360207
- Additional information:

**Comment by dlemstra** [comment]
Moving from version 6 to version 7 allowed us to make these kind of breaking changes. We won't offer an alternative for those methods. And for some reason it looks like those docs are using an outdated version of the header.

**Comment by Ximalas** [comment]
Understood. It will benefit all if the online documentation is accurate.
