### ISSUE TITLE
ImageMagick.MagickTypeErrorException: "UnableToReadFont `helvetica' @ error/annotate.c/RenderFreetype/1392"

### ISSUE THREAD

**Issue by FloridaMatt** [ImageMagick/ImageMagick#1972]
ImageMagick version Magick.NET-Q8-x64 7.16.1
Visual Studio for Mac 8.5.4 build 12
MacOS Catalina 10.15.4
C# application relevant code:
            string ts = item.creationdate.ToString("MM/dd/yy");
            img.Settings.FontFamily = "Tahoma";
            img.Settings.FontPointsize = img.Height / 25;
            img.Settings.FillColor = MagickColors.GhostWhite;
            img.Settings.StrokeColor = MagickColors.Black;
            img.Settings.FontStyle = FontStyleType.Bold;
                img.Annotate(ts, Gravity.Northwest);

code works correctly on Windows.

I've found a variety of fixes for this when using the command line interface, but none for when using the C# interface.

**Comment by dlemstra** [comment]
It looks like Magick.NET cannot find your fonts. Did you install fontconfig on your MacOS machine? This is used in the MacOS build of Magick.NET. You can get a list of installed fonts with `MagickNET.FontFamilies`.

**Comment by FloridaMatt** [comment]
Ok, so after thinking about this for a bit I decided to install the imagemagick application, in case the nuget package had any undocumented dependencies on it.  For reference, I used brew install imagemagic.

This has resolved the original issue.  

However, it seems that fontconfig is extremely unhappy with the mac's  /usr/local/etc/fonts/fonts.conf file's contents, as running my program produces the following spate of error messages:

Fontconfig warning: "/usr/local/etc/fonts/fonts.conf", line 5: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/fonts.conf", line 7: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/fonts.conf", line 9: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/10-hinting-slight.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/20-unhint-small-vera.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/20-unhint-small-vera.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/20-unhint-small-vera.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/20-unhint-small-vera.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/20-unhint-small-vera.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/30-metric-aliases.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/30-metric-aliases.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/30-metric-aliases.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/30-metric-aliases.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/30-metric-aliases.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/30-metric-aliases.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/30-metric-aliases.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/40-nonlatin.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/40-nonlatin.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/40-nonlatin.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/40-nonlatin.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/40-nonlatin.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/40-nonlatin.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/40-nonlatin.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/45-generic.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/45-generic.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/45-generic.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/45-generic.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/45-generic.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/45-generic.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/45-generic.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/45-latin.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/45-latin.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/45-latin.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/45-latin.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/45-latin.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/45-latin.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/45-latin.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/49-sansserif.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/49-sansserif.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/49-sansserif.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/49-sansserif.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/49-sansserif.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/49-sansserif.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/49-sansserif.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/50-user.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/50-user.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/50-user.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/50-user.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/50-user.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/50-user.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/50-user.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/51-local.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/51-local.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/51-local.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/51-local.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/51-local.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/51-local.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/51-local.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/60-generic.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/60-generic.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/60-generic.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/60-generic.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/60-generic.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/60-generic.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/60-generic.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/60-latin.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/60-latin.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/60-latin.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/60-latin.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/60-latin.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/60-latin.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/60-latin.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/65-fonts-persian.conf", line 34: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/65-fonts-persian.conf", line 35: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/65-fonts-persian.conf", line 35: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/65-fonts-persian.conf", line 35: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/65-fonts-persian.conf", line 36: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/65-fonts-persian.conf", line 36: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/65-nonlatin.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/65-nonlatin.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/65-nonlatin.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/65-nonlatin.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/65-nonlatin.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/65-nonlatin.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/65-nonlatin.conf", line 8: unknown element "description"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/69-unifont.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/69-unifont.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/69-unifont.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/69-unifont.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/69-unifont.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/69-unifont.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/80-delicious.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/80-delicious.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/80-delicious.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/80-delicious.conf", line 6: invalid attribute 'version'\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"\
Fontconfig warning: "/usr/local/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"\
Fontconfig error: "/usr/local/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'translate'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'\
Fontconfig error: "/usr/local/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'\
Fontconfig error: Cannot load config file from /usr/local/etc/fonts/fonts.conf\
Fontconfig warning: FcPattern object weight does not accept value [0.5 215)}
[fontsconf.zip](https://github.com/ImageMagick/ImageMagick/files/4570587/fontsconf.zip)
