### ISSUE TITLE
Composite with "+matte" fails whereas "-alpha off" works

### ISSUE THREAD

**Issue by alexander-nitsche** [ImageMagick/ImageMagick#1974]
### Description
When overlapping multiple images with legacy ImageMagick 6 the command line option _+matte_ has been supported even though the documents suggested to replace it with _-alpha off_ (see https://imagemagick.org/script/command-line-options.php#alpha for details).

Now when using ImageMagick 7 _+matte_ seems not to be supported anymore even though the documentation tells different - see https://imagemagick.org/script/porting.php :

```
Deprecated warning given, but will work (for now)

..
-/+matte    Replaced by -alpha Set/Off.
..
```

Is the documentation wrong or the implementation?

### Steps to Reproduce

1. Run this command of the TYPO3 image creation tests with option _+matte_ and ImageMagick 7 which will produce wrong results (see https://forge.typo3.org/issues/91274#note-1 for screenshots):
```
'/usr/bin/composite' -interlace None +profile '*' -compose over -quality 85 +matte 'jpg:/var/www/html/public/typo3/sysext/install/Resources/Public/Images/TestInput/Test.jpg' 'gif:/var/www/html/public/typo3/sysext/install/Resources/Public/Images/TestInput/BackgroundOrange.gif' 'gif:/var/www/html/var/transient/fc32b95e2834c191a1ddc6df21f0f972.gif' '/var/www/html/public/typo3temp/assets/images/installTool-typo3InstallTestcombine15eaefee18e677066106529.jpg'
```

2. Run the modified command with the option _+matte_ replaced by _-alpha off_ and verify that the result is a expected.

### System Configuration

- ImageMagick version:
  - ImageMagick 7.0.9-7 Q16 x86_64 2019-12-03
- Environment:
  - Alpine Linux 3.11.6

**Comment by fmw42** [comment]
You probably should be using the convert syntax for doing composites and using magick in place of convert for IM 7.  Also if you continue to try to use composite, it should be magick composite in IM 7. That is all but convert, need to be prefaced with magick. Convert is simply replaced by magick.  At this late date, I do not know if +matte is still deprecated as that was at the beginning. The docs say "for now". So it could be that you now need to use the proper IM syntax and use -alpha off. I recommend now transitioning to the proper IM syntax.

**Comment by alexander-nitsche** [comment]
Sorry, i missed to add that Alpine Linux 3.11 is creating symbolic links to the magick command like:
```
/var/www/html $ ls -la /usr/bin/composite 
lrwxrwxrwx    1 root     root             6 May  2 12:06 /usr/bin/composite -> magick
```
This is the default when installing ImageMagick via the Alpine Linux package management.

**Comment by alexander-nitsche** [comment]
Ok, the deprecation warning for +matte seems to be in place since ImageMagick 6.7.6-0 which was committed on Mar 11, 2012 in this commit: https://github.com/ImageMagick/ImageMagick6/commit/ce3516c49b3aa8a8fa2dd4ed2b1ff689b4463ca9 . Thus _-alpha off_ should be available on most ImageMagick instances out there.

**Comment by fmw42** [comment]
-alpha off should work for all versions of IM 7
