### ISSUE TITLE
7.0.10.9: perl Graphics-TIFF module test suite is failing

### ISSUE THREAD

**Issue by kloczek** [ImageMagick/ImageMagick#1978]
Looks like test suite of the Graphics-TIFF module is failing with 7.0.10.
All details are on https://rt.cpan.org/Public/Bug/Display.html?id=122933

**Comment by urban-warrior** [comment]
We did not write nor do we maintain the Graphics-TIFF module.  However its likely the module has not been validated against ImageMagick version 7.  Try the latest release of version 6 instead, 6.9.11-10.

**Comment by dlemstra** [comment]
We did not write nor do we maintain the Graphics-TIFF module.  You will need to contact them instead.
