### ISSUE TITLE
Strange results drawing rectangles when using +antialias

### ISSUE THREAD

**Issue by DaLynxx** [ImageMagick/ImageMagick#1994]
### Prerequisites

- [X] I have written a descriptive issue title
- [X ] I have verified that I am using the latest version of ImageMagick
- [ X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When drawing rectangles with +antialias (i.e. antialias turned off) and for example strokewidth 7 I get strange result. The right vertical line changes width and the left and bottom ones are 8 px wide.

### Steps to Reproduce

create 2 files
`magick -size 500x300 xc:white -stroke #ff0000 -strokewidth 7 -fill #ffffff -antialias -draw "rectangle 3,3, 496,296" antialias_on.png`

and
`magick -size 500x300 xc:white -stroke #ff0000 -strokewidth 7 -fill #ffffff +antialias -draw "rectangle 3,3, 496,296" antialias_off.png`

Compare the two files. The second one where antialias is turned off (+antialias) is the one where I get the strange result.
Antialias on: Looks ok.
![antialias_on](https://user-images.githubusercontent.com/1823630/81210008-8a553c00-8fd1-11ea-81e1-acfd82ffc417.png)

Antialias off: strange.
![antialias_off](https://user-images.githubusercontent.com/1823630/81210005-89bca580-8fd1-11ea-8caa-ded5335ae9e2.png)

### System Configuration
- ImageMagick version: ImageMagick 7.0.10-10 Q16 x64 2020-04-28
- Environment (Operating system, version and so on): Windows 10
- Additional information:

**Comment by dlemstra** [comment]
Could you update your message and include the output images? You can copy them into your message.

**Comment by DaLynxx** [comment]
aye!

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
