### ISSUE TITLE
Warning when using simple txt format file

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#1999]
I have a script that creates a simple txt format file. In the past, when I used that file, it worked fine. Now, I am getting a warning message

> convert: insufficient image data in file `stainedglass_C_2476.txt' @ warning/txt.c/ReadTXTImage/630.

This is the script code line that causes the issue, but I think it is simply ImageMagick no longer likes the fact that the txt format file does not have all the usual information filled out.

Input:

![birdofparadise](https://user-images.githubusercontent.com/13458218/81328971-a4832e80-9052-11ea-952a-0f1bc1dcc112.gif)

TXT file:

[stainedglass_C_2476.txt](https://github.com/ImageMagick/ImageMagick/files/4594891/stainedglass_C_2476.txt)

Command:

```
convert birdofparadise.gif \( -background black stainedglass_C_2476.txt \) \
-alpha off -compose copy_opacity -composite \
sparse-color:- |\
convert -size 500x381 xc: -sparse-color voronoi '@-' \
xx.png

```

Result is fine:

![xx](https://user-images.githubusercontent.com/13458218/81329104-e318e900-9052-11ea-9978-1906b00f8f72.png)

I think the issue might be coming from reading the stainedglass_C_2476.txt.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
