### ISSUE TITLE
convert from PDF to EMF when running in a non-Windows environment?

### ISSUE THREAD

**Issue by mewalig** [ImageMagick/ImageMagick#201]
Is this feasible? Can the "R" option / EMF support be ported to work in a non-Win build?

**Comment by dlemstra** [comment]
We don't support writing EMF images in Windows or any other platform. I don't understand why you are asking about the 'R' option because that is for reading. We do support reading EMF files on non-Windows environments but that requires libEMF.

**Comment by mewalig** [comment]
I see, I misunderstood the options and thought there was an option to convert pdf to emf. thanks
