### ISSUE TITLE
Documentation Bug atan2()

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#2012]
There is a bug in the documentation for atan2 on the -fx page at https://imagemagick.org/script/fx.php

It lists

`atan2(x,y)    arc tangent function of two variables`

But that has the x,y reversed. It should be

`atan2(y,x)    arc tangent function of two variables`

See https://en.wikipedia.org/wiki/Atan2

Here is a simple example to prove it.

\# get tan(30 deg)
`convert xc: -format "%[fx:tan((pi/180)*30)]" info:`
0.57735 = Y/X -> Y=0.57735 and X=1

\# correctly compute atan2(Y,X)
`convert xc: -format "%[fx:(180/pi)*atan2(0.57735,1)]" info:`
30

**Comment by urban-warrior** [comment]
Fixed
