### ISSUE TITLE
Problem converting certain TIF to JPG: convert: no images defined

### ISSUE THREAD

**Issue by vtamara** [ImageMagick/ImageMagick#2015]
### Prerequisites

- [X] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Trying to convert the attached tiff to jpg doesn't produce any jpg and generates the error:
```
convert: no images defined `p.jpg' @ error/convert.c/ConvertImageCommand/3226.
```
[p.zip](https://github.com/ImageMagick/ImageMagick/files/4624544/p.zip)

### Steps to Reproduce
Run `convert p.tif p.jpg`
 
### System Configuration

- ImageMagick version: 6.9.10-86
- Environment (Operating system, version and so on): OpenBSD/adJ 6.6
- Additional information: In the same environment works with a previous version of ImageMagick, i.e this file can be converted with 6.9.10-10

Thanks for the good job with ImageMagick

**Comment by fmw42** [comment]
I cannot get it to process either on IM 6.9.11.11. I get lots of warnings even when adding -quiet. I think there is something wrong with your file. Mac Preview will open it as will Photoshop.

I think one of the IM developers will need to examine your file.

**Comment by urban-warrior** [comment]
The image does not conform to the TIFF specification per

`p.tif: Null count for "Tag 34022" (type 1, writecount -3, passcount 1). `_TIFFVSetField' @ error/tiff.c/TIFFErrors/661`

ImageMagick can tolerate warnings generated by the TIFF delegate library, libtiff, but not errors.  The TIFF delegate library throws the error, so ImageMagick exits early to help avoid processing a nefarious image (a security precaution).

**Comment by vtamara** [comment]
Cannot be an option (e.g -insecure) to allow processing of invalid Tiff?

**Comment by dlemstra** [comment]
This is controlled by the libtiff project @vtamara. If you could ask them to add an option for this we could add an option in ImageMagick that controls their option to allow processing of tiff files with errors. It looks like the project now lives here: https://gitlab.com/libtiff/libtiff.

**Comment by spbnick** [comment]
This problem was reported to libtiff a while ago: https://gitlab.com/libtiff/libtiff/-/issues/110

I used the workaround of first running the images through `tiff2rgba` (which strips those unknown tags, apparently), and then running `convert` on them.

**Comment by mrAceT** [comment]
> I used the workaround of first running the images through `tiff2rgba`

Thank you for the tip.

After trying al sorts of ways to repair ImageMagick this was the only way I could get it working.. It ain't pretty.. but it works
