### ISSUE TITLE
Can't convert old TIFF because of an "improper image header"

### ISSUE THREAD

**Issue by Stef-33560** [ImageMagick/ImageMagick#2023]
### Prerequisites

- [X] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick 
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In a context of migration project from an OLD IT system based on Windows. I have extracted a huge number TIFF images. Those TIFF are correctly printed to screen by any software either on Linux or Windows and were even previously converted by a proprietary software to PDF.

Now I want to import them in my Brand New OpenSource Software basd on Linux that use ImageMagick to convert them on the fly. Using command line, it fails saying they have an ""improper image header" ; in fact it seems that only some of the tags are missing, but ImageMagick (as exifs) seems to considers them mandatory :
```
$ exif myOldFile.tif 
Données corrompues
Les données fournies ne respectent pas les spécifications.
ExifLoader: Les données fournies ne semblent pas contenir de données EXIF.
```
I've isolated the error thrown in [coders/tiff.c](https://github.com/ImageMagick/ImageMagick/blob/master/coders/tiff.c#L1423) line 1423
```
   if ((TIFFGetField(tiff,TIFFTAG_IMAGEWIDTH,&width) != 1) ||
        (TIFFGetField(tiff,TIFFTAG_IMAGELENGTH,&height) != 1) ||
        (TIFFGetFieldDefaulted(tiff,TIFFTAG_PHOTOMETRIC,&photometric,sans) != 1) ||
        (TIFFGetFieldDefaulted(tiff,TIFFTAG_COMPRESSION,&compress_tag,sans) != 1) ||
        (TIFFGetFieldDefaulted(tiff,TIFFTAG_FILLORDER,&endian,sans) != 1) ||
        (TIFFGetFieldDefaulted(tiff,TIFFTAG_PLANARCONFIG,&interlace,sans) != 1) ||
        (TIFFGetFieldDefaulted(tiff,TIFFTAG_SAMPLESPERPIXEL,&samples_per_pixel,sans) != 1) ||
        (TIFFGetFieldDefaulted(tiff,TIFFTAG_BITSPERSAMPLE,&bits_per_sample,sans) != 1) ||
        (TIFFGetFieldDefaulted(tiff,TIFFTAG_SAMPLEFORMAT,&sample_format,sans) != 1) ||
        (TIFFGetFieldDefaulted(tiff,TIFFTAG_MINSAMPLEVALUE,&min_sample_value,sans) != 1) ||
        (TIFFGetFieldDefaulted(tiff,TIFFTAG_MAXSAMPLEVALUE,&max_sample_value,sans) != 1))
      {
        TIFFClose(tiff);
        ThrowReaderException(CorruptImageError,"ImproperImageHeader");
      }
```
If I replace this code by the following snippet, then ImageMagick successfully convert my files :
```
    (void) TIFFGetFieldDefaulted(tiff,TIFFTAG_IMAGEWIDTH,&width);
    (void) TIFFGetFieldDefaulted(tiff,TIFFTAG_IMAGELENGTH,&height);
    (void) TIFFGetFieldDefaulted(tiff,TIFFTAG_PHOTOMETRIC,&photometric);
    (void) TIFFGetFieldDefaulted(tiff,TIFFTAG_COMPRESSION,&compress_tag);
    (void) TIFFGetFieldDefaulted(tiff,TIFFTAG_FILLORDER,&endian);
    (void) TIFFGetFieldDefaulted(tiff,TIFFTAG_PLANARCONFIG,&interlace);
    (void) TIFFGetFieldDefaulted(tiff,TIFFTAG_SAMPLEFORMAT,&sample_format);
    (void) TIFFGetFieldDefaulted(tiff,TIFFTAG_ORIENTATION,&orientation);
    (void) TIFFGetFieldDefaulted(tiff,TIFFTAG_BITSPERSAMPLE,&bits_per_sample);
    (void) TIFFGetFieldDefaulted(tiff,TIFFTAG_MINSAMPLEVALUE,&min_sample_value);
    (void) TIFFGetFieldDefaulted(tiff,TIFFTAG_MAXSAMPLEVALUE,&max_sample_value);

```

How can I check the TAGs in my TIFF files or which "specification" my files are referring to ?
Otherwise, how can I simply bulk modify the missing tags ?
Would it be possible to add an exception in ImageMagick to avoid to throw the exception ?

### Steps to Reproduce
```
convert myOldFile.tif somethingNew.jpg
convert-im6.q16: improper image header `myOldFile.tif' @ error/tiff.c/ReadTIFFImage/1274.
convert-im6.q16: no images defined `somethingNew.jpg' @ error/convert.c/ConvertImageCommand/3258.

```
The TIFF file are confidentials, I can't share them.

### System Configuration

- ImageMagick version:  6.9.10-23 (7 don't work on Ubuntu Focal, missing libMagickCore-7.Q16HDRI.so.7)
- Environment (Operating system, version and so on): 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Additional information:

**Comment by urban-warrior** [comment]
ImageMagick has evolved over time and tightened-up its requirements to make it more secure.  See https://imagemagick.org/script/security-policy.php for more details.  As such, we cannot loosen the restrictions on TIFF or any other image format.  The check for TIFF is for the required attributes that must be present in any modern day TIFF image to help ensure the image is not nefarious and an attempt to bypass security with ImageMagick.  As such, our only recommendation is to modify your local copy of ImageMagick as you suggested in your post, use an older less restrictive version of ImageMagick, or use some other program that is less pedantic and can and will read your legacy images.

**Comment by Stef-33560** [comment]
I understand your position, but since some of those tags are not mandatory to convert the file, why would'nt it possible to log a simple warning telling the file ton convert is deprecated (even if adding a default value is needed) ?

Otherwise since Tiff does not really evolve anymore, maintining this modification out of the main branch is also a nonsense. Is there a way to add the missing tags ?

**Comment by dlemstra** [comment]
Have you tracked down which one of those fields are causing the issue? I wonder if we could make an exception for `min_sample_value` and `max_sample_value`. Those fields are only used for debugging.

p.s. Can you also attach an example tiff file.

**Comment by Stef-33560** [comment]
> Can you also attach an example tiff file.
No, sorry, those files are highly confidential and can't be shared on Internet

> Have you tracked down which one of those fields are causing the issue?
```
$ tiffinfo myfile.tif 
TIFF Directory at offset 0xa414 (42004)
  Image Width: 6624 Image Length: 4680
  Resolution: 200, 200 pixels/inch
  Compression Scheme: CCITT Group 4
  Orientation: row 0 top, col 0 lhs
  Planar Configuration: single image plane
  Software: <<CONFIDENTIAL>>
  DateTime: 2011:09:22 08:13:50
```
Note : don't refer the date shown here, that's the date of the last import in the old software ! :)

If `tiffinfo` tells everything, the missing tags seem to be : 

- `[TIFFTAG_FILLORDER](https://www.awaresystems.be/imaging/tiff/tifftags/fillorder.html) : default value = 1
- [TIFFTAG_BITSPERSAMPLE](https://www.awaresystems.be/imaging/tiff/tifftags/bitspersample.html) : default value = 1
- [TIFFTAG_SAMPLEFORMAT](https://www.awaresystems.be/imaging/tiff/tifftags/sampleformat.html) : default value = 1
- [TIFFTAG_MINSAMPLEVALUE](https://www.awaresystems.be/imaging/tiff/tifftags/minsamplevalue.html) : default value = 0
- [TIFFTAG_MAXSAMPLEVALUE](https://www.awaresystems.be/imaging/tiff/tifftags/maxsamplevalue.html) : default value = 2**(BitsPerSample) - 1
- [TIFFTAG_PHOTOMETRIC](https://www.awaresystems.be/imaging/tiff/tifftags/photometricinterpretation.html)` ==> No default value :(

So only PHOTOMETRIC seems to be totally mandatory.

**BUT** when I load this file in GIMP, the only field mentionned is photometric ; error message : `Could not get photometric from 'myfile.tif'. Image is CCITT compressed, assuming min-is-white`

So I would gently suggest that ImageMagick should assume the same behaviour as GIMP :)
Would you agree a PR on this base ?

**Comment by dlemstra** [comment]
Feel free to reach out by email if you want to share the file privately. What are the return values for the calls to `TIFFGetFieldDefaulted`? Which one return `!= 1` and causes the check to fail?
