### ISSUE TITLE
Magick++ 6.9.4 can't work with jpg

### ISSUE THREAD

**Issue by jackyao** [ImageMagick/ImageMagick#203]
hi, i use 6.9.4 ImageMagick,I can 

>convert test.jpg test.png
convert: Corrupt JPEG data: 6 extraneous bytes before marker 0xdb `test.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.

but use Magick++, then it can't work

**Comment by jackyao** [comment]
![test](https://cloud.githubusercontent.com/assets/1876425/15463136/db53617c-20f9-11e6-94f6-c1662641b202.jpg)

**Comment by dlemstra** [comment]
How are you reading the file with Magick++ and are you getting an exception?

**Comment by dlemstra** [comment]
Can you respond to our question @jackyao ? Or did you resolve this and can we close the issue?
