### ISSUE TITLE
mogrify together with `-format jpg` and `-profile file.icc` expects .icc file to be JPG

### ISSUE THREAD

**Issue by pandabear** [ImageMagick/ImageMagick#2030]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
On Centos 7.7 with ImageMagick 7.0.10-13, when converting a gray colorspaced tif to sRGB jpg with following command:
```
mogrify -path target/ -type truecolor -colorspace sRGB -profile /usr/share/color/icc/OpenICC/sRGB.icc -format jpg src/*
```
Produces an error `mogrify: Not a JPEG file: starts with 0x00 0x00 '/usr/share/color/icc/OpenICC/sRGB.icc' @ error/jpeg.c/JPEGErrorHandler/342.` gets raised. However, same error doesn't get raised when using:
```
convert -type truecolor -colorspace sRGB -profile /usr/share/color/icc/OpenICC/sRGB.icc -format jpg src/0001.tif target/0001.jpg
```
and result is what was expected.

Older version (6.7.8-9) did not emit this error when mogrifying and produced the expected result.
sRGB.icc file is provided by https://centos.pkgs.org/7/centos-x86_64/icc-profiles-openicc-1.3.1-5.el7.noarch.rpm.html .

### Steps to Reproduce

1. Install https://centos.pkgs.org/7/centos-x86_64/icc-profiles-openicc-1.3.1-5.el7.noarch.rpm.html this package. `yum install icc-profiles-openicc` on centos machine.

2. Download and extract the single tif file from here to `src` folder: [0001.tif.tar.gz](https://github.com/ImageMagick/ImageMagick/files/4643485/0001.tif.tar.gz).

3. Create target directory `mkdir target`.

4. Mogrify: `mogrify -path target/ -type truecolor -colorspace sRGB -profile /usr/share/color/icc/OpenICC/sRGB.icc -format jpg src/*`

Expectation: Same result as if run by `convert -type truecolor -colorspace sRGB -profile /usr/share/color/icc/OpenICC/sRGB.icc -format jpg src/0001.tif target/0001.jpg`

### System Configuration

- ImageMagick version: ImageMagick 7.0.10-13 Q16 x86_64
- Environment (Operating system, version and so on): Centos 7.7
- Additional information: The issue was discovered on ImageMagick-6.9.10.68-4 when updated from 6.7.8-9.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
