### ISSUE TITLE
[BUG] convert multiple jpg's to pdf doesn't work properly

### ISSUE THREAD

**Issue by jbirnick** [ImageMagick/ImageMagick#2032]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

In one of the version of imagemagick released in the last days, there was the following bug introduced:
If you convert multiple .jpg files to a single pdf file, only the first image will be converted, then 2 black pages, then some "mini"-pages (?!).

### Steps to Reproduce

1. create a new directory
2. drop some .jpg files into it (try it with >5 files)
3. execute `convert $(ls *.jpg) result.pdf`
4. view result.pdf

### System Configuration

- ImageMagick version: 7.0.10-13
- Environment (Operating system, version and so on): Arch Linux
- Additional information: I downgraded to 7.0.10-3 and everything works fine there.

**Comment by urban-warrior** [comment]
We'll get a patch to fix the problem within a day or two.  In the mean-time, add -define pdf:thumbnail=true to your command-line.

**Comment by jbirnick** [comment]
Your are awesome. Don't stress.
