### ISSUE TITLE
Test fails after installing ImageMagics

### ISSUE THREAD

**Issue by azharahmad** [ImageMagick/ImageMagick#204]
I installed the ImageMagics by following the steps from the below URL in Ubuntu
http://www.imagemagick.org/script/install-source.php

After following all the step except last i have not got any error. But at last step (make check) i got the error as in the screenshot.
![imagemagicerror](https://cloud.githubusercontent.com/assets/6468720/15468907/8c2b95be-2104-11e6-989d-98edb43b1c67.png)

Suggest me what should i do?

**Comment by dlemstra** [comment]
Can you upgrade to the most recent version and test if you can reproduce it again?

**Comment by azharahmad** [comment]
How can i upgrade the imageMagic tools

**Comment by dlemstra** [comment]
You will need to download the most recent version and follow the 'build from source steps' again.

**Comment by dlemstra** [comment]
Is this issue resolved @azharahmad ?
