### ISSUE TITLE
FAIL: tests/wandtest.tap 1

### ISSUE THREAD

**Issue by catherinesjy** [ImageMagick/ImageMagick#205]
I have an error with the test suite. Could anyone help? Thanks!

Here is the information in test-suite.log:

   ImageMagick 7.0.1: ./test-suite.log

- # TOTAL: 49
- # PASS:  48
- # SKIP:  0
- # XFAIL: 0
- # FAIL:  1
- # XPASS: 0
- # ERROR: 0

.. contents:: :depth: 2

FAIL: tests/wandtest

lt-wandtest: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1739.
lt-wandtest: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/508.
lt-wandtest: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1739.
lt-wandtest: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/508.
tests/wandtest.c main 5321 non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3176
1..1
Reading images...
Iterate forward...
index 0 scene 0
index 1 scene 1
index 2 scene 2
index 3 scene 3
index 4 scene 4
Iterate reverse...
index 4 scene 4
index 3 scene 3
index 2 scene 2
index 1 scene 1
index 0 scene 0
Remove scene 1...
index 0 scene 0
index 1 scene 2
index 2 scene 3
index 3 scene 4
Insert scene 1 back in sequence...
index 0 scene 0
index 1 scene 1
index 2 scene 2
index 3 scene 3
index 4 scene 4
Set scene 2 to scene 1...
index 0 scene 0
index 1 scene 1
index 2 scene 1
index 3 scene 3
index 4 scene 4
Apply image processing options...
not ok
FAIL: tests/wandtest.tap 1

**Comment by dlemstra** [comment]
Did you install libpng on your machine and what is the output of `convert -version`?

**Comment by catherinesjy** [comment]
Thank you for your reply. I have fixed this issue by ./configure --with-gslib=yes. And my current output of magick -version is 

> Version: ImageMagick 7.0.1-6 Q16 x86_64 2016-05-24 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP
Delegates (built-in): fontconfig freetype gslib jng jpeg lcms png ps tiff zlib
