### ISSUE TITLE
Programs call the wrong version of libraries.

### ISSUE THREAD

**Issue by laukau303** [ImageMagick/ImageMagick#2052]
### Prerequisites

- [x] I have written a descriptive issue title (I hope)
- [x] I have verified that I am using the latest version of ImageMagick 
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported (I've seen similar problems but not solutions)

### Description
Using any ImageMagick CLI program return the following error:

> "[imagemagick-program]: error while loading shared libraries: [library-name]-2_4.so.24: cannot open shared object file: No such file or directory"

The libraries are the ones installed by OpenEXR, and they are the newest version: 2.5, but the program calls the 2.4 version.

The error exists if `export LD_LIBRARY_PATH` is set to `export LD_LIBRARY_PATH=/usr/local/lib` in the `bashrc` file. Changing to `/usr/lib` or commenting/deleting the line and executing `ldconfig -v` makes ImageMagick function again. But the problem with this configuration didn't exist before.

The thing is, the program worked normally even with the "bad" configuration.

### Steps to Reproduce
1. Open terminal
2. Use any command (`convert`, `composite`, etc). There will be the error mentioned.

### System Configuration
- ImageMagick version: 7.0.10.13-1, openexr 2.5.1-1
- Environment (Operating system, version and so on):
Arch Linux, 64-bit
KDE Plasma 5.18.5, KDE Frameworks 5.70.0 (Qt: 5.14.2)
Kernel: 5.4.41-1-lts
OS Type: 64-bit

- Additional information:

* Executing the programs with `sudo` works but gives the "[black pages in PDF](https://github.com/ImageMagick/ImageMagick/issues/2032)" issue.
* Reinstalling the newest ImageMagick or OpenEXR does not change anything.
* Downgrading ImageMagick does not make it work.
* Downgrading OpenEXR to 2.4.1-2 makes ImageMagick work normally again.
* Using `ldconfig` doesn't change anything (whether or not the libpath is specified).
* Deleting `ld.so.cache` doesn't change anything.

### Fixing it:

Changing `export LD_LIBRARY_PATH=/usr/local/lib` to `export LD_LIBRARY_PATH=/usr/lib` , in the `bashrc` lines OR just commenting/deleting this 'export' line then running `ldconfig -v` should fix the issue (but this problem didn't exist before, I'll wait if something breaks). It also gives the new bugs/issues, like the black pages mentioned.

**Comment by urban-warrior** [comment]
Setting the LD_LIBRARY_PATH is an OS consideration for applications on your computer.  It is not specifically an ImageMagick problem -- meaning, there is not much we can do to help other than the method to fix you are using or to build static releases of the ImageMagick delegates.

The black PDF issue is resolved in the latest release of ImageMagick.

**Comment by laukau303** [comment]
Thank you so much! That's awesome. I've seen other people with my issue and I've searched a lot, with different methods that didn't work, so maybe now they'll know what to do if that happens to them.
