### ISSUE TITLE
Convert: memory allocation failed 

### ISSUE THREAD

**Issue by alexandervasylev** [ImageMagick/ImageMagick#206]
After update IM I have issue:

$ convert 'png.png' -resize 300x250 result.jpg
alex: memory allocation failed `png.png' @ error/png.c/ReadOnePNGImage/2109.
alex: no images defined `result.jpg' @ error/convert.c/ConvertImageCommand/3257.

Version: ImageMagick 6.9.4-1 Q16 x86_64 2016-05-19 http://www.imagemagick.org
Features: Cipher DPC
Delegates (built-in): bzlib fftw fontconfig fpx freetype jbig jng jp2 jpeg lcms lqr png tiff webp wmf x xml

How I can fix that?

**Comment by mikayla-grace** [comment]
The PNG library is failing to allocate a simple structure required to read PNG images.  Perhaps your system is severely resource restrained or perhaps its an unusually large image.  Or perhaps the PNG image is corrupt.  Does this work?

```
convert logo: logo.png
identify -verbose logo.png
```

If so, try this command:

```
convert -limit area 100 'png.png' -resize 300x250 result.jpg
```

If that command fails, post a link to your png.png image so we can download ans inspect it.

**Comment by dlemstra** [comment]
Can you respond to our questions @alexandervasylev ? Or did you resolve this issue and can we close it?

**Comment by mikayla-grace** [comment]
We cannot reproduce the problem and it appears to be localized within the PNG delegate library.

**Comment by alexandervasylev** [comment]
I reinstalled latest version of libpng and issue was resolved.

Thanks all.
