### ISSUE TITLE
Update delegates.xml to new Inkscape command line format

### ISSUE THREAD

**Issue by jhofinger** [ImageMagick/ImageMagick#2062]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
With Inkscape 1.0, which was released this month, a new command line syntax was introduced. It looks like the delegates entry for inkscape was not yet updated: https://github.com/ImageMagick/ImageMagick/blob/06e45a6745f6bed140e46d0dadedf796e5dcd9e6/www/source/delegates.xml#L112

### Steps to Reproduce
This was reported in the Inkscape bugtracker, hence I'm unable to fill out the entire issue template, since I didn't test it myself. 

See https://gitlab.com/inkscape/inbox/-/issues/496 for a full description. 

> I imagine it fails because export-png is no longer an input argument (use --export-type=png or just --export-file=EXPORT-FILENAME instead) to inkscape 1.0alpha.
>
> confirmed that I managed to get an output by editing the delegates.xml file.

### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
The latest ImageMagick releases include the new command-line argument for Inkscape 1.0.  Unfortunately, Inkscape did not deprecate the -export-png command-line option and instead opted to remove support.

**Comment by jhofinger** [comment]
Alright, thanks! Seems like config/delegates was updated, but www/source/delegates.xml not (yet), Is this necessary?

As far as I understand, the entire command line interface was redesigned.
