### ISSUE TITLE
mogrify -color 2 *.tiff does not convert image to indexed black and white

### ISSUE THREAD

**Issue by shirha** [ImageMagick/ImageMagick#2065]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
mogrify -color 2 *.tiff does not convert image to indexed black and white

### Steps to Reproduce
magick mogrify -colors 2 -path ../bw *.tiff

this command works in graphics magick but doesn't support -path
gm mogrify -colors 2 *.tiff

magick convert page_048.tiff -format %c histogram:info:
750496: (0,0,0) #000000 gray(0)
8299794: (255,255,255) #FFFFFF gray(255)

### System Configuration
windows 10
ImageMagick-7.0.10-14-Q16-x64-dll.exe

[page_048.zip](https://github.com/ImageMagick/ImageMagick/files/4678457/page_048.zip)

**Comment by fmw42** [comment]
try

`magick mogrify -colors 2 -type bilevel -path ../bw *.tiff`

**Comment by shirha** [comment]
-type bilevel didn't work with or without +dither

**Comment by fmw42** [comment]
Works fine for me in IM 7.0.10.14 Q16 Mac OSX

magick mogrify +dither -colors 2 -type bilevel lena.tif
magick identify -verbose lena.tif
Image:
  Filename: lena.tif
  Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass
  Geometry: 256x256+0+0
  Units: PixelsPerInch
  Colorspace: Gray
  **Type: Bilevel**
  Base type: Grayscale
  Endianness: LSB
  **Depth: 8/1-bit
  Channel depth:
    gray: 1-bit**
  Channel statistics:
    Pixels: 65536
    Gray:
      min: 0  (0)
      max: 255 (1)
      mean: 122.905 (0.481979)
      standard deviation: 127.418 (0.499679)
      kurtosis: -1.99483
      skewness: 0.0721277
      entropy: 0.999063
  Colors: 2
  Histogram:
    **33949: (0,0,0) #000000 gray(0)
    31587: (255,255,255) #FFFFFF gray(255)**
  Rendering intent: Undefined
  Gamma: 0.454545
  Background color: gray(255)
  Border color: gray(223)
  Matte color: gray(189)
  Transparent color: gray(0)
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 256x256+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Orientation: TopLeft
  Properties:
    date:create: 2020-05-26T17:09:00+00:00
    date:modify: 2020-05-26T17:09:00+00:00
    signature: 67446aee5dedbd73293e3aa44280092741646862c8cd698274ea2ff26f5bb5dd
    tiff:alpha: unspecified
    tiff:endian: lsb
    tiff:photometric: min-is-black
    tiff:rows-per-strip: 256
  Artifacts:
    filename: lena.tif
    verbose: true
  Tainted: False
  Filesize: 4252B
  Number pixels: 65536
  Pixels per second: 17.9388MB
  User time: 0.000u
  Elapsed time: 0:01.003
  Version: ImageMagick 6.9.11-14 Q16 x86_64 2020-05-23 https://imagemagick.org
Fredericks-Mac-mini:desktop fred$ 

Perhaps you want to compress it as well by adding -compress Group4  or -compress FAX

**Comment by shirha** [comment]
-compress Group4 actually worked! Thanks.
