### ISSUE TITLE
ImageMagick 6.9.4-3  -  cannot convert doc file to pdf/jpg

### ISSUE THREAD

**Issue by juggleberry** [ImageMagick/ImageMagick#207]
convert -verbose test.doc test-output.pdf
'soffice' --convert-to pdf -outdir `dirname '/var/tmp/magick-15188tmlsImnCv7dG'` '/var/tmp/magick-15188tmlsImnCv7dG' 2> '/var/tmp/magick-15188tj34WvcDg1Kb'; /bin/mv '/var/tmp/magick-15188tmlsImnCv7dG.pdf' '/var/tmp/magick-15188nApK_P3m4QFm'
mv: /var/tmp/magick-15188tmlsImnCv7dG.pdf: No such file or directory
convert: delegate failed `'soffice' --convert-to pdf -outdir `dirname '%i'` '%i' 2> '%u'; /bin/mv '%i.pdf' '%o'' @ error/delegate.c/InvokeDelegate/1962.
convert: unable to open file `/var/tmp/magick-15188rbHvQ-M0oRi5': No such file or directory @ error/constitute.c/ReadImage/544.
convert: no images defined `test-output.pdf' @ error/convert.c/ConvertImageCommand/3257.

**Comment by dlemstra** [comment]
The 'soffice' delegate could not be found. You will need to install OpenOffice for this.

**Comment by juggleberry** [comment]
Couldn't get it to work with OpenOffice as it wouldn't run 'soffice' in headless.
Managed to get it working with LibreOffice though.

**Comment by arirah** [comment]
Same for magick

```
magick de_14464023_001.wmf de_14464023_001.jpg
/bin/mv: cannot stat '/tmp/magick-vyvjGTHXYX2edCcvT8UdqAQDCPJxYfzo.pdf': No such file or directory
magick: delegate failed `'libreoffice' --convert-to pdf --outdir `dirname '%i'` '%i' 2> '%u'; /bin/mv '%i.pdf' '%o'' @ error/delegate.c/InvokeDelegate/1913.
magick: unable to open file '/tmp/magick-yQfhXdskt1WIOGCRqFH_moIsedMBIUiB': No such file or directory @ error/constitute.c/ReadImage/785.
```

**Comment by dlemstra** [comment]
`delegate failed 'libreoffice'` means that you did not install libreoffice.

**Comment by arirah** [comment]
@dlemstra  Thanks for your reply! But LibreOffice was already installed, and this issue was solved after 

```
./configure --with-wmf
 make
 make install
```
 But I still have an issue 
 
```
 magick de_14464023_001.wmf de_14464023_001_new.jpg
ERROR: player/meta.h (1681): Object out of range!
magick: failed to scan file `de_14464023_001.wmf' @ error/wmf.c/ReadWMFImage/2683.
```

 Can you please help to figure out the new issue?

**Comment by dlemstra** [comment]
`ERROR: player/meta.h (1681): Object out of range!` is not an error message from this library so you probably need to ask this question elsewhere.
