### ISSUE TITLE
pls improve security:ImageMagick popen() shell vulnerability via filename

### ISSUE THREAD

**Issue by hetz** [ImageMagick/ImageMagick#208]
I get message http://permalink.gmane.org/gmane.comp.security.oss.general/19669.

pls fix ,thx.

**Comment by mikayla-grace** [comment]
Download ImageMagick 7.0.1-8 or 6.9.4-6.  For those that require this functionality, add --enable-pipes and / or --enable-indrect-reads to your configure script command line, then build and install ImageMagick.
