### ISSUE TITLE
-gravity property when creating  blank pdf when using convert. 

### ISSUE THREAD

**Issue by frapps** [ImageMagick/ImageMagick#2083]
Hi, I've been trying to convert my png image to a pdf which appears to work fine until I use the gravity property, when I use the gravity property, I just get a blank pdf. 

I'm basically looking to ensure image is in the center of the outputted pdf. Rather than in anchored to the bottom currently. 

I want the output size to be A4 and the image dimensions to be the same, and not stretched, just centered in the pdf, I believe the. The command line I'm using is here. I've included both the document that works and the blank output pdf. As well as the source image. The property works if outputting to a jpg or something. 

"C:\Program Files\ImageMagick-7.0.10-0-portable-Q16-x64\convert" E:\Tickets\5335\280\svg.png -units pixelsperinch  -page a4 **-gravity center** -density 72 -rotate 90 E:\Tickets\5335\280\svg.pdf

[svgusinggravity.pdf](https://github.com/ImageMagick/ImageMagick/files/4711594/svgusinggravity.pdf)
[svg.pdf](https://github.com/ImageMagick/ImageMagick/files/4711584/svg.pdf)
![svg](https://user-images.githubusercontent.com/15358499/83415407-eff0e880-a416-11ea-81a3-af911134c7b0.png)

**Comment by fmw42** [comment]
I do not think PDF pages support A4 size. You need to use Letter size. Also -page does not support -gravity. You need to use the pixel equivalent of A4 or Letter with -resize and also center place the image in a white background using -extent as follows:

A4:
`convert svg.png +repage -rotate 90 -resize 595x842 -gravity center -background white -extent 595x842 -units pixelsperinch -density 72 x.pdf`


Letter:
`convert svg.png +repage -rotate 90 -resize 612x792 -gravity center -background white -extent 612x792 -units pixelsperinch -density 72 y.pdf`



See pixel equivalents at https://imagemagick.org/script/command-line-options.php#page

**Comment by frapps** [comment]
Brilliant, thank you for your help.
