### ISSUE TITLE
Magick++ gravity misaligns text over stroked text

### ISSUE THREAD

**Issue by Lastique** [ImageMagick/ImageMagick#209]
I'm having a problem with drawing text over the same text with a stroke (i.e. I want to draw text with an outline). I can do this with the following command line:

```
./convert-im6 -size 320x240 xc:lightblue -font Arial -pointsize 24 \
           -fill white -stroke black -strokewidth 20 \
           -gravity SouthEast \
           -annotate +0+0 'Hello \n World!' \
           -stroke none \
           -annotate +0+0 'Hello \n World!' \
           magick_stroke.png
```

However, when I do the same with Magick++ interface, the top-layer text is drawn shifted to the right of the bottom layer. This seems to happen only when the text is centered horizontally or right-aligned.

Here's the code I use:

```
#include <Magick++.h>

int main()
{
    const char text[] = "Hello \n World!";

    using namespace Magick;

    Geometry magick_geometry(320, 240);
    Image magick_image(magick_geometry, Color("lightblue"));
    magick_image.antiAlias(true);

    magick_image.fillColor(Color("white"));
    magick_image.font("Arial");
    magick_image.fontPointsize(24);

    const auto stroke_anti_alias = magick_image.strokeAntiAlias();
    magick_image.strokeAntiAlias(true);
    const auto stroke_width = magick_image.strokeWidth();
    magick_image.strokeWidth(20.0);
    const auto stroke_color = magick_image.strokeColor();
    magick_image.strokeColor(Color("black"));
    const auto stroke_line_join = magick_image.strokeLineJoin();
    magick_image.strokeLineJoin(RoundJoin);

    magick_image.annotate(text, SouthEastGravity);

    magick_image.strokeAntiAlias(stroke_anti_alias);
    magick_image.strokeWidth(stroke_width);
    magick_image.strokeColor(stroke_color);
    magick_image.strokeLineJoin(stroke_line_join);

    magick_image.annotate(text, SouthEastGravity);

    magick_image.write("magick_stroke.png");

    return 0;
}
```

I attached the two images I get - from the command line and C++. I expected the images to be the same.

C++:
![magick_stroke_magickxx](https://cloud.githubusercontent.com/assets/1589747/15754041/66f3359e-2907-11e6-99eb-7efd577bfe7c.png)

Command line:
![magick_stroke_cmdline](https://cloud.githubusercontent.com/assets/1589747/15754060/79c585be-2907-11e6-8104-f1d7b84b4728.png)

Kubuntu 16.04 x86_64. ImageMagick 6.8.9-9 and 6.9.4-0 (both behave the same way).

**Comment by Lastique** [comment]
Also, a related question. Is the text supposed to be that far from the right edge of the image? I would say, the white text in the C++ image (the closest to the right edge) is the most correct one, and the black stroked text and the white text on the "Command line" image are too far to the left.

**Comment by mikayla-grace** [comment]
A recent patch might fix the problem you reported.  Download ImageMagick 6.9.4-8, available sometime tomorrow.  Let us know if if you get expected results.

**Comment by Lastique** [comment]
Thanks, 6.9.4-8 seems to have fixed the problem. Here's the output from the C++ code with it:
![magick_stroke](https://cloud.githubusercontent.com/assets/1589747/15894112/2e9a85ca-2d95-11e6-9c24-995fac18e03a.png)
