### ISSUE TITLE
Converting a SVG to Jpeg results in a blank image

### ISSUE THREAD

**Issue by thibnes** [ImageMagick/ImageMagick#2098]
Hello,
when trying to convert the following SVG to Jpeg I end up with a blank image.
[sample.zip](https://github.com/ImageMagick/ImageMagick/files/4724313/sample.zip)

Some online converters manage to convert it and some others failed.

Any help would be appreciated. Thank you.

### Steps to Reproduce
command line: ``` magick sample.svg result.jpg ```

### System Configuration
- ImageMagick version: 7.0.10-16 Q16 x64
- OS: Windows 10

Best,

**Comment by urban-warrior** [comment]
Add -define svg:xml-parse-huge=true to your command-line.

**Comment by fmw42** [comment]
@urban-warrior 

Please add this define to the -define section of the options page documentation.

**Comment by thibnes** [comment]
Thank you it resolved my issue.

Best,
