### ISSUE TITLE
6.9.4-6 and 7.0.1-8 - 3 failed tests

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick#210]
```
Trying to build 7.0.1-8 or 6.9.4+6 (7.0.1-6 and 6.9.4-4 were ok)

FAIL: tests/validate-formats-memory.tap 1
FAIL: tests/validate-formats-disk.tap 1
FAIL: tests/validate-formats-map.tap 1
============================================================================
Testsuite summary for ImageMagick 7.0.1
============================================================================
# TOTAL: 86
# PASS:  83
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0
============================================================================
```

**Comment by remicollet** [comment]
Master seems ok, as I noticed about 6.9.4-7 and 7.0.1-9 being release (in commit history), I will wait for official tarball to be available to run another set of builds.

Notice: It will be nice, and could help, if the release were tagged on git (e.g. to run git bissect between 2 tags)

**Comment by dlemstra** [comment]
We have also noticed this and we are working on  a new release. I have also added a bunch of tags and will continue to do so in the future.

**Comment by remicollet** [comment]
Thanks for the tags (and another benefit, we are now able to subscribe to the release RSS feed)

**Comment by KitsuneSolar** [comment]
> 3 failed tests

Confirm!

**Comment by remicollet** [comment]
I confirm version 7.0.1-9 is ok.

**Comment by remicollet** [comment]
I confirm 6.9.4-7 is also ok.
Thanks.
Closing this one
