### ISSUE TITLE
Identify command always prints "1" if you limit it to only one frame in an animated image

### ISSUE THREAD

**Issue by Rekrullurker** [ImageMagick/ImageMagick#2101]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

The identify command can be used to get various information about an animated GIF. By default it prints this information for every frame, even if the information you're asking for is the number of frames. It also includes a way to limit such information to a single frame, by including a number in brackets after the filename. This works for other attributes such as the width, height or even the frame delay. However if you try to get the number of frames and limit it to just one frame, the result is always "1".

### Steps to Reproduce

identify -format %n\n test.gif
5
5
5
5
5

identify -format %n\n test.gif[0]
1

### System Configuration

Windows 32-bit

- ImageMagick version: 7.0.10-15 Q16 x86 2020-05-30
- Environment (Operating system, version and so on): Windows XP Pro, SP3 (yes I know, I'm way behind the times)
- Additional information:
I'm seen the other issue where someone complained that the number of frames was being printed multiple time and they were told that this is the expected behavior and won't be changed. I imagine that I'll be told something similar.

However I have to ask, without using other work-arounds, how are you supposed to be able to get the number of frames in an animated image for use in a script? Let's say that I want to create a script that moves all the animated images in a given directory to a different location so that I can check them to see if they have the delay between frames set properly. Not every GIF is animated, so I need a way to detect which ones have more than one image. If I don't limit the identify command to a single frame it prints multiple copies. Then I have to jump through hoops using string manipulation to figure out if the actual number is higher than one. How many digits do I process? Maybe the GIF only has three frames, or maybe it has 12. I can't just check the first digit, but the frame count might only be a single digit on some files.

If you can't get an accurate count of the number of frames when limiting the command to a single frame, how do you accurately get the number of frames?

And if this is happening because I'm asking for information on one frame and it's telling me that there's only one frame being processed, that's completely pointless. I already know it's a single frame because I specifically told it to process a single frame. It's supposed to be reporting information about the image format, not the command that I typed in.

**Comment by fmw42** [comment]
If you include Unix tools or perhaps there are similar one on Windows already, you can pipe and limit to the first line

`identify -format "%n\n" test.gif | head -n 1`

However, I agree. A define would be very helpful, such as -define identify:repeats=no|off

**Comment by Rekrullurker** [comment]
I figured out a way to do what I needed, but it still seems like a huge shortcoming that there's no way to get the total number of frames in an image as a single number, especially as that particular bit of information doesn't change depending on what frame you're looking at.

**Comment by fmw42** [comment]
It is added to my list of enhancements to do with the IM developers.

**Comment by Rekrullurker** [comment]
Thank you. :)

**Comment by snibgo** [comment]
See https://www.imagemagick.org/script/escape.php . %n doesn't tell you how many images are in a file, and isn't supposed to. It tells you the "number of images in current image sequence". As you say, if you have only one image, the result is one.

If you don't want to read images, but simply want metadata, exiftool is often a better tool:

```
f:\web\im>exiftool -args -FrameCount one-to-ten_1.gif

-FrameCount=50
```

In IM, "-format" loops through all the images, making one output for each image. Perhaps a useful addition to IM would be "-format_once" or similar name, which makes only one output however many images there are.

**Comment by Rekrullurker** [comment]
Do GIF files exist with multiple, separate "image sequences", each containing multiple images? As far as I'm aware, when a GIF or WEBP file has multiple images, they're all one sequence. So printing the number of images in the file for each image is rather redundant. If the number is always going to be the same and you're examining the entire file, shouldn't the whole thing be treated as one image sequence and the number of images only be printed once?
