### ISSUE TITLE
Imagemagick assumes dpi of output pdf is 72

### ISSUE THREAD

**Issue by kuba-orlik** [ImageMagick/ImageMagick#2119]
### Description

When converting an image to a pdf with an offset with the `-page` argument, the offset units are in dots. But even if I specify a custom density, the offset units still behave as if the density was set to 72.

### Steps to Reproduce

1. create a square image, like [this one](https://user-images.githubusercontent.com/2697916/84027945-575ee900-a97f-11ea-8fe4-f609feeb72e1.png)
2. run 

   `magick ./bitmap.png -density 200 -page 200x200+72+72 output.pdf`

3. Open the pdf - it's seemingly empty:

![image](https://user-images.githubusercontent.com/2697916/84028021-807f7980-a97f-11ea-9cf8-a589431189ef.png)

What happened here is that I created a 1x1 inch pdf with density of 200 dots per inch. I've added an image to it with offset ot 72. 72 is smaller than 200 dots per each side of the pdf, so the image should be still partially within the visible part of the document, but that's not the case - the square image is out of bounds.

### System Configuration

- ImageMagick version: 7.0.10-16 Q16 x86_64 2020-06-01
- Environment: Manjaro GNU/Linux

**Comment by urban-warrior** [comment]
ImageMagick is behaving as designed.  Page geometries are in pixels regardless of the resolution.

**Comment by kuba-orlik** [comment]
Thank you for clearing it up. Why is 72dpi the assumed resolution?

**Comment by urban-warrior** [comment]
The page offset is relative to the pixel offset and is simply independent of the resolution whether it be 72 or 300 or in centimetres or inches.

**Comment by kuba-orlik** [comment]
Hmm, how does one then calculate what offset to set when wanting to give the image a 1cm offset on the page?
