### ISSUE TITLE
Proper syntax to generate “text” images with ImageMagick doesn't work on MacOS 10.15.5 Catalina

### ISSUE THREAD

**Issue by shyamalschandra** [ImageMagick/ImageMagick#2133]
### Prerequisites

- [ X ] I have written a descriptive issue title
- [ X ] I have verified that I am using the latest version of ImageMagick
- [ X ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Proper syntax to generate “text” images with ImageMagick doesn't work on MacOS 10.15.5 Catalina

### Steps to Reproduce
1. convert -size 50x50 xc:none -gravity center -draw 'text 0,0 "A B C" ' 1.png
2. The error appears below:

```
convert: unable to read font `Chisel' @ warning/annotate.c/RenderType/960.
convert: unable to read font `Chisel' @ error/annotate.c/RenderFreetype/1392.
convert: non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4434.
```

### System Configuration
- ImageMagick version: ImageMagick 7
- Environment (Operating system, version and so on): MacOS 10.15.5
- Additional information:

**Comment by fmw42** [comment]
I believe you need to specify a font in your command. Apparently the default font is not set on your OSX.

**Comment by shyamalschandra** [comment]
I did and the same thing happened.

```
shyamalchandra@iMac Photos2MusicMovie % convert -size 1920x1080 xc:darkblue -pointsize 30 -gravity center -font Arial -draw 'text 1080,1080 "%D %T"' 0-resized.jpg  
convert: unable to read font `Arial' @ warning/annotate.c/RenderType/960.
convert: unable to read font `Arial' @ error/annotate.c/RenderFreetype/1392.
convert: non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4434.
```

**Comment by fmw42** [comment]
Is the Arial font specified in your type.xml file? If not, then it needs to be entered. Otherwise, you can specify the font by it font file and path to that file, e.g. -font /Library/Fonts/arial.ttf or whatever your path and arial font file is. Try using the path to the font file.

**Comment by shyamalschandra** [comment]
Thank you!
