### ISSUE TITLE
Identify can't open file with frame notation

### ISSUE THREAD

**Issue by ianpurvis** [ImageMagick/ImageMagick#214]
When I run `identify` where the filename has a frame range such as `image.png[0]`, I get an OpenBlob error:

```
identify -format '%wx%h' '/var/folders/zp/dsbgc8v16zz0s4tjkfbkytwc0000gn/T/8bb9aaebf58ab32612f7a64ab273da8a20160605-13366-1wrj0qw.png[0]'
identify: unable to open image `/var/folders/zp/dsbgc8v16zz0s4tjkfbkytwc0000gn/T/8bb9aaebf58ab32612f7a64ab273da8a20160605-13366-1wrj0qw.png[0]': No such file or directory @ error/blob.c/OpenBlob/2705.
identify: unable to open file `/var/folders/zp/dsbgc8v16zz0s4tjkfbkytwc0000gn/T/8bb9aaebf58ab32612f7a64ab273da8a20160605-13366-1wrj0qw.png[0]' @ error/png.c/ReadPNGImage/3921.
```

If I remove the range, it works as expected.

```
identify -format '%wx%h' '/var/folders/zp/dsbgc8v16zz0s4tjkfbkytwc0000gn/T/8bb9aaebf58ab32612f7a64ab273da8a20160605-13366-1wrj0qw.png'
256x255
```

I'm running ImageMagick 6.9.4-7 Q16 x86_64 2016-06-04 on OSX 10.11.5.

I've attached a debug dump of each run. 
[identify_with_frame.txt](https://github.com/ImageMagick/ImageMagick/files/299518/identify_with_frame.txt)
[identify_without_frame.txt](https://github.com/ImageMagick/ImageMagick/files/299519/identify_without_frame.txt)

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by ianpurvis** [comment]
Thanks! I tested in master and it's working great now. 👍
