### ISSUE TITLE
Add Dockerfile/Containerfile to repo for building & release official image

### ISSUE THREAD

**Issue by emanuelb** [ImageMagick/ImageMagick#2141]
There is no Dockerfile or Containerfile in this repo for building ImageMagick from source directory (using COPY instructions)
And there is not official image for ImageMagick posted anywhere (DockerHub or GitHub Packages)
Searching this repo for Docker return:
> <p>In addition to the security policy, you can make ImageMagick safer by ...</p>

https://github.com/ImageMagick/ImageMagick/blob/c253f2f8bc81c2f200dd397b29ae1f2766038ba9/www/security-policy.html#L245

But there no mention on how to do it, examples of ImageMagick Dockerfiles from the internet (that build from source, not installing from package):
https://github.com/dooman87/imagemagick-docker/blob/master/Dockerfile
https://gist.github.com/251/0be2ce762de1aba268318d49333d332f

Thus will enable:
- easy building of master version
- official releases will enable easy testing using different versions including newer ones not packaged yet in distros (such as debian..)

**Comment by dlemstra** [comment]
Building master of ImageMagick itself would be running `./configure` with the arguments that would be the best for your situation and then running `make install` to install the library. The rest of the setup would be installing delegates that are used as a dependency for our project like for example libjpeg. And that part also depends on your situation and what you need to have included. We don't know what you want/need so we cannot have an official release image that would work for every situation. And if we could somehow would be able to create an image that would work for most people we would need to maintain it and make sure we update the delegates. We have a very small team and we would rather focus our time on other things.

**Comment by dooman87** [comment]
Hi @emanuelb, I'm trying to keep my image up to date with upstream version and provide 2 base images for Fedora and Debian. You could find it here - https://github.com/dooman87/imagemagick-docker. I have plans to do some hardening (at least non root user) in a near future, but PRs are welcome :)

**Comment by dooman87** [comment]
@dlemstra I'm happy to move the repo with docker images (see above comment) under ImageMagick space and maintain them if the project could benefit from that.

**Comment by emanuelb** [comment]
> We don't know what you want/need so we cannot have an official release image that would work for every situation.

it's fixed by installing everything related (all possible runtime-deps) by default, and have options to configure what will be used (if different packages can provide same functionality but only one can be used)

> And if we could somehow would be able to create an image that would work for most people we would need to maintain it and make sure we update the delegates. 

it's easy to do it (if used packages and not compile from source it automatically updates), but it still work, so better if community will help you with that, see offer by @dooman87 

as ImageMagick downloads page at:
https://imagemagick.org/script/download.php

currently offer .rpm files:
ImageMagick-7.0.10-19.x86_64.rpm -> Redhat / CentOS 7.1 x86_64 RPM
ImageMagick-libs-7.0.10-19.x86_64.rpm -> Redhat / CentOS 7.1 x86_64 RPM
ImageMagick RPM's -> Development, Perl, C++, and documentation RPM's.

I think it will be better to use `fedora:latest` or `fedora:rawhide` or `registry.access.redhat.com/ubi8/ubi-minimal:latest` as base for official image (maybe code that create the RPM file can be reused here)

**Comment by emanuelb** [comment]
here `Containerfile` that is based on @dooman87 repo, that use `debian:sid-slim` to build master version, tested with `podman` 
`podman build --rm -t imagemagic .`
`podman run --rm -t imagemagic --verbose file.png`

```Dockerfile
FROM debian:sid-slim

ARG DEBIAN_FRONTEND=noninteractive

LABEL org.opencontainers.image.title="Official ImageMagick image" \
      org.opencontainers.image.description="Run ImageMagick with Debian." \
      org.opencontainers.image.source="https://github.com/ImageMagick/ImageMagick.git/"

RUN set -ex; \ 
    useradd -ms /bin/bash user; \
    apt-get -y update; \
    apt-get -y install git make gcc pkg-config autoconf libpng16-16 libpng-dev libjpeg62-turbo libjpeg62-turbo-dev libwebp6 libwebp-dev libgomp1 libwebpdemux2 libwebpmux3 ghostscript; \
    git clone --depth 1 https://github.com/ImageMagick/ImageMagick.git && cd ImageMagick; \ 
    ./configure && make && make install; \
    ldconfig /usr/local/lib; \
    apt-get remove --autoremove --purge -y gcc make git autoconf pkg-config libpng-dev libjpeg62-turbo-dev libwebp-dev; \
    rm -rf /ImageMagick \
             /var/lib/apt/lists/*

USER user
WORKDIR /home/user

ENTRYPOINT ["identify"]
```

Sure it can be improved a lot (such as using multi-stage-build, not running make as root if possible, using alpine instead of debian, etc...)

It's good enough for what I need ImageMagick right now, might be useful for others, and used as base to build better version that will be included here as official one :)
