### ISSUE TITLE
-unsharp

### ISSUE THREAD

**Issue by justin3333** [ImageMagick/ImageMagick#2148]
Good morning, 

Our development team ran into an issue with the -unsharp option with the convert command. We are updating some software tools (Pixelizer) that used image Magick for photo analysis. We are trying to get to the root of the issue and what the purpose of -unsharp is, and why is seems to add a tint to our processed photos. 

Here is an excerpt from the issue we ran into:

"So the command used is: "magick convert %s  -resize 15% -unsharp 0x1 %s" % (filename, jpegFileName)

The issue is with -unsharp 0x1. This command tells Image Magick to "clean up" the photo of any blurring that may have occurred, mostly likely so that Pixelizer could get "cleaner" pixel data so that is could better process any damage to the test subject

In a nutshell, in older versions of Image Magick, leaving the first value as 0 will allow the Image Magick to automatically set it to a value that is appropriate for the post-processed photo based on the size and resolution of the photo. However in Image Magick version available now, this command does not automatically set it to a value and we suspect that its keeping it as 0 and therefore confusing Image Magick on how to process the photo, so it just decides to "white out" the photo. 

The solution to set it to a value that is appropriate for our situation. According to https://redskiesatnight.com/2005/04/06/sharpening-using-image-magick/, the value should roughly based off of this rule:
(Radius is the first value, Sigma is the second value, -unsharp 0x1)
if radius < 1, then sigma = radius
else sigma = sqrt(radius)

Since sigma is already defined as 1 from the previous developer, we feel that based off these equations, going with a value of 1 for radius would be acceptable. In other words changing the code to -unsharp 1x1. From what we can see it produces the same result on (Computer 1), as using -unsharp 0x1 on our computers. 

The question would be ultimately what effect was trying to be achieved with the original -unsharp 0x1? Because without knowing what the original requirement was, changing to -unsharp 1x1 would clean up the photo but maybe not necessarily to the standard that was originally intended."

Any help in this matter would be greatly appreciated.

**Comment by fmw42** [comment]
Unsharp is kind of a misnomer. It is a sharpening filter. The first two arguments radiusxsigma should compute a proper radius if radius is provided as 0 and a non-zero sigma is provided, such as 0x1.  The algorithm is complicated, but approximately radius = 3*sigma+1 or 2*sigma+1. I am not sure which without looking at the code.  If the last two arguments are set to zero, -unsharp 0xsigma+0+0 should be the same or nearly the same as -sharpen 0xsigma.

Please not that proper syntax in IM 7 is to use magick and not magick convert. The latter will give IM 6 behavior or possibly some mixed behavior that may be the cause of your issue.

Can you provide an input image that produces your issue?

**Comment by justin3333** [comment]
Thank you, we make the changes tomorrow and test with -sharpen0x1 and see if the results are affected. 

Below is the before and after photos using the -unsharp 0x1 command. 

![Picture1_before](https://user-images.githubusercontent.com/66968292/84701608-87bffd80-af12-11ea-844f-2597104a8490.jpg)
![Picture1_after](https://user-images.githubusercontent.com/66968292/84701631-93132900-af12-11ea-85d2-732f6d17c20c.jpg)

**Comment by fmw42** [comment]
What is your exact IM version and platform?  It works fine for me on IM 7.0.10.19 Q16 Mac OSX Sierra using libjpeg 90.  

`magick img.jpg -unsharp 0x1 x.jpg`

![x](https://user-images.githubusercontent.com/13458218/84702208-1a5c9e80-af0b-11ea-9c60-a0f7d54ddd60.jpg)



What do you get from

`magick -version`

and

`magick -list format`

for the line starting with JPG or JPEG

**Comment by justin3333** [comment]
Microsoft Windows [Version 10.0.18363.900]
Version: ImageMagick 7.0.8-58 Q16 x64 2019-07-30 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib

JPEG* rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.0.2)
JPG* rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.0.2)

**Comment by fmw42** [comment]
Your version of ImageMagick is rather old. I suggest you upgrade.
