### ISSUE TITLE
linecap doesn't always work and has odd behaviour

### ISSUE THREAD

**Issue by MarkMurphy** [ImageMagick/ImageMagick#215]
### Broken on one end
```
convert -size 400x400 xc: -fill white -stroke red \
-strokewidth 20 -draw "stroke-linecap round line 50,50 200,200" linecap_broken_end.png
```
![Image of broken linecap](https://dl.dropboxusercontent.com/u/16119361/linecap_broken.png)

### Broken both ends
```
convert -size 400x400 xc: -fill white -stroke red \
-strokewidth 20 -draw "stroke-linecap round line 200,200 300,300" linecap_broken_both_ends.png
```
![Image of broken linecaps](https://dl.dropboxusercontent.com/u/16119361/linecap_broken_both_ends.png)

### Not Broken

```
convert -size 400x400 xc: -fill white -stroke red \
-strokewidth 20 -draw "stroke-linecap round line 50,50 100,100" linecap.png
```

![Image non-broken linecaps](https://dl.dropboxusercontent.com/u/16119361/linecap.png)

As you can see, the only thing I've changed between each command is the x1,y1 and x2,y2 coordinates. This also occurs for other draw commands such `path`, `polyline`, etc. 

**Using ImageMagick 6.9.4-8 Q16 x86_64 2016-06-08**

**Comment by t9mike** [comment]
Here is another failing test case:

```
convert -size 220x220 xc: -draw 'fill none stroke-linecap round
    stroke-width 20 stroke red ellipse 110,110 100,100 25,345' test.png
```
![image](https://cloud.githubusercontent.com/assets/1008514/15902809/76da0dea-2d6f-11e6-8fac-dd44ee4de9b4.png)

**Comment by MarkMurphy** [comment]
This won't work in all situations but one potential workaround until this is fixed is to also use `stroke-linejoin round`:

```
convert -size 220x220 xc: -draw 'fill none stroke-linecap round  stroke-linejoin round
    stroke-width 20 stroke red ellipse 110,110 100,100 25,345' test.png
```

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by MarkMurphy** [comment]
@mikayla-grace 👍  seems like it's all good now in v6.9.4-9. Thanks!
