### ISSUE TITLE
Please include support for fallback fonts.

### ISSUE THREAD

**Issue by infinnie** [ImageMagick/ImageMagick#2153]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Per https://github.com/ImageMagick/ImageMagick/issues/711#issuecomment-326313936
> The ImageMagick philosophy is that the user is king-- meaning we try real hard to not do anything automatically and instead we follow the instructions of the user via the command-line options including defines and settings. That way the user does not get unexpected or unexplained results.

And the real “unexpected” and “unexplained” result that has almost tripped everybody up is—exactly—that ImageMagick does not support fallback fonts: the original issue’s author had to resort to alternate solutions like https://stackoverflow.com/questions/45987676/missing-utf-8-symbols-in-font-how-to-combine-multiple-fonts-into-one-linux, and meanwhile, one cannot even use a syntax like the CSS `font-family` declaration to manually declare fallback fonts. So unsupported text in a certain font will appear as blanks in the generated image.

### Steps to Reproduce

See #711

### System Configuration

- ImageMagick version: ImageMagick 7.0.10-19 Q16 x64 2020-06-12
- Environment (Operating system, version and so on): Windows 7
- Additional information:

**Comment by urban-warrior** [comment]
hanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

Note, ImageMagick supports CSS-style font families lists.  If a family is not available, it tries the next in the list.
