### ISSUE TITLE
ImageMagick-7.0.10-19 Make Build Error with Cygwin

### ISSUE THREAD

**Issue by Alexander12365** [ImageMagick/ImageMagick#2155]
### Steps to Reproduce

./configure 

or

 ./configure --with-quantum-depth=32 --enable-hdri --with-rsvg=yes --with-windows-font-dir=/cygdrive/c/Windows/Fonts --disable-docs

make

![MakeError](https://user-images.githubusercontent.com/128189/84828671-b3cca300-b026-11ea-8c5e-0a5fffdaea7a.png)

File is not found even though it actually exists:
![FileExists](https://user-images.githubusercontent.com/128189/84828962-37868f80-b027-11ea-82dc-264d987e2cc6.png)

### System Configuration
- ImageMagick-7.0.10-19
- Windows 10 64bit
- cygwin64

**Comment by urban-warrior** [comment]
Unfortunately, we cannot reproduce the problem.  We have the same system configuration as you and ImageMagick compiled and linked and ran without complete.  Try a `make clean` followed by `make`.  Does it still fail?

**Comment by Alexander12365** [comment]
### System Configuration
* ImageMagick-7.0.10-19
* Windows 10 64bit Version 1909
* cygwin version: 3.1.4 x86_64

Yes the problem persists with make clean, even when using a new unzipped version. I have also tried compiling at a different location such as /cygdrive/c/ImageMagick resulting in the same error.

I have added the configuration log here:
* [config.log](https://github.com/ImageMagick/ImageMagick/files/4797079/config.log)

compiling with g++.exe (tdm64-1) 9.2.0 from here
* https://jmeubank.github.io/tdm-gcc/

**Comment by Alexander12365** [comment]
I am not sure what the exact reasons are, but I do not get an error when I specify the target and host environment as such:

./configure --target=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --with-quantum-depth=32 --enable-hdri --with-rsvg=yes --with-windows-font-dir=/cygdrive/c/Windows/Fonts --disable-docs

however I get errors after with make check:
* [test-suite.log](https://github.com/ImageMagick/ImageMagick/files/4798014/test-suite.log)
