### ISSUE TITLE
PSD format: CompressionNotSupported exception on ReadPSDChannel

### ISSUE THREAD

**Issue by mbaldassarre** [ImageMagick/ImageMagick#216]
Resampling this image (https://www.dropbox.com/s/d58zwz5jrxlrlpa/shutterstock_295418774-2.psd?dl=0) fails with this error:

/ImageMagick-7.0.1/bin/convert -verbose -units PixelsPerInch /Users/mbaldassarre/Downloads/shutterstock_295418774-2.psd -resample 72 output.psd

convert: CompressionNotSupported '5398' @ warning/psd.c/ReadPSDChannel/1226.
convert: CompressionNotSupported '2553' @ warning/psd.c/ReadPSDChannel/1226.
convert: CompressionNotSupported '57856' @ warning/psd.c/ReadPSDChannel/1226.
convert: UnableToDecompressImage '/Users/mbaldassarre/Downloads/shutterstock_295418774-2.psd' @ error/psd.c/ReadPSDChannel/1237.
convert: NoImagesDefined 'output.psd' @ error/convert.c/ConvertImageCommand/3235.

The image, from the XMP headers, was last saved by Photoshop CC 2015.
I have tried opening and re-saving the image with Photoshop CS6, but similar error occurs.

I have looked at the source code where the exception is fired, and it seems that the "compression" field is not read correctly. It should be one of these values: (also as per http://www.adobe.com/devnet-apps/photoshop/fileformatashtml ):
  Raw = 0,
  RLE = 1,
  ZipWithoutPrediction = 2,
  ZipWithPrediction = 3

But instead the exception is reporting a compression of 5398, 2553, 57856 for the three layers.
See also attached how the layers look in Photoshop.

I am using version
Version: ImageMagick 7.0.1-4 Q16 x86_64 2016-05-15 http://www.imagemagick.org

Thank you
Marco
![screen shot 2016-06-09 at 16 22 38](https://cloud.githubusercontent.com/assets/10773751/15935222/7e4e2b84-2e5e-11e6-8162-314c0d20650e.png)
![screen shot 2016-06-09 at 16 22 35](https://cloud.githubusercontent.com/assets/10773751/15935225/7e6bfa74-2e5e-11e6-92ec-74ced5897fd5.png)
![screen shot 2016-06-09 at 16 22 30](https://cloud.githubusercontent.com/assets/10773751/15935223/7e671c02-2e5e-11e6-9d7a-ce7b9f5fe6e8.png)
![screen shot 2016-06-09 at 16 22 19](https://cloud.githubusercontent.com/assets/10773751/15935224/7e677422-2e5e-11e6-8042-88750abb043b.png)

**Comment by dlemstra** [comment]
I can reproduce the issue and I have figured out when it was introduced but I don't understand why right now. I will take a look at it again after this weekend. Thank you for reporting this.

**Comment by mbaldassarre** [comment]
Thank you very much Dirk.
Let me know if you need further data.

Best
Marco

On 10 giu 2016, at 21:55, Dirk Lemstra <notifications@github.com<mailto:notifications@github.com>> wrote:


I can reproduce the issue and I have figured out when it was introduced but I don't understand why right now. I will take a look at it again after this weekend. Thank you for reporting this.

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/ImageMagick/ImageMagick/issues/216#issuecomment-225293258>, or mute the thread<https://github.com/notifications/unsubscribe/AKRk9-J-KM5mSV0AbIgPLVMu8dT5F5MFks5qKc80gaJpZM4IyGBR>.

The information contained in this e-mail is of a confidential nature and is intended only for the addressee. If you are not the intended addressee, any disclosure, copying or distribution by you is prohibited and may be unlawful. Disclosure to any party other than the addressee, whether inadvertent or otherwise, is not intended to waive privilege or confidentiality. Internet communications are not secure and therefore Conde Nast does not accept legal responsibility for the contents of this message. Any views or opinions expressed are those of the author.
