### ISSUE TITLE
identify does not recognize RGB colorspace images as RGB colorspace, but as sRGB colorspace instead

### ISSUE THREAD

**Issue by pandabear** [ImageMagick/ImageMagick#2161]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
With Centos 7.7 with ImageMagick 7.0.10-19 and using the `identify -verbose Shoes-AdobeRGB.jpg` (provided by https://webkit.org/blog-files/color-gamut/ ) to find out the image's colorspace, the tool reports the colorspace as `sRGB`. This is wrong as I expected colorspace to be `RGB`. The ICC-profile is correct on judging the file to be Adobe RGB though.

### Steps to Reproduce
1. Download Shoes-AdobeRGB.jpg from https://webkit.org/blog-files/color-gamut/ or here 
[Shoes-AdobeRGB](https://user-images.githubusercontent.com/1287579/84902501-90046e00-b0b5-11ea-91c6-c220fd29fd44.jpg)
2. Run `identify -verbose` on the image and check the `Colorspace:` section.

### System Configuration

- ImageMagick version: ImageMagick 7.0.10-19 Q16 x86_64
- Environment (Operating system, version and so on): Centos 7.7
- Additional information: None

**Comment by urban-warrior** [comment]
Choosing the colorspace based on the ICC name, e.g. "Adobe RGB (1998)" is not reliable.  Do you know of an ICC profile attribute that can reliably distinguish between RGB and sRGB colorspaces?

**Comment by pandabear** [comment]
sRGB color standard includes defined chromaticities for red, green and blue primaries. This creates a contradiction when the image has some other color profile with different color primaries defined (such as Adobe RGB). One option here could be to refer to an ICC profile if such is present, e.g. by giving "iccbased" (or something similar) as a colorspace value.

**Comment by snibgo** [comment]
An image that is encoded as AdobeRGB is neither linear RGB nor non-linear sRGB. AdobeRGB has a transfer curve that is similar to sRGB, but with different primaries, as you say.

IM doesn't have a colorspace that means "refer to the embedded ICC profile". Perhaps it should, but that would raise questions like: what would the "-colorspace" operation do when converting to or from that colorspace?

**Comment by ValZapod** [comment]
>AdobeRGB has a transfer curve that is similar to sRGB, but with different primaries, as you say.

It does in fact have pure 2.2000 gamma compared to sRGB which is only close to it.

**Comment by ValZapod** [comment]
JPEG does in fact have a way to signal chromaticities and gamma. See this image with exiftool https://github.com/Beep6581/RawTherapee/issues/1805#issuecomment-1249696139

```
White Point                     : 0.313 0.329
Primary Chromaticities          : 0.64 0.33 0.21 0.71 0.15 0.06
Y Cb Cr Coefficients            : 0.299 0.587 0.114
Y Cb Cr Positioning             : Co-sited
Gamma                           : 2.2
```

That is all the needed data. As for ICC that should be parsed, obviously. @dlemstra :)
