### ISSUE TITLE
vertical stripes in resized images

### ISSUE THREAD

**Issue by PontiacCZ** [ImageMagick/ImageMagick#2165]
### Description
Lanczos or Mitchell resize methods produce vertical stripes in generated images. It looks like this:

![image](https://user-images.githubusercontent.com/9153595/84920946-1f188280-b0c4-11ea-88cd-ada273d9005c.png)

### Steps to Reproduce

1. Download `tower.jpg` from [my Dropbox](https://www.dropbox.com/sh/soy1w22w8jcruba/AAAG61zUFsYdjukveBQyXbbla?dl=0)
2. run following command in the image directory: `magick tower.jpg -filter Lanczos -resize 2000x2000 tower_Lanczos.jpg`
3. examine generated image `tower_Lanczos.jpg` - contains 6 vertical stripes

### System Configuration

- ImageMagick version:
Version: ImageMagick 7.0.10-19 Q16 x64 2020-06-12 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC HDRI OpenCL
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib

- Environment (Operating system, version and so on): Windows 10 Pro (64 bit)
- Additional information: Lenovo X395, AMD Ryzen Pro 3500U, 2.10 GHz, 16 GB RAM

**Comment by fmw42** [comment]
Your command an image work fine for me on IM 7.0.10.19 Q16 Mac OSX with libjpeg 90.  What jpg delegate and version are you using? You can find that from

`magick -list format`

and look at the end of the line for JPG.

**Comment by PontiacCZ** [comment]
At the _beginning_ of the line :-) . It returns following line for JPG:

`JPG* rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.0.2)`

I don't understand what that is. It just all came with the portable windows package. :-) 

BTW you have Mac OSX version. Maybe the troubles are only with the Windows version.

**Comment by fmw42** [comment]
My suspicion is that it is your libjpeg-turbo. You are using an older version. It is now at 2.0.4. See https://sourceforge.net/projects/libjpeg-turbo/files. Perhaps try upgrading that and see if that fixes the issue.

**Comment by PontiacCZ** [comment]
I have the latest imagemagick (downloaded today) so I supposed everything was up to date?

Well, I can try to download separately latest libjpeg-turbo but I am puzzled as to what I am supposed to download and where to put it. I searched the directory with imagemagick and didn't find any libjpeg library which I could replace. It's not installed in Windows as well. Isn't it compiled in the main imagemagick executable?

**Comment by fmw42** [comment]
Sorry, I am not a Windows user. So I cannot help you install an update for your delegate. Perhaps one of the Windows users can point you in the correct direction for doing that or confirm if they can reproduce your issue. Otherwise, it will have to wait for one of the IM developers to look into it.

**Comment by urban-warrior** [comment]
It could be an OpenCL issue:

If ImageMagick includes OpenCL support, the OpenCL path is enable by default. You can disable it, simply set the environment variable MAGICK_OCL_DEVICE to OFF. You could also force the OpenCL path to use a particular class of devices by setting it to GPU or CPU.

Turn off OpenCL and see if you still get the same results.

**Comment by PontiacCZ** [comment]
Yup, that works!

I created a new environment variable MAGICK_OCL_DEVICE = OFF and ran my command. Resulting image is correct without those stripes. :-)  I tried it repeatedly back and forth - I changed the variable to ON, did the resize operation a few times, the distortion was there again. Then to OFF and the resized image was clear.

So this DID help. Thank you!

BTW when I was creating the MAGICK_OCL_DEVICE variable, I found out there was already another variable apparently related to Imagemagick in the system variables dialogue - MAGICK_HOME containing path somewhere in my Darktable installation. Can't that have any influence on the OpenCL operation?

![image](https://user-images.githubusercontent.com/9153595/84999049-eecaf580-b150-11ea-8a0f-585677ebff92.png)

**Comment by earthiverse** [comment]
I had the same problem with my image, but horizontal striping. Setting this to "OFF" fixed my problem too.

Environment (Operating system, version and so on): Windows 10 Home (64 bit)
Additional information: AMD Ryzen 9 4900HS, RTX 2060.

![out_1080p_0032](https://user-images.githubusercontent.com/602905/92062026-ac6d9800-edd2-11ea-8bbc-0de83d6f5ee7.png)
