### ISSUE TITLE
16-bit PSD with alpha not decoded correctly

### ISSUE THREAD

**Issue by jonsneyers** [ImageMagick/ImageMagick#2167]
This 16-bit PSD file looks like this in Photoshop:
<img width="642" alt="Screenshot 2020-06-18 at 09 39 38" src="https://user-images.githubusercontent.com/15010068/84992050-a6f3a080-b147-11ea-9869-cab23d3bb7f2.png">

but when decoded by ImageMagick, it has only one layer, and the alpha channel is missing in it (it's black text on a white background instead of a transparent background).

[test-alpha16.psd.zip](https://github.com/ImageMagick/ImageMagick/files/4797010/test-alpha16.psd.zip)

When saved as an 8-bit PSD file, it's fine.

The issue seems to be that for some reason, Photoshop produces a PSD file with a layer count of 0 even though it should in this case actually be -2. It must be hiding the real layer count somewhere else than in the normal place.

I only tried it on ImageMagick 6.9.10-23 but I suspect it will be the same in v7.

**Comment by dlemstra** [comment]
We made various improvements to the PSD coder in IM7. Would it be possible to confirm if is also an issue in IM7?

**Comment by fmw42** [comment]
It works fine for me on IM 6.9.11.19 and on IM 7.0.10.19 Q16 Mac OSX saving as PNG or as PSD. You do not say what output format you saved!

convert test-alpha16.psd x.png

![x](https://user-images.githubusercontent.com/13458218/85045574-fa63ef80-b143-11ea-9d26-7f8688bf969c.png)

**Comment by jonsneyers** [comment]
Oh OK nevermind then, sorry.
