### ISSUE TITLE
No instructions for installing missing deps

### ISSUE THREAD

**Issue by emanuelb** [ImageMagick/ImageMagick#2171]
Reading: https://imagemagick.org/script/download.php
Downloading .rpm files, try to install them as documented on Fedora 32 (latest version):
`rpm -Uvh ImageMagick-7-*` `rpm -Uvh ImageMagick-libs-7.*`
will result in many `error: Failed dependencies:` Errors such as:
```
	libHalf.so.6()(64bit) is needed by ImageMagick-libs-7.0.10-19.x86_64
	libIex.so.6()(64bit) is needed by ImageMagick-libs-7.0.10-19.x86_64
	libIexMath.so.6()(64bit) is needed by ImageMagick-libs-7.0.10-19.x86_64
	libIlmImf.so.7()(64bit) is needed by ImageMagick-libs-7.0.10-19.x86_64
	libIlmThread.so.6()(64bit) is needed by ImageMagick-libs-7.0.10-19.x86_64
	libImath.so.6()(64bit) is needed by ImageMagick-libs-7.0.10-19.x86_64
	libfftw3.so.3()(64bit) is needed by ImageMagick-libs-7.0.10-19.x86_64
	libpng15.so.15()(64bit) is needed by ImageMagick-libs-7.0.10-19.x86_64
	libpng15.so.15(PNG15_0)(64bit) is needed by ImageMagick-libs-7.0.10-19.x86_64
	libwebp.so.4()(64bit) is needed by ImageMagick-libs-7.0.10-19.x86_64
	libwmflite-0.2.so.7()(64bit) is needed by ImageMagick-libs-7.0.10-19.x86_64
```

The documentation say:
> Note, if there are missing dependencies, install them from the EPEL repo.

But not how to do it, adding EPEL repo, how to install the missing deps... (what command to execute which will install the needed packages)

**Comment by urban-warrior** [comment]
The binary RPM files work under CentOS.  Try building from the source RPM or download the portable release @ https://imagemagick.org/download/binaries/magick.
