### ISSUE TITLE
Caption no longer wrapping

### ISSUE THREAD

**Issue by dianomi-mjs** [ImageMagick/ImageMagick#2178]
Hi,

Since a recent upgrade of imagemagick on centos caption is no longer wrapping lines. Taking the example from [the documentation](http://www.imagemagick.org/Usage/text/#caption) with a couple of tweaks for height and font

`convert -background lightblue  -fill blue  -font Helvetica-Narrow-Bold -pointsize 40           -size 320x320  -gravity Center  caption:'ImageMagick Rules OK!'           caption_centered_4.gif`

gives 

![caption_centered_4](https://user-images.githubusercontent.com/17158995/85198423-827efc00-b2e0-11ea-9f3a-a4814f73f68b.gif)

Version:
```
Version: ImageMagick 6.9.10-68 Q16 x86_64 2020-04-01 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
```
Is this a bug or has the usage changed?

**Comment by dlemstra** [comment]
Can you reproduce this issue with the latest version of ImageMagick?

**Comment by dianomi-mjs** [comment]
Hi, thanks for the feedback. I believe this is the latest version available on centos through yum. Do you mean I should compile from source?

**Comment by dianomi-mjs** [comment]
I installed a local copy

Version: ImageMagick 7.0.10-19 Q16 x86_64 2020-06-20 https://imagemagick.org

But same result

**Comment by urban-warrior** [comment]
hanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dianomi-mjs** [comment]
Thanks, for anyone who comes here looking for a solution, a work-around is to use pango
https://www.imagemagick.org/Usage/text/#pango_markup
