### ISSUE TITLE
ImageMagick x64 fails to recognize 64bit  ghostscript ( gswin64c.exe)

### ISSUE THREAD

**Issue by jobsken2017** [ImageMagick/ImageMagick#2180]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I install the latest ImageMagick and GhostScript (both x64 version). I find ImageMagick fails to recognize gswin64c.exe and still requires gswin32c.exe. The error output is shown:

```
>> magick test.jpg -resize 167% test.eps
magick.exe: FailedToExecuteCommand `"gswin32c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -g420x162 -dEPSCrop  "-sOutputFile=C:/Users/xx/AppData/Local/Temp/magick-31872WuzMb0d5c-Hz%d" "-fC:/Users/xx/AppData/Local/Temp/magick-31872cpU2RmqF-Sh6" "-fC:/Users/xx/AppData/Local/Temp/magick-31872ebXwECXOSrGl"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/475.
magick.exe: FailedToExecuteCommand `"gswin32c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -g420x162 -dEPSCrop  "-sOutputFile=C:/Users/xx/AppData/Local/Temp/magick-31872WuzMb0d5c-Hz%d" "-fC:/Users/xx/AppData/Local/Temp/magick-31872cpU2RmqF-Sh6" "-fC:/Users/xx/AppData/Local/Temp/magick-31872ebXwECXOSrGl" -c showpage' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/475.
magick.exe: PostscriptDelegateFailed `The system cannot find the file specified.
' @ error/ps.c/ReadPSImage/817.
```
This problem can be fixed by install 32bit GhostScript .

### Steps to Reproduce

Run `magick test.jpg -resize 167% test.eps`.

### System Configuration

- ImageMagick version: ImageMagick 7.0.10-19 Q16 x64 2020-06-12 http://www.imagemagick.org
- Environment (Operating system, version and so on): Windows 10;  Version	10.0.18363 Build 18363

- Additional information:

**Comment by dlemstra** [comment]
It looks like ImageMagick is unable to find the location of the Ghostscript exe through the registry and then uses `gswin32c` as the default value. I just pushed a change to use `gswin64c` as the default value. 

How was Ghostscript installed and which version did you install? Maybe they changed the registry location?

**Comment by jobsken2017** [comment]
Thank you for you prompt response. 
I use [scoop](https://github.com/lukesampson/scoop) to install them. Technically, scoop unzips the setup executable and adds the gswin32c/gswin64c into `path`.
