### ISSUE TITLE
Resizing PNG increases size by 100KB

### ISSUE THREAD

**Issue by gokulmhegde** [ImageMagick/ImageMagick#2188]
ImageMagick 6.7 resize was working fine.
But the latest version of ImageMagick 6.9 and 7.0 increases the file size by 100-200KB.

**Comment by dlemstra** [comment]
Could you include an example and file that demonstrates this issue?

**Comment by fmw42** [comment]
Also your exact command line. When you resize, you create new colors. The could cause the file size to increase.
