### ISSUE TITLE
"Bold" incorrectly listed as a text style

### ISSUE THREAD

**Issue by salsaman** [ImageMagick/ImageMagick#2194]
Using version 6.9.10-23 on Linux:

$ convert -list style
incorrectly lists "Bold" as a text style, however, "Bold" is a weight value, as

$ convert -list weight
correctly shows.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow
