### ISSUE TITLE
ImageMagick 7.0.10-22 - three tests fail on Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by sstoyanov7** [ImageMagick/ImageMagick#2199]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Install commands pass, but three tests fail on `make check`

```
...
FAIL: Magick++/tests/tests.tap 10
FAIL: Magick++/demo/demos.tap 3
FAIL: Magick++/demo/demos.tap 5
...
============================================================================
Testsuite summary for ImageMagick 7.0.10
============================================================================
# TOTAL: 86
# PASS:  83
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

Makefile:11932: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/opt/ImageMagick-7.0.10'
Makefile:12038: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/opt/ImageMagick-7.0.10'
Makefile:12253: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/opt/ImageMagick-7.0.10'
Makefile:12256: recipe for target 'check' failed
make: *** [check] Error 2
```
### Steps to Reproduce

```
git clone git@github.com:ImageMagick/ImageMagick.git ImageMagick-7.0.10
cd ImageMagick-7.0.10
./configure
make
make install
sudo ldconfig /usr/local/lib
/usr/local/bin/convert logo: logo.gif # pass
make check # fail
```

### System Configuration
- ImageMagick version:ImageMagick 7.0.10-22 Q16 x86_64 2020-06-24
- Environment (Operating system, version and so on): Ubuntu 18.04.4 LTS

[test-suite.log](https://github.com/ImageMagick/ImageMagick/files/4827690/test-suite.log)

**Comment by urban-warrior** [comment]
Freetype and Ghostscript must be installed for all the unit tests to pass.  Notice in your log:

```
delegate library support not built-in '/opt/ImageMagick-7.0.10/PerlMagick/demo/Generic.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/1832
```
