### ISSUE TITLE
convert failed when reading animated WEBP

### ISSUE THREAD

**Issue by kamenik** [ImageMagick/ImageMagick#22]
Hi, 

I tried to open animated webp image with JMagick to get it's info and it failed with error:

data encoding scheme is not supported 'small_animated.webp' @ error/webp.c/ReadWEBPImage/313

it seems that cmd convert have same problem:

> convert small_animated.webp aaa.png
convert: data encoding scheme is not supported `small_animated.webp' @ error/webp.c/ReadWEBPImage/313.
convert: no images defined `aaa.png' @ error/convert.c/ConvertImageCommand/3187.

but identify can say something about it:

> identify small_animated.webp
small_animated.webp WEBP 320x240 320x240+0+0 8-bit sRGB 384KB 0.000u 0:00.000

**Comment by kamenik** [comment]
test image: http://res.cloudinary.com/demo/image/upload/fl_awebp/cell_animation.webp

**Comment by urban-warrior** [comment]
ImageMagick uses the webp delegate library to decode Webp-encoded images and its returning a "data encoding scheme not supported" exception. We'll need to investigate, it should of course be able to decode your image.

**Comment by muhammadn** [comment]
We should use WebPDemuxer before calling on WebPDecoder to unpack the data to process animated WebP files.

More info here:
https://www.jianshu.com/p/588d22e0b271

and search for VP8_STATUS_UNSUPPORTED_FEATURE

**Comment by muhammadn** [comment]
https://chromium.googlesource.com/webm/libwebp/+/0.5.0/examples/vwebp.c

Another example for demux + decoding
