### ISSUE TITLE
convert with background and transparent CMYK PDF

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#220]
I think I'm seeing a problem with a CMYK PDF that has a transparent background. When it is converted to PNG it seems the background is filled to white. I'm testing against 7.0.1-0 but I think it also affects the 6.x branch.

Testing command:

```
convert test_cmyk.pdf -background "#FF0000" -flatten out_convert_cmyk.png
convert test_rgb.pdf -background "#FF0000" -flatten out_convert_rgb.png
```

Input files:
[test_cmyk.pdf](https://github.com/ImageMagick/ImageMagick/files/314573/test_cmyk.pdf)
[test_rgb.pdf](https://github.com/ImageMagick/ImageMagick/files/314581/test_rgb.pdf)

Expected output for RGB 
![out_convert_rgb](https://cloud.githubusercontent.com/assets/1505719/16053273/fdba1a2c-325f-11e6-9c9b-bc7cf14df8d6.png)

Bad output for CMYK
![out_convert_cmyk](https://cloud.githubusercontent.com/assets/1505719/16053292/0fdaa168-3260-11e6-9363-51d82866b842.png)

i.e. the image is full white.

Testing the conversion of PDF to PNG with the GS command of `gs -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=1 -sDEVICE=pngalpha -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r50 -sOutputFile=docgs8-%d.png test_cmyk.pdf` produces the image

![docgs8-1](https://cloud.githubusercontent.com/assets/1505719/16053424/a642009c-3260-11e6-9f4d-22a2bd4e870c.png)

This image is correct ....unfortunately it's white text against a transparent background.....which confusingly in most browsers will appear just white...I'll try to update it with a better example.

**Comment by fmw42** [comment]
These work fine for me:

`convert -background "#FF0000" test_rgb.pdf -flatten testrgb.png`

and

`convert -background "#FF0000" -colorspace rgb test_cmyk.pdf -flatten testcmyk2rgb.png`

The key is to put -background before reading the pdf.

**Comment by Danack** [comment]
> and for cmyk, you need to convert to rgb first to add the background color. 

Hmm, that's seems pretty non-intuitive. How would people know that they need to do that?

The problem I'm actually trying to investigate is this one: https://stackoverflow.com/questions/37698436/cmyk-illustrator-or-pdf-file-to-png-with-transparency-has-a-white-background where the CMYK PDF doesn't get converted correctly.

I think I can produce a simpler test scenario - just converting the PDF to PNG:

```
convert test_cmyk.pdf out_convert_cmyk.png
identify out_convert_cmyk.png
```

seems to produce a 1 bit image:

> out_convert_cmyk.png PNG 628x183 628x183+0+0 8-bit Gray 2c 432B 0.000u 0:00.000

Whereas calling ghostscript directly with the command above does seem convert to png directly. This is using ghostscript 8.70

**Comment by Danack** [comment]
In an attempt to make a simpler reproduce case, here is the output of a direct ghostscript command to convert the PDF to PNG, and the equivalent convert command.

The ghostscript command produces an image with a transparent background. The convert command produces an image with a plain white background.

```
gs -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=1 -sDEVICE=pngalpha -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r50 -sOutputFile=test_cmyk_blue_gs-%d.png test_cmyk_blue.pdf

convert test_cmyk_blue.pdf test_cmyk_blue_convert.png
```

Input image:
[test_cmyk_blue.pdf](https://github.com/ImageMagick/ImageMagick/files/322350/test_cmyk_blue.pdf)

Output image from ghostscript command has a transparent background
![test_cmyk_blue_gs-1](https://cloud.githubusercontent.com/assets/1505719/16178201/b3ceb728-3639-11e6-86c4-2194f8f278af.png)

Output image from convert command has a white background
![test_cmyk_blue_convert](https://cloud.githubusercontent.com/assets/1505719/16178203/bf5b2630-3639-11e6-838b-9626b3f4cdaf.png)

(obviously on the white github page, they look quite similar.....)

**Comment by dlemstra** [comment]
@Danack With Ghostscript 9.20 and the latest ImageMagick release on Windows with the command `convert -colorspace rgb -verbose test_cmyk_blue.pdf i:\test.png` I get a transparent background. Can we close this one?

**Comment by Danack** [comment]
I guess so.
