### ISSUE TITLE
ImageMagick-be59c09-clang-x86_64.AppImage（7.0.10-22）parse dds image file flaw

### ISSUE THREAD

**Issue by hackoflpf** [ImageMagick/ImageMagick#2209]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

when i use afl to fuzz the convert func of imagemagick,i found an interestring bug, when use convert tool to parse a dds image file ,it will almost trap into inifinite loop when it trying to write to the convert file,so,this will cause the program to produce a very large file。I just debug the program and found in blob.c WriteFourCC function ,the image->rows arguments is very large ,may be program should check this argument ,it is read from the 0xc、0x10 offset of dds file。
### Steps to Reproduce

ImageMagick-be59c09-clang-x86_64.AppImage convert test0 xxx
### System Configuration

ubuntu 18.04
- ImageMagick version:7.0.10-22
[test0.zip](https://github.com/ImageMagick/ImageMagick/files/4843528/test0.zip)

- Environment (Operating system, version and so on): ubuntu 18.04
- Additional information:

**Comment by urban-warrior** [comment]
Add a security policy to prevent potential DOS.  See https://imagemagick.org/script/security-policy.php.
