### ISSUE TITLE
Uninitialized variable after reading CMYK pdf.

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#221]
While I was investigating issue number 220, I noticed some reading from unitialized memory for the code below. This was testing against 7.0.1-0

Code
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <malloc.h>
#include <wand/MagickWand.h>
    

int main(int argc,char **argv) {
    MagickWand *magick_wand;

    MagickWandGenesis();

    magick_wand = NewMagickWand();
    MagickSetImageColorspace(magick_wand, sRGBColorspace);
    MagickReadImage(magick_wand, "./images/test_cmyk.pdf");
    MagickSetImageFormat(magick_wand, "png");
    MagickWriteImage(magick_wand, "./test_cmyk.png");

    magick_wand = NewMagickWand();
    MagickReadImage(magick_wand, "./images/test_rgb.pdf");
    MagickSetImageFormat(magick_wand, "png");
    MagickWriteImage(magick_wand, "./test_rgb.png");

    MagickWandTerminus();
 
    return(0);
}
```

```
==19566== Conditional jump or move depends on uninitialised value(s)
==19566==    at 0x51EFBE2: TransformRGBImage (quantum.h:92)
==19566==    by 0x5433047: WriteOnePNGImage (png.c:8152)
==19566==    by 0x543C378: WritePNGImage (png.c:12104)
==19566==    by 0x5207346: WriteImage (constitute.c:1188)
==19566==    by 0x4ECC2A9: MagickWriteImage (magick-image.c:13172)
==19566==    by 0x400854: main (in /home/github/imagemagicktest/cmykpdf)

```

[test_cmyk.pdf](https://github.com/ImageMagick/ImageMagick/files/314985/test_cmyk.pdf)
[test_rgb.pdf](https://github.com/ImageMagick/ImageMagick/files/314988/test_rgb.pdf)

**Comment by mikayla-grace** [comment]
We cannot reproduce this problem with ImageMagick 7.0.2-1.  Valgrind completes without complaint against your test program.

**Comment by Danack** [comment]
Apologies - I should have said, this was testing against 6.9.4-10 compiled with:

```
./configure --with-quantum-depth=16 \
           --with-magick-plus-plus=no \
           --without-perl \
           --disable-static \
           --exec-prefix=/usr/sbin \
           --disable-docs \
           --disable-openmp 

```

**Comment by mikayla-grace** [comment]
We should have mentioned we can't reproduce it with 6.9.4-10 either.  Valgrind completes without complaint against your test program.  We tested with Valgrind 3.11 and gcc 5.3.1.

**Comment by Danack** [comment]
Okay - what I'll try to do is create a vagrant box to test the issue, so that it's completely reproducible.

**Comment by dlemstra** [comment]
Have you been able to create a vagrant box @Danack?

**Comment by Danack** [comment]
Sorry - I just don't have time to spend doing this. I close the issue and if I can ever get a reproducible environment will let you know.
