### ISSUE TITLE
Incorrect results from "magick convert *.tif *.gray"

### ISSUE THREAD

**Issue by Andidy** [ImageMagick/ImageMagick#2221]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When executing the following command: "magick convert filename.tif filename.gray" on a 16-bit grayscale file, the resulting output has incorrect values.

### Steps to Reproduce
- Download ImageMagick-7.0.10-22-Q16-HDRI-x64-dll.exe from imagemagick.org Windows binary downloads page
- Use default installation settings
- Get file 15-K.tif from: http://viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org15.htm and extract the image from the zip file. Edit: To clarify the file in question can be downloaded by clicking the square on the map which contains India and the Himalaya mountains, hovering over the square should have a small tooltip appear saying "15-K"
- Open the file in a image viewer that supports .tif and notice that its very dark grays / almost black everywhere except for a few spots where its white

Version A:
(I believe its also obvious there is a bug just by doing the following)
- Run "magick convert 15-K.tif new.tif"
- Compare the new tif file to the original it will be a medium gray instead of almost black

Version B:
(I include this for completeness as this is my actual use case the bug is hampering)
- Run "magick convert 15-K.tif 15-K.gray"
- Compile the following small C code (I've used MSVC compiler): https://gist.github.com/Andidy/888fd7aa19a3b528cb0ae8e49477bd88
- run the executable with the 15-K.gray file in the same directory as the executable
- Note the wrong values (-32768, 32767)
- Go back to the small C code and uncomment the two lines that say "Uncomment to get correct values"
- Note the correct values (-160, 8703)
(It's not an error with my C code, I've had someone else create a similar code in C++ with the same .tif file and they get the same issue with this version, and for the record this bug doesn't appear in version 7.0.8-65 Q16 x64 version of Imagemagick)

### System Configuration
- ImageMagick version:
I've tested the prepackaged binaries: ImageMagick-7.0.10-22-Q16-HDRI-x64-dll.exe and ImageMagick-7.0.10-22-Q16-x64-static.exe found on imagemagick.org
- Environment (Operating system, version and so on): Windows 10 64-bit

**Comment by fmw42** [comment]
This may not make any difference, but in IM 7, use magick, not magick convert.  Also can you post your 15-K.tif file for the developers to use to check and test.

**Comment by Andidy** [comment]
> This may not make any difference, but in IM 7, use magick, not magick convert. Also can you post your 15-K.tif file for the developers to use to check and test.

I have tested that as well, the issue persists at minimum with the "Version A"
I already provide a link to where the image file can be downloaded in the gist and the issue itself, it is a fairly large file (around 250mb uncompressed) and its not my data / work to distribute.

**Comment by snibgo** [comment]
I downloaded 15-K.zip, and unzipped it making 15-K.tif.

With IM v7.0.8-64, your "Version A" test works fine for me. 15-K.tif and new.tif look the same in Microsoft Photo Viewer, and have the same mean and standard deviation. IM "compare" says they are identical.

This doesn't exclude a bug in later versions of IM, of course.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by snibgo** [comment]
I will add: On the other hand, I suppose 15-K.tif is a Ditigal Elevation Model (DEM) and the values should be interpreted as signed integers, being the height in meters or feet or something above (positive) or below (negative) some standard geoid.

And this fact might be encoded as metadata which my 7.0.8-64 ignores, but later versions use, so the resulting image is close to middle gray. Try "-auto-level" to see that the Himalayas are lighter (higher) than most of India.

To get the "gray" version of the image, using 7.0.8-64:
```
magick 15-K.tif -evaluate AddModulus 50% -auto-level x2.tif
```

**Comment by fmw42** [comment]
Perhaps use  -define quantum:format=signed. See https://imagemagick.org/script/defines.php

**Comment by Andidy** [comment]
> I will add: On the other hand, I suppose 15-K.tif is a Ditigal Elevation Model (DEM) and the values should be interpreted as signed integers, being the height in meters or feet or something above (positive) or below (negative) some standard geoid.
> 
> And this fact might be encoded as metadata which my 7.0.8-64 ignores, but later versions use, so the resulting image is close to middle gray. Try "-auto-level" to see that the Himalayas are lighter (higher) than most of India.
> 
> To get the "gray" version of the image, using 7.0.8-64:
> 
> ```
> magick 15-K.tif -evaluate AddModulus 50% -auto-level x2.tif
> ```

7.0.8 seems to not have this issue, the person who tested the c++ version of my code snippet was not having this issue that I am reporting. And auto-level is not a valid solution because I will be using the data of the whole world from that site, but auto level will cause the data to be incorrect once combined (as smaller elevations in other regions will match Himalayas in height), I probably should have also mentioned that 4 error messages about unidentified tags appear when doing the conversion with 7.0.10 so perhaps this is the issue (I will record the exact messages in a second comment shortly.



> Perhaps use -define quantum:format=signed. See https://imagemagick.org/script/defines.php

I have tried both defining quantum:format=signed and quantum:format=unsigned this had no impact on the output image

**Comment by Andidy** [comment]
convert: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1044.                                             convert: Unknown field with tag 33922 (0x8482) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1044.                                             convert: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1044.                                             convert: Unknown field with tag 34737 (0x87b1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1044.

Here is the list of errors when converting the one of the tif files from the link in the original issue post.

**Comment by fmw42** [comment]
Those are not errors. They are warnings that ImageMagick does not know about meta tag fields in the tiff file that are not standard information. Tiff is customizable and people put all kinds of information in the meta tags.  Use -quiet in your command line right after convert to suppress those warnings.

**Comment by Andidy** [comment]
It seems urban warrior may have addressed this with the commit they made. I will test and report if its solved my issue.

**Comment by urban-warrior** [comment]
ImageMagick introduces a bias to push the signed results into the unsigned range.  To restore the signed values, simply subtract 1/2 interval as follows:

```
$ magick 15-K.tif -evaluate subtract 50% x2.miff
$ identify -verbose x2.miff | grep -e min -e max -e mean
      min: -159.998  (-0.00244141)
      max: 8703.87 (0.132812)
      mean: 863.606 (0.0131778)
```

We could exempt HDRI-enabled ImageMagick from the bias, but non-HDRI requires positive values and therefore bias.

**Comment by snibgo** [comment]
```
Andidy:> And auto-level is not a valid solution because ...
```
Yes. My suggestion of "-auto-level" was only so we could clearly see the image, including river valleys darker than surrounding hills.

```
urban-warrior:> ImageMagick introduces a bias to push the signed results into the unsigned range.
```
I hope it doesn't do this for all tif files, but only those that have whatever metadata means "signed integers".

If it does this for all tif files, then existing scripts will break.

**Comment by urban-warrior** [comment]
Bias is only required for signed TIFF.  15-K returns:

```
Sample Format: signed integer
```

**Comment by Andidy** [comment]
I have tried the suggested command with subtracting 50% of the value and this appears to do what I want. Thank you for everyone's time.
