### ISSUE TITLE
Erroneous convolution in vertical direction in IM 7.0.10.22

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#2224]
I believe I have found an issue with -morphology convolve for 1D vertical convolutions in IM 7.0.10.22 Q16 HDRI Mac OSX Sierra. The 1D convolution in the horizontal direction seems fine.

**horizontal convolution -- seems correct**
`magick rose: -morphology convolve "3x1:-0.5,0,0.5" -evaluate add 50% tx.png`

![tx](https://user-images.githubusercontent.com/13458218/86290559-7c233680-bba2-11ea-8f94-ae484b6f1fd1.png)

**vertical convolution -- seems wrong**
`magick rose: -morphology convolve "1x3:-0.5,0,0.5" -evaluate add 50% ty1.png`

![ty1](https://user-images.githubusercontent.com/13458218/86290605-8f360680-bba2-11ea-8bfa-48b1c7783ab3.png)

**make vertical convolution by rotating -90, do horizontal convolution, rotate +90 -- seems correct**
`magick rose: -rotate -90 -morphology convolve "3x1:-0.5,0,0.5" -rotate 90 -evaluate add 50% ty2.png`

![ty2](https://user-images.githubusercontent.com/13458218/86290668-affe5c00-bba2-11ea-882e-4ef7c1320ca2.png)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
