### ISSUE TITLE
Interlacing not working - identify reporting strange results

### ISSUE THREAD

**Issue by internationils** [ImageMagick/ImageMagick#2228]
Hello, Interlacing does not seem to be working. I want to interlace a JPG (website optimization), but neither the options JPEG, Line or Plane do anything with `mogrify`. And yes, the file is written and changed by the command.
Strangely. `identify` takes interlace as an argument and reports its argument as output ...
It appears to work with `convert` ...
It also works with `mogrify` if the filename is given at the **end** of the arguments instead of the beginning.

I would consider the `mogrify` and `identify` behaviors bugs.

```
$ identify -verbose test.jpg |grep Interlace
  Interlace: None
$ mogrify test.jpg -interlace Line -sampling-factor 4:2:0 -strip -quality 85% -colorspace sRGB
$ identify -verbose test.jpg |grep Interlace
  Interlace: None

$ identify -interlace Line -verbose test.jpg |grep Interlace
  Interlace: Line
$ identify -interlace Plane -verbose test.jpg |grep Interlace
  Interlace: Plane

$ convert test.jpg -interlace Line -sampling-factor 4:2:0 -strip -quality 85% -colorspace sRGB test_conv.jpg
$ identify -verbose test_conv.jpg |grep Interlace
  Interlace: JPEG

$ mogrify -interlace Line -sampling-factor 4:2:0 -strip -quality 85% -colorspace sRGB test.jpg
$ identify -verbose test.jpg |grep Interlace
  Interlace: JPEG
```

**Comment by fmw42** [comment]
I am not sure JPEG supports interlace line.  I think only, JPEG and progressive JPG. Nevertheless, change your command line to put -strip first after reading your input. Also quality does not use % symbol. Also try using convert first.

`convert test.jpg -strip -colorspace sRGB -sampling-factor 4:2:0 -quality 85 -interlace Line result.jpg`

I get:

` Interlace: JPEG`

as opposed to the input which has

`Interlace: None`

**Comment by internationils** [comment]
Yes, mine turns is into `Interlace: JPEG` as well (when specifying `Line`). Why should `strip` be first?
The main bug here to me is that where you put the filename in `mogrify` affects the result. I can understand the modification options being applied in order and thus being significant, but not the filename.

**Comment by fmw42** [comment]
Mogrify was designed to process all files in a folder. So typically one does not put an actual filename as it gets it from each image it process and uses the same name for the output. It is also an older and more restrictive tool than convert / magick. The strip comes first to remove meta data. Then you set new meta data after than with your other commands / settings.
