### ISSUE TITLE
make install fails with """ln: failed to create symbolic link """

### ISSUE THREAD

**Issue by RedactedCode** [ImageMagick/ImageMagick#2234]
### Description
Building ImageMagick 7.0.10 on Puppy Linux XenialPup 7.5, 64-bit

**make install** fails

```
./configure --with-modules --with-perl
```
runs OK.

```
make install
```

runs OK until (fragment):

>cp -f MagickCore/ImageMagick.pc MagickCore/ImageMagick-7.Q16HDRI.pc
cp -f MagickCore/MagickCore.pc MagickCore/MagickCore-7.Q16HDRI.pc
cd . && /bin/sh ./config.status MagickWand/MagickWand.pc
config.status: creating MagickWand/MagickWand.pc
cp -f MagickWand/MagickWand.pc MagickWand/MagickWand-7.Q16HDRI.pc
cd . && /bin/sh ./config.status Magick++/lib/Magick++.pc
config.status: creating Magick++/lib/Magick++.pc
cp -f Magick++/lib/Magick++.pc Magick++/lib/Magick++-7.Q16HDRI.pc
cd . && /bin/sh ./config.status PerlMagick/quantum/quantum.xs
config.status: creating PerlMagick/quantum/quantum.xs
  GEN      PerlMagick/quantum/Q16HDRI.xs
ln: failed to create symbolic link 'PerlMagick/quantum/Q16HDRI.xs': File exists
Makefile:13388: recipe for target 'PerlMagick/quantum/Q16HDRI.xs' failed
make[1]: *** [PerlMagick/quantum/Q16HDRI.xs] Error 1
make[1]: Leaving directory '/initrd/mnt/dev_save/data/src/ImageMagick-master'
Makefile:12313: recipe for target 'install' failed
make: *** [install] Error 2

### Steps to Reproduce
Download latest .zip from ImageMagick 7 Github repo.
Unpack.
Configure
Make
Make install

### System Configuration
Puppy Linux XenialPup 7.5, 64-bit
Dell Inspiron 1545, 4GB
ImageMagick 7 : ImageMagic-master from github download

I've compiled all sorts of versions of IM for years now without ever running into this kind of problem!

**Comment by urban-warrior** [comment]
Unfortunately, we cannot reproduce the problem.  ImageMagick builds and install without complaint.   Try `make distclean;make install`.   Otherwise, try `rm PerlMagick/quantum/Q16HDRI.xs;make install`.  If that fails, try `./configure --without-perl;make install`.

**Comment by RedactedCode** [comment]
OK thanks.


I had tried deleting the .xs files, it failed out again with a different error so I went to bed.


I haven't tried to bottom this further.

 I reverted to 7.0.9-10 from a tar.gz dated 22nd December 2019, and it compiled first time without error.

Some weirdness at my end I guess, sorry
