### ISSUE TITLE
Converting specific resolutions from ico files is broken

### ISSUE THREAD

**Issue by Pulfer** [ImageMagick/ImageMagick#224]
After 6.9.3-7 -> 6.9.4-7 update converting specific resolutions from ico files no longer works.

$convert 'oic_winlogo.ico[8]' wine.png
convert: unable to open image `oic_winlogo.ico[8]': No such file or directory @ error/blob.c/OpenBlob/2705.
convert: no images defined `wine.png' @ error/convert.c/ConvertImageCommand/3257.

$ identify oic_winlogo.ico 
oic_winlogo.ico[0] ICO 48x48 48x48+0+0 8-bit sRGB 25.2KB 0.000u 0:00.000
oic_winlogo.ico[1] ICO 48x48 48x48+0+0 4-bit sRGB 25.2KB 0.000u 0:00.009
oic_winlogo.ico[2] ICO 32x32 32x32+0+0 8-bit sRGB 25.2KB 0.000u 0:00.009
oic_winlogo.ico[3] ICO 32x32 32x32+0+0 4-bit sRGB 25.2KB 0.000u 0:00.009
oic_winlogo.ico[4] ICO 16x16 16x16+0+0 8-bit sRGB 25.2KB 0.000u 0:00.009
oic_winlogo.ico[5] ICO 16x16 16x16+0+0 4-bit sRGB 25.2KB 0.000u 0:00.009
oic_winlogo.ico[6] ICO 48x48 48x48+0+0 32-bit sRGB 25.2KB 0.000u 0:00.009
oic_winlogo.ico[7] ICO 32x32 32x32+0+0 32-bit sRGB 25.2KB 0.000u 0:00.009
oic_winlogo.ico[8] ICO 16x16 16x16+0+0 32-bit sRGB 25.2KB 0.000u 0:00.009

**Comment by mikayla-grace** [comment]
You have identified a transient bug resulting from our efforts to make ImageMagick more secure.  The current release of ImageMagick works as expected, 'oic_winlogo.ico[8]' returns the 9th image from the ICO file.

**Comment by Pulfer** [comment]
Indeed, updating to 6.9.4-9 fixed the issue.
