### ISSUE TITLE
CloneRepositories.cmd Missing?

### ISSUE THREAD

**Issue by Enigma0** [ImageMagick/ImageMagick#2242]
Trying to compile ImageMagick++ for windows but some of the steps in `install-windows.txt` don't appear to be actionable:

> Clone the dependencies
> 
> The ImageMagick library is build with a number of third party libraries. Run
> **CloneRepositories.cmd** to clone these libraries and the ImageMagick library.
> 
> **Build configure.exe**

^ Not sure where/how to build configure.exe either...

**Comment by dlemstra** [comment]
You will need to use this project: https://github.com/ImageMagick/ImageMagick-Windows

**Comment by Enigma0** [comment]
Readme in main project should probably be updated to reflect that you need a different project to build for windows.

**Comment by dlemstra** [comment]
Feel free to oprn up a PR to make this more clear in the documentation.
