### ISSUE TITLE
HEIC file tinted pink when using "-profile"

### ISSUE THREAD

**Issue by ikerr** [ImageMagick/ImageMagick#2245]
### Prerequisites

- [ x] I have written a descriptive issue title
- [ x] I have verified that I am using the latest version of ImageMagick
- [ x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Converting an HEIC file with an embedded color profile and using the "-profile" option produces highly incorrect colors in the output image. Is it the case that although ImageMagick reports that there is an embedded ICC profile, it is not used by the current HEIC loader?

### Steps to Reproduce

```
convert sample.heic -profile AdobeRGB1998.icc out.jpg
```

Note that `identify -format "%[profiles]" sample.heic` reports an exif and icc profile: `exif,icc`.

[sample.heic.zip](https://github.com/ImageMagick/ImageMagick/files/4887412/sample.heic.zip)

### System Configuration

- ImageMagick version: ImageMagick 7.0.10-23 Q16 x86_64 2020-07-05
- Environment (Operating system, version and so on): macOS 10.13.6
- Additional information:

**Comment by urban-warrior** [comment]
You need two profiles, one for the source colorspace and one for the destination. The source colorspace is YCbCr.  Or try this command instead:

```
magick sample.heic -colorspace sRGB -profile AdobeRGB1998.icc out.jpg
```

**Comment by ikerr** [comment]
> You need two profiles, one for the source colorspace and one for the destination. The source colorspace is YCbCr. Or try this command instead:
> 
> ```
> magick sample.heic -colorspace sRGB -profile AdobeRGB1998.icc out.jpg
> ```

My understanding is that if the original image has an embedded color profile, I should not need to specify the source profile. Is that not the case?

**Comment by dlemstra** [comment]
The issue here is that you need to change the colorspace to `sRGB` first because the color profile is not `YCbCr`. Then with the color conversion the image is converted from the `Dispaly P3` profile to `AdobeRGB1998`.
