### ISSUE TITLE
PSD to PNG image taking very long time when Colour space RGB

### ISSUE THREAD

**Issue by bharatsoftpro** [ImageMagick/ImageMagick#2246]
When we are trying to convert .psd image to png we are getting a very long time. 
**Detail of PSD**
-Image disk size: 48.3 MB
-Dimensions: 1300 × 1152
-No of Layer: Layer 41 copy, Layer 45 copy, Layer 43 copy, Layer 47 copy, Layer 37 copy, headlight_reflection, headlight_reflection2, headlight_reflection4, ptc-master-KO_GR, LIGHTEXTURE_3, shadow copy 3, and 13 more
Colour space: RGB instead of CMYK
**Image Magic Version**: 6.7.7.10-6
**OS**: ubuntu 3.13
**Note**: If we change Colour space RGB to CMYK than this is taking very less time.

**Comment by urban-warrior** [comment]
ImageMagick 6.7.7-10 is way old.  Try a modern release of ImageMagick such as 7.0.10-23, the latest release.  If you continue to have performance issues, post your command here along with a link to a sample image so we can reproduce the issue.
