### ISSUE TITLE
strokeLineCap not work with strokePattern

### ISSUE THREAD

**Issue by ondratu** [ImageMagick/ImageMagick#225]
Hi,

I try to draw fat line in python, with width 50px for example. And when i use strokeColor, all, works fine. But when I use strokePatern, graphics magick use RoundCap instead of ButtCap. Not only by defalut, but allways.

This bug is in GraphicsMagick too.

**Comment by mikayla-grace** [comment]
You have not provided any information on how to reproduce the problem.  We tried the following command with ImageMagick 6.9.4-9 and it returns expected results:

```convert -size 256x256 xc:white -quality 100 -depth 24 -stroke rose: -draw "stroke-width 10 stroke-linecap butt line 100,50 200,50" line.jpg```

**Comment by ondratu** [comment]
There is a few problems what a see.

First problematics code:

```python
from PythonMagick import Image, Geometry, DrawableLine


src_img = Image(Geometry(256, 256), "white")
dst_img = Image(Geometry(256, 256), "black")

dst_img.strokeWidth(10)

dst_img.strokePattern(src_img)
dst_img.draw(DrawableLine(20, 20, 240, 240))

# this line is not red, and have not default ButtCap
dst_img.strokeColor("red")
dst_img.draw(DrawableLine(20, 240, 240, 20))

dst_img.display()
```

What i see, i could fix that by ordering:
```python
from PythonMagick import Image, Geometry, DrawableLine


src_img = Image(Geometry(256, 256), "white")
dst_img = Image(Geometry(256, 256), "black")

dst_img.strokeWidth(10)

dst_img.strokeColor("red")
dst_img.draw(DrawableLine(20, 240, 240, 20))

dst_img.strokePattern(src_img)
dst_img.draw(DrawableLine(20, 20, 240, 240))

dst_img.display()
```

In python wrapper i can't set LineCap, but when i try to use GraphicsMagick, when I can, that have no effect. I may try it in C++
