### ISSUE TITLE
convert with rgb psd with alpha or transparency

### ISSUE THREAD

**Issue by sfunm** [ImageMagick/ImageMagick#226]
I think there is a problem with rgb Photoshop (psd) Files that contain alphachannel or transparency.

When I convert the image the alpha/transparency is rendered as 1 bit instead of full range 256 bit transparency.

Alpha:
![comparison_alpha](https://cloud.githubusercontent.com/assets/20112037/16307912/4be8218a-3963-11e6-90df-9d03033d7788.png)

Transparency:
![comparison_trans](https://cloud.githubusercontent.com/assets/20112037/16307928/5c974f92-3963-11e6-939e-10233cf1b1b8.png)

```
convert psd_alpha_rgb.psd test.jpg
convert psd_trans_rgb.psd test.jpg
```

Problem exists with 7.0.2-0 and 6.9.4-9, worked in 6.8.9-9 Q16 x86_64

Source Files:
https://www.dropbox.com/s/9n6e6g8s8nokl5q/alpha.zip?dl=0
https://www.dropbox.com/s/gm3g1duj5nhyj4p/trans.zip?dl=0

**Comment by dlemstra** [comment]
We fixed an issue a while ago. Photoshop seems to blend semi-transparent pixels with white. We resolved this but added a new option to allow the old behavior. When you convert the images with this option enabled you will get the result that you want:

```
convert -define psd:alpha-unblend=off psd_alpha_rgb.psd[0] test.jpg
convert -define psd:alpha-unblend=off psd_trans_rgb.psd[0] test.jpg
```

**Comment by Danack** [comment]
> We resolved this but added a new option to allow the old behavior.

Hi @dlemstra - is this option available through the MagickWand C API ?

cheers
Dan

**Comment by dlemstra** [comment]
You can use `MagickSetOption(wand,"psd:alpha-unblend","off")` to set this option.
