### ISSUE TITLE
Can we save all the attachments in outlook mail as jpeg using imagemagick ?

### ISSUE THREAD

**Issue by abha3011** [ImageMagick/ImageMagick#2263]
Hello, 

Can you please let me know if we can save all the attachments present in any outlook mail as an image using imagemagick? Is so, how can we do that ?

Regards,
Abha

**Comment by urban-warrior** [comment]
You can use ImageMagick to convert any attachment in a format understood by ImageMagick to another format, e.g. a PDF to PNG.

**Comment by abha3011** [comment]
Thanks!  But, I mean I have to convert the whole outlook mail  with attachments into a image. Outlook mail is in .msg format. So can we convert .msg format into a image using imagemagick, where in the atachments are included too?
