### ISSUE TITLE
Semi-transparent stroke linecaps appear mirrored using stroke-linecap round

### ISSUE THREAD

**Issue by MarkMurphy** [ImageMagick/ImageMagick#227]
Notice the use of a semi-transparent color `#0004` and `stroke-linecap round`:

```
convert -size 200x200 xc:white -draw 'stroke "#0004" \
stroke-width 20 stroke-linecap round polyline 100,50 100,150' line.png
```

![line](https://cloud.githubusercontent.com/assets/873474/16339070/021b60b4-39f7-11e6-8f5e-ce5bacd708c5.png)

With this you can see there are some unexpected (darker) semi-circles overlaid at each end of the line.

**Comment by MarkMurphy** [comment]
I'm guessing that ImageMagick is just adding circles to the end of the line to use as the line caps, which causes the darker areas when overlapping with the line stroke.

**Comment by mikayla-grace** [comment]
Correct.  The draw.c/DrawRoundLinecap() method is drawing a full circle.  It was likely a lazy implementation to avoid the complexity of drawing a semi-circle at the required angle.  If a graphics wizards want to contribute a proper round linecap implementation, post it here.  Otherwise, the implementation will likely remain as is.

**Comment by MarkMurphy** [comment]
It doesn't look like it, but is it possible for the draw.c/DrawRoundLinecap() method to gain access to the last two points drawn? If so, it should be possible to calculate an angle.

basically: 

if no points have been drawn, don't do anything.
else if there's only one point, just draw a circle around that point
else if we have access to the last two points, we can calculate the angle and draw an open ellipse using the the angle.

**Comment by MarkMurphy** [comment]
**An interesting note** 

I've discovered that if you add/combine `stroke-linejoin round` with `stroke-linecap round`, the end caps appear as expected.

```
convert -size 200x200 xc:white -draw 'stroke "#0004" \
stroke-width 20 stroke-linecap round stroke-linejoin round polyline 100,50 100,150' \
linecap-round.png
```

![linecap-round](https://cloud.githubusercontent.com/assets/873474/16587360/af6463c2-42a0-11e6-84e0-62a3ad4e9f5c.png)

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by mikayla-grace** [comment]
To comply with the SVG standard, you'll need to use ```stroke-opacity``` rather than a stroke of ```#0004```.  You also need the latest beta available tomorrow.

```convert -size 200x200 xc:white -draw 'stroke-opacity 0.75 stroke "#000" \
stroke-width 20 stroke-linecap round stroke-linejoin round polyline 100,50 100,150' \
linecap-round.png```

**Comment by MarkMurphy** [comment]
So this issue looks good, closing it. However @mikayla-grace, `stroke-opacity` only appears to work when it's provided after `stroke` and not before like you have in your example. #229
