### ISSUE TITLE
Problem usimg IM to access my security camera

### ISSUE THREAD

**Issue by acb764se** [ImageMagick/ImageMagick#2273]
### Prerequisites

- [X ] I have written a descriptive issue title
- [ X] I have verified that I am using the latest version of ImageMagick
- [ X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hi, I have a software for monitoring my own security cameras, checking changes in pictures etc. etc. It worked perfectly well all last summer. This summer I can't get one of my pictures. Forgetting my code for a test, here is what happens using the IM line commands:

homeSys:~> identify "http://admin:admin@192.168.1.33/tmpfs/snap.jpg"
http://admin:admin@192.168.1.33/tmpfs/snap.jpg=>snap.jpg PS 612x792 612x792+0+0 16-bit sRGB 6114B 0.016u 0:00.012

But the picture is NOT 612x792, is 704x576 (see attachment, got from Firefox from exactly the same adress). Also, the 612x792 picture looks completely blank.

homeSys:~> convert "http://admin:admin@192.168.1.33/tmpfs/snap.jpg" Temp/snap.gif

I try to attach also that, it is only 6Kb, don't know if its binary structure will be preserved.
Thank you in advance for any hints.

![snap](https://user-images.githubusercontent.com/68337000/87557125-d13d6d00-c6b7-11ea-92b3-f543c80b6c29.gif)

### Steps to Reproduce
![snap](https://user-images.githubusercontent.com/68337000/87555660-0c3ea100-c6b6-11ea-9cbd-78813a99646f.jpg)

### System Configuration

- ImageMagick version: ImageMagick 6.9.10-11 Q16 i686 2020-06-25 https://www.imagemagick.org
- Environment (Operating system, version and so on): cygwin on Windows 7
- Additional information:

**Comment by urban-warrior** [comment]
Your source image is Postscript, notice the PS in the identify line.  If you identify the JPEG image, it reports JPEG as the image type.  Your camera script is likely not passing the JPEG security image to the `identify` command.

**Comment by acb764se** [comment]
Thanks for your comment, but the hardware and software in my camera, as opposed to the software in IM (and possibly in delegates) is guaranteed to be exactly the same as last year, and I know that it sends a .jpg file. 

If it sent a Postscript file instead (by some sort of miracle, no IP cameras to my knowledge do that) Firefox would not display it, but would open Acrobat Reader, or offer me to save the PS file on disk. 

My question is, what change in IM software (or possibly "delegates" ) may fool IM into thinking that it has to do with a PS file, like you correctly saw; and, now that you saw this, I realize that 612x792 is a "Letter" page format at 72 dpi, but my computer is Letter-free, only A4 on it :-). 

Something is lying to IM, but what? 

Anybody knows the mechanic behind the scenes, or where is the documentation describing it? Which piece of code, IM or not, analyzes the buffer coming back from the URL?

Thanks!

**Comment by snibgo** [comment]
> http://admin:admin@192.168.1.33/tmpfs/snap.jpg=>snap.jpg PS 612x792 612x792+0+0 16-bit sRGB 6114B 0.016u 0:00.012

That file, snap.jpg, seems to be a PS (Postscript) file. Please paste a link to it.

**Comment by acb764se** [comment]
Here is the file:
https://www.dropbox.com/s/nn4m34pglfcjq8r/snap.jpg?dl=0

I hope it is visible, sometimes Dropbox is not straightforward to use.
Thanks again.

**Comment by snibgo** [comment]
According to v6.9.9-50 and v7.0.8-64 of IM, that file is a JPEG:
```
f:\web\im>%IM%identify snap.jpg
snap.jpg JPEG 704x576 704x576+0+0 8-bit sRGB 255033B 0.000u 0:00.000

f:\web\im>%IMG7%magick snap.jpg info:
snap.jpg JPEG 704x576 704x576+0+0 8-bit sRGB 255033B 0.031u 0:00.033
```
What version of IM are you using?
