### ISSUE TITLE
IM 7 -composite not maintaining color

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#2279]
Using IM 6.9.11.23 and IM 7 up to around IM 7.0.8.23 a composite of a color image over a grayscale image produced a color output. But sometime after 7.0.8.23, the result became grayscale. One of my clients complained about one of my scripts with this regard.  Here is a simple example.

Background (grayscale) image:

![promobg_P133](https://user-images.githubusercontent.com/13458218/87720026-25ecf080-c769-11ea-8204-e59afadbe950.png)

Overlay (color) image:

![preview_page_1](https://user-images.githubusercontent.com/13458218/87720061-356c3980-c769-11ea-8360-724d5487ffff.png)

The following works fine for IM 6.9.11.23 -- overlay shows in color in the result:

convert promobg_P133.png \( preview_page_1.png -resize 324x360 \) -geometry +325+190 -compose over -composite test6.png

![test6](https://user-images.githubusercontent.com/13458218/87720175-6187ba80-c769-11ea-8708-9fa1825b80f9.png)

The following works fine for IM 7.0.8.23 -- overlay shows in color in the result:

im70823 magick promobg_P133.png \( preview_page_1.png -resize 324x360 \) -geometry +325+190 -compose over -composite test70823.png

![test70823](https://user-images.githubusercontent.com/13458218/87720197-69475f00-c769-11ea-9454-3cb913dd6044.png)

But the following fails for IM 7.0.10.23 -- overlay shows as gray in the result:

im7 magick promobg_P133.png \( preview_page_1.png -resize 324x360 \) -geometry +325+190 -compose over -composite test7.png

![test7](https://user-images.githubusercontent.com/13458218/87720357-a9a6dd00-c769-11ea-95fc-e0d99266b3bf.png)

*As a workaround, I can add -colorspace sRGB and that will fix it.*

**But I think, it should work the same in IM 7 as in IM 6. If either background or overlay is color, the output should be color.**

**Comment by urban-warrior** [comment]
See https://imagemagick.org/script/porting.php:

### Grayscale
Grayscale images consume one pixel channel in ImageMagick version 7. To process RGB, set the colorspace to RGB (e.g. -colorspace sRGB).

**Comment by fmw42** [comment]
As I noted above, I have done that as a workaround.  But I think IM 7 has changed since previous versions where it worked like IM 6 in regard to compositing, then suddenly changed. Is it not possible to test the two images and make the output color if at least one of the two images is color, like was done in IM 6?

**Comment by dlemstra** [comment]
I think we should not "upgrade" the input from a grayscale image to a sRGB image. The user should control this and decide wether the image should be changed from grayscale to sRGB.

**Comment by fmw42** [comment]
Dirk, it is not a single image that is in question. It only occurs when you have a grayscale background and a color overlay. The result current in the composite shows the overlay part of the image as grayscale. It used to show it in color.  My thoughts are that if either of the two images are color, the result should be color -- just like it does in IM 6 and in older versions of IM 7.

But if you an Magick still want the behavior to differ between the two version, I will keep my -colorspace sRGB patch in my script.

**Comment by snibgo** [comment]
"-colorspace sRGB" is not a great solution, because the inputs may actually be linear, not sRGB.

For a better solution, I suggest a new operation, perhaps called "-deGray". For inputs that are gray, or gray+alpha, this expands the gray channel to three channels (R, G and B). For other inputs, it does nothing.

**Comment by t246246** [comment]
snibgo, can we use -type TrueColor or -type TrueColorAlpha in this case? 

https://www.imagemagick.org/discourse-server/viewtopic.php?p=167184#p167184

**Comment by fmw42** [comment]
If you want to ensure a PNG is color use PNG24:output.png

**Comment by t246246** [comment]
That's only applicable for PNG.  I think it is more general solution to use -type if it works.
However, if one can use -type, users need to know the input has alpha or not.
I think that's why snibgo suggests new general operator.

**Comment by fmw42** [comment]
-type does not work for PNG. See https://imagemagick.org/Usage/formats/#png_formats and https://imagemagick.org/Usage/formats/#png_write
