### ISSUE TITLE
stroke-opacity works only when it's specified after stroke

### ISSUE THREAD

**Issue by MarkMurphy** [ImageMagick/ImageMagick#229]
```
convert -size 200x200 xc:white \
-draw 'stroke-opacity 0.75 stroke "#000" stroke-width 20 stroke-linecap round \
polyline 100,50 100,150' line.png
```

![linecap-round](https://cloud.githubusercontent.com/assets/873474/16809861/329bde84-48f8-11e6-85d5-622ade145d4f.png)

**VS.**

```
convert -size 200x200 xc:white \
-draw 'stroke "#000" stroke-opacity 0.75 stroke-width 20 stroke-linecap round \
polyline 100,50 100,150' line.png

```
![linecap-round](https://cloud.githubusercontent.com/assets/873474/16809892/475ec32c-48f8-11e6-9ab7-764009b2678e.png)

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Can we close this issue @MarkMurphy ?

**Comment by MarkMurphy** [comment]
Yes, thanks
