### ISSUE TITLE
avif encoding broken

### ISSUE THREAD

**Issue by jayjay88282** [ImageMagick/ImageMagick#2291]
I think the newly supported avif codec through libheif has some uninitialised variables in Magick++ when trying to encode a file?

imagmagick 7.0.10-23
libheif 1.7.0
linux x64

1) Outputting a file with Magick::Image::magick() set to avif gives "Magick: Unrecognized image format (avif)"
2) Then doing it again in the same process using heic as magick throws an error "Success `' @ error/heic.c/IsHeifSuccess/136"
3) Then finally using avif again as magick gives no error and the outputted file is successfully avif.

So it seems like there is something uninitialised which gets initiliased trying to encode to heic-format.

**Comment by dlemstra** [comment]
It appears there was a format missing in our configuration. This will be added in the next release.

**Comment by jayjay88282** [comment]
Thanks. Quick response :)
