### ISSUE TITLE
NOT converting image from RGB colorspace to CMYK colorspace

### ISSUE THREAD

**Issue by kavirajk** [ImageMagick/ImageMagick#23]
I have tried using Image magic command line tool ```convert``` to convert RGB image to CYMK(USWebCoatedSWOP). After conversion I checked colorspace using ```identify``` command and the converted image is in sRGB colorspace rather than cmyk.

For some pics its converting RGB to CMYK but for some its not.

following are the commands I used.

![screenshot from 2015-08-31 15 04 49](https://cloud.githubusercontent.com/assets/3735252/9576045/e6358cc0-4ff1-11e5-8b72-2125dfe4f935.png)

### Here is the output of ```identify -verbose``` of rgb1.jpg

Image: rgb1.jpg
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Class: DirectClass
  Geometry: 640x640+0+0
  Resolution: 72x72
  Print size: 8.88889x8.88889
  Units: Undefined
  Type: TrueColor
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
  Channel statistics:
    Red:
      min: 0 (0)
      max: 255 (1)
      mean: 132.239 (0.518585)
      standard deviation: 103.639 (0.406427)
      kurtosis: -1.77176
      skewness: -0.0211258
    Green:
      min: 0 (0)
      max: 255 (1)
      mean: 122.578 (0.480698)
      standard deviation: 99.9724 (0.392049)
      kurtosis: -1.67385
      skewness: 0.210063
    Blue:
      min: 0 (0)
      max: 255 (1)
      mean: 118.942 (0.46644)
      standard deviation: 97.9736 (0.38421)
      kurtosis: -1.59551
      skewness: 0.340405
  Image statistics:
    Overall:
      min: 0 (0)
      max: 255 (1)
      mean: 124.586 (0.488574)
      standard deviation: 100.556 (0.394336)
      kurtosis: -1.69656
      skewness: 0.17395
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Interlace: JPEG
  Background color: white
  Border color: srgb(223,223,223)
  Matte color: grey74
  Transparent color: black
  Compose: Over
  Page geometry: 640x640+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: JPEG
  Quality: 90
  Orientation: Undefined
  Properties:
    date:create: 2015-08-31T15:03:01+06:00
    date:modify: 2015-08-31T15:03:01+06:00
    jpeg:colorspace: 2
    jpeg:sampling-factor: 2x2,1x1,1x1
    signature: 1fdd9905001a355c9fe432dadc5a94371f4e114a86579567243d8407c4822996
  Profiles:
    Profile-8bim: 92 bytes
    Profile-iptc: 79 bytes
      Special Instructions[2,40]: FBMD0f00075c010000a02100003b7300002d810000f8910000e5f0000037430100265f0100
  Artifacts:
    filename: rgb1.jpg
    verbose: true
  Tainted: False
  Filesize: 89.9KB
  Number pixels: 410K
  Pixels per second: 20.48MB
  User time: 0.020u
  Elapsed time: 0:01.019
  Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org

### And here is the output of  ```identify -verbose``` of rgb2.jpg

Image: rgb2.jpg
  Format: JPEG (Joint Photographic Experts Group JFIF format)
  Class: DirectClass
  Geometry: 640x640+0+0
  Resolution: 72x72
  Print size: 8.88889x8.88889
  Units: Undefined
  Type: TrueColor
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 8-bit
  Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
  Channel statistics:
    Red:
      min: 0 (0)
      max: 255 (1)
      mean: 187.79 (0.736431)
      standard deviation: 61.9704 (0.243021)
      kurtosis: -0.528994
      skewness: -0.592129
    Green:
      min: 0 (0)
      max: 255 (1)
      mean: 177.931 (0.697768)
      standard deviation: 64.8704 (0.254394)
      kurtosis: -0.980111
      skewness: -0.355393
    Blue:
      min: 0 (0)
      max: 255 (1)
      mean: 166.568 (0.653209)
      standard deviation: 69.8359 (0.273866)
      kurtosis: -1.33633
      skewness: -0.140064
  Image statistics:
    Overall:
      min: 0 (0)
      max: 255 (1)
      mean: 177.43 (0.695803)
      standard deviation: 65.6393 (0.257409)
      kurtosis: -0.956921
      skewness: -0.376036
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Interlace: JPEG
  Background color: white
  Border color: srgb(223,223,223)
  Matte color: grey74
  Transparent color: black
  Compose: Over
  Page geometry: 640x640+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: JPEG
  Quality: 80
  Orientation: Undefined
  Properties:
    date:create: 2015-08-31T15:03:09+06:00
    date:modify: 2015-08-31T15:03:09+06:00
    jpeg:colorspace: 2
    jpeg:sampling-factor: 2x2,1x1,1x1
    signature: 798b4a8f7d1dd2a1cdc5f1871f69028b714e4263c92ca94238b89112b15d38d7
  Profiles:
    Profile-8bim: 108 bytes
    Profile-icc: 524 bytes
      Description: c2
      Manufacturer: c2
      Model: c2
      Copyright: FB
    Profile-iptc: 95 bytes
      Special Instructions[2,40]: FBMD23000987030000bc170000271c0000f920000086480000506500004d7c0000119f0000fcbc0000a4e40000
  Artifacts:
    filename: rgb2.jpg
    verbose: true
  Tainted: False
  Filesize: 58.5KB
  Number pixels: 410K
  Pixels per second: 20.48MB
  User time: 0.020u
  Elapsed time: 0:01.019
  Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org

**Comment by dlemstra** [comment]
Your version of ImageMagick is over 3 years old. Can you reproduce the issue with the latest version?

**Comment by urban-warrior** [comment]
We can reproduce the problem you posted and will have a patch within the next day or two.  Thanks.

**Comment by kavirajk** [comment]
Ye @urban-warrior  is right. I face the same problem with ImageMagick 6.9.2-0

**Comment by kavirajk** [comment]
@urban-warrior Is it working now??

**Comment by olear** [comment]
ImageMagick works as it should.

You need to check (colorspace/embedded profile) your source image before you do a convert, and adjust accordingly.

**Comment by kavirajk** [comment]
@olear Thanks for the info. Can you tel how do I convert in above case which is not converting rgb1.jpg to CMYK. What should I do before converting rgb1.jpg
