### ISSUE TITLE
delegate failed `"curl" -s -k -o "%o" "https:%F"' @ error/delegate.c/InvokeDelegate/1065

### ISSUE THREAD

**Issue by igniting** [ImageMagick/ImageMagick#230]
On running:

`convert https://www.imagemagick.org/image/wizard.png wizard.png`

I get this error:

```
convert.im6: delegate failed `"curl" -s -k -o "%o" "https:%F"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-3zcDa8hd': No such file or directory @ error/blob.c/OpenBlob/2641.
convert.im6: unable to open file `/tmp/magick-3zcDa8hd': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `wizard.png' @ error/convert.c/ConvertImageCommand/3044.
```

When running `curl -s -k -o wizard.png https://www.imagemagick.org/image/wizard.png` directly, I get no such error.

Useful info:

```
$ convert --version
Version: ImageMagick 6.7.7-10 2016-06-01 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP 
```

I have commented out this line in `policy.xml`:
`<!-- <policy domain="coder" rights="none" pattern="HTTPS" /> -->`

and `delegates.xml` contains this line:
`<delegate decode="https" command="&quot;curl&quot; -s -k -o &quot;%o&quot; &quot;https:%F&quot;"/>`

**Comment by mikayla-grace** [comment]
Add -verbose to your command-line.  What does it report?  We tried your command and it works for us:

```
-> convert -verbose https://www.imagemagick.org/image/wizard.png wizard.png
'curl' -s -k -L -o '/tmp/magick-32246wQvicdplK3Qt' 'https://www.imagemagick.org/image/wizard.png'
```

**Comment by igniting** [comment]
```
$ convert -verbose https://www.imagemagick.org/image/wizard.png wizard.png
"curl" -s -k -o "/tmp/magick-8C5ripNB" "https:"
convert.im6: delegate failed `"curl" -s -k -o "%o" "https:%F"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-vN6RgzJh': No such file or directory @ error/blob.c/OpenBlob/2641.
convert.im6: unable to open file `/tmp/magick-vN6RgzJh': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `wizard.png' @ error/convert.c/ConvertImageCommand/3044.
```

**Comment by vovkin** [comment]
Have exactly same problem

**Comment by PaulAik** [comment]
Same issue here. 

OS: Ubuntu 14.04.5 LTS
ImageMagick: 6.7.7-10

`convert -verbose https://www.imagemagick.org/image/wizard.png wizard.png`

```
"curl" -s -k -o "/tmp/magick-nLw3O5Zv" "https:"
convert.im6: delegate failed `"curl" -s -k -o "%o" "https:%F"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: unable to open image `/tmp/magick-l3o9XmX2': No such file or directory @ error/blob.c/OpenBlob/2641.
convert.im6: unable to open file `/tmp/magick-l3o9XmX2': No such file or directory @ error/constitute.c/ReadImage/583.
convert.im6: no images defined `wizard.png' @ error/convert.c/ConvertImageCommand/3044.
```

**Comment by mikayla-grace** [comment]
It looks like %F was not supported in ImageMagick 6.7.7-10.  Change %F to %M in delegates.xml for the https delegate.  Even better, download the latest release of ImageMagick, build, and install.

**Comment by PaulAik** [comment]
Hi @mikayla-grace, so changed line to:

`<delegate decode="https" command="&quot;curl&quot; -s -k -o &quot;%o&quot; &quot;https:%M&quot;"/>`

Different issue occurs:

```
"curl" -s -k -o "/tmp/magick-8KKtqcfo" "https://www.imagemagick.org/image/wizard.png"
convert.im6: delegate failed `"curl" -s -k -o "%o" "https:%M"' @ error/delegate.c/InvokeDelegate/1065.
convert.im6: Expected 8192 bytes; found 7883 bytes `/tmp/magick-Y3EPReKf' @ warning/png.c/MagickPNGWarningHandler/1754.
convert.im6: Read Exception `/tmp/magick-Y3EPReKf' @ error/png.c/MagickPNGErrorHandler/1728.
convert.im6: corrupt image `/tmp/magick-Y3EPReKf' @ error/png.c/ReadPNGImage/3723.
convert.im6: no images defined `wizard.png' @ error/convert.c/ConvertImageCommand/3044.
```

Looks like a manual build & install may be required to fix as suggested?

**Comment by joanff** [comment]
same problem too

**Comment by jasonlttl** [comment]
I had this issue on ubuntu after an update to 6.7.7-10 and changing from %F to %M in delegates.xml solved the problem for me.

**Comment by stiller-leser** [comment]
This will also fail if the url points at an image stored on AWS S3. Here's the verbose output:

`*   Trying *ip*
* TCP_NODELAY set
* Connected to *bucket* (*ip*) port 443 (#0)
* SSL peer handshake failed, the server most likely requires a client certificate to connect
* Curl_http_done: called premature == 1
* Closing connection 0`

Any idea how to circumvent this? Removing 

> -k

from delegates.xml is not really an options since we'd like not to end up with an individual fork.
