### ISSUE TITLE
Error reading some "OpenImageIO" generated Arnold TX files

### ISSUE THREAD

**Issue by asch75** [ImageMagick/ImageMagick#2316]
Hi guys;

I noticed a issue trying to run "magick identify" in some Arnold TX files. The files are generated using the MakeTX tool included in the Solidangle Arnold bin directory. These are detected (and encoded) as TIFF files.

Files generated with MakeTX command and the --oiio modifier (OIIO-optimized settings for tile size, planarconfig, metadata, and constant-color optimizations) output this error:

> identify: Sanity check on directory count failed, zero tag directories not supported. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/661.
> identify: Failed to read custom directory at offset 4986812. `TIFFReadCustomDirectory' @ error/tiff.c/TIFFErrors/661.

Same files generated with MakeTX and the --prman modifer (Use PRMan-safe settings for tile size, planarconfig, and metadata.) runs fine.

Seems there's some trouble with OpenImageIO TIFF generated files. Any clue about this?. Is a normal issue?
Maybe there's some magick version without this problem?

**Comment by urban-warrior** [comment]
Post a link to one of the problematic TIFF image files.  We need to inspect it before we can offer additional help.

**Comment by asch75** [comment]
Hi;
First, thanks for looking at this problem.
Yep, I forgot to include a sample file. Sorry.
This one was generated with MakeTX.exe found in Solidangle Arnold 2018.

[imageTest.zip](https://github.com/ImageMagick/ImageMagick/files/5006129/imageTest.zip)

Thanks.

**Comment by dlemstra** [comment]
There appears to be an error in the exif properties of your file. With the following command you will be able to read it:
`magick -define tiff:exif-properties=false imageTest.tx info:`
