### ISSUE TITLE
Disable config xml files (on Mac/Windows)

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#232]
I built an application that statically links `magick++` with all of its dependencies into a single program. I got it to work on both mac and windows. The application does not include any xml configuration files, I just want to use the default settings.

However on windows, the first time I try to read an image it throws a c++ exception. The same happens the first time it looks for `color.xml`, etc.

```
Magick: UnableToOpenConfigureFile `magic.xml' @ warning/configure.c/GetConfigureOptions/709 
```

The funny thing is this only happens once. If I try again it works (with the default settings). How can I configure `magick++` to always use the default settings, without throwing an exception when there are no xml configuration files?

**Comment by dlemstra** [comment]
We have a define called `MAGICKCORE_ZERO_CONFIGURATION_SUPPORT` for this but it appears that we did not add this check at all the places where we load xml config files. I just pushed a patch (https://github.com/ImageMagick/ImageMagick/commit/b18d864b3f06e9272582b7736230d934d715d542) to resolve this. I will check the ImageMagick 6 branch later today.

Under Windows you can also set the define `MAGICKCORE_LIBRARY_NAME` to the name of your library and include the XML files as an embedded resource. I use this feature in Magick.NET (.NET wrapper of ImageMagick)

**Comment by jeroenooms** [comment]
Thank you! I'll try to rebuild with the next release, hopefully that solves the problem.

**Comment by jeroenooms** [comment]
This is still not fully working:

```r
> image_read("Rplots.svg")
Error: Magick: UnableToOpenConfigureFile `type.xml' @ warning/configure.c/GetConfigureOptions/71
```

**Comment by dlemstra** [comment]
Is that with IM6 or IM7?

**Comment by jeroenooms** [comment]
6

**Comment by dlemstra** [comment]
Are you sure that you are using the latest source code? You should not get that message when `MAGICKCORE_ZERO_CONFIGURATION_SUPPORT` is set: https://github.com/ImageMagick/ImageMagick/blob/ImageMagick-6/magick/type.c#L201

**Comment by jeroenooms** [comment]
I am compiling the latest IM6 `--with-zero-configuration`. But I can try again.

**Comment by jeroenooms** [comment]
Is there any way I can see if a build was compiled `--with-zero-configuration`? The `MAGICKCORE_ZERO_CONFIGURATION_SUPPORT` macro is not present in `magick-baseconfig.h`.

**Comment by jeroenooms** [comment]
Oh wait there is a `ZERO_CONFIGURATION_SUPPORT` in `magick-baseconfig.h`.

**Comment by jeroenooms** [comment]
Maybe there is a problem with the configure script? IM6 is configured like this:

```
==> ./configure --disable-osx-universal-binary 
--prefix=/private/tmp/homebrew/Cellar/imagemagick/6.9.5-3 
--disable-silent-rules --enable-shared --enable-static --without-modules --disable-openmp 
--with-webp=yes --without-openjp2 
--without-gslib --with-gs-font-dir=/private/tmp/homebrew/share/ghostscript/fonts 
--with-rsvg --without-x --with-fontconfig=yes --with-freetype=yes --enable-zero-configuration
```

However `magick-baseconfig.h` does **not** define `ZERO_CONFIGURATION_SUPPORT`.

**Comment by dlemstra** [comment]
Can you still reproduce this issue @jeroen ?

**Comment by jeroen** [comment]
I think it is fixed. My [latest build](https://github.com/rwinlib/imagemagick6/blob/master/include-4.9.3/x64/magick/magick-baseconfig.h#L1414-L1417) contains the macro.

**Comment by Nicknamen** [comment]
Hi,
how do I solve the same problem with IM7?
I can't find ZERO_CONFIGURATION_SUPPORT in baseconfig anymore.

**Comment by pavik** [comment]
There is MAGICKCORE_ZERO_CONFIGURATION_SUPPORT
