### ISSUE TITLE
convert pdf to png gives surprising result

### ISSUE THREAD

**Issue by pgundlach** [ImageMagick/ImageMagick#2320]
### Prerequisites

- [X] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick (I use ...24, but homebrew has no update)
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I run `convert reference.pdf out.png` and get a surprising output.  I expect a full circle in the PNG instead of a "half" circle.

### Steps to Reproduce

    convert reference.pdf out.png

### System Configuration

- ImageMagick version: 7.0.10-24
- Environment (Operating system, version and so on): macOS 10.14.6, `uname -a`  gives me `Darwin silver.fritz.box 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64`.
- Additional information: installed via homebrew (macOS)

Not sure if this is related to Ghostscript. I use gs version 9.52.

```
Version: ImageMagick 7.0.10-24 Q16 x86_64 2020-07-18 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(3.1) 
Delegates (built-in): bzlib freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib
```

The attached files 
[reference.pdf](https://github.com/ImageMagick/ImageMagick/files/4976301/reference.pdf)

![out](https://user-images.githubusercontent.com/209434/88465062-1df72400-cec0-11ea-8cd9-3edbdca2371c.png)

I'd be happy to give more information if needed.

**Comment by fmw42** [comment]
Works fine for me on IM 7.0.10.24 Q16 Mac OSX with Inkscape as the SVG renderer.  It is likely you are using the internal ImageMagick MSVG/XML renderer. Install either RSVG delegate or Inkscape and it should work better.

**Comment by pgundlach** [comment]
Thank you for your answer. So the SVG delegate is also used for PDF? I do have inkscape installed, so my next step is to find out how to change the svg delegate to use inkscape.

**Comment by dlemstra** [comment]
I suspect @fmw42 misread your question. This is most likely a bug in GhostScript. Converting the image with GS 9.27 produces the correct output.

**Comment by pgundlach** [comment]
@dlech Thank you for the hint. I have tried to use ghostscript directly

    gs -sDEVICE=pngalpha -sOutputFile=out.png reference.pdf  -dBATCH -dNOPAUSE -dQUIET

which gives me the same result. I try to post this bug on the ghostscript site, so I close this one.

**Comment by fmw42** [comment]
SVG renderer is not used for PDF. Ghostscript is needed for PDF

**Comment by fmw42** [comment]
Some GS versions are buggy around 9.25-9.27. I suggest you use the latest version.

**Comment by pgundlach** [comment]
It was indeed a postscript error. It has been fixed upstream. (https://bugs.ghostscript.com/show_bug.cgi?id=702587)
