### ISSUE TITLE
Magick++ "CorruptImageProfile `xmp' @ warning/profile.c/SetImageProfileInternal/1890"

### ISSUE THREAD

**Issue by potterpg** [ImageMagick/ImageMagick#2329]
I have this error using the Magick++ CPP API:
Version: ImageMagick 7.0.10-17 Q16 x86_64 2020-06-19
Error in XCODE: (MacOS Catalina)
![Screenshot - 27_07_2020 , 13_56_57](https://user-images.githubusercontent.com/25082282/88544401-3aef3c80-d011-11ea-855a-8a46cabe7d3c.png)
Image used:
![IMG_0708](https://user-images.githubusercontent.com/25082282/88544443-4b9fb280-d011-11ea-9718-061c92c6e03e.jpg)

Same solution compiled on Windows with VS2019 does seem to work?

_Originally posted by @potterpg in https://github.com/ImageMagick/ImageMagick/issues/1419#issuecomment-664385478_

Additional info:

	Blob ImageBlob;
	Magick::Image ReturnImage;
	Geometry FinalSize;

#if defined(isunix) || defined(isCOCOA)	|| defined(ismac)
			const void* blobData = (qchar*)MEMcalloc(MemSize);
#elif defined(iswin32)
			HGLOBAL liHandle = MEMglobalAlloc(MemSize, qtrue);
			const void* blobData = (qchar*)MEMglobalLock(liHandle);
#endif
			JPG_image.getBinary(MemSize, (qbyte*)blobData, ActualLength);

			ImageBlob.update(blobData, MemSize);

			ImageWidth = JPG_width.getLong();
			ImageHeight = JPG_width.getLong();

			FinalSize.width(ImageWidth);
			FinalSize.height(ImageHeight);
			FinalSize.greater(true);

			ReturnImage.read(ImageBlob);

This last line of reading the ImageBlob into the Image is where the error occurs...
(JPG_image.getBinary is just a transition between this and another language... no problems here, it for sure works on windows, and indeed other images...)
My test was setting the image width/height to 150/150.

**Comment by potterpg** [comment]
in Profile,c:
you have:
#if defined(MAGICKCORE_XML_DELEGATE)
#else
static MagickBooleanType ValidateXMPProfile(const StringInfo *profile)
{
  return(MagickFalse);
}
#endif


I wonder if that should be MagickTrue

I didn't have XML delegate so had the error...
Should not having XML delegate really cause a MagickFalse ?

**Comment by dlemstra** [comment]
When we cannot validate the profile we handle it as invalid. But this exception is just a warning. Calling `ReturnImage.quiet(true)` should silence this warning.
