### ISSUE TITLE
writeImages segfaults for length 0

### ISSUE THREAD

**Issue by jeroenooms** [ImageMagick/ImageMagick#233]
This is an odd edge case but `writeImages` should not segfault if `image` is length 0. 

```cpp
Image *image = new std::vector<Magick::Image>;
Magick::Blob output;
writeImages( image->begin(), image->end(),  &output );
```

**Comment by dlemstra** [comment]
Can you help us with another pull request?

**Comment by dlemstra** [comment]
We have added the patches ourself. Can you confirm that (https://github.com/ImageMagick/ImageMagick/commit/41f886eae8c84db22e27252317901aa20dbd50cc) resolves your issue?

**Comment by jeroenooms** [comment]
I can confirm that this problem was fixed. Thank you!
