### ISSUE TITLE
GIF animate error in IOS(maybe dispose bug)

### ISSUE THREAD

**Issue by EthanXzhang** [ImageMagick/ImageMagick#2363]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Using IM OptimizeImageLayers() and OptimizeImageTransparency() method to optimize input GIF.
The input GIF sequence has 18 frame and all the dispose is NoneDispose, bug when optimize and get the output sequce, 1-4 frame are None, 5th is Previous and 6th is Background.
Output optimized GIF play and rendering normal as input GIF in PC, but optimized GIF will flash in 6/12/18 frame in IOS device.
We put optimized GIF in PhotoShop, and saw that 6/12/18 frame has a transparent background with a few content in canvas.
Now, we suspect GIF optimization function lead the wrong dispose in those flash frame, and we have already try to modify dispose 'Background' to 'None' by ourselves after optimization function and the result seems OK.

We also find that webp animation has the same or relate issue in Mac OX(#1927) and find that a bug fix in #2298 in webp animation dispose with the same solution as we tried.

Thanks for all help!

### System Configuration
Centos 7
ImageMagick 7.0.8 Q8

**Comment by urban-warrior** [comment]
Please try ImageMagick 7.0.10-25, the latest release.  If the issue persists, post a link to an image that exhibits the issue.  We need to reproduce it before we can comment further.
