### ISSUE TITLE
Magick++ cannot load SVG from Blob

### ISSUE THREAD

**Issue by red2fred2** [ImageMagick/ImageMagick#2374]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When using the Magick++ C++ library, reading SVG data from a Blob does nothing.
### Steps to Reproduce

1. Load SVG file into byte array
2. Initialize Blob with that byte array
3. Initialize Image object
4. Read the Blob into that image
5. View blank image

### System Configuration

- ImageMagick version: 7.0.10-23 Q16 x86
- Environment (Operating system, version and so on): Windows 10 Enterprise x64 1809
- Additional information:

**Comment by dlemstra** [comment]
Could you also include the code that can be used to reproduce this?

**Comment by red2fred2** [comment]
```cpp
// Load a blob that is definitely correct
Magick::Image loadedImage("test.svg");
Magick::Blob svgBlob;
loadedImage.write(&svgBlob);

// Set up image to load to
Magick::Image image;
image.backgroundColor("green");
image.size(Magick::Geometry(100, 100));
image.depth(8);

// Here's where the bug seems to happen
image.read(svgBlob);
```
In this case, 'loadedImage' is correct, but 'image' is just a 100x100 green square.

**Comment by dlemstra** [comment]
The problem is that when you save the file the internal svg encoder of ImageMagick is used an an svg with a base64 encoded image is created. But when you read the file the RSVG library that we use cannot process that. My advise would be to save the image to the blob in a different format instead.
