### ISSUE TITLE
wrong mime types for PAM and PGM format in PNM module

### ISSUE THREAD

**Issue by jenderek** [ImageMagick/ImageMagick#2375]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When i run identify command with -verbose option version 7.0.10-14 Q16
x64 on Windows i get wrong mime type for some formats of PNM module.

For comparison reason i run the file format identification utility
TrID ( See https://mark0.net/soft-trid-e.html). This list the correct
used mime type with -v option and the related URL pointing to used file
format information. The URL with sites about Netpbm are as following:

	https://en.wikipedia.org/wiki/Netpbm
	http://fileformats.archiveteam.org/wiki/Netpbm_formats

Netpbm variant like sample input_p2.pgm starting with 2 byte sequence
P2 are described correctly by ImageMagick identify as "PGM (Portable
graymap format (gray scale))", but displayed is mime type
"image/x-portable-greymap". That is not right. According to mentioned
documentation the correct name is American spelled with letter "a"
instead "e" in color. So correct mime type is "image/x-portable-graymap".

The same error occur for variant like sample input_p5.pgm starting
with 2 byte sequence P5.

Netpbm variant like sample sample_1920×1280.pam starting with 2 byte
sequence P7 are described correctly by ImageMagick identify as "PAM
(Common 2-dimensional bitmap format)". The displayed mime type
"image/x-portable-pixmap" is used for "P3" and "P6" PPM variants and
the newer "P7" has an own mime type. That right value is
"image/x-portable-arbitrarymap".

I hope that the wrong mime types in PNM module will be fixed.

Thanks!

### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
