### ISSUE TITLE
Paths in Photoshop EPS files are corrupted on conversion using IM7

### ISSUE THREAD

**Issue by FredrikEngquist** [ImageMagick/ImageMagick#2380]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When converting a Photoshop EPS to another format (e.g. TIFF or JPG) any existing paths are corrupted.
This does not happen when comverting from PSD, TIFF etc.
I'm using ImageMagick 7.0.10-7 Q16 x86_64 on a Mac.
(this works fine in IM6, last verified in 6.9.9-40 Q16 x86_64)

After conversion Photoshop will complain about corrupt content in the resulting image, IM itself finds no paths at all and ExifTool reports 'Warning                         : Bad Photoshop IRB resource "\x00\x00\x00\x00"'.

This works fine in IM6, last verified in 6.9.9-40 Q16 x86_64.

### Steps to Reproduce
I have uploaded a test file and result files to [https://magnitude.box.com/s/9xuzwxcz3e1uwtbniffuxp0pj2eouw1u](https://magnitude.box.com/s/9xuzwxcz3e1uwtbniffuxp0pj2eouw1u)

Version: ImageMagick 7.0.10-7 Q16 x86_6:
`magick -verbose -density 300 eps_w_paths.eps[0] -depth 8 tiff_no_paths_IM7010_7.tif`
results in an image with a corrupt path segment.

Version: ImageMagick 6.9.9-40 Q16 x86_64:
`convert -verbose -density 300 eps_w_paths.eps[0] -depth 8 tiff_w_paths_IM699_40.tif`
results in an image with the same path segment as the original EPS.

### System Configuration
I have done my personal tests on a Mac (10.14.6)
but I have seen the same result on  a Linux host

Mac
fredrik-mac:200805_preview_issues figge$ magick -version
Version: ImageMagick 7.0.10-7 Q16 x86_64 2020-04-10 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib freetype jng jpeg lcms png raw tiff webp xml zlib

Linux:
[root@macserver2 ~]# magick -version
Version: ImageMagick 7.0.10-25 Q16 x86_64 2020-08-03 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(3.1) 
Delegates (built-in): cairo fontconfig freetype jng jp2 jpeg lzma png rsvg tiff x xml zlib

**Comment by fmw42** [comment]
I seem to need a log in to access your file.

**Comment by FredrikEngquist** [comment]
Sorry about that. They make it very difficult to share.

This should work now [https://magnitude.box.com/s/9xuzwxcz3e1uwtbniffuxp0pj2eouw1u](https://magnitude.box.com/s/9xuzwxcz3e1uwtbniffuxp0pj2eouw1u)

**Comment by fmw42** [comment]
I confirm the problem on IM 6.9.11.25 and 7.0.10.25 Q16 Mac OSX. I do not have an installed version of 6.9.9.40 to test that their was no issue at that time.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by FredrikEngquist** [comment]
There seems to be another variation on this.
While the fix has resolved some path corruptions I have also found some that still exist.

I have uploaded another set of images (before and after conversion) here:
[https://magnitude.box.com/s/2dld2jnrgkp3cn3ba9tputcldb6hh156](https://magnitude.box.com/s/2dld2jnrgkp3cn3ba9tputcldb6hh156)

I tested the new build (ImageMagick 7.0.10-27 Q16 x86_64 2020-08-11) on a Linux host with the following steps, verifying the paths using ExifTool:
---
[root@macserver2 200812_path_issue]# magick -version
Version: ImageMagick 7.0.10-27 Q16 x86_64 2020-08-11 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(3.1) 
Delegates (built-in): cairo fontconfig freetype jng jp2 jpeg lcms lzma png rsvg tiff x xml zlib
[root@macserver2 200812_path_issue]# ls -l
total 60608
-rwxr--r--. 1 root root  4451332 Aug 12 04:47 01-957-000.eps
-rwxr--r--. 1 root root   322541 Aug 12 04:46 08-002-040.eps
-rwxr--r--. 1 root root  2390965 Aug 12 04:46 08-972-840.eps
-rwxr--r--. 1 root root  3487219 Aug 12 04:45 55-100-001_wg2.eps
-rwxr--r--. 1 root root  2392001 Aug 12 04:46 61-163-033.eps
-rwxr--r--. 1 root root 48336509 Aug 12 04:45 85-191-877.eps
[root@macserver2 200812_path_issue]# magick 61-163-033.eps -depth 8 61-163-033.tiff;magick 55-100-001_wg2.eps -depth 8 55-100-001_wg2.tiff;magick 08-002-040.eps -depth 8 08-002-040.tiff;magick 08-972-840.eps -depth 8 08-972-840.tiff;magick 01-957-000.eps -depth 8 01-957-000.tiff
[root@macserver2 200812_path_issue]# ls -l
total 60608
-rwxr--r--. 1 root root  4451332 Aug 12 04:47 01-957-000.eps
-rw-r--r--. 1 root root   289142 Aug 12 05:43 01-957-000.tiff
-rwxr--r--. 1 root root   322541 Aug 12 04:46 08-002-040.eps
-rw-r--r--. 1 root root    67918 Aug 12 05:43 08-002-040.tiff
-rwxr--r--. 1 root root  2390965 Aug 12 04:46 08-972-840.eps
-rw-r--r--. 1 root root    60968 Aug 12 05:43 08-972-840.tiff
-rwxr--r--. 1 root root  3487219 Aug 12 04:45 55-100-001_wg2.eps
-rw-r--r--. 1 root root   134020 Aug 12 05:43 55-100-001_wg2.tiff
-rwxr--r--. 1 root root  2392001 Aug 12 04:46 61-163-033.eps
-rw-r--r--. 1 root root   118442 Aug 12 05:43 61-163-033.tiff
-rwxr--r--. 1 root root 48336509 Aug 12 04:45 85-191-877.eps
[root@macserver2 200812_path_issue]# exiftool -Photoshop:ClippingPathName -charset photoshop=MacRoman 61-163-033.eps;exiftool -Photoshop:ClippingPathName -charset photoshop=MacRoman 55-100-001_wg2.eps;exiftool -Photoshop:ClippingPathName -charset photoshop=MacRoman 08-002-040.eps;exiftool -Photoshop:ClippingPathName -charset photoshop=MacRoman 08-972-840.eps;exiftool -Photoshop:ClippingPathName -charset photoshop=MacRoman 01-957-000.eps
Clipping Path Name              : Freisteller
Clipping Path Name              : Path 1
Clipping Path Name              : ÉpÉX1
Clipping Path Name              : Tracé 1
Clipping Path Name              : Trazado 1
[root@macserver2 200812_path_issue]# exiftool -Photoshop:ClippingPathName -charset photoshop=MacRoman 61-163-033.tiff;exiftool -Photoshop:ClippingPathName -charset photoshop=MacRoman 55-100-001_wg2.tiff;exiftool -Photoshop:ClippingPathName -charset photoshop=MacRoman 08-002-040.tiff;exiftool -Photoshop:ClippingPathName -charset photoshop=MacRoman 08-972-840.tiff;exiftool -Photoshop:ClippingPathName -charset photoshop=MacRoman 01-957-000.tiff
Warning: Bad Photoshop IRB resource "\xea\xad\xbe\xea" - 61-163-033.tiff
Warning: Bad Photoshop IRB resource "\xea\xad\xbe\xea" - 55-100-001_wg2.tiff
Warning: Bad Photoshop IRB resource "\xea\xad\xbe\xea" - 08-002-040.tiff
Warning: Bad Photoshop IRB resource "\xea\xad\xbe\xea" - 08-972-840.tiff
Warning: Bad Photoshop IRB resource "\xea\xad\xbe\xea" - 01-957-000.tiff
[root@macserver2 200812_path_issue]#
