### ISSUE TITLE
PCT/PICT type bi-level channel r,g,b 1-bit image RW not working in libmagickcore, wand or convert

### ISSUE THREAD

**Issue by LEE-DOOWON** [ImageMagick/ImageMagick#2386]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

PCT/PICT type bi-level channel r,g,b 1-bit image RW not working in libmagickcore, wand or convert

[ This is a sample file 샘플 파일 입니다. pct.zip](https://github.com/ImageMagick/ImageMagick/files/5039385/pct.zip)

### Steps to Reproduce

 step1. improper image header `pct.pct' @ error/pict.c/ReadPICTImage/917.
```
identify -verbose pct.pct
```
Image without initialization area of the header part is not working. Mac OS X or other apps(libreoffice) seem to have been implemented to load without area(works fine). libreoffice

/core/filter/source/graphicfilter/ipict/ipict.cxx
![image](https://user-images.githubusercontent.com/5683021/89609417-be7f1800-d8b2-11ea-8b01-7d511ac59678.png)

step2. all color black of result image 
 (It same result using libmagickcore, wand ReadImage and WriteImage)

```
convert pct image test.pct ext.pct 
convert pct image test.pct ext.png 
```

![ext](https://user-images.githubusercontent.com/5683021/89610550-c096a600-d8b5-11ea-9ff7-dde3980f9d09.png)

check please!

### System Configuration

- ImageMagick version: ImageMagick 6.9.10-23 Q16 x86_64 20190101
- Environment (Operating system, version and so on): Debian10 5.6.0-2-amd64 
- Additional information: libmagickcore-dev, libmagickwand-dev 8:6.9.10.23+dfsg-2.1

**Comment by urban-warrior** [comment]
ImageMagick can extract image pixels from a PICT image file, however, ImageMagick does not support PICT drawing opcodes.  Your image is comprised of 22 poloygon rendering opcodes.  As these are skipped, the resulting image is blank.

**Comment by LEE-DOOWON** [comment]
Thank you!
