### ISSUE TITLE
Linking on mingw-w64

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#239]
To make the build succeed on mingw-w64 without linking errors I use:

``` bash
./configure \
   --enable-static \
   --enable-shared \
   LIBS="-lOleAut32 -lws2_32 -pthread"
```

It would be great if the autoconf script automatically adds those libs, but I don't understand autoconf well enough to write a pull request. Probably something like this:

``` bash
AS_CASE([$host_os],[mingw*], [
  LIBS="$LIBS -lOleAut32 -lws2_32 -pthread"
])
```

**Comment by mikayla-grace** [comment]
We downloaded the latest MSYS2 with mingw-w64, upgraded to the latest packages with pacman, and compiled, installed, and ran ImageMagick.  The build did not require any modifications to the source or configure scripts.  Testing ImageMagick completed without any complaints.

**Comment by jeroenooms** [comment]
@mikayla-grace strange, I did exactly the same thing and it ends in linking errors. Which configuration did you build? Did you `--enable-static --enable-shared` ?

**Comment by mikayla-grace** [comment]
Did you update pacman? See https://sourceforge.net/p/msys2/wiki/MSYS2%20installation/.  We just used ./configure, no command-line arguments.   We installed ImageMagick with pacman first to install all the dependencies.  We also updated all the system packages with pacman and installed gcc.

**Comment by jeroenooms** [comment]
Did you use the plain IM sources or the patched IM sources from msys2? Try building with `--enable-static` and `--with-magick-plus-plus`

**Comment by mikayla-grace** [comment]
We downloaded the source from the ImageMagick website.  We'll try with --enable-static later today and report back.

**Comment by jeroenooms** [comment]
Make sure you also build the magick++ library :)

**Comment by mikayla-grace** [comment]
Built ImageMagick static with Magick++.  It built, installed, and ran without complaint.  We're using ImageMagick 7.  Are you building ImageMagick 6?

**Comment by dlemstra** [comment]
@jeroen Can we close this issue?
