### ISSUE TITLE
List of errors when attemting to convert .Tif file to .jpg file 

### ISSUE THREAD

**Issue by NicTanghe** [ImageMagick/ImageMagick#2392]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Attemting to convert a tof heightfile downloaded from https://www.sciencebase.gov/catalog/item/5deb3297e4b02caea0f0ea73

results in the following errors.

```(powershell)

 Tanghe@DESKTOP-5TJL5MP  ~\Downloads  magick convert USGS_13_n39w121.tif Heightmap.jpg
convert: Unknown field with tag 33550 (0x830e) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1037.
convert: Unknown field with tag 33922 (0x8482) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1037.
convert: Unknown field with tag 34735 (0x87af) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1037.
convert: Unknown field with tag 34736 (0x87b0) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1037.
convert: Unknown field with tag 34737 (0x87b1) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1037.
convert: Unknown field with tag 42112 (0xa480) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1037.
convert: Unknown field with tag 42113 (0xa481) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1037.
convert: Unknown field with tag 42113 (0xa481) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1037.
convert: Unknown field with tag 42113 (0xa481) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1037.
convert: Unknown field with tag 42113 (0xa481) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1037.
convert: Unknown field with tag 42113 (0xa481) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1037.
convert: Unknown field with tag 42113 (0xa481) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/1037.
```

### System Configuration

- ImageMagick version: Version: ImageMagick 7.0.10-19 Q16 x64 2020-06-12
- Environment (Operating system, version and so on): Windows 10
```
[System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19041  0
```
- Additional information:Exact Dl location https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/n39w121/USGS_13_n39w121.tif

**Comment by fmw42** [comment]
These are all just warnings that ImageMagick does not know about certain custom tiff tags. The processing should work fine. You can ignore these warnings by adding -quiet right after convert in your command.
