### ISSUE TITLE
Freetype does not work on OS-X without fontconfig

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#240]
The [homebrew version](https://github.com/Homebrew/homebrew-core/blob/master/Formula/imagemagick.rb) of imagemagick uses a `--with-freetype --without-fontconfig` configuration. However this build is unable to find fonts:

``` bash
curl -O https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/helloworld.svg
convert helloworld.svg out.png 
#>> convert: unable to read font `serif' @ warning/annotate.c/RenderType/927
```

See [-debug all error log](https://gist.github.com/jeroenooms/da3d5d417f0dd1a03c042502350df374). Same problem via the Magick++ interface:

``` r
> image_annotate(logo, "BLABLA", font = 'arial')
# Error: Magick: unable to read font `arial' @ warning/annotate.c/RenderType/918
```

The problem goes away if we install `--with-fontconfig`. I tried to [persuade](https://github.com/Homebrew/homebrew-core/pull/3129) the homebrew guys to enable this, but they refuse because fontconfig is too slow.

How to get text annotation/rendering to work on OS-X with only freetype (without fontconfig)?

**Comment by fmw42** [comment]
Just provide the full path to the font file including suffix, such as in my case

-font /Library/Fonts/arial.ttf

**Comment by jeroenooms** [comment]
I can't edit svg files to hardcode paths to font files because imagemagick can't find them. Also the name of the font sometimes does not map directly. Shouldn't imagemagick be able to find them by the name? It does so on windows.

**Comment by fmw42** [comment]
As far as I know, Unix versions of IM needs -fontconfig and a script (http://www.imagemagick.org/Usage/scripts/imagick_type_gen) or manual edit of type.xml for it to know fonts by name.  I know very little about SVG files or Windows. Perhaps Windows OS knows more about its system fonts than the Max OS and can deal with those in SVG files. I defer to someone who knows more about fonts and IM than I to help your more.

**Comment by fmw42** [comment]
Do you have either RSVG or Inkscape delegate installed? IM uses these delegates to process SVG files. IM has its own MSVG to do the same, but it is not as good as either of these two and it may require fontconfig to work with fonts. Just a thought. I really do not know enough how fonts are processed with SVG files.

**Comment by dlemstra** [comment]
@jeroen Can we close this issue?

**Comment by jeroen** [comment]
Yes I think so. It's unfortunate that homebrew builds without fontconfig by default, but I guess that's a limitation on their side.
