### ISSUE TITLE
Magick++ API Density retruns in picxlespercm,is it possible to change that to pixelsperInch

### ISSUE THREAD

**Issue by RAmbika** [ImageMagick/ImageMagick#2400]
### Description
I am trying to return Density of an existing BMP image and i want to get the units in pixelsperInch,currently i get this in pixlespercm. Is there a way i can change this.

I have tried as follows:
Image image;	
image.read( ImagePath);
ResolutionType type = image.resolutionUnits();
if (type != ResolutionType::PixelsPerInchResolution)
{
			image.resolutionUnits(ResolutionType::PixelsPerInchResolution);
}
Point Density;
Density = image.density();

but it still returns in pixelspercm. Can you please let me know if my aproach is correct or is there a was in can read the image density in pixelsperinch
		

### System Configuration
Windows 10 ,64 bit machine

- ImageMagick version:
- Windows 10,ImageMagick 7.0.8.67
- Additional information:

**Comment by dlemstra** [comment]
What happens when you upgrade to the most recent version of ImageMagick?
