### ISSUE TITLE
hint at format for readImages(blob)

### ISSUE THREAD

**Issue by jeroenooms** [ImageMagick/ImageMagick#241]
I found that when I read an image from a memory blob, Magick++ often does not recognize the type:

```
Error: Magick: no decode delegate for this image format `' @ error/blob.c/BlobToImage/355 
```

However the same data read fine if I read it directly from disk:

```
> image_info(magick:::magick_image_readpath("inst/Rlogo.svg"))
  format width height colorspace filesize
1    MVG   724    561       sRGB     1714
```

I presume IM uses the `svg` file name extension to detect the type? Is there any way I can read the image from a memory blob while still letting it know that it is an svg file?

**Comment by dlemstra** [comment]
Setting the `magick` property of an Image might help you with that. Can you give that a try?

**Comment by jeroenooms** [comment]
The function errors at `readImages` before one can set such properties.

**Comment by jeroenooms** [comment]
Where can I find the code that guesses the format from the file extension? Perhaps I can reverse engineer something...

**Comment by mikayla-grace** [comment]
See MagickCore/image.c/SetImageInfo().
