### ISSUE TITLE
ImageMagick Support File Format Page has wrong link: JXL goes to JPEG-XR

### ISSUE THREAD

**Issue by odysseyjason** [ImageMagick/ImageMagick#2410]
The page https://imagemagick.org/script/formats.php has a line for JXL but the link goes to the same link for JXR - https://en.wikipedia.org/wiki/JPEG_XR, it should go to https://arxiv.org/ftp/arxiv/papers/1908/1908.03565.pdf or maybe https://jpeg.org/jpegxl/index.html

It is currently pointing to the old Microsoft Jpeg-XR format (which is also supported and linked to above the JXL)

Jpeg-XL is a new image format.  Is it in fact supported?

**Comment by urban-warrior** [comment]
Thanks for the correction.  We made the changes you recommended.
