### ISSUE TITLE
ImageMagick does not wrap correctly between Chinese characters.

### ISSUE THREAD

**Issue by infinnie** [ImageMagick/ImageMagick#2412]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

![magick-output](https://user-images.githubusercontent.com/8168391/90212378-bdefff80-de25-11ea-9de6-5c9c36ad8b91.png)
Text does not correctly wrap between CJK characters, and the calculated font size is therefore incorrect.

### Steps to Reproduce

```bash
magick -debug annotate -size 300x200 -font c:/windows/fonts/msyh.ttf caption:"The quick brown fox jumps 中文字符串功能支持不能中文字符串功能支持不能 over the lazy dog" magick-output.png
```

### System Configuration

- ImageMagick version: ImageMagick 7.0.10-19 Q16 x64 2020-06-12
- Environment (Operating system, version and so on): Windows 7
- Additional information:

**Comment by urban-warrior** [comment]
We have no expertise with the CJK character set.  Can we wrap on any CJK character?  Or are there specific CJK characters we should use for word wrapping?

**Comment by infinnie** [comment]
> We have no expertise with the CJK character set. Can we wrap on any CJK character? Or are there specific CJK characters we should use for word wrapping?

There are CJK punctuation characters that cannot occur at the beginning of a line, and others that cannot occur at the end of a line. Other characters are free to wrap.

(I guess that latest versions have fixed the aforementioned problem?)

**Comment by urban-warrior** [comment]
A step closer, but not enough information to modify our word wrapping algorithm which is currently based on locating ANSI space characters.   In order to resolve this issue, we need a knowledgeable person, perhaps you, to identify which CJK characters cannot occur at the beginning of a line and which cannot occur at the end of a line.  Once the Unicode values are identified, we can improve the wrapping algorithms to support CJK characters.
