### ISSUE TITLE
Distorted clip path after -extent

### ISSUE THREAD

**Issue by xelax90** [ImageMagick/ImageMagick#2414]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
After using the option `-extent` on an image with a clip path inside, the clip path is scaled with the image instead of staying untouched. 

### Steps to Reproduce
Here is my test image: http://stelzers.info/imagemagick/2000000.tif
The executed command: 
```bash
magick '2000000.tif' '-format' 'TIF' '-background' 'srgb(255,255,255)' '-gravity' 'center' '-extent' '600x600' '2000000_ETIM_print.TIF'
```
The resulting image: http://stelzers.info/imagemagick/2000000_ETIM_print.TIF

### System Configuration
- ImageMagick version:
```bash
magick -version
Version: ImageMagick 7.0.10-27 Q16 x86_64 2020-08-14 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib djvu fontconfig freetype gvc jbig jng jp2 jpeg lcms lqr lzma openexr png tiff wmf x xml zlib
```
- Environment (Operating system, version and so on): Debian Stretch 9.12

**Comment by urban-warrior** [comment]
The clipping path is relative to the image size.  We can retain the clipping path if the image is resized as all knots are uniformly resized to the target image dimensions.  As we don't have support for modifying the knots in the clipping path, our only option for the `-extent` option is to remove the 8BIM profile.

**Comment by xelax90** [comment]
Hi @urban-warrior, thx for the reply. Is there any other way to retain the clipping path? For example I could try to extract the clipping path, then modify it with inkscape but I don't know any way to add it back into the resulting image.

**Comment by urban-warrior** [comment]
Try exiftool.

**Comment by xelax90** [comment]
I just looked into the actual clip path svg and a little bit into the code (although I'm not really familiar with c and even less so with the magick codebase). To me it looks like you do modify the clip path by changing the dimension and repositioning all knots in it. Bit I couldn't really find out why. As far as I can tell instead you would just have to set the width and height of the svg and move the knots depending on the gravity setting instead of scaling their positions.

**Comment by urban-warrior** [comment]
Agreed.  However, the development team currently does not have the time to work on this issue.  Instead, you or another user can contribute the solution as a pull request.

**Comment by xelax90** [comment]
I looked a bit into the code and didn't yet find the place where the path is modified but from my understanding this is what is happening: For every operation you use `CloneImage` which copies the profile information and does not modify any paths. When saving you probably check if the path svg fits the canvas and scale it accordingly. If that is correct that would mean that one would have to scale the svg at the end of the extent call and that would fix this particular issue. As far as I can tell, the same issue also occurs when using trim and crop operations. If I were to implement a fix here, could you give me some hints:
- Is my assumption correct that the path is modified right before save?
- Where is the 8bim profile parsed and encoded?
- Where is the code that handles the path modification?
- Is there a simple way to output or see the path svg contents for debugging purposes?

**Comment by urban-warrior** [comment]
The SVG clipping path is scaled when the image is read.  Currently, we simply remove the 8BIM profile when the -extent option is used.  The correct patch would be to move the knots based the extent arguments so they are position correctly when the SVG clipping path renders based on the new dimensions of the image, per the -extent argument.

**Comment by dlemstra** [comment]
In the next release of ImageMagick 7 the clip path will be updated when the image is extended.
