### ISSUE TITLE
unknown attribute '__alloc_size__'

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#242]
Not sure if this is already fixed in master, but when compiling on Debian testing (IM6.8.9) with clang we get a lot of these:

https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/magick-00install.html

**Comment by mikayla-grace** [comment]
Unfortunately we do not have access to Debian so we cannot reproduce the problem.    The warnings can be safely ignored.  The link error appears to be a compiler / linking problem.

**Comment by dlemstra** [comment]
We have a check to make sure this attribute won't get set with clang: https://github.com/ImageMagick/ImageMagick/blob/8aaee407a09d17dfa2d8e9e359f26feb4cc036ee/magick/method-attribute.h#L126. Not sure why __clang__ is not defined.

**Comment by dlemstra** [comment]
@jeroen Is this resolved and can we close this issue?

**Comment by jeroen** [comment]
Yes that's ok. I still have some trouble linking to IM on Debian when compiling with gcc 8 but that might be an issue for Debian.
