### ISSUE TITLE
Processing pdf with huge page performance issue

### ISSUE THREAD

**Issue by EQuincerot** [ImageMagick/ImageMagick#2423]
### Description
Processing pdf with huge page size (21x29 meters) never ends.

### Steps to Reproduce

1. Create a sample.svg with huge page size
```<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" 
     width="2100cm" height="2970cm" 
     viewBox="0 0 21000 29699.999" 
     version="1.1" id="svg16">

    <rect width="100%" height="100%" fill="lightblue"/>
</svg>
```
2. Convert it into pdf with inkscape : `inkscape sample.svg --export-pdf=sample.pdf`
1. Use image magick to get pdf properties `identify sample.pdf`

**Expected** : we get a quick result (within a second)
**Actual result** : huge files are stored in /tmp and pdf last for ages

Note: converting this pdf into image has the same issue:
- inkscape is still able to convert quickly the pdf into png `inkscape -f sample.pdf -e sample.png`
- convert is incredibly slow: `convert sample.pdf sample.png`

### System Configuration

- ImageMagick version: Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 (same result with image magick 7 on docker as well)
- Environment: Ubuntu 19.10
- Additional information: 
  - ghostscript version 9.27
  - Inkscape 0.92.4 (5da689c313, 2019-01-14)

**Comment by urban-warrior** [comment]
The PDF has dimensions of 21000x29699.999.  ImageMagick will render at those dimensions.  You can limit the rendering size in your policy.xml file to prevent a possible DOS or you can render a smaller instance with the -density option:

```
convert -density 10 sample.pdf sample.png
```

**Comment by EQuincerot** [comment]
Setting density does not fix the issue, the time to generate the thumbnail (or to run identify) is still too long (>1 min), you can try by your own.

**Comment by EQuincerot** [comment]
Ok thanks for the density help.
I was only using `-resize x200` option, it was not enough. Sorry for the noise.
