### ISSUE TITLE
Stack when resized

### ISSUE THREAD

**Issue by ts-ts** [ImageMagick/ImageMagick#2426]
Stack when resized...
Please fix it.

- ImageMagick version: ImageMagick-7.0.10-28-portable-Q16-x64.zip
- Environment (Operating system, version and so on): Windows 7 64bit

**Comment by urban-warrior** [comment]
We cannot grok your issue.  We would need more detail before we could comment further.

**Comment by ts-ts** [comment]
Sorry.

On cmd,
"D:\Program Files\ImageMagick\convert.exe" "D:\Temp_image\xxx.jpg" -resize 1140x "D:\Temp_image\xxx.jpg".
As a result, convert.exe gets stuck and resizing does not complete.

**Comment by dlemstra** [comment]
You will need to wait a bit longer. The first time that you run this command it is possible that an OpenCL benchmark is running. This is only done the first run, the next run should be faster.

**Comment by ts-ts** [comment]
I just wait a bit longer(more than 1 min.). But convert.exe remains to be stuck.

**Comment by fmw42** [comment]
Does it fail for a very small image? Does it fail with other image formats, such as GIF or PNG? Does it fail if your run it from C: directory?  Or does it fail if you change directories to the D: directory and remove the paths?

**Comment by ts-ts** [comment]
"ImageMagick-7.0.10-19-portable-Q16-x64" works good.
This contains folders named images and www.

"ImageMagick-7.0.10-20-portable-Q16-x64" does NOT contain folders named images and www.
"ImageMagick-7.0.10-28-portable-Q16-x64" is same.

Why "ImageMagick-7.0.10-20-portable-Q16-x64" does NOT contain these folders?

**Comment by ts-ts** [comment]
New "ImageMagick-7.0.10-29-portable-Q16-x64" get stuck and resizing does not complete.

**Comment by ts-ts** [comment]
New "ImageMagick-7.0.10-30-portable-Q16-x64" get stuck and resizing does not complete.
In addition, "ImageMagick-7.0.10-30-portable-Q8-x64" is same...
It works on Windows 7 64bit, right?

**Comment by ts-ts** [comment]
New "ImageMagick-7.0.10-33-portable-Q16-x64" works good.
Thanks for the fixing.
