### ISSUE TITLE
Error during linux installation

### ISSUE THREAD

**Issue by zeaksi** [ImageMagick/ImageMagick#243]
See ./test-suite.log
# Please report to https://github.com/ImageMagick/ImageMagick/issues

Makefile:10958: recipe for target 'test-suite.log' failed
make[3]: **\* [test-suite.log] Error 1
make[3]: Leaving directory '/home/zeeshan/Downloads/ImageMagick-7.0.2-6'
Makefile:11064: recipe for target 'check-TESTS' failed
make[2]: **\* [check-TESTS] Error 2
make[2]: Leaving directory '/home/zeeshan/Downloads/ImageMagick-7.0.2-6'
Makefile:11276: recipe for target 'check-am' failed
make[1]: **\* [check-am] Error 2
make[1]: Leaving directory '/home/zeeshan/Downloads/ImageMagick-7.0.2-6'
Makefile:11279: recipe for target 'check' failed
make: **\* [check] Error 2

**Comment by mikayla-grace** [comment]
We can't help unless we know why the unit tests failed.  You need to identify which test failed and then find the failure in the log, for example, tests/validate-formats-memory.log.
