### ISSUE TITLE
magickwand org  dead domain

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#2431]
http://www.magickwand.org

> Buy this domain The domain magickwand.org may be for sale by its owner!

Not sure what the status is of that extension, but maybe remove the link from: https://imagemagick.org/script/develop.php#php

> MagickWand for PHP a native PHP-extension to the ImageMagick MagickWand API.

**Comment by urban-warrior** [comment]
> Not sure what the status is of that extension, but maybe remove the link from

The link has been removed.

**Comment by Danack** [comment]
Thanks.

But fyi, the formatting of the page is weird now, with titles on the right after the PHP one.
