### ISSUE TITLE
Enable AVIF write support in Windows builds

### ISSUE THREAD

**Issue by lapo-luchini** [ImageMagick/ImageMagick#2442]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
AVIF (and HEIC) support is only enabled in decoding, not as an encoder.

### Steps to Reproduce
```
% wget 'https://imagemagick.org/download/binaries/ImageMagick-7.0.10-28-portable-Q16-HDRI-x64.zip'
% (extract)
% ./magick-7.0.10-28-portable-Q16-HDRI-x64.exe -list format | egrep -i 'avif|heic'
     AVIF* r--   AV1 Image File Format (1.7.0)
     HEIC* r--   High Efficiency Image Format (1.7.0)
```
(same for the non-HDRI version)

### System Configuration

- ImageMagick version: 7.0.10-28
- Environment (Operating system, version and so on): Windows 10 64 bit

**Comment by dlemstra** [comment]
Support for writing AVIF will become available in the next release. Support for HEIC would require the use of the x264 library and we cannot use that due to the fact that it uses a GPL license.

**Comment by lapo-luchini** [comment]
Yay for AVIF soon!
(I stopped caring about HEIC the moment I read about AVIF)

**Comment by lapo-luchini** [comment]
Nice!

```
% ./magick-7.0.10-29-portable-Q16-HDRI-x64.exe -list format | egrep -i 'avif|heic'
     AVIF* rw+   AV1 Image File Format (1.7.0)
     HEIC* rw+   High Efficiency Image Format (1.7.0)
```
