### ISSUE TITLE
Artifacts when resizing an animated GIF image

### ISSUE THREAD

**Issue by kleisauke** [ImageMagick/ImageMagick#2450]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Artifacts when resizing an animated GIF image with transparent background.

### Steps to Reproduce
```bash
wget https://cloudflare-ipfs.com/ipfs/QmZNDGswJPdxrrTkiTfarwSAgRtFh7nMFwsQgUxD5UjeRu/24LA_Wizard.gif

# IM 7
magick convert -resize 326x 24LA_Wizard.gif x.gif

# IM 6
convert -resize 326x 24LA_Wizard.gif x2.gif
```
(also tried the `-coalesce`  and `-deconstruct` option, but it generates similar results)

**ImageMagick 7.0.10-28**
![x](https://user-images.githubusercontent.com/12746591/90881513-9d3a2380-e3aa-11ea-8a66-5321add14b5e.gif)

**ImageMagick 6.9.11-28**
![x2](https://user-images.githubusercontent.com/12746591/90881545-adea9980-e3aa-11ea-9194-b032c94a6262.gif)

### System Configuration
- ImageMagick version: 7.0.10-28 / 6.9.11-28.
- Environment: Fedora release 32 (Thirty Two).
- Additional information: ImageMagick was installed from [Remi's RPM repository](https://rpms.remirepo.net/).

Downstream issue: https://github.com/weserv/images/issues/240.

**Comment by snibgo** [comment]
> magick convert -coalesce -resize 326x 24LA_Wizard.gif out%05d.png

Try again, with the operations in the correct order: read the frames, then process them, than write them:
```
magick convert 24LA_Wizard.gif -coalesce -resize 326x wiz_%05d.png
```
Does the problem still occur?

Incidentally, for v7, I suggest you use just "magick", not "magick convert". Then IM will point out that the operations are in the wrong order.

**Comment by kleisauke** [comment]
Ah, you're right. Here are the results when doing the operations in the correct order:

| IM 6.9.11.28 | IM 7.0.10.28 |
| :---: |  :---: |
| ![x](https://user-images.githubusercontent.com/12746591/91969459-67842b80-ed16-11ea-8fbf-0d6e0e740443.gif) | ![x](https://user-images.githubusercontent.com/12746591/91969588-a31ef580-ed16-11ea-960b-ddf95aa9a47b.gif) |
| ```convert 24LA_Wizard.gif -coalesce -resize 326x x.gif``` | ```magick 24LA_Wizard.gif -coalesce -resize 326x x.gif``` |

So the only issue remaining is those black artifacts on IM 6, which is possibly the same issue as the one reported in https://github.com/ImageMagick/ImageMagick/issues/2491.

A diff between these images with `giftext -c` reveals that the global color map and the transparent indexes written by IM 7 are different from those written by IM 6, I'll look into that further.

**Comment by kleisauke** [comment]
After doing a `git bisect`, I can conclude that this bug seems to have been introduced in ImageMagick 6.9.10-78. First bad commit:
https://github.com/ImageMagick/ImageMagick6/commit/dc8de5da60f0c0c401d7b8759ff4841d220bd838

Reverting that commit also resolves https://github.com/ImageMagick/ImageMagick/issues/2491.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
