### ISSUE TITLE
Unsupported DDS image when compression is Dxt10

### ISSUE THREAD

**Issue by codecat** [ImageMagick/ImageMagick#2451]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I try to convert dds textures using [Dxt10](https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-header-dxt10) with ImageMagick, it refuses to load them.

```
» magick convert 5ef7825d6a479.dds test.png
convert: image type not supported `/Users/nimble/Downloads/5ef7825d6a479.dds' @ error/dds.c/ReadDDSImage/1767.
```

[Link to example file](http://trackmania-prod-nls-file-store-s3.mdc.akamaized.net/club/25/screen_2x1/5ef7825d6a479.dds).

This seems to be due to the fact that the DX10 compression is unsupported: https://github.com/ImageMagick/ImageMagick/blob/9191334d4e18f1f9c79f242278ba2df785dc0f09/coders/dds.c#L1741-L1768

### Steps to Reproduce
```
$ wget http://trackmania-prod-nls-file-store-s3.mdc.akamaized.net/club/25/screen_2x1/5ef7825d6a479.dds
$ magick 5ef7825d6a479.dds test.png
```

### System Configuration
- ImageMagick version: `7.0.10-28 Q16 x86_64 2020-08-16`
- Environment (Operating system, version and so on): MacOS 10.15.6 & Ubuntu 20.04

**Comment by dlemstra** [comment]
Could you the `.dds` file to this issue @codecat? You will need to zip it before you can add it here. Some work is being done on support for DXT10 and I want to check if your file works with that patch but the link is no longer available.

**Comment by codecat** [comment]
Here's an image:

[5f62256170bf3.zip](https://github.com/ImageMagick/ImageMagick/files/7110414/5f62256170bf3.zip)

Interesting to note is that Paint DotNet loads this image mirrored vertically. Not sure if this is a quirk of the software or just the relevant image.

**Comment by codecat** [comment]
I just tested @SubhadeepG's implementation as of 7.1.0-7 on the file attached above, and this is the result:

![test](https://user-images.githubusercontent.com/136534/133175784-dae982ba-a7c9-41b1-b6be-cd5adc8ab79d.png)

There's a lot of artefacting happening here, which doesn't seem right.

**Comment by fmw42** [comment]
What was your ImageMagick command!  Did the same happened with previous versions of ImageMagick or in ImageMagick 6?

**Comment by codecat** [comment]
In prior versions, DXT10 was not supported, so it just threw an error. The exact command I used was:

```
magick https://trackmania-prod-nls-file-store-s3.cdn.ubi.com/club/screen_2x1/5f62256106a48.dds?updateTimestamp=1600267617.dds test.png
```

**Comment by fmw42** [comment]
Looks OK to me with IM 7.1.0.7 on Mac OSX

`magick DDS:5f62256170bf3.dds result.png`

![result](https://user-images.githubusercontent.com/13458218/133176787-9d17649f-5c25-45c6-999b-c8d7dff614b4.png)

**Comment by SubhadeepG** [comment]
The bug mentioned by @codecat was not present when I tested the code a few days ago. I did not see any kind of artefacts.

This bug was introduced by @dlemstra when he was renaming a bunch of variables in commit ImageMagick/ImageMagick@6d56ce1. He replaced variable alpha_bits with color_bits in two locations.

I will submit a pr soon to fix this bug.

**Comment by dlemstra** [comment]
Can you check this again @codecat?

**Comment by codecat** [comment]
Looks great on 7.1.0-8! Thanks for the fix! 🎉
