### ISSUE TITLE
Build only libraries

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#246]
Is there a configure option to only build the libraries (`libMagick++-6.Q16.a`, `libMagick++-6.Q16.6.dylib`, `libMagickWand-6.Q16.2.dylib`, `libMagickWand-6.Q16.a`, etc) but not command line utilities and other stuff?

**Comment by mikayla-grace** [comment]
Tell 'make' to only build the libraries: ```make Magick++/lib/libMagick++*.la```.

**Comment by jeroenooms** [comment]
That's not always practical for packaging. A `--disable-utils` configure argument would be better.

**Comment by rudchenkos** [comment]
Hi @jeroen 
It seems what you want is implemented here: https://github.com/ImageMagick/ImageMagick/commit/6ac3723062
