### ISSUE TITLE
Broken images after AVIF conversion

### ISSUE THREAD

**Issue by SoftCreatR** [ImageMagick/ImageMagick#2469]
I don't know, if this is a IM issue, but AVIF images don't convert properly to other formats. IM identifies the image as 8-bit, while it's actually 10-bits. This also happens on 12-bits images.

Example file: https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Netflix/avif/cosmos_frame01000_yuv420_10bpc_bt2020_pq_qlossless.avif

Expected result:

![cosmos_frame01000_yuv420_10bpc_bt2020_pq_qlossless](https://user-images.githubusercontent.com/81188/91352667-70db3880-e7ea-11ea-821e-d182f6c1b52d.jpg)

Actual result:

```bash
$ convert -verbose cosmos_frame01000_yuv420_10bpc_bt2020_pq_qlossless.avif cosmos_frame01000_yuv420_10bpc_bt2020_pq_qlossless.jpg
cosmos_frame01000_yuv420_10bpc_bt2020_pq_qlossless.avif AVIF 2048x858 2048x858+0+0 8-bit YCbCr 0.390u 0:00.400
cosmos_frame01000_yuv420_10bpc_bt2020_pq_qlossless.avif=>cosmos_frame01000_yuv420_10bpc_bt2020_pq_qlossless.jpg AVIF 2048x858 2048x858+0+0 8-bit YCbCr 1.12519MiB 0.070u 0:00.076
```

![cosmos_frame01000_yuv420_10bpc_bt2020_pq_qlossless](https://user-images.githubusercontent.com/81188/91352581-5012e300-e7ea-11ea-9eba-aceae9991526.jpg)

I've tested the same file on https://kagami.github.io/avif.js and conversion works just fine here.

**Comment by SoftCreatR** [comment]
Quick update: If I convert a JPEG file to AVIF and then back to JPEG, the result is fine.

```bash
$ convert -verbose cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50.jpg cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50.avif
cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50.jpg JPEG 2048x858 2048x858+0+0 8-bit sRGB 182247B 0.030u 0:00.024
cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50.jpg=>cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50.avif JPEG 2048x858 2048x858+0+0 8-bit YCbCr 13598B 7.240u 0:07.292

$ convert -verbose cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50.avif cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50-2.jpg
cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50.avif AVIF 2048x858 2048x858+0+0 8-bit YCbCr 0.120u 0:00.123
cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50.avif=>cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50-2.jpg AVIF 2048x858 2048x858+0+0 8-bit YCbCr 174263B 0.050u 0:00.046
```

Result:

![cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50-2](https://user-images.githubusercontent.com/81188/91311183-1377c500-e7b3-11ea-8e7b-af6fb1d3749c.jpg)

**Comment by SoftCreatR** [comment]
Probably relates to #2415 

Maybe useful to know:

```bash
$ identify -version
Version: ImageMagick 7.0.10-28 Q16 x86_64 2020-08-25 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr lzma openexr pangocairo png tiff webp wmf x xml zlib
```

Built with libheif 1.7.0 and aom 2.0.0.

**Comment by dlemstra** [comment]
Starting with libheif `1.7.0` there is an option called `convert_hdr_to_8bit` added to the decoder. With this option set we get the correct output. This option will be set in the next release of ImageMagick and we will at a later moment try to get support for reading 10 bit and convert the value to the Quantum depth.
