### ISSUE TITLE
Default policy.xml

### ISSUE THREAD

**Issue by dongkangli** [ImageMagick/ImageMagick#247]
I get this error when calling TextClip in moviepy: "convert: not authorized `@/tmp/tmpmiit2yoh.txt' @ error/property.c/InterpretImageProperties/3307."
And solved this problem by commenting out 
in policy.xml.
How can I solve this problem without modifying policy.xml

**Comment by mikayla-grace** [comment]
Commenting out the policy is the only way to permit indirect reads with ImageMagick.
