### ISSUE TITLE
Undercolor box is misaligned with text

### ISSUE THREAD

**Issue by dalanicolai** [ImageMagick/ImageMagick#2471]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When drawing text, the undercolor is misaligned with the text, see image:
![image](https://user-images.githubusercontent.com/18429791/91386488-62fdd580-e833-11ea-9f77-770fcecc4d9f.png)

### Steps to Reproduce
- (Optionally create blank pdf: `convert xc:none -page Letter a.pdf`)
- Draw text incl. undercolor (e.g the command as used in Emacs's pdf-tools: `convert a.pdf -pointsize 18.34 -undercolor DarkOrange3 -fill 'green' -draw "text 156.083888,169.565215 'AA'" test.pdf`)

### System Configuration
Fedora 32
Version: ImageMagick 7.0.10-29 Q16 x86_64 2020-08-27 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib djvu fontconfig freetype jng jp2 jpeg lcms lzma openexr pangocairo png tiff webp x xml zlib

(However I noticed the bug before upgrading, in Imagemagick version 6.9.11-27)

**Comment by fmw42** [comment]
Your command works fine for me on IM 7.0.10.28 Q16 Mac OSX Sierra. I suspect that it is your default font, which may not have a good glyph definition.

**Comment by dalanicolai** [comment]
First of all, thanks for the quick and useful reply. Indeed the issue is solved by using a different font.

However some questions remain, so I will just give it a shot and post some remaining 'issues' here.

It would be great if ImageMagick could inform me about what fallback/default font it uses because I am on Fedora 32/Gnome 3 and I am not sure which 'system font' I should define. There is an option to set default fonts for documents in the Gnome tweak tool, but setting a different font there does not solve the issue. 
 
It would be great if someone could provide some more information about this, because I can not find much useful information on the web.

Thanks, again
