### ISSUE TITLE
TIF conversion to JPEG: no images defined

### ISSUE THREAD

**Issue by bvb-sc** [ImageMagick/ImageMagick#2472]
Hi,

### Description
We've noticed one of the commands we regularly use for converting from TIF to JPEG stopped working after an upgrade to the latest version of ImageMagick.

### Steps to Reproduce

1. Run the following command with the files attached to this ticket on the latest IM version:

`convert "/tmp/sample.tif"[1] -density 300 +profile icm,icc -profile "/tmp/profile.icc"   -alpha remove -background white -auto-orient "/tmp/output_p%03d.jpeg"`

2. You will see the following error:

`convert: no images defined '/tmp/output_p%03d.jpeg' @ error/convert.c/ConvertImageCommand/3282.`

### System Configuration

ImageMagick version: 7.0.10-28
OS: Windows 10
OS: Ubuntu Bionic 18.04
OS: Ubuntu Focal 20.04
Additional information: The command works up until version 7.0.10-0, breaks as of 7.0.10-1 and up.

[files.zip](https://github.com/ImageMagick/ImageMagick/files/5134873/files.zip)

**Comment by fmw42** [comment]
I get errors as well on IM 7.0.10.28 and IM 6.9.11.28. I can open the file fine in Photoshop. Identify works fine and indicated 3 layers, though I only see two in Photoshop.

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
