### ISSUE TITLE
compress JPEG2000 ignored if output filename extension ".jp2" is missing

### ISSUE THREAD

**Issue by AvrelVor** [ImageMagick/ImageMagick#2473]
The compression of a JPEG image into JPEG 2000 works well, except if the output filename has no extension ".jp2".
Even with the parameter "-compress JPEG2000" the output is a JPEG, not a JPEG 2000.

Converting a JPEG into JPEG2000 works well if the output has an extension ".jp2"
```
convert image.jpg -quality 30 converted.jp2
# correct conversion
identify converted.jp2
converted.jp2 JP2 2560x1920 2560x1920+0+0 8-bit sRGB 0.010u 0:00.000
```

An output filename without extension does not change the filetype, as expected :
```
convert image.jpg converted
# the file "converted"  is a JPEG
identify converted
converted JPEG 2560x1920 2560x1920+0+0 8-bit sRGB 1.12524MiB 0.000u 0:00.004
```
Adding the option "-compress JPEG2000" fails if the output filename is without extension.
The resulting image is the same JPEG as just above.
```
convert image.jpg -compress JPEG2000 converted
# the file "converted" is a JPEG, not a JPEG 2000
identify converted
converted JPEG 2560x1920 2560x1920+0+0 8-bit sRGB 1.12524MiB 0.010u 0:00.004
```
**System configuration**
Tested on the OS Debian 11 ("Bullseye") with ImageMagick 6.9 :
```
convert --version
Version: ImageMagick 6.9.11-24 Q16 x86_64 20200718 https://imagemagick.org
```

Why this bug report ?
Because this behaviour prevents from using ImageMagick as a filter between standard input and standard output, using the parameter "-". That is what I want to do in a Python script, with the function Popen :
```
def jpeg_to_jpeg2000(imagecontent,compression = 30):
	return Popen(["convert","-","-compress","compression","-"],stdin=PIPE,stdout=PIPE).communicate(imagecontent)[0]
```

**Comment by fmw42** [comment]
If you do not have an extension, then preface the file name by JP2:filename to ensure you have jp2 result

**Comment by snibgo** [comment]
As Fred says. Hence you can prefix an output "-" with "JP2:" thus: "JP2:-".

**Comment by AvrelVor** [comment]
Thank you very much for your prompt answers and your suggestion.
Using JP2:filename in a command line works well :

```
convert image.jpg -quality 30 JP2:converted
# the output file "converted" is a JPEG 2000 :
identify converted
converted JP2 2560x1920 2560x1920+0+0 8-bit sRGB 0.000u 0:00.001
ls -l converted
-rw-r--r-- 1 user user 574791 août  27 18:32 converted
```

With a weak factor of "-quality 30" the compression is impressive, half-size in this example.

The same syntax "JP2:" can be used for piping the output with "JP2:-", as I just have done in my Python script :

```
def jpeg_to_jpeg2000(imagecontent,compression = "30"):
	return Popen(["convert","-","-quality",compression,"JP2:-"],stdin=PIPE,stdout=PIPE).communicate(imagecontent)[0]
```
It works well, as a debug message shows when running in a terminal :
[5] 640×427, RGB [JPEG2000] → 83658 octets to 14767 octets

Despite the fact that the option "-compress JPEG2000" should be used when no information is supplied about the output type, the workaround 'JP2:" works well in any case, so the bug can be closed.

**Comment by snibgo** [comment]
You may be confusing two concepts. One is the file format for the output. The other is the compression method used within that file. Some file formats have a choice of compression methods.

The output file format comes from the file prefix. If none, then the file extension. If none, the first input format.

If you ask for an invalid combination of compression method and file format, IM will ignore your compression request.

True, if you don't explicitly ask for a file format but do ask for a compression method that is valid for only one file format, IM could guess that you want that file format. But (a) IM isn't that smart and (b) IM tries not to second-guess what the user really wants.

**Comment by khawar512** [comment]
The quality factor in below command is not working. Please help me
`convert test/images/kodim$i.png -quality $(($j*5)) test/JP2/kodim$i/`printf "%02d" $j`.JP2`
