### ISSUE TITLE
convert svg to png ignores display:none

### ISSUE THREAD

**Issue by SridharRamasami** [ImageMagick/ImageMagick#2482]
I am using convert to convert from an svg to png.  The svg has a few elements with display:none which should not appear in the png file.  However, they do appear.   

The svg image that I am using is here: https://toonclip.com/images/custom/adam.svg
The resulting png image is here: https://toonclip.com/images/custom/adam.png

**The command used is:**
convert adam.svg adam.png

**ImageMagick version:**  7.0.10-28 Q16 x86_64
**OS:** Ubuntu 18.04

When I run it locally on my machine, it converts correctly.
My local machine has:
**ImageMagick version:** 7.0.10-8 Q16 x86_64
**OS:** Ubuntu 18.04

Tips, pointers appreciated.  Also if more info is needed, please let me know.

**Comment by fmw42** [comment]
Works fine for me using IM 7.0.10.28 Q16 Mac OSX Sierra when ImageMagick is using Inkscape.  What SVG renderer are you using. ImageMagick can use Inkscape, RSVG delegate or its internal MSVG/XML renderer.  Inkscape will give the best results. When using IM 7, use magick not convert and not magick convert. Put -verbose in your command to see which renderer it is using.

**Comment by SridharRamasami** [comment]
Hi fmw42,
Thanks.  I ran it with verbose.  Output below.  How do I proceed?

magick -verbose adam.svg adam.png
'inkscape' '/tmp/magick-nyUzrK5-J_E_k70WhVuynQOVA1IOdPfI' --export-file='/tmp/magick-RF_2OZsROKAqFkZLHa6LJKh8yuQz5M6J.png' --export-dpi='96' --export-background='rgb(100%,100%,100%)' --export-background-opacity='1' > '/tmp/magick-Rm6v9DYm67ipPoHQIj1p0dHGtdN53pUS' 2>&1
mvg:/tmp/magick-UHTzTgvm9J38OpObxc-lNiPiUScd1f6Y=>/tmp/magick-UHTzTgvm9J38OpObxc-lNiPiUScd1f6Y MVG 400x670 400x670+0+0 16-bit sRGB 50799B 0.140u 0:00.136
adam.svg MVG 400x670 400x670+0+0 16-bit sRGB 50799B 0.000u 0:00.002
adam.svg=>adam.png MVG 400x670 400x670+0+0 16-bit sRGB 50799B 0.090u 0:00.093

**Comment by SridharRamasami** [comment]
Digging further, looks like I need to change/check delegates file.  However, there are numerous delegate.xml files.   Which one should I be working with?

/etc/ImageMagick-6/delegates.xml
/opt/ImageMagick-7.0.10-28/config/delegates.xml
/opt/ImageMagick-7.0.10-28/config/delegates.xml.in
/opt/ImageMagick-7.0.10-28/www/source/delegates.xml
/snap/inkscape/7821/etc/ImageMagick-6/delegates.xml
/usr/local/etc/ImageMagick-7/delegates.xml
/usr/local/share/doc/ImageMagick-7/www/source/delegates.xml
/var/www/ImageMagick-7.0.10-28/config/delegates.xml
/var/www/ImageMagick-7.0.10-28/config/delegates.xml.in
/var/www/ImageMagick-7.0.10-28/www/source/delegates.xml
root@hwsrv-540819:/var/www/toonclip/public/images/custom# nano /snap/inkscape/7821/etc/Imagick-6/delegates.xml

**Comment by SridharRamasami** [comment]
I reinstalled inkscape using apt-get and changed the delegate file
/usr/local/etc/ImageMagick-7/delegates.xml

It seems to be running fine now from the command line.  However calling it from PHP imagick its still having the old behavior.  Where to look?  Out of scope for this repo?

**Comment by snibgo** [comment]
"-verbose" will tell you which delegates.xml file is read by IM.

You posted:
```
magick -verbose adam.svg adam.png
'inkscape' '/tmp/magick-nyUzrK5-J_E_k70WhVuynQOVA1IOdPfI' ...
adam.svg MVG 400x670 400x670+0+0 16-bit sRGB 50799B 0.000u 0:00.002
adam.svg=>adam.png MVG 400x670 
```
This tells us that IM tried to use Inkscape, but failed, and used its internal MVG instead.

I suspect that inkscape isn't on your system path. When you type "inkscape" at the command line, or PHP, does it run? I suspect not.

**Comment by SridharRamasami** [comment]
snibgo thanks.

I reinstalled inkscape and it now woks correctly when used from the CLI.  However, from php its still having the old behavior.  Running 'inkscape' on the CLI gives
Nothing to do!
'which inkscape' gives me
/usr/bin/inkscape

I think you are right, PHP is not able to find inkscape.  How or where do I correct this?

**Comment by fmw42** [comment]
What did you use in your delegates.xml file?  Often you need to put the full path to inkscape in order for PHP to find delegates. This occurs with Ghostscript for example. This is the first time I have seen that with inkscape. But you can try that.

**Comment by snibgo** [comment]
I don't use PHP, but posts on IM forums suggest that PHP doesn't automatically use the same system path as logged-in users. There is is PHP setting somewhere for this.

**Comment by SridharRamasami** [comment]
Hello to all who helped and contributed.

Finally, here is what I did and got it working.  My version of incscape is 0.9, for which the delegates should have a value of --export-png.  I have 5 of these delegate.xml files.  I changed all of those values to --export-png and restarted apache2.  Things are now working fine.
Thanks again all.  Appreciate it.
