### ISSUE TITLE
inkscape commandline in delegates.xml

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#2489]
At least here (inkscape-1.0 on linux) has `--export-filename` parameter, not `--export-file` as stated in `delegates.xml`.

See [opensuse bug](https://bugzilla.suse.com/show_bug.cgi?id=1174272) for details.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
