### ISSUE TITLE
register' storage class specifier is deprecated

### ISSUE THREAD

**Issue by jeroenooms** [ImageMagick/ImageMagick#249]
```
/usr/local/include/ImageMagick-7/MagickCore/pixel-accessor.h:628:3: warning: 'register' storage class specifier is deprecated [-Wdeprecated-register]
  register ssize_t
```

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Can you confirm that this is resolved @jeroenooms ?
