### ISSUE TITLE
Possible Bug Saving to GIF in IM 6.9.11.28

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#2491]
The following command works fine in IM 7.0.10.28, but fails with artefacts in IM 6.9.11.28 Q16 Mac OSX Sierra

Input:

![tree](https://user-images.githubusercontent.com/13458218/91778100-67651e00-eba6-11ea-8884-10ce85b6fac5.png)

`magick tree.png -background transparent -rotate 10 result7.gif`

![result7](https://user-images.githubusercontent.com/13458218/91778119-7055ef80-eba6-11ea-87e6-2c6ae981f0e2.gif)

`convert tree.png -background transparent -rotate 10 result6.gif`

![result6](https://user-images.githubusercontent.com/13458218/91778140-86fc4680-eba6-11ea-9c3f-141b16b93bc5.gif)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
