### ISSUE TITLE
Regression: converting multi layered TIFF to PNG

### ISSUE THREAD

**Issue by axeld** [ImageMagick/ImageMagick#2500]
Tested with ImageMagick 7.0.10-28 x64 Q16/Q8.
The attached image produces an empty image using the following command:

`magick.exe convert -size 100x51 canvas:none exit-graffiti.tif[1-2] -background none -layers merge +repage output.png`

At least 7.0.8-8 (Q16) does produce the expected output. Both tested under Windows 10 x64.

[exit-graffiti.zip](https://github.com/ImageMagick/ImageMagick/files/5166915/exit-graffiti.zip)

**Comment by dlemstra** [comment]
Thanks for reporting this. This issues was also reported here: #2472. This will be resolved in the next release.

**Comment by axeld** [comment]
Thanks! Sorry that I missed the original ticket; I only searched for "TIFF" and "regression" instead of TIF :-/
At least you now have another test case to play with...
