### ISSUE TITLE
Possible Bug in PDF encoder

### ISSUE THREAD

**Issue by emcconville** [ImageMagick/ImageMagick#2503]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When generating a PDF with ImageMagick, the resulting document may have incompatible ICC profile issues that may prevent ghostscript from future decoding.

### Steps to Reproduce
Take the following example:

    magick input.pdf - | magick - -alpha Off output-page%02d.png

Which will generate the following error:

> ```
>    **** Error: ICCbased space /N value does not match the ICC profile.
>                 Using the number of channels from the profile.
>                 Output may be incorrect.
> ```

The output image looks to have each RGB channel rendered side-by-side. Almost as if a interlace(?) was misread.

![output00](https://user-images.githubusercontent.com/84594/92107113-e165f480-edaa-11ea-9731-b2eaa8fe8b72.jpg)

Note that the following works as expected:

    cat input.pdf | magick - -alpha Off output-page%02d.png

But the issue will occur when writing to a file:

    magick input.pdf temp.pdf
    magick temp.pdf -alpha off output-page%02.png

### System Configuration

- ImageMagick version: 7.0.10-28 (clang w/ modules)
- Environment (Operating system, version and so on): Fedora Linux 32
- Additional information: Ghostscript 9.52

### Additional

This behavior has also been identified with ImageMagick 6.9.11-17
[input.pdf](https://github.com/ImageMagick/ImageMagick/files/5168219/input.pdf)

**Comment by snibgo** [comment]
> magick input.pdf - | magick - -alpha Off output-page%02d.png

What do you intend this command to do? The output of the first "magick" will be in PDF format, because you haven't said otherwise. But reading a PDF (with Ghostscript), splitting it into individual pages, writing each into another PDF, then re-reading each individual PDF (with Ghostscript) again, ... that's a load of work that make no sense.

**Comment by emcconville** [comment]
True. The above was the most minimal example I could craft. The real-world test cases is reading a PDF from stdin, and the potential bug seems to be present if the blob-data was previously generated by ImageMagick.

**Comment by snibgo** [comment]
Okay. With v7.0.10-27 and Ghostscript 9.19 on Windows 8.1, with your input.pdf, that command gives me no errors.

The message seems to come from Ghostscript, not IM. To pin down the problem, does it come from the call to GS from the first magick, or the second?

**Comment by emcconville** [comment]
Yes, the error message comes from ghostscript when reading in (second command). I'm assuming that the message is accurate.

**Comment by snibgo** [comment]
That suggests IM is generating something in a PDF that Ghostscript doesn't like. Your GS is v9.52, which is far more recent than I have. Can you test this with an older version of GS?

A developer may test this with GS 9.52, and comment.

**Comment by fmw42** [comment]
I tested with GS 9.50 and it fails there also

**Comment by emcconville** [comment]
Works as expected with GS v9.19, but fails with GS v9.20 & v9.25. Only difference I can see is that v9.19 doesn't emit ICC profile from original document. Latter versions of ghostscript yield the ICC profile to ImageMagick; which in turn, passes the profile through to the PDF encoder. 

Following the `ICCbased` error message, it looks like the error is caused by `/N 1` & `/DeviceGray` being paired with a sRGB ICC profile. Ghostscript's behavior sides with the profile, so a fix _really_ is just to updated the image type.

    magick input.pdf -type TrueColor - | magick - -alpha Off output-page%02d.png

Works as intended.

So, probably not a bug, or am I way off here?
