### ISSUE TITLE
SVG regression between  6.8.9-9 and upstream

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#251]
Hi,

display magick.svg as a white background with newer imagemagick version whereas it is transparent for older one....

Seems like a regression.

I usually use convert svg -background none -define filter:blur=0.75 -filter Gaussian -size 128x128 -gravity center -extent 128x128 icon.png to create icons and it fail now with a white background.

I could work arround using  convert -background none file.svg -background none -define filter:blur=0.75 -filter Gaussian -size 128x128 -gravity center -extent 128x128 icon.png but it is ugly

**Comment by dlemstra** [comment]
Are you using an SVG delegate or are you using our own SVG reader?

**Comment by bastien-roucaries** [comment]
I use exactly the same configure line. This is for packaging new debian package

**Comment by dlemstra** [comment]
What is the output from `convert -list format | grep -i svg` ?

**Comment by bastien-roucaries** [comment]
Working version:
 convert -list format |grep -i svg
     MSVG  SVG       rw+   ImageMagick's own SVG internal renderer
      SVG  SVG       rw+   Scalable Vector Graphics (XML 2.9.3)
     SVGZ  SVG       rw+   Compressed Scalable Vector Graphics (XML 2.9.3)
Non working
    MSVG  SVG       rw+   ImageMagick's own SVG internal renderer
      SVG  SVG       rw+   Scalable Vector Graphics (XML 2.9.4)
     SVGZ  SVG       rw+   Compressed Scalable Vector Graphics (XML 2.9.4)

**Comment by mikayla-grace** [comment]
Can you post a URL to the source SVG image? We tried MSVG against our SVG unit tests and they returned proper renderings with the latest ImageMagick release, 6.9.5-7.

**Comment by bastien-roucaries** [comment]
http://sources.debian.net/src/imagemagick/8:6.9.2.10%2Bdfsg-2/debian/display-im6.svg/

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Is your issue resolved @bastien-roucaries ?

**Comment by bastien-roucaries** [comment]
This one is not solved

Le 10 septembre 2016 00:46:46 GMT+02:00, Dirk Lemstra <notifications@github.com> a écrit :
>Is your issue resolved @bastien-roucaries ?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ImageMagick/ImageMagick/issues/251#issuecomment-246061635

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
