### ISSUE TITLE
Converting an animated GIF destroys the frames of the gif

### ISSUE THREAD

**Issue by kevinleesmith** [ImageMagick/ImageMagick#2514]
### Prerequisites

- [ x] I have written a descriptive issue title
- [ x] I have verified that I am using the latest version of ImageMagick
- [ x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
in.gif is an animated gif. I am trying to covert it (the same way I convert pngs) ro 

### Steps to Reproduce
magick "in.gif" -colorspace HSV   -channel 0 -evaluate set 6.389%    -colorspace sRGB out.gif"

### System Configuration
win10

**Comment by fmw42** [comment]
Is the gif animated? If not, then your command should work. Post an example input GIF and your resulting output GIF and describe what is not working?

**Comment by snibgo** [comment]
> in.gif is an animated gif.

Your animated GIF may be compressed, so each frame contains only deltas. Try "-layers coalesce" after reading the input.

**Comment by kevinleesmith** [comment]
Manby thanks all. It seems in my rush to implement the colourwash functionality, I broke my functionality that greated the base animated gifs! Now I fixed that, the colourwash command is working fine!!!
