### ISSUE TITLE
Raspbian reports an error when using the 'convert'

### ISSUE THREAD

**Issue by SilveryStar** [ImageMagick/ImageMagick#2515]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I running `magick test.svg test.png` on my machine, the terminal gives the following error:
`magick: no images for write '-write' 'test.png' at CLI arg 2 @ error/operation.c/CLINoImageOperator/4861.`

When I running `magick convert test.svg test.png` or `convert test.svg test.png` on my machine, the terminal gives the following error:
`convert: no images defined 'test.png' @ error/convert.c/ConvertImageCommand/3285.`

### Steps to Reproduce
`test.svg` included
```
<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="2.256ex" height="2.343ex" style="vertical-align: -0.338ex;" viewBox="0 -863.1 971.3 1008.6" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" aria-labelledby="MathJax-SVG-1-Title">
<title id="MathJax-SVG-1-Title">e Superscript x</title>
<defs aria-hidden="true">
<path stroke-width="1" id="E1-MJMATHI-65" d="M39 168Q39 225 58 272T107 350T174 402T244 433T307 442H310Q355 442 388 420T421 355Q421 265 310 237Q261 224 176 223Q139 223 138 221Q138 219 132 186T125 128Q125 81 146 54T209 26T302 45T394 111Q403 121 406 121Q410 121 419 112T429 98T420 82T390 55T344 24T281 -1T205 -11Q126 -11 83 42T39 168ZM373 353Q367 405 305 405Q272 405 244 391T199 357T170 316T154 280T149 261Q149 260 169 260Q282 260 327 284T373 353Z"></path>
<path stroke-width="1" id="E1-MJMATHI-78" d="M52 289Q59 331 106 386T222 442Q257 442 286 424T329 379Q371 442 430 442Q467 442 494 420T522 361Q522 332 508 314T481 292T458 288Q439 288 427 299T415 328Q415 374 465 391Q454 404 425 404Q412 404 406 402Q368 386 350 336Q290 115 290 78Q290 50 306 38T341 26Q378 26 414 59T463 140Q466 150 469 151T485 153H489Q504 153 504 145Q504 144 502 134Q486 77 440 33T333 -11Q263 -11 227 52Q186 -10 133 -10H127Q78 -10 57 16T35 71Q35 103 54 123T99 143Q142 143 142 101Q142 81 130 66T107 46T94 41L91 40Q91 39 97 36T113 29T132 26Q168 26 194 71Q203 87 217 139T245 247T261 313Q266 340 266 352Q266 380 251 392T217 404Q177 404 142 372T93 290Q91 281 88 280T72 278H58Q52 284 52 289Z"></path>
</defs>
<g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)" aria-hidden="true">
 <use xlink:href="#E1-MJMATHI-65" x="0" y="0"></use>
 <use transform="scale(0.707)" xlink:href="#E1-MJMATHI-78" x="659" y="583"></use>
</g>
</svg>
```

### System Configuration

- ImageMagick version: 
```
pi@raspberrypi:~ $ magick -version
Version: ImageMagick 7.0.10-28 Q16 aarch64 2020-09-06 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): freetype jng jpeg png zlib
```
- Environment (Operating system, version and so on):
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux
```
- Additional information:
`.svg` file is rendered by the project [mathjax-node-cli](https://github.com/mathjax/mathjax-node-cli), I used the command `~/node_modules/bin/tex2svg "e^x" > test.svg` to render this file

**Comment by fmw42** [comment]
Post your svg file. You may need to zip it first.  Also I note you have minimal delegates. I would suggest you install Inkscape for ImageMagick to use to render your SVG file.

**Comment by SilveryStar** [comment]
> Post your svg file. You may need to zip it first. Also I note you have minimal delegates. I would suggest you install Inkscape for ImageMagick to use to render your SVG file.

oh, thank! I ignored the inkspace tool before, now it can run smoothly!
