### ISSUE TITLE
MSVG regression between 6.8.9-9 and upstream

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#252]
Now another regression using classical magick svg

exact same line convert MSVG:../*.svg -background none -define filter:blur=0.75 -filter Gaussian -resize 128x128 -gravity center  file.png
![good](https://cloud.githubusercontent.com/assets/4839964/17809215/4b97550a-6615-11e6-9cb1-0a36d02438a5.png)

![bad](https://cloud.githubusercontent.com/assets/4839964/17809208/40d9b072-6615-11e6-87ca-9e03a32d73bb.png)

.png

**Comment by mikayla-grace** [comment]
Can you post a URL to the source SVG image?  We tried MSVG against our SVG unit tests and they returned proper renderings with the latest ImageMagick release, 6.9.5-7.

**Comment by bastien-roucaries** [comment]
http://sources.debian.net/src/imagemagick/8:6.9.2.10%2Bdfsg-2/debian/display-im6.svg/

Note that I use imagemagick 6

**Comment by bastien-roucaries** [comment]
This is used for generating icons cache

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Is your issue resolved @bastien-roucaries ?

**Comment by bastien-roucaries** [comment]
Le 10 septembre 2016 00:47:04 GMT+02:00, Dirk Lemstra <notifications@github.com> a écrit :
>Is your issue resolved @bastien-roucaries ?

This one yes
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
