### ISSUE TITLE
FFmpeg builds used in ImageMagick will be removed by Sept. 18, 2020 

### ISSUE THREAD

**Issue by co-da** [ImageMagick/ImageMagick#2524]
@dlemstra has said 
> We are using the official binaries and don't build them ourselves. We download them from here: https://ffmpeg.zeranoe.com/builds/.

But that Build site says:
> "ffmpeg.zeranoe.com will close on Sep 18, 2020, and all builds will be removed. If you're using Zeranoe FFmpeg Builds in your product, please ensure that you have a hosting strategy in place by the 18th. Thank you to everyone who supported the project along the way!"

I'm posting since I didn't see anything about it when I did a quick search. Disregard if the issue has already been addressed.

**Comment by urban-warrior** [comment]
Thanks for the heads up.  We will find an alternative site to download ffmpeg.
