### ISSUE TITLE
A memory leak in ReadMGKImage in www/source/mgk.c

### ISSUE THREAD

**Issue by ycdxsb** [ImageMagick/ImageMagick#2525]
- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

A memory leak issues in ReadMGKImage in `www/source/mgk.c` ,  though the code is for tutorial, a fix is still necessary for preventing others from using this code.

Below is the problem  in the latest version https://github.com/ImageMagick/ImageMagick/blob/master/www/source/mgk.c#Line255

```
	        /*
	          Allocate next image structure.
	        */
	        AcquireNextImage(image_info,image);
	        if (GetNextImageInList(image) == (Image *) NULL)
	          {
	            image=DestroyImageList(image);
	            return((Image *) NULL);
	          }
	        image=SyncNextImageInList(image);
```

a patch could be found here([`3b48d20`](https://github.com/ImageMagick/ImageMagick/commit/3b48d20df53ad048af05107aa1850c344466b082))

we could patch the code like below.

```patch
   254	        AcquireNextImage(image_info,image);
   255	        if (GetNextImageInList(image) == (Image *) NULL)
   256	          {
        -	        image=DestroyImageList(image);
   	-               return((Image *) NULL);
   257  +		status=MagickFalse;
   258  +		break;
   259	          }
   260	        image=SyncNextImageInList(image);

   ...
   
   269	  } while (count > 0);
   270	  (void) CloseBlob(image);
   271  + if (status == MagickFalse)
   272  +  return(DestroyImageList(image));
   273	  return(GetFirstImageInList(image));
   
```

### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
