### ISSUE TITLE
Three potential missing checks for the return value of function ReadBlobLSBLong and ReadBlobMSBShort before use it

### ISSUE THREAD

**Issue by ycdxsb** [ImageMagick/ImageMagick#2526]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

There are still three potential missing checks for the return value of function ReadBlobLSBLong and ReadBlobMSBShort, we should check it before use. Similar cases have been reported at  https://github.com/ImageMagick/ImageMagick/issues/1269 before.

Case 1: https://github.com/ImageMagick/ImageMagick/blob/master/coders/dcm.c#L3861

```
  3861	          length=(size_t) ReadBlobLSBLong(image);
  3862	          if (EOFBlob(image) != MagickFalse)
  3863	            {
  3864	              status=MagickFalse;
  3865	              break;
  3866	            }

 ...

  3885	          for (c=EOF; length != 0; length--)
  3886	          {
  3887	            c=ReadBlobByte(image);
```

Case 2: https://github.com/ImageMagick/ImageMagick/blob/master/coders/pict.c#L505

```
   504	    if (bytes_per_line > 200)
   505	      scanline_length=ReadBlobMSBShort(blob);
   506	    else
   507	      scanline_length=(size_t) ReadBlobByte(blob);
   508	    if ((scanline_length >= row_bytes) || (scanline_length == 0))
   509	      {
   510	        status=MagickFalse;
   511	        break;
   512	      }
```

Case 3:https://github.com/ImageMagick/ImageMagick/blob/master/coders/pict.c#L1085

```
  1083	                if (length > 200)
  1084	                  {
  1085	                    for (j=0; j < (ssize_t) ReadBlobMSBShort(image); j++)
  1086	                      if (ReadBlobByte(image) == EOF)
  1087	                        break;
  1088	                  }
```

### System Configuration

- ImageMagick version: ImageMagick-master-e009de151211ba311f31ae3d1579fe8df90116fb
- Environment (Operating system, version and so on)：macOS Catalina 10.15.6 + VS Code
- Additional information: code review

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
