### ISSUE TITLE
TIFF compression predictor default wrong for floating point

### ISSUE THREAD

**Issue by kmilos** [ImageMagick/ImageMagick#2527]
This is following up on https://github.com/ImageMagick/ImageMagick/issues/1144

Although it is possible to set tiff:predictor=3 manually, it should also be the default when the quantum is set to floating point. Currently, if no predictor is specified, it always defaults to 2 (horizontal difference for integer data), regardless of the quantum chosen.

For example:

`magick convert test.tif -depth 16 -define quantum:format=floating-point -compress zip test_half.tif`

results in predictor=2, and some apps/libs see the combo with floating point as invalid.

Alternatively, one could st the default predictor to 1 (no predictor) for both integer and floating point quantum (of course breaks compatibility with current behaviour).

**Comment by kmilos** [comment]
Furthermore, in the case of 32-bit floating point quantum

`magick convert test.tif -depth 32 -define quantum:format=floating-point -compress zip test_float.tif`

ends up with default of predictor=1 (no predictor), so it would be nice to make the behaviour consistent for all.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by kmilos** [comment]
Thanks, I can confirm I get the floating point predictor by default now for both 16 and 32-bit floating point quantum with IM 7.0.10.30
