### ISSUE TITLE
Possible bug -connected-components keep-ids

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#2539]
IM 7.0.10.29 and IM 6.9.11.29 Q16 Mac OSX Sierra.

**The bounding box extracted from CCL when using keep-ids sometimes shifts the WxH from id=0 (background) to the +X+Y for id to be kept.**

![objects](https://user-images.githubusercontent.com/13458218/92666920-66776f00-f2bf-11ea-9f22-4dc469919a6d.gif)

```
magick objects.gif \
-define connected-components:verbose=true \
-define connected-components:mean-color=true \
-connected-components 4 \
objects.png

Objects (id: bounding-box centroid area mean-color):
  0: 256x171+0+0 119.2,80.8 33117 srgb(0,0,0)
  2: 120x135+104+18 159.5,106.5 8690 srgb(255,255,255)
  3: 50x36+129+44 154.2,63.4 1529 srgb(0,0,0)
  4: 21x23+0+45 8.8,55.9 409 srgb(255,255,255)
  1: 4x10+252+0 253.9,4.1 31 srgb(255,255,255)

```

```
# id=2
magick objects.gif \
-define connected-components:keep-ids=0,2 \
-define connected-components:mean-color=true \
-connected-components 4 +write x2.png \
-format "%@" info:

120x135+104+18 <--- Correct, see bounding box of id=2 above

```

![x2](https://user-images.githubusercontent.com/13458218/92667290-6461e000-f2c0-11ea-9f5b-afac2865c2ad.png)

```
# id=3
magick objects.gif \
-define connected-components:keep-ids=0,3 \
-define connected-components:mean-color=true \
-connected-components 4 +write x3.png \
-format "%@" info:

magick: geometry does not contain image `' @ warning/attribute.c/GetImageBoundingBox/510.

0x0+256+171 <--- Wrong, see ID=3 above. Note that +256+171 comes from WxH of ID 0

```

![x3](https://user-images.githubusercontent.com/13458218/92667301-6d52b180-f2c0-11ea-981f-e724e8242516.png)

**Comment by urban-warrior** [comment]
Object id 3 is distinguished from object 0, the background, by its ID.  However, when you enable mean colors, it no longer can be distinguished by the bounding box algorithm as it has the same mean-color of the background, i.e. 0,0,0 or black.  Try mean-color=false and you will get the expected results:

```
$ magick objects.gif -define connected-components:verbose=true -define connected-components:keep-ids=0,3 -define connected-components:mean-color=false -connected-components 4 +write x3.png -format "%@" info:
Objects (id: bounding-box centroid area mean-color):
  0: 256x171+0+0 126.5,85.8 42247 srgb(0,0,0)
  3: 50x36+129+44 154.2,63.4 1529 srgb(0,0,0)
50x36+129+44
```

**Comment by fmw42** [comment]
Thanks. I completely overlooked that they had the same color.
