### ISSUE TITLE
ordered dither in v7.0.2

### ISSUE THREAD

**Issue by rostok** [ImageMagick/ImageMagick#254]
The recent version 7 of IM gives strange results when doing order dithering. The Posterized Ordered Dither Expansion example: `magick convert gradient.png -ordered-dither o8x8,6 od_o8x8_6.gif` yields just 2bpp bitmap.

input ![input](http://www.imagemagick.org/Usage/bugs/ordered-dither/gradient.png)
prefferred output ![prefferred output](http://www.imagemagick.org/Usage/bugs/ordered-dither/od_o8x8_6.gif)
actual output ![actual output](http://i.stack.imgur.com/kNjYs.gif)

**Comment by dlemstra** [comment]
This is indeed a bug in IM7 and I just pushed a patch to resolve this. We will release 7.0.3-4 later today.
