### ISSUE TITLE
Converting images AV1 / .avif fails

### ISSUE THREAD

**Issue by manniL** [ImageMagick/ImageMagick#2551]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I've tried converting several images of different types (jpg, png, webp) to avif and always receive the following error message:

> magick: Unsupported file-type: Unspecified `icon.avif' @ error/heic.c/IsHeifSuccess/134.

Output of `convert -verbose icon.png me.avif`:

```
icon.png PNG 512x512 512x512+0+0 8-bit sRGB 390912B 0.010u 0:00.014
icon.png=>me.avif PNG 512x512 512x512+0+0 8-bit sRGB 0.010u 0:00.008
convert: Unsupported file-type: Unspecified `me.avif' @ error/heic.c/IsHeifSuccess/134.
```

### System Configuration

- ImageMagick version: Version: ImageMagick 7.0.10-29 Q16 x86_64 2020-09-06
- Environment (Operating system, version and so on): macOS Catalina 10.15.6 19G73 x86_64
- Additional information: libheif: stable 1.8.0 (bottled), aom: stable 2.0.0 (bottled)

**Comment by dlemstra** [comment]
Are you sure that your `libheif` library is build with support for `aom`? You will get this message when the avif encoder could not be found.

**Comment by manniL** [comment]
> Are you sure that your `libheif` library is build with support for `aom`? You will get this message when the avif encoder could not be found.

You are right, I've re-installed `libheif` with `--verbose` and it seems it doesn't detect the lib though both, `rav1e` *and* `aom` are provided through homebrew. 🤔

```
configure: libaom decoder: no
configure: libaom encoder: no
configure: rav1e encoder: no
```

Not an ImageMagick issue so I'm closing here. I'm open for ideas how to solve this though 😋
