### ISSUE TITLE
Effects broken in IM7

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#256]
Several of the effects seem that are working in IM6 seem to be broken in IM7. I am using the C++ interface. Below my intro doc, it takes a while to load because all images are embedded.
- Rendered with Magick++ 6.9.5-4: [introduction to magic](https://rstudio-pubs-static.s3.amazonaws.com/204160_4c699d7c387448b1b13cdc74d1ae14c4.html)
- Rendered with Magick++ 7.0.2-7: [introduction to magic](https://rstudio-pubs-static.s3.amazonaws.com/204157_5a5008e08e9949978825bd1c9f7ffccd.html)

Note how the "charcoal" and "edge" and "negate" effects don't work in IM7.

**Comment by jeroen** [comment]
Just rechecked this with Magick++ 7.0.5-4 from homebrew, but these effects are still broken in IM7 :(

**Comment by dlemstra** [comment]
@jeroen Can you check again with the latest version?

**Comment by jeroen** [comment]
@dlemstra both drawing and effects are still broken in my places in IM7. I recommend all our users to install IM6. Perhaps we should sit together some time and track down these problems.

**Comment by dlemstra** [comment]
Sounds like a good plan. Have we shared Skype details yet? Lets message on twitter to talk about a moment to do that.

**Comment by jeroen** [comment]
OK I'm busy this week and next week vacation, but after that things clear up a bit.

**Comment by jeroen** [comment]
I'll open a few issues on IM7. I think one of the core problems is that the alpha scale has reversed in IM7 but a lot of code still assumes the old scale. Lot's of issues with transparency.

**Comment by dlemstra** [comment]
I will close this issue for now since this has moved to new separate issues.
