### ISSUE TITLE
This ImageMagick command no longer works (threshold) on png images after ImageTragick patch

### ISSUE THREAD

**Issue by goosehub** [ImageMagick/ImageMagick#257]
I have a command I use to use to monochrome (black and white) an image.

```
convert 'input.png' -threshold '50'% -transparent white 'output.png'
```

After the ImageTragick patch, I found that no longer worked and I needed to restructure my command like this.

```
convert 'input.png' -threshold '50'% -alpha off -transparent white 'output.png'
```

This should ideally be fixed because it may break software that depends on the previous syntax still working.

For more information, see my question on StackOverflow.

http://stackoverflow.com/questions/39167752/imagemagick-no-longer-works-with-threshold-parameters-on-png-images-after-imaget

**Comment by goosehub** [comment]
I found that my new command "convert 'input.png' -threshold '50'% -alpha off -transparent white 'output.png'" does seem to work consistently on 6.7.7-10. It'd be useful to have a monochrome command that works on both.

**Comment by dlemstra** [comment]
Can you clarify why you need the quotes? The following should work.
`convert input.png -threshold 50% -alpha off -transparent white output.png`

**Comment by goosehub** [comment]
Those quotes are the results of using escapeshellarg and escapeshellcmd in my code, but I have also tried without the quotes as in your example and gotten the same resulting behavior.

**Comment by dlemstra** [comment]
Which version are you using now?

**Comment by goosehub** [comment]
7.0.2-0, more information in this StackOverflow question

http://stackoverflow.com/questions/39167752/imagemagick-no-longer-works-with-threshold-parameters-on-png-images-after-imaget

**Comment by fmw42** [comment]
IM 7 is more strict about proper syntax. Replace convert with magick and put your input image right after magick. Does that work?

**Comment by goosehub** [comment]
I ran this command on a png, still receiving a blank image, received no errors from terminal. If it matters, I'm on Ubuntu 14.04.

    magick 'input.png' -threshold '50'% -transparent white 'output.png'

Same results when ran without quotes

    magick input.png -threshold 50% -transparent white output.png

**Comment by dlemstra** [comment]
The following should work for both IM6 and IM7:
```
convert input.png -alpha off -threshold 50% -transparent white output.png
```
