### ISSUE TITLE
ImageMagick fails to recognize the path for ghostscript version 9.53

### ISSUE THREAD

**Issue by trailblazer2006** [ImageMagick/ImageMagick#2571]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
ImageMagick fails to recognize the path for GhostScript version 9.53. Everything was fine for GS v9.52, but after upgrading to 9.53 I got the following error:
Error: Command failed: magick: FailedToExecuteCommand `"gswin64c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r100x100"  "-sOutputFile=E:/BuildAgent/temp/buildTmp/magick-zZ94lYVUwyxtE0i1jUQjfXTfqekSa8ps%d" "-fE:/BuildAgent/temp/buildTmp/magick-1x77Uhu_oAQmHYdb-xoVEnUrDIJbUzDK" "-fE:/BuildAgent/temp/buildTmp/magick-2427aXjCcOTiFluOHrOf032-OyQYv5EK"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/475.
magick: PDFDelegateFailed `The system cannot find the file specified.
' @ error/pdf.c/ReadPDFImage/660.
    at ChildProcess.onExit (E:\BuildAgent\work\5ba010db112a0af8\test\end2end\node_modules\gm\lib\command.js:301:17)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at ChildProcess.cp.emit (E:\BuildAgent\work\5ba010db112a0af8\test\end2end\node_modules\gm\node_modules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
   Error: Command failed: magick: FailedToExecuteCommand `"gswin64c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r100x100"  "-sOutputFil

### System Configuration

- ImageMagick version: ImageMagick-7.0.10-Q16-HDRI
- Environment (Operating system, version and so on): Windows 10 Enterprise 64-bit
- Additional information:

I made some investigations based on this issue https://github.com/ImageMagick/ImageMagick/issues/2180 and found that the registry key was changes in the GhostScript 9.53.
![image](https://user-images.githubusercontent.com/5860308/93106045-77a5ee80-f6b8-11ea-89b0-563b74a1aae1.png)
It might be a root of the problem. I tried to rename "9.53.0" to "9.53" manually and ImageMagick started working.

**Comment by dlemstra** [comment]
Thanks for reporting this. Our code expects the version to be `major.minor`. I just pushed a patch to add support for reading `major.minor.patch`. The next release will support both `major.minor` and `major.minor.patch`. You might want to change that registry key back after the release.
