### ISSUE TITLE
Regression: handling photoshop multi-layer TIFFs results in garbage

### ISSUE THREAD

**Issue by axeld** [ImageMagick/ImageMagick#2577]
Using the TIFF image in the attached ZIP archive:
[exit-graffiti.zip](https://github.com/ImageMagick/ImageMagick/files/5223537/exit-graffiti.zip)

When I process the file in ImageMagick 6.9.3-7 with the following call:
`convert -quiet -size 100x58 canvas:none exit-graffiti.tif[1-3] -background none -layers merge +repage -thumbnail '150x150>' png:result.png`
The result is as expected;
![result](https://user-images.githubusercontent.com/863699/93186741-46243600-f73f-11ea-80be-f78b482940ef.png)

However, the same call using ImageMagick 7.0.10-29 results in garbage:
`magick convert -quiet -size 100x58 canvas:none exit-graffiti.tif[1-3] -background none -layers merge +repage -thumbnail '150x150>' png:result-wrong.png`
![result-wrong](https://user-images.githubusercontent.com/863699/93186977-8be0fe80-f73f-11ea-8d3c-47024f862f5c.png)

**Comment by axeld** [comment]
Just to save you some searching, version 7.0.8-35 also produces the expected result.

**Comment by dlemstra** [comment]
Thanks for reporting this. When adding support for 32bit ZipWithPrediction we broke 8bit ZipWithPrediction. This issue will be resolved in the next release.

**Comment by dlemstra** [comment]
We just published a release where this is resolved.
