### ISSUE TITLE
"convert -density" is not attribute-only modification, as documentation claims.

### ISSUE THREAD

**Issue by duanemoody** [ImageMagick/ImageMagick#258]
http://www.imagemagick.org/script/command-line-options.php#density

> The -density option sets an attribute and does not alter the underlying raster image. 

The notable difference in resulting filesizes made me curious about this, so I decided to check. Here's the original image:![lena](https://cloud.githubusercontent.com/assets/159372/18030614/14b5325c-6c71-11e6-9446-746930adaa4d.jpg)
1. `convert -density 72x72 Lena.jpg Lena_72.jpg` yields this:
   ![lena_72](https://cloud.githubusercontent.com/assets/159372/18030615/2c62a72c-6c71-11e6-9fd1-268143b9be9c.jpg)
2. Open Lena.jpg and Lena_72.jpg in Photoshop and shift-drag Lena_72.jpg's layer to Lena.jpg
3. Change Lena_72.jpg's layer type from Normal to Difference; it will _appear_ black suggesting no difference but…
4. Create Threshold effects layer above this, set its Threshold Level to 1
5. Substantial artifacting and noise visible
   <img width="1250" alt="screen shot 2016-08-27 at 4 09 20 pm" src="https://cloud.githubusercontent.com/assets/159372/18030616/492e1ada-6c71-11e6-8b3c-6cb685fdd55b.png">

This looks like ImageMagick is doing more than just modifying the 0x011a/0x011b XResolution/YResolution EXIF tags ([or other ones](http://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html)) in the resulting JPEG.

I'm using ImageMagick 6.9.5-5 Q16 x86_64 2016-08-07 if that helps any.

**Comment by dlemstra** [comment]
When you convert from JPEG to JPEG it will always re-encode the image. If you just want to modify the EXIF information you might be better of using another tool.

**Comment by duanemoody** [comment]
If that's the case then the documentation needs to be more accurate about "and does not alter the underlying raster image" since that's clearly not the case here. And yes, I know exiftool can manipulate this data directly.
