### ISSUE TITLE
Too many bezier coordinates when drawing an ellipse

### ISSUE THREAD

**Issue by deanloew** [ImageMagick/ImageMagick#2581]
### Prerequisites

- [x ] I have written a descriptive issue title
- [x ] I have verified that I am using the latest version of ImageMagick
- [x ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
A search of all open and closed issues only reveals on "bezier" related bug, and that was with a rectangle some years back which a patch had been made for.

### Description

C# code under Visual Studio 2019 throws an exception "Too many bezier coordinates" on  image.Draw() call

### Steps to Reproduce

my_image.jpg:
![my_image](https://user-images.githubusercontent.com/53237069/93249294-b12d3700-f756-11ea-8ba4-87d52b99411d.jpg)

````C#
using System.Windows;
using ImageMagick;

namespace WpfApp1
{
	public partial class MainWindow : Window
	{
		public MainWindow()
		{
			InitializeComponent();

			MagickImage img = new MagickImage(@"S:\bezierBug\my_image.jpg");  //  <<-- This is an empty white jpg file, and is attached

			// ^^^^ img.Width is 3154px, and img.height is 2446px.  Blank 

			// this next line works (although it is close the right edge)
			img.Draw(new Drawables().Ellipse(3097, 652.82, 37, 37, 0, 360).FillColor(MagickColors.Black));

			// this next doesn't work: even though only .01 increase on y coordinate, and nowhere near bottom of image
			//img.Draw(new Drawables().Ellipse(3097, 652.83, 37, 37, 0, 360).FillColor(MagickColors.Black));  //  <<--  Dies with "too many bezier coordinates"

			// More examples
			Drawables d = new Drawables();
			d.Ellipse(250, 200, 37, 37, 0, 360);
			d.Ellipse(500, 500, 37, 37, 0, 360);
			d.Ellipse(1000, 1000, 37, 37, 0, 360);
			d.Ellipse(1500, 1500, 37, 37, 0, 360);
			d.Ellipse(2000, 2000, 37, 37, 0, 360);
			//d.Ellipse(2800, 1500, 37, 37, 0, 360);   <-- dies if I leave this in
			//d.Ellipse(2500, 2000, 37, 37, 0, 360); <-- dies if I leave this in

			img.Draw(d);     //  <<---- Dies with "too many bezier coordinates"

			img.Write(@"S:\bezierBug\my_image2.jpg");
			// output:
	
			//ImageMagick.MagickDrawErrorException
			//  HResult=0x80131500
			//  Message=too many bezier coordinates `fill' @ error/draw.c/RenderMVGContent/4112
			//  Source=Magick.NET-Q16-AnyCPU
			//  StackTrace:
			//   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception)
			//   at ImageMagick.DrawingWand.NativeDrawingWand.Render()
			//   at ImageMagick.DrawingWand.Draw(IEnumerable`1 drawables)
			//   at ImageMagick.MagickImage.Draw(IEnumerable`1 drawables)
			//   at ImageMagick.MagickImage.Draw(IDrawables`1 drawables)
			//   at WpfApp1.MainWindow..ctor() in S:\bezierBug\WpfApp1\WpfApp1\MainWindow.xaml.cs:line 21
		}
	}
}

````

### System Configuration

Windows 10, Visual Studio 2019,  Magick.NET-Q16-AnyCPU.7.21.1;  Magick.NET.Core.4.1.0; Magick.NET.SystemDrawing.2.0.3

AMD Ryzen processor; 32 gig ram on machine 

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
Our drawing code has some limits and it seems that you are hitting that limit. But this does look like there is some kind of bug in our calculation. I also noticed that it looks like you are trying to draw circles instead of elipses. When you do `d.Circle(2800, 1500, 37, 37)` the circle will be drawn on the image.

**Comment by deanloew** [comment]
Thanks, Dirk.

A couple of things, if this will help:

1.  Using the latest version (7.21), the circle example code you gave
 i*mg.Draw(new
Drawables().Circle(2800, 1500, 37, 37)); *    unfortunately does not work,
it makes a huge black circle which covers almost the entire page (see
attached).   I tried reverting to the version we had been using 7.17.0.1
and it does the same thing - a huge black circle.

2.  If I modify your suggestion slightly to this:    *img.Draw(new
Drawables().Circle( 2800, 1500, 1, 1));*   then the newest version 7.21
gives the same "too many bezier coordinates" error, but the 7.17.0.1 code
works, but makes the huge black circle.

3.  If I switch back to the old version 7.17.0.1, all  "too many bezier
coordinate "  problems seem to go away, but there are other bugs we are
trying to avoid (e.g.  Magick.Net is extremely slow with
multi-threading).   Arghh.

Thanks for all you do!
Dean

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by deanloew** [comment]
Wonderful!  Thank you so much.   I am afraid however, I do not understand
how to get the updated changes into Visual Studio.  Will the Nuget package
manager somehow indicate an updated package available?

**Comment by dlemstra** [comment]
You will need to wait for the next version of Magick.NET. I will try to publish a new release this weekend.

And to answer your other question: `Drawables().Circle(2800, 1500, 37, 37)` should be `Drawables().Circle(2800, 1500, 2800, 1537)` instead. I copy pasted the wrong example.

**Comment by deanloew** [comment]
Ah, okay, thank you.   Will try the new circles example.

**Comment by deanloew** [comment]
Hello Dirk.  Thank you for publishing a new version of Magick.Net, version
7.22.0

Unfortunately, with 7.22.0   and   Magick.Core 5.0    and    SystemDrawing
2.0.4    the dreaded no "ToBitmap()" error returns:

[image: image.png]

[image: image.png]

**Comment by dlemstra** [comment]
Could you response on GitHub instead of the email. The images are not attached when you reply through email.

**Comment by dlemstra** [comment]
Is this still an issue @deanloew?

**Comment by deanloew** [comment]
No, the latest version you released seems to have fixed this.   Thank you, and I am sorry to have not responded sooner.
