### ISSUE TITLE
Static linking on mingw-w64 fails for -std=gnu++11

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#259]
When I build my application with `-std=c++11` I can statically link Magick++. However my host is changing to `std-gnu++11` and now static linking fails with a lot of linking errors [full log](https://www.r-project.org/nosvn/R.check/r-devel-windows-ix86+x86_64/magick-00install.html).

```
attributes.o:attributes.cpp:(.text+0x569d): undefined reference to `_imp__CommandOptionToMnemonic'
edit.o:edit.cpp:(.text+0x11bf): undefined reference to `_imp__AcquireExceptionInfo'
edit.o:edit.cpp:(.text+0x11ce): undefined reference to `_imp__ReadImage'
edit.o:edit.cpp:(.text+0x11fd): undefined reference to `_imp__DestroyExceptionInfo'
edit.o:edit.cpp:(.text+0x1302): undefined reference to `_imp__AcquireExceptionInfo'
edit.o:edit.cpp:(.text+0x131e): undefined reference to `_imp__CoalesceImages'
edit.o:edit.cpp:(.text+0x138d): undefined reference to `_imp__DestroyExceptionInfo'
```

 I tried rebuilding Magick++ with `-std=gnu++11` but this did not solve the problem. Perhaps there is a bug in Magick++ include related to the use of `__GNUC__`.

Perhaps related: some other libraries have some C macro that the client can set to compiler for static linking. For example in libxml the client sets `-DLIBXML_STATIC` and the [xmlexports.h](https://github.com/rwinlib/libxml2/blob/v2.9.4/include/libxml2/libxml/xmlexports.h) include file has something like:

``` c
  #if defined(IN_LIBXML) && !defined(LIBXML_STATIC)
    #define XMLPUBFUN __declspec(dllexport)
    #define XMLPUBVAR __declspec(dllexport)
  #else
    #define XMLPUBFUN
    #if !defined(LIBXML_STATIC)
      #define XMLPUBVAR __declspec(dllimport) extern
    #else
      #define XMLPUBVAR extern
    #endif
  #endif
```

Note how libxml2 does not use `__GNU` anywhere. Do I need to do something similar for Magick++ ?

**Comment by jeroenooms** [comment]
OK I found that I can work around the problem by compiling the client with:

```c
CXXFLAGS= -D_LIB
```

However `-DSTATIC_MAGICK` does **not work** for mingw builds.

**Comment by dlemstra** [comment]
@jeroen Did you resolve this issue yet?

**Comment by jeroen** [comment]
Static linking my application via `-DSTATIC_MAGICK` still doesn't work. But I have been using `-D_LIB` for over a year now and that seems fine.

**Comment by dlemstra** [comment]
Have you tried `--enable-static=yes`?
