### ISSUE TITLE
ImageMagick don't recognize CSS custom variables when converting SVG to PNG 

### ISSUE THREAD

**Issue by schlebe** [ImageMagick/ImageMagick#2599]
### Description

Hello

My SVG file (truncated to have only interesting lines) contains following lines

```
<?xml version="1.0" encoding="UTF-8" ?>
<svg xmlns="http://www.w3.org/2000/svg" version="2.0" width="8000px" height="6000px">
  <script type="text/javascript" href="https://d3js.org/d3.v5.min.js"></script>
  <style type="text/css">

:root {
    --line-color: black;
    --line-width: 2;
    }

line, polyline, rect, circle, path {
    stroke-width: var(--line-width);
    stroke: var(--line-color);
    }
    
svg {
    margin:10px 20px;
    overflow:visible; 
	}

  </style>

<line x1='100' y1='50' x2='100' y2='90'/>
<text x ='110' y='70' fill='black' font-family='Arial' font-size='20'>Différenciel PRINCIPAL</text>
<text x ='110' y='100' fill='black' font-family='Arial' font-size='12'>&#x0394;300 mA</text>
<line x1='100' y1='130' x2='100' y2='170'/>
<line x1='100' y1='170' x2='100' y2='210'/>
<text x ='110' y='190' fill='black' font-family='Arial' font-size='20'>Différentiel SECONDAIRE</text>
<text x ='110' y='220' fill='black' font-family='Arial' font-size='12'>&#x0394;30 mA</text>
<line x1='100' y1='250' x2='100' y2='290'/>
<line x1='100' y1='290' x2='100' y2='330'/>
<text x ='110' y='310' fill='black' font-family='Arial' font-size='20'>A (5)</text>
<text x ='110' y='340' fill='black' font-family='Arial' font-size='12'>20A</text>

</svg>
```

The following ImageMagick command don't recognize **custom CSS variables** (--line-color and --line-width).

`convert Plan-Unifilaire.ATHUS.svg Plan-Unifilaire.ATHUS.png
`

Chrome, Opera, Firefox are displaying my SVG file correctly !

You can find some explanations on custom CSS variables on [https://www.w3schools.com/css/css3_variables.asp](https://www.w3schools.com/css/css3_variables.asp)

### Steps to Reproduce

Start ImageMagick with my SVG file using above convert command

During conversion process, ImageMagick display some warning messages.

A PNG file is generated but all lines have disappeared because custom CSS variables don't have been recognized.

### System Configuration

- ImageMagick version: -7.0.10-Q16 (64 bits)
- Environment (Operating system, version and so on): Windows 10

**Comment by snibgo** [comment]
See my answer to your other thread https://github.com/ImageMagick/ImageMagick/issues/2600
