### ISSUE TITLE
compare: width or height exceeds limit `img.png' @ error/cache.c/OpenPixelCache/3690.\n"

### ISSUE THREAD

**Issue by Gadzillion** [ImageMagick/ImageMagick#2606]
I'm trying to compare two images.

Version: ImageMagick 7.0.10-31 Q16 x86_64 2020-09-22
https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): jbig jng jpeg ltdl lzma png tiff x zlib
```
magick compare base.png new.png -metric RMSE -subimage-search -dissimilarity-threshold 1.0 diff.png
```

but i get

```
b"compare: width or height exceeds limit `base.png' @ error/cache.c/OpenPixelCache/3690.\n"
```

1. I changed the file "policy.xml"
2. I was using '-limit'

1. Resource limits: Width: 16000000P Height: 16000000P Area: 33.1224GP List length: unlimited Memory: 14GiB Map: 30GiB Disk: 30GiB File: 786432 Thread: 12 Throttle: 0 Time: unlimited 2. Size of base.png and new.png: ~3mb

**Comment by fmw42** [comment]
try this syntax

`magick compare -metric rmse -subimage-search -disimilarity-threshold 1 large_image small_image diff_image`

Note the large image comes before the small image. Also I put all settings before the images.

**Comment by Gadzillion** [comment]
@fmw42 Thank you, I'll try it tomorrow at my workstation and write results here.

**Comment by Gadzillion** [comment]
@fmw42 now its working in 3/10 cases

> Note the large image comes before the small image
Is this a prerequisite ? If yes, Then I have to determine the file size and place arguments in command line dynamically.

> The small image must be smaller in both dimension than that of the large image.
I'm trying to compare 2 screenshots of a page. How do I make them the same size ?

And now sometimes when comparing I get two images instead of one: diff-0.jpg, diff-1.jpg. 
diff-1.jpg - just a white line.

**Comment by fmw42** [comment]
Yes, it is required that the large image is first.

**Comment by Gadzillion** [comment]
@fmw42 thx, its kinda work now)
