### ISSUE TITLE
VisualMagick folder missing

### ISSUE THREAD

**Issue by hansmalherbe** [ImageMagick/ImageMagick#261]
Instructions in the file Install-windows.txt mentions the VisualMagick\configure folder.
I cannot find this folder. Even reverting the git history at various times back to 2009 does not produce this folder.

**Comment by dlemstra** [comment]
Are you trying to build from our git repository or are you downloading the source as documented? If you want to build using our git repository you should clone https://github.com/ImageMagick/ImageMagick-Windows and run CloneRepositories.cmd. This will create the VisualMagick folder that you are looking for.

**Comment by hansmalherbe** [comment]
Got it, thanks. Didn't release there were a repository for Windows.
