### ISSUE TITLE
PerlMagick Installation

### ISSUE THREAD

**Issue by ghunt8510** [ImageMagick/ImageMagick#2617]
I have installed ImageMagick on my Windows 10 machine and it seems to work. I can run command line scripts. I need to use ImageMagick inside of my Perl script, so I need PerlMagick. I selected the checkbox on the ImageMagick install to install PerlMagick. It seems to not have worked. I see in the installed directory(C:\Program Files\ImageMagick-7.0.10-Q16-HDRI\PerlMagick) that there is a readme.txt that says to run the Image-Magick.ppd file if PerlMagick didn't seem to install. When I run this file, it says "PPM functionality is being replaced by the State Tool, which does things differently.". Can anyone help me figure out how to get PerlMagick installed on my Windows 10 machine, so I can use ImageMagick in my Perl scripts? This shouldn't be this hard.....

**Comment by dlemstra** [comment]
Please don't open an issue for discussion that was already started here: https://github.com/ImageMagick/ImageMagick/discussions/2607

**Comment by ghunt8510** [comment]
I thought maybe discussions and issues were different threads.  I'd like to get a response to my problem from somewhere.....
