### ISSUE TITLE
tiff:rows-per-strip not honored in some cases

### ISSUE THREAD

**Issue by lightmare** [ImageMagick/ImageMagick#262]
- `COMPRESSION_JPEG`
https://github.com/ImageMagick/ImageMagick/blob/728dc6a600cf4cbdac846964c85cc04339db8ac1/coders/tiff.c#L3490

Here 16 is added to the number of rows per strip when it's already a multiple of 16:
```c
rows_per_strip+=(16-(rows_per_strip % 16));
```
Proper up-rounding would be:
```c
rows_per_strip += 15 - (rows_per_strip + 15) % 16;
```

Moreover, the rounding factor should ideally be `8 * vertical_subsampling`

- `COMPRESSION_ADOBE_DEFLATE`
https://github.com/ImageMagick/ImageMagick/blob/728dc6a600cf4cbdac846964c85cc04339db8ac1/coders/tiff.c#L3540

Here neither `tiff:rows-per-strip` nor input image `TIFFTAG_ROWSPERSTRIP` are honored; instead, single-strip output is forced:
```c
rows_per_strip=(uint32) image->rows;
```

Same for `COMPRESSION_CCITTFAX3/4`

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by lightmare** [comment]
Thanks for the quick reply. I found a report of the rounding problem from 2010 on [forums](http://imagemagick.org/discourse-server/viewtopic.php?t=17076), didn't expect it to be addressed so promptly :)

But the new rounding formula is kinda weird. It leaves multiples of 16 alone, rounds `k*16+15` up, and everything else down.
```
30 -> 16
31 -> 32
32 -> 32
...
46 -> 32
47 -> 48
48 -> 48
```

I'd prefer rounding up (the formula I posted above), or perhaps rounding to the nearest multiple:
```c
rows_per_strip = rows_per_strip <= 16 ? 16 : 16 * ((rows_per_strip + 8) / 16);

30 -> 32
31 -> 32
32 -> 32
...
39 -> 32
40 -> 48
...
46 -> 48
47 -> 48
48 -> 48
```

However, both ways still assume `subsampling-factor=#x2`. I dug deeper and found that after setting JPEG compression and subsampling:
```c
TIFFSetField(tiff, TIFFTAG_COMPRESSION, COMPRESSION_JPEG);
TIFFSetField(tiff, TIFFTAG_YCBCRSUBSAMPLING, horiz, vert);
rows_per_strip = TIFFDefaultStripSize(tiff, rows_per_strip);
```
`TIFFDefaultStripSize` (libtiff function, not [this macro](https://github.com/ImageMagick/ImageMagick/blob/99edc607e2dd8b896072de0d3327d90e4fbfdf9d/coders/tiff.c#L3087)) returns values rounded up to a multiple of `vert*8`, which is perfect. The function appears to be in libtiff since [forever](https://github.com/vadz/libtiff/blame/d4f07876edeffbe4e4c835c92e91d23c49477e6b/libtiff/tif_strip.c#L227), I don't know why magick `WriteTIFFImage` shadows it with the macro.


In my opinion, other compression schemes that don't have special requirements (DEFLATE, FAX, LZMA, LZW) should not override "tiff:rows-per-strip" setting. I'd flip the behaviour: initialize `rows_per_strip = (uint32) image->rows` [here](https://github.com/ImageMagick/ImageMagick/blob/99edc607e2dd8b896072de0d3327d90e4fbfdf9d/coders/tiff.c#L3482) (that is, default to single-strip output), before reading the option value, and then [after](https://github.com/ImageMagick/ImageMagick/blob/99edc607e2dd8b896072de0d3327d90e4fbfdf9d/coders/tiff.c#L3608) the compression switch (i.e. after setting subsampling in JPEG case) round it with `TIFFDefaultStripSize`. That way "tiff:rows-per-strip=0" could be used to ask for libtiff's default strip size guess.

**Comment by mikayla-grace** [comment]
Take a look @ our latest patch.  See if it aligns with your recommendations.  If not, let us now.

**Comment by lightmare** [comment]
Perfect, this finally gives full control over rows-per-strip with all compression modes.

One last bit: [these 2 lines](https://github.com/ImageMagick/ImageMagick/blob/10aa64cb92dacc9703f74d07333ec7e4595b3de6/coders/tiff.c#L3479-L3480) seem unnecessary now. The condition only protected against division by zero in the removed TIFFDefaultStripSize macro, and the second line's effect is equivalent to `-define tiff:rows-per-strip=0` (if this becomes the way to request a guess from libtiff, then it should also be mentioned in the docs; where are doc sources, btw?).

#### Notes on some corner cases for future reference (also for myself)

```sh
convert rose: -compress jpeg -define tiff:rows-per-strip=42 tif:- |
  identify -verbose - |
  grep rows
    tiff:rows-per-strip: 48
```
Here `TIFFDefaultStripSize` rounds 42 to 48, which is greater than image height (46), but that's not a problem. The last (only) strip will simply be incomplete, just like with `rows-per-strip=16` there would be 2 complete and 1 incomplete strip (remaining 14 rows).

```sh
convert rose: -compress jpeg -define tiff:rows-per-strip=46 tif:- |
  identify -verbose - |
  grep rows
    tiff:rows-per-strip: 46
```
Here `TIFFDefaultStripSize` doesn't round 46 to a multiple of 8/16. That doesn't seem to be an issue, either. `JPEGDefaultStripSize` in libtiff intentionally leaves values >= image height unrounded.

**Comment by mikayla-grace** [comment]
We remove the lines you identified in the latest patch.  Thanks.
