### ISSUE TITLE
image height exceeds user limit in ihdr

### ISSUE THREAD

**Issue by AaronTrazona** [ImageMagick/ImageMagick#2623]
HI guys,

I encounter a little problem in resizing the image.
So my  actual image dimensions 12000x29240 and  im trying to resize to 400x400.

 I attached image of  the actual error

![2020-09-25_10-38-54](https://user-images.githubusercontent.com/1627816/94220406-6f9d4880-ff1b-11ea-8b8e-c9a9582e2708.png)

Thanks

**Comment by fmw42** [comment]
In the future, please do not post images of text. Please copy and past the actual text and format it for reading. 

Looks like you need to edit your policy.xml file to permit reading wider images. See https://imagemagick.org/script/resources.php

**Comment by snibgo** [comment]
"Invalid IHDR data" suggests your input file is corrupt. Try writing to "NULL:" to confirm that is the problem. Then use "-verbose" and write to "info:".

**Comment by dlemstra** [comment]
Your `policy.xml` file probably contains a limit for the height of an image and you are exceeding this.
