### ISSUE TITLE
GIF looping bug?

### ISSUE THREAD

**Issue by sivark** [ImageMagick/ImageMagick#263]
I encounter the same bug as this: http://stackoverflow.com/questions/27066511/how-to-make-an-animated-gif-loop-twice-in-imagemagick

`convert` using `-loop 0` seems to play a gif infinite times
`convert` using `-loop 1` seems to play a gif one time
`convert` using `-loop 2` seems to play a gif three times

**Comment by dlemstra** [comment]
Which version of ImageMagick are you using?

**Comment by sivark** [comment]
Here's the output of `convert --version` I see:

> Version: ImageMagick 6.9.5-9 Q16 x86_64 2016-09-07 http://www.imagemagick.org
> Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
> License: http://www.imagemagick.org/script/license.php
> Features: Cipher DPC HDRI Modules OpenCL OpenMP 
> Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps rsvg tiff webp wmf x xml zlib
>

**Comment by fmw42** [comment]
Similar command fails for me also on IM 6.9.5.9 Q16 Mac OS.

convert -delay 50 rose: netscape: -loop 2 tmp.gif

I get 3 loops.

**Comment by dlemstra** [comment]
What do you get with -loop 3 @fmw42 ?

**Comment by fmw42** [comment]
-loop 1 -> 1 loop
-loop 2 -> 3 loops
-loop 3 -> 4 loops

**Comment by dlemstra** [comment]
Thanks for the help @fmw42, will take a look at it tonight.

**Comment by fmw42** [comment]
Revision:  When I do the above on my Netscape from Mac OSX snow leopard or Chrome, I get -loop 2 showing 3 loops. But when I display the same file in Firefox or Opera, I get the proper 2 loops.

**Comment by fmw42** [comment]
dlemstra:  See my edited comments above

**Comment by sivark** [comment]
@fmw42 Interesting catch! I can confirm that observation. My initial report was based on using `GNOME Image Viewer 3.20.4` and I see similar behaviour in `Chromium v53.0.2785.92 (64-bit)`. 

GIF playback seems as expected in `Firefox v48.0.2`.

**Comment by dlemstra** [comment]
There seem to be two different ways on how this can be interpreted. You could see it as the number of times that it should loop or the number of times that the image should be shown. 

> 2  = two loops, three iterations
> or
> 2  = show twice, two iterations

That would explain the difference in the viewrs. There was also an interesting chat about it on the mozilla board here: https://bugzilla.mozilla.org/show_bug.cgi?id=222176. I think we should not change the way we store it.

**Comment by sivark** [comment]
I realize that there is a question of convention is what `loop` means. But it seems like there isn't a way (for example) to get Chromium to go through a GIF and show the animation two times. That was the point of my original post.
 
Since there are examples of some software that handle playback correctly (and presumably their implementation has a consistent internal logic) I guess ImageMagick is fine as it stands. It's now a question of which image rendering code (on linux and Mac OS) is interpreting this inconsistently so one could file bug reports appropriately.

I'm closing this issue, but I would appreciate any comments that help make progress on this matter.

**Comment by fmw42** [comment]
dlemstra: I would agree that there is still something odd going on. On systems that for -loop 2 show 3 loops, why does not -loop 1 show 2 loops. It shows only 1 loop.

**Comment by dlemstra** [comment]
What we do is store the value that was provided with -loop (e.g. 2) and it appears that the value is handled differently by certain programs. One program shows the animation 2 times and another program shows it 3 times. I don't want to change the way we store the value.
