### ISSUE TITLE
Cannot build previous version from source for versions after 7.0.10-19 (Windows)

### ISSUE THREAD

**Issue by conwaypc** [ImageMagick/ImageMagick#2633]
### Prerequisites

- [X] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When downloading windows source from ImageMagick.org (https://imagemagick.org/download/windows/releases/) for previous releases, I cannot build.
In 7.0.10-19 and prior, dependencies were included in archive.  Beginning with 7.0.10-20 this is no longer the case.  Instructions require cloning the dependences from GitHub.com.  Unfortunately this results in a different product (7.0.10-20 + updated third party libraries).

### Steps to Reproduce
1. Download ImageMagick-7.0.10-19.7z, Extract archive into build folder.
2. In VS, open Configure solution in build folder\ImageMagick-7.0.10-19\VisualMagic\configure, and build it.
3. Run configure.exe, select appropriate prompts, to generate VisualMagic* solution.
4. Success - Can build with VisualMagic* solution.

Reproduce - Can't build -
1. Download ImageMagick-7.0.10-25.7z.  Extract archive into build folder.
2. VisualMagic folder does not appear.  Cannot build Configure solution.

Reproduce - Try Frankenstein - 
1. Extracting ImageMagick-7.0.10-19.7z and extracting ImageMagick-7.0.10-25.7z inside the ImageMagick-7.0.10-19 folder.  
2. In VS, open Configure solution in build folder\ImageMagick-7.0.10-19\VisualMagic\configure, and build it.
3. Run configure.exe, select appropriate prompts, to generate VisualMagic* solution.
4. Failure - Updates to third party software made VisualMagic\*\config.txt inconsistent.

Reproduce - Try Bride of Frankenstein - 
1. Extracting ImageMagick-7.0.10-19.7z, extracting ImageMagick-7.0.10-25.7z and latest VisualMagic-master inside the ImageMagick-7.0.10-19 folder.  
2 & 3 as above
4. Failure - Updates to VisualMagic\*\config.txt for future third party software made inconsistent.

It is unclear how to obtain VisualMagic\*\config.txt files for previous releases (e.g., 7.0.10-25).  

### System Configuration
- ImageMagick version: 7.0.10-25
- Environment: Windows 10, Visual Studio 2017 Community
- Additional information:

**Comment by dlemstra** [comment]
We made some changes to the creation of the release and it looks like we missed this. Can you give 7.0.10-32 a try when this has been released?

**Comment by fmw42** [comment]
FYI:   I can install from source OK on my Mac from the Unix source.

**Comment by dlemstra** [comment]
This should be resolved now @conwaypc.
