### ISSUE TITLE
FAIL: tests/wandtest

### ISSUE THREAD

**Issue by mmphosis** [ImageMagick/ImageMagick#264]
wandtest: delegate library support not built-in '/Library/Fonts//Arial.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/1737.
wandtest: delegate library support not built-in '/Library/Fonts//Arial.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/1737.
tests/wandtest.c main 5321 non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3271

**Comment by dlemstra** [comment]
You are getting this message because your build of ImageMagick does not have FreeType support.
