### ISSUE TITLE
error: implicit declaration of function 'sendfile' is invalid in C99

### ISSUE THREAD

**Issue by johnsonea** [ImageMagick/ImageMagick#2641]
compiling ImageMagick-7.0.10-31 on macOS 10.15.6 doesn't like the new defined(MAGICKCORE_HAVE_SENDFILE) in MagickCore/cache.c
MAGICKCORE_HAVE_SENDFILE is autodefined to 1 even if it isn't found.

**Comment by urban-warrior** [comment]
It looks like we need to include the sys/uio.h & sys/socket.h header files.    We'll add a patch.
