### ISSUE TITLE
Error appending/saving large jp2 images

### ISSUE THREAD

**Issue by kisaa** [ImageMagick/ImageMagick#2642]
### Description

Exception while appending jp2-images vertically and saving them to one resulting jp2 image. 
(Resulting file should be 22.000x22.000 px, 484 MPx)

### Steps to Reproduce

`> magick convert -append files_??.jp2 result.jp2`

- Test files (~300 MB, 7-zip):
https://drive.google.com/file/d/1TLbQWEAumJnrYx-92IJlPrtTJotnA-b0/view?usp=sharing

exception:
```
convert: opj_t2_encode_packet(): only 1562 bytes remaining in output buffer. 2242 needed.
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/194.
convert: Cannot encode tile
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/194.
convert: unable to encode image file `result.jp2' @ error/jp2.c/WriteJP2Image/1129.
```

Same thing with C# code and Magick.Net-Q16-x64 v.7.21.1:
```
using MagickImageCollection images = new MagickImageCollection();
for (int segment = 1; segment <= 23; segment++)
{
    string f = $"files_{segment:00}.jp2";
    images.Add(f);
}

using (IMagickImage<ushort> result = images.AppendVertically())
{
    try
    {
        result.Write("result.jp2");
    }
    catch (MagickException e)
    {
        MessageBox.Show(e.ToString());
    }
}
```
exception:
```
ImageMagick.MagickCoderErrorException: opj_t2_encode_packet(): only 2238 bytes remaining in output buffer. 2264 needed.
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/194
   in ImageMagick.MagickExceptionHelper.Check(IntPtr exception)
   in ImageMagick.MagickImage.NativeMagickImage.WriteFile(IMagickSettings`1 settings)
```

### System Configuration

- ImageMagick version:
```
Version: ImageMagick 7.0.10-31 Q16 x64 2020-09-27 http://www.imagemagick.org
...
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib
```

- Environment:
Windows 10 Pro x64 2004 (16 GB RAM)
Windows Server 2016 Std (192 GB RAM)

- Additional information:
Same code, smaller source images (resulting 5500x5500 px or 11000x11000 px) - works fine.

**Comment by fmw42** [comment]
Your syntax is wrong for IM 7. Use magick not magick convert. Then also read the input before doing append.

Try

`magick files_??.jp2 -append result.jp2`

or

`magick files_*.jp2 -append result.jp2`

**Comment by kisaa** [comment]
I just tried it. Same result. 
I see in the Task Manager that the proram works, one CPU core is 100% loaded, the memory consumption grows to 5 GB, but after a while the process gives the same error.

**Comment by snibgo** [comment]
Are pixels cached to disk?

I suggest you try the command with "-limit memory 1GB -limit map 1GB".

**Comment by kisaa** [comment]
No change. Same error.
It doesn't seem like a lack of resources:

```
> magick identify -list resource
Resource limits:
  Width: 107.374MP
  Height: 107.374MP
  Area: 204.752GP
  List length: unlimited
  Memory: 95.3449GiB
  Map: 190.69GiB
  Disk: unlimited
  File: 1536
  Thread: 64
  Throttle: 0
  Time: unlimited
```

**Comment by kisaa** [comment]
Found a similar (possibly original) bug in OpenJpeg:
https://github.com/uclouvain/openjpeg/issues/1243
marked as Closed.

How can this patch be applied to ImageMagick?

**Comment by kisaa** [comment]
I confirm that after replacing `CORE_RL_openjpeg_.dll` with builded using new code from https://github.com/uclouvain/openjpeg, problem solved.

**Comment by dlemstra** [comment]
It seems that we are using the latest version of the openjpeg library. Maybe you could ask them to publish a new release so we can update the library?

**Comment by dlemstra** [comment]
Please let me know when a new release has been publish @kisaa. We will then update the library as soon as possible.

**Comment by kisaa** [comment]
@dlemstra, openjpeg's last release was a year and a half ago. I'm afraid there won't be a new release soon :( But I'll keep an eye on this!
As I understand it, it is rather difficult to build all the intermediate stages yourself?

**Comment by dlemstra** [comment]
We could apply this patch to the Windows build of ImageMagick ourselves. But that means we need to take a good look at this patch to check that it won't break something else.

**Comment by dlemstra** [comment]
I have applied the patch from the issue that you linked. This seems to resolve the issue. The output below is from before and after the patch has been applied. This will be become available in the next version of ImageMagick and Magick.NET

```
I:\issues\im7\2642>magick convert -append files_??.jp2 result.jp2
convert: opj_t2_encode_packet(): only 1562 bytes remaining in output buffer. 2242 needed.
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/194.
convert: Cannot encode tile
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/194.
convert: unable to encode image file `result.jp2' @ error/jp2.c/WriteJP2Image/1129.

I:\issues\im7\2642>magick convert -append files_??.jp2 result.jp2

I:\issues\im7\2642>dir result.jp2
 Volume in drive I is IMAGES
 Volume Serial Number is 9667-D658

 Directory of I:\issues\im7\2642

19/10/2020  21:16       299.864.394 result.jp2
``

**Comment by kisaa** [comment]
@dlemstra, it is great! Thanks a lot!

**Comment by dlemstra** [comment]
A new release of Magick.NET that resolves this issue has been published.
