### ISSUE TITLE
magick identify falsely shows 10-bit and 12-bit depth heif/heic files as 8-bit

### ISSUE THREAD

**Issue by vincedarley** [ImageMagick/ImageMagick#2646]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

With any high-bit depth heif image that I have (10-bit or 12-bit), "magick identify" lists those files as 8-bit. Links to two sample files are attached.

This file is 10-bit
$ magick identify image1.HeIF 
image1.HeIF HEIC 5472x3648 5472x3648+0+0 **8-bit** YCbCr 0.010u 0:00.009

This one is 12-bit
$ magick identify image2.heic
image2.heic HEIC 5782x3946 5782x3946+0+0 **8-bit** YCbCr 0.020u 0:00.020

### Steps to Reproduce

https://app.box.com/s/su11ok9dzg2j5wwn1pblsqneigbnsjwc
https://app.box.com/s/5yavt4rpvewnjvkqmz37ztoosoy06f1y

### System Configuration

- ImageMagick version: Version: ImageMagick 7.0.10-30 Q16 x86_64 2020-09-21 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(3.1) 
Delegates (built-in): bzlib freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib

- Environment (Operating system, version and so on): MacOS Catalina 10.15.7. 
- Additional information: imagemagick, heif-enc, etc installed via homebrew.

**Comment by fmw42** [comment]
try

magick identify depth 16 image1.HeIF

**Comment by vincedarley** [comment]
Ok, if I do that, it tells me both images are 16-bit, which doesn't seem right either (given they are 10,12 respectively)?  Or am I completely misunderstanding what "magick identify" is supposed to do? If I use 'magick identify' on a 16-bit tiff, I get this:

slide1.tif[0] TIFF 5782x3946 5782x3946+0+0 16-bit sRGB 130.754MiB 0.000u 0:00.000

which is correct.

**Comment by fmw42** [comment]
try

identify -verbose -depth 16 slide1.tif[0]

It will tell you that you have 16-bit image but only your 10 or 12 bits are filled. That will show in the statistics where your maximum value will be the digital equivalent of 10 or 12 bits.

You may also see depth of 16/10 or 16/12.

**Comment by snibgo** [comment]
On reading 10-bit HEIC, see https://github.com/ImageMagick/ImageMagick/issues/2415

**Comment by vincedarley** [comment]
Here's what I get on the original tiff:

$ magick identify -verbose slide1.tif[0]
Image:
  Filename: slide1.tif
  Base filename: slide1.tif
  Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass
  Geometry: 5782x3946+0+0
  Resolution: 4000x4000
  Print size: 1.4455x0.9865
  Units: PixelsPerInch
  Colorspace: sRGB
  Type: TrueColor
  Endianness: LSB
  Depth: 16-bit
  Channel depth:
    Red: 16-bit
    Green: 16-bit
    Blue: 16-bit
  Channel statistics:
    Pixels: 22815772
    Red:
      min: 0  (0)
      max: 63186 (0.964157)
      mean: 18334.4 (0.279765)
      standard deviation: 13799.2 (0.210563)
      kurtosis: -0.847777
      skewness: 0.436955
      entropy: 0.8799
    Green:
      min: 0  (0)
      max: 65214 (0.995102)
      mean: 21257.1 (0.324362)
      standard deviation: 16887.6 (0.257688)
      kurtosis: -1.2803
      skewness: 0.323289
      entropy: 0.879871
    Blue:
      min: 0  (0)
      max: 61927 (0.944945)
      mean: 24965.7 (0.380951)
      standard deviation: 20048.2 (0.305916)
      kurtosis: -1.74919
      skewness: 0.0830632
      entropy: 0.86846
  Image statistics:
    Overall:
      min: 0  (0)
      max: 65214 (0.995102)
      mean: 21519 (0.328359)
      standard deviation: 16911.7 (0.258056)
      kurtosis: -1.31884
      skewness: 0.352764
      entropy: 0.876077
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Matte color: grey74
  Background color: white
  Border color: srgb(223,223,223)
  Transparent color: none
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 5782x3946+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: None
  Orientation: TopLeft
  Convex hull: 0,0 5781,0 5781,3944 5780,3945 0,3945 0,0 
  Minimum bounding box: 5781,0 5781,3945 0,3945 0,0 
  Profiles:
    Profile-icc: 492 bytes
  Properties:
    date:create: 2020-09-29T13:52:52+00:00
    date:modify: 2010-03-26T23:52:34+00:00
    icc:copyright: Nikon Inc. & Nikon Corporation 2001
    icc:description: Nikon Apple RGB 4.0.0.3000
    minimum-bounding-box:_p: 0,0
    minimum-bounding-box:_q: 5781,0
    minimum-bounding-box:_v: 5780,3945
    minimum-bounding-box:angle: 0
    minimum-bounding-box:area: 2.2806e+07
    minimum-bounding-box:height: 5781
    minimum-bounding-box:unrotate: -0
    minimum-bounding-box:width: 3945
    signature: 54d416f963c69794924495e46175ca98b989e74677e8883dbcb8f920f084d96a
    tiff:alpha: unspecified
    tiff:endian: lsb
    tiff:make: Nikon
    tiff:model: Nikon SUPER COOLSCAN 4000 ED
    tiff:photometric: RGB
    tiff:rows-per-strip: 1
    tiff:software: Nikon Scan 4.0.2 W
    tiff:timestamp: 2010.03.26 23.49.09
  Artifacts:
    verbose: true
  Tainted: False
  Filesize: 130.754MiB
  Number pixels: 22.8158M
  Pixels per second: 25.5863MP
  User time: 0.260u
  Elapsed time: 0:01.891
  Version: ImageMagick 7.0.10-30 Q16 x86_64 2020-09-21 https://imagemagick.org

The 'max' of each of R,G,B is close to 65536, so does that mean it is using all 16 bits (it was a high-end scanner that produced these tiffs)? Or are you suggesting the lower-order bits are not used? (although a blue max of 62917 would suggest that at least some lower-order bits are used, since that number is odd).

The process I've gone through is to convert such a tiff to a png with magick convert -depth 16. That png is identified as 16 bit. Then I use heif-enc (from libheif) with '-b12' to convert that to a heif (producing image2.heic). Here is where I'm surprised that magick identify tells me the file is only 8-bit.

Note that the 10-bit file image1.HeIF is a sample file from a Canon camera that saves into 10-bit heif directly. So nothing to do with libheif on that one.

**Comment by snibgo** [comment]
Currently (eg v7.0.10-27) IM successfully reads 8-bit HEIC but misreads 10-bit and 12-bit HEIC. See https://github.com/ImageMagick/ImageMagick/issues/2415

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
