### ISSUE TITLE
Image to PDF Conversion Produces Incorrect xref Table With Stream Output

### ISSUE THREAD

**Issue by evan-cleary** [ImageMagick/ImageMagick#2651]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When converting an image to a PDF, the xref table generated when utilizing a stream output vs a file output is incorrect.
Xref when outputting to file:
```
xref
0 20
0000000000 65535 f 
0000000010 00000 n 
0000000059 00000 n 
0000000118 00000 n 
0000000300 00000 n 
0000000384 00000 n 
0000000402 00000 n 
0000000440 00000 n 
0000000461 00000 n 
0000024208 00000 n 
0000024229 00000 n 
0000024264 00000 n 
0000028440 00000 n 
0000028461 00000 n 
0000028608 00000 n 
0000028626 00000 n 
0000028648 00000 n 
0000028666 00000 n 
0000029100 00000 n 
0000029120 00000 n 
trailer
<<
/Size 20
/Info 19 0 R
/Root 1 0 R
/ID [<010acf17686040eb8ae36f91159b2bf7515348e40193ad269d66439e8f325b55> <010acf17686040eb8ae36f91159b2bf7515348e40193ad269d66439e8f325b55>]
>>
startxref
29301
%%EOF
```

Xref table with stream output
```
xref
0 20
0000000000 65535 f 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
18446744073709551615 00000 n 
trailer
<<
/Size 20
/Info 19 0 R
/Root 1 0 R
/ID [<010acf17686040eb8ae36f91159b2bf7515348e40193ad269d66439e8f325b55> <010acf17686040eb8ae36f91159b2bf7515348e40193ad269d66439e8f325b55>]
>>
startxref
10
%%EOF
```

This causes issues in some PDF libraries as they are unable to properly identify the xref table.

### Steps to Reproduce
For incorrect results:
1. Obtain an image
2. Run `convert <image> pdf:-`

Expected Results:
1. Run `convert <image> correct.pdf`
2. Run `cat correct.pdf`
3. Xref table will differ from that produced when output is targeting stdout

### System Configuration

- ImageMagick version: ImageMagick 7.0.10-30
- Environment (Operating system, version and so on): Docker, CentOS 7
- Additional information:
Also observed on ImageMagick 7.0.10-31, OSX Catalina

This was last observed working on ImageMagick 6.9.10.68-3 (Latest in CentOS 7 RPM repos)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
