### ISSUE TITLE
eps input file BoundingBox not honored in output using eps:use-cropbox=true

### ISSUE THREAD

**Issue by alanngnet** [ImageMagick/ImageMagick#2657]
### Prerequisites

- [x ] I have written a descriptive issue title
- [ x] I have verified that I am using the latest version of ImageMagick
- [x ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The BoundingBox defined in the input .eps header is not respected even when -dEPSCrop is set.

See also https://github.com/ImageMagick/ImageMagick/discussions/2632 

### Steps to Reproduce

Use attached test.eps file with this command in Terminal:
`convert -density 600 test.eps -colorspace Gray test.png`
[Archive.zip](https://github.com/ImageMagick/ImageMagick/files/5315675/Archive.zip)

See attached resulting output test.png. Compare whitespace difference when viewing test.eps vs. resulting test.png using MacOS Preview.

Identical (uncropped) result when using this equivalent command:
`convert -define eps:use-cropbox=true -density 600 test.eps -colorspace Gray test.png`

Result of `convert -verbose -define eps:use-cropbox=true -density 600 test.eps -colorspace Gray test.png` is:
`/var/folders/hl/qyt_6pkx5sq5ggbk311zgvr80000gn/T/magick-qm8U1-FiM3pgs8-Cpy5AWjXPhWSe1FYh1 PNG 5100x6600 5100x6600+0+0 8-bit sRGB 167038B 3.990u 0:00.794
test.eps EPS 5100x6600 5100x6600+0+0 16-bit sRGB 167038B 0.000u 0:00.000
[ghostscript library 9.52] -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r600x600' -g5100x6600 -dEPSCrop  '-sOutputFile=/var/folders/hl/qyt_6pkx5sq5ggbk311zgvr80000gn/T/magick-qm8U1-FiM3pgs8-Cpy5AWjXPhWSe1FYh%d' '-f/var/folders/hl/qyt_6pkx5sq5ggbk311zgvr80000gn/T/magick-p6zA8gDQYUwXQ6ZqkP_teiyoKMiM5TbI' '-f/var/folders/hl/qyt_6pkx5sq5ggbk311zgvr80000gn/T/magick-MZZW8Qozta73N_PCZ5THlBzkl_LLZQgt'test.eps=>test.png EPS 5100x6600 5100x6600+0+0 16-bit Grayscale Gray 167038B 12.930u 0:01.743`

Again, resulting test.png is identically uncropped.

Proof that the underlying GhostScript install works as expected to crop when invoked manually:
`gs -dSAFER -dEPSCrop -r600 -sDEVICE=pngalpha -o test.png test.eps`
Results in the desired conversion and crop, attached:
![test](https://user-images.githubusercontent.com/15185920/94886606-460f8000-0439-11eb-95d8-d50498a30d8f.png)

### System Configuration
MacOS 10.15.16
ImageMagick 7.0.10-29 Q16 x86_64 2020-09-0 installed using homebrew
Ghostscript version = GPL Ghostscript 9.52 (2020-03-19) installed using homebrew

**Comment by fmw42** [comment]
For IM 7, you should be using magick, not convert.  It fails to crop for me.

`magick -define eps:use-cropbox=true -density 600 test.eps -colorspace Gray test.png`

However, 

magick identify -verbose text.eps

does not show any dropbox. Neither does EXIFTOOL. However, EXIFTOOL lists a bounding box of 

`BoundingBox                     : 8 -1 327 50`

I do not know enough about that to know if it is what you need. 

Opening in Photoshop, I do not see any path.  There is a small y offset in the file.

I think one of the IM developers will need to look into this. Perhaps user snibgo know.

**Comment by t246246** [comment]
According to GS manual https://www.ghostscript.com/doc/9.53.3/Use.htm#EPS_parameters, -dEPSCrop see the bounding box.
So BoundingBox is enough to crop, but it looks -g5100x6600 is honored rather than that.

**Comment by fmw42** [comment]
If I recall, in the past, identify -verbose used to show both a geometry and an image geometry. The second was what was need. The first for this image is Geometry: 612x792+0+0 which is too large.

**Comment by dlemstra** [comment]
Thanks for reporting this. This isssue will be resolved in the next version of ImageMagick that will be released later today.
