### ISSUE TITLE
Inconsistent behaviour between 7.0.10-11 and 7.0.10-31

### ISSUE THREAD

**Issue by t246246** [ImageMagick/ImageMagick#2667]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Input image is extract1.tif at https://github.com/ImageMagick/ImageMagick/issues/2666#issuecomment-703038650 

Different pixels image is got simpley tiff to tiff conversion between 7.0.10-11 and 7.0.10-31 

### Steps to Reproduce
Otherwise noted, all magick command is done in 7.0.10-31

  % magick extract1.tif out1.tif    

  $ magick extract1.tif out2.tif  **(In  7.0.10-11 (on MSYS2))**

  % magick compare out1.tif out2.tif -metric PSNR NUL:
1.02908

  $ tiffcp extract1.tif out3.tif
  % magick compare out2.tif out3.tif -metric PSNR NUL:
inf

Indeed, input file is odd, at least 

magick: Invalid TIFF directory; tags are not sorted in ascending order. `TIFFReadDirectoryCheckOrder' @ warning/tiff.c/TIFFWarnings/1044.

warning appears when reading.  And tiffinfo reports palette with alpha.

But the file is used in some Adobe eps, and should be converted as in 7.0.10-11, otherwise odd behavior occurs.  (See https://github.com/ImageMagick/ImageMagick/discussions/2661)

(It seems imdisplay (7.0.10.31) view is not correct; object is shift down, view of out2 is expected, it is close to gimp2 and Windows Photo Viewer, aside from transparency.)

![imdisplay](https://user-images.githubusercontent.com/19387062/94985771-512af300-0594-11eb-8c4c-a1a78a359566.png)

### System Configuration

Windows 10 64 bit
- ImageMagick version:
- Environment (Operating system, version and so on):
magick -version
Version: ImageMagick 7.0.10-31 Q16 x64 2020-09-27 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 192729111
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib

Older version in MSYS2:
$ magick -version
Version: ImageMagick 7.0.10-11 Q16 x86_64 2020-09-04 https://imagemagick.org
Copyright: ﾂｩ 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): bzlib cairo djvu fftw flif fontconfig freetype gslib gvc heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf xml zlib

$ tiffcp 2>&1 | head -3
LIBTIFF, Version 4.1.0
Copyright (c) 1988-1996 Sam Leffler
Copyright (c) 1991-1996 Silicon Graphics, Inc.

**Comment by urban-warrior** [comment]
See https://github.com/ImageMagick/ImageMagick/discussions/2661.
