### ISSUE TITLE
 ImageMagick is not working on Windows 10 Enterprise LTSC

### ISSUE THREAD

**Issue by wair92** [ImageMagick/ImageMagick#2673]
### Prerequisites

- [ x] I have written a descriptive issue title
- [ x] I have verified that I am using the latest version of ImageMagick
- [ x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
ImageMagick is not working on **Windows 10 Enterprise LTSC**

### Steps to Reproduce
1.) install IM from binary
2.) run ```magick logo: logo.gif``` command from cmd
3.) you will get following output:
```
magick: unable to open image 'logo:': Invalid argument @ error/blob.c/OpenBlob/3537.
magick: no decode delegate for this image format `' @ error/constitute.c/ReadImage/562.
```

- output from ```convert -list format``` is empty. 
- output from ```convert -list delegate``` is attached
[convert-list-delegate.txt](https://github.com/ImageMagick/ImageMagick/files/5325771/convert-list-delegate.txt)

### System Configuration

- ImageMagick version: 7.0.10-31 Q16 x86 2020-09-27 
- Environment (Operating system, version and so on): 
OS Name:                   Microsoft Windows 10 Enterprise LTSC
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
- Additional information:

**Comment by dlemstra** [comment]
This is probably happening because Windows is unable to find a dependency of one of the ImageMagick libraries. You can use something like https://www.dependencywalker.com/ to determine which dependency is missing.

**Comment by wair92** [comment]
I check it using dependency walker and compare to the output on PC where it is working correctly, I do not see there any big difference. Mostly in both cases  (on PC where it works (WIN 10) and where it doesnt (WIN 10 LTSC)) it is missing a lot of EXT-MS-\*.DLL and API-MS-\*.DLL . 
Registries under HKEY_LOCAL_MACHINE\SOFTWARE\ImageMagick are written correctly.

**Comment by dlemstra** [comment]
Did you figure this out @wair92?

**Comment by wair92** [comment]
@dlemstra Unfortunatelly no. I used qt instead
