### ISSUE TITLE
svg to png 100% cpu / hangs forever

### ISSUE THREAD

**Issue by jay039889387** [ImageMagick/ImageMagick#2680]
### Prerequisites

- [x ] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
SVG 100% cpu
I'm not sure if the svg-file is invalid, but a standard browser will display it and it nevertheless shouldn't hang imagemagick forever

### Steps to Reproduce
convert image.svg image.png

### System Configuration

- ImageMagick version: 7.0.10, multiple versions
- Environment (Operating system, version and so on): linux
- Additional information:

[image.zip](https://github.com/ImageMagick/ImageMagick/files/5332521/image.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
