### ISSUE TITLE
Commands without Arguments returns exit code 1

### ISSUE THREAD

**Issue by futureweb** [ImageMagick/ImageMagick#2681]
----- Also opened this Bug for ImageMagick 6 - https://github.com/ImageMagick/ImageMagick6/issues/106 ----- 

### Description
Commands called without Arguments return exit code 1. 
As no Error occured they should return exit code 0 as it was for years.

It seems this happened before and was corrected: http://webcache.googleusercontent.com/search?q=cache:bCKmxBhvPI8J:www.imagemagick.org/discourse-server/viewtopic.php%3Ft%3D26300+&cd=3&hl=de&ct=clnk&gl=at&client=firefox-b-d (Google Cache as old Board Links currently not working ...)

But later it was changed again it seems?
Return Code Behaviour should be consistent as it's breaking things when changed ... just happened with our CMS which denied working with Images when ImageMagick was updated by "dnf update" (Centos/RHEL) ...

### Steps to Reproduce
Older Version:
```
# /usr/bin/convert -version; /usr/bin/convert >/dev/null; echo $?
Version: ImageMagick 6.7.8-10 2012-08-17 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP    

0
```

Newer Version:
```
# /usr/bin/convert -version; /usr/bin/convert >/dev/null; echo $?
Version: ImageMagick 6.9.10-68 Q16 x86_64 2020-04-01 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(3.1) 
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jpeg lcms ltdl lzma openexr pangocairo png ps rsvg tiff wmf x xml zlib

1
```

Even more Newer Version:
```
/usr/local/bin/convert -version; /usr/local/bin/convert >/dev/null; echo $?
Version: ImageMagick 7.0.10-33 Q16 x86_64 2020-10-04 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib djvu fftw fontconfig freetype gslib jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps raqm raw tiff webp wmf x xml zlib

1
```

### System Configuration

- ImageMagick version: > 6.7.8-10
- Environment (Operating system, version and so on): Centos 7 & 8

**Comment by urban-warrior** [comment]
Try ImageMagick 7.0.10-34.  We get a zero exit code as expected.

**Comment by futureweb** [comment]
looking good - thx ;-)
