### ISSUE TITLE
Possible bug text file as kernel argument to -morphology

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#2695]
IM 6.9.11-33 Q16 Mac OSX Sierra. Trying to duplicate an example on Anthony's morphology page at https://imagemagick.org/Usage/morphology/#image2kernel

![flag](https://user-images.githubusercontent.com/13458218/95399819-eb08dd80-08bd-11eb-9065-ea531f4b89aa.gif)

This command works:

```
convert -size 80x80 xc:black -fill white \
-draw 'point 20,15 point 55,30 point 40,60'  points_pixels.gif
image2kernel -qgm flag.gif flag_kernel.dat
```

This fails with error:

```
convert  points_pixels.gif \
-morphology Dilate @flag_kernel.dat \
flagged_points.gif
```

**convert: invalid argument for option `-morphology': @flag_kernel.dat @ error/convert.c/ConvertImageCommand/2197.**

**Comment by snibgo** [comment]
You don't show the contents of flag_kernel.dat. For me, the file contains "8x11:" then 88 lines of "-".

That is not a valid morphology kernel. The source code morphology.c ParseKernelArray() has a check that the kernel contains at least one real (non-nan) number.

**Comment by fmw42** [comment]
Thanks. Looks like Anthony's image2kernel is not working properly. I get the same kernel with all "-".

**Comment by snibgo** [comment]
This hack seems to fix the problem. Change this line:
```
my $v = $values{$c}/($depth+1);
```
... to the following:
```
my $v = $values{$c};
```

**Comment by fmw42** [comment]
That did not work for me. I changed line 133 and ran it again. But still all "-"

**Comment by urban-warrior** [comment]
We identified the problem.  We'll need a few days to export a fix.

**Comment by fmw42** [comment]
Would it be possible to make the image2kernel a proper function in ImageMagick. That is a method to convert an image into a kernel text file so that the text file could be use as above as a kernel.

**Comment by snibgo** [comment]
My process module "img2knl" does that, more or less. See [Process modules: img2knl](http://im.snibgo.com/customim.htm#img2knl) . Feel free to implement it as a built-in operation to IM.
```
magick flag.gif -process img2knl NULL:

8x11:0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,1,0
,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,1,1
,0,0,1,1,1,1,1,1,1,1
```

**Comment by urban-warrior** [comment]
Look for a kernel image format in ImageMagick within the next few days.  The command will look similar to `convert points_pixels.gif kernel:flag_kernel.dat`.

**Comment by fmw42** [comment]
OK. Thanks

**Comment by fmw42** [comment]
Using IM 7.0.10.35beta, the following works:



```
magick -size 80x80 xc:black -fill white \
-draw 'point 20,15 point 55,30 point 40,60'  points_pixels.gif
```

![points_pixels](https://user-images.githubusercontent.com/13458218/95666921-b2624180-0b13-11eb-9100-d194c05d22f2.gif)


![flag](https://user-images.githubusercontent.com/13458218/95666916-a4142580-0b13-11eb-91f4-91736e1c3b14.gif)


```
magick flag.gif kernel:- | \
magick points_pixels.gif -morphology Dilate @- \
flagged_points.gif

```


![flagged_points](https://user-images.githubusercontent.com/13458218/95666927-c1e18a80-0b13-11eb-9a3a-f5d3e6b7df27.gif)
