### ISSUE TITLE
 Practically-infinite loop in MagickCore/image.c - SetImageBackgroundColor

### ISSUE THREAD

**Issue by moshekaplan** [ImageMagick/ImageMagick#27]
https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1492885

**Comment by urban-warrior** [comment]
Your pict_almost_infinite_loop.pict image converted without complaint for us:

setenv MAGICK_TMPDIR .
convert pict_almost_infinite_loop.pict null:

Modern releases of ImageMagick (6.9.1-5+) check the width and height of an image against the policy.xml file.  See http://www.imagemagick.org/discourse-server/viewtopic.php?f=4&t=26801.   In the example policy from the post, the maximum width / height is set to 8K.  If any image exceeds these limits, ImageMagick exits immediately with a resource policy violation.   For older versions of ImageMagick, the memory, map, area, and disk policy values from our post should help prevent denial-of-service for large image requests by returning a resource policy violation.

**Comment by moshekaplan** [comment]
Interesting. I had tested this on the version from git, where it ran
indefinitely.
