### ISSUE TITLE
The GetImageMinimumBoundingBox and MagickReadImageBlob methods did not release the memory correctly

### ISSUE THREAD

**Issue by Ryanznoco** [ImageMagick/ImageMagick#2707]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

The following code will be killed by oomkiller after running in multiple threads for about 1 hour. 
This is perftools dumping file. [cqwxi-m8h4k.pdf](https://github.com/ImageMagick/ImageMagick/files/5363485/cqwxi-m8h4k.pdf)

### Steps to Reproduce

```c
JNIEXPORT jobject JNICALL Java_com_winxuan_jmagick_MagickImage_magickParseBytesToInfo
        (JNIEnv *env, jobject instance, jbyteArray bytes, jobject identifyParams) {
    jmagick_identify_params *params;
    jobject result;
    jmagick_image_info *image_info;
    MagickWand *wand;
    jbyte *byteData;

    // read image blob
    wand = NewMagickWand();
    byteData = (*env)->GetByteArrayElements(env, bytes, 0);
    MagickBooleanType status = MagickReadImageBlob(wand, byteData, (*env)->GetArrayLength(env, bytes));
    if (status == MagickFalse) {
        DestroyMagickWand(wand);
        free(byteData);
        byteData = NULL;
        return NULL;
    }
    free(byteData);
    byteData = NULL;

    // ......
    
    // identify image
    status = com_winxuan_jmagick_identify_image(image_info, wand, params);
    if (status == MagickFalse) {
        DestroyMagickWand(wand);
        return NULL;
    }
    DestroyMagickWand(wand);
	
    // ......
    return result;
}

MagickBooleanType
com_winxuan_jmagick_identify_image(jmagick_image_info *image_info, MagickWand *wand, jmagick_identify_params *params) {
    MagickBooleanType status;
    ExceptionInfo *ex = AcquireExceptionInfo();

    size_t pointCount;
    PointInfo *minBoundBoxPoints;
    unsigned char *blob;

    // get blob length
    blob = MagickGetImageBlob(wand, &image_info->length);
    free(blob);
    blob = NULL;

    // GetImageMinimumBoundingBox
    Image *image = GetImageFromMagickWand(wand);
    minBoundBoxPoints = GetImageMinimumBoundingBox(image, &pointCount, ex);
    if (ex->severity != UndefinedException) {
        if (minBoundBoxPoints != NULL) {
            free(minBoundBoxPoints);
            minBoundBoxPoints = NULL;
        }
        DestroyExceptionInfo(ex);
        return MagickFalse;
    }
    DestroyExceptionInfo(ex);
    if (pointCount == 4) {
        image_info->content_region = com_winxuan_jmagick_parse_image_content_region(minBoundBoxPoints, pointCount);
    }
    free(minBoundBoxPoints);
    minBoundBoxPoints = NULL;

    // ......
    return MagickTrue;
}
```

### System Configuration

- ImageMagick version: ImageMagick 7.0.10-31 Q16 x86_64
- Environment (Operating system, version and so on): CentOS 7
- Additional information: jdk1.8.0_45

**Comment by dlemstra** [comment]
Did you check if an exception is being raised? I don't see a cleanup of `AcquireExceptionInfo`.

**Comment by Ryanznoco** [comment]
> Did you check if an exception is being raised? I don't see a cleanup of `AcquireExceptionInfo`.

I did. I have added the code to the above, is that right?

**Comment by Ryanznoco** [comment]
> Did you check if an exception is being raised? I don't see a cleanup of `AcquireExceptionInfo`.

Sorry, I will fix it and test agin. Thanks for you reply.

**Comment by Ryanznoco** [comment]
> Did you check if an exception is being raised? I don't see a cleanup of `AcquireExceptionInfo`.

I modified my program, but the problem still exists.

**Comment by dlemstra** [comment]
I would advise you to take a look at your own code first. I suspect that you return allocated memory inside the `com_winxuan_jmagick_parse_image_content_region` and "overwrite" it in `image_info->content_region`. Please make the sample as small as possible so we can reproduce it.

**Comment by dlemstra** [comment]
Can we close this issue @Ryanznoco?
