### ISSUE TITLE
Ubuntu apt autoremove deleted libIlmImf-2_2.so.22

### ISSUE THREAD

**Issue by duffnering** [ImageMagick/ImageMagick#2708]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I recently upgraded from Ubuntu 18.04 to 20.04. I installed imagemagick and all commands functioned as described. I also created a number of bash scripts to automate my usage. A few days ago, Ubuntu had an update. After the update completed, the message to remove items no longer being used is displayed, in which *so.22 was listed. Now, imagemagick does not function at all.
I cannot uninstall imagemagick nor re-install it without receiving the same error.

### Steps to Reproduce
magick -version (or any command)
returns:
magick: error while loading shared libraries: libIlmImf-2_2.so.22: cannot open shared object file: No such file or directory

### System Configuration

- ImageMagick version: 8:6.9.10.23+dfsg-2.1ubuntu11.1
- Environment (Operating system, version and so on): Ubuntu 20.04
- Additional information:

**Comment by dlemstra** [comment]
We don't maintain that. You will need to contact someone from Ubuntu.

**Comment by duffnering** [comment]
Ok, thank you for your reply.
