### ISSUE TITLE
tif to png transformation is failing with Null count for "Tag 32934"

### ISSUE THREAD

**Issue by dhaval1671** [ImageMagick/ImageMagick#2713]
### Description

TIFF to PNG is throwing Error using convert command line tool

### Steps to Reproduce

convert -quiet /Alftemp/mark-1335501_1600788696088.tif my.png

[mark-1335501_1600788696088.zip](https://github.com/ImageMagick/ImageMagick/files/5372166/mark-1335501_1600788696088.zip)

### System Configuration

- ImageMagick version: ImageMagick 7.0.10-26 Q16 x86_64 2020-08-10
- Environment (Operating system, version and so on): RHEL 7

- Additional information:

convert -quiet /Alftemp/mark-1335501_1600788696088.tif my.png

**convert: /Alftemp/mark-1335501_1600788696088.tif: Null count for "Tag 32934" (type 4, writecount -3, passcount 1). `_TIFFVSetField' @ error/tiff.c/TIFFErrors/661.
convert: no images defined `my.png' @ error/convert.c/ConvertImageCommand/3285.**

[mark-1335501_1600788696088.zip](https://github.com/ImageMagick/ImageMagick/files/5372110/mark-1335501_1600788696088.zip)

**Comment by snibgo** [comment]
With IM v7.0.8-64, I also get the error:
```
magick: mark-1335501_1600788696088.tif: Null count for "Tag 32934" (type 4, writecount -3, passcount 1). `_TIFFVSetField' @ error/tiff.c/TIFFErrors/664.
```
Gimp and exiftool don't report any errors.

We can tell IM to ignore that tag:
```
magick -define tiff:ignore-tags=32934 mark-1335501_1600788696088.tif x.png
```
This succeeds.

**Comment by dhaval1671** [comment]
Snibgo

Thanks it works with ignore-tag! Appreciate your help!

**Comment by dhaval1671** [comment]
Resolved
