### ISSUE TITLE
covert kodak PNG images into JP2 with sampling factor

### ISSUE THREAD

**Issue by khawar512** [ImageMagick/ImageMagick#2728]
I am trying to convert png images into JP2 with sampling factor. I am using imagemagick tool for conversion, as they mentioned in docs -sampling-factor is used for sampling but it did not work.

http://ftp.icm.edu.pl/pub/unix/graphics/ImageMagick/www/jp2.html

convert wizard.png -colorspace YUV -sampling-factor 2,2 wizard.jp2

My command, it did not work
convert test/images/kodim$i.png -quality $(($j*5)) -colorspace YUV -sampling-factor 4,2 test/JP2/kodim$i/printf "%02d" $j.jp2

**Comment by dlemstra** [comment]
Please dont' create an issue and a discussion. Closing this one.

**Comment by khawar512** [comment]
Ok thank you. Please give me a answer, if possible

**Comment by khawar512** [comment]
How can i solve this issue?
