### ISSUE TITLE
eb5b612441ad65824b2b71c5758fa344a77cc00e breaks semver

### ISSUE THREAD

**Issue by leshik** [ImageMagick/ImageMagick#2729]
https://github.com/ImageMagick/ImageMagick/commit/eb5b612441ad65824b2b71c5758fa344a77cc00e breaks semver – v7.0.10-34 doesn't compile on Debian Buster anymore using distribution's `libheif-dev`.

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by noma4i** [comment]
Was that fixed? @dlemstra

**Comment by dlemstra** [comment]
This was fixed and will be resolved in the next release.

**Comment by noma4i** [comment]
Cool. Can be closed once released. Thank you and don't break semver plz @dlech

**Comment by dlech** [comment]
I had nothing to do with it :laughing: (watch out for that autocomplete - it is tricksy)
