### ISSUE TITLE
Older Imagemagick crashes on png wider than 16000

### ISSUE THREAD

**Issue by cbm755** [ImageMagick/ImageMagick#2732]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

On ` ImageMagick 6.9.7-4 Q16 x86_64 20170114`, an png of width 16001 causes:
```
identify: ../../magick/quantum.c:216: DestroyQuantumInfo: Assertion `quantum_info != (QuantumInfo *) NULL' failed.
Aborted
```
(But width of 16000 is ok.)

Similar happens on `ImageMagick 6.9.10-?` but apparently without an actual crash (? not my computer, don't know precise version info, but its some Ubuntu release).

On Fedora 32 with `ImageMagick 6.9.11-27 Q16 x86_64 2020-08-11`, there is no such crash.  Tested up to 16383 as per https://alexandre.alapetite.fr/doc-alex/large-image/index.en.html

### Steps to Reproduce

Make two images:
```
G0015g4_16000.png: PNG image data, 16000 x 1956, 8-bit/color RGB, non-interlaced
G0015g4_16001.png: PNG image data, 16001 x 1956, 8-bit/color RGB, non-interlaced
```

### System Configuration

As above.

### Other info

  * This bug seems to be fixed in recent versions
       - but its possible its just a difference in compiling on Fedora vs Ubuntu.
  * Also I did not find anything explicitly in the change log about it.

Thus reporting in case its not fixed, just hidden or maybe still present on Ubuntu.

I did see this in the changelog, which is possibly what fixed it (but I did not bisect the code to confirm):
```
2020-01-12  6.9.10-87 Cristy  <quetzlzacatenango@image...>
  * Conditional compile for huge xml pages for RSVG delegate library.
  * Put "width" property in the PNG namespace (reference
    https://github.com/ImageMagick/ImageMagick/issues/1833).
 * -combine -colorspace sRGB no longer returns grayscale output (reference
    https://github.com/ImageMagick/ImageMagick/issues/1835).
```

This is related to downstream issue https://gitlab.com/plom/plom/-/issues/1222

**Comment by dlemstra** [comment]
I am unable to reproduce your issue. Can you upgrade your version of ImageMagick and try it again?

**Comment by cbm755** [comment]
I also cannot reproduce it with later versions of ImageMagick, as I said:

> This bug seems to be fixed in recent versions 

(You can close if you wish: I only filed it b/c I could not find it mentioned in the Changelog)
