### ISSUE TITLE
"improper image header"

### ISSUE THREAD

**Issue by freshfey** [ImageMagick/ImageMagick#274]
I've tried adding a loop to multiple files in a folder, starting like this:

`convert ab-rollout-1.gif -loop 0 ab-rollout-1.gif`

but I keep getting an error 

    convert: improper image header `ab-rollout-1.gif' @ error/gif.c/ReadGIFImage/1020.
    convert: no images defined `ab-rollout-1.gif' @ error/convert.c/ConvertImageCommand/3257.

All of these images have been converted/edited with ImageMagick, so I'm not sure what's going wrong here.

**Comment by dlemstra** [comment]
Can you share one of those images? And what is your ImageMagick version?

**Comment by freshfey** [comment]
Here's the [link](https://www.dropbox.com/s/c26u9e0vi84z81t/ab-rollout-1.gif?dl=0) to the file `ab-rollout-1.gif` (I had to put it on dropbox, because github says "The file is empty", maybe a hint to the error? Metadata corruption?)

`Version: ImageMagick 6.9.5-9 Q16 x86_64`
`Mac OS X 10.11.6`

**Comment by fmw42** [comment]
I get an empty file message when I try to open it in Mac Preview (on Snow Leopard). And Firefox says it has a bad header.

**Comment by freshfey** [comment]
😞  - any way to fix those headers? Or rather how did they get corrupted? I only used ImageMagick to convert from png and to merge two gifs together.

**Comment by dlemstra** [comment]
Can you reproduce the incorrect gif image? If you can please share the command and the input images on something like dropbox.

**Comment by freshfey** [comment]
@dlemstra sure, here are the original files

![ab-rollout-1](https://cloud.githubusercontent.com/assets/338269/18618141/6dd90e14-7de0-11e6-8020-4370559d3cd2.gif)
![ab-rollout-2](https://cloud.githubusercontent.com/assets/338269/18618142/6df2ff40-7de0-11e6-8567-d2c1420d2e56.gif)

I wrote it using RMagick

```
require 'rmagick'
include Magick

first = Dir.glob("*ab-rollout-1.gif*")
second = Dir.glob("*ab-rollout-2.gif*")

test = ImageList.new(first[1], second[1]) 
test.delay=90 
test.write(first[1])
```

A bit differently though for multiple files, but that's the gist.

**Comment by freshfey** [comment]
To update: I think the metadata got corrupted while I was trying `convert -loop 0 *.gif *.gif`. I have a backup folder of all the images that are in working condition, one is here:

![ab-rollout-1](https://cloud.githubusercontent.com/assets/338269/18640290/b99499f6-7e97-11e6-9291-55e85c1c0ff3.gif)
