### ISSUE TITLE
Unable to convert tif - maximum channels exceeded

### ISSUE THREAD

**Issue by thscott** [ImageMagick/ImageMagick#2746]
### Description
I have a tif with 21 samples per pixel, which ImageMagick can no longer do anything with due to a "maximum channels exceeded" error.

Looking though the code, this comes from:
https://github.com/ImageMagick/ImageMagick/blob/4759d26eafe76fec032da5c2fd56d68574bf289d/coders/tiff.c#L1809-L1813
added in commit 05f9e776d3aa14a2e67d3dde4732015d74ce20aa

I'm not sure that adding samples per pixel and extra samples makes sense here, as extra samples will always be samples_per_pixel - 3 (as per the tif spec [here](https://www.awaresystems.be/imaging/tiff/tifftags/extrasamples.html)). In my case there are 18 extra samples, causing the issue (MaxPixelChannels being 32).

I believe the check should just be against samples_per_pixel.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by cleaman** [comment]
I am having this maximum channels exceeded issue in version 7.0.10-34 as well as version 7.0.10-21. Will this fix be ported to version 7 or is the another workaround?

**Comment by urban-warrior** [comment]
Can you post a link to an image that causes ImageMagick to throw a "maximum channels exceeded" exception?  We need to download the image and reproduce the issue locally to determine the best resolution to the problem.

**Comment by cleaman** [comment]
Here is an example file. Just as a note. This does work with ImageMagick-6.9.5-9 and ImageMagick-6.9.2-8

[example.tif.zip](https://github.com/ImageMagick/ImageMagick/files/5547187/example.tif.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by cleaman** [comment]
I patched the pixel.h file as in the commit but still receive the error. Is something else needed?

tools/imagemagick/bin/convert 0032-1K21US-1123L_339_v03.tif out.jpg
convert: Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/1044.
convert: maximum channels exceeded `0032-1K21US-1123L_339_v03.tif' @ error/tiff.c/ReadTIFFImage/1812.
convert: no images defined `out.jpg' @ error/convert.c/ConvertImageCommand/3285.

**Comment by urban-warrior** [comment]
Works for us.  Perhaps you did not rebuild/reinstall the ImageMagick distribution properly after your patch.  We will have a new release of ImageMagick with the patch within a day or two if you can wait.
