### ISSUE TITLE
`convert *.jpg json:` returns the same "filesize" for every input file, using whichever image was first in the command list.

### ISSUE THREAD

**Issue by johnkw** [ImageMagick/ImageMagick#2749]
`convert *.jpg json:` returns the same "filesize" for every input file, using whichever image was first in the command list.

As few as 2 files can be used to reproduce the bug, but it also occurs with many more files. JPEG, PNG, SVG are all impacted the same - probably all input file types?

"version": "ImageMagick 6.9.11-27 Q16 x86_64 2020-08-11 https://imagemagick.org"
Fedora release 32 (Thirty Two)

**Comment by fmw42** [comment]
Works fine for me on IM 6.9.11.34 Q16 Mac OSX (and 7.0.10.34)

`convert logo: rose: json:tmp.txt
`

[tmp.txt](https://github.com/ImageMagick/ImageMagick/files/5412809/tmp.txt)

**Comment by johnkw** [comment]
I can confirm that doing an output like "json:tmp.txt" does actually avoid the bug.

The bug is possibly limited to "json:" output. Ie, going to stdout as per the original bug report.

**Comment by johnkw** [comment]
This is even more broken than I thought.  You discovered a more complicated version of this bug.

I can confirm that doing an output like "json:tmp.txt" does actually get DIFFERENT byte sizes.  However the byte sizes it puts in the "filesize" field are all incorrect.

When you send it to stdout as in the original report using the "json:" output file, they're all the size of the first input.

When using a "json:out.txt" output file the filesize entries seems to be randomly incremented.  Every "filesize" is greater than the prior, but the amount of increase seems unrelated to the size of the file.

It's more obvious if you do this:
```$ convert rose: rose: rose: json:out.txt
$ grep filesize out.txt
    "filesize": "0B",
    "filesize": "2758B",
    "filesize": "5517B",```

**Comment by fmw42** [comment]
Sorry, I thought you meant dimension, not file size.  It is odd that it produces 0B for the first file. I suspect you have found a bug.

**Comment by johnkw** [comment]
I just noticed another bug, not sure if it warrants a separate ticket since it's very closely related:

The ["artifacts"]["filename"] entry is also broken for multi-file convert to json: (to stdout or to file).  For all files it incorrectly outputs the name of the last input file.

**Comment by snibgo** [comment]
Finding the "filesize" of "rose:", which isn't a file, is fairly meaningless. So I would ignore that test.

But the problem also occurs on real files, eg:
```
f:\web\im>%IMG7%magick toes.png toes.png toes.png json:x.txt

f:\web\im>type x.txt |grep filesize
    "filesize": "0B",     <<== Wrong
    "filesize": "3998B",  <<== Wrong
    "filesize": "8006B",  <<== Wrong
```
Strangely, the bug doesn't occur when we write to "-":
```
f:\web\im>%IMG7%magick toes.png toes.png toes.png json:- |grep filesize
    "filesize": "320268B", <<== Correct
    "filesize": "320268B", <<== Correct
    "filesize": "320268B", <<== Correct
```
Tested with IM v7.0.8-64 on Windows 8.1.

**Comment by johnkw** [comment]
The second example with "toes.png toes.png toes.png" is only right by accident. As noted in the original ticket post, if you use 3 different files, it will brokenly return the size of the first file 3 times.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by johnkw** [comment]
Did this actually happen? I don't see it, but it would sure be helpful to leave this open until the commit makes it in, and link the commit from here.

**Comment by urban-warrior** [comment]
We committed several JSON patches.  The patches have not made it to a release just yet.  In the mean-time, clone the latest ImageMagick repo and verify you are getting expected results.

**Comment by johnkw** [comment]
Oh I think I found one at least: commit 3ea0f81e9b7df1364a3517a92b04bc724cc29634

I had not been looking at commits labeled "..." - I assumed those were non-code-change commits, like updating copyright comments or something unimportant.
