### ISSUE TITLE
identify "d:" hangs

### ISSUE THREAD

**Issue by qwerty4030** [ImageMagick/ImageMagick#275]
Version: ImageMagick 6.9.3-10 Q16 x86_64 2016-05-04 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC OpenMP 
Delegates (built-in): jng jpeg lzma png tiff xml zlib

OS: 4.4.10-22.54.amzn1.x86_64 (amazon linux)

identify hangs on the following commands:

```
identify "d:" (no output, just hangs forever)
identify "d::" (no output, just hangs forever)
identify "http:"
error : Unknown IO error (hangs after this message)
identify "http::"
error : Unknown IO error (hangs after this message)
```

**Comment by glennrp** [comment]
I haven't finished bisecting this bug yet, but I observed that the bug exists at least from 6.9.3-1 through 6.9.4-1 and not in 6.9.4-7 and later (testing on Ubuntu 16:04).  I don't see anything about it in the ChangeLog.

**Comment by mikayla-grace** [comment]
ImageMagick previously defaulted to stdin if no filename was specified.  With recent versions of ImageMagick, you can replicate the behavior with a dash, e.g. identify -.  To prevent reading from stdin, add this policy (see http://www.imagemagick.org/script/security-policy.php):

```
<policy domain="path" rights="none" pattern="-"/>
```

With this policy, we get

```
$ identify -
identify: not authorized `-' @ error/blob.c/OpenBlob/2451.
identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/508.
```

**Comment by qwerty4030** [comment]
Still getting this error on an upgraded version:
```
Version: ImageMagick 6.9.5-10 Q16 x86_64 2016-11-11 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC OpenMP 
Delegates (built-in): zlib
```
The following command hangs:
```
identify "http:"
```
I noticed that some delegates are missing, working on installing those now. However I do not expect that command to hang.

**Comment by qwerty4030** [comment]
@dlemstra If I remember correctly, installing the missing delegates resolved the issue. We are now only passing valid filenames (from the `tmp` directory) to IM and we have not run into this issue since then.
