### ISSUE TITLE
ICO encoder uses illegal PNG depths

### ISSUE THREAD

**Issue by jtippet** [ImageMagick/ImageMagick#2756]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The ICO file format can embed a PNG image, but the PNG _must_ be encoded as RGBA32.  ImageMagick's ICO encoder attempts to honor this requirement:

```
        /*
          Only write PNG32 formatted PNG (32-bit RGBA), 8 bits per channel.
        */
        (void) SetImageArtifact(write_image,"png:format","png32");
```

However, setting the artifact `png:format` does not actually seem to constrain the PNG encoder to using RGBA like the code comment wants it to.  Instead, it merely constrains the encoder to use 32bpp color depth.  Probably you'd instead need to set both `png:IHDR.color-type-orig` to 6 and `png:IHDR.bit-depth-orig` to 8.

### Steps to Reproduce
```
# Create a greyscale PNG file
magick -size 256x256 canvas:none -draw 'rectangle 32, 32, 224, 224' -fill black t.png

# Convert it to an ICO
magick t.png t.ico

# Verify the resulting PNG is not Grayscale
magick identify t.ico
t.ico PNG 256x256 256x256+0+0 8-bit Grayscale Gray 609B 0.000u 0:00.003

# Double-check the IHDR in the embedded PNG
xxd t.ico
00000000: 0000 0100 0100 0000 0000 0100 2000 4b02  ............ .K.
00000010: 0000 1600 0000 8950 4e47 0d0a 1a0a 0000  .......PNG......
00000020: 000d 4948 4452 0000 0100 0000 0100 0804  ..IHDR..........
```

`magick identify` says it's Grayscale, but older versions of this printed just wrong information, so I don't completely trust it ;)  .  So I also checked the hexdump.  Note that the 5th word after the embedded PNG file's IHDR is 0x0804 -- this corresponds [bits per channel = 8 / color type = 4 greyscale](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html).  The only legal value in an ICO file is 0x0806, which would correspond to RGBA32.

### System Configuration

- ImageMagick version:  7.0.10-34 Q16 x86_64 2020-10-10, also repros on 6.9.7-4 Q16 packaged with Ubuntu bionic
- Environment (Operating system, version and so on): Ubuntu 18.04 (bionic)
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow

**Comment by danpla** [comment]
I don't know if this is a regression, but the problem still exists in ImageMagick 7.1.1-20. IM still doesn't force RGBA for 256 px PNGs, resulting in invalid ICOs.

You can reproduce this with the original steps from https://github.com/ImageMagick/ImageMagick/issues/2756#issue-727788645, or with the following:
```sh-session
$ magick rose: -resize 256x256! PNG24:i.png
$ magick i.png i.ico
$ icotool -l i.ico
--icon --index=1 --width=256 --height=256 --bit-depth=24 --palette-size=0
```

As you can see, `--bit-depth` is 24 instead of 32.

**Comment by danpla** [comment]
Here's an even more interesting example, where IM optimizes an RGBA image to grayscale:
```sh-session
$ magick -size 256x256 xc:black PNG32:i.png
$ magick identify i.png
i.png PNG 256x256 256x256+0+0 8-bit sRGB 1085B 0.000u 0:00.000
$ magick i.png i.ico
$ magick identify i.ico
i.ico PNG 256x256 256x256+0+0 8-bit Grayscale Gray 2c 110B 0.000u 0:00.000
$ icotool -l i.ico
--icon --index=1 --width=256 --height=256 --bit-depth=1 --palette-size=0
```

**Comment by fmw42** [comment]
If you want RGBA, then use PNG32: rather than PNG24:

**Comment by danpla** [comment]
I suppose that this should be done on the ImageMagick side, since it has the code to do this automatically, and there has already been an unsuccessful attempt to fix this.
