### ISSUE TITLE
Range based filename references + delay bug

### ISSUE THREAD

**Issue by gpakosz** [ImageMagick/ImageMagick#276]
Hello,

I noticed the following command produces a broken output animation:

```
convert -verbose -delay 10 ./frames-%d.png[0-1] ./frames-%d.png[2-10] -coalesce +dither -loop 0 animation.gif
```

Output only contains frames 0 and 1 and remaining frames are blank.

Removing `-delay 10` or keeping `-delay` but using `./frames-%d.png[0-10]` works. My initial goal was to assign different delays to different parts of the frames sequence.

**Comment by dlemstra** [comment]
I cannot reproduce your issue with the latest version of ImageMagick. Can you still reproduce this issue @gpakosz?

**Comment by gpakosz** [comment]
Hi @dlemstra, for some reason I didn't get a notification you answered 18 days ago.

And to be honest, I don't even remember what I was doing when I reported this 😐

I don't have frames files at hand but will try to reproduce.
