### ISSUE TITLE
Converting 1-bpp PNG into TIFF does not preserve depth

### ISSUE THREAD

**Issue by ppisar** [ImageMagick/ImageMagick#277]
After upgrading from 6.9.2-7 to 6.9.3-0 I found that conversion from PNG into TIFF stopped preserving image depth. The same issue is with latest 6.9.5-5:

```
$ convert -version
Version: ImageMagick 6.9.2-7 Q16 x86_64 2016-09-29 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib jbig jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps rsvg tiff webp wmf x xml zlib

$ convert in.png out.tiff && file in.png out.tiff 
in.png:   PNG image data, 157 x 196, 1-bit grayscale, non-interlaced
out.tiff: TIFF image data, little-endian, direntries=16, height=196, bps=1, compression=deflate, PhotometricIntepretation=BlackIsZero, orientation=upper-left, width=157

$ convert -version
Version: ImageMagick 6.9.5-5 Q16 x86_64 2016-09-29 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib jbig jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps rsvg tiff webp wmf x xml zlib

$ convert in.png out.tiff && file in.png out.tiff 
in.png:   PNG image data, 157 x 196, 1-bit grayscale, non-interlaced
out.tiff: TIFF image data, little-endian, direntries=17, height=196, bps=8, compression=deflate, PhotometricIntepretation=BlackIsZero, orientation=upper-left, width=157
```

**Comment by ppisar** [comment]
This is the input in.png
![in](https://cloud.githubusercontent.com/assets/1064942/18957649/2cd741d2-8660-11e6-8523-86ff591a721f.png).

**Comment by ppisar** [comment]
I also tried 6.9.5-10. The bug is there too.

**Comment by dlemstra** [comment]
The PNG reader calls `png_set_packing` and changes the depth of the image from 1 bit to 8 bit. This patch was added a while back. Maybe @glennrp can explain why this was added?

**Comment by glennrp** [comment]
We call png_set_packing in the decoder to expand the samples to 8 bits, but we also call png_set_packing in the encoder to pack them into 8-sample bytes again.

**Comment by glennrp** [comment]
I don't see anything in the ChangeLog nor is there any difference between 6.9.2-6/coders/png.c and 6.9.3-1/coders/png.c that would explain this.

**Comment by dlemstra** [comment]
I think the line https://github.com/ImageMagick/ImageMagick/blob/ImageMagick-6/coders/png.c#L2433 is setting the depth to 8 bit instead of 1 bit.

**Comment by ppisar** [comment]
I can see 6.9.9-38 is still broken.

**Comment by ppisar** [comment]
6.9.10-64 is also broken.
