### ISSUE TITLE
Load big tiff error

### ISSUE THREAD

**Issue by KngStr** [ImageMagick/ImageMagick#2773]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I'm trying to load some tiff. Failed with some big files.
My test file: test.tiff - 293.46 MB
![im tiff error](https://user-images.githubusercontent.com/1308555/97522312-71ef3880-19da-11eb-9688-76728641806f.png)

### Steps to Reproduce

Just load with imdisplay.

### System Configuration

- ImageMagick version:
   7.0.10.34-Q16 HDR
- Environment (Operating system, version and so on):
   Win10 Enterprise 1903 x64

- Additional information:
    You can download test tiff from here: http://dl.kngstr.com/im.test.tiff.7z

**Comment by fmw42** [comment]
What was your command?  What is your version of libtiff? Does it contain BigTiff compatibility?

**Comment by KngStr** [comment]
I do not know it. I just downloaded exe from your website.

**Comment by t246246** [comment]
It looks just a warning.  Can you view it after closing that dialog?

**Comment by KngStr** [comment]
@t246246 

Thanks.
I remeber it failed yesterday, but it succeed today.
