### ISSUE TITLE
memory leaks in ReadDOTImage

### ISSUE THREAD

**Issue by butterflyhack** [ImageMagick/ImageMagick#2778]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

==89381==ERROR: LeakSanitizer: detected memory leaks
```
Direct leak of 13024 byte(s) in 1 object(s) allocated from:
    #0 0x7f10b382eb90 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb90)
    #1 0x7f10b2c3d9f0 in AcquireMagickMemory MagickCore/memory.c:527
    #2 0x7f10b2c3da16 in AcquireCriticalMemory MagickCore/memory.c:603
    #3 0x7f10b2bfa37f in AcquireImageInfo MagickCore/image.c:328
    #4 0x7f10b2bfd579 in CloneImageInfo MagickCore/image.c:924
    #5 0x7f10b2f0e638 in ReadDOTImage coders/dot.c:133
    #6 0x7f10b2a676f7 in ReadImage MagickCore/constitute.c:563
    #7 0x7f10b2a6a80b in ReadImages MagickCore/constitute.c:953
    #8 0x7f10b222043b in CompositeImageCommand MagickWand/composite.c:536
    #9 0x7f10b23e598b in MagickCommandGenesis MagickWand/mogrify.c:191
    #10 0x401a75 in MagickMain utilities/magick.c:149
    #11 0x401cf3 in main utilities/magick.c:180
    #12 0x7f10b1b7d83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)

```
### Steps to Reproduce

run cmd:
```
./magick composite input1 input2 output.aai
```

### System Configuration

- ImageMagick version: ImageMagick 7.0.10-35 Q16 x86_64 2020-10-29
- Environment (Operating system, version and so on): Linux ubuntu 4.15.0-118-generic #119~16.04.1-Ubuntu SMP Tue Sep 8 14:54:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Additional information: ./configure CC="gcc" CXX="g++" CFLAGS="-g -fsanitize=address"

tesecase:
[https://github.com/butterflyhack/pocs/blob/master/memory-leaks-aai.zip](url)

credit by ADLab of venustech

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
