### ISSUE TITLE
Comparison with AE metrics doesn't notice two closest but different pixels

### ISSUE THREAD

**Issue by Alepod** [ImageMagick/ImageMagick#2781]
### Prerequisites

- [ ✔️ ] I have written a descriptive issue title
- [ ✔️ ] I have verified that I am using the latest version of ImageMagick
- [ ✔️ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Comparison with AE metrics ignores difference between tho closest shades (if they differ by 1 only in one channel)

### Steps to Reproduce
So, for example, we have two 1×1 PNG images, 1st filled with hex8B405F and the 2nd filled with hex8C405F.
So we compare these two images using AE (and other metrics):

>compare +fuzz -metric ae pics\pixel_1.png pics\pixel_2.png - > nul
0
>compare +fuzz -metric mae pics\pixel_1.png pics\pixel_2.png - > nul
0.33333 (0.0013072)
>compare +fuzz -metric pae pics\pixel_1.png pics\pixel_2.png - > nul
1 (0.0039216)
>compare +fuzz -metric psnr pics\pixel_1.png pics\pixel_2.png - > nul
52.902
>compare +fuzz -metric mepp pics\pixel_1.png pics\pixel_2.png - > nul
1 (5.1262e-06, 0.0039216)
>compare +fuzz -metric mse pics\pixel_1.png pics\pixel_2.png - > nul
0.0013072 (5.1262e-06)
>compare +fuzz -metric fuzz pics\pixel_1.png pics\pixel_2.png - > nul
0.57735 (0.0022641)

### System Configuration

- ImageMagick version: ImageMagick-7.0.10-34-portable-Q8-x64
- Environment (Operating system, version and so on): Win 8.1
- Additional information:
Here's test images, used by me (yeap, 1×1)
![pixel_2](https://user-images.githubusercontent.com/22130090/97766888-ac1b2000-1b29-11eb-8b81-28e390b62a1d.png)
![pixel_1](https://user-images.githubusercontent.com/22130090/97766889-acb3b680-1b29-11eb-92b0-390ad12fa285.png)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
