### ISSUE TITLE
Reading animated AVIF fails

### ISSUE THREAD

**Issue by andrius4669** [ImageMagick/ImageMagick#2788]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Trying `magick identify` on files in https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles/Netflix/avis fails with errors like
```
identify: Invalid input: Non-existing item ID referenced: Non-existing alpha image referenced `alpha_video.avif' @ error/heic.c/IsHeifSuccess/134.
```
or
```
identify: Unsupported file-type: Unspecified: File does not include any supported brands.
 `Chimera-AV1-10bit-480x270.avif' @ error/heic.c/IsHeifSuccess/134.
```
Both of these open fine in gwenview (with qt-avif-image-plugin installed) and also chromium.

### Steps to Reproduce

```
git clone https://github.com/AOMediaCodec/av1-avif
cd av1-avif/testFiles/Netflix/avis
magick identify alpha_video.avif
magick identify Chimera-AV1-10bit-480x270.avif
```

### System Configuration

- ImageMagick version: 7.0.10-35 Q16 x86_64 2020-11-01
- Environment (Operating system, version and so on): x86_64 ArchLinux
- Additional information: libheif 1.9.1, libavif 0.8.2, dav1d 0.7.1, aom 2.0.0

EDIT: adjusted for https://github.com/AOMediaCodec/av1-avif/commit/a33fd7ba8d4d19bef2a59d843cc61f0642296d92 and omitted details only relevant for `.avifs` file extension workaround since upstream now uses just `.avif`
Archive of relevant files for record purposes: [imgs.zip](https://github.com/ImageMagick/ImageMagick/files/5540075/imgs.zip) https://github.com/AOMediaCodec/av1-avif/tree/a33fd7ba8d4d19bef2a59d843cc61f0642296d92/testFiles/Netflix/avis

**Comment by urban-warrior** [comment]
Can you verify your link?  We get a 404 on the link you provided.

**Comment by andrius4669** [comment]
umm yeah upstream renamed directory in https://github.com/AOMediaCodec/av1-avif/commit/a33fd7ba8d4d19bef2a59d843cc61f0642296d92 and they also renamed avifs files to avif now.
I'll update instructions to reflect the change.

**Comment by fmw42** [comment]
You might want to zip your files and post the zip file. That will prevent any changes to your files.

**Comment by andrius4669** [comment]
Instructions changed, also removed stuff about avifs extension because it's being phased out anyway (same extension will be used for both animated and non-animated images).

**Comment by dlemstra** [comment]
You are getting the error message `File does not include any supported brands.` because `avis` is not supported here: https://github.com/strukturag/libheif/blob/master/libheif/heif_file.cc#L218. Tried to add this locally but then it would break somewhere else. Support for adding this should be requested here: https://github.com/strukturag/libheif/issues. I don't understand why you are getting the other error message so you should probably also open a separate issue for that in their repository.
