### ISSUE TITLE
phash comparison ignores close-shaded pixels

### ISSUE THREAD

**Issue by Alepod** [ImageMagick/ImageMagick#2792]
### Prerequisites

- [✅ ] I have written a descriptive issue title
- [✅ ] I have verified that I am using the latest version of ImageMagick
- [✅ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
phash comparison ignores close-shaded pixels

### Steps to Reproduce
Just take sample images from https://github.com/ImageMagick/ImageMagick/issues/2781

> compare.exe -metric phash pix1.png pix2.png -> nul
> 0
> compare.exe -metric mepp pix1.png pix2.png -> nul
> 1 (5.1262e-06, 0.0039216)
> compare.exe -metric psnr pix1.png pix2.png -> nul
> 52.902

### System Configuration
- ImageMagick version: ImageMagick-7.0.10-35-portable-Q8-x64
- Environment (Operating system, version and so on): Win 8.1
- Additional information:

**Comment by fmw42** [comment]
The algorithm was not designed for 1x1 constant color images. Furthermore, the closer the colors the smaller the phash. Precision may also be at play since you are using Q8.
