### ISSUE TITLE
Histograms Output Problem

### ISSUE THREAD

**Issue by blue-j** [ImageMagick/ImageMagick#2801]
### Prerequisites

- [ x ] I have written a descriptive issue title
- [ x ] I have verified that I am using the latest version of ImageMagick
- [ x ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Histograms are outputting an inaccurate tallest bin at 255 intensity no matter what the image data is.  Both Fred and snigbo reproduced.  [https://github.com/ImageMagick/ImageMagick/discussions/2799
![histo](https://user-images.githubusercontent.com/3990142/98321655-7e573080-1f9a-11eb-9f01-9e771f270c53.gif)
](url)

### Steps to Reproduce

`convert in.jpg -alpha off -depth 8 -flatten -separate -append -strip -define histogram:unique-colors=false histogram:histo.gif`

### System Configuration
My build, installed with Homebrew on macOS 10.15.7:

ImageMagick 7.0.10-34 Q16 x86_64 2020-10-09
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): bzlib freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib

**Comment by urban-warrior** [comment]
The histogram is behaving properly.  The option order is important.  An alpha channel is required for the `-flatten` option.  If it does not exist, an opaque alpha channel is introduced for the flattening to work properly.  So for `-separate` you get 4 channels whereas you were expecting three.  The alpha channel returns all white.  Remove the alpha channel and you should get expected results.  Here is the magick you need:

`convert in.jpg -flatten -alpha off -separate -append -strip -depth 8 -define histogram:unique-colors=false histogram:histo.gif`

The ImageMagick command-line is a scripting language.  Like any programming language, you need to add debug statements at each step.  I found the problem promptly by using your command like this:

`convert in.jpg -alpha off -depth 8 -flatten -separate -append x:`

and immediately visualized the white at the bottom of the append image which caused the white spike @ the tail of the histogram.

**Comment by blue-j** [comment]
> The histogram is behaving properly. The option order is important. An alpha channel is required for the `-flatten` option. If it does not exist, an opaque alpha channel is introduced for the flattening to work properly. So for `-separate` you get 4 channels whereas you were expecting three. The alpha channel returns all white. Remove the alpha channel and you should get expected results.

You're very kind to help me with this.  You were absolutely correct, and have given very good advice.  Thank you!  I hope you're well during this craziness.  : )

- J
