### ISSUE TITLE
-evaluate-sequence returns multiple images when the inputs is so big

### ISSUE THREAD

**Issue by datalot-369** [ImageMagick/ImageMagick#2805]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [ ] I have verified that I am using the latest version of ImageMagick

### Description

If you pass too many arguments to this function, instead of outputting just one file, it outputs file-1, file-2, file-3... What appears to be a bug.

### Steps to Reproduce

- Extract more than `1.000` images from a video in a folder.
- `convert folder/* -evaluate-sequence mean out.png`

### System Configuration

- ImageMagick version: ImageMagick 6.9.10-23 Q16 x86_64 20190101
- Environment: MX Linux 19.2 amd64

### Additional information

- My `folder` has 1227 PNG samples of 640x480 pixels (~584.2 KiB) each one.
- At the end, the command returned me 545 images in the current directory, and the exit:

> `convert-im6.q16: cache resources exhausted '.temp_1604733724/i1000.png' @ error/cache.c/OpenPixelCache/4083.`

- While when I left only 50 files in the folder, `convert` gives me a single `out.png` (Expected result). This doesn't make sense.

---

What I'm doing is just a context menu shortcut to create a `median_output.png` from any `video` with a single click. Here's the command:

`tempistamp=$(date +%%s) && mkdir ".temp_${tempistamp}" && ffmpeg -i %f ".temp_${tempistamp}/i%%d.png" && convert ".temp_${tempistamp}"/* -evaluate-sequence mean "mean_${tempistamp}.png" && rm --dir --recursive ".temp_${tempistamp}"`

**Comment by fmw42** [comment]
Perhaps you are running out of RAM. When you read image, they get decompressed into 4 channels including alpha. In IM 6, you will have 640x480*4 bytes = 1.2 MB x 1226 images = 1.5 GB. Do you have that much space in your temp directory. You need to modify your policy.xml file as you are exhausting cache.

**Comment by datalot-369** [comment]
I have no idea how to restore my policy file to defaults, but I have:

```xml
<policymap>
  <policy domain="cache" name="memory-map" value="anonymous"/>
  <policy domain="cache" name="synchronize" value="True"/>
  <policy domain="cache" name="shared-secret" value="passphrase" stealth="true"/>
  <policy domain="system" name="shred" value="2"/>
  <policy domain="system" name="precision" value="6"/>
  <policy domain="system" name="memory-map" value="anonymous"/>
  <policy domain="system" name="max-memory-request" value="256MiB"/>
  <policy domain="system" name="pixel-cache-memory" value="anonymous"/>
  <policy domain="system" name="shred" value="2"/>
  <policy domain="system" name="precision" value="6"/>
  <policy domain="resource" name="temporary-path" value="/tmp"/>
  <policy domain="resource" name="memory" value="1GiB"/>
  <policy domain="resource" name="map" value="256MiB"/>
  <policy domain="resource" name="width" value="16KP"/>
  <policy domain="resource" name="height" value="16KP"/>
  <policy domain="resource" name="list-length" value="128"/>
  <policy domain="resource" name="area" value="128MB"/>
  <policy domain="resource" name="disk" value="1GiB"/>
  <policy domain="resource" name="file" value="768"/>
  <policy domain="resource" name="thread" value="4"/>
  <policy domain="resource" name="throttle" value="0"/>
  <!-- <policy domain="resource" name="time" value="3600"/> -->
  <!-- <policy domain="module" rights="none" pattern="{PS,PDF,XPS}" /> -->
  <!-- <policy domain="path" rights="none" pattern="@*" /> -->
  <!-- not needed due to the need to use explicitly by mvg: -->
  <!-- use curl -->
  <policy domain="delegate" rights="none" pattern="URL" />
  <policy domain="delegate" rights="none" pattern="HTTPS" />
  <policy domain="delegate" rights="none" pattern="HTTP" />
  <!-- <policy domain="delegate" rights="none" pattern="HTTPS" /> -->
  <!-- <policy domain="delegate" rights="none" pattern="MVG" /> -->
  <!-- in order to avoid to get image with password text -->
  <policy domain="path" rights="none" pattern="@*"/>
  <!-- disable ghostscript format types -->
  <policy domain="coder" rights="none" pattern="PS" />
  <policy domain="coder" rights="none" pattern="PS2" />
  <policy domain="coder" rights="none" pattern="PS3" />
  <policy domain="coder" rights="none" pattern="EPS" />
  <policy domain="coder" rights="none" pattern="PDF" />
  <policy domain="coder" rights="none" pattern="XPS" />
  <!-- <policy domain="coder" rights="none" pattern="MVG" /> -->
</policymap>
```

---

My free space in `/tmp` has `33 GiB` and in `/home` is `70 GiB`. I have `4 GB` RAM.
Hehe, I'm hard-restarted my PC just now because it was completely freeze after commenting all my policymap :facepalm:

**Comment by snibgo** [comment]
I suppose it is creating temporary files, and crashing because you have run out of resources.

You have:
```
<policy domain="resource" name="memory" value="1GiB"/>
<policy domain="resource" name="map" value="256MiB"/>
<policy domain="resource" name="disk" value="1GiB"/>
```
Limiting memory and map is fair enough, although I think map should be at least the same as memory. This will limit the cache in memory, and use disk instead.

But your disk limit is also very low. As fmw42 says, you need more than 1 GiB. I suggest you temporarily remove that line, or change it to 20GiB.

**Comment by datalot-369** [comment]
Changing `memory` to `2GiB` was enough for this time, giving me an expected resoult but at the cost of a high RAM ussage, but I have a lot of questions. Can you elaborate a response a little bit more detailed about the role of `map` and `disk` and what its values can cause?

As far as I know, when one is out, another is used, but the procedure, limitations, or meaning/definition of those values are out of my comprehension, and changing them randomly doesn't appear to be a good "solution".

If I run the command directly from the `video.file` (`convert %f -evaluate-sequence mean "mean_${tempistamp}.png"`), I get a failture with `list-length`, what also doesn't make sense because it work with the same amount of frames (1227) but ectracted with `FFMPEG` (`folder/*`) and increasing the `memory` to `2GiB`.

---

**Recap:** Please define the specific roles and functioning of the `map`, `disk`, and `list-length` policies.

**Comment by snibgo** [comment]
Ah, yes, I didn't notice that you have a list-length limit of 128 but read 1227 images. Again, I suggest you either remove the limit or change it to something larger.

Not every part of IM respects every limit, so that may be why "convert {video_file}" works.

For policy.xml settings, see https://imagemagick.org/script/resources.php, and search for "policy.xml".

For how pixel cache is used, see https://www.imagemagick.org/script/architecture.php
