### ISSUE TITLE
soversion went *down* in 7.0.10.36

### ISSUE THREAD

**Issue by antonio-rojas** [ImageMagick/ImageMagick#2806]
### Description
libMagickCore and libMagickWand soversions went down from 7 to 6 in version 7.0.10.36. This is totally unexpected behavior for shared libraries, the soversion should never decrease.

### Steps to Reproduce
Build 7.0.10.36, look at the library soversion

### System Configuration
- ImageMagick version: 7.0.10.36
- Environment (Operating system, version and so on): Liinux x86_64

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  We'll post a -37 release by end of day.

**Comment by remicollet** [comment]
@urban-warrior I see soname was bump to "8" in -37 patch release

BTW, as already explain in the past, please DO NOT do this in a patch release
At least worth to bump version (at least 3rd digit), which is used for path.
