### ISSUE TITLE
Problem to convert image *.avif to *.tiff

### ISSUE THREAD

**Issue by herb52** [ImageMagick/ImageMagick#2808]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I use program convert.exe from released versions: ImageMagick-7.0.10-xx-portable-Q16-HDRI-x64.zip on a Win10 system.
I use the following command:
convert.exe  testimage.avif  testimage.tiff
with image: one of the 10-bit avif images downloaded from http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/

With convert.exe from release
- 7.0.10-27 I get a *.tiff image with wrong colors
                  For this I found a bug-report which is corrected now
- 7.0.10-31 I get a correct generated *.tiff image
- 7.0.10-34 or higher: I get a "corrupted" *.tiff image which cannot be loaded e.g. by IrfanView
### Steps to Reproduce
Use program convert.exe from the mentioned releases: 7.0.10-27 to 7.0.10-37
Enter command in Windows Dos-box:  convert.exe testimage.avif testimage.tiff
with testimage e.g.: Chimera-AV1-10bit-1280x720-2380kbps-6.avif

### System Configuration
- ImageMagick version: 7.0.10-27 to 7.0.10.37
- Environment (Operating system, version and so on): Win 10
- Additional information:

**Comment by urban-warrior** [comment]
We leverage the HEIC delegate library to read the AVIF image format.  The bug may be in that library.  We tried 7.0.10-27, 7.0.10-31, and 7.0.10-37 and get the same discolored results when converting to the sRGB colorspace (e.g. -colorspace sRGB).  The problem may be with 10-bit AVIF image files.  We tried an 8-bit AVI image in the YCbCr colorspace and it converted to sRGB with expected results.  Saving the image in the TIFF format returned good results as well.

**Comment by fmw42** [comment]
Does it work if the AVIF image is scaled to 8-bits first, then converted to TIFF?

**Comment by herb52** [comment]
Hello,

Thanks for your comments.
To answer your questions:
- yes, the problem is only with 10-bit *.avif images.

For the following I will name convert.exe from file  ImageMagick-7.0.10-xx-portable-Q16-HDRI-x64.zip as convert(xx).exe
- convert(31).exe creates proper *.tiff images from 8-bit and 10-bit *.avif
  BUT: command "convert(31).exe -identify image.avif image.tiff" identifies also 10-bit images as 8-bit images.
  I remember to have read for the correction done in convert(31) somethings like: Yes, we now read all 10-bit avif-images as only or like 8-bit images.
- convert(37).exe creates proper *.tiff images from 8-bit files ( I have ) , but creates *.tiff that cannot be opened e.g. with IrfanView
  It identifies correctly 8-bit and 10-bit.

Best rgards
herb

**Comment by dlemstra** [comment]
Most TIFF viewers don't support 10bit images and this means that you will need to change the depth of the image to either 8 or 16 bit. It might be possible that we can properly read 10 bit images in the future so it might be a good idea to change the depth to 16 bit already (unless you use the Q8 version). But you could also use 8 as the depth for now. And other thing is that support for the YCbCr color space is not available in all the viewers so you should also change the colorspace.

The current TIFF encoder of ImageMagick has support for writing 10 bit images but our decoder has no support for that yet. I will need to investigate how easy it would be to add support for that. This is an extra note in case someone else finds this issue.

**Comment by herb52** [comment]
Hello dlemstar,

thanks for your detailed comments. They are really very very helpful.
It looks like, the proposed (additional) parameter will solve my problem.

Thanks and Best regards
herb
