### ISSUE TITLE
Convert multi-page PDF to TIFF results in 3 identical images per tiff page

### ISSUE THREAD

**Issue by careycane** [ImageMagick/ImageMagick#2813]
### Description
I have a multi-page PDF.

When I use ImageMagick to convert it to TIFF, the resulting TIFF repeats each PDF page three times.

### Steps to Reproduce

I've experimented with ImageMagick options. The basic command is:

```convert input.pdf output.tiff```

### Environment

I am running a Mac, Catalina. 

ImageMagick version:
Version: ImageMagick 7.0.10-31 Q16 x86_64 2020-09-28 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
 
#### Files
https://gofile.io/d/imbpnZ

**Comment by fmw42** [comment]
I can reproduce on IM 7.0.10.37 Q16 Mac OSX Sierra.

**Comment by t246246** [comment]
It happens also when I invoke ghostscript (9.53.3) directly:
"C:\Program Files\gs\gs9.53.3\bin\gswin64c.exe" -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72"  "-sOutputFile=out.tif" news.pdf

**Comment by fmw42** [comment]
I suspect your PDF is irregular or a version that IM does not understand

**Comment by t246246** [comment]
Seems to be img2pdf 0.4.0.

**Comment by fmw42** [comment]
Try a different converter? You can use Imagemagick to convert from your raster image to a PDF (though it won't vectorize).

**Comment by snibgo** [comment]
Adobe Acrobat reader can't read that PDF. Therefore it is a bad PDF.

**Comment by t246246** [comment]
I guess wrong icc profile is embedded from those pdf creating tool.

**Comment by fmw42** [comment]
I doubt it is a color profile issue.

**Comment by t246246** [comment]
Rewrite PDF using qpdf
That include

/ColorSpace [
    /ICCBased
    34 0 R
]

...

34 0 obj
<<
  /Alternate /DeviceGray
  /N 1
  /Length 35 0 R
>>

So it requires some gray profile.  I guess the embedded profile is for RGB or something require 3 values)

**Comment by snibgo** [comment]
It can certainly be read, eg by Gimp 2.10.0. But it seems to be a bad PDF. Maybe just the profile, I don't know.

**Comment by t246246** [comment]
This pdf is parsable, grammatically correct, but semantically wrong somewhere.  I think it is not a bug of ImageMagick/ghostscript.

@careycane If only you have is this pdf, you can extract jpeg images from it, by using pdfimages.  These jpeg files have  no problems. You can convert them to multi-tiff using ImageMagick.

**Comment by careycane** [comment]
I have a script that creates these PDFs using img2pdf. It pulls JPGs from the internet, concats them into a line, and then converts to PDF. 

I tried to use ImageMagick to do the same thing (`convert x.jpg y.jpg z.jpg output.pdf`) and am having the same issue with the resultant PDFs when I try to convert them to TIFF. 

So...maybe there's an issue upstream, with the JPGs I'm using the build the PDF. I'm at a loss.

**Comment by fmw42** [comment]
What version of Imagemagick? What platform?  See the comments above regarding color profiles and img2pdf.  I am having no problems with IM convert doing the processing. Does it fail with GIMP?

**Comment by t246246** [comment]
I see no problem with the following command.  (news.pdf is form your uploads copied to empty directory.)

% pdfimages -j news.pdf tmp
% magick tmp-*.jpg news.tif

By the way, ghostscript begin to start supporting ocr.
If you are interested, see https://ghostscript.com/ocr.html

**Comment by t246246** [comment]
I just installed img2pdf on my mac from macport. On the same directory,

% img2pdf tmp-*.jpg -o news2.pdf

create broken pdf.

Quote from https://pypi.org/project/img2pdf/
```
Bugs

    If you find a JPEG, JPEG2000, PNG or CCITT Group 4 encoded TIFF file that, when embedded into the PDF cannot be read by the Adobe Acrobat Reader, please contact me.
```

**Comment by t246246** [comment]
Those jpeg files has sRGB profile "Artifex Software sRGB ICC Profile" that is the cause of the problem.

This command can generate non-problematic pdf.

% for i in tmp-*.jpg; do magick $i +profile icc `echo $i | sed 's/tmp/tmp2/'`; done
% img2pdf tmp2-*.jpg -o news3.pdf

**Comment by careycane** [comment]
Okay, I've isolated the issue to img2pdf, and have a number of good options to resolve this. Agree this is not an IM issue. Closing with many thanks...
