### ISSUE TITLE
XWD? file format version mismatch when converting .ico file

### ISSUE THREAD

**Issue by AndreasGB** [ImageMagick/ImageMagick#282]
Hi,

When trying to convert the attached icon, I get the following error, while converting other icons works just fine. 

The icon also does not seem to be broken since gimp is capable of opening it, so I assume the problem is with imagemagick and not the icon.

I also tried to convert it on Arch Linux, where the same error is thrown.

Version used: ImageMagick 6.9.5-10 Q16 x86_64 2016-09-22

```
vagrant@vagrant-ubuntu-trusty-64:~$ convert chrome-icon.ico test.ico
convert.im6: file format version mismatch `chrome-icon.ico' @ error/xwd.c/ReadXWDImage/240.
convert.im6: no images defined `test.ico' @ error/convert.c/ConvertImageCommand/3044.


```

[chrome_icon.zip](https://github.com/ImageMagick/ImageMagick/files/503423/chrome_icon.zip)

**Comment by mikayla-grace** [comment]
Looks like a false positive.  While we investigate, use this command: ```convert icon:chrome-icon.ico test.ico```

**Comment by AndreasGB** [comment]
Hi mikayla-grace,

thanks for the quick reply. I encountered the problem originally when using the python library wand, do you happen to know how I could use the workaround there?

Kind regards,

AndreasGB

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
