### ISSUE TITLE
Memory leak for PingImage some svg

### ISSUE THREAD

**Issue by KngStr** [ImageMagick/ImageMagick#2821]
### Prerequisites

- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have written a descriptive issue title
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I'm trying to get size of images with `PingImage`.
But memory leak was found with some svg.

### Steps to Reproduce

Just run code with `MagickPingImage`.

### System Configuration

- ImageMagick version:
   7.0.10.34-Q16 HDR
- Environment (Operating system, version and so on):
   Win10 Enterprise 1903 x64

- Additional information:
    You can download test image from here: http://dl.kngstr.com/im.test.svg.7z

**Comment by dlemstra** [comment]
Can you provide a full code sample that demonstrates this issue? It might be possible that you are not cleaning something up in your code.

**Comment by KngStr** [comment]
Thanks for anwser.
But it works fine with other files.

I tested a lot of files. It should not be my fault.

**Comment by dlemstra** [comment]
You are giving me minimal information and not a small code sample that demonstrates this issue. You are asking me to invest time in something that could possibly be an issue in your code. If you have a small main.c (or .cpp, not sure what you are using) file that demonstrates this issue I can investigate this further.

**Comment by KngStr** [comment]
```
    try {
       
        //image.ping("F:\\Program Files\\ImageMagick-7.0.10-Q16\\test-svg.svg");
        auto wand = NewMagickWand();
        if (wand) {
            if (MagickPingImage(wand, "F:\\Program Files\\ImageMagick-7.0.10-Q16\\test-svg.svg") == MagickTrue) {
                auto width = MagickGetImageWidth(wand);
                auto height = MagickGetImageHeight(wand);
                std::cout << "width: " << width << ", height: " << height << "\n";
            }
            DestroyMagickWand(wand);
        }
        //std::cout << "fileName: " << image.fileName() << "\n";
    }
    catch (std::exception &e) {
        std::cout << "exception: " << e.what() << "\n";
    }
```

I'm using Pascal. Sorry for poor C++

**Comment by urban-warrior** [comment]
We use valgrind to detect memory leaks.  Your program and sample image returns:
```
==2957608== LEAK SUMMARY:
==2957608==    definitely lost: 0 bytes in 0 blocks
```
We switched to the internal renderer with the filename of `msvg:im.test.svg` and got the same results, no memory leaked.

**Comment by KngStr** [comment]
@urban-warrior 

Thanks.
I tested this with `Process Explorer`.
Look at this:

1. Start time
![start](https://user-images.githubusercontent.com/1308555/99141752-60b85400-2689-11eb-9478-f9643dccad31.jpg)

2. End time
![end](https://user-images.githubusercontent.com/1308555/99141759-69108f00-2689-11eb-812d-a3559ccc45ea.jpg)

3. Memory in task manager.
![task](https://user-images.githubusercontent.com/1308555/99141763-6e6dd980-2689-11eb-8316-40b79397b5e6.jpg)

Waited this for 30 mins. It keeps 1GB memroy along.
It should be memroy leak.

**Comment by urban-warrior** [comment]
Try the internal SVG renderer.  Add MSVG as an explicit format to your input filename, e.g. msvg:test-svg.svg. Without MSVG, we leverage an external renderer which must completely render the SVG image @ 15781x16611 first before it is `pinged` thus losing the advantage of speed and reduced resource consumption.  The internal renderer does not render the SVG when pinged.  Instead it exits early after capturing the SVG metadata such as the width/height and returns a speed advantage along with minimal memory consumption.

**Comment by dlemstra** [comment]
Thanks for reporting this @KngStr. It appears that there was a call missing to cleanup the `svg_handle` when pinging the image. This issues will be resolved in the next release.

**Comment by KngStr** [comment]
@dlemstra  Thanks.
@urban-warrior  Thanks. The internal renderer works well.

**Comment by KngStr** [comment]
Tested with 7.0.10.39. It fixed.

Thanks
