### ISSUE TITLE
convert of SVGs updates timestamps of working directory

### ISSUE THREAD

**Issue by slavistan** [ImageMagick/ImageMagick#2828]
### Description

The current working directory's timestamp of last modification is updated whenever `convert` is used on SVG files, but is not updated for other input file types such as PNG (see code example below). This is suprising and, as far as my inquiry goes, undocumented. May this be due to temporary files being created inside the working directory which are deleted immediately after? If so, I feel it would be more intuitive to use a central temporary directory, such as /tmp/.

This behaviour has caused me a couple of hours of headache until I could nail it down. I use `convert` to create temporary PNGs from SVG files for image previews since many image viewers don't handle SVGs particularly well. The problem is that file navigators like `ranger`, `vifm` or `lf`, which utilize these image previews, watch the timestamp of their working directory in order to update previews if files change. Now, a preview for a svg file updates the timestamp which in turn causes the preview to reload, which updates the timestamp etc. ad infinitium. This effect happens only for SVGs and not for other filetypes which made this issue particularly confusing. My current workaround is to move to another directory for the call to `convert`.

### Steps to Reproduce

Here's a self-contained script to demonstrate the "problem". Two images are downloaded for your convenience. Two conversions are performed and the timestamp of the current working directory is displayed before and after either conversion. The timestamp is changed only where the SVG file is involved.

```
#!/usr/bin/env sh

tempdir="$(mktemp -d)"
mkdir "$tempdir"/output
cd "$tempdir"
curl -s -L -o tux.svg "https://upload.wikimedia.org/wikipedia/commons/3/3a/Tux_Mono.svg"
curl -s -L -o tux.png "https://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png"

echo "tempdir = '$tempdir'"
echo "PNG -> JPEG:"
stat --printf='\tbefore: %y\n' .
convert tux.png output/tux.jpeg
stat --printf='\t after: %y\n' .

echo "\nSVG -> JPEG:"
stat --printf='\tbefore: %y\n' .
convert tux.svg output/tux.jpeg
stat --printf='\t after: %y\n' .
```

Exemplary output:
```
tempdir = '/tmp/tmp.BO1JDg71Hb'
PNG -> JPEG:
        before: 2020-11-14 17:37:23.092857446 +0100
         after: 2020-11-14 17:37:23.092857446 +0100

SVG -> JPEG:
        before: 2020-11-14 17:37:23.092857446 +0100
         after: 2020-11-14 17:37:23.132857949 +0100
```

### System Configuration

- ImageMagick version: ImageMagick 6.9.10-23 Q16 x86_64 20190101
- Environment: Ubuntu 19.10, Linux 5.3.0-64-generic

Kind regards.

**Comment by urban-warrior** [comment]
With the latest ImageMagick release, 6.9.11-38, we get expected results:

```
tempdir = '/tmp/tmp.KL33YxQjXL'
PNG -> JPEG:
        before: 2020-11-18 00:31:37.865142161 +0000
         after: 2020-11-18 00:31:37.865142161 +0000
\nSVG -> JPEG:
        before: 2020-11-18 00:31:37.865142161 +0000
         after: 2020-11-18 00:31:37.865142161 +0000
```

**Comment by slavistan** [comment]
I've updated to `ImageMagick 7.0.10-43 Q16 x86_64 2020-11-23` and I can confirm that the problem no longer exist. Thank you!
