### ISSUE TITLE
ImageMagick can setting config to not write temporary files

### ISSUE THREAD

**Issue by dongjiang1989** [ImageMagick/ImageMagick#2831]
ImageMagick can setting config to not write temporary files!

so mang files
magick--43AJkqaS8RmLCl-eTQmsbk8VZf__WJw magick-B-3SOxNZUbsJfvnv-TGviGbdVZUX5Pc6 magick-Nomo-0oxRBTP44U4utbKPWwPgebHMIP7 magick-dxUIR5OS1tER6jlXGyXag8xqANDHJ1jq magick-taMbqO-4ljWi-StZCrh6rxfq9S7XiZgy
magick--CAoCkyo2oNhnCxiqNjIt0xEXZostRfk magick-BP8YlExgtUMSijhG5t3cXodCJO4S4SQn magick-P55VhEW8WSrF-8Pcx4ZfA0Zq5n-M6_U8 magick-e-r-IP_vLAgunLbkhdRz6aeYE_K9Kq3y magick-tbLniU60itWwVuwjKstkz1xY5cMG5CBO

**Comment by dlemstra** [comment]
What are you asking or telling us?

**Comment by dongjiang1989** [comment]
When I use imagemagic for watermark operation, the / TMP / Magic XXX file affects the efficiency of imagemagic processing. Is there a config configuration to close it?

watermark image format 『SVG』

**Comment by snibgo** [comment]
You can use "-limit disk 0". This will prevent IM from storing pixel caches on disk. But then, if IM needs to do this, the command will fail, so it doesn't solve your problem.

I'm not sure what problem you want to solve. Please show a sample command with sample input files.

**Comment by urban-warrior** [comment]
See https://imagemagick.org/script/architecture.php for an in-depth discussion about why some pixel operations end up on disk rather than memory.
