### ISSUE TITLE
SSIM metric issue when comparing images with transparent background

### ISSUE THREAD

**Issue by zhutq** [ImageMagick/ImageMagick#2835]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

`magick compare -metric SSIM` on two images with transparent background seems counting the RGB value of totally transparent pixels and returns low value, although the images actually look the same.

### Steps to Reproduce

The input image is: https://github.com/zhutq/filehost/blob/master/png_ssim/minnie.png
I convert the image to webp then back to png
```
magick minnie.png -quality 100 minnie.webp
magick minnie.webp minnie.webp.png
```
The result is: https://github.com/zhutq/filehost/blob/master/png_ssim/minnie.webp.png
Then compare the two images with SSIM metric:
```
magick compare -metric SSIM minnie.png minnie.webp.png null:
```
The result is only 0.614659.
dssim 2.11.3 returns 0.00046943.

However, if I fill the background of both images with white,
```
magick minnie.png -background white -alpha remove minnie.opaque.png
magick minnie.webp.png -background white -alpha remove minnie.webp.opaque.png
```
Then compare
```
magick compare -metric SSIM minnie.opaque.png minnie.webp.opaque.png null:
```
returns 1. (dssim returns 0.00221810.)

The process is also in https://github.com/zhutq/filehost/blob/master/png_ssim/test.sh

### System Configuration

- ImageMagick version:
Version: ImageMagick 7.0.10-38 Q16 x86_64 2020-11-15 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib

- Environment (Operating system, version and so on):
macOS Big Sur
version 11.0.1

- Additional information:

**Comment by fmw42** [comment]
The reason for the difference is that the original minnie.png background color under the transparency is green. 

![minnie_aoff](https://user-images.githubusercontent.com/13458218/99466982-41702f80-28f2-11eb-975e-175865ed8a3c.png)


But when it is converted to webp, the color under the alpha is converted to black.

![minnie_webp_aoff](https://user-images.githubusercontent.com/13458218/99466986-4503b680-28f2-11eb-8b52-763bd09a451b.png)

**Comment by zhutq** [comment]
@fmw42 agreed.
IMHO compare should consider this case. SSIM is a perceptual metric so  counting invisible differences is  confusing.

**Comment by fmw42** [comment]
I will leave that to the IM developers. But in my opinion, it would be better if the conversion to webp preserved the underlying colors rather than change the color under transparency to black.

**Comment by snibgo** [comment]
> SSIM is a perceptual metric so counting invisible differences is confusing.

IM generally ignores the alpha channel when comparing. But you can use a read mask, derived from one alpha channel or both alpha channels. See https://www.imagemagick.org/discourse-server/viewtopic.php?f=4&t=31053

**Comment by dlemstra** [comment]
We cannot preserve the green color @fmw4. It looks like the webP encoder (or maybe the decoder?) ignores the RGB values when the alpha channel is zero and defaults them to black.
