### ISSUE TITLE
Why SVG not support blob

### ISSUE THREAD

**Issue by linfangrong** [ImageMagick/ImageMagick#2836]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

****
```code
MagickCore/magick.c: 194
magick_info->flags=CoderAdjoinFlag | CoderBlobSupportFlag |
    CoderDecoderThreadSupportFlag | CoderEncoderThreadSupportFlag |
    CoderUseExtensionFlag
```

```code
coders/svg.c: 3766  3780  3795

entry->flags^=CoderBlobSupportFlag
```

BlobSupportFlag is false

### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
You are right, SVG is designed to be streamed.  Random access may of been needed sometime ago but that's not the case now.  We'll add a patch to fix the problem.
