### ISSUE TITLE
[7.0.3-3] Failed tests

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick#284]
```
FAIL: tests/validate-formats-memory.tap 1
FAIL: tests/validate-formats-disk.tap 1
FAIL: tests/validate-formats-map.tap 1
```
Everything ok with 7.0.3-2
6.9.6-1 is also OK.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by remicollet** [comment]
Indeed, adding the linked patch fix the test suite.
Thanks.
