### ISSUE TITLE
Merge libheif 1.9+?

### ISSUE THREAD

**Issue by ScriptTiger** [ImageMagick/ImageMagick#2845]
Can we get the latest libheif merged into the ImageMagick delegate? The current delegate, 1.8, has color distortion issues preventing actual lossless AVIF conversion. These issues were addressed in the 1.9 release.

The issues related to this were already much better documented by others, so I don't want to be too redundant here. Obviously everyone here is already familiar with libheif since that's what ImageMagick is using, so this is just a basic bump request to make a lot of ImageMagick users waiting for actual lossless AVIF happy before the holidays. Unless we're waiting for the major 2.0 release? I'm not familiar with the current milestones of this project, so forgive me if this is premature.

Related issues:
https://github.com/strukturag/libheif/issues/288
https://github.com/strukturag/libheif/issues/304

**Comment by dlemstra** [comment]
I suspect that you are using the Windows build? We just updated both the libde265 and the libheif to the most recent version.
