### ISSUE TITLE
text breaks when converting pdf to png

### ISSUE THREAD

**Issue by logosha** [ImageMagick/ImageMagick#2846]
Hello,
I am trying to convert png from pdf, but I get unexpected result, the text in the image is broken,
I attached the original pdf document and the resulting image
ImageMagick: Portable-Q16-x64 7.0.10.32
Ghostscript: 9.04 (at 9.25 the text also breaks)
command: convert -density 150 -colorspace RGB simple.pdf [0] -profile sRGB.icm -depth 8 -type TrueColorMatte simple_forIM.png

if density is in the range from 120 to 220 dpi, then the text breaks, if outside, then everything is in order.
Could you check why this is happening?
thanks
[simple.pdf](https://github.com/ImageMagick/ImageMagick/files/5566305/simple.pdf)
![simple_forIM](https://user-images.githubusercontent.com/13949928/99658243-e2ccc200-2a67-11eb-936c-2185ca6fcb01.png)

**Comment by fmw42** [comment]
You have a very old Ghostscript and a bit old IM. I suggest you upgrade atlas GS. This command works fine for me on IM 7.0.10.39 Q16 Mac OSX Sierra with GS 9.50.

`magick -density 150 -colorspace sRGB simple.pdf[0] -profile /Users/fred/images/profiles/sRGB.icc -depth 8 -type TrueColorMatte simple_forIM.png`

Note, when using IM 7, use magick not convert. However, that is not likely going to change this issue.

![simple_forIM](https://user-images.githubusercontent.com/13458218/99691663-53f77f80-2a3e-11eb-8a1e-6c766424a7c3.png)

**Comment by logosha** [comment]
Thanks, for your answer, I updated gs, now it works
