### ISSUE TITLE
Unexpected end-of-file when identifying .ico file 

### ISSUE THREAD

**Issue by AndreasGB** [ImageMagick/ImageMagick#285]
Hi,

I have two icon files which trigger the following error when identifying them with ImageMagick version 6.9.6-0. Gimp can open them, so I guess they are not broken.

The german part of the error translates to "File or directory not found"

```
identify 12c06945babcb531d4aa546151b4d79bbbf6bcc44b49fa4727e5e370c075079d.ico                  1 ↵
12c06945babcb531d4aa546151b4d79bbbf6bcc44b49fa4727e5e370c075079d.ico[0] PNG 256x256 256x256+0+0 8-bit sRGB 238KB 0.000u 0:00.000
12c06945babcb531d4aa546151b4d79bbbf6bcc44b49fa4727e5e370c075079d.ico[1] ICO 128x256 128x256+0+0 32-bit sRGB 238KB 0.000u 0:00.000
identify: unexpected end-of-file `12c06945babcb531d4aa546151b4d79bbbf6bcc44b49fa4727e5e370c075079d.ico': Datei oder Verzeichnis nicht gefunden @ error/icon.c/ReadICONImage/706.

```

The icons are in the attached zip:

[failingIcons.zip](https://github.com/ImageMagick/ImageMagick/files/518541/failingIcons.zip)

Thank you very much,

AndreasGB

**Comment by mikayla-grace** [comment]
The images are corrupt.  The height value is 0 which means the image height is 256 per https://en.wikipedia.org/wiki/ICO_(file_format).  The ```file``` command confirms our conjecture:
```
-> file 021e0d4fcf8f01f822af645b2866e68322cc4ca37ab668e71d0ffe042151b06b.ico 
021e0d4fcf8f01f822af645b2866e68322cc4ca37ab668e71d0ffe042151b06b.ico: MS Windows icon resource - 4 icons, 128x256
```

However, if we force the height to 128, ImageMagick reads it properly.

**Comment by AndreasGB** [comment]
Okay, thanks very much.
