### ISSUE TITLE
[Not a bug report but there was no other type to pick that made sense] [Cosmetics] Please make the FTP listing show at the least towards the file type of the download

### ISSUE THREAD

**Issue by rubyFeedback** [ImageMagick/ImageMagick#2852]
Hey there ImageMagick devs,

This issuse is mostly about cosmetics; but the good thing is that it should be trivial to change. :)

But first - the templates to choose from right now only, like, allow us to pick 3 different types
here on the issue tracker. Bug report, "ask a question" and security problem. It would be useful
if a fourth option would be added, aka "any other type" or something like this. Because my 
issue is mostly about cosmetics or such.

Anyway.

If you go there:

http://www.imagemagick.org/download/

You see lots of downloads. I usually pick .tar.xz but if I look at the FTP listing
I can not see which one of these is .tar.xz. So I have to scan manually with my
mouse, until I find the right variant.

I would like to suggest to, instead, show at the least the full FILE PATH of the
individual file, on the left hand side.

To see how this can be done, have a look at the Gnome FTP listing which
was recently changed to look a bit "nicer" by default:

https://download.gnome.org/sources/gedit/?C=M;O=D
https://download.gnome.org/sources/gedit/3.38/?C=M;O=D

If you look at the latter, you see that the file name + extension is
instantly shown. I suppose there is an easy way to enable this
in apache httpd or whatever else is used by ImageMagick.

Hopefully that is a simple issue request, but please do feel 
completely free to close this issue at any moment in time, for
any reason - I understand wanting to keep the issue 
listing small and tidy.

**Comment by urban-warrior** [comment]
File folder listings are controlled by the browser.  We have no control over the style so we cannot resolve this issue.
