### ISSUE TITLE
convert interprets SVG transform:rotation parameter list wrong

### ISSUE THREAD

**Issue by infusion** [ImageMagick/ImageMagick#2855]
I use `ImageMagick 7.0.10-34 Q16 x86_64 2020-10-09` on MacOS 10.15.3 and tried to convert an SVG to a JPG/PDF using `convert`.

Everything works fine except that `transform="rotate(34.984589831749304 120 50)"` ignores the transform origin. In Inkscape, Firefox and Chrome this syntax is interpreted correctly:

![image](https://user-images.githubusercontent.com/197742/99908136-1f572280-2ce1-11eb-8fe9-85fb970b2906.png)

After using `convert` the result looks like this:

![image](https://user-images.githubusercontent.com/197742/99908150-372ea680-2ce1-11eb-9679-aac1dc51930a.png)

Thanks for Imagemagic and your work!

**Comment by fmw42** [comment]
ImageMagick can use any of its internal MSVG/XML, RSVG delegate or Inkscape (in order of best processing). Imagemagick's internal MSVG/XML renderer is the most primitive and Inkscape is the most capable. I suggest simply installing Inkscape on your system and ImageMagick should use that over its internal renderer.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later this week.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime next week.
