### ISSUE TITLE
import: fails to start rectangular portion grabber in some games

### ISSUE THREAD

**Issue by bgkillas** [ImageMagick/ImageMagick#2860]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

in say csgo while you are in a match import fails and gives this error
```
import: unable to grab mouse '': No such file or directory @ error/xwindow.c/XSelectWindow/9301.
import: unable to read X window image '': Success @ error/xwindow.c/XImportImage/4933.
import: unable to read X window image '': Success @ error/xwindow.c/XImportImage/5040.
import:  `file' @ error/import.c/ImportImageCommand/1285.
```
### Steps to Reproduce

get into a match in csgo
use import while in the match
### System Configuration

- ImageMagick version: 7.0.10-43
- Environment (Operating system, version and so on): arch linux, kde plasma
- Additional information:

**Comment by urban-warrior** [comment]
Its possible csgo exclusively grabs the mouse preventing other programs from grabbing the mouse.  You can always bypass the mouse and grab the screen with the -screen or -window option.
