### ISSUE TITLE
Relative paths needed instead of absolute paths

### ISSUE THREAD

**Issue by thirdknife** [ImageMagick/ImageMagick#287]
I am building ImageMagick with openEXR support. I have built it successfully, the only issue left is; that I want to ship ImageMagick to other systems as well. 

otool for ./magick executable returns a link to .dylibs with an absolute path. 

`/Users/<user>/ImageMagick/ilmbase/lib/libImath-2_2.12.dylib`

What I need instead is a relative path using @executable_path.

How the script will copy all libs and link them with a relative path.

**Comment by mikayla-grace** [comment]
Use the ```configure``` script ```--disable-installed``` option.  See http://www.imagemagick.org/script/advanced-unix-installation.php.

**Comment by dlemstra** [comment]
Can we close this issue @thirdknife?

**Comment by thirdknife** [comment]
Yes sure, I figured there is no way in the ./configure script to make paths relative but that is a manual task.
