### ISSUE TITLE
Color issues when converting SVGs

### ISSUE THREAD

**Issue by kiloreux** [ImageMagick/ImageMagick#2872]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When trying to convert this [file](https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/vnu.svg)

With the following command:

`convert  -verbose vnu.svg -auto-orient -background 'rgba(0,0,0,0)' -channel RGB result.svg` 

It will produce a white and black image. Instead of a normal one that preserves colors. Which is not the desired behavior in this case. 

### Steps to Reproduce

`convert  -verbose vnu.svg -auto-orient -background 'rgba(0,0,0,0)' -channel RGB result.svg` 

### System Configuration
Ubuntu-20.04 

- ImageMagick version: ImageMagick 7.0.10-43 Q16 x86_64 2020-11-26
- Environment (Operating system, version and so on): Ubuntu-20.04 
- Additional information: Features: Cipher DPC OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib heic jbig jng jp2 jpeg lcms lqr lzma openexr png ps raw rsvg tiff webp x xml zlib

**Comment by snibgo** [comment]
IM is a raster image processor, not a vector image processor. SVG is a vector format that can contain raster images, but your SVG doesn't.

Your command doesn't seem to do anything useful. You could simply copy vnu.svg to result.svg.

**Comment by kiloreux** [comment]
@snibgo I initially wanted to resize it. How would you suggest I go about it?

**Comment by snibgo** [comment]
Your SVG has only vector operations, with no physical dimensions. So what do you mean by "resize"? In what way should your output SVG be different to your input SVG?

**Comment by kiloreux** [comment]
Okay, I got it. Thanks for the pointer.
