### ISSUE TITLE
Feature request: SVG groups read modifier

### ISSUE THREAD

**Issue by rdoursenaud** [ImageMagick/ImageMagick#288]
Unless my research have not been thorough enough, it seems that ImageMagick can't pick a specific SVG group.
SVG groups are often used for layers (i.e.: Inkscape uses it).
Converting a single layer to another format is often desirable.
A group read modifier would be very helpful for converting icons and the likes.

References:
https://www.imagemagick.org/Usage/files/#read_mods
https://www.w3.org/TR/SVG11/struct.html#Groups

**Comment by dlemstra** [comment]
I don't think this is a feature that should be added to ImageMagick. We would need to parse the XML and remove the groups that you don't want in your output image. You can do that yourself before you give the SVG file to ImageMagick.
