### ISSUE TITLE
PSD Conversion: Insufficient Image Data In File

### ISSUE THREAD

**Issue by bvb-sc** [ImageMagick/ImageMagick#2888]
### Description
Using Image Magick 7.0.10-44 (originally found issue on 7.0.10-24). When using the following command on the file provided, we receive the error message below:

```
convert "file.psd[0]" "file.png"

> convert: insufficient image data in file 'file.psd' @ error/psd.c/ReadPSDImage/2599.
> convert: no images defined 'file.png' @ error/convert.c/ConvertImageCommand/3298.
```

 On a much older version (6.9.3-10), we do not face the same issue and the file conversion happens as expected.

### Steps to Reproduce
Execute this command on the provided file: 
```
convert "file.psd[0]" "file.png"
```

### System Configuration

- ImageMagick version: 7.0.10-24, 7.0.10-44
- Environment (Operating system, version and so on): Windows 10, Linux Ubuntu 20.04, Linux Bionic 18.04
- Additional information: works as expected on IM 6.9.3-10

[file.zip](https://github.com/ImageMagick/ImageMagick/files/5616717/file.zip)

**Comment by dlemstra** [comment]
Your file has a corrupt merged layer (image 0) but we had a work around for this in earlier versions. This seems to be broken now. I just pushed a patch to fix this. This issue will be resolved in the next release.
