### ISSUE TITLE
Make sure documentation is also mobile ready

### ISSUE THREAD

**Issue by jidanni** [ImageMagick/ImageMagick#2904]
http://www.imagemagick.org/Usage/text/ is an example of a documentation page that is not yet mobile ready.

Certainly a few simple changes could be made and then the document could be read on both desktop browsers and mobile devices. Therefore as a long-term goal these accessibility improvements should be made.
![Screenshot_20201202-220521](https://user-images.githubusercontent.com/1230959/100885897-1ee33680-34ee-11eb-9c7c-3d9f9a37f688.jpg)

**Comment by snibgo** [comment]
You can submit a pull request to https://github.com/ImageMagick/Website

> Certainly a few simple changes could be made...

Perhaps you can say what those changes are, or link to a guide.

**Comment by dlemstra** [comment]
The usage documentation is in this repository: https://github.com/ImageMagick/Usage. We won't be changing this ourselves anytime soon.

**Comment by urban-warrior** [comment]
The Usage pages are legacy pages contributed by @antofthy.   We thank him for his contribution.  Anyone in the community can port the pages to mobile ready from the Usage repo @ https://github.com/ImageMagick/Usage per @dlemstra.  The ImageMagick team will continue to support the mobile-first web site @ https://imagemagick.org but not the Usage pages.  It requires a level of commitment that our small team is not in a position to honor.

**Comment by jidanni** [comment]
Here you go!:
https://search.google.com/test/mobile-friendly

**Comment by jidanni** [comment]
OK, but I would leave this issue open. Else they will never get mobilized.

**Comment by urban-warrior** [comment]
We added a mobile friendly viewport to the Usage pages and they now pass the mobile friendly Google test.

**Comment by jidanni** [comment]
OK but these table layouts will never fit
![20201213T221114](https://user-images.githubusercontent.com/1230959/102014299-3e048280-3d90-11eb-9dc5-cc254383ca7f.jpg)

**Comment by urban-warrior** [comment]
Again, the pages are open source.  Anyone in the community can contribute toward the goal of making the Usage pages more mobile friendly.  Setting the viewport was just one step toward that goal.

**Comment by jidanni** [comment]
Actually it might be quite easy to fix,
https://www.google.com/search?q=table+layouts+mobile+friendly

**Comment by urban-warrior** [comment]
Post a pull request with your mods and we will merge them and update the web site so that the tables are more mobile friendly.  Thanks in advance for your contribution.
