### ISSUE TITLE
"-features" and "-moments"

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#2906]
### Prerequisites

- [y] I have written a descriptive issue title
- [y] I have verified that I am using the latest version of ImageMagick
- [y] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
"-features" and "-moments" are options listed on https://imagemagick.org/script/command-line-options.php

However, with IM v7.0.10-45 pre-build binary on Windows 8.1, they are not recognized.

### Steps to Reproduce
```
f:\web\im>magick rose: -feaures 3 info:
magick: unrecognized option `-feaures' at CLI arg 2 @ fatal/magick-cli.c/ProcessCommandOptions/428.

f:\web\im>magick rose: -moments info:
magick: unrecognized option `-moments' at CLI arg 2 @ error/operation.c/CLISimpleOperatorImage/2909.
```

### System Configuration

Windows 8.1
IM v7.0.10-45 pre-build binary

**Comment by dlemstra** [comment]
The first command contains a typo?

**Comment by snibgo** [comment]
Oops, yes, it does, thanks. But fixing that still shows the problem:
```
magick rose: -features 3 info:

magick: unrecognized option `-features' at CLI arg 2 @ error/operation.c/CLISimpleOperatorImage/2452.
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by urban-warrior** [comment]
The -features option was deprecated for ImageMagick version 7.  Use this command instead: `magick rose: -define identify:features=true -verbose info:`

**Comment by urban-warrior** [comment]
We'll add support for -features in the next release.  In the mean-time, use `magick identify rose: -features 3...` or `-verbose -define identify:features=3`.
