### ISSUE TITLE
converting to PBM (P1) - rows of characters don't match lines of pixels

### ISSUE THREAD

**Issue by belvsdragon** [ImageMagick/ImageMagick#294]
I wrote a shell script on Fedora 24 that uses ImageMagick to convert an image (BMPs or PNG) to the PBM ASCII format and then parses it.
The result was always that every row of ones and zeros represents one line of pixels. But now i am using Ubuntu 16.04 and the result is that the rows are filled with a fixed number of characters. So I can't parse the file by rows and columns any more.

Is this a bug? And if not is there a flag to turn this off?

**Comment by fmw42** [comment]
See http://netpbm.sourceforge.net/doc/pgm.html. If P2 (ascii), then there appears to be a limit of 70 characters per line. Perhaps this is an issue with NetPBM version or your OS limitations?

**Comment by belvsdragon** [comment]
You are right. This is part of the file format definition. [http://netpbm.sourceforge.net/doc/pbm.html](http://netpbm.sourceforge.net/doc/pbm.html) 

> No line should be longer than 70 characters.

I don't understand what the practical advantage of this rule is, because it messes up all rows and columns. So it becomes more difficult to parse and convert.  And it doesn't even look better. A 16x16 picture gets scattered over 6-7 lines. 

The other thing I don't understand is why Fedora 24 has a version with the usefull rules and Ubuntu 16.04 has a version with the useless 70 character per line rule. This is rather feature than a bug in Fedora 24.

**Comment by fmw42** [comment]
Just out of curiosity, why are your images producing 1s and 0s?  Are you converting binary images?  What is your goal for having to convert to PGM and parse the data?  Could you not just write your images to IM txt: format and parse that. See http://www.imagemagick.org/Usage/files/#txt

**Comment by belvsdragon** [comment]
Additionally I have to say "No line should be longer than 70 characters." doesn't mean "Every line has to be 70 characters long." So in relation to smaller images this should be reconsidered.

**Comment by fmw42** [comment]
Have you checked the versions of NetPBM? Are they the same or different?

**Comment by belvsdragon** [comment]
My goal was to paint monochrome pixelart and convert it to unicode block characters. Like this:

████████████████████████████████
██████████▀▀▀░░░░░░▀▀▀██████████
████████▀░░▄▄▗▖▖▄▄▗▖▖░░▀████████
██████▛▘░░░█▖▐▌▌█░▐▙▘░░░▝▜██████
█████▘░░░░░█░▐▙▌█▄▐▛▖░░░░░▝█████
████▘▗▘░░░░░░░░░░░░░░░░░░▝▖▝████
███▌▗▘░▐▛▘█▜▐▛▘▜▛▐▛▘▟▙▐░▌░▝▖▐███
███░▞░░▝▜▌█▐▐▌░▐▌▐▛░▜▛▝█▘░░▚░███
██▌▗▘▘░▝▀▘▀▀▝▀▘▀▀▝▀▘▝▘░▀░░▖▝▖▐██
██▌▐▘▖▗░▄▄▖░░░░░░░░░░▗▄▄░░▗▝▌▐██
██░▐▙▗▄▀░░░░░▀▚▄▄▞▀░░░░░▀▟▖▟▌░██
██░▐█▛░░▗▙▄▄▖░░▝▘░░▗▄▄▄▌░░▜█▌░██
██▖░▀░░▗█████▙░▖░░▟█████▖░░▀░▗██
██▌░░░▗███████▙░▖▟███████▖░░░▐██
██▙░░▄█████████▖▗█████████▄░░▟██
███▖░▝█████████▌▐█████████▘░▗███
███▙░▘█████████▌▐█████████░▘▟███
████▙░▞████████▘▝████████▚░▟████
█████▙░▜███████▖░███████▛░▟█████
██████▘░█████▛░░▝░▜████▛▘▝██████
██████▝▙▖▝▀▀▘▗░▌▐░▖▝▀▀▘▗▟▘██████
██████▙▟█▙▄▄▞▘▟▌▐▙▝▚▄▄▟█▙▟██████
████████▌▜▘▖░░░▘▝░░░▗▝▛▐████████
█████████▛▌░▖░░░░░░▗░▐▜█████████
█████████░▙▗░▝░▘▝░▘░▖▟░█████████
█████████░▘▜▄▌░▌▐░▐▄▛▝░█████████
█████████▖▝▝░▛▀▛▜▀▜░▘▘▗█████████
█████████▌▗░▘▗░▖▗░▖▝░▖▐█████████
██████████▟░░░░░░░░░░▙██████████
███████████▄░░░░░░░░▄███████████
██████████████▄▄▄▄██████████████
████████████████████████████████

The format mentioned in your link could be a workaround for my problem. Or I just find a way to parse the 70 character per line Frankenstein format. :D 
I am confused about what the versions are:
[http://packages.ubuntu.com/xenial/netpbm](http://packages.ubuntu.com/xenial/netpbm)
 netpbm (2:10.0-15.3)

[http://koji.fedoraproject.org/koji/packageinfo?packageID=104](http://koji.fedoraproject.org/koji/packageinfo?packageID=104)
 netpbm-10.75.99-1.fc24

`netpbm -version` doesn't work.

**Comment by fmw42** [comment]
Sorry, I do not know about those versions. 

But see http://www.imagemagick.org/Usage/quantize/#diy_symbols

**Comment by dlemstra** [comment]
I did a quick check through our code and it appears we don't limit the line length to 70 characters we allow much bigger lines. So I don't understand why you are experiencing an issue. I am also a bit confused about the netpbm talk, we don't maintain or work on that library.
