### ISSUE TITLE
Perl spurious lib

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#295]
Could you apply the folliowing patch magick.xs and magick.pm are not needed due to using default wrapper

**Comment by bastien-roucaries** [comment]
I means you could delete perlmagick/magick.*

**Comment by mikayla-grace** [comment]
We need Magick.xs, Magick.pm, and Makefile.nt for the Windows build of PerlMagick.

**Comment by bastien-roucaries** [comment]
It generate on unix magick.so that is not needed due to parent def

**Comment by dlemstra** [comment]
Can we close this issue @bastien-roucaries?

**Comment by bastien-roucaries** [comment]
Yes
