### ISSUE TITLE
Test failures after 5d934588341f78ed0aa8278f3fc5a55db2d66ed2

### ISSUE THREAD

**Issue by antonio-rojas** [ImageMagick/ImageMagick#2959]
### Description

Commit 5d934588341f78ed0aa8278f3fc5a55db2d66ed2 is causing test failures on Arch Linux:
```
FAIL: tests/validate-formats-memory.tap 1
FAIL: tests/validate-formats-map.tap 1
FAIL: tests/validate-formats-disk.tap 1
```
The logs show errors such as
```
lt-validate: Sorry, can not handle images with 12-bit samples. `/tmp/magick-bxyxoB0cKk2hFrGc3Llvzc-vas5VjLi3' @ error/tiff.c/TIFFErrors/661.
  test 673: PTIF/Undefined/TrueColor/10-bits... fail @ tests/validate.c/ValidateImageFormatsInMemory/1664.
    reason:Sorry, can not handle images with 10-bit samples. `/tmp/magick-bxyxoB0cKk2hFrGc3Llvzc-vas5VjLi3' @ error/tiff.c/TIFFErrors/661
  test 674: PTIF/Undefined/TrueColor/12-bits... fail @ tests/validate.c/ValidateImageFormatsInMemory/1664.
    reason:Sorry, can not handle images with 12-bit samples. `/tmp/magick-bxyxoB0cKk2hFrGc3Llvzc-vas5VjLi3' @ error/tiff.c/TIFFErrors/661
```

### Steps to Reproduce
Build 7.0.10.47 and run the test suite

### System Configuration

- ImageMagick version: 7.0.10.47
- Environment (Operating system, version and so on): Arch Linux x86_64
- Additional information:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
