### ISSUE TITLE
'Unknown marker type 194 in JPEG data' When loaded tif file

### ISSUE THREAD

**Issue by KngStr** [ImageMagick/ImageMagick#2962]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When loaded tif file, I got error ```Unknown marker type 194 in JPEG data. `OJPEGReadHeaderInfoSec' @ error/tiff.c/TIFFErrors/661```

My test file: 
[image0040.zip](https://github.com/ImageMagick/ImageMagick/files/5670880/image0040.zip)

  Error screenshot: 
![IM ERROR JPEG 194](https://user-images.githubusercontent.com/1308555/101733946-8e62b280-3afa-11eb-8158-f74296a893f7.jpg)

### Steps to Reproduce

Just load with imdisplay.

### System Configuration

- ImageMagick version:
   ImageMagick-7.0.10-47-portable-Q16-x64
- Environment (Operating system, version and so on):
   Windows 7 Ultimate 6.1.7601 x64

- Additional information:

**Comment by fmw42** [comment]
I think your TIFF file is either corrupt or malformed. I tried several tools to open it including Photoshop and none of them will even open your file.

**Comment by KngStr** [comment]
@fmw42  Maybe, but the default tool of windows 7 and windows 10 can open it.

**Comment by fmw42** [comment]
Are your TIFF files JPG compressed. If so and they are using an obsolete JPG compression, then libtiff, which ImageMagick use, cannot read that format. Otherwise, I will step back and leave it to the IM developers.

**Comment by KngStr** [comment]
@fmw42 

Thanks.

I don't know if it is JPG compressed.
This file from scanner.
So where can I get libtiff program for testing?

BTW: IM supports TIFF files JPG compressed

**Comment by fmw42** [comment]
I suspect you have the old obsolete JPG compression from your error message.

*When loaded tif file, I got error Unknown marker type 194 in JPEG data.*

You must have libtiff installed with ImageMagick if you are processing tiff files. So it should be on your system.  But you can find it at http://www.libtiff.org.

My guess is that your Windows system can  handle the old style JPG compression, but libtiff cannot.

**Comment by KngStr** [comment]
@fmw42 

The libtiff is in IM. I can't test it alone.

OK. Thanks.

**Comment by fmw42** [comment]
It can be tested alone. Or download another version and use that.

**Comment by KngStr** [comment]
@fmw42 

Really? How can it be tested?

**Comment by fmw42** [comment]
If I create a simple tiff file:

convert logo: logo.tiff

Then use libtiff's tiffinfo command, I get

```
tiffinfo -D logo.tiff
TIFF Directory at offset 0x6e04 (28164)
  Image Width: 640 Image Length: 480
  Bits/Sample: 8
  Compression Scheme: LZW
  Photometric Interpretation: palette color (RGB from colormap)
  FillOrder: msb-to-lsb
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 1
  Rows/Strip: 480
  Planar Configuration: single image plane
  Page Number: 0-1
  Color Map: (present)
  White Point: 0.3127-0.329
  PrimaryChromaticities: 0.640000,0.330000,0.300000,0.600000,0.150000,0.060000

```

When I use your file, I get

```
tiffinfo -D image0040.tif
OJPEGReadHeaderInfoSec: Unknown marker type 194 in JPEG data.
TIFF Directory at offset 0x8 (8)
  Subfile Type: (0 = 0x0)
  Image Width: 1644 Image Length: 733
  Resolution: 200, 200 pixels/inch
  Bits/Sample: 8
  Compression Scheme: Old-style JPEG
  Photometric Interpretation: YCbCr
  YCbCr Subsampling: 2, 2
  Orientation: row 0 top, col 0 lhs
  Samples/Pixel: 3
  Rows/Strip: 733
  Planar Configuration: single image plane
  Software: Pixel Translations Inc., PIXTIFF Version 58.6.1.1991
  JpegInterchangeFormat: 520
  JpegInterchangeFormatLength: 137929
  JpegQTables: 0
  JpegDcTables: 0
  JpegAcTables: 0
  JpegProc: 1
OJPEGSetupDecode: Warning, Depreciated and troublesome old-style JPEG compression mode, please convert to new-style JPEG compression and notify vendor of writing software.
OJPEGReadHeaderInfoSec: Unknown marker type 194 in JPEG data.
```

Which says as I expected,  "Compression Scheme: Old-style JPEG", which it cannot handle as it says, "Depreciated and troublesome old-style JPEG compression mode, please convert to new-style JPEG compression and notify vendor of writing software."

**Comment by KngStr** [comment]
OK. Thanks.
