### ISSUE TITLE
Website doesn't always redirect to HTTPS

### ISSUE THREAD

**Issue by jidanni** [ImageMagick/ImageMagick#2975]
![20201213T221344](https://user-images.githubusercontent.com/1230959/102014401-b5d2ad00-3d90-11eb-9f12-5806f91d6a1b.jpg)

The site correctly redirects to HTTPS here,
```
$ HEAD -Sd http://www.imagemagick.org/
HEAD http://www.imagemagick.org/
302 Found
HEAD https://imagemagick.org/index.php
200 OK
```
But not e.g., here,
```
$ HEAD -Sd http://www.imagemagick.org/Usage
HEAD http://www.imagemagick.org/Usage
301 Moved Permanently
HEAD http://www.imagemagick.org/Usage/
200 OK
```
Not sure if this is a good [security/policy](https://github.com/ImageMagick/ImageMagick/security/policy).

**Comment by urban-warrior** [comment]
It should redirect now.  Give it a try.

**Comment by jidanni** [comment]
```
$ HEAD -Sd http://www.imagemagick.org/Usage/
HEAD http://www.imagemagick.org/Usage/
200 OK

```

**Comment by urban-warrior** [comment]
It should redirect now. Give it a try.

**Comment by jidanni** [comment]
OK, but now there is a different problem! Note the double "//"....
```
$ HEAD -Sd http://www.imagemagick.org/Usage/
HEAD http://www.imagemagick.org/Usage/
301 Moved Permanently
HEAD https://legacy.imagemagick.org/Usage// <============HERE
200 OK
```

**Comment by urban-warrior** [comment]
We're don't see that as a problem.  It redirects to https and the correct location of the usage documents.

**Comment by jidanni** [comment]
Well then might as well toss in some more, /// ////.
"A new look on the Internet."

**Comment by urban-warrior** [comment]
Not more extraneous slashes.  It should work as expected now.
