### ISSUE TITLE
regression: distorted image when compressing TIFF as fax after update from 7.0.10-46 to 7.0.10-48

### ISSUE THREAD

**Issue by ginkel** [ImageMagick/ImageMagick#2977]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
As part of my document scanning pipeline I am applying some transformations to the scanned pages and converting the result to 1bit fax compressed TIFF before feeding it to tesseract. Since upgrading from IM 7.0.10-46 to 7.0.10-48 the fax conversion step results in a distorted (horizontally stretched / interlaced) image:

#### 7.0.10-46
![image](https://user-images.githubusercontent.com/174129/102022079-b2392900-3d84-11eb-86f7-964b739e24d7.png)

#### 7.0.10-48
![image](https://user-images.githubusercontent.com/174129/102022064-9766b480-3d84-11eb-9c15-52f7c1498d7b.png)

### Steps to Reproduce

Clone the sample data from: https://github.com/ginkel/imagemagick-distorted-image

Reproduce the issue with:

```
convert input.tif -alpha remove -alpha off -depth 1 -compress fax output.tif
```

`output-46.tif` has been produced with 7.0.10-46, `output-48.tif` with 7.0.10-48.

### System Configuration

- ImageMagick version: 7.0.10-48

```
$ convert --version
Version: ImageMagick 7.0.10-48 Q16 x86_64 2020-12-10 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zlib
```

- Environment (Operating system, version and so on): ArchLinux x86_64
- Additional information:

**Comment by fmw42** [comment]
`magick input.tif -alpha remove -alpha off -depth 1 -compress fax output.tif`

Fails for me with IM 7.0.10.49beta Mac OSX Sierra. The image gets split into two copies sided by side

**Comment by ginkel** [comment]
Just noticed that I accidentally swapped both output images in the reproducer Git repo. This has been corrected now. Sorry for the confusion. :-/

**Comment by ginkel** [comment]
I performed a `git bisect` with the following result:

```
9ccb4b82bae50ffb3c0d36b75e7ad477ec568be2 is the first bad commit
commit 9ccb4b82bae50ffb3c0d36b75e7ad477ec568be2
Author: Cristy <urban-warrior@imagemagick.org>
Date:   Thu Dec 10 00:24:40 2020 +0000

    https://github.com/ImageMagick/ImageMagick/issues/2959

 coders/tiff.c | 11 +++++++----
 1 file changed, 7 insertions(+), 4 deletions(-)
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by ginkel** [comment]
I can confirm that `master` as of 83c162886 fixes the problem. Thanks a lot!
