### ISSUE TITLE
Percentage -border in x dimension adds one pixel border in y dimension

### ISSUE THREAD

**Issue by tmont** [ImageMagick/ImageMagick#2978]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Specifying a percentage `-border` value (e.g. `10%`) in the `x` dimension adds a one pixel border in the `y` dimension when a `y`-value is not specified (or zero). Using non-percentages works fine and does not add a border.

In the opposite direction (e.g. `0x10%`) works fine and does not add a horizontal border.

Note that this is inside a Docker container for use as an AWS Lambda layer. Every other build I've tried has worked fine.

Still, this isn't the kind of issue I expected to run into, because it kind of just seems like a rounding error or something. I think perhaps this build is missing some core piece somehow?

### Steps to Reproduce
Input (black square):
```bash
magick -size 100x100 xc:black input.png
```

![input](https://user-images.githubusercontent.com/188562/102022705-72028800-3d3d-11eb-89d2-33df268d243b.png)

```bash
magick input.png -bordercolor teal -border 10%x0 output.png
```
![output](https://user-images.githubusercontent.com/188562/102022717-7b8bf000-3d3d-11eb-9a41-9cadb53533ee.png)

```bash
magick input.png -bordercolor teal -border 10%x0% output.png
```
![output](https://user-images.githubusercontent.com/188562/102022775-e0dfe100-3d3d-11eb-8b52-83fd45dff181.png)

### System Configuration
- ImageMagick version:
```
$ magick -version
Version: ImageMagick 7.0.10-48 Q16 x86_64 2020-12-13 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib jng jp2 jpeg png tiff webp zlib
```
- Environment (Operating system, version and so on):

Compiled inside this Docker container: https://github.com/serverlesspub/imagemagick-aws-lambda-2

It builds libopenjp2, libwebp, ligtiff, libjpeg, bzip2 and libpng from source.

Here are the package config flags:
```
PKG_CONFIG_PATH=$(CACHE_DIR)/lib/pkgconfig \
	./configure \
	CPPFLAGS=-I$(CACHE_DIR)/include \
	LDFLAGS=-L$(CACHE_DIR)/lib \
	--disable-dependency-tracking \
	--disable-shared \
	--enable-static \
	--prefix=$(TARGET_DIR) \
	--enable-delegate-build \
	--without-modules \
	--disable-docs \
	--without-magick-plus-plus \
	--without-perl \
	--without-x \
	--disable-openmp
```
- Additional information:

The default version from the apt repository (at least the one on my host machine) works fine, as does the latest binary from imagemagick.org. It seems to only be this build inside the docker container.

Any guidance would be appreciated.

**Comment by tmont** [comment]
I thought it only occurred with the a zero-ed out y dimension, but it's the same issue with the x dimension as well.

```bash
magick input.png -bordercolor teal -border 0x10% output.png
```

![output](https://user-images.githubusercontent.com/188562/102028722-65435b80-3d60-11eb-833d-84d72bc790b5.png)

**Comment by snibgo** [comment]
I confirm this bug with IM v6.9.9-50 and v7.0.8-64.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by tmont** [comment]
I downloaded and built ImageMagick 7.0.10-53 from source and this appears to be fixed.

Thanks!
