### ISSUE TITLE
convert tiff to jpg is now creating a stretched, cropped, and partial red only output

### ISSUE THREAD

**Issue by harriott** [ImageMagick/ImageMagick#2983]
I use `convert` on an almost daily basis for tiffs. Today it didn't work - the original images are ripped towards the right, cropped, and what's left is turned red.

GNU/Linux `5.9.14-arch1-1` with `imagemagick 7.0.10.48-1` (two different machines).
Windows 10 Home up-to-date with `ImageMagick-7.0.10-48-Q16-x64-static.exe` installed.

As my personal `tiff` files could, since today, not be correctly converted, I investigated further by grabbing a freely available sample image, [Sample .tiff download](https://file-examples.com/index.php/sample-images-download/sample-tiff-download/) , and on that I tried some conversions:

```bash
convert file_example_TIFF_1MB.tiff out.jpg
convert file_example_TIFF_1MB.tiff out.png
```

Both out-files are failures - I include one here:
![out](https://user-images.githubusercontent.com/6985117/102122970-9007df80-3e46-11eb-820b-4b2da40b3fb6.jpg)

Converting an equivalent sample `jpg` works fine.

Windows 10 Home up-to-date with `ImageMagick-7.0.8-3-Q16-x64-dll.exe` installed, as was the case for me an hour ago, did the conversions correctly, so this would seem to be a problem introduced somewhere in a very recent `ImageMagick` update.

Hoping this can be fixed. I love `ImageMagick`!

**Comment by fmw42** [comment]
With IM 7, use magick not convert.  Does that help?

**Comment by ginkel** [comment]
The interlacing pattern looks pretty similar to what I am seeing with #2977...

**Comment by fmw42** [comment]
It fails for me on IM 7.0.10.48, but works fine on IM 7.0.10.49beta Mac OSX Sierra with LIBTIFF, Version 4.1.0

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by ryantuck** [comment]
I just built `v70.10-50` locally on MacOS Catalina 10.15.7 and can confirm that the below now works as expected:

```
magick img.tif img.png
```

@urban-warrior Thank you for the quick turnaround. Is there a timeline for when that change will be available via `brew`?

**Comment by urban-warrior** [comment]
You'll need to contact the `brew` team to determine their schedule.  We maintain the ImageMagick distribution only.

**Comment by harriott** [comment]
@fmw42, I've got the update to `imagemagick 7.0.10.50-1` before I could check your suggestion.
Everyone else, it's fixed for me now. Thanks @urban-warrior.
