### ISSUE TITLE
alternative to setImageClipMask() in version 7.0

### ISSUE THREAD

**Issue by ragcsalo** [ImageMagick/ImageMagick#2988]
I have an important project that uses **setImageClipMask()** but in version 7.0 this command **does not exist**.
I have moved to a new hosting provider which only has ImageMagick 7.0, and now I'm stuck... it seems that there is **NO ALTERNATIVE** to this command, which is really annoying. Do you have any suggestion or solution for this problem?

**Comment by dlemstra** [comment]
Please don't create duplicate questions.

**Comment by ragcsalo** [comment]
sorry, I haven't found a similar issue yet, though I was searching carefully... so where is the original post then?

**Comment by dlemstra** [comment]
You created both an issue and a discussion and that is why I closed this issue.
