### ISSUE TITLE
`convert -sharpen` on a CMYK image causes weird visual artifacts to appear (black horizontal stripes or black color being mostly missing)

### ISSUE THREAD

**Issue by MatmaRex** [ImageMagick/ImageMagick#299]
Calling `convert -sharpen` on a CMYK image causes weird visual artifacts to appear (black horizontal stripes or black color being mostly missing).

Examples (generated with ImageMagick 6.9.0-0 Q16 x64 2014-11-14 on Windows, but I tested multiple versions with same results):
* `convert P.J._Proby_2007.jpg -sharpen 0x1 out.jpg` [Original](https://upload.wikimedia.org/wikipedia/commons/archive/3/3b/20120507074031%21P.J._Proby_2007.jpg) [Result](https://phab.wmfusercontent.org/file/data/v7f3ubea4ioqavwbx2l7/PHID-FILE-scn4vjzihegbs37rmrfp/out.jpg)
* `convert Google_Code-in_logo_2016.jpg -sharpen 0x1 out.jpg` [Original](https://upload.wikimedia.org/wikipedia/commons/archive/f/f1/20161010224659%21Google_Code-in_logo_2016.jpg) [Result](https://phab.wmfusercontent.org/file/data/r7c2ebal6dgbzvy3mrwl/PHID-FILE-th4bo3uczftsrvukyiip/out.jpg)

This is not specific to these images, converting the logo to CMYK and sharpening produces the same issue:

* `convert -colorspace CMYK logo: -sharpen 0x1 out.jpg` [Result](https://phab.wmfusercontent.org/file/data/zvqlw4h5ler3run4vini/PHID-FILE-qe3vyzfsfhu3wzuxvhqj/out.jpg)

This affects ImageMagick 6.8.4-0 and later, up to 6.9.6 (the latest release at the moment). It doesn't affect ImageMagick 7.x, or ImageMagick 6.8.3-10. It seems to be distinct from CMYK thumbnailing issues that plagued older versions (around 6.5) and have been fixed back then.

I have a more detailed investigation of this for Wikimedia, where this is currently causing some thumbnails to appear incorrectly: <https://phabricator.wikimedia.org/T141739>. We're currently considering downgrading ImageMagick or reverting changes since 6.8.3-10 and building a custom version.

(There is no alternative or workaround: `-convolve` is affected by the same bug, while `-unsharp` is apparently affected by some completely different bug that I didn't investigate.)

**Comment by fmw42** [comment]
A workaround until the IM developers can investigate is to convert your CMYK image to sRGB (preferably with profiles), then process, then if necessary convert back to CMYK, if you must have a CMYK result.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by mikayla-grace** [comment]
We released ImageMagick 6.9.6-5.  It converts your CMYK images properly without any visual artifacts.

**Comment by MatmaRex** [comment]
Thank you!
