### ISSUE TITLE
unable to convert dcm to jpg using php larvel

### ISSUE THREAD

**Issue by suvasisoft** [ImageMagick/ImageMagick#2994]
Getting below exception while converting from dicom to jpeg file.

	"message": "insufficient image data in file `/var/www/html/dev/api/temp/5fd9f5284b0f60177f524183/ser002img00002.dcm' @ error/dcm.c/ReadDCMImage/3092",
	"exception": "ImagickException",
	"file": "/var/www/html/dev/api/app/Http/Controllers/ImageController.php",
	"line": 36,

below is the code used to convert dicom file using php laravel:
  $d = new \dicom_convert;
                $d->file = $source_directory."/".$file_name;
                $d->dcm_to_jpg();
				$d->dcm_to_tn();
				$imagick = new \Imagick($source_directory."/".$file_abs_name.".dcm");               
                $imagick = new \Imagick($new_dic_img);
Imagick Version used in our server:
 convert --version
Version: ImageMagick 7.0.10-49 Q16 x86_64 2020-12-15 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.0)
Delegates (built-in): bzlib djvu fontconfig freetype gvc jbig jng jpeg lcms lqr lzma openexr png tiff x xml zlib

i am using Ubuntu 16.04 Version OS in aws

**Comment by urban-warrior** [comment]
Post a link to your ser002img00002.dcm image.  We need to download it and inspect to determine if your image is corrupt or if there is a bug in ImageMagick.
