### ISSUE TITLE
Can't get image rows() & columns()

### ISSUE THREAD

**Issue by Tarifut** [ImageMagick/ImageMagick#2995]
test.jpg is a 634x458 jpg

Image magicImage;
magicImage.read( "test.jpg" );
int height = magicImage.rows();
int width= magicImage.columns();

cout << width << "-" << height << endl;  

Displayed return is 458x8

**Comment by dlemstra** [comment]
Which library are you using?

**Comment by Tarifut** [comment]
I use magick++ last version (imagemagick 7.0.10-49)

**Comment by dlemstra** [comment]
Can you also share your test image?
