### ISSUE TITLE
svg to png conversion issue

### ISSUE THREAD

**Issue by f6fvy** [ImageMagick/ImageMagick#2996]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When converting the svg file extracted from http://prop.kc2g.com/  to png, several graphical items are not correctly drawn (circles / disks are incomplete) and/or misplaced (numbers should be in centered in the disks). See the comparison below.

SVG file rendered in the browser:

![muf_rendered](https://user-images.githubusercontent.com/12431844/102354451-de35f380-3faa-11eb-8437-2aa3bc849403.png)

Converted file in PNG:

![muf](https://user-images.githubusercontent.com/12431844/102354501-f279f080-3faa-11eb-8b61-6edb66544df5.png)

SVG Zipped file:
 
[muf.zip](https://github.com/ImageMagick/ImageMagick/files/5702995/muf.zip)

## Steps to Reproduce

- Save http://prop.kc2g.com/renders/current/mufd-normal-now.svg as muf.svg
- Use : convert muf.svg muf.png
- Compare the rendered svg in your browser to the converted file in png

### System Configuration

- ImageMagick version: ImageMagick-7.0.10-49-Q16-x86-static
- Environment (Operating system, version and so on): Win7
- Additional information:

**Comment by fmw42** [comment]
Which SVG renderer is ImageMagick using: MSVG/XML, RSVG or Inkscape. Add -verbose to your command to see which. But for best results, install Inkscape and ImageMagick should then use that automatically.

**Comment by f6fvy** [comment]
```
D:\MUF>"C:\Program Files\ImageMagick-7.0.10-Q16\magick.exe" -verbose muf.svg muf.png

muf.svg SVG 1526x904 1526x904+0+0 16-bit sRGB 270257B 1.516u 0:01.506
muf.svg=>muf.png SVG 1526x904 1526x904+0+0 16-bit sRGB 270257B 0.734u 0:00.391
```

Inskcape is installed, but it seems that ImageMagick doesn't use it as I get a different result with Inkscape (like yours). Is there a way to force its use ?

**Comment by fmw42** [comment]
Sorry, I am not a Windows expert. Are both Inkscape and ImageMagick in your PATH environment variable, if Windows has such?  P.S. When using ImageMagick, use magick.exe, not magick.exe convert. In other words, do not add convert to the command.

**Comment by f6fvy** [comment]
Inkscape is in the path (I can start it from the command prompt). ImageMagick isn't, but I guess it's irrelevant in this case. For some reason the Inkscape renderer isn't used. Thanks for your help anyway.

**Comment by urban-warrior** [comment]
ImageMagick selects one SVG renderer from {MSVG|InkScape|RSVG} when configured.  The Windows binary builds we provide includes the RSVG renderer and apparently RSVG cannot render your SVG image.  The work-around is to install inkscape on your Windows host and access it as a delegate.  Add

```
<delegate decode="ink" command="cmd.exe /c (&quot;inkscape&quot; &quot;%i&quot; --export-filename=&quot;%o.png&quot;) &amp; (move &quot;%o.png&quot; &quot;%o&quot; >nul)"/>
```

to delegates.xml and convert like this:

```
convert ink:muf.svg muf.png
```

Note the delegate above is untested.  You may need to mod to get it to work.

**Comment by ValZapod** [comment]
The source file is sRGB, yet the new PNG file is not sRGB, since there is no sRGB chunk there.
