### ISSUE TITLE
V6 label-option default-font regression 

### ISSUE THREAD

**Issue by LinuCC** [ImageMagick/ImageMagick#300]
Hi there!

With ImageMagick < `6.9.6` following command generates a Picture on Arch Linux:
```
convert label:BXVASDASD jpeg:myimg
```
(While also stderr-ing out warnings: `convert: unable to read font '(null)' @ error/annotate.c/RenderFreetype/1310`)

With ImageMagick >= `6.9.6` the same command fails with 
```
convert: unable to read font `(null)' @ error/annotate.c/RenderFreetype/1312.
convert: no images defined `jpeg:myimg' @ error/convert.c/ConvertImageCommand/3257.
```
Although specifying a font with `-font MyFont` will make it work again.

I couldnt find anything mentioning it in the Patch Notes, so I figured that this is not intended or a deprecation that was finally removed?

Edit: The command & the version `6.9.6` do not cause problems on Mac OS X.
Is it possible that the default font was changed / a fallback removed?

**Comment by mikayla-grace** [comment]
Type `convert -list configure`.  If freetype included in the DELEGATES tag?  Its required to render fonts.

**Comment by LinuCC** [comment]
Yes, `freetype` is included there:

```bzlib mpeg fontconfig freetype gslib jng jpeg lcms lqr lzma openexr openjp2 pango png ps rsvg tiff webp wmf x xml zlib```

Just to be sure, i have replaced the custom lib `freetype2-infinality` with `freetype2`, but  without avail.

What makes me scratch my head is that the image-generation worked in previous versions, and some kind of font must have been picked as a fallback since it was visible in the image.

This problem also exists on an older Arch Linux machine, on which I have only upgraded the ImageMagick-package, so the problem seems to originate from there.

**Comment by LinuCC** [comment]
I have tried upgrading to ImageMagick `7.0.3` through the AUR-package `imagemagick-full`.
It looks like the command works fine with V7, with no Warnings at all.
 
I have also downgraded it once again to check if a peer-dependency was missing, but it failed again.

Gonna stay on V7 for now :)
