### ISSUE TITLE
Wrong conversion of dicom-files

### ISSUE THREAD

**Issue by lfekson** [ImageMagick/ImageMagick#302]
DICOM-files (grayscale, 16 bits) are identified as 8-bits:
identify test.dcm
test.dcm DCM 512x512 512x512+0+0 8-bit sRGB 526KB 0.000u 0:00.000

and convert gives wrong picture for such files:
convert test.dcm test.jpeg
additional parameters don't help:
convert -depth 16 -type grayscale test.dcm test.jpeg

convert -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2016-06-01
OS: Ubuntu 16.04, imagemagick 8:6.8.9.9-7ubuntu5.1

[02859725.zip](https://github.com/ImageMagick/ImageMagick/files/600195/02859725.zip)

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by lfekson** [comment]
Thank you very much!

**Comment by lfekson** [comment]
Hello! Would you please tell which file from beta is appropriate for Ubuntu 16 64 bit? I've tried ImageMagick-6.9.6-6~beta20161120.zip, it can be installed, and gives a correct result for dicom-file, but a program compiled with this version gives "segmentation fault" on definition "Image fileIn;".

**Comment by lfekson** [comment]
Never mind, the newer version 7 is working correctly on Ubuntu 16.04. Thanks a lot for your quick fix of dicom-s!
