### ISSUE TITLE
Broken Downloads Page

### ISSUE THREAD

**Issue by Daggy1234** [ImageMagick/ImageMagick#3026]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Broken Install link. `https://imagemagick.org/download/releases/ImageMagick-7.0.10-41.tar.gz` is broken as it leads to a new website. All download pages lead to `urban-warriors.org` and hence make using the original downloads break.

### System Configuration
All Enviroments

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by urban-warrior** [comment]
We are off-loading some of the network bandwidth demand to a remote server.  We use a redirect because the download location will likely change in the near future.  The links work fine from a browser or from a robust network downloader that properly handles a redirect.  The `wget` program, for example, downloads the link you provided without complaint:

```
$ wget https://imagemagick.org/download/releases/ImageMagick-7.0.10-41.tar.gz
... ImageMagick-7.0.10-41.tar.gz’ saved
```

**Comment by Daggy1234** [comment]
Interesting because I used curl and it broke . Used github releases as a last ditch method

**Comment by urban-warrior** [comment]
Understood but necessary. ImageMagick is quite popular and the monthly download is many terabytes.  Network bandwidth is not free so we needed to turn to a cost sharing model.  The ImageMagick web pages are hosted @ https://imagemagick.org and the source and binaries are hosted at a temporary remote host until we can find a more permanent home.

**Comment by saydo17** [comment]
The server on the other end of the redirect is now returning 404.

**Comment by saydo17** [comment]
Seems to be back up this morning

**Comment by fantapop** [comment]
Download page is not responding for me

**Comment by fmw42** [comment]
Binaries can be download from https://imagemagick.org/script/download.php.  The source code download page seems to be offline or they are upgrading the directory with new software. Please give it some time. Or try https://imagemagick.org/script/install-source.php

**Comment by fantapop** [comment]
Download page is back!
