### ISSUE TITLE
ImageMagick-7, wrong normalize in convert

### ISSUE THREAD

**Issue by lfekson** [ImageMagick/ImageMagick#303]
In ImageMagick-7 a command "convert -normalize test.tiff test.jpeg" can give wrong colors. The last tested version 6.8.6 Q16 worked correctly.

convert --version
Version: ImageMagick 7.0.3-7 Q16 x86_64
Ubuntu 16.04.1 LTS
[AortaWL.zip](https://github.com/ImageMagick/ImageMagick/files/604592/AortaWL.zip)

**Comment by dlemstra** [comment]
Have you tried `convert test.tiff -normalize test.jpeg`?

**Comment by lfekson** [comment]
Yes, sorry, forgot to add the command.

**Comment by lfekson** [comment]
Have tried, moving "-normalize" from "convert -normalize" to "convert src -normalize" doesn't make difference.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
