### ISSUE TITLE
Add example of combined -draw options

### ISSUE THREAD

**Issue by jidanni** [ImageMagick/ImageMagick#3037]
https://imagemagick.org/script/command-line-options.php#draw says
> The rotate primitive rotates subsequent shape primitives and text primitives about the origin of the main image.

OK, but without an example the user will think this means:
```
-draw "rotate 25" -draw "text 4499,3206 I"
```

**Comment by urban-warrior** [comment]
We added an example to the -draw description to help clarify the rotate element.
