### ISSUE TITLE
Documentation fix

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#304]
Hi could you run (before release):

find . -path '.git' -prune -o -type f -name '*.html' -exec sed -i 's,<col \([^>]*\)\([^/]\)>,<col \1\2 />,g' {} \;

**Comment by bastien-roucaries** [comment]
And

 find . -path '.git' -prune -o -type f -name '*.html' -exec sed -i 's,<link \([^>]*\)\([^/]\)>,<link \1\2 />,g' {} \;

**Comment by bastien-roucaries** [comment]
Fix meta tag
    
    find . -path '.git' -prune -o -type f -name '*.html' -exec sed -i 's,<meta \([^>]*\)\([^/]\)>,<meta \1\2 />,g' {} \;
    
    Forwarded: Yes, https://github.com/ImageMagick/ImageMagick/issues/304

**Comment by bastien-roucaries** [comment]
Fix img tag
    
    find . -path '.git' -prune -o -type f -name '*.html' -exec sed -i 's,<img \([^>]*\)\([^=/]\)>,<img \1\2 />,g' {} \;
    
    Forwarded: Yes, https://github.com/ImageMagick/ImageMagick/issues/304

**Comment by bastien-roucaries** [comment]
BTW could you also apply
diff --git a/www/api/morphology.html b/www/api/morphology.html
index d56fda6..e36f67b 100644
--- a/www/api/morphology.html
+++ b/www/api/morphology.html
@@ -97,10 +97,6 @@ KernelInfo *AcquireKernelInfo(const char *kernel_string)
 
 <p>A description of each parameter follows:</p>
 
-<dd>
-</dd>
-
-<dd> </dd>
 <dl class="dl-horizontal">
 <dt>kernel_string</dt>
 <dd>the Morphology/Convolution kernel wanted. </dd>
@@ -122,10 +118,7 @@ KernelInfo *AcquireKernelBuiltIn(const KernelInfoType type,
 
 <p>A description of each parameter follows:</p>
 
-<dd>
-</dd>
 
-<dd> </dd>
 <dl class="dl-horizontal">
 <dt>type</dt>
 <dd>the pre-defined type of kernel wanted </dd>
@@ -292,10 +285,7 @@ KernelInfo *CloneKernelInfo(const KernelInfo *kernel)
 
 <p>A description of each parameter follows:</p>
 
-<dd>
-</dd>
 
-<dd> </dd>
 <dl class="dl-horizontal">
 <dt>kernel</dt>
 <dd>the Morphology/Convolution kernel to be cloned </dd>
@@ -314,10 +304,6 @@ KernelInfo *DestroyKernelInfo(KernelInfo *kernel)
 
 <p>A description of each parameter follows:</p>
 
-<dd>
-</dd>
-
-<dd> </dd>
 <dl class="dl-horizontal">
 <dt>kernel</dt>
 <dd>the Morphology/Convolution kernel to be destroyed </dd>
@@ -345,10 +331,7 @@ Image *MorphologyApply(const Image *image,MorphologyMethod method,
 
 <p>A description of each parameter follows:</p>
 
-<dd>
-</dd>
 
-<dd> </dd>
 <dl class="dl-horizontal">
 <dt>image</dt>
 <dd>the source image </dd>
@@ -409,10 +392,7 @@ Image *MorphologyImage(const Image *image,MorphologyMethod method,
 
 <p>A description of each parameter follows:</p>
 
-<dd>
-</dd>
 
-<dd> </dd>
 <dl class="dl-horizontal">
 <dt>image</dt>
 <dd>the image. </dd>
@@ -450,10 +430,7 @@ void ScaleGeometryKernelInfo(KernelInfo *kernel,
 
 <p>A description of each parameter follows:</p>
 
-<dd>
-</dd>
 
-<dd> </dd>
 <dl class="dl-horizontal">
 <dt>kernel</dt>
 <dd>the Morphology/Convolution kernel to modify </dd>
@@ -464,7 +441,6 @@ void ScaleGeometryKernelInfo(KernelInfo *kernel,
        "-set option:convolve:scale {geometry}" setting.
 </pre>
 
-<p></dd>
 </dl>
 <h2><a href="http://www.imagemagick.org/api/MagickCore/morphology_8c.html" id="ScaleKernelInfo">ScaleKernelInfo</a></h2>
 
@@ -497,10 +473,6 @@ void ScaleKernelInfo(KernelInfo *kernel, const double scaling_factor,
 
 <p>A description of each parameter follows:</p>
 
-<dd>
-</dd>
-
-<dd> </dd>
 <dl class="dl-horizontal">
 <dt>kernel</dt>
 <dd>the Morphology/Convolution kernel </dd>
@@ -511,14 +483,12 @@ void ScaleKernelInfo(KernelInfo *kernel, const double scaling_factor,
        zero.  If the kernel is normalized regardless of any flags.
 </pre>
 
-<p>o normalize_flags: </dd>
+<dd>o normalize_flags: </dd>
 
 <pre class="text">
        specifically: NormalizeValue, CorrelateNormalizeValue,
                      and/or PercentValue
 </pre>
-
-<p></dd>
 </dl>
 <h2><a href="http://www.imagemagick.org/api/MagickCore/morphology_8c.html" id="ShowKernelInfo">ShowKernelInfo</a></h2>
 
@@ -532,10 +502,7 @@ void ShowKernelInfo(const KernelInfo *kernel)
 
 <p>A description of each parameter follows:</p>
 
-<dd>
-</dd>
 
-<dd> </dd>
 <dl class="dl-horizontal">
 <dt>kernel</dt>
 <dd>the Morphology/Convolution kernel </dd>
@@ -556,10 +523,7 @@ void UnityAdditionKernelInfo(KernelInfo *kernel, const double scale )
 
 <p>A description of each parameter follows:</p>
 
-<dd>
-</dd>
 
-<dd> </dd>
 <dl class="dl-horizontal">
 <dt>kernel</dt>
 <dd>the Morphology/Convolution kernel </dd>
@@ -570,7 +534,6 @@ void UnityAdditionKernelInfo(KernelInfo *kernel, const double scale )
        the given kernel.
 </pre>
 
-<p></dd>
 </dl>
 <h2><a href="http://www.imagemagick.org/api/MagickCore/morphology_8c.html" id="ZeroKernelNans">ZeroKernelNans</a></h2>
 
@@ -584,10 +547,6 @@ void ZeroKernelNans (KernelInfo *kernel)
 
 <p>A description of each parameter follows:</p>
 
-<dd>
-</dd>
-
-<dd> </dd>
 <dl class="dl-horizontal">
 <dt>kernel</dt>
 <dd>the Morphology/Convolution kernel </dd>

**Comment by bastien-roucaries** [comment]
Remove spurious cache line
  
This does not allow to apply patch cleanly
 
find . -path './.git' -prune -o -type 'f' -name '*.html' -exec sed -i 's,^<!-- Magick Cache.*$,,g' {} \;

Forwarded: Yes, https://github.com/ImageMagick/ImageMagick/issues/304

**Comment by bastien-roucaries** [comment]
more patches could be found http://sources.debian.net/src/imagemagick/8:6.9.6.2%2Bdfsg-3/debian/patches/

**Comment by mikayla-grace** [comment]
Thanks for the patches-- they are applied.
