### ISSUE TITLE
Autoconf modernize

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#305]
Hi,

A remainder to apply when you are ready this patch that simplify downstream but need to rewrite your release script.

Not an immediate priority we could use it downstream
http://sources.debian.net/src/imagemagick/8:6.9.6.2%2Bdfsg-3/debian/patches/0017-Use-modern-idiom-for-autoconf.patch/

**Comment by bastien-roucaries** [comment]
In this case you could also apply http://sources.debian.net/src/imagemagick/8:6.9.6.2%2Bdfsg-3/debian/patches/0019-Robustify-doxygen-dir-install.patch/

**Comment by bastien-roucaries** [comment]
And this also http://sources.debian.net/src/imagemagick/8:6.9.6.2%2Bdfsg-3/debian/patches/0025-Allow-distribution-to-custumize-the-html-pointer-to-.patch/

**Comment by mikayla-grace** [comment]
Thanks for the patches-- they are applied.

**Comment by mikayla-grace** [comment]
We had to revert the configure.ac patch because ImageMagick.spec.in must also be patched for the RPM to build.
