### ISSUE TITLE
Text Handling: If the input is combination between Latin and Arabic symbols then the image cannot be created

### ISSUE THREAD

**Issue by Filbor80** [ImageMagick/ImageMagick#3056]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When the following is executed in the Command prompt (where in Temp.txt: Latin and Arabic symbols are combined):
magick convert -font Arial -pointsize 64 pango:@"C:\temp\Temp.txt" "C:\temp\Temp.jpg"
The Temp.jpg cannot be created.

### Steps to Reproduce

1) Create manually C:\temp\Temp.txt in UTF8 wihout BOM with Latin and Arabic symbols with suitable font. In this case Arial.
![Capture_Text txt](https://user-images.githubusercontent.com/76432505/102773147-6a705e00-4391-11eb-94ac-f253422a8482.PNG)
2) Open CMD and execute:
magick convert -font Arial -pointsize 64 pango:@"C:\temp\Temp.txt" "C:\temp\Temp.jpg"
3) Temp.jpg cannot be created.
4) The Expected result is:
![Temp](https://user-images.githubusercontent.com/76432505/102773295-ae636300-4391-11eb-8812-c04b8f9924c1.jpg)

### System Configuration

- ImageMagick version: **ImageMagick-7.0.10-52-Q16-HDRI-x64-dll**
- Environment (Operating system, version and so on): **Windows 10 (64-bit)**
- Additional information: The version **ImageMagick-7.0.10-19-Q16-HDRI-x64-dll** is OK and works correctly.

**Comment by Filbor80** [comment]
In fact, my workaround is usage of version:
ImageMagick-7.0.10-52-Q16-HDRI-x64-dll

I am attaching a video:

https://user-images.githubusercontent.com/76432505/103403528-259ab300-4b59-11eb-9d06-23ddfa50b030.mp4

... and when the path is not correct, off course the image, but with default "wrong" content.

**Comment by dlemstra** [comment]
This appears to be an issue in the Windows build of ImageMagick. Just pushed a patch to fix this. This will be resolved in the next release of ImageMagick
