### ISSUE TITLE
TGA Converted Images are Disoriented

### ISSUE THREAD

**Issue by blue-j** [ImageMagick/ImageMagick#3061]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am aware that this has been reported before, but it doesn't appear to be solved in the latest version (7.0.10-53_1).  When I convert any TGA images to JPEG, they are flipped upside down, and horizontally.

### Steps to Reproduce
`convert sample_1920×1280.tga sample_1920×1280.jpg`

[https://filesamples.com/samples/image/tga/sample_1920%C3%971280.tga](url)

### System Configuration
I have tried it on Ubuntu 14.04 with ImageMagick 7.0.10-45 Q16 x86_64
and macOS 10.15.7 with ImageMagick 7.0.10-53 Q16 x86_64

**Comment by fmw42** [comment]
This works for me on IM 7.0.10.53 Q16 Mac OSX Sierra

magick sample_1920×1280.tga -auto-orient sample_1920×1280.jpg


![sample_1920×1280](https://user-images.githubusercontent.com/13458218/103449960-66332300-4c64-11eb-84fa-73cbb89786cb.jpg)

**Comment by blue-j** [comment]
Indeed!  I was using auto-orient only with v 7.0.10-45, where it doesn't seem to work, but with 7.0.10-53 it does.  Thanks, Fred!
