### ISSUE TITLE
Missing "Single Colour Compression" mode in DXT compressor?

### ISSUE THREAD

**Issue by sp-1234** [ImageMagick/ImageMagick#309]
http://sjbrown.co.uk/2006/01/19/dxt-compression-techniques/
As can be seen in the article, squish library has one additional compression mode ("Single Colour Compression"), but I don't see any usages of it here https://github.com/ImageMagick/ImageMagick/blob/master/coders/dds.c although it's said to be a port of the squish library.

**Comment by dlemstra** [comment]
Do you have an example of reading or writing that fails.

**Comment by dlemstra** [comment]
@sp-1234 Can you respond to my question so I can investigate this?

**Comment by sp-1234** [comment]
There is no such example. It's just an optional alternative compression algorithm which is useful for grayscale inputs.

**Comment by dlemstra** [comment]
We do have single color compression: https://github.com/ImageMagick/ImageMagick/blob/master/coders/dds.c#L3041 and this will be done automatically: https://github.com/ImageMagick/ImageMagick/blob/master/coders/dds.c#L2916. I thought you had an example where this did not work.

**Comment by sp-1234** [comment]
Ah ok. I made a mistake, sorry!
