### ISSUE TITLE
Possible bug -draw "matte_alpha 0,0 flood fill"

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#3091]
I am having trouble using -draw "matte_alpha" n IM7 

`magick -size 250x250 xc:black xc:blue -append -fuzz 10% -fill none -draw "matte_alpha 0,0 floodfill" y1.png`

**magick: non-conforming drawing primitive definition `matte_alpha' @ error/draw.c**

but this works fine using -draw "color 0,0 floodfill"

`magick -size 250x250 xc:black xc:blue -append -fuzz 10% -fill red -draw "color 0,0 floodfill" y2.png`

![y2](https://user-images.githubusercontent.com/13458218/103970487-3630c780-511d-11eb-8a99-e57468b8a5fe.png)

but this works in IM 6

`convert -size 250x250 xc:black xc:blue -append -fuzz 10% -fill none -draw "matte 0,0 floodfill" y3.png`

So there seems to be something wrong with matte_alpha in IM 7

**Comment by snibgo** [comment]
https://imagemagick.org/script/command-line-options.php#draw doesn't list "matte_alpha" as an option within "-draw". It does list "matte", and this works in v6 but not v7. That documentation is wrong for v7.

The porting guide https://imagemagick.org/script/porting.php correctly says:
```
-draw
    The matte primitive is now alpha (e.g. -draw 'alpha 0,0 floodfill').
```

**Comment by fmw42** [comment]
Thanks snibgo. I am a little tired this evening and forgot the proper change for matte.
