### ISSUE TITLE
AppImage is not useable in aws lambda (some lib missing)

### ISSUE THREAD

**Issue by bpoussin** [ImageMagick/ImageMagick#3092]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I try to use AppImage version in aws lambda JS, but some lib is missing to use `convert`

I see #1592 issue, and the explication with exclude file https://github.com/AppImage/pkg2appimage/blob/master/excludelist.

But i think, if AppImage can be use as is in aws lambda, many people will be very happy ;)

Adding missing lib, add only 1Mo to AppImage for big portability

### Steps to Reproduce

Create lambda layer with extracted version of AppImage file, and call `convert` in JS lambda.
convert fail with missing lib

To reproduce localy you can use docker:
```
wget https://imagemagick.org/download/binaries/magick
chmod +x magick
./magick --appimage-extract
docker run -ti --rm --entrypoint bash -v $PWD/squashfs-root/usr:/opt lambci/lambda:nodejs12.x -c "ldd /opt/bin/convert" |grep "=> not found"
```
output
```
	libfontconfig.so.1 => not found
	libfreetype.so.6 => not found
	libX11.so.6 => not found
	libX11.so.6 => not found
	libfreetype.so.6 => not found
	libX11.so.6 => not found
	libexpat.so.1 => not found
	libfreetype.so.6 => not found
```
and if i copy missing lib, and run again
```
docker run -ti --rm --entrypoint bash -v $PWD/squashfs-root/usr/lib:/opt/lib ubuntu:trusty -c 'apt-get update -q && apt-get install -y libfontconfig1-dev libX11-dev libxcb1-dev && cp -v /lib/x86_64-linux-gnu/libexpat.so.1* /opt/lib/  && for lib in libfontconfig.so.1 libfreetype.so.6 libX11.so.6 libX11.so.6 libfreetype.so.6 libX11.so.6 libfreetype.so.6 libxcb.so.1; do cp -v /usr/lib/x86_64-linux-gnu/${lib}* /opt/lib/; done'

docker run -ti --rm --entrypoint bash -v $PWD/squashfs-root/usr:/opt lambci/lambda:nodejs12.x -c "ldd /opt/bin/convert" |grep "=> not found"
```
no output, and convert work

### System Configuration

- ImageMagick version: 7.0.10-56-x86_64
- Environment (Operating system, version and so on): AppImage version in aws Lambda
- Additional information:

**Comment by urban-warrior** [comment]
Why not just type `./magick'.  You do not need to extract the files.  If you must extract the files from the AppImage, review the AppRun script.  It properly sets the dependencies ImageMagick requires to execute.

**Comment by bpoussin** [comment]
Because aws lambda don't have and can't have fusefs, we must used  extracted version of  AppImage

**Comment by relikd** [comment]
Not sure if I can hijack this issue but I have similar problems. I just downloaded the `darwin20.1.0.tar.gz` (v7.1.0) macOS image and can't execute any binary. I know that it used to work in v7.0.10.

```
dyld: Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /userdir/convert
  Reason: image not found
zsh: abort      convert
```

Could it be that an X11 dependency was added in a recent release? My `opt` folder is (and was) empty, so there is no chance it could be referenced. Are there somewhere older binary releases I could download to pinpoint the exact version it changed?

**Comment by dlemstra** [comment]
Where did you download that macOS AppImage @relikd?

**Comment by relikd** [comment]
@dlemstra https://imagemagick.org/script/download.php#macosx (not sure if that really is an AppImage, but these binary files show the error message above)

**Comment by dlemstra** [comment]
Please ask your question here instead @relikd: https://github.com/ImageMagick/ImageMagick/discussions.
