### ISSUE TITLE
Conversion of 4 channel PSB (R,G,B,IR) to BigTIFF 

### ISSUE THREAD

**Issue by Aladar2021** [ImageMagick/ImageMagick#3093]
### Prerequisites

- [yes] I have written a descriptive issue title
- [yes] I have verified that I am using the latest version of ImageMagick
- [yes] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When converting Photoshop Large Document format (PSB) with 4 channels (Red, Green, Blue and InfraRed)  to BigTIFF, output image contains strange histogram values for each channel and the image does not look like original one.

(Note: If input PSB is 3 channel RGB then output BigTIFF is ok.)

### Steps to Reproduce

cmd
convert Input_RGBIR.psb TIFF64:Output_RGBIR.tif

### System Configuration

- ImageMagick version:  ImageMagick-7.0.10-56-portable-Q16-x64
- Environment (Operating system, version and so on): Windows 10 Enterprise, 64bit
- Additional information:

**Comment by fmw42** [comment]
What are the dimensions and file size of your input? If not huge please post your input and output images.

**Comment by urban-warrior** [comment]
Post a link to one or two PSB image samples. We need to download and inspect them before we can help further.

**Comment by Aladar2021** [comment]
> Post a link to one or two PSB image samples. We need to download and inspect them before we can help further.

Input PSB:
http://s000.tinyupload.com/index.php?file_id=56807581717214445922

Output BigTIFF:
http://s000.tinyupload.com/index.php?file_id=60612674125225755876

Thank you very much.

**Comment by fmw42** [comment]
One possible issue - Photoshop files won't keep the alpha channel open when opened and then closed. So ImageMagick will never be able to access the alpha channel when opening the file to save it. Also I can open the file in IM 7.0.10.57 as truecolor (3-channel). I have IM7 7.0.10.57 which is using libtiff 4.1.0

**Comment by urban-warrior** [comment]
ImageMagick is treating the IR channel as alpha.  Discard it as follows:

```
convert Input_RGBIR.psb -alpha off TIFF64:Output_RGBIR.tif
```

**Comment by fmw42** [comment]
I thought he wanted to keep the 4th channel as alpha in his output TIFF. But I do not believe he can keep the alpha channel from Photoshop when saving the file even when it is enabled before saving

**Comment by Aladar2021** [comment]
Yes, I want to keep IR channel...

**Comment by Aladar2021** [comment]
I have tested ImageMagick 7.0.10-62 Q16 x64, the output image is still not ok.

**Comment by dlemstra** [comment]
Closing this because there is a duplicate discussion: https://github.com/ImageMagick/ImageMagick/discussions/3095
