### ISSUE TITLE
Access violation at MagickCore/string.c:1647

### ISSUE THREAD

**Issue by moshekaplan** [ImageMagick/ImageMagick#31]
https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1496645

**Comment by dlemstra** [comment]
Thanks for reporting this, it will be fixed in ImageMagick 6.9.2-2.

**Comment by moshekaplan** [comment]
No problem. ImageMagick seemed like a good target to fuzz; its been fun so far;
