### ISSUE TITLE
IM-7.0.3-8 tests don't like Apple's Helvetica

### ISSUE THREAD

**Issue by nieder** [ImageMagick/ImageMagick#310]
Running `make check` fails magick++/demo/demos.tap 3 with the following error:

````
PASS: Magick++/demo/demos.tap 2
Read images ...
Creating thumbnails...
  add noise ...
  add noise (blue) ...
  annotate ...
Caught exception: demo: unable to read font `/System/Library/Fonts/Helvetica.dfont' @ error/annotate.c/RenderFreetype/1392
not ok
FAIL: Magick++/demo/demos.tap 3
Writing image "flip_out.miff" ...
ok
PASS: Magick++/demo/demos.tap 4
````
````
$ ls -l /System/Library/Fonts/Helvetica.dfont
-rw-r--r--  1 root  wheel  2562874 Aug 28  2015 /System/Library/Fonts/Helvetica.dfont
````
If I add my local install of ghostscript-fonts to my FC search path, then the tests all pass. This is similar to [issue 136](https://github.com/ImageMagick/ImageMagick/issues/136) and I have a local working fix, but it would be preferable if IM was able to work out of the box with a system provided font.

**Comment by nieder** [comment]
M-6.9.6-6 also has this problem, but seems OK at 6.9.5-10.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
