### ISSUE TITLE
ImageMagick isn't compatible with TTC font

### ISSUE THREAD

**Issue by yunhao** [ImageMagick/ImageMagick#3110]
I'm currently working on macOS system and trying to draw some text on images. However, it seems that IM doesn't works well with TTC fonts, which is commonly used in macOS (`/System/Fonts/*.ttc`).

First, I try to use this script `https://legacy.imagemagick.org/Usage/scripts/imagick_type_gen` to generate a `type.xml` in `~/.magick/`.
But some errors occur:
```bash
...
imagick_type_gen: "/System/Library/Fonts/HelveticaNeue.ttc" skipped, unknown suffix
imagick_type_gen: "/System/Library/Fonts/ãã©ã­ããè§ã³ãã·ãã¯ W8.ttc" skipped, unknown suffix
imagick_type_gen: "/System/Library/Fonts/PingFang.ttc" skipped, unknown suffix
imagick_type_gen: "/System/Library/Fonts/Noteworthy.ttc" skipped, unknown suffix
imagick_type_gen: "/System/Library/Fonts/NotoSansOriya.ttc" skipped, unknown suffix
imagick_type_gen: "/System/Library/Fonts/ãã©ã­ããè§ã³ãã·ãã¯ W9.ttc" skipped, unknown suffix
imagick_type_gen: "/System/Library/Fonts/Optima.ttc" skipped, unknown suffix
imagick_type_gen: "/System/Library/Fonts/Monaco.dfont" skipped, unknown suffix
...
```
It look like this script can't handle TTC files.

Then I try to explicit specify the font file path:
```bash
convert -font '/System/Library/Fonts/PingFang.ttc' -pointsize 24 -weight 700 caption:'Hello Worls!' test.png
```
This command works and generate an image with text, but the `weight` parameter is ignored. No matter how I change the weight, the result is the same.

**Comment by urban-warrior** [comment]
The  imagick_type_gen script supports TTF and OTF fonts, not TTC fonts. You can of course add the fonts manually to the type.xml configuration file.   Font weights are considered when searching for a font or for font substitution.  If you specify a font, ImageMagick simply utilized that font @ the specified pointsize.

**Comment by KrasnayaPloshchad** [comment]
TTC is commonly used for CJK fonts.
