### ISSUE TITLE
SVG is identified as MVG

### ISSUE THREAD

**Issue by NikolayRys** [ImageMagick/ImageMagick#3117]
### Description
In the most recent version(7.0.10-57) of ImageMagick, the "identify" feature changed its behavior when analyzing SVG files. Now they all are recognized as MVG, which is presumably not intended and it should be SVG.
Please see the steps below.
At least for version 7.0.10-45 these steps above correctly produce the output `SVG`.

### Steps to Reproduce
1. Create a simple SVG file, named test.svg
```html
<svg version="1.1" baseProfile="full" width="300" height="200" xmlns="http://www.w3.org/2000/svg">
  <rect width="100%" height="100%" fill="red" />
  <circle cx="150" cy="100" r="80" fill="green" />
  <text x="150" y="125" font-size="60" text-anchor="middle" fill="white">SVG</text>
</svg>
```
2. Run `magick identify -format "%m" test.svg`
3. Observe that the output is "MVG", but it should be "SVG" instead.

## Additional info
Nevertheless, it is seen by both versions as SVG if "format" option is not given:
```
➜  magick identify test.svg
test.svg SVG 300x200 300x200+0+0 16-bit sRGB 305B 0.000u 0:00.014
```

*Environment:* MacOS 11.01 Big Sur, x86_64

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by NikolayRys** [comment]
Thanks for the quick response.

**Comment by kleisauke** [comment]
Not sure if this is the desired behavior, but for binary strings this also returns MSVG. Reproducer:

```c
#include <magick/api.h>
#include <stdio.h>

int main() {
  char format[MagickPathExtent];

  if (GetImageMagick("<svg", 4, format))
    printf("%s\n", format);

  return 0;
}
```

```bash
$ gcc test.c `pkg-config MagickCore --cflags --libs`
$ ./a.out
MSVG
```

Tested with ImageMagick 6.9.12-2.

**Comment by urban-warrior** [comment]
The behavior is fine.  ImageMagick permits zero or more aliases associated with a particular image format.  We could mark any aliases so that the authoritative name is returned instead but so far we have not seen a need to do so since ReadImage() provides for that requirement.
