### ISSUE TITLE
Failure count not reset after a test in the validation suite fails

### ISSUE THREAD

**Issue by zarniwhoop73** [ImageMagick/ImageMagick#3120]
### Description
After a test run by tests/validate fails, each subsequent suite shows that one test failed, and therefore the number of tests which passed is reduced for that suite.

### Steps to Reproduce
Build, run make check, then run 'tests/validate 2>&1 | tee validate.log'

In this case, the final report showed that 1 test failed.

The failure was actually in 'validate convert command line program:'

test 79: -map netscape:... fail @ tests/validate.c/ValidateConvertCommand/1370.

but from that point until the end of the run every other set of tests reported 1 failure, e.g. the report ended:

validate montage command line program:
  test 0: ... pass.
  test 1: -frame 5... pass.
  test 2: -geometry 13x19+10+5 -gravity Center... pass.
  test 3: -label %f... pass.
  test 4: -pointsize 10... pass.
  test 5: -shadow... pass.
  test 6: -tile 3x3... pass.
  summary: 7 subtests; 6 passed; 1 failed.
validate stream command line program:
  test 0: ... pass.
  summary: 1 subtests; 0 passed; 1 failed.
validation suite: 6002 tests; 6001 passed; 1 failed.

### System Configuration
Beyond Linuxfromscratch.org, as at http://www.linuxfromscratch.org/blfs/view/svn/general/imagemagick.html but using 7.0.10-57 (all tests passed with 7.0.10-27, but clearly we should move on from that).

- ImageMagick version: 7.0.10-27
- Environment  Linux x86_64 - linuxfromscratch from last month (package versions available if required)
- Additional information: Whenever I've run this in a previous version all tests have passed, no idea if this is a new or old logic error.

**Comment by zarniwhoop73** [comment]
I retried this with 7.0.10-57 and this time there were no failures at al. Therefore I cannot identify if this is a new issue, or has been lurking in the background.

**Comment by urban-warrior** [comment]
There could have been a transient problem that was systemic, that is, each block of unit tests failed in the same way.  Since the unit tests pass now, is there any further action required for this issue?  If not, feel free to close the issue.

**Comment by zarniwhoop73** [comment]
There was only one detailed failure message , and I'm happy to accept that that one was a transient failure. For the first three sets of subtests (the reported failure was in the fourth set) the total shown as failed was 0. No more tests failed after this, but every subsequent subtest had a count of 1 failed although every test in the subtest was reported to 'pass'.

See the montage and stream results at the end of what I posted in Steps to Reproduce. The overall total of 1 failed is ok, but the remaining subtests are all showing one failure.
$grep 'fail ' validate.log 
  test 79: -map netscape:... fail @ tests/validate.c/ValidateConvertCommand/1370.

 $grep failed validate.log 
  summary: 26 subtests; 26 passed; 0 failed.
  summary: 2 subtests; 2 passed; 0 failed.
  summary: 59 subtests; 59 passed; 0 failed.
  summary: 149 subtests; 148 passed; 1 failed.
  summary: 949 subtests; 948 passed; 1 failed.
  summary: 949 subtests; 948 passed; 1 failed.
  summary: 949 subtests; 948 passed; 1 failed.
  summary: 949 subtests; 948 passed; 1 failed.
  summary: 949 subtests; 948 passed; 1 failed.
  summary: 949 subtests; 948 passed; 1 failed.
  summary: 4 subtests; 3 passed; 1 failed.
  summary: 60 subtests; 59 passed; 1 failed.
  summary: 7 subtests; 6 passed; 1 failed.
  summary: 1 subtests; 0 passed; 1 failed.
validation suite: 6002 tests; 6001 passed; 1 failed.

I suspect that a variable for the sub-test number of failures is either shared with the total number of failures, or else not getting (re-)initialised to 0 when a sub-test starts. But I'm not good on perl and since no tests normally fail I've no idea where to look.

**Comment by urban-warrior** [comment]
# fails is a global variable.  We'll update so that # fails is local to each subtest.
