### ISSUE TITLE
psd:layer.invisible gone

### ISSUE THREAD

**Issue by axeld** [ImageMagick/ImageMagick#3128]
ImageMagick 6.9.3-7 "identify" emits an artifact called "psd:layer.invisible" for TIFFs written by Photoshop. I was using this to detect whether or not the layer was visible at all.

With ImageMagick 7.0.10-49, this artifact is gone. I possibly could achieve the same thing by evaluating %[compose] == "None" now. Is that equivalent?

If this change was on purpose, and there is an adequate replacement, please feel free to close this ticket without action.

**Comment by dlemstra** [comment]
That artifact was never added to ImageMagick 7 and you are correct that you can check if `compose` is `None`.

**Comment by axeld** [comment]
Thanks for the quick response!
