### ISSUE TITLE
Magick++ is not compliant to C++1z

### ISSUE THREAD

**Issue by SirRade** [ImageMagick/ImageMagick#313]
Magick++ contains hundreds of syntax errors since [std::unary_function<>](http://en.cppreference.com/w/cpp/utility/functional/unary_function) got removed from the C++ standard. In particular, Visual Studio 2017 RC with the /std:c++latest switch enabled refuses to compile it.  
This is causing our library for artificial intelligence, [Hippocrates](https://github.com/SirRade/Hippocrates), great trouble, as we planned to use Magick++ for it's [image recognition module](https://github.com/IDPA16/CNN-Code).  

Fortunately, the fix is rather simple: Because std::unary_function<> was guaranteed to be an empty base, you can either
- Just remove the unnecessary inheritance completly
- replace it by an empty class called `Magick::unary_function` or, for no replacement, even `Magick::std::unary_function`

This fix should take at most 15 minutes. Should I create a pull request?

**Comment by dlemstra** [comment]
Pull requests are always welcome 👍  I don't know if we can remove it without breaking the API/ABI. If we can that would be my preferred solution.

**Comment by SirRade** [comment]
It would certainly *change* both the API and ABI.
But I'm very positive that this would not *break* anything.  

In theory it is possible that someone somewhere is iteration over a
```cpp
template <typename ArgumentType, typename ResultType>
std::vector<std::unary_function<ArgumentType, ResultType>> v;
``` 
but I'd wager to say there is no sensible way anyone ever did that.
1. std::unary_function<> was since the beginning defined as expty and only to be used by implementatoins of the STL and standard library to document their implementation. So if someone did use the interface in the way I described, his code would have been ill-formed in the first place
2. The thought of putting together a construct like that seems so extremely redundandly broad, unhelpful and misguided that the only use case I can imagine of experimental natur is

**Comment by dlemstra** [comment]
We have also applied your changes to IM6. Thanks for helping us out 🍾 .

**Comment by SirRade** [comment]
Open source is great, isn't it? :)
