### ISSUE TITLE
A error occurred when install imagemagick by homebrew on MacOS 10.14.6

### ISSUE THREAD

**Issue by sytuzhouyong** [ImageMagick/ImageMagick#3132]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
my macos operating system is 10.14.6 Mojave, when i type 'brew install imagemagick' in zsh shell window, it shows me a error as below
```
➜  bin brew install imagemagick
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
hackintool                                          vuescan

Error: python@3.9: undefined method `on_macos' for #<PourBottleCheck:0x00007f937fb2fc68>

```

### System Configuration

- ImageMagick version: 
   None
- Environment (Operating system, version and so on):
```
Operating system:
     macOS Mojave  10.14.6

➜  brew --version
Homebrew 2.4.16
Homebrew/homebrew-core (git revision 0fa32; last commit 2021-01-17)
Homebrew/homebrew-cask (git revision 3a519f0; last commit 2021-01-18)
```
- Additional information:
my default python version is 2.7.16，and python3 version is 3.9.1
```
➜  Desktop which python3
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3
```

**Comment by urban-warrior** [comment]
Post your issue to the HomeBrew community.  We did not write nor do we support HomeBrew.
