### ISSUE TITLE
AVIF incorrectly identified as HEIC, if file extension is missing

### ISSUE THREAD

**Issue by oittaa** [ImageMagick/ImageMagick#3137]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

AVIF incorrectly identified as HEIC, if file extension is missing

### Steps to Reproduce

```
wget -O test.avif https://libre-software.net/wp-content/uploads/AVIF/AVIF%20test%20file%20-%20Your%20browser%20%28software%29%20supports%20AVIF%20%28Quality%2025%29.avif
identify -format '%[magick]' test.avif
```
Output: `AVIF`

```
wget -O test_no_ext https://libre-software.net/wp-content/uploads/AVIF/AVIF%20test%20file%20-%20Your%20browser%20%28software%29%20supports%20AVIF%20%28Quality%2025%29.avif
identify -format '%[magick]' test_no_ext
```
Output: `HEIC`

### System Configuration

- ImageMagick version: 7.0.10-58
- Environment (Operating system, version and so on): Debian Buster
- Additional information: LIB_HEIF 1.10.0, LIB_AOM 2.0.1

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by urban-warrior** [comment]
We reverted the patch and have a better, more robust method to resolve this issue.  It will take a week or two to finalize the solution.  Stand by...

**Comment by dlemstra** [comment]
I just pushed a change that will output `AVIF` as the format. This will require version `v1.11.0` of `libheif`. This will become available in the next version of ImageMagick.

**Comment by dlemstra** [comment]
Attaching file [aaa.zip](https://github.com/ImageMagick/ImageMagick/files/8397430/aaa.zip).
