### ISSUE TITLE
Error processing some jpegs version 7.0.10-58

### ISSUE THREAD

**Issue by jshow** [ImageMagick/ImageMagick#3145]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In version 7.0.10-58, **convert**(identify, etc) is reporting DelegateSupportNotBuiltin for some jpegs. The convert succeeds, but the firing of the error causes errors to be triggered upstream (based on parsing the response)

### Steps to Reproduce
```
# ./magick convert /downloads/bad_media/3431188e-1bea-4f94-8fa4-665df105cdd7.jpg -resize 50%  /downloads/bad_media/3431188e-1bea-4f94-8fa4-665df105cdd7_converted.jpg
convert: DelegateLibrarySupportNotBuiltIn '/downloads/bad_media/3431188e-1bea-4f94-8fa4-665df105cdd7.jpg' (XML) @ error/profile.c/ValidateXMPProfile/1927.
```
on this image:
![3431188e-1bea-4f94-8fa4-665df105cdd7](https://user-images.githubusercontent.com/1148494/105411806-dd276000-5c01-11eb-9bd9-ba1b217b05db.jpg)

### System Configuration

- ImageMagick version: 7.0.10-58
- Environment (Operating system, version and so on): Amazon Linux 2
- Additional information:
./convert -version
Version: ImageMagick 7.0.10-58 Q16 x86_64 2021-01-14 https://imagemagick.org
Copyright: © 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib heic jng jp2 jpeg png tiff webp zlib

thank you!

**Comment by fmw42** [comment]
With IM 7, use magick in place of convert, and also no macick convert.

**Comment by snibgo** [comment]
Your list of "Delegates (built-in)" doesn't include "XML". I think that is needed to read XMP profiles.

**Comment by jshow** [comment]
This bug does not exist in 7.0.8-45 - it's a regression

**Comment by dlemstra** [comment]
In the next version of ImageMagick we will raise a warning instead of an error when the library is build without the xml delegate.

**Comment by jshow** [comment]
thanks for your help all - I will confirm

I'm building from source, trying to find the switch/library for the xml delegate, google not much help

**Comment by fmw42** [comment]
Perhaps this will help. https://itectec.com/ubuntu/ubuntu-how-to-install-delegate-libraries-for-image-magick-7-0-7/

**Comment by jshow** [comment]
I did not resolve (gave up on trying to build from source - all packages/delegates must be compiled from source for AWS lambda layer) - will wait til this issue is resolve in future version - thanks

**Comment by ndivakaran** [comment]
We tried with the latest version of imagemagic (7.0.11.14)  , but i could not resolve my  issue. I try to load some JPEG images still get the error (identify: DelegateLibrarySupportNotBuiltIn '/testimg/CHDC1K.jpg' (XML) @ error/profile.c/ValidateXMPProfile/1927.)

**Comment by dlemstra** [comment]
The latest version is not `7.0.11-14` @ndivakaran and it looks like you are using an older version that what you are saying. You probably want to check the output of `convert -version`.

**Comment by ndivakaran** [comment]
thanks @dlemstra  for  your valid input. I used  "Version: ImageMagick 7.1.0-0 Q8 aarch64 2021-06-13 https://imagemagick.org "  and  now i get "identify: DelegateLibrarySupportNotBuiltIn 'testimg/CHDC2K.jpg' (XML) @ warning/profile.c/ValidateXMPProfile/1931".  I observed that  get "warning"  instead of "error".

**Comment by ndivakaran** [comment]
@dlemstra I used "Version: ImageMagick 7.1.0-0 Q8 to build for aarch64-linux-gnu  ,but "libMagick++-7.Q8HDRI.a" is not found in lib.
When i tried to  older version (7.0.7.31) we found in lib folder. To build latest version we need to any modification in script?

**Comment by ndivakaran** [comment]
I used script is "./configure --host=aarch64-linux-gnu --target=aarch64-linux-gnu " but libMagick++-7.Q8HDRI.a  is not generated. (just use ./configure generate libMagick++-7.Q8HDRI.a  ) .I tried with  --with-magick-plus-plus=yes but its not worked.  
Thank you
