### ISSUE TITLE
Uncorrect result when converting YUV444 HEIF images to PNG (both HEIC & AVIF, both 8bit & 10bit).

### ISSUE THREAD

**Issue by Mr-Z-2697** [ImageMagick/ImageMagick#3153]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Colors are blocky.
It looks like YUV444 HEIF images will be somehow convert to YUV420 then to actual RGB.
So here comes another question: is using point resize when upscaling chroma panel of YUV420 image a good idea?

### Steps to Reproduce
1. Convert a YUV444 HEIF image to PNG.
2. See blocky colors.

### System Configuration

- ImageMagick version: 7.0.10-58-Q16-HDRI-x64-dll
- Environment (Operating system, version and so on): Windows10 Pro 1909
- Additional information: https://github.com/d2phap/ImageGlass/issues/977

**Comment by dlemstra** [comment]
We could always decode the image in `YUV444` instead of `YUV420` but I prefer we would only do that when the image is `YUV444`. But we can now not detect the chroma of the image. I posted this feature request upstream: https://github.com/strukturag/libheif/issues/442

**Comment by dlemstra** [comment]
We got the advice to decode the image in RGB instead and we will do that in the next release. We get the following output image:
![rgb](https://user-images.githubusercontent.com/10426229/108773339-77aaf400-755e-11eb-91c2-3aeddf774455.png)

**Comment by Mr-Z-2697** [comment]
> We got the advice to decode the image in RGB instead and we will do that in the next release. We get the following output image:
> ![rgb](https://user-images.githubusercontent.com/10426229/108773339-77aaf400-755e-11eb-91c2-3aeddf774455.png)
> 

Thank you!
