### ISSUE TITLE
Variety of RAW files seemingly using dng:decode delegate

### ISSUE THREAD

**Issue by bvb-sc** [ImageMagick/ImageMagick#3156]
### Description
As of version 7.0.10-58 we are noticing some issues with RAW files. All of them appear to be using the delegate we defined for `dng:decode`. 

Delegate defined as such:
```
<delegate decode="dng:decode" command="darktable-wrapper &quot;%f&quot; &quot;%i&quot; &quot;%u.ppm&quot;"/>
```
Sample files: https://bvbpublicstorage.blob.core.windows.net/public/raw.zip

Error received:

```
$ convert "/tmp/grass_branch.raf[0]" "/tmp/grass_branch.pdf"
convert: delegate failed `'ufraw-batch' --silent --create-id=also --out-type=png --out-depth=16 --output='%u.png' '%i'' @ error/delegate.c/InvokeDelegate/1903.
convert: unable to open image '/tmp-im/magick-90WZ_BJE7kLuIuAg3nBZT6gXfRD1rclG.ppm': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: no images defined `/tmp/grass_branch.pdf' @ error/convert.c/ConvertImageCommand/3304.
```

Up until version 7.0.10-57, we do not get delegate errors:

### Steps to Reproduce
Execute command `convert "/<file>.NEF[0]" "/file.pdf"` 
(same error for any of the files in the zip)

### System Configuration
- ImageMagick version: 7.0.10-58/59
- Environment (Operating system, version and so on): Linux Ubuntu Focal 20.04

**Comment by urban-warrior** [comment]
Change `--output=&quot;%u.png&quot;` to `&quot;--output=%u.png&quot;` in your `dng:decode` delegate element in `delegates.xml`.
