### ISSUE TITLE
Completely Destroyed Photos, When Upsizing/Downsizing!

### ISSUE THREAD

**Issue by netgurucr** [ImageMagick/ImageMagick#3159]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Combining -distort resize with -filter sinc or -filter sincfast, completely destroys photos.

### Steps to Reproduce

magick "photo input" -strip -filter sinc -distort resize 1280 -clamp -depth 16 "png output"

magick "photo input" -strip -filter sincfast -distort resize 1280 -clamp -depth 16 "png output"

### System Configuration

- ImageMagick version: 7.0.11-0 Q16 HDRI x64 2021-02-13
- Environment (Operating system, version and so on): Windows 10
- Additional information: None

**Comment by fmw42** [comment]
see (especially the last link)

https://legacy.imagemagick.org/Usage/resize/
https://legacy.imagemagick.org/Usage/filter/
https://legacy.imagemagick.org/Usage/filter/nicolas/

**Comment by netgurucr** [comment]
Super, thank you!
