### ISSUE TITLE
ImageMagick-6.9.6-6 exact gradient colors

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#316]
Hi,

Someone tested ImageMagick 6.9.6-6 against PHP Imagick's set of tests and found an issue: https://github.com/mkoppanen/imagick/issues/187

It seems that from this bug report 
https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=30570 a change was committed:
https://github.com/ImageMagick/ImageMagick/commit/d75ed24792891c10837da941adea162073093dda

That change, has altered the colors of pixels that are generated for a black-white gradient.

What [this test is doing](https://github.com/mkoppanen/imagick/blob/master/tests/256_Imagick_exportImagePixels_basic.phpt) is creating a 256x256 image, that is a gradient from black to white. It then checks that each of the pixels is the correct color, on the assumption that they should be 0/255, 1/255, 2/255,....., 255/255

The colors are slightly off for each pixel, other than the black one. At the white end of the gradient, the color is not 255/255 but is instead 0.99609369039445.

According to the reporter, this issue does not affect ImageMagick 7.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by Danack** [comment]
Thanks. Looks fixed for the existing tests. 

I'm going to try to setup another test for the 'diagonal' gradient, but will do that at a later date.
