### ISSUE TITLE
Get('orientation') always returns 'Undefined" in perlmagick

### ISSUE THREAD

**Issue by hstejas** [ImageMagick/ImageMagick#3162]
### Prerequisites

- [ y] I have written a descriptive issue title
- [ y] I have verified that I am using the latest version of ImageMagick
- [ y] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The orientation property when read from the Perl `Image::Magick` module always returns 'Undefined'

### Steps to Reproduce
Example image: https://raw.githubusercontent.com/ianare/exif-samples/master/jpg/orientation/landscape_2.jpg

```
wget https://raw.githubusercontent.com/ianare/exif-samples/master/jpg/orientation/landscape_2.jpg
identify -format '%[orientation]' landscape_2.jpg 
TopRight

perl -MImage::Magick  -E 'my $i = Image::Magick->new; say $i->Get("version"); $i->Read("landscape_2.jpg") ; say $i->Get("magick", "orientation", "columns");'
ImageMagick 7.0.10-59 Q8 armv7l 2021-01-23 https://imagemagick.org
JPEGUndefined600
```

### System Configuration

- ImageMagick version: 
   - ImageMagick 7.0.10-59 Q8 armv7l 2021-01-23 https://imagemagick.org  
   - ImageMagick 7.0.10-60 Q8 x86_64 2021-01-24 https://imagemagick.org
   - ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
- Environment (Operating system, version and so on):
   - Ubuntu 20.04
   - Ubuntu 18.04
- Additional information:
    - perl versions 5.30 and 5.28

**Comment by hstejas** [comment]
Initial analysis
In file PerlMagick/quantum/quantum.xs.in Line 5480

```
        case 'O':
        case 'o':
        {
          if (LocaleCompare(attribute,"orientation") == 0)
            {
              j=info ? info->image_info->orientation : image ?
                image->orientation : UndefinedOrientation;
```
`info->image_info->orientation` which is `0` seems to have higher precedence over `image->orientation` which is `2`
either `info->image_info->orientation` is not initialized or the order needs to be switched

Other attributes like `endian` and `compression` seem to follow this precedence

**Comment by urban-warrior** [comment]
Since you are asking for attributes associated with an image, the image attribute should take precedence over the ImageInfo structure.   We will export a patch for this issue within the next day or two.  Thanks,

**Comment by urban-warrior** [comment]
Download the latest release of ImageMagick.  It includes a patch to this issue.

**Comment by hstejas** [comment]
Hello @urban-warrior ,
Tanks for the fix, orientation is not Undefined anymore (I have checked Q8 only)
But the documentation says that orientation would be one of `top-left, top-right, bottom-right, bottom-left, left-top, right-top, right-bottom, left-bottom` here https://github.com/ImageMagick/ImageMagick/blob/a9aa55e6d1cc00df4206ddc37b7db4bc98dfd181/www/perl-magick.html#L1652

But I see that it returns something like `TopLeft`, Should the Document be updated?

**Comment by urban-warrior** [comment]
Fixed.  Thanks.

**Comment by hstejas** [comment]
Thanks for the fix
