### ISSUE TITLE
whit-method-prefix broken

### ISSUE THREAD

**Issue by vhuber** [ImageMagick/ImageMagick#3163]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

```sh
./configure --with-method-prefix=toto
```
generates
```sh
./MagickCore/magick-baseconfig.h:1199:37: error: pasting ""toto"" and "RollImage" does not give a valid preprocessing token
 #define MAGICKCORE_NAMESPACE_PREFIX "cov"
```

notice the quotes that are doubled.

### Steps to Reproduce
given upper

### System Configuration
Linux

- ImageMagick 7.0.10-59:
- Linux:
- Reset that line in correct form
https://github.com/ImageMagick/ImageMagick/commit/c1bfec283549b81ee8b7c49817da77396a3612e9#diff-90d08e583c4c9c6f391b2ae90f819f600a6326928ea9512c9e0c6d98e9f29ac2L22444

### How to fix
- remove quotes on that line - https://github.com/ImageMagick/ImageMagick/commit/c1bfec283549b81ee8b7c49817da77396a3612e9#diff-90d08e583c4c9c6f391b2ae90f819f600a6326928ea9512c9e0c6d98e9f29ac2L22444

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by vhuber** [comment]
Thank you @urban-warrior.
do you have an idea of the required time to pass the beta in the next state (not beta) ?

**Comment by dlemstra** [comment]
We publish a new release very frequently: https://github.com/ImageMagick/ImageMagick/releases. We cannot give you an exact date but it will probably not take long.

**Comment by urban-warrior** [comment]
Download the latest release of ImageMagick.  It includes the patch to this issue.
