### ISSUE TITLE
Issue with .nef image to jpg conversion issue.

### ISSUE THREAD

**Issue by sruthi09I** [ImageMagick/ImageMagick#3165]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Color of output file changes on converting from .nef format to jpg.

### Steps to Reproduce

I have a raw image .nef file which I am trying to convert to jpg file. Converted jpg file color is not as expected, it is darker than the original image.

On adding an extra parameter(-e) to delegates.xml file in ImageMagick-7.0.3 version as below, the issue is resolved:
<delegate decode="dng:decode" stealth="True" command="dcraw.exe -e -6 -W -O "%u.ppm" "%i""/>

But tried adding the same parameter -e in later imagemagick versions, the issue still exits. Tried in imagemagick versions - ImageMagick-7.0.6-Q16, 7.0.8-3 Q16 and ImageMagick 7.0.10-10 Q16.

Do we require to add any other parameters in latest imagemagick versions? If yes can you please the details.

Command used to convert raw image to jpg format:
magick.exe nef:C:\ASSETS\cust\OriginalAsset.nef -intent relative -sample "1024x768>" -quality 95 -colorspace sRGB -strip -auto-orient C:\ASSETS\cust\OriginalAsset-S.JPG

Verbose output with IM 7.0.3 version(working):
dcraw.exe -6 -W -O "C:/Users/sinampud/AppData/Local/Temp/magick-30052jo1esoFwvcjL.ppm" "C:/Users/sinampud/AppData/Local/Temp/magick-30052R4Ji-g3TlcFG"
C:/Users/sinampud/AppData/Local/Temp/magick-30052jo1esoFwvcjL.ppm PPM 2868x4312 2868x4312+0+0 16-bit sRGB 74.2MB 0.063u 0:00.074
nef:C:\ASSETS\cust\OriginalAsset.nef=>C:/Users/sinampud/AppData/Local/Temp/magick-30052jo1esoFwvcjL.ppm NEF 2868x4312 2868x4312+0+0 16-bit sRGB 74.2MB 0.016u 0:00.012
nef:C:\ASSETS\cust\OriginalAsset.nef=>C:\ASSETS\cust\OriginalAsset-S.JPG NEF 2868x4312=>511x768 511x768+0+0 16-bit sRGB 152KB 0.031u 0:00.015

Verbose output with later IM versions(not working):
nef:C:\ASSETS\cust\OriginalAsset.nef=>C:\ASSETS\cust\OriginalAsset.nef NEF 2868x4312 4320x2868+0+0 16-bit sRGB 22.7287MiB 3.359u 0:01.213
nef:C:\ASSETS\cust\OriginalAsset.nef=>C:\ASSETS\cust\OriginalAsset-S.JPG NEF 2868x4312=>511x768 770x511+0+0 16-bit sRGB 155744B 0.031u 0:00.017

### System Configuration

- ImageMagick version:imagemagick versions - ImageMagick-7.0.6-Q16(Working), 7.0.8-3 Q16(Not working) and ImageMagick 7.0.10-10 Q16(Not working)
- Environment : Windows 10, Windows server 2016.
- Additional information:

**Comment by sruthi09I** [comment]
[metadata.txt](https://github.com/ImageMagick/ImageMagick/files/5887603/metadata.txt)

**Comment by snibgo** [comment]
You already asked this at https://github.com/ImageMagick/ImageMagick/discussions/3133

I gave an answer, but you didn't reply.

**Comment by sruthi09I** [comment]
Sorry i actually tried out the recommendation mentioned in discussion forum#3133, but forgot to tell you. I still see the issue existing even after trying options-define dng:use-auto-wb=true. The color is not as expected.
Imagemagick version i used have delegates.
Can you please close the discussion and reopen this issue for further communication.
