### ISSUE TITLE
TIFF no GPS Info identified and copied

### ISSUE THREAD

**Issue by marsie321** [ImageMagick/ImageMagick#3167]
This might be a **general problem** with imagemagick identify and libtiff. 
 **jpg + exif is OK but tiff + exif is not reading GPSinfo.** 

I added a reference geotagged image. (see attachment below)
GPS_location_stamped_with_GPStamper.jpg/tiff.

**identify** -verbose GPS_location_stamped_with_GPStamper.**jpg** | grep -i gps
  Filename: GPS_location_stamped_with_GPStamper.jpg
    comment: Location stamped with GPStamper
    exif:GPSInfo: 3360
    exif:GPSLatitude: 41/1, 53/1, 12633/625
    exif:GPSLatitudeRef: N
    exif:GPSLongitude: 87/1, 37/1, 35223/1250
    exif:GPSLongitudeRef: W

**identify** -verbose GPS_location_stamped_with_GPStamper.**tif** | grep -i gps
  Filename: GPS_location_stamped_with_GPStamper.tif
identify: Wrong data type 2 for "UserComment"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1046.
identify: Wrong data type 3 for "PixelXDimension"; tag ignored. `TIFFReadCustomDirectory' @ 
warning/tiff.c/TIFFWarnings/1046.
identify: Wrong data type 3 for "PixelYDimension"; tag ignored. `TIFFReadCustomDirectory' @ warning/tiff.c/TIFFWarnings/1046.

**exiv2** -pv images-zip/GPS_location_stamped_with_GPStamper.tif  | grep -i GPS
0x8825 Image        GPSTag                      Long        1  7320
0x0001 GPSInfo      GPSLatitudeRef              Ascii       2  N
0x0002 GPSInfo      GPSLatitude                 Rational    3  41/1 53/1 12633/625
0x0003 GPSInfo      GPSLongitudeRef             Ascii       2  W
0x0004 GPSInfo      GPSLongitude                Rational    3  87/1 37/1 35223/1250

I uploaded some sample data:
[images-zip.zip](https://github.com/ImageMagick/ImageMagick/files/5879740/images-zip.zip)

Of course you can use tools like exiftools or exiv2, but Imagemagick can do so much and reading GPSInfo is something very common.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by marsie321** [comment]
Thank you too.

Do you patch ImageMagick6 only or ImageMagick7 too. And I could test the patch.

**Comment by urban-warrior** [comment]
Both.  For GPS tags, libtiff 4.2.0+ is required.

**Comment by marsie321** [comment]
Thank you for the beta,

I just compiled and tested the beta and I can confirm, that the beta () has now gps tags.
But there might a problem with the conversion, the coordinates are with tiffs not correct, see the example below (the test-images can be found in zip of my first post).

identify --version
Version: ImageMagick **7.0.10-62 Q16 x86_64 2021-01-31** https://imagemagick.org

**identify** -verbose images-zip/GPS_location_stamped_with_GPStamper.**tif** | grep -i lati
    gps:latitude: 0.000000,3.070312,0.000000
    gps:latitudeRef: N

identify -verbose images-zip/GPS_location_stamped_with_GPStamper.**jpg** | grep -i lati
    exif:GPSLatitude: 41/1, 53/1, 12633/625
    exif:GPSLatitudeRef: N

exiftool -v images-zip/GPS_location_stamped_with_GPStamper.tif | grep -i lat
  | | 0)  GPSLatitudeRef = N
  | | 1)  GPSLatitude = 41 53 20.2128 (41/1 53/1 12633/625)


# === libtiff should be fine (> 4.2.0+)
apt-cache policy libtiff-dev 
libtiff-dev:
  Installed: 4.2.0-1
  Candidate: 4.2.0-1
  Version table:
 *** 4.2.0-1 100
        100 /var/lib/dpkg/status
     4.1.0+git191117-2~deb10u1 500
        500 http://ftp.de.debian.org/debian stable/main amd64 Packages
        500 http://security.debian.org/debian-security stable/updates/main amd64 Packages
        500 http://ftp.debian.org/debian stable/main amd64 Packages
        500 http://ftp.de.debian.org/debian buster/main amd64 Packages
        500 http://security.debian.org/debian-security buster/updates/main amd64 Packages


apt-cache policy libtiff5
libtiff5:
  Installed: 4.2.0-1
  Candidate: 4.2.0-1
  Version table:
 *** 4.2.0-1 100
        100 /var/lib/dpkg/status
     4.1.0+git191117-2~deb10u1 500
        500 http://ftp.de.debian.org/debian stable/main amd64 Packages
        500 http://security.debian.org/debian-security stable/updates/main amd64 Packages
        500 http://ftp.debian.org/debian stable/main amd64 Packages
        500 http://ftp.de.debian.org/debian buster/main amd64 Packages
        500 http://security.debian.org/debian-security buster/updates/main amd64 Packages
     4.0.8-2+deb9u5 500
        500 http://ftp.de.debian.org/debian stretch/main amd64 Packages
        500 http://security.debian.org/debian-security stretch/updates/main amd64 Package

**Comment by marsie321** [comment]
Is libtiff linked statically, because I don't see any links with?

ldd /usr/local/bin/magick | grep -i libtiff
   ... empty ...

ldd /usr/local/bin/magick
	linux-vdso.so.1 (0x00007ffe49d9c000)
	libMagickCore-7.Q16HDRI.so.9 => /usr/local/lib/libMagickCore-7.Q16HDRI.so.9 (0x00007fa9f1546000)
	libMagickWand-7.Q16HDRI.so.9 => /usr/local/lib/libMagickWand-7.Q16HDRI.so.9 (0x00007fa9f140f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa9f124a000)
	libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fa9f109c000)
	libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fa9f1054000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fa9f0f91000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007fa9f0f7c000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007fa9f0e39000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007fa9f0e26000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa9f0e09000)
	libltdl.so.7 => /lib/x86_64-linux-gnu/libltdl.so.7 (0x00007fa9f0dfc000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa9f0cb8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa9f0c96000)
	libgomp.so.1 => /lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fa9f0c56000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa9f0c3c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa9f1863000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa9f0c36000)
	libicuuc.so.67 => /lib/x86_64-linux-gnu/libicuuc.so.67 (0x00007fa9f0a4b000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fa9f0a23000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fa9f09f4000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fa9f09eb000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fa9f09b1000)
	libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007fa9f09a3000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fa9f0976000)
	libicudata.so.67 => /lib/x86_64-linux-gnu/libicudata.so.67 (0x00007fa9eee5d000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa9eec90000)
	libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007fa9eec6d000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fa9eea69000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fa9ee861000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fa9ee847000)

**Comment by urban-warrior** [comment]
Check `MagickCore/magick-baseconfig.h` and look for `MAGICKCORE_HAVE_TIFFREADGPSDIRECTORY`.  It must be defined to read the GPS tags.

Post any incorrect results to the `libtiff` developers.  We simply call `TIFFPrintDirectory()` to garner tags so any unexpected results are within the libtiff code set.

ImageMagick has a built-in EXIF/GPS parser.  If you provide a `libtiff` API snippet that returns the EXIF profile, we could pass it directly to our parser and likely extract the correct GPS tags.

**Comment by marsie321** [comment]
where the official libtiff git, so I will look for the exif-gps snippet. Is the following the correct one?
https://gitlab.com/libtiff/libtiff/-/issues

... checking for TIFFReadGPSDirectory... yes ... see above, and 
cat MagickCore/magick-baseconfig.h | grep MAGICKCORE_HAVE_TIFFREADGPSDIRECTORY
#ifndef MAGICKCORE_HAVE_TIFFREADGPSDIRECTORY
#define MAGICKCORE_HAVE_TIFFREADGPSDIRECTORY 1

So I guess from compile side and imagemagick side, everything seems fine.
