### ISSUE TITLE
Photoshop Layer styles are not rendering at all when converting TIF to JPG

### ISSUE THREAD

**Issue by Vignesh-Vin** [ImageMagick/ImageMagick#3173]
### What I am trying to do

I am trying to convert a .tif file made using Photoshop 7.0 (don't ask me why) to .jpg file. And I am also using the `-flatten` to get a single merged jpg file.

### Description
I am converting tif files that I made in Photoshop to jpg, There are no errors in conversion, but the layer styles that I added in Photoshop (like stroke, drop shadow, outer glow, color overlay etc.) are not rendering in the final jpg. And 

### Steps to Reproduce
 - Take a tif file with multiple layers with the layers having any "Layer Styles" applied in Photoshop.
 - Convert it to jpg using the command `magick convert test.tif -flatten test.jpg`
 - I've also tried it with Photoshop CC 2015, but it's the same story
![fileComparision](https://user-images.githubusercontent.com/59286418/106387618-91926480-6400-11eb-9dae-d0d9f635bc8c.jpg)

### System Configuration
I'm using Photoshop 7.0

- ImageMagick version:  7.0.10-58 Q16 x64
- Environment (Operating system, version and so on): Windows 10 64-bit build 20H2

**Comment by urban-warrior** [comment]
Try exporting your image from Photoshop in the PSD format and converting to JPEG.  Also, post a link to both the TIFF and PSD formats of your image.  We need to reproduce the problem before we can offer additional insight into the problem.

**Comment by Vignesh-Vin** [comment]
I tried saving my file as PSD in Photoshop, and then converting PSD file to jpg using ImageMagick, but it doesn't solve the issue.
And here are the links to my files:
[PSD file](https://www.mediafire.com/file/2ajg30v6qr9g4nc/test.psd/file) (made with Photoshop), [JPG file](https://www.mediafire.com/file/9qz3l2xd8n9rg94/test_out.jpg/file) (converted using ImageMagick)

**Comment by fmw42** [comment]
Your PSD file seems to need an Adobe login to access. Also I get a pop window asking to download the obsolete Adobe Flash.

Please fix this.

**Comment by Vignesh-Vin** [comment]
That's very strange,
What version of Photoshop are you using?

Try this one instead [PSD](https://www.mediafire.com/file/m2zk6zleupbxg8a/test2.psd/file)

**Comment by Vignesh-Vin** [comment]
Sometimes "Clipping Masks" in Photoshop are also not rendering correctly.

**Comment by fmw42** [comment]
Clipping masks are not related to your original question. Please start a new question and provide and example image along with your exact command and version of ImageMagick

**Comment by Vignesh-Vin** [comment]
> Clipping masks are not related to your original question. Please do not mix questions. Please start a new question and provide and example image along with your exact command and version of ImageMagick.
> 
> 

Sorry
