### ISSUE TITLE
-auto-threshold with define does not return threshold value to terminal

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#3174]
In IM 7.0.10.61 (Mac OSX Sierra), -auto-threshold with the define set to true does not return the threshold value to the terminal.

The documentation says:

`The computed threshold is returned as the auto-threshold:threshold image property. To instead print to your device, use -define auto-threshold:threshold=true.`

But when I do

`magick logo: -alpha off -define auto-threshold:threshold=true -auto-threshold otsu x.png`

No threshold value is returned to terminal. The image is properly thresholded. I have tried both true and false. Neither return a value.

**Comment by urban-warrior** [comment]
Try `-define auto-threshold:verbose=true`.

**Comment by fmw42** [comment]
Thanks. That works. 

I see you have changed the documentation already. Glad it was a documentation problem and not in the code.  Thanks.

Fred
