### ISSUE TITLE
"label:@<filename>" breaks on 6.9.6-6

### ISSUE THREAD

**Issue by AlbericC** [ImageMagick/ImageMagick#318]
Recently updated debian package imagemagick and encountered a change in IM behavior :

    $ convert -background lightblue  -fill blue label:@/etc/motd  show:
    convert-im6.q16: not authorized `@/etc/motd' @ error/property.c/InterpretImageProperties/3505.
    convert-im6.q16: no images defined `show:' @ error/convert.c/ConvertImageCommand/3258.

    $ convert -background lightblue  -fill blue label:"$(cat /etc/motd)"  show:  # newline management hell

    $ convert -version
    Version: ImageMagick 6.9.6-6 Q16 x86_64 20161125 http://www.imagemagick.org

Used to work as expected till last week (I use the deb package in testing repository)

**Comment by dlemstra** [comment]
You will need to use your own policy.xml file (info on setting that up can be found here: https://www.imagemagick.org/script/resources.php). I am guessing that debian has disabled reading from file by default because of this security issue: http://www.debian.org/security/2016/dsa-3580.

**Comment by AlbericC** [comment]
Thank you. 

I tried `cp`'ing `/etc/ImageMagick-6/policy.xml` into `~/.config/ImageMagick` and commented the line

    <policy domain="path" rights="none" pattern="@*"/>

But I can't make it to work. I tried exporting `export MAGICK_CONFIGURE_PATH=~/.config/ImageMagick/` 

Am I doing something wrong ? Any pointers on how I should configure this ?

**Comment by mikayla-grace** [comment]
It would be a security flaw to allow local customizations to the security policy to override the system policy.  To enable indirect reads, you must modify the system location of policy.xml.  Alternatively you can download the ImageMagick source, edit config/policy.xml, and build.

**Comment by AlbericC** [comment]
Thank you for that clarification.
