### ISSUE TITLE
Error Installing from Source with WEBP enabled

### ISSUE THREAD

**Issue by hipwebdesign** [ImageMagick/ImageMagick#3189]
I'm using AWS Linux 2, PHP 7.3 — trying to install from source. I made sure to install the `libwebp-devel` library first. Still, I'm getting this every time:

` CC       coders/MagickCore_libMagickCore_7_Q16HDRI_la-webp.lo
coders/webp.c: In function ‘WriteWEBPImage’:
coders/webp.c:1227:3: warning: implicit declaration of function ‘WebPMemoryWriterClear’; did you mean ‘WebPMemoryWriterInit’? [-Wimplicit-function-declaration]
   WebPMemoryWriterClear(&writer);
   ^~~~~~~~~~~~~~~~~~~~~
   WebPMemoryWriterInit
At top level:
coders/webp.c:753:12: warning: ‘WebPEncodeWriter’ defined but not used [-Wunused-function]
 static int WebPEncodeWriter(const unsigned char *stream,size_t length,
            ^~~~~~~~~~~~~~~~
`

**Comment by urban-warrior** [comment]
What version of libwebp are you using?  We may need to add additional checks for this incompatible release of libwebp.

**Comment by hipwebdesign** [comment]
> What version of libwebp are you using? We may need to add additional checks for this incompatible release of libwebp.

libwebp-1.2.0

**Comment by urban-warrior** [comment]
We downloaded libwebp-1.2.0 and built/installed, followed by an install of ImageMagick.  ImageMagick compiled, linked with libwebp without complaint and could write/read WEBP images.  The `identify -list format` command returns:

```
WebP Image Format (libwebp 1.2.0 [020F])
```
We tested with and without WebPMux.

Take a look @ webp/encode.h on your system.  Notice how WebPMemoryWriterClear() is defined as external.  Perhaps you are building against Webp 1.2.0 headers but linking to an older version of libwebp?  Try install libwebp from source and see if that resolves the build issue.

**Comment by hipwebdesign** [comment]
Thank you for this — It looks like `libwebp-devel` that AWS Linux 2 compiles is an older version and is conflicting with the `libwebp` that I installed from source. I removed the `libwebp-devel` package, but I'm having trouble figuring out how to configure it use the new lib from source. Any tips? Otherwise, I'll close the issue. Thanks!

**Comment by Ali-Dalal** [comment]
hi @hipwebdesign 
did you find a solution for this? I am facing the same issue. 

OS: AWS Linux 2

**Comment by hipwebdesign** [comment]
Not yet, I can't seem to get ImageMagick to use the `libwebp` installed from source. I suspect that I've got a path configuration wrong somewhere.
