### ISSUE TITLE
Cannot process video from stdin

### ISSUE THREAD

**Issue by kevinresol** [ImageMagick/ImageMagick#319]
Version: ImageMagick 6.9.6-5 Q16 x86_64 2016-11-15
OS: Mac Sierra 10.12.1

This works: `convert test.mp4[1] frame.png`
This fails: `cat test.mp4 | convert mp4:-[1] frame.png`

```
convert: delegate failed `'ffmpeg' -nostdin -v -1 -i '%i' -vframes %S -vcodec pam -an -f rawvideo -y '%u.pam' 2> '%u'' @ error/delegate.c/InvokeDelegate/1919.
convert: unable to open image `/var/tmp/magick-22006PDdq-m5w5v0L.pam': No such file or directory @ error/blob.c/OpenBlob/2705.
convert: no images defined `frame.png' @ error/convert.c/ConvertImageCommand/3257.
```

**Comment by dlemstra** [comment]
Do you have ffmpeg installed?

**Comment by kevinresol** [comment]
yup, as I said the non-stdin command works

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Is this fixed with the latest release @kevinresol ?

**Comment by kevinresol** [comment]
Sorry for the delay, I will check soon and post and update

**Comment by kevinresol** [comment]
Yes it works now. Thanks!
