### ISSUE TITLE
[7.0.10-61] Please bump version for new soname

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick#3196]
For same reason as https://github.com/ImageMagick/ImageMagick6/issues/133

Please bump version to at least **7.0.11**
and LibMagick++ soname (from 4 to 5 of use same soname than C libraries)

**Comment by urban-warrior** [comment]
We intend to release 7.0.10-62 this weekend.  Next week, we will bump to 7.0.11-0 and 6.9.12-0 as you recommend.
