### ISSUE TITLE
Breaking ABI

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#320]
on the debian side we found that you break abi of core, wand and pp

see https://bugs.debian.org/846385

The only solution is to bump so for all the library.

Could you do it ASAP ?

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in a release of ImageMagick @ http://www.imagemagick.org/download/ within 2-3 days.
