### ISSUE TITLE
Missing break in switch statement?

### ISSUE THREAD

**Issue by qarmin** [ImageMagick/ImageMagick#3200]
https://github.com/ImageMagick/ImageMagick/blob/3e7265214685ed90c836df73870e207e465ad231/MagickCore/attribute.c#L648-L682
This code overwrites values, so everytime only values from last case are used

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
