### ISSUE TITLE
Useless if statement in image-view.c

### ISSUE THREAD

**Issue by qarmin** [ImageMagick/ImageMagick#3201]
https://github.com/ImageMagick/ImageMagick/blob/f548a590c00313db021a687323ee6eb5f30d1e62/MagickCore/image-view.c#L1187-L1188

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
