### ISSUE TITLE
TIF: Delegate library not built-in (LCMS)

### ISSUE THREAD

**Issue by bvb-sc** [ImageMagick/ImageMagick#3204]
### Description
We've noticed that color profiles are no longer being embedded in files with a certain command that used to work before. Even though we haven't changed anything to our build process, other than IM versions.

### Steps to Reproduce
Execute the following command:

```
convert -density 72 -units PixelsPerInch "/tmp/sample.tif[0]" -strip  +profile icm,icc -profile "/tmp/file.icc" -profile "/tmp/file.icc" -alpha off -resize "1100x1100>"  -background white -auto-orient  -define png:include-chunk=zTXt,iCCP,pHYs "/tmp/sample.png"
```

The following error will appear:

```
convert: delegate library support not built-in '/tmp/sample.tif' (LCMS) @ warning/profile.c/ProfileImage/1004.
```

### System Configuration

- ImageMagick version: IM 7.0.10-61 (first spotted on IM 7.0.10-57)
- Environment: Linux Ubuntu Focal 20.04

### Additional
Sample tif and icc file:
[files.zip](https://github.com/ImageMagick/ImageMagick/files/5934466/files.zip)

**Comment by fmw42** [comment]
Do you have LCMS or LCMS2 installed in your delegates.  Look at 

magick -version

does it list lcms or lcms2

**Comment by bvb-sc** [comment]
It doesn't seem to be listed:

```
Version: ImageMagick 7.0.10-61 Q16 x86_64 2021-01-25 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): bzlib cairo fontconfig freetype gslib jbig jng jp2 jpeg ltdl lzma png ps rsvg tiff webp x xml zlib
```

Even though we're adding this package:
```
'liblcms2-2=2.9-4'
```

And building IM with the following parameter:

```
--with-lcms
```

**Comment by fmw42** [comment]
When yo build/install your lcms package, check to see if any errors or if that needs more delegates before it can be installed.

**Comment by bvb-sc** [comment]
We managed to get it working again by explicitly adding 2 more packages:

```
'liblcms2-utils=2.9-4' \
'liblcms2-dev=2.9-4' \
```

Thanks for the help!
