### ISSUE TITLE
So bump need minor version bump

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#323]
Hi,

so bump need a minor version bump for coinstallability of old and new library.

Inded /usr/lib/x86_64-linux-gnu/ImageMagick-6.9.6/configure.xml will conflict....

So please could you open 6.9.7 and release ASAP ?

Bastien

**Comment by mikayla-grace** [comment]
OK, look version 6.9.7 this weekend.
