### ISSUE TITLE
Test suite fails with jpeg-xl 0.3.1

### ISSUE THREAD

**Issue by dbermond** [ImageMagick/ImageMagick#3236]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Test suite fails when using [jpeg-xl 0.3.1](https://gitlab.com/wg1/jpeg-xl/-/releases/v0.3.1).
Works fine with [jpeg-xl 0.3](https://gitlab.com/wg1/jpeg-xl/-/releases/v0.3).

### Steps to Reproduce
Build ImageMagick with `--with-jxl` using jpeg-xl 0.3.1 and run the test suite.

test-suite.log:

```
Caught exception: lt-coderInfo: unable to load module '/build/imagemagick-full/src/ImageMagick/coders/jxl.la': file not found @ error/module.c/OpenModule/1287
not ok
FAIL: Magick++/tests/tests.tap 5
```

Note: the referenced file `jxl.la` is present on the specified path.

### System Configuration

- ImageMagick version: 7.0.10-62
- Environment (Operating system, version and so on): Arch Linux x86_64
- Additional information: compiler gcc 10.2.0

**Comment by urban-warrior** [comment]
This type of exception is usually an environment issue.  Did you configure the dynamic linker run-time bindings after you installed jpeg-xl?  What does `ldd` say about the jxl.so?  It likely complains that it can't find the jpeg-xl library.

**Comment by dbermond** [comment]
Thank you for the reply.

Dynamic linker is fine. After building ImageMagick, `ldd ImageMagick/coders/.libs/jxl.so` shows no missing library links. Link to jpeg-xl library is there: `libjxl.so.0 => /usr/lib/libjxl.so.0 (0x00007f91f3b98000)`.

Also tested with new ImageMagick 7.0.11-0 and new jpeg-xl 0.3.2. Same test failure.

When using jpeg-xl 0.3 (which I rebuilt again just to make sure), the tests passes.

**Comment by urban-warrior** [comment]
It looks like the jpeg-xl developers have removed the JxlEncoderSetDimensions() method.  They are entitled to do so as their API release is not 1.0.0 yet where stability is expected.  We'll need to update the module to the new API requirements.  In the mean-time, you will need to use jpeg-xl 0.2.0 with ImageMagick as it supprts the JxlEncoderSetDimensions() method.

**Comment by dbermond** [comment]
Thank you for investigating this.

Meanwhile, and in line with your explanation, I've found that jpeg-xl image processing looks to be broken with these newer jpeg-xl versions, and not only the test suite. For example, `identify` command is broken for .jxl images.

**Comment by Jan-E** [comment]
> It looks like the jpeg-xl developers have removed the JxlEncoderSetDimensions() method.

Side effect is that the standard build instructions for Windows fail:
https://ci.appveyor.com/project/Jan-E/imagemagick-windows/builds/37876034/job/089d60f0788yiatb?fullLog=true#L3846

**Comment by dlemstra** [comment]
You will need to build the 7.0.11-1 release. It looks like you are using the 7.0.11-0 release that is no longer compatible with the latest commit in our jpeg-xl repository.

**Comment by Jan-E** [comment]
Thanks. That worked, at least for the x64 build:
https://ci.appveyor.com/project/Jan-E/imagemagick-windows/history

X86 is still building:
https://ci.appveyor.com/project/Jan-E/imagemagick-windows/builds/37877821/job/gv3jbvjlniejrqb3

**Comment by dbermond** [comment]
This issue can now be closed since it's now fixed.

Working fine with latest ImageMagick 7.0.11-1 and jpeg-xl 0.3.2.

Thanks to everyone who dedicated time to it.
