### ISSUE TITLE
How can I write multi-images to file buf?

### ISSUE THREAD

**Issue by RiweiChen** [ImageMagick/ImageMagick#325]
Hi, everybody,

I want to make a gif using ImageMagick++, I had look through the doucument, and found out that I can using **writeImages** interface, but how can I direct return the gif-file buf?

I have try this way：
```
    // DOESN'T WORK
    // frames are the multi frames that will be write to gif file.
    Blob blob;
    Magick::writeImages(frames.begin(), frames.end(), &blob);
    char *data = (char*)blob.data();
    buf_len = blob.length();
    //cout<<"buf_len: "<<buf_len<<endl;
    strncpy(buf,data,4000000);        //I want that buf save the gif-file buf, but when I save buf to file, it's not a gif file
    Image temp;
    temp.read(blob);
    temp.write("blob2file.gif");        // I found that blob2file.gif only have one frame

    // buf data is what I want to return.
```

I have try many method, but it still not working.

and later, I try a ugly but work method.
```
    //Work, but ugly.
    
    Magick::writeImages(frames.begin(), frames.end(), ".temp.gif");
    std::ifstream input( ".temp.gif", std::ios::binary );
    std::vector<char> buffer((std::istreambuf_iterator<char>(input)), (std::istreambuf_iterator<char>()));
    for(int i = 0; i < buffer.size(); i++)
    {
	buf[i] = buffer[i];
    }
    buf_len = buffer.size();
    cout<<"buf_len: "<<buf_len<<endl;
    // // buf data is what I want to return.
```

but using this way, I have to write the gif file to disk first, which I think is very time costing. can any one tell the elegent way to do this?

Thanks

**Comment by dlemstra** [comment]
An Image will only contain a single frame. The blob will contain the whole image. I am not really understanding what you are trying to achieve.

**Comment by RiweiChen** [comment]
Hi @dlemstra ,thank you for you response , what I want to achieve is using Magick++ to make a gif, and return the gif file object( I means I can direct write the gif file object to a file, and other tool can direct read it). so in the example code, all I want to return is `buf ` data .

Thank you .

**Comment by dlemstra** [comment]
Not sure what the type of buf is but all you need to do is memcopy the *data into buf.

**Comment by RiweiChen** [comment]
Thanks to @dlemstra , finally I using MagickWand API to the task, the mainly fuction is `MagickGetImagesBlob`

code is like this: 
```
blob = MagickGetImagesBlob(wand, &length);
memcpy((void *)buf, (void *)blob, length);
```

Thank you!
