### ISSUE TITLE
Explicit avif type not recognized

### ISSUE THREAD

**Issue by thommath** [ImageMagick/ImageMagick#3258]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When converting an image to avif it does not recognize the explicit typing format "avif:filename.avif". This breaks converting using streams as a file named "avif:-" is created. 

### Steps to Reproduce

Command to reproduce: 
```
convert -verbose jpg:Downloads/396056.jpg avif:test.avif

  jpg:Downloads/396056.jpg=>Downloads/396056.jpg JPG 1920x1200 1920x1200+0+0 8-bit sRGB 750537B 0.030u 0:00.032
  jpg:Downloads/396056.jpg=>avif:test.avif JPG 1920x1200 1920x1200+0+0 8-bit sRGB 709061B 0.050u 0:00.048
```
### System Configuration

- ImageMagick version: 7.0.11-0 Q16 x86_64 2021-02-13
- Environment (Operating system, version and so on): Ubuntu 19.04
- Additional information:

**Comment by snibgo** [comment]
For IM v7, I suggest you use "magick" instead of "convert".

Please confirm that your installation of IM can write AVIF format files:
```
magick -list format
```

**Comment by urban-warrior** [comment]
Your command works for us.  To support AVIF you must build ImageMagick with a recent release of the HEIC delegate library.  You can confirm with this command:

```
$ magick -list format | grep -i AVIF
     AVIF* rw+   AV1 Image File Format (1.8.0)
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by urban-warrior** [comment]
To support AVIF, you need a modern release of the HEIC delegate library.  We're using this release:

```
$ magick -list format | grep -i AVIF
     AVIF* rw+   AV1 Image File Format (1.8.0)
```

and this command:

```
magick -verbose jpg:logo.jpg avif:-
```
works as expected for us (e.g. an AVIF image is written to `stdout`).

**Comment by thommath** [comment]
Thank you for suck quick response! 
Seems like I didn't include HEIC correctly when building im yesterday. I thought converting to avif was working since 
```convert Downloads/396056.jpg test.avif``` seemed to generate the right output, but of course it was not AVIF format. 

Feel free to close the issue
