### ISSUE TITLE
To set background with -window root needs to set foreground

### ISSUE THREAD

**Issue by mowgli** [ImageMagick/ImageMagick#3259]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I display a image with `display -backdrop -background \#ff0000 image.jpg` everything is fine. But if I do  `display -window root -backdrop -background \#ff0000 image.jpg` I get the background (outside of the image) set to black.

By accident, I found out, that I can get correct result with `display -window root -backdrop -foreground \#ff0000 image.jpg`.

### Steps to Reproduce
The steps are in the description.

### System Configuration
linux. But I seen many persons out there having the same troubles. However, none seems to find the solution with changing `-background` to `-foreground`

- ImageMagick version: Multible, oldest tested version: 6.9.11.60
- Environment (Operating system, version and so on): Multible linux; devuan and gentoo

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
