### ISSUE TITLE
Always killed ?

### ISSUE THREAD

**Issue by crazy-canux** [ImageMagick/ImageMagick#327]
$ convert -delay 2 -loop 0 *.gif example.gif                                                                             
[1]    28901 killed     convert -delay 2 -loop 0 *.gif example.gif

**Comment by mikayla-grace** [comment]
Does this work?

```
$convert -limit memory 2mb -limit map 2mb -delay 2 -loop 0 *.gif example.gif
```

**Comment by crazy-canux** [comment]
Looks yes.
Thanks!
