### ISSUE TITLE
How to disable SetImageGray?

### ISSUE THREAD

**Issue by Xuno** [ImageMagick/ImageMagick#328]
SetImageGray

SetImageGray() returns MagickTrue if all the pixels in the image have the same red, green, and blue intensities and changes the type of the image to bi-level or grayscale.

Can SetImageGray be disabled in the API so batch .tif images are saved in the desired color space?

**Comment by mikayla-grace** [comment]
You can explicitly set the image type to Truecolor to force grayscale TIFF to sRGB.  From the command-line, its -type truecolor.  From the API, well that depends on which API you are using.  For MagickWand, for example, use MagickSetType.

**Comment by Xuno** [comment]
MagickCore::TrueColorType works

Thank you
