### ISSUE TITLE
Problem with stdout output in powershell (Windows).

### ISSUE THREAD

**Issue by kpym** [ImageMagick/ImageMagick#3283]
### Prerequisites

- [ x ] I have written a descriptive issue title
- [ x ] I have verified that I am using the latest version of ImageMagick
- [ x ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When I redirect the pdf output to powershell stdout, the file is significantly different from what is expected. The following two command give the same result in `cmd` and `gitbash`, but in `powershell` the result is significantly different (the size is doubled) and the result is not a valid pdf:
```bash
magick.exe -density 300 bug3.pdf -threshold 77% -type bilevel -compress Group4 bug3im1.pdf
magick.exe -density 300 bug3.pdf -threshold 77% -type bilevel -compress Group4 pdf:- > bug3im2.pdf
```
Using ` | Out-File bug3im2.pdf` in place of `> bug3im2.pdf` do not change the result.

### Steps to Reproduce

The commands are already described in the previous section.

### System Configuration

- ImageMagick version:
```
Version: ImageMagick 7.0.11-1 Q16 x64 2021-02-21 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Visual C++: 192829337
Features: Cipher DPC OpenCL
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zip zlib
```
- Environment (Operating system, version and so on): 
    - Windows 10
    - PowerShell 5.1.19041.610

**Comment by snibgo** [comment]
> (the size is doubled)

Powershell assumes your redirected stdout is text, and makes it into "wide characters", 2 bytes per character, UTF-16. I suppose there is some way to prevent this but I don't use Powershell, and I don't know how.

**Comment by kpym** [comment]
@snibgo You are right. This is not an ImageMagick issue, but a [Power shell issue](https://github.com/PowerShell/PowerShell/issues/1908).
