### ISSUE TITLE
-deskew of black/white 1BPP TIFF file creates 256 grayscale PNG

### ISSUE THREAD

**Issue by 00SS** [ImageMagick/ImageMagick#3284]
### Description
I have a 2 colors (black/white) (1BPP) TIFF file.
Previously (v7.0.7-11-Q16) when I deskewed the file and saved it as a PNG I got a small file size (and the PNG had just 2 colors).
In later versions  I get a much bigger PNG file, in Grayscale, showing it has 256 colours.

This only seems to be happening when using the ```-deskew``` option, but no problem when using many other options.

### Steps to Reproduce
The TIFF file sample can be created with:
```magick logo: -monochrome -depth 1 -compress LZW logo.tif```

Previous version created the correct output:
```"C:\Program Files\ImageMagick-7.0.7-Q16\magick.exe"  logo.tif -deskew 40%  -quality 99 -compress LZW logo-old.png```

New version creates the unexpected output:
```"C:\Program Files\ImageMagick-7.0.11-Q16\magick.exe" logo.tif -deskew 40%  -quality 99 -compress LZW logo-new.png```

### System Configuration
Windows 10

- ImageMagick version: 7.0.11-1 Q16 x64 2021-02-21 
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zip zlib

**Comment by snibgo** [comment]
This seems to be a change in IM. If you want a specific depth in your output, you should specify that, rather than relying on an IM default. You can insert "-depth 1" in your conversion to logo-new.png.

Note that your "-compress LZW" has no effect, as LZW is not a valid compression method for PNG.

**Comment by 00SS** [comment]
I guess I thought there may be a regressive bug because in the newer versions, only the **-deskew** option is changing the PNG color depth. A whole bunch of other command line options are not resulting in this change, including: -background -crop -chop -splice -repage -level -black-threshold -extent"

Anyway, on further reflection, with the newer versions ( some-time after v7.0.7) the result seems to be much better when done in 2 steps instead of directly. Since in v7.0.11 **-deskew** to a TIF output does _not_ increase the number of colours:
```magick logo.tif -deskew 40%  -compress LZW logo-newest.tif```

Then when this TIF is converted to the PNG, the result is much better (and closer to the original):
```"magick logo.tif logo-newest.tif  -quality 99 logo-newest-tif.png```

Changing from the original TIF directly to the PNG with the below line seems to substantially lower the quality of the output image:
```"magick logo.tif -deskew 40% -depth 1 -quality 99 logo-newest-depth-1.png```


Note: My mistake in the initial post. Including the LZW compression for PNG was a copy paste error while formatting here in markdown.

**Comment by snibgo** [comment]
> A whole bunch of other command line options are not resulting in this change, including: -background -crop -chop -splice -repage -level -black-threshold -extent"

When the input is black and white only, none of those operations can create gray pixels (ie increase the number of colours). But a rotation can.

**Comment by fmw42** [comment]
When you resample pixels due to rotations, scaling or distortions, new pixels are created with colors that may not be in the original image. It is like an average of two colors to produce a new color. Other functions, such as 90 deg rotations do not do resampling so no new colors are created. Things like borders and crops may or may not change the number of colors. ImageMagick does not try to guess what the user wants. It leaves it to the user to make most decisions and control the output.

**Comment by 00SS** [comment]
Good information to remember (for me!).
Thanks for taking the time to explain the reasons.

I use ImageMagick to prepare scans of out of print books both for OCR and for presenting as PDF books. Its an amazing program. Invaluable!

A Big Thanks to the whole team who got it to where it is, and who keep polishing and improving it.
