### ISSUE TITLE
Why are you producing invalid PDFs with stream dicts without or illegal Length?

### ISSUE THREAD

**Issue by hhrutter** [ImageMagick/ImageMagick#3286]
https://github.com/pdfcpu/pdfcpu/issues/299

**Comment by kpym** [comment]
@hhrutter As [I said](https://github.com/pdfcpu/pdfcpu/issues/299#issuecomment-783276838) this is not true in the last version of ImageMagick, so no need to be an issue here.

**Comment by hhrutter** [comment]
@kpym ok so please provide me your file based on the latest version so I can verify this and start working on it.
