### ISSUE TITLE
Converting multiple images to PDF creates corrupted pdf title

### ISSUE THREAD

**Issue by BreadyX** [ImageMagick/ImageMagick#3287]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Using `convert` to convert images to a pdf generates one with corrupted metadata: the "Title" attribute cannot be modified (e.g. using postscript with `gs`) and some pdf readers (tested only with evince) outright fail to read the title.

### Steps to Reproduce
1. Convert images to pdf using `convert *.jpg file.pdf`
2. Try to change the title to something different using postscript
    ```sh
    gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=file.pdf -c "[ /Title (My Title goes here) /DOCINFO pdfmark" -f test.pdf
    ```
3. Use `pdfinfo` or something similar to see that the title is stuck to being 'file' or 'None' depending on the program

### System Configuration

- ImageMagick version: 7.0.11-1 (appimage from the downloads page)
- Environment (Operating system, version and so on): Fedora 33 (updated to latest) with Gnome Shell 3.38.3
- Additional information: 
  - Bug also is present in ImageMagick version 6.9.11-27 (from Fedora 33 repos)
  - pdfinfo version 0.90.0 (from Fedora 33 repos)
  - evince version 3.38.2

### Additional info

While searching for other issues I found [this very old post](https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=30405)  on your(?) forum. Could it be related to this?

Also this is not a `gs` bug because changing title works as expected with other pdfs.

**Comment by BreadyX** [comment]
If it can be of any help I ran `convert -debug All ...` one some test jpgs I had and created a pdf. I attached the to this comment the output: [debug.log](https://github.com/ImageMagick/ImageMagick/files/6028824/debug.log).

Here is the information about the generated pdf:
- `pdfinfo`:
  ```
  Title:          test
  Producer:       https://imagemagick.org
  CreationDate:   Tue Feb 23 13:16:17 2021 CET
  ModDate:        Tue Feb 23 13:16:17 2021 CET
  Tagged:         no
  UserProperties: no
  Suspects:       no
  Form:           none
  JavaScript:     no
  Pages:          4
  Encrypted:      no
  Page size:      1668 x 2157 pts
  Page rot:       0
  File size:      2301942 bytes
  Optimized:      no
  PDF version:    1.3
  ```
- evince/nautilus: 
  ![image](https://user-images.githubusercontent.com/37741488/108842996-643d6e80-75da-11eb-9afe-d08a633a0d4a.png)

**Comment by urban-warrior** [comment]
You have yet to prove there is an issue with ImageMagick.  The command:

```
convert *.jpg test.pdf
```
returns a PDF with a title of `/Title <00740065007300740000>`.  `pdfinfo` returns the expected title, `test`.  You then create a new PDF with Ghostscript.  If you have an issues with that PDF, it would be a Ghostscript issue, not ImageMagick.  For it to be an ImageMagick issue, you need to show that `test.pdf ` is not a proper PDF or that the title is not proper.

**Comment by BreadyX** [comment]
You are right, the problem is not at all imagemagick. The problem is that for some reason ghostscript doesn't change metadata, it just adds what whatever: running different pdfmark scripts keeps adding new elements to the outline, but the title (if already present) never changes. 

Sorry for wasting your time with this unrelated issue, I'll close this issue.
