### ISSUE TITLE
Help needed with apveyor

### ISSUE THREAD

**Issue by Izopi4a** [ImageMagick/ImageMagick#329]
Hi guys, 

as you can see https://github.com/phalcon/cphalcon/pull/12493 i am struggling like an idiot

did anyone ever made image magick installed with appveyor, if so can you please help me.

i guess noone here can help me with php imagick, but at least if you could tell me how to install image magick correctly from the console ( if i am doing something wrong )

Thanks

**Comment by dlemstra** [comment]
I don't know if you can run our installer from the command line. You might just want to build IM yourself and create a zip file that you can use in appveyor.

**Comment by Izopi4a** [comment]
seems like .exe /SILENT , /VERYSILENT did the trick 👍
