### ISSUE TITLE
Compose difference/negate completely removes source from destination.

### ISSUE THREAD

**Issue by TheColorRed** [ImageMagick/ImageMagick#3293]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When using the `-compose difference` or `-compose difference`, I seem to be getting the wrong output. Reversing the two image creates the correct filter, but the image size is completely different.

### Steps to Reproduce
[Puppy](https://user-images.githubusercontent.com/1571806/109028560-89d48180-7687-11eb-9b68-1241acf272c8.png)
[Kitten](https://user-images.githubusercontent.com/1571806/109028564-8a6d1800-7687-11eb-8ac4-ef8f47026aa5.jpg)
```
magick puppy.png kitten.jpg -compose difference -composite difference.png
magick puppy.png kitten.jpg -compose negate -composite negate.png
```

It generates this image (Checker background generated by Gimp):

<img src="https://user-images.githubusercontent.com/1571806/109026146-09ad1c80-7685-11eb-9b11-534be1542a44.png" height="400">

However, in a photo editor such as Gimp, that same composition outputs:

<img src="https://user-images.githubusercontent.com/1571806/109026345-44af5000-7685-11eb-86b6-ce77957f3ddb.png" height="400">

This also seems to affect development tools. I am using Magick.NET which is where I originally found this, then tested via the command line.

### System Configuration
```
Windows 10 x64

Version: ImageMagick 7.0.10-62 Q16 x64 2021-02-07 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Visual C++: 192829336
Features: Cipher DPC HDRI OpenCL
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zip zlib
```

**Comment by dlemstra** [comment]
You probably also want to include your original test images?

**Comment by TheColorRed** [comment]
@dlemstra I have updated the main issue under **Steps to Reproduce**.

**Comment by fmw42** [comment]
Image order is important in -composite when doing difference, minus, or divide. The size depends upon the size of the first image in the command line. So you may have to pad one image before doing the composite.

See https://legacy.imagemagick.org/Usage/compose/#compose

**Comment by snibgo** [comment]
> magick puppy.png kitten.jpg -compose negate -composite negate.png

This is not a valid IM command, because "negate" is not a valid compose option.

**Comment by dlemstra** [comment]
Adding `-alpha off` or `-channel rgb` on the command line solves your issue. You probably want to call the `Compose` overload of the `MagickImage` that accepts a channel.

p.s. negate is valid in IM7 @snibgo.

**Comment by TheColorRed** [comment]
Perfect!

`image.Composite(overlay, x, y, blend, Channels.RGB);`
