### ISSUE TITLE
Division by zero in XRedGamma() of MagickCore/xwindow.c

### ISSUE THREAD

**Issue by pcy190** [ImageMagick/ImageMagick#3297]
### Prerequisites

- [√] I have written a descriptive issue title
- [√] I have verified that I am using the latest version of ImageMagick
- [√] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When the `red_gamma` was set to zero, a division by zero error would happen in line 134, `1.0/(double) red_gamma`.

https://github.com/ImageMagick/ImageMagick/blob/f548a590c00313db021a687323ee6eb5f30d1e62/MagickCore/xwindow.c#L133-L135

Notice that `red_gamma` is assigned by `geometry_info.rho`, which could be zero in the process of `ParseGeometry` function.
Once `red_gamma` is set to zero, multiple it will still get zero in line 3209.

https://github.com/ImageMagick/ImageMagick/blob/f548a590c00313db021a687323ee6eb5f30d1e62/MagickCore/xwindow.c#L3201-L3209

By the way, the `XGreenGamma`, `XBlueGamma` macro also have the division by zero problem. I list the code position below:
https://github.com/ImageMagick/ImageMagick/blob/f548a590c00313db021a687323ee6eb5f30d1e62/MagickCore/xwindow.c#L130-L132
https://github.com/ImageMagick/ImageMagick/blob/f548a590c00313db021a687323ee6eb5f30d1e62/MagickCore/xwindow.c#L113-L115

So a crafted file may trigger undefined behavior in the form of division by zero. Maybe there need the `PerceptibleReciprocal()` function to do division.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
