### ISSUE TITLE
-draw "image over..." doesn't work

### ISSUE THREAD

**Issue by Papirosnik** [ImageMagick/ImageMagick#330]
Hello.
I'm using ImageMagick-7.0.4-0-Q16-x64-dll.exe on Windows10 64 bit.

Any example with -draw "image **over**..." (and others: SrcOver, Src, Over, Dst, In and etc, too) doesn't draw image over source one. I'm getting either white rectangle in the desired place, or nothing.
The only way when it works is **Copy** composite operator.
Let's see. This works properly:
 `magick -size 256x64 xc:white -draw "image Copy 0,0 128,64 'side_tex1.png' " out.png`
I can see side_tex1.png in the result out.png.

And this doesn't work:  
`magick -size 256x64 xc:white -draw "image Over 0,0 128,64 'side_tex1.png' " out.png. `
Out.png doesn't contain 'side_tex1.png' image . It's just a white rectangle.

Is this bug related only to this version? (I can't download older binaries 7th version)
Or maybe I do something completely wrong for IM ver.7 ?

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by Papirosnik** [comment]
Thanks for the fix. It works now.
Also, I've noticed that using any attribute in -draw command for 'image' primitive doesn't work.
For example, scale, skewX, rotate (and any other from here: http://www.imagemagick.org/script/command-line-options.php#draw)
works for, let's say, **-draw "rectangle..."** and do nothing for **-draw "image...**";
Should they work for 'image' too?

**Comment by mikayla-grace** [comment]
The image primitive does respond to affine changes but only if the draw compose is Over, for example:

`convert logo: -draw 'rotate 45 image Over 100,100 225,225 image.jpg' x:`
