### ISSUE TITLE
mogrify It seems does not works as expected

### ISSUE THREAD

**Issue by gcatnine** [ImageMagick/ImageMagick#3300]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I would like to convert all tiff files in a forder to jpeg
in the folder all files have the sufix as .tif

Here the command I use
magick mogrify -format tif *.jpg
and I got this response
zsh: no matches found: *.jpg

### System Configuration

- ImageMagick version: ImageMagick 7.0.11-1 Q16 x86_64 2021-02-21
- Environment (Operating system, version and so on): MacOS Cataline 10.15.7
- Additional information:

**Comment by fmw42** [comment]
You have the syntax reversed. If you want to convert all tiff files to jpg, then

`magick mogrify -format jpg *.tiff`

The *.tiff identifies the input files to be processed and -format jpg identifies the desired format for the output.

**Comment by gcatnine** [comment]
I'm stupid. Many thanks for your help
