### ISSUE TITLE
display > /dev/null < /dev/null does not work

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#331]
Hi,

You should check if argc is 1 and run the default display menu with logo.

display without command line means I want to run the display gui

**Comment by bastien-roucaries** [comment]
it is debian bug 816300

**Comment by bastien-roucaries** [comment]
Does it fail now cat somefile.png | display ? 
It supposed in the documentation to write cat file.png | display -

If you think it is a regression may be you should add a new option -nostdin.

Recent freedesktop comptaible run desktop file with /dev/null as stdin so running with no stdin is needed.
Command line of desktop file is
 display %F
with %F the list to file passed by interface or nothing if directly running the desktop file

**Comment by bastien-roucaries** [comment]
Yes it break previous behavior...

**Comment by mikayla-grace** [comment]
We reverted the patch.  Our recommendation is this command:

```
display logo: < /dev/null > /dev/null
```

**Comment by bastien-roucaries** [comment]
Ok this patch work for me like a charm
[0001-Add-a-new-option.txt](https://github.com/ImageMagick/ImageMagick/files/679667/0001-Add-a-new-option.txt)

**Comment by bastien-roucaries** [comment]
Ping could you merge this option ?

**Comment by mikayla-grace** [comment]
Why yes we can.

**Comment by bastien-roucaries** [comment]
Thanks it is needed for modern .desktop file
