### ISSUE TITLE
SSIM metric returns wrong value

### ISSUE THREAD

**Issue by ueda-san** [ImageMagick/ImageMagick#3315]
### Prerequisites

- [ x] I have written a descriptive issue title
- [ x] I have verified that I am using the latest version of ImageMagick
- [ x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
SSIM metric returns wrong value.
The easiest to reproduce is when comparing the same images. 

### Steps to Reproduce
compare same image with -metric SSIM option
```
$ magick compare -metric SSIM a.png a.png diff
0.33003
```

before 8b6d407cef98c0173718f25d8f76e07e5fd49a44 looks like OK
```
$ magick compare -metric SSIM a.png a.png diff
1
```

### System Configuration
Windows binary:
Version: ImageMagick 7.0.11-1 Q16 x64 2021-02-21

from source (Ubuntu 20.10 on WSL)
Version: ImageMagick 7.0.11-2 Q16 x86_64 2021-02-21

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
