### ISSUE TITLE
Division by zero in ConvertLuvToXYZ() of MagickCore/gem-private.h

### ISSUE THREAD

**Issue by wuruoyu** [ImageMagick/ImageMagick#3317]
### Prerequisites

- [√] I have written a descriptive issue title
- [√] I have verified that I am using the latest version of ImageMagick
- [√] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
A division-by-zero exception can happen in function `ConvertLuvToXYZ()` when the arguments `L` and `u` are zero

https://github.com/ImageMagick/ImageMagick/blob/f548a590c00313db021a687323ee6eb5f30d1e62/MagickCore/gem-private.h#L154-L172

One of the functions calls `ConvertLuvToXYZ()` is `ConvertLCHuvToXYZ()`, which is shown below. To make its first two arguments zero, an attacker can set `luma = 0`, `chroma = 0`. 

https://github.com/ImageMagick/ImageMagick/blob/f548a590c00313db021a687323ee6eb5f30d1e62/MagickCore/gem.c#L797-L802

An API `ConvertLCHuvToRGB()` calls `ConvertLCHuvToXYZ()`, which does not do any sanity check. `ConvertLCHuvToRGB(0, 0.5, ......)` can trigger the division by zero exception, which can be achieved with a crafted file. 

https://github.com/ImageMagick/ImageMagick/blob/f548a590c00313db021a687323ee6eb5f30d1e62/MagickCore/gem.c#L804-L820

Thank you in advance! Let me know if you have any question.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
