### ISSUE TITLE
imagemagick-6.q16: convert generates monochrome images with inverted colors (black and white)

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#332]
Could you get a glimpse at

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=849507

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
