### ISSUE TITLE
Division by zero in ConvertRGBToHSV() of MagickCore/gem.c

### ISSUE THREAD

**Issue by wuruoyu** [ImageMagick/ImageMagick#3320]
### Prerequisites

- [√] I have written a descriptive issue title
- [√] I have verified that I am using the latest version of ImageMagick
- [√] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
A division-by-zero exception can happen in function ConvertRGBToHSV() when the arguments `red = 0`, `green = 0`, `blue = -1`. 
https://github.com/ImageMagick/ImageMagick/blob/a39f313294df8c1bfa9b56cbf77a89737f350a81/MagickCore/gem.c#L1171-L1210

This function assumes that the arguments are non-positive, which is not true. With arguments `red = 0`, `green = 0`, `blue = -1`, we will have `max = 0`, `min = -1` and `c = 1`. So it will not return at line 1191 - 1196. And it will reach line 1209 and cause a division-by-zero exception. 

Thank you in advance! Let me know if you have any questions.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
