### ISSUE TITLE
xwd writer sets 0, 0, 0 as r, g, b mask instead of the correct values

### ISSUE THREAD

**Issue by scrouthtv** [ImageMagick/ImageMagick#3324]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The `xwd` (x window dump) file format consists of a header and the image as a table of colored pixels.
In the header, there are 3 uint32 values located at offsets 56, 60, 64 (big endian) which correspond to the [r, g, b channel masks](https://en.wikipedia.org/wiki/XImage). If you create a new xwd file with either `xwd` directly or gimp (I haven't tried anything else yet), these values might be set to
```
0b111111110000000000000000 = 16711680
0b000000001111111100000000 = 65280
0b000000000000000011111111 = 255
```
Which makes sense as each channel would have 8 bits.

However, when writing the file with Image Magick, all three masks are set to 0.

### Steps to Reproduce
1. Get an image in any format (let's call it `bad.png`)
2. Convert it to `xwd` using magick:
```
 ~ magick convert bad.png bad.xwd
 ~ file bad.xwd
bad.xwd: XWD X Window Dump image data, "xwdump", 484x316x8
```
No errors have been reported. Even displaying this file might work fine in image viewers that have these masks hardcoded. Now create an `xwd` file that follows the specification, e. g. by creating one using `xwd`:
```
 ~ xwd -root > good.xwd
 ~ file good.xwd
good.xwd: XWD X Window Dump image data, "xwdump", 1920x1080x24
```

If you compare the mask values of both files:
```
 ~ od -t d4 good.xwd --endian=big -j 56 -N $((3*4))
0000070    16711680       65280         255
 ~ od -t d4 bad.xwd --endian=big -j 56 -N $((3*4))
0000070           0           0           0
```
Note how the image created by magick sets all three channels to 0.

This happens only for some files (e. g. if I convert an `xwd` to `png` and back to `xwd` all using magick, it sometimes does not happen). Here's the png file that I used as `bad.png`:
![bad](https://user-images.githubusercontent.com/23227405/109415885-932d5900-79bb-11eb-93ec-d3c701872228.png)

### System Configuration

- ImageMagick version: `imagemagick 7.0.11.1-1`
- Environment (Operating system, version and so on):
```
linux 5.11.1.arch1-1
mesa 20.3.4-3
Linux archblack 5.11.1-arch1-1 #1 SMP PREEMPT Tue, 23 Feb 2021 14:05:30 +0000 x86_64 GNU/Linux
```
- Additional information: I'm running an Intel i5-3570 with no gpu.

**Comment by urban-warrior** [comment]
The masks are non-zero if the image is not colormapped.  Try adding `-type truecolor` to your command-line to force a non-colormapped image which will return the masks you expect.

**Comment by scrouthtv** [comment]
Can confirm. Sorry, my bad.
