### ISSUE TITLE
Issues with building ImageMagick-7.0.11-2 source code for Windows.

### ISSUE THREAD

**Issue by pprasanthk** [ImageMagick/ImageMagick#3325]
### Prerequisites
- [YES ] I have written a descriptive issue title
- [ YES] I have verified that I am using the latest version of ImageMagick
- [ YES] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Issues with building ImageMagick-7.0.11-2 source code for Windows for Q-8 Quantum depth for both 32-bit and 64-bit.

### Steps to Reproduce
We have downloaded the ImageMagick-7.0.11-2 source from the below location: 
    https://download.imagemagick.org/ImageMagick/download/windows/ImageMagick-7.0.11-2.zip
We have unzipped the above code, opened Visual Studio 2017 and opened configure.sln inside ImageMagick-7.0.11/VisualMagick/configure folder. We then right clicked on the configure.sln solution and retargeted to Windows SDK version to 10.0.177630.0. 
We then ensured that the Solution Configuration is set to Release, and Solution Platforms is set to Win32 and rebuilt the entire solution, and we are could build this project successfully. 
After that, we ran the above built configure.exe, just changed the Quantum depth as Q8 (all others options in the UI are not changed) and completed the process, which generated the VisualDynamicMT.sln file.

We then opened the above generated VisualDynamicMT.sln file, right clicked on the solution and retargeted to Windows SDK version to 10.0.177630.0, ensured that the Solution Configuration is set to Release, and Solution Platforms is set to Win32 and rebuilt the entire solution. 
We got the following compilation errors inside \7.0.11-2\Source\ImageMagick-7.0.11-2\ImageMagick-
Windows\libheif\libheif\heif_encoder_aom.cc

 **1>heif_encoder_aom.cc
1>c:\users\it\desktop\im_upgrade\7.0.11-2\source\imagemagick-7.0.11-2\imagemagick-windows\libheif\libheif\heif_encoder_aom.cc(522): error C2039: 'max': is not a member of 'std'
2>ma.cc
1>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\set(18): note: see declaration of 'std'
1>c:\users\it\desktop\im_upgrade\7.0.11-2\source\imagemagick-7.0.11-2\imagemagick-windows\libheif\libheif\heif_encoder_aom.cc(522): error C3861: 'max': identifier not found
1>c:\users\it\desktop\im_upgrade\7.0.11-2\source\imagemagick-7.0.11-2\imagemagick-windows\libheif\libheif\heif_encoder_aom.cc(523): error C2039: 'max': is not a member of 'std'
1>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.16.27023\include\set(18): note: see declaration of 'std'
1>c:\users\it\desktop\im_upgrade\7.0.11-2\source\imagemagick-7.0.11-2\imagemagick-windows\libheif\libheif\heif_encoder_aom.cc(523): error C3861: 'max': identifier not found
1>Done building project "CORE_libheif_DynamicMT.vcxproj" -- FAILED.**

To fix this we had to add **#include <algorithm>**  at the top of the above heif_encoder_aom.cc. 

Could you please fix this in your code or let me know if I am doing anything wrong here?

We also tried to generate the 64-bit flavor of VisualDynamicMT.sln, by running configure.exe and selecting Quantum depth as Q8 and also enabling the "Build 64-bit  distribution" option (all other options except these two are not changed to generate the VisualDynamicMT.sln).
We then opened the generated VisualDynamicMT.sln, ensured the entire solution is targeted to the above Windows SDK 10.0.177630.0, ensured that the Solution Configuration is set to Release, and Solution Platforms is set to X64 and rebuilt the entire solution. 
Apart from the above compilation errors that we got while building for x86 Windows platform, we also got the following compilation error: 

**1>ma.cc
1>Disabling AVX2/3 due to known issues with MSVC/32-bit builds
1>c:\users\it\desktop\im_upgrade\7.0.11-2\source\imagemagick-7.0.11-2\imagemagick-windows\jpeg-xl\lib\jxl\modular\encoding\ma.cc(579): error C2398: Element '1': conversion from 'const size_t' to '_Ty' requires a narrowing conversion** 

To fix this problem, we had to add a **type cast (uint32_t) to the constexpr kWPProp @ line# 579** inside the above file mac.cc. Could you please fix this in your code or let me know if I am doing anything wrong here?

Could you please fix the above two issues in your code or let me know if I am doing anything wrong here?

### System Configuration
 Windows 10, both 32-bit and 64-bit

- ImageMagick version: 7.0.11-2
- Environment (Operating system, version and so on): Windows 10, both 32-bit and 64-bit
- Additional information:

**Comment by dlemstra** [comment]
Building with Visual Studio 2017 is not possible with the current release. In the next release the jpeg-xl libaries will be excluded when you use VS2017. And the libheif library is failing due to a missing include. If you want to build the current release with VS2017 I would advise you to do the following:

- Apply this patch: https://github.com/strukturag/libheif/pull/455 (we will wait for a new libheif release before changing our local repository)
- Remove the following folders in the VisualMagick directory: brotli, highway, jpeg-xl.

**Comment by pprasanthk** [comment]
Hi, 

Could you please let us know the version of Visual Studio we can use to build this  version of ImageMagick? Is VS 2013 be okay?

--
Thanks
Prasanth

**Comment by pprasanthk** [comment]
Hi, 

The above patch says that it applies the missing include to fix the **std::max** compilation error. Could you please let me know if compiling the 7.0.11-2 source code with VS 2015 fixes the other issues that are occurring with x64 version of the build (without removing the folders  **brotli, highway, jpeg-xl** from VisualMagick directory)? 

In case of compiling with VS 2017, could you please let me know if removing the folders **brotli, highway, jpeg-xl** from VisualMagick directory would not lead to any missing features?

--
Thanks
Prasanth

**Comment by dlemstra** [comment]
You will need to remove the  brotli, highway, jpeg-xl folders because the jpeg-xl library needs VS2019. The only feature that you will be missing is support for JXL (jpeg-xl).

**Comment by pprasanthk** [comment]
Hi, 

We are able to successfully build the ImageMagick source code using Visual Studio 2019, without any changes to the source code. Thanks for all the help.

--
Thanks
Prasanth
