### ISSUE TITLE
convert fails to interpret STDIN data

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#333]
Could you get a glimpse at https://bugs.debian.org/848849 ?

**Comment by mikayla-grace** [comment]
Try ```xwd -root | convert xwd:- /tmp/foo.png```.    The XWD signature is only 3 characters which increases the chances for a false positive, therefore an explicit format is required for STDIN.

**Comment by bastien-roucaries** [comment]
Ok so won't fix
