### ISSUE TITLE
Division by zero in DistortImage() of MagickCore/distort.c

### ISSUE THREAD

**Issue by wuruoyu** [ImageMagick/ImageMagick#3331]
### Prerequisites

- [√] I have written a descriptive issue title
- [√] I have verified that I am using the latest version of ImageMagick
- [√] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
A division-by-zero exception can happen at the line 1971 in function DistortImage() when `method = DepolarDistortion`, `arguments[0] = 1`, `arguments[1] = 0`, `arguments[4] = 180 / pi`, `arguments[5] = 0`.

https://github.com/ImageMagick/ImageMagick/blob/4ab6c708538b5f73ddb309b07be5c2bcc0ca8494/MagickCore/distort.c#L1968-L1971

Argument `arguments` of `DistortImage()` are sanitized and assigned to `coeff` in function `GenerateCoefficients()`, in the code shown below:

https://github.com/ImageMagick/ImageMagick/blob/4ab6c708538b5f73ddb309b07be5c2bcc0ca8494/MagickCore/distort.c#L1252-L1343

When `arguments[0] = 1`, `arguments[1] = 0`, `arguments[4] = 180 / pi`, `arguments[5] = 0`, `GenerateCoefficients()` will give `coeff[0] = 1`, `coeff[1] = 0`, `coeff[4] = 1`, `coeff[5] = 0`. And as shown in the code below, it will let `(coeff[0]-coeff[1])*(coeff[5]-coeff[4])*0.5 = -0.5`, and thus `(size_t) ceil((coeff[0]-coeff[1])*(coeff[5]-coeff[4])*0.5 = 0`. and trigger the division-by-zero exception at line 1971.  

https://github.com/ImageMagick/ImageMagick/blob/4ab6c708538b5f73ddb309b07be5c2bcc0ca8494/MagickCore/distort.c#L1968-L1971

Thank you in advance! Let me know if you have any questions.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
