### ISSUE TITLE
Division by zero in ApplyFunction() of MagickCore/statistic.c

### ISSUE THREAD

**Issue by wuruoyu** [ImageMagick/ImageMagick#3332]
### Prerequisites

- [√] I have written a descriptive issue title
- [√] I have verified that I am using the latest version of ImageMagick
- [√] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
A division-by-zero exception can happen in function ApplyFunction() when the arguments `function = ArcsinFunction` and `parameters[0] = 0`. Please refer to the code below:

https://github.com/ImageMagick/ImageMagick/blob/ce7b0f29a08d75c71ef0429ebfd064f895a7cd2c/MagickCore/statistic.c#L1031-L1035

`ApplyFunction()` is called in `FunctionImage()`, which is an API function. Before calling `ApplyFunction()`, no sanity check is imposed. So an attacker can call `FunctionImage()` with `function = ArcsinFunction` and `parameters[0] = 0` to trigger this exception. 

https://github.com/ImageMagick/ImageMagick/blob/ce7b0f29a08d75c71ef0429ebfd064f895a7cd2c/MagickCore/statistic.c#L1139

Thank you in advance! Let me know if you have any questions.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
