### ISSUE TITLE
Division by zero in XFileBrowserWidget() of MagickCore/widget.c

### ISSUE THREAD

**Issue by wuruoyu** [ImageMagick/ImageMagick#3334]
### Prerequisites

- [√] I have written a descriptive issue title
- [√] I have verified that I am using the latest version of ImageMagick
- [√] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Similar to https://github.com/ImageMagick/ImageMagick/issues/3333, a division-by-zero exception can happen in function XFileBrowserWidget() at line 4472 when `windows->widget.font_info->ascent = 0` and `windows->widget.font_info->descent = 0`. 
Below is the code that the division-by-zero exception can happen. 
https://github.com/ImageMagick/ImageMagick/blob/ce7b0f29a08d75c71ef0429ebfd064f895a7cd2c/MagickCore/widget.c#L4472

`height` is defined in the code below:
https://github.com/ImageMagick/ImageMagick/blob/ce7b0f29a08d75c71ef0429ebfd064f895a7cd2c/MagickCore/widget.c#L4333

`windows->widget.font_info->ascent` and `windows->widget.font_info->descent` are controller by the user since `XFileBrowserWidget()` is an API function, and there is no sanity check in between.

Thank you in advance! Let me know if you have any questions.

**Comment by urban-warrior** [comment]
hanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
