### ISSUE TITLE
Division by zero in DrawGradientImage() of MagickCore/draw.c

### ISSUE THREAD

**Issue by wuruoyu** [ImageMagick/ImageMagick#3338]
### Prerequisites

- [√] I have written a descriptive issue title
- [√] I have verified that I am using the latest version of ImageMagick
- [√] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
A division-by-zero exception can happen in function DrawGradientImage() at line 2187 when `draw_info->gradient->radius = 0` and `draw_info->gradient->spread = RepeatSpread`, which are controlled by user/attacker. 

https://github.com/ImageMagick/ImageMagick/blob/ce7b0f29a08d75c71ef0429ebfd064f895a7cd2c/MagickCore/draw.c#L2187

Thank you in advance! Let me know if you have any questions.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
