### ISSUE TITLE
Font integer overflow

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#334]
Could you get a glimpse at https://bugs.debian.org/814836

**Comment by mikayla-grace** [comment]
Unfortunately we cannot reproduce this problem under CentOS 7, Fedora, or Windows.  We get

```
convert -debug annotate -pointsize 72 -font ./RNS.ttf label:g null:
  Font ./RNS.ttf; font-encoding none; text-encoding none; pointsize 72
2016-12-28T21:05:40-05:00 0:00.040 0.000u 7.0.4 Annotate convert[32051]: annotate.c/GetTypeMetrics/851/Annotate
  Metrics: text: g; width: 38; height: 103; ascent: 70; descent: -31; max advance: 61; bounds: 0.4375,-0.140625  35,54.0781; origin: 36.2812,0; pixels per em: 72,72; underline position: -1.5625; underline thickness: 0.78125
```

Which is expected results.

**Comment by dlemstra** [comment]
Can you help us reproduce this @bastien-roucaries?

**Comment by bastien-roucaries** [comment]
Will try

**Comment by dlemstra** [comment]
@bastien-roucaries It looks like this issue is still open in the debian bug tracker. Can you help us reproduce this issue?

**Comment by urban-warrior** [comment]
Unfortunately, we cannot reproduce this problem.  With the provided command, we get reasonable and expected results for the font metrics.
