### ISSUE TITLE
Drawing artifacts when using multiple layers

### ISSUE THREAD

**Issue by hypertextjay** [ImageMagick/ImageMagick#3344]
### Description
I am trying to add a border to an image with the following:
`magick convert -page +0+0 cat.png -page -20-20 -size 640x541 xc:none -fill none -stroke red -strokewidth 20 -draw 'rectangle 0,0 640,541' -background none -layers merge +repage out.png`
which results in:
![out](https://user-images.githubusercontent.com/52509092/109856775-b8fe6c00-7c0e-11eb-909a-509a2abbbd23.png)
Notice the double border on the top/left sides. I've tried variants with `-layers flatten` and positive offsets but the double-border is still present. I know there are other ways to add a border but I thought this seemed like a bug.

### System Configuration
- ImageMagick version: 7.0.11-1 Q16 x86_64 2021-02-15
- Environment (Operating system, version and so on): Linux/Ubuntu

**Comment by fmw42** [comment]
You are drawing on both your cat image and your xc:none image. You should merge before drawing. Also in ImageMagick 7, use magick not magick convert.

**Comment by hypertextjay** [comment]
Rookie-mistake on my part. Adding parens around the draw command gave me the results I was looking for:
`magick convert -page +0+0 cat.png -page -20-20 \( -size 640x541 xc:none -fill none -stroke red -strokewidth 20 -draw 'rectangle 0,0 640,541' \) -background none -layers merge +repage out.png`. Reason I'm doing it this roundabout-way is because it is part of a larger system which takes in a variable amount of "layers" and merges things together.

On a different note, I tried following your advice by using `magick` instead of `magick convert`, but they produce different results. Here is the result (seemingly incorrect) using just `magick`:
![out](https://user-images.githubusercontent.com/52509092/109863308-590bc380-7c16-11eb-8f52-ecfb0c77970c.png)
It seems my page offsets are being ignored. Maybe this is a proper bug and not my ignorance.

**Comment by snibgo** [comment]
> It seems my page offsets are being ignored. Maybe this is a proper bug and not my ignorance.

If you provide your input cat.png, we can test.

**Comment by fmw42** [comment]
In IM 7, you need to put your page offsets and the images in parentheses together. Try (also remove convert)

`magick \( -page +0+0 cat.png \) \( -page -20-20 -size 640x541 xc:none -fill none -stroke red -strokewidth 20 -draw 'rectangle 0,0 640,541' \) ...`

**Comment by hypertextjay** [comment]
Adding those parentheses did the trick (works without `convert`). Thanks for the help!
