### ISSUE TITLE
Forcing 256 colors in black and white grayscale picture

### ISSUE THREAD

**Issue by AndroYD84** [ImageMagick/ImageMagick#3348]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I run this command:
`magick input.png -set colorspace:auto-grayscale true -colors 256 -colorspace Gray -type Grayscale -fill "#FFFFFF" +opaque "#000000" PNG:output-1.png`
I'm expecting it to generate a 8-bit Gray **256c** picture rather than a 8-bit Gray **2c** picture as it's doing

### Steps to Reproduce
You can reproduce the problem by [downloading this file](https://github.com/AndroYD84/Files/raw/master/IMproblem1/input.png).
Run:
`magick input.png -set colorspace:auto-grayscale true -colors 256 -colorspace Gray -type Grayscale -fill "#FFFFFF" +opaque "#000000" PNG:output-1.png`
Then compare `magick identify output-1.png` and `magick identify input.png` outputs.
You'll have (1) output-1.png PNG 533x800 533x800+0+0 8-bit Gray **2c** 2207B 0.000u 0:00.000 (2) input.png PNG 533x800 533x800+0+0 8-bit Gray **256c** 4231B 0.000u 0:00.000
They are supposed to be both **256c** but output-1.png is **2c**.

I verified that this doesn't happen with other software such as XnViewMP: Replace color (1,1,1 to 255,255,255) + Change color depth (Greyscale: 256) => magick identify [output-2.png](https://github.com/AndroYD84/Files/raw/master/IMproblem1/output-2.png) => [output-2.png](https://github.com/AndroYD84/Files/raw/master/IMproblem1/output-2.png) PNG 533x800 533x800+0+0 8-bit Gray **256c** 4346B 0.000u 0:00.000
And Photoshop => magick identify [output-3.png](https://github.com/AndroYD84/Files/raw/master/IMproblem1/output-3.png) => [input-3.png](https://github.com/AndroYD84/Files/raw/master/IMproblem1/output-3.png) PNG 533x800 533x800+0+0 8-bit Gray **256c** 5655B 0.000u 0:00.000

I believe it's overriding my rule because it's generally not an optimal solution to have 256 colors when I'm using only 2 (What a waste of space, right? I know it, I got very good reasons to want it that way). Afterall, isn't customization/control to the finest details what makes command line tools more appealing to their dumber GUI counterparts?

### System Configuration
- ImageMagick version: ImageMagick 7.0.10-9 Q16 x64 2020-04-26
- Environment (Operating system, version and so on): Windows 10 Version 10.0.19042 Build 19042

**Comment by snibgo** [comment]
Your input file "input.png" has only two colours. None of your operations increases the number of colours. So the output has only two colours.

IM tries to use a space-efficient PNG format, in this case "bilevel". You could use the prefix "PNG24:" if you want, or "PNG00:" which tries to use the same format as the input:
```
f:\web\im>%IMG7%magick input4.png -set colorspace:auto-grayscale true -colors 256 -colorspace Gray -type Grayscale -fill "#FFFFFF" +opaque "#000000" PNG00:x.png

f:\web\im>%IMG7%magick x.png info:
x.png PNG 533x800 533x800+0+0 8-bit Gray 256c 4509B 0.094u 0:00.026
```

**Comment by AndroYD84** [comment]
In my experience the "PNG24" rule would always generate a RGB picture no matter how hard you try to brute force it to be grayscale, also "PNG8" would do the same in my specific case for whatever reason. In the end "PNG00" is what did the trick, I got a 8-bit Gray 256c this time, thank you so much!

**Comment by AndroYD84** [comment]
I'm reopening this issue because the problem is more serious than I thought, it's really bad that IM chooses to use a space-efficient PNG format against your will as that's not always a desirable behavior, sometimes I require to follow very specific standards, the "PNG00" workaround can only work when the original picture is already in 8-bit Gray 256c, but what if my picture is 8-bit sRGB?
To reproduce the problem [download this picture](https://raw.githubusercontent.com/AndroYD84/Files/master/IMproblem1/inputrgb.png) and run:
`magick inputrgb.png -fill "#FFFFFF" +opaque "#45065A" -fill "#000000" -opaque "#45065A" -colors 256 -colorspace Gray -type Grayscale PNG:outputrgb-1.png`
`magick identify outputrgb-1.png`
The output is in **8-bit Gray 2c** even thought I asked for **8-bit Gray 256c**
I get even worse results when using the options "PNG8:" or "PNG24:" as it will save the picture in 8-bit sRGB in both cases, **this is completely unasked for and definitely a bug.**
Please allow us to make the choice when we don't want IM to tamper with our decisions because according to it "it's not the best solution".

**Comment by fmw42** [comment]
Try adding -colorspace gray with PNG8:

**Comment by AndroYD84** [comment]
> 
> 
> Try adding -colorspace gray with PNG8:

I already did, it returns a 8-bit sRGB 2c picture instead of grayscale, the same happens with PNG24, I believe it's a bug.

**Comment by fmw42** [comment]
Try also -type grayscale

**Comment by AndroYD84** [comment]
Using "-define png:color-type=0" and "PNG24:" did the trick! I'm finally generating a **8-bit Gray 256c** picture! Thank you so much you're a lifesaver! Closing issue for now.
