### ISSUE TITLE
imagemagick: Nested <SVG> tag: wrong rendering - wrong positioning

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#335]
Could you get glimpse at htttps://bugs.debian.org/793982

It is low priority

**Comment by mikayla-grace** [comment]
ImageMagick has three different renders: 1) the MSVG internal rendered; 2) The librsvg delegate library; or 3) the inkscape delegate program.  We use inkscape 0.92pre3 and it returns expected results:

```
> convert -verbose test.svg null:
'inkscape' '/home/cristy/magick-23695KsI3JcRN8CES' --export-png='/tmp/magick-2369567LkG68rGynJ' --export-dpi='90,90' --export-background='rgb(100%,100%,100%)' --export-background-opacity='1' > '/tmp/magick-23695H7FyXZLYHv6z' 2>&1
/tmp/magick-2369567LkG68rGynJ PNG 188x94 188x94+0+0 8-bit sRGB 411B 0.020u 0:00.020
test.svg=>/tmp/magick-2369567LkG68rGynJ PNG 188x94 188x94+0+0 8-bit sRGB 411B 0.020u 0:00.019
test.svg=> PNG 188x94 188x94+0+0 8-bit sRGB 411B 0.020u 0:00.020
```

The internal renderer is less robust and does not render properly:

```
convert msvg:test.svg test.png
```

We did not test the libRSVG delegate library.

**Comment by bastien-roucaries** [comment]
Yes it is the internal one

**Comment by bastien-roucaries** [comment]
Ping

**Comment by mikayla-grace** [comment]
We recommend the libRSVG delegate library or inkscape delegate program as the preferred SVG renderer.  The internal renderer is less robust and likely will never support all of the SVG standard.
