### ISSUE TITLE
regression  display -loop option not working/missing

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#336]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793629

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
