### ISSUE TITLE
Cannot read partial Targa files

### ISSUE THREAD

**Issue by absolutelynothinghere** [ImageMagick/ImageMagick#3364]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.10.60

### Operating system

Linux

### Operating system, version and so on

Void Linux x86_64

### Description

I'm using a raytracer (3D software) that can render a limited portion of an image into a TGA file. Said file cannot be read by ImageMagick, giving this error: ``convert: unable to read image data `/home/bob/temp.tga' @ error/tga.c/ReadTGAImage/511.``  
The file can be read by GIMP however.

### Steps to Reproduce

Using the files in the attached `targa.zip`:

1. Run `convert temp.tga output.png`, and you'll get this error: ``convert: unable to read image data `/home/bob/temp.tga' @ error/tga.c/ReadTGAImage/511.``
2. Open `temp.tga` in GIMP, and you'll notice it looks like `temp.png`

[targa.zip](https://github.com/ImageMagick/ImageMagick/files/6095609/targa.zip)

**Comment by urban-warrior** [comment]
Reading a malformed image that does not meet the image format specification is not permitted in ImageMagick.  It is considered a possible security vulnerability since it can introduce undefined behavior or data.

**Comment by absolutelynothinghere** [comment]
Thanks for the tip. Looking into the raytracer docs and the hex representation of the image I found that non rendered pixels are already populated with black, however the resulting image has less height than what is written in the header. For example if the raytracer is rendering an area that is 50 pixels high of an image that is 100 pixels high in full, the targa header will report a height of 100 pixels, but the image data itself fills up to 50 pixels only. Note that the width is correct.

```
temp.tga header (original, incorrect):
                                          ↓↓ ↓↓
00 00 02 00 00 00 00 00 00 00 EF 00 80 02 E0 01 18

temp.tga header (corrected):
                                          ↓↓ ↓↓
00 00 02 00 00 00 00 00 00 00 00 00 80 02 7A 00 18
```

Is there any way to make ImageMagick attempt to recover such a file, by displaying data up to the EOF and automatically padding the rest with black?

**Comment by urban-warrior** [comment]
Sure we could pad the rest with black-- but we won't.  One of the primary goals of ImageMagick is to be secure which means to avoid any situation which might return undefined behavior or data.  The only compromise is that you can have the raytracer pipe the output to ImageMagick on stdin.  ImageMagick will wait until the entire image is available before it completes the command-line.  That's likely not what you want.  If so, we again recommend using some other utility that is less rigorous about security.

**Comment by snibgo** [comment]
Gimp v2.10 can read the bad file temp.tga, and can save the result as a PNG or whatever you want. Gimp can be driven from the command line.

As urban-warrior points out, ImageMagick doesn't process files that don't conform to relevant standards. One reason is security. Another reason is that trying to make images from bad files is difficult, and impossible to be consistent, and impossible to satisfy all users. IM would need to guess what is wrong with the file, and guess what the file should contain instead.

I'll add another reason: developers should not be encouraged to write image files that do not conform to standards.

**Comment by absolutelynothinghere** [comment]
Running GIMP from the command line looks promising, I didn't even know that was possible. Thank you urban-warrior and snibgo. ☺
