### ISSUE TITLE
TMP variables are not honored

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#337]
Hi,

Could you get a glimpse at: 

https://bugs.debian.org/791460

please be cautious they are security implication here

**Comment by mikayla-grace** [comment]
We increased the precedence of the TMPDIR environment variable.  In the mean-time, use the MAGICK_TEMPORARY_PATH or MAGICK_TMPDIR environment variables to set the temporary path.

**Comment by bastien-roucaries** [comment]
Do you have a référence to commit?

Le 29 décembre 2016 01:48:50 GMT+01:00, mikayla-grace <notifications@github.com> a écrit :
>We increased the precedence of the TMPDIR environment variable.  In the
>mean-time, use the MAGICK_TEMPORARY_PATH or MAGICK_TMPDIR environment
>variables to set the temporary path.

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by dlemstra** [comment]
The reference to this commit is right below his post?

**Comment by bastien-roucaries** [comment]
Yes missed thank
