### ISSUE TITLE
[jxl] decoding error if quality > 91

### ISSUE THREAD

**Issue by cocoon** [ImageMagick/ImageMagick#3375]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-3 Q16 x64 2021-03-06

### Operating system

Windows

### Operating system, version and so on

Windows 10 20H2

### Description

ImageMagick fails to decode jpeg-xl images if encoded with cjxl.exe with quality greater than 91
or encoded with ImageMagick if quality is 100

### Steps to Reproduce

1. encode an png image with imagemagick or cjxl to jxl with quality 100
```magick convert -quality 100 2021-03-test1.png 2021-03-test6.jxl```
or
```cjxl.exe 2021-03-test1.png 2021-03-test6.jxl -s 3 -q 92```

2. try to decode with imagemagick
```magick convert 2021-03-test6.jxl 2021-03-test6.png```

Error message: ```convert: InsufficientImageDataInFile `2021-03-test5.jxl' @ error/jxl.c/ReadJXLImage/259.```

https://github.com/ImageMagick/ImageMagick/blob/main/coders/jxl.c#L259

**Comment by dlemstra** [comment]
Can you decode the image with `djxl` (if that is the decoder name)?

**Comment by cocoon** [comment]
Yes I can decode with djxl.

And I just saw that it is not always exactly at QUality 92, sometimes it starts to fail with higher numbers.
With the attached b500.png it starts to fail for me with Quality 97.
[b500.zip](https://github.com/ImageMagick/ImageMagick/files/6101845/b500.zip)


But I have an old ImageMagick v7.0.10-54 in ImageGlass with Magick.NET-Q16-OpenMP-x64.7.22.3 where it still is able to decode it and display it:

https://github.com/cocoon/ImageGlass/commits/featureJPEG-XL
Versions: https://github.com/cocoon/ImageGlass/commit/1d0051ffda6298ddea1f2793ae1846462f6a5178

**Comment by nar2634** [comment]
I can also reproduce the problem with lossless JPEG transcoded JXL (i.e. `cjxl image.jpg image.jxl` and seeing `JPEG, lossless transcode` in command output).

For lossless JXL converted from PNG (i.e. `cjxl -d 0 image.png image.jxl`), many of them also fail with `InsufficientImageDataInFile`.

**Comment by dlemstra** [comment]
Upgrading to version `0.3.3` did not solve the issue. Can you decode that lossless encoded image with `djxl` @nar2634? And is it only ImageMagick that cannot decode it?

**Comment by dlemstra** [comment]
Well this looks like a bug in the jpeg-xl library. When we provide the input data in blocks it fails but when we provide all the data at once the input can be decoded. Will need to investigate this.

**Comment by nar2634** [comment]
I can decode all lossless encoded images with `djxl`.
ImageMagick fails to decode most of them, throwing `InsufficientImageDataInFile` error.

**Comment by dlemstra** [comment]
It seems that we were missing a call to `JxlDecoderReleaseInput`. This issue will be resolved in the next release.

**Comment by cocoon** [comment]
Thank you very much! 
The new version did read all jxl files I generated without a problem.
