### ISSUE TITLE
Load some heic file error

### ISSUE THREAD

**Issue by KngStr** [ImageMagick/ImageMagick#3386]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-3-portable-Q16-x64

### Operating system

Windows

### Operating system, version and so on

Windows 7 Enterprise sp1

### Description

I'm trying to load some heic files. But it failed with some of them.
![IM HEIC ERROR](https://user-images.githubusercontent.com/1308555/110783505-848c4f00-82a3-11eb-9ade-d8c2fa521735.jpg)

### Steps to Reproduce

Just load with imdisplay.

You can test with this file: [IMG20210103002456.zip](https://github.com/ImageMagick/ImageMagick/files/6122741/IMG20210103002456.zip)

**Comment by urban-warrior** [comment]
We utilize the libheif delegate library @ https://github.com/strukturag/libheif.  If you use their online demo @  https://strukturag.github.io/libheif/ you'll see the resulting image has major artifacts.  This suggests a bug in libheif since your image is correctly rendered with other HEIF online conversion apps.

**Comment by KngStr** [comment]
@urban-warrior 
Thanks. Should I report this issue to libheif?

**Comment by KngStr** [comment]
It seems to be fixed. https://github.com/strukturag/libheif/issues/465
Waiting for the next release.
