### ISSUE TITLE
[jxl] Comparison returns difference between a lossless JPEG transcoded JXL and the original JPG

### ISSUE THREAD

**Issue by ghost** [ImageMagick/ImageMagick#3397]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-3 (with the patch in #3375)

### Operating system

Linux

### Operating system, version and so on

* Arch Linux
* jpeg-xl 0.3.3

### Description

JXL can transcode a JPG losslessly, and the JXL can be reconstructed to the original JPG, i.e. the reconstructed JPG is bit-by-bit the same as the original JPG.

When using `compare -metric pae image.jpg image.jxl null:` on such files, the expected result should be `0 (0)`, but the actual result is not.

### Steps to Reproduce

1. Transcode a JPG losslessly to JXL: `cjxl image.jpg image.jxl`
2. `compare -metric pae image.jpg image.jxl null:`
3. For the test image, the result is `4369 (0.0666667)` (which is not expected because both images are the same)
4. Reconstruct the original JPG and save it to `image_1.jpg`: `djxl image.jxl image_1.jpg`
5. `compare -metric pae image.jpg image_1.jpg null:`
6. Result is `0 (0)`
7. (Optional) Compare the checksums of both jpgs and they should be identical

### Additional information

Imagemagick has no problem when comparing identical JPGs, but has problem when comparing a JPG and a JXL which has exactly the same image data.

Test image: https://upload.wikimedia.org/wikipedia/commons/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg

(Image copyright: Morio, CC BY-SA 3.0)

**Comment by urban-warrior** [comment]
ImageMagick calls the JPEG-XL delegate library to populate the image with pixels.  Any differences in pixels would be within the JPEG-XL delegate library since all we do is copy them from JxlDecoderSetInput() API call.  You might want to contact the JPEG-XL developers for additional help.

**Comment by dlemstra** [comment]
Can you test this again @ghost? Your `cjxl` command is not lossless. These are the options you will need to add (from their documentation):

```console
# Compress it losslessly. These are equivalent.
$ cjxl -d 0   input.png lossless.jxl
$ cjxl -q 100 input.png lossless.jxl
```

**Comment by TPS** [comment]
For those interested, this continued in https://gitlab.com/wg1/jpeg-xl/-/issues/180 & https://gitlab.com/wg1/jpeg-xl/-/issues/226
