### ISSUE TITLE
6.9.7-1 / 7.0.4-1 failed tests

### ISSUE THREAD

**Issue by remicollet** [ImageMagick/ImageMagick#340]
6.9.7-0 and 7.0.4-0 were OK.

```
ERROR: tests/validate-formats-memory.tap - too few tests run (expected 1, got 0)
ERROR: tests/validate-formats-disk.tap - too few tests run (expected 1, got 0)
ERROR: tests/validate-formats-map.tap - too few tests run (expected 1, got 0)

```

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by remicollet** [comment]
I confirm, 6.9.7-2 and 7.0.4-2 are ok.
Thanks.

**Comment by kellnerp** [comment]
ERROR: tests/validate-formats-disk.tap - too few tests run (expected 1, got 0)
ERROR: tests/validate-formats-map.tap - too few tests run (expected 1, got 0)
ERROR: tests/validate-formats-memory.tap - too few tests run (expected 1, got 0)
ImageMagick-7.0.5-3
Compiled according to http://www.linuxreport.org/compile-latest-version-of-imagemagick-and-php-imagick-on-ubuntu-14-04/
