### ISSUE TITLE
PerlMagick: getPixel returns incorrect values

### ISSUE THREAD

**Issue by pacien** [ImageMagick/ImageMagick#3402]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-3, PerlMagick 7.0.10 from CPAN

### Operating system

Linux

### Operating system, version and so on

NixOS, nixpkgs master branch

### Description

`$image->GetPixel` returns an incorrect pixel value. 

### Steps to Reproduce

Run the following script with the attached image.

```perl
use strict;
use warnings;

use Image::Magick;
use Data::Dumper;

my $image = Image::Magick->new(magick=>'png');
$image->Read('image.png');
my @pixel = $image->GetPixel(x=>300, y=>200);
print Dumper(\@pixel);
```

This prints:

```
$VAR1 = [
          '0',
          '0',
          '0.996108949416342'
        ];
```

This is incorrect. The pixel at the middle of the picture is green.

image.png:
![image](https://user-images.githubusercontent.com/1449319/111202009-aea38100-85c3-11eb-81b3-84178b2f14a7.png)

**Comment by pacien** [comment]
Note that the `convert` utility returns the correct value:

```
convert image.png -crop 1x1+300+200 txt:-
# ImageMagick pixel enumeration: 1,1,255,srgb
0,0: (0,255,0)  #00FF00  lime
```

**Comment by urban-warrior** [comment]
Edit Makefile.PL and change `MAGICKCORE_HDRI_ENABLE=0` to `MAGICKCORE_HDRI_ENABLE=1`.    We'll update CPAN soon.

**Comment by pacien** [comment]
I confirm that setting `MAGICKCORE_HDRI_ENABLE=1` solves the issue. Thanks!
