### ISSUE TITLE
Magick++/demo/gravity demo fails on Fedora 33+

### ISSUE THREAD

**Issue by sharkcz** [ImageMagick/ImageMagick#3404]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

git

### Operating system

Linux

### Operating system, version and so on

Fedora 33+

### Description

The Magick++/demo/gravity demo fails on Fedora 33 (or newer) systems with an error about missing `helvetica` font, see bellow. There is no such issue with Fedora 32, so probably something changed with regard to fonts there. Reproduced on x86_64, ppc64le and s390x systems.
````
...
PASS: Magick++/demo/demos.tap 4
angle 0
Caught exception: lt-gravity: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1425
not ok
FAIL: Magick++/demo/demos.tap 5
Writing image "piddle_out.miff" ...
Writing MVG metafile "piddle_out.mvg" ...
ok
PASS: Magick++/demo/demos.tap 6
...
````
When running under `strace` I see it tries to open a file called `helvetica` after reading many font related files (from `/etc/fonts`, `/usr/share/fontconfig` and more)
````
...
1454996 munmap(0x3ffa3d80000, 100328)   = 0
1454996 openat(AT_FDCWD, "helvetica", O_RDONLY) = -1 ENOENT (No such file or directory)
1454996 openat(AT_FDCWD, "/home/jenkins/workspace/ImageMagick/label/s390x/config/locale.xml", O_RDONLY) = 3
1454996 lseek(3, 0, SEEK_END)           = 2461
...
````

The `helvetica` font should be reachable and aliased to `NimbusSans`
````
<mock-chroot> bash-5.0# fc-match helvetica
NimbusSans-Regular.otf: "Nimbus Sans" "Regular"
````
Would anyone have an idea what could be the problem?

### Steps to Reproduce

`configure && make && make check`

**Comment by urban-warrior** [comment]
We develop ImageMagick on a Fedora 33 system and we do not have this issue.  Do you have `freetype-devel` installed?  What about `ghostscript-tools-fonts`?  https://imagemagick.org/script/install-source.php says "Ghostscript and Freetype are prerequisites, otherwise expect  ..." [some of the unit tests to fail].

**Comment by sharkcz** [comment]
I have all BuildRequires for the Fedora ImageMagick package (https://src.fedoraproject.org/rpms/ImageMagick/blob/rawhide/f/ImageMagick.spec#_20) installed, it includes `ghostscript-tools-fonts-9.53.3-5.fc34.x86_64` and `freetype-devel-2.10.4-3.fc34.x86_64`, so I'm quite lost ... Any chance you could provide me a list of installed rpm from your system (`rpm -qa`)? I suspect it could be a missing rpm, possibly from some package splits that wasn't installed during system upgrade from F-32.
