### ISSUE TITLE
identify -quiet does not suppress warnings

### ISSUE THREAD

**Issue by jfqd** [ImageMagick/ImageMagick#341]
Tried with ImageMagick version 6.9.3-0 and 6.9.7-1. Both versions do not suppress warnings when using ```-quiet```.

Running ```identify -quiet -format %wx%h ~/a.pdf[0]```

results in:

```
   **** Warning: considering '0000000000 XXXXX n' as a free entry.
292x607
```

Expected was:

```
292x607
```

**Comment by dlemstra** [comment]
Is this a warning from Ghostscript? Can you share your input file so we can try to reproduce this?

**Comment by jfqd** [comment]
Thank you for your fast response!

As this is a PDF file, it is possible, that the error is from Ghostscript. But should ```identify``` not suppress the warning, if ```-quiet``` is used?

You can download the today pdf from this link: http://bit.ly/2iuB4Bs

**Comment by jfqd** [comment]
FYI: The Ghostscript version is 9.20 (the latest).

**Comment by mikayla-grace** [comment]
Your link does not work.  When it does, we'll your PDF as a unit test for a patch we're working on.

**Comment by mikayla-grace** [comment]
Edit delegates.xml and add -sstdout=%%stderr before -dQUIET in several places.  You can then redirect stderr to /dev/null on the convert command-line.  Does that work for you?

**Comment by jfqd** [comment]
Thx for your suggestion. Yes that fixed it. But I need to rewrite my software, which I think is not perfect.

So the question is, why there is a ```-quiet``` flag, which is not doing what it is expected to do?

**Comment by dlemstra** [comment]
We are telling Ghostscript to be quiet (https://ghostscript.com/doc/9.20/Use.htm#dQUIET) but in your case it still outputs something. Ghostscript is an external tool that we cannot change. 

I build Ghostscript from source to see if I could figure out why it was printing that warning but it looks like the warning is no longer printed in the development version.

```
D:\ghostpdl\debugbin>gswin64c -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 -sDEVICE=ps2write -sOutputFile=test -- d:\images\pdf\a.pdf

D:\ghostpdl\debugbin>"c:\Program Files\gs\gs9.20\bin\gswin64c" -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 -sDEVICE=ps2write -sOutputFile=test -- d:\images\pdf\a.pdf
   **** Warning: considering '0000000000 XXXXX n' as a free entry.
```
Hope it will be gone in the next version of Ghostscript.

**Comment by jfqd** [comment]
Thank you all for your support!
