### ISSUE TITLE
Extreme memory consumption when converting gif to gif

### ISSUE THREAD

**Issue by poldi1405** [ImageMagick/ImageMagick#3418]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11.3

### Operating system

Linux

### Operating system, version and so on

Arch Linux x86_64 5.11.7-AMD

### Description

Converting a gif to gif completely fills the RAM. It filled 28 GB of RAM in about 10s.

I have a (rather big) gif (19 MB) created using 
```shell
youtube-dl https://youtu.be/5Z8HDADU57U
ffmpeg -i Ready\ for\ QA-5Z8HDADU57U.mkv Ready\ for\ QA.gif
```

ffmpeg is version 4.3.1

### Steps to Reproduce

`convert Ready\ for\ QA.gif please-dont-kill-my-machine.gif`

[gif-oom-bug.zip](https://github.com/ImageMagick/ImageMagick/files/6169274/gif-oom-bug.zip)

**Comment by dlemstra** [comment]
The dimensions of your gif are `3840x2160`, it contains `864` frames and has `3` channels of `1` byte. ImageMagick will load all frames at once and that means you need at least `3840*2160*864*3*1 = 21499084800` bytes (`21.4` Gb) to load the image. And of course the conversion of the image will require additional memory.

**Comment by poldi1405** [comment]
Okay, then it's probably more of a feature-request: a way to limit the RAM consumption to "normal" levels (for example by not loading all frames at once for gifs of a certain size).

It sure is an edge case but I feel that ImageMagick should not get OOM on a 32 Gig machine.

**Comment by snibgo** [comment]
As you use IM v7, I suggest you use "magick", not "convert".

I don't know what you really want to do. Do you merely want to convert one GIF to another?

A command of the form...
```
magick infile.ext {some_processing} outfile.ext
```
... will read all the images from inile.ext, then do the processing, then write all images to the output. IM has no mechanism to read just some images, then do the processing, write those, then continue with more input images.

"magick mogrify" does operate on one image at a time, and can be used to read a GIF and write all the images to another GIF.

Another possibility is:
```
magick infile.ext[0-99] {some_processing} outfile.ext
```
... to just process the first 100 images.

Or use gifsicle or some other utility.

**Comment by urban-warrior** [comment]
Try this command per https://imagemagick.org/script/architecture.php#tera-pixel:

```
magick -monitor -limit memory 2GiB -limit map 4GiB Ready\ for\ QA.gif please-dont-kill-my-machine.gif
```

To make limits global so you don't need to set limits individually on the command-line, see https://imagemagick.org/script/security-policy.php.

**Comment by poldi1405** [comment]
Thanks limiting kinda solved my problem since it's now writing the frames to /tmp… which is unfortunately is a ramdisk. But that's an issue I can resolve by myself. Thank you very much for your help.

**Comment by pirate486743186** [comment]
There's a bug in here. It shouldn't be consuming all this ram by default.

It should be loading the frames that it currently needs, then saving in a .part file.
More like video processing. If there's lots of ram, then it could go crazy on cache.

**Comment by urban-warrior** [comment]
ImageMagick does exactly as you propose if you set memory limits in the security policy or the `-limit` command-line option.   As an example, if you set the memory limit to 256MiB, once the limit is reached, all subsequent images are mapped to disk and memory mapped the next time they are accessed.  This statement in the security policy will apply the limit across all invocations of ImageMagick:

```
<policy domain="resource" name="memory" value="256MiB"/>
```

**Comment by pirate486743186** [comment]
yes, you said that in your previous comment here.

I'm saying, that it's a bug that the default is like it is. Why leave it like this?
the example gif is 19MB and consumes 20+GB of RAM, i've seen gifs of 70MB, presumably that would consume 70+GB. This is broken by default.

By default, it should behave nicely.

**Comment by urban-warrior** [comment]
Not a bug.  Its by design, see https://imagemagick.org/script/security-policy.php for the reasoning.    If you don't agree with the default policy, create your own policy by modifying the security policy to suit your local environment.

**Comment by pirate486743186** [comment]
Normally, you make default configurations to accommodate the noobs and simple usage. For advanced users, it's up to them to know what they are doing.

**Comment by urban-warrior** [comment]
If you read the architecture discussion @ https://imagemagick.org/script/architecture.php, you'll see ImageMagick automatically detects constrained memory consumption and moves subsequent images from memory-based caching  to disk.  If anyone does not agree with our default policies, they can change them with the security policy or by setting limits with any of the language wrappers, environment variables, or the command-line.
