### ISSUE TITLE
[Compile problem] in fourier.c at ForwardFourierTransform

### ISSUE THREAD

**Issue by rubyFeedback** [ImageMagick/ImageMagick#3422]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [ ] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

6666666

### Operating system

Other (enter below)

### Operating system, version and so on

GET RID OF THIS TEMPLATE SHIT PLEASE

### Description

NO

### Steps to Reproduce

SEE BELOW

Hi guys,

First - the issue template is HORRIBLE. I have been using github issue trackers for years
and the above is totally useless. So, apologies for skipping it, but I don't waste my time
with this garbage.

To the issue at hand:

I can not compile imagemagick right now.

Allow me to copy/paste the problem first:

    make[1]: Entering directory '/Depot/jjjj/ImageMagick-7.0.11.1'
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-animate.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-annotate.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-artifact.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-attribute.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-blob.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-cache.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-cache-view.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-channel.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-cipher.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-client.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-coder.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-color.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-colormap.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-colorspace.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-compare.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-composite.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-compress.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-configure.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-constitute.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-decorate.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-delegate.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-deprecate.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-display.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-distort.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-distribute-cache.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-draw.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-effect.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-enhance.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-exception.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-feature.lo
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-fourier.lo
    MagickCore/fourier.c: In function ‘ForwardFourierTransform’:
    MagickCore/fourier.c:71:25: error: subscripted value is neither array nor pointer nor vector
       71 | #define cabs(z)  (sqrt(z[0]*z[0]+z[1]*z[1]))
          |                         ^
    MagickCore/fourier.c:833:29: note: in expansion of macro ‘cabs’
      833 |         magnitude_pixels[i]=cabs(forward_pixels[i]);
          |                             ^~~~
    MagickCore    /fourier.c:71:30: error: subscripted value is neither array nor pointer nor vector
       71 | #define cabs(z)  (sqrt(z[0]*z[0]+z[1]*z[1]))
          |                              ^
    MagickCore/fourier.c:833:29: note: in expansion of macro ‘cabs’
      833 |         magnitude_pixels[i]=cabs(forward_pixels[i]);
          |                             ^~~~
    MagickCore/fourier.c:71:35: error: subscripted value is neither array nor pointer nor vector
       71 | #define cabs(z)  (sqrt(z[0]*z[0]+z[1]*z[1]))
          |                                   ^
    MagickCore/fourier.c:833:29: note: in expansion of macro ‘cabs’
      833 |         magnitude_pixels[i]=cabs(forward_pixels[i]);
          |                             ^~~~
    MagickCore/fourier.c:71:40: error: subscripted value is neither array nor pointer nor vector
       71 | #define cabs(z)  (sqrt(z[0]*z[0]+z[1]*z[1]))
          |                                        ^
    MagickCore/fourier.c:833:29: note: in expansion of macro ‘cabs’
      833 |         magnitude_pixels[i]=cabs(forward_pixels[i]);
          |                             ^~~~
    MagickCore/fourier.c:77:21: error: subscripted value is neither array nor pointer nor vector
       77 | #define cimag(z)  (z[1])
          |                     ^
    MagickCore/fourier.c:74:25: note: in expansion of macro ‘cimag’
       74 | #define carg(z)  (atan2(cimag(z),creal(z)))
          |                         ^~~~~
    MagickCore/fourier.c:834:25: note: in expansion of macro ‘carg’
      834 |         phase_pixels[i]=carg(forward_pixels[i]);
          |                         ^~~~
    MagickCore/fourier.c:80:21: error: subscripted value is neither array nor pointer nor vector
       80 | #define creal(z)  (z[0])
          |                     ^
    MagickCore/fourier.c:74:34: note: in expansion of macro ‘creal’
       74 | #define carg(z)  (atan2(cimag(z),creal(z)))
          |                                  ^~~~~
    MagickCore/fourier.c:834:25: note: in expansion of macro ‘carg’
      834 |         phase_pixels[i]=carg(forward_pixels[i]);
          |                         ^~~~
    MagickCore/fourier.c:80:21: error: subscripted value is neither array nor pointer nor vector
       80 | #define creal(z)  (z[0])
          |                     ^
    MagickCore/fourier.c:841:29: note: in expansion of macro ‘creal’
      841 |         magnitude_pixels[i]=creal(forward_pixels[i]);
          |                             ^~~~~
    MagickCore/fourier.c:77:21: error: subscripted value is neither array nor pointer nor vector
       77 | #define cimag(z)  (z[1])
          |                     ^
    MagickCore/fourier.c:842:25: note: in expansion of macro ‘cimag’
      842 |         phase_pixels[i]=cimag(forward_pixels[i]);
          |                         ^~~~~
    make[1]: *** [Makefile:8789: MagickCore/libMagickCore_7_Q16HDRI_la-fourier.lo] Error 1
    make[1]: Leaving directory '/Depot/jjjj/ImageMagick-7.0.11.1'
    make: *** [Makefile:6120: all] Error 2
    make install
    make  install-am
    make[1]: Entering directory '/Depot/jjjj/ImageMagick-7.0.11.1'
      CC       MagickCore/libMagickCore_7_Q16HDRI_la-fourier.lo
    MagickCore/fourier.c: In function ‘ForwardFourierTransform’:
    MagickCore/fourier.c:71:25: error: subscripted value is neither array nor pointer nor vector
       71 | #define cabs(z)  (sqrt(z[0]*z[0]+z[1]*z[1]))
          |                         ^
    MagickCore/fourier.c:833:29: note: in expansion of macro ‘cabs’
      833 |         magnitude_pixels[i]=cabs(forward_pixels[i]);
          |                             ^~~~
    MagickCore/fourier.c:71:30: error: subscripted value is neither array nor pointer nor vector
       71 | #define cabs(z)  (sqrt(z[0]*z[0]+z[1]*z[1]))
          |                              ^
    MagickCore/fourier.c:833:29: note: in expansion of macro ‘cabs’
      833 |         magnitude_pixels[i]=cabs(forward_pixels[i]);
          |                             ^~~~
    MagickCore/fourier.c:71:35: error: subscripted value is neither array nor pointer nor vector
       71 | #define cabs(z)  (sqrt(z[0]*z[0]+z[1]*z[1]))
          |                                   ^
    MagickCore/fourier.c:833:29: note: in expansion of macro ‘cabs’
      833 |         magnitude_pixels[i]=cabs(forward_pixels[i]);
          |                             ^~~~
    MagickCore/fourier.c:71:40: error: subscripted value is neither array nor pointer nor vector
       71 | #define cabs(z)  (sqrt(z[0]*z[0]+z[1]*z[1]))
          |                                        ^
    MagickCore/fourier.c:833:29: note: in expansion of macro ‘cabs’
      833 |         magnitude_pixels[i]=cabs(forward_pixels[i]);
          |                             ^~~~
    MagickCore/fourier.c:77:21: error: subscripted value is neither array nor pointer nor vector
       77 | #define cimag(z)  (z[1])
          |                     ^
    MagickCore/fourier.c:74:25: note: in expansion of macro ‘cimag’
       74 | #define carg(z)  (atan2(cimag(z),creal(z)))
          |                         ^~~~~
    MagickCore/fourier.c:834:25: note: in expansion of macro ‘carg’
      834 |         phase_pixels[i]=carg(forward_pixels[i]);
          |                         ^~~~
    MagickCore/fourier.c:80:21: error: subscripted value is neither array nor pointer nor vector
       80 | #define creal(z)  (z[0])
          |                     ^
    MagickCore/fourier.c:74:34: note: in expansion of macro ‘creal’
       74 | #define carg(z)  (atan2(cimag(z),creal(z)))
          |                                  ^~~~~
    MagickCore/fourier.c:834:25: note: in expansion of macro ‘carg’
      834 |         phase_pixels[i]=carg(forward_pixels[i]);
          |                         ^~~~
    MagickCore/fourier.c:80:21: error: subscripted value is neither array nor pointer nor vector
       80 | #define creal(z)  (z[0])
          |                     ^
    MagickCore/fourier.c:841:29: note: in expansion of macro ‘creal’
      841 |         magnitude_pixels[i]=creal(forward_pixels[i]);
          |                             ^~~~~
    MagickCore/fourier.c:77:21: error: subscripted value is neither array nor pointer nor vector
       77 | #define cimag(z)  (z[1])
          |                     ^
    MagickCore/fourier.c:842:25: note: in expansion of macro ‘cimag’
      842 |         phase_pixels[i]=cimag(forward_pixels[i]);
          |                         ^~~~~
    make[1]: *** [Makefile:8789: MagickCore/libMagickCore_7_Q16HDRI_la-fourier.lo] Error 1
    make[1]: Leaving directory '/Depot/jjjj/ImageMagick-7.0.11.1'
    make: *** [Makefile:12536: install] Error 2
    
-----------------

I was able to compile imagemagick just fine some months ago, and the underlying
software remained the same (I typically compile from source on my linux system).
So I suspect that some code in imagemagick must have changed, because fourier.c
suddenly complains. (Also, not totally related to this but perhaps it may be time to
consider abandoning libtool. This thing really keeps on causing me so many
issues ...)

That error in regards to fourier.c happens with ImageMagick-7.0.11.1
but also ImageMagick-7.0.11.3.

Perhaps there is something wrong with my host setup now, I don't know, but
gcc compiles just about everything fine here on my system as-is, so I don't
suspect my toolchain is broken. For example I can compile all of the KDE
suite just fine, and just yesterday compiled evince
http://ftp.gnome.org/pub/gnome/sources/evince/3.38/evince-3.38.2.tar.xz
and it also works fine. So I suspect something must have changed in 
imagemagick. Perhaps whoever understands the code at fourier transform 
could have a look.

PS: The "prerequisities" checkbox is also pointless. You encourage people
to use an auto-fill up that way. Or perhaps just add a third template that is
free-form, so people don't get handicapped when they try to report a bug...

PSS: Also there seems to be some javascript? Filling this all out took much
longer than the old freeform variant. Please don't follow github's quest
to erode the issue tracker functionality - it's the only reason I still use
github, since the issue tracker USED to be great. And now they are dumbing
it down at lightning speed ......... reminds me of wikipedia when they loaded
up the "fancy" editor. I hated this, compared to the free-form markdown
variant.

**Comment by rubyFeedback** [comment]
I forgot to add: the above was a free "./configure --prefix" just to test 
whether I can compile it.

Normally I use this:

    ./configure --prefix=/home/Programs/Imagemagick/7.0.11.1/ --enable-hdri --with-modules --without-perl --disable-static 

Similar to how BLFS recommends it but then imagemagick whines that libtool
is incomplete (what the ...). Even compile libtool anew, without problem, into
/usr/ prefix, does not change this error message. When I just do "./configure --prefix=/usr"
it works ok, until it breaks at the fourier.c stuff.

Also, my environment is:

        Operating system:                GNU/Linux
    Operating system bit type:       x86_64 (64 bit)
    CPU Model:                       AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G, 4 cores
    RAM:                             14951 MB RAM
    CFLAGS in use:                   -O2 -fPIC -fno-strict-overflow -Wno-error
    gcc:                             10.2.0
    glibc:                           2.28
    linux:                           5.8.0
    binutils:                        2.36.1
    ruby:                            2.7.2

**Comment by rubyFeedback** [comment]
Yikes, I meant "./configure --prefix=/usr". I use the palmoon browser; for some reason the javascript
at github is currently broken for me, so I can not edit my own issues. :\ That also used to work
some months ago ... really strange how things suddenly change, together with the claim of
"not a supported browser" nowadays. But I don't want use the google-monopoly browser and
neither the mozilla-paid-by-google variant either....

**Comment by dlemstra** [comment]
We have the template for a reason. Please enter the information that we requested and open a new issue.
