### ISSUE TITLE
Speed decrease from 7.0.8 to 7.0.11: blur with trim takes 350% longer.

### ISSUE THREAD

**Issue by Cerberus-tm** [ImageMagick/ImageMagick#3426]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-4

### Operating system

Windows

### Operating system, version and so on

10 Pro

### Description

A combination of blur and trim on any normal image (I've tried with several different images) seems to be much slower in the newer IM (7.0.11 versus 7.0.8).

### Steps to Reproduce

1. Download the image Test.jpg (in message below).
2. Uninstall any existing version of IM and install IM 7.0.11-4 (latest version).
3. Execute `magick "C:\Test.jpg" -blur 0x1 -trim info:` (or change to the appropriate file path).
- Execution takes about 550 ms.
4. Uninstall IM and reinstall the older version, 7.0.8.
5. Execute the exact same command again.
- Execution now takes about 110 ms.

I love IM, but I don't know much about it, so I apologize in case I'm doing something wrong.

This command takes about 110 ms for me with IM 7.0.8-23, while it takes about 550 ms with IM 7.0.11-4. It is basically the combination of blur with trim on any normal image (test image below; but I've tried with several different normal images) that is much slower in the newer IM. When you need to do this 1000 times, it adds up.

Versions I've tried (which are slow):
- ImageMagick-7.0.11-4-Q16-x64-dll.exe
- ImageMagick-7.0.11-4-Q16-HDRI-x64-dll.exe
- ImageMagick-7.0.11-4-Q8-x64-static.exe

Old version (which is fast):
- ImageMagick-7.0.8-23-Q16-x64-dll.exe

![Test](https://user-images.githubusercontent.com/4452023/111937157-70c4c200-8ac7-11eb-9e53-18ecf8963643.jpg)

**Comment by urban-warrior** [comment]
Try eliminating `info:`.  What is the millisecond timing for `magick "C:\Test.jpg" -blur 0x1 -trim null:`.  If that has similar benchmarks for 7.0.8 and 7.0.11, that would suggest that ImageMagick .11 is performing more work for the `info:` coder.

**Comment by Cerberus-tm** [comment]
@urban-warrior Thanks for the suggestion. I tried it, but it still takes over 500 ms. In my experience, it's blur and trim together that cause the huge time increase. I wonder what could have happened, between such minor versions.

**Comment by fmw42** [comment]
Test blur only. Then Test trim only.  Does one of them show the delay?

**Comment by fmw42** [comment]
Have you considered your resource limits (memory, map, temp directory space) etc or hardware speed?

**Comment by fmw42** [comment]
I see no significant time difference between 7.0.8.23 Q16 Mac OSX Sierra and 7.0.12.4 Q16 Mac OSX Sierra.

`magick -version`
Version: ImageMagick 7.0.11-4 Q16 x86_64 2021-03-20 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(3.1) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc jbig jng jp2 jpeg lcms lqr ltdl lzma openexr png ps raw rsvg tiff webp x xml zlib

IM 7.0.11.4
`time magick hummingbird.jpg -blur 0x1 -trim info:`
hummingbird.jpg JPEG 700x531 700x531+0+0 8-bit sRGB 111512B 0.020u 0:00.003

real	0m0.222s
user	0m0.307s
sys	0m0.062s


IM 7.0.8.23 
`time magick hummingbird.jpg -blur 0x1 -trim info:`
hummingbird.jpg JPEG 700x531 700x531+0+0 8-bit sRGB 111512B 0.020u 0:00.000

real	0m0.215s
user	0m0.286s
sys	0m0.060s

**Comment by Cerberus-tm** [comment]
@fmw42 Thanks for testing! I could have sworn I tested blur and trim separately, and the increase only happened with the combination; but now I see it happens even with blur only (not with trim only), and even at `0x0`:
`magick "C:\Test.jpg" -blur 0x0 null:`
Takes ca. 550 ms.

`magick "C:\Test.jpg" -trim null:`
Takes ca. 80 ms, as expected.

I think my system is pretty fast, shouldn't be an issue (though I'm not sure what "map is?), specs below. And it's strange how IM 7.0.8 didn't have this issue for me. And I haven't seen any other operations that seem unexpectedly slow, in neither version.

`magick -version`
Version: ImageMagick 7.0.11-4 Q8 x64 2021-03-20 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Visual C++: 192829910
Features: Cipher DPC Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zip zlib

System:
Processor: 6-core Ryzen 2600
Video card: RX 570 4GB (two years old, fairly good)
Storage: Samsung 970 NVME, plenty of free space
16 GB of decent RAM

**Comment by fmw42** [comment]
compare your two systems for

`magick -list resource`

**Comment by Cerberus-tm** [comment]
Resource limits:
  Width: 1.8447EP
  Height: 1.8447EP
  Area: 17.109GP
  List length: unlimited
  Memory: 7.9671GiB
  Map: 15.934GiB
  Disk: unlimited
  File: 1536
  Thread: 12
  Throttle: 0
  Time: unlimited

But what do you mean by "two systems"? Oh, maybe you mean with the old version of IM installed? The above is with 7.0.11.

**Comment by fmw42** [comment]
Yes, compare to your old IM. However, the new one looks fine. As you can see from my timings, I saw no significant difference. Note that the first time you run any command after booting, it will take extra time for IM to load things. Did you do an average of number of runs and discard the first one?

**Comment by Cerberus-tm** [comment]
I've probably run this and similar commands with blur fifty times over ca. three Windows sessions. And the timings are always similar, somewhere around 500–550 ms. It's quite consistent. I think you use an Apple computer? Could it be something that is specific to the Windows version of IM?

**Comment by snibgo** [comment]
Perhaps your old version used OpenCL, and your new one doesn't, for some reason. Try the command again on both systems, after running this:
```
set MAGICK_OCL_DEVICE=off
```

**Comment by Cerberus-tm** [comment]
Yes! That did the trick.
`set MAGICK_OCL_DEVICE=off
magick "C:\Test.jpg" -blur 0x1 null:`
50–80 ms.

So this means I need to use this `set` command before each time I use Image Magick in a script. I wonder why that is. Did I do something wrong? Is there something unusual about my system? If so, why did the issue not occur with IM 7.0.8?

Is there some way to set this option automatically, system wide?

**Comment by snibgo** [comment]
See my last reply in https://github.com/ImageMagick/ImageMagick/discussions/3438

**Comment by dlemstra** [comment]
We are planning to disable OpenCL by default in a future release and make it an opt-in feature instead. You will need to do `set MAGICK_OCL_DEVICE=on` to enable it instead of having to turn it off.

**Comment by Cerberus-tm** [comment]
@snibgo Thank you, that works perfectly! I didn't even know `set` set an environment variable.

@dlemstra Interesting, So `set MAGICK_OCL_DEVICE=off` disables OpenCL, and for some reason OpenCL slows things down? This suggests that it was off by default in 7.0.8, but something (the installer?) of 7.0.11 sets it to `on` on installation of IM?

**Comment by dlemstra** [comment]
At some point in time we enabled OpenCL by default or added support for using OpenCL when blurring and that probably happend between those versions. OpenCL can make things a lot faster but that depends on the operations that you are doing and how you are using the library. But due to the recent issues that we are seeing with OpenCL and because it is not always easy to figure out that OpenCL is causing this we will disable this by default in future releases (probably the next one).

**Comment by Cerberus-tm** [comment]
@dlemstra OK great, that makes sense. So I might try to enable it for specific operations while experimenting. Dank U!
