### ISSUE TITLE
Extraneous spaces in AC_PATH_PROG calls in configure.ac break the default delegates

### ISSUE THREAD

**Issue by xworld21** [ImageMagick/ImageMagick#3428]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.10-61

### Operating system

MacOS

### Operating system, version and so on

10.5.7, installed via nixpkgs

### Description

The current calls to [AC_PATH_PROG](https://github.com/ImageMagick/ImageMagick/blob/20f7808d700c811f3e01ac0bcbcf9eb968abaeb1/configure.ac#L3227) have an extra space in the second and third arguments. And probably too many quotes, but I don't understand m4, so maybe that's ok.

On macOS/nixpkgs *at least*, this causes an extra space to be added to the default delegates in `delegates.xml`, so for instance `&quot;potrace&quot;` becomes `&quot; potrace&quot;`, and it breaks everything.

I am not sure why only certain systems are affected – possibly subtle differences in autotools?

### Steps to Reproduce

Compile ImageMagick with `--with-frozenpaths` on a system that does not have enough runtime dependencies installed, so that it falls back to the default delegates, and check the content of `delegates.xml`.

You may also check the [patch I have submitted to nixpkgs](https://github.com/NixOS/nixpkgs/blob/2c91363b38ed0134d24002bcfdc7ba3759bf2c3a/pkgs/applications/graphics/ImageMagick/remove-breaking-quotes.patch) to see the extraneous spaces popping up in `configure`.

**Comment by veprbl** [comment]
Seems like a regression in c1bfec283549b81ee8b7c49817da77396a3612e9
cc @urban-warrior

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
