### ISSUE TITLE
fx:standard_deviation (and maybe others) are computed incorrectly starting with ImageMagick 7.0.1-0

### ISSUE THREAD

**Issue by stapelberg** [ImageMagick/ImageMagick#343]
```
$ git log -n 1 --format=oneline
39bcfab4687c9cd127e339ee382bd501240cd934 https://github.com/ImageMagick/ImageMagick/issues/341
$ ./utilities/magick --version                                                 
Version: ImageMagick 7.0.4-3 Q16 x86_64 2017-01-04 http://www.imagemagick.org
[…]
$ ./utilities/magick identify -format '%[fx:standard_deviation]' images/arc.png
identify: UnableToOpenConfigureFile `magic.xml' @ warning/configure.c/GetConfigureOptions/715.               
0.157948
```

Which differs from:
```
$ identify --version
Version: ImageMagick 6.9.6-6 Q16 x86_64 20161125 http://www.imagemagick.org
$ identify -format '%[fx:standard_deviation]' images/arc.png
0.182382
```

I _think_ this is because the newer version of the code is computing averages by dividing the sums by 4 (including the alpha channel, for which the sum is 0) instead of dividing by 3.

Indeed, comparing the values of an individual channel yields the correct result:
```
$ ./utilities/magick identify -format '%[fx:standard_deviation.g]' images/arc.png
identify: UnableToOpenConfigureFile `magic.xml' @ warning/configure.c/GetConfigureOptions/715.
0.155013
$ identify -format '%[fx:standard_deviation.g]' images/arc.png                   
0.155013
```

I originally wanted to bisect the change, but unfortunately the git repository contains a lot of commits which don’t build, which drastically slows down bisection time, so I gave up after a few hours.

What I can say is that I cannot reproduce the issue with 6.9.7-2, and I can reproduce the issue with 7.0.1-0.

**Comment by mikayla-grace** [comment]
The arc.png image has an alpha channel and is including when computing the standard deviation in IMv7, it is not included by default with IMv6.  See the porting guide @ https://www.imagemagick.org/script/porting.php for this and other important differences between version 6 and 7.  To return the same value for both versions, explicitly set the channels you want to use in the standard deviation computation:

```
identify -channel rgb -format '%[fx:standard_deviation]' images/arc.png
```

**Comment by stapelberg** [comment]
Ah! Thanks for the pointer. Since the change is intentional, I’m closing this issue.
