### ISSUE TITLE
Does not render full image after convert

### ISSUE THREAD

**Issue by olegkhorev** [ImageMagick/ImageMagick#3443]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [ ] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

6.9.10-68 Q16

### Operating system

Linux

### Operating system, version and so on

CentOS 7

### Description

Very often it does not finish rendering image and it has black at the bottom

### Steps to Reproduce

I just run "convert png_image jpg_image" - PNG has no transparent background, just easier for use to use JPG.

Hello,

I have issue with ImageMagick convert function.

Very often it does not finish rendering image and it has black at the bottom

![0c2ccbd46704c246827decf6a406476c png](https://user-images.githubusercontent.com/4076932/112332900-90303a80-8cd3-11eb-9e79-6e73f9a6e38c.jpg)

See attached.

I hope for some help.

Thank you,
Oleg

**Comment by dlemstra** [comment]
Please don't create both a discussion and an issue. Your discussion has been deleted.

**Comment by snibgo** [comment]
The problem may be OpenCL. Try disabling it, by setting MAGICK_OCL_DEVICE to false.

**Comment by olegkhorev** [comment]
> MAGICK_OCL_DEVICE

Thank you for your reply. Sorry I don't know where to find that. Spent 20 minutes trying to find but cannot. CentOS 7 and ImageMagick 6.9

Could you tell me, please?

**Comment by snibgo** [comment]
I don't use bash much, but I think the command to set an environment variable is:
```
export MAGICK_OCL_DEVICE=true
```

**Comment by olegkhorev** [comment]
> I don't use bash much, but I think the command to set an environment variable is:
> 
> ```
> export MAGICK_OCL_DEVICE=false
> ```

I have typed that
[root@~]# export MAGICK_OCL_DEVICE=false

I hope it is what you mean? Please, confirm. We will keep looking if it happen
