### ISSUE TITLE
Regression in JP2 support

### ISSUE THREAD

**Issue by jonathangreen** [ImageMagick/ImageMagick#345]
I am having trouble using ImageMagick to work with a JP2 file. I started seeing this behaviour when updating to the latest imagemagick.

I am getting this error:
```
convert: Problem with skipping JPEG2000 box, stream error
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/193.
convert: unable to decode image file `licorenko.jp2' @ error/jp2.c/ReadJP2Image/383.
convert: no images defined `lyrasis-1552_TN.jpg' @ error/convert.c/ConvertImageCommand/3212.
```

Using git-bisect it seems like this is the first commit that has this issue:
8ef435d718d779aa8f959e7aa9a2f9f8f413e9ea

Any commit before that is able to work with the file okay.

You can find a zip containing the JP2 that is causing the issue here:
[licorenko.jp2.zip](https://github.com/ImageMagick/ImageMagick/files/690515/licorenko.jp2.zip)

`opj_decompress` and `opj_dump` from OpenJPEG seem to read the file okay. And preview on my Mac doesn't seem to have any problem with the file.

**Comment by fmw42** [comment]
Imagemagick switched to using OpenJpeg rather than Jasper to read jp2 images. You will need to install tohe openjpeg 2.1.x delegate library for current versions of IM

**Comment by jonathangreen** [comment]
Both before and after that commit are both using OpenJPEG. 

If I compile ImageMagick with the same libraries, same configuration options, etc. I get the error shown when using any 8ef435d and any commit after it. If I use 6d56b1330d9bca0a3d9f9b93d78b9e7eaa4321e4 which is the commit immediately before then I am able to work with the attached JP2 file.

**Comment by fmw42** [comment]
I tried to read you file, which opens fine in Mac Preview, but do get errors using IM 6.9.7.2. But IM 7.0.4.2 will read it.

```
IM 6
identify licorenko.jp2
identify: Problem with skipping JPEG2000 box, stream error
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/193.
identify: unable to decode image file `licorenko.jp2' @ error/jp2.c/ReadJP2Image/386.
```


```
IM 7
magick identify licorenko.jp2
licorenko.jp2 JP2 2067x2955 2067x2955+0+0 8-bit Grayscale Gray 2.475MB 0.000u 0:00.000
```


However neither will convert the image:
```
magick convert licorenko.jp2 licorenko.png
convert: Problem with skipping JPEG2000 box, stream error
 `OpenJP2' @ error/jp2.c/JP2ErrorHandler/193.
convert: unable to decode image file `licorenko.jp2' @ error/jp2.c/ReadJP2Image/384.
convert: no images defined `licorenko.png' @ error/convert.c/ConvertImageCommand/3254.

```

So I will leave this for the IM developers to examine.

**Comment by mikayla-grace** [comment]
With ImageMagick 6.9.7-2 and 7.0.4-2 and OpenJPEG2 version 2.1.2, we could identify, display, and convert your image with expected results and no exceptions.

**Comment by dlemstra** [comment]
Can we close this issue @jonathangreen?

**Comment by jonathangreen** [comment]
@dlemstra Apologies for the delay on my part here. This has been on my todo list and I haven't gotten around to it. If you can leave it open I'll compile with the versions mentioned, confirm it works for me and close the ticket if so next week.

**Comment by jonathangreen** [comment]
Finally circled back around to test this and it does indeed work with the latest openjp2. Many thanks for all the help. In case it helps anyone in the future when it finally started working it was giving this warning:
convert licorenko.jp2 licorenko.png
convert: Non conformant codestream TPsot==TNsot.
 `OpenJP2' @ warning/jp2.c/JP2WarningHandler/236.

So I assume there is something not quite right in this JP2 file.
