### ISSUE TITLE
C MagickWand: MagickReadImageBlob cannot find decode delegate for JXR data

### ISSUE THREAD

**Issue by iameox** [ImageMagick/ImageMagick#3456]
### Prerequisites

- [X] I have written a descriptive issue title
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [x] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-6

### Operating system

Linux

### Operating system, version and so on

Ubuntu Server 20.04.2 LTS

### Description

MagickReadImageBlob fails with exception "no decode delegate for this image format `JXR' @ error/blob.c/BlobToImage/458" although it works if I write the blob to a ".jxr" file and then call MagickReadImage.
I'm not sure if this is a bug since I'm new to MagickWand but I need to know if I can read a JXR memory blob without writing it to a file first. Maybe I missed something?

### Steps to Reproduce

The following code works for me (it creates the PNG image):
```c
unsigned char *data = // the blob
size_t size = // the blob's size in bytes
FILE *image_file = fopen("img.jxr", "wb");
if (image_file == NULL) return 1;
fwrite(data, size, 1, image_file);
fclose(image_file);
MagickWandGenesis();
MagickWand *wand = NewMagickWand();
MagickBooleanType status = MagickReadImage(wand, "img.jxr");
if (status == MagickFalse) {
    ExceptionType e;
    fprintf(stdout, "%s\n", MagickGetException(wand, &e));
} else {
    MagickWriteImage(wand, "img.png");
}
ClearMagickWand(wand);
MagickWandTerminus();
```

But this won't and prints the above exception:
```c
unsigned char *data = // the blob
size_t size = // the blob's size in bytes
MagickWandGenesis();
MagickWand *wand = NewMagickWand();
MagickSetFilename(wand, "jxr:img.jxr");
MagickBooleanType status = MagickReadImageBlob(wand, data, size);
if (status == MagickFalse) {
    ExceptionType e;
    fprintf(stdout, "%s\n", MagickGetException(wand, &e));
} else {
    MagickWriteImage(wand, "img.png");
}
ClearMagickWand(wand);
MagickWandTerminus();
```

I also tried to add `MagickSetFormat("JXR")` but it doesn't seem to do anything in my case (no exception but MagickGetFormat returns an empty string).

Edit: I should also mention that I had to tweak the JXR delegate to make it work for me. I changed it so that JxrDecApp converts the input to a BMP file instead of a PNM.

Edit 2: the following code also fails with the same exception:
```c
FILE *file_stream = // the JXR image stream
MagickWandGenesis();
MagickWand *wand = NewMagickWand();
MagickSetFilename(wand, "jxr:img.jxr");
MagickBooleanType status = MagickReadImageFile(wand, file_stream);
if (status == MagickFalse) {
    ExceptionType e;
    fprintf(stdout, "%s\n", MagickGetException(wand, &e));
} else {
    MagickWriteImage(wand, "img.png");
}
ClearMagickWand(wand);
MagickWandTerminus();
fclose(file_stream);
```

**Comment by urban-warrior** [comment]
The JxrDecApp can't handle all the variations of the JXR format.  Can you post a link to img.jxr so we can inspect the image and ensure ImageMagick supports it.
