### ISSUE TITLE
memory allocation failed ' @ error/tiff.c/ReadTIFFImage/1780

### ISSUE THREAD

**Issue by Yoda-Man** [ImageMagick/ImageMagick#3460]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.23.3

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

I get the error "memory allocation failed ' @ error/tiff.c/ReadTIFFImage/1780"

when converting Tiff files with more than 100 pages to PDF
on the line collection.AddRange(FileName);

### Steps to Reproduce

I only get the error on large Tiff files over 100 pages.

I have tried 3 different approaches and I get the same error

**Approach 1**
                using (var collection = new MagickImageCollection())
                {
                    collection.AddRange(FileName);
                    collection.Write(sOutputFile);
                }

**Approach 2**

        using (var collection = new MagickImageCollection())
        {
            using (FileStream fs = File.OpenRead(FileName))
            {
                collection.AddRange(fs);
                collection.Write(sOutputFile);

            }
        }

**Approach 3**
                byte[] tiffArray = File.ReadAllBytes(FileName);

                using (var collection = new MagickImageCollection())
                {
                    collection.AddRange(tiffArray);
                    collection.Write(sOutputFile);
                }

**Comment by dlemstra** [comment]
It looks like you are using the Magick.NET library. Are you using the 32bit or the 64bit version of the library?

**Comment by Yoda-Man** [comment]
I am using the 32Bit Version of the library

**Comment by dlemstra** [comment]
You are probably running into a 32 bit memory allocation issue. I would advise you to switch to a 64-bit version.

**Comment by Yoda-Man** [comment]
Thanks, I will do that.

**Comment by Yoda-Man** [comment]
switching to a 64 bit version did the trick.
