### ISSUE TITLE
Attempting to output animated APNG image with PNG extension exports first frame then throws "delegate failed"

### ISSUE THREAD

**Issue by Scripter17** [ImageMagick/ImageMagick#3468]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-5

### Operating system

Windows

### Operating system, version and so on

Windows 10 20H2 (2020-08-28)

### Description

Trying to export an APNG file with a PNG extension (to make one of those Discord "don't open in the browser" memes) throws `magick: delegate failed `"ffmpeg.exe" -nostdin -v -1 -i "%M%%d.pam" -plays %I "%u.%m"' @ error/delegate.c/InvokeDelegate/1907.`

Image magick is on version 7.0.11-5 and ffmpeg is the 4.2.3 version included with IM, though replacing the file with the 4.3.2 full version on [gyan.dev](https://www.gyan.dev/ffmpeg/builds/) doesn't fix the error

Doing the same but with JPG instead of APNG appears to work just fine, so this seems to be a bug with how IM handles APNG files specifically and not the `format:` output... thing

Also worth noting that the images I'm using *are* the same size. Exporting as an APNG file works just fine

### Steps to Reproduce

1. Run `magick 1.png 2.png apng:3.png`

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by Scripter17** [comment]
Issue is resolved as of 7.0.11-13. Closing the issue now

Thank you for the help
