### ISSUE TITLE
$LIBS_magick in all Makefile.PL.in files miss libperl when not using system perl

### ISSUE THREAD

**Issue by perlfam** [ImageMagick/ImageMagick#3469]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.x (believe 6.x also)

### Operating system

Linux

### Operating system, version and so on

debian, ensure `libperl-dev` is NOT installed

### Description

For details, see https://perlmonks.org/?node_id=11130498 - the essential problem is discussed as are steps attempted to resolve. A solution was proposed and worked; this solution is included below:

Essential solution, for all `Makefile.PL.in` files:

```
-my $LIBS_magick = '-L../magick/.libs -lMagickCore-@MAGICK_MAJOR_VERSION@.@MAGICK_ABI_SUFFIX@ -lperl @MATH_LIBS@';
+my $LIBS_magick = '-L../magick/.libs -lMagickCore-@MAGICK_MAJOR_VERSION@.@MAGICK_ABI_SUFFIX@ @MATH_LIBS@ -L' . $Config{'archlib'} . '/CORE';
```

### Steps to Reproduce

on debian (e.g., via `docker run -it debian:stretch-slim` sh):

1. install `perlbrew`
2. install a `perl`
3. prepare for Linux source build/installation as non-privileged user following most current documentation
4. use that `perl` to ./configure and build any 7.x from source `--with-perl`:

```
./configure --prefix=/path/to/my/prefixdir --with-perl=/path/to/perlbrew/installed/perl
make
```

Fails during PerlMagick build stage, saying it can't find `-lperl`

Note: I can provide a PR if the above solution seems acceptable. I am not the original author of the fix, seems like a good thing to get upstream.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by perlfam** [comment]
Thank you very much for this and for your awesome contributions.

**Comment by perlfam** [comment]
@urban-warrior - just wanted to make sure I pointed out; there are 3 `Makefile.PL.in` files; all of which need to be updated based on my using the solution. So long as you consider that, I have no other oversight to provide:

* `PerlMagick/Makefile.PL.in`
* `PerlMagick/default/Makefile.PL.in`
* `PerlMagick/quantum/Makefile.PL.in`

Thank you, again.

**Comment by todd-richmond** [comment]
same issue with 6 and there is a missing trailing ; so the build fails

**Comment by dlemstra** [comment]
Is this resolved in the latest release and can we close this issue?
