### ISSUE TITLE
Error converting png to jpg: "insufficient image data in file" 

### ISSUE THREAD

**Issue by wjl311** [ImageMagick/ImageMagick#3470]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-5

### Operating system

Linux

### Operating system, version and so on

 Ubuntu 18.04, 64bit

### Description

I'm trying to convert an image from png to jpg and it fails as InsufficientImageDataInFile。

### Steps to Reproduce

Compile with the following command:
```
$ CC=/usr/local/bin/afl-clang CXX=/usr/local/bin/afl-clang++ ./configure --disable-shared 
$ make
```
run with this command:
```
$ ./magick convert id:000000,sig:06,src:003649,op:havoc,rep:4.png out.jpg
convert: InsufficientImageDataInFile `id:000000,sig:06,src:003649,op:havoc,rep:4.png' @ error/dib.c/ReadDIBImage/671.
convert: NoImagesDefined `out.jpg' @ error/convert.c/ConvertImageCommand/3322.
```
version:
```
$ ./magick convert --version
Version: ImageMagick 7.0.11-5 Q16 x86_64 2021-03-20 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(3.1) 
Delegates (built-in): bzlib djvu fontconfig freetype gvc jbig jng jpeg lcms lqr lzma openexr png tiff x xml zlib
```
Please ask how this error should be solved, is this a bug?

You can use this to test .
[test.zip](https://github.com/ImageMagick/ImageMagick/files/6227293/test.zip)

**Comment by snibgo** [comment]
Your file id000000,sig06,src003649,ophavoc,rep4.png is no a valid PNG file. Perhaps it is corrupt.
