### ISSUE TITLE
After cropping a TIFF, converting to PDF  most of the image is lost when viewing with Acrobat Reader

### ISSUE THREAD

**Issue by wvwhome** [ImageMagick/ImageMagick#3479]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-4 Q16 x64 2021-03-20

### Operating system

Windows

### Operating system, version and so on

10 Pro 

### Description

After cropping a TIFF, and converting to PDF  most of the image is missing when viewing with Acrobat Reader

### Steps to Reproduce

After cropping a TIFF, converting to PDF causes most of the image to be missing when viewing with Acrobat Reader.

I've uploaded the TIFF file zipped.

The command I used: convert   FP_density_300_compress_lzw_IM_6.tiff  FP_density_300_compress_lzw_IM_6.pdf 
The same issue with ImageMagick 6.9.10-68 Q16 x86_64 2021-02-24 on Linux CentOS 7

This is not an issue with lower density, but I want the higher resolution.

[FP_density_300_compress_lzw_IM_6_crop.zip](https://github.com/ImageMagick/ImageMagick/files/6232941/FP_density_300_compress_lzw_IM_6_crop.zip)

**Comment by fmw42** [comment]
When cropping your TIFF, did you add +repage after the -crop command? If not, try that.

**Comment by wvwhome** [comment]
Thanks.  I had not used +repage.   On using it, the problem has been solved.  I'll read the docs more closely next time.

**Comment by fmw42** [comment]
See https://legacy.imagemagick.org/Usage/formats/#png_offsets and https://imagemagick.org/script/command-line-options.php#repage. There is no direct mention that I can find for TIFF, but it also has a virtual canvas.
