### ISSUE TITLE
Load more cpu

### ISSUE THREAD

**Issue by skyleelove** [ImageMagick/ImageMagick#349]
Hi,
Imagemagick version: 6.9.6
Linux version 2.6.32-642.1.1.el6.x86_64
When I use Imagemagick to process picture，I find that when  calling libMagickCore-6.Q16.so.2 of ImageMagick take more cpu.How can I do for this。
？

**Comment by dlemstra** [comment]
I have no idea what you are trying to ask.

**Comment by skyleelove** [comment]
The cpu is high when I use ImageMagick.Imagemagick version is 6.9.6.

**Comment by skyleelove** [comment]
![image](https://cloud.githubusercontent.com/assets/18411957/21800750/f5f3c8ca-d759-11e6-91e7-ba63c6e77099.png)

**Comment by skyleelove** [comment]
I just add a watermark to a picture and resize picture size

**Comment by skyleelove** [comment]
The qps is about 20.

**Comment by mikayla-grace** [comment]
To reduce CPU load, you can cache your image to disk (tradeoff CPU for IO), or add a CPU throttle.  To cache you image to disk, you need to set the memory and map resource limits to a modest value, perhaps 2MB.   To throttle the CPU, add this to your policy.xml configuration file:

`  <policy domain="resource" name="throttle" value="2"/>`
