### ISSUE TITLE
imagemagick 7.0.11-5 produces garbage in DDS mipmaps

### ISSUE THREAD

**Issue by wmassingham** [ImageMagick/ImageMagick#3492]
### Prerequisites

I have written a descriptive issue title
I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-5

### Operating system

Windows

### Operating system, version and so on

Windows 10 20H2 version 10.0.19042.870 64-bit

### Description

From https://github.com/ImageMagick/ImageMagick/discussions/3486

Converting an image to DDS is expected to generate a valid DDS image with mipmaps. ImageMagick appears to create a valid image but with garbage data for mipmaps.

### Steps to Reproduce

1. Take a test image like https://homepages.cae.wisc.edu/~ece533/images/fruits.png (also attached)
2. `magick fruits.png fruits.dds`
3. Observe result has valid first image and garbage mipmaps (screenshot.png, attached)

[fruits.png](https://user-images.githubusercontent.com/305160/113354707-676ffc80-92f4-11eb-83b3-e201f73bf50f.png)
[screenshot.png](https://user-images.githubusercontent.com/305160/113354669-5f17c180-92f4-11eb-9452-ca8f16f0d424.png)

**Comment by wmassingham** [comment]
I compiled current git and it's working properly there. I guess it's already been fixed since 7.0.11-5.

**Comment by dlemstra** [comment]
It is very unlikely that it was fixed after the release of 7.0.11-5 because the changes that were made are not in the dds encoder. Did you compile a debug or a release build?

**Comment by wmassingham** [comment]
Release.

**Comment by dlemstra** [comment]
The changes that were made are all in unrelated areas and could not suddenly fix it. Did you check if the output of `magick -version` produces the same output?

**Comment by dlemstra** [comment]
I suspect that the version that works for you has `OpenCL` missing from the output. I just pushed a fix to resolve this.

**Comment by wmassingham** [comment]
Yes, it looks like I initially compiled without OpenCL, but after rebuilding with OpenCL the garbage showed up again. After pulling your fix it works as expected.
