### ISSUE TITLE
Thumbnail option fails silently

### ISSUE THREAD

**Issue by dennis508** [ImageMagick/ImageMagick#3498]
### Prerequisites

I have written a descriptive issue title
I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-5 Q8 x64

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

Thumbnail option fails silently. No output and no error.
>magick Image.TIF -auto-orient -thumbnail 160x128 -strip -depth 8 zzzz.png

Changing -thumbnail to -size works. Output file type doesn't matter.

convert -version
Version: ImageMagick 7.0.11-5 Q8 x64 2021-03-28 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Visual C++: 192829912
Features: Cipher DPC Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zip zlib

### Steps to Reproduce

magick Image.TIF -auto-orient -thumbnail 160x128 -strip -depth 8 zzzz.png
or 
convert...

[Image.zip](https://github.com/ImageMagick/ImageMagick/files/6250956/Image.zip)

**Comment by dlemstra** [comment]
All related to a mistake I made last week. A new release to fix this will be published soon.

**Comment by fmw42** [comment]
Works fine for me on IM 7.0.11.5 Q16 Mac OSX Sierra with LIBTIFF, Version 4.1.0
