### ISSUE TITLE
Identify shows APNG has only one frame

### ISSUE THREAD

**Issue by animeavi** [ImageMagick/ImageMagick#3499]
### Prerequisites

I have written a descriptive issue title
I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-5

### Operating system

Linux

### Operating system, version and so on

Debian 10

### Description

When using identify with an APNG, it shows only one frame, with GIFs it works properly.

### Steps to Reproduce

Running:
magick identify -format "%n" clock.png 

Shows 1 for the attached APNG.

![clock](https://user-images.githubusercontent.com/14946679/113467067-8bbffc00-940e-11eb-84cb-9231c5e76868.png)

**Comment by fmw42** [comment]
You need to identify your png as APNG. Try

`magick identify -format "%n\n" APNG:clock.png | head -n 1`
40

**Comment by animeavi** [comment]
I get `identify: delegate failed 'ffmpeg' -nostdin -v -1 -i '%i' -vframes %S -vcodec pam -an -f rawvideo -y '%u.pam' 2> '%u'' @ error/delegate.c/InvokeDelegate/1907.` but may because I have an old ffmpeg version (4.1.6-1~deb10u1).

**Comment by fmw42** [comment]
I am using ffmpeg version 4.2.1

**Comment by fmw42** [comment]
FYI see comment about APNG at https://imagemagick.org/script/formats.php

**Comment by animeavi** [comment]
Thank you, it's not a bug then.

**Comment by fmw42** [comment]
I do not believe so. But you can wait to hear from the IM developers.

**Comment by ValZapod** [comment]
There were a lot of bugs in ffmpeg about apng recemtly. Also insane leaks in png decoder itself, in the part of the code that was readinv gAMA and cHRM chunks. See: https://trac.ffmpeg.org/ticket/9017 and https://trac.ffmpeg.org/ticket/8972
