### ISSUE TITLE
JPG to PDF transcode doesn't respect exif orientation data

### ISSUE THREAD

**Issue by ddarfantasy** [ImageMagick/ImageMagick#3502]
### Prerequisites

I have written a descriptive issue title
I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-0

### Operating system

Windows

### Operating system, version and so on

20H2

### Description

If I transcode an jpg file with exif orientation data to pdf, the orientation data is ignored. It's especially inconvenient to rotate manually(which have to depend on each image).

### Steps to Reproduce

I can reproduce it easily. So if you can't, I'll provide more details.

**Comment by ddarfantasy** [comment]
I've also tried to convert it into png/webp and they also show a wrong orientation...
So I think its necessary to first transpose exif orientation then convert to another format.

**Comment by ddarfantasy** [comment]
Adding the `-auto-orient` option solve the problem... Sorry for opening a non-exist issue.

**Comment by ddarfantasy** [comment]
After a second thought, I think it's necessary to make `-auto-orient` a default option for jpg so that there would be less confusion for starters like me.

**Comment by dlemstra** [comment]
We will not automatically change the orientation when we read a JPG image. It will always be read in the orientation that it was in when the image was created. And if you in your use case want it to be in the top left orientation you can use the `-auto-orient` option to rotate the image when that is necessary.

**Comment by fmw42** [comment]
Just always add -auto-orient to your commands when reading jpg to avoid any issues.
