### ISSUE TITLE
convert -resample not working because of Exif data

### ISSUE THREAD

**Issue by dontub** [ImageMagick/ImageMagick#351]
Executing the following command on the attached image under https://cloud.githubusercontent.com/assets/5405481/21811674/d8fa7f56-d750-11e6-8386-feda8ca28bd8.jpg (2,6 KB) fills /tmp and utilizes the CPU to the full:
`convert image.jpg -resample 72x72 result.jpg`

When I save the image without Exif data it works. The Exif data seems to be flawed (multiple entries with the same key):
```
$ exiftool -a image.jpg | grep Resolution
Resolution Unit                 : cm
X Resolution                    : 28
Y Resolution                    : 28
X Resolution                    : 71
Y Resolution                    : 71
Resolution Unit                 : inches
X Resolution                    : 28,346
Y Resolution                    : 28,346
Resolution Unit                 : Centimeter
```

**Comment by dlemstra** [comment]
And your ImageMagick version is? (convert -version)

**Comment by mikayla-grace** [comment]
ImageMagick picks the last instance of the X/Y resolution tag, 28346.  It uses that value to compute the resampling size based on the original image size and determines you want to resize the image to 548064x12456.  It then proceeds to create the image at that size.  If you have enough resources on your system, the command will complete.  You can prevent a possible denial-of-service by setting a maximum image size in your ImageMagick security policy.  Edit policy.xml and add

```
 <policy domain="resource" name="width" value="8192"/>
 <policy domain="resource" name="height" value="8192"/>
```

With this policy, ImageMagick  returns immediately with:

```
convert image.jpg -resample 72x72 result.jpg
convert: width or height exceeds limit `image.jpg' @ error/cache.c/OpenPixelCache/3440.
```

**Comment by dontub** [comment]
I see, ImageMagick's behaviour is correct if the `,` in `28,346` is ignored/treated as thousand separator. I think here it is `28.346` in localized form. So the question is: Should ImageMagick treat `,` as `.` in the resolution?

And for the record: ImageMagick 6.9.7-3 Q16 x86_64

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick within a few days.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ within a few days.
