### ISSUE TITLE
A particular GIF fails to convert, using all CPU and finally crashing with OOM

### ISSUE THREAD

**Issue by dssjoblom** [ImageMagick/ImageMagick#3517]
### Prerequisites

I have written a descriptive issue title
I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I have verified that I am using the latest version of ImageMagick

### ImageMagick version

6.9.10-23 Q16 x86_64 20190101

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04.2 LTS

### Description

The following GIF fails to convert properly: https://privat.rejbrand.se/lorenz50.gif. Convert will use all CPU, process the image for 1-2 minutes and finally exit with an out of memory message:

```
convert-im6.q16: cache resources exhausted `lorenz50-out.gif' @ error/cache.c/OpenPixelCache/4083.
convert-im6.q16: memory allocation failed `lorenz50-out.gif' @ error/quantize.c/AssignImageColors/496. 
```

### Steps to Reproduce

From commandline:

wget https://privat.rejbrand.se/lorenz50.gif
convert lorenz50.gif -auto-orient -coalesce -resize 650x lorenz50-out.gif

NB: I'm not sure if this is the absolutely latest version of ImageMagick, but it is the latest version on the latest Ubuntu.

**Comment by dssjoblom** [comment]
Update: tested with later ImageMagick, 7.0.11-6 Q16 x86_64 2021-03-28, the result is more or less the same, all CPU is consumed, nothing happens. The only difference is that the process is automatically killed by the kernel:

```
[to huhti  8 11:15:20 2021] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=convert,pid=56787,uid=1000
[to huhti  8 11:15:20 2021] Out of memory: Killed process 56787 (convert) total-vm:7158336kB, anon-rss:2893936kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:6136kB oom_score_adj:0
```

**Comment by dssjoblom** [comment]
I'm assuming this is also a security risk since a lot of servers use imagemagick for manipulating images. Uploading this, or another "hostile" image could potentially cause a lot of problems, e.g. on my desktop I was unable to use other software simultaneously since convert used all of the CPU. Feel free to make this issue secret, or whatever process you use for security flaws.

**Comment by dlemstra** [comment]
You probably want to configure the security policy of ImageMagick on the machine that you are testing this: https://imagemagick.org/script/security-policy.php.

**Comment by snibgo** [comment]
With IM v6.9.9-50 and v7.0.8-54 (using "magick" instead of "convert"), the OP command works on my Windows 8.1 laptop without complaint.

**Comment by urban-warrior** [comment]
See https://imagemagick.org/script/architecture.php#tera-pixel.  Utilizing the sage advice, this command should work for you:

```
convert -monitor -limit memory 2GiB -limit map 4GiB -define registry:temporary-path=./ \
   lorenz50.gif -auto-orient -coalesce -resize 650x lorenz50-out.gif

**Comment by dssjoblom** [comment]
@urban-warrior I get the same error with this command (cache resources exhausted / memory allocation failed) on the Ubuntu version, although I suspect that it is indeed because of the policy file that ships with Ubuntu. With ImageMagick compiled from the latest source code, 7.0.11-7 Q16 x86_64 2021-04-11, and without a policy, the command succeeds. Actually, on the custom compiled version, the command succeeds even without the limit options. The version that crashed with OOM was installed via IMEI, https://github.com/SoftCreatR/imei/. Perhaps there is some difference between these versions? Anyway, since this does not look like an issue in the latest version, and might be related to resource limits, it's probably fine to close this.
