### ISSUE TITLE
--with-jxl ignored

### ISSUE THREAD

**Issue by SoftCreatR** [ImageMagick/ImageMagick#3528]
### Prerequisites

I have written a descriptive issue title
I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-6

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04 (64-bit)

### Description

I'm trying to configure IM as follows:

```shell
./configure [...] --with-jxl=yes [...]
```

But it's not recognized:

```
Delegate library configuration:
  [...]
  JPEG XL           --with-jxl=no		no
  [...]
```

I've built JXL as described here: https://gitlab.com/wg1/jpeg-xl and it works fine so far:

```
$# /usr/local/bin/cjxl -h
  J P E G   \/ |
            /\ |_   e n c o d e r    [v0.3.7 | SIMD supported: AVX2,SSE4,Scalar]

Usage: /usr/local/bin/cjxl INPUT OUTPUT [OPTIONS...]
 INPUT
    the input can be PNG, APNG, GIF, JPEG, EXR, PPM, PFM, or PGX
 OUTPUT
    the compressed JXL output file (can be omitted for benchmarking)
 -d maxError, --distance=maxError
    Max. butteraugli distance, lower = higher quality. Range: 0 .. 15.
    0.0 = mathematically lossless. Default for already-lossy input (JPEG/GIF).
    1.0 = visually lossless. Default for other input.
    Recommended range: 0.5 .. 3.0.
 -q QUALITY, --quality=QUALITY
    Quality setting (is remapped to --distance). Range: -inf .. 100.
    100 = mathematically lossless. Default for already-lossy input (JPEG/GIF).
    Positive quality values roughly match libjpeg quality.
 -s EFFORT, --speed=EFFORT
    Encoder effort/speed setting. Valid values are:
    3|falcon| 4|cheetah| 5|hare| 6|wombat| 7|squirrel| 8|kitten| 9|tortoise
    Default: squirrel (7). Values are in order from faster to slower.
 -p, --progressive
    Enable progressive/responsive decoding.
 -v, --verbose
    Verbose output; can be repeated, also applies to help (!).
 -h, --help
    Prints this help message (use -v to see more options).
```

### Steps to Reproduce

(See Description)

**Comment by SoftCreatR** [comment]
Follow up: This also happens on a fresh Debian 10.

**Comment by darrynten** [comment]
Came here to post this

**Comment by dlemstra** [comment]
The jpeg-xl team probably changed their API, and they can because this is an early. We will need to investigate what was changed and apply a patch. ImageMagick works with version 0.3.3 of the library.

**Comment by SoftCreatR** [comment]
But shouldn't it be

```
Delegate library configuration:
  [...]
  JPEG XL           --with-jxl=yes		no
  [...]
```

In this case, regardless of their API? Because that's the expected behavior.

**Comment by dlemstra** [comment]
I am sorry I missed that part. 

I suspect that you are building a `static` build of ImageMagick. In that case the `--with-jxl` option is overruled because the jpeg-xl team does not provide use with a proper `pkg-config` file. We only support this combination when `--without-utilities` is added.

**Comment by SoftCreatR** [comment]
Thank you, `--without-utilities` did the trick. Works with the latest JXL version.

However, I did not explicitly build with `--enable-static`, so I guess, it's default and I would have to build with `--disable-static`?
