### ISSUE TITLE
ImageMagick 7.x / php56-imagick breaking change

### ISSUE THREAD

**Issue by gweiss27** [ImageMagick/ImageMagick#353]
Hi, 

I noticed imagemagick has moved its latest stable built up to 7.x.  I use php56-imagick with imagemagick for my application and that doesnt appear to support the 7.x version.  Is this going to be updated or fixed?

Is there any recommendation about how to get these two to work together now?  I use homebrew so the 7.x version was pushed in my latest update without any other options.

Thanks in advance!

**Comment by mikayla-grace** [comment]
Find ImageMagick version 6 @ http://legacy.imagemagick.org.  It continues to be supported with bug fixes and enhancements.  We did not write nor do we support PHP iMagick.    Hopefully someone from the iMagick community will release a port that supports IMv7 in the near future.

**Comment by Danack** [comment]
Hi guys,

Imagick compiles against both [ImageMagick 6 and 7](https://travis-ci.org/mkoppanen/imagick/builds/192857007) however the compiled code then only runs against the version of ImageMagick it was compiled against.

Mixing and matching library versions does not work.

@gweiss27 - you ought to direct your question to whoever is the package manager for the operating system you use. It is up to them to pick which version of ImageMagick to compile Imagick against.

> I use homebrew so the 7.x version was pushed in my latest update without any other options.

So you're your own package manager then. Have you tried recompiling Imagick?

Regardless - this is not the appropriate place to ask for support for homebrew. Either the homebrew repo, or https://github.com/mkoppanen/imagick would be more appropriate.

cheers
Dan

btw if you want to help out documenting the changes between ImageMagick 6 -> 7 for Imagick users volunteering here would be good: https://github.com/mkoppanen/imagick/issues/162

**Comment by gweiss27** [comment]
I'm not my own package manager.  I have no idea what you are talking about.  I've already reinstalled the legacy 6.x version of ImageMagick to get this to work.  And I certainly do not have the time, expertise, or interest, in documenting changes between IM 6 and 7.  I dont have the slighest idea what those are, just that there are now two version that exist.

I'm sorry you felt my question was so inappropriate.  Sorry to trouble you in my effort to get some help from the open source community.

**Comment by lt** [comment]
@gweiss27 An [issue reported on the homebrew repo](https://github.com/Homebrew/homebrew-php/issues/3916) seems to indicate this is an issue with dependencies on their end.

A quick look at their Formula files shows that php56-imagick requires version 3.3 of the plugin, and ImageMagick 7 support wasn't added until plugin version 3,4

The update needs to come from their end I believe.

**Comment by gweiss27** [comment]
Thank You Leigh!  I appreciate the helpful follow up!

**Comment by Danack** [comment]
> I'm sorry you felt my question was so inappropriate. 

It's not inappropriate. It's inappropriate _here_, as the people here can't help you. 

I've opened an issue in the HomeBrew https://github.com/Homebrew/homebrew-php/issues/3919 as the people there should be able to help you.


> I certainly do not have the time, expertise, or interest, in documenting changes between IM 6 and 7.
> Sorry to trouble you in my effort to get some help from the open source community.

I'm troubled by people who want stuff from the open source community, but then point blank refuse to give anything back.

**Comment by gweiss27** [comment]
Its a very rude way to respond to a professional on a public site.  That’s how you talk to an 8 year old who’s misbehaving in a restaurant, not a professional peer and certainly not to someone you don’t even know.

I have helped on a number of open source projects and will continue to do so for the ones I use and have experience with.

I don’t know Imagemagick 7.x.  I have never used it.  I have never looked at the codebase.  I don’t have the slightest ideas what the differences are, expect that the 7.x version seems to use php70 which is something I’ve never used.  I know what I need from ImageMagick/Imagick to meet my needs for one of my projects.

You need to think very carefully about how you communicate with people.  I would never talk to anyone like this and my direct response to you was because I was unnecessarily offended by your remarks.  When I respond to people I either offer very concrete helpful answers to their questions or I simply don’t remark at all.

People aren’t interested, nor do they have time for you rude opinions.  It’s very unprofessional.
