### ISSUE TITLE
Processing DPX removes last byte of some header data entries

### ISSUE THREAD

**Issue by ChristyKail** [ImageMagick/ImageMagick#3537]
### Prerequisites

I have written a descriptive issue title
I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-6

### Operating system

MacOS

### Operating system, version and so on

10.15.7 Catalina

### Description

I'm attempting to do a batch resize on a DPX sequence using the following Imagemagicks command:

`magick test.dpx -resize 2076x1186 test_2k.dpx`

However, when I do, various pieces of the embedded metadata have their last character removed, most noticeably in my use case the ones listed below:

- dpx:film.count
- dpx:film.id
- dpx:film.offset
- dpx:film.prefix
- dpx:film.type

The relevant output of an `identify` command from both the original and converted files is below:

```
Original: 
dpx:film.count: 8350
dpx:film.format: 003F
dpx:film.frame_position: 86410
dpx:film.frame_rate: 24
dpx:film.id: 02
dpx:film.offset: 08
dpx:film.prefix: 048832
dpx:film.shutter_angle: nan
dpx:film.type: 07`

Modified: 
dpx:film.count: 835
dpx:film.format: 003F
dpx:film.frame_position: 86410
dpx:film.frame_rate: 24
dpx:film.held_count: 0
dpx:film.id: 0
dpx:film.offset: 0
dpx:film.prefix: 04883
dpx:film.sequence_extent: 0
dpx:film.shutter_angle: nan
dpx:film.type: 0
```

Performing the same operation in GraphicsMagick did not show this behaviour, so I believe this may be a bug.

### Steps to Reproduce

Get file metadata using `magick identify -verbose test.dpx`

Convert the file using `magick test.dpx -resize 2076x1186 test_2k.dpx`or similar

Get new file metadata using `magick identify -verbose test_2k.dpx` and compare results.

**Comment by fmw42** [comment]
Can you provide your dpx image? You can zip it and then upload it in your post.

**Comment by ChristyKail** [comment]
> Can you provide your dpx image? You can zip it and then upload it in your post.

Unfortunately the DPXs I've been testing on are too large for GitHub upload, see Google Drive link here: https://drive.google.com/drive/folders/1F9hI9I8pyZ2BjM-vag-gcKckl4ldSIqR?usp=sharing

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
