### ISSUE TITLE
Resizing GIF with both -coalesce and -deconstruct produces broken output

### ISSUE THREAD

**Issue by dfedorin** [ImageMagick/ImageMagick#3545]
### Prerequisites

I have written a descriptive issue title
I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageMagick version

7.0.10-Q16-HDRI

### Operating system

Windows

### Operating system, version and so on

windows 7 x86-64

### Description

For some GIFs using both -coalesce and -deconstruct produce broken output

### Steps to Reproduce

For attached image
1. magick convert gif-2.gif -coalesce -resize 181x200 -deconstruct bad.gif - produce broken GIF
2. magick convert gif-2.gif -coalesce -resize 181x200 inter.gif 
    magick convert inter.gif -deconstruct good.gif - produce good GIF

**Comment by dfedorin** [comment]
[images.zip](https://github.com/ImageMagick/ImageMagick/files/6309720/images.zip)

**Comment by urban-warrior** [comment]
Try upgrading.  We're using ImageMagick 7.0.11-8 and getting identical results from your two command-line scripts.

**Comment by dfedorin** [comment]
Where do i get 7.0.11-8? Download links here https://imagemagick.org/script/download.php#windows are broken

**Comment by fmw42** [comment]
See https://imagemagick.org/script/download.php#windows

**Comment by dfedorin** [comment]
No luck with 7.0.11-8. Fifth and sixth frames still appear to be cropped from the left.
![bad2](https://user-images.githubusercontent.com/11648378/115123827-8a263480-9fc7-11eb-9386-31a49f078b11.gif)

**Comment by urban-warrior** [comment]
Try this command:

```
magick convert gif-2.gif -coalesce -resize 181x200 -type palette-bilevel-alpha -layers CompareAny good.gif
```

**Comment by dfedorin** [comment]
Yeah, this one works. But why change of image type affects -deconstruct?

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by fmw42** [comment]
FYI: This does not make a good gif for me on IM 7.0.11.8 Q16 Mac OSX Sierra

```
magick gif-2.gif -coalesce tmp.gif
magick tmp.gif -layers CompareAny x1.gif

```

I also note from the following that gif-2.gif seems to be coalesced already:

i```
dentify gif-2.gif
gif-2.gif[0] GIF 318x350 318x350+0+0 8-bit sRGB 128c 0.000u 0:00.001
gif-2.gif[1] GIF 318x350 318x350+0+0 8-bit sRGB 128c 0.000u 0:00.001
gif-2.gif[2] GIF 318x350 318x350+0+0 8-bit sRGB 128c 0.000u 0:00.001
gif-2.gif[3] GIF 318x350 318x350+0+0 8-bit sRGB 128c 0.000u 0:00.001
gif-2.gif[4] GIF 318x350 318x350+0+0 8-bit sRGB 128c 0.000u 0:00.001
gif-2.gif[5] GIF 318x350 318x350+0+0 8-bit sRGB 128c 0.000u 0:00.001
gif-2.gif[6] GIF 318x350 318x350+0+0 8-bit sRGB 128c 0.000u 0:00.001
gif-2.gif[7] GIF 318x350 318x350+0+0 8-bit sRGB 128c 0.000u 0:00.000
gif-2.gif[8] GIF 318x350 318x350+0+0 8-bit sRGB 128c 0.000u 0:00.000
gif-2.gif[9] GIF 318x350 318x350+0+0 8-bit sRGB 128c 164566B 0.000u 0:00.000

```

So the simplest command

magick gif-2.gif -layers CompareAny x1.gif

produces a bad gif. But if the image is coalesced, why is it doing anything.

**Comment by urban-warrior** [comment]
ImageMagick is behaving as designed and documented @ https://legacy.imagemagick.org/Usage/anim_basics/#deconstruct:

> Unfortunately "-deconstruct" has absolutely no understanding of the GIF animation "-dispose" settings. Consequently if you try this on an animation that clears pixels from one frame to the next, such as the 'background disposed' animation we created above (and shown left), it will fail badly... Basically "-deconstruct" is designed to simply find the differences between image layers. It was never designed to correctly optimize animations, and will fail for animations that need to use various disposal techniques to clear (erase or make transparent) previously overlaid pixels.
