### ISSUE TITLE
convert command no longer works in latest version

### ISSUE THREAD

**Issue by chowbok** [ImageMagick/ImageMagick#3549]
### Prerequisites

I have written a descriptive issue title
I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-7

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

I've been running the following command with no problems until the upgrade to 7.0.11-7:

`convert \( cover/1723.png -bordercolor none -background none -rotate -10 -repage +57+57 \) -colorspace sRGB -layers merge \( cover/1724.png -bordercolor none -background none -rotate +21 -repage -43+61 \) -colorspace sRGB -layers merge \( cover/1722.png -bordercolor none -background none -rotate -10 -repage +21-43 \) -colorspace sRGB -layers merge +repage -colorspace sRGB -flatten +repage -background black \( +clone -shadow 60x4+4+4 \) +swap -background none -colorspace sRGB -flatten -interlace Line output.png`

Now I get the following errors, and the output image is empty:

`convert: invalid image index 'cover/1723.png' @ error/list.c/CloneImages/282.`
`convert: no such image '+clone' @ error/convert.c/ConvertImageCommand/1027.`

### Steps to Reproduce

See above.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by chowbok** [comment]
Works in latest git, thanks very much.
