### ISSUE TITLE
Metafile conversion results in strange text when running in container

### ISSUE THREAD

**Issue by FrankAtHexagon** [ImageMagick/ImageMagick#3555]
### Prerequisites

I have written a descriptive issue title
I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-7

### Operating system

Windows

### Operating system, version and so on

Windows 10 20H2

### Description

When converting an enhanced metafile (EMF) to a PNG image using Magick++ while running in a Windows container, any text looks very strange. Almost like it has a 1960's psychedelic effect applied. The text appears normal when the conversion is done while running outside of a container.

### Steps to Reproduce

Steps.
* Obtain enhanced metafile (EMF) with text
* Use Magick++ to convert EMF to PNG

Sample code.

```cpp

// Read EMF into blob here...

Image image;
image.magick("EMF");
image.read(emfBlob);

Blob pngBlob;
image.magick("PNG");
image.write(&pngBlob);

// Write PNG to file here...
```

### Images
![image](https://user-images.githubusercontent.com/47671460/114880318-95127680-9dc7-11eb-89b0-1b72c3673291.png)

**Comment by dlemstra** [comment]
Please also attach your EMF file that can be used to reproduce this issue.

**Comment by FrankAtHexagon** [comment]
Here you go. GitHub doesn't support files with the `.emf` extension so I simply changed the extension to `.png`. The content of the file is what you'd get from `GetEnhMetaFileBits`.

![example](https://user-images.githubusercontent.com/47671460/114885278-1bc95280-9dcc-11eb-8155-805bbdd4b632.png)

**Comment by dlemstra** [comment]
I am unable to reproduce your issue with the latest release. I get the following output:

![test](https://user-images.githubusercontent.com/10426229/115140767-410ec880-a039-11eb-8abc-74b556273bc7.png)

Maybe the Windows GDI library that we are using is unable to load the fonts in your container?

**Comment by FrankAtHexagon** [comment]
Thank you for looking into this. Have you tried reproducing the issue while running in a container? I get the same output as you when running outside of a container. I'm happy to help if needed.

**Comment by dlemstra** [comment]
I suspect it has to do with the container that you decided to use. What is your base image / Dockerfile?

**Comment by FrankAtHexagon** [comment]
Our base image is `mcr.microsoft.com/windows/servercore:1809`.

**Comment by FrankAtHexagon** [comment]
A friend of mine tried changing our base image to `mcr.microsoft.com/windows:1809`, which resulted in a much better image. So it seems like your theory is correct!

**Comment by FrankAtHexagon** [comment]
Good morning. We'll take a look at this and post back an update in about a week or two.

**Comment by FrankAtHexagon** [comment]
Unfortunately, the problem does not seem to be the fonts. I used the Dockerfile `COPY` command to move all fonts from `C:\Windows\Fonts` on my machine to the corresponding folder on the `mcr.microsoft.com/windows/servercore:1809` image.

However, since we have a viable workaround using the much larger `mcr.microsoft.com/windows:1809` image, I think we can close the issue. Thanks for all your help @dlemstra, I really do appreciate it. I hope you have a great day!
