### ISSUE TITLE
JPEG transformation with embedded color profiles has inverted colors

### ISSUE THREAD

**Issue by bvb-sc** [ImageMagick/ImageMagick#3556]
### Prerequisites

I have written a descriptive issue title
I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-7

### Operating system

Linux

### Operating system, version and so on

Ubuntu Focal 20.04

### Description

We have a bunch of JPEG files that have an embedded `Coated Fogra 27` color profile. We are trying to resave these and embed an `sRGB` color profile instead. When we do this, the colors in the output images become seemingly inverted.

E.g.

![image](https://user-images.githubusercontent.com/67702686/114884822-5f40b280-9e06-11eb-88a2-dbacb26a6596.png)

One thing we noticed about the input files, is that despite them having an embedded `CMYK` color profile, they are still marked as having colorspace `sRGB`, which is not what we expect.

### Steps to Reproduce

With the files attached below, execute the following command:

```
convert -density 72 "input.jpg[0]" -strip  +profile icm,icc -profile "<path>/CoatedFOGRA27.icc" -profile "<path>/sRGB.icc"  -resize "1100x1100>"  -alpha remove -background white -auto-orient  "output.jpg"
```

Notice that the output files do not have correct colors.

### Images

Files: [files.zip](https://github.com/ImageMagick/ImageMagick/files/6318699/files.zip)

**Comment by fmw42** [comment]
There is something strange about your jpg file. If I do a simple write of input to output, it still inverts.

![1before](https://user-images.githubusercontent.com/13458218/114898070-a909a880-9dc6-11eb-843d-29d5ad0d8c57.jpg)


`magick 1before.jpg x.jpg
`

![x](https://user-images.githubusercontent.com/13458218/114898019-9f804080-9dc6-11eb-9a28-517c51d05f2b.png)

Imagemagick sees it as RGB with color profile.  You are converting to CMYK and then back to RGB with profiles.

There seems to be a lot of Photoshop processing.

EXIFTOOL says it is CMYK in one place

16 ColorSpaceData                  : CMYK

and in another

262 PhotometricInterpretation       : 2  (which is RGB)

It also says

40961 ColorSpace                      : 65535

and

ColorComponents                 : 3 (so possibly RGB)

I suspect that your image might be CMYK but labeled as RGB.  But I am not an expert on this and so will leave to the IM developers or others.

**Comment by snibgo** [comment]
As fmw42 says, your "before" jpegs have RGB channels, not CMYK channels. So they should not have embedded CMYK ICC profiles, and stripping then re-assigning CMYK profiles, as your command does, is wrong.

**Comment by bvb-sc** [comment]
Thanks for the feedback!
