### ISSUE TITLE
you break ABI

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#356]
Hi,

You have break ABI for libmagick++ could you revert the breaking change ?

https://abi-laboratory.pro/tracker/objects_report/imagemagick/6.9.7-2/6.9.7-3/report.html

**Comment by bastien-roucaries** [comment]
And made a release ASAP in order to avoid problems

**Comment by dlemstra** [comment]
The method has been in the same order for ages. This was the file in 2009: https://github.com/ImageMagick/ImageMagick/blob/3ed852eea50f9d4cd633efb8c2b054b8e33c2530/Magick%2B%2B/lib/Magick%2B%2B/Drawable.h#L125. It looks like a bug in the tool.

**Comment by bastien-roucaries** [comment]
It likely a bug. maybe in g++
