### ISSUE TITLE
Cannot convert SVG to PNG using Inkscape 1.0.2

### ISSUE THREAD

**Issue by yaqwsx** [ImageMagick/ImageMagick#3564]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [ ] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

6.9.10 (but according to the source affects also 7.X.X)

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04

### Description

The delegate for Inkscape does not work properly on Inkscape 1.X.X. Moving from Inkscape 0.9X to 1.X.X the meaning of the command line switches has changed.

Instead of `--export-png` there is `--export-filename`. However, the simple change as https://github.com/ImageMagick/ImageMagick/discussions/1880 proposes does not work. Inkscape tries to guess the filename type from the extension, which is, however, absent in the command invoked by ImageMagick (due to the temporary symlink). When the switch `--export-type=png` is added, Inkscape adds a suffix `.png` to the output filename which breaks ImageMagick.

My current workaround is to create a wrapper script;
```
#!/usr/bin/env sh

# Arguments are
# - input
# - output
# - DPI
# - BG
# - BG opacity

TMP=$(mktemp --suffix=.png)

inkscape $1 "--export-filename=$TMP" "--export-dpi=$3" "--export-background=$4" "--export-background-opacity=$5"
mv $TMP $2
```

and change the delegate to:
```
  <delegate decode="svg:decode" stealth="True" command="inkscapeWrapper.sh &quot;%s&quot; &quot;%s&quot; &quot;%s&quot; &quot;%s&quot; &quot;%s&quot;  &gt; &quot;%s&quot; 2&gt;&amp;1"/>
```

However, this solution is rather poor. If I understand correctly, there is no way to specify such delegate directly in the XML without a wrapper script. I guess it would be much better if ImageMagick would be able to append a proper suffix to the output filename.

Related: 
- https://github.com/ImageMagick/ImageMagick/discussions/1880
- https://github.com/ImageMagick/ImageMagick/issues/2489
- https://github.com/ImageMagick/ImageMagick/issues/2996

PS: Is there a command-line option to see stdout and stderr of the delegate when invoking `convert`? I had to remove the stdout and stderr redirection from the delegate in order to debug this.

### Steps to Reproduce

- Install Inkscape 1.0.2
- invoke `convert -verbose <someSVG> <somePNG>`
- observe, that invocation of Inkscape fails and MVG converter is used instead.

**Comment by urban-warrior** [comment]
Try the latest release of ImageMagick, 6.9.12-8.  It has a patch for this issue.

**Comment by yaqwsx** [comment]
Thanks, I confirm that it works with 6.9.12-8. Thank you for your quick response.
