### ISSUE TITLE
When resizing APNG file via ffmpeg (magick: delegate failed `"ffmpeg.exe" -nostdin...)

### ISSUE THREAD

**Issue by JohnLuCN** [ImageMagick/ImageMagick#3565]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

ImageMagick 7.0.11-0 Q16 x64 2021-02-13

### Operating system

Windows

### Operating system, version and so on

Microsoft Windows [Version 10.0.19042.928]

### Description

When I was trying to resize APNG file, I would encounter the delegation error as below. Have tried to search history articles, but no similar issue reported. Would you please help to have a look and possibly provide some solution?

=>magick: delegate failed `"ffmpeg.exe" -nostdin -v -1 -i "%M%%d.pam" -plays %I "%u.%m"' @ error/delegate.c/InvokeDelegate/1907.

### Steps to Reproduce

magick apng:tmp.png -resize 520x520 apng:test1.png
=>magick: delegate failed `"ffmpeg.exe" -nostdin -v -1 -i "%M%%d.pam" -plays %I "%u.%m"' @ error/delegate.c/InvokeDelegate/1907.

**Comment by urban-warrior** [comment]
@dlemstra, can you try this command under Windows?  We get expected results on our Fedora system.

**Comment by dlemstra** [comment]
I can take a look but I am going to need a test image from @JohnLuCN.

**Comment by JohnLuCN** [comment]
Dear @dlemstra ,
Below is a test image you can use for trial.
![test](https://user-images.githubusercontent.com/24828239/117250736-3f853300-ae76-11eb-9237-9848970ed50d.png)

And regarding this issue:
- The command need to be changed to "magick apng:tmp.png -resize 520x520 **test1.apng**" (To avoid error message)
1. But the output is in black background
2. The file name suffix will be "**apng**"
3. The **frame rate** is different with the original one

- In order to solve above problems, I have found the way out, below is the specific solution and script I wrote for your reference, which as tested, is working as expected.

1. https://github.com/JohnLuCN/APNGResizer

**Comment by dlemstra** [comment]
I the next version of ImageMagick we will read this image with the alpha channel enabled. It turns out that we need to pass an extra paramater to the `ffmpeg` executable to get an output image that has an alpha channel.
