### ISSUE TITLE
Uncaught ImagickException: UnableToOpenBlob 'file.pdf'

### ISSUE THREAD

**Issue by tmwebs** [ImageMagick/ImageMagick#3569]
![Captura](https://user-images.githubusercontent.com/12540076/115391121-63424b00-a1df-11eb-8aa7-df1f4ef54f7f.png)
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-Q16

### Operating system

Windows

### Operating system, version and so on

Windows Server 2016

### Description

I have ImageMagick installed, and from the windows console it works fine, but when I run it from PHP I get the error 

> Fatal error: Uncaught ImagickException: UnableToOpenBlob 'file.pdf': No such file or directory @ error/blob.c/OpenBlob/3315

The file I have it in the root folder, and says it can not find it. I do not see where the problem is, have the environment variable configured and it seems that it is well installed in php, attached image.

I also have Ghostscript installed

### Steps to Reproduce

```
$imagick = new Imagick();
$imagick->readImage("file.pdf"); 

### Images

![Captura de pantalla 2021-04-20 a las 13 43 57](https://user-images.githubusercontent.com/12540076/115391034-46a61300-a1df-11eb-8fda-e76ee5e1b397.png)

**Comment by tmwebs** [comment]
I found the problem, I had to rename gswin64.exe to gs.exe.

Thank you.

**Comment by terryb58** [comment]
I don't have that file and I'm encountering this problem. What else can be causing it?

**Comment by dlemstra** [comment]
You probably did not install Ghostscript on your system.
