### ISSUE TITLE
Differences in computing linear gray

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#3571]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11.8 Q16

### Operating system

MacOS

### Operating system, version and so on

Sierra

### Description

According to https://imagemagick.org/script/command-line-options.php#grayscale, these three methods should produce the same linear result. **Is the documentation in error?**

The first one is clearly not linear as it is too bright. The next two are similar, but show difference when viewing by alternating and also from compare.

Input:

![lena](https://user-images.githubusercontent.com/13458218/115601512-c17c3600-a292-11eb-83b7-8de3bfbc4701.png)

`magick lena.png -colorspace rgb -colorspace gray lena_rgb_gray.png`

![lena_rgb_gray](https://user-images.githubusercontent.com/13458218/115602275-9a723400-a293-11eb-9bb8-5828397aecfe.png)

`magick lena.png -colorspace lineargray lena_linear_gray.png`

![lena_linear_gray](https://user-images.githubusercontent.com/13458218/115601747-00aa8700-a293-11eb-9d80-17744fec517e.png)

`magick lena.png -grayscale Rec709Luminance lena_r709Luminance.png`

![lena_r709luminance](https://user-images.githubusercontent.com/13458218/115601887-2a63ae00-a293-11eb-9e0c-6d13b17c2252.png)

`magick compare -metric rmse lena_linear_gray.png lena_r709luminance.png null:`
1649.58 (0.0251709)

### Steps to Reproduce

See above

### Images

See above

**Comment by snibgo** [comment]
In your command...
```
magick lena.png -colorspace rgb -colorspace gray lena_rgb_gray.png
```
... converts to one colourspace (which happens to be linear RGB), then to another (gray). So converting to the first colourspace has no overall effect. The result is "gray", which is non-linear gray. In that respect, the documentation is wrong.

Your command...
```
magick lena.png -colorspace lineargray lena_linear_gray.png
```
... work as expected. The mean value is 0.21885 (on a scale of 0 to 1), compared to 0.457852 for the non-linear version. But it looks the same, with Firefox on my computer. Why does they look the same? Because Firefox recognises that the linear version (with gamma=1) is in the wrong colourspace for my screen, which is sRGB, so Firefox converts the image before displaying it.

**Comment by fmw42** [comment]
The second and third commands are supposedly the same according to the docs, but produce somewhat different results according to compare (as well as visually).

I was suspicious of the first command, since it converts to linear (rgb) and then back to non-linear (gray). But at one time IM worked to do that the same as the second and third commands.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
