### ISSUE TITLE
convert a psd to pdf got empty pdf file

### ISSUE THREAD

**Issue by KngStr** [ImageMagick/ImageMagick#3574]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

ImageMagick-7.0.11-8-portable-Q16-x64

### Operating system

Windows

### Operating system, version and so on

Windows 7 x64 Enterprise sp1

### Description

When I tried to convert a psd file to pdf, it got empty pdf.
And I tried to convert this psd to jpg or tif, it's ok.

### Steps to Reproduce

Use the command line: `convert 1.psd 1.pdf`

### Images
[1.psd.zip](https://github.com/ImageMagick/ImageMagick/files/6357038/1.psd.zip)

**Comment by snibgo** [comment]
Try "-strip" after reading the psd:
```
convert 1.psd -strip 1.pdf
```

**Comment by KngStr** [comment]
@snibgo  Thanks.
But how can I know which file should use `strip`

**Comment by dlemstra** [comment]
It looks like this problem was also fixed in issue #2070. This will be resolved in the next release of ImageMagick.

**Comment by KngStr** [comment]
Thanks very much.
