### ISSUE TITLE
Wand 0.4.4 

### ISSUE THREAD

**Issue by F10CH** [ImageMagick/ImageMagick#360]
I encounter an issue using ImageMagick 7 with Wand 0.4.4 (python 3.6).
Does something change in the libraries ?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/wand/api.py", line 180, in <module>
    libraries = load_library()
  File "/usr/local/lib/python3.6/site-packages/wand/api.py", line 135, in load_library
    raise IOError('cannot find library; tried paths: ' + repr(tried_paths))
OSError: cannot find library; tried paths: []
```
See [https://github.com/dahlia/wand/issues/316](https://github.com/dahlia/wand/issues/316)

**Comment by mikayla-grace** [comment]
We cannot help.  We did not write nor do we support Wand 0.4.4.  Perhaps this extension requires version 6 of ImageMagick and has not yet been ported to ImageMagick version 7.

**Comment by amyrebecca** [comment]
Downgrading to imagemagick 6.x fixed this for me.
