### ISSUE TITLE
Color channel issue after resize DDS (BC 2-3 normal map with alpha) 

### ISSUE THREAD

**Issue by Bxaa** [ImageMagick/ImageMagick#3606]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-9 portable-Q16-HDRI-x64

### Operating system

Windows

### Operating system, version and so on

Win10x64

### Description

premultiplied alpha? (alpha cutoff)?
How to disable it while resize dds with alpha?

### Steps to Reproduce

convert -colorspace RGB -define filter:Lanczos -resize 1024^>x1024^> "test.dds" -colorspace srgb "test.dds

TEST DDS:
https://drive.google.com/file/d/1ryfz08wi8iZBskW2dXffCyr_hdTa3Qxi/view?usp=sharing

<a href="https://ibb.co/2jjWj7q"><img src="https://i.ibb.co/2jjWj7q/Broken-color-channel.jpg" alt="Broken-color-channel" border="0"></a> <a href="https://ibb.co/gmVhtZY"><img src="https://i.ibb.co/gmVhtZY/Normal.jpg" alt="Normal" border="0"></a>
ALPHA:
<a href="https://ibb.co/6sGnczp"><img src="https://i.ibb.co/6sGnczp/alpha.jpg" alt="alpha" border="0"></a>

**Comment by fmw42** [comment]
What version of Imagemagick? Assuming Imagemagick 6, then did you try using -alpha off at the beginning and then -alpha on at the end.

**Comment by Bxaa** [comment]
Used:
ImageMagick 7.0.11-9 portable-Q16-HDRI-x64

I'll try right now and report

**Comment by fmw42** [comment]
For Imagemagick 7, use magick, not convert.  But -alpha off and -alpha on do not work on IM 7 in the same way they did in IM 6. Try -channel rgb at the beginning and then -channel rgba at the end. Not sure that will will either, but you can try it.

**Comment by Bxaa** [comment]
magick do equal bug
Also -channel rgb rgba not work

**Comment by Bxaa** [comment]
I think this is a  bug  with alpha background

**Comment by Bxaa** [comment]
Do you have installed imagemagick?
If... try my dds and 
convert -colorspace RGB -define filter:Lanczos -resize 1024^>x1024^> "test.dds" -colorspace srgb "test.dds"
May be this issue with my version only...

**Comment by fmw42** [comment]
This works for me on IM 6.9.12.9 Q16 Mac OSX.

`convert "DDS:test.dds" -alpha off -colorspace RGB -define filter:Lanczos -resize "1024x1024>" -colorspace srgb -alpha on "DDS:test2.dds"`

When I do:

`display -alpha off test2.dds`

it looks the same as with

`display -alpha off test1.dds`

The equivalent, I believe, in IM 7 would be

magick "DDS:test.dds" -alpha activate -colorspace RGB -define filter:Lanczos -resize "1024x1024>" -colorspace srgb -alpha deactivate "DDS:test2.dds"

but that does not seem to work.  One way to deal with it would be to separate the alpha channel, do your processing and then put it back again.

**Comment by Bxaa** [comment]
> but that does not seem to work. One way to deal with it would be to separate the alpha channel, do your processing and then put it back again.
Bad idea because this texture is normal map. It already was separated  and rebuilded. (after -compose copyopacity -composite operations black color start shift and need recalculate)

Wrong rendering in game without it.
-type grayscale -level-colors rgb(6,6,6),white -blur 1x1 -black-threshold -black-threshold 2.4%
I have 76k such textures and resizing 76k x2...:)

Seems to be i'll use texconv for resize twithout Lanczos :(

**Comment by Bxaa** [comment]
I found solution
Using -separate and -combine
Notice: -separate before colorspace only!
