### ISSUE TITLE
file converted from tga to png fails in libpng "not a PNG file"

### ISSUE THREAD

**Issue by ChefNiko** [ImageMagick/ImageMagick#3612]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-10 Q16

### Operating system

Linux

### Operating system, version and so on

5.8.0-51-generic #57-Ubuntu SMP

### Description

```
($) ~/cursors/test: convert Cursor.tga default.png
($) ~/cursors/test: xcursorgen default.cursor default
libpng error: Not a PNG file
xcursorgen: PNG error while reading default.png
```

Additionally, Firefox displays "The image <image> cannot be displayed, because it contains errors."

### Steps to Reproduce

Steps listed above.

### Images

[images.tar.gz](https://github.com/ImageMagick/ImageMagick/files/6398719/images.tar.gz)

**Comment by fmw42** [comment]
Your command works fine for me on IM 7.0.11.9 Q16 Mac OSX Sierra. No problem with the png. What is your version of libpng?

Note that with IM 7, use magick not convert.

**Comment by ChefNiko** [comment]
Thanks, I tried using magick instead of convert, but it still didn't work for me.

libpng 1.6.37

**Comment by dlemstra** [comment]
What is the output of `magick -version`? I suspect that you have build ImageMagick without png support.
