### ISSUE TITLE
SVG to PNG conversion glitches using Inkscape

### ISSUE THREAD

**Issue by raffaem** [ImageMagick/ImageMagick#3613]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-6

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.10

### Description

Converting a SVG image to PNG image using the Inkscape backend results in glitches.

Using Inkscape directly results in no glitches instead.

### Steps to Reproduce

1. `wget https://upload.wikimedia.org/wikipedia/commons/1/1a/Boxplot_vs_PDF.svg`

2. `$HOME/bin/magick convert -verbose Boxplot_vs_PDF.svg magick.png`
     > 'inkscape' '/tmp/magick-_PEmJ1f87-JIotICD-uV0S_RcpthoJSO' --export-filename='/tmp/magick-9z95nBo0Bj8LPZh1Dh-Jl9s1QbkGT6zN.png' --export-dpi='96' --export-background='rgb(100%,100%,100%)' --export-background-opacity='0.99999999999900002212' > '/tmp/magick-CizO3zORe7rHzTUmm9Fy4FuSkl23OWmO' 2>&1
mvg:/tmp/magick-hHXMc6Y6As_TmUkxFjWPju2MK-TED2iQ=>/tmp/magick-hHXMc6Y6As_TmUkxFjWPju2MK-TED2iQ MVG 598x652 598x652+0+0 16-bit sRGB 496963B 2.350u 0:01.983
Boxplot_vs_PDF.svg SVG 598x652 598x652+0+0 16-bit sRGB 496963B 0.000u 0:00.000
Boxplot_vs_PDF.svg=>magick.png SVG 598x652 598x652+0+0 16-bit sRGB 496963B 0.190u 0:00.072
    
    Open the file and see the glitches
    ![image](https://user-images.githubusercontent.com/54762742/116648187-b739f600-a97c-11eb-9e8d-e0634a95633e.png)

3. `inkscape --without-gui Boxplot_vs_PDF.svg -w 800 -h 800 -o inkscape.png`
No glitches in resulting file
![image](https://user-images.githubusercontent.com/54762742/116648399-329ba780-a97d-11eb-837c-ddb27709a1d0.png)

### Images

[Boxplot_vs_PDF.zip](https://github.com/ImageMagick/ImageMagick/files/6402977/Boxplot_vs_PDF.zip)
![magick](https://user-images.githubusercontent.com/54762742/116648160-a7221680-a97c-11eb-8f0f-7dd1f996aecd.png)
![inkscape](https://user-images.githubusercontent.com/54762742/116648314-01bb7280-a97d-11eb-8c5f-a11aeeaa79da.png)

**Comment by urban-warrior** [comment]
What version of `inkscape` are you using?  We're using inkscape 1.0.2 and get expected results (i.e. no glitches).

**Comment by raffaem** [comment]
```
$ inkscape --version
Gtk-Message: 12:55:42.612: Failed to load module "appmenu-gtk-module"
Inkscape 1.0.1 (3bc2e813f5, 2020-09-07)
    Pango version: 1.46.2
```

Are we sure that ImageMagick is using the inkscape rendering on my system?

(who is "we"?)

**Comment by snibgo** [comment]
ImageMagick calls the Inkscape executable that is on your system path. Inkscape is not embedded in ImageMagick.

Your "-verbose" shows the arguments that IM passes to Inkscape. These include:
```
--export-dpi='96' --export-background='rgb(100%,100%,100%)' --export-background-opacity='0.99999999999900002212'
```
... which you did not include in your "inkscape" command. What happens when you do include them?

I makes a temporary copy of your SVG input, and passes this to Inkscape. There may be a bug in the copying process.

You show an example of a "glitch", but I don't see what is wrong with it.
