### ISSUE TITLE
Ashlar pseudo-image format crops labels in last row of tiles by default

### ISSUE THREAD

**Issue by imdn** [ImageMagick/ImageMagick#3618]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-6 Q16 x86_64 2021-04-24 

### Operating system

Linux

### Operating system, version and so on

Arch Linux on kernel 5.10.32-1-lts

### Description

When using the Ashlar pseudo-format to create a montage with labels for individual tiles, labels on the last line are cropped. This was tested on several different datasets with the same resulting effect.

### Steps to Reproduce

1. Use a dataset with a considerable number of images. E.g. the Yale Face Database with 166 images (http://vision.ucsd.edu/datasets/yale_face_dataset_original/yalefaces.zip). Unzip into a directory and remove non-image files.
2. Create a montage with the Ashlar pseudo-image format (resize large images if necessary, to avoid running out of memory)
`magick * -label %f 'ashlar:test.jpg'`
3. Examine the last row of tiles on the resulting `test.jpg` . The labels are cropped. (see image attached to this issue)

### Images

![collage](https://user-images.githubusercontent.com/700275/116809392-1c891500-ab3e-11eb-8187-5715cc29ce62.jpg)

**Comment by imdn** [comment]
changed wording - 'truncated' -> 'cropped'

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by imdn** [comment]
I'm afraid the patch does not work as expected. The labels are still cropped.

I built ImageMagick from Git  (ImageMagick 7.0.11-12 Q16 x86_64 2021-05-06).

Can you please confirm the same?

**Comment by urban-warrior** [comment]
Try the latest main branch again.  Hopefully this patch will resolve the issue.

**Comment by imdn** [comment]
Amen ... it is working as it should now. I will close the issue.

Thanks for the speedy fix!
