### ISSUE TITLE
1 FAILure during make operation

### ISSUE THREAD

**Issue by HAUSEVULT** [ImageMagick/ImageMagick#3648]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-12

### Operating system

Linux

### Operating system, version and so on

Arch Linux, 5.11.16-arch1-1

### Description

Because all mirrors for Imagemagick appear to no longer host its files, I followed the compilation instructions over at [https://imagemagick.org/script/install-source.php](the imagemagick website):

```
./configure --with-modules
make
sudo make install
```
I ran ```make check``` as recommended to check whether or not Imagemagick had been successfully installed. Here is a sample of the log file, which I have also included as an attachment.
```
============================================================================
Testsuite summary for ImageMagick 7.0.11-12
============================================================================
# TOTAL: 86
# PASS:  85
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See ./test-suite.log
Please report to https://github.com/ImageMagick/ImageMagick/issues
============================================================================
```
Unsure what the issue is. Here's your bug report.
[test-suite.log](https://github.com/ImageMagick/ImageMagick/files/6444960/test-suite.log)

### Steps to Reproduce

```
./configure --with-modules
make
sudo make install
```

**Comment by urban-warrior** [comment]
You are missing the Helvetica font on your system.  ImageMagick works fine without it, but it is required for the unit tests to pass.  Install Ghostscript and Ghostscript fonts and try the unit tests again.
