### ISSUE TITLE
"-extent" doesn't work with "-background transparent"

### ISSUE THREAD

**Issue by njdoyle** [ImageMagick/ImageMagick#365]
Using `-extent` with `-background transparent` creates a completely transparent image instead of just filling new pixels with transparency.

Here is an example of the problem:
`convert logo: -background transparent -gravity Center -extent 640x640 logo.png`

I can confirm this used to work in 6.9.5-10 and can confirm that it is broken in 7.0.3-10.

I have been able to work around the problem by using `-compose dst-over` but this should not be necessary.

**Comment by dlemstra** [comment]
I cannot reproduce the issue with the latest version of ImageMagick. Have you tried upgrading?

**Comment by njdoyle** [comment]
You're right, the issue isn't present in 7.0.4-6.

I never pick up a non "-10" version because the downloads always disappear from under me. :(
