### ISSUE TITLE
Outputting TIFF over STDOUT fails

### ISSUE THREAD

**Issue by njdoyle** [ImageMagick/ImageMagick#366]
Outputting TIFF files over STDOUT no longer works.

`convert logo: TIFF:- > logo.tiff` outputs:
```
convert: Maximum TIFF file size exceeded. `TIFFAppendToStrip' @ error/tiff.c/TIFFErrors/569.
convert: Error flushing data before directory write. `TIFFWriteDirectorySec' @ error/tiff.c/TIFFErrors/569.
convert: Attempt to write value larger than 0xFFFFFFFF in Classic TIFF file.. `TIFFWriteDirectoryTagLongLong8Array' @ error/tiff.c/TIFFErrors/569.
```

This used to work in version 7.0.3-10 and does not work for me in version 7.0.4-6.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Can we close this issue @njdoyle?

**Comment by njdoyle** [comment]
Works for me. :)
