### ISSUE TITLE
Slow conversion of PSD files

### ISSUE THREAD

**Issue by seb-mtl** [ImageMagick/ImageMagick#3660]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-12

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

I created an empty 10.000x10.000 PSD file in the latest Adobe Photoshop version. The conversion using `convert.exe` takes around 15 seconds.

### Steps to Reproduce

I use the following command to convert the PSD into a png:

```
convert.exe -size 512 -flatten -colorspace RGB foo.psd[0] foo.png
```

If I use [psd-tools](https://github.com/psd-tools/psd-tools) with a Python frontend, it takes around 4 seconds.

### Images

Here is a compressed PSD file (size 10.000x10.000): [foo.psd.zip](https://github.com/ImageMagick/ImageMagick/files/6453839/foo.zip)

**Comment by urban-warrior** [comment]
ImageMagick reads the precombined image along with all the layers.  If we short-cut the process and just extracted the precombined image it would accelerate the process.  We'll add this as a feature request. We do not currently have an ETA on this enhancement.

**Comment by seb-mtl** [comment]
Thanks!
