### ISSUE TITLE
convert -type palette reduces colors too much.

### ISSUE THREAD

**Issue by yoya** [ImageMagick/ImageMagick#3661]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-12

### Operating system

MacOS

### Operating system, version and so on

macOS Catalina version 10.15.7

### Description

Using convert -type palette for 256 colors image will cause extreme color reduction.
There is no problem with either PNG8: palette or magick command -type palette.

### Steps to Reproduce

% magick -version
Version: ImageMagick 7.0.11-12 Q16 x86_64 2021-05-09 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI
Delegates (built-in): bzlib fontconfig freetype gvc heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png tiff webp xml zip zlib
%
% convert -size 64x256 gradient:white-green wg.png
% convert wg.png png8:test1.png
% convert -type palette wg.png test2.png
% magick -type palette wg.png test3.png
%
% identify -verbose test1.png | grep Colors:
Colors: 256
% identify -verbose test2.png | grep Colors:
Colors: 37
% identify -verbose test3.png  | grep Colors:
  Colors: 256

### Images

| original | convert PNG8: | convert -type palette| magick -type palette|
|---|---|---|---|
| ![wg](https://user-images.githubusercontent.com/26040/117701821-a605aa80-b202-11eb-92d9-e10d85e95a77.png) |  ![test1](https://user-images.githubusercontent.com/26040/117701832-a9993180-b202-11eb-8cac-0c16b8235d0f.png) | ![test2](https://user-images.githubusercontent.com/26040/117701838-ab62f500-b202-11eb-9c80-3a63d16b4310.png) |![test3](https://user-images.githubusercontent.com/26040/117702800-f6313c80-b203-11eb-8773-32c88d5b47a5.png) |

**Comment by snibgo** [comment]
Are you using the same IM version? What do "convert -version" and "magick -version" say?

For IM v7, I suggest always using "magick", not "convert" as that gives v6 syntax.

**Comment by dlemstra** [comment]
`magick -type palette wg.png test3.png` should be written as `magick wg.png -type palette test3.png` instead.

**Comment by yoya** [comment]
The magick command and the convert command are the same version, but..
As @dlemstra pointed out, the options were out of order and the magick command had the same problem. 

```
% ~/ImageMagick/7.0.11-12/bin/magick -version
Version: ImageMagick 7.0.11-12 Q16 x86_64 2021-05-09 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI
Delegates (built-in): bzlib fontconfig freetype gvc heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png tiff webp xml zip zlib
% ~/ImageMagick/7.0.11-12/bin/convert -version
Version: ImageMagick 7.0.11-12 Q16 x86_64 2021-05-09 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI
Delegates (built-in): bzlib fontconfig freetype gvc heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png tiff webp xml zip zlib
%
% ~/ImageMagick/7.0.11-12/bin/convert -size 64x256 gradient:white-green wg.png
% ~/ImageMagick/7.0.11-12/bin/convert wg.png png8:test1.png
% ~/ImageMagick/7.0.11-12/bin/convert wg.png -type palette test2.png
% ~/ImageMagick/7.0.11-12/bin/magick  wg.png -type palette test3.png
%
% ~/ImageMagick/7.0.11-12/bin/identify -verbose test1.png | grep Colors:
  Colors: 256
% ~/ImageMagick/7.0.11-12/bin/identify -verbose test2.png | grep Colors:
  Colors: 37
% ~/ImageMagick/7.0.11-12/bin/identify -verbose test3.png | grep Colors:
  Colors: 37
```

| original	| convert PNG8: | convert -type palette | magick -type palette |
|---|---|---|---|
| ![wg](https://user-images.githubusercontent.com/26040/117746034-a6c03000-b246-11eb-9cbd-b075ba649143.png) | ![test1](https://user-images.githubusercontent.com/26040/117746040-a9228a00-b246-11eb-94bd-f21a2ee8b8a0.png) | ![test2](https://user-images.githubusercontent.com/26040/117746046-acb61100-b246-11eb-950b-f1a9961411e1.png) | ![test3](https://user-images.githubusercontent.com/26040/117746051-af186b00-b246-11eb-9734-91bafed1b74c.png) |

**Comment by fmw42** [comment]
Syntax is more strict in IM 7 than in IM 6

**Comment by urban-warrior** [comment]
Use `-kmeans 256` instead of `-type palette`.

**Comment by hoosierc** [comment]
Thanks for the quick response!

When using just `-kmeans 256` with 7.1.0-30 it looks like I'm not getting an indexed bitmap written, but the following arguments seem to be doing what I was hoping for (writing an indexed bitmap that doesn't reduce the number of colors in the image):

`-format bmp -kmeans 256 -type Palette`

Do you know of any reason that using `-kmeans 256` and `-type Palette` together would be a bad idea for now?

It sounds like `-type palette` might start doing what I'm looking for in a future release without also needing to specify `-kmeans 256`, so I'll keep an eye out for that release, too.

**Comment by hoosierc** [comment]
7.1.0-32 is working for me with the palette type specified. Thanks again!
