### ISSUE TITLE
Using convert to draw text using undercolor isn't working

### ISSUE THREAD

**Issue by Kurt-DDir** [ImageMagick/ImageMagick#3665]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

6.9.10-68

### Operating system

Linux

### Operating system, version and so on

CentOS 7.9.2009

### Description

I'm moving some scripts from a RedHat 6 system to CentOS 7 system and the behavior of the undercolor isn't the same. The purpose was to make the text readable when placed on images that would have changing colors.
 
I'm using the following command on both systems.
 
convert -font helvetica -undercolor navy -fill yellow -draw "text 5,100 '$filename'" input.png output.png

On RedHat 6.10   ImageMagick 6.7.2-7 2017-01-12 Q16  ... it works as expected
![RH6_undercolor](https://user-images.githubusercontent.com/84044764/117883229-c8cea800-b270-11eb-9b82-d22e0b488685.png)

On CentOS 7.9.2009    ImageMagick 6.9.10-68 Q16 ... it doesn't work as expected. In this case the text is underlined only. And the text is hard to read depending on the image color underneath.
![Centos7_undercolor](https://user-images.githubusercontent.com/84044764/117883606-38449780-b271-11eb-8ecb-dc4df77bec8f.png)

Is this a bug in the latest version of ImageMagick on CentOS 7 or is there another command I should be using?

### Steps to Reproduce

I've tried using the convert command with "annotate" and "label" options but can't seem to make it behave the same way.

**Comment by fmw42** [comment]
I tested IM 6.9.10.68 on my Mac with your command in proper syntax (**Read the input first**) and it works fine. So try

`convert input.png -font helvetica -undercolor navy -fill yellow -draw "text 5,100 '$filename'" output.png`

Check your freetype and libpng version also to be sure it is the same and or current.

**Comment by Kurt-DDir** [comment]
So I'm still getting the same problem.  These are the current versions of freetype and libpng on the system
   freetype-2.8-14.el7_9.1.x86_64
   freetype-devel-2.8-14.el7_9.1.x86_64
   libpng-devel-1.5.13-8.el7.x86_64
   libpng-1.5.13-8.el7.x86_64
   libpng12-1.2.50-10.el7.x86_64

I've taken the command out of my script and using the command line as such
   convert test.png -font helvetica -undercolor navy -fill yellow -draw "text 15,15 'This is a test on CentOS-7" test_out.png
and still get the underline behavior
![Centos7_undercolor](https://user-images.githubusercontent.com/84044764/118015350-cd02d000-b319-11eb-87ea-2ffadc8aed03.png)

But it still works on RedHat 6
![RH6_undercolor](https://user-images.githubusercontent.com/84044764/118016085-97aab200-b31a-11eb-9410-61842508763d.png)

Any other ideas to try?

**Comment by dlemstra** [comment]
Have you tried to use the most recent version of ImageMagick 6 instead?
