### ISSUE TITLE
Outputting JP2 over STDOUT fails

### ISSUE THREAD

**Issue by njdoyle** [ImageMagick/ImageMagick#367]
Outputting JP2 files over STDOUT no longer works.

`convert logo: JP2:- > logo.jp2` outputs:
```
convert: unable to encode image file `-' @ error/jp2.c/WriteJP2Image/1060.
```

This used to work in version 7.0.3-10 and does not work for me in version 7.0.4-6.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Can we close this issue @nhdoyle?
