### ISSUE TITLE
Bad version number on github releases page

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#3675]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-10

### Operating system

Linux

### Operating system, version and so on

N/A - problem with builds

### Description

The releases [page on github](https://github.com/ImageMagick/ImageMagick/releases) has a list of releases.

The top-most release is labelled as 7.0.11-10. However the files linked are 7.0.11-6.

It seems that releases after 7.0.11-6 are not present on the releases page. I guess it might be related to the travis buids failing: https://travis-ci.org/github/ImageMagick/ImageMagick/builds

### Steps to Reproduce

Go to https://github.com/ImageMagick/ImageMagick/releases

Attempt to download 7.0.11-10 tar.gz file, see that you have 7.0.11-6 instead.

### Images

![ReleaseFilename](https://user-images.githubusercontent.com/1505719/118115020-48c75000-b3e0-11eb-9271-63e3221bad4b.png)

**Comment by Danack** [comment]
Actually, I've just realised that later releases are there, but not listed as the latest release, and are collapsed by default.

![LatestRelease](https://user-images.githubusercontent.com/1505719/118115769-4addde80-b3e1-11eb-9b89-f71f14a6ab53.PNG)

**Comment by dlemstra** [comment]
Thanks for reporting this. Our travis build was broken and we just moved this GitHub actions. We ran some tests in a branch and that new build seems to be working. This should be fixed again starting with the next release.

**Comment by Jan-E** [comment]
> Actually, I've just realised that later releases are there, but not listed as the latest release, and are collapsed by default.

I had noticed this as well and was just wondering if official releases were delayed because of  https://github.com/ImageMagick/ImageMagick/issues/3534

**Comment by dlemstra** [comment]
We have been doing a lot of releases (see the tags) since that verson. The build that created the releases was broken and this is hopefully fixed in the next release.

**Comment by dlemstra** [comment]
A new release has been created with the AppImage build.

**Comment by Jan-E** [comment]
Github sent me a notice about the new release, so I already knew. At the moment I am building new artifacts on Appveyor for my Windows builds of php_imagick.dll on https://www.apachelounge.com/viewtopic.php?t=6359

WIP: https://ci.appveyor.com/project/Jan-E/imagemagick-windows/builds/39219890
