### ISSUE TITLE
mogrify doubles output size when writing to STDOUT

### ISSUE THREAD

**Issue by lucacorti** [ImageMagick/ImageMagick#3676]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-12

### Operating system

MacOS

### Operating system, version and so on

Big Sur

### Description

Mogrify seems to output differently depending on wether it is writing to file or STDOUT.

This seems unrelated to the OS and is reported here as a blocker: https://github.com/route/mogrify/issues/56

### Steps to Reproduce

```
% mogrify -write - -resize 100x100 image.jpg | wc -c 
    5616
% mogrify -write tmp.jpg -resize 100x100 image.jpg        
% cat tmp.jpg | wc -c
    2808
```

### Images

Any file

**Comment by dlemstra** [comment]
It looks like the image is written twice. This is also happening in ImageMagick 6.

**Comment by lucacorti** [comment]
@dlemstra Yes, hex dumping the output confirms that.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
