### ISSUE TITLE
Corruption of MIFF files created from sources with curly braces in comment metadata

### ISSUE THREAD

**Issue by njdoyle** [ImageMagick/ImageMagick#368]
If an image is input to ImageMagick with curly braces in it's text comment metadata then MIFF files may be corrupted when output.

Here's a command that demonstrates the problem:
`convert logo: -set text 'CommentWith{curly}braces.' PNG:- | convert PNG:- MIFF:- | convert MIFF:- logo.png`

This command creates a PNG file with a text comment containing curly braces, converts it to a MIFF file, and then converts it back to a PNG file for viewing.

The command produces warnings and, for me, produces corrupted image data.

This has been happening for a while and can be confirmed to be a problem on version 7.0.4-6.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Can we close this issue @njdoyle?
