### ISSUE TITLE
Compilation problem with 7.0.10-54 and newer

### ISSUE THREAD

**Issue by smtalk** [ImageMagick/ImageMagick#3687]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-12

### Operating system

Linux

### Operating system, version and so on

CentOS7

### Description

Compilation succeeds with 7.0.10-53 but fails with 7.0.10-54 and any newer version, including newest 7.0.11-12.

Error:
  CCLD     utilities/magick
MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `WebPMemoryWriterClear'
collect2: error: ld returned 1 exit status
make[1]: *** [utilities/magick] Error 1
make[1]: *** Waiting for unfinished jobs....

OS: CentOS7, no custom libraries, libwebp-devel installed from yum. All lower versions than 7.0.10-54 have no problems.

### Steps to Reproduce

Simply:
yum -y install libwebp-devel

And try to compile latest version of ImageMagick.

**Comment by dlemstra** [comment]
It looks like you are using a very old version of the WebP library. Are you able to upgrade that?

**Comment by smtalk** [comment]
Yes, default webp library provided in CentOS7 is 0.3.0, however, we did not expect a minor update to break all the installations :) As mentioned before, 7.0.10-53 had no issues at all. CentOS7 is going to be EOL only in 2024. Is it possible to get it fixed in next release? If not, we'll be forced to source-compile libwebp on every CentOS7 server.. And it'd be the best not to do it.

**Comment by dlemstra** [comment]
It seems that the `WebPMemoryWriterClear` method was added in version `0.4.1`. I think we can add a version check for this in configure.ac but that would mean you will no longer have webp support.

**Comment by smtalk** [comment]
A version check would be awesome (to disable webp automatically if version is too low)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
