### ISSUE TITLE
Windows installer hangs

### ISSUE THREAD

**Issue by HunterZ** [ImageMagick/ImageMagick#3688]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-12

### Operating system

Windows

### Operating system, version and so on

Windows 10 Home x64 20H2 (19042.985)

### Description

When attempting to install via ImageMagick-7.0.11-12-Q16-HDRI-x64-dll.exe downloaded from https://imagemagick.org/script/download.php, the installer hangs in the pictured state for at least 10 minutes until I kill it.

Task Manager reports that it is Not Responding.

### Steps to Reproduce

1. Navigate to https://imagemagick.org/script/download.php
2. Download ImageMagick-7.0.11-12-Q16-HDRI-x64-dll.exe
3. Run ImageMagick-7.0.11-12-Q16-HDRI-x64-dll.exe

### Images

![image](https://user-images.githubusercontent.com/108939/118416983-095e6500-b667-11eb-8887-092c2ad14b06.png)
![image](https://user-images.githubusercontent.com/108939/118417279-352e1a80-b668-11eb-91c3-5c9baf0c7c42.png)
![image](https://user-images.githubusercontent.com/108939/118417451-f056b380-b668-11eb-9ad9-16980ec9d455.png)

**Comment by dlemstra** [comment]
I am unable to reproduce your issue. I was able to install that version of the library on a VM without any issues. Are you setting any options that might cause issue?

**Comment by HunterZ** [comment]
You tell me - are there any options that might cause the issue?

It was happening both via the Chocolatey installer and via manual install, so I'd be surprise if it was happening due to a non-default option.

**Comment by dlemstra** [comment]
You are the only person that is experiencing this issue. Maybe there is something running on your machine that blocks the installer?

**Comment by HunterZ** [comment]
It looks like this is a general Inno Setup 6.x issue for me. I've taken it to their forums and will close this issue for now.
