### ISSUE TITLE
Using isnan with cmath in c++ does not work due to it is forcely undefined in cmath

### ISSUE THREAD

**Issue by brovko** [ImageMagick/ImageMagick#3690]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [ ] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-6

### Operating system

Linux

### Operating system, version and so on

Ubuntu 18.04 x86_64

### Description

ImageMagick v. 7 builds successfully but when I try to use it in c++ code along with
`#include <cmath>` it states
```
MagickCore/quantum.h:90:8: error: use of undeclared identifier 'isnan'
  if ((IsNaN(quantum) != 0) || (quantum <= 0.0))
       ^
MagickCore/magick-type.h:187:20: note: expanded from macro 'IsNaN'
#  define IsNaN(a) isnan(a)
```
That is because `#include <cmath>` effectively undefines `isnan` allowing to use `std::isnan` only.

### Steps to Reproduce

Here is a pseudo code (c++ standard 14 and -DMAGICKCORE_HDRI_ENABLE=0, -DMAGICKCORE_QUANTUM_DEPTH=16, ImageMagick compiled as a static libraries only):

**test.cpp**
```
#include <cmath>
#include <Magick++.h>

int main() {
  return 0;
}
```

Try to compile:
```
clang++ -pthread -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -stdlib=libstdc++ -std=c++14 -I<PATH_TO_IMAGEMAGICK>/include/ test.cpp -L<PATH_TO_IMAGEMAGICK>/lib/ -lMagick++-7.Q16 -lMagickWand-7.Q16 -lMagickCore-7.Q16 -lpng -lz -ljpeg
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by urban-warrior** [comment]
Download the latest ImageMagick main branch.  Does the patch resolve the issue for you?

**Comment by brovko** [comment]
I can confirm that the latest `master` resolved the issue. Thank you!
By the way in c++ it is possible to use `std::isnan` after `#include <cmath>`.
