### ISSUE TITLE
`JXL_ASSERT: !fp` if `-quality` is 100 or <= 67 for JXL output

### ISSUE THREAD

**Issue by jo620kix** [ImageMagick/ImageMagick#3698]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-13

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

If `-quality` parameter is 100 (lossless) or <= 67 (lossy), it fails with `JXL_ASSERT: !fp`.

Input is a 16-bit PNG.

### Steps to Reproduce

These will not work:
`convert test.png -quality 100 test.jxl`
`convert test.png -quality 67 test.jxl`

These will work:
`convert test.png -quality 99 test.jxl`
`convert test.png -quality 68 test.jxl`

### Notes

`cjxl` can successfully convert the test image, e.g.
`cjxl -q 100 --override_bitdepth=32 test.png test.jxl`

### Images

![Test image in PNG format](https://user-images.githubusercontent.com/81214276/118766453-f799df00-b86b-11eb-8cfa-683f3b3e5dee.png)

[Source](https://commons.wikimedia.org/wiki/File:Berliner_Dome_,_Berlin_Cathedral_-_Inside_view_-_HDR_Image.tif), Copyright Bpraveenk, CC BY-SA 4.0

**Comment by urban-warrior** [comment]
Unfortunately, we cannot reproduce the problem.  The conversion completes for us without complaint for JXL version 0.3.7-2.
