### ISSUE TITLE
julia 0.4.7 on windows10 ,when Pkg.build("ImageMagick"),throw error

### ISSUE THREAD

**Issue by xulang726** [ImageMagick/ImageMagick#370]
julia> Pkg.build("ImageMagick")
INFO: Building ImageMagick
INFO: Installing ImageMagick library

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x7ffa3fa2accf -- unknown function (ip: 00007FFA3FA2ACCF)
MagickQueryConfigureOption at  (unknown line)
anonymous at no file:0
jl_eval_with_compiler_p at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_eval_module_expr at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_parse_eval_all at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_load_ at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
include at boot.jl:261
jl_apply_generic at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
include_from_node1 at loading.jl:333
jl_apply_generic at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_f_tuple at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
evalfile at loading.jl:349
evalfile at loading.jl:349
jl_apply_generic at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
anonymous at none:14
cd at file.jl:32
jl_apply_generic at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
anonymous at none:13
open at iostream.jl:114
jl_apply_generic at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_expr at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_interpret_toplevel_thunk_with at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_eval_with_compiler_p at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
jl_f_tuple at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
process_options at client.jl:257
_start at client.jl:378
jlcall__start_621 at  (unknown line)
jl_apply_generic at D:\Julia-0.4.7\bin\libjulia.dll (unknown line)
unknown function (ip: 00000000004018D0)
unknown function (ip: 00000000004028AB)
unknown function (ip: 000000000040140C)
unknown function (ip: 000000000040153B)
BaseThreadInitThunk at C:\WINDOWS\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\WINDOWS\SYSTEM32\ntdll.dll (unknown line)
ERROR: Build process failed.
 in build! at pkg/entry.jl:701
 in build at pkg/entry.jl:720
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in build at pkg.jl:64

julia>

**Comment by dlemstra** [comment]
You are posting this message in the wrong repository. We did not create the ImageMagick library for julia. You might want to go here: https://github.com/JuliaImages/Images.jl or here: https://github.com/JuliaIO/ImageMagick.jl. Not sure which one is the correct one.

**Comment by xulang726** [comment]
sorry !
