### ISSUE TITLE
non-conforming drawing primitive definition `text'

### ISSUE THREAD

**Issue by grego001** [ImageMagick/ImageMagick#371]
from 'make check' on Ubuntu 16.04

Caught exception: lt-piddle: non-conforming drawing primitive definition `text'                                                                                       @ error/draw.c/DrawImage/3269
not ok
FAIL: Magick++/demo/demos.tap 6

**Comment by mikayla-grace** [comment]
Unfortunately we cannot reproduce this problem.  We're using ImageMagick 7.0.4-7 and 6.9.7-7, the current releases, under CentOS 7 and Fedora 25, and all the units tests pass.  We do not have access to Ubuntu to do further analysis.

**Comment by dlemstra** [comment]
See #374
