### ISSUE TITLE
libmagick++-dev under Ubuntu installs the header files, but the Options.h is missing

### ISSUE THREAD

**Issue by AlexisWilke** [ImageMagick/ImageMagick#3711]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-14

### Operating system

Linux

### Operating system, version and so on

Ubuntu 21.04 and earlier

### Description

The Options.h from libmagick++ doesn't get installed and thus can't be used in software. Manually copying and using the file from the source package works just fine.

### Steps to Reproduce

    make
    make install
    ls /usr/include/ImageMagick/Magick++    [adjust path to your installation destination]

The `Options.h` file is missing.

With ImageMagick-7, the output looks like this:

    $ ls dist/include/ImageMagick-7/Magick++
    Blob.h       Color.h     Exception.h  Geometry.h  Include.h  Pixels.h          SecurityPolicy.h  STL.h
    CoderInfo.h  Drawable.h  Functions.h  Image.h     Montage.h  ResourceLimits.h  Statistic.h       TypeMetric.h

My take is that it should be included in this list:

(from `Magick++/Makefile.am`)

    MAGICKPP_INCHEADERS_OPT = \
      Magick++/lib/Magick++/Blob.h \
      Magick++/lib/Magick++/CoderInfo.h \
      Magick++/lib/Magick++/Color.h \
      Magick++/lib/Magick++/Drawable.h \
      Magick++/lib/Magick++/Exception.h \
      Magick++/lib/Magick++/Functions.h \
      Magick++/lib/Magick++/Geometry.h \
      Magick++/lib/Magick++/Image.h \
      Magick++/lib/Magick++/Include.h \
      Magick++/lib/Magick++/Montage.h \
      Magick++/lib/Magick++/Options.h \              <--- this one is missing
      Magick++/lib/Magick++/Pixels.h \
      Magick++/lib/Magick++/ResourceLimits.h \
      Magick++/lib/Magick++/SecurityPolicy.h \
      Magick++/lib/Magick++/Statistic.h \
      Magick++/lib/Magick++/STL.h \
      Magick++/lib/Magick++/TypeMetric.h

Or maybe this one (`scripts/Makefile.am`):

    magickppinc_HEADERS = \
    	Magick++/lib/Magick++/Blob.h \
    	Magick++/lib/Magick++/CoderInfo.h \
    	Magick++/lib/Magick++/Color.h \
    	Magick++/lib/Magick++/Drawable.h \
    	Magick++/lib/Magick++/Exception.h \
    	Magick++/lib/Magick++/Geometry.h \
    	Magick++/lib/Magick++/Image.h \
    	Magick++/lib/Magick++/Include.h \
    	Magick++/lib/Magick++/Montage.h \
    	Magick++/lib/Magick++/Options.h \              <--- this one is missing
    	Magick++/lib/Magick++/Pixels.h \
    	Magick++/lib/Magick++/STL.h \
    	Magick++/lib/Magick++/TypeMetric.h

I think that I would have to regenerate everything to make it work, but I have not dealt with a `configure` in like forever so I did not try to go that far.

**Comment by dlemstra** [comment]
You should not be using the `Options.h` header file. That is the reason that it is missing from the install. Why do you want to use it?

**Comment by AlexisWilke** [comment]
How do I replicate this command line option:

    -sampling-factor 4:2:0

If I can't do this:

    img.options()->samplingFactor("4:2:0");

on my image?

And yes, that works, if I copy the `Options.h ` to my folder and `#include` it.

I looked around quite a bit and I can't see how to change the _sampling factor_ in any other way. If it's doable, then it's not properly documented.

    Magick::Image img(f_original_filename);
    img.filterType(Magick::CubicFilter);                 // -filter Cubic
    img.defineSet("filter", "b=0.3333333333", true);     // -define filter:b=1/3
    img.defineSet("filter", "c=0.3333333333", true);     // -define filter:c=1/3
    img.resize(std::to_string(width) + "x" + std::to_string(height));
    img.options()->samplingFactor("4:2:0");           // -sampling-factor 4:2:0
    img.write(output_filename);

Without changing that option, the file may be 4:2:2 or even 4:4:4. With the option it gets forced to 4:2:0 (which is what I need for my Jetson's hardware, the other samplings are not supported).

**Comment by dlemstra** [comment]
It looks like we forgot to add this to the `Image` class. After the next release you will be able to do this: `img->samplingFactor("4:2:0")`
