### ISSUE TITLE
Only the FIRST image can be converted from multiple image HEIC format

### ISSUE THREAD

**Issue by Lorne0** [ImageMagick/ImageMagick#3712]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-12 Q16 x86_64 2021-05-09

### Operating system

MacOS

### Operating system, version and so on

macOS Catalina 10.15.6

### Description

Only **the FIRST image** can be converted from **multiple image HEIC format**

### Experiment 1:
Using `magick Jupiter.heic j.jpg` or `magick Jupiter.heic +adjoin out.heic`
I can get multiple images, but **all images are the first image** in the Jupiter.heic

### Experiment 2:
Also I've tried to combine some different size images (my private images) to heic file
`$ identify *.heic`
`1.heic HEIC 1440x1760 1440x1760+0+0 8-bit sRGB 0.000u 0:00.003`
`2.heic HEIC 1008x1232 1008x1232+0+0 8-bit sRGB 0.000u 0:00.000`
`3.heic HEIC 432x528 432x528+0+0 8-bit sRGB 0.000u 0:00.000`

Then I combine these images into one heic file (a.heic):
`magick 1.heic 2.heic 3.heic a.heic`

But I got
`$ identify a.heic` 
`a.heic[0] HEIC 1440x1760 1440x1760+0+0 8-bit sRGB 0.000u 0:00.001`
`a.heic[1] HEIC 1440x1760 1440x1760+0+0 8-bit sRGB 0.000u 0:00.000`
`a.heic[2] HEIC 1440x1760 1440x1760+0+0 8-bit sRGB 0.000u 0:00.000`

It seems like it only identified the first image.

Then I tried
`$ magick 1.heic 2.heic 3.heic a.tiff`
`$ identify a.tiff`
`a.tiff[0] TIFF 1440x1760 1440x1760+0+0 8-bit sRGB 18.0559MiB 0.000u 0:00.001`
`a.tiff[1] TIFF 1008x1232 1008x1232+0+0 8-bit sRGB 0.000u 0:00.000`
`a.tiff[2] TIFF 432x528 432x528+0+0 8-bit sRGB 0.000u 0:00.000`

Looks like tiff can be identified accurately.

### Images

[Jupiter wallpapers](http://dynwalls.com/wallpapers/Jupiter.heic)
(given by [Issue-1391](https://github.com/ImageMagick/ImageMagick/issues/1391), which is similar to this issue but not the same )

**Comment by dlemstra** [comment]
Can you shere the three files that can be used to reproduce this issue?

**Comment by Lorne0** [comment]
Hi, @dlemstra, since the images I used are my own private images, I tried to use other images from some free image sites, and crop or resize them by magick command.

Previous images:
[1.jpeg](https://images.pexels.com/photos/7889083/pexels-photo-7889083.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500)
[2.jpeg](https://images.pexels.com/photos/1645230/pexels-photo-1645230.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500)
[3.jpeg](https://images.pexels.com/photos/1657212/pexels-photo-1657212.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500)

from jpeg to heic:
`magick 1.jpg -crop "1000x1300+0+0" -quality 30 1.heic`
`magick 2.jpg -crop "800x1200+0+0" -quality 30 2.heic`
`magick 3.jpg -resize '500x650!' -quality 30 3.heic`

[HEIC images link (google drive)](https://drive.google.com/file/d/15oMhLy5OX5sltQdSUuDyrF8tDsqS7lPx/view?usp=sharing)

Here are the new outputs:
`$ identify *.heic`
`1.heic HEIC 1000x1300 1000x1300+0+0 8-bit sRGB 0.000u 0:00.000`
`2.heic HEIC 800x1200 800x1200+0+0 8-bit sRGB 0.000u 0:00.000`
`3.heic HEIC 500x650 500x650+0+0 8-bit sRGB 0.000u 0:00.000`

`$ magick 1.heic 2.heic 3.heic a.heic`
`$ identify a.heic`
`a.heic[0] HEIC 1000x1300 1000x1300+0+0 8-bit sRGB 0.010u 0:00.001`
`a.heic[1] HEIC 1000x1300 1000x1300+0+0 8-bit sRGB 0.010u 0:00.000`
`a.heic[2] HEIC 1000x1300 1000x1300+0+0 8-bit sRGB 0.010u 0:00.000`

`$ magick 1.heic 2.heic 3.heic a.tiff`
`$ identify a.tiff`
`a.tiff[0] TIFF 1000x1300 1000x1300+0+0 8-bit sRGB 7.39657MiB 0.000u 0:00.000`
`a.tiff[1] TIFF 800x1200 800x1200+0+0 8-bit sRGB 0.000u 0:00.000`
`a.tiff[2] TIFF 500x650 500x650+0+0 8-bit sRGB 0.000u 0:00.000`

**Comment by dlemstra** [comment]
It seems that you found a bug. We are reading the other images incorrectly and we are now only reading the primary image 3 times. Just pushed a fix for this and this will be resolved in the next release.
