### ISSUE TITLE
assertion failed error occur in policy read 6.9.7-7 version

### ISSUE THREAD

**Issue by yoya** [ImageMagick/ImageMagick#372]
##  etc/ImageMagick-6/policy.xml
> &lt;policy domain="coder" rights="read" pattern="PNG" /&gt;

## command execution
> % ~/ImageMagick/6.9.7-6/bin/convert in.jpg  out.png
> convert: not authorized `out.png' @ error/constitute.c/WriteImage/1037.
> % ~/ImageMagick/6.9.7-7/bin/convert in.jpg  out.png
> Assertion failed: (exception != (ExceptionInfo *) NULL), function ClearExceptionInfo, file magick/exception.c, line 423.
> zsh: abort      ~/ImageMagick/6.9.7-7/bin/convert in.jpg out.png

## environment

- macOS Sierra 10.12.3
- dependent library setup by homebrew.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Can you test and close this issue after the next release @yoya?

**Comment by yoya** [comment]
Beta(6-*-20170211,7-*-20170212) testing all passed.
I'm waiting for the next version release.

## environment

- macOS Sierra 10.12.3
- dependent library setup by homebrew.
- Install Prefix
  - ImageMagick-6.9.7-8-beta20170211.tar.gz => ~/ImageMagick/6.9.7-8-beta20170211/
  - ImageMagick-7.0.4-8-beta20170212.tar.gz => ~/ImageMagick/7.0.4-8-beta20170212/

## test result

- etc/ImageMagick-[67]/policy.xml

> command & result

-  &lt;policy domain="coder" rights="read" pattern="PNG" /&gt;

> % ~/ImageMagick/6.9.7-8-beta20170211/bin/convert in.jpg out.jpg
> % ~/ImageMagick/6.9.7-8-beta20170211/bin/convert in.jpg out.png
> convert: not authorized `out.png' @ error/constitute.c/WriteImage/1043.

> % ~/ImageMagick/7.0.4-8-beta20170212/bin/convert in.jpg out.jpg
> % ~/ImageMagick/7.0.4-8-beta20170212/bin/convert in.jpg out.png
> convert: not authorized `out.png' @ error/constitute.c/WriteImage/1029.

-  &lt;policy domain="coder" rights="write" pattern="PNG" /&gt;

> % ~/ImageMagick/6.9.7-8-beta20170211/bin/convert in.jpg out.png
> % ~/ImageMagick/6.9.7-8-beta20170211/bin/convert in.png out.png
> convert: not authorized `in.png' @ error/constitute.c/ReadImage/420.
> convert: no images defined `out.png' @ error/convert.c/ConvertImageCommand/3258.

> % ~/ImageMagick/7.0.4-8-beta20170212/bin/convert in.jpg out.png
> % ~/ImageMagick/7.0.4-8-beta20170212/bin/convert in.png out.png
> convert: not authorized `in.png' @ error/constitute.c/ReadImage/425.
> convert: no images defined `out.png' @ error/convert.c/ConvertImageCommand/3254.

**Comment by yoya** [comment]
all OK!
thank you.

## environment

- macOS Sierra 10.12.3
- dependent library setup by homebrew.
- Install Prefix
  - ImageMagick-6.9.7-8.tar.gz => ~/ImageMagick/6.9.7-8/
  - ImageMagick-7.0.4-8.tar.gz => ~/ImageMagick/7.0.4-8/

## test result

- etc/ImageMagick-[67]/policy.xml

> command & result

-  &lt;policy domain="coder" rights="read" pattern="PNG" /&gt;

> % ~/ImageMagick/6.9.7-8/bin/convert in.jpg out.jpg
> % ~/ImageMagick/6.9.7-8/bin/convert in.png out.jpg
> % ~/ImageMagick/6.9.7-8/bin/convert in.jpg out.png
> convert: not authorized `out.png' @ error/constitute.c/WriteImage/1043.

> % ~/ImageMagick/7.0.4-8/bin/convert in.jpg out.jpg
> % ~/ImageMagick/7.0.4-8/bin/convert in.png out.jpg
> % ~/ImageMagick/7.0.4-8/bin/convert in.jpg out.png
> convert: not authorized `out.png' @ error/constitute.c/WriteImage/1029.

-  &lt;policy domain="coder" rights="write" pattern="PNG" /&gt;

> % ~/ImageMagick/6.9.7-8/bin/convert in.jpg out.png
> % ~/ImageMagick/6.9.7-8/bin/convert in.png out.png
> convert: not authorized `in.png' @ error/constitute.c/ReadImage/420.
> convert: no images defined `out.png' @ error/convert.c/ConvertImageCommand/3258.
> % ~/ImageMagick/6.9.7-8/bin/convert in.png out.jpg
> convert: not authorized `in.png' @ error/constitute.c/ReadImage/420.
> convert: no images defined `out.jpg' @ error/convert.c/ConvertImageCommand/3258.

> % ~/ImageMagick/7.0.4-8/bin/convert in.jpg out.png
> % ~/ImageMagick/7.0.4-8/bin/convert in.png out.png
> convert: not authorized `in.png' @ error/constitute.c/ReadImage/425.
> convert: no images defined `out.png' @ error/convert.c/ConvertImageCommand/3254.
> % ~/ImageMagick/7.0.4-8/bin/convert in.png out.jpg
> convert: not authorized `in.png' @ error/constitute.c/ReadImage/425.
> convert: no images defined `out.jpg' @ error/convert.c/ConvertImageCommand/3254.
