### ISSUE TITLE
I can't install it on my computer because "configure: creating ./config.status"

### ISSUE THREAD

**Issue by JohenanLi** [ImageMagick/ImageMagick#3723]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-13

### Operating system

Linux

### Operating system, version and so on

Debian 5.10.28-1kali1 (2021-04-12) x86_64 GNU/Linux

### Description

When i want to install imagemagick,i type the cmd "./configure" in my terminal(zsh),then it throws me a bug:configure: creating ./config.status
./config.status:2068: parse error near `{'"

### Steps to Reproduce

Typing "./configure" in terminal.

### Images

![Uploading Screenshot_2021-05-22_09_47_56.png…]()

**Comment by urban-warrior** [comment]
Unfortunately we cannot reproduce the problem.  The problem is either a bug in your shell or autoconf/automake has not been certified for your release of the shell.  It works fine for our release of the shell, GNU bash, version 4.4.19(1)-release and version 5.1.0(1)-release.
