### ISSUE TITLE
make check failure installing ImageMagick-7.0.4-7 on ubuntu 16.04

### ISSUE THREAD

**Issue by RMPnet-UK** [ImageMagick/ImageMagick#374]
Hi,
I was installing following these instructions:
http://www.imagemagick.org/script/install-source.php
and got two fails when running the check

FAIL: tests/wandtest
====================

lt-wandtest: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/1792.
lt-wandtest: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/1792.
tests/wandtest.c main 5321 non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3269
1..1
Reading images...
Iterate forward...
index 0 scene 0
index 1 scene 1
index 2 scene 2
index 3 scene 3
index 4 scene 4
Iterate reverse...
index 4 scene 4
index 3 scene 3
index 2 scene 2
index 1 scene 1
index 0 scene 0
Remove scene 1...
index 0 scene 0
index 1 scene 2
index 2 scene 3
index 3 scene 4
Insert scene 1 back in sequence...
index 0 scene 0
index 1 scene 1
index 2 scene 2
index 3 scene 3
index 4 scene 4
Set scene 2 to scene 1...
index 0 scene 0
index 1 scene 1
index 2 scene 1
index 3 scene 3
index 4 scene 4
Apply image processing options...
not ok
FAIL: tests/wandtest.tap 1

FAIL: Magick++/demo/demos
=========================
Caught exception: lt-piddle: non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3269
lt-shapes: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/1792.
lt-shapes: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/1792.
lt-shapes: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/1792.
lt-shapes: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/1792.
lt-shapes: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/1792.
lt-shapes: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/1792.
not ok
FAIL: Magick++/demo/demos.tap 6

Full ./test-suite.log [ImageMagick-7.0.4-7 test-suite.pdf](https://github.com/ImageMagick/ImageMagick/files/756232/ImageMagick-7.0.4-7.test-suite.pdf)
I'm not sure if there is a better way to get the latest version of ImageMagick installed, I had tried the .rpm but got loads of missing dependencies so tried the source compile route instead.

**Comment by mikayla-grace** [comment]
In order for the unit tests to pass, you need to install the Freetype development package before you build ImageMagick from source.  Once Freetype is installed, the ImageMagick build process will detect it and include support for font rendering.

**Comment by dlemstra** [comment]
Besides Freetype you also need Ghostscript. I installed the following packages on my Ubuntu machine:
```bash
apt install libfreetype6-dev
apt install libfontconfig1-dev
apt install ttf-mscorefonts-installer # you prob don't need this.
apt install ghostscript
```

And I now get the following result:
```bash
============================================================================
Testsuite summary for ImageMagick 7.0.4
============================================================================
# TOTAL: 86
# PASS:  86
```

**Comment by RMPnet-UK** [comment]
Thanks @dlemstra that did the trick, I didn't install ttf-mscorefonts-installer

Regards
Keith

**Comment by emmaodia** [comment]
Hi, I followed the instructions by @dlemstra and I get this error 
`The following packages have unmet dependencies:
 libfreetype6-dev : Depends: libfreetype6 (= 2.4.8-1ubuntu2) but 2.4.8-1ubuntu2.1 is to be installed
E: Unable to correct problems, you have held broken  #packages.`

What do I do now?

**Comment by dlemstra** [comment]
Does this help you @emmaodia: https://askubuntu.com/a/663823
