### ISSUE TITLE
Site returns 500 status code

### ISSUE THREAD

**Issue by MrKomodoDragon** [ImageMagick/ImageMagick#3764]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-13

### Operating system

MacOS

### Operating system, version and so on

OSX Big Sur 11.0.0

### Description

The site returns a 500 status code. If you visit the website it is blank, and I checked with some python code too, the website returns 500. I have tried multiple browsers.

### Steps to Reproduce

In the browser: 
1. Visit http://imagemagick.org
2. The website will be blank.

With code:
1. Make a request to the site.
2. Check the status. It should be 500

Sample python code:
```py
import requests
resp = requests.get("https://imagemagick.org")
resp.status_code
500
```

### Images

![image](https://user-images.githubusercontent.com/74436682/120125659-8c56e380-c16e-11eb-973d-f56076244713.png)

**Comment by MrKomodoDragon** [comment]
Note: the legacy site still works.

**Comment by urban-warrior** [comment]
Thanks ... and fixed.
