### ISSUE TITLE
fx in -define compose:args=

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#3765]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [ ] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.10-45

### Operating system

Windows

### Operating system, version and so on

Tested with IM v7.0.10-45 on Windows 8.1.

### Description

There is a problem when %[fx:...] is used within "-define compose:args=".

IM returns the wrong result. If "-define compose:args=" cannot parse fx expressions, it should raise an error, rather than making a bad result.

### Steps to Reproduce

```
magick xc:srgb(10%,20%,30%) xc:srgb(16%,17%,18%) -compose Mathematics  -define compose:args=0,-1,2,0 -composite txt:

# ImageMagick pixel enumeration: 1,1,65535,srgb 0,0: (2621.4,15073,27524.7)  #0A3D3AE16B85  srgb(4%,23%,42%)  <== Correct

magick xc:srgb(10%,20%,30%) xc:srgb(16%,17%,18%) -compose Mathematics  -define compose:args=0,%[fx:1-2],2,0 -composite txt:

# ImageMagick pixel enumeration: 1,1,65535,srgb 0,0: (0,0,0)  #000000000000  black  <== Wrong
```

### Images

[No images.]

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
