### ISSUE TITLE
SOVERSION change in 7.0.11-14, is that intentional?

### ISSUE THREAD

**Issue by akien-mga** [ImageMagick/ImageMagick#3768]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-14

### Operating system

Linux

### Operating system, version and so on

Mageia 9, x86_64

### Description

I'm looking at updating Mageia's ImageMagick packages (for Mageia 7, 8 and 9) to include latest security fixes.

I was surprised to find that libMagickCore-7 and libMagickWand-7 changed SOVERSION in 7.0.11-14 compared to 7.0.11-13, bumping the major from 9 to 10: https://github.com/ImageMagick/ImageMagick/commit/396ef110ec41744bd5c084538991aa0757c03afb

I'm not familiar with ImageMagick's versioning system, but it seems surprising to me that such a compatibility breakage is introduced between 7.0.11-13 and 7.0.11-14. Those numbers don't typically denote compatibility breakage (I'd expect a 7.1 minor version bump for that).

In comparison, 7.0.10-62 also has major 9 for these libraries.

Is this breakage intentional and documented? Moreover, the download repository no longer provides 7.0.11-13 so it's not possible to stick to the previous version to avoid introducing the compatibility breakage in stable distro releases that would require a rebuild of all dependent applications: https://download.imagemagick.org/ImageMagick/download/

### Steps to Reproduce

n/a

**Comment by urban-warrior** [comment]
The SOVERSION was bumped because we introduced a new method, StringInfoToDigest().  As this method is new and not used in the wild, we do not anticipate any compatibility issues.

**Comment by kekePower** [comment]
I think it's completely irresponsible to introduce a breaking change in a stable code base like this.

It really creates headaches for distributions.

It would certainly be best to bump to a 7.1 release if/when you decide to do things like this.

So, @urban-warrior, the questions isn't if the method is used in the wild, but rather why it was introduced in a stable release.

**Comment by urban-warrior** [comment]
We needed this single method for a new image cache methods and tools we're building @ https://github.com/ImageMagick/MagickCache.    We have a release scheduled this week.  We'll bump to 7.1.

**Comment by kekePower** [comment]
Thanks.

Do you think it's possible to release a 7.0.11-15 with the changes reverted and SOVERSION back to 9?

This way we, Mageia, can push the security fixes to all three versions we have active at the moment.

**Comment by urban-warrior** [comment]
Its possible, but not practical.  We're a small development team and are perpetually behind on all the tasks required to support ImageMagick.  A release is time consuming and we currently don't have availability.

**Comment by remicollet** [comment]
> The SOVERSION was bumped because we introduced a new method, StringInfoToDigest(). As this method is new and not used in the wild, we do not anticipate any compatibility issues.

New symbol doesn't means API is broken.... :(
