### ISSUE TITLE
Behavior of policy changed from 6.9.7-7

### ISSUE THREAD

**Issue by yoya** [ImageMagick/ImageMagick#377]
The behavior of policy changed from 6.9.7-7. I think that it is a good improvement, but backward compatibility is not perfect so I think that it is necessary to have an official announcement, but how is it?

reference) https://blog.awm.jp/2017/02/09/imagemagick-en/ "Behavior of policy changed from ImageMagick 6.9.7-7"

**Comment by mikayla-grace** [comment]
You may have noticed that we made a reference to the change @ https://www.imagemagick.org/script/security-policy.php.  Our intent is to add comments to the policy.xml configuration file in the next point release and get an announcement @ https://www.imagemagick.org/discourse-server/viewforum.php?f=4 within the next few days.

**Comment by fmw42** [comment]
Have you seen http://www.imagemagick.org/discourse-server/viewtopic.php?f=4&t=26801 at the top of the Announcement forum at http://www.imagemagick.org/discourse-server/index.php

**Comment by mikayla-grace** [comment]
Forgot to mention that, however, it needs to be more explicit-- working on that now.

**Comment by yoya** [comment]
Thank you so much for your quick reply & good information.
I feel so good to be clearly indicated in ChangeLog, bacause many people will rely on considering compatibility when upgrading ImageMagick.

**Comment by bastien-roucaries** [comment]
This need a so bump if new policy file is incompatible with older one....

**Comment by bastien-roucaries** [comment]
I mean if new policy could not be read by older version verbatim

**Comment by mikayla-grace** [comment]
The 7.0.4-7 and 6.9.7-7 should be able to read previous policies.  The previous policies were blacklist only.  The new policy allows blacklisting a set of coders then a subsequent policy can whitelist one or more coders (e.g. blacklist all coders but whitelist PNG, JPEG, and GIF).

**Comment by yoya** [comment]
I think that this issue has been solved. Can I close this?

**Comment by mikayla-grace** [comment]
Go ahead and close this issue.
