### ISSUE TITLE
-define preserve-timestamp=true dont work in windows

### ISSUE THREAD

**Issue by j3l11234** [ImageMagick/ImageMagick#3777]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-14

### Operating system

Windows

### Operating system, version and so on

windows 10

### Description

"D:\Program Files\ImageMagick\magick.exe" mogrify -define preserve-timestamp=true  -quality 80 -interlace plane  xxx.jpg

the timestamp has change to now

### Steps to Reproduce

see above

**Comment by urban-warrior** [comment]
@dlemstra, can you check the Windows build and ensure that MAGICKCORE_HAVE_UTIME is defined.  Without the define, its not possible to preserve the timestamp.

**Comment by j3l11234** [comment]
> @dlemstra, can you check the Windows build and ensure that MAGICKCORE_HAVE_UTIME is defined. Without the define, its not possible to preserve the timestamp.

MAGICKCORE_HAVE_UTIME， Yes, I think that's the reason

**Comment by dlemstra** [comment]
I just pushed a patch to add this missing define. This should be resolved in the next release.
