### ISSUE TITLE
Behaviour of SetImageMask with CompositePixelMask looks bogus

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#3779]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-14 Q16 HDRI

### Operating system

Linux

### Operating system, version and so on

debian:9

### Description

I just added a test for using CompositePixelMask with MagickSetImageMask to the downstream PHP Imagick library. The code for [that test is here](https://github.com/Imagick/imagick/blob/745e49e8316ced0769846b98fd8f01d784338074/tests/289_Imagick_setImageMask_basic.phpt#L25-L64)

The test is drawing a white circle over a black background, and then using that as a mask over an image, before that image is blurred.

The test using WritePixelMask looks as expected:
![test_canvasPIXELMASK_WRITE_CHANNEL_DEFAULT](https://user-images.githubusercontent.com/1505719/120540588-c62f2080-c3e0-11eb-96e4-32be67e532e2.png)

However, the test using CompositePixelMask has a pretty surprising output:
![test_canvasPIXELMASK_COMPOSITE_CHANNEL_DEFAULT](https://user-images.githubusercontent.com/1505719/120539846-eca08c00-c3df-11eb-9917-4e73078d152f.png)

A close up shows some 'interesting' patterns.
![Screen Shot 2021-06-02 at 19 26 06](https://user-images.githubusercontent.com/1505719/120539872-f32f0380-c3df-11eb-9a9f-9cad3f9ee4e1.png)

The behaviour of CompositePixelMask does not look like it is intended behaviour. If that is intended behaviour, please could you clarify under which CompositePixelMask should/shouldn't be used?

### Steps to Reproduce

Reproduce case is the test in [PHPImagick](https://github.com/Imagick/imagick/blob/745e49e8316ced0769846b98fd8f01d784338074/tests/289_Imagick_setImageMask_basic.phpt#L25-L64)

I've just realised that it's not currently possible to just check that out and run a single command to reproduce it. If that's required I'll work on making that easier.

**Comment by urban-warrior** [comment]
A command-line example would be useful.  Our Imagick release runs against ImageMagick version 6.  And we have too many pending tasks to install Imagick from source against ImageMagick 7.

**Comment by Danack** [comment]
I can't actually see how to set a composite mask from the command line. It doesn't seem to be listed on  https://imagemagick.org/script/command-line-options.php or in convert.c 
      
I tried setting both the read and write mask, but that doesn't show the behaviour. But that matches the behaviour shown when doing the same through magickwand, i.e.  appears to work
```    
convert -read-mask test_mask.png -write-mask test_mask.png -blur 10x2 houghline_input_image.png  test_output.png
```

What's the correct option for setting via command line?

Test images are:
![test_mask](https://user-images.githubusercontent.com/1505719/120629425-b6a1ed00-c45d-11eb-977e-5320a7787cd8.png)

![houghline_input_image](https://user-images.githubusercontent.com/1505719/120629472-c02b5500-c45d-11eb-8eba-c23fd176184e.png)

**Comment by fmw42** [comment]
See the mask at https://legacy.imagemagick.org/Usage/compose/#compose

`convert image1 image2 mask -compose over -composite result`

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
