### ISSUE TITLE
convert creates malformed GIF (or did I misread the GIF spec?)

### ISSUE THREAD

**Issue by wlnirvana** [ImageMagick/ImageMagick#3786]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-13

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04

### Description

Images created with `convert` sometimes do not follow the [W3C GIF spec][1] because an application extension (rather than image descriptor or plain text extension) immediately follows the graphic control extension.

Further references:

1. The GIF grammar in the linked spec above is in appendex B
2. A nice [visualization][2] of GIF formats

[1]:https://www.w3.org/Graphics/GIF/spec-gif89a.txt
[2]:http://www.matthewflickinger.com/lab/whatsinagif/bits_and_bytes.asp

### Steps to Reproduce

```bash
$ convert -size 50x50 canvas:white tmp.gif
$ convert tmp.gif -depth 3 -colors 8  -colorspace gray malformed.gif
$ hexdump -C malformed.gif
00000000  47 49 46 38 39 61 32 00  32 00 f0 00 00 ff ff ff  |GIF89a2.2.......|
00000010  00 00 00 21 f9 04 00 00  00 00 00 21 ff 0b 49 6d  |...!.......!..Im|
00000020  61 67 65 4d 61 67 69 63  6b 0e 67 61 6d 6d 61 3d  |ageMagick.gamma=|
00000030  30 2e 34 35 34 35 34 35  00 2c 00 00 00 00 32 00  |0.454545.,....2.|
00000040  32 00 00 02 33 84 8f a9  cb ed 0f a3 9c b4 da 8b  |2...3...........|
00000050  b3 de bc fb 0f 86 e2 48  96 e6 89 a6 ea ca b6 ee  |.......H........|
00000060  0b c7 f2 4c d7 f6 8d e7  fa ce f7 fe 0f 0c 0a 87  |...L............|
00000070  c4 a2 f1 88 4c 2a 27 05  00 3b                    |....L*'..;|
```

Notice that at address `0x0000001b`, a byte sequence `21 ff 0b ...` is started, which corresponds to an application extension. But before this block is `21 f9 04 00 00  00 00 00`, i.e. a graphic control extension. According to the spec, an image descriptor or plain text extension should follow graphic control extension. Or did I misread the spec?

This seems violates the W3C GIF spec.

### Images

![malformed](https://user-images.githubusercontent.com/3822785/120612427-c8988580-c487-11eb-80ab-dbf060d550ce.gif)

**Comment by urban-warrior** [comment]
Does the spec say "should follow" or "must follow"?  Either way its easy enough to change the order.  We'll add a patch to reorder the extensions.
