### ISSUE TITLE
floating windows of display are not properly sized in i3

### ISSUE THREAD

**Issue by Docbroke** [ImageMagick/ImageMagick#379]
When image is opened with display, all windows other then command window specify "1 by 1" size, as shown by xprop. So every window requires to be manually resized, before it can be used..
```
┌─[Wed Feb 15][11:50:27][~]
└─╼ xprop
_NET_WM_STATE(ATOM) = 
_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
WM_TRANSIENT_FOR(WINDOW): window id # 0x2c00083
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLASS(STRING) = "display", "Display"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		window id # of group leader: 0x2c00083
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 683, 683
		program specified size: 1 by 1
		program specified resize increment: 1 by 1
		program specified base size: 1 by 1
		window gravity: NorthWest
WM_CLIENT_MACHINE(STRING) = "pathy"
WM_COMMAND(STRING) = { "display", "Pictures/wallpaper/chaku.jpg" }
WM_ICON_NAME(STRING) = "Browse and Select a File"
WM_NAME(STRING) = "Browse and Select a File"
```

**Comment by mikayla-grace** [comment]
When we display an image, we get properly sized windows as expected.  What version of ImageMagick are you using?  What is your OS and its release version?  Are you using X11 or XWayland?

**Comment by Docbroke** [comment]
imagemagick 6.9.7.8-1
OS archlinux (4.9.8-1-ARCH x86_64)
wm i3 on X11

**Comment by mikayla-grace** [comment]
Unfortunately we do not have access to the i3 window manager to trace the problem.  The display program appears to work with any other window manager, at least all the ones we tested.  Can you try another windows manager under archlinux and see if the windows appear properly.

**Comment by Docbroke** [comment]
I tried with openbox, and windows appeared correctly.  It appears that issue is with i3 (though this has not happened with any other applications I have used) or it may be a common issue with tiling window managers.
What is surprising is that command window (one that appears on left click, is properly sized but all subsequent windows needs to be resized. So there is some difference in the way command window and other windows gives sizing hint to window managers.

**Comment by Airblader** [comment]
As seen at the issue over at i3, imagemagick sets a hint requesting to be 1x1. i3 respects this hint. We'll need to figure out why imagemagick makes this request.

**Comment by mikayla-grace** [comment]
The display program creates a number of X windows with a default size of 1x1, however, they are initialized as withdrawn.  When they are needed, they are reconfigured to the proper size.  Its possible I3 is ignoring the WithdrawnState state and mapping the windows at their initialized width / height of 1.  If you type

```
display
```
you should only get one window, the ImageMagick logo.  If you get other windows, its likely the window manager is ignoring the WithdrawnState manager hint.

For further analysis, debug the X11 events:

```
display -debug X11
```

**Comment by Airblader** [comment]
i3 does not touch withdrawn windows. Perhaps the issue is order of operations. A common problem we see in X clients is that they change things directly after mapping the window when they should be doing it before mapping the window. 

Also note that the issue here is not that the actual geometry of the window is 1x1 but that the window sets an explicit hint that it wants to be 1x1.

**Comment by AndreSouzaAbreu** [comment]
This did happen with me to! It is hard to grab and resize the tiny window dialog that show up when using imagemmagick and i3wm

Still looking for an workaround

**Comment by sljunkie** [comment]
It's been 3 years and the problem still persists, yet both issues are closed on their respective trackers because nobody could pin down whose code is responsible, i3's or display's. Isn't there at least a workaround?

**Comment by urban-warrior** [comment]
The current workaround is to use some window manager other than i3 or don't use the ImageMagick display program.   The ImageMagick development team would issue a patch for this problem if it can be shown to be an issue within our code base.  The display program has worked flawlessly with tens of other window managers over the last 20 years or so.   We're not sure why it fails for the I3 manager.

**Comment by AndreSouzaAbreu** [comment]
I guess the solution is to use other window manager. There are plenty of window manager and many of them are way better than i3
