### ISSUE TITLE
Density change gets ignored by some files

### ISSUE THREAD

**Issue by papst01** [ImageMagick/ImageMagick#381]
I've some EPS where the density change does not work. That are my commands:
```
convert -alpha deactivate -density 300 IM1.eps IM1.jpg
identify -format "%x x %y" IM1.jpg
```
tells me: 300 x 300 as wished. But when I check with IrfanView or with windows itself or with paint.net it tells me 96pdi all the time. Photoshop CS2 on the other hand tells me 72dpi
Even if take this result jpg and convert it to another density it stays with 96dpi:
```
convert -density 150 IM1.jpg IM1_150dpi.jpg
identify -format "%x x %y" IM1_150dpi.jpg
150 x 150
```

But all the other tools tell me it is still 96dpi, but PS CS2 says 72dpi.

If I do these tests with "normal" pictures everything works

Tried with ImageMagick-6.9.7-8-Q16-x64-static.exe, also with ImageMagick-7.0.4-9-Q16-x64-static.exe and the magick.exe command

A pretty old version did not have this bug: ImageMagick-6.7.9-9-Q16-windows-x64-static.exe

Attached the example-file: [IM1.zip](https://github.com/ImageMagick/ImageMagick/files/782704/IM1.zip)

**Comment by mikayla-grace** [comment]
Add -strip to your command: ```convert -density 150 IM1.jpg -strip IM1_150dpi.jpg```.

**Comment by papst01** [comment]
Did not work :( whether when using the EPS as base or the IM1.jpg. 
Tried it with version: ImageMagick 6.8.9-8 Q16 x64 2014-08-26

**Comment by papst01** [comment]
Anyone? Still nothing?

**Comment by fmw42** [comment]
Your EPS file has no units specified. Try 

`convert -units pixelsperinch -density 150 IM1.eps -strip IM1.jpg`

Note that Photoshop often uses its own density in its meta data. But see if this works.

**Comment by amelio-vazquez-reina** [comment]
@fmw42 The command you wrote above doesn't work for me:

```
$ ls -ahl
total 272
-rw-r--r--@ 1 amelio  staff   134K Sep 13 12:17 input.jpg

$ magick convert input.jpg -units pixelsperinch -density 150 output.jpg -strip output.jpg
convert: unable to open image 'output.eps': No such file or directory @ error/blob.c/OpenBlob/3146.
```
