### ISSUE TITLE
conversion to avif multipage keeps writing first page instead of each page

### ISSUE THREAD

**Issue by user98723784** [ImageMagick/ImageMagick#3812]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-8

### Operating system

Linux

### Operating system, version and so on

linux x64 5.10

### Description

convert mypages.tif mypages.avif

If mypages.tif contain 3 pages, the resulting mypages.avif will contain 3 pages also, but all 3 are from page 1 of mypages.tif
Also happens with Magick++ using writeImages()

Compiled with 
libheif 1.11.0
aom master from April 23th

### Steps to Reproduce

convert mypages.tif mypages.avif

and also

convert page1.png page2.png page3 png mypages.avif

**Comment by dlemstra** [comment]
You are experiencing the same issue that was reported here: #3712. Upgrading to the most recent version should resolve your issue.
