### ISSUE TITLE
SVG hangs handling class in <defs>

### ISSUE THREAD

**Issue by marcusclip** [ImageMagick/ImageMagick#3818]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.0.11-14

### Operating system

Linux

### Operating system, version and so on

Amazon Linux, like rhel fedora 2018.03

### Description

It seems when using a class within <defs> a certain way the SVG parser gets caught in an infinite loop.

During my debugging of the SVG I found that this happens if the class definition in question is the last one, i.e.

&lt;style&gt;
.cls {filter:url(#f1);}
&lt;/style&gt;

When adding a dummy class below it, it will no longer hang, e.g.

&lt;style&gt;
.cls {filter:url(#f1);}
.x{}
&lt;/style&gt;

### Steps to Reproduce

The test image is as follows (hanging.svg):

&lt;?xml version="1.0"?&gt;
&lt;svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10" width="10" height="10"&gt;
&lt;defs&gt;
&lt;style&gt;
.cls {filter:url(#f1);}
&lt;/style&gt;
&lt;filter id="f1" x="0" y="0" width="10" height="10"><feGaussianBlur in="SourceGraphic" stdDeviation="10"/&gt;&lt;/filter&gt;
&lt;mask id="mask" x="0" y="0" width="10" height="10" maskUnits="userSpaceOnUse"&gt;
&lt;rect class="cls" x="0" y="0" width="5" height="5"/&gt;
&lt;/mask&gt;
&lt;/defs&gt;
&lt;rect x="0" y="0" width="10" height="10"/&gt;
&lt;/svg&gt;

> convert hanging.svg hanging.png

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by marcusclip** [comment]
Thanks for the super quick response! It no longer hangs, but now there's a new issue. It seems it can longer find the class. Here's a test image:

&lt;?xml version="1.0"?&gt;
&lt;svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10" width="10" height="10"&gt;
&lt;defs&gt;
&lt;style&gt;
.cls{fill:#3333cc;}
&lt;/style&gt;
&lt;/defs&gt;
&lt;rect class="cls" x="0" y="0" width="10" height="10"/&gt;
&lt;/svg&gt;

> convert hanging.svg hanging.png

Now it reports:
convert: non-conforming drawing primitive definition `ill' @ error/draw.c/RenderMVGContent/4470.

Before the patch this svg worked without issue.

**Comment by urban-warrior** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
