### ISSUE TITLE
I get some errors when using ImageMagick

### ISSUE THREAD

**Issue by skyleelove** [ImageMagick/ImageMagick#384]
Hi,

    I get this error "UnableToExtendPixelCache `Success' @ fatal/cache.c/CacheSignalHandler/3625"
My Server is crash.How to solve this problem.Thanks a lot.
   ImageMagick version:6.9.6-2

**Comment by mikayla-grace** [comment]
You are processing a large image and you ran out of temporary disk space.  Use  -define registry:temporary-path to push the pixel cache to an area with plenty of free disk space.  See https://www.imagemagick.org/script/architecture.php#tera-pixel.

**Comment by skyleelove** [comment]
Hi,
     Thanks for your answer,one more question,when processing a large image,if Imagemagick ran out of memory,and then use the disk space or it only use disk space and not use memory?Thank you very much.

**Comment by mikayla-grace** [comment]
See https://www.imagemagick.org/script/architecture.php#cache for how the pixel cache is allocated.
