### ISSUE TITLE
Animated PNG (APNG) format reading is incorrect

### ISSUE THREAD

**Issue by FurkanGozukara** [ImageMagick/ImageMagick#3847]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.1.0-0

### Operating system

Windows

### Operating system, version and so on

Windows 10 latest

### Description

ImageMagick reads the APNG file within an incorrect way

I have tested with both Magick.NET and ImageMagick windows installation version ImageMagick-7.1.0-0-Q16-HDRI-x64-dll.exe

So here let me explain

This is the image I am testing : https://static.pokemonpets.com/images/npcTrainers/trainer15202down.png

You can also test

When I read the APNG image as below it reads the image have 607 frames

![image](https://user-images.githubusercontent.com/19240467/122645075-13212f80-d121-11eb-9b1e-5a2ca24ff25a.png)

However in reality the image has only 66 frames

Here with another library reading

![image](https://user-images.githubusercontent.com/19240467/122645093-3e0b8380-d121-11eb-96ed-52c5ed6c83b4.png)

So when I execute the below command the output I am getting have almost 10x file size and it has black background

Black background and very big size also happened in Magick.NET

`magick "apng:c:/temp/a.png" -quality 100 -define webp:lossless=true "c:/temp/a.webp"`

![image](https://user-images.githubusercontent.com/19240467/122645132-7dd26b00-d121-11eb-97fb-0f49356b4bc8.png)

![image](https://user-images.githubusercontent.com/19240467/122645142-89259680-d121-11eb-94df-9ade6ef7e388.png)

[a.zip](https://github.com/ImageMagick/ImageMagick/files/6680821/a.zip)

Here my path set FFMPEG

![image](https://user-images.githubusercontent.com/19240467/122645149-95a9ef00-d121-11eb-8c2f-2d44a031cc8a.png)

I am 100% sure this is a bug. If not otherwise please point me correct command

### Steps to Reproduce

Download this image and execute below code

https://static.pokemonpets.com/images/npcTrainers/trainer15202down.png

`magick "apng:c:/temp/a.png" -quality 100 -define webp:lossless=true "c:/temp/a.webp"`

### Images

![a](https://user-images.githubusercontent.com/19240467/122645173-b40fea80-d121-11eb-9a3b-0c4f0590e7c1.png)

**Comment by dlemstra** [comment]
The reason that you are getting this huge number of frames is because we extract all the frames. It looks like the other library seems to be doing something that prevents duplicatation of frames. We will need to investigate it would be possible to add an option to prevent this from happening.

**Comment by dlemstra** [comment]
The next version of ImageMagick will include an option (`video:vsync`) to set the `-vsync` setting of `ffmpeg`. This will also become available in the next version of Magick.NET in the form of a `VideoReadDefines` class.

**Comment by FurkanGozukara** [comment]
@dlemstra awesome thank you very much. when is approximate date of next version release?

**Comment by dlemstra** [comment]
I don't know when the next release of Magick.NET will become available. Might be next week, might be next month.

**Comment by faran-tenovos** [comment]
@FurkanGozukara have you gotten around the problem for black background for the apng attached above?

**Comment by FurkanGozukara** [comment]
@faran-tenovos for APNG I have used an outdated library :( : https://github.com/Benny-/apng2webp

I haven't tested new version of magick.net yet

**Comment by faran-tenovos** [comment]
@FurkanGozukara Ok thanks
@dlemstra can you let me know how I can get vsync working on imagemagick linux binary

**Comment by dlemstra** [comment]
You can find that answer here: https://github.com/dlemstra/Magick.NET/discussions/962

**Comment by faran-tenovos** [comment]
@dlemstra I've been through here. I'm using ImageMagick Linux binary and covert using
**magick "apng:c:/temp/a.png" -quality 100 -define webp:lossless=true "c:/temp/a.webp"**
So how do I tell ImageMagick from here to use vsync option for ffmpeg?

**Comment by dlemstra** [comment]
You can do that by adding `-define video:vsync=value` before the file is read.

**Comment by faran-tenovos** [comment]
@dlemstra thanks

**Comment by faran-tenovos** [comment]
@dlemstra I've tried the option as `-define video:vsync=0 and -define video:vsync=1` it doesn't solve the duplicate frames issue. Neither does it solve the black background issue.

**Comment by dlemstra** [comment]
And the version you are on is the latest? This vsync option has been added recently.

**Comment by faran-tenovos** [comment]
@dlemstra I've tried it on the 7.1.0-2 Both Windows and Ubuntu
with the following command
` magick apng:sample3.png -size 100x100 -define video:vsync=0 temp/png/sample3.png`
I get 607 images all with black background on the image attached by OP

**Comment by dlemstra** [comment]
As I said before you will need to specify it before you read the file. You will need to put it right after the `magick` command.

**Comment by faran-tenovos** [comment]
@dlemstra sorry my bad, it works now but the background is still black should I open another bug for it?

**Comment by dlemstra** [comment]
Please open a new issue for that instead. It is possible that this is an issue inside `ffmpeg` but we will need to investigate that.
