### ISSUE TITLE
Eating RAM or normal when batch processing multiple PNG?

### ISSUE THREAD

**Issue by jonathancolledge** [ImageMagick/ImageMagick#3849]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.1.0-1-Q16-HDRI-x64-dll

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

I use this command:
magick *.png -distort barrel "0.00698 -0.0299 -0.13124" +adjoin -scene 00000001 Magicked/frame_%08d.png

But when there are many images in the folder (they are only 1920x1080) it just eats up RAM then gives numerous errors (please see attached image) like this:
magick: unable to extend cache 'frame_00003253.png': No space left on device @ error/cache.c/OpenPixelCache/3902.
magick: TooManyExceptions (exception processing is suspended) @ warning/exception.c/ThrowException/1049.
magick: unable to extend cache 'frame_00003254.png': No space left on device @ error/cache.c/OpenPixelCache/3902.

The above command is very simplified, if it isn't, it doesn't get that far. It seems to be loading all the images to RAM before processing. It chews up all my 96 Gb of RAM, then throws the error.

Is this how it should work? Is my command wrong? I just assumed it would do several images at a time, not the whole lot! (In the image, I actually moved a lot of the files - originally I had >10,000 in the folder).
![Magick Problem](https://user-images.githubusercontent.com/4342400/122865423-4c72be80-d31e-11eb-9af0-fe4eed5ef54a.jpg)
Any help is greatly appreciated, please.
Thanks,
Jonathan

### Steps to Reproduce

Chuck a load of HD images (>3500) into one folder then run:

magick *.png -distort barrel "0.00698 -0.0299 -0.13124" +adjoin -scene 00000001 Magicked/frame_%08d.png

### Images

You'll need 3500 of these!
![frame_00000017](https://user-images.githubusercontent.com/4342400/122865996-2bf73400-d31f-11eb-850b-c40a831c57fa.png)
![frame_00000018](https://user-images.githubusercontent.com/4342400/122866000-2c8fca80-d31f-11eb-9854-c3865312a5ee.png)
![frame_00000014](https://user-images.githubusercontent.com/4342400/122866001-2c8fca80-d31f-11eb-8103-399dd0661413.png)
![frame_00000015](https://user-images.githubusercontent.com/4342400/122866003-2d286100-d31f-11eb-984f-6c5270a9d61b.png)
![frame_00000016](https://user-images.githubusercontent.com/4342400/122866005-2dc0f780-d31f-11eb-9969-6d9926bf2e9b.png)

**Comment by snibgo** [comment]
> It seems to be loading all the images to RAM before processing.

Yes, that is correct.

>  I just assumed it would do several images at a time, not the whole lot!

"magick mogrify" will do that. The syntax is slightly different to a plain "magick" command, something like this:
```
magick mogrify -distort barrel "0.00698 -0.0299 -0.13124" -path Magicked *.png
```

**Comment by jonathancolledge** [comment]
I edited the policy.xml and uncommented the temp file. That seems to work but it takes an age. I think your mogrify way seems faster. Thanks.
