### ISSUE TITLE
Statistics output of grayscale image changed since 7.0.4-7

### ISSUE THREAD

**Issue by brechtm** [ImageMagick/ImageMagick#385]
I used to use this command to check whether an image is grayscale or not:

`convert image.jpg -colorspace HSL -channel g -separate +channel -format %[fx:mean] info:`

For a grayscale JPEG, 7.0.4-7 outputs `0`. For the same image, 7.0.4-9 and 7.0.4-10 output `001`.

I don't claim to understand what the above command does exactly, but it seems to output three numbers now instead of a single one. This is apparent from the output for a colour image:

- 7.0.4-7: `0.014278`
- 7.0.4-9: `0.006220050.0142780.989673`

Is this new behaviour expected?

Possibly related: [Problems with Image Statistics (fx:maxima etc.)](https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=31377)

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by brechtm** [comment]
Seems to be fixed in 7.0.5-0. Thanks!
