### ISSUE TITLE
`-layers optimize` makes animation transparent and empty

### ISSUE THREAD

**Issue by njdoyle** [ImageMagick/ImageMagick#3859]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.1.0-1

### Operating system

Linux

### Operating system, version and so on

Ubuntu 18.04

### Description

For some input images, using `-layers optimize` produces entirely empty transparent output instead of the expected image.

### Steps to Reproduce

```
magick test.gif -layers optimize output.gif
```

### Images

test.gif
![test](https://user-images.githubusercontent.com/316852/123147978-b037dd00-d42d-11eb-9ec4-1501cb32fa60.gif)

brokenOutput.gif (it's invisible)
![brokenOutput](https://user-images.githubusercontent.com/316852/123147990-b463fa80-d42d-11eb-90bc-8a172e97b501.gif)

**Comment by fmw42** [comment]
I can confirm that on Mac OSX Sierra, IM 7.1.0.1 Q16. Likely due to a 1 pixel wide image.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
