### ISSUE TITLE
1px thick crop fails to give proper results

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#3869]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [x] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.1.0.1

### Operating system

MacOS

### Operating system, version and so on

Sierra

### Description

A crop with 1px thick dimension gives error.

### Steps to Reproduce

![tmp3_floodfill](https://user-images.githubusercontent.com/13458218/123493839-a1d6f600-d5d2-11eb-8b1c-388654e482a3.png)

Both the following commands fail on IM 7.1.0.1 Q16 Mac OSX Sierra

`magick tmp3_floodfill.png[1x416+0+0] t1.png`

`magick tmp3_floodfill.png -crop 1x416+0+0 t1.png`

**magick: geometry does not contain image `tmp3_floodfill.png' @ warning/transform.c/CropImage/594.**

Resulting image is 1x1 px and not the 416 pixels in height in the image

`magick identify t1.png`
t1.png PNG 1x1 500x500-1-1 8-bit Grayscale Gray 438B 0.000u 0:00.000

**P.S.  I think this may be an issue because the image contains a virtual canvas offset and works if I add a +repage**

**Comment by snibgo** [comment]
You have answered your own question.

Your input PNG has a virtual canvas with an offset, so there is no pixel at coordinate (0,0) on the canvas. If you want to ignore this virtual canvas, use "+repage" after reading the image.

I suspect you made the input with ImageMagick. You might consider using "+repage" before writing the output file.

**Comment by fmw42** [comment]
Yes, I finally realized the virtual canvas affected the crop. I was hoping to crop and have the virtual canvas aggregate. But that did not work, so I finally just did the +repage and kept track of the offsets in variables. I will close this post.
