### ISSUE TITLE
Bug: Strange image degradation when using imagick module

### ISSUE THREAD

**Issue by mpek** [ImageMagick/ImageMagick#387]
I cannot use a picture and some others, because it looks awful, and nothing like it shows in preview on desktop. For further explanation, there is a thread on wordpress.org, perhaps you'd like to visit:

https://wordpress.org/support/topic/strange-image-degradation/

If you have further question, I'd be happy to help.

**Comment by dlemstra** [comment]
We do not write or maintain the imagicklibrary. I think you will need to open an issue: https://github.com/mkoppanen/imagick

**Comment by mpek** [comment]
Thank you!
