### ISSUE TITLE
imagemagick.org is down

### ISSUE THREAD

**Issue by brian-gates** [ImageMagick/ImageMagick#3872]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

n/a

### Operating system

Windows

### Operating system, version and so on

n/a

### Description

imagemagick.org is down

https://downforeveryoneorjustme.com/imagemagick.org?proto=http

![image](https://user-images.githubusercontent.com/97096/123524377-a78a1580-d67e-11eb-982a-b717ee2b33de.png)

![image](https://user-images.githubusercontent.com/97096/123524343-6265e380-d67e-11eb-9fc5-147a06e6a230.png)

### Steps to Reproduce

Visit http://imagemagick.org/ in your browser

**Comment by fmw42** [comment]
There are some repairs going on right now, I believe. So be patient. It will return as soon as possible.
