### ISSUE TITLE
MagickCLI

### ISSUE THREAD

**Issue by NickNaso** [ImageMagick/ImageMagick#388]
Can i use MagickCLI on ImageMagick version 6 or is it only available for version 7?

**Comment by fmw42** [comment]
The command line interface is basically the the same for both IM 6 and IM 7. The primary difference is that in IM 6 you use convert and in IM 7 you use magick as the basic command tool. If you need other tools such as identify, montage, mogrify, etc., then in IM 6 you just use them. In IM 7 you have to preface them with magick, such as magick identify.

**Comment by NickNaso** [comment]
Ok thanks for feedback
