### ISSUE TITLE
PECL not compiling due to lgomp library

### ISSUE THREAD

**Issue by LorenzoRogai** [ImageMagick/ImageMagick#3886]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.1.0-2

### Operating system

MacOS

### Operating system, version and so on

Big Sur 11.04

### Description

The command "pecl install imagick" doesn't work anymore since the last release. It was working fine with ImageMagick 7.0

The error while compiling is:

```
ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [imagick.la] Error 1
ERROR: `make' failed
```

The attempt to revert back to a previous version of ImageMagick using brew doesn't work

### Steps to Reproduce

brew install imagemagick
pecl install imagick

**Comment by urban-warrior** [comment]
We did not write nor do we maintain iMagick.  Contact the iMagick developers for assistance.  Another option is to install libgomp on your system.
