### ISSUE TITLE
APNG conversion has black background

### ISSUE THREAD

**Issue by faran-tenovos** [ImageMagick/ImageMagick#3891]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.1.0-2

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04

### Description

ImageMagick puts a black background on apng conversion to other formats such as gif or webp. I've tried other conversion tools and they maintain the transparency while IM does not.

### Steps to Reproduce

Download this image and execute below code

https://static.pokemonpets.com/images/npcTrainers/trainer15202down.png

magick apng:a.png a.webp 
OR
magick apng:a.png a.gif

### Images

![a](https://user-images.githubusercontent.com/60923612/124123891-3b018300-da91-11eb-96b3-5d4a46b5e3ed.png)

### UPDATE:
![sample0](https://user-images.githubusercontent.com/60923612/124506621-7bd8ff00-dde5-11eb-9fe8-ff2d3d7d7e14.png)

For the animated elephant image, it clears out the shadow when converting to either gif or webp. And sometimes the result too slow or too fast. In the case of elephant, it is slowed and in the case of the original image, its speed is increaseded.

**Comment by dlemstra** [comment]
Can you still reproduce this issue with the latest version @faran-tenovos?

**Comment by faran-tenovos** [comment]
@dlemstra there is no black background now. 
magick -define video:vsync=0 apng:test.png apng:ouput.png
Doing the above produces the target png/gif/webp at 4 to 5 times more speed than the original file

For the above elephant, the target png/gif/webp is slower than the original png.

How do I keep the original speed while converting apng to other formats?

**Comment by dlemstra** [comment]
That seems to be another issue, can you open a new issue for that?

**Comment by faran-tenovos** [comment]
ok. This is resolved in the latest versions
