### ISSUE TITLE
Mogrify regression: Should not overwrite input file when -write is specified

### ISSUE THREAD

**Issue by talklittle** [ImageMagick/ImageMagick#3893]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
- [X] I have verified that I am using the latest version of ImageMagick

### ImageMagick version

7.1.0-2

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04

### Description

Example command:

    mogrify -resize '50x50>' -write modified.png Lenna.png

Should not overwrite Lenna.png, but it does in broken ImageMagick versions.

**Working** versions:

* 6.9.10-23
* 7.0.11-9

**Broken** versions:

* 6.9.12-18
* 7.0.11-13
* 7.0.11-14
* 7.1.0-2

Suspected cause:

https://github.com/ImageMagick/ImageMagick/commit/49773ef93c0dd9b3b9653517a32790f533fcc8a1 (7.0.11-13)  
https://github.com/ImageMagick/ImageMagick6/commit/9d8e86156f0f2c949623bfbd5c78d6c89a7c5467 (6.9.12-14)  
Which were attempts to address https://github.com/ImageMagick/ImageMagick/issues/3676 relating to `+write` and `-write`

### Steps to Reproduce

```bash
$ ls -l Lenna.png  # see original size e.g. 473831
$ mogrify -resize '50x50>' -write modified.png Lenna.png
$ ls -l Lenna.png  # see it was overwritten, size is 5776
$ ls -l modified.png  # size is also 5776 as expected
```

**Comment by urban-warrior** [comment]
The `-write` option is an in-place image write providing the user an opportunity to write the source image in a different format, e.g. source image is JPEG, write image is PNG.  The current behavior is correct-- the source image is overwritten after any CLI options  are applied.  The `-format` or `-path` options are intended to write the source image in another format or path and leave the source image unmolested.  Any previous behavior was a side-effect of the bug we fixed.
