### ISSUE TITLE
Trim returns empty image on 1-pixel width input

### ISSUE THREAD

**Issue by HydrodynamicSynchrotron** [ImageMagick/ImageMagick#3896]
### ImageMagick version

6.9.11-60

### Operating system

Linux

### Operating system, version and so on

Ubuntu Mate 21.04 Hirsute

### Description

When I input an image with 1px width and use the "-trim" option, ImageMagick trims the whole image (returns an empty image).

### Steps to Reproduce

$ convert input.png -trim +repage output.png
convert-im6.q16: geometry does not contain image `input.png' @ warning/attribute.c/GetImageBoundingBox/519.

![input](https://user-images.githubusercontent.com/8970887/124465645-ef532000-dd95-11eb-8475-8dede2fc0e7a.png)

### Images

See above.

**Comment by snibgo** [comment]
Your image is on a canvas, with an offset, so the geometry of "-crop 1x1+0+0" will not contain the image. To correct that problem, use "+repage" after reading the image.

This gives a good result on IM v6.9.9-50:

```
f:\web\im>%IM%convert oneWide.png +repage -trim info:
oneWide.png PNG 1x10 1x90+0+64 8-bit Gray 0.000u 0:00.031
```

However, it gives a bad result on v7.0.10-45:
```
f:\web\im>%IMG701010%magick oneWide.png +repage -trim info:
magick: geometry does not contain image `oneWide.png' @ warning/attribute.c/GetI
mageBoundingBox/510.
oneWide.png PNG 1x1 0x0-1-1 8-bit Gray 354B 0.016u 0:00.160
```
I don't know why this is. Perhaps a bug in IM.

**Comment by HydrodynamicSynchrotron** [comment]
In my original version I also use +repage, but in this case it's the same for me:

```
$ convert input.png +repage -trim output.png
convert-im6.q16: geometry does not contain image `input.png' @ warning/attribute.c/GetImageBoundingBox/519.
```

**Comment by snibgo** [comment]
So it seems to be a bug introduced between v6.9.9-50 and 6.9.11-60, and carried forwards to v7.

**Comment by urban-warrior** [comment]
Starting at the corners, trim identifies the pixel color in the four corners then works inwardly until a pixel is located that does not match the corner color.  If we have a 1x10 image of solid red, for instance, The edge color is red so it trims but does not find any pixels that are not red so it ends up trimming all pixels.  Under those conditions, given a 0x0 pixel image is not possible, ImageMagick instead returns a single transparent pixel.    Given ImageMagick trim is behaving as expected, why do you consider it a bug? 

Stable behavior is expected between releases, however, a behavioral change is acceptable if it is a consequence of a discovered bug that we patch.  Here, the bug was the previous behavior prior to v6.9.9-5?.

**Comment by HydrodynamicSynchrotron** [comment]
> Starting at the corners, trim identifies the pixel color in the four corners then works inwardly until a pixel is located that does not match the corner color. If we have a 1x10 image of solid red, for instance, The edge color is red so it trims but does not find any pixels that are not red so it ends up trimming all pixels.

That's all fine and good, but that's not what I've provided in the example image. In the example image, on top and bottom there are entirely transparent pixels (expected to be trimmed) but in the middle there's a solid black line. That line is what I expect to end up in the trimmed image. This is not what happens and it very much looks like a bug.

**Comment by urban-warrior** [comment]
We use Gitlab dark mode and could not see your sample image.   Now that we downloaded it and reproduced the problem, we say:

Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by HydrodynamicSynchrotron** [comment]
Great, thank you!
