### ISSUE TITLE
Broken PNG resize

### ISSUE THREAD

**Issue by starkgate** [ImageMagick/ImageMagick#3902]
### ImageMagick version

7.0.11-13 Q16 x64 (Windows),  6.9.10-23 Q16 x86_64 (Linux)

### Operating system

Windows

### Operating system, version and so on

W10 v1803

### Description

Picture is worth a thousand words:  before and after a 200% resize
![2021-07-06_01-21-39](https://user-images.githubusercontent.com/12874678/124523720-851f9700-ddf8-11eb-8be8-fef42c46137a.png)

It only happens on some images and I can't really figure out why. It happens with both image magick 6.9 on Linux and 7.0 on Windows.

### Steps to Reproduce

Take one of the pictures uploaded in test.zip. Run `convert -resize 200% image.png test.png`, observe the resulting file.

### Images

Some textures to reproduce the issue (I uploaded one of the broken textures as well with the -broken suffix): [test.zip](https://github.com/ImageMagick/ImageMagick/files/6766473/test.zip)

**Comment by fmw42** [comment]
With Imgemagick 7, use magick not convert. Also it is important to put the commands in the proper order. Read the input first, then the resize, then the output

`magick image.png -resize 200% test.png`

Does it still fail?  If so, what is your version of libpng?

**Comment by snibgo** [comment]
Your first example (LightMapVector_Dir_0_0x00ABB39A-1x_BC1-smooth2-1x_SSAntiAlias9x.png) has very low alpha, the maximum being 1 on a scale of 0.0 to 255.0.

Your screenshots are with alpha off, so many of the colours are "false" in the sense that the pixels have coloured values but are fully transparent. When enlarged, they become transparent black.

With such low values of alpha, to retain some precision I suggest you use "-depth 16" before writing the output.

**Comment by fmw42** [comment]
Sorry, I did not see the zip link

**Comment by snibgo** [comment]
To get a prettier output, that retains the colours of fully-transparent pixels, you can resize the alpha channel separately, like this (Windows CMD command):
```
magick ^
  LightMapVector_Dir_0_0x00ABB39A-1x_BC1-smooth2-1x_SSAntiAlias9x.png ^
  ( +clone -alpha extract ) ^
  -alpha off -resize 200% -compose CopyOpacity -composite ^
  -depth 16 x4.png
```

**Comment by starkgate** [comment]
> 
> 
> To get a prettier output, that retains the colours of fully-transparent pixels, you can resize the alpha channel separately, like this (Windows CMD command):
> 
> ```
> magick ^
>   LightMapVector_Dir_0_0x00ABB39A-1x_BC1-smooth2-1x_SSAntiAlias9x.png ^
>   ( +clone -alpha extract ) ^
>   -alpha off -filter triangle -resize 200% -compose CopyOpacity -composite ^
>   -depth 16 x4.png
> ```

Thank you, this works. I have 2 questions:
- In what manner does the alpha get resized if it's considered as 'off' by -resize? Does the +clone part take care of the resize?
- Since the output file is depth 8, how does using depth 16 as an intermediary help in any way? Any floats that are too close to 0 after the resize will be rounded back down to 0 in the output file, right?

**Comment by starkgate** [comment]
> 
> 
> With Imgemagick 7, use magick not convert. Also it is important to put the commands in the proper order. Read the input first, then the resize, then the output
> 
> `magick image.png -resize 200% test.png`
> 
> Does it still fail? If so, what is your version of libpng?
> 
> Does it always happen on this same image? If so, please post the actual image and not a screen snap.

What is the difference between using convert and magick?

**Comment by snibgo** [comment]
> In what manner does the alpha get resized if it's considered as 'off' by -resize? Does the +clone part take care of the alpha's resize?

Yes. "( +clone -alpha extract )" creates a second image, which is grayscale, from the alpha channel. So the list contains a colour image with alpha, and a grayscale image with no alpha. "-alpha off" turns alpha off for both images, but this has an effect only on the first image. "-filter triangle -resize 200%" resizes both images. "-compose CopyOpacity -composite" copies the grayscale image into the colour image, and removes the grayscale image.

> Since the output file is depth 8, how does using depth 16 as an intermediary help in any way?

For me, using IM Q16, the output has 16 bits per channel per pixel. It should be also for you. Almost all your input values are 0, the rest are 1, on a scale of 0 to 255. Resizing creates alpha values between 0 and 1, which would get rounded to either 0 or 1. With 16 bits, the rounding is not so severe, and fewer values will be rounded to zero. But this may not be important to you.

> What is the difference between using convert and magick?

"convert" uses IM v6 syntax. "magick" uses IM v7 syntax. v7 syntax is better: it permits "%[fx:]" expressions in more places, the order of operations is more predictable, the syntax checking is better, and so on.

I am curious. Can you tell us what the image represents?

**Comment by starkgate** [comment]
Thank you for the great explanation. I've always found doing complex things with image magick to be quite difficult and confusing, but maybe I should start looking into it more in depth instead of relying on stackoverflow.

> I am curious. Can you tell us what the image represents?

Sure. These images are static light and shadow maps from the Mass Effect video game trilogy. They're used to reduce the amount of dynamic lighting that needs to be rendered in real-time in-game: these textures are just painted over the environments to give the illusion of dynamic lighting. The thing is, the vanilla textures are low resolution and compressed with BC1. I used some ESRGAN models to remove the BC1 artefacts and do some antialiasing. Then the idea was to resize them by 200% with a simple filter to have smoother gradients, which is where I needed image magick. There's about 40k of those to resize :)
