### ISSUE TITLE
ImageMagick convert tool writes a non-default TGA format and sets a metadata to tell third-party tools to adjust

### ISSUE THREAD

**Issue by illwieckz** [ImageMagick/ImageMagick#3903]
### ImageMagick version

7.1.0-3

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04.2 LTS “Focal Fossa” Linux 5.8.0-59-generic x86_64

### Description

This bug is related to #3844 (TGA code mistakenly uses the storage format convention as an orientation metadata and adds it to the actual orientation metadata). The bug can be reproduced when converting a PNG file with default orientation (orientation metadata unset) to TGA format (pixmap flipped vertically and orientation metadata set).

This would be similar to, when converting a PNG file without any orientation information to JPG, the toool would rotate counter-clockwise the pixmap prior to writing the JPG file and then set an Exif metadata to tell viewers to rotate clockwise again so it can be displayed like the PNG.

Also the behavior is not consistent, when converting from a TGA file with default orientation (orientation metadata unset) to TGA format, the produced TGA file keeps the original default orientation (pixmap not flipped vertically and orientation metadata unset).

### Steps to Reproduce

```sh
$ file from-bottom-left.png
from-bottom-left.png: PNG image data, 32 x 32, 4-bit colormap, non-interlaced

$ magick convert from-bottom-left.png png-to-tga.tga

$ file png-to-tga.tga
png-to-tga.tga: Targa image data - RGBA 32 x 32 x 32 - 8-bit alpha - top
```

```sh
$ file raw-bottom-left.tga
raw-bottom-left.tga: Targa image data - RGBA 32 x 32 x 32 - 8-bit alpha

$ magick convert raw-bottom-left.tga tga-to-tga.tga

$ file tga-to-tga.tga
tga-to-tga.tga: Targa image data - RGBA 32 x 32 x 32 - 8-bit alpha
```

### Images

[from-bottom-left.png](https://user-images.githubusercontent.com/2311649/124550154-8b316a00-de30-11eb-9afb-0ef1cd9c7681.png)

Alternate download link: https://gitlab.com/illwieckz/produce-reference-tga/-/raw/master/samples/from-bottom-left.png

[raw-bottom-left.tga.zip](https://github.com/ImageMagick/ImageMagick/files/6767697/raw-bottom-left.tga.zip)

Alternate download link: https://gitlab.com/illwieckz/produce-reference-tga/-/raw/master/samples/raw-bottom-left.tga

**Comment by illwieckz** [comment]
I used a wide tga corpus for some usage statistics: the list of maps and mods for the Tremulous game hosted at [betaserv.tk](https://betaserv.tk/paklist.html).

Tremulous is a game based on the `id Tech 3` game engine, hence making big usage of the TGA format.

I used a snapshot from April 9th 2021, there was 1748 `pk3` archives (I ignored one misnamed `.Pk3 one).

There was 24 473 TGA files in that corpus. A couple of ones may be bad files using another format like JPG but using a TGA extension, we can ignore them as well. It's about more than 24 400 TGA files being part of the study.

From that corpus of more than 24 400 TGA files, only 217 files used a non-default orientation.

The same way for many years not all JPG viewers were taking in account orientation metadata (motivating many projects to rewrite those files prior to distribution) and some kind of viewers may still exist, there may be some TGA viewers not reading the orientation metadata.

Not only those TGA orientation variants may be untested in third party software, but third party software using TGAs in the same way such big corpus expect to be used, most textures are expected to be tileable and/or to be rendered with single or continuous transformations (like blend, translation or rotations) or to represent circular data (like flares), making hard to notice an orientation mistake.

If both a level editor and a game engine sharing the same TGA loading code does not respect the orientation bits, the artist may just adjust the texture orientation in the game level file not noticing the file is not properly loaded to begin with, workarounding in the game level file a software bug. If in a later version such kind of software (level editor, game engine) adds support for TGA orientation, something that looked correctly would then look upside down because of the TGA loader properly applying the orientation after the update, then applying the orientation saved in the game level which was an unconscious workaround.

For example this historical TGA loader in id Tech 3 source code seems to make no usage of the TGA attribute field:

- [github.com/id-Software/Quake-III-Arena/common/imagelib.c:LoadTGABuffer](https://github.com/id-Software/Quake-III-Arena/blob/dbe4ddb10315479fc00086f08e25d968b4b43c49/common/imagelib.c#L850-L1054)

Outside of the question about how much such kind of software does not read the TGA orientation field

- This is a unexpected to produce files in a non-default format, especially when the source file used a default format.
- This is unexpected to rewrite the pixmap with a different the orientation then setting a metadata to revert the display back.
- The file format produced is unreliable, one can't do `magick convert ${source_file} output.tga` and expect all the files having the same format even if all source files were using default formats without any orientation metadata.

**Comment by dlemstra** [comment]
Please don't open new issues to make the same statement.

The orientation of your file `from-bottom-left.png` is not bottom left but top left. And that is why `file` reports `png-to-tga.tga` as `top`. Your other file (`raw-bottom-left.tga`) has a bottom left orientation and ImageMagick will preserve that orientation.

I really don't understand the point that you are trying to make. We currently read the orientation field and will set it on the image and we are not going to change that for your use case.

**Comment by illwieckz** [comment]
Those are two different issues even if they are related or may have a common cause: it's possible to fix this one without fixing the other one, and the other one can be fixed without this one. In fact this issue may even exist if issue #3844 did not exist.

**Comment by illwieckz** [comment]
> The orientation of your file `from-bottom-left.png` is not bottom left but top left.

Exactly, this the proof ImageMagick has a bug, the one described in #3844: a properly converted PNG image from a bottom left tga (as in TGA convention) is expected to produce a top left PNG (as in PNG convention), as you just noticed. Those are not metadata orientations, those are format conventions, like endianness or RGBA ordering, this is where the #3844 bug lies. But can we talk about #3844 bug in #3844 thread instead?

**Comment by dlemstra** [comment]
We do not consider this a bug.
