### ISSUE TITLE
Font's GPOS kerning table is ignored

### ISSUE THREAD

**Issue by joshuakraemer** [ImageMagick/ImageMagick#3905]
### ImageMagick version

7.0.11-12

### Operating system

Linux

### Operating system, version and so on

Void Linux, kernel 5.12.13_1

### Description

The "label" format and "annotate" commands correctly use a font's kerning information if it resides in a "kern" table:
```
magick -font Helvetica -density 96 -pointsize 32 label:'Test' /tmp/kern.png
```
![kern](https://user-images.githubusercontent.com/10373011/124640584-e5144d00-de8d-11eb-976a-619333f1a68d.png)

But the kerning information is ignored if it resides in a newer "GPOS" table ("T" and "e" should be rendered closer together):
```
magick -font Noto-Sans-Regular -density 96 -pointsize 32 label:'Test' /tmp/GPOS.png
```
![GPOS](https://user-images.githubusercontent.com/10373011/124636664-15a5b800-de89-11eb-8490-a5e6b6a17fbc.png)

By contrast, "GPOS" tables are respected with the "pango" format:
```
magick -font Noto-Sans-Regular -density 96 -pointsize 32 pango:'Test' /tmp/pango.png
```
![pango](https://user-images.githubusercontent.com/10373011/124636919-60bfcb00-de89-11eb-9845-f2bda89b2c39.png)

**Comment by dlemstra** [comment]
It seems that freetype does not have support for `GPOS`:

https://www.freetype.org/freetype2/docs/glyphs/glyphs-4.html:
> Note that OpenType fonts (OTF) provide two distinct mechanisms for kerning, using the ‘kern’ and ‘GPOS’ tables, respectively, which are part of the OTF files. Older fonts only contain the former, while recent fonts contain both tables or even ‘GPOS’ data only. FreeType only supports kerning via the (rather simple) ‘kern’ table. For the interpretation of kerning data in the (highly sophisticated) ‘GPOS’ table you need a higher-level library like ICU or HarfBuzz since it can be context dependent (this is, the kerning may vary depending on the position within a text string, for example).

No idea how or if we could add support for this.

**Comment by khaledhosny** [comment]
When imagemagic isbuilt with Raqm support enabled, it can handle this and other advanced text shaping requirements.

**Comment by joshuakraemer** [comment]
Thanks @khaledhosny, GPOS kerning works with raqm enabled.
