### ISSUE TITLE
+antialias is ignored with "pango" format

### ISSUE THREAD

**Issue by joshuakraemer** [ImageMagick/ImageMagick#3906]
### ImageMagick version

7.0.11-12

### Operating system

Linux

### Operating system, version and so on

Void Linux, kernel 5.12.13_1

### Description

Disabling antialiasing by `+antialias` does not work with the "pango" format.

### Steps to Reproduce

```
magick -font Helvetica -density 72 -pointsize 32 +antialias label:'test' -resize 200% /tmp/label.png
```
![label](https://user-images.githubusercontent.com/10373011/124638620-7504c780-de8b-11eb-9cc9-3bdb86ae1400.png)

```
magick -font Helvetica -density 72 -pointsize 32 +antialias pango:'test' -resize 200% /tmp/pango.png
```
![pango](https://user-images.githubusercontent.com/10373011/124638561-61f1f780-de8b-11eb-880e-8700108c68d9.png)

**Comment by fmw42** [comment]
I do not believe this is a bug. It is just a limitation of PANGO. PANGO has limited features. See https://developer.gnome.org/pygtk/stable/pango-markup-language.html for what is implemented.

**Comment by joshuakraemer** [comment]
Then please consider it as a feature request. I think only the following would need to be added to https://github.com/ImageMagick/ImageMagick/blob/main/coders/pango.c:
```
if (draw_info->text_antialias == MagickFalse)
	cairo_font_options_set_antialias(font_options, CAIRO_ANTIALIAS_NONE);
```

**Comment by fmw42** [comment]
I will leave further comment to the Imagemagick developers.

**Comment by dlemstra** [comment]
We just added support for this. This will become available in the next release of ImageMagick 7.

**Comment by joshuakraemer** [comment]
Thank you, @dlemstra!
