### ISSUE TITLE
SIGBUS when trying to convert very large image

### ISSUE THREAD

**Issue by avevad** [ImageMagick/ImageMagick#3917]
### ImageMagick version

7.1.0-2

### Operating system

Linux

### Operating system, version and so on

Linux 5.12.14-arch1-1 #1 SMP PREEMPT Thu, 01 Jul 2021 07:26:06 +0000 x86_64

### Description

`convert` gets killed with SIGBUS while converting a very large PPM image (~ 1.2 GB) to PNG

### Steps to Reproduce

`convert out.ppm out.png`, where `out.ppm` is very large image (>1 GB), example is in the section below

### Images

[out.tar.gz](https://github.com/ImageMagick/ImageMagick/files/6793657/out.tar.gz) - uncompress to get `out.ppm`
**WARNING:** uncompressed file size is about 1 GB

**Comment by urban-warrior** [comment]
You are running out of TMP space.  See https://imagemagick.org/script/architecture.php#tera-pixel for how to properly deal with large images.  See Pixel Cache Synchronize Policy in https://imagemagick.org/script/security-policy.php for a work-around.  Your command did work for us as we have plenty of free-space on the /tmp partition.

**Comment by avevad** [comment]
`/tmp` have 4GB free, why does `convert` need more to convert 1GB file?

**Comment by urban-warrior** [comment]
See https://imagemagick.org/script/architecture.php, section `Cache Storage and Resource Requirements`.
