### ISSUE TITLE
How to disable DPC feature?

### ISSUE THREAD

**Issue by skyleelove** [ImageMagick/ImageMagick#392]
Hi,
    I just want to use OpenMP feature,but DPC can not disbale.What can I do for this?Thank you very much!

**Comment by mikayla-grace** [comment]
We do not have an option to disable DPC.  Its enabled if your system supports sockets.

OpenMP is independent of DPC so we're not sure what your goal is.

**Comment by skyleelove** [comment]
CacheFatalError，this error will make my process crash.How can I do for this?

**Comment by dlemstra** [comment]
@skyleelove You could hack `distribute-cache.` and remove `#define MAGICKCORE_HAVE_DISTRIBUTE_CACHE` from that file and it will be disabled. I still don't know how that would cause an issue on your machine though.
