### ISSUE TITLE
Identify giving strange dimensions for pdf

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#3925]
### ImageMagick version

7.1.0.2

### Operating system

MacOS

### Operating system, version and so on

Sierra

### Description

**The dimensions presented for a pdf with identify are strange. Are they correct?**

The logo: image is 640x480. But identify is showing 18x13.  **What is 18x13?**

Identify -verbose says: 640x480 in pixels and 8.88889x6.66667 for presumably inches print size.

```
magick logo: logo.pdf

magick identify logo.pdf
logo.pdf PDF 18x13 18x13+0+0 16-bit sRGB 2757B 0.010u 0:00.002

magick identify -verbose logo.pdf
Image:
  Filename: logo.pdf
  Format: PDF (Portable Document Format)
  Mime type: application/pdf
  Class: DirectClass
  Geometry: 640x480+0+0
  Resolution: 72x72
  Print size: 8.88889x6.66667
  Units: Undefined
  Colorspace: sRGB
  Type: PaletteAlpha
  Base type: Undefined
  Endianness: Undefined
  Depth: 16/8-bit

```

### Steps to Reproduce

See above

### Images

See logo: image

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
