### ISSUE TITLE
CPU Throttle value doesn't change

### ISSUE THREAD

**Issue by tikendra-chand** [ImageMagick/ImageMagick#393]
I am trying to set CPU throttle for imagemagick and I have tried most of the options specified in docs, yet 'convert -list resource' shows 'Throttle: 0'. I have tried following options:

1. changed policy.xml  and un-commented line with value 3:  `<policy domain="resource" name="throttle" value="3"/>`
2. set the environment variable by putting this in .bashrc: export MAGICK_THROTTLE=5
3. put it in convert command options like this: convert -limit throttle 2 largenew.jpg large.png; which throws: convert: unrecognized resource type `throttle' @ error/convert.c/ConvertImageCommand/2014
4. export MAGICK_THROTTLE=5; in terminal

However 'convert -list resource' always shows 'Throttle: 0'. It works if I change other resource limits though, only throttle isn't working.

I have tried this with 'ImageMagick 6.8.9-9 Q16 x86_64' and 'ImageMagick 7.0.5-0 Q16 x86_64' on ubuntu 15.10.

Can you please fix this or let me know how to configure it if I am doing anything wrong?

**Comment by mikayla-grace** [comment]
We corrected the documentation, the environment variable is MAGICK_THROTTLE_LIMIT.  However, if you have a throttle security policy, it overrides the value of the environment variable.

We added a patch to support the -limit throttle option.

We're not sure why the throttle security policy does not work for you.  We added your policy to policy.xml and it returned expected results: Throttle: 3.  Can you post your security policy?  Perhaps there is a bug in the parser that is triggered in only limited circumstances.

**Comment by tikendra-chand** [comment]
This is mine policy.xml (/etc/ImageMagick-6/policy.xml)
![policy](https://cloud.githubusercontent.com/assets/9821274/23600765/46955514-0270-11e7-8c9d-1759014ef30e.png)

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by tikendra-chand** [comment]
Thanks for fixing it, its working fine in in 7.0.5-10. 
I need one help though:
If I am performing multiple operations in one command like this:
`convert ( -size 800x495 canvas:none ) (newimage.png -resize 1780x1200) -geometry -618-522 -composite changedimage.png`
Will this work (setting -limit option only once)?
`convert ( -size 800x495 canvas:none ) (newimage.png -resize 1780x1200) -geometry -618-522 -composite -limit throttle 100 changedimage.png`
Or do I need to set "-limit throttle 100" inside each sub-operations too?

**Comment by dlemstra** [comment]
@tikendra-chand You should put ` -limit throttle 100` at the start of your command.
