### ISSUE TITLE
-append results in files with half-size geometry; follow-on problems with -crop

### ISSUE THREAD

**Issue by gingerbeardman** [ImageMagick/ImageMagick#3932]
### ImageMagick version

- 7.0.11-13 Q16 x86_64 2021-05-17
- 7.1.0-2 Q16 x86_64 2021-06-25

### Operating system

- MacOS

### Operating system, version and so on

- 11.4 (20F71)

### Description

With some images the crop process ends early. 
In fact exactly half of the image is processed.

Identify shows the image as being half its actual height.

However, if I open and resave the problematic image, and after that run the crop command, then the whole image is cropped as expected.

### Steps to Reproduce

1. append two image of the same size vertically
```
magick $file1 $file2 -append $file3
```
2. run this command to convert a sprite sheet of equal sized frames into an animated GIF
```
magick -dispose background -delay 1 -loop 0 $file3 -crop 38x38 +repage output.gif
```
3. check output specifications
```
magick identify $file3
magick identify output.gif
```

### Images

- file1
  - 1216x418
  - ![twingo-table-38-38](https://user-images.githubusercontent.com/49612/125647108-31f00c73-bd53-4da9-bbb0-dfd8726b664d.png)
- file2
  - 1216x418
  - ![twingo-table-38-38](https://user-images.githubusercontent.com/49612/125647129-3f8a99db-9f41-429a-9648-f584c414255f.png)
- file3 (problem image)
  - generated by magick
  - identify 
    `twingo-table-38-38.png PNG 1216x836 1216x418+0+0 8-bit Grayscale Gray 66265B 0.000u 0:00.000`
  - file
    `twingo-table-38-38.png: PNG image data, 1216 x 836, 8-bit gray+alpha, non-interlaced`
  - ![twingo-table-38-38](https://user-images.githubusercontent.com/49612/125636866-6b0c5a27-db95-42dd-bcc3-c41c3ede5055.png)

- resaved image
  - opened and saved, without modifying any pixels, using another application
  - identify
    `resaved-table-38-38.png PNG 1216x836 1216x836+0+0 8-bit Grayscale Gray 47094B 0.000u 0:00.000`
  - file
    `resaved-table-38-38.png: PNG image data, 1216 x 836, 8-bit gray+alpha, non-interlaced`
  - ![resaved-table-38-38](https://user-images.githubusercontent.com/49612/125636939-014ffd08-eb2c-4323-a2b8-3401efeb1046.png)

**Comment by fmw42** [comment]
Your command:

`magick -dispose background -delay 1 -loop 0 125636866-6b0c5a27-db95-42dd-bcc3-c41c3ede5055.png -crop 38x38 +repage output.gif`

works fine for me on IM 7.1.0.2 Q16 Mac OSX Sierra.  

Why are you using convert on IM 7?  You should be using magick.  

Check to be sure that your /tmp directory is not choked.

If you want us to check both commands, then provide file1 and file2 for the first command.

**Comment by gingerbeardman** [comment]
When you say "works fine", how many frames are you seeing in the output.gif? 

There should be 704.

With the problematic geometry, I'm only seeing 352 frames.

I have just upgraded to 

> ImageMagick 7.1.0-2 Q16 x86_64 2021-06-25

The problem remains.

(Why `convert`? It is an alias for `magick` on my system.)

**Comment by gingerbeardman** [comment]
individual files for testing the append command have been added to the OP

**Comment by fmw42** [comment]
Add +repage to your command to get 704 frames.

`magick -dispose background -delay 1 -loop 0 125636866-6b0c5a27-db95-42dd-bcc3-c41c3ede5055.png +repage -crop 38x38 +repage output.gif`

**Comment by gingerbeardman** [comment]
That's great, thank you.

Is there any way to get the output from the -append command to have the correct geometry?

**Comment by fmw42** [comment]
Try adding +repage at the end of the append command.

**Comment by gingerbeardman** [comment]
Thanks.

So this is all expected behaviour?

**Comment by fmw42** [comment]
Yes. Because you are making one output from two inputs with the append. So the page geometry comes from the first image. Perhaps not the best result, but I think the way IM does things. So best to use +repage when geometry of output is different from the input as with -layers merge, -crop, -append, etc.

**Comment by gingerbeardman** [comment]
Many thanks! I now understand more.

Closing.
