### ISSUE TITLE
Multiple test-failures with OpenMP enabled

### ISSUE THREAD

**Issue by UnitedMarsupials** [ImageMagick/ImageMagick#3958]
### ImageMagick version

7.1.0-3

### Operating system

Other (enter below)

### Operating system, version and so on

FreeBSD-11/amd64

### Description

I tried to run tests after building, and was rather disappointed with the multitude of failures:
```
Testsuite summary for ImageMagick 7.1.0-3
============================================================================
# TOTAL: 86
# PASS:  49
# SKIP:  0
# XFAIL: 0
# FAIL:  37
# XPASS: 0
# ERROR: 0
```
Attaching the [build-log](https://github.com/ImageMagick/ImageMagick/files/6836960/IM7.log), and the [test-suite.log](https://github.com/ImageMagick/ImageMagick/files/6836962/test-suite.log).

### Steps to Reproduce

Configured thus:
```
--without-dps  --without-flif  --without-zstd --without-gcc-arch --with-bzlib --with-fftw --with-fontconfig --with-fpx --with-freetype --with-gvc --enable-hdri --with-heic --with-jbig --with-jpeg --with-openjp2 --with-lcms --with-lqr --with-lzma --with-modules --with-pango --with-png --with-raqm --with-raw --with-rsvg --with-tiff --with-webp --with-x --with-perl=/opt/bin/perl  --with-perl-options="MAKE=gmake" --with-threads --enable-openmp --with-gslib --with-wmf=yes --x-libraries=/opt/lib --x-includes=/opt/include --prefix=/opt
```

**Comment by dlemstra** [comment]
We just publised version `7.1.0-4`. Can you reproduce this issue with that version?

**Comment by UnitedMarsupials** [comment]
> We just publised version `7.1.0-4`. Can you reproduce this issue with that version?

Of course, I can -- the error-count is the same:
```
Testsuite summary for ImageMagick 7.1.0-4
============================================================================
# TOTAL: 86
# PASS:  49
# SKIP:  0
# XFAIL: 0
# FAIL:  37
# XPASS: 0
# ERROR: 0
```
 * [7.1.0-4 build log](https://github.com/ImageMagick/ImageMagick/files/6836996/IM7.1.0-4.log)
 * [test-suite.log](https://github.com/ImageMagick/ImageMagick/files/6836994/test-suite.log)

I gave the exact configuration-options -- is it difficult to reproduce?

**Comment by UnitedMarsupials** [comment]
With the OpenMP option disabled (no other changes), all tests pass:
```
Testsuite summary for ImageMagick 7.1.0-4
============================================================================
# TOTAL: 86
# PASS:  86
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```

**Comment by urban-warrior** [comment]
ImageMagick has OpenMP-enabled loops throughout the distribution.  We have had perhaps less than ten bug reports over the years, otherwise OpenMP works flawlessly with a considerable performance boast.   Our unit tests pass on Fedora, CentOS, Ubuntu, and Windows OS'es before any release.  Its possible there is a bug in your compile chain or OpenMP library.   You could try `gdb` and when it fails, grab a stack trace and post it here.  In the mean-time, we'll try to fire up a FreeBSD VM and see if we can reproduce the problem

**Comment by UnitedMarsupials** [comment]
FreeBSD uses clang/llvm, which is, likely different from most of your -- gcc-based -- test-beds. That said, I just had the same problem on FreeBSD-12/amd64 as well, so it is not a random "fluke", unfortunately.

**Comment by urban-warrior** [comment]
We just compiled on FreeBSD-12/amd64, clang 8.0.1, with OpenMP-enabled and all the unit tests passed without complaint.  We verified OpenMP is enabled, its version 3.1.  We're not sure why its failing for you.

**Comment by UnitedMarsupials** [comment]
> We just compiled on FreeBSD-12/amd64, clang 8.0.1

This is a strange version -- the stock version of clang on FreeBSD-12 is:
```
FreeBSD clang version 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2)
Target: x86_64-unknown-freebsd12.2
Thread model: posix
InstalledDir: /usr/bin
```
Also, were you using the same configure-flags as I posted up above -- to include/enable all of the same "delegates"?

**Comment by urban-warrior** [comment]
Yes, we used your configure command-line.  Since you are using modules, did you `ldconfig` your /opt path so ImageMagick can load the dynamic coder modules?

**Comment by UnitedMarsupials** [comment]
> did you ldconfig your /opt path so ImageMagick can load the dynamic coder modules?

Yes, ports do that automatically.

I think, I found, what it is. For some reason, when OpenMP-option is enabled, FreeBSD port drags in gcc-10, tells ImageMagick to use _that_:
```
...
checking whether build environment is sane... yes
checking whether gmake supports the include directive... yes (GNU style)
checking for gcc... gcc10
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
...
```

The mixture -- delegates are built with the stock compiler -- is not healthy. According to gdb, all of the segfaults are deep inside gcc-installed libraries. After I removed the part of the port, that switches to gcc, tests passed on one machine (FreeBSD-11):
```
Testsuite summary for ImageMagick 7.1.0-4
============================================================================
# TOTAL: 86
# PASS:  86
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
```
The other machine -- FreeBSD-12 -- also no longer a problem with crashes, but reported the following strange-looking errors (as it was reporting in the earlier logs too):
```
--- tests/validate-formats-map.log ---
ERROR: tests/validate-formats-map.tap - too few tests run (expected 1, got 0)
--- tests/validate-formats-memory.log ---
ERROR: tests/validate-formats-memory.tap - too few tests run (expected 1, got 0)
--- tests/validate-formats-disk.log ---
ERROR: tests/validate-formats-disk.tap - too few tests run (expected 1, got 0)
--- test-suite.log ---
============================================================================
Testsuite summary for ImageMagick 7.1.0-4
============================================================================
# TOTAL: 86
# PASS:  83
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 3
```
The three errors are all in the FPX-delegate:
```
Abort trap (core dumped)
  test 158: FPX/Undefined/Grayscale/8-bits... pass.
  test 159: FPX/Undefined/GrayscaleAlpha/8-bitsnot ok
ERROR: tests/validate-formats-disk.tap - too few tests run (expected 1, got 0)

--
Abort trap (core dumped)
  test 160: FPX/Undefined/Palette/8-bits... pass
  test 161: FPX/Undefined/PaletteAlpha/8-bitsnot ok
ERROR: tests/validate-formats-map.tap - too few tests run (expected 1, got 0)

--
Abort trap (core dumped)
  test 156: FPX/Undefined/TrueColor/8-bits... pass.
  test 157: FPX/Undefined/TrueColorAlpha/8-bitsnot ok
ERROR: tests/validate-formats-memory.tap - too few tests run (expected 1, got 0)
```
I'll try to understand, what's happening there -- only on FreeBSD-12.

Regarding OpenMP, I'll be filing a FreeBSD bug-report.
