### ISSUE TITLE
CacheFatalError.This error will make my process crash

### ISSUE THREAD

**Issue by skyleelove** [ImageMagick/ImageMagick#397]
CacheFatalError.This error will make my process crash.How can I do for this to my process not crash when throw this exception.Thank you very much!

**Comment by mikayla-grace** [comment]
A fatal error always causes ImageMagick to exit.  Its not recoverable.  The solution is to  avoid the exception.  We would need to know the associated message for the cache exception before we can advise how to avoid the exception.

**Comment by dlemstra** [comment]
@skyleelove Can you give us more information?
