### ISSUE TITLE
Changing temp folder used by imagemagick?

### ISSUE THREAD

**Issue by sebastienratez** [ImageMagick/ImageMagick#399]
Hi,

I'd like to know how I can change the default folder used to store temp images by imagemagick, when executed from nodejs.

Thank you

**Comment by mikayla-grace** [comment]
You can set the temporary path security policy, see https://www.imagemagick.org/script/security-policy.php.  Or you can a environment variable, see https://www.imagemagick.org/script/resources.php.  Or you can set the path from the command line, see https://www.imagemagick.org/script/architecture.php#tera-pixel.

**Comment by sebastienratez** [comment]
Thanks - but does any of this work with nodejs (i.e. from javascript)? I don't have access to the O/S nor filesystem

**Comment by mikayla-grace** [comment]
The security policy configures ImageMagick.  It doesn't matter where its launched from: command-line, from an API, or from nodejs.

**Comment by dlemstra** [comment]
@sebastienratez Can we close this issue?

**Comment by sebastien-ratez-nec** [comment]
Yes
