### ISSUE TITLE
Converting animated gif to webp with resizing and layers -OptimizePlus makes wrong image proportion

### ISSUE THREAD

**Issue by w00dg1n** [ImageMagick/ImageMagick#3991]
### ImageMagick version

7.0.11-0 Q16

### Operating system

MacOS

### Operating system, version and so on

BigSur 11.0.1

### Description

Converting animated gif to webp with resizing and layers -OptimizePlus makes wrong image proportion

### Steps to Reproduce

`convert silver-massage-gun-phoenix-a2-gif_1600x.gif -verbose -coalesce -layers OptimizePlus -define webp:low-memory=true -define webp:method=3 -define webp:thread-level=0 -thumbnail 200x200 -quality 90 webp:result_200x200.webp`

### Images

![silver-massage-gun-phoenix-a2-gif_1600x](https://user-images.githubusercontent.com/48710739/127316232-1708d894-d358-47f1-b539-5c13f5cfd5f4.gif)

**Comment by snibgo** [comment]
You optimize layers, and then resize. I suspect optimizing layers should be the _final_ operation.

**Comment by w00dg1n** [comment]
@snibgo thanks a lot for quick anwer!
So this command works great
```
convert silver-massage-gun-phoenix-a2-gif_1600x.gif -verbose -coalesce  -define webp:low-memory=true -define webp:method=3 -define webp:thread-level=0 -thumbnail 200x200 -quality 90 -layers OptimizePlus webp:result_200x200.webp
```
