### ISSUE TITLE
APNG conversion has speed issue

### ISSUE THREAD

**Issue by faran-tenovos** [ImageMagick/ImageMagick#3992]
### ImageMagick version

7.1.0-4

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04

### Description

ImageMagick conversion from apng conversion to other formats such as gif, webp or apng has speed issues. The image either gets sped up to 5 times or very slow.

### Steps to Reproduce

I've used the following command.
magick -define video:vsync=0 apng:test.png apng:ouput.png

### Images

![sample1](https://user-images.githubusercontent.com/60923612/127318359-80ca7da1-3fe2-4a77-9d5e-f037d3e65b6f.png)
![sample2](https://user-images.githubusercontent.com/60923612/127318239-1d7136f0-f020-4808-99db-8ac279ec6858.png)

**Comment by urban-warrior** [comment]
Add the `-delay` option to your command-line to control playback speed.

**Comment by faran-tenovos** [comment]
I did I've used -delay 1x25 but for sample, it speeds up the target many times.

**Comment by faran-tenovos** [comment]
Fixed in version 7.1.10-20
