### ISSUE TITLE
Case of percentage Escape ( %x ) being performed after a number

### ISSUE THREAD

**Issue by 00SS** [ImageMagick/ImageMagick#3993]
### ImageMagick version

7.1.0.2 Q16 x64 2021-06-25

### Operating system

Windows

### Operating system, version and so on

10 Build 19042.985

### Description

The [Percentage Escape](https://imagemagick.org/script/escape.php) help page says:

> **WARNING**: short form percent escapes are NOT performed when the percent is after a number. For example, 10%x10 does not expand the %x as a percent escape. If you specifically want to expand the 'x', use the long form which overrides this special case. EG: 10%[x]10. 

This seems to trigger for %x in the case shown below.

### Steps to Reproduce

Does not work as expected -
This: `magick wizard: -gravity NorthEast -crop "50%x50%+0+0" wizard-Gravity=NE-50%x50%+0+0.png`
Creates a file: `wizard-Gravity=NE-50050%+0+0.png`
Expected file: `wizard-Gravity=NE-50%x50%+0+0.png`

Other oddities:
This:  `magick wizard: -gravity NorthEast -crop 50%x50%+0+0 "wizard-G=NE-50%x 50%x+0+0.png"`
Creates file: `wizard-G=NE-5000+0+0.png`

This: `magick wizard: -gravity NorthEast -crop 50%x50%+0+0 "wizard-G=NE-50%x 50%x +0+0.png"`
File created: `wizard-G=NE-500 0 +0+0.png`

**Comment by snibgo** [comment]
In places where "50%" means something, such as in "-crop", "50%x50%" will translate to 123x456 or whatever. But "50%" doesn't mean anything in a filename, so in "wizard-Gravity=NE-50%x50%+0+0.png" IM will try to translate "%x".

To prevent this, use "-define filename:literal=true". See https://imagemagick.org/script/defines.php

```
magick wizard: -gravity NorthEast -crop "50%x50%+0+0" -define filename:literal=true wizard-Gravity=NE-50%x50%+0+0.png
```

**Comment by 00SS** [comment]
Thanks, `-define filename:literal=true` works perfectly!

I guess then that: `magick wizard: -gravity NorthEast -crop 50%x50%+0+0 wizard-G=NE-50%y50%x+0+0.png`
should not give the filename: `wizard-G=NE-50%y50%+0+0.png`
but it does.

**Comment by snibgo** [comment]
Well, using percentage escapes in filenames has never worked well. I think the problem is that when the filename is prepared, the context required for %x, %y etc is missing. If you really want that, I suggest using the filename-type variable. Set the value of a variable, then use it in the filename, like this:
```
magick rose: -set filename:MYNAME abc%xand%y %[filename:MYNAME].png
```
The output filename is "abc72and72.png".

Use whatever name you want for "MYNAME", and any case. You can do this with no name at all, but I think that is bad practice.
