### ISSUE TITLE
IM 7 Channel Maps/Masks

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#4]
Hi,

I was reading the [documentation](http://www.imagemagick.org/script/porting.php) for porting software to IM7 and am a little confused by the functions `PopPixelChannelMap()`, `SetPixelChannelMap()` and `SetPixelChannelMask()`

My confusion comes from:
* only [SetPixelChannelMask](https://github.com/ImageMagick/ImageMagick/blob/7fb75bc9e9b70c59b4bc2d4ffddf636a1583cac8/MagickCore/pixel.c#L6254) seems to exist.

* It doesn't return a value, so there doesn't seem to be a way of restoring an images channel mask to the original values after setting it.

* The functions don't seem to be exposed through the 'Magick' external api i.e. they take an image as the parameter rather than a MagickWand. 

Can you clarify how to use that bit of functionality please?

**Comment by urban-warrior** [comment]
Updated the documentation to reflect the proper method for channel masks.  Use SetImageChannelMask().  We added MagickSetImageChannelMask() to expose channel masks to the MagickWand API.
