### ISSUE TITLE
How should I deal with SIGBUS

### ISSUE THREAD

**Issue by samt42** [ImageMagick/ImageMagick#400]
I notice this code: 

> #if defined(SIGBUS)
>static void CacheSignalHandler(int status)
>{
>ThrowFatalException(CacheFatalError,"UnableToExtendPixelCache");
>}
> #endif

ImageMagick use function **CacheSignalHandler** to handle SIGBUG signal, and function **ThrowFatalException** will call _exit() to make process exit.
That‘s not what I want ...I used ImageMagick in golang, as we all know golang application is one process model, it will cause server process exit immediately.
If I annotate this line of code:

> #if defined(SIGBUS)
>static void CacheSignalHandler(int status)
>{
>//ThrowFatalException(CacheFatalError,"UnableToExtendPixelCache");
>}
> #endif

server process not exit.

But is it the right way to solve this problem? will it cause other problem?

**Comment by mikayla-grace** [comment]
SIGBUS is thrown when the pixel cache is memory mapped and the partition where the mapping resides exceeds the free space.  Possible fixes is to move the pixel cache temporary partition to another device with plenty of free space, see https://www.imagemagick.org/script/architecture.php#tera-pixel.  Or you can expand the /tmp partition.  Or you can not use memory mapping.   Set the map resource to 0 from the command-line, environment variable, or security policy.  See https://www.imagemagick.org/script/security-policy.php and https://www.imagemagick.org/script/resources.php.

**Comment by samt42** [comment]
BTW，I didn't actually know the policy config `disk` mean, is it restrict the max use of space to store pixel cache on disk? I tried to set policy config `disk` to 2GB  and I have 20GB in temporary-path,  but It also use all space in temporary-path.

**Comment by mikayla-grace** [comment]
Correct, a map policy with a value of 0 prevents memory mapping of the pixel cache, instead its allocated on disk and if the partition fills, a recoverable exception is thrown.

A disk policy of 2GB prevents the pixel cache from exceeding 2GB.  If it is exceeded, an exception is thrown and ImageMagick exits.  Add ```-debug cache -debug resource``` to your command-line to track the pixel cache and resource consumption.

**Comment by samt42** [comment]
I have set policy like this `<policy domain="resource" name="map" value="0"/>`
but also receieved SIGBUS, I searched that SIGBUS is not just caused by mmap...how could I absolutelly avoid this problem.

**Comment by mikayla-grace** [comment]
Correct, but its the only way that ImageMagick will throw a SIGBUS-- unless there is another way we are not aware of.  We would need to reproduce the SIGBUS before we can offer further advice.  Do you have a way for us to get ImageMagick to throw a SIGBUS?  If so, we'll investigate a solution.

**Comment by dlemstra** [comment]
@samt42 Can we close this issue?

**Comment by samt42** [comment]
Sorry for the delay of reply, please close the issue.
