### ISSUE TITLE
cHRM-to-profile is not implemented

### ISSUE THREAD

**Issue by brechtm** [ImageMagick/ImageMagick#401]
The [PNG Browser Color-Correction Test Page][1] offers some PNG images that swap color channels using an embedded ICC color profile or a `cHRM` chunk. This image is a copy of `ArcTriomphe-cHRM-red-blue-swap.png`:

![ArcTriomphe-cHRM-red-blue-swap.png][2]

Basic conversion of the images with swapped channels using ImageMagick (or GraphicsMagick),

    convert ArcTriomphe-cHRM-red-blue-swap.png ArcTriomphe-cHRM-red-blue-swap.ppm

results in a blue version of the original, which is not what we want.

For the PNG images with an embedded ICC profile, it is possible to obtain a correctly colored output image by applying an sRGB color profile:

    convert ArcTriomphe-iCCP-red-blue-swap.png -profile sRGB_IEC61966-2-1_black_scaled.icc ArcTriomphe-iCCP-red-blue-swap.ppm

However, this doesn't work for the PNG images with the `cHRM` chunk.

See also this [StackOverflow question](http://stackoverflow.com/questions/42536309/convert-a-png-image-with-a-chrm-chunk-using-imagemagick-graphicsmagick).

  [1]: http://www.libpng.org/pub/png/png-colortest.html
  [2]: https://i.stack.imgur.com/dV4DS.png

**Comment by urban-warrior** [comment]
ImageMagick 7 include a convenient option to perform channel swap.  Try this command:

`convert ArcTriomphe-cHRM-red-blue-swap.png -channel-fx 'red<=>blue' ArcTriomphe-cHRM-red-blue-swap.ppm`

**Comment by brechtm** [comment]
This doesn't solve the original issue though. The channel swap is just one of the possible effects.

**Comment by brechtm** [comment]
Input from Glenn Randers-Pehrson on StackOverflow question: _cHRM-to-profile isn't implemented. It could be, using the approach taken by mozilla, in image/decoders/nsPNGDecoder.cpp (I think the code originally comes from littlecms)._
