### ISSUE TITLE
PDF to JPG - not working with print only layer - '-dPrinted' option of GS

### ISSUE THREAD

**Issue by hardikradixweb** [ImageMagick/ImageMagick#4019]
### ImageMagick version

7.0.10.23 & latest as well

### Operating system

Linux

### Operating system, version and so on

Linux 4.15.0-151-generic #157-Ubuntu - x86_64 x86_64 x86_64 GNU/Linux

### Description

converting PDF to JPG is not working when PDF has print only layer in it. It is not working with latest GS version. It was working fine with old version of GS(e.g v9.20). 

Please refer #4002  for more details. I have attached used PDF and expected output there.

### Steps to Reproduce

down load [Sample PDF](https://github.com/ImageMagick/ImageMagick/files/6907340/sample.pdf) and covert PDF to JPG using following command.

`convert sample.pdf sample.jpg`

Converted jpg file should display both images but it is displaying only one image.
GS make `-dPrinted` parameter compulsory after v9.26 I guess.

**Comment by dlemstra** [comment]
I cannot find any good documentation on why or when this was changed. But it does make sense to use `-dPrinted=false` when we want to view a pdf file. This argument will be added in the next release.

**Comment by hardikradixweb** [comment]
> I cannot find any good documentation on why or when this was changed. But it does make sense to use `-dPrinted=false` when we want to view a pdf file. This argument will be added in the next release.

Yes, you are right even I didn't found good documentation but I found one commit with details of one of the bug which is [here](http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=9e621d6ffb0e29c5de8331bf2c95003c8cf85941).
