### ISSUE TITLE
median filter is very slow (175 times slower than OpenCV for 3357 × 3000 image)

### ISSUE THREAD

**Issue by magicgoose** [ImageMagick/ImageMagick#402]
Processing 3357 × 3000 image with command like 
`time convert input.jpg -median 31 result.tga` takes 5.5 **minutes**
```
real	5m29.412s
user	5m26.687s
sys	0m1.475s
```
OpenCV produces identical result in less than 2 seconds:
```
import cv2

src = cv2.imread('input.jpg')
cv2.imwrite('result.bmp', cv2.medianBlur(src, 31))
```
```
$ time python3 "(above script)"

real	0m1.878s
user	0m1.689s
sys	0m0.161s
```

Version/configuration info:
```
$ convert --version
Version: ImageMagick 7.0.5-2 Q16 x86_64 2017-03-13 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher HDRI Modules OpenCL
Delegates (built-in): bzlib cairo fftw fontconfig freetype jng jpeg lcms ltdl lzma png rsvg tiff webp xml zlib
```

Is it possible to grab the implementation of median filter from OpenCV? Or port it somehow.
The algorithm behind it is free from any patents and other legal problems, AFAIK.

**Comment by saurabheights** [comment]
Not an official developer from IM. I noticed that Imagemagick is using Q16 version, you should try limiting depth to 8. Next, check your security policy, `convert -list resource` to see if there is any limitation placed on system resource usage.

**Comment by magicgoose** [comment]
@saurabheights imagemagick is using 100% CPU while doing this.
re. depth: as user I'd like to be able to do some operations with high precision, and using 2 builds is not practical. but for the sake of experiment, maybe I'll try rebuilding it with Q8 and testing again

**Comment by saurabheights** [comment]
@magicgoose : You do not have to rebuild, there is an option `-depth 8`. See http://www.imagemagick.org/Usage/basics/#cmdline

**Comment by magicgoose** [comment]
@saurabheights added "-depth 8" before "-median 31".
It's still working, a minute has passed already, so I guess it doesn't fix the problem

**Comment by mikayla-grace** [comment]
We tried your command and it completed in 20 seconds.    The -median option uses skip lists to return the median of a neighborhood.  If you have an improved algorithm, post a URL to the algorithm here and we will consider implementing it.  We don't want to re-implement what OpenCV is doing, if they do median filtering fast, we recommend you use OpenCV instead of IM for median filtering.

**Comment by magicgoose** [comment]
>We tried your command and it completed in 20 seconds

On which image and which computer? Is it a "hdri" build of IM?

>We don't want to re-implement what OpenCV is doing

Isn't it written in C just like IM, and under free & permissive license? If so, it doesn't need to be *re-implemented*, most of the code can be taken as is, right?

**Comment by mikayla-grace** [comment]
We created a 3357 × 3000 jpeg image with IM 7.0.5 Q16 HDRI build.

We don't take code from other projects, instead we recommend you just use that project.  However, we sometimes will implement an algorithm if its described in a published paper or someone posts pseudo-code we can implement.

**Comment by magicgoose** [comment]
> We don't take code from other projects, instead we recommend you just use that project

using "that project" is not the best solution, because then one has to roll their own color management (OpenCV can't do sRGB<->linear RGB conversion) and probably lots of other things too which IM can do, for doing any nontrivial processing,
or passing intermediate data back and forth to OpenCV (this is going to be inefficient)

and why you don't take code from other projects? is there a sound reason behind it? (besides NIH™)

speaking of "papers", yes, here's one that is good: https://nomis80.org/ctmf.pdf

**Comment by fmw42** [comment]
I believe they use two different licenses. IM is GPL V3 and OpenCV is BSD License

**Comment by dlemstra** [comment]
IM is apache 2.0 Fred.

**Comment by fmw42** [comment]
From https://www.imagemagick.org/script/license.php, it says
"the license is compatible with the GPL V3."

**Comment by dlemstra** [comment]
Being compatible with that license doesn't make it GPL. The license really is Apache 2.0. You cannot use GPL software in a commercial product without open sourcing your product. You can do that with IM.

**Comment by fmw42** [comment]
Yes, that was my main point about the licenses being different.

**Comment by magicgoose** [comment]
How is that a GPL? https://github.com/ImageMagick/ImageMagick/blob/master/LICENSE
