### ISSUE TITLE
libjxl 0.5.0 force disabled when compiling statically despite working pkg-config files

### ISSUE THREAD

**Issue by landfillbaby** [ImageMagick/ImageMagick#4029]
### ImageMagick version

7.1.0-4

### Operating system

Linux

### Operating system, version and so on

Ubuntu 21.04 x64, Termux aarch64

### Description

libjxl v0.5.0, released yesterday, includes working pkg-config files, but magick's configure[.ac] still forces it off

### Steps to Reproduce

install libjxl 0.5.0
in imagemagick source,
```
configure --with-jxl=yes
```

**Comment by dlemstra** [comment]
Thanks for reporting this, we will need to investigate and run some tests with this.

**Comment by dlemstra** [comment]
It looks like it is still not working. Feel free to submit a PR that would make this work with a static build.

**Comment by landfillbaby** [comment]
libjxl/libjxl#452 ? maybe

**Comment by landfillbaby** [comment]
wait no. i know the problem

**Comment by landfillbaby** [comment]
this is the problem! google/brotli@09b0992

**Comment by dlemstra** [comment]
I asked if we can get a new brotli release. And I had to close that PR because we don't need those patches for the Windows build.

**Comment by landfillbaby** [comment]
once that next brotli release is out, the next problem with libjxl is #3887

**Comment by dlemstra** [comment]
I suspect that I already fixed this issue (see my remark in that linked issue).

**Comment by dlemstra** [comment]
Would you be willing to open an issue here: github.com/google/brotli to request the new release? They asked me to do that but I suspect you can explain better why this fixes the static linking. I am not a pkgconfig expert 😁

**Comment by landfillbaby** [comment]
oh i forgot to mention, i opened google/brotli#917

**Comment by landfillbaby** [comment]
i noticed you allow this with 7.1.0-10 so i'll close it
