### ISSUE TITLE
Implement Guetzli lossy compression for JPEG?

### ISSUE THREAD

**Issue by rlue** [ImageMagick/ImageMagick#403]
Google just open-sourced a new JPEG encoding algorithm (Guetzli) that promises a 35% reduction in file size compared to libjpg, albeit with “significantly longer” execution times.

* https://opensource.googleblog.com/2017/03/guetzli-new-open-source-jpeg-encoder.html
* https://github.com/google/guetzli/

A technical explanation:

> The visual quality of JPEG images is directly correlated to its multi-stage compression process: color space transform, discrete cosine transform, and quantization. Guetzli specifically targets the quantization stage in which the more visual quality loss is introduced, the smaller the resulting file. Guetzli strikes a balance between minimal loss and file size by employing a search algorithm that tries to overcome the difference between the psychovisual modeling of JPEG's format, and Guetzli’s psychovisual model, which approximates color perception and visual masking in a more thorough and detailed way than what is achievable by simpler color transforms and the discrete cosine transform. 

followed by the caveat:

> However, while Guetzli creates smaller image file sizes, the tradeoff is that these search algorithms take significantly longer to create compressed images than currently available methods.

Any chance this might get incorporated into ImageMagick?

**Comment by mikayla-grace** [comment]
The library will not compile on either of our development platforms, CentOS 7 and Fedora 25.

**Comment by rlue** [comment]
Hm. Flash in the pan, I suppose.

I came across a comment on reddit saying that [a 16MP image took ~20 minutes to compress on an i3](https://www.reddit.com/r/programming/comments/601zmg/google_reduces_jpeg_file_size_by_35_new_algorithm/df33qip/), so perhaps it's for the best? I imagine there are use cases where the reduction in filesize might be worth it, but I'm going to assume from the lack of feedback from other users that it wouldn't be sorely missed.
