### ISSUE TITLE
Division by zero in XMenuWidget() of MagickCore/widget.c

### ISSUE THREAD

**Issue by xiaoxiaoafeifei** [ImageMagick/ImageMagick#4040]
### ImageMagick version

7.1.0

### Operating system

All system

### Operating system, version and so on

the latest version

### Description

A division-by-zero exception can happen in function XMenuWidget() of MagickCore/widget.c at line 7876, 7929,  8015.  Below is the code that the division-by-zero exception can happen.
![1](https://user-images.githubusercontent.com/20721416/128337428-4da5ccef-16d2-4ed7-a5c3-5b62d5abd9e3.png)
![2](https://user-images.githubusercontent.com/20721416/128337197-07671d7b-fcc8-4cc0-bedb-b4cbef7a4389.png)
![3](https://user-images.githubusercontent.com/20721416/128337249-ca607a49-f054-46ad-971a-bcdfcd323480.png)

details:
windows->widget.font_info->ascent and windows->widget.font_info->descent are controller by the user since function, and there is no check between the beginning of the function to the line 7876, 7929,  8015. 
When windows->widget.font_info->ascent = 0 and windows->widget.font_info->descent = 0, height = 0, then height is assigned to selection_info.height.  
It will lead to a division-by-zero exception
![4](https://user-images.githubusercontent.com/20721416/128337864-b302c6ed-4427-4913-a029-59b162425194.png)
![5](https://user-images.githubusercontent.com/20721416/128338120-f6d1c07d-8cfc-49a8-9776-8c8db74eb667.png)

Thank you in advance! Let me know if you have any questions.

### Steps to Reproduce

As is mentioned in the description.

**Comment by dlemstra** [comment]
Thanks for the fix!
