### ISSUE TITLE
When using -format with -define preserve-timestamp=true in mogrify, it does not keep the original timestamp

### ISSUE THREAD

**Issue by Shidouuu** [ImageMagick/ImageMagick#4058]
### ImageMagick version

7.1.0.4

### Operating system

Windows

### Operating system, version and so on

Windows 10 Home 21H1

### Description

Just a guess but maybe because `preserve-timestamp=true` only works if the original file is being modified, which is what mogrify usually does without `-format`.

Example command:
` magick mogrify -define preserve-timestamp=true -format png img.jpg`

### Steps to Reproduce

1. Convert image using above command
2. Observe timestamp in file explorer
3. ???
4. Profit.

### Images

![image](https://user-images.githubusercontent.com/36283656/128647208-4b89789c-1384-453d-8534-4fbc42f5e7d3.png)

**Comment by dlemstra** [comment]
Normaly with `preserve-timestamp` the file creation time will not be preserved. This is not done because we use the `utime` method. Under Windows it is possible to copy the attributes differently. I just pushed a patch that will also copy the file creation time on Windows..

**Comment by Shidouuu** [comment]
I'm guessing this issue can be closed now? :)
![image](https://user-images.githubusercontent.com/36283656/131234861-87638068-b1db-4af1-b2bc-e813c8a56970.png)
