### ISSUE TITLE
Issue in converting  a specific JPG file a B/W 200 DPI output TIFF file using ImageMagick library APIs.

### ISSUE THREAD

**Issue by pprasanthk** [ImageMagick/ImageMagick#4059]
### ImageMagick version

7.1.0-Q8

### Operating system

Windows

### Operating system, version and so on

Any version of Windows OS.

### Description

Hi, 

We have an issue with using the latest version of ImageMagick to convert a specific JPG file to a Black and White 200 DPI TIIF file. We are getting a white TIFF file as output. We are using ImageMagick library APIs for this conversion.

Input JPG file (input.zip), output TIFF file (output.zip) and the sample code to reproduce this issue (ImageMagick_Sample.zip) are attached here with. 

Could you please help us with this or let us know if we are missing anything here? 

--
Thanks
Prasanth

### Steps to Reproduce

[ImageMagick_Sample.zip](https://github.com/ImageMagick/ImageMagick/files/6951727/ImageMagick_Sample.zip)

### Images

[input.zip](https://github.com/ImageMagick/ImageMagick/files/6951739/input.zip)
[output.zip](https://github.com/ImageMagick/ImageMagick/files/6951740/output.zip)

**Comment by fmw42** [comment]
Works fine on IM 7.1.0.4 Q16 Mac OSX Sierra.

`magick Input.jpg Input.tif`

**Comment by pprasanthk** [comment]
Hi, 

Issue is happening with ImageMagick-7.1.0.4-Q8 (32-bit) with output as a Black and White 200 DPI TIFF file. Also, instead of using from command line, I tried this conversion using ImageMagick APIs (in "CORE_RL_Magick++_.lib") on Windows 10 machine.

Could you please check this and do the needful?

--
Thanks
Prasanth

**Comment by snibgo** [comment]
I suggest you do a 50% threshold before setting the compression and type.

**Comment by fmw42** [comment]
This works well for me on IM 7.1.0.4 Q16 Mac OSX Sierra

`magick input.jpg -threshold 50% -compress FAX -density 200 input.tif`

**Comment by pprasanthk** [comment]
Hi, 

Thanks for your input. I tried it with 50 percent and I could see the conversion is working fine. However, there is some blurred porting in the output image. Then, I tried with 100 percent threshold and the output looks more neat. Please find both outputs with 50 and 100 percent thresholds. 

Could you please let if it is mandatory this threshold for every image? For us, this is happening for this particular input jpg image. Is it a change in the architecture of ImageMagick?

[OutputTiffsWithDifferentThresholds.zip](https://github.com/ImageMagick/ImageMagick/files/6951980/OutputTiffsWithDifferentThresholds.zip)

**Comment by fmw42** [comment]
I doubt it is change in ImageMagick. It is likely just how dark or light your image is and how the binarization to black & white works. You are free to use any threshold you want for any given image.

Did you find that it worked better in a previous version? If so, what version and I will check that version.

**Comment by pprasanthk** [comment]
Hi, 

Thanks for your response. 

On ImageMagick 7.0.10.0, it was working fine without setting any threshold. It stopped working from version ImageMagick  version 7.0.11 for this particular input JPG file. Other image files to TIFF conversions are working fine. 

Our only concern is we are not setting any threshold when we are converting any image to TIF till now. Now, starting from ImageMagick version 7.0.11, this looks to be required only for this particular JPG file. We look to see how much percentage of threshold is required for different types of images conversion to TIFF and how will that affect the conversion quality for the existing images conversion that we are doing (without setting a threshold).

Could you please check this and confirm?

--
Thanks
Prasanth

**Comment by snibgo** [comment]
A change has occurred in Group4 compression when writing TIFF files. I don't know if the change is in IM code or libtiff code.

Group4 compression reduces the image to black and white only. If you care about how that is done, it is best to do that explicitly before saving the file, eg with threshold or colors or posterize, and with or without dithering.

**Comment by fmw42** [comment]
I can confirm that this command

`magick input.jpg -compress fax -density 200 x.tif`

works fine in IM 7.0.10.10 but gives a completely white image for IM 7.0.11.10

**Comment by pprasanthk** [comment]
Hi, 

Thanks for confirming this. 

I could see the same behavior in the latest version, IM 7.1.0-4 as well. 

Could someone please help me to identify what change resulted in this behavior starting from IM 7.0.11.10?

--
Thanks
Prasanth

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pprasanthk** [comment]
Thank you.

**Comment by pprasanthk** [comment]
Hi, 

Could you please let us know when are planning to include this fix in your official release?

--
Thanks
Prasanth

**Comment by dlemstra** [comment]
That will happen when we do the next release. We don't have a release schedule so we cannot tell you when that happens. It might happen this weekend, but it also might happen another time.

**Comment by pprasanthk** [comment]
Okay fine. Thanks for the update.

**Comment by pprasanthk** [comment]
Hi , 

We have tested with the latest 7.1.0-6 and noticed that the output is a blank output page again. Could you please check this?

[input.zip](https://github.com/ImageMagick/ImageMagick/files/7114572/input.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
Can you test this again @pprasanthk?

**Comment by pprasanthk** [comment]
Hi dlemstra, 

I tested this with 7.1.0-6 and it is working fine. But, it broke the other issue (https://github.com/ImageMagick/ImageMagick/issues/4121)

--
Thanks
Prasanth
