### ISSUE TITLE
PHP imagesMagick not work with Unicode characters

### ISSUE THREAD

**Issue by hengsoheak** [ImageMagick/ImageMagick#406]
I'm trying to use PHP ImageMagick to write any Unicode text into images as the original source for PHP.net But those character is not correct 
Please check the question below

http://stackoverflow.com/questions/42876517/php-imagesmagick-not-work-with-unicode-characters

**Comment by hengsoheak** [comment]
👍

**Comment by Danack** [comment]
Please open PHP Imagick issues at https://github.com/mkoppanen/imagick with a simple code example, rather than a link to a different site.
