### ISSUE TITLE
Blurrier resizing on PNG32 images

### ISSUE THREAD

**Issue by d4rkne55** [ImageMagick/ImageMagick#4085]
### ImageMagick version

7.1.0-4

### Operating system

Windows

### Operating system, version and so on

Windows 10 Pro 64bit, Version 21H1

### Description

When resizing PNG images with an alpha channel (32bit), the result is blurrier than resizing ones without (24bit PNG, JPEG).

PNG32 source:
![sam-the-womp-bom-bom_500x1](https://user-images.githubusercontent.com/14071933/129770595-ac35b244-eba1-491a-a138-0ad4fd0331bd.png)
PNG24 source, by removing the alpha channel before resizing:
![sam-the-womp-bom-bom_500x2](https://user-images.githubusercontent.com/14071933/129770604-46a61245-95c2-4090-8513-65a5a966b552.png)

One could say now that the former looks cleaner, but it's less close to the source and on complex images like photographs this is more obvious. As I'm mostly working with album covers I took this one though, as it's a recreation by me and doesn't have potential copyright issues.^^

I don't think there should be a difference and the RGB channels at least should be resized the same way. If it's not a bug, what is the reason for this behaviour? I checked existing issues and could not find the problem I describe here, so I'm curious.

This already happened with previous versions btw (definitely 7.0.8, I think also v6.9), I just updated to the newest before reporting.

### Steps to Reproduce

Either

1) Use the ImageMagick GUI for resizing
2) Use the following simple command on the CLI: `magick input.png -resize 500x output.png`

I recently discovered through [this](https://legacy.imagemagick.org/discourse-server/viewtopic.php?f=3&t=36086) (unrelated) bug report that there is a (maybe) more convenient way of working around this instead of opening the source image in an image editing software, removing the alpha channel manually and resaving to a new temporary file before resizing, by using the CLI with following command: `magick input.png -alpha off -resize 500x output.png`
This works and would be more convenient/streamlined if I'd use the CLI anyways, but I'm usually not, primarily because drag-and-drop is easier than typing paths for every individual operation.

### Images

[sam-the-womp-bom-bom.png](https://user-images.githubusercontent.com/14071933/129773479-b9480b83-b993-45e4-8d80-e091416b2465.png)

**Comment by fmw42** [comment]
Using ImageMagick 7.1.0.4 Q16 Mac OSX Sierra command line, I see no difference with or without the alpha channel. Your alpha channel is perfectly opaque.

```
magick 129770595-ac35b244-eba1-491a-a138-0ad4fd0331bd.png -resize 500x y1.png
and
magick 129770595-ac35b244-eba1-491a-a138-0ad4fd0331bd.png -alpha off -resize 500x y2.png
```

**Comment by snibgo** [comment]
With IM v7.1.0-4 on Windows 8.1, using the third linked file, I confirm the problem.
```
magick 129773479-b9480b83-b993-45e4-8d80-e091416b2465.png -resize 500x a.png

magick 129773479-b9480b83-b993-45e4-8d80-e091416b2465.png -alpha off -resize 500x b.png

magick compare -metric RMSE a.png b.png NULL:
512.381 (0.00781843)
```
The input file 129773479-b9480b83-b993-45e4-8d80-e091416b2465.png has an alpha channel that IM says is entirely opaque. So resizing with alpha on or off should make no difference. But there is a difference.

This seems to be a bug.

**Comment by d4rkne55** [comment]
Should add that I'm more precisely using the Q8 x64 build, maybe Q16 fixes that issue? Which build are you using, @snibgo?

**Comment by fmw42** [comment]
On Mac OSX Sierra, IM 7.1.0.4 Q16, I get zero difference:


```
magick 129770595-ac35b244-eba1-491a-aad4fd0331bd.png -resize 500x a.png

magick 129770595-ac35b244-eba1-491a-a138-0ad4fd0331bd.png -alpha off -resize 500x b.png

magick compare -metric RMSE a.png b.png NULL:
0 (0)
```

**Comment by snibgo** [comment]
I tested on Q16:
```
Version: ImageMagick 7.1.0-4 Q16 x64 2021-07-18 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Visual C++: 192930038
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms
 lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
```
The input image is only 8 bits per channel per pixel. fmw42 is correct, that this will result in 8-bit/c/p PNG outputs, so rounding errors may be evident. But using "+depth" before the output still gives an RMSE of:
```
510.701 (0.0077928)
```

If we save the two files as "-define quantum:format=floating-point -depth 32" in miff format, the RMSE is slightly worse, at:
```
566.862 (0.00864976)
```
The difference, at nearly 1% RMSE, is more than a trivial rounding error, in my opinion.

**Comment by fmw42** [comment]
Sorry, I was thinking 51 vs 510. I used to get on the order up to 50 from various differences between IM 6 and 7 that I could not account for. But snibgo is right 1% is too much.

**Comment by dlemstra** [comment]
This is happening because a different `-filter` is used when the image has an alpha channel. With an alpha channel `Mitchell` is used and for images without an alpha channel `Lanczos` will be used instead. When adding the filter the difference is minor or zero:

```console
d@l:~$ magick input.png -filter mitchell -resize 500x a.png
d@l:~$ magick input.png -alpha off -filter mitchell -resize 500x b.png
d@l:~$ compare -metric RMSE a.png b.png NULL:
0.363453 (5.54594e-06)

d@l:~$ magick input.png -filter lanczos -resize 500x a.png
d@l:~$ magick input.png -alpha off -filter lanczos -resize 500x b.png
d@l:~$ compare -metric RMSE a.png b.png NULL:
0 (0)

```
