### ISSUE TITLE
error  building ImageMagick-7.1.0-5  error while loading shared libraries: libIlmImf-2_2.so.23

### ISSUE THREAD

**Issue by pleabargain** [ImageMagick/ImageMagick#4086]
### ImageMagick version

7.1.0-4

### Operating system

Linux

### Operating system, version and so on

ubuntu 21.04

### Description

after $make

/usr/bin/sed: can't read test/ImageMagick-7.1.0-4/MagickCore/libMagickCore-7.Q16HDRI.la: No such file or directory
libtool:   error: 'test/ImageMagick-7.1.0-4/MagickCore/libMagickCore-7.Q16HDRI.la' is not a valid libtool archive
make[1]: *** [Makefile:7162: MagickWand/libMagickWand-7.Q16HDRI.la] Error 1
make[1]: Leaving directory '/home/dgd/Pictures/bash sort test/ImageMagick-7.1.0-4'
make: *** [Makefile:6120: all] Error 2

I plowed ahead and tried make install (hoping)
make  install-am
make[1]: Entering directory '/home/dgd/Pictures/bash sort test/ImageMagick-7.1.0-4'
  CCLD     utilities/magick
libtool:   error: cannot find the library 'test/ImageMagick-7.1.0-4/MagickCore/libMagickCore-7.Q16HDRI.la' or unhandled argument 'test/ImageMagick-7.1.0-4/MagickCore/libMagickCore-7.Q16HDRI.la'
make[1]: *** [Makefile:8044: utilities/magick] Error 1
make[1]: Leaving directory '/home/dgd/Pictures/bash sort test/ImageMagick-7.1.0-4'
make: *** [Makefile:12536: install] Error 2

### Steps to Reproduce

I was following these instructions:
https://scottiestech.info/2020/05/26/how-to-install-imagemagick-7-on-ubuntu/

here's the command history:
 754  sudo apt remove imagemagick imagemagick-6-common
  755  sudo apt autoremove
  756  apt build-dep imagemagick
  757  sudo apt build-dep imagemagick
  758  sudo apt-get install checkinstall libwebp-dev libopenjp2-7-dev librsvg2-dev libde265-dev
  759  wget https://www.imagemagick.org/download/ImageMagick.tar.gz
  760  tar xzvf ImageMagick.tar.gz
  761  ls
  762  cd ImageMagick-7.1.0-4/
  763  ./configure --enable-shared --with-modules --with-gslib
  764  make
  765  make install

### Images

![2021-08-18_10-39](https://user-images.githubusercontent.com/640846/129857871-a57ca2f5-bfd5-4f96-a7b9-ac139f55676e.png)

**Comment by snibgo** [comment]
I suggest you try "automake" and "autoconf" before "./configure".

**Comment by dlemstra** [comment]
Did that resolve your issue @pleabargain and can we close this issue?

**Comment by pleabargain** [comment]
I tried 
```automake```

and got this error

```dgd@ubuntu21-04:~/Downloads/ImageMagick-7.1.0-5$ automake
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
configure.ac:60: error: version mismatch.  This is Automake 1.16.3,
configure.ac:60: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:60: comes from Automake 1.16.1.  You should recreate
configure.ac:60: aclocal.m4 with aclocal and run automake again.
```

Still no joy in getting a working v of imagemagick.

here's the history

```
1147  sudo apt remove imagemagick imagemagick-6-common
 1148  sudo apt autoremove
 1149  apt build-dep imagemagick
 1150  sudo apt build-dep imagemagick
 1151  sudo apt-get install checkinstall libwebp-dev libopenjp2-7-dev librsvg2-dev libde265-dev
 1152  wget https://www.imagemagick.org/download/ImageMagick.tar.gz
 1153  tar xzvf ImageMagick.tar.gz
 1154  cd ImageMagick-7.1.0-5/
 1155  automake
```

**Comment by dlemstra** [comment]
Another option would be to use `autoreconf -fiv` before you do `./configure`.

**Comment by pleabargain** [comment]
Got a bunch errors:

```
~/Downloads/ImageMagick-7.1.0-5$ autoreconf -fiv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
autoreconf: configure.ac: tracing
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: copying file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
autoreconf: running: /usr/bin/autoconf --force
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
autoreconf: running: /usr/bin/autoheader --force
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:266: installing 'config/compile'
configure.ac:60: installing 'config/missing'
Makefile.am: installing 'config/depcomp'
autoreconf: Leaving directory `.'
```

then I ran with no errors
```autoconf
automake
```

then 


```
./config
```

finally I tested with 

```convert --version```

 and got a libIlmImf-2_2.so.23:  error


```
ImageMagick-7.1.0-5$ convert --version
convert: error while loading shared libraries: libIlmImf-2_2.so.23: cannot open shared object file: No such file or directory
```

I thought the necessary libs would be in

```
apt-get install checkinstall libwebp-dev libopenjp2-7-dev librsvg2-dev libde265-dev
```

I appreciate your advice and help.

**Comment by pleabargain** [comment]
I changed the bug header as the bug has changed.
