### ISSUE TITLE
Webp identified as VIDEO

### ISSUE THREAD

**Issue by williamjacobszoon** [ImageMagick/ImageMagick#4093]
### ImageMagick version

7.1.0-4

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04.2 LTS

### Description

Extracted AppImage downloaded from (https://download.imagemagick.org/ImageMagick/download/binaries/magick) identify webp as `VIDEO`

./AppRun identify -debug ALL -ping WEBP_500kB.webp

identify: no decode delegate for this image format `VIDEO' @ error/constitute.c/ReadImage/572.

- [WEBP_500kB.zip](https://github.com/ImageMagick/ImageMagick/files/7011454/WEBP_500kB.zip)
- [error.log](https://github.com/ImageMagick/ImageMagick/files/7011455/error.log)
- [version.log](https://github.com/ImageMagick/ImageMagick/files/7011508/version.log)
- [delegates.log](https://github.com/ImageMagick/ImageMagick/files/7011509/delegates.log)

### Steps to Reproduce

1. Download AppImage from => https://download.imagemagick.org/ImageMagick/download/binaries/magick
2. Extract AppImage => ./magick --appimage-extract
3. Rename squashfs-root folder to => magickdir
4. cd magickdir
5. ./AppRun identify -debug ALL -ping WEBP_500kB.webp

**Comment by snibgo** [comment]
Your webp file works fine for me.

Perhaps your version of IM has not been built with webp support. What does "magick -version" or "identify -version" say? For me, it says:
```
Version: ImageMagick 7.1.0-4 Q16 x64 2021-07-18 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Visual C++: 192930038
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms
 lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
```
Note that "webp" is a built-in delegate.

**Comment by williamjacobszoon** [comment]
@snibgo Yes, You are correct this works fine with the Windows build. However, same image is not working with the Linux build. If you could following the the steps to reproduce you should get the same error. Please have a look at the log files that I have attached for more information.

**Comment by snibgo** [comment]
Sorry, I overlooked your version.log. Yes, it shows your IM build can't read webp files with a built-in delegate. Your delegates.log shows that your build should use external delegate "dwebp" to read webp, and "cwebp" to write webp. Do you have these programs? If not, can you obtain them for your system? (For Windows, they are available from Cygwin, so I expect they are readily available.)

I know nothing about the AppImage build, sorry.

**Comment by williamjacobszoon** [comment]
@snibgo, I can confirm dwebp & cwebp is installed.
`userx@imagemagick:~$ which dwebp
/usr/bin/dwebp

userx@imagemagick:~$ which cwebp
/usr/bin/cwebp`

**Comment by snibgo** [comment]
Your error.log suggests that IM is correctly identifying your input as format WEBP, but then as VIDEO. I don't understand why.

Please show the text outputs from:
```
identify -list policy

identify -verbose WEBP_500kB.webp
```
The first will tell us if there is a problem in policy.xml. The second may tell us whether IM is trying to use an external delegate.

One possibility: You run IM with "./AppRun identify ..." Perhaps this doesn't pass the system path to IM, so it can't find "dwebp". Perhaps using the full path in delegates.xml will fix the problem.

**Comment by williamjacobszoon** [comment]
@snibgo 

```
userx@imagemagick:~/magickdir$ ./AppRun identify -list policy

Path: [built-in]
  Policy: Undefined
    rights: None
```

I've already attached the verbose output of the identify command. Please have a look at the error.log file

**Comment by williamjacobszoon** [comment]
After getting the latest build which includes Webp as a Built-in delegate, Webp image are getting identified correctly.

```
Version: ImageMagick 7.1.0-5 Q16 x86_64 2021-08-14 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in): bzlib djvu fontconfig freetype jbig jng jpeg lcms lqr lzma openexr png raqm tiff webp x xml zlib
```

The issue that I was facing is now fixed but not sure why the external webp delegate wasn't working???

**Comment by fmw42** [comment]
I asked the IM developer to look into it and apparently he added it.
