### ISSUE TITLE
Data truncation in commit 6b6fd6

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#41]
Apologies if this is duplication, I'm not sure if you get notifications for comments on code with your setup.

It looks like [commit 6b6fd6](https://github.com/ImageMagick/ImageMagick/commit/6b6fd646449e6f192dc5e0459c31b2ac9a907a4f?diff=unified) has an issue with data truncation.

I'm getting a large number of errors of:
> unable to read font `(null)' @ error/annotate.c/RenderFreetype/1152

For versions after this commit.

**Comment by urban-warrior** [comment]
We will revert part of this patch in a few hours.  Let us know if that fixes the problem.

**Comment by Danack** [comment]
Yep, looks good.
