### ISSUE TITLE
Identify returns quantum depth as bit depth for some TIFF images 

### ISSUE THREAD

**Issue by sbraz** [ImageMagick/ImageMagick#4109]
### ImageMagick version

7.1.0-5

### Operating system

Linux

### Operating system, version and so on

Gentoo unstable

### Description

Hi,
I noticed something really weird with some TIFF images, rebuilding IM with `--with-quantum-depth=32` changes the value of  `identify`'s `%[bit-depth]`.

### Steps to Reproduce

Run `identify -format "%[version] %[f] %[depth] %[bit-depth] %[q]\n" *.tiff`.

The first file seems to behave correctly:
```
ImageMagick 7.1.0-5 Q16 x86_64 2021-08-22 https://imagemagick.org tiff_palette4_img0_in.tiff 4 8 16
ImageMagick 7.1.0-5 Q32 x86_64 2021-08-22 https://imagemagick.org tiff_palette4_img0_in.tiff 4 8 32
```

The second file, however, sees its `bit-depth` change depending on the value of the quantum depth:
```
ImageMagick 7.1.0-5 Q16 x86_64 2021-08-22 https://imagemagick.org tiff_rgb80_in.tiff 12 16 16
ImageMagick 7.1.0-5 Q32 x86_64 2021-08-22 https://imagemagick.org tiff_rgb80_in.tiff 12 32 32
```

### Images

[tiff.zip](https://github.com/ImageMagick/ImageMagick/files/7035111/tiff.zip)

**Comment by fmw42** [comment]
It is reporting the file bit depth (first number - 8) and then the IM bit depth into which it is read that depends upon the quantum range that you used to compile IM (16 or 32). The file is an 8-bit file scaled to the range of 16 or 32 so that it looks normal on the higher bit depth system

**Comment by snibgo** [comment]
Format %[bit-depth] calls attribute.c GetImageDepth(). If I understand that correctly, this should report the actual number of bits required to record the pixel values. For integer IM, pixel values are stored as integers with Q-number bits, so %[bit-depth] should never be larger than the Q-number.

Further, if no image processing has occurred, %[bit-depth] should never be larger than the bits used to store the numbers in the file. Exiftool shows that tiff_rgb80_in.tiff has 12-bit values, so %[bit-depth] should not be larger than 12.

@sbraz: Is your build with HDRI? That might cause complications.

For comparison, with home-built Q32 HDRI 7.0.7-4:
```
%IM7DEV%magick identify -ping -format "%[version] %[f] %[depth] %[bit-depth] %[q]\n" tiff_rgb80_in.tiff 

ImageMagick 7.0.8-64 Q32 x86_64 2021-02-24 https://imagemagick.org tiff_rgb80_in.tiff 12 12 32
```

With pre-built Q16 HDRI 7.0.1-4:
```
%IMG7%magick identify -format "%[version] %[f] %[depth] %[bit-depth] %
[q]\n" tiff_rgb80_in.tiff

ImageMagick 7.1.0-4 Q16 x64 2021-07-18 https://imagemagick.org tiff_rgb80_in.tiff 12 12 16
```
In both these cases, %[bit-depth] is 12, which seems correct to me. Perhaps something has changed in 7.1.0-5.

**Comment by sbraz** [comment]
@snibgo no it was not built with HDRI:
```
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/imagemagick-7.1.0.5 --htmldir=/usr/share/doc/imagemagick-7.1.0.5/html --with-sysroot=/ --libdir=/usr/lib64 --disable-static --disable-hdri --disable-opencl --with-threads --with-modules --with-quantum-depth=32 --with-magick-plus-plus --without-perl --with-perl-options=INSTALLDIRS=vendor --with-gs-font-dir=/usr/share/fonts/urw-fonts --with-bzlib --with-x --without-zip --with-zlib --without-autotrace --without-dps --without-djvu --with-dejavu-font-dir=/usr/share/fonts/dejavu --with-fftw --without-fpx --without-fontconfig --with-freetype --without-gslib --without-gvc --without-heic --without-jbig --with-jpeg --with-openjp2 --without-jxl --with-lcms --without-lqr --without-lzma --without-openexr --with-pango --with-png --without-raw --with-rsvg --with-tiff --without-webp --without-windows-font-dir --without-wmf --with-xml --enable-openmp --with-gcc-arch=no-automagic
```

It is not really a recent behaviour change, I can see it with older IM versions too.

@fmw42  I'm sorry, I don't understand what you mean by "first number - 8"? I don't see two numbers whose difference is 8.  Does your comment apply to `tiff_palette4_img0_in.tiff` or `tiff_rgb80_in.tiff`?  Could you elaborate a little bit? Maybe this is not a bug but at the moment I don't understand what is happening.

**Comment by fmw42** [comment]
> ImageMagick 7.1.0-5 Q16 x86_64 2021-08-22 https://imagemagick.org tiff_palette4_img0_in.tiff 4 8 16
> ImageMagick 7.1.0-5 Q32 x86_64 2021-08-22 https://imagemagick.org tiff_palette4_img0_in.tiff 4 8 32
> 

There are numbers 8 16 or 8 32 in the identify result. The first is 8, the second is either 16 or 32.

**Comment by fmw42** [comment]
My mistake, the last was Q level. The previous 2 were depth and bit-depth. Not sure of the difference.

**Comment by dlemstra** [comment]
The `depth` is the depth that was loaded from the file. The `bit-depth` is the calculated bit depth of the image. And this looks at the pixels of the image. With my debug build I get the following output on Windows:

```
magick identify -ping -format "%[version] %[f] %[depth] %[bit-depth] %[q]\n" tiff_rgb80_in.tiff
ImageMagick 7.1.0-5 Q16x64 2021-08-21 https://imagemagick.org tiff_rgb80_in.tiff 12 1 16
```

This is `1` because all the pixels of the image are undefined and get the value zero. With your build this is probably a release build where the pixel values will be random and if you have a `Q32` build you will probably get values that make it 32 bit depth image. Don't think you should use `%[bit-depth]` here.

**Comment by dlemstra** [comment]
You are doing a `ping` of the image and that means that we will not read the pixels of the image. And when memory is allocated to get all the pixel data it will have random "junk" in it.

**Comment by sbraz** [comment]
I assume `-ping` is the default, then? Because I'm not passing that argument to `identify`.

**Comment by dlemstra** [comment]
The default value for identify is indeed ping.

**Comment by sbraz** [comment]
@dlemstra thanks for your feedback. Should we close this issue? Is there anything that can be improved in terms of documentation maybe?

**Comment by dlemstra** [comment]
I also think we can close this issue. The documentation of `identify` can be found here: https://github.com/ImageMagick/Website/blob/main/include/identify.php. Feel free to open up a pull request to improve our documentation.
