### ISSUE TITLE
-colorspace sRGB is ignored when converting from grayscale image

### ISSUE THREAD

**Issue by chconnor** [ImageMagick/ImageMagick#4118]
### ImageMagick version

6.9.11-60

### Operating system

Linux

### Operating system, version and so on

Kubuntu 21.04

### Description

If I take a grayscale PNG and convert like so:

convert -colorspace sRGB in.png out.png
...the resulting image is still in PNG grayscale mode, as indicated by the "identify" utility:
out.png PNG 4508x2809 4508x2809+0+0 8-bit Gray 256c 7125710B 0.000u 0:00.000

I'm getting the impression that this is a PNG library thing, maybe, because GIMP does the same thing: even if you "force" sRGB, it is ignored when writing the PNG. It's clear that this is an optimization in the file writing (since there is no obvious utility to writing a grayscale image as sRGB) but I need to do it to work around a [bug in Inkscape](https://gitlab.com/inkscape/inkscape/-/issues/1934) that does not export SVG grayscale images correctly when generating PDFs.

I can make a pixel have some tiny amount of chromaticity as a workaround, but that's annoying. :-)

So, I'm not sure if this is really an imagemagick thing or if I should report against a png library (libpng?)

Thanks for any attention to this!

### Steps to Reproduce

convert -colorspace sRGB grayscale_input.png sRGB_output_but_it_isnt_actually.png

**Comment by fmw42** [comment]
First, read the input, then use any commands. So -colorspace should come after reading your image. However, PNG is special. You tell it to convert to 24-bit color by prefacing the output with PNG24: as follows PNG24:output.png. So

`convert grayscale_input.png PNG24:color.png
`

**Comment by chconnor** [comment]
Works great; apologies for the noise, and thanks!
