### ISSUE TITLE
install-windows.txt out of date. No way to build windows libs?

### ISSUE THREAD

**Issue by cliffowen** [ImageMagick/ImageMagick#4120]
### ImageMagick version

7.1.0-5

### Operating system

Windows

### Operating system, version and so on

10.x

### Description

In the file install-windows.txt, it describes the process for building for Windows. It states:

Run CloneRepositories.cmd to clone these libraries... There is no CloneRepositories.cmd. Similarly, whatever 3rd party repositories are used are not listed anywhere obvious (or less obvious), and are not provided as submodules.

as a result, the VisualMagick folder is not available for building configure.exe, and without configure.exe there is no magick-baseconfig.h that is generated.

Expected behavior is: A build file that accurately describes how to build on each platform along with a repository sufficiently complete to build it.

### Steps to Reproduce

clone ImageMagick on a Windows machine and try to build any part of it from Visual Studio (no solution/project file) or command prompt (no make file (as Make.com is not a valid .com file), and no .cmd file). Similarly, there are no cmake or similar files to provide direction on how to build.

**Comment by dlemstra** [comment]
That document is copied from the repository here: https://github.com/ImageMagick/ImageMagick-Windows. We should probably just add a link in this file instead. Thanks for letting us known.
