### ISSUE TITLE
ProfileImage:  profile.c: 1102:13: error:  artifact undeclared

### ISSUE THREAD

**Issue by GPU-pipeline-guru** [ImageMagick/ImageMagick#4128]
### ImageMagick version

7.1.0.5

### Operating system

Linux

### Operating system, version and so on

ubuntu 20.10

### Description

Build fails
../MagickCore/profile.c: In function 'ProfileImage':
../MagickCore/profile.c:1102:13: error: 'artifact' undeclared (first use in this function)
 1102 |             artifact=GetImageArtifact(image,"profile:highres-transform");
      |             ^~~~~~~~
../MagickCore/profile.c:1102:13: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [Makefile:8993: MagickCore/libMagickCore_7_Q64HDRI_la-profile.lo] Error 1

### Steps to Reproduce

configure
make

### Images

![image](https://user-images.githubusercontent.com/79639097/131308213-340cf6f2-f055-4a38-80c7-2cb2aace7a55.png)

**Comment by dlemstra** [comment]
Thanks for reporting this. Seems that I made a mistake yesterday, will resolve this later today.
