### ISSUE TITLE
DisplayVersion in the Control Panel

### ISSUE THREAD

**Issue by quhxl** [ImageMagick/ImageMagick#4133]
### Operating system

Windows

### Operating system, version and so on

21H2

### Description

To increase compatibility with the Windows package manager winget, the version number in the control panel should be changed with each update. For example, it is possible to implement further subversions and change the version number from 7.1.0-1 to 7.1.0-2 and so on. This way the users would be notified at each update.

### Steps to Reproduce

1. Install any version of ImageMagick
2. Check the control panel
3. See the same version number for different versions

### Images

![Screenshot 2021-08-30 194400](https://user-images.githubusercontent.com/69106310/131381783-73c327d4-2794-464b-b1d8-f8a09429d502.png)

**Comment by dlemstra** [comment]
We made some changes to the installer settings and the next release will have the following version number:
![afbeelding](https://user-images.githubusercontent.com/10426229/132104524-c0de239c-6313-4fbe-9abf-fb3e4c6f3a62.png)
