### ISSUE TITLE
Images cannot be encoded into PNG in parallel in Magick++

### ISSUE THREAD

**Issue by atk91** [ImageMagick/ImageMagick#4134]
### ImageMagick version

 7.1.0-4

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

Images cannot be encoded into PNG in parallel in Magick++

### Steps to Reproduce

Compile the following code with 
```
g++ -g `Magick++-config --cxxflags --cppflags` -O2 -o demo main.cpp `Magick++-config --ldflags --libs`
```

```
#include <Magick++.h> 
#include <iostream> 
#include <vector>
#include <thread>
#include <mutex>

using namespace std; 
using namespace Magick; 


void log(const char* message) {
    static std::mutex log_mutex;
    std::lock_guard<std::mutex> guard(log_mutex);
    std::cout << message << std::endl;
}

Blob doStuff() {
    Image image;
    image.read( "stark.jpg" );
    log("Starting scale");
    image.scale("5000x5000!");
    log("Scale done");
    Blob res;
    log("Starting write");
    image.write(&res, "png");
    log("Write done");
    return res;
}

int main(int argc,char **argv) 
{ 
  InitializeMagick(*argv);

  std::vector<std::thread> ts;
  for (int i = 0; i < 8; i++) {
      ts.emplace_back(doStuff);
  }
  for (std::thread& t: ts) {
      t.join();
  }
  std::cout << "All done";
  return 0; 
} 

```

In contrast with scaling, no two `.write`s will be executed concurrently, as you can see from when `Write done` will be printed, also one may see in `top` that only one CPU will be utilized. It seems like `.write(...)` function is protected by some kind of mutex. There's no such problems with webp, for example.

### Images

![stark](https://user-images.githubusercontent.com/3193829/131396264-094fec23-395c-413b-88a1-5ac55dd2cf51.jpg)

**Comment by urban-warrior** [comment]
The PNG coder and libpng delegate library are re-entrant.  PNG utilizes compression.  Perhaps all the scaling is completed before any of the threads complete the compression step prior to writing.  Try resizing to 1x1.  Now we see `Write done` interleaved with scaling.

**Comment by dlemstra** [comment]
Lets continue the conversation in #4123 instead. There is no need to open both an issue and a discussion when you don't get an answer quick enough.
