### ISSUE TITLE
Compare CLI tool no longer works

### ISSUE THREAD

**Issue by njdoyle** [ImageMagick/ImageMagick#414]
I'm trying to use the compare tool but it isn't working. I've built both ImageMagick 7.0.4-10 and 7.0.5-5 on macOS and both fail in trivial cases. Here's what I see:

```
$ magick compare logo: logo:
compare:  `logo:' @ error/compare.c/CompareImagesCommand/967.
```

**Comment by fmw42** [comment]
try
`magick compare logo: logo: null:`

**Comment by njdoyle** [comment]
You're right, sorry, my problem was actually caused by something else. I misattributed it to my incorrect use of compare. Thanks.

**Comment by Mellbourn** [comment]
What was the "something else"? I'm getting this message and I don't understand the cause.
