### ISSUE TITLE
Shadow x y offset does not go to the upper left

### ISSUE THREAD

**Issue by akicho8** [ImageMagick/ImageMagick#4151]
### ImageMagick version

7.1.0-5

### Operating system

MacOS

### Operating system, version and so on

11.5.2

### Description

It works correctly when executed on the command line.
However, running from rmagick does not work properly.

With reference to rmagick code, shadow was running with the correct argument.
I check arguments with printf, it was the correct value.
https://github.com/rmagick/rmagick/blob/main/ext/RMagick/rmimage.c#L12503

### Steps to Reproduce

# Command Line

    convert logo: -transparent white \( +clone -shadow 50x4-5-5 \) +swap -background white -flatten output1.png

# rmagick

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "rmagick"
end

require "rmagick"
require "rmagick/version"
include Magick

VERSION        # => "4.2.2"
Magick_version # => "ImageMagick 7.1.0-5 Q16 x86_64 2021-08-22 https://imagemagick.org"

image1 = Image.read("logo:").first.transparent("white")
shadow1 = image1.shadow(-5, -5, 4, "50%") # -shadow 50x4-5-5 (Same arguments as convert)
shadow1.write("shadow1.png") # <-- At this point, shadows in the lower right direction
# The following is a code that is not related to this problem that only the appearance is easy to understand
image1 = shadow1.composite(image1, 0, 0, OverCompositeOp)
canvas = Image.new(image1.columns, image1.rows) { |e| e.background_color = "white" }
canvas.composite!(image1, 0, 0, OverCompositeOp)
canvas.write("output2.png")
```

### Images

# output1.png (convert command)

![output1](https://user-images.githubusercontent.com/808955/132089948-c2a7b71f-d523-43d5-8570-864598523ae2.png)

# output2.png (rmagick)

![output2](https://user-images.githubusercontent.com/808955/132089954-3027ae6e-dc36-4972-8349-2861bee37eae.png)

**Comment by snibgo** [comment]
Your command line uses "-flatten", but your rmagick code uses "composite". As these use different metadata for offsets, I suppose that is the problem.

I know nothing about rmagick, but see https://rmagick.github.io/ilist.html#flatten_images

**Comment by akicho8** [comment]
> Your command line uses "-flatten", but your rmagick code uses "composite". As these use different metadata for offsets, I suppose that is the problem.

When I made `shadow1`, I was able to make shadows in the lower right direction.
The following code has nothing to do with this problem.
It is a code written to match the appearance and the command line appearance.

**Comment by fmw42** [comment]
That is because you are using -flatten (-layers flatten) and should be using -layer merge. -flatten clips the output to the size of the input. -layers merge expands the output canvas.  See https://legacy.imagemagick.org/Usage/layers/


`convert logo: -transparent white \( +clone -shadow 50x4-5-5 \) +swap -background white -layers merge +repage output1.png`

![output1](https://user-images.githubusercontent.com/13458218/133865705-f13c3809-78f5-417e-96c7-166873c35a19.png)

**Comment by akicho8** [comment]
I'm sorry I could not tell the intention properly. :sob:
I have not asked how to use convert command line option.
The command line is an example for confirming that you have a shadow on the upper left when you specify `50x4-5-5`.
On the other hand, RMagick's code does not turn the shadow at the top left despite specifying the **same option**.
That is the essence of the problem.

> shadow1 = image1.shadow(-5, -5, 4, "50%") # -shadow 50x4-5-5 (Same arguments as convert)

**Comment by akicho8** [comment]
It became works.

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "rmagick"
end

require "rmagick"
require "rmagick/version"
include Magick

VERSION        # => "4.2.2"
Magick_version # => "ImageMagick 7.1.0-5 Q16 x86_64 2021-08-22 https://imagemagick.org"

image1 = Image.read("logo:").first.transparent("white")
shadow1 = image1.shadow(-5, -5, 4, "50%") # -shadow 50x4-5-5
shadow1.write("shadow1.png")

if false
  # Wrong synthesis method
  image1 = shadow1.composite(image1, 0, 0, OverCompositeOp)
  canvas = Image.new(image1.columns, image1.rows) { |e| e.background_color = "white" }
  canvas.composite!(image1, 0, 0, OverCompositeOp)
  canvas.write("output2.png")
end

# Correct synthesis method
image_list = ImageList.new
image_list.new_image(image1.columns, image1.rows, SolidFill.new("white"))
image_list << shadow1
image_list << image1
image_list.flatten_images.write("output2.png")
```
