### ISSUE TITLE
Windows arm64 support?

### ISSUE THREAD

**Issue by pb5050** [ImageMagick/ImageMagick#4157]
### Is your feature request related to a problem? Please describe.

any plans on this please?

### Describe the solution you'd like

add arm64

**Comment by dlemstra** [comment]
As soon as @Github has hosted `ARM64` runners we will check if we can add support for this.

**Comment by dlemstra** [comment]
We now have arm64 support on Windows but this is not yet included in our releases.

**Comment by dlemstra** [comment]
Support for this will become available in the next release.
