### ISSUE TITLE
imagemagick's /usr/bin/import doesn't work with touchpad

### ISSUE THREAD

**Issue by trufanov-nok** [ImageMagick/ImageMagick#4176]
### ImageMagick version

8:6.9.11.60+dfsg-1ubuntu1 amd64  

### Operating system

Linux

### Operating system, version and so on

Kubuntu 21.04, Linux 5.11.0-31-generic 

### Description

Operating System: Kubuntu 21.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.84.0
Qt Version: 5.15.2
Kernel Version: 5.11.0-31-generic
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × Intel® Core™ i7-3520M CPU @ 2.90GHz
Memory: 7,6 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

Notebook: Lenovo g780

Today, while debugging 3rd party python script I accidentally pasted the script contents in a console window instead of python interpretator. The script was started with `import blablabla` as most of pythons scripts. Then I found out that there is such tool as `import` which is installed of my system with imagemagick package. That tool surprisingly for me was launched and blocked all input, while displaying a strange shaped cursor. Via the phone I read its man page, but couldn't shut it down till I connect a mouse to my notebook. It's need to be said that I almost never use a mouse and work with only a touchpad. And its buttons are broken. I'm using a double tap as a button press. So, the problem is that `import` command isn't response to a "clicks" made via a touchpad (double taps). Hopefully I found and tried a mouse, but believe me, I use it so rare, that I could not had it at all. In this case I would be forced to forcefully power off the machine.

Could you please doublecheck if `import` application(?) is working correctly with only a touchpad's double taps?

### Steps to Reproduce

1. Launch `import` on a notebook
2. Try to close it with only touchpad's double taps

**Comment by urban-warrior** [comment]
The `import` application is behaving as intended.  It locks the screen and provides a cursor for the user to locate an area of interest to create a screenshot.  The screenshot takes place once the mouse button is pushed.   The issue is with the touchpad.  As long as the touchpad can map taps to a mouse click, `import` will behave as expected.  Perhaps touchpad blocks mouse clicks when the screen is locked?
