### ISSUE TITLE
`coders/yuv.c` compilation produces a `-Wfor-loop-analysis` warning.

### ISSUE THREAD

**Issue by d-ph** [ImageMagick/ImageMagick#418]
Hello,

When compiling current master branch from source, I get the following warning:
```
CC       coders/MagickCore_libMagickCore_7_Q16HDRI_la-yuv.lo
coders/yuv.c:709:13: warning: variable 'x' is incremented both in the loop header and in the loop body [-Wfor-loop-analysis]
            x++;
            ^
coders/yuv.c:681:55: note: incremented here
          for (x=0; x < (ssize_t) yuv_image->columns; x++)
                                                      ^
1 warning generated.
```
I quickly checked that for-loop and it indeed seems suspicious to me: [link](https://github.com/ImageMagick/ImageMagick/blob/f6ff9ea/coders/yuv.c#L681), [link](https://github.com/ImageMagick/ImageMagick/blob/f6ff9ea/coders/yuv.c#L709).

I might be wrong though. Feel free to close this ticket if this is excepted (in that case the warning should actually be suppressed somehow, but I don't know whether that's possible).

Thank you.

**Comment by mikayla-grace** [comment]
False positive.  The code is correct.  However, we'll add a patch to remove the warning.

**Comment by dlemstra** [comment]
Can you rebuild IM again and check if your warning is gone @d-ph? Feel free to close the issue yourself then.

**Comment by d-ph** [comment]
All good now.

Thanks for not leaving false-positive compilation warnings in the codebase.
