### ISSUE TITLE
how to support cocoa app ???

### ISSUE THREAD

**Issue by liufsd** [ImageMagick/ImageMagick#419]
HI~
I have test Magick++ on cocoa app. and run success when not enable sandbox.
(config like this: https://www.youtube.com/watch?v=7miwnp8iDm8  or here : http://stackoverflow.com/questions/41254653/problems-using-imagemagick-in-xcode-c-application)
but if i open sandbox mod enable. it will crash .

libc++abi.dylib: terminating with uncaught exception of type Magick::ErrorModule: MagickCocoa: UnableToLoadModule '/usr/local/Cellar/imagemagick/7.0.5-4/lib/ImageMagick//modules-Q16HDRI/coders/png.la': file not found @ error/module.c/OpenModule/1279

i have post my demo project here: https://github.com/liufsd/MagickCocoa
and if you want close sandbox mod (just got target and close app sandbox)

please help me~.

**Comment by liufsd** [comment]
i think i need build Magick++  library by myself. and not use the system library by brew install.

**Comment by liufsd** [comment]
Any idea about this issue like work on ios library https://www.imagemagick.org/script/binary-releases.php#iOS

**Comment by dlemstra** [comment]
I don't think we are able to help you @liufsd.

**Comment by icebergcwp1990** [comment]
I have the same issue, Have you found any solution?

**Comment by liufsd** [comment]
@icebergcwp1990 sorry, no!

**Comment by icebergcwp1990** [comment]
This, if I figure out this, I will let you know , you too.

**Comment by liufsd** [comment]
👌
