### ISSUE TITLE
ImageMagick installer doesn't create %localappdata%/ImageMagick and is unusable

### ISSUE THREAD

**Issue by checkraisefold** [ImageMagick/ImageMagick#4209]
### ImageMagick version

7.1.0-7

### Operating system

Windows

### Operating system, version and so on

x64 Home 1909

### Description

Upon installation, any ImageMagick PNG operation doesn't work. I'm not sure where to find an installer log file, which should assist with debugging this problem.

### Steps to Reproduce

1. Install ImageMagick
2. Perform any (in this case, haven't tested with other formats) PNG operation
3. Unable to find decode delegate for 'PNG'

**Comment by snibgo** [comment]
Please say where you installed it from. Was it https://imagemagick.org/script/download.php#windows ? If so, which .exe file did you download and install from?

**Comment by checkraisefold** [comment]
> Please say where you installed it from. Was it https://imagemagick.org/script/download.php#windows ? If so, which .exe file did you download and install from?

ImageMagick-7.1.0-7-Q16-HDRI-x64-dll.exe

**Comment by dlemstra** [comment]
I am unable to reproduce the issue. On a virtual machine where I just installed ImageMagick I can do this without any problems:

```cmd
C:\Users\dirk>magick -version
Version: ImageMagick 7.1.0-7 Q16-HDRI x64 2021-09-12 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2019 (192930133)

C:\Users\dirk>magick logo: logo.png

C:\Users\dirk>magick identify logo.png
logo.png PNG 640x480 640x480+0+0 8-bit sRGB 256c 27398B 0.000u 0:00.000
```
