### ISSUE TITLE
Assertion failed: (!scaled_font->cache_frozen), function _cairo_scaled_glyph_page_destroy, file cairo-scaled-font.c, line 459.

### ISSUE THREAD

**Issue by hengsoheak** [ImageMagick/ImageMagick#421]
I've installed ImageMagick as below environment and try to used Pango with Unicode characters then I found below problem. 

**Environment:**
Version : ImageMagick 7.0.5-4 Q16 x86_64 2017-04-04
Features : Cipher DPC HDRI 
Delegates (built-in) : bzlib djvu fftw fontconfig freetype gvc jp2 lcms lzma openexr pangocairo png x xml zlib
OS        : OS X EI Capitan

**Check Pango Version:**

Commend  : identify -list format | grep -Ei "Description|pango"
Result         : PANGO* r--   Pango Markup Language (Pangocairo 1.40.4)

After I try to create images as below commend-line

`convert -size 500x500 xc:'#263238' \(-gravity Center -size 100x50 -background none -font "IRANSans.ttf" -pointsize 32 pango:"<span face='IRANSans' foreground='white'>درود</span>" \) -gravity Center -composite bge.png`

**RESULT:**

```
Assertion failed: (!scaled_font->cache_frozen), function _cairo_scaled_glyph_page_destroy, file cairo-scaled-font.c, line 459.
Abort trap: 6
```

I've list all configuration be run **convert -list configure** commend-line.

`convert -list configure

Path: /usr/local/lib/ImageMagick-7.0.5//config-Q16HDRI/configure.xml

Name           Value
-------------------------------------------------------------------------------
CC             gcc
CFLAGS         -I/opt/local/include/libxml2 -I/opt/local/include/libpng16  -I/opt/local/include/pango-1.0 -I/opt/local/include/harfbuzz -I/opt/local/include -I/opt/local/include/pango-1.0 -I/opt/local/include/cairo -I/opt/local/include/glib-2.0 -I/opt/local/lib/glib-2.0/include -I/opt/local/include -I/opt/local/include/pixman-1 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include/libpng16 -I/opt/local/include -D_THREAD_SAFE -I/opt/local/include/OpenEXR -I/opt/local/include -I/opt/local/include/openjpeg-2.1 -I/opt/local/include -I/opt/local/include/graphviz -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include/freetype2 -I/opt/local/include -I/opt/local/include -I/opt/local/include   -g -O2 -Wall -mtune=haswell -fexceptions -D_FORTIFY_SOURCE=0 -D_THREAD_SAFE -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
CODER_PATH     /usr/local/lib/ImageMagick-7.0.5/modules-Q16HDRI/coders
CONFIGURE      ./configure 
CONFIGURE_PATH /usr/local/etc/ImageMagick-7/
COPYRIGHT      Copyright (C) 1999-2016 ImageMagick Studio LLC
CPPFLAGS       -I/usr/local/include/ImageMagick-7
CXX            g++
CXXFLAGS       -g -O2 -D_THREAD_SAFE -pthread
DEFS           -DHAVE_CONFIG_H
DELEGATES      bzlib djvu mpeg fftw fontconfig freetype lcms lzma openexr openjp2 pango png ps x xml zlib
DISTCHECK_CONFIG_FLAGS  --disable-deprecated  --with-quantum-depth=16  --with-jemalloc=no  --with-umem=no  --with-autotrace=no  --with-gslib=no  --with-fontpath=  --with-rsvg=no  --with-perl=no 
DOCUMENTATION_PATH /usr/local/share/doc/ImageMagick-7
EXEC-PREFIX    /usr/local
EXECUTABLE_PATH /usr/local/bin
FEATURES       DPC HDRI Cipher
FILTER_PATH    /usr/local/lib/ImageMagick-7.0.5/modules-Q16HDRI/filters
GIT_REVISION   11757
HOST           x86_64-apple-darwin15.6.0
INCLUDE_PATH   /usr/local/include/ImageMagick-7
LDFLAGS        -L/usr/local/lib   -L/usr/X11/lib
LIB_VERSION    0x705
LIB_VERSION_NUMBER 7,0,5,4
LIBRARY_PATH   /usr/local/lib/ImageMagick-7.0.5
LIBS             -L/opt/local/lib -llcms2  -L/opt/local/lib -lfreetype     -L/opt/local/lib -lpng16  -L/opt/local/lib -ldjvulibre -L/opt/local/lib -lfftw3   -L/opt/local/lib -lfontconfig -lfreetype    -lXext -lXt   -lSM -lICE -lX11  -L/opt/local/lib -llzma -lbz2 -L/opt/local/lib -lIlmImf -lImath -lHalf -lIex -lIexMath -lIlmThread -L/opt/local/lib -lopenjp2 -L/opt/local/lib -lpangocairo-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lintl -lcairo  -L/opt/local/lib -lxml2 -L/opt/local/lib -lgvc -lcgraph -lcdt -L/opt/local/lib -lz  -lm     
NAME           ImageMagick
PCFLAGS        -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
PREFIX         /usr/local
QuantumDepth   16
RELEASE_DATE   2017-04-04
SHARE_PATH     /usr/local/share/ImageMagick-7
SHAREARCH_PATH /usr/local/lib/ImageMagick-7.0.5/config-Q16HDRI
TARGET_CPU     x86_64
TARGET_OS      darwin15.6.0
TARGET_VENDOR  apple
VERSION        7.0.5
WEBSITE        http://www.imagemagick.org

Path: [built-in]

Name           Value
-------------------------------------------------------------------------------
FEATURES       
NAME           ImageMagick
`
THANK FOR HELP.

**Comment by mikayla-grace** [comment]
Your command worked for us without complaint.  We're using ImageMagick 7.0.5-6 and Pangocairo 1.40.5.  The result was PNG image with the international characters drawn on a canvas as expected.

**Comment by dlemstra** [comment]
@hengsoheak Can we close this issue?
