### ISSUE TITLE
move ffmpeg out of the Windows path

### ISSUE THREAD

**Issue by Yay295** [ImageMagick/ImageMagick#422]
I use both ffmpeg and ImageMagick on my Windows computer, and both are in my path. Since ImageMagick has its own copy of ffmpeg, and that copy is in the main folder with everything else, and that main folder is added to the path as the first item on install, when I then try to use ffmpeg it uses ImageMagick's ffmpeg instead of my own. Please don't leave ffmpeg in the path.

**Comment by dlemstra** [comment]
I think it would make more sense to make installing 'ffmpeg' optional during the installation process. I'll try to add a new option for this to the installer as soon as possible.

**Comment by dlemstra** [comment]
The installer of the next version of ImageMagick will include an option that you can use to prevent the installation of FFmpeg.

**Comment by bazzilic** [comment]
Is this available through command-line install, e.g. when installing through [Chocolatey](https://chocolatey.org/packages/imagemagick.app)?
It would be neat if ImageMagick can detect whether ffmpeg is already available on path.
