### ISSUE TITLE
Security policy "(null)" invoked

### ISSUE THREAD

**Issue by yunal** [ImageMagick/ImageMagick#4225]
### ImageMagick version

7.1.0-7

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.10

### Description

This was first noticed on CentOS 6 running stock CentOS ImageMagick 6.9.10, but I have reproduced it on Ubuntu 20.10 with the freshest ImageMagick: 7.1.0-7.

We have installed a security policy to prevent all delegated commands, but it turns out that some legacy software is giving ImageMagick urls so we need to be able to delegate http/https to curl.

```
$ /usr/local/bin/convert  'https://akamai.vgc.no/v2/images/f8fb4219-897e-497a-a965-8fcb45f68950?fit=crop&h=1267&w=1900&s=f033e555d3849160777106727eaa68fda7511280' foo.jpg
convert: attempt to perform an operation not allowed by the security policy `(null)' @ error/delegate.c/InvokeDelegate/1734.
convert: no images defined `foo.jpg' @ error/convert.c/ConvertImageCommand/3322.
```

### Steps to Reproduce

We have this policy.xml:
```
<policymap>
  <!-- Disable all external commands -->
  <policy domain="delegate" rights="none" pattern="*" />
  <!-- This allows execution of curl for http and https -->
  <policy domain="delegate" rights="execute" pattern="{http:decode,https:decode}" />

  <!-- Only allow whitelisted image formats and http/https                                                                                                                
  <policy domain="coder" rights="none" pattern="*" />
  <policy domain="coder" rights="read|write" pattern="{gif,GIF,jpg,JPG,jpeg,JPEG,png,PNG,webp,WEBP,avif,AVIF,heic,HEIC,tiff,TIFF,HTTP,HTTPS}" />
</policymap>
```

Retrieving any jpeg via https results in this:

```
$ /usr/local/bin/convert https://upload.wikimedia.org/wikipedia/en/8/8d/David-bowie-lets-dance.jpg bar.jpg
convert: attempt to perform an operation not allowed by the security policy `(null)' @ error/delegate.c/InvokeDelegate/1734.
convert: no images defined `bar.jpg' @ error/convert.c/ConvertImageCommand/3322.
```

### Images

Bug requires https access.

**Comment by yunal** [comment]
Removing the `<policy domain="delegate" rights="none" pattern="*" />` rule fixes this but we'd like to block everything and then whitelist the few things we want to allow.

**Comment by dlemstra** [comment]
It looks like we were missing a null check for one of the arguments in `InvokeDelegate`. A patch has been pushed to fix this and you will no longer get an error message about `(null)` in the next releasse.
