### ISSUE TITLE
problem in installing ImageMagick

### ISSUE THREAD

**Issue by samrangy** [ImageMagick/ImageMagick#423]
I an using Mac OS Sierra and getting the following error after giving the command : make && make check.
Can someone please help me to resolve it?

[test-suite.txt](https://github.com/ImageMagick/ImageMagick/files/912454/test-suite.txt)

**Comment by dlemstra** [comment]
It looks like ImageMagick is build without font support. Have you tried what is suggested here: https://github.com/ImageMagick/ImageMagick/issues/374#issuecomment-279252866?
