### ISSUE TITLE
Identify doesn't read EXIF in JXL pictures

### ISSUE THREAD

**Issue by jackyhallyday** [ImageMagick/ImageMagick#4232]
### ImageMagick version

7.1.0-7

### Operating system

Linux

### Operating system, version and so on

Debian 10

### Description

I've got a JPEG file with EXIF data, that Identify is able to list when I use the -verbose option.
Then I convert that JPEG file to JPEG XL with cjxl.
Identify can't show me the EXIF informations in that JXL file.

I wasn't sure if the EXIF infos were being kept during the conversion process, so I asked and it should be the case, so I guess JXL is not fully supported by Identify yet?
https://twitter.com/JackyHallyday/status/1438410975963713539

### Steps to Reproduce

Get a JPEG file with EXIF data
Convert it to JXL with cjxl
Try "Identify -verbose" on that file.

### Images

Example of a JPEG file and the generated JXL.
Github doesn't support JXL files yet, so I put them in a Zip.

[Archive.zip](https://github.com/ImageMagick/ImageMagick/files/7177051/Archive.zip)

**Comment by urban-warrior** [comment]
ImageMagick does not currently support EXIF in a JXL image file.  We'll add support but we do not have an ETA just yet.

**Comment by dlemstra** [comment]
We will need to wait till it becomes available through the API: https://twitter.com/jonsneyers/status/1439161240119660547.
