### ISSUE TITLE
84/86 Testsuite

### ISSUE THREAD

**Issue by kekdude** [ImageMagick/ImageMagick#424]
* TOTAL: 86
* PASS:  84
* SKIP:  0
* XFAIL: 0
* FAIL:  2
* XPASS: 0
* ERROR: 0

[test-suite.log.txt](https://github.com/ImageMagick/ImageMagick/files/921938/test-suite.log.txt)

**Comment by dlemstra** [comment]
It looks like ImageMagick cannot properly handle fonts. Have you tried what is suggested here: https://github.com/ImageMagick/ImageMagick/issues/374#issuecomment-279252866?
