### ISSUE TITLE
ImageMagick convert from ai to png shows some patches in the image

### ISSUE THREAD

**Issue by 9shet56** [ImageMagick/ImageMagick#4240]
### ImageMagick version

ImageMagick 7.0.10-3 Q16

### Operating system

Windows

### Operating system, version and so on

Windows 2016 Standard, 64 bit OS

### Description

We are using an Adobe Illustrator type of Image and trying to convert into png using ImageMagick. After converting it shows up some extra patches in the image in our Production environment, but the same image in our non production environment shows up correctly without any black patches.
The ImageMagick version in both the environments are same.

'Im unable to attach the file to this issue.

### Steps to Reproduce

Used below command in the server having ImageMagick.
("
magick convert <filename.ai> <filename.png>
")

**Comment by 9shet56** [comment]
Any other way can I attach the error screenshots?

**Comment by dlemstra** [comment]
You are most likely using a different version of Ghostscript in both situations.
