### ISSUE TITLE
Horrible output results when using tile option with some specific images

### ISSUE THREAD

**Issue by toonerd** [ImageMagick/ImageMagick#4255]
### ImageMagick version

7.1.0-7

### Operating system

Linux

### Operating system, version and so on

centos-release-7-9.2009.1.el7.centos.x86_64

### Description

Trying to tile a watermark on some images while resizing them using the command:
`convert THE_INPUT_IMAGE.jpg -strip -colorspace sRGB -resize "480X480>" -size "480X480>" tile:THE_WATERMARK_IMAGE.png -quality 90 -composite output.jpg`
The command is working well for most of the input images, but for some specific images it doesn't.

**Comment by snibgo** [comment]
Please show examples of "for some specific images it doesn't".

**Comment by toonerd** [comment]
I have edited again and attached the watermark image and one of the bad images which cause the command fail.
