### ISSUE TITLE
Convert colorspace back to original, color preservation

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#426]
Hi,

One of the users of Imagick reported an [issue](https://stackoverflow.com/questions/43347921/keep-colors-when-converting-cmyk-to-srgb-to-cmyk-imagick-php), that I didn't know how to answer; when you convert an image from CMYK to sRGB and then back to CMYK how do you get an image that looks like the original?

Using one of the files from here: https://drive.google.com/drive/folders/0B0_03DCODKMJVXRvRUhPQTh6ZjA?usp=sharing

And the commands:

convert 2k_213.jpg -colorspace sRGB  output_cli_srgb.jpg
convert output_cli_srgb.jpg -colorspace CMYK output_cli_cmyk.jpg

Gives the images shown below. The final output CMYK image looks very different to the input image.

How should the conversion from sRGB back to CMYK be done to best preserve the appearance of the image?

2k_213.jpg - aka the start image:
![2k_213](https://cloud.githubusercontent.com/assets/1505719/25063623/90fc8268-21e1-11e7-8534-108eb742a051.jpg)

output_cli_srgb.jpg:
![output_cli_srgb](https://cloud.githubusercontent.com/assets/1505719/25063624/982dd460-21e1-11e7-9b2e-a81e81c04693.jpg)

output_cli_cmyk.jpg:
![output_cli_cmyk](https://cloud.githubusercontent.com/assets/1505719/25063625/a588f036-21e1-11e7-9fe6-09223cd37dff.jpg)

**Comment by saurabheights** [comment]
You should see this [Gamut Image](https://image.slidesharecdn.com/adobeandsrgbandcolorgamut-160317030601/95/adobe-rgb-and-srgb-and-color-gamut-4-638.jpg?cb=1458184062). Notice that certain range of colours in CMYK gamut are not in sRGB gamut. Thus any conversion from CMYK to sRGB should lead to permanent loss of original image color.

**Comment by Danack** [comment]
Hi @saurabheights,

> Thus any conversion from CMYK to sRGB should lead to permanent loss of original image color.

I think I understand that some colors just can't be expressed in sRGB, and some information would be lost. However it _looks_ like:

i) The conversion from CMYK to sRGB is working fine, it's the converting back that is losing information, which is contrary to what you suggested.

ii) The color information loss is a lot larger than I would expect.

Looking elsewhere, I've seen suggestions that using the rendering intent setting, and/or black point compensation should allow for the colorspace conversion to be done with less perceptual change, however I'm not sure what these should be set to.

**Comment by fmw42** [comment]
Have you tried using profiles? That is the most accurate way -- at least more accurate than just -colorspace

**Comment by saurabheights** [comment]
@Danack : Your reply is on spot. I tried your code to confirm however I noticed an issue. My cli CMYK output image is exactly same as sRGB image produced by you. This looks like a bug or manual error. Could you give another try to reproduce the CMYK image? If you still see the issue, report IM version and platform as well. 

My IM version(on Mac):-
> convert --version
Version: ImageMagick 7.0.4-4 Q16 x86_64 2017-01-18 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png tiff webp xml zlib

Commands I ran(the image is sRGB image uploaded by danack):-

```
> wget https://cloud.githubusercontent.com/assets/1505719/25063624/982dd460-21e1-11e7-9b2e-a81e81c04693.jpg

> convert 982dd460-21e1-11e7-9b2e-a81e81c04693.jpg -colorspace CMYK output_cli_cmyk_secondManualTry.jpg

> exiftool -g 982dd460-21e1-11e7-9b2e-a81e81c04693.jpg 
---- ExifTool ----
ExifTool Version Number         : 10.12
---- File ----
File Name                       : 982dd460-21e1-11e7-9b2e-a81e81c04693.jpg
Directory                       : .
File Size                       : 425 kB
File Modification Date/Time     : 2017:04:15 18:14:07+05:30
File Access Date/Time           : 2017:04:17 14:55:52+05:30
File Inode Change Date/Time     : 2017:04:17 14:55:23+05:30
File Permissions                : rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Image Width                     : 1754
Image Height                    : 2421
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:4:4 (1 1)
---- JFIF ----
JFIF Version                    : 1.01
Resolution Unit                 : inches
---- Photoshop ----
X Resolution                    : 300
Displayed Units X               : inches
Y Resolution                    : 300
Displayed Units Y               : inches
---- Composite ----
Image Size                      : 1754x2421
Megapixels                      : 4.2

> exiftool -g output_cli_cmyk_secondManualTry.jpg 
---- ExifTool ----
ExifTool Version Number         : 10.12
---- File ----
File Name                       : output_cli_cmyk_secondManualTry.jpg
Directory                       : .
File Size                       : 788 kB
File Modification Date/Time     : 2017:04:17 14:55:45+05:30
File Access Date/Time           : 2017:04:17 14:56:24+05:30
File Inode Change Date/Time     : 2017:04:17 14:55:45+05:30
File Permissions                : rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
Image Width                     : 1754
Image Height                    : 2421
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 4
---- JFIF ----
JFIF Version                    : 1.01
Resolution Unit                 : inches
---- APP14 ----
DCT Encode Version              : 100
APP14 Flags 0                   : (none)
APP14 Flags 1                   : (none)
Color Transform                 : YCCK
---- Photoshop ----
X Resolution                    : 300
Displayed Units X               : inches
Y Resolution                    : 300
Displayed Units Y               : inches
---- Composite ----
Image Size                      : 1754x2421
Megapixels                      : 4.2
```

**Comment by dlemstra** [comment]
@saurabheights and @Danack Do we still need to assist you?

**Comment by Danack** [comment]
I'll close it. I'm spending less time looking after Imagick, and am not going to chase other people's problems.

**Comment by saurabheights** [comment]
@dlemstra :- There was never any issue in imagemagick, I had already checked this using latest IM version and retrying Danack commands. It's ok to close as long as Danack agrees(and he does).
