### ISSUE TITLE
memory leak in svg

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#427]
on ImageMagick latest version

#identify $FILE
=================================================================
==23830==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 384 byte(s) in 1 object(s) allocated from:
    #0 0x7f6a59533b58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x69f9da in AcquireSVGInfo coders/svg.c:265
    #3 0x6ae6ca in ReadSVGImage coders/svg.c:3180
    #4 0x7f23d8 in ReadImage MagickCore/constitute.c:497
    #5 0x9e4e89 in ReadStream MagickCore/stream.c:1045
    #6 0x7f1486 in PingImage MagickCore/constitute.c:226
    #7 0x7f1a39 in PingImages MagickCore/constitute.c:327
    #8 0xbba496 in IdentifyImageCommand MagickWand/identify.c:319
    #9 0xc10fea in MagickCommandGenesis MagickWand/mogrify.c:183
    #10 0x40f839 in MagickMain utilities/magick.c:149
    #11 0x40fa06 in main utilities/magick.c:180
    #12 0x7f6a54842b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

SUMMARY: AddressSanitizer: 384 byte(s) leaked in 1 allocation(s).

testcase:
https://github.com/bestshow/p0cs/blob/master/memory-leak-in-svg.svg

Author: Haojun Hou in ADLab of Venustech

**Comment by dlemstra** [comment]
Can you give it another try with the code from our git repository (or wait for the next beta). Feel free to close the issue if you think this is resolved.

**Comment by bestshow** [comment]
The issue is resolved.
