### ISSUE TITLE
Label cut off for certain font

### ISSUE THREAD

**Issue by nicoruti** [ImageMagick/ImageMagick#4278]
### ImageMagick version

7.1.0.8

### Operating system

MacOS

### Operating system, version and so on

10.13.6

### Description

For certain (custom) fonts, I experience that the lables are slightly cut off (top left of 'S' in the example below).

### Steps to Reproduce

Download the font [Philly Sans](https://www.dafont.com/philly-sans.font).

Then run the following command:
`convert -size 1000x1000 -background none -channel RGBA -fill white -font "Philly-Sans" -interline-spacing -70 -gravity center label:"Sample" text.png`

### Images

![text](https://user-images.githubusercontent.com/4671020/134783848-6d6dd290-74d4-4948-a360-951ad1a2a3d0.png)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by nicoruti** [comment]
Thanks for the fast fix, @urban-warrior ! I just tested the latest version and it's working like a charm!
