### ISSUE TITLE
make: recipe for target 'MagickCore/libMagickCore_7_Q16HDRI_la-cache.lo' failed

### ISSUE THREAD

**Issue by kyleawayan** [ImageMagick/ImageMagick#4279]
### ImageMagick version

7.1.0-8

### Operating system

Linux

### Operating system, version and so on

Ubuntu Server 18.04.6 LTS

### Description

When running `make`, this error appears about `libMagickCore_7_Q16HDRI_la-cache.lo`:
```
  CC       MagickCore/libMagickCore_7_Q16HDRI_la-cache.lo
In file included from ./MagickCore/memory_.h:22:0,
                 from ./MagickCore/pixel-accessor.h:28,
                 from ./MagickCore/colorspace-private.h:24,
                 from MagickCore/cache.c:49:
MagickCore/cache.c: In function ‘GetPixelCachePixels’:
MagickCore/cache.c:2331:10: error: ‘exception’ undeclared (first use in this function); did you mean ‘ExceptionType’?
   assert(exception != (ExceptionInfo *) NULL);
          ^
MagickCore/cache.c:2331:10: note: each undeclared identifier is reported only once for each function it appears in
Makefile:8615: recipe for target 'MagickCore/libMagickCore_7_Q16HDRI_la-cache.lo' failed
make[1]: *** [MagickCore/libMagickCore_7_Q16HDRI_la-cache.lo] Error 1
make[1]: Leaving directory '/home/plex/ImageMagick-7.1.0'
Makefile:6121: recipe for target 'all' failed
make: *** [all] Error 2
```

Installing the previous version 7.1.0-7 works and compiles correctly.

### Steps to Reproduce

1. Clone the repo: `git clone https://github.com/ImageMagick/ImageMagick.git ImageMagick-7.1.0`
2. `cd` into the folder and run `./configure`
3. Run `make`

**Comment by dlemstra** [comment]
This was due to a mistake that was made earlier today. And a fix for this was just pushed. Thanks for reporting this but you were a bit to early.
