### ISSUE TITLE
convert to svg

### ISSUE THREAD

**Issue by RJGhugo** [ImageMagick/ImageMagick#4293]
### ImageMagick version

7.1.0.8-1

### Operating system

Linux

### Operating system, version and so on

Linux workstation 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64 GNU/Linux

### Description

scan a char/number as png
remove background
convert png to svg

svg not fully transformed

### Steps to Reproduce

convert 8-scanned.png -fuzz 20%% -transparent White 8-transparent.png
convert 8-transparent.png 8.svg

### Images

[example-8.zip](https://github.com/ImageMagick/ImageMagick/files/7258598/example-8.zip)

**Comment by RJGhugo** [comment]
Installed latest version of Birdfont. Works now.
The export from Inkscape works fine, also in the old version of Birdfont nor the ImageMagick.

**Comment by snibgo** [comment]
You say:
> svg not fully transformed

What does that mean? When I view 8.svg and 8-from-inkscape.svg in Inkscape, the shapes look the same.

**Comment by RJGhugo** [comment]
There seems to be a different between 8.svg and 8-from-inkscape.svg. The older version of birdfont ( 2.28.0-1) can not handle 8.svg. 2.29.5 can handle both.

**Comment by snibgo** [comment]
What is "birdfont"?

Both SVG files seem to be valid. If an old version of birdfont can't read one of the files, I suppose that was a bug which is now fixed.

**Comment by RJGhugo** [comment]
https://birdfont.org/

Thanks for the information. My knowledge about svg-files is quite limited. Just struggle over svg's for creating fonts...
