### ISSUE TITLE
caption '%t' for filenames with @ character segfaults imagemagick

### ISSUE THREAD

**Issue by ffloress** [ImageMagick/ImageMagick#43]
when I use $convert caption "%t" input.jpg output.png  , filenames with @    (like @photo.jpg)    makes imagemagick segfaults

**Comment by dlemstra** [comment]
What is the exact command line that you are running? And what is the output of convert -version ?

**Comment by ffloress** [comment]
Version: ImageMagick 6.7.7-10 2014-04-09 Q16 

I am running this exact command line:

montage -gravity center null: '*.*' -thumbnail 250x250 -sharpen 10 -bordercolor black -set caption '%t ' -fill white -pointsize 14 -background grey20 +polaroid -background Transparent -geometry '1x1-60+0<' -tile 8x montage_3.png

It works well inside a folder with many photos.

But if there are files with names like:  @instauser.jpg, @heyheymymy.jpg @123.jpg

The app breaks., and the only verbose is:
Segmentation Fault

**Comment by urban-warrior** [comment]
The -caption option no longer fails for filenames with @ prefix.
