### ISSUE TITLE
Missing images on forum discussions

### ISSUE THREAD

**Issue by pauloney** [ImageMagick/ImageMagick#430]
I would like to get a hold of a recent Forum content dump, so I can extract the URL's pointing to images ringing 404 and have a shot on asking for the restoration of these images - for the sake of a better reading and archival of the Forum. ImageShack which seems to be the biggest culprit has promised a restoration of the images upon request. I would like to get a list ready and prepare these requests for them.

I am trying, for example, to read:

    http://www.imagemagick.org/discourse-server/viewtopic.php?t=11726

but it is literally impossible to follow the discussion without the images. 

When ImageShack changed their web-site (and policies) and the images became unavailable they promised to restore any that were used in forums, but that would have required someone to make a list and pass it over to them.

**Comment by pauloney** [comment]
@dlemstra I don't understand why it was closed. I am asking for something so easy, a dump of the forum so I can deal with ImageShack.

**Comment by dlemstra** [comment]
Your question might be easy but for us it won't be easy to create a dump. We have on a small team and 1000 other things that also need our attention. I closed this because I don't think we will be able to give you the information anytime soon. I could reopen the issue if you don't mind getting the information in 1 or 2 years.

**Comment by pauloney** [comment]
I don't mind. I have already waited a year, so one more won't be much of a
problem...but I do believe creating this dump will take less time than what
you took to write the email.

Given some level of access I can do it all myself. Is there a way to get
some access to the forum data?

Paulo Ney

**Comment by mikayla-grace** [comment]
You should not need our help.  Just Google web-site mirroring and mirror https://www.imagemagick.org/discourse-server/.  Make sure you limit the bandwidth during the mirror.
