### ISSUE TITLE
Some, but not all, svg images not displaying

### ISSUE THREAD

**Issue by edencreeper** [ImageMagick/ImageMagick#4304]
### ImageMagick version

7.1.0-8

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

When trying to open some .svg images (but not all), display with throw an error
```
display: negative or zero image size `emacs-e.svg' @ error/image.c/SetImageExtent/2660.
display: no decode delegate for this image format `emacs-e.svg' @ error/svg.c/RenderRSVGImage/534.
```

It wouldn't appear to be an issue with the image itself as `nomacs` can display it just fine.

### Steps to Reproduce

run `display emacs-e.svg`

### Images

![maim-region-20211002-093122](https://user-images.githubusercontent.com/80257908/135709373-9a07b4e5-564e-4536-9fff-eeb0ed7f6a30.png)
![maim-full-20211002-093248](https://user-images.githubusercontent.com/80257908/135709396-0e917d79-9179-40a4-946a-84ba87066f05.png)

**Comment by snibgo** [comment]
emacs-e.svg may have a problem that some software ignores. Please paste a link to it.

**Comment by edencreeper** [comment]
https://github.com/edencreeper/dotfiles/blob/master/.config/doom/misc/splash-images/emacs-e.svg

**Comment by snibgo** [comment]
The file you have uploaded, named "emacs-e.svg", is an HTML file, not a SVG file.

**Comment by snibgo** [comment]
The SVG file looks fine.

I use Windows, so don't have "display". The following work fine with IM v7.1.0-4.
```
magick emacs.svg x.png

magick MSVG:emacs.svg x2.png
```
The first of those uses Inkscape. The second uses IM's internal MSVG decoder. Both results are 86x100 pixels.

Please try those "magick" commands.

**Comment by edencreeper** [comment]
Aha! Seemed to have fixed it by installing inkscape! I didn't realise that was a dependency, perhaps it was listed somewhere that i didn't notice?
Thanks for the help

**Comment by snibgo** [comment]
It isn't a dependency. If Inkscape is available (on the system path), IM will use it to rasterize SVG. If it isn't available, IM will use RSVG as an external delegate if that is in delegates.xml. Otherwise, it uses its own internal MSVG decoder. MSVG usually works for simple SVG files such as this one. Inkscape is the most complete rasterizer.

As a general rule, if an SVG isn't rasterized properly, check with "-verbose" that Inkscape is being used.

**Comment by ValZapod** [comment]
> Inkscape is the most complete rasterizer.

That is after Chrome's and firefox's, no? I mean they do fix a lot of crazy bugs there... But still. https://bugs.chromium.org/p/chromium/issues/detail?id=1212634
