### ISSUE TITLE
Non-breaking space on newline in caption breaks subsequent characters

### ISSUE THREAD

**Issue by vixducis** [ImageMagick/ImageMagick#4305]
### ImageMagick version

7.1.0-8

### Operating system

MacOS

### Operating system, version and so on

macOS 10.13.6

### Description

When you use ImageMagick to create a caption with a caption that contains a non-breaking space on the exact location where ImageMagick will break the line, the subsequent characters will no longer match. For example the input (the second space is a non-breaking space):
```
Нуорунен в Карелии
```
will result in the output:
![test](https://user-images.githubusercontent.com/378998/135727168-b1018a1c-4571-4027-a909-49ccca88845a.jpg)

I'm not entirely sure if the Russian characters are part of the issue here, though. Looks like an edge case though, as there are a lot of conditions to this bug. 

### Steps to Reproduce

``` bash
convert -size 160 -pointsize 19 -channel RGBA -fill "black" -weight 400 -font "Arial" -gravity NorthWest -background "white" caption:'Нуорунен в Карелии' test.jpg
```
Have a look at the output, `test.jpg`, which will contain different characters then the input (Нуорунен в Карелии).
Please make sure that the second space is a non-breaking space (not sure if GitHub will preserve them).

### Images

No input files required.

**Comment by ValZapod** [comment]
> . For example the input (the second space is a non-breaking space):

It is not. Check for yourself with https://www.babelstone.co.uk/Unicode/whatisit.html

**Comment by vixducis** [comment]
> It is not. Check for yourself with https://www.babelstone.co.uk/Unicode/whatisit.html

For me, that website correctly reports the nbsp in chrome and firefox, but not in safari. Anyway, as I mentioned in my STR:
> Please make sure that the second space is a non-breaking space (not sure if GitHub will preserve them).

This should result in the issue becoming obvious in the output.

**Comment by dlemstra** [comment]
This can be reproduced with caption:@test.txt ([test.txt](https://github.com/ImageMagick/ImageMagick/files/7273021/test.txt))

**Comment by ValZapod** [comment]
> reproduced with caption:@test.txt

I suppose you should insert UTF-8 BOM, EF BB BF.

**Comment by vixducis** [comment]
Even with a BOM, I still run into the same issue. This file does contain a BOM: [caption.txt](https://github.com/ImageMagick/ImageMagick/files/7273112/caption.txt)
And when I use it to run the command, I still get similar output.
``` bash
convert -size 160 -pointsize 19 -channel RGBA -fill "black" -weight 400 -font "Arial" -gravity NorthWest -background "white" caption:"$(cat caption.txt)" test.jpg
```

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by vixducis** [comment]
Thanks a lot for your quick intervention, this can now be closed as a fix is on the way!
(Thanks for creating this awesome product btw!)
