### ISSUE TITLE
-compare does not allow highlight or lowlight arguments

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#4312]
### ImageMagick version

7.1.0-8

### Operating system

MacOS

### Operating system, version and so on

OSX Sierra

### Description

With magick compare, one can specify highlight color and lowlight color. But that does work with magick ... -compare.

### Steps to Reproduce

![1](https://user-images.githubusercontent.com/13458218/135765002-e67e67bd-82c2-4a2f-920d-3f4f8f42ba28.jpg)

![2](https://user-images.githubusercontent.com/13458218/135765013-2f94bb1a-9b9f-4528-883d-d279306382be.jpg)

**magick compare:**

`magick compare -fuzz 10% 1.jpg 2.jpg -compose Src -highlight-color white -lowlight-color black result1.png`

![result1](https://user-images.githubusercontent.com/13458218/135765025-4881a3ad-dd3a-46e5-8f34-dd7cc835d7bb.png)

**magick ... -compare:**

`magick -fuzz 10% 1.jpg 2.jpg -compose Src -highlight-color white -lowlight-color black -compare result2.png`

**magick: unrecognized option `-highlight-color' at CLI arg 7 @ fatal/magick-cli.c/ProcessCommandOptions/428.**

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by fmw42** [comment]
This seems to be fixed in IM 7.1.0.10 beta. Thanks.
