### ISSUE TITLE
Improve handling of font NAMES

### ISSUE THREAD

**Issue by rubyFeedback** [ImageMagick/ImageMagick#4313]
### Is your feature request related to a problem? Please describe.

A

### Describe the solution you'd like

B

### Describe alternatives you've considered

C

### Additional context

Hey guys,

Sorry for skipping the above templates but the template format is hugely annoying, even more so in browsers such as palemoon - .I can not even resize the damn thing and it's so small ... the usual issue tracker is much bigger. Can't you guys think about free-form untemplated issues? It's so much easier to use the default than this narrowed down go-the-template-gauntlet ... but anyway.

Consider the following commandline:

"convert -size 500x120 xc:lightblue -font Hack -pointsize 72 -tile pattern:checkerboard -annotate +28+68 "Anthony Quinn" output_file.jpg"

ImageMagick says:

"convert: unable to read font `Hack' @ warning/annotate.c/RenderType/971."

But in just about every other application I can use the Hack font (which is installed AND works fine here on my linux box) 
as-is. Why does it not work via ImageMagick?

The font is here:

/usr/share/fonts/TTF/Hack-Regular.ttf

So I replaced it via:

"convert -size 500x120 xc:lightblue -font Hack-Regular -pointsize 72 -tile pattern:checkerboard -annotate +28+68 "Anthony Quinn" output_file.jpg"

And now it works. Ok, so we have to be more specific and I can understand it.

BUT!

When I use e. g. libreoffice I can simply use "Hack", and then style it differently, e. g. bold or italic.

I understand if imagemagick does not behave the same, as it is not an office suite like libreoffice,
but isn't it more convenient if a simple string such as "Hack" would work as-is? Internally perhaps
imagemagick could try to guess which font may be wanted e. g. append assume -Regular or 
something like that. (It's not just LibreOffice though - KDE apps have no problem with that
either. For instance in KDE Konsole I could use "Hack 18pt" as-is. Might be interesting if
imagemagick could support the very same string.)

Anyway it's not a really important issue - I auto-generate the above string via ruby anyway
so I can code to replace the name "Hack" via the one that ImageMagick expects. But if 
someone ever wants to reconsider how imagemagick behaves here, then it would be 
convenient if we could get away just using "Hack" as-is, rather than "Hack-Regular".

This is not just about the font Hack by the way, but other fonts did not work either
such as "candice", so I have no idea whether it was even installed, or imagemagick
just could not find it. The first is ok and not the fault of imagemagick but the second
is annoying, because the error message kind of indicates that the font were not
installed, which is not correct in regards to the font Hack. So perhaps the issue is
more about the error messages. They always are so short in C/C++ based
applications ... I got so used to super-verbose and helpful error messages from
ruby and python applications! The build system meson even links in github
discussions aka github issues from the commandline. :D

**Comment by rubyFeedback** [comment]
Yikes, wrong formatting in my own comment above ... unfortunately palemoon no longer works with github due to javascript-related changes (I really need to switch eventually ...)

**Comment by fmw42** [comment]
What is your IM version and platform/OS?

What do you have in your type.xml file?  That is what do you get from: 

`convert -list font`

Is that font family there? If so, what is the name of the font there?

If you do not have the font in your type.xml file, then you can always use the full path to the font. Also if on Unix-like systems (Linux, Mac OSX, Windows 10 Unix), you can use https://legacy.imagemagick.org/Usage/scripts/imagick_type_gen to find your fonts and put them into the type.xml file.
