### ISSUE TITLE
“magick identify” reports jpeg size wrong [ignores the .jpeg rotation]

### ISSUE THREAD

**Issue by GeneThomas** [ImageMagick/ImageMagick#4314]
### ImageMagick version

7.1.0-4

### Operating system

Windows

### Operating system, version and so on

 Microsoft Windows [Version 10.0.19043.1237]

### Description

"magick identify" reports that the attached image is 960x720, not 720x960.

### Steps to Reproduce
 
magick identify IMG_0392.JPG

>IMG_0392.JPG JPEG 960x720 960x720+0+0 8-bit sRGB 308580B 0.000u 0:00.001

Looking at the image or getting the details in File Explorer shows that the image is 720x960, not 960x720

### Images

![IMG_0392](https://user-images.githubusercontent.com/514360/135812714-a4ee09af-7479-4117-a679-9350f80196be.JPG)

**Comment by snibgo** [comment]
IM won't rotate the image unless you explicitly rotate it or use "-auto-orient". Those can't be use in "magick identify". You can use it in simple "magick":
```
magick IMG_0392.JPG -auto-orient info:
```

**Comment by GeneThomas** [comment]
-auto-orient should be the default behaviour as the results are correct. In "magick identifiy" too. :o)

**Comment by urban-warrior** [comment]
We'll add support for the `auto-orient` option to the `identify` command within a day or two.
