### ISSUE TITLE
Image::Magick build problems w/ Strawberry Perl

### ISSUE THREAD

**Issue by sciurius** [ImageMagick/ImageMagick#4322]
### ImageMagick version

7.1.0-9

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

Strawberry Perl 5.32.2.

Building the perl module Image::Magick from CPAN fails since it cannot find the binaries convert and/or identify.

### Steps to Reproduce

Install ImageMagick 7.1.0-9 (e.g. ImageMagick-7.1.0-9-Q8-x64-dll.exe).

From powershell, type `cpan Image::Magick`.

[Image-Magick-7.0.11-1-build.log.txt](https://github.com/ImageMagick/ImageMagick/files/7292669/Image-Magick-7.0.11-1-build.log.txt)

Suggested solution:
* In Makefile.PL.in, try `magick identify -list Configure` before trying `identify` and/or `convert`.
* In the helpful message, change step 3 to
````
# 3) During installation select that you want to install ImageMagick's
#    development files (libraries+headers) and legacy utilities.
````

**Comment by urban-warrior** [comment]
Thanks for the suggestions.  We changed `identify` to `magick identify`.  No legacy utilities are needed.  We updated CPAN, however, it may take 48 hours for the update to clone itself worldwide.
