### ISSUE TITLE
  Software no response

### ISSUE THREAD

**Issue by okfirelee** [ImageMagick/ImageMagick#433]
convert 51-5m.gif -coalesce -gravity SouthEast -geometry +2+2 null: five1.png -layers composite -layers optimize 51-5m.gif

http://ohwfxc8wt.bkt.clouddn.com/51-5m.gif
http://ohwfxc8wt.bkt.clouddn.com/five1.png

The software is not responding, the system is dead

**Comment by okfirelee** [comment]
I need to GIF plus watermark, but some problems.

**Comment by fmw42** [comment]
Try this. It works for me on IM 6.9.8.3 Q16 Mac OSX. It takes a little time but does finish.

`convert 51-5m.gif -coalesce null: five1.png -gravity SouthEast -geometry +2+2 -layers composite -layers optimize 51-5m.gif`

**Comment by okfirelee** [comment]
new err : convert: UnrecognizedLayerType `composite'.

**Comment by okfirelee** [comment]
@fmw42 Thanks answer. Further testing with software version with server CPU and mem.

**Comment by okfirelee** [comment]
convert: missing Null Image List Separator layers Composite @ error/mogrify.c/MogrifyImageList/8412.

**Comment by okfirelee** [comment]
The latest version of the operating results
