### ISSUE TITLE
About memory and CPU

### ISSUE THREAD

**Issue by okfirelee** [ImageMagick/ImageMagick#434]
Is it necessary to restrict memory and CPU on the command line parameters on the normally configured server.
If there are no restrictions on the parameters will not cause errors ?

cmd
`convert 51-5m.gif -coalesce -gravity SouthEast -geometry +2+2 null: five1.png -layers composite -layers optimize 51-5m.gif`

**Comment by dlemstra** [comment]
I don't understand what you are trying to ask?

**Comment by mikayla-grace** [comment]
Read https://www.imagemagick.org/script/security-policy.php.  The security policy can set reasonable resource limits which enables you to run commands without worrying about denial-of-service problems from excessive resource requests.  You might also want to review Large Image Support @ https://www.imagemagick.org/script/architecture.php#tera-pixel.
