### ISSUE TITLE
No such file or directory @ error/constitute.c/ReadImage/583

### ISSUE THREAD

**Issue by yegor256** [ImageMagick/ImageMagick#435]
I'm getting this exception when trying to open an image from blob:

```
No such file or directory @ error/constitute.c/ReadImage/583
```

What this might be? I installed `libmagickwand-dev` and `imagemagick` on Ubuntu 14.04.

**Comment by dlemstra** [comment]
What is the type of the image that you are trying to read? It looks like you are missing a delegate. When you are trying to read a PDF file you will need to install Ghostscript.

**Comment by dlemstra** [comment]
@yegor256 Is your issue solved?

**Comment by yegor256** [comment]
@dlemstra yes, the problem was with the file extension. My file `picture` didn't have any extension. When I renamed it to `picture.gif` everything started to work just fine.
