### ISSUE TITLE
sRGB images are written to PNG without an sRGB chunk, and `identify -verbose` does not make that apparent

### ISSUE THREAD

**Issue by sboukortt** [ImageMagick/ImageMagick#4375]
### ImageMagick version

7.0.10-11

### Operating system

Windows

### Operating system, version and so on

Windows 10 20H2, MINGW64 (MSYS2), ImageMagick 7.0.10-11 Q16 x86_64 2021-07-24

### Description

For sRGB images, ImageMagick does not seem to include an sRGB chunk in the PNG files that it creates. It does include the [“fallback” cHRM and gAMA chunks](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#:~:text=An%20application%20that%20writes%20the%20sRGB%20chunk%20should%20also%20write%20a%20gAMA%20chunk%20(and%20perhaps%20a%20cHRM%20chunk)%20for%20compatibility%20with%20applications%20that%20do%20not%20use%20the%20sRGB%20chunk.), which however makes such images look different since the sRGB transfer function is not exactly a gamma curve and gAMA=45455 is only an approximation.

Attached are four images: one with no color space chunk at all, one with just an sRGB chunk, one with sRGB + gAMA/cHRM (which should look identical to the one with just the sRGB chunk since sRGB takes precedence), and one with just gAMA/cHRM (which should look slightly different). Google Chrome indeed displays the first three identically, and the fourth one with slightly darker shadows. Their chunks can be verified with `pngcheck -v` or with [TweakPNG](http://entropymine.com/jason/tweakpng/).

But when running `convert input.png output.png` on them, they all end up with gAMA/cHRM and no sRGB chunk. A fact that `identify -verbose` does not make clear at all since it nevertheless says:

```
png:sRGB: intent=0 (Perceptual Intent)
```

### Steps to Reproduce

The `identify -verbose` issue:

`identify -verbose images/image-sRGB.png` and `identify -verbose images/image-gAMA-cHRM.png` display apparently identical pixel value statistics and image properties, and yet those two images look different (as they should) when opened in Chrome. `pngcheck -v` displays their actual chunks.

----

The `convert` issue:

After running `mkdir -p output; parallel convert '{}' output/'{/}' ::: images/*.png`, the output images all end up with a gAMA and cHRM chunks but no sRGB chunk. If the input images had one, it is lost, and thus the image is displayed differently by color-managed viewers that take the gAMA chunk into account.

This also affects images created with e.g. `convert -size 64x64 'xc:red' red.png`.

### Images

[images.zip](https://github.com/ImageMagick/ImageMagick/files/7354809/images.zip)

**Comment by urban-warrior** [comment]
Try this command:
```
convert -size 64x64 'xc:red' -profile sRGB.icc red.png
```

**Comment by sboukortt** [comment]
Thank you, that is indeed a possible workaround, but I personally think that nevertheless ImageMagick should not silently drop sRGB chunks or mislead about their presence.

**Comment by sboukortt** [comment]
Yes, that is my point — ImageMagick includes chunks that say otherwise (gAMA, cHRM). The [sRGB chunk](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.sRGB) would take precedence and restore interpretation as sRGB without being as large as the sRGB ICC profile.

**Comment by thebombzen** [comment]
This is still an issue in ImageMagick. Here's my version dump:
```
$ magick convert -version
Version: ImageMagick 7.1.0-52 Q16-HDRI x86_64 20549 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fontconfig freetype heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zip zlib
Compiler: gcc (12.2)
```

**Comment by ValZapod** [comment]
can be fixed by https://github.com/ImageMagick/ImageMagick/pull/5824

**Comment by ValZapod** [comment]
Fixed, only a fix for SVG to PNG that violates documentation is needed. Will open a new issue.

As for the last argument here is fallback for PQ BT.2020 ICC profile. https://www.w3.org/TR/png-hdr-pq/

As you can see it specifies fallback gAMA, but PQ cannot be approximated by any gAMA, **not even close**. And also there is this bug in png library. https://github.com/glennrp/libpng/issues/309

**Comment by Traneptora** [comment]
FWIW, you can reproduce this like so:

```
leo@gauss ~ :) $ magick convert rose: -colorspace sRGB rose.png
leo@gauss ~ :) $ umbrielpng rose.png
PNG signature found: rose.png
Chunk: IHDR, Size: 25, Offset: 8, CRC32: 1aebf8e4
Chunk: cHRM, Size: 44, Offset: 33, CRC32: 9cba513c
Chunk: bKGD, Size: 18, Offset: 77, CRC32: a0bda793
Chunk: IDAT, Size: 6754, Offset: 95, CRC32: 113ce85f
Chunk: tEXt, Size: 49, Offset: 6849, CRC32: 81d010af
Chunk: tEXt, Size: 49, Offset: 6898, CRC32: f08da813
Chunk: tEXt, Size: 52, Offset: 6947, CRC32: a79889cc
Chunk: IEND, Size: 12, Offset: 6999, CRC32: ae426082
Size: 70x46, Color: 8-bit RGB
cHRM matches sRGB space
leo@gauss ~ :) $ magick convert -version
Version: ImageMagick 7.1.1-24 Q16-HDRI x86_64 21856 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zip zlib zstd
Compiler: gcc (13.2)
```

Explicitly requesting sRGB color space should produce an sRGB chunk. Untagged files default to sRGB, but this file isn't untagged, because it writes cHRM. If the goal is to write sRGB it should just write an `sRGB` chunk.
