### ISSUE TITLE
A few uninitialized value use bugs in coders

### ISSUE THREAD

**Issue by xiaobaozidi** [ImageMagick/ImageMagick#4379]
### ImageMagick version

latest git version 7eba68fd23e68f48911291

### Operating system

Linux

### Operating system, version and so on

ubuntu-18.04

### Description

Hi maintainers,
These issues are in:

1.coders/pdf.c: 470
```
470   if (image_info->density != (char *) NULL)
 471     {
 472       flags=ParseGeometry(image_info->density,&geometry_info);
 473       image->resolution.x=geometry_info.rho;
 474       image->resolution.y=geometry_info.sigma;
 475       if ((flags & SigmaValue) == 0)
 476         image->resolution.y=image->resolution.x;
```

2. oders/pdf.c:1692

```
1692     if ((resolution.x == 0.0) || (resolution.y == 0.0))
1693       {
1694         flags=ParseGeometry(PSDensityGeometry,&geometry_info);
1695         resolution.x=geometry_info.rho;
1696         resolution.y=geometry_info.sigma;
1697         if ((flags & SigmaValue) == 0)
1698           resolution.y=resolution.x;
1699       }
1700     if (image_info->density != (char *) NULL)
1701       {
1702         flags=ParseGeometry(image_info->density,&geometry_info);
1703         resolution.x=geometry_info.rho;
1704         resolution.y=geometry_info.sigma;
1705         if ((flags & SigmaValue) == 0)
1706           resolution.y=resolution.x;
1707       }

```

3.coders/svg.c:3702:116573:      GeometryInfo

4.coders/emf.c:680:20276:  GeometryInfo

5.coders/pcl.c:230:8357:      GeometryInfo

6.coders/djvu.c:619:20673:            GeometryInfo

7.coders/jbig.c:529:17319:            GeometryInfo

8.coders/txt.c:216:7937:      GeometryInfo

9. coders/dpx.c:1473:46955:  GeometryInfo

10.coders/msl.c:8001:278072:  GeometryInfo

11.coders/ps.c:569:18644:  GeometryInfo

12. coders/ps.c:1390:47241:  GeometryInfo

13.coders/ps2.c:394:14638:  GeometryInfo

14. coders/xps.c:148:5856:  GeometryInfo

15.coders/yuv.c:156:6139:      GeometryInfo

16. coders/yuv.c:656:23557:      GeometryInfo

17. coders/pcd.c:970:31560:  GeometryInfo

18. coders/jpeg.c:2609:83340:      GeometryInfo

19. coders/ps3.c:832:27607:  GeometryInfo

I found it based on my tools.

These issues are similar to the issue:https://github.com/ImageMagick/ImageMagick/issues/1522:

```
if (image_info->density != (char *) NULL)
    {Credit
      GeometryInfo
        geometry_info;

      flags=ParseGeometry(image_info->density,&geometry_info);
      image->resolution.x=geometry_info.rho;
      image->resolution.y=geometry_info.sigma;
      if ((flags & SigmaValue) == 0)
        image->resolution.y=image->resolution.x;
    }
```
proposal patch:

```
-          image->resolution.x=geometry_info.rho;
-          image->resolution.y=geometry_info.sigma;
-          if ((flags & SigmaValue) == 0)
-            image->resolution.y=image->resolution.x;
+          if ((flags & RhoValue) != 0)
+            image->resolution.x=geometry_info.rho;
+          image->resolution.y=image->resolution.x;
+          if ((flags & SigmaValue) != 0)
+            image->resolution.y=geometry_info.sigma;

```
Thank you for the review. I appreciate your time

Acknowledged for the report:
Andrew Bao

### Steps to Reproduce

As described

**Comment by urban-warrior** [comment]
Can you show us a trace of the uninitialized value? geometry.c/ParseGeometry()/884 initializes the geometry_info structure. In theory, the .rho & .sigma member should always be initialized to zero unless overridden. Can you post a command-line where an uninitialized value is generated?
