### ISSUE TITLE
Converting to Grayscale behaves differently based on OS

### ISSUE THREAD

**Issue by SARAN-thala** [ImageMagick/ImageMagick#438]
[Mini Magick Issue Link] (https://github.com/minimagick/minimagick/issues/411)

_**Mini Magick Version : 3.8.0**_
_**Ruby Version : 2.3.3**_

```
require 'mini_magick'

image = MiniMagick::Image.open('https://cdn-images-1.medium.com/max/1600/1*eP0V-xfRWfW3QHJhALJ5RA.jpeg')
image.colorspace 'gray'
image.write('output.jpg')
```
I ran the above code in Mac OSX and Ubuntu 14.04 but the ouput seems to different for different operating systems. In Ubuntu i am getting a more darkened image.

(Attached both the output images (Mac and Ubuntu))

**Mac OSX output Image**
![mac](https://cloud.githubusercontent.com/assets/15261261/25226987/81568078-25e4-11e7-82ed-ae959e8a8e7d.jpeg)

**Ubuntu Output Image**
![ubuntu](https://cloud.githubusercontent.com/assets/15261261/25227009/9769174a-25e4-11e7-96f1-38d0c3d318f2.jpg)

**Comment by dlemstra** [comment]
What is the version of ImageMagick on both systems?

**Comment by SARAN-thala** [comment]
In Ubuntu
`Version: ImageMagick 6.7.7-10 2017-03-14 Q16 http://www.imagemagick.org`

In Mac OSX
`Version: ImageMagick 7.0.5-4 Q16 x86_64 2017-03-25 http://www.imagemagick.org`

**Comment by fmw42** [comment]
That is to be expected. Your older version of Imagemagick had linear grayscale, but the current version has nonlinear grayscale.  The transition started during IM 6.7 and was fully complete after 6.8. See http://www.imagemagick.org/discourse-server/viewtopic.php?f=4&t=21269.

Try adding -set colorspace RGB to one or the other to get similar results.

**Comment by SARAN-thala** [comment]
Thanks for your information. Now, am able to get same image in both OS.

In Mac OSX, I ran the below code.
```
require 'mini_magick'

image = MiniMagick::Image.open('https://cdn-images-1.medium.com/max/1600/1*eP0V-xfRWfW3QHJhALJ5RA.jpeg')
image.colorspace 'gray'
image.write('output.jpg')
```

**Mac OS output image:**
![macos](https://cloud.githubusercontent.com/assets/15261261/25275776/96617a42-26b4-11e7-8d6a-1a669aadb4d9.jpeg)


In Ubuntu, I ran the below code.
```
require 'mini_magick'

image = MiniMagick::Image.open('https://cdn-images-1.medium.com/max/1600/1*eP0V-xfRWfW3QHJhALJ5RA.jpeg')
image.colorspace 'gray'
image.colorspace 'sRGB'
image.write('output.jpg')
```
**Ubuntu Trusty (14.04) output image:**
![ubuntu](https://cloud.githubusercontent.com/assets/15261261/25277068/d6b08326-26ba-11e7-9695-ae23c90c4913.jpg)

**Comment by SARAN-thala** [comment]
I'm closing this issue
