### ISSUE TITLE
.avif not converted, but just copies .jpg

### ISSUE THREAD

**Issue by kkmuffme** [ImageMagick/ImageMagick#4380]
### ImageMagick version

7.1.0

### Operating system

Linux

### Operating system, version and so on

Centos 8

### Description

It does not actually create the .avif, but just copies it as jpeg and changes the file extension

I have Imagemagick 7.1, libaom 3.1.1 and libheif 1.7.0 (which is the version that added avif support):

```
convert --version
Version: ImageMagick 7.1.0-8 Q16-HDRI x86_64 2021-09-18 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): bzlib cairo djvu fontconfig freetype gslib gvc heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib
Compiler: gcc (8.4)

dnf list installed | grep libaom
libaom.x86_64                                 3.1.1-1.el8                               @epel

dnf list installed | grep libheif
libheif.x86_64                                1.7.0-2.el8                               @rpmfusion-free-updates
```

It seems there are other people with this issue (https://github.com/ImageMagick/ImageMagick/issues/1432#issuecomment-813528513) who just commented on a closed ticket, so I wanted to bring this to attention again.

### Steps to Reproduce

```
convert -verbose a.jpg d.avif
a.jpg JPEG 900x900 900x900+0+0 8-bit sRGB 16389B 0.000u 0:00.008
a.jpg=>d.avif JPEG 900x900 900x900+0+0 8-bit sRGB 15507B 0.030u 0:00.022
```

**Comment by dlemstra** [comment]
This is happening because we check if the heic code has support for encoding with the `heif_compression_AV1` format. When this is not supported we will disable the `.avif` encoder. And when an encoder is not supported the image is written in the same format as the input format.

**Comment by dlemstra** [comment]
This looks like an issue with how ImageMagick or libheif is build. We ask the libheif library if it supports reading/writing `heif_compression_AV1` and it returns false for writing. This should also be visble in `magick -list format`

**Comment by fmw42** [comment]
Does 

`magick -list format`

show rw or just r in the line for avif?

 For example on my Mac OSX with Imagemagick 7.1.0-10 Q16-HDRI

AVIF* HEIC      **### rw+**   AV1 Image File Format (1.12.0)

**Comment by fmw42** [comment]
It is still possible that Imagemagick code was not fully implemented or buggy and/or some changes to libheif needed changes in Imagemagick code. I suggest it would not hurt to try to upgrade. What do you have to lose?

**Comment by MaluNoPeleke** [comment]
Even with using libheif 1.12.0 I still don't have writing support in ImageMagick for AVIF:

> AVIF* HEIC      r--   AV1 Image File Format (1.12.0)

Why is that?

**Comment by fmw42** [comment]
I will leave that to one of the IM developers. I am at a loss to know what may be the issue. Perhaps libheif does not yet support writing that format???

**Comment by regs01** [comment]
AVIF can't work on Windows because of HEIC licensing issues as well?

though `magick -list format` shows, but it's still outputting same as input
```
AVIF* HEIC      rw+   AV1 Image File Format (1.12.0)
HEIC* HEIC      r--   High Efficiency Image Format (1.12.0)
```

**Comment by dlemstra** [comment]
The reason that you don't have avif support @MaluNoPeleke is probably because libheif is not compiled with `aom` support that is required for `avif` support.

And on Windows this does work @regs01:
```console
I:\>magick logo: logo.avif

I:\>identify logo.avif
logo.avif AVIF 640x480 640x480+0+0 8-bit sRGB 0.000u 0:00.00

**Comment by MaluNoPeleke** [comment]
I still have the problem and don't know how to solve it:

> magick -verbose content/asc04672_dxo.jpg content/asc04672_dxo.jpg.avif
> content/asc04672_dxo.jpg JPEG 2048x1365 2048x1365+0+0 8-bit sRGB 513478B 0.160u 0:00.191
> content/asc04672_dxo.jpg=>content/asc04672_dxo.jpg.avif JPEG 2048x1365 2048x1365+0+0 8-bit sRGB 97608B 18.820u 0:08.645

> magick -list format | grep -i HEIC
>      AVIF* HEIC      rw+   AV1 Image File Format (1.12.0)
>      HEIC* HEIC      rw+   High Efficiency Image Format (1.12.0)
>      HEIF* HEIC      rw+   High Efficiency Image Format (1.12.0)
> 
> magick -version
> Version: ImageMagick 7.1.0-10 Q16-HDRI x86_64 2021-10-05 https://imagemagick.org
> Copyright: (C) 1999-2021 ImageMagick Studio LLC
> License: https://imagemagick.org/script/license.php
> Features: Cipher DPC HDRI Modules OpenMP(4.5) 
> Delegates (built-in): bzlib cairo djvu fontconfig freetype gslib gvc heic jbig jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf xml zlib
> Compiler: gcc (8.3)
