### ISSUE TITLE
IM hardcodes `$HOME/.config`

### ISSUE THREAD

**Issue by spudowiar** [ImageMagick/ImageMagick#44]
In [`MagickCore/opencl.c`](../blob/master/MagickCore/opencl.c), [`MagickCore/configure.c`](../blob/master/MagickCore/configure.c) and [`MagickCore/module.c`](../blob/master/MagickCore/opencl.c), `$HOME/.config` is hardcoded. Instead, it should check for `$XDG_CONFIG_HOME` and then use `$HOME/.config` if not set. Also, the use in [`MagickCore/opencl.c`](../blob/master/MagickCore/opencl.c) appears to be for caching purposes only and should use `$XDG_CACHE_HOME` or `$HOME/.cache` instead.

>[`$XDG_CONFIG_HOME` defines the base directory relative to which user specific configuration files should be stored. If `$XDG_CONFIG_HOME` is either not set or empty, a default equal to `$HOME/.config` should be used. ](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by urban-warrior** [comment]
Try this:

export $MAGICK_CONFIGURE_PATH=$XDG_CONFIG_HOME
convert ...

**Comment by spudowiar** [comment]
haven't tried but also need `$MAGICK_OPENCL_CACHE_DIR`
