### ISSUE TITLE
Could not make in msys2.

### ISSUE THREAD

**Issue by iamsurfing** [ImageMagick/ImageMagick#4424]
### ImageMagick version

7.0.10.59(from git)

### Operating system

Windows

### Operating system, version and so on

win10-21h1 msys2(mingw64) 

### Description

  CCLD     MagickCore/libMagickCore-7.Q16HDRI.la
msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: MagickCore\\.libs\\libMagickCore_7_Q16HDRI_la-nt-base.o: in function `NTInitializeWinsock':
D:\share\msys64\home\user\git\ImageMagick/MagickCore/nt-base.c:1609: undefined reference to `__imp_WSAStartup'
msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\share\msys64\home\user\git\ImageMagick/MagickCore/nt-base.c:1609: undefined reference to `__imp_WSAStartup'
msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: MagickCore\\.libs\\libMagickCore_7_Q16HDRI_la-nt-base.o: in function `NTWindowsTerminus':
\msys64\home\user\git\ImageMagick/MagickCore/nt-base.c:2792: undefined reference to `__imp_WSACleanup'
collect2.exe: error: ld returned 1 exit status

### Steps to Reproduce

./configure;make -j

**Comment by dlemstra** [comment]
It is build on Windows: https://github.com/ImageMagick/ImageMagick/runs/4053728378?check_suite_focus=true. And you can also see that here: https://github.com/ImageMagick/ImageMagick/blob/8a9b07155b7bb6e9c4768b117e9e6fb1c21e0306/.github/workflows/daily.yml#L168.
