### ISSUE TITLE
insufficient image data in file, no images defined

### ISSUE THREAD

**Issue by dorianmariefr** [ImageMagick/ImageMagick#4427]
### ImageMagick version

Version: ImageMagick 7.1.0-8 Q16-HDRI x86_64 2021-09-18 https://imagemagick.org

### Operating system

MacOS

### Operating system, version and so on

big sur, 11.6

### Description

```
convert: insufficient image data in file `/Users/dorianmariefr/Downloads/gwuyl7ykg7gg3lwp0nz4lv8fd8yb.jpeg' @ error/jpeg.c/ReadJPEGImage_/1112.
convert: no images defined `a.jpg' @ error/convert.c/ConvertImageCommand/3322.
```

### Steps to Reproduce

`convert gwuyl7ykg7gg3lwp0nz4lv8fd8yb.jpeg a.jpg`

### Images

https://bashupload.com/oQvl9/ohdC0.jpeg

Opens fine in Chrome but not in Preview:

<img width="715" alt="Screenshot 2021-10-30 at 16 59 28" src="https://user-images.githubusercontent.com/58794487/139538465-20c89a30-4a38-4010-806d-b4938b6ce29c.png">

<img width="332" alt="Screenshot 2021-10-30 at 16 59 34" src="https://user-images.githubusercontent.com/58794487/139538464-7e2e9c1c-efd0-4090-8ecb-0a58eeca3ef5.png">

**Comment by snibgo** [comment]
Your link is bad. bashupload reports error "404 no such file".

But I suspect your JPEG is corrupt. Im reports and error. Do any other programs report errors?

**Comment by dorianmariefr** [comment]
I uploaded it elsewhere https://gofile.io/d/sKQFBo

**Comment by dorianmariefr** [comment]
I don't know any other program

**Comment by snibgo** [comment]
I downloaded your gwuyl7ykg7gg3lwp0nz4lv8fd8yb.jpeg from gofile.io. It has 17 bytes. It is a text file, not a JPEG. The text is "Introuvable (404)".

**Comment by dorianmariefr** [comment]
oh okay sorry
