### ISSUE TITLE
MagickCLAHEImage has double instead of int param

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#4429]
### ImageMagick version

7.0.11-10

### Operating system

Other (enter below)

### Operating system, version and so on

N/A - problem with builds

### Description

MagickCLAHEImage has the parameter `number_bins` defined as being a double, but then [it is just cast to size_t](https://github.com/ImageMagick/ImageMagick/blob/0c660f2ff8899401be4acf0ce539f0441ebc370e/MagickWand/magick-image.c#L1440-L1452):

```
CLAHEImage(wand->images,width,height,(size_t) number_bins,clip_limit,
```

I guess it's a typo? I just found it confusing as I didn't understand the description in the docs.

### Steps to Reproduce

N/A

**Comment by urban-warrior** [comment]
CLAHEImage() requires `size_t` for the `number_bin` parameter.  MagickCLAHEImage() should be declared `size_t` but instead is declared as a `double`.  To change it now would break the ABI-- which we cannot do.  So instead, we accept the `number_bins` parameter as a double then cast it as `size_t` when CLAHEImage() is called.

**Comment by Danack** [comment]
How about adding a [note like this](https://github.com/Danack/ImageMagick/commit/b5656a38fe0905e1ba8a10307d3b4267a70dc28f) so that it shows up on the docs, as currently https://imagemagick.org/api/magick-image.php#MagickCLAHEImage is hard to interpret.
