### ISSUE TITLE
Unexpected result for "convert -composite" with grayscale image 

### ISSUE THREAD

**Issue by printmaps** [ImageMagick/ImageMagick#4432]
### ImageMagick version

ImageMagick 7.1.0-12 Q16-HDRI arm 2021-10-25

### Operating system

MacOS (12.0.1)

### Operating system, version and so on

macOS Monterey (Apple M1 Pro)

### Description

Colors missing after "convert -composite" operation.

### Steps to Reproduce

Script on Ubuntu (ImageMagick 6.9.10-23 Q16 x86_64 20190101) works as expected. Same script on macOS results in image without colors. Merging of large files (10488 x 10488 pixel, 10016 x 10016 pixel).

### Images

Ubuntu (expected result):

![Ubuntu-kreis-tomato-yellow-9812-kreis-848-848-kreis](https://user-images.githubusercontent.com/26689799/139859146-2afbfbc3-83cf-4466-83ba-47014a800438.png)

macOS (unexpected result):

![Monterey-M1-kreis-tomato-yellow-9812-kreis-848-848-kreis](https://user-images.githubusercontent.com/26689799/139859226-4d900f37-46cd-4dae-b682-88b7db4d1ef8.png)

**Comment by fmw42** [comment]
What was your exact command line?

**Comment by printmaps** [comment]
> What was your exact command line?

`convert -composite -gravity center "$DateinameLeinwandBeschriftungGedreht" "$DateinamePlasma" "$DateinameLeinwandPlasma"`

**Comment by fmw42** [comment]
That is incorrect syntax. You must read the input two images before -composite and -gravity center should come after the images and before -composite. So try

`convert "$DateinameLeinwandBeschriftungGedreht" "$DateinamePlasma" -gravity center -composite "$DateinameLeinwandPlasma"`

Also your IM version is rather old. Upgrade if you can.

**Comment by printmaps** [comment]
Same result (Ubuntu OK, macOS with M1 Pro NOK, see images above) with modified command:

`convert "$DateinameLeinwandBeschriftungGedreht" "$DateinamePlasma" -gravity center -composite "$DateinameLeinwandPlasma"`

The IM version for macOS (ImageMagick 7.1.0-12 Q16-HDRI arm 2021-10-25) is for me the newest available version.

**Comment by snibgo** [comment]
As you use IM v7, I suggest you use "magick" instead of "convert".

You don't show your inputs. Perhaps $DateinameLeinwandBeschriftungGedreht is grayscale, which would make the output grayscale. If so then insert "-set colorspace sRGB" after reading the first input.

If that doesn't help, please show sample inputs.

**Comment by printmaps** [comment]
> Perhaps $DateinameLeinwandBeschriftungGedreht is grayscale, which would make the output grayscale.

Good point ... and yes, this input image is grayscale (black & white).

Here are the test results:

1. 'magick' instead of 'convert' -> not working
magick "$DateinameLeinwandBeschriftungGedreht" "$DateinamePlasma" -gravity center -composite "$DateinameLeinwandPlasma"

2. 'black and white image' changed to 'black and blue image' -> working

3. convert: define colorspace (for 'black and white image') -> working
convert "$DateinameLeinwandBeschriftungGedreht" -colorspace sRGB "$DateinamePlasma" -gravity center -composite "$DateinameLeinwandPlasma"

4. magick: define colorspace (for 'black and white image') -> working
magick "$DateinameLeinwandBeschriftungGedreht" -colorspace sRGB "$DateinamePlasma" -gravity center -composite "$DateinameLeinwandPlasma"

I think this issue can be closed. I have changed the title for better search results. Maybe helpful for other IM users facing the same 'unexpected' effect.

Thanks for your support.

**Comment by printmaps** [comment]
Issue solved.
