### ISSUE TITLE
Building ImageMagick-Windows fails with Visual Studio 2017

### ISSUE THREAD

**Issue by cmb69** [ImageMagick/ImageMagick#4441]
### ImageMagick version

7.1.0-13

### Operating system

Windows

### Operating system, version and so on

Windows 10, Visual Studio 2017

### Description

I'm trying to build ImageMagick via ImageMagick-Windows, and that works well with Visual Studio 2019, but fails with Visual Studio 2017 (15.9.40) with a long list of error messages like:
````
  d:\imagemagick-windows\highway\hwy\ops\generic_ops-inl.h(310): error C2938: "
hwy::N_AVX2::TFromD<unknown-type>": Spezialisierung der Aliasvorlage fehlgeschl
agen (Quelldatei wird kompiliert ..\..\jpeg-xl\lib\jxl\modular\encoding\enc_ma.
cc) [D:\ImageMagick-Windows\VisualMagick\jpeg-xl\CORE_jpeg-xl_DynamicMT.vcxproj
]
  d:\imagemagick-windows\highway\hwy\ops\generic_ops-inl.h(310): error C2955: "
hwy::IsSameT" : Für die Verwendung von Klasse Vorlage ist eine Vorlage-Argument
liste erforderlich (Quelldatei wird kompiliert ..\..\jpeg-xl\lib\jxl\modular\en
coding\enc_ma.cc) [D:\ImageMagick-Windows\VisualMagick\jpeg-xl\CORE_jpeg-xl_Dyn
amicMT.vcxproj]
````
If I exclude CORE_highway, CORE_jpeg-xl and IM_MOD_jxl projects from the build, the build succeeds (with several warnings, but that appears to be the same as with VS 2019).

### Steps to Reproduce

Follow the build description in https://github.com/ImageMagick/ImageMagick-Windows#readme. Configuration is shown below (2nd page uses the default paths). Build with VS 2017 fails.

### Images

![Screenshot 2021-11-04 155632](https://user-images.githubusercontent.com/2306138/140337306-8125b99a-54b1-43c3-9190-d65d010ec9fd.gif)

**Comment by dlemstra** [comment]
It seems that an upgrade of the google highway library broke the VS2017 build. Doing another upgrade seems to have fixed it. This will become available in the next release.

**Comment by cmb69** [comment]
I can confirm that https://github.com/ImageMagick/highway/commit/a5b6622c32b01e7c2f5b21fd0d39f24110e8a689 fixes this issue. Thank you for the swift resolution!
