### ISSUE TITLE
32-bpc PBMs are flipped / not color managed when converted

### ISSUE THREAD

**Issue by blue-j** [ImageMagick/ImageMagick#4445]
### ImageMagick version

7.1.0-13

### Operating system

MacOS

### Operating system, version and so on

11.6.1

### Description

Converting PBMs to JPG works as expected with 8bpc, and 16bpc PBMs,  but 32bpc get flipped upside down and have no respect for ICC source profile.

### Steps to Reproduce

magick PDI_Target_AdobeRGB_32bpc.pbm PDI_Target_AdobeRGB_32bpc.jpg

i have tried -auto-orient via mogrify on the JPEG, and as a switch between input and output without joy.

### Images

[PDI_Target_AdobeRGB_32bpc.pbm.zip](https://github.com/ImageMagick/ImageMagick/files/7489775/PDI_Target_AdobeRGB_32bpc.pbm.zip)

**Comment by dlemstra** [comment]
It looks like that your file is saved incorrectly. The rows should be stored in a bottom to top order. And PBM's file don't have a colorspace setting in it. We assume the colorspace is sRGB. It might be an idea to add a define to allow specifying the colorspace but I am not sure if we should.

**Comment by blue-j** [comment]
i'm reporting it as a bug to Adobe.

**Comment by blue-j** [comment]
https://community.adobe.com/t5/photoshop-ecosystem-bugs/32bpc-pbm-files-are-malformed/idi-p/12504614#M29818
