### ISSUE TITLE
GIF (animated) conversation from multiframe TIFF

### ISSUE THREAD

**Issue by Laserlicht** [ImageMagick/ImageMagick#4451]
### ImageMagick version

7.0.10.11-5

### Operating system

Other (enter below)

### Operating system, version and so on

Windows and Linux

### Description

ImageMagick creates incorrect animated GIF file when converting an image batch (from TIFF) with more than 200 frames to a GIF.

Then:
- Linux: If first 200 frames are correct and the others are empty
- Windows: If there are more than 200 frames, the script runs indefinitely

With less than 200 frames, everything is perfect.

### Steps to Reproduce

`convert -delay 2 video.tiff -repage 546x532+-18+0 -set dispose background -coalesce -layers Optimize video.gif`
if TIFF contains more than 200 images.

**Comment by snibgo** [comment]
I can't reproduce the problem.

Perhaps you are running out of memory. How many pixels do you have?

Please share an input tiff that has the problem.

**Comment by Laserlicht** [comment]
Github don't let me upload ZIP-files 🤔
So... here is a link: https://we.tl/t-rtOXHBfuON

Tested with linux (6GB of RAM, 4GB free).

**Comment by snibgo** [comment]
I can download from that website only if I agree they can steal my data. I won't.

**Comment by Laserlicht** [comment]
What possibility do I have to send you the 40MB ZIP? If Github is buggy and external services are undesirable due to privacy?

**Comment by fmw42** [comment]
Consider Dropbox (public folder).

**Comment by Laserlicht** [comment]
Okay, so I dusted off my dropbox account.

https://www.dropbox.com/s/q1yj3ytnvrj9sao/imagemagick_files.zip?dl=0

**Comment by snibgo** [comment]
With IM v7.1.0-4 on Windows 8.1, input video_280_white.tiff, your command works fine for me, using about 1.2 GB memory at the peak.

**Comment by Laserlicht** [comment]
Unfortunately could not reproduce it myself.
