### ISSUE TITLE
Bug in IM 7 displacement mapping

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#4458]
### ImageMagick version

7.1.0-13 Q16-HDRI x86_64 2021-10-29

### Operating system

MacOS

### Operating system, version and so on

OSX Sierra

### Description

7.1.0-13 Q16-HDRI x86_64 2021-10-29 gives a faulty result in one of my scripts. Whereas IM 6.9.12-28 Q16 x86_64 2021-10-29 produces a correct result. I have tracked the issue to differences in the displacement mapping command in the script.

### Steps to Reproduce

Input (totally white image -- sorry):

![X3](https://user-images.githubusercontent.com/13458218/140868361-21a2c660-ec55-4d2f-a64a-a40288bdd099.png)

X mapping:

![X11](https://user-images.githubusercontent.com/13458218/140868387-a0b5f4d0-eeff-4d68-8029-96e27bfbe12f.png)

Y mapping:

![X12](https://user-images.githubusercontent.com/13458218/140868398-b1497b46-cc4e-4ccf-97a4-e9baa2aeba8a.png)

IM 7 (result is white on transparent background):

```
magick X3.png X11.png X12.png -channel rgba -alpha on -virtual-pixel background \
-background none -define compose:args=533.5x205 -compose displace -composite out7.png
```

![out7](https://user-images.githubusercontent.com/13458218/140868464-23a0e157-9681-4973-94ce-56685d439761.png)

Whereas the expected result as produced by IM 6 is (result is white on transparent background):

```
convert X3.png X11.png X12.png -channel rgba -alpha on -virtual-pixel background \
-background none -define compose:args=533.5x205 -compose displace -composite out6.png
```

![out6](https://user-images.githubusercontent.com/13458218/140868533-3e101b6d-f5a5-42d4-bc4e-0d1e433d49a1.png)

### Images

Above images also contained in zip file:

[im7_bug.zip](https://github.com/ImageMagick/ImageMagick/files/7502231/im7_bug.zip)

**Comment by snibgo** [comment]
I am tempted to reply in white text on a white background.

The problem is that in v7, grayscale images have only one channel, as documented in the porting document. The map image needs to have three channels. "-set colorspace sRGB" does this. So:
```
magick grd.png ( X11.png -set colorspace sRGB ) X12.png ...
```

**Comment by fmw42** [comment]
Thanks snibgo,  I had not thought about that issue. Turns out I needed to make all 3 images 3 channel, so by placing -colorspace sRGB after all 3 images.

Sorry about the white image. It was from a client and it was late last night. I was going to replace it this morning with a gray or gradient, but you resolved it before I got to it.
