### ISSUE TITLE
Perl Magick returns Undefined for "orientation" attribute

### ISSUE THREAD

**Issue by scareduck** [ImageMagick/ImageMagick#4476]
### ImageMagick version

6.9.11.27-3

### Operating system

Linux

### Operating system, version and so on

Fedora 34, ImageMagick-6.9.11.27-3

### Description

The "orientation" attribute returns "Undefined", but it isn't if you the CLI (see this discussion: https://github.com/ImageMagick/ImageMagick/discussions/4050).

### Steps to Reproduce

#!/usr/bin/perl
#
# Test Image::Magick orientation. Normally should be

use Image::Magick;
use strict;

my $img = Image::Magick->new;
my $fn = "<path>/img_0068.jpg";

my $status = $img->Read($fn);

die $status if ($status);
my $attr = "orientation";
my @attrs = $img->Get($attr);
print "$attr: ".join(",",@attrs)."\n";

### Images

 #[
![img_0068](https://user-images.githubusercontent.com/30180792/141600068-60eb44cf-03d6-4df7-8219-df10fb0755ec.jpg)
](url)

**Comment by fmw42** [comment]
Orientation is left bottom from identify -verbose in IM `6.9.12.28`

  Orientation: LeftBottom

Use -auto-orient to display properly.

**Comment by scareduck** [comment]
That's great but non-responsive to the bug in the Perl package.

**Comment by urban-warrior** [comment]
Your script returns expected results with the latest releases of ImageMagick 7.1.0-14 and 6.9.12-28: `orientation: LeftBottom`.  Its possible there is a bug in your release of ImageMagick.  Our advice, upgrade.

**Comment by scareduck** [comment]
That in fact appears to have done the trick. Thank you!
