### ISSUE TITLE
ChangeLog x tarball version

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#4479]
### ImageMagick version

7.1.0-14

### Operating system

Linux

### Operating system, version and so on

n/a

### Description

Thanks for the new release.

ChangeLog says it is 7.1.0-15, tarball name says it is 7.1.0-14.

### Steps to Reproduce

download tarball

**Comment by urban-warrior** [comment]
The ChangeLog is wrong.  We'll fix it in the next point release scheduled within the next week or so.

**Comment by pgajdos** [comment]
Thank you!
