### ISSUE TITLE
unexpected hue change in modulate image

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#4484]
### ImageMagick version

7.1.0-13

### Operating system

Linux

### Operating system, version and so on

Debian 11

### Description

In a source image that contains pixels that are close-ish to white, but distinctly blue, those pixels end up being red when processed with modulate without a hue change being asked for.

This happens when running ImageMagick with HDRI support compiled in.

I understand that HDRI mode has some unexpected differences in working than non-HDRI mode, but pixels changing from one hue to another seems wrong.

### Steps to Reproduce

magick -size 256x30 "gradient:rgb(255,0,0)-rgb(128,255,255)" linear_gradient.png

magick -size 256x30 "gradient:rgb(255,0,0)-rgb(128,255,255)" -modulate 188,100,100 -modulate 100,145,100 linear_gradient_with_modulate.png

// explicitly don't touch hue
magick -size 256x30 "gradient:rgb(255,0,0)-rgb(128,255,255)" -modulate 188,100 -modulate 100,145 linear_gradient_with_modulate_hue_not_touched.png

### Images

linear_gradient.png - the bottom part of the image is distinctly blue
![linear_gradient](https://user-images.githubusercontent.com/1505719/141802944-c4a4749d-68ae-419b-aa34-3297f1af7537.png)

linear_gradient_with_modulate.png
![linear_gradient_with_modulate](https://user-images.githubusercontent.com/1505719/141803037-0a700be8-d128-4b0a-9254-288c8dec3ad8.png)
The bottom part of the image is now slightly red.

linear_gradient_with_modulate_hue_not_touched.png
![linear_gradient_with_modulate_hue_not_touched](https://user-images.githubusercontent.com/1505719/141803079-d0e1a75c-99b3-4af5-b3a0-e0e9744e7818.png)

**Comment by snibgo** [comment]
Your first "-modulate 188,100,100" increases the brightness massively, beyond 100%. Insert "-clamp" after this to ensure no pixels are whiter than white.

**Comment by Danack** [comment]
Ok, that's pretty surprising behaviour. I guess there's nothing to be done for ImageMagick 7, but maybe if ImageMagick 8 ever happens, making it safe to use any operation without unexpected hue changes might be one of the design goals.

Do you have a list of operations that can result in pixels being white than white? I guess MagickBrightnessContrastImage and MagickModulateImage are the two obvious ones.

**Comment by snibgo** [comment]
With HDRI, most operations can give RGB values outside of the range 0 to 100% of QuantumRange, or "blacker than black" and "whiter than white". One exception is "-composite", which will clamp values to that range unless we first "-define compose:clamp=off".

This is useful. The concept of "white" applies to display devices (screens and prints), which have a maximum lightness. But the real world doesn't. In the real world, however bright a scene is, it can always be brighter. There is no maximum.

So HDRI is useful when we are trying to reproduce a real-world scene from a photo, or series of photos.

Another complication is that the formulae for HSL don't behave well for "whiter than white". This is why "-clamp" fixes the problem.

Instead, you could do your operation in HCL, which behaves slightly better than HSL:
```
magick ^
  -size 256x250 "gradient:rgb(255,0,0)-rgb(128,255,255)" ^
-set option:modulate:colorspace hcl ^
  -modulate 188,100,100 ^
  -modulate 100,145,100 ^
  linear_gradient_with_modulate.png
```

**Comment by Danack** [comment]
Okay, thanks for the info.

As I said, if ImageMagick 8 ever happens (which I'm guessing might depend on companies stepping up and actually sponsoring the project) then making it so HDRI is safer to use might be a worthy goal imo.
