### ISSUE TITLE
WebP image-hint and emulate-jpeg-size encoding options not working

### ISSUE THREAD

**Issue by VickiBall** [ImageMagick/ImageMagick#4490]
### ImageMagick version

7.1.0-1

### Operating system

Linux

### Operating system, version and so on

Centos 8

### Description

It seems defining `image-hint` and `emulate-jpeg-size` ([WebP Encoding Options page](https://imagemagick.org/script/webp.php)) as a `webp` option doesn't affect on the output file.
I tried to convert different JPEG and PNG files to WebP with the `image-hint` and `emulate-jpeg-size` option set, but when I compare their MD5 checksum, the files are just the same.

### Steps to Reproduce

```
convert image.jpg -define webp:image-hint=picture output-picture.webp
convert image.jpg -define webp:image-hint=graph output-graph.webp
convert image.jpg -define webp:image-hint=photo output-photo.webp

convert image.jpg -define webp:emulate-jpeg-size=true -quality 50 output-picture-2.webp
convert image.jpg -define webp:emulate-jpeg-size=false -quality 50 output-picture-2.webp
```
The output files are all the same.

**Comment by dlemstra** [comment]
Are you testing this with the latest version? And some of these options require at least a specific version of the webp library:

```c
#if WEBP_ENCODER_ABI_VERSION >= 0x0201
  SetBooleanOption(image_info,"webp:emulate-jpeg-size",
    &configure.emulate_jpeg_size);
  SetBooleanOption(image_info,"webp:low-memory",&configure.low_memory);
  SetIntegerOption(image_info,"webp:thread-level",&configure.thread_level);
#endif
```
