### ISSUE TITLE
Alpha Channels in PSDs

### ISSUE THREAD

**Issue by blue-j** [ImageMagick/ImageMagick#4494]
### ImageMagick version

7.1.0-13

### Operating system

MacOS

### Operating system, version and so on

11.6.1

### Description

I am trying to produce all channel images from PSD files.  My test file is an RGB file with 5 alpha channels.  (As has been mentioned many times before, Photoshop is an authoring tool, not a rendering tool, and PSD is their authoring format, so it allows users to store selections in the form of multiple alpha channels (something unexpected in the image processing community, which is accustomed to alpha channel = transparency).  It seems that the IM team is aware and doesn't want to support multiple alphas...?

Nothing I try seems to make a difference regardless.  It **always** applies an alpha channel to the output.  I'm also charged with producing a grayscale rendering of each alpha channel next!

![channels_1_alpha_applied](https://user-images.githubusercontent.com/3990142/142347553-e057e920-5827-438f-8ce3-733eff8b49c0.jpg)
![channels_1_no_alphas](https://user-images.githubusercontent.com/3990142/142347556-7c1bfa6a-bed6-4a7a-96c4-6153873445e9.jpg)
![channels_2_alpha_applied](https://user-images.githubusercontent.com/3990142/142347558-1178aed6-e30d-42fd-9660-29deb3b73402.jpg)
![channels_2_no_alphas](https://user-images.githubusercontent.com/3990142/142347562-b5a73994-a85b-4585-9052-d571f400fd9e.jpg)

![channels_0_alpha_applied](https://user-images.githubusercontent.com/3990142/142347547-175575a0-78c3-410c-92e8-ad9cd472b7db.jpg)
![channels_0_no_alphas](https://user-images.githubusercontent.com/3990142/142347552-e2e93baf-8142-4a22-bb88-1be6c4a29ede.jpg)
t.

### Steps to Reproduce

No matter what I do, including:
   calling out the merged image data with input.psd[0]
   -alpha off
   -alpha dissociate
   -define psd:alpha-unblend=off
   
```
magick input.psd[0] -define psd:alpha-unblend=off -channel RGB -separate channels_%d.jpg
magick input.psd -define psd:alpha-unblend=off -channel RGB -separate channels_%d.jpg
magick input.psd[0] -alpha off -channel RGB -separate channels_%d.jpg
magick input.psd -alpha off -channel RGB -separate channels_%d.jpg
etc
```
And also using `-channel 0,1,2`

have the same results.  It always applies the alpha around the beard.

### Images

Source images - one with 5 alphas that I'm having trouble removing from the pipeline, and one with all alphas removed, which produces the desired output.

[Archive.zip](https://github.com/ImageMagick/ImageMagick/files/7559725/Archive.zip)

**Comment by snibgo** [comment]
IM doesn't support multiple alpha channels from PSD files. It would be good if it did.

IM contains code for many channels, currently a maximum of 32, but has poor support for these extra channels at the CLI.

You show a few outputs. They are JPEGs so they have no alpha. I suppose none of them are what you want, but you don't say explicitly what you do want. Can you show a sample required output?

**Comment by fmw42** [comment]
He is trying to turn off the masking from the alpha channel(s), which shows up as a black border around the beard. 

A simple test shows that 

`magick alpha_test_5.psd -alpha off x.png`

still has the effect of the alpha channel as a black border. It should have been disabled without the black.

![x](https://user-images.githubusercontent.com/13458218/142360140-d92f3a85-dc7e-4d35-94af-3fcad0a9cdc5.png)

I have tried

`magick alpha_test_5.psd -alpha disable xx.png`

But that oddly gives and error:

magick: UnrecognizedAlphaChannelOption '-alpha' 'disable' at CLI arg 2 @ error/operation.c/CLISimpleOperatorImage/1779.


The image should look as follows (from the same image which does not have the PSD alpha channels):

`magick alpha_test_none.psd zz.png`

![zz](https://user-images.githubusercontent.com/13458218/142360802-29e9bf5a-f8da-4a05-8555-fd270c7f9f02.png)

**Comment by blue-j** [comment]
Hi snigbo, always a pleasure.

My first goal is to produce the JPEGs without the black weirdness along the bottom of the beard, except from the source PSD with 5 alphas. I can't seem to find any way to do that!

I don't care that they are JPEGs because the goal is to ignore the alpha channels entirely!

**Comment by blue-j** [comment]
I hasten to add that I have provided samples of the undesired output and the desired output. The names are not showing?  They clarify that they use different source images, which I also have provided.

**Comment by snibgo** [comment]
```
magick -define psd:alpha-unblend=off alpha_test_5.psd -alpha off x.png
```
![x](https://user-images.githubusercontent.com/33812368/142374231-bd71bc53-a3a9-45b1-b808-c42ba5b33b65.jpg)
Is that what you want?

**Comment by blue-j** [comment]
What makes the difference is putting the `-define` switch **BEFORE** the PSD path!  Thanks so much for your support!  : )

J
