### ISSUE TITLE
Invalid colorspace in conversion from grayscale jpeg to pdf

### ISSUE THREAD

**Issue by lucascars** [ImageMagick/ImageMagick#4497]
### ImageMagick version

7.1.0-11+

### Operating system

Linux

### Operating system, version and so on

Slackware 15.0-RC2

### Description

When running the command "convert image.jpg image.pdf" and the source image is a grayscale JPEG, the colorspace in the PDF is set to TrueColor.

This is due to the usage of  "IsImageGray" (it only checks the image->type parameters, where in JPEG it is zero/undefined) when setting the PDF Device. It should be used instead the function "IdentifyImageCoderGray".

Attached proposed patch.
[imagemagick-pdfgray.diff.txt](https://github.com/ImageMagick/ImageMagick/files/7563003/imagemagick-pdfgray.diff.txt)

### Steps to Reproduce

convert testgrayscale.jpg testgrayscale.pdf

### Images

![testgrayscale](https://user-images.githubusercontent.com/94619741/142422088-557cdbb9-e7c7-4ce3-bf40-3ce152ee0019.jpg)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by lucascars** [comment]
Many thanks!
