### ISSUE TITLE
PSD to PNG: No transparency with alpha channel

### ISSUE THREAD

**Issue by luisfdgon** [ImageMagick/ImageMagick#4500]
### ImageMagick version

7.1.0-14

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20 

### Description

Hi there,

I'm facing an issue when converting a PSD to PNG, it gets converted without background transparency even if an alpha channel is present.

I've tested with a couple of examples and this only occurs for a particular condition which is: PSD file has level and curve layers. If I delete those layers then the PNG gets correctly generated with transparency.
I've tried with Ubuntu 18 and 20 systems with a simple "convert testimage.psd testimage.png"

I'm attaching the file so that someone can validate if this is a bug. I guess that if it is, then you'll need also to port it to IM7.

Some additional notes: I also tried in IM6.9.12-22 and behaves the same, but in IM6.9.7-10 the transparency was working fine. 

Thanks in advance!

### Steps to Reproduce

convert testimage.psd testimage.png

### Images

[testimage.psd.zip](https://github.com/ImageMagick/ImageMagick/files/7570487/testimage.psd.zip)

**Comment by urban-warrior** [comment]
What is expected?  We get two images both with green backgrounds.  This is the same results we get with other PSD applications.  We do not have access to Photoshop to compare the results.

**Comment by luisfdgon** [comment]
Hi @urban-warrior , 

I already replied in https://github.com/ImageMagick/ImageMagick6/issues/169

Feel free to close this as it duplicates the other, or, the other way around.

Thanks
