### ISSUE TITLE
Memory leak of ping parameter

### ISSUE THREAD

**Issue by fa1lr4in** [ImageMagick/ImageMagick#4501]
### ImageMagick version

7.1.0-15

### Operating system

Linux

### Operating system, version and so on

Version: ImageMagick 7.1.0-15 Q16-HDRI x86_64 2021-11-14 https://imagemagick.org Copyright: (C) 1999-2021 ImageMagick Studio LLC License: https://imagemagick.org/script/license.php Features: Cipher DPC HDRI OpenMP(5.0)  Delegates (built-in): bzlib fontconfig freetype jbig jng jpeg lcms lzma pangocairo png tiff webp x xml zlib Compiler: gcc (4.2)

### Description

When I execute the following command
`./magick convert -ping ImageMagick/install/share/doc/ImageMagick-7/images/black.png /dev/null
`
It will cause memory leaks.

==114754==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 256 byte(s) in 1 object(s) allocated from:
    #0 0x5d1e17 in posix_memalign (/root/fuzz/target/imagemagick/ImageMagick/install/bin/magick+0x5d1e17)
    #1 0x8a9bfe in AcquireAlignedMemory_POSIX /root/fuzz/target/imagemagick/ImageMagick/MagickCore/memory.c:299:7
    #2 0x8a9bfe in AcquireAlignedMemory /root/fuzz/target/imagemagick/ImageMagick/MagickCore/memory.c:377:10
    #3 0x697e52 in AcquireCacheNexusPixels /root/fuzz/target/imagemagick/ImageMagick/MagickCore/cache.c:4977:37
    #4 0x697e52 in SetPixelCacheNexusPixels /root/fuzz/target/imagemagick/ImageMagick/MagickCore/cache.c:5097:12
    #5 0x691bb5 in QueueAuthenticPixelCacheNexus /root/fuzz/target/imagemagick/ImageMagick/MagickCore/cache.c:4186:10
    #6 0x691699 in GetAuthenticPixelCacheNexus /root/fuzz/target/imagemagick/ImageMagick/MagickCore/cache.c:1344:10
    #7 0x71309c in GetCacheViewAuthenticPixels /root/fuzz/target/imagemagick/ImageMagick/MagickCore/cache-view.c:312:10
    #8 0x71019e in .omp_outlined._debug__.38 /root/fuzz/target/imagemagick/ImageMagick/MagickCore/attribute.c:2060:7
    #9 0x71019e in .omp_outlined..39.3901 /root/fuzz/target/imagemagick/ImageMagick/MagickCore/attribute.c:2047:3
    #10 0x7f666a6f2892 in __kmp_invoke_microtask (/usr/lib/x86_64-linux-gnu/libomp.so.5+0xba892)
    #11 0x7f666a67bdc2  (/usr/lib/x86_64-linux-gnu/libomp.so.5+0x43dc2)

SUMMARY: AddressSanitizer: 256 byte(s) leaked in 1 allocation(s).

The png file is in the official installation directory :
`share/doc/ImageMagick-7/images/black.png`

### Steps to Reproduce

./magick convert -ping black.png /dev/null

When I turn on the asan mode, it will prompt a memory leak,
The black picture below is black.png

### Images

![black](https://user-images.githubusercontent.com/82496001/142632780-331d50cf-0996-4824-9a20-799f6687e3b8.png)

**Comment by urban-warrior** [comment]
Unfortunately, we cannot reproduce the issue.  We checked your command with `valgrind` and `UBsan` and both returned without detecting a memory leak.  We're checking on Fedora and CentOS 8.  We have had false positives in the past on Ubuntu suggesting a compiler chain issue.

**Comment by fa1lr4in** [comment]
Maybe you can add the ASAN option when compiling. Thanks.

**Comment by urban-warrior** [comment]
Here is our build command:
```
CC=/usr/bin/afl-clang-fast CXX=/usr/bin/afl-clang-fast++ CFLAGS="-ggdb -fsanitize=address,undefined -fno-omit-frame-pointer" LDFLAGS="-ggdb -fsanitize=address,undefined -fno-omit-frame-pointer" ./configure --disable-shared --disable-openmp
```

**Comment by fa1lr4in** [comment]
Here is our build command:
`CC=afl-clang-lto CXX=afl-clang-lto++ CFLAGS="-g -fsanitize=address -fno-omit-frame-pointer" CXXFLAGS="-g -fsanitize=address -fno-omit-frame-pointer" LDFLAGS="-g -fsanitize=address -fno-omit-frame-pointer" ./configure --disable-shared`
I hope I can help you!

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by fa1lr4in** [comment]
> Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

I found a new problem:
When I use the following command
`./magick convert -ping -enhance ImageMagick/install/share/doc/ImageMagick-7/images/black.png /dev/null`
The following problem will occur when the above command is executed 100 times (perhaps less than 100 times)

> ==46699==ABORTING
AddressSanitizer:DEADLYSIGNAL
=================================================================
==46702==ERROR: AddressSanitizer: UNKNOWN SIGNAL on unknown address 0x000000000000 (pc 0x000000695ea2 bp 0x7ffefbc07bb0 sp 0x7ffefbc07af0 T0)
    #0 0x695ea2 in SetPixelCacheNexusPixels /root/fuzz/target/imagemagick/ImageMagick/MagickCore/cache.c:5043:3
    #1 0x6a5eaf in GetVirtualPixelCacheNexus /root/fuzz/target/imagemagick/ImageMagick/MagickCore/cache.c:2776:10
    #2 0x6a79e5 in GetVirtualPixelCacheNexus /root/fuzz/target/imagemagick/ImageMagick/MagickCore/cache.c:3079:9
    #3 0x6a8310 in GetVirtualPixelCacheNexus /root/fuzz/target/imagemagick/ImageMagick/MagickCore/cache.c:2932:17
    #4 0x71219a in GetCacheViewVirtualPixels /root/fuzz/target/imagemagick/ImageMagick/MagickCore/cache-view.c:664:10
    #5 0x7fa0c8 in .omp_outlined._debug__.46 /root/fuzz/target/imagemagick/ImageMagick/MagickCore/enhance.c:1932:7
    #6 0x7fa0c8 in .omp_outlined..48 /root/fuzz/target/imagemagick/ImageMagick/MagickCore/enhance.c:1910:3
    #7 0x7f0aba16cf22 in __kmp_invoke_microtask (/usr/lib/x86_64-linux-gnu/libomp.so.5+0xbef22)
    #8 0x7f0aba0f1f88  (/usr/lib/x86_64-linux-gnu/libomp.so.5+0x43f88)
    #9 0x7f0aba0ea328 in __kmp_fork_call (/usr/lib/x86_64-linux-gnu/libomp.so.5+0x3c328)
    #10 0x7f0aba0d7d9b in __kmpc_fork_call (/usr/lib/x86_64-linux-gnu/libomp.so.5+0x29d9b)
    #11 0x7f9297 in EnhanceImage /root/fuzz/target/imagemagick/ImageMagick/MagickCore/enhance.c:1910:3
    #12 0x17d1fc3 in MogrifyImage /root/fuzz/target/imagemagick/ImageMagick/MagickWand/mogrify.c:1580:27
    #13 0x17c302a in MogrifyImages /root/fuzz/target/imagemagick/ImageMagick/MagickWand/mogrify.c:9124:13
    #14 0x16334a0 in ConvertImageCommand /root/fuzz/target/imagemagick/ImageMagick/MagickWand/convert.c:3320:3
    #15 0x17ea3ff in MagickCommandGenesis /root/fuzz/target/imagemagick/ImageMagick/MagickWand/mogrify.c:188:14
    #16 0x604809 in MagickMain /root/fuzz/target/imagemagick/ImageMagick/utilities/magick.c:150:10
    #17 0x604809 in main /root/fuzz/target/imagemagick/ImageMagick/utilities/magick.c:182:10
    #18 0x7f0ab9ac6bf6 in __libc_start_main /build/glibc-S9d2JN/glibc-2.27/csu/../csu/libc-start.c:310
    #19 0x554d89 in _start (/root/fuzz/target/imagemagick/ImageMagick/install/bin/magick+0x554d89)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: UNKNOWN SIGNAL /root/fuzz/target/imagemagick/ImageMagick/MagickCore/cache.c:5043:3 in SetPixelCacheNexusPixels
==46702==ABORTING

I have updated the latest version and used the following build command
`CC=afl-clang-lto CXX=afl-clang-lto++ CFLAGS="-g -fsanitize=address -fno-omit-frame-pointer" CXXFLAGS="-g -fsanitize=address -fno-omit-frame-pointer" LDFLAGS="-g -fsanitize=address -fno-omit-frame-pointer" ./configure --disable-shared`

Thanks.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
