### ISSUE TITLE
SVG to PNG conversion: Warnings and wrong text placement

### ISSUE THREAD

**Issue by jo-kl** [ImageMagick/ImageMagick#4504]
### ImageMagick version

7.1.0-15

### Operating system

Windows

### Operating system, version and so on

Windows 10 Pro, 64-bit, ImageMagick-7.1.0-15-Q16-HDRI-x64-dll.exe

### Description

When using the Windows Build of ImageMagick 7.1.0-15 for converting SVGs containing text to PNGs ImageMagick prints out warnings and the text placement in the resulting PNG file is wrong:
`** (process:1388): WARNING **: 14:58:51.431: Invalid UTF-8 string passed to pango_layout_set_text()
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.
_cairo_win32_scaled_font_ucs4_to_index:GetGlyphIndicesW: Der Vorgang wurde erfolgreich beendet.`

I haven't been able to reproduce the problem with the Linux build of ImageMagick 7.1.0-14 running on Debian.

### Steps to Reproduce

1. Convert the appended SVG image on a Windows machine:
`magick text.svg text.png`

### Images

[text.zip](https://github.com/ImageMagick/ImageMagick/files/7596329/text.zip)

**Comment by dlemstra** [comment]
This issue cannot be reproduced with the latest version of ImageMagick.
