### ISSUE TITLE
Files with same name as IM's options in working directory break the options

### ISSUE THREAD

**Issue by BlackXStar42** [ImageMagick/ImageMagick#4512]
Orignal title was: Parameter of -quality option not recognized as its parameter anymore
This is the original issue report, for the update see https://github.com/ImageMagick/ImageMagick/issues/4512#issuecomment-981089219.

### ImageMagick version

7.1.0-16 Q8 x64 (portable)

### Operating system

Windows

### Operating system, version and so on

7

### Description

When using `-quality` with `mogrify` or `convert`, an error message similar to the following will show up:
```
convert.exe: NoDecodeDelegateForThisImageFormat `' @ error/constitute.c/ReadImage/572.
convert.exe: UnableToOpenBlob '99': No such file or directory @ error/blob.c/OpenBlob/3527.
convert.exe: NoDecodeDelegateForThisImageFormat `' @ error/constitute.c/ReadImage/572.
```

### Steps to Reproduce

```
convert rose: -quality 99 output.jpg
```

**Comment by BlackXStar42** [comment]
Last known working version: 7.1.0-2 Q8 x64 (portable)

**Comment by urban-warrior** [comment]
Your command works fine for us and returns expected results.  Try these commands:

```
magick -version
magick convert rose: -quality 99 output.jpg
```

Do they complete without complaint?

**Comment by BlackXStar42** [comment]
I have pinned down the problem. The issue is when I have a file with the same name as an option in the working directory. For instance, when I have a file named `-quality` in the working directory, I can't use the `-quality` option anymore. A file named `-format` will render IM unable to use the `-format` option etc.

```
C:\>magick -version
Version: ImageMagick 7.1.0-16 Q8 x64 2021-11-21 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC OpenCL
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2019 (192930137)

C:\>magick convert rose: -quality 99 output.jpg

C:\>echo. > -quality

C:\>magick convert rose: -quality 99 output.jpg
convert: NoDecodeDelegateForThisImageFormat `' @ error/constitute.c/ReadImage/572.
convert: UnableToOpenBlob '99': No such file or directory @ error/blob.c/OpenBlob/3527.
convert: NoDecodeDelegateForThisImageFormat `' @ error/constitute.c/ReadImage/572.
```

**Comment by urban-warrior** [comment]
Correct.  Previously we had a issue where someone wanted to read a filename that happened to be the same as a command-line option.  We added a patch to check.  We could add a define to support both behaviors or you can run the command-line in a different path than the file with the name of an option.

**Comment by BlackXStar42** [comment]
Wow, I find that a _bit_ unexpected. This way, users might access files they don't want to touch or might not even be aware of their existence, possibly loading, modifying or changing them, just because they _think_ they are using an option.

Every option could already be made a file name by just prepending it with `./` or `.\` on the respective platform. I really don't see why this change was necessary, which additionaly bears the high risk of breaking some scripts out there. _If_ such a change was necessary, I would have certainly suggested this approach: Add a pseudo-option, which will tell IM to treat its parameter as a file name in place of the parameter. This way, the user had precise control over the new behavior.

**Comment by urban-warrior** [comment]
Your suggestion is problematic because many times users want to use wildcards. e.g. "*".  If they happen to have a file called `-quality` it will read it with the wildcard.  Not reading it would be unexpected behavior.  We need a define, e.g., `-define option:pedantic=true|false` where pedantic means interpret the argument as an option otherwise as a filename, if it exists, otherwise its interpreted as an option.  We'll await your feedback before we implement this feature.  Perhaps you can propose a better method other than `-file`.

**Comment by fmw42** [comment]
@BlackXStar42  Why don't you just rename your files to replace "-" with "_".  Using "-" as the first character of a file is bad in a Unix environment as well as in ImageMagick.  Why do you have leading "-" in filenames? Is there some particular reason that is necessary for you?

**Comment by BlackXStar42** [comment]
> @BlackXStar42 Why don't you just rename your files to replace "-" with "_". Using "-" as the first character of a file is bad in a Unix environment as well as in ImageMagick. Why do you have leading "-" in filenames? Is there some particular reason that is necessary for you?

You are confusing something. I'm not the one who has the files starting with dashes. I'm talking about the change that was _made_ for someone who has such file names.

**Comment by BlackXStar42** [comment]
> Your suggestion is problematic because many times users want to use wildcards. e.g. "*". If they happen to have a file called `-quality` it will read it with the wildcard. Not reading it would be unexpected behavior. We need a define, e.g., `-define registry:option:pedantic=true|false` where pedantic is true means interpret the argument as an option otherwise as an option or filename. If you have a better solution, let us know.

I don't see how my suggestion influences wildcards and why files found by a wildcard were skipped before. It is my understanding that this issue is only about the interpretation of a command line itself. I suggest that there should be no ambiguity between options and file names on a command line (as it was before). I suggest that a dash always commences an option, unless the dash is the first character of a parameter of another option. Everything else is a file name, so is `*`. Of course that wildcard should find _all_ files it matches.

**Comment by fmw42** [comment]
Sorry for the confusion. But you wrote "I have pinned down the problem. The issue is when I have a file with the same name as an option in the working directory."  So where did that file come from?

**Comment by BlackXStar42** [comment]
> Sorry for the confusion. But you wrote "I have pinned down the problem. The issue is when I have a file with the same name as an option in the working directory." So where did that file come from?

Yes, because I _accidentially_ had one, so my script was suddenly broken with the new version of IM. And it is my understanding that making changes to IM that could break existing scripts is highly undesirable.

**Comment by urban-warrior** [comment]
The problem is shell wildcards., e.g. `convert * anim.gif`.  Suppose you have these files: `1 2 -quality`.  The shell will create this command line: `convert 1 2 -quality anim.gif`.   Under your suggestion, if I have I understand correctly, an exception is thrown-- which is not expected behavior.  The only solution we can think of is for the user to explicitly specify the behavior with a define.

**Comment by urban-warrior** [comment]
We agree, "break existing scripts is highly undesirable."   However, if a breaking change is the result of a bug fix, its okay in limited circumstances.

**Comment by snibgo** [comment]
> Add a pseudo-option which will tell IM to treat its parameter as a file name in place of the option, for instance -file x will make IM treat x as a file name, no matter if it starts with a dash.

>  I additionally suggest, as mentioned above, to add a new option -file x will allow to pass any file starting with a dash on the command line.

IM already has this: the "-read" operation. For example, to read a file named "-quality":
```
magick -read -quality -write info: -exit
```
But this won't cope with expanded wildcards.

**Comment by BlackXStar42** [comment]
> We agree, "break existing scripts is highly undesirable." However, if a breaking change is the result of a bug fix, its okay in limited circumstances.

Well, one could argue whether suddenly allowing files to start with a dash is really a bug fix :grin: As mentioned above, files starting with dashes are never a good idea in the first place.

> The problem is shell wildcards., e.g. `convert * anim.gif`. Suppose you have these files: `1 2 -quality`. The shell will create this command line: `convert 1 2 -quality anim.gif`. Under your suggestion, if I have I understand correctly, an exception is thrown-- which is not expected behavior. The only solution we can think of is for the user to explicitly specify the behavior with a define.

I understand the circumstances now. The wildcards are already expanded before IM even looks at them. While I don't consider this a useful order, not even on Linux, because this way you can actually accidentally "modify" your command line just by having the "right" contents found by a wildcard, I do accept that this is obviously common practice on Linux.

Windows is a different story, though. As there is no such built-in functionality in the command-line processor of Windows, I assume there is some additional preprocessing done inside IM to mimic the behavior of glob on Linux (maybe hidden by some framework). From the point of view of a Windows user, this is all done by the application, so he or she would expect an application to first tokenize the command line and _then_ expand the wildcards, the same way as all built-in tools do it, even as PS does it (probably even on Linux).

So my suggestion certainly looks radical to you:
1) Reconsider the order in which wildcards are expanded. First tokenize the command line, then expand the wildcards as needed, perhaps by calling glob explicitly. I am not certain if shell wildcard expansion can be disabled per application on Linux but it certainly can be on Windows because it is an ancillary feature there anyway.
2) Make a dash always commence an option, unless it is the first character of the parameter of another option of course. Everything else is considered a file name, possibly containing wildcards.
3) Add a new option `-file x` which allows the user to pass any arbitrary file name to IM, even those starting with a dash.

This should not break real-world scripts. It might change the behavior of very awkward scripts which currently make use of dynamically adding options to the command line by using wildcards etc.

I know this is certainly not a small change, maybe it is better suited for the backlog instead.

**Comment by snibgo** [comment]
> 3. Add a new option -file x which allows the user to pass any arbitrary file name to IM, even those starting with a dash.

See my comment above. Would "-file" do anything that "-read" doesn't?

**Comment by fmw42** [comment]
@snibgo.  I do not see -read option at https://imagemagick.org/script/command-line-options.php. Is that some special function you created?

**Comment by snibgo** [comment]
I didn't create "-read". It is documented at https://www.imagemagick.org/script/porting.php . It should also be added to https://imagemagick.org/script/command-line-options.php .

**Comment by fmw42** [comment]
Thanks. I just posted a bug report asking for them to be documented at both places.
