### ISSUE TITLE
Documentation: Missing Options -- -read and -exit

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#4513]
### ImageMagick version

7.1.0-16

### Operating system

MacOS

### Operating system, version and so on

OSX Sierra

### Description

Please add the options:  **-read** and **-exit** to the options page at https://imagemagick.org/script/command-line-options.php.  They are documented in the porting document at https://imagemagick.org/script/porting.php#cli, but missing at the options page.

### Steps to Reproduce

None

### Images

None

**Comment by urban-warrior** [comment]
Done.

**Comment by fmw42** [comment]
Thanks
