### ISSUE TITLE
BMP parser: check on information header size

### ISSUE THREAD

**Issue by I-mpossible** [ImageMagick/ImageMagick#4522]
### ImageMagick version

7.1.0-12

### Operating system

Linux

### Operating system, version and so on

Ubuntu 18.04

### Description

For the attached BMP image, ImageMagick successfully parses it while GraphicsMagick complains:

```
Improper image header ... GraphicsMagick-1.3.36/coders/bmp.c:680
```

The corresponding check in GraphicsMagick is:
```
      if ((bmp_info.size != 12) && (bmp_info.size != 40) && (bmp_info.size != 108)                                                        
          && (bmp_info.size != 124) &&                                                                                                    
          (!(bmp_info.size >= 12 && bmp_info.size <= 64)))                                                                                
        ThrowBMPReaderException(CorruptImageError,ImproperImageHeader,image);
```

I'm wondering if there's a missing check on the information header size. Or would it be good to add a warning if there's an invalid value?

Thanks

### Steps to Reproduce

identify infosize.bmp

### Images

[infosize.zip](https://github.com/ImageMagick/ImageMagick/files/7620364/infosize.zip)

**Comment by dlemstra** [comment]
That check is not entirely correct but we should problably add a check when the size exceeds `124`. Will take a look at this later this week and see how we should handle this.

**Comment by I-mpossible** [comment]
Thanks for your prompt reply! Could you please elaborate on which part is incorrect so that I can report to GraphicsMagick as well and help refine the check?

Thanks

**Comment by dlemstra** [comment]
It's not wrong but they aren't checking for every know header size value. The `(bmp_info.size >= 12 && bmp_info.size <= 64)` check leaves room for incorrect values. But I also don't know if we will be going to add a check for that.
