### ISSUE TITLE
Pango does not work under Windows (CLI & file input) because of UTF-8 warnings

### ISSUE THREAD

**Issue by milekpl** [ImageMagick/ImageMagick#4527]
### ImageMagick version

7.1.0-16

### Operating system

Windows

### Operating system, version and so on

Windows 10 64-bit

### Description

My older script (which used to work with some version 6.x) is now broken, and I have unfortunately lost the old version. There are three bugs overall:

- pango complains "Invalid UTF-8 string passed to pango_layout_set_text()" (even on pure ASCII input and after using chcp 65001)
- when reading from a see code snippet below, it says that I have "negative or zero image size"
- and it says "no images defined" and outputs the filename of the output, which is absurd.

### Steps to Reproduce

1. Save this one-liner as a text file "pr_98": 
`<span font_desc="Charis SIL" size="14">b </span>`
2. Run:
`convert.exe -density 300 -crop -5 +repage pango:@pr_98 a.gif`
3. You get:

`** (process:7708): WARNING **: 19:28:51.860: Invalid UTF-8 string passed to pango_layout_set_text()
convert.exe: negative or zero image size `@pr_98' @ error/image.c/SetImageExtent/2692.
convert.exe: no images defined `a.gif' @ error/convert.c/ConvertImageCommand/3229.`

**Comment by dlemstra** [comment]
I suspect that your `pr_98` text file contains some extra information that breaks the pango coder. I am not able to reproduce your issue. 

And you are getting `no images defined` because your commands are in an incorrect order. ImageMagick 7 is more strict and you should put it in this order:
`magick -density 300 pango:@pr_98 -crop -5 +repage a.gif`

**Comment by milekpl** [comment]
I get the same result on Cygwin and Debian (using 6.9.10-13) with the same set of files, with the exception of the UTF-8 warning. This is why I expect that there is a bug in the Windows build specifically.

After changing the order of parameters, I only got the message about negative or zero image size, under Windows, Cygwin, and Debian. 

And there's absolutely nothing special about my text file. It is 48 bytes, pure ASCII. But I can see that I forgot to escape the code, so here it goes again:
`<span font_desc="Charis SIL" size="14">b </span>`

**Comment by dlemstra** [comment]
Why are you talking about version ` 6.9.10-13` now instead of `7.1.0-16`?

**Comment by milekpl** [comment]
Sorry for not being clear: I just have an install of Debian that has this version, and not the current one. I did not wish to say that I confirmed this on a current version using Debian, because I could not (this is the version I got through apt-get install in my system).

Moreover, it's good to trace the source of the bug to remove a regression.

I would be grateful if you could see whether you get the same problem when you specifically use pango formatting strings.

**Comment by milekpl** [comment]
(And to make it explicit, on Cygwin I use  `7.1.0-16`.

**Comment by milekpl** [comment]
Did some further checks, it turns out that the way Pango works changed, and `size` is no longer expressed in pts but in 1000ths of the pt size, so no wonder I got error messages. Still, the UTF-8 message for a file that contains no UTF-8 is simply wrong. BTW, the same happens even for this example in Windows:
`chcp 65001
magick pango:"a" a.gif `
