### ISSUE TITLE
Unable to read plain encoded PNM files

### ISSUE THREAD

**Issue by ynse01** [ImageMagick/ImageMagick#4546]
### ImageMagick version

7.1.0

### Operating system

Windows

### Operating system, version and so on

Windows 10 21H2

### Description

The specification of the PNM format includes some example images.
[PBM](http://netpbm.sourceforge.net/doc/pbm.html) [PGM](http://netpbm.sourceforge.net/doc/pgm.html) and [PPM](http://netpbm.sourceforge.net/doc/ppm.html).

These images do not load correctly in Magick. 

For your reference I have included these example images below. Please note the PBM image loads correctly !
The images are encoded using the _Plain_ encoding. This is plain text for the entire image. As I'm using Windows, line endings have both \r and \n characters. As this is a text based format, I think any library should handle Windows line endings transparently.

### Steps to Reproduce

Open the images using magick command line.
Error is thrown that image in invalid.

### Images

[Pbm.zip](https://github.com/ImageMagick/ImageMagick/files/7655839/Pbm.zip)

**Comment by urban-warrior** [comment]
```
$ ppmtogif rgb_plain.ppm 
ppmtogif: EOF / read error reading a byte
$ pnmtopng grayscale_plain.pgm
pnmtopng: EOF / read error reading a byte
```

Netpbm utilities are the stewards of the PBM formats.  If these utilities cannot read your plaintext images, you can be certain you are not conforming to the PBM image format standards.

**Comment by ynse01** [comment]
These images might not adhere to the literal specification, but I feel that whitespace in these images is not of significant. 

Whitespace _is_ however significant in Magick's implementation.

I feel a library should be permissive for "user error" on whitespace usage.

**Comment by snibgo** [comment]
The format documentation http://netpbm.sourceforge.net/doc/ppm.html specifies:

> Each sample in the raster has white space before _and after_ it.

(Emphasis mine.)

That isn't true of your rgb_plain.ppm. There is no white space afer the final sample.

If you add white space to the end of the file, IM reads it without complaint.

**Comment by ynse01** [comment]
This sentence talks about samples, being the different components of a pixel. The same section says about the pixel themselves:

>  There is no particular separation of one pixel from another

All in all, I don't consider a missing space at the end of an image a breaking change in loading the image. As the same specification agrees with:

> Programs that read this format should be as lenient as possible, accepting anything that looks remotely like a PPM image.

Just consider a novice user, who tries to create a simple text based image. He or she will easily miss the requirement to add a trailing space after the last pixel. The error message is also not very specific on the exact error in the image, no line numbers or anything.

I think is would be more user friendly to ignore be robust against this mistake and load the image regardless.

**Comment by fmw42** [comment]
ImageMagick tries to keep with conventions and standards. I do not think this will be changed. But I will defer to the developers.

**Comment by urban-warrior** [comment]
If the Netpbm utilities can read an image format and ImageMagick cannot-- that's a bug and we will fix it.  The Netpbm utilities cannot read your images so we are not inclined to take any action.  We tried a few other utilities and they failed as well.  Gimp, however, could read your image.
