### ISSUE TITLE
import -screen -window $(xdotool selectwindow)

### ISSUE THREAD

**Issue by The-Repo-Club** [ImageMagick/ImageMagick#4547]
### ImageMagick version

7.1.0-16

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

import:  `81788943' @ error/import.c/ImportImageCommand/1288.

### Steps to Reproduce

import -screen -window $(xdotool selectwindow)

**Comment by urban-warrior** [comment]
We require the Windows ID in a hex format.  Rather than 8395589, we require 0x801b45 as returned by `xwininfo`.

**Comment by The-Repo-Club** [comment]
thats kind of strange as it works if ran from a script but not if ran in the terminal
