### ISSUE TITLE
Select a font inside a TrueType Collection

### ISSUE THREAD

**Issue by Bytologic** [ImageMagick/ImageMagick#4558]
### Is your feature request related to a problem? Please describe.

While I was working on supporting Japanese fonts I stumbled upon the MS Gothic font, which is a default font in Windows 10. This font is saved, together with its variations MS PGothic and MS UI Gothic, inside a TrueType Collection. With ImageMagick I am only able to use the first font inside the collection, which is MS Gothic. I am unable to use MS PGothic or MS UI Gothic. Of course, this is only an example and it applies to all collections of fonts out there.

### Describe the solution you'd like

I would like a way in Magick++ to select a font inside a collection to use for the rendering of text.

### Describe alternatives you've considered

What I have done to make it work is to unbundle the fonts into their own TrueType Font files, as suggested [here](https://github.com/ImageMagick/ImageMagick/discussions/4540#discussioncomment-1757402). However, if I want to support all fonts coming with an operating system, I'd first have to unpack all the collections and install them separately.

### Additional context

See this discussion for context: https://github.com/ImageMagick/ImageMagick/discussions/4540

**Comment by urban-warrior** [comment]
ImageMagick supports a face index in the font configuration file, `type.xml`, with the `face` element.  We now have support for explicit font collection filenames, e.g.,

```
convert logo: -pointsize 32 -font "@msgothic.ttc[1]" -gravity center -annotate +0+0 "ImageMagick" logo.png
```
where `1` is the font face index.

**Comment by fmw42** [comment]
Why the @?

**Comment by urban-warrior** [comment]
`-font arial` means search for a font matching the name Ariel, whereas, `-font @ariel.ttf` does not search and instead loads the `ariel.ttf` font file from your working directory.  `font @msgothic.ttc[1]' utilizes the second face index in the MS Gothic font collection in your working directory.

**Comment by fmw42** [comment]
But I assume one can still provide an absolute or relative path to the font file or font family with face index

`path_to/ariel.ttf[1]`

correct?

**Comment by urban-warrior** [comment]
Yes, the font path has always been accepted.

**Comment by fmw42** [comment]
Sorry for the confusion. I just wanted to be sure that the @ was not some special character indicating a font family as opposed to a font (file) itself.
