### ISSUE TITLE
identify: UnableToOpenBlob '02.jpg': Permission denied @ error/blob.c/OpenBlob/3527.

### ISSUE THREAD

**Issue by shibababa** [ImageMagick/ImageMagick#4566]
### ImageMagick version

Version: ImageMagick 7.1.0-17 Q8 x64 2021-12-04

### Operating system

Windows

### Operating system, version and so on

10 20H2

### Description

I tried the following code.
`identify -format "%f %[colorspace], " "*.jpg"`

The result.
`identify: UnableToOpenBlob '02.jpg': Permission denied @ error/blob.c/OpenBlob/3527.
01.jpg sRGB, 03.jpg Gray, 05.jpg Gray, 06.jpg Gray, 07.jpg Gray, 08.jpg Gray, 09.jpg Gray, 10.jpg Gray, 11.jpg Gray, 12.jpg Gray, 13.jpg Gray, 14.jpg Gray, 15.jpg Gray, 16.jpg Gray, 17.jpg Gray, 18.jpg Gray, 19.jpg Gray, 20.jpg Gray, 21.jpg Gray, 22.jpg Gray, 23.jpg Gray, 24.jpg Gray, 25.jpg Gray, 26.jpg Gray, 27.jpg Gray, 28.jpg Gray, 29.jpg Gray, 30.jpg Gray, 31.jpg Gray, 32.jpg Gray, 33.jpg Gray, 34.jpg Gray, 35.jpg Gray, 36.jpg Gray, 37.jpg Gray, 38.jpg Gray, 39.jpg Gray, 40.jpg Gray, 41.jpg Gray, 42.jpg Gray, 43.jpg Gray, 44.jpg Gray, 46.jpg Gray, 47.jpg Gray, 48.jpg Gray, 49.jpg Gray, 50.jpg Gray, 51.jpg sRGB,`

I don't have any special security settings for my portable imagemagick or image folders, but I don't understand why access is denied.

I think this is a big bug.
I look forward to an immediate fix.

### postscript
Repeating the same command multiple times will either succeed or fail.

Results if successful
`01.jpg sRGB, 02.jpg sRGB, 03.jpg Gray, 05.jpg Gray, 06.jpg Gray, 07.jpg Gray, 08.jpg Gray, 09.jpg Gray, 10.jpg Gray, 11.jpg Gray, 12.jpg Gray, 13.jpg Gray, 14.jpg Gray, 15.jpg Gray, 16.jpg Gray, 17.jpg Gray, 18.jpg Gray, 19.jpg Gray, 20.jpg Gray, 21.jpg Gray, 22.jpg Gray, 23.jpg Gray, 24.jpg Gray, 25.jpg Gray, 26.jpg Gray, 27.jpg Gray, 28.jpg Gray, 29.jpg Gray, 30.jpg Gray, 31.jpg Gray, 32.jpg Gray, 33.jpg Gray, 34.jpg Gray, 35.jpg Gray, 36.jpg Gray, 37.jpg Gray, 38.jpg Gray, 39.jpg Gray, 40.jpg Gray, 41.jpg Gray, 42.jpg Gray, 43.jpg Gray, 44.jpg Gray, 46.jpg Gray, 47.jpg Gray, 48.jpg Gray, 49.jpg Gray, 50.jpg Gray, 51.jpg sRGB,`

Result in case of failure
`identify: UnableToOpenBlob '10.jpg': Permission denied @ error/blob.c/OpenBlob/3527.
identify: UnableToOpenBlob '11.jpg': Permission denied @ error/blob.c/OpenBlob/3527.
identify: UnableToOpenBlob '12.jpg': Permission denied @ error/blob.c/OpenBlob/3527.
identify: UnableToOpenBlob '12.jpg': Permission denied @ error/blob.c/OpenBlob/3527.
01.jpg sRGB, 02.jpg sRGB, 03.jpg Gray, 05.jpg Gray, 06.jpg Gray, 07.jpg Gray, 08.jpg Gray, 09.jpg Gray, 13.jpg Gray, 14.jpg Gray, 15.jpg Gray, 16.jpg Gray, 17.jpg Gray, 18.jpg Gray, 19.jpg Gray, 20.jpg Gray, 21.jpg Gray, 22.jpg Gray, 23.jpg Gray, 24.jpg Gray, 25.jpg Gray, 26.jpg Gray, 27.jpg Gray, 28.jpg Gray, 29.jpg Gray, 30.jpg Gray, 31.jpg Gray, 32.jpg Gray, 33.jpg Gray, 34.jpg Gray, 35.jpg Gray, 36.jpg Gray, 37.jpg Gray, 38.jpg Gray, 39.jpg Gray, 40.jpg Gray, 41.jpg Gray, 42.jpg Gray, 43.jpg Gray, 44.jpg Gray, 46.jpg Gray, 47.jpg Gray, 48.jpg Gray, 49.jpg Gray, 50.jpg Gray, 51.jpg sRGB,`

The result changes like every time and it is not stable at all.
I have no idea.

### Steps to Reproduce

`identify -format "%f %[colorspace], " "*.jpg"`

**Comment by snibgo** [comment]
IM couldn't open the files.

What else was your computer doing at the same time?

**Comment by shibababa** [comment]
> IM couldn't open the files.
> 
> What else was your computer doing at the same time?

When I closed all windows except the command prompt and ran it about 10 times, no error occurred.

I wasn't doing anything else in particular, but I don't know the exact cause, but as you said, something else may have been the factor.

I will let you know if I find out.
