### ISSUE TITLE
Issue building imagemagick on windows using mingw

### ISSUE THREAD

**Issue by WilliamBehrens** [ImageMagick/ImageMagick#4567]
### ImageMagick version

7.1.0-17

### Operating system

Windows

### Operating system, version and so on

Windows 10 using mingw/msys2

### Description

ImageMagick fails to build when using msys2 on windows giving the error `configure: error: C compiler cannot create executables`

### Steps to Reproduce

See linked ImageMagick6 issue for more details, the steps taken and outcome is the same

https://github.com/ImageMagick/ImageMagick6/issues/171

**Comment by dlemstra** [comment]
We have a successful msys2 build: https://github.com/ImageMagick/ImageMagick/blob/f8c1f138bd746a27b41aee6355a571f7fd89a2cb/.github/workflows/main.yml#L121. Not sure what is missing in your situation.
