### ISSUE TITLE
Metadata issue in rotated PNG file

### ISSUE THREAD

**Issue by philrob42** [ImageMagick/ImageMagick#4590]
### ImageMagick version

7.0.11-13

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

When using the -rotate option on a PNG file, in the example a 45 degree rotation, the output PNG file appears to have invalid metadata making it impossible for a subsequent -crop command to find its center. Observe that the image 3.png and 6.png should be identical, but the actual result is image 3.png is cropped off-center.

### Steps to Reproduce

magick 1.png -rotate 45 2.png
magick 2.png -gravity center -crop 6588x6588+0+0 3.png
magick convert 2.png 4.bmp
magick convert 4.bmp 5.png
magick 5.png -gravity center -crop 6588x6588+0+0 6.png

### Images
Image: 1.png
![1](https://user-images.githubusercontent.com/96162141/146125380-3f698186-8584-4d3f-88b0-6cbd7b401252.png)

Image: 2.png
![2](https://user-images.githubusercontent.com/96162141/146125388-b27da0d7-ce8f-4ae6-afd2-5472b2e416d6.png)

Image 3.png
![3](https://user-images.githubusercontent.com/96162141/146125391-4c528e59-dd12-46fd-a148-5acb0796ec69.png)

Image #4 omitted due to unsupported file type .bmp, but this is output of the third step above.

Image: 5.png
![5](https://user-images.githubusercontent.com/96162141/146125424-4d7cb461-c434-44e4-b07d-b2d79bb2a48f.png)

Image: 6.png
![6](https://user-images.githubusercontent.com/96162141/146125433-1efa8bcf-d65e-4d02-a049-629346443c05.png)

**Comment by snibgo** [comment]
> ... 45 degree rotation, the output PNG file appears to have invalid metadata ...

The metadata is valid and correct, but I suppose not what you want. Use "+repage" to remove the canvas offsets:
```
magick 1.png -rotate 45 +repage 2.png
```
I suggest also using "+repage" afer "-crop".

**Comment by philrob42** [comment]
Thank you @snibgo. That did work. I do wonder why one must do a +repage to reset the virtual canvas metadata as an extra step rather than that be an implicit part of the crop and rotate functions... Would have saved me quite some time in figuring out how to get the pixels I wanted in the crop. As it is, it did not meet my expectations as a  user.

**Comment by snibgo** [comment]
I know what you mean, but the difficulty is that this metadata (page offsets) is sometimes useful. If IM changed to remove this metadata by default, many scripts would break.

Perhaps the documentation at https://imagemagick.org/script/command-line-options.php#rotate should be updated to warn that "+repage" might be useful after "-rotate" to remove the page offsets.
