### ISSUE TITLE
MSVG rendering should report errors instead of failing silently

### ISSUE THREAD

**Issue by toolforger** [ImageMagick/ImageMagick#46]
MSVG rendering is known to be limited (the docs say so), but if MSVG hits a limitation, it should report an error or a warning instead of silently creating a faulty image.

The problem with the faulty image is that people won't know how to fix the problem, IM doesn't tell them. Judging by the number of search engine hits that explain how to fix this problem, I guess this is widespread enough of an issue that fixing it is worth the (possibly considerable) effort.

**Comment by urban-warrior** [comment]
http://www.imagemagick.org/script/formats.php warns "... if neither are available, ImageMagick reverts to its internal SVG renderer."    It's a feature, not a bug :-)

**Comment by toolforger** [comment]
Yes, this is not a bug report, it's a feature request.
I'd like to specify not just the format (SVG), but also the decoder (inkscape), because for my use case, the fallback policy is much less useful than an error message (and appropriate exit code so that IM-using scripts can react properly).

**Comment by urban-warrior** [comment]
We are not inclined to implement this feature request.  We'll give it some more thought and perhaps change our mind.
