### ISSUE TITLE
Saving layered RGB 32-bit per channel floating point TIFF, PSD or EXR

### ISSUE THREAD

**Issue by KeygenLLC** [ImageMagick/ImageMagick#4600]
### ImageMagick version

ImageMagick 7.1.0-17 Q16-HDRI x86_64 2021-12-04

### Operating system

MacOS

### Operating system, version and so on

macOS Mojave 10.14

### Description

I've been trying to save layered files in PSD or TIFF that can be read by Adobe Photoshop or After Effects. Also tried EXR.

I read through #4418 and tried the example code, and some other code for saving layered files, but I'm getting unexpected results.

TIFF will not save layers (which I expected it not to given forum posts). The file is larger than a single file so the data is possibly there but not writing the layers the way Photoshop expects. It does however save the TIFF in proper 32-bit per channel RGB floating point, and the colors are accurate.

With PSD, I can get layers, but it will not save as 32-bit per channel, only 16-bit per channel. The colors are washed out like it's trying to use 32-bit, but 16-bit is all it saves. I tried setting `-depth 16` which forced TIFF into 32-bit mode, but it doesn't work with PSDs. 

I also tried EXR format, but it just saves individual files instead of layers and saves them as half float instead of normal float.

I'm starting off with 3 x 32-bit floating point TIFF files saved from Photoshop. I'm also checking all the files with exiftool.

Here's the code I've tried:
```bash
magick /project/path/*.tif -define quantum:format=floating-point  \( -clone 0--2 -background none -flatten \) -depth 16 -type truecolor layers.psd

magick /project/path/*.tif -define quantum:format=floating-point  \( -clone 0--2 -background none -flatten \) -depth 16 -type truecolor layers.tif

magick /project/path/*.tif -define quantum:format=floating-point  \( -clone 0--2 -background none -flatten \) -depth 16 -type truecolor layers.exr
```
I don't know if this is a bug or if the functionality isn't there. Was hoping ImageMagick could do it because I'm not finding any python libraries that will spit out layered float RGB files that Adobe apps can read.

### Steps to Reproduce

Save multiple 32-bit per channel TIFF files out of Photoshop.

Try to combine with supplied code in CLI.

**Comment by fmw42** [comment]
ImageMagick does not support layered TIFFs only TIFFs with multiple pages. I do not know that EXR will support layers, but I am not an expert on that. However, ImageMagick only supports 16-bit per channel EXR (called "half floating point"). With TIFF, if you need to save as 32-bit pages, then you need to add -define quantum:format=float and -type tricolor. I am not sure what is supported in the way of PSD 32-bit layers or even single channel.

**Comment by KeygenLLC** [comment]
Thanks. PSD will be fine if I can get it to work since Photoshop and After Effects can both read the layers.

I'll try out `-type tricolor` and see if it works.

**Comment by KeygenLLC** [comment]
Got an error:
```bash
magick: unrecognized image type '-type' 'tricolor' at CLI arg 15 @ error/operation.c/CLISettingOptionInfo/1503.
```

**Comment by fmw42** [comment]
adding -type truecolor was for TIFF not PSD

**Comment by fmw42** [comment]
I do not think IM supports 32-bit PSD only 32-bit TIFF (single or multipage).

**Comment by KeygenLLC** [comment]
Well, hopefully they add it in sooner than later.

I'll check out the source code and see how exactly they're tagging the files, because that's the trouble I've been having with trying to do it in Python.
