### ISSUE TITLE
Variable fonts support?

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#4604]
### Is your feature request related to a problem? Please describe.

[Variable fonts](https://v-fonts.com/) seem a nicer solution than having to manage fonts on a system. I tried to use the [OpenSans](https://fonts.google.com/specimen/Open+Sans?vfonly=true) variable font and set some weights:

```
convert -background lightblue -fill blue \
          -font "fonts/OpenSans-VariableFont_wdth,wght.ttf" -pointsize 72 -weight 100 label:Anthony \
          label_OpenSans_weight_100.png

convert -background lightblue -fill blue \
          -font fonts/OpenSans-VariableFont_wdth,wght.ttf -pointsize 72 -weight 400 label:Anthony \
          label_OpenSans_weight_400.png

convert -background lightblue -fill blue \
          -font "fonts/OpenSans-VariableFont_wdth,wght.ttf" -pointsize 72 -weight 600 label:Anthony \
          label_OpenSans_weight_600.png
```

But all of the images came out the same.

### Describe the solution you'd like

Appropriate weight + font style to be selected when a variable font is used, and style settings are set.

### Describe alternatives you've considered

Writing copious notes on how users can install and manage fonts on their system, once I actually understand that myself.

**Comment by urban-warrior** [comment]
ImageMagick supports font rendering with the Freetype delegate library which supports variable fonts.  Post some links here of example Freetype API calls that are responsive to varying weights with a variable font and we will look into adding support for this feature request.

**Comment by hellocatfood** [comment]
I was able to get variable fonts working by passing some arguments to [pango](https://legacy.imagemagick.org/Usage/text/#pango), though I don't know if this presents any issues over using `label`.

```
convert -background lightblue -fill blue \
          -font ".fonts/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf" -pointsize 72 pango:'<span weight="100">Anthony</span>' \
          label_OpenSans_weight_100.png
```
![label_OpenSans_weight_100](https://user-images.githubusercontent.com/151947/162584112-1e93a1c0-7617-405e-b8e3-3c50918ab7c9.png)
```
convert -background lightblue -fill blue \
          -font ".fonts/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf" -pointsize 72 pango:'<span weight="400">Anthony</span>' \
          label_OpenSans_weight_400.png
```
![label_OpenSans_weight_400](https://user-images.githubusercontent.com/151947/162584129-09a5bedd-d426-4920-80f4-654e394e9921.png)
```
convert -background lightblue -fill blue \
          -font ".fonts/Open_Sans/OpenSans-VariableFont_wdth,wght.ttf" -pointsize 72 pango:'<span weight="600">Anthony</span>' \
          label_OpenSans_weight_600.png
```
![label_OpenSans_weight_600](https://user-images.githubusercontent.com/151947/162584165-bb657592-50b9-4fe1-911f-6610d051825b.png)

**Comment by chirsz-ever** [comment]
I meet a related problem: I need to set [the language for the font](https://www.w3.org/TR/css-fonts-3/#language-specific-support).

Maybe the pango script could solve this (`<span lang="...">`), but Pango is not available with the version installed with homebrew on MacOS.

**Comment by fmw42** [comment]
I don't really understand the issue. But can you not add the Pango (Cairo) delegate when you install Imagemagick from Homebrew. It would be a combination install.

**Comment by chirsz-ever** [comment]
Thanks for the advice but I don't understand what is "the Pango (Cairo) delegate". [It seems not work](https://stackoverflow.com/a/55504636).
