### ISSUE TITLE
memory leak in ReadOnePNGImage 

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#461]
on ImageMagick 7.0.5-5

The ReadOnePNGImage function in png.c:3517 allows attackers to cause a denial of service (memory leak) via a crafted file.

#convert $FILE out.bmp
=================================================================

Direct leak of 152 byte(s) in 1 object(s) allocated from:
    #0 0x7f170cd46b58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x982520 in AcquireQuantumInfo MagickCore/quantum.c:118
    #3 0x718d94 in ReadOnePNGImage coders/png.c:3517
    #4 0x71c2dc in ReadPNGImage coders/png.c:4380
    #5 0x7f27a7 in ReadImage MagickCore/constitute.c:497
    #6 0x7f48f5 in ReadImages MagickCore/constitute.c:866
    #7 0xadc3e5 in ConvertImageCommand MagickWand/convert.c:639
    #8 0xc10308 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x40f839 in MagickMain utilities/magick.c:149
    #10 0x40fa06 in main utilities/magick.c:180
    #11 0x7f1708055b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

Indirect leak of 1060 byte(s) in 4 object(s) allocated from:
    #0 0x7f170cd46b58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x43ed2f in AcquireQuantumMemory MagickCore/memory.c:536
    #3 0x982955 in AcquireQuantumPixels MagickCore/quantum.c:175
    #4 0x984573 in SetQuantumDepth MagickCore/quantum.c:693
    #5 0x984772 in SetQuantumEndian MagickCore/quantum.c:733
    #6 0x718de3 in ReadOnePNGImage coders/png.c:3522
    #7 0x71c2dc in ReadPNGImage coders/png.c:4380
    #8 0x7f27a7 in ReadImage MagickCore/constitute.c:497
    #9 0x7f48f5 in ReadImages MagickCore/constitute.c:866
    #10 0xadc3e5 in ConvertImageCommand MagickWand/convert.c:639
    #11 0xc10308 in MagickCommandGenesis MagickWand/mogrify.c:183
    #12 0x40f839 in MagickMain utilities/magick.c:149
    #13 0x40fa06 in main utilities/magick.c:180
    #14 0x7f1708055b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f170cd47590 in __interceptor_posix_memalign ../../../../libsanitizer/asan/asan_malloc_linux.cc:128
    #1 0x48bef5 in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x48bf9d in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x9835ac in GetQuantumInfo MagickCore/quantum.c:427
    #4 0x982642 in AcquireQuantumInfo MagickCore/quantum.c:122
    #5 0x718d94 in ReadOnePNGImage coders/png.c:3517
    #6 0x71c2dc in ReadPNGImage coders/png.c:4380
    #7 0x7f27a7 in ReadImage MagickCore/constitute.c:497
    #8 0x7f48f5 in ReadImages MagickCore/constitute.c:866
    #9 0xadc3e5 in ConvertImageCommand MagickWand/convert.c:639
    #10 0xc10308 in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x40f839 in MagickMain utilities/magick.c:149
    #12 0x40fa06 in main utilities/magick.c:180
    #13 0x7f1708055b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f170cd46b58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x43ed2f in AcquireQuantumMemory MagickCore/memory.c:536
    #3 0x982814 in AcquireQuantumPixels MagickCore/quantum.c:166
    #4 0x984573 in SetQuantumDepth MagickCore/quantum.c:693
    #5 0x984772 in SetQuantumEndian MagickCore/quantum.c:733
    #6 0x718de3 in ReadOnePNGImage coders/png.c:3522
    #7 0x71c2dc in ReadPNGImage coders/png.c:4380
    #8 0x7f27a7 in ReadImage MagickCore/constitute.c:497
    #9 0x7f48f5 in ReadImages MagickCore/constitute.c:866
    #10 0xadc3e5 in ConvertImageCommand MagickWand/convert.c:639
    #11 0xc10308 in MagickCommandGenesis MagickWand/mogrify.c:183
    #12 0x40f839 in MagickMain utilities/magick.c:149
    #13 0x40fa06 in main utilities/magick.c:180
    #14 0x7f1708055b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

1308 byte(s) leaked in 7 allocation(s).

testcase:https://github.com/bestshow/p0cs/blob/master/memory-leak-in-ReadOnePNGImage-22.png24
Credit:ADLab of Venustech

**Comment by dlemstra** [comment]
Can you run this again with the latest version of png.c from our git repository? It would help me in locating where we are leaking memory.

**Comment by bestshow** [comment]
@dlemstra 
OK, on ImageMagick 7.0.5-6 (the latest version)

#convert $FILE out.bmp
Direct leak of 152 byte(s) in 1 object(s) allocated from:
    #0 0x7f90f7d5bb58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x9822ca in AcquireQuantumInfo MagickCore/quantum.c:118
    #3 0x719928 in ReadOnePNGImage coders/png.c:3515
    #4 0x71ce38 in ReadPNGImage coders/png.c:4374
    #5 0x7f2551 in ReadImage MagickCore/constitute.c:497
    #6 0x7f469f in ReadImages MagickCore/constitute.c:866
    #7 0xadc18f in ConvertImageCommand MagickWand/convert.c:639
    #8 0xc100b2 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x40f839 in MagickMain utilities/magick.c:149
    #10 0x40fa06 in main utilities/magick.c:180
    #11 0x7f90f306ab34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

Indirect leak of 1060 byte(s) in 4 object(s) allocated from:
    #0 0x7f90f7d5bb58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x43ed2f in AcquireQuantumMemory MagickCore/memory.c:536
    #3 0x9826ff in AcquireQuantumPixels MagickCore/quantum.c:175
    #4 0x98431d in SetQuantumDepth MagickCore/quantum.c:693
    #5 0x98451c in SetQuantumEndian MagickCore/quantum.c:733
    #6 0x719977 in ReadOnePNGImage coders/png.c:3520
    #7 0x71ce38 in ReadPNGImage coders/png.c:4374
    #8 0x7f2551 in ReadImage MagickCore/constitute.c:497
    #9 0x7f469f in ReadImages MagickCore/constitute.c:866
    #10 0xadc18f in ConvertImageCommand MagickWand/convert.c:639
    #11 0xc100b2 in MagickCommandGenesis MagickWand/mogrify.c:183
    #12 0x40f839 in MagickMain utilities/magick.c:149
    #13 0x40fa06 in main utilities/magick.c:180
    #14 0x7f90f306ab34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f90f7d5c590 in __interceptor_posix_memalign ../../../../libsanitizer/asan/asan_malloc_linux.cc:128
    #1 0x48bef5 in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x48bf9d in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x983356 in GetQuantumInfo MagickCore/quantum.c:427
    #4 0x9823ec in AcquireQuantumInfo MagickCore/quantum.c:122
    #5 0x719928 in ReadOnePNGImage coders/png.c:3515
    #6 0x71ce38 in ReadPNGImage coders/png.c:4374
    #7 0x7f2551 in ReadImage MagickCore/constitute.c:497
    #8 0x7f469f in ReadImages MagickCore/constitute.c:866
    #9 0xadc18f in ConvertImageCommand MagickWand/convert.c:639
    #10 0xc100b2 in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x40f839 in MagickMain utilities/magick.c:149
    #12 0x40fa06 in main utilities/magick.c:180
    #13 0x7f90f306ab34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f90f7d5bb58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x43ed2f in AcquireQuantumMemory MagickCore/memory.c:536
    #3 0x9825be in AcquireQuantumPixels MagickCore/quantum.c:166
    #4 0x98431d in SetQuantumDepth MagickCore/quantum.c:693
    #5 0x98451c in SetQuantumEndian MagickCore/quantum.c:733
    #6 0x719977 in ReadOnePNGImage coders/png.c:3520
    #7 0x71ce38 in ReadPNGImage coders/png.c:4374
    #8 0x7f2551 in ReadImage MagickCore/constitute.c:497
    #9 0x7f469f in ReadImages MagickCore/constitute.c:866
    #10 0xadc18f in ConvertImageCommand MagickWand/convert.c:639
    #11 0xc100b2 in MagickCommandGenesis MagickWand/mogrify.c:183
    #12 0x40f839 in MagickMain utilities/magick.c:149
    #13 0x40fa06 in main utilities/magick.c:180
    #14 0x7f90f306ab34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

1308 byte(s) leaked in 7 allocation(s).

testcase:https://github.com/bestshow/p0cs/blob/master/memory-leak-in-ReadOnePNGImage-22.png24
Credit:ADLab of Venustech

**Comment by dlemstra** [comment]
@bestshow https://github.com/ImageMagick/ImageMagick/issues/462#issuecomment-299138056. This was next time :)

**Comment by bestshow** [comment]
@dlemstra Sorry，forgive my mistakes and I do it again.

on ImageMagick 7.0.5-6

Direct leak of 152 byte(s) in 1 object(s) allocated from:
    #0 0x7f90f7d5bb58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x9822ca in AcquireQuantumInfo MagickCore/quantum.c:118
    #3 0x719928 in ReadOnePNGImage coders/png.c:3515
    #4 0x71ce38 in ReadPNGImage coders/png.c:4374
    #5 0x7f2551 in ReadImage MagickCore/constitute.c:497
    #6 0x7f469f in ReadImages MagickCore/constitute.c:866
    #7 0xadc18f in ConvertImageCommand MagickWand/convert.c:639
    #8 0xc100b2 in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x40f839 in MagickMain utilities/magick.c:149
    #10 0x40fa06 in main utilities/magick.c:180
    #11 0x7f90f306ab34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

Indirect leak of 1060 byte(s) in 4 object(s) allocated from:
    #0 0x7f90f7d5bb58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x43ed2f in AcquireQuantumMemory MagickCore/memory.c:536
    #3 0x9826ff in AcquireQuantumPixels MagickCore/quantum.c:175
    #4 0x98431d in SetQuantumDepth MagickCore/quantum.c:693
    #5 0x98451c in SetQuantumEndian MagickCore/quantum.c:733
    #6 0x719977 in ReadOnePNGImage coders/png.c:3520
    #7 0x71ce38 in ReadPNGImage coders/png.c:4374
    #8 0x7f2551 in ReadImage MagickCore/constitute.c:497
    #9 0x7f469f in ReadImages MagickCore/constitute.c:866
    #10 0xadc18f in ConvertImageCommand MagickWand/convert.c:639
    #11 0xc100b2 in MagickCommandGenesis MagickWand/mogrify.c:183
    #12 0x40f839 in MagickMain utilities/magick.c:149
    #13 0x40fa06 in main utilities/magick.c:180
    #14 0x7f90f306ab34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f90f7d5c590 in __interceptor_posix_memalign ../../../../libsanitizer/asan/asan_malloc_linux.cc:128
    #1 0x48bef5 in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x48bf9d in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x983356 in GetQuantumInfo MagickCore/quantum.c:427
    #4 0x9823ec in AcquireQuantumInfo MagickCore/quantum.c:122
    #5 0x719928 in ReadOnePNGImage coders/png.c:3515
    #6 0x71ce38 in ReadPNGImage coders/png.c:4374
    #7 0x7f2551 in ReadImage MagickCore/constitute.c:497
    #8 0x7f469f in ReadImages MagickCore/constitute.c:866
    #9 0xadc18f in ConvertImageCommand MagickWand/convert.c:639
    #10 0xc100b2 in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x40f839 in MagickMain utilities/magick.c:149
    #12 0x40fa06 in main utilities/magick.c:180
    #13 0x7f90f306ab34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f90f7d5bb58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x43ed2f in AcquireQuantumMemory MagickCore/memory.c:536
    #3 0x9825be in AcquireQuantumPixels MagickCore/quantum.c:166
    #4 0x98431d in SetQuantumDepth MagickCore/quantum.c:693
    #5 0x98451c in SetQuantumEndian MagickCore/quantum.c:733
    #6 0x719977 in ReadOnePNGImage coders/png.c:3520
    #7 0x71ce38 in ReadPNGImage coders/png.c:4374
    #8 0x7f2551 in ReadImage MagickCore/constitute.c:497
    #9 0x7f469f in ReadImages MagickCore/constitute.c:866
    #10 0xadc18f in ConvertImageCommand MagickWand/convert.c:639
    #11 0xc100b2 in MagickCommandGenesis MagickWand/mogrify.c:183
    #12 0x40f839 in MagickMain utilities/magick.c:149
    #13 0x40fa06 in main utilities/magick.c:180
    #14 0x7f90f306ab34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

1308 byte(s) leaked in 7 allocation(s).
testcase:https://github.com/bestshow/p0cs/blob/master/memory-leak-in-ReadOnePNGImage-22.png24
Credit:ADLab of Venustech

**Comment by bestshow** [comment]
@dlemstra  Sorry, forgive my mistakes and I do it again.
on ImageMagick 7.0.5-6

Direct leak of 152 byte(s) in 1 object(s) allocated from: 
   [stack]0 0x7f90f7d5bb58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62 
   [stack]1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463 
   [stack]2 0x9822ca in AcquireQuantumInfo MagickCore/quantum.c:118 
   [stack]3 0x719928 in ReadOnePNGImage coders/png.c:3515 
   [stack]4 0x71ce38 in ReadPNGImage coders/png.c:4374 
   [stack]5 0x7f2551 in ReadImage MagickCore/constitute.c:497 
   [stack]6 0x7f469f in ReadImages MagickCore/constitute.c:866 
   [stack]7 0xadc18f in ConvertImageCommand MagickWand/convert.c:639 
   [stack]8 0xc100b2 in MagickCommandGenesis MagickWand/mogrify.c:183 
   [stack]9 0x40f839 in MagickMain utilities/magick.c:149 
   [stack]10 0x40fa06 in main utilities/magick.c:180 
   [stack]11 0x7f90f306ab34 in __libc_start_main (/lib64/libc.so.6+0x21b34) 

Indirect leak of 1060 byte(s) in 4 object(s) allocated from: 
   [stack]0 0x7f90f7d5bb58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62 
   [stack]1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463 
   [stack]2 0x43ed2f in AcquireQuantumMemory MagickCore/memory.c:536 
   [stack]3 0x9826ff in AcquireQuantumPixels MagickCore/quantum.c:175 
   [stack]4 0x98431d in SetQuantumDepth MagickCore/quantum.c:693 
   [stack]5 0x98451c in SetQuantumEndian MagickCore/quantum.c:733 
   [stack]6 0x719977 in ReadOnePNGImage coders/png.c:3520 
   [stack]7 0x71ce38 in ReadPNGImage coders/png.c:4374 
   [stack]8 0x7f2551 in ReadImage MagickCore/constitute.c:497 
   [stack]9 0x7f469f in ReadImages MagickCore/constitute.c:866 
   [stack]10 0xadc18f in ConvertImageCommand MagickWand/convert.c:639 
   [stack]11 0xc100b2 in MagickCommandGenesis MagickWand/mogrify.c:183 
   [stack]12 0x40f839 in MagickMain utilities/magick.c:149 
   [stack]13 0x40fa06 in main utilities/magick.c:180 
   [stack]14 0x7f90f306ab34 in __libc_start_main (/lib64/libc.so.6+0x21b34) 

Indirect leak of 64 byte(s) in 1 object(s) allocated from: 
   [stack]0 0x7f90f7d5c590 in __interceptor_posix_memalign ../../../../libsanitizer/asan/asan_malloc_linux.cc:128 
   [stack]1 0x48bef5 in AcquireSemaphoreMemory MagickCore/semaphore.c:154 
   [stack]2 0x48bf9d in AcquireSemaphoreInfo MagickCore/semaphore.c:200 
   [stack]3 0x983356 in GetQuantumInfo MagickCore/quantum.c:427 
   [stack]4 0x9823ec in AcquireQuantumInfo MagickCore/quantum.c:122 
   [stack]5 0x719928 in ReadOnePNGImage coders/png.c:3515 
   [stack]6 0x71ce38 in ReadPNGImage coders/png.c:4374 
   [stack]7 0x7f2551 in ReadImage MagickCore/constitute.c:497 
   [stack]8 0x7f469f in ReadImages MagickCore/constitute.c:866 
   [stack]9 0xadc18f in ConvertImageCommand MagickWand/convert.c:639 
   [stack]10 0xc100b2 in MagickCommandGenesis MagickWand/mogrify.c:183 
   [stack]11 0x40f839 in MagickMain utilities/magick.c:149 
   [stack]12 0x40fa06 in main utilities/magick.c:180 
   [stack]13 0x7f90f306ab34 in __libc_start_main (/lib64/libc.so.6+0x21b34) 

Indirect leak of 32 byte(s) in 1 object(s) allocated from: 
   [stack]0 0x7f90f7d5bb58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62 
   [stack]1 0x43ecdb in AcquireMagickMemory MagickCore/memory.c:463 
   [stack]2 0x43ed2f in AcquireQuantumMemory MagickCore/memory.c:536 
   [stack]3 0x9825be in AcquireQuantumPixels MagickCore/quantum.c:166 
   [stack]4 0x98431d in SetQuantumDepth MagickCore/quantum.c:693 
   [stack]5 0x98451c in SetQuantumEndian MagickCore/quantum.c:733 
   [stack]6 0x719977 in ReadOnePNGImage coders/png.c:3520 
   [stack]7 0x71ce38 in ReadPNGImage coders/png.c:4374 
   [stack]8 0x7f2551 in ReadImage MagickCore/constitute.c:497 
   [stack]9 0x7f469f in ReadImages MagickCore/constitute.c:866 
   [stack]10 0xadc18f in ConvertImageCommand MagickWand/convert.c:639 
   [stack]11 0xc100b2 in MagickCommandGenesis MagickWand/mogrify.c:183 
   [stack]12 0x40f839 in MagickMain utilities/magick.c:149 
   [stack]13 0x40fa06 in main utilities/magick.c:180 
   [stack]14 0x7f90f306ab34 in __libc_start_main (/lib64/libc.so.6+0x21b34) 

1308 byte(s) leaked in 7 allocation(s).

**Comment by dlemstra** [comment]
I am unable to reproduce your issue. I get the following output:
```
D:\>convert memory-leak-in-ReadOnePNGImage-22.png24 null:
convert: IHDR: CRC error `memory-leak-in-ReadOnePNGImage-22.png24' @ error/png.c/MagickPNGErrorHandler/1672.
convert: corrupt image `memory-leak-in-ReadOnePNGImage-22.png24' @ error/png.c/ReadPNGImage/4394.
convert: no images defined `null:' @ error/convert.c/ConvertImageCommand/3254.
```

I also attached a debugger with Visual Studio but line `3515` is never reached. And with the current code of png.c I cannot see a point where we exit the method without releasing quantum_info.

**Comment by dlemstra** [comment]
@bestshow Can you still reproduce this issue?

**Comment by bestshow** [comment]
@dlemstra 
Yes , it still reproduce on Version: ImageMagick 7.0.5-8 Q16

```
#convert $FILE out.bmp
Direct leak of 152 byte(s) in 1 object(s) allocated from:
    #0 0x7f4b34b28b58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43f1c8 in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x984bc5 in AcquireQuantumInfo MagickCore/quantum.c:118
    #3 0x71b631 in ReadOnePNGImage coders/png.c:3515
    #4 0x71eb41 in ReadPNGImage coders/png.c:4374
    #5 0x7f4bb1 in ReadImage MagickCore/constitute.c:497
    #6 0x7f6cff in ReadImages MagickCore/constitute.c:866
    #7 0xae742c in ConvertImageCommand MagickWand/convert.c:639
    #8 0xc1b34f in MagickCommandGenesis MagickWand/mogrify.c:183
    #9 0x40fc49 in MagickMain utilities/magick.c:149
    #10 0x40fe16 in main utilities/magick.c:180
    #11 0x7f4b2fc27b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

Indirect leak of 1060 byte(s) in 4 object(s) allocated from:
    #0 0x7f4b34b28b58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43f1c8 in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x43f21c in AcquireQuantumMemory MagickCore/memory.c:536
    #3 0x984ffa in AcquireQuantumPixels MagickCore/quantum.c:175
    #4 0x986c18 in SetQuantumDepth MagickCore/quantum.c:693
    #5 0x986e17 in SetQuantumEndian MagickCore/quantum.c:733
    #6 0x71b680 in ReadOnePNGImage coders/png.c:3520
    #7 0x71eb41 in ReadPNGImage coders/png.c:4374
    #8 0x7f4bb1 in ReadImage MagickCore/constitute.c:497
    #9 0x7f6cff in ReadImages MagickCore/constitute.c:866
    #10 0xae742c in ConvertImageCommand MagickWand/convert.c:639
    #11 0xc1b34f in MagickCommandGenesis MagickWand/mogrify.c:183
    #12 0x40fc49 in MagickMain utilities/magick.c:149
    #13 0x40fe16 in main utilities/magick.c:180
    #14 0x7f4b2fc27b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

Indirect leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f4b34b29590 in __interceptor_posix_memalign ../../../../libsanitizer/asan/asan_malloc_linux.cc:128
    #1 0x48c3e2 in AcquireSemaphoreMemory MagickCore/semaphore.c:154
    #2 0x48c48a in AcquireSemaphoreInfo MagickCore/semaphore.c:200
    #3 0x985c51 in GetQuantumInfo MagickCore/quantum.c:427
    #4 0x984ce7 in AcquireQuantumInfo MagickCore/quantum.c:122
    #5 0x71b631 in ReadOnePNGImage coders/png.c:3515
    #6 0x71eb41 in ReadPNGImage coders/png.c:4374
    #7 0x7f4bb1 in ReadImage MagickCore/constitute.c:497
    #8 0x7f6cff in ReadImages MagickCore/constitute.c:866
    #9 0xae742c in ConvertImageCommand MagickWand/convert.c:639
    #10 0xc1b34f in MagickCommandGenesis MagickWand/mogrify.c:183
    #11 0x40fc49 in MagickMain utilities/magick.c:149
    #12 0x40fe16 in main utilities/magick.c:180
    #13 0x7f4b2fc27b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)

Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f4b34b28b58 in __interceptor_malloc ../../../../libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x43f1c8 in AcquireMagickMemory MagickCore/memory.c:463
    #2 0x43f21c in AcquireQuantumMemory MagickCore/memory.c:536
    #3 0x984eb9 in AcquireQuantumPixels MagickCore/quantum.c:166
    #4 0x986c18 in SetQuantumDepth MagickCore/quantum.c:693
    #5 0x986e17 in SetQuantumEndian MagickCore/quantum.c:733
    #6 0x71b680 in ReadOnePNGImage coders/png.c:3520
    #7 0x71eb41 in ReadPNGImage coders/png.c:4374
    #8 0x7f4bb1 in ReadImage MagickCore/constitute.c:497
    #9 0x7f6cff in ReadImages MagickCore/constitute.c:866
    #10 0xae742c in ConvertImageCommand MagickWand/convert.c:639
    #11 0xc1b34f in MagickCommandGenesis MagickWand/mogrify.c:183
    #12 0x40fc49 in MagickMain utilities/magick.c:149
    #13 0x40fe16 in main utilities/magick.c:180
    #14 0x7f4b2fc27b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)
```

**Comment by dlemstra** [comment]
@bestshow Can you give it another try with the latest version?

**Comment by bestshow** [comment]
@dlemstra The issue was fixed in the latest version.
