### ISSUE TITLE
Alpha channel is ignored on all but the first image received from a RGBA pipe

### ISSUE THREAD

**Issue by Saiapatsu** [ImageMagick/ImageMagick#4629]
### ImageMagick version

ImageMagick 7.1.0-18

### Operating system

Windows

### Operating system, version and so on

Windows 8.1

### Description

`magick` can receive raw RGBA data from standard input. If the amount of data exceeds `width`x`height`x`depth`, then multiple images will be received. Only the first image loaded this way will have alpha information. Successive images will be completely opaque.

### Steps to Reproduce

Run this command:
```
magick -size 128x128 -depth 8 xc:#FF00FF00 RGBA:- | magick -size 128x64 -depth 8 RGBA:- -append out.png
```

It will create a 128x128 image that's transparent (#FF00FF00) in the top half and opaque pink (#FF00FFFF) in the bottom half.
Outputting to `RGBA:out` instead of `out.png` reveals that the data is, indeed, half transparent and half pink.

The expected output is a fully transparent 128x128 image like the output of one of these commands:
```
magick -size 128x128 -depth 8 xc:#FF00FF00 out.png
magick -size 128x128 -depth 8 xc:#FF00FF00 -crop 128x64 -append out.png
```

The bug also occurs if the transparent image is piped from disk to magick:
```
magick -size 128x128 -depth 8 xc:#FF00FF00 RGBA:out
type out | magick -size 128x64 -depth 8 RGBA:- -append out.png
```
(replace `type` with `cat` on Unix?)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
