### ISSUE TITLE
No git tag for 7.1.0-19

### ISSUE THREAD

**Issue by dotlambda** [ImageMagick/ImageMagick#4633]
### ImageMagick version

7.1.0-19

### Operating system

Other (enter below)

### Operating system, version and so on

any

### Description

The tag for version 7.1.0-19 is missing on https://github.com/ImageMagick/ImageMagick/releases and https://github.com/ImageMagick/ImageMagick/tags.
This is keeping me from packaging that version for NixOS.

### Steps to Reproduce

Follow the above links.

**Comment by urban-warrior** [comment]
There is likely a lag due to the holidays.  Behind these seemly automated systems are real humans that want time off to connect with family and friends.  Give us a few days to export the tag.
