### ISSUE TITLE
Needs windows.h

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#4638]
### ImageMagick version

7.1.0-19

### Operating system

Windows

### Operating system, version and so on

Windows 8.1, with Cygwin toolchain

### Description

I'm trying to build IM v7.1.0-19, on a Windows 8.1 laptop, with Cygwin.

One problem was that "make" failed at MagickCore/nt-feature.c with messages like:
```
warning: implicit declaration of function 'GetLogicalDrives'
error: unknown type name 'HKEY'
error: unknown type name 'LONG'
error: unknown type name 'DWORD'
error: 'KEY_READ' undeclared
```

An older version of IM, v7.0.8-64, in MagickCore/nt-feature.c, had the line "#include <windows.h>". That line seems to have been removed. Inserting that line into MagickCore/nt-feature.c fixes that problem.

### Steps to Reproduce

Use Cygwin tools: automake, autoconf, ./configure, make.

Fails at "make".

### Images

No images.

**Comment by dlemstra** [comment]
I will take a look at it this weekend.

**Comment by dlemstra** [comment]
Do you also need these two defines?:

```
#define WIN32_LEAN_AND_MEAN
#define VC_EXTRALEAN
```

The `windows.h` header file should already be included from the `studio.h` file so I don't understand why I would need to restore this.

**Comment by snibgo** [comment]
Sorry, I have only just seen your reply:
> Do you also need these two defines?

I don't also need those. Including windows.h is sufficient.

I did a "git clone" of IM today, and the make failed again with the same messages. "#include <windows.h>" fixed the problem.

**Comment by FuzzyBunnys** [comment]
I have had the same issue as snibgo, following his advice on a separate thread I was able to successfully build ImageMagick after adding the line he specified

**Comment by dlemstra** [comment]
@urban-warrior pushed some patches to restore this for Cygwin and this should be resolved in the next release.
