### ISSUE TITLE
mogrify: unrecognized option `-compose'

### ISSUE THREAD

**Issue by mfaux** [ImageMagick/ImageMagick#4639]
### ImageMagick version

7.1.0-19

### Operating system

Windows

### Operating system, version and so on

Windows 10 Enterprise

### Description

`mogrify` doesn't recognize the option `-compose`.

```
magick mogrify -background "transparent" -bordercolor "#a4a4a4" -compose "Copy" -border 1 *
mogrify: unrecognized option `-compose' @ error/mogrify.c/MogrifyImageCommand/4675.
```

Note that `convert` works fine with `-compose`:

```
magick convert -background "transparent" -bordercolor "#a4a4a4" -compose "Copy" -border 1 input.png output.png
```

### Steps to Reproduce

To reproduce, run:

```
magick mogrify -background "transparent" -bordercolor "#a4a4a4" -compose "Copy" -border 1 *
```

### Images

![image](https://user-images.githubusercontent.com/1324114/147667464-a557a9d1-a7c6-40f5-8aa9-cee0c3312f20.png)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
