### ISSUE TITLE
-fuzz doesn't seem to do anything for a gif

### ISSUE THREAD

**Issue by Yay295** [ImageMagick/ImageMagick#464]
Calling `convert tt1.png tt2.png -fuzz 90% -layers optimize tg.gif` ([tt1](https://cloud.githubusercontent.com/assets/8922038/25553068/2e42a3a6-2c67-11e7-9fbf-5f9d2b8b5b75.png), [tt2](https://cloud.githubusercontent.com/assets/8922038/25553069/2e575922-2c67-11e7-92cc-e6231c78c960.png)), and then converting the gif back to png's gives me [A](https://cloud.githubusercontent.com/assets/8922038/25553079/756d116c-2c67-11e7-9cfe-3bffbfc8fb6b.png) and [B](https://cloud.githubusercontent.com/assets/8922038/25553078/756c5f6a-2c67-11e7-96e2-3353a10b662e.png). With `-fuzz 90%` I wouldn't have expected to see "TEXT" in the top left of the second frame.

**Comment by fmw42** [comment]
What is your IM version and platform? If I do your commands, I do not see any text in the final B result. The text is there, but only if you remove the alpha channel.  What are you trying to do with -fuzz 90%?

**Comment by Yay295** [comment]
I figured out what I was doing wrong after running the commands again from the command line. I had previously been running them from a batch file (on Windows 7), and `%` is a special character in Batch, so `90%` was turning into just `90` when the file executed. I was using 90% to try to see a difference.
