### ISSUE TITLE
IM with OpenCL enabled on Linux with AMD GPU appear not to be working

### ISSUE THREAD

**Issue by denydias** [ImageMagick/ImageMagick#4646]
### ImageMagick version

7.1.0-19

### Operating system

Linux

### Operating system, version and so on

Slackware 15.0 x86_64 (-current), Linux kernel 5.15.12, OpenCL 2.1 AMD-APP, amdgpu-opencl-20.40-x86_64

### Description

I've been trying to enable IM OpenCL support without much success. With no further ado, here is my environment and build details:

```
$ clinfo 
Number of platforms:                             2
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.1 AMD-APP (3180.7)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 1.1 Mesa 21.2.6
  Platform Name:                                 Clover
  Platform Vendor:                               Mesa
  Platform Extensions:                           cl_khr_icd

  Platform Name:                                 AMD Accelerated Parallel Processing
  Number of devices:                             1
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     1002h
  Board name:                                    Unknown AMD GPU

...some long info feature details cleaned...

  Platform ID:                                   0x7f044c042f30
  Name:                                          gfx902
  Vendor:                                        Advanced Micro Devices, Inc.
  Device OpenCL C version:                       OpenCL C 2.0 
  Driver version:                                3180.7 (PAL,HSAIL)
  Profile:                                       FULL_PROFILE
  Version:                                       OpenCL 2.0 AMD-APP (3180.7)
  Extensions:                                    cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_khr_gl_depth_images cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes cl_amd_copy_buffer_p2p
```

```
$ ./configure \
  --prefix=/usr \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --mandir=/usr/man \
  --sysconfdir=/etc \
  --program-prefix= \
  --with-x \
  --with-frozenpaths=no \
  --with-modules \
  --enable-opencl \
  --enable-hdri \
  --enable-static=no \
  --enable-shared \
  --with-gcc-arch=$ARCH \
  --with-perl \
  --with-perl-options="INSTALLDIRS=vendor" \
  --with-rsvg \
  --build=$ARCH-slackware-linux || exit 1
```

```
$ grep checking imocl-configure.log | grep -e cl.h -e OpenCL
checking CL/cl.h usability... yes
checking CL/cl.h presence... yes
checking for CL/cl.h... yes
checking for OpenCL library... yes
```

During compile time I see a lot of this:

```
In file included from /usr/include/CL/cl.h:20,
                 from ./MagickWand/studio.h:133,
                 from utilities/magick.c:44:
/usr/include/CL/cl_version.h:22:9: note: ‘#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)’
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
      |         ^~~~~~~
```

Then I applied the following patch I did:

```
--- MagickCore/opencl.c.orig   2021-12-22 18:03:36.000000000 -0300
+++ MagickCore/opencl.c   2021-12-31 06:25:36.259201608 -0300
@@ -99,6 +99,9 @@
 /*
   Define declarations.
 */
+#define CL_HPP_MINIMUM_OPENCL_VERSION 110
+#define CL_HPP_TARGET_OPENCL_VERSION 210
+#define CL_TARGET_OPENCL_VERSION 210
 #define IMAGEMAGICK_PROFILE_FILE "ImagemagickOpenCLDeviceProfile.xml"
 
 /*
```

But the warnings keep popping. Anyway, let's move on...

```
$ magick -version
Version: ImageMagick 7.1.0-19 Q16-HDRI x86_64 2021-12-18 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fontconfig freetype jng jp2 jpeg lcms ltdl lzma openexr pangocairo png raw rsvg tiff webp wmf x xml zip zlib
Compiler: gcc (11.2)
```

It all looks good for OpenCL support, but when I run `convert logo: -despeckle null:` a `$HOME/.cache/ImageMagick/ImagemagickOpenCLDeviceProfile.xml` is never created. Other `convert` tests using filters know to be OpenCL accelerated (e.g. gaussian-blur) shows no GPU activity and only uses OpenMP (multiprocessing on CPU).

What am I missing?

Thanks in advance for any advice.

### Steps to Reproduce

Compile IM with `--enable-opencl` on updated Slackware64 -current and AMD OpenCL drivers v20.40.

**Comment by dlemstra** [comment]
OpenCL is disabled by default. You will need to set `MAGICK_OCL_DEVICE` to `true` or to `GPU/CPU` to enable it.

**Comment by denydias** [comment]
Thanks for the quick reply, @dlemstra.

Oh! During runtime? Like `MAGICK_OCL_DEVICE=true magick -version`?

**Comment by dlemstra** [comment]
The `-version` option does not do any OpenCL operations so that doesn't really do anything but yes you will need to set it at runtime. And if that doesn't work you probably have an `NVIDIA` card that we had to disable due to strange access violations.

**Comment by denydias** [comment]
Right! I used `-version` by mistake. I did it with:

`MAGICK_OCL_DEVICE=true convert logo: -despeckle null:`

And nope. No OpenCL profile created.

I'm aware of some NVIDIA hardware being [disabled](https://github.com/ImageMagick/ImageMagick/commit/0e27e8568c46b2e83058fe655a32be84cee4e791#diff-8d1566c14dcfa367c671ccd4dc077d2fdb26feb1dcfce203408e70d7fd6673f6), but that's not my case as I have an AMD one, precisely AMD Ryzen 7 5700U with Radeon Graphics.

That's why I came here upstream to report this. ;)

**Comment by dlemstra** [comment]
First of all `convert` should probably be `magick` instead. OpenCL only works on images without a color map and our `logo:` image has a color map. And for this method you will also need to have the alpha channel enabled.

**Comment by denydias** [comment]
Understood. I also tried the command bellow with the attached image:

```
MAGICK_OCL_DEVICE=true convert 20211230_imagemagick-opencl.jpg -monitor -gaussian-blur 0x20 test-blur-ocl.jpg
```

Is that enough to enable OpenCL? This command also doesn´t generate the profile and processing occurs only in CPU realm.

PS: I know my OpenCL hardware is working for sure because GIMP's Bilateral filter (which is [know to be OpenCL accelerated](https://wiki.gimp.org/wiki/Hacking:Porting_filters_to_GEGL#Port_of_new_GEGL_ops_to_OpenCL)) on this very same image and it rises GPU processing to the top, while CPU is free.

![20211230_imagemagick-opencl](https://user-images.githubusercontent.com/948202/147819494-352b64da-d231-4249-a1af-45c367f2369f.jpg)

**Comment by dlemstra** [comment]
We had to disable OpenCL inside `ConvolveImage` that is used by `GaussianBlurImage` so this path will also not use OpenCL. And as I said before some of the opertions need an alpha channel enabled. For example this one does:

`magick 20211230_imagemagick-opencl.jpg -alpha on -despeckle null:`

**Comment by denydias** [comment]
All right. That seems to work. Thank you, @dlemstra.

Now I have `~/.cache/ImageMagick/ImagemagickOpenCLDeviceProfile.xml` and processing time difference is relevant:

```
$ time magick 20211230_imagemagick-opencl.jpg -alpha on -despeckle null:
real    0m1,719s
user    0m19,743s
sys     0m0,155s

$ time MAGICK_OCL_DEVICE=true magick 20211230_imagemagick-opencl.jpg -alpha on -despeckle null:

real    0m0,843s
user    0m0,961s
sys     0m0,193s
```

There's also a huge difference in CPU/GPU usage when `MAGICK_OCL_DEVICE=true`.

As such the bug here does not appear to be on the code itself but in documentation instead. In this issue we've seen a lot of conditions[^1] required by `magick` so OpenCL can be used. But none of these conditions are documented at [ImageMagick OpenCL page](https://imagemagick.org/script/opencl.php).

Is that a good moment to upgrade that document?

[^1]: e.g. `MAGICK_OCL_DEVICE` defaults to false, some NVIDIA excluded, alpha on, no filter using `ConvolveImage` etc.

**Comment by dlemstra** [comment]
Feel free to help us improve the documentation, the source for that page can be found in this repository: https://github.com/ImageMagick/Website.

**Comment by denydias** [comment]
Nice! I'll propose some changes there, @dlemstra.

Based on that page's filter list, can you at least provide an updated list of filters still in OpenCL path?

**Comment by dlemstra** [comment]
Thanks for offering to help us with this. The following operators are still supported:

`blur` `contrast` `charcoal` `function` `grayscale` `motion-blur` `resize`

And these require an alpha channel:

`despeckle` `equalize` `modulate`

**Comment by denydias** [comment]
My pleasure!

The rest is up to me now. Thank you so much, @dlemstra.

**Comment by denydias** [comment]
Done!

https://github.com/ImageMagick/Website/pull/84
