### ISSUE TITLE
Disabling antialiasing disable rotation also

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#4649]
### ImageMagick version

7.1.0-17

### Operating system

Linux

### Operating system, version and so on

Debian 11

### Description

Disabling font anti-aliasing also disables rotation.

This was reported from a user using PHP Imagick https://github.com/Imagick/imagick/issues/525, so going through MagickWand, but seems reproducible on the command line also.

### Steps to Reproduce

Two commands should produce similar result:

magick logo: -antialias -pointsize 48 -draw "rotate 45 text 10,10 \'Works like magick\'"  logo_with_antialias.png

magick logo: +antialias -pointsize 48 -draw "rotate 45 text 10,10 \'Works like magick\'"  logo_no_antialias.png

### Images

![logo_with_antialias](https://user-images.githubusercontent.com/1505719/147864972-e85b7794-6cd2-4a14-b6cd-49bdd5c4afae.png)

![logo_no_antialias](https://user-images.githubusercontent.com/1505719/147864975-ee717438-24e2-4eec-88cf-029cf7d09b50.png)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
