### ISSUE TITLE
FxImage() multithreading

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#4654]
### ImageMagick version

v7.1.0-20

### Operating system

Windows

### Operating system, version and so on

Windows 8.1

### Description

In a recent update to fx.c, in FxImage(), the multithreading for the y loop has changed to:
```
  #pragma omp parallel for schedule(dynamic) shared(progress,status) \
    magick_number_threads(image,fx_image,fx_image->rows, \
      GlobExpression(fx_info[0]->expression,"debug(",MagickTrue) == 0 ? 1 : 0)
```
However, ...
```
GlobExpression(fx_info[0]->expression,"debug(",MagickTrue)
```
... is always false, except for the unusual case where the expression is exactly "debug(", ignoring case. Hence the ternary result is always 1, so multithreading is always enabled.

Perhaps the intention was to use:
```
GlobExpression(fx_info[0]->expression,"*debug(*",MagickTrue)
```
... with wildcards '*', so multithreading would be disabled when the expression contained "debug(" anywhere within the string.

Incidentally, I expect to propose a replacement for FxImage() etc in about a week.

### Steps to Reproduce

See the code in fx.c FxImage().

### Images

N/A

**Comment by urban-warrior** [comment]
Your analysis is sound, we will apply a patch.  Also, looking forward to reviewing your implementation.
