### ISSUE TITLE
`-family` fallback not working as intended

### ISSUE THREAD

**Issue by vladdeSV** [ImageMagick/ImageMagick#4660]
### ImageMagick version

7.1.0-19

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04 (on Windows Subsystem for Linux)

### Description

I am attempting to use the `-family` flag to primarily use one typeface, and have a fallback typeface for Japanese characters. However, I believe the flag is not working as intended.

### Steps to Reproduce

I'll show a few examples showing my reasoning, and also demonstrating that my fonts are properly installed. I will be creating an image with the text `1月` (ordinary 1, and the moon symbol in Japanese) with the typefaces *Arial* and *[Noto Sans JP](https://fonts.google.com/noto/specimen/Noto+Sans+JP)*.

This command produces the following image, with the moon character missing; this is what to be expected.
```sh
convert -pointsize 50 -family 'Arial' label:'1月' arial.png
```
![arial](https://user-images.githubusercontent.com/7542961/148000168-eb98f230-15b8-41c1-8736-e191ac9f6841.png)

To verify I have properly installed *Noto Sans JP* I'll run the same command with this typeface as well, which produces this image. Besides the `月` now appearing, we see that the `1` is different.
```
convert -pointsize 50 -family 'Noto Sans JP' label:'1月' noto.png
```
![noto](https://user-images.githubusercontent.com/7542961/148000248-c0317234-362e-4d39-8aa5-8db6f7798007.png)

According to the official website, "the family can be a CSS-style font list" ([source](https://imagemagick.org/script/command-line-options.php#family)). If we try to pass in a CSS-style like string for the font family I expect to get multiple typefaces.

### Parsing families

Before I continue, I would like to address that, if a font family is not understood it defaults to something similar; in my case it defaults to *Arial*. To demonstrate a point I will now use *Courier* and *Noto Sans JP*.

The three lines use valid CSS family list syntax, which a browser would interpret to firstly use Courier. This examples shows that parsing the families is not handled properly.
```
convert -pointsize 50 \
  -family "Courier,   'Noto Sans JP'" label:'word' \
  -family "Courier ,  'Noto Sans JP'" label:'word' \
  -family "'Courier', 'Noto Sans JP'" label:'word' \
-append combined.png
```
![combined](https://user-images.githubusercontent.com/7542961/148004236-03520ccd-bf01-4810-b9d2-5a67859e1b9a.png)

This next example specifies the fonts as separated with spaces. 

```
convert -pointsize 50 \
  -family "'Courier' 'Noto Sans JP'" label:'word' \
  -family "'Courier' 'Noto Sans JP' ," label:'word' \
  -family "'Noto Sans JP' 'Courier' ," label:'word' \
-append combined.png
```
![combined](https://user-images.githubusercontent.com/7542961/148004840-f441d913-6de2-43f2-8af0-8b9c0c1a7ef2.png)

The first line results in the typeface *Arial* being used; it looks for the font name `'Courier' 'Noto Sans JP'`, which is an invalid name, and defaults to *Arial* (notice the first "word" being in *Arial*). However, the second line is interpreted differently. Because it contains a comma at the end of the string, it interpreted as having multiple families [by this line of code](https://github.com/ImageMagick/ImageMagick6/blob/main/magick/annotate.c#L991). It is then [passed to `StringToArgv`](https://github.com/ImageMagick/ImageMagick6/blob/main/magick/annotate.c#L1008) which (I assume) returns `['Courier', 'Noto Sans JP', ',']`. The third line only demonstrates that parsing the order of family names works, and that it is not a fluke that they use different fonts.

### Fallback fonts
With the knowledge of how families are parsed right now, we can construct an example showing that fallbacks in fact do not work properly.

```
convert -pointsize 50 -family "Courier 'Noto Sans JP' ," label:'1月' combined.png
```
![combined](https://user-images.githubusercontent.com/7542961/148004990-328d6a26-ea42-4dbe-8b59-0c3e969849bb.png)

I expect the text "1月" to appear, where the "1" is in *Courier*, and the "月" is in *Noto Sans JP*.

---

Fallback families were brought up in issue https://github.com/ImageMagick/ImageMagick/issues/2153, and from my understanding a11b665e00cac39849987a20eaefed1d7dc784bd was supposed to fix this.

Looking at this [line of code](https://github.com/ImageMagick/ImageMagick6/blob/main/magick/annotate.c#L1008) which is supposed to parse the families inputted, it uses the function `StringToArgv`. From reading [the code of `StringToArgv`](https://github.com/ImageMagick/ImageMagick6/blob/7b5d5d943fec12ccd167a6fed11758c609cb3275/magick/string.c#L2002), I believe it only separates arguments separated by whitespace, and not commas.

Thank you for taking the time to read through this long report 👋.

**Comment by vladdeSV** [comment]
I did not bring this up in the report, but I am using the command `convert` instead of `magick`/`magick-script`.

On my system, with the latter, fonts do not get recognized and default to *Arial*. I am unsure how relevant this is, but because my examples work with `convert` I opted to use that.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
