### ISSUE TITLE
Support for Image tracing

### ISSUE THREAD

**Issue by OyewoleOyedeji** [ImageMagick/ImageMagick#4669]
### Is your feature request related to a problem? Please describe.

Yes, when trying to convert `PNG` to `SVG`, I see you guys just copied the data URI of the `PNG` file and pasted it in the `SVG` file

### Describe the solution you'd like

Support `image tracing` and export of PNG files to SVG. Somehow like what Adobe illustrator supports

### Describe alternatives you've considered

None yet

### Additional context

Nope

**Comment by snibgo** [comment]
Vectorization of raster images is a large and complex topic. Do you have specific needs?

Open source programs (eg potrace and autotrace) have sometimes been included with IM, as external delegates.

**Comment by OyewoleOyedeji** [comment]
@snibgo something like what `Adobe Illustrator`, trying looking up convert `PNG` to `SVG` on YouTube. That is what I mean
