### ISSUE TITLE
Convert Tiff to PNG error

### ISSUE THREAD

**Issue by reply2srij** [ImageMagick/ImageMagick#4671]
### ImageMagick version

ImageMagick 7.0.8-45

### Operating system

Linux

### Operating system, version and so on

AWS Lambda 

### Description

Hi!

I'm getting this error when I try to convert a TIF file to PNG:
org.im4java.core.CommandException: org.im4java.core.CommandException: convert: improper image header `/tmp/XYZ.TIF' @ error/tiff.c/ReadTIFFImage/1388.

I'm using the following version of imageMagick 
ImageMagick 7.0.8-45 from https://console.aws.amazon.com/lambda/home?region=us-east-1#/create/app?applicationId=arn:aws:serverlessrepo:us-east-1:145266761615:applications/image-magick-lambda-layer 

Thank you.

### Steps to Reproduce

Invoking convert command using im4java throws image magick error 

### Images

File Attached:

[XYZ.zip](https://github.com/ImageMagick/ImageMagick/files/7817394/XYZ.zip)

**Comment by fmw42** [comment]
You might be able to attach the file if you zip it first.

**Comment by reply2srij** [comment]
> 

Thank you, attached the file.

**Comment by fmw42** [comment]
Your tiff file may be damaged or malformed. I tried to open it in Mac Preview and it complained.   Is is JPG compressed.  The libtif that ImageMagick uses will not support the older JPG compression. Otherwise, one of the IM developers will need to look into this.

**Comment by fmw42** [comment]
P.S. I can open it in Mac GraphicsConverter. So I suspect there is something malformed in the header or it uses the older JPG compression.

**Comment by reply2srij** [comment]
> 

The source for these images are old legacy applications, which I dont have understanding/control of. But as I saw another similar issue https://github.com/ImageMagick/ImageMagick/issues/1091, wanted to bring this up in case this is something that needs to be looked at

**Comment by urban-warrior** [comment]
Your image does not include the required tags such as photometric interpretation.  As such, ImageMagick won't read it.  We tried a few utilities and the image was rejected, likely for the same reason.  However, Gimp and Atril could read the image.
