### ISSUE TITLE
Installation is broken on macOS

### ISSUE THREAD

**Issue by ad-si** [ImageMagick/ImageMagick#4676]
### ImageMagick version

7.0.10

### Operating system

MacOS

### Operating system, version and so on

\>= 11.6

### Description

I can't install ImageMagick on macOS versions >11.6. (I don't have access to older versions, so maybe it doesn't work on them either.)

### Steps to Reproduce

After following the installation instructions at https://imagemagick.org/script/download.php#macosx I get following error:

```txt 
$ ./magick -version 
dyld: Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Users/mm501k1/Downloads/Perspec.app/Contents/Resources/imagemagick/bin/./magick
  Reason: image not found
zsh: abort      ./magick -version
```

**Comment by fmw42** [comment]
Current ImageMagick binary for Mac will not work for older systems. You should install from Homebrew or from MacPorts.  Homebrew will install IM 7. MacPorts will install IM 6.  The alternate is to install all delegates from MacPorts, but install IM 7 from source after installing the delegates. Homebrew is the simplest way to go.

**Comment by ad-si** [comment]
> Current ImageMagick binary for Mac will not work for older systems

It's also not working on the latest version (12.1). That's why I wrote `>= 11.6`

I want to bundle ImageMagick in my app https://github.com/feramhq/Perspec. Therefore installing with Homebrew is not an option.

Also, if the macOS installation is broken, but there is no fix planned I think it should be removed from the website to not mislead people.

**Comment by fmw42** [comment]
It is not broken. It is compiled for a given Mac OSX version. They cannot compile versions for every Mac OSX version  There is a portable version. See the Linux version labeled "Magick". That might work on Mac, but I will defer to the IM developers for further comment.

**Comment by ad-si** [comment]
😳  I'm really sorry. I read over the "macOS High Sierra" the whole time. I thought it was a generic macOS installation. That explains a lot 🙈
