### ISSUE TITLE
#include inside namespace causes problems with library functions

### ISSUE THREAD

**Issue by hstejas** [ImageMagick/ImageMagick#4679]
### ImageMagick version

7.0.11-14

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.10, tested on gcc 11 and clang 13

### Description

In `Magick++/lib/Magick++/Include.h:45` 

```cpp
    namespace MagickCore
    {
    #include <MagickCore/MagickCore.h>
    #include <MagickWand/MagickWand.h>
    #undef inline // Remove possible definition from config.h
    
    #undef class
    }
```

since `MagickCore.h` and `MagickWand.h` includes other c library headers, all these are declared in this namespace,
this causes issues if I(or a third part lib I use) happen to use the same functions/types.

### Steps to Reproduce

This specific code causes a compilation error due to the namespace issue.

```cpp
    // #include<cassert> // workaround
    #include<Magic++.h>
    void foo() { assert(true); }
```
or
```cpp
    #include<Magic++.h>
    #include <nlohmann/json.hpp>
```
causes this error
> clang: Use of undeclared identifier '__assert_fail'; did you mean 'MagickCore::__assert_fail'?
> gcc: ‘__assert_fail’ was not declared in this scope; did you mean ‘MagickCore::__assert_fail’?

**Comment by urban-warrior** [comment]
We incorrectly call assert() in two of the public header files.  We will fix this in the next release.  Any other conflicts must be handled on a case-by-case basis as wholesale changes might break existing code sets.
