### ISSUE TITLE
convert generates invalid png for tesseract

### ISSUE THREAD

**Issue by superbonaci** [ImageMagick/ImageMagick#4698]
### ImageMagick version

7.1.0.19

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

Using [imagemagick 7.1.0.19-1](https://archlinux.org/packages/extra/x86_64/imagemagick/) for Arch linux.
Convert pdf to png generates invalid png for [tesseract](https://github.com/tesseract-ocr/tesseract).

### Steps to Reproduce

Convert pdf file to png:
````
$ convert -density 900 file.pdf file.png
convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `file.png' @ warning/png.c/MagickPNGWarningHandler/1748.
````
Then try to scan it with tesseract:
````
$ tesseract file.png file.txt
Tesseract Open Source OCR Engine v4.1.1 with Leptonica
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 1119
````
Only works if I explicitly set dpi, which is undocumented:
````
$ tesseract --dpi 900 file.png file.txt
````

**Comment by superbonaci** [comment]
Related: https://github.com/tesseract-ocr/tesseract/issues/1702

**Comment by dlemstra** [comment]
Can you share the file `file.pdf` that can be used to reproduce this?

**Comment by superbonaci** [comment]
I don't have the pdf anymore, I think any png generated by tesseract does it, there's an example on mentioned issue.

**Comment by dlemstra** [comment]
This looks like a tesseract issue instead.
