### ISSUE TITLE
inkskape: prefix should not fall back to other methods

### ISSUE THREAD

**Issue by toolforger** [ImageMagick/ImageMagick#47]
If the user explicitly requests `inkscape:`, I think IM should assume that there's a reason why neither `rsvg:` nor `msvg:` were requested and report an error if Inkscape is not available.

See viewtopic.php?f=1&t=28416 for an example SVG where you wouldn't want MSVG.

**Comment by dlemstra** [comment]
There is no such thing as an inkscape: prefix. If you want to use inkscape you should edit your delegates.xml file and specify this.

**Comment by toolforger** [comment]
`identify -list formats` indeed does not list any inkscape format, just `SVG`.
That's strange, because `convert inkscape:foo.svg foo.png` works for me; I'd have expected IM to throw errors at me if I'm using an invalid prefix.

What I actually need is a way to make IM fail reading SVG is inkscape is not installed.

Either way I guess I'll close this issue and open a new, more specific one :-)

**Comment by toolforger** [comment]
Please reopen, there's yet no resolution to the question why the `inkscape:` prefix didn't error out.

**Comment by urban-warrior** [comment]
Explicit image formats (e.g. inkscape:) are hints.  in your example, inkscape:foo.svg hints that you might want to use a delegate tagged inkscape, however, since ImageMagick has a SVG coder, the delegates are never consulted, instead the SVG coder is called.
