### ISSUE TITLE
Animation FPS issues after conversion of APNG to WebP

### ISSUE THREAD

**Issue by SoftCreatR** [ImageMagick/ImageMagick#4704]
### ImageMagick version

7.1.0-19 Q16

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04

### Description

By converting an APNG file to WebP, the FPS rate drops noticeably and the animation is visibly slower than the original.

### Steps to Reproduce

```bash
magick -background white -dispose background APNG:butterfly.png -coalesce butterfly.webp
```

### Images

Original PNG:
![butterfly](https://user-images.githubusercontent.com/81188/149324520-e758431f-1da0-4c7d-9b98-4fb73a16fc9b.png)

Result WebP: [webp.zip](https://github.com/ImageMagick/ImageMagick/files/7862443/webp.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by SoftCreatR** [comment]
Seems to work, tyvm.
