### ISSUE TITLE
Exporting all alpha-channels

### ISSUE THREAD

**Issue by andrey-hider** [ImageMagick/ImageMagick#4735]
### ImageMagick version

7.1.0-19

### Operating system

MacOS

### Operating system, version and so on

macOS Monterey 12.1

### Description

I wasn't able to export more than one alpha channel.

### Steps to Reproduce

According to documentation: [separate](https://imagemagick.org/script/command-line-options.php#separate) and [channel](https://imagemagick.org/script/command-line-options.php#channel) there is an option to export image alpha channels with the CLI command:
`convert '/<path_to_file>/Alpha Masks Sample with 2 Alphas.tif' -separate -channel 4 /<path_to_file>/channels_%d.png`

As a result I've got only "Alpha 2" channel exported:
<img width="450" alt="Screenshot 2022-01-20 at 12 25 11" src="https://user-images.githubusercontent.com/30869869/150330024-83127b73-7338-411a-9bbc-a092137e3c81.png">
Result after CLI command:
<img width="300" alt="channels_3" src="https://user-images.githubusercontent.com/30869869/150330097-fdbe3553-07d6-4d1c-9173-fc04011b0f0d.png">

Is there a way to export also channel with the name "Numbers"?

### Images

[Alpha Masks Sample with 2 Alphas.zip](https://github.com/ImageMagick/ImageMagick/files/7904617/Alpha.Masks.Sample.with.2.Alphas.zip)

**Comment by dlemstra** [comment]
With the latest version of ImageMagick you will be able to extract that channel:

`magick "Alpha Masks Sample with 2 Alphas.tif"[0] -separate channels_%d.png`
