### ISSUE TITLE
PDF comparison shows no difference even if there are differences between files, fuzz value is set to 0 (-metric AE +fuzz)

### ISSUE THREAD

**Issue by mk654321** [ImageMagick/ImageMagick#4743]
### ImageMagick version

6.9.11-60

### Operating system

Linux

### Operating system, version and so on

Sparky Linux 6.1

### Description

No difference is being found when comparing 2 pdfs (fuzz value 0) even if there are visual differences.
Please find below 2 examples:
* doc1.pdf says "Test" doc2.pdf says "Test." (difference is a "full stop" character) 

### Steps to Reproduce

compare -metric AE +fuzz doc1.pdf doc2.pdf docdiff12.pdf

### Images

[doc1.pdf](https://github.com/ImageMagick/ImageMagick/files/7916468/doc1.pdf)
[doc2.pdf](https://github.com/ImageMagick/ImageMagick/files/7916469/doc2.pdf)

**Comment by fmw42** [comment]
Turn alpha off

```
compare -metric ae -alpha off  doc1.pdf doc2.pdf null:

5

```

**Comment by mk654321** [comment]
Thank you @fmw42 turning alpha on or turning alpha makes it behave as expected - compare recognises files are different.

I have found one more case where it says files are identical even if there are differences (comparing two 10x10 pdf files one white, one with black 1px horizontal line across):
```
compare -metric AE +fuzz -alpha off 1.pdf 3.pdf null:
0
```
```
compare -metric AE +fuzz -channel rgba 1.pdf 3.pdf null:
0
```

[1.pdf](https://github.com/ImageMagick/ImageMagick/files/7917388/1.pdf)
[3.pdf](https://github.com/ImageMagick/ImageMagick/files/7917389/3.pdf)

**Comment by fmw42** [comment]
I do not know how you produced 3.pdf. But if you remove the alpha and compare the alpha channel to the rgb channel images, you will see no stripe. Both images are completely white.

**Comment by snibgo** [comment]
According to Adobe Reader, 3.pdf is 0.1x0.1 inches. As documents go, that is small. When IM rasterizes it...
```
magick 3.pdf info:

3.pdf PDF 7x7 7x7+0+0 16-bit sRGB 159B 0.000u 0:00.108
```
... the result is 7x7 pixels. This is too small to show the black vector line.

**Comment by mk654321** [comment]
identify -verbose 3.bmp
```
Image:
  Filename: 3.bmp
  Format: BMP3 (Microsoft Windows bitmap image (V3))
  Class: DirectClass
  Geometry: 10x10+0+0
  Resolution: 37.8x37.8
  Print size: 0.26455x0.26455
  Units: PixelsPerCentimeter
  Colorspace: sRGB
  Type: Bilevel
  Base type: Undefined
  Endianness: Undefined
  Depth: 8/1-bit
  Channel depth:
    red: 1-bit
    green: 1-bit
    blue: 1-bit
  Channel statistics:
    Pixels: 100
    Red:
      min: 0  (0)
      max: 255 (1)
      mean: 229.5 (0.9)
      standard deviation: 76.8854 (0.301511)
      kurtosis: 4.9497
      skewness: -2.62677
      entropy: 0.468996
    Green:
      min: 0  (0)
      max: 255 (1)
      mean: 229.5 (0.9)
      standard deviation: 76.8854 (0.301511)
      kurtosis: 4.9497
      skewness: -2.62677
      entropy: 0.468996
    Blue:
      min: 0  (0)
      max: 255 (1)
      mean: 229.5 (0.9)
      standard deviation: 76.8854 (0.301511)
      kurtosis: 4.9497
      skewness: -2.62677
      entropy: 0.468996
  Image statistics:
    Overall:
      min: 0  (0)
      max: 255 (1)
      mean: 229.5 (0.9)
      standard deviation: 76.8854 (0.301511)
      kurtosis: 5.05713
      skewness: -2.65334
      entropy: 0.468996
  Colors: 2
  Histogram:
    10: (0,0,0) #000000 black
    90: (255,255,255) #FFFFFF white
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33)
    green primary: (0.3,0.6)
    blue primary: (0.15,0.06)
    white point: (0.3127,0.329)
  Background color: white
  Border color: srgb(223,223,223)
  Matte color: grey74
  Transparent color: black
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 10x10+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: None
  Orientation: Undefined
  Properties:
    date:create: 2022-01-22T02:06:13+00:00
    date:modify: 2022-01-21T20:13:57+00:00
    signature: 1c868539d3956d2c4848e570b8ca780e9ce6ff2ed937b6532e5fc3aa1ee32e91
  Artifacts:
    filename: 3.bmp
    verbose: true
  Tainted: False
  Filesize: 374B
  Number pixels: 100
  Pixels per second: 593535B
  User time: 0.000u
  Elapsed time: 0:01.000
  Version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org

```

**Comment by snibgo** [comment]
Okay, so your 3.pdf contains a raster image. IM tells Ghostscript to rasterize each page at whatever density is specified. For example, "magick -density 300 3.pdf x.png". Larger densities will give larger images (ie more pixels).

If you know your pdf contains just raster images, with one raster image per PDF page, I suggest using pdfimages. This will extract just the raster images from the PDF, and you don't need to specify a density. Aside from compression, the resulting raster images should be exactly the same as the raster images you put into the PDF, at the same size.

**Comment by mk654321** [comment]
1.pdf and 3.pdf were my attempts to minimize the scenario, not a real life example. I was interested why missing "full stop" wasn't detected as a difference. It looks, however I didn't know I should turn on or off alpha.
Thank you very much for detailed explanation.

**Comment by fmw42** [comment]
There are subtle issues when using transparent image and -metric AE as discussed at https://legacy.imagemagick.org/Usage/compare/#statistics. However, I do not understand why one has to deal with -alpha off or -channel rgba, since the RGB channels and the alpha channel were identically different. Perhaps one of the developers might be able to explain why it sees them as identical by default. I do not think that issue was resolution. I tried increasing the density of the PDFs but still got identical results from -metric AE.
