### ISSUE TITLE
Animations broken after conversion of APNG to WebP

### ISSUE THREAD

**Issue by SoftCreatR** [ImageMagick/ImageMagick#4746]
### ImageMagick version

7.1.0-20 Q16

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04

### Description

By converting an APNG file to WebP, the animations break on many images.

### Steps to Reproduce

```bash
magick -background white -dispose background APNG:clock.png -coalesce clock.webp
magick -background white -dispose background APNG:bottle_with_popping_cork.png -coalesce bottle_with_popping_cork.webp
```

### Images

Original PNG:

![clock@2x](https://user-images.githubusercontent.com/81188/150668257-c50f70df-d8cc-4d6e-9bf4-7c44169ce03a.png) ![bottle_with_popping_cork](https://user-images.githubusercontent.com/81188/150668325-45bff3bc-bd15-4ffb-91c1-ae2ff53f7557.png)

Result WebP: 

[clock.zip](https://github.com/ImageMagick/ImageMagick/files/7919965/clock.zip)
[bottle_with_popping_cork.zip](https://github.com/ImageMagick/ImageMagick/files/7919968/bottle_with_popping_cork.zip)

**Comment by urban-warrior** [comment]
While we investigate, add `-define video:intermediate-format=pam` to your command-line (before APNG:).

**Comment by SoftCreatR** [comment]
Looks like that did the trick, ty.
