### ISSUE TITLE
X3F conversion fails

### ISSUE THREAD

**Issue by mironych** [ImageMagick/ImageMagick#4753]
### ImageMagick version

7.1.0-20

### Operating system

Windows

### Operating system, version and so on

Windows 10 Pro, 10.0.19044

### Description

Conversion of X3F file fails even it's listed in the supported formats. Tried with different files, same result.

```
magick identify -verbose RAW_SIGMA_SD9_SRGB.X3F
> identify: Unsupported file format or not RAW file `.\RAW_SIGMA_SD9_SRGB.X3F' @ error/dng.c/ReadDNGImage/480.
```
```
dcraw -i RAW_SIGMA_SD9_SRGB.X3F
> RAW_SIGMA_SD9_SRGB.X3F is a Sigma SD9 image.
```

### Steps to Reproduce

```
magick RAW_SIGMA_SD9_SRGB.X3F RAW_SIGMA_SD9.jpg
> magick.exe: Unsupported file format or not RAW file `RAW_SIGMA_SD9_SRGB.X3F' @ error/dng.c/ReadDNGImage/480.
```

### Images

[RAW_SIGMA_SD9_SRGB.zip](https://github.com/ImageMagick/ImageMagick/files/7933533/RAW_SIGMA_SD9_SRGB.zip)

**Comment by snibgo** [comment]
"X3F" is probably used by Sigma for different files created by different models of camera, and these files can be different. Software that successfully reads files from one model may not read files from another.

IM v7.0.1-20 can read your X3F when it uses ufraw-batch to read the file.

A version of libraw can read your file.

Pre-built IM 7.1.0-4 that uses libraw can't read your file. So, perhaps that pre-built IM doesn't use the latest libraw. A developer may comment on this.

You might test whether you have ufraw-batch. If you do, can it read your file? If it can, you might adjust delegate.xml to use it.

**Comment by mironych** [comment]
>You might test whether you have ufraw-batch. If you do, can it read your file? If it can, you might adjust delegate.xml to use it.
no, I don't have it

```
 magick -verbose RAW_SIGMA_SD9_SRGB.X3F RAW_SIGMA_SD9.jpg
> magick.exe: Unsupported file format or not RAW file `RAW_SIGMA_SD9_SRGB.X3F' @ error/dng.c/ReadDNGImage/480.
```

**Comment by dlemstra** [comment]
We are using the libraw library and support for X3F is disabled by default. You can find more info about this here: https://www.libraw.org/download#stable (scroll down to `Imported code policy disclaimer`)
