### ISSUE TITLE
Adding an image layer to a .psd is rasterizing every other layer

### ISSUE THREAD

**Issue by kerngebiet-digital** [ImageMagick/ImageMagick#4754]
### ImageMagick version

ImageMagick 6.9.10-23 Q16 x86_64 20190101

### Operating system

Linux

### Operating system, version and so on

Linux on Hosted Server

### Description

Hi,
we want to add an image to an existing psd. Problem ist that all the other Text layers are rasterized and not editable in PS anymore.

`'convert "test.psd" -label "Added" test.png out.psd'`

Regards 
Chris 

### Steps to Reproduce

Reproduce by using a psd with text layers and adding an image to it.

**Comment by fmw42** [comment]
I do not think ImageMagick is the tool for this.

**Comment by snibgo** [comment]
> It should add the image without touching the text layers.

But that isn't what IM does, or is designed to do.

In your command...
```
convert "test.psd" -label "Added" test.png out.psd
```
... IM will read all the images, as raster images. Then it will write them all out to a single file, "out.psd".
