### ISSUE TITLE
In some cases thumbnail will "upsample" the image resulting in worse performance than resize

### ISSUE THREAD

**Issue by pglizniewicz** [ImageMagick/ImageMagick#4761]
### ImageMagick version

7.1.0-20

### Operating system

Linux

### Operating system, version and so on

Rocky Linux 8.5

### Description

`ThumbnailImage()` in [resize.c](https://github.com/ImageMagick/ImageMagick/blob/main/MagickCore/resize.c) uses some questionable logic to choose whether to sample the image or not. The condition `(x_factor*y_factor) > 0.1` is false for example when making a thumbnail of size 1000x1000 from an image of size 4000x4000 (`x_factor` and `y_factor` are `0.25`). This results in a call to `SampleImage` with dimensions 5000x5000 resulting in a bigger image to `ResizeImage`. This results in `-thumbnail` taking up to twice as much time compared to `-resize`.

### Steps to Reproduce

* Take a large, square image (like 4000x4000)
* Make a square `-thumbnail` with dimensions between 800 and 1250
* Compare it to `-resize` with the same dimensions

It's especially visible, when the target to source dimension ratio is close below sqrt(0,1) (1250 in the case of the above example) - on my machine `-thumbnail` will be 2 times slower than `-resize` in such case.

The original topic with a simple benchmark is here: [thumbnail discussion](https://github.com/ImageMagick/ImageMagick/discussions/4755)

**Comment by urban-warrior** [comment]
A thumbnail utilizes a heuristic and like many heuristics, its not always the optimal solution.   We have a different solution that focuses on perceived image quality rather than speed.  We will update the documentation to reflect this new focus.

**Comment by pglizniewicz** [comment]
Am I understanding this right, will `-thumbnail` now use the same method for resizing as `-distort Resize`?

**Comment by urban-warrior** [comment]
We take another approach.  We sample down to 4x, then use a box filter to 2x, then use a LanzcosSharp for the final size.  In most cases, that should be optimal for speed against a tradeoff of image quality.
