### ISSUE TITLE
MATLAB Image parser broken

### ISSUE THREAD

**Issue by wamserma** [ImageMagick/ImageMagick#4766]
### ImageMagick version

7.1.0-20

### Operating system

Linux

### Operating system, version and so on

nixos-21.11.335481.604c44137d9

### Description

https://github.com/ImageMagick/ImageMagick/commit/075565e93c71bcaaabf0ce70b7d1060bccdf0020

triggers a test failure in PerlMagick

please see https://github.com/NixOS/nixpkgs/issues/156826 and https://github.com/NixOS/nixpkgs/pull/156920 for more info.

### Steps to Reproduce

Assuming [nix](https://nixos.org/download.html) is installed:

```sh
# succeeds (includes revert of 075565e93c71bcaaabf0ce70b7d1060bccdf0020)
nix-build -A perlPackages.ImageMagick  https://github.com/wamserma/nixpkgs/archive/9bb48e7edb4b7e132491ea77480490f0ef695ad7.tar.gz
# fails (unmodified checkout)
nix-build -A perlPackages.ImageMagick  https://github.com/wamserma/nixpkgs/archive/61a3b954644a2ba0b6d5d4578d080cad37e170ac.tar.gz
```

### Images

-none-

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by wamserma** [comment]
Thank you for the quick reply. This fixes the downstream build issue.
