### ISSUE TITLE
generated pdf with non-ascii name does not show correct title

### ISSUE THREAD

**Issue by dymn** [ImageMagick/ImageMagick#4771]
### ImageMagick version

7.1.0.20

### Operating system

Linux

### Operating system, version and so on

Gentoo, Ubuntu 21.10

### Description

I use imagemagick to convert one or more jpg images to a PDF file that has a non-ascii filename: `convert *.jpg анализы.pdf`

When I open the resulting анализы.pdf with evince or qpdfview, the window title bar displays strange characters "0=0;87K" instead of "анализы". It is as if convert saves the title of the document in a different encoding than expected by pdf.

The special decoding [service](https://www.artlebedev.ru/decoder/)  gives the following result if you put these characters "0=0;87K" there: 7-bit ASCII -> ISO-8859-5.

Everything works fine in ImageMagick 6.

### Steps to Reproduce

Convert image or images to pdf with convert using non-ascii characters as file name: `convert *.jpg анализы.pdf`

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dymn** [comment]
This patch does not work correctly.
Evinсe - no title.
Qpdfview - wrong encoding.
Mupdf - wrong encoding.

**Comment by dlemstra** [comment]
Can you check this again with the next release. We will probably release that this weekend.
