### ISSUE TITLE
ImageMagick 7.1.0-21 not released on GitHub

### ISSUE THREAD

**Issue by vedantmgoyal2009** [ImageMagick/ImageMagick#4777]
### Describe the solution you'd like

Hi there,

I'm maintainer of [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation), a project that updates the manifests which are used by Windows Package Manager (WinGet) at [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs). I found that you publish ImageMagick Releases on GitHub, so, I added the package in the automation which queries GitHub Releases API, get the latest releases tag and generate version number and download links of the binaries.

This time I found that the version got updated at https://download.imagemagick.org/ImageMagick/download/binaries/ but not on GitHub. I just want that please try to keep both GitHub releases and binaries at download sever in sync or if you have any API which can return latest version of ImageMagick (plus the download links of binaries), it will helpful for the automation to keep the package up-to-date at [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs).

**Comment by dlemstra** [comment]
This is not an automated process and it can sometimes take a couple days before we add the tag. See also #4633.
