### ISSUE TITLE
cannot open source file "MagickCore/version.h" and cannot open source file "MagickCore/magick-baseconfig.h" on Visual studio

### ISSUE THREAD

**Issue by siladrenja** [ImageMagick/ImageMagick#4778]
### ImageMagick version

IDK, latest one on this repo at the time I'm writing

### Operating system

Windows

### Operating system, version and so on

Win10 pro Build 19041.1052

### Description

I downloaded the repo, and imported it to visual studio 2019, and added the root folder of the repo, and also the lib folder to additional libraries, made a basic script to test out, and pressed compile to which I got bunch of errors. Most of them are that the global scope has no ssize_t, but 2 errors pose me more problems:

cannot open source file "MagickCore/version.h"
****

### Steps to Reproduce

Already said in Description

**Comment by urban-warrior** [comment]
`Magickcore/version.h` exists in the source distribution.  Find it and add it as a path in your VisualStudio configuration.

**Comment by dlemstra** [comment]
Build instructions for Windows can be found here: https://github.com/ImageMagick/ImageMagick-Windows.
