### ISSUE TITLE
DrawSetTextInterwordSpacing bogus code

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#478]
[This line](https://github.com/ImageMagick/ImageMagick/blob/7fcca7ff26c0579f3010222b9a44063ba0b45182/MagickWand/drawing-wand.c#L6123) in DrawSetTextInterwordSpacing appears bogus. It should either be calling fabs for `CurrentContext->interword_spacing-interword_spacing` or it could be safer to do it as it's done for the [ImageMagick 6 branch](https://github.com/ImageMagick/ImageMagick/blob/01d522e990aa57cbe67d222dd5e8f7196cc6d199/wand/drawing-wand.c#L6129), where it is a direct comparison without epsilon.

Currently, the code won't work if the new interword_spacing is greated than the old interword_spacing.

This was reported downstream at:

https://github.com/mkoppanen/imagick/issues/206
https://bugs.php.net/bug.php?id=72438

**Comment by Danack** [comment]
The same pattern appears to be affecting [DrawSetTextKerning](https://github.com/ImageMagick/ImageMagick/blob/7fcca7ff26c0579f3010222b9a44063ba0b45182/MagickWand/drawing-wand.c#L6041) and [DrawSetTextInterlineSpacing](https://github.com/ImageMagick/ImageMagick/blob/7fcca7ff26c0579f3010222b9a44063ba0b45182/MagickWand/drawing-wand.c#L6082) .

**Comment by KevinGregull** [comment]
I can confirm that changing the Line to the following does work and fix the Problem:

`if ((wand->filter_off != MagickFalse) &&
      (CurrentContext->interline_spacing!=interline_spacing))
    {`

**Comment by KevinGregull** [comment]
Seeing how they chose to use the Delta Value, I think using the absolute difference is a better solution here.
Created a Pull Request for the change.

**Comment by KevinGregull** [comment]
Thank you for spotting the error @Danack. Fix applied, this Issue can be closed.

**Comment by dlemstra** [comment]
Your changes have been merged and will be available in the next release.
