### ISSUE TITLE
Incorrect result when converting multiple jpg files to a single pdf

### ISSUE THREAD

**Issue by taroxd** [ImageMagick/ImageMagick#479]
OS: Windows 10 Build 15063 / 16188  (both failed)
Windows Binary Release: ImageMagick-7.0.5-5-Q16-x64-dll.exe / ImageMagick-7.0.5-5-portable-Q16-x64.zip (both failed)

I tried the command `magick convert sky.jpg sky.jpg output.pdf` and get an incorrect result.
Here are the `sky.jpg` I have used and the `output.pdf` which ImageMagick has output.

sky.jpg: [sky.jpg](https://cloud.githubusercontent.com/assets/6070540/25781468/56d84cb4-336d-11e7-9003-33493723e36e.jpg)
output.pdf: [output.pdf](https://github.com/ImageMagick/ImageMagick/files/981605/output.pdf)

Screenshot of the incorrect output.pdf: 
![snipaste20170507_213436](https://cloud.githubusercontent.com/assets/6070540/25781502/a443a976-336d-11e7-8f13-13635ea4f262.png)

It can be seen on the screenshot that the second page is not displayed properly.

It seems that the bug was introduced in recent update, because everything was fine in 7.0.4

**Comment by dlemstra** [comment]
This is most likely caused by #417. We are working on fixing that.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
