### ISSUE TITLE
convert: pixel cache allocation failed when getting layers from psd

### ISSUE THREAD

**Issue by ingolfured** [ImageMagick/ImageMagick#48]
Hi guys

With most of the psd I'm working with, when I run

    convert file.psd file_%d.jpg

It gives me the following error:

    convert: pixel cache allocation failed `file.psd' @ error/cache.c/OpenPixelCache/3560.
    convert: memory allocation failed `file.psd' @ error/psd.c/ReadPSDChannel/1094.
    convert: no images defined `file_%d.jpg' @ error/convert.c/ConvertImageCommand/3230.

I get the following version when I run `convert -version`

    Version: ImageMagick 6.9.2-0 Q16 x86_64 2015-08-18 http://www.imagemagick.org
    Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
    License: http://www.imagemagick.org/script/license.php
    Features: Cipher DPC HDRI Modules OpenCL OpenMP 
    Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms lqr ltdl lzma pangocairo png ps rsvg tiff webp wmf x xml zlib

Any ideas?

**Comment by dlemstra** [comment]
Does your PSD file have a negative offset? Then it is probably the same issue as reported here: http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=28461. Otherwise you might want to upgrade to 6.9.2-4 and test if you can reproduce the issue with that version.

**Comment by ingolfured** [comment]
Alright, I tried to update to the following

    Version: ImageMagick 6.9.2-4 Q16 x86_64 2015-10-20 http://www.imagemagick.org
    Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
    License: http://www.imagemagick.org/script/license.php
    Features: Cipher DPC Modules OpenCL OpenMP 
    Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff webp wmf x xml zlib

and getting the same error.

    convert: pixel cache allocation failed `file.psd' @ error/cache.c/OpenPixelCache/3559.
    convert: memory allocation failed `file.psd' @ error/psd.c/ReadPSDChannel/1094.
    convert: no images defined `file_%d.jpg' @ error/convert.c/ConvertImageCommand/3230.

Is version 7 stable enough to be worth the try?

**Comment by dlemstra** [comment]
What is the output from `identify file.psd`?

You can use version 7 but we are still making API changes at the moment. The C# Api (Magick.NET) has been using version 7 for over a year now without a lot of issue.

**Comment by ingolfured** [comment]
The output from `identify file.psd` is
   
    file.psd[0] PSD 768x1004 768x1004+0+0 8-bit sRGB 5.893MB 0.000u 0:00.000
    file.psd[1] PSD 1360x1446 1360x1446-199-414 8-bit sRGB 5.893MB 0.000u 0:00.000
    file.psd[2] PSD 549x103 549x103+148+178 8-bit sRGB 5.893MB 0.000u 0:00.000
    file.psd[3] PSD 96x132 96x132+34+76 8-bit sRGB 5.893MB 0.000u 0:00.000
    file.psd[4] PSD 512x46 512x46+126+354 8-bit sRGB 5.893MB 0.000u 0:00.000
    file.psd[5] PSD 136x127 136x127+312+608 8-bit sRGB 5.893MB 0.000u 0:00.000

However, I built ImageMagick 6.9.2-5 and it solved the issue. Thanks so much for your assistance!
