### ISSUE TITLE
Large slow down for commit 1496901aea4d6de5bc5c1051a423e95a80d77995

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#4807]
### ImageMagick version

ImageMagick-7.1.0-21

### Operating system

Linux

### Operating system, version and so on

Debian 11

### Description

One of the users of Imagick reported a large slowdown from commit 1496901aea4d6de5bc5c1051a423e95a80d77995 onwards.

Originally reported at https://github.com/Imagick/imagick/issues/538 their test script takes about 30 times longer after that commit than before. 

I can't see an issue with that commit, but checking with callgrind `valgrind --tool=callgrind php slow.php` I can see that the number of instructions executed:

```
Before:    229,083,423
After:  10,757,761,446
```

So....there's definitely a lot more work being done, which probably wasn't intended.

### Steps to Reproduce

This script that draws 10000 points 

```
<?php

\define('TEST_START', microtime(true));

$draw = new \ImagickDraw();
$draw->setFillColor('#000000');

for ($x = 0; $x < 10000; $x++) {
    $draw->point(rand(0, 500), rand(0, 500));
}

$imagick = new \Imagick();
$imagick->newImage(500, 500, new \ImagickPixel('#ffffff'));
$imagick->setImageFormat('png');
$imagick->drawImage($draw);

echo number_format((microtime(true) - TEST_START), 2) . "\n";
```

**Comment by urban-warrior** [comment]
Yikes!  Investigating now...

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
