### ISSUE TITLE
Hard work to build library for mac app 

### ISSUE THREAD

**Issue by liufsd** [ImageMagick/ImageMagick#481]
http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=13145&sid=78ffac2e012bbe45f91af34c47c5945f&start=15

Need some build script files and demo Xcode project.

Thanks.

**Comment by dlemstra** [comment]
Answer here: http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=13145&start=15#p139258
