### ISSUE TITLE
MagickCore/Magick++: WebP images are identified as VIDEO

### ISSUE THREAD

**Issue by reima** [ImageMagick/ImageMagick#4819]
### ImageMagick version

7.1.0-23 Q8 x64

### Operating system

Windows

### Operating system, version and so on

Windows 10 21H2 (Build 19044.1466)

### Description

I'm using the Magick++ API to read images.

My program reads multiple files one after another. When both videos in the RIFF container format (e.g. AVI) and WebP images are part of the files being processed, the order of processing influences if the WebP images are identified as such.

When the first file being read is a WebP file, all following WebP files and AVI files are identified correctly as WEBP and VIDEO respectively.

But when the first file being read is an AVI file, all following WebP files are misidentified as VIDEO instead of WEBP. Depending on the configured delegates, this may lead to WebP images not being readable anymore.

I investigated this behavior in some depth and believe I have identified the issue:

* WebP images are RIFF containers.
* Therefore *both* the VIDEO header https://github.com/ImageMagick/ImageMagick/blob/cadfcdd11829197ed415177ef00a61921add7345/coders/video.h#L21 *and* the WEBP header https://github.com/ImageMagick/ImageMagick/blob/cadfcdd11829197ed415177ef00a61921add7345/coders/webp.h#L20 match on WebP images.
* When a file with the RIFF header (but without the WEBP header) is read first, `GetMagicInfo` inserts the matching VIDEO `MagicInfo` into the `magic_cache`.
  * When a WebP file is read after that, `GetMagicInfo` first consults the `magic_cache`. The VIDEO `MagicInfo` from the RIFF file is present there, and it matches on the WebP file, so it is returned without consulting the `magic_list`.
  * The WebP file has now been identified as VIDEO :x:
* When a WebP file is read first, `GetMagicInfo` inserts the matching WEBP `MagicInfo` into the `magic_cache`.
  * When a file with the RIFF header (but without the WEBP header) is read after that, `GetMagicInfo` consults the `magic_cache`. The WEBP `MagicInfo` is present there, but does not match. The VIDEO `MagicInfo` from the `magic_list` *does* match and is inserted into the `magic_cache` and returned. The important part is that the `magic_cache` is ordered in such a way that the WEBP info is always *before* the VIDEO info.
  * When another WebP file is read after that, the WEBP `MagicInfo` in the `magic_cache` is encountered first, and is returned ✔️

The bug has first appeared in 7.0.8-13 in commit https://github.com/ImageMagick/ImageMagick/commit/44b1a1bb, where the RIFF header definition was introduced (in `mpeg.h`).

As far as I can tell this bug affects all versions since then on all platforms.

### Steps to Reproduce

The following Magick++ program loads the AVI video and WebP image in different orders (uncomment the scenario to run and comment the other one):

```cpp
#include <Magick++.h>
#include <iostream>

using namespace std;
using namespace Magick;

void ReadImage(const char* path)
{
    cout << path << endl;

    try
    {
        Image image;
        image.ping(path);
        cout << "Success: " << image.format() << endl;
    }
    catch (Exception &error)
    {
        cout << "Error: " << error.what() << endl;
    }
}

int main(int argc, char **argv)
{
    InitializeMagick(*argv);

    // Scenario 1: AVI before WebP (triggers the bug)
    ReadImage("video.avi");
    ReadImage("logo.webp");

    // Scenario 2: WebP before AVI (works)
    //ReadImage("logo.webp");
    //ReadImage("video.avi");
    //ReadImage("logo.webp");
}
```

The bug can also be triggered with IMDisplay.exe by loading the files in the specific order.

### Images

See [files.zip](https://github.com/ImageMagick/ImageMagick/files/8019537/files.zip) for sample files.

Note that the `video.avi` file is not an actual AVI video, but just contains the four bytes `RIFF`. This is the minimal file that triggers the behavior.

**Comment by dlemstra** [comment]
Thanks for the detailed report. This header was already checked earlier and would identify the image as an AVI file. We removed this header from the `video.h` header file to avoid issues. This will be resolved in the next release.
