### ISSUE TITLE
Windows Installer option ImageMagickObject is missing

### ISSUE THREAD

**Issue by marcoklemm** [ImageMagick/ImageMagick#4820]
### ImageMagick version

7.1.0-23-Q16-HDRI-x64-dll

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

Hi there,
I could not install ImageMagickObject, because the option is not visible in the windows installer. Please see the steps and screenshots below. Using an old binary worked (ImageMagick-7.0.7-27-Q16-x64-dll.exe).
Thanks!
Marco 

### Steps to Reproduce

1. Start the installer ImageMagick-7.1.0-23-Q16-HDRI-x64-dll.exe
2. Navigate to the "Select additional tasks"
3. See that the option is not visible. Please see screenshot

### Images

![image](https://user-images.githubusercontent.com/1312054/152939308-3983db02-c6c3-4da5-9aa2-b7f5758ac5b9.png)

**Comment by dlemstra** [comment]
We stopped supporting this and that it why it has been removed from the installer.

**Comment by dlemstra** [comment]
You can no longer access the API but maybe you can execute something on the command line? I haven't worked in VB for ages. Maybe you will need to upgrade your project to something more modern (.NET).

**Comment by marcoklemm** [comment]
That would be a good idea. However, I use it within a Powerpoint VBA-macro for creating images of slides. For now, it is okay for me to use an older version of ImageMagick. Thanks again for clarifying!

**Comment by dlemstra** [comment]
You will need to rewrite your application. COM support is gone and will stay gone.

**Comment by mwolfe02** [comment]
I think dropping that support would, at the least, require a major version change from 7.x to 8.x under semantic versioning.

**Comment by dlemstra** [comment]
This is something that was an addition to ImageMagick and not part of the core library so we dont need to make any version bumps.

**Comment by mwolfe02** [comment]
Got it. Thanks for the explanation.

Are there any Windows binaries still available from the last release that included the object or would I need to build from source?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SylvainGino** [comment]
Maybe you find an older version of ImageMagick with ImageMagickObject OLE Control on this page : https://legacy.imagemagick.org/script/download.php

**Comment by mwolfe02** [comment]
Thanks for the link, @SylvainGino.  I was hoping to find a Windows binary for the last version 7.x release that included the COM object, which appears to be **version 7.1.0-19**.  It doesn't appear that those earlier minor versions of 7.1.0 are available as pre-compiled binaries (only the latest release seems to have pre-compiled binaries).

**Comment by SylvainGino** [comment]
I could not find any version 7 binaries with ImageMagickObject OLE Control.
I finally found some 4-year-old version 6 binaries with ImageMagickObject OLE Control at this address : https://sourceforge.net/projects/imagemagick/files/im6-exes/

**Comment by mwolfe02** [comment]
Thanks for your efforts, @SylvainGino.  Long term, I plan to recreate the COM object's functionality with a VBA class module that builds and executes calls to the ImageMagick executable, or possibly a replacement COM object using twinBASIC.

If I do eventually get to either of those things, I will write about it on my daily Access/VBA blog, nolongerset.com.  You will be able to find any future articles related to ImageMagick using the following URL: https://nolongerset.com/?ss360Query=ImageMagick
