### ISSUE TITLE
Text color is invalid, while other colors are valid in conversion PDF to PNG

### ISSUE THREAD

**Issue by matisiekpl** [ImageMagick/ImageMagick#4821]
### ImageMagick version

7.1.0-22

### Operating system

MacOS

### Operating system, version and so on

macOS 12.2

### Description

Hello.
I'm going to convert PDF file to separate PNG files.
Command:
```bash
convert -density 150 -colorspace RGB input.pdf output.png
```
Unfortunately, the white text in PDF is converted to Grey in PNG.
![image](https://user-images.githubusercontent.com/21008961/153005453-bd6bc02b-c33b-4205-9b04-99c4764266f5.png)
![image](https://user-images.githubusercontent.com/21008961/153005503-4aea6331-a6f3-4110-a477-d8285693b41c.png)

Thanks,
Mateusz Woźniak

### Steps to Reproduce

[input.pdf](https://github.com/ImageMagick/ImageMagick/files/8024543/input.pdf)
```bash
convert -density 150 -colorspace RGB input.pdf output.png
```

**Comment by fmw42** [comment]
try using -colorspace sRGB not -colorspace RGB

**Comment by matisiekpl** [comment]
@fmw42 Same result

**Comment by dlemstra** [comment]
This might be related to the ghostcript version? I cannot reproduce your issue with the latest version of Ghostscript and ImageMagick on Windows.

**Comment by fmw42** [comment]
It works fine for me on IM 6.9.12-52 Q16 Mac OSX Monterey with Ghostscript 9.55.0. Note your image is already sRGB so I just ran:

`convert -density 150 input.pdf output.png`

Here is one PNG page result:

![output-0](https://user-images.githubusercontent.com/13458218/173133903-a9f44dc2-7ad9-497f-9b88-e1b5a5db2429.png)
