### ISSUE TITLE
Tests fail on perl built with quadmath

### ISSUE THREAD

**Issue by Tux** [ImageMagick/ImageMagick#4822]
### ImageMagick version

7.1.0-19

### Operating system

Linux

### Operating system, version and so on

openSUSE Leap 15.3

### Description

```
This is perl 5, version 34, subversion 0 (v5.34.0) built for x86_64-linux-thread-multi-quadmath
```
```
Image-Magick-7.0.11-0 511 > prove -vbt t/getattribute.t
t/getattribute.t ..
1..25
ok 1
ok 2
ok 3
ok 4
ok 5
ok 6
ok 7
Expected (0.454545), Got (0.454544999999999976836306814220734)
not ok 8
ok 9
ok 10
ok 11
ok 12
ok 13
ok 14
ok 15
ok 16
ok 17
ok 18
ok 19
ok 20
ok 21
ok 22
ok 23
ok 24
ok 25
Failed 1/25 subtests

Test Summary Report
-------------------
t/getattribute.t (Wstat: 0 Tests: 25 Failed: 1)
  Failed test:  8
Files=1, Tests=25,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.01 cusr  0.01 csys =  0.04 CPU)
Result: FAIL
```

### Steps to Reproduce

```
$ perl Makefile.PL
$ make
$ make test
```

**Comment by urban-warrior** [comment]
Can you check the commit posted here?  Does it fix the problem?  If not, post instructions on how to enable Perl's quadmath so we can attempt to reproduce the problem locally and seek a proper fix.  Thanks.

**Comment by urban-warrior** [comment]
We cannot reproduce the problem but we have a quick fix... use a whole number for gamma.  We'll commit a patch to fix the problem soon.  Thanks for alerting us to the issue.
