### ISSUE TITLE
Tag 7.1.0-24 missing

### ISSUE THREAD

**Issue by dotlambda** [ImageMagick/ImageMagick#4836]
### ImageMagick version

7.1.0-24

### Operating system

Other (enter below)

### Operating system, version and so on

any

### Description

There is no tag `7.1.0-24` on GitHub.

### Steps to Reproduce

https://github.com/ImageMagick/ImageMagick/releases

**Comment by dotlambda** [comment]
@dlemstra Why was this closed? There is still no 7.1.0-24 on https://github.com/ImageMagick/ImageMagick/releases while that version can be downloaded from https://imagemagick.org/script/download.php.

**Comment by dlemstra** [comment]
See other issues/ discussiond about tags to get an answer to your question.
