### ISSUE TITLE
Incontinuity in straight segment of polyline

### ISSUE THREAD

**Issue by gergely-elias** [ImageMagick/ImageMagick#4837]
### ImageMagick version

6.9.10-23

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04

### Description

Polyline command produces segments which have missing pixels. See the image which was created by the command below.

![polyline](https://user-images.githubusercontent.com/4532150/153751315-39475ef1-b357-4566-b67f-80e5074b11fe.png)

### Steps to Reproduce

The command:
```
convert -size 33x173 xc:black -fill red -stroke white -draw 'polyline 1,171 1,15 31,15 31,7 21,7 21,17' polyline.png
```
produces the image I attached above, on which the white segment on the left has a black pixel around the center.
The problem does not appear if I move that segment to the right (it might to do with the segment being close to the edge of the image?), or if I remove other segments of the polyline.

**Comment by urban-warrior** [comment]
`polyline 1,171 1,15.000000000001 31,15 31,7 21,7 21,17` works which suggests numerical instability-- but at the same time, we get correct results if threads are set to 1.   Add `-limit thread 1` to your command-line until we can commit a proper patch.

**Comment by gergely-elias** [comment]
Thanks for confirming and for the workaround!

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
