### ISSUE TITLE
ImageMagick returning size of last gif frame only

### ISSUE THREAD

**Issue by Muffinman** [ImageMagick/ImageMagick#4842]
### ImageMagick version

6.9.11-60

### Operating system

Linux

### Operating system, version and so on

Ubuntu 21.10

### Description

Hi, I've been debugging an issue with our Drupal 9 site incorrectly resizing some gifs, and I believe I have tracked this back to ImageMagick reporting an incorrect width / height for the gifs.

ref. https://github.com/Imagick/imagick/issues/539

This ultimately comes from ImageMagick's `MagickGetImageWidth` / `MagickGetImageHeight` functions called [here](https://github.com/Imagick/imagick/blob/master/imagick_class.c#L6699).

It seems that `MagickGetImageWidth` / `MagickGetImageHeight` return the size of the last gif frame only? Is this expected behaviour?

I had thought the work-around of calling `coalesce` first would work for me, but it seems that `gif2webp` (which is run next in the optimisation pipeline) also exhibits the same behaviour, so I was wondering if there's an issue with some underlying library which is causing this?

Any input/advice is greatly appreciated.

### Steps to Reproduce

Attempt to read width / height of gif containing multiple animation frames of different sizes.

I used PHP / Imagick, but I believe calling `MagickGetImageWidth` / `MagickGetImageHeight` directly would exhibit the same behavior.

```php
<?php
$image = new Imagick();
$image->readImage("/home/matt/Desktop/3-stylish-men-xmas.gif");
var_dump($image->getImageGeometry());
```

```sh
 $ ~/Desktop  php test.php
array(2) {
  ["width"]=>
  int(375)
  ["height"]=>
  int(452)
}
```

This reports the image is `375x452 px` when it's actually `800x550 px`.

### Images

![3-stylish-men-xmas](https://user-images.githubusercontent.com/1319568/153860843-9759906e-ef61-4fa5-a803-0f928b8a33c1.gif)

```
 ~/Desktop  identify 3-stylish-men-xmas.gif
3-stylish-men-xmas.gif[0] GIF 800x550 800x550+0+0 8-bit sRGB 256c 0.000u 0:00.000
3-stylish-men-xmas.gif[1] GIF 376x458 800x550+3+59 8-bit sRGB 256c 0.000u 0:00.000
3-stylish-men-xmas.gif[2] GIF 353x466 800x550+26+59 8-bit sRGB 256c 0.000u 0:00.000
3-stylish-men-xmas.gif[3] GIF 375x452 800x550+3+59 8-bit sRGB 256c 459138B 0.000u 0:00.000
```

**Comment by snibgo** [comment]
> It seems that MagickGetImageWidth / MagickGetImageHeight return the size of the last gif frame only? Is this expected behaviour?

MagickGetImageWidth returns one value, which is the width of only one of the images in the list. (Similarly for height.)

From your "identify" listing, the final image has a width of 375 pixels, on a canvas of width 800.

Your php is reporting 375 for array(2), which I assume is the third image, but I don't use or understand PHP.

Images in a GIF file are often compressed, so each image stores only the bounding box of pixels that have changed. Your "identify" shows that the final image is 375x452 pixels, on a canvas of 800x550. I suspect you are interested in the canvas size, not the image size. If your "coalesce" the image list, the each image will become a complete frame, so 800x550 pixels.

**Comment by Muffinman** [comment]
Hi @snibgo, thanks for your response.

I've learned much more about gifs in the past couple of days than I really wanted to!

I guess I was expecting `MagickGetImageWidth` to return the canvas width. If this is _supposed_ to be the Image size of the last image in the list, then I would guess this is an implementation bug in the [Imagick](https://github.com/Imagick/imagick/blob/master/imagick_class.c#L6699) module?

Is there a similar function like `MagickGetCanvasWidth` to return the correct canvas data needed? I had a quick look in [magick-image.c](https://github.com/ImageMagick/ImageMagick/blob/main/MagickWand/magick-image.c) but couldn't see anything else relevant.

**Comment by snibgo** [comment]
> ... then I would guess this is an implementation bug in the Imagick module?

I don't think so. That IMagick code correctly refers to images, not canvases. 

I have corrected the final sentence of my post above. If we want to manipulate frames from  GIF file, we usually need to "-layers coalesce" them first so they are all the same size. We might "-layers optimize" before writing them back to a GIF file.

Without trying MagickGetImagePage(), I can't be sure, but that looks like what you need. Get just the width and height, and ignore x and y.
