### ISSUE TITLE
unrecognized color as the color is used before it is defined

### ISSUE THREAD

**Issue by oharboe** [ImageMagick/ImageMagick#4843]
### ImageMagick version

7.1.0-24

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.10

### Description

Error message when color is used before it is defined.

All other applications I have tried is forgiving about the color being referenced before it is defined in the .svg file.

### Steps to Reproduce

```
$ ~/Downloads/magick --version
Version: ImageMagick 7.1.0-24 Q16-HDRI x86_64 2022-02-06 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib djvu fontconfig freetype jbig jng jpeg lcms lqr lzma openexr png raqm tiff webp x xml zlib
Compiler: gcc (7.5)
$ ~/Downloads/magick foo.svg foo.png
magick: unrecognized color `d' @ warning/color.c/GetColorCompliance/1056.
magick: non-conforming drawing primitive definition `fill' @ error/draw.c/RenderMVGContent/4471.
```

### Images

![foo](https://user-images.githubusercontent.com/2798822/154081707-323b72f9-956e-4403-8702-2e77e8518e03.svg)

**Comment by snibgo** [comment]
What delegate is your IM using to rasterize the SVG? It seems to be MSVG.

For me, using "MSVG:" gives the error message you get, but using Inkscape works fine.

As a general rule, if you get an error message when rasterizing SVG, check that Inkscape is being used.

**Comment by oharboe** [comment]
> MSVG:

How do I specify inkscape delegate?

I have found that whether or not this works, varies from Ubuntu 21.10 to Ubuntu 21.10 machine...

I can reproduce the failure on those machines that it works on by explicitly choosing the MSVG: delegate

```
$ convert MSVG:foo.svg foo.png
convert-im6.q16: unrecognized color `d' @ warning/color.c/GetColorCompliance/1052.
convert-im6.q16: non-conforming drawing primitive definition `fill' @ error/draw.c/RenderMVGContent/4300.
$ convert foo.svg foo.png
$ 
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
