### ISSUE TITLE
[Cygwin] Wall of errors immediately when building (header issue?)

### ISSUE THREAD

**Issue by snowbie** [ImageMagick/ImageMagick#4848]
### ImageMagick version

7.1.0-25

### Operating system

Windows

### Operating system, version and so on

Windows 10 21H2 19044.1466

### Description

If I had to guess it seems like a header issue. I attempted to build the prepackaged 7.1.0-25 from the website, and I received similar errors. The difference being that some of them had nearly the same note being sent between warnings.  
```
./MagickCore/delegate-private.h:1:1: note: include ‘<string.h>’ or provide a declaration of ‘strlen’ 
...
./MagickCore/random-private.h:1:1: note: include ‘<string.h>’ or provide a declaration of ‘memset’
...
```
Hoping to have whatever issue I encounter resolved. I've still yet to successfully build ImageMagick on Windows.

### Steps to Reproduce

Configuration:  
`./configure --prefix=/home/Snow/iminstw --with-quantum-depth=16 --enable-hdri=yes --enable-hugepages=yes --enable-legacy-support=yes --disable-static --enable-gcov=yes --enable-pipes=yes --enable-gprof=yes --enable-prof=yes  --enable-shared=yes --with-modules=yes --enable-delegate-build --with-autotrace=yes --with-bzlib=yes --with-djvu=yes --with-dps=yes --enable-cipher=yes --with-fftw=yes --with-flif=yes --with-fontconfig=yes --with-fpx=yes --with-freetype=yes --with-gslib=yes --with-gvc=yes --with-heic=yes --with-jbig=yes --with-jpeg=yes --with-jxl=yes --with-lcms=yes --with-lqr=yes --with-magick-plus-plus=yes --with-openexr=yes --with-openjp2=yes --with-pango=yes --with-perl=yes --with-png=yes --with-raqm=yes --with-raw=yes --with-rsvg=yes --with-tiff=yes --with-webp=yes --with-wmf=yes --with-x=yes --with-xml=yes --with-zlib=yes --with-zstd=yes --with-windows-font-dir=/cygdrive/c/Windows/Fonts`
building:  
```
$ make
make  all-am
make[1]: Entering directory '/home/Snow/winim7/imagemagick'
  CC       MagickCore/libMagickCore_7_Q16HDRI_la-animate.lo
In file included from MagickCore/animate.c:70:
./MagickCore/string-private.h: In function ‘StringToInteger’:
./MagickCore/string-private.h:105:16: warning: implicit declaration of function ‘strtol’; did you mean ‘strtok’? [-Wimplicit-function-declaration]
  105 |   return((int) strtol(value,(char **) NULL,10));
      |                ^~~~~~
      |                strtok
./MagickCore/string-private.h: In function ‘StringToUnsignedLong’:
./MagickCore/string-private.h:139:10: warning: implicit declaration of function ‘strtoul’; did you mean ‘strtok’? [-Wimplicit-function-declaration]
  139 |   return(strtoul(value,(char **) NULL,10));
      |          ^~~~~~~
      |          strtok
In file included from MagickCore/animate.c:74:
./MagickCore/utility-private.h: In function ‘access_utf8’:
./MagickCore/utility-private.h:137:10: warning: implicit declaration of function ‘access’ [-Wimplicit-function-declaration]
  137 |   return(access(path,mode));
      |          ^~~~~~
./MagickCore/utility-private.h: In function ‘getcwd_utf8’:
./MagickCore/utility-private.h:188:14: warning: implicit declaration of function ‘getcwd’; did you mean ‘getw’? [-Wimplicit-function-declaration]
  188 |    directory=getcwd(path,extent);
      |              ^~~~~~
      |              getw
./MagickCore/utility-private.h:188:13: warning: assignment to ‘char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  188 |    directory=getcwd(path,extent);
      |             ^
./MagickCore/utility-private.h: In function ‘remove_utf8’:
./MagickCore/utility-private.h:261:10: warning: implicit declaration of function ‘unlink’ [-Wimplicit-function-declaration]
  261 |   return(unlink(path));
      |          ^~~~~~
./MagickCore/utility-private.h: In function ‘set_file_timestamp’:
./MagickCore/utility-private.h:327:5: error: storage size of ‘timestamp’ isn’t known
  327 |     timestamp;
      |     ^~~~~~~~~
./MagickCore/utility-private.h:331:10: warning: implicit declaration of function ‘utime’; did you mean ‘utimes’? [-Wimplicit-function-declaration]
  331 |   status=utime(path,&timestamp);
      |          ^~~~~
      |          utimes
./MagickCore/utility-private.h:327:5: warning: unused variable ‘timestamp’ [-Wunused-variable]
  327 |     timestamp;
      |     ^~~~~~~~~
make[1]: *** [Makefile:8643: MagickCore/libMagickCore_7_Q16HDRI_la-animate.lo] Error 1
make[1]: Leaving directory '/home/Snow/winim7/imagemagick'
make: *** [Makefile:6164: all] Error 2
```

**Comment by urban-warrior** [comment]
We just tried compiling the very latest ImageMagick 6 & 7 main repo's with the very latest Cgywin release which includes gcc 11-- it compiled without complaint and all the unit tests passed.

**Comment by snowbie** [comment]
> I suggest you look at [Compiling IM with Cygwin](http://im.snibgo.com/compim.htm).
> 
> Did you do automake and autoconf?

That's the guide I followed. Running the commands, apparently my autoconf was too new. I downgraded the packages to the version aligned with ImageMagick and received the same errors

**Comment by snibgo** [comment]
I notice the errors and warnings are about C library functions, rather than ImageMagick functions. This suggests the compiler can't find the system libraries.

I suggest you try building a simple program such as:
```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main (int argc, char **argv)
{
  printf ("Hello world");

  return(0);
}
```
If that doesn't build, then the problem is clearly unrelated to IM.

If it does build, then add:
```
#include <MagickWand/MagickWand.h>
```
