### ISSUE TITLE
I Want Use ImageMagick  like image codec for my program 

### ISSUE THREAD

**Issue by RomanTruhanov** [ImageMagick/ImageMagick#487]
Hi All! My problem This:  Library compile normal, but fail run standard test program 
![image](https://cloud.githubusercontent.com/assets/13104248/26037315/597161f4-38f9-11e7-8c82-b30dc4ec93c6.png) unsuccessful message is this 
![image](https://cloud.githubusercontent.com/assets/13104248/26037343/b79d0d1e-38f9-11e7-8028-5429ef1c7d6e.png) I mind this message is uinx-like errors for wrong config library how disable all config and bound this broken module for my program(if its possible)

**Comment by dlemstra** [comment]
@RomanTruhanov Have you resolved this issue?
