### ISSUE TITLE
`magick` produces incorrect result possibly due to overflow

### ISSUE THREAD

**Issue by shao-hua-li** [ImageMagick/ImageMagick#4870]
### ImageMagick version

7.1.0-24

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04.4 LTS, x86_64

### Description

Hi,

I compiled ImageMagick with `gcc-11` and `clang-13` separately. For the given input, two `magick` would produce different results.

### Steps to Reproduce

- Compile ImageMagick with `gcc-11` and `clang-13` separately.
- Run `magick issue-4870 out.gcc` on `gcc-11` compiled binary and `magick issue-4870 out.clang` on `clang-13` compiled binary.
- Compare their outputs:
```
$ diff out.clang out.gcc
2c2
< 0,0: (65535,0,0)  #FFFF00000000  rgb(255,0,0)
---
> 0,0: (0,0,0)  #000000000000  rgb(0,0,0)
```

I tried to diagnose this issue with sanitizers. AdressSanitizers didn't complain. UndefinedBehaviorSanitizer in `clang-13` reported a run-time error. However, UndefinedBehaviorSanitizer in `gcc-11` didn't report anything. 
The  UndefinedBehaviorSanitizer in `clang-13` reported as follows (compiled with `CC=clang CXX=clang++ CFLAGS="-f -fsanitize=undefined" CXXFLAGS="-g -fsanitize=undefined"`)
```
coders/txt.c:568:54: runtime error: 2.55778e+21 is outside the range of representable values of type 'unsigned long long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior coders/txt.c:568:54
```
This could also be a false warning of UndefinedBehaviorSanitizer in `clang-13`. Nevertheless, the difference in the two `magick` is indeed an issue.

### Images
[issue-4870.tar.gz](https://github.com/ImageMagick/ImageMagick/files/8110128/issue-4870.tar.gz)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
