### ISSUE TITLE
`magick` produces results changing over time.

### ISSUE THREAD

**Issue by shao-hua-li** [ImageMagick/ImageMagick#4872]
### ImageMagick version

7.1.0-24

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04.4 LTS, x86_64

### Description

Hi,

I found that the given input, `magick` emits different results per run.

### Steps to Reproduce

When I run `magick issue-4872 tmp.out`, I found that some part of `tmp.out` changes per run.  It didn't take me long to notice that some of them are time infos. To remove possible time info in the output, I used `-define preserve-timestamp=true`. Even so, `tmp.out` still change per run.

Then I used the following command to diagnose if the output is related to timestamp or not.
```
while :
do
	magick -define preserve-timestamp=true issue-4872 tmp.out
	date; md5sum tmp.out
	sleed 0.3
done
```
Here is partial result:
```
Mon Feb 21 16:58:16 CET 2022
284106a3baa64ee72dbfb388ddf07af9  tmp.out
Mon Feb 21 16:58:16 CET 2022
24b078c028c070e1bf7d9ac4715495ea  tmp.out
Mon Feb 21 16:58:16 CET 2022
24b078c028c070e1bf7d9ac4715495ea  tmp.out
Mon Feb 21 16:58:17 CET 2022
d3a54eff8cba8885991da7d2bf6b291d  tmp.out
Mon Feb 21 16:58:17 CET 2022
d3a54eff8cba8885991da7d2bf6b291d  tmp.out
```
Although the final output contains no time info, some field in the output still relies on the current timestamp. **This would be very annoying and frustrating if users want to create consistent outputs across runs.**

### Images

[issue-4872.tar.gz](https://github.com/ImageMagick/ImageMagick/files/8110649/issue-4872.tar.gz)

**Comment by urban-warrior** [comment]
`preserve-timestamp` affects `magick mogrify`, not the PNG coder.  Instead, use `+set date:modify`  or `-strip`.

**Comment by shao-hua-li** [comment]
@urban-warrior Thanks for your suggestion. I tried with `+set date:modify` and `-strip`, the output still change over time.
The script:
```
while :
do
	magick +set date:modify issue-4872 -strip tmp.out
	date; md5sum tmp.out
	sleed 0.3
done
```
Output:
```
Mon Feb 21 22:04:29 CET 2022
8485ebd5a7fbf1353fd66c09c3959b10  tmp.out
Mon Feb 21 22:04:30 CET 2022
2626db497971e0703e9193a78e1b86b5  tmp.out
Mon Feb 21 22:04:30 CET 2022
2626db497971e0703e9193a78e1b86b5  tmp.out
Mon Feb 21 22:04:30 CET 2022
2626db497971e0703e9193a78e1b86b5  tmp.out
Mon Feb 21 22:04:31 CET 2022
7061ea55706b8df3d23afa22d7322790  tmp.out
```

**Comment by urban-warrior** [comment]
In out testing, we were outputting to a PNG image type, e.g., png:tmp.out.  For PDB, you are seeing correct behavior.  The header includes a create and modify time which changes and changes in the checksum is expected.  We could protect against the header change but that would be an enhancment request rather than a bug report.
