### ISSUE TITLE
JXL: JXL_CHECK: metadata_->color_encoding.IsGray() == c_current.IsGray()

### ISSUE THREAD

**Issue by pindumb** [ImageMagick/ImageMagick#4874]
### ImageMagick version

ImageMagick-7.1.0-26-Q16-x64-dll

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

Grayscale (tiff) image can not be converted to JXL

### Steps to Reproduce

- Unzip attached profile-gray.zip
- magick profile-gray.tif profile-gray.jxl
- Output is: D:\a\ImageMagick\ImageMagick\ImageMagick-Windows\jpeg-xl\lib\jxl\image_bundle.cc:33: JXL_CHECK: metadata_->color_encoding.IsGray() == c_current.IsGray()

Result image is 0 bytes.

### Images

[profile-gray.zip](https://github.com/ImageMagick/ImageMagick/files/8111907/profile-gray.zip)

See also this bug report in jpeg-xl repository: https://gitlab.com/wg1/jpeg-xl/-/issues/70

**Comment by russell-taylor** [comment]
The same thing is happening for me.

**Comment by pindumb** [comment]
@urban-warrior Is this a libjxl or ImageMagick bug?

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by dlemstra** [comment]
I will probably publish a new release of Magick.NET this weekend @pindumb.

**Comment by pindumb** [comment]
Thanks all. It works in 7.1.0-27. :)

**Comment by pindumb** [comment]
@urban-warrior @jyrkialakuijala

Today I could test with larger images with size 2000 x 2000 and above and I noticed that JXL conversion was extremely slow compared to j2k or jpg.

jpg = <1 second
j2k = ~2 seconds
jxl = multiple minutes

Should I create an ImageMagick issue for that or is this a problem of the JXL format / libjxl?

**Comment by urban-warrior** [comment]
We converted a 2000x2000 pixel image to JXL in ~2 seconds, libjxl 0.6.1.  JXL is threaded.  How many cores does you host support?

**Comment by pindumb** [comment]
> We converted a 2000x2000 pixel image to JXL in ~2 seconds, libjxl 0.6.1. JXL is threaded. How many cores does you host support?

It used all my cores. 6 cores / 12 logical cores. I create new issue with sample image so we can compare.
