### ISSUE TITLE
The same command run on different systems (environments) and possibably outputs different results

### ISSUE THREAD

**Issue by fu123456** [ImageMagick/ImageMagick#4879]
### ImageMagick version

7 and 6

### Operating system

Linux

### Operating system, version and so on

Manjaro and other systems

### Description

The command line ' convert <input> <output>' I often used recently made me doubt.
I run 'convert test.exr output.jpg' on my Manjaro (Archlinux) system, and obtain the different result with that produced on other sysytems (environments). Note that, exr image indicate high dynamic range (HDR) image. For fast understand, please see the following figure
![位图](https://user-images.githubusercontent.com/22411577/155126590-84bcd20a-c088-4921-bd26-7d2c27d411b2.png)
In the above figure, (a) Input exr image (visually showed by Photoshop or Gimp for easy observation), (b) my result produced on my Manjaro system, (c) the correct result produced on other environments such as Ubuntu 16 and Centos (I have tested some different system). Thus, basicually, we can argue that the result in (c) should be correct and that in (b) should be incorrect. I run the command line on my Manjaro system without any error. Running this command line by convert v7 (Imagemagick7) and convert v6 (Imagemagick6) suffers from the same issue. So I do not know why like this and this make me doubt the stability and robustness of the Imagemagick software .

.

### Steps to Reproduce

the exr image can be downloaded at https://drive.google.com/file/d/1IgSllkNopmxPkJd0QGiOKp4q_XI2krOn/view?usp=sharing

### Images

https://drive.google.com/file/d/1IgSllkNopmxPkJd0QGiOKp4q_XI2krOn/view?usp=sharing

**Comment by dlemstra** [comment]
Please don't create both an issue and a discussion.
