### ISSUE TITLE
Leaving directory

### ISSUE THREAD

**Issue by rashmimhatre100** [ImageMagick/ImageMagick#488]
============================================================================
See ./test-suite.log
Please report to https://github.com/ImageMagick/ImageMagick/issues
============================================================================
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory `/home/iassureit/Downloads/ImageMagick-master'
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory `/home/iassureit/Downloads/ImageMagick-master'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/iassureit/Downloads/ImageMagick-master'
make: *** [check] Error 2

**Comment by dlemstra** [comment]
Could you include the test-suit.log file that contains the actual test error?
