### ISSUE TITLE
MagickCore/constitute.c:1504: WriteImages: Assertion `images != (Image *) NULL' failed.

### ISSUE THREAD

**Issue by shao-hua-li** [ImageMagick/ImageMagick#4888]
### ImageMagick version

7.1.0-24

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04.4 LTS, x86_64

### Description

Hi,

I've raised a similar issue before https://github.com/ImageMagick/ImageMagick/issues/4865, and the patch indeed fixed the problem triggered by that input. However, on the latest branch, I triggered the assertion failure again.

### Steps to Reproduce

run `magick issue-4888 /dev/null` and you'll see the error `MagickCore/constitute.c:1504: WriteImages: Assertion `images != (Image *) NULL' failed.`

### Images

[issue-4888.tar.gz](https://github.com/ImageMagick/ImageMagick/files/8127879/issue-4888.tar.gz)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
