### ISSUE TITLE
-bilateral-blur

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#4896]
### ImageMagick version

7.1.0-20

### Operating system

Windows

### Operating system, version and so on

Tested with v7.1.0-20, built with Cygwin tools, on Windows 8.1.

### Description

```
f:\web\im>%FXNEW%magick rose: -bilateral-blur 0.625 x.png

magick: memory allocation failed `ROSE' @ error/effect.c/BilateralBlurImage/950.
```
I think the problem is that BilateralBlurImage() assumes its parameters for width and height parameters are integers greater than zero, but in this case the width is zero.

I suggest the code is changed to include checks, and that the documentation at https://imagemagick.org/script/command-line-options.php#bilateral-blur is changed to include "Width and height should be integers greater than zero."

### Steps to Reproduce

As above.

### Images

rose:

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
