### ISSUE TITLE
magick command not working in Windows 10

### ISSUE THREAD

**Issue by Kalankaboom** [ImageMagick/ImageMagick#4904]
### ImageMagick version

7.1.0

### Operating system

Windows

### Operating system, version and so on

10

### Description

After first installing the ImageMagick tool, I found that the magick command simply wasn't working.
However I managed to solve the issue by looking at my **System Environment Variables**. ImageMagick automatically adds the directory to the system path, but it adds it all the way at the top. I found that the magick command started working when I deleted the automatically added directory and readded it at the end.
To achieve this, search **"Environment variables"** in the Windows search bar, then click to edit. Then, under the **Advanced** tab, click on **Environment variables**. Under **System Variables**, find **Path**. Click on **Edit**, then delete the automatic directory, and finally add it again by clicking on **New** and pasting in the ImageMagick directory.

### Steps to Reproduce

Install without modifying environment variables.

**Comment by urban-warrior** [comment]
Adding the path to the front of the system path works for nearly everyone as expected-- excepting perhaps you.  We're clueless why it fails for you.   To confirm, we tried installing the very latest release of ImageMagick on a Windows 11 system and `magick` ran without any issues in the Command Prompt window.

**Comment by snibgo** [comment]
I don't understand how magick doesn't work when the path is added to the front of the system path, but does work when it is added to the back end. Perhaps there was a syntax problem, eg it was added with a colon ":" instead of a semicolon ";".

@Kalankaboom: it would be helpful if you could post the output of the following commands, both when you have the problem, and afer you have fixed the problem. I show the outputs when I run the commands (on Windows 8.1).

```
f:\web\im>where /T magick

     45840   18/07/2021      15:08:56  C:\im\ImageMagick-7.1.0-4-Q16-HDRI\magick.exe
```

```
f:\web\im>path

PATH=C:\IM\ImageMagick-7.1.0-4-Q16-HDRI\;C:\cygwin64\bin;C:\cygwin64\usr\local\b
in;F:\pictures\bash;C:\Program Files (x86)\HP SimplePass\x64;C:\Program Files (x
86)\HP SimplePass\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\In
tel\iCLS Client\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDO
WS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPower
Shell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\In
tel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;C
:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\In
tel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Ma
nagement Engine Components\IPT;C:\Program Files (x86)\Common Files\Adobe\AGL;C:\
Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon
\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files (x86)\Tesseract-OC
R;c:\cygwin64\bin\;C:\UTIL;C:\UTILEXE;C:\UTILEXE4;C:\UTILEXE3;C:\UTILEXE2;C:\Uti
lXP;"C:\Program Files\windows nt\accessories";F:\DOS62
```

**Comment by dlemstra** [comment]
Please don't create both a discussion and an issue.

**Comment by Kalankaboom** [comment]
That was unintended, sorry 😬.

**Comment by Kalankaboom** [comment]
@snibgo you are probably right that it was a colon/semicolon issue. I moved magick back to the top of my environment variables and it worked just fine!
Thank you very much ^_^
