### ISSUE TITLE
Missing (open) symbols in graph converted from pdf to png

### ISSUE THREAD

**Issue by linuxrider** [ImageMagick/ImageMagick#4905]
### ImageMagick version

7.1.0-26

### Operating system

Linux

### Operating system, version and so on

Ubuntu 21.10

### Description

Converting a pdf graph (generated with the pgfplots package) with the appimage version of ImageMagick to png format leads to missing symbols (open triangles and open squares while open diamonds are preserved).

### Steps to Reproduce

Convert attached PDF:
`./magick convert prod_thesis-temp-pgffilter-22.pdf convert_appimage_7.1_open_symbols_disappear.png`

### Images

[prod_thesis-temp-pgffilter-22.pdf](https://github.com/ImageMagick/ImageMagick/files/8167448/prod_thesis-temp-pgffilter-22.pdf)

![convert_appimage_7 1_open_symbols_disappear](https://user-images.githubusercontent.com/5882359/156313094-81eda2c1-609b-4f82-9222-9f63a92ccd4b.png)

**Comment by fmw42** [comment]
This is a Ghostscript issue.  Imagemagick uses Ghostscript to rasterize the pdf. You should report this on a Ghostscript forum.

**Comment by snibgo** [comment]
With IM v7.1.0-4 and Ghostscript v9.19:
```
magick -density 200 -verbose prod_thesis-temp-pgffilter-22.pdf x.png
```
x.png is:
![x](https://user-images.githubusercontent.com/33812368/156463328-091dfd67-49a5-4679-8887-21e3cc13f984.png)

The result is very close to the image shown in Adobe Acrobat Reader DC 2021.011.20039. I can't see any missing symbols.

**Comment by fmw42** [comment]
With IM 7.1.026 and GS 9.54, I did not see the open symbols.  Snibgo's command produced:

![x](https://user-images.githubusercontent.com/13458218/156466215-8b135c67-d003-4c8a-a326-83e28cb2531f.png)

So as I said above, I think it is a GS problem.
