### ISSUE TITLE
Wrong mp4 -> jpg frames extraction

### ISSUE THREAD

**Issue by mcu70** [ImageMagick/ImageMagick#4910]
### ImageMagick version

7.1.0-26

### Operating system

Linux

### Operating system, version and so on

OpenSuse

### Description

Hello!
if I run this simple mp4->jpg command

`convert -background 'white' 'file_example_MP4_480_1_5MG.mp4' -alpha 'remove' -quality '85' -antialias -verbose -version 'frame_%03d.jpg' 2>&1`

I receive the following output (shortened):
```
Version: ImageMagick 7.1.0-26 Q16-HDRI x86_64 2022-02-21 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib cairo djvu fftw flif fontconfig fpx freetype gvc heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zip zlib
Compiler: gcc (7.5)
file_example_MP4_480_1_5MG.mp4=>frame_000.jpg[0] MP4 480x270 480x270+0+0 8-bit sRGB 7691B 0.870u 0:00.879
file_example_MP4_480_1_5MG.mp4=>frame_001.jpg[1] MP4 196x188 480x270+140+36 8-bit sRGB 9664B 0.860u 0:00.877
file_example_MP4_480_1_5MG.mp4=>frame_002.jpg[2] MP4 217x188 480x270+132+36 8-bit sRGB 10847B 0.860u 0:00.877
file_example_MP4_480_1_5MG.mp4=>frame_003.jpg[3] MP4 222x186 480x270+128+36 8-bit sRGB 6429B 0.860u 0:00.878
file_example_MP4_480_1_5MG.mp4=>frame_004.jpg[4] MP4 216x185 480x270+128+36 8-bit sRGB 6461B 0.870u 0:00.878
file_example_MP4_480_1_5MG.mp4=>frame_005.jpg[5] MP4 221x184 480x270+130+38 8-bit sRGB 13052B 0.870u 0:00.878
```

While, the same command with an old version that I was using, gives back
```
Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib
file_example_MP4_480_1_5MG.mp4=>frame_000.jpg[0] MP4 480x270 480x270+0+0 8-bit sRGB 8776B 0.620u 0:00.620
file_example_MP4_480_1_5MG.mp4=>frame_001.jpg[1] MP4 480x270 480x270+0+0 8-bit sRGB 8778B 0.620u 0:00.620
file_example_MP4_480_1_5MG.mp4=>frame_002.jpg[2] MP4 480x270 480x270+0+0 8-bit sRGB 8718B 0.620u 0:00.620
file_example_MP4_480_1_5MG.mp4=>frame_003.jpg[3] MP4 480x270 480x270+0+0 8-bit sRGB 8763B 0.620u 0:00.620
file_example_MP4_480_1_5MG.mp4=>frame_004.jpg[4] MP4 480x270 480x270+0+0 8-bit sRGB 8741B 0.620u 0:00.620
file_example_MP4_480_1_5MG.mp4=>frame_005.jpg[5] MP4 480x270 480x270+0+0 8-bit sRGB 8817B 0.610u 0:00.620
```

As you can see, with the new version I'm getting frames with different sizes. Just the first one is of the correct size.
Also, with a private file that I cannot share, I got one frame less with v7.1.0-26 than with v6.9.10-23.

Thank You!

### Steps to Reproduce

Just run the command

```
`convert -background 'white' 'file_example_MP4_480_1_5MG.mp4' -alpha 'remove' -quality '85' -antialias -verbose -version 'frame_%03d.jpg' 2>&1`
```

with the example file that I used. I found it here:
https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4
but I got same wrong frame sizes also with other private MP4 videos.

**Comment by snibgo** [comment]
As you have IM v7, I suggest using "magick" instead of "convert".

I suggest moving "-verbose" to the start, which may show the delegate that extracts the frames. With IM v7.1.0-4, I get:
```
f:\web\im>%IMG7%magick -verbose file_example_MP4_480_1_5MG.mp4 info:
"ffmpeg.exe" -nostdin -loglevel error -i "file_example_MP4_480_1_5MG.mp4" -vcodec pam -an -f rawvideo -y  "C:/Users/Alan/AppData/Local/Temp/magick-iI_TK9jt_ffF2K3iOmkPdVQNwVQqn1ly"
C:/Users/Alan/AppData/Local/Temp/magick-iI_TK9jt_ffF2K3iOmkPdVQNwVQqn1ly[0] PAM480x270 480x270+0+0 8-bit TrueColor sRGB 3.594u 0:03.602
C:/Users/Alan/AppData/Local/Temp/magick-iI_TK9jt_ffF2K3iOmkPdVQNwVQqn1ly[1] PAM480x270 480x270+0+0 8-bit TrueColor sRGB 3.594u 0:03.621
C:/Users/Alan/AppData/Local/Temp/magick-iI_TK9jt_ffF2K3iOmkPdVQNwVQqn1ly[2] PAM480x270 480x270+0+0 8-bit TrueColor sRGB 3.609u 0:03.640
C:/Users/Alan/AppData/Local/Temp/magick-iI_TK9jt_ffF2K3iOmkPdVQNwVQqn1ly[3] PAM480x270 480x270+0+0 8-bit TrueColor sRGB 3.609u 0:03.661
C:/Users/Alan/AppData/Local/Temp/magick-iI_TK9jt_ffF2K3iOmkPdVQNwVQqn1ly[4] PAM480x270 480x270+0+0 8-bit TrueColor sRGB 3.594u 0:03.679
:
:
```
So the delegate is ffmpeg. This is distributed in the IM directory. "ffmpeg -version" tells me it is:
```
ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9.3.1 (GCC) 20200523
```
Is your delegate command essentially the same as mine? Does that command use ffmpeg? If so, what version?

Perhaps you need "-layers coalesce" after reading the mp4.

**Comment by mcu70** [comment]
**UPDATE**
I found that this one works fine for me:
```
convert -verbose -define video:intermediate-format=pam -background 'white' 'file_example_MP4_480_1_5MG.mp4' -alpha 'remove' -quality '85' -antialias 'frame_%03d.jpg' 2>&1
```
which forces ffmpeg to the following:
```
'ffmpeg' -nostdin -loglevel error -i 'file_example_MP4_480_1_5MG.mp4' -an -f rawvideo -y  -vcodec pam '/tmp/magick-cPLBBPHpLEQnbOkE2BDi8iGP8RdeVars'
```

Now the fun part.
If I look inside the delegates.xml file, I can see this line
```
<delegate decode="video:decode" command="&quot;ffmpeg&quot; -nostdin -loglevel error -i &quot;%s&quot; -an -f rawvideo -y %s &quot;%s&quot;"/>
```
where is pretty clear that the **-vcodec webp** in my previous post was injected directly by imagemagick itself.
If I remove the %s and put **-vcodec pam**, it complains because of course it lacks the last parameter for the ffmpeg call.
If I simply add it next to the **%s** , the -vocodec is duplicated: once with pam and once with webp.

So this let me think that in the new imagemagick version, the webp is used/injected by default, but since I have no idea how imagemagick's code works, I cannot tell for sure.
Should that be filed as a bug or do you know any way to modify the injected vcode in the config other than using the switch **-define video:intermediate-format=pam** as I've done?

**Comment by dlemstra** [comment]
We now use `webp` as the intermediate format by default and with that define you can override that to force the user of `pam` instead. That define is the only way you can override that now.
