### ISSUE TITLE
Why does ImageMagick show this JPG image different to every other picture viewer I try?

### ISSUE THREAD

**Issue by simounn** [ImageMagick/ImageMagick#4911]
### ImageMagick version

6.9.10-23

### Operating system

Linux

### Operating system, version and so on

Xubuntu 20.04.02

### Description

Please see this image for the rendering error: [https://i.stack.imgur.com/wt7uK.png](url)

This is the error_picture.jpg file (also attached to this post): [https://i.stack.imgur.com/8wc7c.jpg](url)

Image viewing programs tested are : GIMP, ristretto, feh, Pix, Firefox, LibreOffice Writer, IrFanView (wine)

$ display --version Version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org/ Copyright: © 1999-2019 ImageMagick Studio LLC License: https://imagemagick.org/script/license.php Features: Cipher DPC Modules OpenMP Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

### Steps to Reproduce

run "display error_picture.jpg"

### Images

![error_picture](https://user-images.githubusercontent.com/72730470/156882211-22d5eb03-a24d-4253-ba9d-be33303e1fa5.jpg)

**Comment by simounn** [comment]
**Fixing bad URLs in post**

Please see this image for the rendering error: [https://i.stack.imgur.com/wt7uK.png](https://i.stack.imgur.com/wt7uK.png)

This is the error_picture.jpg file (also attached to this post): [https://i.stack.imgur.com/8wc7c.jpg](https://i.stack.imgur.com/8wc7c.jpg)

**Comment by urban-warrior** [comment]
We tried your image with the release of ImageMagick, 7.1.0-26 anf 6.9.12-41 and both displayed the image properly.   Can you upgrade your release of ImageMagick on your host?

**Comment by simounn** [comment]
Thanks urban-warrior. I used 7.1.0-26 appimage and it displayed image correctly! :-) I'll look into how to update host.
