### ISSUE TITLE
when I build ImageMagick in mingw, I met a compile error... 

### ISSUE THREAD

**Issue by xiaoxiongli** [ImageMagick/ImageMagick#4917]
### ImageMagick version

7.1.0-27

### Operating system

Windows

### Operating system, version and so on

win10, mingw

### Description

when I build ImageMagick in mingw, I met a compile error... 

$ make
D:/software/mingw64/bin/make  all-am
make[1]: Entering directory 'D:/transcode/magick/magick'
  CC       utilities/magick.o
  CC       MagickCore/libMagickCore_7_Q16HDRI_la-accelerate.lo
**/usr/bin/sh: C:/Program: No such file or directory**
make[1]: *** [Makefile:8638: MagickCore/libMagickCore_7_Q16HDRI_la-accelerate.lo] Error 127
make[1]: Leaving directory 'D:/transcode/magick/magick'
make: *** [Makefile:6164: all] Error 2

### Steps to Reproduce

in mingw64:
./configure
make

**Comment by dlemstra** [comment]
Please don't create both and issue and a discussion.
