### ISSUE TITLE
Install, 3 Tests FAIL Report

### ISSUE THREAD

**Issue by intmarine** [ImageMagick/ImageMagick#4918]
### ImageMagick version

7.1.0-27

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04 up to date

### Description
=========
Testsuite summary for ImageMagick 7.1.0-27
========================
# TOTAL: 86
# PASS:  83
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0
========================
See ./test-suite.log
Please report to https://github.com/ImageMagick/ImageMagick/issues
=======
make[3]: *** [Makefile:12294: test-suite.log] Error 1
make[3]: Leaving directory '/home/dxg/ImageMagick-7.1.0-27'
make[2]: *** [Makefile:12402: check-TESTS] Error 2
make[2]: Leaving directory '/home/dxg/ImageMagick-7.1.0-27'
make[1]: *** [Makefile:12615: check-am] Error 2
make[1]: Leaving directory '/home/dxg/ImageMagick-7.1.0-27'
make: *** [Makefile:12617: check] Error 2

====
...
PASS: tests/validate-convert.tap 1
FAIL: tests/validate-formats-disk.tap 1
FAIL: tests/validate-formats-map.tap 1
FAIL: tests/validate-formats-memory.tap 1
PASS: tests/validate-identify.tap 1
...

### Steps to Reproduce

Install per https://gist.github.com/zulhfreelancer/e104e4b330c8dbc6622d92b8cd525bf6, replacing version number
Fail at 
sudo make check

**Comment by urban-warrior** [comment]
Do you have Ghostscript installed on your host?  Edit `tests/validate-formats-memory.log` and identify which test failed and post the log output for just that test here so we can review.
