### ISSUE TITLE
Cropping an image using percentages will not work, whereas resizing it with the same parameters will.

### ISSUE THREAD

**Issue by IoIxD** [ImageMagick/ImageMagick#4919]
### ImageMagick version

7.1.0-23

### Operating system

Linux

### Operating system, version and so on

Linux jeff 5.14.21-2-MANJARO #1 SMP PREEMPT Sun Nov 21 22:43:47 UTC 2021 x86_64 GNU/Linux

### Description

Trying to do either of the following commands...
`convert A.png -verbose -crop 110%x110%+0+0 ./test A.png`
`mogrify -verbose -crop 110%x100%+0+0 -path ./test A.png`
On a 5x7 image does nothing, despite a success being reported.

```
writing raw profile: type=icc, length=672
A.png PNG 5x7 5x7+0+0 8-bit sRGB 539B 0.000u 0:00.001
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/740.
convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `A.png' @ warning/png.c/MagickPNGWarningHandler/1748.
gavin@jeff ~/P/S/test [1]> 
```

I CAN see the error `RGB color space not permitted on grayscale PNG`, but this clearly doesn't matter if the resize command works.

### Steps to Reproduce

- Obtain the attached image
- Try to extend the borders of the image using the crop command, making sure that "-verbose" is applied
- notice that the size doesn't change but a success is reported
- do the same command but swap resize instead of crop
- observe the change

### Images

(...is black, so it's hard to see on dark mode. But it's there)

![A](https://user-images.githubusercontent.com/30945097/157160759-42fe288b-80de-4563-8a92-20cec91b0680.png)

**Comment by snibgo** [comment]
As you use M v7, I suggest you use "magick" and "magick mogrify" instead of "convert" and "mogrify".

> convert A.png -verbose -crop 110%x110%+0+0 ./test A.png

"-crop" will reduce dimensions. It will never enlarge the image. Giving crop dimensions larger than the image doesn't cause an error.


> convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `A.png'
@warning/png.c/MagickPNGWarningHandler/1748.

That is just a warning, not an error, so it won't prevent the action you wanted.

**Comment by fmw42** [comment]
If you want to pad or crop, use -extent rather than -crop.
