### ISSUE TITLE
Extracting first frame from MNG file fails with out of memory error

### ISSUE THREAD

**Issue by reima** [ImageMagick/ImageMagick#4927]
### ImageMagick version

7.1.0-27 Q8 x64

### Operating system

Windows

### Operating system, version and so on

Windows 10 21H2

### Description

I'm trying to extract the first frame from the attached MNG file and save it as a PNG via command line.

ImageMagick takes several minutes, consumes all of the available system memory, and finally exits with an out of memory error:
```
convert: Out of memory `createvd_progress.mng' @ warning/png.c/MagickPNGWarningHandler/1748.
convert: IDAT: insufficient memory `createvd_progress.mng' @ error/png.c/MagickPNGErrorHandler/1715.
convert: NoImagesDefined `frame.png' @ error/convert.c/ConvertImageCommand/3325.
```

IrfanView 4.59 64-bit can display the MNG file just fine with the MNG plugin.

Inspection of the MNG file revealed that it contains a [LOOP](http://www.libpng.org/pub/mng/spec/#mng-LOOP) chunk with an iteration count of 2,147,483,647 (2<sup>31</sup> - 1), which may be part of the problem.

Is there any way to stop decoding after the first complete frame, as that's all that I am interested in?

### Steps to Reproduce

Run the following command:
```
magick convert 'createvd_progress.mng[0]' frame.png
```

### Images

[createvd_progress.zip](https://github.com/ImageMagick/ImageMagick/files/8215978/createvd_progress.zip)

**Comment by urban-warrior** [comment]
You can limit the image list length with this security policy:

```
<policy domain="resource" name="list-length" value="128"/>
```

However, you should be able to just read the first image of an animation.  We'll add patch to address this issue within a day or two.  Thanks for alerting us to this problem.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by reima** [comment]
I can confirm that this issue is resolved on the main branch.

Thank you!
