### ISSUE TITLE
Sometimes float_t is long double, causes linking error

### ISSUE THREAD

**Issue by dubhater** [ImageMagick/ImageMagick#493]
Apparently you can't count on ``float_t`` to be ``float``. The documentation of math.h says ``float_t`` must be *at least* the size of ``float``. My application is compiled with ``-msse2 -mfpmath=sse``, which causes math.h to make ``float_t`` ``float``, but ImageMagick itself was compiled without those parameters, which caused math.h to make ``float_t`` ``long double``. The result:
```
src/filters/imwri/.libs/libimwri_la-imwri.o:imwri.cpp:(.text+0xa6a1): undefined reference to `Magick::Color::Color(float, float, float, float)'
```
Sure enough, nm shows the Magick++ library contains
```
Magick::Color::Color(long double, long double, long double, long double)
```

It seems you only check if ``float_t`` exists, without checking its size: https://github.com/ImageMagick/ImageMagick/blob/a5d49d1c5b4762dd7aa124e6dc9de84975909e92/MagickCore/magick-type.h#L42

ImageMagick version: 7.0.5-6 configured for Q16 HDRI.
Operating system where I'm compiling ImageMagick and my application: 64 bit Arch Linux.
Operating system where the application will run: 32 bit Windows.
GCC version: 6.3.1.

This problem doesn't happen when compiling for 64 bit Windows, probably because the features enabled by ``-msse2 -mfpmath=sse`` are available by default.

**Comment by bastien-roucaries** [comment]
Magick it is this bug https://github.com/ImageMagick/ImageMagick/issues/510

**Comment by bastien-roucaries** [comment]
And the reporter is right it more important.... float_t and double_t should not be used on ABI ...

I have made originally this patch but checking the size in order to get ABI type from float_t

This commit is buggy
https://github.com/ImageMagick/ImageMagick/commit/2f4e2b26f7cf50f05545eef88b6038a876040182

**Comment by bastien-roucaries** [comment]
Imagemagick6 include something that is fixed:
/*
  Float_t is not an ABI type.
*/
#if MAGICKCORE_SIZEOF_FLOAT_T == 0
typedef float MagickRealType;
#elif (MAGICKCORE_SIZEOF_FLOAT_T == MAGICKCORE_SIZEOF_FLOAT)
typedef float MagickRealType;
#elif (MAGICKCORE_SIZEOF_FLOAT_T == MAGICKCORE_SIZEOF_DOUBLE)
typedef double MagickRealType;
#elif (MAGICKCORE_SIZEOF_FLOAT_T == MAGICKCORE_SIZEOF_LONG_DOUBLE)
typedef long double MagickRealType;
#else
# error Your float_t type is neither a float, nor a double, nor a long double
#endif

**Comment by bastien-roucaries** [comment]
so fix #510 and fix this bug using the #define stuff then do not forget to bump version of lib (all).

For v6 you only need to fix #510 and bump version of lib

**Comment by bastien-roucaries** [comment]
ok the right way is to do something like:
`
#if MAGICKCORE_SIZEOF_FLOAT_T == 0
typedef float Magickfloat_t;
#elif (MAGICKCORE_SIZEOF_FLOAT_T == MAGICKCORE_SIZEOF_FLOAT)
typedef float Magickfloat_t;
#elif (MAGICKCORE_SIZEOF_FLOAT_T == MAGICKCORE_SIZEOF_DOUBLE)
typedef double Magickfloat_t;
#elif (MAGICKCORE_SIZEOF_FLOAT_T == MAGICKCORE_SIZEOF_LONG_DOUBLE)
typedef long double Magickfloat_t;
#else
#error Your float_t type is neither a float, nor a double, nor a long double
#endif
#if MAGICKCORE_SIZEOF_DOUBLE_T == 0
typedef double Magickdouble_t;
#elif (MAGICKCORE_SIZEOF_DOUBLE_T == MAGICKCORE_SIZEOF_DOUBLE)
typedef double Magickdouble_t;
#elif (MAGICKCORE_SIZEOF_DOUBLE_T == MAGICKCORE_SIZEOF_LONG_DOUBLE)
typedef long double Magickdouble_t;
#else
#error Your double_t type is neither a float, nor a double, nor a long double
#endif
`

then to use  Magickdouble_t/Magickfloat_t

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by bastien-roucaries** [comment]
This should be close
