### ISSUE TITLE
JXL conversion is very slow (compared to jpeg / j2k)

### ISSUE THREAD

**Issue by matthias3333** [ImageMagick/ImageMagick#4930]
### ImageMagick version

7.1.0-27 Q16 x64

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

Input image: 2000 x 2000 random pixels, 16-bit grayscale

Conversion with J2K takes ~2 seconds
Conversion with JXL takes ~41 seconds

![image](https://user-images.githubusercontent.com/3605191/157550328-c570f734-1556-490d-96a6-16fff55053ae.png)

### Steps to Reproduce

- Extract input.zip
- magick input.tiff output.jxl

### Images

[input.zip](https://github.com/ImageMagick/ImageMagick/files/8218685/input.zip)

**Comment by urban-warrior** [comment]
```
$ time magick input.tiff output.jxl
2.808u 0.146s 0:00.43 683.7%    0+0k 0+3472io 0pf+0w
```

Subsecond timing.

**Comment by urban-warrior** [comment]
@dlemstra, can you take a look @ libjxl under Windows.  The test image takes 17 seconds under Windows and subsecond under Linux.  Is this a build issue or an issue with the delegate library?

**Comment by dlemstra** [comment]
This is probably related to the Windows configuration. We had to disable optimizations because this would break the binary created by VisualStudio. But I will need to investigate that. Don't know when I will have time for that though.

**Comment by jumper444** [comment]
I have been using jxl on windows in Irfanview and also IM.  I'm not sure whether they use the same library reference or not.  JXL (conversion to) *in general* appears to be DRAMATICALLY slower than pretty much all other common formats.  This seems to simply be the nature of the images themselves.  You can make it somewhat faster by dropping the 'effort' parameter to 'faster', but then your image size goes up a lot.  I only get good image sizes when the effort is set to (way too) slow.  And not by a minor amount.  Setting effort to 9 can cause my machine to take a minute or more per image.

**Comment by dlemstra** [comment]
We re-enabled optimization so this should have improved. Haven't tested this myself.

**Comment by snowbie** [comment]
> We re-enabled optimization so this should have improved. Haven't tested this myself.

I haven't done any benchmarks, but I can confirm that there is a significant speed boost now compared to previous versions. Thanks

**Comment by matthias3333** [comment]
Indeed. It now takes 500 milliseconds with ImageMagick 7.1.0-52 Q16 x64 on Windows :)
