### ISSUE TITLE
Installation of png delegate on Redhat 6.5 (Santiago) 64bit.

### ISSUE THREAD

**Issue by daacon** [ImageMagick/ImageMagick#494]
Hi All 

I have googled , searched here.  Spent about a day on this and no luck so far. I have tried almost every suggestion (from google searches) and yet I cannot get the PNG delegate added.  The last attempt was as follows:  My guess is I am not telling Imagemagic where to look for the proper library (missing a switch or an invalid switch) . The kicker is all I need is png. 

Any help would be appreciated thanks ! 

Latest Steps 

1. Installed the ZLIB Library 
./configure  --prefix=/usr/local/lib64/zlib-1.2.11  
make
make install
2. Installed the PNG library 
./configure CFLAGS=-O3 --prefix=/tmp/install --enable-shared --disable-dependency-tracking
make check && make install
3. Install Imagemagick (ImageMagick-7.0.5-5)
./configure LDFLAGS=-L/tmp/install/lib CFLAGS=-O3 --prefix=/tmp/install --enable-shared --disable-dependency-tracking --with-png=yes
make check

84 of 86 pass (test_suite.log) - not sure I am concerned about the fonts as I will only use this at the command line never in X-windows but feel free to tell me it's important and how I can fix it. 

lt-wandtest: delegate library support not built-in '/usr/share/fonts/default/Typ
e1/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1792.
lt-wandtest: no decode delegate for this image format `PNG' @ error/constitute.c
/ReadImage/509.
lt-wandtest: delegate library support not built-in '/usr/share/fonts/default/Typ
e1/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1792.
lt-wandtest: no decode delegate for this image format `PNG' @ error/constitute.c
/ReadImage/509.
tests/wandtest.c main 5321 non-conforming drawing primitive definition `text' @
error/draw.c/DrawImage/3269

 ImageMagick-7.0.5-5]# identify -version
Version: ImageMagick 7.0.5-5 Q16 x86_64 2017-05-17 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP
Delegates (built-in):

Thansk.

**Comment by mikayla-grace** [comment]
Did you install the PNG development release of PNG.  ImageMagick needs access to the PNG headers.  Take a look at config.log and search for where the script is trying to validate the PNG library.  The validation fails and this section of the log tells you exactly why it failed.  Correct the problem, reconfigure ImageMagick until PNG passes the validation test, then build and install ImageMagick.

**Comment by daacon** [comment]
Thanks for the feedback. As it turns out I removed everything (Imagemagick, all delegates). Then I just did a yum install ImageMagick.x86_64 and yum install libpng. Even though when I executed a  convert -list configure there were no delegates listed, when I tried the convert *.png *.jpg it worked. I got so hung up in reading the config file I had not tried the convert. It's all good now.
