### ISSUE TITLE
new on magick help

### ISSUE THREAD

**Issue by vaccarieli** [ImageMagick/ImageMagick#4942]
### ImageMagick version

7.1.0-27

### Operating system

Linux

### Operating system, version and so on

Ubuntu 21.10

### Description

Hi, I can not use magick dk what am doing wrong.

```<policymap>
  <!-- temporary path must be a preexisting writable directory -->
  <policy domain="resource" name="temporary-path" value="/data/magick"/>
  <policy domain="resource" name="memory" value="256MiB"/>
  <policy domain="resource" name="list-length" value="32"/>
  <policy domain="resource" name="width" value="8KP"/>
  <policy domain="resource" name="height" value="8KP"/>
  <policy domain="resource" name="map" value="512MiB"/>
  <policy domain="resource" name="area" value="16KP"/>
  <policy domain="resource" name="disk" value="1GiB"/>
  <policy domain="resource" name="file" value="768"/>
  <policy domain="resource" name="thread" value="2"/>
  <policy domain="resource" name="time" value="120"/>
  <policy domain="module" rights="none" pattern="URL" /> 
  <policy domain="filter" rights="none" pattern="*" />
  <policy domain="path" rights="none" pattern="@*"/>  <!-- indirect reads not permitted -->
  <policy domain="cache" name="memory-map" value="anonymous"/>
  <policy domain="cache" name="synchronize" value="true"/>
  <policy domain="cache" name="shared-secret" value="passphrase" stealth="True"/>
  <policy domain="system" name="precision" value="6"/>
  <policy domain="system" name="shred" value="1"/>
  <policy domain="module" rights="read | write" pattern="{GIF,JPEG,PNG,WEBP}" />
  <policy domain="coder" rights="none" pattern="{PS,EPI,EPS,EPSF,EPSI}" />
</policymap>``` 

   raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

convert: attempt to perform an operation not allowed by the security policy `@/tmp/tmp7w0jgb9u.txt' @ error/property.c/InterpretImageProperties/3714.
convert: no images defined `PNG32:/tmp/tmp94s66vj0.png' @ error/convert.c/ConvertImageCommand/3325.


### Steps to Reproduce

python script to paste subs on video

```generator = lambda txt: TextClip(txt, font='Georgia-Regular', fontsize=40, color='white', align="center")
sub = SubtitlesClip(videoYt+".srt", generator)
myvideo = VideoFileClip(videoYt)
final = CompositeVideoClip([myvideo, sub])
final.write_videofile(videoYt+".mp4", fps=myvideo.fps)```



### Images

_No response_

**Comment by snibgo** [comment]
One line of your policy.xml is:

```
  <policy domain="path" rights="none" pattern="@*"/>  <!-- indirect reads not permitted -->
```

The first error is:
```
convert: attempt to perform an operation not allowed by the security policy `@/tmp/tmp7w0jgb9u.txt'
@ error/property.c/InterpretImageProperties/3714.
```
So I expect that if you remove that line from policy.xml, that error won't occur.

**Comment by vaccarieli** [comment]
hi, thanks for the response. I removed it but now i got this 

```    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

convert: unable to read font `Georgia-Regular' @ warning/annotate.c/RenderType/1005.
convert: delegate library support not built-in 'Georgia-Regular' (Freetype) @ warning/annotate.c/RenderFreetype/1919.
convert: attempt to perform an operation not allowed by the security policy `PS' @ error/constitute.c/IsCoderAuthorized/447.
convert: no images defined `PNG32:/tmp/tmpjodprj75.png' @ error/convert.c/ConvertImageCommand/3325.
.
```

**Comment by snibgo** [comment]
IM can't find the "Georgia-Regular" font. You might change that to a font you do have, or remove the requirement for a particular font.

The final "policy domain" gives you no rights for "PS" and other file types. So change that line to remove "PS", or remove the line entirely.

**Comment by vaccarieli** [comment]
I deleted everything and left the policy.xml, Still getting the same issue after deleting all, even tried to change the font type, also tried to check the available fonts using `convert -list font` and is empty no fonts are showing, having a real hard time with this.

`  <!ELEMENT policymap (policy)*>
  <!ATTLIST policymap xmlns CDATA #FIXED ''>
  <!ELEMENT policy EMPTY>
  <!ATTLIST policy xmlns CDATA #FIXED '' domain NMTOKEN #REQUIRED
    name NMTOKEN #IMPLIED pattern CDATA #IMPLIED rights NMTOKEN #IMPLIED
    stealth NMTOKEN #IMPLIED value CDATA #IMPLIED>
]>
`

`convert: unable to read font `Courier' @ warning/annotate.c/RenderType/1005.
convert: delegate library support not built-in 'Courier' (Freetype) @ warning/annotate.c/RenderFreetype/1919.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/737.
convert: no images defined `PNG32:/tmp/tmp62ui82qg.png' @ error/convert.c/ConvertImageCommand/3325.`

**Comment by snibgo** [comment]
So, your IM installation can't read any fonts, and can't decode PNG files. Can it do anything? Try these commands, at the command line:
```
convert -version

magick -version

convert rose: x.png

convert x.png x.jpg
```

How did you install IM? If you built from source, did you first install the delegates?

**Comment by vaccarieli** [comment]
The command worked fine, apparenly my fonts are missing from `type.xml` which is empty.

``
./type.xml

``

``
magick -version

convert rose: x.png

convert x.png x.jpg
Version: ImageMagick 7.1.0-27 Q16-HDRI x86_64 2022-03-04 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in):
Compiler: gcc (11.2)
Version: ImageMagick 7.1.0-27 Q16-HDRI x86_64 2022-03-04 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in):
Compiler: gcc (11.2)
``

STEPS I FOLLOW TO INSTALL 

```
          *********** Install *************

sudo apt install build-essential make
wget https://download.imagemagick.org/ImageMagick/download/ImageMagick.tar.gz
tar -axvf ImageMagick.tar.gz
cd ImageMagick-
./configure
sudo make install
sudo ldconfig /usr/local/lib
```

**Comment by snibgo** [comment]
```
Delegates (built-in):
```
That line is blank, so your IM has no built-in delegates. For comparison, here is mine:
```
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms
 lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
```
