### ISSUE TITLE
CR3 error 

### ISSUE THREAD

**Issue by gentilmente** [ImageMagick/ImageMagick#4956]
### ImageMagick version

7.1.0-27

### Operating system

MacOS

### Operating system, version and so on

12.3 Monterey

### Description

`magick --version
Version: ImageMagick 7.1.0-27 Q16-HDRI x86_64 2022-03-04 https://imagemagick.org 
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(5.0)
Delegates (built-in): bzlib fontconfig freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib
Compiler: gcc (4.2)`

`magick identify -verbose example.CR3
identify: delegate failed `'ufraw-batch' --silent --create-id=also --out-type=png --out-depth=16 '--output=%u.png' '%i'' @ error/delegate.c/InvokeDelegate/1913.
identify: unable to open image '/var/folders/j_/gw40wy3s18n5hpt7j38fh44w0000gp/T/magick-CC-mWuedexReGixz6bcd4YGx-tw36OK2.ppm': No such file or directory @ error/blob.c/OpenBlob/3527.`

### Steps to Reproduce

magick identify -verbose example.CR3

### Images

github dont support CR3 to upload
i'm using this https://github.com/Cardoso222/cr3-to-jpg/blob/master/rawImages/example.CR3

**Comment by snibgo** [comment]
Try running ufraw-batch directly at the command line. I suspect that will fail, and the reason is that ufraw-batch (like many other raw processors) can't yet read CR3 files.

**Comment by gentilmente** [comment]
I get `zsh: command not found: ufraw-batch`

**Comment by urban-warrior** [comment]
Try `identify -list format`.  You'll see that the CR3 image format is not yet supported in ImageMagick.
