### ISSUE TITLE
Divide_by_zero in CORE_RL_openjpeg_!opj_write_tile+0x29fb

### ISSUE THREAD

**Issue by pengjiaqi** [ImageMagick/ImageMagick#496]
Hello,

On the newest windows binary release ImageMagick 7.0.5-6, there is a divide_by_zero bug in  CORE_RL_openjpeg_!opj_write_tile+0x29fb when opening a crafted .jp2 file with IMDisplay MFC Application, which will cause a denial of service attack.

**##Crash Info**
0:000> g
(25e4.20d0): Integer divide-by-zero - code c0000094 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
CORE_RL_openjpeg_!opj_write_tile+0x29fb:
000007fedd01b61b f7fb            idiv    eax,ebx
0:000> r ebx
ebx=0

**##Crash Stack**
0:000> kp
Child-SP          RetAddr           Call Site
0000000000236960 000007fedd020051 CORE_RL_openjpeg_!opj_write_tile+0x29fb
00000000002369c0 000007fedd022360 CORE_RL_openjpeg_!opj_write_tile+0x7431
0000000000236a70 000007fedd00a818 CORE_RL_openjpeg_!opj_write_tile+0x9740
0000000000236ad0 000007fedd00aa7e CORE_RL_openjpeg_!opj_image_tile_create+0x56f8
0000000000236b30 000007fedd00b837 CORE_RL_openjpeg_!opj_image_tile_create+0x595e
0000000000236be0 000007fedd00a379 CORE_RL_openjpeg_!opj_image_tile_create+0x6717
0000000000236c20 000007fedd1218b2 CORE_RL_openjpeg_!opj_image_tile_create+0x5259
0000000000236c50 000007fed42cbb54 IM_MOD_RL_jp2_+0x18b2
0000000000238d90 000007fee2bffd4f CORE_RL_MagickCore_!ReadImage+0x2b4
000000000023dee0 000000013fb55c8b CORE_RL_Magick___!Magick::Image::read+0x4f
000000000023df10 000000013fb5609c IMDisplay+0x5c8b
000000000023dfd0 000007feca608cf5 IMDisplay+0x609c

**##Author**
Name: Jiaqi Peng of VARAS@IIE
Organization: IIE(http://iie.ac.cn)

**Comment by mikayla-grace** [comment]
Send the crafted .jp2 image to or a URL to the image to ajdl27 at imagemagick.org.  We need to reproduce the problem before we can comment further.

**Comment by mikayla-grace** [comment]
Post this bug report to the OpenJPEG2 development team.  The library includes a utility, opj2_decompress, that shows a arithemetic exception fault in that library:

```
opj2_decompress -i PoC_divide_by_zero.jp2 -o image.pgm

[INFO] Start to read j2k main header (0).
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
[WARNING] tgt_create tree->numnodes == 0, no tree created.
[WARNING] No incltree created.
[WARNING] tgt_create tree->numnodes == 0, no tree created.
WARNING] No imsbtree created.
[INFO] Header of tile 1 / 1 has been read.
Floating exception (core dumped)
```

The trace confirms the bug within the OpenJPEG library:

```
Program received signal SIGFPE, Arithmetic exception.
0x00007ffff7bbffc2 in opj_pi_next () from /lib64/libopenjp2.so.7
(gdb) where
#0  0x00007ffff7bbffc2 in opj_pi_next () from /lib64/libopenjp2.so.7
#1  0x00007ffff7bc52a8 in opj_t2_decode_packets () from /lib64/libopenjp2.so.7
#2  0x00007ffff7bc9209 in opj_tcd_decode_tile () from /lib64/libopenjp2.so.7
#3  0x00007ffff7bb598b in opj_j2k_decode_tile () from /lib64/libopenjp2.so.7
#4  0x00007ffff7bb5c10 in opj_j2k_decode_tiles () from /lib64/libopenjp2.so.7
#5  0x00007ffff7bae12b in opj_j2k_exec () from /lib64/libopenjp2.so.7
#6  0x00007ffff7bb73e7 in opj_j2k_decode () from /lib64/libopenjp2.so.7
#7  0x00005555555567f2 in main ()
```

We are using OpenJPEG2 2.1.2-3 under Fedora.

Once the fault is fixed within OpenJPEG2, its likely ImageMagick will exit gracefully on a corrupt JP2 image.  In the mean-time, you can prevent ImageMagick from reading or writing JP2 images.  See https://www.imagemagick.org/script/security-policy.php.

**Comment by mikayla-grace** [comment]
Post this bug report to the OpenJPEG2 development team.  The library includes a utility, opj2_decompress, that shows a segmentation fault in that library:

```
opj2_decompress -i PoC_null_pointer_deference.jp2 -o image.pgm

[INFO] Start to read j2k main header (0).
[INFO] Main header has been correctly decoded.
[INFO] No decoded area parameters, set the decoded area to the whole image
WARNING -> [PGM file] Only the first component
           is written to the file
Segmentation fault (core dumped)
```

The trace confirms the bug within the OpenJPEG library:

```
Program received signal SIGFPE, Arithmetic exception.
0x00007ffff7bbffc2 in opj_pi_next () from /lib64/libopenjp2.so.7
(gdb) where
#0  0x00007ffff7bbffc2 in opj_pi_next () from /lib64/libopenjp2.so.7
#1  0x00007ffff7bc52a8 in opj_t2_decode_packets () from /lib64/libopenjp2.so.7
#2  0x00007ffff7bc9209 in opj_tcd_decode_tile () from /lib64/libopenjp2.so.7
#3  0x00007ffff7bb598b in opj_j2k_decode_tile () from /lib64/libopenjp2.so.7
#4  0x00007ffff7bb5c10 in opj_j2k_decode_tiles () from /lib64/libopenjp2.so.7
#5  0x00007ffff7bae12b in opj_j2k_exec () from /lib64/libopenjp2.so.7
#6  0x00007ffff7bb73e7 in opj_j2k_decode () from /lib64/libopenjp2.so.7
#7  0x00005555555567f2 in main ()
```

We are using OpenJPEG2 2.1.2-3 under Fedora.

Once the fault is fixed within OpenJPEG2, its likely ImageMagick will exit gracefully on a corrupt JP2 image.  In the mean-time, you can prevent ImageMagick from reading or writing JP2 images.  See https://www.imagemagick.org/script/security-policy.php.

**Comment by dlemstra** [comment]
Link to the bug report for OpenJPEG2: uclouvain/openjpeg#855
