### ISSUE TITLE
PS and EPS %%BoundingBox not being parsed

### ISSUE THREAD

**Issue by SJBUK42** [ImageMagick/ImageMagick#4961]
### ImageMagick version

7.1.0-26

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

The %%BoundingBox DSC in some Postscript files is being skipped due to a bug in the version parsing code in the ps coder. This  results in a default page size being assigned to the image rather than that specified in the bounding box.

In one example I have an EPS file with the following header:
...
%!PS-Adobe-1.0 EPSF-1.2\r%%BoundingBox: 0 0 600 900
...

Running identify.exe on this results in "EPT 612x792 612x792+0+0 8-bit sRGB 453.02KiB 0.000u 0:00.000", rather than "EPT 600x900 600x900+0+0 8-bit sRGB 453.02KiB 0.000u 0:00.000" as expected.

Looking in ps.c I can see that the version parsing code stops when it hits the '\r' but it doesn't set new_line=MagickTrue. Thus the parsing loop skips over the following %%BoundingBox DSC. until the next \r or \n. Looks like the same problem further down  when processing spot colour.

Code has not changed in 7.1.0-27. 

### Steps to Reproduce

Unzip owl.eps from the attached owl.zip archive.
Run:
identify owl.eps

### Images

[Owl.zip](https://github.com/ImageMagick/ImageMagick/files/8284190/Owl.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
