### ISSUE TITLE
Imagick segfault on Alpine Linux (--without-threads)

### ISSUE THREAD

**Issue by csandanov** [ImageMagick/ImageMagick#497]
Hi guys,

I'm getting a segfault error while using php extension imagick on Alpine Linux 3.4. The maintainer of imagick (@Danack) extension [referred](https://github.com/mkoppanen/imagick/issues/207#issuecomment-303055834) it as a bug in ImageMagick library on Alpine and recommended to compile it with `--without-threads` flag. The [similar issue](https://bugs.alpinelinux.org/issues/6021) was posted before in alpine's bug tracker.

After a look up in alpine repository turned out [it's already compiled](https://git.alpinelinux.org/cgit/aports/tree/main/imagemagick/APKBUILD?h=3.4-stable#n62) without threads support but as was noted by @Danack: 

> Apparently CreateMagickThreadKey still does stuff when threads aren't compiled in.
> 
> https://github.com/ImageMagick/ImageMagick/blob/ac23b02ecb741e5de60f5235ea443790c88a0b80/magick/thread.c#L145-L166.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
