### ISSUE TITLE
-format %c histograms

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#4973]
### ImageMagick version

7.1.0-20

### Operating system

Windows

### Operating system, version and so on

Windows 8.1

### Description

A simple sort of the text histogram no longer orders "1" before "14", etc. This applies whether using Windows "sort" or bash "sort".

```
magick rose: -format %c histogram:info: |sort >h2.txt
```

I think the difference is in MagickCore\histogram.c, function GetNumberColors(). In v6.9.9-40, this included:
```
    (void) ConcatenateMagickString(tuple,")",MaxTextExtent);
    (void) QueryMagickColorname(image,&pixel,SVGCompliance,color,exception);
    GetColorTuple(&pixel,MagickTrue,hex);
    (void) FormatLocaleFile(file,"%10.20g",(double) ((MagickOffsetType)
      p->count));
    (void) FormatLocaleFile(file,": %s %s %s\n",tuple,hex,color);
```
This has changed, so in v7.1.0-20 that section is:
```
    (void) ConcatenateMagickString(tuple,")",MagickPathExtent);
    (void) QueryColorname(image,&pixel,SVGCompliance,color,exception);
    GetColorTuple(&pixel,MagickTrue,hex);
    (void) sprintf(count,"%.20g:",(double) ((MagickOffsetType) p->count));
    (void) FormatLocaleFile(file,"    %s %s %s %s\n",count,tuple,hex,color);
```
Note the change from "%10.20g" to "%.20g:", so the minimum field width of "10", right-justified, has been removed. I don't know why or when that change was made.

I would like the change to be reverted.

### Steps to Reproduce

magick rose: -format %c histogram:info: |sort >h.txt

### Images

N/A

**Comment by urban-warrior** [comment]
Try this command:

```
magick rose: -format %c histogram:info: |sort -n >h2.txt
```

**Comment by snibgo** [comment]
Thanks. That works for bash sort, but not for Windows sort, which has no equivalent to "-n".

**Comment by urban-warrior** [comment]
A quick Google check returns a number of batch scripts that will sort by numeric rather than alphanumeric.

**Comment by dlemstra** [comment]
@urban-warrior Should we revert that change?

**Comment by urban-warrior** [comment]
The mod was made nearly 2 years ago.  Users are now accustomed to the current format.  If we revert, we will likely cause issues with modern users of ImageMagick 7.
