### ISSUE TITLE
uniconvertor missing

### ISSUE THREAD

**Issue by caltrop2075** [ImageMagick/ImageMagick#4992]
### ImageMagick version

8:6.9.10.23

### Operating system

Linux

### Operating system, version and so on

Mint 20.1

### Description

for some reason THEY have removed lots of stuff from the repositories especially Python

now some of Image Magick is broken because UNICONVERTOR IS GONE!

### Steps to Reproduce

convert some vector graphics
always

### Images

meh...

**Comment by dlemstra** [comment]
We don't maintain what is installed in the Mint distribution.

**Comment by caltrop2075** [comment]
where do we get uniconvertor that Image Magick Convert needs?

if Image Magic needs it it should be included



I know though don't have any control over repositories, duh...

Liz
🤪🔥💥💀
