### ISSUE TITLE
Incorrect string formats for statistics for 10-bit depth images

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#4994]
### ImageMagick version

7.1.0-8

### Operating system

MacOS

### Operating system, version and so on

Sierra

### Description

I have a 10-bit depth DPX image. It does not produce the correct %[max] and %[min] etc statistics

[RNST_SDI_20220303_145749.DPX.zip](https://github.com/ImageMagick/ImageMagick/files/8358150/RNST_SDI_20220303_145749.DPX.zip)

Here is the verbose information, which is correct. Note the Depth of 10/16-bit. The max value is 545 (0.532753) for the overall statistic, which is correct.

identify -verbose RNST_SDI_20220303_145749.DPX

Image:
  Filename: RNST_SDI_20220303_145749.DPX
  Format: DPX (SMPTE 268M-2003 (DPX 2.0))
  Class: DirectClass
  Geometry: 1729x981+0+0
  Units: Undefined
  Colorspace: RGB
  Type: TrueColor
  Endianness: LSB
  Depth: 10/16-bit
  Channel depth:
    red: 10-bit
    green: 10-bit
    blue: 10-bit
.
.
.  
Image statistics:
    Overall:
      min: 458  (0.4477)
      max: 545 (0.532753)
      mean: 517.658 (0.506019)
      standard deviation: 12.3196 (0.0120426)
      kurtosis: 0.144879
      skewness: -0.632984
      entropy: 0.874075
...

Now check the value using %[fx:maxima] for 10-bit depth, which is also correct:
 
```
convert RNST_SDI_20220303_145749.DPX -format "%[fx:(2^10-1)*maxima]\n" info:
545.007

```

**Now use the string format %[max], which is giving the 16-bit equivalent, not the 10-bit value.**

```
convert RNST_SDI_20220303_145749.DPX -format "%[max]\n" info:
34914

```
I can prove that using %[fx:maxima],

```
convert RNST_SDI_20220303_145749.DPX -format "%[fx:(2^16-1)*maxima]\n" info:
34914
```

**Should %[maxima] not properly return the value according to the actual bit-depth?**

### Steps to Reproduce

See above

### Images

See above

**Comment by snibgo** [comment]
For 10-bit inputs, IM "-format %[max]" has reported a number on a scale of 0 to QuantumRange since at least v6.9.0, and probably earlier.

I suppose it always worked that way, and a change would break scripts.

**Comment by fmw42** [comment]
Perhaps. But is that result not wrong for the odd cases when the bit-depth is not in line with the QuantumRange?

**Comment by snibgo** [comment]
After an image has been read into memory, it seems logical to me that %[max] should be the maximum of the pixel values in memory. At that time, the bit depth of the image in the file is no longer relevant.
