### ISSUE TITLE
IM7 upgrade notes for changed functions

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#5]
Hi, 
The upgrade notes for migrating an application, that uses the Magick API, from 6 to 7 don't cover a couple of things.

These functions are no longer available:
* MagickSetImageBias
* MagickSetImageClipMask
* DrawMatte

Do they have equivalent methods, and/or could their removal be documented?

The functions below have changed method signatures (which I can probably guess the meaning of). Are they going to be documented on the page http://www.imagemagick.org/script/magick-wand.php or will you make a page specific to the 7 Magick API?

```
MagickAddNoiseImage(MagickWand *wand, const NoiseType noise_type)
//changed to
MagickAddNoiseImage(MagickWand *,const NoiseType,const double)


MagickClutImage(MagickWand *wand, const MagickWand *clut_wand)
//change to
MagickClutImage(MagickWand *,const MagickWand *,const PixelInterpolateMethod)


WandExport MagickBooleanType MagickCompositeImage(MagickWand *wand,
  const MagickWand *source_wand,const CompositeOperator compose,const ssize_t x,
  const ssize_t y)
//changed to
MagickCompositeImage(MagickWand *,const MagickWand *,const CompositeOperator,
    const MagickBooleanType clip_to_self,const ssize_t,const ssize_t),
 ```

**Comment by urban-warrior** [comment]
See http://www.imagemagick.org/ImageMagick-7.0.0/script/magick-wand.php.  Use DrawAlpha() instead of DrawMatte().

**Comment by Danack** [comment]
Ok thanks for the link.

Presumably MagickSetImageBias has gone away because the convolve function now takes a kernel as the parameter, and if someone wants a bias setting, they can just set a bias on the kernel. Is that correct?

Which would just me confused by how to migrate code that use MagickSetImageClipMask to 7.

**Comment by Danack** [comment]
Also, could you provide some guidance on how to handle functionality that was previously dependent on [MagickSetImageIndex](http://www.imagemagick.org/api/magick-deprecate.php#MagickSetImageIndex) which has been deprecated for a while.

Is the correct thing to do to just iterate over the images in the wand, and effectively do the image index setting externally?

**Comment by urban-warrior** [comment]
Use SetImageOption() with "convolve:bias" to add bias to your kernels or just add the bias directly to your kernels.

Use MagickSetIteratorIndex() instead of MagickSetImageIndex().

**Comment by Danack** [comment]
Thanks
