### ISSUE TITLE
ImageMagick 7 fails to convert linked image from SVG to PDF(IM6 works fine)

### ISSUE THREAD

**Issue by guruas3** [ImageMagick/ImageMagick#5003]
### ImageMagick version

7.1.0-29

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04.4 LTS

### Description

I've put all the necessary details in discussion. Then realized that it might be just an unknown bug. Please check #5001

### Steps to Reproduce

`magick -verbose test.svg test.pdf`

### Images

[test-im7-inkscape.pdf](https://github.com/ImageMagick/ImageMagick/files/8389749/test-im7-inkscape.pdf)
[test-im6.pdf](https://github.com/ImageMagick/ImageMagick/files/8389750/test-im6.pdf)
[test-im7.pdf](https://github.com/ImageMagick/ImageMagick/files/8389751/test-im7.pdf)
[test.svg](https://user-images.githubusercontent.com/981231/161065036-dfcec002-03a1-4b96-9c21-a526d241c567.svg)

**Comment by dlemstra** [comment]
There is no need to create a discussion and an issue.

**Comment by guruas3** [comment]
yeah sorry. i thought it might be lost there if it's a bug.
