### ISSUE TITLE
NoDecodeDelegateForThisImageFormat `' @ error/blob.c/BlobToImage/458

### ISSUE THREAD

**Issue by cuizhiqiang0** [ImageMagick/ImageMagick#5007]
### ImageMagick version

7.0.8-62

### Operating system

Linux

### Operating system, version and so on

 Debian GNU/Linux 8.11

### Description

picture url = "https://images.xinglinpukang.com/upload/doctor/auth/202004/20200428091622515_s.jpg"
content is the content for the picture
The code is:
Magick::Blob blob(content.c_str(), content.size());
image.quiet(true);
image.read(blob);

then I got  "NoDecodeDelegateForThisImageFormat `' @ error/blob.c/BlobToImage/458" 
I test a lot of pics and it works fine, only this pic throws exception. So I wonder what's special about this picture？

### Steps to Reproduce

https://images.xinglinpukang.com/upload/doctor/auth/202004/20200428091622515_s.jpg

**Comment by dlemstra** [comment]
Attaching file: [20200428091622515_s.zip](https://github.com/ImageMagick/ImageMagick/files/8399045/20200428091622515_s.zip)

**Comment by dlemstra** [comment]
I suspect this has to do with how you are reading the file. On the command line I can read the file without any issues.

**Comment by Cppowboy** [comment]
I have the same problem, do you have any solutions?
