### ISSUE TITLE
dng coder support GPS info

### ISSUE THREAD

**Issue by zmdyy0318** [ImageMagick/ImageMagick#5008]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

hello, im using IM to get RAW image meta info, but some image cant get GPS info.
i debug "magick identify -verbose path_to_file/file.dng".
i notice "coder/dng.c" "SetDNGProperties" function  not save GPS info, but the param "raw_info->other->parsed_gps" have GPS info.
"SetImageProperty(parsed_gps->latitude)
SetImageProperty(parsed_gps->longitude)
SetImageProperty(parsed_gps->altitude)" will support this.
i really want this value, thanks.
dng file here:
[pic.zip](https://github.com/ImageMagick/ImageMagick/files/8402214/pic.zip)

### Describe alternatives you've considered

EXIFTOOL is a  good idea, but im IMAGEMAGICK fan!

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
