### ISSUE TITLE
Broken option for AVIF endofing

### ISSUE THREAD

**Issue by raui100** [ImageMagick/ImageMagick#5013]
### ImageMagick version

7.1.0-29

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

As described in #3076 I can use `-quality 100` for lossless AVIF conversion. However using `avif:lossless=true` leads to a lossy conversion, which is unexpected

### Steps to Reproduce

```bash
# Lossless conversion
magick rose: -quality 100 lossless.webp

# Lossy conversion
magick rose: -define avif:lossless=true lossy.webp

# Comparing pictures
identify rose: lossless.webp lossy.webp

> rose:=>ROSE PNM 70x46 70x46+0+0 8-bit sRGB 9673B 0.000u 0:00.000
> lossless.webp WEBP 70x46 70x46+0+0 8-bit sRGB 6332B 0.000u 0:00.000
> lossy.webp WEBP 70x46 70x46+0+0 8-bit sRGB 906B 0.000u 0:00.000
```

**Comment by dlemstra** [comment]
There is no `avif:lossless` option so this is the expected behavior.
