### ISSUE TITLE
Convert not working as expected

### ISSUE THREAD

**Issue by rprasanth** [ImageMagick/ImageMagick#5016]
### ImageMagick version

ImageMagick-7.1.0-29

### Operating system

Linux

### Operating system, version and so on

Custom-Linux 4.14kernel

### Description

I'm trying to create a sample hello-world .bmp file, Which we used to earlier. in Imagemagic-6 which work good.
But in the recent versions, I could see the "convert" binary was not working as expected.

Could you help me to fix the issue?

I have traced down the versions
```
# convert -v | head
Version: ImageMagick 7.0.8-62 Q16 armv7l 2022-04-05 https://imagemagick.org
```
Till this v7.0.8-62, convert creates me a .bmp file with "Hello World" output. Later this version it fails.
Hope this will help to trace down the bug easily.

### Steps to Reproduce

In version 7.1.0-29
```
convert -background black -fill white -font Droid-Sans-Bold -pointsize 14 -gravity center -size 800x caption:"HELLO WORLD" BMP3:test.bmp
```

in version 6*

```
convert -background black -fill white -font Droid-Sans-Bold -pointsize 14 -gravity center -size 800x caption:"HELLO WORLD" BMP3:test-6.bmp
```

same command for both, old works, latest fails. Check the images sections

### Images

not-working
[test.bmp.zip](https://github.com/ImageMagick/ImageMagick/files/8418233/test.bmp.zip)

working
[test-6.bmp.zip](https://github.com/ImageMagick/ImageMagick/files/8418234/test-6.bmp.zip)

**Comment by fmw42** [comment]
I suggest you use "magick" in place of "convert" in IM 7.  Also please supply your font file for testing properly.

**Comment by urban-warrior** [comment]
We rely on Freetype 2 to return font metrics.  Freetype is not returning expected results for this font.  We tried Carlito-Bold instead and got expected results.  We also downloaded another version of droid-sans-bold off the internet, it also worked.  We're not sure why Freetype does not like Google's version of droid-sans-bold.

**Comment by rprasanth** [comment]
> I suggest you use "magick" in place of "convert" in IM 7. Also please supply your font file for testing properly.

Same issue. Could you get the image correctly?
[truetype.zip](https://github.com/ImageMagick/ImageMagick/files/8423485/truetype.zip)

**Comment by rprasanth** [comment]
> Carlito-Bold

# convert -v |head
Version: ImageMagick 7.0.10-23 Q16 armv7l 2022-04-05 https://imagemagick.org

# freetype 2.10.4

I too use the FreeType version 2, Still the same issue, I tried the same font from Google as you mentioned. Both fail.
Could you share yours, please

https://www.fontsquirrel.com/fonts/carlito
https://www.dafontfree.net/droid-sans-bold/f153446.htm#google_vignette

**Comment by urban-warrior** [comment]
This seems for work for us: https://www.dafontfree.net/data/29/d/153446/DroidSans-Bold.ttf.

**Comment by rprasanth** [comment]
Sorry and Thanks, guys. 
Identified the issue, It was MagickCore/locale.c file customization, in which I added locale.h to resolve my build issue with uClibc.
