### ISSUE TITLE
Invalid PAM combination (MAXVAL vs TUPLTYPE)

### ISSUE THREAD

**Issue by malaterre** [ImageMagick/ImageMagick#5027]
### ImageMagick version

6.9.11.60

### Operating system

Linux

### Operating system, version and so on

Debian

### Description

```
% convert -colorspace Gray -colors 1 -depth 12 -size 512x512 xc:white white12.tif
% convert white12.tif white12.pam
% head -6 white12.pam
P7
WIDTH 512
HEIGHT 512
DEPTH 1
MAXVAL 4095
TUPLTYPE BLACKANDWHITE
```

pam specs states:

[...]
A black and white image, such as would alternatively be represented by a PBM image, has a tuple type of "BLACKANDWHITE". Such a PAM image has a depth of 1 and maxval 1 
[...]

* http://netpbm.sourceforge.net/doc/pam.html

So the only two valid combinations are:

```
MAXVAL 4095
TUPLTYPE GRAYSCALE
```
or

```
MAXVAL 1
TUPLTYPE BLACKANDWHITE
```

### Steps to Reproduce

```
% convert -colorspace Gray -colors 1 -depth 12 -size 512x512 xc:white white12.tif
% convert white12.tif white12.pam
```

### Images

use a monochrome image to reproduce.

**Comment by malaterre** [comment]
As a side note I do not see how to generate a white/grayscale image using P7 header.

Compare:

```
% convert -depth 12 -size 512x512 xc:white white12.pgm
% convert -depth 12 -size 512x512 xc:white white12.pam
```

gives:

```
% head -3 white12.pgm
P5
512 512
4095
```

while

```
% head -7 white12.pam
P7
WIDTH 512
HEIGHT 512
DEPTH 3
MAXVAL 4095
TUPLTYPE RGB
ENDHDR
```

**Comment by fmw42** [comment]
Text PGM has P2 not P7.  See http://netpbm.sourceforge.net/doc/pgm.html

You can do that by adding -compress none.

```
convert -depth 12 -size 512x512 xc:white -compress none x.pgm

head -3 x.pgm
P2
512 512
65535

```

**Comment by malaterre** [comment]
@fmw42 I want PAM header not PNM header:

* http://netpbm.sourceforge.net/doc/pam.html

**Comment by fmw42** [comment]
Same thing to do - add -compress none!

```
convert -depth 12 -size 512x512 xc:white -compress none x.pam

head -7 x.pam
P7
WIDTH 512
HEIGHT 512
DEPTH 3
MAXVAL 4095
TUPLTYPE RGB
ENDHDR

```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
