### ISSUE TITLE
DrawSetFont function with Chinese file path

### ISSUE THREAD

**Issue by zmdyy0318** [ImageMagick/ImageMagick#5028]
### ImageMagick version

7.1.0-29 visual magick build version

### Operating system

Windows

### Operating system, version and so on

windows visual studio error, macos ok

### Description

font name is "字体.ttf" can not draw anything，but same file "aaaaa.ttf" success.
i debug the code:
when i give UTF-8 to DrawSetFont, "MagickCore/annotate.c -> RenderFreetype() -> 1470 FT_Open_Face" return error.
when i give GB2312 to DrawSetFont, "MagickCore/annotate.c -> RenderType() -> 997 IsPathAccessible" return error

maybe freetype need GB2312 path, bug ImageMagick need UTF-8 path

here is one font file with two diff name, only english success:
[font_file.zip](https://github.com/ImageMagick/ImageMagick/files/8449393/font_file.zip)

### Steps to Reproduce

my code:
```
std::string local_path = u8"path/to/my/file/字体.ttf";
std::string content = "aaaaa";
MagickWand* magick_wand = NewMagickWand();
DrawingWand* d_wand = NewDrawingWand()
PixelWand* p_wand = NewPixelWand();
PixelSetColor(p_wand, "rgb(230,230,230)");
MagickNewImage(magick_wand, 320, 320, p_wand);
DrawSetFontSize(d_wand, 60);
DrawSetTextInterlineSpacing(d_wand, 32);
DrawSetTextAlignment(d_wand, CenterAlign);
DrawAnnotation(d_wand, 160, 160 - 32, (const unsigned char*)content.c_str());
MagickDrawImage(magick_wand, d_wand);
MagickWriteImage(magick_wand,"111111.png");
```

**Comment by dlemstra** [comment]
Are you sure that you have the correct file name on Windows? 
![afbeelding](https://user-images.githubusercontent.com/10426229/162398814-3b32d82d-6059-4c6e-8a6e-ae367276a7c3.png)
The zip you provided contained an invalid file name. I copied and renamed the first file and I can run your code without any issues.

**Comment by zmdyy0318** [comment]
> Are you sure that you have the correct file name on Windows? ![afbeelding](https://user-images.githubusercontent.com/10426229/162398814-3b32d82d-6059-4c6e-8a6e-ae367276a7c3.png) The zip you provided contained an invalid file name. I copied and renamed the first file and I can run your code without any issues.

![image](https://user-images.githubusercontent.com/16699676/162416019-05a80655-6c22-4d7f-904d-454fdd24ad45.png)


My System Language is "Chinese(Simplified, China)"，Extract "font_file.zip" is right.
But when i choose "English(United States)", Extract "font_file.zip" is wrong as you.

Then i search on Google.

Chinese Language use gb2312 in system.
English Language use utf-8 in system.

BUT

"FT_Open_Face" use "fopen" to open file. "fopen" file path base on system encoding.

SO

My Chinese System TTF_PATH(utf8) -> DrawSetFont(utf8) -> RenderFreetype(utf8) -> FT_Open_Face(error, system need gb2312)
Your English System TTF_PATH(utf8) -> DrawSetFont(utf8) -> RenderFreetype(utf8) -> FT_Open_Face(utf8, system need utf8)

i have some idea to fix this:
1. utf8 string to local(maybe utf8, maybe gb2312) string before "FT_Open_Face".
2. use func like "_wfopen" to open wide path file, then using "FT_OPEN_STREAM" arg to "FT_Open_Face".

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
