### ISSUE TITLE
-region not working

### ISSUE THREAD

**Issue by jox81** [ImageMagick/ImageMagick#503]
Hello, 
Using ImageMagick-7.0.5-9-Q16-x64 on windows 10 the following command doesn't work correctly : 
`magick logo: -region '100x200+10+20' -negate wizNeg1.png`

All the image is negated...

Jox

**Comment by mikayla-grace** [comment]
Until we get a patch prepared, use this command instead:

```
convert logo: -type truecolor -region '100x200+10+20'  -negate wizNeg1.png
```

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
