### ISSUE TITLE
-draw in alpha

### ISSUE THREAD

**Issue by jox81** [ImageMagick/ImageMagick#504]
Hello, 

Using ImageMagick-7.0.5-9-Q16-x64 on windows 10 

I'm trying to find a "singleline" command to draw a rectangle in the alpha channel. 

This work in the rgb channel :
`-alpha opaque -fill 'rgba( 0, 0, 0 , 0.5 )' -draw 'rectangle 66,50 200,150' `

This work in the alpha channel :
`-alpha opaque -fill 'rgba( 0, 0, 0 , 0.5 )' -draw 'alpha 4,4 point' `

I don't know if this is possible, but how can i draw a rectangle directly in the alpha channel ?
i.e, this cause an error
`-alpha opaque -fill 'rgba( 0, 0, 0 , 0.5 )' -draw 'alpha rectangle 66,50 200,150' `

Thanks in advance 
:D

**Comment by fmw42** [comment]
Unix syntax, assuming your image is opaque to start. Below I used the ImageMagick internal image logo: . You can replace it with image.suffix

```
convert logo: -alpha set \
\( +clone -alpha extract -fill black -draw "translate 320,240 rectangle -100,-100 100,100" \) \
-alpha off -compose copy_opacity -composite result.png
```

For windows, replace the end of line \ with ^ and remove the \ from the parens.
