### ISSUE TITLE
logical conditions always false 

### ISSUE THREAD

**Issue by maddin200** [ImageMagick/ImageMagick#505]
\MagickCore\cache.c line 2680
 if (virtual_nexus == (NexusInfo **) NULL)
    {
      if (virtual_nexus != (NexusInfo **) NULL)
       virtual_nexus=DestroyPixelCacheNexus(virtual_nexus,1);  // always false

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
