### ISSUE TITLE
ImageMagick does not compile because "treat warnings as errors"

### ISSUE THREAD

**Issue by he-igel** [ImageMagick/ImageMagick#5050]
### ImageMagick version

7.1.0.30 and a few before

### Operating system

Windows

### Operating system, version and so on

win10 - vs2022

### Description

build and run VisualMagick\configure\configure.exe
=> VisualStaticMT.sln is created
This solution cannot be compiled because some projects have the option "treat warnings as errors" set
after removing this option from all projects, it compiles fine.

### Steps to Reproduce

see description

**Comment by dlemstra** [comment]
We have a daily build where we build ImageMagick on Windows. We are not getting any warnings in that build. What kind of warnings are you getting?

**Comment by he-igel** [comment]
35>------ Build started: Project: CORE_filters, Configuration: Debug x64 ------
35>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): error C2220: the following warning is treated as an error
35>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: macro expansion producing 'defined' has undefined behavior
34>C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): error C2220: the following warning is treated as an error (compiling source file ..\..\ImageMagick\MagickWand\animate.c)

![ScreenCapture_004](https://user-images.githubusercontent.com/17963897/163781148-e7298009-329f-41aa-9771-4c16fe6c3008.jpg)

**Comment by dlemstra** [comment]
It looks like you are getting this error because of an issues the Windows SDK. Can you upgrade this?

**Comment by he-igel** [comment]
i have installed the latest win10 sdk : 10.0.20348.0
and it works fine.

THANK YOU VERY MUCH.

but i wonder: i have some other projects on the machine ( own and foreign ) 
and they all compile fine with the older sdk.
