### ISSUE TITLE
Can't exclude unwanted PNG chunk: orNT

### ISSUE THREAD

**Issue by geitda** [ImageMagick/ImageMagick#5052]
### ImageMagick version

7.1.0-30

### Operating system

Windows

### Operating system, version and so on

Windows 10 Pro 21H2 64-bit

### Description

ImageMagick sometimes outputs PNG files that include a private, ancillary, unsafe-to-copy chunk 'orNT' that cannot be removed or omitted. Once a PNG has this orNT chunk, ImageMagick cannot be used to remove it.

### Steps to Reproduce

`magick convert example.jpg example.png` where example.jpg has some orientation metadata in it that causes the PNG encoder to include an 'orNT' chunk. Note that `magick convert logo: logo.png` does not have this chunk, so IM appears to not just "invent" an orientation for all outputs.
Neither `-strip` nor `-define png:include-chunk=none` nor `-define png:exclude-chunk=orNT` work to get rid of it, either on the initial JPG-to-PNG conversion, or any subsequent PNG-to-PNG convert or mogrify command.
Documentation for the `png:include-chunk` [1] states that `-strip` is equivalent to `-define png:exclude-chunk=EXIF,iCCP,iTXt,sRGB,tEXt,zCCP,zTXt,date` so it is not surprising that it doesn't work, but it is surprising that 'orNT' is not on that list.

The fix should add the 'orNT' chunk as a recognized chunk for the `png:exclude-chunk` and `png:include-chunk` defines and should probably get added to the list of chunks that are excluded when using `-strip` by the rationale that `-strip` should not output _private_, ancillary, **_unsafe-to-copy_** chunks, but this can be subject to debate. Likewise, the exact behavior for `png:include-chunk` can also be defined in any manner that makes sense, but `png:exclude-chunk` should do what it says. Update list of known ancillary chunks in the defines [1].

[1] https://imagemagick.org/script/defines.php

### Images

![example](https://user-images.githubusercontent.com/44627194/163860936-b428e6f3-3479-4a20-82d0-0f720b1fcdc9.jpg)

**Comment by urban-warrior** [comment]
The orNT chunk is a private chunk used within ImageMagick to specify the image orientation.  To exclude it, set the orientation to undefined, e.g. `-orient undefined`.

**Comment by geitda** [comment]
`-orient undefined` works to remove this chunk: thank you for providing this solution.
Nothing in the documentation suggests that having an orientation will include this chunk or that undefining it will remove it. It's not listed in the `png:include-chunk` documentation, whereas there's plenty of other chunks that have good documentation for when to expect those to be automatically included or excluded.
At the very least, the statement, "The ancillary chunks currently known to ImageMagick are `bKGD`, `cHRM`, `gAMA`, `iCCP`, `oFFs`, `pHYs`, `sRGB`, `tEXt`, `tRNS`, `vpAg`, and `zTXt`" is not correct as IM "knows" `orNT` but you have to use a different mechanism to modify it.
I'm also still strongly leaning towards expecting `-strip` to exclude the orNT chunk as it's _private and unsafe-to-copy_.
So this bug report is now down to, "make the documentation more complete, and think about changing the `-strip` behavior." If that's more "enhancement" than "bug," this can be (re)tagged appropriately.

**Comment by urban-warrior** [comment]
We updated the documentation to mention the `orNT` chunk.  Thanks for alerting us to the documentation deficiency.
