### ISSUE TITLE
assertion failed in WriteBlob

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#506]
On version: ImageMagick 7.0.5-10 , a crafted file revealed an assertion failure in blob.c.

```
#convert $FILE out.mvg
convert: MagickCore/blob.c:5171: ssize_t WriteBlob(Image *, const size_t, const void *): Assertion `data != (const void *) ((void*)0)' failed.
Aborted
```

testcase : https://github.com/bestshow/p0cs/blob/master/assertion-failed-in-WriteBlob-blob5171_7_0_5_10
Credit : ADLab of Venustech

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
