### ISSUE TITLE
convert png to jpeg but get a bigger file

### ISSUE THREAD

**Issue by zcony3** [ImageMagick/ImageMagick#5076]
### ImageMagick version

7.0.10-27

### Operating system

MacOS

### Operating system, version and so on

Monterey

### Description

use the following command convert png image to jpeg, we want to get a smaller file, but it get bigger. 
usually, we think convert to jpeg smaller than png image, why this image become bigger

`convert 100301239105.png -quality 75 -strip 100301239105.jpg`

### Steps to Reproduce

`convert 100301239105.png -quality 75 -strip 100301239105.jpg`

### Images

![100301239105](https://user-images.githubusercontent.com/34224625/164971135-dfdeb45d-c2b2-4fac-8e43-737a992ace8b.png)

**Comment by snibgo** [comment]
JPG compression is designed for photographs. PNG compression is designed for graphics.

The program "pngcrush" can reduce the size of the PNG file by 30%.

**Comment by zcony3** [comment]
> JPG compression is designed for photographs. PNG compression is designed for graphics.
> 
> The program "pngcrush" can reduce the size of the PNG file by 30%.

Thanks for you replay, we have to change png to jpeg in some cases. Can we tell what kind of PNG convet to JPG will become bigger?

**Comment by snibgo** [comment]
For JPG, photographs compress well, and graphics do not.

Photographs have most information in their lightness, not in hue or saturation. Photographs do not have massive swings in hue or saturation.
