### ISSUE TITLE
not modified alpha

### ISSUE THREAD

**Issue by jox81** [ImageMagick/ImageMagick#508]
Hello,
Using ImageMagick-7.0.5-9-Q16-x64 on windows 10 the following command doesn't work correctly on a png with alpha image : 
`magick imageWithAlpha.png -brightness-contrast 100x0 wizAlpha1.png`

All the image is white opaque, the alpha is modified. 

Now I must specify explicitly to change only the rgb channel as 
`magick imageWithAlpha.png -channel rgb -brightness-contrast 100x0 wizAlpha1.png`

in v6, alpha was kept correctly

Jox

**Comment by mikayla-grace** [comment]
The change in behavior between IMv6 and IMv7 is documented in the porting guide @ https://www.imagemagick.org/script/porting.php:

> Most algorithms update the red, green, blue, black (for CMYK), and alpha channels. Most operators will blend alpha the other color channels, but other operators (and situations) may require this blending to be disabled, and is currently done by removing alpha from the active channels via -channel option. (e.g. convert castle.gif -channel RGB -negate castle.png).
