### ISSUE TITLE
Can't convert the endianess of DPX

### ISSUE THREAD

**Issue by alexhabgood** [ImageMagick/ImageMagick#5090]
### ImageMagick version

7.1.0-29

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04

### Description

Using the following command, doesn't convert a DPX file from big to little endianess:

`convert input.dpx -endian LSB output.dpx`

When I subsequently open the file in mediainfo, it still says the DPX is big endian.

Any ideas whats going wrong?

### Steps to Reproduce

Step 1 
`convert input.dpx -endian lsb output.dpx`

Step 2
Open file in mediainfo.

**Comment by dlemstra** [comment]
Can you share input.dpx?
