### ISSUE TITLE
Ghostscript Load Error with GBK path

### ISSUE THREAD

**Issue by zmdyy0318** [ImageMagick/ImageMagick#5092]
### ImageMagick version

7.1.0-29

### Operating system

Windows

### Operating system, version and so on

windows10, system encoding GBK

### Description

In Chinese system(local encoding is GBK), ghostscript default using "Local Encoding"(GBK) to read UTF8 Chinese path, to fix this:
1、MagickCore/delegate-private.h "GhostInfo" add
```
  int
    (MagickDLLCall* set_arg_encoding)(gs_main_instance*, int);
```

2、coders/ghostscript-private.h "InvokeGhostscriptDelegate" add between "ghost_info->set_stdio" and "ghost_info->init_with_args"
```
//enum {
//    GS_ARG_ENCODING_LOCAL = 0,
//    GS_ARG_ENCODING_UTF8 = 1,
//    GS_ARG_ENCODING_UTF16LE = 2
//};
ghost_info->set_arg_encoding(interpreter, 1);
```

3、MagickCore/nt-base.c "NTGhostscriptDLLVectors" add
```
ghost_info.set_arg_encoding = (int (MagickDLLCall*)(gs_main_instance*, int)) (
    lt_dlsym(ghost_handle, "gsapi_set_arg_encoding"));
```

### Steps to Reproduce

1.change system encoding to GBK.
![image](https://user-images.githubusercontent.com/16699676/165687889-6dc69a83-60a2-4833-8596-d6665a9f4d2a.png)

2.set temporary-path to chinese path.
```
ExceptionInfo* exception = AcquireExceptionInfo();
SetImageRegistry(StringRegistryType, "temporary-path", u8"C:\\temp\\测试", exception);
exception = DestroyExceptionInfo(exception);
```

3.put gsdll64 somewhere.
`_putenv("MAGICK_GHOSTSCRIPT_PATH=C:\\gspath");`

4.load file like "sample.eps", using GS to load.
[sample.zip](https://github.com/ImageMagick/ImageMagick/files/8579997/sample.zip)
```
MagickBooleanType status = MagickReadImage(magick_wand.get(), "D:\\temp\\sample.eps");
if (status == MagickFalse) {
	char* description;
	ExceptionType severity;
	description = MagickGetException(magick_wand.get(), &severity);
	assert(0);
	description = (char*)MagickRelinquishMemory(description);
}
```

5.status return false, "description,s8"(description with UTF8) here
```
PostscriptDelegateFailed `[ghostscript library 9.55] -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pamcmyk32" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -dFirstPage=1 -dLastPage=1 -dEPSCrop  "-sOutputFile=C:/temp/测试/magick-ofISxA07gJC6sswxUVcZh4fkjx0vlNqk%d" "-fC:/temp/测试/magick-2M0EuKHvU8b9DWCpx7Ra20dDJiw2Hn6h" "-fC:/temp/测试/magick-fKHqPUxlwT31ohGiAJqcIRGzojZ-g92f"': Error: /undefinedfilename in (C:/temp/\345\250\264\345\254\255\347\230\257/magick-2M0EuKHvU8b9DWCpx7Ra20dDJiw2Hn6h)
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push
Dictionary stack:
   --dict:771/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--
Current allocation mode is local
Last OS error: No such file or directory
GPL Ghostscript 9.55.0: Unrecoverable error, exit code 1
 @ error/ghostscript-private.h/InvokeGhostscriptDelegate/181
```

**Comment by dlemstra** [comment]
Thanks for your help with solving this. I have added the patches that you suggested. Next time feel free to create a pull request for these kind of changes.
