### ISSUE TITLE
convert file.png file.jpg doesn't seem to output a jpg

### ISSUE THREAD

**Issue by ingolfured** [ImageMagick/ImageMagick#51]
I have a png file `image.png` and when I run

    convert image.png image.jpg

I get a new file, `image.jpg` of size, 30% bigger than the `image.png`. However, when I run 

    file image.jpg

it outputs

    image.jpg: PNG image data, 544 x 184, 8-bit/color RGBA, non-interlaced

Am I doing something wrong? `convert --version` gives me

    Version: ImageMagick 6.9.2-5 Q16 x86_64 2015-10-29 http://www.imagemagick.org
    Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
    License: http://www.imagemagick.org/script/license.php
    Features: Cipher DPC HDRI Modules OpenMP 
    Delegates (built-in): bzlib djvu fftw fontconfig freetype jp2 lcms ltdl lzma openexr pangocairo png webp wmf x xml zlib

**Comment by glennrp** [comment]
It appears that you built ImageMagick without jpeg support.

**Comment by ingolfured** [comment]
Great, my bad. Thanks a lot!
