### ISSUE TITLE
API/ABI problem

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#510]
Hi,

Magick++/lib/Magick++/color.h declare constructors has:
  // Construct Color using the specified RGB values
    Color(Quantum red_,Quantum green_,Quantum blue_);

    // Construct Color using the specified RGBA values
    Color(Quantum red_,Quantum green_,Quantum blue_,Quantum alpha_);
instead of:
  // Construct Color using the specified RGB values
    Color(Magick::Quantum red_,Magick::Quantum green_,Magick::Quantum blue_);

    // Construct Color using the specified RGBA values
    Color(Magick::Quantum red_,Magick::Quantum green_,Magick::Quantum blue_,Magick::Quantum alpha_);

Correcting this is needed for a API point of view (API is not consistant accross quantum buiit) but it will need a so bump of magick++ lib

Bastien

**Comment by bastien-roucaries** [comment]
Ping

**Comment by dlemstra** [comment]
Can you clarify why we need to change this? Magick::Quantum and Quantum are the same type.

**Comment by bastien-roucaries** [comment]
dlemstra: they are the same type but symbols emited are not the same... You should use Magick::Quantum that is independant of size of int due to an obscrure rule of c++ ABI

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by bastien-roucaries** [comment]
Could you revert please ? This is note the right way to do... And could you separate the two issue the fix for #510 is fine the fix for #493 is not fine...

**Comment by bastien-roucaries** [comment]
This one could be closed I think
