### ISSUE TITLE
BUG: Background kept when distorting

### ISSUE THREAD

**Issue by luco** [ImageMagick/ImageMagick#5110]
### ImageMagick version

7.1.0-29

### Operating system

MacOS

### Operating system, version and so on

macOS Monterey

### Description

I'm trying to make a cylinder wrap via ImageMagick. It's working fine on creating the cylinder, but it's keeping the original image on back.

### Steps to Reproduce

```
magick \
-verbose \
\( \
      -size 2585x1181 \
      xc:blue \
      \( \
         ./images/test.png \
         -geometry +820+0 \
      \) \
      -composite \
      -geometry 730x390 \
      -roll -230+0 \
      -crop 270x408+0+0 \
      +append \
\) \
-gravity south -background Transparent -splice 0x40 \
\( +clone -sparse-color barycentric '0,0 black 273,0 white' \) \
\( -clone 1 -function arcsin 0.5 \) \
\( -clone 1 -level 0%,100% \
            -function polynomial -4,4,0 -gamma 2 \
            +level 50%,0%  \) \
-delete 1 \
-virtual-pixel Transparent \
-define compose:args=0x40 \
-compose Displace \
-composite \
./output/out.png
```

### Images

![image](https://user-images.githubusercontent.com/246373/166393858-41571bc3-a59b-4890-b322-df785c281b8b.png)

**Comment by fmw42** [comment]
This is not a bug. It is just the way the math works. This post should be closed or at least moved to the discussions.

**Comment by fmw42** [comment]
Post your input image. With a change of code one ought to be able to make the background transparent. I need to be able to test your code.

**Comment by luco** [comment]
![test](https://user-images.githubusercontent.com/246373/166401697-4b703395-1207-4655-a9f7-5c426ea8bd40.png)

@fmw42 There you go.

**Comment by fmw42** [comment]
This will let you use any opaque color for the background (but not transparent).

```
magick \
-verbose \
\( \
      -size 2585x1181 \
      xc:magenta \
      \( \
         test.png \
         -geometry +820+0 \
      \) \
      -composite +write t1.png \
      -geometry 730x390 \
      -roll -230+0 \
      -crop 270x408+0+0 +repage +write t2.png \
      +append +write t3.png \
\) \
-gravity north -background magenta -splice 0x40 +write t4.png \
-gravity south -background magenta -splice 0x40 +write t4.png \
\( +clone -sparse-color barycentric '0,0 black 270,0 white' \) \
\( -clone 1 -function arcsin 0.5 \) \
\( -clone 1 -level 0%,100% \
            -function polynomial -4,4,0 -gamma 2 \
            +level 50%,0%  \) \
-delete 1 \
-background magenta -virtual-pixel background \
-define compose:args=0x40 \
-compose Displace \
-composite \
test_out.png

```
![test_out](https://user-images.githubusercontent.com/13458218/166403470-0abbd288-684c-4059-97a3-de69f55b33de.png)

**Comment by fmw42** [comment]
I am not sure at the moment how to modify it like Anthony's code:

```
convert rose: -background none -gravity south -splice 0x16 \
\( +clone -sparse-color barycentric '0,0 black 69,0 white' \) \
\( -clone 1 -function arcsin 0.5 \) \
\( -clone 1 -level 25%,75% \
-function polynomial -4,4,0 -gamma 2 \
+level 50%,0 \) \
-delete 1 \
-virtual-pixel none  -define compose:args=17x7 \
-compose Displace  -composite   rose_cylinder.png

```
![rose_cylinder](https://user-images.githubusercontent.com/13458218/166403595-45c7671e-b0c2-4520-b8bc-6b7d78187c30.png)

**Comment by fmw42** [comment]
It looks to me like this approach is writing the distorted image over the original. But I do not see why that is happening unless it is baked in to the displacement method.  It is not writing the image onto the back of the cylinder. It is simply writing the distorted image over the original.

**Comment by luco** [comment]
@fmw42 On ImageMagick 6 is working properly:

![kensington-bottle-1](https://user-images.githubusercontent.com/246373/166451970-dccb47c4-7ab2-4335-8297-b72e7f80d98f.png)

The same code. Only switching to `convert` instead of `magick`.

**Comment by luco** [comment]
In fact, in ImageMagick 6 it fixed the top, but the bottom gets buggy:
![kensington-bottle](https://user-images.githubusercontent.com/246373/166457235-c93be0ea-e419-45ea-83a3-59ea2beb6f3b.png)

**Comment by snibgo** [comment]
This is a repeat of another post in "discussions": https://github.com/ImageMagick/ImageMagick/discussions/5112

I spent time answering that, only to discover developments on this thread. This is very annoying.

Please don't multi-post.
