### ISSUE TITLE
Crash in Imf_2_2::OpaqueAttribute::readValueFrom()

### ISSUE THREAD

**Issue by lcatro** [ImageMagick/ImageMagick#512]
Crash : [https://raw.githubusercontent.com/lcatro/My_PoC/master/ImageMagick/imagemagick%20convert%20id_000002%2Csig_06%2Csrc_000031%2Cop_havoc%2Crep_16%20output_uil%20%20assert%20fault%20%20%20Imf_2_2OpaqueAttribute__readValueFrom](url)

I get this crash using AFL fuzzing .no more detail when i reproduct it .

Trigger : ./afl_entry_fuzzer_afl convert id\:000002\,sig\:06\,src\:000031\,op\:havoc\,rep\:16 /dev/null

Crash Detail in valgrind :

libfuzzer@libfuzzer-virtual-machine:~/fuzzing/ImageMagick/fuzzing$ valgrind ./afl_entry_fuzzer_afl convert new_fuzzing/convert_uil/crashes/id\:000002\,sig\:06\,src\:000031\,op\:havoc\,rep\:16 /dev/null
==22024== Memcheck, a memory error detector
==22024== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==22024== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==22024== Command: ./afl_entry_fuzzer_afl convert new_fuzzing/convert_uil/crashes/id:000002,sig:06,src:000031,op:havoc,rep:16 /dev/null
==22024== 
==22024== Argument 'size' of function __builtin_vec_new has a fishy (possibly negative) value: -16711936
==22024==    at 0x4C2E80F: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22024==    by 0x8E8CCCB: Imf_2_2::OpaqueAttribute::readValueFrom(Imf_2_2::IStream&, int, int) (in /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0)
==22024==    by 0x8E86743: Imf_2_2::Header::readFrom(Imf_2_2::IStream&, int&) (in /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0)
==22024==    by 0x8E8A562: Imf_2_2::InputFile::InputFile(char const*, int) (in /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0)
==22024==    by 0x8E9304B: Imf_2_2::RgbaInputFile::RgbaInputFile(char const*, int) (in /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0)
==22024==    by 0x8E7D809: ImfOpenInputFile (in /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0)
==22024==    by 0xD0D66B: ReadEXRImage (exr.c:202)
==22024==    by 0x5F30D3: ReadImage (constitute.c:497)
==22024==    by 0x5F5FDE: ReadImages (constitute.c:866)
==22024==    by 0xE30F08: ConvertImageCommand (convert.c:639)
==22024==    by 0x44B721: MagickCommandGenesis (mogrify.c:183)
==22024==    by 0x5372F6: MagickMain (magick.c:149)
==22024==    by 0x5372F6: main (magick.c:180)
==22024== 
**22024** new/new[] failed and should throw an exception, but Valgrind
**22024**    cannot throw exceptions and so is aborting instead.  Sorry.
==22024==    at 0x4C2D96C: ??? (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22024==    by 0x4C2E885: operator new[](unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==22024==    by 0x8E8CCCB: Imf_2_2::OpaqueAttribute::readValueFrom(Imf_2_2::IStream&, int, int) (in /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0)
==22024==    by 0x8E86743: Imf_2_2::Header::readFrom(Imf_2_2::IStream&, int&) (in /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0)
==22024==    by 0x8E8A562: Imf_2_2::InputFile::InputFile(char const*, int) (in /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0)
==22024==    by 0x8E9304B: Imf_2_2::RgbaInputFile::RgbaInputFile(char const*, int) (in /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0)
==22024==    by 0x8E7D809: ImfOpenInputFile (in /usr/lib/x86_64-linux-gnu/libIlmImf-2_2.so.22.0.0)
==22024==    by 0xD0D66B: ReadEXRImage (exr.c:202)
==22024==    by 0x5F30D3: ReadImage (constitute.c:497)
==22024==    by 0x5F5FDE: ReadImages (constitute.c:866)
==22024==    by 0xE30F08: ConvertImageCommand (convert.c:639)
==22024==    by 0x44B721: MagickCommandGenesis (mogrify.c:183)
==22024== 
==22024== HEAP SUMMARY:
==22024==     in use at exit: 311,901 bytes in 2,076 blocks
==22024==   total heap usage: 5,080 allocs, 3,004 frees, 549,663 bytes allocated
==22024== 
==22024== LEAK SUMMARY:
==22024==    definitely lost: 0 bytes in 0 blocks
==22024==    indirectly lost: 0 bytes in 0 blocks
==22024==      possibly lost: 1,352 bytes in 18 blocks
==22024==    still reachable: 310,549 bytes in 2,058 blocks
==22024==                       of which reachable via heuristic:
==22024==                         newarray           : 1,536 bytes in 16 blocks
==22024==         suppressed: 0 bytes in 0 blocks
==22024== Rerun with --leak-check=full to see details of leaked memory
==22024== 
==22024== For counts of detected and suppressed errors, rerun with: -v
==22024== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)

**Comment by mikayla-grace** [comment]
The failure is coming from within ASN itself.  The last call in the stack before the exception is made within the OpenEXR delegate library.  As such its not a bug in ImageMagick.  We get:

```
==5900==WARNING: AddressSanitizer failed to allocate 0xffffffffff00ff00 bytes
==5900==AddressSanitizer's allocator is terminating the process instead of returning 0
==5900==If you don't like this behavior set allocator_may_return_null=1
==5900==AddressSanitizer CHECK failed: /builddir/build/BUILD/compiler-rt-3.9.1.src/lib/sanitizer_common/sanitizer_allocator.cc:199 "((0)) != (0)" (0x0, 0x0)
```

**Comment by lcatro** [comment]
@mikayla-grace Hi ,i had not using ASAN when i compile ImageMagick .Can you reproduct this at ImageMagick without ASAN again ? ..

**Comment by mikayla-grace** [comment]
The problem is coming from within the OpenEXR delegate library rather than ImageMagick:

```
==45710== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==45710== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==45710== Command: convert abc.exr null:
==45710== 
==45710== Argument 'size' of function __builtin_vec_new has a fishy (possibly negative) value: -16711936
==45710==    at 0x4C2E8E9: operator new[](unsigned long) (vg_replace_malloc.c:423)
==45710==    by 0x7CEEB8B: Imf_2_2::OpaqueAttribute::readValueFrom(Imf_2_2::IStream&, int, int) (in /usr/lib64/libIlmImf-2_2.so.22.0.0)
==45710==    by 0x7CE8453: Imf_2_2::Header::readFrom(Imf_2_2::IStream&, int&) (in /usr/lib64/libIlmImf-2_2.so.22.0.0)
==45710==    by 0x7CEC3B2: Imf_2_2::InputFile::InputFile(char const*, int) (in /usr/lib64/libIlmImf-2_2.so.22.0.0)
==45710==    by 0x7CF4ABB: Imf_2_2::RgbaInputFile::RgbaInputFile(char const*, int) (in /usr/lib64/libIlmImf-2_2.so.22.0.0)
==45710==    by 0x7CDF829: ImfOpenInputFile (in /usr/lib64/libIlmImf-2_2.so.22.0.0)
==45710==    by 0x5126B10: ReadEXRImage (exr.c:202)
```

The last call within ImageMagick is ReadEXRImage().

**Comment by dlemstra** [comment]
@lcatro Have you reported this to the OpenEXR project? Can you add a link to the issue there if you did and close this issue?

**Comment by lcatro** [comment]
@dlemstra Not yet reported to OpenEXR project .I fuzzing some thrid-party crash from ImageMagick and try to reproduct these bug in thrid-party but they can not crash (my library is install by apt in Ubuntu) .
