### ISSUE TITLE
Memory Leak in PNM Read

### ISSUE THREAD

**Issue by EthanXzhang** [ImageMagick/ImageMagick#5121]
[testcase.zip](https://github.com/ImageMagick/ImageMagick/files/8629405/testcase.zip)
### ImageMagick version

First 7.0.7-38 but still have now

### Operating system

Linux

### Operating system, version and so on

Centos6

### Description

https://github.com/ImageMagick/ImageMagick/blob/206e07e29bbbf7a8b06f47bb7c36f9d051de99dc/coders/pnm.c#L489
``` 
   if ((image_info->ping != MagickFalse) && (image_info->number_scenes != 0))
      if (image->scene >= (image_info->scene+image_info->number_scenes-1))
        break;
```
when condition is active, break causes comment_info.comment to miss release, so causing memory leak.
Suggested changes like this
```
    if ((image_info->ping != MagickFalse) && (image_info->number_scenes != 0))
      if (image->scene >= (image_info->scene+image_info->number_scenes-1)) 
     {
        comment_info.comment=DestroyString(comment_info.comment);
        break;
      }
```

### Steps to Reproduce

```
ExceptionInfo* exception = AcquireExceptionInfo();
auto image_info = CloneImageInfo(NULL);
CopyMagickString(image_info->magick, "APNG", MaxTextExtent);
image_info->number_scenes = 2;    // frame nums with input APNG
auto image = PingBlob(image_info, src_data, src_size, exception);
DestroyImageInfo(image_info);
DestroyImageList(image);
DestroyExceptionInfo(exception);
```
Using this code to build a demo.
src_data is APNG image data, src_size is APNG image data size. Using number_scenes to set to frames num in APNG image.

And, when ImageMagick decode APNG Image whick is only have 2 frames, may cause another problem, I will submit another issue to report it, becuase its cause by ffmpeg setting.

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
