### ISSUE TITLE
regression with ftypavis since 7.1.0-28

### ISSUE THREAD

**Issue by totoestcontent** [ImageMagick/ImageMagick#5123]
### ImageMagick version

7.1.0-28+

### Operating system

Linux

### Operating system, version and so on

Ubuntu 18 | 20 | windows 10

### Description

Up to version 7.1.0-27 it was possible to convert an animated avif into jpeg.
`convert animated.avif toto.jpg`

![image](https://user-images.githubusercontent.com/55127910/166897969-48200d19-0b13-4e3a-8978-e69e324594da.png)

Since version 7.1.0-28 we have an exception:
`convert.exe: ImageTypeNotSupported titi_animated.avif @ error/heic.c/ReadHEICImage/500.`
`convert.exe: NoImagesDefined toto.jpg @ error/convert.c/ConvertImageCommand/3325.`

![image](https://user-images.githubusercontent.com/55127910/166897547-5fd417f4-c40c-48a0-ab1a-b00794aadfdb.png)

Problems exist on Linux too.
Problem also exists with version 7.1.0-32.

### Steps to Reproduce

simple command line (windows or linux):
`convert animated.avif toto.jpg`

### Images

[animated.zip](https://github.com/ImageMagick/ImageMagick/files/8629861/animated.zip)

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by totoestcontent** [comment]
Thanks you.
