### ISSUE TITLE
Delegate using ffmpeg decode APNG/MPEG may cause frame copy

### ISSUE THREAD

**Issue by EthanXzhang** [ImageMagick/ImageMagick#5124]
### Is your feature request related to a problem? Please describe.

ImageMagick using ffmpeg delegate to decode MPEG format, such as APNG. Most of the time it running correct.
But, using default command in setting like to decode some APNG may cause problem.
```
<delegate decode=\"mpeg:decode\" command=\"&quot;ffmpeg&quot; -v -1 -i &quot;%i&quot; -vframes %S -vcodec pam -an -f rawvideo -y &quot;%u.pam&quot; 2&gt; &quot;%u&quot;\"/>
```
delegate will set  -vframes param to default 2147483647 when image_info->number_scenes == 0.
https://github.com/ImageMagick/ImageMagick/blob/main/MagickCore/delegate.c#L845
```
    case 'S': /* Number of scenes in image list.  */
    {
      WarnNoImageInfoReturn("\"%%%c\"",letter);
      (void) FormatLocaleString(value,MagickPathExtent,"%.20g",(double)
        (image_info->number_scenes == 0 ? 2147483647 :
         image_info->number_scenes));
      break;
    }
```
Most time set -vframes param to default 2147483647 will automatically set ffmpeg to decode all frame.
But, when input file get few frame and get no framerate setting, may cause ffmpeg get warning like that.
```
[rawvideo @ 0x6cf780] Frame rate very high for a muxer not efficiently supporting it.
Please consider specifying a lower framerate, a different muxer or -vsync 2
```
And, if using command like delegate default to decode a APNG like that
```
ffmpeg -i test.png -pix_fmt rgba -vframes 2147483647 -vcodec pam -an -f rawvideo -y test.pam
```
ffmpeg will auto copy frame as it consider framerate and nums.
```
Input #0, apng, from 'test.png':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Video: apng, pal8(pc), 210x210, 100k tbr, 100k tbn, 100k tbc
Stream mapping:
  Stream #0:0 -> #0:0 (apng (native) -> pam (native))
Press [q] to stop, [?] for help
[rawvideo @ 0x18db780] Frame rate very high for a muxer not efficiently supporting it.
Please consider specifying a lower framerate, a different muxer or -vsync 2
Output #0, rawvideo, to 'test.pam':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: pam, rgba, 210x210, q=2-31, 200 kb/s, 100k fps, 100k tbn, 100k tbc
    Metadata:
      encoder         : Lavc57.107.100 pam
More than 1000 frames duplicated
More than 10000 frames duplicated
....
```
It may cause a will big file save in disk.
Using this can reproduce the problem.
[testcase.zip](https://github.com/ImageMagick/ImageMagick/files/8637198/testcase.zip)

Problem now is only just appear in 2 frames APNG in my case, but I'm not sure if it has anything relate with the frame nums or other.

### Describe the solution you'd like

Suggest to change the default delegate command in mpeg:decode. Add "-vsync 2" in command.
```
<delegate decode=\"mpeg:decode\" command=\"&quot;ffmpeg&quot; -v -1 -i &quot;%i&quot; -vframes %S -vsync 2 -vcodec pam -an -f rawvideo -y &quot;%u.pam&quot; 2&gt; &quot;%u&quot;\"/>
```

**Comment by urban-warrior** [comment]
Add `-define video:vsync=2` to your command-line to set the vsync to 2.

**Comment by EthanXzhang** [comment]
> Add `-define video:vsync=2` to your command-line to set the vsync to 2.

Thanks Reply. 
Because it feels that the default delegate command may cause problems in the handling of special cases(such as 2 frames APNG), so that I suggested to consider adding corresponding parameters to the configuration.
If delegate function is more consider to let the user customize rather than use the default command, sorry for disturbing.

**Comment by urban-warrior** [comment]
For your particular use case, `-video:vsync=2` may make sense.  But there are other use cases where the user may not want to set vsync at all.  There is certainly much discussion about that on the Net.  Instead, we leave it to the user to decide.  As mentioned, the default is no vsync argument at all.  In some cases a user might want a vsync of 1 or in your case a vsync of 2, thus the need for the vsync define.  In the past we would sometimes set certain defaults that "make sense" only to receive complaints that the setting did not meet the requirements of a particular user.  The solution was introducing defines to modify the behavior of a workflow per the requirements of each user.

**Comment by EthanXzhang** [comment]
Thanks for the reply, I think this solution is great.
