### ISSUE TITLE
RHEL 8 -unable to read font `x:-*-helvetica-medium-r-*-*-20-*-*-*-*-*-iso8859-*'

### ISSUE THREAD

**Issue by feumw** [ImageMagick/ImageMagick#5126]
### ImageMagick version

7.1.0-32

### Operating system

Linux

### Operating system, version and so on

RHEL 8

### Description

We are using a CMS which requires ImageMagick for working with assets. So we installed ImageMagick and all functions are working except "Annotate". The message we get is:

Variant creation failed: Cannot create variant: Applying of “Annotate” on “/22/24” failed: Exception 405: unable to read font `x:-*-helvetica-medium-r-*-*-20-*-*-*-*-*-iso8859-*' @ error/annotate.c/RenderFreetype/1538 : at

We already tried everything we could find while doing research on how to fix this issue. We're installing ImageMagick from source
```
./configure
make
make install
ldconfig /usr/local/lib
```
and to verify
`magick --version`.
We installed our RHEL-system using ansible. Same modules and packages on rocky8 instead of RHEL is working totally fine. Seems like there is an issue with RHEL 8?

We tried fixing the issue by installing
```
xorg-x11-fonts*
ghostscript*
```
unfortunately none worked. We also tried installing fonts manually by putting those files on the /usr/share/fonts /usr/local/share/fonts directories. We tried adding fonts and path using this "Workaround/Fix" which was initially used for OSX: https://stackoverflow.com/questions/24696433/why-font-list-is-empty-for-imagemagick/24701602#24701602

Any ideas? Is this a general issue or just for us?

### Steps to Reproduce

RHEL 8 install following dnf packages:
```
  - libxml2
  - libxml2-devel
  - ghostscript*
  - ImageMagick
  - ImageMagick-devel
  - ImageMagick-perl
  - make
  - automake 
  - cmake 
  - gcc 
  - libtool-ltdl-devel
  - git
```
Install ImageMagick from source:
```
git clone https://github.com/ImageMagick/ImageMagick.git /opt/ImageMagick
./configure
make
make install
ldconfig /usr/local/lib
```
use convert

**Comment by urban-warrior** [comment]
ImageMagick tries to find a suitable default font when annotating.  Start by defining a system-wide default font in policy.xml, for example:

```
<policy domain="system" name="font" value="/usr/local/etc/ImageMagick-7/arial-unicode.ttf"/>
```

You can also explicitly set your font with the `-font` command-line option.  Otherwise we would need to see your unit test for annotation to determine why its trying to default to an X11 font.  It normally does not do that unless you are using a command utility that links to the X11 library.

**Comment by feumw** [comment]
I found out that there is a difference between our CMS and ImageMagick on the system.

First I used convert on command line using annotate and adding a label which didn't worked. 
```
root@imp11 ~ # convert /opt/imperia/dev/htdocs/mam/test_300x300.jpg -background Khaki label:'Faerie Dragon' -gravity Center -append -annotate +0+2 'foo bar' /vagrant/NAMENEU.jpg
convert: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1538.
```
Then I added a policy-rule you recommended ...
```
root@imp11 ~ # find / -name "policy.xml" -type f
/opt/ImageMagick/config/policy.xml
/opt/ImageMagick/www/source/policy.xml
/usr/local/etc/ImageMagick-7/policy.xml
/usr/local/share/doc/ImageMagick-7/www/source/policy.xml
/etc/ImageMagick-6/policy.xml
root@imp11 ~ # l /usr/share/fonts/google-droid/DroidSans.ttf
-rw-r--r--. 1 root root 187K Jul 15  2012 /usr/share/fonts/google-droid/DroidSans.ttf
root@imp11 ~ # tail /usr/local/etc/ImageMagick-7/policy.xml 
  <!-- <policy domain="path" rights="none" pattern="@*" /> -->
  <!-- <policy domain="cache" name="memory-map" value="anonymous"/> -->
  <!-- <policy domain="cache" name="synchronize" value="True"/> -->
  <!-- <policy domain="cache" name="shared-secret" value="passphrase" stealth="true"/> -->
  <!-- <policy domain="system" name="max-memory-request" value="256MiB"/> -->
  <!-- <policy domain="system" name="shred" value="2"/> -->
  <!-- <policy domain="system" name="font" value="/path/to/unicode-font.ttf"/> -->
  <policy domain="system" name="precision" value="6"/>
  <policy domain="system" name="font" value="/usr/share/fonts/google-droid/DroidSans.ttf"/>
</policymap>
root@imp11 ~ # convert /opt/imperia/dev/htdocs/mam/test_300x300.jpg   -background Khaki  label:'Faerie Dragon' -gravity Center -append    /vagrant/NAMENEU.jpg
root@imp11 ~ #
```
and it worked for the command line.

Using `convert -list font` doesn't return anything. Even with system policy set. I found out that instead of setting system policy, an alternative solution is editing type.xml. If we replace `<include file="type-ghostscript.xml" />` with type-urw-base35.xml in the type.xml convert does work on command line as well. 

The error in my CMS stays the same
```
Variant creation failed: Cannot create variant: Applying of “Annotate” on “/22/24” failed: Exception 405: unable to read font `x:--helvetica-medium-r---20------iso8859-*' @ error/annotate.c/RenderFreetype/1538 : at
```
I reinstalled the server and I changed policy.xml before installing the perl-module. This might be an issue with the perl-module then?

**Comment by feumw** [comment]
I'm closing this issue for now, since I believe it's an issue in out CMS. This font is hard-coded into it. I have no idea why it works on older servers but anyway, ImageMagick on Command Line seems to work fine.

**Comment by feumw** [comment]
Just in case anyone wonders. I could find a way to get this working by using a different Image::Magick version for the perl module. Seems like YUM uses Image-Magic 6.x. When I install JCRISTY/Image-Magick-6.9.12-1.tar.gz instead of the latest Perl-Module-Version the YUM installed ImageMagick does find all C-Header files and everything works as intended. So I guess we stay on JCRISTY/Image-Magick-6.9.12-1.tar.gz until YUM updates to ImageMagick 7 then.
