### ISSUE TITLE
[Windows, VisualMagick] Please add /source-charset:utf-8 to compiler options

### ISSUE THREAD

**Issue by taroxd** [ImageMagick/ImageMagick#513]
For non-English Windows, the system-wide codepage is probably not utf-8. Visual Studio C++ compiler uses system codepage instead of utf-8, and therefore the utf-8 source code will fail to compile.

A similar issue can be seen at: https://github.com/Microsoft/vcpkg/issues/141

Adding /source-charset:utf-8 will solve the problem.

Specifically, these four projects need the compiler option:
* CORE_pango
* CORE_MagickCore
* CORE_coders
* CORE_ttf

For /source-charset, reference is available at <https://msdn.microsoft.com/en-us/library/mt708819.aspx>

**Comment by dlemstra** [comment]
Our projects use `Use Multi-Byte Character Set` for the Character Set and we have methods to convert from UTF-8. Are you experiencing UTF-8 issues with ImageMagick?

**Comment by taroxd** [comment]
I am not experiencing issues when using ImageMagick, but I am when I am building it with Visual Studio 2017.

It won't compile on Windows 10 Simplified Chinese, unless given the /source-charset:utf-8 option. Because some of the source files (such as [this one](https://github.com/ImageMagick/pango/blob/master/pango/pango-language-sample-table.h)) is encoded in UTF-8 (without BOM) and contains non-ASCII characters. 

> By default, Visual Studio detects a byte-order mark to determine if the source file is in an encoded Unicode format, for example, UTF-16 or UTF-8. If no byte-order mark is found, it assumes the source file is encoded using the current user code page, unless you specify a character set name or code page 

(From https://msdn.microsoft.com/en-us/library/mt708819.aspx)

**Comment by dlemstra** [comment]
I am sorry I thought you were talking about the 'Character Set' option. You are talking about a different option. I will have to take a look and see if it still works on my machine.

Could you create an issue in the VisualMagick project to remind me to add an option for MAGICKCORE_ZERO_CONFIGURATION_SUPPORT to configure.exe? Should not be that difficult to add.
