### ISSUE TITLE
memory leak in ReadPSImage in coders/ps.c

### ISSUE THREAD

**Issue by maodongchen** [ImageMagick/ImageMagick#5131]
### ImageMagick version

7.1.0-32

### Operating system

Linux

### Operating system, version and so on

openeuler-20.03-LTS-SP3

### Description

I just found a memory leak in ReadPSImage in coders/ps.c. Maybe you can tell me whether it's reasonable or not. Thanks~  :)

### Steps to Reproduce

[https://github.com/ImageMagick/ImageMagick/blob/d4d5ca2dd981a37408e7a97e407c1d5632312c07/coders/ps.c#L673](url)
![image](https://user-images.githubusercontent.com/62093476/167252480-4af97466-32db-40a5-9736-bd9e1cfd11ad.png)

System will not reclaim the memory in info in ReadPSInfo if the processes go to if statement which has a return
![image](https://user-images.githubusercontent.com/62093476/167252591-c4d45320-4300-4920-98d4-b81ddbb9ccfd.png)

So maybe it's better to add 
`CleanupPSInfo(&info);` 
before 
`return((Image *) NULL);`

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
