### ISSUE TITLE
Converting PDF to PBM broken since 7.1.0.32

### ISSUE THREAD

**Issue by windmueller** [ImageMagick/ImageMagick#5134]
### ImageMagick version

7.1.0.33

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

When converting a PDF file to PBM, large rectangle areas of the image or even the whole one is replaced with black or white.

/etc/ImageMagick-7/policy.xml already contains this which worked until 7.1.0.31:

```
<policy domain="coder" rights="read|write" pattern="{PS,PS2,PS3,EPS,PDF,XPS}" />
<policy domain="coder" rights="read | write" pattern="PDF" />
```

Downgrading to 7.1.0.31 fixes this issue.

### Steps to Reproduce

$ convert test.pdf test.pbm

### Images

[test.pdf](https://github.com/ImageMagick/ImageMagick/files/8645802/test.pdf)

**Comment by fmw42** [comment]
It seems to work on ImageMagick 6.9.12-48 Q16 (though the quality is reduced by the default 72 dpi when reading the PDF), but gives me a **completely white image** on 7.1.0-33 Q16-HDRI.

IM 6:

`convert test.pdf test6.pbm`

IM 7:

`magick test.pdf test7.pbm`

Results in below zip file:

[Archive.zip](https://github.com/ImageMagick/ImageMagick/files/8645842/Archive.zip)

**Comment by fmw42** [comment]
If I run with higher dpi and turn alpha off, then the result looks fine.

`magick -density 300 test.pdf -alpha off test.pbm`

[test.pbm.zip](https://github.com/ImageMagick/ImageMagick/files/8645846/test.pbm.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
