### ISSUE TITLE
Convert .png to multiple .ico. Default size is 128x128 (Not maximum - 256x256).

### ISSUE THREAD

**Issue by moninah850** [ImageMagick/ImageMagick#5137]
### ImageMagick version

7.1.0-Q16-HDRI

### Operating system

Windows

### Operating system, version and so on

Windows 7

### Description

Hello

When I use the command:

`magick convert favicon.png -alpha on -resize 256x256 -define icon:auto-resize="256,128,96,64,48,32,16" favicon.ico`

favicon.ico is created with a resolution of 128x128 (Not maximum - 256x256).

### Steps to Reproduce

If open the favicon.ico file in Photoshop, then I can select a resolution of 256x256 or 128x128 or 96x96 etc. How I can get 256x256 when creating a default .ico file in a folder?

**Comment by snibgo** [comment]
Please state the exact IM version. You can paste the text output from "magick -version".

Please show your input favicon.png.

I suggest using "magick", not "magick convert".

**Comment by urban-warrior** [comment]
Type `magick identify favicon.ico`.  If the 256x256 resolution listed?

**Comment by moninah850** [comment]
> Please state the exact IM version. You can paste the text output from "magick -version".
> 
> Please show your input favicon.png.
> 
> I suggest using "magick", not "magick convert".

Version: ImageMagick 7.1.0-33 Q16-HDRI x64 39baedd:20220507 https://imagemagick.
org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms
 lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (193131107)



> Type `magick identify favicon.ico`. If the 256x256 resolution listed?

magick identify favicon.ico
favicon.ico[0] PNG 256x256 256x256+0+0 8-bit sRGB 18934B 0.000u 0:00.001
favicon.ico[1] ICO 128x128 128x128+0+0 8-bit sRGB 0.000u 0:00.003
favicon.ico[2] ICO 96x96 96x96+0+0 8-bit sRGB 0.000u 0:00.005
favicon.ico[3] ICO 64x64 64x64+0+0 8-bit sRGB 0.000u 0:00.007
favicon.ico[4] ICO 48x48 48x48+0+0 8-bit sRGB 0.000u 0:00.008
favicon.ico[5] ICO 32x32 32x32+0+0 8-bit sRGB 0.000u 0:00.010
favicon.ico[6] ICO 16x16 16x16+0+0 8-bit sRGB 156700B 0.000u 0:00.012

But in windows 7 when creating the favicon.ico file:

![Untitled](https://user-images.githubusercontent.com/105148733/167336994-8784bfa3-ca1e-408b-ab20-ad6be0ad610f.png)

**Comment by fmw42** [comment]
The first row says:

`favicon.ico[0] PNG 256x256 256x256+0+0 8-bit sRGB 18934B 0.000u 0:00.001`

So 256x256 is the biggest resolution.  I have no clue what your Windows Properties is showing or trying to find since it is a multi-resolution  file. Perhaps it is just showing the resolution it used for the preview.
