### ISSUE TITLE
Caught exception: Magick: UnableToOpenFile 'C:/Users/ubaid/AppData/Local/Temp/ma gick-50688gZyU9cXTX7MK': No such file or directory @ error/constitute.c/ReadImag e/549

### ISSUE THREAD

**Issue by spertasolutions** [ImageMagick/ImageMagick#514]
```
       try {
		Magick::Image svgImage;
		svgImage.backgroundColor(c);
		svgImage.read("a.svg");  // first read file
		svgImage.magick("png");  // then specify PNG format
		Magick::Blob blob;
		svgImage.write(&blob);
	}
	catch (std::exception &error_)
	{
		std::cout << "Caught exception: " << error_.what() << std::endl;
		system("pause");
	}
```

a.svg is available in Release, Debug and project folder. I'm using Magick++ in Visual Studio 2015.

I'm getting the following error:
Caught exception: Magick: UnableToOpenFile 'C:/Users/ubaid/AppData/Local/Temp/ma
gick-50688gZyU9cXTX7MK': No such file or directory @ error/constitute.c/ReadImag
e/549

I have compiled all the binaries myself using configure utility. Please guide. I am just trying to convert an SVG file into a PNG file here.

**Comment by dlemstra** [comment]
Did you also build ImageMagick from source? It looks like the library you link with does not have the SVG decode. And did you call `Magick::InitializeMagick`?

**Comment by dlemstra** [comment]
@spertasolutions Can we close this issue?

**Comment by spertasolutions** [comment]
Yes please.

**Comment by aaaaaa111111a** [comment]
i met this prebolem too， x86 dll, what i do, is copy delegate.xml同dll same dir level, then call success
