### ISSUE TITLE
TGA orientation is inconsistent with other open-source programs

### ISSUE THREAD

**Issue by Taemojitsu** [ImageMagick/ImageMagick#5148]
### ImageMagick version

6.9.11-60

### Operating system

Linux

### Operating system, version and so on

Ubuntu 21.10

### Description

I apologize for not using IM 7.x to report this bug. Even if upgraded to the latest version of Ubuntu, I [would still have IM 6.9](https://www.ubuntuupdates.org/package/core/jammy/universe/base/imagemagick). However, a previous (locked) report for this issue reported it for 7.1 with the response being "working as intended": https://github.com/ImageMagick/ImageMagick/issues/3844

Other reports about this issue:
https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=34757 (possibly where it was changed from earlier behavior)
https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1838860

With those previous reports, there was confusion about the "real" orientation of a TGA. We can reduce this confusion using IM's own 'display'. In short, Imagemagick treats TGAs the same regardless of what orientation was defined when creating them, while other programs including Eye of Gnome (eog), Gimp, and whatever reads TGA files for Wine (or maybe a particular Wine application, MikuMikuDance) ignore the orientation bits and therefore display flipped or rotated versions of the image, depending on the TGA orientation.

This is the first question: are other graphics programs treating TGAs wrong on purpose, because everything else does, while IM has decided to follow the format specification; or should a bug be reported for these projects; or are these programs treating TGAs correctly and the bug is in Imagemagick?

The suggestion for proper conversions used in the previous report is to use '-auto-orient'. There are reports that it is unnecessary and harmful with some versions of IM; it works for me, but the concern here is that using '-orient TopLeft' directly does not produce the same result as '-auto-orient'.

### Steps to Reproduce

Steps to reproduce the bugs:
```
 convert image.jpg (or rose:) -orient BottomLeft BL.tga
 convert image.jpg -orient BottomRight BR.tga
 convert image.jpg -orient TopLeft TL.tga
 display BL.tga BR.tga TL.tga
 convert image.jpg default.tga
 convert image.jpg -auto-convert auto-convert.tga
```

Result: all look normal using 'display' (possibly 'magick display' on some systems).
Open with another common program like eog or gimp. Result: flipped or rotated. Only TL.tga and auto-convert.tga are shown the same by all programs.

Then, converting from a typical BottomLeft orientation to another format, like png or jpg:
```
 convert BL.tga -auto-orient BL_auto-orient.jpg
 convert BL.tga -orient TopLeft BL_to_TL.jpg
 convert BL.tga -orient BottomLeft BL_to_BL.jpg
```

'display' and programs like eog and Gimp show these images with the same orientation, but the auto-orient is flipped from both the TL and BL outputs. (PNG output is the same as jpg.) Auto-orientation does something different from manually specifying an orientation. In fact, the '-orient' operator is doing nothing here, with jpg output: the files are identical.

It might seem that everything is working fine: the BL_to_BL.jpg and BL_to_TL.jpg images are right-side-up, while BL_auto-orient.jpg is upside-down. But this is only because we started from a jpg; turned it into a TGA which most programs thought was upside-down; and then flipped it again. In cases where a TGA was created and deemed to be correctly oriented when viewed by common programs (including Imagemagick prior to the ~2018 code change, which took time to filter to distributions), no '-orient' operator will give the intended result when converting a typical BottomLeft TGA to PNG to save space. Only '-flip' works, which can require testing TGAs for their orientation, and '-auto-orient' works, with some reports that it works inconsistently with different IM versions.

The '-orient' operator should probably be able to do the same thing as '-auto-orient', but it can't.

**Comment by snibgo** [comment]
> The '-orient' operator should probably be able to do the same thing as '-auto-orient', but it can't.

No, they do different things.

"-orient" merely changes the orientation metadata. It does not (and should not) change the image.

"-auto-orient" examines the orientation metadata. If it isn't top-left, it changes the image as required, and sets the metadata to top-left.

**Comment by Taemojitsu** [comment]
> "-orient" merely changes the orientation metadata. It does not (and should not) change the image.
Based on this, and evidence like other programs being affected by this change in metadata when writing TGA files and the run-length-encoded TopLeft and BottomLeft TGAs from gimp being the same size, I surmise that most programs, including eog, gimp, and whatever does TGAs for MikuMikuDance in Wine (whether it's a library from Windows or part of Linux), view the orientation data for TGAs as required, and always do it. Either they start writing from the bottom-left for BottomLeft orientation, or they write from the top and flip (either after loading or while displaying).

Imagemagick views TGA orientation as optional, and only respects it (whether viewing or converting) if the user tells it to with -auto-orient. -auto-orient is not automatically applied because it also affects rotations of other images like jpegs, I guess. So Imagemagick starts writing from the top-left regardless of the orientation data, and continues to treat the top-left as the top-left when converting to other formats.

When a user in gimp saves with BottomLeft encoding, it means to represent the same image with a different data ordering, starting with the pixel at the bottom left. When a user converts to TGA using imagemagick, which defaults to Bottom-Left orientation, it means to include instructions to flip the image, although IM itself will not follow these instructions unless explicitly instructed to.

From this perspective, one could describe IM's behavior as "not a bug" and choose to close this issue.

**Comment by snibgo** [comment]
@fmw42 or someone who can edit documentation: I suggest that https://imagemagick.org/script/command-line-options.php#orient is edited to include this:

> This merely sets the orientation metadata, and does not change the image.

**Comment by urban-warrior** [comment]
Done.
