### ISSUE TITLE
JPEG to PDF: some output files have double size

### ISSUE THREAD

**Issue by Caleb13-2** [ImageMagick/ImageMagick#5149]
### ImageMagick version

7.1.0-Q16-HDRI

### Operating system

Windows

### Operating system, version and so on

W10 64-bit 21H2

### Description

I'm using magick.exe to combine scanned JPEG files (pages from old magazines) to PDF files. I already processed about 20 thousand input JPEGs, each output PDF has about 30 pages (one magazine issue). Normally, the resulting PDFs have very similar file size as the source JPEGs (as expected), but sometimes they're MUCH larger.  It happens even if I process only one "problematic" JPEG into one PDF.  I'm pretty sure it's IM bug, because if I use Adobe Acrobat to process the JPEGs, the resultig PDFs have the proper size.

### Steps to Reproduce

I'm attaching one "problematic" JPEG and the resulting PDF - the JPEG has about 1200 KB, but the resulting PDF has almost double size, 2400 KB. It happens with the simplest command:
magick.exe *.jpg out.pdf

### Images

![in](https://user-images.githubusercontent.com/70209677/167957512-84da1a3e-2d0d-455e-8551-15eb498c6f0a.jpg)
[out.pdf](https://github.com/ImageMagick/ImageMagick/files/8673743/out.pdf)

**Comment by snibgo** [comment]
I suggest using a "-quality" setting, like this:
```
magick abcmlad.jpg -quality 40 out.pdf
```

**Comment by Caleb13-2** [comment]
That would recompress the JPEGs to lower quality. I need to avoid that - I'm joining them into PDFs because I want to perform OCR on them.

**Comment by urban-warrior** [comment]
The quantization tables of your image suggests it was compressed with a quality of 29 resulting in a relatively well-compressed image.  It also has an EXIF profile we could strip:

```
$ magick in.jpg -strip -quality 29 out.pdf
$ ls -l out.pdf
```
returning 1158597 bytes, comparable to your original image.  The default compression quality for ImageMagick is 92, thus the larger than expected resulting image size, due to increased compression quality.

**Comment by Caleb13-2** [comment]
I checked it with pdfimages utility and IM indeed transcoded the "problematic" JPEG from original 90 compression to 92. When I did the same in GIMP, the file size also roughly doubled. But now comes the weird part - the "good" JPEG files also have 90 compression, but IM leaves them untouched. Or maybe not untouched, but they remain at 90 inside the PDF. Why? Why IM switches some images to 92 but leaves most at 90?

I'm attaching an example of a "good" JPEG file, its PDF created by IM and JPEG extracted by pdfimages. The extracted image has 90 compression, not 92.
[Untouched_image.zip](https://github.com/ImageMagick/ImageMagick/files/8682764/Untouched_image.zip)

**Comment by urban-warrior** [comment]
ImageMagick, if it can detect the image compression quality from the quantization tables, will set the compression quality attribute and use it when writing a new JPEG image.  If it cannot detect the compression quality, it defaults to 92.  You can always set a specific compression quality with `-quality 75`, for example.

**Comment by Caleb13-2** [comment]
Ah, that makes sense. Not a bug after all, it seems.

In the meantime, I may have found an alternative solution: utility img2pdf that's made explicitly to convert the images to PDF without transcoding (if possible).

https://pypi.org/project/img2pdf/

**Comment by urban-warrior** [comment]
It would be easiest enough to support this use case in ImageMagick but there has not been much call for it-- and we tend to prioritize enhancements based on user-base demand.

**Comment by Caleb13-2** [comment]
It would go against IM's core idea, too - if IM always transcodes everything, then it should remain so. 
Many thanks for all your assistance, I think you can close this thread.
