### ISSUE TITLE
ImageMagick from source on macOS 10.12 Sierra FAIL

### ISSUE THREAD

**Issue by linchong899201** [ImageMagick/ImageMagick#515]
=========================================
   ImageMagick 7.0.6: ./test-suite.log
=========================================

# TOTAL: 86
# PASS:  84
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/wandtest
====================

wandtest: delegate library support not built-in '/Library/Fonts//Arial.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/1818.
wandtest: delegate library support not built-in '/Library/Fonts//Arial.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/1818.
tests/wandtest.c main 5321 non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3269
1..1
Reading images...
Iterate forward...
index 0 scene 0
index 1 scene 1
index 2 scene 2
index 3 scene 3
index 4 scene 4
Iterate reverse...
index 4 scene 4
index 3 scene 3
index 2 scene 2
index 1 scene 1
index 0 scene 0
Remove scene 1...
index 0 scene 0
index 1 scene 2
index 2 scene 3
index 3 scene 4
Insert scene 1 back in sequence...
index 0 scene 0
index 1 scene 1
index 2 scene 2

**Comment by dlemstra** [comment]
You are getting this error because you did not build ImageMagick with the FreeType delegate.
