### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by mads256h** [ImageMagick/ImageMagick#5152]
### ImageMagick version

7.1.0.33

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

My background blur script suddenly stopped working.
The convert command pinned all my cores on my cpu to 100% and would never get finished.
It even managed to make my pc overheat and shut down.
Downgrading to 7.1.0.31 makes this problem go away.
I haven't tested this with version 7.1.0.32 as i don't have it in my package cache.

### Steps to Reproduce

Run this command:
`convert "input.jpg" -depth 16 -channel R +level 0,30% -channel G +level 0,30% -channel B +level 0,30% +channel -gaussian-blur 0x8 -dither FloydSteinberg -colors 16777216 /tmp/background.png`

**Comment by urban-warrior** [comment]
What are the dimensions of the image you are converting?  We used the ImageMagick logo and the command completed in 49 seconds.  If we change 16777216 to 1024, it runs in 1 second.  The large color value caused the color-reduction algorithm to create a large colormap which increases the colormap size when resolving which pixel belongs to which which colormap entry.  Set the max colors to something reasonable, perhaps 1024.

**Comment by mads256h** [comment]
I have upgraded to 7.1.0.35. This has resolved the issue. Thank you :)
