### ISSUE TITLE
svg display error with chinese character

### ISSUE THREAD

**Issue by zmdyy0318** [ImageMagick/ImageMagick#5154]
### ImageMagick version

7.1.0-34

### Operating system

Windows

### Operating system, version and so on

windows 11

### Description

this image chrome display good, but IMDisplay display error.
![image](https://user-images.githubusercontent.com/16699676/168532060-aacfaaaa-6446-45bd-82a2-7ae21c35303b.png)
![image](https://user-images.githubusercontent.com/16699676/168532143-b553e832-cd55-4e62-aa2f-07fa7c937d22.png)

### Steps to Reproduce

1. goto https://demo.bpmn.io/s/start.
2. type some chineses like "你好".
3. download svg image.
4. open svg image via IMDisplay.
![image](https://user-images.githubusercontent.com/16699676/168532249-bc59bebe-a854-4269-afab-c332f6b3304d.png)

### Images

![diagram](https://user-images.githubusercontent.com/16699676/168531722-e260c306-44f8-4291-be5b-dc3bced39c9f.svg)

**Comment by zmdyy0318** [comment]
this svg contain "font-family: Arial, sans-serif"
Arial not support chinese, but sans-serif support.
maybe we should try every font-famliy, util success?

**Comment by zmdyy0318** [comment]
macos m1 12.3.1
imagemagick 3.1.0-33
this svg image can not convert too.
```
brew install imagemagick
magick /Users/zmdyy03/Downloads/diagram.svg /Users/zmdyy03/Downloads/111.png
magick: non-conforming drawing primitive definition `px' @ error/draw.c/RenderMVGContent/4490.
```

**Comment by ValZapod** [comment]
> maybe we should try every font-famliy, util success?

Yes.

>or set failback font-famliy?
Again, yes. But you need to find same optical size font. Font subtitution is complex thing.
