### ISSUE TITLE
HEIC files identified as AVIF

### ISSUE THREAD

**Issue by kayline** [ImageMagick/ImageMagick#5159]
### ImageMagick version

7.1.0-30

### Operating system

MacOS

### Operating system, version and so on

MacOS 12.3.1

### Description

At some point between 7.1.0-23 and 7.1.0-30, ImageMagick's file type identifier started identifying HEIC files as AVIF files. This is causing problems for our app, because we can accept HEIC files but we can't accept AVIF files. When we upgraded our version of ImageMagick, we started incorrectly rejecting HEIC files because ImageMagick was identifying them as AVIF.

### Steps to Reproduce

Using the Ruby gem 'mini_magick', create a file type parser and use it to determine the file type of a HEIC file.

```
file_type_parser = MiniMagick::Image.open(File.open(file_path)).data['format']
file_type  = file_type_parser.file_type
```
Where file_path is the path to any HEIC file.

**Comment by urban-warrior** [comment]
What release of the libheif delegate library are you using?  Check the headers.  We need at least LIBHEIF_NUMERIC_VERSION >= 0x010b0000 to properly set the image type to AVIF.

**Comment by ncgisudo** [comment]
I am also experiencing this issue.  I don't know what version it started in, but what I can it's fairly recent as I've just had to install the latest version on a new box and found this issue.

Running `-list format` reports a version number for High Efficiency Image Format.  I don't know if this is the libheic version, but I have included it below.

I've tried a few versions and found the following:
_Note - all versions of the binaries tested below below came straight off of imagemagick.org_

| ImageMagick Version | Platform | Portable |  HEIC Version in "-list format" | HEIC detected as |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| ImageMagick 7.1.0-17 Q16-HDRI x64 2021-12-04 | Windows x64 | No | 1.12.0 | HEIC |
| ImageMagick 7.1.0-33 Q16-HDRI x64 39baedd:20220507 | Windows x64 | Yes | 1.12.0 | AVIF |
| ImageMagick 7.1.0-34 Q16-HDRI x64 f2934c5:20220515 | Windows x64 | Yes | 1.12.0 | AVIF |

**Comment by kayline** [comment]
Update: We are also seeing some files with `.jpg` extensions identified as file type AVIF. I'm sorry I can't provide an example, the files contain confidential client data.

**Comment by dlemstra** [comment]
Can you share a file privately or the first 100? bytes of the header of the file? I think those files really are AVIF files.

**Comment by ncgisudo** [comment]
I have attached my sample HEIC image (inside a ZIP, because GitHub doesn't allow uploading of HEIC images)
[image1.zip](https://github.com/ImageMagick/ImageMagick/files/8727291/image1.zip)

Note - The `file` command (i.e. `magic` file) reports it as HEIC, although I have not looked at what it uses to determine HEIC:
>ncgisudo@thebox ~
$ file image1.heic
image1.heic: ISO Media, HEIF Image HEVC Main or Main Still Picture Profile
\
ncgisudo@UK-thebox ~
$ file --mime-type image1.heic
image1.heic: image/heic

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
