### ISSUE TITLE
Auto-orient over rotates dng image

### ISSUE THREAD

**Issue by bart-quintens** [ImageMagick/ImageMagick#5183]
### ImageMagick version

7.1.0-35

### Operating system

Linux

### Operating system, version and so on

debian:buster

### Description

We compiled ImageMagick with libraw library to convert raw images. The attached image is correctly handled by LibRaw separately  but in ImageMagick the auto-orient argument overrotates the image.

### Steps to Reproduce

Compile ImageMagick with latest libraw from https://github.com/LibRaw/LibRaw . 

Run the command `convert example_vertical.dng +repage -auto-orient test.jpg`

Result: The image is over rotated

### Images

[example_vertical.zip](https://github.com/ImageMagick/ImageMagick/files/8803164/example_vertical.zip)

**Comment by snibgo** [comment]
There seems to be a bug.

With IM v7.1.0-32 pre-built binary on Windows 8.1, IM does an "-auto-orient" when I haven't told it to.

I don't have "the auto-orient argument overrotates the image" the OP says for 7.1.0-35. Perhaps that is a bug on top of another bug.

For me, "-auto-orient" seems to work correctly, but I suspect for the wrong reason. I suspect it rotates the image when reading it, so the explicit "-auto-orient" has no work to do.

**Comment by snibgo** [comment]
The file does have an orientation flag.
```
f:\web\im>exiftool example_vertical.dng |grep -i orient
Orientation                     : Rotate 90 CW
```

**Comment by urban-warrior** [comment]
Right, however we don't currently read the EXIF profile.  We'll need to add an EXIF callback to the coder and extract the orientation tag.  We'll likely have a patch in a few days.

**Comment by Hephaistion** [comment]
Thank you for your swift action, we are eagerly awaiting your patch. ImageMagick has been a truly added value to our product.

**Comment by LeonLdv** [comment]
Hello. I use Magick.NET-Q16-AnyCPU -Version 13.5.0. 
After converting image DNG to JPG the image become upside down.
 Please see images before converting and after.
Images were made by Iphone 15.
 Thank you for help.

[BeforeAndAfterConvertImages.zip](https://github.com/ImageMagick/ImageMagick/files/13964618/BeforeAndAfterConvertImages.zip)

` public byte[] Convert(byte[] inputBytes, MagickFormat toFormat, MagickGeometry geometry = null)
    {
        
        using MagickImage image = new (inputBytes);
        // Set any additional processing options if needed
        // For example, you can resize the image:

        if (geometry is not null)
        {
            image.Resize(geometry);
        }
               
        // Convert the image to JPEG format
        image.Format = toFormat;
        image.AutoOrient();
        // Save the result to a memory stream
        using MemoryStream outputStream = new ();
        image.Write(outputStream);
        return outputStream.ToArray();
    }`
