### ISSUE TITLE
Python 3.5 support for pymagick

### ISSUE THREAD

**Issue by apiszcz** [ImageMagick/ImageMagick#52]
Is the Python 3.5 API in development or planned? Thank you.

**Comment by urban-warrior** [comment]
We have Python 3.4.  It builds without complaint from the git repository @ https://github.com/ImageMagick/PythonMagick.  Does it fail for you with Python 3.5?

**Comment by dlemstra** [comment]
@apiszcz Could you reply to our question?

**Comment by apiszcz** [comment]
I am interested in a windows build, and have not tried to compile. I
typically use packages from
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonmagick
​

**Comment by pidugusundeep** [comment]
> I am interested in a windows build, and have not tried to compile. I
> typically use packages from
> http://www.lfd.uci.edu/~gohlke/pythonlibs/#pythonmagick
> ​
> 
> On Sun, Nov 29, 2015 at 3:37 AM, Dirk Lemstra [notifications@github.com](mailto:notifications@github.com)
> wrote:
> 
> > @apiszcz https://github.com/apiszcz Could you reply to our question?
> > —
> > Reply to this email directly or view it on GitHub
> > [#52 (comment)](https://github.com/ImageMagick/ImageMagick/issues/52#issuecomment-160391545)
> > .

Which one should I be downloading for my Linux installation?
