### ISSUE TITLE
Downscale (with FILTER_CUBIC) looks worse in 7.0.5-4 than in 6.9.4-0

### ISSUE THREAD

**Issue by Trost123** [ImageMagick/ImageMagick#520]
**UPD**: We figured out that it's not a sharpen problem, but downscale problem: https://github.com/ImageMagick/ImageMagick/issues/520#issuecomment-310768785

Original post:
Hi. I have 2 servers, one runs with ImageMagick 6.9.4, other got  7.0.5.
For some reason, sharpen looks way worse in 7.0.5:
[Blurry dress patterns and flowers](https://user-images.githubusercontent.com/21346282/27492041-5eef1c66-584d-11e7-8e74-4720ee0527a6.jpg)
This is how this image looks in 6.9.4:
[Sharp and good looking](https://user-images.githubusercontent.com/21346282/27492045-61dcb94c-584d-11e7-8fa0-2136fb4240c3.jpg)

My actions are:
```
$image = new Imagick('testimg.JPG');
$image->resizeImage(467, 700, Imagick::FILTER_CUBIC, 0.5); 
$image->sharpenImage(0, 0.6);
```

Original image is 647x970.
[Original, just in case](https://user-images.githubusercontent.com/21346282/27492314-7618021c-584e-11e7-8da4-9c0f396ec015.JPG)

Also, if I crank up the second parameter, the image will change on 7.0.5, so sharpenImage() works, but it jumps from blurry to messy in 0.6-1.1 range real quick.

Any idea to why this happens or how to fix it? (I'd hate having to roll-back to 6.9.4)

**Comment by fmw42** [comment]
I have tested your image in command line mode using the latest IM 6.9.8.10 Q16 (non-hdri) and IM 7.0.6.0 Q16 hydri with the following commands and see no significant differences.

```
convert 27492314-7618021c-584e-11e7-8da4-9c0f396ec015.JPG -filter cubic -define filter:b=0.5 -resize 467x700 -sharpen 0x0.6 tmpb6.jpg
```
[](http://www.fmwconcepts.com/misc_tests/sharpen_test/tmpb6.jpg)

`magick 27492314-7618021c-584e-11e7-8da4-9c0f396ec015.JPG -filter cubic -define filter:b=0.5 -resize 467x700 -sharpen 0x0.6 tmpb7.jpg`
[](http://www.fmwconcepts.com/misc_tests/sharpen_test/tmpb7.jpg)

```
compare -metric rmse tmpb6.jpg tmpb7.jpg null:
64.0422 (0.000977222)
```
You have not identified the full versions of ImageMagick, so I could not test with those exact versions. Perhaps this is an issue with your ImageMagick versions or with Imagick using ImageMagick 7.

**Comment by Trost123** [comment]
Sorry, didn't know.
It's:
ImageMagick 6.9.4-0 Q16 x86_64 2016-05-09 http://www.imagemagick.org
vs
ImageMagick 7.0.5-4 Q16 x86_64 2017-04-12 http://www.imagemagick.org

**Comment by Trost123** [comment]
Also, difference can be seen better if you downscale more:
![1 200](https://user-images.githubusercontent.com/21346282/27494697-a8a1c304-5857-11e7-9d3e-3bc207390b5c.JPG)
![1 200 blur](https://user-images.githubusercontent.com/21346282/27494698-a8ab458c-5857-11e7-9250-accc3754c5cf.JPG)

**Comment by fmw42** [comment]
What resizing values did you use here in these smaller ones.

**Comment by Trost123** [comment]
$image->resizeImage(133, 200, Imagick::FILTER_CUBIC, 0.5);

**Comment by fmw42** [comment]
I still do not find any differences using 6.9.4.0 and 7.0.5.4.
im6940
` convert 27492314-7618021c-584e-11e7-8da4-9c0f396ec015.JPG -filter cubic -define filter:b=0.5 -resize 133x300 -sharpen 0x0.6 tmpc6.jpg`

[IM 6 result](http://www.fmwconcepts.com/misc_tests/sharpen_test/tmpc6.jpg)

im7054 
`magick 27492314-7618021c-584e-11e7-8da4-9c0f396ec015.JPG -filter cubic -define filter:b=0.5 -resize 133x300 -sharpen 0x0.6 tmpc7.jpg`

[IM 7 result](http://www.fmwconcepts.com/misc_tests/sharpen_test/tmpc7.jpg)

```
compare -metric rmse tmpc6.jpg tmpc7.jpg null:
79.9543 (0.00122003)
```

My guess is that it is in Imagick and its interface to IM 7

**Comment by Trost123** [comment]
Hm. Why are your results 133x199 though?
And your commands have 133x300, where I mentioned 133x**200** in previous post.

Regarding the quality - your examples look the same compared to each other.
Compared to my examples it's (sharpness quality):
my v.7 image > your v.6\7 image > my v.6 image

I have 4 virtual servers from same hosting provider. PHP settings show PHP version 5.6 on all of them.
2 of them report ImageMagick 6.9.4-0 Q16 x86_64, other two report 7.0.5-4 Q16 x86_64.
When I run this test on all 4 I get 2 blurry results (v7) and 2 sharp result (v6).
Note that I'm a basic user and I don't know PHP well. All of this was pre-installed. I have no idea why is ImageMagick different on these servers.
If you know what else I can log through php files to debug this, I'll do it.

> My guess is that it is in Imagick and its interface to IM 7
Should I contact my hosting provider with this issue? I've no idea what this means.

**Comment by Trost123** [comment]
Also, in version 7, if I change:
`$image->sharpenImage(0, 0.6);`
to
`$image->sharpenImage(0, 2);`
(just to test if sharpen does anything at all)
I get this result:
![imagick_test](https://user-images.githubusercontent.com/21346282/27496772-1f123b9c-5860-11e7-8df2-42383baabaee.jpg)
Which doesn't look like sharpening to me at all. More like some kind of bloom.

**Comment by fmw42** [comment]
Sorry about my typo of 300 rather than 200. I have edited my post above and replaced the images. But is see no difference.

With regard to sharpen change from 0.6 to 2.0, I did this test with IM 7.0.5.4 and 7.0.60

`im7054 magick 27492314-7618021c-584e-11e7-8da4-9c0f396ec015.JPG -filter cubic -define filter:b=0.5 -resize 133x200 -sharpen 0x2 tmpc7054.jpg`

`im7 magick 27492314-7618021c-584e-11e7-8da4-9c0f396ec015.JPG -filter cubic -define filter:b=0.5 -resize 133x200 -sharpen 0x2 tmpc7060.jpg`

```
compare -metric rmse tmpc7054.jpg tmpc7060.jpg null:
0 (0)
```

So there does not seem to be any difference between the two versions of ImageMagick 7.

Here are my images using 0.6 and 2.0 in IM 7.0.5.4

`magick 27492314-7618021c-584e-11e7-8da4-9c0f396ec015.JPG -filter cubic -define filter:b=0.5 -resize 133x200 -sharpen 0x2 tmp7054_s2.jpg`

![sharpen 0x2](http://www.fmwconcepts.com/misc_tests/sharpen_test/tmp7054_s2.jpg)

`magick 27492314-7618021c-584e-11e7-8da4-9c0f396ec015.JPG -filter cubic -define filter:b=0.5 -resize 133x200 -sharpen 0x0.6 tmp7054_s0p6.jpg`

![sharpen 0x0.6](http://www.fmwconcepts.com/misc_tests/sharpen_test/tmp7054_s0p6.jpg)

**Comment by Trost123** [comment]
@fmw42 man, you're a genius!
Simplified my test case to:
```
<?php

error_reporting(E_ALL);
ini_set( 'display_errors','1');

//sending image header to proper display the image
header('Content-type: image/png');

//loading the image
$image = new Imagick('testimg.JPG');
$image->resizeImage(133, 200, Imagick::FILTER_CUBIC, 0.5);

echo $image;
?>
```

![Result](https://image.prntscr.com/image/9BeK-3rOTwelOAbuAIPKtA.png)

So this **is** a filter problem after all? Renamed this thread accordingly.

Doesn't solve my problem yet, but brings me another step closer to solution.
So, I guess new imagick on my host is really messing up the resize\cubic filer.

_P.S. I don't want to mess with my site's CMS code (which uses Imagick), so I guess I'll just reinstall version 6 on all servers and forget it._

**Comment by fmw42** [comment]
To be honest, I did not know that Imagick even supported ImageMagick 7, yet. So perhaps if it does, it still has some bugs.

**Comment by Trost123** [comment]
@fmw42 anyway, thanks for the help. There's no telling how long I'd struggle with this without someone cooperating. Now I can sleep peacefully. 🛌 
I thought you're the developer, because of your avatar. 😄 
I'll contact my hosting provider tomorrow and ask them to downgrade IM7 on those servers.

Leaving this issue open for the developer to see.

**Comment by fmw42** [comment]
I am not a developer, but I work with the ImageMagick developers to answer questions on their forum and prototype and test code. I script ImageMagick and have many little scripts, which you can see at http://www.fmwconcepts.com/imagemagick/index.php. 

But note that the ImageMagick team did not create nor do they support Imagick. That is a separate piece of software built upon ImageMagick. You can post to the Imagick forum at http://www.imagemagick.org/discourse-server/viewforum.php?f=18&sid=0412005dc66f5785fcb2d2e8d6a13449. I may be wrong, but I think the new Imagick developer's username is danack.

**Comment by Trost123** [comment]
I was always wondering if there is difference between ImageMagick and Imagick, or it's just an short alias for it. Now you made it clear.
Thanks for the link, I'll reference this issue there.

**Comment by fmw42** [comment]
As I said in my previous message:

> But note that the ImageMagick team did not create nor do they support Imagick. That is a separate piece of software built upon ImageMagick. You can post to the Imagick forum at http://www.imagemagick.org/discourse-server/viewforum.php?f=18&sid=0412005dc66f5785fcb2d2e8d6a13449. I may be wrong, but I think the new Imagick developer's username is danack.

**Comment by fmw42** [comment]
See also https://github.com/mkoppanen/imagick

**Comment by fmw42** [comment]
See also
https://github.com/Danack/Imagick-demos

**Comment by Trost123** [comment]
**snibgo** helped me resolve this issue [on the IMagick forum](http://www.imagemagick.org/discourse-server/viewtopic.php?f=18&t=32220). 🍾 

> I conclude that your v7 version (or, more likely, IMagick) is respecting "-filter cubic", so you get the mushy result. Your v6 version ignores "-filter cubic" and uses the default filter, with the better result.
