### ISSUE TITLE
Behavior change with convert command

### ISSUE THREAD

**Issue by chowbok** [ImageMagick/ImageMagick#5202]
### ImageMagick version

7.1.0.37

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

Before the latest version, the command below gave me an image with a transparent background. As of 7.1.0.37, I get a black background.

### Steps to Reproduce

`convert \( cover/1723.png -bordercolor none -background none -rotate -10 -repage +57+57 \) -colorspace sRGB -layers merge \( cover/1724.png -bordercolor none -background none -rotate +21 -repage -43+61 \) -colorspace sRGB -layers merge \( cover/1722.png -bordercolor none -background none -rotate -10 -repage +21-43 \) -colorspace sRGB -layers merge +repage -colorspace sRGB -flatten +repage -background black \( +clone -shadow 60x4+4+4 \) +swap -background none -colorspace sRGB -flatten -interlace Line output.png`

**Comment by chowbok** [comment]
I didn't think the input images were relevant, they're just non-transparent rectangular images. I can attach some if necessary.

Previous version was 7.1.0.36, but I've been using ImageMagick since 7.0.10.29 without this issue.

**Comment by snibgo** [comment]
To help debugging, perhaps you can make the simplest command that shows the problem.

Why are you using "convert" instead of "magick"? "convert" uses the old v6 syntax. V7 and v6 differ in their use of transparency.

**Comment by chowbok** [comment]
Having trouble reproducing this now. Sorry for the false alarm.
