### ISSUE TITLE
-define ftxt: documentation

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#5205]
### Describe the solution you'd like

I suggest adding the following to the "defines" page, https://imagemagick.org/script/defines.php , between "exr:color-type=value" and "fpx:view=value".

ftxt:chsep 	A single text character that separates channel values for reading and writing. Default: "," (Comma).

ftxt:format 	The format string for writing and reading. Default: "\x,\y:\c".  For escapes \x etc, see <a href="http://im.snibgo.com/fmttxt.htm">ftxt: formatted text</a>.

ftxt:hasalpha 	Whether the text has an alpha channel, for reading only. Default: false.

ftxt:nummeta 	The number of meta channels, for reading only. Default 0 (Zero).

**Comment by dlemstra** [comment]
I have updated the documentation here: https://github.com/ImageMagick/Website. This will be updated on our website in a couple of days.
