### ISSUE TITLE
OpenCL

### ISSUE THREAD

**Issue by Bxaa** [ImageMagick/ImageMagick#5206]
### ImageMagick version

ImageMagick-7.1.0-37-Q16-HDRI-x64

### Operating system

Windows

### Operating system, version and so on

Win10

### Description

One of old IM version (2020-21 Sadly, I can't find that version.)
```
<devices>
  <device name="CPU" score="1.102"/>
  <device platform="NVIDIA CUDA" vendor="NVIDIA Corporation" name="NVIDIA GeForce GTX 1060 6GB" version="465.89" maxClockFrequency="1708" maxComputeUnits="10" score="0.1098"/>
  <device platform="Intel(R) OpenCL HD Graphics" vendor="Intel(R) Corporation" name="Intel(R) UHD Graphics 630" version="27.20.100.8681" maxClockFrequency="1250" maxComputeUnits="24" score="0.3308"/>
</devices>
```
Current version not detect Nvidia OpenCL (ImageMagick-7.1.0-37-Q16-HDRI-x64-dll.exe)
What could be the reason?
```
<devices>
  <device name="CPU" score="1.299"/>
  <device platform="Intel(R) OpenCL HD Graphics" vendor="Intel(R) Corporation" name="Intel(R) UHD Graphics 630" version="30.0.101.1340" maxClockFrequency="1250" maxComputeUnits="24" score="0.3362"/>
</devices>
```

OpenCL should use all hardware discrete+integrated and why it not implemented in IM? (OpenCL support it)
This will give a noticeable performance boost.

### Steps to Reproduce

--\\--\\--

**Comment by dlemstra** [comment]
We no longer support NVIDIA with OpenCL because of all the random crashes we had reported. And I personally don't have an NVIDIA card to help me diagnose this problem.

**Comment by Bxaa** [comment]
Could you please specify from which version you removed nvidia support
I'll check source codes and fix it

Thx
