### ISSUE TITLE
16-bit png-files

### ISSUE THREAD

**Issue by heinerbilling** [ImageMagick/ImageMagick#5209]
### ImageMagick version

6.q16(1)

### Operating system

Linux

### Operating system, version and so on

??

### Description

Writing 16.bit unsigned integer data into png.files mund GDL with write_png.pro
produces always 8-bit-3 channels png-files.
Before I used IDL and could 16-bit Grayscale Image.
I test it with ex_query_png.pro.
I am still using ImageMagick-im6.q16(1)

Using convert 16bit png-files can be created.

read_png.pro cal read 16-bit-png-files, if (magick_IndexedColor(mid)) is ignored

### Steps to Reproduce

ex_query_png.pro

rgbdata = UINDGEN(3,320,240) ;UINDGEN(4,320,240)

cidata = BYTSCL(DIST(256))
cidatau=uint(cidata)*256
red = indgen(256)

green = indgen(256)

blue = indgen(256)

tempdir = GETENV('IDL_TMPDIR')
WRITE_PNG, tempdir+'rgb_image.png',rgbdata
WRITE_PNG, tempdir+'ci_image.png',cidata,red,green,blue
WRITE_PNG, tempdir+'ciu_image.png',cidatau,red,green,blue
...
 img = READ_PNG(names[i])

; Query and Read the data:

write_png.pro

;+
;
; NAME: WRITE_PNG
;
; PURPOSE: write a image from memory to a bitmap
;
; CATEGORY: Images (IO)
;
; CALLING SEQUENCE:
;    WRITE_PNG, filename, image, red, green, blue, $
;               order=order, transparent=transparent, $
;               test=test, verbose=verbose, help=help, debug=debug
;
; KEYWORD PARAMETERS:
;     ORDER      : 1 = top-bottom, 0 = bottom-top
;     VERBOSE    : Not Used
;     TRANSPARENT:
;
;
; OPTIONAL INPUTS: For pseudocolor only
;        red  : the Red colormap vector (for PseudoColor images)
;        green: the Green colormap vector (for PseudoColor images)
;        blue : the Blue colormap vector (for PseudoColor images)
...
pro WRITE_PNG, filename, image, red, green, blue, $
               order=order, transparent=transparent, $
               verbose=verbose, help=help, test=test, debug=debug
;
; this line allows to compile also in IDL ...
FORWARD_FUNCTION MAGICK_EXISTS, MAGICK_PING, MAGICK_READ
...
; usual 3D case [3,N,M]
;
if(nb_channels EQ 3) then begin
   mid=MAGICK_CREATE(im_size[1],im_size[2])
   MAGICK_WRITE, mid, image, rgb=rgb
   if (KEYWORD_SET(order)) then MAGICK_FLIP, mid
   MAGICK_WRITEFILE, mid, filename,"PNG"
   MAGICK_CLOSE, mid

**Comment by snibgo** [comment]
ImageMagick can read and write 16 bit/channel/pixel PNG files with no problem.

The question seems to be not about ImageMagick, but about GDL: GNU Data Language. See https://github.com/gnudatalanguage . I suspect the question should be directed there.

**Comment by fmw42** [comment]
I agree. I think the OP posted to the wrong forum. As far as I know GDL does not use Imagemagick.
