### ISSUE TITLE
crashing convert -gaussian-blur with --disable-shared

### ISSUE THREAD

**Issue by dylanjwolff** [ImageMagick/ImageMagick#5211]
### ImageMagick version

7.1.0-38 beta (249bcdf)

### Operating system

Linux

### Operating system, version and so on

Ubuntu 21.04, Kernel 5.11.0-49-generic

### Description

Hi!

I'm getting an `IOT Instruction (core dumped)` error when attempting to apply a gaussian blur to the attached image. It looks like there is a null pointer if I compile with `-00 -g`: 
    the `nexus_info` argument to `SetPixelCacheNexusPixels` at cache.c:5033 is `0x0`.

In gdb without the compiler flags, the error reported is a `double free or corruption`.

This is on main, commit https://github.com/ImageMagick/ImageMagick/commit/249bcdffd7ef8a31f1529b643ea2d5d0b1caeb57. OpenMP is enabled and this is running multi-threaded. If I configure and compile without `--disable-shared` the bug does not seem to reproduce.

Thanks!

### Steps to Reproduce

```
export CC=clang
export CXX=clang++
./configure --disable-shared
make
make install
magick convert bug.png -gaussian-blur 10x1 out.png
```

```
> clang --version
Ubuntu clang version 12.0.0-3ubuntu1~21.04.2
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

### Images

![bug](https://user-images.githubusercontent.com/17279039/172796579-c0c1f7ef-3fdb-4177-8ec1-4444b30c3b42.png)

**Comment by urban-warrior** [comment]
We tried your command on a Fedora system with clang 14.  It ran without complaint.    We'll track down a Ubuntu system tomorrow and see if we can reproduce the fault and report back.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.
