### ISSUE TITLE
Drawing on certain TIFF images inverts color

### ISSUE THREAD

**Issue by btacordex** [ImageMagick/ImageMagick#5214]
### ImageMagick version

7.1.0-37

### Operating system

MacOS

### Operating system, version and so on

macOS 12.4, ImageMagick installed via homebrew

### Description

Drawing on certain TIFF images inverts the color.

### Steps to Reproduce

Please refer to the images in the archive. The original image is source.tif. The following commands were issued, resulting in the other images:

`magick source.tif noRect.tif`
`magick source.tif -draw "rectangle 50,50 200,200" rect.tif`
`magick source.tif -draw "rectangle 50,50 200,200" rect.jpg`

As you can see, reading this TIFF image, drawing to it, and then writing back to a TIFF image results in the colors being inverted. This behavior does not happen when drawing does not occur, nor does it happen when also converting to a JPEG. Although I did not include images, I did not experience this behavior when the source image was a JPEG.

### Images

[images.zip](https://github.com/ImageMagick/ImageMagick/files/8874183/images.zip)

**Comment by fmw42** [comment]
Your tiff file has 

`tiff:photometric: min-is-white`

So it is basically inverted. When writing the output to TIFF, Imagemagick writes with 

`tiff:photometric: min-is-black`

So do the following:

`magick source.tif -fill black -define quantum:polarity=min-is-white -draw "rectangle 50,50 200,200" drawToTif.tif`

See https://imagemagick.org/script/formats.php

**Comment by btacordex** [comment]
So... ImageMagick should just use the source image's value.

**Comment by fmw42** [comment]
Generally, yes, it does. But it seems tif has been different for years. Even the compression is not preserved as far as I can tell. Perhaps there is something about using libtiff.
