### ISSUE TITLE
Crafted JPEG hangs `convert` and produce 48G large file, causing DoS attack

### ISSUE THREAD

**Issue by chinggg** [ImageMagick/ImageMagick#5223]
### ImageMagick version

7.1.0

### Operating system

Linux

### Operating system, version and so on

ImageMagick 7.1.0-37(latest release) on Linux

### Description

A flaw in `libjpeg` library used by `convert` program in ImageMagick 7.1.0 allows attacker to make DoS attack via uploading a crafted JPEG file with large width and height.

### Steps to Reproduce

1. Choose an arbitary image, modify particular bytes to change its width and height to 65500.
2. Execute `convert file.jpg file.pdf`
3. The program should hang for nearly an hour, with a large file of 48G size produced in `/tmp/`

### Images

![image](https://user-images.githubusercontent.com/24590067/173577490-b26f624c-cdee-40bc-81ca-7ae1e252f3bd.png)

**Comment by dlemstra** [comment]
Did you run this with a security policy (https://imagemagick.org/script/security-policy.php) enabled?

**Comment by urban-warrior** [comment]
ImageMagick recommended practices strongly encourage you to configure a security policy that suits your local environment. 
 Add this to your security policy:

```
  <policy domain="resource" name="width" value="8KP"/>
  <policy domain="resource" name="height" value="8KP"/>
```

That should resolve the issue.  If not, post a link to an image we can download and reproduce the issue.
