### ISSUE TITLE
ESP file had wrong colorspace for Ubuntu

### ISSUE THREAD

**Issue by OlegOLK** [ImageMagick/ImageMagick#5232]
### ImageMagick version

7.1.0-37

### Operating system

Linux

### Operating system, version and so on

Ubuntu Focal 20.04

### Description

We have a bunch of ESP files that we are trying to convert to JPG and the result of the operation is the image with the wrong colors. After some research we figure out that on Windows with the  7.1.0-37 magic identify command returns `colorspace: CMYK` but for ubuntu setup, it is `colorspace: sRGB`.

### Steps to Reproduce

1. Create a docker file with the content like: 

```
FROM ubuntu:focal as build-libs

RUN apt-get update && \
		DEBIAN_FRONTEND=noninteractive apt-get install -y \
		'build-essential=12.8ubuntu1' \
		'cmake=3.16.3-1ubuntu1' \
		'curl=7.68.0-1ubuntu2.11' \
                'darktable=3.0.1-0ubuntu1' \
		'libltdl-dev=2.4.6-14' && \
		mkdir /dist && \
		mkdir /dist/usr && \
		mkdir /dist/usr/bin
		
ARG IM_VERSION=7.1.0-37

RUN mkdir /imagemagick && \
		cd /imagemagick && \
		curl -o imagemagick.tar.gz https://codeload.github.com/ImageMagick/ImageMagick/tar.gz/$IM_VERSION && \
		tar -xzvf imagemagick.tar.gz && \
		cd ImageMagick* && \
		./configure \
			--sysconfdir=/etc \
			--prefix=/usr \
			--disable-static \
			--with-tcmalloc \
			--with-threads \
			--with-x \
			--with-tiff \
			--with-png \
			--with-webp \
			--with-rsvg \
			--with-gs-font-dir=/usr/share/fonts/Type1 \
			--with-modules \
			--with-lcms \
			--with-xml && \
		make -j$(grep -c processor /proc/cpuinfo) DESTDIR=/dist install
		
RUN sed -i '/<delegatemap>/ a <delegate decode="ps:cmyk" stealth="True" command="&quot;gs&quot; -sstdout=%%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 &quot;-sDEVICE=png16m&quot; -dTextAlphaBits=%u -dGraphicsAlphaBits=%u &quot;-r%s&quot; %s &quot;-sOutputFile=%s&quot; &quot;-f%s&quot; &quot;-f%s&quot;"/>' /etc/ImageMagick-7/delegates.xml

```
2. copy the image above to the docker container
3. run: `identify -verbose file.eps`
4. verify the output: `Colorspace: sRGB`

### Images

[file.zip](https://github.com/ImageMagick/ImageMagick/files/8913956/file.zip)

**Comment by fmw42** [comment]
Your eps file has a CMYK profile. So that is why it shows CMYK.  To convert to CMYK JPG

`magick file.eps file.jpg`

to convert to sRGB JPG, you need to use a profile

`magick file.eps -profile path_to/sRGB.icc file.jpg`

The colors both ways look correct to me and match what I get viewing the eps file in Mac Preview browser.

**Comment by fmw42** [comment]
In Mac OSX (Unix-like), magick display seems to ignore the colorspace or the profile. So this

magick display file.eps

looks color inverted compare to the use of profiles. Does magick display ignore imbedded non-sRGB profiles or CMYK colorspace when displaying without a profile conversion to sRGB.

This does work properly, if I explicitly specify a profile.

`magick display -profile path_to/sRGB.icc file.eps`

**Comment by OlegOLK** [comment]
Wow, sorry didn't notice your fast reply. The thing is that `identify` shows sRBG for that file for my dockerfile ENV

**Comment by OlegOLK** [comment]
output of the identify  `file.eps EPS 1198x799 1198x799+0+0 16-bit sRGB 1.35926MiB 0.000u 0:00.004`

**Comment by fmw42** [comment]
On my Mac OSX Monterey, I get CMYK

```
magick identify file.eps
file.eps EPS 1198x799 1198x799+0+0 16-bit ColorSeparation CMYK 3828910B 0.010u 0:00.005

```

I do not know how your docker was built. What do you get from 

`magick -version`

**Comment by OlegOLK** [comment]
```
Version: ImageMagick 7.1.0-37 Q16-HDRI x86_64 b65d0d9af:20220605 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): jbig jng jpeg ltdl lzma png tiff webp x zlib
Compiler: gcc (9.4)
```

**Comment by fmw42** [comment]
You are missing lcms 2, which is the color delegate. Install that. You seem to be missing Ghostscript also.  Please install the needed delegates and re-install ImageMagick

**Comment by OlegOLK** [comment]
I will try later today, thanks a lot for your support. I will reply in a several hours

**Comment by fmw42** [comment]
See https://www.littlecms.com
