### ISSUE TITLE
ImageMagick crashes after loading an unknown file

### ISSUE THREAD

**Issue by hbl917070** [ImageMagick/ImageMagick#5233]
### ImageMagick version

7.1.0-29 Q8 x64

### Operating system

Windows

### Operating system, version and so on

Windows 10 64-bit 21H2

### Description

This "中文.VBR3" file is not a picture, but a project file of some program.
This is a file I copied from my school computer many years ago, I have no more information about this file.

Once ImageMagick loads this file, and the path of the file contains symbols other than alphanumeric, the program will crash immediately.
I use "Magick.NET" in C#, even with try syntax, it still can't stop the program from crashing, which may be a big problem for the server.
```C#
try {
	new MagickImage("中文.VBR3");
} catch { }
```

### Steps to Reproduce

I use "IMDisplay.exe" to open the file.
Under normal circumstances, when "IMDisplay.exe" encounters a file that cannot be loaded, only the prompt "reported an error" will pop up.
But if I open "中文.VBR3", IMDisplay.exe will crash immediately.
![GIF 2022-6-16 上午 09-25-10](https://user-images.githubusercontent.com/12185698/173972008-bd050b56-fcc5-4dc0-92ce-61d72f92b0d0.gif)

Running `identify` or `convert` with the terminal will also cause a crash and no message will be returned.
```
identify "D:\中文.VBR3"
```

Even with a white list of `policy.xml`, there is still no way to stop the crash.
```xml
<policymap>
    <policy domain="delegate" rights="none" pattern="*" />
    <policy domain="coder" rights="none" pattern="*" />
    <policy domain="coder" rights="read|write" pattern="{GIF,JPEG,PNG,WEBP}" />
</policymap>
```

### Images

[test.zip](https://github.com/ImageMagick/ImageMagick/files/8914889/test.zip)

**Comment by dlemstra** [comment]
This issues is caused by a failing call to `gzopen`. And we should probably use `gzopen_w` on Windows instead.
