### ISSUE TITLE
Background Opacity rounding (-9.9999999999999997989e-13)

### ISSUE THREAD

**Issue by pgodwin** [ImageMagick/ImageMagick#5264]
### ImageMagick version

Version: ImageMagick 7.1.0-40 beta Q16-HDRI x86_64 21a5642bc:20220620 https://imagemagick.org Copyright: (C) 1999 ImageMagick Studio LLC License: https://imagemagick.org/script/license.php Features: Cipher DPC HDRI OpenMP(4.5) Delegates (built-in): bzlib djvu fontconfig freetype jbig jng jpeg lcms lqr lzma openexr png tiff x xml zlib Compiler: gcc (9.4)

Just built the latest version of ImageMagic from source commit b11d64704f46cedade2ca3cdcebbc8d1f315035e

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04.4 LTS

### Description

When converting svg files to png with a transparent background, the opacity value seems to be rounded incorrectly.

### Steps to Reproduce

```bash
$ convert -verbose -density 300 -background none Settings.svg Test.png
'inkscape' '/tmp/magick-qMRSiukCiXR6gpVoVOocOQNdYsTdI6AY' --export-filename='/tmp/magick-4WdtWHJ2ciWTLkcs9Fn3fFSjR6I1TWsV.png' --export-dpi='300' --export-background='rgb(0%,0%,0%)' --export-background-opacity='-9.9999999999999997989e-13' > '/tmp/magick-vq6CXeVohKSCTTaqHt-uxMSU06x5lFvW' 2>&1
mvg:/tmp/magick-ftZhEnmZoFqUlWfBFhGjvqa6Q9rkwhdW=>/tmp/magick-ftZhEnmZoFqUlWfBFhGjvqa6Q9rkwhdW MVG 50x50 50x50+0+0 16-bit sRGB 1686B 0.010u 0:00.011
Settings.svg SVG 50x50 50x50+0+0 16-bit sRGB 1686B 0.000u 0:00.000
Settings.svg=>Test.png SVG 50x50 50x50+0+0 16-bit sRGB 1686B 0.000u 0:00.007
```

### Images

Source:
![Settings](https://user-images.githubusercontent.com/1046558/175224033-03c3035c-c641-4627-8883-ff3ed6698d1a.svg)

Result:
![Test](https://user-images.githubusercontent.com/1046558/175224013-cb0c02dc-0991-424a-ae14-f8124fd7f4c2.png)

**Comment by snibgo** [comment]
The problem is independent of the Inkscape version. It occurs in IM v7.1.0-32, and probably many other versions.
```
f:\web\im>%IMG7%magick -verbose -background None 410c.svg x.png
"inkscape.exe" -z "C:/Users/Alan/AppData/Local/Temp/magick-ATmAzEJ5mCvNWWx3d8yRD
X3oe7hjDM5w" --export-png="C:/Users/Alan/AppData/Local/Temp/magick-_Y-OY58ZHgtyo
terPDrharovQYSSbEMP.png" --export-dpi="96" --export-background="rgb(0%,0%,0%)" -
-export-background-opacity="-9.9999999999999997989e-13" > "C:/Users/Alan/AppData
/Local/Temp/magick-V7DJRJ1RN77RDhUn1AGMKOft1Bmu0PkJ" 2>&1
410c.svg SVG 100x100 100x100+0+0 16-bit sRGB 235B 0.094u 0:15.306
410c.svg=>x.png SVG 100x100 100x100+0+0 16-bit sRGB 235B 0.016u 0:00.026
```
I don't know what Inkscape does with a negative background-opacity, or what we might expect it to do. Inkscape seems to treat this value as zero. But it would be beter if IM issied:
```
-export-background-opacity="0"
```

**Comment by fmw42** [comment]
@snibgo. It seemed to work fine for me. Any idea why?

**Comment by dlemstra** [comment]
It looks like this issue was introduced in this commit: 43e07c0.

**Comment by fmw42** [comment]
But it seems unaffected on my Mac in 7.1.0.32 and 7.1.0.39

**Comment by snibgo** [comment]
In 7.1.0-33, svg.c included:
```
  (void) FormatLocaleString(opacity,MagickPathExtent,"%.20g",QuantumScale*
    image->background_color.alpha-MagickEpsilon);
```
I suppose "-background None" sets image->background_color.alpha to zero, and subtracting MagickEpsilon gives a small negative number.

The other common case is an opaque colour for "-background":
```
f:\web\im>%IMG7%magick -verbose -background red 410c.svg x.png
[...] --export-background-opacity="0.99999999999900002212" [...]
```
So the number is slightly less than "one".

Is there a good reason for subtracting MagickEpsilon?
