### ISSUE TITLE
-define jpeg:arithmetic-coding=on produce an unreadable jpeg file

### ISSUE THREAD

**Issue by Vaitek** [ImageMagick/ImageMagick#5278]
### ImageMagick version

7.1.0-39

### Operating system

Windows

### Operating system, version and so on

Microsoft Windows 11 21H2 [Version 10.0.22000.778]

### Description

After converting following file with parameter `-define jpeg:arithmetic-coding=on` i get a file that can't be opened by Windows photo viewer and some other tools (for example Python Pillow library) 

* Original file: https://drive.google.com/file/d/1JS_wKkJOh5LO57zboG5DBkcshHVJyeNv/view?usp=sharing
* Result (bad ) file: https://drive.google.com/file/d/1R5XORTDAyORyGfbpLeIM515NQ9H4qFQo/view?usp=sharing

Command line:
`magick convert 0.jpg -quality 50 -define jpeg:arithmetic-coding=on res.jpg;`

```
magick --version
Version: ImageMagick 7.1.0-39 Q16-HDRI x64 21a5642:20220620 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (193231329)
```

### Steps to Reproduce

1. Download original image
2. Run `magick convert 0.jpg -quality 50 -define jpeg:arithmetic-coding=on res.jpg;`
3. Open result file in Windows photo viewer or try python code:
   ```
   from PIL import Image
   with Image.open("res.jpg") as image:
       image.save("out.png", format="png")
   ``` 

### Images

Files are too big for your bugs tracker. Please download them from google drive 
* Original file: https://drive.google.com/file/d/1JS_wKkJOh5LO57zboG5DBkcshHVJyeNv/view?usp=sharing
* Result (bad ) file: https://drive.google.com/file/d/1R5XORTDAyORyGfbpLeIM515NQ9H4qFQo/view?usp=sharing

**Comment by dlemstra** [comment]
It cannot be opened by those tools because they don't support arithmetic coding.
