### ISSUE TITLE
Different Output with indexed grayscale bitmaps

### ISSUE THREAD

**Issue by v11** [ImageMagick/ImageMagick#5285]
### ImageMagick version

ImageMagick 7.1.0-30

### Operating system

MacOS

### Operating system, version and so on

Mac OS Monterey 12.3

### Description

I'm working on a project with e-ink displays and I'm converting images to bitmaps so I can display them on the display. Now I have a strange problem.

I convert images (JPG or PNG) to a bitmap with the following specifications:

- 8bit
- 256 Grayscale
- 1200x825

Conversion with Imagemagick
When I use Imagemagick for the conversion, I get a bitmap which is displayed correctly in OSX. But on the e-paper display everything is displayed much too dark.

![display-bad](https://user-images.githubusercontent.com/18447866/176646321-3b5d9a87-8616-4466-8d80-c1804e549e90.JPG)

I use the following command:
`magick image.jpg -resize 1200x825^ -gravity center -extent 1200x825 -alpha off -colorspace Gray -colors 256 -compress none -depth 8 BMP3:image.bmp`

Conversion with Photoshop
When I use Photoshop for the conversion, everything fits just fine. Therefore I exclude a bug in the bitmap parsing in my firmware.

![display-good](https://user-images.githubusercontent.com/18447866/176646118-8616ee8f-bcd9-42e6-8ad1-502e608b8453.JPG)

Now I have found out: If I make the source image (JPG) one pixel smaller, for example 1200x824, then also the image converted with Imagemagick looks good on the display. 

When I analyze the two images in Photoshop, I see a different color table:

1200x825 (Faulty image)
<img width="1022" alt="ps_1200x825" src="https://user-images.githubusercontent.com/18447866/176647178-5bbc61cf-598a-4f2f-92d5-bb9b3669ccae.png">

1200x824 (Good image)
<img width="1020" alt="ps_1200x824" src="https://user-images.githubusercontent.com/18447866/176647245-06cc4cc5-31e5-4845-9e8a-ad9de8366993.png">

I have uploaded the source images here:
[http://vision11.ch/share/temp/image_1200x825.jpg](http://vision11.ch/share/temp/image_1200x825.jpg)
[http://vision11.ch/share/temp/image_1200x825.bmp](http://vision11.ch/share/temp/image_1200x825.bmp)

[http://vision11.ch/share/temp/image_1200x824.jpg](http://vision11.ch/share/temp/image_1200x824.jpg)
[http://vision11.ch/share/temp/image_1200x824.bmp](http://vision11.ch/share/temp/image_1200x824.bmp)

Can someone give me an explanation why the conversion is different? Any help is greatly appreciated.

### Steps to Reproduce

I have attached the sourceimage and command above.

**Comment by v11** [comment]
Thanks for the feedback. I only parse 8-bit bitmaps in my firmware. TrueColor will output RGB (24-bit) images.

Anyway, i found a working solution:
I am now using remap with a predefined gradient png (black to white with 256 steps) and the following command:
`magick image.jpg -resize 1200x824^ -gravity center -extent 1200x824  -dither FloydSteinberg -remap remap-256grey.png -compress none -type Palette -depth 8 BMP3:image.bmp`

Now the pallete stays consistent and imagemagick will not reduce its pallete colors. And this finally will not confuse my bitmap parser.

**Comment by LeonMillan** [comment]
> Thanks for the feedback. I only parse 8-bit bitmaps in my firmware. TrueColor will output RGB (24-bit) images.
> 
> Anyway, i found a working solution: I am now using remap with a predefined gradient png (black to white with 256 steps) and the following command: `magick image.jpg -resize 1200x824^ -gravity center -extent 1200x824 -dither FloydSteinberg -remap remap-256grey.png -compress none -type Palette -depth 8 BMP3:image.bmp`
> 
> Now the pallete stays consistent and imagemagick will not reduce its pallete colors. And this finally will not confuse my bitmap parser.

I was about to go insane until I tried this workaround and it worked, thank you so much. The fact ImageMagick will ignore your commands and decide on its own to optimize the image is absurd to me.
