### ISSUE TITLE
Resource files in static libraries on Windows lead to LNK1241 error

### ISSUE THREAD

**Issue by egzumer** [ImageMagick/ImageMagick#529]
I used ImageMagick-7.0.5-4 on Visual Studio 2015.

Static libraries generated by VisualMagick project have resource files linked into ***.lib** files which can lead to linker errors in projects which use this libraries. I believe resource files shouldn't be linked into static builds.
In my case I made static library project which links ImageMagick. When building debug version I get

> LNK1241 resource file already specified CORE_RL_zlib_.lib(Resource.rc)

To fix this I edited **.\VisualMagick\configure\ProjectFile.cpp** and at the end of **ProjectFile::loadSource** method I added

> `if (_wizard->solutionType() > 0) _resourceFiles.clear();`

**Comment by dlemstra** [comment]
I am resolving that issue like this in my own project that statically links ImageMagick: https://github.com/dlemstra/Magick.NET/blob/master/Source/Magick.NET.Native/Stdafx.h#L35.

**Comment by dlemstra** [comment]
Can we close this issue @egzumer?

**Comment by egzumer** [comment]
I'm not sure, just made a report and published my solution, don't see any related commits. The decision is on project administrators side, if this is a valid request. I can make a merge request if that helps.

**Comment by dlemstra** [comment]
Did you see my suggestion on how you should link the .lib files? You should not use `*.lib`.

**Comment by egzumer** [comment]
Oh, ok I just realized that meanwhile I did find out that static libraries shouldn't be linked into other static libraries so that was my mistake. We can close this then.
