### ISSUE TITLE
Converting a screenshot taken on a classic Macintosh (MacPaint format) results in a scrambled image

### ISSUE THREAD

**Issue by aaronk6** [ImageMagick/ImageMagick#5291]
### ImageMagick version

7.1.0-39 Q16-HDRI arm 20175

### Operating system

MacOS

### Operating system, version and so on

macOS Monterey Version 12.4

### Description

Converting screenshots taken on a vintage Macintosh computer running [System 6](https://en.wikipedia.org/wiki/System_6) will result in scrambled output.

Other tools such as macptopbm (from netpbm package) or GraphicConverter 11 (GUI image converter for macOS) will convert the image correctly.

### Steps to Reproduce

You’ll need a screenshot taken on [System 6](https://en.wikipedia.org/wiki/System_6) (example file attached).

Screenshots from System 6 are stored in [MacPaint format](http://fileformats.archiveteam.org/wiki/MacPaint).

```
$ convert mac:Screen\ 0 Screen\ 0.png
```

**Output:**

![Screen 0](https://user-images.githubusercontent.com/446063/177047631-2e718afa-af44-41d6-a208-00ab4f780162.png)

**Expected output:**

![Screen 0 copy](https://user-images.githubusercontent.com/446063/177047732-d524e850-d4af-4afe-9bd2-f482f477fe91.png)

### Images

[Screen 0.zip](https://github.com/ImageMagick/ImageMagick/files/9035105/Screen.0.zip)

**Comment by fmw42** [comment]
I can confirm on IM 7.1.0.39 Q16 Mac OSX Monterey (on M1 Mac). I renamed the file put the suffix on it and also added the Mac: prefix.

`magick mac:screen_0.mac screen_0.png`

![screen_0](https://user-images.githubusercontent.com/13458218/177048277-b7dcc096-2150-49a9-bb10-511b546f1aa5.png)

I do get the proper result using Mac Preview and also GraphicConverter.

**Comment by aaronk6** [comment]
@fmw42 Thanks for confirming! How did you manage to open the file in Preview app though? I tried appending the `.mac` extension, however, that doesn’t seem to be recognized by Preview. Also no luck with `.pntg` or `.pic`.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by aaronk6** [comment]
@urban-warrior Wow, that was fast. Thanks a lot! I’ll watch out for the beta release tomorrow.

Is it expected that https://imagemagick.org/download/beta/ is returning 404 right now?

**Comment by urban-warrior** [comment]
Try https://imagemagick.org/archive/beta.

**Comment by fmw42** [comment]
> Thanks for confirming! How did you manage to open the file in Preview app though? I tried appending the .mac extension, however, that doesn’t seem to be recognized by Preview. Also no luck with .pntg or .pic.

My mistake. I just double clicked and thought it opened in Preview. But it actually opened in GraphicConverter.

I just now tried drag and drop on Preview, but nothing happened.
