### ISSUE TITLE
File not recognized as SVG if it starts with a newline or space

### ISSUE THREAD

**Issue by dgsiegel** [ImageMagick/ImageMagick#5294]
### ImageMagick version

7.1.0-39

### Operating system

Linux

### Operating system, version and so on

Fedora 36

### Description

I've been trying to build a minimal ImageMagick in order to use it on an embedded system to identify files which get uploaded to that system (Mostly JPG, PNG and SVG). As such I compiled ImageMagick with its internal SVG/XML coder (ie. `--with-xml --without-rsvg`), no RSVG or Inkscape.

Files don't have any file extension, but consist of just a random string or characters (e.g. `foobar`). I now want to know what file type these files are. A few of the SVG files begin with an empty line, e.g.

```

<svg xmlns="http://www.w3.org/2000/svg">
</svg>
```

When calling `magick identify [file]`, I get this output:

`identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/576.`

If I remove the newline manually and re-run the command, I'll get this:

`[file] SVG 300x150 300x150+0+0 8-bit sRGB 633B 0.000u 0:00.000`

But unfortunately I can't really change these files manually.

It seems that this coder only compares the first 4 characters of a file, but as that includes the newline character, the SVG doesn't get recognized: https://github.com/ImageMagick/ImageMagick/blob/main/coders/svg.c#L239

### Steps to Reproduce

- Compile ImageMagick as described above
- Create a sample SVG with a leading newline
- Call `magick identify [file]`

### Images

```

<svg xmlns="http://www.w3.org/2000/svg">
</svg>
```

**Comment by urban-warrior** [comment]
We could add a check for a single whitespace before the `<svg` element to identify a SVG document file.  However, its not a robust solution since two whitespaces would then fail detection.   Identification is designed to be fast so any "magic" string must be well-known and in a predicable location.  Even the `file` command fails detection if a whitespace precedes the `<svg` element.

**Comment by dgsiegel** [comment]
You're right, checking for a single whitespace won't do it. But how about removing all whitespaces/newlines at the beginning of a file before doing the check? Sort of like a `trim` function.

**Comment by urban-warrior** [comment]
We had some concern about performance issues if had to search past whitespace, however, if we restrict the search to just a few coders, such as SVG, it should work.  We'll add a patch to the main branch later today.

**Comment by dgsiegel** [comment]
This is great! Thank you for being so quick!
