### ISSUE TITLE
Median calculation is incorrect

### ISSUE THREAD

**Issue by blue-j** [ImageMagick/ImageMagick#5298]
### ImageMagick version

7.1.0-39

### Operating system

MacOS

### Operating system, version and so on

12.4

### Description

We just spent hours comparing metrics between IM, Gimp, ImageJ, Photoshop, as well as the results from several people independently calculating them.

IM was perfect in all metrics and in accord for all except median. The median values seem far off. In the sample photo I provide, the correct value is 98, and IM reports 72, for the red channel.

We reserve the right to be wrong! 🤘 

### Steps to Reproduce

magick identify input.jpg -channel red -format “%[fx:255*median]”

### Images

![7771pre_d48bb953cd52d63](https://user-images.githubusercontent.com/3990142/177280251-436ba58c-ec8b-4dfc-adff-ff55a887aaf3.jpg)

**Comment by fmw42** [comment]
`magick identify input.jpg -channel red -format “[fx:255*%median]”`

You have the % in the wrong place. It should be

`magick identify input.jpg -channel red -format “%[fx:255*median]”`

**Comment by blue-j** [comment]
> `magick identify input.jpg -channel red -format “[fx:255*%median]”`
> 
> You have the % in the wrong place. It should be
> 
> `magick identify input.jpg -channel red -format “%[fx:255*median]”`

Thanks, Fred!  That was just a typo in this forum - we were using the proper command during tests.

**Comment by blue-j** [comment]
> We extracted the red channel creating a list of 326900 values. We passed this list to a couple of Python methods to calculate median and it returned 70. The `identify -verbose input.jpg` returns 70 as the median value as expected. With this command:
> 
> ```
> magick input.jpg -channel red -format "%[median]" info:
> ```
> 
> we get 17990. Scale to 8-bits, 17990/257, we confirm the correct median is 70.

I thank you for your cross-checking the calculation.  (And for years of sharing your knowledge and code!)

I'd like to share with you our work and method.  We first extracted the histogram of the red channel.  This seems already different from your method?  We sought the median OF the histogram, which seems to be what other platforms mainly attend to:

[https://docs.google.com/spreadsheets/d/1aPj5Xuqp0D1qv6rQYwHcl3Hm6tWe2jjdXJXEa00zlVM/edit?usp=sharing]

Column B shows the histogram data for the red channel.  You can see the values we obtained from other imaging software in the sheet as well.

Have we made a fundamental error here in scoping the calculation?

Thanks in advance for your time and expertise.   - J

**Comment by SafetyCar** [comment]
Sorry, I found this topic interesting and I've been looking at it.

I looked at the spreadsheet and I saw the accumulated column, I took the last value which at that point should be the total, and divided it by 2. Then searching that number, it lands near the value mentioned by the other user.

Because of that I've made some more attempts and I've noticed that adding `-flop` after the file name changes the output to 122, and `-flop -flop` brings it back to 70. And also seems to be affected by -sort-pixels, etc.

**Comment by blue-j** [comment]
@fmw42 Hey Fred, would you mind affirming this?  IM's other statistics are perfect, but we simply cannot make the median output reconcile with anyone else's output, even when we use all pixels and avoid histogram binning.

**Comment by blue-j** [comment]
> `magick identify input.jpg -channel red -format “[fx:255*%median]”`
> 
> You have the % in the wrong place. It should be
> 
> `magick identify input.jpg -channel red -format “%[fx:255*median]”`

(Please note that i corrected this in the OP, as it is a distraction, and I don't want any others to try using my malformed command.)

**Comment by blue-j** [comment]
Here's an example of Python used with scipy and numpy:

`import numpy as np
from scipy.ndimage import median as scimedian
from PIL import Image, ImageStat
infile = 'input.jpg'
im = Image.open(infile)
pix_val = list(im.getdata())
d = [x[0] for x in pix_val]
n = len(d)
d = sorted(d)
median = float((d[int((n-1)/2)] + d[int(n/2)])/2.0)
print("formula median", median)
allpixels = sum(d)
median_index = (allpixels + 1) / 2
total = 0
for i in d:
    total += d[i]
    if total > median_index:
        median = int(i)
        break
print("algo median", median)
print("numpy median",np.median(d))
print("scipy median",scimedian(d))
stat = ImageStat.Stat(im)
print("PIL median",stat.median[0])`

**Comment by urban-warrior** [comment]
Run this script:

```
import statistics

grays = []
with open("grays.txt",'r') as data_file:
  for gray in data_file:
    grays.append(int(gray))
median_value = statistics.median(grays)
print(median_value/257)
```

[grays.txt](https://github.com/ImageMagick/ImageMagick/files/9057239/grays.txt)

The grays text file contains the red channel intensities at 16-bit.  The script returns 17990 which we scale back to 8-bit, which us 70.

**Comment by SafetyCar** [comment]
I have to agree that with that script I get 70.
And I've also managed to sort the grays.txt and also end up with the same value.
I'm still a bit concerned about the value 122 that I got when using -flop though.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by blue-j** [comment]
I can say this - this did not result in the same values:
magick infile.jpg -depth 16 -channel red ~/output.txt

**Comment by urban-warrior** [comment]
We concentrated on ensuring our median algorithm was correct and our assumption was that the red channels pixels were expected values.  Turns out the median algorithm was correct but we were gathering the wrong pixel values.  Now the correct median pixel is returned and the results are invariant as expected (-flop returns the same value for median).

**Comment by blue-j** [comment]
I learned a lot during this, and I thank you for your time sincerely.  <deep bow>  - J

**Comment by SafetyCar** [comment]
> Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

Thanks for looking into it.
I'm trying to follow the beta download link in your reply but it redirects me and I can't see anything.
I'm not sure if I'm being impatient or there's a problem with the link.

**Comment by fmw42** [comment]
https://imagemagick.org/archive/beta/
