### ISSUE TITLE
'UnregisterDOTImage' should check whether 'graphic_context' is NULL

### ISSUE THREAD

**Issue by civodul** [ImageMagick/ImageMagick#53]
We observed a test failure of 'Magick++/tests/color' in 6.9.2-1, which the attached patch fixes (see the explanation at the top of the file.)

HTH,
Ludo'.

**Comment by civodul** [comment]
Seems I can't attach a patch, but you can get it here: http://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/patches/imagemagick-test-segv.patch .

**Comment by dlemstra** [comment]
We already have checks for that in the latest version of ImageMagick. I would advise you to upgrade to the latest version.

**Comment by civodul** [comment]
Dirk Lemstra <notifications@github.com> skribis:

> We already have checks for that in the latest version of ImageMagick. I would advise you to upgrade to the latest version.

My bad, thanks!

Ludo’.
