### ISSUE TITLE
In Memory Processing

### ISSUE THREAD

**Issue by bubba-h57** [ImageMagick/ImageMagick#530]
I have a desire to implement a memory only pipeline for processing PDF Pages -> IMG. Initially, I only need to handle single page PDFs. They will contain a single page with anything from a letter sized page to a large format blueprint, the large format will make up about 95% of all the conversions.

I can not use any disk space at all, nor an OS  implemented ramdisk or tmpfs or any mounts at all for that matter, but I have more than enough RAM to do everything I want to do. The high-level pipeline would look like:

1. Download PDF to Blob from URL
2. Load PDF into _(libvips, poppler, libgs, ?)_
3. Convert PDF to some reasonable image format. _(Generic Ghostscript command line for this would look like_ `gs -dNOPAUSE -q -dBATCH -o"out.png" -dFirstPage=1 -dLastPage=1 -sDEVICE=png256 -r300x300  in.pdf` _although I hope to tweak that such that for black & white blueprints I can get a much smaller file size but still have good support for full-color blueprints/graphics. I would also like to come up with a process to resize these large format images to something that is still big enough to allow zooming in and seeing all the detail w/out being so massive.)_
4. Upload resulting image to URL

Ultimately I desired to do this in PHP _(because that is what everyone else on the team writes in)_ and I tried using the [imagick](https://github.com/mkoppanen/imagick) PHP extension. However, the 
underlying [ImageMagick](https://github.com/ImageMagick/ImageMagick) library always writes a PDF Blob to a temp file prior to passing it off to gslib.

Here is some sample code of what I was trying in PHP:
```php
$data = file_get_contents($uri); //560MB Single Page PDF
$image = new Imagick();
$image->readImageBlob($data);

$colorCount = $image->getImageColors();

 //Reduce the image to 256 colours nicely.
if ($colorCount > 256) {
     $this->info('Reduce the colors nicely.');
     $image->quantizeImage(256, \Imagick::COLORSPACE_RGB, 0, false, false);
} else {
     $image->setColorspace(\Imagick::COLORSPACE_RGB);
}
$image->setImageDepth(8);
$image->setImageFormat('png8');
$this->info('Writing Image: ' . $outputPath);
$image->writeImage($outputPath);
```

Here are the relevant calls:
[imagick](https://github.com/mkoppanen/imagick/blob/3acc635fe321bde7e2154f0cd01e6aa7d970bc3f/imagick_class.c#L3840)->[magick-wand](https://github.com/ImageMagick/ImageMagick/blob/f19d414d0ac4527544fef324969aa2a5d38b1027/MagickWand/magick-image.c#L8248) -> [magic-core](https://github.com/ImageMagick/ImageMagick/blob/3e69675df13c81e9acee2a532b1b31f947985271/MagickCore/blob.c#L434)

So I could successfully load the blob in memory via PHP, pass it off to imagick, and no matter what else I do, it always writes a temp cache and then finishes the process with no other disk activity.

Is there any particular way that I can configure, build or compile Imagemagick to use the blob w/out writing a tmp file? Or is this simply not something that Image Magick can do with Ghostscript?

I would prefer to do this in a scripting language like PHP, Python, Nodejs _(in order of personal preference)_ although I am not opposed to doing it in C#, Go, Java, or C++ _(in order of personal preference)._

**Comment by dlemstra** [comment]
When your version of ImageMagick links ghostscript (Linux) or if you install Ghostscript (Windows) the call to Ghostscript will be through the dll and it won't write any temp files. The only downside of using the library is that you can't do it in parallel. The Ghostscript library is not thread safe so there is some protection in place that prevents a concurrent call from using the library. That call will use the executable and create a temp file. So you can use the library but you have to make sure you only convert one file at the same time.

**Comment by njdoyle** [comment]
There are a number of cases that don't involve Ghostscript or delegates that force temporary files to be written. Specifically if a seekable blob is necessary; this is accomplished by writing the non-seekble blob to a file and reading that file to get a seekble blob. Some coders depend on this, is there a way to keep these blobs in memory only and off the filesystem? If not, consider this my feature request :)

**Comment by dlemstra** [comment]
If your blob is in memory then I don't understand why it would not be seekable? There are still some coders that do require a file on disk and we have a special flag for this. One of those is the exr reader where we need to call `ImfOpenInputFile(fileName)` to read an exr image.

**Comment by bubba-h57** [comment]
@dlemstra if I understand you correctly, I just need to rebuild ImageMagick and link it to GS myself? Anything, in particular, I should do to configure the build?

I am not doing anything that would be concurrent. Every job is siloed and the entire process is killed once it completes. However, the default build that I am using is definitely writing the tmp file before passing it off to GS.

**Comment by bubba-h57** [comment]
I am actually running this on AWS Lambda .. so while I necessarily roll my own PHP and Extensions, I have simply been linking to the underlying ImageMagick and GhostScript that they have installed by default.

**Comment by njdoyle** [comment]
My use case is passing image data over STDIN to convert. Instead of loading that data in to memory and creating a seekble blob from that, it writes the data to a temporary file and reads that file to create the seekable blob. So I guess it isn't exactly the same case but the effect of there being unnecessary temporary files is the same.

**Comment by dlemstra** [comment]
@bubba-h57 You will need to build ImageMagick from source with the `--with-gslib` option set to true.

@njdoyle I will need to check why and where that is happening.

**Comment by njdoyle** [comment]
`convert logo: BMP:- | convert -debug Resource BMP:- NULL:-` is a good example where this happens.

```
2017-06-27T17:34:55-04:00 0:00.070 0.000u 7.0.5 Resource convert[2429]: resource.c/AcquireUniqueFileResource/511/Resource
  ...
2017-06-27T17:34:55-04:00 0:00.070 0.010u 7.0.5 Resource convert[2429]: resource.c/AcquireUniqueFileResource/562/Resource
  /var/folders/v0/1tt_9zm13rl5mdn2wrhw3dnh00109s/T/magick-2429LkgRxZiaLiON
2017-06-27T17:34:55-04:00 0:00.100 0.010u 7.0.5 Resource convert[2429]: resource.c/AcquireMagickResource/319/Resource
  Width: 640B/0P/107.374MP
2017-06-27T17:34:55-04:00 0:00.100 0.010u 7.0.5 Resource convert[2429]: resource.c/AcquireMagickResource/319/Resource
  Height: 480B/0P/107.374MP
2017-06-27T17:34:55-04:00 0:00.100 0.010u 7.0.5 Resource convert[2429]: resource.c/AcquireMagickResource/319/Resource
  Area: 4915200B/4915200P/8.58993GP
2017-06-27T17:34:55-04:00 0:00.100 0.010u 7.0.5 Resource convert[2429]: resource.c/AcquireMagickResource/319/Resource
  Memory: 4915200B/4915200B/4GiB
2017-06-27T17:34:55-04:00 0:00.100 0.010u 7.0.5 Resource convert[2429]: resource.c/AcquireMagickResource/319/Resource
  Memory: 430080B/5345280B/4GiB
2017-06-27T17:34:55-04:00 0:00.110 0.020u 7.0.5 Resource convert[2429]: resource.c/RelinquishMagickResource/968/Resource
  Memory: 430080B/4915200B/4GiB
2017-06-27T17:34:55-04:00 0:00.110 0.020u 7.0.5 Resource convert[2429]: resource.c/RelinquishUniqueFileResource/1005/Resource
  /var/folders/v0/1tt_9zm13rl5mdn2wrhw3dnh00109s/T/magick-2429LkgRxZiaLiON
2017-06-27T17:34:55-04:00 0:00.110 0.020u 7.0.5 Resource convert[2429]: resource.c/RelinquishMagickResource/968/Resource
  Memory: 4915200B/0B/4GiB
```

**Comment by bubba-h57** [comment]
Thanks, this was helpful for me!
