### ISSUE TITLE
IsPolicyCacheInstantiated has mutex dead lock unless MagickCoreGenesis was called first

### ISSUE THREAD

**Issue by stomachfoot** [ImageMagick/ImageMagick#5301]
### ImageMagick version

6.9.12.50-2

### Operating system

Linux

### Operating system, version and so on

Red Hat Enterprise 8

### Description

We encountered a mutex deadlock in the ImageMagick library on RHEL8 (6.9.12.50-2).
It is easily reproducible with this test program.   If MagickCoreGenesis is invoked then it works fine, if it was not invoked then a deadlock happens.   This behavior changed in between version 6.9.10 and 6.9.12.  I'm wondering if the ConstantString method should not use AcquireQuantumMemory but instead use AcquireMagickMemory?
```
#include <Magick++.h>
using namespace MagickCore;
int main(int argc, char *argv[])
{
    // MagickCoreGenesis("/tmp", MagickFalse);
    SetMagickResourceLimit(ThreadResource, 2);

    return 0;
}
```

below is the stack trace

```
#0  0x00007f568663e7e0 in gomp_mutex_lock_slow () from /lib64/libgomp.so.1
#1  0x00007f5687e400a2 in IsPolicyCacheInstantiated () from /lib64/libMagickCore-6.Q16.so.7
#2  0x00007f5687e4030f in GetPolicyInfo () from /lib64/libMagickCore-6.Q16.so.7
#3  0x00007f5687e40922 in GetPolicyValue () from /lib64/libMagickCore-6.Q16.so.7
#4  0x00007f5687e1f00a in GetMaxMemoryRequest () from /lib64/libMagickCore-6.Q16.so.7
#5  0x00007f5687e1f1b5 in AcquireQuantumMemory () from /lib64/libMagickCore-6.Q16.so.7
#6  0x00007f5687ea1798 in ConstantString () from /lib64/libMagickCore-6.Q16.so.7
#7  0x00007f5687d7151d in GetConfigurePaths () from /lib64/libMagickCore-6.Q16.so.7
#8  0x00007f5687d717be in GetConfigureOptions () from /lib64/libMagickCore-6.Q16.so.7
#9  0x00007f5687e40120 in IsPolicyCacheInstantiated () from /lib64/libMagickCore-6.Q16.so.7
#10 0x00007f5687e4030f in GetPolicyInfo () from /lib64/libMagickCore-6.Q16.so.7
#11 0x00007f5687e40922 in GetPolicyValue () from /lib64/libMagickCore-6.Q16.so.7
#12 0x00007f5687e82e7c in SetMagickResourceLimit () from /lib64/libMagickCore-6.Q16.so.7
```

### Steps to Reproduce

This test program will hang with version 6.9.12.50-2.
```
#include <Magick++.h>
using namespace MagickCore;
int main(int argc, char *argv[])
{
    // MagickCoreGenesis("/tmp", MagickFalse);
    SetMagickResourceLimit(ThreadResource, 2);

    return 0;
}
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by stomachfoot** [comment]
Great!  Thanks for the quick fix!
