### ISSUE TITLE
Possible bug MSVG rendering SVG file

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#5307]
### ImageMagick version

7.1.0.41 and earlier

### Operating system

MacOS

### Operating system, version and so on

Monterey

### Description

Rendering from IM 6.9.12-56 Q16 works fine but not IM 7.1.0.41 and earlier.

This may be the issue related to the report at https://github.com/ImageMagick/ImageMagick/discussions/5304

SVG file:

[puzzle.svg.zip](https://github.com/ImageMagick/ImageMagick/files/9067624/puzzle.svg.zip)

IM 6.9.12.56 (correct):

`convert -density 96 MSVG:puzzle.svg puzzle6.png`

![puzzle6](https://user-images.githubusercontent.com/13458218/177879161-d44af6ce-7925-4b86-9b6f-06d076e4b262.png)

IM 7.1.0.41 (incorrect):

`magick -density 96 MSVG:puzzle.svg puzzle7.png`

![puzzle7](https://user-images.githubusercontent.com/13458218/177879231-418c9a36-6074-43e1-ab61-96bdb01c08fc.png)

### Steps to Reproduce

See above

### Images

See above

**Comment by fmw42** [comment]
Correct about auto-level. I could see a faint outline there in the IM 7 version.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by fmw42** [comment]
Thanks. This seems to be fixed in IM 7.1.0.43
