### ISSUE TITLE
Possible bug IM 7.1.0.43 threshold after rasterizing SVG

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#5311]
### ImageMagick version

7.1.0.43 Q16 HDRI

### Operating system

MacOS

### Operating system, version and so on

Monterey

### Description

After rasterizing an SVG and then thresholding, the result is transparent in IM 7, but opaque in IM 6.

SVG:

[puzzle.svg.zip](https://github.com/ImageMagick/ImageMagick/files/9079460/puzzle.svg.zip)

IM 6.9.12-58

`convert -density 96 MSVG:puzzle.svg -depth 8 +write t6.png -threshold 25% x6.png`

t6 before threshold:

![t6](https://user-images.githubusercontent.com/13458218/178154099-bd2aeaa8-53c2-4f3b-b4dc-f83cdfb71301.png)

x6 after threshold:

![x6](https://user-images.githubusercontent.com/13458218/178154108-0d340c57-d017-4682-a589-a2dff941ba08.png)

IM 7.1.0.43:

`magick -density 96 MSVG:puzzle.svg -depth 8 +write t7.png -threshold 25% x7.png`

t7 before threshold:

![t7](https://user-images.githubusercontent.com/13458218/178154131-655983c4-a6f9-4ea4-9d8b-bf145350b5dc.png)

x7 after threshold (white on transparent background):

![x7](https://user-images.githubusercontent.com/13458218/178154146-b5f781a3-f7d5-41a1-8d35-5890ee65789c.png)

### Steps to Reproduce

See above

### Images

See above

**Comment by urban-warrior** [comment]
Try, per the [porting guide](https://imagemagick.org/script/porting.php), this command:

```
magick -density 96 MSVG:puzzle.svg -depth 8 +write t7.png -channel RGB -threshold 25% x7.png
```

**Comment by fmw42** [comment]
Cristy,

Can you explain?  Why should thresholding a non-alpha image produce and alpha result so that I need to add -channel RGB.  

Thanks

Fred

**Comment by urban-warrior** [comment]
SVG requires an Alpha channel.  IMv6 enables the RGB channels by default, IMv7 defaults to RGBA.

**Comment by fmw42** [comment]
Curious but where in the porting does it say that SVG requires an alpha?

**Comment by snibgo** [comment]
fmw42's command was:
```
magick -density 96 MSVG:puzzle.svg -depth 8 +write t7.png -threshold 25% x7.png
```
t7.png, as shown, has an alpha channel but all pixels are entirely opaque. "-threshold 75%" should not make any pixels transparent.

In IM v7.1.0-32, "magick t7.png -threshold 75% t9.png" correctly doesn't make any pixels transparent.

**Comment by fmw42** [comment]
Thanks for confirming.

**Comment by fmw42** [comment]
So "magick" if the SVG has an opaque alpha as pointed out by snibgo, why should any threshold but 100% make the alpha channel transparent if one does not use -channel rgb?  How does -threshold deal with an opaque input alpha channel?

This does not result in a transparent image!

magick -size 200x200 xc:"rgba(255,255,255,1)" -threshold 25% x.png

So why should my command above when the rendered SVG at t7.png is opaque, but x7.png is transparent?

**Comment by urban-warrior** [comment]
Create a minimum command where IM first introduces what you think are incorrect results as evidenced by the pixel channel statistics from `identify -verbose` or `-verbose info:`  Try the same command with IMv6.  If you write to a file, use the MIFF image format unless you are displaying inside a browser (for that use PNG).  Post your commands and the unexpected differences in the statistics.  We need to reproduce the issue locally before we can comment further.  There are differences in thresholding between an RGB image vs. a grayscale vs. a default channel mask vs. a custom channel mask (e.g. `-channels RGBA) vs. a RGB image and one with an alpha channel.  We need to narrow the case down to an atomic issue to ensure we can account for the behavior-- either by understanding why its behaving a certain way or identifying it as a bug.

**Comment by fmw42** [comment]
Same command as above. Both t6.miff and t7.miff are nearly identical and both have a fully opaque alpha channel (see t6.txt and t7.txt). But the result of thresholding are completely different. Why?  Does -threshold in IM 7 do something odd with the alpha channel that IM 6 does not?

```
convert -density 96 MSVG:puzzle.svg -depth 8 +write t6.miff -threshold 25% x6.png

magick -density 96 MSVG:puzzle.svg -depth 8 +write t7.miff -threshold 25% x7.png


magick compare -metric rmse -channel rgba t6.miff t7.miff null:
66.695 (0.0010177)

magick compare -metric rmse -channel rgba x6.png x7.png null:
700.919 (0.0106953)

```

Here are the two identify -verbose text files for t6.miff and t7.miff, which are virtually identical.

[threshold_bug.zip](https://github.com/ImageMagick/ImageMagick/files/9080496/threshold_bug.zip)


**I could add -channel rgb before thresholding and get the same results. But I would like to understand if there is a bug or if this is just the way IM 7 does thresholding even with an opaque alpha channel.**

**Comment by urban-warrior** [comment]
The difference between t6 and t7 is expected because IMv7 is floating point pixels, whereas, IMv6 is unsigned short.

If we save to x6.miff and x7.miff and identify them you'll see a difference in the alpha channel.  IMv6 does not threshold the alpha channel because its default channel mask is RGB.  IMv7's default mask is RGBA so it thresholds the alpha channel.  For IMv7, as previously suggested, add `-channel RGB` to your command-line:

```
magick t7.miff -channel RGB -threshold 25% x7.miff
```

and  we practically get the same results between x7 and x6, the RMSE is 0.00926.

**Comment by fmw42** [comment]
***@***.***
    On Monday, July 11, 2022, 05:20:40 PM PDT, Cristy ***@***.***> wrote:  
 
 


The difference between t6 and t7 is expected because IMv7 is floating point pixels, whereas, IMv6 is unsigned short.

If we save to x6.miff and x7.miff and identify them you'll see a difference in the alpha channel. IMv6 does not threshold the alpha channel because its default channel mask is RGB. IMv7's default mask is RGBA so it thresholds the alpha channel. For IMv7, as previously suggested, add -channel RGB to your command-line:
magick t7.miff -channel RGB -threshold 25% x7.miff

and we practically get the same results between x7 and x6, the RMSE is 0.00926.

**Comment by fmw42** [comment]
Thanks for the clarification.
