### ISSUE TITLE
compile error in api_examples/wand.c

### ISSUE THREAD

**Issue by xiaoxiongli** [ImageMagick/ImageMagick#5314]
### ImageMagick version

7.1.0-27

### Operating system

Linux

### Operating system, version and so on

ubuntu-16.04

### Description

when I run below command on linux:
`gcc -I`pwd` -LMagickWand/.libs -LMagickCore/.libs -lMagickWand-7.Q16 -lMagickCore-7.Q16  api_examples/wand.c -o api_examples/wand`

compile error happend:

![image](https://user-images.githubusercontent.com/13975044/178264096-f4ebfff3-a5cb-4b1d-a48b-6c3e68ecfc49.png)

BTW:  I met 
 `warning "you should set MAGICKCORE_QUANTUM_DEPTH to sensible default set it to configure time default" `  during compile,  What does it means?  Does this warning cause the compile error? How Can  I fix it?

please help me...   thank you very much

### Steps to Reproduce

run below command in the root dir:
`gcc -I`pwd` -LMagickWand/.libs -LMagickCore/.libs -lMagickWand-7.Q16 -lMagickCore-7.Q16  api_examples/wand.c -o api_examples/wand`

**Comment by snibgo** [comment]
For documentation on building wand programs, see https://www.imagemagick.org/script/magick-wand.php

Your command doesn't have `pkg-config`, or anything else that defines `https://www.imagemagick.org/script/magick-wand.php`.
