### ISSUE TITLE
JzAzBz quantization looks very wrong

### ISSUE THREAD

**Issue by P-Star7** [ImageMagick/ImageMagick#5319]
### ImageMagick version

7.1.0-43

### Operating system

Windows

### Operating system, version and so on

Windows 10 x64

### Description

Quantizing using the JzAzBz colorspace gives a very erroneous look to the image that warps the colours and has much less colours than requested by the parameters. You can compare how the middle image (quantized using RGB) looks faithful to the top source image and has sixteen pleasing and appropriate colours, while the bottom image only has four colours that do not reproduce the image very accurately despite the requested amount of colours being sixteen. JzAzBz is a really cool colorspace as seen here:
http://gramaz.io/chromaticity/
so I'm really hyped to see how it looks in action quantizing colours. Thank you guys so much!

### Steps to Reproduce

Top image: Source image, nothing done to it
Middle image: sesamestreetexample.png -quantize rgb -colorspace rgb -colors 16 +dither sesamestreetrgb.png
Bottom image: sesamestreetexample.png -quantize jzazbz -colorspace jzazbz -colors 16 +dither sesamestreetjzazbz.png

### Images

![sesamestreetexample](https://user-images.githubusercontent.com/26371167/178520452-ac68beb7-19ec-4182-a3de-1feb7ef7323d.png)
![sesamestreetrgb](https://user-images.githubusercontent.com/26371167/178520563-a1f62b21-25a1-4693-a3fc-72767722d9bf.png)
![sesamestreetjzazbz](https://user-images.githubusercontent.com/26371167/178520623-90956d6b-831e-4b15-a954-d0abbf99ea66.png)

**Comment by urban-warrior** [comment]
Let's do a sanity check, a round-trip from sRGB to JzAzBz back to sRGB:

```
$ magick sesame.png -colorspace  jzazbz -colorspace sRGB sesame.miff
$ magick compare -metric RMSE sesame.miff sesame.png null:
0 (0)
```

The image survived the round trip.

Next, let's review the color transformations for JzAzBz.  Its detailed here: http://im.snibgo.com/jzazbz.htm.  It looks like its correct.

Now let's try color reduction in the JzAzBz colorspace:

```
magick sesame.png -colorspace jzazbz -colors 256 -colorspace sRGB sesameQ.png
```

The results look great.

Where did that Alpha channel come from?  Its part of the original `sesame.png` image.  It has an opaque alpha channel.  Let's remove it:

```
 magick sesame.png -alpha off -colorspace jzazbz -colors 256 -colorspace sRGB sesameQ.png
````

**Comment by P-Star7** [comment]
Ah, look at this. It's so much better. Thank you for correcting my syntax.
![sesamestreetjzazbz2](https://user-images.githubusercontent.com/26371167/178640944-dc7b40b1-715c-4516-913e-553501429293.png)
