### ISSUE TITLE
+clip should remove mask from WritePixelMask and not ReadPixelMask ?

### ISSUE THREAD

**Issue by ptitpix** [ImageMagick/ImageMagick#532]
Hello,

We had some issues with clipping path and IM7. After digging, we finally found that the following works : 
`convert source.jpg -alpha transparent -clip -alpha opaque +mask -thumbnail "600x600>" result.png`
but this one doesn't if thumbnail does some "sampling" :
`convert source.jpg -alpha transparent -clip -alpha opaque +clip -thumbnail "600x600>" result.png`

Reviewing sources tells me : 
- "-clip" deals with WritePixelMask ( MagickCore/image.c Line:758 )
- "+clip" deals with ReadPixelMask. ( MagickWand/operation.c Line:1968 )

So I think one of these two must be wrong but I'm not sure which one. I would change "+clip" to deal with WritePixelMask like the source comment suggests it but I don't know the consequences.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
