### ISSUE TITLE
Spurious extra channel

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#5325]
### ImageMagick version

v7.1.0-42.

### Operating system

Windows

### Operating system, version and so on

Windows 8.1

### Description

Some operations create an extra junk channel, "channel 3".

This occurs when converting to a colorspace such as Lab, JzAzBz and HSL, and only when the input has an alpha channel.

### Steps to Reproduce

For example:
```
magick xc:White -alpha Opaque -colorspace HSL -verbose info:
```
The text output includes:
```
    Channel 0:
      min: 0  (0)
      max: 0 (0)
      mean: 0 (0)
      median: 0 (0)
      standard deviation: 0 (0)
      kurtosis: -3
      skewness: 0
      entropy: 0
    Channel 1:
      min: 0  (0)
      max: 0 (0)
      mean: 0 (0)
      median: 0 (0)
      standard deviation: 0 (0)
      kurtosis: -3
      skewness: 0
      entropy: 0
    Channel 2:
      min: 65535  (1)
      max: 65535 (1)
      mean: 65535 (1)
      median: 65535 (1)
      standard deviation: 0 (0)
      kurtosis: -3
      skewness: 0
      entropy: 0
    Channel 3:
      min: inf  (2.7431e+303)
      max: -inf (-2.7431e+303)
      mean: 0 (0)
      median: 0 (0)
      standard deviation: -0 (-0)
      kurtosis: -3
      skewness: 0
      entropy: 0
    Alpha:
      min: 65535  (1)
      max: 65535 (1)
      mean: 65535 (1)
      median: 65535 (1)
```
The bug is that "Channel 3" should not be present. The result should have channels 0, 1 and 2 for H,S,L, and alpha. But "channel 3" is bad. 

The problem occurs only when I add an alpha channel with "alpha Opaque". It does not occur when I add alpha with "-alpha Transparent" or "-alpha set".

### Images

None.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
