### ISSUE TITLE
Parameter -auto-orient does not work as expected, depending on metadata 

### ISSUE THREAD

**Issue by haukemac** [ImageMagick/ImageMagick#5326]
### ImageMagick version

7.1.0-43

### Operating system

MacOS

### Operating system, version and so on

macOS, Centos7

### Description

When converting an image with `-auto-orient` then the orientation is wrong, e.g. not in portrait mode.

To me it looks like it is related to the meta-data information, eg:
`Orientation : Rotate 270 CW` or `Orientation : Rotate 90 CW`
Images with this meta-data are correct: `Orientation : Horizontal (normal)`
But other meta-data may play into this, as I am no specialist on this topic.

This occurs in my tests with DNG, CR2 and NEF images. But it may occur with other image types too.
Example images attached.

This was ok for years up (and including) ImageMagick `7.1.0-29`. (last release we use)

### Steps to Reproduce

convert -auto-orient input.file output.file

### Images

[test.nef.zip](https://github.com/ImageMagick/ImageMagick/files/9111764/test.nef.zip)
[test.cr2.zip](https://github.com/ImageMagick/ImageMagick/files/9111766/test.cr2.zip)
[test.dng.zip](https://github.com/ImageMagick/ImageMagick/files/9111770/test.dng.zip)

**Comment by snibgo** [comment]
As you use IM v7, I suggest using "magick", not "convert" (and not "magick convert").

I confirm there is a problem, using your raw NEF file named as "test_1.nef". If we don't ask to auto-orient the image...
```
magick test_1.nef info:

test_1.nef NEF 2613x3900 3904x2616+0+0 16-bit sRGB 9.1279MiB 0.000u 0:00.000
```
... the image is auto-oriented (note the reslt is "portrait" format.

On the other hand, if we ask for "-auto-orient", the image is further rotated:
```
magick test_1.nef -auto-orient info:

test_1.nef NEF 3900x2613 1753x5827+0+0 16-bit sRGB 9.1279MiB 0.000u 0:00.000
```
Tested with IM 7.1.0-42 on Windows 8.1.

**Comment by dlemstra** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by haukemac** [comment]
@dlemstra 

hello, I just tested it with 7.1.0-44 (macOS home-brew) and unfortunately the orientation is still wrong. The converted images are still not in portrait mode, they are now turned to the left (beforehand they were turned to the right instead)

<img width="1057" alt="Bildschirmfoto 2022-07-26 um 09 06 17" src="https://user-images.githubusercontent.com/47486748/180944882-2c2e1ee9-26b4-4398-8f44-1ff9347485e4.png">

**Comment by axelrose** [comment]
Can we reopen the issue or is it necessary to create a new one, please?

**Comment by dlemstra** [comment]
There is no need to open a new issue. But without any files that demonstrate the issue we cannot investigate or re-open this issue.

**Comment by haukemac** [comment]
In my first comment I provided 3 different images. When I convert them to a jpeg, e.g. `convert -auto-orient test.nef test.jpg` then the output file has the wrong orientation.

**Comment by dlemstra** [comment]
I really need more information. Why is it wrong? All my information points to the current version being correct. Those three images have either `Rotate 90 CW` or `Rotate 270 CW` and that should result in `RightTop` and `LeftBottom` orientation?

**Comment by fmw42** [comment]
Dirk,

I checked test.cr2 with exiftool, which says:

 `125 CameraOrientation               : 2
`

Flag 2 is according to https://jdhao.github.io/2019/07/31/image_rotation_exif_info/ is horizontal mirror. But IM is saying 

 `Orientation: LeftBottom`
 
which does not seem to take into account the mirror and thus seems wrong according to the reference.

**Comment by haukemac** [comment]
Don’t know if it helps, but as mentioned, the output of ImageMagick was correct up to version `7.1.0-29`, which is the version we currently use. So some change after that version must have broken it.

**Comment by dlemstra** [comment]
We fixed other bugs so it might be something that was always wrong. All the information that I currently have says that this is the correct result.

**Comment by haukemac** [comment]
That is of course possible. But the `test.dng` photo (the ork helmet) was shot by me with my iPhone in portrait mode, so why should it be in landscape after conversion?

**Comment by totoestcontent** [comment]
I see the same thing.
I wonder if the problem would not be related to the absence of initialization of the parameter of the "libraw" library "**libraw_output_params_t.user_flip**".
From what I understand from the documentation, it must be at 0 in order not to rotate.
But by default it is **-1** and that seems to mean that the library will find the information on its own.
`int user_flip;
dcraw keys: -t
[0-7] Flip image (0=none, 3=180, 5=90CCW, 6=90CW). Default -1, which means taking the corresponding value from RAW.`
Maybe we should initialize this parameter to 0 ?

Sorry if my thinking is wrong...

**Comment by haukemac** [comment]
Hello, is there any update please? thank you in advance

**Comment by dlemstra** [comment]
As I said before I see no reason to change our implementation.

**Comment by totoestcontent** [comment]
@dlemstra Here is more information, with this images IMG_9591.CR2.
[IMG_9591.zip](https://github.com/ImageMagick/ImageMagick/files/9432098/IMG_9591.zip)

With Win/Imagmagick **7.0.11-3**
	Version: ImageMagick 7.0.11-3 Q16 x64 2021-03-06 https://imagemagick.org
	Copyright: (C) 1999-2021 ImageMagick Studio LLC
	License: https://imagemagick.org/script/license.php
	Visual C++: 192829337
	Features: Cipher DPC OpenCL
	Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zip zlib

	convert IMG_9591.CR2 toto_without_auto_orient.jpg 				
	convert IMG_9591.CR2 -auto-orient toto_with_auto_orient.jpg 	
	identify toto*.jpg =>
		toto_with_auto_orient.jpg 		JPEG **3176x4770** 3176x4770+0+0 8-bit sRGB 4.06379MiB 0.000u 0:00.000
		toto_without_auto_orient.jpg 		JPEG **3176x4770** 3176x4770+0+0 8-bit sRGB 4.06379MiB 0.000u 0:00.000
		
	=> auto-orient or not, give same result
		
With Win/**7.1.0-46**
	Version: ImageMagick 7.1.0-46 Q16 x64 2b90eb9:20220817 https://imagemagick.org
	Copyright: (C) 1999 ImageMagick Studio LLC
	License: https://imagemagick.org/script/license.php
	Features: Cipher DPC OpenCL
	Delegates (built-in): bzlib cairo freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
	Compiler: Visual Studio 2022 (193231333)
	
	convert IMG_9591.CR2 toto_without_auto_orient.jpg 				
	convert IMG_9591.CR2 -auto-orient toto_with_auto_orient.jpg 	
	identify toto*.jpg =>
		toto_with_auto_orient.jpg 		JPEG **4770**x3176 4770x3176+0+0 8-bit sRGB 4.0423MiB 0.000u 0:00.000
		toto_without_auto_orient.jpg 		JPEG **3176**x4770 3176x4770+0+0 8-bit sRGB 4.06363MiB 0.000u 0:00.000
		
	=> auto-orient or not, give different result.
		
With DCRAW
	We use dcraw to export an image without flip 
	dcraw -t 0 -T -O toto_filp_none.tiff IMG_9591.CR2
	We use dcraw to export the image with the orientation setting of the camera
	dcraw -T -O toto_auto_orient_from_camera.tiff IMG_9591.CR2
	identify toto*.tiff =>
		toto_auto_orient_from_camera.tiff 		TIFF **3177**x4770 3177x4770+0+0 8-bit sRGB 43.3585MiB 0.016u 0:00.003
		toto_filp_none.tiff 					TIFF **4770**x3177 4770x3177+0+0 8-bit sRGB 43.3585MiB 0.000u 0:00.001
		
So :
	- with auto-orientation, we should have an image of size: 3177x4770
	- without: 4770x3177
	
Where is problem:
The problem is not in detecting the orientation or in the transformation you are doing.
The problem is that libraw does the default orientation itself.
And you work from an image that has already been rotated.

Solution:
To correct this, I think it is enough to add in the "SetLibRawParams" method the following line:
`libraw_output_params_t.user_flip=0;`.
The other solution would be to let libraw do the rotation if needed and not do it again.

Expected:
- with auto-orient:
![toto_auto_orient_from_camera](https://user-images.githubusercontent.com/55127910/186879908-adb1a59b-3e9f-4654-b003-55ee8c42592e.jpg)
- without auto-orient:
![toto_no_auto_orient](https://user-images.githubusercontent.com/55127910/186880009-ecc9a63b-65b9-4d6b-8628-acb03c92961b.jpg)

**Comment by totoestcontent** [comment]
@dlemstra With this new information. Should I create a new ticket or do you prefer to reopen this one ?

**Comment by dlemstra** [comment]
I did not have time to take a look at this. Thanks for your explanation this is the TLDR:

> The problem is that libraw does the default orientation itself.

Setting `raw_info->params.user_flip` to `0` did solve the issue. The default is apparently `-1` and that results in libraw rotating the image.
