### ISSUE TITLE
Conversion of png file to tif format is failing

### ISSUE THREAD

**Issue by RAmbika** [ImageMagick/ImageMagick#5329]
### ImageMagick version

7.1.0-7

### Operating system

Windows

### Operating system, version and so on

Windows 7, Windows 2019 server

### Description

ImageMagick library is unable to convert a particular png file to Tif format. 
Below output is shown when we ran convert.exe command:
convert.exe: Expected 4 bytes; found 3 bytes `C:\Temp\image001.png' @ warning/png.c/MagickPNGWarningHandler/1746.
convert.exe: Read Exception `C:\Temp\image001.png' @ error/png.c/MagickPNGErrorHandler/1713.
convert.exe: NoImagesDefined `output.tif' @ error/convert.c/ConvertImageCommand/3322.

### Steps to Reproduce

Run the convert.exe command as below with the attached png file:
<ImageMagickDir>\convert.exe <SourcePath>\image001.png Result.tif

### Images

![image001](https://user-images.githubusercontent.com/66011737/179211104-8b2c5d4d-c05a-41da-8759-cd4c6ea3b4ee.png)

This this image is public available at https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ciresa.it%2F&amp;data=05%7C01%7C%7C6c0ce64cf21d4db4830108da6578f2a4%7Cbcd8ba5f75e24d6c8aa5fff6c8baa1ff%7C0%7C0%7C637933867377981215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=ElfOG6FGYfSGKz8zqlmpYs%2Bf3Wc9mIZU5DoGucQ1O4E%3D&amp;reserved=0

**Comment by dlemstra** [comment]
That PNG file is invalid and that is why ImageMagick will fail to read it.

**Comment by RAmbika** [comment]
Hi,
Thanks for your reply. Our customer wants to know more details about the png file. What is the abnormal information in this file and it looks this file is not invalid for our customers.

**Comment by dlemstra** [comment]
This is the error message from pngcheck:

```
dirk@DIRK:/mnt/i/issues/im7/5329$ pngcheck image001.png
image001.png  EOF while reading CRC value
ERROR: image001.png
```
