### ISSUE TITLE
DIY dither no longer works as documented

### ISSUE THREAD

**Issue by yoya** [ImageMagick/ImageMagick#5332]
### ImageMagick version

7.1.0-43

### Operating system

MacOS

### Operating system, version and so on

macOS Monterey 12.4

### Description

The documented DIY dither command has not worked since ImageMagick-7.0.7-29 until latest version.

- https://www.imagemagick.org/Usage/quantize/#diy_hlines

```
  magick gradient.png  dpat_hlines.gif  \
          -virtual-pixel tile  -fx 'u[floor((n-1)*u)+1]' \
          dgrad_dpat_hlines.gif
```

Please refer to "Steps to Reproduce" for the behavior of each version.

### Steps to Reproduce

# ImageMagick-7.1.0-43

```
% magick -size 20x640  gradient: -rotate 90  gradient.png
% wget https://www.imagemagick.org/Usage/images/dpat_hlines.gif
%
% ~/ImageMagick/7.1.0-43/bin/magick -version
Version: ImageMagick 7.1.0-43 Q16-HDRI x86_64 20237 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI
Delegates (built-in): bzlib freetype gvc jng jp2 jpeg lcms lqr lzma openexr png raw tiff webp xml zip zlib
Compiler: gcc (4.2)
%
% ~/ImageMagick/7.1.0-43/bin/magick gradient.png  dpat_hlines.gif  \
          -virtual-pixel tile  -fx 'u[floor((n-1)*u)+1]' \
          dgrad_dpat_hlines.gif
magick: ImgNum 10 bad for ImgListLen 10 @ error/fx.c/ChkImgNum/2987.
```

# Previous Versions

## Success (7.0.1-0 ... 7.0.7-28)

```
% ~/ImageMagick/7.0.7-28/bin/magick gradient.png  dpat_hlines.gif  \
          -virtual-pixel tile  -fx 'u[floor((n-1)*u)+1]' \
          dgrad_dpat_hlines.gif
```

## Failure 1 (7.0.7-29 ... 7.1.0-19) no such image

```
%  ~/ImageMagick/7.0.7-29/bin/magick gradient.png  dpat_hlines.gif  \
          -virtual-pixel tile  -fx 'u[floor((n-1)*u)+1]' \
          dgrad_dpat_hlines.gif
magick: no such image `u[floor((n-1.0*1)*u)+1]' @ error/fx.c/FxGetSymbol/1400.
```

## Failure 2 (7.1.0-20) Abort trap: 6 (macOS)

```
% ~/ImageMagick/7.1.0-20/bin/magick gradient.png  dpat_hlines.gif  \
          -virtual-pixel tile  -fx 'u[floor((n-1)*u)+1]' \
          dgrad_dpat_hlines.gif
Abort trap: 6
```

## Failure 3 (7.1.0-21 ... 7.1.0-43) ImgNum 10 bad for ImgListLen 10

```
% ~/ImageMagick/7.1.0-21/bin/magick gradient.png  dpat_hlines.gif  \
          -virtual-pixel tile  -fx 'u[floor((n-1)*u)+1]' \
          dgrad_dpat_hlines.gif
magick: ImgNum 10 bad for ImgListLen 10 @ error/fx.c/ChkImgNum/2929.
```

### Images

|   |  sample & expected output images. |
|---|---|
| gradient.png | ![gradient](https://user-images.githubusercontent.com/26040/179400680-2b6d779e-16b1-40cf-8e95-a39f9f66f803.png) |
| dpat_hlines.gif | ![dpat_hlines](https://user-images.githubusercontent.com/26040/179400689-0177c83b-5395-4b7b-93b0-23cebac9b408.gif) |
|  dgrad_dpat_hlines.gif | ![dgrad_dpat_hlines](https://user-images.githubusercontent.com/26040/179400562-15733b80-d551-48c0-9838-ae1181f34083.gif) |

**Comment by snibgo** [comment]
Thanks for the problem report. I think the problem is in the documentation at https://www.imagemagick.org/Usage/quantize/#diy_hlines, not in current "-fx".

Windows syntax, with IM v7.1.0-42:
```
%IMG7%magick gradient.png  dpat_hlines.gif  -virtual-pixel tile  -fx "u[floor((n-1)*u)+1]" out.gif

magick: ImgNum 10 bad for ImgListLen 10 @ error/fx.c/ChkImgNum/2987.
```
The error message is correct. This is why.

gradient.png has one image. dpat_hlines.gif has 9 images. So `u[0]` to `u[9]` should be valid, and `u[10]` should not be valid.

`u` refers to pixel values in the first image, gradient.png, and has values from 0 to 1.

`n` is the number of images in the list, which here is 10.

So the expression `u[floor((n-1)*u)+1]` is `u[floor(9*u)+1]`, which has values from `u[floor(9*0)+1]` to `u[floor(9*1)+1]`, from `u[floor(0)+1]` to `u[floor(9)+1]`, from `u[0+1]` to `u[9+1]`, from `u[1]` to `u[10]`.

So we get `u[10]`, which is not valid.

If we use `u[floor((n-2)*u)+1]` instead, there is no error.

**Comment by yoya** [comment]
Thank you very much!

**Comment by urban-warrior** [comment]
Thanks for bringing this issue to our attention.  We corrected the web page to reflect the proper Fx expression:

```
magick gradient.png dpat_hlines.gif -virtual-pixel tile -fx 'u[(floor((n-1)*u)+1) % n]' dgrad_dpat_hlines.gif
```
