### ISSUE TITLE
Does "gitversion" exist as an executable command for a UNIX shell interpreter?

### ISSUE THREAD

**Issue by ballapete** [ImageMagick/ImageMagick#534]
Hello!

https://github.com/ImageMagick/ImageMagick/search?utf8=%E2%9C%93&q=gitversion&type= mentions a command "gitversion" to be a executed by sh. On Mac OS X this command does *not* exist. During the configure phase we get here an error:

sh: gitversion: command not found

Is it possible that the change set https://github.com/ImageMagick/ImageMagick/commit/6b58c59d17ee69125324e55374196229b01f3f13 meant to implement the command "git version" as substitute to "svnversion"? That command does exist on Macs.

I don't know which implications the above mentioned error has, but could you at least for Macs choose a command that exists here and provides an output for configure that delivers the information configure needs? Or is "gitversion" just a typo?
--

Pete

**Comment by mikayla-grace** [comment]
Here is gitversion:

```
git_rev ()
{
    d=`date +%Y%m%d`
    c=`git rev-list --full-history --all --abbrev-commit | wc -l | sed -e 's/^ *//'`
    h=`git rev-list --full-history --all --abbrev-commit | head -1`
    echo ${c}:${h}:${d}
}
git_rev

```

**Comment by ballapete** [comment]
Am 04.07.2017 um 00:43 schrieb mikayla-grace:

> Here is gitversion:
> 
> ```
> git_rev ()
> {
>    d=`date +%Y%m%d`
>    c=`git rev-list --full-history --all --abbrev-commit | wc -l | sed -e 's/^ *//'`
>    h=`git rev-list --full-history --all --abbrev-commit | head -1`
>    echo ${c}:${h}:${d}
> }
> git_rev
> 
> ```

Well, me, I can't see the name "gitversion" here. Assuming this object does exist, then the question is why it can't be find and used on Mac OS X – and maybe macOS too.

ImageMagick 6.9.8 was recently installed on my Mac. Sh complained about a dozen times that it could not find *gitversion*.

--
Greetings

  Pete

Hard Disk, n.:
	A device that allows users to delete vast quantities of data with simple mnemonic commands.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
