### ISSUE TITLE
PNG image flattening results in canvas resize

### ISSUE THREAD

**Issue by Tristan971** [ImageMagick/ImageMagick#5357]
### ImageMagick version

7.1.0-43

### Operating system

Linux

### Operating system, version and so on

Fedora 36, kernel 5.10.102.1-microsoft-standard-WSL2

### Description

Happens on 6.9.12-52 and Ubuntu 20.04 too (spotted in a live prod environment, merely reproduced locally with most uptodate-est version just in case before raising this issue).

When using -flatten, the resulting image ends up with an odd blank expansion of the original canvas.

It's definitely specific to this image, and I'm not really familiar enough with the PNG spec to be sure that it's a bug...

Alas it's also not feasible to contact the user that authored the image file to ask them how exactly they got there...

### Steps to Reproduce

Minimal:
```
/path/to/magick convert -flatten original.png flattened.png
```

Full command:
```
convert -strip -flatten -interlace plane -compress jpeg -quality 90.0 original.png flattened.jpg
```

### Images

<details>
<summary>original.png</summary>

![original.png](https://user-images.githubusercontent.com/875533/180585920-db5bc33a-88bf-43e9-831a-85ec895c8600.png)

</details>

<details>
<summary>flattened.png</summary>

![flattened.png](https://user-images.githubusercontent.com/875533/180585932-d0ae857b-1e11-4eae-abbd-39cd8c32e798.png)

</details>

**Comment by takaradariku** [comment]
Running `identify` on the original image yields an interessting find:
```
Page geometry: 1920x1080+197+0
Background color: white
Properties:
    png:caNv: width=1920, height=1080, x_offset=197, y_offset=0
```

which is consistent with the output of the flattened image.

From some Googling, looks like caNv is a nonstandard chunk from ImageMagick, so the original image was likely processed through IM at some point...

**Comment by snibgo** [comment]
You should rearrange your command to be in the logical order: read the image, then do any operations on the image, then finally write the image.

```
f:\web\im>%IMG7%magick 1805.png info:
1805.png PNG 763x1080 1920x1080+197+0 8-bit sRGB 1.0979MiB 0.000u 0:00.000
```
Your input image is 763x1080 pixels on a larger canvas, 1920x1080. "Flatten" doesn't change the canvas size. If the canvas was large than the image, the image will become larger, the same as the canvas size.

```
f:\web\im>%IMG7%magick 1805.png -flatten x.png

f:\web\im>%IMG7%magick x.png info:
x.png PNG 1920x1080 1920x1080+0+0 8-bit sRGB 1.28183MiB 0.000u 0:00.000
```
This is not a bug. You might want to "`+repage`" after reading the input image. That will discard the canvas data.

**Comment by Tristan971** [comment]
That does fix the "issue" indeed, thanks for the answer. Will close the issue then.
