### ISSUE TITLE
Convert multiple images to .webp does not work

### ISSUE THREAD

**Issue by dpthurst** [ImageMagick/ImageMagick#5362]
### ImageMagick version

7.1.0-44

### Operating system

Linux

### Operating system, version and so on

Debian GNU/Linux 11 bullseye, kernel 5.10.0-14

### Description

Conversion to .webp works fine for individual files, but fails on multiple images.

### Steps to Reproduce

1. Create a 3-page pdf file test.pdf
2. Run 'magick test.pdf t.webp'
See attached for a complete log for various things that work and don't.
[imagemagick-bug.txt](https://github.com/ImageMagick/ImageMagick/files/9174378/imagemagick-bug.txt)

**Comment by urban-warrior** [comment]
Some ImageMagick formats leverage delegate libraries or programs to assist with decode/encoding of a subset of image formats.  PDF requires `libgs` library or the `gs` utility.  Webp requires the `libwebp` library or the `cwebp` utility.

**Comment by dpthurst** [comment]
I had the `cwebp` utility installed, and that delegation worked for single files (as the logs showed). I recompiled with the `libwebp-dev` package installed (to use the library rather than the utility) and then the multi-file conversion worked as expected. But I think it should work either way. (I was also using the external `gs` utility rather than `libgs` library, but that wasn't the issue, as the tests converting from the sequence of PNG files in the log show.)
