### ISSUE TITLE
Problems in -connected-components

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#5368]
### ImageMagick version

7.1.0-42

### Operating system

Windows

### Operating system, version and so on

Prebuilt IM v7.1.0-42 on Windows 8.1.

### Description

`-connected-components` has two problems. Perhaps they are caused by a single bug.

Input image, shown below, spm_hue_4a.png:
```
%IMG7%magick spm_hue_4a.png -unique-colors txt:

# ImageMagick pixel enumeration: 4,1,0,65535,srgb
0,0: (52171,31611,514)  #CBCB7B7B0202  srgb(203,123,2)
1,0: (2570,54998,20560)  #0A0AD6D65050  srgb(10,214,80)
2,0: (0,53713,41634)  #0000D1D1A2A2  srgb(0,209,162)
3,0: (0,50886,53970)  #0000C6C6D2D2  srgb(0,198,210)
```
The image has four colours, with many more components. I want to reduce the image to two connected-components.

The second largest area has 5433 pixels, so limiting the area to 5433 should work.
```
%IMG7%magick spm_hue_4a.png ^
  -define connected-components:verbose=true ^
  -define connected-components:mean-color=true ^
  -define connected-components:area-threshold=5433 ^
  -connected-components 4 ^
  x2.png

Objects (id: bounding-box centroid area mean-color):
  3: 297x163+0+0 152.0,81.3 42763 srgb(0,209,162)
  15: 179x47+40+57 121.0,81.3 5433 srgb(203,123,2)
```
That looks fine, there are only 2 components, and the smallest is 5433. But the sum of the areas is 42763+5433=48196, which is less that the number of pixels in the image, which is 48411. And when we find the connected components of x2.png ...
```
%IMG7%magick x2.png ^
  -define connected-components:verbose=true ^
  -connected-components 4 ^
  x2a.png

Objects (id: bounding-box centroid area mean-color):
  1: 297x163+0+0 151.9,81.3 42819 srgb(0,209,162)
  2: 179x47+40+57 121.0,81.3 5433 srgb(203,123,2)
  0: 20x10+0+0 9.4,3.5 159 srgb(0,198,210)
```
...there are 3 components. One has fewer than 5433 pixels, and that component should not be present. That is the first problem.

IM now has `connected-components:keep-top=2`, so that should do what I want. But it doesn't.
```
%IMG7%magick spm_hue_4a.png ^
  -define connected-components:keep-top=2 ^
  -define connected-components:verbose=true ^
  -define connected-components:mean-color=true ^
  -connected-components 4 ^
  xkeep.png

Objects (id: bounding-box centroid area mean-color):
  3: 297x159+0+0 149.3,68.4 36031 srgb(0,209,162)
  26: 297x33+0+130 166.3,150.0 6732 srgb(0,198,210)
  15: 179x47+40+57 121.0,81.3 5433 srgb(203,123,2)
```
It claims to have kept three components. (It sems to always say it keeps one more that I request.) But has it really?
```
%IMG7%magick xkeep.png ^
  -define connected-components:verbose=true ^
  -define connected-components:mean-color=true ^
  -connected-components 4 ^
  xkeepa.png

Objects (id: bounding-box centroid area mean-color):
  1: 297x159+0+0 149.3,68.4 36087 srgb(0,209,162)
  3: 297x33+0+130 166.3,150.0 6732 srgb(0,198,210)
  2: 179x47+40+57 121.0,81.3 5433 srgb(203,123,2)
  0: 20x10+0+0 9.4,3.5 159 srgb(0,198,210)
```
No. It has kept four components. So that is the second problem.

As always, the bug may be in my brain. 

### Steps to Reproduce

See above.

### Images

spm_hue_4a.png is:
![spm_hue_4a](https://user-images.githubusercontent.com/33812368/180667511-51f535cc-e1b8-40d5-b23f-02aa27552235.png)

**Comment by fmw42** [comment]
snibgo wrote:

> %IMG7%magick spm_hue_4a.png ^
>   -define connected-components:verbose=true ^
>   -define connected-components:mean-color=true ^
>   -define connected-components:area-threshold=5433 ^
>   -connected-components 4 ^
>   x2.png
> 
> Objects (id: bounding-box centroid area mean-color):
>   3: 297x163+0+0 152.0,81.3 42763 srgb(0,209,162)
>   15: 179x47+40+57 121.0,81.3 5433 srgb(203,123,2)
> That looks fine, there are only 2 components, and the smallest is 5433. But the sum of the areas is 42763+5433=48196, which is less that the number of pixels in the image, which is 48411. And when we find the connected components of x2.png ...
> 

If you look carefully at the top left corner of x2.png, you will see a small slightly blue region that I suspect is the missing pixels. So in fact the image contains 3 colors: the two that are listed and one more for the top left region of color srgb(0,198,210)

**So there is a bug with respect to this.**

So this is what you show in:

> %IMG7%magick xkeep.png ^
>   -define connected-components:verbose=true ^
>   -define connected-components:mean-color=true ^
>   -connected-components 4 ^
>   xkeepa.png
> 
> Objects (id: bounding-box centroid area mean-color):
>   1: 297x159+0+0 149.3,68.4 36087 srgb(0,209,162)
>   3: 297x33+0+130 166.3,150.0 6732 srgb(0,198,210)
>   2: 179x47+40+57 121.0,81.3 5433 srgb(203,123,2)
>   0: 20x10+0+0 9.4,3.5 159 srgb(0,198,210)

where region #3 is the blue area in the top left corner

**Comment by snibgo** [comment]
The problem seems to occur when we have a small component at top-left. For example (Windows scripts):
```
%IMG7%magick ^
  -size 300x300 xc:#0f0 ^
  -fill Black ^
  -draw "rectangle 0,0,10,10" ^
  -draw "rectangle 290,290,299,299" ^
  x3.png
```
x3.png is:
![x3](https://user-images.githubusercontent.com/33812368/181161230-2890abf6-93a7-423c-865a-109ac6b400f5.png)

There are 90000 pixels, and 3 components:
```
%IMG7%magick ^
  x3.png ^
  -define connected-components:verbose=true ^
  -connected-components 4 ^
  NULL:

Objects (id: bounding-box centroid area mean-color):
  1: 300x300+0+0 149.5,149.5 89779 srgb(0,255,0)
  0: 11x11+0+0 5.0,5.0 121 srgb(0,0,0)
  2: 10x10+290+290 294.5,294.5 100 srgb(0,0,0)
```
We try to remove areas smaller than 6000 pixels:
```
%IMG7%magick ^
  x3.png ^
  -define connected-components:verbose=true ^
  -define connected-components:area-threshold=6000 ^
  -connected-components 4 ^
  -auto-level ^
  x4.png

Objects (id: bounding-box centroid area mean-color):
  1: 300x300+0+0 149.7,149.7 89879 srgb(0,255,0)
```
It claims only one component was found, which would be correct, but the count is 121 pixels short. This is the size of the top-left rectangle.

x4.png is mostly white, with 11x11 black in the top-left corner:
![x4](https://user-images.githubusercontent.com/33812368/181161251-01d64c52-9211-493f-a0e6-2fac48756758.png)

We try fmw42's suggestion of repeating the operation:
```
%IMG7%magick ^
  x4.png ^
  -define connected-components:verbose=true ^
  -define connected-components:area-threshold=6000 ^
  -connected-components 4 ^
  -auto-level ^
  x5.png

Objects (id: bounding-box centroid area mean-color):
  1: 300x300+0+0 149.7,149.7 89879 gray(255)
```
The count is still short 121 pixels, and x5 is the same as x4:

x5.png is:
![x5](https://user-images.githubusercontent.com/33812368/181161271-837a5ed8-f7eb-49e3-9b2d-12d62daf423b.png)

I conclude there is a bug, and I haven't found a workaround.

**Comment by fmw42** [comment]
Possibly an issue of the top left corner being the background (first region found) and not allowed to remove the background in the actual output image. So you have it removed in the list, but not removed in the image,

**Comment by snibgo** [comment]
In my x3.png above, the bottom-right black square was correctly removed, but the top-left square was not removed.

A workaround for this image (not a general workaround) is "-virtual-pixel Tile" or "None"):
```
%IMG7%magick ^
  -size 300x300 xc:#0f0 ^
  -fill Black ^
  -draw "rectangle 0,0,10,10" ^
  -draw "rectangle 290,290,299,299" ^
  x3.png

%IMG7%magick ^
  x3.png ^
  -define connected-components:verbose=true ^
  -define connected-components:area-threshold=6000 ^
  -virtual-pixel Tile ^
  -connected-components 4 ^
  -auto-level ^
  x4.png

  1: 300x300+0+0 149.5,149.5 90000 srgb(0,255,0)
```
The count is correct, and x4.png is entirely black. Both squares have now been merged.

I believe (but haven't tested) the problem is in the "`connect4[n][0]`" array. Elements are 0 or -1, so in this code ...
```
            /*
              Compute area of adjacent objects.
            */
            if (status == MagickFalse)
              continue;
            dx=connectivity > 4 ? connect8[k][1] : connect4[k][1];
            dy=connectivity > 4 ? connect8[k][0] : connect4[k][0];
            q=GetCacheViewVirtualPixels(object_view,bounding_box.x+x+dx,
              bounding_box.y+y+dy,1,1,exception);

```
... we always look above or to the left of a pixel. For the component at top-left, we will get a virtual-pixel. The default "`-virtual-pixel`" is "`edge`", so we will look in the same component.

If that is the bug (untested), I'm not sure of the best solution.

**Comment by fmw42** [comment]
I suppose it is easy enough either for the code or for the user to just include -virtual-pixel none.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by snibgo** [comment]
> I suppose it is easy enough either for the code or for the user to just include -virtual-pixel none.

That would solve the merging issue, but sadly there are other problems. For example, we use transparent small squares:
```
%IMG7%magick ^
  -size 300x300 xc:#0f0 ^
  ( +clone ^
    -fill White -colorize 100  ^
    -fill Black ^
    -draw "rectangle 0,0,10,10" ^
    -draw "rectangle 290,290,299,299" ^
  ) ^
  -alpha off -compose CopyOpacity -composite ^
  -background Black -alpha Background ^
  x11.png
```
x11.png is:
![x11](https://user-images.githubusercontent.com/33812368/181408290-60b881a0-ff86-40f7-9c19-4706b4d6d2ec.png)


```
%IMG7%magick ^
  x11.png ^
  -define connected-components:verbose=true ^
  -connected-components 4 ^
  NULL:

Objects (id: bounding-box centroid area mean-color):
  1: 300x300+0+0 149.5,149.5 89779 srgba(0,255,0,1.72996)
  0: 11x11+0+0 5.0,5.0 121 srgba(0,0,0,541.612)
  2: 10x10+290+290 294.5,294.5 100 srgba(0,0,0,655.35)
```
Note the incorrect alpha values, such as 655.35 which should be zero.

```
%IMG7%magick ^
  x11.png ^
  -define connected-components:verbose=true ^
  -define connected-components:area-threshold=6000 ^
  -virtual-pixel None ^
  -connected-components 4 ^
  -define quantum:format=floating-point -depth 32 ^
  x12.tiff

Objects (id: bounding-box centroid area mean-color):
  1: 300x300+0+0 149.7,149.7 89879 srgba(0,255,0,1.72996)
```
Note the incorrect count, and incorrect alpha value.

The image x12.tiff looks correct but it isn't. The corner squares are rgba(0,0,0,0) but most of the image is rgba(0.0015259,0.0015259,0.0015259,100). So it has two different colours:
```
f:\web\im>%IMG7%magick x12.tiff -unique-colors txt:
# ImageMagick pixel enumeration: 2,1,0,65535,graya
0,0: (0,65535)  #000000000000FFFF  graya(0,1)
1,0: (1,65535)  #000100010001FFFF  graya(0.0015259%,1)
```

**Comment by snibgo** [comment]
"-virtual-pixel None" doesn't fix the problem with spm_hue_4a.png in the OP. For the component at top-left, there are no components above or to the left to merge into.

For this image, we can fix by rotating and repeating "-connected-components 4", then rotating back. 

```
magick ^
  spm_hue_4a.png
  -virtual-pixel None ^
  -define connected-components:verbose=true ^
  -define connected-components:mean-color=true ^
  -define connected-components:area-threshold=5433 ^
  -connected-components 4 ^
  -rotate 180 -connected-components 4 -rotate -180
  s.png
```
![s](https://user-images.githubusercontent.com/33812368/181826561-c3e7fae5-dcbf-4f0f-bbf4-41bf0f9f1d46.png)
This trick of rotating and repeating "-connected-components 4" also fixes the problem with x11.png.
```
%IMG7%magick ^
  x11.png ^
  -define connected-components:verbose=true ^
  -define connected-components:area-threshold=6000 ^
  -virtual-pixel None ^
  -connected-components 4 ^
  -rotate 180 -connected-components 4 -rotate -180 ^
  -define quantum:format=floating-point -depth 32 ^
  x12.tiff
```
The result is entirely black, as we would expect.

The current C code walks through the pixels of a component, in the usual row-column order, looking for a component above or to the left. A possible fix is: If none are found, we could repeat the search in the opposite order, looking for a component below or to the right.

I haven't tested this by writing C code. It seems logical, because we might need to merge a small component with a larger one that may be above, below, or to the left or right.
