### ISSUE TITLE
Possible OpenCL Regression in Win64 7.1.0-43-Q16-HDRI-x64-dll

### ISSUE THREAD

**Issue by wx00** [ImageMagick/ImageMagick#5369]
### ImageMagick version

7.1.0-43

### Operating system

Windows

### Operating system, version and so on

Windows 10 21H2

### Description

I typically use a powershell command to run multiple magick instances in parallel to do some image format conversion with customized resizing and file renaming.
My computer uses an Intel i5-10500 and its iGPU, when I used 7.1.0-40 and previous version, turning on the OpenCL flag accelerates the converting process a little bit, so I leave the flag turn on.
Recently (in ~3 weeks), after I updated the Intel Graphics driver (to 30.0.101.1994) and ImageMagick, it become very slow when I run the same command, and later I found it run at normal speed when I turn off the OpenCL flag.
![image](https://user-images.githubusercontent.com/4850853/180680127-e147213a-1e15-43a4-878f-76e8a233a3de.png)

I currently have no other machines in hand to test on different hardware, and the computer is not ready to reboot and reinstall older drivers to test right now. I'm hoping maybe someone can help to confirm and address the issue, thanks.

### Steps to Reproduce

Set environmental variable `MAGICK_OCL_DEVICE=True`, in a folder with images named `[prefix]-[number].[extention]` (extension can be `.jpg, .png, .tif`, I see no difference here), run the following command : 
```
Measure-Command -Expression{
$extracted = Get-ChildItem *-*.*;
if ($extracted.Count -ne 0){ 1..$extracted.Count |ForEach-Object -ThrottleLimit 10 -Parallel {
  $fmt = "jpg";
  $infile = ($using:extracted)[$($_-1)];
  $iname = $infile.FullName;
  if($(magick identify -format '%[opaque]' $iname)) {
  $outfile = Join-Path $infile.DirectoryName $("$($infile.BaseName -replace 'gimp-' -replace 'orig-' -replace '.rotate').$($fmt)");
  magick convert -format $fmt -strip -interlace Plane `
    -define jpeg:dct-method=float -sampling-factor 4:2:0 -quality 80 `
    -define filter:lobes=3 -filter lanczos `
    -units PixelsPerInch -resize 864> -density 104 `
    $iname $outfile
}};}}|Select-Object TotalSeconds
```

**Comment by dlemstra** [comment]
We haven't made any changes in the OpenCL part for ages so I suspect that this is a driver issue.

**Comment by wx00** [comment]
Thanks for the info, I'll try rollback the driver to an earlier version later.

**Comment by wx00** [comment]
So I tried 3 most recent Intel Graphics driver release:

- 30.0.101.1660 (this version was used before the update)
- 30.0.101.1960
- 30.0.101.1994 (latest)

install, reboot, then run magick convert the same batch of images with the MAGICK_OCL_DEVICE flag turn on and off, and the results are like this:

| Graphics Driver version | time with OpenCL | time without OpenCL | 
| ------ | ------ | ------ |
| 30.0.101.1660 | 5.40s | 6.17s |
| 30.0.101.1960 | 69.19s | 6.26s |
| 30.0.101.1994 | 6.33s | 6.24s |

Interestingly, the 30.0.101.1994 version now has similar runtime with and without the OpenCL turn on, unlike the ~7x speed difference when I reported this issue, but still a regression compare to 30.0.101.1660. It looks like Intel has done something wrong after the 30.0.101.1660 version and almost fix it in the latest release.

I guess I'll stay using 30.0.101.1660 for now and wait for later version.

Since it's not a problem from IM, I'm closing this issue now.
