### ISSUE TITLE
ImageMagick compilation error in make file

### ISSUE THREAD

**Issue by atifgatherit** [ImageMagick/ImageMagick#5372]
### ImageMagick version

7.1.0-44

### Operating system

Linux

### Operating system, version and so on

debian

### Description

ImageMagick make file compilation fails.
I get the error **undefined reference to `FT_Set_Default_Properties'**.

### Steps to Reproduce

I am following the steps mentioned [here](https://www.linuxcapable.com/how-to-install-imagemagick-on-debian-11/).
Compilation fails when command `make  all-am` is run.

### Images

![image](https://user-images.githubusercontent.com/91684606/180760358-df0930fb-e510-4896-aa9e-966153935cb8.png)
![image](https://user-images.githubusercontent.com/91684606/180760521-ebd4b565-6b62-44cb-83bc-12b788a8ca33.png)

**Comment by urban-warrior** [comment]
Looks like we may need to conditionally compile that statement.  What version of Freetype are you using?  We use Freetype 2.12.1-2.

**Comment by Weiwf** [comment]
I encountered a similar issue during compilation.


> 2 MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `FT_Set_Default_Properties'
collect2: error: ld returned 1 exit status
Makefile:8197: recipe for target 'utilities/magick' failed
make[1]: *** [utilities/magick] Error 1
make[1]: Leaving directory '/opt/wwf/ImageMagick-7.0.1'
Makefile:6244: recipe for target 'all' failed
make: *** [all] Error 2

Check my freetype version, using the command `pkg-config --modversion freetype2`:

> 18.1.12

How can i solve the issue? @dlemstra

**Comment by dlemstra** [comment]
That version of freetype2 looks incorrect?  Version 18.1.12 makes no sense to me...
