### ISSUE TITLE
-evaluate Pow 2

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#5376]
### ImageMagick version

7.1.0-42

### Operating system

Windows

### Operating system, version and so on

Pre-built IM v7.1.0-42 (with HDRI) on Windows 8.1

### Description

When a negative number is squared, the result should be positive.
```
f:\web\im>%IMG7%magick xc:srgb(-10%,20%,-30%) -evaluate pow 2 txt:
# ImageMagick pixel enumeration: 1,1,0,65535,srgb
0,0: (0,2621,0)  #00000A3D0000  srgb(-1%,4%,-9%)  <== Wrong
```

Workaround: "-fx" can be used to get the correct result (but more slowly):
```
f:\web\im>%IMG7%magick xc:srgb(-10%,20%,-30%) -fx u*u txt:
# ImageMagick pixel enumeration: 1,1,0,65535,srgb
0,0: (655,2621,5898)  #028F0A3D170A  srgb(1%,4%,9%)  <== Correct

f:\web\im>%IMG7%magick xc:srgb(-10%,20%,-30%) -fx pow(u,2) txt:
# ImageMagick pixel enumeration: 1,1,0,65535,srgb
0,0: (655,2621,5898)  #028F0A3D170A  srgb(1%,4%,9%)  <== Correct
```

### Steps to Reproduce

As above.

### Images

None.

**Comment by snibgo** [comment]
The problem seems to be in statistic.c, function ApplyEvaluateOperator():
```
    case PowEvaluateOperator:
    {
      if (pixel < 0)
        result=(double) -(QuantumRange*pow((double) -(QuantumScale*pixel),
          (double) value));
      else
        result=(double) (QuantumRange*pow((double) (QuantumScale*pixel),
          (double) value));
      break;
    }
```
The condition `(pixel < 0)` is too weak. It should not apply when `value` is an integer, so it should test for pixel being negative AND value not being an integer, to avoid a C "domain error", for example:
```
      if (pixel < 0 && value - int(value) > MagickEpsilon)
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
