### ISSUE TITLE
Documentation Issue -FX

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#5388]
### ImageMagick version

7.1.0.44

### Operating system

MacOS

### Operating system, version and so on

Mac OSX Monterey

### Description

On page https://imagemagick.org/script/fx.php

The mean() is missing in two places:

1) Between max() and min() in:

> math functions:
> abs(), acos(), acosh(), airy(), alt(), asin(), asinh(), atan(), atanh(), atan2(), ceil(), clamp(), cos(), cosh(), debug(), drc(), erf(), exp(), floor(), gauss(), gcd(), hypot(), int(), isnan(), j0(), j1(), jinc(), ln(), log(), logtwo(), max(), min(), mod(), not(), pow(), rand(), round(), sign(), sin(), sinc(), sinh(), sqrt(), squish(), tan(), tanh(), trunc()
> 

2) Between image.maxima, image.minima

> image.depth, image.kurtosis, image.maxima, image.minima, image.resolution.x, image.resolution.y, image.skewness, image.standard_deviation
> image attributes
> 

### Steps to Reproduce

See above

### Images

none

**Comment by snibgo** [comment]
>The mean() is missing in two places:
> 1. Between max() and min() in:

"`-fx`" doesn't have a `mean()` function.

> 2. Between image.maxima, image.minima

You are correct. "`-fx`" has a `mean` attribute, for example `u.mean` and `u.mean.r`, and that should be in that documentation.

**Comment by fmw42** [comment]
> The mean() is missing in two places:
> 
> Between max() and min() in:
> "-fx" doesn't have a mean() function.
> 

True not for -fx, but for %[fx] it does.  

If no mean(), then why is mod() listed?  What is the mod() function? I only know about using it in %[fx] as well.

**Comment by snibgo** [comment]
> True not for -fx, but for %[fx] it does.

Can you show an example?
```
f:\web\im>%IMG7%magick xc: -format "%[fx:mean(2,3)]" info:
magick: Not a real operator at '(2,3)' @ error/fx.c/GetOperator/2411.
```
There is a "`mod()`" function. It takes 2 arguments, and returns the first modulus the second. For positive integers, this is the remainder after dividing the first number by the second.
```
f:\web\im>%IMG7%magick xc: -format "%[fx:mod(123,10)]" info:
3
```

**Comment by fmw42** [comment]
You are correct in that regard. But

there is a mean for %[fx:] but I guess that is really equivalent to image.mean and not a function mean().

**Comment by snibgo** [comment]
> But there is a mean for %[fx:] but I guess that is really equivalent to image.mean and not a function mean().

Yes.

**Comment by safetycar** [comment]
image.median also seems available, but not documented
