### ISSUE TITLE
Grayscale by FX DIY Evaluate Operator no longer works as documented with ImageMagick 7.

### ISSUE THREAD

**Issue by yoya** [ImageMagick/ImageMagick#5389]
### ImageMagick version

7.1.0-44

### Operating system

MacOS

### Operating system, version and so on

macOS Monterey 12.4

### Description

The documented FX DIY Evaluate Operator Grayscale command has not worked since ImageMagick-7.0.1-0 until latest version.
This issue points out a problem with the documentation, not the implementation.

- https://www.imagemagick.org/Usage/color_mods/#grayscale

```
  magick test.png -channel R -evaluate multiply .2 \
                   -channel G -evaluate multiply .5 \
                   -channel B -evaluate multiply .3 \
                   +channel -separate -compose add -flatten gray_253.png
```

| gray_253.png |  expected image |
|---|---|
 ![gray_253-v7](https://user-images.githubusercontent.com/26040/181796203-2023a52e-4305-4caf-a5a2-ca9a5b84ca22.png) | ![gray_253-v6](https://user-images.githubusercontent.com/26040/181796228-1b9db1be-34ee-43e7-b7f6-804f4f756ac7.png) |

We need to keep the alpha channel out of the composite.
I couldn't come up with a simple command, sorry.

This is not a problem with ImageMagick 6. (As you know, It's a convert command, not a magick).
It's consistent behavior as ImageMagick7, but the document is wrong and should be corrected.

Please refer to "Steps to Reproduce" for the behavior of each version.

## ImageMagick-7.1.0-44

```
% ~/ImageMagick/7.1.0-44/bin/magick -version
Version: ImageMagick 7.1.0-44 Q16-HDRI x86_64 20294 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI
Delegates (built-in): bzlib jpeg lzma tiff xml zlib
Compiler: gcc (4.2)
% ~/ImageMagick/7.1.0-44/bin/magick test.png \
           -channel R -evaluate multiply .2 \
           -channel G -evaluate multiply .5 \
           -channel B -evaluate multiply .3 \
           +channel -separate -compose add -flatten gray_253-v7.png

```
| gray_253-v7.png | 
|---|
| ![gray_253-v7](https://user-images.githubusercontent.com/26040/181796203-2023a52e-4305-4caf-a5a2-ca9a5b84ca22.png) |

###  Success (6.9.12-59)

```
% ~/ImageMagick/6.9.12-59/bin/convert test.png \
           -channel R -evaluate multiply .2 \
           -channel G -evaluate multiply .5 \
           -channel B -evaluate multiply .3 \
           +channel -separate -compose add -flatten gray_253-v6.png
```

| gray_253-v6.png |
|---|
|  ![gray_253-v6](https://user-images.githubusercontent.com/26040/181796228-1b9db1be-34ee-43e7-b7f6-804f4f756ac7.png) |

### Failure (7.0.1-0)

```
% ~/ImageMagick/7.0.1-0/bin/magick test.png \
           -channel R -evaluate multiply .2 \
           -channel G -evaluate multiply .5 \
           -channel B -evaluate multiply .3 \
           +channel -separate -compose add -flatten gray_253-v70.png
```

| gray_253-v70.png  |
|---|
|  ![gray_253-v70](https://user-images.githubusercontent.com/26040/181796256-990d9c0e-32c4-460c-b454-326bc4ccfaef.png) |

### Images

|  |  output images.
|---|---|
| gray_253-v7.png | ![gray_253-v7](https://user-images.githubusercontent.com/26040/181796203-2023a52e-4305-4caf-a5a2-ca9a5b84ca22.png) |
| gray_253-v6.png | ![gray_253-v6](https://user-images.githubusercontent.com/26040/181796228-1b9db1be-34ee-43e7-b7f6-804f4f756ac7.png) |
| gray_253-v70.png  | ![gray_253-v70](https://user-images.githubusercontent.com/26040/181796256-990d9c0e-32c4-460c-b454-326bc4ccfaef.png) |

**Comment by fmw42** [comment]
Is this what you want?

```
magick test.png \
-channel R -evaluate multiply .2 +channel \
-channel G -evaluate multiply .5 +channel \
-channel B -evaluate multiply .3 +channel \
-channel rgb -separate -compose add -flatten gray_253.png

```
![gray_253](https://user-images.githubusercontent.com/13458218/181800452-d5b7ff34-3807-4055-b6b0-6a2e2e3b4d2a.png)

**Comment by yoya** [comment]
Thank you, I got it.
I was expecting the original alpha data to be retained, like the other grayscale commands.

But, even in ImageMagick v6, the FX DIY Evaluate Operator command does not retain the alpha channel (changes all to 0xff),
so fmw's command works almost the same effect.

**Comment by fmw42** [comment]
The comment on that linked pages says:

> For example, here is a 2/5/3 ratio gray-scaled image, though again I make no attempt to preserve the transparency channel of the original image.

So he was not preserving the alpha channel.

If you want the alpha channel on the result, you can do:

```
magick test.png -write mpr:img \
-channel R -evaluate multiply .2 +channel \
-channel G -evaluate multiply .5 +channel \
-channel B -evaluate multiply .3 +channel \
-channel rgb -separate -compose add -flatten \
\( mpr:img -alpha extract \) \
-alpha off -compose copy_opacity -composite \
gray_253c.png

```
![gray_253c](https://user-images.githubusercontent.com/13458218/181806688-2b970d19-efa8-43cd-9c64-affcf95bdf62.png)

**Comment by yoya** [comment]
Thank you for editing the official document.

By the way, regarding command, is +channel required?

```
  magick test.png -channel R -evaluate multiply .2 +channel \
                   -channel G -evaluate multiply .5 +channel \
                   -channel B -evaluate multiply .3 +channel \
                   -channel RGB -separate -compose add -flatten gray_253.png
```

The following command produces the same result.

```
  magick test.png -channel R -evaluate multiply .2 \
                   -channel G -evaluate multiply .5  \
                   -channel B -evaluate multiply .3  \
                   -channel RGB -separate -compose add -flatten gray_253.png
```

**Comment by fmw42** [comment]
In this case it does not appear to cause problems. But I do it to be safe. I may be overly cautious. But I want to ensure subsequent -channel X do not affect previous ones.

**Comment by yoya** [comment]
I understood that the fmw42's command avoids unnecessary context by restoring the channel default each time channel processing is completed.
I have confirmed that this is reflected in the documentation and will close this issue. Thank you very much. > fmw42
