### ISSUE TITLE
PixelColor off by one on i386

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#54]
For the code below, the quantum value of a pixel that has had its color set by `PixelSetColor(pixel_wand, "rgb(50%, 50%, 50%)"); ` is off by one on Centos i386 platofrm compared to the value on Centos x86_64. I think the x86_64 is correct.

Output on  CentOS-6.4-i386 http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-i386-v20131103.box
50  percent is 32768, 32768, 32768
100 percent is 65535, 65535, 65535
  
Output on CentOS-6.4-x86_64 http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box
50  percent is 32767, 32767, 32767
100 percent is 65535, 65535, 65535

Code:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <wand/MagickWand.h>

int main(int argc,char **argv) {

    PixelWand *pixel_wand;
    
    int red, green, blue;

    MagickWandGenesis();

    pixel_wand = NewPixelWand();  
    PixelSetColor(pixel_wand, "rgb(50%, 50%, 50%)");
    red   = PixelGetRedQuantum(pixel_wand);
    green = PixelGetGreenQuantum(pixel_wand);
    blue  = PixelGetBlueQuantum(pixel_wand);
    printf("50  percent is %d, %d, %d\n", red, green, blue);

    
    PixelSetColor(pixel_wand, "rgb(100%, 100%, 100%)");  
    red   = PixelGetRedQuantum(pixel_wand);
    green = PixelGetGreenQuantum(pixel_wand);
    blue  = PixelGetBlueQuantum(pixel_wand);
    printf("100 percent is %d, %d, %d\n", red, green, blue);
    
    
// Output on  CentOS-6.4-i386
// http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-i386-v20131103.box
//50  percent is 32768, 32768, 32768
//100 percent is 65535, 65535, 65535
  
// Output on CentOS-6.4-x86_64
// http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box
//50  percent is 32767, 32767, 32767
//100 percent is 65535, 65535, 65535

    MagickWandTerminus();
    return (0);
}


// Both were compiled with:
//
// ./configure --with-quantum-depth=16 \
//           --with-magick-plus-plus=no \
//           --without-perl \
//           --disable-static \
//           --exec-prefix=/usr/sbin \
//           --disable-hdri \
//           --disable-docs \
//           --disable-openmp 

```

**Comment by urban-warrior** [comment]
We'll commit a patch to fix this problem sometime today.  Thanks.

**Comment by Danack** [comment]
Hi, does the patch need to be applied to the IM6 branch? I should have said, that was the branch I was testing against, and it still seems to be off by one.

**Comment by urban-warrior** [comment]
The correct answer is 32768 (65535/2 = 32767.5 rounded up to 32768).  We get 32768 for X86_64 and i386 in ImageMagick 6.9.2-6 Beta.

**Comment by Danack** [comment]
K - thanks.
