### ISSUE TITLE
Different rendered image with same inputs on two computers

### ISSUE THREAD

**Issue by starkyller** [ImageMagick/ImageMagick#5401]
### ImageMagick version

7.1.0-44

### Operating system

MacOS

### Operating system, version and so on

Monterey 12.1

### Description

Hi there,
I am currently facing a peculiar problem with imagemagick that I think is related to one of its dependencies although I am unable to figure out which one.
Basically the problem is the following, I am creating some pictures that render text (with help from [wand](https://github.com/emcconville/wand)). 
When I render it on my machine Imagemagick (version 7.1.0-23) it renders out perfectly, but when it renders on my co-worker machine the text gets weird.

Picture rendered on my machine (version 7.1.0-23):
![buehl2_9](https://user-images.githubusercontent.com/15750437/182103142-ba9ea16a-e401-472e-85f2-9c428ea42cd1.png)

Picture rendered on my co-worker machine (version 7.1.0-44):
![buehl2_9](https://user-images.githubusercontent.com/15750437/182103292-18124759-09a8-4f0c-b671-30628beb7d1d.png)

I believe we have installed the same dependencies (I started playing with imagemagick some months ago, and he only started a week ago).
We installed everything with brew.
Ghostscript and then ImageMagick.

Are we missing some dependency installation on his machine? I am unable to remember if I faced this problem back then when I started playing with imagemagick, and I am unable to find people here that have suffered from the same issue  before.

### Steps to Reproduce

n/a

**Comment by urban-warrior** [comment]
It would be helpful to view the code snippet you used to render the image.  What version of Freetype delegate library are you using on both systems? Type `magick -list format | grep TTF`.  Compare the ImageMagick builds with `magick -list configure`.  Did you specify a font?  If not, do so to ensure both systems are rendering with the same font.

**Comment by starkyller** [comment]
We did specify a font (we even have a absolute path to it). Thank you very much. I will collect this information you have asked and report back.

**Comment by fmw42** [comment]
What are your versions of freetype? Are they the same?

**Comment by starkyller** [comment]
So here it is the collected information

## magick -list format | grep TTF

|TTF format |My Machine Version| My co-workers machine version|
|----|-----|------|
|DFONT* TTF|Multi-face font package (Freetype 2.11.1) |Multi-face font package (Freetype 2.12.1) |
|OTF* TTF| Open Type font (Freetype 2.11.1)| Open Type font (Freetype 2.12.1)|
|PFA* TTF| Postscript Type 1 font (ASCII) (Freetype 2.11.1)|Postscript Type 1 font (ASCII) (Freetype 2.12.1) |
|PFB* TTF|Postscript Type 1 font (binary) (Freetype 2.11.1) | Postscript Type 1 font (binary) (Freetype 2.12.1)|
|TTC* TTF| TrueType font collection (Freetype 2.11.1)|TrueType font collection (Freetype 2.12.1) |
|TTF* TTF|TrueType font (Freetype 2.11.1) | TrueType font (Freetype 2.12.1)|

## About 'magick -list configure' diff comparison (only rows with different data are in this table)

|Name |My Machine| My co-workers machine|
|----|-----|------|
|CFLAGS | -I/usr/local/Cellar/webp/1.2.2/include -I/usr/local/Cellar/webp/1.2.2/include -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -pthread -I/usr/local/Cellar/imath/3.1.4/include -I/usr/local/Cellar/imath/3.1.4/include/Imath -I/usr/local/Cellar/openexr/3.1.4/include -I/usr/local/Cellar/openexr/3.1.4/include/OpenEXR -I/usr/local/Cellar/xz/5.2.5/include -I/usr/local/Cellar/pcre/8.45/include -I/usr/local/Cellar/glib/2.70.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.70.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/liblqr/0.4.2_1/include/lqr-1 -I/usr/local/Cellar/openjpeg/2.4.0/include/openjpeg-2.4 -I/usr/local/Cellar/little-cms2/2.13/include -I/usr/local/Cellar/brotli/1.0.9/include -I/usr/local/Cellar/jpeg-xl/0.6.1/include -I/usr/local/Cellar/libvmaf/2.3.0_1/include -I/usr/local/Cellar/libvmaf/2.3.0_1/include/libvmaf -I/usr/local/Cellar/aom/3.2.0_2/include -I/usr/local/Cellar/libde265/1.0.8/include -I/usr/local/Cellar/x265/3.5/include -I/usr/local/Cellar/libheif/1.12.0_1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.13.1/include  -Xpreprocessor -fopenmp -Wall -g -O2 -mtune=ivybridge -fexceptions -D_FORTIFY_SOURCE=0 -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 | -I/usr/local/Cellar/webp/1.2.3/include -I/usr/local/Cellar/webp/1.2.3/include -I/usr/local/Cellar/little-cms2/2.13.1/include -I/usr/local/Cellar/libraw/0.20.2_2/include/libraw -I/usr/local/Cellar/libraw/0.20.2_2/include -I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -pthread -I/usr/local/Cellar/imath/3.1.5/include -I/usr/local/Cellar/imath/3.1.5/include/Imath -I/usr/local/Cellar/openexr/3.1.5/include -I/usr/local/Cellar/openexr/3.1.5/include/OpenEXR -I/usr/local/Cellar/xz/5.2.5_1/include -I/usr/local/Cellar/pcre/8.45/include -I/usr/local/Cellar/glib/2.72.3/include/glib-2.0 -I/usr/local/Cellar/glib/2.72.3/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/liblqr/0.4.2_1/include/lqr-1 -I/usr/local/Cellar/openjpeg/2.5.0/include/openjpeg-2.5 -I/usr/local/Cellar/little-cms2/2.13.1/include -I/usr/local/Cellar/brotli/1.0.9/include -I/usr/local/Cellar/jpeg-xl/0.6.1/include -I/usr/local/Cellar/libvmaf/2.3.1/include -I/usr/local/Cellar/libvmaf/2.3.1/include/libvmaf -I/usr/local/Cellar/aom/3.4.0/include -I/usr/local/Cellar/libde265/1.0.8/include -I/usr/local/Cellar/x265/3.5/include -I/usr/local/Cellar/libheif/1.12.0_1/include -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/opt/freetype/include/freetype2 -I/usr/local/Cellar/fontconfig/2.14.0/include  -Xpreprocessor -fopenmp -Wall -g -O2 -mtune=ivybridge -fexceptions -D_FORTIFY_SOURCE=0 -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16|
|CODER_PATH | /usr/local/Cellar/imagemagick/7.1.0-23/lib/ImageMagick/modules-Q16HDRI/coders|/usr/local/Cellar/imagemagick/7.1.0-44/lib/ImageMagick/modules-Q16HDRI/coders |
|CONFIGURE| ./configure  '--enable-osx-universal-binary=no' '--prefix=/usr/local/Cellar/imagemagick/7.1.0-23' '--disable-dependency-tracking' '--disable-silent-rules' '--disable-opencl' '--enable-shared' '--enable-static' '--with-freetype=yes' '--with-gvc=no' '--with-modules' '--with-openjp2' '--with-openexr' '--with-webp=yes' '--with-heic=yes' '--with-gslib' '--with-gs-font-dir=/usr/local/share/ghostscript/fonts' '--with-lqr' '--without-fftw' '--without-pango' '--without-wmf' '--enable-openmp' 'ac_cv_prog_c_openmp=-Xpreprocessor -fopenmp' 'ac_cv_prog_cxx_openmp=-Xpreprocessor -fopenmp' 'LDFLAGS=-lomp -lz' '--without-x' 'CC=clang' 'PKG_CONFIG_PATH=/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/jbig2dec/lib/pkgconfig:/usr/local/opt/jpeg/lib/pkgconfig:/usr/local/opt/libidn/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/little-cms2/lib/pkgconfig:/usr/local/opt/openjpeg/lib/pkgconfig:/usr/local/opt/brotli/lib/pkgconfig:/usr/local/opt/imath/lib/pkgconfig:/usr/local/opt/openexr/lib/pkgconfig:/usr/local/opt/webp/lib/pkgconfig:/usr/local/opt/jpeg-xl/lib/pkgconfig:/usr/local/opt/libvmaf/lib/pkgconfig:/usr/local/opt/aom/lib/pkgconfig:/usr/local/opt/libde265/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.9/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/x265/lib/pkgconfig:/usr/local/opt/libheif/lib/pkgconfig:/usr/local/opt/liblqr/lib/pkgconfig:/usr/local/opt/shared-mime-info/share/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/12' 'CXX=clang++'| ./configure  '--enable-osx-universal-binary=no' '--prefix=/usr/local/Cellar/imagemagick/7.1.0-44' '--disable-dependency-tracking' '--disable-silent-rules' '--disable-opencl' '--enable-shared' '--enable-static' '--with-freetype=yes' '--with-gvc=no' '--with-modules' '--with-openjp2' '--with-openexr' '--with-webp=yes' '--with-heic=yes' '--with-raw=yes' '--with-gslib' '--with-gs-font-dir=/usr/local/share/ghostscript/fonts' '--with-lqr' '--without-fftw' '--without-pango' '--without-wmf' '--enable-openmp' '--without-x' 'ac_cv_prog_c_openmp=-Xpreprocessor -fopenmp' 'ac_cv_prog_cxx_openmp=-Xpreprocessor -fopenmp' 'LDFLAGS=-lomp -lz' 'CC=clang' 'PKG_CONFIG_PATH=/usr/local/opt/libpng/lib/pkgconfig:/usr/local/opt/freetype/lib/pkgconfig:/usr/local/opt/fontconfig/lib/pkgconfig:/usr/local/opt/jbig2dec/lib/pkgconfig:/usr/local/opt/jpeg/lib/pkgconfig:/usr/local/opt/libidn/lib/pkgconfig:/usr/local/opt/libtiff/lib/pkgconfig:/usr/local/opt/little-cms2/lib/pkgconfig:/usr/local/opt/openjpeg/lib/pkgconfig:/usr/local/opt/brotli/lib/pkgconfig:/usr/local/opt/imath/lib/pkgconfig:/usr/local/opt/openexr/lib/pkgconfig:/usr/local/opt/webp/lib/pkgconfig:/usr/local/opt/jpeg-xl/lib/pkgconfig:/usr/local/opt/libvmaf/lib/pkgconfig:/usr/local/opt/aom/lib/pkgconfig:/usr/local/opt/libde265/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/glib/lib/pkgconfig:/usr/local/opt/x265/lib/pkgconfig:/usr/local/opt/libheif/lib/pkgconfig:/usr/local/opt/liblqr/lib/pkgconfig:/usr/local/opt/jasper/lib/pkgconfig:/usr/local/opt/libraw/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/shared-mime-info/share/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/12' 'CXX=clang++' |
| CONFIGURE_PATH| /usr/local/Cellar/imagemagick/7.1.0-23/etc/ImageMagick-7/ | /usr/local/Cellar/imagemagick/7.1.0-44/etc/ImageMagick-7/|
|CPPFLAGS | -I/usr/local/Cellar/imagemagick/7.1.0-23/include/ImageMagick-7| -I/usr/local/Cellar/imagemagick/7.1.0-44/include/ImageMagick-7|
| DELEGATES| bzlib fontconfig freetype gslib heic jng jpeg lcms lqr lzma openexr openjp2 png ps tiff webp xml zlib | bzlib fontconfig freetype gslib heic jng jpeg lcms lqr lzma openexr openjp2 png ps raw tiff webp xml zlib|
|DOCUMENTATION_PATH|    /usr/local/Cellar/imagemagick/7.1.0-23/share/doc/ImageMagick-7|/usr/local/Cellar/imagemagick/7.1.0-44/share/doc/ImageMagick-7|
|EXEC-PREFIX   |        /usr/local/Cellar/imagemagick/7.1.0-23|/usr/local/Cellar/imagemagick/7.1.0-44|
|EXECUTABLE_PATH |      /usr/local/Cellar/imagemagick/7.1.0-23/bin|/usr/local/Cellar/imagemagick/7.1.0-44/bin|
|FILTER_PATH |/usr/local/Cellar/imagemagick/7.1.0-23/lib/ImageMagick/modules-Q16HDRI/filters | /usr/local/Cellar/imagemagick/7.1.0-44/lib/ImageMagick/modules-Q16HDRI/filters|
| GIT_REVISION | 19648 | 20294 |
| HOST |x86_64-apple-darwin21.1.0|x86_64-apple-darwin21.5.0 |
|INCLUDE_PATH |/usr/local/Cellar/imagemagick/7.1.0-23/include/ImageMagick-7 | /usr/local/Cellar/imagemagick/7.1.0-44/include/ImageMagick-7|
|LDFLAGS|-L/usr/local/Cellar/imagemagick/7.1.0-23/lib -lomp -lz | -L/usr/local/Cellar/imagemagick/7.1.0-44/lib -lomp -lz|
|LIB_VERSION_NUMBER |7,1,0,23 | 7,1,0,44|
|LIBRARY_PATH | /usr/local/Cellar/imagemagick/7.1.0-23/lib/ImageMagick| /usr/local/Cellar/imagemagick/7.1.0-44/lib/ImageMagick|
|LIBS |-L/usr/local/Cellar/little-cms2/2.13/lib -llcms2 -L/usr/local/opt/freetype/lib -lfreetype  -L/usr/local/Cellar/glib/2.70.3/lib -L/usr/local/opt/gettext/lib -llqr-1 -lglib-2.0 -lintl  -lxml2  -L/usr/local/opt/freetype/lib -L/usr/local/Cellar/fontconfig/2.13.1/lib -lfontconfig -lfreetype     -lbz2 -lz   -lltdl  -lm    -lpthread   |-L/usr/local/Cellar/little-cms2/2.13.1/lib -llcms2 -L/usr/local/opt/freetype/lib -lfreetype  -L/usr/local/Cellar/glib/2.72.3/lib -L/usr/local/opt/gettext/lib -llqr-1 -lglib-2.0 -lintl  -lxml2  -L/usr/local/opt/freetype/lib -L/usr/local/Cellar/fontconfig/2.14.0/lib -lfontconfig -lfreetype     -lbz2 -lz   -lltdl  -lm    -lpthread |
|PREFIX | /usr/local/Cellar/imagemagick/7.1.0-23|/usr/local/Cellar/imagemagick/7.1.0-44 |
| RELEASE_DATE| 2022-02-05| 2022-07-24|
| SHARE_PATH|/usr/local/Cellar/imagemagick/7.1.0-23/share/ImageMagick-7 |/usr/local/Cellar/imagemagick/7.1.0-44/share/ImageMagick-7 |
| SHAREARCH_PATH|/usr/local/Cellar/imagemagick/7.1.0-23/lib/ImageMagick/config-Q16HDRI |/usr/local/Cellar/imagemagick/7.1.0-44/lib/ImageMagick/config-Q16HDRI |
| TARGET_OS|darwin21.1.0 |darwin21.5.0 |



## About some code sample

I am not alowed to show you our codebase, so I made a small sample of how we have Drawing objects configured and how we render text<br>
This is just a very small sample.


```python
from wand.image import Image
from wand.drawing import Drawing
from wand.color import Color

from something.font_tools import func_that_gets_absolute_path_to_font

# we are using LibberationMono-Regular.ttf, it is freally available on the web
font_path = func_that_gets_absolute_path_to_font()

canvas_res_width = 500
canvas_res_height = 500


text_to_write = "test test 123"
text_start_x_position = 15
text_start_y_position = 15

with Drawing() as draw:
    
    draw.stroke_opacity = 0.0
    draw.text_antialias = False

    draw.text(text_start_x_position, text_start_y_position, text_to_write)

    with Image(
        width=canvas_res_width,
        height=canvas_res_height,
        depth=1,
        background=Color("white")
        ) as image:
        
        draw(image)

        image.format = "png"
        image.save(filename="picture.png")


```

**Comment by starkyller** [comment]
Actually if we look at our installed versions of freetype both report the same version

```shell
-$> brew info freetype
freetype: stable 2.12.1 (bottled)
Software library to render fonts
https://www.freetype.org/
/usr/local/Cellar/freetype/2.12.0 (67 files, 2.3MB) *
  Poured from bottle on 2022-04-12 at 10:13:23
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/freetype.rb
License: FTL
==> Dependencies
Required: libpng ✔
==> Analytics
install: 309,036 (30 days), 1,030,362 (90 days), 3,718,957 (365 days)
install-on-request: 10,060 (30 days), 39,481 (90 days), 152,688 (365 days)
build-error: 9 (30 days)
```

**Comment by fmw42** [comment]
That is not what you showed above in your table. One showed 2.11.1 and the other 2.21.1
