### ISSUE TITLE
Rotational blur documentation

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#5412]
### ImageMagick version

N/A

### Operating system

Windows

### Operating system, version and so on

N/A

### Description

The document https://imagemagick.org/script/command-line-options.php#radial-blur refers to the "`-radial-blur`" operation, but this has now been renamed "`-rotational-blur`".

Please change the heading, and also remove the sentence ...
> Note that this is actually a rotational blur rather than a radial and as such actually mis-named. 

... and add the sentence ...

> This operation used to be called "-radial-blur".

### Steps to Reproduce

N/A

**Comment by dlemstra** [comment]
Thanks for helping us fix the documentation. We have updated this and this should be changed on the website in a couple days.
