### ISSUE TITLE
+Antialiasing no longer work with convert

### ISSUE THREAD

**Issue by oliviermetienne** [ImageMagick/ImageMagick#5422]
### ImageMagick version

7.1.0-44

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

The following command use to work perfectly in 7.0.7-22
convert.exe +antialias -background none -density 96 MSVG:vectorfile.svg -define png:format=png32 -format png  pixel.png
But no longer create a descent output in 7.1.0-44

success and failing output images are included along with the svg file used for the test

### Steps to Reproduce

Just rung the above command and you will see that the png file render the svg shape incorrectly and does not draw the outline of the shape.
And the colors are watch out compare to the original svg

### Images

![pixelfail](https://user-images.githubusercontent.com/110706595/183231113-66aee90a-266a-4017-9f9f-98707b2de82f.png)
![pixelSuccess](https://user-images.githubusercontent.com/110706595/183231114-4343d0ad-a7e4-40ac-b3d3-812f1dac1990.png)
![vectorfile](https://user-images.githubusercontent.com/110706595/183231115-f1acd7eb-ad19-42f2-9f93-176214aceb46.svg)

**Comment by snibgo** [comment]
Does the `+antialias` make any difference?

With IM v7.1.0-32, the strokes are rendered, and appear correct.

With IM v7.1.0-42, the strokes are not rendered at all. This seems to be a bug.

**Comment by snibgo** [comment]
The command I used was:
```
magick -density 600 -background White  MSVG:vftest2.svg x.png
```
... where `vftest2.svg` is my name for the supplied SVG file.

**Comment by oliviermetienne** [comment]
> iff

Thank you very much for your reply, much appreciated.
Yes +Antialias render the svg as pixelArt. if not present antialias is active the outline are fuzzy

**Comment by oliviermetienne** [comment]
> Does the `+antialias` make any difference?
> 
> With IM v7.1.0-32, the strokes are rendered, and appear correct.
> 
> With IM v7.1.0-42, the strokes are not rendered at all. This seems to be a bug.

Hello, where and how can I download the v7.1.0-32?

Do you know if it is an easy fix? will it be resolved at the next release ?

I was planning to release a book which is much anticipated, and it require ImageMagic to work,

How can you direct the download V7.1.0-32 instead of the next version?

You help is greatly appreciated.

Best Regards

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by oliviermetienne** [comment]
> Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

Thank you very much indeed, much appreciated.
Look forward to test the Patch tomorrow morning.
I will let you know the outcome

Best regards,

**Comment by oliviermetienne** [comment]
> Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

Hello and thank you very much for making the Betha available.
I can see the files, but after download two of them:
ImageMagick-7.1.0-46_beta20220806-windows.zip
ImageMagick-7.1.0-46_beta20220806.zip

I can find the convert.exe or Magic.exe to test and see if the Bug as been fixed.
Can you confirm which one I need to download and how to test it?

I hope you won't have to compile it myself as I am not familiar with compilation and Compilation environment.

I look forward to read you guidance so that I can start testing and give you feedback

**Comment by dlemstra** [comment]
There are no automatic beta builds but I just kicked off a release build: https://github.com/ImageMagick/ImageMagick/actions/runs/2820908063. When this build is completed you can use one of the executables to install a beta version of ImageMagick on your Windows machine.

**Comment by oliviermetienne** [comment]
> There are no automatic beta builds but I just kicked off a release build: https://github.com/ImageMagick/ImageMagick/actions/runs/2820908063. When this build is completed you can use one of the executables to install a beta version of ImageMagick on your Windows machine.

Thank you very much indeed, I was able to successfully download the patch and done some further test which is awesome!!!
The outline now appears which is amazing but there is still an issue with some form of transparencies apply to the whole image. I will mention to UrbanWarrior see if he can fix the issue.

**Comment by oliviermetienne** [comment]
> Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

After you colleague dlemstra create a built for me, I was able to do some further test.
The strokes now appears, which is absolutly awesome!!!
But there is an issue with transparency being applied to the whole image.
I have attached the svg file the command used and the output png in both cases.
Hope you can locate this bug and fix, so very much looking forward to it.

Command used for version 7.0.7.22
Magick.exe +antialias -density 96 -background none MSVG:vectorfile.svg 7_0_7_22.png

Command used for version 7.1.0.46
Magick.exe +antialias -density 96 -background none MSVG:vectorfile.svg 7_1_0_46_Beta.png


![vectorfile](https://user-images.githubusercontent.com/110706595/183744047-d1067123-7437-4a3b-9844-19d5aae70739.svg)
![7_1_0_46_Beta](https://user-images.githubusercontent.com/110706595/183744051-bd2eb0a9-73f6-4ead-b826-824c6dc63c0c.png)
![7_0_7_22](https://user-images.githubusercontent.com/110706595/183744055-06ad6231-8363-44a8-94cb-189acd032d50.png)

**Comment by urban-warrior** [comment]
The issue is that ImageMagick does not support the full SVG specification.  Your image include a `inkscape:grid` element  with `opacity="0.39215686"`.  Change that opacity to 1.0 and the image renders fine.  Alternatively, can you export the SVG without the Inkscape grid?  Or can you just install Inkscape on your Windows system and render the file directly with Inkscape?

On Linux systems, Inkscape is automatically leveraged if its found in your system path.  @dlemstra, is the same true for Windows?  Or does ImageMagick, under Windows, always utilize the internal SVG renderer?

**Comment by oliviermetienne** [comment]
> 

Thank you very much indeed for the prompt reply and as a matter of fact when changing the opacity, the image renders absolutely fine which is awesome.
Thank you so much for sharing your expertise, so very much appreciated.
The issue has indeed now been resolved.

To answer you question about Inkscape, antialiasing cannot be disabled when rendering Svg which is why image magic is crucial in the SVG to PixelArt conversion book which I am writing at the moment.
This is an example of SVG to pixel Converstion using Image Magick, the SVG is creating in Inkscape 
and image Magick render the Pixel Art equivalent thanks to the priceless + antialiasing option

![TerrySvgPixel](https://user-images.githubusercontent.com/110706595/183794922-16f4fd78-025a-46c3-b5f8-e8f0230dfa1a.png)

Thanks you very much indeed, because now I can finish the instruction part of the book about the installation of ImageMagick knowing that everything render correctly.
Can you confirm when the 7.1.46 will be available for download on the Website? so I can time the release of the book.

I will make sure that a percentage of the sales goes toward the Support/Sponsor of ImageMagick.

Thank you so very much indeed for fixing the issue and sharing your expertise.
It is very much appreciated.

**Comment by urban-warrior** [comment]
ImageMagick 7.1.0-46 will be released this weekend, if not sooner.

**Comment by oliviermetienne** [comment]
> ImageMagick 7.1.0-46 will be released this weekend, if not sooner.

Thank you so very much, I am truly impressed with the support, 
I am then closing the issue at it has indeed been resolved.
