### ISSUE TITLE
Unable to output MVG file from SVG using the Magick command line

### ISSUE THREAD

**Issue by oliviermetienne** [ImageMagick/ImageMagick#5429]
### ImageMagick version

7.1.0-44

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

MVG fail to generate when try the following command:

Magick.exe msvg:vectorfile.svg vectorfile.mvg

error displayed:
Magick.exe: NonconformingDrawingPrimitiveDefinition `<?xml' @ error/draw.c/DrawImage/3284.

But no error and the file is generate successfully when using image Magick 7.0.7-22

### Steps to Reproduce

Try the following:
Magick.exe msvg:vectorfile_circle.svg vectorfile.mvg

using the svgfile provided below

### Images

![vectorfile_circle](https://user-images.githubusercontent.com/110706595/183779658-89e336a2-9f2f-4197-be1c-ba0d290fd761.svg)

**Comment by urban-warrior** [comment]
@dlemstra, can you verify this issue under Windows?  We tried the command under Linux and it rendered the image without complaint.

**Comment by urban-warrior** [comment]
The ImageMagick internal renderer first converts SVG to the Magick Vector Graphics (MVG) format and then renders that translation.  You may recall that the ImageMagick renderer is not fully compliant with the SVG standard.  Your SVG file includes features that ImageMagick does not grok so it does not return a proper MVG script.  However, we will investigate.  There may be a simple patch to resolve this issue.  We'll investigate and post here once we have a solution committed.

**Comment by urban-warrior** [comment]
Your image and command renders properly under our Linux systems.  Were you looking for an MVG script as your output file?  If so, MVG must be explicit as in

```
magick msvg:vectorfile_circle.svg mvg:vectorfile.mvg
```

**Comment by oliviermetienne** [comment]
> Your image and command renders properly under our Linux systems. Were you looking for an MVG script as your output file? If so, MVG must be explicit as in
> 
> ```
> magick msvg:vectorfile_circle.svg mvg:vectorfile.mvg
> ```

That's Absolutly fantastic!!! because adding mvg: in mvg:vectorfile.mvg
worked!!! 

Please allow me to explain where the confusion come from:
Use the  svg driver section:
https://imagemagick.org/Usage/draw/#svg_drivers

The following line is mention
"IM generates by converting a SVG directly into a MVG file."
then the following is given:
magick msvg:diagonal.svg diagonal.mvg

I would love to contribute to the update of the the documentation and contribute to IM
Can you update the Documentation or Let me know how I can contribute as I live and Breath IM everyday.


Once again thank you for the invaluable support and sharing your expertise in giving a solution to the issues I have raised.

This is much appreciated

**Comment by urban-warrior** [comment]
We fixed the docs.  Explicitly setting the MVG format was enforced after the docs were first written due to a security issue with the format.
