### ISSUE TITLE
brew install fails

### ISSUE THREAD

**Issue by Louvivien** [ImageMagick/ImageMagick#5432]
### ImageMagick version

latest

### Operating system

MacOS

### Operating system, version and so on

monterey

### Description

Error: imagemagick: Failed to download resource "giflib_bottle_manifest"
The downloaded GitHub Packages manifest was corrupted or modified (it is not valid JSON):

### Steps to Reproduce

brew install imagemagick

**Comment by urban-warrior** [comment]
We do not have any connection to Brew.  You'll need to contact the Brew developers directly for assistance.
