### ISSUE TITLE
morphology thicken

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#5433]
### ImageMagick version

7.1.0-42

### Operating system

Windows

### Operating system, version and so on

v7.1.0-42 on Windows 8.1

### Description

`-morphology Thicken:-1 Skeleton` is creating silly values. For example:

```
magick xc:White xc:Black +append +repage -morphology Thicken:-1 Skeleton txt:

# ImageMagick pixel enumeration: 2,1,0,65535,srgb
0,0: (387414624,387414624,387414624)  #FFFFFFFFFFFF  srgb(591157%,591157%,591157%)
1,0: (0,0,0)  #000000000000  black
```
Tested on v7.1.0-42 on Windows 8.1. The bug seems to be present in v7.0.7-28 and later.

### Steps to Reproduce

As above.

### Images

N/A

**Comment by urban-warrior** [comment]
Add `-clamp` just before the output file to return expected results.  In the mean-time, we'll investigate if the out-of-band values are appropriate for the morphology kernel.

**Comment by snibgo** [comment]
Thanks. If this is mathematically correct, then that is fine, of course.

When I use v7 Q32 HDRI, v7.1.0-20, I get 591156.74%.

With IM v6.9.9-40, Q32, HDRI:

```
Version: ImageMagick 6.9.9-40 Q32 x86_64 2021-02-23 http://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP
Delegates (built-in): bzlib cairo fftw fontconfig fpx freetype jbig jng jpeg lcm
s ltdl lzma pangocairo png rsvg tiff webp wmf x xml zlib

convert xc:White xc:Black +append +repage -morphology Thicken:-1 Skeleton txt:
# ImageMagick pixel enumeration: 2,1,4294967295,srgb
0,0: (8.58993e+09,8.58993e+09,8.58993e+09)  #FFFFFFFFFFFFFFFFFFFFFFFF  srgb(200%,200%,200%)
1,0: (4.29497e+09,4.29497e+09,4.29497e+09)  #FFFFFFFFFFFFFFFFFFFFFFFF  white
```

I don't suppose that 591157% and 200% are both mathematically correct.

**Comment by urban-warrior** [comment]
Add `-define morphology:showKernel=true` to your command-line to view the morphology kernels used by `Thicken:-1`. 

We know that HDRI-enabled ImageMagick supports out of band values.   We also know that CSS colors can exceed 100%.  If they do, the final color is clamped, e.g., rgb(300%,4200%,200%) returns white.

What we're not sure about is your results for Q32.  We get expected results, tested with the latest ImageMagick 7 release:

Q16:

```
# ImageMagick pixel enumeration: 2,1,0,65535,srgb
0,0: (387414624,387414624,387414624)  #FFFFFFFFFFFF  srgb(591157%,591157%,591157%)
1,0: (0,0,0)  #000000000000  black
```

Q32:

```
# ImageMagick pixel enumeration: 2,1,0,4294967295,srgb
0,0: (25389989161192,25389989161192,25389989161192)  #FFFFFFFFFFFFFFFFFFFFFFFF  srgb(591156.74%,591156.74%,591156.74%)
1,0: (0,0,0)  #000000000000000000000000  black
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
