### ISSUE TITLE
main image on github readme is broken

### ISSUE THREAD

**Issue by kylebakerio** [ImageMagick/ImageMagick#5438]
### ImageMagick version

7.0.0.0

### Operating system

Linux

### Operating system, version and so on

linux

### Description

the image at the top of the readme in the root directory of this github project is flawed and shows up as 80% transparent, only the top showing. 

### Steps to Reproduce

Just look at github readme. Also, I've copy pasted that image.

### Images

![image](https://user-images.githubusercontent.com/6391152/184469741-ab84a486-4158-4b01-a6ac-f5f5701b1823.png)

**Comment by dlemstra** [comment]
Looks like an issue on your machine. The image is showing correctly here and hasn't been changed in years.

**Comment by kylebakerio** [comment]
If I view the readme on my android phone, or just copy/paste the link of the image itself to view directly, it also loads incorrectly there.

Did you try a hard refresh? You may have an old cached version that is working...?

**Comment by dlemstra** [comment]
Must be an issue with your device. I cannot reproduce your issue on my device.

**Comment by kylebakerio** [comment]
Ok, I see the exact same behavior from my phone, laptop, and even from my e-reader's browser. here's a screenshot from my ereader, which also runs android 11:
![image](https://user-images.githubusercontent.com/6391152/184545218-c650fe1c-974b-4bea-85df-33fb8f24e1ea.png)

**Comment by kylebakerio** [comment]
Does the iamge pasted in the first comment of this issue show up correct for you? Because that's directly copy/pasted from right-clicking the image and selecting "open image in a new link", too... I see this everywhere. 

The image _does_ show up correctly on https://imagemagick.org/ , it looks like it's supposed to be the same image. That one just actually loads.

**Comment by dlemstra** [comment]
It looks like you are having an issue downloading that image file. I have no idea why this is happening but as I have said before it seems to be something that is related to you. Maybe there is some strange caching happening in your WIFI network that is causing this? I have no idea how to fix your situation and I have checking the readme through various connections and it all seems to work for me.

**Comment by kylebakerio** [comment]
That is super strange, but sure enough, when I visit through a VPN, it loads correctly. Some weird router caching indeed. I'm at an AirBNB, so no insight there.

Sorry for false alarm.
