### ISSUE TITLE
Mogrify fails to convert a set a SVG into PNG

### ISSUE THREAD

**Issue by oliviermetienne** [ImageMagick/ImageMagick#5444]
### ImageMagick version

7.1.0-44

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

In image Magic 7.0.1-22
the following command 
mogrify.exe -format png +antialias -background #000000 -density 96 MSVG:_*.svg
successfully converted a set of png starting with_ (_1 _2 _3 ect...) into their PNG equivalent

But the same command in 7.1.0-44 the  produce corrupted 1Kb png file which I am unable to open
I have tried the following as per the new documentation
Magick mogrify -format png +antialias -background #000000 -density 96 MSVG:_*.svg

But the output png are still corrupted

### Steps to Reproduce

run the following as descibe above and the file provided
mogrify.exe -format png +antialias -background #000000 -density 96 MSVG:_*.svg

### Images

![_6](https://user-images.githubusercontent.com/110706595/184564249-8f28b61e-32bf-4946-8aaf-b1cf315a4395.svg)
![_7](https://user-images.githubusercontent.com/110706595/184564251-1c792c41-14f8-44c3-8604-a09396aa7248.svg)
![_8](https://user-images.githubusercontent.com/110706595/184564253-8c86a73a-ebe9-45b4-8fd3-c30281b0a43c.svg)
![_9](https://user-images.githubusercontent.com/110706595/184564255-c840ae28-f127-4206-9668-a72533cca93e.svg)
![_10](https://user-images.githubusercontent.com/110706595/184564256-6bd5a3da-b2c7-4d5c-8569-e898ff355e8a.svg)
![_1](https://user-images.githubusercontent.com/110706595/184564258-bc1aa225-087d-4ccb-b261-c44a65c517bd.svg)
![_2](https://user-images.githubusercontent.com/110706595/184564259-1f4ecf79-d663-442c-a3a3-f343d876635f.svg)
![_3](https://user-images.githubusercontent.com/110706595/184564262-c4d55e60-812a-4649-a98c-f95255669836.svg)
![_4](https://user-images.githubusercontent.com/110706595/184564265-0d5104f3-6b25-44a8-a9e9-e33d7d300ab4.svg)
![_5](https://user-images.githubusercontent.com/110706595/184564266-6384abff-2979-40d5-8e46-5b72a6fee08d.svg)

**Comment by snibgo** [comment]
> the produce corrupted 1Kb png file which I am unable to open

Please link to the file, or paste it here if it is text.

When I try on IM v7.1.0-42 on Windows 4.1, the output file _1m.png contains:
```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
  "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg width="256" height="256">
<g style="fill:black;fill-opacity:1;stroke:none;stroke-width:1;stroke-opacity:1;fill-rule:nonzero;opacity 1 <defs>
<0Gradient id="linear" x1="0" y1="0" x2="0" y2="0">
  <stop offset="0" stop-color="#000000" />
  <stop offset="0.5" stop-color="#000000" />
  <stop offset="1" stop-color="#000000" />
</0Gradient>
<clipPath id="clip-units">
</svg>
```
Clearly, this is SVG, not PNG. This seems to be a bug.

A workaround would be to use a shell loop to run `magick` on each input file.

**Comment by oliviermetienne** [comment]
> > the produce corrupted 1Kb png file which I am unable to open
> 
> Please link to the file, or paste it here if it is text.
> 
> When I try on IM v7.1.0-42 on Windows 4.1, the output file _1m.png contains:
> 
> ```
> <?xml version="1.0" standalone="no"?>
> <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
>   "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
> <svg width="256" height="256">
> <g style="fill:black;fill-opacity:1;stroke:none;stroke-width:1;stroke-opacity:1;fill-rule:nonzero;opacity 1 <defs>
> <0Gradient id="linear" x1="0" y1="0" x2="0" y2="0">
>   <stop offset="0" stop-color="#000000" />
>   <stop offset="0.5" stop-color="#000000" />
>   <stop offset="1" stop-color="#000000" />
> </0Gradient>
> <clipPath id="clip-units">
> </svg>
> ```
> 
> Clearly, this is SVG, not PNG. This seems to be a bug.
> 

Thank you for looking into this for me and identifying the bug
as request here a copy of the first 5 files generated from the Svg above
Indeed when  open the file in text editor I get the files below indeed with some svg content for all of them,

[_1.txt](https://github.com/ImageMagick/ImageMagick/files/9340313/_1.txt)
[_5.txt](https://github.com/ImageMagick/ImageMagick/files/9340314/_5.txt)
[_4.txt](https://github.com/ImageMagick/ImageMagick/files/9340315/_4.txt)
[_3.txt](https://github.com/ImageMagick/ImageMagick/files/9340316/_3.txt)
[_2.txt](https://github.com/ImageMagick/ImageMagick/files/9340317/_2.txt)

> A workaround would be to use a shell loop to run `magick` on each input file.
Yes thank you very much indeed for your suggestion. 
That's what I did before until I used Mogrify which is blazingly fast!!
But I will do that until the Bug is fixed.

Thank you very much indeed.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by oliviermetienne** [comment]
> Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

Thank you very much indeed.

A s There are no automatic beta builds can you just kicked off a release build as your colleague
 [dlemstra](https://github.com/dlemstra) done for me ?
 here : https://github.com/ImageMagick/ImageMagick/actions/runs/2820908063. ]
 
When this build is completed I will use one of the executables to install a beta version of ImageMagick on my Windows machine and I can run some test it

Thank you very much indeed.

**Comment by oliviermetienne** [comment]
Hello just to confirm that I tried the following command on the latest build and everything is working perfectly:
magick mogrify -format png +antialias -background none -density 96   MSVG:_*.svg

So I closing the call,
Thank you very much indeed for resolving the issue, much appreciated
