### ISSUE TITLE
Cannot convert to 32-bit PSD or PSB

### ISSUE THREAD

**Issue by gregbenz** [ImageMagick/ImageMagick#5447]
### ImageMagick version

7.1.0-45 Q16-HDRI x64 e32676e:20220731

### Operating system

Windows

### Operating system, version and so on

10

### Description

Converting a 32-bit TIF to PSB or PSB always results in a 16-bit file.

### Steps to Reproduce

magick "source.tif" -depth 32 "newFile.psd"

magick "source.tif" -depth 32 "newFile.psb"

**Comment by dlemstra** [comment]
Please don't create this type of issue for a feature requests. Please ask for information in a discussion first and then create a feature request that also contains an image that we can use to implement that feature.

**Comment by gregbenz** [comment]
Sure. It seemed like a bug to me as the result is significantly degraded and there is no warning from the software that the request is not supported.

**Comment by dlemstra** [comment]
I can understand why you think that. We have a lot of things that are not supported and we cannot and will not raise a warning for all these situations.

**Comment by gregbenz** [comment]
Understood. Truly appreciate all the hard work you and others have put into this amazing tool.
