### ISSUE TITLE
Possible bug in -complex magnitude-phase

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#5451]
### ImageMagick version

7.1.0.45 Q16 HDRI

### Operating system

MacOS

### Operating system, version and so on

OSX Monterey

### Description

I believe that -complex magnitude-phase in in error computing the magnitude (if not both). I compare that to direct generation of the magnitude and also to the magnitude computed from the real and imaginary components.

### Steps to Reproduce

Input:

![square31](https://user-images.githubusercontent.com/13458218/185019065-90637b63-3992-4cd6-b5c9-d07b27d2ea46.png)

Direct magnitude (correct):
`magick square31.png -define fourier:normalize=inverse -fft -delete 1 mag1.png`

![mag1](https://user-images.githubusercontent.com/13458218/185019169-9d426d84-d35a-4258-b5d7-8b64987d7440.png)

-complex magnitude-phase (incorrect):
`magick square31.png -define fourier:normalize=inverse +fft -complex magnitude-phase -delete 1 mag2.png`

![mag2](https://user-images.githubusercontent.com/13458218/185019313-22e88e04-4197-422d-99f8-dd83f77c8c50.png)

Computed magnitude from real and imaginary components (correct):
```
magick square31.png -define fourier:normalize=inverse +fft -write mpr:fft -delete 0,1 \
\( mpr:fft -complex conjugate \) mpr:fft -complex multiply -evaluate pow 0.5 -delete 1 mag3.png 
```
![mag3](https://user-images.githubusercontent.com/13458218/185019399-a7862e19-4e91-4521-a081-7b9a2cffa3aa.png)

Although the incorrect one from -complex looks better, the other two work properly in my FFT scripts and the one from -complex does not.  Also note that these are computed in HDRI and that may not be properly taken into account in -complex. Or perhaps there is incorrect normalization. Just some thoughts.

The code in Fourier.c say:

>           case MagnitudePhaseComplexOperator:
>           {
>             Cr[i]=sqrt(QuantumScale*Ar[i]*Ar[i]+QuantumScale*Ai[i]*Ai[i]);
>             Ci[i]=atan2((double) Ai[i],(double) Ar[i])/(2.0*MagickPI)+0.5;
>             break;
>           }
> 

So when I do it manually, I get the correct result:

```
magick square31.png -define fourier:normalize=inverse +fft -write mpr:fft -delete 0,1 \
\( mpr:fft[0] mpr:fft[0] -define compose:clamp=false -compose multiply -composite \) \
\( mpr:fft[1] mpr:fft[1] -define compose:clamp=false -compose multiply -composite \) \
 -define compose:clamp=false -compose plus -composite \
-evaluate pow 0.5 -delete 1 mag4.png 

```

![mag4](https://user-images.githubusercontent.com/13458218/185026844-dfefadf3-ca92-4bc7-9380-10e4b6e0766d.png)

**So what am I missing!?**

### Images

see above

**Comment by fmw42** [comment]
I think I know how to generate the wrong result. It is equivalent the forward normalized -fft scaled by 255:

`magick square31.png -define fourier:normalize=forward -fft -delete 1 -evaluate multiply 255 mag5.png`

![mag5](https://user-images.githubusercontent.com/13458218/185027595-b921c49f-6c11-471f-903b-ef91bc35a480.png)

I believe we made -complex magnitude-phase that way to reproduce what one gets from the default -fft magnitude.

But perhaps we need to do it both ways, depending upon what Fourier normalization is used.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

The issue was normalization.

**Comment by fmw42** [comment]
Can we have it both ways? We need it one way (as current) to be able to reproduce -fft results and the other way to support the +fft or inverse Fourier normalization result. I am not sure whether it is best to have a define or key off of the + or - fft or Fourier normalization. Lets talk about it.

**Comment by urban-warrior** [comment]
The normalization was not done properly, as such, its a bug.  With the bug fix, if you want to produce different results, we can introduce a define.

**Comment by fmw42** [comment]
So do you want me to check the bug fix when ready before adding the define?

**Comment by urban-warrior** [comment]
Verify that each of the complex option methods are working properly.  Once confirmed, you can propose alt versions enabled by a define option.

**Comment by fmw42** [comment]
FYI. It was not wrong. There was no normalization error. It was normalized to reproduce the -fft magnitude and phase result (limited to display range). My original report was that I was working in HDRI and needed the unnormalized result for a script. That is why I think it would be useful to have it both ways with a define. However, it you only want one way, then the unnormalized result would be best so that it works with +fft.

**Comment by fmw42** [comment]
Do you want me to check those options in the current release or after your bug fix?

**Comment by fmw42** [comment]
Cristy,

All options seem to be working as expected

Here are my tests if you have interest. The problem I was having when I called you was that I forgot to divide by 257 to get from 16-bits to the 8-bit values I had supplied.


im7beta magick -size 2x2 xc:"gray(2)" -evaluate divide 257  real.txt
im7beta magick -size 2x2 xc:"gray(1)" -evaluate divide 257  imag.txt
im7beta magick identify -verbose real.txt
2
im7beta magick identify -verbose imag.txt
1

im7beta magick real.txt imag.txt -complex conjugate conj.pfm
im7beta magick identify -verbose conj.pfm
2 -1j

im7beta magick conj.pfm conj.pfm -complex add conj_add.pfm
im7beta magick identify -verbose conj_add.pfm
4 -2j

im7beta magick conj.pfm conj.pfm -complex subtract conj_subt.pfm
im7beta magick identify -verbose conj_subt.pfm
0 0j

im7beta magick conj.pfm conj.pfm -complex multiply -evaluate multiply 65535 conj_mult.pfm
im7beta magick identify -verbose conj_mult.pfm
3-4j

im7beta magick conj.pfm conj.pfm -complex divide -evaluate divide 65535 conj_div.pfm
im7beta magick identify -verbose conj_div.pfm
1+0j

im7beta magick square31.png -define fourier:normalize=inverse +fft -complex magnitude-phase mag-phase.pfm
im7beta magick square31.png -define fourier:normalize=inverse +fft -complex magnitude-phase -complex real-imaginary -complex magnitude-phase mag-phase2.pfm
im7beta magick animate -delay 50 mag-phase.pfm[0] mag-phase.pfm[1]
im7beta magick animate -delay 50 mag-phase2.pfm[0] mag-phase2.pfm[1]
im7beta magick animate -delay 50 mag-phase.pfm[0] mag-phase2.pfm[0]
im7beta magick animate -delay 50 mag-phase.pfm[1] mag-phase2.pfm[1]
im7beta magick compare -metric rmse mag-phase.pfm[0] mag-phase2.pfm[0] null:
0.00507202 (7.7394e-08)
im7beta magick compare -metric rmse mag-phase.pfm[1] mag-phase2.pfm[1] null:
3.37699e-05 (5.15296e-10)

im7beta magick real.txt imag.txt -define fourier:normalize=inverse +fft -complex magnitude-phase -complex real-imaginary re-im2.pfm
im7beta magick compare -metric rmse real.txt re-im2.pfm[0] null:
3.4641 (5.28588e-05)
im7beta magick compare -metric rmse imag.txt re-im2.pfm[1] null:
1 (1.5259e-05)
