### ISSUE TITLE
tagging

### ISSUE THREAD

**Issue by kloczek** [ImageMagick/ImageMagick#5455]
### Is your feature request related to a problem? Please describe.

IMO it would be good back to tagging without slashes only because 

### Describe the solution you'd like

Use version git tags without slashes and only with dots.

### Describe alternatives you've considered

N/A

### Additional context

it makes packaging easier (none of the PM software accepts `-` as part of the versio string and it makes necessary to replace that on packaging).

**Comment by dlemstra** [comment]
We have never made tags without the `-` and the version number that our application uses also contains this slash. Changing this might break other applications so we cannot change this.

**Comment by kloczek** [comment]
Acrtualluy you made that two times
https://github.com/ImageMagick/ImageMagick/releases/tag/7.1.0.43
https://github.com/ImageMagick/ImageMagick/releases/tag/7.1.0.42

What kind of application may be broken by this? 🤔

**Comment by dlemstra** [comment]
It looks like I made a mistake then that I should fix later. You apparently want to use our tag so I think it would be safe to assume that other people already do this. We have been using this type of version number for a lot of years now and I don't see a good reason why we need to change it now.

**Comment by kloczek** [comment]
If no one complained about tose tags withou tdash reall .. it woud be better to witch to tagging without dashes (please).
I geve you reason for that: reduce overhead on packaging layer (for peeople like me). With tag matching to version it would be as well easier to detect new version withou treating ImageMagick special way.
