### ISSUE TITLE
Error on convert calling

### ISSUE THREAD

**Issue by mikhailushka** [ImageMagick/ImageMagick#5460]
### ImageMagick version

7.1.0.46

### Operating system

Linux

### Operating system, version and so on

CentOS Linux release 7.4.1708

### Description

After updating ImageMagick to version 7.1.0.46, we encountered a problem in the stage environment.

When executing a command like:

```
convert -background none -fill '#ffffff' -size '450x120' -font './public/fonts/Spectral-Medium.ttf' -geometry '+320-130' -gravity 'north' caption:'\n some text' '/tmp/262f02b78c8ac2118c8a8c18d79a10da20220818-29386-1q6rj4h[0]'
```

We get an error:

```
convert: symbol lookup error: /lib64/libMagickCore-7.Q16HDRI.so.10: undefined symbol: FT_Set_Default_Properties
```

with 127 exit status.

Version 7.1.0-36 does not have this problem.

Maybe something related to https://github.com/ImageMagick/ImageMagick/issues/5372 🤔 

### Steps to Reproduce

In our case, it is enough to go to the staged machine and execute the command:

```
convert -background none -fill '#ffffff' -size '450x120' -font './public/fonts/Spectral-Medium.ttf' -geometry '+320-130' -gravity 'north' caption:'\n some text' '/tmp/262f02b78c8ac2118c8a8c18d79a10da20220818-29386-1q6rj4h[0]'
```

**Comment by fmw42** [comment]
Your output has no suffix. Might that have something to do with your issue?

**Comment by dlemstra** [comment]
Which version of freetype are you using. You should be using at least version 2.8

**Comment by mirror222** [comment]
same issue, I have the freetype-2.8-14.el7_9.1.x86_64 installed on my centos 7.6.

any reply will highly appreciated. :)
