### ISSUE TITLE
-defines documentation

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#5490]
### ImageMagick version

7

### Operating system

Windows

### Operating system, version and so on

N/A

### Description

https://imagemagick.org/script/defines.php has three typos: "ffpmeg" should be "ffmpeg".

### Steps to Reproduce

N/A

**Comment by dlemstra** [comment]
Thanks, just pushed a patch to fix this. Will take a couple days before this is updated on the website.
