### ISSUE TITLE
PNG gets bigger after ImageMagick conversion

### ISSUE THREAD

**Issue by jiuzhoucui** [ImageMagick/ImageMagick#5491]
### Is your feature request related to a problem? Please describe.

# Problem
* The original image is 370K, and after ImageMagick conversion, it becomes more than 980K.

* Command

```
convert origin.png dest.png
```

* some diff
![image](https://user-images.githubusercontent.com/102148284/186569672-4d04a667-aa7b-410c-92d8-156ac6447308.png)

* origin have only one IDAT, but dest have many.
![image](https://user-images.githubusercontent.com/102148284/186569871-a8bf29c7-1648-49bd-b278-9fd8b9c7c51b.png)

* get origin.png
![origin](https://user-images.githubusercontent.com/102148284/186569199-4aa5bda8-2c61-434d-8165-b73bb8600f43.png)

### Describe the solution you'd like

* Can ImageMagick convert png without changing the size?
* Please explain the above phenomenon, thanks.

**Comment by fmw42** [comment]
Post your original png and your IM version and platform/OS

**Comment by jiuzhoucui** [comment]
original png is in the origin issue.

Version: ImageMagick 7.0.11-6 Q16 x86_64 2021-04-03 https://imagemagick.org

OS: Both in Linux and Mac.

**Comment by Meet909** [comment]
Maybe it's an OS or IM dependency problem?
On the first OS I have the same problem as OP (size increased from **300kB to 1,2MB**), IM version ImageMagick 6.9.9-33 Q16 x86_64.
The second one OS made conversion more properly (size increased from **300kB to380 kB**). The same IM version.

**Comment by dlemstra** [comment]
I can also reproduce this issue on Windows. Not sure yet that is causing this.

**Comment by snibgo** [comment]
For me, v7.1.0-42 on Windows 8.1, the command ...
```
magick sbucks.png x.png
```
... where sbucks.png is the OP input (377705 bytes) makes an output 985806 bytes.

Exiftool says the input uses an 8-bit pallete. The output has three channels (RGB) plus alpha. So, ignoring compression, the output would be four times the size of the input.

IM does have an annoying habit of adding an alpha channel to fully-opaque images. Perhaps we need a new operation to remove the alpha channel if it is fully opaque.

sbucks.png has 256 unique colours.

This fails:
```
magick sbucks.png -alpha off -colors 256 -type palette x.png

magick: Valid palette required for paletted images `x.png' @ error/png.c/MagickPNGErrorHandler/1716.
```

This succeeds:
```
magick sbucks.png -alpha off -colors 255 -type palette x.png
```
x.png is now 332259 bytes, which is smaller than the input.

I don't know why palette PNG files can't cope with 256 colors.

**Comment by fmw42** [comment]
This likely happens because this is a palette image with alpha where one color is used to specify the alpha. So if you disable alpha, you remove that one color from use and are now left with one less color or in this case from 256 to 255 colors.

**Comment by snibgo** [comment]
Yes, but the input file has no alpha, 256 unique colours, with palette. So the problem isn't the PNG format, but a restriction within IM.

**Comment by fmw42** [comment]
Sorry, but you wrote

>  Exiftool says the input uses an 8-bit pallete. The output has three channels (RGB) plus alpha. So, ignoring compression, the output would be four times the size of the input.
> 
> IM does have an annoying habit of adding an alpha channel to fully-opaque images. Perhaps we need a new operation to remove the alpha channel if it is fully opaque.magick sbucks.png -alpha off -colors 255 -type palette x.png
> 

So I thought that meant the file had transparency.

**Comment by snibgo** [comment]
The input file that I have called sbucks.png has transparency. One of the 256 entries in the palette is (90,89,102,254).

IM reads the file with no problem. But IM can save the file in palette format only by reducing the image to "`-colors 255`". I don't understand why this reduction is needed.

**Comment by jiuzhoucui** [comment]
@dlemstra Do you have plan to fix this case?

**Comment by dlemstra** [comment]
I havent made time to investigate this yet.

**Comment by dlemstra** [comment]
I just pushed some patches to resolve this issue. The image is still slightly larger but you can now convert into another png without the requirement to do a reduction of the number of colors.
