### ISSUE TITLE
raw image property unit error

### ISSUE THREAD

**Issue by zmdyy0318** [ImageMagick/ImageMagick#5492]
### ImageMagick version

7.1.0-46

### Operating system

Other (enter below)

### Operating system, version and so on

any

### Description

dng:focal.length unit is "mm" not "m"
![image](https://user-images.githubusercontent.com/16699676/186858352-31983036-47e8-4e94-b0d0-07af10d6fdbd.png)

### Steps to Reproduce

run code
coders/dng.c
`  (void) FormatImageProperty(image,"dng:focal.length","%0.1f m",
    raw_info->other.focal_len);`
fix to
`  (void) FormatImageProperty(image,"dng:focal.length","%0.1f mm",
    raw_info->other.focal_len);`

**Comment by dlemstra** [comment]
Would you be willing to open a pull request for this? Or would you like us to fix this?

**Comment by urban-warrior** [comment]
We encourage pull requests, however, for a one-line patch, we'll just apply it manually.
