### ISSUE TITLE
When I Use ImageMagick to Open Chinese Named File, it crashed

### ISSUE THREAD

**Issue by flowerlove** [ImageMagick/ImageMagick#5495]
### ImageMagick version

7.1.0-Q16

### Operating system

Windows

### Operating system, version and so on

windows 10

### Description

I want to konw, if the lib support to open chinese path file

### Steps to Reproduce

when the path include chinese or the filename include chinese, it will crash when i load the image

### Images

![测试图片](https://user-images.githubusercontent.com/10022404/186952415-6eee1618-53b6-41ac-868b-e9b4642c11be.png)

**Comment by dlemstra** [comment]
What is the exact version of ImageMagick that you are using? I cannot reproduce your issue with that latest version of ImageMagick on Windows.
