### ISSUE TITLE
ImagickException: no decode delegate for this image format @ error/constitute.c/ReadImage/741

### ISSUE THREAD

**Issue by kefahB** [ImageMagick/ImageMagick#5503]
### ImageMagick version

3.7.0

### Operating system

MacOS

### Operating system, version and so on

Silicon M1 pro

### Description

Hi,

I tru to upload an png with php using this :  

It throw 
```ts
Uncaught ImagickException: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741 in /Users/.../Sites/.../vendor/intervention/image/src/Intervention/Image/Imagick/Decoder.php:25

Next Intervention\Image\Exception\NotReadableException: Unable to read image from path (/private/tmp/php/phpgsejr3). in /Users/.../Sites/.../vendor/intervention/image/src/Intervention/Image/Imagick/Decoder.php:29


```

### Steps to Reproduce

```php

$small = new ImageManager(['driver' => 'imagick']);
            $saved = $small->make($_FILES['fileToUpload']['tmp_name'])
                ->resize(50, 50)
                ->save($imagesPaths . "/" . $fileName);

```

**Comment by snibgo** [comment]
The question is about IMagick, not ImageMagick. IMagick is an interface between ImageMagick and PHP. I don't know about IMagick or PHP.

> Unable to read image from path (/private/tmp/php/phpgsejr3).

This suggests you were trying to read a file named "phpgsejr3". Is that an image file? Can ImageMagick read it from the command line? Perhaps you can zip the file and upload it here.

**Comment by kefahB** [comment]
Thanks for your reply, the problem come from ios !
