### ISSUE TITLE
Possible bugs -metric PSNR

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#5504]
### ImageMagick version

7.1.0-47 Q16-HDRI

### Operating system

MacOS

### Operating system, version and so on

OSX Monterey

### Description

There are two issues.

1) The Imagemagick code  at line 1254 in compare.c says the formula is:

> distortion[i]=10.0*MagickLog10(1.0)-10.0*MagickLog10(distortion[i])

However, according to Wikipedia at https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio, it should be

`distortion[I]=20.0*MagickLog10(1.0)-10.0*MagickLog10(distortion[I])`

(where the input distortion(I) is just mse)

Furthermore, log10(1)=0, so to simplify, the formula should be just

`distortion[I]=-10.0*MagickLog10(distortion[I])`

_So the answer Imagemagick gets is correct, it just wastes computations._

2) Using the following images:

![logo](https://user-images.githubusercontent.com/13458218/187279137-4cd1789d-ef8f-496b-9633-1144e3793c32.png)

![hat_124_124_417_44_white](https://user-images.githubusercontent.com/13458218/187279177-8f6fa936-68de-48c7-8025-59cb53bcedb4.png)

I get:

```
$ magick compare -metric psnr -subimage-search -dissimilarity-threshold 1 logo.png hat_124_124_417_44_white.png null:
**compare: images too dissimilar `logo.png' @ error/compare.c/CompareImagesCommand/1169.**
```

whereas for -metric mse, it works fine:

```
$ magick compare -metric mse -subimage-search -dissimilarity-threshold 1 logo.png hat_124_124_417_44_white.png null:
0 (0) @ 417,44
```

### Steps to Reproduce

See above

### Images

See above

**Comment by urban-warrior** [comment]
The dissimilarity threshold defaults to 1.0.  PSNR is not normalized, in your example, it returns 4.42909.  Since that distortion exceeds the dissimilarity threshold, it throws an exception.  You can set the dissimilarity threshold with the `dissimilarity-threshold` option.  Another option would be to normalize the PSNR distortion.  Does that even make sense mathematically?

**Comment by fmw42** [comment]
With respect to the -dissimilarity-threshold, that was indeed my oversight. So if I increase it to 100,

`magick compare -metric psnr -subimage-search -dissimilarity-threshold 100 logo.png hat_124_124_417_44_white.png null:`
4.42909 @ 272,246

It works without complaint, **but does not give the correct locations, which should be 417,44**.

I would expect the same location as resulted from -metric mse,

`magick compare -metric mse -subimage-search -dissimilarity-threshold 1 logo.png hat_124_124_417_44_white.png null:`
0 (0) @ 417,44

**Comment by urban-warrior** [comment]
It looks like PSNR might not be the best metric for similarity search or the algorithm is not correct. 4.42909 @ 272,246 is the minimum PSNR.  The algorithm gets the mean squared distortion first then computes -10.0*log10(distortion).  Can you try the mean-square distortion and see if it is returning sane results?
