### ISSUE TITLE
Aborted (core dumped) when converting large .psb to .png

### ISSUE THREAD

**Issue by sloganking** [ImageMagick/ImageMagick#5509]
### ImageMagick version

7.1.0-47

### Operating system

Linux

### Operating system, version and so on

Arch Linux. Kernel: 5.15.63-1-lts

### Description

running ``magick convert androm.psb androm.png`` fails after a couple minutes with the message ``Aborted (core dumped)``

### Steps to Reproduce

- Goto https://esahubble.org/images/heic1502a/ and download the 4.3 GB [Fullsize Original](https://esahubble.org/media/archives/images/original/heic1502a.psb)
- Rename the downloaded file to ``androm.psb``
- Open a terminal and run ``magick convert androm.psb androm.png``
- Wait a few minutes until error: ``Aborted (core dumped)``

**Comment by snibgo** [comment]
Those files are too large for me to download. How many pixels do they have? How much memory does your computer have? I suspect you are running out of memory.

What happens if you save to MIFF or TIFF format instead of PNG?

**Comment by fmw42** [comment]
See https://imagemagick.org/script/architecture.php#tera-pixel and https://imagemagick.org/script/security-policy.php

**Comment by fmw42** [comment]
What do you get from

`magick -list resource`

**Comment by snibgo** [comment]
IM needs to store the entire image in memory. If not enough RAM is available, it will use disk.

69536 * 22230 pixels, assuming three channels, 4 bytes per channel, needs 18.5 GB of memory.

In your case, IM may use all the memory for pixels, with no memory left to reorganise the data for writing to a file.

You might try "-limit memory 1MB -limit map 1MB" so RAM is not used for pixels, and is available for writing to files.

**Comment by sloganking** [comment]
@snibgo 

```
magick convert androm.psb androm.png -limit memory 1MB -limit map 1MB
```
Still returns ``Aborted (core dumped)`` after one minute.

**Comment by sloganking** [comment]
> What do you get from
> 
> `magick -list resource`

```
Resource limits:
  Width: 461.169PP
  Height: 461.169PP
  Area: 33.4278GP
  List length: unlimited
  Memory: 15.566GiB
  Map: 31.1321GiB
  Disk: unlimited
  File: 768
  Thread: 8
  Throttle: 0
  Time: unlimited
  ```

**Comment by sloganking** [comment]
Per https://imagemagick.org/script/security-policy.php

> If any one image has a width or height that exceeds 8192 pixels or if an image sequence exceeds 32 frames, an exception is thrown and processing stops.

I suspect this might be the issue. I will look into editing this configuration later. If this is the issue. It would be nice if the error message stated what the problem was and maybe how to fix it, instead of just ``Aborted (core dumped)``.

**Comment by snibgo** [comment]
> magick convert androm.psb androm.png -limit memory 1MB -limit map 1MB

That would limit the memory (RAM) usage *after* reading the PSB and writing the PNG. I suggest doing it *before* reading and writing:
```
magick -limit memory 1MB -limit map 1MB androm.psb androm.png
```

Ideally, IM should never abort, with a dumped core. A developer may look at this.

**Comment by sloganking** [comment]
@snibgo 

> ```
> magick -limit memory 1MB -limit map 1MB androm.psb androm.png
> ```


That makes sense. I find it a little intuitive that adding flags causes that command to no longer have the ``convert`` keyword in it. But here is the output after running that command.

```
magick: unable to write pixel cache '/tmp/magick-E7ZRpp5KR43IBjIrUB7KkRkTbZ2wqjcI': No space left on device @ error/cache.c/WritePixelCachePixels/5851.
```

**Comment by snibgo** [comment]
`magick convert` will read the command assuming IM v6 syntax. Plain `magick` will assume v7 syntax. V7 is better than v6. I suggest that `magick convert` should *only* be used when you know there is a good reason for using v6 syntax, perhaps for compatibility of old scripts. For new work, I suggest v6 syntax should *never* be used.

However, V6 or V7 should make no difference to your problem.

> magick: unable to write pixel cache '/tmp/magick-E7ZRpp5KR43IBjIrUB7KkRkTbZ2wqjcI': No space left on device

This suggests that IM was not able to create a large file in `/tmp`. You say you have plenty of free disk space, but perhaps there is a quota limit on /tmp. Try creating a large file in `/tmp` with some other utility.

**Comment by fmw42** [comment]
>  I find it a little intuitive that adding flags causes that command to no longer have the convert keyword in it

It is not the flags. Imagemagick 7 is new and uses magick **in place of** convert. But for all the other tools such as mogrify and identify and montage, etc, they are still old IM 6 technology and must use magick as a preface to those commands to run them under IM 7.

**Comment by sloganking** [comment]
@snibgo my file explorer (unprivileged) lets me manually copy a 4.6GB file to ``/tmp``. and ``cp androm.psb /tmp`` works as well.

Should I try a larger file, or do you think that's sufficient? Before that operation, ``/tmp`` was only using ``50MB``

**Comment by snibgo** [comment]
> Should I try a larger file ...?

See my calculation above:

> 69536 * 22230 pixels, assuming three channels, 4 bytes per channel, needs 18.5 GB of memory.

**Comment by sloganking** [comment]
``cp large_file.txt /tmp`` still worked fine. But moving a ``57.3`` GB file with my file explorer fails with the error

![](https://i.imgur.com/BrDWiEB.png)

57.3 - 45.4 = 11.9

So it looks like ``11.9GB`` is the limit for my ``/tmp`` directory right now. I take it that's on me to fix and report back with another conversion attempt. 

Seems a little weird that IM's capabilities are limited by the system's ``/tmp`` file size limit. I wonder it would be desirable for that to be fixed by IM somehow.

**Comment by sloganking** [comment]
I increased ``/tmp``'s size limit to 25GB. And upon attempting conversion with,

```
magick -limit memory 1MB -limit map 1MB androm.psb androm.png
```

The desktop freezes fore a few seconds before all open terminal windows crash. No error message. The terminal windows themselves just disappear.

the last frame from htop before the terminal displaying it crashes, shows all memory becoming purple. I'm having trouble finding what purple means, but am looking into it.

![](https://i.imgur.com/FgpsD1m.png)

**Comment by snibgo** [comment]
> Seems a little weird that IM's capabilities are limited by the system's /tmp file size limit. I wonder it would be desirable for that to be fixed by IM somehow.

You can tell IM to use somewhere else as its temporary directory. You can do this for just one IM command (`-define registry:temporary-path=/data/tmp`), or for all IM commands (see https://imagemagick.org/script/security-policy.php).

**Comment by fmw42** [comment]
Check your policy.xml file to see where Imagemagick is putting your temporary files.

Either:

`magick -list policy
`
if you do not have a custom one

or on Unix

`cat /usr/local/etc/ImageMagick-7/policy.xml`

**Comment by sloganking** [comment]
```
magick -limit memory 1MB -limit map 1MB -define registry:temporary-path=/home/username/temp androm.psb androm.png
```

Finally worked. It took between 10 minutes and 90 minutes. I am not sure exactly how long. I did not edit the security policy. Perhaps the docs that stated the default security policy would not allow any images with any dimension over ``8192`` pixels, is out of date.

> Ideally, IM should never abort, with a dumped core. A developer may look at this.

This issue may want to be kept open to investigate why IM crashes with a core dump. Though I've solved my immediate problem for now.

**Comment by sloganking** [comment]
@fmw42 

For reference. Here is the result of running ``magick -list policy``

```
Path: /etc/ImageMagick-7/policy.xml
  Policy: Undefined
    rights: None 

Path: [built-in]
  Policy: Undefined
    rights: None
```

**Comment by snibgo** [comment]
> Perhaps the docs that stated the default security policy would not allow any images with any dimension over 8192 pixels, is out of date.

No. The page https://imagemagick.org/script/security-policy.php shows an example policy.xml, which includes:
```
  <policy domain="resource" name="width" value="8KP"/>
```
The page then explains the example, including:
> With this policy, ... If any one image has a width or height that exceeds 8192 pixels ... an exception is thrown and processing stops.

**Comment by fmw42** [comment]
As I said, you must have a private policy in addition to the one in /etc.  List that one as I did above in my second command

cat /usr/local/etc/ImageMagick-7/policy.xml

**Comment by urban-warrior** [comment]
This command converted the image for us without complaint:

```
$ identify -monitor -limit memory 2GiB -limit map 4GiB -define registry:temporary-path=/opt/tmp heic1502a.psb
load images[heic1502a.psb]: 2 of 3, 100% complete
heic1502a.psb PSB 69536x22230 69536x22230+0+0 8-bit sRGB 4.3189GiB 107.000u 2:20.064

$ magick -monitor -limit memory 2GiB -limit map 4GiB -define registry:temporary-path=/opt/tmp heic1502a.psb heic1502a.png
load images[heic1502a.psb]: 2 of 3, 100% complete
save image[heic1502a.png]: 22229 of 22230, 100% complete
```

Note, we cached the pixels to a disk with plenty of free space @ `/opt/tmp`.  In addition, we did not have any width/height constraints in the security policy.

**Comment by sloganking** [comment]
> As I said, you must have a private policy in addition to the one in /etc. List that one as I did above in my second command
> 
> cat /usr/local/etc/ImageMagick-7/policy.xml

@fmw42 Is this responding to me? I have no file in ``/usr/local/etc/ImageMagick-7/policy.xml`` However I do see a ``/etc/ImageMagick-7/policy.xml``

Here are it's contents (I changed filetype to a text file go GitHub would accept it)
[policy.txt](https://github.com/ImageMagick/ImageMagick/files/9481504/policy.txt)

**Comment by fmw42** [comment]
It is located in different places on different systems. That is the correct file.  Give it a try editing it and saving it and see if your changes helped.
