### ISSUE TITLE
A real Ai Upscaler/Enlarger (CPU based)

### ISSUE THREAD

**Issue by Daijobou** [ImageMagick/ImageMagick#5511]
### Is your feature request related to a problem? Please describe.

Enlarge images (like 2 times) is with ImageMagick blurred and in most cases (for me) not really usable. Its unfortunately true for most graphics tools. GIMP is also a disaster here. ImageMagick is a great tool, I love it, however shouldn't it also be able to enlarge images in a modern way?

### Describe the solution you'd like

There exists tools since many years that do this work excellent. The most avatars in communities have cartoon-look, so here open source ai upscaler specialized for cartoons as example:
https://github.com/nagadomi/waifu2x
https://github.com/bloc97/Anime4K 

Unfortunately this sources are poorly maintained or stalled. I would like, that ImageMagick add a CPU based (for webserver) AI Upscaler as new function.  For me, it's not a problem that this function is much slower.

However I understand when this is not what ImageMagick want to offer in this lib. I just wanted to throw it in, because for webserver there exists not such a lib (not that I know it) and ImageMagick would be here a **_must have_** for anyone looking for something like that. ;)

**Comment by PeterBBBBB** [comment]
There is a command line tool, xbrzscale, that is easier to build and use than Waifu2x.
Does scaling up to x6 in one pass, similar quality to Waifu2x
