### ISSUE TITLE
Thats a issue with github to google (wizard utf8)

### ISSUE THREAD

**Issue by Daijobou** [ImageMagick/ImageMagick#5512]
### ImageMagick version

*

### Operating system

Windows

### Operating system, version and so on

*

### Description

In HTML here on the page is
`<title>ImageMagick/ImageMagick: 🧙‍♂️ ImageMagick 7</title>`
I can see a Wizard utf8 icon after ":"

In Google its look this way
<img width="322" alt="image" src="https://user-images.githubusercontent.com/260343/187896756-1671925c-785d-4c2e-b158-27f985e3bf7e.png">

Thats strange to see a male icon here (instead the wizard icon). Private club for old white mens? Thats only meant in a joking way. ;)

### Steps to Reproduce

see description

### Images

see description

**Comment by dlemstra** [comment]
That is apparently how google decides to render that UTF8 character. Could be an issue with GitHub or how Google handles that. There is not much we can do about it.
