### ISSUE TITLE
Tiff RGB RGBA read issue

### ISSUE THREAD

**Issue by dharrison007** [ImageMagick/ImageMagick#5521]
### ImageMagick version

7.1.0-48 beta Q8-HDRI x64 81a8bc4:20220828

### Operating system

Windows

### Operating system, version and so on

Windows 10 (latest released build)

### Description

Issue reading Tiff files produced in an earlier version of ImageMagick (6.?).
The tiff file in question is multipage tiff of a bank statement (two pages/ images), I have many of them and need to process using ImageMagick Magick++ to clean up the images prior to OCR.
Windows Photo Viewer displays the image perfectly fine; however IMDisplay, and Magick++, does not. 
The image is slightly compressed horizontally with a blank right hand margin (alpha), the colour is washed with pixel's missing. 
I am unable to provide examples due to privacy issues, however I attach the identify -verbose output.
I am no expert but something that jumped out at me was the conflicting :
Type: TrueColorAlpha
Base type: TrueColor

My thoughts:the image magick tiff reading module may be using the incorrect type when reading the data?
[Tiff-Corruption-IMIdentify.txt](https://github.com/ImageMagick/ImageMagick/files/9478092/Tiff-Corruption-IMIdentify.txt)

### Steps to Reproduce

Apologies, but I am unsure how to recreate the problematic tiff, however the tiff file renders perfectly with Windows Photo Viewer and does not with current ImageMagick release (IMDisplay, Magick++).

**Comment by dharrison007** [comment]
Any thoughts/ answers on how to idenitfy and correct or workaround the problem would be greatly appreciated.

Kind regards.

**Comment by dharrison007** [comment]
I'm not sure if it helps but I attach two screen shots that have been redacted to show the the display issue.  please ignore the black boxes this is the redaction to maintain privacy.  Obviously they are not the original tiff image, andtherefore are only purley to show the visual issue.
![Capture 1 redacted](https://user-images.githubusercontent.com/11913659/188160164-9d31848f-f1ea-46ca-99bc-0b565ae1a8ea.png)
![Capture 2 redacted](https://user-images.githubusercontent.com/11913659/188160183-7ef9a676-89f8-499d-9dfb-89cdee06818f.PNG)

**Comment by dharrison007** [comment]
If I recall the problematic tiff was created by extracting images from a pdf file (containing embedded jpg images), then using a version of ImageMagick Magick++ to create the tiff from a vector of Magick::Images. The version of Magick ++ used for this was an older version most likely version 6.?

**Comment by snibgo** [comment]
Your images have an alpha channel with statistics that are roughly equal to the stats of the RGB channels. So I suspect the dark areas are transparent, where the white areas are opaque. Gimp will show transparency as chequers. I don't know why scanned images would have an alpha channel (especially if they were JPEGs). Perhaps they have been processed in  some way. You might try:
```
magick "Problematic image.tiff" -alpha off x1.tiff
```
What do x1.tiff images look like? Are they better?

Or:
```
magick "Problematic image.tiff" -background Black -laters Flatten x1.tiff
```
Better? Or try flattening against White.

I also see your IM is Q8 with HDRI. This is unusual. I expect that writing to integer formats will always have depth 8.

**Comment by dharrison007** [comment]
Unfortunately the same result as before for the 1st suggestion and the 2nd suggestion is still processing... I think it is stuck.. no error or return at command prompt?. IM isn't 'reading' the data correctly (or in a way that works). I know 'reading' is the issue as I have dumped the image straight after reading it, using Magick++ interface. I am sure you get this a lot (people accusing IM being at fault, when its not), however I believe IM has a bug in how the 'reading' of a tiff is taking place.  I believe the issue is it isn't using the correct image 'type' setting (for this particular scenario).
Type: TrueColorAlpha
Base type: TrueColor
Given other (Windows Photo Viewer) display software appears to be able to 'read' and display it correctly.
Is there a way to force the 'reading' settings of magick prior to the actually read? Such as force IM to 'read' the file images with or without Alpha channel?
Also I am unclear what the above 'Type' settign actually resolves to in as core settings. It looks like an amalgamation of:
The number of channels
The depth of each channel

e.g.
TrueColourAlpha is 4 channels with 256bit depth?
TrueColor is 3 channels with 256bit depth?

My thoughts were the image is being read using the incorrect setting (perhaps being read as 3 channels when the  encoding is 4) or vice versa?

Your help is much appreciated.

Kind regards,

Dan

**Comment by dharrison007** [comment]
Also you correctly identified the image had been processed.  It has, as I mentioned before the processing steps some years ago was:
Scanned paper document using Fujitsu fi-6240i scanner using ScanPro software, to create a pdf.
Used Image Magick (Magick++) ver 6.? with PoDoFo to extract image from PDF and save as a Multipage Tiff (using vector of Magick::Image) and Magick::writeImages(vector start, vector end, filename).
Now using IM ver 7 to open (whch is failing due to this issue).

Kind regards

**Comment by dharrison007** [comment]
The second suggestion is not returning. Please see current view of resources on my computer.. 
![image](https://user-images.githubusercontent.com/11913659/188263922-8698404c-c410-46f1-917d-969d545d66ca.png)
![image](https://user-images.githubusercontent.com/11913659/188263972-8cd6195d-a204-421a-99de-a788312b1998.png)

**Comment by dharrison007** [comment]
It is is a debug build but I assume that should be OK?

**Comment by dharrison007** [comment]
> Your images have an alpha channel with statistics that are roughly equal to the stats of the RGB channels. So I suspect the dark areas are transparent, where the white areas are opaque. 
Could that mean IM is trying to read data into an alpha channel that doesnt exist?
reading:
IM:R  <---  File:R
IM:G  <---  File:G
IM:B  <---  File:B
IM:A  <---  File:R
IM:R  <---  File:G
IM:G  <---  File:B
IM:B  <---  File:R
IM:A  <---  File:G

etc..

That's what I believe is happening? This would make the alpha channel appear to have the same stats as RGB? Because of the 'reading' being at odds with the actual image data.

**Comment by dharrison007** [comment]
I took a look at IM source code to identify where IM takes the channel count from when reading a tiff multipage image.. but I got lost tracing the various calls through the various Magick++, MagickCore and tiff project interfaces.  I have very limited awareness of the architecture of IM so i am not much help.

**Comment by dharrison007** [comment]
Sorry wrong button press!

**Comment by dharrison007** [comment]
The output of "Identify" shows the "Base type" of individual image as "TrueColor", but IM is reading the image as "TrueColorAlpha"! This is the bug. It should use the individual page image type ("Base type", as labelled in output of identify.exe).  So I am more convinced this is a bug?

line 762 in identify.c indicates that IM can correctly identify the "type" of individual image within a multipage tiff; however the read process (a bit complicated for me to follow in code) is not doing this, nor is the output of the identify stats, as its reading the Images as RGBA instead of RGB.

If you need me to do anything more I am happy to do so?

Kind regards.

**Comment by snibgo** [comment]
```
Type: TrueColorAlpha
Base type: TrueColor
```
That isn't a problem. "Type" will include "Alpha" if the image in memory has an enabled alpha channel (ie alpha_trait is not undefined).

What does exiftool say about your tiff? I suspect it includes:
```
Bits Per Sample                 : 8 8 8 8
Samples Per Pixel               : 4
```
If so, I regard that as proof that images in your file contain an alpha channel.

> I think the old Ver IM6 wrote the tiff using TrueColorAlpha (RGBA) at the top level then for each image specified the TrueColor (RGB). 

What "top level"? I don't think TIFF files have "top level" metadata for "Type".

> ... however I believe IM has a bug in how the 'reading' of a tiff is taking place.

That is possible, of course. Another possibility is a bug in the process that created your TIFF file, that wrote colour data to the alpha channel.

I make heavy use of TIFF with alpha, and haven't encountered a problem like yours. So I suspect the problem  is in your TIFF file, not in IM's reading of that file.

I suggest you use IM to separate your multi-image TIFF into multiple single-image TIFFs. For each one, separate the four channels. What does each channel look like? Does the alpha channel seem to contain colour data?

Then do the same operations in Gimp.

**Comment by dharrison007** [comment]
With some expert help I have recreated and tested the issue. The issue/bug is with the reading tiff images that have have been converted from images with alpha channel to tiff. 
The steps to evidence this are very easy to reproduce:
Obtain an image with Alpha channel:
![Rick Original](https://user-images.githubusercontent.com/11913659/188290161-7a1d189c-a17c-4991-b6cf-d9c7ad7af4dc.png)
* Magick convert this to a tiff
* Open with IMDisplay to see the corrupted reading issue
 
[Rick IM conversion.zip](https://github.com/ImageMagick/ImageMagick/files/9483547/Rick.IM.conversion.zip)
The converted image can be viewed without any image issue in:

- GIMP 2.10.32 (revision 1)
- Windows Photo Viewer
- MS Paint
- MS Paint 3D
- Windows Snip and Sketch

Another test (out of several performed)
* Convert the Image to tiff using MS Paint (It confirms the alpha channel will be removed).
* Open with IMDisplay to see the corrupted reading issue

[Rick paint conversion.zip](https://github.com/ImageMagick/ImageMagick/files/9483554/Rick.paint.conversion.zip)

As above this image is fine when opened in alternative image viewers however when read by IM the image is corrupted.

I believe IM reading is mismatched to the actual data format in the file, such as: reading using RGBA (8bit on all channels) when the actual data is RGB only or RGBA with alpha being 1bit.

This is evidenced with the MS Paint conversion of the PNG to Tiff as the file size and message from MS Paint "Any transparency will be lost if you save this picture. Do you want to continue?" indicates the Alpha channel is removed. As does opening the converted image in GIMP (which displays is correctly). However if I use Identify -verbose it shows:
` Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass
  Geometry: 153x333+0+0
  Resolution: 96.012x96.012
  Print size: 1.59355x3.46832
  Units: PixelsPerInch
  Colorspace: sRGB
  Type: TrueColorAlpha
  Base type: TrueColor
  Endianness: LSB
  Depth: 8-bit
  Channel depth:
    Red: 8-bit
    Green: 8-bit
    Blue: 8-bit
    Alpha: 8-bit`
Which shows two types, (I'm not sure how the first type is ascertained) The Base type clearly saying TrueColor (RGB) yet it then reads the image as RGBA which corrupts the image.

GIMP shows this image has no Alpha channel, as do most of the other alternative image viewers.

Kind regards,

Dan

**Comment by dharrison007** [comment]
I have tested with prebuilt download of ImageMagick-7.1.0-Q16-HDRI; the same issue exists.

**Comment by fmw42** [comment]
> Magick convert this to a tiff

Please show your exact command.  Your PNG has alpha.  So if you do

`magick convert image.png image.tiff`

The tiff will also have and alpha. Furthermore, in IM 7, use magick not magick convert.

If you do not want the alpha, then turn it off

`magick image.png -alpha off image.tiff`

**Comment by dharrison007** [comment]
I used:
`magick "Rick Original.png" "Rick IM conversion.tiff`

It doesn't matter to me if there is an alpha or not, the issue is IM is not reading the resulting file correctly, and corrupting the image.

**Comment by dharrison007** [comment]
Here is a screen capture of the resulting `"Rick IM conversion.tiff"` in IMDisplay:
![Capture of rick in IMDisplay](https://user-images.githubusercontent.com/11913659/188292487-89e83c72-21ba-4cab-bb59-e96641201161.PNG)


here is the same image in GIMP:

![Capture of rick in GIMP](https://user-images.githubusercontent.com/11913659/188292526-cb3f9ad4-ef6a-42d3-8a03-c81ae1f2f594.PNG)

**Comment by dharrison007** [comment]
I am using Image Magick on many TIFF files that have been converted from other image formats, I am seeking for IM to be reliable in reading Tiff images.

**Comment by dlemstra** [comment]
It looks like this bug was introduced in this commit: e389397. Not sure how to fix this yet though.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by dharrison007** [comment]
> It looks like this bug was introduced in this commit: [e389397](https://github.com/ImageMagick/ImageMagick/commit/e389397b2be1a1b586923f279b1f2c36b28b1eb0). Not sure how to fix this yet though.

Many thanks.

> Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

Great news!

**Comment by dharrison007** [comment]
Thank you [https://github.com/JoeBoon](url) for spending your evening time investigating the issue with me with your QA expertise.  Resulting in a simple reproducible pattern.

[https://github.com/urban-warrior](url)
Suggest (sorry if a bit obvious) adding a few relevant image processing tests in your automated testing to capture future similar bug introductions.  As suggested by Joe (above) in our evening of investigating the problem.

**Comment by dharrison007** [comment]
@urban-warrior I had a quick read of the code in tiff.c (CORE_coders) and my initial pass identified a possible cause (albeit I'm not familiar enough with the code base, and subject matter, to be highly confident). Apologies for any improper comments I meant only to identify where I see some logical issue. However on the off chance it helps:
ReadTIFFImage() function:
`    if (tiff_status == 1)
      {
      // Note: alpha_trait is set to unsepcified as default
        (void) SetImageProperty(image,"tiff:alpha","unspecified",exception);
        
        if (extra_samples == 0)
          {
          // Possible issue : Where is the logic for scenario: samples_per_pixel =3 to &&
          //                  photometric == PHOTOMETRIC_RGB? Perhaps this implied by no denfinition?
          //                  However later the alpha_trait is forced?
            if ((samples_per_pixel == 4) && (photometric == PHOTOMETRIC_RGB))
              image->alpha_trait=BlendPixelTrait;
          }
        else
          {
            (void) SetPixelMetaChannels(image,extra_samples,exception);
            for (i=0; i < extra_samples; i++)
            {
              // Note: This appears to be the issue as it is defaulting the alpha_trait..
              //       when it may still need to be undefined (I'm not sure on the bigger picture though)
              // Possible issue: This forces the alpha_trait not to be UndefinedPixelTrait even if
              //                 samples_per_pixel==3
              image->alpha_trait=BlendPixelTrait;
              if (sample_info[i] == EXTRASAMPLE_ASSOCALPHA)
                {
                  SetQuantumAlphaType(quantum_info,AssociatedQuantumAlpha);
                  (void) SetImageProperty(image,"tiff:alpha","associated",
                    exception);
                }
              else
                if (sample_info[i] == EXTRASAMPLE_UNASSALPHA)
                  {
                    SetQuantumAlphaType(quantum_info,DisassociatedQuantumAlpha);
                    (void) SetImageProperty(image,"tiff:alpha","unassociated",
                      exception);
                  }
            }
            (void) SetPixelMetaChannels(image,extra_samples,exception);
            // Note: The condition below will always be met as alpha_trait is assigned BlendedPixelTrait above
            //       given scenario: extra_samples = 0 and samples_per_pixel = 3 would this be an issue?
            if (image->alpha_trait != UndefinedPixelTrait)
              (void) SetPixelMetaChannels(image,extra_samples-1,exception);
          }
      }
    // Note:  The above code would imply that the below condition will always be met?
    if (image->alpha_trait != UndefinedPixelTrait)
      (void) SetImageAlphaChannel(image,OpaqueAlphaChannel,exception);`

The above impacts:
`    if (interlace != PLANARCONFIG_SEPARATE)
      {
        size_t
          pad;

        pad=(size_t) MagickMax((ssize_t) samples_per_pixel-1,0);
        // Note: The above code means this is always the case.
        if (image->alpha_trait != UndefinedPixelTrait)
          {
            if (image->storage_class == PseudoClass)
              quantum_type=IndexAlphaQuantum;
            else
              quantum_type=samples_per_pixel == 1 ? AlphaQuantum :
                GrayAlphaQuantum;
          }
        // Note: It's already determined that the interlace != PLANARCONFIG_SEPARATE in above parent if statement
        if ((samples_per_pixel > 2) && (interlace != PLANARCONFIG_SEPARATE))
          {
            quantum_type=RGBQuantum;
            pad=(size_t) MagickMax((ssize_t) samples_per_pixel+
              extra_samples-3,0);
            // Note: The earlier code (issue?) means this is always the case.
            if (image->alpha_trait != UndefinedPixelTrait)
              {
                quantum_type=RGBAQuantum;
                // Note: The padding will depend on the bits_per_sample
                //       Tiff RGB can all have independent bits_per_sample although rare I expect
                //       Alpha would likely be 1 bit or Max bit to align with RGB, albeit it is independent.
                //       I am unaware if this is worked out prior to read?
                // https://awaresystems.be/imaging/tiff/tifftags/bitspersample.html
                pad=(size_t) MagickMax((ssize_t) samples_per_pixel+
                  extra_samples-4,0);
              }
            if (image->colorspace == CMYKColorspace)
              {
                quantum_type=CMYKQuantum;
                pad=(size_t) MagickMax((ssize_t) samples_per_pixel+
                  extra_samples-4,0);
                // Note: The earlier code (issue?) means this is always the case.
                if (image->alpha_trait != UndefinedPixelTrait)
                  {
                    quantum_type=CMYKAQuantum;
                    pad=(size_t) MagickMax((ssize_t) samples_per_pixel+
                      extra_samples-5,0);
                  }
              }
            status=SetQuantumPad(image,quantum_info,pad*((bits_per_sample+7) >>
              3));
            if (status == MagickFalse)
              ThrowTIFFException(ResourceLimitError,"MemoryAllocationFailed");
          }
      }`

**Comment by dlemstra** [comment]
We resolved the issue with this patch; 77561be

**Comment by dharrison007** [comment]
Oh.. fantastic ! :-) that was fast! Sorry for my bumbling attempts to help.

**Comment by dharrison007** [comment]
Many thanks @urban-warrior , @dlemstra and @joeboon tested the files that I am using and all is looking perfect! Super efficient resolution!
