### ISSUE TITLE
-family fallback not working

### ISSUE THREAD

**Issue by q3cpma** [ImageMagick/ImageMagick#5531]
### ImageMagick version

7.1.0-44

### Operating system

Linux

### Operating system, version and so on

Gentoo

### Description

Hello,

after reading https://github.com/ImageMagick/ImageMagick/issues/4660, I thought the problem was fixed long ago, but trying it isn't working here (even if the individual fonts are).

Am I doing something wrong? By the way, could `-family` be added to the `montage` tool?

### Steps to Reproduce

```
$ magick convert -pointsize 50 \
        -family "Courier"                         label:'1月' \
        -family "Source Han Sans JP"              label:'1月' \
        -family "Courier,   'Source Han Sans JP'" label:'1月' \
        -family "Courier ,  'Source Han Sans JP'" label:'1月' \
        -family "'Courier', 'Source Han Sans JP'" label:'1月' \
        -family "Courier 'Source Han Sans JP' ,"  label:'1月' \
        -append combined.png
```
![result](http://0x0.st/opG7.png)

Here are the relevant sections from `magick convert -list font`:
```
$ magick convert -list font
...
  Font: Source-Han-Sans-JP
    family: Source Han Sans JP
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/source-han-sans/SourceHanSansJP-Regular.otf
...
  Font: Courier
    family: Courier
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/urw-fonts/n022003l.pfb
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by q3cpma** [comment]
Thanks for the speed.

**Comment by q3cpma** [comment]
Tried with 7.1.0-48 and I got:
![combined](https://user-images.githubusercontent.com/40627987/194593369-765f96d8-309b-437e-8145-3ef06b585052.png)

Unless I misunderstand the feature, isn't the working case supposed to have the 1 rendered with Courier and the CJK characters with Source Han Sans JP?

**Comment by dlemstra** [comment]
The fallback font will be used for all characters when the other font (Courier in our case) could not be loaded. It is not a fallback per character.
