### ISSUE TITLE
Cannot open images by URL anymore

### ISSUE THREAD

**Issue by NicoHood** [ImageMagick/ImageMagick#5532]
### ImageMagick version

7.1.0.47

### Operating system

Linux

### Operating system, version and so on

ArchLinux, Package version 7.1.0.47-1

### Description

Hi,
I come from this issue originally:
https://github.com/emcconville/wand/issues/591

I noticed, that for some reasons I cannot open https urls anymore with the python wand library. Downgrading to the previous python library version did not help, so I expect that the issue is located in imagemagick itself? I recently upgraded from `7.1.0.45-1 -> 7.1.0.47-1` so I guess there the issue was introduced.

I am not sure if it is really caused by imagemagick, but I have no better idea

### Steps to Reproduce

See the linked python example.

**Comment by NicoHood** [comment]
Update: A package downgrade of imagemagick also did not solve it. Is it an any third party library, or am I missing something?

**Comment by fmw42** [comment]
Did you permit HTTPS in your policy.xml file?

**Comment by NicoHood** [comment]
This is my policy file:

```xml
<policymap>
  <!-- <policy domain="resource" name="temporary-path" value="/tmp"/> -->
  <!-- <policy domain="resource" name="memory" value="2GiB"/> -->
  <!-- <policy domain="resource" name="map" value="4GiB"/> -->
  <!-- <policy domain="resource" name="width" value="10KP"/> -->
  <!-- <policy domain="resource" name="height" value="10KP"/> -->
  <!-- <policy domain="resource" name="list-length" value="128"/> -->
  <!-- <policy domain="resource" name="area" value="100MP"/> -->
  <!-- <policy domain="resource" name="disk" value="16EiB"/> -->
  <!-- <policy domain="resource" name="file" value="768"/> -->
  <!-- <policy domain="resource" name="thread" value="4"/> -->
  <!-- <policy domain="resource" name="throttle" value="0"/> -->
  <!-- <policy domain="resource" name="time" value="3600"/> -->
  <!-- <policy domain="coder" rights="none" pattern="MVG" /> -->
  <!-- <policy domain="module" rights="none" pattern="{PS,PDF,XPS}" /> -->
  <!-- <policy domain="delegate" rights="none" pattern="HTTPS" /> -->
  <!-- <policy domain="path" rights="none" pattern="@*" /> -->
  <!-- <policy domain="cache" name="memory-map" value="anonymous"/> -->
  <!-- <policy domain="cache" name="synchronize" value="True"/> -->
  <!-- <policy domain="cache" name="shared-secret" value="passphrase" stealth="true"/> -->
  <!-- <policy domain="system" name="max-memory-request" value="256MiB"/> -->
  <!-- <policy domain="cache" name="synchronize" value="true"/> -->
  <!-- <policy domain="system" name="shred" value="1"/> -->
  <!-- <policy domain="system" name="font" value="/path/to/unicode-font.ttf"/> -->
  <policy domain="Undefined" rights="none"/>
</policymap>
```

I also tried to downgrade imagemagick to the version that was working, but that also did not solve the issue. Maybe it is also related to an external library upgrade?

**Comment by fmw42** [comment]
Try uncommenting the line for HTTPS

**Comment by NicoHood** [comment]
Uncommenting does not help.

The owner of the python package gave me the hint, that this is a packaging issue:
https://github.com/emcconville/wand/issues/591#issuecomment-1237139256

Do you have an idea why this happens?

**Comment by NicoHood** [comment]
It was fixed by archlinux:
https://github.com/archlinux/svntogit-packages/commit/761863adcab219f73790bfd1dde52a76ca4f8c10
