### ISSUE TITLE
Converting SVG to PNG (with possibly unsupported values?)

### ISSUE THREAD

**Issue by grapho** [ImageMagick/ImageMagick#5534]
### ImageMagick version

7.1.0-47

### Operating system

MacOS

### Operating system, version and so on

Monterey 12.0.1

### Description

Attempting to simply 1:1 convert SVG to PNG:

`magick https://es-dev.imgix.net/uploads/3a8effd8-6a4a-4130-88d8-4f4ee09d41d4.svg test.png `

Results in the error:

```magick: non-conforming drawing primitive definition `stroke-dasharray' @ error/draw.c/RenderMVGContent/4495```

It is not clear to me.. is it an incorrect _value_ set on `stroke-dasharray`? or is `stroke-dasharray` simply not supported?

### Steps to Reproduce

You can try to convert this image: `https://es-dev.imgix.net/uploads/3a8effd8-6a4a-4130-88d8-4f4ee09d41d4.svg` to see the result

### Images

https://es-dev.imgix.net/uploads/3a8effd8-6a4a-4130-88d8-4f4ee09d41d4.svg

**Comment by snibgo** [comment]
What is your rasterizer? Inkscape, RSVG or MSVG? I suppose MSVG, as your error occurred in function RenderMVGContent().

For me, IM v7.1.0-42 on Windows 8.1, it works fine when the rasteriser is Inkscape.

When I use MSVG as the rasterizer, it breaks with the same error message. If I replace the numbers after "`stroke-dasharray`" with non-numeric text like this:
```
stroke-dasharray:abc;
```
... then it succeeds.

I think there is a bug in IM's handling of stroke-dasharray in SVG.

**Comment by grapho** [comment]
> What is your rasterizer? Inkscape, RSVG or MSVG?

That's a good question.. perhaps i neglected to configure IM properly.. I use Inkscape personally.. but i didnt not declare what IM should be using

**Comment by ValZapod** [comment]
Well, is this a bug in Adobe Illustrator 25.4.1 then?

RSVG works. It generates wrong colors though... Cause it does not write sRGB chunk in png.
