### ISSUE TITLE
exif gets duplicated when convert from heic to heic

### ISSUE THREAD

**Issue by japheth-sh** [ImageMagick/ImageMagick#5537]
### ImageMagick version

7.1.0-11

### Operating system

Linux

### Operating system, version and so on

amazon linux 2

### Description

exif item is duplicated thus when open the converted heic in MacOS it ignores exif:Orientation.

### Steps to Reproduce

convert 43ae6f68-7f55-4228-bff3-61c2b383ff27.heic -quality 40 43_.heic
exiftool -v3 43ae6f68-7f55-4228-bff3-61c2b383ff27.heic > 43a.txt
exiftool -v3 43_.heic > 43_.txt

### Images

[43a.txt](https://github.com/ImageMagick/ImageMagick/files/9504718/43a.txt)
[43_.txt](https://github.com/ImageMagick/ImageMagick/files/9504725/43_.txt)
![20220907172728](https://user-images.githubusercontent.com/43056596/188843583-2af64c7e-d184-4e64-9724-af5c900496cf.jpg)

**Comment by japheth-sh** [comment]
though I set the version to 7.1.0-11, but I believe I tried 7.1.0-47 and got the same result.

**Comment by japheth-sh** [comment]
![debug](https://user-images.githubusercontent.com/43056596/188845988-f446ecc8-fdf0-466c-ad70-1d576f9d5ffb.png)

**Comment by wsx958191** [comment]
hi:

I installed ImageMagick on CentOS, and HEIC entrusted it, but the command-line test failed. Can you guide me？

<img width="796" alt="企业微信截图_eaa18fbe-0ead-4508-85d4-5b0d70204328" src="https://user-images.githubusercontent.com/66000167/189019227-d333e4bb-dc7e-4355-8810-20e3d4e85101.png">

**Comment by japheth-sh** [comment]
> hi:
> 
> I installed ImageMagick on CentOS, and HEIC entrusted it, but the command-line test failed. Can you guide me？
> 
> <img alt="企业微信截图_eaa18fbe-0ead-4508-85d4-5b0d70204328" width="796" src="https://user-images.githubusercontent.com/66000167/189019227-d333e4bb-dc7e-4355-8810-20e3d4e85101.png">

I cannot reproduce. Mine mogrify works well. Check whether you have libheif and its dependencies (libx265 for write heif, libde265 for read) installed before build IM. And your directory access as well.

PS: it is not a good idea to find help here.

Japheth

**Comment by japheth-sh** [comment]
@dlemstra do you have an estimate of when this can be solved? I am blocked by this.

**Comment by dlemstra** [comment]
I cannot give you an estimate. I will take a look at this when I have time to investigate it.

**Comment by dlemstra** [comment]
I just pushed a patch to fix this issue. You should be able to check the fix in our GitHub Codespace after the pre-build has been completed: https://github.com/ImageMagick/ImageMagick/actions/workflows/codespaces/create_codespaces_prebuilds.

**Comment by japheth-sh** [comment]
@dlemstra Thank you~~ I will have a check.

**Comment by japheth-sh** [comment]
Hi, we do have only one EXIF now. However, Mac still use orientation 1 until I removed the 'miaf' CompatibleBrands.
![image](https://user-images.githubusercontent.com/43056596/190958486-b1510aab-729a-40b3-90af-e2cc72b3a4b2.png)
to:
![image](https://user-images.githubusercontent.com/43056596/190958558-ff850147-fcad-41f7-91db-0373eb2fc04e.png)

**Comment by japheth-sh** [comment]
confirmed this dup-exif issue is fixed in lastest 7.1.0-49.
