### ISSUE TITLE
memory exhaustion in ReadTIFFImage

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#554]
Version: ImageMagick 7.0.6-1 Q16 x86_64

`#./magick identify $FILE`

When identify TIFF file , imagemagick will allocate memory to store the data, here is the critical code:
(tiff.c , in function ReadTIFFImage)
```
  tiff=TIFFClientOpen(image->filename,"rb",(thandle_t) image,TIFFReadBlob,  //1176
    TIFFWriteBlob,TIFFSeekBlob,TIFFCloseBlob,TIFFGetBlobSize,TIFFMapBlob,
    TIFFUnmapBlob);
```
The function chain from TIFFClientOpen is : TIFFClientOpen->TIFFReadDirectory->TIFFReadDirectory->_TIFFCheckRealloc,and in the critical function _TIFFCheckRealloc:
```
 _TIFFCheckRealloc(TIFF* tif, void* buffer,
                              tmsize_t nmemb, tmsize_t elem_size, const char* what)
{
void* cp = NULL;
tmsize_t bytes = nmemb * elem_size;

/*
 * XXX: Check for integer overflow.
 */
if (nmemb && elem_size && bytes / elem_size == nmemb)  //72
          cp = _TIFFrealloc(buffer, bytes);     // bytes is controlled by input file
```
The “bytes”is controlled by input file,the function _TIFFrealloc will allocate large memory bypassed the limition of policy.xml,here is my policy.xml
```
...

<policy domain="resource" name="area" value="100MP"/>

<policy domain="resource" name="memory" value="256MiB”/>

...

```
testcase: https://github.com/bestshow/p0cs/blob/master/memory_exhaustion_in_ReadTIFFImage
Credit: ADLab of Venustech

**Comment by mikayla-grace** [comment]
The problem you posted is within the libTIFF delegate library.  Notify the libTIFF developers requesting a fix.

**Comment by bastien-roucaries** [comment]
Could you please open a CVE again libtiff ? I have contacted tiff upstream

**Comment by dlemstra** [comment]
@bestshow Do you also have a link to the tiff bug report?

**Comment by bastien-roucaries** [comment]
Not it was a mail to the mailling list.

But creating a CVE will really help here.
