### ISSUE TITLE
appimage cannot open ORA file

### ISSUE THREAD

**Issue by braindevices** [ImageMagick/ImageMagick#5551]
### ImageMagick version

7.1.0-47 Q16-HDRI x86_64 d91623c12:20220827

### Operating system

Linux

### Operating system, version and so on

Ubuntu20.04

### Description

```
Delegates (built-in): bzlib djvu fontconfig freetype jbig jng jpeg lcms lqr lzma openexr png raqm tiff webp x xml zlib
```
error:
```
identify: no decode delegate for this image format `ORA' @ error/constitute.c/ReadImage/741.
```

### Steps to Reproduce

just try `magick identify any.ora`

**Comment by snibgo** [comment]
I don't have a sample ORA file to test this, but "magick -list format" says:
```
      ORA  r--   OpenRaster format
```
... suggesting my version of IM can read ORA files.

**Comment by urban-warrior** [comment]
We get expected results for ORA with our instance of ImageMagick, i.e., we can read/write ORA images.  Post a link to one of your ORA images.  We'll download it and inspect it to verify we can read it or why it fails to read.
