### ISSUE TITLE
MagickSetDefaultResolution() method

### ISSUE THREAD

**Issue by za3k** [ImageMagick/ImageMagick#5554]
### Is your feature request related to a problem? Please describe.

Yes. I use a program (zbar) for reading QR codes. It uses imagemagick, so it happily accepts PDF input. However by default, imagemagick samples them at 72dpi, which means the QR decode typically fails. Typically I work with multi-page PDFs, because there aren't many multi-image printable formats.

There isn't a perfect solution here, in that pdf doesn't encode a resolution. I'm proposing what I see as one good option.

### Describe the solution you'd like

I'd like to see a variant of SetResolution(), SetDefaultResolution(), which only has an effect if the image doesn't specify a resolution itself.

I have never used SetImageResolution() so I'm not sure if there should be a SetDefaultImageResolution() as well.

## Solution 1
1. Use SetResolution() unconditionally. 

This messes up files which have a resolution encoded in them, as I understand it.

## Solution 2 (use file extension)
1. Look at the filename to see what type of file it is (pdf, png, etc)
2. Set the resolution using SetResolution() if warranted by the file/image type
3. Read the file using one of the Read() methods

This relies on each "user" program of ImageMagick to know how to deal with every possible format. It assumes you have a filename, which is not always true. It assumes the filename is accurate, which is also not always true.

## Solution 3 (read twice)
1. Read the file once, to see what type of file it is, using one of the Ping() methods for speed.
2. Set the resolution using SetResolution() if warranted by the file/image type
3. Read the file a second time

Again, this relies on each "user" program to know how to deal with every possible format. It runs into issues with streams, which can't be read twice (you can read the file into a blob first, which is my current workaround). It requires reading a significant portion of the file twice.

## Solution 4 (reset resolution)
1. Read the file once
2. Examine the image type and resolution
3. Call SetImageResolution() depending on the image type and resolution

I can't say whether this method works or not, because I'm not familiar with SetImageResolution(). I can say it seems like it still requires a bunch of knowledge of image formats from the user.

**Comment by urban-warrior** [comment]
To  render PDF's at a higher resolution, you need to set the resolution before the image is read.  After it is read, you can modify the resolution of the image either by setting it or resampling.  There are no SetImageResolution() or SetResolution() methods in ImageMagick.  To set the resolution before an image is read from the command-line, use `-density 300`, for example.  From the MagickCore API, use `SetIImageOption(image_info,"density","300");`.  For MagickWand, use `MagickSetResolution(wand,300,300);`.

**Comment by za3k** [comment]
Sorry, `MagickSetResolution()`, not `SetResolution()`, right you are. Sorry to be sloppy with function names. 

If it was unclear, this is a feature request. I'm aware you can already do this stuff. Nothing is insurmountable.

Maybe before and after code would be helpful here?

Existing (MagickSetResolution):
```
// We're going to read the file twice, so move to a blob in case the file is a stream.
  size_t blob_length;
ExceptionInfo *blob_exception = AcquireExceptionInfo();
void *blob = FileToBlob(filename, MAGICK_SSIZE_MAX, &blob_length, blob_exception);
if (!blob && dump_core_exception(blob_exception)) return (-1);
DestroyExceptionInfo(blob_exception);
  
// Check the format quickly, then start over.
MagickWand *images = NewMagickWand();
if (!MagickReadImageBlob(images, blob, blob_length) && dump_error(images)) return (-1);
char *format = MagickGetImageFormat(images);
  
// Upgrade PDF resolution. Note, the program needs a list of Image formats that need a resolution set he  re! 
if (format != 0 && strcmp(format, "PDF") == 0) MagickSetResolution(images, 300, 300);
  
// Re-read the images
while (MagickRemoveImage(images)); // remove all images
if (!MagickReadImageBlob(images, blob, blob_length) && dump_error(images)) return (-1);
```

I'm skipping a resampling code snippet, which could definitely be an improvement.

Proposed (MagickSetDefaultResolution):
```
if (!MagickSetDefaultResolution(images, 300, 300) && dump_error(images)) return (-1);
if (!MagickReadImage(images, filename) && dump_error(images)) return (-1);
```

**The biggest benefit of 'proposed' is that the program in question doesn't need to be specifically aware of the list of formats needing a default density.** Of secondary benefit is reduced size.

**Comment by urban-warrior** [comment]
Why not call `MagickSetResolution(images, 300, 300);` always.  It only affects a few formats such as {PDF, PS, XPS} and all other formats ignore it.   For example, try these commands:

```
$ magick -density 300x300 logo: -verbose info:
$ magick logo: -set density 300x300 -verbose info:
```

The image defaults to 72x72 resolution for the first command and 300x300 for the second.

**Comment by za3k** [comment]
I guess I had concluded that some formats had a PPI/DPI setting which would be overruled, and I'm not sure where I got that any more. Sorry for wasting your time! Sounds like MagickSetResolution already works how I want.
