### ISSUE TITLE
MP3s with Album Thumbnail are Treated as PNM 

### ISSUE THREAD

**Issue by justdan23** [ImageMagick/ImageMagick#557]
When using identify, the tool doesn't keep track of the stack of all types internally found and doesn't identify the top most format.

Using MP3s with Album Thumbnail, it traverses through:
- MPEG Delegate with FFMPEG,
- PS Delegate with GhostScript (erasing the mpeg file info)
- PNM Delegate for Thumbnail (again erasing the file info struct to only show it as a PNM pixmap image)

The end result is the wrong type and mime type detected.

This in-turn breaks convert as it doesn't recognize it as an audio mpeg file.

Version: 7.0.5.5;  Was this fixed in a newer patch version?

Note: It would be ideal to have an option to stop reading the file after the signature is identified for the top level format to support type cataloging.  Also, when using 'convert', Allow for smart conversion if output requested is a PNG or JPG to use the detected PNM.  I mention these here as they could impact the architecture needed to fix this main issue and support scaling for future improvements.

**Comment by justdan23** [comment]
Correction.  I'm working with Version 7.0.5.5's base source code.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
