### ISSUE TITLE
dds:mipmaps is slow

### ISSUE THREAD

**Issue by ikerr** [ImageMagick/ImageMagick#558]
When enabling mipmaps while writing a DDS file, I expected convert's CPU time to double, since it is encoding about twice as many pixels; however, I'm seeing much larger increases in time when running:

```convert image.png -define dds:compression=dxt1 image.dds```

vs.

```convert image.png -define dds:compression=dxt1 -define dds:mipmaps=0 image.dds```

For example, the first command takes 32s while the second takes only 7s for an 8192x8192 image. My hunch is that this is due to the fact that in `WriteMipmaps()`, the code resizes the *original* image for each mip-level:

https://github.com/ImageMagick/ImageMagick/blob/master/coders/dds.c#L3023

This likely results in the highest quality mips, but if each iteration could re-use the previous iteration's scaled image, the function could likely be sped up considerably. Perhaps it would make sense to add an option for this? For example: `dds:fastmips`?

Thoughts?

**Comment by dlemstra** [comment]
I think your idea is a very good idea and should be easy to add. Would love to run some test to see how much faster this will be. Can you share your input image?

**Comment by ikerr** [comment]
Hi @dlemstra, sorry for the slow response! Unfortunately, I can't share the particular image that I was using as a test case, though I would guess that almost any large image would exhibit similar behaviour.

If I can find some time to submit a patch, I'll do so :) Thanks.

**Comment by dlemstra** [comment]
I got a patch ready but I just need to get a good test image. To test if it still works correct and what kind of performance you will get.

**Comment by dlemstra** [comment]
The patch has been added to IM7 and will be available in the next release.
