### ISSUE TITLE
Conversion of a .CR3 image into a .FITS image stretches (normalize or level) the .FITS image, but this is not wanted!

### ISSUE THREAD

**Issue by AlbertFetscher** [ImageMagick/ImageMagick#5580]
### ImageMagick version

ImageMagick 7.1.0-35

### Operating system

Windows

### Operating system, version and so on

Windows 10 Professional, uptodate and so on

### Description

Conversion of a .CR3 image into a .FITS image stretches (normalize or level) the .FITS image, but this is not wanted and commanded!

Command line:
  magick image.CR3 image.FITS

Expected result:
  The image.CR3 will be converted into image.FITS, without any modifications.

Result:
  The image.CR3 was converted into image.FITS but the image has also been stretched (normalized or leveled). 

### Steps to Reproduce

On windows command line:

  magick image.CR3 image.FITS

### Images

Sorry, but it is not possible to upload the related image (also not as .ZIP file).

**Comment by snibgo** [comment]
Try inserting "`-define dng:no-auto-bright=true`" before reading the CR3 file. See https://imagemagick.org/script/defines.php for other DNG settings that may be useful.

**Comment by AlbertFetscher** [comment]
Thank you very much for your reply. 
Your proposal was very helpful and will help to convert .CR3 into .FITS without stretching the image.
  magick -define dng:no-auto-bright=true image.CR3 image.FITS

Question: Should "dng:no-auto-bright=true" not be the default value?

**Comment by snibgo** [comment]
I think the default was inherited from the behaviour of dcraw, which by default will "automatically brighten the image", ie stretch the values up to 100%, unless told not to.

Changing the default behaviour of IM would cause problems in existing scripts.

**Comment by AlbertFetscher** [comment]
Now understand the current behavior of IM and thanks for clarifying the issue.
