### ISSUE TITLE
Regression with DICOM handling

### ISSUE THREAD

**Issue by cmcfadden** [ImageMagick/ImageMagick#559]
There's a regression with handling the attached file, caused by this merge:
https://github.com/ImageMagick/ImageMagick/pull/485

The issue causes Images to come out very dark when doing a simple convert <DCM> output.jpg

[IM-0003-0387-0001.dcm.zip](https://github.com/ImageMagick/ImageMagick/files/1149259/IM-0003-0387-0001.dcm.zip)

**Comment by dlemstra** [comment]
We introduced a new option to handle this. You will now need to do this:

`convert  -define dcm:rescale=true IM-0003-0387-0001.dcm output.jpg`
