### ISSUE TITLE
Support half (16-bit) float for JPEG XL

### ISSUE THREAD

**Issue by kmilos** [ImageMagick/ImageMagick#5599]
### Describe the solution you'd like

The jxl delegate currently supports 32-bit (single) float pixel format, but JPEG XL can also carry 16-bit (half) float HDR/WCG data, similar to EXR:

https://github.com/libjxl/libjxl/blob/f95da131cf7c7ccd4da256356fde2fec1fa23bb5/lib/include/jxl/types.h#L37-L56

**Comment by urban-warrior** [comment]
Can you post a link to 2-3 example JPEG XL images that include 16-bit half float pixels and can be read by `djxl`?  We'll use these to verify proper support for the format within ImageMagick.

**Comment by kmilos** [comment]
Please find attached the JPEG XL sample transcoded* from CC0 EXR here: https://polyhaven.com/a/shanghai_bund

[shanghai_bund_1k.zip](https://github.com/ImageMagick/ImageMagick/files/10013484/shanghai_bund_1k.zip)

```sh
$ jxlinfo shanghai_bund_1k.jxl
JPEG XL file format container (ISO/IEC 18181-2)
JPEG XL image, 1024x512, lossy, 16-bit float (5 exponent bits) RGB
Color space: RGB, D65, sRGB primaries, Linear transfer function, rendering intent: Perceptual
Uncompressed xml  metadata: 2559 bytes
```
AFAIK `djxl` cannot output to any 16-bit float format, and requesting 32-bit PFM didn't work for me using libjxl 0.7.0 (`Encode failed`). Converting to 16-bit unsigned integer (e.g. PPM) works, but not sure how useful it is in this case...

*using darktable master

**Comment by kmilos** [comment]
There's probably nothing really to do here apart from hooking up, as JPEG XL stores these as floats internally in the lossy mode, and once 32-bit float is requested as output decoding format, the conversion is done by libjxl anyway?

**Comment by urban-warrior** [comment]
The latest main repo can read your `shanghai_bund_1k.jxl` as linear RGB.
