### ISSUE TITLE
Error converting from PDF do image file (.PNG and others)

### ISSUE THREAD

**Issue by luissilva-AIRC** [ImageMagick/ImageMagick#5608]
### ImageMagick version

7.0.0-49

### Operating system

Windows

### Operating system, version and so on

Windows 10, Windows 11

### Description

When converting a .PDF to .PNG (or other image formats) magick does not produce an image.
In version 7.1.0-27 the program works fine.
I attached the LOGs of versions 7.1.0-27 and 7.1.0-49:
[Magick-7.1.0-27_OK.log](https://github.com/ImageMagick/ImageMagick/files/9683142/Magick-7.1.0-27_OK.log)
[Magick-7.1.0-49-ERROR.log](https://github.com/ImageMagick/ImageMagick/files/9683143/Magick-7.1.0-49-ERROR.log)

### Steps to Reproduce

Used the command:
magick.exe +antialias -quality 100 -density 96 "File.pdf"[0] "File.png"

**Comment by luissilva-AIRC** [comment]
By mistake I mentioned version 7.0.0-49 when it should be 7.1.0-49

**Comment by dlemstra** [comment]
What happens when you upgrade Ghostscript to a more recent version?

**Comment by luissilva-AIRC** [comment]
When I install Ghostscript 10.00.0 Imagemagick does not find GS.
I used the workaround reported here for that problem:
https://stackoverflow.com/questions/13304832/ghostscripts-file-path-in-imagemagick
With GS version 10.00.0 it works.
Thank you
