### ISSUE TITLE
PS and EPS %%HiResBoundingBox incorrect

### ISSUE THREAD

**Issue by SJBUK42** [ImageMagick/ImageMagick#5623]
### ImageMagick version

7.1.0-49

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

When converting an EPS/PS file with a %%HiResBoundingBox DSC, at a higher density than 72 to another EPS , the height is rounded, losing precision. e.g.

Input: %%HiResBoundingBox: 0.00 0.00 170.10 0.50 

Output: %%HiResBoundingBox: 0 0 170.16 **0**

The height issue seems to be caused by a typo in ImageMagick\coders\ps.c - line  1571:

bounds.y2=(double) geometry.y+(geometry.height+text_size);

should be:

bounds.y2=(double) geometry.y+(scale.y+text_size);

In case you're we're doing something so odd, it's to strip out unnecessary content from the source EPS! 

### Steps to Reproduce

Run:
convert.exe -density 300 hiresbbox.eps hiresbbox.out.eps 

Compare the %%HiResBoundingBox DCS's at the top of the input and output files. Some rounding is expected but in this case the height should be 0.5

### Images

[hiresbbox.eps.zip](https://github.com/ImageMagick/ImageMagick/files/9725314/hiresbbox.eps.zip)

**Comment by fmw42** [comment]
I suggest you try upgrading to the current IM version. Yours is rather old. Try again and then report if still an issue.

**Comment by dlemstra** [comment]
Thanks for this fix. It will come available in the next release.
