### ISSUE TITLE
montage -label '%f' works + -label '%t' fails

### ISSUE THREAD

**Issue by davidfavor** [ImageMagick/ImageMagick#5624]
### ImageMagick version

6.9.11-60

### Operating system

MacOS

### Operating system, version and so on

Monterey - 12.4, MacPorts build

### Description

Subject says it all '%f' works + '%t' fails...

### Steps to Reproduce

This works...
```
montage -label '%f' -frame 5 -background white -pointsize 24 null: 0*.jpeg -label %f -tile x1 -geometry -5+2 null: front-line.jpeg
```
This fails...
```
montage -label '%t' -frame 5 -background white -pointsize 24 null: 0*.jpeg -label %f -tile x1 -geometry -5+2 null: front-line.jpeg
montage: unknown image property "%t" @ warning/property.c/InterpretImageProperties/3835.
```
Docs say this should work, so seems like a bug.

Also, please provide a work around... maybe with '%[basename]' which I couldn't get to work either.

Thanks!

### Images

![01 Leader Woody Sky Steel](https://user-images.githubusercontent.com/87222/194455951-637fef15-4e35-4197-94e7-a7871d413885.jpeg)
![02 Warrior Firey Castle Sunset](https://user-images.githubusercontent.com/87222/194455953-c8cb493a-715f-493a-be19-a1bf68c7b179.jpeg)
![03 Warrior Earthy Citrus Rainbow](https://user-images.githubusercontent.com/87222/194455954-87dc7bdf-7bf2-4a24-b0b5-4ea87bce9d01.jpeg)
![04 Warrior Metallic Dragon Rainbow](https://user-images.githubusercontent.com/87222/194455955-3c840241-fd9a-493d-aebe-4ee6445584d5.jpeg)
![05 Warrior Watery Griffen Grey](https://user-images.githubusercontent.com/87222/194455958-fec2dc2a-0e81-4c4f-9242-f5a7dfa488d2.jpeg)

**Comment by fmw42** [comment]
The following works fine for me on IM 6.9.12-64 OSX Monterey

`montage -label "%t" lena.png x.png`

![x](https://user-images.githubusercontent.com/13458218/194468080-0bc0b1b9-963a-4352-8ca2-5d7665c85ca9.png)

Your version of IM is rather old. I suggest that you upgrade it.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by davidfavor** [comment]
Curiously enough I notice something else too.

1) The error emits, per above.

2) The actual output file is created + appears to be correct.

Just mentioning this, as I only checked the actual output file after opening the ticket.
