### ISSUE TITLE
There is an error converting a dng image to a jpg image

### ISSUE THREAD

**Issue by helloworldgnu** [ImageMagick/ImageMagick#5637]
### ImageMagick version (Installed using homebrew)

7.1.0-49

### Operating system

MacOS

### Operating system, version and so on

macOS Monterey 12.6

### Description

dng picture address  -->  https://gitee.com/helloworldgnu/images/blob/master/files/apple_iphone_12_pro_max_02.dng ,

After converting this image from dng to jpg the chromatic aberration was very large, the command line error "convert: Data corrupted at '15076539' @ warning/dng.c/LibRawDataError/388."

The address of the wrong jpg picture after conversion(Generated using ImageMagick's convert command) --> https://gitee.com/helloworldgnu/images/blob/master/files/apple_iphone_12_pro_max_02_error.jpg ,

The correct image address after conversion(Exported using mac picture preview software) --> https://gitee.com/helloworldgnu/images/blob/master/files/apple_iphone_12_pro_max_02_right.jpg , 

### Steps to Reproduce

convert apple_iphone_12_pro_max_02.dng  apple_iphone_12_pro_max_02.jpg

**Comment by fmw42** [comment]
try

convert DNG:apple_iphone_12_pro_max_02.dng apple_iphone_12_pro_max_02.jpg

**Comment by helloworldgnu** [comment]
> 

Still not right，This error still occurs "convert: Data corrupted at `15076539' @ warning/dng.c/LibRawDataError/388", The converted image is still chromatic

**Comment by helloworldgnu** [comment]
> try
> 
> convert DNG:apple_iphone_12_pro_max_02.dng apple_iphone_12_pro_max_02.jpg

**Comment by urban-warrior** [comment]
Is there a way to download the reference image without creating a gitee account?  If not, post your image to a free download service and we will investigate the issue?

**Comment by urban-warrior** [comment]
The corruption error is issued by the `libraw` delegate library ImageMagick leverages to read DNG images.

Your image is a linear DNG.  We got expected results with this command:

```
convert apple_iphone_12_pro_max_02.dng -profile rgb.icc -profile sRGB.icc apple_iphone_12_pro_max_02.jpg
```

**Comment by helloworldgnu** [comment]
> The corruption error is issued by the `libraw` delegate library ImageMagick leverages to read DNG images.
> 
> Your image is a linear DNG. We got expected results with this command:
> 
> ```
> convert apple_iphone_12_pro_max_02.dng -profile rgb.icc -profile sRGB.icc apple_iphone_12_pro_max_02.jpg
> ```

How the rgb.icc and srgb.icc files are obtained ?

**Comment by fmw42** [comment]
If you do not have them, put them on your system and provide the path to them in your command. See profiles.zip at https://imagemagick.org/archive/delegates/

**Comment by helloworldgnu** [comment]
Using the two icc files you provided, and the above command, the dng image is converted to jpg, although there are still some inaccuracies in the color and some darkness in the light, but I have some understanding, thank you very much

**Comment by helloworldgnu** [comment]
> If you do not have them, put them on your system and provide the path to them in your command. See profiles.zip at https://imagemagick.org/archive/delegates/

Using the two icc files you provided, and the above command, the dng image is converted to jpg, although there are still some inaccuracies in the color and some darkness in the light, but I have some understanding, thank you very much
