### ISSUE TITLE
Fails to read RAF-file

### ISSUE THREAD

**Issue by loth0** [ImageMagick/ImageMagick#5638]
### ImageMagick version

6.9.10-23

### Operating system

Linux

### Operating system, version and so on

Linux 5.15.0-25-generic #25-Ubuntu SMP

### Description

Throws exception when trying to read a RAF-file. A jpg in the same folder woks fine. Have tested with both raf and RAF extension.

PHP Version 8.0.24

```
    $im = new Imagick();
    $im->readImage("images/DSCF3480.RAF");
```

Exception:

```
Fatal error: Uncaught ImagickException: UnableToOpenBlob `/tmp/magick-27168D4wV2skgGqXt.ppm': No such file or directory
@ error/blob.c/OpenBlob/2874 in /.../index.php:63
Stack trace:
#0 /.../index.php(63): Imagick->readimage('images/DS...')
#1 {main}
thrown in /.../index.php on line 63
```

From phpinfo:
![image](https://user-images.githubusercontent.com/8112287/194751011-5726d364-ee12-42f7-9814-8228163ba77d.png)

### Steps to Reproduce

Make sure DSCF3480.RAF is on the server, and run the following code:

```
    $im = new Imagick();
    $im->readImage("images/DSCF3480.RAF");
```

### Images

[DSCF3480.RAF](https://image-upload.outdoordiversity.se/images/DSCF3480.RAF)

**Comment by snibgo** [comment]
The conversion works for me without complaint with ImageMagick v6.9.9-50 and v7.1.0-49 on Windows 8.1.

I suggest you try with just ImageMagick (not IMagick). Does this work?
```
convert DSCF3480.RAF x2.tiff
```
If that works, then the problem is not with ImageMagick.

**Comment by urban-warrior** [comment]
We converted the image from the command-line without issue.  We're using ImageMagick version 6.9.12-65.

**Comment by loth0** [comment]
The server is on a web hosting platform, and I don't have access to the convert command, so unfortunately I'm not able to test that.
