### ISSUE TITLE
IM 7.1.0.50 Release says "beta"

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#5646]
### ImageMagick version

7.1.0.50

### Operating system

MacOS

### Operating system, version and so on

Monterey

### Description

I downloaded the release from the release directory yesterday and installed it.  Both IM 7.1.0.50 and 6.9.12-65 say "beta".

Is this a mistake?

```
convert -version
Version: ImageMagick 6.9.12-65 beta Q16 aarch64 17481 https://legacy.imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr png ps raw rsvg tiff webp x xml zlib
fred@Fredericks-Mac-mini-2 ~ % 
fred@Fredericks-Mac-mini-2 ~ % 


magick -version
Version: ImageMagick 7.1.0-50 beta Q16-HDRI aarch64 20489 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr png ps raw rsvg tiff webp x xml zlib
Compiler: gcc (4.2)

```

### Steps to Reproduce

See above

### Images

None

**Comment by urban-warrior** [comment]
Its a production release.  To eliminate the `beta` tag, change `m4/version.sh/magick_is_beta` from `y` to `n` and rebuild.

**Comment by fmw42** [comment]
I do not understand. Is the 'beta' there a mistake or not? If a mistake, I do not mind it there so long as it would be removed in future production releases.

**Comment by rubyFeedback** [comment]
I think there is a slight miscommunication problem perhaps. IM tends to have many smaller releases. Users may be confused as to which of these releases may be beta and which ones not, since this is not easily discernable just from the (quickly changing) version.

**Comment by urban-warrior** [comment]
If its a beta release, `magick -version` returns `beta` in the Version value.  If it does not mention `beta`, its a production release.  This, for example, is a beta release:

```
$ magick -version
Version: ImageMagick 7.1.0-53 beta Q16-HDRI x86_64 20556 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(5.1) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig fpx freetype gvc heic jbig jng jp2 jpeg lcms lzma openexr pangocairo png raqm raw rsvg tiff webp x xml zip zlib
Compiler: gcc (13.9)
```
