### ISSUE TITLE
One green image when converting a PDF with text

### ISSUE THREAD

**Issue by MisiekDP** [ImageMagick/ImageMagick#5653]
### ImageMagick version

7.1.0-Q16-HDRI-x64

### Operating system

Windows

### Operating system, version and so on

Windows 10 Home 19044.1889

### Description

Hey,
I have a problem with converting PDF file (confirmation of transfer from Alior Bank) to other PDF file (with only magenta color-scale).
I use Ghostscript 9.56.1 and ImageMagick-7.1.0-Q16-HDRI-x64.
The command I use to convert is: `magick.exe convert -density 300 PDFin.pdf -background white -alpha background -alpha remove +level-colors magenta,white -quality 100 PDFout_MAGENTA.pdf`

The part of PDF input:
![image](https://user-images.githubusercontent.com/22171619/195441826-5a5a2082-d732-41ad-be3d-b5c615e93d34.png)

The part of PDF output:
![image](https://user-images.githubusercontent.com/22171619/195442033-27ca3aa9-cfb9-4298-bb36-59a6d8a11244.png)
The output PDF is one green image without visible text.

### Steps to Reproduce

1. Get two PDFs A5 from Alior Bank transfer confirmations (maybe other banks will works too).
2. Join two A5 PDFs to one A4 PDF using printing option "Adobe PDF":
![image](https://user-images.githubusercontent.com/22171619/195443377-b0b48d74-ce31-4657-9618-640375a44166.png)
3. Save new PDF file.
4. Convert PDF file using command: `magick.exe convert -density 300 PDFin.pdf -background white -alpha background -alpha remove +level-colors magenta,white -quality 100 PDFout_MAGENTA.pdf`

**Comment by MisiekDP** [comment]
And I can't upload input PDF because it contains personal data.

**Comment by snibgo** [comment]
If you can't share an actual PDF, we can only guess.

If your input PDF fully opaque? Does it have a transparent background? Is the background transparent black?

Why are you using "magick convert" instead of just "magick"?

**Comment by MisiekDP** [comment]
@snibgo Yes! I have a good news :) I found other PDF file which has this same problem.
There is a input PDF file:
[1instrukcja-AIB-pierwsze logowanie.pdf](https://github.com/ImageMagick/ImageMagick/files/9769181/1instrukcja-AIB-pierwsze.logowanie.pdf)


And my results:
Before convert:
![image](https://user-images.githubusercontent.com/22171619/195463700-ea105842-52cb-4b77-8cb4-8de4a50aa6be.png)

After convert:
![image](https://user-images.githubusercontent.com/22171619/195463739-e64aa303-5819-4f20-b3b4-a89940f6598d.png)

**Comment by MisiekDP** [comment]
I can upload a converted PDF file too but it has 70MB and it is not so easy on my Internet :/ But if it is necessary, I upload it.

**Comment by snibgo** [comment]
The main problem is that the input is encoded as CMYK, so colours work the opposite way you might expect. I suggest first converting it to sRGB, like this:
```
magick -density 300 logowanie.pdf[0] -colorspace sRGB -background white -alpha background -alpha remove +level-colors magenta,white out.pdf
```
Does that do what you want?

**Comment by MisiekDP** [comment]
> The main problem is that the input is encoded as CMYK, so colours work the opposite way you might expect. I suggest first converting it to sRGB, like this:
> 
> ```
> magick -density 300 logowanie.pdf[0] -colorspace sRGB -background white -alpha background -alpha remove +level-colors magenta,white out.pdf
> ```
> 
> Does that do what you want?

Yes! It works now awesome :D 
Awesome help, thank you!
