### ISSUE TITLE
Trying to name the right side of a picture first when using -crop

### ISSUE THREAD

**Issue by Roshri** [ImageMagick/ImageMagick#5668]
### ImageMagick version

ImageMagick 7.1.0-51 Q16-HDRI x64

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

As the title says, I'm trying to name the right side of a picture first when cropping.
I have some scans from books and comics in Japanese so the reading orientation is always right page first, but when I run
`magick convert .\*.jpg -crop 50%x100% output%02d.jpg`

It always names the left side as 01.jpg and right side as 02.jpg and so on.

I tried using the `-reverse` switch but using it on the whole folder reverses the whole batch of images and I need it to act per file basis
Is there a way to accomplish this?

### Steps to Reproduce

1- Gather some files on a folder
2- Run `magick convert .\*.jpg -crop 50%x100% output%02d.jpg`
3- It will always name the left side of the picture first

**Comment by snibgo** [comment]
For IM v7, I suggest using just "magick", not "magick convert".
```
magick .\*.jpg -flop -crop 50%x100% -flop output%02d.jpg
```

**Comment by Roshri** [comment]
Ohhh
This mirrors the picture, crops it and then mirrors it again, right?
That's great, it should work!

Thanks!

**Comment by snibgo** [comment]
Yes. "-crop" will always create the left-side first, then the right side. So we mirror-image (left-right) each input first, then crop each one, then mirror-image each of the results.

This is horribly inefficient, as every pixel must be copied at each "flop". But it works.
