### ISSUE TITLE
magick -script freezes at info: and at -delete mpr:name

### ISSUE THREAD

**Issue by mviereck** [ImageMagick/ImageMagick#5702]
### ImageMagick version

7.1.0-51 static build

### Operating system

Linux

### Operating system, version and so on

Debian 11

### Description

If I run an interactive `magick -script -`, it freezes in two cases, i.e. does not respond anymore, prints no error, does not exit. This happens if I type `info:` and if I try `-delete mpr:name`

### Steps to Reproduce

Example for `info:`:
```
$ magick -script -
rose:
info:
# type anything, magick won't react: freeze
```
I'd expect that it shows the same output as with `magick rose: info:`.

---------
Example: Try to delete an mpr:
```
$ magick -script -
rose:
-write mpr:test
-delete 0
-delete mpr:test
# freeze
```
Maybe I am wrong how I try to delete an mpr:, but I'd expect magick to error out instead of freezing.

**Comment by snibgo** [comment]
For the first problem, I suggest:
```
magick -script -
rose:
-write info:
-exit
```
For the second, "-delete mpr:test" is bad syntax. "-delete" should be followed by an integer. You can't delete an mpr image.

On this invalid command:
```
magick toes.png -write mpr:TEST -delete mpr:TEST NULL:
```
... IM gobbles CPU power, and does nothing. This seems to be a bug. It should raise an error about the bad "-delete".

**Comment by mviereck** [comment]
> For the first problem, I suggest:
> -write info:

Right, thank you! I was not aware that `-write` is mandatory for `info:`, too. However, once I see it, it is obvious.

> You can't delete an mpr image.

I need to reduce memory usage, so something like `-delete mpr:name` would be the obvious way and would be a useful feature.
Maybe this is a valid workaround, hopefully releasing memory:
```
$ magick -script -
rose:
-write mpr:test
-delete 0
-size 0x0
xc:white
-write mpr:test
-delete 0
-exit
```
This generates a small white image that is stored as the mpr:name that I'd like to remove from memory.

**Comment by snibgo** [comment]
"-size 0x0" isn't a valid size. Use "-size 1x1" instead.

"-write x.png" will overwrite x.png if it exists, freeing up any disk space it took up. We might hope that "-write mpr:TEST" would work the same way. Sadly, it doesn't seem to. For example:

```
%IM7DEV%magick -limit memory 1MB -size 10000x10000 xc: -write mpr:TEST -process pause -size 1x1 xc: -write mpr:TEST -process pause -exit
```
After the first "-write mpr:TEST", I have a temporary file of 2.4GB. After the second "-write mpr:TEST", that file is still there. I don't know if this is a bug.

To free memory, I suggest using parentheses and clones.

**Comment by mviereck** [comment]
> "-write x.png" will overwrite x.png if it exists, freeing up any disk space it took up. We might hope that "-write mpr:TEST" would work the same way. Sadly, it doesn't seem to. 

Good to know, thank you that you have checked this.
I'd say that the possibility to delete an mpr: (i.e. free its memory) is a core feature that should be available.

Maybe this could be forwarded to the code developers? Or should I open a feature request for `-delete mpr:name`?

Luckily I did not change too much code yet to use mpr:.
I have a script that, after some adjustment to use `magick -script` instead of multiple single `magick` calls, will create a magick script of several thousands of lines with several hundreds of images involved. So memory management is critical.

> To free memory, I suggest using parentheses and clones.

I had a first look at this possibility. Maybe I can partially use it, but it would (likely) heavily change the current workflow.

If I cannot delete/free `mpr:` at all, I am rather stuck with writing results to disk and read them back later, so I can use `-delete 0`. If I use a RAM disk (`XDG_RUNTIME_DIR` on linux) I can at least reduce disk i/o; however, there will still be wasted CPU usage to encode and decode the images.

**Comment by snibgo** [comment]
I agree that the ability to delete mpr:XX from the CLI (command line interface), freeing memory, would be useful. It is likely that a developer has read this thread.

> ... create a magick script of several thousands of lines with several hundreds of images involved.

Instead of using CLI, you might consider writing a compiled program, eg in C or C++, using the MagickCore or MagickWand interface. This would give you greater control over which operations affect which images, and how memory is used.

> ... I am rather stuck with writing results to disk and read them back later ...

If you do this, for performance I suggest using a file format with no compression, so encoding/decoding is trivial. For example, don't use PNG. You might use MIFF or MPC, which are formats proprietary to IM. Remember that IM can't delete these files from the CLI, so you would need to remove them later.

**Comment by urban-warrior** [comment]
Try `+set registry:mpr:TEST` to delete the image from the registry.

**Comment by mviereck** [comment]
> "-write x.png" will overwrite x.png if it exists, freeing up any disk space it took up. We might hope that "-write mpr:TEST" would work the same way. Sadly, it doesn't seem to. For example:

> %IM7DEV%magick -limit memory 1MB -size 10000x10000 xc: -write mpr:TEST -process pause -size 1x1 xc: -write mpr:TEST -process pause -exit

> After the first "-write mpr:TEST", I have a temporary file of 2.4GB. After the second "-write mpr:TEST", that file is still there. I don't know if this is a bug.

I've checked your example within `magick -script -`. I see a 1GB cache file appearing in `/tmp` that disappears after `size 1x1 xc: -write mpr:TEST`. So this seems to work here, different from your observation:
```
$ magick -script -
-limit memory 1MB
-size 10000x10000
xc:
# 1GB cache file appears
-write mpr:test
-delete 0
-size 1x1
xc:
-write mpr:test
# cache file disappears
-exit
```
The issue in your example might be a missing `-delete 0`, so the `xc:` image still needs cache. I cannot reproduce directly because my magick version does not know `-process pause`.

> Instead of using CLI, you might consider writing a compiled program, eg in C or C++, using the MagickCore or MagickWand interface. This would give you greater control over which operations affect which images, and how memory is used.

You are right. Currently I am familiar only with bash (at a rather high level), but not with other languages.
I consider to learn python3 because it has a magickWAND API. However, I am not entirely sure if it would fulfill my wishes of memory management and keeping alive the `magick` process instead of running it in multiple single shots.
I hesitate to do the major step top learn C/C++.
Would you recommend python3+magickWAND API?

------------
> Try +set registry:mpr:TEST to delete the image key from the registry. Deleting the image key reduces the reference count to the image and if the reference count is reduced to zero, image resources are freed.

I have tried this, but the cache file does not disappear, so I assume the memory is not freed:
```
$ magick -script -
-limit memory 1MB
-size 10000x10000
xc:
# 1GB cache file appears
-write mpr:test
-delete 0
+set registry:mpr:test
# cache file remains
-exit
# cache file disappears
```

**Comment by urban-warrior** [comment]
The cache file is the constant image you created.  Writing to the magick persistent registry (MPR) simply increases the reference count.  The `+set` option deletes the key from the registry and decrements the reference count.  However, the reference count remains @ 1 so the cache file is not removed.  You instead want to use `+set` to delete the registry key and `-delete` to delete the image and free up the cache file.

**Comment by mviereck** [comment]
> You instead want to use +set to delete the registry key and -delete to delete the image and free up the cache file.

I did that in my example. The image generated with `xc:` is removed with `-delete 0`, and `mpr:test` is removed with `+set registry:mpr:test`. So the reference count should be zero.
If I finally try `-write info:`, I get a message that no image is left:
```
$ magick -script -
-limit memory 1MB
-size 10000x10000
xc:
# 1GB cache file appears
-write mpr:test
-delete 0
+set registry:mpr:test
# cache file remains
-write info:
magick: no images for write '-write' 'info:' in "stdin" at line 8,column 1 @ error/operation.c/CLINoImageOperator/4946.
```
But the cache file remains.

**Comment by urban-warrior** [comment]
Use `+set registry:test` instead.

**Comment by mviereck** [comment]
> Use +set registry:test instead.

This one did the trick, thank you!

In general it might make sense to provide `-delete mpr:NAME` as an (alias) option for `+set registry:NAME`.

**Comment by snibgo** [comment]
> I see a 1GB cache file appearing in /tmp that disappears after size 1x1 xc: -write mpr:TEST. So this seems to work here ...

Good stuff. I use Windows, which may not free up memory in a measurable way.

> The issue in your example might be a missing -delete 0, ...

Yes, it was. I spotted the error and tried again, with the same result.

> Would you recommend python3+magickWAND API?

I use Python only when I really really have to. I prefer C. Partly because I don't like Python, but mostly because I like to limit the number of layers between my code and the code that does the real work (IM functions).

> > Use +set registry:test instead.

> This one did the trick, thank you!

Excellent.

**Comment by mviereck** [comment]
Just to collect the leftovers I suggest to fix:

Bug: In (at least) two cases of wrong syntax `magic -script -` freezes instead of throwing an error:
 - `info:` instead of `-write info:`
 - `-delete mpr:NAME`
 
Feature request:
 - Introduce `-delete mpr:NAME` as an alias for `+set registry:NAME`.

Aside from that, this ticket can be closed. Thank you again!

**Comment by urban-warrior** [comment]
A fix to hanging for the `-delete mpr:NAME` has already been applied to the `main` repo.  We will add support for `-delete NAME` within a day or two.

**Comment by mviereck** [comment]
> We will add support for -delete NAME within a day or two.

Great!
I'd suggest to rather use the scheme `-delete mpr:NAME` than `-delete NAME`, because it is more obvious what will be deleted, and everywhere else the leading `mpr:` is mandatory to access this memory image format. 
However, maybe you have reasons why to prefer `-delete NAME`.

**Comment by urban-warrior** [comment]
MPR is a specific coder for reading and writing images.  Registry is the system registry to store key/value pairs for text, images, or image info.   To us, it would not make sense to use `-delete mpr:NAME` rather than `-delete registry:NAME`.

**Comment by fmw42** [comment]
I may be out of order on this and have not followed it. But if I am creating -write MPR:named and wanted to delete it, I would think that -delete MPR:name would make sense rather than an obscure -delete Registry:name.

**Comment by urban-warrior** [comment]
MPR is a specific coder for reading and writing images.  For `mpr:name`, the MPR prefix tells ImageMagick to use the Magick Persistent Cache coder to write the image to the system registry and the registry key is `name`.  If you want to delete the image you just registered, you need to uniquely identify it-- in our example it would be `registry:name`.

**Comment by fmw42** [comment]
Just my two cents worth.  That is coder friendly, but not user friendly.

**Comment by urban-warrior** [comment]
Its been designed that way for several decades.  Changing it now will break existing scripts.

**Comment by mviereck** [comment]
Currently neither `-delete registry:NAME` nor `-delete mpr:NAME` exists.
So it is rather a question of parsing the new argument(s) and would not break existing scripts.

I just found that `-write registry:NAME` works and seems to have the same effect as `-write mpr:NAME`. Am I right?

So an option `-delete registry:NAME` would fit `-write registry:NAME`,
and an option `-delete mpr:NAME` would fit `-write mpr:NAME`.

They might do the same, but just have different notations.
However, `-delete mpr:NAME` might be restricted to `mpr` registry entries only, 
while `-delete registry:NAME` might as well delete other registry elements. (Not sure which might exist).

From a user point of view, `-write` and `-delete` should accept the same syntax, as @fmw42 already pointed out.

**Comment by urban-warrior** [comment]
`+set registry:NAME` exists and sets precedence.   Utilizing the orthogonality design principle, there should only be one way to do one thing-- which means the new `-delete` argument should be the same as `+set`. 

The `-write` and `-delete` options are different.  For `-write mpr:NAME`, the `mpr:` prefix explicitly sets the image format to Magick Persistent Registry, whereas, `NAME` is the registry key.  For `-delete`, we are deleting objects in the registry by key which has nothing to do with the image format.
