### ISSUE TITLE
Convert color dxp to mono

### ISSUE THREAD

**Issue by lundsimon** [ImageMagick/ImageMagick#5705]
### ImageMagick version

7.1.0-Q16-HDR!

### Operating system

Windows

### Operating system, version and so on

Windows 10 

### Description

A convert script I always used to convert color DPX to Mono is broken with this version of IM, I am able to write mono dpx out of c++ using the library but when I use this scipt, I get images with stripes in the image:

### Steps to Reproduce

FOR %%a in (*.dpx) DO convert %%a -grayscale Rec709luminance  %%a

### Images

[ColorDPX.zip](https://github.com/ImageMagick/ImageMagick/files/9902320/ColorDPX.zip)

**Comment by lundsimon** [comment]
To add a correction, writing mono tiff from c++ works but writing mono dpx does not, the same problem as the script above.
Magick::Image mgk2(combImage_2.cols, combImage_2.rows, "BGR", ShortPixel, (unsigned short*)combImage_2.data);
mgk2.depth(16);
mgk2.type(GrayscaleType);
mgk2.write(fileNameWithCountOut);

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
