### ISSUE TITLE
[Feature Request] Either modify -draw circle or provide a different functionality to specify radius

### ISSUE THREAD

**Issue by rubyFeedback** [ImageMagick/ImageMagick#5746]
### Is your feature request related to a problem? Please describe.

Hey ImageMagick folks,

Today I had to solve a problem in Java. But, it was complicated, so I used ruby, and imagemagick
to draw circles.

The only problem is: while determining the center of the circle, and having radius and diameter,
I had to specify a point on the outside of the circle (due to imagemagick requiring x2 and y2
coordinates there). My brain is not the best; I would prefer if I could tell imagemagick "use
the radius" instead. This is easier to draw, IMO. So, just the radius from that center position.
x1 and y1 are fine to specify, no problem.

Now I am **not** necessarily suggesting a change that invalidates existing scripts, but perhaps
there could be a special syntax, such as:

    -draw circle "x1,y1 r5.5"

or something like that. Or, alternative to that, a variant that allows that, via x1,y1,r where r is radius.

For instance:

    -draw circle_simple "x1, y1, r"

Or anything like that:

    -draw circle_radius "x1, y1, r"

This feature request is made every now and then. I saw it on a webforum phpbb style just before
I looked whether imagemagick had a github issue tracker.

Again, I am NOT suggesting to invalidate existing scripts per se (although perhaps, if we omit the
fourth parameter, we could ASSUME the user then meant radius, but again, I am not really
suggesting that). So I am more thinking to add an additional use case that is very similar
to circle, right now, but the sole difference is that we can specify a RADIUS instead.

The syntax above is just a suggestion. It can be different.

I think the more important thing is whether users and devs may agree (or not?) whether this
could be nice and useful and thus warrant a change or addition code-wise.

So this can then perhaps serve as a bit of a discussion. Perhaps it could be left open for
1-2 months before it is closed, so people can chime in?

Anyway thanks for reading, that's it.

### Describe the solution you'd like

See above please.

### Describe alternatives you've considered

See above please.

### Additional context

See above please.

**Comment by urban-warrior** [comment]
See https://imagemagick.org/Usage/draw/#circles where @fmw42  notes that by using a translation you can remove the need to calculate the circles edge coordinate, but can just give the radius directly.

```
  magick -size 100x60 xc:  -stroke SeaGreen  -fill PaleGreen  -strokewidth 2 \
          -draw 'translate 50,30 circle 0,0 25,0'   circle_circle_trans.gif
```

**Comment by fmw42** [comment]
See my method:

> [Fred Weinhaus](http://www.fmwconcepts.com/fmw/fmw.html) noted that by using a translation you can remove the need to calculate the circles edge coordinate, but can just give the radius directly.
> 
>   magick -size 100x60 xc:  -stroke SeaGreen  -fill PaleGreen  -strokewidth 2 \
>           -draw 'translate 50,30 circle 0,0 25,0'    circle_circle_trans.gif

Posted at https://imagemagick.org/Usage/draw/#circles

**Comment by mviereck** [comment]
This might be worth to be mentioned in the documentation of `-draw` at https://imagemagick.org/script/command-line-options.php#draw , additionally to the x2,y2 example for `circle`.
