### ISSUE TITLE
Libheif 1.14.0 isn't detected by the configure script

### ISSUE THREAD

**Issue by dmilith** [ImageMagick/ImageMagick#5783]
### ImageMagick version

7.1.0-52

### Operating system

Linux

### Operating system, version and so on

System agnostic issue

### Description

Configure script has Libheif 1.14.0 available in PREFIX, but:

```
checking for libheif >= 1.4.0... no
```

### Steps to Reproduce

Build libheif version 1.14.0 from source, then try building latest Imagemagick stable release

**Comment by dmilith** [comment]
Guess it's likely to this change: "library should now be initialized with heif_init()"

**Comment by urban-warrior** [comment]
We'll add heif_init() to the main branch.  Build ImageMagick and post any compile complaints or issues here.  Thanks.

**Comment by dmilith** [comment]
Well, I applied https://github.com/ImageMagick/ImageMagick/commit/e057607f1eb75e9059d896b9ff90711293d84015.patch as a patch for 7.1.0-52 with the same result: `checking for libheif >= 1.4.0... no`

**Comment by urban-warrior** [comment]
Post the validation step that failed.  See `config.log` and search for `heic`.

**Comment by dmilith** [comment]
Interesting… it says
```
configure:31813: result:
configure:31858: result: -------------------------------------------------------------
configure:31862: checking for libheif >= 1.4.0
configure:31869: $PKG_CONFIG --exists --print-errors "libheif >= 1.4.0"
configure:31872: $? = 0
configure:31886: $PKG_CONFIG --exists --print-errors "libheif >= 1.4.0"
configure:31889: $? = 0
configure:31903: result: no
Package 'libde265', required by 'libheif', not found
```

but after looking into my PREFIX I noticed this: `liblibde265.so` using the latest version (1.0.9). Although libheif is able to find that weirdly named shared object.

So I switched build mechanism from cmake to autotools for libde265 and it fixed the issue.

```
checking for libheif >= 1.4.0... yes
```

Is now correct with your patch applied :) Will write bug report to libde265 then. Thanks!
