### ISSUE TITLE
Bad result from aggressive trim

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#5798]
### ImageMagick version

7.1.0.52

### Operating system

MacOS

### Operating system, version and so on

Monterey

### Description

I am not getting an expected result from 

`-define trim:percent-background=0% -trim `

### Steps to Reproduce

Input:

![img](https://user-images.githubusercontent.com/13458218/203611877-0500de98-9c50-450c-be75-3c74f683a3f0.png)

```
magick img.png +repage -bordercolor black -border 2 -background black -define trim:percent-background=0% -trim +repage img_trim.png
```

Result

![img_trim](https://user-images.githubusercontent.com/13458218/203612001-b4cf7a58-c87d-45c1-9f65-e5b5b4b3b0df.png)

I would have expected something like:

![crop](https://user-images.githubusercontent.com/13458218/203612054-6601f9cb-5b94-425d-9764-c4fe8b6ccf81.png)

**Comment by urban-warrior** [comment]
Try fuzzing:

```
magick -fuzz 20% img.png +repage -bordercolor black -border 2 -background black -define trim:percent-background=0% -trim +repage ikg_trim.png
```

**Comment by fmw42** [comment]
Thanks that works.  But I do not understand why I need -fuzz 20% when all the background is pure black.
