### ISSUE TITLE
Documentation error for -composite

### ISSUE THREAD

**Issue by lurch** [ImageMagick/ImageMagick#58]
http://www.imagemagick.org/script/command-line-options.php?#composite says "The location of the 'source' or 'overlay' image is controlled according to -geometry, and -geometry settings." i.e. it mentions `-geometry` twice. I assume this is a mistake, but I don't know ImageMagick well enough to suggest what it's supposed to say.

**Comment by fmw42** [comment]
It is a typo. It should say -gravity and -geometry.  I will fix that. Look for it tomorrow if not sooner.

**Comment by lurch** [comment]
Why has this been closed? http://www.imagemagick.org/script/command-line-options.php?#composite still says "-geometry, and -geometry" and (assuming that that file is auto-generated) I can't see anything in the commit-history for this project's source code that suggests it's been fixed?

I've also just found that https://github.com/ImageMagick/ImageMagick/blob/master/www/command-line-options.html#L1436 has the `-geometry` flag repeated twice.

**Comment by fmw42** [comment]
I fixed it at http://magick.imagemagick.org/script/command-line-options.php#composite 3 days ago and I thought it would go over to http://www.imagemagick.org/script/command-line-options.php#composite automatically. 

dlemstra told me he merged it to GIT. I really do not know much about GIT, yet.  

Perhaps he can find out why it did not roll over automatically and correct the GIT if for some reason it did not make it there.

**Comment by dlemstra** [comment]
We have recently moved our website to a GIT repository. I closed this issue because I pushed these changes to our website repository. A commit does not automatically update the website. Your change will be shown there in a couple of days.

We have a script that mirrors our website and updates the www folder of the ImageMagick. The next time we run this the 'other' mistake will disappear also.

**Comment by lurch** [comment]
Thanks for the clarification, I didn't realise there was a separate repository for your website :-)
