### ISSUE TITLE
display delegate library support not built-in

### ISSUE THREAD

**Issue by exekutive** [ImageMagick/ImageMagick#5818]
### ImageMagick version

7.1.0-52

### Operating system

MacOS

### Operating system, version and so on

13.0.1

### Description

Unable to use 'display' command.
Error:
`display: delegate library support not built-in '' (X11) @ error/display.c/DisplayImageCommand/1901.

Installed via homebrew
env var 'DISPLAY' is set to zero

### Steps to Reproduce

execute commmand 'display logo.gif' inside XQuartz X11 terminal window

**Comment by dlemstra** [comment]
We do not maintain the homebrew installation. You will either need to build ImageMagick from source or request a change inside homebrew.
