### ISSUE TITLE
API method to set image filter

### ISSUE THREAD

**Issue by ansstuff** [ImageMagick/ImageMagick#5825]
### Is your feature request related to a problem? Please describe.

Some [ImageMagick docs](https://legacy.imagemagick.org/Usage/filter/nicolas/) recommend using "Distort Resize" instead of simple "Resize" for higher quality slower resizing.
With [MagickWand API](https://imagemagick.org/api/magick-image.php) it means using `MagickDistortImage()` instead of `MagickResizeImage()`. But `MagickDistortImage()` doesn't have a way to define which filter is used for resampling, it just uses currently configured filter, and there's no API methods to change the filter.

With commandline IM it's possible:
`magick.exe input.png -filter Lanczos -distort Resize 200x200! output.png`

So for now I have to run CLI process each time, with obvious drawbacks (disk IO, lost precision on conversions).

### Describe the solution you'd like

As suggested in [this discussion](https://github.com/emcconville/wand/discussions/601) (Wand is IM binding for Python) a clean solution would be introducing new API methods to get/set filter:

```c
FilterType MagickGetImageFilter(MagickWand *wand);
MagickBooleanType MagickSetImageFilter(MagickWand *wand, FilterType filter);

```

### Describe alternatives you've considered

Alternatively, `MagickDistortImage()` could use an additional argument `const FilterType filter`, similar to `MagickResizeImage()`, the argument may be useful for some other DistortMethods as well, not just 'resize'.

**Comment by urban-warrior** [comment]
Try `MagickSetOption(wand,"filter","Lanczos");` to set the image filter to Lanczos before you read your image.  Let us know if that works for you.

**Comment by ansstuff** [comment]
> Try `MagickSetOption(wand,"filter","Lanczos");` to set the image filter to Lanczos before you read your image. Let us know if that works for you.

It doesn't work, the "filter" option seems to be ignored.
Only MagickCore `SetImageOption` and then `SyncImageSettings` works, but Python binding of IM needs MagickWand API.
Thank you!

**Comment by urban-warrior** [comment]
We added support for image filters in MagickWand as you suggested.

**Comment by urban-warrior** [comment]
Done.
