### ISSUE TITLE
-clip-path unable to target Photoshop path when the name includes extended characters

### ISSUE THREAD

**Issue by FredrikEngquist** [ImageMagick/ImageMagick#5830]
### ImageMagick version

7.1.0-52

### Operating system

Linux

### Operating system, version and so on

also exists in earlier v7 version and on MacOS and Win OSes

### Description

When converting Photoshop images we need to address the clipping path by name since such images often contain many paths and the clipping path is not always guaranteed to be the first one.
This means I cannot use -clip or -clip-path "#1" but have to use the actual name: -clip-path "path_name".

This works well in most situations (e.g. with the PS English default 'Path 1') but I have now encountered an issue where the clipping path name is 'Tracé 1', which is the Photoshop default name in French versions. I also have the same issue with images that seem to originate from Asia.

I use:
magick 306629_03_2022_s.jpg[0] -background none -fill none -transparent none -alpha transparent -clip-path "Tracé 1" -alpha opaque -strip 306629_03_2022_s.png
to create a transparent PNG from an original image with a clipping path.

The attached image '306629_03_2022_s.jpg' contains 2 paths; 'Path 1' and 'Tracé 1' where the latter is the clipping path.

magick throws the following error:
"magick: no clip path defined '306629_03_2022_s.jpg': Undefined error: 0 @ error/image.c/ClipImagePath/722."

I am aware that I can address the paths by number (-clip-path "#2"), but unfortunately I do not know of a way to determine the number.
The whole point is that the Photoshop clipping path is unknown since an image can contain any number of paths and any one of them can be the actual clipping path as set in Photoshop.
The only way I know to find it among all the paths in the image is to use Exiftool to extract the name of it. This does not give me the number, only the name.

Photoshop 8BIM text seems to be encoded as MacRoman (unsurprising given it's origin) and I can extract the Clipping Path Name tag correctly using Exiftool with '-Photoshop:ClippingPathName -charset photoshop=MacRoman'.

Exporting the 8BIM profile to a .8bimtext file confirms this as demonstrated in this clip:

---
```
8BIM#2000#Path 1="&#0;&#6;&#0;&#0;&#0;&#0;&#0;&#0;[...]
8BIM#2001#Tracé 1="&#0;&#6;&#0;&#0;&#0;&#0;&#0;&#0;[...]
8BIM#3000#OriginDataIRB="&#0;&#0;&#0;&#16;&#0;&#0;[...]
8BIM#2999="&#7;Trac&#142; 1&#0;&#0;&#0;&#0;&#0;&#1;"
```
---
`'&#142;'` is the MacRoman coding of é.

This means that if 'image.c/ClipImagePath' doesn't actively read the path names as MacRoman and translte it to UTF-8 when matching the input I give as the -clip-path value there is no chance of actually achieving a match.

Ultimately, I will either need a way to read the clipping path number from the image (and I don't know of any tool that does this) or I need a fix in IM that addresses the paths in the 8BIM profile using the correct text encoding.

### Steps to Reproduce

Command:
`magick 306629_03_2022_s.jpg[0] -background none -fill none -transparent none -alpha transparent -clip-path "Tracé 1" -alpha opaque -strip 306629_03_2022_s.png`

magick throws the following error:
`"magick: no clip path defined '306629_03_2022_s.jpg': Undefined error: 0 @ error/image.c/ClipImagePath/722."`

### Images

Image:
![306629_03_2022_s](https://user-images.githubusercontent.com/69301299/204556670-48a7768c-0787-49f8-8f27-e90458dbd0d0.jpg)
zipped version:
[306629_03_2022_s.jpg.zip](https://github.com/ImageMagick/ImageMagick/files/10113967/306629_03_2022_s.jpg.zip)

**Comment by snibgo** [comment]
Are you suggesting that IM could guess that the pathname is encoded as MacRoman? I don't see how that could work. Or perhaps you want IM to translate the name given in the command to MacRoman, presumably using a "-define" or something.

In your other thread https://github.com/ImageMagick/ImageMagick/discussions/5807 , urban-warrior suggested using the external utility "iconv" to do the translation. Doesn't that work for you?

**Comment by dlemstra** [comment]
There is no need to start both an issue and a discussion.
