### ISSUE TITLE
HDR chromaticities and gamma

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#5835]
### ImageMagick version

7.1.0-52

### Operating system

Windows

### Operating system, version and so on

Any

### Description

This report follow from a discussion at https://github.com/ImageMagick/ImageMagick/discussions/5823

In coders\hdr.c function ReadHDRImage():
```
                  if (count == 8)
                    {
                      image->chromaticity.red_primary.x=chromaticity[0];
                      image->chromaticity.red_primary.y=chromaticity[1];
                      image->chromaticity.green_primary.x=chromaticity[2];
                      image->chromaticity.green_primary.y=chromaticity[3];
                      image->chromaticity.blue_primary.x=chromaticity[4];
                      image->chromaticity.blue_primary.y=chromaticity[5];
                      image->chromaticity.white_point.x=white_point[0],
                      image->chromaticity.white_point.y=white_point[1];
                    }

```
The comma after `white_point[0]` should be a semi-colon. I expect this makes no difference to the result.

After setting the chromaticity, the function calls:
```
  (void) SetImageColorspace(image,RGBColorspace,exception);
```
In MagickCore\colorspace.c, the function SetImageColorspace() sets chromaticities to zero. And then, as the requested colorspace is not LinearGRAY, the chromaticites are set to values for sRGB.

Hence the chromaticities that have been successfully read from an HDR file are then overwritten, which is bad.

A similar argument applies to image->gamma, which may have been read from the HDR file, but is overwritten by SetImageColorspace().

I'm not sure of the best solution. Perhaps move the call to `SetImageColorspace(image,RGBColorspace,exception);` to *before* the header is read and processed.

### Steps to Reproduce

magick.exe xc: -evaluate Pow 1.8 -set colorspace RGB -red-primary 0.734699,0.265301 -green-primary 0.159597,0.840403 -blue-primary 0.036598,0.000105 -white-point 0.345704,0.358540 x.hdr

The first few bytes of x.hdr are:
```
#?RADIANCE\n
GAMMA=1\n
PRIMARIES=0.734699 0.265301 0.159597 0.840403 0.036598 0.000105 0.345704 0.35854\n
FORMAT=32-bit_rle_rgbe\n\n
-Y 1 +X 1\n
```
... where "\n" represents a single byte, the usual unix new-line. This looks good to me.

Then:
```
magick x.hdr -verbose info:
```
The verbose info does *not* show any chromaticities, but it should.

### Images

N/A

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
