### ISSUE TITLE
unexpexted result of converting from grayscale jxl

### ISSUE THREAD

**Issue by multiSnow** [ImageMagick/ImageMagick#5836]
### ImageMagick version

7.1.0-53

### Operating system

Linux

### Operating system, version and so on

linux 6.0.8 amd64

### Description

Result converted from grayscale jxl file is corrupted (compared with the result converted by `djxl`).

(result of RGB jxl is correct.)

### Steps to Reproduce

generate a grayscale image in png format by imagemagick:
```shell
$ magick -size 100x60 xc:gray -fill white -stroke black \
       -draw "roundrectangle 20,10 80,50 20,15" test.png
```
the png image is in grayscale color:
```shell
$ identify test.png
test.png PNG 100x60 100x60+0+0 16-bit Grayscale Gray 1216B 0.000u 0:00.000
```
convert it (losslessly) into jxl format with the reference tools from [libjxl](https://github.com/libjxl/libjxl):
```shell
$ cjxl test.png out.jxl --quality=100
```
the jxl image is also in grayscale color:
```shell
$ jxlinfo out.jxl
JPEG XL file format container (ISO/IEC 18181-2)
JPEG XL image, 100x60, (possibly) lossless, 16-bit Grayscale
Color space: Grayscale, D65, gamma(0.454550) transfer function, rendering intent: Relative
```
then, convert back to png format:
```shell
$ mogrify -format png out.jxl
```

### Images

`test.png`, the grayscale png format image generated by `magick`:
![test](https://user-images.githubusercontent.com/2306079/205025503-4a87ff64-9424-4aa7-bdba-a5d2bb43c366.png)
`out.png`, the grayscale png format image converted from jxl format by `mogrify`:
![out](https://user-images.githubusercontent.com/2306079/205025898-c2e64bcd-97a2-41de-9dae-aa8abd1f6c3b.png)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by multiSnow** [comment]
https://github.com/ImageMagick/ImageMagick/commit/c327e0008b5139a0c9245d8f226405afa70ea23a is confirmed to fix this issue. Thinks.

**Comment by multiSnow** [comment]
It seems that the RGB colorspace corrupted this time...

generate:
```shell
$ magick -size 100x60 xc:cyan -fill red -stroke yellow \
    -draw "roundrectangle 20,10 80,50 20,15" test.png
```
other steps are same with above.

test.png:
![test](https://user-images.githubusercontent.com/2306079/205227101-54a75b99-5a5d-4b96-bd08-d33680d7f8b4.png)

out.png:
![out](https://user-images.githubusercontent.com/2306079/205227223-9858c7b9-5ad3-49b2-81c4-a6044ed283b7.png)
