### ISSUE TITLE
RSVG violates documentation on sRGB PNG chunk

### ISSUE THREAD

**Issue by ValZapod** [ImageMagick/ImageMagick#5850]
### ImageMagick version

7.1.0-53

### Operating system

Windows

### Operating system, version and so on

11 22H2

### Description

https://github.com/ImageMagick/ImageMagick/blob/b0cc8e4ae2c8cf48f8e059dd34ecbeff00b11a9d/coders/png.c#L12356-L12358

and
https://github.com/ImageMagick/ImageMagick/blob/b0cc8e4ae2c8cf48f8e059dd34ecbeff00b11a9d/www/defines.html#L1230

say that if gAMA is 2.2 gAMA chunk should not be written unless sRGB chunk is written. Not the case for SVG RSVG generator, and causes bad problems for Wikimedia Foundation, all wikipedia has wrong PNG previews and PNG converts (we do not use directly SVG).

### Steps to Reproduce

Use a SVG here: https://upload.wikimedia.org/wikipedia/commons/a/a4/Mastercard_2019_logo.svg

Now compare to https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Mastercard_2019_logo.svg/2560px-Mastercard_2019_logo.svg.png

created by magick.exe https://upload.wikimedia.org/wikipedia/commons/a/a4/Mastercard_2019_logo.svg test111.png

and that no longer has sRGB chunk but has gAMA chunk which breaks sRGB in Chrome/ Firefox. Indeed red color in mastercard logo in svg is sRGB #EB001B, but PNG has the same color #EB001B, but cause it is tagged as 2.2 gamma with sRGB display profile it will show as #EC0014.

This is even funnier: https://upload.wikimedia.org/wikipedia/commons/6/60/SMPTE_Color_Bars_16x9.svg

Issue in bugtracker: https://phabricator.wikimedia.org/T26768

SVG is sRGB unless tagged otherwise as part of Color v4 CSS specs.

**Comment by ValZapod** [comment]
As said in ImageMagick's documentation gAMA chunk must be excluded here.

**Comment by dlemstra** [comment]
Adding images for future reference.

![Mastercard_2019_logo](https://user-images.githubusercontent.com/10426229/205510733-ad14f2ce-e64e-4fed-993f-a981db036eff.svg)
![Mastercard_2019_logo svg](https://user-images.githubusercontent.com/10426229/205510734-3e080d81-b1d4-470d-8036-4691337cbff1.png)
![SMPTE_Color_Bars_16x9](https://user-images.githubusercontent.com/10426229/205510737-f70dbaef-5f2e-4cf8-a59c-5676de98f260.svg)

**Comment by urban-warrior** [comment]
We'll review the issue.  In the mean-time, add `-define png:exclude-chunk=gAMA` to your command-line to exclude the gamma chunk.

**Comment by ValZapod** [comment]
>In the mean-time, add -define png:exclude-chunk=gAMA to your command-line to exclude the gamma chunk.

Wikipedia is not going to do this.

**Comment by ValZapod** [comment]
I suppose the bug is deeper since 

magick.exe  https://upload.wikimedia.org/wikipedia/commons/a/a4/Mastercard_2019_logo.svg -define png:exclude-chunk=**sRGB** tes21212t3.png

produces a no gAMA too.

**Comment by urban-warrior** [comment]
Before we apply a patch, outline precisely what should be done with the sRGB and gAMA chunks?  Only write the gAMA chunk if the sRGB chunk is written too?  However, write the gAMA chunk if gamma is not 1.0/2.2?   Once we have a well defined recipe, we'll add a patch and push a new release .

**Comment by ValZapod** [comment]
"Only write the gAMA chunk if the sRGB chunk is written too. However, write the gAMA chunk if gamma is not 1.0/2.2 and no sRGB chunk."

**Comment by urban-warrior** [comment]
Try the main branch and see if the issue is resolved.

**Comment by ValZapod** [comment]
@urban-warrior Please just attach new png file here on github.

**Comment by urban-warrior** [comment]
Here is the chunk info with the latest patch:

```
$ magick https://upload.wikimedia.org/wikipedia/commons/a/a4/Mastercard_2019_logo.svg test111.png
$ pngcheck -v test111.png
File: test111.png (29373 bytes)
  chunk IHDR at offset 0x0000c, length 13
    1000 x 618 image, 32-bit RGB+alpha, non-interlaced
  chunk cHRM at offset 0x00025, length 32
    White x = 0.3127 y = 0.329,  Red x = 0.64 y = 0.33
    Green x = 0.3 y = 0.6,  Blue x = 0.15 y = 0.06
  chunk bKGD at offset 0x00051, length 6
    red = 0x00ff, green = 0x00ff, blue = 0x00ff
  chunk pHYs at offset 0x00063, length 9: 3779x3779 pixels/meter (96 dpi)
  chunk IDAT at offset 0x00078, length 29046
    zlib: deflated, 32K window, maximum compression
  chunk tEXt at offset 0x071fa, length 37, keyword: date:create
  chunk tEXt at offset 0x0722b, length 37, keyword: date:modify
  chunk tEXt at offset 0x0725c, length 40, keyword: date:timestamp
  chunk tEXt at offset 0x07290, length 25, keyword: Software
  chunk IEND at offset 0x072b5, length 0
No errors detected in test111.png (10 chunks, 98.8% compression).
```

Notice, no gAMA chunk.   Does that match your expectations?

**Comment by ValZapod** [comment]
Yes.
