### ISSUE TITLE
convert TIFF (16bit depth) to HEIC (>=12bit depth) creates invalid output file

### ISSUE THREAD

**Issue by mengmann** [ImageMagick/ImageMagick#5866]
### ImageMagick version

7.1.0-52 Q16-HDRI

### Operating system

MacOS

### Operating system, version and so on

Ventura 13.0.1 @Darwin Kernel Version 22.1.0

### Description

Hello,

the conversion from a TIFF 16 bit depth input file to HEIC output file with >=12bit depth produces a blank green image.

input file:

```
identify -verbose DSCF6250.tif
  ...
  Depth: 16-bit
  Channel depth:
    Red: 16-bit
    Green: 16-bit
    Blue: 16-bit
  ...
```

conversion to 8 and 10 bit depth works:
```
magick DSCF6250.tif -depth 8 DSCF6250_magick_8bit.heic
magick DSCF6250.tif -depth 10 DSCF6250_magick_10bit.heic
```
Both files can be opened and viewed properly.

But conversion to >=12 bit depth produces invalid output files.
There is no specific error message from cli. The output files just can't be viewed. I tested it with Mac preview.app and ApolloOne.app. I can see only a green blank image.

### Steps to Reproduce

```
magick DSCF6250.tif  DSCF6250_magick.heic # which defaults to 12 bit depth output
magick DSCF6250.tif -depth 12 DSCF6250_magick_12bit.heic
magick DSCF6250.tif -depth 14 DSCF6250_magick_14bit.heic
magick DSCF6250.tif -depth 16 DSCF6250_magick_16bit.heic
```
### Images

[DSCF6250.tif.zip](https://github.com/ImageMagick/ImageMagick/files/10185651/DSCF6250.tif.zip)

**Comment by dlemstra** [comment]
How did you check that those viewers support 12 bit images? And everything above 10 will be set to 12 bit.

**Comment by ValZapod** [comment]
Unfortunately ffmpeg still does not support all heic container (only in part needed for avif). So, I cannot test on my end. But it is possible 12 bit hevc does work, in fact it should be HW decoded on Turing just as VP9 is.
