### ISSUE TITLE
Convert raw to png,convert: Unsupported file format or not RAW file  @ error/dng.c/ReadDNGImage/521.

### ISSUE THREAD

**Issue by Robby0318** [ImageMagick/ImageMagick#5874]
### ImageMagick version

7.1.0-53

### Operating system

MacOS

### Operating system, version and so on

MacOS10.13

### Description

Successfully converted png to raw，
convert raw(raw,dng,cr2,crw,nef,orf,dcr,arw,mrw,raf) to png will report an error, the error is Unsupported file format or not RAW file @ error/dng.c/ReadDNGImage/521.

Use libraw (0.20.2) to support raw

### Steps to Reproduce

./configure   --enable-osx-universal-binary=no  --prefix=/Users/kell/Desktop/imagMagick/prefix --disable-opencl  --enable-shared   --enable-static   --with-freetype=yes   —with-gvc=no  --with-modules  --with-openjp2  --with-openexr  --with-webp=yes  --with-heic=yes  --with-raw=yes   --with-gslib  --with-gs-font-dir=/usr/local/Cellar/ghostscript/9.54.0/share/ghostscript/fonts  --with-lqr  --without-fftw  --without-pango  --without-wmf  --enable-openmp RAW_R_LIBS=/usr/local/Cellar/libraw/0.20.2/lib  RAW_R_CFLAGS=/usr/local/Cellar/libraw/0.20.2/include    CPPFLAGS=-I/usr/local/Cellar/libtool/2.4.6_4/include  LDFLAGS=-L/usr/local/Cellar/libtool/2.4.6_4/lib        --libdir=/Users/kell/Desktop/imagMagick/opt-imageMagick/lib  --includedir=/Users/kell/Desktop/imagMagick/opt-imageMagick/include

magick -version
Version: ImageMagick 7.1.0-53 Q16-HDRI x86_64 c91ce2143:20221204 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib fontconfig freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps raw tiff webp x xml zlib
Compiler: gcc (4.2)

magick  -list format
 3FR  DNG       r--   Hasselblad CFV/H3D39II (0.20.2-Release)
      3G2  VIDEO     r--   Media Container
      3GP  VIDEO     r--   Media Container
      AAI* AAI       rw+   AAI Dune image
       AI  PDF       rw-   Adobe Illustrator CS2
     APNG  VIDEO     rw+   Animated Portable Network Graphics
      ART* ART       rw-   PFS: 1st Publisher Clip Art
      ARW  DNG       r--   Sony Alpha Raw Image Format (0.20.2-Release)
   ASHLAR* ASHLAR    -w+   Image sequence laid out in continuous irregular courses
      AVI  VIDEO     r--   Microsoft Audio/Visual Interleaved
     AVIF  HEIC      rw+   AV1 Image File Format (1.12.0)
      AVS* AVS       rw+   AVS X image
    BAYER* BAYER     rw+   Raw mosaiced samples
   BAYERA* BAYER     rw+   Raw mosaiced and alpha samples
      BGR* BGR       rw+   Raw blue, green, and red samples
     BGRA* BGR       rw+   Raw blue, green, red, and alpha samples
     BGRO* BGR       rw+   Raw blue, green, red, and opacity samples
      BMP* BMP       rw-   Microsoft Windows bitmap image
     BMP2* BMP       rw-   Microsoft Windows bitmap image (V2)
     BMP3* BMP       rw-   Microsoft Windows bitmap image (V3)
      BRF* BRAILLE   -w-   BRF ASCII Braille format
      CAL* CALS      rw-   Continuous Acquisition and Life-cycle Support Type 1
           Specified in MIL-R-28002 and MIL-PRF-28002
     CALS* CALS      rw-   Continuous Acquisition and Life-cycle Support Type 1
           Specified in MIL-R-28002 and MIL-PRF-28002
   CANVAS* XC        r--   Constant image uniform color
  CAPTION* CAPTION   r--   Caption
      CIN* CIN       rw-   Cineon Image File
      CIP* CIP       -w-   Cisco IP phone image format
     CLIP* CLIP      rw+   Image Clip Mask
     CMYK* CMYK      rw+   Raw cyan, magenta, yellow, and black samples
    CMYKA* CMYK      rw+   Raw cyan, magenta, yellow, black, and alpha samples
      CR2  DNG       r--   Canon Digital Camera Raw Image Format (0.20.2-Release)
      CR3  DNG       r--   Canon Digital Camera Raw Image Format (0.20.2-Release)
      CRW  DNG       r--   Canon Digital Camera Raw Image Format (0.20.2-Release)
     CUBE* CUBE      r--   Cube LUT
      CUR* ICON      rw-   Microsoft icon
      CUT* CUT       r--   DR Halo
     DATA* INLINE    rw+   Base64-encoded inline images
      DCM* DCM       r--   Digital Imaging and Communications in Medicine image
           DICOM is used by the medical community for images like X-rays.  The
           specification, "Digital Imaging and Communications in Medicine
           (DICOM)", is available at http://medical.nema.org/.  In particular,
           see part 5 which describes the image encoding (RLE, JPEG, JPEG-LS),
           and supplement 61 which adds JPEG-2000 encoding.
      DCR  DNG       r--   Kodak Digital Camera Raw Image File (0.20.2-Release)
    DCRAW  DNG       r--   Raw Photo Decoder (dcraw) (0.20.2-Release)
      DCX* PCX       rw+   ZSoft IBM PC multi-page Paintbrush
      DDS* DDS       rw+   Microsoft DirectDraw Surface
    DFONT* TTF       r--   Multi-face font package (Freetype 2.11.0)
      DNG  DNG       r--   Digital Negative (0.20.2-Release)
      DOT  DOT       ---   Graphviz
      DPX* DPX       rw-   SMPTE 268M-2003 (DPX 2.0)
           Digital Moving Picture Exchange Bitmap, Version 2.0.
           See SMPTE 268M-2003 specification at http://www.smtpe.org
           
     DXT1* DDS       rw+   Microsoft DirectDraw Surface
     DXT5* DDS       rw+   Microsoft DirectDraw Surface
     EPDF  PDF       rw-   Encapsulated Portable Document Format
      EPI  PS        rw-   Encapsulated PostScript Interchange format
      EPS  PS        rw-   Encapsulated PostScript
     EPS2  PS2       -w-   Level II Encapsulated PostScript
     EPS3  PS3       -w+   Level III Encapsulated PostScript
     EPSF  PS        rw-   Encapsulated PostScript
     EPSI  PS        rw-   Encapsulated PostScript Interchange format
      EPT  EPT       rw-   Encapsulated PostScript with TIFF preview
     EPT2  EPT       rw-   Encapsulated PostScript Level II with TIFF preview
     EPT3  EPT       rw+   Encapsulated PostScript Level III with TIFF preview
      ERF  DNG       r--   Epson RAW Format (0.20.2-Release)
      EXR  EXR       rw-   High Dynamic-range (HDR) (OpenEXR 3.1.1)
 FARBFELD* FARBFELD  rw-   Farbfeld
      FAX* FAX       rw+   Group 3 FAX
           FAX machines use non-square pixels which are 1.5 times wider than
           they are tall but computer displays use square pixels, therefore
           FAX images may appear to be narrow unless they are explicitly
           resized using a geometry of "150x100%".
           
       FF* FARBFELD  rw-   Farbfeld
     FILE* URL       r--   Uniform Resource Locator (file://)
     FITS* FITS      rw+   Flexible Image Transport System
     FL32* FL32      rw-   FilmLight
      FLV  VIDEO     rw+   Flash Video Stream
  FRACTAL* PLASMA    r--   Plasma fractal image
      FTP* URL       r--   Uniform Resource Locator (ftp://)
      FTS* FITS      rw+   Flexible Image Transport System
     FTXT* FTXT      rw-   Formatted text image
       G3* FAX       rw-   Group 3 FAX
       G4* FAX       rw-   Group 4 FAX
      GIF* GIF       rw+   CompuServe graphics interchange format
    GIF87* GIF       rw-   CompuServe graphics interchange format (version 87a)
 GRADIENT* GRADIENT  r--   Gradual linear passing from one shade to another
     GRAY* GRAY      rw+   Raw gray samples
    GRAYA* GRAY      rw+   Raw gray and alpha samples
   GROUP4* TIFF      rw-   Raw CCITT Group4
       GV  DOT       ---   Graphviz
     HALD* HALD      r--   Identity Hald color lookup table image
      HDR* HDR       rw+   Radiance RGBE image format
     HEIC  HEIC      rw+   High Efficiency Image Format (1.12.0)
     HEIF  HEIC      rw+   High Efficiency Image Format (1.12.0)
HISTOGRAM* HISTOGRAM -w-   Histogram of the image
      HRZ* HRZ       rw-   Slow Scan TeleVision
      HTM* HTML      -w-   Hypertext Markup Language and a client-side image map
     HTML* HTML      -w-   Hypertext Markup Language and a client-side image map
     HTTP* URL       r--   Uniform Resource Locator (http://)
    HTTPS* URL       r--   Uniform Resource Locator (https://)
      ICB* TGA       rw-   Truevision Targa image
      ICO* ICON      rw+   Microsoft icon
     ICON* ICON      rw-   Microsoft icon
      IIQ  DNG       r--   Phase One Raw Image Format (0.20.2-Release)
     INFO  INFO      -w+   The image format and characteristics
   INLINE* INLINE    rw+   Base64-encoded inline images
      IPL* IPL       rw+   IPL Image Sequence
   ISOBRL* BRAILLE   -w-   ISO/TR 11548-1 format
  ISOBRL6* BRAILLE   -w-   ISO/TR 11548-1 format 6dot
      J2C* JP2       rw-   JPEG-2000 Code Stream Syntax (2.4.0)
      J2K* JP2       rw-   JPEG-2000 Code Stream Syntax (2.4.0)
      JNG* PNG       rw-   JPEG Network Graphics
           See http://www.libpng.org/pub/mng/ for details about the JNG
           format.
      JNX* JNX       r--   Garmin tile format
      JP2* JP2       rw-   JPEG-2000 File Format Syntax (2.4.0)
      JPC* JP2       rw-   JPEG-2000 Code Stream Syntax (2.4.0)
      JPE* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg 90)
     JPEG* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg 90)
      JPG* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg 90)
      JPM* JP2       rw-   JPEG-2000 File Format Syntax (2.4.0)
      JPS* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg 90)
      JPT* JP2       rw-   JPEG-2000 File Format Syntax (2.4.0)
     JSON  JSON      -w+   The image format and characteristics
      K25  DNG       r--   Kodak Digital Camera Raw Image Format (0.20.2-Release)
      KDC  DNG       r--   Kodak Digital Camera Raw Image Format (0.20.2-Release)
   KERNEL* KERNEL    -w-   Morphology Kernel
    LABEL* LABEL     r--   Image label
      M2V  VIDEO     rw+   MPEG Video Stream
      M4V  VIDEO     rw+   Raw VIDEO-4 Video
      MAC* MAC       r--   MAC Paint
      MAP* MAP       rw-   Colormap intensities and indices
     MASK* MASK      rw+   Image Clip Mask
      MAT  MAT       rw+   MATLAB level 5 image format
    MATTE* MATTE     -w+   MATTE format
      MEF  DNG       r--   Mamiya Raw Image File (0.20.2-Release)
     MIFF* MIFF      rw+   Magick Image File Format
      MKV  VIDEO     rw+   Multimedia Container
      MNG* PNG       rw+   Multiple-image Network Graphics (libpng 1.6.37)
           See http://www.libpng.org/pub/mng/ for details about the MNG
           format.
     MONO* MONO      rw-   Raw bi-level bitmap
      MOV  VIDEO     rw+   MPEG Video Stream
      MP4  VIDEO     rw+   VIDEO-4 Video Stream
      MPC* MPC       rw+   Magick Pixel Cache image format
     MPEG  VIDEO     rw+   MPEG Video Stream
      MPG  VIDEO     rw+   MPEG Video Stream
      MRW  DNG       r--   Sony (Minolta) Raw Image File (0.20.2-Release)
      MSL* MSL       rw+   Magick Scripting Language
     MSVG* SVG       rw+   ImageMagick's own SVG internal renderer
      MTV* MTV       rw+   MTV Raytracing image format
      MVG* MVG       rw-   Magick Vector Graphics
      NEF  DNG       r--   Nikon Digital SLR Camera Raw Image File (0.20.2-Release)
      NRW  DNG       r--   Nikon Digital SLR Camera Raw Image File (0.20.2-Release)
     NULL* NULL      rw-   Constant image of uniform color
      ORA  ORA       ---   OpenRaster format
      ORF  DNG       r--   Olympus Digital Camera Raw Image File (0.20.2-Release)
      OTB* OTB       rw-   On-the-air bitmap
      OTF* TTF       r--   Open Type font (Freetype 2.11.0)
      PAL* UYVY      rw-   16bit/pixel interleaved YUV
     PALM* PALM      rw+   Palm pixmap
      PAM* PNM       rw+   Common 2-dimensional bitmap format
    PANGO* PANGO     ---   Pango Markup Language
  PATTERN* PATTERN   r--   Predefined pattern
      PBM* PNM       rw+   Portable bitmap format (black and white)
      PCD* PCD       rw-   Photo CD
     PCDS* PCD       rw-   Photo CD
      PCL  PCL       rw+   Printer Control Language
      PCT* PICT      rw-   Apple Macintosh QuickDraw/PICT
      PCX* PCX       rw-   ZSoft IBM PC Paintbrush
      PDB* PDB       rw+   Palm Database ImageViewer Format
      PDF  PDF       rw+   Portable Document Format
     PDFA  PDF       rw+   Portable Document Archive Format
      PEF  DNG       r--   Pentax Electronic File (0.20.2-Release)
      PES* PES       r--   Embrid Embroidery Format
      PFA* TTF       r--   Postscript Type 1 font (ASCII) (Freetype 2.11.0)
      PFB* TTF       r--   Postscript Type 1 font (binary) (Freetype 2.11.0)
      PFM* PNM       rw+   Portable float format
      PGM* PNM       rw+   Portable graymap format (gray scale)
      PGX* PGX       rw-   JPEG 2000 uncompressed format
      PHM* PNM       rw+   Portable half float format
    PICON* XPM       rw-   Personal Icon
     PICT* PICT      rw-   Apple Macintosh QuickDraw/PICT
      PIX* PIX       r--   Alias/Wavefront RLE image format
    PJPEG* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg 90)
   PLASMA* PLASMA    r--   Plasma fractal image
      PNG* PNG       rw-   Portable Network Graphics (libpng 1.6.37)
           See http://www.libpng.org/ for details about the PNG format.
    PNG00* PNG       rw-   PNG inheriting bit-depth, color-type from original, if possible
    PNG24* PNG       rw-   opaque or binary transparent 24-bit RGB (zlib 1.2.11)
    PNG32* PNG       rw-   opaque or transparent 32-bit RGBA
    PNG48* PNG       rw-   opaque or binary transparent 48-bit RGB
    PNG64* PNG       rw-   opaque or transparent 64-bit RGBA
     PNG8* PNG       rw-   8-bit indexed with optional binary transparency
      PNM* PNM       rw+   Portable anymap
POCKETMOD  PDF       rw+   Pocketmod Personal Organizer
      PPM* PNM       rw+   Portable pixmap format (color)
       PS  PS        rw+   PostScript
      PS2  PS2       -w+   Level II PostScript
      PS3  PS3       -w+   Level III PostScript
      PSB* PSD       rw+   Adobe Large Document Format
      PSD* PSD       rw+   Adobe Photoshop bitmap
     PTIF* TIFF      rw+   Pyramid encoded TIFF
      PWP* PWP       r--   Seattle Film Works
      QOI* QOI       rw-   Quite OK image format
RADIAL-GRADIENT* GRADIENT  r--   Gradual radial passing from one shade to another
      RAF  DNG       r--   Fuji CCD-RAW Graphic File (0.20.2-Release)
      RAS* SUN       rw+   SUN Rasterfile
      RAW  DNG       r--   Raw (0.20.2-Release)
      RGB* RGB       rw+   Raw red, green, and blue samples
   RGB565* RGB       r--   Raw red, green, blue samples in 565 format
     RGBA* RGB       rw+   Raw red, green, blue, and alpha samples
     RGBO* RGB       rw+   Raw red, green, blue, and opacity samples
      RGF* RGF       rw-   LEGO Mindstorms EV3 Robot Graphic Format (black and white)
      RLA* RLA       r--   Alias/Wavefront image
      RLE* RLE       r--   Utah Run length encoded image
      RMF  DNG       r--   Raw Media Format (0.20.2-Release)
      RW2  DNG       r--   Panasonic Lumix Raw Image (0.20.2-Release)
      SCR* SCR       r--   ZX-Spectrum SCREEN$
      SCT* SCT       r--   Scitex HandShake
      SFW* SFW       r--   Seattle Film Works
      SGI* SGI       rw+   Irix RGB image
    SHTML* HTML      -w-   Hypertext Markup Language and a client-side image map
      SIX* SIXEL     rw-   DEC SIXEL Graphics Format
    SIXEL* SIXEL     rw-   DEC SIXEL Graphics Format
SPARSE-COLOR* TXT       -w+   Sparse Color
      SR2  DNG       r--   Sony Raw Format 2 (0.20.2-Release)
      SRF  DNG       r--   Sony Raw Format (0.20.2-Release)
  STEGANO* STEGANO   r--   Steganographic image
   STRIMG* STRIMG    rw-   String to image and back
      SUN* SUN       rw+   SUN Rasterfile
      SVG* SVG       rw+   Scalable Vector Graphics (XML 2.9.4)
     SVGZ* SVG       rw+   Compressed Scalable Vector Graphics (XML 2.9.4)
     TEXT* TXT       r--   Text
      TGA* TGA       rw-   Truevision Targa image
THUMBNAIL* THUMBNAIL -w+   EXIF Profile Thumbnail
     TIFF* TIFF      rw+   Tagged Image File Format (LIBTIFF, Version 4.3.0)
   TIFF64* TIFF      rw+   Tagged Image File Format (64-bit) (LIBTIFF, Version 4.3.0)
     TILE* TILE      r--   Tile image with a texture
      TIM* TIM       r--   PSX TIM
      TM2* TIM2      r--   PS2 TIM2
      TTC* TTF       r--   TrueType font collection (Freetype 2.11.0)
      TTF* TTF       r--   TrueType font (Freetype 2.11.0)
      TXT* TXT       rw+   Text
     UBRL* BRAILLE   -w-   Unicode Text format
    UBRL6* BRAILLE   -w-   Unicode Text format 6dot
      UIL* UIL       -w-   X-Motif UIL table
     UYVY* UYVY      rw-   16bit/pixel interleaved YUV
      VDA* TGA       rw-   Truevision Targa image
    VICAR* VICAR     rw-   Video Image Communication And Retrieval
      VID* VID       rw+   Visual Image Directory
     VIFF* VIFF      rw+   Khoros Visualization image
     VIPS* VIPS      rw+   VIPS image
      VST* TGA       rw-   Truevision Targa image
     WBMP* WBMP      rw-   Wireless Bitmap (level 0) image
     WEBM  VIDEO     rw+   Open Web Media
     WEBP* WEBP      rw+   WebP Image Format (libwebp 1.2.1 [020F])
      WMV  VIDEO     rw+   Windows Media Video
      WPG* WPG       r--   Word Perfect Graphics
        X* X         rw+   X Image
      X3F  DNG       r--   Sigma Camera RAW Picture File (0.20.2-Release)
      XBM* XBM       rw-   X Windows system bitmap (black and white)
       XC* XC        r--   Constant image uniform color
      XCF* XCF       r--   GIMP image
      XPM* XPM       rw-   X Windows system pixmap (color)
      XPS  XPS       r--   Microsoft XML Paper Specification
       XV* VIFF      rw+   Khoros Visualization image
      XWD* XWD       rw-   X Windows system window dump (color)
     YAML  YAML      -w+   The image format and characteristics
    YCbCr* YCbCr     rw+   Raw Y, Cb, and Cr samples
   YCbCrA* YCbCr     rw+   Raw Y, Cb, Cr, and alpha samples
      YUV* YUV       rw-   CCIR 601 4:1:1 or 4:2:2

**Comment by fmw42** [comment]
For IM 7 use magick not convert. What do you get from 

`magick identify -verbose your-raw-file`

Most of those raw formats are read only.

**Comment by Robby0318** [comment]
> For IM 7 use magick not convert. What do you get from
> 
> `magick identify -verbose your-raw-file`
> 
> Most of those raw formats are read only.
> 
> What were your exact command lines? Post your "raw" image that fails.

the same error: Unsupported file format or not RAW file @ error/dng.c/ReadDNGImage/521.
convert /Users/kell/Downloads/test1.raw /Users/kell/Downloads/test1.png
test1.raw: https://drive.google.com/file/d/18YA_QSWX44lyx3aIOKKjntzdXlPn818U/view?usp=sharing

**Comment by fmw42** [comment]
Your command is still using convert.  Try with magick in place of convert.

**Comment by fmw42** [comment]
How was your raw file created?  What type of raw file is it?

I get

`magick identify -verbose test1.raw`
identify: Unsupported file format or not RAW file `test1.raw' @ error/dng.c/ReadDNGImage/521.

If this is a raw format that is just binary data, no headers, etc, then you need to supply the dimensions and depth to read such format.  If this is a DNG, etc, then something is wrong. It is not compatible with libraw.  Photoshop and GraphicConverter open it fine. But Imagemagick will not.

We need more information how it was created.

**Comment by fmw42** [comment]
If DNG or the like, then preface the file in the read with that name as

`magick DNG:test1.raw test1.png`

**Comment by Robby0318** [comment]
> How was your raw file created? What type of raw file is it?
> 
> I get
> 
> `magick identify -verbose test1.raw` identify: Unsupported file format or not RAW file `test1.raw' @ error/dng.c/ReadDNGImage/521.
> 
> If this is a raw format that is just binary data, no headers, etc, then you need to supply the dimensions and depth to read such format. If this is a DNG, etc, then something is wrong. It is not compatible with libraw. Photoshop and GraphicConverter open it fine. But Imagemagick will not.
> 
> We need more information how it was created.



> How was your raw file created? What type of raw file is it?
> 
> I get
> 
> `magick identify -verbose test1.raw` identify: Unsupported file format or not RAW file `test1.raw' @ error/dng.c/ReadDNGImage/521.
> 
> If this is a raw format that is just binary data, no headers, etc, then you need to supply the dimensions and depth to read such format. If this is a DNG, etc, then something is wrong. It is not compatible with libraw. Photoshop and GraphicConverter open it fine. But Imagemagick will not.
> 
> We need more information how it was created.



> How was your raw file created? What type of raw file is it?
> 
> I get
> 
> `magick identify -verbose test1.raw` identify: Unsupported file format or not RAW file `test1.raw' @ error/dng.c/ReadDNGImage/521.
> 
> If this is a raw format that is just binary data, no headers, etc, then you need to supply the dimensions and depth to read such format. If this is a DNG, etc, then something is wrong. It is not compatible with libraw. Photoshop and GraphicConverter open it fine. But Imagemagick will not.
> 
> We need more information how it was created.

The raw image I got was converted to using the convert png to raw command

**Comment by fmw42** [comment]
Please show that command

**Comment by Robby0318** [comment]
> Please show that command

convert /Users/kell/Downloads/test.png  /Users/kell/Downloads/test1.raw

**Comment by fmw42** [comment]
OK.

`magick lena.png lena.raw`

works fine, but I do not know what type of raw file that is (DNG, NEF, etc)

but 

`magick lena.raw x.png`

fails as above.

**Looks like it might be a bug.**    So the IM developers will need to look into this.

**Comment by Robby0318** [comment]
> OK. On IM 7.1.0.53 Q16 HDRI Mac OSX Monterey
> 
> `magick lena.png lena.raw`
> 
> works fine (and Photoshop and GraphicConverter open it fine), but I do not know what type of raw file that is supposed to be (DNG, NEF, etc)
> 
> but
> 
> `magick lena.raw x.png`
> 
> fails as above.
> 
> **Looks like it might be a bug.** So the IM developers will need to look into this.



> OK. On IM 7.1.0.53 Q16 HDRI Mac OSX Monterey
> 
> `magick lena.png lena.raw`
> 
> works fine (and Photoshop and GraphicConverter open it fine), but I do not know what type of raw file that is supposed to be (DNG, NEF, etc)
> 
> but
> 
> `magick lena.raw x.png`
> 
> fails as above.
> 
> **Looks like it might be a bug.** So the IM developers will need to look into this.

ok thanks for your help

**Comment by fmw42** [comment]
OK.  The file is a PNG (likely APNG) so you can read it as

`magick PNG:lena.raw x.png`

I am not sure if it is intended that .raw should write an APNG format file by default with the .raw suffix.  The IM developers will have to comment

**Comment by Robby0318** [comment]
> OK. The file is a PNG (likely APNG) so you can read it as
> 
> `magick PNG:lena.raw x.png`
> 
> I am not sure if it is intended that .raw should write an APNG format file by default with the .raw suffix. The IM developers will have to comment

ok thank you very much

**Comment by fmw42** [comment]
Properly, if you want a .raw or .rgb suffix file read or written, you need to supply the size and depth.  If you want a NEF or DNG, etc, you need to preface the file with that prefix (NEF:filename.nef or DNG:filename.dng).

It appears that specifying .raw without the size and depth, just creates a PNG.

**Is this the intended behavior of .raw?**.

Perhaps one of the IM developers would comment or someone who knows more about RAW files than I.

**Comment by fmw42** [comment]
Thanks for that clarification, snibgo.
