### ISSUE TITLE
ImageMagick-6.9.9-0 hardcodes the pkg-config command in the wrapper scripts

### ISSUE THREAD

**Issue by tgurr** [ImageMagick/ImageMagick#589]
While configure allows to specify the pkg-config command, e.g. for cross environments where it may be prefixed with the host triplet (x86_64-pc-linux-gnu-pkg-config) there are a few occurances where the pkg-config command is hardcoded to pkg-config:

* Magick++/bin/Magick++-config.in
* magick/Magick-config.in
* magick/MagickCore-config.in
* wand/MagickWand-config.in
* wand/Wand-config.in

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
