### ISSUE TITLE
WEBP files are twice the size they should be

### ISSUE THREAD

**Issue by dpthurst** [ImageMagick/ImageMagick#5895]
### ImageMagick version

7.1.0-56

### Operating system

Linux

### Operating system, version and so on

Debian unstable

### Description

The webp files produced by ImageMagick are approximately twice the size of files produced by `cwebp` or other programs with the same quality settings.

Reporting this bug is more difficult because `.webp` isn't allowed as a suffix on github, I'll do what I can to work around. The source image is `accelerated_rot.png` (in a lossless format for this step.)

### Steps to Reproduce

```
% cwebp -version
1.2.2
% cwebp accelerated_rot.png -q 50 -m 6 -o accelerated_rot-cwebp.webp
Saving file 'accelerated_rot-cwebp.webp'
(snip)
% ls -l accelerated_rot-cwebp.webp
-rw-r--r-- 1 dpt dpt 38598 Dec 20 07:46 accelerated_rot-cwebp.webp
% magick accelerated_rot.png -quality 50 -define webp:method=6 accelerated_rot-magick.webp
% ls -l accelerated_rot-magick.webp
-rw-r--r-- 1 dpt dpt 74274 Dec 20 07:48 accelerated_rot-magick.webp
```
I've attached my configuration file for compiling ImageMagick.
[config.log](https://github.com/ImageMagick/ImageMagick/files/10268481/config.log)

### Images

Source image:
![accelerated_rot](https://user-images.githubusercontent.com/13771964/208670170-4590e24e-ca84-4944-b50f-70c76a8d28b4.png)

Produced with `cwebp` (with suffix changed to allow an upload):
[accelerated_rot-cwebp.webm](https://user-images.githubusercontent.com/13771964/208672175-17a5c7d6-f274-45fb-b776-3b647cdf524e.webm)

Produced with `magick` (ditto):
[accelerated_rot-magick.webm](https://user-images.githubusercontent.com/13771964/208672309-63455085-954d-4595-807b-fd03415d9612.webm)

**Comment by urban-warrior** [comment]
Add `-strip` to your `magick` command-line to get similar results as `cwebp`.

**Comment by dpthurst** [comment]
Indeed, that works! It seems that color profiles are really very large in the scale of these images.
