### ISSUE TITLE
Batch Mode

### ISSUE THREAD

**Issue by stijnsanders** [ImageMagick/ImageMagick#5898]
### Is your feature request related to a problem? Please describe.

In order to increase performance by avoiding process start-up and tear-down operations, and the resources this uses, I would like to start a magick.exe process, that takes a series of other 'magick' command lines from standard-in, and performs these as magick.exe would, but then waits for the next command over standard-in.

### Describe the solution you'd like

For example a command line like `magick batch -separator 12 -idle-timeout 90`, which starts the batch mode and waits for commands like these sent over standard-in:

    identify -format="%wx%h" somefile.jpg
    convert somefile.png somefile1.jpg

Optional parameters could be:

"-separator" (default 13: carriage return) a required terminator to command lines sent over standard-in, that clearly determines where one command line stops and a next starts.

"-idle-timeout" (default none: wait indefinitely) a number of seconds after which, when no new command line is posted to standard-in, the batch-mode and the magick.exe instance terminates.

Optionally, while waiting for input, the 'health' of the standard-in handle/pipe should be checked for the case that the owning/commanding process has terminated. If so the batch-mode and magick.exe instance should also terminate. (I think this can be done on Windows using the PeekNamedPipe function.)

### Describe alternatives you've considered

Having a bulk image processing service call repeated `image.exe identify` and `image.exe convert` commands (each with a dedicated set of pipes for std-in,std-out,std-err to setup and cleanup). It _works_ but is less performant than the old ImageMagickObject before it because the system does more of the _plumbing._

MagickWand C API in theory would be an option, but involves housekeeping of the DLL's and their location, which we would like to prevent by using ImageMagick's portable versions which offers easier version updates.

**Comment by fmw42** [comment]
Perhaps Magick scripting is what you want.  See https://imagemagick.org/script/conjure.php and https://imagemagick.org/script/conjure.php#msl

**Comment by stijnsanders** [comment]
Sorry, no. Constructing incantations imply that one knows all the operations to perform onbeforehand. I would like to keep one (or more) magick.exe instances running, ready to perform identify or convert (or whatever) tasks as soon as 'the job comes in'...

**Comment by snibgo** [comment]
>  I would like to start a magick.exe process, that takes a series of other 'magick' command lines from standard-in, and performs these as magick.exe would, but then waits for the next command over standard-in.

That is ambitious. A simpler process has been proposed in the past, in the link provided by fmw42. For example:

> Basically you have a "magick" command running in background.  This
'co-process' reads in the images, and performs any tasks requested of it by
the parent shell script (or any other programming language).

As far as I know, this has not been implemented. I don't know how it would be implemented in Windows, or Unix, or other platforms supported by IM. And then it would need more work to accept arbitrary commands while running in the background.

If you know how to implement it, feel free...

**Comment by snibgo** [comment]
I should add that it would be easy to write a program that accepted characters from the console or a file, and executed those as ImageMagick options, then waited for more input. That program would be portable across any platform.

But I don't know how to implement that as a daemon (a "service"?) that could accept strings from any process.

**Comment by stijnsanders** [comment]
Oh, no not from _any_ process. Only one process (thread, even) would be in full control of one magick.exe 'batch' instance (and its standard-in, -out and -error handles). (Though, on Windows I would contemplate using a named pipe...)

**Comment by dlemstra** [comment]
I think it would be better to for you to create this functionality yourself. I don't think we should add a feature like this to ImageMagick.

**Comment by snibgo** [comment]
If anyone is interested: I have written a portable program that loops, waiting for IM commands to arrive at stdin, and executing each command. I have shown how to use this in various ways, including a primitive client-server to other processes can send it IM commands to execute.

See [Client-server](http://im.snibgo.com/cliserv.htm).

**Comment by stijnsanders** [comment]
I had a go at it myself! I'm handling incoming requests from stdin and are using the C API (the several [MagickCommand](https://github.com/ImageMagick/ImageMagick/blob/main/utilities/magick.c#L83)'s) to have them processed.
**Except** I had trouble with the C run-time not playing nice with my primary run-time (Delphi's in my case), and Magick's writing to stdout would end up _after_ any of mine. What's missing is a simple `fflush(file)` at the end of the ...ImageCommand functions. I solved it with a 'raw' call to ucrtbased.dll's `_fflush(__acrt_iob_func(1))`. Should I consider adding fflush(file) with a pull request?
