### ISSUE TITLE
No such file or directory (Windows 10 & Visual Studio 2015)

### ISSUE THREAD

**Issue by BusinessIQ** [ImageMagick/ImageMagick#59]
1)	ImageMagick installation completes successfully. 
2)	My VC++ console app compiles just fine but whenever I try to read an image from disk:

Image img("D:\\Projects\\Test.JPG"); (Please note that I am using double slash to escape)

The following error pops up:

Caught exception: ConsoleApplication14.exe: unable to open image 'h¸ñs(': No such file or directory @ error/blob.c/OpenBlob/2691

I have tried to reinstall and even switched to different versions of the package but the error remains.

Reading the images to a List seems to work fine.

list<Image> imageList;
	      readImages(&imageList, " D:\\Projects\\Test.JPG");

Can you please advise how I can correct this bug?

**Comment by dlemstra** [comment]
I have the feeling that it must be issue with your project settings. Can you share your project on something like dropbox? And the line number of the error corresponds with ImageMagick 7, do you also have this issue with ImageMagick 6?

**Comment by BusinessIQ** [comment]
https://www.dropbox.com/s/y5zdglwm3fkcsor/ConsoleApplication14.zip?dl=0
The application is nothing advance. I have been just trying to make the VC++ API work.


#include "stdafx.h"
#include <Magick++.h>
#include <string>
#include <iostream>
#include <list>
#include <fstream>
#include <string>

using namespace std;
using namespace Magick;

int main(int argc) {
	InitializeMagick("");
	
	try {
		// Read a file into image object 
		Image test("D:\\Projects\\test.JPG"); //<-- Exception is generated by this command The rest is actually not relevant.

		// Read images into STL list
		list<Image> imageList;
		readImages(&imageList, "d:\\projects\\test.jpg"); //<-- Works

		for each(Image i in imageList)
		{
			i.flip();
			i.quantizeColorSpace(GRAYColorspace);
			i.quantizeColors(256);
			i.quantize();

			i.type(GrayscaleType);
			//i.write("D:\\Projects\\TekNode\\Faktura\\test_flip2.jpg"); <- This line gives Write Access Violation
		}

		//for_each(imageList.begin(), imageList.end(), cropImage(Geometry(500, 500, 500, 500))); <-- Works fine
		//writeImages(imageList.begin(), imageList.end(), "d:\\projects\\teknode\\faktura\\test_flip.jpg"); <-- Works fine
	}
	catch (Exception &error_)
	{
		cout << "Caught exception: " << error_.what() << endl;
		system("pause");
		return 1;
	}
	system("pause");

	return 0;
}

**Comment by BusinessIQ** [comment]
Have you had a chance to look at this problem?

**Comment by dlemstra** [comment]
I am sorry but I haven't had time to look at it. I will try to check it this weekend

**Comment by dlemstra** [comment]
You are mixing debug and release in your project. Your project is build with the /MDd (C/C++ -> Code Generation -> Runtime Library) but our libraries are build with /MD. If you switch to release mode and set the lib/include settings that you used in debug mode it builds without any problems. You will need to build ImageMagick in Debug mode and link with the _DB_ libraries if you want to use /MDd

**Comment by BusinessIQ** [comment]
Thanks, that solved the problem.
