### ISSUE TITLE
"convert -colors 2" gives a single color image

### ISSUE THREAD

**Issue by plsamuel** [ImageMagick/ImageMagick#590]
When I run `convert ajaxwhite.png -colors 2 ajaxwhite.colors2.png`, the output file is an all-grey image.

![ajaxwhite](https://user-images.githubusercontent.com/854562/28367566-694cd5a6-6c5f-11e7-858b-ffdb9f041297.png)

output:

![ajaxwhite colors2](https://user-images.githubusercontent.com/854562/28367652-c2c7291a-6c5f-11e7-99a1-87212d8470a7.png)

Using imagemagick 6.9.7-4.  This used to work in ancient versions (6.6.4-10)

**Comment by glennrp** [comment]
Verified that current IM6-6.9.9-0 and IM7-7.0.6-1 create all-white images.  The input image consists only of gray pixels that are grey59 or lighter.

**Comment by mikayla-grace** [comment]
Try this command:

`convert ajaxwhite.png -normalize -colors 2 ajaxwhite.colors2.png`
