### ISSUE TITLE
How to add multiple text annotation?

### ISSUE THREAD

**Issue by kainingzhou** [ImageMagick/ImageMagick#5901]
### Is your feature request related to a problem? Please describe.

I wish to add multiple text annotations tob different locations of the same . jpg image using Magick. I tried many times, however, it can only add one annotation. Is there any solutions?

Thank you very much!  

### Describe the solution you'd like

I tried using piping to add multiple text annotations, but it didn't succeed.

**Comment by fmw42** [comment]
Just do -annotate multiple times in the same image.  See https://imagemagick.org/Usage/text/#annotate

**Comment by kainingzhou** [comment]
> Just do -annotate multiple times in the same image. See https://imagemagick.org/Usage/text/#annotate

Many thanks! I will try it out.
