### ISSUE TITLE
TGA Image Convert Bug Orientation

### ISSUE THREAD

**Issue by TemKaSD** [ImageMagick/ImageMagick#5906]
### ImageMagick version

7.1.0-55

### Operating system

Linux

### Operating system, version and so on

ubuntu 22.04

### Description

I use command convert 842974301_war3mapPreview.tga test.jpg.
test.jpg - bad orientation:

TGA sourse:
![image](https://user-images.githubusercontent.com/6318282/209429491-e1868a7d-0083-465b-8b1b-0dad38c1c0ce.png)

JPG Convert:

![image](https://user-images.githubusercontent.com/6318282/209429477-66f85ad1-ec33-4c9f-aa1a-1df5fbf94efc.png)

https://github.com/Imagick/imagick/issues/576#issuecomment-1364453100

### Steps to Reproduce

sudo convert 842974301_war3mapPreview.tga test.jpg

### Images
[842974301_war3mapPreview.zip](https://github.com/ImageMagick/ImageMagick/files/10298288/842974301_war3mapPreview.zip)

**Comment by dlemstra** [comment]
Can you please explain your issue here? And attach a test image?

**Comment by TemKaSD** [comment]
> Can you please explain your issue here? And attach a test image?

Done

**Comment by urban-warrior** [comment]
Try this command:

```
magick 842974301_war3mapPreview.tga -auto-orient test.jpg
```

**Comment by TemKaSD** [comment]
> 

Is ok

**Comment by urban-warrior** [comment]
We did not write nor maintain the PHP wrapper for ImageMagick.  The C method for auto orientation is AutoOrientImage().
