### ISSUE TITLE
The system cannot find the file specified error when using -resize

### ISSUE THREAD

**Issue by Bunnywood** [ImageMagick/ImageMagick#5910]
### ImageMagick version

7.1.0-55 Q16-HDRI x64

### Operating system

Windows

### Operating system, version and so on

Windows 10 Enterprise N 22H2 Build: 19045.2364

### Description

When using the -resize command I always get the error **The system cannot find the file specified.**

The following work just fine:
```
magick logo: logo.gif
magick instagram.png logo.gif
```

but as soon as I try this, I get the error

`magick instagram.png -resize '1080x1350<' resized.png`

### Steps to Reproduce

Fresh install of ImageMagick from the **ImageMagick-7.1.0-55-Q16-HDRI-x64-dll.exe** downloaded file.

In a folder containing a PNG image called instagram.png, with a current size of 955x1350, run the command:

`magick instagram.png -resize '1080x1350<' resized.png`

### Images

![Instagram](https://user-images.githubusercontent.com/59474346/209807020-91ee3d0e-a210-4e57-9d2c-cb151156655c.png)

**Comment by dlemstra** [comment]
On windows you will need to use `"` instead of `'`.

**Comment by Bunnywood** [comment]
OMG!
I can't believe it was that after all this time!
Thank you so much.
Happy New Year to you and yours.
