### ISSUE TITLE
Issue creating image from list of colors

### ISSUE THREAD

**Issue by urban-warrior** [ImageMagick/ImageMagick#5922]
<div type='discussions-op-text'>

<sup>Originally posted by **fmw42** January  2, 2023</sup>
### ImageMagick version

7.1.0.57

### Operating system

MacOS

### Operating system, version and so on

Monterey

### Description

I am trying to get block maxima from an image -- that is reduce the image storing maxima in each non-overlapping block. So I crop  the image in blocks and compute the maxima and store that as a list of colors with an Imagemagick header. This works. But when I try to interpolate that out to expand it back to the size of the input, it does not fill the output.

Input:

![lena](https://user-images.githubusercontent.com/13458218/210268679-71ab240b-148c-48de-880f-ec0908ad1270.png)

```
echo "# ImageMagick pixel enumeration: 4,4,255,srgb" > file2.txt
magick lena.png -crop 64x64 -format "%[pixel:s.maxima]\n" info: >> file2.txt
magick file2.txt -scale 256x256 y.png
```

The result is as follow showing that the last step, the -scale, does not work properly.

![y](https://user-images.githubusercontent.com/13458218/210268759-aac7d82e-4c5a-487b-9c1b-a496410eb590.png)

Here is file2.txt

[file2.txt](https://github.com/ImageMagick/ImageMagick/files/10333134/file2.txt)

If I do it using NetPBM, it works fine

```
magick lena.png -crop 64x64 -format "%[pixel:s.maxima]\n" info: |\
sed 's/^[^0-9]*\([0-9]*\),\([0-9]*\),\([0-9]*\).*$/\1 \2 \3/g' > file3.txt
list=`cat file3.txt`
echo "P3 4 4 255 $list" | magick - -scale 256x256 z.png
```

![z](https://user-images.githubusercontent.com/13458218/210268935-285ddad0-1d0e-4a38-bdbb-9db0e640d05d.png)

Here is file3.txt

[file3.txt](https://github.com/ImageMagick/ImageMagick/files/10333138/file3.txt)

**Am I not setting up file2.txt correctly?**

### Steps to Reproduce

See above

### Images

See above</div>

**Comment by urban-warrior** [comment]
Your image does not meet the requirements of the TXT image format.  To create the proper format, convert this image:

```
P2
4 4
255 255 255 246 255 255 255 249 247 255 249 249 247 250 224 248 253
```

It returns

```
# ImageMagick pixel enumeration: 4,4,0,255,gray
0,0: (255)  #FFFFFF  gray(255)
1,0: (255)  #FFFFFF  gray(255)
2,0: (246)  #F6F6F6  gray(246)
3,0: (255)  #FFFFFF  gray(255)
0,1: (255)  #FFFFFF  gray(255)
1,1: (255)  #FFFFFF  gray(255)
2,1: (249)  #F9F9F9  gray(249)
3,1: (247)  #F7F7F7  gray(247)
0,2: (255)  #FFFFFF  gray(255)
1,2: (249)  #F9F9F9  gray(249)
2,2: (249)  #F9F9F9  gray(249)
3,2: (247)  #F7F7F7  gray(247)
0,3: (250)  #FAFAFA  gray(250)
1,3: (224)  #E0E0E0  gray(224)
2,3: (248)  #F8F8F8  gray(248)
3,3: (253)  #FDFDFD  gray(253)
```

If you scale that image, you'll now get expected results.

**Comment by fmw42** [comment]
Why is this now a discussion?  Is is not a bug in the image that is created from adding the header? Or have I missed something in the header?  Why does it not expand properly using -scale (or even -filter triangle -resize)?

**Comment by urban-warrior** [comment]
The image scaled properly, it just interpreted the colors differently than you expect because your TXT image was not in the expected format and therefore returning garbage pixel values.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by fmw42** [comment]
Thanks

**Comment by snibgo** [comment]
The "ftxt:" format can read the pixels from file2.txt, provided it has no header. Windows BAT syntax:
```
magick ^
  lena.png ^
  -set option:sizBlks %%[fx:ceil(w/64)]x%%[fx:ceil(h/64)] ^
  -crop 64x64 ^
  -format "%%[pixel:s.maxima]\n" +write info:temp2.txt ^
  -size %%[sizBlks] ^
  -define ftxt:format=\s\n ^
  -delete 0--1 ^
  ftxt:temp2.txt ^
  -scale 256x256 ^
  x.png
```

**Comment by fmw42** [comment]
I am still getting the wrong output using IM 7.1.0.58 beta with

```
echo "# ImageMagick pixel enumeration: 4,4,255,srgb" > file2.txt
magick lena.png -crop 64x64 -format "%[pixel:s.maxima]\n" info: >> file2.txt
magick file2.txt -scale 256x256 y.png
```

**Was the old style txt format not implemented again in the beta?**

**Comment by urban-warrior** [comment]
We get expected results with -58 Beta:

```
 Histogram:
          4096: (224,224,224) #E0E0E0 gray(224)
          4096: (246,246,246) #F6F6F6 gray(246)
          8192: (247,247,247) #F7F7F7 gray(247)
          4096: (248,248,248) #F8F8F8 gray(248)
         12288: (249,249,249) #F9F9F9 gray(249)
          4096: (250,250,250) #FAFAFA gray(250)
          4096: (253,253,253) #FDFDFD gray(253)
         24576: (255,255,255) #FFFFFF gray(255)
```

**Comment by fmw42** [comment]
Are you running from the beta or your development environment. I downloaded the .58 beta and do not get the same results from 

```
echo "# ImageMagick pixel enumeration: 4,4,255,srgb" > file2.txt
magick lena.png -crop 64x64 -format "%[pixel:s.maxima]\n" info: >> file2.txt
magick file2.txt -scale 256x256 y.png

```
and 

```
magick lena.png -crop 64x64 -format "%[pixel:s.maxima]\n" info: |\
sed 's/^[^0-9]*\([0-9]*\),\([0-9]*\),\([0-9]*\).*$/\1 \2 \3/g' > file3.txt
list=`cat file3.txt`
echo "P3 4 4 255 $list" | magick - -scale 256x256 z.png
```


`magick compare -metric rmse y.png z.png null:`
16553.7 (0.252593)

**Comment by fmw42** [comment]
Hold on. Let me check the version I used

**Comment by fmw42** [comment]
OK. My mistake. I was using the release and not the beta.  Everything works and I now get 0 for the compare difference.  So it is OK to close this topic.  Sorry, for the false alarm.
