### ISSUE TITLE
Popularity algorithm for color quantization

### ISSUE THREAD

**Issue by Jsfasdf250** [ImageMagick/ImageMagick#5927]
### Is your feature request related to a problem? Please describe.

ImageMagick's color quantization method isn't particularly well-suited to cartoon images. Such images have large regions of solid color, but not all of those common colors are chosen in the color palette, causing undesired dithering in regions which should be a single solid color.

### Describe the solution you'd like

I would like the Popularity method of color quantization to be implemented. Many implementations of the algorithm use a 4x4x4 bucket size, but I want every possible color to be its own bucket. The algorithm would simply find the colors that are most common in the image until the desired number of colors is reached. If there is a tie, then the color that is farthest from the colors already in the palette would be added to it, and this process is repeated until the exact number of colors desired is reached.

Perhaps an even better algorithm for cartoon images is to find the largest contiguous region of a single color, and add that color to the palette. Then, find the largest contiguous region of a different single color, add that color to the palette, and repeat until the desired number of colors is reached. If a tiebreaker is required, then the color(s) with the higher frequency would be kept. If that tiebreaker doesn't work, then a tiebreaker similar to the one described in the previous paragraph would be used. This algorithm not only considers what colors are used and their frequencies, but also how they're arranged within the image.

### Additional context

I reduce colors of images for making gifs. More specifically, I reduce colors of TrueColor spritesheets before ripping the sprites and making gifs from them. However, I found out that Ezgif (which uses ImageMagick) tends to produce gifs with higher color quality when using ripped sprites from the original spritesheet than when using ripped sprites from the color-reduced spritesheet.

**Comment by fmw42** [comment]
What is your IM version and platform?  If on IM 7, have you tried -kmeans, -mean-shift, -kuwahara

**Comment by Jsfasdf250** [comment]
I am using IM 7 and have tested out the -kmeans command, which resulted in more of the common colors chosen. However, there are many problems with the algorithm:

- It runs very slowly, especially when the desired number of colors (255) and the image size are very large (multi-megapixel)
- The algorithm relies on randomness, causing inconsistent results.
- There is no dithering applied.

I haven't used the other commands, but they probably won't suit my needs anyway.

If the algorithms I described couldn't be implemented directly as commands, is it at least possible to write scripts that implement them?

**Comment by fmw42** [comment]
> Perhaps an even better algorithm for cartoon images is to find the largest contiguous region of a single color, and add that color to the palette. Then, find the largest contiguous region of a different single color, add that color to the palette, and repeat until the desired number of colors is reached. If a tiebreaker is required, then the color(s) with the higher frequency would be kept. If that tiebreaker doesn't work, then a tiebreaker similar to the one described in the previous paragraph would be used. This algorithm not only considers what colors are used and their frequencies, but also how they're arranged within the image.

You can use -connected-components, if not too many colors to find contiguous regions. See https://imagemagick.org/script/connected-components.php. You can tell it to list the top N regions sorted by decreasing size with their mean colors. Then build your color table from that.

Does that help?

**Comment by fmw42** [comment]
What is your IM version and platform/OS?

**Comment by Jsfasdf250** [comment]
I am using Windows 11

**Comment by Jsfasdf250** [comment]
> > Perhaps an even better algorithm for cartoon images is to find the largest contiguous region of a single color, and add that color to the palette. Then, find the largest contiguous region of a different single color, add that color to the palette, and repeat until the desired number of colors is reached. If a tiebreaker is required, then the color(s) with the higher frequency would be kept. If that tiebreaker doesn't work, then a tiebreaker similar to the one described in the previous paragraph would be used. This algorithm not only considers what colors are used and their frequencies, but also how they're arranged within the image.
> 
> You can use -connected-components, if not too many colors to find contiguous regions. See https://imagemagick.org/script/connected-components.php. You can tell it to list the top N regions sorted by decreasing size with their mean colors. Then build your color table from that.
> 
> Does that help?

It's good to know that I don't have to code the connected-components algorithm myself, but I have little experience writing ImageMagick scripts, and there is still the question of how the tiebreakers would be implemented, which is important because I want the algorithm to always generate a palette with the exact number of colors needed (unless there are less colors in the original image than the number specified).

**Comment by snibgo** [comment]
I think this would be a useful addition to IM.

"`-remap`" is powerful and useful, with or without dithering, once a list of colours has been found. We can find the N (N<=256) colours from: (a) the N most common colours or (b) connected components sorted by size. These methods would be fairly easy in a script, or built-in to IM. Tie-breakers would be messy in a script.

So I would like an operation called, say, "`-reduce common N`" or "`-reduce connected N`" where N is an integer. It would make a Nx1 image of distinct colours that can then be used in "`-remap`".

**Comment by Jsfasdf250** [comment]
@snibgo Would it be possible for you to write scripts that implement each of the algorithms I described? (Preferably within the next few days)

**Comment by snibgo** [comment]
For a Windows script that makes a map of popular colours, see colProp.bat in [Frequent colours](http://im.snibgo.com/freqcol.htm).

**Comment by Jsfasdf250** [comment]
It displays a "Not Found" error, so could you just provide the code of the script directly?

**Comment by Jsfasdf250** [comment]
@snibgo Do you know how I'm supposed to use this with the terminal?

**Comment by snibgo** [comment]
Make a file for testing:
```
magick wizard: w.png
```

Suppose we want to remap w.png to the 16 most common colours that are in w.png.
```
call colProp w.png x.csv . . 16 map.png
```
Now map.png contains exactly 16 pixels, the most common colours. We use it in "`-remap`":
```
magick wizard: -remap map.png out.png
```
Job done.

Note that "`-remap`" will result in an image that contains *only* colours that are in the map image. So if you modifiy an image with any mechanism, then "`-remap`" to the original image, the result will contain *only* colours that are in the original.

**Comment by Jsfasdf250** [comment]
What happens if, in that example, the 16th and 17th most common colors appear with exactly the same frequency? I would prefer that the tiebreaker above (add the color that is farthest from the other colors already in the palette, and repeat) is implemented, but if it isn't, does it use all of the tied colors or none of them?

**Comment by Jsfasdf250** [comment]
> Make a file for testing:
> 
> ```
> magick wizard: w.png
> ```
> 
> Suppose we want to remap w.png to the 16 most common colours that are in w.png.
> 
> ```
> call colProp w.png x.csv . . 16 map.png
> ```
> 
> Now map.png contains exactly 16 pixels, the most common colours. We use it in "`-remap`":
> 
> ```
> magick wizard: -remap map.png out.png
> ```
> 
> Job done.
> 
> Note that "`-remap`" will result in an image that contains _only_ colours that are in the map image. So if you modifiy an image with any mechanism, then "`-remap`" to the original image, the result will contain _only_ colours that are in the original.

The execution stops at `if "%WW%"=="" exit /B 1`, even though I made sure that the file exists. Also, I got errors involving `echoOffSave` and `setInOut`. Is the script compatible with Windows 11?

**Comment by snibgo** [comment]
> What happens if, in that example, the 16th and 17th most common colors appear with exactly the same frequency?

You will get one of those colours. My script has no tie-breaking mechanism.

> Is the script compatible with Windows 11?

Yes.

> The execution stops at if "%WW%"=="" exit /B 1, even though I made sure that the file exists.

%INFILE% has not been set, because the call to setInOut failed.

> Also, I got errors involving echoOffSave and setInOut.

For repetitive stuff, my scripts call other scripts. See [Zipped BAT files](http://im.snibgo.com/zipbats.htm). You can download and unzip them all.

Or you can edit colProp.bat: remove calls to echoOffSave and echoRestore, and replace...
```
call %PICTBAT%setInOut %1 cp
```
... with ...
```
set INFILE=%1
```

**Comment by snibgo** [comment]
> -rThe system cannot find the file specified.

See my comment above:
> This uses the Cygwin "sort.exe", which uses "-r" for reverse order. Windows sort.exe uses "/R".

**Comment by Jsfasdf250** [comment]
After making changes to the script, I finally got it to work, but there are still some problems. When using `-remap` with the colormap, the resulting images tend to use completely different colors than what was originally there in some areas. I had to use GIMP to get better results, but even so, there are some regions of solid colors that became dithered. It turns out that the algorithm chose colors that are mostly the result of anti-aliasing that happened to be more common than the colors that actually take up some sizeable solid-color regions. Would you be able to implement the other algorithm I described?

From now on, I would like to reserve discussion here to be about implementation of the color reduction algorithms as commands, while using #5934 for further discussion about scripts.
