### ISSUE TITLE
Installation of imageMagick on AIX (Unix) machine shows error

### ISSUE THREAD

**Issue by abhikuhikar** [ImageMagick/ImageMagick#593]
Hello,

I want to install ImageMagick on AIX (Unix) machine.
But it shows error while using command ./configure as
" ./configure[10700]: syntax error at line 10707 : `;' unexpected " 

I am following the same process as you mentioned in 
[ImageMagick Advance Unix Installation]
(https://www.imagemagick.org/script/advanced-unix-installation.php)

And downloaded ImageMagick.tar.gz file and used following command
1. gunzip -d ImageMagick.tar.gz 
tar -xvf ImageMagick.tar // to unpack files
2. cd ImageMagick-7.0.6-1
3. ./configure --with-quantum-depth=8

"./configure --with-quantum-depth=8" This command shows error as
" ./configure[10700]: syntax error at line 10707 : `;' unexpected " 

Cofigure Output and Config.log file attached with this

[configurelog.txt](https://github.com/ImageMagick/ImageMagick/files/1164948/configurelog.txt)
[Cofigure.txt](https://github.com/ImageMagick/ImageMagick/files/1164949/Cofigure.txt)

Thank you in advance

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by bouchranechchach** [comment]
> Hello,
> 
> I want to install ImageMagick on AIX (Unix) machine. But it shows error while using command ./configure as " ./configure[10700]: syntax error at line 10707 : `;' unexpected "
> 
> I am following the same process as you mentioned in [ImageMagick Advance Unix Installation] (https://www.imagemagick.org/script/advanced-unix-installation.php)
> 
> And downloaded ImageMagick.tar.gz file and used following command
> 
>     1. gunzip -d ImageMagick.tar.gz
>        tar -xvf ImageMagick.tar // to unpack files
> 
>     2. cd ImageMagick-7.0.6-1
> 
>     3. ./configure --with-quantum-depth=8
> 
> 
> "./configure --with-quantum-depth=8" This command shows error as " ./configure[10700]: syntax error at line 10707 : `;' unexpected "
> 
> Cofigure Output and Config.log file attached with this
> 
> [configurelog.txt](https://github.com/ImageMagick/ImageMagick/files/1164948/configurelog.txt) [Cofigure.txt](https://github.com/ImageMagick/ImageMagick/files/1164949/Cofigure.txt)
> 
> Thank you in advance

**Comment by bouchranechchach** [comment]
Hello, I'm facing some difficultiess downloading ImageMagick for AX system, Any help would be appreciated

**Comment by bouchranechchach** [comment]
> Thanks for the problem report. We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
