### ISSUE TITLE
Crash on startup when updating from 7.1.0-29 to 7.1.0-57

### ISSUE THREAD

**Issue by Cyriuz** [ImageMagick/ImageMagick#5931]
### ImageMagick version

7.1.0-57

### Operating system

Windows

### Operating system, version and so on

Windows 11
With OpenMP

### Description

Due to this change deb080b28ef0216e2d0785db923445dee4e8fc41 (i think) a couple of code paths that was possible to run before InitializeMagick will now crash. In my case this call:

```
MagickCore::SetImageRegistry(MagickCore::StringRegistryType, "temporary-path", tempCacheDir, exception);
```

Will crash since the code in policy.c does this in a few places, specifically `IsPolicyCacheInstantiated`:
```
 if (policy_semaphore == (SemaphoreInfo *) NULL)
    ActivateSemaphoreInfo(&policy_semaphore);
```

Which is no longer allowed due to the above mentioned change.

Edit: I don't remember where I found that this api could be used before init so maybe it was never really supported? But if so if I want to set this in code do I have to pass it as an arg?

### Steps to Reproduce

```
MagickCore::SetImageRegistry(MagickCore::StringRegistryType, "temporary-path", tempCacheDir, exception);
Magick::InitializeMagick("");
```

**Comment by dlemstra** [comment]
The order of your method calls looks incorrect? You should call `InitializeMagick` before that other method.

**Comment by Cyriuz** [comment]
I did it that way because it was used during init, but when debugging now it is not, so either that was fixed or I was confused when I wrote this code! I suppose it is good that it is this way, I initially made the bug since I thought I had followed some docs that specified it should be set before init but I can't find that either. I'll just close it then and reopen if I remember why I had to do it before...
