### ISSUE TITLE
when i place Space between word in svg it show in UI but when i convert from svg to pdf by using Magick.NET it remove space.

### ISSUE THREAD

**Issue by ShrikantShinde1991** [ImageMagick/ImageMagick#5936]
### ImageMagick version

12.1.0.0

### Operating system

Windows

### Operating system, version and so on

windows 10

### Description

SVG given below please check. When i convert svg to PDF. The space is not shown in between word in PDF. If i put multiple space between word or after word or begin of word in svg. It show in UI but when i export by using Magick.NET dll then space is remove.
Also i use word-spacing,TextInterwordSpacing but it remove all space between word. 

### Steps to Reproduce

<?xml version="1.0" encoding="UTF-8" ?>
<svg viewBox="-1 -2 88 208" width="88" height="208" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" zoomAndPan="magnify">

<rect id="cad_2d_background" x="-1" y="-2" width="88" height="208" fill="rgb(255,255,255)" />
<defs>
</defs>
<g >
<text xml:space="preserve" transform="matrix(1.000000e+001 0.000000e+000 0.000000e+000 1.000000e+001 1.428571e-001 1.300000e+001)" style="font-family: romans" font-size="1.28571428571429px"  stroke="none" fill="rgb(0,0,0)"><tspan letter-spacing="0" font-weight='bold'  >ABCDEF</tspan></text>
<text xml:space="preserve" transform="matrix(1.000000e+001 0.000000e+000 0.000000e+000 1.000000e+001 1.428571e-001 3.000000e+001)" style="font-family: romans" font-size="1.28571428571429px"  stroke="none" fill="rgb(0,0,0)"><tspan letter-spacing="0" font-weight='bold'  > ABCDEF</tspan></text>
<text xml:space="preserve" transform="matrix(1.000000e+001 0.000000e+000 0.000000e+000 1.000000e+001 1.428571e-001 4.600000e+001)" style="font-family: romans" font-size="1.28571428571429px"  stroke="none" fill="rgb(0,0,0)"><tspan letter-spacing="0" font-weight='bold'  >  ABCDEF</tspan></text>
<text xml:space="preserve" transform="matrix(1.000000e+001 0.000000e+000 0.000000e+000 1.000000e+001 1.428571e-001 6.200000e+001)" style="font-family: romans" font-size="1.28571428571429px"  stroke="none" fill="rgb(0,0,0)"><tspan letter-spacing="0" font-weight='bold'  >ABC   DEF</tspan></text>
<polyline points="0.14,204.00 0.14,0.00 " fill="none"  stroke-width="0.25" stroke="rgb(0,0,0)" />
</g>

<g/>
</svg>

**Comment by dlemstra** [comment]
You should ask your question here instead: https://github.com/dlemstra/Magick.NET/discussions. Your question also does not seem to include an SVG file.

**Comment by ShrikantShinde1991** [comment]
<?xml version="1.0" encoding="UTF-8" ?>
<svg viewBox="-1 -2 88 208" width="88" height="208" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" zoomAndPan="magnify">

<rect id="cad_2d_background" x="-1" y="-2" width="88" height="208" fill="rgb(255,255,255)" />
<defs>
</defs>
<g >
<text xml:space="preserve" transform="matrix(1.000000e+001 0.000000e+000 0.000000e+000 1.000000e+001 1.428571e-001 1.300000e+001)" style="font-family: romans" font-size="1.28571428571429px"  stroke="none" fill="rgb(0,0,0)"><tspan letter-spacing="0" font-weight='bold'  >ABCDEF</tspan></text>
<text xml:space="preserve" transform="matrix(1.000000e+001 0.000000e+000 0.000000e+000 1.000000e+001 1.428571e-001 3.000000e+001)" style="font-family: romans" font-size="1.28571428571429px"  stroke="none" fill="rgb(0,0,0)"><tspan letter-spacing="0" font-weight='bold'  > ABCDEF</tspan></text>
<text xml:space="preserve" transform="matrix(1.000000e+001 0.000000e+000 0.000000e+000 1.000000e+001 1.428571e-001 4.600000e+001)" style="font-family: romans" font-size="1.28571428571429px"  stroke="none" fill="rgb(0,0,0)"><tspan letter-spacing="0" font-weight='bold'  >  ABCDEF</tspan></text>
<text xml:space="preserve" transform="matrix(1.000000e+001 0.000000e+000 0.000000e+000 1.000000e+001 1.428571e-001 6.200000e+001)" style="font-family: romans" font-size="1.28571428571429px"  stroke="none" fill="rgb(0,0,0)"><tspan letter-spacing="0" font-weight='bold'  >ABC   DEF</tspan></text>
<polyline points="0.14,204.00 0.14,0.00 " fill="none"  stroke-width="0.25" stroke="rgb(0,0,0)" />
</g>

<g/>
</svg>

**Comment by ShrikantShinde1991** [comment]
![No18_Test](https://user-images.githubusercontent.com/121941277/211241165-18ecde4b-eb5f-4cd7-8e47-602069a76ab9.svg)

**Comment by ShrikantShinde1991** [comment]
Please check attached file. This is svg file. After export svg to PDF then it removes space.
