### ISSUE TITLE
The "-monochrome" parameter loses all the visible information and gets a full black picture

### ISSUE THREAD

**Issue by barrer** [ImageMagick/ImageMagick#594]
convert -brightness-contrast -10x20 20170721.jpg 20170721-correct.png
convert -brightness-contrast -10x20 -monochrome 20170721.jpg 20170721-lost-information.png

picture:
https://github.com/barrer/bug-report/tree/master/imagemagick

environment:
https://github.com/barrer/bug-report/blob/master/imagemagick/20170721.txt

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by glennrp** [comment]
Verified that the bug exists in IM7-7.0.6-1 but not in IM6-6.9.9-0

**Comment by barrer** [comment]
@glennrp Thank you very much! I have installed 6.9.9 (brew install imagemagick@6), work perfectly! Wait until the 7 version of the repair I then test it!
