### ISSUE TITLE
GIF transparency regression

### ISSUE THREAD

**Issue by josephnaberhaus-wk** [ImageMagick/ImageMagick#5942]
### ImageMagick version

7.1.0-56

### Operating system

Linux

### Operating system, version and so on

Alpine 3.17.0 

### Description

Our integration tests have caught a change of behavior between 7.1.0-55 and 7.1.0-56. It seems like transparency is no longer being handled the same for GIFs.

### Steps to Reproduce

# GIF -> GIF

Source image:

![world](https://user-images.githubusercontent.com/50586585/210858980-3d5fe9a6-438f-4341-8a89-5ea0e178b230.gif)

Command:

```bash
convert -background none - -coalesce -scale 150x100! -layers optimize -
```

On 7.1.0-55 it would produce this image:

![world-150x100-low](https://user-images.githubusercontent.com/50586585/210858436-bb6d5113-088f-4dfc-b61e-3b8223fcc479.gif)

On 7.1.0-56 it produces this image:

![world-150x100-low](https://user-images.githubusercontent.com/50586585/210858839-757b80a7-0c1a-4915-9d50-b6c34ec3a0e5.gif)

Notice that. the blue ocean now has lot's of black artifacts in it.

# SVG -> GIF (using an RSVG delegate)

Source image:

![moon](https://user-images.githubusercontent.com/50586585/210859206-80fa44ce-c648-4e5f-93fb-26bfeea0fd5d.svg)

Command:

```bash
convert -background none - -layers optimize gif:-
```

On 7.1.0-55 it would produce this image:

![moon](https://user-images.githubusercontent.com/50586585/210859671-756808d5-3019-4f51-a3fb-9f9c0b89baa2.gif)

On 7.1.0-56 it produces this image:

![moon](https://user-images.githubusercontent.com/50586585/210859744-824dff7a-193c-43a0-b91e-b3f983b93cee.gif)

### Images

![world](https://user-images.githubusercontent.com/50586585/210859062-76cab393-f9f7-48c4-a4da-5f6ba40c2063.gif)
![moon](https://user-images.githubusercontent.com/50586585/210859206-80fa44ce-c648-4e5f-93fb-26bfeea0fd5d.svg)

**Comment by fmw42** [comment]
On IM 7.1.0.57 I get

magick 210859206-80fa44ce-c648-4e5f-93fb-26bfeea0fd5d.svg -layers optimize x.gif

![x](https://user-images.githubusercontent.com/13458218/210863568-ff33e4a1-cc73-44d9-9134-214c9761584f.gif)

So it looks fine.  However, my system uses Inkscape with Imagemagick to render the SVG.

**Comment by josephnaberhaus-wk** [comment]
@fmw42 Yeah, the results for that image are wildly different between MSVG, RSVG, and InkScape. It's also important (for this bug, and our use-case) to include the `-background none` portion. Otherwise, you get a white background.

The GIF of the world spinning is easier to reproduce since it doesn't involve a delegate.

**Comment by fmw42** [comment]
I do not see the issue with the spinning GIF?  What is the input and what is your output?  Have you provided the input, so that others can test?  What was your exact command line?  Using IM 7, use magick not convert (unless you have a symbolic link between them).

**Comment by fmw42** [comment]
OK. Sorry, I overlooked your input and command. It works fine for me on IM 7.1.0.57

`magick -background none 210858980-3d5fe9a6-438f-4341-8a89-5ea0e178b230.gif -coalesce -scale 150x100! -layers optimize x.gif`

![x](https://user-images.githubusercontent.com/13458218/210865355-20eba862-9b58-4c17-89b7-e2914bdb8368.gif)

**Comment by josephnaberhaus-wk** [comment]
@fmw42 It's kind of hard to see because of the lack of contrast, but there are black artifacts over the ocean.

Too make the problem more obvious, I've extracted the 6th frame from each GIF and increased the exposure of it:

Here's what it looks like on 7.0.1-55
![image](https://user-images.githubusercontent.com/50586585/210866736-fb7e5dc0-3fad-40c8-9824-91e887b13ef5.png)

Here's what it looks like on 7.0.1-56
![image](https://user-images.githubusercontent.com/50586585/210866823-b1f3ac76-129b-4552-b44a-5c09f593eb57.png)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by josephnaberhaus-wk** [comment]
Thanks for resolving this! I'm happy to report that we haven't seen any regressions since then.

I'll go ahead and close this issue.
