### ISSUE TITLE
Invalid arguments to magick

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#5946]
### ImageMagick version

7.1.0-54

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

Invalid arguments to `magick` gives a successful exit (ie it returns zero). I think it should return non-zero, and should set the exception parameter to indicate that there is a problem.

### Steps to Reproduce

```
C:\web\im>%IMG7%magick somejunk
Error: Invalid argument or not enough arguments

Usage: magick tool [ {option} | {image} ... ] {output_image}
Usage: magick [ {option} | {image} ... ] {output_image}
       magick [ {option} | {image} ... ] -script {filename} [ {script_args} ...]
       magick -help | -version | -usage | -list {option}


C:\web\im>echo %ERRORLEVEL%
0
```

### Images

N/A

**Comment by urban-warrior** [comment]
Agreed.  We'll commit a patch by sometime tomorrow.
