### ISSUE TITLE
Please use talloc lib for avoiding memory leak

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#595]
This a medium term goal in order to harden imagemagick.

Could you please use the talloc lib ?

it is the standard lib to use when you have memory leak due to object life....

It is well tested, portable and fast

https://talloc.samba.org/talloc/doc/html/index.html

**Comment by mikayla-grace** [comment]
Most of the recent leaks are associated with exceptions.  We run nearly 3000 ImageMagick unit tests against valgrind to detect leaks-- since they all complete without complaint, we missed the ones associated with exceptions.  However, yes, we will take a look at talloc(), likely in a few weeks.

**Comment by bastien-roucaries** [comment]
Talloc is portable, and if not you could ask upstream. 

Talloc will reduce the memory leak due to exception. If you free the main object it will free the children object. It is a little bit like c++ destructor.

I agree that it is not a drop in replacement. It is a medium term goal and it will reduce your technical debt by reducing the code line total in imagemagick. I think reducing your burden is a worthwhile goal

**Comment by urban-warrior** [comment]
Won't fix.  It would cause too much disruption in how ImageMagick allocates memory.
