### ISSUE TITLE
identify json output format

### ISSUE THREAD

**Issue by ror6ax** [ImageMagick/ImageMagick#5950]
### Is your feature request related to a problem? Please describe.

To use imagemagick identify as a part of a automated pipeline, I need to make it produce expected, formatted output.

### Describe the solution you'd like

I would like a flag that makes identify utility produce it's output as a valid JSON. This would allow me to use industry standard tools like jq in a pipeline to build whatever logic I need with ease, applying skills I already have.

### Describe alternatives you've considered

It seems I can use format flag to achieve structured output but it has an entire [page](https://imagemagick.org/script/escape.php) dedicated to how to use it. I can't use my skills from other software here. Frankly, I don't have time to learn, test and keep up with this formatting system.

**Comment by snibgo** [comment]
How about:
```
magick in.png json:
```

**Comment by ror6ax** [comment]
On my Linux, `identity in.png json:` produces exact same output as `identity in.png` does, but it also seems to hold the terminal indefinitely afterwards. :man_shrugging:

**Comment by fmw42** [comment]
Don't use identify, use convert.

`convert in.png json:`

or

`convert in.png json: > test.txt`

**Comment by ror6ax** [comment]
Ok, it seems to work, somehow. Seems like a hack though, convert does not sound like a utility for inspection, especially when inspect exists. Is one of them being phased out?

**Comment by fmw42** [comment]
Generally, you can do

`identify image.suffix`

or

`convert image.suffix info:`

But with json: output, json: is only available with convert as far as I know as a replacement format for info:.  There is no equivalent with identify as there is no info: part.

**Comment by snibgo** [comment]
@ror6ax: IM has many built-in input and output formats. (Some are output-only.) Examples are: PNG: TIFF: INFO: and JSON:

The "`identify`" program has limited power. I haven't used it seriously for years. It can't do anything that "`magick ... info:`" can't do.

"`identify`" isn't being deprecated, as far as I know. But if it doesn't do what you want, "`magick`" might.

You don't say what version of IM you use. "`magick`" is for IM v7. The equivalent in v6 is "`convert`". In v7, "`convert`" is available for backwards-compatibility.
