### ISSUE TITLE
mogrify leaves image file renamed when returning an error

### ISSUE THREAD

**Issue by mack3457** [ImageMagick/ImageMagick#5952]
### ImageMagick version

7.1.0-48

### Operating system

Other (enter below)

### Operating system, version and so on

FreeBSD 13.1-RELEASE-p3

### Description

When using mogrify on some files, it returns an error.

It seems to rename the original file before returning and leaves an almost empty file on exit.

This is bad on scripts using mogrify on thousands of images, possible failing on some.

File should be re-renamed before exit.

### Steps to Reproduce

Use below image file and do something like this:

```
[mack@www ~]$ ls -l  schloss.tif*
-rw-rw-r--  1 www  user  18572165 21 Feb.  2013 schloss.tif

[mack@www ~/bin]$ /usr/local/bin/mogrify -auto-orient -compress LZW  schloss.tif
mogrify: Using code not yet in table. `schloss.tif' @ error/tiff.c/TIFFErrors/597.

[mack@www ~]$ ls -l  schloss.tif*
-rw-r--r--  1 mack  user         8  9 Jan. 10:30 schloss.tif
-rw-rw-r--  1 www   user  18572165 21 Feb.  2013 schloss.tif~

[mack@www ~/bin]$
```

### Images

[schloss.tif.zip](https://github.com/ImageMagick/ImageMagick/files/10371997/schloss.tif.zip)

**Comment by dlemstra** [comment]
Can you reproduce this issue with the latest version?

**Comment by mack3457** [comment]
I upgraded ImageMagick7-nox11: 7.1.0.48 -> 7.1.0.50 - nothing newer in the package repository.

Problem is identical.

**Comment by fmw42** [comment]
Your file is corrupt!   Was that the input or output?  Be sure to provide the input file.

**Comment by urban-warrior** [comment]
The corrupt file was include under Images in the original posting.  We'll try to reproduce the problem and report back with a fix within a day or two.
