### ISSUE TITLE
When i place Space between word in svg it show in UI but when i convert from svg to pdf by using Magick.NET it removes all space.

### ISSUE THREAD

**Issue by ShrikantShinde1991** [ImageMagick/ImageMagick#5955]
### ImageMagick version

12.1.0.0

### Operating system

Windows

### Operating system, version and so on

windows 10

### Description

The SVG given below please check. When i convert SVG to PDF by using Magick.NET space is not shown in between word in PDF. If i put multiple space between word or after word or begin of word in SVG. It shows in UI but when i export by using Magick.NET dll then space is removed. Also, i use word-spacing,TextInterwordSpacing but it removes all space between word.

SVG file:-
![No18_Test](https://user-images.githubusercontent.com/121941277/211469801-e676d74c-3195-4a4a-aee4-03026bdc8905.svg)

output is shown below:-
[IPE_Demo_No18_Test (99).pdf](https://github.com/ImageMagick/ImageMagick/files/10379274/IPE_Demo_No18_Test.99.pdf)

### Steps to Reproduce

Please check svg file and try to convert it to pdf. Also, output is given in pdf format.

### Images

SVG File:
![No18_Test](https://user-images.githubusercontent.com/121941277/211471351-f9c2d92f-bfe7-4933-8d55-8788dee37343.svg)

Output pdf file:

[IPE_Demo_No18_Test (99).pdf](https://github.com/ImageMagick/ImageMagick/files/10379324/IPE_Demo_No18_Test.99.pdf)

**Comment by fmw42** [comment]
What SVG renderer are you using?  What font are you using? 

When I run

magick 211469801-e676d74c-3195-4a4a-aee4-03026bdc8905.svg x.pdf

on IM 7.1.0.57 Q16 Mac OSX Monterey with Inkscape 1.2.1, I get

[x.pdf](https://github.com/ImageMagick/ImageMagick/files/10379353/x.pdf)

**Comment by ShrikantShinde1991** [comment]
Do u change any thing in svg. Which SVG renderer r u using

**Comment by ShrikantShinde1991** [comment]
I apply only Format as SVG and Density(new Density(600, 600)

**Comment by ShrikantShinde1991** [comment]
Which version do u use for Magick.NET (i use this version Magick.NET-Q16-x64, Version=12.1.0.0.)
For convent SVG To PDF i use below code:-
using (MagickImageCollection collection = new MagickImageCollection())
          {
              using (StreamReader stringReader = new StreamReader(zipArchiveEntry.Open()))
                   {
                           MagickImage magickImage = new MagickImage(Encoding.UTF8.GetBytes(stringReader.ReadToEnd()), 
                          magickFormat);
                       collection.Add(magickImage);
                  }
        }
 MemoryStream collectionMemoryStream = new MemoryStream(); // NOTE inherent 2Gb limitation of this, would require use of UnmanagedMemoryStream if > 2Gb required
                        collection.WriteAsync(collectionMemoryStream, MagickFormat.Pdf, cancellationToken).GetAwaiter().GetResult();
                        collectionMemoryStream.Capacity = (int)collectionMemoryStream.Length; // truncate stream to actual content length so we can use GetBuffer (which gets all allocated)
                        return collectionMemoryStream.GetBuffer();

**Comment by ShrikantShinde1991** [comment]
<?xml version="1.0" encoding="UTF-8" ?>
<svg viewBox="-1 -2 88 208" width="88" height="208" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" zoomAndPan="magnify">

**Comment by fmw42** [comment]
Imagemagick can use 3 different SVG renderers:  its default MSVG/XML, RSVG delegate, Inkscape. If Inkscape in on your system it will be used automatically and is the best of the 3. Next would be RSVG delegate, which you have to install with your Imagemagick. Finally and least of the 3 is the default MSVG/XML.  Which do you have?  You can tell in command line mode using

`convert -list format`

Also what do you get from 

`convert -version`

Sorry, I know little about Magick.Net

**Install Inkscape and see if that helps.** I suspect you are using the default MSVG/XML, which is the poorest of the 3 options.

**Comment by dlemstra** [comment]
The default of Magick.NET is librsvg. Installing Inkscape might help.

**Comment by dlemstra** [comment]
I did not realize you just opened another issue while I told you to ask a question in the Magick.NET discussions instead, Also closing this issue here now.
