### ISSUE TITLE
Build heic failure on MinGW-W64/MSYS2

### ISSUE THREAD

**Issue by rageworx** [ImageMagick/ImageMagick#5958]
### ImageMagick version

master

### Operating system

Windows

### Operating system, version and so on

gcc version 12.2.0 (Rev6, Built by MSYS2 project)

### Description

I have tested multiple times to build ImageMagick latest version and current master branch.
It happens same time to build on MinGW-W64 with MSYS2.
`./configure` configured as well, then just tried to make, but always failure on this,
```
  CC       coders/MagickCore_libMagickCore_7_Q16HDRI_la-heic.lo
coders/heic.c: In function 'ReadHEICImageHandle':
coders/heic.c:333:18: warning: implicit declaration of function 'heif_image_hand
le_get_luma_bits_per_pixel'; did you mean 'heif_image_get_bits_per_pixel'? [-Wim
plicit-function-declaration]
  333 |   bits_per_pixel=heif_image_handle_get_luma_bits_per_pixel(image_handle)
;
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  heif_image_get_bits_per_pixel
coders/heic.c:358:12: error: 'heif_chroma_interleaved_RRGGBB_LE' undeclared (fir
st use in this function); did you mean 'heif_chroma_interleaved_RGBA'?
  358 |     chroma=heif_chroma_interleaved_RRGGBB_LE;
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            heif_chroma_interleaved_RGBA
coders/heic.c:358:12: note: each undeclared identifier is reported only once for
 each function it appears in
coders/heic.c:363:16: error: 'heif_chroma_interleaved_RRGGBBAA_LE' undeclared (f
irst use in this function); did you mean 'heif_chroma_interleaved_RGBA'?
  363 |         chroma=heif_chroma_interleaved_RRGGBBAA_LE;
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                heif_chroma_interleaved_RGBA
coders/heic.c: In function 'WriteHEICImage':
coders/heic.c:1228:18: error: 'heif_chroma_interleaved_RRGGBBAA_LE' undeclared (
first use in this function); did you mean 'heif_chroma_interleaved_RGBA'?
 1228 |           chroma=heif_chroma_interleaved_RRGGBBAA_LE;
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  heif_chroma_interleaved_RGBA
coders/heic.c:1236:20: error: 'heif_chroma_interleaved_RRGGBB_LE' undeclared (fi
rst use in this function); did you mean 'heif_chroma_interleaved_RGBA'?
 1236 |             chroma=heif_chroma_interleaved_RRGGBB_LE;
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                    heif_chroma_interleaved_RGBA
make[1]: *** [Makefile:10240: coders/MagickCore_libMagickCore_7_Q16HDRI_la-heic.lo] Error 1
```
It looks same issue of https://github.com/ImageMagick/ImageMagick/issues/4972, but seems not solved to other platform.

### Steps to Reproduce

1. Clone any version of ImageMagick on MSYS2
2. Do `./configure`
3. Then `make`

**Comment by dlemstra** [comment]
We build ImageMagick on MSYS for every commit on our main branch and if you go to the actions tab you can see that this build passes for the latest commit. ImageMagick requires at least version 1.4.0 of libheif and I suspect that you are using an older version. Not sure why this is not detected by your build system.

**Comment by dlemstra** [comment]
Please don't hijack other issues/discussions to ask me something @kmilos. And feel free to open up a pull request to change this.

**Comment by kmilos** [comment]
Fair enough, sorry.

**Comment by rageworx** [comment]
Is it mean libheif need to upgraded ?
There's no update by pacman -Syuu for now.
There before, I think configure may failed to complete job by testing libheif.

**Comment by fmw42** [comment]
ImageMagick requires at least version 1.4.0 of libheif. If your version is older, then yes, you need to upgrade to 1.4.0
