### ISSUE TITLE
Links changed in doc

### ISSUE THREAD

**Issue by ooker777** [ImageMagick/ImageMagick#5969]
In [Graphics from the Command Line](http://www.ibm.com/developerworks/library/l-graf/?ca=dnt-428 ""), these two links are obsolete:

- [Graphics from the Command Line](http://www.ibm.com/developerworks/library/l-graf/?ca=dnt-428)
- [More Graphics from the Command Line](http://www.ibm.com/developerworks/library/l-graf2/?ca=dgr-lnxw15GraphicsLine)

**Comment by dlemstra** [comment]
Thanks for reporting this. We have removed the links from our repository and this should be updated on our sites in a couple days.
