### ISSUE TITLE
composite -dissolve does not work

### ISSUE THREAD

**Issue by franklai** [ImageMagick/ImageMagick#597]
Hello,

I am using ImageMagick 6.9.8-10.

Using `composite -dissolve` does not change opacity.

Complete command is like
`composite -dissolve 25% -gravity south wmark_image.png logo.jpg wmark_dissolve.jpg`

Revert this commit seems to make `-dissolve` work again
https://github.com/ImageMagick/ImageMagick/commit/87be42439e1df8c51e7af5ea5d6591a8af499cf2

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
