### ISSUE TITLE
Getting this error on Magick lib version 7.1.0-2 "exception: Magick: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4470"

### ISSUE THREAD

**Issue by AbdulAzeezC** [ImageMagick/ImageMagick#5971]
### ImageMagick version

7.1.0-2

### Operating system

Linux

### Operating system, version and so on

NAME="SLES" VERSION="12-SP5" VERSION_ID="12.5" PRETTY_NAME="SUSE Linux Enterprise Server 12 SP5"

### Description

Getting this error on migrating to some latest Magick lib "exception: Magick: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4470"

currently we are using version imageMagick version 7.1.0-2
the same issue was not observed previously, as there is no change around this code since long time in our code.

some more inputs here we are trying to draw over an image & giving inputs like below (Note that some of the getter & setters are purely our application level.
If you can kindly help with the syntax of drawableText or something is got changed in between these versions prior to above mentioned version??

```
std::vectorMagick::Drawable aDrawList;
// font
aDrawList.push_back(DrawableFont(iImage.getDynAdFontFilePath()));
NGN_LOG_INFORMATION("Abdul Font related issue check "<< iImage.getDynAdFontFilePath()<<"\n"; // font color
aDrawList.push_back(DrawableFillColor(Color(iImage.getDynAdFontColor())));
// font size
aDrawList.push_back(DrawablePointSize(iImage.getDynAdFontSize()));
// text
const double aDX=BTB_Utils::convert<double, string>(iImage.getDynAdLocationX());
const double aDY=BTB_Utils::convert<double, string>(iImage.getDynAdLocationY());
aDrawList.push_back(DrawableText(aDX, aDY , iPriceCurrency));
```

As suggested I even tried to hard code the value directly inside the api DrawableFont("Courier-BoldOblique").
Here it used to pick the ttf file from a path, but it dint work somehow.
FYI the defaults fonts also had some issue with the setup hence all the ttf fonts were directly placed inside our project in some path.

Not sure if there is any syntax issue or any kind of setup issue also. If so kindly help to further debug it.

### Steps to Reproduce

```
std::vectorMagick::Drawable aDrawList;
// font
aDrawList.push_back(DrawableFont(iImage.getDynAdFontFilePath()));
NGN_LOG_INFORMATION("Abdul Font related issue check "<< iImage.getDynAdFontFilePath()<<"\n"; // font color
aDrawList.push_back(DrawableFillColor(Color(iImage.getDynAdFontColor())));
// font size
aDrawList.push_back(DrawablePointSize(iImage.getDynAdFontSize()));
// text
const double aDX=BTB_Utils::convert<double, string>(iImage.getDynAdLocationX());
const double aDY=BTB_Utils::convert<double, string>(iImage.getDynAdLocationY());
aDrawList.push_back(DrawableText(aDX, aDY , iPriceCurrency));
````

Kindly provide the direct values rather than getters & setter api's
Also do you suggest if any new changes were done around this area of code in draw.c file which might have impacted, if so then Should i have to get the latest magick lib version 7.2.1-57?

**Comment by urban-warrior** [comment]
ImageMagick version 7.1.0-2 is quite old.  Try your code-set with ImageMagick 7.1.0-57, the current release.  Let us know if that resolves the issue.  If not, post a complete (small) demo that throws the exception.  Assuming we can reproduce the problem locally, we will provide  a patch to fix the issue.

**Comment by AbdulAzeezC** [comment]
Hi @urban-warrior ,
I tried the same way as suggested by using the latest version 7.1.0-57
but looks like the issue is still the same 

```
exception: Magick: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4503 
```
Here is the reference to the code in draw.c file in MagickCore/draw.c highlighted below

```
  if (status == MagickFalse)
    **ThrowBinaryException(DrawError,"NonconformingDrawingPrimitiveDefinition",**
      keyword);
```

Below is the code sample snippet which tries to draw the image & text.
```
try{
Image aSrc_image(iImageFilePath+iImageFileName); //this is the path of image & its file name further on top of this the text is written.
std::vectorMagick::Drawable aDrawList;
aDrawList.push_back(DrawableFont(../test/data/fonts/Courier-BoldOblique.ttf) //this was the path where the ttf file for the font was residing is passed here
aDrawList.push_back(DrawableFillColor("#ffffff");
aDrawList.push_back(DrawablePointSize(30);
aDrawList.push_back(DrawableText(218, 48, "MyTextDisplay"));// --> May be the issues seems to be here i believe which causes the above mentioned error
aResultImage.draw(aDrawList);
}
catch(Exception& e)
  {
    cout<<"BTB_Utils::writeImgMgk - exception: " << e.what()<<endl;
    aSuccess = false;
  }
  catch(...)
  {
    cout<<"Unexpected Exception in ImgMagik flow"<<endl;
    aSuccess = false;
  }
```

**Comment by urban-warrior** [comment]
Your code does not compile, however, with small modifications it did-- and it produced expected results without throwing an exception.  We got an image with MyTextDisplay written on it.  We're using IM 7.1.0-57.

**Comment by AbdulAzeezC** [comment]
> Your code does not compile, however, with small modifications it did-- and it produced expected results without throwing an exception. We got an image with MyTextDisplay written on it. We're using IM 7.1.0-57.

ok... sorry my bad that it dint compile for you, as I pasted very small snippet...
But Please May I know what change was required to make this code work? I mean any thing on syntax or something?? I am still not able to get what might be the issue on our side.

**Comment by AbdulAzeezC** [comment]
Also May I know how is the setup of the environment done for fonts etc?? Is there any default path of font or any place from where u are loading the fonts??

Just want to understand how different is our environment from the one you have....

**Comment by fmw42** [comment]
Fonts can be anywhere if you use the path to the font file.  If you want to use font names, then you need to set up the type.xml file. See https://imagemagick.org/script/resources.php. Also you can use the following perl script to find and load all the usable fonts on your system.  See https://www.imagemagick.org/Usage/scripts/imagick_type_gen

**Comment by AbdulAzeezC** [comment]
Hi Team,

Here is the sample program i tried & got it reproduced.... on a different environment setup, which has freetype version 2.12.1 & imageMagick version installed is 7.1.0.57

`#include <string>
#include <iostream>
#include <Magick++.h>

using namespace std;
using namespace Magick;

int main(int /*argc*/,char **argv)
{
  try
  {
          InitializeMagick(*argv);
          Image image("/home/aazeezc/logo.jpg");
        std::vector<Magick::Drawable> aDrawList;
        // font
        aDrawList.push_back(DrawableFont("Courier-BoldOblique"));
        aDrawList.push_back(DrawableFillColor(Color("#000000")));
        // font size
        aDrawList.push_back(DrawablePointSize(100));
        // text
        aDrawList.push_back(DrawableText(200, 180 , "Abdul's Code"));
       image.draw(aDrawList);
        image.write("/home/aazeezc/logo2.jpg");
        image.display();
  }
catch( exception & error_ )
    {
      cout << "Caught exception: " << error_.what() << endl;
      return 1;
    }
  return 0;
}`

**compile step**: g++ -O2 -o example example.cpp `Magick++-config --cppflags --cxxflags --ldflags --libs`
**./example** -> on running this am able to get the same error i initially reported with the older version of imageMagick.

To conclude on the investigation, i did run the **make check** cmd this resulted in the error identified as below
**Caught exception: gravity: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1619
FAIL: Magick++/demo/demos.tap 5**


Another observation, I have not used this font **helvetica** but am using this font as in the code `aDrawList.push_back(DrawableFont("Courier-BoldOblique"));`

Kindly help if I have missed anything..... Also do run this cmd & see if it has same error on the version of freetype & imageMagick version i am using.

**Comment by urban-warrior** [comment]
We tried you example code and it worked for us with the latest release of ImageMagick.  We did not have the `Courier-BoldOblique` font so we substituted `arial`.

**Comment by murattkoc** [comment]
Hello Everyone,

I started getting the same error. I'm trying to generate an image using imagick v.3.4.3 but the same error comes up on the median. PHP 7.3.33-8+ubuntu20.04. 

My Code;

```
$image = new \Imagick($certificateTemplatePath);
$image = new \Imagick($certificateTemplatePath);
        // Reviewer Part
        $this->drawAwarded($image, $articleProcessReviewer->getUser()->getFullName());
      
        $maxWidth = 2500;
        $yMargin = 150;
        $yWrapMargin = 120;
        $y = 1000;
        $x = 230;
        $fontSize = 70;

        // ID Part
        $this->drawLabel($image, 'ID:', $x, $y, $fontSize);
        $articleIdDraw = new \ImagickDraw();
        $articleIdDraw->setFontSize($fontSize);
        $articleIdDraw->setFont('../app/fonts/arial.ttf');
        $image->annotateImage($articleIdDraw, $x + 520, $y, 0, $article->getId());
        $y += $yWrapMargin;

$image->setImageFormat('jpg');

```

Please help me.

**Comment by fmw42** [comment]
Please note that Imagemagick is not the creator or maintainer of Imagick. You should perhaps post to some Imagick forum. Also please create a new post. Do not add to an existing post with a different issue.

I am not an Imagick user so cannot help much. Perhaps someone else here who uses Imagick can check your code.  In which part of your code does the error arise? Perhaps the $x + 520 should be done outside the annotateImage command and the result of $x + 520 put into annotateImage. Just a guess.
