### ISSUE TITLE
TGA shows upside down

### ISSUE THREAD

**Issue by kasymovga** [ImageMagick/ImageMagick#5973]
### ImageMagick version

7.1.0

### Operating system

Linux

### Operating system, version and so on

void linux

### Description

tga files (event if they created by imagemagick) shows upside down.

### Steps to Reproduce

```
convert file.png file.tga
display file.tga               #file.tga shows upside down, but actually it's ok in other tools.
convert file.tga file.png      #now file.png upside down
```

**Comment by dlemstra** [comment]
You will probably need to add `-auto-orient` to your command and next time when you open up an issue please attach an image that can be used to reproduce your issue.

**Comment by kasymovga** [comment]
yes, `-auto-orient` working.
i was probably wrong about tga files created by `convert`. cannot reproduce. probably i used `gm convert` (tga files created this way showing upside down in `display` without `-auto-orient`).
so it's more like affect tga files created by other tools:
https://github.com/kasymovga/rexdlc/blob/master/powerups/gfx/hud/sb_akimbo.tga
this files was created with gimp and it's required this option otherwise it's upside down.

still it's not looks right, that random tga not working correctly without this extra option. maybe it must be enabled by default for tga files?

**Comment by dlemstra** [comment]
I have gave this some thought this weekend and I am going to make a change in our TGA coder later this week. We have had a couple questions why TGA files are not automatically rotated. For some of our coders we do this by default and we are also going to do this for the TGA coder. With the next release you will need to add `-define tga:preserve-orientation=true` to preserve the original orientation. Otherwise there will be an automatic change of the image orientation to `TopLeft`.

**Comment by ped7g** [comment]
> I have gave this some thought this weekend and I am going to make a change in our TGA coder later this week. We have had a couple questions why TGA files are not automatically rotated.

The original legacy TGA files contain lines stored from bottom up, just like legacy BMP. There's was no "orientation" data per se, and bit 5 in header was later extension IIRC. So to be most compatible with legacy tools and already written SW, the TGA files should be written bottom-up (and also read that way, unless the bit 5 is set in header).

The older versions of IM (don't know precise version, sorry) were working as expected and producing correct TGA files, now my base OS updated from Ubuntu 20.04 LTS to Ubuntu 22.04 LTS, and I have newer convert 6.9.11-60, and it's converting png files to tga with wrong orientation (no matter if I use -auto-orient or not, it just writes the TGA data in wrong order technically flipping the image upside down).
