### ISSUE TITLE
TIM2 decoder fails to read single-image TM2 files

### ISSUE THREAD

**Issue by LewisMCYoutube** [ImageMagick/ImageMagick#5978]
### ImageMagick version

7.1.0-57

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

The TIM2 coder is currently supposed to only support files which contain one image. But when trying to read TM2 files containing only one image, ImageMagick emits an error:

```identify: number of images is not supported `KeyboardShifted.tm2' @ error/tim2.c/ReadTIM2Image/699.```

This seems to make it impossible to read any TIM2 files at all. Other tools, like XnView MP, can read the files I've tested and identify them as containing one image:
![XnViewtm2test](https://user-images.githubusercontent.com/12817318/212734565-0901ae26-09b1-4ee6-84dd-4e489a0d8291.png)

### Steps to Reproduce

Run any command on a TIM2 file containing one image, like `magick identify 37.tm2`.

### Images

[37.tm2.zip](https://github.com/ImageMagick/ImageMagick/files/10427942/37.tm2.zip)
https://github.com/PSP-Archive/PSPVice/blob/main/gfx/KeyboardShifted.tm2
https://github.com/PSP-Archive/PSPVice/blob/main/gfx/KeyboardWiddy.tm2

**Comment by dlemstra** [comment]
The mipmap count of this image is two and we only support reading 1.

**Comment by dlemstra** [comment]
Reopening this issue because it looks like we are reading this file incorrectly. Not sure why but we will need to investigate this some time in the future.

**Comment by dlemstra** [comment]
Found what was causing this and this issue will be resolved in the next release. I am a now getting the following output images with my local development build:

![KeyboardShifted](https://user-images.githubusercontent.com/10426229/212864561-4d364d12-3e8b-4778-8ae0-d1e1958111b1.png)
![KeyboardWiddy](https://user-images.githubusercontent.com/10426229/212864568-05a70129-8151-4c84-abcf-7ed951eaf341.png)
