### ISSUE TITLE
MagickResourceLimitErrorException: pixel cache allocation failed

### ISSUE THREAD

**Issue by phil000** [ImageMagick/ImageMagick#5979]
### ImageMagick version

12.2.2

### Operating system

Windows

### Operating system, version and so on

10.0.14393

### Description

**Magick.NET-Q8-AnyCPU**
**12.2.2**

ImageMagick.MagickResourceLimitErrorException: pixel cache allocation failed `[0]' @ error/cache.c/AcquireCacheNexusPixels/5000

Getting this exception on our server in Azure, but when I try scaling the image locally in a unit test it works fine.

```
Exception: ImageMagick.MagickResourceLimitErrorException: pixel cache allocation failed `[0]' @ error/cache.c/AcquireCacheNexusPixels/5000
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result) in /_/src/Magick.NET/Native/NativeInstance.cs:line 63
   at ImageMagick.MagickImage.NativeMagickImage.AutoOrient() in /_/src/Magick.NET/Native/MagickImage.cs:line 4190
   at Onsend.Lib.Core.Drawing.ImageMagickResizer.CoreResizeImage(MagickImage image, Int32 maxWidth, Int32 maxHeight, Int32 quality) in /_/Onsend.Lib/Core/Drawing/ImageMagickResizer.cs:line 196
```

### Steps to Reproduce

Resize image (with a file that's too big for me to upload here). Seems to happen on the initial 'AutoOrient' we perform.

Original Image: 
64MP (6936 x 9248)
11.2 MB (11,770,438 bytes)

### Images

I can provide the image, it's just too big to upload here.

**Comment by dlemstra** [comment]
You are creating this issue in the wrong project. You should have asked for help here: https://github.com/dlemstra/Magick.NET/discussions. Closing this issue now.

It looks like you are running out of memory on your Azure server. Do you have enough memory in that server? And it might also be possible that you are running in 32-bit mode and then you will run out of memory much faster. I would advise you to first switch to `Magick.NET-Q8-x64` and give it another try.
