### ISSUE TITLE
New dlls for reading/writing JPEG XL, LIBHEIF, WEBP

### ISSUE THREAD

**Issue by JamesPous** [ImageMagick/ImageMagick#5986]
### Is your feature request related to a problem? Please describe.

Today I saw at github, that there are new sourcecodes available for different file formats.

JPEG XL 0.80 is available:
It has many interesting changes since version 0.70.
https://github.com/libjxl/libjxl

LIBHEIF 1.14.2 is available:
https://github.com/strukturag/libheif

LIBWEBP 1.30 is available:
https://developers.google.com/speed/webp/docs/precompiled?hl=en

### Describe the solution you'd like

I would be very nice to see the latest picture file import/export dlls in one of the next ImageMagick releases. Thank you!

**Comment by dlemstra** [comment]
Thanks for reporting this, your post made me create something that informs us about upgrades.
