### ISSUE TITLE
Images are incorrectly reported as not-fully-opaque with the %[opaque] format specifier

### ISSUE THREAD

**Issue by alexwlchan** [ImageMagick/ImageMagick#5987]
### ImageMagick version

7.1.0-52

### Operating system

Linux

### Operating system, version and so on

Alpine Linux

### Description

I'm using `identify -format '%[opaque]'` to detect images which are fully opaque, for example:

```console
$ identify -format '%[opaque]' IMG_1857.png
True  # => the image is fully opaque
```

But I've found a handful of images in my collection where ImageMagick is returning an false negative (as far as I can tell) – that is, all the pixels in the image are opaque, but it says they're not.

### Getting a version of ImageMagick

I originally observed this issue with a version of ImageMagick 7.1.0-57, which I'd compiled using [IMEI](https://github.com/SoftCreatR/imei) inside the ruby:3.1-slim Docker image.

To ensure it's not an issue with this particular installation, I've also run these steps inside an Alpine Linux Docker container with a pre-built version of ImageMagick:

```console
$ docker run -it -v $(pwd):/working --workdir /working alpine sh
$ apk add --update imagemagick
$ identify -version
# identify -version
Version: ImageMagick 7.1.0-52 Q16-HDRI aarch64 20549 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib cairo fontconfig freetype gslib heic jng jpeg jxl lcms ltdl lzma png ps rsvg tiff webp x xml zlib
Compiler: gcc (12.2)
```

### Reproducing the bug

1. Download one of the example images.
2. Run the following command in ImageMagick.

    ```console
    $ identify -format '%[opaque]' IMG_1877.3.png
    False
    ```

    Observe that ImageMagick returns `False` – it believes this image is not fully-opaque.

3. Open the image in an image editor, observe that it contains only opaque pixels.

    Or run the following Python script, which prints a list of distinct RGBA values in the image:

    ```python
    import sys

    from PIL import Image

    im = Image.open('IMG_1877.png')
    print(set(p for p in im.getdata()))  # {(7, 91, 164, 255)}
    ```

    Notice that all the colours have `alpha=255`, i.e. they're opaque pixels.

### Images

I found the following examples in a collection of 213 PNG images with an RGBA image profile; these were the three outliers where ImageMagick didn't match other tools. Unfortunately I don't remember how they were created.

I was able to reduce them to minimal examples using Preview.app on macOS, then I stripped the metadata using Acorn. I've included both the minimal examples and the original images, in case they're important.

Minimal examples:

<table>

<tr><td>

![blue](https://user-images.githubusercontent.com/301220/213589745-92dba382-4d4e-4854-a523-627ffd987adb.png)
</td><td>blue.png / from IMG_1877.png / 10×10 / 110 bytes<br/>sha256: <code>5c05dc6751cf606aab58bacc6c33232c045e82bda9d441ab8912f22db7c79edf</code></td></tr>

<tr><td>

![orange 1](https://user-images.githubusercontent.com/301220/213590255-74f5585b-35e4-429f-a983-81214ba730fc.png)
</td><td>orange.png / from happybackgrounds.png / 10×10 / 165 bytes<br/>sha256: <code>1eea523a39f4f866ff2d2e539661c68c61290c5e75fb9dc75e8973b7b64924fb</code></td></tr>

<tr><td>

![cream](https://user-images.githubusercontent.com/301220/213590642-9b4e8c9d-a48e-47e5-96cf-388981a13881.png)
</td><td>cream.png / from hackernews.png / 10×10 / 107 bytes<br/>sha256: <code>d8342e056d5ffa9fadcb51b254f79e0c7c3d3ba691955023137773532aa9a10d</code></td></tr>

</table>

Original images:

<table>
<tr><td>

![IMG_1877](https://user-images.githubusercontent.com/301220/213589907-b0c15c68-c060-4ee7-9f9a-d84c17da3a9c.png)
</td><td>IMG_1877.png / 1827 × 590 / 758KB<br/>sha256: <code>ee9554baf2c38ff7c86433baa89866183ce6a1f76e88a9b94bfff1524354d849</code></td></tr>

<tr><td>

![happybackgrounds](https://user-images.githubusercontent.com/301220/213590372-16f8d2c1-a874-43d6-8bdd-fca2d21149b0.png)
</td><td>happy backgrounds.png / 503 × 444 / 215KB<br/>sha256: <code>af336f8058cb21124da042898931eb10bb8bc4c9548ceaca952b00118ed497e8</code></td></tr>

<tr><td>

![hackernews](https://user-images.githubusercontent.com/301220/213590759-bd7b9c85-f586-4b70-968c-c3e58377484d.png)
</td><td>hackernews.png / 900×450 / 334KB<br/>sha256: <code>024e3613dff38cc878febb4cbea839cf47be016a47bb949674cb03ce36f76147</code></td></tr>

</table>

**Comment by fmw42** [comment]
Your images have some non-fully opaque vertical stripes.

For example, extract the alpha channel. Then color any pixel that is not fully opaque as red and the rest as black

![213590372-16f8d2c1-a874-43d6-8bdd-fca2d21149b0](https://user-images.githubusercontent.com/13458218/213593208-f198f2b0-0c84-4a6f-b0e2-bd9f9cd34226.png)


`magick 213590372-16f8d2c1-a874-43d6-8bdd-fca2d21149b0.png -alpha extract -fx "u<1?red:black" x.png`

![x](https://user-images.githubusercontent.com/13458218/213593326-f48c724e-0e64-41ca-b92e-73e87003eb74.png)

**Comment by alexwlchan** [comment]
How odd, I have no idea how that got there or why I couldn't find it myself.

Thanks for explaining!
