### ISSUE TITLE
ImageMagick generates improper output images

### ISSUE THREAD

**Issue by DigneshGoyal** [ImageMagick/ImageMagick#6]
Below is the command used .
convert.exe input.jpg -intent relative -sample 500x375 -quality 95 -auto-orient -strip -output.jpg
please check the generated output file which is not proper.

![input](https://cloud.githubusercontent.com/assets/12810106/8053026/6835087e-0eaa-11e5-87be-323626395c70.jpg)

**Comment by dlemstra** [comment]
I assume you meant 'output.jpg' instead of '-output.jpg'. Which version of ImageMagick are you using and what is your operating system? I am unable to reproduce your problem with the latest beta.

**Comment by DigneshGoyal** [comment]
Version of Image magick used ImageMagick-6.8.0-Q16
OS :- Windows 7 Enterprise

**Comment by DigneshGoyal** [comment]
attached is generated output file 
![output](https://cloud.githubusercontent.com/assets/12810106/8053491/ce67815e-0eae-11e5-9e6a-674a97bbb30d.jpg)

**Comment by dlemstra** [comment]
Can you clarify whats wrong with it? If it is the quality I would suggest you use -resize instead of -sample.

**Comment by DigneshGoyal** [comment]
The attached output generated by the image magick is pixelated.
I also tried using -resize instead of -sample but still the output is not proper.please compare the output with the original input file attached
![outputs](https://cloud.githubusercontent.com/assets/12810106/8053623/0fb2e256-0eb0-11e5-877e-6e0f3e5a9614.jpg)

**Comment by dlemstra** [comment]
Can you post the output of conver -version ?

**Comment by DigneshGoyal** [comment]
Version: ImageMagick 6.8.0-5 2012-11-03 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP

**Comment by dlemstra** [comment]
Are you building from source? I get the following output image:
![output](https://cloud.githubusercontent.com/assets/10426229/8053825/51d8c7e8-0e94-11e5-8889-72bbcfeea930.jpg)

**Comment by DigneshGoyal** [comment]
No .I have installed ImageMagick software using installer.

**Comment by dlemstra** [comment]
Can you upgrade to 6.9.1-4?

**Comment by DigneshGoyal** [comment]
If the issue gets resolved in 6.9.1-4 i will upgrade.
One more issue what i am facing with imagemagick is when the same image is of CMYK model then generated output consists of white background.Is there any way to preserve the same color/background using some options.
![test](https://cloud.githubusercontent.com/assets/12810106/8054025/1954391a-0eb3-11e5-872f-071356e306f3.jpg)

**Comment by dlemstra** [comment]
Can you upgrade to 6.9.1-4 first and then try to see if that resolves this issue?

If you can still reproduce the CMYK problem with that version then please start a new issue for that.

**Comment by DigneshGoyal** [comment]
The latest version of IM resolves the issue when transformation is done from jpg to jpg.
But it fails from psd to jpg.
I cannot attach the image as file is >10MB.
Please advice the next steps.

**Comment by dlemstra** [comment]
Can you put the image on something like dropbox / onedrive and add the link in a new issue? I will close this one because the original issue has been resolved.

**Comment by DigneshGoyal** [comment]
Ok Thank you much for the help.

**Comment by DigneshGoyal** [comment]
File is available here http://tinyurl.com/dignesh-com
