### ISSUE TITLE
TintImage values

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#60]
Hi,

I'm trying to fix a bug in the PHP Imagick extension, and would like to check the behaviour of the MagickTintImage before I say it's fixed, when it actually might not be.

Please could you confirm what the accepted values are for [MagickTintImage](http://www.imagemagick.org/api/magick-image.php#MagickTintImage) and how they relate to the command line version of `-tint`

Using this source image:
![tinttest](https://cloud.githubusercontent.com/assets/1505719/11601370/9d22bdd6-9aca-11e5-9e62-77c6ea580f8f.png)

and using the command line `convert TintTest.png -fill red -tint 40 tint_red.png` gives this file:
![tinttest_convert_40](https://cloud.githubusercontent.com/assets/1505719/11601373/a449ec56-9aca-11e5-851d-0e32dc83bda2.png)

After fixing one bug in the imagick library, now when I do what I thought would be the equivalent of that command line, `$imagick->tintImage ("red", "rgba(40, 40, 40, 1)");` gives an image that is darker.

![tinttest_imagick_40](https://cloud.githubusercontent.com/assets/1505719/11601379/ae227158-9aca-11e5-84d1-fcea50af5d7b.png)

Scaling the values up to by 255/100 (i.e. to make the normal range be 0-255 instead of 0-100) gives an image that is almost identical to the command lin version `$imagick->tintImage ("red", "rgba(102, 102, 102, 1)");`
![tinttest_imagick_102](https://cloud.githubusercontent.com/assets/1505719/11601382/b1ca0938-9aca-11e5-9eec-d881f24d1924.png)

However, for the command line version, it's possible to set the -tint value above 100. Unless that would imply an 'opacity' setting in the MagickWand above 255, and unless ImageMagick is compiled as HDRI, that isn't possible is it?

If you could just confirm what the range of values are that would be awesome.

**Comment by dlemstra** [comment]
The TintTimage method in MagickCore is called by MagickTintImage in Wand. The '40' is directly passed to the MagickCore method on the command land. The Wand method takes your value and does the following calculation:

``` c
#define MaxColormapSize  256UL /* Q8 */
#define QuantumScale  ((double) 1.0/(double) QuantumRange)

/* This is only an example for the red channel */
100.0*QuantumScale*value->red
````

So to get 40 you should use 102/103 as you posted in your example.
``` c
100*(1.0/256)*102 = 39,84
100*(1.0/256)*103 = 40,23
```

**Comment by Danack** [comment]
Thanks, so is it possible to do the equivalent of the command line:

    convert  test.png  -fill white  -tint 130 tint_lighter.png

where the tint value is greater than 100 through the magick wand function MagickTintImage?

**Comment by Danack** [comment]
Actually just using `$imagick->tintImage ("red", "rgba(331.5, 331.5, 331.5, 1)");` seems to give an equivalent result.
