### ISSUE TITLE
montage command -page flag with -gravity flag not working

### ISSUE THREAD

**Issue by dcoder47** [ImageMagick/ImageMagick#6014]
### ImageMagick version

6.9.12-70 Q16 x86_64 17597

### Operating system

Linux

### Operating system, version and so on

Fedora 37

### Description

`montage` command with `-page A4` flag and `-gravity Center` flag not working.

### Steps to Reproduce

- Only 1 image `1062x880` resolution to be placed scaled proportionately as `Centered`on an `A4` page.

![img1](https://user-images.githubusercontent.com/124032294/215702100-19a70c30-ca9d-400f-8195-2f9d28930157.jpg)

- Requirement :

![img2](https://user-images.githubusercontent.com/124032294/215702401-3216c530-1d64-490c-9a9a-47157322b570.jpg)

Using the following command

`montage -page A4 -gravity Center -tile 1x1 im1.jpg im2.jpg`

produces output like this 
![img3](https://user-images.githubusercontent.com/124032294/215701973-7c827e24-bfb1-47b8-b50b-e101161ca62c.jpg)

output of `128x126` resolution is produced which is not required.

- Without the `tile 1x1` option still the same output.

![img3](https://user-images.githubusercontent.com/124032294/215701973-7c827e24-bfb1-47b8-b50b-e101161ca62c.jpg)

**Comment by fmw42** [comment]
-page is not sensitive to -gravity and never has been

**Comment by dcoder47** [comment]
Any suggestions on how to get the above desired result ?

**Comment by fmw42** [comment]
A4 = 595x842 pixels. So do

`convert 215702100-19a70c30-ca9d-400f-8195-2f9d28930157.jpg -resize 595x842 -gravity center -extent 595x842 result.png`

If you want a smaller resize, that is fine. But keep the extent at 595x842 for A4.

If you upgrade to IM 7, then 595x842 can be replace with just "A4".

**Comment by dcoder47** [comment]
Thanks.

**Comment by dcoder47** [comment]
Thanks.
