### ISSUE TITLE
any operation on svg images output black images

### ISSUE THREAD

**Issue by mortezadadgar** [ImageMagick/ImageMagick#6022]
### ImageMagick version

7.1.0-48

### Operating system

Linux

### Operating system, version and so on

Gentoo

### Description

I always gets #000 images no matter what I do on the image, for example I trimmed the image
also comment potrace from delegates.xml output a very low quality svg image

### Steps to Reproduce

1. magick cloudy-day-3.svg -trim cloudy-day-3-trimmed.svg
2. open image and it's a solid black image

### Images

![cloudy-day-3](https://user-images.githubusercontent.com/27911493/216359720-c8281f45-7f2f-4ff8-a27d-7e033c61689f.svg)

**Comment by snibgo** [comment]
Your input SVG file contains vectors. ImageMagick is a raster image processor. When IM reads your SVG, it will convert it to raster (ie pixels). Is that what you want?

When IM writes an image to SVG output, it will embed the raster image in the SVG file. It does not convert the raster image to vector. Again, is this what you want?

**Comment by fmw42** [comment]
Works fine for me on IM 7.1.0.60 Mac OSX Monterey with Inkscape as the SVG renderer.

`magick cloudy-day-3.svg -trim cloudy-day-3-trimmed.png`

![cloudy-day-3-trimmed](https://user-images.githubusercontent.com/13458218/216383975-72d0333a-c3e2-46f8-8410-638351dbf6c0.png)


What SVG renderer are you using? It could be the Internal MSVG/XML renderer, RSVG delegate or Inkscape. The latter is the most functional.  Add -verbose to your command to see what you have. Note: recommend installing Inkscape. IM will then use it automatically over the other two. You likely are using the MSVG/XML native renderer.

**Comment by mortezadadgar** [comment]
@snibgo I want the exact image that I have, which is a vector image without transparent space around it; that's not possible with IM? if not what should i do

**Comment by mortezadadgar** [comment]
@fmw42
verbose output
`
'inkscape' '/tmp/magick-ivf2FObPOVKmWdHGddQ23tajSySvdDM3' --export-filename='/tmp/magick-AY_m1Zlaemg5iGRXUCQllbJEEp6rZOUv.png' --export-dpi='96' --export-background='rgb(100%,100%,100%)' --export-background-opacity='1' > '/tmp/magick-X0Br5fBPrDA4dMFEtsl2jp2n7Xk4Yh5S' 2>&1
cloudy-day-3.svg SVG 43x33 43x33+0+0 16-bit sRGB 6175B 0.030u 0:00.056
cloudy-day-3.svg=>cloudy-day-3-trimmed.svg PNM 43x33=>43x32 43x33+0+1 16-bit sRGB 8271B 0.010u 0:00.013
`
which indicate inkscape rendere but I have it installed as a appimage which should be recognized by IM

**Comment by fmw42** [comment]
Perhaps you have an older delegates.xml file.  Check it to see what it says about SVG. On my 7.1.0.60 IM, I get

 ```
 <delegate decode="svg" command="&quot;rsvg-convert&quot; -o &quot;%o&quot; &quot;%i&quot;"/>
  <!-- Change export-filename to export-png for inkscape < 1.0 -->
  <delegate decode="svg:decode" stealth="True" command="&quot;inkscape&quot; &quot;%s&quot; --export-filename=&quot;%s&quot; --export-dpi=&quot;%s&quot; --export-background=&quot;%s&quot; --export-background-opacity=&quot;%s&quot; &gt; &quot;%s&quot; 2&gt;&amp;1"/>

```

**Comment by mortezadadgar** [comment]
@fmw42 outputing png works on my IM as well actually I want svg

**Comment by fmw42** [comment]
IM is a raster processor. It will rasterize your SVG file. To get SVG output, your would have to rasterize from the read of SVG then re-vectorize using potrace. (But the resulting vector file will just be dots, if I understand correctly). You have to have the right entry in your delegates.xml file and have potrace on your system.  Sorry, that is all I know.

**Comment by snibgo** [comment]
> I want the exact image that I have, which is a vector image without transparent space around it; that's not possible with IM? if not what should i do

I suggest using Inkscape for this task. Just Inkscape, not ImageMagick.

**Comment by mortezadadgar** [comment]
is this limitation is documented anywhere?

**Comment by fmw42** [comment]
The only place that I know about is at https://imagemagick.org/Usage/formats/#vector

**Comment by mortezadadgar** [comment]
Thanks! I close this now
