### ISSUE TITLE
Deprecated and troublesome old-style JPEG compression mode

### ISSUE THREAD

**Issue by RAmbika** [ImageMagick/ImageMagick#6025]
### ImageMagick version

7.1.0-60

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

Hi, 

We have few tiff images and when we try to convert these files using below command:
convert.exe "inputFile.tif" -density "200" "outputFile.PDF"

We are getting the below error:
convert.exe: Unknown field with tag 33000 (0x80e8) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/960.
convert.exe: Deprecated and troublesome old-style JPEG compression mode, please convert to new-style JPEG compression and notify vendor of writing software. `OJPEGSetupDecode' @ warning/tiff.c/TIFFWarnings/960.

Could you please let us know what is causing this error and how can we resolve this?

Thanks,
Ambika

### Steps to Reproduce

convert.exe "inputFile.tif" -density "200" "outputFile.PDF"

**Comment by fmw42** [comment]
Imagemagick uses libtiff to read TIFF files, our libtiff cannot handle older style JPG compression. It can handle newer JPG compression. You will need to find some other tool to read and convert them to either newer JPG compression or one of the other TIFF compatible compressions. Perhaps Photoshop or even GIMP might be able to read them and reprocess them to be compatible with Imagemagick and libtiff.

**Comment by dlemstra** [comment]
Closing this as the answer to this question could have been found in #5000.
