### ISSUE TITLE
write.t failing on Truevision Targa image file

### ISSUE THREAD

**Issue by dotlambda** [ImageMagick/ImageMagick#6026]
### ImageMagick version

7.1.0-60

### Operating system

Linux

### Operating system, version and so on

NixOS 23.05

### Description

Using `TEST_VERBOSE=1`, `t/write.t` fails with
```
Truevision Targa image file ...
ReadImage()
Image: TGA:input.tga, signatures do not match.
     Expected: fb6fc68beb3b1001c5ebaa671c8ac8fddea06995027127765ff508f77723cc52
     Computed: ff78a650ff5f4adfdf6ef34e8cc3369de44e71ed4eef1807dc88372352ddac90
     Depth:    16
not ok 24
```

### Steps to Reproduce

Run `nix-build -A perlPackages.ImageMagick` on https://github.com/NixOS/nixpkgs/pull/212205.
The version of the Perl package is 7.0.11-3.

**Comment by dlemstra** [comment]
Can this be reproduced with a bump to `7.1.0-60`?

**Comment by dotlambda** [comment]
> Can this be reproduced with a bump to `7.1.0-60`?

I am already using version 7.1.0-60.
The Perl package has version 7.0.11-3 because that's the latest one available on https://metacpan.org/pod/Image::Magick.

**Comment by urban-warrior** [comment]
We updated PerlMagick in CPAN with new signatures to account for the recent mod to the TGA coder.
