### ISSUE TITLE
montage can't read files with a name containing [ or ]

### ISSUE THREAD

**Issue by xhsdf** [ImageMagick/ImageMagick#6040]
### ImageMagick version

7.1.0.61

### Operating system

Linux

### Operating system, version and so on

Archlinux

### Description

Since updating from 7.1.0.60 to 7.1.0.61 montage can't read files with a name containing `[` or `]` anymore.

Command I'm using:
`montage -quality 95 -geometry +0+0 -mode concatenate -tile 1x /home/xhsdf/test/files/* test.jpg`

If a file in that folder contains `[` or `]` I get this error now:

```
montage: unable to open image '����': No such file or directory @ error/blob.c/OpenBlob/3569.
montage: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
```

It works fine in 7.1.0.60 and with all other special characters I tried.
I'm using up-to-date Archlinux.

### Steps to Reproduce

Make a folder containing an image with `[` or `]` in the name and run
`montage -quality 95 -geometry +0+0 -mode concatenate -tile 1x folder/* test.jpg`

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by xhsdf** [comment]
Thank you!

**Comment by azinsharaf** [comment]
hi @urban-warrior i experience the same issue when the photo file contains curly bracket. { or }
