### ISSUE TITLE
Convert gif to webp fail on new version

### ISSUE THREAD

**Issue by jiuzhoucui** [ImageMagick/ImageMagick#6041]
### ImageMagick version

7.1.0-60

### Operating system

Linux

### Operating system, version and so on

centos

### Description

convert testcase.gif testcase.webp

This works well on v7.1.0-11, but when I use v7.1.0-60, it get error as below:

convert: ERROR adding frame: Invalid frame dimensions. `testcase.webp' @ error/webp.c/WriteAnimatedWEBPImage/965. 

### Steps to Reproduce

convert testcase.gif testcase.webp

### Images

![testcase](https://user-images.githubusercontent.com/102148284/217476395-0e0f627c-44a6-4d72-a74f-c1389c3640d0.gif)

**Comment by dlemstra** [comment]
Previous versions of ImageMagick would automatically do the `-coalesce` option when writing a `.webp` image. But this caused issues when this was done by the user and done by ImageMagick. But that does mean that you will need to do that yourself now: `convert testcase.gif -coalesce testcase.webp`

**Comment by jiuzhoucui** [comment]
Got it, thanks

**Comment by milahu** [comment]
the error message could be more helpful

```diff
  convert:
  ERROR adding frame: Invalid frame dimensions.
+ Hint: Add "-coalesce" to the convert arguments.
  `output.webp' @ error/webp.c/WriteAnimatedWEBPImage/955.
```

**Comment by fmw42** [comment]
Did you try the hint.  Converting from gif to webp needs the **-coalesce**.  Gif animations have compression that removes constant parts between frames. So they need to be expanded so that the webp reader can handle it .

**Comment by dlemstra** [comment]
The user wants us to add that hint Fred. But we will not do that. We don't interpret string error message from other libraries because they might change in the future. But I am still thinking if we could auto detect if we need to run coalesce without adding a big performance penalty when we don't need to do this. I hope I will have some time to investigate that next week.

p.s. For ImageMagick 7 you should use `magick` instead of `convert`.

**Comment by dlemstra** [comment]
The next release of ImageMagick will perform a `-coalesce` when it detects that not all frames have the same dimensions. This will restore the old behavior for images that have not yet been "coalesced".
