### ISSUE TITLE
Image corruption when writing to MIFF from an input image with particular EXIF

### ISSUE THREAD

**Issue by njdoyle** [ImageMagick/ImageMagick#6052]
### ImageMagick version

7.1.0-29 to 7.1.0-61

### Operating system

Linux

### Operating system, version and so on

Ubuntu 18.04

### Description

With input images with particular EXIF data, saving to MIFF corrupts the image data.

This is a regression introduced between versions 7.1.0-28 and 7.1.0-29. The exact commit looks to be 25309b9772d72072f8574352968aeca7134ba433 which relates to issue #4987.

Building ImageMagick 7.1.0-61 with the above change reverted makes this corruption go away.

I have attached an image that triggers the issue as well as results of the corrupted output I see.

### Steps to Reproduce

```
magick logo_with_metadata.jpg MIFF:- | magick MIFF:- broken.jpg
```

### Images

logo_with_metadata.jpg:
![logo_with_metadata.jpg](https://user-images.githubusercontent.com/316852/218173290-8d45fcba-4135-416a-b10d-79d411869df9.jpg)

broken.jpg:
![broken.jpg](https://user-images.githubusercontent.com/316852/218173368-95696316-ded7-4836-8416-8d29a6d54838.jpg)

[broken.miff.zip](https://github.com/ImageMagick/ImageMagick/files/10710358/broken.miff.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
