### ISSUE TITLE
memory leak during process psd file

### ISSUE THREAD

**Issue by tymonkey** [ImageMagick/ImageMagick#606]
The imagemagick take more than 10GB memory  when get this psd info ， but the psd file is only 350MB， Maybe it's a memory leak issue.

version：`7.0.6-2`
command: ` magick identify -quiet  -format "%p:%[label],"  bigpsd.psd`
psd file: [http://img.ucweb.com/s/uae/g/2n/bigpsd.psd](http://img.ucweb.com/s/uae/g/2n/bigpsd.psd)

**Comment by mikayla-grace** [comment]
Valgrind does not report any memory leaks.  To reduce memory resource requirements, try this command:

`magick identify -limit memory 0 -limit map 0 -quiet -format "%p:%[label]," bigpsd.psd`

**Comment by dlemstra** [comment]
You are using so much memory because your PSD file contains a lot of layers. And ImageMagick needs to allocate the pixels for each of those layers. The image data is compressed in the file and that is why it is a lot smaller than the required memory.
