### ISSUE TITLE
JPEG policy pattern behaves differently for read and write

### ISSUE THREAD

**Issue by blx** [ImageMagick/ImageMagick#6061]
### ImageMagick version

7.1.0-45

### Operating system

MacOS

### Operating system, version and so on

macOS 13.2

### Description

In `policy.xml`, the pattern `JPEG` matches any JPEG file for reading, **as identified by magic bytes,** but only matches ".jpeg" (case-insensitive) for writing, not also ".jpg".

This is understandable from one angle but was not clear to me from the policy docs.

It means that, with a policy like
```xml
<policymap>
  <policy domain="coder" rights="none" pattern="*" />
  <policy domain="coder" rights="read | write" pattern="{JPEG}" />
</policymap>
```
what seems like almost a no-op, like
```
magick convert sample.jpeg sample.jpg
```
is blocked by the policy, unless I override the file extension inference for the output, like
```
magick convert sample.jpeg jpeg:sample.jpg
```
even though a read-only operation, like `identify`, works with all the JPEG-aliased file extensions:
```
magick identify sample.jpeg
magick identify sample.jpg
magick identify sample.jpe
```

---

So, if I want to write images with filenames ending in `.jpg`, I need to have a policy like:
```xml
<policymap>
  <policy domain="coder" rights="none" pattern="*" />
  <policy domain="coder" rights="read | write" pattern="{JPEG,JPG}" />
</policymap>
```
even though `JPG` can not be substituted for `JPEG` on the `read` side:
```xml
<policymap>
  <policy domain="coder" rights="none" pattern="*" />
  <policy domain="coder" rights="read | write" pattern="{JPG}" />
</policymap>
```
fails to read JPEGs:
```
[nix-shell:~/Downloads/x]$ MAGICK_CONFIGURE_PATH=$(pwd) magick identify mario2.jpg
identify: attempt to perform an operation not allowed by the security policy `JPEG' @ error/constitute.c/IsCoderAuthorized/449.
```

---

Again, I can understand this technically, but I think it would be more clear if the policy.xml docs mentioned that, in essence,
* patterns for the `read` right are matched against their normalized name, taking aliases into account,
* while patterns for the `write` right are matched literally, and don't consider format aliases.

### Steps to Reproduce

```sh
$ magick convert -size 100x100 xc:#1155cc blue.jpg
$ echo '<policymap><policy domain="coder" rights="none" pattern="*" /><policy domain="coder" rights="read | write" pattern="{JPEG}" /></policymap>' > policy.xml
$ MAGICK_CONFIGURE_PATH=$(pwd) magick identify blue.jpg
# works fine
$ MAGICK_CONFIGURE_PATH=$(pwd) magick convert blue.jpg blue2.jpg
convert: attempt to perform an operation not allowed by the security policy `JPG' @ error/constitute.c/IsCoderAuthorized/449.
```

**Comment by urban-warrior** [comment]
You likely want the `module` policy.  Substitute `module` for `coder` in your policy.  The module policy assigns rights to all formats that the module supports.  For `pattern=JPEG`, that includes "PJPG, JPS, JPG, JPEG, and JPE.  To get the same effect from the coder policy, the pattern would be "{PJPG,JPS,JPG,JPEG,JPE}".
