### ISSUE TITLE
The text rotate 180 degree after convert from SVG to PNG

### ISSUE THREAD

**Issue by findyy99** [ImageMagick/ImageMagick#6066]
### ImageMagick version

7.1.0-62

### Operating system

MacOS

### Operating system, version and so on

macOS 13.2

### Description

- The svg is generated by matplotlib, after convert it to type png, the vertical text was rotated 180 degree.
- This is the command I used:
`for file in *.svg; do convert -density 400 -trim -auto-orient $file ${file%%.}.png; done`
- The first picture is very 'good'
<img width="500" alt="image" src="https://user-images.githubusercontent.com/26852735/218970531-2153de82-1387-46fa-ba0c-68e8acceb099.png">

- This picture which was convert to type PNG is wired. Text `Load` has been rotated 180 degree.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/26852735/218971084-97f0c439-2a5e-4271-877e-0d882ae868df.png">

### Steps to Reproduce

- Download the `zip`, unzip it.
- And run the command as I mentioned above.
[Archive.zip](https://github.com/ImageMagick/ImageMagick/files/10740831/Archive.zip)

**Comment by fmw42** [comment]
Your command should use magick not convert on IM 7.  What SVG renderer is being used (MSVG/XML, RSVG or Inkscape).

It works fine for me on IM 7.1.0.62 using Inkscape 

`magick -density 400 recycled_deflection.svg -auto-orient -trim +repage recycled_deflection.png`

![recycled_deflection](https://user-images.githubusercontent.com/13458218/219086963-3cf3946c-699d-427c-8215-5e07d069e6f7.png)

**Comment by findyy99** [comment]
@fmw42 How to under `using Inkscape`? I have installed the Inkscape, and I tried the command you give, the result is the same as I got before.

- `magick -density 500 recycled_deflection.svg -auto-orient -trim +repage test.png`
- 
![test](https://user-images.githubusercontent.com/26852735/219357164-7baafac9-4b64-4a93-9de0-4c0adb435afd.png)

**Comment by fmw42** [comment]
What version of Inkscape? Was it installed with its path in the $PATH environment variable.  Add -verbose to your command right after magick. That will show if it is being used.

My version of Inkscape was 1.2.1

**Comment by findyy99** [comment]
@fmw42 The version of Inkscape is same as you, I checked again, the version of Inkscape 1.2.1 and the version of IM is 7.1.0-62.  By the way , I am using macOS Ventura 13.2.1 with M1 Pro.
- The $PATH seems doesn't include the Inkscape.
`/Users/findyy/opt/miniconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Library/Apple/usr/bin`
- This is log after add `-verbose`.
`'inkscape' '/var/folders/qb/9kyxhjdd475gpdb_6tz8195m0000gn/T/magick-Ztt89sebsxQGhPQZ9cNHvfVKKkZBz5Dh' --export-filename='/var/folders/qb/9kyxhjdd475gpdb_6tz8195m0000gn/T/magick-qRHmr2h1Fzh5UIhrxTkYRif0TitPl0dj.png' --export-dpi='500' --export-background='rgb(100%,100%,100%)' --export-background-opacity='1' > '/var/folders/qb/9kyxhjdd475gpdb_6tz8195m0000gn/T/magick-OeVP30KjFkIoS8LfmvOzVas_I4RJ7qfs' 2>&1
mvg:/var/folders/qb/9kyxhjdd475gpdb_6tz8195m0000gn/T/magick-zhStq2zn_veg4gO5rpbsKC7Nvl18LzoK=>/var/folders/qb/9kyxhjdd475gpdb_6tz8195m0000gn/T/magick-zhStq2zn_veg4gO5rpbsKC7Nvl18LzoK MVG 1223x1026 1223x1026+0+0 16-bit sRGB 63880B 5.350u 0:01.348
recycled_deflection.svg SVG 1223x1026 1223x1026+0+0 16-bit sRGB 63880B 0.000u 0:00.000
recycled_deflection.svg=>test.png SVG 1223x1026=>1219x1021 16-bit sRGB 63880B 0.110u 0:00.115`

**Comment by fmw42** [comment]
I am on M1 Mac Monterey.

I get

'inkscape' '/tmp/magick-A1uejxw370dTb-s2LvHhriNrcWdbsKaV' --export-filename='/tmp/magick-dYxRKbR4kXWc8AhYZMpMYlFks0hSKHCY.png' --export-dpi='400' --export-background='rgb(100%,100%,100%)' --export-background-opacity='1' > '/tmp/magick-kE7MsfFSijj8ryJQ1fk_YKu3EB0khe7u' 2>&1
/tmp/magick-dYxRKbR4kXWc8AhYZMpMYlFks0hSKHCY.png PNG 1305x1095 1305x1095+0+0 8-bit TrueColorAlpha sRGB 184224B 0.030u 0:00.021
recycled_deflection.svg SVG 1305x1095 1305x1095+0+0 8-bit TrueColorAlpha sRGB 184224B 0.000u 0:00.000
recycled_deflection.svg=>recycled_deflection.png SVG 1305x1095=>1265x1058 8-bit TrueColorAlpha sRGB 184224B 0.070u 0:00.079


Yours seems to be trying to use Inkscape, but defaulting to IM internal one.

Here is my entry in delegates.xml file:

```
  <delegate decode="svg" command="&quot;rsvg-convert&quot; -o &quot;%o&quot; &quot;%i&quot;"/>
  <!-- Change export-filename to export-png for inkscape < 1.0 -->
  <delegate decode="svg:decode" stealth="True" command="&quot;inkscape&quot; &quot;%s&quot; --export-filename=&quot;%s&quot; --export-dpi=&quot;%s&quot; --export-background=&quot;%s&quot; --export-background-opacity=&quot;%s&quot; &gt; &quot;%s&quot; 2&gt;&amp;1"/>

```

What do you have for your entry for SVG in your delegates.xml file?

Have you tried adding the path to the folder containing Inkscape to your $PATH variable in your .zprofile or .bash_profile file, depending upon where you are running your commands?  I still use bash, so it is in my .bash_profile. But I think I have it in both.  I load my delegates from MacPorts into /opt and install imagemagick from source.  Did you install both Inkscape and IM from Homebrew or how?

**Comment by findyy99** [comment]
Amazing!!! After add the Inkscape to `$PATH`, everything works fine!!!!
- Entry for SVG is same in your delegates.xml file
- Add Inkscape to `$PATH`; `export PATH="/Applications/Inkscape.app/Contents/MacOS:$PATH"`
- I use the Homebrew to install ImageMagick
Thanks for your help!!!!!
