### ISSUE TITLE
SIGABORT when calling "-distort Perspective" with certain parameters

### ISSUE THREAD

**Issue by bourdoncle** [ImageMagick/ImageMagick#6070]
### ImageMagick version

7.1.0-62

### Operating system

MacOS

### Operating system, version and so on

macOS Ventura 13.2.1 (22D68) on a MacStudio

### Description

When calling "-distort Perspective" with certain parameters, the magic process ends with a SIGABORT signal. Just changing some of the parameters (e.g, the final 9090 to 9000 or 9100) works fine. I am using the home-brew distribution.

### Steps to Reproduce

magick -size 5820x7760 canvas:Black -virtual-pixel Transparent -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:

**Comment by fmw42** [comment]
I can verify that abort trap 6 on IM 7.1.0.62 Mac OSX Monterey.

**Comment by bourdoncle** [comment]
My take is that it's probably a system-independent "logic" bug. I am using IM to build videos (lots of frames, and each frame has a different perspective distortion), and I cannot go past a few frames before the bug manifests itself. Quite amazingly, another video works just fine, but then I think the the distortions in this video are less pronounced (maybe the source of the bug).

**Comment by fmw42** [comment]
Draw your coordinates on a constant background and verify that the lines connecting them do not cross. That is the point are always either clockwise or counterclockwise, but both sets are the same ordering.

**Comment by bourdoncle** [comment]
![Projection](https://user-images.githubusercontent.com/5870415/219450470-407fbb4c-ff76-4fa3-83f7-472257f95055.png)
I am doing the following projection (projecting the magenta rectangle to the yellow quadrilateral) connecting the points clockwise.

**Comment by fmw42** [comment]
Will 5820x7760 hold all your coordinates? If not, then try +distort rather than -distort.

 magick -size 5820x7760 canvas:Black -virtual-pixel Transparent +distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:

works fine for me with +distort

**Comment by fmw42** [comment]
It might be your limits in your policy.xml file or perhaps some limit on canvas: One of the IM developers will have to comment.  But generally one uses +distort to get the output such that its size is limited by the distortion  output (usually the dimensions of the control points) rather than truncated to the size of the input, which is the result from -distort. In your case your output was larger than the input, which should have simply truncated your output to the size of the input. But it did an abort 6, which I do not understand. Perhaps it ran out of resources. I am not sure and an IM developer will have to comment about that also.

**Comment by bourdoncle** [comment]
![bug](https://user-images.githubusercontent.com/5870415/219490755-4cb4ffd9-b681-47f6-91c1-9e8b9bcda9bb.png)

Well, here is another interesting case. The following command apparently never terminates. As it turns out, some control points fall outside of the original image, but even using "+distort" seems to fail.

`magick -size 5820x10347 canvas:Black -virtual-pixel Transparent +distort Perspective "4125,4403,3991,4199       5890,3881,5661,4199       5818,7491,5661,7170       4090,6926,3991,7170" null:`

**Comment by fmw42** [comment]
You are trying to create a file whose size is way to big for your RAM.  How much RAM do you have allocated?

5820 * 10347 * 8bits/channel * 3channels = 1,445,268,960 bytes

**Comment by fmw42** [comment]
> I am doing the following projection (projecting the magenta rectangle to the yellow quadrilateral) connecting the points clockwise. It looks perfectly legit to me, unless I am missing something.

But your control points are ordered the other way such that you are warping from the yellow quad to magenta rectangle. Which do you really want?

**Comment by snibgo** [comment]
It is late, well past mny bedtime, but I think this is wrong:

> I am doing the following projection (projecting the magenta rectangle to the yellow quadrilateral) connecting the points clockwise. 

I think the requested transformation is from the yellow quadrilateral to the magenta rectangle.

"-precision 16 -verbose" gives the equivalent "-distort PerspectiveProjection", which does work:
```
%IMG7%magick toes.png -resize "5820x7760^!" ^
  -background Blue -virtual-pixel Background ^
  -distort PerspectiveProjection ^
2.121562248793953,-0.01758153076400285,-378.239463564614,5.078887822712784,^
1.55711280987029,-4735.399121085766,0.0006054059259055204,-8.522426580928307e-07 ^
  x.jpg
```
Virtual pixels are shown in blue. Note the gray area to the right. These are "beyond the horizon", indeterminate values.

![x](https://user-images.githubusercontent.com/33812368/219565010-bcb19cd4-21e5-4bef-a7d2-4548cb621f27.jpg)

**Comment by bourdoncle** [comment]
> It might be your limits in your policy.xml file or perhaps some limit on canvas: One of the IM developers will have to comment. But generally one uses +distort to get the output such that its size is limited by the distortion output (usually the dimensions of the control points) rather than truncated to the size of the input, which is the result from -distort. In your case your output was larger than the input, which should have simply truncated your output to the size of the input. But it did an abort 6, which I do not understand. Perhaps it ran out of resources. I am not sure and an IM developer will have to comment about that also.

Well, I have a MacStudio with 64GB of RAM and 4TB of disk, and the my limits are as follows:

```
  Width: 461.169PP
  Height: 461.169PP
  Area: 274.878GP
  List length: unlimited
  Memory: 64GiB
  Map: 128GiB
  Disk: unlimited
  File: 768
  Thread: 10
  Throttle: 0
  Time: unlimited
```

However, you probably are right, since I left the process running during the night and in the morning (on my Intel iMac) it failed with the following error message :

`processing error: unable to persist pixel cache, Unable to write file`

The input image being very large and the perspective being quite pronounced, the intermediate image must indeed have been huge. And this was a dumb thing to do since I should have cropped the image to the bounding rectangle of the quadrilateral to the destination rectangle before actually applying the transform. Doing so actually works and is much faster, too.

> But your control points (below) are ordered the other way such that you are warping from a quad to a rectangle. Which do you really want?

Yes sorry, my bad, the interpretation of the projection is wrong but the actual shell command is right.

> Virtual pixels are shown in blue. Note the gray pixels to the right. These are "beyond the horizon", indeterminate values.

As it turns out, a portion of the quadrilateral was outside of the original image. I thought that IM would have automatically padded the image with the virtual pixel color, but that is apparently not the case, so I am now padding the image myself when there is a need to it.

Thank you so much to all of you for helping me understand and resolve the issue. However, the original SIGABRT issue should still probably be fixed :-)

**Comment by snibgo** [comment]
> As it turns out, a portion of the quadrilateral was outside of the original image. 

That shouldn't matter.

Given that the equivalent `-distort PerspectiveProjection` works, the original `-distort Perspective` should work. I don't know why it doesn't. It certainly shouldn't SIGABRT.

**Comment by fmw42** [comment]
If you have OpenMP enabled, try running it with OpenMP disabled. Sometimes that can cause issues.

**Comment by bourdoncle** [comment]
OMP is enabled on the home-brew distribution. If I set the environment variable (assuming that's how you disable OMP?),

`export MAGICK_THREAD_LIMIT=1`

then following command still SIABRTs on my Apple Silicon MacStudio.

`magick -size 5820x7760 canvas:Black -virtual-pixel Transparent -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null: `

 I'll also try later tonight on my Intel Mac to see if it's specific to Apple Silicon. Interestingly, if I remove the `-virtual-pixel Transparent` option, the command still SIGABRTs but after a longer delay.

**Comment by bourdoncle** [comment]
Well, it's now confirmed, the command ends gracefully on Intel Macs and aborts on Apple Silicon Macs.

```
%time magick -size 5820x7760 canvas:Black -virtual-pixel Transparent -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
magick: width or height exceeds limit `Black[0]' @ error/cache.c/SetPixelCacheNexusPixels/5063.
28,05s user 0,93s system 1337% cpu 2,167 total

```

and without the `-virtual-pixel` option:

```
%time magick -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:  
magick: width or height exceeds limit `Black[0]' @ error/cache.c/SetPixelCacheNexusPixels/5063.
69,12s user 0,41s system 352% cpu 19,729 total

```

**Comment by urban-warrior** [comment]
Try this command:

```
$ MAGICK_SYNCHRONIZE=true magick -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
```

Does that resolve the issue?

**Comment by fmw42** [comment]
I still get abort trap 6 using MAGICK_SYNCHRONIZE=true on my M1 Mac OSX Monterey.

**Comment by fmw42** [comment]
Not sure what I am doing. I tried

```
gdb im7 magick 
run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
bt

```

But got gdb and run not found:

```
bash-3.2$ gdb im7 magick 
bash: gdb: command not found
bash-3.2$ run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
bash: run: command not found
bash-3.2$ bt
bash: bt: command not found
```

**Comment by urban-warrior** [comment]
You would of course need to first install gdb.  If its not available on the Mac, do a quick search and see what they use to produce a stack trace.

**Comment by bourdoncle** [comment]
```
Try this command:

$ MAGICK_SYNCHRONIZE=true magick -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
Does that resolve the issue?
```

No, it still ends with an error message on my Intel Mac.

**Comment by fmw42** [comment]
I installed gdb 12.1, but still getting errors on run and bt and where.

```
gdb im7 magick 
run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
bt
```

```
bash-3.2$ gdb im7 magick 
bash: gdb: command not found
bash-3.2$ run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
bash: run: command not found
bash-3.2$ bt
bash: bt: command not found

```

I cannot find either run or bt on MacPorts.

**Comment by urban-warrior** [comment]
`run` and `bt` are `gdb` commands.  If you installed `gdb` , it should include the `gdb` executable.  Try a `find` command to locate it.

**Comment by fmw42** [comment]
```
find /opt -name gdb

/opt/local/libexec/gnubin/gdb
/opt/local/include/gdb
/opt/local/var/macports/software/gdb
/opt/local/var/macports/sources/rsync.macports.org/macports/release/tarballs/ports/devel/gdb
/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_graphics_opencv4/opencv4/work/opencv-opencv-8a18519/samples/gdb
/opt/local/share/gdb
/opt/local/share/glib-2.0/gdb

```

I do not see anything in /opt/local/bin nor /opt/bin.  So which path is relevant?

I took a guess at:

```
/opt/local/libexec/gnubin/gdb im7 magick 
run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
bt
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin21.3.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
"/Users/fred/Applications/ImageMagick-Scripts/bin/im7": not in executable format: file format not recognized
/Users/fred/Desktop/magick: No such file or directory.
(gdb) run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
Starting program:  -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
Note: this version of macOS has System Integrity Protection.
Because `startup-with-shell' is enabled, gdb has worked around this by
caching a copy of your shell.  The shell used by "run" is now:
    /Users/fred/Library/Caches/gdb/bin/zsh
No executable file specified.
Use the "file" or "exec-file" command.
bt
(gdb) bt
No stack.
(gdb) 

```

**Comment by urban-warrior** [comment]
Instead of `im7 magick` find the magick executable path and use it instead, something like `/opt/local/libexec/gnubin/gdb /usr/local/bin/magick`.

**Comment by fmw42** [comment]
I do not have IM 7 installed. I compiled it, but use the im7 script to run it.

**Comment by urban-warrior** [comment]
`im7` is a script.  Somewhere inside the script it points to the `magick` utility.  Find the path to the `magick` utility and use it with `gdb`.  `gdb` need the executable path to work properly, not an indirect script.

**Comment by fmw42** [comment]
I don't think that works since my IM 7 is not installed, just compiled.  Here is what happens

```
/opt/local/libexec/gnubin/gdb /Users/fred/Applications/ImageMagick-7.1.0-62/utilities/magick 
run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
bt
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin21.3.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...

"/Users/fred/Applications/ImageMagick-7.1.0-62/utilities/magick": not in executable format: file format not recognized

(gdb) run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
Starting program:  -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
No executable file specified.
Use the "file" or "exec-file" command.
bt
(gdb) bt
No stack.

```

**Comment by fmw42** [comment]
P.S. This was my im7 script:

```
#!/bin/sh
#
#  im imagemagick_command args....
#
# Run the given Imagemagick command directly from the predefined build
# directory.  This script lets me run the test version IM command from
# anywhere, not just within the build directory.
#
# This script was based on the "magick.sh" command.
#
#DIR='$HOME/Applications/IMv7'
DIR='/Users/fred/Applications/ImageMagick-7.1.0-62'

# testing scripts...
export PATH="$DIR/utilities:${PATH}"


# The build libraries
DYLD_LIBRARY_PATH="$DIR/MagickWand/.libs:$DYLD_LIBRARY_PATH"
DYLD_LIBRARY_PATH="$DIR/MagickCore/.libs:$DYLD_LIBRARY_PATH"
export DYLD_LIBRARY_PATH

export MAGICK_CODER_MODULE_PATH="$DIR/coders"
export MAGICK_CONFIGURE_PATH="$DIR/config"
export MAGICK_FILTER_MODULE_PATH="$DIR/filters"

exec "$@"

```

**Comment by urban-warrior** [comment]
Without a stack trace, we can't help.  On our Fedora system, we get:

```
$ gdb magick
GNU gdb (GDB) Fedora Linux 12.1-7.fc37
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from magick...
(gdb) run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
Starting program: /opt/local/bin/magick -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
...
```

Notice the `Starting program: /opt/local/bin/magick`.    If you get that working on your system, you will be able to generate a stack trace to trace the line in the ImageMagick source where the abort occurs.  With that information, we can determine why its failing.

**Comment by fmw42** [comment]
I do not have either Imagemagick installed in /opt/local/bin.  It is just compiled in the download directory in my home directory (i.e. /Users/fred/Applications/ImageMagick-7.1.0-62). **It was not installed**. So I do not have a version at /opt/local/bin/magick. My only installed version is IM 6.  I always run IM 7 via the im7 script, since I can apparently have only one installed version on the Mac. Is there a way to have more than one installed version?

**Comment by urban-warrior** [comment]
You don't need an "installed" version of ImageMagick, just the path to the `magick` executable.  However, you can have both ImageMagick 6 and ImageMagick 7 installed on the same system in `/opt/local`.  You can also install it in non-default locations with the `--prefix` and `--exec-prefix` `configure` script CLI arguments.

**Comment by fmw42** [comment]
Imagemagick 7 is at /Users/fred/Applications/ImageMagick-7.1.0-62/utilities/magick 

But the following command does not work. The error message is

`"/Users/fred/Applications/ImageMagick-7.1.0-62/utilities/magick": not in executable format: file format not recognized`

That is why I though it Imagemagick needs to be installed, not just compiled.  Does this message mean anything to you?


```
/opt/local/libexec/gnubin/gdb /Users/fred/Applications/ImageMagick-7.1.0-62/utilities/magick 
run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
bt
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin21.3.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...

"/Users/fred/Applications/ImageMagick-7.1.0-62/utilities/magick": not in executable format: file format not recognized


(gdb) run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
Starting program:  -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
No executable file specified.
Use the "file" or "exec-file" command.
bt
(gdb) bt
No stack.

```

**Comment by urban-warrior** [comment]
List `/Users/fred/Applications/ImageMagick-7.1.0-62/utilities/magick`, you'll find its a script that points to the actual executable, perhaps in `/Users/fred/Applications/ImageMagick-7.1.0-62/utilities/magick/.libs`.  To avoid all the possible shared library issues, try building a static version of ImageMagick which will land the executable @ `/Users/fred/Applications/ImageMagick-7.1.0-62/utilities/magick`.  Use `./configure --disable-shared`.

**Comment by fmw42** [comment]
Can I call you or you call me about this abort 6 issue?  I have just a couple of question to be sure I know what I am doing with the install.

Fred

**Comment by urban-warrior** [comment]
The issue is that we don't know what we're doing when it comes to building under the Mac.  Its been too many years.  We've exhausted all the help we can provide.

**Comment by fmw42** [comment]
I was going to build IM 7 as you suggested to see if I can get your debug information. Will that not help?

**Comment by urban-warrior** [comment]
This is how we build and debug under Linux.  Give it a shot and see if it works for you:

```
$ tar xvf ImageMagick-7.1.0-63.tar.gz
$ cd ImageMagick-7.1.0-63
$ ./configure --disable-shared
$ make -j
$ cp */*.xml .
$ ./utilities/magick --version
$ gdb ./utilities/magick
run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
```

If it aborts, type

```
bt
```

to generate the backtrace and post the stack trace here.  If the command complete without any issues, no stack trace will be generated.  We checked the command under Fedora, CentOS, Ubuntu, and Windows and the command completes without any complaints.

**Comment by fmw42** [comment]
My questions are:

1) No make install --- is that correct?
2) Will this interfere with either my IM 6 with make install (default location on /usr/local) or my IM 7 ( n /opt/local) that did not have a make install and for which I use the im7 script

**Comment by urban-warrior** [comment]
No `make install`.  No interference with IM 6 since you are not install.  This is a stand-alone test environment.

**Comment by fmw42** [comment]
My gdb was installed via MacPorts. But seems to be in an odd directory. The results seem to show some issue.

```
$ /opt/local/libexec/gnubin/gdb ./utilities/magick

GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-apple-darwin21.3.0".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./utilities/magick...
(gdb) run -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
Starting program: /Users/fred/Applications/ImageMagick-7.1.0-63beta/utilities/magick -size 5820x7760 canvas:Black -distort Perspective "581,7740,534,7633 1428,7492,1356,7633 1450,9234,1356,9095 593,9000,534,9095" null:
Unable to find Mach task port for process-id 35773: (os/kern) failure (0x5).
 (please check gdb is codesigned - see taskgated(8))
(gdb) 

```

**Comment by urban-warrior** [comment]
See [gdb Debugger for macOS](https://thomaskov.medium.com/gdb-debugger-for-macos-5cb7751dc0a9#:~:text=This%20guide%20will%20walk%20you%20through%20the%20steps%20of%20installing,installed%20it%2C%20check%20out%20here).

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by bourdoncle** [comment]
Thank you so much for spending time on fixing this one! 👍🏻
