### ISSUE TITLE
SIGSEGV with empty `-process`

### ISSUE THREAD

**Issue by george-hopkins** [ImageMagick/ImageMagick#6080]
### ImageMagick version

7.1.0-62

### Operating system

Linux

### Operating system, version and so on

Alpine Linux

### Description

A null pointer gets passed to `strchr` when giving an empty `-process` filter:

https://github.com/ImageMagick/ImageMagick/blob/c6efe14959b8801471259d47858b177ea3890298/MagickWand/mogrify.c#L8772

### Steps to Reproduce

`convert a.jpg -process ' ' b.jpg`

**Comment by dlemstra** [comment]
Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
