### ISSUE TITLE
Duplicate unhelpful error messages

### ISSUE THREAD

**Issue by nneil** [ImageMagick/ImageMagick#6083]
### ImageMagick version

7.1.0-62

### Operating system

Linux

### Operating system, version and so on

CentOS Linux release 7.9.2009 (Core)

### Description

The command:

```
magick convert -background "#555555" -fill white -size 320x320 -gravity center -border 100x100 -bordercolor "#555555" caption:text image.jpg
```

Produces many lines of unhelpful error messages.

```convert: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/2070.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/2070.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/2070.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/2070.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/2070.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/2070.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: delegate library support not built-in 'none' (Freetype) @ warning/annotate.c/RenderFreetype/2070.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/741.
convert: no images defined `image.jpg' @ error/convert.c/ConvertImageCommand/3342.
```

Can these be consolidated?

It's also not clear me what they mean. They seem directed to a developer rather than an end-user.

### Steps to Reproduce

```
magick convert -background "#555555" -fill white -size 320x320 -gravity center -border 100x100 -bordercolor "#555555" caption:text image.jpg
```

**Comment by urban-warrior** [comment]
ImageMagick extends it capabilities by leveraging external delegate library such as Freetype for superior font rendering.  When you built ImageMagick, you did not first install Freetype so ImageMagick defers to another font renderer such as Postscript or X11.  The recommended solution is to rebuild/reinstall ImageMagick after you first install the Freetype delegate library, development edition.

In your example, an exception is thrown each time you request metrics  or render a font.  No worries, however, ImageMagick is designed to stop throwing exceptions after the first 1000 warnings.  We could track which exceptions are thrown, but that requires we maintain a memory pool which adds overhead and slows processing of ImageMagick.  Its a compromise not to do so.  In most cases, ImageMagick throws one or two exceptions.  Your case is rare.
