### ISSUE TITLE
Bug: Failure to convert animated .avif to .apng

### ISSUE THREAD

**Issue by LuminairPrime** [ImageMagick/ImageMagick#6086]
### ImageMagick version

7.1.0-62

### Operating system

Windows

### Operating system, version and so on

Win10

### Description

Converting animated .avif to .apng produces a single PNG file with no animation.

There does not appear to be documentation on the website about converting animated AVIF to animated APNG. The "Animation Basics" and "Image Formats" documentation pages don't mention animated AVIF.

### Steps to Reproduce

Sample file: https://cdn.7tv.app/emote/60ae7316f7c927fad14e6ca2/4x.avif

Command: `magick 4x.avif avif_test1.apng`

**Comment by fmw42** [comment]
try

`magick 4x.avif APNG:avif_test1.apng`
