### ISSUE TITLE
Bug: Failure to convert animated .webp to .apng

### ISSUE THREAD

**Issue by LuminairPrime** [ImageMagick/ImageMagick#6087]
### ImageMagick version

7.1.0-62

### Operating system

Windows

### Operating system, version and so on

Win10

### Description

Converting animated .webp to .apng produces animation with warped frames. 

The frames ImageMagick extracts from the .webp appear to be modified into different resolutions than the source and destination files. When ImageMagick assembles the frame files into the animated destination file, they are again modified, stretched to the destination resolution, producing the warped result.

There does not appear to be documentation on the website about converting animated WEBP to animated APNG. 

### Steps to Reproduce

Sample file: https://cdn.7tv.app/emote/60ae7316f7c927fad14e6ca2/4x.webp

Command: `magick 4x.webp webp_test1.apng`

**Comment by urban-warrior** [comment]
@fmw42 says: Try

`magick 4x.avif APNG:avif_test1.apng`

See https://imagemagick.org/script/formats.php.
