### ISSUE TITLE
cpu exhaustion in deal with svg

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#609]
Version: ImageMagick 7.0.6-3 Q16 x86_64
`#./convert $FILE OUT.png`
When convert svg file , imagemagick will read data from input file and deal with it, here is the critical code:
blob.c , in function ReadBlob:

`          count=(ssize_t) fread(q,1,length,image->blob->file_info.file); //3266`

The value of "length" was not checked correctly, it can be controlled by input file , also it`s default value is too big.A crafted file will cause cpu exhaustion.
testcase: https://github.com/bestshow/p0cs/blob/master/cpu_exhaustion_in_deal_with_svg.svg
Credit : ADLab of Venustech

**Comment by mikayla-grace** [comment]
ReadBlob(), which subsumes the fread() method you mention, is behaving correctly.  It should and will read bytes from a file for the specified length.  Any checks for length must comes from the coder modules.  Unfortunately, we cannot reproduce the problem.  The conversion completes in seconds for us with ImageMagick 7.0.6-3 as expected.  Can you help us reproduce the problem?

**Comment by bestshow** [comment]
@mikayla-grace Sorry,I think it is a misinformation in my test environment.
