### ISSUE TITLE
changing the path for ImageMagick

### ISSUE THREAD

**Issue by soluna1** [ImageMagick/ImageMagick#61]
Hi,
I've been trying to install ImageMagick several times, and finally I did according to http://cactuslab.com/imagemagick/ which installed it in /opt/ folder (being all the libraries installed there: $ $/opt/ImageMagick/bin/convert -version
Version: ImageMagick 6.9.1-0 Q16 x86_64 2015-03-22 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: DPC OpenCL
Delegates (built-in): bzlib fftw fontconfig freetype jng jpeg lcms lzma png tiff webp x xml zlib)

However, there is another convert in opt/local/bin/ and the typing:
$convert -list configure | grep -i "delegates"
DELEGATES      bzlib mpeg x

Then, I think that I need to change the Path in the .profile file, but I don't know to do that. Could someone help me whit this??

Thanks

**Comment by mikayla-grace** [comment]
We answer ImageMagick issues here, your question is more about the Linux shell.  Post your question to a Linux's forum for help with your .profile and execution path.
