### ISSUE TITLE
heic convert to jpg was failed

### ISSUE THREAD

**Issue by wuchencm** [ImageMagick/ImageMagick#6119]
### ImageMagick version

7.1.0-62

### Operating system

Linux

### Operating system, version and so on

ubuntu 20.04 

### Description

kernal:
Linux 708bdfa6cac2 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

root@708bdfa6cac2:/imgs# magick -version
Version: ImageMagick 7.1.0-62 Q16-HDRI x86_64 74b3683a4:20230211 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) TCMalloc 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jpeg lcms lqr lzma openexr pangocairo png ps raqm raw tiff webp wmf x zip zlib
Compiler: gcc (9.4)

**others:**
root@708bdfa6cac2:/imgs# identify -list format | grep HEIC
     HEIC  rw+   High Efficiency Image Format (1.6.1)

error message:
root@708bdfa6cac2:/imgs# magick a1.heic a1.jpg  
magick: Unsupported feature: Unsupported color conversion (4.3003) `a1.heic' @ error/heic.c/IsHEIFSuccess/139.

note: the online tools is ok (https://heic.online/)

### Steps to Reproduce

 magick a1.heic a1.jpg  

### Images

[images.zip](https://github.com/ImageMagick/ImageMagick/files/10857717/images.zip)

**Comment by fmw42** [comment]
Your libheif is too old.  Update your libheif.  Your command works fine for me with libheif at 1.15.1.

**Comment by wuchencm** [comment]
Yes, it works fine at libheif 1.15.1
