### ISSUE TITLE
YCbCr support for 4:2:0 no longer correct?

### ISSUE THREAD

**Issue by figgis** [ImageMagick/ImageMagick#612]
Using

$ display -version
Version: ImageMagick 7.0.6-3 Q16 x86_64 2017-07-25 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): fontconfig freetype jbig jng jpeg lzma openexr pangocairo png tiff x xml zlib

Viewing and/or converting YCbCr 4:2:0 plane-separated data produce faulty output.

To convert the first frame from BQMall_832x480_60.yuv to a png, I normally use

`convert -size 832x480 -depth 8 'BQMall_832x480_60.yuv[1]' b1.png`

The result
![b1](https://user-images.githubusercontent.com/124234/28565183-c761fe34-712b-11e7-9911-c53eaf11f84a.png)

Using the `-sampling-factor` doesn't seem to resolve the issue.

Many test-sequences of YCbCr 4:2:0 can be downloaded from
https://media.xiph.org/video/derf/

They are however in y4m-format, but they can easily be converted to yuv using ffmpeg
`ffmpeg -i foreman_cif.y4m foreman_cif.yuv`

Output from

`display -size 352x288 -depth 8 foreman_cif.yuv[1]`

![f1](https://user-images.githubusercontent.com/124234/28565633-11a44b2c-712d-11e7-9247-061a8f3126d6.png)

The input files are correct and is verified using e.g. http://www.offminor.de/, ffmpeg, etc...

**Comment by dlemstra** [comment]
Do you have the same issue with ImageMagick 6?

**Comment by figgis** [comment]
Using this on another machine with debians default version of imagemagick produce the correct result!

`display -size 352x288 -depth 8 -colorspace sRGB foreman_cif.yuv[1]`

convert -version:
Version: ImageMagick 6.8.9-9 Q16 x86_64 2017-07-15 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib

Adding the `sRGB` to 7.0.6-3 still gives me a broken output

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by figgis** [comment]
Cool! Thanks for excellent communication and speed :-)
