### ISSUE TITLE
PDF to JPG - missing digital signatures - '-dPrinted=false' option of GS

### ISSUE THREAD

**Issue by MrGutis** [ImageMagick/ImageMagick#6128]
### ImageMagick version

7.1.0-46

### Operating system

Linux

### Operating system, version and so on

Ubuntu 18.04.6 LTS

### Description

Converting PDF with digital signature to JPG/PNG results in missing digital signature in final image.

### Steps to Reproduce

`convert -verbose signature.pdf output.jpg`
The output will contain GS option `-dPrint=false`.
Replacing with `-dPrint=true` would result in correct output with digital signature visible. Solution would be not to hardcode `-dPrint=false` but make it default and give option to change it if needed.

**Comment by dlemstra** [comment]
I really don't think we should change the default according to the documentation:

> Determines whether the file should be displayed or printed using the "screen" or "printer" options for annotations and images. With -dPrinted, the output will use the file's "print" options; with -dPrinted=false, the output will use the file's "screen" options. 

Since we are creating an image that will be shown on a screen the `-dPrinted=false` should be the default. But maybe we could add an option that would allow you to change it to true.

**Comment by MrGutis** [comment]
> Since we are creating an image that will be shown on a screen the -dPrinted=false should be the default. But maybe we could add an option that would allow you to change it to true.
That was my actual suggestion. Sorry if I was not clear enough.
> Solution would be not to hardcode -dPrint=false but make it default and give option to change it if needed.

**Comment by grunlowen2** [comment]
I have the same issue. I load a PDF into Python Wand (which fronts ImageMagick) and the digital signature is not included. If I use the bytes to make a new PDF (with Wand it is 'img.make_blob()'), and create a new PDF, the entire page is there, except for the digital signature. Trying to figure out how I can get around this. I see the OP posted the -dPrinted=True option, but it sounds like that would require a modification to the code? I have created a Lambda Layer that includes ImageMagick, so I can make the change there and redeploy it, but it is a bit of a pain. If there is another option, or if I am misunderstanding the solution, please let me know.

**Comment by grunlowen2** [comment]
Actually, in my case they aren't actually signatures. They are PDF Rectangles, so I think they have been pasted onto the document. So I need to figure out how to include those Rectangles when I load my PDFs into ImageMagick via Wand.

Most Docusign and Adobe signatures show up for me. I have no idea what is different about the Rectangle objects, but I can open the document in Acrobat and add a comment on the Rectangle, but that is the only information Adobe gives me about what part of the PDF. The properties of it just say 'Rectangle'.

I have tried merging layers via Wand, but no matter what I try I seem to lose the content of that Rectangle, which I assume was copy/pasted into that area of the PDF.

**Comment by MrGutis** [comment]
As I build own docker images with ImageMagick from the source I've used sed to tweak source code as a workaround for the time being
```
ARG IM_WANTED_VERSION=7.1.0-62

RUN cd /opt && \
  git clone https://github.com/ImageMagick/ImageMagick.git && \
  cd ImageMagick && git checkout ${IM_WANTED_VERSION} && \
  # hotfix for IM to sent to GS -dPrinted=true (to generate images with digital signatures)
  echo "*** BEFORE" && cat coders/pdf.c | grep "dPrinted" && \
  sed -i 's/-dPrinted=false/-dPrinted=true/' "coders/pdf.c" && \
  echo "*** AFTER" && cat coders/pdf.c | grep "dPrinted" && \
  ./configure --with-modules --without-magick-plus-plus --disable-docs --disable-static --with-tiff && \
  make -j$(nproc) && make install && \
  ldconfig /usr/local/lib && \
  cd .. && rm -rf /opt/ImageMagick
```
But I still need to do much more testing for side effects on this solution (if any).

**Comment by dlemstra** [comment]
In the next version of ImageMagick 7 you will be able to do this:

`magick -verbose -define pdf:printed=true signature.pdf output.jpg`

**Comment by alphyon** [comment]
@MrGutis It's work
