### ISSUE TITLE
High CPU Load on M1 MacOS

### ISSUE THREAD

**Issue by mslmn** [ImageMagick/ImageMagick#6150]
### ImageMagick version

ImageMagick 7.1.1-2 Q16-HDRI aarch64 20952

### Operating system

MacOS

### Operating system, version and so on

Ventura 13.2.1

### Description

I've noticed that the magick command uses up all available CPU load when running through the terminal, and it takes a lot longer to finish running a command than it used to. This also slows down the rest of the device.

### Steps to Reproduce

Running any magick command.

**Comment by urban-warrior** [comment]
Post your command-line plus any images you use.  We need to reproduce the issue locally before we can comment.

**Comment by mslmn** [comment]
I'm using `parallel -N4 magick mogrify -depth 4 ::: *png` on about 200 images.

**Comment by urban-warrior** [comment]
ImageMagick is already threaded.  If you want to use `parallel`, make `magick` single threaded with `-limit thread 1` to reduce the load on your system.

**Comment by ValZapod** [comment]
Is it this? https://stackoverflow.com/questions/75189107/gnu-parallel-usage-in-m1mac-running-osx-13-1

Why are you using it? Does it make a difference??

**Comment by urban-warrior** [comment]
Its your choice to parallelize your algorithm anyway you want.  We were pointing out that if you run multiple instances of ImageMagick in parallel, each instance will try to consume all the cores on your system so in some cases it will thrash your host.  To prevent thrashing, you can run a single instance of ImageMagick across all cores or you can run multiple instances of ImageMagick in parallel and reduce the threads to one-- one per instance.  As an example, assume you have a 4 core system and you run 4 instances of ImageMagick. Each instance of ImageMagick will consume 4 cores for a total of 16 cores-- which likely will clock your host.  If you limit the # of threads in each instance of ImageMagick to 1, then the total consumed cores is 4.  That will ensure your host is not overwhelmed by ImageMagick.

**Comment by mslmn** [comment]
> ImageMagick is already threaded. If you want to use `parallel`, make `magick` single threaded with `-limit thread 1` to reduce the load on your system.

Seems this solved the issue.
