### ISSUE TITLE
image with meta channel created from using -channel-fx does not look correct

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#6159]
### ImageMagick version

7.1.1.3

### Operating system

MacOS

### Operating system, version and so on

Monterey

### Description

The result of adding a grayscale image to an RGB in the meta channel results in an image that shows the meta channel as if it was in the alpha channel.  Is this the way it should look? Does not seem correct to me. Is there a bug?

Input:

![lena](https://user-images.githubusercontent.com/13458218/224761070-41aeda93-b7c7-40ba-80f8-652ea2aeee8d.png)

![mandril3](https://user-images.githubusercontent.com/13458218/224761081-fdb9d083-5efd-4842-9da7-ba631e586091.jpg)

`magick lena.png \( mandril3.jpg -colorspace gray \) -channel-fx '| gray=>meta’ meta.tif
`

[meta.tif.zip](https://github.com/ImageMagick/ImageMagick/files/10959346/meta.tif.zip)

### Steps to Reproduce

see above

### Images

see above

**Comment by urban-warrior** [comment]
The `display` program displays the image properly-- no alpha blending.    Some applications assume that an extra channel is automatically an alpha channel.  It's not.  If it is an alpha channel, it should be marked as EXTRASAMPLE_ASSOCALPHA or EXTRASAMPLE_UNASSALPHA.  If its is marked as EXTRASAMPLE_UNSPECIFIED, it should not be interpreted as alpha.

**Comment by fmw42** [comment]
Thanks.  That must be the issue.  IM display and Photoshop view it correctly.  But Mac Preview and GraphicConverter show the meta channel as an alpha.
