### ISSUE TITLE
regression/undocumented change of `-page` behaviour in IM7

### ISSUE THREAD

**Issue by eddy-geek** [ImageMagick/ImageMagick#6160]
### ImageMagick version

7.1.1-3

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04, latest `ImageMagick--clang-x86_64.appimage` from today

### Description

Following tutorial [Merging - to Create a New Layer Image](https://imagemagick.org/Usage/layers/#merge) -- this is presumably the latest / IM7 version ?!

At the time of writing this, it says 

```sh
  magick -page +5+10  balloon.gif   -page +35+30 medical.gif  \
          -page +62+50 present.gif   -page +10+55 shading.gif  \
          -background dodgerblue  -layers merge  +repage layers_merge.gif
```

I only changed the samples to use instead the font_*.gif images from this repo (where are the samples for the tutorial?):

```sh
for i in 0 1 2 3 ; do
  wget https://raw.githubusercontent.com/ImageMagick/ImageMagick/main/MagickWand/tests/font_${i}.gif
done

magick -page +5+10 font_0.gif -page +35+30 font_1.gif \
  -page +62+50 font_2.gif -page +10+55 font_3.gif \
  -background dodgerblue  -layers merge  +repage layers_merge.gif
```

This gives the following "wrong" or at least undocumented result:

![layers_merge](https://user-images.githubusercontent.com/2772505/224777487-4a39f514-3d70-4ba8-bac7-022d6c877146.gif)

ImageMagick 7.1.0-19 AppImage from December 2021 gives the same result.

But good old `convert` from Ubuntu universe *8:6.9.11.60+dfsg-1.3ubuntu0.22.04.1* gives expected/documented result:

```sh
convert -page +5+10 font_0.gif -page +35+30 font_1.gif \
  -page +62+50 font_2.gif -page +10+55 font_3.gif \
  -background dodgerblue  -layers merge  +repage layers_merge.gif
```

![layers_merge](https://user-images.githubusercontent.com/2772505/224778362-6af69368-cece-450b-9111-b89a534b1530.gif)

So is the documentation outdated or is this a real regression from IM7 ?

**Comment by eddy-geek** [comment]
found the following "fix", to use parentheses:

```sh
magick \( -page +5+10 font_0.gif \) \( -page +35+30 font_1.gif \) \
 \(  -page +62+50 font_2.gif \) \( -page +10+55 font_3.gif \) \
  -background dodgerblue  -layers merge  +repage layers_merge.gif
```

![layers_merge7w](https://user-images.githubusercontent.com/2772505/224781389-9ffe0638-e968-40f1-92bd-a028f56aa45f.gif)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
