### ISSUE TITLE
Weird artifacts when converting PDF to JPG

### ISSUE THREAD

**Issue by meator** [ImageMagick/ImageMagick#6161]
### ImageMagick version

7.1.0-62

### Operating system

Linux

### Operating system, version and so on

VoidLinux

### Description

Hi. I'm working on some things in LaTeX. When I include a PNG image, ImageMagick converts it just fine but then all other text gets pretty much destroyed.

### Steps to Reproduce

Here is the LaTeX file:
```tex
\documentclass{article}
\usepackage{graphicx}

\begin{document}
Test test.

\includegraphics[scale=0.5]{geogebra-export.png}

Test test.
\end{document}
```

It can be "compiled" with `pdflatex <filename.tex>`. I have included the compiled PDF in the following section. The `geogebra-export.png` file is also included in the following section.

When I convert this file to JPG using `convert -density 1500 file.pdf file.jpg`, the text becomes black. This can be seen in the `broken-image.jpg` file. I'm unsure if this is an error on my side but my PDF viewer can display the PDF just file and I've tried other tools to convert the PDF and they have worked as expected.

### Images

[geogebra-export.png](https://user-images.githubusercontent.com/67633081/224827649-4962e99a-0d56-4295-ba2a-bea053e7b75e.png)
[file.pdf](https://github.com/ImageMagick/ImageMagick/files/10961754/file.pdf)
[broken-image.jpg](https://user-images.githubusercontent.com/67633081/224827758-f3082985-c810-413d-ae8c-87395327f2bb.jpg)

**Comment by fmw42** [comment]
Your PDF has an alpha channel and some of the information you want is in the alpha channel and JPG does not support and transparency. So you have to make the background white to see it all.

`convert -density 1500 file.pdf  -background white -alpha background file.jpg`

![file](https://user-images.githubusercontent.com/13458218/224831290-cb45bea2-f23d-43bd-bb79-04fee44fbda6.jpg)

**Comment by meator** [comment]
Oh, I didn't know that. Thanks!
