### ISSUE TITLE
Gistesy font - some upper case letters are partially cut in a text box

### ISSUE THREAD

**Issue by joyresourceshub** [ImageMagick/ImageMagick#6163]
### ImageMagick version

7.1.0-61

### Operating system

MacOS

### Operating system, version and so on

Big Sur 11.7.4

### Description

Hi,

When trying to use Gistesy font in a text box in position west, when certain letters are used first occurs a partial cut - as in the attachment.

Thank you for fixing the bug if feasible.

### Steps to Reproduce

Create a text box with a text starting with J uppercase, with Gistesy font, position west.

### Images

![out-dr-name-over-1-Johnson-final](https://user-images.githubusercontent.com/119510808/225032971-490810f3-fa73-4a81-a397-8058c6c51abd.png)

**Comment by urban-warrior** [comment]
Post the command-line you use to create your rendering.  We need to reproduce the issue locally before we can comment.
