### ISSUE TITLE
load Magick::Image from string in C++ Magick: NoDecodeDelegateForThisImageFormat ' @ error/blob.c/BlobToImage/458`

### ISSUE THREAD

**Issue by sj3203** [ImageMagick/ImageMagick#6180]
### ImageMagick version

7.0.8-62

### Operating system

Linux

### Operating system, version and so on

Debian GNU/Linux 8.11

### Description

The image is downloaded from this [URL](https://images.xinglinpukang.com/upload/doctor/auth/201906/20190613083117525_s.jpg), which can be loaded normally in the following way

        Magick::Image image(file_name.c_str());
        cout << "magick is " << image.magick() << endl;
        cout << "baseColumns is " << image.baseColumns() << endl;
        cout << "baseRows is " << image.baseRows() << endl;
When the file is converted into a string, and the blob is converted into an Image object

        std::string content = get_file_contents(file_name.c_str());
        const size_t len = content.size();
        Magick::Blob blob(static_cast<const void *>(content.c_str()), len);
        Magick::Image image;
an error message will appear: Magick: NoDecodeDelegateForThisImageFormat ' @ error/blob.c/BlobToImage/458`

### Steps to Reproduce

I guessed it was a problem with my program, so I tried to change the pictures, and it turned out that most of the pictures can work normally, but the pictures with problems that can be opened normally on the browser cannot work normally

Is there anything special about this picture? How should I load Image from string

**Comment by dlemstra** [comment]
Please don't open both a discussion and issue!
