### ISSUE TITLE
Alpha channel handling not working correctly

### ISSUE THREAD

**Issue by gursch** [ImageMagick/ImageMagick#6187]
### ImageMagick version

 7.1.1-4

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

I was using version  7.1.0-28 and I was able to extract the alpha channel from an image using: convert demo.tif -alpha extract extract.png

It worked perfectly on 7.1.0. The alpha channel was extracted. When I use the same command in 7.1.1-4 I get only a white image. 

### Steps to Reproduce

convert demo.tif -alpha extract extract.png

Extracts the alpha channel. extract.png is white but should contain the alpha channel image.

### Images

[demo.zip](https://github.com/ImageMagick/ImageMagick/files/11059385/demo.zip)

**Comment by fmw42** [comment]
On IM 7, you should be using magick not convert.  Nevertheless, it fails for me using either convert or magick with a white image also. I think that is because magick identify  -verbose only lists RGB and meta[0].

```
 Channel depth:
    Red: 8-bit
    Green: 8-bit
    Blue: 8-bit
    Meta channel[0]: 8-bit

```

Tested with IM 6.9.12-82 and 7.1.1-4  on Mac OSX Monterey

**Comment by urban-warrior** [comment]
Your image returns these attributes:

```  
  Image Width: 472 Image Length: 392
  Resolution: 300, 300 pixels/inch
  Bits/Sample: 8
  Compression Scheme: None
  Photometric Interpretation: RGB color
  Extra Samples: 1<unspecified>
```

The TIFF docs say

```
If an extra sample is used to encode information that has little or nothing to do with alpha, ExtraSample=0 (EXTRASAMPLE_UNSPECIFIED) is recommended.
```

Extra samples declared as unspecified are interpreted as a meta channel by ImageMagick.  If the extra sample are true transparency values, label your extra channels as associated alpha.

**Comment by fmw42** [comment]
Or you can do 

`magick demo.tif -define tiff:alpha=associated demo.tif`

That will convert the alpha (meta) channel into background transparency (as viewed in Photoshop).

Before:

![Screen Shot 2023-03-25 at 11 10 42 AM](https://user-images.githubusercontent.com/13458218/227734288-6c42a3c8-5f49-4dc5-9b3b-47766bffab80.png)

After:

![Screen Shot 2023-03-25 at 11 11 02 AM](https://user-images.githubusercontent.com/13458218/227734295-d44153d7-e847-4ccb-b62b-efb7b2b16bcc.png)

**Comment by gursch** [comment]
Thanks for the information. Very interesting, I will try it.

**Comment by gursch** [comment]
-channel-fx "meta=>alpha" work great.
