### ISSUE TITLE
XML delegate not built-in due to missing libxml2-dev package

### ISSUE THREAD

**Issue by bits** [ImageMagick/ImageMagick#6190]
### ImageMagick version

7.1.1-4

### Operating system

Linux

### Operating system, version and so on

Debian 11 bullseye

### Description

Building from HEAD results in binaries without XML delegate built-in.  Using 7.1..0-62, it builds fine on the same system.

Trying to use it on a file with embedded XML results in the following error message:

`Exception 320: delegate library support not built-in ''PATH_TO_PNG_WITH_XML'' (XML) @ warning/profile.c/ValidateXMPProfile/1946 at … line …`

In both versions, `./configure` finds libxml2, configures --with-xml=yes, and sets CFLAGS and LIBS with xml:

> …
> checking for libxml-2.0 >= 2.0.0... yes
> …
> XML               --with-xml=yes		yes
> …
> CFLAGS          = -I/usr/include/libxml2 -I/usr/include/x86_64-linux-gnu -I/usr/include/libpng16  -I/usr/include/freetype2 -I/usr/include/libpng16  -fopenmp -Wall -g -O2 -mtune=haswell -fexceptions -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
> …
> LIBS            =  -ljbig  -ltiff -lfreetype  -ljpeg    -lpng16 -lz                -llzma       -lxml2  -lz     -lm    -lpthread 

However, the resulting build of 7.1.1-4 doesn't have the xml delegate:

> ❭ magick -version
> Version: ImageMagick 7.1.1-4 (Beta) Q16-HDRI x86_64 c5d5e7117:20230311 https://imagemagick.org
> Copyright: (C) 1999 ImageMagick Studio LLC
> License: https://imagemagick.org/script/license.php
> Features: Cipher DPC HDRI OpenMP(4.5) 
> Delegates (built-in): freetype jbig jng jpeg lzma png tiff zlib
> Compiler: gcc (10.2)

While 7.1.0-62 does have the XML delegate:

> ❭ magick -version
> Version: ImageMagick 7.1.0-62 Q16-HDRI x86_64 74b3683a4:20230211 https://imagemagick.org
> Copyright: (C) 1999 ImageMagick Studio LLC
> License: https://imagemagick.org/script/license.php
> Features: Cipher DPC HDRI OpenMP(4.5) 
> Delegates (built-in): freetype jbig jng jpeg lzma png tiff xml zlib
> Compiler: gcc (10.2)

### Steps to Reproduce

No XML delegate:
```
sudo apt install build-essential libfreetype6 libfreetype6-dev libpng-dev libjpeg-dev libtiff6 libtiff-dev libperl-dev ghostscript libltdl-dev pkg-config
git clone https://github.com/ImageMagick/ImageMagick.git
cd ImageMagick
./configure
make -j$(nproc)
./utilities/magick -version
# → Delegates (built-in): freetype jbig jng jpeg lzma png tiff zlib
```

Checking out 7.1.0-62 gets working XML delegate:
```
sudo apt install build-essential libfreetype6 libfreetype6-dev libpng-dev libjpeg-dev libtiff6 libtiff-dev libperl-dev ghostscript libltdl-dev pkg-config
git clone https://github.com/ImageMagick/ImageMagick.git
cd ImageMagick
git checkout 7.1.0-62
./configure
make -j$(nproc)
./utilities/magick -version
# → Delegates (built-in): freetype jbig jng jpeg lzma png tiff xml zlib
```

**Comment by urban-warrior** [comment]
Check `MagickCore/magick-baseconfig.h`.  Does it have this define:

```
#ifndef MAGICKCORE_XML_DELEGATE
#define MAGICKCORE_XML_DELEGATE 1
#endif
```

Or is `XML_DELEGATE` undefined?  If its undefined, the XML library was not validated properly by `./configure`.

**Comment by bits** [comment]
Thanks — As you suspected, `MagickCore/magick-baseconfig.h` did not contain the `MAGICKCORE_XML_DELEGATE` define after`./configure`

Installing the missing  `libxml2-dev` apt package resolved the issue.

For reference, the shell sequence that worked:

```
sudo apt install git build-essential pkg-config libpng-dev libjpeg-dev \
  libtiff-dev libfreetype-dev libltdl-dev libxml2-dev libperl-dev ghostscript &&
git clone https://github.com/ImageMagick/ImageMagick.git &&
cd ImageMagick &&
./configure &&
make -j$(nproc) &&
sudo make install &&
sudo ldconfig -v /usr/local/lib
```
Resulted in a good build with the XML delegate built-in:
```
$ magick -version
Version: ImageMagick 7.1.1-6 (Beta) Q16-HDRI x86_64 2d24be538:20230326 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): freetype jbig jng jpeg lzma png tiff xml zlib
Compiler: gcc (10.2)
```
