### ISSUE TITLE
It look like ppm install failed

### ISSUE THREAD

**Issue by BrandonWanHuanSheng** [ImageMagick/ImageMagick#6199]
### ImageMagick version

7.1.1.5

### Operating system

Windows

### Operating system, version and so on

Windows 10 22H2

### Description

when I run ImageMagick Setup, I noticed ppm installation failed.
![Screenshot (110)](https://user-images.githubusercontent.com/118059864/227994513-4de32147-5065-4969-b922-55d0079e888e.png)

### Steps to Reproduce

Starting the ImageMagick Setup. The setup overwrite the file to the program. I also noticed a ppm installation failed.
![Screenshot (111)](https://user-images.githubusercontent.com/118059864/227996391-82b58bc3-782f-4f93-b924-04b0f8fb3e8e.png)
![Screenshot (112)](https://user-images.githubusercontent.com/118059864/227996401-28ba9b16-561e-4eb4-b004-b48f569e122f.png)

**Comment by dlemstra** [comment]
ppm is the perl package manager. If you want to install perlmagick you will need to have perl installed on your system.

**Comment by BrandonWanHuanSheng** [comment]
Where I can get it from

**Comment by BrandonWanHuanSheng** [comment]
It look like it went successfully. I found the perl package manager on winget. The installer URL coming from the strawberryperl.com
![Screenshot (114)](https://user-images.githubusercontent.com/118059864/228186810-e9309c02-edeb-4339-b4d0-6e1d8c28af9b.png)
![Screenshot (115)](https://user-images.githubusercontent.com/118059864/228187003-a10de29a-6f76-4189-85ec-071cfeb29e3a.png)
