### ISSUE TITLE
"-set dispose background" flag corrupts output animated gif>animated gif file

### ISSUE THREAD

**Issue by necros2k7** [ImageMagick/ImageMagick#6206]
### ImageMagick version

7.1.1-5 Q16-HDRI x64, 7.1.1-6 (Beta) Q16-HDRI x64

### Operating system

Windows

### Operating system, version and so on

win11

### Description

magick convert 1.gif -set dispose background 2.gif
results in corrupted gif

### Steps to Reproduce

convert any animated gif with "-set dispose background" flag into animated gif

### Images

![1](https://user-images.githubusercontent.com/16452453/228775532-6ac94a5a-e9c1-41f5-8c44-8e7e5945aaae.gif)

**Comment by dlemstra** [comment]
You are changing the gif because you are setting this flag. This is by design and I don't understand why you are reporting this.

**Comment by dlemstra** [comment]
There is no need to edit your post in case you are reporting something by mistake. If someone else would also report something like this they will find your issue and figure out that this is by design.
