### ISSUE TITLE
Cannot use literal backslash

### ISSUE THREAD

**Issue by leviem1** [ImageMagick/ImageMagick#6209]
### ImageMagick version

7.1.1-5

### Operating system

MacOS

### Operating system, version and so on

Ventura 13.2.1 (Intel)

### Description

While experimenting with [newline escapes](https://imagemagick.org/script/escape.php), I found I was not able to get the literal `\` to work. When I use the text `everybody\nobody`, `\n` is interpreted as a new line, which is to be expected, but trying to escape the backslash using `everybody\\nobody` results in an unwanted line break. Maybe I'm missing something?

### Steps to Reproduce

Just run the following command with the attached image
`convert img.png -gravity center -fill white -pointsize 120 -font montserrat-Thin -annotate +0+0 "everybody\\nobody" out.jpg`
![img](https://user-images.githubusercontent.com/6848225/228930798-2e7eacdf-1c9e-4536-9ab3-70bc9aba3394.png)

### Images

![out](https://user-images.githubusercontent.com/6848225/228930601-a154e375-fafd-475e-b589-cd05d932a0c2.jpg)

**Comment by fmw42** [comment]
Use "\n"  in place of "\\" in that situation

**Comment by leviem1** [comment]
Not sure if I understand you. Both `everybody\nobody` and `everybody\\nobody` result in a line break. I want a way for the text to literally display `everybody\nobody`

**Comment by fmw42** [comment]
Try "everybody\nnobody". note the \n between everybody and nobody

**Comment by fmw42** [comment]
use \\\

`convert -size 1200x1200 xc:brown -gravity center -fill white -pointsize 120 -font ubuntu -annotate +0+0 "everybody\\\nobody" out.jpg`


![out](https://user-images.githubusercontent.com/13458218/228943935-7f09de54-50d7-455f-bf49-d7ab3c5da19d.jpg)

**Comment by leviem1** [comment]
Ah, that did it! Many thanks! I'm guessing this is from bash interpolating `\\n` as `\n`, then imagemagick reading the `\n` as newline? If so, that makes sense why `\\\n` would get interpolated as `\\n`, which imagemagick would then understand as literal `\n`

**Comment by fmw42** [comment]
There is no extra n. Just `\\\`

**Comment by leviem1** [comment]
I get that, I was just trying to make sense of why `\\` didn't work but `\\\` did.

**Comment by fmw42** [comment]
`I think you have to escape the \ with \\ and the third is your character \`
