### ISSUE TITLE
non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4300

### ISSUE THREAD

**Issue by murattkoc** [ImageMagick/ImageMagick#6210]
### ImageMagick version

v.3.4.3

### Operating system

Linux

### Operating system, version and so on

Ubuntu 2004

### Description

Hello, I am using php 7 and nginx in Ubuntu. I am getting such an error. **non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4300.** The file cannot be written. I used the SetFont parameter but it didn't work.

### Steps to Reproduce

```
$image = new \Imagick($certificateTemplatePath);
        // Reviewer Part
        $this->drawAwarded($image, $articleProcessReviewer->getUser()->getFullName());
        if ($isOfficeIp) {
            file_put_contents($file,"fullName => ". $articleProcessReviewer->getUser()->getFullName(). "\n", FILE_APPEND);
        }
        $maxWidth = 2500;
        $yMargin = 150;
        $yWrapMargin = 120;
        $y = 1000;
        $x = 230;
        $fontSize = 70;

        // ID Part
        $this->drawLabel($image, 'ID:', $x, $y, $fontSize);
        $articleIdDraw = new \ImagickDraw();
        $articleIdDraw->setFontSize($fontSize);
        $articleIdDraw->setFont('../app/fonts/arial.ttf');
        $image->annotateImage($articleIdDraw, $x + 520, $y, 0, $article->getId());
```

**Comment by urban-warrior** [comment]
We need to reproduce an exception before we can offer a solution.  Post a script that we can run within our local environment that reproduces the issue.  We'll investigate and offer a solution to mitigate the issue.

**Comment by murattkoc** [comment]
The strange thing is that the local server does not give an error. But I am getting error on normal server

**Comment by fmw42** [comment]
Do both systems have arial font file in the same location?  Do you have the same versions of freetype on both systems?

**Comment by dlemstra** [comment]
Can you give it another try with the latest `7.1.1-6` release? This should now give you another error message.
