### ISSUE TITLE
mean of channel for second image is always 0

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#6213]
### ImageMagick version

7.1.1.5

### Operating system

MacOS

### Operating system, version and so on

Monterey

### Description

Computation of  %[fx:v.mean.r] returns 0 for all images.

### Steps to Reproduce

```
list="lena.jpg barn.jpg mandril3.jpg monet2.jpg zelda1.jpg"
for img in $list; do
magick "$img" \( +clone -colorspace gray \) +swap \
-format "%[fx:u.mean], %[fx:v.mean.r], %[fx:v.mean.g], %[fx:v.mean.b]\n" \
info: | head -n 1
done

0.457864, 0, 0.388355, 0.413283
0.454236, 0, 0.460988, 0.510916
0.508171, 0, 0.505525, 0.443787
0.47364, 0, 0.473377, 0.261628
0.553102, 0, 0.523639, 0.488245

```

### Images

![lena](https://user-images.githubusercontent.com/13458218/229175978-b8ccac73-8115-4b22-936f-cf2cd12d32c5.jpg)
![barn](https://user-images.githubusercontent.com/13458218/229175984-eb8a1232-328f-4a90-8f5c-615c4803d50d.jpg)
![mandril3](https://user-images.githubusercontent.com/13458218/229175988-f7c2db65-ce1d-4ab0-aa8b-c4a9dfee31a0.jpg)
![monet2](https://user-images.githubusercontent.com/13458218/229175990-173dfebf-3e8b-446d-be9e-04a45d1ea07f.jpg)
![zelda1](https://user-images.githubusercontent.com/13458218/229175992-22dc9131-327e-41d5-81f8-a6376ddb1878.jpg)

**Comment by snibgo** [comment]
Not just the second image. For example:
```
magick rose: -format "%[fx:u.mean.r], %[fx:u.mean.g], %[fx:u.mean.b]\n" info:

0, 0.35004, 0.315562
```
The first value for "red" is wrong.

I will investigate.

**Comment by snibgo** [comment]
Thanks for the problem report. It also occurs with other statistics such as "maxima".

I think I have found the bug, but I need to check.

**Comment by snibgo** [comment]
In fx.c, function ImageStat, checks have been inserted for bad parameters. The problem is that these checks are over-zealous.

The checks are that `cs` isn't `NULL` and `channel > 0`. Oops, because the red channel is 0. The checks should be "`>= 0`".

These checks were not in my last release `fx2w.c`. So I give here the patch from im v7.1.1-5(Beta) and my edit of that file, which I designate `fx2aa.c`. (We have done `fx2a.c to fx2w.c, which is nearly `z`, so I start again at `aa`. My next release will be `ab`.)

```
diff -u --strip-trailing-cr fxprev.c fx2aa.c >v2aa.diff
```

```
--- fxprev.c	2023-03-31 20:52:28.077794500 +0100
+++ fx2aa.c	2023-03-31 20:57:49.966729600 +0100
@@ -2918,23 +2918,23 @@
       ret = (fxFltType) GetBlobSize (pfx->image);
       break;
     case aKurtosis:
-      if ((cs != (ChannelStatistics *) NULL) && (channel > 0))
+      if ((cs != (ChannelStatistics *) NULL) && (channel >= 0))
         ret = cs[channel].kurtosis;
       break;
     case aMaxima:
-      if ((cs != (ChannelStatistics *) NULL) && (channel > 0))
+      if ((cs != (ChannelStatistics *) NULL) && (channel >= 0))
         ret = cs[channel].maxima;
       break;
     case aMean:
-      if ((cs != (ChannelStatistics *) NULL) && (channel > 0))
+      if ((cs != (ChannelStatistics *) NULL) && (channel >= 0))
         ret = cs[channel].mean;
       break;
     case aMedian:
-      if ((cs != (ChannelStatistics *) NULL) && (channel > 0))
+      if ((cs != (ChannelStatistics *) NULL) && (channel >= 0))
         ret = cs[channel].median;
       break;
     case aMinima:
-      if ((cs != (ChannelStatistics *) NULL) && (channel > 0))
+      if ((cs != (ChannelStatistics *) NULL) && (channel >= 0))
         ret = cs[channel].minima;
       break;
     case aPage:
@@ -2976,11 +2976,11 @@
       ret = pfx->Images[ImgNum]->resolution.y;
       break;
     case aSkewness:
-      if ((cs != (ChannelStatistics *) NULL) && (channel > 0))
+      if ((cs != (ChannelStatistics *) NULL) && (channel >= 0))
         ret = cs[channel].skewness;
       break;
     case aStdDev:
-      if ((cs != (ChannelStatistics *) NULL) && (channel > 0))
+      if ((cs != (ChannelStatistics *) NULL) && (channel >= 0))
         ret = cs[channel].standard_deviation;
       break;
     case aH:
```

**Comment by fmw42** [comment]
Thanks for looking into it. The index issue makes sense as the issue and fix.

**Comment by urban-warrior** [comment]
We applied @snibgo's patch to the latest main repo.
