### ISSUE TITLE
rsvg-convert delegate doesn't respect -density

### ISSUE THREAD

**Issue by dnschneid** [ImageMagick/ImageMagick#6214]
### ImageMagick version

main

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04

### Description

When using SVGs as source material, it's common to use `-density` to improve the rendering quality of the SVG.

If you have Inkscape installed, `--export-dpi` is passed to ImageMagick and everything is great.

However, if you have rsvg-convert installed and not Inkscape, rsvg-convert is called without the `--dpi-x` and `--dpi-y` parameters for DPI, and you are stuck with the default 96 dpi.

ImageMagick should emit the `--dpi-x` and `--dpi-y` parameters when `-density` is provided and rsvg-convert is the chosen delegate for SVG import.

### Steps to Reproduce

1. Configure your system such that the Inkscape delegate is used
2. Convert any SVG `convert -verbose -density 300 input.svg output.png`
3. Observe that inkscape was used and the dimensions of output.png are reasonable
4. Reconfigure your system such that the rsvg-convert delegate is used
5. Same command: `convert -verbose -density 300 input.svg output.png` 
6. Observe that rsvg-convert was used, but dpi is not provided and the dimensions of output.png are smaller than before

**Comment by dlemstra** [comment]
When you configure `rsvg-convert` yourself you can add `--dpi-x %x --dpi-y %y ` to pass these arguments. We have also updated our built-in delegates and applied this change.
