### ISSUE TITLE
Letters are cut at the top when generating label with Joseph Sophia font

### ISSUE THREAD

**Issue by NickMihaiu91** [ImageMagick/ImageMagick#6221]
### ImageMagick version

7.1.1-6

### Operating system

MacOS

### Operating system, version and so on

macOS Monterey 12.6.3

### Description

When trying to create an image containing a text using the font Joseph Sophia(https://www.dafont.com/josephsophia.font) the top part of the letters gets cut.

### Steps to Reproduce

example command:
`convert -size 3600x550 -background transparent -gravity center -fill "black" -font josephsophia.ttf "label: Karyna" out-Karyna-1.png`

please see images to see how the resulting image looks like

### Images

![out-Karyna-1](https://user-images.githubusercontent.com/5738598/229590684-ae7dbd18-74f6-42d7-a430-b084aaab0673.png)
![out-rn-2023](https://user-images.githubusercontent.com/5738598/229590713-a0966d1c-5898-4470-be11-6e14fb7e4180.png)

**Comment by fmw42** [comment]
I downloaded the same font from a different site and get similar results on IM 7.1.1.6 Mac OSX Monterey.

On IM 7, use magick, not convert.

`magick -size 3600x550 -background transparent -gravity center -fill "black" -font /Users/fred/library/fonts/josephsophia.ttf "label: Karyna" out-Karyna-1.png`

![out-Karyna-1](https://user-images.githubusercontent.com/13458218/230457386-84221aae-66f2-436f-921d-d872636c8480.png)

**Comment by NickMihaiu91** [comment]
@fmw42 so you think there is something wrong with the font? It's not a bug in image magick? Thank you

**Comment by urban-warrior** [comment]
Its a design flaw.  We're working on an improved algorithm.

**Comment by NickMihaiu91** [comment]
> Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

That's awesome, thank you so much :)
