### ISSUE TITLE
convert to STDOUT does work for PNG

### ISSUE THREAD

**Issue by bittorf** [ImageMagick/ImageMagick#6225]
### ImageMagick version

7.1.1.-6

### Operating system

Linux

### Operating system, version and so on

Debian 12

### Description

writing a file to STDOUT using convert seems not working for PNG,
but it works for JFIF.

### Steps to Reproduce

writing a file to STDOUT using convert seems not working for PNG

```
$ magick convert out.gif png:- | wc -c
0

$ magick -list format | grep PNG
     APNG  VIDEO     rw+   Animated Portable Network Graphics
      JNG* PNG       rw-   JPEG Network Graphics
      MNG* PNG       rw+   Multiple-image Network Graphics (libpng 1.6.39)
      PNG* PNG       rw-   Portable Network Graphics (libpng 1.6.39)
           See http://www.libpng.org/ for details about the PNG format.
    PNG00* PNG       rw-   PNG inheriting bit-depth, color-type from original, if possible
    PNG24* PNG       rw-   opaque or binary transparent 24-bit RGB
    PNG32* PNG       rw-   opaque or transparent 32-bit RGBA
    PNG48* PNG       rw-   opaque or binary transparent 48-bit RGB
    PNG64* PNG       rw-   opaque or transparent 64-bit RGBA
     PNG8* PNG       rw-   8-bit indexed with optional binary transparency
```

but it works for JFIF, the reason is not clear:

```
$ magick convert out.gif jpg:- | wc -c
26513

$ magick convert out.gif jpg:- | magick display -
OK

$ magick -list format | grep JFIF
      JPE* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.1.5)
     JPEG* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.1.5)
      JPG* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.1.5)
      JPS* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.1.5)
    PJPEG* JPEG      rw-   Joint Photographic Experts Group JFIF format (libjpeg-turbo 2.1.5)
```

**Comment by fmw42** [comment]
Works fine for me IM 7.1.1.5. 

```
magick lena.png PNG:- | wc -c
  118261
```

Perhaps it has to do with your converting a GIF to a PNG:-

**Comment by snibgo** [comment]
> $ magick convert out.gif png:- | wc -c
0

Perhaps there is something strange about your input file. I suggest you link to it.

For example, we get that result when the input doesn't exist:
```
C:\web\im>%IMG7%magick none.gif PNG:- | wc -c
magick: unable to open image 'none.gif': No such file or directory @ error/blob.c/OpenBlob/3569.
0
```

**Comment by bittorf** [comment]
Indeed! And the real magic is, that the format specifier MUST be uppercase:

```
$ magick convert out.gif PNG:- | wc -c
21881
```

**Comment by snibgo** [comment]
The format specifier can be uppercase or lowercase (eg `PNG:` or `png:`).

**Comment by bittorf** [comment]
It seems, that is not true in the PNG case, see above.  
Can you point to documentation or or code describing this?  
If so, i should maybe reopen labeling as "bug".

**Comment by bittorf** [comment]
I tried to reproduce that (i wanted to upload my example gif-image) but i can not?  
It is also working with a lowercase "pseudo filename" `png:-` 

```
 magick convert out.gif jpg:- | wc -c
26513

$ magick convert out.gif png:- | wc -c
21881
```

It is just working, and it *is* the image in question.  
It's still the same shell, so i rule out ENV vars issues or alike?!

For now: nevermind, the issue araised during scripting,  
If it happens again, i will report it here.  
Sorry for the noise and thanks for your work!

**Comment by fmw42** [comment]
First, do not use magick convert. In Imagemagick 7, use just magick. For other tools such as mogrify, identify, etc do preface them with magick. Just not convert. Magick replace convert.

Second, upload your image. You can zip it first and then upload, if direct upload fails.
