### ISSUE TITLE
Image Magic is not resizing the checkimage having Compression  CCITT T.6

### ISSUE THREAD

**Issue by ankitmogha** [ImageMagick/ImageMagick#6239]
### ImageMagick version

7.1.0.30

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

We are trying to resize (reduce the size )of checkimage which is tiff format and having compression as CCITT T.6.
The image is not getting resize. I have attached the images.
we are using the following command to replicate this issue
magick.exe" "dummy.tif" -sample 862x403 testdummy.tif
Resulting image is in fact increased by 10 times 

Here is the information for magick
magick.exe" --version
Version: ImageMagick 7.1.0-30 Q16-HDRI x64 8e8a7ceba:20220416 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2017 (191627041)[](url)

**The older version  7.0.10-3 was able to compress the same. File name is :dummy2.tif.**
 magick.exe" --version
Version: ImageMagick 7.0.10-3 Q16 x64 2021-06-21 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 191627030
Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib

There is changeset in version 7.0.10.32 where there is a change in  file **ImageMagick-7.0.10-32\ImageMagick\coders\tiff.c** which actually causing this problem.

### Steps to Reproduce

use the the below command to replicate the same.
magick.exe" "dummy.tif" -sample 862x403 testdummy.tif

### Images

[files.zip](https://github.com/ImageMagick/ImageMagick/files/11176585/files.zip)

**Comment by fmw42** [comment]
When saving to TIF, imagemagick always uses no compression in the output unless you specify what compression you want in your command line.

**Comment by dlemstra** [comment]
And your input file uses `group4` compression so you will need to add this ` -compress group4`.
