### ISSUE TITLE
Memory-Leak in libMagickCore-6.Q16.so.5

### ISSUE THREAD

**Issue by k0keoyo** [ImageMagick/ImageMagick#624]
Memory Leak File Link : https://github.com/k0keoyo/im_poc/blob/master/Memory-Leak-27_output_braille_1501166004.7

Trigger Command : ./convert Memory-Leak-27_output_braille_1501166004.7 output.png

Leak Detail :
root@ubuntu:/home/sh1/ImageMagick/ImageMagick/utilities# ./convert Memory-Leak-27_output_braille_1501166004.7  output.png

=================================================================
==5550==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 50376 byte(s) in 3 object(s) allocated from:
    #0 0x4bc322  (/home/sh1/ImageMagick/ImageMagick/utilities/.libs/lt-convert+0x4bc322)
    #1 0x7f48c4349720  (/home/sh1/ImageMagick/ImageMagick/magick/.libs/libMagickCore-6.Q16.so.5+0x471720)
    #2 0x7f48c4215ed0  (/home/sh1/ImageMagick/ImageMagick/magick/.libs/libMagickCore-6.Q16.so.5+0x33ded0)
    #3 0x7f48c42180ac  (/home/sh1/ImageMagick/ImageMagick/magick/.libs/libMagickCore-6.Q16.so.5+0x3400ac)
    #4 0x7f48c3a4023d  (/home/sh1/ImageMagick/ImageMagick/wand/.libs/libMagickWand-6.Q16.so.5+0x13123d)
    #5 0x7f48c3b50a13  (/home/sh1/ImageMagick/ImageMagick/wand/.libs/libMagickWand-6.Q16.so.5+0x241a13)

Direct leak of 456 byte(s) in 3 object(s) allocated from:
    #0 0x4bc322  (/home/sh1/ImageMagick/ImageMagick/utilities/.libs/lt-convert+0x4bc322)
    #1 0x7f48c43e485a  (/home/sh1/ImageMagick/ImageMagick/magick/.libs/libMagickCore-6.Q16.so.5+0x50c85a)
    #2 0x7f48c4215ed0  (/home/sh1/ImageMagick/ImageMagick/magick/.libs/libMagickCore-6.Q16.so.5+0x33ded0)
    #3 0x7f48c42180ac  (/home/sh1/ImageMagick/ImageMagick/magick/.libs/libMagickCore-6.Q16.so.5+0x3400ac)
    #4 0x7f48c3a4023d  (/home/sh1/ImageMagick/ImageMagick/wand/.libs/libMagickWand-6.Q16.so.5+0x13123d)
    #5 0x7f48c3b50a13  (/home/sh1/ImageMagick/ImageMagick/wand/.libs/libMagickWand-6.Q16.so.5+0x241a13)

**Comment by dlemstra** [comment]
Can you specify the version of ImageMagick that you used to produce this issue? And can you reproduce the issue with the latest version using our git repository?

**Comment by k0keoyo** [comment]
I install ImageMagick by command: git clone --depth=50 --branch=ImageMagick-6 https://github.com/ImageMagick/ImageMagick.git ImageMagick/ImageMagick

**Comment by k0keoyo** [comment]
Version: ImageMagick 6.9.9-4 Q16 x86_64

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by bastien-roucaries** [comment]
Cold you open a CVE ? https://cveform.mitre.org/

**Comment by k0keoyo** [comment]
Of course yes
