### ISSUE TITLE
'invalid colormap index' error occurring on opening many animated gifs

### ISSUE THREAD

**Issue by cyburgee** [ImageMagick/ImageMagick#625]
This is largely a copy of my issue here: https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=32407

Not certain if this is bug or not, but after upgrading to imagemagick version 7, attempting to read or resize many animated gifs result in an 'invalid colormap index' error. This is also happening when trying to open animated gifs with Magick::readImages when using Magick++. This happens on both Mac OS X and Ubuntu 14.04. If this is in fact correct and intended behavior, I would appreciate it greatly if somebody could indicate to me what in particular is wrong with the gif below.

Here's a sample file: https://www.dropbox.com/s/wlz7hdkbz430y44/test.gif?dl=0

The following works as expected when compiled with v6 of the Magick libs
```cpp
#include <iostream>
#include <Magick++.h>

using namespace std;
using namespace Magick;

int main() {
    vector<Magick::Image> gif;
    try {
        readImages(&gif, "test.gif");
    } catch (Magick::Exception &error) {
        std::cout << error.what() << std::endl;
        return 1;
    }

    cout << "Read gif successfully. It has " << gif.size() << " frames." << endl;
    return 0;
}
```
The following  is printed and the return code is 0:
```bash
Read gif successfully. It has 4 frames.
```

However when compiled with v7 it prints the following and returns 1:
```bash
Magick: invalid colormap index `/Users/collin/Downloads/test.gif' @ error/colormap-private.h/ConstrainColormapIndex/34
```

**Comment by mikayla-grace** [comment]
Do not cross post.  The IM developers already answered your question here: https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=32407.
