### ISSUE TITLE
CLI commands crashing with an "abort" when trying to work with large images

### ISSUE THREAD

**Issue by brettboylen** [ImageMagick/ImageMagick#6254]
### ImageMagick version

7.1.1-6 Q16-HDRI x64_64

### Operating system

MacOS

### Operating system, version and so on

MacOS 13.0.1 (22A400) - M1 Pro

### Description

```
Version: ImageMagick 7.1.1-6 Q16-HDRI x86_64 21020 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(5.0)
Delegates (built-in): bzlib fontconfig freetype gslib heic jng jp2 jpeg jxl lcms lqr ltdl lzma openexr png ps raw tiff webp xml zlib
Compiler: gcc (4.2)
```

When trying to work with large images, `magick` or `convert` simply instantly crashes with an `abort`.   I will provide some examples below.

### Steps to Reproduce

I have a source image that is 10800x10800 pixels at 72 DPI.

Trying to run the following or any similar commands instantly crashes:

`magick convert temp.png -crop 10800x7200 -gravity center temp2.png`

All that is shown is: 

`[1]    52851 abort      magick convert temp.png -crop 10800x7200 -gravity center temp2.png`

After doing some Googling around, I found a few people saying this has something to do with the policy file only allowing up to a certain size, but I tried modifying my policy file with no luck.  In fact, it looks like the width and height max settings were actually commented out already in the file.

**Comment by fmw42** [comment]
Are you actually trying to do a tile crop or just a simple crop. 10800x7200 is huge. Do you have enough RAM for the input and output to be in RAM at at the same time?

Try adding +repage before the output.  If a simple crop put +X+Y where X and Y are the offsets of the top left corner appended to the WxH part of the crop.   Also put the -gravity center before the -crop.

Also in Im 7 use magick not magick convert.Other tools (identify, mogrify etc) need the magick preface to the tool, but not convert.

 magick temp.png -gravity center -crop 10800x7200 +repage temp2.png

You may need to change your policy.xml to use disk if you do not have enough RAM.

**Comment by urban-warrior** [comment]
Refer to https://imagemagick.org/script/architecture.php#tera-pixel for converting large images.
