### ISSUE TITLE
Confusing Documentation About Size

### ISSUE THREAD

**Issue by flywire** [ImageMagick/ImageMagick#6256]
### ImageMagick version

7.1.0-62

### Operating system

Other (enter below)

### Operating system, version and so on

website

### Bug Description

The term size is used in conflicting ways and users are not directed to the different usages.
See from https://github.com/ImageMagick/ImageMagick/discussions/6245#discussioncomment-5620695 for specific comments.

### Steps to Reproduce

As above.

**Comment by urban-warrior** [comment]
Find the web page repo @ https://github.com/ImageMagick/Website (IMv7) and https://github.com/ImageMagick/Website6 (IMv6).  Usage pages are @ https://github.com/ImageMagick/Usage.  Post a pull request for your changes against one or more of these repos to correct the documentation.
