### ISSUE TITLE
Convert frame [n] from YCbCr 4:2:0 to png fails with "Aborted"

### ISSUE THREAD

**Issue by figgis** [ImageMagick/ImageMagick#626]
When converting a specific frame in a YCbCr 4:2:0 file to png the convert command aborts

```
$ convert -size 1920x1072 -depth 8 'Cykeltunnel_1920x1072_10.yuv[1300]' x.png
convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `No such file or directory' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322.
.
.
.
.
.
.
.
Aborted
```

...and when running with `-colorspace sRGB`
```
$ convert -size 1920x1072 -depth 8 'Cykeltunnel_1920x1072_10.yuv[1300]' -colorspace sRGB x.png
convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `No such file or directory' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322convert: unable to extend pixel cache `Success' @ fatal/cache.c/CacheSignalHandler/3322.
.
.
.
.
.
.
.
*** Error in `convert': double free or corruption (!prev): 0x0000000001b78f30 ***
Aborted

```

For smaller numbers (i tried e.g. n=500) of n, the conversion succeeds.
The conversion is however painfully slow. Instead of doing a `fseek` to the correct position, Imagemagick seems to cache every single frame up until n. Looking at the memory usage and cpu usage during the convert operation hints at this. 

Huge YCbCr 4:2:0 test sequences can be downloaded from https://media.xiph.org/video/derf/

Or you can create a "empty" test sequence corresponding to my own using perl:
```
perl -e 'print "\x80" x 4374789120' > Cykeltunnel_1920x1072_10.yuv
```
$ convert -version
Version: ImageMagick 7.0.6-4 Q16 x86_64 2017-07-28 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): fontconfig freetype jbig jng jpeg lzma openexr pangocairo png tiff x xml zlib

Actually using commit: 4b9eeffe5b159ab5de3b3e1487c5e8bca8d0db39

**Comment by mikayla-grace** [comment]
You likely ran out of free disk space in your temporary disk partition due to the size of this image sequence.  See https://www.imagemagick.org/script/architecture.php#tera-pixel.

**Comment by figgis** [comment]
Probably. But the thing is that although my YCbCr 4:2:0 sequence is 4.1G. The actual frame is only:

```python
In [7]: 1920*1072*3/2
Out[7]: 3087360
```
bytes. Which is minuscule. Nothing needs to be cashed, just a `fseek` and then read the above number of bytes from file and convert that buffer to a png.
Then again, I have never figured out the internal architecture of Imagemagick so perhaps this breaks the flow of how things are handled...  One day I'll go through the source code :-)

I have wrapped "convert frame n to a png" in a shell-script that first used `dd` to extract the frame and then I run `convert` on that file instead and it's almost instantaneous. It would however be really nice if convert could do this on it's own.

```bash
dd if=Cykeltunnel_1920x1072_10.yuv bs=3087360 count=1 skip=1300 of=/tmp/out.yuv;
convert -size 1920x1072 -depth 8 -colorspace sRGB /tmp/out.yuv x.png
```
