### ISSUE TITLE
negative or zero image size

### ISSUE THREAD

**Issue by nomeata** [ImageMagick/ImageMagick#6287]
### ImageMagick version

7.1.1-7

### Operating system

Linux

### Operating system, version and so on

nixos unstable

### Description

The following steps lead to a 
```
convert: negative or zero image size `test.pnm' @ error/resize.c/ResizeImage/3743.
```
error, despite
```
$ identify test.pnm
test.pnm PBM 1125x100 1125x100+0+0 1-bit Bilevel Gray 14112B 0.000u 0:00.000
```

### Steps to Reproduce

In an empty directory, run:
```
convert +matte -depth 1 -border 2x2 -bordercolor black -family 'DejaVu Sans' -pointsize 12 -density 300 label:"The quick brown fox" 1.pnm
convert +matte -depth 1 -border 2x2 -bordercolor black -family 'DejaVu Sans' -pointsize 12 -density 300 label:'The slower lazy dog' 2.pnm
convert -size 100x100 xc:black black.pnm
convert 1.pnm black.pnm 2.pnm +append test.pnm
convert test.pnm -depth 1 -resize 1x1 txt:-

```

This is a test case of the gscan2pdf program, where upgrading imagemagick made the test suite fail: https://sourceforge.net/p/gscan2pdf/bugs/418/

**Comment by snibgo** [comment]
Your commands work fine for me, with IM v6.9.9-11 and (after prefixing each command with `magick`) v7.1.0-62.

But:

You use IM v7, so I suggest using `magick` so it uses v7 syntax, not `convert` or `magick convert` which both use the old v6 syntax.

`test.pnm` is about 1000x100 pixels. You ask for "`-resize 1x1`", which means you want to retain the same aspect ratio of 10:1 but fitting inside a box that is size 1x1. The result would be 1x0.1 pixels, which may be the problem you are hitting.

I suppose you want the output to be exactly 1x1 pixel. If so, then use a `!` suffix: "`-resize 1x1!`".

**Comment by nomeata** [comment]
I don't really know what these commands are supposed to be doing, they come out of a test suite of another program, which started to fail after upgrading imagemagick. Maybe they are auto-generated?

It seems the behavior has changed, so I wonder if that's a regression that could be fixed, or if it only worked by accident before.

**Comment by dlemstra** [comment]
Can you reproduce this issue with the latest version @nomeata? We had a bug with parsing image dimensions and I suspect your issue is resolved with the latest release.

**Comment by nomeata** [comment]
Seems to work, great!
