### ISSUE TITLE
Wrong precision of the Gamma value when converting

### ISSUE THREAD

**Issue by edhelas** [ImageMagick/ImageMagick#630]
ImageMagick doesn't keep the precision of the original Gamma value when converting some PNG files.
This causes some slight color changes for some pictures.

To reproduce.
```
$ wget https://nl.movim.eu/app/widgets/Stickers/stickers/miho/34a406c2212522d7e6b60e888665267b16fc37ba.png -O sticker.png
$ convert sticker.png sticker_out.png
$ identify -verbose sticker.png > sticker.txt
$ identify -verbose sticker_out.png > sticker_out.txt
$ diff sticker.txt sticker_out.txt 
1c1
< Image: sticker.png
---
> Image: sticker_out.png
317c317
<   Gamma: 0.454545
---
>   Gamma: 0.45455
336,337c336,340
<     date:create: 2017-07-29T18:37:35+02:00
<     date:modify: 2017-07-25T18:50:39+02:00
---
>     date:create: 2017-07-29T19:10:12+02:00
>     date:modify: 2017-07-29T19:10:12+02:00
>     png:bKGD: chunk was found (see Background color, above)
>     png:cHRM: chunk was found (see Chromaticity, above)
>     png:gAMA: gamma=0.45454544 (See Gamma, above)
345a349,350
>     png:text: 2 tEXt/zTXt/iTXt chunks were found
>     png:tIME: 2017-07-25T18:50:39Z
```

**Comment by glennrp** [comment]
Not a bug.

$ pngcheck -v *.png
File: sticker.png (34655 bytes)
  chunk IHDR at offset 0x0000c, length 13
    400 x 400 image, 8-bit palette, non-interlaced
  chunk PLTE at offset 0x00025, length 762: 254 palette entries
  chunk tRNS at offset 0x0032b, length 62: 62 transparency entries
  chunk IDAT at offset 0x00375, length 33750
    zlib: deflated, 32K window, maximum compression
  chunk IEND at offset 0x08757, length 0
No errors detected in sticker.png (5 chunks, 78.3% compression).

File: sticker_out.png (37157 bytes)
  chunk IHDR at offset 0x0000c, length 13
    400 x 400 image, 8-bit palette, non-interlaced
  chunk gAMA at offset 0x00025, length 4: 0.45455
  chunk cHRM at offset 0x00035, length 32
    White x = 0.3127 y = 0.329,  Red x = 0.64 y = 0.33
    Green x = 0.3 y = 0.6,  Blue x = 0.15 y = 0.06
  chunk PLTE at offset 0x00061, length 762: 254 palette entries
  chunk tRNS at offset 0x00367, length 62: 62 transparency entries
  chunk bKGD at offset 0x003b1, length 1
    index = 118
  chunk tIME at offset 0x003be, length 7: 29 Jul 2017 14:10:33 UTC
  chunk IDAT at offset 0x003d1, length 32768
    zlib: deflated, 32K window, maximum compression
  chunk IDAT at offset 0x083dd, length 3282
  chunk tEXt at offset 0x090bb, length 37, keyword: date:create
  chunk tEXt at offset 0x090ec, length 37, keyword: date:modify
  chunk IEND at offset 0x0911d, length 0
No errors detected in sticker_out.png (12 chunks, 76.8% compression).
$

The original PNG has no colorspace information.  The reported gamma is just the default gamma
assumed by ImageMagick for untagged files.  The output file has a gAMA chunk with the precision allowed by the gAMA chunk format.

**Comment by edhelas** [comment]
Oh, sorry and thanks for the quick answer. I'll fix those images on my side.
Thanks for the quick feedback!

**Comment by glennrp** [comment]
If you see a difference between the two images you are probably
dreaming.  The maximum difference in intensity for any sample is about
.001  on a scale of 0 to 256, as demonstated here:

#include <stdio.h>
#include <math.h>
int main()
{
   int i;
   double g45455, g454545;

   for (i=0;i<256;i++)
   {
      g45455=255.*pow((double)i/255.,1.0/.45455);
      g454545=255.*pow((double)i/255.,1.0/.454545);
      printf("%5i: g45455=%g, g454545=%g, difference=%g\n",
      i,g45455,g454545,g45455-g454545);
   }
}
studio> a.out
    0: g45455=0, g454545=0, difference=0
    1: g45455=0.00129481, g454545=0.00129463, difference=1.73618e-07
    2: g45455=0.00594928, g454545=0.00594858, difference=6.97948e-07
    3: g45455=0.0145165, g454545=0.0145149, difference=1.5606e-06
    4: g45455=0.0273353, g454545=0.0273325, difference=2.74841e-06
    5: g45455=0.0446605, g454545=0.0446562, difference=4.24921e-06
    6: g45455=0.0666992, g454545=0.0666931, difference=6.05182e-06
    7: g45455=0.0936272, g454545=0.093619, difference=8.14584e-06
    8: g45455=0.125598, g454545=0.125588, difference=1.05216e-05
    9: g45455=0.162749, g454545=0.162735, difference=1.31699e-05
   10: g45455=0.205203, g454545=0.205186, difference=1.60822e-05
   11: g45455=0.253073, g454545=0.253054, difference=1.92502e-05
   12: g45455=0.306464, g454545=0.306442, difference=2.26662e-05
   13: g45455=0.365473, g454545=0.365447, difference=2.63227e-05
   14: g45455=0.430191, g454545=0.430161, difference=3.02124e-05
   15: g45455=0.500702, g454545=0.500668, difference=3.43286e-05
   16: g45455=0.577088, g454545=0.57705, difference=3.86644e-05
   17: g45455=0.659425, g454545=0.659382, difference=4.32135e-05
   18: g45455=0.747785, g454545=0.747737, difference=4.79696e-05
   19: g45455=0.842237, g454545=0.842184, difference=5.29267e-05
   20: g45455=0.942849, g454545=0.942791, difference=5.80789e-05
   21: g45455=1.04968, g454545=1.04962, difference=6.34205e-05
   22: g45455=1.1628, g454545=1.16273, difference=6.8946e-05
   23: g45455=1.28226, g454545=1.28219, difference=7.46498e-05
   24: g45455=1.40812, g454545=1.40804, difference=8.05268e-05
   25: g45455=1.54043, g454545=1.54034, difference=8.65717e-05
   26: g45455=1.67925, g454545=1.67916, difference=9.27795e-05
   27: g45455=1.82462, g454545=1.82453, difference=9.91453e-05
   28: g45455=1.97661, g454545=1.9765, difference=0.000105664
   29: g45455=2.13525, g454545=2.13513, difference=0.000112331
   30: g45455=2.30059, g454545=2.30047, difference=0.000119142
   31: g45455=2.47268, g454545=2.47255, difference=0.000126093
   32: g45455=2.65156, g454545=2.65143, difference=0.000133177
   33: g45455=2.83728, g454545=2.83714, difference=0.000140393
   34: g45455=3.02987, g454545=3.02973, difference=0.000147734
   35: g45455=3.22939, g454545=3.22923, difference=0.000155197
   36: g45455=3.43586, g454545=3.4357, difference=0.000162777
   37: g45455=3.64934, g454545=3.64917, difference=0.000170471
   38: g45455=3.86985, g454545=3.86967, difference=0.000178274
   39: g45455=4.09743, g454545=4.09725, difference=0.000186183
   40: g45455=4.33213, g454545=4.33194, difference=0.000194193
   41: g45455=4.57397, g454545=4.57377, difference=0.000202301
   42: g45455=4.823, g454545=4.82279, difference=0.000210503
   43: g45455=5.07925, g454545=5.07903, difference=0.000218795
   44: g45455=5.34275, g454545=5.34252, difference=0.000227173
   45: g45455=5.61353, g454545=5.61329, difference=0.000235634
   46: g45455=5.89163, g454545=5.89138, difference=0.000244174
   47: g45455=6.17708, g454545=6.17683, difference=0.00025279
   48: g45455=6.46991, g454545=6.46965, difference=0.000261477
   49: g45455=6.77016, g454545=6.76989, difference=0.000270233
   50: g45455=7.07785, g454545=7.07757, difference=0.000279055
   51: g45455=7.39301, g454545=7.39273, difference=0.000287938
   52: g45455=7.71568, g454545=7.71539, difference=0.000296879
   53: g45455=8.04588, g454545=8.04558, difference=0.000305876
   54: g45455=8.38365, g454545=8.38333, difference=0.000314924
   55: g45455=8.729, g454545=8.72867, difference=0.000324021
   56: g45455=9.08197, g454545=9.08163, difference=0.000333163
   57: g45455=9.44258, g454545=9.44224, difference=0.000342348
   58: g45455=9.81087, g454545=9.81052, difference=0.000351571
   59: g45455=10.1869, g454545=10.1865, difference=0.000360831
   60: g45455=10.5706, g454545=10.5702, difference=0.000370123
   61: g45455=10.962, g454545=10.9617, difference=0.000379445
   62: g45455=11.3613, g454545=11.3609, difference=0.000388795
   63: g45455=11.7683, g454545=11.7679, difference=0.000398167
   64: g45455=12.1832, g454545=12.1828, difference=0.000407561
   65: g45455=12.6059, g454545=12.6055, difference=0.000416973
   66: g45455=13.0365, g454545=13.0361, difference=0.0004264
   67: g45455=13.475, g454545=13.4746, difference=0.000435838
   68: g45455=13.9214, g454545=13.921, difference=0.000445287
   69: g45455=14.3758, g454545=14.3754, difference=0.000454742
   70: g45455=14.8382, g454545=14.8377, difference=0.0004642
   71: g45455=15.3085, g454545=15.308, difference=0.00047366
   72: g45455=15.7868, g454545=15.7864, difference=0.000483117
   73: g45455=16.2732, g454545=16.2727, difference=0.00049257
   74: g45455=16.7677, g454545=16.7672, difference=0.000502016
   75: g45455=17.2702, g454545=17.2697, difference=0.000511452
   76: g45455=17.7809, g454545=17.7804, difference=0.000520876
   77: g45455=18.2997, g454545=18.2991, difference=0.000530284
   78: g45455=18.8266, g454545=18.826, difference=0.000539674
   79: g45455=19.3617, g454545=19.3611, difference=0.000549044
   80: g45455=19.9049, g454545=19.9044, difference=0.000558391
   81: g45455=20.4564, g454545=20.4559, difference=0.000567712
   82: g45455=21.0161, g454545=21.0156, difference=0.000577006
   83: g45455=21.5841, g454545=21.5835, difference=0.000586268
   84: g45455=22.1604, g454545=22.1598, difference=0.000595498
   85: g45455=22.7449, g454545=22.7443, difference=0.000604692
   86: g45455=23.3377, g454545=23.3371, difference=0.000613848
   87: g45455=23.9389, g454545=23.9383, difference=0.000622963
   88: g45455=24.5484, g454545=24.5478, difference=0.000632035
   89: g45455=25.1663, g454545=25.1657, difference=0.000641062
   90: g45455=25.7926, g454545=25.792, difference=0.000650042
   91: g45455=26.4273, g454545=26.4266, difference=0.000658971
   92: g45455=27.0704, g454545=27.0697, difference=0.000667848
   93: g45455=27.722, g454545=27.7213, difference=0.00067667
   94: g45455=28.382, g454545=28.3813, difference=0.000685434
   95: g45455=29.0505, g454545=29.0498, difference=0.000694139
   96: g45455=29.7275, g454545=29.7268, difference=0.000702783
   97: g45455=30.413, g454545=30.4123, difference=0.000711362
   98: g45455=31.107, g454545=31.1063, difference=0.000719875
   99: g45455=31.8096, g454545=31.8089, difference=0.000728319
  100: g45455=32.5208, g454545=32.52, difference=0.000736693
  101: g45455=33.2405, g454545=33.2398, difference=0.000744993
  102: g45455=33.9689, g454545=33.9681, difference=0.000753218
  103: g45455=34.7058, g454545=34.7051, difference=0.000761366
  104: g45455=35.4514, g454545=35.4507, difference=0.000769434
  105: g45455=36.2057, g454545=36.2049, difference=0.00077742
  106: g45455=36.9686, g454545=36.9678, difference=0.000785322
  107: g45455=37.7402, g454545=37.7394, difference=0.000793137
  108: g45455=38.5205, g454545=38.5197, difference=0.000800865
  109: g45455=39.3096, g454545=39.3088, difference=0.000808502
  110: g45455=40.1073, g454545=40.1065, difference=0.000816046
  111: g45455=40.9138, g454545=40.913, difference=0.000823496
  112: g45455=41.7291, g454545=41.7283, difference=0.000830849
  113: g45455=42.5532, g454545=42.5524, difference=0.000838103
  114: g45455=43.3861, g454545=43.3852, difference=0.000845256
  115: g45455=44.2277, g454545=44.2269, difference=0.000852306
  116: g45455=45.0782, g454545=45.0774, difference=0.000859252
  117: g45455=45.9376, g454545=45.9367, difference=0.00086609
  118: g45455=46.8058, g454545=46.8049, difference=0.000872819
  119: g45455=47.6829, g454545=47.682, difference=0.000879437
  120: g45455=48.5688, g454545=48.568, difference=0.000885942
  121: g45455=49.4637, g454545=49.4628, difference=0.000892331
  122: g45455=50.3675, g454545=50.3666, difference=0.000898604
  123: g45455=51.2802, g454545=51.2793, difference=0.000904758
  124: g45455=52.2019, g454545=52.201, difference=0.00091079
  125: g45455=53.1325, g454545=53.1316, difference=0.0009167
  126: g45455=54.0722, g454545=54.0712, difference=0.000922485
  127: g45455=55.0208, g454545=55.0198, difference=0.000928143
  128: g45455=55.9784, g454545=55.9774, difference=0.000933672
  129: g45455=56.945, g454545=56.9441, difference=0.000939071
  130: g45455=57.9207, g454545=57.9197, difference=0.000944337
  131: g45455=58.9054, g454545=58.9044, difference=0.000949468
  132: g45455=59.8992, g454545=59.8982, difference=0.000954463
  133: g45455=60.902, g454545=60.901, difference=0.00095932
  134: g45455=61.9139, g454545=61.913, difference=0.000964037
  135: g45455=62.935, g454545=62.934, difference=0.000968612
  136: g45455=63.9651, g454545=63.9642, difference=0.000973043
  137: g45455=65.0044, g454545=65.0035, difference=0.000977328
  138: g45455=66.0529, g454545=66.0519, difference=0.000981466
  139: g45455=67.1104, g454545=67.1095, difference=0.000985454
  140: g45455=68.1772, g454545=68.1762, difference=0.000989292
  141: g45455=69.2531, g454545=69.2522, difference=0.000992976
  142: g45455=70.3383, g454545=70.3373, difference=0.000996506
  143: g45455=71.4326, g454545=71.4316, difference=0.000999879
  144: g45455=72.5362, g454545=72.5352, difference=0.00100309
  145: g45455=73.649, g454545=73.648, difference=0.00100615
  146: g45455=74.771, g454545=74.77, difference=0.00100904
  147: g45455=75.9023, g454545=75.9013, difference=0.00101177
  148: g45455=77.0429, g454545=77.0419, difference=0.00101433
  149: g45455=78.1928, g454545=78.1918, difference=0.00101673
  150: g45455=79.352, g454545=79.3509, difference=0.00101896
  151: g45455=80.5204, g454545=80.5194, difference=0.00102102
  152: g45455=81.6982, g454545=81.6972, difference=0.0010229
  153: g45455=82.8854, g454545=82.8843, difference=0.00102461
  154: g45455=84.0818, g454545=84.0808, difference=0.00102615
  155: g45455=85.2877, g454545=85.2866, difference=0.0010275
  156: g45455=86.5029, g454545=86.5019, difference=0.00102868
  157: g45455=87.7275, g454545=87.7265, difference=0.00102968
  158: g45455=88.9615, g454545=88.9604, difference=0.00103049
  159: g45455=90.2049, g454545=90.2038, difference=0.00103113
  160: g45455=91.4577, g454545=91.4567, difference=0.00103157
  161: g45455=92.7199, g454545=92.7189, difference=0.00103183
  162: g45455=93.9916, g454545=93.9906, difference=0.0010319
  163: g45455=95.2728, g454545=95.2717, difference=0.00103177
  164: g45455=96.5634, g454545=96.5624, difference=0.00103146
  165: g45455=97.8635, g454545=97.8624, difference=0.00103095
  166: g45455=99.1731, g454545=99.172, difference=0.00103024
  167: g45455=100.492, g454545=100.491, difference=0.00102934
  168: g45455=101.821, g454545=101.82, difference=0.00102824
  169: g45455=103.159, g454545=103.158, difference=0.00102693
  170: g45455=104.506, g454545=104.505, difference=0.00102543
  171: g45455=105.864, g454545=105.863, difference=0.00102372
  172: g45455=107.23, g454545=107.229, difference=0.00102181
  173: g45455=108.607, g454545=108.606, difference=0.00101969
  174: g45455=109.993, g454545=109.992, difference=0.00101736
  175: g45455=111.388, g454545=111.387, difference=0.00101482
  176: g45455=112.793, g454545=112.792, difference=0.00101207
  177: g45455=114.208, g454545=114.207, difference=0.0010091
  178: g45455=115.632, g454545=115.631, difference=0.00100592
  179: g45455=117.066, g454545=117.065, difference=0.00100252
  180: g45455=118.51, g454545=118.509, difference=0.000998909
  181: g45455=119.963, g454545=119.962, difference=0.000995075
  182: g45455=121.426, g454545=121.425, difference=0.00099102
  183: g45455=122.899, g454545=122.898, difference=0.000986743
  184: g45455=124.381, g454545=124.38, difference=0.000982241
  185: g45455=125.873, g454545=125.872, difference=0.000977513
  186: g45455=127.375, g454545=127.374, difference=0.000972558
  187: g45455=128.886, g454545=128.885, difference=0.000967375
  188: g45455=130.407, g454545=130.406, difference=0.000961961
  189: g45455=131.938, g454545=131.937, difference=0.000956316
  190: g45455=133.479, g454545=133.478, difference=0.000950437
  191: g45455=135.029, g454545=135.028, difference=0.000944324
  192: g45455=136.589, g454545=136.589, difference=0.000937974
  193: g45455=138.159, g454545=138.158, difference=0.000931387
  194: g45455=139.739, g454545=139.738, difference=0.00092456
  195: g45455=141.329, g454545=141.328, difference=0.000917493
  196: g45455=142.928, g454545=142.927, difference=0.000910184
  197: g45455=144.537, g454545=144.536, difference=0.000902631
  198: g45455=146.156, g454545=146.155, difference=0.000894834
  199: g45455=147.785, g454545=147.784, difference=0.000886789
  200: g45455=149.424, g454545=149.423, difference=0.000878497
  201: g45455=151.072, g454545=151.072, difference=0.000869956
  202: g45455=152.731, g454545=152.73, difference=0.000861163
  203: g45455=154.399, g454545=154.398, difference=0.000852118
  204: g45455=156.077, g454545=156.077, difference=0.00084282
  205: g45455=157.766, g454545=157.765, difference=0.000833267
  206: g45455=159.464, g454545=159.463, difference=0.000823457
  207: g45455=161.172, g454545=161.171, difference=0.000813389
  208: g45455=162.889, g454545=162.889, difference=0.000803061
  209: g45455=164.617, g454545=164.617, difference=0.000792473
  210: g45455=166.355, g454545=166.354, difference=0.000781623
  211: g45455=168.103, g454545=168.102, difference=0.000770509
  212: g45455=169.861, g454545=169.86, difference=0.00075913
  213: g45455=171.628, g454545=171.627, difference=0.000747485
  214: g45455=173.406, g454545=173.405, difference=0.000735572
  215: g45455=175.194, g454545=175.193, difference=0.00072339
  216: g45455=176.991, g454545=176.99, difference=0.000710937
  217: g45455=178.799, g454545=178.798, difference=0.000698213
  218: g45455=180.617, g454545=180.616, difference=0.000685215
  219: g45455=182.444, g454545=182.444, difference=0.000671943
  220: g45455=184.282, g454545=184.281, difference=0.000658394
  221: g45455=186.13, g454545=186.129, difference=0.000644568
  222: g45455=187.988, g454545=187.987, difference=0.000630464
  223: g45455=189.856, g454545=189.855, difference=0.000616079
  224: g45455=191.734, g454545=191.733, difference=0.000601413
  225: g45455=193.622, g454545=193.621, difference=0.000586465
  226: g45455=195.52, g454545=195.52, difference=0.000571232
  227: g45455=197.428, g454545=197.428, difference=0.000555713
  228: g45455=199.347, g454545=199.346, difference=0.000539908
  229: g45455=201.275, g454545=201.275, difference=0.000523815
  230: g45455=203.214, g454545=203.214, difference=0.000507432
  231: g45455=205.163, g454545=205.163, difference=0.000490759
  232: g45455=207.122, g454545=207.122, difference=0.000473794
  233: g45455=209.091, g454545=209.091, difference=0.000456535
  234: g45455=211.07, g454545=211.07, difference=0.000438981
  235: g45455=213.06, g454545=213.06, difference=0.000421132
  236: g45455=215.06, g454545=215.059, difference=0.000402985
  237: g45455=217.07, g454545=217.069, difference=0.00038454
  238: g45455=219.09, g454545=219.089, difference=0.000365794
  239: g45455=221.12, g454545=221.12, difference=0.000346748
  240: g45455=223.16, g454545=223.16, difference=0.000327399
  241: g45455=225.211, g454545=225.211, difference=0.000307746
  242: g45455=227.272, g454545=227.272, difference=0.000287788
  243: g45455=229.343, g454545=229.343, difference=0.000267524
  244: g45455=231.425, g454545=231.425, difference=0.000246953
  245: g45455=233.516, g454545=233.516, difference=0.000226072
  246: g45455=235.618, g454545=235.618, difference=0.000204881
  247: g45455=237.731, g454545=237.731, difference=0.000183379
  248: g45455=239.853, g454545=239.853, difference=0.000161564
  249: g45455=241.986, g454545=241.986, difference=0.000139435
  250: g45455=244.129, g454545=244.129, difference=0.000116991
  251: g45455=246.283, g454545=246.283, difference=9.4231e-05
  252: g45455=248.447, g454545=248.447, difference=7.11529e-05
  253: g45455=250.621, g454545=250.621, difference=4.77559e-05
  254: g45455=252.805, g454545=252.805, difference=2.40387e-05
  255: g45455=255, g454545=255, difference=0

**Comment by glennrp** [comment]
I ran the trial over again with 16-bit precision, and the maximum difference
was about .26 out of 65535; i.e., indistinguishable even at 16-bit precision.
