### ISSUE TITLE
TIFF default byte-order set to big-endian on little-endian aarch64 Linux

### ISSUE THREAD

**Issue by gsauthof** [ImageMagick/ImageMagick#6300]
### ImageMagick version

7.1.1

### Operating system

Linux

### Operating system, version and so on

Fedora 38, aarch64

### Description

ImageMagick 7 sets the default TIFF endianness  to big-endian (MSB) on Fedora 38 Linux aarch64, although aarch64 is a little-endian architecture.

This is caused by ImageMagick 7 using libtiff's idea of a native **bit-order**:

https://github.com/ImageMagick/ImageMagick/blob/3a1ce456f0b02d456078906897b20265a3111ab5/coders/tiff.c#L3368

NB: The concept of a native bit-order is questionable and as of now libtiff simply has the opinion that x86/x86_64 are the only architectures that have a 'native' LSB2MSB fillorder/bit-order ([see also](https://gitlab.com/libtiff/libtiff/-/issues/558)).

However, this has nothing to do with the native **byte-order**.

FWIW, nowadays most architectures are little-endian, and most bi-endian architectures are nowadays initialized to little-endian and most operating systems.

This is a regression to ImageMagick 6 where the byte-order was pushed to libtiff (unless explicitly specified):

```
  switch (endian_type)                                                                     
  {                                                                                        
    case LSBEndian: mode="wl"; break;                                                      
    case MSBEndian: mode="wb"; break;                                                      
    default: mode="w"; break;                                                              
  } 
```

See also: Fedora bug about this issue: https://bugzilla.redhat.com/show_bug.cgi?id=2195906

### Steps to Reproduce

`convert`  some png image to tiff and check its endianness with some like:

```
/usr/bin/convert out.tiff json: | grep endian
```

Expected output:

On aarch64 Linux (e.g. Fedora 38) the endianness should read LSB.

Actual output:

On aarch64 Linux (e.g. Fedora 38) the endianness reads MSB.

**Comment by fmw42** [comment]
See -endian at https://imagemagick.org/script/command-line-options.php#endian to set it however you want.

**Comment by gsauthof** [comment]
Yeah, there is also `-define tiff:endian` one could use as a work-around.

However, the point of this issue is that ImageMagick 7 should set the TIFF byte-order to the native host byte-order, by default.

**Comment by dlemstra** [comment]
This should be reported to the maintainers of the `libtiff` library? The value of `HOST_FILLORDER` should be corrected there? And maybe you can even tell `libtiff` which byte order should be used when building the library.

**Comment by gsauthof** [comment]
Well, `HOST_FILLORDER` simply isn't the right tool for determining the **byte**-order of a system.
`HOST_FILLORDER` is about the **bit**-order that is supposedly native to the system.

However, the bit-order of a byte usually is completely transparent to a program, on modern architectures.
It looks like it's simply a curious design decision of the TIFF format to allow this flexibility of reversing the bits in a byte.

It might have marginally simplified the construction of some FAX machines (cf. e.g. Section 2.2.2 of https://www.ietf.org/rfc/rfc2301.txt).

Note that libtiff itself only every uses `HOST_FILLORDER`  when a file is opened with `H` mode:

https://gitlab.com/libtiff/libtiff/-/blob/7e28cd362b9b7ca984b685562ee945dacdc2c50e/libtiff/tif_open.c#L369

Also note, the fill order of TIFF files created with ImageMagick 7 on aarch64 has the common `msb-to-lsb` value, as on x86_64 (check e.g. with `tiffinfo`), although they are written in big-endian byte-order.
This is caused by ImageMagick 7 not adding any of H/L/B to the `TIFFClientOpen()` mode.

I think the simplest fix for ImageMagick 7 is to only ever add l/b characters the `TIFFClientOpen()` mode when the user has supplied the `-define tiff:endian=...` or `-endian ...` option.
I mean similar to what the ImageMagick 6 code is doing there.
That way libtiff defaults to the true host byte-order like this:

https://gitlab.com/libtiff/libtiff/-/blob/7e28cd362b9b7ca984b685562ee945dacdc2c50e/libtiff/tif_open.c#L425

---

Btw, in contrast to ImageMagick 6, the resulting tiff isn't compressed by default (e.g. when using `/usr/bin/convert normal.png -depth 32 -define quantum:format=floating-point out.tiff`) - is this a deliberate change?

---

FWIW, I _did_ open a related issue with libtiff regarding their fillorder 'detection':
https://gitlab.com/libtiff/libtiff/-/issues/558

**Comment by dlemstra** [comment]
I have been reading the TIFF issue and decided we will default to writing in LSB unless the user specifies otherwise.

And to answer your other question.. This is by design. We no longer "inherit" the compression from the input image, you will need to specify the compression.
