### ISSUE TITLE
Delegates not getting installed on RHEL

### ISSUE THREAD

**Issue by skalokhe** [ImageMagick/ImageMagick#6308]
### ImageMagick version

7.1.0.62

### Operating system

Linux

### Operating system, version and so on

RHEL8.3 , till RHEL 8.7

### Description

convert --version
Version: ImageMagick 7.1.0-62 Q16-HDRI x86_64 20885 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5)
Delegates (built-in): lzma zlib
Compiler: gcc (8.5)

All the delegates are not installed we are facing lots of issues with this

### Steps to Reproduce

Followed :

## Pre-req dependencies
sudo yum groupinstall "Development Tools" -y
yum -y install bzip2-devel freetype-devel libjpeg-devel libpng-devel libtiff-devel giflib-devel zlib-devel ghostscript-devel djvulibre-devel libwmf-devel jasper-devel libtool-ltdl-devel libX11-devel libXext-devel libXt-devel lcms-devel libxml2-devel librsvg2-devel OpenEXR-devel php-devel
## download imagemagic :
wget https://imagemagick.org/archive/releases/ImageMagick-7.1.0-62.tar.gz

## extact the tar ###
tar -xvf ImageMagick-7.1.0-62.tar.gz

cd ImageMagick-7.1.0-62
./configure --prefix=/usr
make
##If build fails, try gmake instead.
sudo make install
export LD_LIBRARY_PATH=/usr/lib
sudo ldconfig
ldconfig /usr/lib

#sudo ldconfig /usr/local/lib
#ls -l /usr/local/bin/magick
#cd ~
#echo "export PATH=$PATH:/usr/local/bin" >>.bashrc
#export PATH=$PATH:/usr/local/bin
convert --version

### Images

Error Executing ImageMagick command 'convert'
![imagemagick1](https://user-images.githubusercontent.com/31537012/236759937-18413f96-191e-406c-80f7-379c9711bdea.png)

**Comment by dlemstra** [comment]
Please don't create both a discussion and an issue about the same thing.
