### ISSUE TITLE
getting Tiff error on converting the issue 

### ISSUE THREAD

**Issue by reykhan786** [ImageMagick/ImageMagick#6310]
### ImageMagick version

13.1.0

### Operating system

Windows

### Operating system, version and so on

11

### Description

Getting tiff directory error for few base64 byte . for most of the files it working 

using (MagickImage imagemagick = new MagickImage(filepath))
            {
                imagemagick.Format = MagickFormat.Png;
                imagemagick.Write(outputpath);
            }

### Steps to Reproduce

Attched the code above

**Comment by snibgo** [comment]
Please supply everything needed to reproduce the problem: a complete but minimal program, and input image files.

**Comment by reykhan786** [comment]
> Please supply everything needed to reproduce the problem: a complete but minimal program, and input image files.
Below is the base 64 
 base64 = base64.Replace("\n", string.Empty).Replace(@"\", string.Empty);
            byte[] base64Bytes = Convert.FromBase64String(base64);
            string currentPathImages = Path.GetTempPath();
            string outputpath = currentPathImages + @"\Images" + "\\" + "output" + ".png";
            string filepath = currentPathImages + @"\Images" + "\\" + "base" + "." + mimeType;
            File.WriteAllBytes(filepath, base64Bytes);

            // Save images
            if (!Directory.Exists(Path.Combine(currentPathImages, "Images")))
            {
                Directory.CreateDirectory(Path.Combine(currentPathImages, "Images"));
            }

            using (MagickImage imagemagick = new MagickImage(filepath))
            {
                imagemagick.Format = MagickFormat.Png;
                imagemagick.Write(outputpath);
            }


SUkqAJYXAABkAAAAAQAAAGQAAAABAAAAgD/gUDgkFg0HhEJhULhkNhTgh0RiUTikVgUQi0ZjUbh0\nYjkfkEcj0hkkljsmlEphDgfwDT8qmEolgAmk1movmM5isjQE2n0/mhJAM6okXhr6DlApVKDqBP9FjMjj\nbopdVoAHqEGqVFTz/YFWn4/nNbrMMflgAFYkFkssUr9omp/ftihlstsfs9wqt3vj+GFWvmBh+CwlawuH\no2Iwt2xVQxmNomPyFjyeByWVlWXzEyzdtzWdkmf0Fr0eO0tF0WnjWp1UW1mtimv2ES2Wzk+2lMYZ+4ks\nYQ7ngrHfsMQ+8g++YcFYb4g/AgfMgr4p+23zH5T548F6d0fwP3HVY7imgfYLxg7mD8GfFqf4ngbf1sYY\nbDAM1B7heLh58KfwA6bsIEX6BwAgyXsQjC3gABgAA+/BgoGe6Fumgpfum8yDwMggALohMCN6gS3gOfgB\nD+dJ4Eehx/OmfyCB8gZyIQ7yCnAtR+AGg54IGuh+IHFiCQyuqBJ6AJBxGf58gy5KCmBHsewmgkCGag5/\nHegToH+fz9H+fC0oMYiBxkfEdye9LbkAMAYnCfjvHQDqtmNMp+LVHyDDOgZOoOfrdn/HKBH5HiBE+rZG\nIGnE+TjMssRkhqMEAP0LoGD7hoVAE6IIfz4IFDkoIGekfUBQMVIKXyBzsf5wTiJ6Bn5PdGIEZh/gCAJn\nLUD5uRTKdM1Egx4RkZh+KfScAoOPyBO6i84udI9M1cgZBkGY8ZF/JkjoOfaB2Egh+0yfA9ubPZOVFbMB\nIKfweWNMtUIEfsIoEfdmSChR5oFLSC2vdaB3uf89SsACDmfPYeHcp8PU3Pz/H+fkynHMr1wheCFs1JV7\nWxfKCOcedIR+gY/GdgiCSegR84VhMDHPAx8UWc+IMGhrrIq5xz3agofvgfx+E8p99IQedJ34f5j3JK5/\nkDIGIopch/5nfR5rUfd5n+b+ZyddZ/A/nWQIMc9JnzPZn3IeUOEBRd4olDaBHhG5/30cEJwBpKCVAeZ/\nB+p+oIFkJ/mfSZ9ucb66Hm7gf7VZuzTKeD2IHVuE7ziqBOA6ZwX9LEMQBvtAume8DWBuGjpjg1OIFVqW\n1Wg5fwAeeoK6gR7z25nQIS2qS2Yfg78dml7nnAFqH+c7nOx2CVqLKqKWygl9UmcaBnf5R/3nxvhM3naI\nnfjXoOz6SKnfobaOMk3Ze97HwtJ8fyfKkXzo/8H01P9iN/X9JwICAIA/4FA4JBYNB4RCYVC4ZDYU4IdE\nYlE4pFYFEItGY1G4dGI5H5BHI9IZJJY7JpRKYRI5VLZNLJdMY/MJlNYtNJtOYjOJ1PYfPqBJ6DQ4TPKJ\nLXPP6POnHSqXNqbRX3T5s4adVJjVqLWJq9KvXJU9q/YJQ5ofU7JKnMf6laZU57ZK7RbpNcLbdIy4A/B3\nOP7veIm+UA4DEF4M91/f8BEXoAMcAGPBcRisXDHe4MeAAHBXmn4HcYG4LnlYY/Mc/3xjr3A87An9foJo\ntJDmQALY/scAYI82/rtXodHs4Q/kAD9xmQfrN6/39v4vweFB0A/2AYM08NPAt5ruTseh0YI/gG/H+8AG\noA5jtg++W/DfBdl4IO/r1kUAP2BjgwB4E+eWfx3vg775H+AB+A+fgBtSxwHumf58me1yku9AiDH6QZ4N\nQD5AC+fgOACcC/HzAJ/n5CbgQqgp9P4fZgBgB6kgfAzknxCMSxO58UoIfAPD+fYBwcf5wmAD5BxLEh+H\nnAUdIGeA8w0/hvke6oBqsfkkHvJcmH+QKmkwIi9m+Z5jAwAB8D/K6BH5LMKS2AbenAYLlmeY4GAIHgPn\n8M81SVNsmAevxhgO5YHmOYYBke409xLPsURtCp/A8gRHg+3pgUKeMumPPU+SWZ7EoHM7hHwHLmAwH9LA\neZ58HAOKrBvTsKGPUCBVE2Z4SyfA4OYB5hkeRwPDgHg8H/WESzZFBhl4HwGH5HzQMqcMAngMbUAOY5nk\nQH4OA+Hg/2NNclkmXD0jwH54WgxZht6YZDvKY9sOmRgHk8H7DWPJZtl2ZhzDmT58OjGxjg+B54nOc5nt\n0YQDnOD5LwlJZul+BhzjuT8MuERyBAcPgDnmYZzmOADygGeZnkniEKE4HGKBAD8QtmfwOoEDh8M2Ad4A\nwP58ACfJz5Q5kSRQTwcEad+XHc5yPqSP6tJKfgdxKHJoHGfg55CDk0DBJOgQBJZPBmZpz1gd+lItE9Nj\nO3STHwO7UDGYZ5nweJ3meHofnwGB/DyYbXCfJZPhiBpz39huloGbZ/5htlpnOQ5yHwcOEB4vwID+Xm+u\nZpTZG+HACneHAfnA7qNxObZ/EClL/SER5jmAPCMB+zxGB+b3MubLR/TUP+MI5E5sn90iSnmxJhg+cZAB\nw7ofm4P5iA+dyotfLSUqi6gAL9HCQL6f5DD+eIPh82Afm6f5xASe4RtddL4+q0O1s8kpjj+fwGPKH62H\nIBwfwieIBj7SMP8Xj7EBkgesPk1xsCSDOIEzNM4PzcD/AOM8b48V3OZEBAQlpVi/DxVqShmY/FSj8D83\ngvwNB3jvHy30qIg4NEqHCgcf7a3MklL2PAOaJQ+D/gCD4F49x+DDH8n0R8LyUjhHwN8Hh/B/vCJAP4tg\n8E9j+BgPx8cKR/BhH+n0X8GlGklHAPgbgAD+LOJMPxtw8EIj+ACrYH47EAgxH/B56aSxgLIJIOQPAwFL\nxzJQiZB5ywDjBIGL8dxbAYHlAerZCgzG3EmHMHg8Zfl3NsGeE8eInCBAPkqP8T5zR6CIH+NAABulaI5E\n+aCPBGxzA/O7HUkp/hDijW9J434nxvuuNtKQ5Mp3FFTE+HcQY8R4vWI4OZVUHyUDxE+od0KJTQS4HmIA\nAjogXkCl8bIQ48wAmDDCD1dsxwPo2hqSUcYvx4jGD4XtgBAzPGpmqOQ2Avx8jANgbIYI8wYicHcHMHox\nzNkbHoB9EjZoDA/H2AaCUfiBDwAeL+ESIZ5EDHiIA1ZsocB7E4P4O4PBnJPI2PcR6AYzEoLg/WHg/4ag\nDEGxcHal3Fi/HCJ8R6OR/AyDyL4cAdwejebWRoe6NoPEpe8P8DI/5CU1RK/wD4+ANnFGROwB4xaaEXIC\nAIA+3+vxke084DuPG8AX/DYdD4hEYc92PDYrEoxGYwhIaGX+4H+H4a+D+zjyQAWAAOnAe/3gB2evx/DX\nBAk+Nj2vmcd143pnGqBDnPDZFQaNEkY/34M3++B9P3i/2ceHwA2DK2e/3mw2cfj/NIEhhuM51CW8e6PQ\nHnSj+97Tb3+jX+9qY/A9X3+43+AB4/AG6UOPqy83m2H9Dpq/2AdwGvmAM0A3xHcIk96jUbXlKNHnoZ4q\nHIc434AAY/HimQMfqHWmC/MRAqig1+4BigX+B81EHm+X/F9zQY84DPuFxDmO8CABDgAA4AH8Z4a571r4\ndaN/EcO+36/5b16AG6UzwO795FkIwgAYAAeAA/zn0YhiYaA+9Dh+f9dAn5ePrEn8ph4GYH5jsyf7xGMY\nAjnAOBAK0hqsoe+Tbv6f5PD+fw/k2psKIwfwbnebBOD+Q7Vn+ZgPkMdAnn4PQgH+WaWke+KBQfChPH8D\nw/AWvMOIkfgznOfMRGG3xkCcA5sAefgfPaXCWk+/iPxpHpOH8DgcCGf8ZR6iB+Dee5YxEccIMUfAznQB\n5/AAEKmtwHEZy4uJ+A4AJxn8n84obLx5jiHg/nGT6HGAeBznwkQAPabAAn8+kIwLDhmn4YL6HxPKHn4d\n5wHnP1AOMQcgpEZ4AB+aAIH87rqS4Zh+mHGTp0sppnkGcY+B+cc8FCB5zn6kRnAAD5wDwiUJQ4Yh9kOi\n1YJGZwHnGPwPm/PAYA/IKZnYCBPnA1yI00/sonIfbug/R84ngR51nMP4DkMn5/BgP8goaeFsHFbb4syo\nZfs1DCHnMHCZv3Mk8ngT55mMP4AAcvB8ABP4IoaQBMGQdw+WHGkCTwt87oeceGn+8tlYJgzFA8hx4AAD\nwxsmvxMAQe1hW4zJnnnjK042hp9nm20eWUlwfnuZilXsYAHgCUa0H2QZIEeew82GtZhkOcIRqitLtn8o\nqtQLLdlHiH57aCpSHEAB5gmO6x5kAD57ute5/kDqQAmAt9K6whzdvtnp/nCma5H+7Z/zUH54AK6Z8kBn\n735if4OZmDOwqO11ToaH+8LZvW+H4Rpg4+hs1QuBroD+fJEB8PcosQpgeZmHsLLS/Z/Cfyh523que74f\nxOmAH+QGghp+tWfpkDifeapo+nVnmHpAdQjT9n/2R/8qw5/xLZW+H6DJgABKaHD5ZG/kR7njI/BoeG/5\nXmdemboH/gqHYFWG+HwDM1cUf5YQuP5Lz0ZAAB7X0twcAP3kuteaRluz7RPjhby3qAb2R/jyfuHBwI+i\nfj8e3ABYY8AHiJdYI6A6HSRBjMOtlPTeiGq3H8R5BxDR6jhH8PgF7nhgADHzAE+IMyrDfHiD1ubNiWhz\nQwI8pLnYULOBUeCFo4B3jxH689wIgA7kDWGIMYBbh8j9gYW8I4/h5p3AEUVcisBhh/HxEotw/xjBniyP\n0b7ngAB+CCL8P472MjgHiPBrJlARj8N4D8MBP34qwGEfiNBDRvx1j9AFNQfBmx0fiOAeAfFUGUBDH4f4\nHg4kOUDCiQo/AJnSNWN8dgDAOAYF6IYD4xgEA8GajKSI8wPkMNyDgfilS7wNb0MIPwOgNjDHCasYI7BG\nAIAQL0RgDwBAIAYAUQYYBnggP4poY6DTcicBya5hTnoUENl4DsHZxzVjgDCMEZoyBeiZGeBAAABBkiLD\nME8MU0x5jxGBCEoIngAj8H8i4hrIG9RlG2LsR4/DVj8DAO0dwDReiYAeDgAARBmgZD8E8E89B8DwfIUY\nT4gx/B+JAQ2MchELgzEeP41YnwQjtHQFkTtDj2AgGSB4MATwXzTHuP4HklS3lZQwgV6zPZCj/pM9Uhon\nw2jNHSNmdI7z2BgGaB8I1Np6D/E4bgzSEGMyDkIH4CIO1AxTMUGwQIyREiZE6M8HYAASDdAwE6qhiD3j\nHUaZSrRD43zdjKPgHdBX2jgoWMwBgwROAfEGAABAzRJBMriTQtbaTckXk7N0h8hR8g7GfQZnA/BnjvIc\nH9UQABuiHDEE8N9VRwBALwPOfBESLjLsoRCMo8Jwj8jSUpGUOB/DADGP2yajjRggMmVqjZEjp1Bsorcb\nQOxwABtu3Yh9uwDj9hwhEe4+AHLTpFa0iCr7YscB+DgHZL7bkSB+MEL91GnqGAwAdGQE3qFGi3d+8DxF\nDXlOw5y9TMaNVXXWAMHFOyjO2voQ1rweUND/e6REfhth93VMQPccIPAAAGDmIwcYMwcU8IxgTAuB4lUj\nIfg7CFjhxg8ACAAeYnB5h3EzcgiSlcCkOHiL8HI3WcEaD6KPBRGBwEUB6BEQAAxeqbAzjAiOMsZj/HiJ\n8TuOB/NtOwP0EQf8HrDHuI8D4mRgATyKHDI5Rl7YzyaP3KCNK8kQH6AAX+V1uZZE+BgYAcxeDzDni/JZ\nbx4DfH4N0fo7ZOEYAGI8gWacIgfEcBgIAYxeD3DPnjPJR89j9GacLQJER9EwkQQ6vI4B7A/GAc0xoAww\nZh0iUYeFmQGjob+PwdwgRwjDGGPQOg5xzjCPHfjTo9HeCOV+L8C4cBE2e1OUEfATxnjuLcPwfgzhAiBG\nCIEeAMBAiDEEAMQ4BwwjcA0D4HgXyaB2JEI8TEe9ilG2ON8dznh/DEEoBwSIuR5iREyLkGAAwBAnGINg\nDAmAMFFHAJek43xuYc3O846Axt2DEEYBwQgAA4ADAyJ/e4eg5jPG2JkbY25OjgHOMc/azODuvOgEZzwf\ngKiME8MEAIdxJAAEHikHwAhhibG2NkTenR5jjJIOarHIygj8BOb2z4MROCcFwD0e4kwejxxSA4AY4BJj\nbGgBvnQ+Soj35/0B5xTB/l4B/0YbomN5AzByDkBIGgQBhG8NPmw29OluL0POuvXIEFMBWXgX4OxODBGC\nIAeAMwAiDAHWsIIzOcDZEzx0e4vyKj5EH3YoA/jwDr0CP4fpeh4D/DWrIHYhwHjhGwBsbgPOAeNs8Plz\nnkiNEeu8RMufXx/g2JmN+nNvyPj3GeB8fakvWetb+Q6z0b43j29kG4/g+/cY/HOL8YY/KQ+/IkXJwFRh\nvj7jf9UNh/B8M1x+WsBY/r5/SIhEUb9Px/xvF/sSE4/y3XxwiPsf34QwfkIkIYh+Vh/2en4dsP4fo4r9\nzHwe4fqSYf6Cj+wiAY4vAezYj9j4QXLMbN6Pw1wGEBK7or6zwZ7+Bj56gGJmEAbKI10AMC6FJfSNJfhC\nBkAebJTLB6RSoTEErGhfQXaKghpGQcKLIf4bwc5YTQxCIG56TzcGMGTJiN47RQKN5GQYBqr50BDHwW59\nye4bkIpWJnD4gf5ZAQAJIhoHoZwGkGxbkKIb4A4H8KkIpLz4MNQioAgjwkgTg1zHhYYgIIA93+zh+n3Y\nX3/CYVC4ZDYdD4hEYk/ju/39CXy+X+x3+Pjy/3gO0MvH+AYTF4W4Bu/3cf4NCIlMZlM5o/pXAn++4THB\n5H3iBxIHH8gJO/x/CpU/3O/0/LZpT6hNH4B4SH3/OH+/I2/xzH3GhjG2H+jD+761VoTSYEH3Mf6jb7hD\nX4A3+76tOoXSxnGmOwHG/H4nj+834/m/SIE83wP3sb7jj7g/I050fCV/CmfSwPk0Bf3+vj+/a1h7TiXB\nV6PkNVUny4WGh4Th5xS0e+KUMcJnz+Dh4/9I/3BAn2z9Rq+NMcAwGGA39KH+z3xS+hSnhhDvF94f9/wZ\nzxHmL+P4YfgE45jnzn+H38J3+h3wz3K4NzgB+nH/l9K/37CX3qfE/6EsAfhzDy36FFGf5Rn4X5xkYOZ+\nDefJnvqP78OAgT9py/0APE5J3AAjCUj+GLTmEDg4n4L54h+D5eQqjkLv0iw9lvDkAMkRx3AQtxurqPZ/\nnGLgAAYfpwh4fJ/B+05Dh8P5cNS7j9mMHZLxs/7JE8dw9KOdzfIucZ/Awfh9mAHEkB+YbgD8P6TPyfh5\nAOHMqys8K5vKPYPKutyEnGjqtHwHBdpad6i0JNxwk+fJPzpOoDkAMYBvsnSdF3PoHD4fo4ACfZvT2iyG\nO4filn7RdGPCc55leYwfo0fZhjieZ/kAPh/NerNPIa7iUVJU0AHGb5+UIfw51icB+HwA6BD/XFQIFXdS\n168J40IgRfnuWLfH4dQHIEO9mJSrB515aM6v4hJ7nihJ4G+Hz9HPb7EIsfZ6j7aFyNXJMZH6d59m+nR/\nXa3yI10PASB7e17tUqyUHetzmjyXq6wsh1dD2SOD4S47iKwnRvH0OdFm/eCkHgAGTAAHrK4y1c+oU0jD\ngO4hfIkcGS5Pm+ThBkwBQNlaJLwgVDKvhaP4Gk4QDaMGTgFnGm6cRufQCP5/T2ip/notx+qwh7TotrOE\nIWfoaadsmyggFS0PEfyrNA9qLHgqx5uJo2vP1sCaF+NRHAIAAEbLv+TAGQGTAMUynuJoRfn8YKEmfu6U\npOfwn3HUw4FBvwAAhk4A7+CQHog0576EfC0SbmiTngQ5+knqKHF4GXAZwDJgXShJ8LcfDbdOix7nufpN\n9amh9AAB3Y6aCfHuAoo50V4LIGB42cc1k6FHePfm+cuKpnPPpAXSfA/LQfZ/HqThDHwGBAADwcA1R7Hs\nrgYAwn4Fi0GGrSY66rR5nzif4FQH8yYqg/x8g/Za7sfo8wTj7Rq/8uL3QAFUQ26BmzNxZivgcW9/CISZ\nHBD+NgEAH3jErgyQ9GA/05v5KWRonMJCTjDHgOABAlBgvRBK84fyixgsjVyUsvA84XE0DCDB6DOGdN/T\nalYTgAHkq5OEueHi+DRAUFgzpwbgIkqMO4PNxg94oq9HuKAMAfResmaUziAZER3v+fyQIe4wA/j2i+8E\nfgUBUOAEKFAAhUTuDnF8D8p0JSZBNEA0xnDnGbhEdARVd8gI5yCJkO8GoGnBgIERFcAERylsNINJBXo4\nClsiF+MyTyppQD/E8D8X43I2SlPFKcThVkeyuStKcHwIB/jZlpLUgIAOAP4ABAABAAAAAAAAAAABBAAB\nAAAAKwMAAAEBBAABAAAAAgEAABYBBAABAAAARgAAABEBBAAEAAAAQBgAABcBBAAEAAAAUBgAABoBBQAB\nAAAACAAAABsBBQABAAAAEAAAACgBAwABAAAAAgAAABUBAwABAAAAAQAAAAIBAwABAAAAAQAAAAMBAwAB\nAAAABQAAAAYBAwABAAAAAQAAAAoBAwABAAAAAQAAABgAAACpAwAAIgkAAPESAACRAwAAeQUAAM8JAACl\nBAAA

**Comment by dlemstra** [comment]
And what is the actual error message that you are getting?

**Comment by snibgo** [comment]
What line is failing? What is the IM error message?

You write the bytes to a file. What happen when you read that file with a command line like this:
```
magick yourfile info:
```
Perhaps your base64 string is not a valid image.

**Comment by reykhan786** [comment]
> And what is the actual error message that you are getting?

Error fetching directory link. `TIFFAdvanceDirectory' @ error/tiff.c/TIFFErrors/599 @dlemstra

**Comment by dlemstra** [comment]
Your tiff file seems to be corrupt.
