### ISSUE TITLE
Force grayscale PNG output for paletted input

### ISSUE THREAD

**Issue by q3cpma** [ImageMagick/ImageMagick#6314]
### ImageMagick version

7.1.1-8

### Operating system

Linux

### Operating system, version and so on

Gentoo

### Description

I tried every combination of `-colorspace gray`, `-type gray` and `-define png:color-type=0` (which produces an error) but can't get a grayscale PNG when using the builtin `logo:` as input.

### Steps to Reproduce

```
$ magick convert -colorspace gray -type gray logo: logo.png
$ magick identify logo.png
logo.png PNG 640x480 640x480+0+0 8-bit sRGB 174c 26205B 0.000u 0:00.000
$ magick convert -colorspace gray -type grayscale -define png:color-type=0 logo: logo.png
convert: Cannot write image with defined png:bit-depth or png:color-type. `logo.png' @ warning/png.c/MagickPNGWarningHandler/1526.
```

**Comment by snibgo** [comment]
With version v7.1.0-62:
```
magick logo: -colorspace gray g.png
```
Exiftool shows g.png has only one channel.

**Comment by q3cpma** [comment]
On Tue May 9, 2023 at 9:45 PM CEST, snibgo wrote:
> With version v7.1.0-62:
> ```
> magick logo: -colorspace gray g.png
> ```
> Exiftool shows g.png has only one channel.
>

But what does identify show? Here, same result. And Gimp treats it as paletted
too.

**Comment by snibgo** [comment]
Okay, try:
```
magick logo: -colorspace gray -define png:color-type=2 g.png
```

**Comment by q3cpma** [comment]
On Wed May 10, 2023 at 1:12 AM CEST, snibgo wrote:
> Okay, try:
> ```
> magick logo: -colorspace gray -define png:color-type=2 g.png
> ```
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/ImageMagick/ImageMagick/issues/6314#issuecomment-1541003692
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

Still showing sRGB. And https://www.w3.org/TR/PNG-Chunks.html shows 0 for
grayscale.

**Comment by q3cpma** [comment]
On Wed May 10, 2023 at 4:51 PM CEST, Fred Weinhaus wrote:
> Please clarify why you need that.  If the image is single channel, then it is grayscale.  In what application or purpose do you need it to be as you require and why is snibgo's result not adequate?
>

But is it single channel (which would indeed be grayscale)? `identify -verbose`
shows `Channels: 3.0` here. Anyway, it's a basic problem (if only for
compression) if you want a grayscale (color-type 0) PNG to not be able to get
it.

**Comment by fmw42** [comment]
Convert with make 3 equal channels. But Magick will make only a single channel result when using -colorspace gray.

**Comment by q3cpma** [comment]
On Wed May 10, 2023 at 5:48 PM CEST, Fred Weinhaus wrote:
> Convert with make 3 equal channels. But Magick will make only a single channel result when using -colorspace gray.

Unless I'm mistaken, not here:
```
$ magick logo: -colorspace gray g.png
$ magick identify -verbose g.png | grep -E '(Channels|Colorspace):'
  Colorspace: sRGB
  Channels: 4.0
$ magick logo: -colorspace gray -define png:color-type=2 g.png
$ magick identify -verbose g.png | grep -E '(Channels|Colorspace):'
  Colorspace: sRGB
  Channels: 3.0
```

**Comment by snibgo** [comment]
"`magick identify`" tells you nothing about how the image is stored in the file. Instead, it tells you how it is stored in memory, after IM has read it.

**Comment by q3cpma** [comment]
On Wed May 10, 2023 at 9:37 PM CEST, Fred Weinhaus wrote:
> Python read and then print is telling you want you have after it is read and that depends upon how it is read by python. So you are getting a similar result as to what is happening with Imagemagick. Try using Exiftool to find out what is stored in the file, not what it converted by IM or Python (as user snibgo) has said.
>

I'm sorry, but you are wrong. In this small Python segment, I read the file
purely as a binary blob, not a PNG (as does hexdump which shows the same thing).

And exiftool shows the following:
```
$ magick logo: -colorspace gray g.png
$ exiftool g.png
ExifTool Version Number         : 12.50
File Name                       : g.png
Directory                       : .
File Size                       : 26 kB
File Modification Date/Time     : 2023:05:10 22:00:22+02:00
File Access Date/Time           : 2023:05:10 22:00:22+02:00
File Inode Change Date/Time     : 2023:05:10 22:00:22+02:00
File Permissions                : -rw-r--r--
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 640
Image Height                    : 480
Bit Depth                       : 8
Color Type                      : Palette
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Palette                         : (Binary data 522 bytes, use -b option to extract)
Background Color                : 173
Modify Date                     : 2023:05:10 20:00:22
Warning                         : [minor] Text/EXIF chunk(s) found after PNG IDAT (may be ignored by some readers)
Datecreate                      : 2023-05-10T20:00:22+00:00
Datemodify                      : 2023-05-10T20:00:22+00:00
Datetimestamp                   : 2023-05-10T20:00:22+00:00
Image Size                      : 640x480
Megapixels                      : 0.307
```

so color type palette (3), not grayscale (0).

**Comment by fmw42** [comment]
Post a PNG image that is grayscale and Exiftool identifies it the way you want.

**Comment by fmw42** [comment]
logo: is an internal image format and does not seem to convert respecting the grayscale format.  I am not sure if this is a bug or just the way the internal images work.

But take some other PNG input image and convert it as follows and it does show grayscale.

```
magick lena.png -colorspace gray -type grayscale gg.png

exiftool -s -ee -g1 -u -D gg.png
---- ExifTool ----
    - ExifToolVersion                 : 12.56
    - Warning                         : [minor] Text/EXIF chunk(s) found after PNG IDAT (may be ignored by some readers)
---- System ----
    - FileName                        : gg.png
    - Directory                       : .
    - FileSize                        : 40 kB
    - FileModifyDate                  : 2023:05:10 13:28:33-07:00
    - FileAccessDate                  : 2023:05:10 13:28:35-07:00
    - FileInodeChangeDate             : 2023:05:10 13:28:33-07:00
    - FilePermissions                 : -rw-r--r--
---- File ----
    - FileType                        : PNG
    - FileTypeExtension               : png
    - MIMEType                        : image/png
---- PNG ----
    0 ImageWidth                      : 256
    4 ImageHeight                     : 256
    8 BitDepth                        : 8
    9 ColorType                       : Grayscale
   10 Compression                     : Deflate/Inflate
   11 Filter                          : Adaptive
   12 Interlace                       : Noninterlaced
    - BackgroundColor                 : 255
    - ModifyDate                      : 2023:05:10 20:28:33
    - Datecreate                      : 2023-04-24T17:43:54+00:00
    - Datemodify                      : 2012-07-27T01:42:47+00:00
    - Datetimestamp                   : 2023-05-10T20:28:33+00:00
    - Software                        : GraphicConverter
---- Composite ----
    - ImageSize                       : 256x256
    - Megapixels                      : 0.066

```

**Comment by q3cpma** [comment]
On Wed May 10, 2023 at 10:31 PM CEST, Fred Weinhaus wrote:
> logo: is an internal image format and does not seem to convert respecting the grayscale format.  I am not sure if this is a bug or just the way the internal images work.
>

```
$ magick logo: g.png
$ magick g.png -colorspace gray g2.png
$ magick identify g2.png
g2.png PNG 640x480 640x480+0+0 8-bit sRGB 256c 27434B 0.000u 0:00.000
$ exiftool g2.png | grep 'Color Type'
Color Type                      : Palette
```

Saving logo: to an external file before doing the conversion doesn't fix it.
But I tested on another paletted input and it was correctly converted to
grayscale, so I don't know what's the trigger here.

**Comment by fmw42** [comment]
I think it is the way internal images are handles and the meta data set in the header when converted to grayscale.  I think you get a single channel image with grayscale color palette as output. So it is essentially grayscale but handled as palette with a gray only color table. I am not sure why this is happening other than possibly the internal images are handles differently or were never put through the same rigorous tests as with proper image formats. Each image format is different. Some do not even support grayscale. So I suspect the internal ones are not allowing grayscale on output to be safe with all output formats. This information is then passed to your output PNG.

**Comment by snibgo** [comment]
With IM v7.0.1-62:
```
magick logo: -colorspace gray -define png:color-type=2 g.png

exiftool g.png
Bit Depth                       : 8
Color Type                      : RGB
```
There is one channel (of 8 bits), non-palette, as required. (If there were 3 channels, it would show `Bit Depth: 8 8 8`.)

If you really want color-type=0 then:
```
magick logo: -colorspace gray -depth 16 -define png:color-type=0 g.png

exiftool g.png
Bit Depth                       : 16
Color Type                      : Grayscale
```
I don't know why it doesn't allow 8-bit at color-type=0.

**Comment by q3cpma** [comment]
>I think you get a single channel image with grayscale color palette as output. So it is essentially grayscale but handled as palette with a gray only color table

That's also what I think, hence the issue title.

On Thu May 11, 2023 at 4:11 AM CEST, snibgo wrote:
> With IM v7.0.1-62:
> ```
> magick logo: -colorspace gray -define png:color-type=2 g.png
>
> exiftool g.png
> Bit Depth                       : 8
> Color Type                      : RGB
> ```
> There is one channel (of 8 bits), non-palette, as required. (If there were 3 channels, it would show `Bit Depth: 8 8 8`.)
>
I'd rather call this an Exiftool bug, RGB (including paletted) is by definition
3 channels.

> If you really want color-type=0 then:
> ```
> magick logo: -colorspace gray -depth 16 -define png:color-type=0 g.png
>
> exiftool g.png
> Bit Depth                       : 16
> Color Type                      : Grayscale
> ```
> I don't know why it doesn't allow 8-bit at color-type=0.
>

I see, but I hope I'm not insane in thinking that this is not normal and these
(-color-type=0 not allowed and not automatic when -colorspace gray is used) are
legitimate bugs.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by q3cpma** [comment]
On Sun May 14, 2023 at 3:13 PM CEST, Cristy wrote:
> Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
>

Thanks for the fix!
