### ISSUE TITLE
Imagick extension not working

### ISSUE THREAD

**Issue by ashokmahal** [ImageMagick/ImageMagick#6315]
### ImageMagick version

8.2

### Operating system

Windows

### Operating system, version and so on

windows server 2019

### Description

we have started using ext-imagick-php8.2-nts-x64 for an application called redcap. We have a version upgrade recently and post that we are receiving and error mentioned below.

Imagick extension not working: The Imagick PHP extension, while enabled, gives an error that REDCap doesn't know how to handle. Until this is fixed, rendering of inline PDFs in descriptive fields will not work. The error message returned was:

RegistryKeyLookupFailed `CoderModulesPath' @ error/module.c/GetMagickModulePath/667

### Steps to Reproduce

We are getting following error post upgrade

Imagick extension not working: The Imagick PHP extension, while enabled, gives an error that REDCap doesn't know how to handle. Until this is fixed, rendering of inline PDFs in descriptive fields will not work. The error message returned was:

RegistryKeyLookupFailed `CoderModulesPath' @ error/module.c/GetMagickModulePath/667

**Comment by dlemstra** [comment]
We did not write and we don't maintain imagick. You should ask your question here instead: https://github.com/Imagick/imagick.
