### ISSUE TITLE
Convert Raw to DNG

### ISSUE THREAD

**Issue by kevflynn** [ImageMagick/ImageMagick#6344]
### ImageMagick version

7.1.1-9

### Operating system

MacOS

### Operating system, version and so on

13.3.1 Mac OS Silicon

### Description

I am trying to simply convert a raw file (.ARW file extension) to a dng file (.dng file extension) and it's throwing two warnings and not producing a converted file.

### Steps to Reproduce

run on raw photo .arw

`magick public/test.ARW dng:public/output.dng`

### Images

github doesn't let me upload the raw photo file type for the input

**Comment by snibgo** [comment]
You can see what formats your installation of IM can read and write like this:
```
D:\temp>%IMG7%magick -list format |grep -i dng
      DNG  r--   Digital Negative (0.21.1-Release)
```
So the version I use can read but not write DNG.

The page https://imagemagick.org/script/formats.php shows what formats IM is generally capable of reading and writing. On there, it shows DNG as read-only.

However, a DNG file is really a TIFF file with ".DNG" extension, possibly with a mosaiced image, and possibly with certain metadata. I show how this can be done at [Processing Bayer pixels](http://im.snibgo.com/procbay.htm).

**Comment by kevflynn** [comment]
Ahh - got it. didn't notice the R- for read only. bummer. thanks @snibgo - i need to convert a raw file to dng with lossy for compression. I guess ill checkout dcraw?

**Comment by kmilos** [comment]
I don't think dcraw nor LibRaw's dcraw_emu will output a DNG...

Adobe DNG Converter is pretty much your only option that's known to work for most raw files. There's an open source alternative called [DNGlab](https://github.com/dnglab/dnglab) you might want to check out as well.

Other than that, you have to roll your own e.g. using Python and rawpy + tifffile, or PiDNG etc.

**Comment by kevflynn** [comment]
ty @kmilos - trying to figure out how to get the adobe dng converter running. causing major headaches with little to no documentation.

**Comment by kevflynn** [comment]
@snibgo - any chance you're open to connecting further? Would really love to pick your thoughts on that post you shared. Trying to understand it a bit more. Either way, thanks for the help!
