### ISSUE TITLE
support for raw canon images .cr3 files

### ISSUE THREAD

**Issue by 1michaelbrown** [ImageMagick/ImageMagick#6345]
### ImageMagick version

7.9.11-60

### Operating system

Linux

### Operating system, version and so on

 Ubuntu 22.04.2 LTS

### Description

using the convert command doesn't work on .cr3 which are raw image file from canon cameras. 

### Steps to Reproduce

use the command

`convert`

on a .cr3 file 

for example in a directory with a image called image.CR3 using command 

`convert image.CR3 -thumbnail 200x200 image.png`

I get 

```
convert-im6.q16: delegate failed `'ufraw-batch' --silent --create-id=also --out-type=png --out-depth=16 --output='%u.png' '%i'' @ error/delegate.c/InvokeDelegate/1966.
convert-im6.q16: unable to open image `/tmp/magick-WwWNmNMt0MlHO6ZfHPIV0nT3Py4XboNH.ppm': No such file or directory @ error/blob.c/OpenBlob/2924.
convert-im6.q16: no images defined `image.png' @ error/convert.c/ConvertImageCommand/3229
```

### Images

It says the file size is too large so.... is there another way for me to provide the image?

**Comment by snibgo** [comment]
> ImageMagick version
7.9.11-60

I don't think so. Please paste the text outputs from "convert -version" and "magick -version".

IM can read (at least some) CR3 files, when it has libraw as the delegate.

**Comment by fmw42** [comment]
Did you mean 6.9.11-60?  There is no 7.9.11-60.

**Comment by 1michaelbrown** [comment]
> To the OP: Did you mean 6.9.11-60? There is no 7.9.11-60.

yes ops

**Comment by 1michaelbrown** [comment]
> > ImageMagick version
> > 7.9.11-60
> 
> I don't think so. Please paste the text outputs from "convert -version" and "magick -version".
> 
> IM can read (at least some) CR3 files, when it has libraw as the delegate.

done. I notice on the `magick -version` that it's not installed. So would I just 

sudo apt install magick 

or is magics or magic the same thing just name slight different

**Comment by fmw42** [comment]
If you have 6.9.11-60, then change magick to convert in the commands. That should run. But post the output from 

convert -version

So that we can see if you have libraw installed.

**Comment by 1michaelbrown** [comment]
> If you have 6.9.11-60, then change magick to convert in the commands. That should run. But post the output from
> 
> `convert -version`
> 
> So that we can see if you have libraw installed.

Version: ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org/
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP(4.5)
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff webp wmf x xml zlib

**Comment by 1michaelbrown** [comment]
after running the command `sudo apt install libraw-dev` 

I get 
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libraw-dev is already the newest version (0.20.2-2ubuntu2).
The following package was automatically installed and is no longer required:
  php8.1
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded

```

**Comment by fmw42** [comment]
That was not what I asked.  Please show the results from

`convert -version`

**Comment by 1michaelbrown** [comment]
![Screenshot 2023-05-18 at 11 12 38 PM](https://github.com/ImageMagick/ImageMagick/assets/123066581/e00be83c-da8b-4431-b7bb-c237dfd0ffae)

**Comment by 1michaelbrown** [comment]
> Libraw is **not** installed in Imagemagick. If it were it would show as raw in the list (at least that is how it show on my system)

is `sudo apt install libraw-dev` the wrong command to install libraw?

**Comment by fmw42** [comment]
what do you get as output from 

`convert -list configure`

**Comment by fmw42** [comment]
Where is libraw installed?  What is its path?  Is it in the same location as Imagemagick?

Did you look for the config.log file in the libraw directory to see what error message there might be?  Perhaps libraw needed some other delegate?

**Comment by raleighlittles** [comment]
I'm not sure why this issue was closed if it was never fixed. Even after installing `libraw-dev` I still am seeing the same error when trying to convert a CR3 file:

```
convert-im6.q16: delegate failed `'ufraw-batch' --silent --create-id=also --out-type=png --out-depth=16 --output='%u.png' '%i'' @ error/delegate.c/InvokeDelegate/1966.
convert-im6.q16: unable to open image `/tmp/magick-fQhsRTf-bCDahKLXG-c0Qia9i-T4DU3N.ppm': No such file or directory @ error/blob.c/OpenBlob/2924.
convert-im6.q16: no images defined `r7.jpg' @ error/convert.c/ConvertImageCommand/3229.

```

**Comment by apalazzi** [comment]
+1

I have the same issue on my system, what should I do to either fix the problem or to give some additional info?

```
$ LC_ALL=C sudo apt install libraw-bin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libraw-bin is already the newest version (0.20.2-2ubuntu2.22.04.1).
```

convert -list configure [configure.txt](https://github.com/ImageMagick/ImageMagick/files/13121101/configure.txt)
