### ISSUE TITLE
7.1.1.9 portable Q16 HDRI. VCOMP140.dll missing.

### ISSUE THREAD

**Issue by carsten-riedel** [ImageMagick/ImageMagick#6346]
### ImageMagick version

7.1.1.9 portable Q16 HDRI

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

VCOMP140.dll missing.

I think it is supposed in this portable build that the .exe are launching without dependency's.

### Steps to Reproduce

Refresh install of Windows 10 virtual box for testing, updates done ~ April,May 2023

Downloaded [ImageMagick-7.1.1-9-portable-Q16-HDRI-x64.zip](https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-9-portable-Q16-HDRI-x64.zip) and extracted to local directory.

Launch magick.exe from CMD.

### Images

![image](https://github.com/ImageMagick/ImageMagick/assets/97656046/c0551585-41ab-4319-b6c5-a28340e87456)

**Comment by snibgo** [comment]
The IM download binary for Windows page https://imagemagick.org/script/download.php#windows says:

> If you have any problems, you likely need vcomp120.dll. To install it, download Visual C++ Redistributable Package [ https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads ].

I suppose `vcomp140.dll` is an updated version of this file. Also see Microsoft:

https://www.microsoft.com/en-ca/download/details.aspx?id=48145
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by carsten-riedel** [comment]
@snibgo
Thank you so much for your assistance! It seems that the root cause has indeed been identified. However, I'm wondering if there's a way to distribute it alongside the portable variant or include it in the build process. I was able to make it work by extracting the vc redistributable using the "dark" tool from https://github.com/wixtoolset/wix3/releases/tag/wix3112rtm and placing the DLL file in the extracted "imagemagick" folder.

```
dark.exe -x C:\temp\vc_redist vc_redist.x64.exe
mkdir C:\temp\vcdll
expand -F:* "C:\temp\vc_redist\AttachedContainer\packages\vcRuntimeMinimum_amd64\cab1.cab" C:\temp\vcdll
```

So, it now can run without any installing on the system.

**Comment by snibgo** [comment]
I can see the argument for IM distributing `vcomp140.dll`. But that also creates other problems.

On my Windows 11 laptop, I have two versions of that file, in two locations:
```
 Directory of c:\windows\System32

05/10/2022  23:36           191,824 vcomp140.dll
               1 File(s)        191,824 bytes

 Directory of c:\windows\SysWOW64

08/01/2020  01:05           141,600 vcomp140.dll
               1 File(s)        141,600 bytes
```

That file is built and distributed by Microsoft. When it is installed in a `\Windows` directory, I suppose the Windows update process updates the file as required for bugs, vulnerabilities etc. If IM were to distribute the file, IM would somehow need to ensure that it was distributing the most current version of the file. In addition, if the file is in an `\ImageMagick` directory, it would never be updated by the Windows update process.

I don't know the best solution to the problem.

**Comment by dlemstra** [comment]
I agree with snibgo here and I think we should not include those binaries in the portable zip. But you can decide to do that yourself as you have shown in an earlier post.

**Comment by carsten-riedel** [comment]
Thanks for providing the updated information. Consider the adjustment of the DLL search order to favor system DLLs over those in the current directory. However, be aware that this could potentially add overhead. Statically building applications always carries the risk of incorporating outdated or insecure libraries. (I'm not sure how this currently affects the build, but I normally decide everything or nothing)

**Comment by lfcnassif** [comment]
I just hit this situation with portable Windows distributions 7.1.1-19-q8-x64 and 7.1.1-20-q8-x64: vcomp140.dll missing. The previous imagemagick-7.1.0-16-q8-x64 we used didn't have this dependency and was 100% portable.

So I would like to ask if the recommended solution from now is to embed vcomp140.dll into imagemagick or to install MS Visual Redistributable package? Or imagemagick project intend to statically link that DLL to the portable executables again in the future?

**Comment by lfcnassif** [comment]
I don't know why vcomp140.dll was removed from the static builds (or added as dependency at some point), but if security vulnerabilities were the cause, they can happen with any dependency, not just vcomp140.dll.

**Comment by dlemstra** [comment]
These files have never been part of the portable build and we will not add them. The user will need to install the MS Visual C++ Redistributable package themselves.

**Comment by lfcnassif** [comment]
Fine. Thank you @dlemstra for replying, I appreciate your time. And thanks for this great open source project.

**Comment by axeld** [comment]
This is obviously a newly introduced dependency, and this breaks the portable version. I'm not sure if that has been fully understood. Closing this bug does not make the problem go away, unfortunately. Version 7.1.0-57 did work okay (this was the last version I tested with before updating to the current release). Having a portable version that is not portable, does not seem like a good or even acceptable solution to me.

Maybe this dependency can be removed again, or the portable version can be built without it. 

dlemstra wrote: "These files have never been part of the portable build and we will not add them." -- that completely disregards the fact that this is a new issue that needs a bit more than "we never did that".

**Comment by dlemstra** [comment]
As I said before we will not be going to add this file ourselves and someone has already pointed out a solution to get this file so you can add it yourself.

**Comment by axeld** [comment]
Care to elaborate what component introduced this dependency?

Also, the least you must do in this case is to document this behavior. The website still states "Just copy to your host and run (no installer, no Windows registry entries)", for example, which is obviously untrue now.

**Comment by dlemstra** [comment]
I have no clue what caused this dependency on your system. We will be going to need your help to figure out what has caused this change. And until we have an answer to that question I don't think we need to update our documentation because we already mention that it is possible that you need the C++ redistributable.

**Comment by dlemstra** [comment]
As I said before, we will be going to need your help to figure out what has caused this change. I don't know what has caused this and I don't have the time now to figure that out for you. I might have time for this in the future but there are other things that also need my attention. You can help us by figuring out the cause of this new dependency.

**Comment by axeld** [comment]
Ah okay, I'll see what I can do.

**Comment by sergeevabc** [comment]
[The solution][1].

[1]: https://github.com/abbodi1406/vcredist

**Comment by QiWei** [comment]
Note that Visual C++ does not support static linking of the OpenMP runtime, although static linking is supported in the version for Xbox 360.
[Reap the Benefits of Multithreading without All the Work](https://learn.microsoft.com/en-us/archive/msdn-magazine/2005/october/openmp-and-c-reap-the-benefits-of-multithreading-without-all-the-work)

**Comment by QiWei** [comment]
Enabled OpenMP in the portable build. [`f92ab19`](https://github.com/ImageMagick/ImageMagick/commit/f92ab197cfabe8020c014818736e8bed71435d58)
