### ISSUE TITLE
Build error: incompatible function pointer types passing

### ISSUE THREAD

**Issue by kmilos** [ImageMagick/ImageMagick#6347]
### ImageMagick version

7.1.1-9

### Operating system

Windows

### Operating system, version and so on

Windows Server 2022 10.0.20348 MSYS2 CLANG64

### Description

IM [no longer builds w/ Clang on Windows](https://github.com/msys2/MINGW-packages/actions/runs/5025655926/jobs/9012915030?pr=17176#step:11:1438):
```
  ../ImageMagick-7.1.1-9/MagickCore/distribute-cache.c:1026:48: error: incompatible function pointer types passing 'DWORD (void *) __attribute__((stdcall))' (aka 'unsigned long (void *)') to parameter of type 'void *(*)(void *)' [-Wincompatible-function-pointer-types]
      status=pthread_create(&threads,&attributes,DistributePixelCacheClient,
                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
  D:/M/msys64/clang64/include/pthread.h:305:93: note: passing argument to parameter 'func' here
  int       WINPTHREAD_API pthread_create(pthread_t *th, const pthread_attr_t *attr, void *(* func)(void *), void *arg);
                                                                                              ^
  1 error generated.
```

Last good known version was 7.1.1-6

### Steps to Reproduce

Try to build under MSYS2 CLANG64 (instead of MINGW64/UCRT64 using GCC).

**Comment by Biswa96** [comment]
To project devs, Should `--without-threads` option be added with configure command to disable the pthread_create call and use the native Windows thread APIs?

**Comment by urban-warrior** [comment]
Can you try your MING build again with the latest main repo?

**Comment by Biswa96** [comment]
It seems that the actual issue was not fixed. I get the same compiler error as before with clang.

```
../MagickCore/distribute-cache.c:1026:48: error: incompatible function pointer types passing 'DWORD (void *) __attribute__((stdcall))' (aka 'unsigned long (void *)') to
      parameter of type 'void *(*)(void *)' [-Wincompatible-function-pointer-types]
    status=pthread_create(&threads,&attributes,DistributePixelCacheClient,
                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
C:/msys64/clang64/include/pthread.h:305:93: note: passing argument to parameter 'func' here
int       WINPTHREAD_API pthread_create(pthread_t *th, const pthread_attr_t *attr, void *(* func)(void *), void *arg);
```

Though we could disable pthreads and use Windows native thread APIs. Just asking if that would be a right choice (see my previous comment).

**Comment by urban-warrior** [comment]
We need to set up a proper MINGW environment to debug this issue.  That may take a while given our current workload.  In the mean-time, you can try debugging yourself and post a patch.  It looks like its conditionally compiling as Windows (line 92) but as POSIX at line 1026.  If configuring with `--without-threads` works for you, use this workaround until we can investigate further.

**Comment by Biswa96** [comment]
mingw-w64 provides pthread library as a wrapper upon Windows APIs. So, both `MAGICKCORE_THREAD_SUPPORT` and `MAGICKCORE_WINDOWS_SUPPORT` is true in mingw-w64 environment. As ImageMagick already supports native Windows thread APIs, disabling pthread using `--without-threads` might be better option.

**Comment by kmilos** [comment]
FYI, still seeing this w/ pthreads on 7.1.1-10 building w/ Clang.

**Comment by kmilos** [comment]
FYI, still seeing this w/ pthreads on 7.1.1-11 building w/ Clang, so the linked commit must've addressed something different?
