### ISSUE TITLE
ImageMagick-7.1.1-10-portable-Q16-x64 zip is corrupt, CentOS builds are missing.

### ISSUE THREAD

**Issue by FredThompsonII** [ImageMagick/ImageMagick#6353]
### ImageMagick version

7.1.1-10

### Operating system

Windows

### Operating system, version and so on

All Win x64

### Description

ImageMagick-7.1.1-10-portable-Q16-x64 zip is corrupt. Filenames >= montage cannot be extracted. Please update that file.

### Steps to Reproduce

well...the zip is corrupt and cannot be extracted fully. I tried 7z, WinRar, and some others.

**Comment by FredThompsonII** [comment]
CentOS builds are also missing.

**Comment by dlemstra** [comment]
We can open that file without any problem on Windows. And I have no idea why you think that the zip file should also contain CentOS files?

**Comment by FredThompsonII** [comment]
The zip file which was being transferred was truncated at 99.2 M. I just tried again and got a good one at 113 M.  I tried 3 different computers.

I didn't say the CentOS files should be inside the Win64 zip. I said they are missing. That's still the case.

**Comment by FredThompsonII** [comment]
Whoops. Nope. I downloaded the x32 version by mistake just now.

ImageMagick-7.1.1-10-portable-Q16-x64.zip is still truncated.
