### ISSUE TITLE
on creating a Magick::Image, it crashes with nullptr access on OpenMP mutex

### ISSUE THREAD

**Issue by viastore-mg** [ImageMagick/ImageMagick#6356]
### ImageMagick version

7.1.1

### Operating system

Windows

### Operating system, version and so on

ImageMagick from at least 7.1.0-57 to the latest 7.1.1-10

### Description

imagemagick/visualmagick on Windows, built with
`configure.exe -noWizard -VS2022 -dmt -Q16 -zeroConfigurationSupport -x64`
on creating the Image::Magick object, it tries to lock the static mutex 
the address of this variable is a nullptr in the line
`omp_set_lock(&translation_unit_mutex);`
in file MagickCore/mutex.h

I compiled with Visual Studio 2019 14.29, Visual Studio 2022 14.35, both debug and release, the crash happens always.
It did not happen with ImageMagick version 7.1.0-36.
When I compile VisualMagick with -noOpenMP, everything works fine.

### Steps to Reproduce

compile the following file (e.g. with the CMakeLists.txt after that)
imtest.cpp:

```
#include "Magick++.h"
#if __has_include("MagickCore/composite.h")
#include "MagickCore/composite.h"
#else
#include "magick/composite.h"
#endif

#include <memory>

class ImageData
{
public:

	ImageData()
		: image_()
	{
	}

	[[nodiscard]] ImageData* clone() const
	{
		return new ImageData(*this);
	}

	Magick::Image& image()
	{
		return image_;
	}

private:

	Magick::Image image_;
};

int main()
{
	auto x = std::make_unique<ImageData>();
	return 0;
}
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.20)
cmake_policy(SET CMP0074 NEW)
project(imtest)

add_executable(imtest)

target_sources(imtest PRIVATE
	imtest.cpp
	)

target_compile_definitions(imtest PRIVATE
		$<$<PLATFORM_ID:Windows>:_WINDOWS>
	)

find_package(ImageMagick COMPONENTS Magick++ MagickWand MagickCore REQUIRED)
target_link_libraries(imtest PUBLIC
	ImageMagick::ImageMagick
	)
```

**Comment by urban-warrior** [comment]
Recommended practice is to call

```
InitializeMagick(*argv);
```

before you make any Magick++ API calls.  However, we did add a patch so your module will work even if initialization is not performed.  Test out the patch and let us know if it works.

**Comment by viastore-mg** [comment]
In the production code I actually had a call to InitializeMagick, which I accidentally left out from the short example here. But with your patch it works in both cases. Thank you very much!
