### ISSUE TITLE
Having trouble with missing library libtool archives during build

### ISSUE THREAD

**Issue by satmandu** [ImageMagick/ImageMagick#6365]
### ImageMagick version

7.1.1-10

### Operating system

Linux

### Operating system, version and so on

Chromebrew / x86_64

### Description

We're building with these options and getting this build error eventually:
Ubuntu and debian don't have a `libpng16.la` file and the debian/ubuntu builds work just fine, so what are we doing wrong?

```
 ./configure \
      --prefix=/usr/local --libdir=/usr/local/lib64 --mandir=/usr/local/share/man --build=x86_64-cros-linux-gnu --host=x86_64-cros-linux-gnu --target=x86_64-cros-linux-gnu --program-prefix='' --program-suffix='' \
      --mandir=/usr/local/share/man \
      --program-prefix='' \
      --with-windows-font-dir=/usr/local/share/fonts/truetype/msttcorefonts \
      --disable-dependency-tracking \
      --disable-static \
      --enable-shared \
      --enable-hdri \
      --enable-hugepages \
      --with-jemalloc \
      --with-magick-plus-plus \
      --with-modules \
      --with-perl \
      --with-perl-options='INSTALLDIRS=vendor' \
      --with-rsvg \
      --with-x
```

```
make  all-am
make[1]: Entering directory '/usr/local/tmp/crew/imagemagick7.20230526160818.dir'
  CCLD     coders/svg.la
/bin/grep: /usr/local/lib64/libpng16.la: No such file or directory
/usr/local/bin/sed: can't read /usr/local/lib64/libpng16.la: No such file or directory
libtool:   error: '/usr/local/lib64/libpng16.la' is not a valid libtool archive
make[1]: *** [Makefile:7836: coders/svg.la] Error 1
make[1]: Leaving directory '/usr/local/tmp/crew/imagemagick7.20230526160818.dir'
make: *** [Makefile:6236: all] Error 2
```

We get multiple complaints about missing libtool archives from various libraries. These libraries do have pkgconfig files, but don't always have `.la` files.  

Is there a way for libtool to just use the pkgconfig files? Why is libtool seeking out the `.la` files? Is this a libtool bug?

### Steps to Reproduce

See above.

**Comment by urban-warrior** [comment]
Check your `/usr/local` folders.  You likely have a `.la` or `.pc` file that references the `libpng16` dependency.   Perhaps a stale dependent ImageMagick delegate library.  We can't help you with `libtool`.  You would need to seek out the Libtool developers for assistance.

**Comment by satmandu** [comment]
I get complaints about missing `.la` files even if I delete all the `.la` files in the libdir. I also don't see any `.la` files referenced in the pkgconfig folder. I guess I'll ask the libtool folks about this then...
