### ISSUE TITLE
Missing -define pixel:compliance

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#6366]
### Is your feature request related to a problem? Please describe.

The defines page has the following define in the Image Formats section.  I think it should be moved to the Command Line section since it does not really pertain to any one particular image format.

`-define pixel:compliance={svg,none,undefined,mvg,x11,xpm}`

### Describe the solution you'd like

Just move the define to the Command Line section.

**Comment by urban-warrior** [comment]
Done.
