### ISSUE TITLE
[Literally not an issue with ImageMagick] Discord doesn't seem to think ImageMagick APNGs are APNGs

### ISSUE THREAD

**Issue by Scripter17** [ImageMagick/ImageMagick#6368]
### ImageMagick version

7.1.1-10

### Operating system

Linux

### Operating system, version and so on

Ubuntu 23.04 with kernel 6.3.1

### Description

Okay I know this literally isn't a bug with ImageMagick but given the alternative is reporting this issue to discord, I think this is a faster way to solve the issue (Also there's a very slight chance ImageMagick does actually do something wrong with APNGs)

For some reason, converting images into APNGs via ImageMagick does not meet whatever test discord uses to check for a "valid" APNG. This is weird because aspose.app (one of those generic "convert X to Y" sites) is able to do it perfectly fine.

I've tried this with adding a second (different) frame as well as `apng:abc.png`, but every time discord just doesn't seem to detect ImageMagick's output as a valid APNG

### Steps to Reproduce

1. Convert the image by doing `magick abc.jpeg abc.apng`
2. Fill out the discord sticker form and press submit
3. "Invalid asset" error

### Images

[The original image, though it likely isn't relevant given this seems to happen on any image](https://github.com/ImageMagick/ImageMagick/assets/25886989/20dfd0a5-0236-4cb7-8886-810baaa447b2)

[The ImageMagick conversion (renamed from `.apng` to `.png` to make github accept it)](https://github.com/ImageMagick/ImageMagick/assets/25886989/abc48140-a1f4-4244-b969-238bfa63f68c)

[The aspose.app conversion (already had a `.png` extension)](https://github.com/ImageMagick/ImageMagick/assets/25886989/908b3d30-deac-4e20-8531-71642d7f4d86)

**Comment by dlemstra** [comment]
What happens when you do `magick abc.jpeg apng:abc.png` and use that image instead?

**Comment by Scripter17** [comment]
For some stupid reason it works for when the extension is .png but NOT .apng

I could've sworn I tested this before but I guess not

Closing as it's not possible to for ImageMagick to fix this
