### ISSUE TITLE
Imagemagick.org slow/nonresponsive

### ISSUE THREAD

**Issue by Arro** [ImageMagick/ImageMagick#638]
I'm not sure if this is the right place to put this, but I really need to look at some of your docs, and your pages only sometimes load, and when they do it takes 10 minutes.

**Comment by fmw42** [comment]
I have already reported this issue. The whole of the Discourse Server has been slow all day.

**Comment by glennrp** [comment]
The discourse server seems OK now but I haven't been able to pull from the
git repos for the past 24 hours or so.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We could reproduce the performance issue and fixed it.
