### ISSUE TITLE
Error rendering font (No writable cache directories)

### ISSUE THREAD

**Issue by byrafaelr** [ImageMagick/ImageMagick#6381]
### ImageMagick version

ImageMagick 7.1.0-35 Q16-HDRI x86_64 20062

### Operating system

Linux

### Operating system, version and so on

Laravel Vapor

### Description

I am using Imagik to convert SVG images to PNG, but the texts are not being rendered, I am informing the font file using "setfont", I believe that the problem may be due to Laravel Vapor (Serveless),
Which folder does Imagik use for caching? Is it possible to set change at runtime?

Example of generated image:
![image](https://github.com/ImageMagick/ImageMagick/assets/5587864/75f8dd1e-c9fb-42bc-86c2-35afc1db01c4)

The logs show an error:
"Fontconfig error: No writable cache directories"

### Steps to Reproduce

Example code:

```php
$im = new Imagick();
$im->setfont("fonts/Arial.ttf");
$im->readImageBlob($svgFileString);
$im->setImageFormat("png");
return $im->getImageBlob();
``` 

### Images
[test.zip](https://github.com/ImageMagick/ImageMagick/files/11628933/test.zip)

**Comment by fmw42** [comment]
Post your input SVG file.  You may want to ZIP it first.

**Comment by byrafaelr** [comment]
[test.zip](https://github.com/ImageMagick/ImageMagick/files/11628927/test.zip)

**Comment by fmw42** [comment]
That SVG file has no text in it.  So trying to change the font would be ineffective.  I am not sure you can even change the font external to the SVG file. I think you have to edit the SVG file. But I will defer to those more knowledgeable with that process in SVG files.

**Comment by byrafaelr** [comment]
> That SVG file has no text in it. So trying to change the font would be ineffective. I am not sure you can even change the font external to an SVG file that has text in it. I think you have to edit the SVG file. But I will defer to those more knowledgeable with that process in SVG files.

I add the text in the svg before "readImageBlob" I checked if the text is added, it's ok, if you want I can add an svg with example text, but I'm using simple characters like ABC 123, I've already tested it by defining and changing the ecode but that doesn't seem to be the problem.

**Comment by fmw42** [comment]
Read the SVG file first, then add the text afterwards.

**Comment by byrafaelr** [comment]
I'm sorry, I think I didn't explain it well, the code that does the conversion, puts the text and etc... works.
The problem is that when I use it in the serveless environment (Laravel Vapor) Imagik does not work the text, despite generating the image the text is like the image I attached, as the error says "No writable cache directory" I believe I need to change the folder used for /tmp because of serveless, but even so... I find it strange because I'm doing it in memory.

**Comment by fmw42** [comment]
You can set the temp directory for Imagemagick by changing the Imagemagick environment variables in your profile file. See Magick_TEMPORARY_PATH at https://imagemagick.org/script/resources.php#environment

**Comment by byrafaelr** [comment]
> You can set the temp directory for Imagemagick by changing the Imagemagick environment variables in your profile file. See Magick_TEMPORARY_PATH at https://imagemagick.org/script/resources.php#environment

can i change the values of MAGICK_FONT_PATH or MAGICK_TEMPORARY_PATH in php runtime?

**Comment by fmw42** [comment]
Sorry, I am not an IMagick user. But I do not see any direct way at https://www.php.net/manual/en/book.imagick.php. Perhaps via https://www.php.net/manual/en/imagick.setimageartifact.php

**Comment by byrafaelr** [comment]
I tried to set the cache folders to use /tmp but without success, I understand the problems in running in the serveless environment but for me it doesn't make sense to generate the image and only the text doesn't work.
Thanks for the answers.

**Comment by urban-warrior** [comment]
See `file:///usr/share/doc/fontconfig/fontconfig-user.html`.

**Comment by dugwood** [comment]
@byrafaelr got the same issue with `dot`. I tried `dpkg-reconfigure fontconfig-config` which did nothing, but running `fc-cache` as root (or `fc-cache -v` for verbose output) did the trick.

**Comment by vmrfriz** [comment]
> @byrafaelr got the same issue with `dot`. I tried `dpkg-reconfigure fontconfig-config` which did nothing, but running `fc-cache` as root (or `fc-cache -v` for verbose output) did the trick.

Thank you so much. `sudo fc-cache` fix the problem.
