### ISSUE TITLE
Specify the number of levels and pyramid scale factor

### ISSUE THREAD

**Issue by WxpHB** [ImageMagick/ImageMagick#6392]
### ImageMagick version

7.1.1-11

### Operating system

Windows

### Operating system, version and so on

win10

### Description

Hi, thanks for your great work.
I got .tif images in size of 36GB，the "convert" command create a 50GB file,and I also got .tif with almost 150GB, the command may create file in about 200GB, it's too big, . Is there any options to specify the amout of levels, such as "-pyramid-resolutions 4" ，and specify the pyramid scale factor,the default scale factor is 1 ,2,4,8,16, can I specify the scale factor to something like "1,4,16,32,64" or " 1,8,16 ,32"?
Thanks and regards

### Steps to Reproduce

convert input -define tiff:tile-geometry=256x256 -compress jpeg 'ptif:output.tif'

**Comment by urban-warrior** [comment]
We added a new define to the main repo.  As an example, support you want a minimum base of 64 and at most 4 levels in the pyramid, use `-define ptif:pyramid=64x4`.
