### ISSUE TITLE
accept an invalid bmp file

### ISSUE THREAD

**Issue by boofish** [ImageMagick/ImageMagick#6393]
### ImageMagick version

7.1.1-11

### Operating system

Linux

### Operating system, version and so on

Ubuntu 18.04

### Description

An invalid bmp image file should be rejected but it does not. I also tried other bmp image file parser graphicmagick, it can successfully reject it.

### Steps to Reproduce

I test it with the following code, and it does not report an error.

```
#include <string>
#include <iostream>
#include <fstream>
#include <vector>
#include <cstdint>
#include <Magick++/Blob.h>
#include <Magick++/Image.h>
using namespace std;
using namespace Magick;

int main(int argc,char **argv) 
{ 
  // InitializeMagick(*argv);

  if (argc<2)
    {
        printf("need a bmp file\n");
        return 0;
    }

  Image image;
  try { 
    // Read a file
    image.read(argv[1] );
  } 
  catch( Exception &error_ ) 
    { 
      std::cout << "Caught exception: " << error_.what() << std::endl; 
      return 1; 
    } 
  return 0; 
}
```

However, when I test it with graphicmagick, it reports an error with the following logic:

```
if ((bmp_info.size != 12) && (bmp_info.size != 40) && (bmp_info.size != 108)
        && (bmp_info.size != 124) &&
        (!(bmp_info.size >= 12 && bmp_info.size <= 64))) {
    ThrowBMPReaderException(CorruptImageError,ImproperImageHeader,image);
}

```

Hope this helps!

### Images

[invalid.zip](https://github.com/ImageMagick/ImageMagick/files/11667440/invalid.zip)

**Comment by dlemstra** [comment]
We could test for this but I am not sure if we should. Maybe some applications depend on us not being super strict about the size specification.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by boofish** [comment]
thanks for the quick reply!
