### ISSUE TITLE
Image orientation is not correct after converting to WebP

### ISSUE THREAD

**Issue by dooman87** [ImageMagick/ImageMagick#6396]
### ImageMagick version

7.1.1-10

### Operating system

Linux

### Operating system, version and so on

Debian Bullseye

### Description

The result image displays in the wrong orientation after converting Jpeg to WebP.

libwebp version is 1.3.0

### Steps to Reproduce

1. Open the original image in Chrome or other viewers (I tried gwenview and okular) and make sure it displays in the portrait orientation
2. Run `magick test.jpeg webp:test.webp`
3. Open webp image in Chrom or other viewer (I tried gwenview and okular)

Expected behaviour: the result image displays in portrait orientation similar to the original
Actual behaviour: the result imaged displays in landscape orientation

### Images

![orientation](https://github.com/ImageMagick/ImageMagick/assets/124110/2c47d7c9-7d35-4a73-ad24-af4ad0326387)

**Comment by fmw42** [comment]
add -auto-orient to your command

**Comment by dooman87** [comment]
> add -auto-orient to your command

Thanks, that worked! But should the conversion also preserve exif orientation? Or it's not working the same from one format to another?

**Comment by fmw42** [comment]
It looks for  Orientation: RightTop.  Your input does not have any EXIF tag for orientation that I can see.  I do not know if EXIF data is preserved when converting to webp.  That is a question for the IM developers.  They will have to comment further on that aspect.

**Comment by kmilos** [comment]
The Exif is preserved (at least w/ 7.1.1-11).

Part of the problem is that many (or no?) browsers might not support Exif orientation in WebP: https://zpl.fi/exif-orientation-in-different-formats/
