### ISSUE TITLE
RGB -> HSL -> RGB different result.

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#64]
Hi, 

The code below does not behave as I would expect, and I think it's either a bug, or something non-obvious that needs explaining to me. 

Creating an RGB color, converting it to HSL and then converting it back to RGB does not result in the original color. Additionally, the values for the HSL are not what would be expected by most RGB -> HSL conversions.

Input color: rgb(158, 146, 130) 
Final color: rgb(158.00, 141.33, 130.00)

hsl values are 0.0952, 0.1261, 0.5647

Expected values for HSL are:
[hue] => 0.34285714285714
[saturation] => 0.12612612612613
[luminosity] => 0.56470588235294

Please could you shed some light on this?

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <malloc.h>


#include <wand/MagickWand.h>
    

int main(int argc,char **argv) {
    MagickWand *magick_wand;
    MagickBooleanType status;
    PixelWand *pixel_wand_input;
    PixelWand *pixel_wand_output;
    double hue, saturation, luminosity;
    double red, green, blue, alpha;

    char hslString[2028];
    char *inputColor = "rgb(158, 146, 130)";

    MagickWandGenesis();

    pixel_wand_input = NewPixelWand();

    if (PixelSetColor (pixel_wand_input, inputColor) == MagickFalse) {
        printf("Failed to set color");
        exit(-1);
    }

    PixelGetHSL(pixel_wand_input, &hue, &saturation, &luminosity);
    
    sprintf(
        hslString,
        "hsl(%.4f, %.4f, %.4f)", 
        hue * 255,
        saturation * 255,
        luminosity * 255
    );

    printf("hslString is %s\n", hslString);

    pixel_wand_output = NewPixelWand();
    if (PixelSetColor(pixel_wand_output, hslString) == MagickFalse) {
        printf("Failed to set color");
        exit(-1);
    }

    red   = PixelGetRed(pixel_wand_output);
    green = PixelGetGreen(pixel_wand_output);
    blue  = PixelGetBlue(pixel_wand_output);
    
    
    printf("Input color: %s \n", inputColor);

    printf(
        "Final color: rgb(%.2f, %.2f, %.2f)\n", 
        red * 255,
        green * 255,
        blue * 255
    );


    MagickWandTerminus();
    MagickWandTerminus();
 
    return(0);
}
```

**Comment by mikayla-grace** [comment]
The hue multiplier is 360, not 255.  Make that change and results are

```shell
hslString is hsl(34.2857, 32.1622, 144.0000)
Input color: rgb(158, 146, 130) 
Final color: rgb(158.00, 146.00, 130.00)
```

**Comment by Danack** [comment]
Thank-you for the information. 

Please could you point me in the direction of how ImageMagick calculates the HSL values, so that I can include that information in the PHP Imagick documentation, and also be able to respond to people who are expecting different HSL values from the input RGB values, such [as this guy](https://bugs.php.net/bug.php?id=71074)

**Comment by mikayla-grace** [comment]
HSL is normalized.  To get the desired results, multiply the hue by 3.6.

**Comment by Danack** [comment]
Thank you.
