### ISSUE TITLE
Transforming animated Gif to webp creates memoryleak

### ISSUE THREAD

**Issue by CMeldgaard** [ImageMagick/ImageMagick#6407]
### ImageMagick version

ImageMagick 7.1.0-50

### Operating system

Linux

### Operating system, version and so on

64bit Amazon Linux 2/3.5.8

### Description

We were experience issues, where a single process was using up all the memory on the server and all the swap memory. We tracked it down to that, is was a gif, which was animated, was beeing converted to webp. The creates som sort of memoryleak, that crashes the entire server.

### Steps to Reproduce

1. Upload image to server
2. Try to transform to webp
3. Server memory spikes out, until server craches

### Images

https://cdn2.surisuri.dk/uploads/products/premium-hair-treatment/cp-1-premium-hair-treatment-25ml-3.gif

**Comment by snibgo** [comment]
To assist the IM developers, please show the exact IM command you used.

**Comment by urban-warrior** [comment]
Review https://imagemagick.org/script/architecture.php#tera-pixel and apply recommended practice for handling large images or image sequences.

**Comment by HubbGit** [comment]
Yes I can confirm that using PHP Imagick module  converting to animated webp creates memory leaks

**Comment by urban-warrior** [comment]
We're using the latest ImageMagick 7 release with libwebp 1.3.0.  We get no memory leaks:

```
$ magick cp-1-premium-hair-treatment-25ml-3.gif test.webp
==285344== LEAK SUMMARY:
==285344==    definitely lost: 0 bytes in 0 blocks
==285344==    indirectly lost: 0 bytes in 0 blocks
==285344==      possibly lost: 0 bytes in 0 blocks
```
