### ISSUE TITLE
Running against a mapped network drive causes infinite loop that maintains between reboots

### ISSUE THREAD

**Issue by Jason-Orman** [ImageMagick/ImageMagick#6417]
### ImageMagick version

7.1.10

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

Running this command against a mapped network drive, causes an infinite loop of running the same command over and over: 

**C:\test>magick -density 350 "MT-18515 (2).pdf" -alpha remove -compress group4 -scene 1 "V:\PDFs2\MT-18515(2)_%04d.tif"**

even after breaking the command in terminal, rebooting and trying a *different* output directory, it continues with the previous command. Please see the screenshot below

![image](https://github.com/ImageMagick/ImageMagick/assets/111380312/2e5da410-1961-4277-a830-a94639ca2beb)

### Steps to Reproduce

Map a network drive to a SMB path.

Run the command listed above. Trying to run anything using the word "Magick"

**Comment by fmw42** [comment]
Try

C:\test>magick -density 350 "MT-18515 (2).pdf[0]" -alpha remove -compress group4 -scene 1 "V:\PDFs2\MT-18515(2)_%04d.tif"

Does that go into a loop?  The [0] at the end of the input reads only the first page of the PDF

**Comment by Jason-Orman** [comment]
The loop continues even if I run : Magick -version

Somewhere that command is being stored and recalled. It persisted across a reboot on two different machines. Anything involving the magick command recalls that command that loops forever.

**Comment by Jason-Orman** [comment]
![image](https://github.com/ImageMagick/ImageMagick/assets/111380312/cd47b464-c64a-452a-90b7-922442c736c7)

**Comment by fmw42** [comment]
might you have an alias for "magick" that runs some loop?

**Comment by Jason-Orman** [comment]
Not unless ImageMagick created it. This command was run last week using an
older version of the sottware (.1.1) and had no issue, I upgraded both
machines on Friday to .1.11 and now this issue happens when trying to run
anything. In fact, just earlier today it worked fine when converting a PDF
on a local drive to both multipage tifs and +adjoining them to multiple
files.

This only started after trying to run this when output goes specifically to
a mapped drive

**Comment by fmw42** [comment]
What was the older version that ran?  How did you install the upgrade?  What software and from where? Did you use the installer?

**Comment by Jason-Orman** [comment]
The version that worked I believe was 7.1.1-7 (I think). It may just be
coincidence that this was done locally previously. I installed the upgrade
from https://imagemagick.org/script/download.php#windows using the primary
download link. I did use the installer. I'm going to try installing
7.1.1-11 in a few moments to see if it resolves this long enough to run
things locally. I am currently on 7.1.1-10

**Comment by dlemstra** [comment]
It looks like you are using a batch file? Isn't this an issue inside your batch file?

**Comment by Jason-Orman** [comment]
This isn't a batch file, it's just a command line.

I have a little more time, so I will write up a formalized way to recreate:

1. Map a drive letter to a network smb drive: v: > \\diskarray\destinationfolder
2. run **magick -density 350 "origin.pdf" -alpha remove -compress group4 -scene 1 "V:\destinationfolder\MT-31071_%04d.tif**
3. Doing this will cause an immediate endless loop that calls the command 100's of times a second, but never does the actual process.
4. Terminate the process with CTRL-C
5. Run any command again including **magick -version** and it will not run the command given, but recall the previous command (line 2), and repeat it endlessly as fast as your system can process it.

As a note, in trying to clear up the issue, the system was rebooted. When rebooting and running the process again (magick -version), it somehow recalled the line from step 2 and began running it endlessly again. Does IM store the last command anywhere (registry, user config, etc) on a process running? 

I will try to make a screencap video of it later if it helps.

As a note, I installed the most recent version: 7.1.1.11 and on one PC that was rebooted it resolved the issue. On the second PC, it continued to happen. After a reboot, it resolved it still persisted on the 2nd PC even with an upgrade to the new version.

**Comment by snibgo** [comment]
Does it happen with all PDFs, or just "MT-18515 (2).pdf"? If just that file, please link to it. Maybe there is something funny about it, such as it includes itself. If you rename that file, does the problem still occur?

> Does IM store the last command anywhere (registry, user config, etc) on a process running?

No. While an IM command is running, it can recall its own arguments. But IM has no memory from one command to the next.

Shells do remember commands, so they can recalled by `up-arrow` or whatever. 

On Windows, what is the text output from:
```
where magick.exe
```

After a fresh reboot, what is the text output from:
```
magick -version
```

**Comment by Jason-Orman** [comment]
Ok, here is a REALLY weird development. I had a bat file in the same directory and when I would run anything, it appeared to be trying to run the bat file instead of the command I was actually typing. When I deleted the batch file out of the directory, while trying to record a video of what was happening, it immediately started working normally again. This was tested on the second computer as well.

**Comment by fmw42** [comment]
What was in the .bat file?  Did it contain Imagemagick commands?  What was the name of the bat file - was it named magick or something like that? Did it have a cron command or the like to run repeatedly?

**Comment by Jason-Orman** [comment]
ok, I confirmed with the user... /sigh... they named it magick.bat... I've been troubleshooting this with them for hours and never thought to ask that... only when I deleted the .bat file and you asking that did it dawn on me.

Thank you for helping me solve this short circuit between the keyboard and chair lol
