### ISSUE TITLE
Text by path not working

### ISSUE THREAD

**Issue by FilippovAM** [ImageMagick/ImageMagick#642]
1) open svg in the browser
![text-by-path-in-browser](https://user-images.githubusercontent.com/12913535/28859498-27996f9e-778a-11e7-9900-95c6b8f13ece.jpg)
That was taken from the resource - https://developer.mozilla.org/ru/docs/Web/SVG/Element/textPath 
2) install ImageMagick, OS Windows 10
3) run the command prompt as administrator
4) magick -version
![im-version](https://user-images.githubusercontent.com/12913535/28859427-c28c26f0-7789-11e7-852a-35bb2bf94577.jpg)
5) magick convert text-by-path.svg text-by-path.png
![im-convert](https://user-images.githubusercontent.com/12913535/28859565-a4e4f978-778a-11e7-96c1-52eae2186c4d.jpg)
6) file is saved
![save-png](https://user-images.githubusercontent.com/12913535/28859569-b06ca70a-778a-11e7-8fdf-151f4b5dc45a.jpg)
7) open text-by-path.png, but text disappeared :'(
![open-png](https://user-images.githubusercontent.com/12913535/28859669-495ce2fe-778b-11e7-9745-9879459eb73f.jpg)

If i start ImageMagick Display and open text-by-path.svg then I will see the following:
![im-display-open-svg](https://user-images.githubusercontent.com/12913535/28859623-ff702eb2-778a-11e7-8119-928098df5d0a.jpg)

Just do it!! Please:) Thank you!

**Comment by mikayla-grace** [comment]
You are likely using the ImageMagick internal SVG renderer which is still not fully SVG compliant.  Your example worked for us.  Try installing inkscape on your system or the RSVG delegate library.  We use RSVG:

```
$ convert -list format | grep SVG
SVG  rw+   Scalable Vector Graphics (RSVG 2.40.18)
```

**Comment by dlemstra** [comment]
The Windows build uses librsvg. Will need to test if upgrading fixes this issue.

**Comment by RomanLubushkin** [comment]
Thank you for your suggestions, we have tried both, but the result is nearly the same.
librsvg - gives the absolutely same result
Inkscape - works correct for single line text, but fails in case of multi-line

| Input SVG preview  | Output PDF preview |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/680750/29302088-db49aa30-81b3-11e7-85d1-72a75c2d3a5f.png)  | ![image](https://user-images.githubusercontent.com/680750/29302096-eb8f139e-81b3-11e7-8206-1e7f3886ba35.png)  |

Note the way top text is rendered.
Source files: [input svg](https://www.dropbox.com/s/5e8995xdf787g0x/imagemagic_input.svg?dl=0), [output pdf](https://www.dropbox.com/s/2ni8xwx0w8loeyr/imagemagic_output.pdf?dl=0)

**Comment by loki20beta** [comment]
Guys, any news on this, we are really interested in possible solutions or confirmation it is a bug.

**Comment by dlemstra** [comment]
I will upgrade librsvg to 2.40.18 tonight and check if that will resolve the issue.

**Comment by dlemstra** [comment]
Just did an upgrade of librsvg to 2.40.18 and it appears there is still no support for `textPath` in that version. An issue for librsvg can be found here: https://bugzilla.gnome.org/show_bug.cgi?id=644624.
