### ISSUE TITLE
Menu Box

### ISSUE THREAD

**Issue by AnonymousRonin** [ImageMagick/ImageMagick#6420]
### Is your feature request related to a problem? Please describe.

Can the utility box be configured to be moved? Or  if is what am I missing.  I would be nice if they were just dropdowns, I keep finding that box right where I need to work.

### Describe the solution you'd like

Redesign or reconfugure the menu box.

### Describe alternatives you've considered

None

**Comment by urban-warrior** [comment]
Not sure what you're talking about.  Post a screenshot and point out where the "menu" box is and where you would like it to be...
