### ISSUE TITLE
./configure `--with-perl` should imply `--with-dynamic`

### ISSUE THREAD

**Issue by guest20** [ImageMagick/ImageMagick#6422]
### ImageMagick version

7.1.1-11

### Operating system

Linux

### Operating system, version and so on

dockerhub  perl:5.26  image derived from debian 

### Description

This is line 168 on `Install-unix.txt`:

>       --enable-shared
>         build the shared libraries and support for loading coder and process
>         modules. Shared libraries are preferred because they allow programs
>         to share common code, making the individual programs much smaller. In
>         addition shared libraries are required in order for PerlMagick to be
>         dynamically loaded by an installed PERL (otherwise an additional PERL
>         (PerlMagick) must be installed.

It seems pretty clear that when I say `--with-perl=/usr/local/bin/perl` I would like `--enable-shared` to also be switched on, so that I can actually load my freshly compiled magick into the perl I was just configuring the makefile about. 

### Steps to Reproduce

In a `Dockerfile`: 

```Dockerfile
FROM perl:5.26
COPY ImageMagick*tar.gz  .
RUN tar -zxf ImageMagick-7.1.1-11.tar.gz && \
  cd ImageMagick-7.1.1-11  && \
  ./configure --with-perl=/usr/local/bin/perl --enable-shared  && \
  make install 
```
```sh
docker build 
docker run /usr/local/bin/perl -MData::Dumper  \
  -E' eval "use Image::Magick"; say Dumper \%INC '
```
Without `--enable-shared`, the Dumper will show the `Image/Magick.pm => undef`, indicating that perl didn't find the installed _stuff_

### Images

This is the docker kind of image, not a pixel kind of image.

**Comment by urban-warrior** [comment]
The Linux build instructions are out of date.  We updated the instructions in the main repo.

**Comment by guest20** [comment]
Is there a specific reason why `--with-perl` shouldn't turn on `--with-dynamic`? It seems like having `--with-perl` not produce a loadable library by default might lead to someone spending 2 or 3 days trying to figure out why perl can't find the modules they literally just compiled and installed.

Also, perl doesn't need to be in SHOUTY CAPS in the docs. Personally, I'm pretty enthusiastic about perl, but I don't think it needs to be shouted every time ;)
