### ISSUE TITLE
Why don't ImageMagick pin the versions of dependencies? 

### ISSUE THREAD

**Issue by junwha0511** [ImageMagick/ImageMagick#6430]
### Is your feature request related to a problem? Please describe.

The current version of ImageMagick is failed to build the fuzzers on base-builder image of oss-fuzz
(Magick++/fuzz/build_dependencies.sh)

the reason is 
- xz now requires --no-doxgen, otherwise it halts its build because base-builder has no doxygen in default
- libheif now requires -DBUILD_TESTING=off, otherwise it will lead to undefined reference crashes with AddressSanitizer build
- libjxl must be at most v0.7.0, because some of its interfaces in  jxl/decode.h are now incompatible with ImageMagick

### Describe the solution you'd like

Thus, it seems there is a need to pin the dependencies for Imagemagick. 
while I'm creating the PR for that, I wonder why anyone didn't try this.

### Describe alternatives you've considered
we can just add the options for enabling or disabling some features with latest version, except the case of libjxl

**Comment by dlemstra** [comment]
With the oss-fuzz build we always want to build with the latest commit of our dependencies so we can find issues in our and their code earlier. And this will also allow us to find build issues or compatibility issues early. But we haven't had/made time to fix the breaking build that has been an issue for almost a month now. But I am right now working on fixing the build.

**Comment by junwha0511** [comment]
Thank you for your fast reponse!:)

> p.s. What was the reason you reached out about this to us? We could use some help to fix those issues when they happen. Are you monitoring the failing builds?

I'm currently experimenting my custom tool with the applications in oss-fuzz, and the ImageMagick is the one of them.
Thus I encountered that issues while building the imagemagick fuzzers in oss-fuzz on my server, and found the issues.

**Comment by dlemstra** [comment]
I pushed some changes that should resolve the build issues. Can you check it with the latest commit and close this issue if the build issues have been resolved?

**Comment by junwha0511** [comment]
Thank you

it seems jxl macro didn't work
<img width="529" alt="image" src="https://github.com/ImageMagick/ImageMagick/assets/17183234/375dfea7-f2b5-48d0-a5ce-708d83700d61">

**Comment by junwha0511** [comment]
Now I checked all the issues are completely resolved on base-builder! Thank you for your efforts on this issue:)

**Comment by dlemstra** [comment]
Our oss-fuzz build seems to be broken again but I have no clue what is causing this now. How did you figure out last time that libheif was causing this issue @junwha0511? And do you have any pointers what could be causing this now?

**Comment by junwha0511** [comment]
Sorry for the late response. I just checked the changes of dependencies (more specifically, its build file) after the last working date of imagemagick build on base-builder image.
And now I tried once again, but it have no build crash with my oss-fuzz version. Did you resolve the issues?

**Comment by dlemstra** [comment]
I did figure out what was causing this by attaching a debugger and finding the "problem" in the `xz` repository.
