### ISSUE TITLE
Did 7.1.1-12 get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [ImageMagick/ImageMagick#6434]
### ImageMagick version

7.1.1-12

### Operating system

Linux

### Operating system, version and so on

n/a

### Description

👋 Looks like imagemagick 7.1.1-12 get re-tagged? And now the artifact reports different checksum, raise this issue to confirm if that is intended. Thanks!

relates to:
- https://github.com/Homebrew/homebrew-core/pull/134983
- https://github.com/Homebrew/homebrew-core/pull/134953

### Steps to Reproduce

Download the artifact `https://imagemagick.org/archive/releases/ImageMagick-7.1.1-12.tar.xz` and run the checksum

```
$ curl -sL https://imagemagick.org/archive/releases/ImageMagick-7.1.1-12.tar.xz | shasum -a 256
a761aa8c3b0690910600ba838d15379b676820f1ed912382d31c9b5da1ca1878  -
```

**Comment by dlemstra** [comment]
We didn't create the tag yet? There is always a delay between the release and the creation of the tag. I just pushed the tag.

**Comment by chenrui333** [comment]
@dlemstra Got you, which one would you recommend for us (homebrew) to track each release. Thanks!

**Comment by dlemstra** [comment]
Not sure if I understand what you are asking us? You created this issue about tags but it seems that you are using our `http` download and creating a checksum for that file? I am sorry but I don't know how `brew` works internally.

It might be possible that @urban-warrior had to replace the file because he uploaded an incorrect file by accident?

**Comment by chenrui333** [comment]
also noticed the same file change for `ImageMagick-6.9.12-90.tar.xz`

@urban-warrior do you mind answering what happened? Thanks!

**Comment by urban-warrior** [comment]
The 7.1.1-12 and 6.9.12-90 releases of ImageMagick were disrupted and we had to restart the release script.  This could account for any checksum differences.  Recall that ImageMagick generates GPG signatures and checksum digests.  If these do not match the current files, that would suggest a security issue.  You can correct your checksums, or we can issue a quick release to fix the checksum issue.  What is your preference?

**Comment by chenrui333** [comment]
yeah, for now, I will just correct the checksums for homebrew packages (not sure if it would an issue for other package distributions)

**Comment by chenrui333** [comment]
Looking at archlinux and alpine index, they all use the correct checksum, maybe it is just homebrew side issue 🤷 😅 

Thanks for the offering though.
