### ISSUE TITLE
Convert heic to jpg aborted on server but not on local machine

### ISSUE THREAD

**Issue by Riaz1** [ImageMagick/ImageMagick#6435]
### ImageMagick version

7.1.1-12

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04.6 LTS

### Description

Running the command on my local machine:

```
$ magick IMG20230522091101.heic -quality 85% IMG20230522091101.jpeg
```

creates the jpeg image with message: magick: exif profile size exceeds limit and will be truncated

Running the same command on my server is Aborted, no jpeg image is created

```
$ magick IMG20230522091101.heic -quality 85% IMG20230522091101.jpeg -debug all

2023-06-26T20:10:25+00:00 0:00.000 0.010u 7.1.1 Wand magick[24081]: wandcli.c/AcquireMagickCLI/115/Wand
  MagickWandCLI-0
2023-06-26T20:10:25+00:00 0:00.000 0.010u 7.1.1 Command magick[24081]: magick-cli.c/MagickImageCommand/938/Command
  Initializing "magick"
2023-06-26T20:10:25+00:00 0:00.000 0.010u 7.1.1 Configure magick[24081]: client.c/SetClientName/123/Configure
  magick
2023-06-26T20:10:25+00:00 0:00.000 0.010u 7.1.1 Command magick[24081]: magick-cli.c/ProcessCommandOptions/617/Command
  at CLI arg 1 - Starting ("IMG20230522091101.heic")
2023-06-26T20:10:25+00:00 0:00.000 0.010u 7.1.1 Command magick[24081]: operation.c/CLINoImageOperator/4852/Command
  at CLI arg 1 - NoImage Operator: -read "IMG20230522091101.heic" ""
2023-06-26T20:10:25+00:00 0:00.000 0.010u 7.1.1 Configure magick[24081]: utility.c/ExpandFilenames/975/Configure
  Command line: IMG20230522091101.heic
2023-06-26T20:10:25+00:00 0:00.001 0.010u 7.1.1 Policy magick[24081]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Module; rights=Unrecognized; pattern="HEIC" ...
2023-06-26T20:10:25+00:00 0:00.001 0.010u 7.1.1 Policy magick[24081]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Path; rights=Read; pattern="IMG20230522091101.heic" ...
2023-06-26T20:10:25+00:00 0:00.001 0.010u 7.1.1 Blob magick[24081]: blob.c/OpenBlob/3453/Blob
    read 3 magic header bytes
2023-06-26T20:10:25+00:00 0:00.001 0.010u 7.1.1 Cache magick[24081]: cache.c/DestroyPixelCache/1065/Cache
  destroy 
2023-06-26T20:10:25+00:00 0:00.001 0.010u 7.1.1 Policy magick[24081]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Path; rights=Read; pattern="IMG20230522091101.heic" ...
2023-06-26T20:10:25+00:00 0:00.001 0.010u 7.1.1 Blob magick[24081]: blob.c/OpenBlob/3453/Blob
    read 3 magic header bytes
2023-06-26T20:10:25+00:00 0:00.001 0.010u 7.1.1 Cache magick[24081]: cache.c/DestroyPixelCache/1065/Cache
  destroy 
2023-06-26T20:10:25+00:00 0:00.001 0.010u 7.1.1 Policy magick[24081]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Coder; rights=Read; pattern="HEIC" ...
2023-06-26T20:10:25+00:00 0:00.001 0.010u 7.1.1 Policy magick[24081]: policy.c/IsRightsAuthorized/647/Policy
  Domain: Path; rights=Read; pattern="IMG20230522091101.heic" ...
2023-06-26T20:10:25+00:00 0:00.001 0.010u 7.1.1 Blob magick[24081]: blob.c/OpenBlob/3453/Blob
    read 3 magic header bytes
2023-06-26T20:10:25+00:00 0:00.010 0.020u 7.1.1 Pixel magick[24081]: pixel.c/SetPixelChannelMask/6305/Pixel
  IMG20230522091101.heic[07ffffff]
2023-06-26T20:10:25+00:00 0:00.010 0.020u 7.1.1 Pixel magick[24081]: pixel.c/LogPixelChannels/6189/Pixel
  IMG20230522091101.heic[07ffffff]
2023-06-26T20:10:25+00:00 0:00.010 0.020u 7.1.1 Pixel magick[24081]: pixel.c/LogPixelChannels/6286/Pixel
    0: red (update)
2023-06-26T20:10:25+00:00 0:00.010 0.020u 7.1.1 Pixel magick[24081]: pixel.c/LogPixelChannels/6286/Pixel
    1: green (update)
2023-06-26T20:10:25+00:00 0:00.010 0.020u 7.1.1 Pixel magick[24081]: pixel.c/LogPixelChannels/6286/Pixel
    2: blue (update)
2023-06-26T20:10:25+00:00 0:00.010 0.020u 7.1.1 Resource magick[24081]: resource.c/AcquireMagickResource/390/Resource
  Area: 48MiB/0B/250.757GiB
2023-06-26T20:10:25+00:00 0:00.011 0.020u 7.1.1 Resource magick[24081]: resource.c/AcquireMagickResource/390/Resource
  Memory: 576MiB/576MiB/62.6892GiB
2023-06-26T20:10:25+00:00 0:00.011 0.020u 7.1.1 Cache magick[24081]: cache.c/OpenPixelCache/3803/Cache
  open IMG20230522091101.heic[0] (Heap Memory, 6144x8192x3 576MiB)
Aborted
```

More Info:

```
$ magick --version
Version: ImageMagick 7.1.1-11 Q16-HDRI x86_64 21206 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib djvu fontconfig freetype heic jbig jng jpeg lcms lqr lzma openexr pangocairo png tiff webp x xml zlib
Compiler: gcc (9.4)

$ identify IMG20230522091101.heic 
IMG20230522091101.heic HEIC 6144x8192 6144x8192+0+0 8-bit sRGB 915745B 0.010u 0:00.009
```

I am able to convert the example.heic to a jpeg on my server

### Steps to Reproduce

Run on magick IMG20230522091101.heic -quality 85% IMG20230522091101.jpeg using the image attached.

### Images

[IMG20230522091101.zip](https://github.com/ImageMagick/ImageMagick/files/11873824/IMG20230522091101.zip)

**Comment by urban-warrior** [comment]
We're using ImageMagick 7.1.1-12 and your command completes without complaint.  We'll need a stack trace.  Try this command sequence:

```
$ gdb magick
run IMG20230522091101.heic -quality 85% IMG20230522091101.jpeg
where
```

Post the back-trace here so we can determine  which subsystem threw the abort.

**Comment by Riaz1** [comment]
Thank you for your response, the results of the command are below:

(gdb) run IMG20230522091101.heic -quality 85% IMG20230522091101.jpeg
Starting program: /usr/local/bin/magick IMG20230522091101.heic -quality 85% IMG20230522091101.jpeg
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffc592f700 (LWP 44987)]
[New Thread 0x7fffc512e700 (LWP 44988)]
[New Thread 0x7fffc492d700 (LWP 44989)]
[New Thread 0x7fffbffff700 (LWP 44990)]
[New Thread 0x7fffbf7fe700 (LWP 44991)]
[New Thread 0x7fffbeffd700 (LWP 44992)]
[New Thread 0x7fffbe7fc700 (LWP 44993)]

Thread 2 "magick" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc592f700 (LWP 44987)]
0x00007ffff70f3496 in heif::HeifContext::decode_image_planar (this=0x55555559f080, ID=10000, 
    img=std::shared_ptr<heif::HeifPixelImage> (empty) = {...}, out_colorspace=heif_colorspace_RGB, options=0x0, alphaImage=false)
    at heif_context.cc:1093
1093	heif_context.cc: No such file or directory.


(gdb) where
#0  0x00007ffff70f3496 in heif::HeifContext::decode_image_planar(unsigned int, std::shared_ptr<heif::HeifPixelImage>&, heif_colorspace, heif_decoding_options const*, bool) const
    (this=0x55555559f080, ID=10000, img=std::shared_ptr<heif::HeifPixelImage> (empty) = {...}, out_colorspace=heif_colorspace_RGB, options=0x0, alphaImage=false) at heif_context.cc:1093
#1  0x00007ffff70f5d94 in heif::HeifContext::decode_and_paste_tile_image(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const (this=<optimized out>, tileID=<optimized out>, img=std::shared_ptr<heif::HeifPixelImage> (use count 5, weak count 1) = {...}, x0=0, y0=0)
    at heif_image.h:89
#2  0x00007ffff70f6a1d in std::__invoke_impl<heif::Error, heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int>(std::__invoke_memfun_deref, heif::Error (heif::HeifContext::*&&)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*&&, unsigned int&&, std::shared_ptr<heif::HeifPixelImage>&&, int&&, int&&) (__t=<optimized out>, __f=<optimized out>)
    at /usr/include/c++/9/bits/invoke.h:89
#3  std::__invoke<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int>(heif::Error (heif::HeifContext::*&&)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*&&, unsigned int&&, std::shared_ptr<heif::HeifPixelImage>&&, int&&, int&&)
    (__fn=<optimized out>) at /usr/include/c++/9/bits/invoke.h:96
#4  std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul, 5ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul, 5ul>) (this=<optimized out>) at /usr/include/c++/9/thread:244
#5  std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >::operator()() (this=<optimized out>)
    at /usr/include/c++/9/thread:251
#6  std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<heif::Error>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >, heif::Error>::operator()() const (this=0x7fffc592ebf0)
    at /usr/include/c++/9/future:1339
#7  std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<heif::Error>, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >, heif::Error> >::_M_invoke(std::_Any_data const&) (__functor=...)
    at /usr/include/c++/9/bits/std_function.h:286
#8  0x00007ffff70f65ed in std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>::operator()() const (this=<optimized out>) at /usr/include/c++/9/bits/std_function.h:683
#9  std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (this=0x555555575710, __f=<optimized out>, __did_set=0x7fffc592eba7) at /usr/include/c++/9/future:561
--Type <RET> for more, q to quit, c to continue without paging--
#10 0x00007ffff66934df in __pthread_once_slow (once_control=0x555555575728, init_routine=0x7ffff6309c20 <__once_proxy>) at pthread_once.c:116
#11 0x00007ffff70f78cd in __gthread_once (__func=<optimized out>, __once=0x555555575728)
    at /usr/include/x86_64-linux-gnu/c++/9/bits/gthr-default.h:700
#12 std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) (__f=
    @0x7fffc592ebc0: (void (std::__future_base::_State_baseV2::*)(std::__future_base::_State_baseV2 * const, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()> *, bool *)) 0x7ffff70f65c0 <std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>, __once=...)
    at /usr/include/c++/9/mutex:683
#13 std::__future_base::_State_baseV2::_M_set_result(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool) (__ignore_failure=false, __res=..., this=0x555555575710) at /usr/include/c++/9/future:401
#14 std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >, heif::Error>::_Async_state_impl(std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >&&)::{lambda()#1}::operator()() const (this=0x5555555d8a68) at /usr/include/c++/9/future:1662
#15 std::__invoke_impl<void, std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >, heif::Error>::_Async_state_impl(std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >&&)::{lambda()#1}>(std::__invoke_other, std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >, heif::Error>::_Async_state_impl(std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >&&)::{lambda()#1}&&) (__f=...) at /usr/include/c++/9/bits/invoke.h:60
#16 std::__invoke<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >, heif::Error>::_Async_state_impl(std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >&&)::{lambda()#1}>(std::__invoke_result&&, (std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >, heif::Error>::_Async_state_impl(std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::--Type <RET> for more, q to quit, c to continue without paging--
HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >&&)::{lambda()#1}&&)...) (__fn=...) at /usr/include/c++/9/bits/invoke.h:95
#17 std::thread::_Invoker<std::tuple<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >, heif::Error>::_Async_state_impl(std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >&&)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x5555555d8a68) at /usr/include/c++/9/thread:244
#18 std::thread::_Invoker<std::tuple<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >, heif::Error>::_Async_state_impl(std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >&&)::{lambda()#1}> >::operator()() (this=0x5555555d8a68) at /usr/include/c++/9/thread:251
#19 std::thread::_State_impl<std::thread::_Invoker<std::tuple<std::__future_base::_Async_state_impl<std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >, heif::Error>::_Async_state_impl(std::thread::_Invoker<std::tuple<heif::Error (heif::HeifContext::*)(unsigned int, std::shared_ptr<heif::HeifPixelImage> const&, int, int) const, heif::HeifContext const*, unsigned int, std::shared_ptr<heif::HeifPixelImage>, int, int> >&&)::{lambda()#1}> > >::_M_run() (this=0x5555555d8a60) at /usr/include/c++/9/thread:195
#20 0x00007ffff630ade4 in  () at /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#21 0x00007ffff668a609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#22 0x00007ffff78c3133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)

For reference, the example.heic file is converted:

(gdb) run example.heic -quality 85% example.jpeg
Starting program: /usr/local/bin/magick example.heic -quality 85% example.jpeg
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff1d75700 (LWP 44909)]
[Thread 0x7ffff1d75700 (LWP 44909) exited]
[New Thread 0x7ffff1d75700 (LWP 44910)]
[Thread 0x7ffff1d75700 (LWP 44910) exited]
[Inferior 1 (process 44841) exited normally]
(gdb)

**Comment by urban-warrior** [comment]
The stack trace shows the abort is inside the libheif delegate library.  You will need to contact their support team to fix the issue.  Try this command:

```
$ magick -list format | grep HEIC
```

It shows our HEIC delegate library version is 1.16.1.  If you have an older version, try upgrading first before you report the issue to the libheif developers.

**Comment by Riaz1** [comment]
Updating the HEIC delegate library from 1.12.0 to 1.16.2 solved it.
