### ISSUE TITLE
Oklab and Oklch colorspaces conversion bug

### ISSUE THREAD

**Issue by vrzlev** [ImageMagick/ImageMagick#6444]
### ImageMagick version

7.1.1

### Operating system

Linux

### Operating system, version and so on

openSUSE Tumbleweed

### Description

Hello!

The following produces a black rectangle instead of reconstructing the original image.

```
magick -size 800x800 plasma: plasma1.png
magick plasma1.png -colorspace Oklch -separate lch%d.png
magick lch0.png lch1.png lch2.png -set colorspace Oklch -combine -colorspace sRGB plasma2.png
```

Same in Oklab colorspace.

First raised here: https://github.com/ImageMagick/ImageMagick/discussions/6443

Thank you very much.

### Steps to Reproduce

```
magick -size 800x800 plasma: plasma1.png
magick plasma1.png -colorspace Oklch -separate lch%d.png
magick lch0.png lch1.png lch2.png -set colorspace Oklch -combine -colorspace sRGB plasma2.png
```

### Images

| Input  | Channels | Output 
| ------------- | ------------- | --- |
| ![plasma1](https://github.com/ImageMagick/ImageMagick/assets/137961841/fa154f45-a686-49af-95fe-dd6f70a365bd)  | ![lch0](https://github.com/ImageMagick/ImageMagick/assets/137961841/97037525-c8eb-4425-b365-118072e62ecd) | ![plasma2](https://github.com/ImageMagick/ImageMagick/assets/137961841/43badc83-66be-4d5e-a7cb-fa88ec719fc0) |
|   | ![lch1](https://github.com/ImageMagick/ImageMagick/assets/137961841/cbbedfb3-6758-4780-b99a-5e41fa10026c)  | |
| | ![lch2](https://github.com/ImageMagick/ImageMagick/assets/137961841/51093c44-060f-49c7-8559-5f28e0f858d6) | |

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
