### ISSUE TITLE
[magick++] Using RoundCap breaks LineJoins

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#646]
**summary:** Setting a `LineCap` to `RoundCap` will automatically override `LineJoin` to be `RoundJoin`. This makes it impossible to create images with e.g. `RoundCap` and `MiterJoin`.

I am using `ImageMagick 6.9.9.5`. The problem does not seem to happen on `6.8.9.9`. Perhaps it might have been introduced in here:

```
2016-12-14  6.9.7-0 Cristy  <quetzlzacatenango@image...>
  * Do not close path for linejoins of round (reference
    https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=31039).
```

The example below has `Magick::RoundCap` with 3 lines `Magick::RoundJoin`, `Magick::MiterJoin` and `Magick::BevelJoin`. As you can see the linejoin is always rounded when line-ending is set to `RoundCap`. If `DrawableStrokeLineCap` is unset, then the joins are OK.

![magick_linejoin](https://user-images.githubusercontent.com/216319/28994759-12ce3204-79d6-11e7-82af-cea6cc52083b.png)

Below the output we would expect (using plain cairo):
![cairo_linejoin](https://user-images.githubusercontent.com/216319/28994752-d987e38c-79d5-11e7-8ac9-2d8e46e5dc67.png)

**Comment by mikayla-grace** [comment]
Can you post a small program we can use to reproduce the problem you posted?   Once we reproduce it, we can use the demo to help identify a proper patch to fix the problem.

**Comment by jeroen** [comment]
OK [here an example](https://gist.github.com/jeroen/75f35785720a358e6be9026ff8290193) that should roughly produce the figure above. Note that `LineJoin` values only work after you comment-out the line with `RoundCap`.

**Comment by jeroen** [comment]
@mikayla-grace @urban-warrior does the example suffice? Can you reproduce this problem?

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by jeroen** [comment]
Thank you! Assuming this is fixed (will wait for next release to test).
