### ISSUE TITLE
Error in number of channels output from command in IM 7 but not in IM 6

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#6461]
### ImageMagick version

7.1.1-12

### Operating system

MacOS

### Operating system, version and so on

Ventura

### Description

The following code works fine in IM 6 to give a single grayscale channel output.

![image original](https://github.com/ImageMagick/ImageMagick/assets/13458218/f76d03cb-907b-43cb-a2f8-9080dfa028fa)

```
convert image.original.jpg \
\( -clone 0 -colorspace HSB -channel G -negate -separate +channel \) \
\( -clone 0 -colorspace HSB -channel B -separate +channel -solarize 50% -level 0x50% \) \
\( -clone 1 -clone 2 -compose multiply -composite \) \
\( -clone 3 -contrast-stretch 0,1% -fill black +opaque white \) \
-delete 0-3 -format "%[channels]\n" info:
gray
```

However, I get a weird combination of images output as if getting every different image from each parenthesis in the output from the same command in IM 7. This is possibly an issue with MPC.

```
magick image.original.jpg \
\( -clone 0 -colorspace HSB -channel G -negate -separate +channel \) \
\( -clone 0 -colorspace HSB -channel B -separate +channel -solarize 50% -level 0x50% \) \
\( -clone 1 -clone 2 -compose multiply -composite \) \
\( -clone 3 -contrast-stretch 0,1% -fill black +opaque white \) \
-delete 0-3 -format "%[channels]\n" info:
srgb  3.0
srgb  3.0
srgb  3.0
gray  1.0
gray  1.0
```

### Steps to Reproduce

See above

### Images

See above

**Comment by urban-warrior** [comment]
We're using ImageMagick 7.1.1-13 and we get expected results: the image colorspace and the number channels and number of meta channels:

```
$ magick image.original.jpg \( -clone 0 -colorspace HSB -channel G -negate -separate +channel \) \( -clone 0 -colorspace HSB -channel B -separate +channel -solarize 50% -level 0x50% \) \( -clone 1 -clone 2 -compose multiply -composite \) \( -clone 3 -contrast-stretch 0,1% -fill black +opaque white \) -delete 0-3 -format "%[channels]\n" info:
gray  1.0
```

**Comment by fmw42** [comment]
I am getting an error when trying to unzip and install the 7.1.1-13 beta.  After I decompress it and try to move it to my directory, I get an error saying 

"The Finder can’t complete the operation because some data in “ImageMagick-7.1.1-13beta” can’t be read or written.
(Error code -36)”

On my Mac.

Fred

**Comment by fmw42** [comment]
OK. With the latest 7.1.1.13 beta, I now get expected results.
