### ISSUE TITLE
Unexpected end-of-file error when loading valid 180x215 1-bit gray format image

### ISSUE THREAD

**Issue by circl-lastname** [ImageMagick/ImageMagick#6463]
### ImageMagick version

7.1.1-12

### Operating system

Linux

### Operating system, version and so on

Arch Linux Rolling - kernel 6.4.1-arch1-1

### Description

The `convert` utility fails to load a valid 180x215 image encoded in 1-bit monochrome using the `gray` coder, resulting in an unexpected end-of-file error on line 245 in `gray.c`. No issue occurs when loading an image encoded the same way of resolution 256x256. The former file has a size of 4838 bytes, which according to the calculation `180x215/8`, it is enough bytes to fit such image. The images are generated by my own dithering utility, however are valid and have worked every other time.

### Steps to Reproduce

1. Download the files `david_4838.gray` and `david_8192.gray`
2. Run the command `convert -size 256x256 -depth 1 david_8192.gray david_8192.png` - expected behavior, file is loaded and converted to PNG.
3. Run the command `convert -size 180x215 -depth 1 david_4838.gray david_4838.png` - receive the following error:
```
convert: unexpected end-of-file 'david_4838.gray': Invalid argument @ error/gray.c/ReadGRAYImage/245.
convert: no images defined `david_4838.png' @ error/convert.c/ConvertImageCommand/3342.
```
4. Use another utility like [rawpixels.net](https://rawpixels.net/), specifying the file format - expected behavior, file is loaded (albeit with slightly incorrect color levels, that's on them).

### Images

`david_4838.gray` and `david_8192.gray`:
[david.tar.gz](https://github.com/ImageMagick/ImageMagick/files/11956331/david.tar.gz)

Converted `david_8192.gray`:
![david_8192](https://github.com/ImageMagick/ImageMagick/assets/39885272/ad430c14-c724-4a18-92b3-37eea797b697)

Converted `david_4838.gray` using rawpixels:
![david_4838](https://github.com/ImageMagick/ImageMagick/assets/39885272/db53cbbe-aeeb-4d38-8f88-010627b545e5)

Original source image:
![david](https://github.com/ImageMagick/ImageMagick/assets/39885272/eb991cdc-5507-43c2-b202-128e00783bdf)

**Comment by circl-lastname** [comment]
After a closer look, I've found that most likely it expects the file to be 4837.5 bytes long, and if there's even a nybble more than that, it attempts to read another channel, which ends after 4 bits causing the error, I also have seen this error in the RGB coder just now.

**Comment by urban-warrior** [comment]
You need 23 bytes to cover a scan line of 180 pixels at depth 1.  The specified height is 512, 512*23 is 11776 bytes.  The file is only 4838 bytes suggesting the file is corrupt.  Another possibility is that you set the dimensions to 180x512.  Is that the expected columns and rows?

**Comment by circl-lastname** [comment]
Hello, 
The rows of pixels are not aligned to a byte, and no data is missing when reading the file as such, as seen by the rawpixels example. I believed it was not necessary to align the rows, however I will admit I don't have much experience in low bit depth graphics like these

**Comment by urban-warrior** [comment]
ImageMagick pads the rows so rather than 22.5 bytes per row, it uses 23.  ImageMagick pads the last byte in the row.  It would of course correctly read any image at depth 1 with a row length divisible by 8 or if the last byte of the row is padded or if the raw image was created by ImageMagick.

**Comment by circl-lastname** [comment]
I understand, is there any possibility of allowing unpadded rows or is that outside the scopeof ImageMagick?

**Comment by snibgo** [comment]
The 180x215 file can be read like this. Note that `180x215=38700`.
```
magick -size 38700x1 -depth 1 david_4838.gray -crop 180x1 +repage +write info: -append +repage x.png
```

**Comment by circl-lastname** [comment]
Thanks, considering there is a way to read such a file, and how it seems it is pretty universally accepted that row of pixels in 1-bit images are byte-aligned, I will close it as resolved for now

**Comment by urban-warrior** [comment]
ImageMagick is designed to handle up to tera-pixel images and by default assumes scanline padding to facilitate reading large images one scanline at a time.  However, to support your use case, we  now support an option to reshape the image:

```
$ magick -depth 1 -size 38700x1  gray:image.bin -reshape 180x215 image.png
```

**Comment by circl-lastname** [comment]
Thank you, that is good to now
