### ISSUE TITLE
[Magick++] border problems

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#647]
Two problems with creating borders in Magick++:

 - If the image background is transparent, the entire background is filled rather than just the border. This used to work so this was introduced fairly recently (within the last year).
 - If the border offset (the `+x+y` part is not working at all (never has)

I am using `ImageMagick 6.9.9.5`.

```cpp
XPtrImage magick_image_border( XPtrImage input, const char * color, const char * geometry){
  XPtrImage output = copy(input);
  //need to set color before adding the border!
  if(strlen(color))
    for_each ( output->begin(), output->end(), Magick::borderColorImage(color));
  if(strlen(geometry))
    for_each ( output->begin(), output->end(), Magick::borderImage(Geom(geometry)));
  return output;
}
```

Here is an example image:

![frink](https://jeroen.github.io/images/frink.png)

After setting a `10x10` border `red` it looks like this:

![frinkout](https://user-images.githubusercontent.com/216319/28994893-e8ff7d12-79d9-11e7-8fae-643921079e8d.png)

**Comment by mikayla-grace** [comment]
Can you post a complete demo of the problem.  We'll use it to reproduce the problem and to ensure our patch works properly.

**Comment by jeroen** [comment]
Here is a demo of the transparency problem:

```cpp
#include <Magick++.h>

int main(){
  Magick::Image image("logo:");
  image.transparent("white");
  image.borderColor("red");
  image.border("10x10");
  image.write(std::string("test.png"));
}

```

![test](https://user-images.githubusercontent.com/216319/29317240-4735ca96-81cb-11e7-9cf2-89ff4fb0cd38.png)

And here a demo to show that the geom offset is ignored:

```cpp
#include <Magick++.h>

int main(){
  Magick::Image image("logo:");
  image.borderColor("red");
  image.border("10x10+5+5");
  image.write(std::string("test.png"));
}
```

![test](https://user-images.githubusercontent.com/216319/29317306-9829f2d8-81cb-11e7-9eff-01ebc56d461f.png)

**Comment by urban-warrior** [comment]
You likely want Frame().  Border() only accepts width / height.  Frame() accepts width / height / x-offset / y-offset.

**Comment by jeroen** [comment]
I don't think that is correct. A frame give something completely different (see below). Note that `border()` used to work a few versions ago (at least with the transparency) so I think there really is a bug.

![test](https://user-images.githubusercontent.com/216319/29317848-1abc775a-81ce-11e7-9a53-e6b7f60a0a77.png)

**Comment by urban-warrior** [comment]
Border() is sensitive to the composite operator which defaults to Over.  Try setting the composite operator to Copy instead.

**Comment by jeroen** [comment]
@urban-warrior thank you that fixes the transparency problem indeed! Is there a overview somewhere to see which methods are sensitive to which attributes?

**Comment by urban-warrior** [comment]
There should be-- but there is not.   We have the standard open-source excuse-- too much to do, too little time, not enough volunteers.
