### ISSUE TITLE
-channel-fx meta10

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#6471]
### Is your feature request related to a problem? Please describe.

With IM v7.1.1-13 (Beta), the following Windows BAT command ...
```
magick ^
  xc:sRGBa(10%%,20%%,30%%,0.5) ^
  -channel-fx "r=>meta,g=>meta1,b=>meta2" ^
  -channel-fx "r=>meta3,g=>meta4,b=>meta5" ^
  -channel-fx "r=>meta6,g=>meta7,b=>meta8" ^
  -channel-fx "r=>meta9,g=>meta10,b=>meta11" ^
  x.tiff
```
... fails with the message:
```
magick: unrecognized channel type `meta10' @ error/channel.c/ChannelFxImage/357.
```

The problem is in `option.c`, the array `PixelChannelOptions[]`, which defines channels only up to `Meta9`. The array `ChannelOptions[]` defines channels up to `Meta15`.

### Describe the solution you'd like

I suggest that `PixelChannelOptions[]` is extended to match `ChannelOptions[]`. The diff is:
```
--- "snibgo\\option20230708.c"	2023-07-04 14:51:18.304361100 +0100
+++ "MagickCore\\option.c"	2023-07-08 15:59:51.370013700 +0100
@@ -1909,6 +1909,12 @@
     { "Meta7", MetaPixelChannels+7, UndefinedOptionFlag, MagickFalse },
     { "Meta8", MetaPixelChannels+8, UndefinedOptionFlag, MagickFalse },
     { "Meta9", MetaPixelChannels+9, UndefinedOptionFlag, MagickFalse },
+    { "Meta10", MetaPixelChannels+10, UndefinedOptionFlag, MagickFalse },
+    { "Meta11", MetaPixelChannels+11, UndefinedOptionFlag, MagickFalse },
+    { "Meta12", MetaPixelChannels+12, UndefinedOptionFlag, MagickFalse },
+    { "Meta13", MetaPixelChannels+13, UndefinedOptionFlag, MagickFalse },
+    { "Meta14", MetaPixelChannels+14, UndefinedOptionFlag, MagickFalse },
+    { "Meta15", MetaPixelChannels+15, UndefinedOptionFlag, MagickFalse },
     { "O", AlphaPixelChannel, UndefinedOptionFlag, MagickFalse },
     { "R", RedPixelChannel, UndefinedOptionFlag, MagickFalse },
     { "ReadMask", ReadMaskPixelChannel, UndefinedOptionFlag, MagickFalse },
```

### Describe alternatives you've considered

A more extensive change, to both arrays, would permit CLI access up to Meta54.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
