### ISSUE TITLE
New Reshape option on command line options page does not work

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#6472]
### ImageMagick version

7.1.1.13

### Operating system

MacOS

### Operating system, version and so on

Ventura

### Description

On the Command Line Options page at https://imagemagick.org/script/command-line-options.php, the option for Reshape in the selector list does not jump to its description section further down the page.

### Steps to Reproduce

See above

### Images

None

**Comment by dlemstra** [comment]
Thanks for reporting this Fred. I have updated the page but it will take a while before this will show up on the size.
