### ISSUE TITLE
Insufficient Image Data In File

### ISSUE THREAD

**Issue by ZCWei51** [ImageMagick/ImageMagick#6499]
### ImageMagick version

7.1.1-12

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04.6 LTS

### Description

# Description
Using ImageMagick 7.1.1-12 with command as below receiving error message:
```
magick id:000000,3525685,sig:11,src:001744,op:havoc,rep:4 /dev/null

> magick: insufficient image data in file `id:000000,3525685,sig:11,src:001744,op:havoc,rep:4' @ error/dib.c/ReadDIBImage/674.
```

# System Configuration
- ImageMagick 7.1.1-12
- Ubuntu 20.04 LTS

### Steps to Reproduce

# Steps to Reproduce
Execute this command on the provided file:
```
magick id:000000,3525685,sig:11,src:001744,op:havoc,rep:4 /dev/null
```

### Images

[id_000000,3525685,sig_11,src_001744,op_havoc,rep_4.zip](https://github.com/ImageMagick/ImageMagick/files/12092985/id_000000.3525685.sig_11.src_001744.op_havoc.rep_4.zip)

**Comment by dlemstra** [comment]
Your file does not contain enough data and is corrupt? Why did you open this issue?

**Comment by ZCWei51** [comment]
Hello, thank you very much for replying.
I'm using AFL-go for fuzzy testing and this file is reported as a UNIQUE CRASH file, so is this kind of output an error on version 7.1.1-12?
