### ISSUE TITLE
FL32 RGBA image read looks like scrambled RGB 

### ISSUE THREAD

**Issue by RichardKirk** [ImageMagick/ImageMagick#6506]
### ImageMagick version

7.1.1-13 Q16-HDRI x86_64 21276 

### Operating system

MacOS

### Operating system, version and so on

Ventura 13.4 on Intel Mac 2.6 GHz 6-Core Intel Core i7

### Description

RGB and RGBA FL32 files written by 'convert' seem fine. I have generated both, and inspected them with my own tools. I can read RGB FL32 files, but the RGBA FL32 files appear as scrambled RGB.  PNG RGBA file formats read correctly on my machine. The read and wrote code seems to support from 1 to 4 channels, and it seems to make sense.

FL32 is a very simple 32-bit float format used by FilmLight for image dumps that you guys have kindly supported. Baselight 6.0 now supports alpha throughout, so the RGBA files are going to be used. I was adding an option for using ImageMagick for file reads and writes in a tool of mine, and I spotted this. I upgraded to the latest build using homebrew today.

### Steps to Reproduce

convert macbeth.fl32 macbeth.png
View Macbeth.png. File is RGB. Contents looks like scrambled RGB.

If RGB.png is any 3-channel PNG file, then...
convert RGB.png RGB temp.fl32
convert temp.fl32 temp.png
..g gives a temp.png the looks like the original.

### Images

[macbeth.fl32.zip](https://github.com/ImageMagick/ImageMagick/files/12136502/macbeth.fl32.zip)

**Comment by dlemstra** [comment]
Closing this as a duplicate. Next time please edit your issue instead.
