### ISSUE TITLE
Cannot build from source with latest jpeg-turbo (3.0.0)

### ISSUE THREAD

**Issue by adamperrry** [ImageMagick/ImageMagick#6514]
### ImageMagick version

7.1.1-14

### Operating system

MacOS

### Operating system, version and so on

Ventura, M1

### Description

[The latest version of jpeg-turbo](https://github.com/libjpeg-turbo/libjpeg-turbo/releases/tag/3.0.0) causes ImageMagick builds from source to fail due to use of deprecated functions. Here are the errors:

```bash
coders/jpeg.c:1214:31: error: no member named 'process' in 'struct jpeg_decompress_struct'
  image->interlace=jpeg_info->process == JPROC_PROGRESSIVE ?
                   ~~~~~~~~~  ^
coders/jpeg.c:1214:42: error: use of undeclared identifier 'JPROC_PROGRESSIVE'
  image->interlace=jpeg_info->process == JPROC_PROGRESSIVE ?
                                         ^
coders/jpeg.c:1216:33: error: no member named 'process' in 'struct jpeg_decompress_struct'
  image->compression=jpeg_info->process == JPROC_LOSSLESS ?
                     ~~~~~~~~~  ^
coders/jpeg.c:1216:44: error: use of undeclared identifier 'JPROC_LOSSLESS'
  image->compression=jpeg_info->process == JPROC_LOSSLESS ?
                                           ^
coders/jpeg.c:2485:11: error: call to undeclared function 'jpeg_simple_lossless'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          jpeg_simple_lossless(jpeg_info,predictor,point_transform);
          ^
coders/jpeg.c:2485:11: note: did you mean 'jpeg_enable_lossless'?
/opt/homebrew/include/jpeglib.h:995:14: note: 'jpeg_enable_lossless' declared here
EXTERN(void) jpeg_enable_lossless(j_compress_ptr cinfo,
```

I haven't dug into all of these, but I know for sure that `jpeg_simple_lossless()` was [renamed to `jpeg_enable_lossless()`](https://github.com/libjpeg-turbo/libjpeg-turbo/commit/af618ffe093de6563fc61355d4d28f2038ec6e9e).

Would be great to have this compatible across versions so we can enable JPEG support when building from source. As a workaround for now, I think we'll just build the older version of `jpeg-turbo` since homebrew doesn't maintain older versions.

### Steps to Reproduce

Build from source with `jpeg-turbo` v3.0.0. This seems to be the default version when installing `jpeg` on an M1 Ventura via homebrew.

**Comment by adamperrry** [comment]
Update - it seems I had my `LDFLAGS` and `CPPFLAGS` in the wrong order, and now I'm correctly pointing to the `jpeg` library installed by brew. However, this would still be good to update or guard against, since it's only a matter of time before jpeg-turbo is the standard.

**Comment by dlemstra** [comment]
There are already guards against that method being called when using libjpeg-turbo: https://github.com/ImageMagick/ImageMagick/blob/edf7a2a8c7f5aa698f07ee93dfe09463bdeb27a5/coders/jpeg.c#L2629.
