### ISSUE TITLE
Lossless APNG to WebP is not lossless

### ISSUE THREAD

**Issue by Kuuuube** [ImageMagick/ImageMagick#6523]
### ImageMagick version

7.1.1-4

### Operating system

Windows

### Operating system, version and so on

Win10 22H2 19045.3208

### Description

When converting from apng to webp, passing `-define webp:lossless=true` appears to be ignored.

Example (webp, apng):

![webp_apng](https://github.com/ImageMagick/ImageMagick/assets/61125188/0c24f8aa-4b93-4c1b-94fd-3e8ff5d617c9)

Non-animated png to webp works losslessly without issue. This only applies to animations.

### Steps to Reproduce

Full command I used:

```
convert apng:input_file.png -define webp:lossless=true -coalesce output_file.webp
```

### Images

Input apng and output webp from my conversion: [input_output_files.zip](https://github.com/ImageMagick/ImageMagick/files/12209990/input_output_files.zip)

**Comment by urban-warrior** [comment]
We're using ImageMagick 7.1.1-15 with libwebp 1.3.1 under Linux.  We get zero distortion suggesting the conversion is lossless as expected:

```
$ convert apng:input_file.png input%02d.png
$ convert apng:input_file.png -define webp:lossless=true -coalesce output_file.webp
$ convert output_file.webp output%02d.png
$ compare -metric rmse output00.png input00.png null:
0 (0)
$ compare -metric rmse output01.png input01.png null:
0 (0)
$ compare -metric rmse output02.png input02.png null:
0 (0)
$ compare -metric rmse output03.png input03.png null:
0 (0)
$ compare -metric rmse output04.png input04.png null:
0 (0)
$ compare -metric rmse output05.png input05.png null:
0 (0)
```

If you do not get the same results, we'll need @dlemstra to determine if there is an issue with libwebp built under Windows.

**Comment by Kuuuube** [comment]
Checked ImageMagick 7.1.1-15 (should've done that first sorry). It does still happen there.

Running the commands you have run I do get the same outputs (showing no diff and all)... However, the `input%02d.png` files contain the same distortion making it compare already distorted inputs (not matching the real apng input) to the outputs. 

It looks like even extracting the frames apng to png has this issue. 

I can also replicate this by converting png to png but telling imagemagick that the first png is an apng:

```
$ convert apng:input_frame.png output_frame.png
$ compare -metric rmse input_frame.png output_frame.png null:
1480.7 (0.022594)
```

Files from the above test: [input_output_frame.zip](https://github.com/ImageMagick/ImageMagick/files/12210559/input_output_frame.zip)

**Comment by Kuuuube** [comment]
Pulled up a linux vm. I also get the same issues there.

**Comment by fmw42** [comment]
You have not said what version of libwebp you are using!!!  If not the latest, then update

**Comment by Kuuuube** [comment]
`convert -list format` shows `     WEBP* rw+   WebP Image Format (libwebp 1.3.1 [020F])`

I believe that should be the correct version.

**Comment by Kuuuube** [comment]
Build some old versions to check if this was a regression and 7.1.0-0 worked. Bisected and ended up with 7.1.0-20 having the issue and 7.1.0-19 not having the issue. I'll go bisect to the specific commit tomorrow if this isn't enough information.

**Comment by Kuuuube** [comment]
This regression was caused by 14ee32548b8f9143317ebc30436f7adfa7e42c78. I would try to fix this myself but I'm not sure how to do so without breaking #4704 again so I'll leave it to you guys.

**Comment by urban-warrior** [comment]
Edit your `delegate.xml` file and add `-lossless 1` after the `-vcodec webp` option.  Does that resolve the issue?

**Comment by Kuuuube** [comment]
There doesn't seem to be a `-vcodec webp` in the default `delegates.xml` but trying to add it and `-lossless 1` (or one or the other) to any lines that webp or png appear doesn't fix the output.

Is there a specific version of `delegates.xml` that I should be using to test this? Or a line that isn't included by default that should be added altogether?

**Comment by Kuuuube** [comment]
Ah, I see you pushed a change to fix this. I'm not sure what's up with the delegates.xml stuff but I just built latest (9cd23d18e9d81103580d8417be57dd529a3a58bf) and it works perfectly. Thank you for the fix!
