### ISSUE TITLE
Provide thread safe API to access pixel data that is not dependent on OpenMP

### ISSUE THREAD

**Issue by Cyriuz** [ImageMagick/ImageMagick#6545]
### Is your feature request related to a problem? Please describe.

Based on my question [here](https://github.com/ImageMagick/ImageMagick/discussions/6539) I found it pretty unintuitive that the cache view depends on OpenMP to be used from multiple threads.

### Describe the solution you'd like

The best would of course be if the current api could be threading library agnostic but if that is not possible just a way to set the `number_threads` that is used in `AcquirePixelCacheNexus` instead of `GetOpenMPMaximumThreads()`

### Describe alternatives you've considered

I assume I could write my own cache view to work around the issue but it seems like quiet some work. If there's another better way to achieve this just let me know!

**Comment by urban-warrior** [comment]
Cache views do not depend on OpenMP.  Cache views conveniently leverage OpenMP if its available.  You can disable OpenMP by not enabling the feature in ImageMagick build or you can set the thread limit to one.  When you do, you can then manage any cache views yourself in your codeset, including in  a threaded environment.   As an example use case, you could allocate 16 threads and each of these threads would allocate a separate cache view.  The cache view would be responsible for 64 rows of a 1024 row image, e.g. thread 1, rows 0-63; thread 2, rows 64-127, etc.

**Comment by Cyriuz** [comment]
Thank you for the answer! I'm a little bit confused but if I understand correctly the cache_view->nexus_info is just a list for convenience in the OpenMP case? If that's the case and it is safe to just allocate one view per thread without significant performance loss then I will do that.

When I wrote the issue I was a bit too deep in my debugging and forgot that the actual issue that I was so confused about is that the `GetMagickNumberThreads` and `GetOpenMPMaximumThreads` differs (because I didn't explicitly set it I assume now) and that `GetCacheViewAuthenticPixels` uses OpenMP to get the thread id, which is always 0 for me, so it used the same info for all threads.

I don't want to disable OpenMP since I want ImageMagick to use it for internal operations.

**Comment by urban-warrior** [comment]
It is possible to mix OpenMP and POSIX threads (often referred to as pthreads) in the same program. However, it requires careful management of thread creation, synchronization, and resource sharing to ensure that both threading libraries work together effectively.

**Comment by Cyriuz** [comment]
Maybe I can suggest to just add a little note in the otherwise great [documentation](https://imagemagick.org/script/architecture.php#threads), that the provided examples are only for OpenMP and that the view needs to be allocated per thread otherwise?

Thanks for answering, I'll close the issue.
