### ISSUE TITLE
Avoid GraphicsAlphaBits for PDF conversion

### ISSUE THREAD

**Issue by dpthurst** [ImageMagick/ImageMagick#6561]
### ImageMagick version

7.1.1-16

### Operating system

Linux

### Operating system, version and so on

Debian GNU/Linux unstable

### Description

PDF conversion call ghostscript with the parameters GraphicsAlphaBits and TextAlphaBits set to 4 (unless you turn off anti-aliasing with `magick +antialias`). This causes problems with numerous PDF files, at least with ghostscript version 10+. (See https://bugs.ghostscript.com/show_bug.cgi?id=707023 for a list of some of the reported issues on their bugzilla, and https://github.com/ImageMagick/ImageMagick/discussions/6557 for an ImageMagick user encountering this.) As reported in those bugs, the `GraphicsAlphaBits` feature of gs is a poor fit for the PDF 1.4 transparency model, and is deprecated by the gs developers; ImageMagick should not be using it.

This can't be fixed by editing `delegates.xml`, since the parameter is passed in as an integer in `coders/pdf.c`. I'm not sure exactly when or if one should use `GraphicsAlphaBits` at all (including for other formates delegated to gs), but it seems to be wrong for most PDF files around.

I've attached my own image that encountered an issue for completeness.

### Steps to Reproduce

% magick -verbose -antialias -density 300 bcp.pdf bcp-antialias.png
/tmp/magick--i_j7pzTKyc3AqNR_8iXOHGVgEGlI14b1 PAM 815x1110 815x1110+0+0 8-bit ColorSeparation CMYK 3.45106MiB 0.020u 0:00.005
bcp.pdf AI 815x1110 815x1110+0+0 16-bit ColorSeparation CMYK 3.45106MiB 0.000u 0:00.000
[ghostscript library 10.01] -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pamcmyk32' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r300x300' -dPrinted=false  '-sOutputFile=/tmp/magick--i_j7pzTKyc3AqNR_8iXOHGVgEGlI14b%d' '-f/tmp/magick-chftELPZMmPHrJfMkDMWPImnbxawQxTq' '-f/tmp/magick-wFC8OGk2LdJeSE9qVVzqtbHhzN3bPLwI'writing raw profile: type=xmp, length=35554
bcp.pdf=>bcp-antialias.png AI 815x1110 815x1110+0+0 16-bit ColorSeparation CMYK 3.45106MiB 0.560u 0:00.373
% magick -verbose +antialias -density 300 bcp.pdf bcp-noaa.png
/tmp/magick-CMZHQlSqChWcxyjKGVIDc4FS8CEBtO731 PAM 815x1110 815x1110+0+0 8-bit ColorSeparation CMYK 3.45106MiB 0.020u 0:00.006
bcp.pdf AI 815x1110 815x1110+0+0 16-bit ColorSeparation CMYK 3.45106MiB 0.010u 0:00.000
[ghostscript library 10.01] -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pamcmyk32' -dTextAlphaBits=1 -dGraphicsAlphaBits=1 '-r300x300' -dPrinted=false  '-sOutputFile=/tmp/magick-CMZHQlSqChWcxyjKGVIDc4FS8CEBtO73%d' '-f/tmp/magick-KM26n54Y3T5HBeo6av3AwBXbPmB3frvM' '-f/tmp/magick-Z7tm6cV1jqOFzx4xFRoOUp6Bn6QfgFRV'writing raw profile: type=xmp, length=35554
bcp.pdf=>bcp-noaa.png AI 815x1110 815x1110+0+0 16-bit ColorSeparation CMYK 3.45106MiB 0.470u 0:00.294

### Images

[bcp.pdf](https://github.com/ImageMagick/ImageMagick/files/12352535/bcp.pdf)
![bcp-antialias](https://github.com/ImageMagick/ImageMagick/assets/13771964/31e44972-1323-40d7-9c82-445ec9193889)
![bcp-noaa](https://github.com/ImageMagick/ImageMagick/assets/13771964/04262052-39f6-440b-8bbc-5b505f609b54)

**Comment by dpthurst** [comment]
Update: It seems GraphicsAlphaBits is more supported than I thought, as per the discussion in the bug I linked to. As Ken Sharp writes there:

> We'd rather people didn't use it, and instead used the downscaling devices to do anti-aliasing after rendering, instead of during rendering. But the consensus of opinion internally is still that it can be made to work ...

So I'd make this a wishlist bug, to switch to one of the downscaling devices instead (eg png16malpha with `DownScaleFactor=4`)

**Comment by urban-warrior** [comment]
We typically recommend supersampling, for example,

```
magick -verbose -density 1200 bcp.pdf -resize 25% bcp-antialias.png
```
