### ISSUE TITLE
Write Error on Large TIFF Blob in Memory-Intensive Programs

### ISSUE THREAD

**Issue by MrAnderson1971** [ImageMagick/ImageMagick#6562]
### ImageMagick version

7.1.1 Q8

### Operating system

Windows

### Operating system, version and so on

Windows 10/11

### Description

In a memory-intensive scenario on Windows 10/11, when attempting to write a large TIFF image to a blob, a Magick::ErrorCoder is thrown with the error message:

ConsoleApplication4.exe: Write error at scanline 5792. `TIFFAppendToStrip' @ error/tiff.c/TIFFErrors/598
This issue makes it difficult to determine if it's a memory-related problem or something else.
![MicrosoftTeams-image](https://github.com/ImageMagick/ImageMagick/assets/67478505/36edc15a-4532-464d-aa3f-5e315ab2f4de)
Expected Behavior:
The image should be written to the Magick::Blob without any issues, and in the event of an error, a clearer message detailing the exact problem would be beneficial.

Actual Behavior:
The program throws a Magick::ErrorCoder with the error message:
ConsoleApplication4.exe: Write error at scanline 5792. `TIFFAppendToStrip' @ error/tiff.c/TIFFErrors/598

### Steps to Reproduce

Steps to Reproduce:

Consume a significant amount of system memory. In our standalone program, we allocated 1 GB on the heap.
Read an image (in our case bliss.jpg).
Resize the image to larger dimensions (8192x6144).
Change the image's format to TIFF. This does not occur for other image types.
Attempt to write the image to a Magick::Blob.

```
#include <Magick++.h>
#include <iostream>

int main()
{
   try {
      Magick::InitializeMagick(nullptr);
      char* heap = new char[1000 * 1024 * 1024]; // consume some memory
      Magick::Image image("bliss.jpg");
      image.resize("8192x6144");
      image.magick("TIFF");
      Magick::Blob blob;
      image.write(&blob);
      delete[] heap;
      return 0;
   }
   catch (const Magick::ErrorCoder& e) {
      std::cerr << e.what() << std::endl;
      return 1;
   }
}
```

**Comment by snibgo** [comment]
Your program builds and runs without complaint on my Windows 11 laptop, with 16 GB memory, ImageMagick 7.1.1-5 (Beta) Q32-HDRI x86_64, using the Gnu toolchain.

**Comment by MrAnderson1971** [comment]
> Your program builds and runs without complaint on my Windows 11 laptop, with 16 GB memory, ImageMagick 7.1.1-5 (Beta) Q32-HDRI x86_64, using the Gnu toolchain.

Where can I find the beta version?

**Comment by snibgo** [comment]
That was the current version when I last downloaded and built the IM source, against which I built your program.

**Comment by dlemstra** [comment]
Are you compiling the program in 64-bit? With 33-bit you cannot allocate a lot of memory.

**Comment by MrAnderson1971** [comment]
> Are you compiling the program in 64-bit? With 33-bit you cannot allocate a lot of memory.

32 bit yes

**Comment by dlemstra** [comment]
I would advise you to switch to 64-bit then so you can allocate more than 2GB.

**Comment by MrAnderson1971** [comment]
> I would advise you to switch to 64-bit then so you can allocate more than 2GB.

This is a test case to reproduce the crash. The crash was first seen while testing an application calling many different ImageMagick methods. The application must remain 32-bit, so we can't switch to the 64-bit libraries. The test code above is the simplest case we could create demonstrating the crash.

The issue appears to be specific to the TIFF coder. It doesn't occur with BMP, for example.

**Comment by urban-warrior** [comment]
The exception suggests the strip size is too large.  Try setting the property `tiff:rows-per-strip=96`.  Does that work?

Also see https://imagemagick.org/script/architecture.php#tera-pixel.
