### ISSUE TITLE
can MagickPingImageBlob get webp image's "number_scenes" parameter faster?

### ISSUE THREAD

**Issue by t00350320** [ImageMagick/ImageMagick#6572]
### Is your feature request related to a problem? Please describe.

magic version: 7.1.0-4
case description:
we only care about  the original image's meta data . 
So,
get an webp image's meta info on top of MagickPingImageBlob function
get some meta datas such as MagickGetNumberImages .

here is the meta data info we got:
[type:WEBP, w:720, h:960, size:1800692, quality:0, number_scenes:68, depth:8,dst_processed:1]

the MagickPingImageBlob cost time is about 0.5s
2023-08-21 11:00:05:913:[TBL][INFO-]<IMAGE_SDK>:src/tbl_image_im.cpp:00260:im_ping_image_blob:begin
2023-08-21 11:00:06:570:[TBL][INFO-]<IMAGE_SDK>:src/tbl_image_im.cpp:00274:im_ping_image_blob:end

### Describe the solution you'd like

so, can we extract  the meta faster ? 100ms

thanks a lot !!!

### Additional context
our webp image is here
[webp1.zip](https://github.com/ImageMagick/ImageMagick/files/12391342/webp1.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce the issue and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
