### ISSUE TITLE
Cropping with "-gravity Center" not working as advertised

### ISSUE THREAD

**Issue by dpthurst** [ImageMagick/ImageMagick#6577]
### ImageMagick version

7.1.1-16

### Operating system

Linux

### Operating system, version and so on

Debian GNU/Linux unstable 6.4.4-3 (2023-08-08)

### Description

Cropping with "-gravity Center" does not work as advertised in the documentation.

### Steps to Reproduce

 The simplest example is the one from the manual:

> `% magick rose: -gravity Center -crop 32x32+0+0 +repage crop_center.png`
> `% file crop_center.png`
> `crop_center.png: PNG image data, 13 x 25, 8-bit/color RGB, non-interlaced`

![crop_center](https://github.com/ImageMagick/ImageMagick/assets/13771964/61e24e84-9a47-4b51-a34d-54f5f81fb6e3)

**Comment by dpthurst** [comment]
Yes, I'm aware I'm using a development version. Is this not the development bug tracker? The version I compiled passed 'make check', so I assumed it was fair game.

In any case, this has since been fixed, perhaps by commit 7a159d69b9908128ae38545041b89211ad1a3828

**Comment by fmw42** [comment]
This is the forum for all versions, but mostly for releases.  Why would you use a developmental version, unless you are testing some new code?  Reporting other existing code bugs should be done using the released version otherwise you risk reporting a bug on something that is under development.
