### ISSUE TITLE
open gif hangs with 100% CPU

### ISSUE THREAD

**Issue by razsh** [ImageMagick/ImageMagick#658]
Try `identify giflood.gif`

![giflood](https://user-images.githubusercontent.com/3828260/29039633-b475970c-7bb4-11e7-9691-028465e6a83e.gif)

https://user-images.githubusercontent.com/3828260/29039633-b475970c-7bb4-11e7-9691-028465e6a83e.gif

**Comment by mikayla-grace** [comment]
This is a legitimate GIF image and ImageMagick is behaving properly.  We can read it on our system without any complaint.  It creates an image sequence of 40,000 1x1 frames.  You can limit the number of frames in a sequences like this: 

```
$ identify 'giflood.gif[0-49]'
```
Here we limit the number of frames in an image sequence to 50.

**Comment by ThomasLabstep** [comment]
Can reproduce this bug on our AWS EC2 tiny Load balanced cluster.

It's been bugging us a lot these past days.

Any other standard 3Mb GIF works fine.

Example: https://giphy.com/gifs/big-hero-6-UYgK6kSXD1WDu

We have no idea how to fix this...
