### ISSUE TITLE
Windows Build Not Working for debug Binaries

### ISSUE THREAD

**Issue by jaideep746** [ImageMagick/ImageMagick#6581]
### ImageMagick version

7

### Operating system

Windows

### Operating system, version and so on

windows 11, x64 bit configuration intel i7

### Description

I Am trying to Build Imagemagick from source and followed the readme file and cloned all the third parties dependencies. 
then I run the configure.exe and selected the properties as static run time Dlls , since I only need the lib file to be included in my project. After the configure.exe i got the visualstaticMTD.sln solution, when i build the solution in x64 debug mode, Certain third party projects are not build , eg Corehighway, corejpeg-xl and its relevant projects are showing errors in build.
further when I tried including there libs in my project , the Magick++.h files need to include corejp2 llib as a dependencies, but no such project exists. I have added the StaticMagick as my preprocessor. 

### Steps to Reproduce

E0304 no instance of overloaded function "hwy::N_SSE2::Combine" matches the argument list	CORE_highway	C:\Users\jkaushal\Desktop\gitclone\ImageMagick-Windows-7\highway\hwy\ops\x86_256-inl.h

E0312	no suitable user-defined conversion from "hwy::N_SSE2::Vec128<uint8_t, 16Ui64>" to "hwy::N_SSE2::Vec256<uint8_t>" exists CORE_highway C:\Users\jkaushal\Desktop\gitclone\ImageMagick-Windows-7\highway\hwy\ops\x86_256-inl.h

C2672	'BitCast': no matching overloaded function found	CORE_highway	c:\users\jkaushal\desktop\gitclone\imagemagick-windows-7\highway\hwy\ops\x86_256-inl.h
 some of the errors i  got while building corehighway

**Comment by dlemstra** [comment]
We are in the middle of making some changes to `configure.exe` so it might be possible that this is now breaking your setup. This looks like an error message I had earlier this week but should now be fixed. Maybe you need to update some of the dependencies?

**Comment by dlemstra** [comment]
Did updating your dependencies solve your issue? And if that did not work you will need to wait till we are done with the changes.

**Comment by dlemstra** [comment]
The name `visualstaticMTD.vcproj` is probably a typo but your steps are correct and when you open `visualstaticMTD.sln` you should be able to build the project. 

But the new information you are giving me now is the version of Visual Studio. It looks like one of the project no longer builds with VisualStudio 2017. Not sure what is happening though so I will need to investigate that.

**Comment by jaideep746** [comment]
Yeah , I am Able to build all the 60 projects in visualstaticMTD.sln , but during including these libraries in my project, core_DB_jp2.lib is missing ig, it has been defined in include.h #pragma comment (libname) , so i guess that why its including bydefalut and searching for that.
is this the one project you are talking about ??

**Comment by dlemstra** [comment]
As I said before. I will need to investigate this and I don't know when I will do that. I will get back to this issue when I have more information.

**Comment by jaideep746** [comment]
Sure Sir , waiting for your response.

**Comment by jaideep746** [comment]
I would Like to share a bug with you, Actually after renaming the jp2 to jasper, the Magick/include.h has jp2 delegate name set as CORE_DB_jp2.lib but it has to be CORE_DB_jasper.lib. 
Kindly Look into this.

**Comment by dlemstra** [comment]
Thanks for reporting that mistake. I just pushed a patch to correct that name.

**Comment by jaideep746** [comment]
Great.
Thanks for addressing my queries.
