### ISSUE TITLE
ImageMagick-7.1.1-15 RPM is not compatible with RHEL 9.2 stack

### ISSUE THREAD

**Issue by TooManyUsersToFindALogin** [ImageMagick/ImageMagick#6582]
### ImageMagick version

7.1.1-15

### Operating system

Linux

### Operating system, version and so on

RHEL 9.2

### Description

Your Linux Binary Release RPMs are not compatible with RHEL 9.2 distributions. Using EPEL repository is not a workaround. 
The installation fails:

```
$ docker run -it --name dest almalinux:latest
# cd /tmp
# dnf install ./ImageMagick-7.1.1-15.x86_64.rpm ./ImageMagick-libs-7.1.1-15.x86_64.rpm 
Last metadata expiration check: 0:01:00 ago on Thu Aug 24 11:40:09 2023.
Error: 
 Problem 1: conflicting requests
  - nothing provides libgs.so.10()(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
  - nothing provides libjxl.so.0.7()(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
  - nothing provides libjxl.so.0.7(JXL_0)(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
  - nothing provides libjxl_threads.so.0.7()(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
  - nothing provides libjxl_threads.so.0.7(JXL_0)(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
  - nothing provides libm.so.6(GLIBC_2.35)(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
  - nothing provides libraw_r.so.23()(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
 Problem 2: package ImageMagick-7.1.1-15.x86_64 requires libMagickCore-7.Q16HDRI.so.10()(64bit), but none of the providers can be installed
  - package ImageMagick-7.1.1-15.x86_64 requires libMagickWand-7.Q16HDRI.so.10()(64bit), but none of the providers can be installed
  - package ImageMagick-7.1.1-15.x86_64 requires libMagickWand-7.Q16HDRI.so.10(VERS_10.0)(64bit), but none of the providers can be installed
  - package ImageMagick-7.1.1-15.x86_64 requires ImageMagick-libs(x86-64) = 7.1.1-15, but none of the providers can be installed
  - conflicting requests
  - nothing provides libgs.so.10()(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
  - nothing provides libjxl.so.0.7()(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
  - nothing provides libjxl.so.0.7(JXL_0)(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
  - nothing provides libjxl_threads.so.0.7()(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
  - nothing provides libjxl_threads.so.0.7(JXL_0)(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
  - nothing provides libm.so.6(GLIBC_2.35)(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
  - nothing provides libraw_r.so.23()(64bit) needed by ImageMagick-libs-7.1.1-15.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

The following librairies are missing and are not available for the RHEL 9.2 distribution:
- [libgs.so.10](https://pkgs.org/search/?q=libgs) is not available for RHEL 9.2, only on Fedora 38
- [libm.so.6](https://pkgs.org/search/?q=libmng)(GLIBC_2.35) is compiled on GLIBC 2.35, but RHEL 9.2 uses GLIBC 2.34, it will be usable on Fedora 38 based on GLIBC 2.37

```
# /lib64/libc.so.6
GNU C Library (GNU libc) stable release version 2.34.
```
- [libraw_r.so.23](https://pkgs.org/search/?q=LibRaw) only available on Fedora 38, not on RHEL 9

Depending on your choices (vulnerabilities) you may target only latest stacks and up to date distributions like Fedora 38. 

### Steps to Reproduce

On a Docker-enabled machine, launch a RHEL 9.2 Linux distribution docker container 
```
$ docker run -it --name dest almalinux:latest
```
[download your RPMs](https://imagemagick.org/script/download.php)

In a shell/CMD console of the host machine copy those files to the _dest_ container

```
cd Download
docker cp ImageMagick-libs-7.1.1-15.x86_64.rpm dest:/tmp
docker cp ImageMagick-7.1.1-15.x86_64.rpm dest:/tmp
```

Then proceed with the _dest_ container operations:

```
# cd /tmp
# dnf install ./ImageMagick-7.1.1-15.x86_64.rpm ./ImageMagick-libs-7.1.1-15.x86_64.rpm
```

You will get the given diagnostic. 

Finally check the availability of the missing libraries with [pkgs.org](https://pkgs.org/).

**Comment by dlemstra** [comment]
This looks like a duplicate of #6540?

**Comment by urban-warrior** [comment]
We'll correct the documentation.  In the mean-time, RPM's of the latest versions of ImageMagick library are available in [Remi](https://blog.remirepo.net/post/2023/04/27/ImageMagick-and-imagick-extension) repository for Fedora and Enterprise Linux (RHEL, Alma, CentOS, Rocky, and other clones).

**Comment by NadunW** [comment]
Hi, 

Even I add remi, I still get similar errors.
