### ISSUE TITLE
-mask bug

### ISSUE THREAD

**Issue by sunnytomy** [ImageMagick/ImageMagick#6583]
### ImageMagick version

7.1.1-15

### Operating system

Windows

### Operating system, version and so on

10

### Description

I tryied this: magick rose: -mask rose_bg_mask.png -modulate 110,100,33.3  +mask rose_blue.png from the official tutorial example and got the following message: magick: option deprecated, unable to execute `-mask' at CLI arg 2 @ error/operation.c/CLIOption/5411.

When I tried to use convert rather than magick, it worked. 

### Steps to Reproduce

magick rose: -mask rose_bg_mask.png -modulate 110,100,33.3 +mask rose_blue.png

**Comment by dlemstra** [comment]
You should use ` -read-mask` or `-write-mask` instead of `-mask` with ImageMagick 7.

**Comment by sunnytomy** [comment]
> You should use ` -read-mask` or `-write-mask` instead of `-mask` with ImageMagick 7.

Thanks, it works

**Comment by sunnytomy** [comment]
> You should use ` -read-mask` or `-write-mask` instead of `-mask` with ImageMagick 7.

Thanks, it works
