### ISSUE TITLE
Caught exception: demo: memory allocation failed during unit tests

### ISSUE THREAD

**Issue by l1gi** [ImageMagick/ImageMagick#6598]
### ImageMagick version

6.9.12-93

### Operating system

Other (enter below)

### Operating system, version and so on

Solaris-11.4.63.153.0

### Description

During `make check` I hit an issue on 32bit Sparc on recent Solaris OS:
```
@@ -52,7 +52,7 @@
 PASS: Magick++/tests/tests.tap 12
 PASS: Magick++/demo/demos.tap 1
 PASS: Magick++/demo/demos.tap 2
-PASS: Magick++/demo/demos.tap 3
+FAIL: Magick++/demo/demos.tap 3
 PASS: Magick++/demo/demos.tap 4
 PASS: Magick++/demo/demos.tap 5
 PASS: Magick++/demo/demos.tap 6
```
The log file reads:
```
PASS: Magick++/demo/demos.tap 2
Read images ...
Creating thumbnails...
  add noise ...
  add noise (blue) ...
  annotate ...
  blur ...
  blur red channel ...
  border ...
  channel ...
  charcoal ...
  composite ...
  contrast ...
  convolve ...
  crop ...
  despeckle ...
  draw ...
  edge ...
  emboss ...
  equalize ...
  explode ...
  flip ...
  flop ...
  frame ...
  gamma ...
  gaussian blur ...
  gaussian blur channel ...
  gradient ...
  grayscale ...
  implode ...
  level ...
  level red channel ...
  median filter ...
Caught exception: demo: memory allocation failed `/builds/mrehak/workspace/im/components/imagemagick/I
mageMagick-6.9.12-93/Magick++/demo/model.miff' @ error/statistic.c/StatisticImageChannel/3651
not ok
FAIL: Magick++/demo/demos.tap 3
Writing image "flip_out.miff" ...
ok
```
I don't observe this issue on Intel Platform and 64bit Sparc.

As far as I understand this is the code which triggers the message:
```
ImageMagick-6.9.12-93/magick/statistic.c:
  if (pixel_list == (PixelList **) NULL)                                                              
    {                                                                                                 
      statistic_image=DestroyImage(statistic_image);                                                  
      ThrowImageException(ResourceLimitError,"MemoryAllocationFailed");                               
    }           
```
Could you help me debug the issue, please? Should you need more info, please let me know.

### Steps to Reproduce

Run `make check` on Sparcv7 (32bit) platform.

**Comment by dlemstra** [comment]
This is probably related to not having enough memory on that machine?

**Comment by l1gi** [comment]
`Memory: 1023G phys mem, 260G free mem, 256G total swap, 256G free swap`

I could imagine the limit is its 32bit address space. Maybe openmp is trying to isolate memory spaces of the threads somehow while consuming more memory.

Should you don't have any other idea why that would happen, I am fine to close the issue.

Thanks,
m.

**Comment by urban-warrior** [comment]
Try

```
MAGICK_THREAD_LIMIT=1;make check
```

**Comment by l1gi** [comment]
That worked and verified that it is a memory problem. Thank you both for helping me find the root cause.

Closing,
m.
