### ISSUE TITLE
Preserving image properties on write

### ISSUE THREAD

**Issue by Danack** [ImageMagick/ImageMagick#66]
Hi, 

Is it currently possible, and if not please consider this a feature request, to be able to preserve image properties when ImageMagick writes an image, when using the MagickWand api?

In particular, ImageMagick normally reduces the color depth to the smallest one that can represent the image without loss. I believe currently, if you want ImageMagick to write the image with the same color-depth as the image, you need to jump through different hoops based on what the output image format is going to be;

An example for tiff, to force 16bit tiff output.
```
$imagick = new Imagick();
$imagick->newPseudoImage(200, 200, 'xc:white');
$imagick->setType(\Imagick::IMGTYPE_TRUECOLOR);
$imagick->setImageFormat('tiff');
$imagick->setImageDepth(16);
$imagick->writeImage("./output.tif"); 
```

An example of PNG, to force the image written to be the same depth as the image read.
```
$imagick = new Imagick("./testImage.png");
$imagick->flopImage();
$imagick->setOption('png:format', 'png00');
$imagick->writeImage("./output.png");
```

It would be good if it was possible (if it isn't already possible and I'm just unaware of it) to be able to set  a single option, such as:

```
MagickSetOption(wand, "im:depth_preserve", "true");
```
to be able to set the behaviour for all image types. And for the file writing to give an error if the image can't be written in the exact format as it exists in memory.

**Comment by mikayla-grace** [comment]
Modern releases of ImageMagick, by default, writes to an image format @ the same depth as the source image assuming the particular image format supports the depth.   XBM, for example, only supports images of depth 1, regardless of the source image depth.  This is by design.   If you find that ImageMagick behaves differently, post a command-line illustrating the exception.

**Comment by Danack** [comment]
>  If you find that ImageMagick behaves differently, post a command-line illustrating the exception.

I am not using the command-line, I am using the MagickWand API. 

> Modern releases of ImageMagick, by default, writes to an image format @ the same depth as the source image assuming the particular image format supports the depth.

Actually, no it doesn't. The code below produces two images.  Even though both images are set to be 16-bit, one of them is a 1-bit image.

```
./output_default.tif TIFF 200x200 200x200+0+0 1-bit Bilevel Gray 5.26KB 0.000u 0:00.000
./output_forceTrueColor.tif TIFF 200x200 200x200+0+0 16-bit sRGB 241KB 0.000u 0:00.000
```

The only difference in the code that generates the two images is the line ```$imagick->setType(\Imagick::IMGTYPE_TRUECOLOR);``` which I saw affects how the images are saved.

As I said, this is a feature request rather than a bug, but it seems like being able to control the output image format directly should be possible, rather than working around the different behaviours of the image coders.

```
<?php

$imagick = new Imagick();
$imagick->newPseudoImage(200, 200, 'xc:white');
$imagick->setImageFormat('tiff');
$imagick->setImageDepth(16);
$imagick->writeImage("./output_default.tif");
system('identify ./output_default.tif');


$imagick = new Imagick();
$imagick->newPseudoImage(200, 200, 'xc:white');
$imagick->setType(\Imagick::IMGTYPE_TRUECOLOR);
$imagick->setImageFormat('tiff');
$imagick->setImageDepth(16);
$imagick->writeImage("./output_forceTrueColor.tif");
system("identify ./output_forceTrueColor.tif");

```

**Comment by mikayla-grace** [comment]
This identifies a TIFF specific issue.  By default, if the TIFF coder detects a monochrome image, it writes at a depth of 1 unless overridden by setType() or setDepth().   This is a legacy issue which we will patch in the next release of ImageMagick.

**Comment by Danack** [comment]
If it is meant to preserve depth, and the issue was isolated to Tiffs, I will close this issue.
