### ISSUE TITLE
HSL modulation of certain near-white colors by hue 60 results in black

### ISSUE THREAD

**Issue by evanmcallaway** [ImageMagick/ImageMagick#6602]
### ImageMagick version

7.1.1-15 with HDRI disabled

### Operating system

Linux

### Operating system, version and so on

Debian 22.04

### Description

There may be more colors that are affected, but I've only encountered this issue with #EAEBE6 so far.

### Steps to Reproduce

I've isolated the issue here.

`convert -size 100x100 xc:#EAEBE6 -modulate 100,100,60 out.png`

This results in a pure black output image for me.

You can also see it when modulating other images like the one attached.

`convert lady.png -modulate 100,100,60 lady_hsl.png`

Running the same operation on an adjacent color or a different modulation results in an appropriate near-white color.  Running the same hue transformation in HSB space works properly as well.

### Images

![lady](https://github.com/ImageMagick/ImageMagick/assets/5093359/4f500d1c-5b92-491a-86f3-d4e01daee55b)
![lady_hsl](https://github.com/ImageMagick/ImageMagick/assets/5093359/e1798fea-2c2a-4271-b169-9a5883169c1c)

**Comment by fmw42** [comment]
All white colors have no (zero) hue.  When I do your processing, I get a whitish input and whitish output

Input:

![in](https://github.com/ImageMagick/ImageMagick/assets/13458218/c7e82e9d-0921-47a6-b1c2-31dbba79c1d4)

magick -size 100x100 xc:#EAEBE6 +write in.png -modulate 100,100,60 out.png

Output:

![out](https://github.com/ImageMagick/ImageMagick/assets/13458218/46a232c6-1c44-48e9-aa3f-64aa7db9a2fc)

**Comment by fmw42** [comment]
I made a mistake. On Unix-like systems, the hex color must be enclosed in quotes.

`magick -size 100x100 xc:"#EAEBE6" +write in.png -modulate 100,100,60 out.png`

Does make a black result:

Out:

![out](https://github.com/ImageMagick/ImageMagick/assets/13458218/da1e0791-6bfc-4449-8be4-1fe5db904fad)


When the hue=0, you cannot rotate it. IM then interprets the result as hue=0, which is all shades of gray. So IM assigns it black, as the hue of 0 is indeterminant.  This is my understanding.  But someone could check the code to see what it is actually doing.

**Comment by evanmcallaway** [comment]
No change for me with or without quotes.
`magick -size 100x100 xc:"#EAEBE6" +write in.png -modulate 100,100,60 out.png`

In:
![in](https://github.com/ImageMagick/ImageMagick/assets/5093359/c4100dff-4b5f-4463-be02-472861dff825)

Out:
![out](https://github.com/ImageMagick/ImageMagick/assets/5093359/65fe7c3f-7e55-49af-8fc3-4a9083509fdd)

Do you get also not get black artifacts if you do the transform on the test image I attached to the ticket?

**Comment by fmw42** [comment]
I do not know, then why you get black!

**Comment by fmw42** [comment]
> Do you get also not get black artifacts if you do the transform on the test image I attached to the ticket?

Yes, that happens when any pixel has hue=0 and the input is likely white.

`magick 264391708-4f500d1c-5b92-491a-86f3-d4e01daee55b.png -modulate 100,100,60 264391708-4f500d1c-5b92-491a-86f3-d4e01daee55b_result.png`

Output:

![264391708-4f500d1c-5b92-491a-86f3-d4e01daee55b_result](https://github.com/ImageMagick/ImageMagick/assets/13458218/558cbaa5-ffb5-4665-8c31-63502ccc14d1)

**Comment by evanmcallaway** [comment]
Interesting!  The distribution of black artifacts in your output is slightly different from my output.  You can see it clearly in  if you look at just the upper-right corner of the image.  If it were only white/nearly-white pixels I'd expect our outputs to be identical or at least more similar.

I've noticed that performing hue modulation in HSB space does not introduce the black artifacts.

**Comment by fmw42** [comment]
Yes, see https://imagemagick.org/Usage/color_mods/#modulate_colorspace

**Comment by evanmcallaway** [comment]
It's also curious that (for my examples) the black pixels only occur when modulating hue with 60.  59 or 61 (or any other value I've tried) do not introduce the black pixels.

**Comment by BagpipesJohnson** [comment]
Co-worker of Evan's here. Mac OS Monterey 12.3. I am seeing the same behavior. I'm using the pre-compiled version that homebrew provides.

`Path: /opt/homebrew/Cellar/imagemagick/7.1.1-15/lib/ImageMagick//config-Q16HDRI/configure.xml

Name                  Value
-------------------------------------------------------------------------------
CC                    clang
CFLAGS                 -I/opt/homebrew/Cellar/webp/1.3.1/include -I/opt/homebrew/Cellar/webp/1.3.1/include/webp -I/opt/homebrew/Cellar/webp/1.3.1/include -I/opt/homebrew/Cellar/webp/1.3.1/include/webp -I/opt/homebrew/Cellar/jpeg-turbo/3.0.0/include -I/opt/homebrew/Cellar/xz/5.4.3/include -I/opt/homebrew/Cellar/zstd/1.5.5/include -I/opt/homebrew/Cellar/libtiff/4.5.1/include -I/opt/homebrew/Cellar/little-cms2/2.15/include -I/opt/homebrew/Cellar/libraw/0.21.1/include/libraw -I/opt/homebrew/Cellar/libraw/0.21.1/include -I/opt/homebrew/opt/libpng/include/libpng16 -pthread -I/opt/homebrew/Cellar/imath/3.1.9/include -I/opt/homebrew/Cellar/imath/3.1.9/include/Imath -I/opt/homebrew/Cellar/openexr/3.1.9/include -I/opt/homebrew/Cellar/openexr/3.1.9/include/OpenEXR -I/opt/homebrew/Cellar/xz/5.4.3/include -I/opt/homebrew/Cellar/pcre2/10.42/include -I/opt/homebrew/Cellar/glib/2.76.4/include/glib-2.0 -I/opt/homebrew/Cellar/glib/2.76.4/lib/glib-2.0/include -I/opt/homebrew/opt/gettext/include -I/opt/homebrew/Cellar/liblqr/0.4.2_1/include/lqr-1 -I/opt/homebrew/Cellar/openjpeg/2.5.0_1/include/openjpeg-2.5 -I/opt/homebrew/Cellar/little-cms2/2.15/include -DHWY_SHARED_DEFINE -I/opt/homebrew/Cellar/little-cms2/2.15/include -I/opt/homebrew/Cellar/brotli/1.0.9/include -I/opt/homebrew/Cellar/highway/1.0.5/include -I/opt/homebrew/Cellar/webp/1.3.1/include/webp -I/opt/homebrew/Cellar/jpeg-xl/0.8.2/include -I/opt/homebrew/Cellar/libvmaf/2.3.1/include -I/opt/homebrew/Cellar/libvmaf/2.3.1/include/libvmaf -I/opt/homebrew/Cellar/aom/3.6.1/include -I/opt/homebrew/Cellar/libde265/1.0.12/include -I/opt/homebrew/Cellar/x265/3.5/include -I/opt/homebrew/Cellar/libheif/1.16.2/include -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/Cellar/fontconfig/2.14.2/include   -Xpreprocessor -fopenmp -Wall -g -O2 -fexceptions -D_FORTIFY_SOURCE=0 -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
CODER_PATH            /opt/homebrew/Cellar/imagemagick/7.1.1-15/lib/ImageMagick/modules-Q16HDRI/coders
CONFIGURE             ./configure  '--disable-debug' '--disable-dependency-tracking' '--prefix=/opt/homebrew/Cellar/imagemagick/7.1.1-15' '--libdir=/opt/homebrew/Cellar/imagemagick/7.1.1-15/lib' '--enable-osx-universal-binary=no' '--disable-silent-rules' '--disable-opencl' '--enable-shared' '--enable-static' '--with-freetype=yes' '--with-gvc=no' '--with-modules' '--with-openjp2' '--with-openexr' '--with-webp=yes' '--with-heic=yes' '--with-raw=yes' '--with-gslib' '--with-gs-font-dir=/opt/homebrew/share/ghostscript/fonts' '--with-lqr' '--without-djvu' '--without-fftw' '--without-pango' '--without-wmf' '--enable-openmp' '--without-x' 'ac_cv_prog_c_openmp=-Xpreprocessor -fopenmp' 'ac_cv_prog_cxx_openmp=-Xpreprocessor -fopenmp' 'LDFLAGS=-lomp -lz' 'CC=clang' 'CXX=clang++' 'PKG_CONFIG_PATH=/opt/homebrew/opt/libpng/lib/pkgconfig:/opt/homebrew/opt/freetype/lib/pkgconfig:/opt/homebrew/opt/fontconfig/lib/pkgconfig:/opt/homebrew/opt/jbig2dec/lib/pkgconfig:/opt/homebrew/opt/jpeg-turbo/lib/pkgconfig:/opt/homebrew/opt/libidn/lib/pkgconfig:/opt/homebrew/opt/xz/lib/pkgconfig:/opt/homebrew/opt/lz4/lib/pkgconfig:/opt/homebrew/opt/zstd/lib/pkgconfig:/opt/homebrew/opt/libtiff/lib/pkgconfig:/opt/homebrew/opt/little-cms2/lib/pkgconfig:/opt/homebrew/opt/openjpeg/lib/pkgconfig:/opt/homebrew/opt/brotli/lib/pkgconfig:/opt/homebrew/opt/highway/lib/pkgconfig:/opt/homebrew/opt/imath/lib/pkgconfig:/opt/homebrew/opt/openexr/lib/pkgconfig:/opt/homebrew/opt/webp/lib/pkgconfig:/opt/homebrew/opt/jpeg-xl/lib/pkgconfig:/opt/homebrew/opt/libvmaf/lib/pkgconfig:/opt/homebrew/opt/aom/lib/pkgconfig:/opt/homebrew/opt/libde265/lib/pkgconfig:/opt/homebrew/opt/pcre2/lib/pkgconfig:/opt/homebrew/opt/glib/lib/pkgconfig:/opt/homebrew/opt/x265/lib/pkgconfig:/opt/homebrew/opt/libheif/lib/pkgconfig:/opt/homebrew/opt/liblqr/lib/pkgconfig:/opt/homebrew/opt/jasper/lib/pkgconfig:/opt/homebrew/opt/libraw/lib/pkgconfig:/opt/homebrew/opt/shared-mime-info/share/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/12'
CONFIGURE_PATH        /opt/homebrew/Cellar/imagemagick/7.1.1-15/etc/ImageMagick-7/
COPYRIGHT             Copyright (C) 1999 ImageMagick Studio LLC
CPPFLAGS              -I/opt/homebrew/Cellar/imagemagick/7.1.1-15/include/ImageMagick-7
CXX                   clang++ -std=gnu++11 -std=gnu++11
CXXFLAGS              -g -O2 -pthread
DEFS                  -DHAVE_CONFIG_H
DELEGATES             bzlib fontconfig freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr png ps raw tiff webp xml zlib zstd
DISTCHECK_CONFIG_FLAGS 'CC=clang' 'CXX=clang++' 'LDFLAGS=-lomp -lz'  --disable-deprecated  --with-quantum-depth=16  --with-jemalloc=no  --with-umem=no  --with-autotrace=no  --with-dps=no  --with-fftw=no  --with-flif=no  --with-fpx=no  --with-djvu=no  --with-fontpath=  --with-gs-font-dir=/opt/homebrew/share/ghostscript/fonts  --with-gvc=no  --with-pango=no  --with-rsvg=no  --with-wmf=no  --with-perl=no 
DOCUMENTATION_PATH    /opt/homebrew/Cellar/imagemagick/7.1.1-15/share/doc/ImageMagick-7
EXEC-PREFIX           /opt/homebrew/Cellar/imagemagick/7.1.1-15
EXECUTABLE_PATH       /opt/homebrew/Cellar/imagemagick/7.1.1-15/bin
FEATURES              DPC HDRI Cipher OpenMP Modules
FILTER_PATH           /opt/homebrew/Cellar/imagemagick/7.1.1-15/lib/ImageMagick/modules-Q16HDRI/filters
GIT_REVISION          21298
HOST                  aarch64-apple-darwin21.6.0
INCLUDE_PATH          /opt/homebrew/Cellar/imagemagick/7.1.1-15/include/ImageMagick-7
LDFLAGS               -L/opt/homebrew/Cellar/imagemagick/7.1.1-15/lib -lomp -lz
LIB_VERSION           0x711
LIB_VERSION_NUMBER    7,1,1,15
LIBRARY_PATH          /opt/homebrew/Cellar/imagemagick/7.1.1-15/lib/ImageMagick
LIBS                   -L/opt/homebrew/Cellar/little-cms2/2.15/lib -llcms2  -L/opt/homebrew/opt/freetype/lib -lfreetype  -L/opt/homebrew/Cellar/glib/2.76.4/lib -L/opt/homebrew/opt/gettext/lib -llqr-1 -lglib-2.0 -lintl  -lxml2  -L/opt/homebrew/opt/freetype/lib -L/opt/homebrew/Cellar/fontconfig/2.14.2/lib -lfontconfig -lfreetype     -lbz2 -lz   -lltdl  -lm    -lpthread   
NAME                  ImageMagick
PCFLAGS               -Xpreprocessor -fopenmp -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
PREFIX                /opt/homebrew/Cellar/imagemagick/7.1.1-15
QuantumDepth          16
RELEASE_DATE          2023-07-30
SHARE_PATH            /opt/homebrew/Cellar/imagemagick/7.1.1-15/share/ImageMagick-7
SHAREARCH_PATH        /opt/homebrew/Cellar/imagemagick/7.1.1-15/lib/ImageMagick/config-Q16HDRI
TARGET_CPU            aarch64
TARGET_OS             darwin21.6.0
TARGET_VENDOR         apple
VERSION               7.1.1
WEBSITE               https://imagemagick.org

Path: [built-in]

Name                  Value
-------------------------------------------------------------------------------
DELEGATES             bzlib fontconfig freetype gslib heic jng jp2 jpeg jxl lcms lqr ltdl lzma openexr png ps raw tiff webp xml zlib
FEATURES              Cipher DPC HDRI Modules OpenMP(5.0) 
MAGICK_TEMPORARY_PATH /var/folders/5q/q0fnvnz52qg0fw442km5w6k80000gn/T
NAME                  ImageMagick
QuantumDepth          Q16
`

`magick -size 100x100 xc:"#EAEBE6" +write in.png -modulate 100,100,60 out.png`

![in](https://github.com/ImageMagick/ImageMagick/assets/2204599/94750c84-3602-4246-80b1-daadce04019d)
![out](https://github.com/ImageMagick/ImageMagick/assets/2204599/885702a3-9602-457d-bb55-c56a5bb7fdab)

**Comment by snibgo** [comment]
There is a problem. We can demonstrate it simply. Windows, where `#` is not a special character.
```
magick  xc:#EAEBE6 +write txt: -modulate 100,100,60 txt:

# ImageMagick pixel enumeration: 1,1,0,65535,srgb
0,0: (60138,60395,59110)  #EAEAEBEBE6E6  srgb(234,235,230)
# ImageMagick pixel enumeration: 1,1,0,65535,srgb
0,0: (0,0,0)  #000000000000  black
```
The single pixel is close to gray. Rotating the hue should give another colour that is close to gray. Black is wrong. I would call it a bug.

I think `-modulate` works in HSL space. Doing the conversion...
```
magick  xc:#EAEBE6 -colorspace HSL txt:

# ImageMagick pixel enumeration: 1,1,0,65535,hsl
0,0: (13107,7282,59753)  #33331C72E969  hsl(72,11.1111%,91.1765%)
```
... we see that saturation isn't very close to gray.

I haven't looked at the code.

**Comment by fmw42** [comment]
I measured a pixel in the input for which his output is black. I then processed it as follows:

`magick -size 100x100 xc:"rgb(236,237,232)" +write in.png -modulate 100,100,60 out.png`

Output

![out](https://github.com/ImageMagick/ImageMagick/assets/13458218/c9a0d315-3a76-471d-a61d-a0b1f4ee3ecd)

**Comment by snibgo** [comment]
In gem.c, function ConvertHSLToRGB(), I suspect we are hitting the default in ...
```
  switch ((int) floor(h))
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce the issue and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
