### ISSUE TITLE
Policy file misnamed

### ISSUE THREAD

**Issue by parkerjm** [ImageMagick/ImageMagick#6604]
### ImageMagick version

7.1.1-16

### Operating system

Linux

### Operating system, version and so on

debian

### Description

When attempting to run `./configure` against lastest, I get this error:

```config.status: error: cannot find input file: `config/open-policy.xml'```

In the Makefile and other config, the file is named `open-policy.xml`, but in the `config` folder, the file is named `policy-open.xml`. I copied `policy-open.xml` to `open-policy.xml` and the build worked.

Am I missing something?

### Steps to Reproduce

pull latest, `./configure`

**Comment by parkerjm** [comment]
Broken here: https://github.com/ImageMagick/ImageMagick/commit/2e529f63e1f4ef548de956d99fc8aa76e7bd1685

**Comment by urban-warrior** [comment]
Grab the latest commit.  Does that resolve the issue?

**Comment by parkerjm** [comment]
yeah latest commit looks like it fixes the problem, ty

**Comment by mmomtchev** [comment]
@urban-warrior Same goes for the Windows build - at the moment it is not possible to rebuild the latest ImageMagick release, you have to build the git `HEAD`.

**Comment by dlemstra** [comment]
If you want to rebuild an ImageMagick Windows release you should make sure that you are not using commits in The ImageMagick-Windows/VisualMagick repository that have been made after the release date. And this also goes for all the dependencies. When we update our dependencies it is possible that we need to make changes that break building older releases.

**Comment by mmomtchev** [comment]
@dlemstra I confirm you that the latest ImageMagick `7.1.1-15`, commit `a0a5f3da4cd07919dd2d1bbae121e590b5f105e2` does not build for Windows with `ImageMagick-Windows`, commit `6570fa03a44d5e2c650bbeb1175b587657ef5b3c` - the last one before the ImageMagick release on July 30. The latest git checkout builds correctly. Anyway, there haven't been any commits on `ImageMagick-Windows` before the `dependabot` one this Monday.
