### ISSUE TITLE
Add conda support for ImageMagick

### ISSUE THREAD

**Issue by Julian-O** [ImageMagick/ImageMagick#661]
I am writing AppVeyor scripts to test a Python package that depends on ImageMagick. Automatically installing ImageMagick on Windows is one of the more difficult components of the script - not least because the download URL changes as new versions are released, so the script breaks regularly.

[Conda.io](https://conda.io/docs/) is a package manager that allows scripts to specify what version/range of versions of ImageMagick they depend on, and it takes care of installing binaries, across several platforms.

Someone has produced the appropriate packaging for [imagemagick 6.9.1 on 64-bit Linux only](https://anaconda.org/kalefranz/imagemagick).

Please consider providing a conda channel with official definitions for multiple versions of ImageMagick on all the supported platforms.

**Comment by mikayla-grace** [comment]
We have a small development team and its unlikely we will find the time to support Conda.io.   Perhaps a ImageMagick user will volunteer to configure and maintain Conda.io.

**Comment by fanninpm** [comment]
ImageMagick is availabe [on the conda-forge channel.](https://anaconda.org/conda-forge/imagemagick)
