### ISSUE TITLE
Tif conversion, maximum channels exceeded

### ISSUE THREAD

**Issue by bvb-sc** [ImageMagick/ImageMagick#6615]
### ImageMagick version

7.1.1-15

### Operating system

Linux

### Operating system, version and so on

Ubuntu Focal 20.04

### Description

We have quite a few tiff files with a lot of additional alpha channels. When using the `magick convert` command on them, they immediately fail with the following error description:

```
convert: maximum channels exceeded `file.tif' @ error/tiff.c/ReadTIFFImage/1369.
convert: no images defined `file.png' @ error/convert.c/ConvertImageCommand/3354.
```

The issue seems similar to this previously fixed one: https://github.com/ImageMagick/ImageMagick/issues/2746

On some previous versions (e.g. 7.0.11-7), the issue can't be replicated.

### Steps to Reproduce

1. Use this file: https://sitecore1-my.sharepoint.com/:i:/g/personal/bvb_sitecore_net/ERgnmjUjQA1OoXzaBk8y0VIBw7ATh8nJ6Dj_nu6VaPywVA?e=oOiF22
2. run `magick convert "input_file.tif[0]" -resize "1000x1000>" "output_file.png"`

**Comment by snibgo** [comment]
Opening that link, I can't see any way to download the TIFF file. How many channels does it have?

I think the current limit on the total number of channels is 32. Some are reserved for R,G,B,A,read-mask etc, so there can be about 22 "meta" channels.

**Comment by urban-warrior** [comment]
If you download the Github main repo, you can enable up to 51 meta channels by adding the `--enable-64bit-channel-masks` option to the `configure` build script.

**Comment by bvb-sc** [comment]
> Opening that link, I can't see any way to download the TIFF file. How many channels does it have?
> 
> I think the current limit on the total number of channels is 32. Some are reserved for R,G,B,A,read-mask etc, so there can be about 22 "meta" channels.

I've reuploaded it as a zip file: https://sitecore1-my.sharepoint.com/:u:/g/personal/bvb_sitecore_net/Ea6UZLPVQ7NCvt9f1c0XAY4Bo1ZDtDEdRoqTeJL7RDw_eQ?e=qS3Tr5

This file has 50 total channels, of which 46 invisible:

![channels](https://github.com/ImageMagick/ImageMagick/assets/67702686/4331f855-e33b-4714-985c-3908a3397729)


> If you download the Github main repo, you can enable up to 51 meta channels by adding the `--enable-64bit-channel-masks` option to the `configure` build script.

I'll give this one a try, should work for these files I guess, thanks!
