### ISSUE TITLE
Implode Consistently Crashing at Specific Positive Value

### ISSUE THREAD

**Issue by iansantagata** [ImageMagick/ImageMagick#6623]
### ImageMagick version

7.1.0-28

### Operating system

Windows

### Operating system, version and so on

Windows 10 Pro - Version 22H2 - OS Build 19045.3324

### Description

When trying to run `magick INPUT_FILE -implode +X OUTPUT_FILE` via the command line, `magick` will succeed for fractional values of `X`, but fails at some consistent positive value for `X` which seems to depend on image size.

Failure message reported back:

```bash
magick.exe: width or height exceeds limit `INPUT_FILE[0]' @ error/cache.c/SetPixelCacheNexusPixels/5053.
```

Command line execution was done via Git Bash for Windows (`git --version` outputs `git version 2.42.0.windows.2`).

Examples:

```bash
# CLI commands that succeeded and produced the OUTPUT_FILE
magick Astronaut.png -implode +8 Astronaut_implode.png
magick Phoenix.png -implode +6 Phoenix_implode.png
magick Santa.png -implode +9 Santa_implode.png

# Increasing the implode value by 1 causes each of these same commands to fail
magick Astronaut.png -implode +9 Astronaut_implode.png
magick Phoenix.png -implode +7 Phoenix_implode.png
magick Santa.png -implode +10 Santa_implode.png
```

### Steps to Reproduce

Can save the following script below as `test.sh` and run it as `./test.sh` to determine what value the `-implode VALUE` fails at for a given file.

See `# Editable` for things that can be configured, but for now this file is setup to look at attached file `Astronaut.png` and fails at `9` consistently.

```bash
#! /bin/bash
set -e

# Target local file name to test (file should be in same directory as script is running)
FILE_NAME_ROOT="Astronaut" # Editable
EXTENSION="png" # Editable
FILE=$FILE_NAME_ROOT.$EXTENSION

echo "Determining what implode value this file fails at..."
VALUE=1
MAX_VALUE=100  # Editable

while [ "$VALUE" -le "$MAX_VALUE" ]; do

    # Create a new file temporarily to test the magick -implode command working successfully
    NEW_FILE="${FILE_NAME_ROOT}_implode_${VALUE}.$EXTENSION"
    echo "Testing value '$VALUE'"

    # Will fail here for some VALUE
    magick $FILE -implode +$VALUE $NEW_FILE
    echo "Successfully created file for -implode '$VALUE'"

    # Clean up so as not to create a bunch of files that we do not need
    rm $NEW_FILE

    VALUE=$(($VALUE + 1))
done

echo "Reached maximum -implode value without failure"
exit 0
```

Output should look like this:
```bash
$ ./test.sh
Determining what implode value this file fails at...
Testing value '1'
Successfully created file for -implode '1'
Testing value '2'
Successfully created file for -implode '2'
Testing value '3'
Successfully created file for -implode '3'
Testing value '4'
Successfully created file for -implode '4'
Testing value '5'
Successfully created file for -implode '5'
Testing value '6'
Successfully created file for -implode '6'
Testing value '7'
Successfully created file for -implode '7'
Testing value '8'
Successfully created file for -implode '8'
Testing value '9'
magick.exe: width or height exceeds limit `Astronaut.png[0]' @ error/cache.c/SetPixelCacheNexusPixels/5053.
```

### Images

![Astronaut](https://github.com/ImageMagick/ImageMagick/assets/7070901/67724f1a-e00a-4332-ab2c-6327bbbaccc6)

![Phoenix](https://github.com/ImageMagick/ImageMagick/assets/7070901/e6c94fea-68b5-4184-9d45-b9e03e11f867)

![Santa](https://github.com/ImageMagick/ImageMagick/assets/7070901/01ae4423-3e17-4435-9b4c-e65325ebb1ce)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce the issue and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by iansantagata** [comment]
Hi @urban-warrior!  Forgive me since I'm unaware of Image Magick's processes, but is this expected to get into a published version eventually?  Do published versions get packaged and deployed at some regularity, or is it more arbitrary than that?

Thanks again for getting this fix into the `main` branch and the beta release already!

**Comment by urban-warrior** [comment]
We should have a new release of ImageMagick with the patch to address this issue within the next two weeks.

**Comment by iansantagata** [comment]
@urban-warrior - Is this expected to have been fixed and pushed to the latest release package?

I just ran the same tests again on version `7.1.1-21` of ImageMagick and receive the same failure, with a different line number:

```bash
magick.exe: width or height exceeds limit `Santa.png[0]' @ error/cache.c/SetPixelCacheNexusPixels/5123
```

This makes it seem like this issue is still a problem and may be worth re-opening?

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
