### ISSUE TITLE
No alpha channel saved in Targa (tga) images (fix included)

### ISSUE THREAD

**Issue by bztsrc** [ImageMagick/ImageMagick#6629]
### ImageMagick version

all, latest git too

### Operating system

Other (enter below)

### Operating system, version and so on

all

### Description

If you try to save an indexed tga file, the alpha channel is lost.

I looked at coders/tga.c, and no wonder, it's not implemented at all. Here's a patch that fixes it:
```
$ diff -u old_tga.c tga.c 
--- old_tga.c	2023-09-07 16:38:17.000000000 +0200
+++ tga.c	2023-09-08 03:32:12.396125267 +0200
@@ -923,6 +923,9 @@
         if (image_info->depth == 5)
           tga_info.colormap_size=16;
         else
+        if (image->alpha_trait & BlendPixelTrait)
+          tga_info.colormap_size=32;
+        else
           tga_info.colormap_size=24;
       }
   if ((image->orientation == BottomRightOrientation) ||
@@ -984,6 +987,8 @@
             *q++=ScaleQuantumToChar(ClampToQuantum(image->colormap[i].blue));
             *q++=ScaleQuantumToChar(ClampToQuantum(image->colormap[i].green));
             *q++=ScaleQuantumToChar(ClampToQuantum(image->colormap[i].red));
+            if(tga_info.colormap_size == 32)
+              *q++=ScaleQuantumToChar(ClampToQuantum(image->colormap[i].alpha));
           }
       }
       (void) WriteBlob(image,(size_t) ((tga_info.colormap_size/8)*
```
On the read side, indexed tga images with alpha channel are handled properly.

Unrelated, but please consider removing that annoying "optional footer", it's no use. It was added just yesterday, wasn't there before and it worked fine.

### Steps to Reproduce

convert any_rgba.png -colors 256 -compress RLE noalpha.tga

**Comment by dlemstra** [comment]
Thanks for this opening issue. We have applied (a modified version) of your patch and this will become available in the next release. 

We have added that optional header because of this issue: #6543.

**Comment by bztsrc** [comment]
> Thanks for this opening issue. We have applied (a modified version) of your patch and this will become available in the next release.

Thank you! Not sure what you've modified, but as long as `-alpha on` adds the alpha channel to the palette it's good for me! Thanks again!

> We have added that optional header because of this issue: #6543.

I see. And would it possible to add a command line switch that controls if that annoying optional footer is written or not, just like the issue suggested? Right now it's written unconditionally and it causes problems for me.

**Comment by bztsrc** [comment]
Since this has been merged, I can close this issue I guess? If you would like to keep it open until this gets into a release, then sorry, and please re-open it.
