### ISSUE TITLE
OpenCL -function Polynomial is bad

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#6631]
### ImageMagick version

7.1.1-15 Q16-HDRI

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

The accelerated version of "`-function Polynomial`" is badly inaccurate.

### Steps to Reproduce

For example, "`-function Polynomial 1,0`" should not change values, but:
```
D:\temp>set MAGICK_OCL_DEVICE=false

D:\temp>%IMG7%magick xc:sRGB(10%,20%,30%) -function Polynomial 1,0 txt:
# ImageMagick pixel enumeration: 1,1,0,65535,srgb
0,0: (6554,13107,19661)  #199A33334CCD  srgb(10%,20%,30%)  <== CORRECT

D:\temp>set MAGICK_OCL_DEVICE=true

D:\temp>%IMG7%magick xc:sRGB(10%,20%,30%) -function Polynomial 1,0 txt:
# ImageMagick pixel enumeration: 1,1,0,65535,srgb
0,0: (6442,12885,19327)  #192A32554B7F  srgb(9.83025%,19.6605%,29.4907%)  <== WRONG
```

**Comment by dlemstra** [comment]
I can reproduce this issue and I suspect this has to do with the fact that OpenCL uses `float` instead of `double` but I am not sure about this. Feel free to investigate this and help us resolve this issue.

**Comment by snibgo** [comment]
Thanks.

The error, about 1 part in 60, is too large to be a float-or-double precision problem. We can get the expected no-change with:
```
D:\temp>%IMG7%magick xc:sRGB(10%,20%,30%) -function Polynomial 1.0172682,0 -precision 15 txt:
# ImageMagick pixel enumeration: 1,1,0,65535,srgb
0,0: (6554,13107,19661)  #199A33334CCD  srgb(10%,20%,30%)
```
So the error is a constant factor, which rounding errors are not. The same factor of 1.0172682 works with other pixel values. If we double that number, we get a doubling of the pixel values. So the error is a constant factor.

I can't see any problem in the C code. I have no experience with OpenCL.

I will keep looking.

**Comment by snibgo** [comment]
The problem also occurs with "`-function sinusoid`". When using OpenCL, I need to multiply pixel values by 1.0172682 to get the answer I expect. The problem does not occur with "`-blur`".

My working theory is that for "`-function`", pixel values are somehow divided by 1.0172682.

**Comment by dlemstra** [comment]
I just pushed a patched that seems to resolve this issue. Please don't ask me why this fixes the problem...

**Comment by snibgo** [comment]
Ha, well done! Yes, a "wrong" value for QuantumScale could explain it.

My tests above were done with pre-built IM on Windows. When I try to build with OpenCL, I get:
```
fatal error: OpenCL/cl.h: No such file or directory
```
I guess I haven't installed the correct OpenCL library. Where should I gt that from?

**Comment by dlemstra** [comment]
Where are using these header files: https://github.com/ImageMagick/VisualMagick/tree/34663bbfd168314d17134710f98aeab4328093f1/OpenCL/CL. You should probably add the folder of these files to your include path.
