### ISSUE TITLE
PDF to JPG / TIFF adds some weird horizontal lines

### ISSUE THREAD

**Issue by mranvick** [ImageMagick/ImageMagick#6639]
### ImageMagick version

7.1.1-15_1

### Operating system

MacOS

### Operating system, version and so on

Ventura 13.2 Intel Core i7

### Description

I am using ImageMagick to convert from PDF to a raster image format such as JPG or TIFF.

When I use GhostScript directly, e.g. with:
`gs -sDEVICE=jpeg -o rastered_img_gs.jpg -r600x600 mypdf.pdf`
or
`gs -sDEVICE=tiff24nc -o rastered_img_gs.tiff -r600x600 mypdf.pdf`

The output looks ok. However, if I use ImageMagick, e.g. with:
`convert -density 600 mypdf.pdf rastered_img_im.jpg`
or
`convert -density 600 mypdf.pdf rastered_img_im.tiff`

Some weird lines appear on various normally-plain colour areas, as depicted on the images below.

---

I also had the same issue with PNG or BMP formats... I ended up using `pdftoppm` which works fine (or I could have stuck with GhostScript).

### Steps to Reproduce

I made this minimal working example in Tikz to show the issue at hand, LaTeX code:

```latex
\documentclass[tikz]{standalone}
\usepackage{pgfplots}
\pgfplotsset{width=8cm, height=7cm, compat=1.18}
\usepackage{tikz}
\newcommand{\mytau}{0.075}

\begin{document}
	
	\begin{tikzpicture}
		\begin{axis}[xmin=0, xmax=10, ymin=0, ymax=1]
			\addplot[color=black,line cap=round,
			domain=0:5,
			samples=200,
			line width=5pt,
			]{1-exp(-\mytau*x)};
			\addplot[forget plot, color=black,line cap=round,
			domain=5:10,
			samples=200,
			line width=5pt,
			]{1-exp(-2*\mytau*(x-5))+1-exp(-\mytau*5)};
			\addplot[color=blue, line cap=round,
			domain=0:10,
			samples=200,
			line width=2pt,
			]{1-exp(-\mytau*x)};
			\addplot[color=red, line cap=round,
			domain=5:10,
			samples=200,
			line width=2pt,,
			]{1-exp(-2*\mytau*(x-5))+1-exp(-5*\mytau)};
		\end{axis}
	\end{tikzpicture}
\end{document}
```

Compile using `lualatex mwe.tex`, which should produce a `mwe.pdf` file.

Using Ghostscript works fine using either of these commands:

```bash
gs -sDEVICE=jpeg -o rastered_img_gs.jpg -r600x600 mwe.pdf
gs -sDEVICE=tiff24nc -o rastered_img_gs.tiff -r600x600 mwe.pdf
```

However, using ImageMagick with:

```bash
convert -density 600 mwe.pdf rastered_img_im.jpg
convert -density 600 mwe.pdf rastered_img_im.tiff
```

Yields horrible horizontal lines...

### Images

PDF version is clean:
![image](https://github.com/ImageMagick/ImageMagick/assets/17085178/1d6aee7e-5e1b-4f43-914e-7562383c2c5c)
Ghostscript JPG is also clean (apart from the crappy JPG compression of course):
![image](https://github.com/ImageMagick/ImageMagick/assets/17085178/a19e6eae-8668-401b-93b6-158bbb137b04)
ImageMagick version has some weird horizontal lines:
![image](https://github.com/ImageMagick/ImageMagick/assets/17085178/7eb83896-ef29-40fb-beae-a9db27fd6c00)

**Comment by dlemstra** [comment]
This is probably an issue in the output device that is used by Ghoscript that we don't control. You can view the exact command by adding `-verbose` to your command,

**Comment by fmw42** [comment]
What version of Ghostscript are you using?   You may need to upgrade or downgrade

**Comment by mranvick** [comment]
@fmw42 I tried with GhostScript 10.01.1 and 10.01.2.

> You may need to upgrade or downgrade

Could you please elaborate? Do you mean that you tested it with another version and that it works? Could you please give me more details so that I may report this directly to GS devs?

**Comment by fmw42** [comment]
I have heard that there are some issues with that version, GS 10. Please try downgrading to 9.x

**Comment by mranvick** [comment]
@fmw42 I just tested with Ghostscript 9.26 and it works.

Cmd: `gs -sDEVICE=pngalpha -o rastered_img_gs.png -r600x600 mwe.pdf`

Result:
![image](https://github.com/ImageMagick/ImageMagick/assets/17085178/4ecb7ef1-8c19-4242-a9ad-b336f9611051)

Unfortunately, I am using MacOS and [no binaries exist](https://ghostscript.com/releases/gsdnld.html). I installed the latest available version on Homebrew (10.01.2, not working), and I had the 9.26 (working) installed behind brew so I could test with both.

Sadly, I tried to compile other intermediary versions locally to pinpoint the apparition of the bug to a specific version, but I am getting some weird compilation errors and do not want to dive into this rabbit hole...

**Comment by fmw42** [comment]
I am on a Mac. I install all my delegates with MacPorts, then install Imagemagick from source.  That would be a different way for you to it. I can give more details if you want.

**Comment by mranvick** [comment]
@fmw42 yes, I would appreciate it! (or if you just have a link towards some documentation on the topic) Thanks !

Anyway, I compiled the latest version from source 10.02.0 and the issue disappears, while the 10.01.2 (also compiled from source) exhibits it. So I guess it was introduced somewhere between the 9.53 and the 10.01.2 and then resolved in the 10.02.0. It's such a shame that the homebrew formula isn't the latest one..

I'll have a look at this if I find some time...

**Comment by fmw42** [comment]
What I have done for years is first download my delegates from MacPorts.  (Note that MacPorts unfortunately only has a delegate for Imagemagick 6, so one cannot just download a binary for Imagemagick 7 and not deal with the delegates separately).

Then I get the source for either Imagemagick 6 or Imagemagick 7 from https://imagemagick.org/archive/

Then in a terminal window, I do the following

```
./configure ...
make clean
make
sudo make install

```
My actual configure file is

```
./configure \
--enable-openmp  \
--enable-delegate-build --enable-shared --disable-static --disable-opencl \
--with-modules --with-quantum-depth=16 --without-wmf --with-rsvg --with-fftw \
--disable-silent-rules --disable-dependency-tracking --without-pango \
--with-lqr --with-gslib --with-gs-font-dir=/opt/local/share/ghostscript/fonts/

```

You will want to customize it as appropriate for you.


Here are some links to past notes that I have posted about this for earlier versions of Imagemagick and Mac OSX.  I am currently on Mac OSX Ventura.

http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=29100
and
http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=21502&p=88202&hilit=OSX+MacPorts#p88202

**Comment by mranvick** [comment]
@fmw42 Thank you very much, I'll give it a try!

In the meantime I created a new discussion to update the faulty homebrew formula [here](https://github.com/orgs/Homebrew/discussions/4788). I do not know if it was the appropriate place to do so, but hopefully someone will have a look at it, and anyway it'll be logged, that's something...

I think this issue can be closed since it is independent of ImageMagick in the end.
