### ISSUE TITLE
"About Display" window closes after a few seconds by itself 

### ISSUE THREAD

**Issue by Kojimboy** [ImageMagick/ImageMagick#6640]
### ImageMagick version

7.1.1.15

### Operating system

Linux

### Operating system, version and so on

ALT Workstation K 10.1 (sisyphus)

### Description

"About Display" window closes after a few seconds by itself 

### Steps to Reproduce

1. Open any image in ImageMagick:
$ display *.png/jpg/djvu (and e.t.c)
2. Left click on display -> Help -> About Display
3. Wait for 5-10 seconds

Actual result:
Notice window closes by itself 

Expected result:
Notice window stays on screen untill user closes it or presses "Dismiss" button

Reproduces on X11, Xfce and mate on other alt-linux distros

Also reproduces on ubuntu 22.04.3 LTS (Jammy Jellyfish)

**Comment by urban-warrior** [comment]
You image includes delay or loop metadata.  Try `display -delay 0 *.png`.

**Comment by Kojimboy** [comment]
Issue isn't related to specific image or file. If you just open display windows without any arguments `$ display` and then left click on display -> Help -> About Display. Notice window still closes by itself after few seconds

**Comment by urban-warrior** [comment]
Understood now.  The behavior is as designed.  We get notice banners on our Linux Desktop, for example, and they are ephemeral, after a few seconds they disappear.   Our preference is to keep the existing behavior unless there is a compelling reason to change it.
