### ISSUE TITLE
DICOM files using Q8 throws memory allocation failed

### ISSUE THREAD

**Issue by svenclaesson** [ImageMagick/ImageMagick#6643]
### ImageMagick version

7.1.1-15-portable-Q8-x64

### Operating system

Windows

### Operating system, version and so on

11

### Description

DCM file with more then 8 bits throws error (8 bits works fine) when using Q8 version of ImageMagick. 
All other formats i've tried with more then 8 bits still works with Q8.

This is very niche so feel free to close as "won't do" if you see fit.

### Steps to Reproduce

identify.exe MRBRAIN.DCM

will throw 

<code>identify.exe: memory allocation failed `C:\MRBRAIN.DCM' @ error/colormap.c/AcquireImageColormap/123.
identify.exe: memory allocation failed `C:\MRBRAIN.DCM' @ error/dcm.c/ReadDCMImage/4112.
</code>

### Images

[MRBRAIN.zip](https://github.com/ImageMagick/ImageMagick/files/12619879/MRBRAIN.zip)

**Comment by dlemstra** [comment]
Your are getting this error message because the Q8 version of ImageMagick has no support for colormaps of that size. Maybe we should improve the error message here @urban-warrior?

**Comment by urban-warrior** [comment]
We have enhanced the error message to state "colormap creation failure." The Q8 version of ImageMagick can only accommodate up to 256 colors, whereas your image demands a colormap with 4096 entries. The Q16 version of ImageMagick, on the other hand, can seamlessly handle the image without any issues.
