### ISSUE TITLE
unrecognized option with-lcms2

### ISSUE THREAD

**Issue by exekutive** [ImageMagick/ImageMagick#6646]
### ImageMagick version

7.1.1

### Operating system

MacOS

### Operating system, version and so on

13.5.2

### Description

Install-unix.txt file included in source code package for 7.1.1 lists this option in the 'Configure' section:

`    LCMS v2           --with-lcms2=yes		yes`

### Steps to Reproduce

Run configure 

`./configure --with-lcms2`

I get:

`configure: WARNING: unrecognized options: --with-lcms2
`

**Comment by fmw42** [comment]
Did you install the lcms2 delegate?

What do you get from

`magick -version`

does it list lcms?

**Comment by exekutive** [comment]
does any of that matter? the option isn't being recognized by configure.

**Comment by fmw42** [comment]
Yes, that option only is valid if you have lcms delegate installed.  You can tell it you want it, but if the delegate is not there it is meaningless.

**Comment by exekutive** [comment]
well that's a very confusing message then.
But yes 'little-cms2' is installed via homebrew.

**Comment by fmw42** [comment]
-- with lcms2 option in ./configure is not use if you have lcms2 installed and IM can see it in 

`magick -version`

If Homebrew installed it and not where IM can find it, then it won't show in magick -version and you will likely get that error message. Or perhaps that message is saying not to specify it if you have it installed.  Try without specifying --with lcms2

**Comment by exekutive** [comment]
libraries installed via homebrew are accessible in path env vars, so why wouldn't it see it?
> message is saying not to specify it if you have it installed.
that would be very odd and counter-intuitive. But no, that does not help

**Comment by urban-warrior** [comment]
`./configure --with-lcms2` works for us without complaint.  We're using ImageMagick-7.1.1-16 from the Github main repository.  If the validation of the LCMS2 library fails, check `config.log` to determine why, fix the issue, and try again until the delegate library validates-- then build ImageMagick.

**Comment by exekutive** [comment]
so I have the file:
`/opt/homebrew/include/lcms2.h`
which is sym linked to
`/opt/homebrew/Cellar/little-cms2/2.15/include/lcms2.h`
output from configure shows:
```
checking for lcms2 >= 2.0.0... yes
checking for lcms2/lcms2.h... no
```
why isn't configure finding it?

**Comment by urban-warrior** [comment]
Because `lcms2/lcm2.h` is not in your path.  To verify, carefully review `config.log`.  If its in a non-standard path, you may need to specify it with your CFLAGS environment variable.

**Comment by exekutive** [comment]
>lcms2/lcm2.h is not in your path

in what path? Where does configure look?

I already carefully reviewed the log. Searched for 'lcms' and looked for anything helpful. What am I looking for?

>  If its in a non-standard path

What is the "standard path" for lcms2?

**Comment by exekutive** [comment]
here is the log. Would love to hear your thoughts ...
[config.log](https://github.com/ImageMagick/ImageMagick/files/12641778/config.log)

**Comment by urban-warrior** [comment]
Here is the exception:

```
configure:32713: checking for lcms2/lcms2.h
configure:32713: gcc -c -I/opt/homebrew/Cellar/little-cms2/2.15/include -DHWY_SHARED_DEFINE -I/opt/homebrew/Cellar/libheif/1.16.2/include -I/opt/homebrew/Cellar/libde265/1.0.12/include -I/opt/homebrew/Cellar/x265/3.5/include -I/opt/homebrew/Cellar/aom/3.7.0/include -I/opt/homebrew/Cellar/libvmaf/2.3.1/include -I/opt/homebrew/Cellar/libvmaf/2.3.1/include/libvmaf -I/opt/homebrew/Cellar/jpeg-xl/0.8.2_1/include -I/opt/homebrew/Cellar/highway/1.0.7/include -I/opt/homebrew/Cellar/brotli/1.1.0/include -I/opt/homebrew/Cellar/little-cms2/2.15/include -I/opt/homebrew/Cellar/webp-full/1.3.0/include/webp -I/opt/homebrew/Cellar/graphviz/9.0.0/include/graphviz -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/Cellar/fontconfig/2.14.2/include -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/opt/libpng/include/libpng16   -I/opt/homebrew/Cellar/libzip/1.10.1/include  -Wall -g -O2 -fexceptions -D_FORTIFY_SOURCE=0 -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  conftest.c >&5
conftest.c:174:10: fatal error: 'lcms2/lcms2.h' file not found
```

So it can't find `lcms2/lcms2.h` in any of those paths.  Correct the problem and try `configure` again.

**Comment by exekutive** [comment]
Well, since my homebrew installation of lcms2 wasn't "standard", I decided to make it as standard as possible.
I installed lcms2 straight from source, and ran configure again

```
configure:32713: checking for lcms2/lcms2.h
configure:32713: gcc -c -I/usr/local/include -DHWY_SHARED_DEFINE -I/opt/homebrew/Cellar/libheif/1.16.2/include -I/opt/homebrew/Cellar/libde265/1.0.12/include -I/opt/homebrew/Cellar/x265/3.5/include -I/opt/homebrew/Cellar/aom/3.7.0/include -I/opt/homebrew/Cellar/libvmaf/2.3.1/include -I/opt/homebrew/Cellar/libvmaf/2.3.1/include/libvmaf -I/opt/homebrew/Cellar/jpeg-xl/0.8.2_1/include -I/opt/homebrew/Cellar/highway/1.0.7/include -I/opt/homebrew/Cellar/brotli/1.1.0/include -I/opt/homebrew/Cellar/webp-full/1.3.0/include/webp -I/usr/local/include -I/opt/homebrew/Cellar/graphviz/9.0.0/include/graphviz -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/opt/libpng/include/libpng16 -I/opt/homebrew/Cellar/fontconfig/2.14.2/include -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/opt/libpng/include/libpng16   -I/opt/homebrew/Cellar/libzip/1.10.1/include  -Wall -g -O2 -fexceptions -D_FORTIFY_SOURCE=0 -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16  conftest.c >&5
conftest.c:174:10: fatal error: 'lcms2/lcms2.h' file not found
```

the header file is right there:
`/usr/local/include/lcms2.h`
I have no clue why IM is looking in a subdirectory called 'lcms2'

So is it possible that where IM is looking is not standard, not my library paths?

**Comment by urban-warrior** [comment]
Try `/usr/local/include/lcms2/lcsm2.h`.

**Comment by exekutive** [comment]
seems like this has been a problem before
https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=28522

property.c was supposedly patched to fix this (I'm not a programmer). It should be finding the header just fine, without the subdirectory.  but it's not.
I'm totally lost

**Comment by exekutive** [comment]
> Try /usr/local/include/lcms2/lcsm2.h.

sorry but it seems to me that path is simply incorrect.

**Comment by urban-warrior** [comment]
We checked the script more carefully.  The `configure` script checks for liblcms and if found it checks if `lcms2/lcms2.h` exists.  If not, it reverts to `lcms2.h`.  So `/usr/local/include/lcms2.h` will work as long as `/usr/local/include` is one of your header search paths and the script finds liblcms2.  Look at the last lines of the configure script output.  What you want to see is this:

```
  LCMS              --with-lcms=yes                     yes
```

**Comment by exekutive** [comment]
that line is present, yes. But that's lcms version 1, not version 2

**Comment by urban-warrior** [comment]
ImageMagick requires LCMS version 2 or above.  It will not work with version 1.

**Comment by exekutive** [comment]
we know `/usr/local/include` is in the search path because log shows:
`configure:32713: gcc -c -I/usr/local/include`
right?

**Comment by exekutive** [comment]
from 'install-unix.txt' file:
```
LCMS v1           --with-lcms=yes		yes
LCMS v2           --with-lcms2=yes		yes
```
sdf

**Comment by urban-warrior** [comment]
Right.  Check the permissions of `/usr/local/include/lcsm2.h`.

**Comment by exekutive** [comment]
`-rw-r--r--  1 root  admin   103K 16 Sep 17:37 lcms2.h`

**Comment by exekutive** [comment]
so I created a subdirectory `/usr/local/include/lcms2` and created a sym link `/usr/local/include/lcms2/lcms2.h` pointing back to `/usr/local/include/lcms2.h` and configure no longer complains.
Running `magick -version` shows:
`Delegates (built-in): bzlib fontconfig freetype gvc heic jng jp2 jpeg jxl lcms lzma openexr pangocairo png raw tiff webp x xml zip zlib`
which is the same as before.

**Comment by exekutive** [comment]
>the configure script must find lcms2.pc in your package config cache

and how do I know if it found it or not? There is no mention of the file in config.log
The file is present in what appear to be the standard directory `/usr/local/lib/pkgconfig/lcms2.pc`
The contents are:

```
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: lcms2
Description: LCMS Color Management Library
Version: 2.15
Libs: -L${libdir} -llcms2 
Libs.private: -lm -lpthread
Cflags: -I${includedir}

```

**Comment by urban-warrior** [comment]
Notice that the delegates include LCMS.  You have now have LCMS support in your release of ImageMagick.

**Comment by exekutive** [comment]
oops pardon me, there are still complaints in config.log
`configure:41454: WARNING: unrecognized options: --with-lcms2`

>  Notice that the delegates include LCMS
shouldn't it say lcms2?

**Comment by exekutive** [comment]
so I ran `magick -list configure` and it shows:
`LIBS                    -L/usr/local/lib -llcms2  ...`
So I guess it's fine.
Maybe the option `with-lcms2` simply doesn't exist any more, and v2 is just called lcms now.
In that case the documentation should be updated.
