### ISSUE TITLE
`Magick::SetSecurityPolicy` / `MagickCore::SetMagickSecurityPolicy` return true on completely invalid XML

### ISSUE THREAD

**Issue by mmomtchev** [ImageMagick/ImageMagick#6649]
### ImageMagick version

`HEAD`

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04

### Description

`Magick.SetSecurityPolicy("invalid");` returns `true` without doing anything

### Steps to Reproduce

`Magick.SetSecurityPolicy("invalid");`

**Comment by mmomtchev** [comment]
Although this isn't a vulnerability *per se*, it probably warrants a security advisory

**Comment by urban-warrior** [comment]
ImageMagick does not perform validation.  In the docs, we request that the security policy by validated @ https://imagemagick-secevaluator.doyensec.com/ and that it be verified with `magick -list policy`.  As such, the advisory is already encoded in the docs.

**Comment by mmomtchev** [comment]
Although the online tool is excellent, I think that this a violation of the best practices in security. Currently, it is difficult to check anything especially when using the library embedded in another software.

Failing to load/parse the specified security policy should be a fatal error that prevents the program from running.

I see that the security policy parser is hand-made. ImageMagick includes a `libxml2` dependency which would be a far better choice, but I guess that you want to preserve its status as an optional dependency?

I will try to add some error-checking to the parser.

**Comment by urban-warrior** [comment]
It's simple enough to check the security policy.  On start-up or after you call SetSecurityPolicy(), call MagickCore::GetPolicyList() to validate or MagickCore::IsRightsAuthorized() (e.g., check to ensure the HTTP decoder is blocked) from within your Magick++/MagickCore wrapper program.  In the mean-time, we'll add a basic validator.  We don't want to add a deeper validator as it could cause a performance hit on the ImageMagick API start-up time plus, as mentioned, we encourage users to validate their policies against https://imagemagick-secevaluator.doyensec.com/ which is a deep and robust validator.
