### ISSUE TITLE
Error in resulting composite when using -normalize

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#6653]
### ImageMagick version

7.1.0.16

### Operating system

MacOS

### Operating system, version and so on

OSX Ventura

### Description

When using IM 6.9.12-94, the following works fine and we see both the color and the checkerboard:

`convert -size 150x150 pattern:checkerboard -normalize xc:"rgba(255,0,0,0.5)" -composite -depth 8 x0.png`

![x0](https://github.com/ImageMagick/ImageMagick/assets/13458218/becf6d00-e0a7-4076-8bbc-d4f4f76bf74f)

But the same command does not show the color in IM 7, if -normalize is in the command:

`magick -size 150x150 pattern:checkerboard -normalize xc:"rgba(255,0,0,0.5)" -composite -depth 8 x1.png`

![x1](https://github.com/ImageMagick/ImageMagick/assets/13458218/737156fb-3a51-48e8-8a94-3c10e2b7e39b)

If -normalize is remove, the color and checkerboard show properly:

`magick -size 150x150 pattern:checkerboard xc:"rgba(255,0,0,0.5)" -composite -depth 8 x2.png`

![x2](https://github.com/ImageMagick/ImageMagick/assets/13458218/ea3c4107-1411-4279-9b6a-d8c5fa929a0c)

### Steps to Reproduce

See above

### Images

See above

**Comment by snibgo** [comment]
Writing to `info:` explains the problem:
```
D:\temp>%IMG7%magick -size 150x150 pattern:checkerboard info:
pattern:checkerboard PATTERN 150x150 150x150+0+0 16-bit sRGB 0.000u 0:00.000

D:\temp>%IMG7%magick -size 150x150 pattern:checkerboard -normalize info:
pattern:checkerboard PATTERN 150x150 150x150+0+0 16-bit Gray 0.000u 0:00.000
```
The pattern:checkerboard image contains only gray pixels, but it has 3 colour channels. `-normalize` realises that the image has no coloured pixels, and changes the colorspace from sRGB to gray. So the first image to your `-composite` has only one channel, and the output inherits that.

A fix is "`-set colorspace sRGB`":
```
D:\temp>%IMG7%magick -size 150x150 pattern:checkerboard -normalize -set colorspace sRGB info:
pattern:checkerboard PATTERN 150x150 150x150+0+0 16-bit sRGB 0.000u 0:00.000
```

**Comment by fmw42** [comment]
Thanks, Snibgo, that make sense.  It was a change going from IM 6 to IM 7 that broke this command in an old script. I forgot about the number of channels issue/change.
