### ISSUE TITLE
montage.t tests failing

### ISSUE THREAD

**Issue by dotlambda** [ImageMagick/ImageMagick#6655]
### ImageMagick version

7.1.1-16

### Operating system

Linux

### Operating system, version and so on

NixOS

### Description

I'm trying to update ImageMagick in nixpkgs and noticed that PerlMagick's test suite has failing tests with the new version:
```
t/blob.t .......... ok
t/composite.t ..... ok
t/filter.t ........ ok
t/getattribute.t .. ok
t/montage.t ....... Failed 2/19 subtests
t/ping.t .......... ok
t/read.t .......... ok
t/setattribute.t .. ok
t/write.t ......... ok

Test Summary Report
-------------------
t/montage.t     (Wstat: 0 Tests: 19 Failed: 2)
  Failed tests:  12-13
Files=9, Tests=273,  3 wallclock secs ( 0.09 usr  0.02 sys +  4.33 cusr  1.20 csys =  5.64 CPU)
Result: FAIL
Failed 1/9 test programs. 2/273 subtests failed.
```

### Steps to Reproduce

Run `nix-build -A perlPackages.ImageMagick` on https://github.com/NixOS/nixpkgs/pull/255817.
The version of the Perl package is 7.1.0-0.

**Comment by urban-warrior** [comment]
We fix that issue in the main repo.  We'll issue another release likely by tomorrow.

**Comment by dotlambda** [comment]
I get the same issue with ImageMagick 7.1.1-17. Maybe we need a new release on https://metacpan.org/pod/Image::Magick?
