### ISSUE TITLE
GPS location read incorrectly

### ISSUE THREAD

**Issue by SpectralFlame** [ImageMagick/ImageMagick#6656]
### ImageMagick version

7.1.1-16

### Operating system

Linux

### Operating system, version and so on

6.5.3-arch1-1

### Description

I use the command `identify -format '%[EXIF:GPS*]' image.jpg` to get the GPS information from my images.

Since I updated to version 7.1.1-16, it reports an incorrect latitude: `exif:GPSLatitude=49/1, 49/1, 49/1` while `feh --draw-exif image.jpg` reports the correct latitude: `49, 30, 34.3799`. It seems that `identify` simply copies the first number 3 times.

Note that this error happens for GPSLatitude, GPSLongitude and GPSTimeStamp.

### Steps to Reproduce

- Take an image with known GPS coordinates
- Run `identify -format '%[EXIF:GPS*]' image.jpg`

The GPS coordinates and timestamp don't match up with the actual coordinates & timestamp

### Images

[Uploading example.zip…]()

**Comment by dlemstra** [comment]
Please add an image that can be used to reproduce this issue.

**Comment by urban-warrior** [comment]
We'll need an example.  In our sample image with GPS, we get expected results:

```    
    exif:GPSLatitude: 41.000000,53.000000,20.212800
    exif:GPSLatitudeRef: N
    exif:GPSLongitude: 87.000000,37.000000,28.178400
    exif:GPSLongitudeRef: W
```

**Comment by SpectralFlame** [comment]
My bad, here's an example: https://drive.google.com/file/d/1ut_6YRnj72E4pYxaocJrtg1SIsupOMWQ/view?usp=sharing

I get these results
```
exif:GPSLatitude=51/1, 51/1, 51/1
exif:GPSLatitudeRef=N
exif:GPSLongitude=17/1, 17/1, 17/1
exif:GPSLongitudeRef=E
exif:GPSTimeStamp=12/1, 12/1, 12/1
```

`feh` gives me: `GPS: N 51, 5, 34.2095 , E 17, 1, 10.9919`

**Comment by AminoffZ** [comment]
Can confirm same issue on Windows portable

```
$ ./magick identify -format '%[EXIF:GPS*]' test.jpg
exif:GPSAltitude=166876/1000
exif:GPSAltitudeRef=.
exif:GPSDateStamp=2023:09:06
exif:GPSInfo=5248,
exif:GPSLatitude=51/1, 51/1, 51/1
exif:GPSLatitudeRef=N
exif:GPSLongitude=17/1, 17/1, 17/1
exif:GPSLongitudeRef=E
exif:GPSProcessingMethod=ASCII
exif:GPSTimeStamp=12/1, 12/1, 12/1
```

**Comment by dlemstra** [comment]
Can you please add the file to the issue instead of a link so we make sure we keep the file? You might need to zip it before adding it here.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ within a few days.

**Comment by SpectralFlame** [comment]
> Can you please add the file to the issue instead of a link so we make sure we keep the file? You might need to zip it before adding it here.

I tried editing the initial issue, but I'm not sure if I added it correctly.
