### ISSUE TITLE
Incorrect Font kerning

### ISSUE THREAD

**Issue by CollinHeist** [ImageMagick/ImageMagick#6658]
### ImageMagick version

7.1.1-16 Q16-HDRI aarch64 21560

### Operating system

MacOS

### Operating system, version and so on

MacOS Ventura 13.5.1 ARM

### Description

When annotating text with a specific Font, the kerning of some letters is incorrect. I edited the Font to add custom kerning pairs, but these have no effect.

I expect either the kerning to be correct in the first place, or the use of the modified kerning pairs present in the font.

I am using Freetype v2.13.2.

### Steps to Reproduce

1. Download the attached Font files [here](https://github.com/ImageMagick/ImageMagick/files/12667543/SlashSignature-ModifiedKerning.otf.zip)
2. Execute the following command:
    ```
    magick -size 800x400 xc:black -font SlashSignature-ModifiedKerning.otf -pointsize 150 -fill white -gravity center -annotate +0+0 "Fe Te" out.png
    ```
3. Observe the resulting image - the distance between `F` and `e`, as well as `T` and `e` (I haven't tested other letters) is far too large.
   ![out](https://github.com/ImageMagick/ImageMagick/assets/17693271/7d359aeb-c824-46a6-b11b-7232b29a8a96)
4. Compare this to the _expected_ result (see below - generated elsewhere)
    ![good-ref](https://github.com/ImageMagick/ImageMagick/assets/17693271/8d85d233-7d30-4835-ae06-5c98c3c8e2f5)

**Comment by urban-warrior** [comment]
Annotation is data driven.  We rely on the attributes returned by Freetype to space the resulting rendering.  Add `-debug annotate` to your command to view the glyph attributes.  If the rendering is not proper, the issue is the font, Freetype, or ImageMagick.  If you can prove the issue is with ImageMagick, we will investigate further.

**Comment by CollinHeist** [comment]
Thanks for the quick reply. Debug output below:
```
2023-09-20T01:24:30+00:00 0:00.007 0.000u 7.1.1 Annotate magick[58148]: annotate.c/RenderFreetype/1786/Annotate
  Font ./SlashSignature-ModifiedKerning.otf; font-encoding none; text-encoding none; pointsize 150
2023-09-20T01:24:30+00:00 0:00.007 0.000u 7.1.1 Annotate magick[58148]: annotate.c/GetTypeMetrics/943/Annotate
  Metrics: text: Fe Te; width: 585; height: 258; ascent: 173; descent: -86; max advance: 1303; bounds: -4.0625,-19.2188  222.422,121.328; origin: 584.531,0; pixels per em: 150,150; underline position: 0; underline thickness: 0
2023-09-20T01:24:30+00:00 0:00.007 0.000u 7.1.1 Annotate magick[58148]: annotate.c/RenderFreetype/1786/Annotate
  Font ./SlashSignature-ModifiedKerning.otf; font-encoding none; text-encoding none; pointsize 150
```

---

I suspect it's not the font because I am able to create an image with the same font that has the proper kerning. I agree it could be FreeType, I wasn't sure how to verify that.

**Comment by fmw42** [comment]
What tool did you use to generate your "good" result?

**Comment by CollinHeist** [comment]
I used [Photopea](https://www.photopea.com/) (a free Photoshop alternative)

**Comment by fmw42** [comment]
And the very same font file (not just font name)? 

Perhaps that tool is ignoring some of the font glyph metrics and Imagemagick is using them?

**Comment by CollinHeist** [comment]
The very same - I uploaded the Font into the program directly (it's not a built-in font).

That seems possible.. Does ImageMagick use just the glyph metrics, or does it also look at and utilize kerning pairs? Or is all of that just delegated to Freetype

**Comment by CollinHeist** [comment]
Thanks for the help - I was able to modify the Font to use a `kern` table in addition to the `GPOS` kerning pair tables after seeing #3905 that has fixed this issue. Thanks!
