### ISSUE TITLE
FFT IFT Round Trip fails to produce the proper image

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#6660]
### ImageMagick version

7.1.1.16

### Operating system

MacOS

### Operating system, version and so on

Mac OSX Ventura

### Description

The following fft ift round trip fails to produce the proper resulting image.

Input Logo: Image:

![logo](https://github.com/ImageMagick/ImageMagick/assets/13458218/e4b35e6a-93cd-478f-9cc5-f9cac143f090)

`magick logo: -fft -ift logo_fft_ift.png`

![logo_fft_ift](https://github.com/ImageMagick/ImageMagick/assets/13458218/94b81937-c28a-4f49-9e02-53c7f430453f)

Note: it fails also the same way in IM 6.9.12-94

The result is proper when using IM 7.1.1.8. 
(Testing shows it works fine up to IM 7.1.1.15 and fails at 7.1.1.16 and now also at 7.1.1.17)

Here is the result from IM 7.1.1.8

![logo_fft_ift](https://github.com/ImageMagick/ImageMagick/assets/13458218/7b2b759b-4c01-485b-a7c1-370ed8e4341e)

(There are excess pixels at the bottom due to the original input image being non-square and being squared off in the FFT processings, which is proper here and should be cropped at the end as post processing in a subsequent command.)

### Steps to Reproduce

See above

### Images

See above

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce the issue and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
