### ISSUE TITLE
Trying to compile fftw on Windows, but doesn't work

### ISSUE THREAD

**Issue by xanatos** [ImageMagick/ImageMagick#6667]
### ImageMagick version

7.1.1-18 (Beta)

### Operating system

Windows

### Operating system, version and so on

Windows 11, Visual Studio 2022 17.7.3

### Description

I'm trying to compile fftw on Windows. Sadly the "official" builds for Windows doesn't seem to include it.
Successfully compiled with latest https://github.com/ImageMagick/ImageMagick-Windows on Visual Studio 2022 17.7.3 Release x64

> magick -version

gives me

```
Version: ImageMagick 7.1.1-18 (Beta)  Q16-HDRI x64 a9ff2e491:20230921 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Channel-masks(64-bit) Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo fftw freetype gslib heic jbig jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (193732822)
```

but then

> magick logo: -fft -ift logo_fft_ift.png

gives me:

```
magick: DelegateLibrarySupportNotBuiltIn `LOGO' (FFTW) @ warning/fourier.c/ForwardFourierTransformImage/917.
magick: ImageSequenceRequired `-ift' @ error/operation.c/CLIListOperatorImages/4340.

```

(I'm in the D:\ImageMagick-Windows\VisualMagick\bin where I compiled the magick.exe, and there is no other magick in the path)

In the configure.exe I only change (checking) the "Build Projects that are not compatible with the Apache 2.0 license", leaving everything else as-is (so Dynamic multi-threaded DLL runtimes). A CORE_RL_fftw_.dll has been generated in the bin folder together with the magick,exe

### Steps to Reproduce

Explained in description

**Comment by xanatos** [comment]
From a quick analysis, it seems that the fourier.c file is quite full of:

> #if defined(MAGICKCORE_FFTW_DELEGATE) && !defined(__cplusplus) && !defined(c_plusplus)

But the CORE_MagickCore is defined as a C++ project (/TP)

**Comment by dlemstra** [comment]
Feel free to post a pull request to make this work again. We are not actively checking if this build still works. We had to switch to C++ because of 64-bit channels masks. I might take a look at this in the future again but I don't know when that will happen.

**Comment by xanatos** [comment]
@dlemstra Thanks. I could have made it compile on VC++, but for sure I couldn't have fixed it "in the right way" for Windows+Linux+MacOSX+??? (so it would have been an "it works on my machine")

**Comment by dlemstra** [comment]
I added a patch that should resolve your issue today. Can you check if that works for you?

**Comment by xanatos** [comment]
Compiles and works under VS 2022
