### ISSUE TITLE
assertion failure in DestroyImage

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#671]
Version: ImageMagick 7.0.6-6 Q16 x86_64

An assertion failure was found in function DestroyImage in MagickCore/image.c,which allow attackers to cause a denial of service via a crafted file.
```
#./identify $FILE
identify: MagickCore/image.c:1185: Image *DestroyImage(Image *): Assertion `image != (Image *) ((void*)0)' failed.
Aborted
```
testcase:https://github.com/bestshow/p0cs/blob/master/assertion_failure_in_DestroyImage1185
Credit:ADLab of Venustech

**Comment by urban-warrior** [comment]
Unfortunately, we cannot reproduce the problem you posted with the latest ImageMagick release, 7.0.6-7.  We get:

```
$ identify assertion_failure_in_DestroyImage1185 
identify: unexpected end-of-file 'assertion_failure_in_DestroyImage1185': No such file or directory @ error/xcf.c/ReadXCFImage/1305.
identify: insufficient image data in file `assertion_failure_in_DestroyImage1185' @ error/xcf.c/ReadOneLayer/807.
identify: memory allocation failed `assertion_failure_in_DestroyImage1185' @ error/xcf.c/ReadXCFImage/1354.
```

**Comment by dlemstra** [comment]
@bestshow Can you still reproduce this with the latest version of ImageMagick?

**Comment by bestshow** [comment]
@dlemstra The issue was solved on the latest ImageMagick release.
