### ISSUE TITLE
[question] choosing correct library

### ISSUE THREAD

**Issue by msx752** [ImageMagick/ImageMagick#673]
@dlemstra 
hi, i am using .net core 1.1(only windows platform) and i want to use WriteablePixelCollection with RGBA and also needs draw image into specific x,y,w,h, which libraries should i use. There are many libraries in here but i couldn't find correct one.

- ImageMagick Qx16 is not have WriteablePixelCollection, it is readonly.

note: (i am working on high resolution like 11000x8000) so ImageMagick is the best library i have seen.

Thanks.

**Comment by dlemstra** [comment]
The Magik.NET project has its own [issues page](https://github.com/dlemstra/Magick.NET/issues) so you should use that next time.

The `WriteablePixelCollection`  class has been removed a while back. The `GetPixels` method returns a `PixelCollection` that has various `Set..` methods that you can use to change the pixels.
