### ISSUE TITLE
ChangeLog.md  is missing in the tarball release.

### ISSUE THREAD

**Issue by marillat** [ImageMagick/ImageMagick#6736]
### ImageMagick version

7.1.1.18

### Operating system

Linux

### Operating system, version and so on

Debian unstable

### Description

I noticed a [.auto-changelog](https://github.com/ImageMagick/ImageMagick/blob/main/.auto-changelog) supposed to generate a ChangeLog.md but this file is missing since a long time.

Really annoying.

Christian 

### Steps to Reproduce

I don't know.

**Comment by urban-warrior** [comment]
We generate `ChangeLog.mf` at release time and store it @ https://github.com/ImageMagick/Website/blob/main/ChangeLog.md rather than in the source distribution.

**Comment by marillat** [comment]
It's annoying for people who wants to build imagemagick from source.

We need to open a browser to read the ChangeLog instead of a simple ```less ChangeLog```

**Comment by urban-warrior** [comment]
@dlemstra you suggested we remove `ChangeLog.md` from the source distribution.  Given this discussion, should we restore it?

**Comment by dlemstra** [comment]
I don't think we should. Our changelog file is based on our git commit history and it makes no sense to have that in a file inside our repository also. Having this on the website should be sufficient enough.
