### ISSUE TITLE
montage.t tests still failing

### ISSUE THREAD

**Issue by dotlambda** [ImageMagick/ImageMagick#6737]
### ImageMagick version

7.1.1-18

### Operating system

Linux

### Operating system, version and so on

NixOS

### Description

https://github.com/ImageMagick/ImageMagick/issues/6655 was closed without being fixed

### Steps to Reproduce

Download the Perl package from CPAN and run its test against ImageMagick >= 7.1.1-16.

**Comment by urban-warrior** [comment]
It takes a few days for the uploaded patch to land properly in CPAN.  Try again in a few days.

**Comment by dlemstra** [comment]
Next time please wait for a reply in that other issue.
