### ISSUE TITLE
PerlMagick Compose with dissolve does not work

### ISSUE THREAD

**Issue by hakonhagland** [ImageMagick/ImageMagick#6738]
### ImageMagick version

7.1.0

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04

### Description

Trying the test case with dissolve on line 119: 

https://github.com/ImageMagick/ImageMagick/blob/25e3a4f3845f59536d19aba0ac0580aa6715147f/PerlMagick/demo/compose-specials.pl#L119

the destination disappears completely for all values of `args` that I have tested: Example for args = 50:

![test](https://github.com/ImageMagick/ImageMagick/assets/6708379/e0e50a1c-6beb-4a35-a97c-cef91b356545)

Here is the code I am using:

```perl
use strict;
use warnings;
use feature qw(say);
use Image::Magick;

my $dest=Image::Magick->new();
$dest->Read('logo:');
$dest->Crop('100x100+400+100');  # wizards hat
$dest->Set(page=>'0x0+0+0');
$dest->Set(alpha=>'Set');

# Source, Composite or Overlay image
my $src=Image::Magick->new();
$src->Set(size=>'80x80');
$src->Read('gradient:black-white');
$src->Set(alpha=>'Set');

my $offset="+10+10";

$dest->Composite(
  image=>$src,
  compose=>'dissolve',
  args=>'50',
  geometry=>$offset,
);

{
    my $error = $dest->Write( 'test.jpg' );
    die "Cannot write new.jpg: $error" if $error;
}
```

Expected output would be somthing like:

![test](https://github.com/ImageMagick/ImageMagick/assets/6708379/e1a526eb-371c-41ca-a19b-3778c5679561)

### Steps to Reproduce

Run the shown perl code (perl 5.36) to reproduce.

**Comment by snibgo** [comment]
The example in your link has:
```
args=>'50x50'
```
... but you have just:
```
args=>'50'
```
Does that help?

**Comment by hakonhagland** [comment]
> args=>'50x50' : Does that help?

@snibgo Unfortunately it does not help.

**Comment by wanradt** [comment]
> Does that help?

Actually, there are two examples: "50" and "50x50", but neither works.

**Comment by hakonhagland** [comment]
> Expected output would be something like:

The expected output can be obtained by running `composite` like this:

```
$ composite -dissolve 50% -gravity South src.png dest.jpg new.jpg
```
where `src.png` is obtained by saving above `$src` and `dest.png` is obtained by saving `$dest` to `dest.jpg`. This gives:

![new](https://github.com/ImageMagick/ImageMagick/assets/6708379/fdf3904f-8220-4138-93a3-15496362c54e)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce the issue and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.
