### ISSUE TITLE
Wrong exit status code

### ISSUE THREAD

**Issue by Sur3** [ImageMagick/ImageMagick#6744]
### ImageMagick version

7.1.1.15

### Operating system

Linux

### Operating system, version and so on

Gentoo Linux

### Description

I lost a bunch of files because I had a typo in my shellscript and imagemagick returned a success exit code despite not finding the files.

### Steps to Reproduce

Way to replicate:

`convert nonexistingfile.png && echo success`

Running this wrong command prints a help messages and then exits with success code echoing success. Instead it should return a non-zero exit code!

**Comment by snibgo** [comment]
Why are you using `convert`? This gives you the very old v6 syntax, and returns `0` in your case. I suggest using `magick` (and not `magick convert`), to get the superior v7 syntax, which also returns `1`.

**Comment by Sur3** [comment]
Well it just felt fitting to convert images with the convert command though and I don't know about the new magick syntax and didn't see any news that the convert command is deprecated..?
Still I think this is a bug that should be fixed as long as the convert frontend is delivered.

**Comment by snibgo** [comment]
The documentation (eg https://imagemagick.org/script/command-line-processing.php and https://imagemagick.org/script/convert.php) uses `magick`, not `convert`. `convert` is still supported for backwards compatibility. I do not recommend its use in new work.

See also https://imagemagick.org/script/porting.php :
> The "magick" command is the new primary command of the Shell API, replacing the old "convert" command.

Still, I agree that `convert` should return `1` in your command.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce the issue and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/archive/beta/ by sometime tomorrow.

**Comment by dischglv** [comment]
Trying to build ImageMagick, seems there is a typo [https://github.com/ImageMagick/ImageMagick/blob/ffe980977cbae8fb556be9b765a217e3986a9aef/MagickWand/montage.c#L333](MontgageUsage)

**Comment by dlemstra** [comment]
The typos has been fixed. Next time feel free to open a pull request to help us fix these things.
