### ISSUE TITLE
PerlMagic installation using --without-perl configure option: No rule to make target 'Q16HDRI.pm'

### ISSUE THREAD

**Issue by hakonhagland** [ImageMagick/ImageMagick#6763]
### ImageMagick version

7.1.0

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04

### Description

According to the [documentation](https://imagemagick.org/script/advanced-linux-installation.php):

>When --without-perl is specified, you must first install ImageMagick, change to the PerlMagick subdirectory, build, and finally install PerlMagick.

I tried this on Ubuntu 22.04:

```
$ git clone --depth=1 git@github.com:ImageMagick/ImageMagick.git
$ cd ImageMagick
$ ./configure --without-perl --prefix=/opt/image-magick3
$ make
$ sudo make install
$ cd PerlMagick
$ perl Makefile.PL
Checking if your kit is complete...
Looks good
Warning: -L../MagickCore/.libs changed to -L/home/hakon/test/ImageMagick/PerlMagick/../MagickCore/.libs
Warning: -L../../MagickCore/.libs changed to -L/home/hakon/test/ImageMagick/PerlMagick/default/../../MagickCore/.libs
Writing MYMETA.yml and MYMETA.json
Warning: -L../../MagickCore/.libs changed to -L/home/hakon/test/ImageMagick/PerlMagick/quantum/../../MagickCore/.libs
Writing MYMETA.yml and MYMETA.json
Generating a Unix-style Makefile
Writing Makefile for Image::Magick
Writing MYMETA.yml and MYMETA.json

$ make
cp Magick.pm blib/lib/Image/Magick.pm
AutoSplitting blib/lib/Image/Magick.pm (blib/lib/auto/Image/Magick)
make[1]: Entering directory '/home/hakon/test/ImageMagick/PerlMagick/default'
cp Magick.pm ../blib/lib/Image/Magick.pm
Manifying 1 pod document
make[1]: Leaving directory '/home/hakon/test/ImageMagick/PerlMagick/default'
make[1]: Entering directory '/home/hakon/test/ImageMagick/PerlMagick/quantum'
make[1]: *** No rule to make target 'Q16HDRI.pm', needed by 'pm_to_blib'.  Stop.
make[1]: Leaving directory '/home/hakon/test/ImageMagick/PerlMagick/quantum'
make: *** [Makefile:545: subdirs] Error 2

```
Here are the complete log files from the previous build steps: 
[configure_log.txt](https://github.com/ImageMagick/ImageMagick/files/12829474/configure_log.txt)
[make_log.txt](https://github.com/ImageMagick/ImageMagick/files/12829480/make_log.txt)
[make_install_log.txt](https://github.com/ImageMagick/ImageMagick/files/12829483/make_install_log.txt)

(NOTE: If I use the `--with-perl` configure option instead, it works fine, i.e. no errors when running `sudo make install`. So this question is specifically about the `---without-perl` configure option)

### Steps to Reproduce

See description

**Comment by sisyphus** [comment]
I get essentially the same error with Strawberry Perl 5.38.0 on Windows 11:
```
D:\s\ImageMagick\PerlMagick>gmake
cp Magick.pm blib\lib\Image\Magick.pm
AutoSplitting blib\lib\Image\Magick.pm (blib\lib\auto\Image\Magick)
gmake[1]: Entering directory 'D:/s/ImageMagick/PerlMagick/default'
cp Magick.pm ..\blib\lib\Image\Magick.pm
gmake[1]: Leaving directory 'D:/s/ImageMagick/PerlMagick/default'
gmake[1]: Entering directory 'D:/s/ImageMagick/PerlMagick/quantum'
gmake[1]: *** No rule to make target 'Q16HDRI.pm', needed by 'pm_to_blib'.  Stop.
gmake[1]: Leaving directory 'D:/s/ImageMagick/PerlMagick/quantum'
gmake: *** [makefile:537: subdirs] Error 2
```
Cheers,
Rob

**Comment by urban-warrior** [comment]
We updated the documentation.  When `--without-perl` is specified, you must first install ImageMagick, download the [PerlMagick](https://imagemagick.org/archive/perl/) source distribution, build, and finally install PerlMagick.

**Comment by hakonhagland** [comment]
>We updated the documentation

@urban-warrior Thanks!

> download the [PerlMagick](https://imagemagick.org/archive/perl/) source distribution, build, and finally install PerlMagick.

I will test this later today. A quick question about the documentation. If I go to this page: https://imagemagick.org/script/perl-magick.php (instead of the other page https://imagemagick.org/script/advanced-linux-installation.php) it says:

> you must install PerlMagick from the ImageMagick source distribution. Download the latest [source](https://imagemagick.org/archive/ImageMagick.tar.gz) release.

but this link refers to another page.. It is confusing, maybe this page also need to be updated?

**Comment by urban-warrior** [comment]
The documentation is correct.  The recommended PerlMagick install is from the ImageMagick source distribution with the `--with-perl` configure script command-line argument.

**Comment by hakonhagland** [comment]
> download the [PerlMagick](https://imagemagick.org/archive/perl/) source distribution, build, and finally install PerlMagick.
>
> I will test this later today

@urban-warrior I tested this now from a docker container running Ubuntu 22.04 and I get a failed tests, see:
https://github.com/ImageMagick/ImageMagick/issues/6767

**Comment by hakonhagland** [comment]
Since #6767 is partially resolved now, I close this.
