### ISSUE TITLE
PerlMagick installation: make test: Magick.so: undefined symbol: DestroyImageInfo

### ISSUE THREAD

**Issue by hakonhagland** [ImageMagick/ImageMagick#6767]
### ImageMagick version

7.1.0

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04, docker image

### Description

I am trying to install PerlMagick on Ubuntu 22.04, perl 5.34.0:

```
$ git clone --depth=1 https://github.com/ImageMagick/ImageMagick.git
$ cd ImageMagick
$ ./configure --without-perl
$ make
$ sudo make install
$ cd ..
$ mkdir PerlMagick
$ cd PerlMagick
$ wget https://imagemagick.org/archive/perl/Image-Magick-7.1.1-18.tar.gz
$ tar zxvf Image-Magick-7.1.1-18.tar.gz
$ cd Image-Magick-7.1.1-18
$ perl Makefile.PL INC="-I/usr/local/include/ImageMagick-7" LIBS="-L/usr/local/lib/"
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Image::Magick
Writing MYMETA.yml and MYMETA.json

$ make
cp Magick.pm blib/lib/Image/Magick.pm
AutoSplitting blib/lib/Image/Magick.pm (blib/lib/auto/Image/Magick)
Running Mkbootstrap for Magick ()
chmod 644 "Magick.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Magick.bs blib/arch/auto/Image/Magick/Magick.bs 644
"/usr/bin/perl" "/usr/share/perl/5.34/ExtUtils/xsubpp"  -typemap '/usr/share/perl/5.34/ExtUtils/typemap' -typemap '/home/docker-user/Image-Magick-7.1.1/typemap'  Magick.xs > Magick.xsc
mv Magick.xsc Magick.c
x86_64-linux-gnu-gcc -c  -I/usr/local/include/ImageMagick-7 -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/include/freetype2 -g -O2 -Wall -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -O2 -g   -DVERSION=\"7.1.1\" -DXS_VERSION=\"7.1.1\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.34/CORE"  -D_LARGE_FILES=1 -DHAVE_CONFIG_H Magick.c
rm -f blib/arch/auto/Image/Magick/Magick.so
x86_64-linux-gnu-gcc  -L/usr/local/lib -lMagickCore-7.Q16HDRI -shared -L/usr/local/lib -fstack-protector-strong   Magick.o  -o blib/arch/auto/Image/Magick/Magick.so  \
      \
  
chmod 755 blib/arch/auto/Image/Magick/Magick.so
Manifying 1 pod document

$ make test
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Magick.bs blib/arch/auto/Image/Magick/Magick.bs 644
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/blob.t .......... 1/1 Can't load '/home/docker-user/Image-Magick-7.1.1/blib/arch/auto/Image/Magick/Magick.so' for module Image::Magick: /home/docker-user/Image-Magick-7.1.1/blib/arch/auto/Image/Magick/Magick.so: undefined symbol: DestroyImageInfo at /usr/lib/x86_64-linux-gnu/perl-base/DynaLoader.pm line 187.
 at t/blob.t line 20.
Compilation failed in require at t/blob.t line 20.
BEGIN failed--compilation aborted at t/blob.t line 20.
&Image::Magick::constant not defined. The required ImageMagick libraries are not installed or not installed properly.
END failed--call queue aborted at t/blob.t line 20.
t/blob.t .......... Dubious, test returned 22 (wstat 5632, 0x1600)
Failed 1/1 subtests 
```

### Steps to Reproduce

See description

**Comment by urban-warrior** [comment]
Your command-set works for us.  PerlMagick tests complete without complaint.  We did configure ImageMagick with the `--with-modules` option, however, it should work without it.  You may need to add `/home/docker-user/Image-Magick-7.1.1/blib/arch/auto/Image/Magick/` to your dynamic load path for it to work.

**Comment by hakonhagland** [comment]
> Your command-set works for us.

@urban-warrior Interesting. Can you share the exact commands you used, then I can try reproduce those locally?

**Comment by urban-warrior** [comment]
In our environment, we installed ImageMagick after building with `./configure --with-modules --with-perl`.  For this use case, we removed the `--with-perl` option and instead downloaded the PerlMagick source and built and tested without issue.

**Comment by hakonhagland** [comment]
> removed the --with-perl option

@urban-warrior Don't you also need to give `--without-perl` ? According to the [documentation](https://imagemagick.org/script/advanced-linux-installation.php):

> When --without-perl is specified, you must first install ImageMagick, download the [PerlMagick](https://imagemagick.org/archive/perl/) source distribution, build, and finally install PerlMagick.

**Comment by hakonhagland** [comment]
> we installed ImageMagick after building with `./configure --with-modules --with-perl`

@urban-warrior Don't you also need `--enable-shared` ? According to the [documentation](https://imagemagick.org/script/advanced-linux-installation.php):

> The modules build option is only available in conjunction with --enable-shared. If --enable-shared is not also specified, support for building modules is disabled.

**Comment by urban-warrior** [comment]
Recommended practice is to install PerlMagick from the source distribution with `--with-modules --with-perl`.  When you enter `make install`, it not only installs ImageMagick but also PerlMagick.  The `--enable-shared` option is not required as a shared library build is the default.  If you don't follow recommended practice, e.g. no `-with-perl` option, you can use the alternative method of downloading the PerlMagick source distribution and install from that repo.   You can also install PerlMagick from CPAN if you prefer.

**Comment by hakonhagland** [comment]
> If you don't follow recommended practice, e.g. no -with-perl option

This question is about using the `--without-perl` option but I think this is not the same as omitting the `with-perl` ? The documentation indicates that omitting `--with-perl` does not imply that perl is not installed. The `--with-perl` is only a way to tell the installer that we want to use a non-standard perl, right?

**Comment by hakonhagland** [comment]
> $ perl Makefile.PL INC="-I/usr/local/include/ImageMagick-7" LIBS="-L/usr/local/lib/"

I think I found the problem. When giving LIBS on the command line like this, it overwrites the default LIBS in the Makefile.PL, so I also need to specify the name of the magick core library like this:

```
$ perl Makefile.PL INC="-I/usr/local/include/ImageMagick-7" LIBS="-L/usr/local/lib/ -lMagickCore-7.Q16HDRI"
```

This modification makes the tests pass on my laptop (outside the docker container), but not inside the docker container though. I think the docker version fails to set the RPATH to the magick core library inside the of the generated perl shared object for Image::Magick. I notice also that the perl version on the docker image is lower than on my laptop so it might be related to that or something else..
