### ISSUE TITLE
Documentation error wrt modulate scaling

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#678]
Both the `image->modulate()` as well as STL `modulateImage()` function will turn the image completely black for all values. Example program below. I'm using IM 6.9.9.7.

```cpp
#include <Magick++.h>

int main(){
  Magick::Image image("logo:");
  image.modulate(1.0, 1.0, 1.0);
  image.write(std::string("test.png"));
}
```

Resulting image:

![test](https://user-images.githubusercontent.com/216319/29316973-40c0b2ee-81ca-11e7-939b-0a75a7b7ac78.png)

**Comment by urban-warrior** [comment]
Modulate accepts percentages.  Try 100.0 instead of 1.0.

**Comment by jeroen** [comment]
Thanks. Please update the documentation for [Image++](https://www.imagemagick.org/Magick++/Image++.html) and [STL](https://www.imagemagick.org/Magick++/STL.html) because both mention:

> Modulation of saturation and brightness is as a ratio of the current value (1.0 for no change). Modulation of hue is an absolute rotation of -180 degrees to +180 degrees from the current position corresponding to an argument range of 0 to 2.0 (1.0 for no change).

**Comment by jeroen** [comment]
So are in fact all 3 values percentages now? Also hue?

**Comment by urban-warrior** [comment]
Yes, all three modulate parameters are percentages.

**Comment by jeroen** [comment]
ok thanks!
