### ISSUE TITLE
Issue while converting specific PNG to TIFF (Expected 4 bytes; found 3 bytes).

### ISSUE THREAD

**Issue by pprasanthk** [ImageMagick/ImageMagick#6790]
### ImageMagick version

7.1.1-20

### Operating system

Windows

### Operating system, version and so on

Windows 10 and later

### Description

Hi, 

We are facing an issue while converting the attached PNG file to TIFF. We are getting the following error while running the command convert.exe test.png test.tiff:

**convert.exe: Expected 4 bytes; found 3 bytes `test.png' @ warning/png.c/MagickPNGWarningHandler/1526.
convert.exe: Read Exception `test.png' @ error/png.c/MagickPNGErrorHandler/1492.
convert.exe: no images defined `test.tiff' @ error/convert.c/ConvertImageCommand/3359.**

We even tried to open this test.png using IMDisplay tool and we are getting the same error. Please find the error attached (**IMDisplay_Error.jpg**). 

Could you please help us with this?

**--
Thanks
Prasanth**

### Steps to Reproduce

Run the below command: 
**convert.exe test.png test.tiff**

### Images

![test](https://github.com/ImageMagick/ImageMagick/assets/79841943/235fd51d-ee7b-49ac-8449-f33967948f7d)
![IMDisplay_Error](https://github.com/ImageMagick/ImageMagick/assets/79841943/ca95b736-0ecf-45c2-b492-e2cb2654ddf2)

**Comment by snibgo** [comment]
`pngcheck` confirms that your file has a problem:
```
C:\web\im>pngcheck parkHayat.png
zlib warning:  different version (expected 1.2.11, using 1.2.13)

parkHayat.png  EOF while reading CRC value
ERROR: parkHayat.png
```
IM is stricter than some programs about file integrity. For example, Gimp can read your file and write a new PNG that IM reads without complaint.
