### ISSUE TITLE
convert -help gives "missing required argument" at the end

### ISSUE THREAD

**Issue by Spanni26** [ImageMagick/ImageMagick#6797]
### ImageMagick version

7.1.1-19

### Operating system

Linux

### Operating system, version and so on

openSUSE Tumbleweed 20231008

### Description

When calling convert 7.1.1-19 with "-help", it gives an error at the end:

with an image format name and a colon (i.e. ps:image) or specify the
image type as the filename suffix (i.e. image.ps). Specify 'file' as
'-' for standard input or output.
convert: missing required argument @ error/convert.c/ConvertImageCommand/562.
It exits with rc 1.

In my opinion it should give back the usage, nothing more. On 7.1.0-9 there is no error message and it exists with 0.

### Steps to Reproduce

ds@morbo convert -help >/dev/null
convert: missing required argument  @ error/convert.c/ConvertImageCommand/562.
ds@morbo echo $?
1

**Comment by fmw42** [comment]
Use magick not convert on IM 7

magick -help
Usage: magick tool [ {option} | {image} ... ] {output_image}
Usage: magick [ {option} | {image} ... ] {output_image}
       magick [ {option} | {image} ... ] -script {filename} [ {script_args} ...]
       magick -help | -version | -usage | -list {option}

**Comment by Spanni26** [comment]
Numerous script here use "convert". If convert is available it should be fixed in my opinion.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
