### ISSUE TITLE
mogrify: no encode delegate for this image format `HEIC'

### ISSUE THREAD

**Issue by J4cker14** [ImageMagick/ImageMagick#6798]
### ImageMagick version

7.1.1-21 (Beta)  Q16-HDRI x64

### Operating system

Windows

### Operating system, version and so on

W11 22H2 x64 i5

### Description

Hi,

I built magick on windows using Visual Studio 2022 own magick.

All done correctly, but heic is still reported only for read, not for write.
Lib is there, all repos downloaded.
Using Visual configuration I generated visual project for final build.

```
C:\_heic_build\ImageMagick-Windows\VisualMagick\bin>magick identify -list format |findstr HEIF
     HEIF  r--   High Efficiency Image Format (1.17.0)
```

failing case:

```
c:\_heic_build>magick mogrify -resize 100x100 aa.heic
mogrify: no encode delegate for this image format `HEIC' @ warning/constitute.c/WriteImage/1399.
mogrify: no encode delegate for this image format `HEIC' @ error/constitute.c/WriteImage/1408.
```

Goal is to resize heic pictures. I tried this via ruby require 'mini_magick' as well as directly as above.

### Steps to Reproduce

I followed manual here:
https://imagemagick.org/script/install-source.php#windows

git clone https://github.com/ImageMagick/ImageMagick-Windows.git
target folder: c:\_heic_build\ImageMagick-Windows\

called CloneRepositories.cmd

build c:\_heic_build\ImageMagick-Windows\VisualMagick\configure\configure.2022.sln  in Release
run configure.exe

next
![image](https://github.com/ImageMagick/ImageMagick/assets/20604067/8b0f4324-85ba-46c2-9cf5-c3558cdaa5c3)
next
next
finish

open and build c:\_heic_build\ImageMagick-Windows\VisualMagick\VisualStaticMT.sln 

add c:\_heic_build\ImageMagick-Windows\VisualMagick\bin\ into PATH

thats it.

All passed, but "w" by HEIC is missing

**Comment by dlemstra** [comment]
It is not missing it is not supported due to licensing issues. You can create `.avif` files but there is no support for writing `.heic` files.

**Comment by J4cker14** [comment]
I understood thats potential license issue and thus it is not supported by default, but should be available for those, who can built it for their own.

**Comment by dlemstra** [comment]
You will need to do that yourself. We are not going to add and maintain that for you.

**Comment by fmw42** [comment]
Dirk,  for my understanding is there a licensing issue?  Is that only for Windows or all OS's?  I thought we had that in the binaries already.

**Comment by dlemstra** [comment]
That is for all OS's. The libx265 encoder (https://www.x265.org/x265-licensing-faq) uses a GPL v2 license and that is not compatible with our Apache 2 license.

**Comment by fmw42** [comment]
Thanks for the clarification

**Comment by VictorLamoine** [comment]
@dlemstra I have old scripts that used to convert HEIC to HEIC (reducing image size) in the past but I don't know which `ImageMagick` version was used (it was compiled from source for sure).

Am I right saying encoding to HEIC was supported at some point in ImageMagick?
Can you point when (version/commit) the support for encoding HEIC was dropped?

Thanks

**Comment by dlemstra** [comment]
There was never support for encoding HEIC images on Windows due to licensing issue. 

And what could we do to improve the error message? It is telling you that encode for HEIC is not supported?

**Comment by VictorLamoine** [comment]
I am using Linux.

```bash
$ magick heic.heic -resize 50% out.heic
magick: no encode delegate for this image format `HEIC' @ warning/constitute.c/WriteImage/1403.
magick: no encode delegate for this image format `HEIC' @ error/constitute.c/WriteImage/1412.
```

The message itself is fine, but it contradicts :

```bash
$ magick -version
Version: ImageMagick 7.1.1-39 Q16-HDRI x86_64 e339a05ed:20241002 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib fontconfig freetype heic jbig jng jpeg lzma pangocairo png tiff webp x xml zip zlib zstd
Compiler: gcc (13.2)
```

Something like `Delegates (built-in): heic (decode only)` would be better. I thought this was a bug but it turns out it's was just not explicit that the `heic` delegate is decode only.

**Comment by dlemstra** [comment]
If you experience this on Linux you are probably getting a version that is compiled by the vendor of that distribution were they removed support for this.

The message doesn't really contradicts that `delegates` list. And in the code that prints `Delegates (built-in)` we cannot print if the delegate is decode or encode only because of how our project is setup. The output of `magick -list format` will give more information about this:
```
HEIC  r--   High Efficiency Image Format (1.18.0)
```

Maybe you can still write `AVIF` files?

**Comment by VictorLamoine** [comment]
I have configured / compiled / installed `ImageMagick-7.1.1-39` from source, with the `--with-heic=yes` switch

```bash
$ magick -list format | grep HEIC
     HEIC  r--   High Efficiency Image Format (1.17.6)
```
This information is correct and not misleading, thanks!

Looks like the `--with-heic=yes` switch is not enough to be able to write HEIC images.
I have switched to `AVIF` in the meantime 👍🏼
