### ISSUE TITLE
Setting the color depth on TIFF files written using the Wand API.

### ISSUE THREAD

**Issue by emxjay** [ImageMagick/ImageMagick#68]
The issue is well explained [here](https://github.com/mkoppanen/imagick/issues/134#issuecomment-165391428).

Can you please clarify this for us?

**Comment by mikayla-grace** [comment]
Modern releases of ImageMagick, by default, writes to an image format @ the same depth as the source image assuming the particular image format supports the depth. XBM, for example, only supports images of depth 1, regardless of the source image depth. This is by design. If you find that ImageMagick behaves differently, post a command-line illustrating the exception.

**Comment by emxjay** [comment]
What do you mean by *modern*? For instance, the issue above is valid on ImageMagick 6.7.7-10.

**Comment by mikayla-grace** [comment]
We did not write IMagick so we cannot help with it.  If you post a command-line that behaves in an unexpected way, we'll investigate further.

**Comment by mikayla-grace** [comment]
ImageMagick picks up the attributes of the first image in a sequence to determine the output image depth.  If the first image in the sequence has a depth of 1, the output TIFF image depth is 1.  Set the first image sequence to a depth of 16, with setImageDepth(16), and your output TIFF image is 16.  The MagickWand API has a method, MagickSetDepth(), that overrides the attributes of the entire image sequence.  We got an error when we called setDepth(16).   All the methods in wand/magick-property.c should be supported in IMagick is they are not already supported.  Apologies if these properties are already supported.  We are unfamiliar with IMagick.

**Comment by Danack** [comment]
I've just seen that this is a duplicate (or at least caused by the same desire) of #66 .

Are you saying that setDepth() will always control the output image depth?

**Comment by emxjay** [comment]
@mikayla-grace `setImageDepth(16)` have no effect, unless `setType()` is specified. And that's the case for every image of the sequence (including the first one). And again, I'm talking about the *Wand API*, not the command-line tools.

**Comment by mikayla-grace** [comment]
Will setDepth() always control the output image depth?  Well that depends on the output format.  XBM, for example, is limited to a pixel depth of 1 so a setDepth(16) would still return an image of depth 1.  ImageMagick typically sets the attributes of the destination image from the source image.  Assume two images, the first of depth 1 and the second of depth 8.  Write this to TIFF and the first image in the TIFF is of depth 1 and the second of depth 8.  Whereas, if you call setDepth(8), both images in the TIFF file will be of depth 8.

setImageDepth() has no effect unless setType() is specified?  We'll need a specific use case that we can download and reproduce the problem before we can comment further.

**Comment by Danack** [comment]
>setImageDepth() has no effect unless setType() is specified? We'll need a specific use case that we can download and reproduce the problem before we can comment further.

An example from the other issue is below. Yes, it is in PHP as I find that a lot easier to write than C. If absolutely necessary I can convert it to C.

```
<?php

$imagick = new Imagick();
$imagick->newPseudoImage(200, 200, 'xc:white');
$imagick->setImageFormat('tiff');
$imagick->setImageDepth(16);
$imagick->writeImage("./output_default.tif");
system('identify ./output_default.tif');


$imagick = new Imagick();
$imagick->newPseudoImage(200, 200, 'xc:white');
$imagick->setType(\Imagick::IMGTYPE_TRUECOLOR);
$imagick->setImageFormat('tiff');
$imagick->setImageDepth(16);
$imagick->writeImage("./output_forceTrueColor.tif");
system("identify ./output_forceTrueColor.tif");

```

**Comment by mikayla-grace** [comment]
We have a patch in ImageMagick to fix this problem.  Its a legacy issue specific to TIFF.  setImageDepth() does not resolve the problem, instead use setImageType(), setDepth(), or install the latest GIT source.

**Comment by emxjay** [comment]
Are you referring to [this patch](https://github.com/ImageMagick/ImageMagick/commit/a38b4564f00511a8a7b260d6f3aa929263c91c32)?

**Comment by emxjay** [comment]
Are you referring to [this patch](https://github.com/ImageMagick/ImageMagick/commit/a38b4564f00511a8a7b260d6f3aa929263c91c32)?

**Comment by mikayla-grace** [comment]
The patch sets the appended images depth to the maximum depth of any one image used to build the result.  A different patch removes the TIFF legacy algorithm of automatically reducing a TIFF image to a depth of 1 if the image was determined to be grayscale / monochrome.

**Comment by emxjay** [comment]
Sweet. Thanks.
