### ISSUE TITLE
convert crashes with this png file

### ISSUE THREAD

**Issue by Giszmo** [ImageMagick/ImageMagick#6801]
### ImageMagick version

7.1.1-20

### Operating system

Linux

### Operating system, version and so on

11

### Description

convert works fine with thousands of files but it fails with this one attached png.

### Steps to Reproduce

```
$ convert b.png c.jpg
convert: Expected 8 bytes; found 0 bytes `/imgs/b.png' @ warning/png.c/MagickPNGWarningHandler/1526.
convert: Read Exception `/imgs/b.png' @ error/png.c/MagickPNGErrorHandler/1492.
convert: no images defined `c.jpg' @ error/convert.c/ConvertImageCommand/3359.
```

As I had the issue with my locally installed IM 6.99, I tried it with a containered version 7.1:

```
$ podman run --rm -v  $PWD:/imgs -it dpokidov/imagemagick b.png c.jpg
convert: Expected 8 bytes; found 0 bytes `b.png' @ warning/png.c/MagickPNGWarningHandler/1526.
convert: Read Exception `b.png' @ error/png.c/MagickPNGErrorHandler/1492.
convert: no images defined `c.jpg' @ error/convert.c/ConvertImageCommand/3359.
```

### Images

![b](https://github.com/ImageMagick/ImageMagick/assets/96378/1c6b7af5-d08d-45be-8074-1c65d23c4719)

**Comment by fmw42** [comment]
Your PNG file is created to PNG standards.  Imagemagick is very strict on holding to standards.  Other tools are less so and thus may be able to read your file.

**Comment by Giszmo** [comment]
I'm not sure what to make of your reply. The first sentence might be missing a "not"?

Are you suggesting that this is a bug in IM or that the png is broken to begin with, so crashing on it is fair? If the latter, how did you find it to be broken?

**Comment by fmw42** [comment]
Your PNG is not formed according to the PNG standards.  Imagemagick is very strict about that. So that is why IM will not read it and gives you an error message about what is wrong.

**Comment by snibgo** [comment]
The PNG file is bad.

```
C:\web\im>pngcheck odds.png
zlib warning:  different version (expected 1.2.11, using 1.2.13)

odds.png  file doesn't end with an IEND chunk
ERROR: odds.png
```

**Comment by Giszmo** [comment]
I would be curious to know why IM is so strict or if there is a lenient mode but the two who replied sound like this will end in a "won't fix" so I'm closing it myself.

**Comment by fmw42** [comment]
They just decided to follow the specs and warn or make error if the file is not according to specs.  There is no "lenient" mode in IM 7.  You can use IM 6, which is less strict, but may still flag this file as bad.

**Comment by snibgo** [comment]
One issue is security. A hostile actor might craft a non-compliant image that takes advantage of lenient image readers, to make them follow code paths that were unplanned by the code authors, which can compromise system integrity.

Another issue is workflow integrity. If some software makes a bad PNG file, a lenient reader needs to make assumptions about what was intended. Those assumptions may be wrong, so the reader will then present a valid but incorrect PNG file to the next software in the workflow. When the final incorrect result is discovered, debugging the workflow (identifying the first software that did something wrong) is difficult.

IM is often used in batch workflows that have high volumes of user-uploaded images, so it needs to address both issues. Interactive software such as Gimp is not often used in such workflows.

Aside: the title of this thread is misleading. For this file, convert does not crash. It reports the error and terminates in a controlled manner. A "crash" is an uncontrolled termination.
