### ISSUE TITLE
Gravity gets stored - is this a bug or a feature?

### ISSUE THREAD

**Issue by stiebel** [ImageMagick/ImageMagick#6808]
### ImageMagick version

6.9.11-60

### Operating system

Linux

### Operating system, version and so on

Ubuntu 24.04

### Description

If a add a border to an image with `concert image1.mpc -gravity east -splice  100x0 image2.mpc`
and than crop with `convert image2.mpc -crop 20x0+0+0 cropimage.mpc`
I do not get the first 50 pixels image but the last 20 pixels image.
Doing a convert cropimage.mpc -gravity west cropimage.mpc restores to normal behavior.

Is this intended? 

I use imagemagick in an productive content and have to use long term support ubuntu. 
at this very moment 6.9.11-60 is the current ubuntu-lts-imagemagick.

If this issue is intended  I have to stick to the workaround.
If not, please consider fixing this for future versions. Thanks a lot! 

### Steps to Reproduce

imagick$ `convert rose: rose.mpc`
imagick$ `convert rose.mpc -gravity east -splice  100x0 splicerose.mpc`
imagick$ `convert splicerose.mpc -crop 20x0+0+0 croprose1.mpc`
imagick$ `convert splicerose.mpc -gravity west westrose.mpc`
imagick$ `convert westrose.mpc -crop 20x0+0+0 croprose2.mpc`
imagick$ `identify croprose1.mpc` 
croprose1.mpc MPC 20x46 170x46+150+0 8-bit sRGB 409B 0.000u 0:00.000
magick$ `identify croprose2.mpc `
croprose2.mpc MPC 20x46 170x46+0+0 8-bit sRGB 407B 0.000u 0:00.000

see the difference after the first "+"
150 != 0

### Images

not needed

**Comment by snibgo** [comment]
> Is this intended?

Yes. The .mpc and .miff formats record IM metadata, including gravity.

The .mpc file is text. You can see what metadata it contains by using a text editor, or `cat` (unix) or `type` (Windows).

You can use `+gravity` before writing the .mpc file to remove that metadata.

**Comment by urban-warrior** [comment]
Its by design.  Both MIFF and MPC are specific to ImageMagick and were designed to capture as much metadata as possible so that all state is saved across separate invocations of ImageMagick.
