### ISSUE TITLE
Magick++: Segmentation fault on getConstMetacontent when reading a paletted image

### ISSUE THREAD

**Issue by HorstBaerbel** [ImageMagick/ImageMagick#6811]
### ImageMagick version

7.1.1.15-1.fc38

### Operating system

Linux

### Operating system, version and so on

Fedora 38

### Description

Segmentation when reading pixels from a paletted image:
```c++
// --> img is PseudoClass and PaletteType
        const auto nrOfColors = img.colorMapSize(); <-- 256
        const auto nrOfIndices = img.columns() * img.rows(); <-- correct # of pixels
        auto pixels = img.getConstPixels(0, 0, img.columns(), img.rows()); // returns valid pointer. needed for getConstMetaContent to work...
        auto indices = static_cast<const uint8_t *>(img.getConstMetacontent()); <-- crash
```

Doing anything wrong?

### Steps to Reproduce

see above

### Images

![new_height](https://github.com/ImageMagick/ImageMagick/assets/1310747/bafd5fe3-70fd-4179-81fc-11a662f8364b)

**Comment by dlemstra** [comment]
You probably don't need that method but we should make sure that we return `null` instead and then an exception will be thrown. I will add a patch for this tomorrow.

**Comment by dlemstra** [comment]
Thanks for reporting this and the patch has just been applied.

**Comment by HorstBaerbel** [comment]
Hi @dlemstra . I started a discussion [here](https://github.com/ImageMagick/ImageMagick/discussions/6822), but nobody is responding. An answer or link to an up-to-date example would be much appreciated. In comparison to ImageMagick command line and scripting info the Magick++ is a bit lacking imo...
