### ISSUE TITLE
ImageMagick-libs requires downgrading LibRaw when installing

### ISSUE THREAD

**Issue by Kha1r0** [ImageMagick/ImageMagick#6817]
### ImageMagick version

current (26.10.23)

### Operating system

Linux

### Operating system, version and so on

Centos Stream 9

### Description

![image](https://github.com/ImageMagick/ImageMagick/assets/115714947/c6b71bfe-7705-48e7-b27b-feef3f4313c3)

When running the usual sudo dnf update, i get this error.
All dnf flags (--allowerasing, --skip-broken, --best, --nobest) can't resolve this, --nobest can atleast skip it.
So i uninstalled ImageMagick, only installed LibRaw, and when i tried to install ImageMagick again, i'm prompted to downgrade LibRaw again.
Pretty sure this is not supposed to be that way, sorry if i made some sort of dumb mistake, please let me know.

### Steps to Reproduce

See above

### Images

![image](https://github.com/ImageMagick/ImageMagick/assets/115714947/886835a8-654c-42cf-ae02-1cbdb3dc0c72)

**Comment by urban-warrior** [comment]
We are not responsible for the creation or upkeep of CentOS ImageMagick RPM packages. To seek assistance,  get in touch with their dedicated team.

**Comment by Kha1r0** [comment]
Thanks for letting me know, I'll reach out to them. Sorry for posting it here.

**Comment by Kha1r0** [comment]
Can you pinpoint me on where to post this issue?
