### ISSUE TITLE
on i686 not work convert utility

### ISSUE THREAD

**Issue by Pro-pra** [ImageMagick/ImageMagick#6820]
### ImageMagick version

7.1.1.21

### Operating system

Linux

### Operating system, version and so on

Rosa linux

### Description

convert /builddir/build/SOURCES/hp-sendfax.png -scale 16x16 16.png
convert: time limit exceeded `/builddir/build/SOURCES/hp-sendfax.png' @ fatal/cache.c/GetImagePixelCache/1702.

### Steps to Reproduce

convert foo.png -scale 16x16 16.png

**Comment by urban-warrior** [comment]
We added a patch that may resolve the problem.  We don't have access to an I686 to verify.  In the mean-time, try

```
convert -limit time 2000 foo.png -scale 16x16 16.png
```

**Comment by Pro-pra** [comment]
thank you with last patch 'unlimited is INT_MAX' and 'new default time to live' work fine
