### ISSUE TITLE
Support for ODG (OpenDocument Format Graphics)

### ISSUE THREAD

**Issue by manfromarce** [ImageMagick/ImageMagick#6827]
### Describe the solution you'd like

I understand ImageMagick is primarly a raster image processing library, but it support vector formats such as SVG and WPG too. Having support for ODG files - part of OpenDocument Format and created by LibreOffice Draw - would be a nice addition.

**Comment by dlemstra** [comment]
Is there a library that can be used to change ODG files into a raster image?

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Comment by manfromarce** [comment]
> Is there a library that can be used to change ODG files into a raster image?

I'm not aware of any, except of using LibreOffice from command line to convert them.
