### ISSUE TITLE
identify gives incorrect/inconsistent color depth for some ICO files

### ISSUE THREAD

**Issue by colinmorris** [ImageMagick/ImageMagick#683]
I can't find "depth" (as reported by `identify -format "%[depth]"`, for example) defined anywhere, but for JPEG/BMP/GIF/PNG files, it seems to consistently correspond to the number of bits per color channel.

For some ICO files, `identify` reports a suspiciously high color depth.

```
wget au.org/favicon.ico
mv favicon.ico au.ico
wget 0101shop.com/favicon.ico
mv favicon.ico shop.ico
identify -format "%f %[depth]\n" *.ico
au.ico 8
au.ico 8
shop.ico 32
shop.ico 32
```

`identify -verbose` reports the following for both files:

```
Channel depth:
    red: 8-bit
    green: 8-bit
    blue: 8-bit
    alpha: 1-bit
```

The histogram section for `shop.ico` uses rgba tuples and hex codes that suggest that each channel actually has 2^32 possible values:

```
Histogram:
       502: (         0,         0,         0,         0) #00000000000000000000000000000000 none
         1: (1549556828,1549556828,1532713819,4294967295) #5C5C5C5C5C5C5C5C5B5B5B5B srgba(92,92,91,1)
         1: (1667457891,1667457891,1650614882,4294967295) #636363636363636362626262 srgba(99,99,98,1)
         1: (2038004089,2021161080,2004318071,4294967295) #797979797878787877777777 srgba(121,120,119,1)
...
```

But all the colors are ones that could be encoded with 8-bit color. 

This does not seem to be a rare issue. Out of hundreds of thousands of favicon ICO files I've looked at, this bug affects the majority of them.

```
identify -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2017-07-31 http://www.imagemagick.org
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
