### ISSUE TITLE
ImageMagick-7.0.6-7/MagickCore/xml-tree.c:2735]: (style) Array index 'offset' is used before limits check.

### ISSUE THREAD

**Issue by dcb314** [ImageMagick/ImageMagick#684]
Source code is

  while ((content[offset] != '\0') && (offset < xml_info->offset))
    offset++;

Maybe better code

  while ((offset < xml_info->offset) && (content[offset] != '\0'))
    offset++;

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
