### ISSUE TITLE
7.1.1-21 Latest Appimage fails to open and on website it's missing it's file extension

### ISSUE THREAD

**Issue by dener3id** [ImageMagick/ImageMagick#6842]
### ImageMagick version

7.1.1-21 Latest

### Operating system

Linux

### Operating system, version and so on

Mint 21.2

### Description

Run Appimage doesn't work (I have other Appimage's that do work so I know my system can run them just fine).

### Steps to Reproduce

Run Appimage doesn't work or open.

**Comment by urban-warrior** [comment]
The Appimage is https://imagemagick.org/archive/binaries/magick.  We downloaded it on Fedora, performed a `chmod 755 magick` and executed with `./magick rose: rose.png` and it ran without complaint.
