### ISSUE TITLE
Invalid argument for option  @ error/magick-cli.c/MagickImageCommand/991.

### ISSUE THREAD

**Issue by LiamTheBox** [ImageMagick/ImageMagick#6847]
### ImageMagick version

7.1.1-21

### Operating system

Linux

### Operating system, version and so on

Linux Mint 21.2

### Description

The App Image will not run
Using the terminal to run it gives me this result
```
liambox@liambox-Nitro-AN515-43:~/Downloads$ ./magick
Usage: magick tool [ {option} | {image} ... ] {output_image}
Usage: magick [ {option} | {image} ... ] {output_image}
       magick [ {option} | {image} ... ] -script {filename} [ {script_args} ...]
       magick -help | -version | -usage | -list {option}

magick: invalid argument for option  @ error/magick-cli.c/MagickImageCommand/991.
liambox@liambox-Nitro-AN515-43:~/Downloads$
```

### Steps to Reproduce

using the command `./magick`

Error
`
magick: invalid argument for option  @ error/magick-cli.c/MagickImageCommand/991.
`

### Images

![image](https://github.com/ImageMagick/ImageMagick/assets/69638063/5a5299c0-747f-4489-b54b-b20b29d5857f)

**Comment by snibgo** [comment]
> The App Image will not run

The `magick` program is running. When you run that program with no arguments, it gives the error message you show, and exits.
