### ISSUE TITLE
include swp file

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#6849]
### ImageMagick version

lastest

### Operating system

Linux

### Operating system, version and so on

debian

### Description

Could you please remove this file

https://github.com/ImageMagick/ImageMagick/blob/main/www/assets/.magick-template.css.swp

### Steps to Reproduce

None

**Comment by dlemstra** [comment]
We have removed the file but feel free to open a PR to remove this next time.
