### ISSUE TITLE
Cannot convert specific DNGs to JPG

### ISSUE THREAD

**Issue by paurodriguez0220** [ImageMagick/ImageMagick#6854]
### ImageMagick version

7.1.1-21

### Operating system

Windows

### Operating system, version and so on

Windows 11 and Windows 10

### Description

Using portable ImageMagick I'm getting error in converting some specific DNG
For the installed version its working fine

_magick: Unsupported file format or not RAW file `test.dng' @ error/dng.c/ReadDNGImage/547._

Version: ImageMagick 7.1.1-21 Q16 x64 58d86e4:20231021 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Channel-masks(64-bit) Cipher DPC OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (193532217)

### Steps to Reproduce

For Windows
`magick failsample.dng -resize 800x800 failsample.jpg`

### Images

[failsample.zip](https://github.com/ImageMagick/ImageMagick/files/13282451/failsample.zip)

**Comment by snibgo** [comment]
`dcraw` and `dcraw_emu` can both read that DNG raw file without problem.

I don't know why IM has a problem. A developer may comment.

**Comment by paurodriguez0220** [comment]
> `dcraw` and `dcraw_emu` can both read that DNG raw file without problem.
> 
> I don't know why IM has a problem. A developer may comment.

But have you tried opening it to a portable IM and can replicate the issue?

**Comment by dlemstra** [comment]
Thanks for reporting this. This seems to be an issue in the configuration of the static libraw build. This will be resolved in the next release.
