### ISSUE TITLE
--with-security-option does not work on configure

### ISSUE THREAD

**Issue by vaidyasaurabh08** [ImageMagick/ImageMagick#6863]
### ImageMagick version

7.1.1-21

### Operating system

Linux

### Operating system, version and so on

Redhat 7.9

### Description

Imagemagick picks up security policy OPEN irrespective of --with-security-policy ARG passed to the configure script

### Steps to Reproduce

- Download Image magick 7.1.1-21 tar file
- Extract contents
- Run configure with --with-security-policy=secure

On doing this configure output shows security policy default to OPEN

```
 ImageMagick-7.1.1-21 -> ./configure --with-security-policy=secure > conf_op

ImageMagick-7.1.1-21 -> grep -B 20 'security-policy'  conf_op
config.status: executing magick.sh.in commands
config.status: executing MagickCore-config.in commands
config.status: executing MagickWand-config.in commands
config.status: executing Magick++-config.in commands
config.status: executing PerlMagick/check.sh.in commands
configure:
==============================================================================
ImageMagick 7.1.1-21 is configured as follows. Verify that this configuration
matches your expectations.

Host system type: x86_64-pc-linux-gnu
Build system type: x86_64-pc-linux-gnu

                    Option				Value
------------------------------------------------------------------------------
Shared libraries    --enable-shared=yes			yes
Static libraries    --enable-static=yes			yes
Build utilities     --with-utilities=yes		yes
Module support      --with-modules=no			no
GNU ld              --with-gnu-ld=yes			yes
Security policy     --with-security-policy=open		open
```

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
