### ISSUE TITLE
Latest build is stopped by Windows 10 SmartScreen but all previous releases have been fine

### ISSUE THREAD

**Issue by jmfgdev** [ImageMagick/ImageMagick#687]
On more than one computer, the latest build of imagemagick from https://www.imagemagick.org/script/download.php#windows

is throwing windows 10 smartscreen warnings, all previous builds have been installed without warning,
any particular reason this might be occuring?

**Comment by mikayla-grace** [comment]
Windows releases are built in a clean safe environment @ AppVeyor.  Its likely a false positive.  We will have an updated Windows binary release by sometime tomorrow.

**Comment by akupaka** [comment]
I have just downloaded ImageMagick-7.0.9-21-Q16-x64-dll.exe using HTTP and FTP and the issue is present.
The same with ImageMagick-7.0.9-21-Q16-x64-static.exe
