### ISSUE TITLE
The magick command and the -map option suspend processing and do not complete.

### ISSUE THREAD

**Issue by yoya** [ImageMagick/ImageMagick#6872]
### ImageMagick version

7.1.1-21

### Operating system

MacOS

### Operating system, version and so on

Sonoma 14.1.1（23B81）

### Description

The magick command and the -map option suspend processing and do not complete.
CPU load is not increased and may be waiting for image input.

Incidentally, 7.0.1-0 has the same problem.

### Steps to Reproduce

A simple reproduction command is as follows

```
% magick netscape: -map netscape: out.png
(Will not return to prompt.)
```

It is reproduced  in the file image input.

```
% magick netscape: netscape.png
% magick netscape.png -map netscape.png out.png
(Will not return to prompt.)
```

**Comment by yoya** [comment]
In "case map" of CLISimpleOperatorImage, it is reinterpreted as "remap", (is this a mistake?)

https://github.com/ImageMagick/ImageMagick/blob/7.1.1-21/MagickWand/operation.c#L4538

In "case remap", I have confirmed that the GetImageCache does not return.

https://github.com/ImageMagick/ImageMagick/blob/7.1.1-21/MagickWand/operation.c#L3230

**Comment by snibgo** [comment]
On `-map`, see https://imagemagick.org/script/command-line-options.php#map

`-map netscape:` is not valid. IM does not correctly check for this, which is a bug. For example, the following hangs:
```
magick xc: -map garbage: info:
```

**Comment by urban-warrior** [comment]
We'll export a patch soon to resolve this issue.  In the mean-time, try `magick convert`.

**Comment by fmw42** [comment]
According to the porting document at https://imagemagick.org/script/porting.php#cli, -map is deprecated 

> -/+map
> Replaced by -/+remap.

**Comment by yoya** [comment]
thank you for your information!
