### ISSUE TITLE
Remove FFmpeg or be sure you distribute the latest version

### ISSUE THREAD

**Issue by Scal-Human** [ImageMagick/ImageMagick#6875]
### Is your feature request related to a problem? Please describe.

Hi all,
Because ImageMagick includes an ancient version of FFmpeg and because it updates the Path, this is the old version that is executed when starting ffmpeg (version 4 something while I have 6.1 like everybody else).
This is an annoyance that forces to take actions on every upgrade to ImageMagick ... or to write scipts to solve the issue.

`Version Path
------- ----
4.2     C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\ffmpeg.exe
6.1     C:\ProgramData\chocolatey\lib\ffmpeg\tools\ffmpeg\bin\ffmpeg.exe
6.1     C:\ProgramData\chocolatey\bin\ffmpeg.exe
`
The third is Chocolatey's shim to the second, and it is preceeded by ancient one that should not be found in the Path.

### Describe the solution you'd like

You have multiple options but having both a copy of thrid party tools and place them in the path is not viable.
The solution I would like is not to find FFmpeg inside ImageMagick when using the Path to find it.

### Describe alternatives you've considered

There are multiple options:
1) completely remove FFmpeg
I mention this in case it is not really needed or in some edge cases where you may request it to be installed
2) place everything that is not actually ImageMagick is a subdirectory of it
This allows to have access to ImageMagick tools using the Path but do not pollute third party installation.
3) verify or ask where FFmpeg is installed
Instead of distributing ancient versions of tools because these version are enough for you, verify or ask where they are installed
4) require the user to install it (to use feature x or y)
Possibly require to have an environment variable telling where to find FFmpeg.
5) always distribute the last version of the tools
This means you both publish updates when you update your project and when tools are updated.

### Additional context

This means that if I executed FFmpeg with parameters that are compatible between version 4 and 6, I am actually running a ancient version with possible different reaction or different quality of result than expected with the otherwise up-to-date FFmpeg installation.

**Comment by dlemstra** [comment]
The ffmpeg executable will be removed from the installer and will require a manual installation in the future.

**Comment by Scal-Human** [comment]
Many thanks, have a nice day.
