### ISSUE TITLE
FloodfillPaintImage with pseudo image class fails

### ISSUE THREAD

**Issue by MootoolsSoftware** [ImageMagick/ImageMagick#6879]
### ImageMagick version

7.1.1.21

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

I am using FloodFillPaint, filling a DirectClass RGBColorspace 256x256 destination image with a 128x128 pseudo class pattern.
The destination image is black, and the filling operation should result in tilling the pattern over the destination image.

But the result **is an a black image with a white alpha channel**.

It seems that the filling operation which occurs line 355/356 in FloodfillPaintImage (.\MagickCore\paint.c) does not correctly handle the pseudo class case.

On the capture, bottom left, there's the fill_color get by GetFillColor, and right is the q pixel content fill by fill_color.
As show the red/green/blue pixel value are fill with invalid values.

![FillFloodDebug](https://github.com/ImageMagick/ImageMagick/assets/15813085/87cb20ed-c251-4561-bb40-98d71481bf96)

May be there's a command that allows to reproduce the problem using a magick, but I didn't find it.

### Steps to Reproduce

This is the file used to fill the destination image

![defaultbk](https://github.com/ImageMagick/ImageMagick/assets/15813085/143cb470-02c7-48ea-842c-13b72dc99456)

**Comment by urban-warrior** [comment]
We need to reproduce the issue.  Post your command-line here and a link to your source images.  Once we can reproduce the issue, we will look for a patch to resolve it.

**Comment by MootoolsSoftware** [comment]
Thanks.

> Post your command-line here and a link to your source images

The issue is related to using imagemagick directly through the C interface, not using through the command line.
Is it the right place to post such problems?

**Comment by dlemstra** [comment]
You can post that here but we need something to reproduce your issue.

**Comment by MootoolsSoftware** [comment]
Thanks for your help.

Digging the problem, I found that I incorrectly initialized the pseudoclass pattern bitmap.
I miss that not only 'SetPixelIndex' must be called but also 'SetPixelViaPixelInfo' to properly initialize the image pixels.
Doing that it appears that the FloodFillPaint works correctly and the issue might be closes.
