### ISSUE TITLE
Getting error while processing tif files

### ISSUE THREAD

**Issue by SUBHAROOP** [ImageMagick/ImageMagick#6884]
### ImageMagick version

7.0.6.5

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

Hi Team while processing some tif files I was getting error in log it is mentioned Use Imagemagick to fix bad Tif headers

### Steps to Reproduce

There are some particular tif files for that it is not working. Please let us know how to fix.
[167543083 (2).zip](https://github.com/ImageMagick/ImageMagick/files/13452990/167543083.2.zip)

**Comment by fmw42** [comment]
Your tif file is malformed.  Even Photoshop will not open it.

**Comment by SUBHAROOP** [comment]
![image](https://github.com/ImageMagick/ImageMagick/assets/26341034/185fd967-fdbc-47d4-bf0b-15a332f6151e)
I am able to open it please check

**Comment by fmw42** [comment]
It is malformed.  Probably something in the header.  Imagemagick is very strict in following the specifications for TIF. Other tools may be able to open it if they are less strict about following the specifications.

A developer may look at it to confirm.

**Comment by SUBHAROOP** [comment]
[TIFsThatDontWork.zip](https://github.com/ImageMagick/ImageMagick/files/13461125/TIFsThatDontWork.zip)
This are tiff files not working can you please check those files

**Comment by fmw42** [comment]
Both of your files open fine.  They give warnings not errors.  Warnings are common in TIF files when using non-standard TIF tags.

You can suppress the warnings by adding -quiet right after magick and before the input file read. For example

`magick -quiet 167543083.tif 167543083.png`

**Comment by fmw42** [comment]
No reply since Nov 2023, so I assume the -quiet helped the OP. I am closing this.
