### ISSUE TITLE
Strange horizontal lines

### ISSUE THREAD

**Issue by techiedesu** [ImageMagick/ImageMagick#6905]
### ImageMagick version

ImageMagick 7.1.1-13 Q16-HDRI x64 d5974ce:20230716 https://imagemagick.org Copyright: (C) 1999 ImageMagick Studio LLC License: https://imagemagick.org/script/license.php Features: Cipher DPC HDRI Modules OpenCL OpenMP(2.0) Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib Compiler: Visual Studio 2022 (193532217)

### Operating system

Windows

### Operating system, version and so on

Windows 11 23H2, 22631.2615

### Description

Getting strange horizontal lines when running magick. Sample issue on Linux `Version: ImageMagick 7.1.1-11 Q16 x86_64 21206 https://imagemagick.org`.

### Steps to Reproduce

1. Download attached zip archive
2. Run `magick.exe .\8ef3f8b5792e460787d481eb61f4fbe8.mp4 .\out-rep.mp4`

File should be broken like `8ef3f8b5792e460787d481eb61f4fbe8-out.mp4`

Also, sample with liquid-rescale gives black dots
`magick.exe .\8ef3f8b5792e460787d481eb61f4fbe8.mp4 -scale 512x512 -liquid-rescale 50% -scale 200% .\out-rep-d.mp4`

### Images

[hl-samples.zip](https://github.com/ImageMagick/ImageMagick/files/13518971/hl-samples.zip)

**Comment by fmw42** [comment]
Perhaps try

`magick.exe .\8ef3f8b5792e460787d481eb61f4fbe8.mp4 -coalese -scale 512x512 -liquid-rescale 50% -scale 200% .\out-rep-d.mp4`

why are your doing -liquid-rescale?

**Comment by techiedesu** [comment]
@fmw42 Thank you!

`coalesce` argument helped. 

> why are your doing -liquid-rescale?

Just experimenting with different videos. Forgot to change.
