### ISSUE TITLE
Magick++: Example needed for reading a paletted image

### ISSUE THREAD

**Issue by HorstBaerbel** [ImageMagick/ImageMagick#6930]
### ImageMagick version

7.1.1.22 built from source (8fccfab)

### Operating system

Linux

### Operating system, version and so on

Fedora 38

### Description

This is related to #6811 .

I am still trying to read the pixel data / indices a paletted image:
![new_height](https://github.com/ImageMagick/ImageMagick/assets/1310747/c33f4a16-421b-452c-a71a-38ba44f146f7)

But get the Magick::ErrorOption Exception "Magick: Unable to retrieve meta content." on calling getConstMetacontent().

In ImageMagick 6 / Magick++ the function to get indexed pixel data was called getConstIndexes(), but it does not exist anymore. From the docs [here](https://www.imagemagick.org/Magick++/Image++.html) I'm grasping that my minimal example below should read the pixels / indices fine.

### Steps to Reproduce

Minimal example:

**imtest.cpp:**

```c++
#include <iostream>

#include <Magick++.h>

int main(int argc, const char *argv[])
{
    std::cout << "Reading " << argv[1];
    Magick::Image img;
    try
    {
        img.read(argv[1]);
    }
    catch (const Magick::Exception &ex)
    {
        throw std::runtime_error("Failed to read image");
    }
    auto imgSize = img.size();
    std::cout << " -> " << imgSize.width() << "x" << imgSize.height() << ", ";
    if (img.classType() == Magick::ClassType::PseudoClass && img.type() == Magick::ImageType::PaletteType)
    {
        std::vector<uint8_t> data;
        std::cout << "paletted, " << img.colorMapSize() << " colors" << std::endl;
        // get palette indices as unsigned chars
        const auto nrOfColors = img.colorMapSize();
        // auto pixels = img.getConstPixels(0, 0, img.columns(), img.rows()); // needed to call this first for getConstMetacontent to work?
        auto indices = static_cast<const uint8_t *>(img.getConstMetacontent()); // <--- Exception
        const auto nrOfIndices = img.columns() * img.rows();
        for (std::remove_const<decltype(nrOfIndices)>::type i = 0; i < nrOfIndices; i++)
        {
            data.push_back(indices[i]);
        }
        std::cout << "Read " << data.size() << " pixels" << std::endl;
    }
    else
    {
        throw std::runtime_error("Unsupported image format");
    }
}
```

**CMakeLists.txt**

```cmake
cmake_minimum_required(VERSION 3.16)

find_package(PkgConfig REQUIRED)

pkg_check_modules(LIBMAGICK REQUIRED IMPORTED_TARGET
    Magick++
)

add_definitions(-DMAGICKCORE_HDRI_ENABLE=0)
add_definitions(-DMAGICKCORE_QUANTUM_DEPTH=16)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_C_STANDARD 11)

add_executable(imtest imtest.cpp)
target_include_directories(imtest PRIVATE ${ImageMagick_INCLUDE_DIRS})
target_link_libraries(imtest PkgConfig::LIBMAGICK)
```

Adjust to whereever Magick++ is located for you.

**Comment by urban-warrior** [comment]
Magick++ is behaving correctly.  getConstMetacontent() returns meta content associated with each pixel.  Your image does set any meta data channels thus the exception.  Instead, what you are looking for is the IndexChannel, which is just another inline channel in IMv7, e.g., RGBI or GI for grayscale images.   This can be somewhat confusing for IMv6 users as colormap indexes are not embedded with the expected RGBA channels, but instead are stored in a separate area just for indexes or the black channel for CMYK images.  See https://imagemagick.org/script/porting.php for some discussion on how IMv7 differs from IMv6.

**Comment by HorstBaerbel** [comment]
> Magick++ is behaving correctly. getConstMetacontent() returns meta content associated with each pixel. Your image does set any meta data channels thus the exception. Instead, what you are looking for is the IndexChannel, which is just another inline channel in IMv7, e.g., RGBI or GI for grayscale images. This can be somewhat confusing for IMv6 users as colormap indexes are not embedded with the expected RGBA channels, but instead are stored in a separate area just for indexes or the black channel for CMYK images. See https://imagemagick.org/script/porting.php for some discussion on how IMv7 differs from IMv6.

Thank you for the info. I've read the porting guide, but it is for using ImageMagick directly. I'm using Magick++ and there is no porting guide for that afaik. So I've stuck to the [docs](https://www.imagemagick.org/Magick++/Image++.html#Raw%20Image%20Pixel%20Access) and they seem to be wrong indeed and should be fixed. I'll try to work out a minimal example using IndexChannel and update the issue.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We updated the docs to reflect meta-content rather than colormap indexes. Your patience and feedback are greatly appreciated.

**Comment by HorstBaerbel** [comment]
> Magick++ is behaving correctly. getConstMetacontent() returns meta content associated with each pixel. Your image does set any meta data channels thus the exception. Instead, what you are looking for is the IndexChannel, which is just another inline channel in IMv7, e.g., RGBI or GI for grayscale images. This can be somewhat confusing for IMv6 users as colormap indexes are not embedded with the expected RGBA channels, but instead are stored in a separate area just for indexes or the black channel for CMYK images. See https://imagemagick.org/script/porting.php for some discussion on how IMv7 differs from IMv6.

I've read through the porting guide and looked at the C functions, but there's a couple of issues:

What I have now:

```c++
auto depth = img.channelDepth(MagickCore::IndexChannel); //<--- is 1 ???
img.channel(MagickCore::IndexChannel); // <--- seems to "select" channel. needs to copy internally?, which is unfortunate
auto pixels = img.getConstPixels(0, 0, img.columns(), img.rows());
MagickCore::GetPixelIndex(???); // <--- uses const * MagickCode::Image. I have an object or a reference of Magick::Image. There seems to be no Magick++ equivalent for this function
const auto nrOfIndices = img.columns() * img.rows();
for (std::remove_const<decltype(nrOfIndices)>::type i = 0; i < nrOfIndices; i++)
{
    data.push_back(pixels[i]); // <--- wth do I do here?
}
```

The pixels pointer for my 4x4 test image:
![test1](https://github.com/ImageMagick/ImageMagick/assets/1310747/f94719cc-c42b-4525-95a7-0f362ff0d966)

looks like this:
![Bildschirmfoto vom 2023-12-09 18-26-04](https://github.com/ImageMagick/ImageMagick/assets/1310747/61e51c5a-c77a-4f1e-9d6a-15b7ec9bbb89)

Which makes me one the wiser. It would be much appreciated if you could help an point me to the functions I need to use.

**Comment by HorstBaerbel** [comment]
So. I've tried it the the C(ish)-way:

```c++
#include <iostream>
#include <Magick++.h>

int main(int argc, const char *argv[])
{
    std::cout << "Reading " << argv[1];
    Magick::Image img;
    try
    {
        img.read(argv[1]);
    }
    catch (const Magick::Exception &ex)
    {
        throw std::runtime_error("Failed to read image");
    }
    auto imgSize = img.size();
    std::cout << " -> " << imgSize.width() << "x" << imgSize.height() << ", ";
    if (img.classType() == Magick::ClassType::PseudoClass && img.type() == Magick::ImageType::PaletteType)
    {
        std::cout << "paletted, " << img.colorMapSize() << " colors" << std::endl;
        auto coreImg = img.constImage();
        for (std::size_t y = 0; y < coreImg->rows; y++)
        {
            auto pixels = GetVirtualPixels(coreImg, 0, y, coreImg->columns, 1, nullptr);
            for (std::size_t x = 0; x < coreImg->columns; x++)
            {
                auto value = GetPixelIndex(coreImg, pixels);
                std::cout << value << ", ";
                pixels += GetPixelChannels(coreImg);
            }
        }
    }
    else
    {
        throw std::runtime_error("Unsupported image format");
    }
}
```

returns: `18303, 16544, 0, 16384, 0, 0, 18303, 16512, 0, 0, 0, 0, 0, 0, 0, 0,` which makes no sense to me looking at my example image, not even when fiddling around with QuantumRange...

**Comment by HorstBaerbel** [comment]
Ok, Nevermind. I've solved the mystery. I have compiled ImageMagick from source, master commit 8fccfabce (or origin/HEAD actually). This gives me the error. When using the installed ImageMagick version 7.1.1.15-1.fc38 I DON'T have the problem with the same code and get the correct index values: 

> 5, 2, 0, 3, 0, 4, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0

Why that is I have no clue, it could be I just built ImageMagick wrong...

The correct code to read the index channel using Magick++ seems to be:

```c++
#include <iostream>
#include <Magick++.h>

int main(int argc, const char *argv[])
{
    std::cout << "Reading " << argv[1];
    Magick::Image img;
    try
    {
        img.read(argv[4]);
    }
    catch (const Magick::Exception &ex)
    {
        throw std::runtime_error("Failed to read image");
    }
    auto imgSize = img.size();
    std::cout << " -> " << imgSize.width() << "x" << imgSize.height() << ", ";
    if (img.classType() == Magick::ClassType::PseudoClass && img.type() == Magick::ImageType::PaletteType)
    {
        std::vector<MagickCore::Quantum> data;
        std::cout << "paletted, " << img.colorMapSize() << " colors" << std::endl;
        img.channel(MagickCore::IndexChannel);
        auto pixels = img.getConstPixels(0, 0, img.columns(), img.rows());
        for (std::size_t i = 0; i < img.columns() * img.rows(); i++)
        {
            auto value = *pixels++;
            std::cout << value << ", ";
            data.push_back(value);
        }
        std::cout << "Read " << data.size() << " pixels" << std::endl;
    }
    else
    {
        throw std::runtime_error("Unsupported image format");
    }
}

```
