### ISSUE TITLE
Possible bug flood fill in iM 7

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#6933]
### ImageMagick version

7.1.1.22

### Operating system

MacOS

### Operating system, version and so on

Venture

### Description

Flood fill works with IM 6.9.13.0 but not IM 7.1.1.22

### Steps to Reproduce

Input:

![f1-7](https://github.com/ImageMagick/ImageMagick/assets/13458218/e06bf5ea-6b6e-4428-849f-af717c2e4ad0)

IM 6:
`convert f1-7.png -fuzz 5% -fill none -draw "matte 275,314 floodfill" -alpha off x-6.png`

![x-6](https://github.com/ImageMagick/ImageMagick/assets/13458218/215fca7e-7de3-42c8-af2a-662c3c99ee04)

IM7:
`magick f1-7.png -fuzz 5% -fill none -draw "alpha 275,314 floodfill" -alpha off x-7.png`

![x-7](https://github.com/ImageMagick/ImageMagick/assets/13458218/beb05fad-62b9-4345-9179-e796a408accd)

Note that the background color from the input should remain in the output, but in IM 7 it is turned black.

**Why do they behave differently? Is that intended?**

**Comment by urban-warrior** [comment]
Alpha is reversed in IMv6.  To properly visualize the results, composite the flooded image against a white background.  With this mod, we see both IMv6 and IMv7 produces identical results:

```
$ magick \( -size 296x335 xc:white \) \( f1-7.png -fuzz 5% -fill none -draw "alpha 275,314 floodfill" \) -composite x-7.png
$ convert \( -size 296x335 xc:white \) \( f1-7.png -fuzz 5% -fill none -draw "matte 275,314 floodfill" \) -composite x-6.png
$ magick compare -metric rmse ~/x-6.png x-7.png null:
0 (0) 
```

Notice, the zero distortion suggesting IMv6 and IMv7 flood-filling produces the same results as expected.

**Comment by fmw42** [comment]
But I want the orange background from the input image, not white

**Comment by fmw42** [comment]
But I want to keep the orange background from the input, not white (not black) and not a single orange color. It should just make that orange color transparent from the flood fill the same as in IM 6

**Comment by urban-warrior** [comment]
Floodfill acts as a mask.  It identifies which pixels are replaced by the fill color.  You set the fill color to `none` which is transparent black , just black after you remove the alpha channel.  Try `-fill #E89877`  to get the desired results.  With IMv6, you are seeing a side-effect of a bug in IMv6.  We export a patch for that issue and Imv6 and IMv7 will have identical results.

**Comment by fmw42** [comment]
This breaks my script if you make the background black in both versions.  I do not want a constant color there. I want to see the actual background with the rest of the image transparent (before -alpha off). If you make the background black and the mask makes the rest black, I will have a totally black image after -alpha off.

Any way to have a define to for the behavior that I need and was used in IM 6 before your "bug fix"?

**Comment by urban-warrior** [comment]
Since IMv6 is legacy, we can leave it as it.  However, IMv7 is behaving properly per the definition of flood-filling, that is, filling the connected areas with the specified fill color.  For IMv7, you'll need to revamp your command-line to get the desired results.

**Comment by fmw42** [comment]
No possibility for a define between the two behaviors?

**Comment by urban-warrior** [comment]
No, we limit how much effort we put into IMv6 as its legacy code and direct our attention instead to IMv7.

**Comment by fmw42** [comment]
I was asking about doing the define for IM 7

**Comment by urban-warrior** [comment]
IMv7 is behaving properly.  We don't want to introduce a define for buggy behavior.  You can get the desired results by refactoring you command-line.  You probably need to define the mask by flood-filling the alpha channel and composite it on the original image or flood-fill a mask channel.  Once you generate the proper command, it likely can be ported to IMv6 so you will get identical behavior with both.

**Comment by fmw42** [comment]
Sorry for the confusion.  Are you fixing IM 7 or IM 6?

**Comment by urban-warrior** [comment]
IMv7 behaves like IMv6 now.

**Comment by fmw42** [comment]
@urban-warrior. 

If you prefer to leave IM 7 as it was and have different behaviors, I have a work around that is likely working for more IM 7 versions as well as IM 6.  

Note, I agree with your first impression that IM 7 is more correct. That is using -fill none should have that color for the flood fill result, i.e. the base image under transparency is black not the original image. Correct IM 6 if you desire to the same behavior or leave them different.

**Comment by urban-warrior** [comment]
With this latest patch, IMv6 and IMv7 now behave exactly the same.  The `matte` floodfill operator only operates and fills the matte channel, previously IMv7 was not respecting the channel mask.

**Comment by fmw42** [comment]
It is not in the current 7.1.1.23 release.  Is that in the beta for me to test?

**Comment by urban-warrior** [comment]
Beta.

**Comment by fmw42** [comment]
It does not appear to be in the current beta.  I just downloaded it and tested and I get the same results as in my original post.

**Comment by urban-warrior** [comment]
We just tested, we get the same results as IMv6 above.  That is, only the alpha channel is floodfilled, then it becomes a no-op once you delete the alpha channel.

**Comment by fmw42** [comment]
Sorry, my mistake.  I accidentally tested with IM 7.1.1.23 not 7.1.1.24beta.

It does work as described when using the beta.

**Comment by fmw42** [comment]
Seems to work fine with IM 7.1.1.24beta, now.
