### ISSUE TITLE
Montage creating corrupt times on Raspberry Pi

### ISSUE THREAD

**Issue by Smashcat** [ImageMagick/ImageMagick#6937]
### ImageMagick version

6.9.11-60 Q16 arm

### Operating system

Linux

### Operating system, version and so on

Raspbian GNU/Linux 11 (bullseye)

### Description

When attempting to contatenate 2 images using montage, with a transparent background, result is a corrupt file. If I omit the "-background none" switch, the file is valid with white background.

### Steps to Reproduce

montage 0.png 0.png -background none -tile 2x -geometry +0+0 PNG32:0-tiled.png

### Images

![1](https://github.com/ImageMagick/ImageMagick/assets/599579/9f58d215-3b50-429a-99c1-dc2078538cd1)
![0](https://github.com/ImageMagick/ImageMagick/assets/599579/524c4624-97ba-4a39-a8f4-7faa47aa1635)

**Comment by urban-warrior** [comment]
You may need to upgrade your release of ImageMagick.  We tried you command with the latest release, 6.9.13-1, and got expected results.
