### ISSUE TITLE
JPEG2000 encoder crashes with YUV colorspace images

### ISSUE THREAD

**Issue by frkd-dev** [ImageMagick/ImageMagick#6943]
### ImageMagick version

7.1.1-21

### Operating system

MacOS

### Operating system, version and so on

macOS 14.1.2

### Description

Exporting JPEG2000 images in YUV colorspace is generally broken and unusable as it either produces corrupted images or crashes the app.

Also, the [jp2 encoder](https://github.com/ImageMagick/ImageMagick/blob/da099f2d2f62613644a942a8369bf986d9bfdf09/coders/jp2.c#L1043) is parsing a "-sampling-factor" option as "1:1" rather than "1x1" as specified in the documentation.

### Steps to Reproduce

Crash:
```sh
convert logo: -resize 5000x5000 -colorspace YUV logo.jp2
```
Corrupted image:
```sh
convert logo: -colorspace YUV -sampling-factor 2:2 logo.jp2
```

Non-decodeable image:
```sh
convert logo: -colorspace YUV logo.jp2
```

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Comment by frkd-dev** [comment]
> Also, the [jp2 encoder](https://github.com/ImageMagick/ImageMagick/blob/da099f2d2f62613644a942a8369bf986d9bfdf09/coders/jp2.c#L1043) is parsing a "-sampling-factor" option as "1:1" rather than "1x1" as specified in the documentation.

I see this wasn’t addressed by the commits. Is this expected behavior? If so, then perhaps it should be added to documentation, because now jp2 doc mentions absolutely [different formatting](https://github.com/ImageMagick/ImageMagick/blob/804e2b73a400d77270a0912f6f63a6f4fecf5dc4/www/jp2.html#L119). In other encoders sampling-factor uses "2x2" format, so this confuses a lot. 

I’m curious why sampling-factor option parsing isn’t mainstreamed and each encoder has to parse it by its own? This leads to situations when encoder can implement something that not follows the documentation like with jp2 encoder.

Do you accept PRs? I could implement a such common parsing.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
