### ISSUE TITLE
cannot update image title

### ISSUE THREAD

**Issue by FredVz** [ImageMagick/ImageMagick#6946]
### ImageMagick version

7.1.1-23 Q16 HDRI x64

### Operating system

Windows

### Operating system, version and so on

Windows 11 Family 22H2

### Description

Hello all,
I MUST update title and legend of 1660 jpg files... no choice.
I'm not a good developper (was some decades ago)
I ran a PowerShell script as admin in Windows 11 to update one file ttitle as a first try.
The script runs with no error but my jpg title is NOT modified :( 
I already spent days trying to find a solution, Majick seemed to be the best candidate but... I'm crying :D  

Thanks a million if you can solve my issue :) - Fred

### Steps to Reproduce

PS C:\WINDOWS\system32> $imageFilePath = "D:\ALFBXL\essai2\ev1908.jpg"
>> echo $imageFilePath
>>
D:\ALFBXL\essai2\ev1908.jpg
PS C:\WINDOWS\system32> $newTitle = "Nouveau Titre ev1908"
>>
PS C:\WINDOWS\system32> echo $newTitle
>>
Nouveau Titre ev1908
PS C:\WINDOWS\system32> if (Test-Path $imageFilePath -PathType Leaf) {
>>     magick $imageFilePath -set title "$newTitle" $imageFilePath
>>     Write-Host "Titre de l'image mis à jour avec succès : $newTitle"
>>     } else {
>>     Write-Host "Le fichier image n'a pas été trouvé : $imageFilePath"
>> }
>>
Titre de l'image mis à jour avec succès : Nouveau Titre ev1908
PS C:\WINDOWS\system32>

### Images

![image](https://github.com/ImageMagick/ImageMagick/assets/153724914/a30d224c-fe7d-4fc7-91f1-b5cf98dcfe8f)

**Comment by snibgo** [comment]
Please show or link to a JPG file that has a title.

**Comment by FredVz** [comment]
![ev1908](https://github.com/ImageMagick/ImageMagick/assets/153724914/aeafe82a-f66e-467c-9085-184731fca86c)

**Comment by FredVz** [comment]
![image](https://github.com/ImageMagick/ImageMagick/assets/153724914/16da93ec-3eab-4474-accf-ff39d5056e37)

**Comment by snibgo** [comment]
I can't download the JPG for some reason. Can you zip it, and upload the zip file?

**Comment by dlemstra** [comment]
The maximum dimensions of a jpeg file are `65535x65535`. Is your output image within these limits?

**Comment by snibgo** [comment]
```
C:\web\im>exiftool -G0 -args ev1908.jpg |grep -i title
-EXIF:XPTitle=evenement 1908 prem titre pour test
-XMP:Title=evenement 1908 prem titre pour test
```
So we have two titles. One is EXIF, the other is XMP.

I suggest you change these using exiftool:
```
exiftool -XMP:title="New XMP title" -EXIF:XPTitle="new exif title" e.jpg
```
Verify the changes:
```
C:\web\im>exiftool -G0 -args e.jpg |grep -i title
-EXIF:XPTitle=new exif title
-XMP:Title=New XMP title
```

**Comment by FredVz** [comment]
Thanks a lot indeed Snibgo.
I could succesfuly update picture's headline and caption with 
   .\exiftool.exe -charset IPTC=UTF8 -IPTC:Headline="$name" -IPTC:Caption-abstract="$caption" $name".jpg"

Last and big problem exiftool does not understand multiple lines captions - neither with CAR(10) nor <B /> 😢

**Comment by snibgo** [comment]
See `exiftool --help`. The "-ec" option does the trick:
```
exiftool -ec -XMP:title="New XMP\ntitle" e.jpg
```
The title now contains the newline character.

**Comment by FredVz** [comment]
Thanks Snibgo, my multiline caations are in :) :)
