### ISSUE TITLE
Problems with UTF-8 comment in PNG images

### ISSUE THREAD

**Issue by agguser** [ImageMagick/ImageMagick#6949]
### ImageMagick version

7.1.1-22

### Operating system

Linux

### Operating system, version and so on

Arch Linux 6.6.6

### Description

I have problems with UTF-8 comment metadata in PNG images (but not JPEG) when using with exiftool, so I create an issue https://github.com/exiftool/exiftool/issues/235, which says this might be a bug in ImageMagick (https://github.com/exiftool/exiftool/issues/235#issuecomment-1858428657).

### Steps to Reproduce

1. exiftool does not correctly display UTF-8 comments set by ImageMagick
```(sh)
$ ie() {   # set by ImageMagick, get by exiftool
   convert logo: "$1"; mogrify -comment "$2" "$1"; exiftool -p 'comment: $comment' "$1"; }

$ ie f.png 'Hi 😃'
comment: Hi ðŸ˜ƒ   # incorrect
Warning: [minor] Text/EXIF chunk(s) found after PNG IDAT (may be ignored by some readers) - f.png

$ ie f.jpg 'Hi 😃'
comment: Hi 😃   # correct if .jpg
```

2. UTF-8 comment set by exiftool is not displayed by ImageMagick
```(sh)
$ ei() {   # set by exiftool, get by ImageMagick
   convert logo: "$1"; exiftool -comment="$2" "$1"; identify -format 'comment: %c\n' "$1"; }

$ ei f.png 'Hi 😃'
Warning: [minor] Text/EXIF chunk(s) found after PNG IDAT (fixed) - f.png
    1 image files updated
comment:    # incorrect: comment not shown at all!

$ ei f.png 'Hi Smiley'
Warning: [minor] Text/EXIF chunk(s) found after PNG IDAT (fixed) - f.png
    1 image files updated
comment: Hi Smiley   # correct if no UTF-8

$ ei f.jpg 'Hi 😃'
    1 image files updated
comment: Hi 😃   # correct if .jpg
```

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
