### ISSUE TITLE
heap-buffer-overflow in GetPixelAlpha

### ISSUE THREAD

**Issue by wangdazhuang** [ImageMagick/ImageMagick#695]
Version: ImageMagick 7.0.6-10 Q16 x86_64 2017-08-24 http://www.imagemagick.org

```
magick convert  -resize '50%' crash_2.gif test.png

=================================================================
==32580==AddressSanitizer: while reporting a bug found another one. Ignoring.
==32580==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62500005229c at pc 0x7fdb8fc60d6d bp 0x7fdb8a4e6270 sp 0x7fdb8a4e6268
READ of size 4 at 0x62500005229c thread T3
    #0 0x7fdb8fc60d6c in GetPixelAlpha /root/ImageMagick/./MagickCore/pixel-accessor.h:59:10
    #1 0x7fdb8fc64cd1 in .omp_outlined..66 /root/ImageMagick/MagickCore/resize.c:2618:13
    #2 0x7fdb8e010742 in __kmp_invoke_microtask (/usr/lib/libomp.so+0x77742)
    #3 0x7fdb8dfca28b in __kmp_invoke_task_func (/usr/lib/libomp.so+0x3128b)
    #4 0x7fdb8dfc97d7 in __kmp_launch_thread (/usr/lib/libomp.so+0x307d7)
    #5 0x7fdb8e005e4b in __kmp_launch_worker(void*) (/usr/lib/libomp.so+0x6ce4b)
    #6 0x7fdb8e64c183 in start_thread /build/eglibc-SvCtMH/eglibc-2.19/nptl/pthread_create.c:312
    #7 0x7fdb8dab7ffc in clone /build/eglibc-SvCtMH/eglibc-2.19/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:111

0x62500005229c is located 1180 bytes to the right of 3584-byte region [0x625000051000,0x625000051e00)
allocated by thread T3 here:
    #0 0x4c19f7 in __interceptor_posix_memalign /work/release-test/final/llvm.src/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:142:3
    #1 0x7fdb8fae53a4 in AcquireAlignedMemory /root/ImageMagick/MagickCore/memory.c:262:7
    #2 0x7fdb8f78ff68 in AcquireCacheNexusPixels /root/ImageMagick/MagickCore/cache.c:4733:37
    #3 0x7fdb8f777fc7 in SetPixelCacheNexusPixels /root/ImageMagick/MagickCore/cache.c:4849:14
    #4 0x7fdb8f76e311 in GetVirtualPixelsFromNexus /root/ImageMagick/MagickCore/cache.c:2678:10
    #5 0x7fdb8f793ef5 in GetCacheViewVirtualPixels /root/ImageMagick/MagickCore/cache-view.c:664:10
    #6 0x7fdb8fc63bd9 in .omp_outlined..66 /root/ImageMagick/MagickCore/resize.c:2542:7
    #7 0x7fdb8e010742 in __kmp_invoke_microtask (/usr/lib/libomp.so+0x77742)
    #8 0x7fdb8dfca28b in __kmp_invoke_task_func (/usr/lib/libomp.so+0x3128b)

Thread T3 created by T0 here:
    #0 0x4aa2e6 in __interceptor_pthread_create /work/release-test/final/llvm.src/projects/compiler-rt/lib/asan/asan_interceptors.cc:305:3
    #1 0x7fdb8e0054d4 in __kmp_create_worker (/usr/lib/libomp.so+0x6c4d4)

SUMMARY: AddressSanitizer: heap-buffer-overflow /root/ImageMagick/./MagickCore/pixel-accessor.h:59:10 in GetPixelAlpha
Shadow bytes around the buggy address:
  0x0c4a80002400: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80002410: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80002420: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80002430: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80002440: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c4a80002450: fa fa fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80002460: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80002470: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80002480: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80002490: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a800024a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==32580==ABORTING 
```
![crash_2](https://user-images.githubusercontent.com/13193376/29657347-dd62c4ea-88e9-11e7-8baf-bf2ff5c78640.gif)

**EDIT** Next time please put your stack trace in a code block.

**Comment by dlemstra** [comment]
Next time please put your stack trace in a code block.

**Comment by mikayla-grace** [comment]
Unfortunately we cannot reproduce the problem.   Can you post a URL to your crash_2.gif so we can download it.  Perhaps the problem is specific to your image.  In the mean-time, if you build ImageMagick with `configure --disable-openmp`, the problem will likely resolve itself.

**Comment by wangdazhuang** [comment]
The problem was resolved when configured with --disable-openmp, Please ignore the issue, thanks~

**Comment by wangdazhuang** [comment]
FYI.
I compiled ImageMagick with asan, see the command below:
CC=clang CXX=clang++ ./configure CFLAGS="-O0 -g  -fsanitize=address" CXXFLAGS="-O0 -g  -fsanitize=address"
Without  --disable-openmp, the problem can be reproduced every time.

magick convert  -resize '50%' crash_2.gif test.png

testfile: https://github.com/wangdazhuang/pocs/blob/master/crash_2.gif

**Comment by mikayla-grace** [comment]
Unfortunately we cannot reproduce the problem.   Which version of clang are you using?  We suspect a bug in the OpenMP implementation for that release.  We're using clang version 4.0.0-1ubuntu1~16.04.2 and ImageMagick 7.0.7-0 Beta.  We compiled as you suggested and the magick command completed without complaint.  Assuming its a threading issue, we ran your command 10,000 times. It did not fail.

**Comment by wangdazhuang** [comment]
OS:     Linux dazhuang-fuzz 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
clang:   clang+llvm-4.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
Version: ImageMagick 7.0.6-10 Q16 x86_64 2017-08-24 http://www.imagemagick.org

**Comment by wangdazhuang** [comment]
root@a77dae2cec72:~# uname -a
Linux a77dae2cec72 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@a77dae2cec72:~# clang -v
clang version 4.0.0 (tags/RELEASE_400/final)
Target: x86_64-unknown-linux-gnu


I also tested on fedora23, the problem still exists.

[root@localhost workspace]# uname -a
Linux localhost.localdomain 4.2.3-300.fc23.x86_64 #1 SMP Mon Oct 5 15:42:54 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost workspace]# clang -v
clang version 3.9.0 (tags/RELEASE_390/final)
Target: x86_64-unknown-linux-gnu

[root@localhost workspace]#  magick -version
Version: ImageMagick 7.0.6-6 Q16 x86_64 2017-09-04 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP
Delegates (built-in): bzlib fontconfig freetype lzma pangocairo png x xml zlib

**Comment by mikayla-grace** [comment]
We have ImageMagick 7.0.7-0, Fedora 26, clang 4.0.1 with ASN enabled, and libgomp 7.1.1-3.  We resized your image for 50,000 iterations.  All iterations completed without complaint (other than the 'Ignoring invalid time value' warning).  As expected, we need to reproduce the problem to ensure the problem is localized to ImageMagick.  When we do, we will offer a patch.
