### ISSUE TITLE
7.1.1-23 has (Beta) in the version string

### ISSUE THREAD

**Issue by debohman** [ImageMagick/ImageMagick#6950]
### ImageMagick version

7.1.1-23

### Operating system

MacOS

### Operating system, version and so on

macOS

### Description

`configure.ac` is correct. Rebuilding `configure` fixes it. 

### Steps to Reproduce

Configure the project, and build it. It generates the following:

`Version: ImageMagick 7.1.1-23 (Beta) Q16-HDRI x86_64 b135bacc6:20231210 https://imagemagick.org`

Regenerate configure, configure the project and build it. You get the following:

`Version: ImageMagick 7.1.1-23 Q16-HDRI x86_64 54b13e91d:20231210 https://imagemagick.org`

**Comment by debohman** [comment]
It seems that `configure` was not generated for the release. Note that I am building out of the repository.

**Comment by urban-warrior** [comment]
Its possible the release tag is off by a commit where we resolve the "beta" issue.  We'll correct it, perhaps tomorrow, when 7.1.1-24 will be released.

**Comment by debohman** [comment]
The tag seems to be correct. It really looks like `configure` was not regenerated after `configure.ac` was modified.

Don't worry, I just regenerated `configure`.

Here is the top of the git log:

```
commit 54b13e91d262b1083e27fc8c02532c89d3ff649c (HEAD, tag: 7.1.1-23)
Author: Cristy <urban-warrior@imagemagick.org>
Date:   Sun Dec 10 15:11:32 2023 -0500

    release

commit e6cfc7cb4cbd6c2b5c3ffd01774b07712bdef25e
Author: Cristy <urban-warrior@imagemagick.org>
Date:   Sun Dec 10 15:10:49 2023 -0500

    beta release

commit b135bacc69df9f1de0b71cf3638f7e8296bbfb57
Author: Cristy <urban-warrior@imagemagick.org>
Date:   Sun Dec 10 13:58:58 2023 -0500

    release

commit c5567ea1c23d6bd7dd41c6b7fb7660c5245bdf19
Author: Dirk Lemstra <dirk@lemstra.org>
Date:   Sun Dec 10 18:03:14 2023 +0100

    Fixed patch for non windows platform.
```
