### ISSUE TITLE
[magick++] How to set antialias when rendering pdf

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#696]
The `convert` utility allows for controlling antialias when reading a pdf file:

```
convert -density 100x100 +antialias test.pdf test.png
```

How to set antialias in magick++ when reading images via e.g. `Magick::readImages()`? I had a look at `Magick::ReadOptions` which sets depth / density, but I can't enable/disable antialiassing.

**Comment by dlemstra** [comment]
That option is not yet available in the ReadOptions class. You could help us with a pull request to add this. You should use the `antialias` property of the `_imageInfo` of that class.
