### ISSUE TITLE
fx calculations of skewness and kurtosis

### ISSUE THREAD

**Issue by snibgo** [ImageMagick/ImageMagick#6964]
### ImageMagick version

7.1.1-20 and older

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

This is a very old bug. Perhaps it has always been present. When I re-wrote fx.c, I didn't understand the meanings of `skewness` and `kurtosis`, and I simply copied what the old fx code did. The code calls `GetImageStatistics()`, and multiplies all statistics by `QuantumScale`. That is correct for mean, median, maxima, minima and standard_deviation. It is incorrect for skewness and kurtosis. Those statistics are dimensionless, and should not be multiplied by QuantumScale. If we multiply an image by `k`, the mean and standard deviation should also multiply by `k`, but skewness and kurtosis should not change. (I don't know if entropy is also wrong.)

### Steps to Reproduce

A simple demonstration with the skewness of the red channel:
```
magick rose: -verbose info: |grep -i skewness |head -n 1
      skewness: 0.14630194
```
That number is correct. But if we use fx...
```
magick rose: -format "r=%[fx:skewness.r]\n" info:
r=3.4063576e-11
```
... the result is wrong.

The workaround is to multiply by QuantumRange:
```
D:\temp>%IM7DEV%magick rose: -format "r=%[fx:skewness.r*QuantumRange]\n" info:
r=0.14630194
```
I suppose this bug has always been present. If anyone uses fx for kurtosis or skewness, they probably know it needs to by multiplied by QuantumRange, and perhaps regard this an an "undocumented feature" rather than a bug.

If the bug is fixed, it might break existing scripts.

So I do not propose that this bug is fixed.

### Images

N/A

**Comment by fmw42** [comment]
I think it should be fixed.  But I am open to hear from other users about use in scripts that might break.

**Comment by urban-warrior** [comment]
Our priority is to not break existing behavior-- unless its determined to be a bug.  This issue looks like a bug, so we should fix it.

**Comment by snibgo** [comment]
That's fine. I'll close the issue.

**Comment by SergeSirota** [comment]
Hi, Alan.
I found your link on the forum with the latest version of the «ImageMagickJbject.dll».
But the link «snibgo.com/im/ImageMagick-7.1.0-19-Q16-HDRI-x64-dll.exe» contains a file of zero length.
Can you help me?
Yours, Serge Sirota.
