### ISSUE TITLE
imagemagick.org is not the same site as www.imagemagick.org

### ISSUE THREAD

**Issue by jmfgdev** [ImageMagick/ImageMagick#698]
compare the following:
https://imagemagick.org/script/download.php

https://www.imagemagick.org/script/download.php

As you can see, www.imagemagick.org shows imagemagick 7 as the recommended download,
sans the www, version 6 is shown.

Is this intentional? If it is, it's very confusing, its not THAT hard to end up on imagemagick.org rather than www.imagemagick.org considering most people know the domain is imagemagick.org and won't go to a search engine and will rather probably type imagemagick.org in their browser, which in my case, would take me to the page suggesting version 6 to download.

**Comment by mikayla-grace** [comment]
Try now.

**Comment by jmfgdev** [comment]
It's the same for me, cleared cache and tried it again and still the same behavior

**Comment by fmw42** [comment]
The first link:

https://imagemagick.org/script/download.php

is going to the legacy web site

https://legacy.imagemagick.org/script/download.php

**Comment by jmfgdev** [comment]
That does seem to be the current behavior

**Comment by dlemstra** [comment]
Looks like it is fixed now?
