### ISSUE TITLE
APNG specifier cant be used on images from the web

### ISSUE THREAD

**Issue by MichaelPriebe** [ImageMagick/ImageMagick#6980]
### ImageMagick version

7.1.1-24

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

The APNG format specifier cant be used on images from the web.

### Steps to Reproduce

ImageMagick does support urls:

```
magick identify https://em-content.zobj.net/source/microsoft-teams/363/grinning-face_1f600.png
```

But specifying it as an apng makes ImageMagick unable to open the image:

```
magick identify apng:https://em-content.zobj.net/source/microsoft-teams/363/grinning-face_1f600.png
```
```
identify: unable to open image 'https://em-content.zobj.net/source/microsoft-teams/363/grinning-face_1f600.png': Invalid argument @ error/blob.c/OpenBlob/3572.
```

### Images

https://em-content.zobj.net/source/microsoft-teams/363/grinning-face_1f600.png

**Comment by urban-warrior** [comment]
ImageMagick is behaving properly.  APNG leverages a delegate program and for security reasons we sanitize the image filename and require that it is on local disk before we pass it to the delegate program.  We will apply a patch today so that this command will work:

```
curl https://em-content.zobj.net/source/microsoft-teams/363/grinning-face_1f600.png | magick identify apng:-
```
