### ISSUE TITLE
can not open png, but is shown in windows (relying on WIC codec) and browsers (that uses libpng)

### ISSUE THREAD

**Issue by Charltsing** [ImageMagick/ImageMagick#6983]
### ImageMagick version

7.1.1.17

### Operating system

Windows

### Operating system, version and so on

Windows10 22H2

### Description

[png.zip](https://github.com/ImageMagick/ImageMagick/files/13793708/png.zip)
this png file contains an invalid value for the adaptive filter

I open it use Magick.Net:
![293328351-551540a0-6fdf-4931-a4d4-19e12abb71c1](https://github.com/ImageMagick/ImageMagick/assets/19963715/53dd2a50-7b37-4084-a4eb-1a9fec8de136)

It is shown in windows (relying on WIC codec) and browsers (that uses libpng), so i hope imagemagick  can open it.

### Steps to Reproduce

you can see it:
https://github.com/saucecontrol/PhotoSauce/issues/139#issuecomment-1806421745

https://github.com/dlemstra/Magick.NET/issues/1500

**Comment by snibgo** [comment]
`pngcheck 1.png` says:
```
1.png  private (invalid?) IDAT row-filter type (136) (warning)
1.png  private (invalid?) IDAT row-filter type (136) (warning)
1.png  private (invalid?) IDAT row-filter type (153) (warning)
1.png  private (invalid?) IDAT row-filter type (136) (warning)
1.png  private (invalid?) IDAT row-filter type (136) (warning)
1.png  CRC error in chunk IDAT (computed 2a1ccc06, expected 00001c00)
ERROR: 1.png
```
IM is strict, and won't read corrupt files.

If another program can read it, you can use that program to save the image in a file, and use IM to read that.

**Comment by dlemstra** [comment]
As I told you in the other issue we are not able to read that image because it is corrupt.

**Comment by Charltsing** [comment]
> As I told you in the other issue we are not able to read that image because it is corrupt.

but windows can open it,  I cannot explain this problem to my user.
so i hope imagemagick can open it.

**Comment by dlemstra** [comment]
It cannot, the file is corrupt and that is why we cannot open it.

**Comment by fmw42** [comment]
Imagemagick follows strict rules about processing. If the file does not follow the specs properly, it won't be open.  Other tools may be more forgiving about opening files that do not follow specs. That is the explanation you need.

**Comment by Charltsing** [comment]
> Imagemagick follows strict rules about processing. If the file does not follow the specs properly, it won't be open. Other tools may be more forgiving about opening files that do not follow specs. That is the explanation you need.

Usually, users do not listen to my explanations, they only use Windows behavior as a basis for judging whether the software functionality is correct

**Comment by Charltsing** [comment]
> > Imagemagick follows strict rules about processing. If the file does not follow the specs properly, it won't be open. Other tools may be more forgiving about opening files that do not follow specs. That is the explanation you need.
> 
> Usually, users do not listen to my explanations, they only use Windows behavior as a basis for judging whether the software functionality is correct

they will say : Windows can open it, your soft must open it too!
