### ISSUE TITLE
Perl API change after 7.1.1-21?

### ISSUE THREAD

**Issue by schmonz** [ImageMagick/ImageMagick#6984]
### ImageMagick version

7.1.1-23

### Operating system

Other (enter below)

### Operating system, version and so on

NetBSD/amd64 9.3

## What I tried

I updated from ImageMagick and PerlMagick 7.1.1-21 to 7.1.1-23 on my development machine running macOS, saw no breakage on my staged websites, then performed the same update on my production server running NetBSD.

I performed the updates on both platforms the same way I always do, which is to install the latest versions from pkgsrc (here's the [p5-PerlMagick package's commit history](https://github.com/NetBSD/pkgsrc/commits/trunk/graphics/p5-PerlMagick)).

## What I expected to happen

I anticipated no breakage on my production websites, given the changelog entries and the uneventful package updates on the macOS side.

## What actually happened

In production, I saw image rendering errors from my web CMS (ikiwiki), of several kinds:

- `failed to determine size`: all `.jpg` or `.JPG`
- `failed to get dimensions`: some `.gif`, some `.jpg`, some `.JPG`
- `failed to read`: all `.png`, followed by the message `Exception 425: unable to read image data png:/correct/looking/path/to/file.png` from `error/constitute.c/ReadImage/991` 

The site contains approximately 200 images and I see about 160 errors.

## What confuses me

What could account for PerlMagick behaving this differently on NetBSD from 7.1.1-21 to 7.1.1-23, especially when it behaves the same -- as we would all expect, presumably! -- on macOS between those same versions?

Has ikiwiki perhaps been invoking PerlMagick incorrectly for a while, and got lucky until just now? Here's the [`img` plugin code](http://source.ikiwiki.branchable.com/?p=source.git;a=blob;f=IkiWiki/Plugin/img.pm;h=b85824345ed6e1634cf6f43b08ac3887a56117d4;hb=HEAD) (and [end-user docs](http://ikiwiki.info/ikiwiki/directive/img/)) where the errors are coming from.

I know this is far from a minimal reproducer. How would you suggest I try to narrow this down?

### Steps to Reproduce

1. On NetBSD, run `ikiwiki --setup /path/to/mysite.setup`
2. In a browser, observe e.g. `[[!img Error: failed to determine size of image images/cokebabies.jpg]]` where the rendered image should be

**Comment by urban-warrior** [comment]
First try the ImageMagick + PerlMagick unit tests:

```
$ cd ImageMagick-7.1.1
$ make check
$ cd PerlMagick
$ make test
$ cd demo
$ make
```

Do the unit tests complete?  You can also replace `PerlMagick/quantum/quantum.xs.in` with the version from IMv 7.1.1.21.  If that fixes the issue, the problem is isolated to PerlMagick.

**Comment by schmonz** [comment]
On NetBSD/amd64 9.3, `make check`:

- 7.1.1-21 fails 1 of 87 (`tests/cli-pipe`), passing the remaining 86
- 7.1.1-22 fails 52 of 87, passing the remaining 35
- 7.1.1-23 same as -22

Maybe the Perl bindings are fine, maybe not, but that's not our problem yet :-)  I'll try bisecting -21 and -22 and report back.

**Comment by schmonz** [comment]
On NetBSD/aarch64 10.0_RC1 (a very similar system that can bisect much faster):

- Last "good" commit (still failing only 1/87 tests) was [d8b38c26f](https://github.com/ImageMagick/ImageMagick/commit/d8b38c26fcd7df5c82aa457ecf7903079399a2da)
- First "bad" commit (failing 55/87) was 
[86d2efbbb](https://github.com/ImageMagick/ImageMagick/commit/86d2efbbb413c758a0f9c26a9c9c4b88df549a96)

What's my next useful step? I'm happy to try things, or if it'd be easiest for an ImageMagick developer to work on the problem(s) directly, I can easily provide SSH access to a NetBSD system.

**Comment by urban-warrior** [comment]
Let's make this easy, we set up a temp email account, netbsd @ imagemagick.org.  Provide access to a netbsd system so we can do proper forensics.  Thanks.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Comment by schmonz** [comment]
I applied this patch to my production 7.1.1-23 and can confirm my sites are back to rendering images normally. Thanks for the quick turnaround!
