### ISSUE TITLE
Chopping an image with virtual canvas has inconsistent behavior

### ISSUE THREAD

**Issue by BlackXStar42** [ImageMagick/ImageMagick#6997]
### ImageMagick version

7.1.1-24

### Operating system

Windows

### Operating system, version and so on

7, 6.1.7601

### Description

I am trying to chop an image which has a virtual canvas. In one case, I add the the canvas through `-page` and then `-chop` in the same command. In another case, I `-chop` an existing image containing a virtual canvas. In both cases I'm chopping off the same part of the image, yet they yield different results. I would like to understand:
1) Shouldn't the both methods below yield the same result?
2) As I am chopping 10 pixels from the north and the west, shouldn't the resulting virtual canvas be either 40x40+0+0 (if `-chop` also chops off the canvas) or 50x50+10+10 (if `-chop` doesn't chop off the canvas)? 

I have noticed this behavior when I used `-append`. It seems IM makes a decision on behalf of the user to add a virtual canvas in the resulting image derived from the first image in the sequence. So my additional question is:

3) What is the purpose of automatically adding a virtual canvas when using `-append` or `+append`?

### Steps to Reproduce

```
>magick convert -size 100x100 xc: -page 50x50 -chop 10x10 VCChoppedImm.png
>magick identify VCChoppedImm.png
VCChoppedImm.png PNG 90x90 50x50+0+0 8-bit Grayscale Gray 2c 335B 0.001u 0:00.000

>magick convert -size 100x100 xc: -page 50x50 VC.png
>magick convert VC.png -chop 10x10 VCChoppedLoad.png
>magick identify VCChoppedLoad.png
VCChoppedLoad.png PNG 90x90 45x45+0+0 8-bit Grayscale Gray 2c 335B 0.000u 0:00.000
```

**Comment by urban-warrior** [comment]
`magick convert` is the legacy command-line interpreter.    Don't use it.  Instead, just use `magick`:

```
$ magick  -size 100x100 xc: -page 50x50 -chop 10x10 VCChoppedImm.png
$ magick identify VCChoppedImm.png
VCChoppedImm.png PNG 90x90 45x45+0+0 8-bit Grayscale Gray 2c 335B 0.000u 0:00.000
```
