### ISSUE TITLE
Option to skip determining a new png:tIME when writing a file

### ISSUE THREAD

**Issue by BlackXStar42** [ImageMagick/ImageMagick#6999]
### Is your feature request related to a problem? Please describe.

There are scnearios where I want to retain the existing value for the property, for instance when I patch existing image files and I don't want to introduce additional changes just through new timestamps. Sometimes it may also be necessary to set the `png:tIME` to a particular value for conformance reasons. It seems there is currently no way to achieve this with IM as IM always determines `png:tIME` by setting it to the current system time when a file is written.

### Describe the solution you'd like

A new switch on the command line could toggle between the existing and the desired behavior.

### Describe alternatives you've considered

Existing files may contain filestamps, which may be beyond my control. So removing the timestamps altogether, which is already supported by IM, is not helping with keeping the number of changes minimal.

**Comment by urban-warrior** [comment]
Try setting the `png:tIME` (if image is not modified) or `date:modify` (if image is modified) properties with `-define` or `-set`.
