### ISSUE TITLE
ImageMagick generates improper output images

### ISSUE THREAD

**Issue by DigneshGoyal** [ImageMagick/ImageMagick#7]
i have used below command
convert.exe input.psd[0] -intent relative -sample 500x375 -quality 95 -auto-orient -strip output.jpg

file can be accessed fom below location

http://tinyurl.com/dignesh-com

**Comment by dlemstra** [comment]
Downsizing blends numerous pixels about the central pixel.  If you remove the alpha channel you'll see the area around the headphones are highlighted.  It looks like the highlights in some cases lighten up certain pixels to give the appearance of artifacts.  Remove the alpha channel and you get reasonable results or if you include the alpha channel, linear light and the triangle filter returns similiar good results.

This works good for the image:
`convert.exe input.psd[0] -colorspace RGB -filter Triangle -distort Resize 500x375 -colorspace sRGB  -quality 95 -auto-orient -strip output.jpg`

or better yet remove the alpha channel before resizing:
`convert input.psd[0] -alpha off -colorspace RGB -resize 500x375 -colorspace sRGB  -quality 95 -auto-orient -strip output.jpg`

**Comment by DigneshGoyal** [comment]
Thank you so much ..It worked ..Appreciate Your help on this.. :)
