### ISSUE TITLE
Option to skip determining a new date:create/modify when reading a file

### ISSUE THREAD

**Issue by BlackXStar42** [ImageMagick/ImageMagick#7000]
### Is your feature request related to a problem? Please describe.

There are scenarios where I want to check the properties of an existing file. It seems there is currently no way to achieve this with IM as IM always determines those properties by retrieving them from the file system when a file is read.

### Describe the solution you'd like

A new switch on the command line could toggle between the existing and the desired behavior.

**Comment by fmw42** [comment]
Have you looked at all the -defines at https://imagemagick.org/script/defines.php

For example:

`-define preserve-timestamp=true|false`        Preserve file timestamp (mogrify only).

Not sure why it is limited to mogrify though.

**Comment by urban-warrior** [comment]
Clarify your ask.  To gather properties associated with an image, ImageMagick will of course need to read the image.  The image is the metadata store.  Doing so should not be an issue unless you don't want to update the image file read date.  When writing the image, the properties are updated except as Fred mentioned, you can preserve the file stamp with the  `mogrify` CLI utility by enabling the `preserve-timestamp` define.
