### ISSUE TITLE
Caption: weird behavior depending on first letter capitalization  

### ISSUE THREAD

**Issue by WillemMe** [ImageMagick/ImageMagick#7004]
### ImageMagick version

7.1.1-21

### Operating system

Linux

### Operating system, version and so on

Debian bullseye

### Description

I was trying to make a `caption:` best fill a box horizontal and vertical. When the `caption:` starts with a capital letter or `"` the auto-fit works. However, when it starts with a lowercase letter it fails to utilize all vertical space.  

### Steps to Reproduce

This fit best in both axis
```
convert -background grey -fill black -gravity Center -size 330x330 caption:"This is a very long caption that should fill the grey box as most as possible and not only stick the the horizontal"  out.jpg
```
This fails to utilize all vertical space:
```
convert -background grey -fill black -gravity Center -size 330x330 caption:"this is a very long caption that should fill the grey box as most as possible and not only stick the the horizontal"  out.jpg
```

### Images

![lower](https://github.com/ImageMagick/ImageMagick/assets/20991420/0b7fa6ca-b9ad-4a35-ac8d-7a0c85d93655)
![Capital](https://github.com/ImageMagick/ImageMagick/assets/20991420/7974b366-6da0-4847-83c5-141578efa0d0)

**Comment by fmw42** [comment]
On IM 7, I suggest you use magick, not convert.   What is the font you are using?  Perhaps its font glyphs are not defined properly.  It works fine for me on IM 7.1.1.25 using my default font.

Cap:

![out](https://github.com/ImageMagick/ImageMagick/assets/13458218/9c2f72e0-5cc7-4233-8399-be5d8630a1ff)

No Cap:

![out2](https://github.com/ImageMagick/ImageMagick/assets/13458218/5e387da1-4cb8-46dc-8352-be0ea6cc3ec7)

**Comment by WillemMe** [comment]
I played around with it some more.
This works nicely
`magick -background grey -gravity Center -fill black -size 330x330 caption:'eeen a a more words hele word lang qor some more words\n\nby me' out.jpg`
![works](https://github.com/ImageMagick/ImageMagick/assets/20991420/8a93443a-e15b-4f40-a9d2-7e345a47b31d)

whilst with one letter less doesn't
`magick -background grey -gravity Center -fill black -size 330x330 caption:'een a a more words hele word lang qor some more words\n\nby me' out.jpg
`
![not](https://github.com/ImageMagick/ImageMagick/assets/20991420/393b66f7-b534-47ca-8033-5318e3673ba6)

The line height of the characters seem to matter. If I capitalize a letter that should come on the second line it also produces something nicely. 
`magick -background grey -gravity Center -fill black -size 330x330 caption:'een a a more words helE word lang qor some more words\n\nby me ' out.jpg`

Whilst this fails again:
`magick -background grey -gravity Center -fill black -size 330x330 caption:'een a a Eore words hele word lang qor some more words\n\nby me ' out.jpg` 

I'm guessing this is just on the boundary of when the caption algorithm decides whether to increase the pointsize.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
