### ISSUE TITLE
Magick++-config fails when the .pc file is not installed in a place searched by pkg-config by default

### ISSUE THREAD

**Issue by TedLyngmo** [ImageMagick/ImageMagick#7007]
### ImageMagick version

7.1.1-25

### Operating system

Linux

### Operating system, version and so on

Fedora 39

### Description

Magick++-config fails when the .pc file is not installed in a place searched by pkg-config by default.

### Steps to Reproduce

```
$ ./configure CFLAGS=-O3 CXXFLAGS=-O3 --disable-static --prefix ~/local
$ make
$ make install
$ Magick++-config --libs
Package Magick++-7.Q16HDRI was not found in the pkg-config search path.
Perhaps you should add the directory containing `Magick++-7.Q16HDRI.pc'
to the PKG_CONFIG_PATH environment variable
Package 'Magick++-7.Q16HDRI', required by 'virtual:world', not found
```

**Comment by urban-warrior** [comment]
You will need to set the  PKG_CONFIG_PATH environment variable as recommended in the documentation.

**Comment by TedLyngmo** [comment]
> You will need to set the PKG_CONFIG_PATH environment variable as recommended in the documentation.

Yes, that would work if there is no ImageMagick installed in a standard path, but if you do and then build from source and install in your home directory, you want your `~/local/bin/Magick++-config` to pick `~/local/lib/pkgconfig/Magick++-7.Q16HDRI.pc` instead of the one in the standard path. That's why my patch used `PKG_CONFIG_LIBDIR` to put it first in the search path.
