### ISSUE TITLE
HEIC to JPEG conversion results in HEIF format

### ISSUE THREAD

**Issue by timrettop** [ImageMagick/ImageMagick#7009]
### ImageMagick version

7.1.1-22

### Operating system

Linux

### Operating system, version and so on

Alpine 3.19 (latest)

### Description

using imagemagick convert HEIC to JPEG in the alpine repo results in a file with the descriptor "IMG_5746.JPG: ISO Media, HEIF Image HEVC Main or Main Still Picture Profile" when its expected to be JPEG image data. 

My environment: 

```
/ # convert -version
Version: ImageMagick 7.1.1-22 Q16-HDRI aarch64 21779 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): bzlib cairo fftw fontconfig freetype gslib heic jng jpeg jxl lcms ltdl lzma pangocairo png ps raw rsvg tiff webp x xml zlib
Compiler: gcc (13.2)

/src # apk info libheif
libheif-1.17.3-r1 description:
ISO/IEC 23008-12:2017 HEIF file format decoder and encoder

/src # apk info libde265
libde265-1.0.15-r0 description:
Open h.265 video codec implementation
```

### Steps to Reproduce

docker run -it  alpine:latest    // I include --mount type=bind,src="$(pwd)",target=/src to test with my host files
apk add --update imagemagick imagemagick-heic
wget https://github.com/tigranbs/test-heic-images/raw/master/image1.heic
convert image1.heic image1.jpeg
file image1.jpeg

### Images

Included in repro steps

**Comment by dlemstra** [comment]
You also need to install `jpeg` if you want to use that as the output format. Executing `apk add jpeg` resolved your issue.

**Comment by timrettop** [comment]
Thanks, such a simple fix!
