### ISSUE TITLE
Text is looking smaller after the version update

### ISSUE THREAD

**Issue by catalinnp** [ImageMagick/ImageMagick#7010]
### ImageMagick version

7.1.1.-25

### Operating system

MacOS

### Operating system, version and so on

macOS Ventura Version 13.1

### Description

I updated my version of ImageMagick from `7.1.0-51` to the new one `7.1.1-25` and discovered a bug while generating text in a specific field.

As you can see from the attached images, the text is smaller in the newer version.

I have over 2000 manual customizations for different types of text and I cannot just make it bigger, because that would mean manually changing all 2000 designs' sizes (e.g. from "2600x420" to "2900x420").

 Something that can work for all of them will be perfect.

### Steps to Reproduce

For generating the exact text in a specific field I am using this command: 
`convert -size 2600x420 -background transparent -gravity west -fill "black" -font ~/fonts/Macaw-Medium.otf  "label: Laura" -stroke red -strokewidth 3 -fill none -draw "rectangle 0,0 2597,417"  ~/Laura.png`

_I added the red stroke to better see the margins and to better point out that the text is smaller_

Nothing else changed in my command after changing the versions.

### Images

This is how normally looked before changing the version:
![out-temp-phd-definition-motivational-1-Laura-0](https://github.com/ImageMagick/ImageMagick/assets/18000184/bf904189-42c2-4490-b785-baf820aaf8da)

This is after changing the version:
![out-temp-phd-definition-motivational-1-Laura-0](https://github.com/ImageMagick/ImageMagick/assets/18000184/d744f509-f49f-4844-9240-f6e4653e75bb)

**Comment by urban-warrior** [comment]
Our goal is to maintain consistency across releases-- unless there is a bug.  If someone posts an issue and its determined to be a bug, we'll fix it.  The fix sometimes has side-effects such as the one you posted here.  We had an issue where if you created two different labels and appended them, they would not always line up. In addition, we had some labels where some parts of the label were being cut-off.  We had to adjust the font metrics to ensure each label would append along the same baseline and not be cut-off.

**Comment by catalinnp** [comment]
Hello,

Thanks so much for the fast response.

Based on what you said, I either:
1. change the version back - if you have an idea of how to do it with Brew, it will be very helpful - like a link or something similar, because I only saw the last version on the install (or v.6, which is too old)
2. update on my side with the idea that won't change again - but here I am a little afraid. If changes like this happen overnight, nobody can guarantee that they might happen again.

Nevertheless, thank you!

**Comment by urban-warrior** [comment]
Can you check ImageMagick version 7.1.1-27?  Run your command again and see if you get expected results.

**Comment by catalinnp** [comment]
Thanks! I installed the new version, but the results are the same.

**Comment by urban-warrior** [comment]
As mentioned, we fixed a bug in the past and the existing behavior is a side-effect of the bug fix.  We do not anticipate any additional changes to the algorithm.

**Comment by catalinnp** [comment]
From your earlier comment, I understood that it might get changed. 

What's the best way to install back the `7.1.0-50` version? I am trying to find the binary or with brew, but it's not working.

Any hints?

**Comment by urban-warrior** [comment]
You can download the source distribution for 7.1.0-50 from the [releases folder](https://imagemagick.org/archive/releases/) and build + install it.
