### ISSUE TITLE
Magick++: Magick::Image::channel() can not be used on const Magick::Image

### ISSUE THREAD

**Issue by HorstBaerbel** [ImageMagick/ImageMagick#7011]
### Is your feature request related to a problem? Please describe.

You can't use channel() on const Magick::Images. This is unfortunate, because a copy of the Magick::Image is needed.

### Describe the solution you'd like

Introduce a getConstChannel() method or a const override for channel()

### Describe alternatives you've considered

A copy of the Magick::Image

**Comment by dlemstra** [comment]
You cannot do that because the image gets changed? And that is why you cannot use this with a `const`.  But you can use the `separate` method?

**Comment by HorstBaerbel** [comment]
It is missing in the docs [here](https://imagemagick.org/Magick++/Image++.html). The doxygen docs [here](https://imagemagick.org/api/Magick++/classMagick_1_1Image.html) give no clue as to what it does.

**Comment by urban-warrior** [comment]
As an open-source project, we're always looking for volunteers to improve the Magick++ documentation.

**Comment by HorstBaerbel** [comment]
> You cannot do that because the image gets changed? And that is why you cannot use this with a `const`. But you can use the `separate` method?

seperate() seems to work. Thanks.
