### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [ImageMagick/ImageMagick#7015]
### Describe the solution you'd like

Dear @ImageMagick team, @dlemstra, @urban-warrior, ...

In first, I wish you a Happy New Year 2024!

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/imagemagick/

To disable/delete tabs, go here: https://sourceforge.net/projects/imagemagick/
To add a new tab, go here: https://sourceforge.net/projects/imagemagick/
To change informations, go here: https://sourceforge.net/p/imagemagick/admin/overview
To export, go here: https://sourceforge.net/p/imagemagick/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/imagemagick/admin/overview
- A new tab, go here: https://sourceforge.net/projects/imagemagick/

Time to remove the "Code" tab:
- https://sourceforge.net/p/imagemagick/code/

Note:
@urban-warrior: I think that you must to add admin @dlemstra on Sourceforge:
- https://sourceforge.net/u/dirklemstra/profile/

Glenn Randers-Pehrson is dead since 2018 :/
I think that you can add the new libpng leader: Cosmin Truta: @ctruta too:
- https://sourceforge.net/p/imagemagick/_members/
- https://sourceforge.net/p/libpng/_members/

@urban-warrior: Please add your visibility in Public, you are currently in Private here:
- https://github.com/orgs/ImageMagick/people

Thanks in advance.

**Comment by urban-warrior** [comment]
Most/all changes made per your suggestions.

**Comment by Neustradamus** [comment]
@urban-warrior: Thanks a lot for your quick changes! :)

On Sourceforge, I see links:
- https://github.com/ImageMagick/ImageMagick/discussions
- https://github.com/ImageMagick/ImageMagick/issues
- https://github.com/ImageMagick/ImageMagick/wiki

I think that you can add two links in more on SF too:
- https://github.com/ImageMagick
- https://github.com/ImageMagick/ImageMagick

**Comment by urban-warrior** [comment]
Try now.

**Comment by Neustradamus** [comment]
@urban-warrior: Good job!
If all people were like you, the World will be better ^^
