### ISSUE TITLE
Conversion to text with -colorspace RGB produces wrong pixel values

### ISSUE THREAD

**Issue by orlitzky** [ImageMagick/ImageMagick#7017]
### ImageMagick version

7.1.1.11

### Operating system

Linux

### Operating system, version and so on

Gentoo linux

### Description

While working on https://github.com/gap-packages/hap/issues/115, I noticed that imagemagick and graphicsmagick are producing different pixel values from `convert -colorspace RGB`. After narrowing it down to a one-pixel example, it looks like imagemagick is the one producing mysterious deviations.

### Steps to Reproduce

1. Create a single-pixel image whose RGB value is `#e1cbe1`
2. Save it as a bitmap with no colorspace information
3. Run `convert <infile> -colorspace RGB out.txt`
4. `out.txt` contains `0,0: (192,152,192)  #C098C0  rgb(75.2941%,59.7208%,75.2941%)`

(GraphicMagick, on the other hand, produces `0,0: (225,203,225) #E1CBE1`, which is correct.)

**Comment by snibgo** [comment]
It would help if you showed all the commands you used.

Your step 3 converts the image from non-linear sRGB to linear RGB. The output txt values are what I would expect.

If you don't want to change the colorspace to linear RGB, then don't do it.

**Comment by orlitzky** [comment]
The `convert` command is the only command I used. (I created the one-pixel image in GIMP and disabled color management.)

Does ImageMagick parse the `# ImageMagick pixel enumeration: 1,1,0,255,rg` header that gets added to the txt file?

If ImageMagick is parsing the header, that would make more sense. GraphicsMagick doesn't write a header so obviously it cannot. That means that GM must assume that the colorspace of the text file is whatever it assumes the colorspace to be whenever there is no colorspace information; otherwise `convert foo.bmp foo.txt; convert foo.txt foo.bmp` would change the image. ImageMagick, on the other hand, could effectively change the colorspace by writing it into the header, to be parsed later.

Are there any docs on the txt format?

**Comment by fmw42** [comment]
Graphics magick use -colorspace RGB for non-linear sRGB.  Imagemagick uses -colorspace RGB for linear RGB. If you want the same in Imagemagick, use -colorspace sRGB

**Comment by snibgo** [comment]
> (I created the one-pixel image in GIMP and disabled color management.)

In Gimp, when creating an image, Advanced options, you have the option of making it "Linear Light" or "Perceptual gamma (sRGB)". Which did you choose?

> Does ImageMagick parse the # ImageMagick pixel enumeration: 1,1,0,255,rg header that gets added to the txt file?

Yes. We can demonstrate this by writing a `txt:` image, and piping that into another `magick` command:
```
D:\temp>%IMG7%magick xc:#e1cbe1 -colorspace RGB txt:- | %IMG7%magick - txt:
# ImageMagick pixel enumeration: 1,1,0,65535,rgb
0,0: (49344,39138,49344)  #C0C098E2C0C0  rgb(75.2941%,59.7208%,75.2941%)
```
We created the image as sRGB #e1cbe1, then converted it to linear RGB, so the pixel values have changed. The final `txt:` shows the colorspace is RGB.

I don't use GraphicsMagick, and can't comment on it.

**Comment by orlitzky** [comment]
> Graphics magick use -colorspace RGB for non-linear sRGB. Imagemagick uses -colorspace RGB for linear RGB. If you want the same in Imagemagick, use -colorspace sRGB

Oof. All I really want is for the command in https://github.com/gap-packages/hap/issues/115 to not produce different answers by surprise. But yeah, that would make sense if ImageMagick is parsing the header. (If it's not parsing the header, it should assume sRGB in the absense of colorspace information, which would then be wrong.)

**Comment by orlitzky** [comment]
> > (I created the one-pixel image in GIMP and disabled color management.)
> 
> In Gimp, when creating an image, Advanced options, you have the option of making it "Linear Light" or "Perceptual gamma (sRGB)". Which did you choose?

I left it at Perceptual gamma, but have since tried it with linear light, and it makes no difference (I'm exporting as bmp).

> > Does ImageMagick parse the # ImageMagick pixel enumeration: 1,1,0,255,rg header that gets added to the txt file?
> 
> Yes. We can demonstrate this by writing a `txt:` image, and piping that into another `magick` command:

Ok, thank you. This is starting to look like an irreconcilable difference of opinion between the two tools. I'll close the issue as I don't think there's anything to fix. Thanks again.
