### ISSUE TITLE
PNG Grayscale Bug with quantum-depth=8

### ISSUE THREAD

**Issue by warpspin** [ImageMagick/ImageMagick#702]
Hello

If ImageMagick 7 is configured with  --with-quantum-depth=8, reading Grayscale PNG images will fail - images will be mostly white after reading (An example picture where this problem did occur for one of our users: http://www.earthmate.net/d9c0575c%2d5960671.png ), as if the PNG coder still assumes the wrong quantum depth or so.

Compiling with the default quantum depth 16 will read the same images properly.

ImageMagick 6 also properly reads such images with quantum depth 8.

**Comment by dlemstra** [comment]
What is the exact version of ImageMagick and libpng that you are using? And what is the operating system that you are working on?

**Comment by warpspin** [comment]
ImageMagick 7.0.6-10 (ImageMagick-7.0.5-9 was also affected - this was the version where we noticed the problem after upgrading from ImageMagick 6)
Ubuntu 14.04
libpng1.2.5 (Ubuntu package: libpng12-0)

ImageMagick was compiled with:

./configure --with-quantum-depth=8 --without-dps --without-djvu --without-fpx --without-gvc --without-jbig --without-openexr --without-wmf --with-modules --with-windows-font-dir=/usr/share/fonts/truetype/ --with-perl --without-threads

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
