### ISSUE TITLE
ImageMagick.ImageMagick missing from winget 

### ISSUE THREAD

**Issue by sonofmartinus** [ImageMagick/ImageMagick#7029]
### ImageMagick version

7

### Operating system

Windows

### Operating system, version and so on

Windows 11 22H3, Windows Package Manager v1.6.3482

### Description

When searching for ImageMagick in winget there are no results. Looking at the winget pkgs github the manifest was removed by the bot about 2 weeks ago. Any plans to address this? I've searched closed issues and see no mention of this anywhere.

### Steps to Reproduce

winget search ImageMagick.ImageMagick 

This returns no results.

**Comment by urban-warrior** [comment]
We did not write nor do we maintain winget.  You'll need to contact the winget team about this issue.

**Comment by sonofmartinus** [comment]
I understand Winget is not maintained by the ImageMagick team. I may be misunderstanding which team takes care of making sure the windows binaries for ImageMagick are available through winget package manager. That is the reason why I opened the issue on the ImageMagick github, as I understood it, the ImageMagick team is in charge of publishing a manifest for winget?

Some examples:

https://github.com/microsoft/winget-pkgs/tree/master/manifests/i/ImageMagick/ImageMagick

After doing some more digging, it looks like the manifest is not itself published to winget-pkgs repository by the ImageMagick team? 

If so, please close this issue. 

Thanks!
