### ISSUE TITLE
missing delegate error

### ISSUE THREAD

**Issue by simonm3** [ImageMagick/ImageMagick#703]
I have installed on windows using the binary installer. I set the environment MAGICK_HOME to the folder in program files. But I get missing delegate error.

I tried configure - list format and get no formats.

Are there any additional installation instructions?

**Comment by simonm3** [comment]
The answer is that the installer apparently sets the environment variables incorrectly to paths that don't even exist.  

A workaround is to check ALL environment variables point to the correct path. There are 3 in my installation. However would be better to update the installer.

**Comment by dlemstra** [comment]
Which incorrect paths are being used by the installer? Do you have an example so I can understand the issue?

**Comment by simonm3** [comment]
Sorry I overwrote them. But from memory it was something like
xyzview/modules/coders and xyzview/modules/filters.

**Comment by sondretjvimond** [comment]
I also have a a missing delegate error. It happened after upgrade to 6.9.7 from 6.8.9. The exact same command works if I downgrade.

`convert /data/tmp/_1504084252062_14 -crop 402x301+204+118 :|convert -  -resize 960x720^ -background transparent -gravity center -extent 960x720  -quality 95  /data/tmp/_data_tmp__1504084252062_14_o_14
convert: unable to open image `/data/tmp/_1504084252062_14': No such file or directory @ error/blob.c/OpenBlob/2712.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
convert: no images defined `:' @ error/convert.c/ConvertImageCommand/3210.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
convert: no images defined `/data/tmp/_data_tmp__1504084252062_14_o_14' @ error/convert.c/ConvertImageCommand/3210.`

**Comment by simonm3** [comment]
BTW version 6.9.9

It all works fine now all three environment variables are correct.

**Comment by dlemstra** [comment]
Which three environment variables are you talking about? It might be possible that some other application decided to overwrote them.

**Comment by simonm3** [comment]
magick_home, magick_coder_module_path, magick_coder_filter_path

If another application overwrote it would be pyocr.

**Comment by dlemstra** [comment]
@simonm3 My guess is that some other program changed the variables and that this is not an issue with the installer. Can we close this issue?

**Comment by simonm3** [comment]
Sure. Maybe put a note in the docs to suggest people check the three
environment variables if they have an issue.
Seems odd that another program would change these as they are specifically
prefixed with the name of the package and stop it working.
