### ISSUE TITLE
Identifying TGA orientation broken between 7.1.0 and 7.1.1

### ISSUE THREAD

**Issue by weavejester** [ImageMagick/ImageMagick#7035]
### ImageMagick version

7.1.1-26

### Operating system

Linux

### Operating system, version and so on

Ubuntu 23.10

### Description

In version 7.1.0-33 the `magick identify` command correctly determined the orientation of TGA files. In 7.1.1-26 it always responds with `TopLeft`, regardless of the actual orientation. My suspicion is this bug was introduced by 75fbe9a.

(I created the test image by exporting from GIMP, and I verified the orientation bits via a hexdump.)

### Steps to Reproduce

1. Create a TGA file with an orientation that isn't "TopLeft". The attached zip file contains a TGA file with a BottomLeft orientation.
2. Run `magick identify -format "%[orientation]" TCF_centre.tga` to check the orientation.

### Images

[TCF_centre.zip](https://github.com/ImageMagick/ImageMagick/files/13952634/TCF_centre.zip)

**Comment by dlemstra** [comment]
There have been numerous discussions about the TGA orientation and unless you add `-define tga:preserve-orientation` the orientation will always be `TopLeft`.

**Comment by weavejester** [comment]
Aha, the `-define` needs to be before the `-format` for it to work. I did play around with `tga:preserve-orientation` but I couldn't get it to work correctly. I also assumed that option was just for conversion/processing, rather than identifying.

**Comment by dlemstra** [comment]
It's used by both. When you idenify an image you read only the metadata. The rest is skipped but this is part of the metadata.
