### ISSUE TITLE
Imagemagick 6.9.9-10 crashes with iOS Icon png but older and newer versions don't

### ISSUE THREAD

**Issue by jeremybdk** [ImageMagick/ImageMagick#704]
Hello,

We use ImageMagick to process iOS icons (PNGCrush), but it seems that a recent change is making ImageMagick crash.

Here is the issue that I am seeing when using convert for example:

- With 6.9.9-10
`
Assertion failed: (quantum_info != (QuantumInfo *) NULL), function DestroyQuantumInfo, file magick/quantum.c, line 216.`

- With 7.0.6-10
`
convert: CgBI: unhandled critical chunk 'test_icon_default.png' @ error/png.c/MagickPNGErrorHandler/1711.
convert: corrupt image 'test_icon_default.png' @ error/png.c/ReadPNGImage/4274.
convert: no images defined 'test_icon_default_fixed.png' @ error/convert.c/ConvertImageCommand/3275.
`

- With 6.8.9-10
`
convert: CgBI: unhandled critical chunk 'test_icon_default.png' @ error/png.c/MagickPNGErrorHandler/1645.
convert: corrupt image 'test_icon_default.png' @ error/png.c/ReadPNGImage/3973.
convert: no images defined 'test_icon_default_fixed.png' @ error/convert.c/ConvertImageCommand/3210.
`

We used to catch up these errors and use the pngdefry ruby gem to "Defry" the png and use them with ImageMagick but now convert is simply crashing.

I have added an icon that makes ImageMagick 6.9.9-10 crash.

![appicon60x60 3x](https://user-images.githubusercontent.com/1963030/29810744-54fe8a7e-8ca1-11e7-9627-2265bac2662b.png)

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by jeremybdk** [comment]
Thanks a lot for the fix !

**Comment by liuende501** [comment]
is this fix?
