### ISSUE TITLE
Some AVIF images (esp. with smaller dimensions) not working in Safari 16.3

### ISSUE THREAD

**Issue by hyvyys** [ImageMagick/ImageMagick#7062]
### ImageMagick version

7.1.1-26

### Operating system

MacOS

### Operating system, version and so on

macOS 13.2.1 (22D68)

### Description

Safari 16.3 has an issue with displaying `AVIF` images — on Version 16.3 (18614.4.6.1.6) it sometimes won't display the AVIF image leaving an empty space instead — from what I've observed, it happens with images of smaller dimensions especially. The standard way to include an AVIF image on a website is by using an AVIF `source` inside a `picture` tag, but this version of Safari thinks it can support all AVIF images, so a WEBP, JPG, or PNG fallback is not used in the case I'm describing.

Release notes for Safari 16.4 mention this:
> Fixed ensuring the \<picture\> element works with AVIF.
https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes

However, as I mentioned, some (most) AVIF images I get from image-magick work correcly in Safari 16.3, and this article led me to believe there might be an issue with how some images are converted in image-magick:
https://tylergaw.com/blog/ios-16-avif-fix/

I am attaching an image converted by image-magick that does not work in Safari 16.3, and the same image converted with https://squoosh.app/editor that works.

Images: [avif-images-safari-16.3.zip](https://github.com/ImageMagick/ImageMagick/files/14024925/avif-images-safari-16.3.zip)

Note how macOS Finder preview differs with these two images:

![image](https://github.com/ImageMagick/ImageMagick/assets/20814638/4e24a849-cec4-4fb8-8325-2792c0c208e4)
![image](https://github.com/ImageMagick/ImageMagick/assets/20814638/7772f8d1-7bf4-48eb-99bc-f73f44e215e2)

### Steps to Reproduce

Reproduction repo - open in Safari 16.3:

https://plnkr.co/edit/AIwKqXZsIqeCR7xn?open=lib%2Fscript.js

Original PNG image:

![original](https://github.com/ImageMagick/ImageMagick/assets/20814638/207b5de3-364a-4ab7-90cb-0a38ae8eb252)

**Comment by fmw42** [comment]
Your two files open differently in both Safari and Chrome on my Mac OSX Ventura

**Comment by hyvyys** [comment]
I last checked on Monterey, one file worked in Safari and both files worked in Firefox.

On another Mac though, also Monterey, neither image works in Safari Version 16.3 (17614.4.6.11.6, 17614), both work in Firefox and Chrome.

**Comment by fmw42** [comment]
One difference that I see in your two files is that the Imagemagick versions has a GIMP built-in sRGB ICC profile; whereas your other file has no color profile.  I do not know if the is the issue or not.

**Comment by MauScheff** [comment]
Also happens when encoding with sharp on small images (256)
