### ISSUE TITLE
leaking memory when `Magick::Color` throws

### ISSUE THREAD

**Issue by mmomtchev** [ImageMagick/ImageMagick#7066]
### ImageMagick version

7.1.1-26

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04

### Description

The following code leaks memory while leaving `c` equal to `nullptr`

```cpp
#include <Magick++.h>

int main() {
	Magick::Color *c = nullptr;
	try {
		c = new Magick::Color{"invalid"};
	} catch (...) {}
	printf("c = %p\n", c);
}
```

### Steps to Reproduce

Build the above program with a leak detector

**Comment by dlemstra** [comment]
Feel free to create a pull request to fix this.
