### ISSUE TITLE
Possible bug running PANGO

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#7067]
### ImageMagick version

7.1.1.27

### Operating system

MacOS

### Operating system, version and so on

Ventura

### Description

I was running the example at https://imagemagick.org/Usage/text/#pango_markup  and I get an error message.  This may be in pango.  But I thought I would check.  There is one strange factor that may be related.  I install my delegates from MacPorts.  When I check my delegates, I see both Cairo and CairoPango listed.  Is it possible that Imagemagick is getting confused with both installed?

```
magick -background lightblue \
pango:'  Some  <span size="49152" rise="-20480" foreground="red" background="blue"> Big Red on Blue </span>  Text  ' \
pango_span.gif

Assertion failed: (tmp.table_size - hash_table_sizes < ARRAY_LENGTH (hash_table_sizes)), function _cairo_hash_table_manage, file cairo-hash.c, line 286.
Abort trap: 6

```
<br>

Here are my delegates:

```
magick -version
Version: ImageMagick 7.1.1-27 Q16-HDRI aarch64 21931 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps raw rsvg tiff webp x xml zlib zstd
Compiler: gcc (4.2)
```

### Steps to Reproduce

See above

**Comment by urban-warrior** [comment]
That exception comes from the `pango` delegate library rather than ImageMagick.  Try  your `pango` script directly on the CLI bypassing ImageMagick.  You will get the same exception.  If so, try contacting that team for assistance.

If you instead its an issue in ImageMagick, use `gdb` to produce a stack trace and post it here so we can investigate further.

Just an FYI, your command produces expected results, without any complaints, for us on our Linux system.

**Comment by fmw42** [comment]
But do you think there is any conflict between the two versions of Cairo?

**Comment by snibgo** [comment]
coders/svg.c references both Cairo and PangoCairo delegates. But coders/pango.c references only the PangoCairo delegate.

So I can see no possibility of a confusion between those delegates when reading a `pango:` image.
