### ISSUE TITLE
ABI problem with gcc-7 on Debian

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#707]
We've been having trouble building the R bindings on Debian "testing" (Buster). I have arrowed it down to the `std::string()` coercion of the `Magick::Color` class. 

I am unsure if this is a bug in IM or Debian or me. I know that Debian ships a reasonable old version of IM6, but perhaps we can at least point down the issue so that I can properly understand and report it.

Below a minimal example:

```cpp
#include <Magick++.h>
#include <iostream>

int main(){
  Magick::Image image("logo:");
  Magick::Color col(image.fillColor());
  std::string strcol(col);
  std::cout << strcol;
  return 0;
}
```

The program builds fine with g++6 but with g++7 I get a linking error:

```
g++-6 test.cpp $(pkg-config --cflags --libs Magick++)
./a.out
> #000000000000
```

However with gcc 7 we get:

```
g++-7 test.cpp $(pkg-config --cflags --libs Magick++)
/tmp/cchhBIuN.o: In function `main':
test.cpp:(.text+0x7f): undefined reference to `Magick::Color::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >() const'
collect2: error: ld returned 1 exit status
```

**Comment by mikayla-grace** [comment]
We had similar problems with gcc 7 under Fedora.  A recent update to the compiler fixed the problem.  We are compiling with g++ (GCC) 7.1.1 20170622 and your test.cpp source compiles without complaint.

**Comment by jeroen** [comment]
Which commit/patch from this recent update would need to used by Debian to fix this?

**Comment by jeroen** [comment]
Debian is running 7.2:

```
# g++-7 --version
g++-7 (Debian 7.2.0-1) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
```

**Comment by mikayla-grace** [comment]
The patch was just the latest update to GCC 7.1, we did not make any changes to ImageMagick.  We have access to Fedora, Ubuntu, and CentOS and test.cpp works fine on all of these systems.  We do not have access to a Debian system so we're not sure how we can help.  It could very well be a compiler issue.

**Comment by jeroen** [comment]
Hmm I don't see any gcc 7.1.1 release on the GNU website, must have been a Fedora thing or so. I'll have to figure out what exactly they patched.

**Comment by jeroen** [comment]
This may be related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871300
