### ISSUE TITLE
PerlMagick on Windows broken

### ISSUE THREAD

**Issue by stoecker** [ImageMagick/ImageMagick#7077]
### ImageMagick version

7.1.1-27

### Operating system

Windows

### Operating system, version and so on

10 or 11 x86_64

### Description

Installing PerlMagick on Windows fails using (https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-27-Q16-HDRI-x64-dll.exe). The Installer contains a PerlMagick version for Strawberry perl 5.20. Current is 5.38. Please update the installer.

Also installing perl package using cpan (cpan install Image::Magick) fails with:
```
C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\include/MagickCore/magick-baseconfig.h:279:6: error: #error ImageMagick was build with a 64 channel bit mask and that requires a C++ compiler
  279 | #    error ImageMagick was build with a 64 channel bit mask and that requires a C++ compiler
```
which is untrue as commenting this line 279 lets the perl package build, see also
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/139#issuecomment-1756595270

I didn't find these lines or the texts in the sourcecode repo somewhere, so I don't know how they are generated and also not how to provide a patch for it.

So please provide two fixes:
* drop the line preventing proper build
* update the strawberry perl version used to deliver perl package

### Steps to Reproduce

Install and/or Compile as described

**Comment by dlemstra** [comment]
This looks like an issue in your build. When you are using our compiled libraries they are build with a C++ compiler and you will also need to use a C++ compiler when you link them. Uncommenting that line and using a C compiler will result in unexpected behavior.

We are using Strawberry perl 5.3.0 in our installation and we might update that in the future when we need to.

**Comment by stoecker** [comment]
This is not an issue in my build. It's an issue in many peoples build as the referenced ticket shows. My colleague tried lots of ways to get a working PerlMagick version (including old versions of the softwares) on Windows and failed in all of them. Above fix is one which creates anything usable.

Please explain how using a C compiler can result in unexpected behaviour when the linking works. C and C++ use totally different methods to build function names. When the linking works it is unlikely that one part was compiled with a C compiler and the other one with C++. Also why does a 64 bit variable on a 64 bit system need a C++ compiler when it otherwise works with a c compiler. That makes no sense and I as said I was unable to find where this strange check originates to see why it is there at all.

Please explain how you can provide PerlMagick for perl 5.20.0 with the installer (which is now 10 years old) when you use a perl version of 5.3.0 (which must be ancient). That makes no sense. Perl versions are not really ABI compatible when the major version changes.

**Comment by dlemstra** [comment]
The Windows build uses Visual Studio 2022 and this requires a C++ compiler for the 64-bit channel mask because we need a 64-bit enum. This won't work with a C compiler in Visual Studio. That check was added to make sure that anyone who links with our libraries also needs to compile their library with a C++ compiler to avoid possible compatibility issues. So this now also means you will need to build your project with a C++ compiler.

Version `5.3.0` was typo, we are using `5.30.0` in our release build. But it looks like we forgot to update the version number in the our installer template. I will probably remove the version number from the template.
