### ISSUE TITLE
posterize command line option is ignoring dither option

### ISSUE THREAD

**Issue by Packbat** [ImageMagick/ImageMagick#7079]
### ImageMagick version

7.1.1-25

### Operating system

Linux

### Operating system, version and so on

NixOS 23.11.3409.d7f206b723e4 (Tapir)

### Description

According to [the documentation on the `-dither` command line option](https://imagemagick.org/script/command-line-options.php#dither) and [the color quantization examples page](https://www.imagemagick.org/Usage/quantize/#posterize), the `-posterize` option should use the current dither setting when reducing the color space. However, as of right now, it doesn't seem to do any dithering at all.

### Steps to Reproduce

1. Run a command with a `-dither` option and a `-posterize` option - for example: `magick Parrot.red.macaw.1.arp.750pix.jpg -dither FloydSteinberg -posterize 2 Parrot-posterize2-fs.png`

Expected result: A posterized image using the appropriate dither setting.

Observed result: An undithered posterized image.

### Images

Using [Adrian Pingstone's macaw picture](https://commons.wikimedia.org/wiki/File:Parrot.red.macaw.1.arp.750pix.jpg) for demonstration:
![Parrot red macaw 1 arp 750pix](https://github.com/ImageMagick/ImageMagick/assets/11142302/26d11106-9cf1-4322-8cda-5a85098f9033)

`magick Parrot.red.macaw.1.arp.750pix.jpg +dither -posterize 2 Parrot-posterize2-none.png`
![Parrot-posterize2-none](https://github.com/ImageMagick/ImageMagick/assets/11142302/3b93db2b-7d61-4995-bdef-6a756866c41a)

`magick Parrot.red.macaw.1.arp.750pix.jpg -dither FloydSteinberg -posterize 2 Parrot-posterize2-fs.png`
![Parrot-posterize2-fs](https://github.com/ImageMagick/ImageMagick/assets/11142302/895d13a2-3d48-456e-b8d6-ce23df5835cc)

`magick Parrot.red.macaw.1.arp.750pix.jpg -dither FloydSteinberg -remap RGB_3bits_palette_color_test_chart.png Parrot-remap-fs.png`
![Parrot-remap-fs](https://github.com/ImageMagick/ImageMagick/assets/11142302/acc768aa-6f02-4934-b785-5c89d0e2b7c2)

**Comment by urban-warrior** [comment]
Posterize is dithering the image, however, there is not enough error to distribute to easily visualize any artifacts.  Remapping may be the best method to achieve the desired effect.

**Comment by Packbat** [comment]
> Posterize is dithering the image, however, there is not enough error to distribute to easily visualize any artifacts. Remapping may be the best method to achieve the desired effect.

So, the exact line on [the command line options documentation for -dither](https://imagemagick.org/script/command-line-options.php#dither) is "The color reduction operators [-colors](https://imagemagick.org/script/command-line-options.php#colors), [-monochrome](https://imagemagick.org/script/command-line-options.php#monochrome), [-remap](https://imagemagick.org/script/command-line-options.php#remap), and [-posterize](https://imagemagick.org/script/command-line-options.php#posterize), apply dithering to images using the reduced color set they created." This says to me that `-remap RGB_3bits_palette_color_test_chart.png` (which uses [this 8-color image](https://commons.wikimedia.org/wiki/File:RGB_3bits_palette_color_test_chart.png)) and `-posterize 2` (which references the exact same 8 colors) should both produce dithered images with the same 8-color palette, and therefore should produce the same results ... which they do not.

If this is a documentation error, that's fine - there's obviously workarounds - but if it's not, then I imagine something got broken during an update at some point.

**Comment by Packbat** [comment]
I'm very confused by your explanation. If I use `+dither -posterize 2`, I get an image where every pixel is pushed to the nearest of these 8 colors - fair enough. If I use `+dither -remap RGB_3bits_palette_color_test_chart.png`, I, again, get an image where every pixel is pushed to the nearest of these 8 colors - exactly the same image, as I would expect.

If I use `-dither FloydSteinberg -posterize 2`, I once again get an image where every pixel is pushed to the nearest of these 8 colors - *not* an image with error-diffusion dithering.

And I *know* it's not an image with error-diffusion dithering because if I use `-dither FloydSteinberg -remap RGB_3bits_palette_color_test_chart.png`, the image changes - it's dithered, it has the additional color detail you get with dithering.

Same starting image, same specification of dither, same colors in the color map, different image. This isn't what I would expect from the documentation.

Like, [the color quantization examples page](https://www.imagemagick.org/Usage/quantize/#posterize) *has examples with dithering.*

> For example lets posterize the IM logo image at various levels...
> 
> `magick logo.png  +dither -posterize 2  posterize_logo.gif`
> `magick logo.png          -posterize 2  posterize_logo_dither.gif`
> `magick logo.png          -posterize 6  posterize_6_logo.gif`

...and the result on that page with `+dither` set is different than the one with no option set. And if I run those exact commands *right now* on the exact image from that page, `posterize_logo.gif` and `posterize_logo_dither.gif` turn out the same and it's the no-dither version. It doesn't match what the page says should happen.

**Comment by snibgo** [comment]
In a small number of tests, it seems that `+posterize` or `-posterize` makes no difference to `-posterize`. The results from dithering or not dithering are identical.

So I think there is a bug.

In `quantize.c`, function `PosterizeImage()`, I can't see an obvious problem. The parameter `dither_method` is correct.

(A workaround is to posterize, then remap the input image to the posterized result. This is clumsy and should not be necessary.)

**Comment by urban-warrior** [comment]
We can increase the amount of error diffusion by using the default depth instead of a fully expanded color quantization tree as it is now.  It still will not achieve the same diffusion as the remap.

**Comment by Packbat** [comment]
> (A workaround is to posterize, then remap the input image to the posterized result. This is clumsy and should not be necessary.)

For this workaround, I would suggest posterizing an appropriate gradient test image and using that for the remap, rather than relying on your input image to include a sufficient range of colors.

> We can increase the amount of error diffusion by using the default depth instead of a fully expanded color quantization tree as it is now. It still will not achieve the same diffusion as the remap. However, it does a decent job. We'll export the patch soon for testing.

Thank you for looking into it - I'm very interested in how that change affects the output. When I export to .gif, both `+dither -posterize 2` and `-dither FloydSteinberg -posterize 2` produce byte-identical results, which suggests errors are not being diffused at all in the version I have.

**Comment by urban-warrior** [comment]
Test the patch we just added to the main branch.    Let us know if that meets your expectations.

**Comment by snibgo** [comment]
Results from the patch look good to me.

**Comment by Packbat** [comment]
Sorry for the delay - I don't actually know how to build things from source so I had to get help from friends.

Testing on the parrot and logo images again, it looks like the dither part is working now, but it's not picking the right colors. Here's the command and the output:

`magick Parrot.red.macaw.1.arp.750pix.jpg -dither FloydSteinberg -posterize 2 Parrot-posterize2-fs-patched.png`
![Parrot-posterize2-fs-patched](https://github.com/ImageMagick/ImageMagick/assets/11142302/a85da5c7-496a-4c91-b310-9262c1f5ccf9)

and running `identify -verbose`, I see:
```
  Colormap:
    0: (20,18,9,1) #141209FF srgba(20,18,9,1)
    1: (82,69,38,1) #524526FF srgba(82,69,38,1)
    2: (107,140,116,1) #6B8C74FF srgba(107,140,116,1)
    3: (216,93,65,1) #D85D41FF srgba(216,93,65,1)
    4: (236,174,91,1) #ECAE5BFF srgba(236,174,91,1)
    5: (162,23,16,1) #A21710FF srgba(162,23,16,1)
    6: (207,201,190,1) #CFC9BEFF srgba(207,201,190,1)
    7: (218,36,28,1) #DA241CFF srgba(218,36,28,1)
    8: (255,255,255,1) #FFFFFFFF white
```

On a hunch, I ran:

`magick Parrot.red.macaw.1.arp.750pix.jpg -dither FloydSteinberg -colors 8 Parrot-colors8-fs-patch.png`

and these are in fact the eight colors produced with `-colors 8`.

Does that match other folks' observations?

**Comment by urban-warrior** [comment]
The formula for posterize is:

```
(channel)[i] = ((channel)[i] * (levels - 1) / 255) * 255 / (levels - 1);
```

which creates new colors in the image.  If you are looking to only use colors that are in the original image, you will need to use `-remap`.

**Comment by snibgo** [comment]
Yes, the colours are wrong. The patch also makes the wrong number of values in each channel.

Before the patch, when posterizing without dithering, it made these colours:
```
C:\web\im>%IMG7%magick Parrot.red.macaw.1.arp.750pix.jpg +dither -posterize 2 -unique-colors txt:
# ImageMagick pixel enumeration: 8,1,0,255,srgb
0,0: (0,0,0)  #000000  black
1,0: (255,0,0)  #FF0000  red
2,0: (0,255,0)  #00FF00  lime
3,0: (255,255,0)  #FFFF00  yellow
4,0: (0,0,255)  #0000FF  blue
5,0: (255,0,255)  #FF00FF  magenta
6,0: (0,255,255)  #00FFFF  cyan
7,0: (255,255,255)  #FFFFFF  white
```
As expected, each channel has 2 values, and those values are 0% and 100%.

With the patch, each channel has more than 2 values:
```
C:\web\im>%IM7DEV%magick Parrot.red.macaw.1.arp.750pix.jpg +dither -posterize 2 -unique-colors txt:
# ImageMagick pixel enumeration: 8,1,0,255,srgb
0,0: (10,9,5)  #0A0905  srgb(3.8194992%,3.6068857%,2.078099%)
1,0: (39,36,16)  #272410  srgb(15.327063%,14.033964%,6.1909307%)
2,0: (82,69,38)  #524526  srgb(32.330763%,26.957303%,14.771722%)
3,0: (218,36,28)  #DA241C  srgb(85.661399%,14.010079%,11.013429%)
4,0: (197,68,48)  #C54430  srgb(77.240127%,26.613471%,18.747109%)
5,0: (107,140,116)  #6B8C74  srgb(41.804537%,54.789639%,45.500079%)
6,0: (236,174,91)  #ECAE5B  srgb(92.55895%,68.102306%,35.78794%)
7,0: (207,201,190)  #CFC9BE  srgb(81.357312%,78.666645%,74.548018%)
```

**Comment by Packbat** [comment]
> The formula for posterize is:
> 
> ```
> (channel)[i] = ((channel)[i] * (levels - 1) / 255) * 255 / (levels - 1);
> ```

I agree. Those are the colors I would expect. For example, if I do:
```
magick input.png -posterize 2 output.png
magick identify -verbose output.png
```
I should see:
```
  Colormap:
    0: (0,0,0,1) #000000FF black
    1: (0,255,0,1) #00FF00FF lime
    2: (255,255,0,1) #FFFF00FF yellow
    3: (0,0,255,1) #0000FFFF blue
    4: (255,255,255,1) #FFFFFFFF white
    5: (255,0,0,1) #FF0000FF red
    6: (0,255,255,1) #00FFFFFF cyan
    7: (255,0,255,1) #FF00FFFF magenta
```
in the output, regardless of the input image.

Using `ImageMagick 7.1.1-25 Q16-HDRI x86_64 054b98c80:20231230`, that's exactly what I see. 

Using `ImageMagick 7.1.1-28 (Beta) Q16-HDRI x86_64 0225ac41a:20240121`, I don't. I see an image-specific colormap, specifically the same one that `-colors 8` will generate.

**Comment by snibgo** [comment]
> Also, I didn't know about that trick for getting the color palette!

Strictly speaking, that trick gives only the colours that are in the result image. The palette may contain more colours.

But that is an aside. I agree, the patch gives unexpected results. In fact, the results have the same colours as `-colors 8` gives:
```
C:\web\im>%IM7DEV%magick Parrot.red.macaw.1.arp.750pix.jpg +dither -colors 8 -unique-colors txt:
# ImageMagick pixel enumeration: 8,1,0,255,srgb
0,0: (10,9,5)  #0A0905  srgb(3.8194992%,3.6068857%,2.078099%)
1,0: (39,36,16)  #272410  srgb(15.327063%,14.033964%,6.1909307%)
2,0: (82,69,38)  #524526  srgb(32.330763%,26.957303%,14.771722%)
3,0: (218,36,28)  #DA241C  srgb(85.661399%,14.010079%,11.013429%)
4,0: (197,68,48)  #C54430  srgb(77.240127%,26.613471%,18.747109%)
5,0: (107,140,116)  #6B8C74  srgb(41.804537%,54.789639%,45.500079%)
6,0: (236,174,91)  #ECAE5B  srgb(92.55895%,68.102306%,35.78794%)
7,0: (207,201,190)  #CFC9BE  srgb(81.357312%,78.666645%,74.548018%)
```

**Comment by urban-warrior** [comment]
Our posterize macros divided by the # of levels, rather than (levels-1).  Download load the latest Github main and see if any issues remain.

**Comment by Packbat** [comment]
```
magick Parrot.red.macaw.1.arp.750pix.jpg -dither FloydSteinberg -posterize 2 -unique-colors txt:
# ImageMagick pixel enumeration: 8,1,0,255,srgb
0,0: (20,18,9)  #141209  srgb(7.70761%,7.12992%,3.46772%)
1,0: (82,69,38)  #524526  srgb(32.3308%,26.9573%,14.7717%)
2,0: (162,23,16)  #A21710  srgb(63.718%,9.16464%,6.40632%)
3,0: (218,36,28)  #DA241C  srgb(85.6614%,14.0101%,11.0134%)
4,0: (216,93,65)  #D85D41  srgb(84.7768%,36.3387%,25.6253%)
5,0: (107,140,116)  #6B8C74  srgb(41.8045%,54.7896%,45.5001%)
6,0: (236,174,91)  #ECAE5B  srgb(92.559%,68.1023%,35.7879%)
7,0: (207,201,190)  #CFC9BE  srgb(81.3573%,78.6666%,74.548%)
```
It looks like the colors might have changed but they still aren't the right ones.

**Comment by urban-warrior** [comment]
What are the "right colors?"  We are at diminishing returns in terms of tweaking the existing posterize algorithm.  If its not producing expected results, propose a different posterize macro that we should try.

**Comment by snibgo** [comment]
The pool of colours from which pixels can be coloured should be independent of the input image. for `-posterize N`, each channel of the pool colours can take N values. For N=2, those values are 0 and 100% of QuantumRange. For N=3, the values are 0, 50% and 100%. For N=4, the values are 0, 33.3%, 66.7% and 100%. And so on.

The pool will contain N^3 colours, for every combination of N values in 3 channels. The output image will contain up to N^3 colours, because it may not need all of the pool colours.

When there is no dithering, each output pixel should be the closest colour from the pool.

When there is dithering, the error is diffused to nearby pixels.

I can look at this, and propose code to do the above, with or without dithering. But I am too busy to start today.

**Comment by Packbat** [comment]
Thank you also for putting all this time in, @snibgo!

If this bug does turn out to be impossible or infeasible to fix, I would suggest reverting the `-posterize` behavior to that in https://github.com/ImageMagick/ImageMagick/commit/ce9b069cc1ad9748e91b9d37be54cfbb6a714ac5 - I think getting the posterized colors right is more important than getting the dither right.

**Comment by snibgo** [comment]
The patch below fixes the pool of colours used by `-posterize` to what it used to be. It also enables dithering with `-posterize`.

It posterizes all active channels, which by default includes alpha. If any channel (including alpha) has only values that are 0 or 100%, then posterizing has no effect on that channel.

In ImageMagick, dithering is on by default, with the Riemersma method. If we don't want `-posterize` to dither, we should precede it with `+dither`.

When dithering, the code creates an extra image size Mx1 pixels, where M=L^C where L is the requested number of levels and P is the number of active channels. The code remaps the input to this extra image, which it then destroys.

Posterizing with dither in a non-linear colorspace such as sRGB hardly changes the mean, but significantly lightens the image subjectively.
```
magick toes.png -dither FloydSteinberg -posterize 2 f0.png
```

One fix to the subjective lightening is to convert the image to linear RGB, then posterize, then convert back to sRGB:
```
magick toes.png -dither FloydSteinberg -colorspace RGB -posterize 2 -colorspace sRGB f2.png
```
A different fix is to do the quantizing in linear RGB space:
```
magick toes.png -dither FloydSteinberg -quantize RGB -posterize 2 f3.png
```

The patch is:
```
--- quantize20240202.c	2024-02-01 17:10:54.765729500 +0000
+++ quantize.c	2024-02-03 17:25:14.399305100 +0000
@@ -2855,8 +2855,12 @@
   const DitherMethod dither_method,ExceptionInfo *exception)
 {
 #define PosterizeImageTag  "Posterize/Image"
-#define PosterizePixel(pixel) ClampToQuantum(((MagickRealType) \
-  QuantumScale*(pixel)*levels)*((MagickRealType) QuantumRange/levels))
+#define PosterizePixel(pixel) \
+  ClampToQuantum( (MagickRealType) \
+                    QuantumRange \
+                    * ( MagickRound (QuantumScale*(MagickRealType) pixel*(levels-1))) \
+                    / MagickMax((ssize_t) levels-1,1) \
+                )
 
   CacheView
     *image_view;
@@ -2867,9 +2871,6 @@
   MagickOffsetType
     progress;
 
-  QuantizeInfo
-    *quantize_info;
-
   ssize_t
     i,
     y;
@@ -2880,94 +2881,173 @@
   assert(exception->signature == MagickCoreSignature);
   if (IsEventLogging() != MagickFalse)
     (void) LogMagickEvent(TraceEvent,GetMagickModule(),"%s",image->filename);
-  if (image->storage_class == PseudoClass)
-#if defined(MAGICKCORE_OPENMP_SUPPORT)
-    #pragma omp parallel for schedule(static) shared(progress,status) \
-      magick_number_threads(image,image,image->colors,1)
-#endif
-    for (i=0; i < (ssize_t) image->colors; i++)
+
+  if (dither_method != NoDitherMethod && levels > 1) {
+    Image 
+      *map_image;
+
+    ssize_t
+      i;
+
+    size_t
+      channels;
+
+    channels=0;
+    for (i=0; i < (ssize_t) GetPixelChannels(image); i++)
     {
-      /*
-        Posterize colormap.
-      */
-      if ((GetPixelRedTraits(image) & UpdatePixelTrait) != 0)
-        image->colormap[i].red=(double)
-          PosterizePixel(image->colormap[i].red);
-      if ((GetPixelGreenTraits(image) & UpdatePixelTrait) != 0)
-        image->colormap[i].green=(double)
-          PosterizePixel(image->colormap[i].green);
-      if ((GetPixelBlueTraits(image) & UpdatePixelTrait) != 0)
-        image->colormap[i].blue=(double)
-          PosterizePixel(image->colormap[i].blue);
-      if ((GetPixelAlphaTraits(image) & UpdatePixelTrait) != 0)
-        image->colormap[i].alpha=(double)
-          PosterizePixel(image->colormap[i].alpha);
+      PixelChannel channel = GetPixelChannelChannel(image,i);
+      PixelTrait traits = GetPixelChannelTraits(image,channel);
+      if ((traits & UpdatePixelTrait) != 0)
+        channels++;
     }
-  /*
-    Posterize image.
-  */
-  status=MagickTrue;
-  progress=0;
-  image_view=AcquireAuthenticCacheView(image,exception);
-#if defined(MAGICKCORE_OPENMP_SUPPORT)
-  #pragma omp parallel for schedule(static) shared(progress,status) \
-    magick_number_threads(image,image,image->rows,1)
-#endif
-  for (y=0; y < (ssize_t) image->rows; y++)
-  {
-    Quantum
-      *magick_restrict q;
 
-    ssize_t
-      x;
+    size_t numPoolCols = pow (levels, channels);
 
-    if (status == MagickFalse)
-      continue;
-    q=GetCacheViewAuthenticPixels(image_view,0,y,image->columns,1,exception);
-    if (q == (Quantum *) NULL)
-      {
-        status=MagickFalse;
-        continue;
+    map_image = CloneImage(image, numPoolCols, 1, MagickTrue, exception);
+    if (map_image == (Image *) NULL)
+      return MagickFalse;
+
+    if (SetImageStorageClass (map_image, DirectClass, exception) == MagickFalse)
+      return MagickFalse;
+
+    { /* Populate the map image */
+      size_t
+        x, c;
+
+      CacheView
+        *map_image_view;
+
+      Quantum
+        *magick_restrict q;
+
+      map_image_view=AcquireAuthenticCacheView (map_image,exception);
+
+      q = GetCacheViewAuthenticPixels (map_image_view,0,0,numPoolCols,1,exception);
+      if (q == (const Quantum *) NULL)
+        return MagickFalse;
+
+      for (x=0; x < numPoolCols; x++) {
+        size_t rem = x;
+        for (c=0; c < (ssize_t) GetPixelChannels(image); c++) {
+          PixelChannel channel = GetPixelChannelChannel (image, c);
+          PixelTrait traits = GetPixelChannelTraits (image, channel);
+          if ((traits & UpdatePixelTrait) != 0) {
+            size_t val = rem % levels;
+            SetPixelChannel (map_image, channel, val * QuantumRange/(levels-1), q);
+            rem  = (rem - val) / levels;
+          }
+        }
+        q += GetPixelChannels (map_image);
       }
-    for (x=0; x < (ssize_t) image->columns; x++)
-    {
-      if ((GetPixelRedTraits(image) & UpdatePixelTrait) != 0)
-        SetPixelRed(image,PosterizePixel(GetPixelRed(image,q)),q);
-      if ((GetPixelGreenTraits(image) & UpdatePixelTrait) != 0)
-        SetPixelGreen(image,PosterizePixel(GetPixelGreen(image,q)),q);
-      if ((GetPixelBlueTraits(image) & UpdatePixelTrait) != 0)
-        SetPixelBlue(image,PosterizePixel(GetPixelBlue(image,q)),q);
-      if (((GetPixelBlackTraits(image) & UpdatePixelTrait) != 0) &&
-          (image->colorspace == CMYKColorspace))
-        SetPixelBlack(image,PosterizePixel(GetPixelBlack(image,q)),q);
-      if (((GetPixelAlphaTraits(image) & UpdatePixelTrait) != 0) &&
-          (image->alpha_trait != UndefinedPixelTrait))
-        SetPixelAlpha(image,PosterizePixel(GetPixelAlpha(image,q)),q);
-      q+=GetPixelChannels(image);
+      if (SyncCacheViewAuthenticPixels (map_image_view,exception) == MagickFalse)
+        return MagickFalse;
+      map_image_view = DestroyCacheView (map_image_view);
+    }
+
+    { /* Remap to the map_image. */
+      ImageInfo *ii = AcquireImageInfo ();
+      QuantizeInfo *quantize_info = AcquireQuantizeInfo (ii);
+      quantize_info->dither_method = dither_method;
+      (void) RemapImage (quantize_info, image, map_image, exception);
+      quantize_info=DestroyQuantizeInfo(quantize_info);
     }
-    if (SyncCacheViewAuthenticPixels(image_view,exception) == MagickFalse)
-      status=MagickFalse;
-    if (image->progress_monitor != (MagickProgressMonitor) NULL)
+    map_image = DestroyImage (map_image);
+
+  } else {
+    /* No dither. */
+
+    if (image->storage_class == PseudoClass)
+#if defined(MAGICKCORE_OPENMP_SUPPORT)
+      #pragma omp parallel for schedule(static) shared(progress,status) \
+        magick_number_threads(image,image,image->colors,1)
+#endif
+      for (i=0; i < (ssize_t) image->colors; i++)
       {
-        MagickBooleanType
-          proceed;
+        /*
+          Posterize colormap.
+        */
+        if ((GetPixelRedTraits(image) & UpdatePixelTrait) != 0)
+          image->colormap[i].red=(double)
+            PosterizePixel(image->colormap[i].red);
+        if ((GetPixelGreenTraits(image) & UpdatePixelTrait) != 0)
+          image->colormap[i].green=(double)
+            PosterizePixel(image->colormap[i].green);
+        if ((GetPixelBlueTraits(image) & UpdatePixelTrait) != 0)
+          image->colormap[i].blue=(double)
+            PosterizePixel(image->colormap[i].blue);
+        if ((GetPixelAlphaTraits(image) & UpdatePixelTrait) != 0)
+          image->colormap[i].alpha=(double)
+            PosterizePixel(image->colormap[i].alpha);
+      }
 
+    /*
+      Posterize image.
+    */
+    status=MagickTrue;
+    progress=0;
+    image_view=AcquireAuthenticCacheView(image,exception);
 #if defined(MAGICKCORE_OPENMP_SUPPORT)
-        #pragma omp atomic
+    #pragma omp parallel for schedule(static) shared(progress,status) \
+      magick_number_threads(image,image,image->rows,1)
 #endif
-        progress++;
-        proceed=SetImageProgress(image,PosterizeImageTag,progress,image->rows);
-        if (proceed == MagickFalse)
+    for (y=0; y < (ssize_t) image->rows; y++)
+    {
+      Quantum
+        *magick_restrict q;
+
+      ssize_t
+        x;
+
+      if (status == MagickFalse)
+        continue;
+      q=GetCacheViewAuthenticPixels(image_view,0,y,image->columns,1,exception);
+      if (q == (Quantum *) NULL)
+        {
           status=MagickFalse;
+          continue;
+        }
+      for (x=0; x < (ssize_t) image->columns; x++)
+      {
+        if ((GetPixelRedTraits(image) & UpdatePixelTrait) != 0)
+          SetPixelRed(image,PosterizePixel(GetPixelRed(image,q)),q);
+        if ((GetPixelGreenTraits(image) & UpdatePixelTrait) != 0)
+          SetPixelGreen(image,PosterizePixel(GetPixelGreen(image,q)),q);
+        if ((GetPixelBlueTraits(image) & UpdatePixelTrait) != 0)
+          SetPixelBlue(image,PosterizePixel(GetPixelBlue(image,q)),q);
+        if (((GetPixelBlackTraits(image) & UpdatePixelTrait) != 0) &&
+            (image->colorspace == CMYKColorspace))
+          SetPixelBlack(image,PosterizePixel(GetPixelBlack(image,q)),q);
+        if (((GetPixelAlphaTraits(image) & UpdatePixelTrait) != 0) &&
+            (image->alpha_trait != UndefinedPixelTrait))
+          SetPixelAlpha(image,PosterizePixel(GetPixelAlpha(image,q)),q);
+        q+=GetPixelChannels(image);
       }
+      if (SyncCacheViewAuthenticPixels(image_view,exception) == MagickFalse)
+        status=MagickFalse;
+      if (image->progress_monitor != (MagickProgressMonitor) NULL)
+        {
+          MagickBooleanType
+            proceed;
+
+#if defined(MAGICKCORE_OPENMP_SUPPORT)
+          #pragma omp atomic
+#endif
+          progress++;
+          proceed=SetImageProgress(image,PosterizeImageTag,progress,image->rows);
+          if (proceed == MagickFalse)
+            status=MagickFalse;
+        }
+    }
+    image_view=DestroyCacheView(image_view);
+    {
+      QuantizeInfo *quantize_info=AcquireQuantizeInfo((ImageInfo *) NULL);
+      quantize_info->number_colors=(size_t) MagickMin(levels*levels*levels,
+        MaxColormapSize);
+      quantize_info->dither_method=dither_method;
+      status=QuantizeImage(quantize_info,image,exception);
+      quantize_info=DestroyQuantizeInfo(quantize_info);
+    }
   }
-  image_view=DestroyCacheView(image_view);
-  quantize_info=AcquireQuantizeInfo((ImageInfo *) NULL);
-  quantize_info->number_colors=(size_t) MagickMin(levels*levels*levels,
-    MaxColormapSize);
-  quantize_info->dither_method=dither_method;
-  status=QuantizeImage(quantize_info,image,exception);
-  quantize_info=DestroyQuantizeInfo(quantize_info);
   return(status);
 }
 
```

**Comment by urban-warrior** [comment]
Your patch won't work against the main branch as we changed the posterize macro to an inline method.  Can you post a patch against the lastest `quantize.c` or post your PosterizeImage() source module?  Thanks.

**Comment by snibgo** [comment]
The new PosterizeImage() function is:
```
MagickExport MagickBooleanType PosterizeImage(Image *image,const size_t levels,
  const DitherMethod dither_method,ExceptionInfo *exception)
{
#define PosterizeImageTag  "Posterize/Image"
#define PosterizePixel(pixel) \
  ClampToQuantum( (MagickRealType) \
                    QuantumRange \
                    * ( MagickRound (QuantumScale*(MagickRealType) pixel*(levels-1))) \
                    / MagickMax((ssize_t) levels-1,1) \
                )

  CacheView
    *image_view;

  MagickBooleanType
    status;

  MagickOffsetType
    progress;

  ssize_t
    i,
    y;

  assert(image != (Image *) NULL);
  assert(image->signature == MagickCoreSignature);
  assert(exception != (ExceptionInfo *) NULL);
  assert(exception->signature == MagickCoreSignature);
  if (IsEventLogging() != MagickFalse)
    (void) LogMagickEvent(TraceEvent,GetMagickModule(),"%s",image->filename);

  if (dither_method != NoDitherMethod && levels > 1) {
    Image 
      *map_image;

    ssize_t
      i;

    size_t
      channels;

    channels=0;
    for (i=0; i < (ssize_t) GetPixelChannels(image); i++)
    {
      PixelChannel channel = GetPixelChannelChannel(image,i);
      PixelTrait traits = GetPixelChannelTraits(image,channel);
      if ((traits & UpdatePixelTrait) != 0)
        channels++;
    }

    size_t numPoolCols = pow (levels, channels);

    map_image = CloneImage(image, numPoolCols, 1, MagickTrue, exception);
    if (map_image == (Image *) NULL)
      return MagickFalse;

    if (SetImageStorageClass (map_image, DirectClass, exception) == MagickFalse)
      return MagickFalse;

    { /* Populate the map image */
      size_t
        x, c;

      CacheView
        *map_image_view;

      Quantum
        *magick_restrict q;

      MagickRealType
        valmult = QuantumRange / (levels - 1.0);

      map_image_view=AcquireAuthenticCacheView (map_image,exception);

      q = GetCacheViewAuthenticPixels (map_image_view,0,0,numPoolCols,1,exception);
      if (q == (const Quantum *) NULL)
        return MagickFalse;

      for (x=0; x < numPoolCols; x++) {
        size_t rem = x;
        for (c=0; c < (ssize_t) GetPixelChannels(image); c++) {
          PixelChannel channel = GetPixelChannelChannel (image, c);
          PixelTrait traits = GetPixelChannelTraits (image, channel);
          if ((traits & UpdatePixelTrait) != 0) {
            size_t val = rem % levels;
            SetPixelChannel (map_image, channel, val * valmult, q);
            rem  = (rem - val) / levels;
          }
        }
        q += GetPixelChannels (map_image);
      }
      if (SyncCacheViewAuthenticPixels (map_image_view,exception) == MagickFalse)
        return MagickFalse;
      map_image_view = DestroyCacheView (map_image_view);
    }

    { /* Remap to the map_image. */
      ImageInfo *ii = AcquireImageInfo ();
      QuantizeInfo *quantize_info = AcquireQuantizeInfo (ii);
      quantize_info->dither_method = dither_method;
      (void) RemapImage (quantize_info, image, map_image, exception);
      quantize_info=DestroyQuantizeInfo(quantize_info);
    }
    map_image = DestroyImage (map_image);

  } else {
    /* No dither. */

    if (image->storage_class == PseudoClass)
#if defined(MAGICKCORE_OPENMP_SUPPORT)
      #pragma omp parallel for schedule(static) shared(progress,status) \
        magick_number_threads(image,image,image->colors,1)
#endif
      for (i=0; i < (ssize_t) image->colors; i++)
      {
        /*
          Posterize colormap.
        */
        if ((GetPixelRedTraits(image) & UpdatePixelTrait) != 0)
          image->colormap[i].red=(double)
            PosterizePixel(image->colormap[i].red);
        if ((GetPixelGreenTraits(image) & UpdatePixelTrait) != 0)
          image->colormap[i].green=(double)
            PosterizePixel(image->colormap[i].green);
        if ((GetPixelBlueTraits(image) & UpdatePixelTrait) != 0)
          image->colormap[i].blue=(double)
            PosterizePixel(image->colormap[i].blue);
        if ((GetPixelAlphaTraits(image) & UpdatePixelTrait) != 0)
          image->colormap[i].alpha=(double)
            PosterizePixel(image->colormap[i].alpha);
      }

    /*
      Posterize image.
    */
    status=MagickTrue;
    progress=0;
    image_view=AcquireAuthenticCacheView(image,exception);
#if defined(MAGICKCORE_OPENMP_SUPPORT)
    #pragma omp parallel for schedule(static) shared(progress,status) \
      magick_number_threads(image,image,image->rows,1)
#endif
    for (y=0; y < (ssize_t) image->rows; y++)
    {
      Quantum
        *magick_restrict q;

      ssize_t
        x;

      if (status == MagickFalse)
        continue;
      q=GetCacheViewAuthenticPixels(image_view,0,y,image->columns,1,exception);
      if (q == (Quantum *) NULL)
        {
          status=MagickFalse;
          continue;
        }
      for (x=0; x < (ssize_t) image->columns; x++)
      {
        if ((GetPixelRedTraits(image) & UpdatePixelTrait) != 0)
          SetPixelRed(image,PosterizePixel(GetPixelRed(image,q)),q);
        if ((GetPixelGreenTraits(image) & UpdatePixelTrait) != 0)
          SetPixelGreen(image,PosterizePixel(GetPixelGreen(image,q)),q);
        if ((GetPixelBlueTraits(image) & UpdatePixelTrait) != 0)
          SetPixelBlue(image,PosterizePixel(GetPixelBlue(image,q)),q);
        if (((GetPixelBlackTraits(image) & UpdatePixelTrait) != 0) &&
            (image->colorspace == CMYKColorspace))
          SetPixelBlack(image,PosterizePixel(GetPixelBlack(image,q)),q);
        if (((GetPixelAlphaTraits(image) & UpdatePixelTrait) != 0) &&
            (image->alpha_trait != UndefinedPixelTrait))
          SetPixelAlpha(image,PosterizePixel(GetPixelAlpha(image,q)),q);
        q+=GetPixelChannels(image);
      }
      if (SyncCacheViewAuthenticPixels(image_view,exception) == MagickFalse)
        status=MagickFalse;
      if (image->progress_monitor != (MagickProgressMonitor) NULL)
        {
          MagickBooleanType
            proceed;

#if defined(MAGICKCORE_OPENMP_SUPPORT)
          #pragma omp atomic
#endif
          progress++;
          proceed=SetImageProgress(image,PosterizeImageTag,progress,image->rows);
          if (proceed == MagickFalse)
            status=MagickFalse;
        }
    }
    image_view=DestroyCacheView(image_view);
    {
      QuantizeInfo *quantize_info=AcquireQuantizeInfo((ImageInfo *) NULL);
      quantize_info->number_colors=(size_t) MagickMin(levels*levels*levels,
        MaxColormapSize);
      quantize_info->dither_method=dither_method;
      status=QuantizeImage(quantize_info,image,exception);
      quantize_info=DestroyQuantizeInfo(quantize_info);
    }
  }
  return(status);
}
```

**Comment by urban-warrior** [comment]
Thanks @snibgo for the updated posterize algorithm.  We added it to Github main with a minor mod to replace the PosterizePixel() macro with the preferred inline method to promote type checking.

**Comment by Packbat** [comment]
Seconding that - thanks, @snibgo ! I just tested the new commit on my machine and it seems to be working perfectly; I think we can close the bug.

**Comment by snibgo** [comment]
Good stuff. Thanks for testing it. If you find any problems, please report them here.
