### ISSUE TITLE
HEIC images not recognized by static magick command, despite having the heic delegate built-in

### ISSUE THREAD

**Issue by mholt** [ImageMagick/ImageMagick#7094]
### ImageMagick version

7.1.1-26 and 7.1.1-27

### Operating system

Linux

### Operating system, version and so on

Arch

### Description

I have a locally-installed copy of ImageMagick that runs this command successfully:

```
$ magick convert -format jpg -resize 720 -quality 35 IMG_0002.HEIC IMG_0002.JPG
```

However, when I download the [latest static build from the Download page](), and verify it is static and does have HEIC support, I get an error with the same command using the static binary:

```
$ ./magick convert -format jpg -resize 720 -quality 35 IMG_0002.HEIC IMG_0002.JPG
convert: Unsupported feature: Unsupported codec (4.3000) `IMG_0002.HEIC' @ error/heic.c/IsHEIFSuccess/138.
convert: no images defined `IMG_0002.JPG' @ error/convert.c/ConvertImageCommand/3362.
```

Some more info about the two builds (notice the difference is the use of `./` for the static build):

```
$ magick -list format | grep HEIC
     AVIF  HEIC      rw+   AV1 Image File Format (1.17.6)
     HEIC  HEIC      rw+   High Efficiency Image Format (1.17.6)
     HEIF  HEIC      rw+   High Efficiency Image Format (1.17.6)

$ ./magick -list format | grep HEIC
     HEIC  r--   High Efficiency Image Format (1.17.6)

$ magick -version
Version: ImageMagick 7.1.1-26 Q16-HDRI x86_64 21914 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff webp wmf x xml zip zlib zstd
Compiler: gcc (13.2)

$ ./magick -version
Version: ImageMagick 7.1.1-27 Q16-HDRI x86_64 9c64c662f:20240120 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib djvu fontconfig freetype heic jbig jng jp2 jpeg lcms lqr lzma openexr png raqm tiff webp x xml zlib
Compiler: gcc (9.4)
```

How come my HEIC image can't be decoded by the static build, and what can I do to make it work? Thanks!

### Steps to Reproduce

(Given above)

**Comment by fmw42** [comment]
This likely won't help, but on Imagemagick 7 use magick, not magick convert.

**Comment by mholt** [comment]
That's a much more elegant CLI. Thanks for the tip! (I'm new to this utility, so I appreciate it.)

```
$ ./magick IMG_0002.HEIC -resize 720 -quality 35 IMG_0002.JPG
magick: Unsupported feature: Unsupported codec (4.3000) `IMG_0002.HEIC' @ error/heic.c/IsHEIFSuccess/138.
```

Unfortunately the error remains :(

I noticed that the `./magick -list format` command shows:

```
     AVIF  ---   AV1 Image File Format (1.17.6)
```

which seems odd. The mode is `---`, so it's included but not able to read or write the format? Could that be the problem?

**Comment by fmw42** [comment]
Install libavif.  I have 

AVIF  HEIC      rw+   AV1 Image File Format (1.17.6)

on my Mac.  

(I load my delegates from MacPorts and then install IM from source.)

**Comment by mholt** [comment]
Another great tip -- thanks. However, I already have it installed:

```
$ sudo pacman -S libavif
warning: libavif-1.0.3-1 is up to date -- reinstalling
...
```

And, I don't think it would help in this case, as the statically-linked build from the ImageMagick website is the one that gives the error. My distro's PATH-installed `magick` command (dynamically linked) works fine :+1:

**Comment by fmw42** [comment]
If magick -list format for AVIF show -- rather than rw, then it is not installed properly or where Imagemagick can find it.

**Comment by mholt** [comment]
Thank you! Does that apply to static binaries too, though? I was under the impression that the static binary has everything it needs contained in it, so it wouldn't be looking externally for libraries.

It's strange that the static build downloaded from this site can't find it but the one installed on my system can.

**Comment by fmw42** [comment]
I don't know that much about the software builds. Sorry. An Imagemagick developer will need to respond.

**Comment by urban-warrior** [comment]
You have two versions of ImageMagick that link to two different instances of `libheif`, version 1.17.6.  However, one instance of `libheif` includes support for the 4.3000 codec, the other does not.  The solution is to build ImageMagick from source or wait until a static release of ImageMagick links to a robust instance of `libheif`.
