### ISSUE TITLE
The SVG converter uses incorrect default value for `stroke` attributes

### ISSUE THREAD

**Issue by mmomtchev** [ImageMagick/ImageMagick#7097]
### ImageMagick version

7.1.1-27

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04

### Description

The rendering of the following SVG is incorrect:
```html
<svg viewBox="0,0,200,200" width="200" height="200">
  <g fill="#2A5784">
    <rect x="50" y="50" width="100" height="100" />
  </g>
</svg>
```

In the absence of an explicit setting for `stroke`, ImageMagick assumes `stroke="black" stroke-width="1"`, it should be `stroke="none"`

### Steps to Reproduce

Convert the SVG to a PNG and compare it to an SVG rendered by a browser or an image viewer. ImageMagick produces a border.
If `stroke="none"` is added to the `<g>` element, both images will be absolutely identical.

### Images

```html
<svg viewBox="0,0,200,200" width="200" height="200">
  <g fill="#2A5784">
    <rect x="50" y="50" width="100" height="100" />
  </g>
</svg>
```

**Comment by mmomtchev** [comment]
This is without RSVG

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
