### ISSUE TITLE
Encoding to AVIF generate image that are opened as Raw in photoshop

### ISSUE THREAD

**Issue by neckaros** [ImageMagick/ImageMagick#7099]
### ImageMagick version

ImageMagick 7.1.1-27 Q8 x64 0225ac4:20240121

### Operating system

Windows

### Operating system, version and so on

11

### Description

AVIF generated by ImageMagick are opened as raw in photoshop. I can't identify why as i don't see any difference with the identify -verbose

File converted with another tool or WebP does not exhibitit the same issue

### Steps to Reproduce

Convert this image to avif:
![sample](https://github.com/ImageMagick/ImageMagick/assets/7789770/883109ff-3244-465f-972d-b6a9f4415d50)
magick sample.jpg sample2.avif
Open it in photoshop: it will open camera raw before opening the image.
Convert the image with another service like https://convertio.co/fr/jpg-avif/
Open in photoshop: it opens derectly

### Images

![sample](https://github.com/ImageMagick/ImageMagick/assets/7789770/0bbda032-24c4-40f5-bf15-9ed4e8970986)

**Comment by fmw42** [comment]
When I do this on my Mac OSX Ventura with IM 7.1.1.28, I get two files, a JPG file and also an XMP file.  When drop the JPG on Photoshop, it opens in Camera Raw window.
