### ISSUE TITLE
Issue with write/read base64 via variable

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#7102]
### ImageMagick version

7.1.1.28

### Operating system

MacOS

### Operating system, version and so on

Ventura

### Description

The following no longer works and did not work in the previous IM version also. I am not sure in how many release it has been broken.  It used to work many releases ago.

![noseguy](https://github.com/ImageMagick/ImageMagick/assets/13458218/023ed67f-5dd3-4fa7-9cf3-56ddae9b5412)

```
img64=$(magick noseguy.gif inline:png:-)
magick inline:$img64 noseguy_b64.png
```

The variable is empty and the read then hangs with no messages

### Steps to Reproduce

see above

### Images

see above

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Comment by fmw42** [comment]
This now works for me in IM 7.1.1-29.

**Comment by fmw42** [comment]
These commands do not seem to be working again in IM 7.1.1.30 Mac OSX Ventura.

A file png/- is created with the variable string. But echo $img64 shows and empty or blank variable. And the second command hangs.

**Comment by urban-warrior** [comment]
Does this command work for you?

```
magick noseguy.gif inline:png:- | magick inline:- noseguy_b64.png
```

**Comment by fmw42** [comment]
> Does this command work for you?
> 
> magick noseguy.gif inline:png:- | magick inline:- noseguy_b64.png

Yes that works for me.

**But the following fails with an empty string**

```
img64=$(magick noseguy.gif inline:png:-)
echo $im64
```

**Comment by urban-warrior** [comment]
We don't support shell script issues.  However, this command returned expected results:

```
img64=$(magick noseguy.gif inline:png:-)
magick inline:$img64 noseguy_b64.png
```

**Comment by fmw42** [comment]
> However, this command returned expected results:
> 
> img64=$(magick noseguy.gif inline:png:-)
> magick inline:$img64 noseguy_b64.png

Very strange if you have done nothing to fix it.  That was my original complaint that it did not work. Now it seems to be working again.
