### ISSUE TITLE
Support more UTF-8 symbols by default with Label creation

### ISSUE THREAD

**Issue by gwpl** [ImageMagick/ImageMagick#711]
Hello, I've followed: [Label - Simple Text Label], which is great feature allowing to make text labels with imagemagick from commandline.

However, I find that by default, only some UTF-8 symbols are rendered, e.g. for `'label:⌁ Electricity\n🔌 Chargers\n🔋 Powerbanks` :

```
convert -background white -fill black \
 -density 600x600 -size 1346x756 -font DejaVu-Sans -gravity center \
 'label:⌁ Electricity\n🔌 Chargers\n🔋 Powerbanks' \
 out.pdf # or out.png
```
I get:
![utf-8vsimagemagick](https://user-images.githubusercontent.com/221403/29917577-ae0ba3a2-8e42-11e7-8aaf-965469a285f8.png)

References:

* I also brought this up here: https://unix.stackexchange.com/q/389035/9689

[Label - Simple Text Label]: http://www.imagemagick.org/Usage/text/#label

**Comment by dlemstra** [comment]
Did you check if the DejaVu-Sans font supports those characters and if you have it installed on your system?

**Comment by gwpl** [comment]
I have not much knowledge about Linux fonts subsystems. Could you advice if there are any particular commands I should execute to provide data?

The test I've conducted now was to try quoted example with different fonts in LibreOffice Writer,
however I don't know if it does not failover to another font when symbol is missing.
To sum it up, in LibreOffice Writer, results were successful:

![utf-8indifferentfonts](https://user-images.githubusercontent.com/221403/29920877-d3d0d1f4-8e4f-11e7-89a4-a627323b06a5.png)

**Comment by gwpl** [comment]
It worked with Symbola font, I captured here results: https://unix.stackexchange.com/a/389474/9689
Still, automatic failover would be great for imagemagic. (as I mentined [here](https://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=32604&p=149341#p149339)) Does it sound like sound feature request?

**Comment by urban-warrior** [comment]
The ImageMagick philosophy is that the user is king-- meaning we try real hard to not do anything automatically and instead we follow the instructions of the user via the command-line options including defines and settings.  That way the user does not get unexpected results.

**Comment by gwpl** [comment]
Ok, so let me phrase it differently.

As user I'd like to pass to `-font` flag, list of fonts, so ImageMagick would render each symbol with first font where it's available. How does it sound now?

(btw. here I've posted idea of similar workaround, but "outsourced" from imagemagick, to problem of combining multiple fonts into one)
