### ISSUE TITLE
No decode delegates found on Windows 11

### ISSUE THREAD

**Issue by frugbug** [ImageMagick/ImageMagick#7110]
### ImageMagick version

7.1.1-28 Q16-HDRI x64 365d9b6:20240211

### Operating system

Windows

### Operating system, version and so on

Windows 11 22H2

### Description

After installing ImageMagick from the official Windows 64bit installer, all operations will basically fail to complete due to the error ``magick: no decode delegate for this image format `[format name]' @ error/constitute.c/ReadImage/746.``

Trying to open the built in image "rose" will not work. The output of `magick rose: rose.jpg` is as follows:
`magick: unable to open image 'rose:': Invalid argument @ error/blob.c/OpenBlob/3571.`
``magick: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.``

`magick -version` shows `Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib`, however, they don't seem to actually work in practice.

`magick identify -list format` simply returns nothing.

I've made sure to have the Visual C++ Redistributables installed, and re-installed ImageMagick itself many times.
I've read through #6783 but as that seems to be caused by other software the user recently updated (which I don't use) I decided to make this issue anyway, apologies if it actually is a duplicate. Please let me know if I can provide some more information to diagnose the issue!

### Steps to Reproduce

1. Install ImageMagick 7.1.1-28 from the [official installer](https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-28-Q16-HDRI-x64-dll.exe) on Windows 11
2. Run `magick rose: rose.jpg`
3. Note the error produced.

**Comment by fmw42** [comment]
What do get returned from 

`magick -version`

Show everything.

Did you install IM 7 or the legacy IM 6 from the installer?

Which version from https://imagemagick.org/script/download.php#windows did you install?  Is it compatible (64-bit versus 32-bit) to your computer?

**Comment by Luke-Marchant** [comment]
> What do get returned from
> 
> `magick -version`
> 
> Show everything.
> 
> Did you install IM 7 or the legacy IM 6 from the installer?
> 
> Which version from https://imagemagick.org/script/download.php#windows did you install? Is it compatible (64-bit versus 32-bit) to your computer?

```
C:\Users\xxx>magick -version
Version: ImageMagick 7.1.1-28 Q16-HDRI x64 365d9b6:20240211 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Channel-masks(64-bit) Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (193732826)
```

I have IM 7. I installed the version I stated in the my original post in the version section, 7.1.1-28 Q16-HDRI x64, it's the most prominent link on the page under the Windows section. I have a 64 bit system.

**Comment by frugbug** [comment]
For anyone else having this problem, I ended up clumsily "fixing" it by downloading the portable release for the same version, and copying all the files from the portable release into the existing install folder, without replacing. The portable release worked fine by itself as well.

**Comment by JokerMartini** [comment]
> > What do get returned from
> > `magick -version`
> > Show everything.
> > Did you install IM 7 or the legacy IM 6 from the installer?
> > Which version from https://imagemagick.org/script/download.php#windows did you install? Is it compatible (64-bit versus 32-bit) to your computer?
> 
> ```
> C:\Users\xxx>magick -version
> Version: ImageMagick 7.1.1-28 Q16-HDRI x64 365d9b6:20240211 https://imagemagick.org
> Copyright: (C) 1999 ImageMagick Studio LLC
> License: https://imagemagick.org/script/license.php
> Features: Channel-masks(64-bit) Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
> Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
> Compiler: Visual Studio 2022 (193732826)
> ```
> 
> I have IM 7. I installed the version I stated in the my original post in the version section, 7.1.1-28 Q16-HDRI x64, it's the most prominent link on the page under the Windows section. I have a 64 bit system.

I'm having the same issue on our end.
