### ISSUE TITLE
Missing file: jxl/decode.h

### ISSUE THREAD

**Issue by bwva** [ImageMagick/ImageMagick#7111]
### ImageMagick version

7.1.1-28

### Operating system

MacOS

### Operating system, version and so on

14.3.1

### Description

make fails with:
```
coders/jxl.c:64:10: fatal error: 'jxl/decode.h' file not found
#include <jxl/decode.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[1]: *** [coders/MagickCore_libMagickCore_7_Q16HDRI_la-jxl.lo] Error 1
make: *** [all] Error 2

```

### Steps to Reproduce

Downloaded distro ImageMagick 7.1.1-28.tar.gz
tar ImageMagick 7.1.1-28.tar
./configure -with-perl
make 
#...
coders/jxl.c:64:10: fatal error: 'jxl/decode.h' file not found
#include <jxl/decode.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[1]: *** [coders/MagickCore_libMagickCore_7_Q16HDRI_la-jxl.lo] Error 1
make: *** [all] Error 2

**Comment by urban-warrior** [comment]
That would be a configuration issue on your computer.  To fix, install the development headers of the libjxl delegate library or try this command:

```
$ ./configure --without-jxl
```

**Comment by isenberg** [comment]
This works:
```
brew install jxl-oxide jpeg-turbo
CFLAGS="-I$HOMEBREW_PREFIX/opt/libjpeg-turbo/include -I$HOMEBREW_PREFIX/include" LDFLAGS="-L$HOMEBREW_PREFIX/opt/libjpeg-turbo/lib -L$HOMEBREW_PREFIX/lib" ./configure --enable-osx-universal-binary=no [...] --without-x
```
