### ISSUE TITLE
During Install: configure process does not find libraw

### ISSUE THREAD

**Issue by gb5256** [ImageMagick/ImageMagick#7122]
### ImageMagick version

7.1.1-29

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04

### Description

Running the ./configure --with-modules does not find libraw

LibRaw is working standalone as this "raw-identify -v image_sample.dng" does outpout the metadata of the file.

Do I need to specify a path somewhere?

Thanks for any help!
gb5256

### Steps to Reproduce

First install libraw:
```
sudo apt-get install build-essential checkinstall libx11-dev libxext-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev libxml2-dev -y
sudo apt-get install libraw20 libraw-bin libltdl-dev
```

Then install ImageMagick:
```
cd ~
git clone https://github.com/ImageMagick/ImageMagick.git ImageMagick-7.1.1-29
cd ImageMagick-7.1.1-29
./configure --with-modules
```

If I am now looking at the output, I can see
```
...
checking for libraw_r >= 0.14.8... no
...
Delegate library configuration:
...
RAW               --with-raw=yes			no
...
```

**Comment by gb5256** [comment]
@kmilos : thanks for your reply, but same happens with libraw-dev.
It does not find it.

**Comment by urban-warrior** [comment]
Check `config.log`.  Find the reason the libraw library is not validated, fix the issue, and try to `configure` again.  Once the issue is resolved, build and install ImageMagick and you will have Raw image support.
