### ISSUE TITLE
`text-anchor` and `dominant-baseline` not respected in svg conversion

### ISSUE THREAD

**Issue by akbyrd** [ImageMagick/ImageMagick#7136]
### ImageMagick version

7.1.1-29

### Operating system

Windows

### Operating system, version and so on

Win 10 22H2

### Description

When converting an image neither `text-anchor="middle"` or `dominant-baseline="middle"` are respected. Opening the imagine with Inkscape the attributes are applied as expected and text using them is centered. The three major browsers also handle the attributes as expected.

I've confirmed ImageMagick is using Inkscape with the `-verbose` option. Apologies if I'm simply using ImageMagick incorrectly.

### Steps to Reproduce

Using this svg
```
<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48">
	<text x="50%" y="50%" font-size="32px" text-anchor="middle" dominant-baseline="middle">
		{ }
	</text>
</svg>
```

* Open it in inkscape
* Notice the text is centered
* Convert it with `magick -size 180x180 minimal.svg result.png`
* Notice the text is not centered

### Images

Before Conversion
![minimal](https://github.com/ImageMagick/ImageMagick/assets/484784/a4b76644-9878-4342-bb51-f8e5e23ef080)

After Conversion
![apple-touch-icon](https://github.com/ImageMagick/ImageMagick/assets/484784/03983cf4-73ff-4025-af12-6f94a5460d03)

**Comment by akbyrd** [comment]
If I use `-verbose` and manually invoke Inkscape with the same parameters that ImageMagick prints the output image is correct. It looks like IM is creating an intermediate file then converting that with Inkscape, so I suppose something is going wrong when preprocessing the original file and creating the intermediate file that Inkscape ultimately processes?

```
"inkscape" "C:/Users/akbyrd/AppData/Local/Temp/magick-mtaJwpOhyEzrcRDtiw64VnNFMtRi-Xnd" --export-filename="C:/Users/akbyrd/AppData/Local/Temp/magick-OPTXBsn7PO760nZZ-jrBMqBq8Osvl0Dt.png" --export-dpi="96" --export-background="rgb(100%,100%,100%)" --export-background-opacity="1" > "C:/Users/akbyrd/AppData/Local/Temp/magick-MykQJUcuw8dYoDCWYlxAZkIK4t4MoBxP" 2>&1
```

**Comment by urban-warrior** [comment]
The intermediate file is a clone of the authoritative source.

On our Fedora system, we are getting expected results with `inkscape`.  That is, the text is centered.  We're not sure why its failing for you.

**Comment by akbyrd** [comment]
Do you mean that it works when converting the image with ImageMagick from the command line with ` magick -size 180x180 minimal.svg result.png`?

If so, which version? Is there any other information can gather to help diagnose why ImageMagick doesn't work correctly on Windows?

I reproduced this with Windows Sandbox which provides a clean Windows install.
Run this on the host machine to launch Sandbox with winget installed
```
winget configure https://aka.ms/sandbox.dsc.yaml
```

Run this in Windows Powershell in the Sandbox to install ImageMagick, convert the svg, and open the result in Edge
```
winget install ImageMagick

'<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48">
    <text x="50%" y="50%" font-size="32px" text-anchor="middle" dominant-baseline="middle">
        { }
    </text>
</svg>' > minimal.svg

& 'C:\Program Files\ImageMagic-7.1.1-Q16-HDRI\magick.exe' -size 180x180 minimal.svg result.png

start msedge (Get-Item result.png).FullName
```

I tested 3 other machines (not in the Sandbox) that have the same results (ImageMagick 7.1.1.29 on each):
* Windows 10 Pro 22H2 (19045.4123)
* Windows 11 Home 22H2 (22621.3155)
* Windows 11 Home 23H2 (22631.3007)

**Comment by akbyrd** [comment]
> The intermediate file is a clone of the authoritative source.
Ah. I was thinking maybe it was converting the source into MVG then running the conversion on that.

**Comment by dlemstra** [comment]
It looks like there seems to be some odd issue when invoking `inkscape` as a delegate on Windows. I am getting the following error message:

> ConcreteInkscapeApplication<Gtk::Application>::on_open: Can't use '--export-filename' with multiple input files (output file would be overwritten for each input file). Please use '--export-type' instead and rename manually.

It looks like this is happening because we redirect the stdout and stderr output. When I remove that the command executes without any issues. This looks like a bug in inkscape but I also wonder if we really need to save the output to a file because we are not using the output.

p.s. Make sure you also add the path to inkscape to your `%PATH%` because this doesn't seem to be happening automatically.

**Comment by akbyrd** [comment]
> Make sure you also add the path to inkscape to your %PATH% because this doesn't seem to be happening automatically.

For clarity, will this help with the issue or is it just a good idea in general?

**Comment by dlemstra** [comment]
You will need to do that because otherwise inkscape will not be used.

**Comment by akbyrd** [comment]
I've added `C:\Program Files\Inkscape\bin` to my path and confirmed I can invoke `inkscape.com` from my terminal. The issue still occurs. The output when using `-verbose` looks largely the same.

```
"inkscape" "C:/Users/akbyrd/AppData/Local/Temp/magick-z1aVWRIz7IogSFNNgdR3mKZDxZxXL6A7" --export-filename="C:/Users/akbyrd/AppData/Local/Temp/magick-TWI5Xm02xpSXSeH2hhdMLUiv9vy39KDy.png" --export-dpi="96" --export-background="rgb(100%,100%,100%)" --export-background-opacity="1" > "C:/Users/akbyrd/AppData/Local/Temp/magick--wAOw0azw_izCT4kcwMqb56Oc4y2vIaj" 2>&1
test.svg SVG 180x180 180x180+0+0 16-bit sRGB 175B 1.280u 0:01.280
test.svg=>result.png SVG 180x180 180x180+0+0 16-bit sRGB 175B 0.003u 0:00.003
```

How can I confirm inkscape is being used if that verbose logging is insufficient? It listed inkscape as the command in my earlier post before I added inkscape to my path.

I would appreciate keeping this open until we are able to find a working solution.

**Comment by dlemstra** [comment]
The solution has already been applied and will become available in the next release. A temporary patch for you could be changing the `delegates.xml` file and change the `command` for `svg:decode` to this:

> &quot;inkscape&quot; &quot;%s&quot; --export-filename=&quot;%s&quot; --export-dpi=&quot;%s&quot; --export-background=&quot;%s&quot; --export-background-opacity=&quot;%s&quot;
