### ISSUE TITLE
magick mogrify yields "zsh: no matches found" error

### ISSUE THREAD

**Issue by vivzhong** [ImageMagick/ImageMagick#7141]
### ImageMagick version

7.1.1-29

### Operating system

MacOS

### Operating system, version and so on

Sonoma 14.2.1, Apple M1 Pro

### Description

I'm trying to convert all the .tif files in a folder into .jpg. When I run:

`magick mogrify -format tif *.jpg`

I get:

`zsh: no matches found: *.jpg`

Is there something wrong with the command or my files?

### Steps to Reproduce

Run `magick mogrify -format tif *.jpg` inside the folder with .tif files to be converted.

**Comment by fmw42** [comment]
You have it backwards the *.XXX is the input data and the output format is the -format YYY, so

`magick mogrify -format jpg *.tif`

**Comment by vivzhong** [comment]
Oh wow, I feel dumb — thank you!
