### ISSUE TITLE
jasper build issue related to JAS_HAVE_THREAD_LOCAL

### ISSUE THREAD

**Issue by niclet** [ImageMagick/ImageMagick#7146]
### ImageMagick version

7.1.1.29

### Operating system

Windows

### Operating system, version and so on

Windows 10 22H2 - VS 2022 17.4

### Description

It seems that _Thread_local is not supported on all versions of VS 2022.

At least, it is not available in VS 2022 17.4 (threads.h is not available)
It seems to be OK in last available VS2022 17.9.2.

Maybe JAS_HAVE_THREAD_LOCAL should be conditioned to _MSC_VER value ? (1934 is KO, 1939 seems to be OK)

`jasper\src\libjasper\include\jasper\jas_init.h(397,32): error C2054: expected '(' to follow '_Thread_local' (compiling source file ..\..\..\jasper\src\libjasper\base\jas_cm.c)`

### Steps to Reproduce

Just build ImageMagick with VS 2022 17.4

`jasper\src\libjasper\include\jasper\jas_init.h(397,32): error C2054: expected '(' to follow '_Thread_local' (compiling source file ..\..\..\jasper\src\libjasper\base\jas_cm.c) [VisualMagick\VisualStudioProjects\CORE_jasper\CORE_jasper_StaticMTD.vcxproj]`

**Comment by dlemstra** [comment]
Thanks for reporting this. We will patch this sometime this week, not yet sure how we should do that.
