### ISSUE TITLE
Have -path create any needed directories rather than throwing an error.

### ISSUE THREAD

**Issue by dt192** [ImageMagick/ImageMagick#7157]
### Is your feature request related to a problem? Please describe.

-path currently chokes if the destination location doesn't exist.

`mogrify.exe -format tif -path ..\new_dir pngs\*.png`
`mogrify.exe: unable to open image '..\new_dir\0.tif': No such file or directory @ error/blob.c/OpenBlob/3571.`

### Describe the solution you'd like

It should create any directories needed, as specified in the argument.

**Comment by urban-warrior** [comment]
Automatically creating a path if it doesn't exist might seem like a convenient solution at first glance, but there are several reasons why it could be considered a bad idea:

* Security Risks: Automatically creating paths can introduce security vulnerabilities. Imagine a scenario where `mogrify` is used by multiple users or processes with different levels of access. If `mogrify` automatically creates paths, it might create directories with improper permissions, potentially exposing sensitive data or allowing unauthorized access.
* Unintended Consequences: Automatically creating paths could lead to unintended consequences. For example, it might inadvertently create directories in unexpected locations, causing confusion or conflicts with other utilities.
* Data Integrity: Creating paths automatically can bypass validation checks that ensure the integrity of the data. For instance, if the path is meant to point to a specific location where certain files are expected to be stored, automatically creating the path might result in files being stored in the wrong location or with incorrect naming conventions.
* User Expectations: Users might expect `mogrify` to fail if the specified path does not exist, prompting them to take necessary actions to set up the environment properly. Automatically creating paths could mask potential configuration issues, leading to difficulties in troubleshooting or diagnosing problems later on.
* Performance Impact: Depending on the frequency and scale of path creation, automatically creating paths could have a negative impact on performance. It might introduce unnecessary overhead, especially if the creation process involves complex operations or interactions with external systems.
* Lack of Control: By automatically creating paths, you're relinquishing control over the environment to `mogrify`. This can make it harder to enforce organizational policies or implement custom configurations tailored to specific needs.

While automatically creating paths might seem like a convenient shortcut, it's generally better to let users or administrators handle path creation themselves. This approach provides more control, enhances security, and reduces the risk of unintended consequences.
