### ISSUE TITLE
mogrify -resize 60% -monitory *.jpg, does Not change image

### ISSUE THREAD

**Issue by LandisTwo** [ImageMagick/ImageMagick#7161]
### ImageMagick version

7.1.1-29 Q16-HDRI x86_64 21991

### Operating system

Linux

### Operating system, version and so on

opensuse: 15.5 kde: 5.27.9 cpu/gpu: intel

### Description

for the past month or so, when you use mogrify 'in' a directory, it 'goes through the motions' and loads, processes, save each image file, but Nothing changes dimensions or size on disk
OR, it takes 30 minutes per image. 1.x to 3.x MB files
It may do the first image as usual, but by image 2 or three it's 1% per many minutes, to days.
# mogrify -resize 60% -monitor *.jpg
load image[Casting_001.jpg]: 2073 of 2074, 100% complete
resize image[Casting_001.jpg]: 3109 of 3110, 100% complete
save image[Casting_001.jpg]: 1243 of 1244, 100% complete
load image[Casting_002.jpg]: 5183 of 5184, 100% complete ^C [I cancelled at 2%, @ 5 mins]
was installed from main repo at opensuse_leap_15
changed to leap_15_graphics repo still hours/days to -resize a directory

downgraded to ImageMagick 7.1.0-9 Q16-HDRI x86_64 2021-10-03 and all is fine..
may be a opensuse issue

### Steps to Reproduce

cd to a directory with images.jpg
# mogrify -resize 60% -montor *.jpg
enter.... WAIT!
load first image
resize first image
save first image
load second image
resize second image 1%, 2%
C^ because it's taking 5 to 10 mins instead of a several seconds.

**Comment by fmw42** [comment]
Have you tried without the -monitor

**Comment by fmw42** [comment]
Can you provide an example input and your command for that input that does not create an output.

What is all the information returned from 

magick -version

**Comment by fmw42** [comment]
Do you have enough space in /tmp and your RAM?
