### ISSUE TITLE
Image::Magic does not install via span on Debian bookworm

### ISSUE THREAD

**Issue by PavelNSH** [ImageMagick/ImageMagick#7171]
### ImageMagick version

7.1.1

### Operating system

Linux

### Operating system, version and so on

Debian bookworm

### Description

I install it in Docker based on Debian and perl 5.38. Doesn't find magick/magick-baseconfig.h during installation

`cc -c  -I/usr/local/include/ImageMagick-7 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/libxml2 -I"/usr/include/ImageMagick-7" -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -I/usr/include/freetype2 -g -O2 -Wall -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -O2   -DVERSION=\"7.1.1\" -DXS_VERSION=\"7.1.1\" -fPIC "-I/usr/local/lib/perl5/5.36.3/x86_64-linux-gnu/CORE"  -D_LARGE_FILES=1 -DHAVE_CONFIG_H Magick.c
In file included from /usr/include/ImageMagick-7/MagickCore/MagickCore.h:29,
                 from Magick.xs:56:
/usr/include/ImageMagick-7/MagickCore/magick-config.h:25:10: fatal error: MagickCore/magick-baseconfig.h: No such file or directory
   25 | #include "MagickCore/magick-baseconfig.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

### Steps to Reproduce
1. Copy from https://www.deb-multimedia.org/pool/main/d/deb-multimedia-keyring/deb-multimedia-keyring_2016.8.1_all.deb

2. `docker build .`

with Dockerfile:

```
FROM perl:5.38

RUN echo 'Types: deb' >> /etc/apt/sources.list.d/debian.sources
RUN echo 'URIs: http://www.deb-multimedia.org' >> /etc/apt/sources.list.d/debian.sources
RUN echo 'Suites: bookworm' >> /etc/apt/sources.list.d/debian.sources
RUN echo 'Components: main' >> /etc/apt/sources.list.d/debian.sources

COPY . .

RUN dpkg -i deb-multimedia-keyring_2016.8.1_all.deb
RUN echo 'Signed-By: /etc/apt/trusted.gpg.d/deb-multimedia-keyring.gpg' >> /etc/apt/sources.list.d/debian.sources

RUN apt-get update

RUN apt-get update -oAcquire::AllowInsecureRepositories=true
RUN apt-get install libmagickcore-7-dev -y

RUN cpanm -i Bundle::CPAN
#RUN cpanm install Image::Magick
```

3. `docker run -it <image> bash`

4. `cpan install Image::Magick`

**Comment by urban-warrior** [comment]
You'll need to install the ImageMagick library first then PerlMagick.

**Comment by PavelNSH** [comment]
> You'll need to install the ImageMagick library first then PerlMagick.

Yeah, only the distribution version 6 of ImageMagick, and when installing version 7 from third-party repositories, the situation does not get any better.

**Comment by urban-warrior** [comment]
Download the ImageMagick source distribution and add the `--with-modules --with-perl` to the `configure` script command-line.  This will build and install both ImageMagick and PerlMagick.
