### ISSUE TITLE
Sony Raw CR3 on Ubuntu/docker - can't get it to work

### ISSUE THREAD

**Issue by Webreaper** [ImageMagick/ImageMagick#7173]
### ImageMagick version

 7.1.1-29

### Operating system

Linux

### Operating system, version and so on

Docker Ubuntu 23.10

### Description

I use ImageMagic as part of my Image management app, Damselfly. I've got a base image which should install all the deps, and build a version of ImageMagick `convert` that'll support HEIC, Raw and any other formats I need. However, I can't for the life of me get it to convert CR3s successfully. 

### Steps to Reproduce

Here's my dockerfile (I'm working on the `develop` branch): https://github.com/Webreaper/Damselfly-Base-Image/blob/develop/Dockerfile - it's installing all the right (I think) tools and deps and delegates, including libraw-dev and libraw-bin.

The dockerfile does the IM build using this script: https://github.com/Webreaper/Damselfly-Base-Image/blob/develop/make_imagemagick.sh - is there anything I'm missing for CR3 support? It works for everything else, including HEIC. 

Running the version from inside the base image gives: 

```
root@1dd3b429b87a:/app# convert -version
Version: ImageMagick 7.1.1-29 Q16-HDRI x86_64 21991 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib djvu fontconfig freetype jbig jng jp2 jpeg lcms lqr lzma openexr pangocairo png raw tiff webp x xml zlib
Compiler: gcc (9.4)
```
You can try this yourself if you pull `webreaper/damselfly-base:dev` and bash into the image, and poke about. 

Any clues what might be missing? 

The sample Image I've been testing with is linked here: https://github.com/Webreaper/Damselfly/issues/520#issuecomment-1997749820 - and it converts fine when using the ImageMagick that distributes with MacOS. 

Any help you can give to identify what's missing from my build would be much appreciated!!

Edit: I've also just noticed that in my latest build, since I added `--with-raw=yes` and `libraw-dev` that seems to have broken HEIC now: 
```
#10 133.3 Delegate library configuration:
#10 133.3   BZLIB             --with-bzlib=yes			yes
#10 133.3   Autotrace         --with-autotrace=no			no
#10 133.3   DJVU              --with-djvu=yes			yes
#10 133.3   DPS               --with-dps=no			no
#10 133.3   FFTW              --with-fftw=no			no
#10 133.3   FLIF              --with-flif=no			no
#10 133.3   FlashPIX          --with-fpx=no			no
#10 133.3   FontConfig        --with-fontconfig=yes		yes
#10 133.3   FreeType          --with-freetype=yes			yes
#10 133.3   Ghostscript lib   --with-gslib=no			no
#10 133.3   Graphviz          --with-gvc=yes			no
#10 133.3   HEIC              --with-heic=yes			no
#10 133.3   JBIG              --with-jbig=yes			yes
#10 133.3   JPEG v1           --with-jpeg=yes			yes
#10 133.3   JPEG XL           --with-jxl=yes			no
#10 133.3   DMR               --with-dmr=yes			no
#10 133.3   LCMS              --with-lcms=yes			yes
#10 133.3   LQR               --with-lqr=yes			yes
#10 133.3   LTDL              --with-ltdl=no			no
#10 133.3   LZMA              --with-lzma=yes			yes
#10 133.3   Magick++          --with-magick-plus-plus=yes		yes
#10 133.3   OpenEXR           --with-openexr=yes			yes
#10 133.3   OpenJP2           --with-openjp2=yes			yes
#10 133.3   PANGO             --with-pango=yes			yes
#10 133.3   PERL              --with-perl=no			no
#10 133.3   PNG               --with-png=yes			yes
#10 133.3   RAQM              --with-raqm=yes			no
#10 133.3   RAW               --with-raw=yes			yes
#10 133.3   RSVG              --with-rsvg=no			no
#10 133.3   TIFF              --with-tiff=yes			yes
```
Any idea why?!?

**Comment by fmw42** [comment]
Perhaps your release of Cannon software is not up to date.

What do you get for CR3 in

`magick -list format`

By the way it is only Read (not write) compatible in Imagemagick.

**Comment by snibgo** [comment]
Do you get an error message when trying to read the CR3?

What version of libraw do you have? For example:
```
C:\web\im>%IMG7%magick -list format |grep -i cr3
      CR3  r--   Canon Digital Camera Raw Image Format (0.21.1-Release)
```
If yours is older, that may be the problem.

There are different forms of CR3 files, for different camera models. Libraw can't yet process all CR3 files. But your file can be processed by IM v7.1.1-20:
```
C:\web\im>%IMG7%magick img_0201.cr3 info:
img_0201.cr3 CR3 5999x3999 6188x4120+168+108 16-bit sRGB 22.0285MiB 0.000u 0:00.000
```

**Comment by Webreaper** [comment]
> Perhaps your release of Cannon software is not up to date.
> 
> What do you get for CR3 in
> 
> `magick -list format`

I get:
```
CR3  r--   Canon Digital Camera Raw Image Format (0.19.5-Release)
```
> By the way it is only Read (not write) compatible in Imagemagick.

Read is all I need!

**Comment by Webreaper** [comment]
> If yours is older, that may be the problem.
> 
> There are different forms of CR3 files, for different camera models. Libraw can't yet process all CR3 files. But your file can be processed by IM v7.1.1-20:
> 
> ```
> C:\web\im>%IMG7%magick img_0201.cr3 info:
> img_0201.cr3 CR3 5999x3999 6188x4120+168+108 16-bit sRGB 22.0285MiB 0.000u 0:00.000
> ```

Looks like that may be the issue - as above, the one I'm pulling is 0.19.5. As you say, it works on MacOS. 

Is there anything in my build I can do to get a newer libraw? Or is it just a case of waiting until it's availalble via `apt-get`?

**Comment by Webreaper** [comment]
Looks like the problem is that I'm getting an older version of Libraw:
```
#6 6.381 The following additional packages will be installed:
#6 6.381   fontconfig-config libbsd0 libc-dev-bin libcairo2 libcrypt-dev libexif12
#6 6.381   libexpat1 libfontconfig1 libfreetype6 libgif7 libglib2.0-0 libjbig0
#6 6.381   libjpeg-turbo8 libjpeg8 liblcms2-2 libpixman-1-0 libpng16-16 libraw19
#6 6.381   libtiff5 libwebp6 libx11-6 libx11-data libxau6 libxcb-render0 libxcb-shm0
#6 6.382   libxcb1 libxdmcp6 libxext6 libxrender1 linux-libc-dev ucf
#6 6.382 Suggested packages:
#6 6.382   gphoto2 netpbm glibc-doc manpages-dev liblcms2-utils
#6 6.382 Recommended packages:
#6 6.382   manpages manpages-dev libglib2.0-data shared-mime-info xdg-user-dirs
#6 6.447 The following NEW packages will be installed:
#6 6.447   apt-utils dcraw fontconfig fontconfig-config fonts-liberation libbsd0
#6 6.447   libc-dev-bin libc6-dev libcairo2 libcrypt-dev libexif12 libexpat1
#6 6.447   libfontconfig1 libfreetype6 libgdiplus libgif7 libglib2.0-0 libgomp1
#6 6.447   libjbig0 libjpeg-turbo8 libjpeg8 liblcms2-2 libpixman-1-0 libpng16-16
#6 6.448   libraw-bin libraw19 libtiff5 libwebp6 libx11-6 libx11-data libxau6
#6 6.448   libxcb-render0 libxcb-shm0 libxcb1 libxdmcp6 libxext6 libxrender1
#6 6.448   linux-libc-dev ucf
#6 6.912 0 upgraded, 39 newly installed, 0 to remove and 0 not upgraded.
#6 6.912 Need to get 10.3 MB of archives.
#6 6.912 After this operation, 48.4 MB of additional disk space will be used.
#6 6.912 Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 apt-utils amd64 2.0.10 [213 kB]
...
(https://github.com/Webreaper/Damselfly-Base-Image/actions/runs/8289404552/job/22685768392#step:7:65) libraw-bin amd64 0.19.5-1ubuntu1.3 [41.8 kB]
#6 7.874 Get:39 http://archive.ubuntu.com/ubuntu focal/universe amd64 dcraw amd64 9.28-2 [219 kB]
#6 8.710 debconf: delaying package configuration, since apt-utils is not installed
#6 8.738 Fetched 10.3 MB in 1s (72[65](https://github.com/Webreaper/Damselfly-Base-Image/actions/runs/8289404552/job/22685768392#step:7:66) kB/s)
```
Seems like the latest is available: https://launchpad.net/ubuntu/+source/libraw/0.21.2-2.1

Do you know if/how I can use an alternate package source to get 0.21? I'm not an expert on `apt-get` so not sure how to solve this...

**Comment by Webreaper** [comment]
Okay, looks like the best option is to build libraw 0.21.2 myself. Giving that a go, will close the issue if it works!

**Comment by Webreaper** [comment]
Confirmed building 0.21.2 myself fixed it.
