### ISSUE TITLE
Posterize flag crashing the application

### ISSUE THREAD

**Issue by dooman87** [ImageMagick/ImageMagick#7181]
### ImageMagick version

7.1.1-29

### Operating system

Linux

### Operating system, version and so on

Debian 12 (bookworm)

### Description

Something changed between versions 7.1.1-17 and 7.1.1-29 that causing the application to run out of memory. I could narrow down the problem to `posterise` flag.

### Steps to Reproduce

Running below command causing IM to crash:

```
convert ./test.png -auto-orient -posterize 136 -dither None -define jpeg:fancy-upsampling=off -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=0 -define png:exclude-chunk=bKGD,cHRM,EXIF,gAMA,iCCP,iTXt,sRGB,tEXt,zCCP,zTXt,date -define heic:speed=6 -interlace None -colorspace sRGB -sampling-factor 4:2:0 +profile '!icc,*' -define webp:lossless=true -quality 100 -define jxl:effort=9 -define webp:method=6 webp:./test.webp
```

Removing `-posterize 136` make it work :)

### Images

![test](https://github.com/ImageMagick/ImageMagick/assets/124110/431b67b3-176e-433b-b313-1aeb6b20a980)

**Comment by snibgo** [comment]
Your command (using "magick convert" or "magick") works fine for me, with IM 7.1.1-20 on Windows 11. But using IM v7.1.1-28, it gets stuck in a loop, eating more and more memory.

The same problem occurs when we simplify the command to:
```
magick envel.png -auto-orient -posterize 136 x.png
```
Instead of "136", using "100" causes the problem. Using "10" succeeds. Using "50", we get:
```
magick envel.png -auto-orient -posterize 50 x.png
magick: unable to create colormap `envel.png' @ error/colormap.c/AcquireImageColormap/123.
magick: memory allocation failed `envel.png' @ error/quantize.c/SetImageColormap/4088.
```
So that provides a clue. Perhaps "136" runs out of memory, but doesn't realise this.

**Comment by urban-warrior** [comment]
We traced the issue.  Give us a few days to come up with an optimal patch.

**Comment by dooman87** [comment]
Thank you so much for a quick turn around!
