### ISSUE TITLE
There is an advertisement in the middle of the text for connected components

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#7210]
### ImageMagick version

7.1.1.29

### Operating system

MacOS

### Operating system, version and so on

Ventura

### Description

See https://imagemagick.org/script/connected-components.php

There is some kind of advertisement in the middle of the text on that page about "Discover related topics".

Is this intended?  If so, I think it should be at the bottom of the page. Being in the middle of the page breaks up one's reading of CCL and is annoying.

### Steps to Reproduce

See above

### Images

None

**Comment by urban-warrior** [comment]
We use Google ads to help support the ImageMagick open-source project.  We have some modest control over how many ads appear on a page and where.   We're experimenting with the limited controls we have and that will take a few days.  If the new Google ads does not work out, we'll revert to placing a single ad at the top of the page.
