### ISSUE TITLE
-draw "color 0,0 point" does not respect gravity

### ISSUE THREAD

**Issue by znakeeye** [ImageMagick/ImageMagick#7222]
### ImageMagick version

7.1.1-29

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

The `-draw` command does not respect gravity. E.g. This examples should (correct me if I'm wrong) render a pixel at the bottom right.
```bat
magick.exe convert test.png -fill "rgb(255,00,00)" -gravity southeast -draw "color 0,0 point" point-bottom-right.png
```
Also tried this:
```bat
magick.exe convert test.png -fill "rgb(255,00,00)"-draw "gravity southeast color 0,0 point" point-bottom-right.png
```

**Expected:** The red pixel is rendered at the bottom right pixel.
**Actual:** The red pixel is rendered at the top left pixel.

### Steps to Reproduce

Just run the command above.

### Images

![test](https://github.com/ImageMagick/ImageMagick/assets/958469/63893761-ca94-4d48-a639-0ef7f7a24fef)

**Comment by fmw42** [comment]
This is not an answer.  But I note that for IM 7, use magick, not magick convert.  magick is a replacement for convert.

**Comment by snibgo** [comment]
Most `-draw` operations are not sensitive to the `-gravity` setting. As far as I know, they never have been. So that is the expected behaviour.

See https://imagemagick.org/script/command-line-options.php#gravity :

> Only the text primitive of -draw is affected by the -gravity option.

**Comment by znakeeye** [comment]
Fair enough. Then how do you set the bottom right pixel of an image without manual steps? I've googled all day 😛

**Comment by fmw42** [comment]
You can use inline computations, %[fx:w-1],%[fx:h-1], for the coordinates inside the -draw command.

**Comment by snibgo** [comment]
As fmw42 says.

It can also be done with a `translate` inside the `-draw` string, *before* the `color` operation, kike this:
```
magick in.png -draw "translate %[fx:w-1],%[fx:h-1] color 0,0 point" out.png
```
