### ISSUE TITLE
perl module man pages installed to wrong path

### ISSUE THREAD

**Issue by antonio-rojas** [ImageMagick/ImageMagick#7231]
### ImageMagick version

7.1.1-30

### Operating system

Linux

### Operating system, version and so on

Arch Linux x86_64

### Description

In 7.1.1-30, the man pages for `Image::Magick.3pm.gz` and `Image::Magick::Q16HDRI.3pm.gz` are installed in `${prefix}/man` instead of `${prefix}/share/man`

### Steps to Reproduce

Build and install the package with `--with-perl`

**Comment by urban-warrior** [comment]
We've incorporated a patch to facilitate the installation of PerlMagick into the ImageMagick build prefix. You can find more details on how to do this in the documentation at https://perldoc.perl.org/ExtUtils::MakeMaker#INSTALL_BASE. One notable aspect is the configuration of INSTALLMAN3DIR, which is set to INSTALL_BASE/man/man3. This allows you to customize the installation directory from the command-line, thus overriding the default location.

**Comment by dbermond** [comment]
Looks like this can done by specifying `INSTALLVENDORMAN3DIR` in `--with-perl-options` when installing into the `vendor` directory.

For example:

```
--with-perl-options='INSTALLDIRS=vendor INSTALLVENDORMAN3DIR=/usr/share/man/man3'
```

Offtopic, but related: the perl module is also being installed into a different directory. This can be changed by specifying `INSTALLVENDORARCH` in `--with-perl-options` when installing into the `vendor` directory.
