### ISSUE TITLE
-separate no longer outputting only channels

### ISSUE THREAD

**Issue by blue-j** [ImageMagick/ImageMagick#7237]
### ImageMagick version

7.1.1-29

### Operating system

MacOS

### Operating system, version and so on

13.6.6

### Description

The -separate switch no longer reliably outputs only channel images (for TIFFs with embedded PSDs at least)

### Steps to Reproduce

magick -define psd:alpha-unblend=off -define colorspace:auto-grayscale=false 609205.tif -separate -channel ALL channels.cha%d.png

or

magick -define psd:alpha-unblend=off -define colorspace:auto-grayscale=false 609205.tif -separate channels.cha%d.png

### Images

[609205.tif.zip](https://github.com/ImageMagick/ImageMagick/files/14923258/609205.tif.zip)

**Comment by fmw42** [comment]
Your command produces 26 images for me.  Is that what you expect?

Your command is not proper IM 7 syntax.  You should generally read the input before any settings or operators for reading raster images.  You should put your settings before the operators that use them. So a more proper syntax would be

`magick 609205.tif -define colorspace:auto-grayscale=false -define psd:alpha-unblend=off -channel ALL -separate channels.cha%d.png`

Why are you specifying a define for PSD when your input and output are not PSD?

You do not need the colorspace define either for PNG or TIFF and should normally be accompanied by -type truecolor, when used. The define docs at https://imagemagick.org/script/defines.php says

> colorspace:auto-grayscale=on|off	Prevent automatic conversion to grayscale inside coders that support grayscale. This should be accompanied by -type truecolor. PNG and TIF do not need this define. With PNG, just use PNG24:image. With TIF, just use -type truecolor. JPG and PSD will need this define.

**Comment by snibgo** [comment]
@blue-j: Please tell us what you expect from your command, and why what you get is not correct.

**Comment by fmw42** [comment]
That would be what I would have expected - 3 channel images.  Looks like you are getting channels for each layer.  Might the -channel ALL mean to get all channels for each layer?  Or perhaps this is a bug?

**Comment by snibgo** [comment]
fmw42 wrote:
> Your command produces 26 images for me on Mac OSX Ventura with IM 7.1.1.29. Is that what you expect?

I get 27 images from:
```
magick 609205.tif -separate info:
```

blue-j wrote:
> the image only has the 3 color channels and zero alphas.

That isn't correct. Some images in the file have alpha.


We can see what images we have, and how many channels are in each image:
```
C:\web\im>%IMG7%magick 609205.tif info:
609205.tif[0] TIFF 2000x2000 2000x2000+0+0 8-bit TrueColor sRGB 33.2375MiB 0.001u 0:00.000
609205.tif[1] TIFF 2000x2000 2000x2000+0+0 8-bit sRGB 33.2375MiB 0.003u 0:00.002
609205.tif[2] TIFF 2632x2632 2632x2632-23-608 8-bit sRGB 33.2375MiB 0.004u 0:00.004
609205.tif[3] TIFF 2421x538 2421x538+308+863 8-bit sRGB 33.2375MiB 0.006u 0:00.005
609205.tif[4] TIFF 1906x1906 1906x1906+48+48 8-bit sRGB 33.2375MiB 0.007u 0:00.006
609205.tif[5] TIFF 2000x2000 2000x2000+1+1 8-bit sRGB 33.2375MiB 0.008u 0:00.008
609205.tif[6] TIFF 2002x2002 2002x2002+0+0 8-bit sRGB 33.2375MiB 0.009u 0:00.009

C:\web\im>%IMG7%magick 609205.tif -format %[channels]\n info:
srgb  3.0
srgb  3.0
srgba 4.0
srgba 4.0
srgba 5.1
srgba 4.0
srgba 4.0
```
Image [4] has five channels, including one meta channel:
```
%IMG7%magick 609205.tif[4] -verbose info:

  Channels: 5.1
  Channel depth:
    Red: 8-bit
    Green: 8-bit
    Blue: 8-bit
    Alpha: 8-bit
    Meta channel[0]: 1-bit
  Channel statistics:
    Pixels: 3632836
    Red:
      min: 23  (0.0901961)
      max: 255 (1)
      mean: 247.799 (0.971759)
      median: 255 (1)
      standard deviation: 24.9006 (0.0976492)
      kurtosis: 13.0034
      skewness: -3.60627
      entropy: 0.134098
    Green:
      min: 10  (0.0392157)
      max: 255 (1)
      mean: 245.7 (0.963529)
      median: 255 (1)
      standard deviation: 31.6391 (0.124075)
      kurtosis: 10.8511
      skewness: -3.40874
      entropy: 0.133502
    Blue:
      min: 0  (0)
      max: 255 (1)
      mean: 243.806 (0.956101)
      median: 255 (1)
      standard deviation: 37.6752 (0.147746)
      kurtosis: 9.49699
      skewness: -3.27681
      entropy: 0.1346
    Alpha:
      min: 0  (0)
      max: 255 (1)
      mean: 21.5729 (0.0845997)
      median: 0 (0)
      standard deviation: 70.6312 (0.276985)
      kurtosis: 6.93418
      skewness: 2.98531
      entropy: 0.0636593
    Meta channel[0]:
      min: 0  (0)
      max: 0 (0)
      mean: 0 (0)
      median: 0 (0)
      standard deviation: 0 (0)
      kurtosis: -3
      skewness: 0
      entropy: 4.82164e-05
```
The meta channel is boring: entirely zero. What happens when we `-separate` that image?
```
C:\web\im>%IMG7%magick 609205.tif[4] -separate info:
609205.tif[4][0] TIFF 1906x1906 1906x1906+48+48 8-bit Gray 33.2375MiB 0.001u 0:00.000
609205.tif[4][1] TIFF 1906x1906 1906x1906+48+48 8-bit Gray 33.2375MiB 0.002u 0:00.002
609205.tif[4][2] TIFF 1906x1906 1906x1906+48+48 8-bit Gray 33.2375MiB 0.004u 0:00.003
609205.tif[4][3] TIFF 1906x1906 1906x1906+48+48 8-bit Gray 33.2375MiB 0.005u 0:00.004
609205.tif[4][4] TIFF 1906x1906 1906x1906+48+48 8-bit Gray 33.2375MiB 0.006u 0:00.005
```
As expected, `-separate` makes 5 images from image [4].

**Comment by fmw42** [comment]
> I get 27 images from:

It is possible that I forgot to count the 0th file.  I don't have them around any longer

**Comment by dlemstra** [comment]
The `-separate` command works on all images/laters in the file. When you only want the primary image you will need to use `609205.tif[0] -separate` instead.
