### ISSUE TITLE
Failed to assign ICC/ICM profile

### ISSUE THREAD

**Issue by liuxd17thu** [ImageMagick/ImageMagick#7239]
### ImageMagick version

7.1.1-30

### Operating system

Windows

### Operating system, version and so on

Windows 11 23H2

### Description

Sometimes imagemagick raises an error when assigning specific ICM Profiles.
```
magick.exe: profile 'icc': 2F6h: length does not match profile `output.png' @ warning/png.c/MagickPNGWarningHandler/1526.
```

### Steps to Reproduce

Test files are here: https://drive.google.com/file/d/1uZ7_wJ3DGYMgVDPCf401bvXWhjAvKmWT/view?usp=sharing

Error:
```powershell
magick.exe input.png -profile ".\LG ULTRAGEAR+.ICM" output.png
```
No error:
```powershell
magick.exe input.png -profile ".\sRGB Color Space Profile.icm" output.png
```

**Comment by snibgo** [comment]
> @ warning/png.c/MagickPNGWarningHandler/1526.

That is a warning, not an error. I can assign that profile to an image and write that to a PNG file, despite the warning.

**Comment by liuxd17thu** [comment]
> That is a warning, not an error. I can assign that profile to an image and write that to a PNG file, despite the warning.

Yes you are right. I have found the icc information in the output image.
