### ISSUE TITLE
Shortcut "ImageMagick Display" is pointing to old version - 7.1.1.29

### ISSUE THREAD

**Issue by metaad** [ImageMagick/ImageMagick#7246]
### ImageMagick version

7.1.1.30

### Operating system

Windows

### Operating system, version and so on

Windows 10 x64

### Description

While testing upgrade **7.1.1.30** downloaded from (https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-30-Q16-x64-dll.exe)  from 7.1.1.29, it was found that when shortcut is launched it is still showing the version as 7.1.1.29
![image](https://github.com/ImageMagick/ImageMagick/assets/106653425/937170a1-e7ba-45a5-9184-3532bc498f11)

Also when 7.1.1.30 is installed on the clean machine without earlier version, the shortcut does not get installed. Also there are few files missing in latest version. **Is this the intended behavior of this release or a bug?**

![image](https://github.com/ImageMagick/ImageMagick/assets/106653425/a533dc5c-5279-43a5-a6a1-69f4dddb402a)

### Steps to Reproduce

1. Install old version 7.1.1.29
2. Upgrade with 7.1.1.30
3. Launch Shortcut **ImageMagick Display** ->Help->IMDispaly

### Images

![image](https://github.com/ImageMagick/ImageMagick/assets/106653425/f4135459-010e-4607-88bd-6665850c72b9)

**Comment by dlemstra** [comment]
This is intended behavior, the `IMDisplay` program is no longer part of the Windows installation.

**Comment by c-exe** [comment]
> This is intended behavior, the IMDisplay program is no longer part of the Windows installation.

The installer still claims it is placing a desktop icon for imdisplay (it doesn't) and then asks you to use 
```
magick wizard: wizard.jpg
magick wizard.jpg win:
```
to confirm that imagmagick is installed, which doesn't work of course (failing with `magick: delegate failed `imdisplay "%i"' @ error/delegate.c/InvokeDelegate/1924.`).  If `IMDisplay` has been removed, all this should be changed.  (Also, why is `IMDisplay` removed?  It should still work: I upgraded to the latest from 7.0.1 on Windows 10 and the old version worked fine?)

**Comment by dlemstra** [comment]
We removed `IMDisplay` from the Windows installer because we will no longer support this. There are better alternatives like [ImageGlass](https://imageglass.org/) available now.

We have updated the documentation of the website but it might take a couple days before this is updated on the website.
