### ISSUE TITLE
Convert big PDF documents is slow

### ISSUE THREAD

**Issue by scresto09** [ImageMagick/ImageMagick#7262]
### Is your feature request related to a problem? Please describe.

Hello,

I noticed that saving large PDF files with ImageMagick was very slow, and it was generating the PDF ID entry which took a long time.
According to the PDF specification, this ID field is not required (page 47 of Document Management — Portable Document Format — Part 1: PDF 1.7).

### Describe the solution you'd like

I will add the **pdf:noID=true** option to the PDF encoder which allows this ID field not to be generated.

With a 3 MB JPG file, this goes from 1.12 s to 0.28 s.
![bench](https://github.com/ImageMagick/ImageMagick/assets/22740592/74aec3c9-34e0-44ba-9149-6892f99ba9c0)

**Comment by dlemstra** [comment]
There really is no need to start a discussion, open an issue and also create a PR. Next time feel free to start with a pull request.
