### ISSUE TITLE
The latest ImageMagick does not install `CORE_RL_MagickCore_.lib` on Windows

### ISSUE THREAD

**Issue by Watson1978** [ImageMagick/ImageMagick#7272]
### ImageMagick version

7.1.1-30

### Operating system

Windows

### Operating system, version and so on

11

### Description

I maintain RMagick, the ImageMagick binding for Ruby.
To build the binding, it depends on CORE_RL_MagickCore_.lib.
Since ImageMagick-7.1.1-30, the installer no longer installs `CORE_RL_MagickCore_.lib`.
Therefore, our binding installation is no longer available....

Is it possible to get the CORE_RL_MagickCore_.lib installed again?

And ImageMagick 6 has same issue....

Thanks

### Steps to Reproduce

https://github.com/rmagick/rmagick/issues/1584

**Comment by dlemstra** [comment]
We have removed the `.lib` files from the installer because you probably don't need those `.lib` files. I suspect that it is just being used to detect that ImageMagick is installed. I think you can fix this by tweaking the `extconf.rb` file. You don't need to link those `.lib` files those files are available as `.dll` files and should be referenced instead?

**Comment by dlemstra** [comment]
Those symbols are exported in the `CORE_RL_MagickCore_.dll` file. You should be able to reference those symbols with a `dllimport` instead?

**Comment by Watson1978** [comment]
Is the ImageMagick API interface immutable? It is a lot of work to keep up with every change, and we do not want to do it.

**Comment by dlemstra** [comment]
If you use a `dllimport` you are still using the same header files and this will result in a build error when the api changes. We don't change our API interface that often and when we do it will be a new method. You would need to do the same amount of work when you are using our `.lib` or `.dll` files. The only difference would be how the MagickCore library is linked.

**Comment by Watson1978** [comment]
OK, I try to change build proccess of our binding.
Thanks

**Comment by dlemstra** [comment]
Feel free to come back here or ping me in the other issue if you need help with this.
