### ISSUE TITLE
error: 'png_text'

### ISSUE THREAD

**Issue by Kr3m** [ImageMagick/ImageMagick#7275]
### ImageMagick version

7.1.1

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04

### Description

coders/png.c:7939:13: error: 'png_text' {aka 'struct png_text_struct'} has no member named 'itxt_length'; did you mean 'text_length'?
 7939 |     text[0].itxt_length=length;

### Steps to Reproduce

./configure
make

**Comment by urban-warrior** [comment]
The `itxt_length` structure member was introduced to libpng in version 1.6.0.  We need to add a version check in `coders/png.c`.

**Comment by dlemstra** [comment]
Okay, I will add a patch for that.
