### ISSUE TITLE
Add DLLs to ImageMagick Windows portable versions

### ISSUE THREAD

**Issue by ErwanBDF** [ImageMagick/ImageMagick#7287]
### Is your feature request related to a problem? Please describe.

Our proxy did not authorize download of exe files. 
So I'm turn on portable versions, but I would like to use it with Python mapped by Wand.
Wand need DLLs to work.

### Describe the solution you'd like

Integrate DLLs files in Windows portable versions

### Describe alternatives you've considered

No alternative solution found.

**Comment by ErwanBDF** [comment]
I forgot to mention that I also can execute and install software which manipulate windows registry.

Regards

**Comment by dlemstra** [comment]
This sounds like you will need to build ImageMagick yourself instead. We will not be going to create a new portable version that contains `.dll` files.

**Comment by ErwanBDF** [comment]
I am working in a context with a lot of security constraints... That's why, I was asking for this... 
Unlucky me... :(

**Comment by dlemstra** [comment]
I am sorry but this would require more work and maintaince for us.
