### ISSUE TITLE
[IM7] image.negate() broken

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#729]
Image negation does not work in IM7. It works fine in IM6. I think it is related to transparency. Example below.

![frink](https://user-images.githubusercontent.com/216319/30019266-3a44723e-9160-11e7-86fc-4489822a1eb7.png)

```c++
#include <Magick++.h>

int main(){
  Magick::Image image("frink.png");
  image.negate();
  image.write(std::string("negated.png"));
}
```

![negated](https://user-images.githubusercontent.com/216319/30019278-3eeefc6e-9160-11e7-9c4a-d5367ad62f6b.png)

**Comment by mikayla-grace** [comment]
See the porting guide @ https://www.imagemagick.org/script/porting.php: the default is to update the RGBA channels, previously, in IMv6, the default was RGB. If you get results that differ from IMv6, you may need to specify -channel RGB on your command line (e.g. -level-colors option).  This works for us:

`convert 30019266-3a44723e-9160-11e7-86fc-4489822a1eb7.png -channel RGB -negate negate.png`

**Comment by jeroen** [comment]
I am using the C++ api, not the command line option. It seems to me that the code above is correct?

**Comment by mikayla-grace** [comment]
Same principle applies.  Set the channels in C++ to RGB rather than RGBA.  By default, ImageMagick treats all channels the same-- so alpha is negated along with the other channels.  By setting the channel mask to RGB, the alpha channel is left alone-- that is it is not negated matching the behavior of IMv6.

**Comment by jeroen** [comment]
Perhaps the `image.negate()` method should set to RGB by default then? I cannot imagine this new behavior is ever intended?

**Comment by dlemstra** [comment]
I think the default for the channels should be CompositeChannels. Will push a patch for this later tonight.

**Comment by mikayla-grace** [comment]
Disagree.  Magick++ should match the behavior of the command line to avoid confusion and to match the "written in stone" expectations of the porting guide.  Instead the user can set the channels to CompositeChannels if that is what they want.   Its always a question of defaults.  In IMv6 we had SyncChannels to treat all channels as independent.  This is the default for IMv7.  For some options, it makes sense to treat the alpha channels differently but for others it should be treated the same as all other channels.  Given that, the default should be to treat all the channels the same unless the user decides to treat it differently so we don't get unexpected behavior.

**Comment by jeroen** [comment]
Can you explain how I do this in C++ (preferably via the STL)? I try this but I can't get it to work:

```
  for_each ( output->begin(), output->end(), Magick::channelImage(Magick::RGBChannels));
  for_each ( output->begin(), output->end(), Magick::negateImage());
```

I think negating by the alpha channel is almost always undesired and unexpected but OK.

**Comment by dlemstra** [comment]
I think you should use `Magick::CompositeChannels` instead. That is what I use in Magick.NET to avoid default negating of the alpha channel.

**Comment by mikayla-grace** [comment]
Dirk knows Magick++, he will need to let you know how to do this.

Agreed, negating the alpha channel does not make sense in general.  However, if we skip operating on the alpha channels in general, we get unexpected behavior for other image processing algorithms.  This was one of the problems we tried to fix in IMv7.  With IMv6 we had too many special cases to get desired behavior.  We had to introduce the SyncChannels and numerous specialized defines.  For IMv7 we get a consistent clean and expected default way to handle channels with the option to modify the default behavior where it makes sense.

**Comment by mikayla-grace** [comment]
Perhaps a compromise.  Add SetV6CompatibilityMode() to Magick++, version 7.  With it, Magick++ tries to behave like it does for version 6.

**Comment by jeroen** [comment]
That will make things even more complex. If you really think the new default is appropriate, it should be documented more clearly. Perhaps add a C++ overload with a channel parameter to make it easier to override this default, as the client will probably almost always want to do this.

**Comment by mikayla-grace** [comment]
In the porting guide we say "-negate currently negates all channels, including alpha if present. As such you may need to use the -channel option to prevent alpha negation."  We will add a comment that this extends to the API's as well.

**Comment by dlemstra** [comment]
It seems that you will need to call `image.negateChannel` with `Magick::CompositeChannels` as it argument. You can hide that in your own api under `negate`.

**Comment by jeroen** [comment]
Ah OK I guess there is no STL wrapper for `negateChannel` that's why I didnt' notice

**Comment by jeroen** [comment]
Hmm actually it still doesn't work. This still negates the alpha channel (7.0.6.10)

```
  for(size_t i = 0; i < output->size(); i++)
    output->at(i).negateChannel(Magick::CompositeChannels);
```

**Comment by dlemstra** [comment]
Thought I used the CompositeChannels operator in Magick.NET to ignore the alpha channel but it turns out I didn't. You will need to do this:
```c++
Magick::ChannelType channels = (Magick::ChannelType)(Magick::CompositeChannels ^ Magick::AlphaChannel);
image.negateChannel(channels);
````

**Comment by dlemstra** [comment]
@jeroen Can you give it another try with the latest beta?

**Comment by jeroen** [comment]
Thanks @dlemstra. I couldn't get it to work via the STL api but this seems to work:

```c++
for(size_t i = 0; i < output->size(); i++)
    output->at(i).negateChannel(Magick::ChannelType(Magick::CompositeChannels ^ Magick::AlphaChannel));
```
