### ISSUE TITLE
ImageMagick stopped working on Windows 7

### ISSUE THREAD

**Issue by sergeevabc** [ImageMagick/ImageMagick#7296]
### ImageMagick version

7.1.1-32 x86 & x64

### Operating system, version and so on

Windows 7 x64

### Description

Aggrrhh! [7.1.1-31][1] works fine.

[1]: https://web.archive.org/web/20240423175708/https://imagemagick.org/script/download.php

### Steps to Reproduce

Run.

### Images

![2024-0507-2202 magick 7 error](https://github.com/ImageMagick/ImageMagick/assets/373718/3cc3c8ae-3fe2-41cc-90f0-62a32c88aac8)

**Comment by dlemstra** [comment]
And how can we reproduce this issue?

**Comment by sergeevabc** [comment]
@dlemstra The issue is far being completed.

Microsoft is a commercial company, so its decisions are dictated by profit. If the support does not promise profit, it will be canceled. It says nothing about the tool. A good hammer continues to hammer regardless of whether the warranty has expired. Microsoft calls it obsolete so that people get scared and run to spend money, and not because there is something revolutionary new in the new OSes (like 64-bit, NTFS instead of FAT32, and the ability to work with more than 4 GB RAM). This trick is called [planned obsolescence][1]. There are users, especially outside relatively well-off places, who don't care about support, because Windows 7 is polished and works properly.

Your résumé suggests that you're part of Microsoft's circle of evangelists, which makes you a person interested in having as few programs as possible run on "obsolete" Windows 7. This explains your haste to bury this request as soon as possible. But I'm sure there are some ImageMagick developers who may disagree with you, believing that this program should serve as many people as possible as an alternative to heavy and expensive GUI programs. So please re-open the issue and let others speak.

[1]: https://en.wikipedia.org/wiki/Planned_obsolescence

**Comment by fmw42** [comment]
There is no way to test that to figure out what the issue is. The Imagemagick team does not have a Window 7 system.

**Comment by sergeevabc** [comment]
@fmw42 It's not a problem. In the open source world, we rely on users' computers as testing sites. I am ready to participate in testing. You just need to show the curiosity of the researcher, which is expected from real programmers, and see what has changed between the two recent builds (31 and 32).

**Comment by fmw42** [comment]
I will leave that to the IM developers. If one of them wants to contact you about further testing, that is great.  But I know they are very busy and have full-time jobs. So this is likely a low priority issue. But then again it is up to them.

**Comment by dlemstra** [comment]
It's interesting to read what kind of assumptions you are making. But as fmw42 said this is a project that we work on in our spare time. We don't have the time to figure out how to get Windows 7 running somewhere and then which part of the build or code has broken this. You are more than welcome to figure that out yourself and propose a patch to allow backwards compatibility with Windows 7.

**Comment by sergeevabc** [comment]
Programming is not and will never be my area of expertise, so I can only send signals like a bug report or an idea for improvement, which is what I've been doing since the early 1990s. Or do you think that if a person is able to register on Github to post here, then they automatically acquire or claim that they have the necessary competencies to research the code? No, regular users see the Github issue tracker as a help desk, a support forum, a modern replacement for Usenet and Fidonet groups. 

I am well aware that open-source projects are mostly developed at the expense of the goodwill and free time of the participants. But developed for what? A catchy line in a profile, a reason to brag in a bar or to show off at conferences? Or is it to make technology more accessible to people, thereby making life easier? When you implement a change in the dark, you imagine that users might be happy about it. But here you encounter a live user of your tool who comes in pain and says that an established workflow is disrupted, so you do not need to imagine what can be useful, because your skills can be applied to solve a real problem. And it affects not even one, but still many people.

From my experience, this is what usually happens next: the developer is in no hurry to spit on someone else's pain, but on the contrary, shows empathy and tries to fix the situation, as, for example, in the case of [Foobar2000][1] media player. After all, if all the fuss is about adding a compilation flag or using a function that is supported on more systems, then why not?

To be more specific, I read reports about CreateFile2 error on [Stackoverflow][2] and they say this call is valid starting with Windows 8, but on Windows 7 you need to use CreateFileW. That is, if you make a [replacement in the executable][3], then ImageMagick works fine, but how does this call get into the executable in the first place? It's not in the source code (I couldn't find CreateFile2 string using Ripgrep). Therefore, it is reasonable to assume that among the [recent changes][4] there is an instruction that encourages the compiler to use modern calls instead of legacy ones. I can't specify a specific place in the code, but isn't there an expert among you who has already guessed what we are talking about?

> If you want to target a specific version of Windows that's older than the SDK you are using, you should explicitly set _WIN32_WINNT in your project settings.

[1]: https://hydrogenaud.io/index.php/topic,125795.0.html
[2]: https://www.google.com/search?q=%22CreateFile2%22+%22windows+7%22+site%3Astackoverflow.com
[3]: https://rentry.org/7fix#createfile2-error
[4]: https://github.com/ImageMagick/Website/blob/main/ChangeLog.md

**Comment by dlemstra** [comment]
I think you overestimate the amount of people that work on this project. And you also underestimate what you can do to help us solve this. Explaining me in detail what I need to do to add support for Windows 7 saves me a lot of time. I suspect that something has changed in the Windows SDK that we are using and that it now uses Windows 10 as the default target version of Windows. We can set `_WIN32_WINNT` in our projects to `0x0601` to allow support for Windows 7 for now. But be aware that we will be going to remove this if it causes issues in a future build.

**Comment by sergeevabc** [comment]
A quick follow-up.
The latest IM version 7.1.1-43 works fine on Windows 7. Hooray!

However, it's a bit tricky to see the header with version information now because you added a lot of info about switches. I would prefer the approach of LAME (MP3 encoder) developers who roll out basics by default and provide the rest via `--help`.

``` console
$ magick.exe
Version: ImageMagick 7.1.1-43 Q16-HDRI x64 a2d96f4:20241222 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Channel-masks(64-bit) Cipher DPC HDRI OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (194234435)
Usage: magick.exe tool [ {option} | {image} ... ] {output_image}
Usage: magick.exe [ {option} | {image} ... ] {output_image}
       magick.exe [ {option} | {image} ... ] -script {filename} [ {script_args} ...]

Image Settings:
  -adjoin              join images into a single multi-image file
...
```

**Comment by flawrist** [comment]
Aggrrhh! ImageMagick version [7.1.2-23](https://github.com/ImageMagick/ImageMagick/releases/tag/7.1.2-23) released 2 (two!) weeks ago works perfectly on Windows 7, but version 7.1.2-24 released 4 days ago does not.

## 7.1.2-23

``` console
$ ver && magick --version
Microsoft Windows [Version 6.1.7601]

Version: ImageMagick 7.1.2-23 Q8 x64 6a10c82:20260517 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/license/
Features: Channel-masks(64-bit) Cipher DPC OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (194435226)
```

## 7.1.2-24

![](https://github.com/user-attachments/assets/40fadc8b-7b43-4bc0-9b9f-5733b3b748c8)

**Comment by dlemstra** [comment]
We switched to Visual Studio 2026 and that is probably causing this. You can probably get it to work if you would compile ImageMagick yourself with Visual Studio 2022.

**Comment by flawrist** [comment]
> We switched to Visual Studio 2026

Why? Any features require this mandatory? What about [backward compatibility](https://en.wikipedia.org/wiki/Backward_compatibility)? 

> Compile ImageMagick yourself with Visual Studio 2022

Sure! Just send over a 3-week coding bootcamp voucher and a more powerful and roomy replacement for an IBM X61 laptop so that I can handle this task without creating 100500 issues about how to fit all the bricks together.

![](https://slimger.com/wp-content/uploads/2021/04/shutterstock_1915493305.jpg)

**Comment by dlemstra** [comment]
As an open-source project maintained by volunteers, we aren't able to maintain compatibility with every older environment indefinitely. Windows 7 reached end-of-life in January 2020. You have posted your original message two years ago so you have had more than enough time to switch to a newer version of Windows.

**Comment by flawrist** [comment]
God bless volunteers. But your logic is pure gymnastics: you’re treating Microsoft’s corporate decision as a law of physics.

End-of-life means Microsoft’s stopped patching. It doesn’t mean software evaporates, nor does it stop you from clicking “Build” in Visual Studio 2022. That compiler didn’t break — you broke compatibility by choice, trading a working toolchain for a shinier one that locks out older OS users.

It’s like a carpenter throwing away an 8mm drill bit because the factory stopped making that model, then announcing: “I don’t drill that size anymore, you’ve had two years to buy new furniture.” The holes didn’t become impossible — the carpenter simply became unwilling.

Name the C++23 feature critical for JPEG-to-PNG conversion. You can’t. There is no technical necessity here, only a habit of chasing version numbers and declaring everything older obsolete. Honesty would have suited you better than hiding behind Microsoft’s lifecycle policy.

The support you dropped was free: keep compiling with the toolchain that already worked. Instead, you actively embraced a bleeding-edge environment, cut off users, and now dress that up as inevitability while blaming them for not falling in line.

So no, the issue isn’t that Windows 7 is expired. It’s a developer whose empathy expires the moment a new Visual Studio version drops.

**Comment by dlemstra** [comment]
I decided to make the move to Visual Studio 2026 without realizing that it could cause this for you. In January next year Visual Studio 2022 is end of life and it will probably disappear from the runners  a while after that. So at some point we will be forced anyway to make the move. I don't want to invest extra time to move back to support your very specific situation. You have delayed the move for a long time so I would advise you to either make the move or to keep using `7.1.2-23`.

**Comment by flawrist** [comment]
> @dlemstra
In January next year Visual Studio 2022 is end of life …

LAME v4 (MP3 encoder released in July 2026) [was built with VS2026](https://github.com/Chocobo1/lame_win32-build/releases/tag/2026.07.17), it works fine on Windows 7.

![](https://github.com/user-attachments/assets/8eb41731-71fa-4013-9f1c-d042ef132a44)
