### ISSUE TITLE
Converting gif to webp does not meet expectations

### ISSUE THREAD

**Issue by jiuzhoucui** [ImageMagick/ImageMagick#7299]
### ImageMagick version

7.1.1-31

### Operating system

Linux

### Operating system, version and so on

centos

### Description

convert origin.gif des.webp

The result des.webp is wrong. You can compare with origin.gif as below.

![image](https://github.com/ImageMagick/ImageMagick/assets/102148284/c1f6c839-a8aa-4078-bcd9-9be0949c6118)

Please help to find out the reason, thanks!

### Steps to Reproduce

convert origin.gif des.webp

### Images

![origin](https://github.com/ImageMagick/ImageMagick/assets/102148284/32acc828-4f4a-4e14-88de-de948ff5721f)

**Comment by fmw42** [comment]
On IM 7, you should be using magick, not convert.  You did not say what version webp is being used. That could also make a difference.

**Comment by jiuzhoucui** [comment]
Use magick has the same result. 
Webp version: v1.3.2

Can you reproduced this problem or not?

**Comment by jiuzhoucui** [comment]
This works for me.  magick origin.gif -coalesce des.webp

**Comment by dlemstra** [comment]
That commit did not fix this. We will only do the "automatic" `-coalesce` call when the images have different dimensions. So you will need to add `-coalesce` for this specific file.

**Comment by jiuzhoucui** [comment]
OK. But I think you can do the "automatic" -coalesce call when an image have many frames.

**Comment by dlemstra** [comment]
Doing the automatic `-coalesce` call could result in incorrect artifacts that was reported in #5542.
