### ISSUE TITLE
[IM7] charcoal effect broken

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#730]
![frink](https://user-images.githubusercontent.com/216319/30019604-7b8ebaf0-9161-11e7-8db0-2a15c21afcd2.png)
Example:
```c++
#include <Magick++.h>

int main(){
  Magick::Image image("frink.png");
  image.charcoal();
  image.write(std::string("charcoal.png"));
}
```
Compile with:
```
g++ test.cpp $(pkg-config --cflags --libs Magick++)
./a.out
```

Output on IM7 gives:

![charcoal](https://user-images.githubusercontent.com/216319/30019614-842e6750-9161-11e7-9b3d-310ce676723c.png)

Output with IM6 gives:

![charcoal](https://user-images.githubusercontent.com/216319/30019714-cbb57df2-9161-11e7-89ad-6942f51701e9.png)

**Comment by mikayla-grace** [comment]
See the porting guide @ https://www.imagemagick.org/script/porting.php: the default is to update the RGBA channels, previously, in IMv6, the default was RGB. If you get results that differ from IMv6, you may need to specify -channel RGB on your command line (e.g. -level-colors option). This works for us:

`convert 30019604-7b8ebaf0-9161-11e7-8db0-2a15c21afcd2.png -channel RGB -charcoal RGB charcoal.png`

**Comment by jeroen** [comment]
I am using the C++ api, not the command line option. Perhaps you can update the C++ wrapper to do the right thing? Or is the image above the new intended result for `image.charcoal()`?

**Comment by dlemstra** [comment]
You will need to use charcoalChannel (https://github.com/ImageMagick/ImageMagick/commit/094941915d4e183d28cda5c015cba6a36779b66c) that will be available in the next release.
