### ISSUE TITLE
Using caption: to perform a "best fit" is not always working and causes text truncation

### ISSUE THREAD

**Issue by bullmoose20** [ImageMagick/ImageMagick#7304]
### ImageMagick version

7.1.1

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

& "magick.exe" -size 1400x600 -font "Comfortaa-Medium.ttf" -gravity center -fill black caption:"CONSPIRACY THEORY WITH JESSE VENTURA" -format "%[caption:pointsize]" info:

returns a size of 161

Which then when applied to the poster with:

"magick.exe" "Conspiracy Theory with Jesse Ventura (2009) _imdb-tt1572498_.jpg" -gravity center -background None -layers Flatten ( -font "Comfortaa-Medium.ttf" -pointsize "161" -fill "white" -size "1400x600" -background none caption:"CONSPIRACY THEORY WITH JESSE VENTURA" -trim -gravity south -extent "1400x600" ) -gravity south -geometry "+0+400" -quality 92% -composite "Conspiracy Theory with Jesse Ventura (2009) _imdb-tt1572498_-out.jpg"

gives you:
![Conspiracy_Theory_with_Jesse_Ventura_2009__imdb-tt1572498_](https://github.com/ImageMagick/ImageMagick/assets/12549033/6ef2bc43-4199-4055-9478-c2deabb3b4c7)

Here are some other values when we just adjust text string slightly and see how the value changed significantly:
![image (1)](https://github.com/ImageMagick/ImageMagick/assets/12549033/524ecfc1-b5cb-46a8-bc65-e941529c19af)

Also adjusting the box by 1 or 2 pixels will also fix the issue. 

As we are creating thousands of text overlay images, we encounter this problem. There is also a similar issue whereby the returned value is way too small (47) for when we want to perform the same caption command for the following text: "THE LORD OF THE RINGS: THE FELLOWSHIP OF THE RING". It should be around 106

& "magick" -size 1200x485 -font "Comfortaa-Medium.ttf" -gravity center -fill black caption:"THE LORD OF THE RINGS: THE FELLOWSHIP OF THE RING" -format "%[caption:pointsize]" info:
![LOTR](https://github.com/ImageMagick/ImageMagick/assets/12549033/aa620880-e248-4a4b-8a0a-7772d757f585)

[Comfortaa-Medium.zip](https://github.com/ImageMagick/ImageMagick/files/15269633/Comfortaa-Medium.zip)

### Steps to Reproduce

Steps outlined above

### Images

images and font shown above

**Comment by kevbentz** [comment]
![poster](https://github.com/ImageMagick/ImageMagick/assets/3792559/5070cb69-8dca-47a7-8730-7f545ac74506)

**Comment by kevbentz** [comment]
This is the expected result (achieved by manually adjusting the pointsize by -1 or adding 1 pixel to the text box width):
![poster](https://github.com/ImageMagick/ImageMagick/assets/3792559/ec620caa-420e-47f6-959b-c374ce1d0986)

**Comment by bullmoose20** [comment]
C:\Users\bullmoose20\ppm>ver

Microsoft Windows [Version 10.0.22621.3447]

C:\Users\bullmoose20\ppm>".\magick\magick.exe" -version
Version: ImageMagick 7.1.1-32 Q16-HDRI x64 178bb32:20240505 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Channel-masks(64-bit) Cipher DPC HDRI OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (193833135)

C:\Users\bullmoose20\ppm>".\magick\magick.exe" -size "2000x3000" xc:pink -background none "C:\Users\bullmoose20\ppm\test\testimage.png"

C:\Users\bullmoose20\ppm>".\magick\magick.exe" -size 1400x600 -font "C:\\Users\\bullmoose20\\ppm\\temp\\Comfortaa-Medium.ttf" -gravity center -fill black caption:"CONSPIRACY THEORY WITH JESSE VENTURA" -format "%[caption:pointsize]" info:
161
C:\Users\bullmoose20\ppm>".\magick\magick.exe" "C:\Users\bullmoose20\ppm\test\testimage.png" -gravity center -background none -layers Flatten ( -font "C:\\Users\\bullmoose20\\ppm\\temp\\Comfortaa-Medium.ttf" -pointsize "161" -fill "#0000FF" -size "1400x600" -background "#ACD7E6" caption:"CONSPIRACY THEORY WITH JESSE VENTURA" -trim -gravity south -extent "1400x600" ) -gravity south -geometry +0+"+300" -quality 92% -composite "C:\Users\bullmoose20\ppm\test\posterLongTextCAPS.jpg"

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
