### ISSUE TITLE
Bug in `MagickGetImageArtifacts`

### ISSUE THREAD

**Issue by 5ohue** [ImageMagick/ImageMagick#7309]
### ImageMagick version

7.1.1.32-1

### Operating system

Linux

### Operating system, version and so on

Arch Linux

### Description

It looks like there is a type in the `MagickGetImageArtifacts`.

In the function implementation [here](https://github.com/ImageMagick/ImageMagick/blob/main/MagickWand/magick-property.c#L637-L695) functions like `GetNextImageProperty` are used instead of `GetNextImageArtifact`. As a result, when you call `MagickGetImageArtifacts("*")` what you get are the image properties, not the artifacts.

Replacing the word `Property` with `Artifact` inside this function would probably solve this issue.

### Steps to Reproduce

Compiling and running this code shows the issue.

#### Code:

`example.c`
```c
#include <ImageMagick-7/MagickWand/MagickWand.h>

#define ThrowWandException(wand) \
    { \
        char \
        *description; \
        \
        ExceptionType \
        severity; \
        \
        description=MagickGetException(wand,&severity); \
        (void) fprintf(stderr,"%s %s %lu %s\n",GetMagickModule(),description); \
        description=(char *) MagickRelinquishMemory(description); \
        exit(-1); \
    }

int main(int argc, char ** argv) {
    MagickBooleanType status;

    MagickWand *magick_wand;

    if (argc != 2) {
        (void) fprintf(stdout,"Usage: %s image", argv[0]);
        exit(0);
    }

    MagickWandGenesis();
    magick_wand=NewMagickWand();
    status=MagickReadImage(magick_wand,argv[1]);
    if (status == MagickFalse) {
        ThrowWandException(magick_wand);
    }

    size_t num_of_artifacts = 0;
    char ** artifacts = MagickGetImageArtifacts(magick_wand, "*", &num_of_artifacts);
    if (artifacts == NULL) {
        ThrowWandException(magick_wand);
    }
    for (size_t i = 0; i < num_of_artifacts; ++i) {
        fprintf(stdout, "Artifact: %s\n", artifacts[i]);
    }

    magick_wand=DestroyMagickWand(magick_wand);
    MagickWandTerminus();
    return(0);
}
```

#### Compiling and running
```
clang example.c -o example `MagickWand-config --cflags --cppflags` `MagickWand-config --ldflags --libs`
./example some_image.jpg
```

This outputs something like this:
```
Artifact: date:create
Artifact: date:modify
Artifact: date:timestamp
Artifact: jpeg:colorspace
Artifact: jpeg:sampling-factor
```

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
