### ISSUE TITLE
rsvg-convert 

### ISSUE THREAD

**Issue by aelgn** [ImageMagick/ImageMagick#7312]
### ImageMagick version

7.1.1-32

### Operating system

Linux

### Operating system, version and so on

alpine 3.19.1

### Description

Upgrading our alpine docker image from 3.18.6 to 3.19.1 breaks svg to png conversion.

```
magick /tmp/test.svg -density 300x300 -units PixelsPerInch png8:qwop.png
magick: delegate failed `'rsvg-convert' -o '%o' '%i'' @ error/delegate.c/InvokeDelegate/1911.
magick: unable to open file '/tmp/magick-oTVMmSbCgZcrDyFBhon5-ycb7wAPBGAo': No such file or directory @ error/constitute.c/ReadImage/785.
```
Tested as root so permissions should not be a problem. Each time the command is run the referenced temp file name changes, which leads me to believe that imagemagick's temp file creation is incompatible alpine 3.19.1.

```
Version: ImageMagick 7.1.1-32 Q16-HDRI x86_64 22207 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo fftw fontconfig freetype gslib heic jng jpeg jxl lcms ltdl lzma pangocairo png ps raw rsvg tiff webp x xml zlib zstd
Compiler: gcc (13.2)
```

### Steps to Reproduce

* use alpine:3.19.1
* `magick /tmp/test.svg -density 300x300 -units PixelsPerInch png8:qwop.png`

**Comment by dlemstra** [comment]
It looks like you no longer have `rsvg-convert` installed on your system? Or maybe you had Inkscape installed and that is no longer available?

**Comment by aelgn** [comment]
Interesting and thank you. Neither rsvg-convert nor inkscape was installed on the previous alpine 3.18.x image. But it would seem that the `apk add imagemagick` was enough on alpine 3.18 to also install svg dependencies.
I have added to my alpine based Dockerfile: `apk add imagemagick-svg` which installs a load of dependecies - librsvg chief among them 👍
