### ISSUE TITLE
Outdated Magick++ Pixels documentation

### ISSUE THREAD

**Issue by unknown321** [ImageMagick/ImageMagick#7318]
### ImageMagick version

7.1.1-32

### Operating system

Linux

### Operating system, version and so on

Debian

### Description

Example on https://www.imagemagick.org/Magick++/Pixels.html is broken, see steps to reproduce.

### Steps to Reproduce

```shell
$ g++ \
	-DMAGICKCORE_HDRI_ENABLE=1 \
	-DMAGICKCORE_QUANTUM_DEPTH=8 \
	-DMAGICKCORE_CHANNEL_MASK_DEPTH=32 \
	-I./include/ImageMagick-7 \
	-L./lib \
	-lMagickCore-7.Q8HDRI \
	-lMagick++-7.Q8HDRI \
	-lMagickWand-7.Q8HDRI \
	-lgomp \
	main.c \
	./lib/libMagick++-7.Q8HDRI.a \
	./lib/libMagickWand-7.Q8HDRI.a \
	./lib/libMagickCore-7.Q8HDRI.a \
	/lib/x86_64-linux-gnu/libgomp.so.1 -o main

$ ./main 
terminate called after throwing an instance of 'Magick::ErrorMissingDelegate'
  what():  main: no encode delegate for this image format `XC' @ error/constitute.c/WriteImage/1409
Aborted
```

**Comment by urban-warrior** [comment]
The example works for us per the documentation.   We built the source as recommended:

```
$ c++ `Magick++-config --cxxflags --cppflags` -O2 -o demo demo.cpp `Magick++-config --ldflags --libs`
```

Verify you have support for the XC: image format with this command:

```
$ identify -list format
```

We assume ImageMagick is installed in `/usr`.  If instead its `/usr/local`, you'll need this command before you compile the source:

```
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
````

**Comment by unknown321** [comment]
My bad, IM lacks XC write support:

```shell
$ ./magick -list format | grep "XC\*"
       XC* r--   Constant image uniform color
```

**Comment by unknown321** [comment]
In fact, my problem was not XC support.

As far as I remember, I was trying to run modified example, goal was to fill an image with color.

Image constructor defaults to XC/Canvas format, which [has no encoder, only decoder](https://github.com/ImageMagick/ImageMagick/blob/19bfab8f05bf84734bbdc280c6eb2e5f984c5e40/coders/xc.c#L185)

To fix that, I added magick like this: 

```cpp
    void FlatColorImage(const Magick::Geometry &g, const Magick::Color &color) {
        Magick::Blob blob;
        auto image = Magick::Image(g, color);
        image.magick("RGBA");
        image.fillColor(color);
        image.draw(Magick::DrawableRectangle(0, 0, g.width(), g.height()));
        image.write(&blob);
}
```
