### ISSUE TITLE
imagemagick.org is down

### ISSUE THREAD

**Issue by oleghalin** [ImageMagick/ImageMagick#7319]
### ImageMagick version

-

### Operating system

Linux

### Operating system, version and so on

-

### Description

[imagemagick.org](https://www.imagemagick.org/) currently is down

### Steps to Reproduce

visit [imagemagick.org](https://www.imagemagick.org/)

**Comment by dlemstra** [comment]
Also discussed here: #4402. We are aware that it's down but we don't know when this will come available again.
