### ISSUE TITLE
"Use to_string instead of our custom implementation" - Issue with old compiler on AIX

### ISSUE THREAD

**Issue by niclet** [ImageMagick/ImageMagick#7322]
### ImageMagick version

7.1.1-32

### Operating system

Other (enter below)

### Operating system, version and so on

AIX 7.2 TL2 

### Description

Not really a bug, but an issue with old compiler on AIX 7.2 (xlC 16) which don't support C++11
The use of "to_string" from std::string is not supported on old compiler.
Do you think it could be feasible to keep previous implementation under #ifdef ?

### Steps to Reproduce

"Magick++/lib/SecurityPolicy.cpp", line 35.9: 1540-0274 (S) The name lookup for "to_string" did not find a declaration.

**Comment by dlemstra** [comment]
We can revert this patch. I wasn't aware this wasn't support in C++11.
