### ISSUE TITLE
identify outputting incorrect sizes for ico file

### ISSUE THREAD

**Issue by elachlan** [ImageMagick/ImageMagick#7341]
### ImageMagick version

Version: ImageMagick 7.1.1-32 Q16-HDRI x86_64 e1de8c5eb:20240505

### Operating system

Linux

### Operating system, version and so on

5.15.146.1-microsoft-standard-WSL2

### Description

`identify` and `convert` are outputting incorrect/corrupt data. `icotool` is reporting different sizes from `identify` for indexes 3/5 (icotool indexes 4/6).

`identify`
```
256_1.ico[0] PNG 505x308 505x308+0+0 8-bit sRGB 13030B 0.000u 0:00.009
256_1.ico[1] ICO 202x123 202x123+0+0 8-bit sRGB 0.000u 0:00.009
256_1.ico[2] PNG 707x431 707x431+0+0 8-bit sRGB 16711B 0.000u 0:00.005
256_1.ico[3] ICO 148x148 148x148+0+0 8-bit sRGB 0.000u 0:00.004
256_1.ico[4] PNG 606x370 606x370+0+0 8-bit sRGB 13120B 0.000u 0:00.002
256_1.ico[5] ICO 47x47 47x47+0+0 8-bit sRGB 0.000u 0:00.002
256_1.ico[6] PNG 808x492 808x492+0+0 8-bit sRGB 805702B 0.000u 0:00.000
```

`icotool`
```
--icon --index=1 --width=505 --height=308 --bit-depth=32 --palette-size=0
--icon --index=2 --width=202 --height=123 --bit-depth=32 --palette-size=0
--icon --index=3 --width=707 --height=431 --bit-depth=32 --palette-size=0
--icon --index=4 --width=404 --height=246 --bit-depth=32 --palette-size=0
--icon --index=5 --width=606 --height=370 --bit-depth=32 --palette-size=0
--icon --index=6 --width=303 --height=185 --bit-depth=32 --palette-size=0
--icon --index=7 --width=808 --height=492 --bit-depth=32 --palette-size=0
```

We get corruption on the differing indexes if we use `convert` with:
```
convert 256_1.ico 256_1-d%.png
```

We are attempting to compress file sizes for winforms at: https://github.com/dotnet/winforms/pull/11375

### Steps to Reproduce

```
identify 256_1.ico
icotool -l 256_1.ico
```

### Images

https://github.com/dotnet/winforms/blob/f53f153808bbbaddda3f0c1e994e8a3b5cc085a9/src/System.Windows.Forms.Design/src/Resources/System/WinForms/Design/256_1.ico

**Comment by dlemstra** [comment]
Are you sure you are working with ImageMagick 7? I just pushed a patch to correct the scene number. I was getting this with the latest commit in the main repository:

```
I:\issues\im7\7341>identify 256_1.ico
256_1.ico[0] PNG 505x308 505x308+0+0 8-bit sRGB 13030B 0.007u 0:00.007
256_1.ico[1] ICO 202x123 202x123+0+0 8-bit sRGB 0.007u 0:00.006
256_1.ico[1] PNG 707x431 707x431+0+0 8-bit sRGB 16711B 0.005u 0:00.004
256_1.ico[1] ICO 148x148 148x148+0+0 8-bit sRGB 0.005u 0:00.005
256_1.ico[2] PNG 606x370 606x370+0+0 8-bit sRGB 13120B 0.003u 0:00.003
256_1.ico[1] ICO 47x47 47x47+0+0 8-bit sRGB 0.003u 0:00.003
256_1.ico[3] PNG 808x492 808x492+0+0 8-bit sRGB 805702B 0.003u 0:00.002
```

**Comment by elachlan** [comment]
256_1.ico[1] ICO 148x148 148x148+0+0 8-bit sRGB 0.005u 0:00.005
256_1.ico[1] ICO 47x47 47x47+0+0 8-bit sRGB 0.003u 0:00.003 

These two lines I think are wrong. If you open it in visual studio you get the real resolutions. It's very strange.

**Comment by dlemstra** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

This is the new output:

```
I:\issues\im7\7341>identify 256_1.ico
256_1.ico[0] PNG 505x308 505x308+0+0 8-bit sRGB 13030B 0.017u 0:00.017
256_1.ico[1] ICO 202x123 202x123+0+0 8-bit sRGB 0.018u 0:00.017
256_1.ico[2] PNG 707x431 707x431+0+0 8-bit sRGB 16711B 0.016u 0:00.015
256_1.ico[3] ICO 404x246 404x246+0+0 8-bit sRGB 0.016u 0:00.015
256_1.ico[4] PNG 606x370 606x370+0+0 8-bit sRGB 13120B 0.008u 0:00.007
256_1.ico[5] ICO 303x185 303x185+0+0 8-bit sRGB 0.008u 0:00.007
256_1.ico[6] PNG 808x492 808x492+0+0 8-bit sRGB 805702B 0.003u 0:00.002
```

**Comment by elachlan** [comment]
Amazing! Thank you so much!
