### ISSUE TITLE
Test fails for Microsoft Windows (24-bit) bitmap image file

### ISSUE THREAD

**Issue by arjendekorte** [ImageMagick/ImageMagick#7344]
### ImageMagick version

7.1.1-33

### Operating system

Linux

### Operating system, version and so on

openSUSE Tumbleweed

### Description

This version fails on one of the tests:
```
[  216s] t/write.t ......... 
[  216s] 1..32
[  216s] AVS X image file ...
[  216s] ok 1
[  216s] Microsoft Windows bitmap image file ...
[  216s] ReadImage()
[  216s] Image: BMP:input.bmp, signatures do not match.
[  216s]      Expected: d7324c919f04f4c118da68061a5dbb3f07ebab76b471ecfb0ac822453f677983
[  216s]      Computed: a0c5566d67ad974ba31f6f5d9ef1661b2613b60ac934f2339a2efafed1ecb68b
[  216s]      Depth:    16
[  216s] not ok 2
[  216s] Microsoft Windows 24-bit bitmap image file ...
[  216s] ReadImage()
[  216s] Image: BMP:input.bmp24, signatures do not match.
[  216s]      Expected: fb6fc68beb3b1001c5ebaa671c8ac8fddea06995027127765ff508f77723cc52
[  216s]      Computed: 74136c90d3e699ea5bcbf4aa733aff0dc822b6af72fce00f0c7647bcb0d49f66
[  216s]      Depth:    16
[  216s] not ok 3
```

### Steps to Reproduce

Build and run tests. This worked correctly up to 7.1.1-32 but now fails in 7.1.1-33.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

**Comment by rhendric** [comment]
Hi, is it possible that this is an actual bug and not just a test that needs to be updated?

I grabbed the input.bmp from the tests and ran `magick BMP:input.bmp BMP:output.bmp` with both old and new versions of ImageMagick. The resulting output.bmp is identical. Running `magick identify -format %A input.bmp` returns `Undefined` with both old and new versions. However, running `magick identify -format %A output.bmp`—on the same output.bmp—returns `Undefined` with ImageMagick 7.1.1-32 and `Blend` with ImageMagick 7.1.1-33. The new ImageMagick build reports that the output file has a transparency channel that the input file does not, despite no transformations being requested. I find this surprising; should I?

**Comment by dlemstra** [comment]
In earlier version we did not detect the alpha channel properly. You should also now see `Blend` with `magick identify -format %A input.bmp`?

**Comment by dlemstra** [comment]
It was or is? And without your `input.bmp` file I cannot tell you why this is happening.

**Comment by rhendric** [comment]
In the context of this issue, we're talking about https://github.com/ImageMagick/ImageMagick/blob/5bbfc6164b65e6fe8af515d2d4fd1631072e5ca2/PerlMagick/t/input.bmp

As my [previous comment](https://github.com/ImageMagick/ImageMagick/issues/7344#issuecomment-2133986413) explained, both old and new versions of ImageMagick have the same behavior on input.bmp.

**Comment by rhendric** [comment]
I'm one of the maintainers of the ImageMagick package on NixOS, and not knowing whether this upgrade is bugged has been holding me back from releasing it. It'd be nice to get some clarity about whether this change in behavior is intentional.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
