### ISSUE TITLE
No auto orient in magick cmd and way to processing nd array and combine in python

### ISSUE THREAD

**Issue by juhonkang** [ImageMagick/ImageMagick#7359]
### ImageMagick version

7.1.1

### Operating system

Linux

### Operating system, version and so on

Ubuntu

### Description

I try to find a way to processing big data nd array with python. 
Besides the way of save it as tmp file and run parallely with pool. 
Any other way?

### Steps to Reproduce

magick -auto-orient datasets/rotation.jpg x.jpg

magick: no images found for operation `-auto-orient' at CLI arg 1 @ error/operation.c/CLIOption/5479.

**Comment by dlemstra** [comment]
Your command is in an incorrect order. You should do this instead: `magick datasets/rotation.jpg -auto-orient x.jpg`

**Comment by juhonkang** [comment]
Yes, it run, but the result have no changed with auto orient :( Some issues
here :(

**Comment by fmw42** [comment]
Post and example image that fails.

**Comment by juhonkang** [comment]
@fmw42 Sure, this is an part of document. 
![unrotated](https://github.com/ImageMagick/ImageMagick/assets/67153600/71368ff9-28e5-4726-9498-a0279a56a091)

**Comment by fmw42** [comment]
The image has a tag of:

`Orientation: TopLeft`

which is why it does not change.  Some one or some tool has changed it or set it that way.

How was this image acquired?

**Comment by juhonkang** [comment]
@fmw42 It has been extract from an PDF, so what is the solution for that? Could you let me know?

**Comment by fmw42** [comment]
Post the PDF and explain how the image was extracted?

**Comment by juhonkang** [comment]
Could you give me the email, I will send you via Gmail, not post publicly
to everyone :)

**Comment by fmw42** [comment]
fmw at alink dot net
