### ISSUE TITLE
Wrong APNG frame delay

### ISSUE THREAD

**Issue by Yay295** [ImageMagick/ImageMagick#7371]
### ImageMagick version

7.1.1-33

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

The duration of the second frame in the attached image is wrong. The delay numerator for both frames is 16384, while the denominator is 4096 and 16384. The frame durations then should be 400 and 100.

### Steps to Reproduce

```batch
> magick identify -format %T\n apng:different_durations.png
400
99
```

### Images

![different_durations](https://github.com/ImageMagick/ImageMagick/assets/8922038/b8b3ee6a-1296-4538-bed3-d0fa71117597)

**Comment by Yay295** [comment]
It shouldn't be. 16384 / 16384 is 1; there's nothing to round.

**Comment by dlemstra** [comment]
Turns out it was a rounding error. I just pushed a patch to fix that and this will be the output in the next version:
```
I:\issues\im7\7371>magick identify -format %T\n apng:different_durations.png
400
100
```
