### ISSUE TITLE
Exception encountered when trying to compare 2 pdf files. 

### ISSUE THREAD

**Issue by TylerJohnsonGamePlan** [ImageMagick/ImageMagick#7376]
### ImageMagick version

7.1.1-33

### Operating system

Linux

### Operating system, version and so on

Linux AMD64

### Description

Been using Image Magick for a while now in golang in a built docker container. We have a program that will compare pages of pdfs and call out what the differences are to see at a glance. Recently we noticed that this started failing for us around the time the 7.1.1-32 release came out with the following exception being thrown.

```
pdfdiff: MagickCore/string.c:1200: GetStringInfoDatum: Assertion `string_info->signature == MagickCoreSignature' failed.
SIGABRT: abort
PC=0x7f70cee43e2c m=4 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 34 gp=0xc0000828c0 m=4 mp=0xc00004f808 [syscall]:
runtime.cgocall(0x666dc0, 0xc000198810)
	/usr/local/go/src/runtime/cgocall.go:157 +0x4b fp=0xc0001987e8 sp=0xc0001987b0 pc=0x4134ab
gopkg.in/gographics/imagick.v3/imagick._Cfunc_MagickReadImage(0x7f707c000b70, 0x7f707c0099e0)
	_cgo_gotypes.go:6686 +0x4b fp=0xc000198810 sp=0xc0001987e8 pc=0x660fcb
gopkg.in/gographics/imagick.v3/imagick.(*MagickWand).ReadImage.func2(0xc00019c080?, 0x7f707c0099e0)
	/go/pkg/mod/gopkg.in/gographics/imagick.v3@v3.7.0/imagick/magick_wand_image.go:1933 +0x4d fp=0xc000198850 sp=0xc000198810 pc=0x6620cd
gopkg.in/gographics/imagick.v3/imagick.(*MagickWand).ReadImage(0xc0001a6018, {0xc00019c080?, 0x9dd7d168d?})
	/go/pkg/mod/gopkg.in/gographics/imagick.v3@v3.7.0/imagick/magick_wand_image.go:1933 +0x6d fp=0xc0001988a0 sp=0xc000198850 pc=0x661fed
main.contrastPdfsWithMagic({0x6e4dea, 0x11}, {0x6e4dfb, 0x11})
	/app/main.go:52 +0x75 fp=0xc000198990 sp=0xc0001988a0 pc=0x662b95
main.Diff({0x75dce0?, 0x2?}, 0xc000184240?)
	/app/main.go:41 +0x97 fp=0xc000198a10 sp=0xc000198990 pc=0x6629b7
net/http.HandlerFunc.ServeHTTP(0xc0001a2120?, {0x75d720?, 0xc0001ae000?}, 0x4c2a2f?)
	/usr/local/go/src/net/http/server.go:2166 +0x29 fp=0xc000198a38 sp=0xc000198a10 pc=0x6392a9
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000fe000, {0x75d720, 0xc0001ae000}, 0xc0001a2000)
	/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x1e2 fp=0xc000198b60 sp=0xc000198a38 pc=0x65d9c2
net/http.serverHandler.ServeHTTP({0xc000184090?}, {0x75d720?, 0xc0001ae000?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3137 +0x8e fp=0xc000198b90 sp=0xc000198b60 pc=0x63b70e
net/http.(*conn).serve(0xc000188000, {0x75dce0, 0xc00009ef90})
	/usr/local/go/src/net/http/server.go:2039 +0x5e8 fp=0xc000198fb8 sp=0xc000198b90 pc=0x637ee8
net/http.(*Server).Serve.gowrap3()
	/usr/local/go/src/net/http/server.go:3285 +0x28 fp=0xc000198fe0 sp=0xc000198fb8 pc=0x63bf28
runtime.goexit({})
	/usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000198fe8 sp=0xc000198fe0 pc=0x47ae81
created by net/http.(*Server).Serve in goroutine 1
	/usr/local/go/src/net/http/server.go:3285 +0x4b4
```

We have updated to latest image magick version as well as golang image magick wrapper with no change. Have tried reading in the pdfs using different methods (ReadImage, ReadImageBlob, ReadImageFile) but always with the same MagickCoreSignature assert.

### Steps to Reproduce

Attached is a zip file of a small program that can reproduce the issue. Building and running the docker image and hitting the diff endpoint will result in the assertion happening.

```
docker build --tag pdfdiff .
docker run -p 8080:8080 pdfdiff
curl http://localhost:8080/diff
```

Any help or advice that can be given is greatly appreciated. Thank you.

[pdfDiff.zip](https://github.com/user-attachments/files/15682478/pdfDiff.zip)

**Comment by dlemstra** [comment]
You should only get the message when there is something wrong in your setup. It looks like you are mixing two different ImageMagick versions.

**Comment by TylerJohnsonGamePlan** [comment]
> You should only get the message when there is something wrong in your setup. It looks like you are mixing two different ImageMagick versions.

Thank you for the quick reply. I will explore our setups in more detail and double check everything.

**Comment by farvour** [comment]
We recently rebuilt ImageMagick against 7.1.1-36 and are seeing a similar issue.

Here's how we are building it, in case it helps anyone:

```
###############
# IMAGEMAGICK #
###############

ENV IMAGE_MAGICK_VERSION=7.1.1-36

# This dogfoods the package so we know the linked libs are working.
RUN echo "=== Install JPEG encoding lib for ImageMagick deb..." \
    && cd ${BUILD_FPM_OUT_DIR} \
    && dpkg -i jpeg-encoding-lib_1.0.0-${BUILD_ITERATION}*.deb

RUN echo "=== Install Libheif for ImageMagick deb..." \
    && cd ${BUILD_FPM_OUT_DIR} \
    && dpkg -i libheif_${HEIF_VERSION}-${BUILD_ITERATION}*.deb

RUN echo "=== Compile ImageMagick..." \
    && mkdir -p ${BUILD_DIR}/imagemagick ${BUILD_DIR}/imagemagick-out \
    && curl -L https://github.com/ImageMagick/ImageMagick/archive/${IMAGE_MAGICK_VERSION}.tar.gz | tar xz -C ${BUILD_DIR}/imagemagick \
    && cd ${BUILD_DIR}/imagemagick/ImageMagick-${IMAGE_MAGICK_VERSION} \
    && ./configure --prefix=/usr/local --with-gslib --with-heic=yes --with-webp=yes --with-jpeg=yes --with-png=yes --with-jp2=yes --with-modules \
    && make \
    && make DESTDIR=${BUILD_DIR}/imagemagick-out install
```


Then when we try to use a working interactive sample (that worked in prior versions):

```
root@8bb9abe979f9:/app# magick -version
Version: ImageMagick 7.1.1-36 Q16-HDRI x86_64 58ddb87ca:20240726 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): gslib heic jbig jng jpeg ltdl lzma png ps tiff zlib
Compiler: gcc (9.4)
root@8bb9abe979f9:/app# magick -density 300 custom/vendors/aws/tests/test_interactive_file.pdf output1.pdf
magick: MagickCore/string.c:1200: GetStringInfoDatum: Assertion `string_info->signature == MagickCoreSignature' failed.
Aborted
```

**Comment by jonn** [comment]
I ran into this recently, trying to update to the latest ImageMagick, and rolled back to the previously used 7.1.1-16. I've now walked up the releases to confirm that this bug was introduced in 7.1.1-31.

I've now locked us in at 7.1.1-30, which is working for us without issue.

**Comment by dlemstra** [comment]
I am still not able to reproduce this issue.

**Comment by jonn** [comment]
Looking for commonalities to help reproduction...

Like @TylerJohnsonGamePlan, I am using the MagickWand api inside a Go app deployed on a Docker image.

It looks like @farvour is building in a Dockerfile as well, though he is demonstrating with the magick cli bin, so Go is not required to reproduce.

Like @farvour, @TylerJohnsonGamePlan and I are using Debian as the Docker image os as it is what the official golang images are built with. I am using bullseye, @TylerJohnsonGamePlan's attached example program uses bookworm.

And we're all experiencing the assertion abort when reading in a PDF. So gslib, right? With bullseye, I have libgs 9.53.3. It looks like bookworm comes with libgs 10.0.0.

**Comment by farvour** [comment]
> Looking for commonalities to help reproduction...
> 
> Like @TylerJohnsonGamePlan, I am using the MagickWand api inside a Go app deployed on a Docker image.
> 
> It looks like @farvour is building in a Dockerfile as well, though he is demonstrating with the magick cli bin, so Go is not required to reproduce.
> 
> Like @farvour, @TylerJohnsonGamePlan and I are using Debian as the Docker image os as it is what the official golang images are built with. I am using bullseye, @TylerJohnsonGamePlan's attached example program uses bookworm.
> 
> And we're all experiencing the assertion abort when reading in a PDF. So gslib, right? With bullseye, I have libgs 9.53.3. It looks like bookworm comes with libgs 10.0.0.

We're specifically using Ubuntu 20.04. I'll try and remember tomorrow to grab a sample of the interactive PDF file we're using in this unit test too. Maybe there is some commonality with that.

**Comment by maurice-ellis** [comment]
I'm running into the same issue with the latest 7.1.1-38. I had no problem converting images to PDF previously, but just tried to use Magick on an empty PDF (opens in Acrobat and Mac Preview) and encountered the error. I built from source back to 7.1.1-30 as @jonn mentioned and no issue.

**Comment by fmw42** [comment]
Post your command line and your PDF files.

**Comment by fmw42** [comment]
@maurice-ellis I have no issue with using your Empty.pdf on IM 7.1.1.38 on Mac OSX Ventura.  I can convert to PDF or PNG and open them. I can display them in Imagemagick with magick display. 

What exactly is your issue?

**Comment by maurice-ellis** [comment]
Ran into the assertion error mentioned above. I built from source for AWS Lambda for NodeJS Docker container and a container I used to build this. I was stunned that it had an issue with a PDF that was empty. It works with no problem on -30. I didn't try later versions before -38. Not trying to spend my day compiling lol. I had no issue working with images, but this PDF encountered the issue.

I'm just reporting that I experienced the same issue.

**Comment by fmw42** [comment]
Perhaps related to your Docker build?

**Comment by maurice-ellis** [comment]
It would be an AWS issue I guess because I'm using their based image for compilining and then it runs into the error on their container used to test Lambda functions. One thing for sure, same containers, -30 works with the same files.

**Comment by jonn** [comment]
@fmw42 - you may be on to something, as we are all using Docker images. But I am not using any AWS infrastructure. And let me be clear, the only thing that changes in my setup between a working ImageMagick and a broken ImageMagick is the version of ImageMagick. This sounds like it is true of @maurice-ellis's environment as well.

Here is how I am setting up my OS and building ImageMagick, from my Dockerfile:
<pre><code># Specify parent image
FROM golang:1.23-bullseye

# Ignore APT warnings about not having a TTY
ENV DEBIAN_FRONTEND noninteractive

# Update packages and grab the libraries we need
RUN apt-get update \
    && apt-get install -y \
        wget build-essential \
        pkg-config \
        --no-install-recommends \
    && apt-get -q -y install \
        libjpeg-dev \
        libpng-dev \
        libtiff-dev \
        libgif-dev \
        libopenjp2-7-dev \
        libbz2-1.0 \
        libx11-6 \
        libgs9 \
        libgs9-common \
        libgs-dev \
        fontconfig \
        gsfonts gsfonts-x11 \
        libfreetype6 \
        --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

ARG IMAGEMAGICK_PROJECT=ImageMagick
ARG IMAGEMAGICK_VERSION=7.1.1-30
ENV IMAGEMAGICK_VERSION=$IMAGEMAGICK_VERSION

# Get and build ImageMagick to our requirements
RUN cd && \
        wget https://github.com/ImageMagick/${IMAGEMAGICK_PROJECT}/archive/${IMAGEMAGICK_VERSION}.tar.gz && \
        tar xvzf ${IMAGEMAGICK_VERSION}.tar.gz && \
        cd ImageMagick* && \
        ./configure \
            --without-magick-plus-plus \
            --without-perl \
            --disable-openmp \
            --with-gvc=no \
            --disable-docs \
            --with-bzlib=yes \
            --with-jpeg=yes \
            --with-openjp2=yes \
            --with-png=yes \
            --with-tiff=yes \
            --with-fontconfig=yes \
            --with-freetype=yes \
            --with-gslib=yes && \
        make -j$(nproc) && make install && \
        ldconfig /usr/local/lib
</code></pre>

Changing the IMAGEMAGICK_VERSION to 7.1.1-31 or above results in the ImageMagick falling over when opening a PDF.

@fmw42 - do you see anything in this setup that would be problematic for 7.1.1-31 but not 7.1.1-30?

**Comment by dlemstra** [comment]
Thanks for providing the Dockerfile. I just pushed a commit that resolves this issue. The XMP profile was freed because it could not be validated and that caused an issue when we were trying to use it afterwards. Swapping the order fixed this bug.

**Comment by maurice-ellis** [comment]
Amazing, thanks all.
