### ISSUE TITLE
Edge detection gives very different output on IM6 vs IM7

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#738]
Original image:

![frink](https://user-images.githubusercontent.com/216319/30019604-7b8ebaf0-9161-11e7-8db0-2a15c21afcd2.png)

Using the STL for image detection:

```cc
for_each ( output->begin(), output->end(), Magick::edgeImage(radius));
```

IM 6.9.9.10 gives:
![edge6](https://user-images.githubusercontent.com/216319/30170142-9810993e-93ee-11e7-90ae-f2056a9ecfa9.png)

IM 7.0.7.0 gives:
![edge7](https://user-images.githubusercontent.com/216319/30170217-c5368ee6-93ee-11e7-9bf0-80f8311d340a.png)

**Comment by mikayla-grace** [comment]
See #729.  The alpha channel is edged by default.  Mask the alpha channel and you will get similar results to IMv6.
