### ISSUE TITLE
converting animated webp produces frames with artifacts

### ISSUE THREAD

**Issue by dzek69** [ImageMagick/ImageMagick#7386]
### ImageMagick version

7.1.1-33

### Operating system

Linux

### Operating system, version and so on

KDE Neon 6

### Description

When converting this image: https://mathiasbynens.be/demo/animated-webp-supported.webp to frames imagick produces very broken frames with a lot of artifacts:
![mm-1](https://github.com/ImageMagick/ImageMagick/assets/4936805/b84cda8b-aa05-42fd-84c5-1ebcc2765d05)
![mm-2](https://github.com/ImageMagick/ImageMagick/assets/4936805/a8427fb9-1b01-48bc-a6b5-99b25578a37f)
![mm-3](https://github.com/ImageMagick/ImageMagick/assets/4936805/b62c2914-1519-424d-8806-104af83ae4c5)

only 1st and 11th frame (one before last frame) are extracted as expected

This happens on all of these versions:
ImageMagick AppImage 7.1.1-33 on KDE Neon 6
ImageMagick from `apt`: 6.9.11-60 on KDE Neon 6
ImageMagick from `apk`: 7.1.1-32 on Alpine Linux 3.20.0 (inside Docker)

### Steps to Reproduce

1. Download https://mathiasbynens.be/demo/animated-webp-supported.webp
2. Run `convert animated-webp-supported.webp mm.png`

### Images

[animated-webp-supported.zip](https://github.com/user-attachments/files/15751309/animated-webp-supported.zip)

**Comment by dlemstra** [comment]
This is the expect behavior. I think you will want to add `-coalesce`: `magick animated-webp-supported.webp -coalesce mm.png`

**Comment by dzek69** [comment]
Hmm. Okay. I did some reading and I understand why artifacts were produced, but I don't understand this design choice to make this behavior default.

My initial confusion also comes from the fact that: `convert animated-webp-supported.webp file.mp4` (so mp4 target) DOES work as I would expect it on 6.9.11-60, but it does not on 7.1.1-32 (can't test 7.1.1-33 because of #6890).

But it produces the "broken" images on all versions if I want to extract frames to png.

Thanks for your clarification, I guess if that's intended behavior then it's all fine.
