### ISSUE TITLE
Reading a video file leaves behind a temporary file on Windows

### ISSUE THREAD

**Issue by reima** [ImageMagick/ImageMagick#7389]
### ImageMagick version

7.1.1-33

### Operating system

Windows

### Operating system, version and so on

Windows 11 23H2

### Description

Reading a video file via the C or C++ API of ImageMagick on Windows will leave behind a copy of the file in the temporary directory.

I've identified that two temporary files are created in `ReadVIDEOImage`:
https://github.com/ImageMagick/ImageMagick/blob/05a551ae7994b1aa0628b35227da74012a3a6c2b/coders/video.c#L253-L255

`read_info->unique` is used as the output file path for the delegate. `read_info->filename` is used as the input file path for the delegate. Note that `AcquireUniqueSymbolicLink` creates a copy of the file when running on Windows.

After building the delegate command line, `read_info->filename` is overwritten with the content of `read_info->unique`:
https://github.com/ImageMagick/ImageMagick/blob/05a551ae7994b1aa0628b35227da74012a3a6c2b/coders/video.c#L262-L263

The two temporary files should in theory be removed in these lines:
https://github.com/ImageMagick/ImageMagick/blob/05a551ae7994b1aa0628b35227da74012a3a6c2b/coders/video.c#L272-L273

But as `read_info->filename` has already been overwritten, this will not remove the temporary file.

Note that `MagickCoreTerminus` will delete this temporary file. This is why the problem is not directly observable with the ImageMagick command line tools.

### Steps to Reproduce

The following trivial Magick++ program reproduces the problem:

```cpp
#include <Magick++.h>
#include <iostream>

int main(int argc, char **argv)
{
    Magick::InitializeMagick(*argv);

    try
    {
        Magick::Image image;
        image.read("F:\\test.mp4[0]"); // any file that ImageMagick identifies as video will do
    }
    catch (Magick::Exception& error)
    {
        std::cout << "Error: " << error.what() << std::endl;
    }

    // Temporary file still exists.

    Magick::TerminateMagick();

    // Temporary file has been deleted.
}
```

**Comment by dlemstra** [comment]
Thanks for reporting this and the detailed information. I just pushed a patch to make sure this will be fixed in the next release.

**Comment by reima** [comment]
I can confirm that the issue is fixed on the main branch.

As always, thank you very much for the swift response! I really appreciate it.
