### ISSUE TITLE
ImageMagick fails to parse an XBM image in two cases

### ISSUE THREAD

**Issue by peteroupc** [ImageMagick/ImageMagick#7406]
### ImageMagick version

7.1.1-26

### Operating system

Linux

### Operating system, version and so on

Fedora 40

### Description

There are two circumstances I noticed where ImageMagick fails to parse an XBM image file.

First: Where the image defines a hotspot (`_x_hot` and `_y_hot`), as allowed in [`XReadBitmapFile`](https://www.x.org/releases/current/doc/libX11/libX11/libX11.html#Manipulating_Bitmaps):

```
#define xbm_width 32
#define xbm_height 2
#define xbm_x_hot 0
#define xbm_y_hot 0
static char xbm_bits[] = {
   0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00};
```

Second: Where one or more lines appear after the `#define` statements:

```
#define xbm2_width 8
#define xbm2_height 1

static char xbm2_bits[] = {
 0xFF
};
```

I don't know, and don't know how to check, whether `XReadBitmapFile` can parse an XBM image file in either circumstance.  Another circumstance where ImageMagick fails to parse XBM is given in another issue: #6775.

### Steps to Reproduce

Save the first block of text as `xbm1.xbm` and run `magick xbm1.xbm xbm1.png`.

Save the second block of text as `xbm2.xbm` and run `magick xbm2.xbm xbm2.png`.

**Comment by dlemstra** [comment]
Thanks for reporting this and I can reproduce your issue. I will work on a fix for this later this week/weekend.

**Comment by dlemstra** [comment]
I just pushed a patch to fix this for the next release.
