### ISSUE TITLE
Anatomy conflicts with usage examples

### ISSUE THREAD

**Issue by gqqnbig** [ImageMagick/ImageMagick#7408]
### ImageMagick version

7.1

### Operating system

Other (enter below)

### Operating system, version and so on

online documentation

### Description

https://imagemagick.org/script/command-line-processing.php#anatomy 

> The ImageMagick command-line consists of
> 
> 1. one or more required input filenames.
> 2. zero, one, or more image settings.
> 3. zero, one, or more image operators.
> 4. zero, one, or more image sequence operators.
> 5. zero, one, or more image stacks.
> 6. zero or one output image filenames

This section conveys the brief that the first part of the command-line must be input filenames.

However, this anatomy does not hold for many examples on that page. For example in `magick -size 640x480 -depth 8 rgb:image image.png`, the first part is image settings rather than input filenames.

In my beginner's opinion, The Anatomy of the Command-line is incorrect or confusing. Can we revise the section to the following?

> The ImageMagick command-line consists of
> 
> 1. zero, one, or more **input** image settings.
> 2. one or more required input filenames.
> 3. zero, one, or more **output** image settings.
> 4. zero, one, or more image operators.
> 5. zero, one, or more image sequence operators.
> 6. zero, one, or more image stacks.
> 7. zero or one output image filenames

Or, are you saying the order is not really strict? Then probabaly it's better to use unordered list rather than ordered list.

**Comment by dlemstra** [comment]
We are just listing the various parts that are possible. We will update it to an unordered list to make that more clear.

**Comment by gqqnbig** [comment]
Fixed in https://github.com/ImageMagick/Website/commit/53a905d991ea4ad3be4a4ea07c0ef079af90e900
