### ISSUE TITLE
Tiff files convert fail with a memory error on ubuntu 22.04

### ISSUE THREAD

**Issue by AnjaliPal** [ImageMagick/ImageMagick#7418]
### ImageMagick version

7.0.8-44

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.04

### Description

Hello,

I am currently using Imagemagick 7.0.8 on ubuntu 20.04 which works absolutely fine. Now I have upgraded my operating system from ubuntu 20.04 to 22.04 and Imagemagick started to fail for tiff file. I am running below commands to convert one of my tiff files:
**convert -flatten -sharpen 0x1.0 ICS_TIF_1.tif ICS_TIF_1.tif.convert**
and the error I get is:
**free(): invalid next size (fast)
Aborted**

Below is my Imagemagick version:

**Version: ImageMagick 7.0.8-44 Q16 aarch64 2024-06-21 https://imagemagick.org
Copyright: © 1999-2019 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): freetype gslib jbig jng jpeg lcms lzma png ps tiff x xml zlib**

Below are the installed packages I have for libtiff:

**ii  libtiff-dev:arm64             4.3.0-6ubuntu0.9                        arm64        Tag Image File Format library (TIFF), development files
ii  libtiff5:arm64                4.3.0-6ubuntu0.9                        arm64        Tag Image File Format (TIFF) library
ii  libtiff5-dev:arm64            4.3.0-6ubuntu0.9                        arm64        Tag Image File Format library (TIFF), development files (transitional package)
ii  libtiffxx5:arm64              4.3.0-6ubuntu0.9                        arm64        Tag Image File Format (TIFF) library -- C++ interface**

Thank you in advance!

### Steps to Reproduce

1: Install ubuntu 22.04
2: Install Imagemagick 7.0.8
3: run below command:
**convert -flatten -sharpen 0x1.0 ICS_TIF_1.tif ICS_TIF_1.tif.convert**

### Images

I am not able to attach the tiff files I am using. But you can use any valid tiff file to reproduce the issue.

**Comment by fmw42** [comment]
With IM 7 use magick not convert.  Also read the input before -flatten -sharpen. That is read the input right after magick.  See if that helps.  If you cannot attach the tiff, then zip it first and then try again.

**Comment by urban-warrior** [comment]
ImageMagick 7.0.8 is quite old.  Try upgrading to the latest release, 7.1.1-33.  If the issue persists, let us know and we will add a patch or suggest a work-around.

**Comment by AnjaliPal** [comment]
> With IM 7 use magick not convert. Also read the input before -flatten -sharpen. That is read the input right after magick. See if that helps. If you cannot attach the tiff, then zip it first and then try again.

Unfortunately that did not work as well.

**Comment by AnjaliPal** [comment]
> ImageMagick 7.0.8 is quite old. Try upgrading to the latest release, 7.1.1-33. If the issue persists, let us know and we will add a patch or suggest a work-around.

I tried latest IM 7.1.1-33 this morning and it worked fine with latest ubuntu 24.10. Thank you so much for this.
