### ISSUE TITLE
test failures on big endian systems due different signatures

### ISSUE THREAD

**Issue by sharkcz** [ImageMagick/ImageMagick#742]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
2 tests fails in the Magic++ test suite on big endian system due different signatures being computed

from ```Magick++/tests/tests.log```
```
1..13
Line: 49  Horizontal append failed, signature = 3e963245ee5ca5e40977431ad23b5ec759e516f0511a80a21361c7d41cd4f84c
Line: 63  Vertical append failed, signature = 3869872f8e23fa9fb9362e152b778e6a94d2f271339bbcc5b1b5c21d002a1a81
2 failures
not ok
FAIL: Magick++/tests/tests.tap 1
Testing throwing and catching exceptions. A program crash or a message
that the exception was not caught indicates a test failure.  A properly
formatted exception message indicates success:
Caught exception, good!:
  "lt-attributes: unable to open image 'foo': No such file or directory @ error/blob.c/OpenBlob/3146"
Line: 1277, signature (606d5cec3f2ed563d93303e0e1909b81120547abd222481c9fc4932baa59f4ba) is incorrect
Caught exception: lt-attributes: unable to open X server `/home/sharkcz/projects/ImageMagick/utilities/magick display' @ error/display.c/DisplayImages/1685
not ok
FAIL: Magick++/tests/tests.tap 2
ok
PASS: Magick++/tests/tests.tap 3
ok
...
```

### Steps to Reproduce
```make check```

### System Configuration
- ImageMagick version: (output of gitversion.sh)
21049:11f3966e9:20170908
- Environment (Operating system, version and so on):
Fedora 26 on ppc64 and s390x
- Additional information:

**Comment by mikayla-grace** [comment]
Can you post a URL to appendImages_horizontal_out.miff and appendImages_vertical_out.miff so we can download and inspect them?  We cannot directly debug this problem because we do not have access to a big endian host.  Instead we must compare your horizontal and vertical images to that of a little-endian machine.  Perhaps we can divine the reason for the incorrect signatures.

**Comment by sharkcz** [comment]
[appendImages.zip](https://github.com/ImageMagick/ImageMagick/files/1287665/appendImages.zip)

Let me know if you want access to a big endian system, I can organize that. Also we (the Fedora Alternative Architectures team) work on a CI system that would monitor upstream projects for issues on non-x86 arches.

**Comment by mikayla-grace** [comment]
We verified the x86 and non-x86 images are the same.  The compare utility returns zero distortion for the RMSE.  That means the signature algorithm is misbehavin'.    We will need access to a big endian system to investigate.  We set up a temporary e-mail @ fedora-alternative-architectures @ imagemagick.org so you can contact us directly with a path forward.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by sharkcz** [comment]
Good news, thanks.
