### ISSUE TITLE
Command to read text file as image works in IM 6, but not IM 7

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#7422]
### ImageMagick version

7.1.1.33

### Operating system

MacOS

### Operating system, version and so on

OSX Ventura

### Description

I have a problem in one of my scripts. 

The following command works in IM 6.9.13-11, but fails in IM 7.1.1-33

Text file:

[stainedglass_C_2728.txt.zip](https://github.com/user-attachments/files/15938310/stainedglass_C_2728.txt.zip)

IM 6:

`convert -background black stainedglass_C_2728.txt x6.png`

Produces x6.png (grid of vertices):

![t1_6](https://github.com/ImageMagick/ImageMagick/assets/13458218/a12917a4-e600-4305-b82c-faa3cc7961c7)

IM 7

```
magick -background black stainedglass_C_2728.txt x7.png 
magick: no images for write '-write' 'x7.png' at CLI arg 4 @ error/operation.c/CLINoImageOperator/4983

```

### Steps to Reproduce

See above

### Images

See above

**Comment by dlemstra** [comment]
This is not a problem with your script but with your input data. Your input file doesn't contain enough data.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.

@dlemstra, we need to support sparse pixels, so I reverted your patch.  @fmw42, for IMv7, you need to specify the background color for sparse pixels, e.g., `-background black`.

**Comment by fmw42** [comment]
Thanks. It seems to work now for IM 7.1.1.34
