### ISSUE TITLE
Scanned Color PDF does not converted to Black and White images, rather converted into original color image with Monochrome as TRUE

### ISSUE THREAD

**Issue by SakthivelArumugam1** [ImageMagick/ImageMagick#7432]
### ImageMagick version

Magic.Net 13.2.0

### Operating system

Windows

### Operating system, version and so on

Windows Server 2016 Standard 64 bit OS x64 based processor

### Description

We are using Imagemagic and Ghostscript to convert digital/scanned pdf to images. In Windows Environment, scanned color PDF was converted to original color images. But with Monochrome as TRUE should convert color PDF to black and white images. Why it was not converted to black and white images?

Below are the details and settings:

Magick.NET-Q8-x64 - 13.2.0
Magick.NET.Core - 13.2.0
GPL Ghostscript - 10.00.0

Imagemagic Settings:
Density: 300
Image Width: 1500
Image Height: 1500
Monochrome: true
Image Format: jpg

In Linux, we have installed same Ghostscript version 10.00.0. With Image magic version and setting, scanned color PDF was converted to black and white grey based images(NOT original color).

Probelm Statement:
In Windows Environment, scanned color PDF was converted to original color images. But with Monochrome as TRUE should convert color PDF to black and white images. Why it was not considered Monochrome setting? Is there any limitation or some windows settings is causing this issue? 

### Steps to Reproduce

1. Have same set of environment like windows, imagemagic, magic.net, ghostscript. 
2. Provide a color scanned pdf to Imagemagic conversion. 
3. Validate the converted images. Expected is to convert to black and white / grey based images. But we are receiving same original color images.

**Comment by snibgo** [comment]
We need more information to try to reproduce the problem.

If you use a command, please show that command and a sample PDF input that shows the problem.

If you use a program, please show a *minimal* program and a sample PDF input that shows the problem.

**Comment by SakthivelArumugam1** [comment]
Input PDF on the left side and Output Image on the right side...
![InputPDF_OutputImage](https://github.com/ImageMagick/ImageMagick/assets/174089607/217dbada-2390-4533-86f7-fbd11c8e0c9f)

Sample code snip
![CodeSnip](https://github.com/ImageMagick/ImageMagick/assets/174089607/388023bc-6f46-4da0-8d23-7c0c0a02a465)
Hi, added sample code snip, input pdf and output image. Hope this will help you understand the problem.

**Comment by snibgo** [comment]
Please don't multi-post to here and https://github.com/dlemstra/Magick.NET/issues (which is the more appropriate place).
