### ISSUE TITLE
Denial-of-Service (DOS) issue. Large multi-frame animated GIF consumes 100% CPU and exhausts RAM with `identify -limit thread X` option

### ISSUE THREAD

**Issue by onethumb** [ImageMagick/ImageMagick#7441]
### ImageMagick version

7.1.1-34

### Operating system

Other (enter below)

### Operating system, version and so on

macOS, Linux

### Description

When using `identify -limit thread {X} {FILENAME}.gif` on an animated GIF, a CPU core pegs at 100% and RAM exhausts itself until the system crashes.

### Steps to Reproduce

I can't currently share the file in question (I run Flickr and SmugMug, so this is a customer's image, and I'd have to ask for permission), but would be willing to try to reproduce if this was hard to track down... a private customer GIF that includes 1517 frames, is 1920x1080 for each frame, and is 57,957,982 bytes (~55MB) in size.

Using `-limit thread X` (any number we've tried from 1 to 20), results in 100% CPU (single core) and eventual RAM exhaustion.

Omitting `-limit thread` returns very quickly with very limited RAM overhead.

**Comment by urban-warrior** [comment]
To prevent potential DOS, use this command:

```
identify  -define registry:temporary-path=./ -limit area 0 -limit thread 1 -ping myhugeimagesequence.gif
```

In the mean-time, we added a patch to the master branch so that `-ping` will not be necessary.

**Comment by onethumb** [comment]
Thank you! Will try this out. 👍
