### ISSUE TITLE
libxml2 deprecated --with-ftp configure flag, compile fails from now 

### ISSUE THREAD

**Issue by osevan** [ImageMagick/ImageMagick#7444]
### ImageMagick version

latest master

### Operating system

Linux

### Operating system, version and so on

debian sid

### Description

I want try to compile libimagemagick with latest libxml2, but it fails since last release

Becauee imagemsgick needs  
usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `xmlNanoFTPNewCtxt'
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `xmlNanoFTPConnect'
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `xmlNanoFTPClose'
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `xmlNanoFTPInit'
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `xmlNanoFTPGet

https://gitlab.gnome.org/GNOME/libxml2/-/releases

They wrote above

Support for FTP and xpointer() XPath extensions will be removed in
the next release.
Several more legacy symbols were deprecated. Users of the old "SAX1"
API functions are encouraged to upgrade to the new "SAX2" API,
available since version 2.6.0 from 2003.

Thanks and

Best regards

### Steps to Reproduce

Latest imagick with latest libxml2

### Images

Not needed

**Comment by dlemstra** [comment]
We are checking if `LIBXML_FTP_ENABLED` is define. Why is this still defined if support has been removed?

**Comment by osevan** [comment]
How i can remove this at configure level with --without-ftp?

**Comment by dlemstra** [comment]
This `LIBXML_FTP_ENABLED` is coming from the `libxml2` library? It seems that the header files of that library still contain this define?

**Comment by osevan** [comment]
We need at configure level to disable ftp...


LIBXML_FTP_ENABLED header comes from Debian syystem default path. 
 
Im installing newest libxml2 from git on different path and all librarys since years.

Working well untill now with ftp headers trouble on libxml2 changelogs ..

I think configure sgript looking in wrong directory for heades and finding old libxml2 version headers with these ftp content 

But this should not ve happen .


Thanks and


Best regards
.

**Comment by dlemstra** [comment]
That sounds like an issue with how libxml2 is installed on your system? Is there a reason you did not close this issue?

**Comment by osevan** [comment]
Could you tell me which directorys i shoukd overwrite with my latest libxml2 files and headers? 

Than i can write manualy script to do this .


Thanks and


Best regards

**Comment by osevan** [comment]
Could you tell me how i can consider my alternative libxml2 path of headers and librarys?
I did -I/mypath and -L/mypath and for all other compiles it was enough,  but not for imagemagick

**Comment by dlemstra** [comment]
And as I said before this is something that you will need to figure out yourself. I really think it's easier to solve this problem by not having two libxml2 versions on your system. 

p.s. Please come back here to explain how you solved this.

**Comment by osevan** [comment]
https://github.com/ImageMagick/ImageMagick/blob/9980efa871fd0661fa06e458e9d3bac8a1490c8d/coders/url.c#L64

I outcomment these lines still same error

**Comment by dlemstra** [comment]
You should be able to fix this without making patches to our software.

**Comment by osevan** [comment]
:~/compile/test/ImageMagick# plocate nanoftp.h
/root/compile/test/libxml2-src/doc/devhelp/libxml2-nanoftp.html
/root/compile/test/libxml2-src/include/libxml/nanoftp.h
/usr/include/libxml2/libxml/nanoftp.h
 --- alternative libc path bottom
/usr/lib/x86_64-linux-gnu/clearlibc/glibc-2.39/install/include/libxml2/libxml/nanoftp.h

**Comment by osevan** [comment]
cat config.log|grep -i "configure:6014"
configure:6014: gcc -O2 -g3 -march=znver4 -L/usr/lib/x86_64-linux-gnu/clearlibc/glibc-2.39/install/lib -I/usr/lib/x86_64-linux-gnu/clearlibc/glibc-2.39/install/include -Wl,--rpath=/usr/lib/x86_64-linux-gnu/clearlibc/glibc-2.39/install/lib -Wl,--dynamic-linker=/usr/lib/x86_64-linux-gnu/clearlibc/glibc-2.39/install/lib/ld-linux-x86-64.so.2 -I/usr/lib/x86_64-linux-gnu/clearlibc/glibc-2.39/install/include/libxml2 -Wno-deprecated-declarations -fno-omit-frame-pointer  conftest.c  >&

**Comment by osevan** [comment]
cp -f MagickCore/ImageMagick.pc MagickCore/ImageMagick-7.Q16HDRI.pc
cp -f MagickCore/MagickCore.pc MagickCore/MagickCore-7.Q16HDRI.pc
cp -f MagickWand/MagickWand.pc MagickWand/MagickWand-7.Q16HDRI.pc
cp -f Magick++/lib/Magick++.pc Magick++/lib/Magick++-7.Q16HDRI.pc
  CCLD     MagickCore/libMagickCore-7.Q16HDRI.la
  CCLD     MagickWand/libMagickWand-7.Q16HDRI.la
  CXXLD    utilities/magick
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `xmlNanoFTPNewCtxt'
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `xmlNanoFTPConnect'
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `xmlNanoFTPClose'
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `xmlNanoFTPInit'
/usr/bin/ld: MagickCore/.libs/libMagickCore-7.Q16HDRI.so: undefined reference to `xmlNanoFTPGet'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:8217: utilities/magick] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/root/compile/test/ImageMagick'
make: *** [Makefile:6259: all] Error 2

**Comment by osevan** [comment]
I fixed my issue with disabling system path /usr/include/libxml2 inside fine granular chroot


5:~/compile/test/ImageMagick# magick --version
Version: ImageMagick 7.1.1-35 (Beta) Q16-HDRI x86_64 a262192e3:20240630 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib freetype jbig jng jpeg lzma png raqm tiff webp x xml zip zlib zstd
Compiler: gcc (13.3)
