### ISSUE TITLE
Issue with TreatWarningAsError and magick_unused attribute

### ISSUE THREAD

**Issue by niclet** [ImageMagick/ImageMagick#7459]
### ImageMagick version

7.1.1-34

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

While trying to turn off LQR delegate, compilation fails in ImageMagick\MagickCore\resize.c (l 2018)

Actually, magick_unused has no effect on windows, but MagickCore is built with /WX option according to Project::treatWarningAsError() from ImageMagick-Windows\Configure\Project.cpp (l 181)

And so, unused named parameters lead to warning, and are treated as errors.

### Steps to Reproduce

Turn off MAGICKCORE_LQR_DELEGATE, and compilation will fail for ImageMagick\MagickCore\resize.c :

ImageMagick\MagickCore\resize.c(2018,52): warning C4100: 'rigidity': unreferenced formal parameter ImageMagick\MagickCore\resize.c(2018,16): warning C4100: 'delta_x': unreferenced formal parameter
ImageMagick\MagickCore\resize.c(2017,52): warning C4100: 'rows': unreferenced formal parameter
ImageMagick\MagickCore\resize.c(2017,16): warning C4100: 'columns': unreferenced formal parameter 

ImageMagick\MagickCore\resize.c(2018,52): error C2220: the following warning is treated as an error

**Comment by dlemstra** [comment]
I will take a look at this and see how we can resolve this.
