### ISSUE TITLE
Better document the default behavior and limitations in rendering SVGs

### ISSUE THREAD

**Issue by peteroupc** [ImageMagick/ImageMagick#7468]
### Is your feature request related to a problem? Please describe.

See the following discussion: https://github.com/ImageMagick/ImageMagick/discussions/7440

### Describe the solution you'd like

It appears that ImageMagick renders SVGs using Inkscape by default if Inkscape is installed.  But this fact appears not to be mentioned in the ImageMagick documentation.  Nor is it mentioned that using Inkscape comes with several limitations that are not present when `msvg:` or `rsvg:` (two alternative SVG renderers) are added in front of the file name.

One of these limitations is that `-size` is ignored when Inkscape is the SVG renderer, due to an apparent limitation in Inkscape.

Thus, the documentation should mention these and other limitations in ImageMagick's default way of rendering SVGs.

(In my opinion, if `-size` is given, ImageMagick should use by default an SVG renderer that takes account of `-size`: if not Inkscape, then possibly `rsvg`. If `-size` is not given, then ImageMagick can safely default to Inkscape.  However, I suspect that these changes to ImageMagick are not forthcoming; moreover, these changes can wait as far as I am concerned.)

**Comment by snibgo** [comment]
> It appears that ImageMagick renders SVGs using Inkscape by default if Inkscape is installed. But this fact appears not to be mentioned in the ImageMagick documentation.

See the formats page https://www.imagemagick.org/script/formats.php :

> ImageMagick utilizes inkscape if its in your execution path otherwise RSVG. If neither are available, ImageMagick reverts to its internal SVG renderer.  ... etc.

But feel free to suggest suggest changes to documentation.

**Comment by peteroupc** [comment]
The following suggestion will resolve this issue.

> By default, ImageMagick renders SVGs with Inkscape if Inkscape is in your execution path; otherwise RSVG. If neither is available, ImageMagick reverts to its internal SVG renderer (called MSVG). The default resolution is 96 DPI. Use the `-size` command line option to specify the maximum width and height. (`-size` is currently ignored by the Inkscape renderer due to a limitation on the Inkscape side.) If you want to substitute entities and you trust the SVG source, enable this option: `-define svg:substitute-entities=true`. If you want to render a very large SVG and you trust the source, enable this option: `-define svg:parse-huge=true`.  If you want to render an SVG using RSVG, add `rsvg:` just before the file name.  If you want to render an SVG using MSVG, add `rsvg:` just before the file name.

**Comment by fmw42** [comment]
The last part about RSVG requires that delegate to be installed.

**Comment by snibgo** [comment]
>  If you want to render an SVG using MSVG, add rsvg: just before the file name.

I think you mean `msvg:`.

**Comment by peteroupc** [comment]
Made suggested changes.

**Comment by dlemstra** [comment]
We also support pull requests for our website. Can you open one here: https://github.com/ImageMagick/Website?
