### ISSUE TITLE
Image is failing to read because IDAT: chunk data is too large

### ISSUE THREAD

**Issue by coderangerdan** [ImageMagick/ImageMagick#747]
- [YES] I have written a descriptive issue title
- [YES] I have verified that I am using the latest version of ImageMagick
- [YES ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I try and read the image below and i get an "because IDAT: chunk data is too large" error message:

![testimage](https://user-images.githubusercontent.com/1733292/30274811-ed8429e8-96f6-11e7-8e75-6d28de1ea669.png)

Earlier version (v7.0.6.102 specifically) of ImageMagick worked fine, I upgraded to v7.07 and now it doesn't.

The image opens in all image editors fine.

If I open the image in paint.net and save it back out in same format and using Auto-Depth settings, the size reduces from 65kb to 4kb and ImageMagick then has no problems reading it.

### Steps to Reproduce
```
var readSettings = new MagickReadSettings();
readSettings.Format = MagickFormat.Png;

using( var downloadStream = new FileStream( "TestImage.png", FileMode.Open ) )
using( var resizedImageStream = new MemoryStream() )
using( var image = new MagickImage( downloadStream, readSettings ) )  // exception thrown here
{
    image.Strip();                // Strip out all profile info...
    image.Quality = 100;

    image.Write( resizedImageStream, readSettings.Format );
    resizedImageStream.Position = 0;

    // we do something with the memory stream....
}
```

Stack trace:
```
Source: Magick.NET-Q16-x64
IDAT: chunk data is too large `' @ error/png.c/MagickPNGErrorHandler/1711
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadStream(MagickSettings settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller)
   at ImageMagick.MagickImage.Read(Stream stream, MagickReadSettings readSettings, Boolean ping)
   at ImageMagick.MagickImage..ctor(Stream stream, MagickReadSettings readSettings)
```
### System Configuration
Windows 10 Visual Studio 2017, but also on Windows Server multiple versions

- ImageMagick version: Magick.NET-Q16-x64 v7.07
- Environment (Operating system, version and so on): Windows (any)
- Additional information: none not already mentioned above

**Comment by dlemstra** [comment]
You are positing the message in the wrong project. Can you open an issue here instead: https://github.com/dlemstra/Magick.NET/issues? Feel free to use the same template 👍

**Comment by glennrp** [comment]
I believe that this bug exists in libpng-1.6.32  and is fixed in
libpng-1.6.33beta

**Comment by dlemstra** [comment]
@glennrp When are you planning to release 1.6.33?

**Comment by glennrp** [comment]
Hopefully on Sept 28, but I've got some oss-fuzz issues that I'd like to resolve first.  oss-fuzz turnaround is slow.
