### ISSUE TITLE
magick ±append versus magick convert

### ISSUE THREAD

**Issue by mMerlin** [ImageMagick/ImageMagick#7484]
### ImageMagick version

7.1.1-33

### Operating system

Linux

### Operating system, version and so on

Fedora 40 workstation, bash

### Description

I read through the information about using magick instead of convert or magick convert for IM7. However there seems to be a problem with +append and -append (and other convert options). When using 'just' magick here, the files to be processed are not found.

### Steps to Reproduce

```
$ convert +append one.png two.png right.png
WARNING: The convert command is deprecated in IMv7, use "magick"

$ magick convert +append one.png two.png right.png
WARNING: The convert command is deprecated in IMv7, use "magick"

$ magick +append one.png two.png right.png
magick: no images found for operation `+append' at CLI arg 1 @ error/operation.c/CLIOption/5479.
$ convert -append one.png two.png bottom.png
WARNING: The convert command is deprecated in IMv7, use "magick"

$ magick convert -append one.png two.png bottom.png
WARNING: The convert command is deprecated in IMv7, use "magick"

$ magick -append one.png two.png bottom.png
magick: no images found for operation `-append' at CLI arg 1 @ error/operation.c/CLIOption/5479.

$ which convert
/usr/bin/convert
$ which magick
/usr/bin/magick
$ ls -ls /usr/bin/convert
4 lrwxrwxrwx. 1 root root 6 Jun 16 18:00 /usr/bin/convert -> magick
$ magick --version
Version: ImageMagick 7.1.1-33 Q16-HDRI x86_64 22263 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib gvc heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png ps raqm raw rsvg tiff webp wmf x xml zip zlib zstd
Compiler: gcc (14.1)
```

### Images

![one](https://github.com/user-attachments/assets/ea15afc5-ae87-4222-acaf-7d0168a7ab71)
![two](https://github.com/user-attachments/assets/41bf7165-69af-4ee9-97d9-5c3ca157a14c)

**Comment by fmw42** [comment]
IM 7 is more strict about command line syntax.  Read the input first, then your settings, then your operators, then the output.

**Comment by mMerlin** [comment]
So this works without warnings:
```sh
magick one.png two.png +append right.png
```
That symptom is a bit strange. Since 'convert' is aliased to 'magick' with the symbolic link, there is no obvious difference between
```sh
convert +append one.png two.png right.png
```
and
```sh
magick +append one.png two.png right.png
```
The first works but gives the deprecated warning, the second fails due to the stricter command line syntax parsing. But the command line syntax looks identical. It would seem that when the deprecated command is detected, if also falls back to the older parsing rules.


Or alternately, when a tool is detected in the command line (convert), the parsing rules change.

**Comment by urban-warrior** [comment]
Review https://imagemagick.org/script/porting.php for a description of how the `magick` CLI parser differs from the `convert` legacy parser.

**Comment by lamyergeier** [comment]
> IM 7 is more strict about command line syntax. Read the input first, then your settings, then your operators, then the output.

Can you please tell where did you find this? I could not find this at [ImageMagick – Porting to ImageMagick Version 7](https://imagemagick.org/script/porting.php)

**Comment by mMerlin** [comment]
Search for "Shell API or Command-line Interface". It's about 2/3 of the way through that long page. It starts with:

As mentioned the primary focus of the changes to the Shell API or Command Line Interface is the abstraction so that not only can options be read from command line arguments, but also from a file (script) or from a file stream (interactive commands, or co-processing).

To do this the CLI parser needed to be re-written, so as to always perform all options, in a strict, do-it-as-you-see it order. Previously in IMv6 options were performed in groups (known as 'FireOptions), this awkwardness is now gone. However the strict order means that you can no longer give operations before providing an image for the operations to work on. To do so will now produce an error.

**Comment by fmw42** [comment]
Just from what I heard from the developers. And also from https://imagemagick.org/Usage/basics/#cmdline (for IM 6)

**Comment by fmw42** [comment]
For novices, see

http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=9620
http://www.imagemagick.org/script/command-line-processing.php
https://imagemagick.org/script/command-line-options.php (and see the sitemap link at the bottom)
http://www.imagemagick.org/Usage/reference.html
http://www.imagemagick.org/Usage/
https://github.com/ImageMagick/usage-markdown
https://imagemagick.org/script/porting.php#cli
https://legacy.imagemagick.org/discourse-server/index.php

**Comment by MilkBiscuit** [comment]
If you suddenly change the command format from

`convert +append a.png b.png comparison.png`

to

`magick a.png b.png +append c.png`

**AT LEAST MENTION THIS AND GIVE AN EXAMPLE IN [THE DOCUMENT]**(https://imagemagick.org/script/command-line-options.php#append)!


`magick: no images found for operation '+append' at CLI arg 1 @ error/operation.c/CLIOption/5481.` **IS NOT HELPFUL!!!**

**Comment by urban-warrior** [comment]
See https://usage.imagemagick.org/basics/#cmdline:


> Note that no 'operation' should be given, before at least one image is either read in or created. In fact you may like to consider a 'image read/create' also as an operation as well. After all it really is image processing operation, that of translate an image in a file to an image in memory. So the correct way to do this in IMv7 is to read the image, process and then use the final 'implicit write' argument to write out the result. That is..
> 
> command  "image" { -operation }... "output_image"

**Comment by MilkBiscuit** [comment]
We are just some old customers using below command to finish a 5-second task.
`convert +append a.png b.png comparison.png`

In fact, `convert +append` is the one and only magick command I use in the past 3 years.
You can't expect us to spend a whole hour reading your verbose https://usage.imagemagick.org/basics/#cmdline .

**Comment by fmw42** [comment]
This has been explained for many years even for IM 6, but is now more strict in IM 7.  See https://usage.imagemagick.org/basics/#cmdline

**Comment by Jmorkcho** [comment]
Thank God this thread exists.
I agree with @MilkBiscuit. Took me 10 minutes to figure out how exactly to work this out, instead the error could've been more detailed/shown an example.


Maybe there could be an `magick --apend --help` command to give you an example how to use it. 👍
