### ISSUE TITLE
-density and -background arguments are ignored if the source filename is not in the end

### ISSUE THREAD

**Issue by mihaon** [ImageMagick/ImageMagick#7489]
### ImageMagick version

7.1.1-32

### Operating system

Linux

### Operating system, version and so on

alpine 3.20.0

### Description

The documentations provides example:
`magick rose.jpg -resize 50% rose.png`

So I tried to execute:
`convert file.svg -density 3072 -resize 1024x1024 -background transparent file.png`

But -density and -background arguments are ignored.

But if I move the source filename to the end, everything is fine:
`convert -density 3072 -resize 1024x1024 -background transparent file.svg file.png`

Is it bug?

### Steps to Reproduce

1. Install Linux alpine
2. Install libraries:
`apk add --no-cache imagemagick imagemagick-libs freetype-dev libpng-dev jpeg-dev libjpeg-turbo-dev librsvg-dev rsvg-convert`
3. Execute in shell:
`convert file.svg -density 3072 -resize 1024x1024 -background transparent file.png`

Actual result:
-density and -background arguments are ignored

**Comment by fmw42** [comment]
density 3072 is huge. You probably do not want that much. What color is your current background.  -background is a setting. You have to change your background color to transparent. But you have to specify your current background. First try

Just turn on a current transparent background:

`convert -density 300 -background transparent file.svg -resize 1024x1024 file.png
`
If that fails, try

Change current background to transparent:

`convert -density 300 -background transparent file.svg -resize 1024x1024 -transparent your_current_background_color file.png
`

Do either of those work?

If not, then perhaps you need to modify the svg file to reset the size to your desired size.  An SVG expert may need to comment further.

**Comment by snibgo** [comment]
> convert file.svg -density 3072 -resize 1024x1024 -background transparent file.png

@mihaon: Why are you using `convert`? That is deprecated. Don't use it. Use `magick` instead.

```
magick file.svg -density 3072 -resize 1024x1024 -background transparent file.png
```
With `magick`, options are executed in the order you give them. So this will read an SVG file and rasterize it. Then it sets the density metadata, and resizes the image. Then it sets the background metadata (which doesn't change the image). Then it writes the image to a PNG file.

If you move `-density 3072` to *before* reading the SVG, this will have an impact on the rasterization. The default SVG density is 96, so 3072 will greatly increase the size in pixels, by a factor of approximately 30 in both directions.

**Comment by mihaon** [comment]
> With magick, options are executed in the order you give them.

That was I missing, thanks a lot for info.
