### ISSUE TITLE
imagemagic website is down

### ISSUE THREAD

**Issue by AnuMano** [ImageMagick/ImageMagick#7490]
### ImageMagick version

ImageMagick-7

### Operating system

Linux

### Operating system, version and so on

Ubuntu 20.04.6

### Description

We are unable to download. from https://www.imagemagick.org/download

### Steps to Reproduce

Access https://www.imagemagick.org

**Comment by dlemstra** [comment]
This happens occasionally and should be available again in a couple days.

**Comment by maxacarvalho** [comment]
Is there anything that can be done? It's still down. Pipelines are failing because it can't fetch the release.

**Comment by fmw42** [comment]
It is being worked on.  Please be patient.

**Comment by versionbayjc** [comment]
> Is there anything that can be done? It's still down. Pipelines are failing because it can't fetch the release.

One option is to add to your pipeline some alternative download locations. There are mirrors for ImageMagick, from the [Wayback Machine](https://web.archive.org/web/20240714201854/https://imagemagick.org/script/mirror.php) I found a mirror close to me (in Germany): https://mirror.dogado.de/imagemagick/. But there are others as well. Maybe you want to include a backup mirror download location in your pipeline logic?

**Comment by fmw42** [comment]
Please note that there was a major GLOBAL power outage yesterday with Microsoft.  Many web sites are down around the world that rely upon Microsoft.  Even airline computers are down and many people are stranded.

**Comment by versionbayjc** [comment]
I believe you’re referring to the CrowdStrike issue? That’s not really Microsoft’s fault nor a power outage. But yes lots of computers/services (that were protected by CrowdStrike) were affected. However the imagemagick website outage does not seem related as this issue #7490 was created 3 days ago and the CrowdStrike issue started less than 24h ago. Anyway, the public website of imagemagick is again up and running 👍

**Comment by fmw42** [comment]
I only mentioned that to say that it might contribute to the delay for the Imagemagick web site recovery.
