### ISSUE TITLE
Can't build ImageMagick-Windows with Visual Studio 2017 anymore

### ISSUE THREAD

**Issue by vergol** [ImageMagick/ImageMagick#7498]
### ImageMagick version

Current github version (19-07-2024)

### Operating system

Windows

### Operating system, version and so on

10 64-bit

### Description

I'm building current version with Visual Studio 2017 (as static Win32 library) , with default compiler settings (v141).
During the building process there's an error in harfbuzz library (CORE_harfbuzz)
```
C2955 'OT::Condition': use of class template requires template argument list
```
The error is really strange to me, because OT::Condition has no template arguments.

I've built ImageMagick few times before and never had such problems. So I guess something was changed in that library.

### Steps to Reproduce

Following the tutorial; Downloading dependencies; Building Configure.exe; Building solution in Release mode.

**Comment by fmw42** [comment]
IM version is 7.x.x.x.  Please post that?  Did you get a valid release from the GIT source or was it a beta. If a beta, I do not recommend that.  In any case, I recommend getting your release from https://imagemagick.org/script/download.php for binary or from https://imagemagick.org/archive/ for source files.

**Comment by vergol** [comment]
The version is 7.1.1-36 (Beta)
I'm just repeating my usual steps with ImageMagick but now got that error.
If it's an error in a third-party library, will it make any difference if I use a bit older (stable) ImageMagick source version?

**Comment by fmw42** [comment]
Don't use a beta.  It may be under changes?  Get the released version from the links above.

**Comment by vergol** [comment]
@fmw42 ok. Now I can confirm that the same problem appears on 7.1.1-35 version (https://imagemagick.org/archive/windows/ImageMagick-7.1.1-35.7z).
![image](https://github.com/user-attachments/assets/69b59d98-7fc6-498e-9043-61e632e57891)

**Comment by dlemstra** [comment]
Thanks for notifying us about this. We don't have any build pipelines that monitor if our project still builds with VS2017 so please create a new issue when this happens again. We have made patches in several repositories and we are able to build our project with VS2017. Can you confirm this is working for you with the latest unreleased code?
