### ISSUE TITLE
Different renders in same version, wrong svg render

### ISSUE THREAD

**Issue by websharik** [ImageMagick/ImageMagick#7501]
### ImageMagick version

7.1.1.35

### Operating system

Linux

### Operating system, version and so on

CentOS 8.10

### Description

Cant success run on prod.

Dev env: container based on alpine with 7.1.0-16.
Prod env: CentOS with 7.1.0-16 builded from source.

```convert -list font``` includes svg font both env's

Whats wrong: Stars style not working. Font not working. 

Was try latest version (7.1.1.35), all wrongs same + ship icon 
disappeared.

### Steps to Reproduce

convert test.svg out.png

### Images
Original svg:
![original](https://github.com/user-attachments/assets/ad9a7030-4fcc-49e3-8946-ad42e2a6376e)
Right render (DEV):
![right_render](https://github.com/user-attachments/assets/fdb792ba-a508-4d15-8171-524501fdd09f)
Wrong render (PROD):
![wrong_render](https://github.com/user-attachments/assets/edd3e89b-6870-43f1-bdab-7e1e38c43999)

**Comment by fmw42** [comment]
On my Mac OSX Ventura, it works with IM 6.9.13-13 with Ghostscript installed, but hangs with IM 7.1.1.35 with the same Ghostscript installed.  However, it fails on IM 6.9.13-13 and produces the bad result if using the internal MSVG.

So you probably have Ghostscript installed on your DEV, but no on your PROD.

Solution: install Ghostscript on both systems.  IM will use that automatically, if installed and can find it. So be sure its path is in your $PATH

**Comment by dlemstra** [comment]
Ghostscript  = Inkscape @fmw42.

**Comment by fmw42** [comment]
Oops!  I meant Inkscape.  Thanks Dirk for the correction.

**Comment by websharik** [comment]
Inkscape install resolve it.
