### ISSUE TITLE
we need removing mtune and march guessing at configure level

### ISSUE THREAD

**Issue by osevan** [ImageMagick/ImageMagick#7506]
### ImageMagick version

latest master 

### Operating system

Linux

### Operating system, version and so on

sid

### Description

Im setting my mtune flag self and mtune guessing inside configure doesnt work correctly. Even when i add my cflags self they add additonal wrong mtune flag. 

I want remove every mtune and March from configure. 

Hope you can plant --noarch-guessing or else.

Thanks and
Regards 

### Steps to Reproduce

..

### Images

.

**Comment by urban-warrior** [comment]
You can specify `--with-gcc-arch=`<arch>` in order to override the macro's choice of architecture, or --without-gcc-arch to disable this.

**Comment by osevan** [comment]
Thx
