### ISSUE TITLE
Various build errors when disabling some delegates

### ISSUE THREAD

**Issue by niclet** [ImageMagick/ImageMagick#7510]
### ImageMagick version

7.1.1-35

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

Hi,

Similarly to #7459 , I'm facing some other issues :

- without MAGICKCORE_FREETYPE_DELEGATE:

ImageMagick-Windows\ImageMagick\MagickCore\annotate.c
RenderFreetype (line 2109) : "encoding" parameter is not used
=> need to add
```
magick_unreferenced(encoding);
```

- without MAGICKCORE_HEIC_DELEGATE:

ImageMagick_7_1_1_35_DS\ImageMagick-Windows\ImageMagick\coders\heic.c
IsHEIC (line 788) : "magick" and "length" parameters are not used 
=> need to add
```
#else
  magick_unreferenced(magick);
  magick_unreferenced(length);
```

RegisterHEICImage and UnregisterHEICImage :
=> need to check for MAGICKCORE_HEIC_DELEGATE before using LIBHEIF_NUMERIC_VERSION

Regards.

### Steps to Reproduce

Build without MAGICKCORE_FREETYPE_DELEGATE and without MAGICKCORE_HEIC_DELEGATE

**Comment by dlemstra** [comment]
Feel free to create pull requests to resolve this?

**Comment by niclet** [comment]
Ok, I'll try that.

**Comment by niclet** [comment]
Hi,
Just tried with #7515 pull request to fix freetype issue. I'm not very familiar with that.
If everything is OK, I'll create other pull request for heic issue.
Regards.

**Comment by dlemstra** [comment]
Thanks for helping us. That was the correct fix! This has been merged so please create the PR for the heic errors.

**Comment by niclet** [comment]
Done.
Thanks for asking me to do my own pull requests.

**Comment by dlemstra** [comment]
And thank you for giving it a try 😄
