### ISSUE TITLE
Identify Error

### ISSUE THREAD

**Issue by palmuse** [ImageMagick/ImageMagick#7513]
Version: ImageMagick 7.1.1-35 Q16-HDRI aarch64 22320 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI
Delegates (built-in): bzlib cairo fftw fontconfig freetype heic jng jp2 jpeg jxl lcms lzma openexr pangocairo png rsvg tiff webp x xml zlib zstd
Compiler: gcc (4.2)

I just updated my installation.
I have used this code to get min width or height of image. It is now failing. Error below.

_magick identify -format "%[fx:min(w,h)]" test.jpg_

identify: GetHslInt failure 0 0,0 @ error/fx.c/ExecuteRPN/3159.
identify: ExecuteRPN failed   @ error/fx.c/FxEvaluateChannelExpression/4022.

**update:** I found a workaround or the requirement has changed. The following code works as expected.

_magick identify -colorspace sRGB -format "%[fx:min(w,h)]" test.jpg_

**Comment by urban-warrior** [comment]
Your command works as expected for us.  Try this command sequence:

```
magick identify -format "%[fx:min(w,h)]"  logo:
```

We get `480`.   What do you get?

**Comment by fmw42** [comment]
On my IM 7.1.1.35 Mac OSX Ventura, I get

```
magick identify -colorspace sRGB -format "%[fx:min(w,h)]" lena.jpg
256
```

So it works fine for me

**Comment by palmuse** [comment]
It is not clear to me what the issue is. The following did work as expected.

_magick identify -format "%[fx:min(w,h)]"  logo:_

So odd. Just adding -colorspace fixes my issue.

I am running this on am Android phone using a terminal app called Termux. Perhaps it is something in my set up that is causing the issue to be unique to my set up.

Been running this code for months without issue until today.

This can certainly be closed if it is only my issue.

Thanks so much for thsi wonderful tool!

**Comment by Tekl** [comment]
I'm on macOS 15 Beta 4 and have the same issues with this command:

`magick identify -format '%[pixel:u.p{120,5}]'`

But the error only occurs when the file is inside a folder managed by iCloud Drive. When I move the file into my Downloads folder, it works as expected. It doesn't matter if the file is marked with the new "Keep Downloaded" option or not.

**Comment by fmw42** [comment]
@Tiki  Your command has not image specified.

However, this morning I tested a file on my desktop that is on iCloud and got:

```
magick identify -format '%[pixel:u.p{120,5}]' lena.jpg
identify: GetHslInt failure 0 0,0 @ error/fx.c/ExecuteRPN/3159.
identify: ExecuteRPN failed   @ error/fx.c/FxEvaluateChannelExpression/4022.
identify: ExecuteRPN failed   @ error/fx.c/FxEvaluateChannelExpression/4022.
identify: ExecuteRPN failed   @ error/fx.c/FxEvaluateChannelExpression/4022.
identify: ExecuteRPN failed   @ error/fx.c/FxEvaluateChannelExpression/4022.
```

Yesterday I tested a different command that has been complained, which worked fine today also

```
magick identify -colorspace sRGB -format "%[fx:min(w,h)]" lena.jpg
256

```

**Looks like and issue with %[pixel: ... ]**

**Comment by snibgo** [comment]
This is the same issue as https://github.com/ImageMagick/ImageMagick/issues/7491

> identify: GetHslInt failure 0 0,0 @ error/fx.c/ExecuteRPN/3159.

This means your IM has the issue identified in that thread. The error message has recently been changed.

> Looks like and issue with %[pixel: ... ]

The issue is that fx (including `%[pixel: ... ]`) needs pixels, and `identify` was setting `ping`, so it didn't read pixels.

**Comment by palmuse** [comment]
> Yesterday I tested a different command that has been complained, which worked fine today also
> 
@fmw42 Just wanted to clarify that I added _-colorspace_ to my code to get it working. Without it the code failed.

@snibgo I see now that this is a known issue. Thanks for pointing it out. Also, thanks for the _+ping_ workaround.

**Comment by snibgo** [comment]
`+ping` is the simplest workaround, as it ensures pixels are read, with no other effects. `-colorspace sRGB` will also ensure pixels are read, but will also change the colorspace to sRGB (with three colour channels) if it isn't already.

The current (Beta) source code should work fine, with no workarounds needed.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and applied a patch to resolve the issue in the current release of ImageMagick.
