### ISSUE TITLE
Is converting XWD to PNG not supported?

### ISSUE THREAD

**Issue by wintonzheng** [ImageMagick/ImageMagick#7520]
### ImageMagick version

7.1.1-36

### Operating system

Linux

### Operating system, version and so on

macos, linux, ubuntu - Any version so far

### Description

Getting this error:
```
magick: no decode delegate for this image format `XWD' @ error/constitute.c/ReadImage/746.
```

### Steps to Reproduce

```
xwd -root -out screenshot.xwd
magick screenshot.xwd screenshot.png
```

**Comment by urban-warrior** [comment]
ImageMagick depends on the X11 delegate library to support images in the XWD format.  Type `magick --version` and see if `x` is in the list of delegates.

**Comment by wintonzheng** [comment]
> ImageMagick depends on the X11 delegate library to support images in the XWD format. Type `magick --version` and see if `x` is in the list of delegates.

i've been testing it with:
- the `FROM python:3.11` docker image (debian)
- `apt-get install libpq5 xvfb x11-apps`
- running `Xvfb :99 -screen 0 ...`

not sure why x delegate is not installed.

I found a workaround:
`xwd -root | xwdtopnm | pnmtopng > {screenshot.png}`
