### ISSUE TITLE
[BUG] no decode delegate for this image format `JPEG'

### ISSUE THREAD

**Issue by fscorrupt** [ImageMagick/ImageMagick#7521]
### ImageMagick version

7.1.1.36

### Operating system

Linux

### Operating system, version and so on

Alpine 3.17

### Description

Im installing imagemagick like this in my container: 

```bash
# Add the Edge Community repository and update
RUN echo @edge http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories \
    && apk upgrade --update-cache --available \
    && apk update \
    && apk add --no-cache \
        python3 \
        py3-pip \
        libjpeg-turbo-dev \
        imagemagick-libs@edge \
        imagemagick@edge
```

With imagemagick `v7.1.1.35` everything works as it should.

but with `v7.1.1.36` i get this error when trying to do for example, the command below:

Error: 
`error/module.c/OpenModule/1293.
no decode delegate for this image format 'JPEG'`

Command: 
`"magick" "./config/temp/Picture.jpg" -gravity center -background None -layers Flatten ( -font "./config/temp/Colus-Regular.ttf" -pointsize "250" -fill "white" -size "1900x500" -background none caption:"MY TEXT" -trim -gravity south -extent "1900x500" ) -gravity south -geometry +0"+400" -quality 100% -composite "./config/temp/Picture.jpg"`

The coders are present:
```bash
find /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders -name 'jpeg.*'

/usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.la
/usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.so
```

if i search inside the delegates.xml on both version i do not find *jpeg*
`cat /etc/ImageMagick-7/delegates.xml | grep -i jpeg`

### Steps to Reproduce

install imagemagick like this in a alpine container, in my case im using this base image and code:

```bash
FROM mcr.microsoft.com/powershell:7.4-alpine-3.17

# Add the Edge Community repository and update
RUN echo @edge http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories \
    && apk upgrade --update-cache --available \
    && apk update \
    && apk add --no-cache \
        python3 \
        py3-pip \
        libjpeg-turbo-dev \
        imagemagick-libs@edge \
        imagemagick@edge
```

and then run this command:  
`"magick" "./config/temp/Picture.jpg" -gravity center -background None -layers Flatten ( -font "./config/temp/Colus-Regular.ttf" -pointsize "250" -fill "white" -size "1900x500" -background none caption:"MY TEXT" -trim -gravity south -extent "1900x500" ) -gravity south -geometry +0"+400" -quality 100% -composite "./config/temp/Picture.jpg"`

you should then get the same error as i do, but only with imagemagick `v7.1.1.36`

**Comment by dlemstra** [comment]
And where can we find `Picture.jpg` to confirm this is not an issue with your file?

**Comment by fscorrupt** [comment]
it also happens with a short command, so no need for the long one, just try to add a comment: 
`magick "./config/temp/picture.jpg" -set "comment" "created with posterizarr" "./config/temp/picture.jpg" `

this results in getting same error message on `v7.1.1.36`
`magick: unable to load module '/usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.la': file not found @ error/module.c/OpenModule/1293.`

but it is present:
```bash
find /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders -name 'jpeg.*'
/usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.la
/usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.so
```

**Comment by dlemstra** [comment]
What is the output of `ldd /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.la`? Are you missing a reference there?

**Comment by fscorrupt** [comment]
with `7.1.1.36`:
`PS /> ldd /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.la
/lib/ld-musl-x86_64.so.1: /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.la: Not a valid dynamic program`

but thats the result of the .so file:
```
ldd /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.so
        /lib/ld-musl-x86_64.so.1 (0x7f5be62e2000)
        libMagickCore-7.Q16HDRI.so.10 => /usr/lib/libMagickCore-7.Q16HDRI.so.10 (0x7f5be5fe5000)
        libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x7f5be5f5e000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f5be62e2000)
        liblcms2.so.2 => /usr/lib/liblcms2.so.2 (0x7f5be5f09000)
        libfftw3.so.3 => /usr/lib/libfftw3.so.3 (0x7f5be5d0f000)
        libxml2.so.2 => /usr/lib/libxml2.so.2 (0x7f5be5be8000)
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x7f5be5ba8000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x7f5be5aee000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x7f5be5adc000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x7f5be59b9000)
        libbz2.so.1 => /usr/lib/libbz2.so.1 (0x7f5be59a6000)
        libz.so.1 => /lib/libz.so.1 (0x7f5be598c000)
        libltdl.so.7 => /usr/lib/libltdl.so.7 (0x7f5be5982000)
        libgomp.so.1 => /usr/lib/libgomp.so.1 (0x7f5be593b000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f5be591d000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x7f5be58f3000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x7f5be58d0000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x7f5be58a0000)
        libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x7f5be5892000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x7f5be586c000)
        libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x7f5be5849000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x7f5be5844000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x7f5be583c000)
        libbsd.so.0 => /usr/lib/libbsd.so.0 (0x7f5be5829000)
        libmd.so.0 => /usr/lib/libmd.so.0 (0x7f5be581d000)
Error relocating /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.so: jpeg_enable_lossless: symbol not foundError relocating /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.so: jpeg12_read_scanlines: symbol not found
Error relocating /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.so: jpeg12_write_scanlines: symbol not found
Error relocating /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.so: jpeg16_read_scanlines: symbol not found
Error relocating /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.so: jpeg16_write_scanlines: symbol not found
```

with `v7.1.1.35`:
`PS /> ldd /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.la
/lib/ld-musl-x86_64.so.1: /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.la: Not a valid dynamic program`

but thats the result of the .so file:
```
ldd /usr/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/jpeg.so
        /lib/ld-musl-x86_64.so.1 (0x7f0bd8a99000)
        libMagickCore-7.Q16HDRI.so.10 => /usr/lib/libMagickCore-7.Q16HDRI.so.10 (0x7f0bd879c000)
        libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x7f0bd8715000)
        libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f0bd8a99000)
        liblcms2.so.2 => /usr/lib/liblcms2.so.2 (0x7f0bd86c0000)
        libfftw3.so.3 => /usr/lib/libfftw3.so.3 (0x7f0bd84c6000)
        libxml2.so.2 => /usr/lib/libxml2.so.2 (0x7f0bd839f000)
        libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x7f0bd835f000)
        libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x7f0bd82a5000)
        libXext.so.6 => /usr/lib/libXext.so.6 (0x7f0bd8293000)
        libX11.so.6 => /usr/lib/libX11.so.6 (0x7f0bd8170000)
        libbz2.so.1 => /usr/lib/libbz2.so.1 (0x7f0bd815d000)
        libz.so.1 => /lib/libz.so.1 (0x7f0bd8143000)
        libltdl.so.7 => /usr/lib/libltdl.so.7 (0x7f0bd8139000)
        libgomp.so.1 => /usr/lib/libgomp.so.1 (0x7f0bd80f2000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f0bd80d4000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x7f0bd80aa000)
        libexpat.so.1 => /usr/lib/libexpat.so.1 (0x7f0bd8087000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x7f0bd8057000)
        libbrotlidec.so.1 => /usr/lib/libbrotlidec.so.1 (0x7f0bd8049000)
        libxcb.so.1 => /usr/lib/libxcb.so.1 (0x7f0bd8023000)
        libbrotlicommon.so.1 => /usr/lib/libbrotlicommon.so.1 (0x7f0bd8000000)
        libXau.so.6 => /usr/lib/libXau.so.6 (0x7f0bd7ffb000)
        libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x7f0bd7ff3000)
        libbsd.so.0 => /usr/lib/libbsd.so.0 (0x7f0bd7fe0000)
        libmd.so.0 => /usr/lib/libmd.so.0 (0x7f0bd7fd4000)
```

**Comment by urban-warrior** [comment]
The configuration script checks whether a function is available in the JPEG delegate library and only invokes the function if it is present, such as `jpeg16_write_scanlines`. To verify this, examine the `config.log` file and look for references to `jpeg16_write_scanlines`. The context should indicate whether the function was found and identify the corresponding library module.

Additionally, run the following command to check the JPEG library version:

```bash
magick -list format | grep JPG
```

Ensure that the library version displayed matches the version noted in the `config.log `file. It's possible that you might be building against one version of the JPEG delegate library while loading a different version when executing the ImageMagick utilities.

If you still have issues, you can add `--disable-shared` to your `configure` script command-line.  Does that resolve the issue?

**Comment by fscorrupt** [comment]
im using the pre-built package from Alpine Linux repositories, so i do not configure it and i do not have a config.log file?

**Comment by fscorrupt** [comment]
okey i tried to manually configure it and it works, so only the pre-build packages from alpine linux repositories are affected.

Who is responsible for the packages on alpine linux repo?

this is how i manually build container & imagemagick:
```bash
FROM mcr.microsoft.com/powershell:7.4-alpine-3.17

# Install build dependencies and prerequisites
RUN apk upgrade --update-cache --available \
    && apk update \
    && apk add --no-cache \
        build-base \
        wget \
        tar \
        autoconf \
        automake \
        libtool \
        pkgconfig \
        python3 \
        py3-pip \
        libjpeg-turbo-dev \
        libpng-dev \
        freetype-dev \
        fontconfig-dev \
        tiff-dev \
        libwebp-dev \
        lcms2-dev \
        fftw-dev \
        docker-cli

# Download and build ImageMagick from source
RUN wget https://imagemagick.org/archive/ImageMagick.tar.gz \
    && tar xvzf ImageMagick.tar.gz \
    && cd ImageMagick-* \
    && ./configure --with-jpeg \
    && make \
    && make install \
    && ldconfig /usr/local/lib

# Verify ImageMagick installation
RUN magick -version \
    && magick -list format | grep -i jpg
```

**Comment by darthShadow** [comment]
If you are installing the edge variant of imagemagick, you also need the edge variant of the dependent jpeg library `libjpeg-turbo`.

The `jpeg_enable_lossless` function was only added in `3.0` of libjpeg-turbo whereas the latest non-edge version in alpine is `2.1.4`.

**Comment by fscorrupt** [comment]
> If you are installing the edge variant of imagemagick, you also need the edge variant of the dependent jpeg library `libjpeg-turbo`.
> 
> The `jpeg_enable_lossless` function was only added in `3.0` of libjpeg-turbo whereas the latest non-edge version in alpine is `2.1.4`.

if you look at my init post you see that i have it that way:

```bash
# Add the Edge Community repository and update
RUN echo @edge http://dl-cdn.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories \
    && apk upgrade --update-cache --available \
    && apk update \
    && apk add --no-cache \
        python3 \
        py3-pip \
        libjpeg-turbo-dev \
        imagemagick-libs@edge \
        imagemagick@edge
```

**Comment by darthShadow** [comment]
`libjpeg-turbo-dev` needs to be `libjpeg-turbo-dev@edge`.

**Comment by darthShadow** [comment]
And just verified that `3.0.3-r0` of `libjpeg-turbo-dev`  is only available in the main repos, so you will need to add `http://dl-cdn.alpinelinux.org/alpine/edge/main` too.

**Comment by fscorrupt** [comment]
That was the solution; it's the kind of thing you just have to know. Thank you very much!

**Comment by darthShadow** [comment]
This is one of the reasons why mixing the edge repo with a versioned repo is never recommended for alpine.

If you absolutely have to do it, the best way that I have found is to follow these steps in the upstream alpine:edge container:
* List all installed packages by default.
* Add all required packages that you want to test on edge.
* List the packages again.
* Diff the final list with the one from the first step to list all the dependencies that need upgrading.
