### ISSUE TITLE
MagickGetImageBlob returns null for a TIFF image in some rare conditions

### ISSUE THREAD

**Issue by takashi543** [ImageMagick/ImageMagick#7534]
### ImageMagick version

7.1.1-36

### Operating system

Linux

### Operating system, version and so on

Fedora 40

### Description

libtiff (4.6.0 or earlier) seems to call TIFFSeekBlob() back with an offset beyond EOF for TIFF images with resolution properties during a MagickGetImageBlob call.  SeekBlob() returns -1 if the offset > `blob_info->extent`, that leads MagickGetImageBlob to return null.

### Steps to Reproduce

Please find the reproduction code as follows:
```
#include <stdio.h>
#include <MagickWand/MagickWand.h>

int main()
{
  MagickWand *magick_wand;
  unsigned char * blob;
  size_t blob_size;

  MagickWandGenesis();
  magick_wand=NewMagickWand();
  MagickSetSize(magick_wand, 1228, 425);
  if (MagickReadImage(magick_wand,"canvas:black") == MagickFalse)
    exit(1);
  MagickSetImageFormat(magick_wand, "tiff");
  MagickSetImageUnits(magick_wand, PixelsPerInchResolution);
  MagickSetImageResolution(magick_wand, 600, 600);
  MagickSetImageType(magick_wand, BilevelType);
  MagickSetImageDepth(magick_wand, 1);
  MagickSetImageCompression(magick_wand, NoCompression);

  blob = MagickGetImageBlob(magick_wand, &blob_size);
  printf("MagickGetImageBlob returned %p\n", blob);

  magick_wand=DestroyMagickWand(magick_wand);
  MagickWandTerminus();
  return(0);
}
```
The above code will show `MagickGetImageBlob returned (nil)` instead of a valid blob address.

### Images

(generated in the above reproduction code)

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
