### ISSUE TITLE
magick -define jpg:extend=xkb not working

### ISSUE THREAD

**Issue by iconberg** [ImageMagick/ImageMagick#7553]
### ImageMagick version

7.1.1.-36

### Operating system

Windows

### Operating system, version and so on

Win 10, Build 19045.4651

### Description

magick -define jpg:extend ist not working. I tried all combinations with and without -quality and kb, KB, Kb.

For example:
`magick test_big.jpg -define jpg:extent=100kb test.jpg`

A file with 277kb ist only down to 273kb. I attached my test.jpg

### Steps to Reproduce

Try to size the file down with the attached jpg to a size like 100kb.

### Images

![Test_big](https://github.com/user-attachments/assets/778cc30e-38b1-45c8-9930-8d3351eb554e)

**Comment by snibgo** [comment]
See https://imagemagick.org/script/defines.php . Your define should be `jpeg:`, not `jpg:`.

**Comment by iconberg** [comment]
Thanks, it is working then.

I played around, there is no validating on the -define options!
I understand it is because of so much different image modules and options, and you would like to reuse the options for different formats, but a warning would be nice.

**Comment by snibgo** [comment]
> ... there is no validating on the -define options!

That is true. `-define` can be used to define anything. IM doesn't have a list of defines that it recognizes, so can't validate that the `-define` isn't useful.
