### ISSUE TITLE
-respect-parentheses Is Missing in IM 7 Syntax

### ISSUE THREAD

**Issue by mastercoder42** [ImageMagick/ImageMagick#7559]
### ImageMagick version

7.1.1.36

### Operating system

Windows

### Operating system, version and so on

Windows 10.0.19045.4651

### Description

The `magick` tool does not recognize `-respect-parentheses`, while all other tools do. I realized this because the recent releases unexpectedly dropped support for `convert`, which forced me to migrate to the IM 7 syntax. I am really unhappy with the situation because the IM 7 syntax also produces different results sometimes and I had to go all over my scripts again just because I updated from version 7.1.1-10 to 7.1.1-36 (which was necessary because I wanted to switch from Q8 to HDRI but I wasn't able to find any HDRI build for 7.1.1-10 anymore online). The community faces a breaking change though only the 4th item of the version number changed.

### Steps to Reproduce

```
magick -respect-parentheses rose: info:
magick: unrecognized option `-respect-parentheses' at CLI arg 1 @ fatal/magick-cli.c/ProcessCommandOptions/657.

magick identify -respect-parentheses rose:
rose:=>ROSE PNM 70x46 70x46+0+0 8-bit sRGB 9673B 0.000u 0:00.000

identify -respect-parentheses rose:
rose:=>ROSE PNM 70x46 70x46+0+0 8-bit sRGB 9673B 0.000u 0:00.000
```

### Images

Just use `rose:`.

**Comment by fmw42** [comment]
Use `-respect-parenthesis`

**Comment by mastercoder42** [comment]
IM doesn't stop keeping me dumbfounded.

I believe the documentation needs a little patch then (https://imagemagick.org/script/command-line-options.php).

Personally, I wonder why someone would feel like singular is better than plural in this case but certainly whoever made the change has clearly seen that the benefits of doing so outweigh the confusion the change may cause by far.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
