### ISSUE TITLE
Ghostscript dependency for converting JPE files to PDF/TIFF using magick.exe from command line.

### ISSUE THREAD

**Issue by pprasanthk** [ImageMagick/ImageMagick#7561]
### ImageMagick version

 7.1.1-23

### Operating system

Windows

### Operating system, version and so on

Windows 10 and above.

### Description

Hi, 

While converting any JPE file to PDF or TIFF using magick.exe from command line using the below commands, it is observed that it requires Ghost script exe to be present in the same directory as the magick.exe or Ghost script software needs to be installed on the same machine: 
                 magick.exe 1.jpe 1.pdf
                magick.exe 1.jpe 1.tiff
We are looking for a way so that Ghost script is not required for these JPE to PDF and JPE to TIFF conversions. 

Could you please let us know of any alternative to avoid this Ghost script dependency for converting JPE files to PDF/TIFF using magick.exe from command line.

Please find the sample 1.JPE file attached here with inside 1.zip.

--
Thanks
Prasanth

### Steps to Reproduce

Run the below commands to reproduce the issue without Ghost script: 
magick.exe 1.jpe 1.pdf
magick.exe 1.jpe 1.tiff

### Images

[1.zip](https://github.com/user-attachments/files/16634043/1.zip)

**Comment by dlemstra** [comment]
Your `1.jpe` file is a `pdf` file and we need Ghostscript to read those files. And next time please open a discussion instead of an issue.
