### ISSUE TITLE
Current change has removed  -respect-parenthesis in favor of -respect-parentheses

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#7575]
### ImageMagick version

7.1.1.37

### Operating system

MacOS

### Operating system, version and so on

OSX Ventura

### Description

We used to allow (for ages now) both -respect-parenthesis (singular) and -respect-parentheses (plural).  In fact, originally there was only -respect-parentisis (singular). Current IM has removed -respect-parenthesis (singular). Please allow both as otherwise that breaks many of my scripts.

```
magick -respect-parenthesis logo: x.png
magick: unrecognized option `-respect-parenthesis' at CLI arg 1 @ fatal/magick-cli.c/ProcessCommandOptions/657.
```

### Steps to Reproduce

See above

### Images

See above

**Comment by urban-warrior** [comment]
We made the change because it was a bug.  IMv6 support parentheses, the documentation reflects parentheses, and parenthesis is the expected spelling.  We could add `-respect-parenthesis` as a deprecated option.

**Comment by fmw42** [comment]
Originally IM 6 had only parenthesis (singular).  Parentheses (plural) was added later as an option because someone asked for it or mentioned that plural sounded more correct.  I have been using the singular in all my scripts, since the beginning when it was only singular.

So please add back the singular form as an optional spelling (for backward compatibility). Thanks.

**Comment by fmw42** [comment]
IM 7.1.1.37 beta, both singular and plural work for me.  Thanks very much.

**Comment by fmw42** [comment]
Resolved.
