### ISSUE TITLE
Incorrect rounding when converting bitfield BMP to 8-bit

### ISSUE THREAD

**Issue by profi200** [ImageMagick/ImageMagick#7579]
### ImageMagick version

7.1.1-36 Q16-HDRI x86_64 22352

### Operating system

Linux

### Operating system, version and so on

6.6.46-1-MANJARO

### Description

When converting BMP files that use bitfield compression with less than 8 bits per channel to 8 bits ImageMagick incorrectly rounds some colors. Expected behavior is nearest rounding. GIMP for example does it correctly.

I could not find where exactly the conversion happens in the code but i may just as well offer the solution. These functions have been fully tested and they round to nearest without floating point math.
https://gist.github.com/profi200/20a9ccf36143fb0c2966b36b2e227c73

### Steps to Reproduce

`magick ./2024_03_20_01_07_51.bmp ./out_magick.png`

### Images

Original BMP file:
[2024_03_20_01_07_51.bmp.zip](https://github.com/user-attachments/files/16762765/2024_03_20_01_07_51.bmp.zip)

Converted with ImageMagick:
![out_magick](https://github.com/user-attachments/assets/7caa44c8-1a1d-4cde-8d4b-550b132fdaee)

Converted with GIMP:
![out_gimp](https://github.com/user-attachments/assets/61b97acf-3d37-44df-8fa5-a17d4c41efe6)

Also see here for how i create such BMP files. They are a little bit unusual but should be covered by the standards.
https://github.com/profi200/open_agb_firm/blob/50e2f30e0d578adc048bd4d3ee9496f23f8b9922/source/arm11/oaf_video.c#L228

**Comment by urban-warrior** [comment]
We get an exact reproduction of the source image with your command:

```
$ magick ./2024_03_20_01_07_51.bmp ./out_magick.png
$ magick compare -metric rmse out_magick.png 2024_03_20_01_07_51.bmp x:
0 (0) 
```

There is no distortion at all as expected.     How can we reproduce the issue you are having?

**Comment by profi200** [comment]
One way to see the difference is opening the BMP file in GIMP and opening the ImageMagick created png as layer. Then magnify to 400% (to make navigation easier) and take a sample from pixel position 81,35 (bottom left corner shows the position). On the BMP layer this gives a red value of 0x19 and the PNG layer previously converted with ImageMagick is 0x18.

Method 2:
```
$ magick ./2024_03_20_01_07_51.bmp ./out_magick.rgb
$ magick ./out_gimp.png ./out_gimp.rgb
$ sha256sum ./out_magick.rgb
3c3b7c32468a6da4c2c3d8538657023eb60e708222a08a3a86cf1e97ae75006c  ./out_magick.rgb
$ sha256sum ./out_gimp.rgb
d89b36d63e7368ce3f025c7c1ab2e0ecc7ac3f5a061fee5449b8d7794765385b  ./out_gimp.rgb
```
You see the raw pixels don't match.

**Comment by fmw42** [comment]
With IM 7.1.1.37 on Mac OSX Ventura, I get

```
magick 2024_03_20_01_07_51.bmp 2024_03_20_01_07_51.png
magick compare -metric rmse 2024_03_20_01_07_51.bmp 2024_03_20_01_07_51.png null:
0 (0) 

```

So the files are identical.

**Comment by profi200** [comment]
Quick and dirty test program. You can clone lodepng from [here](https://github.com/lvandeve/lodepng).
```CPP
// License: Do what you want. I don't care.

#include <algorithm>
#include <math.h>
#include <memory>
#include <cstdio>
#include <cinttypes>
#include "lodepng.h"


typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;

typedef int8_t  s8;
typedef int16_t s16;
typedef int32_t s32;
typedef int64_t s64;



// Compile with "g++ -std=c++17 -s -flto -O2 -fstrict-aliasing -ffunction-sections -Wall -Wextra -I./lodepng -Wl,--gc-sections ./lodepng/lodepng.cpp ./magick_test.cpp -lm -o ./magick_test"
int main(int argc, char const *argv[])
{
	if(argc != 3)
	{
		puts("Usage: magick_test input_bmp output_png");
		return 1;
	}

	const std::unique_ptr<u8[]> buf(new(std::nothrow) u8[240 * 160 * 3]);
	if(!buf)
	{
		fputs("Out of memory.", stderr);
		return 2;
	}

	u8 *buf8Ptr = buf.get();
	u16 *buf5Ptr = (u16*)(buf8Ptr + ((240 * 160 * 3) - (240 * 160 * 2)));
	FILE *f = fopen(argv[1], "rb");
	fseek(f, 0x80, SEEK_SET);
	fread(buf5Ptr, 240 * 160 * 2, 1, f);
	fclose(f);

	constexpr float mult = 8.225806451612903225806f; // 255 / 31.
	u32 i = 0;
	do
	{
		const u16 rgb15 = *buf5Ptr++; // Lowest bit is unused alpha. Rest is 15 bit RGB with swapped channels.
		buf8Ptr[0] = lroundf((rgb15>>11) * mult);
		buf8Ptr[1] = lroundf(((rgb15>>6) & 0x1Fu) * mult);
		buf8Ptr[2] = lroundf(((rgb15>>1) & 0x1Fu) * mult);
		buf8Ptr += 3;
	} while(++i < 240 * 160);

	const u32 lpngErr = lodepng_encode24_file(argv[2], buf.get(), 240, 160);
	if(lpngErr)
	{
		fprintf(stderr, "lodepng error: %s", lodepng_error_text(lpngErr));
		return 3;
	}

	return 0;
}
```

Test output:
```
$ g++ -std=c++17 -s -flto -O2 -fstrict-aliasing -ffunction-sections -Wall -Wextra -I./lodepng -Wl,--gc-sections ./lodepng/lodepng.cpp ./magick_test.cpp -lm -o ./magick_test
$ ./magick_test ./2024_03_20_01_07_51.bmp ./out_magick_test.png
$ magick ./2024_03_20_01_07_51.bmp ./out_magick.rgb
$ magick ./out_gimp.png ./out_gimp.rgb
$ magick ./out_magick_test.png ./out_magick_test.rgb
$ sha256sum ./out_gimp.rgb
d89b36d63e7368ce3f025c7c1ab2e0ecc7ac3f5a061fee5449b8d7794765385b  ./out_gimp.rgb
$ sha256sum ./out_magick.rgb
3c3b7c32468a6da4c2c3d8538657023eb60e708222a08a3a86cf1e97ae75006c  ./out_magick.rgb
$ sha256sum ./out_magick_test.rgb
d89b36d63e7368ce3f025c7c1ab2e0ecc7ac3f5a061fee5449b8d7794765385b  ./out_magick_test.rgb
```
As you can see the output of my test program is identical to the output of GIMP. ImageMagick's output differs.

And here are the rounding errors in a hex editor:
![gimp_vs_magick](https://github.com/user-attachments/assets/39ea67df-82f3-4613-b84e-e19705e39075)

**Comment by urban-warrior** [comment]
ImageMagick uses floating point rounding, presumably more accurate than the integer algorithm you use.

**Comment by profi200** [comment]
The code i just posted does use floating point and lroundf() which rounds to nearest integer. It's the other way around. ImageMagick uses integer math. More specififcally it uses the common bitwise shift and bitwise or technique. Here is the proof.

```CPP
// License: Do what you want. I don't care.

#include <algorithm>
#include <math.h>
#include <memory>
#include <cstdio>
#include <cinttypes>
#include "lodepng.h"


typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;

typedef int8_t  s8;
typedef int16_t s16;
typedef int32_t s32;
typedef int64_t s64;



// Compile with "g++ -std=c++17 -s -flto -O2 -fstrict-aliasing -ffunction-sections -Wall -Wextra -I./lodepng -Wl,--gc-sections ./lodepng/lodepng.cpp ./magick_test.cpp -lm -o ./magick_test"
int main(int argc, char const *argv[])
{
	if(argc != 3)
	{
		puts("Usage: magick_test input_bmp output_png");
		return 1;
	}

	const std::unique_ptr<u8[]> buf(new(std::nothrow) u8[240 * 160 * 3]);
	if(!buf)
	{
		fputs("Out of memory.", stderr);
		return 2;
	}

	u8 *buf8Ptr = buf.get();
	u16 *buf5Ptr = (u16*)(buf8Ptr + ((240 * 160 * 3) - (240 * 160 * 2)));
	FILE *f = fopen(argv[1], "rb");
	fseek(f, 0x80, SEEK_SET);
	fread(buf5Ptr, 240 * 160 * 2, 1, f);
	fclose(f);

	//constexpr float mult = 8.225806451612903225806f; // 255 / 31.
	u32 i = 0;
	do
	{
		/*const u16 rgb15 = *buf5Ptr++; // Lowest bit is unused alpha. Rest is 15 bit RGB with swapped channels.
		buf8Ptr[0] = lroundf((rgb15>>11) * mult);
		buf8Ptr[1] = lroundf(((rgb15>>6) & 0x1Fu) * mult);
		buf8Ptr[2] = lroundf(((rgb15>>1) & 0x1Fu) * mult);*/
		const u16 rgb15 = *buf5Ptr++; // Lowest bit is unused alpha. Rest is 15 bit RGB with swapped channels.
		const u8 r = rgb15>>11;
		const u8 g = (rgb15>>6) & 0x1Fu;
		const u8 b = (rgb15>>1) & 0x1Fu;
		buf8Ptr[0] = r<<3 | r>>2;
		buf8Ptr[1] = g<<3 | g>>2;
		buf8Ptr[2] = b<<3 | b>>2;
		buf8Ptr += 3;
	} while(++i < 240 * 160);

	const u32 lpngErr = lodepng_encode24_file(argv[2], buf.get(), 240, 160);
	if(lpngErr)
	{
		fprintf(stderr, "lodepng error: %s", lodepng_error_text(lpngErr));
		return 3;
	}

	return 0;
}
```

Result:
```
$ g++ -std=c++17 -s -flto -O2 -fstrict-aliasing -ffunction-sections -Wall -Wextra -I./lodepng -Wl,--gc-sections ./lodepng/lodepng.cpp ./magick_test.cpp -lm -o ./magick_test
$ ./magick_test ./2024_03_20_01_07_51.bmp ./out_magick_test.png
$ magick ./out_magick_test.png ./out_magick_test.rgb
$ sha256sum ./out_magick_test.rgb
3c3b7c32468a6da4c2c3d8538657023eb60e708222a08a3a86cf1e97ae75006c  ./out_magick_test.rgb
```
Hash matches out_magic.rgb from previous post.

**Comment by urban-warrior** [comment]
ImageMagick implemented a general framework to handle any legit BMP bit depth and mask for each component, RGB.  We now need to extend the framework to account for rounding rather than bit lopping.  We'll need a few days to review the code and see if we can implement rounding.

**Comment by profi200** [comment]
If you need more combinations of bit depth conversion functions i can make more. The gist i linked above only contains the ones i needed and i verified them against the actual floating point math. I literally bruteforced the constants for the lack of coming up with a better way to find exactly matching slopes.

**Comment by urban-warrior** [comment]
We have adjusted the algorithm to ensure more pixels match your test case. However, there is still an off-by-one error in another use case. Since our algorithm does not use floating-point arithmetic, this outcome is not unexpected. For now, we will continue using integer bit shifting rather than floating-point operations, as the current algorithm is robust and sensitive to the BMP header bit masks and bit shifts, not just to the 555 use case.

**Comment by profi200** [comment]
Well, i have given a solution to the problem that works. I agree it's not very flexible because it needs different constants for every bit depth combination but it's almost as fast as bitwise shift + or.

Copying the gist in here so it doesn't get lost.
```C
// License: Do what you want. I don't care.

/**
 * @brief      Converts 8-bit RGBA components to 4-bit with nearest rounding.
 *
 * @param[in]  c     The 8-bit color component.
 *
 * @return     The color component converted to 4-bit format.
 */
static inline u32 rgbEight2Four(const u32 c)
{
	// No rounding errors for 0-255.
	return (15 * c + 135)>>8;
}

/**
 * @brief      Converts 8-bit RGBA components to 5-bit with nearest rounding.
 *
 * @param[in]  c     The 8-bit color component.
 *
 * @return     The color component converted to 5-bit format.
 */
static inline u32 rgbEight2Five(const u32 c)
{
	// No rounding errors for 0-255.
	return (249 * c + 1024)>>11;
}

/**
 * @brief      Converts 8-bit RGBA components to 6-bit with nearest rounding.
 *
 * @param[in]  c     The 8-bit color component.
 *
 * @return     The color component converted to 6-bit format.
 */
static inline u32 rgbEight2Six(const u32 c)
{
	// No rounding errors for 0-255.
	return (253 * c + 512)>>10;
}

/**
 * @brief      Converts 4-bit RGBA components to 8-bit with nearest rounding.
 *
 * @param[in]  c     The 4-bit color component.
 *
 * @return     The color component converted to 8-bit format.
 */
static inline u32 rgbFour2Eight(const u32 c)
{
	// No rounding errors for 0-15.
	return 17 * c;
}

/**
 * @brief      Converts 5-bit RGBA components to 8-bit with nearest rounding.
 *
 * @param[in]  c     The 5-bit color component.
 *
 * @return     The color component converted to 8-bit format.
 */
static inline u32 rgbFive2Eight(const u32 c)
{
	// No rounding errors for 0-31.
	return (527 * c + 23)>>6;
}

/**
 * @brief      Converts 6-bit RGBA components to 8-bit with nearest rounding.
 *
 * @param[in]  c     The 6-bit color component.
 *
 * @return     The color component converted to 8-bit format.
 */
static inline u32 rgbSix2Eight(const u32 c)
{
	// No rounding errors for 0-63.
	return (259 * c + 33)>>6;
}
```

**Comment by urban-warrior** [comment]
Review https://github.com/ImageMagick/ImageMagick/blob/main/coders/bmp.c#L1380 which is a robust implementation that accounts for various BMP bit masks and shifts.  Present your floating point solution as a Github pull request and we review for inclusion in a future release of ImageMagick.
