### ISSUE TITLE
Failed tests in validation suite, no decode delegate messages for various formats

### ISSUE THREAD

**Issue by bitsgalore** [ImageMagick/ImageMagick#758]
### Prerequisites

- [X ] I have written a descriptive issue title
- [ ]X I have verified that I am using the latest version of ImageMagick
- [ X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Running the validation suite resulted in 2 failed tests. I've posted the full test suite log here:

<https://gist.github.com/bitsgalore/5244ddc7bbe22134c72d3673006614f1#file-test-suite-log>

The log reports numerous 'no decode delegate for this image format' messages for the PNG format. In actual fact I'm getting similar error messages for other formats when I run any of the IM tools. E.g.:

    identify test.tiff

results in:

    identify: no decode delegate for this image format `TIFF' @ error/constitute.c/ReadImage/509

I'm also getting this error for other formats  (e.g. JP2; strangely GIF works).

### Steps to Reproduce

I literally followed the instructions [here](https://www.imagemagick.org/script/install-source.php) ("install from Unix source").

### System Configuration

- ImageMagick version: 7.0.7-1
- Environment: Linux Mint MATE, 64 bit

**Comment by mikayla-grace** [comment]
ImageMagick depends on external delegate libraries for certain image formats such as PNG, TIFF, JPEG, etc.  When you configure ImageMagick. check the final output.  It lists which delegate libraries where validated ensuring support for those image formats.  If an image format you need is not validated, ensure the development version of the library that supports the image format is installed and try reconfiguring ImageMagick until the validation passes.  Once its does, your instance of ImageMagick will support the image format (e.g. PNG).

**Comment by bitsgalore** [comment]
@mikayla-grace thanks, I didn't know that. Just  tried this out by installing libtiff5-dev and libpng-dev, and after running `./config`, `make` and `make install` TIFF and PNG support now works! I'll close the issue now.
