### ISSUE TITLE
Can't use MagickWand in C project

### ISSUE THREAD

**Issue by Philosoph228** [ImageMagick/ImageMagick#7583]
### ImageMagick version

7.1.1-37 Q16-HDRI x64 1ffe565:20240824

### Operating system

Windows

### Operating system, version and so on

10

### Description

```
Error	C1189	#error:  ImageMagick was build with a 64 channel bit mask and that requires a C++ compiler	C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\include\MagickCore\magick-baseconfig.h	274
```
I can't use a C++ compiler. I need it done with C one, as my whole application is in C and compiling as a C project.

Have tried to comment out the causing string in magick-baseconfig.h, as I thought it's just header misconfiguration issue maybe.
```
/*
  The 64-bit channel mask requires a C++ compiler
*/
#if MAGICKCORE_CHANNEL_MASK_DEPTH == 64
#  if !defined(__cplusplus) && !defined(c_plusplus)
#    error ImageMagick was build with a 64 channel bit mask and that requires a C++ compiler
#  endif
#endif
```
But it gave more errors specific to C++ type definitions.

Normally library interfaces are made in C ABI, to use them in bunch of languages like Pascal, C. Even for Java, C++, as people write OOP wrappers for them importing and calling __cdecl, __stdcall functions. It isn't the case? So what's wrong? I can't just include "libraryname.h" header and just use it.

### Steps to Reproduce

Just tried to use MagickWand in C

### Images

main.c
```
#include <MagickWand/MagickWand.h>

int main()
{
    MagickWand* wand;

    MagickWandGenesis();    // Initialize MagickWand environment

    wand = NewMagickWand(); // Create a wand
    MagickReadImage(wand, "input.jpg"); // Read an image
    MagickResizeImage(wand, 100, 100, LanczosFilter);   // Resize the image
    MagickWriteImages(wand, "output.jpg", MagickTrue);  // Write the image

    DestroyMagickWand(wand);    // Clean up
    MagickWandTerminus();

    return 0;
}
```

**Comment by urban-warrior** [comment]
@dlemstra, any reasonable way to resolve this issue?  ImageMagick should support C compiler builds under Windows.  Do we need to issue separate 32-bit channel masks builds to ensure MagickWand can compile with a C compiler?

**Comment by snibgo** [comment]
In Windows 11, using the Gnu gcc build tools, IM can have MaxPixelChannels=64, and build C or C++ programs that link and run successfully.

My copy of `magick-baseconfig.h` doesn't have that check for requiring a C++ compiler.

**Comment by Philosoph228** [comment]
@snibgo maybe. But I'm sticking with msvc for developing for windows and switching to another toolset just isn't applicable for me. I don't want to use GNU toolchain or mix it/include in build process with msvc at all, sorry.

Even if MaxPixelChannels=64 build is implemented in C++, probably, why wouldn't just __cdecl C bindings be exported, or somewhat

> My copy of `magick-baseconfig.h` doesn't have that check for requiring a C++ compiler.
Mine installed from the ImageMagick website (https://imagemagick.org/).
The installer file was ImageMagick-7.1.1-37-Q16-HDRI-x64-dll.exe

**Comment by snibgo** [comment]
I don't use msvc and can't advise on that, sorry.

**Comment by dlemstra** [comment]
Our default builds Windows use 64bit channel masks and this only works when a C++ compiler is used in Visual Studio. This might change in future Visual Studio releases but for now this is a requirement. You can work around this by doing your own compilation of ImageMagick.
