### ISSUE TITLE
Perl module installation got broken between 7.1.1-25 and 7.1.1-38

### ISSUE THREAD

**Issue by akhuettel** [ImageMagick/ImageMagick#7602]
### ImageMagick version

7.1.1-38

### Operating system

Linux

### Operating system, version and so on

Gentoo Linux

### Description

The Perl bindings need to be installed where the Perl interpreter can find them, together with all the other Perl modules. 
For that purpose, the module build system queries Perl for the relevant paths and sets the directories accordingly.
This was broken by commits 2d5edb26e22dd34ac1e43936b5c461bf0dbdb03a and c09d35f22090585a0357ecfbd58786022a37aae7 , leading to an essentially random installation location.

For example, /usr/lib/perl5/... when everything else is in /usr/lib64/perl5/...
See also https://bugs.gentoo.org/939324

I would like to strongly suggest that the two commits are reverted. 
I suspect issue #7191 may have been caused by a broken Perl installation or sillyness in the environment.

Andreas (Gentoo Linux Perl packager)

### Steps to Reproduce

Build 7.1.1-38, compare file list with 7.1.1-25

### Images

not applicable

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
