### ISSUE TITLE
Documentation issue for APNG

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#7603]
### ImageMagick version

7.1.1.38

### Operating system

MacOS

### Operating system, version and so on

Ventura

### Description

On the formats page at https://imagemagick.org/script/formats.php#supported please include a note that APNG **requires ffmpeg** installed for reading or writing, whichever one or both is applicable.

### Steps to Reproduce

not applicable

### Images

not applicable

**Comment by urban-warrior** [comment]
We updated the docs as you suggested.
