### ISSUE TITLE
Documentation issue for command line tools

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#7605]
### ImageMagick version

7.1.1.38

### Operating system

MacOS

### Operating system, version and so on

Ventura

### Description

At https://imagemagick.org/script/sitemap.php#command-line, in the section for command line tools, identify should be magick identify.

Change

[identify](https://imagemagick.org/script/identify.php): describes the format and characteristics of one or more image files.

to

[magick identify](https://imagemagick.org/script/identify.php): describes the format and characteristics of one or more image files.

### Steps to Reproduce

not applicable

### Images

not applicable

**Comment by urban-warrior** [comment]
Thanks for alerting us to this issue.  Fixed.
