### ISSUE TITLE
Legacy convert.exe is missing after installing on Windows

### ISSUE THREAD

**Issue by whowrotethiscode** [ImageMagick/ImageMagick#7608]
### ImageMagick version

7.1.1-38

### Operating system

Windows

### Operating system, version and so on

Windows 10

### Description

Hello,

When using the current Windows installer:

    ImageMagick-7.1.1-38-Q16-HDRI-x64-dll.exe

It offers the following option during installation
to Windows version 10:

    [x] Install legacy utilities (eg convert)

But after completing the installation
convert.exe is missing.

Please see the attached screenshots.

Thanks.

### Steps to Reproduce

1. Run ImageMagick-7.1.1-38-Q16-HDRI-x64-dll.exe
2. Enable the "Install legacy utilities" option during installation
3. convert.exe is missing after the installation is completed

### Images

![windows-install-dialog](https://github.com/user-attachments/assets/cf380cfa-6da1-43f0-9174-3d18f3c8918f)

![windows-explorer-after-install](https://github.com/user-attachments/assets/366b3255-8b17-4424-8ac6-8639f674b2ba)

**Comment by dlemstra** [comment]
It looks like we need to update the text in the interface. We no longer install the `convert.exe` file when that option is selected. You will now need to use `magick.exe`. This option only installs binaries like `identify.exe` and `mogrify,exe`,

**Comment by whowrotethiscode** [comment]
Hello,

> We no longer install the `convert.exe` file when that option is selected.

It is surprising that previous versions of Imagemagick 7.x provided `convert.exe`
but the current version of Imagemagick 7.x does not provide `convert.exe`
when selecting the `Install legacy utilities` option.

Is this change documented somewhere?

The "_Command Changes_" section of [porting.php](https://www.imagemagick.org/script/porting.php)
suggests that `convert.exe` (and others) should still be available.

**Comment by dlemstra** [comment]
That page should also be updated. Feel free to open pull requests to help us with that.

**Comment by dlemstra** [comment]
I have updated the documentation. It will take a while before this will show up on our website, this process is not automated (yet).

**Comment by whowrotethiscode** [comment]
Hello,

> I have updated the documentation

Ok thanks.

It is still surprising that `convert.exe`
was provided in previous versions of Imagemagick 7.1.x
but is no longer provided in current versions of Imagemagick 7.1.x

Why remove some legacy binaries (`convert.exe`)
but keep others (`identify.exe, mogrify.exe`)?

**Comment by dlemstra** [comment]
`identify.exe` is just a shortcut for `magick identify` and that is the same case for the other executables. But `convert` is the legacy syntax version of `magick` and should not be used anymore. This was also possible with `magick convert` but support for this has been removed in the Windows release and that is also why `convert.exe` was removed.
