### ISSUE TITLE
Windows installation win: and show: don't work

### ISSUE THREAD

**Issue by PeteMWilson** [ImageMagick/ImageMagick#7609]
### ImageMagick version

7.1.1-38 Q16-HDRI x64

### Operating system

Windows

### Operating system, version and so on

Windows 10 21H2

### Description

After installation, a test is suggested to verify magick is working. The test says create wizard.jpq than display it using
`magick wizard.jpg win:`
but that results in an error message:
`magick: unable to open image 'win:': Invalid argument @ error/blob.c/OpenBlob/3596.`

What should the proper test be?

### Steps to Reproduce

Install magick on Windows 10. Open command prompt to writeable folder. Run
`magick wizard: wizard.jpg`
`magick wizard.jpg win:`
See error message.

### Images

n/a

**Comment by dlemstra** [comment]
Thanks for reporting this. We will no longer be showing this document after the installation of ImageMagick. You could use `magick wizard.jpg info:` instead of `win:`

**Comment by PeteMWilson** [comment]
Is there no replacement for win: built-in to magick.exe anymore?

Could it be added by editing delegates.xml?

**Comment by dlemstra** [comment]
We no longer include the ancient IMDisplay.exe execute that was used for this so you cannot update the delegates to get this back. 

If you want to view images for formats that are not supported with the default image viewers on Windows I would advise you to install ImageGlass. This use ImageMagick under the hood.

**Comment by fmw42** [comment]
You should be able to create a new line in the delegates.xml file for some viewer on Windows. You probably could call it win if you want. One of the Windows users might be able to help you to create that or show you how they do it.

**Comment by snibgo** [comment]
If your Windows computer is setup so that...
```
explorer x.png
```
... will run a program that displays `x.png` (use any PNG filename you want), then add this to delegates.xml:
```
  <delegate decode="png" encode="expl" command="cmd.exe /c (move &quot;%i&quot; &quot;%i.png&quot; >nul) &amp; &quot;explorer&quot; &quot;%i.png&quot;"/>
```

**Comment by PeteMWilson** [comment]
I don't believe Windows File Explorer works like that?

Did you mean "start"?
