### ISSUE TITLE
Support for QTIF images

### ISSUE THREAD

**Issue by manfromarce** [ImageMagick/ImageMagick#7618]
### Describe the solution you'd like

QTIF is an image "container" used by QuickTime on both MacOS and Windows. It contains a descriptive part and a data part which can be JPEG or, in theory, any compressed format. So the image itself is already supported by ImageMagick in many cases once extracted, or at least it can attempt to read it like any other file.
It would be nice to have decoding support in ImageMagick, writing in this format probably doesn't make sense since it's now deprecated.
QTIF images may be found with the .qtif, .qif and .qti file extensions.
Documentation on the format can be found on the Apple website: [https://developer.apple.com/documentation/quicktime-file-format/appendix_a_quicktime_image_file_format](https://developer.apple.com/documentation/quicktime-file-format/appendix_a_quicktime_image_file_format).
Sample files: 
[qtif.zip](https://github.com/user-attachments/files/17003424/qtif.zip)
Also, the GdkBuf library seems to be able to read QTIF: [https://github.com/djdeath/gdk-pixbuf/blob/master/gdk-pixbuf/io-qtif.c](https://github.com/djdeath/gdk-pixbuf/blob/master/gdk-pixbuf/io-qtif.c)

**Comment by urban-warrior** [comment]
The documentation you recommended suggested this format is deprecated and is not to be used for new development.

**Comment by manfromarce** [comment]
Yes, I know, it would be only for converting existing images to JPEG or PNG. ImageMagick already support many old formats

**Comment by fmw42** [comment]
I know nothing about QTIF, but out of curiosity, what is your purpose for using QTIF?  Is there not any other format that would suit? Do you have some tool that only uses QTIF?

**Comment by urban-warrior** [comment]
Since QTIF is not recommended for development, we prefer not to accept a PR got QTIF. Instead, consider writing a utility to extract images from the QTIF frame. ImageMagick can then be used to read/view the extracted images.
