### ISSUE TITLE
Smartcrop is failing in latest ImageMagick

### ISSUE THREAD

**Issue by contactsmrajesh** [ImageMagick/ImageMagick#7628]
### ImageMagick version

7.1.1-36

### Operating system

Windows

### Operating system, version and so on

11

### Description

We were using smartcrop library to crop images, which was using ImageMagick under the hood. The functionality is working fine if we are using ImageMagick version 7.1.1-15, but with latest versions it is failing with below error, 

Error: Stream yields empty buffer
    at Socket.<anonymous> (C:\smart\smartcrop\node_modules\gm\lib\command.js:57:17)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

### Steps to Reproduce

Execute smartcrop command, 
smartcrop --width 100 --height 100 avatar.jpg

### Images

![4k-wallpaper-autumn-leaves-blur-1477459](https://github.com/user-attachments/assets/f0ddd035-4918-4fad-a534-cd9661e171a2)

**Comment by fmw42** [comment]
We know nothing about the smart crop library.  I recommend that you contact the smart crop developers and find out if there is some restriction on IM version. They should test with the latest version of IM to be sure their software is compatible.  

Can you provide the Imagemagick command that smart crop is using for your image?

Your smart crop command:

smartcrop --width 100 --height 100 avatar.jpg

does not specify the start point (upper left corner of the 100x100 crop). Does smart crop need that or does it default to offsetx=0 and offsety=0 (or whatever terms they use)?  An offset in x and y is needed with IM or it will do a tiled crop and produce many output crops.

**Comment by urban-warrior** [comment]
There are many `smartcrop` utilities, we identified at least 8.  Which one are you using?  And have you installed the ImageMagick nodeJS wrapper?  The `gm` path in the exception is not an ImageMagick path.

**Comment by contactsmrajesh** [comment]
We are using smartcrop-cli from below,

https://github.com/jwagner/smartcrop-cli

Yes we have installed imagemagick nodejs wrapper.

In the smartcrop-cli.js I can see it is redirecting to imagemagick by below code,
var gm = require('gm').subClass({ imageMagick: true });

Below are the versions,
Node: 20.15.1
Smartcrop cli: 2.0.3
ImageMagick: 7.1.1.36
gm: 1.23.1

**Comment by fmw42** [comment]
what is the "gm" for?  looks like offloading to GraphicsMagick to me, not Imagemagick. "require('gm')"!

**Comment by fmw42** [comment]
Imagemagick requires not only width and height, but also the top left corner x,y for a crop. Your software has an argument faceDetection: 'perform faceDetection using opencv', which is boolean. The docs don't say whether that default is true or false.  If true, then you must be doing face detection with OpenCV. Do you have OpenCV installed?  If false, how are you supplying the X,Y for the top left corner of the crop?

**Comment by urban-warrior** [comment]
We installed smartcrop on a Fedora system with ImageMagick 7.1.1-38 and got expected results:

```
$ smartcrop --width 100 --height 100 avatar.jpg thumb.jpg
{
  "topCrop": {
    "x": 0,
    "y": 1920,
    "width": 4000,
    "height": 4000,
    "score": {
      "detail": 28.031107075234363,
      "saturation": 13.862143921322126,
      "skin": 11.565455899556554,
      "boost": 0,
      "total": 0.0030582685210645308
    }
  }
}
$ identify thumb.jpg 
thumb.jpg JPEG 100x100 100x100+0+0 8-bit sRGB 8094B 0.000u 0:00.000
```

The thumbnail looked reasonable.

**Comment by contactsmrajesh** [comment]
Thanks for all your responses, I just tested it in windows,
with magick version: 7.1.1-15

cmd: node smartcrop-cli.js C:\test\images\test1.jpg

{
  "topCrop": {
    "x": 0,
    "y": 1992,
    "width": 4000,
    "height": 4000,
    "score": {
      "detail": 1427.5076370436789,
      "saturation": 1273.325115335588,
      "skin": 480.27623705773163,
      "boost": 0,
      "total": 0.00009574976804458306
    }
  }
}
with magick version: 7.1.1-38
Error: Stream yields empty buffer
    at Socket.<anonymous> (C:\work\source\rma\smartcrop\node_modules\gm\lib\command.js:57:17)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Is there a way to print error, when magick is used in tools like smartcrop like a flag or something i can pass to debug the error.

**Comment by contactsmrajesh** [comment]
The problem is, latest image magick no longer supports legacy "convert" command, and expects command to be "magick". To fix this, performed below actions,

1. Force gm(ghostMagick) to use "magick" comand, this is done by modifying to below code in, smarcrop-cli.js, index.js(smartcrop-gm), example.js(smartcrop-gm)
var gm = require('gm').subClass({ imageMagick: '7+' });
2. Upgraded gm to latest version 1.25.0 and also its corresponding dependencies.
After above 2 fixes, it is working fine.

**Comment by fmw42** [comment]
Dirk, another reason to revert the deprecation of convert  - outside tools still require the name "convert"

**Comment by fmw42** [comment]
@contactsmrajesh Did you try a symbolic link from convert to magick?

**Comment by contactsmrajesh** [comment]
@fmw42 I am not aware of that option to link it, I didn't try that.

**Comment by contactsmrajesh** [comment]
@fmw42 In linux it does create symbolic link and it is working. Only issue is in windows environment, where the convert.exe is not present(even though I selected install legacy convert during installation process). I tried to manually copy the magick.exe to convert.exe, it is working fine.

**Comment by fmw42** [comment]
Correct. Legacy convert.exe has been removed as deprecated long enough.
