### ISSUE TITLE
convert spits out unrelated errors.

### ISSUE THREAD

**Issue by john123903** [ImageMagick/ImageMagick#7636]
### ImageMagick version

7.1.1

### Operating system

Windows

### Operating system, version and so on

22H2

### Description

I tried to run 
```powershell
convert --version
``` 
into the console. turns out that it doesn't do that and all it does is spit out errors that i don't think it is really convert.
```powershell
C:\Users\[CENSORED]\Documents\git\yt2009>convert
Must specify a file system

C:\Users\[CENSORED]\Documents\git\yt2009>convert --version
Invalid drive specification.
``` 

is it me or is this convert?

### Steps to Reproduce

```
C:\Users\[CENSORED]\Documents\git\yt2009>convert
Must specify a file system

C:\Users\[CENSORED]\Documents\git\yt2009>convert --version
Invalid drive specification.

C:\Users\[CENSORED]\Documents\git\yt2009>convert
Must specify a file system
```

### Images

![image](https://github.com/user-attachments/assets/c3537fa4-469b-4885-85d9-520c8b14682c)

**Comment by fmw42** [comment]
It looks to me like ou are using the Windows convert.exe not the Imagemagick convert.exe.  Also convert is now deprecated in Imagemagick. Use IM 7 magick.exe, not convert.exe

**Comment by snibgo** [comment]
As fmw42 says. Try:
```
magick -version
```

**Comment by john123903** [comment]
> As fmw42 says. Try:
> 
> ```
> magick -version
> ```

but when i run post_config_setup.js, they want convert!

**Comment by snibgo** [comment]
Whoever supplied `post_config_setup.js` should alter it to use `magick`.
