### ISSUE TITLE
A command example in the docs doesn't work as intended

### ISSUE THREAD

**Issue by lkintact** [ImageMagick/ImageMagick#7637]
### ImageMagick version

7.1.1-37 Q16-HDRI x64 1ffe565:20240824

### Operating system

Windows

### Operating system, version and so on

Windows 10 Home

### Description

I tried executing this set of commands given in `www/composite.html` (replacing `'` with `"` and `\` with `^`, as I'm on MS-Windows):
```
magick -size 70x70 canvas:none -fill red -draw 'circle 35,35 10,30' red-circle.png
magick -size 70x70 canvas:none -draw 'circle 35,35 35,20' -negate \
  -channel A -gaussian-blur 0x8 white-highlight.png
magick composite -compose atop -geometry -13-17 white-highlight.png red-circle.png red-ball.png
```
However, the result (the attached image below) differs from what is shown in the docs.

### Steps to Reproduce

.

### Images

![red-ball_incorrect](https://github.com/user-attachments/assets/d3ef52cd-4e1f-400c-baee-95d8336c7e11)

**Comment by fmw42** [comment]
Please link to the example page. Also show your Windows converted command.

**Comment by lkintact** [comment]
> Please link to the example page.

This is the example page: https://imagemagick.org/script/composite.php.

> Also show your Windows converted command.

This is the commands I execute:
1. `magick -size 70x70 canvas:none -fill red -draw "circle 35,35 10,30" red-circle.png`
2. `magick -size 70x70 canvas:none -draw "circle 35,35 35,20" -negate -channel A -gaussian-blur 0x8 white-highlight.png`
3. `magick composite -compose atop -geometry -13-17 white-highlight.png red-circle.png red-ball.png`

**Comment by snibgo** [comment]
The problem is in the middle command. V6 would negate just the colour channels. V7 by default also negates the alpha channel. So this is better:
```
magick -size 70x70 canvas:none -draw "circle 35,35 35,20" -channel RGB -negate -channel A -gaussian-blur 0x8 white-highlight.png
```

**Comment by urban-warrior** [comment]
Updated the documentation with @snibgo's mod.
