### ISSUE TITLE
Ligatures are not displayed for Arabic text on image

### ISSUE THREAD

**Issue by Raduh** [ImageMagick/ImageMagick#764]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When trying to use an Arabic font to render Arabic text on a image, ligatures (character joins) are not displayed.
This is the font I would like to use: https://www.google.com/get/noto/#naskh-arab

### Steps to Reproduce
1. Fetch the font from https://www.google.com/get/noto/#naskh-arab.
2. Use any input image (size 300+x300+ should be fine).
3. Run the following command:
`convert -background lightblue -fill blue -pointsize 48 -font NotoSansArabic-Regular.ttf -direction right-to-left -annotate +450+250 "هذا اختبار"  input.jpg output.jpg`
4. The output characters on the image will be drawn individually without ligatures.

### System Configuration

- ImageMagick version:  7.0
- Environment (Operating system, version and so on): CentOS

**Comment by mikayla-grace** [comment]
Does your instance of ImageMagick include support for Freetype (font rendering) and RAQM (complex text layout).  Check with `convert -version`.  The Delegates should include TTF and RAQM.  We did not find NotoSansArabic-Regular.ttf in the link you posted, instead we used NotoNaskhArabic-Regular.ttf and an expected rendering with ligatures. If all else fails, try using the Pango markup language @ https://www.imagemagick.org/Usage/text/#pango.

**Comment by Raduh** [comment]
@mikayla-grace, are you able to get the same result from c++ code?
-- Using `annotate()` on an image to render Arabic font.

**Comment by mikayla-grace** [comment]
We did not try C++, but there is no reason to believe it won't work.  Magick++ and the command-line are both wrappers to the same MagickCore API.

**Comment by Raduh** [comment]
It seems that with c++, not only are the ligatures omitted, but even the order is incorrect (not Right to Left).
I tried setting textDirection(DirectionType::RightToLeftDirection).

**Comment by urban-warrior** [comment]
In C++ are you passing text as UTF-8.  Make sure the high order byte is not being eliminated.  If you want us to investigate further, you'll need to post a Magick++ demonstration source code that illustrates the problem.  We'll use your demo source to test the problem in our environment.
