### ISSUE TITLE
Image magick cannot read monochrome TGA files

### ISSUE THREAD

**Issue by Fojtik** [ImageMagick/ImageMagick#7641]
### ImageMagick version

7.1.1-38-portable-Q8-x64 

### Operating system

Windows

### Operating system, version and so on

10

### Description

Image magick cannot read monochrome TGA files. There exists potentially 4 variants of unsupported TGA files. Monochrome, bi-color, 16 colors, 16 gray levels.

### Steps to Reproduce

O:\programs\ImageMagick-7.1.1-38-portable-Q8-x64>O:\programs\ImageMagick-7.1.1-38-portable-Q8-x64\magick.exe identify O:\src\GraphicsMagick\PerlMagick\t\input_mono.tga
O:\src\GraphicsMagick\PerlMagick\t\input_mono.tga TGA 53x67 53x67+0+0 8-bit Grayscale Gray 487B 0.000u 0:00.000
 
O:\programs\ImageMagick-7.1.1-38-portable-Q8-x64>magick.exe convert input_mono.tga input_mono.bmp
magick.exe: unable to open image 'convert': No such file or directory @ error/blob.c/OpenBlob/3596.
magick.exe: no decode delegate for this image format `' @ error/constitute.c/ReadImage/746.

----------------------------------------------------------------------------------------------------------------------------
But:
O:\programs\ImageMagick-7.1.1-38-portable-Q8-x64>gm IDENTIFY input_mono.tga
input_mono.tga TGA 53x67+0+0 PseudoClass 2c 8-bit 487 0.000u 0m:0.000009s
O:\programs\ImageMagick-7.1.1-38-portable-Q8-x64>gm CONVERT input_mono.tga input_mono.BMP
O:\programs\ImageMagick-7.1.1-38-portable-Q8-x64>

### Images

I can generate much more files of these types:
[tga.zip](https://github.com/user-attachments/files/17088677/tga.zip)

**Comment by snibgo** [comment]
Gimp 2.10.38 can't open either TGA file.

Exiftool says of both:
```
Error                           : Unknown file type
```
So, if IM has a bug, it is not complaining that the TGA files are bad.

**Comment by urban-warrior** [comment]
The command appears to work fine on our Linux systems, version 7.1.1-38:

```
$ magick identify input_mono.tga 
input_mono.tga TGA 53x67 53x67+0+0 8-bit Grayscale Gray 487B
```

**Comment by snibgo** [comment]
The command executes without complaint, but the result looks weird. The OP hasn't posted a version of what the image should look like, so we can't know.
```
magick input_mono.tga x.png
```
x.png is:

![x](https://github.com/user-attachments/assets/a1810f00-93ff-4015-8d09-30b78bcafdd1)

**Comment by Fojtik** [comment]
The image you display is correct. That is really monochrome dithered sample.

_O:\programs\ImageMagick-7.1.1-38-portable-Q8-x64>magick.exe input1_1.bmp input1_1.pcx
magick.exe: unable to open image 'input1_1.pcx': Permission denied @ error/blob.c/OpenBlob/3596._

sorry: _O:\programs\ImageMagick-7.1.1-38-portable-Q8-x64>magick.exe input1_1.bmp input1_1.bmp_ 
![input1_1](https://github.com/user-attachments/assets/0ebed0a0-65cd-4fae-b387-c824ace48754)

**Comment by Fojtik** [comment]
Sorry, I have forgotten that **im convert** is no longer used.

**Comment by snibgo** [comment]
@Fojtik: Okay, so IM can correctly read the two TGA files you have posted. Is that correct? So, is there a problem?

**Comment by Fojtik** [comment]
There is perhaps one cosmetic issue that bilevel gray image is considered as 8bit grayscale. But everything seems workable.

O:\programs\ImageMagick-7.1.1-38-portable-Q8-x64>magick.exe identify input1_1.tga
input1_1.tga TGA 640x480 640x480+0+0 **8-bit Grayscale** Gray 38418B 0.000u 0:00.000


I has been verify that even 2 color palette tha image works.

_O:\programs\ImageMagick-7.1.1-38-portable-Q8-x64>gm identify test_A.tga
d:\program files\graphicsmagick-1.4-q8\gm.exe identify: Data storage type is not supported (test_A.tga).                                                                                                           d:\program files\graphicsmagick-1.4-q8\gm.exe identify: Request did not return an image.

O:\programs\ImageMagick-7.1.1-38-portable-Q8-x64>magick.exe identify test_A.tga                                                                                                                                    test_A.tga TGA 576x720 576x720+0+0 8-bit sRGB 2c 51864B 0.000u 0:00.000_
