### ISSUE TITLE
imagemagick 7.x magick convert cannot handle convert and scale operations in one go, while it was possible in covert version 6.x

### ISSUE THREAD

**Issue by Dwokfur** [ImageMagick/ImageMagick#7642]
### ImageMagick version

7.1.1-38

### Operating system

Linux

### Operating system, version and so on

Gentoo-2.15

### Description

I previously making use of the capability of convert in imagemagick version 6.x to convert and scale images in one go.
For example:
`convert -format gif -scale 256 Image001.jpg Image001.gif`
Since imagemagick version 7.x this command displays a warning:
`WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"`
OK, I get it.
However if I issue the command according to the warning I either have to face with an error message:
`magick -format gif -scale 256 Image001.jpg Image001.gif`
`magick: no images found for operation '-scale' at CLI arg 3 @ error/operation.c/CLIOption/5481.`
or I still have to see the warning:
`magick convert -format gif -scale 256 Image001.jpg Image001.gif`
`WARNING: The convert command is deprecated in IMv7, use "magick" instead of "convert" or "magick convert"`

### Steps to Reproduce

Issue a convert that also scales an image.
How it is possible to convert and scale in one go without the warning since imagemagick 7.x?

### Images

It happens with every image I try to convert.

**Comment by Dwokfur** [comment]
Somewhat related issue:
https://github.com/ImageMagick/ImageMagick/issues/7484
However I have no clue about the correct syntax here...

**Comment by Dwokfur** [comment]
Solution:
`magick Image001.jpg -format gif -scale 256 Image001.gif`
Scale me...

**Comment by snibgo** [comment]
IM v7 executes options in the same order they appear in the command. It can't scale an image before it has read an image.

**Comment by Dwokfur** [comment]
> IM v7 executes options in the same order they appear in the command. It can't scale an image before it has read an image.

I see, but it would have been beneficial to have a heads up about the syntax change before old scripts start misbehaving suddenly after an upgrade.

**Comment by fmw42** [comment]
This was explained a long time ago during IM 6.  See https://imagemagick.org/Usage/basics/#why

**Comment by snibgo** [comment]
> ... suddenly after an upgrade.

Not "sudddenly". `magick` has been available for ten years. Since then, users have been encouraged to use it instead of `convert`. There has been a ten-year overlap with v6 and v7 syntax, to permit graceful and gentle migration.

**Comment by Dwokfur** [comment]
> > ... suddenly after an upgrade.
> 
> Not "sudddenly". `magick` has been available for ten years. Since then, users have been encouraged to use it instead of `convert`. There has been a ten-year overlap with v6 and v7 syntax, to permit graceful and gentle migration.

I have to admit I missed the above mentioned pieces of documentation. Apart from my whinning, I appreciate all the work developers invest in this application. Thanks: Dw.
