### ISSUE TITLE
A couple of typos in the docs

### ISSUE THREAD

**Issue by lkintact** [ImageMagick/ImageMagick#7649]
### ImageMagick version

7.1.1-38 Q16-HDRI x64 b0ab922:20240901

### Operating system

Windows

### Operating system, version and so on

10 Home

### Description

At https://imagemagick.org/script/command-line-options.php:
1. "Fully define the look of each frame of **an** GIF animation sequence"
2. "**An** simple alias for the -layers method "mosaic".

### Steps to Reproduce

.

### Images

.

**Comment by dlemstra** [comment]
Thanks for mentioning this. We have fixed this but it will take a while before this will show up on our website.

The code of our website is hosted in this project: https://github.com/ImageMagick/Website. Next time feel free to open a pull requests there.
