### ISSUE TITLE
Extracting EXIF thumbnails from JPEG images doesn't seem to work

### ISSUE THREAD

**Issue by lkintact** [ImageMagick/ImageMagick#7662]
### ImageMagick version

7.1.1-38 Q16-HDRI x64 b0ab922:20240901

### Operating system

Windows

### Operating system, version and so on

10 Home

### Description

Try executing `magick.exe furn.jpg thumbnail:thumb.jpg` ([furn.jpg](https://github.com/user-attachments/assets/5ae69673-dc2a-4c6f-8e4b-46ac841b8cbb)).
Instead of creating a `thumb.jpg` file, ImageMagick reports an error:
`magick.exe: image does not have a EXIF thumbnail ``thumb.jpg' @ error/thumbnail.c/WriteTHUMBNAILImage/190`, while `image.jpg` does have a thumbnail.

### Steps to Reproduce

.

### Images

.

**Comment by dlemstra** [comment]
Thanks for reporting this. I have pushed a patch that includes a fix for this and I am now able to get the following output image.
![thumb](https://github.com/user-attachments/assets/72b97fbc-c7b0-4133-93ad-fb71082cfab8)

This will be resolved in the next release.
