### ISSUE TITLE
A bug in placing text in PNG images

### ISSUE THREAD

**Issue by lkintact** [ImageMagick/ImageMagick#7670]
### ImageMagick version

7.1.1-39 Q16-HDRI x64 18ae555:20241005

### Operating system

Windows

### Operating system, version and so on

10 Home

### Description

Execute this command:
`magick.exe vs.png -gravity center -pointsize 100 -fill white -annotate +0+0 "center" result.png` ([vs.png](https://github.com/user-attachments/assets/36d3bab8-a9d5-40b4-9f1a-1053dcab87b3)).

Notice that the text in the result image, `result.png`, is not centered horizontally:

![result](https://github.com/user-attachments/assets/58ba8e50-c955-4a28-a2ec-fcc51791ffaa)

### Steps to Reproduce

.

### Images

.

**Comment by fmw42** [comment]
Add +repage after reading your input to clear the virtual canvas geometry.  IM 7.1.1.39 Mac OSX Ventura

`magick vs.png +repage -gravity center -pointsize 100 -fill white -annotate +0+0 "center" result.png`

![result](https://github.com/user-attachments/assets/6b04045e-90d1-480a-9fbc-569b3318618d)

**Comment by lkintact** [comment]
Thank you, @fmw42, that works. The fact that it didn't happen to the JPG version of the image misled me into thinking that's a bug... Closing the issue.

**Comment by fmw42** [comment]
JPG does not support virtual canvas, but PNG does.
