### ISSUE TITLE
Issues with links in the docs

### ISSUE THREAD

**Issue by lkintact** [ImageMagick/ImageMagick#7672]
### ImageMagick version

7.1.1-39 Q16-HDRI x64 18ae555:20241005

### Operating system

Windows

### Operating system, version and so on

10 Home

### Description

There are two issues with the download links in `www/download.html`: they 1) don't work, and 2) link obsolete (7.1.1-38) versions of IM. (Please note that I'm talking about a file that comes with IM distros, not the website).

### Steps to Reproduce

.

### Images

.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
