### ISSUE TITLE
"imagemagick.exe identify" incorrectly displays filenames with non-latin characters

### ISSUE THREAD

**Issue by lkintact** [ImageMagick/ImageMagick#7674]
### ImageMagick version

7.1.1-39 Q16-HDRI x64 18ae555:20241005

### Operating system

Windows

### Operating system, version and so on

10 Home

### Description

Suppose we have a file, `изображение.jpg`.

Execute `magick.exe identify изображение.jpg`.

IM outputs something like this:
`РёР·РѕР±СЂР°Р¶РµРЅРёРµ.jpg JPEG 486x600 486x600+0+0 8-bit sRGB 197499B 0.002u 0:00.001`. 
Notice that the filename is displayed incorrectly.

I tried to solve the issue with specifying the [-encoding](https://imagemagick.org/script/command-line-options.php#encoding) option:
`magick.exe identify -encoding Unicode изображение.jpg`,
but IM reports an error:
``identify: unrecognized option `-encoding' @ error/identify.c/IdentifyImageCommand/563.``.

`

### Steps to Reproduce

.

### Images

.

**Comment by snibgo** [comment]
In Windows 11, this works with no problem:
```
D:\temp>%IMG7%magick rose: изображение.jpg

D:\temp>%IMG7%magick identify изображение.jpg
изображение.jpg JPEG 70x46 70x46+0+0 8-bit sRGB 2664B 0.001u 0:00.000
```
Windows 10 doesn't handle UTF-8 filenames so easily. I no longer use Windows 10 so can't test this, but the solution is probably to change the code page: "`chcp 65001`" or perhaps "`chcp 1252`".

**Comment by lkintact** [comment]
> but the solution is probably to change the code page: "chcp 65001" or perhaps "chcp 1252".

Tried changing the code page with `chcp` to `65001`, `1252`, `866` and `1251`, that didn't help.

**Comment by dlemstra** [comment]
The `-encoding` option is used to specify the encoding of drawn text. I also don't have a Windows 10 machine anymore that I can use to test this and this seems to work fine under Windows 11. And with a work around being available I will close this issue as something that we won't fix. But we are of course open to pull requests in case there is a way to fix this.

**Comment by lkintact** [comment]
>One actually has to [turn on the UTF-8 locale OS-wide](https://superuser.com/a/1451686) I think (which could be the default now in Windows 11).

Thank you, @kmilos, that indeed solved the issue. Sorry it took me that long to answer.

To people facing a similar problem: be aware that turning on the UTF-8 locale OS-wide may cause some old applications that use 2-byte code pages (cp1251, cp866 etc) produce incorrect output.
