### ISSUE TITLE
Some command examples in the docs work not quite as intended

### ISSUE THREAD

**Issue by lkintact** [ImageMagick/ImageMagick#7678]
### ImageMagick version

7.1.1-39 Q16-HDRI x64 18ae555:20241005

### Operating system

Windows

### Operating system, version and so on

10 Home

### Description

There are two command examples in the [Command-line Tools: Montage](https://imagemagick.org/script/montage.php) section of the docs.

I tried executing them (with a bit of editing as I run MS-Windows) and got the following results:
1. For `magick.exe montage -background "#336699" -geometry +4+4 rose.jpg red-ball.png montage.jpg`:

![montage](https://github.com/user-attachments/assets/66d9dd12-3f37-4d0b-a0fc-b839e05aee08)

2. For `magick.exe montage -label %f -frame 5 -background "#336699" -geometry +4+4 rose.jpg red-ball.png frame.jpg`: 

![frame](https://github.com/user-attachments/assets/af3d93b0-2d58-4344-a84f-79309ea680fd)

Notice that in both cases the image of the rose is not centered vertically, while it is in the docs.

### Steps to Reproduce

.

### Images

.

**Comment by urban-warrior** [comment]
Thanks for alerting us to this issue.  We updated the documentation with the correct command-line.
