### ISSUE TITLE
doc: imagemagick winget install not present

### ISSUE THREAD

**Issue by ykhan21** [ImageMagick/ImageMagick#7681]
### ImageMagick version

7

### Operating system

Windows

### Operating system, version and so on

11

### Description

https://imagemagick.org/script/download.php

The documentation does not mention how to install imagemagick through winget.

### Steps to Reproduce

n/a

### Images

n/a

**Comment by dlemstra** [comment]
You could help us by adding that information in this repository: https://github.com/ImageMagick/Website?

**Comment by ykhan21** [comment]
@dlemstra, I made [a PR](https://github.com/ImageMagick/Website/pull/108).
I haven't be able to build the site locally, so I haven't fully tested.

**Comment by dlemstra** [comment]
Thanks for helping us with this. And next time you should try to use the dev container inside that project. It should start our website on your local machine.
