### ISSUE TITLE
Request .ico size support of 768px and 512px

### ISSUE THREAD

**Issue by jshengst** [ImageMagick/ImageMagick#7684]
### Is your feature request related to a problem? Please describe.

When using ImageMagick 7.1.1-39 to convert .ico icons, if the conversion parameters exceed 256xp (such as 512 and 768xp), the conversion will fail.

```
PS F:\tools> magick tt.jpg -define icon:auto-resize=512 icon2.ico
magick.exe: unable to open image 'tt.jpg': No such file or directory @ error/blob.c/OpenBlob/3596.
```

### Describe the solution you'd like

I hope magick can remove the resolution limit and support high-resolution ico (512, 768xp) format conversion.

### Describe alternatives you've considered

I found that 768xp is the size supported by Microsoft for win10 build 9926 in 2015.

I tried to use other software to solve it. For example, Axialis IconWorkshop supports up to 768xp .ico, but it is commercial software.

**Comment by snibgo** [comment]
According to https://en.wikipedia.org/wiki/ICO_(file_format), the maximum width and height is 255. The metadata for these are recorded in single bytes.

> I found that 768xp is the size supported by Microsoft for win10 build 9926 in 2015.

Please supply a reference for this.

**Comment by jshengst** [comment]
Hi，@snibgo
I saw an article about high-resolution ico icons in a software media published in January 2015. When I tried to trace the source, I did not find any official authoritative news.
This is probably the media's one-sided opinion. I apologize for not completing sufficient investigation in advance.

After doing some tests, I came to the conclusion that high-resolution ico is supported in modern Windows systems, whether for custom folders and application icons.
But the high-resolution scheme of the ico format seems to be undefined behavior; at the same time, Microsoft does not use high-resolution ico, and the necessity of using high-resolution ico is questionable.

Here are some of my attempts:

When I used a magical software called BeCyIconGrabber to extract the official icons of window 11, I found that no official ico icon had a resolution of more than 256xp (it seems that there are, but they are all blank, I am not sure).
I only found that a software called Marmoset Toolbag 5 used icos with a maximum of 512 and 786xp.

At the same time, I successfully compiled the VS default c++ desktop application using only 786xp ico in window 11.
(This 786xp ico file was created using Axialis IconWorkshop;
When Windows does not find an ico of the required size, it will automatically scale the closest ico)

**Comment by urban-warrior** [comment]
If the image size is greater than 256 and the compression is Zip or undefined, ImageMagick saves the image as PNG within the ICON file.  This is supported by the standard.

**Comment by jshengst** [comment]
@urban-warrior Hi, 
can you explain this in more detail? 
I don't quite understand. I tried to convert a 1024*1024px png to a 512px icon, but it didn't work.

```
PS F:\tool> magick tt.png -define icon:auto-resize=512 icon2.ico
magick.exe: InvalidDimensions `icon2.ico' @ error/icon.c/WriteICONImage/1044.
```

**Comment by urban-warrior** [comment]
Yikes!  There is an improper check for width/height < 256 when the ICON format supports > 256.  We'll add a patch to mitigate this issue in a day or two.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
