### ISSUE TITLE
JXR information is out of alphabetic order on the Supported Formats page

### ISSUE THREAD

**Issue by fmw42** [ImageMagick/ImageMagick#7686]
### ImageMagick version

7.1.1.39

### Operating system

MacOS

### Operating system, version and so on

Ventura

### Description

At https://imagemagick.org/script/formats.php#supported, the information about JXR is out of alphabetic order. It is listed between JPEG and JSON and should be after JXL, which is after JSON.

### Steps to Reproduce

See above

### Images

None

**Comment by dlemstra** [comment]
Thanks for reporting this Fred, pushed a patch to fix this. Next time please report website issues here instead: https://github.com/ImageMagick/Website/issues. It might take a while before this change will show up on our website.
