### ISSUE TITLE
A way to list commands and their arguments

### ISSUE THREAD

**Issue by q3cpma** [ImageMagick/ImageMagick#7688]
### Is your feature request related to a problem? Please describe.

Basically, I manually sandbox imagemagick through bubblewrap, but to do that in a more generic way, I need to parse the quite complex `magick` command line to find filenames. The issue is that `magick -list Command` is a great start, but I need the argument count and "type", like in `magick convert -help` or the man page (which aren't parseable without heuristics).

### Describe the solution you'd like

Either for `magick -list Command` to also list argument names, i.e. `-decipher filename`, which would break the API, or a `magick -list CommandVerbose` to do this. Or improve `magick -list CLI` to mention if `+opt` is available and put the arguments there.

I'm ready to write a patch if we agree on a syntax.

**Comment by dlemstra** [comment]
I don't think we should add this kind of help for our commands. We have documentation about this on our website and I don't think we should add this to the command line.

**Comment by q3cpma** [comment]
I see, guess I'll have to hardcode it then. Thought this was a coherent idea because of the already present CLI and Command listings.

**Comment by fmw42** [comment]
> magick convert -help

Note that for Imagemagick 7, use magick, not magick convert.

**Comment by q3cpma** [comment]
> > magick convert -help
> 
> Note that for Imagemagick 7, use magick, not magick convert.

This is in fact by design in this case, as `magick -help` is almost empty.
