### ISSUE TITLE
IM doesn't seem to see manually installed fonts on MS-Windows

### ISSUE THREAD

**Issue by lkintact** [ImageMagick/ImageMagick#7696]
### ImageMagick version

7.1.1-39 Q16-HDRI x64 18ae555:20241005

### Operating system

Windows

### Operating system, version and so on

Windows 10 Home

### Description

1. Install a new font, for example, [DejaVu Sans Mono](https://github.com/user-attachments/files/17384951/DejaVuSansMono.ttf.zip) (by downloading the archive, unzipping it, clicking on `DejaVuSansMono.ttf`, and clicking on "Install").
2. Execute `magick.exe -list font`.

Notice that the font is not present in the list and thus cannot be referenced by name with the `-font` option. (It can be referenced by absolute path though).

### Steps to Reproduce

.

### Images

.

**Comment by dlemstra** [comment]
I cannot reproduce your issue. Maybe the install did not add it to the registry? It might also be possible that you only installed the font for your current user? I am getting the following output:

```
  Font: DejaVu-Sans-Mono
    family: DejaVu Sans Mono
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: c:\windows\fonts\dejavusansmono.ttf
    index: 0
```

**Comment by lkintact** [comment]
> It might also be possible that you only installed the font for your current user?

Indeed, it was installed for the current user only, sorry, I didn't know it must be installed for all users to work...
I guess the issue can be closed, thank you.
