### ISSUE TITLE
Text gets truncated inside a textbox.

### ISSUE THREAD

**Issue by fscorrupt** [ImageMagick/ImageMagick#7698]
### ImageMagick version

7.1.1.39

### Operating system

Windows

### Operating system, version and so on

Win 11 23h2 -  22631.4317

### Description

You can see that the text gets truncated inside the box, even though there is enough space left:
![testimage_text](https://github.com/user-attachments/assets/3b53689a-88e0-4f4e-adb9-e531f6cdc040)

### Steps to Reproduce

this is the font i use in the example:
https://www.ffonts.net/Colus-Regular.font

So i calculate the Pointsize this way:
`magick.exe -size 1900x500 -font "C:\\PosterTemp\\Colus-Regular.ttf" -gravity center -fill black -interline-spacing 0 caption:"EL EQUIPO A" -format "%[caption:pointsize]" info:`
which returns: 299

Next i apply it to my testimage:
`magick.exe "C:\PosterTemp\temp\testimage.png" -gravity center -background None -layers Flatten ( -font "C:\\PosterTemp\\Colus-Regular.ttf" -pointsize "299" -fill "white" -size "1900x500" -background "#ACD7E6" -interline-spacing "0" caption:"EL EQUIPO A " -trim -gravity south -extent "1900x500" ) -gravity south -geometry +0"+400" -quality 92% -composite "C:\PosterTemp\temp\testimage_text.png"`

### Images

![testimage](https://github.com/user-attachments/assets/03d1a1ec-cf87-4c77-9b02-b2f282a955f5)

**Comment by snibgo** [comment]
You can debug complex commands like this by inserting options like "+write x0.png", "+write x1.png" at appropriate places. Then look at each debugging image to isolate where the problem occurs.

By doing this, we find the problem is that `caption:` is sensitive to `-gravity`, which is set to `center`. A fix is to insert `+gravity` immediately before `caption:`.

I also suggest inserting `+repage` immediately after the `-trim`.

**Comment by fscorrupt** [comment]
> You can debug complex commands like this by inserting options like "+write x0.png", "+write x1.png" at appropriate places. Then look at each debugging image to isolate where the problem occurs.
> 
> By doing this, we find the problem is that `caption:` is sensitive to `-gravity`, which is set to `center`. A fix is to insert `+gravity` immediately before `caption:`.
> 
> I also suggest inserting `+repage` immediately after the `-trim`.

Thank you for the tip, I didn't know that one yet. Also, thanks for the information on what I should add. It works perfectly when I make the changes as you suggested. Many thanks!
