### ISSUE TITLE
The undo function does not work for images with a high resolution.

### ISSUE THREAD

**Issue by Deltom** [ImageMagick/ImageMagick#7704]
### ImageMagick version

7.1.1-38

### Operating system

Linux

### Operating system, version and so on

ALT Linux

### Description

To reproduce, an image with a resolution of at least 4608x3072, in any format, is required.

### Steps to Reproduce

Steps to reproduce:

1.Open the image:
      $ display <Image>
2.Modify it: For example, Right-click -> Transform -> Rotate Right
3.Undo the changes: Right-click -> Edit -> Undo or Ctrl + Z

Expected result: The changes are undone.
Actual result: Nothing happens. The changes are not undone.

### Images

![Uploading kote.jpg…]()

**Comment by urban-warrior** [comment]
Set the undoCache resource value to 4096.  That will resolve the issue.  In the mean-time, we added a patch to the main branch to increase the undo cache resource limit.
