### ISSUE TITLE
A command example in the docs doesn't work as intended

### ISSUE THREAD

**Issue by lkintact** [ImageMagick/ImageMagick#7708]
### ImageMagick version

7.1.1-39 Q16-HDRI x64 18ae555:20241005

### Operating system

Windows

### Operating system, version and so on

10 Home

### Description

There's a command example at https://www.imagemagick.org/Usage/masking/, `magick moon.png  -alpha off  -alpha on    alpha_on.png`, and in its description it's said: "For example, here we turn 'Off' the transparency data, then immediately turn it back 'On, reproducing the original image". That doesn't seem to happen, however:
1. Download the original image:
![moon.png](https://www.imagemagick.org/Usage/images/moon.png)

3. Execute `magick moon.png  -alpha off  -alpha on    alpha_on.png`; notice that the resulting image,  `alpha_on.png`, differs from the original:
![alpha_on.png](https://github.com/user-attachments/assets/c6751054-8eda-4ec6-a18b-e1c1a8360677)

### Steps to Reproduce

.

### Images

.

**Comment by dlemstra** [comment]
In IM7 the command should be `-alpha deactivate -alpha activate` instead to preserve the values in the alpha channel.

**Comment by lkintact** [comment]
Thank you, turns out `Alpha Activate/Deactivate` is described a bit below the command example. Sorry, I should have read the docs a bit more before reporting an issue.
