### ISSUE TITLE
One more command example in the docs doesn't work as intended

### ISSUE THREAD

**Issue by lkintact** [ImageMagick/ImageMagick#7709]
### ImageMagick version

7.1.1-39 Q16-HDRI x64 18ae555:20241005

### Operating system

Windows

### Operating system, version and so on

10 Home

### Description

There's another command example at https://www.imagemagick.org/Usage/masking/ that doesn't work as intended: `magick alpha_extract.png  -alpha copy   alpha_copy.png`.

1. Download the original image, `alpha_extract.png`:
![alpha_extract.png](https://www.imagemagick.org/Usage/masking/alpha_extract.png)
2. Execute `magick alpha_extract.png  -alpha copy   alpha_copy.png`; notice that the resulting image, `alpha_copy.png`, differs from what is shown in the docs:
This is the result from the docs:
![alpha_copy.png](https://github.com/user-attachments/assets/eea6055c-ca13-4fc8-8925-b46bd6b30f35)
This is what I get:
![alpha_copy_my.png](https://github.com/user-attachments/assets/180ccae0-6035-4e8b-bd01-d4c7fbfb87ea)

### Steps to Reproduce

.

### Images

.

**Comment by lkintact** [comment]
> For me as i installed ImageMagick 6

But why install ImageMagick 6 when version 7.1.1-39 is available?

**Comment by fmw42** [comment]
IM 7.1.1.39 is producing the wrong output.  Consider:

![moon](https://github.com/user-attachments/assets/2e13e320-5827-46c2-b214-0311c2f2cc87)

`magick moon.png -alpha extract alpha_extract.png`

![alpha_extract](https://github.com/user-attachments/assets/7450f11a-5c83-4bb0-b2d1-aeea228f8cae)

`magick alpha_extract.png  -alpha copy   alpha_copy.png`

![alpha_copy](https://github.com/user-attachments/assets/9568e7a9-a05b-4ce4-b6e7-91c2279fb5c2)

There should be transparency, but it is not here.

If I use 6.9.13-17

`convert alpha_extract.png  -alpha copy   alpha_copy-2.png`

![alpha_copy-2](https://github.com/user-attachments/assets/a5e2e338-5a0b-428f-b97d-00df98bf85a6)

Which has transparency, though one cannot see it well on a white background. But it is obvious when downloaded and viewed.

This is the same image that is displayed on the https://usage.imagemagick.org/masking/#alpha page. 

So IM 6 is correct and IM 7 is not and is missing the transparency from the -alpha copy.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
