### ISSUE TITLE
Default font regression

### ISSUE THREAD

**Issue by bastien-roucaries** [ImageMagick/ImageMagick#7728]
### ImageMagick version

7

### Operating system

Linux

### Operating system, version and so on

debian

### Description

Last im version return nothing with test program

### Steps to Reproduce

 ```
 #!/usr/bin/perl

  use Image::Magick;
  my $i = Image::Magick->new;
  $i->Read('null:#ffffff');

  use Data::Dumper;
  my @a = $i->QueryFontMetrics(font => '');

  print Dumper \@a;

```
This gives a list of thirteen integers on trixie, but
just one undef on sid.

### Images

None

**Comment by dlemstra** [comment]
Is it possible to create a docker file that I can use reproduce this?

**Comment by bastien-roucaries** [comment]
```
docker run -it debian:unstable-slim /usr/bin/bash
```
then
```
apt update
apt dist-upgrade
apt install libimage-magick-perl
```
then you could test

**Comment by urban-warrior** [comment]
This issue is likely related to the ImageMagick default font.  There is no universal cross-platform font so ImageMagick tries various methods to identify a default font, using Fontconfig for example.  Is Fontconfig enabled under SID?  If it is, ImageMagick should work. 

Can you post the output of this command: `magick -list font`?  What about `MAGICK_DEBUG=annotate perl t.pl`?

See https://imagemagick.org/script/security-policy.php.  You can set a default font policy.  Specify a path to a font that ImageMagick defaults to whenever the user does not specify a font preference:

```
<policy domain="system" name="font" value="/usr/share/fonts/google-noto/NotoSans-Black.ttf"/>
```

Now try your Perl script once more.  Did that resolve the issue?  If so, add that path to your package release.  If not, we'll try the Docker route and try to reproduce the issue.

**Comment by bastien-roucaries** [comment]
magick -list font

Path: System Fonts
  Font: C059-BdIta
    family: C059
    style: Italic
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/opentype/urw-base35/C059-BdIta.otf
    index: 0
  Font: C059-Bold
    family: C059
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/type1/urw-base35/C059-Bold.t1
    index: 0
  Font: C059-Bold-Italic
    family: C059
    style: Italic
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/type1/urw-base35/C059-BdIta.t1
    index: 0
  Font: C059-Italic
    family: C059
    style: Italic
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/C059-Italic.otf
    index: 0
  Font: C059-Roman
    family: C059
    style: Normal
    stretch: Normal
    weight: 500
    glyphs: /usr/share/fonts/X11/Type1/C059-Roman.pfb
    index: 0
  Font: D050000L
    family: D050000L
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/D050000L.otf
    index: 0
  Font: D050000L-Regular
    family: D050000L
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/X11/Type1/D050000L.pfb
    index: 0
  Font: DejaVu-Sans
    family: DejaVu Sans
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
    index: 0
  Font: DejaVu-Sans-Bold
    family: DejaVu Sans
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
    index: 0
  Font: DejaVu-Sans-Mono
    family: DejaVu Sans Mono
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf
    index: 0
  Font: DejaVu-Sans-Mono-Bold
    family: DejaVu Sans Mono
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf
    index: 0
  Font: DejaVu-Sans-Mono-Bold-Oblique
    family: DejaVu Sans Mono
    style: Oblique
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-BoldOblique.ttf
    index: 0
  Font: DejaVu-Sans-Mono-Oblique
    family: DejaVu Sans Mono
    style: Oblique
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Oblique.ttf
    index: 0
  Font: DejaVu-Serif
    family: DejaVu Serif
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf
    index: 0
  Font: DejaVu-Serif-Bold
    family: DejaVu Serif
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf
    index: 0
  Font: Droid-Sans-Fallback
    family: Droid Sans Fallback
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf
    index: 0
  Font: Nimbus-Mono-PS-Bold
    family: Nimbus Mono PS
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/type1/urw-base35/NimbusMonoPS-Bold.t1
    index: 0
  Font: Nimbus-Mono-PS-Bold-Italic
    family: Nimbus Mono PS
    style: Italic
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/X11/Type1/NimbusMonoPS-BoldItalic.pfb
    index: 0
  Font: Nimbus-Mono-PS-Italic
    family: Nimbus Mono PS
    style: Italic
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/X11/Type1/NimbusMonoPS-Italic.pfb
    index: 0
  Font: Nimbus-Mono-PS-Regular
    family: Nimbus Mono PS
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/X11/Type1/NimbusMonoPS-Regular.pfb
    index: 0
  Font: Nimbus-Roman-Bold
    family: Nimbus Roman
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/type1/urw-base35/NimbusRoman-Bold.t1
    index: 0
  Font: Nimbus-Roman-Bold-Italic
    family: Nimbus Roman
    style: Italic
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/X11/Type1/NimbusRoman-BoldItalic.pfb
    index: 0
  Font: Nimbus-Roman-Italic
    family: Nimbus Roman
    style: Italic
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/X11/Type1/NimbusRoman-Italic.pfb
    index: 0
  Font: Nimbus-Roman-Regular
    family: Nimbus Roman
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/X11/Type1/NimbusRoman-Regular.pfb
    index: 0
  Font: Nimbus-Sans-Bold
    family: Nimbus Sans
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/type1/urw-base35/NimbusSans-Bold.t1
    index: 0
  Font: Nimbus-Sans-Bold-Italic
    family: Nimbus Sans
    style: Italic
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/type1/urw-base35/NimbusSans-BoldItalic.t1
    index: 0
  Font: Nimbus-Sans-Italic
    family: Nimbus Sans
    style: Italic
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/X11/Type1/NimbusSans-Italic.pfb
    index: 0
  Font: Nimbus-Sans-Narrow-Bold
    family: Nimbus Sans Narrow
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/X11/Type1/NimbusSansNarrow-Bold.pfb
    index: 0
  Font: Nimbus-Sans-Narrow-Bold-Oblique
    family: Nimbus Sans Narrow
    style: Oblique
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/X11/Type1/NimbusSansNarrow-BoldOblique.pfb
    index: 0
  Font: Nimbus-Sans-Narrow-Oblique
    family: Nimbus Sans Narrow
    style: Oblique
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/type1/urw-base35/NimbusSansNarrow-Oblique.t1
    index: 0
  Font: Nimbus-Sans-Narrow-Regular
    family: Nimbus Sans Narrow
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/X11/Type1/NimbusSansNarrow-Regular.pfb
    index: 0
  Font: Nimbus-Sans-Regular
    family: Nimbus Sans
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/X11/Type1/NimbusSans-Regular.pfb
    index: 0
  Font: NimbusMonoPS-Bold
    family: Nimbus Mono PS
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusMonoPS-Bold.otf
    index: 0
  Font: NimbusMonoPS-BoldItalic
    family: Nimbus Mono PS
    style: Italic
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusMonoPS-BoldItalic.otf
    index: 0
  Font: NimbusMonoPS-Italic
    family: Nimbus Mono PS
    style: Italic
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusMonoPS-Italic.otf
    index: 0
  Font: NimbusMonoPS-Regular
    family: Nimbus Mono PS
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusMonoPS-Regular.otf
    index: 0
  Font: NimbusRoman-Bold
    family: Nimbus Roman
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusRoman-Bold.otf
    index: 0
  Font: NimbusRoman-BoldItalic
    family: Nimbus Roman
    style: Italic
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusRoman-BoldItalic.otf
    index: 0
  Font: NimbusRoman-Italic
    family: Nimbus Roman
    style: Italic
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusRoman-Italic.otf
    index: 0
  Font: NimbusRoman-Regular
    family: Nimbus Roman
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusRoman-Regular.otf
    index: 0
  Font: NimbusSans-Bold
    family: Nimbus Sans
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusSans-Bold.otf
    index: 0
  Font: NimbusSans-BoldItalic
    family: Nimbus Sans
    style: Italic
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusSans-BoldItalic.otf
    index: 0
  Font: NimbusSans-Italic
    family: Nimbus Sans
    style: Italic
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusSans-Italic.otf
    index: 0
  Font: NimbusSans-Regular
    family: Nimbus Sans
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusSans-Regular.otf
    index: 0
  Font: NimbusSansNarrow-Bold
    family: Nimbus Sans Narrow
    style: Normal
    stretch: SemiCondensed
    weight: 700
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusSansNarrow-Bold.otf
    index: 0
  Font: NimbusSansNarrow-BoldOblique
    family: Nimbus Sans Narrow
    style: Oblique
    stretch: SemiCondensed
    weight: 700
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusSansNarrow-BoldOblique.otf
    index: 0
  Font: NimbusSansNarrow-Oblique
    family: Nimbus Sans Narrow
    style: Oblique
    stretch: SemiCondensed
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusSansNarrow-Oblique.otf
    index: 0
  Font: NimbusSansNarrow-Regular
    family: Nimbus Sans Narrow
    style: Normal
    stretch: SemiCondensed
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/NimbusSansNarrow-Regular.otf
    index: 0
  Font: Noto-Mono
    family: Noto Mono
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/truetype/noto/NotoMono-Regular.ttf
    index: 0
  Font: Noto-Sans-Mono-Bold
    family: Noto Sans Mono
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/truetype/noto/NotoSansMono-Bold.ttf
    index: 0
  Font: Noto-Sans-Mono-Regular
    family: Noto Sans Mono
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/truetype/noto/NotoSansMono-Regular.ttf
    index: 0
  Font: P052-Bold
    family: P052
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/opentype/urw-base35/P052-Bold.otf
    index: 0
  Font: P052-Bold-Italic
    family: P052
    style: Italic
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/X11/Type1/P052-BoldItalic.pfb
    index: 0
  Font: P052-BoldItalic
    family: P052
    style: Italic
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/opentype/urw-base35/P052-BoldItalic.otf
    index: 0
  Font: P052-Italic
    family: P052
    style: Italic
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/P052-Italic.otf
    index: 0
  Font: P052-Roman
    family: P052
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/P052-Roman.otf
    index: 0
  Font: Standard-Symbols-PS
    family: Standard Symbols PS
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/StandardSymbolsPS.otf
    index: 0
  Font: Standard-Symbols-PS-Regular
    family: Standard Symbols PS
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/type1/urw-base35/StandardSymbolsPS.t1
    index: 0
  Font: Tuffy-Bold
    family: Tuffy
    style: Normal
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/truetype/tuffy/tuffy_bold.ttf
    index: 0
  Font: Tuffy-Bold-Italic
    family: Tuffy
    style: Italic
    stretch: Normal
    weight: 700
    glyphs: /usr/share/fonts/truetype/tuffy/tuffy_bold_italic.ttf
    index: 0
  Font: Tuffy-Italic
    family: Tuffy
    style: Italic
    stretch: Normal
    weight: 500
    glyphs: /usr/share/fonts/truetype/tuffy/tuffy_italic.ttf
    index: 0
  Font: Tuffy-Regular
    family: Tuffy
    style: Normal
    stretch: Normal
    weight: 500
    glyphs: /usr/share/fonts/truetype/tuffy/tuffy_regular.ttf
    index: 0
  Font: URW-Bookman-Demi
    family: URW Bookman
    style: Normal
    stretch: Normal
    weight: 600
    glyphs: /usr/share/fonts/X11/Type1/URWBookman-Demi.pfb
    index: 0
  Font: URW-Bookman-Demi-Italic
    family: URW Bookman
    style: Italic
    stretch: Normal
    weight: 600
    glyphs: /usr/share/fonts/type1/urw-base35/URWBookman-DemiItalic.t1
    index: 0
  Font: URW-Bookman-Light
    family: URW Bookman
    style: Normal
    stretch: Normal
    weight: 300
    glyphs: /usr/share/fonts/type1/urw-base35/URWBookman-Light.t1
    index: 0
  Font: URW-Bookman-Light-Italic
    family: URW Bookman
    style: Italic
    stretch: Normal
    weight: 300
    glyphs: /usr/share/fonts/X11/Type1/URWBookman-LightItalic.pfb
    index: 0
  Font: URW-Gothic-Book
    family: URW Gothic
    style: Normal
    stretch: Normal
    weight: 300
    glyphs: /usr/share/fonts/X11/Type1/URWGothic-Book.pfb
    index: 0
  Font: URW-Gothic-Book-Oblique
    family: URW Gothic
    style: Oblique
    stretch: Normal
    weight: 300
    glyphs: /usr/share/fonts/type1/urw-base35/URWGothic-BookOblique.t1
    index: 0
  Font: URW-Gothic-Demi
    family: URW Gothic
    style: Normal
    stretch: Normal
    weight: 600
    glyphs: /usr/share/fonts/type1/urw-base35/URWGothic-Demi.t1
    index: 0
  Font: URW-Gothic-Demi-Oblique
    family: URW Gothic
    style: Oblique
    stretch: Normal
    weight: 600
    glyphs: /usr/share/fonts/type1/urw-base35/URWGothic-DemiOblique.t1
    index: 0
  Font: URWBookman-Demi
    family: URW Bookman
    style: Normal
    stretch: Normal
    weight: 600
    glyphs: /usr/share/fonts/opentype/urw-base35/URWBookman-Demi.otf
    index: 0
  Font: URWBookman-DemiItalic
    family: URW Bookman
    style: Italic
    stretch: Normal
    weight: 600
    glyphs: /usr/share/fonts/opentype/urw-base35/URWBookman-DemiItalic.otf
    index: 0
  Font: URWBookman-Light
    family: URW Bookman
    style: Normal
    stretch: Normal
    weight: 300
    glyphs: /usr/share/fonts/opentype/urw-base35/URWBookman-Light.otf
    index: 0
  Font: URWBookman-LightItalic
    family: URW Bookman
    style: Italic
    stretch: Normal
    weight: 300
    glyphs: /usr/share/fonts/opentype/urw-base35/URWBookman-LightItalic.otf
    index: 0
  Font: URWGothic-Book
    family: URW Gothic
    style: Normal
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/URWGothic-Book.otf
    index: 0
  Font: URWGothic-BookOblique
    family: URW Gothic
    style: Oblique
    stretch: Normal
    weight: 400
    glyphs: /usr/share/fonts/opentype/urw-base35/URWGothic-BookOblique.otf
    index: 0
  Font: URWGothic-Demi
    family: URW Gothic
    style: Normal
    stretch: Normal
    weight: 600
    glyphs: /usr/share/fonts/opentype/urw-base35/URWGothic-Demi.otf
    index: 0
  Font: URWGothic-DemiOblique
    family: URW Gothic
    style: Oblique
    stretch: Normal
    weight: 600
    glyphs: /usr/share/fonts/opentype/urw-base35/URWGothic-DemiOblique.otf
    index: 0
  Font: Z003-Medium-Italic
    family: Z003
    style: Italic
    stretch: Normal
    weight: 500
    glyphs: /usr/share/fonts/type1/urw-base35/Z003-MediumItalic.t1
    index: 0
  Font: Z003-MediumItalic
    family: Z003
    style: Italic
    stretch: Normal
    weight: 500
    glyphs: /usr/share/fonts/opentype/urw-base35/Z003-MediumItalic.otf

**Comment by bastien-roucaries** [comment]
@urban-warrior 

With your patch it still fail I suppose it is incomplete
see https://salsa.debian.org/debian/imagemagick/-/jobs/6528173
autopkgtest [10:31:07]: test perlmagick-fonts-7.q16: [-----------------------
$VAR1 = [
          undef
        ];

**Comment by urban-warrior** [comment]
Yikes! Our original patch was a no-op.  Instead, we ported the search for default font from IMv6 which presumably works on SID.

**Comment by bastien-roucaries** [comment]
Still not good see https://salsa.debian.org/debian/imagemagick/-/jobs/6528457/raw

**Comment by urban-warrior** [comment]
Setting up Docker is going to take some time in my environment so let's try one last test before we go Docker-diving.  The script is acting like it can't find any fonts.  Let's see if the PerlMagick environment has access to any fonts.  Append these lines to your PerlMagick script:

```
my @a = $i->QueryFont(); 
print Dumper \@a;
```

Send use the link to the output so we can review to help us debug.

Thanks,

**Comment by bastien-roucaries** [comment]
here https://salsa.debian.org/debian/imagemagick/-/jobs/6529095

**Comment by bastien-roucaries** [comment]
$VAR1 = [
          'C059-BdIta',
          'C059-Bold',
          'C059-Bold-Italic',
          'C059-Italic',
          'C059-Roman',
          'D050000L',
          'D050000L-Regular',
          'DejaVu-Sans',
          'DejaVu-Sans-Bold',
          'DejaVu-Sans-Mono',
          'DejaVu-Sans-Mono-Bold',
          'DejaVu-Sans-Mono-Bold-Oblique',
          'DejaVu-Sans-Mono-Oblique',
          'DejaVu-Serif',
          'DejaVu-Serif-Bold',
          'Nimbus-Mono-PS-Bold',
          'Nimbus-Mono-PS-Bold-Italic',
          'Nimbus-Mono-PS-Italic',
          'Nimbus-Mono-PS-Regular',
          'Nimbus-Roman-Bold',
          'Nimbus-Roman-Bold-Italic',
          'Nimbus-Roman-Italic',
          'Nimbus-Roman-Regular',
          'Nimbus-Sans-Bold',
          'Nimbus-Sans-Bold-Italic',
          'Nimbus-Sans-Italic',
          'Nimbus-Sans-Narrow-Bold',
          'Nimbus-Sans-Narrow-Bold-Oblique',
          'Nimbus-Sans-Narrow-Oblique',
          'Nimbus-Sans-Narrow-Regular',
          'Nimbus-Sans-Regular',
          'NimbusMonoPS-Bold',
          'NimbusMonoPS-BoldItalic',
          'NimbusMonoPS-Italic',
          'NimbusMonoPS-Regular',
          'NimbusRoman-Bold',
          'NimbusRoman-BoldItalic',
          'NimbusRoman-Italic',
          'NimbusRoman-Regular',
          'NimbusSans-Bold',
          'NimbusSans-BoldItalic',
          'NimbusSans-Italic',
          'NimbusSans-Regular',
          'NimbusSansNarrow-Bold',
          'NimbusSansNarrow-BoldOblique',
          'NimbusSansNarrow-Oblique',
          'NimbusSansNarrow-Regular',
          'P052-Bold',
          'P052-Bold-Italic',
          'P052-BoldItalic',
          'P052-Italic',
          'P052-Roman',
          'Standard-Symbols-PS',
          'Standard-Symbols-PS-Regular',
          'URW-Bookman-Demi',
          'URW-Bookman-Demi-Italic',
          'URW-Bookman-Light',
          'URW-Bookman-Light-Italic',
          'URW-Gothic-Book',
          'URW-Gothic-Book-Oblique',
          'URW-Gothic-Demi',
          'URW-Gothic-Demi-Oblique',
          'URWBookman-Demi',
          'URWBookman-DemiItalic',
          'URWBookman-Light',
          'URWBookman-LightItalic',
          'URWGothic-Book',
          'URWGothic-BookOblique',
          'URWGothic-Demi',
          'URWGothic-DemiOblique',
          'Z003-Medium-Italic',
          'Z003-MediumItalic'
        ];

**Comment by urban-warrior** [comment]
Curious, there are fonts and the script still fails.  It works on all my other test hosts.  We'll need to dust off my Docker environment to attempt to reproduce the issue.  This may a few week as we're currently overbooked.

**Comment by urban-warrior** [comment]
The issue is the URW fonts are now T1/AFM rather than OTF.  Give us a few days to export a patch.

**Comment by bastien-roucaries** [comment]
Le dimanche 3 novembre 2024, 23:31:35 UTC Cristy a écrit :
> 
> The issue is the URW fonts are now T1/AFM rather than OTF.  Give us a few days to export a patch.
Can using dejavu be a solution ?

Bastien
> 
> 
> 
>

**Comment by bastien-roucaries** [comment]
Le dimanche 3 novembre 2024, 23:32:50 UTC Bastien Roucariès a écrit :
> Le dimanche 3 novembre 2024, 23:31:35 UTC Cristy a écrit :
> > 
> > The issue is the URW fonts are now T1/AFM rather than OTF.  Give us a few days to export a patch.
> Can using dejavu be a solution ?

I can also install  fonts-texgyre that is urw compatible by OTF

Bastien
> 
> Bastien
> > 
> > 
> > 
> > 
> 
>

**Comment by bastien-roucaries** [comment]
https://packages.debian.org/sid/all/fonts-urw-base35/filelist list otf file @urban-warrior  are you sure ?

**Comment by bastien-roucaries** [comment]
May be the news file is relevant
https://sources.debian.org/src/fonts-urw-base35/20200910-8/debian/NEWS/

**Comment by urban-warrior** [comment]
Thanks for all the tips.  We will incorporate it into our patch... which might take a few days due to other priorities.  In the mean-time, you can remove `'--with-urw-base35-font-dir=/usr/share/fonts/type1/urw-base35'` from your configure script command-line (until we push a patch) and the PerlMagick script will work.

**Comment by urban-warrior** [comment]
Download the latest ImageMagick main branch and add this configure command line option `--with-urw-base35-type1-font-dir=/usr/share/fonts/type1/urw-base35`.  The script now returns the 13 font metrics from the Perl scripts, as expected.
