### ISSUE TITLE
Invalid width (4096) too large

### ISSUE THREAD

**Issue by canonex** [ImageMagick/ImageMagick#7747]
### Is your feature request related to a problem? Please describe.

Montage issues errors when dealing with 4K images, particularly with 4 images 4096 × 2048 px.

With openexr
`magick montage A/0250_A.exr B/0250_B.exr C/0250_C.exr D/0250_D.exr -mode Concatenate -tile 2x2 file-montage.exr`
`...
montage: CorruptImage `Invalid width (4096) too large (max 4000)' @ error/exr.c/EXRError/176.`

with jpg, even with resize option:
`magick montage A/0250_A.jpg B/0250_B.jpg C/0250_C.jpg D/0250_D.jpg -mode Concatenate -tile 2x2 -resize 50% file-montage.jpg`
`...
montage: width or height exceeds limit `A/0250_A.jpg' @ error/cache.c/OpenPixelCache/3695`

### Describe the solution you'd like

Support for hi resolution images.
The use case is the creation of a video for projection mapping with four 4K/4KUHD projectors (4096 x 2160/ 3860 x 2400): the total resolution of a single frame should be 8K, like 8192 x 4800px.
Although this is an extreme case, there is starting to be quite a lot of equipment, even non-specialized 8K equipment, and in the future it will certainly be more widespread.
Ex. DaVinci support 8k (Blender even more so).  Imagemagick is a good companion for large productions!

### Describe alternatives you've considered

...not using montage for this assembly work :(
Maybe python, maybe the Blender compositor.

### Additional context

Please ask if you need further information. Thank you!

**Comment by snibgo** [comment]
> CorruptImage Invalid width (4096) too large (max 4000)' @ error/exr.c/EXRError/176.

This is reporting that one of your input EXR files is corrupt. To find which has the problem, try:
```
magick A/0250_A.exr info:
```
... etc, for each input file.

For your second error, please give us enough for use to try to reproduce the problem, eg supply A/0250_A.jpg etc.

Where p.png is 5000x3000 pixels, this works fine for me:
```
magick montage p.png p.png p.png p.png -mode Concatenate -tile 2x2 -resize 50% x.png
```

**Comment by canonex** [comment]
Thank you, here more context and info and files attached.

### System
Debian GNU/Linux 12 (bookworm)
```
$ magick -version
Version: ImageMagick 7.1.1-39 Q16-HDRI x86_64 22428 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): fontconfig freetype heic jbig jng jp2 jpeg ltdl lzma openexr png tiff webp x zlib zstd
Compiler: gcc (12.2)
```


### File info
About the exr info:
```
$ magick A/0250_A.exr info
magick: CorruptImage `Invalid width (4096) too large (max 4000)' @ error/exr.c/EXRError/176.
magick: unable to open image `A/0250_A.exr' @ error/exr.c/ReadEXRImage/270.
```

```
$ exrinfo A/0250_A.exr
File 'A/0250_A.exr':
  compression: 'dwaa'
 displayWindow: [ 0, 0 - 4095 2159 ] 4096 x 2160
  dataWindow: [ 0, 0 - 4095 2159 ] 4096 x 2160
  channels: 4 channels
   'A': float samp 1 1
   'B': float samp 1 1
   'G': float samp 1 1
   'R': float samp 1 1
```

Similar with jpg:
```
$ magick tmp/0001_A.jpg info
magick: width or height exceeds limit `tmp/0001_A.jpg' @ error/cache.c/OpenPixelCache/3695
```

Attached the 4K files, exr and jpg. Those are render by Blender: [0001.zip](https://github.com/user-attachments/files/17622098/0001.zip)


### More
...investigating a little more .
If I create a new jpg render 2048 × 1080 pixel, I receive:
```
$ magick montage tmp/0001_A.jpg tmp/0001_B.jpg tmp/0001_C.jpg tmp/0001_D.jpg -mode Concatenate -tile 2x2 tmp/0001.jpg
montage: width or height exceeds limit `tmp/0001.jpg' @ error/cache.c/OpenPixelCache/3695.
montage: Application transferred too few scanlines `tmp/0001.jpg' @ error/jpeg.c/JPEGErrorHandler/356.
```
If I resize the jpg 1024 × 540 pixel, the command work smoothly.


Thank you,
Riccardo

**Comment by snibgo** [comment]
`info:` should have a colon suffix, but I doubt that this fixes your problem.

I get:
```
magick 0001_A.exr info:
0001_A.exr EXR 4096x2160 4096x2160+0+0 16-bit RGB 41502B 0.000u 0:00.000
```
So it works for me, but not for you.

What OpenEXR do you have?
```
magick -list format |grep -i exr
      EXR  rw-   High Dynamic-range (HDR) (OpenEXR 3.2.1)
```

**Comment by canonex** [comment]
I have tried the command both with the colon and without, and the result, unfortunately, does not change :)

I seem to have an older version....
```
$ magick -list format |grep -i exr
      EXR  EXR       rw-   High Dynamic-range (HDR) (OpenEXR 3.1.5)
```
Is this the problem? This I think is the Debian stable default.

Thank you,
Riccardo

ps.  Nooo, don't I have to recompile everything? I'm not good at these things...

**Comment by snibgo** [comment]
> (OpenEXR 3.1.5)

I don't know if that is the EXR problem but, yes, I suggest you upgrade the library and rebuild IM.

I should mention that ...
```
magick montage 0001_A.jpg 0001_B.jpg 0001_C.jpg 0001_D.jpg -mode Concatenate -tile 2x2 x.png
```
... works fine for me. This doesn't involve exr, so is a different problem.

I use IM v7.1.1-38 on Windows 11:
```
Version: ImageMagick 7.1.1-38 Q16-HDRI x64 b0ab922:20240901 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Channel-masks(64-bit) Cipher DPC HDRI OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (194134120)
```

> montage: width or height exceeds limit `tmp/0001.jpg' @ error/cache.c/OpenPixelCache/3695

That seems to be in this code:
```
  if (((MagickSizeType) image->columns > cache_info->width_limit) ||
      ((MagickSizeType) image->rows > cache_info->height_limit))
    ThrowBinaryException(ImageError,"WidthOrHeightExceedsLimit",
      image->filename);
```
... but I don't know what can cause that problem.

**Comment by urban-warrior** [comment]
See if the problem is related to your security policy with this command: `magick -list policy`.

**Comment by canonex** [comment]
> See if the problem is related to your security policy with this command: `magick -list policy`.

### Jpeg [solved]
Ah, I did not know about this,, for jpeg it is solved, on policy.xml it was set to 4KP... Thank you!!!

> Set the maximum width of an image.  When this limit is exceeded, an exception is thrown.
> policy domain="resource" name="width" value="10KP"
Why this? This is not even 4k, `Invalid width (4096) too large (max 4000)'`. I have more than doubled all values.

**Summary: policy.xml sets maximum size for elaboration.**

### Exr
The size error, is gone but the montage is doing wrong, I think I'll open another thread.


Thank you!
