### ISSUE TITLE
Montage, mode Concatenate, tile, exr

### ISSUE THREAD

**Issue by canonex** [ImageMagick/ImageMagick#7751]
### ImageMagick version

7.1.1-40

### Operating system

Linux

### Operating system, version and so on

Debian 12, Bookworm

```
$ magick -list format |grep -i exr
      EXR  EXR       rw-   High Dynamic-range (HDR) (OpenEXR 3.4.0-dev)
```

```
$ magick --version
Version: ImageMagick 7.1.1-40 (Beta) Q16-HDRI x86_64 f56b10574:20241104 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): fontconfig freetype heic jbig jng jp2 jpeg ltdl lzma openexr png tiff webp x zlib zstd
Compiler: gcc (12.2)
```

### Description

Magic montage, with mode concatenate, produces a partially black file.

The command is:
`magick montage 0001_*.exr -mode Concatenate -tile 2x2 file-montage.exr`
The first tile, top-left is drawn, the others are black.

The same command, using jpg or png, works fine.
Even a mixed command like:
`magick montage 0001_*.jpg -mode Concatenate -tile 2x2 file-montage.exr`
works fine.

Thank you,
Riccardo

### Steps to Reproduce

Decompress the attached file and run the commands:
`
magick montage 0001_*.png -mode Concatenate -tile 2x2 file-montage.png`
Works fine

`magick montage 0001_*.jpg -mode Concatenate -tile 2x2 file-montage.jpg`
Works fine

`magick montage 0001_*.exr -mode Concatenate -tile 2x2 file-montage.exr`
Different wrong result, partial black.

### Images

[0001.zip](https://github.com/user-attachments/files/17637604/0001.zip)

The good result:
![file-montage](https://github.com/user-attachments/assets/ae4936b9-93e7-4524-b5d9-bc34e751b782)

The bad result:
[file-montage.zip](https://github.com/user-attachments/files/17637608/file-montage.zip)
that in jpg it looks like
![file-montage](https://github.com/user-attachments/assets/96063af9-a51c-4450-a2fa-92f8e1f73706)

**Comment by dlemstra** [comment]
You seem to be using version 3.4.0 of openexr that has not yet been released. What happens when you downgrade to the latest official release?

**Comment by canonex** [comment]
I confirm the problem in versions (always Debian 12 but default packages):

- Imagemagick 7.1.1-39
- OpenExr 3.1.5

Note that in this version, artifacts are present on the final exr image.
[file-montage.zip](https://github.com/user-attachments/files/17653541/file-montage.zip)

Thank you,
Riccardo

**Comment by snibgo** [comment]
> The first tile, top-left is drawn, the others are black.

Gimp can open and show 0001_A.exr. For the other three, it says:
```
Opening 'C:\web\im\0001\0001_C.exr' failed: Procedure 'file-exr-load' returned no return values
```

IM "-verbose info:" says the other three files are entirely black.

**Comment by canonex** [comment]
> > The first tile, top-left is drawn, the others are black.
> 
> Gimp can open and show 0001_A.exr. For the other three, it says:
> 
> ```
> Opening 'C:\web\im\0001\0001_C.exr' failed: Procedure 'file-exr-load' returned no return values
> ```
> 
> IM "-verbose info:" says the other three files are entirely black.

Yes, gimp/2.0/plug-ins/file-exr/file-exr Gimp plugins returns an error.

The files are definitely not black as they can be properly viewed with other software.
I was able to view them with:
- Tev: https://github.com/paulocr2/tev-The-EXR-Viewer?tab=readme-ov-file
- Mrv2: https://github.com/ggarra13/mrv2/ (this one is super cool)
- Krita: https://krita.org/it/
- Blender, the software : https://www.blender.org/
Here you can see a screenshot of the B image (the same applies to C and D):
![Schermata del 2024-11-07 09-42-47](https://github.com/user-attachments/assets/61628bfb-a6be-4361-8037-578279220d5e)

Here is the output of exrinfo of A:

```
$ exrinfo -a 0001_A.exr 
File '0001_A.exr': ver 2 flags longnames
 parts: 1
 part 1: <single>
  Camera: string 'Camera_D'
  Date: string '2024/11/05 18:56:02'
  File: string '/home/...Montage.blend'
  Frame: string '1'
  RenderTime: string '00:00.33'
  Scene: string 'Multiview'
  Time: string '00:00:00:01'
  channels: chlist 4 channels
   'A': float samp 1 1
   'B': float samp 1 1
   'G': float samp 1 1
   'R': float samp 1 1
  compression: compression 'none' (0x00)
  dataWindow: box2i [ 0, 0 - 255 127 ] 256 x 128
  displayWindow: box2i [ 0, 0 - 255 127 ] 256 x 128
  lineOrder: lineOrder 0 (increasing)
  multiView: stringvector [1 entries]:
    'A'
  pixelAspectRatio: float 1
  screenWindowCenter: v2f [ 0, 0 ]
  screenWindowWidth: float 1
```

and B image:
```
$ exrinfo -a c0001_B.exr 
File 'c0001_B.exr': ver 2 flags longnames
 parts: 1
 part 1: <single>
  Camera: string 'Camera_D'
  Date: string '2024/11/05 18:56:02'
  File: string '/home/...Montage.blend'
  Frame: string '1'
  RenderTime: string '00:00.33'
  Scene: string 'Multiview'
  Time: string '00:00:00:01'
  channels: chlist 4 channels
   'ViewLayer.Combined.A': float samp 1 1
   'ViewLayer.Combined.B': float samp 1 1
   'ViewLayer.Combined.G': float samp 1 1
   'ViewLayer.Combined.R': float samp 1 1
  compression: compression 'none' (0x00)
  dataWindow: box2i [ 0, 0 - 255 127 ] 256 x 128
  displayWindow: box2i [ 0, 0 - 255 127 ] 256 x 128
  lineOrder: lineOrder 0 (increasing)
  multiView: stringvector [1 entries]:
    'B'
  pixelAspectRatio: float 1
  screenWindowCenter: v2f [ 0, 0 ]
  screenWindowWidth: float 1
```

The differences are, apart from file name and multiView name, the channel names: are these channel types ( ViewLayer.Combined.A ... ) supported or are they expected to be called are RGBA?

I would add again that, using OpenImageIO, the oiiotool command, the result is as expected:
`oiiotool 0001_*.exr --mosaic 2x2 --compression dwaa -o file-montage.exr`


Thank you!
Riccardo

**Comment by fmw42** [comment]
Imagemagick is strict and follows the specs. If something is not according to the specs some software will read it, but Imagemagick may not.  A developer will need to check your images.

**Comment by dlemstra** [comment]
I just pushed a patch to ignore the layer and/or view of the channel name (`ViewLayer/Combined`) when all channels start with that name and I am now getting the following output image:
![output](https://github.com/user-attachments/assets/cdfe5bfc-8388-4f0b-8c13-6645a22449e1)

This change will become available in the next release.

**Comment by canonex** [comment]
@dlemstra ... wow: I could compile it and reproduce the same result!

@fmw42 I found this document about the naming of nested layers and channel name:
https://openexr.com/en/latest/TechnicalIntroduction.html#channel-names-label

Again, thank you!
Riccardo
