### ISSUE TITLE
NUL byte in PDF metadata

### ISSUE THREAD

**Issue by danielzgtg** [ImageMagick/ImageMagick#7756]
### ImageMagick version

7.1.1-39

### Operating system

Linux

### Operating system, version and so on

debian:unstable-20241016

### Description

There is an unexpected NUL byte in various fields of the PDF metadata. This happens whether from `xc:white` or PNG. PDFs from the internet don't have this. This breaks `grep` on `pdfinfo`.

This bug's severity varied across versions:
* `8:6.9.11.60+dfsg-1.6+deb12u2` Docker debian:stable-20241016: after each letter in the title
* `8:6.9.12.98+dfsg1-5.2build2` Ubuntu 24.04: after the title only
* `8:7.1.1.39+dfsg1-2`: after various fields

### Steps to Reproduce

```bash
$ convert -size 100x100 xc:white test.pdf
$ pdfinfo test.pdf | grep Title # Prints error not desired field
grep: (standard input): binary file matches
$ pdfinfo test.pdf | xxd # Notice the four 00s
00000000: 5469 746c 653a 2020 2020 2020 2020 2020  Title:
00000010: 2074 6573 7400 0a41 7574 686f 723a 2020   test..Author:
00000020: 2020 2020 2020 2020 6874 7470 733a 2f2f          https://
00000030: 696d 6167 656d 6167 6963 6b2e 6f72 6700  imagemagick.org.
00000040: 0a43 7265 6174 6f72 3a20 2020 2020 2020  .Creator:
00000050: 2020 6874 7470 733a 2f2f 696d 6167 656d    https://imagem
00000060: 6167 6963 6b2e 6f72 6700 0a50 726f 6475  agick.org..Produ
00000070: 6365 723a 2020 2020 2020 2020 6874 7470  cer:        http
00000080: 733a 2f2f 696d 6167 656d 6167 6963 6b2e  s://imagemagick.
00000090: 6f72 6700 0a43 7265 6174 696f 6e44 6174  org..CreationDat
...
```

### Images

The image is builtin `xc:white`

**Comment by dlemstra** [comment]
Thanks for reporting this. I just pushed a patch to make sure this is fixed in the next release.
