### ISSUE TITLE
IM7 creates artefacts in a simple .heic --> .png conversion

### ISSUE THREAD

**Issue by emk2203** [ImageMagick/ImageMagick#7760]
### ImageMagick version

7.1.1-39

### Operating system

Linux

### Operating system, version and so on

Arch Linux (EndeavourOS)

### Description

I want to convert .heic photos from a Samsung Galaxy S24+ into .png format. Command is just `magick file.heic file.png`.

Most, but not all, files end up with a green square in the corner or at the edge. Shades of green change as well.

### Steps to Reproduce

I have attached  two sample images before and after the conversion.

### Images

[pngs.zip](https://github.com/user-attachments/files/17681955/pngs.zip)
[heic.zip](https://github.com/user-attachments/files/17681963/heic.zip)

**Comment by dlemstra** [comment]
It seems that you have corrupt images. When I run this in with the latest libheif version I get the following error message:

```
magick: Decoder plugin generated an error: Unexpected end of file (7.100) `20241102_162401.heic' @ error/heic.c/IsHEIFSuccess/141.
I:\issues\im7\7760>magick 20241102_162444.heic z.png
magick: Decoder plugin generated an error: Unexpected end of file (7.100) `20241102_162444.heic' @ error/heic.c/IsHEIFSuccess/141.

**Comment by emk2203** [comment]
Thanks for the quick analysis. I downloaded them via  Google Photos from the phone, maybe they get corrupted in the cloud somehow. I try again with a direct download from the phone.

Strange that this unexpected EOF causes such an issue. The heic files display without problem or warning in `feh` and in KDE's Gwenview or in the thumbnails by `ffmpegthumbnailer`.

Shouldn't IM be more fault-tolerant as well?

**Comment by fmw42** [comment]
Imagemagick follows strictly to the specs.  Other tools may be more flexible with respect to errors.

**Comment by emk2203** [comment]
Direct download reveals that the photos are not changed in the cloud; sha256sums and sizes are identical. Conversion results are also similar, with artefacts.

I close this issue since the root cause seems to be the origin of the pictures with a non-standard heic generation, not IM.
