### ISSUE TITLE
Redundant declarations in MagickWand headers

### ISSUE THREAD

**Issue by msharov** [ImageMagick/ImageMagick#7762]
### ImageMagick version

7.1.1-39

### Operating system

Linux

### Operating system, version and so on

Arch

### Description

```
In file included from /usr/include/ImageMagick-7/MagickWand/deprecate.h:25,                                                                              
                 from /usr/include/ImageMagick-7/MagickWand/MagickWand.h:82,                                                                             
                 from tes.cc:3:                                                                                                                          
/usr/include/ImageMagick-7/MagickWand/pixel-wand.h:41:3: warning: redundant redeclaration of ‘double PixelGetAlpha(const PixelWand*)’ in same scope [-Wredundant-decls]                                                                                                                                           
   41 |   PixelGetAlpha(const PixelWand *) magick_attribute((__pure__)),                                                                                 
      |   ^~~~~~~~~~~~~                                                                                                                                  
/usr/include/ImageMagick-7/MagickWand/pixel-wand.h:34:3: note: previous declaration of ‘double PixelGetAlpha(const PixelWand*)’                          
   34 |   PixelGetAlpha(const PixelWand *) magick_attribute((__pure__)),                                                                                 
      |   ^~~~~~~~~~~~~
```
Same warning also reported for PixelGetAlphaQuantum, PixelSetAlpha, PixelSetAlphaQuantum, PixelSetPixelColor, and MagickGetImageRange (in magick-image.h).

### Steps to Reproduce

Compile MagickWand-using code with -Wredundant-decls .

### Images

Not image related.

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
