### ISSUE TITLE
Magick Mogrify conversion from heic to jpg fails in 7.1.1-40, but works in 7.1.1-39

### ISSUE THREAD

**Issue by ExpPhysU** [ImageMagick/ImageMagick#7778]
### ImageMagick version

7.1.1.-40

### Operating system

Windows

### Operating system, version and so on

11 23H2

### Description

Calling magick mogrify -format jpg -quality 97 -define heic:depth-image=true -define preserve-timestamp=true  *.HEIC heic fails with 7.1.1-40. Downgrade to 7.1.1-39 works

Error
mogrify: Decoder plugin generated an error: Unexpected end of file (7.100) `IMG_1936.HEIC' @ error/heic.c/IsHEIFSuccess/141.

The Bug is reproducible with 7.1.1-40 and is not present in 7.1.1-39

### Steps to Reproduce

[IMG_1936.zip](https://github.com/user-attachments/files/17774227/IMG_1936.zip)

The zip file contains the HEIC-File which works with 7.1.1-39 and fails wit 7.1.1-40
Just run the command 
magick mogrify -format jpg -quality 97 -define heic:depth-image=true -define preserve-timestamp=true  *.HEIC
on the file provided.

Program download imagemagick64-7.1.1.39-ImageMagick-7.1.1-39-Q16-HDRI-x64-dll.exe
and imagemagick64-7.1.1.39-ImageMagick-7.1.1-40-Q16-HDRI-x64-dll.exe

### Images

[IMG_1936.zip](https://github.com/user-attachments/files/17774237/IMG_1936.zip)
 Zip file, since HEIC files are not allowed

**Comment by dlemstra** [comment]
Thanks for reporting this. This was also reported in one of my other projects and I just pushed a patch to fix this. This will be resolved in the next release.
