### ISSUE TITLE
Linked images in SVGs are resolved against cwd instead of the file path

### ISSUE THREAD

**Issue by wasamasa** [ImageMagick/ImageMagick#779]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I've noticed that when using ImageMagick to process SVG files with linked images, they're only resolved correctly by `convert` if you're in the same directory as the SVG file. Running `convert` from another directory embeds a "Linked image not found" image where I'd expect the linked image to be.  The same issue extends to other programs using the Magickwand bindings, such as Emacs.  I've found a similar issue with librsvg usage in Emacs before, it wouldn't surprise me if Imagemagick needs to use the same workaround:

- https://debbugs.gnu.org/cgi/bugreport.cgi?bug=19373
- https://bugzilla.gnome.org/show_bug.cgi?id=596114

### Steps to Reproduce
- Download [a SVG file](http://dev.w3.org/SVG/profiles/1.1F2/test/svg/struct-image-02-b.svg) referencing [a local image](http://dev.w3.org/SVG/profiles/1.1F2/test/images/struct-image-02.jpg)
- `cd` into a different directory than the SVG file is contained in
- `convert path/to/in.svg out.png`
- View `out.png` to confirm that it failed embedding the local image
- `cd` into the directory the SVG file is contained in
- `convert in.svg out.png`
- View `out.png` to confirm that it embedded the local image correctly

### System Configuration

- ImageMagick version: "Version: ImageMagick 6.9.9-15 Q16 x86_64 2017-09-23 http://www.imagemagick.org"
- Environment (Operating system, version and so on): Arch Linux
- Additional information: Emacs 25.3.1

**Comment by dlemstra** [comment]
Which SVG library is being used? You can see that in the output from `convert -list format`

**Comment by wasamasa** [comment]
According to `convert -list format` it's librsvg, however I've discovered that the issue disappears once I uninstall Inkscape from my system.  That again renders Emacs unable to render SVGs with ImageMagick at all.
