### ISSUE TITLE
`.avci` does not work despite libheif including support

### ISSUE THREAD

**Issue by festive-onion** [ImageMagick/ImageMagick#7792]
### ImageMagick version

7.1.1-39

### Operating system

MacOS

### Operating system, version and so on

Sonoma 14.5

### Description

I would expect that `.avci` files would be supported given that libheif can be built with openh264 support, but attempting to interact with the file gives the following error:
`identify: no decode delegate for this image format `AVCI' @ error/constitute.c/ReadImage/746.`

### Steps to Reproduce

- Build ImageMagick with libheif+openh264
- Run `identify` or other command on the file

### Images

Any `.avci` file, example attached:
[825f483bf0244ea8016177251416d27730c119f1.avci.zip](https://github.com/user-attachments/files/17837751/825f483bf0244ea8016177251416d27730c119f1.avci.zip)

**Comment by dlemstra** [comment]
Please attach an image that someone could use to reproduce this. Don't make us search a file online.

**Comment by festive-onion** [comment]
Sorry for the delay, just added!

**Comment by dlemstra** [comment]
No worries it also took me a while before I could take a look at this. I just pushed a patch that adds support for reading this file and this will become available in the next release.

**Comment by festive-onion** [comment]
Awesome, thank you!!
