### ISSUE TITLE
out-of-bounds read in MagickCore/pixel-accessor.h:778 SetPixelViaPixelInfo

### ISSUE THREAD

**Issue by moshekaplan** [ImageMagick/ImageMagick#78]
https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1533451

**Comment by dlemstra** [comment]
Can you get the latest version from GIT and let us know if the problem is resolved?

**Comment by moshekaplan** [comment]
This bug appears to have been fixed. Thanks for being so responsive.

**Comment by attritionorg** [comment]
Can you link to the commit please?

**Comment by dlemstra** [comment]
If you want to create a patch for this you should use the commits from 15/16 jan to psd.c

**Comment by dlemstra** [comment]
You should use the following patch: https://github.com/ImageMagick/ImageMagick/commit/280215b9936d145dd5ee91403738ccce1333cab1.
