### ISSUE TITLE
Crashes with glib 2.83

### ISSUE THREAD

**Issue by rgpublic** [ImageMagick/ImageMagick#7801]
### ImageMagick version

7.1.1-41

### Operating system

Linux

### Operating system, version and so on

Linux / Ubuntu Noble

### Description

If I try to build ImageMagick (statically, but I don't think that's the main reason) with the recently released 2.83.0 it just crashes with a segmentation fault. It's not even necessary to convert images etc. Just entering ./magick crashes with some utf8_validate error shown in valgrind. Might have sth. to do with this:

https://gitlab.gnome.org/GNOME/glib/-/issues/3481

But I'm no expert at all on this. My build immediately starts working when I'm building with 2.82.0. It might not even be ImageMagick's fault. It might be somewhere up in the dependency chain. Just wanted to let you know about this. Perhaps anyone else might be able to confirm this or alternatively tell me it's working with their build.

### Steps to Reproduce

Compile ImageMagick with glib 2.83.0.

### Images

There's just the segmentation fault. Nothing else I could provide unfortunately. If it's not reproducible on your end, I will try to find out more.

**Comment by urban-warrior** [comment]
We need a stack trace to determine if the issue is within ImageMagick and where.  Post the output of this command sequence:

```
$ gbd ./magick
(gdb) bt
```

**Comment by rgpublic** [comment]
I think you meant gdb and I needed a "run" in between (just to be sure):

![image](https://github.com/user-attachments/assets/e96be9c8-ac8b-4c82-8fd2-5bd69fa03ecf)

**Comment by urban-warrior** [comment]
The stack trace shows that the fault is outside ImageMagick.  It fails as the program is started, no ImageMagick code is touched.

**Comment by rgpublic** [comment]
Closing this. It's a bug in GLib and only even version number of Glib should be used:

https://gitlab.gnome.org/GNOME/glib/-/issues/3518#note_2285695

Sorry for the confusion. Thank you for pointing me to the right direction. Closing this.
