### ISSUE TITLE
Compare needs a better error message when the first argument dimensions are larger than second

### ISSUE THREAD

**Issue by betelgeuse** [ImageMagick/ImageMagick#7808]
### ImageMagick version

7.1.1-41

### Operating system

Linux

### Operating system, version and so on

Ubuntu 22.10 container image

### Description

As described in #2606 the second argument needs to be smaller than the first. The error message is currently not that helpful as it makes think the issue is with limit configuration. It should explicitly say the issue is with the relation of the dimensions of the arguments.

### Steps to Reproduce

```
root@a988579fc61e:~# compare -metric mse -subimage-search small.png  large.png null:
compare: width or height exceeds limit `small.png' @ error/cache.c/OpenPixelCache/3695.
```

### Images

```
root@a988579fc61e:~# magick -size 800x800 xc:white large.png
root@a988579fc61e:~# magick -size 400x400 xc:white small.png
```

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
