### ISSUE TITLE
Implicit Conversion warning in jpeg.c

### ISSUE THREAD

**Issue by blue-j** [ImageMagick/ImageMagick#7813]
### ImageMagick version

7.1.1-41

### Operating system

MacOS

### Operating system, version and so on

15.1.1

### Description

`coders/jpeg.c:798:10: warning: implicit conversion from enumeration type 'MagickBooleanType' to different enumeration type 'boolean' [-Wenum-conversion]`

for me, installing on macOS 15.1.1 from source, this doesn't stop the installation, but I have seen it stop others several times, which is puzzling.  it's likely a trivial fix, so i thought i'd mention it.

-J

### Steps to Reproduce

i think this happens with any install from source?  i've only done it on macOS 15.x so far.

### Images

![Screenshot 2024-11-28 at 3 49 08 PM](https://github.com/user-attachments/assets/08950629-bbee-4847-857f-b2d3046e7f05)

**Comment by dlemstra** [comment]
Thanks for mentioning this. I just pushed a patch to silence this warning.
