### ISSUE TITLE
default to lossless when converting png to webp

### ISSUE THREAD

**Issue by nycki93** [ImageMagick/ImageMagick#7817]
### Is your feature request related to a problem? Please describe.

I'm trying to write a script that compresses large images into lossy or lossless webp's. It seems that magick always defaults to lossy webp, so I have to add logic to my script to check the format of the input. And if the input is itself a webp, I can't use magick to find out whether it's lossy or lossless, I have to use an external tool like webpinfo.

### Describe the solution you'd like

The best option would be for imagemagick to convert lossless formats to lossless webp by default. This seems like it would always be the expected behavior.

It would also be nice if `magick identify` could be used to check if a webp is lossless or lossy.

### Describe alternatives you've considered

For a bash script, I could use an external tool such as webpinfo. My actual use case is NodeJS, so I could use a library like Sharp. It adds a dependency, but sometimes you just have to live with that. I still think that this particular use case is worth addressing, because converting a png to a lossy webp is unexpected behavior.

**Comment by dlemstra** [comment]
In the past there were situations where we used the quality of the input image when writing the output image. But that could cause issues with low quality input images. This has been removed and will not be added again in future versions.

You can detect in a `webp` image is lossless by checking if the quality of the image is `100`.
