### ISSUE TITLE
accept an invalid bmp image

### ISSUE THREAD

**Issue by jiuhao47** [ImageMagick/ImageMagick#7830]
### ImageMagick version

7.1.1-42 (Beta)

### Operating system

Linux

### Operating system, version and so on

Ubuntu 24.04.1 LTS x86_64, kernel version 6.10.11, compiler clang (18.1.3)

### Description

An invalid bmp image file should be rejected but it does not. 

I also tried other bmp image file parser graphicmagick, it can successfully reject it.

This exception is caused by `bmp_info.compression = 6` and `bmp_info.bits_per_pixel ! = 16 && bmp_info.bits_per_pixel ! = 32` trigger.

In the [BITMAPINFOHEADER (Windows CE 5.0) documentation](https://learn.microsoft.com/en-us/previous-versions/windows/embedded/aa452885(v=msdn.10)) provided by Microsoft, the requirement for `bits_per_pixel` for `bmp_info.compression = 6` is mentioned

Specifies that the bitmap is not compressed and that the color table consists of four DWORD color masks that specify the red, green, blue, and alpha components of each pixel.

*This is valid when used with 16- and 32-bpp bitmaps.*

This value is valid in Windows CE .NET 4.0 and later.

### Steps to Reproduce

I test it with the following code, and it does not report an error.

```cpp
#include <string>
#include <iostream>
#include <fstream>
#include <vector>
#include <cstdint>
#include <Magick++/Blob.h>
#include <Magick++/Image.h>
using namespace std;
using namespace Magick;

int main(int argc,char **argv) 
{ 
  // InitializeMagick(*argv);

  if (argc<2)
    {
        printf("need a bmp file\n");
        return 0;
    }

  Image image;
  try { 
    // Read a file
    image.read(argv[1] );
  } 
  catch( Exception &error_ ) 
    { 
      std::cout << "Caught exception: " << error_.what() << std::endl; 
      return 1; 
    } 
  return 0; 
}
```

However, when I test it with graphicmagick, it reports an error with the following logic:

`Graphicmagick/coders/bmp.c`: `ReadBMPImage`

```cpp
if (!(bmp_info.bits_per_pixel == 16 || bmp_info.bits_per_pixel == 32))
	ThrowBMPReaderException(CorruptImageError, CorruptImage, image);
```

Hope this helps!

### Images

[invalid.zip](https://github.com/user-attachments/files/18096059/invalid.zip)

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
