### ISSUE TITLE
MNG file consumes all RAM

### ISSUE THREAD

**Issue by Sembiance** [ImageMagick/ImageMagick#7832]
### ImageMagick version

7.1.1-38 Q16-HDRI x86_64 22398

### Operating system

Linux

### Operating system, version and so on

Gentoo

### Description

Running `magick identify _7AD4C6FDA1664599A5DE1A7FF89000C2` on the MNG file included in the attached zip causes magick to consume all system RAM until crash.

### Steps to Reproduce

`magick identify _7AD4C6FDA1664599A5DE1A7FF89000C2` 

### Images

[_7AD4C6FDA1664599A5DE1A7FF89000C2.zip](https://github.com/user-attachments/files/18127967/_7AD4C6FDA1664599A5DE1A7FF89000C2.zip)

**Comment by dlemstra** [comment]
You should add `<policy domain="resource" name="list-length" value=""/>` to your policy.xml file and set the value to the maximum number of images that you want. Your input file contains a ridiculous `LOOP` value and that is why it's trying to create `2147483647` images.

**Comment by Sembiance** [comment]
> You should add `<policy domain="resource" name="list-length" value=""/>` to your policy.xml file and set the value to the maximum number of images that you want. Your input file contains a ridiculous `LOOP` value and that is why it's trying to create `2147483647` images.

Ah, thanks, that worked. I have this set in policy.xml:
```
  <policy domain="resource" name="memory" value="4GiB"/>
  <policy domain="resource" name="map" value="4GiB"/>
```

But with this file magick blows right past that limit. Is that a bug? Or is there another setting somewhere for max memory usage?
