### ISSUE TITLE
creating pdf from monochrome png ends up garbled (adobe distiller works fine)

### ISSUE THREAD

**Issue by qnxor** [ImageMagick/ImageMagick#7834]
### ImageMagick version

7.1.1-41 Q16 x64

### Operating system

Windows

### Operating system, version and so on

10

### Description

Example input png attached at the end of this message. It has 6.7 KB.

When I use `magick bw.png bw.pdf` (I tried older versions too, down to 7.0.1) it ends up with a garbled pdf file, which is also 21.7 KB. PDF viewers show it as thin contours around the black lines, almost as if the conversion resulted in a median filter that detects edges. Attached:
[bw.pdf](https://github.com/user-attachments/files/18132769/bw.pdf)

If I use Adobe's distiller i get what I expect, and the PDF file size also matches (6.9 KB):
[bw-distiller.pdf](https://github.com/user-attachments/files/18132970/bw-distiller.pdf)

![bw.png](https://github.com/user-attachments/assets/ce50201f-0a51-4bd5-be76-6134434aea3c)

### Steps to Reproduce

see above

### Images

see above

**Comment by dlemstra** [comment]
It looks like turning the alpha channel off results in a better visual result: `magick bw.png -alpha off bw.pdf`. But I don't know if this is a pdf rendering issue or if we are doing something incorrectly.

**Comment by urban-warrior** [comment]
ImageMagick is behaving properly.  You have a two channel PNG image, one grayscale channel and one alpha which has identical pixel values.   The alpha is inverted, you can correct for that or add `-alpha off` to get reasonable results:

```
$ magick bw.png -alpha off bw.pdf
$ magick bw.png -channel A -negate +channel bw.pdf
```

**Comment by qnxor** [comment]
Thanks for the speedy reply. Interesting. That .png was actually produced with IM from a pdf file which contains an embedded color image (`pdfimages` says color=icc, comp=3, bpc=8, interp=yes), using `convert -trim -threshold 25% -density 200 page.pdf bw.png` ... which I expected to produce a 2 color grayscale image without an alpha channel. Sorry to ask in here, but how would I produce that? I tried adding `-colorspace Gray` and it didn't help.

Side note: interestingly doing `magick bw.png -alpha off bw.pdf` produces a 11 KB pdf, and `magick bw.png -channel A -negate +channel bw.pdf` produces a 22 KB pdf ... both quite a bit larger than the png and than the Distiller pdf (6.7 KB and 6.9 KB respectively).

**Comment by urban-warrior** [comment]
Remove the alpha channel and add `-compress group4` to your command-line to get a compressed PDF.  We currently do not support JBIG2 compression in PDF files.
