### ISSUE TITLE
Magick.exe doesn't process -help parameter

### ISSUE THREAD

**Issue by gaiking-uk** [ImageMagick/ImageMagick#7835]
### ImageMagick version

7.1.1-41

### Operating system

Windows

### Operating system, version and so on

Windows 11

### Description

Magick.exe does not provide help information when passing the `-help` parameter.

When calling `Magick.exe -help`, Magick.exe acts as if an invalid parameter has been passed and advises the user to call `Magick.exe -help`

### Steps to Reproduce

1. Run `magick.exe -help` on Windows 11

### ❌ Magick.exe doesn't process -help
![Magick exe -help](https://github.com/user-attachments/assets/9b51d257-b796-4930-abcf-f4285c293d25)

### ✅ Other apps successfully process -help parameter
![Conjure exe Mogrify exe -help](https://github.com/user-attachments/assets/2d345141-f098-48d8-b5cf-e0135ece3e82)

**Comment by urban-warrior** [comment]
Thank you for reporting the issue. We have successfully reproduced it and are actively working on a patch to resolve it. You can expect this patch to be merged into the [main GIT branch](https://github.com/ImageMagick/ImageMagick), later today. As part of our commitment to quality, this fix will also be included in the upcoming [beta releases of ImageMagick](https://imagemagick.org/archive/beta/) by tomorrow. Your patience and feedback are greatly appreciated.
