### ISSUE TITLE
Converting some images to PICT results in files that will crash a classic Mac system

### ISSUE THREAD

**Issue by briankendall** [ImageMagick/ImageMagick#7837]
### ImageMagick version

7.1.1-34

### Operating system

MacOS

### Operating system, version and so on

macOS 13.6.5

### Description

Converting certain images to a PICT file will produce files that will crash the system when attempting to view them on a classic Mac OS system. I've reproduced the crash on Macintosh System 7.1, Mac OS 8, and Mac OS 9.

Converting the PICT file back to a png using ImageMagick does not present any issues. I have not yet identified a modern app that presents a problem viewing the bad PICT file ImageMagick produces.

I've attached both the png file that exhibits this bug and the resulting PICT file that will crash a classic Mac.

### Steps to Reproduce

1. Convert the attached png file to a pict with the following:
    `magick bad.png bad.pict`
2. Copy `bad.pict` to a system running classic Mac OS and open it in any application that can view PICT files (such as SimpleText)
3. System freezes or displays a system error

### Images

![bad](https://github.com/user-attachments/assets/b782b586-90d3-40fc-bde1-8438975e597d)
[bad.pict.zip](https://github.com/user-attachments/files/18142059/bad.pict.zip)

**Comment by fmw42** [comment]
Perhaps Apple changed the PICT format between old classic Mac and newer OSX versions.

**Comment by briankendall** [comment]
> Perhaps Apple changed the PICT format between old classic Mac and newer OSX versions.

I don't believe that's the case. The latest PICT format is "Extended Version 2" which has been around since at least the 1990s, and which is what ImageMagick is producing based off of the version information in the outputted file.

**Comment by dlemstra** [comment]
Is this not an issue/bug inside the SimpleText application?

**Comment by briankendall** [comment]
SimpleText uses the same system-level API to display a PICT as every other app in classic Mac OS. I can trigger the crash using any application that can read PICT files.

It's possible that their implementation has a bug that would cause it to crash reading an otherwise valid PICT, but I think that's unlikely. Also, given that Apple's PICT implementation from classic Mac OS is essentially the canonical implementation, I think we need to assume that ImageMagick is producing invalid files.

**Comment by briankendall** [comment]
I do believe I found the issue. The key is in page 119 of Inside Macintosh: Volume V, where it describes how the pixel data of a PICT should be written out. Here's a screen shot of the relevant section:

<img width="550" alt="Screenshot 2024-12-16 at 9 42 41 PM" src="https://github.com/user-attachments/assets/1191910f-0fa0-4cba-a149-c5f8640feb9f" />

The key part is where it says "If rowBytes > 250". In `bad.pict`, rowBytes is 240, but the `byteCount` of each scanline is two bytes rather than one. I just manually modified the file so that the `byteCount` entries for each scanline is only one byte, and it fixed the file, in that classic Mac OS can now properly read it. (See : [fixed.pict.zip](https://github.com/user-attachments/files/18159393/fixed.pict.zip) )

This bug apparently affects ImageMagick's PICT reader as well, as it's unable to open `fixed.pict` and produces this error:

    error/pict.c/ReadPICTImage/1267.

In fact, I think that points me to the error, see: https://github.com/ImageMagick/ImageMagick/blob/b77eb776838b6039834948bb63f8106a7980554b/coders/pict.c#L504

That should be:

    if (bytes_per_line > 250)

Same here: https://github.com/ImageMagick/ImageMagick/blob/b77eb776838b6039834948bb63f8106a7980554b/coders/pict.c#L694

And here too: https://github.com/ImageMagick/ImageMagick/blob/b77eb776838b6039834948bb63f8106a7980554b/coders/pict.c#L1087

**Comment by briankendall** [comment]
Since I went through all the effort of figuring that out, why not have a PR! #7840

**Comment by dlemstra** [comment]
The PR has been merged and thanks for taking the time to fix this for us.

**Comment by bobfriesenhahn** [comment]
Failing to be able to read the existing PICT files that ImageMagick wrote for perhaps 30 years seems pretty brutal.
