### ISSUE TITLE
ImageMagick-Windows source code cloning is corrupt!

### ISSUE THREAD

**Issue by pprasanthk** [ImageMagick/ImageMagick#7842]
### ImageMagick version

ImageMagick-Windows

### Operating system

Windows

### Operating system, version and so on

Windows 10 and above.

### Description

Hi all, 

We downloaded ImageMgick-Windows source code from the below location, unzipped it and ran CloneRepositories.IM7.cmd to clone ImageMagick-7 source code: 
https://github.com/ImageMagick/ImageMagick-Windows

Please see the CloneRepositories.IM7.cmd error snapshot attached: 

![ImageMagick-Windows-Clone-IM7_Bug](https://github.com/user-attachments/assets/565cc1a7-d591-40cc-9567-003f433d5a52)

--
Thanks
Prasanth

### Steps to Reproduce

1. Download ImageMagick source code zip file from the URL https://github.com/ImageMagick/ImageMagick-Windows.
2. Unzip it.
3. 3. Run CloneRepositories.IM7.cmd and observe the error.

### Images

![ImageMagick-Windows-Clone-IM7_Bug](https://github.com/user-attachments/assets/f5a990ad-4d15-45b3-ab2a-8195b896fbbf)

**Comment by dlemstra** [comment]
This looks like an issue in your git client or connection. Our daily build ran successful: https://github.com/ImageMagick/ImageMagick/actions/runs/12387310922/job/34576554883
