### ISSUE TITLE
Add AI to list of supported formats

### ISSUE THREAD

**Issue by cancan101** [ImageMagick/ImageMagick#7844]
@cancan101: Yes, IM delegates rasterization of AI files to Ghostscript. Inserting "-verbose" at the start will show this. Yes, https://imagemagick.org/script/formats.php should list AI but doesn't. This a documentation bug.

_Originally posted by @snibgo in https://github.com/ImageMagick/ImageMagick/discussions/4241#discussioncomment-11581231_

**Comment by dlemstra** [comment]
You are more than welcome to create a PR to fix that in the file `include/formats.php` of the https://github.com/ImageMagick/Website repository.

**Comment by urban-warrior** [comment]
We added the AI image format to the formats web page.
