### ISSUE TITLE
Conversions of some HEIC and HEIF files to PDF and TIFF are failing only on Windows Server 2022 Standard operating system.

### ISSUE THREAD

**Issue by pprasanthk** [ImageMagick/ImageMagick#7846]
### ImageMagick version

7.1.1-41

### Operating system

Windows

### Operating system, version and so on

Microsoft Windows Server 2022 Standard

### Description

Hi, 

Conversions of some HEIC and HEIF files to PDF and TIFF on **Windows Server 2022 Standard** are failing with the below error: 
**magick.exe: unable to load module 'C:\Program Files (x86)\Kofax\KIC-ED\MC\bin\ImageMagick\IM_MOD_RL_HEIC_.dll': A dynamic link library (DLL) initialization routine failed.
 @ error/module.c/OpenModule/1293.
magick.exe: no decode delegate for this image format `HEIC' @ error/constitute.c/ReadImage/746.**

We noticed the same error when we tried to convert the attached FailedTest.HEIC to TIFF as well with the same error: 
**magick.exe C:\IM\FailedTest.heic failedTest.tiff
magick.exe: unable to load module 'C:\Program Files (x86)\Kofax\KIC-ED\MC\bin\ImageMagick\IM_MOD_RL_HEIC_.dll': A dynamic link library (DLL) initialization routine failed.
 @ error/module.c/OpenModule/1293.
magick.exe: no decode delegate for this image format `HEIC' @ error/constitute.c/ReadImage/746.**

We saw that **IM_MOD_RL_HEIC_.dll** is present in the current directory from which the test was executed.

For example please find the FaildTest.HEIC inside the attached FailedTest.zip: 
[FailedTest.zip](https://github.com/user-attachments/files/18198766/FailedTest.zip)

Please not that this conversion is working on Windows 10 and Windows 11 operating systems.
--
Thanks
Prasanth

### Steps to Reproduce

Run magick.exe on the attached FaildTest.HEIC to convert it to PDF and TIFF on Microsoft Windows Server 2022 Standard operating system.
Please not that this conversion is working on Windows 10 and Windows 11 operating systems.

### Images

[FailedTest.zip](https://github.com/user-attachments/files/18198836/FailedTest.zip)

**Comment by fmw42** [comment]
What version of libheif?

**Comment by fmw42** [comment]
Not necessarily.  I read a recent complaint about the version of libheif in one of the current IM versions.  

`magick -list format`

find the line for HEIC and at the end of that line it will show your version.  Be sure it is the latest.

**Comment by pprasanthk** [comment]
@fmw42 

When I run the command **magick -list format** on Windows-10 OS, I am getting the output for HEIF as below: 
**HEIF  HEIC      r--   High Efficiency Image Format (1.19.3)**
But, when I run this command on Windows Server 2022 Standard operating system., I am not getting any entry for HEIF.
Please find both the outputs below for your reference below: 
[Windows-10_Output.txt](https://github.com/user-attachments/files/18201017/Windows-10_Output.txt)
[WindowsServer2002Standard_Output.txt](https://github.com/user-attachments/files/18201019/WindowsServer2002Standard_Output.txt)

Could you please suggest us why is this difference and what to do to fix this?

--
Thanks
Prasanth

**Comment by pprasanthk** [comment]
@fmw42

Please find the outputs of magick -version for both Windows 10 and Windows Server 2002 Standard operating systems: 
[Win2002_MagickVersion.txt](https://github.com/user-attachments/files/18201194/Win2002_MagickVersion.txt)
[Win10MagickVersion.txt](https://github.com/user-attachments/files/18201196/Win10MagickVersion.txt)

Please not that I did not install ImageMagick. To avoid Windows registry dependencies I built all the ImageMagick binaries from the ImageMagick source code and are using them.

I am using the same binaries on both Windows 10 and Windows Server 2002 Standard operating systems and little surprised why the same set of binaries causing different behavior on different Windows operating systems.
Please let me know if you need any more information.


--
Thanks
Prasanth

**Comment by fmw42** [comment]
Both versions list heic. But -list format only shows for your Win10 system.  I do not understand that.

Perhaps your Win2002 does not have a current version.  Can you upgrade the libheif on your Win2002 system?

**Comment by pprasanthk** [comment]
I have the same IM_MOD_RL_heic_.dll on both the machines.
I think there is some issue only on Windows Server 2002 Standard probably while loading this DLL.
Could you please try to reproduce this issue in Windows Server 2002 Standard by simply running the command **magick.exe C:\IM\FailedTest.heic failedTest.tiff** and see why this issue is happening only on Windows Server 2002 Standard machine?

--
Thanks
Prasanth

**Comment by fmw42** [comment]
One of the IM developers or Windows users will have to do that, if possible.  I am on a Mac and have no experience with Window.

Have you tried re-installing IM on your server?

**Comment by pprasanthk** [comment]
@fmw42 
As I mentioned earlier, I did not install IM on my Windows Server 2022 Standard machine. Instead, I have built the IM binaries from IM source code, put it on a directory and trying to convert an HEIC/HEIF file to PDF and TIFF using magick.exe and I am getting the above mentioned error.

Could you please ask one of your IM windows developers to try this scenario/conversion of HEIC/HEIF files to PDF and TIFF using magick.exe on a Windows Server 2022 Standard machine. 
Please note that as I mentioned earlier, this issue is happening only on Windows Server 2022 Standard machine but is working fine on Windows-10/Windows-11 machines.

Please let me know if you need any more information.

--
Thanks
Prasanth

**Comment by fmw42** [comment]
If you installed from source, you will have NO delegates. That is likely your issue. The IM developers will read this post and they will respond accordingly.

**Comment by pprasanthk** [comment]
Binaries installed from source is working fine for me on Windows-10/Windows-11 machine, but it is failing only on Windows Server 2022 Standard machine. But as you said, I will wait for the response form the other IM developers (possibly IM Windows developers). 

--
Thanks
Prasanth

**Comment by fmw42** [comment]
There is a difference between a binary install and a source install. The latter does not come with delegates. Please clarify which you used. See https://imagemagick.org/script/download.php#windows vs https://imagemagick.org/archive/

**Comment by pprasanthk** [comment]
I tried with source built binaries. Could you please let me know what difference it is making only on windows Server 2022 platform?

**Comment by snibgo** [comment]
> When I run the command magick -list format on Windows-10 OS, I am getting the output for HEIF as below:
HEIF HEIC r-- High Efficiency Image Format (1.19.3)
But, when I run this command on Windows Server 2022 Standard operating system., I am not getting any entry for HEIF.

> I built all the ImageMagick binaries from the ImageMagick source code and are using them.

So, the problem is that your Windows Server 2022 build of IM doesn't include libheif. Perhaps you didn't install libheif on that machine. You can compare the delegate directories on the Windows 11 installation.

I don't use Windows Server 2022, but your problem seems to be in the build of IM, not the operating system.

I don't use Visual Studio, and can't advise on that.

**Comment by pprasanthk** [comment]
When we run magick.exe on Windows-10/11 we are getting correct output. But when we are running on Windows Server 2002, we are getting this error. So I would say this issue is specific to particular version of windows OS. Could you please check this? This issue is straight away reproducible for me on windows server 2002.

**Comment by pprasanthk** [comment]
Also, we used the same build for both windows 10/11 and windows server 2022.

**Comment by dlemstra** [comment]
This looks like an issue with your machine then. I noticed that you wrote both 2002 and 2002 but I suspect that you meant 2022 then. I just create a Virtual Machine in Azure with Windows 2022 and this seems to be working there:

```cmd
PS C:\Users\dirk> systeminfo | findstr /B /C:"OS Name" /B /C:"OS Version"
OS Name:                   Microsoft Windows Server 2022 Datacenter Azure Edition
OS Version:                10.0.20348 N/A Build 20348
PS C:\Users\dirk> magick FailedTest.heic info:
FailedTest.heic HEIC 3024x4032 3024x4032+0+0 8-bit sRGB 1.52991MiB 0.001u 0:00.001
PS C:\Users\dirk> magick -version
Version: ImageMagick 7.1.1-41 Q16-HDRI x64 bbdcbf7:20241116 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Channel-masks(64-bit) Cipher DPC HDRI Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg jxl lcms lqr lzma openexr pangocairo png ps raqm raw rsvg tiff webp xml zip zlib
Compiler: Visual Studio 2022 (194234433)
```

**Comment by pprasanthk** [comment]
The same binaries are not working on Windows Server 2002 Standard version, but working fine on Windows 10 and Windows 11. Could you please try this normal OS instead of Azure? Also, we noticed this error on 3 VMs running on Windows Server 2002 Standard OS. Also, all other conversions are working fine except HEIC/HEIF on our Windows Server 2002 Standard VMs.

--
Thanks
Prasanth

**Comment by dlemstra** [comment]
As I said before it must be something with your machine I don't have the time or the license to debug this on a Windows Server 2022 Standard. Maybe you need to install the Visual C++ Redistributable Package?

p.s. Why do you keep typing 2002 instead of 2022?

**Comment by pprasanthk** [comment]
@dlemstra 

Apologies for the type 2002 instead of 2022.
Yes, your hint worked. The Visual C++ Redistributable package (msvcp140.dll) was missing. By adding this DLL, conversion of HEIC and HEIF files to PDF/TIFF is working fine now.
Thank you for your help and instructions. I closed this bug. 


--
Thanks
Prasanth

**Comment by dlemstra** [comment]
Thanks for coming back and telling us that this resolved your issue.
