### ISSUE TITLE
codecs/uil.c matte handling is buggy, only uses last pixel for matte

### ISSUE THREAD

**Issue by msmeissn** [ImageMagick/ImageMagick#785]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Reviewing issue #562 the security problem is fixed incorrectly.

Note that you have two loops of rows*columns, the first filling in the matte array, the secoind one should be reading it out.

As it is... the first loop fills the matte_image array using i= 0; and i++ 
The second loop however only uses matte_image[i], without incrementing i, so the matte is only used from the last pixel of the original image. 

It should also set i=0;
at begin and i++ over the second loop.

### Steps to Reproduce

code review

### System Configuration
looking at git code.

- ImageMagick version: master at 2017-09-28
- Environment (Operating system, version and so on):
- Additional information:

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
