### ISSUE TITLE
Option to allow importing svg from svg

### ISSUE THREAD

**Issue by anatawa12** [ImageMagick/ImageMagick#7854]
### Is your feature request related to a problem? Please describe.

I tried to convert svg to png with imagemagick but I failed to import svg from svg.

I found commit a3b0f6c0677e4db09236ccb0c934db7aef3cd52f disables this feature manually so I assumed this is expected behavior but it is useful to allow import svg from svg

### Describe the solution you'd like

An option to allow svg recursion that should not be used for untrusted svgs.

### Describe alternatives you've considered

Allow svg recursion with reasonably big limit (ten?)

**Comment by fmw42** [comment]
Please provide your IM command line and your SVG file.  Edit your policy.xml file, if needed, to permit reading of SVG files.

**Comment by urban-warrior** [comment]
SVG recursion provides a vector for nefarious users to crash ImageMagick so we removed the feature: alice.svg calls bob.svg which calls alice.svg.

With the current code set we could not find a convenient method to conveniently limit the depth of the recursion.  If you find a robust method to prevent run-away recursion, post a pull request and we will consider adding it to the main branch.

**Comment by anatawa12** [comment]
> Please provide your IM command line and your SVG file.

(subsituated from original cause)

```
magick test.svg test.png
```

```svg
<svg width="100%" height="100%" viewBox="0 0 4096 4096" version="1.1" xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve"
>
    <rect x="0" y="0" width="4096" height="4096" style="fill:rgb(45,45,45);"/>
    <image x="260.5858" y="3689.09" width="240px" height="240px" xlink:href="./lucide-triangle-alert.svg"/>
</svg>
```
```svg
<!-- lucide-triangle-alert.svg -->
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#EDCE00" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-triangle-alert"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3"/><path d="M12 9v4"/><path d="M12 17h.01"/></svg>
```

I know nefarious svg can cause crash with infinite recursion but for I want this for kown safe svg file.

**Comment by urban-warrior** [comment]
We added a patch to support this self-evident define: `-define svg:embedding=true`.
