### ISSUE TITLE
.png input parser problem ?

### ISSUE THREAD

**Issue by jpka-** [ImageMagick/ImageMagick#7860]
### ImageMagick version

7.1.1-43 (it says), 7.1.1.43-1 (pacman says)

### Operating system

Linux

### Operating system, version and so on

Version: ImageMagick 7.1.1-43 Q16-HDRI x86_64 22550 https://imagemagick.org Copyright: (C) 1999 ImageMagick Studio LLC License: https://imagemagick.org/script/license.php Features: Cipher DPC HDRI Modules OpenCL OpenMP(4.5)  Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype heic jbig jng jp2 jpeg jxl lcms lqr ltdl lzma openexr pangocairo png raqm raw rsvg tiff uhdr webp wmf x xml zip zlib zstd Compiler: gcc (14.2) Linux 6.12.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 19 Dec 2024 21:29:01 +0000 x86_64 GNU/Linux. OS: ArchLinux

### Description

Hello. Trying to process an .png image, which itself also result of Magick, (and looks not damaged in Okular and Gimp), i got strange result: it shifted by 16 px down. It not depends on _output_ file type (i test .png & .gif output), and bug disappear if i change _input_ from .png to (converted by other tool) .gif, so looks like .png input parser problem.

`magick phase1.png -background white -gravity center -extent 150x phase2.png`
`magick phase1.png -background white -gravity center -extent 150x phase2.gif`

I've add zipped phase1.png here, to keep it exactly bit-by-bit:
[phase1.zip](https://github.com/user-attachments/files/18253777/phase1.zip)

### Steps to Reproduce

1. Take 1st attached image (phase1.png)
2. Run proposed commands
3. See if results (phase2{.png,.gif}) are shifted down by 16 px for both commands.

### Images

![phase1](https://github.com/user-attachments/assets/a8e9603e-5b00-4465-b2a8-ce449fae275c)
![phase2](https://github.com/user-attachments/assets/cfdf1364-df7c-4dad-a143-444e6c584d0f)

**Comment by fmw42** [comment]
The issue is that your geometry is not the same as your page geometry. So you need to add +repage after reading the file.

`magick phase1.png +repage -background white -gravity center -extent 150x phase2b.png`

![phase2b](https://github.com/user-attachments/assets/d6348558-d3e6-4d05-a128-dc44f1de2776)

What was the command you used to create the input PNG? Perhaps you need to use +repage before saving the output of that command (which is the input you used here).

**Comment by jpka-** [comment]
1. Yes, this new command with _+repage_, works perfectly.
2. The commands which produces this "strange" .png input, are also does not contain _+repage_:
`QImage image = QImage(... ,QImage::Format_RGB32) ...
image.save(QString("out.bmp")` from simple Qt example;
`magick out.bmp phase0.png`
`magick phase0.png -sample 100% -flop -rotate 270 phase1.png`
I will add _+repage_ now to these.
P.S. The "strange" fact that .gif format not show the problem, now i see is not format depend, but due to fact that .gif was created by other tool (Gimp). I (re)create .png from .png using Gimp and problem is also gone (without _+repage_).
Thank you so much for quick & valuable help.

**Comment by fmw42** [comment]
You only need to add +repage to

`magick phase0.png -sample 100% -flop -rotate 270 phase1.pn`g

just before the output

**Comment by jpka-** [comment]
Tested, works well. Thanks!

**Comment by jpka-** [comment]
Sorry for reopening noise, can't figure why it occurs.
