### ISSUE TITLE
coders/txt.c:198: ReadTEXTImage: Assertion `exception->signature == 0xabacadabUL' failed.

### ISSUE THREAD

**Issue by erjoalgo** [ImageMagick/ImageMagick#789]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

when trying to convert text to an image, I get the error below:

```sh
$ echo test | convert text:- text_box_trimmed.png
convert: ../../coders/txt.c:198: ReadTEXTImage: Assertion `exception->signature == 0xabacadabUL' failed.
Aborted
```

### Steps to Reproduce

```
$ echo test | convert text:- text_box_trimmed.png
convert: ../../coders/txt.c:198: ReadTEXTImage: Assertion `exception->signature == 0xabacadabUL' failed.
Aborted
```

### System Configuration

- ImageMagick version: 
```
$ convert -version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2017-03-12 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2014 ImageMagick Studio LLC
Features: DPC Modules OpenMP
Delegates: bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff wmf x xml zlib
```
- Environment (Operating system, version and so on): Debian GNU/Linux 8.8 (jessie)
- Additional information:

**Comment by mikayla-grace** [comment]
Try the latest release of ImageMagick version 6.9.9-15.  Your command completes without complaint.
