### ISSUE TITLE
 heap-buffer-overflow in coders/psd.c:2240 PSDPackbitsEncodeImage

### ISSUE THREAD

**Issue by moshekaplan** [ImageMagick/ImageMagick#79]
https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1533450

**Comment by dlemstra** [comment]
Can you get the latest from GIT and let us know if the problem is resolved?

**Comment by moshekaplan** [comment]
The bug appears to have been fixed.

**Comment by attritionorg** [comment]
Can you link to the fixing commit please?

**Comment by dlemstra** [comment]
If you want to create a patch for this you should use the commits from 15/16 jan to psd.c

**Comment by dlemstra** [comment]
The following patch resolves this: https://github.com/ImageMagick/ImageMagick/commit/6f1879d498bcc5cce12fe0c5decb8dbc0f608e5d#diff-57d2cedbdffead46c821c7b3601b3464
