### ISSUE TITLE
null pointer dereference in XGetWindowInfo

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#801]
Here is the critical code:(in XGetWindowInfo)
```
        if (window->segment_info == (void *) NULL)                                                   
          window->segment_info=AcquireQuantumMemory(2,sizeof(*segment_info));     //4625
        segment_info=(XShmSegmentInfo *) window->segment_info;
        segment_info[0].shmid=(-1);
        segment_info[0].shmaddr=(char *) NULL;
        segment_info[1].shmid=(-1);
        segment_info[1].shmaddr=(char *) NULL;
```
AcquireQuantumMemory(...) may return NULL, so some of the following operations on the "window->segment_info" will dereference null pointer to cause memory error.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
