### ISSUE TITLE
null pointer dereference in NTOpenDirectory

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#806]
Here is the critical code : (in NTOpenDirectory)
```
  entry=(DIR *) AcquireMagickMemory(sizeof(DIR));            //1790
  if (entry != (DIR *) NULL)
    {
      entry->firsttime=TRUE;
      entry->hSearch=FindFirstFileW(file_specification,&entry->Win32FindData);
    }
  if (entry->hSearch == INVALID_HANDLE_VALUE)            //1796
    {
      if(wcsncat(file_specification,L"*.*",
        MagickPathExtent-wcslen(file_specification)-1) == (wchar_t*) NULL)
        {
          entry=(DIR *) RelinquishMagickMemory(entry);
          return((DIR *) NULL);
        }
      entry->hSearch=FindFirstFileW(file_specification,&entry->Win32FindData);
      if (entry->hSearch == INVALID_HANDLE_VALUE)
        {
          entry=(DIR *) RelinquishMagickMemory(entry);
          return((DIR *) NULL);
        }
    }
```

Line 1790 AcquireMagickMemory(...) may return NULL, so some of the following operations (eg:line 1796) on the "entry" will dereference null pointer to cause memory error.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
