### ISSUE TITLE
out-of-bounds read in coders/sun.c:499 ReadSUNImage

### ISSUE THREAD

**Issue by moshekaplan** [ImageMagick/ImageMagick#81]
https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1533447

**Comment by urban-warrior** [comment]
Grab the latest from GIT and let us know if the problem is resolved.

**Comment by moshekaplan** [comment]
I didn't examine it closely, but a similar behavior manifests with poc2: https://bugs.launchpad.net/ubuntu/+source/imagemagick/+bug/1533447/+attachment/4550177/+files/id%3A000031%2Csig%3A06%2Csrc%3A001500%2Cop%3Aflip1%2Cpos%3A15

**Comment by urban-warrior** [comment]
Grab the latest from GIT and let us know if the problem is resolved.

**Comment by moshekaplan** [comment]
The bug appears to have been fixed.
