### ISSUE TITLE
memory leak in WritePDBImage

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#810]
Here is the critical code: (in WritePDBImage)
```
  runlength=(unsigned char *) AcquireQuantumMemory(9UL*packets,            //839
    image->rows*sizeof(*runlength));
  if (runlength == (unsigned char *) NULL)
    ThrowWriterException(ResourceLimitError,"MemoryAllocationFailed");        //842
  buffer=(unsigned char *) AcquireQuantumMemory(512,sizeof(*buffer));
  if (buffer == (unsigned char *) NULL)
    ThrowWriterException(ResourceLimitError,"MemoryAllocationFailed");        //845 not free correctly before
  packet_size=(size_t) (image->depth > 8 ? 2 : 1);
  scanline=(unsigned char *) AcquireQuantumMemory(image->columns,packet_size*
    sizeof(*scanline));
  if (scanline == (unsigned char *) NULL)
    ThrowWriterException(ResourceLimitError,"MemoryAllocationFailed");        //850 not free correctly before
```

AcquireQuantumMemory(…) may return NULL,if “buffer” is null,line 845 may cause memory leak about “runlength”;if “scanline” is null, line 850 may cause memory leak about “runlength” and “buffer”.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
