### ISSUE TITLE
memory leak in DecodeImage 

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#811]
Here is the critical code :(in DecodeImage (cocers/pict.c) )
```
  pixels=(unsigned char *) AcquireQuantumMemory(image->rows,row_bytes*        //449
    sizeof(*pixels));
  if (pixels == (unsigned char *) NULL)
    return((unsigned char *) NULL);
  *extent=row_bytes*image->rows*sizeof(*pixels);
  (void) ResetMagickMemory(pixels,0,*extent);
  scanline=(unsigned char *) AcquireQuantumMemory(row_bytes,2*        //455
    sizeof(*scanline));
  if (scanline == (unsigned char *) NULL)
    return((unsigned char *) NULL);        //458 not free correctly before

```
Line 458 , if the “scanline" is null and the “pixels” is not ,it may cause memory leak error.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
~
