### ISSUE TITLE
memory leak in ReadOneMNGImage

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#812]
Here is the critical code : (in ReadOneMNGImage)
```
                next=(Quantum *) AcquireQuantumMemory(length,sizeof(*next));    //6905
                prev=(Quantum *) AcquireQuantumMemory(length,sizeof(*prev));    //6906
                if ((prev == (Quantum *) NULL) ||
                    (next == (Quantum *) NULL))
                  {
                     image=DestroyImageList(image);
                     ThrowReaderException(ResourceLimitError,                            //6912
                       "MemoryAllocationFailed");
                  }

```
If one of the “next” and “prev” is null and the other is not, it may cause memory leak error.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
