### ISSUE TITLE
memory leak in WriteTIFFImage

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#813]
Here is the critical code : (in WriteTIFFImage)
```
        red=(uint16 *) AcquireQuantumMemory(65536,sizeof(*red));        //4132
        green=(uint16 *) AcquireQuantumMemory(65536,sizeof(*green));
        blue=(uint16 *) AcquireQuantumMemory(65536,sizeof(*blue));
        if ((red == (uint16 *) NULL) || (green == (uint16 *) NULL) ||    //4135
            (blue == (uint16 *) NULL))
          ThrowWriterException(ResourceLimitError,"MemoryAllocationFailed");    //4137
```
AcquireQuantumMemory(…) may return NULL,if one of the “red” 、“green” and ”blue”  is NULL，and the others are not，this may cause memory leak error in “If statement”.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
