### ISSUE TITLE
memory leak in sRGBTransformImage

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#814]
Here is the critical code : (in sRGBTransformImage)
```
  x_map=(TransformPacket *) AcquireQuantumMemory((size_t) MaxMap+1UL,    //754
    sizeof(*x_map));
  y_map=(TransformPacket *) AcquireQuantumMemory((size_t) MaxMap+1UL,
    sizeof(*y_map));
  z_map=(TransformPacket *) AcquireQuantumMemory((size_t) MaxMap+1UL,
    sizeof(*z_map));
  if ((x_map == (TransformPacket *) NULL) ||                            //760
      (y_map == (TransformPacket *) NULL) ||
      (z_map == (TransformPacket *) NULL))
    ThrowBinaryException(ResourceLimitError,"MemoryAllocationFailed”,    //763
      image->filename);
```

AcquireQuantumMemory(…) may return NULL,if one of the “x_map” 、“y_map” and ”z_map”  is NULL，and the others are not，this may cause memory leak error in “If statement”.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
~
