### ISSUE TITLE
memory leak in HuffmanDecodeImage

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#815]
Here is the critical code : (in HuffmanDecodeImage)
```
  mb_hash=(HuffmanTable **) AcquireQuantumMemory(HashSize,sizeof(*mb_hash));        //452
  mw_hash=(HuffmanTable **) AcquireQuantumMemory(HashSize,sizeof(*mw_hash));
  scanline=(unsigned char *) AcquireQuantumMemory((size_t) image->columns,
    sizeof(*scanline));
  if ((mb_hash == (HuffmanTable **) NULL) ||                                        //456
      (mw_hash == (HuffmanTable **) NULL) ||
      (scanline == (unsigned char *) NULL))
    ThrowBinaryException(ResourceLimitError,"MemoryAllocationFailed”,            //459
      image->filename);
```
AcquireQuantumMemory(…) may return NULL,if one of the “mb_hash” 、“mw_hash” and ”scanline”  is NULL，and the others are not，this may cause memory leak error in “If statement”.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
