### ISSUE TITLE
memory leak in TraceStrokePolygon

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#816]
Here is the critical code : (in TraceStrokePolygon)
```
  path_p=(PointInfo *) AcquireQuantumMemory((size_t) max_strokes,        //5991
    sizeof(*path_p));
  path_q=(PointInfo *) AcquireQuantumMemory((size_t) max_strokes,
    sizeof(*path_q));
  polygon_primitive=(PrimitiveInfo *) AcquireQuantumMemory((size_t)
    number_vertices+2UL,sizeof(*polygon_primitive));
  if ((path_p == (PointInfo *) NULL) || (path_q == (PointInfo *) NULL) ||    //5997
      (polygon_primitive == (PrimitiveInfo *) NULL))
    return((PrimitiveInfo *) NULL);                                        //5999
```

AcquireQuantumMemory(…) may return NULL,if one of the “path_p” 、“path_q” and ”polygon_primitive”  is NULL，and the others are not，this may cause memory leak error in “If statement”.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
