### ISSUE TITLE
memory leak in RotationalBlurImage

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#818]
Here is the critical code : (in RotationalBlurImage)
```
  cos_theta=(double *) AcquireQuantumMemory((size_t) n,    //2847
    sizeof(*cos_theta));
  sin_theta=(double *) AcquireQuantumMemory((size_t) n,
    sizeof(*sin_theta));
  if ((cos_theta == (double *) NULL) ||                    //2851
      (sin_theta == (double *) NULL))
    {
      blur_image=DestroyImage(blur_image);
      ThrowImageException(ResourceLimitError,"MemoryAllocationFailed");    //2855
    }
```
AcquireQuantumMemory(…) may return NULL,if one of the “cos_theta” and ”sin_theta”  is NULL at and the other is not，this may cause memory leak error.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
