### ISSUE TITLE
memory leak in MontageImageList

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#819]
Here is the critical code : (in MontageImageList)
```
    montage->montage=AcquireString((char *) NULL);        //629
    tile=0;
    extent=1;
    while (tile < MagickMin((ssize_t) tiles_per_page,(ssize_t) number_images))
    {
      extent+=strlen(image_list[tile]->filename)+1;
      tile++;
    }
    montage->directory=(char *) AcquireQuantumMemory(extent,        //637
      sizeof(*montage->directory));
    if ((montage->montage == (char *) NULL) ||
        (montage->directory == (char *) NULL))
      ThrowImageException(ResourceLimitError,"MemoryAllocationFailed");       //641
```

AcquireQuantumMemory(…) may return NULL,if one of the “montage->montage” and ”montage->directory”  is NULL and the other is not，this may cause memory leak error.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
