### ISSUE TITLE
memory leak in XDitherImage

### ISSUE THREAD

**Issue by bestshow** [ImageMagick/ImageMagick#821]
Here is the critical code : (in XDitherImage)
 ```
     red_map[i][j]=(unsigned char *) AcquireQuantumMemory(256UL,        //2162
        sizeof(*red_map));
      green_map[i][j]=(unsigned char *) AcquireQuantumMemory(256UL,
        sizeof(*green_map));
      blue_map[i][j]=(unsigned char *) AcquireQuantumMemory(256UL,
        sizeof(*blue_map));
      if ((red_map[i][j] == (unsigned char *) NULL) ||                //2168
          (green_map[i][j] == (unsigned char *) NULL) ||
          (blue_map[i][j] == (unsigned char *) NULL))
        {
          ThrowXWindowException(ResourceLimitError,"MemoryAllocationFailed”,    //2172
            image->filename);
```
AcquireQuantumMemory(…) may return NULL,if one of the “red_map[i][i]”、“green_map[i][i]” and ”blue_map[i][i]”  is NULL and the others are not，this may cause memory leak error.

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
