### ISSUE TITLE
Regression: "extra check" causes existing code to fail

### ISSUE THREAD

**Issue by Schnouki** [ImageMagick/ImageMagick#825]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Recent versions of ImageMagick cause a regression in Emacs image handling: after starting Emacs, the user can load a first image, but trying to load any image after that fails silently (it just shows an empty square).

By running `git bisect`, I was able to trace this issue to commit 870af5fe9befdb59f0533b12ffafd7b3b5a67e82. This commits adds a `magick_list_initialized` boolean that is set to `MagickTrue` once `magick_list` has been initialized.

However it seems that if `magick_list` is cleared (with `DestroySplayTree()`, as in `MagickComponentTerminus()`), the `magick_list_initialized` is not re-set to `MagickFalse`, which causes subsequent calls to ImageMagick to fail.

I wrote a small patch that does just that but it's apparently not enough (loading images in Emacs works, but calling functions such as `(imagemagick-types)` hangs Emacs). Same thing when just reverting commit 870af5fe9befdb59f0533b12ffafd7b3b5a67e82.

I'm not familiar with ImageMagick internals *at all* so I have no idea how to fix this... But I can easily test any changes :)

### Steps to Reproduce

1. On ArchLinux, install Emacs: `pacman -S emacs`. This installs ImageMagick as a dependency.
2. Start Emacs: `emacs -Q`
3. Check that ImageMagick behaves correctly: in Emacs: type `M-: (imagemagick-types) RET`: it should show a list of supported types in the minibuffer (`(3G2 3GP AAI AI ART AVI AVS BGR BGRA ...)`). With a bad version of ImageMagick, it hangs Emacs.
4. Open an image: `C-x C-f ~/test.jpg RET". It should show the image.
5. Show it as text with `C-c`, and as image again with `C-c` again: it should show the image. With a bad version of ImageMagick, it shows an empty square instead.
6. Re-run the `(imagemagick-types)` function: it should show the same list of supported types. With a bad version of ImageMagick, it returns an empty list (`nil`) instead. 
7. Go to the `*Messages*` buffer: `C-x b *Messages* RET`. With a bad version of ImageMagick, it contains several error messages: "ImageMagick error: no decode delegate for this image format `JPEG' @ error/constitute.c/ReadImage/504".

### System Configuration

- ImageMagick version: 6.9.9-17 (ArchLinux package imagemagick-6.9.9.17), also tested with 6.9.9-15 compiled by hand
- Environment (Operating system, version and so on): Arch Linux
- Additional information: Emacs 25.3

This issue has also been reported on the Arch bugtracker and the Emacs mailing-list:
https://bugs.archlinux.org/task/55838
https://lists.gnu.org/archive/html/bug-gnu-emacs/2017-09/msg00700.html
https://lists.gnu.org/archive/html/bug-gnu-emacs/2017-09/msg01089.html
https://lists.gnu.org/archive/html/bug-gnu-emacs/2017-09/msg01069.html

**Comment by Schnouki** [comment]
OK, I've made a mistake: reverting commit 870af5fe9befdb59f0533b12ffafd7b3b5a67e82 just after it was committed resulted in a bad build, but reverting it against a recent version of the ImageMagick-6 branch (commit e4fa0bd32) actually fixes everything for me.

So, would it be OK to submit a PR that reverts that commit?

**Comment by dlemstra** [comment]
I wonder why you would want to call terminus and then call initialize again. But I think we should set the boolean to false inside the terminus method. Could you submit a PR for both IM6 and IM7?

**Comment by dlemstra** [comment]
Dont revert the commit, just setting the boolean to false should resolve the issue.

**Comment by Schnouki** [comment]
Not sure why Emacs calls terminus and then initialize again, but I guess it's because since Emacs is not an image manipulation tool, it prefers to reset ImageMagick and free as much memory as possible when it does not need to handle images anymore, and then re-init it as needed.

Anyway, I confirm that setting the boolean to false in 6.9.9-17 solves the issue, so I'm going to submit a PR for IM6 and IM7.
