### ISSUE TITLE
Original sRGB profile is not correctly recognised as such by IM/libpng

### ISSUE THREAD

**Issue by paperboyo** [ImageMagick/ImageMagick#828]
Hello,

Thank you for all your hard work on this tool!

One of the most popular (if not – the most popular) version of the sRGB profile when present in PNG files (e.g. saved from within all Photoshop versions up to the latest one) prevents ImageMagick (7.0.7-5 Q16 x86_64; libpng 1.6.32) from working correctly. The same profile in e.g. JPEG files works fine.

Some specific examples (image attached, example of standard CMYK profile [here](http://www.ifra.com/WebSite/ifra.nsf/html/CONT_ISO_DOWNLOADS):
- `convert 40_EmbeddedRGB.png 40_EmbeddedRGB.icc` produces `convert: no color profile is available 40_EmbeddedRGB.icc' @ error/meta.c/WriteMETAImage/2407.` and no output.
- `convert 40_EmbeddedRGB.png -profile "ISOnewspaper26v4.icc" 40_EmbeddedRGB_to_ISONews.psd` produces an invalid RGB image with CMYK profile embedded (sic!)
- `convert 40_EmbeddedRGB.png test.png` produces a PNG without iCCP or sRGB chunks (but with gAMA and cHRM intact, sic!)

Adding `-define png:preserve-iccp` fixes the second problem, but doesn’t fix the first one and introduces its own complications.

AFAIK, this is caused by (a highly irresponsible, IMHO) decision to warn/disallow certain sRGB profiles by recent versions of libpng.

Description for `-define png:preserve-iccp` [states](https://www.imagemagick.org/script/command-line-options.php#define) (emphasis mine):

> There are some ICC profiles that claim to be sRGB but have various errors that cause them to be rejected by libpng16; **such profiles are recognized anyhow and converted to the sRGB chunk**, but are rejected if the -define png:preserve-iCCP is present. Note that not all "sRGB" ICC profiles are recognized yet; we will add them to the list as we encounter them.

It looks like this sRGB profile is not recognised as sRGB even though it’s the one that is bundled with Adobe apps and Windows OS. To error on it because it’s “known” to be “invalid” is like cutting all water supply to the city because one read about this water spring in a faraway land having purer water. Allegedly.

I don’ really have an opinion over whether this popular sRGB is really invalid or just “invalid”. I think it’s fine, [just fine](https://ninedegreesbelow.com/photography/srgb-profile-comparison.html). But, given its popularity, I find this question mostly irrelevant.

In my humblest of opinions, ImageMagick should treat this sRGB profile as... an sRGB profile.

Regards
m.

[40_EmbeddedRGB.png.zip](https://github.com/ImageMagick/ImageMagick/files/1356340/40_EmbeddedRGB.png.zip)

**Comment by paperboyo** [comment]
Maybe ImageMagick could do [this](https://github.com/lovell/sharp/issues/73#issuecomment-51317184) to avoid the check?

**Comment by urban-warrior** [comment]
Closing due to being stale.  We tried the command with the latest ImageMagick and libpng releases and no exceptions or warnings were thrown.
