### ISSUE TITLE
Bessel filter option works for v6.9.9-17 but not in v7.0.7-5

### ISSUE THREAD

**Issue by thetizzo** [ImageMagick/ImageMagick#829]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am using ImageMagick to process images for a Rails app and recently noticed some differences between developer machines that I tracked down to the ImageMagick version being used.

Using this command:
```bash
convert <path to some jpg> -auto-orient -resize "80x40" -filter Bessel -define filter:blur=0.5 -auto-orient -unsharp 0x0.75+0.75+0.008 <path to converted jpg>
```

On v6.9.9-17, this runs successfully.  On v7.0.7-5, I get this error: 
```bash
convert: unrecognized image filter `Bessel' @ error/convert.c/ConvertImageCommand/1623.
```

If I change the filter option name from `Bessel` to `Jinc` it run successfully on both versions.

Searching through the code, I found [this line of code](https://github.com/ImageMagick/ImageMagick/blob/7.0.7-5/MagickCore/resample.h#L76), which seems to indicate that Bessel and Jinc are actually the same filter type, but I am far from an expert in C++ or this code base. :)

I googled around and searched this repo for signs that the Bessel filter option was actually removed but couldn't find anything indicating that it was.

Here is an example image that I was using: 
![dfp](https://user-images.githubusercontent.com/709926/31206382-bbeebbd2-a934-11e7-870f-032b5c3a26a6.jpg)

### Steps to Reproduce
1) Install 6.9.9-17 
2) Run above command (see that it returns successfully)
3) Install 7.0.7-5
4) Run above command on the same image as in step 2, see error message output

### System Configuration

- ImageMagick version: 7.0.7-5
- Environment (Operating system, version and so on): macOS Sierra v10.12.6

**Comment by mikayla-grace** [comment]
The -filter Jinc works for IMv6 and IMv7.  Bessel was an alias for Jinc in IMv6 and remove before IMv7 was released.

**Comment by thetizzo** [comment]
Excellent, thanks!  Just wanted to make sure that was intentional and that I wasn't missing something. 👍 😄
