### ISSUE TITLE
7.0.7-5 failed tests with ghostscript-9.21 

### ISSUE THREAD

**Issue by premsompura** [ImageMagick/ImageMagick#830]
### Description

I am trying to build rpm of ImageMagick-7.0.7-5 and ghostscript-9.21.
I was able to built ghostscript-9.21 rpm package and installed it but when I tried to build IM-7.0.7-5 got errors in three test cases:
```
ERROR: tests/validate-formats-memory.tap - too few tests run (expected 1, got 0)
ERROR: tests/validate-formats-map.tap - too few tests run (expected 1, got 0)
ERROR: tests/validate-formats-disk.tap - too few tests run (expected 1, got 0)
```

[Here](https://pastebin.com/raw/nGrgsT76) is the test-suite.log file

### System Configuration

- ImageMagick version: 7.0.7-5
- GhostScript version: 9.21
- Environment (Operating system, version and so on): CentOS Linux release 7.3.1611 (Core)

**Comment by mikayla-grace** [comment]
We need to see how the unit tests failed before we can comment.  Edit tests/validate-formats-memory.log and look for the failure and post it here.  Once we know why the unit test failed,  we can post a remedy here.

**Comment by premsompura** [comment]
check [here](https://pastebin.com/raw/yEqskThB) for validate-formats-memory.log

**Comment by urban-warrior** [comment]
Do you have the default security policy?  Or do you have a custom security policy (policy.xml)?  If so, one of your security policies may preempt the unit tests.  If you have the default security policy we would need to see a stack trace to help further:

```
gdb .libs/validate
run -validate formats-memory
bt
```

Post the output after the 'bt' command here so we can trace the source of the abort.

**Comment by premsompura** [comment]
Here is the output as requested
```
#0  0x00007fffe296e47d in i_free_object () from /lib/libgs.so.9
#1  0x00007fffe26c1c53 in gs_jpeg_mem_term () from /lib/libgs.so.9
#2  0x00007fffe26c1cc1 in gs_jpeg_destroy () from /lib/libgs.so.9
#3  0x00007fffe288b6f4 in psdf_DCT_filter () from /lib/libgs.so.9
#4  0x00007fffe2885f81 in psdf_put_image_dict_param () from /lib/libgs.so.9
#5  0x00007fffe28864d2 in psdf_put_image_params.isra.7 () from /lib/libgs.so.9
#6  0x00007fffe2887a3c in gdev_psdf_put_params () from /lib/libgs.so.9
#7  0x00007fffe2876abf in gdev_pdf_put_params_impl () from /lib/libgs.so.9
#8  0x00007fffe2877fe2 in gdev_pdf_put_params () from /lib/libgs.so.9
#9  0x00007fffe2982741 in gs_putdeviceparams () from /lib/libgs.so.9
#10 0x00007fffe2ace24a in zputdeviceparams () from /lib/libgs.so.9
#11 0x00007fffe2aa03a1 in interp () from /lib/libgs.so.9
#12 0x00007fffe2aa0e3e in gs_interpret () from /lib/libgs.so.9
#13 0x00007fffe2a94a82 in gs_run_init_file () from /lib/libgs.so.9
#14 0x00007fffe2a94f8e in gs_main_init2aux () from /lib/libgs.so.9
#15 0x00007fffe2a95501 in gs_main_init2 () from /lib/libgs.so.9
#16 0x00007fffe2a96888 in runarg () from /lib/libgs.so.9
#17 0x00007fffe2a97012 in swproc () from /lib/libgs.so.9
#18 0x00007fffe2a98370 in gs_main_init_with_args () from /lib/libgs.so.9
#19 0x00007fffe40e6eb2 in ReadPDFImage () from /usr/lib64/ImageMagick-7.0.7/modules-Q16HDRI/coders/pdf.so
#20 0x00007ffff79a7cbf in ReadImage () from /lib64/libMagickCore-7.Q16HDRI.so.4
#21 0x00007ffff7ad0e49 in ReadStream () from /lib64/libMagickCore-7.Q16HDRI.so.4
#22 0x00007ffff79a77d3 in PingImage () from /lib64/libMagickCore-7.Q16HDRI.so.4
#23 0x0000000000403e90 in ValidateImageFormatsInMemory (image_info=image_info@entry=0x60f1d0, 
    reference_filename=reference_filename@entry=0x7fffffffc2b0 "/tmp/magick-46189Zncy4nGQohT", 
    output_filename=output_filename@entry=0x7fffffffb2b0 "/tmp/magick-4618Tjs4RLqAA4Z0", fail=fail@entry=0x7fffffffb2a0, 
    exception=exception@entry=0x60e250) at tests/validate.c:1648
#24 0x00000000004032ed in main (argc=<optimized out>, argv=<optimized out>) at tests/validate.c:2657
```

**Comment by urban-warrior** [comment]
The problem appears inside Ghostscript.  Notice the stack trace leads deep into the Ghostscript delegate library stack.  We're using Ghostscript 9.20 and the ImageMagick unit tests work without complaint.

**Comment by premsompura** [comment]
Can you provide ghostscript 9.20 rpm?

**Comment by urban-warrior** [comment]
We maintain ImageMagick, not Ghostscript.  We suggest you google.

**Comment by premsompura** [comment]
Can you please answer this question: Why the official rpm of IM depends on GS 9.04?

**Comment by urban-warrior** [comment]
ImageMagick is not dependent on any particular version of Ghostscript.  ImageMagick RPM releases are built on CentOS 7, we likely bind to whatever version of ImageMagick CentOS 7 provides.
