### ISSUE TITLE
Imagemagick generated image has black color background

### ISSUE THREAD

**Issue by DigneshGoyal** [ImageMagick/ImageMagick#833]
Hi,

I am trying to convert an PNG file to JPG using the ImageMagick. After conversion I see the background color is in black color.
I am using the below command to do the transformation

magick.exe png:renditionfile.png -intent relative -sample 1024x768> -quality 95 -colorspace sRGB -strip -auto-orient renditionfile-S.JPG

Below is version of Imagemagick i am using

C:\>magick -version
Version: ImageMagick 7.0.3-8 Q16 x64 2016-11-24 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib cairo flif freetype jng jp2 jpeg lcms lqr openexr pangocairo png ps rsvg tiff webp xml zlib

Below is the test file i am using
![renditionfile](https://user-images.githubusercontent.com/12810106/31434764-e960a7cc-ae9a-11e7-8c53-0f42798d3eb7.jpg)

Can anyone please help me on this.. I dont want the black color background to be generated .is there any extra setting that needs to be added ?

**Comment by DigneshGoyal** [comment]
![renditionfile](https://user-images.githubusercontent.com/12810106/31434742-d497e17a-ae9a-11e7-947f-719536d48465.jpg)

**Comment by urban-warrior** [comment]
The JPEG image format does not support transparency, PNG does.  Use this command instead:

`magick renditionfile.png -intent relative -resize 1024x768> -quality 95 -colorspace sRGB -strip -auto-orient background white -flatten renditionfile-S.JPG
