### ISSUE TITLE
Targa identification

### ISSUE THREAD

**Issue by TomMettam** [ImageMagick/ImageMagick#834]
ImageMagick appears to fail to correctly identify a TGA blob. In some cases, this is expected, since a targa file may not have any signature, however, many DO, and these are not detected.

Many tga images contain the signature "TRUEVISION-XFILE." near the end of the file. It would be immensely helpful if ImageMagick could detect this.

[MARBLES.zip](https://github.com/ImageMagick/ImageMagick/files/1378851/MARBLES.zip)

**Comment by mikayla-grace** [comment]
The current release of ImageMagick, version 6.9.9-19, recognizes your TGA image.

**Comment by TomMettam** [comment]
From blob?  It recognises it when given the file extension, but not when just given a blob of binary data

**Comment by mikayla-grace** [comment]
Got it.  For performance / efficiency, ImageMagick only looks at the first 2048 bytes for a unique image signature.  Some newer TGA files include a signature but its @ the end of the image file.  So, no we will not be able to detect TGA from an image blob without a hint.  Your code could detect the blob is TGA and add that to the ImageInfo structure (member magick) and then ReanImage() will then know its a TGA blob.

**Comment by TomMettam** [comment]
Would it not be appropriate to do a more exhaustive search as a last resort? i.e if no format can be detected

**Comment by mikayla-grace** [comment]
Almost all image formats have a unique signature within the first hundred bytes of the image format.  The exception is TGA where the signature is at the end of the file, likely an afterthought.  We're not interested in  supporting this one off image format.  However, as mentioned, the user can perform this check themselves and add a hint to the ImageInfo structure and ReadImage() will then recognize the TGA blob.
