### ISSUE TITLE
Use of uninitialized data reading BMP files using ImageMagick-6.9.9-19

### ISSUE THREAD

**Issue by freddy77** [ImageMagick/ImageMagick#835]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Trying to run compare utility on some images I'm getting not consistent results. This seems to be triggered by not initialized data usage. Valgrind seems to confirm this

### Steps to Reproduce
The command I'm trying is
`compare -metric AE in.png out.bmp /dev/null`

### System Configuration
- ImageMagick version: 6.9.9-19
- Environment (Operating system, version and so on): Linux Fedora 26 x64
- Additional information: compiled last 6 sources

**Comment by freddy77** [comment]
[test2.zip](https://github.com/ImageMagick/ImageMagick/files/1379454/test2.zip)
test images and valgrind output of the issue

**Comment by mikayla-grace** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by freddy77** [comment]
Downloaded beta version (2017-10-12), I cannot find the issue anymore.
