### ISSUE TITLE
Missing comma after delay in json for gif files

### ISSUE THREAD

**Issue by regedarek** [ImageMagick/ImageMagick#837]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Missing comma returns invalid json for gif images.

### Steps to Reproduce
```convert path/to/image.gif json:```

### System Configuration
docker with debian:jessy 

- ImageMagick version: latest
- Environment (Operating system, version and so on): linux

I created PR: https://github.com/ImageMagick/ImageMagick/pull/836

**Comment by urban-warrior** [comment]
We applied your PR.  Thanks.
