### ISSUE TITLE
Animated gif frames overlapping after running Convert with LZW command

### ISSUE THREAD

**Issue by devedse** [ImageMagick/ImageMagick#838]
### Prerequisites

- [X] I have written a descriptive issue title
- [<Almost, I'm using 7.0.7-6>] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Currently I'm working a lot on optimizing images using FileOptimizerFull which will optimize images without any loss in quality (lossless): https://encode.ru/threads/1589-FileOptimizer

However what I have noticed is that some gif images are not optimized correctly, the frames are sometimes overlapping. After diving a bit in the source code I extracted the command that caused this issue:
`magick.exe convert -quiet -compress LZW -layers optimize Source.gif Result.gif`

So either this command won't do lossless optimizations which both me and the writer of FullFileOptimizer are unaware of, or there might be an issue in ImageMagick where it combines frames accidently.

Source Image:
![source](https://user-images.githubusercontent.com/2350015/31522150-b4c57232-afac-11e7-8909-13daa29ab6e1.gif)

Result Image:
![final](https://user-images.githubusercontent.com/2350015/31522159-baea5c7c-afac-11e7-87a6-020fb11f2053.gif)

### Steps to Reproduce
Download the Source Image and run it with the command as stated above. The resulting image will have all frames overlapping.

### System Configuration

- ImageMagick version: ImageMagick 7.0.7-6 Q16 x64 2017-10-04 http://www.imagemagick.org
- Environment (Operating system, version and so on): Windows 10, 64-bit
- Additional information: I also included the .gif files as zip:
[GifInvest.zip](https://github.com/ImageMagick/ImageMagick/files/1380896/GifInvest.zip)

**Comment by urban-warrior** [comment]
We can confirm the problem you reported.  We currently do not have an ETA on a patch to fix the problem.

**Comment by antofthy** [comment]
I have been asked to look into it and I confirm a problem in ImageMagick. I am the author of IM Examples, and specifically the [GIF animation processing example pages](https://www.imagemagick.org/Usage/anim_basics/)...

Note the command you are using is not correct, and relies on [Legacy Option Handling](https://www.imagemagick.org/Usage/basics/#legacy).  The options are order dependant and processed in that order. You should read the image first, then process using the options before outputting the image...
`convert  Source.gif -layers optimize -compress LZW Result.gif`


**As for the problem** it seems IM is not recognising the "Background", and is failing to preserve the "loop" attribute of the source image.  I have reported this to the main developer.

As a workaround you can force IM to use background disposal and re-set the loop.
`convert  Source.gif -set dispose background -layers optimize -compress -loop 0 LZW Result.gif`

A good way of seeing the attributes of a GIF Animation, and the options IM should be using you can use
`gif2anim -L`  See http://www.imagemagick.org/Usage/anim_basics/#list_info

Anthony Thyssen <A.Thyssen@griffith.edu.au>

**Comment by devedse** [comment]
Thanks for your information, what would be the "non legacy" way to execute this command?

**Comment by antofthy** [comment]
The non-legacy is basically read the image first, then optimise it,  then give the settings you want for the save (compression) and save the image (final option which is 'assumed' to be a -write operation).  I give the command above just below that part.   See the link which explains it.

And no forcing the disposal to background will not work for all images, it is just correcting what IM got wrong when reading this image. Same for the -loop option.  Both of these should be handled automatically, but is failing.  The main developer has said he will fix the issue when he gets back from his vacation.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow. 

ImageMagick defaults to a loop of 1 when writing a Gif image sequence unless a GIF extension sets it otherwise.  Your image has the loop defined for frames 1-4 but not for frame 0.  Download the latest source from Git and try this command:

```
convert Source.gif -loop 0  Result.gif
```

**Comment by devedse** [comment]
I'll try and run that command when the latest beta has been released :smile:.

**Comment by devedse** [comment]
Is there already a new version of ImageMagick released? I downloaded the version from 17-10-2017 and the issue wasn't yet resolved.

**Comment by devedse** [comment]
Ah with the latest version and the following command it now works:

`magick.exe convert Source.gif -layers optimize -compress LZW Result.gif`
