### ISSUE TITLE
Misuse of Macro `ThrowWriterException` in WriteOnePNGImage would cause Null Pointer Dereference

### ISSUE THREAD

**Issue by viennadd** [ImageMagick/ImageMagick#839]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Our code scanner has reported a potential null pointer dereference in png.c, when memory allocation failed in `CloneImageInfo`,
https://github.com/ImageMagick/ImageMagick/blob/cf4bb148f7c39d20e6843c2eba24d406580335f4/coders/png.c#L8417-L8419

Macro `ThrowWriterException` will use the NULL image_info (line 86), it could cause process crash.
https://github.com/ImageMagick/ImageMagick/blob/cf4bb148f7c39d20e6843c2eba24d406580335f4/MagickCore/exception-private.h#L82-L91

### Steps to Reproduce
```cpp
  image_info=(ImageInfo *) CloneImageInfo(IMimage_info);
  image_info=NULL;   // explicitly add NULL value here to mimic memory allocation failure, it will just crashed instead of throwing exception.
  if (image_info == (ImageInfo *) NULL)
    ThrowWriterException(ResourceLimitError, "MemoryAllocationFailed");

```

### System Configuration

- ImageMagick version: master branch (commit cf4bb148f7c39d20e6843c2eba24d406580335f4)
- Environment (Operating system, version and so on):
- Additional information:

Regards,
Alex, SourceBrella Inc.

**Comment by urban-warrior** [comment]
CloneImageInfo() cannot fail.  It calls AcquireImageInfo() and returns a NULL if AcquireImageInfo() fails to allocate an ImageInfo structure, however, AcquireImageInfo() returns a fatal exception and exits the calling application if memory cannot be allocated.

**Comment by viennadd** [comment]
I see, @urban-warrior I had missed the internal null handling of `AcquireImageInfo`, thank you for your concern.
