### ISSUE TITLE
Add support for writing RLE/ZIP compressed layers in the PSD writer.

### ISSUE THREAD

**Issue by dlemstra** [ImageMagick/ImageMagick#84]
Add support for writing RLE/ZIP compressed layers in the PSD writer. 

http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=29000

**Comment by thirdknife** [comment]
+1

**Comment by huyi7** [comment]
+1

**Comment by dlemstra** [comment]
RLE compression of layers has been added to IM7. I will add this to IM6 this weekend and I hope I will be able to start with ZIP compression soon.

**Comment by dlemstra** [comment]
Support for ZIP compressed layers has been added and will be available in IM 7.0.3-5 (or 6.9.6-3 if you are still using IM6).
