### ISSUE TITLE
ImageMagick is becoming nauseating, perverse, obnoxious and even repulsive

### ISSUE THREAD

**Issue by bdheeman** [ImageMagick/ImageMagick#841]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Day by day the ImageMagick is becoming nauseating, perverse, obnoxious and even repulsive :-(

### Steps to Reproduce

_Machine 1:_

<pre><code>[bdheeman@mon:tests]$ convert -version
Version: ImageMagick 6.8.6-10 2013-09-19 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2013 ImageMagick Studio LLC
Features: DPC
Delegates: bzlib cairo djvu fftw fontconfig freetype jng jp2 jpeg lcms lzma openexr pango pangocairo png png rsvg tiff x xml zlib

[bdheeman@mon:tests]$ ls -l test.svg
-rw-r--r-- 1 bdheeman bdheeman 36125 Oct 13 00:42 test.svg

[bdheeman@mon:tests]$ convert test.svg test_none.pdf
[bdheeman@mon:tests]$ ls -l test_none.pdf
-rw-r--r-- 1 bdheeman bdheeman 116487 Oct 15 22:23 test_none.pdf

[bdheeman@mon:tests]$ convert test.svg -compress JPEG test_jpeg.pdf
[bdheeman@mon:tests]$ ls -l test_jpeg.pdf
-rw-r--r-- 1 bdheeman bdheeman 153586 Oct 15 22:23 test_jpeg.pdf

[bdheeman@mon:tests]$ convert test.svg -encoding JPX -compress JPEG test_jpx.pdf
[bdheeman@mon:tests]$ ls -l test_jpx.pdf
-rw-r--r-- 1 bdheeman bdheeman 153585 Oct 15 22:23 test_jpx.pdf

[bdheeman@mon:tests]$ convert test.svg -encoding JPX -compress JPEG2000 test_jp2.pdf
[bdheeman@mon:tests]$ ls -l test_jp2.pdf
-rw-r--r-- 1 bdheeman bdheeman 378132 Oct 15 22:23 test_jp2.pdf

[bdheeman@mon:tests]$ pdfimages test_none.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     765  1215  rgb     3   8  image  no         8  0    90    90  105K 3.8%
   1     1 smask     765  1215  gray    1   8  image  no         8  0    90    90  924B 0.1%
[bdheeman@mon:tests]$ pdfimages test_jpeg.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     765  1215  rgb     3   8  jpeg   no         8  0    90    90  131K 4.8%
   1     1 smask     765  1215  gray    1   8  image  no         8  0    90    90 14.3K 1.6%
[bdheeman@mon:tests]$ pdfimages test_jpx.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     765  1215  rgb     3   8  jpeg   no         8  0    90    90  131K 4.8%
   1     1 smask     765  1215  gray    1   8  image  no         8  0    90    90 14.3K 1.6%
[bdheeman@mon:tests]$ pdfimages test_jp2.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     765  1215  rgb     3   8  jpx    no         8  0    90    90  343K  13%
   1     1 smask     765  1215  gray    1   8  image  no         8  0    90    90 14.3K 1.6%</code></pre>

_Machine 2:_

<pre><code>[bdheeman@noc:tests]$ convert -version
Version: ImageMagick 6.9.9-19 Q16 i686 2017-10-07 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenCL OpenMP 
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps rsvg tiff webp wmf x xml zlib

[bdheeman@noc:tests]$ ls -l test.svg
-rw-r--r-- 1 bdheeman bdheeman 36125 Oct 13 00:42 test.svg

[bdheeman@noc:tests]$ convert test.svg test_none.pdf
[bdheeman@noc:tests]$ ls -l test_none.pdf
-rw-r--r-- 1 bdheeman bdheeman 116797 Oct 15 23:24 test_none.pdf

[bdheeman@noc:tests]$ convert test.svg -compress JPEG test_jpeg.pdf
[bdheeman@noc:tests]$ ls -l test_jpeg.pdf
-rw-r--r-- 1 bdheeman bdheeman 203256 Oct 15 23:24 test_jpeg.pdf

[bdheeman@noc:tests]$ convert test.svg -encoding JPX -compress JPEG test_jpx.pdf
[bdheeman@noc:tests]$ ls -l test_jpx.pdf
-rw-r--r-- 1 bdheeman bdheeman 203254 Oct 15 23:24 test_jpx.pdf

[bdheeman@noc:tests]$ convert test.svg -encoding JPX -compress JPEG2000 test_jp2.pdf
[bdheeman@noc:tests]$ ls -l test_jp2.pdf
-rw-r--r-- 1 bdheeman bdheeman 377368 Oct 15 23:24 test_jp2.pdf

[bdheeman@noc:tests]$ pdfimages test_none.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     765  1215  rgb     3   8  image  no         8  0    97    97  105K 3.9%
   1     1 smask     765  1215  gray    1   8  image  no         8  0    97    97  924B 0.1%
[bdheeman@noc:tests]$ pdfimages test_jpeg.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     765  1215  rgb     3   8  jpeg   no         8  0    97    97  178K 6.5%
   1     1 smask     765  1215  gray    1   8  image  no         8  0    97    97 14.3K 1.6%
[bdheeman@noc:tests]$ pdfimages test_jpx.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     765  1215  rgb     3   8  jpeg   no         8  0    97    97  178K 6.5%
   1     1 smask     765  1215  gray    1   8  image  no         8  0    97    97 14.3K 1.6%
[bdheeman@noc:tests]$ pdfimages test_jp2.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     765  1215  rgb     3   8  jpx    no         8  0    97    97  342K  13%
   1     1 smask     765  1215  gray    1   8  image  no         8  0    97    97 14.3K 1.6%</code></pre>

_Machine 3:_

<pre><code>[bdheeman@sun:tests]$ convert -version
Version: ImageMagick 7.0.7-7 Q16 i486 2017-10-16 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): bzlib djvu fontconfig freetype jng jp2 jpeg lcms lzma openexr pangocairo png tiff webp x xml zlib

[bdheeman@sun:tests]$ ls -l test.svg
-rw-r--r-- 1 bdheeman bdheeman 36125 Oct 13 00:42 test.svg

[bdheeman@sun:tests]$ convert test.svg test_none.pdf
[bdheeman@sun:tests]$ ls -l test_none.pdf
-rw-r--r-- 1 bdheeman bdheeman 2822695 Oct 16 11:56 test_none.pdf

[bdheeman@sun:tests]$ convert test.svg -compress JPEG test_jpeg.pdf
[bdheeman@sun:tests]$ ls -l test_jpeg.pdf
-rw-r--r-- 1 bdheeman bdheeman 239618 Oct 16 11:56 test_jpeg.pdf

[bdheeman@sun:tests]$ convert test.svg -encoding JPX -compress JPEG test_jpx.pdf
[bdheeman@sun:tests]$ ls -l test_jpx.pdf
-rw-r--r-- 1 bdheeman bdheeman 239616 Oct 16 11:56 test_jpx.pdf

[bdheeman@sun:tests]$ convert test.svg -encoding JPX -compress JPEG2000 test_jp2.pdf
[bdheeman@sun:tests]$ ls -l test_jp2.pdf
-rw-r--r-- 1 bdheeman bdheeman 999236 Oct 16 11:56 test_jp2.pdf

[bdheeman@sun:tests]$ pdfimages test_none.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     765  1215  rgb     3   8  image  no         8  0    72    72 2719K 100%
   1     1 smask     765  1215  gray    1   8  image  no         8  0    72    72 14.3K 1.6%
[bdheeman@sun:tests]$ pdfimages test_jpeg.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     765  1215  rgb     3   8  jpeg   no         8  0    72    72  214K 7.8%
   1     1 smask     765  1215  gray    1   8  image  no         8  0    72    72 14.3K 1.6%
[bdheeman@sun:tests]$ pdfimages test_jpx.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     765  1215  rgb     3   8  jpeg   no         8  0    72    72  214K 7.8%
   1     1 smask     765  1215  gray    1   8  image  no         8  0    72    72 14.3K 1.6%
[bdheeman@sun:tests]$ pdfimages test_jp2.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     765  1215  rgb     3   8  jpx    no         8  0    72    72  949K  35%
   1     1 smask     765  1215  gray    1   8  image  no         8  0    72    72 14.3K 1.6%</code></pre>

### System Configuration

- ImageMagick version: See in the steps
- Environment (Operating system, version and so on): See in the steps
- Additional information:
  **Look at how the file sizes grow with newer IM versions of output files for the same source file, an SVG created using InkScape.**

  **The versions on machine 2 and 3 failed to find density and, or dpi from SVG file, while only version on machine 1 produced an exact or expected page size, -page whatever is ignored.**

  **Last, but not the least, why the hell IM adds a space after %PDF-1.x?, wasting a byte is not that very costly today, but doing such illogical things and, or mistakes is not acceptable to mind**

**Comment by urban-warrior** [comment]
ImageMagick has three different SVG renders, internal, libRSVG, and inkscape.  Each has different compliance issues with the SVG standard and consequently can produce different results.  On top of that we dealing with different versions of each of these libraries.  To get optimal results, use a modern release of ImageMagick, we recommend 7.0.7-8, and inkscape.  Now produce your your PDF from SVG.   If you are still not satisfied with the results, post here with your command-line, input image, output image, and a description of how you think the results are not optimal.  We'll investigate and see if we can improve ImageMagick to meet your expectations, if possible.

**Comment by bdheeman** [comment]
### Results improved after rebuilding and with Inkscape

@urban-warrior, Thanks a lot for your respose :-) 

Well, the output is better after rebuild of IM (**7.0.7-7, latest available release as per github tags, huh**) now, but not optimal as yet.

Though, I successfully added support for cairo, gslib, lqr, ltdl (libtool), ps, rsvg and wmf etc., but I couldn't find how do I add OpenCL functionality/features.

I think, it was especially InkScape which did the trick this time, the rebuilding seems to has nothing to do with SVG rendering and, or quality of output PDF files, otherwise ^_^

It's notable (when I'm converting SVG designs, cover/back-cover pages for e-books/books, here):

 - that, the Inkscape also has functionality for export to PDF format, but not any better than ImageMagick-6/7 ;-)
 - that, the a change in default DPI Inkscape version 0.92.x, (mine is current i.e. 0.92.2, with IM 7) was also causing problem and producing a wrong page size. _Which I fixed using -density 35.43307086 (90/2.54, either the units must be in centimeters or we need to try -units PixelsPerInch -density 90 ...)_. How did I figured it out is not long a story, though.
 - that, the Leptonica can also convert most of image formats to PDF files, but not the SVG files, though produces a better quality and is also efficient than IM :-P

**I attempted to search, but could not find that how do we ask IM to list available PDF renders and direct it to use a particular render for our case or SVG conversion?**

FYI, here are the latest results:

<pre><code>[bdheeman@sun:tests]$ convert -version
Version: ImageMagick 7.0.7-7 Q16 i486 2017-10-18 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP 
Delegates (built-in): bzlib cairo fontconfig freetype gslib jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png ps rsvg tiff webp wmf x xml zlib

[bdheeman@sun:tests]$ ls -l test.svg
-rw-r--r-- 1 bdheeman bdheeman 36125 Oct 13 00:42 test.svg

[bdheeman@sun:tests]$ convert test.svg test_none.pdf
[bdheeman@sun:tests]$ ls -l test_none.pdf
-rw-r--r-- 1 bdheeman bdheeman 124512 Oct 18 03:00 test_none.pdf

[bdheeman@sun:tests]$ convert test.svg -compress JPEG test_jpeg.pdf
[bdheeman@sun:tests]$ ls -l test_jpeg.pdf
-rw-r--r-- 1 bdheeman bdheeman 223685 Oct 18 03:00 test_jpeg.pdf

[bdheeman@sun:tests]$ convert test.svg -encoding JPX -compress JPEG test_jpx.pdf
[bdheeman@sun:tests]$ ls -l test_jpx.pdf
-rw-r--r-- 1 bdheeman bdheeman 223683 Oct 18 03:00 test_jpx.pdf

[bdheeman@sun:tests]$ convert test.svg -encoding JPX -compress JPEG2000 test_jp2.pdf
[bdheeman@sun:tests]$ ls -l test_jp2.pdf
-rw-r--r-- 1 bdheeman bdheeman 403758 Oct 18 03:00 test_jp2.pdf

[bdheeman@sun:tests]$ pdfimages test_none.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     816  1296  rgb     3   8  image  no         8  0    97    97  113K 3.6%
   1     1 smask     816  1296  gray    1   8  image  no         8  0    97    97 1047B 0.1%
[bdheeman@sun:tests]$ pdfimages test_jpeg.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     816  1296  rgb     3   8  jpeg   no         8  0    97    97  196K 6.3%
   1     1 smask     816  1296  gray    1   8  image  no         8  0    97    97 16.3K 1.6%
[bdheeman@sun:tests]$ pdfimages test_jpx.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     816  1296  rgb     3   8  jpeg   no         8  0    97    97  196K 6.3%
   1     1 smask     816  1296  gray    1   8  image  no         8  0    97    97 16.3K 1.6%
[bdheeman@sun:tests]$ pdfimages test_jp2.pdf -list
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image     816  1296  rgb     3   8  jpx    no         8  0    97    97  366K  12%
   1     1 smask     816  1296  gray    1   8  image  no         8  0    97    97 16.3K 1.6%</code></pre>

It's not only strange that I'm struggling to do such a simple task, but has become quiet boring and distressing after software upgrades. Hence, I, indeed, was forced to locally build latest versions of tools involved, but to a no avail or an overkill and waste of time, eventually.

**Comment by bdheeman** [comment]
Closed? but why?
