### ISSUE TITLE
Downstream A JSON::ParserError occurred while parsing broken JSON (UTF-8)

### ISSUE THREAD

**Issue by PeterMozesMerl** [ImageMagick/ImageMagick#848]
Would you please look at it?

https://github.com/minimagick/minimagick/issues/423#issuecomment-328806401

### Prerequisites

- A broken jpeg file that can be displayed in browsers and opened in image editing applications
- ImageMagick
- Ruby
- MiniMagick gem

### Description
Invalid UTF-8 sequence in the image metadata prevents the JSON parser from working

### Steps to Reproduce
Open the broken image file with MiniMagick and try to access the image.data

### System Configuration
Version: ImageMagick 6.9.9-19 Q16 x86_64 2017-10-12 http://www.imagemagick.org

mini_magick (4.8.0)

ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]

MacOS and FreeBSD (and probably the rest)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
