### ISSUE TITLE
avs signature changed

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#849]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
avs signature testcase changed after bb11d07139efe0f5e4ce0e4afda32abdbe82fa9d

### Steps to Reproduce

`test.pl`
```
use Image::Magick;
use lib 't';
require 'subroutines.pl';
testReadWrite( 'AVS:t/input.avs',
  'AVS:t/output.avs',
  q//,
  'f7b3db46d6f696ea8392f0ad0be945dd502a806e2c1e9c082efef517191758f7');
```

BEFORE

```
$ perl test.pl
ok 
$
```

AFTER

```
$ perl test.pl
ReadImage()
Image: AVS:t/input.avs, signatures do not match.
     Expected: f7b3db46d6f696ea8392f0ad0be945dd502a806e2c1e9c082efef517191758f7
     Computed: 646ac633d5b5553721e032d2c9f8f54ffc19d315832bbf808c2b7321b1067293
     Depth:    16
not ok 
$
```

### System Configuration

- ImageMagick version: 7.0.7-9
- Environment (Operating system, version and so on): linux

**Comment by urban-warrior** [comment]
We fixed a bug in the AVS coder in ImageMagick 7.0.7-9.  Previously, the alpha channel was only enabled if a non-opaque pixel was located.  This is incorrect.  AVS *always* has an alpha channel.  When we enabled the alpha channel with the patch, naturally the image signature changed.
