### ISSUE TITLE
Parsing comments in pnm fails

### ISSUE THREAD

**Issue by HeroicKatora** [ImageMagick/ImageMagick#850]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Comments inside pnm headers are not parsed correctly. This might not only corrupt images but also allows one to craft images which are reported as tiny by `pamfile` from `netpbm` while requiring several gigabytes to analyze with ImageMagick.

The reason behind this is the way comments are handled by ImageMagick. Comments should start at `#` and end at the next `\r` or `\n`. They should not terminate header content such as width or height and can appear within such tokens. Those are separated by whitespace, '\x09' - '\x0d' and ' ', and exactly one whitespace character will appear after the header.

The parser built into ImageMagick has a bunch of shortcomings:
 1. Comments can only be terminated by `\n`.
 2. Reading a number will ignore the character immediately following it.
 3. Parsing numbers can terminate early when the number gets too large while in theory it should continue until the next whitespace.
 4. Comments should not end tokens such as numbers or the header but due to 2. a comment after the header will be silently included within the data section.

The last failure would make it possible to create a pnm that is valid in both programs but appears to hold two different images depending on the utility used to view it. Failure (3) could lead to problems on systems with configurations where the allowed maximum size exceeds `MAX_INT/10`. On these, a number parse could break in the middle of a number while still producing valid image heights and widths with specific images. The consequences on this were not evaluated any further.

### Steps to Reproduce
A malicious file can be produced with
`printf "P5 #\r1 1 1 1\n 107374181# 1 16777215 "`

Feeding this to `pamfile` produces the (per specification) correct output:
`stdin:	PGM raw, 1 by 1  maxval 1`

Meanwhile `identify` will try to allocate more than 10 gigabytes of memory on my machine before reporting this image as corrupt. This is because the genuine pnm representation should be `P5 1 1 1 1` but ImageMagick interprets it as `P5  107374181 1 16777215 `.

### System Configuration

- ImageMagick version: `ImageMagick 6.9.9-21 Q16 x86_64 2017-10-31`
- Environment (Operating system, version and so on): `4.13.9-1-ARCH`
- Additional information: Netpbm 10.73.00

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow. 

ImageMagick best practices strongly encourages you to configure a security policy that suits your local environment.  See https://www.imagemagick.org/script/security-policy.php.
