### ISSUE TITLE
make check reports two fails

### ISSUE THREAD

**Issue by peter-cambridge** [ImageMagick/ImageMagick#852]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Makefile:11012: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/home/ubuntu/peter/ImageMagick-7.0.7-9'
Makefile:11118: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/home/ubuntu/peter/ImageMagick-7.0.7-9'
Makefile:11330: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/home/ubuntu/peter/ImageMagick-7.0.7-9'
Makefile:11333: recipe for target 'check' failed
make: *** [check] Error 2
ubuntu@ubuntu:~/peter/ImageMagick-7.0.7-9$

### Steps to Reproduce
The simple steps in https://www.imagemagick.org/script/install-source.php#unix
./configure
make
sudo make install
make check 

### System Configuration
ubuntu@ubuntu:~/peter/ImageMagick-7.0.7-9$ uname -a
Linux ubuntu 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- ImageMagick version: 7.0.7-9, the latest
- Environment (Operating system, version and so on): Ubuntu 4.4.0-96
- Additional information:

I'm not an expert of imagemagick. Any comments/help would be appreciated.

**Comment by urban-warrior** [comment]
Check test-suite.log.  It should tell you which tests failed.  Take a look at the log for the test, something like tests/validate-convert.log for example, and identify which test failed.  We need to localize which unit test failed before we can help.  Note, that some dependencies may be required for the units tests to succeed.  Ghostscript must be installed, for example.  We did try the unit tests under Ubuntu 3.13.0-61-generic and they all passed without complaint.

**Comment by peter-cambridge** [comment]
Hello urban-warrior,

Thanks for the directions. Below are some copy-and-paste of the test-suite.log, which looks providing some clues. If you could give some more directions, that would be awesome!

Thank you,

peter

 

FAIL: tests/wandtest
====================

lt-wandtest: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1797.
lt-wandtest: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/509.
lt-wandtest: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1797.
lt-wandtest: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/509.
tests/wandtest.c main 5321 non-conforming drawing primitive definition `text' @ error/draw.c/DrawImage/3287
1..1
Reading images...
Iterate forward...
index 0 scene 0
index 1 scene 1
index 2 scene 2
index 3 scene 3
index 4 scene 4
Iterate reverse...
index 4 scene 4
index 3 scene 3
index 2 scene 2
index 1 scene 1
index 0 scene 0
Remove scene 1...
index 0 scene 0
index 1 scene 2
index 2 scene 3
index 3 scene 4
Insert scene 1 back in sequence...
index 0 scene 0
index 1 scene 1
index 2 scene 2
index 3 scene 3
index 4 scene 4
Set scene 2 to scene 1...
index 0 scene 0
index 1 scene 1
index 2 scene 1
index 3 scene 3
index 4 scene 4
Apply image processing options...
not ok
FAIL: tests/wandtest.tap 1

FAIL: Magick++/demo/demos.tap 6

Also, these two lines repeat many times in the test-suite.log.
lt-shapes: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n019003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1797.
lt-shapes: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/509.

**Comment by urban-warrior** [comment]
Install the Freetype delegate library on your system.  Its needed to render fonts properly for the unit tests to pass.  Run the ImageMagick configure script again and review the final 50 lines of output looking for the Freetype library and whether it was found or not.  If so, rebuild ImageMagick and try the unit tests again.  They should work.  The unit tests must pass for us on several OS's before we release ImageMagick.

**Comment by peter-cambridge** [comment]
Freetype libraries are installed.
(sudo apt install freetype2-demos)

'make check' still reports the two same failures after re-configuring, make, and make install.
The last lines of configure is below.
Could you take a look and give some advice?
Sorry for asking many naive questions. I'm just a beginner.
I ran ./configure --enable-opencl=yes --with-modules=yes --with-freetype=yes

Thank you.

==============================================================================
ImageMagick is configured as follows. Please verify that this configuration
matches your expectations.

  Host system type: x86_64-pc-linux-gnu
  Build system type: x86_64-pc-linux-gnu

                 Option                        Value
  ------------------------------------------------------------------------------
  Shared libraries  --enable-shared=yes     yes
  Static libraries  --enable-static=yes     yes
  Module support    --with-modules=yes      yes
  GNU ld            --with-gnu-ld=yes       yes
  Quantum depth     --with-quantum-depth=16 16
  High Dynamic Range Imagery
                    --enable-hdri=yes       yes

  Install documentation:            yes

  Delegate Library Configuration:
  BZLIB             --with-bzlib=yes        no
  Autotrace         --with-autotrace=no     no
  DJVU              --with-djvu=yes     no
  DPS               --with-dps=yes      no
  FFTW              --with-fftw=yes     no
  FLIF              --with-flif=yes     no
  FlashPIX          --with-fpx=yes      no
  FontConfig        --with-fontconfig=yes   no
  FreeType          --with-freetype=yes     no
  Ghostscript lib   --with-gslib=no     no
  Graphviz          --with-gvc=yes      no
  JBIG              --with-jbig=yes     no
  JPEG v1           --with-jpeg=yes     no
  LCMS              --with-lcms=yes     no
  LQR               --with-lqr=yes      no
  LTDL              --with-ltdl=yes     yes
  LZMA              --with-lzma=yes     no
  Magick++          --with-magick-plus-plus=yes yes
  OpenEXR           --with-openexr=yes      no
  OpenJP2           --with-openjp2=yes      no
  PANGO             --with-pango=yes        no
  PERL              --with-perl=no      no
  PERL              --with-perl=no      no
  PNG               --with-png=yes      no
  RAQM              --with-raqm=yes     no
  RAW               --with-raw=yes      no
  RSVG              --with-rsvg=no      no
  TIFF              --with-tiff=yes     no
  WEBP              --with-webp=yes     no
  WMF               --with-wmf=yes      no
  X11               --with-x=           yes
  XML               --with-xml=yes      no
  ZLIB              --with-zlib=yes     no

  Delegate Program Configuration:
  GhostPCL          None                pcl6 (unknown)
  GhostXPS          None                gxps (unknown)
  Ghostscript       None                gs (unknown)

  Font Configuration:
  Apple fonts       --with-apple-font-dir=default
  Dejavu fonts      --with-dejavu-font-dir=default  none
  Ghostscript fonts --with-gs-font-dir=default  none
  URW-base35 fonts  --with-urw-base35-font-dir=default
  Windows fonts     --with-windows-font-dir=default none

  X11 Configuration:
        X_CFLAGS        =
        X_PRE_LIBS      =
        X_LIBS          =
        X_EXTRA_LIBS    =

  Options used to compile and link:
    PREFIX          = /usr/local
    EXEC-PREFIX     = /usr/local
    VERSION         = 7.0.7
    CC              = gcc
    CFLAGS          = -pthread -fopenmp -g -O2 -Wall -mtune=core2 -fexceptions -pthread -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
    CPPFLAGS        = -pthread  -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16
    PCFLAGS         =
    DEFS            = -DHAVE_CONFIG_H
    LDFLAGS         =
    LIBS            =
    CXX             = g++
    CXXFLAGS        = -g -O2 -pthread
    FEATURES        = DPC HDRI Cipher OpenCL OpenMP Modules
    DELEGATES       = mpeg x
==============================================================================

**Comment by jackluo2012** [comment]
ERROR_MISSING_DELEGATE: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/509

**Comment by daavve** [comment]
ImageMagick-7.0.7 has 5 failures on my ArchLinux box.

https://pastebin.com/raw/2hWQNE13

**Comment by jackluo2012** [comment]
@daavve 
try it 
`FROM golang
MAINTAINER  jackluo

RUN apt-get update && apt-get install -y --no-install-recommends libwebp-dev libjpeg-dev libpng-dev wget freetype2-demos libfreetype6-dev libfreetype6

RUN wget https://www.imagemagick.org/download/ImageMagick.tar.gz && \
    tar xvzf ImageMagick.tar.gz && \
    rm ImageMagick.tar.gz && \
    cd ImageMagick-7.0.7-12 && \
    ./configure && \
    make -j4 && \
    make install && \
    ldconfig /usr/local/lib && \
    cd .. && rm -rf ImageMagick-7.0.7-12`

**Comment by daavve** [comment]
Thank you @jackluo2012, I have no trouble installing ImageMMagick if I omit the "make check" phase.  When "make check" encounters failures it requests I report the failures here.  I am attempting to follow those directions.
Here is my test-suite.  It contains 5 failures:

https://pastebin.com/raw/yYWZ3PS6


-Dave

**Comment by smiletobingxue** [comment]
I still have the problems after trying all the solutions above, anyone can give some useful suggestions? Thx

**Comment by daavve** [comment]
Just upgraded to ImageMagick 7.0.7.  All tests now pass!

-Dave

**Comment by daavve** [comment]
[ImageMagick 7.0.7-25]: FAIL: Magick++/tests/tests.tap 5

[test-suite.log](https://github.com/ImageMagick/ImageMagick/files/1799192/test-suite.log)

**Comment by daavve** [comment]
[ImageMagick 7.0.7-26]  All tests pass for me.
