### ISSUE TITLE
Alpine Linux make test fails with v7.0.7.10

### ISSUE THREAD

**Issue by TBK** [ImageMagick/ImageMagick#856]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

7 tests fails when executing `make check` on Alpine Linux.

I have attached the [test-suite.log](https://github.com/ImageMagick/ImageMagick/files/1456090/test-suite.log)

### Steps to Reproduce

- Setup Alpine Linux host (https://wiki.alpinelinux.org/wiki/Installation)
- Configure build enviroment (https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package#Setup_your_system_and_account)
- git clone https://github.com/tbk/aports
- git checkout imagemagick
- cd ~/aports/main/imagemagick
- abuild -r

### System Configuration

- ImageMagick version: 7.0.7.10
- Environment (Operating system, version and so on): Alpine Linux: Edge
- Additional information:

**Dependencies:**
```
makedepends="zlib-dev libpng-dev libjpeg-turbo-dev freetype-dev fontconfig-dev
  perl-dev ghostscript-dev libwebp-dev libtool tiff-dev lcms2-dev
  libwebp-dev libxml2-dev librsvg-dev"
checkdepends="freetype fontconfig ghostscript lcms2"
```

**Flags:**
```
  ./configure \
    --build=$CBUILD \
    --host=$CHOST \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --disable-static \
    --with-threads \
    --without-x \
    --with-tiff \
    --with-png \
    --with-webp \
    --with-rsvg \
    --with-gslib \
    --with-gs-font-dir=/usr/share/fonts/Type1 \
    --with-modules \
    --with-xml \
    $_pic
```

**Comment by urban-warrior** [comment]
You may need to install Ghostscript fonts.  All the tests fail because it can't find a required Helvetica font.  For example:

```
PASS: Magick++/demo/demos.tap 4
angle 0
Caught exception: lt-gravity: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1388
not ok
FAIL: Magick++/demo/demos.tap 5
```

**Comment by TBK** [comment]
@urban-warrior Thanks a lot. I just added ghostscript-fonts and it works flawlessly 👍
