### ISSUE TITLE
Rubygem tests fail after IM6 -19 to -22 update

### ISSUE THREAD

**Issue by mooninite** [ImageMagick/ImageMagick#857]
### Description
After updating from 6.9.9-19 to 6.9.9-22 a test in Rubygem-rmagick fails that previously passed.

### Steps to Reproduce
RubyGem rMagick 2.16.0
Build output:
https://kojipkgs.fedoraproject.org//work/tasks/799/23020799/build.log

### System Configuration

- ImageMagick version: 6.9.9-22
- Environment (Operating system, version and so on): Fedora Rawhide (all architectures)

**Comment by urban-warrior** [comment]
Try the latest ImageMagick release, 6.9.9-28.  If the tests continue to fail, let us know.

**Comment by mooninite** [comment]
There is no -28 available... I tried -27 and the same test still fails. The maintainer for the package has commented out the test so that the rubygem will build with a note that the "iterations initialization behavior changed in /coders/gif.c".

**Comment by fmw42** [comment]
6.9.9.28 is currently a beta. You can get it at http://magick.imagemagick.org/download/beta/

**Comment by mooninite** [comment]
Thanks. FYI, the links to sources for tar.gz, tar.lz, and .tar.xz give a 404 error on the beta link.

-28 still fails and is worse as it introduces an additional test failure. Here is the output:

`===============================================================================
Failure: test_iterations(ImageList1_UT)
/builddir/build/BUILD/rmagick-2.16.0/usr/share/gems/gems/rmagick-2.16.0/test/ImageList1.rb:36:in `test_iterations'
     33: 
     34:     def test_iterations
     35:         assert_nothing_raised { @list.iterations }
  => 36:         assert_equal(1, @list.iterations)
     37:         assert_nothing_raised { @list.iterations = 20 }
     38:         assert_equal(20, @list.iterations)
     39:         assert_raise(ArgumentError) { @list.iterations = 'x' }
<1> expected but was
<0>
===============================================================================
...........................................F
===============================================================================
Failure: <Magick::ImageMagickError> exception was expected but none was thrown.
test_montage(ImageList2_UT)
/builddir/build/BUILD/rmagick-2.16.0/usr/share/gems/gems/rmagick-2.16.0/test/ImageList2.rb:205:in `test_montage'
     202:       montage = ilist.montage { self.font = 2 }
     203:       assert_equal(@ilist, ilist)
     204:     end
  => 205:     assert_raise(Magick::ImageMagickError) do
     206:       montage = ilist.montage { self.frame = 'z' }
     207:       assert_equal(@ilist, ilist)
     208:     end
===============================================================================`

**Comment by urban-warrior** [comment]
We need to reproduce this problem before we can offer any help.  Our OS is Fedora.  How do we build rMagick against ImageMagick 6.9.9-28 Beta and get the unit tests to fail?

**Comment by mooninite** [comment]
Sorry for the delay. You can rebuild by doing the following:
$ fedpkg clone rubygem-rmagick
$ cd rubygem-rmagick
$ vi rubygem-rmagick.spec #(comment out the sed lines that remove the failing unit tests)
$ fedpkg mockbuild

**Comment by urban-warrior** [comment]
We took a shot but we could not get it to build.  We'd fix one problem and a new one would appear.  We're not the right developers to fix this problem.  Whomever takes care of rmagick should review this problem.  Did you post this concern to the rmagick developers?  However, if you can illustrate the problem from the command-line, without rmagick, we will investigate further.
