### ISSUE TITLE
"convert -layers OptimizeFrame" on IM7 won't erase pixels correctly

### ISSUE THREAD

**Issue by unarist** [ImageMagick/ImageMagick#859]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

In below example "Input", the bottom left area is filled on frame 1 and 2, and not filled on frame 3 and 4. 

However, that area is filled even on frame 3 and 4 in example "7.0.7-10", which is a result of `convert -layers OptimizeFrame`. This bug doesn't seem to exist on IM 6.9.9-22.

|Input|6.9.9-22|7.0.7-10|
|-|-|-|
|![input](https://user-images.githubusercontent.com/705555/32690829-4ef2201c-c740-11e7-9e24-f890ea5c0453.gif)|![6.9.9-22](https://user-images.githubusercontent.com/705555/32690813-1e2e5bee-c740-11e7-8802-4e3cc8bdabf4.gif)|![7.0.7-10](https://user-images.githubusercontent.com/705555/32690820-37b9f5fa-c740-11e7-9735-87417bd2a91f.gif)|

### Steps to Reproduce

1. Download [example image (same as above)](https://user-images.githubusercontent.com/705555/32690829-4ef2201c-c740-11e7-9e24-f890ea5c0453.gif)
2. `convert input.gif -layers OptimizeFrame out.gif`

### System Configuration

- ImageMagick version: 7.0.7-10 (ImageMagick-7.0.7-10-portable-Q16-x86)
- Environment (Operating system, version and so on): Windows10 x64
- Additional information: I've also confirmed the problem on Alpine Linux + imagemagick-7.0.5.10-r0

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick likely within a few weeks.
