### ISSUE TITLE
Combination of -resize and -layers optimize corrupts the first frame

### ISSUE THREAD

**Issue by unarist** [ImageMagick/ImageMagick#860]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

In below example, you can see the outer rectangle got thicker and dirty in the first frame, and this won't happen when I resize and optimize in separately.

**input.gif**

![input](https://user-images.githubusercontent.com/705555/32698882-902e0f64-c7ef-11e7-9930-c4179c98f2d3.gif)

**output.gif** (`convert input.gif -resize "120x" -layers optimize output.gif`)

![result](https://user-images.githubusercontent.com/705555/32698884-921c4d18-c7ef-11e7-9847-a8d9c596fd4a.gif)

**expected**

![output2](https://user-images.githubusercontent.com/705555/32699118-c10dc026-c7f3-11e7-93b8-26e5dd39b3d7.gif)

(It's mostly `convert input.gif -resize "120x" resized.gif` + `convert resized.gif -layers optimize output2.gif`, but [the frame 2 gets blank with this commands](https://user-images.githubusercontent.com/705555/32698916-4d6fb668-c7f0-11e7-82a2-5b9c809b8cb5.gif) somehow. So I've avoided this by open and save resized.gif in other software.)

### Steps to Reproduce

Download [above input.gif](https://user-images.githubusercontent.com/705555/32698882-902e0f64-c7ef-11e7-9930-c4179c98f2d3.gif), and run `convert input.gif -resize "120x" -layers optimize output.gif`.

### System Configuration

- ImageMagick version: 7.0.7-10 Q16 x86 2017-11-05
- Environment (Operating system, version and so on): Windows 10 x64
- Additional information:

**Comment by urban-warrior** [comment]
When #859 is resolved we conjecture this problem will resolve as well.
