### ISSUE TITLE
convert  -brightness-contrast leads to alpha channels that don't work in efl / Qt / Browsers

### ISSUE THREAD

**Issue by simotek** [ImageMagick/ImageMagick#861]
### Description
`convert  -brightness-contrast 40 -5` leads to alpha channels that don't work in efl / Qt / Browsers but do work in gimp for some images

### Steps to Reproduce
Run `convert  -brightness-contrast 40 -5` on 
![button_normal](https://user-images.githubusercontent.com/3827011/32707663-71357cd8-c875-11e7-8091-fc820f73c8e3.png) which results in 
![button_normal](https://user-images.githubusercontent.com/3827011/32707687-8fcf3b7a-c875-11e7-92da-b808bc2c4ca9.png)

### System Configuration

- ImageMagick version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by simotek** [comment]
Imagemagick 7.0.7.8 (Ill try the latest version shortly)
openSUSE Tumbleweed

**Comment by fmw42** [comment]
`convert -brightness-contrast 40 -5 on`. Is not a valid command line for IM 6 and especially IM 7. You need to read the input image first, then -brightness-contrast (with a comma or x between the arguments) and then the output. In IM 7, magick replace convert. So try

`magick  input -brightness-contrast 40,-5 output`

**Comment by simotek** [comment]
Ok, I was doing the first (it is in a script and I didn't extracted it out properly), doing the second and dropping the alpha channel has fixed the issue so I guess that some libraries aren't handling whatever transform was being done on the alpha channel.

**Comment by simotek** [comment]
It also seems like a regression from the version I ran 6-12 months back when I last used the script

**Comment by fmw42** [comment]
Can you provide a version number where it worked differently.?

**Comment by fmw42** [comment]
I check and it works without the -channel rgb in IM 6.9.9.23. But IM 7 behaves differently. The IM developers will need to decide if this is a different that is due to a bug or to a feature of the way, IM 7 works differently from IM 6. See http://imagemagick.org/script/porting.php#cli for all the difference. Channels work differently in IM 7 than they did in IM 6. But the IM developers need to decide if this needs special attention to make it work like in IM 6.

**Comment by simotek** [comment]
I have 6.8.8.1 on my other machine and it doesn't show the issue, my main laptop is running a rolling release so I think the imagemagick versions have been kept up to date, last time I ran the script in question to generate a release was October 2016 so it was probably whatever update came just before that when I last saw it working if that helps with a git bisect.

**Comment by urban-warrior** [comment]
Closing due to the topic being stale.
