### ISSUE TITLE
./configure --with-method-prefix is broken

### ISSUE THREAD

**Issue by olivren** [ImageMagick/ImageMagick#871]
I tried to compile ImageMagick 7.0.5 on Linux RHEL6, using GCC 6.3.1. Due to a collision of symbols with another third party I use, I need to use the `--with-method-prefix` ./configure option, that adds a prefix to all symbols of MagickCore.

Compiling with ./configure --with-method-prefix="cov" gives me the following error.

~~~
In file included from ./MagickCore/magick-config.h:25:0,
                 from ./MagickCore/studio.h:35,
                 from MagickCore/module.c:43:
MagickCore/module.c: In function ‘covInvokeDynamicImageFilter’:
./MagickCore/magick-baseconfig.h:1178:37: error: ‘cov’ undeclared (first use in this function)
 #define MAGICKCORE_NAMESPACE_PREFIX cov
                                     ^
MagickCore/module.c:996:5: note: in expansion of macro ‘MAGICKCORE_NAMESPACE_PREFIX’
     MAGICKCORE_NAMESPACE_PREFIX,tag);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
./MagickCore/magick-baseconfig.h:1178:37: note: each undeclared identifier is reported only once for each function it appears in
 #define MAGICKCORE_NAMESPACE_PREFIX cov
                                     ^
MagickCore/module.c:996:5: note: in expansion of macro ‘MAGICKCORE_NAMESPACE_PREFIX’
     MAGICKCORE_NAMESPACE_PREFIX,tag);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
MagickCore/module.c: In function ‘TagToModuleName’:
./MagickCore/magick-baseconfig.h:1178:37: error: ‘cov’ undeclared (first use in this function)
 #define MAGICKCORE_NAMESPACE_PREFIX cov
                                     ^
MagickCore/module.c:1553:7: note: in expansion of macro ‘MAGICKCORE_NAMESPACE_PREFIX’
       MAGICKCORE_NAMESPACE_PREFIX,format);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~

Indeed, all code expects the `MAGICKCORE_NAMESPACE_PREFIX` macro to be a simple name (`cov` in my case), but there are two places that expect the macro to be a string literal (`"cov"`).

https://github.com/ImageMagick/ImageMagick/blob/6714d07f302b9f5de13f8bf88d6f1cda88912d00/MagickCore/module.c#L1001-L1006

https://github.com/ImageMagick/ImageMagick/blob/6714d07f302b9f5de13f8bf88d6f1cda88912d00/MagickCore/module.c#L1554-L1565

My workaround is to patch these two bits of code to hardcode `"cov"` in place of `MAGICKCORE_NAMESPACE_PREFIX`. Everything works perfectly with this workaround.

The right thing to do would be to expand the macro to a string literal, but I know [doing that in C is quite ugly](https://gcc.gnu.org/onlinedocs/cpp/Stringizing.html#Stringizing).

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.
