### ISSUE TITLE
Return value of cairo_image_surface_create_for_data() is checked incorrectly

### ISSUE THREAD

**Issue by federicomenaquintero** [ImageMagick/ImageMagick#875]
https://github.com/ImageMagick/ImageMagick/blob/master/coders/svg.c#L3081-L3090

This calls `cairo_image_surface_create_for_data()` and checks the result against NULL.  This is not how Cairo reports out-of-memory.

Cairo will return a non-NULL surface, although it may return one that is in an error state.  ImageMagick needs to call cairo_surface_status() on the result and see if it is not CAIRO_STATUS_SUCCESS.  There are others like CAIRO_STATUS_NO_MEMORY, etc.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by federicomenaquintero** [comment]
Thanks!
