### ISSUE TITLE
Possible memory limit regression

### ISSUE THREAD

**Issue by ryandoyle** [ImageMagick/ImageMagick#876]
### Description
Hi there

We are having an issue with the current version of ImageMagick failing to convert files that previous versions would convert.

It is failing with the following message:

```
convert: DistributedPixelCache 'shared secret expected' @ error/distribute-cache.c/ConnectPixelCacheServer/209.
convert: cache resources exhausted `/home/ryan/document.pdf' @ error/cache.c/OpenPixelCache/3644.
```
I bisected the issue to the commit `04ff99576f1ebccfbafd5ddc35af2675afe1ad2a` which modifies `AcquireMagickResource()` to decrement a resource if it is over a limit. From my debugging, it looks like this introduces unintended behaviour in `OpenPixelCache()`.

Specifically starting `MagickCore/cache.c:3527`. If this acquisition fails and the `cache_info->type == MemoryCache`, then the code in that block continues up to line `3561`, where `RelinquishPixelCachePixels()` is called. This ends up calling `RelinquishMagickResource()`, and at `MagickCore/resource.c:976`, it decrements `resource_info.memory`. Basically it ends up decrementing twice and in our situation, ends up making `resource_info.memory` negative as its a signed long long. 

This seems to send the memory tracking into a bit of a weird state as new allocations fail because of the casting to a `MagickSizeType` in `MagickCore/resource.c:213`. 

I could create a patch to try and fix the accounting issues but to be honest, I'm not sure what the correct behaviour is here. Should the conditional at `MagickCore/cache.c:3528` continue to execute if the resource check fails? What is special about `cache_info->type == MemoryCache` that it is allowed to continue even if the check fails?

Thanks!

### System Configuration
- ImageMagick version: master, compiled locally
- Environment: Ubuntu 16.04

**Comment by dlemstra** [comment]
I wonder if we also need to check what happens after `status=AcquireMagickResource(DiskResource,cache_info->length);`

**Comment by ryandoyle** [comment]
Yeah, also `RelinquishMagickResource(MemoryResource,cache_info->length)`  at `MagickCore/cache.c:3581` too. I think this is a bit simpler and just needs to be moved one line up into the nested code block.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by ryandoyle** [comment]
Hey

Thanks for the prompt response guys. From my end it still looks like the memory resource is going negative.

As of `56596b797ec27544a4a5095f726e0f35b94bf2bc`, I'm now getting an assertion error:

```
convert: MagickCore/resource.c:217: AcquireMagickResource: Assertion `resource_info.memory >= 0' failed.
Aborted
```

**Comment by urban-warrior** [comment]
We need to reproduce the problem.  Can you post instructions on what we can do to throw the exception?

**Comment by ryandoyle** [comment]
Sure thing,
[test-without-memory-limits.pdf](https://github.com/ImageMagick/ImageMagick/files/1503586/test-without-memory-limits.pdf)


```
~/apps/imagemagick-7.0.7-head/bin $ ./convert -limit memory 50MiB -limit map 1536MiB -limit disk 0MiB  -background white -alpha remove -depth 8 -density 160x160 -resize 1024x768 test-without-memory-limits.pdf[0] out.png
convert: MagickCore/resource.c:217: AcquireMagickResource: Assertion `resource_info.memory >= 0' failed.

```

Whereas the following works. I've just got version `7.0.7-8` in this example.

```
~/apps/imagemagick-7.0.7-8/bin $ ./convert -limit memory 50MiB -limit map 1536MiB -limit disk 0MiB  -background white -alpha remove -depth 8 -density 160x160 -resize 1024x768 test-without-memory-limits.pdf[0] out.png
```

**Comment by urban-warrior** [comment]
We have a patch to fix the assertion, ready in a few hours.  However, with it we return to your original issue.  The reason your command fails is that you set the disk limit to 0.  With the patch, ImageMagick will return the expected exception: Cache resource exhausted.  You need to increase your disk limit if you expect the command to complete.

**Comment by ryandoyle** [comment]
Hi again, the removal of `|| (cache_info->type == MemoryCache)`  in `816ce59d8d9e0c7c3a3b128304fbca156d19b8ac` now makes the command fail always if a `cache_info->type` is anything but `UndefinedCache`.

For example, this command now fails, even with unlimited memory being set:

```
~/apps/imagemagick-7.0.7-head/bin $ ./convert -limit memory unlimited -limit map unlimited -limit disk 0MiB  -background white -alpha remove -depth 8 -density 160x160 -resize 1024x768 test-without-memory-limits.pdf[0] out.png
convert: cache resources exhausted `/tmp/magick-2313x69iuY4ojluO1' @ error/cache.c/OpenPixelCache/3652.
convert: Too many IDAT's found `/tmp/magick-2313x69iuY4ojluO1' @ error/png.c/MagickPNGErrorHandler/1711.
convert: cache resources exhausted `out.png' @ error/cache.c/OpenPixelCache/3652.
convert: memory allocation failed `out.png' @ error/png.c/WriteOnePNGImage/9257.
```

I removed the `cache_info->type == UndefinedCache` check and verified it works correctly but I have no idea the context around why checking for the cache type here is important and if it could be removed.

Is it correct to assume that if the memory limits are unlimited, it shouldn't use the disk cache?

**Comment by urban-warrior** [comment]
Good catch.  We think the most recent patch fixes the problem you reported.  If you spot additional problems with the cache resources, let us know.

**Comment by ryandoyle** [comment]
Re-built and verified. Looks all good now!

Cheers
