### ISSUE TITLE
When I used ImageMagick 6.78-9 to cut the image, the cropped image was larger than the original one. Is there a problem with my configuration？

### ISSUE THREAD

**Issue by BlackJia** [ImageMagick/ImageMagick#881]
```
Version: ImageMagick 6.7.8-9 2016-06-16 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP    
```
The original figure is 19kb of 470* 470, and the size of the compression has changed to more than 200kb.

When I cut the image with ImageMagick 7.1-7, it's normal.
```
Version: ImageMagick 7.0.1-7 Q16 x86_64 2017-09-20 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI 
Delegates (built-in): bzlib jpeg 
```
Use Same code.
```
IMOperation operation = new IMOperation();
        operation.addImage(sourceFilePath);
operation.resize(resizeWidth, resizeHeight, '^');
        operation.gravity("center");
        operation.extent(resizeHeight, resizeHeight);
        operation.addImage(filePath);
        ConvertCmd cmd = new ConvertCmd();
        cmd.run(operation);
```

**Comment by dlemstra** [comment]
@BlackJia Would you mind explaining why you closed it in case someone else finds this same issue?

**Comment by fmw42** [comment]
After cropping one should add +repage to avoid creating the virtual canvas when saving for example to PNG. What kind of input images are you using? If tiff, then the input may be compressed, but the output may not be compressed. Did you check the two images with identify -verbose to see the differences? It might be useful if you post your original image and your command line and output image.
