### ISSUE TITLE
how to covert jbig85 to png 

### ISSUE THREAD

**Issue by TCZWJ** [ImageMagick/ImageMagick#882]
### Prerequisites

- [ ] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of ImageMagick
- [ ] I  I have searched open and closed issues to ensure it has not already been reported

### Description
I cannot convert T85 jbig FAX to png.After i read the source code of ImageMagick , i found ImageMagick  only implements the jbig interface from JBIG-KIT.
Is there a way I can convert jbig85 fax to png? Or, Whether I have to modify the code to achieve my goal.
AnyOne can help me, thx!!

### System Configuration
redhat 7.2

- ImageMagick version:
the lastest.

**Comment by urban-warrior** [comment]
The T85 jbig FAX image format is not supported by ImageMagick.  We do not anticipate support for the format any time soon.
