### ISSUE TITLE
Jmagick Compatability

### ISSUE THREAD

**Issue by paulasiimwe** [ImageMagick/ImageMagick#883]
There doesn't seem to be any visible continuous maintenance of JMagick that I am able to see. (http://www.jmagick.org/ latest release was 2013!)
I'd like help to find out which versions of JMagick that ImageMagick 7.0.0 and above are compatible with and possible pointed to where I can find it if that's not too much to ask.

**Comment by urban-warrior** [comment]
JMagick is likely only compatible with ImageMagick 6 releases.  Someone will need to port JMagick for ImageMagick 7 compatibility per the porting guide @ https://www.imagemagick.org/script/porting.php.

**Comment by dlemstra** [comment]
Maybe you could open an issue here: https://github.com/techblue/jmagick?
