### ISSUE TITLE
Error reading grayscale png

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#884]
Recent versions of IM6 throw an error when reading grayscale PNG images. The problem is not present on older versions of IM. Here is an example image [gray.png](https://jeroen.github.io/images/gray.png)

```sh
> convert gray.png out.png
ERROR: convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG `out.png' @ # warning/png.c/MagickPNGWarningHandler/1665.
```

The image is recognized as `Type: GrayscaleAlpha` but still set to `Colorspace: sRGB`.

```sh
identify -verbose gray.png | head -n10
```
```
Image: gray.png
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: DirectClass
  Geometry: 480x480+0+0
  Units: Undefined
  Type: GrayscaleAlpha
  Endianess: Undefined
  Colorspace: sRGB
  Depth: 8-bit
```

In older versions of IM this image gets (correctly) recongized as `Type: Grayscale`.

**Comment by urban-warrior** [comment]
Try this:

`convert gray.png -strip out.png`

**Comment by jeroen** [comment]
That works for the example that I have, but this problem [actually appears](https://github.com/ropensci/magick/issues/74) in my C++ bindings.

**Comment by jeroen** [comment]
Here is [yet another report](https://stackoverflow.com/questions/45338822/error-using-r-magick-package) of this problem. Is there some way to add a fix that does not require the user to manually add `strip = TRUE` to read grayscale pngs?

**Comment by fmw42** [comment]
This works for me:

`convert gray.png +profile "*" tmp.png`

or

`convert gray.png +profile "icc" tmp.png`

**Comment by w-A-L-L-e** [comment]
Just as a heads up. This also breaks many third party packages. An example is the mini_magick gem in ruby on rails. This error bubbles down and basically disables the ability to use greyscale png  in any rails project using image scaling through mini_magick.

Furthermore, from a user and developer standpoint it seems totally strange to handle greyscale png images different than color ones... IMHO ImageMagick should handle this without any extra parameters. Sure keep the '+profile param' to do something specific but it's NOT OK to throw an error that does not happen on a RGB image with same parameters... 

Remember the core use of imagemagick is to abstract these kind of things from a developer and user using ImageMagick it's basically the core usage to be able to scale an image regardless of the image format...

**Comment by dlemstra** [comment]
@w-A-L-L-e We closed this issue because we are not raising an error. The message is a warning that grayscale images don't support RGB color profiles. But warning can be ignored. @jeroen has done this by enabling the `quiet` option in Magick++ (https://github.com/ropensci/magick/commit/289e997896b037517a3cb46400015e1b138555d9). You could also ignore them on the command line with `-quiet`. I have no idea how you need to do that with mini_magick though.

**Comment by w-A-L-L-e** [comment]
You might think that but somehow it does break the normal chain of execution. Look here all the error'ed favicons are due this above greyscale issue http://favicon.sitweb.eu. Since its just a freebee/spare time project I wont bother fixing it any time soon. Still thanks for the quick reply.
