### ISSUE TITLE
Utility function for converting fuzz percentage to double

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#885]
I am using `Magick::colorFuzzImage` to set a fuzz (double) and then `Magick::floodFillColorImage`. However the fuzz scale is unclear. By trial and error I have found that valid fuzz values are between 0 and 65536 and usually need to be close to the upper end to have any effect at all.

Is there a utility function or formula to let the user specify the fuzz as a percentage value which I can then convert to a fuzz factor for `Magick::colorFuzzImage` or `Magick:: colorFuzz`?

**Comment by urban-warrior** [comment]
For percent fuzz, just multiply the percent by MagickCore:QuantumRange+1 and divide by 100.

**Comment by jeroen** [comment]
Thank you. Any guess how I get to `QuantumRange` from Magick++? There is no `MagickCore::QuantumRange` in the headers I think.

**Comment by jeroen** [comment]
Ah there is a constant `MagickQuantumRange`.

**Comment by dlemstra** [comment]
@jeroen Have you tried just using `QuantumRange`?

**Comment by jeroen** [comment]
That didn't work but perhaps I forgot to include a header or so?

```
/usr/local/Cellar/imagemagick@6/6.9.9-23/include/ImageMagick-6/magick/magick-type.h:86:25: note: expanded from macro 'QuantumRange'
#define QuantumRange  ((Quantum) 65535)
                        ^
/usr/local/Cellar/imagemagick@6/6.9.9-23/include/ImageMagick-6/Magick++/Include.h:283:21: note: 'Magick::Quantum' declared here
  using MagickCore::Quantum;
                    ^
```
