### ISSUE TITLE
Invalid delete when processing images

### ISSUE THREAD

**Issue by woodyuk11** [ImageMagick/ImageMagick#886]
I raised this question on the bugs forum but didn't get a response about what i'm seeing: https://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=33114&p=151717#p151717

Could anyone provide some insight to the crashes i'm witnessing? I have attempted using Windows 6.9.9-20 and 7.0.7-11. This was not present in 6.9.4-8.

**Comment by dlemstra** [comment]
Could you create a small sample program that we can use to reproduce this issue?

**Comment by woodyuk11** [comment]
Here is a small sample program that loads in the file via a single argument in the command line.:

https://github.com/woodyuk11/SampleImageMagick

Load in the test.WPG image.

The Blob makes it's own copy of the data from *data_buffer. This data no longer exists after the magImage.read(), so when the Blob goes out of scope it crashes.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by woodyuk11** [comment]
Is there going to be a full beta build including the windows VisualMagick directories?

**Comment by woodyuk11** [comment]
Built using the beta and ran my tests over it and I can confirm the issue is no longer present.

**Comment by dlemstra** [comment]
@woodyuk11 It was released yesterday.
