### ISSUE TITLE
Comparing two different images results in a error with blank output

### ISSUE THREAD

**Issue by JackDanielZ** [ImageMagick/ImageMagick#887]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of ImageMagick
- [X] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I compare two pngs where the difference should be the scroller on the top right, the error code is 1 (= different). When I look at the output, I don't see any red pixels. When I compare with the -metric AE option (if I understand well, it should return the number of different pixels), I get 0.

I attached the files:
![output](https://user-images.githubusercontent.com/5675055/33349605-855e3f12-d4a3-11e7-8e0a-8406ed739ef4.png)
![2](https://user-images.githubusercontent.com/5675055/33349606-85b9b93c-d4a3-11e7-890e-e1e0299f10d5.png)
![1](https://user-images.githubusercontent.com/5675055/33349608-8620ca6e-d4a3-11e7-83f7-1a4a39e9a45e.png)
### Steps to Reproduce
compare 1.png 2.png output.png
echo $? -> 1 while output doesn't show red pixels
compare -metric AE 1.png 2.png output.png -> 0
echo $? -> 0

### System Configuration
Version: ImageMagick 6.9.9-23 Q16 x86_64 2017-11-12
Linux Yoga 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux

**Comment by urban-warrior** [comment]
We added a patch to 6.9.9-24 Beta a few weeks ago that resolves the problem you reported.  6.6.9-24 will likely be released within a week.

**Comment by JackDanielZ** [comment]
Thank you for the information

**Comment by JackDanielZ** [comment]
Hi,

I compiled from git and it works great

Thank you
