### ISSUE TITLE
[Magick++] Hardcoded addNoise density

### ISSUE THREAD

**Issue by khanhas** [ImageMagick/ImageMagick#889]
`attenuate` method should control `addNoise` method's density but it doesn't. I checked their source code and it turns out the density was hardcoded as `1.0`. 
https://github.com/ImageMagick/ImageMagick/blob/master/Magick%2B%2B/lib/Image.cpp#L1799

**Comment by dlemstra** [comment]
The `attenuate` property was only used by the `addNoise` method and that is why we decided to add an extra argument to the `addNoise` method to specify the density and remove the `attenuate` property. This will become available in the next version of ImageMagick 7.

**Comment by khanhas** [comment]
Thank you. Keep up the good work, you're guys are awesome!

**Comment by jeroen** [comment]
My build is now failing :( Was this intended to be a breaking change?
```c++
// [[Rcpp::export]]
XPtrImage magick_image_noise( XPtrImage input, const char * noisetype){
  XPtrImage output = copy(input);
  for_each ( output->begin(), output->end(), Magick::addNoiseImage(Noise(noisetype)));
  return output;
}
```

Compiler error:

```
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/local/Cellar/imagemagick/7.0.7-14/include/ImageMagick-7 -I"/Users/travis/R/Library/Rcpp/include" -I/usr/local/include   -fPIC  -Wall -g -O2 -c transformations.cpp -o transformations.o
transformations.cpp:120:46: error: no matching conversion for functional-style cast from 'Magick::NoiseType' to 'Magick::addNoiseImage'
  for_each ( output->begin(), output->end(), Magick::addNoiseImage(Noise(noisetype)));
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/Cellar/imagemagick/7.0.7-14/include/ImageMagick-7/Magick++/STL.h:79:24: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'Magick::NoiseType' to 'const Magick::addNoiseImage' for 1st argument
  class MagickPPExport addNoiseImage
                       ^
/usr/local/Cellar/imagemagick/7.0.7-14/include/ImageMagick-7/Magick++/STL.h:79:24: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'Magick::NoiseType' to 'Magick::addNoiseImage' for 1st argument
/usr/local/Cellar/imagemagick/7.0.7-14/include/ImageMagick-7/Magick++/STL.h:82:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    addNoiseImage(const NoiseType noiseType_,const double attenuate_);
    ^
```

**Comment by dlemstra** [comment]
Yes it was and we did a version bump because of this breaking change.

**Comment by jeroen** [comment]
Would it be possible to add a c++ compatibility overload or set a default `attenuate_ = 1.0` such that clients can use the same API before and after this change was made? 

Otherwise bindings will have to condition their call to `addNoiseImage()` on the exact version of IM in order to know whether to call `addNoiseImage(noise_type, 1.0)` or `addNoiseImage(nose_type)`...

**Comment by dlemstra** [comment]
It looks like we only added the default inside Image.cpp and not in STL.h that you seem to be using. Just pushed a fix for that which should be available in the next release.

**Comment by jeroen** [comment]
OK thanks :D
