### ISSUE TITLE
unable to open image `/tmp/magick-17483dH3bBD3MdnV2.pam': No such file or directory

### ISSUE THREAD

**Issue by tumayun** [ImageMagick/ImageMagick#89]
When I use imagemagick, I encountered the following problems.
This problem has troubled me for a long time, and can you give me some help? Many thanks!

```ruby
MiniMagick::Error (`convert /u/apps/yep_server/releases/20160121211238/public/uploads/tmp/attachment/file/1453411541-17453-4991/thumb_file.mp4[0] -auto-orient -resize 320x320 -quality 50 +repage /u/apps/yep_server/releases/20160121211238/public/uploads/tmp/attachment/file/1453411541-17453-4991/tmpfile.jpg` failed with error:
convert: delegate failed `"ffmpeg" -nostdin -v -1 -i "%i" -vframes %S -vcodec pam -an -f rawvideo -y "%u.pam" 2> "%Z"' @ error/delegate.c/InvokeDelegate/1332.
convert: unable to open image `/tmp/magick-17483dH3bBD3MdnV2.pam': No such file or directory @ error/blob.c/OpenBlob/2702.
convert: no images defined `/u/apps/yep_server/releases/20160121211238/public/uploads/tmp/attachment/file/1453411541-17453-4991/tmpfile.jpg' @ error/convert.c/ConvertImageCommand/3241.
):
```

The imagemagick log:

https://gist.github.com/tumayun/3de31ae31e684238fcdf

**Comment by dlemstra** [comment]
It looks like you are using MiniMagick which is not maintained by us. You could ask for help here: https://github.com/minimagick/minimagick but I think you don't have ffmpeg installed on your machine.

**Comment by tumayun** [comment]
@dlemstra Thank you for your reply.
The pam file seems to be generated by the imagemagick, right?

**Comment by tumayun** [comment]
@dlemstra Hello
Can you look at my newly added log file?
Thank you very much!

**Comment by dlemstra** [comment]
Your log states this:

```
2016-01-22T08:37:31+00:00 0:00.020 0.020u 6.9.3 Exception convert[19710]: delegate.c/InvokeDelegate/1332/Exception
  delegate failed `"ffmpeg" -nostdin -v -1 -i "%i" -vframes %S -vcodec pam -an -f rawvideo -y "%u.pam" 2> "%Z"'
```

Delegate failed means that ImageMagick was unable to execute your delegate. Do you have ffmpeg installed on your system?

**Comment by tumayun** [comment]
@dlemstra Yes, I installed ffmpeg.

**Comment by dlemstra** [comment]
Do you have the ffmpeg executable in your path?
