### ISSUE TITLE
Build failure in IM 6.9.9-25 for --without-modules

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#890]
I always build IM6 `--without-modules --with-zero-configuration` for use in a portable app. In IM `6.9.9-23` this was working fine but `6 6.9.9-24` and `6 6.9.9-25` give an error when I build with the following configuration. Any guess what's wrong?

```
brew reinstall imagemagick@6 --without-modules
==> Reinstalling imagemagick@6 --without-modules
==> Downloading https://dl.bintray.com/homebrew/mirror/imagemagick%406-6.9.9-25.tar.xz
Already downloaded: /Users/jeroen/Library/Caches/Homebrew/imagemagick@6-6.9.9-25.tar.xz
==> ./configure --disable-osx-universal-binary --prefix=/usr/local/Cellar/imagemagick@6/6.9.9-25 --disable-silent-rules --enable-shared --enable-static
==> make install
Last 15 lines from /Users/jeroen/Library/Logs/Homebrew/imagemagick@6/02.make:
      _OpenModule in magick_libMagickCore_6_Q16_la-module.o
      _DestroyModuleNode in magick_libMagickCore_6_Q16_la-module.o
  "_lt_dlinit", referenced from:
      _IsModuleTreeInstantiated in magick_libMagickCore_6_Q16_la-module.o
  "_lt_dlopen", referenced from:
      _InvokeDynamicImageFilter in magick_libMagickCore_6_Q16_la-module.o
      _OpenModule in magick_libMagickCore_6_Q16_la-module.o
  "_lt_dlsym", referenced from:
      _InvokeDynamicImageFilter in magick_libMagickCore_6_Q16_la-module.o
      _OpenModule in magick_libMagickCore_6_Q16_la-module.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by urban-warrior** [comment]
We downloaded the ImageMagick source to the latest Mac OS X release (High Sierra), ran your exact configure command-line, and built binaries without complaint.  We're not sure why its failing with brew.  We did need to make a change recently because OpenCL support requires lt_dlopen, lt_dlinit, etc.  Does your computer include a GPU and OpenCL libraries?  You can check the config.log file to see if OpenCL is reported as supported.

We have no control over brew, but they might need to include a dependency to the libtool-ltdl library.

**Comment by jeroen** [comment]
OK homebrew says it must be a bug in imagemagick. Here is the [full build log](https://gist.github.com/5c58700824d14dd4f1e2de5a7a272b57). 

So the problem is that it is not picking up on `-lltdl`. Where is this supposed to happen? I found that I can work around the problem with `export LIBS=-lltdl`.

**Comment by urban-warrior** [comment]
We added a patch to ImageMagick 6.9.9-26 Beta available @ http://magick.imagemagick.org/download/beta (building now, ready in 20 minutes).  Let us know if it works properly with brew and we'll push a 6.9.9-26 release.

**Comment by ilovezfs** [comment]
@urban-warrior LGTM.
