### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rahulpatel033** [ImageMagick/ImageMagick#891]
ImageMagick Version: 7.0.7-14
System: Ubuntu 16.04.2 LTS

I tried to install ImageMagick from source.
when I ran ` sudo make`, this error occurred.

```
make[1]: Entering directory '/home/delegates/new/IM/ImageMagick-7.0.7-14'
  CC       MagickWand/MagickWand_libMagickWand_7_Q16HDRI_la-convert.lo
gcc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:9145: recipe for target 'MagickWand/MagickWand_libMagickWand_7_Q16HDRI_la-convert.lo' failed
make[1]: *** [MagickWand/MagickWand_libMagickWand_7_Q16HDRI_la-convert.lo] Error 1
make[1]: Leaving directory '/home/delegates/new/IM/ImageMagick-7.0.7-14'
Makefile:5183: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by urban-warrior** [comment]
Post this issue to the Ubuntu or gcc teams.  Its a gcc internal compiler error not a bug in ImageMagick.  Note that we use gcc version 5.4.0 under Ubuntu1~16.04.5 and ImageMagick compiles and builds without complaint.

**Comment by golee** [comment]
To someone has this problem:
It could be out of memory situation. 
Set swap memory or stop some services to secure free memory before compile.
