### ISSUE TITLE
[Feature Request] Output of `magick -list list` should enumerate 'SubCommands'

### ISSUE THREAD

**Issue by KurtPfeifle** [ImageMagick/ImageMagick#892]
### Background consideration

In the past I held a few ImageMagick6 tutorials. What participants very often liked a lot was the way how they could learn (and memorize) about ImageMagick features and settings options by running *`convert -list list`*. As you know, you get back a list of items, which you can then apply again on the command line like *`convert -list item1`* or *`convert -list item2`* etc.

With ImageMagick7 it would be nice to get the a list displaying all the sub-commands which are available.

### Feature request

When running *`magick -list list`* it should return an additional entry in the list like:

`[....]`    
*`Storage`*    
*`Stretch`*    
*`Style`*    
**`SubCommand`**    
*`Threshold`*    
`[....]`

Then, when in turn running *`magick -list subcommand`*, the output should be:

 `animate`    
 `compare`    
 `composite`    
 `conjure`    
 `convert`    
 `display`    
 `identify`    
 `import`    
 `magick-script`    
 `mogrify`    
 `montage`    
 `stream`

### Benefit

This would help people discover available sub-commands easier. ImageMagick would gain a small amount of "self-documenting" within its commands.

**Comment by urban-warrior** [comment]
We have a patch to implement your suggestion it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by urban-warrior** [comment]
Try this command: ```magick -list tool```
