### ISSUE TITLE
[Feature Request] Output of `magick -list list` should enumerate 'OperatorTypes'

### ISSUE THREAD

**Issue by KurtPfeifle** [ImageMagick/ImageMagick#893]
### Background consideration

In the past I held a few ImageMagick6 tutorials. What participants very often liked a lot was the way how they could learn (and memorize) about ImageMagick features and settings options by running *`convert -list list`*. As you know, you get back a list of items, which you can then apply again on the command line like *`convert -list item1`* or *`convert -list item2`* etc.

With ImageMagick7 it would be nice to get the a list displaying all **operator types** (operator categories) which are available.

### Feature request

When running *`magick -list list`* it should return an additional entry in the list like:

`[....]`    
*`Morphology`*    
*`Module`*    
*`Noise`*    
**`OperatorType`**    
*`Orientation`*    
`[....]`

Then, when in turn running *`magick -list OperatorType`*, the output should be:

 `ImageChannelOperator`    
 `ImageGeometry`   
 `ImageOperator`   
 `ImageSequenceOperator`   
 `ImageSetting`   
 `ImageStackOperator`   
 `MiscellaneousOption`

Then again, when running *`magick -list [ImageChannelOperator|ImageOperator|ImageSequenceOperator|ImageSetting|ImageStackOperator|MiscellaneousOption]`* we should see this printed:

**magick -list ImageChannelOperator**

    -channel-fx
    -separate

**magick -list ImageOperator**

    -adaptive-blur
    -adaptive-resize
    -adaptive-sharpen
    -alpha
    [....]

**magick -list ImageSequenceOperator**

     -clut
     -coalesce
     -combine
     -compare
     [....]

**magick -list ImageSetting**

    -affine
    -alpha
    -antialias
    -attenuate
    [....]

**magick -list ImageStackOperator**

    -clone
    -delete
    -duplicate
    -insert
    -reverse
    -swap

**magick -list MiscellaneousOption**

    -debug
    -distribute-cache
    -help
    -list
    -log
    -version

### Benefit

This would help people learn to better distinguish between available operator types. This is key in order to understand the architectur, anatomy and logic of (long) ImageMagick command lines. ImageMagick would gain a small amount of "self-documentation" within its commands.

**Comment by urban-warrior** [comment]
We do not see implementing your suggestion anytime soon.  We instead refer you to the command-line processing  documentation @ https://www.imagemagick.org/script/command-line-processing.

**Comment by KurtPfeifle** [comment]
@urban-warrior,

would you accept a pull request which implements a part of this request, i.e.

> ### Feature request
>
> When running *`magick -list list`* it should return an additional entry in the list like:
>
> `[....]`    
> *`Morphology`*    
> *`Module`*    
> *`Noise`*    
> **`OperatorType`**    
> *`Orientation`*    
> `[....]`
>
> Then, when in turn running *`magick -list OperatorType`*, the output should be:
>
> `ImageChannelOperator`    
> `ImageGeometry`    
> `ImageOperator`   
> `ImageSequenceOperator`   
> `ImageSetting`   
> `ImageStackOperator`   
> `MiscellaneousOption`

meaning: no more further diving into *`magick -list ImageChannelOperator`*, etc.
?

**Comment by urban-warrior** [comment]
Try this command: ```magick -list cli```

**Comment by KurtPfeifle** [comment]
@urban-warrior:

Beautiful! Wonderful!
This is an even simpler way than I proposed, and it fully satisfied my wish.
