### ISSUE TITLE
[Feature Request] Output of `magick -list list` should enumerate 'PercentEscapes'

### ISSUE THREAD

**Issue by KurtPfeifle** [ImageMagick/ImageMagick#894]
### Background consideration

In the past I held a few ImageMagick6 tutorials. What participants very often liked a lot was the way how they could learn (and memorize) about ImageMagick features and settings options by running *`convert -list list`*. As you know, you get back a list of items, which you can then apply again on the command line like *`convert -list item1`* or *`convert -list item2`* etc.

With ImageMagick7 it would be nice to get the a list displaying all available *percent escapes*.

### Feature request

When running *`magick -list list`* it should return an additional entry in the list like:

`[....]`      
*`Module`*    
*`Noise`*    
**`PercentEscape`**    
*`PixelChannel`*    
`[....]`

Then, when in turn running *`magick -list percentescape`*, the output should be:

    %% :  a percent sign
    %b :  file size of image read in
    %c :  comment meta-data property
    %d :  directory component of path
    %e :  filename extension or suffix
    %f :  filename (including suffix)
    %g :  layer canvas page geometry (equivalent to "%Wx%H%X%Y")
    %h :  current image height in pixels
    %i :  image filename (note: becomes output filename for "info:")
    %k :  CALCULATED: number of unique colors
    %l :  label meta-data property
    %m :  image file format (file magic)
    %n :  number of images in current image sequence
    %o :  output filename (used for delegates)
    %p :  index of image in current image list
    %q :  quantum depth (compile-time constant)
    %r :  image class and colorspace
    %s :  scene number (from input unless re-assigned)
    %t :  filename without directory or extension (suffix)
    %u :  unique temporary filename (used for delegates)
    %w :  current width in pixels
    %x :  x resolution (density)
    %y :  y resolution (density)
    %z :  image depth (as read in unless modified, image save depth)
    %A :  image transparency channel enabled (true/false)
    %C :  image compression type
    %D :  image GIF dispose method
    %G :  original image size (%wx%h; before any resizes)
    %H :  page (canvas) height
    %M :  Magick filename (original file exactly as given, including read mods)
    %O :  page (canvas) offset ( = %X%Y )
    %P :  page (canvas) size ( = %Wx%H )
    %Q :  image compression quality ( 0 = default )
    %S :  ?? scenes ??
    %T :  image time delay (in centi-seconds)
    %U :  image resolution units
    %W :  page (canvas) width
    %X :  page (canvas) x offset (including sign)
    %Y :  page (canvas) y offset (including sign)
    %Z :  unique filename (used for delegates)
    %@ :  CALCULATED: trim bounding box (without actually trimming)
    %# :  CALCULATED: 'signature' hash of image values

<sup>(Not sure if this list is complete).</sup>

### Benefit

This would help people discover available percent-escapes easier. faster would gain a small amount of "self-documentation" within its commands.

**Comment by urban-warrior** [comment]
We do not see implementing your suggestion anytime soon.  We instead refer you to the percent-escape documentation @ https://www.imagemagick.org/script/escape.php.
