### ISSUE TITLE
errors in ImageMagick installation

### ISSUE THREAD

**Issue by Oyebode** [ImageMagick/ImageMagick#897]
i get these errors when i try to check for how well my ImageMagick software has installed. can someone please help

make[3]: *** [test-suite.log] Error 1
make[2]: *** [check-TESTS] Error 2
make[1]: *** [check-am] Error 2
make: *** [check] Error 2

the tests passed in 84 out of 86 areas. it failed in these areas

FAIL: tests/wandtest.tap 1
FAIL: Magick++/demo/demos.tap 6

**Comment by gstkenpo** [comment]
I have the same problem.
Here is my error-suit.log
# XFAIL: 0
# FAIL:  2
FAIL: tests/wandtest
FAIL: tests/wandtest.tap 1
FAIL: Magick++/demo/demos
FAIL: Magick++/demo/demos.tap 6

I am running ubuntu 16

**Comment by urban-warrior** [comment]
Take a look at tests/wandtest.log to determine which unit test failed.  ImageMagick unit tests do depend on ghostscript and ghostscript fonts to pass.  If you don't have these installed, ImageMagick will still work, but will not be able render Postscript nor properly annotate image text.  Everything else should work though.
