### ISSUE TITLE
svg format can not be read

### ISSUE THREAD

**Issue by LiuLian1992** [ImageMagick/ImageMagick#898]
### Description

when running on iphone or android,if the image's format is svg ,then can't be readBlob or readfile.
when running on mac or iphone simulators,svg is ok.
### Steps to Reproduce

    //svg
   const char* test_base64 = "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj4KPHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSLlm77lsYJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiIHdpZHRoPSI1OTUuMjhweCIgaGVpZ2h0PSI4NDEuODlweCIgdmlld0JveD0iMCAwIDU5NS4yOCA4NDEuODkiIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAwIDU5NS4yOCA4NDEuODkiIHhtbDpzcGFjZT0icHJlc2VydmUiPgogICAgPGxpbmUgZmlsbD0ibm9uZSIgc3Ryb2tlPSIjMjMxODE1IiBzdHJva2UtbWl0ZXJsaW1pdD0iMTAiIHgxPSIxNDgiIHkxPSIxMTgiIHgyPSIzODQiIHkyPSI2MTYiLz4KICAgIDxsaW5lIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzIzMTgxNSIgc3Ryb2tlLW1pdGVybGltaXQ9IjEwIiB4MT0iOTEiIHkxPSI1MDUiIHgyPSI0NTQiIHkyPSIxNTciLz4KICAgIDxsaW5lIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzIzMTgxNSIgc3Ryb2tlLW1pdGVybGltaXQ9IjEwIiB4MT0iNDEiIHkxPSIxOTkiIHgyPSIzOTEiIHkyPSI0MzYiLz4KICAgIDxsaW5lIGZpbGw9Im5vbmUiIHN0cm9rZT0iIzIzMTgxNSIgc3Ryb2tlLW1pdGVybGltaXQ9IjEwIiB4MT0iMzM5IiB5MT0iMTQ4IiB4Mj0iMTY0IiB5Mj0iNTYyIi8+Cjwvc3ZnPgo=";
    int len_test = 0;
    unsigned char* byte_test;
    size_t len1 = 0;
    byte_test = Base64Decode(test_base64, &len1);
    for (int i=0; i<len1; i++) {
        
        printf("%.2x",byte_test[i]);
    }
    MagickWand *w_wand = NULL;
    MagickWandGenesis();
    w_wand = NewMagickWand();
    MagickBooleanType status;
    
    status = MagickReadImageBlob(w_wand,byte_test,len1);

**Comment by LiuLian1992** [comment]
when running on mac or iphone simulators,svg is ok.

**Comment by urban-warrior** [comment]
ImageMagick has an internal SVG renderer but its far from being compliant with the SVG specification and can fail to read anything but the most basic SVG image files.  Instead, we recommend installations rely on alternative SVG renderers, either the RSVG delegate library or Inkscape.  Inkscape is likely not available for the iPhone but its likely the RSVG delegate library is.

**Comment by LiuLian1992** [comment]
but the iphone simulator can run normal,I searched for librsvg,but all for windows .Maybe i need the svg lib for iphone and android?

**Comment by urban-warrior** [comment]
Yes you could likely call a iOS API to render SVG properly.  At least for the iPhone, ImageMagick might not be the best choice.

**Comment by FlashTang** [comment]
I'm having the same issue , yes it works on iOS simulator, but error in real device, and there is no reason to use RSVG or other libraries , since I want to convert SVG to png in iOS Xcode project,
Do you have any solution ? why svg not works on real device ?
Thanks
P.S.  I can use wkwebview to render SVG then take a screenshoot with iOS UIKit api  , but when once the size is big (say 50000x5000), it will fail with black empty image.
