### ISSUE TITLE
[Magick++] fontTypeMetrics does not scale with density setting

### ISSUE THREAD

**Issue by khanhas** [ImageMagick/ImageMagick#905]
### Prerequisites

- [ 👍 ] I have written a descriptive issue title
- [ 👍 ] I have verified that I am using the latest version of ImageMagick
- [ 👍 ] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
`fontTypeMetrics` and `fontTypeMetricsMultiline` do not take `density` setting into account, although their description in [header](https://github.com/ImageMagick/ImageMagick/blob/master/Magick%2B%2B/lib/Magick%2B%2B/Image.h#L949) claimed they do.  

### Steps to Reproduce
```cpp
Magick::Image temp;
Magick::TypeMetric me;
std::string example = "LOLDUDE";

temp.density(72);
temp.fontTypeMetrics(example, &me);
printf("%f", me.textWidth());

temp.density(144);
temp.fontTypeMetrics(example, &me);
printf("%f", me.textWidth());
````
Result:
```
58.000000
58.000000
```

**Comment by urban-warrior** [comment]
image.density() refers to the image resolution.  You instead likely want to use image.fontPointsize().
