### ISSUE TITLE
memory leaks in ReadRLEImage

### ISSUE THREAD

**Issue by henices** [ImageMagick/ImageMagick#916]
## INFO
Version: ImageMagick 7.0.7-16 Q16 x86_64 2017-12-25 http://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gvc jbig jng jpeg lcms lqr lzma pangocairo png rsvg tiff webp wmf x xml zlib

Trigger Command: **magick convert memory-leaks-ReadRLEImage.5 /dev/null**

## ASAN OUTPUT
```

=================================================================
==25616==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3 byte(s) in 1 object(s) allocated from:
    #0 0x7f47abdb3850 in malloc (/lib64/libasan.so.4+0xde850)
    #1 0x7f47ab189a7b in AcquireMagickMemory MagickCore/memory.c:464
    #2 0x7f47ab189acf in AcquireQuantumMemory MagickCore/memory.c:537
    #3 0x7f47ab56c983 in ReadRLEImage coders/rle.c:284
    #4 0x7f47aafb66c7 in ReadImage MagickCore/constitute.c:497
    #5 0x7f47aafb9590 in ReadImages MagickCore/constitute.c:866
    #6 0x7f47aa76c9d1 in ConvertImageCommand MagickWand/convert.c:641
    #7 0x7f47aa8e726e in MagickCommandGenesis MagickWand/mogrify.c:183
    #8 0x401b16 in MagickMain utilities/magick.c:149
    #9 0x401d80 in main utilities/magick.c:180
    #10 0x7f47a44d1009 in __libc_start_main (/lib64/libc.so.6+0x21009)

SUMMARY: AddressSanitizer: 3 byte(s) leaked in 1 allocation(s).
```

testcase:  https://github.com/henices/pocs/raw/master/memory-leaks-ReadRLEImage.5

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
