### ISSUE TITLE
export MagickImageSubRange in MagickWand

### ISSUE THREAD

**Issue by rocaltair** [ImageMagick/ImageMagick#922]
Error occurs now if the last frame in gif is corrupted on MagickReadImageBlob or MagickReadImageBlob.

And it's very slow if I want the first frame only for gif format.

See [Magick++]( https://github.com/ImageMagick/ImageMagick/blob/a52e9472029b48368e592c92f041901de2d18cae/Magick%2B%2B/lib/Image.cpp#L1521)

How about export WandImageSubRange to MagickWand?

in C:

```
void WandImageSubRange(MagickWand *wand, size_t start, size_t count)
{
        wand->image_info->scene = start;
        wand->image_info->number_scenes = count;
}

```

so that, we can call as follows:

```
wand=NewMagickWand();
MagickImageRange(wand, 0, 1);  /*load the first frame of gif*/
MagickReadImageBlob(magick_wand, gif_blob, size);
...
```

**Comment by urban-warrior** [comment]
What happens if you use

```
MagickSetFilename(magick_wand,"image.gif[0]");
MagickReadImageBlob(magick_wand, gif_blob, size);
```
?

**Comment by rocaltair** [comment]
Cool, it works~

much appreciated!
