### ISSUE TITLE
multi frame tiff files

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#925]
__edit__ actually it *does* seem to work for some other tiffs. Perhaps there is just something odd about the ImageJ tiffs.

Scientific image processing software such as [ImageJ](https://en.wikipedia.org/wiki/ImageJ) stores tiff files with multiple frames (for xray scans and such). It would be great if we can read such multi-frame tiff files using Magick++ STL `readImages()` the same way as multi-frame gif files.

Here is a toy example of such an image with 3 frames: https://imagej.nih.gov/ij/images/Composite.tif

Currently if I read this with the STL it only reads only one channel:

```
> image_read("~/Downloads/Composite.tif")
  format width height colorspace matte filesize
1   TIFF   171    140       Gray FALSE   144408
Warning messages:
1: In magick_image_readpath(path, density, depth, strip) :
  TIFFFetchStripThing: Incorrect count for "StripOffsets"; tag ignored
2: In magick_image_readpath(path, density, depth, strip) :
  TIFFFetchStripThing: Incorrect count for "StripByteCounts"; tag ignored
```

**Comment by urban-warrior** [comment]
ImageMagick / Magick++ STL can read a multiple frames from a TIFF container.  In your example, the TIFF image only has one frame.  Here is the output of tiffinfo:

```
-> tiffinfo Composite.tif 
TIFFFetchStripThing: Warning, Incorrect count for "StripOffsets"; tag ignored.
TIFFFetchStripThing: Warning, Incorrect count for "StripByteCounts"; tag ignored.
TIFF Directory at offset 0x8 (8)
  Subfile Type: (0 = 0x0)
  Image Width: 171 Image Length: 140
  Bits/Sample: 16
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Samples/Pixel: 3
  Rows/Strip: 140
  Planar Configuration: separate image planes
  ImageDescription: ImageJ=1.38n
channels=3
min=33.0
max=3931.0
```

**Comment by jeroen** [comment]
OK you are right, ImageJ has stored the 3 channels as shown in your output `channels=3`.

However when I read the file in ImageMagick I only see a single channel grayscale image, rather than an RGB apple that I am seeing in ImageJ. Perhaps they are abusing the tiff format. Do you have any guess how I can read such an image in ImageMagick?

**Comment by urban-warrior** [comment]
For a RGB image, we expect a photometric tag of 2 (RGB) however your image returns a photometric tag of 1 (Grayscale).  We do see an Apple but its grayscale.  Other TIFF programs we tried failed against your sample image in the same way.  Its likely ImageJ is writing the image in a non-standard way.

**Comment by jeroen** [comment]
OK thank you for looking into this. I should figure out what format they use exactly.
