### ISSUE TITLE
Migrate fuzzers from oss-fuzz to upstream!

### ISSUE THREAD

**Issue by alex** [ImageMagick/ImageMagick#933]
In https://github.com/google/oss-fuzz/pull/1040 we landed some fuzzers in the oss-fuzz. The next step is to migrate the build scripts and the fuzzer files into the upstream repo!

/cc @reaperhulk @dlemstra

**Comment by dlemstra** [comment]
Happy to see that this got merged. Are there some instructions available on how we should migrate everything into our repo?

**Comment by alex** [comment]
Based on how we did gnutls, I'd break it down into the following steps:

- [ ] Add `.cc` fuzzer targets to ImageMagick
- [ ] Remove them from `oss-fuzz` and change the `build.sh` script there to use the fuzzer targets in the ImageMagick repo
- [ ] Make the imagemagick build/CI compile, but not run, the fuzzer targets
- [ ] Figure out how to use the ImageMagick build system to build the fuzzer targets in oss-fuzz's `build.sh`

**Comment by alex** [comment]
We should probably also get more ImageMagick developers access to the OSS-Fuzz data.

**Comment by dlemstra** [comment]
@alex I will take a look at some of them later this week / weekend. Kinda swamped with other things right now. We are a very very small team so it might take a while before we take a look at them. I will filter out the ones that we need to look at and fix. Need to work through the 230 emails that were send to me first.

**Comment by alex** [comment]
FWIW, I'd recommend looking at just the ones that are still open in the bug tracker, a HUGE amount of those 230 were OOMs that were closed once we added the memory limit to the fuzzers.

**Comment by reaperhulk** [comment]
You can visit https://oss-fuzz.com to see current active (most of those emails are irrelevant now since the memory stuff has all auto-closed)

**Comment by alex** [comment]
Is everything upstreamed now? Are there any parts left?

**Comment by dlemstra** [comment]
Everything has been moved. Our travis build fails now but I will look at that tomorrow or tonight.

**Comment by alex** [comment]
Awesome! Let's make sure all the imagemagick core devs who want access have it!

**Comment by dlemstra** [comment]
Will submit a PR for the e-mail of the other core developer later tonight.

**Comment by alex** [comment]
Awesome!

**Comment by reaperhulk** [comment]
🙌 thanks for helping us out on this @dlemstra!
