### ISSUE TITLE
Identify Format Properties Reverted?

### ISSUE THREAD

**Issue by KOMON** [ImageMagick/ImageMagick#937]
I'm using the documentation [here](https://www.imagemagick.org/script/escape.php) which indicates that one of the long-form attributes I can use for `identify -format` is `%[interlace]`, saying that it was added in IM 7.0.3.8. I'm using 7.0.7-21, but I get the error: 

`identify: unknown image property "%[interlace]" @ warning/property.c/InterpretImageProperties/3883.`

Taking a look back, I can see that `%[interlace]` (along with several other properties) was removed with 76eb72fd36af6ff1a0343b6af84626fb8d10a579, simply titled 'Revert write mask mod'. 

Are we no longer able to access these properties without whatever that commit was reverting? Or were they just swept up in the process?

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
