### ISSUE TITLE
Latest Imagick 6.x version cannot "read" correctly from external streams in PHP.

### ISSUE THREAD

**Issue by waplet** [ImageMagick/ImageMagick#945]
### Description
When compiling php-imagick (3.4.3) with latest 6.x version of 6.9.9-33.  `Imagick::readImageFile($stream, $filename);` breaks with an ImagickException (might vary)
```
 improper image header `/tmp/magick-27744if7s-GBaken2' @ error/png.c/ReadPNGImage/4066
```
JPEG files breaks here https://github.com/ImageMagick/ImageMagick/blob/master/coders/jpeg.c#L1106

### Steps to Reproduce
```
$stream = fopen('locally_available_image' , 'r');
$stream = fopen('http://static.pexels.com/photos/248797/pexels-photo-248797.jpeg' , 'r'); // Thrown exception
// Same with S3 Stream wrappers

$im = new Imagick();
$im->readImageFile($stream, 'image.jpg');

dd($im->getImageWidth());
```

Although, f.e. ImageMagick 6.9.9-5 works fine.

### System Configuration

- ImageMagick version: 6.9.9-33
- Environment (Operating system, version and so on): Ubuntu 14.04 + PHP-FPM 7.0 + Imagick 3.4.3 compiled with Imagick 6.9.9-33
- Additional information: Vagrant virtualbox with macOS as host machine.

**Comment by urban-warrior** [comment]
Can you post a URL to an image that fails with your Imagick script?  We tried a number of example images and the script returned expected results.

**Comment by waplet** [comment]
Hey, the same one in "steps to reproduce" - http://static.pexels.com/photos/248797/pexels-photo-248797.jpeg

Updated additional information.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by copperseed** [comment]
Hello,

I'm having this same issue on version 7.0.7-22. Have tried many ideas to sort this out but none has worked.

**Comment by Placinta** [comment]
Can confirm. Seeing same issue with HEAD of imagick installed via brew in conjunction with pecl imagick 3.4.
Reported version: 
Version: ImageMagick 7.0.7-29 Q16 x86_64 2018-04-22

Could this be reopened?
