### ISSUE TITLE
composite Difference to same file yields a difference!=0

### ISSUE THREAD

**Issue by andk** [ImageMagick/ImageMagick#947]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
### Description

I have found a PNG file p1.png for which the command

``` text
  composite -compose Difference p1.png p1.png p1d.png
```
produces a not completely black image. Expected is a perfectly black image.

### Steps to Reproduce

The following textblock is a uuencoded PNG file. You can feed the text to uudecode to get the PNG with the name p1.png in the current directory:

``` text
begin-base64 644 p1.png
iVBORw0KGgoAAAANSUhEUgAAAAoAAAAHCAMAAAAGcixRAAAABGdBTUEAALGP
C/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3Cc
ulE8AAAAdVBMVEXM6I2g1Cn5/PHz+uO+4X7K543v+OT4/PGOyiqm1HK94I/Y
7Mh9wTuKxWLF4qyNx1ea0hz///+W0B2QzB2RzR2LyR2Hxx6Bwx7Z7qmCxB98
wR93viCm1zdyuyFtuCFotSLS65tjsyNdryOg1CperyNYrCNTqSTF8DaWAAAA
EHRSTlP+/v7+/v7+/v7+/v7+/v7+czrRdgAAAAFiS0dEEeK1PboAAAAJb0ZG
cwAAAAgAAAAJAOe7j+oAAAAJcEhZcwAAAGAAAABgAPBrQs8AAAAHdElNRQfi
AQ8OExX096G8AAAACXZwQWcAAALQAAAQAACMVRN/AAAARklEQVQI1x3GRxKA
IBAEwDVnmTErKub/P1GKPrUIAM+nJQHQtKEro64fxpichEk6LzojVyFzve2m
OGDL0pxXdbvWz/sp4AepRgUFovG8MgAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAx
OC0wMS0xNVQxNToxNjo1MyswMTowMGQjYbwAAAAldEVYdGRhdGU6bW9kaWZ5
ADIwMTgtMDEtMTVUMTU6MTY6NTMrMDE6MDAVftkAAAAAAElFTkSuQmCC
====
```

To verify, that the file has been translated correctly, compare the output of identify with mine:

``` text
% identify p1.png 
p1.png PNG 10x7 720x4096+8+9 8-bit sRGB 537B 0.000u 0:00.000
```

Now run the command

``` text
  composite -compose Difference p1.png p1.png p1d.png
```

which produces the file p1d.png.

Now analyse the file p1d.png with whichever means you find convenient and see that there are non-black pixels in it. I tried it with netpbm because it provides ascii output:

``` text
% /usr/bin/pngtopnm p1d.png|ppmhist 
   r     g     b         lum     count                                     
 ----- ----- -----      -----   -------
     0     0     0          0        54
     2     2     2          2         5
     1     2     1          2         5
     2     2     1          2         3
     1     2     0          1         3
```

### System Configuration

- ImageMagick version: I have verified the behaviour with
  - current git repository (ImageMagick 7.0.7-22 Q16 x86_64 2018-01-15), compiled after commit f59a9b1
  - debian jessie imagemagick: Package: imagemagick, Version: 8:6.8.9.9-5+deb8u11

- Environment (Operating system, version and so on):
  - Debian jessie x86_64
  - Linux  3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux

- Additional information: I have also tried with this same image converted from sRGB to RGB but got a similar result

**Comment by urban-warrior** [comment]
You are getting expected results.  If you want pure black, turn off the alpha channel to prevent blending per the SVG specification (e.g. -alpha off).

```
   Composition based on the SVG specification:

   A Composition is defined by...
      Color Function :  f(Sc,Dc)  where Sc and Dc are the normizalized colors
      Blending areas :  X = 1     for area of overlap, ie: f(Sc,Dc)
                        Y = 1     for source preserved
                        Z = 1     for canvas preserved

   Conversion to transparency (then optimized)
      Dca' = f(Sc, Dc)*Sa*Da + Y*Sca*(1-Da) + Z*Dca*(1-Sa)
      Da'  = X*Sa*Da + Y*Sa*(1-Da) + Z*Da*(1-Sa)

   Where...
      Sca = Sc*Sa     normalized Source color divided by Source alpha
      Dca = Dc*Da     normalized Dest color divided by Dest alpha
      Dc' = Dca'/Da'  the desired color value for this channel.

   Da' in in the follow formula as 'gamma'  The resulting alpla value.

   Most functions use a blending mode of over (X=1,Y=1,Z=1) this results in
   the following optimizations...
      gamma = Sa+Da-Sa*Da;
      gamma = 1 - QuantumScale*alpha * QuantumScale*beta;
      opacity = QuantumScale*alpha*beta;  // over blend, optimized 1-Gamma

   The above SVG definitions also define that Mathematical Composition
   methods should use a 'Over' blending mode for Alpha Channel.
   It however was not applied for composition modes of 'Plus', 'Minus',
   the modulus versions of 'Add' and 'Subtract'.

   Mathematical operator changes to be applied from IM v6.7...

    1) Modulus modes 'Add' and 'Subtract' are obsoleted and renamed
       'ModulusAdd' and 'ModulusSubtract' for clarity.

    2) All mathematical compositions work as per the SVG specification
       with regard to blending.  This now includes 'ModulusAdd' and
       'ModulusSubtract'.
```

**Comment by andk** [comment]
Thank You for your enlightening explanation! So easy, and still I could not figure it out.
