### ISSUE TITLE
Detect White Spaces and Drag Photos

### ISSUE THREAD

**Issue by dexterhussain** [ImageMagick/ImageMagick#949]
I have a problem that I am making an exam system for which I need that a user can drag small pictures on a bigger picture which will show as a question and correct sequence or answer can be found. 
I am unable to find any solution using ImageMagick in php. Please help.

**Comment by fmw42** [comment]
Can you provide an example picture of what you want to do? I am not sure I understand what the background contains and what the foreground image contains in terms of questions and answers. Imagemagick can overlay one image onto another. See https://www.imagemagick.org/Usage/compose/#compose. PHP Imagick has a similar ability. See http://php.net/manual/en/imagick.compositeimage.php. The uploading or dragging and dropping is not something Imagemagick can do. That will need PHP and/or Javascript.

**Comment by dexterhussain** [comment]
![image](https://user-images.githubusercontent.com/8198511/35083000-8daf23b2-fc3e-11e7-8751-2561d7aca07c.png)
Suppose this image Now the Blue Things are the routers I want to place them outside the picture and let the user drag the picture inside the main picture and if smaller picture is at correct position then correct answer would be checked from DB. i will allocate white paces to place the smaller picture

**Comment by fmw42** [comment]
Imagemagick can only composite one picture on the other at user specified coordinates. The rest is outside its abilities and would need to be done with other tools such as PHP and Javascript.

Regards,

Fred

**Comment by dexterhussain** [comment]
Can you Please help me as I cannot figure out how to do this with PHP?

**Comment by fmw42** [comment]
My scripts only run with PHP exec() and not Imagemick.

See my Pointers for use on my home page at http;//www.fmwconcepts.com/imagemagick/index.html <http://www.fmwconcepts.com/imagemagick/index.html>.

You take  command line that runs the script and just put the whole command line into the PHP exec(....) function

If you cannot figure that out I will help further tomorrow. It is too late for me now to think properly.

Fred

**Comment by dexterhussain** [comment]
I have checked the page but sorry i cannot understand how i can use it. If you can help it will be great

**Comment by fmw42** [comment]
I do not know how much help I can give. My apologies, but my scripts are not relevant to your issue. I do not know PHP that well. But in Imagemagick, you can overlay one image onto another at a specific position.

Large Image:

![logo](https://user-images.githubusercontent.com/13458218/35112852-3c7c93f8-fc34-11e7-8e95-a3062885b7dc.jpg)

Small Image:

![rose](https://user-images.githubusercontent.com/13458218/35112870-4c12b1da-fc34-11e7-87fa-25f426a633e2.jpg)

Command to place the small image's top left corner at coordinates 50,200 relative to the top left corner of the large image:

convert logo.jpg rose.jpg -gravity northwest -geometry +50+200 -compose over -composite logo_rose_comp.jpg

![logo_rose_comp](https://user-images.githubusercontent.com/13458218/35112911-767208d6-fc34-11e7-82d4-f7b2456de821.jpg)

In PHP, which I do not know well, I think this would work using PHP exec() command.

```
<?php
exec("convert logo.jpg rose.jpg -gravity northwest -geometry +50+200 -compose over -composite logo_rose_comp.jpg 2>&1",$out,$returnval);
foreach($out as $text)
{echo "$text<br>";}
?>

```

I do not know PHP Imagick. I can only refer you to the link to the equivalent composite command. See http://php.net/manual/en/imagick.compositeimage.php

I hope that helps. Perhaps someone on the Imagemagick Discourse Server Imagick forum can help further with Imagick.

**Comment by dexterhussain** [comment]
THis is very beautiful this solves my problem. Can just clear me one thing how i can get the Position of small image on the large one using imagick?

**Comment by dexterhussain** [comment]
I mean how i can drag the small image over the large one?

**Comment by fmw42** [comment]
I am sorry, I do not know Imagick. In my command you have to provide the coordinates. This would be something that you would have to do with say Javascript to get the coordinates and then feed that to PHP to use in your Imagick or even in the Imagemagick command. Imagick is not interactive. So you cannot measure with it. But there are other Javascript and Jquery tools that can probably do that.

**Comment by fmw42** [comment]
Dragging is not part of Imagick or Imagegick. They are not interactive. You would need to use something like AJAX with Javascript or Jquery to do that most likely. Unfortunately, I am not an expert on any of those other tools. You should post to one of those forums about that.
