### ISSUE TITLE
Make dependency failure due to wrong file times in tarball

### ISSUE THREAD

**Issue by cpansprout** [ImageMagick/ImageMagick#950]
My system information:
```
$ uname -a
Darwin Treebeard.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:26:45 PDT 2012; root:xnu-1699.32.7~1/RELEASE_I386 i386
```
I downloaded the latest ImageMagick.tar.gz from imagemagick.org (version 7.0.7), and ran `./configure` and `make`.  Make was not happy:
```
$ make
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/sh /ImageMagick-7.0.7-21/config/missing autoconf
/ImageMagick-7.0.7-21/config/missing: line 81: autoconf: command not found
WARNING: 'autoconf' is missing on your system.
         You should only need it if you modified 'configure.ac',
         or m4 files included by it.
         The 'autoconf' program is part of the GNU Autoconf package:
         <http://www.gnu.org/software/autoconf/>
         It also requires GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make: *** [configure] Error 127
```
So I ran `make -d` and found, near the end of the output:
```
      Prerequisite `version.sh' is newer than target `configure'.
      Prerequisite `gitversion.sh' is newer than target `configure'.
```
I set the time on those to file back to another millenium:
```
$ touch -t 197001010000 version.sh gitversion.sh 
```
And then I was able to run make.

So the dates on the files in the tarball are not set correctly.

**Comment by cpansprout** [comment]
Do you have a release guide?  If so, I could write a patch for it to prevent such mistakes in future.

**Comment by cpansprout** [comment]
BTW, ImageMagick.tar.gz unpacks as ImageMagick-7.0.7-21/ (with a -21 suffix), in case that makes a difference.

**Comment by urban-warrior** [comment]
Unfortunately, we cannot reproduce the problem.  Under Ubuntu, we typed:

```
$ wget https://www.imagemagick.org/download/ImageMagick.tar.gz
$ tar xvf ImageMagick.tar.gz
$ cd ImageMagick-7.0.7-21
$ ./configure
$ make
```
The distribution built without complaint.

**Comment by cpansprout** [comment]
Do you have autoconf installed on that machine?  That (I imagine) would allow it to build without complaint, because the Makefile tries to run autoconf to regenerate configure.  I do not have autoconf installed.

I tried unpacking the tarball again.  This is what I see for the file times:
```
$ ls -lT configure gitversion.sh version.sh 
-rwxr-xr-x@ 1 neo  wheel  1250601 Jan 19 18:21:43 2018 configure
-rwxr-xr-x@ 1 neo  wheel      221 Jan 19 18:21:49 2018 gitversion.sh
-rw-r--r--@ 1 neo  wheel     1706 Jan 19 18:21:47 2018 version.sh
```
As you can see, those two .sh files are newer than configure.  make sees that and tries to regenerate configure.

Would it help if I put the generated Makefile in a gist?

**Comment by cpansprout** [comment]
Ugh! I see the problem.  Apple’s Archive Utility is not setting the time stamps properly.  The time for each file is the time it was _extracted_.  When I use tar, I get no problem:
```
$ ls -lT configure gitversion.sh version.sh 
-rwxr-xr-x@ 1 neo  wheel  1250601 Jan  6 06:24:53 2018 configure
-rwxr-xr-x@ 1 neo  wheel      221 Jan  6 06:18:43 2018 gitversion.sh
-rw-r--r--@ 1 neo  wheel     1706 Jan  6 06:18:43 2018 version.sh
```
I’ll just have to remember not to double-click tarballs any more.  I can’t believe an Apple product would be so buggy.  (Well, actually I can....)
