### ISSUE TITLE
Fails to detect libpng on Darwin

### ISSUE THREAD

**Issue by cpansprout** [ImageMagick/ImageMagick#952]
```
$ uname -a
Darwin Treebeard.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:26:45 PDT 2012; root:xnu-1699.32.7~1/RELEASE_I386 i386
```
I am using ImageMagick-7.0.7-21 (the ImageMagick.tar.gz I just downloaded from imagemagick.org).
```
$ ./configure
...snipped...
checking for PNG... no
...snipped...
```
I have libpng15 installed (see below).  ImageMagick 6.8.3-10 finds it with no problem.  Incidentally, pkg-config is not installed.
```
$ ls /usr/local/lib | grep png
libpng.a
libpng.dylib
libpng.la
libpng15.15.dylib
libpng15.a
libpng15.dylib
libpng15.la
$ ls /usr/local/include | grep png
libpng15
png.h
pngconf.h
pnglibconf.h
```

**Comment by urban-warrior** [comment]
ImageMagick prefers pkg-config when search for delegate libraries.  As such, we updated the configure script to validate the PNG delegate library with pkg-config.  You must install libpng15.pc and have it in your PKG path for ImageMagick to find the PNG delegate library.

**Comment by cpansprout** [comment]
If that means that I have to have pkg-config installed, could you document that in the install* files?

**Comment by urban-warrior** [comment]
Done.  Allow 24 hours for the update to mirror world-wide.
