### ISSUE TITLE
The option -strip interferes with metadata-writing options on PNG

### ISSUE THREAD

**Issue by cu98gbmx** [ImageMagick/ImageMagick#954]
I often encounter files that contain a bunch of privacy-infringing unwanted metadata but lack desired metadata.  To handle such files, I just remove all the erasable metadata by the -strip option, and then add the desired metadata by appropriate options such as -density and -units.

If the output file is TIFF, then the -strip option nicely acts and does not interfere with -density or -units; hence, it works on a single command line without creating an intermediary temporary file, as shown below.

    # TIFF -> TIFF : success
    magick img.tif -strip -depth 1 -define quantum:polarity=min-is-white -units PixelsPerInch -density 300 -compress LZW img_Strip_AddDpi.tif
    
    # or
    
    # PNG -> TIFF : success
    magick img.png -strip -depth 1 -define quantum:polarity=min-is-white -units PixelsPerInch -density 300 -compress LZW img_png_Strip_AddDpi.tif

(See below for how to display metadata.)

However, if the output file is PNG, then the -strip option prevents -density and -units from writing their metadata.

    # PNG -> PNG : failure
    magick img.png -strip -depth 1 -define quantum:polarity=min-is-white -units PixelsPerInch -density 300 -compress LZW img_Strip_AddDpi.png
      # The density and unit fail to be written into the output.

In this case, my workaround is to divide the procedure into two steps, that is, to use -strip alone first, creating an intermediary temporary file, and let -density and -units act on the temporary file.

    # 2-Step Workaround
    magick img.png -strip -depth 1 -define quantum:polarity=min-is-white -compress LZW img_OnlyStrip.png
    #
    magick img_OnlyStrip.png -depth 1 -define quantum:polarity=min-is-white -units PixelsPerInch -density 300 -compress LZW img_Strip_AddDpi_2Steps.png

It may be confusing to use the metadata-removal option -strip with metadata-writing options like -density and -units at the same time.  However, as I pointed out, there are situations that demand -strip to nicely and smartly act with other metadata-writing options.

The man page of magick and the www/command-line-options.htm do not mention what -strip is supposed to do when used with other metadata-writing options.

I think that it should be first defined that, if -strip precedes other metadata-writing options, -strip should not prevent them from writing their metadata (and, of course, -strip should remove all the erasable existing metadata passed from the input file).  Then, magick should be implemented accordingly, and the man page and www/command-line-options.htm should be adjusted accordingly.

### System Configuration

* ImageMagick-7.0.7-21

* tiff-4.0.8
* libpng-1.6.31
* zlib-1.2.11

* Mac OS X

### How to Extract Metadata

Since not only the developers of ImageMagick but also anyone can read this post, it is possible that people who do not know how to extract metadata will read this post.  So, I will show how.  (Developers of ImageMagick may skip the rest of this post.)

    # Show metadata
    magick identify -verbose FILE
    
    # Show metadata relevant to -density and -units
    magick identify -verbose FILE | grep -iE '(Resolution|Unit|Print size)'

Note that the options "-units PixelsPerInch -density 300" in the example command statements that appeared near the beginning of this post mean "300 dpi".  DPI stands for "dots per inch", and determines "pixels-per-unit resolution" or "physical pixel dimension".  TIFF can deal with inch and can store dpi.  However, PNG deals with only metric, and stores only dpm (dots per meter).  So, magick internally coverts "300 dpi" into dpm, and saves the dpm into the PNG file.  300 dpi is approximately 11811 dpm (dots per meter) or 118.11 dpcm (dots per centimeter).  Therefore, "magick identify -verbose" displays "11811" or "118.11" instead of "300" for the resolution if FILE is a PNG.  (By the way, "11811 dpm" is exactly "299.9994 dpi".)

    # To explicitly convert 300 dpi into dpm
    bc <<< 'scale=16; 300/0.0254'
    
    # To convert 11811 dpm into dpi
    bc <<< '11811*0.0254'

### ExifTool

Though "magick identify -verbose" shows metadata, it focuses on the kind of metadata useful in order to draw the image, and hence likely neglects to reveal privacy-infringing unwanted metadata embedded in the image file.

ExifTool by Phil Harvey can display privacy-infringing unwanted metadata as well.  It is available at
http://owl.phy.queensu.ca/~phil/exiftool/

    # Show metadata
    exiftool -S FILE
    
    # Show metadata relevant to -density, -units, -depth,
    # polarity (photometric interpretation) and -compress
    { op='-PhotometricInterpretation -BitsPerSample -SamplesPerPixel' #tif
    op+=' -XResolution -YResolution -ResolutionUnit' #tif
    op+=' -ColorType -BitDepth -PixelsPerUnitX -PixelsPerUnitY -PixelUnits' #png
    op+=' -Compression';}
    exiftool -S $op FILE

**Comment by glennrp** [comment]
Strip was designed to remove all metadata.  If you don[t liike the way strip behaves donn't use it.

**Comment by ClarkChalmers** [comment]
i often wonder how people would feel today realizing they used to act like a snob, but it defeats the purpose of being a snob to say they are capable of retrospection.
w/ due thanks to @cu98gbmx for the informative post.
