### ISSUE TITLE
assertion error in RelinquishMagickResource

### ISSUE THREAD

**Issue by benquike** [ImageMagick/ImageMagick#955]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Assertion error in line 1009 in `MagickCore/resource.c`(https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/resource.c#L1009)

### Steps to Reproduce
1. checkout the latest code of this repo
```
git clone https://github.com/ImageMagick/ImageMagick.git
```
2. build the source code
```
cd ImageMagick.git
./configure
make
``` 
3. Download [crash_input.zip](https://github.com/ImageMagick/ImageMagick/files/1655056/crash_input.zip) and run the following command
```
unzip crash_input.zip
utilities/magick crash_input /dev/null
```

### System Configuration

- ImageMagick version:  82c58c138e2ffc1f170db711b07627ee621c2a22
- Environment (Operating system, version and so on): 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
```
and 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
- Additional information:
[crash_input.zip](https://github.com/ImageMagick/ImageMagick/files/1655056/crash_input.zip)

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
