### ISSUE TITLE
segfault on netcup's logo

### ISSUE THREAD

**Issue by MichaelDaum** [ImageMagick/ImageMagick#958]
### Description
Processing the logo from https://www.netcup.de/design/logo_head.png will result in a segfault with
a message: "corrupted size vs. prev_size"

### Steps to Reproduce
- wget https://www.netcup.de/design/logo_head.png
- identify logo_head.png

### System Configuration
- image magic 7.0.7-22
- ubuntu 14.04 LTS

**Comment by urban-warrior** [comment]
We can identify, convert, and display the logo without complaint with the latest ImageMgagick 7.0.7-23 Beta.  Look for a release of 7.0.7-23 later this week.
