### ISSUE TITLE
Figure out why some encoders/decoders aren't making progress in OSS-Fuzz

### ISSUE THREAD

**Issue by alex** [ImageMagick/ImageMagick#962]
There are a handful of encoders/decoders that aren't accomplishing anything in OSS-Fuzz. You can find them all by looking at https://oss-fuzz.com/v2/fuzzer-stats/by-fuzzer/2018-01-20/2018-01-26/fuzzer/libFuzzer/job/libfuzzer_asan_imagemagick and seeing which ones have a tiny corpus (most importantly the ones with a corpus of 2).

We should either get them working properly, or skip them in `encoder_list.cc`.

I looked at SCREENSHOT, and it seems to be a case that we should skip -- it only runs on Windows or with X11, and mostly seems to stress OS integration, not a parser.

**Comment by dlemstra** [comment]
Adding an exclude list sounds like a good plan and I just pushed a patch for this. One that I don't understand is the `bgr` encoder. Will need to investigate this.

**Comment by alex** [comment]
Yes, they do: https://www.google.com/about/appsecurity/patch-rewards/

**Comment by dlemstra** [comment]
Will need to think how we can separate certain coders. One that might needs it's own version would be the `xc` coder. It uses the filename of the image to extract a color and use that as the background of the image. Will add a fuzzer that only uses the `Data` to create a string and use that as the color of the image. How can we give the fuzzer a hint that we only want strings @alex?

**Comment by alex** [comment]
There's no way, we just have to trust that over time the fuzzer "learns" that only certain values generate meaningful coverage gains.

**Comment by dlemstra** [comment]
I hope this will help with some of the fuzzers: https://github.com/ImageMagick/ImageMagick/commit/f8e21539d66697ab692c5545396243654744a33c

**Comment by reaperhulk** [comment]
For reference here's most of the fuzzers with tiny corpuses:

* cmyk
* cmyka
* dng
* fax
* g3
* g4
* gradient
* gray
* hald
* label
* map
* mono
* mpc
* pattern
* plasma
* radial-gradient
* rgb
* rgba
* rgbo
* screenshot
* six
* stegano
* uyvy
* xc
* ycbcr
* yuv

Several of these have already been discussed (and I removed null since it is now explicitly dropped from the fuzzer list), but it's hopefully easier to look at the list here than on that page.

BTW, the huffman_decode fuzzer also only has two seed files, so we may want to do something there as well.

**Comment by dlemstra** [comment]
@reaperhulk I have modified your post and marked the ones that I already did something for. Not sure how long it will take before my patches will take effect.

@alex  and @reaperhulk I am planning to submit a patch reward for the OSS-fuzzing later this week. Are you guys okay with us doing this even though you two did a lot of work to make this possible?

**Comment by reaperhulk** [comment]
@dlemstra I submitted for initial integration already (as that is a prerequisite for submitting for ideal) but in my application I asked them what the process for splitting the award would be since you definitely deserve it!

**Comment by dlemstra** [comment]
@reaperhulk We should also make sure that @alex also gets something for his involvement.
