### ISSUE TITLE
newlines in file names break montage html image map index_map.shtml

### ISSUE THREAD

**Issue by idallen** [ImageMagick/ImageMagick#966]
### Prerequisites

- [y] I have written a descriptive issue title
- [n] I have verified that I am using the latest version of ImageMagick
- [y] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
FIle names containing newline/linefeed characters break montage image map links in the generated index files.

### Steps to Reproduce
```
$ ls -b
a\nb\nc.jpg
$ montage *.jpg index.html
$ cat index_map.shtml
<map id="index" name="index">
  <area href="a" shape="rect" coords="0,0,127,125" alt="" />
  <area href="b" shape="rect" coords="0,126,127,251" alt="" />
  <area href="c.jpg" shape="rect" coords="0,252,127,377" alt="" />
</map>
```
### System Configuration

- ImageMagick version:  ImageMagick 6.8.9-9 Q16 x86_64 2017-07-31 http://www.imagemagick.org
- Environment (Operating system, version and so on):  Ubuntu 16.04.3 LTS

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick within a week or two.

**Comment by idallen** [comment]
This is not fixed in `ImageMagick 7.1.0-25 Q16-HDRI x86_64 2022-02-12`.  The two generated index files contain actual newlines in the `<area href=` file names instead of the `urlencoded` escape sequence `%0A` and thus the actual newlines disappear when read by the browser (Firefox) and all the links are thus wrong.
~~~~~
$ ls -b
a\nb\nc.jpg

$ montage *.jpg index.html

$ cat index_map.shtml
<map id="index" name="index">
  <area href="a
b
c.jpg" shape="rect" coords="0,0,127,125" alt="" />
</map>

$ cat index.html 
<?xml version="1.0" encoding="US-ASCII"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<title>index</title>
</head>
<body style="text-align: center;">
<h1>index.html</h1>
<div>
<img usemap="#index" src="index.png" style="border: 0;" alt="Image map" />
<map id="index" name="index">
  <area href="a
b
c.jpg" shape="rect" coords="0,0,127,125" alt="" />
</map>
</div>
</body>
</html>
~~~~~

**Comment by idallen** [comment]
I looked at the "fix" for the newline problem, and all the fix did was change the newline problem into a `\377` problem.
~~~~~
$ /bin/ls -b
a\377b\377c.jpg

$ montage *.jpg index.html

$ cat index_map.shtml 
<map id="index" name="index">
  <area href="a" shape="rect" coords="0,0,127,125" alt="" />
  <area href="b" shape="rect" coords="0,126,127,251" alt="" />
  <area href="c.jpg" shape="rect" coords="0,252,127,377" alt="" />
</map>
~~~~~

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick within a day or two.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ within a day or two..

**Comment by idallen** [comment]
The fix also doesn't work for all the other special characters that might be in file names, e.g. TAB and FF.
The file name has to be `urlencoded` to escape **all** special characters.
~~~~~
$ /bin/ls -b
a\tb\tc.jpg

$ montage *.jpg index.html

$ cat index_map.shtml 
<map id="index" name="index">
  <area href="a b       c.jpg" shape="rect" coords="0,0,127,125" alt="" />
</map>
~~~~~
~~~~~
$ /bin/ls -b
a\fb\fc.jpg

$ montage *.jpg index.html

$ cat index_map.shtml 
<map id="index" name="index">
  <area href="a
               b
                c.jpg" shape="rect" coords="0,0,127,125" alt="" />
</map>
~~~~~

**Comment by idallen** [comment]
Another example of a failure to `urlencode` the file name:
~~~~~
$ ls
a"b"c.jpg

$ montage *.jpg index.html

$ cat index_map.shtml 
<map id="index" name="index">
  <area href="a"b"c.jpg" shape="rect" coords="0,0,127,125" alt="" />
</map>
~~~~~

**Comment by idallen** [comment]
Reference for URL Encoding: <https://www.urlencoder.io/>

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by idallen** [comment]
> Thanks for the problem report. We can reproduce it and will have a patch to fix it in the GIT main branch @ https://github.com/ImageMagick/ImageMagick later today. The patch will be available in the beta releases of ImageMagick @ https://imagemagick.org/download/beta/ by sometime tomorrow.

The fix breaks file names containing spaces.  Name `abc def.jpg` is incorrectly changed to `abc+def.jpg` (instead of to `abc%20def.jpg`) and is not found.
The code unnecessarily escapes many characters that do not need to be escaped.
See *2.3 Unreserved Characters* in <https://www.ietf.org/rfc/rfc2396.txt>.

**Comment by urban-warrior** [comment]
Thanks for the reference.  We added the complete list of unreserved characters beyond alpha-numerics.

**Comment by idallen** [comment]
I don't think you fixed the `\377` problem (from above, two days ago):

> I looked at the "fix" for the newline problem, and all the fix did was change the newline problem into a `\377` problem.
> 
> ```
> $ /bin/ls -b
> a\377b\377c.jpg
> 
> $ montage *.jpg index.html
> 
> $ cat index_map.shtml 
> <map id="index" name="index">
>   <area href="a" shape="rect" coords="0,0,127,125" alt="" />
>   <area href="b" shape="rect" coords="0,126,127,251" alt="" />
>   <area href="c.jpg" shape="rect" coords="0,252,127,377" alt="" />
> </map>
> ```

**Comment by urban-warrior** [comment]
The problem is fixed.  We updated the formats page for HTML to alert users  that \377 cannot appear in a filename.  Its a reserved character.   We need a sentinel for separating the filenames in the montage directory.  Two UTF-8 characters are reserved \0 & \377.  If you can suggest  a more suitable UTF-8 sentinel, let us know.  It would have to be a character that is provably unlikely to show up in a filename as compared to our choice of \377.

**Comment by idallen** [comment]
> \377 cannot appear in a filename. Its a reserved character. 

You can code so that users don't need to know about your internal reserved `\377` character.  The usual way to do this sort of thing is to escape the reserved character on input and de-escape it on output so that you don't have to document a bug.

I don't know the code, so I don't know what kind of escaping is easiest.

Perhaps on input when you read `\377` you change it to `\376\375` internally and when you read `\376` you change it to `\376\376`.  On output, reverse the process.  Then you don't need to reserve anything other than `\0`, there is no bug, and no documentation change is needed.

If this is too complicated, then please make the program reject file names containing the `\377` reserved character.  Don't just document it; make the program alert the user to its own limitations.  (Of course, the preference is to fix the code not to have the limitation.)

**Comment by urban-warrior** [comment]
We'll reject filenames with \377 characters, otherwise we will break legacy MIFF files.  Thanks for bringing this issue to our attention.
