### ISSUE TITLE
coders/sixel.c goes to infinite loop.

### ISSUE THREAD

**Issue by ssgskid** [ImageMagick/ImageMagick#968]
## Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched open and closed issues to ensure it has not already been reported

## Description

https://github.com/ImageMagick/ImageMagick/blob/0446b210f31ed20f3d600687819d96432e60e099/coders/sixel.c#L429-L435

When `repeat_count` is given as a large number such as `0x5fffffff`, `nx` and `ny` is always less than `posision_x + repeat_count` because `nx` and `ny` can be overflowed and becomes zero. Thus, the loop never endes, and leads to infinite loop.

## Steps to Reproduce

    gdb-peda$ r ./timeout.sixel ./1
    Starting program: /usr/bin/convert ./timeout.sixel ./1
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    ^C
    Program received signal SIGINT, Interrupt.
    
    [----------------------------------registers-----------------------------------]
    RAX: 0x5555555a ('ZUUU')
    RBX: 0x5555555a ('ZUUU')
    RCX: 0xff 
    RDX: 0x5 
    RSI: 0x7ffff3b3e82c --> 0x2000200020002 
    RDI: 0x6280b1 --> 0x633333333333333 
    RBP: 0x0 
    RSP: 0x7fffffff6360 --> 0x0 
    RIP: 0x7ffff3921c40 (<sixel_decode+1648>:	add    r13d,r13d)
    R8 : 0x4 
    R9 : 0x4 
    R10: 0x519 
    R11: 0x7ffff70450f0 (<__ctype_b_loc>:	mov    rax,QWORD PTR [rip+0x395d21]        # 0x7ffff73dae18)
    R12: 0x6280b9 --> 0x606f42b04464953 
    R13: 0x0 
    R14: 0x0 
    R15: 0x628030 --> 0x2606392706060606
    EFLAGS: 0x297 (CARRY PARITY ADJUST zero SIGN trap INTERRUPT direction overflow)
    [-------------------------------------code-------------------------------------]
       0x7ffff3921c39 <sixel_decode+1641>:	mov    eax,DWORD PTR [rsp+0x50]
       0x7ffff3921c3d <sixel_decode+1645>:	jmp    0x7ffff3921c46 <sixel_decode+1654>
       0x7ffff3921c3f <sixel_decode+1647>:	nop
    => 0x7ffff3921c40 <sixel_decode+1648>:	add    r13d,r13d
       0x7ffff3921c43 <sixel_decode+1651>:	add    r14d,r14d
       0x7ffff3921c46 <sixel_decode+1654>:	cmp    r13d,eax
       0x7ffff3921c49 <sixel_decode+1657>:	jl     0x7ffff3921c40 <sixel_decode+1648>
       0x7ffff3921c4b <sixel_decode+1659>:	cmp    r14d,edx
    [------------------------------------stack-------------------------------------]
    0000| 0x7fffffff6360 --> 0x0 
    0008| 0x7fffffff6368 --> 0x1 
    0016| 0x7fffffff6370 --> 0x7ffff351f010 --> 0x0 
    0024| 0x7fffffff6378 --> 0x800 
    0032| 0x7fffffff6380 --> 0x7fffffff641c --> 0x32dcd500000001 
    0040| 0x7fffffff6388 --> 0x7fffffff6420 --> 0x32dcd5 
    0048| 0x7fffffff6390 --> 0x80055555555 
    0056| 0x7fffffff6398 --> 0x400000004 
    [------------------------------------------------------------------------------]
    Legend: code, data, rodata, value
    Stopped reason: SIGINT
    0x00007ffff3921c40 in sixel_decode () from /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/sixel.so
    gdb-peda$ bt
    #0  0x00007ffff3921c40 in sixel_decode ()
       from /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/sixel.so
    #1  0x00007ffff39224aa in ?? () from /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/modules-Q16/coders/sixel.so
    #2  0x00007ffff79a48e8 in ReadImage () from /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2
    #3  0x00007ffff79a597b in ReadImages () from /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2
    #4  0x00007ffff763ef88 in ConvertImageCommand () from /usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.2
    #5  0x00007ffff76ab527 in MagickCommandGenesis () from /usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.2
    #6  0x0000000000400877 in ?? ()
    #7  0x00007ffff7037830 in __libc_start_main (main=0x400830, argc=0x3, argv=0x7fffffffe568, init=<optimized out>, 
        fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffe558) at ../csu/libc-start.c:291
    #8  0x00000000004008d9 in ?? ()

## System Configuration

- ImageMagick version: tested in 7.0.7-22. This will probably be also triggered in the latest master branch.
- Environment (Operating system, version and so on): Ubuntu 14.04
- Additional information:

[timeout.zip](https://github.com/ImageMagick/ImageMagick/files/1680861/timeout.zip)

Found by Choongwoo Han and Kyeongseok Yang, Naver Security Team

**Comment by urban-warrior** [comment]
We verified that your image converts in less than a second with the latest ImageMagick beta, ImageMagick-7.0.7-23.

**Comment by ssgskid** [comment]
I checked it in the beta version you mentioned, and found  that the vulnerability still exists. It seems that the program does not recognize the sixel file format as shown in the attached picture. Do you have a plan to stop supporting the sixel file format?

![image](https://user-images.githubusercontent.com/23254743/36008661-c496da4c-0d8b-11e8-9f10-dba9e628bc0a.png)

**Comment by dlemstra** [comment]
The message that you are seeing is a warning that an xml file could not be loaded. That is not a warning that the file format is not supported. I can also load your file without any issues:

```
I:\sixel>convert -version
Version: ImageMagick 7.0.7-23 Q16 x64 2018-02-05 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 191225835
Features: Debug Cipher DPC HDRI Modules OpenCL OpenMP
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr openexr pangocairo png ps raw rsvg tiff webp xml zlib

I:\sixel>identify timeout.sixel
timeout.sixel SIXEL 5x5 5x5+0+0 24-bit sRGB 3c 154B 0.016u 0:00.015

I:\sixel>convert -bench timeout.sixel null:
Performance[1]: 0i 0.000ips 1.000e 0.000u 0:00.000
Performance[2]: 0i 0.000ips 0.500e 0.000u 0:00.000
Performance[3]: 0i 0.000ips 0.500e 0.000u 0:00.000
Performance[4]: 0i 0.000ips 0.500e 0.000u 0:00.000
Performance[5]: 0i 0.000ips 0.500e 0.000u 0:00.000
Performance[6]: 0i 0.000ips 0.500e 0.000u 0:00.000
Performance[7]: 0i 0.000ips 0.500e 0.000u 0:00.000
Performance[8]: 0i 0.000ips 0.500e 0.000u 0:00.000
```
