### ISSUE TITLE
PICT file unreadable despite being seemingly valid

### ISSUE THREAD

**Issue by cburschka** [ImageMagick/ImageMagick#970]
The file that is attached as [tree.zip](https://github.com/ImageMagick/ImageMagick/files/1683880/tree.zip) appears to be a valid PICT file, and can be opened on MacOS Sierra with Preview 9.0 (909.18). Based on the brief format documentation at http://www.fileformat.info/format/macpict/egff.htm, it looks like the header is intact - it starts with the 2-byte file size, and then contains 8 bytes that encode the dimensions of the image.

However, attempting to use `convert` or `identify` on the file fails with `improper image header 'tree.pict' @ error/pict.c/ReadPICTImage/893`.

Is this version of the format not supported by ImageMagick?

Using Preview to export to PDF and then convert it to PNG yields the following file (which is rotated by 90 degrees counter-clockwise during the PDF export, but is otherwise correct):
![tree](https://user-images.githubusercontent.com/1448001/35651221-339d9588-06df-11e8-9438-481626e8e756.png)

Edit: Replaced gist link with zip attachment.

**Comment by cburschka** [comment]
Update: On a hunch based on a small remark in Wikipedia, I padded the file with 512 0-bytes.

> By saving the resulting byte stream as a resource, a PICT resource resulted, which could be loaded and played back at any time. The same stream could be saved to a data file on disk (**with 512 bytes of unused header space added**) as a PICT file.

The padded file is readable by ImageMagick. It appears that the coder expects to skip the first 512 bytes, and breaks if the data begins right away. (Note that this file resulted from exporting raw PICT data out of a resource file, which doesn't use the padding.)

(As an enhancement idea, it might be worthwhile to add an extra check to the coder to allow for this quirk, since Preview seems to do the same thing.)

**Comment by fmw42** [comment]
What was you exact command line? Did you use the inline: feature to read from a string or from a file?

What is your version of ImageMagick.

**Comment by cburschka** [comment]
This is reading from a regular file. The version is 7.0.7-22.

**Comment by fmw42** [comment]
I thought you said you tried to read the base64 data?

**Comment by cburschka** [comment]
Sorry, no, I just uploaded it as base64 for this issue to be able to put it in a gist; GitHub wasn't able to upload it. However, I now see that I could have attached a zip file instead.

**Comment by fmw42** [comment]
Sorry, I am confused. Did you export the base64 to a PICT in Preview and then ImageMagick would not open it?
