### ISSUE TITLE
identify: non-conforming drawing primitive definition `path' @ error/draw.c/DrawImage/3284.

### ISSUE THREAD

**Issue by mattcoady** [ImageMagick/ImageMagick#974]
### Description
Running identify on the following svg (see below) will return identify: non-conforming drawing primitive definition `path' @ error/draw.c/DrawImage/3284.

### Steps to Reproduce
This svg:
```
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 330 360">
  <defs>
    <path id="SVGID_1_" d="M166.3,7.4c-1.2,0-2.4,0-3.6,0c-10.4,0.2-20.9,1.3-26.9,3.8c-31.3,15.1-36.7,36.2-35.4,65.6"/>
  </defs>
  <clipPath id="SVGID_2_">
    <use xlink:href="#SVGID_1_"/>
  </clipPath>
  <path
    clip-path="url(#SVGID_2_)"
    d="M166.7 1.5S129-4.3 112.9 3.8c-7.3 3.7-12 11.7-15.5 19.1-5.2 11.2-6.8 36.4-6.8 36.4l15.9 11.4c.2-8.2 6.9-17.4 10.5-25.1 3.9-8.2 1.1-6.7 3.6-8.2 15.4-5.9 30.5-1 46 0 16.5 1.1 33.4-6.4 46 0 2.6 1.5 1.6-.6 3.6 8.2 1.6 6.8 12 18.8 10.5 25.1l15.9-11.4s-1.6-25.2-6.8-36.4c-3.4-7.4-8.2-15.4-15.5-19.1-15.9-8.1-53.6-2.3-53.6-2.3z"/>
</svg>
```
Run this:
```
 magick identify -verbose clipPath.svg
```
End of Output:
```
identify: non-conforming drawing primitive definition `path' @ error/draw.c/DrawImage/3284.
```

### System Configuration

- ImageMagick version: ImageMagick 7.0.7-22 Q16 x86_64 2018-01-22
- Environment (Operating system, version and so on): MacOS 10.13.2

**Comment by urban-warrior** [comment]
The internal ImageMagick SVG renderer is not fully compliant with the specification.  Instead we recommend you build ImageMagick with an alternative render, libRSVG, or inkscape.

**Comment by urban-warrior** [comment]
Recent releases of ImageMagick does not return the exception you experienced.

**Comment by Benjamin-Lee** [comment]
Still getting this:

    (env) Benjamins-MacBook-Pro:results BenjaminLee$ magick sg.svg sg.png
    magick: non-conforming drawing primitive definition `path' @ error/draw.c/DrawImage/4274.

**Comment by GBH** [comment]
```
MiniMagick::Error: `identify -format %[orientation] /var/folders/4j/398jj5xj3q76r52_8rw80n1m0000gn/T/ActiveStorage20191208-40819-tp8w08.svg[0]` failed with error:
identify: non-conforming drawing primitive definition `normal' @ error/draw.c/RenderMVGContent/3096.
identify: non-conforming drawing primitive definition `letter-spacing' @ error/draw.c/RenderMVGContent/4419.
```

```
Version: ImageMagick 7.0.9-7 Q16 x86_64 2019-12-01 https://imagemagick.org
```

**Comment by urban-warrior** [comment]
Can you post a link to ActiveStorage20191208-40819-tp8w08.svg?  We need to download it and reproduce the problem before we can offer a solution.  If it contains sensitive data, you could always obfuscate the data before you post it.

**Comment by GBH** [comment]
Sure:
[image.svg.zip](https://github.com/ImageMagick/ImageMagick/files/3937395/image.svg.zip)

I zipped it since Github doesn't support svg uploads.

For now work-around is to rebuild imagemagick with rsvg, but it's a pain after Homebrew decided to ditch options support for some reason.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ within a day or two.

**Comment by GBH** [comment]
Thank you @urban-warrior

**Comment by ahwitz** [comment]
Still able to reproduce with 
[this image (also ZIP'ed)](https://github.com/ImageMagick/ImageMagick/files/4301855/bulgarien.zip) on MacOS 10.14.6.

```
$ convert -resize 400x400 Bulgarien_04.svg Bulgarien_04.png
convert: non-conforming drawing primitive definition `path' @ error/draw.c/RenderMVGContent/4434.
$ convert --version
Version: ImageMagick 7.0.9-27 Q16 x86_64 2020-03-04 https://imagemagick.org
```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by fmw42** [comment]
Works fine for me on IM 7.0.9.27 Q16 Mac OSX, if you use proper IM 7 syntax. Use magick, not convert. Read the SVG before the -resize.

`magick Bulgarien_04.svg -resize 400x400 Bulgarien_04.png`

**Comment by urban-warrior** [comment]
The problem is related to the ImageMagick internal SVG renderer.  Our recent patch resolved the issue.

**Comment by shayanb** [comment]
I have the same issue on `Version: ImageMagick 7.0.10-7 Q16 x86_64 2020-04-20`

```
convert -flatten -geometry 1149x2550 -fuzz 10% -transparent white  -density 400   page0008_4.jpg 0008.svg 0008_out.pdf
convert: non-conforming drawing primitive definition `stroke-linecap' @ error/draw.c/RenderMVGContent/4434.
```

**Comment by fmw42** [comment]
Your syntax is not correct. Imagemagick 7 is not forgiving like Imagemagick 6. For Imagemagick 7, use magick, not convert. Place all operators (like -flatten) after reading the input. If the input is SVG or PDF, you should put -density or -colorspace before reading the input. Otherwise place all other settings or operators after reading the input. So perhaps you want:

`magick -density 400  page0008_4.jpg 0008.svg  -resize 1149x2550 -flatten -fuzz 10% -transparent white 0008_out.pdf`

It is generally not a good idea to use -geometry for resizing.

**Comment by shayanb** [comment]
@fmw42 thanks for the fast reply. I still get the same error with your suggested command:

`magick: non-conforming drawing primitive definition `stroke-linecap' @ error/draw.c/RenderMVGContent/4434.`

even the same with identify
```
    verbose: true
  Tainted: False
  Filesize: 49847B
  Number pixels: 500990
  Pixels per second: 35.4712MP
  User time: 0.120u
  Elapsed time: 0:01.014
  Version: ImageMagick 7.0.10-7 Q16 x86_64 2020-04-20 https://imagemagick.org
identify: non-conforming drawing primitive definition `stroke-linecap' @ error/draw.c/RenderMVGContent/4434.
```

**Comment by fmw42** [comment]
You may have some feature in your SVG file that your SVG renderer cannot handle. What do you get from 

magick -list format

for the end of the line for SVG. Does it say XML or RSVG? If the latter what is the version of RSVG. Do you have Inkscape on your system?

Run the following:

`magick -verbose 0008.svg x.gif`

what is returned?

**Comment by shayanb** [comment]
@fmw42  `magick -verbose 0008.svg x.gif` returns this:

```
'inkscape' '/var/folders/74/lzc0dg8j6lz55dvq2ts7lz6h0000gn/T/magick-26364fRrgzxtEmBN9' --export-png='/var/folders/74/lzc0dg8j6lz55dvq2ts7lz6h0000gn/T/magick-263647wL-mWMd51jZ.png' --export-dpi='96' --export-background='rgb(100%,100%,100%)' --export-background-opacity='1' > '/var/folders/74/lzc0dg8j6lz55dvq2ts7lz6h0000gn/T/magick-26364o39dUA9KUCr1' 2>&1
mvg:/var/folders/74/lzc0dg8j6lz55dvq2ts7lz6h0000gn/T/magick-263640z8o3MuJRVir=>/var/folders/74/lzc0dg8j6lz55dvq2ts7lz6h0000gn/T/magick-263640z8o3MuJRVir MVG 595x842 595x842+0+0 16-bit sRGB 49847B 0.130u 0:00.014
0008.svg MVG 595x842 595x842+0+0 16-bit sRGB 49847B 0.000u 0:00.000
magick: non-conforming drawing primitive definition `stroke-linecap' @ error/draw.c/RenderMVGContent/4434.
```

Here's the svg file (zipped): 
[0008.svz.zip](https://github.com/ImageMagick/ImageMagick/files/4524371/0008.svz.zip)

**Comment by fmw42** [comment]
Your file converts fine for me on IM 7.0.10.7 Q16 Mac OSX with Inkscape 0.92.4. Perhaps your Inkscape is old or buggy?  Check if there is a more current version.

**Comment by shayanb** [comment]
Sorry I didn't have Inkscape installed before, now I installed `Inkscape-1.0.0rc1` but still same error! 

The main thing I want to do is to convert and merge the background image and the svg together. Here's an example file of the two:

[Archive.zip](https://github.com/ImageMagick/ImageMagick/files/4525064/Archive.zip)

**Comment by fmw42** [comment]
You did have inkscape already. You installed a version 1.0 under development. The conversion of your SVG file works fine for me using IM 7.0.10.7 Q16 with Inkscape 0.92.4.

`magick 0009.svg 0009.gif`

works fine for me.  Does it not work for you?

If I use the Internal Imagemagick SVG renderer, I get

`magick MSVG:0009.svg 0009.gif`

magick: non-conforming drawing primitive definition `stroke-linecap' @ error/draw.c/RenderMVGContent/4434.

So I suspect you have not installed Inkscape in a way that Imagemagick can find it.  Put the path to Inkscape in your $PATH environment variable and try again with the first command above.
