### ISSUE TITLE
dcm.c: stream_info->offsets check for NULL

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#978]
While looking at #941, I noticed you added following check:

https://github.com/ImageMagick/ImageMagick/blob/master/coders/dcm.c#L3873

Nevertheless I do not see stream_info->offsets to be set to NULL anywhere. Might be that it is zeroed by the way somewhere, in that case sorry for noise.

**Comment by dlemstra** [comment]
The following line sets that value to zero: https://github.com/ImageMagick/ImageMagick/blob/master/coders/dcm.c#L3082.

```C#
(void) ResetMagickMemory(stream_info,0,sizeof(*stream_info));
```

This zeros the memory in the stream_info object and that will result in `stream_info->offsets` becoming null.

**Comment by pgajdos** [comment]
Opps, overlooked this. Thanks!
