### ISSUE TITLE
Irregular channel geometry not supported for JP2 file

### ISSUE THREAD

**Issue by coffeebite** [ImageMagick/ImageMagick#982]
I'm getting the following error when trying to `identify` a jp2 image: 

```
Error: Command failed: identify: irregular channel geometry not supported `/tmp/magick-81awDNqzdsPOyA' @ error/jp2.c/ReadJP2Image/398.
```

**Imagemagick version**: 7.0.7-22
**OS**: Debian
**Image**: https://padletartifacts.blob.core.windows.net/prod/2170bedb1cb44196b63c01ba012a3453/women-slalom.jpg

I've tried installing package `libopenjp2-7-dev`, package `libopenjpeg-dev`, and even installed openjpeg from source before I installed ImageMagick from source. None of these help.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
