### ISSUE TITLE
MagickAffineTransformImage is broken

### ISSUE THREAD

**Issue by chromia** [ImageMagick/ImageMagick#985]
### Description

MagickAffineTransformImage function in MagickWand does nothing entirely. All affine parameters are ignored.

### Steps to Reproduce

Example code in C/C++

```
#include <wand/magick-wand.h>
int main()
{
    MagickWand *image = NewMagickWand();
    MagickReadImage(image, "rose:");
    DrawingWand *drawing = NewDrawingWand();
    AffineMatrix affine;
    affine.sx = 2.0; affine.sy = 2.0; //scale x2
    affine.rx = 0.0; affine.ry = 0.0; //no rotate
    affine.tx = 0.0; affine.ty = 0.0; //no translate
    DrawAffine(drawing, &affine);
    MagickAffineTransformImage(image, drawing);
    MagickWriteImage(image, "output.png");	
    return 0;
}
```

I expect to obtain an image twice as large, but I got same as input.
The result does not change no matter how the parameter is changed.

### Cause of a Problem(Probably)

MagickAffineTransformImage(wand/magick-image.c) transforms an image using the matrix in drawing context.

```
MagickAffineTransformImage() transforms an image as dictated by the affine matrix of the drawing wand.
```

But in the function, the matrix is initialized(overwritten!) to identity matrix by 
PeekDrawingWand(wand/drawing-wand.c) and GetAffineMatrix(magick/draw.c).
My parameters are lost, and input image is cloned as output...
I think that this behavior is not as designed.

Related source code in my env:
https://github.com/ImageMagick/ImageMagick/blob/6.9.9-34/wand/magick-image.c#L596-L599
https://github.com/ImageMagick/ImageMagick/blob/6.9.9-34/wand/drawing-wand.c#L6791
https://github.com/ImageMagick/ImageMagick/blob/6.9.9-34/magick/draw.c#L4878-L4880

in master branch:
https://github.com/ImageMagick/ImageMagick/blob/master/MagickWand/magick-image.c#L547-L550
https://github.com/ImageMagick/ImageMagick/blob/master/MagickWand/drawing-wand.c#L6785
https://github.com/ImageMagick/ImageMagick/blob/master/MagickCore/draw.c#L4958-L4960

As an additional information, Magick::Image::affineTransform in Magick++ works perfectly.

### System Configuration

- ImageMagick version: ImageMagick 6.9.9-34 Q16 x64 2018-01-22
- Environment (Operating system, version and so on): Windows10 1709, Visual Studio 2017

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by chromia** [comment]
I checked that it works correctly in the beta version(both 6&7 series).
Thank you for the quick response!
