### ISSUE TITLE
montage.t fails completely (19/19)

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#992]
This is with 7.0.7-23, 7.0.7-22 was okay. All are failing for the same reason, for example:

```
$montage=$images->Montage( background=>'#696e7e',  tile=>'4x4', geometry=>'+0+0', mode=>'Unframe', shadow=>'False',
  borderwidth=>'0', background=>'gray' )
Invalid montage directory:
"#000000ÿ#008000ÿ#C0C0C0ÿ#00FF00ÿ#808080ÿ#808000ÿ#FFFFFFÿ#FFFF00ÿ#800000ÿ#000080ÿ#FF0000ÿ#0000FFÿ#800080ÿ#008080ÿ#FF00FFÿ#00FFFFÿ"
Expected:
"#000000
#008000
#C0C0C0
#00FF00
#808080
#808000
#FFFFFF
#FFFF00
#800000
#000080
#FF0000
#0000FF
#800080
#008080
#FF00FF
#00FFFF
"
not ok 19
```

How should I debug?

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
Now montage.t works, thanks.
