### ISSUE TITLE
PICT test of write.t does not pass

### ISSUE THREAD

**Issue by pgajdos** [ImageMagick/ImageMagick#994]
With 7.0.7-23, I get one more failure (in addition to montage.t I reported yesterday, which is now fixed):

```
Apple Macintosh QuickDraw/PICT file ...
ReadImage()
Image: PICT:input.pict, signatures do not match.
     Expected: f7b3db46d6f696ea8392f0ad0be945dd502a806e2c1e9c082efef517191758f7
     Computed: 646ac633d5b5553721e032d2c9f8f54ffc19d315832bbf808c2b7321b1067293
     Depth:    16
not ok 15
```

7.0.7-22 was okay. 

With 6.9.9-35 I get the same only failure, but with other checksums

```
Apple Macintosh QuickDraw/PICT file ...
ReadImage()
Image: PICT:input.pict, signatures do not match.
     Expected: a698f2fe0c6c31f83d19554a6ec02bac79c961dd9a87e7ed217752e75eb615d7
     Computed: 1252b2f3facc0fb67fcfacfc01938843566acbb9480bbe077a4c6f6af528eb4e
     Depth:    16
not ok 15
```

**Comment by pgajdos** [comment]
When I build 7.0.7-23 with 820e636 reverted, then test passes, i. e. computed checksum is the same as expected.

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick later today.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.

**Comment by pgajdos** [comment]
Thanks for quick response.
