### ISSUE TITLE
Drawing broken in IM6

### ISSUE THREAD

**Issue by jeroen** [ImageMagick/ImageMagick#996]
Drawing(in particular clipping) is broken in IM6 starting this commit: https://github.com/ImageMagick/ImageMagick/commit/b0fedf521831ed47127485339f279b1e91cf0df5

Below an example app. Compile with: `clang++ clip.cpp $(pkg-config --cflags --libs Magick++)`.

```cpp
#include <Magick++.h>

using namespace Magick;

#if MagickLibVersion >= 0x700
#define container vector
#else
#define container list
#endif

std::container<Drawable> clipbox(int x0, int y0, int x1, int y1){
  std::container<VPath> path;

  path.push_back(PathMovetoAbs(Coordinate(x0, y0)));
  path.push_back(PathLinetoAbs(Coordinate(x1, y0)));
  path.push_back(PathLinetoAbs(Coordinate(x1, y1)));
  path.push_back(PathLinetoAbs(Coordinate(x0, y1)));
  path.push_back(PathLinetoAbs(Coordinate(x0, y0)));

  std::container<Drawable> clipper;
  std::string id("mypath");
  clipper.push_back(DrawablePushClipPath(id));
  clipper.push_back(DrawablePath(path));
  clipper.push_back(DrawablePopClipPath());
  clipper.push_back(DrawableClipPath(id));
  return clipper;
}

int main(){
  Image image(Geometry(800, 600), Color("thistle"));
  image.magick("PNG");

  //Set clipbox
  image.draw(clipbox(100, 100, 700, 500));

  //Draw rectangle
  std::container<Drawable> rect;
  rect.push_back(DrawableStrokeColor("red"));
  rect.push_back(DrawableFillColor("pink"));
  rect.push_back(DrawableRectangle(0,0, 800, 600));
  image.draw(rect);

  //Set even smaller clipbox
  image.draw(clipbox(200, 200, 600, 400));


  //Draw line
  std::container<Drawable> line;
  line.push_back(DrawableStrokeColor("red"));
  line.push_back(DrawableStrokeWidth(10));
  line.push_back(DrawableLine(0, 0, 800, 600));
  image.draw(line);

  //reset clipbox
  image.draw(clipbox(0, 0, 800, 600));

  image.write(std::string("test.png"));
}

```

**Comment by urban-warrior** [comment]
Thanks for the problem report.  We can reproduce it and will have a patch to fix it in GIT master branch @ https://github.com/ImageMagick/ImageMagick within a day or two.  The patch will be available in the beta releases of ImageMagick @ http://www.imagemagick.org/download/beta/ within a day or two as well.

**Comment by jeroen** [comment]
Thanks. Will test this as soon as you push to github :)

**Comment by jeroen** [comment]
Thank you fix confirmed.

**Comment by jeroen** [comment]
Actually it's not fixed. The example is supposed to show this:

![test7](https://user-images.githubusercontent.com/216319/39868263-21e798d0-5459-11e8-9a5c-137fc8a52f25.png)

However in the master branch of IM6 we see this:

![test](https://user-images.githubusercontent.com/216319/39868293-41d3c8bc-5459-11e8-807a-25c48ffa521a.png)
