### ISSUE TITLE
encode to HEIF

### ISSUE THREAD

**Issue by AlisaFmla** [ImageMagick/ImageMagick#997]
Now ImageMagick support decode HEIF with decodeH265Image, thanks, and this is already everywhere, but there is no encode to HEIF anywhere. Why? Do please encode to HEIF with encodeH265Image!

**Comment by urban-warrior** [comment]
The primary ImageMagick developers are swamped.  If there is any hope of supporting a HEIC encoder, it will need to be a contribution from the ImageMagick user community.

**Comment by farindk** [comment]
HEIF writer based on libheif implemented in pull request #1099
